vsid: arch/gtk3/widgets/vsidcontrolwidget.c File Reference
vsidcontrolwidget.c File Reference
GTK3 control widget for VSID.
#include "vice.h"
#include <gtk/gtk.h>
#include "c64mem.h"
#include "debug.h"
#include "machine.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "psid.h"
#include "ui.h"
#include "uiactions.h"
#include "vice_gtk3.h"
#include "vsidstate.h"
#include "vsidtuneinfowidget.h"
#include "vsync.h"
#include "vsidcontrolwidget.h"
Data Structures
struct vsid_ctrl_button_s
Object containing icon, action ID and tooltip.
Macros
#define FFWD_SPEED 500
Emulation speed during fast forward.
Typedefs
typedef struct vsid_ctrl_button_s vsid_ctrl_button_t
Object containing icon, action ID and tooltip.
Enumerations
enum {
COL_SUBTUNE_PREVIOUS ,
COL_PLAY ,
COL_PAUSE ,
COL_STOP ,
COL_FFWD ,
COL_NEXT ,
COL_EJECT ,
COL_REPEAT ,
NUM_BUTTONS
}
Columns of the buttons.
enum {
BUTTON_PUSH ,
BUTTON_TOGGLE
}
Button types.
Functions
static void push_button_callback (GtkWidget *button, gpointer action)
Handler for 'clicked' event of push buttons.
static void toggle_button_callback (GtkWidget *button, gpointer action)
Handler for 'toggled' event of toggle buttons.
GtkWidget * vsid_control_widget_create (void)
Create widget with media buttons to control VSID playback.
void vsid_control_widget_set_tune_count (int n)
Set number of tunes.
void vsid_control_widget_set_tune_current (int n)
Set current tune.
void vsid_control_widget_set_tune_default (int n)
Set default tune.
void vsid_control_widget_set_progress (gdouble fraction)
Set tune progress bar value.
void vsid_control_widget_next_tune (void)
Play next tune.
void vsid_control_widget_set_repeat (gboolean enabled)
Set repeat of psid.
gboolean vsid_control_widget_get_repeat (void)
Get repeat/loop widget state.
void vsid_control_widget_set_state (vsid_control_t state)
Update control buttons toggled state.
Variables
static gulong button_handler_ids [NUM_BUTTONS]
Signal handler IDs for the buttons.
static GtkWidget * button_widgets [NUM_BUTTONS]
Push/toggle button widget references.
static GtkWidget * progress = NULL
Progress bar.
static gboolean repeat = FALSE
Internal repeat state.
static const vsid_ctrl_button_t buttons []
List of media control buttons.
Detailed Description
GTK3 control widget for VSID.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
FFWD_SPEED
#define FFWD_SPEED 500
Emulation speed during fast forward.
Typedef Documentation
vsid_ctrl_button_t
typedef struct vsid_ctrl_button_s vsid_ctrl_button_t
Object containing icon, action ID and tooltip.
Enumeration Type Documentation
anonymous enum
anonymous enum
Columns of the buttons.
Enumerator
COL_SUBTUNE_PREVIOUS
psid-subtune-previous
COL_PLAY
psid-play
COL_PAUSE
psid-pause
COL_STOP
psid-stop
COL_FFWD
psid-ffwd
COL_NEXT
psid-subtune-next
COL_EJECT
psid-load
COL_REPEAT
psid-loop-toggle
NUM_BUTTONS
number of buttons
anonymous enum
anonymous enum
Button types.
Enumerator
BUTTON_PUSH
normal push button (GtkButton)
BUTTON_TOGGLE
toggle button (GtkToggleButton)
Function Documentation
push_button_callback()
static void push_button_callback (GtkWidget * button, gpointer action) static
Handler for 'clicked' event of push buttons.
Trigger UI action.
Parameters
[in] button push button
[in] action action ID
Referenced by vsid_control_widget_create().
toggle_button_callback()
static void toggle_button_callback (GtkWidget * button, gpointer action) static
Handler for 'toggled' event of toggle buttons.
Trigger UI action.
Parameters
[in] button push button
[in] action action ID
Referenced by vsid_control_widget_create().
vsid_control_widget_create()
GtkWidget * vsid_control_widget_create (void)
Create widget with media buttons to control VSID playback.
Returns
GtkGrid
Referenced by vsid_main_widget_create().
vsid_control_widget_get_repeat()
gboolean vsid_control_widget_get_repeat (void)
Get repeat/loop widget state.
Returns
loop state
Referenced by psid_loop_toggle_action(), and vsid_tune_info_widget_update().
vsid_control_widget_next_tune()
void vsid_control_widget_next_tune (void)
Play next tune.
vsid_control_widget_set_progress()
void vsid_control_widget_set_progress (gdouble fraction)
Set tune progress bar value.
Parameters
[in] fraction amount to fill (0.0 - 1.0)
Referenced by vsid_tune_info_widget_update().
vsid_control_widget_set_repeat()
void vsid_control_widget_set_repeat (gboolean enabled)
Set repeat of psid.
Set internal repeat state and toggle button state
Parameters
[in] enabled repeat current psid
Referenced by psid_loop_toggle_action().
vsid_control_widget_set_state()
void vsid_control_widget_set_state (vsid_control_t state)
Update control buttons toggled state.
Parameters
[in] state player state
Referenced by play_current_tune(), psid_ffwd_action(), psid_pause_action(), psid_play_action(), psid_stop_action(), and ui_vsid_window_load_psid().
vsid_control_widget_set_tune_count()
void vsid_control_widget_set_tune_count (int n)
Set number of tunes.
Parameters
[in] n tune count
vsid_control_widget_set_tune_current()
void vsid_control_widget_set_tune_current (int n)
Set current tune.
Parameters
[in] n tune number
vsid_control_widget_set_tune_default()
void vsid_control_widget_set_tune_default (int n)
Set default tune.
Parameters
[in] n tune number
Variable Documentation
button_handler_ids
gulong button_handler_ids[NUM_BUTTONS] static
Signal handler IDs for the buttons.
Referenced by vsid_control_widget_create(), vsid_control_widget_set_repeat(), and vsid_control_widget_set_state().
button_widgets
GtkWidget* button_widgets[NUM_BUTTONS] static
Push/toggle button widget references.
Referenced by vsid_control_widget_create(), vsid_control_widget_set_repeat(), and vsid_control_widget_set_state().
buttons
const vsid_ctrl_button_t buttons[] static
Initial value:
= {
    { "media-skip-backward",
      ACTION_PSID_SUBTUNE_PREVIOUS,
      BUTTON_PUSH,
      "Select previous subtune" },
    { "media-playback-start",
      ACTION_PSID_PLAY,
      BUTTON_TOGGLE,
      "Play tune" },
    { "media-playback-pause",
      ACTION_PSID_PAUSE,
      BUTTON_TOGGLE,
      "Pause playback" },
    { "media-playback-stop",
      ACTION_PSID_STOP,
      BUTTON_PUSH,
      "Stop playback" },
    { "media-seek-forward",
      ACTION_PSID_FFWD,
      BUTTON_TOGGLE,
      "Fast forward" },
    { "media-skip-forward",
      ACTION_PSID_SUBTUNE_NEXT,
      BUTTON_PUSH,
      "Select next subtune" },
    { "media-eject",
      ACTION_PSID_LOAD,
      BUTTON_PUSH,
      "Load PSID file" },
    { "media-playlist-repeat",
      ACTION_PSID_LOOP_TOGGLE,
      BUTTON_TOGGLE,
      "Loop current subtune" },
    { NULL, 0, 0, NULL }
}
List of media control buttons.
Note
Keep this array and the COL_* enum synchronized!
Referenced by cart_image_widget_new(), create_dialog(), ui_do_drive_popup(), and vsid_control_widget_create().
progress
GtkWidget* progress = NULL static
Progress bar.
Referenced by vsid_control_widget_create(), and vsid_control_widget_set_progress().
repeat
gboolean repeat = FALSE static
Internal repeat state.
Since we toggle this state via a UI action that can be triggered both from the toggle button and a hotkey we keep track of the state here.
Referenced by construct_countdown(), construct_datablock(), vsid_control_widget_get_repeat(), and vsid_control_widget_set_repeat().