vsid: vdrive/vdrive-command.h File Reference
vdrive-command.h File Reference
#include "types.h"
Functions
void vdrive_command_init (void)
int vdrive_command_execute (struct vdrive_s *vdrive, const uint8_t *buf, unsigned int length)
called by vdrive-iec.c; return code not used
int vdrive_command_format (struct vdrive_s *vdrive, const char *disk_name)
int vdrive_command_validate (struct vdrive_s *vdrive)
int vdrive_command_set_error (struct vdrive_s *vdrive, int code, unsigned int track, unsigned int sector)
int vdrive_command_memory_read (struct vdrive_s *vdrive, const uint8_t *buf, uint16_t addr, unsigned int length)
int vdrive_command_memory_write (struct vdrive_s *vdrive, const uint8_t *buf, uint16_t addr, unsigned int length)
int vdrive_command_memory_exec (struct vdrive_s *vdrive, const uint8_t *buf, uint16_t addr, unsigned int length)
int vdrive_command_switch (struct vdrive_s *vdrive, int part)
void vdrive_command_return (struct vdrive_s *vdrive, int origpart)
int vdrive_command_switchtraverse (struct vdrive_s *vdrive, cbmdos_cmd_parse_plus_t *cmd)
Function Documentation
vdrive_command_execute()
int vdrive_command_execute (struct vdrive_s * vdrive, const uint8_t * buf, unsigned int length)
called by vdrive-iec.c; return code not used
< real 58
check for unabbreviated commands
check for abbreviated commands
Referenced by mon_drive_execute_disk_cmd(), and vdrive_iec_flush().
vdrive_command_format()
int vdrive_command_format (struct vdrive_s * vdrive, const char * disk_name)
Todo:
the cmd structure should just be created and passed to the format function
Referenced by vdrive_internal_format_disk_image().
vdrive_command_init()
void vdrive_command_init (void)
Referenced by vdrive_init().
vdrive_command_memory_exec()
int vdrive_command_memory_exec (vdrive_t * vdrive, const uint8_t * buf, uint16_t addr, unsigned int length)
Todo:
FIXME: This function doesn't need buf or length.
Referenced by fsdevice_flush(), and vdrive_command_memory().
vdrive_command_memory_read()
int vdrive_command_memory_read (struct vdrive_s * vdrive, const uint8_t * buf, uint16_t addr, unsigned int length)
< non-tde drive/image
Referenced by fsdevice_flush(), and vdrive_command_memory().
vdrive_command_memory_write()
int vdrive_command_memory_write (vdrive_t * vdrive, const uint8_t * buf, uint16_t addr, unsigned int length)
Todo:
FIXME: incomplete
< non-tde drive/image
< HD in ASCII for CMDHD
Referenced by fsdevice_flush(), and vdrive_command_memory().
vdrive_command_return()
void vdrive_command_return (struct vdrive_s * vdrive, int origpart)
Referenced by vdrive_command_block(), vdrive_command_chdir(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_format_internal(), vdrive_command_initialize(), vdrive_command_lockunlock(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_renameheader(), vdrive_command_renamepart(), vdrive_command_rmdir(), vdrive_command_scratch(), vdrive_command_u1a2b(), and vdrive_command_validate_internal().
vdrive_command_set_error()
int vdrive_command_set_error (struct vdrive_s * vdrive, int code, unsigned int track, unsigned int sector)
last_code = CBMDOS_IPE_OK;
Referenced by iec_close_sequential(), iec_open_read(), iec_open_read_directory(), iec_open_write(), iec_write_sequential(), vdrive_bam_allocate_chain(), vdrive_bam_allocate_chain_255(), vdrive_command_allocate_chain(), vdrive_command_block(), vdrive_command_chcmdpart(), vdrive_command_chpart(), vdrive_command_deletepart(), vdrive_command_execute(), vdrive_command_getpartinfo(), vdrive_command_memory(), vdrive_command_memory_exec(), vdrive_command_memory_read(), vdrive_command_memory_write(), vdrive_command_rmdir(), vdrive_command_scratch(), vdrive_command_time(), vdrive_command_u1a2b(), vdrive_command_validate(), vdrive_command_validate_worker(), vdrive_device_setup(), vdrive_iec_close(), vdrive_iec_open(), vdrive_iec_read(), vdrive_iec_write(), vdrive_rel_add_sector(), vdrive_rel_open(), vdrive_rel_open_new(), vdrive_rel_read(), vdrive_rel_record_max(), and vdrive_rel_write().
vdrive_command_switch()
int vdrive_command_switch (struct vdrive_s * vdrive, int part)
Referenced by vdrive_command_block(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_execute(), vdrive_command_format_internal(), vdrive_command_initialize(), vdrive_command_switchtraverse(), vdrive_command_u1a2b(), and vdrive_command_validate_internal().
vdrive_command_switchtraverse()
int vdrive_command_switchtraverse (struct vdrive_s * vdrive, cbmdos_cmd_parse_plus_t * cmd)
for CD: "CD:DIR" "CD/DIR" "CD/DIR/" "CD_" (<-) are acceptable
Referenced by vdrive_command_chdir(), vdrive_command_copy(), vdrive_command_lockunlock(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_renameheader(), vdrive_command_rmdir(), vdrive_command_scratch(), and vdrive_iec_open().
vdrive_command_validate()
int vdrive_command_validate (struct vdrive_s * vdrive)
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_command_format_worker(), and vdrive_command_validate_internal().