x128: arch/gtk3/video.c File Reference
video.c File Reference
Native GTK3 UI video stuff.
#include "vice.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "debug_gtk3.h"
#include "archdep.h"
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "palette.h"
#include "raster.h"
#include "resources.h"
#include "ui.h"
#include "videoarch.h"
Macros
#define VICE_DEBUG_NATIVE_GTK3
Enable extra debugging info.
Functions
int ui_set_aspect_mode (int mode, void *canvas)
Set <CHIP>AspectMode resource (integer)
int ui_set_aspect_ratio (double aspect, void *canvas)
Set <CHIP>AspectRatio resource (string)
int ui_set_glfilter (int val, void *canvas)
Set the display filter for scaling.
int ui_set_flipx (int val, void *canvas)
int ui_set_flipy (int val, void *canvas)
int ui_set_rotate (int val, void *canvas)
int ui_set_vsync (int val, void *canvas)
Set VSync resource (bool)
int video_arch_get_active_chip (void)
void video_arch_canvas_init (struct video_canvas_s *canvas)
Arch-specific initialization for a video canvas.
int video_arch_cmdline_options_init (void)
Initialize command line options for generic video resouces.
int video_arch_resources_init (void)
Initialize video-related resources.
void video_arch_resources_shutdown (void)
Clean up any memory held by arch-specific video resources.
char video_canvas_can_resize (video_canvas_t *canvas)
Query whether a canvas is resizable.
video_canvas_t * video_canvas_create (video_canvas_t *canvas, unsigned int *width, unsigned int *height, int mapped)
Create a new video_canvas_s.
void video_canvas_destroy (struct video_canvas_s *canvas)
Free a previously created video canvas and all its components.
void video_canvas_refresh (struct video_canvas_s *canvas, unsigned int xs, unsigned int ys, unsigned int xi, unsigned int yi, unsigned int w, unsigned int h)
Update the display on a video canvas to reflect the machine state.
void video_canvas_resize (struct video_canvas_s *canvas, char resize_canvas)
Update canvas size to match the draw buffer size requested by the emulation core.
void video_canvas_adjust_aspect_ratio (struct video_canvas_s *canvas)
React to changes of aspect ratio in the physical system.
int video_canvas_set_palette (struct video_canvas_s *canvas, struct palette_s *palette)
Assign a palette to the canvas.
int video_init (void)
Perform any frontend-specific initialization.
void video_shutdown (void)
Perform any frontend-specific uninitialization.
Variables
static log_t gtk3video_log = ((log_t)-1)
Log for Gtk3-native video messages.
Detailed Description
Native GTK3 UI video stuff.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
Macro Definition Documentation
VICE_DEBUG_NATIVE_GTK3
#define VICE_DEBUG_NATIVE_GTK3
Enable extra debugging info.
Function Documentation
ui_set_aspect_mode()
int ui_set_aspect_mode (int mode, void * canvas)
Set <CHIP>AspectMode resource (integer)
The display will be updated to reflect any changes this makes.
Called by the actual resource handler (do not call directly)
Parameters
[in] mode new value
[in] canvas extra parameter (canvas associated with this videochip)
Returns
0
Referenced by set_aspect_mode().
ui_set_aspect_ratio()
int ui_set_aspect_ratio (double aspect, void * canvas)
Set <CHIP>AspectRatio resource (string)
The display will be updated to reflect any changes this makes.
Called by the actual resource handler (do not call directly)
Parameters
[in] aspect new value
[in] canvas extra parameter (canvas associated with this videochip)
Returns
0
Referenced by set_aspect_ratio().
ui_set_flipx()
int ui_set_flipx (int val, void * canvas)
Referenced by set_flipx().
ui_set_flipy()
int ui_set_flipy (int val, void * canvas)
Referenced by set_flipy().
ui_set_glfilter()
int ui_set_glfilter (int val, void * canvas)
Set the display filter for scaling.
Parameters
val new filter (0: nearest, 1: bilinear, 2: bicubic)
[in] canvas canvas this applies to
Returns
0
Referenced by set_glfilter().
ui_set_rotate()
int ui_set_rotate (int val, void * canvas)
Referenced by set_rotate().
ui_set_vsync()
int ui_set_vsync (int val, void * canvas)
Set VSync resource (bool)
The display will be updated to reflect any changes this makes.
Parameters
[in] val new value
[in] canvas canvas this applies to
Returns
0
Referenced by set_vsync().
video_arch_canvas_init()
void video_arch_canvas_init (struct video_canvas_s * canvas)
Arch-specific initialization for a video canvas.
Parameters
[in,out] canvas The canvas being initialized
See also
video_canvas_create
Referenced by video_canvas_init().
video_arch_cmdline_options_init()
int video_arch_cmdline_options_init (void)
Initialize command line options for generic video resouces.
Returns
0 on success, < 0 on failure
Referenced by video_cmdline_options_init().
video_arch_get_active_chip()
int video_arch_get_active_chip (void)
Referenced by mem_get_screen_parameter().
video_arch_resources_init()
int video_arch_resources_init (void)
Initialize video-related resources.
Returns
0 on success, < on failure
Referenced by video_resources_init().
video_arch_resources_shutdown()
void video_arch_resources_shutdown (void)
Clean up any memory held by arch-specific video resources.
Referenced by video_resources_shutdown().
video_canvas_adjust_aspect_ratio()
void video_canvas_adjust_aspect_ratio (struct video_canvas_s * canvas)
React to changes of aspect ratio in the physical system.
Rescale and reposition the screen inside the canvas if the screen's size has been programatically changed.
For GTK3 this means we need to compute a new minimum size for our display windows.
Parameters
canvas The canvas whose widgets need their sizes updated.
Referenced by ui_trigger_resize().
video_canvas_can_resize()
char video_canvas_can_resize (video_canvas_t * canvas)
Query whether a canvas is resizable.
Parameters
canvas The canvas to query
Returns
TRUE if the canvas can be resized.
Referenced by video_viewport_resize().
video_canvas_create()
video_canvas_t * video_canvas_create (video_canvas_t * canvas, unsigned int * width, unsigned int * height, int mapped)
Create a new video_canvas_s.
Parameters
[in,out] canvas A freshly allocated canvas object.
[in] width Pointer to a width value. May be NULL if canvas size is not yet known.
[in] height Pointer to a height value. May be NULL if canvas size is not yet known.
mapped Unused.
Returns
The completely initialized canvas. The window that holds it will be visible in the UI at time of return.
Referenced by realize_canvas().
video_canvas_destroy()
void video_canvas_destroy (struct video_canvas_s * canvas)
Free a previously created video canvas and all its components.
Parameters
[in] canvas The canvas to destroy.
Referenced by raster_shutdown().
video_canvas_refresh()
void video_canvas_refresh (struct video_canvas_s * canvas, unsigned int xs, unsigned int ys, unsigned int xi, unsigned int yi, unsigned int w, unsigned int h)
Update the display on a video canvas to reflect the machine state.
Parameters
canvas The canvas to update.
xs A parameter to forward to video_canvas_render()
ys A parameter to forward to video_canvas_render()
xi X coordinate of the leftmost pixel to update
yi Y coordinate of the topmost pixel to update
w Width of the rectangle to update
h Height of the rectangle to update
Referenced by refresh_canvas(), and video_canvas_refresh_all().
video_canvas_resize()
void video_canvas_resize (struct video_canvas_s * canvas, char resize_canvas)
Update canvas size to match the draw buffer size requested by the emulation core.
Parameters
canvas The video canvas to update.
resize_canvas Ignored - the canvas will always resize.
Referenced by video_viewport_resize().
video_canvas_set_palette()
int video_canvas_set_palette (struct video_canvas_s * canvas, struct palette_s * palette)
Assign a palette to the canvas.
Parameters
canvas The canvas to update the palette
palette The new palette to assign
Returns
Zero on success, nonzero on failure
Referenced by perform_mode_change(), video_canvas_palette_set(), and video_canvas_resize().
video_init()
int video_init (void)
Perform any frontend-specific initialization.
Returns
0 on success, nonzero on failure
Referenced by main_program().
video_shutdown()
void video_shutdown (void)
Perform any frontend-specific uninitialization.
Referenced by cmdline_help(), and machine_shutdown().
Variable Documentation
gtk3video_log
log_t gtk3video_log = ((log_t)-1) static
Log for Gtk3-native video messages.
Referenced by video_init().