x128: diskimage.h File Reference
diskimage.h File Reference
#include <sys/types.h>
#include "types.h"
Data Structures
struct disk_image_s
union disk_image_s::media_u
struct disk_addr_s
Macros
#define D64_FILE_SIZE_35 174848
D64 image, 35 tracks.
#define D64_FILE_SIZE_35E (174848 + 683)
D64 image, 35 tracks with errors.
#define D67_FILE_SIZE 176640
D67 image, 35 tracks DOS1.
#define D71_FILE_SIZE 349696
D71 image, 70 tracks.
#define D71_FILE_SIZE_E (349696 + 1366)/* D71 image, 70 tracks with errors */
#define D81_FILE_SIZE 819200
D81 image, 80 tracks.
#define D81_FILE_SIZE_E 822400
D81 image, 80 tracks with errors.
#define D81_FILE_SIZE_81 829440
D81 image, 81 tracks (! sams as D1M)
#define D81_FILE_SIZE_81E 832680
D81 image, 81 tracks with errors (! sams as D1M)
#define D81_FILE_SIZE_82 839680
D81 image, 82 tracks.
#define D81_FILE_SIZE_82E 842960
D81 image, 82 tracks with errors.
#define D81_FILE_SIZE_83 849920
D81 image, 83 tracks.
#define D81_FILE_SIZE_83E 853240
D81 image, 83 tracks with errors.
#define D80_FILE_SIZE 533248
D80 image, 77 tracks.
#define D82_FILE_SIZE 1066496
D82 image, 77 tracks.
#define D1M_FILE_SIZE 829440
D1M image, 81 tracks.
#define D1M_FILE_SIZE_E 832680
D1M image, 81 tracks with errors.
#define D2M_FILE_SIZE 1658880
D2M image, 81 tracks.
#define D2M_FILE_SIZE_E 1665360
D2M image, 81 tracks with errors.
#define D4M_FILE_SIZE 3317760
D4M image, 81 tracks.
#define D4M_FILE_SIZE_E 3330720
D4M image, 81 tracks with errors.
#define D9090_FILE_SIZE (153*6*32*256)
D90 image, 153 tracks, 32 sectors, 6 heads.
#define D9060_FILE_SIZE (153*4*32*256)
D90 image, 153 tracks, 32 sectors, 4 heads.
#define DISK_IMAGE_DEVICE_FS 0
#define DISK_IMAGE_DEVICE_REAL 1
opencbm
#define DISK_IMAGE_DEVICE_RAW 2
#define DISK_IMAGE_TYPE_G64 100
#define DISK_IMAGE_TYPE_G71 101
#define DISK_IMAGE_TYPE_P64 200
#define DISK_IMAGE_TYPE_D64 1541
#define DISK_IMAGE_TYPE_D67 2040
#define DISK_IMAGE_TYPE_D71 1571
#define DISK_IMAGE_TYPE_D81 1581
#define DISK_IMAGE_TYPE_D80 8050
#define DISK_IMAGE_TYPE_D82 8250
#define DISK_IMAGE_TYPE_TAP 1531 /*! \todo FIXME: this is nonsense, rename and move elsewhere */
#define DISK_IMAGE_TYPE_D1M 1000
#define DISK_IMAGE_TYPE_D2M 2000
#define DISK_IMAGE_TYPE_D4M 4000
#define DISK_IMAGE_TYPE_DHD 4844
HD in ASCII for CMDHD.
#define DISK_IMAGE_TYPE_D90 9000
D9090/D9060.
Typedefs
typedef struct disk_image_s disk_image_t
typedef struct disk_addr_s disk_addr_t
Functions
void disk_image_init (void)
Initialization.
int disk_image_resources_init (void)
int disk_image_cmdline_options_init (void)
void disk_image_resources_shutdown (void)
void disk_image_fsimage_name_set (disk_image_t *image, const char *name)
Set disk image name.
const char * disk_image_fsimage_name_get (const disk_image_t *image)
Get disk image name.
void * disk_image_fsimage_fd_get (const disk_image_t *image)
Get file descriptor for image.
int disk_image_fsimage_create (const char *name, unsigned int type)
int disk_image_fsimage_create_dxm (const char *name, const char *diskname, unsigned int type)
int disk_image_fsimage_create_dhd (const char *name, const char *diskname, unsigned int type)
void disk_image_rawimage_name_set (disk_image_t *image, const char *name)
void disk_image_rawimage_driver_name_set (disk_image_t *image)
void disk_image_name_set (disk_image_t *image, const char *name)
const char * disk_image_name_get (const disk_image_t *image)
disk_image_t * disk_image_create (void)
void disk_image_destroy (disk_image_t *image)
void disk_image_media_create (disk_image_t *image)
void disk_image_media_destroy (disk_image_t *image)
int disk_image_open (disk_image_t *image)
int disk_image_close (disk_image_t *image)
int disk_image_read_sector (const disk_image_t *image, uint8_t *buf, const disk_addr_t *dadr)
int disk_image_write_sector (disk_image_t *image, const uint8_t *buf, const disk_addr_t *dadr)
int disk_image_check_sector (const disk_image_t *image, unsigned int track, unsigned int sector)
Check out of bound.
unsigned int disk_image_sector_per_track (unsigned int format, unsigned int track)
Get number of sectors for track in format.
unsigned int disk_image_raw_track_size (unsigned int format, unsigned int track)
Get the raw (GCR) track size.
unsigned int disk_image_gap_size (unsigned int format, unsigned int track)
unsigned int disk_image_header_gap_size (unsigned int format, unsigned int track)
Gap between header and sector.
unsigned int disk_image_sync_size (unsigned int format, unsigned int track)
length of a SYNC
int disk_image_read_image (const disk_image_t *image)
int disk_image_write_p64_image (const disk_image_t *image)
int disk_image_write_half_track (disk_image_t *image, unsigned int half_track, const struct disk_track_s *raw)
unsigned int disk_image_speed_map (unsigned int format, unsigned int track)
Speed zones.
void disk_image_attach_log (const disk_image_t *image, signed int lognum, unsigned int unit, unsigned int drive)
Log attachment of disk image.
void disk_image_detach_log (const disk_image_t *image, signed int lognum, unsigned int unit, unsigned int drive)
Log detachment of disk image.
off_t disk_image_size (const disk_image_t *image)
Macro Definition Documentation
D1M_FILE_SIZE
#define D1M_FILE_SIZE 829440
D1M image, 81 tracks.
D1M_FILE_SIZE_E
#define D1M_FILE_SIZE_E 832680
D1M image, 81 tracks with errors.
D2M_FILE_SIZE
#define D2M_FILE_SIZE 1658880
D2M image, 81 tracks.
D2M_FILE_SIZE_E
#define D2M_FILE_SIZE_E 1665360
D2M image, 81 tracks with errors.
D4M_FILE_SIZE
#define D4M_FILE_SIZE 3317760
D4M image, 81 tracks.
D4M_FILE_SIZE_E
#define D4M_FILE_SIZE_E 3330720
D4M image, 81 tracks with errors.
D64_FILE_SIZE_35
#define D64_FILE_SIZE_35 174848
D64 image, 35 tracks.
D64_FILE_SIZE_35E
#define D64_FILE_SIZE_35E (174848 + 683)
D64 image, 35 tracks with errors.
D67_FILE_SIZE
#define D67_FILE_SIZE 176640
D67 image, 35 tracks DOS1.
D71_FILE_SIZE
#define D71_FILE_SIZE 349696
D71 image, 70 tracks.
D71_FILE_SIZE_E
#define D71_FILE_SIZE_E (349696 + 1366)/* D71 image, 70 tracks with errors */
D80_FILE_SIZE
#define D80_FILE_SIZE 533248
D80 image, 77 tracks.
D81_FILE_SIZE
#define D81_FILE_SIZE 819200
D81 image, 80 tracks.
D81_FILE_SIZE_81
#define D81_FILE_SIZE_81 829440
D81 image, 81 tracks (! sams as D1M)
D81_FILE_SIZE_81E
#define D81_FILE_SIZE_81E 832680
D81 image, 81 tracks with errors (! sams as D1M)
D81_FILE_SIZE_82
#define D81_FILE_SIZE_82 839680
D81 image, 82 tracks.
D81_FILE_SIZE_82E
#define D81_FILE_SIZE_82E 842960
D81 image, 82 tracks with errors.
D81_FILE_SIZE_83
#define D81_FILE_SIZE_83 849920
D81 image, 83 tracks.
D81_FILE_SIZE_83E
#define D81_FILE_SIZE_83E 853240
D81 image, 83 tracks with errors.
D81_FILE_SIZE_E
#define D81_FILE_SIZE_E 822400
D81 image, 80 tracks with errors.
D82_FILE_SIZE
#define D82_FILE_SIZE 1066496
D82 image, 77 tracks.
D9060_FILE_SIZE
#define D9060_FILE_SIZE (153*4*32*256)
D90 image, 153 tracks, 32 sectors, 4 heads.
D9090_FILE_SIZE
#define D9090_FILE_SIZE (153*6*32*256)
D90 image, 153 tracks, 32 sectors, 6 heads.
DISK_IMAGE_DEVICE_FS
#define DISK_IMAGE_DEVICE_FS 0
DISK_IMAGE_DEVICE_RAW
#define DISK_IMAGE_DEVICE_RAW 2
DISK_IMAGE_DEVICE_REAL
#define DISK_IMAGE_DEVICE_REAL 1
opencbm
DISK_IMAGE_TYPE_D1M
#define DISK_IMAGE_TYPE_D1M 1000
DISK_IMAGE_TYPE_D2M
#define DISK_IMAGE_TYPE_D2M 2000
DISK_IMAGE_TYPE_D4M
#define DISK_IMAGE_TYPE_D4M 4000
DISK_IMAGE_TYPE_D64
#define DISK_IMAGE_TYPE_D64 1541
DISK_IMAGE_TYPE_D67
#define DISK_IMAGE_TYPE_D67 2040
DISK_IMAGE_TYPE_D71
#define DISK_IMAGE_TYPE_D71 1571
DISK_IMAGE_TYPE_D80
#define DISK_IMAGE_TYPE_D80 8050
DISK_IMAGE_TYPE_D81
#define DISK_IMAGE_TYPE_D81 1581
DISK_IMAGE_TYPE_D82
#define DISK_IMAGE_TYPE_D82 8250
DISK_IMAGE_TYPE_D90
#define DISK_IMAGE_TYPE_D90 9000
D9090/D9060.
DISK_IMAGE_TYPE_DHD
#define DISK_IMAGE_TYPE_DHD 4844
HD in ASCII for CMDHD.
DISK_IMAGE_TYPE_G64
#define DISK_IMAGE_TYPE_G64 100
DISK_IMAGE_TYPE_G71
#define DISK_IMAGE_TYPE_G71 101
DISK_IMAGE_TYPE_P64
#define DISK_IMAGE_TYPE_P64 200
DISK_IMAGE_TYPE_TAP
#define DISK_IMAGE_TYPE_TAP 1531 /*! \todo FIXME: this is nonsense, rename and move elsewhere */
Typedef Documentation
disk_addr_t
typedef struct disk_addr_s disk_addr_t
disk_image_t
typedef struct disk_image_s disk_image_t
Function Documentation
disk_image_attach_log()
void disk_image_attach_log (const disk_image_t * image, signed int lognum, unsigned int unit, unsigned int drive)
Log attachment of disk image.
Parameters
[in] image disk image attached
[in] lognum (unused)
[in] unit unit the image is attached to
Referenced by cmdhd_attach_image(), drive_image_attach(), fdc_attach_image(), pc8477_attach_image(), vdrive_attach_image(), and wd1770_attach_image().
disk_image_check_sector()
int disk_image_check_sector (const disk_image_t * image, unsigned int track, unsigned int sector)
Check out of bound.
Check if a (track, sector) is inside bounds for image
Parameters
[in] image disk image
[in] track track number
[in] sector sector number
Returns
bool
Referenced by bcopy_cmd(), bfill_cmd(), block_cmd(), bpoke_cmd(), bread_cmd(), bwrite_cmd(), chain_cmd(), fsimage_dxx_read_sector(), fsimage_dxx_write_half_track(), fsimage_dxx_write_sector(), fsimage_read_dxx_image(), print_side_sector_group(), vdrive_bam_allocate_chain(), vdrive_bam_allocate_chain_255(), vdrive_command_allocate_chain(), vdrive_command_validate_worker(), and vdrive_dir_free_chain().
disk_image_close()
int disk_image_close (disk_image_t * image)
Referenced by attach_disk_image(), close_disk_image(), detach_disk_image(), and vdrive_internal_close_disk_image().
disk_image_cmdline_options_init()
int disk_image_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
disk_image_create()
disk_image_t * disk_image_create (void)
Referenced by attach_disk_image(), and open_disk_image().
disk_image_destroy()
void disk_image_destroy (disk_image_t * image)
Referenced by attach_disk_image(), close_disk_image(), detach_disk_image_and_free(), and open_disk_image().
disk_image_detach_log()
void disk_image_detach_log (const disk_image_t * image, signed int lognum, unsigned int unit, unsigned int drive)
Log detachment of disk image.
Parameters
[in] image disk image detached
[in] lognum (unused)
[in] unit unit the image is detached from
Referenced by cmdhd_detach_image(), drive_image_detach(), fdc_detach_image(), pc8477_detach_image(), vdrive_detach_image(), and wd1770_detach_image().
disk_image_fsimage_create()
int disk_image_fsimage_create (const char * name, unsigned int type)
Referenced by cbmimage_create_image().
disk_image_fsimage_create_dhd()
int disk_image_fsimage_create_dhd (const char * name, const char * diskname, unsigned int type)
Referenced by cbmimage_create_dhd_image().
disk_image_fsimage_create_dxm()
int disk_image_fsimage_create_dxm (const char * name, const char * diskname, unsigned int type)
Referenced by cbmimage_create_dxm_image().
disk_image_fsimage_fd_get()
void * disk_image_fsimage_fd_get (const disk_image_t * image)
Get file descriptor for image.
Parameters
[in] image disk image
Returns
file descriptor
Referenced by vdrive_command_format().
disk_image_fsimage_name_get()
const char * disk_image_fsimage_name_get (const disk_image_t * image)
Get disk image name.
Parameters
[in] image disk image
Returns
disk image name
Referenced by file_system_get_disk_name().
disk_image_fsimage_name_set()
void disk_image_fsimage_name_set (disk_image_t * image, const char * name)
Set disk image name.
Parameters
[in,out] image disk image
[in] name disk image name
Referenced by attach_disk_image().
disk_image_gap_size()
unsigned int disk_image_gap_size (unsigned int format, unsigned int track)
Referenced by fsimage_create_gcr(), fsimage_create_p64(), and fsimage_read_dxx_image().
disk_image_header_gap_size()
unsigned int disk_image_header_gap_size (unsigned int format, unsigned int track)
Gap between header and sector.
Todo:
FIXME: is this correct ?
Referenced by fsimage_create_gcr(), fsimage_create_p64(), and fsimage_read_dxx_image().
disk_image_init()
void disk_image_init (void)
Initialization.
Referenced by machine_specific_init().
disk_image_media_create()
void disk_image_media_create (disk_image_t * image)
Referenced by attach_disk_image(), open_disk_image(), and vdrive_internal_open_fsimage().
disk_image_media_destroy()
void disk_image_media_destroy (disk_image_t * image)
Referenced by attach_disk_image(), close_disk_image(), detach_disk_image(), open_disk_image(), vdrive_internal_close_disk_image(), and vdrive_internal_open_fsimage().
disk_image_name_get()
const char * disk_image_name_get (const disk_image_t * image)
disk_image_name_set()
void disk_image_name_set (disk_image_t * image, const char * name)
Referenced by open_disk_image(), and vdrive_internal_open_fsimage().
disk_image_open()
int disk_image_open (disk_image_t * image)
Referenced by attach_disk_image(), open_disk_image(), and vdrive_internal_open_fsimage().
disk_image_raw_track_size()
unsigned int disk_image_raw_track_size (unsigned int format, unsigned int track)
Get the raw (GCR) track size.
Parameters
[in] format disk image format enumerator
[in] track track number
Returns
number of bytes for track
Referenced by fsimage_create_gcr(), fsimage_create_p64(), fsimage_gcr_read_half_track(), fsimage_p64_read_half_track(), fsimage_read_dxx_image(), and fsimage_read_gcr_image().
disk_image_rawimage_driver_name_set()
void disk_image_rawimage_driver_name_set (disk_image_t * image)
disk_image_rawimage_name_set()
void disk_image_rawimage_name_set (disk_image_t * image, const char * name)
disk_image_read_image()
int disk_image_read_image (const disk_image_t * image)
Referenced by drive_image_attach().
disk_image_read_sector()
int disk_image_read_sector (const disk_image_t * image, uint8_t * buf, const disk_addr_t * dadr)
Referenced by cmdhd_findbaselba(), drive_snapshot_write_image_module(), fdd_update_raw(), vdrive_read_sector(), and vdrive_read_sector_physical().
disk_image_resources_init()
int disk_image_resources_init (void)
Referenced by machine_resources_init().
disk_image_resources_shutdown()
void disk_image_resources_shutdown (void)
Referenced by machine_resources_shutdown().
disk_image_sector_per_track()
unsigned int disk_image_sector_per_track (unsigned int format, unsigned int track)
Get number of sectors for track in format.
Determines the number of sectors for a given track and disk image format.
Parameters
[in] format disk image type enumerator
[in] track track number
Returns
number of sectors or 0 on error
Referenced by fsimage_check_sector(), fsimage_create_gcr(), fsimage_create_p64(), fsimage_dxx_write_half_track(), fsimage_read_dxx_image(), unzip_cmd(), and vdrive_get_max_sectors().
disk_image_size()
off_t disk_image_size (const disk_image_t * image)
Referenced by cmdhd_attach_image().
disk_image_speed_map()
unsigned int disk_image_speed_map (unsigned int format, unsigned int track)
Speed zones.
Determine the speed zone for track in format
The speed zone determines the number of sectors containing in a track for a given image type. Speed zone 0 is closest to the disk center (containing the smallest number of sectors for a speed zone), 3 is farthest away (containing the largest number of sectors for a speed zone).
Parameters
[in] format disk image type enumerator
[in] track track number
Returns
speed zone (0-3)
Todo:
FIXME: what about 80 track D82s?
Todo:
FIXME: what about 40 track D71s?
Todo:
FIXME: is this correct?
Referenced by disk_image_gap_size(), disk_image_raw_track_size(), disk_image_sector_per_track(), fsimage_create_gcr(), fsimage_gcr_write_half_track(), and fsimage_p64_read_half_track().
disk_image_sync_size()
unsigned int disk_image_sync_size (unsigned int format, unsigned int track)
length of a SYNC
Todo:
FIXME: the value of 5 bytes for sync is also hardcoded in gcr.c
Todo:
FIXME: is this correct ?
Referenced by fsimage_create_gcr(), fsimage_create_p64(), and fsimage_read_dxx_image().
disk_image_write_half_track()
int disk_image_write_half_track (disk_image_t * image, unsigned int half_track, const struct disk_track_s * raw)
Referenced by drive_gcr_data_writeback().
disk_image_write_p64_image()
int disk_image_write_p64_image (const disk_image_t * image)
Referenced by drive_gcr_data_writeback_all(), and drive_image_detach().
disk_image_write_sector()
int disk_image_write_sector (disk_image_t * image, const uint8_t * buf, const disk_addr_t * dadr)
Referenced by drive_snapshot_read_image_module(), fdc_do_format_D20(), fdc_do_format_D40(), fdc_do_format_D80(), fdc_do_format_D90(), fdd_flush_raw(), vdrive_write_sector(), and vdrive_write_sector_physical().