vsid: arch/shared/archdep_file_size.c File Reference
archdep_file_size.c File Reference
Get size of an open file.
#include "vice.h"
#include "archdep_defs.h"
#include <stdio.h>
#include "archdep_fseeko.h"
#include "archdep_ftello.h"
#include "archdep_file_size.h"
Functions
off_t archdep_file_size (FILE *stream)
Detailed Description
Get size of an open file.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
archdep_file_size()
off_t archdep_file_size (FILE * stream)
Referenced by cmdhd_attach_image(), crc32_file(), disk_image_check_for_d1m(), disk_image_check_for_d2m(), disk_image_check_for_d4m(), disk_image_check_for_d64(), disk_image_check_for_d67(), disk_image_check_for_d71(), disk_image_check_for_d80(), disk_image_check_for_d81(), disk_image_check_for_d82(), disk_image_check_for_d90(), disk_image_check_for_dhd(), event_record_attach_in_list(), fsimage_read_p64_image(), fsimage_size(), network_server_connect_trap(), scsi_getmaxsize(), sysfile_load(), tap_close(), tap_open(), util_file_load(), and util_file_load_string().