vsid: drive/driverom.h File Reference
driverom.h File Reference
#include "types.h"
Macros
#define DRIVE_ROM1540_SIZE 0x4000
#define DRIVE_ROM1540_SIZE_EXPANDED 0x8000
#define DRIVE_ROM1541_SIZE 0x4000
#define DRIVE_ROM1541_SIZE_EXPANDED 0x8000
#define DRIVE_ROM1541II_SIZE 0x4000
#define DRIVE_ROM1541II_SIZE_EXPANDED 0x8000
#define DRIVE_ROM1551_SIZE 0x4000
#define DRIVE_ROM1570_SIZE 0x8000
#define DRIVE_ROM1571_SIZE 0x8000
#define DRIVE_ROM1571CR_SIZE 0x8000
#define DRIVE_ROM1581_SIZE 0x8000
#define DRIVE_ROM2000_SIZE 0x8000
#define DRIVE_ROM4000_SIZE 0x8000
#define DRIVE_ROMCMDHD_SIZE 0x4000
#define DRIVE_ROM2031_SIZE 0x4000
#define DRIVE_ROM1001_SIZE 0x4000
same as ROM8050 and ROM8250 !
#define DRIVE_ROM9000_SIZE 0x4000
#define DRIVE_ROM2040_SIZE 0x2000
#define DRIVE_ROM3040_SIZE 0x3000
#define DRIVE_ROM4040_SIZE 0x3000
#define DRIVE_ROM1001_NAME "dos1001-901887+8-01.bin"
1001 Images have the low and high part combined
#define DRIVE_ROM2031_NAME "dos2031-901484-03+05.bin"
2031 Images have the low and high part combined
#define DRIVE_ROM2040_NAME "dos2040-901468-06+07.bin"
2040 Images have the low and high parts combined
#define DRIVE_ROM3040_NAME "dos3040-901468-11-13.bin"
3040 Images have the three parts combined
#define DRIVE_ROM4040_NAME "dos4040-901468-14-16.bin"
4040 Images have the three parts combined
#define DRIVE_ROM9000_NAME "dos9000-300516+7-revC.bin"
90x0 Images have the low and high parts combined
#define DRIVE_ROM1540_NAME "dos1540-325302+3-01.bin"
154x Images have the low and high part combined
#define DRIVE_ROM1541_NAME "dos1541-325302-01+901229-05.bin"
#define DRIVE_ROM1541II_NAME "dos1541ii-251968-03.bin"
#define DRIVE_ROM1551_NAME "dos1551-318008-01.bin"
#define DRIVE_ROM1570_NAME "dos1570-315090-01.bin"
#define DRIVE_ROM1571_NAME "dos1571-310654-05.bin"
#define DRIVE_ROM1571CR_NAME "dos1571cr-318047-01.bin"
#define DRIVE_ROM1581_NAME "dos1581-318045-02.bin"
#define DRIVE_ROM2000_NAME "dos2000-cs-33cc6f.bin"
#define DRIVE_ROM4000_NAME "dos4000-fd-350022.bin"
#define DRIVE_ROMCMDHD_NAME "bootromCMDHD-v2-80.bin"
Functions
void driverom_init (void)
void driverom_initialize_traps (struct diskunit_context_s *drive)
int driverom_load (const char *resource_name, uint8_t *drive_rom, unsigned int *loaded, int min, int max, const char *name, unsigned int type, unsigned int *size)
int driverom_load_images (void)
int driverom_snapshot_write (struct snapshot_s *s, const struct drive_s *drive)
int driverom_snapshot_read (struct snapshot_s *s, struct drive_s *drive)
Macro Definition Documentation
DRIVE_ROM1001_NAME
#define DRIVE_ROM1001_NAME "dos1001-901887+8-01.bin"
1001 Images have the low and high part combined
DRIVE_ROM1001_SIZE
#define DRIVE_ROM1001_SIZE 0x4000
same as ROM8050 and ROM8250 !
DRIVE_ROM1540_NAME
#define DRIVE_ROM1540_NAME "dos1540-325302+3-01.bin"
154x Images have the low and high part combined
DRIVE_ROM1540_SIZE
#define DRIVE_ROM1540_SIZE 0x4000
DRIVE_ROM1540_SIZE_EXPANDED
#define DRIVE_ROM1540_SIZE_EXPANDED 0x8000
DRIVE_ROM1541_NAME
#define DRIVE_ROM1541_NAME "dos1541-325302-01+901229-05.bin"
DRIVE_ROM1541_SIZE
#define DRIVE_ROM1541_SIZE 0x4000
DRIVE_ROM1541_SIZE_EXPANDED
#define DRIVE_ROM1541_SIZE_EXPANDED 0x8000
DRIVE_ROM1541II_NAME
#define DRIVE_ROM1541II_NAME "dos1541ii-251968-03.bin"
DRIVE_ROM1541II_SIZE
#define DRIVE_ROM1541II_SIZE 0x4000
DRIVE_ROM1541II_SIZE_EXPANDED
#define DRIVE_ROM1541II_SIZE_EXPANDED 0x8000
DRIVE_ROM1551_NAME
#define DRIVE_ROM1551_NAME "dos1551-318008-01.bin"
DRIVE_ROM1551_SIZE
#define DRIVE_ROM1551_SIZE 0x4000
DRIVE_ROM1570_NAME
#define DRIVE_ROM1570_NAME "dos1570-315090-01.bin"
DRIVE_ROM1570_SIZE
#define DRIVE_ROM1570_SIZE 0x8000
DRIVE_ROM1571_NAME
#define DRIVE_ROM1571_NAME "dos1571-310654-05.bin"
DRIVE_ROM1571_SIZE
#define DRIVE_ROM1571_SIZE 0x8000
DRIVE_ROM1571CR_NAME
#define DRIVE_ROM1571CR_NAME "dos1571cr-318047-01.bin"
DRIVE_ROM1571CR_SIZE
#define DRIVE_ROM1571CR_SIZE 0x8000
DRIVE_ROM1581_NAME
#define DRIVE_ROM1581_NAME "dos1581-318045-02.bin"
DRIVE_ROM1581_SIZE
#define DRIVE_ROM1581_SIZE 0x8000
DRIVE_ROM2000_NAME
#define DRIVE_ROM2000_NAME "dos2000-cs-33cc6f.bin"
DRIVE_ROM2000_SIZE
#define DRIVE_ROM2000_SIZE 0x8000
DRIVE_ROM2031_NAME
#define DRIVE_ROM2031_NAME "dos2031-901484-03+05.bin"
2031 Images have the low and high part combined
DRIVE_ROM2031_SIZE
#define DRIVE_ROM2031_SIZE 0x4000
DRIVE_ROM2040_NAME
#define DRIVE_ROM2040_NAME "dos2040-901468-06+07.bin"
2040 Images have the low and high parts combined
DRIVE_ROM2040_SIZE
#define DRIVE_ROM2040_SIZE 0x2000
DRIVE_ROM3040_NAME
#define DRIVE_ROM3040_NAME "dos3040-901468-11-13.bin"
3040 Images have the three parts combined
DRIVE_ROM3040_SIZE
#define DRIVE_ROM3040_SIZE 0x3000
DRIVE_ROM4000_NAME
#define DRIVE_ROM4000_NAME "dos4000-fd-350022.bin"
DRIVE_ROM4000_SIZE
#define DRIVE_ROM4000_SIZE 0x8000
DRIVE_ROM4040_NAME
#define DRIVE_ROM4040_NAME "dos4040-901468-14-16.bin"
4040 Images have the three parts combined
DRIVE_ROM4040_SIZE
#define DRIVE_ROM4040_SIZE 0x3000
DRIVE_ROM9000_NAME
#define DRIVE_ROM9000_NAME "dos9000-300516+7-revC.bin"
90x0 Images have the low and high parts combined
DRIVE_ROM9000_SIZE
#define DRIVE_ROM9000_SIZE 0x4000
DRIVE_ROMCMDHD_NAME
#define DRIVE_ROMCMDHD_NAME "bootromCMDHD-v2-80.bin"
DRIVE_ROMCMDHD_SIZE
#define DRIVE_ROMCMDHD_SIZE 0x4000
Function Documentation
driverom_init()
void driverom_init (void)
Referenced by drive_init().
driverom_initialize_traps()
void driverom_initialize_traps (struct diskunit_context_s * drive)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
Referenced by drive_init(), drive_resources_type(), drive_snapshot_read_module(), driverom_load(), and set_drive_idling_method().
driverom_load()
int driverom_load (const char * resource_name, uint8_t * drive_rom, unsigned int * loaded, int min, int max, const char * name, unsigned int type, unsigned int * size)
Referenced by iecrom_load_1540(), iecrom_load_1541(), iecrom_load_1541ii(), iecrom_load_1570(), iecrom_load_1571(), iecrom_load_1581(), iecrom_load_2000(), iecrom_load_4000(), and iecrom_load_CMDHD().
driverom_load_images()
int driverom_load_images (void)
Referenced by drive_init().
driverom_snapshot_read()
int driverom_snapshot_read (struct snapshot_s * s, struct drive_s * drive)
< ASCII for HD
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< same as ROM8050 and ROM8250 !
< DOS 3.0 hard drive
Referenced by drive_snapshot_read_module().
driverom_snapshot_write()
int driverom_snapshot_write (struct snapshot_s * s, const struct drive_s * drive)