vsid: arch/gtk3/widgets/settings_ide64.c File Reference
settings_ide64.c File Reference
Settings widget to control IDE64 resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "cartridge.h"
#include "ide64.h"
#include "machine.h"
#include "resources.h"
#include "ui.h"
#include "vice_gtk3.h"
#include "settings_ide64.h"
Data Structures
struct geometry_spin_t
IDE64 geometry spin button data object.
Functions
static void on_usb_enable_toggled (GtkWidget *usb_enable, gpointer usb_address)
Handler for the "toggled" event of the USB Server check button.
static void on_autosize_toggled (GtkWidget *autodetect_enable, gpointer geometry_grid)
Handler for the "toggled" event of the "Autodetect Size" widgets.
static void on_digimax_toggled (GtkWidget *digimax_enable, gpointer digimax_address)
Handler for the "toggled" event of the "Enable DigiMAX" widget.
static GtkWidget * create_ide64_geometry_widget (int device)
Create grid with spin buttons for IDE64 disk geometry resources.
static GtkWidget * create_ide64_device_widget (int device)
Create widget to select HD image and set geometry.
static int create_ide64_revision_layout (GtkWidget *grid, int row)
Add IDE64 revision widgets to the main grid.
static int create_ide64_usb_layout (GtkWidget *grid, int row)
Add USB server widgets to the main grid.
static int create_ide64_clockport_layout (GtkWidget *grid, int row)
Add RTC/ClockPort widget to main grid.
static int create_ide64_shortbus_layout (GtkWidget *grid, int row)
Add ShortBus settings widgets to the main grid.
static int create_ide64_devices_layout (GtkWidget *grid, int row)
Add widgets for the IDE64 devices to the main grid.
GtkWidget * settings_ide64_widget_create (GtkWidget *parent)
Create widget to control IDE64 resources.
Variables
static const vice_gtk3_radiogroup_entry_t revisions []
List of IDE64 revisions.
static const vice_gtk3_combo_entry_int_t digimax_addresses []
List of ShortBus DIGIMAX I/O bases.
static const geometry_spin_t geometry_spins []
IDE64 geometry spin button data.
static GtkWidget * image_entry [IDE64_DEVICE_COUNT]
References to the HD image file chooser widgets.
Detailed Description
Settings widget to control IDE64 resources.
IDE64 settings widget
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_ide64_clockport_layout()
static int create_ide64_clockport_layout (GtkWidget * grid, int row) static
Add RTC/ClockPort widget to main grid.
Parameters
[in] grid main grid
[in] row row in grid to add widgets
Returns
row in grid for next widgets
Referenced by settings_ide64_widget_create().
create_ide64_device_widget()
static GtkWidget * create_ide64_device_widget (int device) static
Create widget to select HD image and set geometry.
Parameters
[in] device device number (1-4)
Returns
GtkGrid
Referenced by create_ide64_devices_layout().
create_ide64_devices_layout()
static int create_ide64_devices_layout (GtkWidget * grid, int row) static
Add widgets for the IDE64 devices to the main grid.
Add a stack and stack switcher with four stack children for each device.
Parameters
[in] grid main grid
[in] row row in grid to add widgets
Returns
row in grid for next widgets
Referenced by settings_ide64_widget_create().
create_ide64_geometry_widget()
static GtkWidget * create_ide64_geometry_widget (int device) static
Create grid with spin buttons for IDE64 disk geometry resources.
Parameters
[in] device IDE64 device number (1-4)
Returns
GtkGrid
Referenced by create_ide64_device_widget().
create_ide64_revision_layout()
static int create_ide64_revision_layout (GtkWidget * grid, int row) static
Add IDE64 revision widgets to the main grid.
Parameters
[in] grid main grid
[in] row row in grid to add widgets
Returns
row in grid for next widgets
< see http://www.ide64.org/
Referenced by settings_ide64_widget_create().
create_ide64_shortbus_layout()
static int create_ide64_shortbus_layout (GtkWidget * grid, int row) static
Add ShortBus settings widgets to the main grid.
Handles the SBDIGIMAX/SBDIGIMAXbase and SBETFE/SBETFEbase resources.
Parameters
[in] grid main grid
[in] row row in grid to add widgets
Returns
row for in grid for next widgets
< http://starbase.globalpc.net/~ezekowitz/vanessa/hobbies/projects.html
< http://starbase.globalpc.net/~ezekowitz/vanessa/hobbies/projects.html
Referenced by settings_ide64_widget_create().
create_ide64_usb_layout()
static int create_ide64_usb_layout (GtkWidget * grid, int row) static
Add USB server widgets to the main grid.
Parameters
[in] grid main grid
[in] row row in grid to add widgets
Returns
row in grid for next widgets
Referenced by settings_ide64_widget_create().
on_autosize_toggled()
static void on_autosize_toggled (GtkWidget * autodetect_enable, gpointer geometry_grid) static
Handler for the "toggled" event of the "Autodetect Size" widgets.
Parameters
[in] autodetect_enable autodetect enable check button
[in,out] geometry_grid geometry widgets grid
Referenced by create_ide64_device_widget().
on_digimax_toggled()
static void on_digimax_toggled (GtkWidget * digimax_enable, gpointer digimax_address) static
Handler for the "toggled" event of the "Enable DigiMAX" widget.
Parameters
[in] digimax_enable DigiMax enable check button
[in,out] digimax_address DigiMax address widget
Referenced by create_ide64_shortbus_layout().
on_usb_enable_toggled()
static void on_usb_enable_toggled (GtkWidget * usb_enable, gpointer usb_address) static
Handler for the "toggled" event of the USB Server check button.
Parameters
[in] usb_enable USB server check button
[in,out] usb_address USB server address widget
Referenced by create_ide64_usb_layout().
settings_ide64_widget_create()
GtkWidget * settings_ide64_widget_create (GtkWidget * parent)
Create widget to control IDE64 resources.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
Variable Documentation
digimax_addresses
const vice_gtk3_combo_entry_int_t digimax_addresses[] static
Initial value:
= {
    { "$DE40",  0xde40 },
    { "$DE48",  0xde48 },
    { NULL,     -1 }
}
List of ShortBus DIGIMAX I/O bases.
Referenced by create_ide64_shortbus_layout().
geometry_spins
const geometry_spin_t geometry_spins[] static
Initial value:
= {
    { "Cylinders", "IDE64cylinders%d", IDE64_CYLINDERS_MIN, IDE64_CYLINDERS_MAX, 256 },
    { "Heads",     "IDE64heads%d",     IDE64_HEADS_MIN,     IDE64_HEADS_MAX,       1 },
    { "Sectors",   "IDE64sectors%d",   IDE64_SECTORS_MIN,   IDE64_SECTORS_MAX,    16 }
}
IDE64 geometry spin button data.
Referenced by create_ide64_geometry_widget().
image_entry
GtkWidget* image_entry[IDE64_DEVICE_COUNT] static
References to the HD image file chooser widgets.
Referenced by create_ide64_device_widget().
revisions
const vice_gtk3_radiogroup_entry_t revisions[] static
Initial value:
= {
    { "Version 3",      IDE64_VERSION_3 },
    { "Version 4.1",    IDE64_VERSION_4_1 },
    { "Version 4.2",    IDE64_VERSION_4_2 },
    { NULL,             -1 }
}
List of IDE64 revisions.
Referenced by create_ide64_revision_layout().