vsid: c64/vsidmemsnapshot.c File Reference
vsidmemsnapshot.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "c64-resources.h"
#include "c64cart.h"
#include "c64mem.h"
#include "c64memrom.h"
#include "c64memsnapshot.h"
#include "c64pla.h"
#include "c64rom.h"
#include "cartridge.h"
#include "log.h"
#include "mem.h"
#include "resources.h"
#include "reu.h"
#include "georam.h"
#include "snapshot.h"
#include "types.h"
#include "uiapi.h"
#include "c64acia.h"
Macros
#define SNAP_ROM_MAJOR 0
#define SNAP_ROM_MINOR 0
#define SNAP_MAJOR 0
#define SNAP_MINOR 0
Functions
static int c64_snapshot_write_rom_module (snapshot_t *s)
static int c64_snapshot_read_rom_module (snapshot_t *s)
int c64_snapshot_write_module (snapshot_t *s, int save_roms)
int c64_snapshot_read_module (snapshot_t *s)
Variables
static log_t c64_snapshot_log = ((log_t)-1)
static const char snap_rom_module_name [] = "C64ROM"
static const char snap_mem_module_name [] = "C64MEM"
Macro Definition Documentation
SNAP_MAJOR
#define SNAP_MAJOR 0
SNAP_MINOR
#define SNAP_MINOR 0
SNAP_ROM_MAJOR
#define SNAP_ROM_MAJOR 0
SNAP_ROM_MINOR
#define SNAP_ROM_MINOR 0
Function Documentation
c64_snapshot_read_module()
int c64_snapshot_read_module (snapshot_t * s)
c64_snapshot_read_rom_module()
static int c64_snapshot_read_rom_module (snapshot_t * s) static
Todo:
FIXME: reset all cartridge stuff to standard C64 behaviour
Referenced by c64_snapshot_read_module().
c64_snapshot_write_module()
int c64_snapshot_write_module (snapshot_t * s, int save_roms)
c64_snapshot_write_rom_module()
static int c64_snapshot_write_rom_module (snapshot_t * s) static
Referenced by c64_snapshot_write_module().
Variable Documentation
c64_snapshot_log
log_t c64_snapshot_log = ((log_t)-1) static
Referenced by c64_snapshot_read_module(), and c64_snapshot_read_rom_module().
snap_mem_module_name
const char snap_mem_module_name[] = "C64MEM" static
Referenced by c64_snapshot_read_module(), and c64_snapshot_write_module().
snap_rom_module_name
const char snap_rom_module_name[] = "C64ROM" static
Referenced by c64_snapshot_read_rom_module(), and c64_snapshot_write_rom_module().