vsid: profiler.h File Reference
profiler.h File Reference
#include "types.h"
Functions
void profile_start (void)
resets sample statistics and starts profiling sample collection
void profile_stop (void)
stops profiling and writes profiling log to disk
void profile_sample_start (uint16_t pc)
called by the CPU for each instruction
void profile_sample_finish (uint16_t cycle_time, uint16_t stolen_cycles)
void profile_jsr (uint16_t pc_dst, uint16_t pc_src, uint8_t sp)
called whenever a JSR is encountered
void profile_int (uint16_t pc_dst, uint16_t handler, uint8_t sp, uint16_t cycle_time)
void profile_rtx (uint8_t sp)
called whenever an RTS/RI is called
void profile_shutdown (void)
Variables
bool maincpu_profiling
Function Documentation
profile_int()
void profile_int (uint16_t pc_dst, uint16_t handler, uint8_t sp, uint16_t cycle_time)
profile_jsr()
void profile_jsr (uint16_t pc_dst, uint16_t pc_src, uint8_t sp)
called whenever a JSR is encountered
profile_rtx()
void profile_rtx (uint8_t sp)
called whenever an RTS/RI is called
profile_sample_finish()
void profile_sample_finish (uint16_t cycle_time, uint16_t stolen_cycles)
Referenced by profile_int().
profile_sample_start()
void profile_sample_start (uint16_t pc)
called by the CPU for each instruction
Referenced by if(), and profile_int().
profile_shutdown()
void profile_shutdown (void)
Referenced by machine_shutdown().
profile_start()
void profile_start (void)
resets sample statistics and starts profiling sample collection
Referenced by mon_profile_action().
profile_stop()
void profile_stop (void)
stops profiling and writes profiling log to disk
Referenced by mon_profile_action().
Variable Documentation
maincpu_profiling
bool maincpu_profiling extern
Referenced by mon_profile(), mon_profile_action(), profile_int(), profile_start(), and profile_stop().