vsid: attach.h File Reference
attach.h File Reference
#include "types.h"
Macros
#define ATTACH_DEVICE_NONE 0
#define ATTACH_DEVICE_FS 1
filesystem
#define ATTACH_DEVICE_REAL 2
real IEC device (opencbm)
#define ATTACH_DEVICE_VIRT 4
3 was raw device
Functions
void file_system_init (void)
void file_system_shutdown (void)
int file_system_resources_init (void)
int file_system_cmdline_options_init (void)
const char * file_system_get_disk_name (unsigned int unit, unsigned int drive)
int file_system_attach_disk (unsigned int unit, unsigned int drive, const char *filename)
void file_system_detach_disk (unsigned int unit, unsigned int drive)
void file_system_detach_disk_all (void)
void file_system_detach_disk_shutdown (void)
struct vdrive_s * file_system_get_vdrive (unsigned int unit)
struct disk_image_s * file_system_get_image (unsigned int unit, unsigned int drive)
int file_system_bam_get_disk_id (unsigned int unit, unsigned int drive, uint8_t *id)
int file_system_bam_set_disk_id (unsigned int unit, unsigned int drive, uint8_t *id)
void file_system_event_playback (unsigned int unit, unsigned int drive, const char *filename)
Macro Definition Documentation
ATTACH_DEVICE_FS
#define ATTACH_DEVICE_FS 1
filesystem
ATTACH_DEVICE_NONE
#define ATTACH_DEVICE_NONE 0
ATTACH_DEVICE_REAL
#define ATTACH_DEVICE_REAL 2
real IEC device (opencbm)
ATTACH_DEVICE_VIRT
#define ATTACH_DEVICE_VIRT 4
3 was raw device
non-tde drive/image
Function Documentation
file_system_attach_disk()
int file_system_attach_disk (unsigned int unit, unsigned int drive, const char * filename)
Todo:
drive 1?
Referenced by autostart_disk(), autostart_prg_with_disk_image(), create_disk_image(), do_attach(), drive_snapshot_read_image_module(), fliplist_attach_head(), initcmdline_check_attach(), mon_attach(), on_drag_data_received(), set_attach_device_readonly(), try_attach_disk(), and ui_fliplist_select_cb().
file_system_bam_get_disk_id()
int file_system_bam_get_disk_id (unsigned int unit, unsigned int drive, uint8_t * id)
file_system_bam_set_disk_id()
int file_system_bam_set_disk_id (unsigned int unit, unsigned int drive, uint8_t * id)
file_system_cmdline_options_init()
int file_system_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
file_system_detach_disk()
void file_system_detach_disk (unsigned int unit, unsigned int drive)
Referenced by autostart_disk(), autostart_prg_with_virtual_fs(), drive_detach_action(), drive_resources_type(), drive_snapshot_read_image_module(), file_system_detach_disk_all(), mon_detach(), set_attach_device_readonly(), and try_attach_disk().
file_system_detach_disk_all()
void file_system_detach_disk_all (void)
Referenced by drive_detach_all_action(), and resources_set_defaults().
file_system_detach_disk_shutdown()
void file_system_detach_disk_shutdown (void)
< real IEC device (opencbm)
Referenced by cmdline_help(), and machine_shutdown().
file_system_event_playback()
void file_system_event_playback (unsigned int unit, unsigned int drive, const char * filename)
Referenced by event_alarm_handler(), event_playback_attach_image(), and event_playback_event_list().
file_system_get_disk_name()
const char * file_system_get_disk_name (unsigned int unit, unsigned int drive)
Referenced by attach_disk_image(), and set_attach_device_readonly().
file_system_get_image()
struct disk_image_s * file_system_get_image (unsigned int unit, unsigned int drive)
Referenced by autostart_disk(), dir_menu_popup_create(), try_attach_disk(), and ui_do_drive_popup().
file_system_get_vdrive()
struct vdrive_s * file_system_get_vdrive (unsigned int unit)
Referenced by autostart_prg(), autostart_prg_with_disk_image(), drive_resources_type(), file_system_attach_disk_internal(), file_system_detach_disk_all(), file_system_detach_disk_shutdown(), file_system_detach_disk_single(), file_system_get_disk_name(), file_system_get_image(), fsdevice_attach(), fsdrive_listentalk(), fsdrive_open(), fsdrive_read(), fsdrive_reset(), fsdrive_unlisten(), fsdrive_write(), mon_drive_block_cmd(), mon_drive_execute_disk_cmd(), mon_drive_list(), mon_file_open(), parallel_trap_attention(), parallel_trap_receivebyte(), parallel_trap_sendbyte(), parallelcommand(), serialcommand(), set_file_system_device(), vdrive_bam_get_disk_id(), vdrive_bam_set_disk_id(), vdrive_flush(), vdrive_refresh(), and vdrive_snapshot_module_write().
file_system_init()
void file_system_init (void)
< non-tde drive/image
< filesystem
< filesystem
< real IEC device (opencbm)
< real IEC device (opencbm)
Referenced by machine_init().
file_system_resources_init()
int file_system_resources_init (void)
Referenced by machine_resources_init().
file_system_shutdown()
void file_system_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().