x128: vdc/vdc.h File Reference
vdc.h File Reference
#include "types.h"
Macros
#define VDC_REVISION_0 0
8563 R7A
#define VDC_REVISION_1 1
8563 R8/R9
#define VDC_REVISION_2 2
8568
#define VDC_NUM_REVISIONS 3
#define VDC_16KB 0
#define VDC_64KB 1
Functions
int vdc_resources_init (void)
int vdc_cmdline_options_init (void)
struct raster_s * vdc_init (void)
Initialize the VDC emulation.
struct video_canvas_s * vdc_get_canvas (void)
void vdc_reset (void)
Reset the VDC chip.
void vdc_trigger_light_pen (CLOCK mclk)
Trigger the light pen.
CLOCK vdc_lightpen_timing (int x, int y)
Calculate lightpen pulse time based on x/y.
void vdc_prepare_for_snapshot (void)
void vdc_powerup (void)
This should put the VDC in the same state as powerup.
void vdc_resize (void)
void vdc_screenshot (struct screenshot_s *screenshot)
void vdc_async_refresh (struct canvas_refresh_s *r)
int vdc_write_snapshot_module (struct snapshot_s *s)
int vdc_read_snapshot_module (struct snapshot_s *s)
void vdc_set_canvas_refresh (int enable)
void vdc_shutdown (void)
Macro Definition Documentation
VDC_16KB
#define VDC_16KB 0
VDC_64KB
#define VDC_64KB 1
VDC_NUM_REVISIONS
#define VDC_NUM_REVISIONS 3
VDC_REVISION_0
#define VDC_REVISION_0 0
8563 R7A
VDC_REVISION_1
#define VDC_REVISION_1 1
8563 R8/R9
VDC_REVISION_2
#define VDC_REVISION_2 2
8568
Function Documentation
vdc_async_refresh()
void vdc_async_refresh (struct canvas_refresh_s * r)
Referenced by machine_canvas_async_refresh().
vdc_cmdline_options_init()
int vdc_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
vdc_get_canvas()
struct video_canvas_s * vdc_get_canvas (void)
Referenced by machine_canvas_async_refresh(), machine_screenshot(), and machine_video_canvas_get().
vdc_init()
struct raster_s * vdc_init (void)
Initialize the VDC emulation.
Referenced by machine_specific_init().
vdc_lightpen_timing()
CLOCK vdc_lightpen_timing (int x, int y)
Calculate lightpen pulse time based on x/y.
Referenced by machine_specific_init().
vdc_powerup()
void vdc_powerup (void)
This should put the VDC in the same state as powerup.
Referenced by vdc_init().
vdc_prepare_for_snapshot()
void vdc_prepare_for_snapshot (void)
vdc_read_snapshot_module()
int vdc_read_snapshot_module (struct snapshot_s * s)
vdc_reset()
void vdc_reset (void)
Reset the VDC chip.
Referenced by machine_specific_reset(), and vdc_powerup().
vdc_resize()
void vdc_resize (void)
vdc_resources_init()
int vdc_resources_init (void)
< VDC double size
< VDC double scan
Referenced by machine_resources_init().
vdc_screenshot()
void vdc_screenshot (struct screenshot_s * screenshot)
Referenced by machine_screenshot().
vdc_set_canvas_refresh()
void vdc_set_canvas_refresh (int enable)
Referenced by set_column4080_key().
vdc_shutdown()
void vdc_shutdown (void)
Referenced by machine_specific_shutdown().
vdc_trigger_light_pen()
void vdc_trigger_light_pen (CLOCK mclk)
Trigger the light pen.
Referenced by c128_trigger_light_pen().
vdc_write_snapshot_module()
int vdc_write_snapshot_module (struct snapshot_s * s)