x128: romset.c File Reference
romset.c File Reference
#include "vice.h"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "archdep.h"
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "romset.h"
#include "sysfile.h"
#include "types.h"
#include "util.h"
Data Structures
struct string_link_s
Macros
#define READ_ROM_LINE
Typedefs
typedef struct string_link_s string_link_t
Functions
int romset_resources_init (void)
void romset_resources_shutdown (void)
static int option_romsetfile (const char *value, void *extra_param)
static int option_romsetarchive (const char *value, void *extra_param)
static int option_romsetarchiveselect (const char *value, void *extra_param)
int romset_cmdline_options_init (void)
static char * prepend_dir_to_path (const char *dir)
static void restore_path (char *saved_path)
int romset_file_load (const char *filename)
int romset_file_save (const char *filename, const char *const *resource_list)
char * romset_file_list (const char *const *resource_list)
int romset_archive_load (const char *filename, int autostart)
int romset_archive_save (const char *filename)
char * romset_archive_list (void)
int romset_archive_item_save (const char *filename, const char *romset_name)
int romset_archive_item_select (const char *romset_name)
int romset_archive_item_create (const char *romset_name, const char *const *resource_list)
int romset_archive_item_delete (const char *romset_name)
void romset_archive_clear (void)
int romset_archive_get_number (void)
char * romset_archive_get_item (int number)
void romset_init (void)
Variables
static log_t romset_log = ((log_t)-2)
static const cmdline_option_t cmdline_options []
static int num_romsets = 0
static int array_size = 0
static string_link_t * romsets = NULL
static char * romset_dir
Macro Definition Documentation
READ_ROM_LINE
#define READ_ROM_LINE
Value:
    if ((bptr = fgets(buffer, 256, fp)) != NULL) { \
        line_num++; b = buffer;                    \
        while ((*b == ' ') || (*b == '\t')) {      \
            b++;                                   \
        }                                          \
    }
Typedef Documentation
string_link_t
typedef struct string_link_s string_link_t
Function Documentation
option_romsetarchive()
static int option_romsetarchive (const char * value, void * extra_param) static
option_romsetarchiveselect()
static int option_romsetarchiveselect (const char * value, void * extra_param) static
option_romsetfile()
static int option_romsetfile (const char * value, void * extra_param) static
prepend_dir_to_path()
static char * prepend_dir_to_path (const char * dir) static
Referenced by romset_archive_item_select(), and romset_file_load().
restore_path()
static void restore_path (char * saved_path) static
Referenced by romset_archive_item_select(), and romset_file_load().
romset_archive_clear()
void romset_archive_clear (void)
romset_archive_get_item()
char * romset_archive_get_item (int number)
romset_archive_get_number()
int romset_archive_get_number (void)
romset_archive_item_create()
int romset_archive_item_create (const char * romset_name, const char *const * resource_list)
Referenced by machine_romset_archive_item_create().
romset_archive_item_delete()
int romset_archive_item_delete (const char * romset_name)
romset_archive_item_save()
int romset_archive_item_save (const char * filename, const char * romset_name)
< write mode (text)
romset_archive_item_select()
int romset_archive_item_select (const char * romset_name)
Todo:
FIXME: Apparently there are no boundary checks!
Referenced by option_romsetarchiveselect(), and romset_archive_load().
romset_archive_list()
char * romset_archive_list (void)
Referenced by romset_archive_save().
romset_archive_load()
int romset_archive_load (const char * filename, int autostart)
< read mode (text)
Referenced by option_romsetarchive().
romset_archive_save()
int romset_archive_save (const char * filename)
< write mode (binary)
romset_cmdline_options_init()
int romset_cmdline_options_init (void)
Referenced by init_cmdline_options().
romset_file_list()
char * romset_file_list (const char *const * resource_list)
Referenced by machine_romset_file_list().
romset_file_load()
int romset_file_load (const char * filename)
< read mode (text)
Referenced by machine_romset_file_load(), on_load_romset_callback(), and option_romsetfile().
romset_file_save()
int romset_file_save (const char * filename, const char *const * resource_list)
< write mode (text)
Referenced by machine_romset_file_save(), and on_romset_save_callback().
romset_init()
void romset_init (void)
Referenced by init_main().
romset_resources_init()
int romset_resources_init (void)
Referenced by init_resources().
romset_resources_shutdown()
void romset_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
Variable Documentation
array_size
int array_size = 0 static
Referenced by romset_archive_clear(), romset_archive_item_create(), and romset_archive_load().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-romsetfile", CALL_FUNCTION,  (1 << 0) ,
      option_romsetfile, NULL, NULL, NULL,
      "<File>", "load the given romset file" },
    { "-romsetarchive", CALL_FUNCTION,  (1 << 0) ,
      option_romsetarchive, NULL, NULL, NULL,
      "<File>", "load the given romset archive" },
    { "-romsetarchiveselect", CALL_FUNCTION,  (1 << 0) ,
      option_romsetarchiveselect, NULL, NULL, NULL,
      "<Item number>", "select the given item from the current romset archive" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by romset_cmdline_options_init().
num_romsets
int num_romsets = 0 static
Referenced by romset_archive_clear(), romset_archive_get_item(), romset_archive_get_number(), romset_archive_item_create(), romset_archive_item_delete(), romset_archive_item_save(), romset_archive_item_select(), romset_archive_list(), and romset_archive_load().
romset_dir
char* romset_dir static
Referenced by romset_archive_clear(), romset_archive_item_select(), and romset_archive_load().
romset_log
log_t romset_log = ((log_t)-2) static
Referenced by romset_archive_item_save(), romset_archive_load(), romset_archive_save(), romset_file_load(), romset_file_save(), and romset_init().
romsets
string_link_t* romsets = NULL static
Referenced by romset_archive_clear(), romset_archive_get_item(), romset_archive_item_create(), romset_archive_item_delete(), romset_archive_item_save(), romset_archive_item_select(), romset_archive_list(), and romset_archive_load().