x128: arch/gtk3/widgets/settings_retroreplay.c File Reference
settings_retroreplay.c File Reference
Settings widget to control Retro Replay resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "c64cart.h"
#include "cartridge.h"
#include "clockportdevicewidget.h"
#include "vice_gtk3.h"
#include "settings_retroreplay.h"
Macros
#define CARTNAME CARTRIDGE_NAME_RETRO_REPLAY
Temporary define to ease typing and copy/paste.
Functions
static void save_filename_callback (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the save-dialog response handler.
static void on_save_clicked (GtkWidget *widget, gpointer user_data)
Handler for the 'clicked' event of the "Save As" button.
static void on_flush_clicked (GtkWidget *widget, gpointer user_data)
Handler for the 'clicked' event of the "Flush now" button.
static GtkWidget * create_label (const char *text)
Create left-align label.
static GtkWidget * create_switch (const char *resource)
Create GtkSwitch for a boolean resource.
GtkWidget * settings_retroreplay_widget_create (GtkWidget *parent)
Create widget to control Retro Replay resources.
Variables
static const vice_gtk3_combo_entry_int_t rr_revisions []
List of Retro Replay revisions.
Detailed Description
Settings widget to control Retro Replay resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Todo:
Check if the cartimagehelper can be used here to simplify the code for image selection and save/flush.
Macro Definition Documentation
CARTNAME
#define CARTNAME CARTRIDGE_NAME_RETRO_REPLAY
Temporary define to ease typing and copy/paste.
Function Documentation
create_label()
static GtkWidget * create_label (const char * text) static
Create left-align label.
Parameters
[in] text text for the label (uses Pango markup)
Returns
GtkLabel
Referenced by settings_retroreplay_widget_create().
create_switch()
static GtkWidget * create_switch (const char * resource) static
Create GtkSwitch for a boolean resource.
Create new GtkSwitch, left-aligned, centered vertically and non-expanding.
Parameters
[in] resource resource name
Returns
GtkSwitch
Referenced by settings_retroreplay_widget_create().
on_flush_clicked()
static void on_flush_clicked (GtkWidget * widget, gpointer user_data) static
Handler for the 'clicked' event of the "Flush now" button.
Parameters
[in] widget button
[in] user_data extra event data (unused)
< retroreplay.c
< see manual
Referenced by settings_retroreplay_widget_create().
on_save_clicked()
static void on_save_clicked (GtkWidget * widget, gpointer user_data) static
Handler for the 'clicked' event of the "Save As" button.
Parameters
[in] widget button
[in] user_data extra event data (unused)
< see manual
Referenced by settings_retroreplay_widget_create().
save_filename_callback()
static void save_filename_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the save-dialog response handler.
Parameters
[in,out] dialog save-file dialog
[in,out] filename filename
[in] data extra data (unused)
< retroreplay.c
< see manual
Referenced by on_save_clicked().
settings_retroreplay_widget_create()
GtkWidget * settings_retroreplay_widget_create (GtkWidget * parent)
Create widget to control Retro Replay resources.
Parameters
[in] parent parent widget
Returns
GtkGrid
< see manual
Variable Documentation
rr_revisions
const vice_gtk3_combo_entry_int_t rr_revisions[] static
Initial value:
= {
    {  "Retro Replay"  ,  RR_REV_RETRO_REPLAY },
    {  "Nordic Replay"  , RR_REV_NORDIC_REPLAY },
    { NULL,                         -1 }
}
List of Retro Replay revisions.
Referenced by settings_retroreplay_widget_create().