x128: arch/gtk3/ui.h File Reference
ui.h File Reference
Main Gtk3 UI code - header.
#include "vice.h"
#include <gtk/gtk.h>
#include "palette.h"
#include "types.h"
#include "videoarch.h"
Macros
#define NUM_WINDOWS 3
Number of GtkWindow's in the ui_resources.
#define UI_DRAG_TARGETS_COUNT 3
Number of drag-n-drop targets.
#define UNIT_DRIVE_TO_PTR(U, D) (vice_int_to_ptr(((U) << 8) | ((D) & 0xff)))
Encode unit and drive number for an attach/detach callback argument.
#define UNIT_FROM_PTR(P) ((vice_ptr_to_int(P) >> 8) & 0xff)
Convert pointer to unit number.
#define DRIVE_FROM_PTR(P) (vice_ptr_to_int(P) & 0xff)
Convert pointer to drive number.
Enumerations
enum {
PRIMARY_WINDOW ,
SECONDARY_WINDOW ,
MONITOR_WINDOW
}
Window indices.
enum {
DT_TEXT_PLAIN ,
DT_TEXT_URI ,
DT_TEXT_URI_LIST
}
Drag-n-drop 'target' mime types.
Functions
void ui_set_handle_dropped_files_func (int(*func)(const char *))
Prototypes.
void ui_set_create_window_func (void(*func)(video_canvas_t *))
Set function to help create the main window(s)
void ui_set_identify_canvas_func (int(*func)(video_canvas_t *))
Set function to identify a canvas from its video chip.
void ui_set_create_controls_widget_func (GtkWidget *(*func)(int))
Set function to help create the CRT controls widget(s)
void ui_create_main_window (video_canvas_t *canvas)
Create a toplevel window to represent a video canvas.
void ui_display_main_window (int index)
Makes a main window visible once it's been initialized.
void ui_destroy_main_window (int index)
Destroy a main window.
void ui_dispatch_events (void)
Not used.
void ui_exit (void)
Destroy UI resources (but NOT vice 'resources')
gboolean ui_is_fullscreen (void)
Checks if we're in fullscreen mode.
gboolean ui_is_fullscreen_from_canvas (const video_canvas_t *canvas)
Determine fullscreen state via canvas.
void ui_set_fullscreen_enabled (gboolean enabled)
Enable/disable fullscreen for current canvas.
gboolean ui_fullscreen_has_decorations (void)
Determine if the window should have decorations in fullscreen mode.
void ui_trigger_resize (void)
Updates UI in response to the simulated machine screen changing its dimensions or aspect ratio.
void ui_update_fullscreen_decorations (void)
Show or hide the decorations of the active main window as needed.
GtkWindow * ui_get_active_window (void)
Get the most recently focused toplevel window.
video_canvas_t * ui_get_active_canvas (void)
Get video canvas of active window.
video_canvas_t * ui_get_canvas_for_window (int index)
Get canvas by main window index.
int ui_set_aspect_mode (int mode, void *canvas)
Set <CHIP>AspectMode resource (integer)
int ui_set_aspect_ratio (double aspect, void *canvas)
Set <CHIP>AspectRatio resource (string)
int ui_set_glfilter (int val, void *canvas)
Set the display filter for scaling.
int ui_set_flipx (int val, void *canvas)
int ui_set_flipy (int val, void *canvas)
int ui_set_rotate (int val, void *canvas)
int ui_set_vsync (int val, void *canvas)
Set VSync resource (bool)
int ui_pause_active (void)
Get pause active state.
void ui_pause_enable (void)
Pause emulation.
bool ui_pause_loop_iteration (void)
Perform a single iteration of the pause loop.
void ui_pause_enter_monitor (void)
The pause loop should trigger the monitor.
void ui_pause_disable (void)
Unpause emulation.
void ui_pause_toggle (void)
Toggle pause state.
gboolean ui_action_toggle_show_statusbar (void)
Show/Hide statusbar of the active window.
void ui_update_lightpen (void)
Send current light pen state to the emulator core for all windows.
void ui_enable_crt_controls (int enabled)
Enable/disable CRT controls.
void ui_enable_mixer_controls (int enabled)
Enable/disable mixer controls.
GtkWidget * ui_get_window_by_index (int index)
Get GtkWindow instance by index.
int ui_get_window_index (GtkWidget *widget)
Get a window's index.
int ui_get_main_window_index (void)
Get the active main window's index.
GtkWidget * ui_get_main_window_by_index (gint index)
Get active main window.
gboolean ui_get_autostart_on_doubleclick (void)
void ui_set_window_geometries (void)
Set geometry of (both) emulated display window(s) from resources.
Variables
GtkTargetEntry ui_drag_targets [3]
List of drag targets for the drag-n-drop event handler.
Detailed Description
Main Gtk3 UI code - header.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
DRIVE_FROM_PTR
#define DRIVE_FROM_PTR (P) (vice_ptr_to_int(P) & 0xff)
Convert pointer to drive number.
Parameters
[in] P pointer obtained from UNIT_DRIVE_TO_PTR()
NUM_WINDOWS
#define NUM_WINDOWS 3
Number of GtkWindow's in the ui_resources.
UI_DRAG_TARGETS_COUNT
#define UI_DRAG_TARGETS_COUNT 3
Number of drag-n-drop targets.
UNIT_DRIVE_TO_PTR
#define UNIT_DRIVE_TO_PTR (U, D) (vice_int_to_ptr(((U) << 8) | ((D) & 0xff)))
Encode unit and drive number for an attach/detach callback argument.
Encodes unit and drive number into a value to be used as a data argument for event handlers.
Parameters
[in] U unit number (8-11)
[in] D drive number (0 or 1)
UNIT_FROM_PTR
#define UNIT_FROM_PTR (P) ((vice_ptr_to_int(P) >> 8) & 0xff)
Convert pointer to unit number.
Parameters
[in] P pointer obtained from UNIT_DRIVE_TO_PTR()
Enumeration Type Documentation
anonymous enum
anonymous enum
Window indices.
Enumerator
PRIMARY_WINDOW
primary window, all emulators
SECONDARY_WINDOW
secondary window, C128's VDC
MONITOR_WINDOW
optional monitor window/terminal
anonymous enum
anonymous enum
Drag-n-drop 'target' mime types.
Enumerator
DT_TEXT_PLAIN
"text/plain"
DT_TEXT_URI
"text/uri" - haven't seen this one (yet)
DT_TEXT_URI_LIST
"text/uri-list" - Windows Explorer / macOS Finder
Function Documentation
ui_action_toggle_show_statusbar()
gboolean ui_action_toggle_show_statusbar (void)
Show/Hide statusbar of the active window.
Toggle visibility of statusbar based on "${chip}HideStatusbar" resource.
Returns
TRUE (don't pass event along further)
ui_create_main_window()
void ui_create_main_window (video_canvas_t * canvas)
Create a toplevel window to represent a video canvas.
This function takes a video canvas structure and builds the widgets that will represent that canvas in the UI as a whole.
While it creates the widgets, it does not make them visible. The video canvas routines are expected to do any last-minute processing or preparation, and then call ui_display_main_window() when ready.
Parameters
[in] canvas the video_canvas_s to initialize
Warning
The order of the windows created for x128 depends on the order of the calls to vicii_init() and vdc_init() in src/c128/c128.c. That order is currently set to vicii before vdc so we get the proper window indexes. There has to be a better way.
Referenced by video_canvas_create(), and vsid_ui_init().
ui_destroy_main_window()
void ui_destroy_main_window (int index)
Destroy a main window.
Parameters
[in] index which window to destroy
See also
ui_resources_s::window_widget
Referenced by ui_exit().
ui_dispatch_events()
void ui_dispatch_events (void)
Not used.
Referenced by monitor_network_get_command_line(), and uimon_in().
ui_display_main_window()
void ui_display_main_window (int index)
Makes a main window visible once it's been initialized.
Parameters
[in] index which window to display
See also
ui_resources_s::window_widget
Referenced by video_canvas_create(), and vsid_ui_init().
ui_enable_crt_controls()
void ui_enable_crt_controls (int enabled)
Enable/disable CRT controls.
Parameters
[in] enabled enabled state for the CRT controls
Referenced by on_crt_toggled().
ui_enable_mixer_controls()
void ui_enable_mixer_controls (int enabled)
Enable/disable mixer controls.
Parameters
[in] enabled enabled state for the mixer controls
Referenced by on_mixer_toggled().
ui_exit()
void ui_exit (void)
Destroy UI resources (but NOT vice 'resources')
Don't call this directly except from main_exit();
Referenced by main_exit().
ui_fullscreen_has_decorations()
gboolean ui_fullscreen_has_decorations (void)
Determine if the window should have decorations in fullscreen mode.
Returns
bool
Referenced by fullscreen_decorations_toggle_action(), and ui_statusbar_set_visible_for_window().
ui_get_active_canvas()
video_canvas_t * ui_get_active_canvas (void)
Get video canvas of active window.
Returns
current active video canvas, or NULL
Referenced by on_save_screenshot_filename(), on_save_video_filename(), screenshot_ui_auto_screenshot(), ui_action_toggle_show_statusbar(), ui_is_fullscreen(), ui_set_fullscreen_enabled(), and ui_update_fullscreen_decorations().
ui_get_active_window()
GtkWindow * ui_get_active_window (void)
Get the most recently focused toplevel window.
Returns
pointer to a toplevel window, or NULL
Note
Not an event handler, needs to be moved
Referenced by cart_dialog_internal(), create_disk_attach_dialog(), create_sid_attach_dialog(), create_smart_attach_dialog(), create_tape_attach_dialog(), dialog_create_helper(), extendimage_dialog(), keyset_dialog_show(), on_icon_press(), on_launcher_clicked(), open_dialog_new(), restore_display_action(), save_dialog_new(), save_snapshot_dialog(), show_hotkey_dialog(), ui_about_dialog_show(), ui_action_toggle_show_statusbar(), ui_disk_create_dialog_show(), ui_fliplist_load_dialog_show(), ui_fliplist_save_dialog_show(), ui_media_dialog_show(), ui_set_fullscreen_enabled(), ui_tape_create_dialog_show(), uicmdline_dialog_show(), uicompiletimefeatures_dialog_show(), vice_gtk3_integer_input_box(), vice_gtk3_message_confirm(), vice_gtk3_message_error(), vice_gtk3_message_info(), vice_gtk3_open_create_file_dialog(), vice_gtk3_open_file_dialog(), vice_gtk3_save_file_dialog(), vice_gtk3_select_directory_dialog(), and vsid_playlist_add_dialog_create().
ui_get_autostart_on_doubleclick()
gboolean ui_get_autostart_on_doubleclick (void)
ui_get_canvas_for_window()
video_canvas_t * ui_get_canvas_for_window (int index)
Get canvas by main window index.
Parameters
[in] index window index (PRIMARY_WINDOW or SECONDARY_WINDOW)
Returns
video canvas or NULL on error
Referenced by actions_display_setup_ui(), border_mode_action(), show_statusbar_toggle_action(), and ui_statusbar_recreate_crt_controls().
ui_get_main_window_by_index()
GtkWidget * ui_get_main_window_by_index (gint index)
Get active main window.
Parameters
[in] index window index (PRIMARY WINDOW or SECONDARY_WINDOW)
Returns
window or NULL when index is out of bounds
Referenced by mouse_grab_toggle_action().
ui_get_main_window_index()
int ui_get_main_window_index (void)
Get the active main window's index.
Returns
index of a main emulator window
Referenced by fullscreen_toggle_action(), on_hide_vdc_toggled(), speed_cpu_custom_action(), speed_fps_custom_action(), ui_statusbar_get_recording_widget(), uimon_window_suspend_impl(), and video_arch_get_active_chip().
ui_get_window_by_index()
GtkWidget * ui_get_window_by_index (int index)
Get GtkWindow instance by index.
Parameters
[in] index index in the windows widgets array (0-2)
Returns
GtkWindow instance
Referenced by double_size_callback(), on_hide_vdc_toggled(), show_statusbar_secondary_toggle_action(), show_statusbar_toggle_action(), ui_mouse_grab_pointer(), ui_statusbar_recreate_crt_controls(), ui_statusbar_set_kbd_debug(), uimon_window_suspend_impl(), and warp().
ui_get_window_index()
int ui_get_window_index (GtkWidget * widget)
Get a window's index.
Parameters
[in] widget window to get the index of
Returns
window index, or -1 if not a main window
Referenced by on_focus_in_event(), and on_window_state_event().
ui_is_fullscreen()
gboolean ui_is_fullscreen (void)
Checks if we're in fullscreen mode.
Determines fullscreen state by inspecting the "${CHIP}Fullscreen" resource for the active canvas.
Returns
nonzero if we're in fullscreen mode
Todo:
FIXME: During emu boot the array ui_resources.canvas[] will not be properly initialized yet, so when the opengl renderer calls this function during a realize() call the references will still be NULL and we cannot access the chip name, and thus not access CHIPFullscreen.
Referenced by double_size_callback(), fullscreen_toggle_action(), on_window_state_event(), restore_display_action(), ui_statusbar_set_visible_for_window(), and ui_update_fullscreen_decorations().
ui_is_fullscreen_from_canvas()
gboolean ui_is_fullscreen_from_canvas (const video_canvas_t * canvas)
Determine fullscreen state via canvas.
Work around situations where ui_is_fullscreen() cannot be used.
Parameters
[in] canvas video canvas reference
Returns
non-0 if fullscreen is enabled
Referenced by on_widget_resized(), and ui_create_main_window().
ui_pause_active()
int ui_pause_active (void)
Get pause active state.
Returns
boolean
Referenced by actions_speed_setup_ui(), advance_frame_action(), create_pause_checkbox(), mon_exit(), mon_go(), monitor_open_action(), monitor_startup(), pause_toggle_action(), psid_pause_action(), speed_menu_popup_create(), statusbar_speed_widget_update(), ui_media_dialog_show(), ui_pause_toggle(), ui_settings_dialog_show(), ui_snapshot_load_snapshot(), ui_snapshot_save_snapshot(), and vice_opengl_on_ui_frame_clock().
ui_pause_disable()
void ui_pause_disable (void)
Unpause emulation.
Referenced by machine_reset_action(), monitor_startup(), on_dialog_destroy(), on_response(), pause_callback(), play_current_tune(), psid_ffwd_action(), psid_play_action(), psid_subtune_previous_action(), response_callback(), ui_pause_toggle(), ui_vsid_window_load_psid(), and vsyncarch_advance_frame().
ui_pause_enable()
void ui_pause_enable (void)
Pause emulation.
Referenced by advance_frame_action(), monitor_startup(), pause_callback(), response_callback(), ui_media_dialog_show(), ui_pause_toggle(), ui_settings_dialog_show(), and vsyncarch_postsync().
ui_pause_enter_monitor()
void ui_pause_enter_monitor (void)
The pause loop should trigger the monitor.
Referenced by monitor_open_action().
ui_pause_loop_iteration()
bool ui_pause_loop_iteration (void)
Perform a single iteration of the pause loop.
Returns
boolean whether to keep iterating
Referenced by monitor_startup(), and pause_loop().
ui_pause_toggle()
void ui_pause_toggle (void)
Toggle pause state.
Referenced by pause_toggle_action(), and psid_pause_action().
ui_set_aspect_mode()
int ui_set_aspect_mode (int mode, void * canvas)
Set <CHIP>AspectMode resource (integer)
The display will be updated to reflect any changes this makes.
Called by the actual resource handler (do not call directly)
Parameters
[in] mode new value
[in] canvas extra parameter (canvas associated with this videochip)
Returns
0
Referenced by set_aspect_mode().
ui_set_aspect_ratio()
int ui_set_aspect_ratio (double aspect, void * canvas)
Set <CHIP>AspectRatio resource (string)
The display will be updated to reflect any changes this makes.
Called by the actual resource handler (do not call directly)
Parameters
[in] aspect new value
[in] canvas extra parameter (canvas associated with this videochip)
Returns
0
Referenced by set_aspect_ratio().
ui_set_create_controls_widget_func()
void ui_set_create_controls_widget_func (GtkWidget *(*)(int) func)
Set function to help create the CRT controls widget(s)
Parameters
[in] func create CRT controls widget function
ui_set_create_window_func()
void ui_set_create_window_func (void(*)(video_canvas_t *) func)
Set function to help create the main window(s)
Parameters
[in] func create window function
Referenced by ui_machine_window_init(), and ui_vsid_window_init().
ui_set_flipx()
int ui_set_flipx (int val, void * canvas)
Referenced by set_flipx().
ui_set_flipy()
int ui_set_flipy (int val, void * canvas)
Referenced by set_flipy().
ui_set_fullscreen_enabled()
void ui_set_fullscreen_enabled (gboolean enabled)
Enable/disable fullscreen for current canvas.
Set the "${CHIP}Fullscreen" resource and enables or disables fullscreen mode for the main window of the current canvas.
Parameters
[in] enabled enable fullscreen
Referenced by fullscreen_toggle_action(), and on_window_state_event().
ui_set_glfilter()
int ui_set_glfilter (int val, void * canvas)
Set the display filter for scaling.
Parameters
val new filter (0: nearest, 1: bilinear, 2: bicubic)
[in] canvas canvas this applies to
Returns
0
Referenced by set_glfilter().
ui_set_handle_dropped_files_func()
void ui_set_handle_dropped_files_func (int(*)(const char *) func)
Prototypes.
Prototypes.
Parameters
[in] func handle dropped files function
Referenced by ui_vsid_window_init().
ui_set_identify_canvas_func()
void ui_set_identify_canvas_func (int(*)(video_canvas_t *) func)
Set function to identify a canvas from its video chip.
Parameters
[in] func identify canvas function
Referenced by vsid_ui_init().
ui_set_rotate()
int ui_set_rotate (int val, void * canvas)
Referenced by set_rotate().
ui_set_vsync()
int ui_set_vsync (int val, void * canvas)
Set VSync resource (bool)
The display will be updated to reflect any changes this makes.
Parameters
[in] val new value
[in] canvas canvas this applies to
Returns
0
Referenced by set_vsync().
ui_set_window_geometries()
void ui_set_window_geometries (void)
Set geometry of (both) emulated display window(s) from resources.
Attempt to set the size and position of the display window(s) from resources.
Referenced by settings_load_action(), and settings_load_filename_callback().
ui_trigger_resize()
void ui_trigger_resize (void)
Updates UI in response to the simulated machine screen changing its dimensions or aspect ratio.
Referenced by ui_set_aspect_mode(), and ui_set_aspect_ratio().
ui_update_fullscreen_decorations()
void ui_update_fullscreen_decorations (void)
Show or hide the decorations of the active main window as needed.
Todo:
FIXME: this function does not work properly for vsid and should never get called by it, but at least on Macs it can get called if the user clicks the fullscreen button in the main vsid window.
Referenced by fullscreen_decorations_toggle_action(), fullscreen_toggle_action(), on_window_state_event(), and ui_display_main_window().
ui_update_lightpen()
void ui_update_lightpen (void)
Send current light pen state to the emulator core for all windows.
Referenced by vsyncarch_presync().
Variable Documentation
ui_drag_targets
GtkTargetEntry ui_drag_targets[3] extern
List of drag targets for the drag-n-drop event handler.
It would appear different OS'es/WM's pass dropped files using various mime-types.
Referenced by ui_create_main_window(), and vsid_main_widget_create().