x128: snapshot.c File Reference
snapshot.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "types.h"
#include "uiapi.h"
#include "version.h"
#include "vsync.h"
#include "zfile.h"
#include "snapshot.h"
Data Structures
struct snapshot_module_s
struct snapshot_s
Macros
#define DBG(x)
#define SNAPSHOT_MAGIC_LEN 19
#define SNAPSHOT_VERSION_MAGIC_LEN 13
Functions
static int snapshot_write_byte (FILE *f, uint8_t data)
static int snapshot_write_word (FILE *f, uint16_t data)
static int snapshot_write_dword (FILE *f, uint32_t data)
static int snapshot_write_qword (FILE *f, uint64_t data)
static int snapshot_write_double (FILE *f, double data)
static int snapshot_write_padded_string (FILE *f, const char *s, uint8_t pad_char, int len)
static int snapshot_write_byte_array (FILE *f, const uint8_t *data, unsigned int num)
static int snapshot_write_word_array (FILE *f, const uint16_t *data, unsigned int num)
static int snapshot_write_dword_array (FILE *f, const uint32_t *data, unsigned int num)
static int snapshot_write_string (FILE *f, const char *s)
static int snapshot_read_byte (FILE *f, uint8_t *b_return)
static int snapshot_read_word (FILE *f, uint16_t *w_return)
static int snapshot_read_dword (FILE *f, uint32_t *dw_return)
static int snapshot_read_qword (FILE *f, uint64_t *qw_return)
static int snapshot_read_double (FILE *f, double *d_return)
static int snapshot_read_byte_array (FILE *f, uint8_t *b_return, unsigned int num)
static int snapshot_read_word_array (FILE *f, uint16_t *w_return, unsigned int num)
static int snapshot_read_dword_array (FILE *f, uint32_t *dw_return, unsigned int num)
static int snapshot_read_string (FILE *f, char **s)
int snapshot_module_write_byte (snapshot_module_t *m, uint8_t b)
int snapshot_module_write_word (snapshot_module_t *m, uint16_t w)
int snapshot_module_write_dword (snapshot_module_t *m, uint32_t dw)
int snapshot_module_write_qword (snapshot_module_t *m, uint64_t qw)
int snapshot_module_write_double (snapshot_module_t *m, double db)
int snapshot_module_write_padded_string (snapshot_module_t *m, const char *s, uint8_t pad_char, int len)
int snapshot_module_write_byte_array (snapshot_module_t *m, const uint8_t *b, unsigned int num)
int snapshot_module_write_word_array (snapshot_module_t *m, const uint16_t *w, unsigned int num)
int snapshot_module_write_dword_array (snapshot_module_t *m, const uint32_t *dw, unsigned int num)
int snapshot_module_write_string (snapshot_module_t *m, const char *s)
int snapshot_module_read_byte (snapshot_module_t *m, uint8_t *b_return)
int snapshot_module_read_word (snapshot_module_t *m, uint16_t *w_return)
int snapshot_module_read_dword (snapshot_module_t *m, uint32_t *dw_return)
int snapshot_module_read_qword (snapshot_module_t *m, uint64_t *qw_return)
int snapshot_module_read_double (snapshot_module_t *m, double *db_return)
int snapshot_module_read_byte_array (snapshot_module_t *m, uint8_t *b_return, unsigned int num)
int snapshot_module_read_word_array (snapshot_module_t *m, uint16_t *w_return, unsigned int num)
int snapshot_module_read_dword_array (snapshot_module_t *m, uint32_t *dw_return, unsigned int num)
int snapshot_module_read_string (snapshot_module_t *m, char **charp_return)
int snapshot_module_read_byte_into_int (snapshot_module_t *m, int *value_return)
int snapshot_module_read_byte_into_uint (snapshot_module_t *m, unsigned int *value_return)
int snapshot_module_read_word_into_int (snapshot_module_t *m, int *value_return)
int snapshot_module_read_word_into_uint (snapshot_module_t *m, unsigned int *value_return)
int snapshot_module_read_dword_into_ulong (snapshot_module_t *m, unsigned long *value_return)
int snapshot_module_read_dword_into_int (snapshot_module_t *m, int *value_return)
int snapshot_module_read_dword_into_uint (snapshot_module_t *m, unsigned int *value_return)
int snapshot_module_read_qword_into_int64 (snapshot_module_t *m, int64_t *value_return)
snapshot_module_t * snapshot_module_create (snapshot_t *s, const char *name, uint8_t major_version, uint8_t minor_version)
snapshot_module_t * snapshot_module_open (snapshot_t *s, const char *name, uint8_t *major_version_return, uint8_t *minor_version_return)
int snapshot_module_close (snapshot_module_t *m)
snapshot_t * snapshot_create (const char *filename, uint8_t major_version, uint8_t minor_version, const char *snapshot_machine_name)
snapshot_t * snapshot_open (const char *filename, uint8_t *major_version_return, uint8_t *minor_version_return, const char *snapshot_machine_name)
int snapshot_close (snapshot_t *s)
static void display_error_with_vice_version (char *text, char *filename)
void snapshot_display_error (void)
void snapshot_set_error (int error)
int snapshot_get_error (void)
int snapshot_version_is_equal (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version == required version
int snapshot_version_is_bigger (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version > required version
int snapshot_version_is_smaller (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version < required version
Variables
static int snapshot_error = 0
static char * current_module = NULL
static char read_name [16]
static char * current_machine_name = NULL
static char * current_filename = NULL
static size_t current_fpos = 0
static const char snapshot_magic_string [] = "VICE Snapshot File\032"
static const char snapshot_version_magic_string [] = "VICE Version\032"
static unsigned char snapshot_viceversion [4]
informal only, used by the error message created below
static uint32_t snapshot_vicerevision
Macro Definition Documentation
DBG
#define DBG (x)
SNAPSHOT_MAGIC_LEN
#define SNAPSHOT_MAGIC_LEN 19
SNAPSHOT_VERSION_MAGIC_LEN
#define SNAPSHOT_VERSION_MAGIC_LEN 13
Function Documentation
display_error_with_vice_version()
static void display_error_with_vice_version (char * text, char * filename) static
Referenced by snapshot_display_error().
snapshot_close()
int snapshot_close (snapshot_t * s)
Referenced by autostart_snapshot(), c128_snapshot_read(), c128_snapshot_write(), and event_playback_start_trap().
snapshot_create()
snapshot_t * snapshot_create (const char * filename, uint8_t major_version, uint8_t minor_version, const char * snapshot_machine_name)
< write mode (binary)
Referenced by c128_snapshot_write().
snapshot_display_error()
void snapshot_display_error (void)
Referenced by load_snapshot_filename_callback(), load_snapshot_trap(), quickload_snapshot_trap(), quicksave_snapshot_trap(), and save_snapshot_dialog().
snapshot_get_error()
int snapshot_get_error (void)
snapshot_module_close()
int snapshot_module_close (snapshot_module_t * m)
snapshot_module_create()
snapshot_module_t * snapshot_module_create (snapshot_t * s, const char * name, uint8_t major_version, uint8_t minor_version)
snapshot_module_open()
snapshot_module_t * snapshot_module_open (snapshot_t * s, const char * name, uint8_t * major_version_return, uint8_t * minor_version_return)
snapshot_module_read_byte()
int snapshot_module_read_byte (snapshot_module_t * m, uint8_t * b_return)
Referenced by snapshot_module_read_byte_into_int(), and snapshot_module_read_byte_into_uint().
snapshot_module_read_byte_array()
int snapshot_module_read_byte_array (snapshot_module_t * m, uint8_t * b_return, unsigned int num)
snapshot_module_read_byte_into_int()
int snapshot_module_read_byte_into_int (snapshot_module_t * m, int * value_return)
snapshot_module_read_byte_into_uint()
int snapshot_module_read_byte_into_uint (snapshot_module_t * m, unsigned int * value_return)
snapshot_module_read_double()
int snapshot_module_read_double (snapshot_module_t * m, double * db_return)
snapshot_module_read_dword()
int snapshot_module_read_dword (snapshot_module_t * m, uint32_t * dw_return)
Referenced by snapshot_module_read_dword_into_int(), snapshot_module_read_dword_into_uint(), and snapshot_module_read_dword_into_ulong().
snapshot_module_read_dword_array()
int snapshot_module_read_dword_array (snapshot_module_t * m, uint32_t * dw_return, unsigned int num)
snapshot_module_read_dword_into_int()
int snapshot_module_read_dword_into_int (snapshot_module_t * m, int * value_return)
snapshot_module_read_dword_into_uint()
int snapshot_module_read_dword_into_uint (snapshot_module_t * m, unsigned int * value_return)
snapshot_module_read_dword_into_ulong()
int snapshot_module_read_dword_into_ulong (snapshot_module_t * m, unsigned long * value_return)
snapshot_module_read_qword()
int snapshot_module_read_qword (snapshot_module_t * m, uint64_t * qw_return)
Referenced by snapshot_module_read_qword_into_int64().
snapshot_module_read_qword_into_int64()
int snapshot_module_read_qword_into_int64 (snapshot_module_t * m, int64_t * value_return)
snapshot_module_read_string()
int snapshot_module_read_string (snapshot_module_t * m, char ** charp_return)
snapshot_module_read_word()
int snapshot_module_read_word (snapshot_module_t * m, uint16_t * w_return)
Referenced by snapshot_module_read_word_into_int(), and snapshot_module_read_word_into_uint().
snapshot_module_read_word_array()
int snapshot_module_read_word_array (snapshot_module_t * m, uint16_t * w_return, unsigned int num)
snapshot_module_read_word_into_int()
int snapshot_module_read_word_into_int (snapshot_module_t * m, int * value_return)
snapshot_module_read_word_into_uint()
int snapshot_module_read_word_into_uint (snapshot_module_t * m, unsigned int * value_return)
snapshot_module_write_byte()
int snapshot_module_write_byte (snapshot_module_t * m, uint8_t b)
snapshot_module_write_byte_array()
int snapshot_module_write_byte_array (snapshot_module_t * m, const uint8_t * b, unsigned int num)
snapshot_module_write_double()
int snapshot_module_write_double (snapshot_module_t * m, double db)
snapshot_module_write_dword()
int snapshot_module_write_dword (snapshot_module_t * m, uint32_t dw)
snapshot_module_write_dword_array()
int snapshot_module_write_dword_array (snapshot_module_t * m, const uint32_t * dw, unsigned int num)
snapshot_module_write_padded_string()
int snapshot_module_write_padded_string (snapshot_module_t * m, const char * s, uint8_t pad_char, int len)
snapshot_module_write_qword()
int snapshot_module_write_qword (snapshot_module_t * m, uint64_t qw)
snapshot_module_write_string()
int snapshot_module_write_string (snapshot_module_t * m, const char * s)
snapshot_module_write_word()
int snapshot_module_write_word (snapshot_module_t * m, uint16_t w)
snapshot_module_write_word_array()
int snapshot_module_write_word_array (snapshot_module_t * m, const uint16_t * w, unsigned int num)
snapshot_open()
snapshot_t * snapshot_open (const char * filename, uint8_t * major_version_return, uint8_t * minor_version_return, const char * snapshot_machine_name)
< read mode (binary)
Referenced by autostart_snapshot(), c128_snapshot_read(), and event_playback_start_trap().
snapshot_read_byte()
static int snapshot_read_byte (FILE * f, uint8_t * b_return) static
Referenced by snapshot_module_open(), snapshot_module_read_byte(), snapshot_open(), snapshot_read_string(), and snapshot_read_word().
snapshot_read_byte_array()
static int snapshot_read_byte_array (FILE * f, uint8_t * b_return, unsigned int num) static
Referenced by snapshot_module_open(), snapshot_module_read_byte_array(), and snapshot_open().
snapshot_read_double()
static int snapshot_read_double (FILE * f, double * d_return) static
Referenced by snapshot_module_read_double().
snapshot_read_dword()
static int snapshot_read_dword (FILE * f, uint32_t * dw_return) static
Referenced by snapshot_module_open(), snapshot_module_read_dword(), snapshot_open(), snapshot_read_dword_array(), and snapshot_read_qword().
snapshot_read_dword_array()
static int snapshot_read_dword_array (FILE * f, uint32_t * dw_return, unsigned int num) static
Referenced by snapshot_module_read_dword_array().
snapshot_read_qword()
static int snapshot_read_qword (FILE * f, uint64_t * qw_return) static
Referenced by snapshot_module_read_qword().
snapshot_read_string()
static int snapshot_read_string (FILE * f, char ** s) static
Referenced by snapshot_module_read_string().
snapshot_read_word()
static int snapshot_read_word (FILE * f, uint16_t * w_return) static
Referenced by snapshot_module_read_word(), snapshot_read_dword(), snapshot_read_string(), and snapshot_read_word_array().
snapshot_read_word_array()
static int snapshot_read_word_array (FILE * f, uint16_t * w_return, unsigned int num) static
Referenced by snapshot_module_read_word_array().
snapshot_set_error()
void snapshot_set_error (int error)
snapshot_version_is_bigger()
int snapshot_version_is_bigger (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version > required version
snapshot_version_is_equal()
int snapshot_version_is_equal (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version == required version
snapshot_version_is_smaller()
int snapshot_version_is_smaller (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version < required version
snapshot_write_byte()
static int snapshot_write_byte (FILE * f, uint8_t data) static
Referenced by snapshot_create(), snapshot_module_create(), snapshot_module_write_byte(), snapshot_write_double(), snapshot_write_padded_string(), snapshot_write_string(), and snapshot_write_word().
snapshot_write_byte_array()
static int snapshot_write_byte_array (FILE * f, const uint8_t * data, unsigned int num) static
Referenced by snapshot_module_write_byte_array().
snapshot_write_double()
static int snapshot_write_double (FILE * f, double data) static
Referenced by snapshot_module_write_double().
snapshot_write_dword()
static int snapshot_write_dword (FILE * f, uint32_t data) static
Referenced by snapshot_create(), snapshot_module_close(), snapshot_module_create(), snapshot_module_write_dword(), snapshot_write_dword_array(), and snapshot_write_qword().
snapshot_write_dword_array()
static int snapshot_write_dword_array (FILE * f, const uint32_t * data, unsigned int num) static
Referenced by snapshot_module_write_dword_array().
snapshot_write_padded_string()
static int snapshot_write_padded_string (FILE * f, const char * s, uint8_t pad_char, int len) static
Referenced by snapshot_create(), snapshot_module_create(), and snapshot_module_write_padded_string().
snapshot_write_qword()
static int snapshot_write_qword (FILE * f, uint64_t data) static
Referenced by snapshot_module_write_qword().
snapshot_write_string()
static int snapshot_write_string (FILE * f, const char * s) static
Referenced by snapshot_module_write_string().
snapshot_write_word()
static int snapshot_write_word (FILE * f, uint16_t data) static
Referenced by snapshot_module_write_word(), snapshot_write_dword(), snapshot_write_string(), and snapshot_write_word_array().
snapshot_write_word_array()
static int snapshot_write_word_array (FILE * f, const uint16_t * data, unsigned int num) static
Referenced by snapshot_module_write_word_array().
Variable Documentation
current_filename
char* current_filename = NULL static
Referenced by snapshot_create(), snapshot_display_error(), and snapshot_open().
current_fpos
size_t current_fpos = 0 static
Referenced by snapshot_display_error(), snapshot_module_read_byte(), snapshot_module_read_byte_array(), snapshot_module_read_double(), snapshot_module_read_dword(), snapshot_module_read_dword_array(), snapshot_module_read_qword(), snapshot_module_read_string(), snapshot_module_read_word(), snapshot_read_byte(), snapshot_read_byte_array(), snapshot_read_double(), snapshot_read_dword(), snapshot_read_dword_array(), snapshot_read_qword(), snapshot_read_string(), snapshot_read_word(), snapshot_read_word_array(), snapshot_write_byte(), snapshot_write_byte_array(), snapshot_write_double(), snapshot_write_dword(), snapshot_write_dword_array(), snapshot_write_padded_string(), snapshot_write_qword(), snapshot_write_string(), snapshot_write_word(), and snapshot_write_word_array().
current_machine_name
char* current_machine_name = NULL static
Referenced by snapshot_display_error(), and snapshot_open().
current_module
char* current_module = NULL static
Referenced by snapshot_display_error(), snapshot_module_close(), snapshot_module_create(), snapshot_module_open(), and snapshot_open().
read_name
char read_name[16] static
Referenced by snapshot_display_error(), and snapshot_open().
snapshot_error
int snapshot_error = 0 static
Referenced by snapshot_close(), snapshot_create(), snapshot_display_error(), snapshot_get_error(), snapshot_module_close(), snapshot_module_create(), snapshot_module_open(), snapshot_module_read_byte(), snapshot_module_read_byte_array(), snapshot_module_read_double(), snapshot_module_read_dword(), snapshot_module_read_dword_array(), snapshot_module_read_qword(), snapshot_module_read_string(), snapshot_module_read_word(), snapshot_module_read_word_array(), snapshot_module_write_string(), snapshot_open(), snapshot_read_byte(), snapshot_read_byte_array(), snapshot_read_double(), snapshot_set_error(), snapshot_write_byte(), and snapshot_write_byte_array().
snapshot_magic_string
const char snapshot_magic_string[] = "VICE Snapshot File\032" static
Referenced by snapshot_create(), and snapshot_open().
snapshot_version_magic_string
const char snapshot_version_magic_string[] = "VICE Version\032" static
Referenced by snapshot_create(), and snapshot_open().
snapshot_vicerevision
uint32_t snapshot_vicerevision static
Referenced by display_error_with_vice_version(), and snapshot_open().
snapshot_viceversion
unsigned char snapshot_viceversion[4] static
informal only, used by the error message created below
Referenced by display_error_with_vice_version(), and snapshot_open().