vsid: drive/drivesync.h File Reference
drivesync.h File Reference
Functions
void drivesync_factor (struct diskunit_context_s *drv)
void drivesync_set_1571 (struct diskunit_context_s *drv, int new_sync)
void drivesync_set_4000 (struct diskunit_context_s *drv, int new_sync)
void drivesync_clock_frequency (struct diskunit_context_s *drive, unsigned int type)
Function Documentation
drivesync_clock_frequency()
void drivesync_clock_frequency (struct diskunit_context_s * drive, unsigned int type)
< ASCII for HD
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
Referenced by drive_init(), and drive_set_disk_drive_type().
drivesync_factor()
void drivesync_factor (struct diskunit_context_s * drv)
Referenced by drive_init(), drive_set_disk_drive_type(), drive_set_machine_parameter(), drivesync_set_1571(), and drivesync_set_4000().
drivesync_set_1571()
void drivesync_set_1571 (struct diskunit_context_s * drv, int new_sync)
Referenced by store_pra(), and undump_pra().
drivesync_set_4000()
void drivesync_set_4000 (struct diskunit_context_s * drv, int new_sync)
Referenced by pc8477_setup_context().