vsid: printerdrv/driver-select.h File Reference
driver-select.h File Reference
#include "types.h"
#include <stdbool.h>
Data Structures
struct driver_select_s
Printer driver data.
struct driver_select_list_s
Linked list node for printer driver data.
Macros
#define NUM_DRIVER_SELECT 4
same as NUM_OUTPUT_SELECT
#define DRIVER_FIRST_OPEN 0xFFFF
#define DRIVER_LAST_CLOSE 0xFFFF
Typedefs
typedef struct driver_select_s driver_select_t
Printer driver data.
typedef struct driver_select_list_s driver_select_list_t
Linked list node for printer driver data.
Functions
void driver_select_init (void)
int driver_select_init_resources (void)
int driver_select_userport_init_resources (void)
void driver_select_shutdown (void)
int driver_select_init_cmdline_options (void)
int driver_select_userport_init_cmdline_options (void)
void driver_select_register (driver_select_t *driver_select)
int driver_select (unsigned int prnr)
int driver_select_open (unsigned int prnr, unsigned int secondary)
void driver_select_close (unsigned int prnr, unsigned int secondary)
int driver_select_putc (unsigned int prnr, unsigned int secondary, uint8_t b)
int driver_select_getc (unsigned int prnr, unsigned int secondary, uint8_t *b)
int driver_select_flush (unsigned int prnr, unsigned int secondary)
int driver_select_formfeed (unsigned int prnr)
called by printer.c:printer_formfeed()
bool driver_select_is_printer (const char *drv_name)
Determine if drive is a printer driver.
bool driver_select_is_plotter (const char *drv_name)
Determine if driver is a plotter driver.
bool driver_select_has_iec_bus (const char *drv_name)
Determine if driver supports an IEC bus-connected device.
bool driver_select_has_ieee488_bus (const char *drv_name)
Determine if driver supports an IEEE-488 bus-connected device.
bool driver_select_has_userport (const char *drv_name)
Determine if driver supports a userport-connected device.
bool driver_select_has_text_output (const char *drv_name)
Determine if driver supports text output.
bool driver_select_has_graphics_output (const char *drv_name)
Determine if driver supports graphics output.
const driver_select_list_t * driver_select_get_drivers (void)
Get list of registered printer drivers.
Macro Definition Documentation
DRIVER_FIRST_OPEN
#define DRIVER_FIRST_OPEN 0xFFFF
DRIVER_LAST_CLOSE
#define DRIVER_LAST_CLOSE 0xFFFF
NUM_DRIVER_SELECT
#define NUM_DRIVER_SELECT 4
same as NUM_OUTPUT_SELECT
Typedef Documentation
driver_select_list_t
typedef struct driver_select_list_s driver_select_list_t
Linked list node for printer driver data.
driver_select_t
typedef struct driver_select_s driver_select_t
Printer driver data.
Function Documentation
driver_select()
int driver_select (unsigned int prnr)
Referenced by drv_ascii_init_resources(), drv_mps803_init_resources(), drv_nl10_init_resources(), and drv_raw_init_resources().
driver_select_close()
void driver_select_close (unsigned int prnr, unsigned int secondary)
Referenced by close_pr(), and userport_printer_enable().
driver_select_flush()
int driver_select_flush (unsigned int prnr, unsigned int secondary)
Referenced by flush_pr().
driver_select_formfeed()
int driver_select_formfeed (unsigned int prnr)
called by printer.c:printer_formfeed()
Referenced by printer_formfeed(), and printer_shutdown().
driver_select_get_drivers()
const driver_select_list_t * driver_select_get_drivers (void)
Get list of registered printer drivers.
Returns
singly-linked list of registered drivers
Referenced by printer_driver_widget_create().
driver_select_getc()
int driver_select_getc (unsigned int prnr, unsigned int secondary, uint8_t * b)
driver_select_has_graphics_output()
bool driver_select_has_graphics_output (const char * drv_name)
Determine if driver supports graphics output.
Parameters
[in] drv_name driver name
Returns
true if drv_name supports graphics output
Referenced by driver_radio_callback().
driver_select_has_iec_bus()
bool driver_select_has_iec_bus (const char * drv_name)
Determine if driver supports an IEC bus-connected device.
Parameters
[in] drv_name driver name
Returns
true if drv_name is an IEC driver
driver_select_has_ieee488_bus()
bool driver_select_has_ieee488_bus (const char * drv_name)
Determine if driver supports an IEEE-488 bus-connected device.
Parameters
[in] drv_name driver name
Returns
true if drv_name is an IEEE-488 driver
driver_select_has_text_output()
bool driver_select_has_text_output (const char * drv_name)
Determine if driver supports text output.
Parameters
[in] drv_name driver name
Returns
true if drv_name supports text output
Referenced by driver_radio_callback().
driver_select_has_userport()
bool driver_select_has_userport (const char * drv_name)
Determine if driver supports a userport-connected device.
Parameters
[in] drv_name driver name
Returns
true if drv_name is a userport driver
Referenced by printer_driver_widget_create(), and set_printer_driver().
driver_select_init()
void driver_select_init (void)
Referenced by printer_init().
driver_select_init_cmdline_options()
int driver_select_init_cmdline_options (void)
Referenced by printer_cmdline_options_init().
driver_select_init_resources()
int driver_select_init_resources (void)
Referenced by printer_resources_init().
driver_select_is_plotter()
bool driver_select_is_plotter (const char * drv_name)
Determine if driver is a plotter driver.
Parameters
[in] drv_name driver name
Returns
true if drv_name is a plotter driver
Referenced by printer_driver_widget_create(), and set_printer_driver().
driver_select_is_printer()
bool driver_select_is_printer (const char * drv_name)
Determine if drive is a printer driver.
Parameters
[in] drv_name driver name
Returns
true if drv_name is a printer driver
Referenced by printer_driver_widget_create(), and set_printer_driver().
driver_select_open()
int driver_select_open (unsigned int prnr, unsigned int secondary)
Referenced by open_pr(), and userport_printer_enable().
driver_select_putc()
int driver_select_putc (unsigned int prnr, unsigned int secondary, uint8_t b)
Referenced by userport_printer_store_pa2(), and write_pr().
driver_select_register()
void driver_select_register (driver_select_t * driver_select)
Referenced by drv_1520_init_resources(), drv_ascii_init_resources(), drv_mps803_init_resources(), drv_nl10_init_resources(), and drv_raw_init_resources().
driver_select_shutdown()
void driver_select_shutdown (void)
Referenced by printer_shutdown().
driver_select_userport_init_cmdline_options()
int driver_select_userport_init_cmdline_options (void)
Referenced by printer_userport_cmdline_options_init().
driver_select_userport_init_resources()
int driver_select_userport_init_resources (void)
Referenced by printer_userport_resources_init().