vsid: arch/gtk3/uistatusbar.h File Reference
uistatusbar.h File Reference
Gtk3 status bar - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
void ui_statusbar_init (void)
Initialize the status bar subsystem.
void ui_statusbar_shutdown (void)
Clean up any resources the statusbar system uses that weren't cleaned up when the status bars themselves were destroyed.
GtkWidget * ui_statusbar_create (int window_identity)
Create a new status bar.
gboolean ui_statusbar_set_visible_for_window (GtkWidget *window, gboolean visible)
Set visibility of the status bar for a main window.
gboolean ui_statusbar_crt_controls_enabled (GtkWidget *window)
Determine if the CRT controls widget is enabled in window.
gboolean ui_statusbar_mixer_controls_enabled (GtkWidget *window)
Determine if the mixer controls widget is enabled in window.
void ui_statusbar_recreate_crt_controls (void)
Recreate CRT controls on the status bars.
void ui_statusbar_set_kbd_debug_for_window (GtkWidget *window, gboolean state)
Show/hide the keyboard debugging widget on the status bar.
void ui_statusbar_set_kbd_debug (gboolean state)
Show/hide the keyboard debugging widget on the status bar.
void ui_statusbar_update_kbd_debug (GdkEvent *report)
Update status bar debug widget instances.
GtkWidget * ui_statusbar_get_recording_widget (void)
Get active 'Recording' widget.
int ui_statusbar_index_for_window (GtkWidget *window)
Get status bar index for window.
void ui_update_vsid_statusbar (void)
Update VSID-specific status bar.
void ui_update_statusbars (void)
Update status bars for non-VSID machines.
void warp_led_set_active (int bar, gboolean active)
Set Warp mode LED state.
void pause_led_set_active (int bar, gboolean active)
Set Pause LED state.
void shiftlock_led_set_active (int bar, gboolean active)
Set shiftlock LED state.
void mode4080_led_set_active (int bar, gboolean active)
Set 40/80 LED state.
void capslock_led_set_active (int bar, gboolean active)
Set capslock LED state.
void diagnosticpin_led_set_active (int bar, gboolean active)
Set PET userport diagnostic pin led state.
void supercpu_turbo_led_set_active (int bar, gboolean active)
Set SCPU64 turbo led state.
void supercpu_jiffy_led_set_active (int bar, gboolean active)
Set SCPU64 JiffyDOS LED state.
Detailed Description
Gtk3 status bar - header.
This header file only provides functionality that is exposed by the GTK3 statusbar API and that is not declared as part of some other, more general interface. Since the statusbar implementation is very self-contained that means this header file is extremely sparse.
Author
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
capslock_led_set_active()
void capslock_led_set_active (int bar, gboolean active)
Set capslock LED state.
Parameters
[in] bar status bar index
[in] active LED status
Referenced by statusbar_speed_widget_update().
diagnosticpin_led_set_active()
void diagnosticpin_led_set_active (int bar, gboolean active)
Set PET userport diagnostic pin led state.
Parameters
[in] bar status bar index
[in] active new state for led
Referenced by statusbar_speed_widget_update().
mode4080_led_set_active()
void mode4080_led_set_active (int bar, gboolean active)
Set 40/80 LED state.
Parameters
[in] bar status bar index
[in] active LED status
Referenced by statusbar_speed_widget_update().
pause_led_set_active()
void pause_led_set_active (int bar, gboolean active)
Set Pause LED state.
Parameters
[in] bar status bar index
[in] active LED status
Referenced by statusbar_speed_widget_update().
shiftlock_led_set_active()
void shiftlock_led_set_active (int bar, gboolean active)
Set shiftlock LED state.
Parameters
[in] bar status bar index
[in] active LED status
Referenced by statusbar_speed_widget_update().
supercpu_jiffy_led_set_active()
void supercpu_jiffy_led_set_active (int bar, gboolean active)
Set SCPU64 JiffyDOS LED state.
Parameters
[in] bar status bar index
[in] active new state for led
Referenced by jiffy_switch_callback(), and scpu_jiffy_switch_toggle_action().
supercpu_turbo_led_set_active()
void supercpu_turbo_led_set_active (int bar, gboolean active)
Set SCPU64 turbo led state.
Parameters
[in] bar status bar index
[in] active new state for led
Referenced by scpu_speed_switch_toggle_action(), and speed_switch_callback().
ui_statusbar_create()
GtkWidget * ui_statusbar_create (int window_identity)
Create a new status bar.
This function should be called once as part of creating a new machine window.
Parameters
[in] window_identity window identity
Returns
A new status bar, as a floating reference, or NULL if all possible status bars have been allocated already.
Referenced by ui_create_main_window().
ui_statusbar_crt_controls_enabled()
gboolean ui_statusbar_crt_controls_enabled (GtkWidget * window)
Determine if the CRT controls widget is enabled in window.
Parameters
[in] window GtkWindow instance
Returns
bool
Referenced by ui_update_fullscreen_decorations().
ui_statusbar_get_recording_widget()
GtkWidget * ui_statusbar_get_recording_widget (void)
Get active 'Recording' widget.
Returns
recording widget
Referenced by ui_media_stop_recording().
ui_statusbar_index_for_window()
int ui_statusbar_index_for_window (GtkWidget * window)
Get status bar index for window.
Parameters
[in] window GtkWindow instance
Returns
index or -1 on error
Referenced by ui_statusbar_crt_controls_enabled(), and ui_statusbar_mixer_controls_enabled().
ui_statusbar_init()
void ui_statusbar_init (void)
Initialize the status bar subsystem.
Warning
This function must be called before any call to ui_statusbar_create() and must not be called after any call to it.
Referenced by ui_init().
ui_statusbar_mixer_controls_enabled()
gboolean ui_statusbar_mixer_controls_enabled (GtkWidget * window)
Determine if the mixer controls widget is enabled in window.
Parameters
[in] window GtkWindow instance
Returns
bool
Referenced by ui_update_fullscreen_decorations().
ui_statusbar_recreate_crt_controls()
void ui_statusbar_recreate_crt_controls (void)
Recreate CRT controls on the status bars.
Destroy the old CRT controls and create new ones. To be called whenever the video standard changes.
Referenced by update_crt_controls().
ui_statusbar_set_kbd_debug()
void ui_statusbar_set_kbd_debug (gboolean state)
Show/hide the keyboard debugging widget on the status bar.
Show/hide the keyboard debugging widget on the status bar (of both windows in the case of x128).
Parameters
[in] state visible state
Note
Only call from a finalized UI.
Referenced by on_kbd_debug_toggled().
ui_statusbar_set_kbd_debug_for_window()
void ui_statusbar_set_kbd_debug_for_window (GtkWidget * window, gboolean state)
Show/hide the keyboard debugging widget on the status bar.
Show/hide the keyboard debugging widget on the status bar of a single window.
Parameters
[in] window main window instance
[in] state visible state
Referenced by ui_create_main_window().
ui_statusbar_set_visible_for_window()
gboolean ui_statusbar_set_visible_for_window (GtkWidget * window, gboolean visible)
Set visibility of the status bar for a main window.
Parameters
[in] window main window
[in] visible visibility of status bar for window
Returns
TRUE on success
Referenced by show_statusbar_secondary_toggle_action(), show_statusbar_toggle_action(), ui_action_toggle_show_statusbar(), and ui_init_finalize().
ui_statusbar_shutdown()
void ui_statusbar_shutdown (void)
Clean up any resources the statusbar system uses that weren't cleaned up when the status bars themselves were destroyed.
Referenced by ui_shutdown().
ui_statusbar_update_kbd_debug()
void ui_statusbar_update_kbd_debug (GdkEvent * report)
Update status bar debug widget instances.
Parameters
[in] report Gdk key event
Note
Can only be called from the UI thread.
Referenced by kbd_event_handler().
ui_update_statusbars()
void ui_update_statusbars (void)
Update status bars for non-VSID machines.
Todo:
Don't call this for each top level window as it updates all statusbars
Todo:
Another LED for dual drive
Referenced by vice_opengl_on_ui_frame_clock().
ui_update_vsid_statusbar()
void ui_update_vsid_statusbar (void)
Update VSID-specific status bar.
Referenced by on_frame_clock_update().
warp_led_set_active()
void warp_led_set_active (int bar, gboolean active)
Set Warp mode LED state.
Parameters
[in] bar status bar index
[in] active LED status
Referenced by statusbar_speed_widget_update().