vsid: arch/gtk3/actions-speed.c File Reference
actions-speed.c File Reference
UI action implementations for speed-related settings.
#include "vice.h"
#include <gtk/gtk.h>
#include <stddef.h>
#include <stdbool.h>
#include "basedialogs.h"
#include "debug_gtk3.h"
#include "hotkeys.h"
#include "machine.h"
#include "resources.h"
#include "ui.h"
#include "uiactions.h"
#include "uimenu.h"
#include "vsync.h"
#include "vsyncapi.h"
#include "actions-speed.h"
Functions
static void pause_toggle_action (ui_action_map_t *self)
Toggle pause.
static void advance_frame_action (ui_action_map_t *self)
Advance emulation a single frame if paused, pause otherwise.
static void warp_mode_toggle_action (ui_action_map_t *self)
Toggle warp mode.
static void update_cpu_radio_buttons (void)
Update main menu CPU speed radio buttons based on "Speed" resource.
static void update_fps_radio_buttons (void)
Update main menu FPS radio buttons based on "Speed" resource.
static void set_speed_resource (int speed)
Set "Speed" resource and update UI elements.
static void speed_cpu_action (ui_action_map_t *self)
Set CPU speed.
static void speed_cpu_custom_callback (GtkDialog *dialog, int result, gboolean valid)
Callback for custom speed.
static void speed_cpu_custom_action (ui_action_map_t *self)
Set custom CPU speed.
static void fps_custom_callback (GtkDialog *dialog, int result, gboolean valid)
Callback for custom FPS target.
static void speed_fps_custom_action (ui_action_map_t *self)
Set FPS to a custom value using a dialog.
void actions_speed_register (void)
Register speed-related UI actions.
void actions_speed_setup_ui (void)
Set the correct radio buttons and set "${EMU} FPS" label.
Variables
static const ui_action_map_t speed_actions_vsid []
Speed-related UI action mappings for VSID.
static const ui_action_map_t speed_actions []
Speed-related UI action mappings.
Detailed Description
UI action implementations for speed-related settings.
UI actions handling warp mode, pause, CPU speed and FPS.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
actions_speed_register()
void actions_speed_register (void)
Register speed-related UI actions.
Referenced by ui_init_finalize().
actions_speed_setup_ui()
void actions_speed_setup_ui (void)
Set the correct radio buttons and set "${EMU} FPS" label.
Referenced by ui_init_finalize().
advance_frame_action()
static void advance_frame_action (ui_action_map_t * self) static
Advance emulation a single frame if paused, pause otherwise.
Parameters
[in] self action map
fps_custom_callback()
static void fps_custom_callback (GtkDialog * dialog, int result, gboolean valid) static
Callback for custom FPS target.
Parameters
[in] dialog integer-dialog reference
[in] result result from the dialog
[in] valid result is valid
Referenced by speed_fps_custom_action().
pause_toggle_action()
static void pause_toggle_action (ui_action_map_t * self) static
Toggle pause.
Toggles pause and updates UI elements.
Parameters
[in] self action map
set_speed_resource()
static void set_speed_resource (int speed) static
Set "Speed" resource and update UI elements.
Set new value for "Speed" resource: postive values are CPU speed in percentage points (100 = 100%), negative values are FPS values (50 = 50Hz, 60 = 60Hz), using 0 means 100% CPU and machine FPS (dictated by the hardware).
Parameters
[in] speed new value for the resource
Referenced by fps_custom_callback(), speed_cpu_action(), and speed_cpu_custom_callback().
speed_cpu_action()
static void speed_cpu_action (ui_action_map_t * self) static
Set CPU speed.
Parameters
[in] self action map
speed_cpu_custom_action()
static void speed_cpu_custom_action (ui_action_map_t * self) static
Set custom CPU speed.
Pops up a dialog to set a custom emulation speed.
speed_cpu_custom_callback()
static void speed_cpu_custom_callback (GtkDialog * dialog, int result, gboolean valid) static
Callback for custom speed.
Parameters
[in] dialog integer-dialog reference
[in] result result from the dialog
[in] valid result is valid
Referenced by speed_cpu_custom_action().
speed_fps_custom_action()
static void speed_fps_custom_action (ui_action_map_t * self) static
Set FPS to a custom value using a dialog.
Pops up a dialog to set a custom FPS.
Parameters
[in] self action map
update_cpu_radio_buttons()
static void update_cpu_radio_buttons (void) static
Update main menu CPU speed radio buttons based on "Speed" resource.
Referenced by actions_speed_setup_ui(), and set_speed_resource().
update_fps_radio_buttons()
static void update_fps_radio_buttons (void) static
Update main menu FPS radio buttons based on "Speed" resource.
Referenced by actions_speed_setup_ui(), and set_speed_resource().
warp_mode_toggle_action()
static void warp_mode_toggle_action (ui_action_map_t * self) static
Toggle warp mode.
Toggles warp mode and updates UI elements.
Parameters
[in] self action map
Variable Documentation
speed_actions
const ui_action_map_t speed_actions[] static
Initial value:
= {
    {   .action   = ACTION_PAUSE_TOGGLE,
        .handler  = pause_toggle_action,
        .uithread = true
    },
    {   .action   = ACTION_ADVANCE_FRAME,
        .handler  = advance_frame_action,
        .uithread = true
    },
    {   .action   = ACTION_WARP_MODE_TOGGLE,
        .handler  = warp_mode_toggle_action,
        .uithread = true
    },
    {   .action   = ACTION_SPEED_CPU_200,
        .handler  = speed_cpu_action,
        .data     = ((void *)(intptr_t)( 200 )),
        .uithread = true
    },
    {   .action   = ACTION_SPEED_CPU_100,
        .handler  = speed_cpu_action,
        .data     = ((void *)(intptr_t)( 100 )),
        .uithread = true
    },
    {   .action   = ACTION_SPEED_CPU_50,
        .handler  = speed_cpu_action,
        .data     = ((void *)(intptr_t)( 50 )),
        .uithread = true
    },
    {   .action   = ACTION_SPEED_CPU_25,
        .handler  = speed_cpu_action,
        .data     = ((void *)(intptr_t)( 25 )),
        .uithread = true
    },
    {   .action   = ACTION_SPEED_CPU_10,
        .handler  = speed_cpu_action,
        .data     = ((void *)(intptr_t)( 10 )),
        .uithread = true
    },
    {   .action  = ACTION_SPEED_CPU_CUSTOM,
        .handler = speed_cpu_custom_action,
        .blocks  = true,
        .dialog  = true
    },
    {   .action   = ACTION_SPEED_FPS_REAL,
        .handler  = speed_cpu_action,
        .data     = ((void *)(intptr_t)( 100 )),
        .uithread = true
    },
    {   .action   = ACTION_SPEED_FPS_50,
        .handler  = speed_cpu_action,
        .data     = ((void *)(intptr_t)( -50 )),
        .uithread = true
    },
    {   .action   = ACTION_SPEED_FPS_60,
        .handler  = speed_cpu_action,
        .data     = ((void *)(intptr_t)( -60 )),
        .uithread = true
    },
    {   .action  = ACTION_SPEED_FPS_CUSTOM,
        .handler = speed_fps_custom_action,
        .blocks  = true,
        .dialog  = true
    },
     { .action = ACTION_NONE, .handler = NULL }
}
Speed-related UI action mappings.
Referenced by actions_speed_register().
speed_actions_vsid
const ui_action_map_t speed_actions_vsid[] static
Initial value:
= {
    {   .action   = ACTION_PAUSE_TOGGLE,
        .handler  = pause_toggle_action,
        .uithread = true
    },
    {   .action   = ACTION_WARP_MODE_TOGGLE,
        .handler  = warp_mode_toggle_action,
        .uithread = true
    },
     { .action = ACTION_NONE, .handler = NULL }
}
Speed-related UI action mappings for VSID.
Referenced by actions_speed_register().