x128: zfile.h File Reference
zfile.h File Reference
#include <stdio.h>
Enumerations
enum zfile_action_t {
ZFILE_KEEP ,
ZFILE_REQUEST ,
ZFILE_DEL
}
actions to be done when a zfile is closed
Functions
FILE * zfile_fopen (const char *name, const char *mode)
‘fopen()’ wrapper.
int zfile_fclose (FILE *stream)
‘fclose()’ wrapper.
void zfile_shutdown (void)
int zfile_close_action (const char *filename, zfile_action_t action, const char *request_string)
Enumeration Type Documentation
zfile_action_t
enum zfile_action_t
actions to be done when a zfile is closed
Enumerator
ZFILE_KEEP
ZFILE_REQUEST
ZFILE_DEL
Function Documentation
zfile_close_action()
int zfile_close_action (const char * filename, zfile_action_t action, const char * request_string)
Referenced by drive_snapshot_read_image_module().
zfile_fclose()
int zfile_fclose (FILE * stream)
‘fclose()’ wrapper.
Referenced by fsimage_close(), snapshot_close(), t64_close(), t64_destroy(), tap_close(), and tap_open().
zfile_fopen()
FILE * zfile_fopen (const char * name, const char * mode)
‘fopen()’ wrapper.
Referenced by fsimage_open(), snapshot_open(), t64_open(), and tap_open().
zfile_shutdown()
void zfile_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().