x128: fileio/cbmfile.h File Reference
cbmfile.h File Reference
#include "types.h"
Functions
struct fileio_info_s * cbmfile_open (const char *file_name, const char *path, unsigned int command, unsigned int type)
void cbmfile_close (struct fileio_info_s *info)
unsigned int cbmfile_read (struct fileio_info_s *info, uint8_t *buf, unsigned int len)
unsigned int cbmfile_write (struct fileio_info_s *info, uint8_t *buf, unsigned int len)
unsigned int cbmfile_ferror (struct fileio_info_s *info)
unsigned int cbmfile_rename (const char *src_name, const char *dst_name, const char *path)
unsigned int cbmfile_scratch (const char *file_name, const char *path)
unsigned int cbmfile_get_bytes_left (struct fileio_info_s *info)
unsigned int cbmfile_seek (struct fileio_info_s *info, off_t offset, int whence)
unsigned int cbmfile_tell (struct fileio_info_s *info)
Function Documentation
cbmfile_close()
void cbmfile_close (struct fileio_info_s * info)
Referenced by fileio_close().
cbmfile_ferror()
unsigned int cbmfile_ferror (struct fileio_info_s * info)
Referenced by fileio_ferror().
cbmfile_get_bytes_left()
unsigned int cbmfile_get_bytes_left (struct fileio_info_s * info)
Referenced by fileio_get_bytes_left().
cbmfile_open()
struct fileio_info_s * cbmfile_open (const char * file_name, const char * path, unsigned int command, unsigned int type)
Referenced by fileio_open().
cbmfile_read()
unsigned int cbmfile_read (struct fileio_info_s * info, uint8_t * buf, unsigned int len)
Referenced by fileio_read().
cbmfile_rename()
unsigned int cbmfile_rename (const char * src_name, const char * dst_name, const char * path)
Referenced by fileio_rename().
cbmfile_scratch()
unsigned int cbmfile_scratch (const char * file_name, const char * path)
Referenced by fileio_scratch().
cbmfile_seek()
unsigned int cbmfile_seek (struct fileio_info_s * info, off_t offset, int whence)
Referenced by fileio_seek().
cbmfile_tell()
unsigned int cbmfile_tell (struct fileio_info_s * info)
Referenced by fileio_tell().
cbmfile_write()
unsigned int cbmfile_write (struct fileio_info_s * info, uint8_t * buf, unsigned int len)
Referenced by fileio_write().