vsid: cbmimage.c File Reference
cbmimage.c File Reference
Generic image handling.
#include "vice.h"
#include <stdio.h>
#include "diskimage.h"
#include "tape.h"
#include "cbmimage.h"
Functions
int cbmimage_create_image (const char *name, unsigned int type)
Create a disk or tape image file.
int cbmimage_create_dxm_image (const char *name, const char *dname, unsigned int type)
Create a disk or tape image file.
int cbmimage_create_dhd_image (const char *name, const char *dname, unsigned int type)
Create a hard disk image file.
Detailed Description
Generic image handling.
Right now only contains a single function to create either a disk or a tape image file.
Function Documentation
cbmimage_create_dhd_image()
int cbmimage_create_dhd_image (const char * name, const char * dname, unsigned int type)
Create a hard disk image file.
Parameters
[in] name name of/path to image
[in] dname disk name and id
[in] type hard disk image type enumerator
Returns
0 on success, < 0 on failure
Referenced by vdrive_internal_create_format_disk_image().
cbmimage_create_dxm_image()
int cbmimage_create_dxm_image (const char * name, const char * dname, unsigned int type)
Create a disk or tape image file.
Parameters
[in] name name of/path to image
[in] dname disk name and id
[in] type disk/tape image type enumerator
Returns
0 on success, < 0 on failure
Referenced by vdrive_internal_create_format_disk_image().
cbmimage_create_image()
int cbmimage_create_image (const char * name, unsigned int type)
Create a disk or tape image file.
Parameters
[in] name name of/path to image
[in] type disk/tape image type enumerator
Returns
0 on success, < 0 on failure
Todo:
FIXME: this is nonsense, rename and move elsewhere
Referenced by create_tape_image(), and vdrive_internal_create_format_disk_image().