vsid: kbdbuf.c File Reference
kbdbuf.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "alarm.h"
#include "autostart.h"
#include "charset.h"
#include "cmdline.h"
#include "initcmdline.h"
#include "kbdbuf.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "mem.h"
#include "resources.h"
#include "types.h"
Macros
#define DBG(x)
#define QUEUE_SIZE 16384
Maximum number of characters we can queue.
Functions
static int set_kbdbuf_delay (int val, void *param)
set additional keybuf delay. 0 means default. (none)
int kbdbuf_resources_init (void)
initialize the resources
static void kbd_buf_parse_string (const char *string)
int kbdbuf_feed_string (const char *string)
static int kdb_buf_feed_cmdline (const char *param, void *extra_param)
used by the -keybuf cmdline option
int kbdbuf_cmdline_options_init (void)
static void tokbdbuffer (int c)
put character into the keyboard queue inside the emulation
int kbdbuf_is_empty (void)
Return nonzero if the keyboard buffer is empty.
int kbdbuf_queue_is_empty (void)
Return nonzero if there are keys in the buffer queue.
static int string_to_queue (const char *string)
Feed ‘string’ into the incoming queue.
static void removefromqueue (void)
remove current character from incoming queue
void kbdbuf_feed_cmdline (void)
used by autostart
static void kbdbuf_flush_alarm_triggered (CLOCK offset, void *data)
void kbdbuf_reset (int location, int plocation, int size, CLOCK mincycles)
void kbdbuf_abort (void)
abort ongoing "paste", called by reset
void kbdbuf_init (int location, int plocation, int size, CLOCK mincycles)
Initialization.
void kbdbuf_shutdown (void)
int kbdbuf_feed (const char *string)
used by autostart, monitor binary remote protocol, "paste" UI action
int kbdbuf_feed_runcmd (const char *string)
used by autostart to feed "RUN"
void kbdbuf_flush (void)
Variables
static int buffer_location
First location of the buffer.
static int num_pending_location
static int buffer_size
Maximum number of characters that fit in the buffer.
static CLOCK kernal_init_cycles
Number of cycles needed to initialize the Kernal.
static uint8_t queue [16384]
Characters in the queue.
static int head_idx = 0
Next element in ‘queue’ we must push into the kernal's queue.
static int num_pending = 0
Number of pending characters in the incoming queue
static int kbd_buf_enabled = 0
Flag if we are initialized already.
static bool kbd_buf_cmdline = false
Flag that indicates if the cmdline option was used to provide the string
static char * kbd_buf_string = NULL
String to feed into the keyboard buffer.
static int KbdbufDelay = 0
static int use_kbdbuf_flush_alarm = 0
static alarm_t * kbdbuf_flush_alarm = NULL
static bool kbdbuf_init_cmdline_fed = false
Only feed the cmdline -kbdbuf argument to the buffer once.
CLOCK kbdbuf_flush_alarm_time = 0
static const resource_int_t resources_int []
integer resources used by keybuf
static const cmdline_option_t cmdline_options []
Macro Definition Documentation
DBG
#define DBG (x)
QUEUE_SIZE
#define QUEUE_SIZE 16384
Maximum number of characters we can queue.
Function Documentation
kbd_buf_parse_string()
static void kbd_buf_parse_string (const char * string) static
Referenced by kbdbuf_feed_string(), and kdb_buf_feed_cmdline().
kbdbuf_abort()
void kbdbuf_abort (void)
abort ongoing "paste", called by reset
Referenced by machine_reset().
kbdbuf_cmdline_options_init()
int kbdbuf_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
kbdbuf_feed()
int kbdbuf_feed (const char * string)
used by autostart, monitor binary remote protocol, "paste" UI action
Referenced by advance_hasdisk(), advance_hastape(), autostart_finish(), kbdbuf_feed_cmdline(), kbdbuf_feed_string(), monitor_binary_process_keyboard_feed(), and paste_callback().
kbdbuf_feed_cmdline()
void kbdbuf_feed_cmdline (void)
used by autostart
Referenced by autostart_finish(), and kbdbuf_init().
kbdbuf_feed_runcmd()
int kbdbuf_feed_runcmd (const char * string)
used by autostart to feed "RUN"
Referenced by autostart_finish(), kbdbuf_feed_cmdline(), and machine_vsync_hook().
kbdbuf_feed_string()
int kbdbuf_feed_string (const char * string)
Referenced by mon_keyboard_feed().
kbdbuf_flush()
void kbdbuf_flush (void)
Referenced by string_to_queue(), and vsync_do_vsync().
kbdbuf_flush_alarm_triggered()
static void kbdbuf_flush_alarm_triggered (CLOCK offset, void * data) static
Referenced by kbdbuf_init().
kbdbuf_init()
void kbdbuf_init (int location, int plocation, int size, CLOCK mincycles)
Initialization.
Referenced by machine_specific_init().
kbdbuf_is_empty()
int kbdbuf_is_empty (void)
Return nonzero if the keyboard buffer is empty.
Referenced by check2(), is_machine_ready(), and kbdbuf_flush().
kbdbuf_queue_is_empty()
int kbdbuf_queue_is_empty (void)
Return nonzero if there are keys in the buffer queue.
Referenced by check2().
kbdbuf_reset()
void kbdbuf_reset (int location, int plocation, int size, CLOCK mincycles)
Referenced by kbdbuf_init().
kbdbuf_resources_init()
int kbdbuf_resources_init (void)
initialize the resources
Returns
0 on success, else -1.
Remarks
Registers the integer resources
Referenced by machine_resources_init().
kbdbuf_shutdown()
void kbdbuf_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
kdb_buf_feed_cmdline()
static int kdb_buf_feed_cmdline (const char * param, void * extra_param) static
used by the -keybuf cmdline option
removefromqueue()
static void removefromqueue (void) static
remove current character from incoming queue
Referenced by kbdbuf_flush(), and kbdbuf_flush_alarm_triggered().
set_kbdbuf_delay()
static int set_kbdbuf_delay (int val, void * param) static
set additional keybuf delay. 0 means default. (none)
string_to_queue()
static int string_to_queue (const char * string) static
Feed ‘string’ into the incoming queue.
Referenced by kbdbuf_feed(), and kbdbuf_feed_runcmd().
tokbdbuffer()
static void tokbdbuffer (int c) static
put character into the keyboard queue inside the emulation
Referenced by kbdbuf_flush(), and kbdbuf_flush_alarm_triggered().
Variable Documentation
buffer_location
int buffer_location static
First location of the buffer.
Referenced by kbdbuf_reset(), and tokbdbuffer().
buffer_size
int buffer_size static
Maximum number of characters that fit in the buffer.
Referenced by kbdbuf_flush(), and kbdbuf_reset().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-keybuf", CALL_FUNCTION,  (1 << 0) ,
      kdb_buf_feed_cmdline, NULL, NULL, NULL,
      "<string>", "Put the specified string into the keyboard buffer." },
    { "-keybuf-delay", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "KbdbufDelay", NULL,
      "<value>", "Set additional keyboard buffer delay (0: use default)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by kbdbuf_cmdline_options_init().
head_idx
int head_idx = 0 static
Next element in ‘queue’ we must push into the kernal's queue.
Referenced by kbdbuf_flush(), removefromqueue(), and string_to_queue().
kbd_buf_cmdline
bool kbd_buf_cmdline = false static
Flag that indicates if the cmdline option was used to provide the string
Referenced by kbdbuf_abort(), kbdbuf_feed_cmdline(), kbdbuf_feed_string(), kbdbuf_flush(), and kdb_buf_feed_cmdline().
kbd_buf_enabled
int kbd_buf_enabled = 0 static
Flag if we are initialized already.
Referenced by kbdbuf_flush(), kbdbuf_reset(), and string_to_queue().
kbd_buf_string
char* kbd_buf_string = NULL static
String to feed into the keyboard buffer.
Referenced by kbd_buf_parse_string(), kbdbuf_feed_cmdline(), kbdbuf_feed_string(), and kbdbuf_shutdown().
kbdbuf_flush_alarm
alarm_t* kbdbuf_flush_alarm = NULL static
Referenced by kbdbuf_flush(), kbdbuf_flush_alarm_triggered(), and kbdbuf_init().
kbdbuf_flush_alarm_time
CLOCK kbdbuf_flush_alarm_time = 0
Referenced by kbdbuf_flush(), and kbdbuf_flush_alarm_triggered().
kbdbuf_init_cmdline_fed
bool kbdbuf_init_cmdline_fed = false static
Only feed the cmdline -kbdbuf argument to the buffer once.
Referenced by kbdbuf_init().
KbdbufDelay
int KbdbufDelay = 0 static
Referenced by kbdbuf_feed_cmdline(), kbdbuf_init(), and set_kbdbuf_delay().
kernal_init_cycles
CLOCK kernal_init_cycles static
Number of cycles needed to initialize the Kernal.
Referenced by kbdbuf_flush(), and kbdbuf_reset().
num_pending
int num_pending = 0 static
Number of pending characters in the incoming queue
Referenced by kbdbuf_abort(), kbdbuf_flush(), kbdbuf_queue_is_empty(), removefromqueue(), and string_to_queue().
num_pending_location
int num_pending_location static
Referenced by kbdbuf_is_empty(), kbdbuf_reset(), and tokbdbuffer().
queue
uint8_t queue[16384] static
Characters in the queue.
Referenced by kbdbuf_flush(), string_to_queue(), and vsync_shutdown().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "KbdbufDelay", 0, RES_EVENT_NO, (resource_value_t)0,
      &KbdbufDelay, set_kbdbuf_delay, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
integer resources used by keybuf
Referenced by kbdbuf_resources_init().
use_kbdbuf_flush_alarm
int use_kbdbuf_flush_alarm = 0 static
Referenced by kbdbuf_feed(), kbdbuf_feed_runcmd(), and kbdbuf_flush().