x128: c128/c128mem.c File Reference
c128mem.c File Reference
Memory handling for the C128 emulator.
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "c128-resources.h"
#include "c128.h"
#include "c128mem.h"
#include "c128meminit.h"
#include "c64memlimit.h"
#include "c128memrom.h"
#include "c128mmu.h"
#include "c64cart.h"
#include "c128cart.h"
#include "c64cia.h"
#include "c64meminit.h"
#include "c64memrom.h"
#include "c64pla.h"
#include "cartio.h"
#include "cartridge.h"
#include "cia.h"
#include "functionrom.h"
#include "georam.h"
#include "keyboard.h"
#include "keymap.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "monitor.h"
#include "ram.h"
#include "reu.h"
#include "sid.h"
#include "sid-resources.h"
#include "types.h"
#include "vdc-mem.h"
#include "vdc.h"
#include "vdctypes.h"
#include "vicii-mem.h"
#include "vicii-phi1.h"
#include "vicii.h"
#include "viciitypes.h"
#include "z80.h"
#include "z80mem.h"
#include "video.h"
Macros
#define DEBUG_PRINT(x)
#define DBGKEY(x)
#define NUM_VBANKS 4
Number of possible video banks (16K each).
#define NUM_CONFIGS64 32
#define NUM_CONFIGS128 256
#define NUM_CONFIGS (NUM_CONFIGS64+NUM_CONFIGS128)
#define READ_TOP_SHARED(addr) ((addr) > top_shared_limit ? mem_ram[(addr)] : ram_bank[(addr)])
CPU Memory interface.
#define STORE_TOP_SHARED(addr, value) ((addr) > top_shared_limit ? (mem_ram[(addr)] = (value)) : (ram_bank[(addr)] = (value)))
#define READ_BOTTOM_SHARED(addr) ((addr) < bottom_shared_limit ? mem_ram[(addr)] : ram_bank[(addr)])
#define STORE_BOTTOM_SHARED(addr, value) ((addr) < bottom_shared_limit ? (mem_ram[(addr)] = (value)) : (ram_bank[(addr)] = (value)))
#define VICII_STORE_BOTTOM_SHARED(addr, value, func)
c64 mode vicii vbank wrappers, so that p0/p1 translation will work as well
#define VICII_STORE_MIDDLE_SHARED(addr, value, func)
#define VICII_STORE_TOP_SHARED(addr, value, func)
#define MAXBANKS (5 + 2 + 5 + 2)
Exported banked memory access functions for the monitor.
#define result(var)
Enumerations
enum {
bank128_cpu = 0 ,
bank128_ram ,
bank128_rom ,
bank128_io ,
bank128_ram00 ,
bank128_ram01 ,
bank128_intfunc ,
bank128_extfunc ,
bank128_cart ,
bank128_c64rom ,
bank128_vdc
}
enum {
bank256_cpu = 0 ,
bank256_ram ,
bank256_rom ,
bank256_io ,
bank256_ram00 ,
bank256_ram01 ,
bank256_ram02 ,
bank256_ram03 ,
bank256_intfunc ,
bank256_extfunc ,
bank256_cart ,
bank256_c64rom ,
bank256_vdc
}
Functions
static int mem_caps_key_event (int enabled)
called when CAPS was pressed or released
static uint8_t watch_read (uint16_t addr)
static void watch_store (uint16_t addr, uint8_t value)
static void mem_update_tab_ptrs (int flag)
called by mem_update_config(), mem_toggle_watchpoints()
void mem_toggle_watchpoints (int flag, void *context)
void c128_mem_set_mmu_page_0 (uint8_t val)
void c128_mem_set_mmu_page_1 (uint8_t val)
void c128_mem_set_mmu_page_0_bank (uint8_t val)
void c128_mem_set_mmu_page_1_bank (uint8_t val)
void c128_mem_set_mmu_page_0_target_ram (uint8_t val)
void c128_mem_set_mmu_page_1_target_ram (uint8_t val)
void c128_mem_set_mmu_zp_sp_shared (uint8_t val)
static uint16_t z80_mem_mmu_wrap_read_zero (uint16_t address)
returns 0x100 if normal read needs to be done, or <0x100 if the read was remapped
static uint16_t c128_mem_mmu_wrap_read_zero (uint16_t address)
returns 0x100 if normal read needs to be done, or <0x100 if the read was remapped
static uint16_t c128_mem_mmu_wrap_read (uint16_t address)
returns 0x100 if normal read needs to be done, or <0x100 if the read was remapped
static uint8_t z80_mem_mmu_wrap_store (uint16_t address, uint8_t value)
returns 1 if normal write needs to be done, or 0 if write was remapped and done
static uint8_t c128_mem_mmu_wrap_store (uint16_t address, uint8_t value)
returns 1 if normal write needs to be done, or 0 if write was remapped and done
static void mem_update_chargen (unsigned int chargen_high)
void mem_update_config (int config)
void mem_set_machine_type (unsigned type)
void mem_set_vbank (int new_vbank)
void mem_set_ram_config (uint8_t value)
void mem_pla_config_changed (void)
uint8_t zero_read_dma (uint16_t addr)
reads zeropage, 0/1 comes from RAM
uint8_t zero_read (uint16_t addr)
reads zeropage, 0/1 comes from CPU port
static uint8_t zero_peek (uint16_t addr)
void zero_store_dma (uint16_t addr, uint8_t value)
store zeropage, 0/1 goes to RAM
void zero_store (uint16_t addr, uint8_t value)
store zeropage, 0/1 goes to CPU port
uint8_t z80_read_zero (uint16_t addr)
z80 versions of reading and writing the zero page under mmu control.
void z80_store_zero (uint16_t addr, uint8_t value)
uint8_t one_read (uint16_t addr)
uint8_t z80_peek_zero (uint16_t addr)
uint8_t one_peek (uint16_t addr)
void one_store (uint16_t addr, uint8_t value)
uint8_t chargen_read (uint16_t addr)
External memory access functions.
void chargen_store (uint16_t addr, uint8_t value)
void mem_dma_store (uint16_t addr, uint8_t value)
uint8_t mem_dma_read (uint16_t addr)
void mem_store (uint16_t addr, uint8_t value)
Generic memory access.
uint8_t mem_read (uint16_t addr)
void mem_store_without_ultimax (uint16_t addr, uint8_t value)
uint8_t mem_read_without_ultimax (uint16_t addr)
add due to incompatibilities with c64mem.h
void mem_store_without_romlh (uint16_t addr, uint8_t value)
uint8_t lo_read (uint16_t addr)
$0200 - $3FFF: RAM (normal or shared).
uint8_t lo_peek (uint16_t addr)
void lo_store (uint16_t addr, uint8_t value)
uint8_t ram_read (uint16_t addr)
uint8_t ram_peek (uint16_t addr)
void ram_store (uint16_t addr, uint8_t value)
void ram_hi_store (uint16_t addr, uint8_t value)
uint8_t basic_lo_read (uint16_t addr)
$4000 - $7FFF: RAM or low BASIC ROM.
void basic_lo_store (uint16_t addr, uint8_t value)
uint8_t basic_hi_read (uint16_t addr)
$8000 - $BFFF: RAM or high BASIC ROM.
void basic_hi_store (uint16_t addr, uint8_t value)
static uint8_t basic_hi_peek (uint16_t addr)
uint8_t editor_read (uint16_t addr)
$C000 - $CFFF: RAM (normal or shared) or Editor ROM.
void editor_store (uint16_t addr, uint8_t value)
static uint8_t d5xx_read (uint16_t addr)
static void d5xx_store (uint16_t addr, uint8_t value)
uint8_t d7xx_read (uint16_t addr)
void d7xx_store (uint16_t addr, uint8_t value)
uint8_t hi_read (uint16_t addr)
$E000 - $FFFF: RAM or Kernal.
void hi_store (uint16_t addr, uint8_t value)
static uint8_t hi_peek (uint16_t addr)
uint8_t top_shared_read (uint16_t addr)
uint8_t top_shared_peek (uint16_t addr)
void top_shared_store (uint16_t addr, uint8_t value)
void colorram_store (uint16_t addr, uint8_t value)
uint8_t colorram_read (uint16_t addr)
uint8_t colorram_peek (uint16_t addr)
static void c64mode_vicii_mem_vbank_39xx_lo_store (uint16_t adr, uint8_t val)
static void c64mode_vicii_mem_vbank_3fxx_lo_store (uint16_t adr, uint8_t val)
static void c64mode_vicii_mem_vbank_lo_store (uint16_t adr, uint8_t val)
static void c64mode_vicii_mem_vbank_39xx_ram_store (uint16_t adr, uint8_t val)
static void c64mode_vicii_mem_vbank_3fxx_ram_store (uint16_t adr, uint8_t val)
static void c64mode_vicii_mem_vbank_ram_store (uint16_t adr, uint8_t val)
static void c64mode_vicii_mem_vbank_39xx_top_shared_store (uint16_t adr, uint8_t val)
static void c64mode_vicii_mem_vbank_3fxx_top_shared_store (uint16_t adr, uint8_t val)
static void c64mode_vicii_mem_vbank_top_shared_store (uint16_t adr, uint8_t val)
void mem_set_write_hook (int config, int page, store_func_t *f)
void mem_read_tab_set (unsigned int base, unsigned int index, read_func_ptr_t read_func)
void mem_read_base_set (unsigned int base, unsigned int index, uint8_t *mem_ptr)
void mem_read_limit_set (unsigned int base, unsigned int index, uint32_t limit)
static void c64mode_ffxx_store (uint16_t addr, uint8_t value)
void mem_initialize_memory (void)
void mem_mmu_translate (unsigned int addr, uint8_t **base, int *start, int *limit)
void mem_initialize_go64_memory_bank (uint8_t shared_mem)
Set up the memory map for the c64 mode.
void mem_powerup (void)
Initialize RAM for power-up.
void mem_set_tape_sense (int sense)
Set the tape sense status.
void mem_set_tape_write_in (int val)
Set the tape write in.
void mem_set_tape_motor_in (int val)
Set the tape motor in.
void mem_get_basic_text (uint16_t *start, uint16_t *end)
void mem_set_basic_text (uint16_t start, uint16_t end)
uint8_t mem_read_screen (uint16_t addr)
void mem_inject (uint32_t addr, uint8_t value)
void mem_inject_key (uint16_t addr, uint8_t value)
int mem_rom_trap_allowed (uint16_t addr)
void store_bank_io (uint16_t addr, uint8_t byte)
Banked memory access functions for the monitor.
uint8_t read_bank_io (uint16_t addr)
static uint8_t peek_bank_io (uint16_t addr)
const char ** mem_bank_list (void)
Memory access functions for the monitor.
const int * mem_bank_list_nos (void)
int mem_bank_from_name (const char *name)
return bank number for a given literal bank name
int mem_bank_index_from_bank (int bank)
return current index for a given bank
int mem_bank_flags_from_bank (int bank)
static int mem_bank_translate_128_to_256 (int bank)
uint8_t mem_bank_read (int bank, uint16_t addr, void *context)
int mem_get_current_bank_config (void)
static uint8_t mem_peek_with_config_c128 (int config, uint16_t addr, void *context)
"config" here is between 0 and 255 = mmu[0]
static uint8_t ram_peek_c64 (uint16_t addr)
ram peek for c64
static uint8_t mem_peek_with_config_c64 (int config, uint16_t addr, void *context)
"config" here is between 0 and 31
uint8_t mem_peek_with_config (int config, uint16_t addr, void *context)
uint8_t mem_bank_peek (int bank, uint16_t addr, void *context)
used by monitor if sfx off
void mem_bank_write (int bank, uint16_t addr, uint8_t byte, void *context)
void mem_bank_poke (int bank, uint16_t addr, uint8_t byte, void *context)
used by monitor if sfx off
static int mem_dump_io (void *context, uint16_t addr)
mem_ioreg_list_t * mem_ioreg_list_get (void *context)
void mem_get_screen_parameter (uint16_t *base, uint8_t *rows, uint8_t *columns, int *bank)
void mem_get_cursor_parameter (uint16_t *screen_addr, uint8_t *cursor_column, uint8_t *line_length, int *blinking)
void mem_color_ram_to_snapshot (uint8_t *color_ram)
void mem_color_ram_from_snapshot (uint8_t *color_ram)
uint8_t c128_c64io_d000_read (uint16_t addr)
8502 specific I/O function wrappers for 2mhz mode cycle stretching
void c128_c64io_d000_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d100_read (uint16_t addr)
void c128_c64io_d100_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d200_read (uint16_t addr)
void c128_c64io_d200_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d300_read (uint16_t addr)
void c128_c64io_d300_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d400_read (uint16_t addr)
void c128_c64io_d400_store (uint16_t addr, uint8_t value)
uint8_t c128_mmu_read (uint16_t addr)
void c128_mmu_store (uint16_t addr, uint8_t value)
uint8_t c128_d5xx_read (uint16_t addr)
void c128_d5xx_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d600_read (uint16_t addr)
void c128_c64io_d600_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d700_read (uint16_t addr)
void c128_c64io_d700_store (uint16_t addr, uint8_t value)
uint8_t c128_colorram_read (uint16_t addr)
void c128_colorram_store (uint16_t addr, uint8_t value)
uint8_t c128_cia1_read (uint16_t addr)
void c128_cia1_store (uint16_t addr, uint8_t value)
uint8_t c128_cia2_read (uint16_t addr)
void c128_cia2_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_de00_read (uint16_t addr)
void c128_c64io_de00_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_df00_read (uint16_t addr)
void c128_c64io_df00_store (uint16_t addr, uint8_t value)
Variables
uint8_t mem_ram [0x40000]
The C128 memory.
uint8_t mem_chargen_rom [0x2000]
static uint8_t mem_color_ram [0x800]
Internal color memory.
uint8_t * mem_color_ram_cpu
uint8_t * mem_color_ram_vicii
uint8_t * mem_chargen_rom_ptr
Pointer to the chargen ROM.
uint8_t * ram_bank
Currently selected RAM bank.
uint8_t * dma_bank
Currently selected DMA bank.
static int mem_dma_rw = 0
Current mem_read/mem_store is DMA.
static uint16_t top_shared_limit
Shared memory.
static uint16_t bottom_shared_limit
uint8_t * mem_page_zero
Pointers to pages 0 and 1 (which can be physically placed anywhere).
uint8_t * mem_page_one
read_func_ptr_t * _mem_read_tab_ptr
Pointers to the currently used memory read and write tables.
store_func_ptr_t * _mem_write_tab_ptr
read_func_ptr_t * _mem_read_tab_ptr_dummy
store_func_ptr_t * _mem_write_tab_ptr_dummy
static uint8_t ** _mem_read_base_tab_ptr
static uint32_t * mem_read_limit_tab_ptr
static store_func_ptr_t mem_write_tab [4][(32+256)][0x101]
Memory read and write tables.
static read_func_ptr_t mem_read_tab [(32+256)][0x101]
static uint8_t * mem_read_base_tab [(32+256)][0x101]
static uint32_t mem_read_limit_tab [(32+256)][0x101]
static store_func_ptr_t mem_write_tab_watch [0x101]
static read_func_ptr_t mem_read_tab_watch [0x101]
static int vbank = 0
static int tape_sense = 0
Tape sense status: 1 = some button pressed, 0 = no buttons pressed.
static int tape_write_in = 0
static int tape_motor_in = 0
static int mem_config
Current memory configuration.
static int watchpoints_active = 0
static unsigned int mem_machine_type
Current machine type.
static int caps_sense = 1
Status of the CAPS key (ASCII/DIN).
static uint8_t c128_mem_mmu_page_0 = 0
functions for mmu region swap handling
static uint8_t c128_mem_mmu_page_1 = 1
static uint8_t c128_mem_mmu_page_0_bank = 0
static uint8_t c128_mem_mmu_page_1_bank = 0
static uint8_t c128_mem_mmu_page_0_target_ram = 1
static uint8_t c128_mem_mmu_page_1_target_ram = 1
static uint8_t c128_mem_mmu_zp_sp_shared = 0
static char c64mem_read_base_tab [32][0x101]
static const char * banknames128 [(5+2+5+2)+1]
static const char * banknames256 [(5+2+5+2)+1]
static const int banknums128 [(5+2+5+2)+1]
static const int banknums256 [(5+2+5+2)+1]
static const int bankindex128 [(5+2+5+2)+1]
static const int bankindex256 [(5+2+5+2)+1]
static const int bankflags128 [(5+2+5+2)+1]
static const int bankflags256 [(5+2+5+2)+1]
Detailed Description
Memory handling for the C128 emulator.
Author
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Based on the original work in VICE 0.11.0 by Jouko Valta jopi@.nosp@m.stek.nosp@m.t.oul.nosp@m.u.fi
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Macro Definition Documentation
DBGKEY
#define DBGKEY (x)
DEBUG_PRINT
#define DEBUG_PRINT (x)
MAXBANKS
#define MAXBANKS (5 + 2 + 5 + 2)
Exported banked memory access functions for the monitor.
NUM_CONFIGS
#define NUM_CONFIGS (NUM_CONFIGS64+NUM_CONFIGS128)
NUM_CONFIGS128
#define NUM_CONFIGS128 256
NUM_CONFIGS64
#define NUM_CONFIGS64 32
NUM_VBANKS
#define NUM_VBANKS 4
Number of possible video banks (16K each).
READ_BOTTOM_SHARED
#define READ_BOTTOM_SHARED (addr) ((addr) < bottom_shared_limit ? mem_ram[(addr)] : ram_bank[(addr)])
READ_TOP_SHARED
#define READ_TOP_SHARED (addr) ((addr) > top_shared_limit ? mem_ram[(addr)] : ram_bank[(addr)])
CPU Memory interface.
result
#define result (var)
Value:
    res = var;           \
    ram_bank = old_bank; \
    return res;
STORE_BOTTOM_SHARED
#define STORE_BOTTOM_SHARED (addr, value) ((addr) < bottom_shared_limit ? (mem_ram[(addr)] = (value)) : (ram_bank[(addr)] = (value)))
STORE_TOP_SHARED
#define STORE_TOP_SHARED (addr, value) ((addr) > top_shared_limit ? (mem_ram[(addr)] = (value)) : (ram_bank[(addr)] = (value)))
VICII_STORE_BOTTOM_SHARED
#define VICII_STORE_BOTTOM_SHARED (addr, value, func)
Value:
if ((addr) < bottom_shared_limit) {                                       \
    /* store in shared ram00 */                                           \
    if (mem_ram == dma_bank) {                                            \
        /* vicii bank is ram00, store using vic function */               \
        func((addr), (value));                                            \
    } else {                                                              \
        /* vicii in different bank, store into ram00 directly */          \
        mem_ram[(addr)] = (value);                                        \
    }                                                                     \
} else {                                                                  \
    /* store in ramXX */                                                  \
    if (ram_bank == dma_bank) {                                           \
        /* vicii and ramXX are in same bank, store using vic function */  \
        func((addr), (value));                                            \
    } else {                                                              \
        /* vicii in different bank, store into ram00 directly */          \
        ram_bank[(addr)] = (value);                                       \
    }                                                                     \
}
c64 mode vicii vbank wrappers, so that p0/p1 translation will work as well
VICII_STORE_MIDDLE_SHARED
#define VICII_STORE_MIDDLE_SHARED (addr, value, func)
Value:
/* store in ramXX */                                                  \
if (ram_bank == dma_bank) {                                           \
    /* vicii and ramXX are in same bank, store using vic function */  \
    func((addr), (value));                                            \
} else {                                                              \
    /* vicii in different bank, store into ram00 directly */          \
    ram_bank[(addr)] = (value);                                       \
}
VICII_STORE_TOP_SHARED
#define VICII_STORE_TOP_SHARED (addr, value, func)
Value:
if ((addr) > top_shared_limit) {                                          \
    /* store in shared ram00 */                                           \
    if (mem_ram == dma_bank) {                                            \
        /* vicii bank is ram00, store using vic function */               \
        func((addr), (value));                                            \
    } else {                                                              \
        /* vicii in different bank, store into ram00 directly */          \
        mem_ram[(addr)] = (value);                                        \
    }                                                                     \
} else {                                                                  \
    /* store in ramXX */                                                  \
    if (ram_bank == dma_bank) {                                           \
        /* vicii and ramXX are in same bank, store using vic function */  \
        func((addr), (value));                                            \
    } else {                                                              \
        /* vicii in different bank, store into ram00 directly */          \
        ram_bank[(addr)] = (value);                                       \
    }                                                                     \
}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
bank128_cpu
bank128_ram
bank128_rom
bank128_io
bank128_ram00
bank128_ram01
bank128_intfunc
bank128_extfunc
bank128_cart
bank128_c64rom
bank128_vdc
anonymous enum
anonymous enum
Enumerator
bank256_cpu
bank256_ram
bank256_rom
bank256_io
bank256_ram00
bank256_ram01
bank256_ram02
bank256_ram03
bank256_intfunc
bank256_extfunc
bank256_cart
bank256_c64rom
bank256_vdc
Function Documentation
basic_hi_peek()
static uint8_t basic_hi_peek (uint16_t addr) static
Referenced by mem_peek_with_config_c128().
basic_hi_read()
uint8_t basic_hi_read (uint16_t addr)
$8000 - $BFFF: RAM or high BASIC ROM.
Referenced by c128meminit(), and z80mem_mid_rom_area_read().
basic_hi_store()
void basic_hi_store (uint16_t addr, uint8_t value)
Todo:
FIXME: basic replacement and dma?
Referenced by c128meminit(), and z80mem_mid_rom_area_store().
basic_lo_read()
uint8_t basic_lo_read (uint16_t addr)
$4000 - $7FFF: RAM or low BASIC ROM.
Referenced by c128meminit(), and z80mem_lo_rom_area_read().
basic_lo_store()
void basic_lo_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and z80mem_lo_rom_area_store().
c128_c64io_d000_read()
uint8_t c128_c64io_d000_read (uint16_t addr)
8502 specific I/O function wrappers for 2mhz mode cycle stretching
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d000_store()
void c128_c64io_d000_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d100_read()
uint8_t c128_c64io_d100_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d100_store()
void c128_c64io_d100_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d200_read()
uint8_t c128_c64io_d200_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d200_store()
void c128_c64io_d200_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d300_read()
uint8_t c128_c64io_d300_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d300_store()
void c128_c64io_d300_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d400_read()
uint8_t c128_c64io_d400_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d400_store()
void c128_c64io_d400_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d600_read()
uint8_t c128_c64io_d600_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d600_store()
void c128_c64io_d600_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d700_read()
uint8_t c128_c64io_d700_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d700_store()
void c128_c64io_d700_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_de00_read()
uint8_t c128_c64io_de00_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_de00_store()
void c128_c64io_de00_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_df00_read()
uint8_t c128_c64io_df00_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_df00_store()
void c128_c64io_df00_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_cia1_read()
uint8_t c128_cia1_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_cia1_store()
void c128_cia1_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_cia2_read()
uint8_t c128_cia2_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_cia2_store()
void c128_cia2_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_colorram_read()
uint8_t c128_colorram_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_colorram_store()
void c128_colorram_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_d5xx_read()
uint8_t c128_d5xx_read (uint16_t addr)
Referenced by mem_initialize_memory().
c128_d5xx_store()
void c128_d5xx_store (uint16_t addr, uint8_t value)
Referenced by mem_initialize_memory().
c128_mem_mmu_wrap_read()
static uint16_t c128_mem_mmu_wrap_read (uint16_t address) static
returns 0x100 if normal read needs to be done, or <0x100 if the read was remapped
Referenced by lo_peek(), lo_read(), one_peek(), one_read(), ram_peek(), ram_read(), top_shared_peek(), and top_shared_read().
c128_mem_mmu_wrap_read_zero()
static uint16_t c128_mem_mmu_wrap_read_zero (uint16_t address) static
returns 0x100 if normal read needs to be done, or <0x100 if the read was remapped
Referenced by zero_peek(), and zero_read_dma().
c128_mem_mmu_wrap_store()
static uint8_t c128_mem_mmu_wrap_store (uint16_t address, uint8_t value) static
returns 1 if normal write needs to be done, or 0 if write was remapped and done
Referenced by c64mode_vicii_mem_vbank_39xx_lo_store(), c64mode_vicii_mem_vbank_39xx_ram_store(), c64mode_vicii_mem_vbank_39xx_top_shared_store(), c64mode_vicii_mem_vbank_3fxx_lo_store(), c64mode_vicii_mem_vbank_3fxx_ram_store(), c64mode_vicii_mem_vbank_3fxx_top_shared_store(), c64mode_vicii_mem_vbank_lo_store(), c64mode_vicii_mem_vbank_ram_store(), c64mode_vicii_mem_vbank_top_shared_store(), lo_store(), one_store(), ram_store(), top_shared_store(), and zero_store_dma().
c128_mem_set_mmu_page_0()
void c128_mem_set_mmu_page_0 (uint8_t val)
Referenced by mmu_reset(), mmu_store(), and mmu_switch_to_c64mode().
c128_mem_set_mmu_page_0_bank()
void c128_mem_set_mmu_page_0_bank (uint8_t val)
Referenced by mmu_update_page01_pointers().
c128_mem_set_mmu_page_0_target_ram()
void c128_mem_set_mmu_page_0_target_ram (uint8_t val)
Referenced by mmu_update_page01_pointers().
c128_mem_set_mmu_page_1()
void c128_mem_set_mmu_page_1 (uint8_t val)
Referenced by mmu_reset(), mmu_store(), and mmu_switch_to_c64mode().
c128_mem_set_mmu_page_1_bank()
void c128_mem_set_mmu_page_1_bank (uint8_t val)
Referenced by mmu_update_page01_pointers().
c128_mem_set_mmu_page_1_target_ram()
void c128_mem_set_mmu_page_1_target_ram (uint8_t val)
Referenced by mmu_update_page01_pointers().
c128_mem_set_mmu_zp_sp_shared()
void c128_mem_set_mmu_zp_sp_shared (uint8_t val)
Referenced by mmu_update_page01_pointers().
c128_mmu_read()
uint8_t c128_mmu_read (uint16_t addr)
Referenced by c128meminit().
c128_mmu_store()
void c128_mmu_store (uint16_t addr, uint8_t value)
Referenced by c128meminit().
c64mode_ffxx_store()
static void c64mode_ffxx_store (uint16_t addr, uint8_t value) static
Referenced by mem_initialize_memory().
c64mode_vicii_mem_vbank_39xx_lo_store()
static void c64mode_vicii_mem_vbank_39xx_lo_store (uint16_t adr, uint8_t val) static
Referenced by mem_initialize_memory().
c64mode_vicii_mem_vbank_39xx_ram_store()
static void c64mode_vicii_mem_vbank_39xx_ram_store (uint16_t adr, uint8_t val) static
Referenced by mem_initialize_memory().
c64mode_vicii_mem_vbank_39xx_top_shared_store()
static void c64mode_vicii_mem_vbank_39xx_top_shared_store (uint16_t adr, uint8_t val) static
Referenced by mem_initialize_memory().
c64mode_vicii_mem_vbank_3fxx_lo_store()
static void c64mode_vicii_mem_vbank_3fxx_lo_store (uint16_t adr, uint8_t val) static
Referenced by mem_initialize_memory().
c64mode_vicii_mem_vbank_3fxx_ram_store()
static void c64mode_vicii_mem_vbank_3fxx_ram_store (uint16_t adr, uint8_t val) static
Referenced by mem_initialize_memory().
c64mode_vicii_mem_vbank_3fxx_top_shared_store()
static void c64mode_vicii_mem_vbank_3fxx_top_shared_store (uint16_t adr, uint8_t val) static
Referenced by mem_initialize_memory().
c64mode_vicii_mem_vbank_lo_store()
static void c64mode_vicii_mem_vbank_lo_store (uint16_t adr, uint8_t val) static
Referenced by mem_initialize_memory().
c64mode_vicii_mem_vbank_ram_store()
static void c64mode_vicii_mem_vbank_ram_store (uint16_t adr, uint8_t val) static
Referenced by mem_initialize_memory().
c64mode_vicii_mem_vbank_top_shared_store()
static void c64mode_vicii_mem_vbank_top_shared_store (uint16_t adr, uint8_t val) static
Referenced by mem_initialize_memory().
chargen_read()
uint8_t chargen_read (uint16_t addr)
External memory access functions.
Referenced by c128meminit(), mem_initialize_memory(), and z80mem_initialize().
chargen_store()
void chargen_store (uint16_t addr, uint8_t value)
colorram_peek()
uint8_t colorram_peek (uint16_t addr)
colorram_read()
uint8_t colorram_read (uint16_t addr)
Referenced by c128_colorram_read(), c64mode_colorram_read(), peek_bank_io(), read_bank_io(), z80_colorram_read(), z80mem_initialize(), and z80mem_peek_with_config().
colorram_store()
void colorram_store (uint16_t addr, uint8_t value)
Referenced by c128_colorram_store(), c64mode_colorram_store(), store_bank_io(), z80_colorram_store(), and z80mem_initialize().
d5xx_read()
static uint8_t d5xx_read (uint16_t addr) static
Referenced by c128_d5xx_read().
d5xx_store()
static void d5xx_store (uint16_t addr, uint8_t value) static
Referenced by c128_d5xx_store().
d7xx_read()
uint8_t d7xx_read (uint16_t addr)
d7xx_store()
void d7xx_store (uint16_t addr, uint8_t value)
editor_read()
uint8_t editor_read (uint16_t addr)
$C000 - $CFFF: RAM (normal or shared) or Editor ROM.
Referenced by c128meminit(), and z80mem_editor_rom_area_read().
editor_store()
void editor_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and z80mem_editor_rom_area_store().
hi_peek()
static uint8_t hi_peek (uint16_t addr) static
Referenced by mem_peek_with_config_c128().
hi_read()
uint8_t hi_read (uint16_t addr)
$E000 - $FFFF: RAM or Kernal.
Referenced by c128meminit(), mmu_ffxx_read(), and z80mem_hi_rom_area_read().
hi_store()
void hi_store (uint16_t addr, uint8_t value)
Todo:
FIXME: kernal replacement and dma?
Referenced by c128meminit(), mmu_ffxx_store(), z80mem_chargen_rom_area_store(), and z80mem_hi_rom_area_store().
lo_peek()
uint8_t lo_peek (uint16_t addr)
Referenced by mem_peek_with_config_c128(), and z80mem_peek_with_config().
lo_read()
uint8_t lo_read (uint16_t addr)
$0200 - $3FFF: RAM (normal or shared).
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU shared ram translation.
Referenced by c128meminit(), c64mode_colorram_read(), mem_initialize_memory(), and z80mem_initialize().
lo_store()
void lo_store (uint16_t addr, uint8_t value)
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU shared ram translation.
Referenced by c128meminit(), c64mode_colorram_store(), mem_initialize_memory(), and z80mem_initialize().
mem_bank_flags_from_bank()
int mem_bank_flags_from_bank (int bank)
Referenced by maincpu_monitor_interface_get(), and mon_get_bank_flags_for_bank().
mem_bank_from_name()
int mem_bank_from_name (const char * name)
return bank number for a given literal bank name
Referenced by maincpu_monitor_interface_get(), mon_banknum_from_bank(), mon_breakpoint_check_checkpoint(), mon_file_load(), mon_file_verify(), mon_get_bank_name_for_bank(), mon_register_print(), monitor_init(), and monitor_open().
mem_bank_index_from_bank()
int mem_bank_index_from_bank (int bank)
return current index for a given bank
Referenced by maincpu_monitor_interface_get(), and mon_get_bank_index_for_bank().
mem_bank_list()
const char ** mem_bank_list (void)
Memory access functions for the monitor.
Referenced by maincpu_monitor_interface_get(), mon_bank(), mon_display_io_regs(), mon_get_bank_name_for_bank(), and monitor_binary_process_banks_available().
mem_bank_list_nos()
const int * mem_bank_list_nos (void)
Referenced by maincpu_monitor_interface_get(), mon_banknum_validate(), and monitor_binary_process_banks_available().
mem_bank_peek()
uint8_t mem_bank_peek (int bank, uint16_t addr, void * context)
used by monitor if sfx off
Referenced by clipboard_read_screen_output(), maincpu_monitor_interface_get(), mon_get_mem_val_ex(), mon_get_mem_val_ex_nosfx(), and mon_get_mem_val_nosfx().
mem_bank_poke()
void mem_bank_poke (int bank, uint16_t addr, uint8_t byte, void * context)
used by monitor if sfx off
Referenced by maincpu_monitor_interface_get(), mon_set_mem_val(), and mon_set_mem_val_ex().
mem_bank_read()
uint8_t mem_bank_read (int bank, uint16_t addr, void * context)
Referenced by maincpu_monitor_interface_get(), and mem_bank_peek().
mem_bank_translate_128_to_256()
static int mem_bank_translate_128_to_256 (int bank) static
Referenced by mem_bank_peek(), mem_bank_read(), and mem_bank_write().
mem_bank_write()
void mem_bank_write (int bank, uint16_t addr, uint8_t byte, void * context)
Referenced by maincpu_monitor_interface_get(), and mem_bank_poke().
mem_caps_key_event()
static int mem_caps_key_event (int enabled) static
called when CAPS was pressed or released
Referenced by mem_initialize_memory(), and mem_set_machine_type().
mem_color_ram_from_snapshot()
void mem_color_ram_from_snapshot (uint8_t * color_ram)
Referenced by vicii_snapshot_read_module().
mem_color_ram_to_snapshot()
void mem_color_ram_to_snapshot (uint8_t * color_ram)
Referenced by vicii_snapshot_write_module().
mem_dma_read()
uint8_t mem_dma_read (uint16_t addr)
mem_dma_store()
void mem_dma_store (uint16_t addr, uint8_t value)
mem_dump_io()
static int mem_dump_io (void * context, uint16_t addr) static
Referenced by mem_ioreg_list_get().
mem_get_basic_text()
void mem_get_basic_text (uint16_t * start, uint16_t * end)
Referenced by autostart_prg_perform_injection().
mem_get_current_bank_config()
int mem_get_current_bank_config (void)
Referenced by callstack_push(), initialize_context(), mon_backtrace(), mon_disassemble_instr_memconfig_internal(), and profile_sample_start().
mem_get_cursor_parameter()
void mem_get_cursor_parameter (uint16_t * screen_addr, uint8_t * cursor_column, uint8_t * line_length, int * blinking)
Referenced by check2(), and is_machine_ready().
mem_get_screen_parameter()
void mem_get_screen_parameter (uint16_t * base, uint8_t * rows, uint8_t * columns, int * bank)
Referenced by clipboard_read_screen_output(), mon_display_screen(), and mon_memory_display().
mem_initialize_go64_memory_bank()
void mem_initialize_go64_memory_bank (uint8_t shared_mem)
Set up the memory map for the c64 mode.
Todo:
FIXME: Do we need this again?
Referenced by mmu_switch_to_c128mode(), and mmu_switch_to_c64mode().
mem_initialize_memory()
void mem_initialize_memory (void)
Todo:
FIXME: no support for ultimax at $D000 - see c64 code
Referenced by machine_init(), machine_reset(), and mem_load().
mem_inject()
void mem_inject (uint32_t addr, uint8_t value)
Referenced by autostart_prg_perform_injection(), and mem_inject_key().
mem_inject_key()
void mem_inject_key (uint16_t addr, uint8_t value)
Referenced by tokbdbuffer().
mem_ioreg_list_get()
mem_ioreg_list_t * mem_ioreg_list_get (void * context)
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
Referenced by maincpu_monitor_interface_get().
mem_mmu_translate()
void mem_mmu_translate (unsigned int addr, uint8_t ** base, int * start, int * limit)
uncomment to debug mmu related stuff
Referenced by maincpu_resync_limits().
mem_peek_with_config()
uint8_t mem_peek_with_config (int config, uint16_t addr, void * context)
Referenced by maincpu_monitor_interface_get(), mem_bank_peek(), and mon_get_mem_val_nosfx().
mem_peek_with_config_c128()
static uint8_t mem_peek_with_config_c128 (int config, uint16_t addr, void * context) static
"config" here is between 0 and 255 = mmu[0]
Referenced by mem_peek_with_config().
mem_peek_with_config_c64()
static uint8_t mem_peek_with_config_c64 (int config, uint16_t addr, void * context) static
"config" here is between 0 and 31
Referenced by mem_peek_with_config().
mem_pla_config_changed()
void mem_pla_config_changed (void)
Referenced by mem_caps_key_event(), mem_set_machine_type(), mem_set_tape_motor_in(), mem_set_tape_sense(), mem_set_tape_write_in(), mmu_4080_key_event(), and zero_store().
mem_powerup()
void mem_powerup (void)
Initialize RAM for power-up.
Referenced by machine_powerup().
mem_read()
uint8_t mem_read (uint16_t addr)
Referenced by mem_bank_read().
mem_read_base_set()
void mem_read_base_set (unsigned int base, unsigned int index, uint8_t * mem_ptr)
Referenced by c128meminit().
mem_read_limit_set()
void mem_read_limit_set (unsigned int base, unsigned int index, uint32_t limit)
Referenced by c128meminit().
mem_read_screen()
uint8_t mem_read_screen (uint16_t addr)
Referenced by check2(), and is_machine_ready().
mem_read_tab_set()
void mem_read_tab_set (unsigned int base, unsigned int index, read_func_ptr_t read_func)
Referenced by c128meminit().
mem_read_without_ultimax()
uint8_t mem_read_without_ultimax (uint16_t addr)
add due to incompatibilities with c64mem.h
mem_rom_trap_allowed()
int mem_rom_trap_allowed (uint16_t addr)
mem_set_basic_text()
void mem_set_basic_text (uint16_t start, uint16_t end)
Referenced by autostart_prg_perform_injection(), and mon_file_load().
mem_set_machine_type()
void mem_set_machine_type (unsigned type)
Referenced by set_machine_type().
mem_set_ram_config()
void mem_set_ram_config (uint8_t value)
Referenced by mmu_store().
mem_set_tape_motor_in()
void mem_set_tape_motor_in (int val)
Set the tape motor in.
mem_set_tape_sense()
void mem_set_tape_sense (int sense)
Set the tape sense status.
mem_set_tape_write_in()
void mem_set_tape_write_in (int val)
Set the tape write in.
mem_set_vbank()
void mem_set_vbank (int new_vbank)
mem_set_write_hook()
void mem_set_write_hook (int config, int page, store_func_t * f)
Referenced by c128meminit(), and mem_initialize_memory().
mem_store()
void mem_store (uint16_t addr, uint8_t value)
Generic memory access.
Referenced by mem_bank_write().
mem_store_without_romlh()
void mem_store_without_romlh (uint16_t addr, uint8_t value)
mem_store_without_ultimax()
void mem_store_without_ultimax (uint16_t addr, uint8_t value)
mem_toggle_watchpoints()
void mem_toggle_watchpoints (int flag, void * context)
Referenced by maincpu_monitor_interface_get().
mem_update_chargen()
static void mem_update_chargen (unsigned int chargen_high) static
Referenced by mem_pla_config_changed(), and mem_update_config().
mem_update_config()
void mem_update_config (int config)
Referenced by mmu_switch_to_c128mode(), and mmu_switch_to_c64mode().
mem_update_tab_ptrs()
static void mem_update_tab_ptrs (int flag) static
called by mem_update_config(), mem_toggle_watchpoints()
Referenced by mem_toggle_watchpoints(), and mem_update_config().
one_peek()
uint8_t one_peek (uint16_t addr)
Referenced by mem_peek_with_config_c128(), ram_peek_c64(), and z80mem_peek_with_config().
one_read()
uint8_t one_read (uint16_t addr)
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU page 1 translation.
Referenced by c128meminit(), mem_initialize_memory(), and z80mem_initialize().
one_store()
void one_store (uint16_t addr, uint8_t value)
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU page 1 translation.
Referenced by c128meminit(), mem_initialize_memory(), and z80mem_initialize().
peek_bank_io()
static uint8_t peek_bank_io (uint16_t addr) static
Referenced by mem_bank_peek(), mem_peek_with_config_c128(), and mem_peek_with_config_c64().
ram_hi_store()
void ram_hi_store (uint16_t addr, uint8_t value)
ram_peek()
uint8_t ram_peek (uint16_t addr)
Referenced by mem_peek_with_config_c128(), z80mem_lo_rom_area_peek(), z80mem_mid_rom_area_peek(), and z80mem_peek_with_config().
ram_peek_c64()
static uint8_t ram_peek_c64 (uint16_t addr) static
ram peek for c64
Referenced by mem_peek_with_config_c64().
ram_read()
uint8_t ram_read (uint16_t addr)
Referenced by c128meminit(), mem_initialize_memory(), z80mem_initialize(), z80mem_lo_rom_area_read(), and z80mem_mid_rom_area_read().
ram_store()
void ram_store (uint16_t addr, uint8_t value)
Todo:
FIXME: basic replacement and dma?
Referenced by c128meminit(), external_function_rom_store(), internal_function_rom_store(), mem_initialize_memory(), z80mem_initialize(), z80mem_lo_rom_area_store(), and z80mem_mid_rom_area_store().
read_bank_io()
uint8_t read_bank_io (uint16_t addr)
Referenced by mem_bank_read().
store_bank_io()
void store_bank_io (uint16_t addr, uint8_t byte)
Banked memory access functions for the monitor.
Todo:
FIXME: peek, cartridge support
Referenced by mem_bank_write().
top_shared_peek()
uint8_t top_shared_peek (uint16_t addr)
Referenced by mem_peek_with_config_c128(), z80mem_chargen_rom_area_peek(), z80mem_editor_rom_area_peek(), z80mem_hi_rom_area_peek(), and z80mem_peek_with_config().
top_shared_read()
uint8_t top_shared_read (uint16_t addr)
Referenced by c128meminit(), mem_initialize_memory(), mmu_ffxx_read(), z80_io_ram_bank0_read(), z80mem_chargen_rom_area_read(), z80mem_editor_rom_area_read(), z80mem_hi_rom_area_read(), and z80mem_initialize().
top_shared_store()
void top_shared_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), c64mode_ffxx_store(), external_function_top_shared_store(), internal_function_top_shared_store(), mem_initialize_memory(), z80_c64mode_ffxx_store(), z80_io_ram_bank0_store(), z80mem_chargen_rom_area_store(), z80mem_editor_rom_area_store(), z80mem_hi_rom_area_store(), and z80mem_initialize().
watch_read()
static uint8_t watch_read (uint16_t addr) static
Referenced by mem_initialize_memory().
watch_store()
static void watch_store (uint16_t addr, uint8_t value) static
Referenced by mem_initialize_memory().
z80_mem_mmu_wrap_read_zero()
static uint16_t z80_mem_mmu_wrap_read_zero (uint16_t address) static
returns 0x100 if normal read needs to be done, or <0x100 if the read was remapped
Referenced by c128_mem_mmu_wrap_read_zero(), z80_peek_zero(), and z80_read_zero().
z80_mem_mmu_wrap_store()
static uint8_t z80_mem_mmu_wrap_store (uint16_t address, uint8_t value) static
returns 1 if normal write needs to be done, or 0 if write was remapped and done
Referenced by c128_mem_mmu_wrap_store(), and z80_store_zero().
z80_peek_zero()
uint8_t z80_peek_zero (uint16_t addr)
Referenced by z80mem_peek_with_config().
z80_read_zero()
uint8_t z80_read_zero (uint16_t addr)
z80 versions of reading and writing the zero page under mmu control.
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU page 0 translation.
Referenced by z80mem_initialize().
z80_store_zero()
void z80_store_zero (uint16_t addr, uint8_t value)
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU page 0 translation.
Referenced by z80mem_initialize().
zero_peek()
static uint8_t zero_peek (uint16_t addr) static
Referenced by mem_peek_with_config_c128(), and ram_peek_c64().
zero_read()
uint8_t zero_read (uint16_t addr)
reads zeropage, 0/1 comes from CPU port
Referenced by mem_initialize_memory().
zero_read_dma()
uint8_t zero_read_dma (uint16_t addr)
reads zeropage, 0/1 comes from RAM
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU page 0 translation.
Referenced by mem_dma_read(), and zero_read().
zero_store()
void zero_store (uint16_t addr, uint8_t value)
store zeropage, 0/1 goes to CPU port
Referenced by mem_initialize_memory().
zero_store_dma()
void zero_store_dma (uint16_t addr, uint8_t value)
store zeropage, 0/1 goes to RAM
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU page 0 translation.
Referenced by mem_dma_store(), and zero_store().
Variable Documentation
_mem_read_base_tab_ptr
uint8_t** _mem_read_base_tab_ptr static
Referenced by mem_initialize_memory(), mem_mmu_translate(), and mem_update_config().
_mem_read_tab_ptr
read_func_ptr_t* _mem_read_tab_ptr
Pointers to the currently used memory read and write tables.
Referenced by mem_dma_read(), mem_initialize_memory(), mem_read(), mem_read_check_ba(), and mem_update_tab_ptrs().
_mem_read_tab_ptr_dummy
read_func_ptr_t* _mem_read_tab_ptr_dummy
Referenced by mem_read_check_ba_dummy(), and mem_update_tab_ptrs().
_mem_write_tab_ptr
store_func_ptr_t* _mem_write_tab_ptr
Referenced by mem_dma_store(), mem_initialize_memory(), mem_store(), and mem_update_tab_ptrs().
_mem_write_tab_ptr_dummy
store_func_ptr_t* _mem_write_tab_ptr_dummy
Referenced by mem_update_tab_ptrs().
bankflags128
const int bankflags128[(5+2+5+2)+1] static
Initial value:
= {
    0,
    0,
    0,
    0,
    0,
     0x01   |  0x02  ,
     0x01   |  0x04  ,
    0,
    0,
    0,
    0,
    0,
    -1
}
Referenced by mem_bank_flags_from_bank().
bankflags256
const int bankflags256[(5+2+5+2)+1] static
Initial value:
= {
    0,
    0,
    0,
    0,
    0,
     0x01   |  0x02  ,
     0x01  ,
     0x01  ,
     0x01   |  0x04  ,
    0,
    0,
    0,
    0,
    0,
    -1
}
Referenced by mem_bank_flags_from_bank().
bankindex128
const int bankindex128[(5+2+5+2)+1] static
Initial value:
= {
    -1,
    -1,
    -1,
    -1,
    -1,
    0,
    1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1
}
Referenced by mem_bank_index_from_bank().
bankindex256
const int bankindex256[(5+2+5+2)+1] static
Initial value:
= {
    -1,
    -1,
    -1,
    -1,
    -1,
    0,
    1,
    2,
    3,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1
}
Referenced by mem_bank_index_from_bank().
banknames128
const char* banknames128[(5+2+5+2)+1] static
Initial value:
= {
    "default",
    "cpu",
    "ram",
    "rom",
    "io",
    "ram00",
    "ram01",
    "intfunc",
    "extfunc",
    "cart",
    "c64rom",
    "vdc",
    NULL
}
Todo:
FIXME: add ram00 bank, make 'ram' bank always show selected ram bank, ram00 and ram01 always physical ram bank
Referenced by mem_bank_from_name(), and mem_bank_list().
banknames256
const char* banknames256[(5+2+5+2)+1] static
Initial value:
= {
    "default",
    "cpu",
    "ram",
    "rom",
    "io",
    "ram00",
    "ram01",
    "ram02",
    "ram03",
    "intfunc",
    "extfunc",
    "cart",
    "c64rom",
    "vdc",
    NULL
}
Referenced by mem_bank_from_name(), and mem_bank_list().
banknums128
const int banknums128[(5+2+5+2)+1] static
Initial value:
= {
    bank128_cpu,
    bank128_cpu,
    bank128_ram,
    bank128_rom,
    bank128_io,
    bank128_ram00,
    bank128_ram01,
    bank128_intfunc,
    bank128_extfunc,
    bank128_cart,
    bank128_c64rom,
    bank128_vdc,
    -1
}
Referenced by mem_bank_flags_from_bank(), mem_bank_from_name(), mem_bank_index_from_bank(), and mem_bank_list_nos().
banknums256
const int banknums256[(5+2+5+2)+1] static
Initial value:
= {
    bank256_cpu,
    bank256_cpu,
    bank256_ram,
    bank256_rom,
    bank256_io,
    bank256_ram00,
    bank256_ram01,
    bank256_ram02,
    bank256_ram03,
    bank256_intfunc,
    bank256_extfunc,
    bank256_cart,
    bank256_c64rom,
    bank256_vdc,
    -1
}
Referenced by mem_bank_flags_from_bank(), mem_bank_from_name(), mem_bank_index_from_bank(), and mem_bank_list_nos().
bottom_shared_limit
uint16_t bottom_shared_limit static
Referenced by mem_initialize_memory(), and mem_set_ram_config().
c128_mem_mmu_page_0
uint8_t c128_mem_mmu_page_0 = 0 static
functions for mmu region swap handling
Todo:
FIXME: some cases might not be handled correctly yet they will be implemented based on the results of tests on real hardware.
Referenced by c128_mem_mmu_wrap_read(), c128_mem_set_mmu_page_0(), z80_mem_mmu_wrap_read_zero(), and z80_mem_mmu_wrap_store().
c128_mem_mmu_page_0_bank
uint8_t c128_mem_mmu_page_0_bank = 0 static
Referenced by c128_mem_mmu_wrap_read(), c128_mem_set_mmu_page_0_bank(), z80_mem_mmu_wrap_read_zero(), and z80_mem_mmu_wrap_store().
c128_mem_mmu_page_0_target_ram
uint8_t c128_mem_mmu_page_0_target_ram = 1 static
Referenced by c128_mem_mmu_wrap_read(), c128_mem_set_mmu_page_0_target_ram(), z80_mem_mmu_wrap_read_zero(), and z80_mem_mmu_wrap_store().
c128_mem_mmu_page_1
uint8_t c128_mem_mmu_page_1 = 1 static
Referenced by c128_mem_mmu_wrap_read(), c128_mem_set_mmu_page_1(), z80_mem_mmu_wrap_read_zero(), and z80_mem_mmu_wrap_store().
c128_mem_mmu_page_1_bank
uint8_t c128_mem_mmu_page_1_bank = 0 static
Referenced by c128_mem_mmu_wrap_read(), c128_mem_set_mmu_page_1_bank(), and z80_mem_mmu_wrap_store().
c128_mem_mmu_page_1_target_ram
uint8_t c128_mem_mmu_page_1_target_ram = 1 static
Referenced by c128_mem_mmu_wrap_read(), c128_mem_set_mmu_page_1_target_ram(), and z80_mem_mmu_wrap_store().
c128_mem_mmu_zp_sp_shared
uint8_t c128_mem_mmu_zp_sp_shared = 0 static
Referenced by c128_mem_mmu_wrap_read(), c128_mem_set_mmu_zp_sp_shared(), z80_mem_mmu_wrap_read_zero(), and z80_mem_mmu_wrap_store().
c64mem_read_base_tab
char c64mem_read_base_tab[32][0x101] static
Referenced by mem_initialize_go64_memory_bank(), and mem_initialize_memory().
caps_sense
int caps_sense = 1 static
Status of the CAPS key (ASCII/DIN).
Referenced by mem_caps_key_event(), and mem_pla_config_changed().
dma_bank
uint8_t* dma_bank
Currently selected DMA bank.
Referenced by basic_hi_store(), basic_lo_store(), c64mode_ffxx_store(), c64mode_vicii_mem_vbank_39xx_lo_store(), c64mode_vicii_mem_vbank_39xx_ram_store(), c64mode_vicii_mem_vbank_39xx_top_shared_store(), c64mode_vicii_mem_vbank_3fxx_lo_store(), c64mode_vicii_mem_vbank_3fxx_ram_store(), c64mode_vicii_mem_vbank_3fxx_top_shared_store(), c64mode_vicii_mem_vbank_lo_store(), c64mode_vicii_mem_vbank_ram_store(), c64mode_vicii_mem_vbank_top_shared_store(), hi_store(), lo_read(), lo_store(), mem_set_ram_config(), mmu_set_dma_bank(), one_read(), one_store(), ram_hi_store(), ram_read(), ram_store(), top_shared_read(), top_shared_store(), z80_read_zero(), z80_store_zero(), zero_read_dma(), and zero_store_dma().
mem_chargen_rom
uint8_t mem_chargen_rom[0x2000]
Referenced by c128rom_chargen_setup(), mem_bank_read(), mem_initialize_memory(), mem_peek_with_config_c64(), mem_read_rom_snapshot_module(), mem_update_chargen(), and mem_write_rom_snapshot_module().
mem_chargen_rom_ptr
uint8_t* mem_chargen_rom_ptr
Pointer to the chargen ROM.
Referenced by chargen_read(), chargen_store(), handle_fetch_sprite(), mem_initialize_memory(), mem_peek_with_config_c128(), mem_update_chargen(), vicii_update_memory_ptrs(), and z80mem_peek_with_config().
mem_color_ram
uint8_t mem_color_ram[0x800] static
Internal color memory.
Referenced by mem_color_ram_from_snapshot(), mem_color_ram_to_snapshot(), mem_initialize_memory(), mem_powerup(), and mem_update_config().
mem_color_ram_cpu
uint8_t* mem_color_ram_cpu
Referenced by colorram_peek(), colorram_read(), colorram_store(), mem_initialize_memory(), and mem_update_config().
mem_color_ram_vicii
uint8_t * mem_color_ram_vicii
Referenced by mem_initialize_memory(), mem_update_config(), vicii_fetch_matrix(), and vicii_screenshot().
mem_config
int mem_config static
Current memory configuration.
Referenced by c128cartridge_mmu_translate(), get_child_context(), get_mem_config_context(), is_branch_instruction(), mem_bank_peek(), mem_get_current_bank_config(), mem_mmu_translate(), mem_read_without_ultimax(), mem_rom_trap_allowed(), mem_store_without_ultimax(), mem_update_config(), mem_update_tab_ptrs(), mon_disassemble_instr_memconfig_internal(), mon_disassemble_oneline(), mon_get_mem_val_nosfx(), ram_peek_c64(), watch_read(), and watch_store().
mem_dma_rw
int mem_dma_rw = 0 static
Current mem_read/mem_store is DMA.
Referenced by basic_hi_store(), basic_lo_store(), c64mode_ffxx_store(), c64mode_vicii_mem_vbank_39xx_lo_store(), c64mode_vicii_mem_vbank_39xx_ram_store(), c64mode_vicii_mem_vbank_39xx_top_shared_store(), c64mode_vicii_mem_vbank_3fxx_lo_store(), c64mode_vicii_mem_vbank_3fxx_ram_store(), c64mode_vicii_mem_vbank_3fxx_top_shared_store(), c64mode_vicii_mem_vbank_lo_store(), c64mode_vicii_mem_vbank_ram_store(), c64mode_vicii_mem_vbank_top_shared_store(), hi_store(), lo_read(), lo_store(), mem_dma_read(), mem_dma_store(), one_read(), one_store(), ram_hi_store(), ram_read(), ram_store(), top_shared_read(), top_shared_store(), z80_read_zero(), z80_store_zero(), zero_read_dma(), and zero_store_dma().
mem_machine_type
unsigned int mem_machine_type static
Current machine type.
Referenced by mem_pla_config_changed(), mem_set_machine_type(), mem_update_chargen(), and mem_update_config().
mem_page_one
uint8_t * mem_page_one
Referenced by mem_initialize_memory(), mmu_update_page01_pointers(), one_peek(), one_read(), and one_store().
mem_page_zero
uint8_t* mem_page_zero
Pointers to pages 0 and 1 (which can be physically placed anywhere).
Referenced by mem_initialize_memory(), mmu_update_page01_pointers(), z80_peek_zero(), z80_read_zero(), z80_store_zero(), zero_peek(), zero_read_dma(), zero_store(), and zero_store_dma().
mem_ram
uint8_t mem_ram[0x40000]
The C128 memory.
Referenced by _draw_8bpp_chunky_bitmap(), _draw_8bpp_fred2_bitmap_mode(), _draw_8bpp_fred_bitmap_mode(), _draw_8bpp_pixel_cell_bitmap_mode(), _draw_8bpp_two_plane_bitmap_mode(), c128_mem_mmu_wrap_read(), c128_snapshot_read_module(), c128_snapshot_write_module(), c128meminit(), c64_256k_ram_segment2_read(), c64_256k_ram_segment2_store(), mem_bank_read(), mem_bank_write(), mem_get_basic_text(), mem_get_cursor_parameter(), mem_initialize_go64_memory_bank(), mem_initialize_memory(), mem_inject(), mem_powerup(), mem_read_screen(), mem_set_basic_text(), mmu_set_dma_bank(), mmu_set_ram_bank(), mmu_update_page01_pointers(), plus256k_ram_high_read(), plus256k_ram_high_store(), plus60k_ram_read(), plus60k_ram_store(), tape_find_header_trap(), tape_find_header_trap_plus4(), tape_receive_trap(), tape_receive_trap_plus4(), vicii_powerup(), vicii_reset(), vicii_snapshot_read_module(), vicii_snapshot_write_module(), viciidtv_update_colorram(), z80_mem_mmu_wrap_read_zero(), and z80_mem_mmu_wrap_store().
mem_read_base_tab
uint8_t* mem_read_base_tab[(32+256)][0x101] static
Referenced by mem_initialize_go64_memory_bank(), mem_initialize_memory(), mem_read_base_set(), mem_update_config(), and ram_peek_c64().
mem_read_limit_tab
uint32_t mem_read_limit_tab[(32+256)][0x101] static
Referenced by mem_initialize_memory(), mem_read_limit_set(), and mem_update_config().
mem_read_limit_tab_ptr
uint32_t* mem_read_limit_tab_ptr static
Referenced by mem_initialize_memory(), mem_mmu_translate(), and mem_update_config().
mem_read_tab
read_func_ptr_t mem_read_tab[(32+256)][0x101] static
Referenced by mem_initialize_memory(), mem_read_tab_set(), mem_read_without_ultimax(), mem_update_tab_ptrs(), and watch_read().
mem_read_tab_watch
read_func_ptr_t mem_read_tab_watch[0x101] static
Referenced by mem_initialize_memory(), and mem_update_tab_ptrs().
mem_write_tab
store_func_ptr_t mem_write_tab[4][(32+256)][0x101] static
Memory read and write tables.
Referenced by mem_initialize_memory(), mem_set_write_hook(), mem_store_without_romlh(), mem_store_without_ultimax(), mem_update_tab_ptrs(), and watch_store().
mem_write_tab_watch
store_func_ptr_t mem_write_tab_watch[0x101] static
Referenced by mem_initialize_memory(), and mem_update_tab_ptrs().
ram_bank
uint8_t* ram_bank
Currently selected RAM bank.
Referenced by basic_hi_store(), basic_lo_store(), mem_initialize_go64_memory_bank(), mem_initialize_memory(), mem_peek_with_config_c128(), mmu_set_ram_bank(), ram_hi_store(), ram_peek(), ram_read(), ram_store(), and z80mem_peek_with_config().
tape_motor_in
int tape_motor_in = 0 static
Referenced by mem_pla_config_changed(), and mem_set_tape_motor_in().
tape_sense
int tape_sense = 0 static
Tape sense status: 1 = some button pressed, 0 = no buttons pressed.
Referenced by mem_pla_config_changed(), and mem_set_tape_sense().
tape_write_in
int tape_write_in = 0 static
Referenced by mem_pla_config_changed(), and mem_set_tape_write_in().
top_shared_limit
uint16_t top_shared_limit static
Shared memory.
Referenced by mem_initialize_memory(), and mem_set_ram_config().
vbank
int vbank = 0 static
Referenced by c64mode_ffxx_store(), mem_initialize_memory(), mem_set_vbank(), mem_store_without_romlh(), mem_store_without_ultimax(), mem_update_tab_ptrs(), ram_hi_store(), and watch_store().
watchpoints_active
int watchpoints_active = 0 static
Referenced by mem_toggle_watchpoints(), and mem_update_config().