vsid: drive/drive-check.c File Reference
drive-check.c File Reference
#include "vice.h"
#include "drive-check.h"
#include "drive.h"
#include "drivetypes.h"
#include "iecdrive.h"
#include "machine.h"
#include "machine-drive.h"
#include "resources.h"
Functions
static unsigned int drive_check_ieee (unsigned int type)
int drive_check_iec (int type)
unsigned int drive_check_old (unsigned int type)
unsigned int drive_get_num_heads (unsigned int type)
return number of heads for given drive
unsigned int drive_get_half_tracks (unsigned int type)
return number of physical half tracks for given drive
unsigned int drive_check_dual (unsigned int type)
static unsigned int drive_check_tcbm (unsigned int type)
unsigned int drive_check_bus (unsigned int drive_type, unsigned int bus_map)
int drive_check_type (unsigned int drive_type, unsigned int dnr)
int drive_check_expansion (int drive_type)
int drive_check_expansion2000 (int drive_type)
int drive_check_expansion4000 (int drive_type)
int drive_check_expansion6000 (int drive_type)
int drive_check_expansion8000 (int drive_type)
int drive_check_expansionA000 (int drive_type)
int drive_check_parallel_cable (int drive_type)
int drive_check_extend_policy (int drive_type)
int drive_check_idle_method (int drive_type)
int drive_check_profdos (int drive_type)
int drive_check_supercard (int drive_type)
int drive_check_stardos (int drive_type)
int drive_check_rtc (int drive_type)
Check if drive_type supports a real-time clock.
int drive_get_type_by_devnr (int devnr)
int drive_is_dualdrive_by_devnr (int devnr)
Function Documentation
drive_check_bus()
unsigned int drive_check_bus (unsigned int drive_type, unsigned int bus_map)
< parallel IEEE bus
< serial IEC bus
< parallel TCBM bus
Referenced by drive_check_type(), and drive_resources_type().
drive_check_dual()
unsigned int drive_check_dual (unsigned int type)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
Referenced by create_readonly_check_button(), drive_is_dualdrive_by_devnr(), drive_update_ui_status(), layout_statusbar_drives(), on_model_changed(), ui_display_drive_track(), and ui_enable_drive_status().
drive_check_expansion()
int drive_check_expansion (int drive_type)
drive_check_expansion2000()
int drive_check_expansion2000 (int drive_type)
drive_check_expansion4000()
int drive_check_expansion4000 (int drive_type)
drive_check_expansion6000()
int drive_check_expansion6000 (int drive_type)
drive_check_expansion8000()
int drive_check_expansion8000 (int drive_type)
drive_check_expansionA000()
int drive_check_expansionA000 (int drive_type)
drive_check_extend_policy()
int drive_check_extend_policy (int drive_type)
Todo:
FIXME: will be always extended
Todo:
FIXME: will be always extended
Todo:
FIXME: will be always extended
Todo:
FIXME: will be always extended
Referenced by drive_extend_policy_widget_update(), and on_model_changed().
drive_check_idle_method()
int drive_check_idle_method (int drive_type)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
Referenced by on_model_changed().
drive_check_iec()
int drive_check_iec (int type)
< ASCII for HD
Referenced by drive_check_bus().
drive_check_ieee()
static unsigned int drive_check_ieee (unsigned int type) static
Todo:
FIXME: what is the difference between drive_check_ieee and drive_check_old ?
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
Referenced by drive_check_bus().
drive_check_old()
unsigned int drive_check_old (unsigned int type)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
Referenced by drivecpu_snapshot_read_module(), and drivecpu_snapshot_write_module().
drive_check_parallel_cable()
int drive_check_parallel_cable (int drive_type)
Referenced by drive_parallel_cable_widget_update(), and on_model_changed().
drive_check_profdos()
int drive_check_profdos (int drive_type)
drive_check_rtc()
int drive_check_rtc (int drive_type)
Check if drive_type supports a real-time clock.
Parameters
[in] drive_type drive type
Returns
bool
< ASCII for HD
Referenced by create_rtc_check_button(), and on_model_changed().
drive_check_stardos()
int drive_check_stardos (int drive_type)
Todo:
FIXME: stardos apparently exists for 157x, needs more research
drive_check_supercard()
int drive_check_supercard (int drive_type)
drive_check_tcbm()
static unsigned int drive_check_tcbm (unsigned int type) static
Referenced by drive_check_bus().
drive_check_type()
int drive_check_type (unsigned int drive_type, unsigned int dnr)
Referenced by create_combo_model(), drive_init(), and drive_model_widget_update().
drive_get_half_tracks()
unsigned int drive_get_half_tracks (unsigned int type)
return number of physical half tracks for given drive
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
drive_get_num_heads()
unsigned int drive_get_num_heads (unsigned int type)
return number of heads for given drive
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 1M/disk
Referenced by ui_display_drive_track().
drive_get_type_by_devnr()
int drive_get_type_by_devnr (int devnr)
Todo:
FIXME: xvic has its own IEC code and doesn't use "IECDevice[8-11]"
Referenced by drive_is_dualdrive_by_devnr().
drive_is_dualdrive_by_devnr()
int drive_is_dualdrive_by_devnr (int devnr)
Referenced by advance_hasdisk(), create_extra_widget(), dir_menu_popup_create(), drive_snapshot_write_module(), on_unit_changed(), and ui_do_drive_popup().