x128: arch/gtk3/widgets/base/csshelpers.h File Reference
csshelpers.h File Reference
Helper/wrapper functions for using CSS in Gtk3 code - header.
#include <gtk/gtk.h>
Functions
GtkCssProvider * vice_gtk3_css_provider_new (const char *css)
Create a new CSS provider and set it to css.
gboolean vice_gtk3_css_provider_add (GtkWidget *widget, GtkCssProvider *provider)
Add CSS provider to widget.
gboolean vice_gtk3_css_provider_remove (GtkWidget *widget, GtkCssProvider *provider)
Remove provider from widget.
gboolean vice_gtk3_css_add (GtkWidget *widget, const char *css)
Add CSS string css to widget.
Detailed Description
Helper/wrapper functions for using CSS in Gtk3 code - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
vice_gtk3_css_add()
gboolean vice_gtk3_css_add (GtkWidget * widget, const char * css)
Add CSS string css to widget.
Only use this when adding CSS to a single widget, if you need to add the same CSS to multiple widgets use vice_gtk3_css_provider_new() to create a CSS provider once and vice_gtk3_css_provider_add() to add it multiple times.
Parameters
[in,out] widget widget to add CSS to
[in] css CSS string
Returns
bool
Referenced by create_stop_button(), create_treeview(), settings_ramreset_widget_create(), and statusbar_recording_widget_create().
vice_gtk3_css_provider_add()
gboolean vice_gtk3_css_provider_add (GtkWidget * widget, GtkCssProvider * provider)
Add CSS provider to widget.
Parameters
[in,out] widget widget to add provider to
[in] provider CSS provider
Returns
bool
Referenced by create_exp_slider(), create_header(), create_label(), create_slider(), crt_control_widget_create(), dir_item_apply_style(), expandable_list_new(), kbd_debug_widget_create(), on_entry_changed(), set_serial_resource(), settings_rom_widget_create(), statusbar_led_widget_create(), ui_drive_widget_create(), and vice_gtk3_css_add().
vice_gtk3_css_provider_new()
GtkCssProvider * vice_gtk3_css_provider_new (const char * css)
Create a new CSS provider and set it to css.
Use this function if you need a CSS provider you'll apply multiple times, if you need to apply CSS to a widget only once, there's a wrapper function vice_gtk3_css_add().
Parameters
[in] css CSS string
Returns
new provider or NULL on error
Referenced by create_css_providers(), create_serial_entry(), kbd_debug_widget_create(), mixer_widget_create(), settings_rom_widget_create(), statusbar_led_widget_create(), ui_drive_widget_create(), vice_gtk3_css_add(), and vice_gtk3_resource_numeric_string_new().
vice_gtk3_css_provider_remove()
gboolean vice_gtk3_css_provider_remove (GtkWidget * widget, GtkCssProvider * provider)
Remove provider from widget.
Parameters
[in,out] widget gtk widget
[in] provider gtk css provider to remove
Returns
gboolean
Referenced by on_entry_changed(), and set_serial_resource().