vsid: arch/gtk3/uisidattach.c File Reference
uisidattach.c File Reference
Gtk3 SID-attach dialog.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include "archdep_get_hvsc_dir.h"
#include "debug_gtk3.h"
#include "basedialogs.h"
#include "filechooserhelpers.h"
#include "lastdir.h"
#include "lib.h"
#include "psid.h"
#include "resources.h"
#include "ui.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uivsidwindow.h"
#include "uisidattach.h"
Functions
static void on_update_preview (GtkFileChooser *chooser, gpointer data)
Handler for the "update-preview" event.
static void on_hidden_toggled (GtkWidget *widget, gpointer user_data)
Handler for the 'toggled' event of the 'show hidden files' checkbox.
static void on_response (GtkWidget *widget, gint response_id, gpointer user_data)
Handler for 'response' event of the dialog.
static GtkWidget * create_extra_widget (GtkWidget *parent)
Create the 'extra' widget.
static GtkWidget * create_sid_attach_dialog (void)
Create the SID attach dialog.
void uisidattach_show_dialog (void)
Callback for the "Load SID file" menu item.
void uisidattach_shutdown (void)
Clean up the last directory string.
Variables
static ui_file_filter_t filters []
File type filters for the dialog.
static gchar * last_dir = NULL
Last used directory in dialog.
static gchar * last_file = NULL
Last used filename in dialog.
Detailed Description
Gtk3 SID-attach dialog.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_extra_widget()
static GtkWidget * create_extra_widget (GtkWidget * parent) static
Create the 'extra' widget.
Parameters
[in] parent parent widget
Returns
GtkGrid
Referenced by create_sid_attach_dialog().
create_sid_attach_dialog()
static GtkWidget * create_sid_attach_dialog (void) static
Create the SID attach dialog.
Returns
GtkFileChooserDialog
Referenced by uisidattach_show_dialog().
on_hidden_toggled()
static void on_hidden_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the 'toggled' event of the 'show hidden files' checkbox.
Parameters
[in] widget checkbox triggering the event
[in] user_data data for the event (the dialog)
Referenced by create_extra_widget().
on_response()
static void on_response (GtkWidget * widget, gint response_id, gpointer user_data) static
Handler for 'response' event of the dialog.
This handler is called when the user clicks a button in the dialog.
Parameters
[in] widget the dialog
[in] response_id response ID
[in] user_data extra data (unused)
Referenced by create_sid_attach_dialog().
on_update_preview()
static void on_update_preview (GtkFileChooser * chooser, gpointer data) static
Handler for the "update-preview" event.
Parameters
[in] chooser file chooser dialog
[in] data extra event data (unused)
Todo:
show SID info
Referenced by create_sid_attach_dialog().
uisidattach_show_dialog()
void uisidattach_show_dialog (void)
Callback for the "Load SID file" menu item.
Creates the dialog and runs it.
Parameters
[in] widget menu item triggering the callback
[in] data ignored
Returns
TRUE
Referenced by psid_load_action().
uisidattach_shutdown()
void uisidattach_shutdown (void)
Clean up the last directory string.
Referenced by vsid_ui_close().
Variable Documentation
filters
ui_file_filter_t filters[] static
Initial value:
= {
    { "SID/MUS files", file_chooser_pattern_sid },
    { "All files", file_chooser_pattern_all },
    { NULL, NULL }
}
File type filters for the dialog.
Referenced by create_sid_attach_dialog().
last_dir
gchar* last_dir = NULL static
Last used directory in dialog.
Referenced by create_sid_attach_dialog(), on_response(), and uisidattach_shutdown().
last_file
gchar* last_file = NULL static
Last used filename in dialog.
Referenced by create_sid_attach_dialog(), on_response(), and uisidattach_shutdown().