x128: reSID::ExternalFilter Class Reference
reSID::ExternalFilter Class Reference
#include <extfilt.h>
Public Member Functions
ExternalFilter ()
void enable_filter (bool enable)
void clock (short Vi)
void clock (cycle_count delta_t, short Vi)
void reset ()
int output ()
Protected Attributes
bool enabled
int Vlp
int Vhp
int w0lp_1_s7
int w0hp_1_s17
Friends
class SID
Constructor & Destructor Documentation
ExternalFilter()
reSID::ExternalFilter::ExternalFilter ()
Member Function Documentation
clock() [1/2]
void reSID::ExternalFilter::clock (cycle_count delta_t, short Vi)
clock() [2/2]
void reSID::ExternalFilter::clock (short Vi)
Referenced by reSID::SID::clock().
enable_filter()
void reSID::ExternalFilter::enable_filter (bool enable)
Referenced by ExternalFilter(), and reSID::SID::enable_external_filter().
output()
int reSID::ExternalFilter::output ()
reset()
void reSID::ExternalFilter::reset ()
Referenced by ExternalFilter(), and reSID::SID::reset().
Friends And Related Function Documentation
SID
friend class SID friend
Field Documentation
enabled
bool reSID::ExternalFilter::enabled protected
Referenced by enable_filter().
Vhp
int reSID::ExternalFilter::Vhp protected
Referenced by reset().
Vlp
int reSID::ExternalFilter::Vlp protected
Referenced by reset().
w0hp_1_s17
int reSID::ExternalFilter::w0hp_1_s17 protected
Referenced by ExternalFilter().
w0lp_1_s7
int reSID::ExternalFilter::w0lp_1_s7 protected
Referenced by ExternalFilter().
The documentation for this class was generated from the following files:
resid/extfilt.h
resid/extfilt.cc