x128: rs232drv/rs232drv.h File Reference
rs232drv.h File Reference
#include "types.h"
Enumerations
enum rs232handshake_out {
RS232_HSO_RTS = 0x01 ,
RS232_HSO_DTR = 0x02
}
enum rs232handshake_in {
RS232_HSI_CTS = 0x01 ,
RS232_HSI_DSR = 0x02 ,
RS232_HSI_DCD = 0x04 ,
RS232_HSI_RI = 0x08
}
Functions
int rs232drv_resources_init (void)
void rs232drv_resources_shutdown (void)
int rs232drv_cmdline_options_init (void)
void rs232drv_init (void)
void rs232drv_reset (void)
int rs232drv_open (int device)
void rs232drv_close (int fd)
int rs232drv_putc (int fd, uint8_t b)
int rs232drv_getc (int fd, uint8_t *b)
int rs232drv_set_status (int fd, enum rs232handshake_out status)
write the output handshake lines
enum rs232handshake_in rs232drv_get_status (int fd)
write the output handshake lines
void rs232drv_set_bps (int fd, unsigned int bps)
Enumeration Type Documentation
rs232handshake_in
enum rs232handshake_in
Enumerator
RS232_HSI_CTS
RS232_HSI_DSR
Todo:
FIXME: we assume DCD = CTS
RS232_HSI_DCD
RS232_HSI_RI
rs232handshake_out
enum rs232handshake_out
Enumerator
RS232_HSO_RTS
RS232_HSO_DTR
Function Documentation
rs232drv_close()
void rs232drv_close (int fd)
Referenced by myacia_reset(), myacia_snapshot_read_module(), myacia_store(), rsuser_reset(), rsuser_write_ctrl(), set_up_device(), and userport_rs232_enable().
rs232drv_cmdline_options_init()
int rs232drv_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
rs232drv_get_status()
enum rs232handshake_in rs232drv_get_status (int fd)
write the output handshake lines
Referenced by acia_get_status(), and rsuser_read_ctrl().
rs232drv_getc()
int rs232drv_getc (int fd, uint8_t * b)
Referenced by int_acia_rx(), and int_rsuser().
rs232drv_init()
void rs232drv_init (void)
Referenced by machine_specific_init().
rs232drv_open()
int rs232drv_open (int device)
Referenced by myacia_snapshot_read_module(), myacia_store(), rsuser_setup(), and set_up_device().
rs232drv_putc()
int rs232drv_putc (int fd, uint8_t b)
Referenced by check_tx_buffer(), and int_acia_tx().
rs232drv_reset()
void rs232drv_reset (void)
Referenced by machine_specific_reset().
rs232drv_resources_init()
int rs232drv_resources_init (void)
Referenced by machine_resources_init().
rs232drv_resources_shutdown()
void rs232drv_resources_shutdown (void)
Referenced by machine_resources_shutdown().
rs232drv_set_bps()
void rs232drv_set_bps (int fd, unsigned int bps)
Referenced by set_acia_ticks().
rs232drv_set_status()
int rs232drv_set_status (int fd, enum rs232handshake_out status)
write the output handshake lines
Referenced by acia_set_handshake_lines(), myacia_reset(), and rsuser_write_ctrl().