x128: profiler_data.h File Reference
profiler_data.h File Reference
#include "types.h"
Data Structures
struct profiling_data_s
struct profiling_page_s
struct profiling_context_s
Typedefs
typedef uint32_t profiling_counter_t
typedef struct profiling_data_s profiling_data_t
typedef struct profiling_page_s profiling_page_t
typedef struct profiling_context_s profiling_context_t
Enumerations
enum CallstackMagic {
NMI = 0xfffa ,
RESET = 0xfffc ,
IRQ = 0xfffe
}
Functions
profiling_context_t * profile_context_by_id (int id)
int get_context_id (profiling_context_t *context)
void compute_aggregate_stats (profiling_context_t *context)
profiling_page_t * profiling_get_page (profiling_context_t *ctx, uint8_t page)
profiling_context_t * alloc_profiling_context (void)
void free_profiling_context (profiling_context_t *data)
profiling_context_t * get_mem_config_context (profiling_context_t *main_context, uint16_t mem_config)
Variables
profiling_context_t * root_context
profiling_context_t * current_context
Typedef Documentation
profiling_context_t
typedef struct profiling_context_s profiling_context_t
profiling_counter_t
typedef uint32_t profiling_counter_t
profiling_data_t
typedef struct profiling_data_s profiling_data_t
profiling_page_t
typedef struct profiling_page_s profiling_page_t
Enumeration Type Documentation
CallstackMagic
enum CallstackMagic
Enumerator
NMI
RESET
IRQ
Function Documentation
alloc_profiling_context()
profiling_context_t * alloc_profiling_context (void)
Referenced by array_compact(), get_child_context(), get_mem_config_context(), profile_start(), recursively_aggregate_all_functions(), and recursively_aggregate_matching_functions().
compute_aggregate_stats()
void compute_aggregate_stats (profiling_context_t * context)
Referenced by compute_aggregate_stats(), and init_profiling_data().
free_profiling_context()
void free_profiling_context (profiling_context_t * data)
Referenced by free_aggregate_stats(), free_profiling_context(), merge_all_memory_configs(), mon_profile_flat(), mon_profile_func(), profile_reset(), and profile_start().
get_context_id()
int get_context_id (profiling_context_t * context)
Referenced by print_all_contexts(), and print_context_id().
get_mem_config_context()
profiling_context_t * get_mem_config_context (profiling_context_t * main_context, uint16_t mem_config)
Referenced by initialize_context(), and merge_aggregate_contexts().
profile_context_by_id()
profiling_context_t * profile_context_by_id (int id)
Referenced by mon_profile_disass_context(), and mon_profile_graph().
profiling_get_page()
profiling_page_t * profiling_get_page (profiling_context_t * ctx, uint8_t page)
Referenced by compute_aggregate_stats(), merge_aggregate_contexts(), merge_all_pages(), and profile_sample_finish().
Variable Documentation
current_context
profiling_context_t* current_context extern
Referenced by initialize_context(), print_context_graph(), profile_reset(), profile_sample_finish(), profile_sample_start(), and profile_start().
root_context
profiling_context_t* root_context extern
Referenced by init_profiling_data(), initialize_context(), mon_profile(), mon_profile_clear(), mon_profile_disass(), mon_profile_flat(), mon_profile_func(), mon_profile_graph(), profile_reset(), and profile_start().