x128: tape/tap.c File Reference
tap.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "cmdline.h"
#include "datasette.h"
#include "lib.h"
#include "log.h"
#include "tap.h"
#include "tape.h"
#include "types.h"
#include "util.h"
#include "zfile.h"
#include "machine.h"
#include "resources.h"
Data Structures
struct CLKLIST
Macros
#define TAP_DEBUG 0
#define TAP_PULSE_SHORT(x) ((x) >= tap_pulse_short_min && (x) <= tap_pulse_short_max)
#define TAP_PULSE_MIDDLE(x) ((x) >= tap_pulse_middle_min && (x) <= tap_pulse_middle_max)
#define TAP_PULSE_LONG(x) ((x) >= tap_pulse_long_min && (x) <= tap_pulse_long_max)
#define TAP_PULSE_TT_SHORT(x) ((x) >= tap_pulse_tt_short_min && (x) <= tap_pulse_tt_short_max)
#define TAP_PULSE_TT_LONG(x) ((x) >= tap_pulse_tt_long_min && (x) <= tap_pulse_tt_long_max)
#define MAX_ERRORS 30
#define PILOT_TYPE_ANY -1
#define PILOT_TYPE_CBM 0
#define PILOT_TYPE_TT 1
#define TT_BLOCK_TYPE_HEADER 1
#define TT_BLOCK_TYPE_DATA 0
#define PILOT_MIN_LENGTH_TT 200
#define PILOT_MIN_LENGTH_CBM 32
Functions
static int tap_get_clockspeed (int system, int video)
static int tap_header_read (tap_t *tap, FILE *fd)
static tap_t * tap_new (void)
tap_t * tap_open (const char *name, unsigned int *read_only)
int tap_close (tap_t *tap)
int tap_create (const char *name)
static int tap_find_pilot (tap_t *tap, int type)
static int tap_get_pulse (tap_t *tap, int *pos_advance)
static int tap_cbm_read_bit (tap_t *tap)
static int tap_cbm_read_byte (tap_t *tap)
static int tap_cbm_skip_pilot (tap_t *tap)
static int tap_cbm_read_block_once (tap_t *tap, int *pass, uint8_t *buffer, int *size, int *error_buf, int *error_count)
static int tap_cbm_read_block (tap_t *tap, uint8_t *buffer, int size)
NOTE: parameter "size" must equal expected block size + 1 (for parity byte)
static int tap_cbm_read_header (tap_t *tap)
static int tap_cbm_read_file_prg (tap_t *tap)
static int tap_cbm_read_file_seq (tap_t *tap)
static int tap_cbm_read_file (tap_t *tap)
static int tap_cbm_skip_file (tap_t *tap)
static int tap_tt_read_byte (tap_t *tap)
static int tap_tt_skip_pilot (tap_t *tap)
static int tap_tt_read_block (tap_t *tap, int type, uint8_t *buffer, unsigned int size)
static int tap_tt_read_header (tap_t *tap)
static int tap_tt_read_file (tap_t *tap)
static int tap_tt_skip_file (tap_t *tap)
static int tap_determine_pilot_type (tap_t *tap)
static int tap_find_header (tap_t *tap)
static int tap_read_file (tap_t *tap)
static int tap_skip_file (tap_t *tap)
tape_file_record_t * tap_get_current_file_record (tap_t *tap)
int tap_seek_start (tap_t *tap)
int tap_seek_to_file (tap_t *tap, unsigned int file_number)
int tap_seek_to_next_file (tap_t *tap, unsigned int allow_rewind)
int tap_read (tap_t *tap, uint8_t *buf, size_t size)
used by virtual devices
int tap_seek_to_offset (tap_t *tap, unsigned long offset)
unsigned long tap_get_offset (tap_t *tap)
void tap_get_header (tap_t *tap, uint8_t *name)
void tap_init (const tape_init_t *init)
Variables
static log_t tape_log = ((log_t)-2)
Logging goes here.
static int tap_pulse_short_min = 0x24
Default values.
static int tap_pulse_short_max = 0x36
static int tap_pulse_middle_min = 0x37
static int tap_pulse_middle_max = 0x49
static int tap_pulse_long_min = 0x4a
static int tap_pulse_long_max = 0x64
static int tap_pulse_tt_short_min = 0x0a
static int tap_pulse_tt_short_max = 0x22
static int tap_pulse_tt_long_min = 0x23
static int tap_pulse_tt_long_max = 0x36
static CLKLIST clklist []
Macro Definition Documentation
MAX_ERRORS
#define MAX_ERRORS 30
PILOT_MIN_LENGTH_CBM
#define PILOT_MIN_LENGTH_CBM 32
PILOT_MIN_LENGTH_TT
#define PILOT_MIN_LENGTH_TT 200
PILOT_TYPE_ANY
#define PILOT_TYPE_ANY -1
PILOT_TYPE_CBM
#define PILOT_TYPE_CBM 0
PILOT_TYPE_TT
#define PILOT_TYPE_TT 1
TAP_DEBUG
#define TAP_DEBUG 0
TAP_PULSE_LONG
#define TAP_PULSE_LONG (x) ((x) >= tap_pulse_long_min && (x) <= tap_pulse_long_max)
TAP_PULSE_MIDDLE
#define TAP_PULSE_MIDDLE (x) ((x) >= tap_pulse_middle_min && (x) <= tap_pulse_middle_max)
TAP_PULSE_SHORT
#define TAP_PULSE_SHORT (x) ((x) >= tap_pulse_short_min && (x) <= tap_pulse_short_max)
TAP_PULSE_TT_LONG
#define TAP_PULSE_TT_LONG (x) ((x) >= tap_pulse_tt_long_min && (x) <= tap_pulse_tt_long_max)
TAP_PULSE_TT_SHORT
#define TAP_PULSE_TT_SHORT (x) ((x) >= tap_pulse_tt_short_min && (x) <= tap_pulse_tt_short_max)
TT_BLOCK_TYPE_DATA
#define TT_BLOCK_TYPE_DATA 0
TT_BLOCK_TYPE_HEADER
#define TT_BLOCK_TYPE_HEADER 1
Function Documentation
tap_cbm_read_bit()
static int tap_cbm_read_bit (tap_t * tap) inline static
Referenced by tap_cbm_read_byte().
tap_cbm_read_block()
static int tap_cbm_read_block (tap_t * tap, uint8_t * buffer, int size) static
NOTE: parameter "size" must equal expected block size + 1 (for parity byte)
Referenced by tap_cbm_read_file_prg(), tap_cbm_read_file_seq(), tap_cbm_read_header(), and tap_cbm_skip_file().
tap_cbm_read_block_once()
static int tap_cbm_read_block_once (tap_t * tap, int * pass, uint8_t * buffer, int * size, int * error_buf, int * error_count) static
< tape senses both falling edges and rising edges, normal tape blocks end with a medium and a short pulse
Referenced by tap_cbm_read_block().
tap_cbm_read_byte()
static int tap_cbm_read_byte (tap_t * tap) static
Referenced by tap_cbm_read_block_once(), and tap_cbm_skip_pilot().
tap_cbm_read_file()
static int tap_cbm_read_file (tap_t * tap) static
Referenced by tap_read_file().
tap_cbm_read_file_prg()
static int tap_cbm_read_file_prg (tap_t * tap) static
Referenced by tap_cbm_read_file().
tap_cbm_read_file_seq()
static int tap_cbm_read_file_seq (tap_t * tap) static
Referenced by tap_cbm_read_file().
tap_cbm_read_header()
static int tap_cbm_read_header (tap_t * tap) static
< tape senses both falling edges and rising edges, normal tape blocks end with a medium and a short pulse
Referenced by tap_cbm_read_file(), and tap_find_header().
tap_cbm_skip_file()
static int tap_cbm_skip_file (tap_t * tap) static
Referenced by tap_skip_file().
tap_cbm_skip_pilot()
static int tap_cbm_skip_pilot (tap_t * tap) static
Referenced by tap_cbm_read_block(), tap_cbm_read_block_once(), and tap_cbm_skip_file().
tap_close()
int tap_close (tap_t * tap)
Referenced by tape_image_close().
tap_create()
int tap_create (const char * name)
< write mode (binary)
Todo:
FIXME: saving v2 C16 format doesnt actually work
Todo:
FIXME: saving v2 C16 format doesnt actually work
Referenced by tape_image_create().
tap_determine_pilot_type()
static int tap_determine_pilot_type (tap_t * tap) static
Referenced by tap_read_file(), and tap_skip_file().
tap_find_header()
static int tap_find_header (tap_t * tap) static
Referenced by tap_seek_to_next_file().
tap_find_pilot()
static int tap_find_pilot (tap_t * tap, int type) static
count = fread(&data, 1, 256, tap->fd);
{ startCBM+=countCBM+1; countCBM = 0; }
{ startTT+=countTT+1; countTT = 0; }
{ startTT+=countTT; countTT = 1; }
{ startTT+=countTT+1; countTT = 0; }
Referenced by tap_cbm_read_block(), tap_cbm_read_file_prg(), tap_cbm_read_file_seq(), tap_cbm_skip_file(), and tap_find_header().
tap_get_clockspeed()
static int tap_get_clockspeed (int system, int video) static
Referenced by tap_header_read().
tap_get_current_file_record()
tape_file_record_t * tap_get_current_file_record (tap_t * tap)
Referenced by tape_get_current_file_record().
tap_get_header()
void tap_get_header (tap_t * tap, uint8_t * name)
Referenced by tape_get_header().
tap_get_offset()
unsigned long tap_get_offset (tap_t * tap)
Referenced by tape_get_offset().
tap_get_pulse()
static int tap_get_pulse (tap_t * tap, int * pos_advance) inline static
Referenced by tap_cbm_read_bit(), tap_cbm_read_byte(), tap_cbm_skip_pilot(), tap_find_header(), and tap_tt_read_byte().
tap_header_read()
static int tap_header_read (tap_t * tap, FILE * fd) static
Referenced by tap_open().
tap_init()
void tap_init (const tape_init_t * init)
tap_new()
static tap_t * tap_new (void) static
Referenced by tap_open().
tap_open()
tap_t * tap_open (const char * name, unsigned int * read_only)
< read/write mode
< read mode (binary)
Referenced by tape_image_open().
tap_read()
int tap_read (tap_t * tap, uint8_t * buf, size_t size)
used by virtual devices
Referenced by tape_read().
tap_read_file()
static int tap_read_file (tap_t * tap) static
Referenced by tap_read().
tap_seek_start()
int tap_seek_start (tap_t * tap)
Referenced by tap_seek_to_file(), tap_seek_to_next_file(), and tape_seek_start().
tap_seek_to_file()
int tap_seek_to_file (tap_t * tap, unsigned int file_number)
Referenced by tape_seek_to_file().
tap_seek_to_next_file()
int tap_seek_to_next_file (tap_t * tap, unsigned int allow_rewind)
Referenced by tap_read(), tap_seek_to_file(), and tape_seek_to_next_file().
tap_seek_to_offset()
int tap_seek_to_offset (tap_t * tap, unsigned long offset)
Referenced by tape_seek_to_offset().
tap_skip_file()
static int tap_skip_file (tap_t * tap) static
Referenced by tap_seek_to_next_file().
tap_tt_read_block()
static int tap_tt_read_block (tap_t * tap, int type, uint8_t * buffer, unsigned int size) static
Referenced by tap_tt_read_file(), tap_tt_read_header(), and tap_tt_skip_file().
tap_tt_read_byte()
static int tap_tt_read_byte (tap_t * tap) static
Todo:
FIXME: It would be better to decide whether a pulse is S or L by checking if it's shorter or longer than a threshold value computed when reading the pilot (instead of using fixed thresholds)
Referenced by tap_determine_pilot_type(), tap_tt_read_block(), and tap_tt_skip_pilot().
tap_tt_read_file()
static int tap_tt_read_file (tap_t * tap) static
Referenced by tap_read_file().
tap_tt_read_header()
static int tap_tt_read_header (tap_t * tap) static
Referenced by tap_find_header(), and tap_tt_read_file().
tap_tt_skip_file()
static int tap_tt_skip_file (tap_t * tap) static
Referenced by tap_skip_file().
tap_tt_skip_pilot()
static int tap_tt_skip_pilot (tap_t * tap) static
Referenced by tap_find_header(), and tap_tt_read_block().
Variable Documentation
clklist
CLKLIST clklist[] static
Initial value:
= {
    {  0 ,  0 , 985248 },
    {  0 ,  1 , 1022730 },
    {  0 ,  2 , 1022730 },
    {  0 ,  3 , 1023440 },
    {  1 ,  0 , 1108405 },
    {  1 ,  1 , 1022727 },
    {  2 ,  0 , (1773447 + 1) / 2 },
    {  2 ,  1 , (1789772 + 1) /2 },
    {  3 ,  0 , 1000000 },
    {  3 ,  1 , 1000000 },
    {  4 ,  0 , 985248 },
    {  4 ,  1 , 1022730 },
    {  5 ,  0 , 2000000 },
    {  5 ,  1 , 2000000 },
    { -1, -1, -1 }
}
Referenced by tap_get_clockspeed().
tap_pulse_long_max
int tap_pulse_long_max = 0x64 static
Referenced by tap_init().
tap_pulse_long_min
int tap_pulse_long_min = 0x4a static
Referenced by tap_init().
tap_pulse_middle_max
int tap_pulse_middle_max = 0x49 static
Referenced by tap_init().
tap_pulse_middle_min
int tap_pulse_middle_min = 0x37 static
Referenced by tap_init().
tap_pulse_short_max
int tap_pulse_short_max = 0x36 static
Referenced by tap_init().
tap_pulse_short_min
int tap_pulse_short_min = 0x24 static
Default values.
Call tap_init() to change.
Referenced by tap_init().
tap_pulse_tt_long_max
int tap_pulse_tt_long_max = 0x36 static
tap_pulse_tt_long_min
int tap_pulse_tt_long_min = 0x23 static
tap_pulse_tt_short_max
int tap_pulse_tt_short_max = 0x22 static
tap_pulse_tt_short_min
int tap_pulse_tt_short_min = 0x0a static
tape_log
log_t tape_log = ((log_t)-2) static
Logging goes here.
Referenced by tap_close(), tap_header_read(), and tap_init().