x128: drive/iec/cmdhd.h File Reference
cmdhd.h File Reference
#include "types.h"
#include "diskimage.h"
#include "rtc-72421.h"
#include "alarm.h"
#include "via.h"
#include "scsi.h"
#include "i8255a.h"
Data Structures
struct cmdhd_context_s
struct cmdbus_s
Typedefs
typedef struct cmdhd_context_s cmdhd_context_t
typedef struct cmdbus_s cmdbus_t
Functions
void cmdhd_shutdown (struct cmdhd_context_s *ctxptr)
void cmdhd_setup_context (struct diskunit_context_s *ctxptr)
void cmdhd_init (struct diskunit_context_s *ctxptr)
void cmdhd_reset (struct cmdhd_context_s *ctxptr)
void cmdhd_reset_soft (diskunit_context_t *drv)
void cmdhd_store (struct diskunit_context_s *ctxptr, uint16_t addr, uint8_t byte)
uint8_t cmdhd_read (struct diskunit_context_s *ctxptr, uint16_t addr)
uint8_t cmdhd_peek (struct diskunit_context_s *ctxptr, uint16_t addr)
int cmdhd_dump (diskunit_context_t *ctxptr, uint16_t addr)
int cmdhd_attach_image (disk_image_t *image, unsigned int unit)
int cmdhd_detach_image (disk_image_t *image, unsigned int unit)
int cmdhd_update_maxsize (unsigned int size, unsigned int unit)
int cmdhd_snapshot_write_module (cmdhd_context_t *drv, struct snapshot_s *s)
int cmdhd_snapshot_read_module (cmdhd_context_t *drv, struct snapshot_s *s)
void cmdbus_init (void)
Set all the inputs high, like the pull-up resistors do.
void cmdbus_update (void)
Calculate the data/bus values.
void cmdbus_patn_changed (int new, int old)
Update ALL TDE units when PATN changed.
Variables
cmdbus_t cmdbus
Typedef Documentation
cmdbus_t
typedef struct cmdbus_s cmdbus_t
cmdhd_context_t
typedef struct cmdhd_context_s cmdhd_context_t
Function Documentation
cmdbus_init()
void cmdbus_init (void)
Set all the inputs high, like the pull-up resistors do.
cmdbus_patn_changed()
void cmdbus_patn_changed (int new, int old)
Update ALL TDE units when PATN changed.
called from ramlink
cmdbus_update()
void cmdbus_update (void)
Calculate the data/bus values.
Referenced by set_pa(), and set_pc().
cmdhd_attach_image()
int cmdhd_attach_image (disk_image_t * image, unsigned int unit)
< HD in ASCII for CMDHD
Referenced by iec_drive_image_attach().
cmdhd_detach_image()
int cmdhd_detach_image (disk_image_t * image, unsigned int unit)
< HD in ASCII for CMDHD
Referenced by iec_drive_image_detach().
cmdhd_dump()
int cmdhd_dump (diskunit_context_t * ctxptr, uint16_t addr)
cmdhd_init()
void cmdhd_init (struct diskunit_context_s * ctxptr)
Referenced by iec_drive_init().
cmdhd_peek()
uint8_t cmdhd_peek (struct diskunit_context_s * ctxptr, uint16_t addr)
cmdhd_read()
uint8_t cmdhd_read (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memiec_init().
cmdhd_reset()
void cmdhd_reset (struct cmdhd_context_s * ctxptr)
Referenced by iec_drive_reset().
cmdhd_reset_soft()
void cmdhd_reset_soft (diskunit_context_t * drv)
cmdhd_setup_context()
void cmdhd_setup_context (struct diskunit_context_s * ctxptr)
Referenced by iec_drive_setup_context().
cmdhd_shutdown()
void cmdhd_shutdown (struct cmdhd_context_s * ctxptr)
alarm_destroy(hd->reset_alarm);
Referenced by iec_drive_shutdown().
cmdhd_snapshot_read_module()
int cmdhd_snapshot_read_module (cmdhd_context_t * drv, struct snapshot_s * s)
Referenced by iec_drive_snapshot_read().
cmdhd_snapshot_write_module()
int cmdhd_snapshot_write_module (cmdhd_context_t * drv, struct snapshot_s * s)
Referenced by iec_drive_snapshot_write().
cmdhd_store()
void cmdhd_store (struct diskunit_context_s * ctxptr, uint16_t addr, uint8_t byte)
Referenced by memiec_init().
cmdhd_update_maxsize()
int cmdhd_update_maxsize (unsigned int size, unsigned int unit)
Referenced by set_drive_fixed().
Variable Documentation
cmdbus
cmdbus_t cmdbus extern
Referenced by cmdbus_init(), cmdbus_update(), cmdhd_detach_image(), cmdhd_patn_changed(), cmdhd_reset(), get_pa(), get_pb(), set_pa(), and set_pc().