vsid: c64/c64_256k.h File Reference
c64_256k.h File Reference
#include "snapshot.h"
#include "types.h"
Functions
int c64_256k_resources_init (void)
void c64_256k_resources_shutdown (void)
int c64_256k_cmdline_options_init (void)
void c64_256k_init (void)
void c64_256k_reset (void)
void c64_256k_cia_set_vbank (int ciabank)
needed from c64gluelogic.c
void c64_256k_shutdown (void)
void c64_256k_ram_inject (uint16_t addr, uint8_t value)
void c64_256k_ram_segment0_store (uint16_t addr, uint8_t value)
void c64_256k_ram_segment1_store (uint16_t addr, uint8_t value)
void c64_256k_ram_segment2_store (uint16_t addr, uint8_t value)
void c64_256k_ram_segment3_store (uint16_t addr, uint8_t value)
uint8_t c64_256k_ram_segment0_read (uint16_t addr)
uint8_t c64_256k_ram_segment1_read (uint16_t addr)
uint8_t c64_256k_ram_segment2_read (uint16_t addr)
uint8_t c64_256k_ram_segment3_read (uint16_t addr)
int set_c64_256k_enabled (int value, int disable_reset)
int c64_256k_snapshot_write (struct snapshot_s *s)
int c64_256k_snapshot_read (struct snapshot_s *s)
uint8_t c64_256k_read (uint16_t addr)
void c64_256k_store (uint16_t addr, uint8_t byte)
Variables
int c64_256k_start
int c64_256k_enabled
Function Documentation
c64_256k_cia_set_vbank()
void c64_256k_cia_set_vbank (int ciabank)
needed from c64gluelogic.c
Referenced by perform_vbank_switch().
c64_256k_cmdline_options_init()
int c64_256k_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
c64_256k_init()
void c64_256k_init (void)
Referenced by machine_specific_init().
c64_256k_ram_inject()
void c64_256k_ram_inject (uint16_t addr, uint8_t value)
Referenced by memory_hacks_ram_inject().
c64_256k_ram_segment0_read()
uint8_t c64_256k_ram_segment0_read (uint16_t addr)
Referenced by c64_256k_init_config(), and zero_read_dma().
c64_256k_ram_segment0_store()
void c64_256k_ram_segment0_store (uint16_t addr, uint8_t value)
Referenced by c64_256k_init_config(), c64_256k_ram_inject(), zero_store(), and zero_store_dma().
c64_256k_ram_segment1_read()
uint8_t c64_256k_ram_segment1_read (uint16_t addr)
Referenced by c64_256k_init_config().
c64_256k_ram_segment1_store()
void c64_256k_ram_segment1_store (uint16_t addr, uint8_t value)
Referenced by c64_256k_init_config(), and c64_256k_ram_inject().
c64_256k_ram_segment2_read()
uint8_t c64_256k_ram_segment2_read (uint16_t addr)
Referenced by c64_256k_init_config().
c64_256k_ram_segment2_store()
void c64_256k_ram_segment2_store (uint16_t addr, uint8_t value)
Referenced by c64_256k_init_config(), and c64_256k_ram_inject().
c64_256k_ram_segment3_read()
uint8_t c64_256k_ram_segment3_read (uint16_t addr)
Referenced by c64_256k_init_config().
c64_256k_ram_segment3_store()
void c64_256k_ram_segment3_store (uint16_t addr, uint8_t value)
Referenced by c64_256k_init_config(), and c64_256k_ram_inject().
c64_256k_read()
uint8_t c64_256k_read (uint16_t addr)
c64_256k_reset()
void c64_256k_reset (void)
Referenced by c64_256k_activate(), and machine_specific_reset().
c64_256k_resources_init()
int c64_256k_resources_init (void)
Referenced by machine_resources_init().
c64_256k_resources_shutdown()
void c64_256k_resources_shutdown (void)
Referenced by machine_resources_shutdown().
c64_256k_shutdown()
void c64_256k_shutdown (void)
Referenced by machine_specific_shutdown().
c64_256k_snapshot_read()
int c64_256k_snapshot_read (struct snapshot_s * s)
Referenced by memhacks_snapshot_read_modules().
c64_256k_snapshot_write()
int c64_256k_snapshot_write (struct snapshot_s * s)
Referenced by memhacks_snapshot_write_modules().
c64_256k_store()
void c64_256k_store (uint16_t addr, uint8_t byte)
set_c64_256k_enabled()
int set_c64_256k_enabled (int value, int disable_reset)
Referenced by c64_256k_snapshot_read(), memhacks_snapshot_read_modules(), and set_memory_hack().
Variable Documentation
c64_256k_enabled
int c64_256k_enabled extern
Referenced by c64_256k_init_config(), c64_256k_reset(), c64_256k_shutdown(), perform_vbank_switch(), set_c64_256k_base(), set_c64_256k_enabled(), set_c64_256k_filename(), zero_read_dma(), zero_store(), and zero_store_dma().
c64_256k_start
int c64_256k_start extern
Referenced by c64_256k_snapshot_read(), c64_256k_snapshot_write(), and set_c64_256k_base().