vsid: c64/vsid-debugcart.c File Reference
vsid-debugcart.c File Reference
#include "vice.h"
#include "archdep.h"
#include "cartridge.h"
#include "cmdline.h"
#include "lib.h"
#include "resources.h"
#include "machine.h"
#include "maincpu.h"
#include "vsid-debugcart.h"
Functions
void debugcart_store (uint16_t addr, uint8_t value)
static int set_debugcart_enabled (int value, void *param)
int debugcart_resources_init (void)
void debugcart_resources_shutdown (void)
int debugcart_cmdline_options_init (void)
Variables
static int debugcart_enabled = 0
static const resource_int_t resources_i []
static const cmdline_option_t cart_cmdline_options []
Function Documentation
debugcart_cmdline_options_init()
int debugcart_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
debugcart_resources_init()
int debugcart_resources_init (void)
Referenced by machine_resources_init().
debugcart_resources_shutdown()
void debugcart_resources_shutdown (void)
Referenced by machine_resources_shutdown().
debugcart_store()
void debugcart_store (uint16_t addr, uint8_t value)
Todo:
FIXME: perhaps print a timestamp too
Referenced by sid_store_d700().
set_debugcart_enabled()
static int set_debugcart_enabled (int value, void * param) static
Variable Documentation
cart_cmdline_options
const cmdline_option_t cart_cmdline_options[] static
Initial value:
=
{
    { "-debugcart", SET_RESOURCE,  0 ,
      NULL, NULL, "DebugCartEnable", (resource_value_t)1,
      NULL, "Enable Debug cartridge" },
    { "+debugcart", SET_RESOURCE,  0 ,
      NULL, NULL, "DebugCartEnable", (resource_value_t)0,
      NULL, "Disable Debug cartridge" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by debugcart_cmdline_options_init().
debugcart_enabled
int debugcart_enabled = 0 static
Referenced by debugcart_store(), and set_debugcart_enabled().
resources_i
const resource_int_t resources_i[] static
Initial value:
= {
    { "DebugCartEnable", 0, RES_EVENT_STRICT, 0,
      &debugcart_enabled, set_debugcart_enabled, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by debugcart_resources_init().