x128: arch/gtk3/widgets/settings_mmc64.c File Reference
settings_mmc64.c File Reference
Settings widget to control MMC64 resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "c64cart.h"
#include "cartridge.h"
#include "log.h"
#include "vice_gtk3.h"
#include "settings_mmc64.h"
Macros
#define CARTNAME CARTRIDGE_NAME_MMC64
Temporary define to make editing easier.
#define NUM_COLS 4
Functions
static void on_enable_toggled (GtkWidget *check, gpointer user_data)
Handler for the 'toggled' event of the "MMC64 Enabled" widget.
static void save_filename_callback (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the save-dialog response handler.
static void on_save_clicked (GtkWidget *widget, gpointer user_data)
Handler for the "clicked" event of the Save Image button.
static void on_flush_clicked (GtkWidget *widget, gpointer user_data)
Handler for the "clicked" event of the Flush Image button.
static GtkWidget * create_mmc64_enable_widget (void)
Create widget to toggle MMC64 emulation.
static GtkWidget * create_mmc64_jumper_widget (void)
Create widget to toggle the MMC64 flash jumper.
static GtkWidget * create_mmc64_revision_widget (void)
Create widget to set the MMC64 revision.
static int create_bios_image_layout (GtkWidget *grid, int row, int columns)
Add BIOS widgets to main grid.
static int create_card_image_layout (GtkWidget *grid, int row, int columns)
Add widgets for the SD/MCC card.
GtkWidget * settings_mmc64_widget_create (GtkWidget *parent)
Create widget to control MMC64 resources.
Variables
static const vice_gtk3_radiogroup_entry_t revisions []
List of revisions.
static const vice_gtk3_radiogroup_entry_t card_types []
List of memory card types.
static GtkWidget * bios_filename = NULL
BIOS filename entry.
static GtkWidget * card_filename = NULL
SD card widget filename entry.
Detailed Description
Settings widget to control MMC64 resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
CARTNAME
#define CARTNAME CARTRIDGE_NAME_MMC64
Temporary define to make editing easier.
NUM_COLS
#define NUM_COLS 4
Function Documentation
create_bios_image_layout()
static int create_bios_image_layout (GtkWidget * grid, int row, int columns) static
Add BIOS widgets to main grid.
Parameters
[in] grid main grid
[in] row row in grid to add widgets
[in] columns number of columns in grid, for proper column span
Returns
row in grid to add more widgets
< see manual
< see manual
Referenced by settings_mmc64_widget_create().
create_card_image_layout()
static int create_card_image_layout (GtkWidget * grid, int row, int columns) static
Add widgets for the SD/MCC card.
Parameters
[in] grid main grid
[in] row row in grid to add widgets
[in] columns number of columns in grid, for proper column span
Returns
row in grid to add more widgets
< see manual
< see manual
Referenced by settings_mmc64_widget_create().
create_mmc64_enable_widget()
static GtkWidget * create_mmc64_enable_widget (void) static
Create widget to toggle MMC64 emulation.
Returns
GtkCheckButton
< see manual
< mmc64.c, spi-sdcard.c
Referenced by settings_mmc64_widget_create().
create_mmc64_jumper_widget()
static GtkWidget * create_mmc64_jumper_widget (void) static
Create widget to toggle the MMC64 flash jumper.
Returns
GtkSwitch
Referenced by settings_mmc64_widget_create().
create_mmc64_revision_widget()
static GtkWidget * create_mmc64_revision_widget (void) static
Create widget to set the MMC64 revision.
Returns
GtkGrid
Referenced by settings_mmc64_widget_create().
on_enable_toggled()
static void on_enable_toggled (GtkWidget * check, gpointer user_data) static
Handler for the 'toggled' event of the "MMC64 Enabled" widget.
Parameters
[in,out] check check button
[in] user_data extra event data (unused)
< see manual
< see manual
< mmc64.c, spi-sdcard.c
< see manual
< see manual
< see manual
< mmc64.c, spi-sdcard.c
< see manual
< see manual
< see manual
Referenced by create_mmc64_enable_widget().
on_flush_clicked()
static void on_flush_clicked (GtkWidget * widget, gpointer user_data) static
Handler for the "clicked" event of the Flush Image button.
Parameters
[in] widget button
[in] user_data unused
< mmc64.c, spi-sdcard.c
< see manual
Referenced by create_bios_image_layout().
on_save_clicked()
static void on_save_clicked (GtkWidget * widget, gpointer user_data) static
Handler for the "clicked" event of the Save Image button.
Parameters
[in] widget button
[in] user_data unused
< see manual
Referenced by create_bios_image_layout().
save_filename_callback()
static void save_filename_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the save-dialog response handler.
Parameters
[in,out] dialog save-file dialog
[in,out] filename filename
[in] data extra data (unused)
< mmc64.c, spi-sdcard.c
< see manual
Referenced by on_save_clicked().
settings_mmc64_widget_create()
GtkWidget * settings_mmc64_widget_create (GtkWidget * parent)
Create widget to control MMC64 resources.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
< see manual
< see manual
Variable Documentation
bios_filename
GtkWidget* bios_filename = NULL static
BIOS filename entry.
Referenced by create_bios_image_layout(), and on_enable_toggled().
card_filename
GtkWidget* card_filename = NULL static
SD card widget filename entry.
Referenced by create_card_image_layout().
card_types
const vice_gtk3_radiogroup_entry_t card_types[] static
Initial value:
= {
    { "Auto", MMC64_TYPE_AUTO },
    { "MMC",  MMC64_TYPE_MMC },
    { "SD",   MMC64_TYPE_SD },
    { "SDHC", MMC64_TYPE_SDHC },
    { NULL,   -1 }
}
List of memory card types.
Referenced by create_card_image_layout().
revisions
const vice_gtk3_radiogroup_entry_t revisions[] static
Initial value:
= {
    { "Rev. A", MMC64_REV_A },
    { "Rev. B", MMC64_REV_B },
    { NULL,     -1 }
}
List of revisions.
Referenced by create_mmc64_revision_widget().