x128: soundmovie_funcs_t Struct Reference
soundmovie_funcs_t Struct Reference
#include <soundmovie.h>
Data Fields
int(* init)(int speed, int channels, soundmovie_buffer_t **buffer)
int(* encode)(soundmovie_buffer_t *buffer)
void(* close)(void)
Field Documentation
close
void(* soundmovie_funcs_t::close) (void)
Referenced by soundmovie_close().
encode
int(* soundmovie_funcs_t::encode) (soundmovie_buffer_t *buffer)
Referenced by soundmovie_write().
init
int(* soundmovie_funcs_t::init) (int speed, int channels, soundmovie_buffer_t **buffer)
Referenced by soundmovie_init().
The documentation for this struct was generated from the following file:
arch/shared/sounddrv/soundmovie.h