vsid: arch/shared/hotkeys/parser.c File Reference
parser.c File Reference
Parsing functions for hotkeys.
#include "vice.h"
#include <stdbool.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include "archdep_defs.h"
#include "archdep_get_vice_hotkeysdir.h"
#include "archdep_path_is_relative.h"
#include "boolexpr.h"
#include "ifstack.h"
#include "lib.h"
#include "log.h"
#include "symtab.h"
#include "sysfile.h"
#include "textfilereader.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uihotkeys.h"
#include "util.h"
#include "vhkkeysyms.h"
#include "parser.h"
#include "vhkdebug.h"
Data Structures
struct debug_args_s
Object for mapping of !DEBUG arguments to boolean.
struct predef_symbol_s
Predefined symbol declaration.
Macros
#define ARRAY_LEN(arr) (sizeof (arr) / sizeof (arr[0]))
Define this to dump the symbol table on stdout when parsing a hotkeys file.
Typedefs
typedef struct debug_args_s debug_args_t
Object for mapping of !DEBUG arguments to boolean.
typedef struct predef_symbol_s predef_symbol_t
Predefined symbol declaration.
Functions
static void vhk_parser_error (const char *fmt,...)
Log error message.
static void vhk_parser_warning (const char *fmt,...)
Log warning.
static char * vhk_parser_strtrim (const char *s)
Strip leading and trailing whitespace.
static bool no_more_tokens (const char *s)
Check if string only contains whitespace or an inline comment.
static bool vhk_parser_open_file (const char *path)
Open file, optionally using the VICE hotkeys dir as search path.
static vhk_keyword_id_t vhk_parser_get_keyword_id (const char *name, const char **endptr)
currently unused, but might be required again later, so do not delete
static uint32_t parser_get_modifier (const char *s, const char **endptr)
Parse string for modifier.
static bool vhk_parser_get_keysym_and_modmask (const char *line, const char **endptr, uint32_t *vice_keysym, uint32_t *vice_modmask, uint32_t *arch_keysym, uint32_t *arch_modmask)
Parse string for keysym and optional modifiers.
static bool vhk_parser_do_clear (const char *line)
Handler for the '!CLEAR' keyword.
static bool vhk_parser_do_debug (const char *line)
Handler for the '!DEBUG' keyword.
static char * parse_quoted_argument (const char *text)
Parse quoted argument, removing any (escaped) quotes.
static bool vhk_parser_do_include (const char *line)
Handler for the '!INCLUDE' a keyword.
static bool vhk_parser_do_undef (const char *line)
Handler for the '!UNDEF' keyword.
static int get_identifier (const char *text, const char **endptr)
Get identifier and return its token ID.
static bool vhk_parser_do_if (const char *line)
Handler for the !IF keyword.
static bool vhk_parser_do_else (const char *line)
Handler for the !ELSE keyword.
static bool vhk_parser_do_endif (const char *line)
Handler for the !ENDIF keyword.
static bool vhk_parser_do_warning (const char *line)
Handler for the !WARNING keyword.
static bool vhk_parser_handle_keyword (const char *line)
Handle a keyword.
static bool vhk_parser_handle_mapping (const char *line)
Handle a hotkey mapping.
bool vhk_parser_parse (const char *path)
Parse hotkeys file.
static void add_predef_symbols (void)
Add compile time predefined symbols.
static void add_machine_symbols (void)
Add runtime predefined symbols.
void vhk_parser_init (void)
Initialize parser for use.
void vhk_parser_shutdown (void)
Clean up resources used by the parser.
Variables
static const vhk_keyword_t vhk_keyword_list []
Hotkeys parser keyword list.
static const debug_args_t debug_arglist []
Mapping of !DEBUG arguments to boolean.
static bool vhk_debug = false
Debug messages enable flag.
textfile_reader_t reader
Global text file reader instance.
static char identbuf [256]
Buffer for identifiers found in conditionals.
static const predef_symbol_t predef_symbols []
List of predefined symbols known at compile time.
Detailed Description
Parsing functions for hotkeys.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
ARRAY_LEN
#define ARRAY_LEN (arr) (sizeof (arr) / sizeof (arr[0]))
Define this to dump the symbol table on stdout when parsing a hotkeys file.
Array length helper
Parameters
[in] arr array name
Typedef Documentation
debug_args_t
typedef struct debug_args_s debug_args_t
Object for mapping of !DEBUG arguments to boolean.
predef_symbol_t
typedef struct predef_symbol_s predef_symbol_t
Predefined symbol declaration.
Function Documentation
add_machine_symbols()
static void add_machine_symbols (void) static
Add runtime predefined symbols.
Referenced by vhk_parser_init().
add_predef_symbols()
static void add_predef_symbols (void) static
Add compile time predefined symbols.
Referenced by vhk_parser_init().
get_identifier()
static int get_identifier (const char * text, const char ** endptr) static
Get identifier and return its token ID.
Parse text for an identifier in the form [a-zA-Z_][a-zA-Z0-9_]+
Parameters
[in] text text to parse
[in] endptr pointer to first non-identifier character in text
Returns
BEXPR_FALSE or BEXPR_TRUE, or BEXPR_INVALID (-1) on error
Referenced by vhk_parser_do_if().
no_more_tokens()
static bool no_more_tokens (const char * s) static
Check if string only contains whitespace or an inline comment.
Parameters
[in] s string to check
Returns
true if only whitespace or comment
Referenced by vhk_parser_do_clear(), vhk_parser_do_else(), and vhk_parser_do_endif().
parse_quoted_argument()
static char * parse_quoted_argument (const char * text) static
Parse quoted argument, removing any (escaped) quotes.
Parameters
[in] text text to parse
Returns
path stripped from quotes or NULL on error
Note
free result with lib_free() after use
Referenced by vhk_parser_do_include().
parser_get_modifier()
static uint32_t parser_get_modifier (const char * s, const char ** endptr) static
Parse string for modifier.
Parse string s for a known modifier name closed by '>', store pointer to closing angled bracket in endptr (if not NULL). Matching is done case-insensitive.
Parameters
[in] s string to parse
[out] endptr pointer to closing bracket (can be NULL)
Returns
modifier mask or VHK_MOD_NONE (0) when no valid modifier found
Referenced by vhk_parser_get_keysym_and_modmask().
vhk_parser_do_clear()
static bool vhk_parser_do_clear (const char * line) static
Handler for the '!CLEAR' keyword.
Clears all hotkeys registered.
Parameters
[in] line text to parse (unused)
Returns
bool
Referenced by vhk_parser_handle_keyword().
vhk_parser_do_debug()
static bool vhk_parser_do_debug (const char * line) static
Handler for the '!DEBUG' keyword.
Enable/disable debugging messages.
Parameters
[in] line text to parse (unused)
Returns
bool
Todo:
report debug on/off as part of debugging, but only mention 'off' if it was previously 'on': this way using '!debug off' at the start of a vhk file won't trigger a debugging message.
Referenced by vhk_parser_handle_keyword().
vhk_parser_do_else()
static bool vhk_parser_do_else (const char * line) static
Handler for the !ELSE keyword.
Parameters
[in] line text after the keyword (ignored)
Returns
true on success
Referenced by vhk_parser_handle_keyword().
vhk_parser_do_endif()
static bool vhk_parser_do_endif (const char * line) static
Handler for the !ENDIF keyword.
Parameters
[in] line text after the keyword (ignored)
Returns
true on success
Referenced by vhk_parser_handle_keyword().
vhk_parser_do_if()
static bool vhk_parser_do_if (const char * line) static
Handler for the !IF keyword.
Parse line for condition and push condition on the if-stack. A condition may consist of predefined identifiers (such as "C64", "GTK3" or "UNIX"), boolean operators "!" (not), "||" (or) or "&&" (and). Parentheses are supported as are the special identifiers "false" and "true". Nesting of IF/ELSE is supported.
See documentation (TODO) for a more thorough explanation.
Parameters
[in] line text after the keyword
Returns
true on success
Referenced by vhk_parser_handle_keyword().
vhk_parser_do_include()
static bool vhk_parser_do_include (const char * line) static
Handler for the '!INCLUDE' a keyword.
Parameters
[in] line text to parse, must start after "!INCLUDE"
Returns
bool
Note
errors are reported with vhk_parser_error()
Referenced by vhk_parser_handle_keyword().
vhk_parser_do_undef()
static bool vhk_parser_do_undef (const char * line) static
Handler for the '!UNDEF' keyword.
Parameters
[in] line text to parse
Returns
bool
Note
errors are reported with log_message()
Todo:
Support two windows for x128
Referenced by vhk_parser_handle_keyword().
vhk_parser_do_warning()
static bool vhk_parser_do_warning (const char * line) static
Handler for the !WARNING keyword.
Log warning on stdout using line as its text.
Parameters
[in] line text after the keyword
Returns
true on success
Referenced by vhk_parser_handle_keyword().
vhk_parser_error()
static void vhk_parser_error (const char * fmt, ...) static
Log error message.
Log error message on vhk log using printf-style format string, including the current filename and line number.
Parameters
[in] fmt format string
[in] ... arguments for fmt (optional)
Referenced by get_identifier(), parse_quoted_argument(), vhk_parser_do_clear(), vhk_parser_do_debug(), vhk_parser_do_else(), vhk_parser_do_endif(), vhk_parser_do_if(), vhk_parser_do_include(), vhk_parser_do_undef(), vhk_parser_get_keysym_and_modmask(), vhk_parser_handle_keyword(), vhk_parser_handle_mapping(), and vhk_parser_open_file().
vhk_parser_get_keysym_and_modmask()
static bool vhk_parser_get_keysym_and_modmask (const char * line, const char ** endptr, uint32_t * vice_keysym, uint32_t * vice_modmask, uint32_t * arch_keysym, uint32_t * arch_modmask) static
Parse string for keysym and optional modifiers.
Parameters
[in] line string to parse
[out] endptr first character in line past the key name
[out] vice_keysym VICE modifier mask
[out] vice_modmask VICE keysym
[out] arch_keysym arch keysym
[out] arch_modmask arch modifier mask
Returns
true on success
Referenced by vhk_parser_do_undef(), and vhk_parser_handle_mapping().
vhk_parser_get_keyword_id()
static vhk_keyword_id_t vhk_parser_get_keyword_id (const char * name, const char ** endptr) static
currently unused, but might be required again later, so do not delete
Scan string for keyword
Scan string name for a keyword and return keyword ID on match.
The input is allowed to have trailing characters starting with whitespace, which could be the keyword's argument list. The input is expected to not contain the keyword indicator token. Matching is done case-insensitive.
Parameters
[in] name string with possible keyword
Returns
keyword ID when found, -1 otherwise
Referenced by vhk_parser_handle_keyword().
vhk_parser_handle_keyword()
static bool vhk_parser_handle_keyword (const char * line) static
Handle a keyword.
Parameters
[in] line text to parse, must start after the '!' indicator
Returns
bool
Note
errors are reported with log_message()
Referenced by vhk_parser_parse().
vhk_parser_handle_mapping()
static bool vhk_parser_handle_mapping (const char * line) static
Handle a hotkey mapping.
Parse line for a hotkey mapping, set hotkey on success.
Parameters
[in] line string to parse, expected to be trimmed
Returns
bool
Note
errors are reported with log_message()
Todo:
support quotes?
Referenced by vhk_parser_parse().
vhk_parser_init()
void vhk_parser_init (void)
Initialize parser for use.
Set up and fill the symbol table. This function should only be called once, during general init, and not before each call to vkh_parser_parse().
Referenced by ui_hotkeys_init().
vhk_parser_open_file()
static bool vhk_parser_open_file (const char * path) static
Open file, optionally using the VICE hotkeys dir as search path.
Try opening path as-is first, if that fails prepend the VICE hotkeys directory, if path is relative, and try that.
Parameters
[in] path path to file to open
Returns
true on success
Referenced by vhk_parser_do_include(), and vhk_parser_parse().
vhk_parser_parse()
bool vhk_parser_parse (const char * path)
Parse hotkeys file.
Parameters
[in] path path to hotkeys file
Returns
true on success
Todo:
check if EOF or error
Referenced by ui_hotkeys_load().
vhk_parser_shutdown()
void vhk_parser_shutdown (void)
Clean up resources used by the parser.
Free symbol table. This function should only be called once, during general shutdown, and not before each call to vkh_parser_parse().
Referenced by ui_hotkeys_shutdown().
vhk_parser_strtrim()
static char * vhk_parser_strtrim (const char * s) static
Strip leading and trailing whitespace.
Remove leading and trailing whitespace from string s.
Parameters
[in] s string
Returns
heap-allocated string
Note
free with lib_free()
Todo:
move into src/lib.c?
Referenced by vhk_parser_parse().
vhk_parser_warning()
static void vhk_parser_warning (const char * fmt, ...) static
Log warning.
Log warning on vhk log using printf-style format string, including the current filename and line number.
Parameters
[in] fmt format string
[in] ... arguments for fmt (optional)
Referenced by vhk_parser_do_undef(), and vhk_parser_handle_mapping().
Variable Documentation
debug_arglist
const debug_args_t debug_arglist[] static
Initial value:
= {
    { "enable",     true },
    { "disable",    false },
    { "on",         true },
    { "off",        false }
}
Mapping of !DEBUG arguments to boolean.
Referenced by vhk_parser_do_debug().
identbuf
char identbuf[256] static
Buffer for identifiers found in conditionals.
Referenced by get_identifier().
predef_symbols
const predef_symbol_t predef_symbols[] static
Initial value:
= {
    {   "false",    false },
    {   "true",     true  },
    {   "GTK3",
        false
    },
    {   "SDL1",
        true
    },
    {   "SDL2",
        false
    },
    {   "HAVE_DEBUG",
        false
    },
    {   "HAVE_FFMPEG",
        false
    },
    {   "UNIX",
        true
    },
    {   "MACOS",
        false
    },
    {   "WINDOWS",
        false
    }
}
List of predefined symbols known at compile time.
This doesn't include the machine names, since those need to be determined at runtime :(
Referenced by add_predef_symbols().
reader
textfile_reader_t reader
Global text file reader instance.
Stack based file reader, initialized and cleaned up in vhk_parser_parse().
Referenced by textfile_reader_close(), textfile_reader_filename(), textfile_reader_free(), textfile_reader_init(), textfile_reader_linenum(), textfile_reader_open(), textfile_reader_read(), vhk_parser_do_clear(), vhk_parser_do_undef(), vhk_parser_error(), vhk_parser_open_file(), vhk_parser_parse(), and vhk_parser_warning().
vhk_debug
bool vhk_debug = false static
Debug messages enable flag.
Referenced by vhk_parser_do_clear(), vhk_parser_do_debug(), vhk_parser_do_undef(), vhk_parser_handle_mapping(), and vhk_parser_parse().
vhk_keyword_list
const vhk_keyword_t vhk_keyword_list[] static
Initial value:
= {
    { "clear",      VHK_KW_ID_CLEAR,    0, 0,
      "!CLEAR",
      "Clear all hotkeys" },
    { "debug",      VHK_KW_ID_DEBUG,    1, 1,
      "!DEBUG <enable|disable|on|off>",
      "Turn debugging output on or off" },
    { "else",       VHK_KW_ID_ELSE,     0, 0,
      "!ELSE",
      "Execute following statement(s) if the preceding !IF <condition> is not met" },
    { "endif",      VHK_KW_ID_ENDIF,    0, 0,
      "!ENDIF",
      "End of !if [!else] block" },
    { "if",         VHK_KW_ID_IF,       1, 1,
      "!IF <condition>",
      "Execute following statement(s) if <condition> is met" },
    { "include",    VHK_KW_ID_INCLUDE,  1, 1,
      "!INCLUDE <path>",
      "Start parsing hotkeys file <path>" },
    { "undef",      VHK_KW_ID_UNDEF,    1, 1,
      "!UNDEF <modifiers+key>",
      "Undefine a hotkey by <modifiers+key>" },
    { "warning",    VHK_KW_ID_WARNING,  1, 1,
      "!WARNING <message>",
      "Show warning in hotkeys log" }
}
Hotkeys parser keyword list.
List of parser keywords with ID and argument count.
Note
The array needs to stay in alphabetical order.
Referenced by vhk_parser_get_keyword_id().