vsid: arch/gtk3/widgets/sounddriverwidget.c File Reference
sounddriverwidget.c File Reference
GTK3 sound driver widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "basewidgets.h"
#include "lib.h"
#include "ui.h"
#include "resources.h"
#include "vsync.h"
#include "sound.h"
#include "widgethelpers.h"
#include "debug_gtk3.h"
#include "sounddriverwidget.h"
Functions
static void on_device_changed (GtkWidget *widget, gpointer user_data)
Handler for the "changed" event of the device combobox.
static GtkWidget * create_device_combobox (void)
Create combobox with sound devices.
static GtkWidget * create_argument_entry (void)
Create the 'device driver argument' text entry box.
static GtkWidget * create_label (const char *text)
Create left-aligned labe with Pango markup.
GtkWidget * sound_driver_widget_create (void)
Create the sound driver/device widget.
Detailed Description
GTK3 sound driver widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_argument_entry()
static GtkWidget * create_argument_entry (void) static
Create the 'device driver argument' text entry box.
Returns
GtkEntry
Referenced by sound_driver_widget_create().
create_device_combobox()
static GtkWidget * create_device_combobox (void) static
Create combobox with sound devices.
Returns
combobox
Referenced by sound_driver_widget_create().
create_label()
static GtkWidget * create_label (const char * text) static
Create left-aligned labe with Pango markup.
Parameters
[in] text label text
Returns
GtkLabel
Referenced by sound_driver_widget_create().
on_device_changed()
static void on_device_changed (GtkWidget * widget, gpointer user_data) static
Handler for the "changed" event of the device combobox.
Parameters
[in] widget widget triggering the event
[in] user_data data for the event (unused)
Referenced by create_device_combobox().
sound_driver_widget_create()
GtkWidget * sound_driver_widget_create (void)
Create the sound driver/device widget.
Returns
driver widget (GtkGrid)
Referenced by create_inner_grid().