vsid: mem.h File Reference
mem.h File Reference
#include "types.h"
Data Structures
struct mem_ioreg_list_s
Macros
#define MEM_BANK_ISARRAY 0x01
part of a bank group, eg "ram00, ram01 ..."
#define MEM_BANK_ISARRAYFIRST 0x02
first in a bank group, eg "ram00"
#define MEM_BANK_ISARRAYLAST 0x04
last in a bank group, eg "ramff"
Typedefs
typedef uint8_t read_func_t(uint16_t addr)
typedef read_func_t * read_func_ptr_t
typedef void store_func_t(uint16_t addr, uint8_t value)
typedef store_func_t * store_func_ptr_t
typedef struct mem_ioreg_list_s mem_ioreg_list_t
Functions
void mem_initialize_memory (void)
void mem_powerup (void)
Initialize RAM for power-up.
int mem_load (void)
void mem_get_basic_text (uint16_t *start, uint16_t *end)
void mem_set_basic_text (uint16_t start, uint16_t end)
void mem_toggle_watchpoints (int flag, void *context)
int mem_rom_trap_allowed (uint16_t addr)
void mem_mmu_translate (unsigned int addr, uint8_t **base, int *start, int *limit)
void mem_color_ram_to_snapshot (uint8_t *color_ram)
void mem_color_ram_from_snapshot (uint8_t *color_ram)
uint8_t mem_read_screen (uint16_t addr)
void mem_inject (uint32_t addr, uint8_t value)
void mem_inject_key (uint16_t addr, uint8_t value)
const char ** mem_bank_list (void)
Memory access functions for the monitor.
const int * mem_bank_list_nos (void)
int mem_bank_from_name (const char *name)
return bank number for a given literal bank name
int mem_bank_index_from_bank (int bank)
return current index for a given bank
int mem_bank_flags_from_bank (int bank)
uint8_t mem_bank_read (int bank, uint16_t addr, void *context)
read memory with side-effects
uint8_t mem_bank_peek (int bank, uint16_t addr, void *context)
read memory without side-effects
void mem_bank_write (int bank, uint16_t addr, uint8_t byte, void *context)
void mem_bank_poke (int bank, uint16_t addr, uint8_t byte, void *context)
used by monitor if sfx off
uint8_t mem_peek_with_config (int config, uint16_t addr, void *context)
int mem_get_current_bank_config (void)
void mem_get_screen_parameter (uint16_t *base, uint8_t *rows, uint8_t *columns, int *bank)
void mem_get_cursor_parameter (uint16_t *screen_addr, uint8_t *cursor_column, uint8_t *line_length, int *blinking)
mem_ioreg_list_t * mem_ioreg_list_get (void *context)
int mem_write_snapshot_module (struct snapshot_s *s, int save_roms)
int mem_read_snapshot_module (struct snapshot_s *s)
Variables
read_func_ptr_t * _mem_read_tab_ptr
Pointers to the currently used memory read and write tables.
store_func_ptr_t * _mem_write_tab_ptr
read_func_ptr_t * _mem_read_tab_ptr_dummy
store_func_ptr_t * _mem_write_tab_ptr_dummy
uint8_t mem_ram []
The C64 memory.
uint8_t * mem_page_zero
uint8_t * mem_page_one
uint8_t * mem_color_ram_cpu
uint8_t * mem_color_ram_vicii
uint8_t * mem_chargen_rom_ptr
Pointer to the chargen ROM.
read_func_t rom_read
read_func_t rom_trap_read
read_func_t zero_read
read_func_t zero_read_dma
store_func_t rom_store
store_func_t rom_trap_store
store_func_t zero_store
store_func_t zero_store_dma
read_func_t mem_read
store_func_t mem_store
read_func_t mem_dma_read
store_func_t mem_dma_store
Macro Definition Documentation
MEM_BANK_ISARRAY
#define MEM_BANK_ISARRAY 0x01
part of a bank group, eg "ram00, ram01 ..."
MEM_BANK_ISARRAYFIRST
#define MEM_BANK_ISARRAYFIRST 0x02
first in a bank group, eg "ram00"
MEM_BANK_ISARRAYLAST
#define MEM_BANK_ISARRAYLAST 0x04
last in a bank group, eg "ramff"
Typedef Documentation
mem_ioreg_list_t
typedef struct mem_ioreg_list_s mem_ioreg_list_t
read_func_ptr_t
typedef read_func_t* read_func_ptr_t
read_func_t
typedef uint8_t read_func_t(uint16_t addr)
store_func_ptr_t
typedef store_func_t* store_func_ptr_t
store_func_t
typedef void store_func_t(uint16_t addr, uint8_t value)
Function Documentation
mem_bank_flags_from_bank()
int mem_bank_flags_from_bank (int bank)
Referenced by maincpu_monitor_interface_get(), and mon_get_bank_flags_for_bank().
mem_bank_from_name()
int mem_bank_from_name (const char * name)
return bank number for a given literal bank name
Referenced by maincpu_monitor_interface_get(), mon_banknum_from_bank(), mon_breakpoint_check_checkpoint(), mon_file_load(), mon_file_verify(), mon_get_bank_name_for_bank(), mon_register_print(), monitor_init(), and monitor_open().
mem_bank_index_from_bank()
int mem_bank_index_from_bank (int bank)
return current index for a given bank
Referenced by maincpu_monitor_interface_get(), and mon_get_bank_index_for_bank().
mem_bank_list()
const char ** mem_bank_list (void)
Memory access functions for the monitor.
Referenced by maincpu_monitor_interface_get(), mon_bank(), mon_display_io_regs(), mon_get_bank_name_for_bank(), and monitor_binary_process_banks_available().
mem_bank_list_nos()
const int * mem_bank_list_nos (void)
Referenced by maincpu_monitor_interface_get(), mon_banknum_validate(), and monitor_binary_process_banks_available().
mem_bank_peek()
uint8_t mem_bank_peek (int bank, uint16_t addr, void * context)
read memory without side-effects
Referenced by clipboard_read_screen_output(), maincpu_monitor_interface_get(), mem_peek_with_config(), mon_get_mem_val_ex(), mon_get_mem_val_ex_nosfx(), and mon_get_mem_val_nosfx().
mem_bank_poke()
void mem_bank_poke (int bank, uint16_t addr, uint8_t byte, void * context)
used by monitor if sfx off
Referenced by maincpu_monitor_interface_get(), mon_set_mem_val(), and mon_set_mem_val_ex().
mem_bank_read()
uint8_t mem_bank_read (int bank, uint16_t addr, void * context)
read memory with side-effects
Referenced by maincpu_monitor_interface_get(), and mem_bank_peek().
mem_bank_write()
void mem_bank_write (int bank, uint16_t addr, uint8_t byte, void * context)
Referenced by maincpu_monitor_interface_get(), and mem_bank_poke().
mem_color_ram_from_snapshot()
void mem_color_ram_from_snapshot (uint8_t * color_ram)
Referenced by vicii_snapshot_read_module().
mem_color_ram_to_snapshot()
void mem_color_ram_to_snapshot (uint8_t * color_ram)
Referenced by vicii_snapshot_write_module().
mem_get_basic_text()
void mem_get_basic_text (uint16_t * start, uint16_t * end)
Todo:
FIXME: this part needs to be checked.
Todo:
FIXME: this part needs to be checked.
Todo:
FIXME: this part needs to be checked.
Referenced by autostart_prg_perform_injection().
mem_get_current_bank_config()
int mem_get_current_bank_config (void)
Todo:
not implemented yet
Referenced by callstack_push(), initialize_context(), mon_backtrace(), mon_disassemble_instr_memconfig_internal(), and profile_sample_start().
mem_get_cursor_parameter()
void mem_get_cursor_parameter (uint16_t * screen_addr, uint8_t * cursor_column, uint8_t * line_length, int * blinking)
Referenced by check2(), and is_machine_ready().
mem_get_screen_parameter()
void mem_get_screen_parameter (uint16_t * base, uint8_t * rows, uint8_t * columns, int * bank)
Referenced by clipboard_read_screen_output(), mon_display_screen(), and mon_memory_display().
mem_initialize_memory()
void mem_initialize_memory (void)
Referenced by machine_init(), machine_reset(), and memhacks_snapshot_read_modules().
mem_inject()
void mem_inject (uint32_t addr, uint8_t value)
Referenced by autostart_prg_perform_injection(), machine_vsync_hook(), and mem_inject_key().
mem_inject_key()
void mem_inject_key (uint16_t addr, uint8_t value)
Referenced by tokbdbuffer().
mem_ioreg_list_get()
mem_ioreg_list_t * mem_ioreg_list_get (void * context)
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
Referenced by maincpu_monitor_interface_get().
mem_load()
int mem_load (void)
Referenced by machine_specific_init().
mem_mmu_translate()
void mem_mmu_translate (unsigned int addr, uint8_t ** base, int * start, int * limit)
Referenced by maincpu_resync_limits().
mem_peek_with_config()
uint8_t mem_peek_with_config (int config, uint16_t addr, void * context)
Referenced by maincpu_monitor_interface_get(), mem_bank_peek(), and mon_get_mem_val_nosfx().
mem_powerup()
void mem_powerup (void)
Initialize RAM for power-up.
Referenced by machine_powerup().
mem_read_screen()
uint8_t mem_read_screen (uint16_t addr)
Referenced by check2(), and is_machine_ready().
mem_read_snapshot_module()
int mem_read_snapshot_module (struct snapshot_s * s)
mem_rom_trap_allowed()
int mem_rom_trap_allowed (uint16_t addr)
mem_set_basic_text()
void mem_set_basic_text (uint16_t start, uint16_t end)
Referenced by autostart_prg_perform_injection(), machine_vsync_hook(), and mon_file_load().
mem_toggle_watchpoints()
void mem_toggle_watchpoints (int flag, void * context)
Referenced by maincpu_monitor_interface_get().
mem_write_snapshot_module()
int mem_write_snapshot_module (struct snapshot_s * s, int save_roms)
Variable Documentation
_mem_read_tab_ptr
read_func_ptr_t* _mem_read_tab_ptr extern
Pointers to the currently used memory read and write tables.
Referenced by mem_dma_read(), mem_initialize_memory(), mem_read(), mem_read_check_ba(), and mem_update_tab_ptrs().
_mem_read_tab_ptr_dummy
read_func_ptr_t* _mem_read_tab_ptr_dummy extern
Referenced by mem_read_check_ba_dummy(), and mem_update_tab_ptrs().
_mem_write_tab_ptr
store_func_ptr_t* _mem_write_tab_ptr extern
Referenced by mem_dma_store(), mem_initialize_memory(), mem_set_vbank(), mem_store(), and mem_update_tab_ptrs().
_mem_write_tab_ptr_dummy
store_func_ptr_t* _mem_write_tab_ptr_dummy extern
Referenced by mem_update_tab_ptrs().
mem_chargen_rom_ptr
uint8_t* mem_chargen_rom_ptr extern
Pointer to the chargen ROM.
Referenced by handle_fetch_sprite(), mem_initialize_memory(), and vicii_update_memory_ptrs().
mem_color_ram_cpu
uint8_t* mem_color_ram_cpu extern
Referenced by mem_initialize_memory().
mem_color_ram_vicii
uint8_t* mem_color_ram_vicii extern
Referenced by mem_initialize_memory(), vicii_fetch_matrix(), and vicii_screenshot().
mem_dma_read
read_func_t mem_dma_read extern
mem_dma_store
store_func_t mem_dma_store extern
mem_page_one
uint8_t* mem_page_one extern
mem_page_zero
uint8_t* mem_page_zero extern
mem_ram
uint8_t mem_ram[] extern
The C64 memory.
Referenced by _draw_8bpp_chunky_bitmap(), _draw_8bpp_fred2_bitmap_mode(), _draw_8bpp_fred_bitmap_mode(), _draw_8bpp_pixel_cell_bitmap_mode(), _draw_8bpp_two_plane_bitmap_mode(), c64_256k_deactivate(), c64_snapshot_read_module(), c64_snapshot_write_module(), mem_bank_peek(), mem_bank_read(), mem_bank_write(), mem_get_basic_text(), mem_get_cursor_parameter(), mem_initialize_memory(), mem_inject(), mem_peek_with_config(), mem_powerup(), mem_set_basic_text(), plus256k_deactivate(), plus60k_ram_read(), plus60k_ram_store(), ram_hi_store(), ram_read(), ram_store(), tape_find_header_trap(), tape_find_header_trap_plus4(), tape_receive_trap(), tape_receive_trap_plus4(), vicii_powerup(), vicii_reset(), vicii_snapshot_read_module(), vicii_snapshot_write_module(), viciidtv_update_colorram(), zero_read(), zero_read_dma(), zero_store(), and zero_store_dma().
mem_read
read_func_t mem_read extern
Referenced by kbdbuf_is_empty(), serial_get_st(), serial_set_st(), serial_trap_attention(), serial_trap_send(), set_st(), tape_find_header_trap(), tape_find_header_trap_plus4(), tape_receive_trap(), tape_receive_trap_plus4(), and tokbdbuffer().
mem_store
store_func_t mem_store extern
Referenced by serial_set_st(), serial_trap_receive(), set_st(), tape_find_header_trap(), tape_find_header_trap_plus4(), and tape_receive_trap().
rom_read
read_func_t rom_read extern
rom_store
store_func_t rom_store extern
rom_trap_read
read_func_t rom_trap_read
rom_trap_store
store_func_t rom_trap_store
zero_read
read_func_t zero_read
zero_read_dma
read_func_t zero_read_dma
zero_store
store_func_t zero_store
zero_store_dma
store_func_t zero_store_dma