x128: arch/shared/archdep_mkdir.h File Reference
archdep_mkdir.h File Reference
Create a directory - header.
Macros
#define ARCHDEP_MKDIR_RWXU 0700
#define ARCHDEP_MKDIR_RWXUG 0770
#define ARCHDEP_MKDIR_RWXUGO 0777
Functions
int archdep_mkdir (const char *pathname, int mode)
Create a directory pathname with mode.
int archdep_mkdir_recursive (const char *pathname, int mode)
Create directory while creating parents if needed.
Detailed Description
Create a directory - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
ARCHDEP_MKDIR_RWXU
#define ARCHDEP_MKDIR_RWXU 0700
ARCHDEP_MKDIR_RWXUG
#define ARCHDEP_MKDIR_RWXUG 0770
ARCHDEP_MKDIR_RWXUGO
#define ARCHDEP_MKDIR_RWXUGO 0777
Function Documentation
archdep_mkdir()
int archdep_mkdir (const char * pathname, int mode)
Create a directory pathname with mode.
Parameters
[in] pathname directory to create
[in] mode access mode of directory (ignored on some systems)
Returns
0 on success, -1 on error
Referenced by archdep_create_user_cache_dir(), archdep_create_user_config_dir(), archdep_mkdir_recursive(), autostart_prg(), fliplist_save_list(), fsdevice_flush_mkdir(), and mon_make_dir().
archdep_mkdir_recursive()
int archdep_mkdir_recursive (const char * pathname, int mode)
Create directory while creating parents if needed.
Please note: this function does not fail if pathname exists and is a directory. So I might have to change that.
Parameters
[in] pathname directory to create
[in] mode mode for pathname
Returns
0 on success, -1 on failure
< directory separator as an integer
Referenced by archdep_create_user_state_dir().