vsid: vdrive/vdrive-internal.c File Reference
vdrive-internal.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include "attach.h"
#include "cbmdos.h"
#include "cbmimage.h"
#include "diskimage.h"
#include "lib.h"
#include "log.h"
#include "machine-drive.h"
#include "types.h"
#include "vdrive-command.h"
#include "vdrive-internal.h"
#include "vdrive.h"
#include "p64.h"
Functions
vdrive_t * vdrive_internal_open_fsimage (const char *name, unsigned int read_only)
int vdrive_internal_close_disk_image (vdrive_t *vdrive)
static int vdrive_internal_format_disk_image (const char *filename, const char *disk_name)
int vdrive_internal_create_format_disk_image (const char *filename, const char *diskname, unsigned int type)
void vdrive_internal_init (void)
Variables
static log_t vdrive_internal_log = ((log_t)-2)
Function Documentation
vdrive_internal_close_disk_image()
int vdrive_internal_close_disk_image (vdrive_t * vdrive)
Referenced by diskcontents_filesystem_read(), and vdrive_internal_format_disk_image().
vdrive_internal_create_format_disk_image()
int vdrive_internal_create_format_disk_image (const char * filename, const char * diskname, unsigned int type)
< HD in ASCII for CMDHD
Referenced by autostart_prg_with_disk_image(), and create_disk_image().
vdrive_internal_format_disk_image()
static int vdrive_internal_format_disk_image (const char * filename, const char * disk_name) static
Todo:
FIXME: Pass unit here.
Referenced by vdrive_internal_create_format_disk_image().
vdrive_internal_init()
void vdrive_internal_init (void)
Referenced by vdrive_init().
vdrive_internal_open_fsimage()
vdrive_t * vdrive_internal_open_fsimage (const char * name, unsigned int read_only)
Referenced by diskcontents_filesystem_read(), and vdrive_internal_format_disk_image().
Variable Documentation
vdrive_internal_log
log_t vdrive_internal_log = ((log_t)-2) static
Referenced by vdrive_internal_init(), and vdrive_internal_open_fsimage().