vsid: interrupt.c File Reference
interrupt.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "6510core.h"
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "maincpu.h"
#include "snapshot.h"
#include "types.h"
Functions
void interrupt_cpu_status_init (interrupt_cpu_status_t *cs, unsigned int *last_opcode_info_ptr)
Initialization.
void interrupt_cpu_status_reset (interrupt_cpu_status_t *cs)
unsigned int interrupt_cpu_status_int_new (interrupt_cpu_status_t *cs, const char *name)
interrupt_cpu_status_t * interrupt_cpu_status_new (void)
void interrupt_cpu_status_destroy (interrupt_cpu_status_t *cs)
void interrupt_set_nmi_trap_func (interrupt_cpu_status_t *cs, void(*nmi_trap_func)(void))
void interrupt_set_reset_trap_func (interrupt_cpu_status_t *cs, void(*reset_trap_func)(void))
void interrupt_cpu_status_time_warp (interrupt_cpu_status_t *cs, CLOCK warp_amount, int warp_direction)
Move all the CLOCK time references forward/backward.
void interrupt_log_wrong_nirq (void)
void interrupt_log_wrong_nnmi (void)
void interrupt_restore_irq (interrupt_cpu_status_t *cs, int int_num, int value)
void interrupt_restore_nmi (interrupt_cpu_status_t *cs, int int_num, int value)
int interrupt_get_irq (interrupt_cpu_status_t *cs, int int_num)
int interrupt_get_nmi (interrupt_cpu_status_t *cs, int int_num)
void interrupt_fixup_int_clk (interrupt_cpu_status_t *cs, CLOCK cpu_clk, CLOCK *int_clk)
void interrupt_trigger_dma (interrupt_cpu_status_t *cs, CLOCK cpu_clk)
void interrupt_ack_dma (interrupt_cpu_status_t *cs)
void interrupt_trigger_reset (interrupt_cpu_status_t *cs, CLOCK cpu_clk)
Trigger a RESET.
void interrupt_ack_reset (interrupt_cpu_status_t *cs)
Acknowledge a RESET condition, by removing it.
void interrupt_maincpu_trigger_trap (void(*trap_func)(uint16_t, void *data), void *data)
Trigger a TRAP next cycle.
void interrupt_do_trap (interrupt_cpu_status_t *cs, uint16_t address)
Dispatch the TRAP condition.
void interrupt_monitor_trap_on (interrupt_cpu_status_t *cs)
void interrupt_monitor_trap_off (interrupt_cpu_status_t *cs)
int interrupt_write_snapshot (interrupt_cpu_status_t *cs, snapshot_module_t *m)
int interrupt_write_new_snapshot (interrupt_cpu_status_t *cs, snapshot_module_t *m)
int interrupt_write_sc_snapshot (interrupt_cpu_status_t *cs, snapshot_module_t *m)
int interrupt_read_snapshot (interrupt_cpu_status_t *cs, snapshot_module_t *m)
int interrupt_read_new_snapshot (interrupt_cpu_status_t *cs, snapshot_module_t *m)
int interrupt_read_sc_snapshot (interrupt_cpu_status_t *cs, snapshot_module_t *m)
Function Documentation
interrupt_ack_dma()
void interrupt_ack_dma (interrupt_cpu_status_t * cs)
interrupt_ack_reset()
void interrupt_ack_reset (interrupt_cpu_status_t * cs)
Acknowledge a RESET condition, by removing it.
interrupt_cpu_status_destroy()
void interrupt_cpu_status_destroy (interrupt_cpu_status_t * cs)
Referenced by drivecpu65c02_shutdown(), drivecpu_shutdown(), and maincpu_shutdown().
interrupt_cpu_status_init()
void interrupt_cpu_status_init (interrupt_cpu_status_t * cs, unsigned int * last_opcode_info_ptr)
Initialization.
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), and maincpu_init().
interrupt_cpu_status_int_new()
unsigned int interrupt_cpu_status_int_new (interrupt_cpu_status_t * cs, const char * name)
Referenced by c64keyboard_init(), ciacore_init(), myacia_init(), mypia_init(), viacore_init(), and vicii_irq_init().
interrupt_cpu_status_new()
interrupt_cpu_status_t * interrupt_cpu_status_new (void)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), and maincpu_early_init().
interrupt_cpu_status_reset()
void interrupt_cpu_status_reset (interrupt_cpu_status_t * cs)
Referenced by cpu_reset(), drivecpu65c02_reset(), drivecpu65c02_snapshot_read_module(), drivecpu_reset(), and drivecpu_snapshot_read_module().
interrupt_cpu_status_time_warp()
void interrupt_cpu_status_time_warp (interrupt_cpu_status_t * cs, CLOCK warp_amount, int warp_direction)
Move all the CLOCK time references forward/backward.
interrupt_do_trap()
void interrupt_do_trap (interrupt_cpu_status_t * cs, uint16_t address)
Dispatch the TRAP condition.
interrupt_fixup_int_clk()
void interrupt_fixup_int_clk (interrupt_cpu_status_t * cs, CLOCK cpu_clk, CLOCK * int_clk)
Referenced by interrupt_set_irq(), and interrupt_set_nmi().
interrupt_get_irq()
int interrupt_get_irq (interrupt_cpu_status_t * cs, int int_num)
interrupt_get_nmi()
int interrupt_get_nmi (interrupt_cpu_status_t * cs, int int_num)
interrupt_log_wrong_nirq()
void interrupt_log_wrong_nirq (void)
Referenced by interrupt_set_irq().
interrupt_log_wrong_nnmi()
void interrupt_log_wrong_nnmi (void)
Referenced by interrupt_set_nmi().
interrupt_maincpu_trigger_trap()
void interrupt_maincpu_trigger_trap (void(*)(uint16_t, void *data) trap_func, void * data)
Trigger a TRAP next cycle.
Referenced by advance_hassnapshot(), event_playback_start(), event_record_reset_milestone(), event_record_set_milestone(), event_record_start(), event_record_stop(), monitor_startup_trap(), network_connect_client(), network_hook(), network_init_frame_event_list(), network_prepare_next_frame(), ui_snapshot_load_snapshot(), ui_snapshot_quickload_snapshot(), ui_snapshot_quicksave_snapshot(), and ui_snapshot_save_snapshot().
interrupt_monitor_trap_off()
void interrupt_monitor_trap_off (interrupt_cpu_status_t * cs)
Referenced by monitor_check_icount(), and update_checkpoint_state().
interrupt_monitor_trap_on()
void interrupt_monitor_trap_on (interrupt_cpu_status_t * cs)
Referenced by cpu_reset(), drivecpu65c02_reset(), drivecpu_reset(), mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), and update_checkpoint_state().
interrupt_read_new_snapshot()
int interrupt_read_new_snapshot (interrupt_cpu_status_t * cs, snapshot_module_t * m)
Referenced by drivecpu65c02_snapshot_read_module(), drivecpu_snapshot_read_module(), and maincpu_snapshot_read_module().
interrupt_read_sc_snapshot()
int interrupt_read_sc_snapshot (interrupt_cpu_status_t * cs, snapshot_module_t * m)
Referenced by maincpu_snapshot_read_module().
interrupt_read_snapshot()
int interrupt_read_snapshot (interrupt_cpu_status_t * cs, snapshot_module_t * m)
Referenced by drivecpu65c02_snapshot_read_module(), drivecpu_snapshot_read_module(), and maincpu_snapshot_read_module().
interrupt_restore_irq()
void interrupt_restore_irq (interrupt_cpu_status_t * cs, int int_num, int value)
Referenced by cia_restore_int(), restore_int(), and vicii_snapshot_read_module().
interrupt_restore_nmi()
void interrupt_restore_nmi (interrupt_cpu_status_t * cs, int int_num, int value)
Referenced by cia_restore_int().
interrupt_set_nmi_trap_func()
void interrupt_set_nmi_trap_func (interrupt_cpu_status_t * cs, void(*)(void) nmi_trap_func)
interrupt_set_reset_trap_func()
void interrupt_set_reset_trap_func (interrupt_cpu_status_t * cs, void(*)(void) reset_trap_func)
interrupt_trigger_dma()
void interrupt_trigger_dma (interrupt_cpu_status_t * cs, CLOCK cpu_clk)
interrupt_trigger_reset()
void interrupt_trigger_reset (interrupt_cpu_status_t * cs, CLOCK cpu_clk)
Trigger a RESET.
This resets the machine.
Referenced by drivecpu65c02_reset(), drivecpu65c02_trigger_reset(), drivecpu_reset(), and drivecpu_trigger_reset().
interrupt_write_new_snapshot()
int interrupt_write_new_snapshot (interrupt_cpu_status_t * cs, snapshot_module_t * m)
Referenced by drivecpu65c02_snapshot_write_module(), drivecpu_snapshot_write_module(), and maincpu_snapshot_write_module().
interrupt_write_sc_snapshot()
int interrupt_write_sc_snapshot (interrupt_cpu_status_t * cs, snapshot_module_t * m)
Referenced by maincpu_snapshot_write_module().
interrupt_write_snapshot()
int interrupt_write_snapshot (interrupt_cpu_status_t * cs, snapshot_module_t * m)
Todo:
FIXME: could we avoid some of this info?
Referenced by drivecpu65c02_snapshot_write_module(), drivecpu_snapshot_write_module(), and maincpu_snapshot_write_module().