vsid: arch/gtk3/widgets/printerdriverwidget.c File Reference
printerdriverwidget.c File Reference
Widget to control printer drivers.
#include "vice.h"
#include <gtk/gtk.h>
#include "driver-select.h"
#include "log.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "printerdriverwidget.h"
Functions
static void on_radio_toggled (GtkWidget *radio, gpointer user_data)
Handler for the "toggled" event of the radio buttons.
GtkWidget * printer_driver_widget_create (int device, void(*callback)(GtkWidget *radio, int device, const char *drv_name))
Create printer driver selection widget.
void printer_driver_widget_update (GtkWidget *widget, const char *driver)
Update the printer driver widget.
Variables
static const char * driver_resource_names [4]
Resources names per device.
static void(* extra_radio_callback)(GtkWidget *, int, const char *) = NULL
Function to call when a driver radio button is selected.
Detailed Description
Widget to control printer drivers.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Allows selecting drivers for printers #4, #5, #6 and userport printer.
Function Documentation
on_radio_toggled()
static void on_radio_toggled (GtkWidget * radio, gpointer user_data) static
Handler for the "toggled" event of the radio buttons.
Parameters
[in] radio radio button
[in] user_data new value for the resource (const char *)
Referenced by printer_driver_widget_create().
printer_driver_widget_create()
GtkWidget * printer_driver_widget_create (int device, void(*)(GtkWidget *radio, int device, const char *drv_name) callback)
Create printer driver selection widget.
Creates a group of radio buttons to select the driver of printer # device.
Uses a custom property "Driver" for the radio buttons and stores the resource name for device as the "ResourceName" property.
The following device lists are obtained dynamically: Printer 4/5 : [ascii, mps 801/802/803, cbm 2022/4023/8023, nl10, raw] Printer 6 : [1520, raw] Userport (3) : [ascii, nl10, raw]
Parameters
[in] device device number (4-6) or 3 for userport
[in] callback function to call on radio button selection (optional)
Returns
GtkGrid
Referenced by create_printer_widget().
printer_driver_widget_update()
void printer_driver_widget_update (GtkWidget * widget, const char * driver)
Update the printer driver widget.
Parameters
[in,out] widget printer driver widget
[in] driver driver name
Variable Documentation
driver_resource_names
const char* driver_resource_names[4] static
Initial value:
= {
    "PrinterUserportDriver",
    "Printer4Driver",
    "Printer5Driver",
    "Printer6Driver"
}
Resources names per device.
Note
Index 0 is device 3/userport, index 1-2 are printer 4 and 5 and index 3 is plotter 6.
Referenced by printer_driver_widget_create().
extra_radio_callback
void(* extra_radio_callback) (GtkWidget *, int, const char *) (GtkWidget * , int , const char *) = NULL static
Function to call when a driver radio button is selected.
Referenced by on_radio_toggled(), and printer_driver_widget_create().