vsid: screenshot.h File Reference
screenshot.h File Reference
#include "vice.h"
#include <stdio.h>
#include "types.h"
#include "viewport.h"
Data Structures
struct screenshot_s
Macros
#define SCREENSHOT_DEFAULT_QUICKSCREENSHOT_FORMAT "BMP"
#define SCREENSHOT_MODE_PALETTE 0
#define SCREENSHOT_MODE_RGB32 1
#define SCREENSHOT_MODE_RGB24 2
Typedefs
typedef struct screenshot_s screenshot_t
Functions
int screenshot_init (void)
Functions called by external emulator code.
void screenshot_shutdown (void)
Clean up memory resources used by the module.
int screenshot_save (const char *drvname, const char *filename, struct video_canvas_s *canvas)
int screenshot_record (void)
void screenshot_stop_recording (void)
int screenshot_is_recording (void)
void screenshot_prepare_reopen (void)
void screenshot_try_reopen (void)
const char * screenshot_get_fext_for_format (const char *format)
const char * screenshot_get_quickscreenshot_format (void)
char * screenshot_create_datetime_string (void)
char * screenshot_create_quickscreenshot_filename (const char *format)
int screenshot_resources_init (void)
void screenshot_ui_auto_screenshot (void)
Create screenshot with autogenerated filename.
Macro Definition Documentation
SCREENSHOT_DEFAULT_QUICKSCREENSHOT_FORMAT
#define SCREENSHOT_DEFAULT_QUICKSCREENSHOT_FORMAT "BMP"
SCREENSHOT_MODE_PALETTE
#define SCREENSHOT_MODE_PALETTE 0
SCREENSHOT_MODE_RGB24
#define SCREENSHOT_MODE_RGB24 2
SCREENSHOT_MODE_RGB32
#define SCREENSHOT_MODE_RGB32 1
Typedef Documentation
screenshot_t
typedef struct screenshot_s screenshot_t
Function Documentation
screenshot_create_datetime_string()
char * screenshot_create_datetime_string (void)
Referenced by create_proposed_audio_recording_name(), create_proposed_video_recording_name(), and screenshot_create_quickscreenshot_filename().
screenshot_create_quickscreenshot_filename()
char * screenshot_create_quickscreenshot_filename (const char * format)
Referenced by save_screenshot_handler(), and screenshot_auto_screenshot_vsync_callback().
screenshot_get_fext_for_format()
const char * screenshot_get_fext_for_format (const char * format)
Referenced by screenshot_create_quickscreenshot_filename(), and set_autosave_screenshot_format().
screenshot_get_quickscreenshot_format()
const char * screenshot_get_quickscreenshot_format (void)
Referenced by screenshot_auto_screenshot_vsync_callback().
screenshot_init()
int screenshot_init (void)
Functions called by external emulator code.
Functions called by external emulator code.
Returns
0 on success (always)
Referenced by init_main().
screenshot_is_recording()
int screenshot_is_recording (void)
Referenced by screenshot_prepare_reopen(), set_video_halve_framerate(), statusbar_recording_widget_set_recording_status(), statusbar_recording_widget_set_time(), and ui_media_stop_recording().
screenshot_prepare_reopen()
void screenshot_prepare_reopen (void)
Referenced by sid_snapshot_read_module_simple().
screenshot_record()
int screenshot_record (void)
Referenced by machine_vsync_hook().
screenshot_resources_init()
int screenshot_resources_init (void)
Referenced by init_resources().
screenshot_save()
int screenshot_save (const char * drvname, const char * filename, struct video_canvas_s * canvas)
Referenced by mon_screenshot_save(), on_save_video_filename(), save_screenshot_vsync_callback(), screenshot_at_exit(), screenshot_auto_screenshot_vsync_callback(), and screenshot_try_reopen().
screenshot_shutdown()
void screenshot_shutdown (void)
Clean up memory resources used by the module.
Referenced by machine_shutdown().
screenshot_stop_recording()
void screenshot_stop_recording (void)
Referenced by ffmpegexe_soundmovie_close(), ffmpegexedrv_init_file(), ui_media_stop_recording(), zmbv_soundmovie_close(), and zmbvdrv_init_file().
screenshot_try_reopen()
void screenshot_try_reopen (void)
Referenced by sid_snapshot_read_module_simple().
screenshot_ui_auto_screenshot()
void screenshot_ui_auto_screenshot (void)
Create screenshot with autogenerated filename.
Creates a screenshot with an autogenerated filename with an ISO-8601-ish timestamp. See screenshot.c screenshot_get_quickscreenshot_filename().
Referenced by screenshot_quicksave_action().