x128: drive/ieee/memieee.c File Reference
memieee.c File Reference
#include "vice.h"
#include "drive-check.h"
#include "drivemem.h"
#include "driverom.h"
#include "drivetypes.h"
#include "memieee.h"
#include "riotd.h"
#include "types.h"
#include "via1d2031.h"
#include "viad.h"
Functions
static uint8_t drive_read_rom (diskunit_context_t *drv, uint16_t address)
static uint8_t drive_read_2031ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_2031ram (diskunit_context_t *drv, uint16_t address, uint8_t value)
static uint8_t drive_read_zero (diskunit_context_t *drv, uint16_t address)
static void drive_store_zero (diskunit_context_t *drv, uint16_t address, uint8_t value)
static uint8_t drive_read_1001_io (diskunit_context_t *drv, uint16_t address)
SFD1001 specific memory.
static void drive_store_1001_io (diskunit_context_t *drv, uint16_t address, uint8_t byte)
static uint8_t drive_peek_1001_io (diskunit_context_t *drv, uint16_t address)
static uint8_t drive_read_1001zero_ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_1001zero_ram (diskunit_context_t *drv, uint16_t address, uint8_t byte)
static uint8_t drive_read_1001buffer1_ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_1001buffer1_ram (diskunit_context_t *drv, uint16_t address, uint8_t byte)
static uint8_t drive_read_1001buffer2_ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_1001buffer2_ram (diskunit_context_t *drv, uint16_t address, uint8_t byte)
static uint8_t drive_read_1001buffer3_ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_1001buffer3_ram (diskunit_context_t *drv, uint16_t address, uint8_t byte)
static uint8_t drive_read_1001buffer4_ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_1001buffer4_ram (diskunit_context_t *drv, uint16_t address, uint8_t byte)
static uint8_t drive_read_2040buffer1_ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_2040buffer1_ram (diskunit_context_t *drv, uint16_t address, uint8_t byte)
static uint8_t drive_read_2040buffer2_ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_2040buffer2_ram (diskunit_context_t *drv, uint16_t address, uint8_t byte)
static uint8_t drive_read_2040buffer3_ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_2040buffer3_ram (diskunit_context_t *drv, uint16_t address, uint8_t byte)
static uint8_t drive_read_2040buffer4_ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_2040buffer4_ram (diskunit_context_t *drv, uint16_t address, uint8_t byte)
void memieee_init (struct diskunit_context_s *drv, unsigned int type)
Function Documentation
drive_peek_1001_io()
static uint8_t drive_peek_1001_io (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_1001_io()
static uint8_t drive_read_1001_io (diskunit_context_t * drv, uint16_t address) static
SFD1001 specific memory.
Referenced by memieee_init().
drive_read_1001buffer1_ram()
static uint8_t drive_read_1001buffer1_ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_1001buffer2_ram()
static uint8_t drive_read_1001buffer2_ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_1001buffer3_ram()
static uint8_t drive_read_1001buffer3_ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_1001buffer4_ram()
static uint8_t drive_read_1001buffer4_ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_1001zero_ram()
static uint8_t drive_read_1001zero_ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_2031ram()
static uint8_t drive_read_2031ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_2040buffer1_ram()
static uint8_t drive_read_2040buffer1_ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_2040buffer2_ram()
static uint8_t drive_read_2040buffer2_ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_2040buffer3_ram()
static uint8_t drive_read_2040buffer3_ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_2040buffer4_ram()
static uint8_t drive_read_2040buffer4_ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_rom()
static uint8_t drive_read_rom (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_read_zero()
static uint8_t drive_read_zero (diskunit_context_t * drv, uint16_t address) static
Referenced by memieee_init().
drive_store_1001_io()
static void drive_store_1001_io (diskunit_context_t * drv, uint16_t address, uint8_t byte) static
Referenced by memieee_init().
drive_store_1001buffer1_ram()
static void drive_store_1001buffer1_ram (diskunit_context_t * drv, uint16_t address, uint8_t byte) static
Referenced by memieee_init().
drive_store_1001buffer2_ram()
static void drive_store_1001buffer2_ram (diskunit_context_t * drv, uint16_t address, uint8_t byte) static
Referenced by memieee_init().
drive_store_1001buffer3_ram()
static void drive_store_1001buffer3_ram (diskunit_context_t * drv, uint16_t address, uint8_t byte) static
Referenced by memieee_init().
drive_store_1001buffer4_ram()
static void drive_store_1001buffer4_ram (diskunit_context_t * drv, uint16_t address, uint8_t byte) static
Referenced by memieee_init().
drive_store_1001zero_ram()
static void drive_store_1001zero_ram (diskunit_context_t * drv, uint16_t address, uint8_t byte) static
Referenced by memieee_init().
drive_store_2031ram()
static void drive_store_2031ram (diskunit_context_t * drv, uint16_t address, uint8_t value) static
Referenced by memieee_init().
drive_store_2040buffer1_ram()
static void drive_store_2040buffer1_ram (diskunit_context_t * drv, uint16_t address, uint8_t byte) static
Referenced by memieee_init().
drive_store_2040buffer2_ram()
static void drive_store_2040buffer2_ram (diskunit_context_t * drv, uint16_t address, uint8_t byte) static
Referenced by memieee_init().
drive_store_2040buffer3_ram()
static void drive_store_2040buffer3_ram (diskunit_context_t * drv, uint16_t address, uint8_t byte) static
Referenced by memieee_init().
drive_store_2040buffer4_ram()
static void drive_store_2040buffer4_ram (diskunit_context_t * drv, uint16_t address, uint8_t byte) static
Referenced by memieee_init().
drive_store_zero()
static void drive_store_zero (diskunit_context_t * drv, uint16_t address, uint8_t value) static
Referenced by memieee_init().
memieee_init()
void memieee_init (struct diskunit_context_s * drv, unsigned int type)
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
Referenced by ieee_drive_mem_init().