vsid: arch/gtk3/kbd.c File Reference
kbd.c File Reference
Native GTK3 UI keyboard stuff.
#include "vice.h"
#include <stdio.h>
#include <gtk/gtk.h>
#include <string.h>
#include "debug_gtk3.h"
#include "hotkeys.h"
#include "lib.h"
#include "log.h"
#include "ui.h"
#include "kbddebugwidget.h"
#include "keyboard.h"
#include "mainlock.h"
#include "uiactions.h"
#include "uimenu.h"
#include "uimedia.h"
#include "uistatusbar.h"
#include "kbd.h"
Macros
#define KEYS_PRESSED_MAX 200
Maximum size of pressed key buffers.
Enumerations
enum {
KV_FIXED ,
KV_ALIAS ,
KV_BIT8 ,
KV_ARR_SIZE
}
Enable debug_gtk3() calls for the Gdk scancode/keypad fixes.
Functions
void kbd_arch_init (void)
Initialize keyboard handling.
void kbd_arch_shutdown (void)
Shutdown keyboard handling (NOP)
signed long kbd_arch_keyname_to_keynum (char *keyname)
Get keynum from keyname.
const char * kbd_arch_keynum_to_keyname (signed long keynum)
Get keyname from keynum.
void kbd_initialize_numpad_joykeys (int *joykeys)
Initialize numpad joystick key mapping.
static void kbd_fix_shift_press (GdkEvent *report)
Set shift flags on key press.
static void kbd_fix_shift_release (GdkEvent *report)
Unset shift flags on key release.
static void kbd_fix_shift_clear (void)
Clear shift flags.
static void kbd_sync_caps_lock (void)
sync caps lock status with the keyboard emulation
static int kbd_get_modifier (GdkEvent *report)
Get modifiers keys for keyboard event.
static int findpressedkey (GdkEvent *report)
Look up key buffer index for report by hardware scancode.
static int addpressedkey (GdkEvent *report, int *key, int *mod)
Add pressed key.
static int removepressedkey (GdkEvent *report, int *key, int *mod)
Remove pressed key.
static gboolean isresethotkey (GdkEvent *report)
Check if a key event report refers to a "reset" action.
static guint fix_numpad_aliases (GdkEvent *event)
Fix numpad aliases.
static gboolean kbd_event_handler (GtkWidget *w, GdkEvent *report, gpointer gp)
Gtk keyboard event handler.
void kbd_connect_handlers (GtkWidget *widget, void *data)
Connect keyboard event handlers to the current window.
Variables
static int shiftl_state = 0
Left SHIFT key state.
static int shiftr_state = 0
Right SHIFT key state.
static int capslock_state = 0
CAPSLOCK key state (is the key currently pressed?)
static int capslock_lock_state = 0
CAPSLOCK key state (is caps-lock active/locked?)
static int keyspressed = 0
Current number of pressed key buffers elements.
static int pressedkeys [200]
GDK key codes.
static int pressedkeysmod [200]
GDK key modifiers.
static int pressedkeyshw [200]
Key hardware scancodes.
static int pressedkeysstate [200]
GDK key states.
static const guint numpad_aliases [][2]
Table of numpad aliases.
Detailed Description
Native GTK3 UI keyboard stuff.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
Oliver Schaertel
pottendo potte.nosp@m.ndo@.nosp@m.gmx.n.nosp@m.et
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
KEYS_PRESSED_MAX
#define KEYS_PRESSED_MAX 200
Maximum size of pressed key buffers.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enable debug_gtk3() calls for the Gdk scancode/keypad fixes.
Gdk keyval translation table array indexes
Enumerator
KV_FIXED
target keysym (Unix)
KV_ALIAS
Windows/MacOS keysym alias.
KV_BIT8
bit 8 of the scancode
KV_ARR_SIZE
size of the array for a single translation entry
Function Documentation
addpressedkey()
static int addpressedkey (GdkEvent * report, int * key, int * mod) static
Add pressed key.
Parameters
[in] report GDK key-press event
[in] key GDK key value
[out] mod GDK key modifiers
Returns
boolean (1 if added)
Referenced by kbd_event_handler().
findpressedkey()
static int findpressedkey (GdkEvent * report) static
Look up key buffer index for report by hardware scancode.
Parameters
[in] report GDK key-press event
Returns
index or -1 when not found
Referenced by addpressedkey(), and removepressedkey().
fix_numpad_aliases()
static guint fix_numpad_aliases (GdkEvent * event) static
Fix numpad aliases.
Depending on the Keyboard Layout/Localisation some numpad keys produce a different keyval - we fix it here so the joystick mappings can always use the same values
Parameters
[in] event key press/release event
Returns
fixed keyval for numpad keys
Referenced by kbd_event_handler().
isresethotkey()
static gboolean isresethotkey (GdkEvent * report) static
Check if a key event report refers to a "reset" action.
Parameters
[in] report event object
Returns
TRUE if reported key combo is mapped to a "reset" action
Referenced by kbd_event_handler().
kbd_arch_init()
void kbd_arch_init (void)
Initialize keyboard handling.
Referenced by keyboard_init().
kbd_arch_keyname_to_keynum()
signed long kbd_arch_keyname_to_keynum (char * keyname)
Get keynum from keyname.
add more function prototypes as needed below
Parameters
[in] keyname key name as a string
Returns
keynum or -1 on error
Note
You don't see "signed $type-not-plain-char" too often :)
Referenced by keyboard_keyword_undef(), and keyboard_parse_entry().
kbd_arch_keynum_to_keyname()
const char * kbd_arch_keynum_to_keyname (signed long keynum)
Get keyname from keynum.
Parameters
[in] keynum key number
Returns
key value for keynum
Referenced by keyboard_keymap_dump().
kbd_arch_shutdown()
void kbd_arch_shutdown (void)
Shutdown keyboard handling (NOP)
kbd_connect_handlers()
void kbd_connect_handlers (GtkWidget * widget, void * data)
Connect keyboard event handlers to the current window.
Parameters
[in] widget GtkWindow instance
[in] data extra event data
Referenced by ui_create_main_window().
kbd_event_handler()
static gboolean kbd_event_handler (GtkWidget * w, GdkEvent * report, gpointer gp) static
Gtk keyboard event handler.
Parameters
[in] w widget triggering the event
[in] report event object
[in] gp extra data (unused)
Returns
TRUE if event handled (won't get passed to the emulated machine)
Todo:
FIXME: This still gets the unmodified keyval, but we cannot modify report since that's owned by Gdk.
Referenced by kbd_connect_handlers().
kbd_fix_shift_clear()
static void kbd_fix_shift_clear (void) static
Clear shift flags.
Referenced by kbd_event_handler().
kbd_fix_shift_press()
static void kbd_fix_shift_press (GdkEvent * report) static
Set shift flags on key press.
Parameters
[in] report GDK keypress event
Referenced by kbd_event_handler().
kbd_fix_shift_release()
static void kbd_fix_shift_release (GdkEvent * report) static
Unset shift flags on key release.
Parameters
[in] report GDK keypress event
Referenced by kbd_event_handler().
kbd_get_modifier()
static int kbd_get_modifier (GdkEvent * report) static
Get modifiers keys for keyboard event.
Parameters
[in] report GDK keypress event
Returns
bitmasks of modifiers combined into a single int
Referenced by addpressedkey().
kbd_initialize_numpad_joykeys()
void kbd_initialize_numpad_joykeys (int * joykeys)
Initialize numpad joystick key mapping.
Parameters
[out] joykeys pointer to joykey array
kbd_sync_caps_lock()
static void kbd_sync_caps_lock (void) static
sync caps lock status with the keyboard emulation
Referenced by kbd_event_handler().
removepressedkey()
static int removepressedkey (GdkEvent * report, int * key, int * mod) static
Remove pressed key.
Parameters
[in] report GDK key-press event
[out] key GDK key value
[out] mod GDK key modifiers
Returns
boolean (1 if removed)
Referenced by kbd_event_handler().
Variable Documentation
capslock_lock_state
int capslock_lock_state = 0 static
CAPSLOCK key state (is caps-lock active/locked?)
Referenced by kbd_fix_shift_press(), kbd_fix_shift_release(), and kbd_sync_caps_lock().
capslock_state
int capslock_state = 0 static
CAPSLOCK key state (is the key currently pressed?)
Referenced by kbd_event_handler(), kbd_fix_shift_clear(), kbd_fix_shift_press(), kbd_fix_shift_release(), and kbd_get_modifier().
keyspressed
int keyspressed = 0 static
Current number of pressed key buffers elements.
Referenced by addpressedkey(), findpressedkey(), kbd_event_handler(), and removepressedkey().
numpad_aliases
const guint numpad_aliases[][2] static
Initial value:
= {
    { GDK_KEY_KP_Decimal,   GDK_KEY_KP_Separator },
    { GDK_KEY_KP_Page_Up,   GDK_KEY_KP_Prior     },
    { GDK_KEY_KP_Page_Down, GDK_KEY_KP_Next      },
    { GDK_KEY_KP_Begin,     GDK_KEY_Clear        },
    { GDK_KEY_Page_Up,      GDK_KEY_Prior        },
    { GDK_KEY_Page_Down,    GDK_KEY_Next         },
    { 0,                    0,                   }
}
Table of numpad aliases.
Depending on the Keyboard layout some keys produce different keycodes, which we try to combat here. Eg on a german keyboard there is a comma on the "delete" key instead of the decimal point.
The first entry is the (correct) keyval, the second the (incorrect) alias.
CAUTION: when a key exist on KP and as a regular key (example: HOME), you MUST make sure to only map KP to KP and non KP to non KP symbols here.
The list is terminated with 0 in the first (Linux) entry.
Referenced by fix_numpad_aliases().
pressedkeys
int pressedkeys[200] static
GDK key codes.
Referenced by addpressedkey(), and removepressedkey().
pressedkeyshw
int pressedkeyshw[200] static
Key hardware scancodes.
Referenced by addpressedkey(), findpressedkey(), and removepressedkey().
pressedkeysmod
int pressedkeysmod[200] static
GDK key modifiers.
Referenced by addpressedkey(), and removepressedkey().
pressedkeysstate
int pressedkeysstate[200] static
GDK key states.
Referenced by addpressedkey(), and removepressedkey().
shiftl_state
int shiftl_state = 0 static
Left SHIFT key state.
Referenced by kbd_event_handler(), kbd_fix_shift_clear(), kbd_fix_shift_press(), kbd_fix_shift_release(), and kbd_get_modifier().
shiftr_state
int shiftr_state = 0 static
Right SHIFT key state.
Referenced by kbd_event_handler(), kbd_fix_shift_clear(), kbd_fix_shift_press(), kbd_fix_shift_release(), and kbd_get_modifier().