vsid: printerdrv/output-select.c File Reference
output-select.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "output-select.h"
#include "resources.h"
#include "types.h"
#include "util.h"
Data Structures
struct output_select_list_s
Macros
#define DBG(x)
Typedefs
typedef struct output_select_list_s output_select_list_t
Functions
static int set_output_device (const char *name, void *param)
int output_select_init_resources (void)
int output_select_userport_init_resources (void)
static void build_printer_output_names (void)
int output_select_init_cmdline_options (void)
int output_select_userport_init_cmdline_options (void)
void output_select_shutdown (void)
void output_select_register (output_select_t *outp_select)
int output_select_open (unsigned int prnr, struct output_parameter_s *output_parameter)
void output_select_close (unsigned int prnr)
int output_select_putc (unsigned int prnr, uint8_t b)
int output_select_getc (unsigned int prnr, uint8_t *b)
int output_select_flush (unsigned int prnr)
int output_select_formfeed (unsigned int prnr)
Variables
static output_select_t output_select [4]
Currently used output device.
static output_select_list_t * output_select_list = NULL
Pointer to registered printer driver.
static const resource_string_t resources_string []
static const resource_string_t resources_string_userport []
static cmdline_option_t cmdline_options []
static cmdline_option_t cmdline_options_userport []
static char * printer4_output_names = NULL
static char * printer5_output_names = NULL
static char * printer6_output_names = NULL
static char * printeruserport_output_names = NULL
Macro Definition Documentation
DBG
#define DBG (x)
Typedef Documentation
output_select_list_t
typedef struct output_select_list_s output_select_list_t
Function Documentation
build_printer_output_names()
static void build_printer_output_names (void) static
Referenced by output_select_init_cmdline_options(), and output_select_userport_init_cmdline_options().
output_select_close()
void output_select_close (unsigned int prnr)
Referenced by drv_1520_close(), drv_2022_select(), drv_4023_select(), drv_8023_select(), drv_ascii_close(), drv_mps801_select(), drv_mps802_select(), drv_mps803_close(), drv_mps803_select(), drv_nl10_shutdown(), and drv_raw_close().
output_select_flush()
int output_select_flush (unsigned int prnr)
Referenced by drv_1520_flush(), drv_ascii_flush(), drv_mps803_flush(), and drv_raw_flush().
output_select_formfeed()
int output_select_formfeed (unsigned int prnr)
Referenced by drv_1520_formfeed(), drv_ascii_formfeed(), drv_mps803_formfeed(), and drv_raw_formfeed().
output_select_getc()
int output_select_getc (unsigned int prnr, uint8_t * b)
Referenced by drv_1520_getc(), drv_ascii_getc(), drv_mps803_getc(), and drv_raw_getc().
output_select_init_cmdline_options()
int output_select_init_cmdline_options (void)
Referenced by printer_cmdline_options_init().
output_select_init_resources()
int output_select_init_resources (void)
Referenced by printer_resources_init().
output_select_open()
int output_select_open (unsigned int prnr, struct output_parameter_s * output_parameter)
Referenced by drv_1520_open(), drv_2022_open(), drv_4023_open(), drv_8023_open(), drv_ascii_open(), drv_mps801_open(), drv_mps802_open(), drv_mps803_open(), drv_nl10_open(), and drv_raw_open().
output_select_putc()
int output_select_putc (unsigned int prnr, uint8_t b)
Referenced by drv_raw_putc(), formfeed(), linefeed(), output_buf(), print_char(), print_lineend(), write_line(), and write_lines().
output_select_register()
void output_select_register (output_select_t * outp_select)
Referenced by output_graphics_init_resources(), and output_text_init_resources().
output_select_shutdown()
void output_select_shutdown (void)
Referenced by printer_shutdown().
output_select_userport_init_cmdline_options()
int output_select_userport_init_cmdline_options (void)
Referenced by printer_userport_cmdline_options_init().
output_select_userport_init_resources()
int output_select_userport_init_resources (void)
Referenced by printer_userport_resources_init().
set_output_device()
static int set_output_device (const char * name, void * param) static
Variable Documentation
cmdline_options
cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-pr4output", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer4Output", NULL,
      "<Name>", NULL },
    { "-pr5output", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer5Output", NULL,
      "<Name>", NULL },
    { "-pr6output", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer6Output", NULL,
      "<Name>", NULL },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by output_select_init_cmdline_options().
cmdline_options_userport
cmdline_option_t cmdline_options_userport[] static
Initial value:
=
{
    { "-pruseroutput", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "PrinterUserportOutput", NULL,
      "<Name>", NULL },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by output_select_userport_init_cmdline_options().
output_select
output_select_t output_select[4] static
Currently used output device.
Referenced by output_graphics_init_resources(), output_select_close(), output_select_flush(), output_select_formfeed(), output_select_getc(), output_select_open(), output_select_putc(), output_text_init_resources(), and set_output_device().
output_select_list
output_select_list_t* output_select_list = NULL static
Pointer to registered printer driver.
Referenced by build_printer_output_names(), output_select_register(), output_select_shutdown(), and set_output_device().
printer4_output_names
char* printer4_output_names = NULL static
Referenced by build_printer_output_names(), output_select_init_cmdline_options(), and output_select_shutdown().
printer5_output_names
char* printer5_output_names = NULL static
Referenced by build_printer_output_names(), output_select_init_cmdline_options(), and output_select_shutdown().
printer6_output_names
char* printer6_output_names = NULL static
Referenced by build_printer_output_names(), output_select_init_cmdline_options(), and output_select_shutdown().
printeruserport_output_names
char* printeruserport_output_names = NULL static
Referenced by build_printer_output_names(), output_select_shutdown(), and output_select_userport_init_cmdline_options().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "Printer4Output", "graphics", RES_EVENT_NO, NULL,
      (char **)&output_select[0].output_name, set_output_device, (void *)0 },
    { "Printer5Output", "text", RES_EVENT_NO, NULL,
      (char **)&output_select[1].output_name, set_output_device, (void *)1 },
    { "Printer6Output", "graphics", RES_EVENT_NO, NULL,
      (char **)&output_select[2].output_name, set_output_device, (void *)2 },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by output_select_init_resources().
resources_string_userport
const resource_string_t resources_string_userport[] static
Initial value:
= {
    { "PrinterUserportOutput", "text", RES_EVENT_NO, NULL,
      (char **)&output_select[3].output_name, set_output_device, (void *)3 },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by output_select_userport_init_resources().