vsid: vdrive/vdrive-bam.c File Reference
vdrive-bam.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "attach.h"
#include "cbmdos.h"
#include "diskconstants.h"
#include "diskimage.h"
#include "lib.h"
#include "log.h"
#include "types.h"
#include "vdrive-bam.h"
#include "vdrive-command.h"
#include "vdrive.h"
Functions
static int vdrive_bam_read_bam_block (vdrive_t *vdrive, unsigned int block)
static int vdrive_calculate_disk_half (vdrive_t *vdrive)
static int vdrive_bam_get_interleave (vdrive_t *vdrive)
lookup interleave value for supported drive types
static int vdrive_bam_alloc_worker (vdrive_t *vdrive, unsigned int track, unsigned int *sector)
int vdrive_bam_alloc_first_free_sector (vdrive_t *vdrive, unsigned int *track, unsigned int *sector)
static int vdrive_bam_alloc_add_interleave (vdrive_t *vdrive, unsigned int track, unsigned int sector, unsigned int interleave)
add interleave to current sector and adjust for overflow
static int vdrive_bam_alloc_down (vdrive_t *vdrive, unsigned int *track, unsigned int *sector, unsigned int interleave)
static int vdrive_bam_alloc_up (vdrive_t *vdrive, unsigned int *track, unsigned int *sector, unsigned int interleave)
static int vdrive_bam_alloc_next_free_sector_reset (vdrive_t *vdrive, unsigned int track, unsigned int sector, unsigned int interleave)
resets the "sector" to zero, but keeps the "head" value; for D9090/60
int vdrive_bam_alloc_next_free_sector_interleave (vdrive_t *vdrive, unsigned int *track, unsigned int *sector, unsigned int interleave)
int vdrive_bam_alloc_next_free_sector (vdrive_t *vdrive, unsigned int *track, unsigned int *sector)
similar to above, but the default interleave is used.
static void vdrive_bam_set (vdrive_t *vdrive, uint8_t *bamp, unsigned int sector)
bamp should point to "sectors available", not the bam bits for the track
static void vdrive_bam_clr (vdrive_t *vdrive, uint8_t *bamp, unsigned int sector)
bamp should point to "sectors available", not the bam bits for the track
static int vdrive_bam_isset (vdrive_t *vdrive, uint8_t *bamp, unsigned int sector)
bamp should point to "sectors available", not the bam bits for the track
int vdrive_bam_allocate_chain (vdrive_t *vdrive, unsigned int t, unsigned int s)
follow a passed t/s location and allocate all used sectors (used for validate)
int vdrive_bam_allocate_chain_255 (vdrive_t *vdrive, unsigned int t, unsigned int s)
returns DOS error values, 0 = okay, etc
static uint8_t * vdrive_bam_get_track_entry (vdrive_t *vdrive, unsigned int track, unsigned int sector)
Get pointer to the BAM entry for track in vdrive's image.
static void vdrive_bam_sector_free (vdrive_t *vdrive, uint8_t *bamp, unsigned int track, int add)
adjust "blocks available" based on drive type, 1571 and NPs are exceptions
int vdrive_bam_allocate_sector (vdrive_t *vdrive, unsigned int track, unsigned int sector)
allocate a t/s in the bam
int vdrive_bam_free_sector (vdrive_t *vdrive, unsigned int track, unsigned int sector)
unallocate a t/s in the bam
int vdrive_bam_is_sector_allocated (struct vdrive_s *vdrive, unsigned int track, unsigned int sector)
check to see if a sector is allocated
void vdrive_bam_clear_all (vdrive_t *vdrive)
used by validate to clear out bam - sets all blocks as used
static uint8_t * mystrncpy (uint8_t *d, const uint8_t *s, size_t n)
void vdrive_bam_create_empty_bam (vdrive_t *vdrive, const char *name, uint8_t *id)
used by format to setup bam/dir values
int vdrive_bam_int_get_disk_id (vdrive_t *vdrive, uint8_t *id)
get disk id internally
int vdrive_bam_get_disk_id (unsigned int unit, unsigned int drive, uint8_t *id)
get disk id
int vdrive_bam_set_disk_id (unsigned int unit, unsigned int drive, uint8_t *id)
set disk id
int vdrive_bam_read_bam (vdrive_t *vdrive)
int vdrive_bam_write_bam (vdrive_t *vdrive)
Update ALL bam data back to image.
unsigned int vdrive_bam_free_block_count (vdrive_t *vdrive)
int vdrive_bam_isgeos (vdrive_t *vdrive)
void vdrive_bam_setup_bam (vdrive_t *vdrive)
Function Documentation
mystrncpy()
static uint8_t * mystrncpy (uint8_t * d, const uint8_t * s, size_t n) static
Todo:
FIXME: Should be removed some day.
Fixed up a little bit to behave more like strncpy(3), but it's still screwed.
Referenced by vdrive_bam_create_empty_bam().
vdrive_bam_alloc_add_interleave()
static int vdrive_bam_alloc_add_interleave (vdrive_t * vdrive, unsigned int track, unsigned int sector, unsigned int interleave) static
add interleave to current sector and adjust for overflow
Referenced by vdrive_bam_alloc_down(), vdrive_bam_alloc_next_free_sector_interleave(), vdrive_bam_alloc_next_free_sector_reset(), and vdrive_bam_alloc_up().
vdrive_bam_alloc_down()
static int vdrive_bam_alloc_down (vdrive_t * vdrive, unsigned int * track, unsigned int * sector, unsigned int interleave) static
Referenced by vdrive_bam_alloc_next_free_sector_interleave().
vdrive_bam_alloc_first_free_sector()
int vdrive_bam_alloc_first_free_sector (vdrive_t * vdrive, unsigned int * track, unsigned int * sector)
Referenced by iec_open_write(), iec_write_sequential(), vdrive_command_copy(), and vdrive_rel_add_sector().
vdrive_bam_alloc_next_free_sector()
int vdrive_bam_alloc_next_free_sector (vdrive_t * vdrive, unsigned int * track, unsigned int * sector)
similar to above, but the default interleave is used.
Referenced by iec_write_sequential(), vdrive_bam_alloc_first_free_sector(), vdrive_command_block(), vdrive_command_copy(), vdrive_command_mkdir(), and vdrive_rel_add_sector().
vdrive_bam_alloc_next_free_sector_interleave()
int vdrive_bam_alloc_next_free_sector_interleave (vdrive_t * vdrive, unsigned int * track, unsigned int * sector, unsigned int interleave)
Referenced by vdrive_bam_alloc_next_free_sector(), and vdrive_dir_find_next_slot().
vdrive_bam_alloc_next_free_sector_reset()
static int vdrive_bam_alloc_next_free_sector_reset (vdrive_t * vdrive, unsigned int track, unsigned int sector, unsigned int interleave) static
resets the "sector" to zero, but keeps the "head" value; for D9090/60
Referenced by vdrive_bam_alloc_next_free_sector_interleave().
vdrive_bam_alloc_up()
static int vdrive_bam_alloc_up (vdrive_t * vdrive, unsigned int * track, unsigned int * sector, unsigned int interleave) static
Referenced by vdrive_bam_alloc_next_free_sector_interleave().
vdrive_bam_alloc_worker()
static int vdrive_bam_alloc_worker (vdrive_t * vdrive, unsigned int track, unsigned int * sector) static
Referenced by vdrive_bam_alloc_down(), vdrive_bam_alloc_first_free_sector(), vdrive_bam_alloc_next_free_sector_interleave(), and vdrive_bam_alloc_up().
vdrive_bam_allocate_chain()
int vdrive_bam_allocate_chain (vdrive_t * vdrive, unsigned int t, unsigned int s)
follow a passed t/s location and allocate all used sectors (used for validate)
returns DOS error values, 0 = okay, etc
Referenced by vdrive_command_validate().
vdrive_bam_allocate_chain_255()
int vdrive_bam_allocate_chain_255 (vdrive_t * vdrive, unsigned int t, unsigned int s)
returns DOS error values, 0 = okay, etc
Referenced by vdrive_command_validate().
vdrive_bam_allocate_sector()
int vdrive_bam_allocate_sector (vdrive_t * vdrive, unsigned int track, unsigned int sector)
allocate a t/s in the bam
return of 1 if okay, 0 if failed (1571 > 70 tracks) or already allocated
< number of tracks on a 1571 floppy
Referenced by find_next_directory_sector(), vdrive_bam_alloc_next_free_sector_interleave(), vdrive_bam_alloc_worker(), vdrive_bam_allocate_chain(), vdrive_bam_allocate_chain_255(), vdrive_command_allocate_chain(), vdrive_command_block(), vdrive_command_chpart(), vdrive_command_validate(), and vdrive_command_validate_worker().
vdrive_bam_clear_all()
void vdrive_bam_clear_all (vdrive_t * vdrive)
used by validate to clear out bam - sets all blocks as used
< BAM bitmap entries for tracks 36-40 for extended floppies, only valid for SpeedDOS
< Dual Disk Drive
< start of bitmap in each BAM blk
< number of tracks on a standard 1541 floppy
< start of bitmap in each BAM blk
< number of tracks on a 1571 floppy
< BAM bitmap entries for tracks 36-40 for extended floppies (did these exist?)
< number of tracks on a 1571 floppy
< number of tracks on a 1571 floppy
< number of tracks on a 1581 diskette
< number of tracks on a 1581 diskette
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_command_validate().
vdrive_bam_clr()
static void vdrive_bam_clr (vdrive_t * vdrive, uint8_t * bamp, unsigned int sector) static
bamp should point to "sectors available", not the bam bits for the track
Referenced by vdrive_bam_allocate_sector().
vdrive_bam_create_empty_bam()
void vdrive_bam_create_empty_bam (vdrive_t * vdrive, const char * name, uint8_t * id)
used by format to setup bam/dir values
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_command_format_worker().
vdrive_bam_free_block_count()
unsigned int vdrive_bam_free_block_count (vdrive_t * vdrive)
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
< number of tracks on a 1571 floppy
< BAM bitmap entries for tracks 36-40 for extended floppies (did these exist?)
< number of tracks on a 1571 floppy
Referenced by diskcontents_block_read(), vdrive_command_copy(), vdrive_command_mkdir(), and vdrive_dir_next_directory().
vdrive_bam_free_sector()
int vdrive_bam_free_sector (vdrive_t * vdrive, unsigned int track, unsigned int sector)
unallocate a t/s in the bam
return of 1 if okay, 0 if failed (1571 > 70 tracks) or already allocated
< number of tracks on a 1571 floppy
Referenced by vdrive_command_block(), vdrive_command_copy(), vdrive_command_mkdir(), vdrive_command_scratch(), vdrive_command_validate(), vdrive_dir_find_next_slot(), and vdrive_dir_free_chain().
vdrive_bam_get_disk_id()
int vdrive_bam_get_disk_id (unsigned int unit, unsigned int drive, uint8_t * id)
get disk id
Referenced by disk_eof_callback(), and file_system_bam_get_disk_id().
vdrive_bam_get_interleave()
static int vdrive_bam_get_interleave (vdrive_t * vdrive) static
lookup interleave value for supported drive types
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_bam_alloc_next_free_sector().
vdrive_bam_get_track_entry()
static uint8_t * vdrive_bam_get_track_entry (vdrive_t * vdrive, unsigned int track, unsigned int sector) static
Get pointer to the BAM entry for track in vdrive's image.
A CBMDOS BAM entry consists of a single byte indication the number of free sectors (unreliable since there's a lot of disks out there which set this to 0 to get a "0 blocks free."), followed by a bitmap of free/used sectors. The size of the bitmap depends on the image type, 1541 and 1571 have three bytes (enough for 21 sectors), while 1581 has 5 bytes (40 sectors).
Parameters
[in] vdrive vdrive object
[in] track track number
[in] sector sector number (needed for D9090/60)
Returns
pointer to BAM entry
< Dual Disk Drive
< number of tracks on a standard 1541 floppy
< start of bitmap in each BAM blk
< BAM bitmap entries for tracks 36-40 for extended floppies, only valid for SpeedDOS
< number of tracks on a standard 1541 floppy
< number of tracks on a 1571 floppy
< start of bitmap in each BAM blk
< number of tracks on a 1571 floppy
< BAM track number
< BAM track number
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_bam_allocate_sector(), vdrive_bam_free_block_count(), vdrive_bam_free_sector(), and vdrive_bam_is_sector_allocated().
vdrive_bam_int_get_disk_id()
int vdrive_bam_int_get_disk_id (vdrive_t * vdrive, uint8_t * id)
get disk id internally
Referenced by vdrive_bam_get_disk_id(), and vdrive_command_format_worker().
vdrive_bam_is_sector_allocated()
int vdrive_bam_is_sector_allocated (struct vdrive_s * vdrive, unsigned int track, unsigned int sector)
check to see if a sector is allocated
return of 1 if yes, 0 if not, -1 if failed (1571 > 70 tracks)
< number of tracks on a 1571 floppy
Referenced by vdrive_command_chpart().
vdrive_bam_isgeos()
int vdrive_bam_isgeos (vdrive_t * vdrive)
Referenced by vdrive_command_scratch(), and vdrive_command_validate().
vdrive_bam_isset()
static int vdrive_bam_isset (vdrive_t * vdrive, uint8_t * bamp, unsigned int sector) static
bamp should point to "sectors available", not the bam bits for the track
return of 0 is allocated, anything else is unallocated
Referenced by vdrive_bam_allocate_sector(), vdrive_bam_free_sector(), and vdrive_bam_is_sector_allocated().
vdrive_bam_read_bam()
int vdrive_bam_read_bam (vdrive_t * vdrive)
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by diskcontents_block_read(), vdrive_attach_image(), vdrive_bam_clear_all(), vdrive_bam_free_block_count(), and vdrive_command_validate().
vdrive_bam_read_bam_block()
static int vdrive_bam_read_bam_block (vdrive_t * vdrive, unsigned int block) static
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_bam_clr(), vdrive_bam_get_track_entry(), vdrive_bam_int_get_disk_id(), vdrive_bam_isset(), vdrive_bam_read_bam(), vdrive_bam_read_bam_block(), vdrive_bam_sector_free(), vdrive_bam_set(), and vdrive_bam_set_disk_id().
vdrive_bam_sector_free()
static void vdrive_bam_sector_free (vdrive_t * vdrive, uint8_t * bamp, unsigned int track, int add) static
adjust "blocks available" based on drive type, 1571 and NPs are exceptions
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
< number of tracks on a 1571 floppy
< BAM bitmap entries for tracks 36-40 for extended floppies (did these exist?)
< number of tracks on a 1571 floppy
Referenced by vdrive_bam_allocate_sector(), and vdrive_bam_free_sector().
vdrive_bam_set()
static void vdrive_bam_set (vdrive_t * vdrive, uint8_t * bamp, unsigned int sector) static
bamp should point to "sectors available", not the bam bits for the track
Referenced by vdrive_bam_free_sector().
vdrive_bam_set_disk_id()
int vdrive_bam_set_disk_id (unsigned int unit, unsigned int drive, uint8_t * id)
set disk id
Referenced by file_system_bam_set_disk_id().
vdrive_bam_setup_bam()
void vdrive_bam_setup_bam (vdrive_t * vdrive)
< BAM track number (side 1 BAM)
< BAM sector number (side 1 BAM)
< Dual Disk Drive
< 1541 BAM track number
< 1541 BAM sector number
< Dual Disk Drive
< Dual Disk Drive
< block w/disk name
< block w/disk name
Referenced by vdrive_bam_create_empty_bam(), vdrive_command_chpart(), vdrive_command_initialize(), vdrive_command_renameheader(), vdrive_iec_switch(), vdrive_refresh(), and vdrive_switch().
vdrive_bam_write_bam()
int vdrive_bam_write_bam (vdrive_t * vdrive)
Update ALL bam data back to image.
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by iec_close_sequential(), vdrive_attach_image(), vdrive_bam_set_disk_id(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_format_worker(), vdrive_command_initialize(), vdrive_command_mkdir(), vdrive_command_renameheader(), vdrive_command_validate(), vdrive_dir_remove_slot(), vdrive_flush(), vdrive_iec_switch(), vdrive_rel_grow(), and vdrive_switch().
vdrive_calculate_disk_half()
static int vdrive_calculate_disk_half (vdrive_t * vdrive) static
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_bam_alloc_first_free_sector().