vsid: sid/sid.c File Reference
sid.c File Reference
MOS6581 (SID) emulation, hooks to actual implementation.
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "alarm.h"
#include "catweaselmkiii.h"
#include "fastsid.h"
#include "hardsid.h"
#include "joyport.h"
#include "lib.h"
#include "machine.h"
#include "maincpu.h"
#include "parsid.h"
#include "resources.h"
#include "sid-resources.h"
#include "sid-snapshot.h"
#include "sid.h"
#include "sound.h"
#include "types.h"
#include "mouse.h"
#include "lightpen.h"
Data Structures
struct sound_s
needed data for SID
Macros
#define SIDx_READ(sid_nr)
#define SIDx_PEEK(sid_nr)
#define SIDx_STORE(sid_nr)
#define SIDx_DUMP(sid_nr)
#define GETBUFx(nr)
Functions
struct sound_s * fakesid_open (uint8_t *sidstate)
int fakesid_init (struct sound_s *psid, int speed, int cycles_per_sec, int factor)
void fakesid_close (struct sound_s *psid)
uint8_t fakesid_read (struct sound_s *psid, uint16_t addr)
void fakesid_store (struct sound_s *psid, uint16_t addr, uint8_t val)
void fakesid_reset (struct sound_s *psid, CLOCK cpu_clk)
int fakesid_calculate_samples (struct sound_s *psid, short *pbuf, int nr, int interleave, CLOCK *delta_t)
char * fakesid_dump_state (struct sound_s *psid)
void fakesid_resid_state_read (struct sound_s *psid, struct sid_snapshot_state_s *sid_state)
void fakesid_resid_state_write (struct sound_s *psid, struct sid_snapshot_state_s *sid_state)
uint8_t * sid_get_siddata (unsigned int channel)
static int sid_read_off (uint16_t addr, int chipno)
static void sid_write_off (uint16_t addr, uint8_t val, int chipno)
static uint8_t sid_read_chip (uint16_t addr, int chipno)
static uint8_t sid_peek_chip (uint16_t addr, int chipno)
static void sid_store_chip (uint16_t addr, uint8_t byte, int chipno)
write register value to sid
static int sid_dump_chip (int chipno)
uint8_t sid_read (uint16_t addr)
uint8_t sid2_read (uint16_t addr)
uint8_t sid3_read (uint16_t addr)
uint8_t sid4_read (uint16_t addr)
uint8_t sid5_read (uint16_t addr)
uint8_t sid6_read (uint16_t addr)
uint8_t sid7_read (uint16_t addr)
uint8_t sid8_read (uint16_t addr)
uint8_t sid_peek (uint16_t addr)
uint8_t sid2_peek (uint16_t addr)
uint8_t sid3_peek (uint16_t addr)
uint8_t sid4_peek (uint16_t addr)
uint8_t sid5_peek (uint16_t addr)
uint8_t sid6_peek (uint16_t addr)
uint8_t sid7_peek (uint16_t addr)
uint8_t sid8_peek (uint16_t addr)
void sid_store (uint16_t addr, uint8_t byte)
void sid2_store (uint16_t addr, uint8_t byte)
void sid3_store (uint16_t addr, uint8_t byte)
void sid4_store (uint16_t addr, uint8_t byte)
void sid5_store (uint16_t addr, uint8_t byte)
void sid6_store (uint16_t addr, uint8_t byte)
void sid7_store (uint16_t addr, uint8_t byte)
void sid8_store (uint16_t addr, uint8_t byte)
int sid_dump (void)
int sid2_dump (void)
int sid3_dump (void)
int sid4_dump (void)
int sid5_dump (void)
int sid6_dump (void)
int sid7_dump (void)
int sid8_dump (void)
void sid_reset (void)
bool sid_sound_machine_set_engine_hooks (void)
sound_t * sid_sound_machine_open (int chipno)
static int16_t * getbuf1 (int len)
static int16_t * getbuf2 (int len)
static int16_t * getbuf3 (int len)
static int16_t * getbuf4 (int len)
static int16_t * getbuf5 (int len)
static int16_t * getbuf6 (int len)
static int16_t * getbuf7 (int len)
int sid_sound_machine_init_vbr (sound_t *psid, int speed, int cycles_per_sec, int factor)
int sid_sound_machine_init (sound_t *psid, int speed, int cycles_per_sec)
void sid_sound_machine_close (sound_t *psid)
uint8_t sid_sound_machine_read (sound_t *psid, uint16_t addr)
void sid_sound_machine_store (sound_t *psid, uint16_t addr, uint8_t byte)
void sid_sound_machine_reset (sound_t *psid, CLOCK cpu_clk)
int sid_sound_machine_calculate_samples (sound_t **psid, int16_t *pbuf, int nr, int soc, int scc, CLOCK *delta_t)
char * sid_sound_machine_dump_state (sound_t *psid)
int sid_sound_machine_cycle_based (void)
int sid_sound_machine_channels (void)
static void set_sound_func (void)
void sid_sound_machine_enable (int enable)
int sid_engine_set (int engine)
void sid_state_read (unsigned int channel, sid_snapshot_state_t *sid_state)
void sid_state_write (unsigned int channel, sid_snapshot_state_t *sid_state)
void sid_set_machine_parameter (long clock_rate)
int sid_engine_get_max_sids (int engine)
Get maximum number of support SIDs for engine.
int sid_machine_get_max_sids (void)
Get maximum number of SIDs for the current machine, using actual HW.
int sid_machine_engine_get_max_sids (int engine)
Determine maximum number of SIDs for current machine and a \engine.
int sid_machine_can_have_multiple_sids (void)
Determine if the current machine can support multiple SIDs.
Variables
static sid_engine_t sid_engine
SID engine hooks.
static uint8_t lastsidread
read register value from sid
static uint8_t siddata [8][32]
register data
static int(* sid_read_func)(uint16_t addr, int chipno)
static void(* sid_store_func)(uint16_t addr, uint8_t val, int chipno)
static int(* sid_dump_func)(int chipno)
static int sid_enable
static int sid_engine_type = -1
static CLOCK pot_cycle = 0
static uint8_t val_pot_x = 0xff
static uint8_t val_pot_y = 0xff
sid_engine_t fakesid_hooks
static int sidengine
static int16_t * buf1 = NULL
static int16_t * buf2 = NULL
static int16_t * buf3 = NULL
static int16_t * buf4 = NULL
static int16_t * buf5 = NULL
static int16_t * buf6 = NULL
static int16_t * buf7 = NULL
static int blen1 = 0
static int blen2 = 0
static int blen3 = 0
static int blen4 = 0
static int blen5 = 0
static int blen6 = 0
static int blen7 = 0
Detailed Description
MOS6581 (SID) emulation, hooks to actual implementation.
Author
Teemu Rantanen tvr@c.nosp@m.s.hu.nosp@m.t.fi
Michael Schwendt sidpl.nosp@m.ay@g.nosp@m.eocit.nosp@m.ies..nosp@m.com
Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it
Dag Lem resid.nosp@m.@nim.nosp@m.rod.n.nosp@m.o
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Macro Definition Documentation
GETBUFx
#define GETBUFx (nr)
Value:
    static int16_t *getbuf##nr(int len)             \
    {                                               \
        if (buf##nr != NULL) {                      \
            if (blen##nr >= len) {                  \
                /* large enough */                  \
                return buf##nr;                     \
            }                                       \
            lib_free(buf##nr);                      \
        }                                           \
        buf##nr = lib_calloc(len, sizeof(int16_t)); \
        blen##nr = len;                             \
        return buf##nr;                             \
    }
SIDx_DUMP
#define SIDx_DUMP (sid_nr)
Value:
    int sid##sid_nr##_dump(void)          \
    {                                     \
        return sid_dump_chip(sid_nr - 1); \
    }
SIDx_PEEK
#define SIDx_PEEK (sid_nr)
Value:
    uint8_t sid##sid_nr##_peek(uint16_t addr)   \
    {                                           \
        return sid_peek_chip(addr, sid_nr - 1); \
    }
SIDx_READ
#define SIDx_READ (sid_nr)
Value:
    uint8_t sid##sid_nr##_read(uint16_t addr)   \
    {                                           \
        return sid_read_chip(addr, sid_nr - 1); \
    }
SIDx_STORE
#define SIDx_STORE (sid_nr)
Value:
    void sid##sid_nr##_store(uint16_t addr, uint8_t byte) \
    {                                                     \
        sid_store_chip(addr, byte, sid_nr - 1);           \
    }
Function Documentation
fakesid_calculate_samples()
int fakesid_calculate_samples (struct sound_s * psid, short * pbuf, int nr, int interleave, CLOCK * delta_t)
fakesid_close()
void fakesid_close (struct sound_s * psid)
fakesid_dump_state()
char * fakesid_dump_state (struct sound_s * psid)
fakesid_init()
int fakesid_init (struct sound_s * psid, int speed, int cycles_per_sec, int factor)
fakesid_open()
struct sound_s * fakesid_open (uint8_t * sidstate)
fakesid_read()
uint8_t fakesid_read (struct sound_s * psid, uint16_t addr)
fakesid_reset()
void fakesid_reset (struct sound_s * psid, CLOCK cpu_clk)
fakesid_resid_state_read()
void fakesid_resid_state_read (struct sound_s * psid, struct sid_snapshot_state_s * sid_state)
fakesid_resid_state_write()
void fakesid_resid_state_write (struct sound_s * psid, struct sid_snapshot_state_s * sid_state)
fakesid_store()
void fakesid_store (struct sound_s * psid, uint16_t addr, uint8_t val)
getbuf1()
static int16_t * getbuf1 (int len) static
Referenced by sid_sound_machine_calculate_samples().
getbuf2()
static int16_t * getbuf2 (int len) static
Referenced by sid_sound_machine_calculate_samples().
getbuf3()
static int16_t * getbuf3 (int len) static
Referenced by sid_sound_machine_calculate_samples().
getbuf4()
static int16_t * getbuf4 (int len) static
Referenced by sid_sound_machine_calculate_samples().
getbuf5()
static int16_t * getbuf5 (int len) static
Referenced by sid_sound_machine_calculate_samples().
getbuf6()
static int16_t * getbuf6 (int len) static
Referenced by sid_sound_machine_calculate_samples().
getbuf7()
static int16_t * getbuf7 (int len) static
Referenced by sid_sound_machine_calculate_samples().
set_sound_func()
static void set_sound_func (void) static
Referenced by sid_engine_set(), and sid_sound_machine_enable().
sid2_dump()
int sid2_dump (void)
sid2_peek()
uint8_t sid2_peek (uint16_t addr)
sid2_read()
uint8_t sid2_read (uint16_t addr)
sid2_store()
void sid2_store (uint16_t addr, uint8_t byte)
Referenced by sid_snapshot_read_module_extended().
sid3_dump()
int sid3_dump (void)
sid3_peek()
uint8_t sid3_peek (uint16_t addr)
sid3_read()
uint8_t sid3_read (uint16_t addr)
sid3_store()
void sid3_store (uint16_t addr, uint8_t byte)
Referenced by sid_snapshot_read_module_extended().
sid4_dump()
int sid4_dump (void)
sid4_peek()
uint8_t sid4_peek (uint16_t addr)
sid4_read()
uint8_t sid4_read (uint16_t addr)
sid4_store()
void sid4_store (uint16_t addr, uint8_t byte)
Referenced by sid_snapshot_read_module_extended().
sid5_dump()
int sid5_dump (void)
sid5_peek()
uint8_t sid5_peek (uint16_t addr)
sid5_read()
uint8_t sid5_read (uint16_t addr)
sid5_store()
void sid5_store (uint16_t addr, uint8_t byte)
Referenced by sid_snapshot_read_module_extended().
sid6_dump()
int sid6_dump (void)
sid6_peek()
uint8_t sid6_peek (uint16_t addr)
sid6_read()
uint8_t sid6_read (uint16_t addr)
sid6_store()
void sid6_store (uint16_t addr, uint8_t byte)
Referenced by sid_snapshot_read_module_extended().
sid7_dump()
int sid7_dump (void)
sid7_peek()
uint8_t sid7_peek (uint16_t addr)
sid7_read()
uint8_t sid7_read (uint16_t addr)
sid7_store()
void sid7_store (uint16_t addr, uint8_t byte)
Referenced by sid_snapshot_read_module_extended().
sid8_dump()
int sid8_dump (void)
sid8_peek()
uint8_t sid8_peek (uint16_t addr)
sid8_read()
uint8_t sid8_read (uint16_t addr)
sid8_store()
void sid8_store (uint16_t addr, uint8_t byte)
Referenced by sid_snapshot_read_module_extended().
sid_dump()
int sid_dump (void)
Referenced by mem_dump_io().
sid_dump_chip()
static int sid_dump_chip (int chipno) static
Referenced by sid_dump().
sid_engine_get_max_sids()
int sid_engine_get_max_sids (int engine)
Get maximum number of support SIDs for engine.
Helper function for UIs: determine number of supported SIDs to allow UIs to not display impossible settings.
Parameters
[in] engine engine ID
See also
sid.h for engine IDs
Referenced by sid_machine_engine_get_max_sids().
sid_engine_set()
int sid_engine_set (int engine)
Referenced by set_sid_engine().
sid_get_siddata()
uint8_t * sid_get_siddata (unsigned int channel)
Referenced by sid_snapshot_read_module_extended(), sid_snapshot_read_module_simple(), and sid_snapshot_write_module_simple().
sid_machine_can_have_multiple_sids()
int sid_machine_can_have_multiple_sids (void)
Determine if the current machine can support multiple SIDs.
This ignores any expansions and the SID engine, just gives the theoretical maximum that can be done with the current HW available.
Returns
boolean
Referenced by sid_sound_widget_create(), and update_sid_addresses_sensitivity().
sid_machine_engine_get_max_sids()
int sid_machine_engine_get_max_sids (int engine)
Determine maximum number of SIDs for current machine and a \engine.
Only assumes actually available HW expansion and actual old HW, so no Ultimate64 etc.
Parameters
[in] engine SID engine
Returns
maximum number of SIDs
sid_machine_get_max_sids()
int sid_machine_get_max_sids (void)
Get maximum number of SIDs for the current machine, using actual HW.
Returns
number of SIDs
Referenced by create_sid_address_widgets(), sid_machine_can_have_multiple_sids(), and sid_machine_engine_get_max_sids().
sid_peek()
uint8_t sid_peek (uint16_t addr)
Referenced by peek_bank_io().
sid_peek_chip()
static uint8_t sid_peek_chip (uint16_t addr, int chipno) static
Todo:
FIXME: get 0x1b and 0x1c from engine
Referenced by sid_peek().
sid_read()
uint8_t sid_read (uint16_t addr)
Referenced by c64meminit(), read_bank_io(), and vsid_io_read().
sid_read_chip()
static uint8_t sid_read_chip (uint16_t addr, int chipno) static
Todo:
FIXME: we should really use an alarm to update the POT values every 512 cycles. unfortunately the current mouse code will not work with this approach
Referenced by sid_read().
sid_read_off()
static int sid_read_off (uint16_t addr, int chipno) static
Todo:
FIXME: Change API, return BYTE!
Referenced by set_sound_func().
sid_reset()
void sid_reset (void)
Todo:
FIXME: we should really use an alarm to update the POT values every 512 cycles. unfortunately the current mouse code will not work with this approach
Referenced by machine_specific_reset().
sid_set_machine_parameter()
void sid_set_machine_parameter (long clock_rate)
Referenced by machine_change_timing().
sid_sound_machine_calculate_samples()
int sid_sound_machine_calculate_samples (sound_t ** psid, int16_t * pbuf, int nr, int soc, int scc, CLOCK * delta_t)
sid_sound_machine_channels()
int sid_sound_machine_channels (void)
sid_sound_machine_close()
void sid_sound_machine_close (sound_t * psid)
sid_sound_machine_cycle_based()
int sid_sound_machine_cycle_based (void)
sid_sound_machine_dump_state()
char * sid_sound_machine_dump_state (sound_t * psid)
Referenced by sound_machine_dump_state().
sid_sound_machine_enable()
void sid_sound_machine_enable (int enable)
Referenced by sound_machine_enable().
sid_sound_machine_init()
int sid_sound_machine_init (sound_t * psid, int speed, int cycles_per_sec)
sid_sound_machine_init_vbr()
int sid_sound_machine_init_vbr (sound_t * psid, int speed, int cycles_per_sec, int factor)
sid_sound_machine_open()
sound_t * sid_sound_machine_open (int chipno)
sid_sound_machine_read()
uint8_t sid_sound_machine_read (sound_t * psid, uint16_t addr)
sid_sound_machine_reset()
void sid_sound_machine_reset (sound_t * psid, CLOCK cpu_clk)
sid_sound_machine_set_engine_hooks()
bool sid_sound_machine_set_engine_hooks (void)
Referenced by sid_snapshot_write_module(), and sid_sound_machine_open().
sid_sound_machine_store()
void sid_sound_machine_store (sound_t * psid, uint16_t addr, uint8_t byte)
sid_state_read()
void sid_state_read (unsigned int channel, sid_snapshot_state_t * sid_state)
sid_state_write()
void sid_state_write (unsigned int channel, sid_snapshot_state_t * sid_state)
sid_store()
void sid_store (uint16_t addr, uint8_t byte)
Referenced by c64meminit(), sid_snapshot_read_module_extended(), sid_store_d700(), store_bank_io(), and vsid_io_store().
sid_store_chip()
static void sid_store_chip (uint16_t addr, uint8_t byte, int chipno) static
write register value to sid
Referenced by sid_store().
sid_write_off()
static void sid_write_off (uint16_t addr, uint8_t val, int chipno) static
Referenced by set_sound_func().
Variable Documentation
blen1
int blen1 = 0 static
Referenced by sid_sound_machine_close().
blen2
int blen2 = 0 static
Referenced by sid_sound_machine_close().
blen3
int blen3 = 0 static
Referenced by sid_sound_machine_close().
blen4
int blen4 = 0 static
Referenced by sid_sound_machine_close().
blen5
int blen5 = 0 static
Referenced by sid_sound_machine_close().
blen6
int blen6 = 0 static
Referenced by sid_sound_machine_close().
blen7
int blen7 = 0 static
Referenced by sid_sound_machine_close().
buf1
int16_t* buf1 = NULL static
Referenced by sid_sound_machine_close().
buf2
int16_t* buf2 = NULL static
Referenced by sid_sound_machine_close().
buf3
int16_t* buf3 = NULL static
Referenced by sid_sound_machine_close().
buf4
int16_t* buf4 = NULL static
Referenced by sid_sound_machine_close().
buf5
int16_t* buf5 = NULL static
Referenced by sid_sound_machine_close().
buf6
int16_t* buf6 = NULL static
Referenced by sid_sound_machine_close().
buf7
int16_t* buf7 = NULL static
Referenced by sid_sound_machine_close().
fakesid_hooks
sid_engine_t fakesid_hooks
Initial value:
=
{
    fakesid_open,
    fakesid_init,
    fakesid_close,
    fakesid_read,
    fakesid_store,
    fakesid_reset,
    fakesid_calculate_samples,
    fakesid_dump_state,
    fakesid_resid_state_read,
    fakesid_resid_state_write
}
Referenced by sid_sound_machine_set_engine_hooks().
lastsidread
uint8_t lastsidread static
read register value from sid
Referenced by sid_read_chip(), and sid_store_chip().
pot_cycle
CLOCK pot_cycle = 0 static
Referenced by sid_read_chip().
sid_dump_func
int(* sid_dump_func) (int chipno) (int chipno) static
Referenced by set_sound_func(), and sid_dump_chip().
sid_enable
int sid_enable static
Referenced by set_sound_func(), and sid_sound_machine_enable().
sid_engine
sid_engine_t sid_engine static
SID engine hooks.
Referenced by sid_sound_machine_calculate_samples(), sid_sound_machine_close(), sid_sound_machine_dump_state(), sid_sound_machine_init(), sid_sound_machine_init_vbr(), sid_sound_machine_open(), sid_sound_machine_read(), sid_sound_machine_reset(), sid_sound_machine_set_engine_hooks(), sid_sound_machine_store(), sid_state_read(), and sid_state_write().
sid_engine_type
int sid_engine_type = -1 static
Referenced by set_sound_func(), and sid_engine_set().
sid_read_func
int(* sid_read_func) (uint16_t addr, int chipno) (uint16_t addr, int chipno) static
Referenced by set_sound_func(), and sid_read_chip().
sid_store_func
void(* sid_store_func) (uint16_t addr, uint8_t val, int chipno) (uint16_t addr, uint8_t val, int chipno) static
Referenced by set_sound_func(), and sid_store_chip().
siddata
uint8_t siddata[8][32] static
register data
Referenced by sid_get_siddata(), sid_peek_chip(), sid_reset(), sid_snapshot_read_module_extended(), sid_sound_machine_open(), and sid_store_chip().
sidengine
int sidengine static
Referenced by sid_sound_machine_cycle_based(), and sid_sound_machine_set_engine_hooks().
val_pot_x
uint8_t val_pot_x = 0xff static
Referenced by sid_read_chip().
val_pot_y
uint8_t val_pot_y = 0xff static
Referenced by sid_read_chip().