vsid: fliplist.c File Reference
fliplist.c File Reference
Fliplist handling.
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "archdep.h"
#include "attach.h"
#include "charset.h"
#include "cmdline.h"
#include "drive.h"
#include "fliplist.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "util.h"
Data Structures
struct fliplist_s
Macros
#define DBG(x)
#define buffer_size 1024
Functions
static void show_fliplist (unsigned int unit)
static int set_fliplist_file_name (const char *val, void *param)
int fliplist_resources_init (void)
void fliplist_resources_shutdown (void)
int fliplist_cmdline_options_init (void)
void fliplist_shutdown (void)
interface functions
void fliplist_set_current (unsigned int unit, const char *filename)
char * fliplist_get_head (unsigned int unit)
const char * fliplist_get_next (unsigned int unit)
const char * fliplist_get_prev (unsigned int unit)
const char * fliplist_get_image (fliplist_t fl)
unsigned int fliplist_get_unit (fliplist_t fl)
bool fliplist_add_image (unsigned int unit)
void fliplist_remove (unsigned int unit, const char *image)
bool fliplist_attach_head (unsigned int unit, int direction)
Attach new image from the fliplist.
fliplist_t fliplist_init_iterate (unsigned int unit)
fliplist_t fliplist_next_iterate (unsigned int unit)
void fliplist_clear_list (unsigned int unit)
int fliplist_save_list (unsigned int unit, const char *filename)
int fliplist_load_list (unsigned int unit, const char *filename, int autoattach)
Variables
static fliplist_t fliplist [4]
static char * current_image = (char *)NULL
static unsigned int current_drive
static fliplist_t iterator
static const char flip_file_header_old [] = "# Vice fliplist file"
static const char flip_file_header_new [] = "; Vice fliplist file"
static const char flip_file_petscii [9] = { 0x23, 0x50, 0x45, 0x54, 0x53, 0x43, 0x49, 0x49, 0 }
static char * fliplist_file_name = NULL
static char * fliplist_factory = NULL
Keep track of factory value.
static resource_string_t resources_string []
static const cmdline_option_t cmdline_options []
Detailed Description
Fliplist handling.
Author
pottendo potte.nosp@m.ndo@.nosp@m.gmx.n.nosp@m.et
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
buffer_size
#define buffer_size 1024
DBG
#define DBG (x)
Function Documentation
fliplist_add_image()
bool fliplist_add_image (unsigned int unit)
Referenced by fliplist_add_action().
fliplist_attach_head()
bool fliplist_attach_head (unsigned int unit, int direction)
Attach new image from the fliplist.
Parameters
[in] unit drive unit number (8-11)
[in] direction attach either next (>=1) or previous image
Returns
boolean
Referenced by fliplist_load_list(), fliplist_next_action(), fliplist_previous_action(), and ui_fliplist_select_cb().
fliplist_clear_list()
void fliplist_clear_list (unsigned int unit)
Referenced by fliplist_clear_action(), fliplist_load_list(), and fliplist_resources_shutdown().
fliplist_cmdline_options_init()
int fliplist_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
fliplist_get_head()
char * fliplist_get_head (unsigned int unit)
Referenced by fliplist_add_action(), fliplist_next_action(), fliplist_previous_action(), fliplist_remove_action(), and ui_fliplist_select_cb().
fliplist_get_image()
const char * fliplist_get_image (fliplist_t fl)
Referenced by ui_fliplist_select_cb(), and ui_populate_fliplist_menu().
fliplist_get_next()
const char * fliplist_get_next (unsigned int unit)
Referenced by ui_populate_fliplist_menu().
fliplist_get_prev()
const char * fliplist_get_prev (unsigned int unit)
Referenced by ui_populate_fliplist_menu().
fliplist_get_unit()
unsigned int fliplist_get_unit (fliplist_t fl)
fliplist_init_iterate()
fliplist_t fliplist_init_iterate (unsigned int unit)
Referenced by ui_do_drive_popup(), ui_fliplist_select_cb(), and ui_populate_fliplist_menu().
fliplist_load_list()
int fliplist_load_list (unsigned int unit, const char * filename, int autoattach)
< read mode (binary)
Todo:
FIXME: we should handle some special cases of pathes we can find in .lst files:
sd2iec accepts 'cmd' style pathes
all kinds of absolute pathes musst not be converted, those are non portable anyway
Referenced by fliplist_load_response(), and set_fliplist_file_name().
fliplist_next_iterate()
fliplist_t fliplist_next_iterate (unsigned int unit)
Referenced by ui_populate_fliplist_menu().
fliplist_remove()
void fliplist_remove (unsigned int unit, const char * image)
Referenced by fliplist_remove(), and fliplist_remove_action().
fliplist_resources_init()
int fliplist_resources_init (void)
Referenced by machine_resources_init().
fliplist_resources_shutdown()
void fliplist_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
fliplist_save_list()
int fliplist_save_list (unsigned int unit, const char * filename)
< write mode (binary)
Todo:
FIXME: we should handle some more special cases:
absolute pathes must not be modified (those are non portable anyway
relative pathes could be converted to a CMD style path so it works with sd2iec
Referenced by fliplist_save_response().
fliplist_set_current()
void fliplist_set_current (unsigned int unit, const char * filename)
Referenced by file_system_attach_disk_internal().
fliplist_shutdown()
void fliplist_shutdown (void)
interface functions
Referenced by cmdline_help(), and machine_shutdown().
set_fliplist_file_name()
static int set_fliplist_file_name (const char * val, void * param) static
show_fliplist()
static void show_fliplist (unsigned int unit) static
Referenced by fliplist_add_image(), fliplist_load_list(), and fliplist_remove().
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-flipname", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "FliplistName", NULL,
      "<Name>", "Specify name of the flip list file image" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by fliplist_cmdline_options_init().
current_drive
unsigned int current_drive static
Referenced by fliplist_add_image(), fliplist_load_list(), and fliplist_set_current().
current_image
char* current_image = (char *)NULL static
Referenced by fliplist_add_image(), fliplist_set_current(), and fliplist_shutdown().
flip_file_header_new
const char flip_file_header_new[] = "; Vice fliplist file" static
Referenced by fliplist_load_list(), and fliplist_save_list().
flip_file_header_old
const char flip_file_header_old[] = "# Vice fliplist file" static
Referenced by fliplist_load_list().
flip_file_petscii
const char flip_file_petscii[9] = { 0x23, 0x50, 0x45, 0x54, 0x53, 0x43, 0x49, 0x49, 0 } static
Referenced by fliplist_load_list().
fliplist
fliplist_t fliplist[4] static
Initial value:
= {
    (fliplist_t)NULL,
    (fliplist_t)NULL
}
Referenced by fliplist_add_image(), fliplist_attach_head(), fliplist_clear_list(), fliplist_get_head(), fliplist_get_next(), fliplist_get_prev(), fliplist_init_iterate(), fliplist_load_list(), fliplist_next_iterate(), fliplist_remove(), fliplist_save_list(), and show_fliplist().
fliplist_factory
char* fliplist_factory = NULL static
Keep track of factory value.
Don't free() a const
Referenced by fliplist_resources_init(), and fliplist_resources_shutdown().
fliplist_file_name
char* fliplist_file_name = NULL static
Referenced by fliplist_resources_shutdown(), and set_fliplist_file_name().
iterator
fliplist_t iterator static
Referenced by fliplist_init_iterate(), and fliplist_next_iterate().
resources_string
resource_string_t resources_string[] static
Initial value:
= {
    { "FliplistName", NULL, RES_EVENT_NO, NULL,
      &fliplist_file_name, set_fliplist_file_name, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by fliplist_resources_init().