vsid: arch/gtk3/widgets/base/resourcespinbutton.h File Reference
resourcespinbutton.h File Reference
Spin buttons to control resources - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
GtkWidget * vice_gtk3_resource_spin_int_new (const char *resource, int lower, int upper, int step)
Create integer spin button to control resource.
GtkWidget * vice_gtk3_resource_spin_int_new_sprintf (const char *fmt, int lower, int upper, int step,...)
Create integer spin button to control resource.
gboolean vice_gtk3_resource_spin_int_set (GtkWidget *widget, int value)
Set spin button widget to value.
gboolean vice_gtk3_resource_spin_int_get (GtkWidget *widget, int *value)
Get spin button widget value.
gboolean vice_gtk3_resource_spin_int_reset (GtkWidget *widget)
Reset widget to its state when instanciated.
gboolean vice_gtk3_resource_spin_int_sync (GtkWidget *widget)
Synchronize widget with its associated resource.
gboolean vice_gtk3_resource_spin_int_factory (GtkWidget *widget)
Reset widget to its resources factory value.
void vice_gtk3_resource_spin_int_set_fake_digits (GtkWidget *spin, int digits)
Set "fake digits" for the integer spint button.
GtkWidget * vice_gtk3_resource_spin_double_new (const char *resource, double upper, double lower, double step)
Create spin button for double resource.
GtkWidget * vice_gtk3_resource_spin_double_new_sprintf (const char *fmt, double upper, double lower, double step,...)
Create spin button for double resource.
gboolean vice_gtk3_resource_spin_double_get (GtkWidget *spin, double *value)
Get value of resource double spin button.
gboolean vice_gtk3_resource_spin_double_set (GtkWidget *spin, double value)
Set new value for resource double spin button.
gboolean vice_gtk3_resource_spin_double_reset (GtkWidget *spin)
Reset resource double spin button to the value on construction.
gboolean vice_gtk3_resource_spin_double_factory (GtkWidget *spin)
Restore resource double spin button to factory value.
gboolean vice_gtk3_resource_spin_double_sync (GtkWidget *spin)
Synchronize double spin button with its resource.
void vice_gtk3_resource_spin_double_set_digits (GtkWidget *spin, guint digits)
Set the precision to be displayed by a resource double spin button.
GtkWidget * vice_gtk3_resource_spin_custom_new (const gchar *resource_name, gint resource_min, gint resource_max, gdouble display_min, gdouble display_max, gdouble display_step, const gchar *display_format)
Create a resource-bound spin button with custom range and formatting.
GtkWidget * vice_gtk3_resource_spin_custom_new_sprintf (const gchar *resource_format, gint resource_min, gint resource_max, gdouble display_min, gdouble display_max, gdouble display_step, const gchar *display_format,...)
Create a resource-bound spin button with custom range and formatting.
Detailed Description
Spin buttons to control resources - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
vice_gtk3_resource_spin_custom_new()
GtkWidget * vice_gtk3_resource_spin_custom_new (const gchar * resource_name, gint resource_min, gint resource_max, gdouble display_min, gdouble display_max, gdouble display_step, const gchar * display_format)
Create a resource-bound spin button with custom range and formatting.
Create spin button that displays values between display_min and display_max but internally uses resource_min and resource_max for the resource. The display_format string is used to format the displayed value, and while the resource is an int the displayed value is a double, so the format string should reflect this. When displaying and setting the resource, scaling is applied to translate between the resource range and value and its displayed value and range.
Parameters
[in] resource_name resource name
[in] resource_min resource minimum value
[in] resource_max resource maximum value
[in] display_min displayed minimum value
[in] display_max displayed maximum value
[in] display_step displayed value stepping
[in] display_format format string for displayed value
Returns
GtkSpinButton
Referenced by create_datasette_widget(), settings_ramreset_widget_create(), and vice_gtk3_resource_spin_custom_new_sprintf().
vice_gtk3_resource_spin_custom_new_sprintf()
GtkWidget * vice_gtk3_resource_spin_custom_new_sprintf (const gchar * resource_format, gint resource_min, gint resource_max, gdouble display_min, gdouble display_max, gdouble display_step, const gchar * display_format, ...)
Create a resource-bound spin button with custom range and formatting.
This version allows using a printf-style format string for the resource name. See the non-printf vice_gtk3_resource_spin_custom_new() for documentation.
Parameters
[in] resource_format resource name format string
[in] resource_min resource minimum value
[in] resource_max resource maximum value
[in] display_min displayed minimum value
[in] display_max displayed maximum value
[in] display_step displayed value stepping
[in] display_format format string for displayed value
[in] ... arguments for the resource_format
Returns
GtkSpinButton
Referenced by drive_rpm_widget_create().
vice_gtk3_resource_spin_double_factory()
gboolean vice_gtk3_resource_spin_double_factory (GtkWidget * spin)
Restore resource double spin button to factory value.
Parameters
[in] spin resource double spin button
Returns
TRUE on success
vice_gtk3_resource_spin_double_get()
gboolean vice_gtk3_resource_spin_double_get (GtkWidget * spin, double * value)
Get value of resource double spin button.
Parameters
[in] spin resource double spin button
[out] value current value of spin
Returns
TRUE on success
vice_gtk3_resource_spin_double_new()
GtkWidget * vice_gtk3_resource_spin_double_new (const char * resource, double lower, double upper, double step)
Create spin button for double resource.
Create a resource-bound spin button interpreting a string resource to double.
Parameters
[in] resource resource name
[in] lower lower bound of value
[in] upper upper bound of value
[in] step stepping to use when clicking +/-
Returns
GtkSpinButton
Referenced by vice_gtk3_resource_spin_double_new_sprintf().
vice_gtk3_resource_spin_double_new_sprintf()
GtkWidget * vice_gtk3_resource_spin_double_new_sprintf (const char * fmt, double lower, double upper, double step, ...)
Create spin button for double resource.
Create a resource-bound spin button interpreting a string resource to double. This version uses string formatting to create the resource name.
Parameters
[in] resource resource name
[in] lower lower bound of value
[in] upper upper bound of value
[in] step stepping to use when clicking +/-
[in] ... arguments to fmt
Returns
GtkSpinButton
Referenced by video_aspect_widget_create().
vice_gtk3_resource_spin_double_reset()
gboolean vice_gtk3_resource_spin_double_reset (GtkWidget * spin)
Reset resource double spin button to the value on construction.
Reset spin to the value the bound resource contained when spin was constructed.
Parameters
[in] spin resource double spin button
Returns
TRUE on success
vice_gtk3_resource_spin_double_set()
gboolean vice_gtk3_resource_spin_double_set (GtkWidget * spin, double value)
Set new value for resource double spin button.
Parameters
[in] spin resource double spin button
[in] value new value for spin
Returns
TRUE on success
Referenced by vice_gtk3_resource_spin_double_factory(), vice_gtk3_resource_spin_double_reset(), and vice_gtk3_resource_spin_double_sync().
vice_gtk3_resource_spin_double_set_digits()
void vice_gtk3_resource_spin_double_set_digits (GtkWidget * spin, guint digits)
Set the precision to be displayed by a resource double spin button.
Parameters
[in] spin resource double spin button
[in] digits number of digits
Note
currently just calls gtk_spin_button_set_digits(spin), but the internal structure of spin might change, so this function is preferred over the gtk one.
Referenced by video_aspect_widget_create().
vice_gtk3_resource_spin_double_sync()
gboolean vice_gtk3_resource_spin_double_sync (GtkWidget * spin)
Synchronize double spin button with its resource.
Parameters
[in] spin resource double spin button
Returns
TRUE on success
vice_gtk3_resource_spin_int_factory()
gboolean vice_gtk3_resource_spin_int_factory (GtkWidget * widget)
Reset widget to its resources factory value.
Parameters
[in,out] widget integer spin button
Returns
TRUE if the widget was set to its factory value
vice_gtk3_resource_spin_int_get()
gboolean vice_gtk3_resource_spin_int_get (GtkWidget * widget, int * value)
Get spin button widget value.
Parameters
[in] widget integer spin button
[out] value object to store value
Returns
TRUE if value was set
Referenced by vice_gtk3_resource_spin_int_sync().
vice_gtk3_resource_spin_int_new()
GtkWidget * vice_gtk3_resource_spin_int_new (const char * resource, int lower, int upper, int step)
Create integer spin button to control resource.
Parameters
[in] resource resource name
[in] lower lowest value
[in] upper highest value
[in] step step for the +/- buttons
Returns
GtkSpinButton
Referenced by create_datasette_widget(), create_delay_layout(), create_num_sids_widget(), create_port_number_widget(), ffmpeg_widget_create(), settings_monitor_widget_create(), settings_netplay_widget_create(), settings_petcolourgraphics_widget_create(), settings_ramlink_widget_create(), settings_ramreset_widget_create(), and sound_buffer_size_widget_create().
vice_gtk3_resource_spin_int_new_sprintf()
GtkWidget * vice_gtk3_resource_spin_int_new_sprintf (const char * fmt, int lower, int upper, int step, ...)
Create integer spin button to control resource.
Allows setting the resource name with a variable argument list
Parameters
[in] fmt resource name format string
[in] lower lowest value
[in] upper highest value
[in] step step for the +/- buttons
Returns
GtkSpinButton
Referenced by create_ide64_geometry_widget().
vice_gtk3_resource_spin_int_reset()
gboolean vice_gtk3_resource_spin_int_reset (GtkWidget * widget)
Reset widget to its state when instanciated.
Parameters
[in,out] widget integer spin button
Returns
TRUE if the widget was reset to its original value
vice_gtk3_resource_spin_int_set()
gboolean vice_gtk3_resource_spin_int_set (GtkWidget * widget, int value)
Set spin button widget to value.
Parameters
[in,out] widget integer spin button
[in] value new value for the spin button
Returns
TRUE
Referenced by vice_gtk3_resource_spin_int_factory(), vice_gtk3_resource_spin_int_reset(), and vice_gtk3_resource_spin_int_sync().
vice_gtk3_resource_spin_int_set_fake_digits()
void vice_gtk3_resource_spin_int_set_fake_digits (GtkWidget * spin, int digits)
Set "fake digits" for the integer spint button.
Parameters
[in,out] spin integer spin button
[in] digits number of fake digits to display
vice_gtk3_resource_spin_int_sync()
gboolean vice_gtk3_resource_spin_int_sync (GtkWidget * widget)
Synchronize widget with its associated resource.
Parameters
[in,out] widget integer resource spinbutton
Returns
TRUE if the widget was sychronized