vsid: arch/gtk3/uimenu.c File Reference
uimenu.c File Reference
Native GTK3 menu handling.
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <gtk/gtk.h>
#include "archdep.h"
#include "debug_gtk3.h"
#include "vice_gtk3.h"
#include "hotkeys.h"
#include "kbd.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "ui.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uiabout.h"
#include "uistatusbar.h"
#include "util.h"
#include "uimenu.h"
Functions
GtkWidget * ui_menu_submenu_create (GtkWidget *bar, const char *label)
Create an empty submenu and add it to a menu bar.
static void on_menu_item_destroy (GtkWidget *item, gpointer unused)
Handler for the 'destroy' event of a menu item.
static void on_menu_item_activate (GtkWidget *item, gpointer action_id)
Handler for the 'activate' event of a menu item.
static void on_menu_item_toggled (GtkWidget *item, gpointer action_id)
Handler for the 'toggled' event of a menu item.
GtkWidget * ui_menu_add (GtkWidget *menu, const ui_menu_item_t *items, gint window_id)
Add menu items to menu.
Detailed Description
Native GTK3 menu handling.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Marcus Sutton logge.nosp@m.doub.nosp@m.t@gma.nosp@m.il.c.nosp@m.om
Function Documentation
on_menu_item_activate()
static void on_menu_item_activate (GtkWidget * item, gpointer action_id) static
Handler for the 'activate' event of a menu item.
Used for non-radio button items.
Parameters
[in] item menu item
[in] action_id UI action ID
Referenced by ui_menu_add().
on_menu_item_destroy()
static void on_menu_item_destroy (GtkWidget * item, gpointer unused) static
Handler for the 'destroy' event of a menu item.
Parameters
[in] item menu item
[in,out] unused extra event data (unused)
Referenced by ui_menu_add().
on_menu_item_toggled()
static void on_menu_item_toggled (GtkWidget * item, gpointer action_id) static
Handler for the 'toggled' event of a menu item.
Used for radio button items.
Parameters
[in] item menu item
[in] action_id UI action ID
Referenced by ui_menu_add().
ui_menu_add()
GtkWidget * ui_menu_add (GtkWidget * menu, const ui_menu_item_t * items, gint window_id)
Add menu items to menu.
Parameters
[in,out] menu Gtk menu
[in] items menu items to add to menu
[in] window_id window ID (PRIMARY_WINDOW or SECONDARY_WINDOW)
Returns
menu
Referenced by ui_machine_menu_bar_create(), ui_machine_menu_bar_vsid_patch(), ui_menu_add(), and ui_vsid_menu_bar_create().
ui_menu_submenu_create()
GtkWidget * ui_menu_submenu_create (GtkWidget * bar, const char * label)
Create an empty submenu and add it to a menu bar.
Parameters
[in] bar the menu bar to add the submenu to
[in] label label of the submenu to create
Returns
a reference to the new submenu
Referenced by ui_machine_menu_bar_create(), and ui_vsid_menu_bar_create().