x128: drive/ieee/via1d2031.c File Reference
via1d2031.c File Reference
#include "vice.h"
#include <stdio.h>
#include "drive.h"
#include "drivesync.h"
#include "drivetypes.h"
#include "interrupt.h"
#include "lib.h"
#include "parallel.h"
#include "rotation.h"
#include "types.h"
#include "via.h"
#include "via1d2031.h"
#include "viad.h"
Data Structures
struct drivevia1_context_s
Macros
#define parieee_is_out (via1p->v_parieee_is_out)
#define parallel_drivex_set_bus(a) (((diskunit_context_t *)(via_context->context))->func->parallel_set_bus(a))
#define parallel_drivex_set_eoi(a) (((diskunit_context_t *)(via_context->context))->func->parallel_set_eoi(a))
#define parallel_drivex_set_dav(a) (((diskunit_context_t *)(via_context->context))->func->parallel_set_dav(a))
#define parallel_drivex_set_ndac(a) (((diskunit_context_t *)(via_context->context))->func->parallel_set_ndac(a))
#define parallel_drivex_set_nrfd(a) (((diskunit_context_t *)(via_context->context))->func->parallel_set_nrfd(a))
Typedefs
typedef struct drivevia1_context_s drivevia1_context_t
Functions
void via1d2031_store (diskunit_context_t *ctxptr, uint16_t addr, uint8_t data)
uint8_t via1d2031_read (diskunit_context_t *ctxptr, uint16_t addr)
uint8_t via1d2031_peek (diskunit_context_t *ctxptr, uint16_t addr)
static void set_ca2 (via_context_t *via_context, int state)
static void set_cb2 (via_context_t *via_context, int state, int offset)
static void set_int (via_context_t *via_context, unsigned int int_num, int value, CLOCK rclk)
static void restore_int (via_context_t *via_context, unsigned int int_num, int value)
void via1d2031_set_atn (via_context_t *via_context, int state)
static void undump_pra (via_context_t *via_context, uint8_t byte)
static void store_pra (via_context_t *via_context, uint8_t byte, uint8_t oldpa_value, uint16_t addr)
static void undump_prb (via_context_t *via_context, uint8_t byte)
static void store_prb (via_context_t *via_context, uint8_t byte, uint8_t p_oldpb, uint16_t addr)
static void undump_pcr (via_context_t *via_context, uint8_t byte)
static uint8_t store_pcr (via_context_t *via_context, uint8_t byte, uint16_t addr)
static void undump_acr (via_context_t *via_context, uint8_t byte)
static void store_acr (via_context_t *via_context, uint8_t byte)
static void store_sr (via_context_t *via_context, uint8_t byte)
static void store_t2l (via_context_t *via_context, uint8_t byte)
static void reset (via_context_t *via_context)
static uint8_t read_pra (via_context_t *via_context, uint16_t addr)
static uint8_t read_prb (via_context_t *via_context)
void via1d2031_init (diskunit_context_t *ctxptr)
void via1d2031_setup_context (diskunit_context_t *ctxptr)
Macro Definition Documentation
parallel_drivex_set_bus
#define parallel_drivex_set_bus (a) (((diskunit_context_t *)(via_context->context))->func->parallel_set_bus(a))
parallel_drivex_set_dav
#define parallel_drivex_set_dav (a) (((diskunit_context_t *)(via_context->context))->func->parallel_set_dav(a))
parallel_drivex_set_eoi
#define parallel_drivex_set_eoi (a) (((diskunit_context_t *)(via_context->context))->func->parallel_set_eoi(a))
parallel_drivex_set_ndac
#define parallel_drivex_set_ndac (a) (((diskunit_context_t *)(via_context->context))->func->parallel_set_ndac(a))
parallel_drivex_set_nrfd
#define parallel_drivex_set_nrfd (a) (((diskunit_context_t *)(via_context->context))->func->parallel_set_nrfd(a))
parieee_is_out
#define parieee_is_out (via1p->v_parieee_is_out)
Typedef Documentation
drivevia1_context_t
typedef struct drivevia1_context_s drivevia1_context_t
Function Documentation
read_pra()
static uint8_t read_pra (via_context_t * via_context, uint16_t addr) static
< Data direction register for port A
< Port A
< Data direction register for port A
Referenced by via1d2031_setup_context().
read_prb()
static uint8_t read_prb (via_context_t * via_context) static
< Data direction register for port B
< Port B
< Data direction register for port B
Referenced by via1d2031_setup_context().
reset()
static void reset (via_context_t * via_context) static
Referenced by via1d2031_setup_context().
restore_int()
static void restore_int (via_context_t * via_context, unsigned int int_num, int value) static
Referenced by via1d2031_setup_context().
set_ca2()
static void set_ca2 (via_context_t * via_context, int state) static
Referenced by via1d2031_setup_context().
set_cb2()
static void set_cb2 (via_context_t * via_context, int state, int offset) static
Referenced by via1d2031_setup_context().
set_int()
static void set_int (via_context_t * via_context, unsigned int int_num, int value, CLOCK rclk) static
Referenced by via1d2031_setup_context().
store_acr()
static void store_acr (via_context_t * via_context, uint8_t byte) static
Referenced by via1d2031_setup_context().
store_pcr()
static uint8_t store_pcr (via_context_t * via_context, uint8_t byte, uint16_t addr) static
Referenced by via1d2031_setup_context().
store_pra()
static void store_pra (via_context_t * via_context, uint8_t byte, uint8_t oldpa_value, uint16_t addr) static
Referenced by via1d2031_setup_context().
store_prb()
static void store_prb (via_context_t * via_context, uint8_t byte, uint8_t p_oldpb, uint16_t addr) static
Referenced by via1d2031_setup_context().
store_sr()
static void store_sr (via_context_t * via_context, uint8_t byte) static
Referenced by via1d2031_setup_context().
store_t2l()
static void store_t2l (via_context_t * via_context, uint8_t byte) static
Referenced by via1d2031_setup_context().
undump_acr()
static void undump_acr (via_context_t * via_context, uint8_t byte) static
Referenced by via1d2031_setup_context().
undump_pcr()
static void undump_pcr (via_context_t * via_context, uint8_t byte) static
Referenced by via1d2031_setup_context().
undump_pra()
static void undump_pra (via_context_t * via_context, uint8_t byte) static
Referenced by via1d2031_setup_context().
undump_prb()
static void undump_prb (via_context_t * via_context, uint8_t byte) static
Referenced by via1d2031_setup_context().
via1d2031_init()
void via1d2031_init (diskunit_context_t * ctxptr)
Referenced by ieee_drive_init().
via1d2031_peek()
uint8_t via1d2031_peek (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by memieee_init().
via1d2031_read()
uint8_t via1d2031_read (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by memieee_init().
via1d2031_set_atn()
void via1d2031_set_atn (via_context_t * via_context, int state)
Referenced by ieee_drive_parallel_set_atn().
via1d2031_setup_context()
void via1d2031_setup_context (diskunit_context_t * ctxptr)
Referenced by ieee_drive_setup_context().
via1d2031_store()
void via1d2031_store (diskunit_context_t * ctxptr, uint16_t addr, uint8_t data)
Referenced by memieee_init().