vsid: arch/gtk3/widgets/machinemodelwidget.c File Reference
machinemodelwidget.c File Reference
Machine model selection widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "machine.h"
#include "resources.h"
#include "machinemodelwidget.h"
Functions
static void on_model_toggled (GtkWidget *widget, gpointer user_data)
Handler for 'toggled' events of the radio buttons in the widget.
void machine_model_widget_getter (int(*f)(void))
Set machine-specific function to get the model.
void machine_model_widget_setter (void(*f)(int model))
Set machine-specific function to set the model.
void machine_model_widget_set_models (const char **list)
Set machine-specific list of supported models.
GtkWidget * machine_model_widget_create (void)
Create machine model widget.
void machine_model_widget_update (GtkWidget *widget, bool force_callback)
Update the machine model widget.
void machine_model_widget_connect_signals (GtkWidget *widget)
Connect signal handlers.
void machine_model_widget_set_callback (void(*callback)(int))
Set function to call when the model ID changes.
Variables
static int(* model_get)(void) = NULL
Machine-specific model get function.
static void(* model_set)(int) = NULL
Machine-specific model set function.
static const char ** model_list = NULL
Machine-specific List of supported models.
static void(* user_callback)(int) = NULL
Extra callback.
Detailed Description
Machine model selection widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
machine_model_widget_connect_signals()
void machine_model_widget_connect_signals (GtkWidget * widget)
Connect signal handlers.
Parameters
[in,out] widget machine model widget
Referenced by settings_model_widget_create().
machine_model_widget_create()
GtkWidget * machine_model_widget_create (void)
Create machine model widget.
Radio buttons for the models start at row 2 in the grid, while a special 'Unknown' radio button is added at row 1, to allow displaying that no valid model could be found for the current settings.
Returns
GtkGrid
Referenced by settings_model_widget_create().
machine_model_widget_getter()
void machine_model_widget_getter (int(*)(void) f)
Set machine-specific function to get the model.
Parameters
[in] f model getter function
machine_model_widget_set_callback()
void machine_model_widget_set_callback (void(*)(int) callback)
Set function to call when the model ID changes.
Parameters
[in] callback function to call on model change
Referenced by settings_model_widget_create().
machine_model_widget_set_models()
void machine_model_widget_set_models (const char ** list)
Set machine-specific list of supported models.
Parameters
[in] list list of models, NULL-terminatd
machine_model_widget_setter()
void machine_model_widget_setter (void(*)(int model) f)
Set machine-specific function to set the model.
Parameters
[in] f model setter function
machine_model_widget_update()
void machine_model_widget_update (GtkWidget * widget, bool force_callback)
Update the machine model widget.
Parameters
[in,out] widget machine model widget
Referenced by c64dtv_hummer_adc_callback(), cbm2_memory_size_callback(), cbm2_switches_callback(), cbm2_video_callback(), cbm5x0_video_callback(), cia_model_callback(), dtv_revision_callback(), dtv_video_callback(), iec_callback(), kernal_revision_callback(), machine_model_widget_create(), on_c64_glue_toggled(), pet_blank_callback(), pet_crtc_callback(), pet_io_callback(), pet_keyboard_type_callback(), pet_ram9_callback(), pet_ram_size_callback(), pet_rama_callback(), pet_screen2001_callback(), pet_video_size_callback(), plus4_acia_widget_callback(), plus4_mem_hack_callback(), plus4_mem_size_callback(), plus4_video_callback(), power_frequency_callback(), sid_model_callback(), superpet_enable_callback(), v364_speech_widget_callback(), vdc_ram_callback(), vdc_revision_callback(), vic20_video_callback(), and video_model_callback().
on_model_toggled()
static void on_model_toggled (GtkWidget * widget, gpointer user_data) static
Handler for 'toggled' events of the radio buttons in the widget.
Parameters
[in] widget radio button triggering the event
[in] user_data model ID (int)
Referenced by machine_model_widget_connect_signals().
Variable Documentation
model_get
int(* model_get) (void) (void) = NULL static
Machine-specific model get function.
Referenced by machine_model_widget_getter(), and machine_model_widget_update().
model_list
const char** model_list = NULL static
Machine-specific List of supported models.
Referenced by machine_model_widget_create(), and machine_model_widget_set_models().
model_set
void(* model_set) (int) (int) = NULL static
Machine-specific model set function.
Referenced by machine_model_widget_setter(), and on_model_toggled().
user_callback
void(* user_callback) (int) (int) = NULL static
Extra callback.
This callback is called with the new model ID when the model changes
Referenced by machine_model_widget_set_callback(), machine_model_widget_update(), and on_model_toggled().