vsid: vicii/vicii-mem.h File Reference
vicii-mem.h File Reference
#include "types.h"
Functions
void vicii_store (uint16_t addr, uint8_t value)
Store a value in a VIC-II register.
uint8_t vicii_read (uint16_t addr)
Read a value from a VIC-II register.
uint8_t vicii_peek (uint16_t addr)
void vicii_mem_vbank_store (uint16_t addr, uint8_t value)
Encapsulate inlined function for other modules.
void vicii_mem_vbank_39xx_store (uint16_t addr, uint8_t value)
As ‘store_vbank()’, but for the $3900...$39FF address range.
void vicii_mem_vbank_3fxx_store (uint16_t addr, uint8_t value)
As ‘store_vbank()’, but for the $3F00...$3FFF address range.
void vicii_palette_store (uint16_t addr, uint8_t value)
DTV Palette registers at $d2xx.
uint8_t vicii_palette_read (uint16_t addr)
int vicii_extended_regs (void)
void viciidtv_update_colorram (void)
void vicii_init_colorram (uint8_t *colorram)
Function Documentation
vicii_extended_regs()
int vicii_extended_regs (void)
vicii_init_colorram()
void vicii_init_colorram (uint8_t * colorram)
Referenced by mem_powerup().
vicii_mem_vbank_39xx_store()
void vicii_mem_vbank_39xx_store (uint16_t addr, uint8_t value)
As ‘store_vbank()’, but for the $3900...$39FF address range.
Referenced by check_256k_ram_write(), mem_initialize_memory(), plus60k_init_config(), and vicii_mem_vbank_39xx_store_wrapper().
vicii_mem_vbank_3fxx_store()
void vicii_mem_vbank_3fxx_store (uint16_t addr, uint8_t value)
As ‘store_vbank()’, but for the $3F00...$3FFF address range.
Referenced by check_256k_ram_write(), mem_initialize_memory(), plus60k_init_config(), ram_hi_store(), and vicii_mem_vbank_3fxx_store_wrapper().
vicii_mem_vbank_store()
void vicii_mem_vbank_store (uint16_t addr, uint8_t value)
Encapsulate inlined function for other modules.
Referenced by check_256k_ram_write(), mem_initialize_memory(), plus60k_init_config(), vicii_mem_vbank_store_wrapper(), zero_store(), and zero_store_dma().
vicii_palette_read()
uint8_t vicii_palette_read (uint16_t addr)
vicii_palette_store()
void vicii_palette_store (uint16_t addr, uint8_t value)
DTV Palette registers at $d2xx.
vicii_peek()
uint8_t vicii_peek (uint16_t addr)
Referenced by mem_get_screen_parameter(), and peek_bank_io().
vicii_read()
uint8_t vicii_read (uint16_t addr)
Read a value from a VIC-II register.
Referenced by c64meminit(), and read_bank_io().
vicii_store()
void vicii_store (uint16_t addr, uint8_t value)
Store a value in a VIC-II register.
Referenced by c64meminit(), store_bank_io(), vicii_reset_registers(), and vicii_snapshot_read_module().
viciidtv_update_colorram()
void viciidtv_update_colorram (void)
Referenced by d036_store(), d037_store(), d045_store(), vicii_update_memory_ptrs(), and vicii_update_video_mode().