vsid: c64/c64memlimit.c File Reference
c64memlimit.c File Reference
#include "vice.h"
#include "c64memlimit.h"
#include "c64mem.h"
Macros
#define NUM_CONFIGS 32
#define NUM_SEGMENTS 7
Functions
void mem_limit_init (void)
void mem_limit_plus60k_init (void)
void mem_limit_256k_init (void)
void mem_limit_max_init (void)
Variables
static const int mstart [7]
static const int mend [7]
static const uint32_t limit_tab [7][32]
Macro Definition Documentation
NUM_CONFIGS
#define NUM_CONFIGS 32
NUM_SEGMENTS
#define NUM_SEGMENTS 7
Function Documentation
mem_limit_256k_init()
void mem_limit_256k_init (void)
Referenced by c64_256k_init_config(), and plus256k_init_config().
mem_limit_init()
void mem_limit_init (void)
Referenced by mem_initialize_memory().
mem_limit_max_init()
void mem_limit_max_init (void)
Referenced by mem_initialize_memory().
mem_limit_plus60k_init()
void mem_limit_plus60k_init (void)
Referenced by plus60k_init_config().
Variable Documentation
limit_tab
const uint32_t limit_tab[7][32] static
Initial value:
= {
    { 0x0002fffd, 0x0002cffd, 0x0002cffd, 0x00029ffd, 0x0002fffd, 0x0002cffd, 0x0002cffd, 0x00029ffd,
      0x0002fffd, 0x0002cffd, 0x00029ffd, 0x00027ffd, 0x0002fffd, 0x0002cffd, 0x00029ffd, 0x00027ffd,
      0x00020ffd, 0x00020ffd, 0x00020ffd, 0x00020ffd, 0x00020ffd, 0x00020ffd, 0x00020ffd, 0x00020ffd,
      0x0002fffd, 0x0002cffd, 0x00029ffd, 0x00027ffd, 0x0002fffd, 0x0002cffd, 0x00029ffd, 0x00027ffd },
    { 0x0002fffd, 0x0002cffd, 0x0002cffd, 0x00029ffd, 0x0002fffd, 0x0002cffd, 0x0002cffd, 0x00029ffd,
      0x0002fffd, 0x0002cffd, 0x00029ffd, 0x00027ffd, 0x0002fffd, 0x0002cffd, 0x00029ffd, 0x00027ffd,
               0,          0,          0,          0,          0,          0,          0,          0,
      0x0002fffd, 0x0002cffd, 0x00029ffd, 0x00027ffd, 0x0002fffd, 0x0002cffd, 0x00029ffd, 0x00027ffd },
    { 0x0002fffd, 0x0002cffd, 0x0002cffd, 0x00029ffd, 0x0002fffd, 0x0002cffd, 0x0002cffd, 0x00029ffd,
      0x0002fffd, 0x0002cffd, 0x00029ffd,          0, 0x0002fffd, 0x0002cffd, 0x00029ffd,          0,
               0,          0,          0,          0,          0,          0,          0,          0,
      0x0002fffd, 0x0002cffd, 0x00029ffd,          0, 0x0002fffd, 0x0002cffd, 0x00029ffd,          0 },
    { 0x0002fffd, 0x0002cffd, 0x0002cffd, 0xa000bffd, 0x0002fffd, 0x0002cffd, 0x0002cffd, 0xa000bffd,
      0x0002fffd, 0x0002cffd,          0,          0, 0x0002fffd, 0x0002cffd,          0,          0,
               0,          0,          0,          0,          0,          0,          0,          0,
      0x0002fffd, 0x0002cffd,          0,          0, 0x0002fffd, 0x0002cffd,          0,          0 },
    { 0x0002fffd, 0x0002cffd, 0x0002cffd, 0xc000cffd, 0x0002fffd, 0x0002cffd, 0x0002cffd, 0xc000cffd,
      0x0002fffd, 0x0002cffd, 0xc000cffd, 0xc000cffd, 0x0002fffd, 0x0002cffd, 0xc000cffd, 0xc000cffd,
               0,          0,          0,          0,          0,          0,          0,          0,
      0x0002fffd, 0x0002cffd, 0xc000cffd, 0xc000cffd, 0x0002fffd, 0x0002cffd, 0xc000cffd, 0xc000cffd },
    { 0x0002fffd, 0xd000dffd, 0xd000dffd, 0xd000dffd, 0x0002fffd,          0,          0,          0,
      0x0002fffd, 0xd000dffd, 0xd000dffd, 0xd000dffd, 0x0002fffd,          0,          0,          0,
               0,          0,          0,          0,          0,          0,          0,          0,
      0x0002fffd, 0xd000dffd, 0xd000dffd, 0xd000dffd, 0x0002fffd,          0,          0,          0 },
    { 0x0002fffd, 0xe000fffd, 0xe000fffd, 0xe000fffd, 0x0002fffd, 0xe000fffd, 0xe000fffd, 0xe000fffd,
      0x0002fffd, 0xe000fffd, 0xe000fffd, 0xe000fffd, 0x0002fffd, 0xe000fffd, 0xe000fffd, 0xe000fffd,
               0,          0,          0,          0,          0,          0,          0,          0,
      0x0002fffd, 0xe000fffd, 0xe000fffd, 0xe000fffd, 0x0002fffd, 0xe000fffd, 0xe000fffd, 0xe000fffd } }
Referenced by mem_limit_init().
mend
const int mend[7] static
Initial value:
= {
    0x0f, 0x7f, 0x9f,
    0xbf, 0xcf, 0xdf, 0xff
}
Referenced by mem_limit_256k_init(), mem_limit_init(), mem_limit_max_init(), and mem_limit_plus60k_init().
mstart
const int mstart[7] static
Initial value:
= {
    0x00, 0x10, 0x80,
    0xa0, 0xc0, 0xd0, 0xe0
}
Referenced by mem_limit_256k_init(), mem_limit_init(), mem_limit_max_init(), and mem_limit_plus60k_init().