vsid: vsync.c File Reference
vsync.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include "archdep.h"
#include "cmdline.h"
#include "debug.h"
#include "joystick.h"
#include "kbdbuf.h"
#include "lib.h"
#include "log.h"
#include "maincpu.h"
#include "machine.h"
#include "monitor_network.h"
#include "monitor_binary.h"
#include "network.h"
#include "resources.h"
#include "sound.h"
#include "types.h"
#include "videoarch.h"
#include "vsync.h"
#include "vsyncapi.h"
#include "ui.h"
Data Structures
struct callback_queue_s
Macros
#define METRIC_LOCK()
#define METRIC_UNLOCK()
#define MAX_RENDER_SKIP_MS (1000 / 10)
#define MEASUREMENT_SMOOTH_FACTOR 0.99
#define MEASUREMENT_FRAME_WINDOW 250
Typedefs
typedef struct callback_queue_s callback_queue_t
Functions
void vsync_on_vsync_do (vsync_callback_func_t callback_func, void *callback_param)
Call callback_func(callback_param) once at vsync time (or machine reset)
static void execute_vsync_callbacks (void)
Keep executing on_vsync_do callbacks until none are scheduled.
static int set_timer_speed (int speed)
Initialize vsync timers and set relative speed of emulation in percent.
static int set_relative_speed (int val, void *param)
void vsync_set_warp_mode (int val)
int vsync_get_warp_mode (void)
static int set_initial_warp_mode_resource (int val, void *param)
int vsync_resources_init (void)
static int set_initial_warp_mode_cmdline (const char *param, void *extra_param)
int vsync_cmdline_options_init (void)
void vsync_set_machine_parameter (double refresh, long cycles)
double vsync_get_refresh_frequency (void)
void vsync_init (void(*hook)(void))
void vsync_shutdown (void)
void vsync_suspend_speed_eval (void)
void vsync_reset_hook (void)
void vsyncarch_get_metrics (double *cpu_percent, double *emulated_fps, int *is_warp_enabled)
current performance metrics
static void reset_performance_metrics (tick_t frame_tick)
static void update_performance_metrics (tick_t frame_tick)
void vsync_do_end_of_line (void)
bool vsync_should_skip_frame (struct video_canvas_s *canvas)
void vsync_do_vsync (struct video_canvas_s *c)
This is called at the end of each screen frame.
Variables
static double vsync_metric_cpu_percent
Port me...
static double vsync_metric_emulated_fps
static callback_queue_t callback_queues [2]
static callback_queue_t * callback_queue = callback_queues
static int callback_queue_index
static int relative_speed
Relative speed of the emulation (%) (negative values target FPS rather than cpu %)
static int warp_enabled
"Warp mode".
static int initial_warp_mode_resource
"InitialWarpMode" resource controlling whether warp should be enabled from launch.
static int initial_warp_mode_cmdline = -1
warp mode cmdline arg controlling whether warp should be enabled from launch.
static tick_t warp_render_tick_interval
When the next frame should be rendered, not skipped, during warp.
static volatile int update_thread_priority = 1
Triggers the vice thread to update its priorty.
static const resource_int_t resources_int []
Vsync-related resources.
static const cmdline_option_t cmdline_options []
Vsync-related command-line options.
static double refresh_frequency
Number of frames per second on the real machine.
static long cycles_per_sec
Number of clock cycles per seconds on the real machine.
static void(* vsync_hook)(void)
Function to call at the end of every screen frame.
static double ticks_per_frame
static guarantees zero values.
static double cycles_per_frame
static double emulated_clk_per_second
static tick_t last_sync_emulated_tick
static tick_t last_sync_tick
static CLOCK last_sync_clk
static tick_t sync_target_tick
static int timer_speed = 0
static bool sync_reset = true
static bool metrics_reset = false
static int measurement_count
static int next_measurement_index
static tick_t last_tick
For knowing the relevant timespan.
static tick_t tick_deltas [250]
static uint64_t cumulative_tick_delta
static CLOCK last_clock
For measuring emulator cpu cycles per second.
static CLOCK clock_deltas [250]
static uint64_t cumulative_clock_delta
Macro Definition Documentation
MAX_RENDER_SKIP_MS
#define MAX_RENDER_SKIP_MS (1000 / 10)
MEASUREMENT_FRAME_WINDOW
#define MEASUREMENT_FRAME_WINDOW 250
MEASUREMENT_SMOOTH_FACTOR
#define MEASUREMENT_SMOOTH_FACTOR 0.99
METRIC_LOCK
#define METRIC_LOCK ()
METRIC_UNLOCK
#define METRIC_UNLOCK ()
Typedef Documentation
callback_queue_t
typedef struct callback_queue_s callback_queue_t
Function Documentation
execute_vsync_callbacks()
static void execute_vsync_callbacks (void) static
Keep executing on_vsync_do callbacks until none are scheduled.
Referenced by vsync_do_vsync(), and vsync_reset_hook().
reset_performance_metrics()
static void reset_performance_metrics (tick_t frame_tick) static
Referenced by update_performance_metrics().
set_initial_warp_mode_cmdline()
static int set_initial_warp_mode_cmdline (const char * param, void * extra_param) static
set_initial_warp_mode_resource()
static int set_initial_warp_mode_resource (int val, void * param) static
set_relative_speed()
static int set_relative_speed (int val, void * param) static
set_timer_speed()
static int set_timer_speed (int speed) static
Initialize vsync timers and set relative speed of emulation in percent.
Referenced by set_relative_speed(), and vsync_set_machine_parameter().
update_performance_metrics()
static void update_performance_metrics (tick_t frame_tick) static
Referenced by vsync_do_vsync().
vsync_cmdline_options_init()
int vsync_cmdline_options_init (void)
Referenced by init_cmdline_options().
vsync_do_end_of_line()
void vsync_do_end_of_line (void)
Todo:
BSD thread prio stuff
Referenced by vicii_raster_draw_alarm_handler().
vsync_do_vsync()
void vsync_do_vsync (struct video_canvas_s * c)
This is called at the end of each screen frame.
Referenced by vicii_raster_draw_alarm_handler().
vsync_get_refresh_frequency()
double vsync_get_refresh_frequency (void)
Referenced by network_test_delay().
vsync_get_warp_mode()
int vsync_get_warp_mode (void)
Referenced by actions_speed_setup_ui(), create_warp_checkbox(), enable_warp_if_requested(), init_drive_emulation_state(), restore_drive_emulation_state(), speed_menu_popup_create(), ui_create_main_window(), and warp_mode_toggle_action().
vsync_init()
void vsync_init (void(*)(void) hook)
Referenced by machine_specific_init().
vsync_on_vsync_do()
void vsync_on_vsync_do (vsync_callback_func_t callback_func, void * callback_param)
Call callback_func(callback_param) once at vsync time (or machine reset)
Referenced by on_save_screenshot_filename(), pause_loop(), screenshot_ui_auto_screenshot(), set_border_mode(), and ui_pause_enable().
vsync_reset_hook()
void vsync_reset_hook (void)
Referenced by machine_reset().
vsync_resources_init()
int vsync_resources_init (void)
Referenced by init_resources().
vsync_set_machine_parameter()
void vsync_set_machine_parameter (double refresh, long cycles)
Referenced by machine_change_timing(), and machine_specific_init().
vsync_set_warp_mode()
void vsync_set_warp_mode (int val)
Referenced by set_warp_mode(), vsync_init(), warp_callback(), and warp_mode_toggle_action().
vsync_should_skip_frame()
bool vsync_should_skip_frame (struct video_canvas_s * canvas)
Referenced by raster_canvas_handle_end_of_frame().
vsync_shutdown()
void vsync_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
vsync_suspend_speed_eval()
void vsync_suspend_speed_eval (void)
Referenced by set_timer_speed(), vsync_init(), vsync_reset_hook(), and vsync_set_warp_mode().
vsyncarch_get_metrics()
void vsyncarch_get_metrics (double * cpu_percent, double * emulated_fps, int * is_warp_enabled)
current performance metrics
Referenced by statusbar_speed_widget_update().
Variable Documentation
callback_queue
callback_queue_t* callback_queue = callback_queues static
Referenced by execute_vsync_callbacks(), and vsync_on_vsync_do().
callback_queue_index
int callback_queue_index static
Referenced by execute_vsync_callbacks().
callback_queues
callback_queue_t callback_queues[2] static
Referenced by execute_vsync_callbacks(), and vsync_shutdown().
clock_deltas
CLOCK clock_deltas[250] static
Referenced by update_performance_metrics().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-speed", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Speed", NULL,
      "<percent or negative fps>", "Limit emulation speed to specified value" },
    { "-warp", CALL_FUNCTION,  0 ,
      set_initial_warp_mode_cmdline, ((void *)(intptr_t)( 1 )), NULL, NULL,
      NULL, "Initially enable warp mode" },
    { "+warp", CALL_FUNCTION,  0 ,
      set_initial_warp_mode_cmdline, ((void *)(intptr_t)( 0 )), NULL, NULL,
      NULL, "Do not initially enable warp mode (default)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Vsync-related command-line options.
Referenced by vsync_cmdline_options_init().
cumulative_clock_delta
uint64_t cumulative_clock_delta static
Referenced by reset_performance_metrics(), and update_performance_metrics().
cumulative_tick_delta
uint64_t cumulative_tick_delta static
Referenced by reset_performance_metrics(), and update_performance_metrics().
cycles_per_frame
double cycles_per_frame static
Referenced by vsync_set_machine_parameter().
cycles_per_sec
long cycles_per_sec static
Number of clock cycles per seconds on the real machine.
Referenced by set_timer_speed(), update_performance_metrics(), and vsync_set_machine_parameter().
emulated_clk_per_second
double emulated_clk_per_second static
Referenced by set_timer_speed(), and vsync_do_end_of_line().
initial_warp_mode_cmdline
int initial_warp_mode_cmdline = -1 static
warp mode cmdline arg controlling whether warp should be enabled from launch.
Overrides InitialWarpMode resource.
Referenced by set_initial_warp_mode_cmdline(), and vsync_init().
initial_warp_mode_resource
int initial_warp_mode_resource static
"InitialWarpMode" resource controlling whether warp should be enabled from launch.
Referenced by set_initial_warp_mode_resource(), and vsync_init().
last_clock
CLOCK last_clock static
For measuring emulator cpu cycles per second.
Referenced by reset_performance_metrics(), and update_performance_metrics().
last_sync_clk
CLOCK last_sync_clk static
Referenced by vsync_do_end_of_line().
last_sync_emulated_tick
tick_t last_sync_emulated_tick static
Referenced by vsync_do_end_of_line().
last_sync_tick
tick_t last_sync_tick static
Referenced by vsync_do_end_of_line().
last_tick
tick_t last_tick static
For knowing the relevant timespan.
Referenced by reset_performance_metrics(), and update_performance_metrics().
measurement_count
int measurement_count static
Referenced by reset_performance_metrics(), and update_performance_metrics().
metrics_reset
bool metrics_reset = false static
Referenced by update_performance_metrics(), and vsync_do_end_of_line().
next_measurement_index
int next_measurement_index static
Referenced by reset_performance_metrics(), and update_performance_metrics().
refresh_frequency
double refresh_frequency static
Number of frames per second on the real machine.
Referenced by reset_performance_metrics(), set_timer_speed(), vsync_get_refresh_frequency(), and vsync_set_machine_parameter().
relative_speed
int relative_speed static
Relative speed of the emulation (%) (negative values target FPS rather than cpu %)
Referenced by set_relative_speed(), and vsync_set_machine_parameter().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "Speed", 100, RES_EVENT_SAME, NULL,
      &relative_speed, set_relative_speed, NULL },
    { "InitialWarpMode", 0, RES_EVENT_STRICT, (resource_value_t)0,
      &initial_warp_mode_resource, set_initial_warp_mode_resource, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Vsync-related resources.
Referenced by vsync_resources_init().
sync_reset
bool sync_reset = true static
Referenced by vsync_do_end_of_line(), and vsync_suspend_speed_eval().
sync_target_tick
tick_t sync_target_tick static
Referenced by vsync_do_end_of_line().
tick_deltas
tick_t tick_deltas[250] static
Referenced by update_performance_metrics().
ticks_per_frame
double ticks_per_frame static
static guarantees zero values.
Referenced by set_timer_speed(), sound_init(), sound_set_machine_parameter(), and vsync_do_vsync().
timer_speed
int timer_speed = 0 static
Referenced by reset_performance_metrics(), and set_timer_speed().
update_thread_priority
volatile int update_thread_priority = 1 static
Triggers the vice thread to update its priorty.
Referenced by vsync_do_end_of_line(), and vsync_set_warp_mode().
vsync_hook
void(* vsync_hook) (void) (void) static
Function to call at the end of every screen frame.
Referenced by vsync_do_vsync(), and vsync_init().
vsync_metric_cpu_percent
double vsync_metric_cpu_percent static
Port me...
public metrics, updated every vsync
Referenced by reset_performance_metrics(), statusbar_speed_widget_update(), update_performance_metrics(), and vsyncarch_get_metrics().
vsync_metric_emulated_fps
double vsync_metric_emulated_fps static
Referenced by reset_performance_metrics(), statusbar_speed_widget_update(), update_performance_metrics(), and vsyncarch_get_metrics().
warp_enabled
int warp_enabled static
"Warp mode".
If nonzero, attempt to run as fast as possible.
Referenced by vsync_do_end_of_line(), vsync_get_warp_mode(), vsync_set_warp_mode(), vsync_should_skip_frame(), and vsyncarch_get_metrics().
warp_render_tick_interval
tick_t warp_render_tick_interval static
When the next frame should be rendered, not skipped, during warp.
Referenced by vsync_init(), and vsync_should_skip_frame().