x128: fileio/fileio.c File Reference
fileio.c File Reference
#include "vice.h"
#include <stdio.h>
#include "cbmfile.h"
#include "fileio.h"
#include "lib.h"
#include "p00.h"
#include "types.h"
#include "util.h"
Macros
#define DBG(x)
Functions
fileio_info_t * fileio_open (const char *file_name, const char *path, unsigned int format, unsigned int command, unsigned int type, int *reclenp)
void fileio_close (fileio_info_t *info)
unsigned int fileio_read (fileio_info_t *info, uint8_t *buf, unsigned int len)
unsigned int fileio_write (fileio_info_t *info, uint8_t *buf, unsigned int len)
unsigned int fileio_get_bytes_left (fileio_info_t *info)
unsigned int fileio_seek (fileio_info_t *info, off_t offset, int whence)
unsigned int fileio_tell (fileio_info_t *info)
unsigned int fileio_ferror (fileio_info_t *info)
unsigned int fileio_rename (const char *src_name, const char *dest_name, const char *path, unsigned int format)
unsigned int fileio_scratch (const char *file_name, const char *path, unsigned int format)
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
fileio_close()
void fileio_close (fileio_info_t * info)
Referenced by autostart_prg(), command_directory_get(), fsdevice_close(), and read_cmd().
fileio_ferror()
unsigned int fileio_ferror (fileio_info_t * info)
Referenced by command_read(), and relative_read().
fileio_get_bytes_left()
unsigned int fileio_get_bytes_left (fileio_info_t * info)
Referenced by fsdevice_relative_switch_record(), and load_prg().
fileio_open()
fileio_info_t * fileio_open (const char * file_name, const char * path, unsigned int format, unsigned int command, unsigned int type, int * reclenp)
Referenced by autostart_prg(), command_directory_get(), fsdevice_open_file(), and read_cmd().
fileio_read()
unsigned int fileio_read (fileio_info_t * info, uint8_t * buf, unsigned int len)
Referenced by command_read(), fsdevice_relative_switch_record(), load_prg(), and relative_read().
fileio_rename()
unsigned int fileio_rename (const char * src_name, const char * dest_name, const char * path, unsigned int format)
Referenced by fsdevice_flush_rename().
fileio_scratch()
unsigned int fileio_scratch (const char * file_name, const char * path, unsigned int format)
Referenced by fsdevice_flush_scratch().
fileio_seek()
unsigned int fileio_seek (fileio_info_t * info, off_t offset, int whence)
Referenced by fsdevice_relative_pad_record(), fsdevice_relative_switch_record(), fsdevice_relfile_extend_if_needed(), and fsdevice_write().
fileio_tell()
unsigned int fileio_tell (fileio_info_t * info)
Referenced by fsdevice_relfile_extend_if_needed().
fileio_write()
unsigned int fileio_write (fileio_info_t * info, uint8_t * buf, unsigned int len)
Referenced by fsdevice_relative_pad_record(), fsdevice_relfile_extend_if_needed(), fsdevice_write(), and read_cmd().