vsid: c64/c64rom.h File Reference
c64rom.h File Reference
Macros
#define C64_BASIC_NAME "basic-901226-01.bin"
filenames used for the BASIC ROMs
#define C64_KERNAL_UNKNOWN -1
unique IDs to refer to a kernal, used for the KernalRev resource
#define C64_KERNAL_JAP 0
906145-02
#define C64_KERNAL_REV1 1
901227-01
#define C64_KERNAL_REV2 2
901227-02
#define C64_KERNAL_REV3 3
901227-03
#define C64_KERNAL_GS64 39
390852-01
#define C64_KERNAL_SX64 67
251104-04
#define C64_KERNAL_4064 100
901246-01
#define C64_KERNAL_REV3SWE 13
FIXME.
#define C64_KERNAL_NONE -2
used for the MAX machine, which has no kernal
#define C64_KERNAL_JAP_NAME "kernal-906145-02.bin"
filenames used for the kernal ROMs
#define C64_KERNAL_REV1_NAME "kernal-901227-01.bin"
#define C64_KERNAL_REV2_NAME "kernal-901227-02.bin"
#define C64_KERNAL_REV3_NAME "kernal-901227-03.bin"
#define C64_KERNAL_GS64_NAME "kernal-390852-01.bin"
#define C64_KERNAL_SX64_NAME "kernal-251104-04.bin"
#define C64_KERNAL_4064_NAME "kernal-901246-01.bin"
#define C64_KERNAL_NONE_NAME "kernal-none.bin"
dummy, used for the MAX machine, which has no kernal
#define C64_CHARGEN_NAME "chargen-901225-01.bin"
filenames used for the chargen ROMs
#define C64_CHARGEN_JAP_NAME "chargen-906143-02.bin"
#define C64_BASIC_CHECKSUM 15702
simple additive checksum
#define C64_KERNAL_CHECKSUM_JAP 53635
906145-02
#define C64_KERNAL_CHECKSUM_R01 54525
901227-01
#define C64_KERNAL_CHECKSUM_R02 50955
901227-02
#define C64_KERNAL_CHECKSUM_R03 50954
901227-03
#define C64_KERNAL_CHECKSUM_GS64 46538
390852-01 (gs)
#define C64_KERNAL_CHECKSUM_R43 50955
251104-04 (sx)
#define C64_KERNAL_CHECKSUM_R64 49680
901246-01 (educator)
#define C64_KERNAL_CHECKSUM_R03swe 50633
FIXME.
#define C64_KERNAL_ID_JAP 0x00
the value located at 0xff80
#define C64_KERNAL_ID_R01 0xaa
901227-01
#define C64_KERNAL_ID_R02 0x00
901227-02
#define C64_KERNAL_ID_R03 0x03
901227-03
#define C64_KERNAL_ID_GS64 0x03
390852-01 (gs)
#define C64_KERNAL_ID_R43 0x43
251104-04 (sx)
#define C64_KERNAL_ID_R64 0x64
901246-01 (educator)
#define C64_KERNAL_ID_R03swe 0x03
FIXME.
#define C64_BASIC_HASH "79015323128650c742a3694c9429aa91f355905e"
SHA1 hashes.
#define C64_KERNAL_HASH_JAP "4ff0f11e80f4b57430d8f0c3799ed0f0e0f4565d"
906145-02
#define C64_KERNAL_HASH_R01 "87cc04d61fc748b82df09856847bb5c2754a2033"
901227-01
#define C64_KERNAL_HASH_R02 "0e2e4ee3f2d41f00bed72f9ab588b83e306fdb13"
901227-02
#define C64_KERNAL_HASH_R03 "1d503e56df85a62fee696e7618dc5b4e781df1bb"
901227-03
#define C64_KERNAL_HASH_GS64 "3ad6cc1837c679a11f551ad1cf1a32dd84ace719"
390852-01 (gs)
#define C64_KERNAL_HASH_R43 "aa136e91ecf3c5ac64f696b3dbcbfc5ba0871c98"
251104-04 (sx)
#define C64_KERNAL_HASH_R64 "6c4fa9465f6091b174df27dfe679499df447503c"
901246-01 (educator)
Functions
int c64rom_load_kernal (const char *rom_name, uint8_t *new_kernal)
int c64rom_load_basic (const char *rom_name)
int c64rom_load_chargen (const char *rom_name)
int c64rom_get_kernal_chksum_id (uint16_t *sumout, int *idout, char *sha1hash)
int c64rom_print_kernal_info (void)
print ROM ID, checksum, sha1 hash.
int c64rom_print_basic_info (void)
int c64rom_isloaded (void)
Variables
int c64rom_cartkernal_active
Macro Definition Documentation
C64_BASIC_CHECKSUM
#define C64_BASIC_CHECKSUM 15702
simple additive checksum
C64_BASIC_HASH
#define C64_BASIC_HASH "79015323128650c742a3694c9429aa91f355905e"
SHA1 hashes.
C64_BASIC_NAME
#define C64_BASIC_NAME "basic-901226-01.bin"
filenames used for the BASIC ROMs
C64_CHARGEN_JAP_NAME
#define C64_CHARGEN_JAP_NAME "chargen-906143-02.bin"
C64_CHARGEN_NAME
#define C64_CHARGEN_NAME "chargen-901225-01.bin"
filenames used for the chargen ROMs
C64_KERNAL_4064
#define C64_KERNAL_4064 100
901246-01
C64_KERNAL_4064_NAME
#define C64_KERNAL_4064_NAME "kernal-901246-01.bin"
C64_KERNAL_CHECKSUM_GS64
#define C64_KERNAL_CHECKSUM_GS64 46538
390852-01 (gs)
C64_KERNAL_CHECKSUM_JAP
#define C64_KERNAL_CHECKSUM_JAP 53635
906145-02
C64_KERNAL_CHECKSUM_R01
#define C64_KERNAL_CHECKSUM_R01 54525
901227-01
C64_KERNAL_CHECKSUM_R02
#define C64_KERNAL_CHECKSUM_R02 50955
901227-02
C64_KERNAL_CHECKSUM_R03
#define C64_KERNAL_CHECKSUM_R03 50954
901227-03
C64_KERNAL_CHECKSUM_R03swe
#define C64_KERNAL_CHECKSUM_R03swe 50633
FIXME.
C64_KERNAL_CHECKSUM_R43
#define C64_KERNAL_CHECKSUM_R43 50955
251104-04 (sx)
C64_KERNAL_CHECKSUM_R64
#define C64_KERNAL_CHECKSUM_R64 49680
901246-01 (educator)
C64_KERNAL_GS64
#define C64_KERNAL_GS64 39
390852-01
C64_KERNAL_GS64_NAME
#define C64_KERNAL_GS64_NAME "kernal-390852-01.bin"
C64_KERNAL_HASH_GS64
#define C64_KERNAL_HASH_GS64 "3ad6cc1837c679a11f551ad1cf1a32dd84ace719"
390852-01 (gs)
C64_KERNAL_HASH_JAP
#define C64_KERNAL_HASH_JAP "4ff0f11e80f4b57430d8f0c3799ed0f0e0f4565d"
906145-02
C64_KERNAL_HASH_R01
#define C64_KERNAL_HASH_R01 "87cc04d61fc748b82df09856847bb5c2754a2033"
901227-01
C64_KERNAL_HASH_R02
#define C64_KERNAL_HASH_R02 "0e2e4ee3f2d41f00bed72f9ab588b83e306fdb13"
901227-02
C64_KERNAL_HASH_R03
#define C64_KERNAL_HASH_R03 "1d503e56df85a62fee696e7618dc5b4e781df1bb"
901227-03
C64_KERNAL_HASH_R43
#define C64_KERNAL_HASH_R43 "aa136e91ecf3c5ac64f696b3dbcbfc5ba0871c98"
251104-04 (sx)
C64_KERNAL_HASH_R64
#define C64_KERNAL_HASH_R64 "6c4fa9465f6091b174df27dfe679499df447503c"
901246-01 (educator)
C64_KERNAL_ID_GS64
#define C64_KERNAL_ID_GS64 0x03
390852-01 (gs)
C64_KERNAL_ID_JAP
#define C64_KERNAL_ID_JAP 0x00
the value located at 0xff80
906145-02
C64_KERNAL_ID_R01
#define C64_KERNAL_ID_R01 0xaa
901227-01
C64_KERNAL_ID_R02
#define C64_KERNAL_ID_R02 0x00
901227-02
C64_KERNAL_ID_R03
#define C64_KERNAL_ID_R03 0x03
901227-03
C64_KERNAL_ID_R03swe
#define C64_KERNAL_ID_R03swe 0x03
FIXME.
C64_KERNAL_ID_R43
#define C64_KERNAL_ID_R43 0x43
251104-04 (sx)
C64_KERNAL_ID_R64
#define C64_KERNAL_ID_R64 0x64
901246-01 (educator)
C64_KERNAL_JAP
#define C64_KERNAL_JAP 0
906145-02
C64_KERNAL_JAP_NAME
#define C64_KERNAL_JAP_NAME "kernal-906145-02.bin"
filenames used for the kernal ROMs
C64_KERNAL_NONE
#define C64_KERNAL_NONE -2
used for the MAX machine, which has no kernal
C64_KERNAL_NONE_NAME
#define C64_KERNAL_NONE_NAME "kernal-none.bin"
dummy, used for the MAX machine, which has no kernal
C64_KERNAL_REV1
#define C64_KERNAL_REV1 1
901227-01
C64_KERNAL_REV1_NAME
#define C64_KERNAL_REV1_NAME "kernal-901227-01.bin"
C64_KERNAL_REV2
#define C64_KERNAL_REV2 2
901227-02
C64_KERNAL_REV2_NAME
#define C64_KERNAL_REV2_NAME "kernal-901227-02.bin"
C64_KERNAL_REV3
#define C64_KERNAL_REV3 3
901227-03
C64_KERNAL_REV3_NAME
#define C64_KERNAL_REV3_NAME "kernal-901227-03.bin"
C64_KERNAL_REV3SWE
#define C64_KERNAL_REV3SWE 13
FIXME.
C64_KERNAL_SX64
#define C64_KERNAL_SX64 67
251104-04
C64_KERNAL_SX64_NAME
#define C64_KERNAL_SX64_NAME "kernal-251104-04.bin"
C64_KERNAL_UNKNOWN
#define C64_KERNAL_UNKNOWN -1
unique IDs to refer to a kernal, used for the KernalRev resource
Function Documentation
c64rom_get_kernal_chksum_id()
int c64rom_get_kernal_chksum_id (uint16_t * sumout, int * idout, char * sha1hash)
< used for the MAX machine, which has no kernal
Referenced by c64rom_print_kernal_info().
c64rom_isloaded()
int c64rom_isloaded (void)
Referenced by set_kernal_revision().
c64rom_load_basic()
int c64rom_load_basic (const char * rom_name)
Referenced by mem_load(), and set_basic_rom_name().
c64rom_load_chargen()
int c64rom_load_chargen (const char * rom_name)
Referenced by mem_load(), and set_chargen_rom_name().
c64rom_load_kernal()
int c64rom_load_kernal (const char * rom_name, uint8_t * new_kernal)
< dummy, used for the MAX machine, which has no kernal
Referenced by mem_load(), and set_kernal_rom_name().
c64rom_print_basic_info()
int c64rom_print_basic_info (void)
Referenced by c64_snapshot_read_rom_module(), and c64rom_load_basic().
c64rom_print_kernal_info()
int c64rom_print_kernal_info (void)
print ROM ID, checksum, sha1 hash.
returns the revision
Todo:
FIXME: this function has a misleading name, only called from snapshot stuff atm it was used to patch the kernal before, but not anymore
< used for the MAX machine, which has no kernal
Referenced by c64_snapshot_read_rom_module(), and c64rom_load_kernal().
Variable Documentation
c64rom_cartkernal_active
int c64rom_cartkernal_active extern
Referenced by c64rom_load_kernal().