vsid: fsdevice/fsdevice-filename.c File Reference
fsdevice-filename.c File Reference
#include "vice.h"
#include <string.h>
#include "archdep.h"
#include "charset.h"
#include "fsdevicetypes.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "vdrive.h"
#include "fsdevice-filename.h"
Macros
#define DBG(x)
#define LONGNAMEMARKER '/'
#define MAXDIRPOSMARK (10+26+26)
Functions
static int _limit_longname (archdep_dir_t *archdep_dir, vdrive_t *vdrive, char *longname, int mode)
static int limit_longname (vdrive_t *vdrive, char *longname, int mode)
static char * expand_shortname (vdrive_t *vdrive, char *shortname, int mode)
char * fsdevice_expand_shortname (vdrive_t *vdrive, char *name)
char * fsdevice_expand_shortname_ascii (vdrive_t *vdrive, char *name)
int fsdevice_limit_namelength (vdrive_t *vdrive, uint8_t *name)
int fsdevice_limit_namelength_ascii (vdrive_t *vdrive, char *name)
int fsdevice_limit_createnamelength (vdrive_t *vdrive, char *name)
Macro Definition Documentation
DBG
#define DBG (x)
LONGNAMEMARKER
#define LONGNAMEMARKER '/'
MAXDIRPOSMARK
#define MAXDIRPOSMARK (10+26+26)
Function Documentation
_limit_longname()
static int _limit_longname (archdep_dir_t * archdep_dir, vdrive_t * vdrive, char * longname, int mode) static
Referenced by expand_shortname(), and limit_longname().
expand_shortname()
static char * expand_shortname (vdrive_t * vdrive, char * shortname, int mode) static
Referenced by fsdevice_expand_shortname(), and fsdevice_expand_shortname_ascii().
fsdevice_expand_shortname()
char * fsdevice_expand_shortname (vdrive_t * vdrive, char * name)
Referenced by fsdevice_flush(), fsdevice_flush_rename(), and fsdevice_open_file().
fsdevice_expand_shortname_ascii()
char * fsdevice_expand_shortname_ascii (vdrive_t * vdrive, char * name)
Referenced by fsdevice_flush().
fsdevice_limit_createnamelength()
int fsdevice_limit_createnamelength (vdrive_t * vdrive, char * name)
Referenced by fsdevice_flush(), fsdevice_flush_rename(), and fsdevice_open_file().
fsdevice_limit_namelength()
int fsdevice_limit_namelength (vdrive_t * vdrive, uint8_t * name)
Referenced by autostart_prg(), and command_directory_get().
fsdevice_limit_namelength_ascii()
int fsdevice_limit_namelength_ascii (vdrive_t * vdrive, char * name)
limit_longname()
static int limit_longname (vdrive_t * vdrive, char * longname, int mode) static
Referenced by fsdevice_limit_namelength(), and fsdevice_limit_namelength_ascii().