x128: arch/shared/archdep_dir.c File Reference
archdep_dir.c File Reference
Read host directory.
#include "vice.h"
#include "archdep.h"
#include <string.h>
#include <stdbool.h>
#include <errno.h>
#include <sys/types.h>
#include <dirent.h>
#include "lib.h"
#include "util.h"
#include "archdep_dir.h"
Macros
#define INITIAL_ARRAY_SIZE 64
Initial size of an array of file/directory entries.
Functions
static int compare_names (const void *a, const void *b)
Comparision function for qsort() in archdep_opendir()
static bool must_show_dotfile (const char *name, int mode)
Check if an entry must be shown.
static void add_dir_entry (archdep_dir_t *dir, const char *path)
Add dir entry to directory object.
static void add_file_entry (archdep_dir_t *dir, const char *path)
Add file entry to directory object.
static bool scan_directory (archdep_dir_t *dir, const char *path, int mode)
Populate the directory and file lists.
archdep_dir_t * archdep_opendir (const char *path, int mode)
Scan directory and return a directory object.
const char * archdep_readdir (archdep_dir_t *dir)
Get an entry from the directory.
void archdep_closedir (archdep_dir_t *dir)
Close directory.
void archdep_rewinddir (archdep_dir_t *dir)
Rewind position in directory.
void archdep_seekdir (archdep_dir_t *dir, int pos)
Set position in directory.
int archdep_telldir (const archdep_dir_t *dir)
Get position in directory.
const char * archdep_readdir_get_dir (const archdep_dir_t *dir, int pos)
Get directory entry from directory object.
const char * archdep_readdir_get_file (const archdep_dir_t *dir, int pos)
Get filename entry from directory object.
const char * archdep_readdir_get_entry (const archdep_dir_t *dir, int pos)
Get entry from directory object.
int archdep_readdir_num_entries (const archdep_dir_t *dir)
Get total number of entries.
int archdep_readdir_num_dirs (const archdep_dir_t *dir)
Get number of directory entries.
int archdep_readdir_num_files (const archdep_dir_t *dir)
Get number of file entries.
Detailed Description
Read host directory.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Macro Definition Documentation
INITIAL_ARRAY_SIZE
#define INITIAL_ARRAY_SIZE 64
Initial size of an array of file/directory entries.
Number of elements in the arrays when initially allocating them.
This number was chosen arbitrarily, reasonable trade-off between wasting memory for small directories and not triggering too many realloc calls with larger directories.
Function Documentation
add_dir_entry()
static void add_dir_entry (archdep_dir_t * dir, const char * path) static
Add dir entry to directory object.
Add path to the list of directory in dir.
Parameters
[in] dir directory object
[in] path dirname to add
Referenced by scan_directory().
add_file_entry()
static void add_file_entry (archdep_dir_t * dir, const char * path) static
Add file entry to directory object.
Add path to the list of files in dir.
Parameters
[in] dir directory object
[in] path filename to add
Referenced by scan_directory().
archdep_closedir()
void archdep_closedir (archdep_dir_t * dir)
Close directory.
Free memory used by dir and its members.
Parameters
[in] dir directory object
Referenced by archdep_opendir(), cbmfile_find_file(), expand_shortname(), fsdevice_close(), limit_longname(), mon_show_dir(), p00_file_find(), and palette_get_info_list().
archdep_opendir()
archdep_dir_t * archdep_opendir (const char * path, int mode)
Scan directory and return a directory object.
Parameters
[in] path directory to scan
[in] mode filter to apply on each directory entry
Returns
directory object or NULL on failure
Referenced by cbmfile_find_file(), expand_shortname(), fsdevice_open_directory(), limit_longname(), mon_show_dir(), p00_file_find(), and palette_get_info_list().
archdep_readdir()
const char * archdep_readdir (archdep_dir_t * dir)
Get an entry from the directory.
Parameters
[in] dir directory object
Returns
entry or NULL when the directory is exhausted
Referenced by _limit_longname(), cbmfile_find_file(), command_directory_get(), expand_shortname(), mon_show_dir(), p00_file_find(), and palette_get_info_list().
archdep_readdir_get_dir()
const char * archdep_readdir_get_dir (const archdep_dir_t * dir, int pos)
Get directory entry from directory object.
Parameters
[in] dir directory object
[in] pos position in directories list in dir
Returns
directory name or NULL when pos is out of bounds
Referenced by archdep_readdir_get_entry().
archdep_readdir_get_entry()
const char * archdep_readdir_get_entry (const archdep_dir_t * dir, int pos)
Get entry from directory object.
Get entry from dir with the assumption that the directories come before the files, joining the two lists as a single list for the pos argument.
Parameters
[in] dir directory object
[in] pos position in directories and files list in dir
Returns
entry or NULL when pos is out of bounds
archdep_readdir_get_file()
const char * archdep_readdir_get_file (const archdep_dir_t * dir, int pos)
Get filename entry from directory object.
Parameters
[in] dir directory object
[in] pos position in files list in dir
Returns
filename or NULL when pos is out of bounds
Referenced by archdep_readdir_get_entry().
archdep_readdir_num_dirs()
int archdep_readdir_num_dirs (const archdep_dir_t * dir)
Get number of directory entries.
Parameters
[in] dir directory object
Returns
number of directory entries
archdep_readdir_num_entries()
int archdep_readdir_num_entries (const archdep_dir_t * dir)
Get total number of entries.
Parameters
[in] dir directory object
Returns
total number of entries (dirs + files)
archdep_readdir_num_files()
int archdep_readdir_num_files (const archdep_dir_t * dir)
Get number of file entries.
Parameters
[in] dir directory object
Returns
number of file entries
archdep_rewinddir()
void archdep_rewinddir (archdep_dir_t * dir)
Rewind position in directory.
Rewind position in dir to the first entry.
Parameters
[in] dir directory object
Referenced by _limit_longname().
archdep_seekdir()
void archdep_seekdir (archdep_dir_t * dir, int pos)
Set position in directory.
Parameters
[in] dir directory object
[in] pos new position
Referenced by _limit_longname().
archdep_telldir()
int archdep_telldir (const archdep_dir_t * dir)
Get position in directory.
Parameters
[in] dir directory object
Returns
position in dir or -1 when dir is exhausted
Referenced by _limit_longname().
compare_names()
static int compare_names (const void * a, const void * b) static
Comparision function for qsort() in archdep_opendir()
Parameters
[in] a first item
[in] b second item
Returns
< 0 if a < b, 0 if a == b, > 0 if a > b
Referenced by archdep_opendir().
must_show_dotfile()
static bool must_show_dotfile (const char * name, int mode) static
Check if an entry must be shown.
Check if name matches the mode filter.
Checks if a dotfile must be shown according to mode.
Returns
true if the file or directory must be shown
Referenced by scan_directory().
scan_directory()
static bool scan_directory (archdep_dir_t * dir, const char * path, int mode) static
Populate the directory and file lists.
Scan path for files and directories, filtering them according to mode.
Parameters
[in] dir directory object
[in] path directory to scan
[in] mode filter to apply to each directory entry
Returns
true on success
< directory separator as a string
Referenced by archdep_opendir().