vsid: arch/shared/console_unix.c File Reference
console_unix.c File Reference
Unix specific console access interface for SDL.
#include "vice.h"
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "console.h"
#include "lib.h"
#include "log.h"
#include "charset.h"
#include "lib/linenoise-ng/linenoise.h"
Data Structures
struct console_private_s
Monitor console window object.
Typedefs
typedef struct console_private_s console_private_t
Functions
console_t * native_console_open (const char *id)
the same set of functions, which will work with a "native" console of the host
int native_console_close (console_t *log)
int native_console_out (console_t *log, const char *format,...)
output to console, no translation (ASCII)
int native_console_petscii_out (int maxlen, console_t *log, const char *format,...)
int native_console_petscii_upper_out (int maxlen, console_t *log, const char *format,...)
int native_console_scrcode_out (int maxlen, console_t *log, const char *format,...)
char * native_console_in (console_t *log, const char *prompt)
int native_console_init (void)
int native_console_close_all (void)
Detailed Description
Unix specific console access interface for SDL.
Author
Hannu Nuotio hannu.nosp@m..nuo.nosp@m.tio@t.nosp@m.ut.f.nosp@m.i
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
!
Todo:
Properly document this code.
Typedef Documentation
console_private_t
typedef struct console_private_s console_private_t
Function Documentation
native_console_close()
int native_console_close (console_t * log)
Referenced by uimonfb_window_close().
native_console_close_all()
int native_console_close_all (void)
Referenced by consolefb_close_all().
native_console_in()
char * native_console_in (console_t * log, const char * prompt)
Referenced by uimonfb_get_in().
native_console_init()
int native_console_init (void)
Referenced by consolefb_init().
native_console_open()
console_t * native_console_open (const char * id)
the same set of functions, which will work with a "native" console of the host
Referenced by uimonfb_window_open().
native_console_out()
int native_console_out (console_t * log, const char * format, ...)
output to console, no translation (ASCII)
Referenced by consolefb_out(), and uimonfb_out().
native_console_petscii_out()
int native_console_petscii_out (int maxlen, console_t * log, const char * format, ...)
Referenced by uimonfb_petscii_out().
native_console_petscii_upper_out()
int native_console_petscii_upper_out (int maxlen, console_t * log, const char * format, ...)
Referenced by uimonfb_petscii_upper_out().
native_console_scrcode_out()
int native_console_scrcode_out (int maxlen, console_t * log, const char * format, ...)
Referenced by uimonfb_scrcode_out().