x128: arch/shared/hotkeys/textfilereader.c File Reference
textfilereader.c File Reference
Stack-based text file reader.
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <errno.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "sysfile.h"
#include "util.h"
#include "textfilereader.h"
#include "vhkdebug.h"
Macros
#define TEXTFILE_READER_BUFSIZE 1024
Initial size of the buffer of the textfile reader.
Functions
static textfile_entry_t * textfile_entry_new (const char *path)
Create new textfile_entry_t instance.
static void textfile_entry_free (textfile_entry_t *entry)
Free textfile entry and its members.
static void textfile_entry_free_all (textfile_entry_t *entry)
Free textfile entry and its members recusively.
void textfile_reader_init (textfile_reader_t *reader)
Initialize reader.
void textfile_reader_free (textfile_reader_t *reader)
Free all memory used by reader.
bool textfile_reader_open (textfile_reader_t *reader, const char *path)
Open a new file.
bool textfile_reader_close (textfile_reader_t *reader)
Close current file, reopen any previous file.
const char * textfile_reader_read (textfile_reader_t *reader)
Read a single line of text.
long textfile_reader_linenum (const textfile_reader_t *reader)
Get line number of current file.
const char * textfile_reader_filename (const textfile_reader_t *reader)
Get name of current file.
Detailed Description
Stack-based text file reader.
Read text files that can recursively "include" other text files while using a single file descriptor.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
TEXTFILE_READER_BUFSIZE
#define TEXTFILE_READER_BUFSIZE 1024
Initial size of the buffer of the textfile reader.
The buffer will be automatically doubled in size
Function Documentation
textfile_entry_free()
static void textfile_entry_free (textfile_entry_t * entry) static
Free textfile entry and its members.
Free entry and its members.
Parameters
[in] entry textfile entry instance
Referenced by textfile_entry_free_all(), and textfile_reader_close().
textfile_entry_free_all()
static void textfile_entry_free_all (textfile_entry_t * entry) static
Free textfile entry and its members recusively.
Free entry, its members and recursively its siblings.
Parameters
[in] entry textfile entry instance
Referenced by textfile_entry_free_all(), and textfile_reader_free().
textfile_entry_new()
static textfile_entry_t * textfile_entry_new (const char * path) static
Create new textfile_entry_t instance.
Allocate memory for a textfile_entry_t instance and copy path.
Parameters
[in] path path to file
Returns
heap-allocated textfile_entry_t instance
Referenced by textfile_reader_open().
textfile_reader_close()
bool textfile_reader_close (textfile_reader_t * reader)
Close current file, reopen any previous file.
Closes the current file and reopens and repositions any previous file.
Parameters
[in] reader textfile reader
Returns
true if a previous file was reopened
Referenced by textfile_reader_read(), and vhk_parser_parse().
textfile_reader_filename()
const char * textfile_reader_filename (const textfile_reader_t * reader)
Get name of current file.
Get the path of the currently opened file of reader.
Parameters
[in] reader textfile reader
Returns
path or "<null>" when no file is open
Referenced by vhk_parser_do_clear(), vhk_parser_do_undef(), vhk_parser_error(), and vhk_parser_warning().
textfile_reader_free()
void textfile_reader_free (textfile_reader_t * reader)
Free all memory used by reader.
Free all memory used by reader and close any open file.
Parameters
[in,out] reader textfile reader instance
Referenced by vhk_parser_parse().
textfile_reader_init()
void textfile_reader_init (textfile_reader_t * reader)
Initialize reader.
Initialize the reader for use by setting all members and allocating the buffer to its initial size.
Parameters
[in,out] reader textfile reader
Referenced by vhk_parser_parse().
textfile_reader_linenum()
long textfile_reader_linenum (const textfile_reader_t * reader)
Get line number of current file.
Get the line number of the currently opened file in reader.
Parameters
[in] reader textfile reader
Returns
line number or -1 when no file is open
Referenced by vhk_parser_do_clear(), vhk_parser_do_undef(), vhk_parser_error(), vhk_parser_parse(), and vhk_parser_warning().
textfile_reader_open()
bool textfile_reader_open (textfile_reader_t * reader, const char * path)
Open a new file.
Open a new file and remember the position in the previous file, if any.
If a previous file was open, close it and remember its stream position and line number, open the new file and push it on top of the stack.
Parameters
[in] reader textfile reader
[in] path path to new file
Returns
bool
Referenced by vhk_parser_open_file().
textfile_reader_read()
const char * textfile_reader_read (textfile_reader_t * reader)
Read a single line of text.
Reads a single line of text from the file on top of the stack.
Parameters
[in] reader textfile reader
Returns
pointer to line buffer in reader or NULL when EOF
Todo:
Also returns NULL on I/O error, I'll need a way to differenciate between EOF and I/O errors, akin to feof(3).
Referenced by vhk_parser_parse().