vsid: tape/tape.c File Reference
tape.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "autostart.h"
#include "datasette.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "mem.h"
#include "network.h"
#include "t64.h"
#include "tap.h"
#include "tape-internal.h"
#include "tape.h"
#include "tapeimage.h"
#include "tapeport.h"
#include "traps.h"
#include "types.h"
#include "uiapi.h"
#include "vice-event.h"
Macros
#define CAS_TYPE_OFFSET 0
Cassette Format Constants.
#define CAS_STAD_OFFSET 1
start address
#define CAS_ENAD_OFFSET 3
end address
#define CAS_NAME_OFFSET 5
filename
Functions
static void set_st (uint8_t b)
void tape_traps_install (void)
void tape_traps_deinstall (void)
static void tape_init_vars (const tape_init_t *init)
int tape_init (const tape_init_t *init)
Initialize the tape emulation, using the traps in ‘trap_list’.
int tape_reinit (const tape_init_t *init)
re-init the traps, needed to switch between different configurations in x128
void tape_shutdown (void)
int tape_deinstall (void)
static int default_tape_header_type (void)
int tape_find_header_trap (void)
Find the next Tape Header and load it onto the Tape Buffer.
int tape_find_header_trap_plus4 (void)
int tape_receive_trap (void)
int tape_receive_trap_plus4 (void)
const char * tape_get_file_name (int port)
int tape_tap_attached (int port)
int tape_image_detach_internal (unsigned int unit)
Detach.
int tape_image_detach (unsigned int unit)
External tape image interface.
void tape_image_detach_all (void)
static int tape_image_attach_internal (unsigned int unit, const char *name)
Attach.
int tape_image_attach (unsigned int unit, const char *name)
void tape_image_event_playback (unsigned int unit, const char *filename)
Variables
static uint16_t buffer_pointer_addr
CPU addresses for tape routine variables.
static uint16_t st_addr
static uint16_t verify_flag_addr
static uint16_t stal_addr
static uint16_t eal_addr
static uint16_t kbd_buf_addr
static uint16_t kbd_buf_pending_addr
static int irqval
static uint16_t irqtmp
static int tape_is_initialized = 0
Flag: has tape been initialized?
static const trap_t * tape_traps
Tape traps to be installed.
static log_t tape_log = ((log_t)-1)
Logging goes here.
tape_image_t * tape_image_dev [TAPEPORT_MAX_PORTS] = { NULL }
The tape image for device 1.
Macro Definition Documentation
CAS_ENAD_OFFSET
#define CAS_ENAD_OFFSET 3
end address
CAS_NAME_OFFSET
#define CAS_NAME_OFFSET 5
filename
CAS_STAD_OFFSET
#define CAS_STAD_OFFSET 1
start address
CAS_TYPE_OFFSET
#define CAS_TYPE_OFFSET 0
Cassette Format Constants.
Function Documentation
default_tape_header_type()
static int default_tape_header_type (void) static
< Relocatable Program (loaded to basic start, SAVE "",1,0)
Referenced by tape_find_header_trap(), and tape_find_header_trap_plus4().
set_st()
static void set_st (uint8_t b) inline static
Referenced by tape_receive_trap(), and tape_receive_trap_plus4().
tape_deinstall()
int tape_deinstall (void)
tape_find_header_trap()
int tape_find_header_trap (void)
Find the next Tape Header and load it onto the Tape Buffer.
< start address
< start address
< end address
< end address
< filename
< End of Tape marker (SAVE "",1,n+2)
tape_find_header_trap_plus4()
int tape_find_header_trap_plus4 (void)
< start address
< start address
< end address
< end address
< filename
< End of Tape marker (SAVE "",1,n+2)
tape_get_file_name()
const char * tape_get_file_name (int port)
tape_image_attach()
int tape_image_attach (unsigned int unit, const char * name)
tape_image_attach_internal()
static int tape_image_attach_internal (unsigned int unit, const char * name) static
Attach.
Referenced by tape_image_attach(), and tape_image_event_playback().
tape_image_detach()
int tape_image_detach (unsigned int unit)
External tape image interface.
Referenced by tape_image_detach_all().
tape_image_detach_all()
void tape_image_detach_all (void)
tape_image_detach_internal()
int tape_image_detach_internal (unsigned int unit)
Detach.
Referenced by machine_specific_shutdown(), tape_deinstall(), tape_image_attach_internal(), tape_image_detach(), tape_image_event_playback(), and tape_snapshot_read_module().
tape_image_event_playback()
void tape_image_event_playback (unsigned int unit, const char * filename)
tape_init()
int tape_init (const tape_init_t * init)
Initialize the tape emulation, using the traps in ‘trap_list’.
Todo:
FIXME: This should be passed through a struct.
Referenced by machine_specific_init().
tape_init_vars()
static void tape_init_vars (const tape_init_t * init) static
Referenced by tape_init(), and tape_reinit().
tape_receive_trap()
int tape_receive_trap (void)
tape_receive_trap_plus4()
int tape_receive_trap_plus4 (void)
tape_reinit()
int tape_reinit (const tape_init_t * init)
re-init the traps, needed to switch between different configurations in x128
tape_shutdown()
void tape_shutdown (void)
tape_tap_attached()
int tape_tap_attached (int port)
tape_traps_deinstall()
void tape_traps_deinstall (void)
Referenced by tape_deinstall(), tape_image_attach_internal(), and tape_reinit().
tape_traps_install()
void tape_traps_install (void)
Referenced by tape_image_detach_internal(), tape_init(), and tape_reinit().
Variable Documentation
buffer_pointer_addr
uint16_t buffer_pointer_addr static
CPU addresses for tape routine variables.
Referenced by tape_find_header_trap(), tape_find_header_trap_plus4(), and tape_init_vars().
eal_addr
uint16_t eal_addr static
Referenced by tape_init_vars(), tape_receive_trap(), and tape_receive_trap_plus4().
irqtmp
uint16_t irqtmp static
Referenced by tape_find_header_trap(), tape_init_vars(), and tape_receive_trap().
irqval
int irqval static
Referenced by tape_find_header_trap(), tape_init_vars(), and tape_receive_trap().
kbd_buf_addr
uint16_t kbd_buf_addr static
Referenced by tape_find_header_trap(), tape_find_header_trap_plus4(), and tape_init_vars().
kbd_buf_pending_addr
uint16_t kbd_buf_pending_addr static
Referenced by tape_find_header_trap(), tape_find_header_trap_plus4(), and tape_init_vars().
st_addr
uint16_t st_addr static
Referenced by set_st(), tape_find_header_trap(), tape_find_header_trap_plus4(), and tape_init_vars().
stal_addr
uint16_t stal_addr static
Referenced by tape_init_vars(), tape_receive_trap(), and tape_receive_trap_plus4().
tape_image_dev
tape_image_t* tape_image_dev[TAPEPORT_MAX_PORTS] = { NULL }
The tape image for device 1.
Referenced by tape_deinstall(), tape_find_header_trap(), tape_find_header_trap_plus4(), tape_get_file_name(), tape_image_attach_internal(), tape_image_detach_internal(), tape_init(), tape_receive_trap(), tape_receive_trap_plus4(), tape_shutdown(), and tape_tap_attached().
tape_is_initialized
int tape_is_initialized = 0 static
Flag: has tape been initialized?
Referenced by tape_deinstall(), tape_init(), and tape_reinit().
tape_log
log_t tape_log = ((log_t)-1) static
Logging goes here.
Referenced by tape_image_attach_internal(), tape_image_detach_internal(), tape_init(), tape_receive_trap(), and tape_receive_trap_plus4().
tape_traps
const trap_t* tape_traps static
Tape traps to be installed.
Referenced by tape_deinstall(), tape_init_vars(), tape_reinit(), tape_traps_deinstall(), and tape_traps_install().
verify_flag_addr
uint16_t verify_flag_addr static
Referenced by tape_find_header_trap(), tape_find_header_trap_plus4(), and tape_init_vars().