vsid: vdrive/vdrive-command.c File Reference
vdrive-command.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "cbmdos.h"
#include "diskimage.h"
#include "lib.h"
#include "log.h"
#include "machine-drive.h"
#include "types.h"
#include "util.h"
#include "vdrive-bam.h"
#include "vdrive-command.h"
#include "vdrive-dir.h"
#include "vdrive-iec.h"
#include "vdrive-rel.h"
#include "vdrive.h"
#include "diskconstants.h"
#include "serial.h"
Macros
#define VDRIVE_IS_IMAGE(a) (serial_device_type_get(a->unit - 8) == SERIAL_DEVICE_VIRT)
#define IP_MAX_COMMAND_LEN 128
real 58
#define COPYBUFFER 32
#define COPYMAX 6
Functions
static int vdrive_command_format_internal (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_format_worker (struct vdrive_s *vdrive, uint8_t *disk_name, uint8_t *disk_id)
static int vdrive_command_validate_internal (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_block (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_memory (vdrive_t *vdrive, uint8_t *buffer, unsigned int length)
static int vdrive_command_initialize (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_copy (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_chdir (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_mkdir (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_rmdir (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_chpart (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_chcmdpart (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_rename (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_renameheader (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_renamepart (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_scratch (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_position (vdrive_t *vdrive, uint8_t *buf, unsigned int length)
static int vdrive_command_u1a2b (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_lockunlock (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_command_time (vdrive_t *vdrive, uint8_t *cmd, int length)
static int vdrive_command_getpartinfo (vdrive_t *vdrive, const uint8_t *cmd, int length)
static int vdrive_command_deletepart (vdrive_t *vdrive, const uint8_t *cmd, int length)
static void vdrive_cmdfree_full (cbmdos_cmd_parse_plus_t *cmd)
static void vdrive_cmdfree_abbrv (cbmdos_cmd_parse_plus_t *cmd)
static void vdrive_cmdfree_path (cbmdos_cmd_parse_plus_t *cmd)
static void vdrive_cmdfree_file (cbmdos_cmd_parse_plus_t *cmd)
static void vdrive_cmdfree_command (cbmdos_cmd_parse_plus_t *cmd)
static void vdrive_cmdfree_more (cbmdos_cmd_parse_plus_t *cmd)
static int vdrive_haswildcard (uint8_t *name, int length)
static unsigned int vdrive_atoi (char *namein, char **nameout, unsigned int length)
void vdrive_command_init (void)
int vdrive_command_execute (vdrive_t *vdrive, const uint8_t *buf, unsigned int length)
called by vdrive-iec.c; return code not used
static int vdrive_command_get_block_parameters (char *buf, int *p1, int *p2, int *p3, int *p4)
int vdrive_command_switchtraverse (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd)
void vdrive_command_return (vdrive_t *vdrive, int origpart)
int vdrive_command_switch (vdrive_t *vdrive, int part)
static int vdrive_command_allocate_chain (vdrive_t *vdrive, unsigned int t, unsigned int s, unsigned int *c)
static int vdrive_command_validate_worker (vdrive_t *vdrive, int geos, unsigned int *t_passed, unsigned int *s_passed)
int vdrive_command_validate (vdrive_t *vdrive)
int vdrive_command_format (struct vdrive_s *vdrive, const char *disk_name)
int vdrive_command_set_error (vdrive_t *vdrive, int code, unsigned int track, unsigned int sector)
int vdrive_command_memory_write (vdrive_t *vdrive, const uint8_t *buf, uint16_t addr, unsigned int length)
int vdrive_command_memory_exec (vdrive_t *vdrive, const uint8_t *buf, uint16_t addr, unsigned int length)
int vdrive_command_memory_read (vdrive_t *vdrive, const uint8_t *buf, uint16_t addr, unsigned int length)
static int int_to_bcd (int dec)
Variables
static log_t vdrive_command_log = ((log_t)-1)
Macro Definition Documentation
COPYBUFFER
#define COPYBUFFER 32
COPYMAX
#define COPYMAX 6
IP_MAX_COMMAND_LEN
#define IP_MAX_COMMAND_LEN 128
real 58
VDRIVE_IS_IMAGE
#define VDRIVE_IS_IMAGE (a) (serial_device_type_get(a->unit - 8) == SERIAL_DEVICE_VIRT)
Function Documentation
int_to_bcd()
static int int_to_bcd (int dec) inline static
Referenced by vdrive_command_time().
vdrive_atoi()
static unsigned int vdrive_atoi (char * namein, char ** nameout, unsigned int length) static
Referenced by vdrive_command_chcmdpart().
vdrive_cmdfree_abbrv()
static void vdrive_cmdfree_abbrv (cbmdos_cmd_parse_plus_t * cmd) static
Referenced by vdrive_command_copy(), vdrive_command_execute(), vdrive_command_format(), vdrive_command_rename(), vdrive_command_renamepart(), and vdrive_command_scratch().
vdrive_cmdfree_command()
static void vdrive_cmdfree_command (cbmdos_cmd_parse_plus_t * cmd) static
Referenced by vdrive_command_copy(), vdrive_command_execute(), vdrive_command_format(), vdrive_command_rename(), vdrive_command_renamepart(), vdrive_command_rmdir(), and vdrive_command_scratch().
vdrive_cmdfree_file()
static void vdrive_cmdfree_file (cbmdos_cmd_parse_plus_t * cmd) static
Referenced by vdrive_command_execute(), vdrive_command_format(), vdrive_command_rename(), vdrive_command_renamepart(), and vdrive_command_scratch().
vdrive_cmdfree_full()
static void vdrive_cmdfree_full (cbmdos_cmd_parse_plus_t * cmd) static
Referenced by vdrive_command_copy(), vdrive_command_execute(), vdrive_command_rename(), vdrive_command_renamepart(), and vdrive_command_scratch().
vdrive_cmdfree_more()
static void vdrive_cmdfree_more (cbmdos_cmd_parse_plus_t * cmd) static
Referenced by vdrive_command_execute(), vdrive_command_format(), and vdrive_command_scratch().
vdrive_cmdfree_path()
static void vdrive_cmdfree_path (cbmdos_cmd_parse_plus_t * cmd) static
Referenced by vdrive_command_execute(), vdrive_command_format(), vdrive_command_rename(), vdrive_command_renamepart(), vdrive_command_rmdir(), and vdrive_command_scratch().
vdrive_command_allocate_chain()
static int vdrive_command_allocate_chain (vdrive_t * vdrive, unsigned int t, unsigned int s, unsigned int * c) static
Referenced by vdrive_command_validate(), and vdrive_command_validate_worker().
vdrive_command_block()
static int vdrive_command_block (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
Referenced by vdrive_command_execute().
vdrive_command_chcmdpart()
static int vdrive_command_chcmdpart (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
< HD in ASCII for CMDHD
< 1581
< 1581
< 1581
< 1581
< 1581
< 1581
Referenced by vdrive_command_execute().
vdrive_command_chdir()
static int vdrive_command_chdir (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
Referenced by vdrive_command_execute().
vdrive_command_chpart()
static int vdrive_command_chpart (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
backup current partition information
< 1581
< 1581 partition
< 1581
< 1581
< should match FILEIO_TYPE_xxx
< 1581 partition
< 1581
< directory sector number
< 1581
< 1581
Referenced by vdrive_command_execute().
vdrive_command_copy()
static int vdrive_command_copy (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
< should match FILEIO_TYPE_xxx
< for relative files
< for relative files
< should match FILEIO_TYPE_xxx
< should match FILEIO_TYPE_xxx
< for relative files
Referenced by vdrive_command_execute().
vdrive_command_deletepart()
static int vdrive_command_deletepart (vdrive_t * vdrive, const uint8_t * cmd, int length) static
< HD in ASCII for CMDHD
Referenced by vdrive_command_execute().
vdrive_command_execute()
int vdrive_command_execute (vdrive_t * vdrive, const uint8_t * buf, unsigned int length)
called by vdrive-iec.c; return code not used
< real 58
check for unabbreviated commands
check for abbreviated commands
Referenced by mon_drive_execute_disk_cmd(), and vdrive_iec_flush().
vdrive_command_format()
int vdrive_command_format (struct vdrive_s * vdrive, const char * disk_name)
Todo:
the cmd structure should just be created and passed to the format function
Referenced by vdrive_internal_format_disk_image().
vdrive_command_format_internal()
static int vdrive_command_format_internal (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
backup current partition information
Referenced by vdrive_command_execute(), and vdrive_command_format().
vdrive_command_format_worker()
static int vdrive_command_format_worker (struct vdrive_s * vdrive, uint8_t * disk_name, uint8_t * disk_id) static
Todo:
FIXME: should we do this?
Referenced by vdrive_command_format_internal().
vdrive_command_get_block_parameters()
static int vdrive_command_get_block_parameters (char * buf, int * p1, int * p2, int * p3, int * p4) static
Referenced by vdrive_command_block(), and vdrive_command_u1a2b().
vdrive_command_getpartinfo()
static int vdrive_command_getpartinfo (vdrive_t * vdrive, const uint8_t * cmd, int length) static
< HD in ASCII for CMDHD
Referenced by vdrive_command_execute().
vdrive_command_init()
void vdrive_command_init (void)
Referenced by vdrive_init().
vdrive_command_initialize()
static int vdrive_command_initialize (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
backup current partition information
Referenced by vdrive_command_execute().
vdrive_command_lockunlock()
static int vdrive_command_lockunlock (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
backup current partition information
Referenced by vdrive_command_execute().
vdrive_command_memory()
static int vdrive_command_memory (vdrive_t * vdrive, uint8_t * buffer, unsigned int length) static
Referenced by vdrive_command_execute().
vdrive_command_memory_exec()
int vdrive_command_memory_exec (vdrive_t * vdrive, const uint8_t * buf, uint16_t addr, unsigned int length)
Todo:
FIXME: This function doesn't need buf or length.
Referenced by fsdevice_flush(), and vdrive_command_memory().
vdrive_command_memory_read()
int vdrive_command_memory_read (vdrive_t * vdrive, const uint8_t * buf, uint16_t addr, unsigned int length)
< non-tde drive/image
Referenced by fsdevice_flush(), and vdrive_command_memory().
vdrive_command_memory_write()
int vdrive_command_memory_write (vdrive_t * vdrive, const uint8_t * buf, uint16_t addr, unsigned int length)
Todo:
FIXME: incomplete
< non-tde drive/image
< HD in ASCII for CMDHD
Referenced by fsdevice_flush(), and vdrive_command_memory().
vdrive_command_mkdir()
static int vdrive_command_mkdir (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
backup current partition information
< should match FILEIO_TYPE_xxx
Referenced by vdrive_command_execute().
vdrive_command_position()
static int vdrive_command_position (vdrive_t * vdrive, uint8_t * buf, unsigned int length) static
default the record number to 1
default the record number's high byte to 0
default the position to 1
Referenced by vdrive_command_execute().
vdrive_command_rename()
static int vdrive_command_rename (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
unsigned int filetype;
backup current partition information
filetype = cmd->filetype;
Todo:
FIXME: is this right?
Referenced by vdrive_command_execute().
vdrive_command_renameheader()
static int vdrive_command_renameheader (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
backup current partition information
Referenced by vdrive_command_execute().
vdrive_command_renamepart()
static int vdrive_command_renamepart (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
backup current partition information
Referenced by vdrive_command_execute().
vdrive_command_return()
void vdrive_command_return (vdrive_t * vdrive, int origpart)
Referenced by vdrive_command_block(), vdrive_command_chdir(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_format_internal(), vdrive_command_initialize(), vdrive_command_lockunlock(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_renameheader(), vdrive_command_renamepart(), vdrive_command_rmdir(), vdrive_command_scratch(), vdrive_command_u1a2b(), and vdrive_command_validate_internal().
vdrive_command_rmdir()
static int vdrive_command_rmdir (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
backup current partition information
Referenced by vdrive_command_execute().
vdrive_command_scratch()
static int vdrive_command_scratch (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
< should match FILEIO_TYPE_xxx
backup current partition information
any =[filetype] is on the 'more' structure
Todo:
FIXME: 1581 sub-directories? where is the geos signature?
< 1581 partition
Referenced by vdrive_command_execute().
vdrive_command_set_error()
int vdrive_command_set_error (vdrive_t * vdrive, int code, unsigned int track, unsigned int sector)
last_code = CBMDOS_IPE_OK;
Referenced by iec_close_sequential(), iec_open_read(), iec_open_read_directory(), iec_open_write(), iec_write_sequential(), vdrive_bam_allocate_chain(), vdrive_bam_allocate_chain_255(), vdrive_command_allocate_chain(), vdrive_command_block(), vdrive_command_chcmdpart(), vdrive_command_chpart(), vdrive_command_deletepart(), vdrive_command_execute(), vdrive_command_getpartinfo(), vdrive_command_memory(), vdrive_command_memory_exec(), vdrive_command_memory_read(), vdrive_command_memory_write(), vdrive_command_rmdir(), vdrive_command_scratch(), vdrive_command_time(), vdrive_command_u1a2b(), vdrive_command_validate(), vdrive_command_validate_worker(), vdrive_device_setup(), vdrive_iec_close(), vdrive_iec_open(), vdrive_iec_read(), vdrive_iec_write(), vdrive_rel_add_sector(), vdrive_rel_open(), vdrive_rel_open_new(), vdrive_rel_read(), vdrive_rel_record_max(), and vdrive_rel_write().
vdrive_command_switch()
int vdrive_command_switch (vdrive_t * vdrive, int part)
Referenced by vdrive_command_block(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_execute(), vdrive_command_format_internal(), vdrive_command_initialize(), vdrive_command_switchtraverse(), vdrive_command_u1a2b(), and vdrive_command_validate_internal().
vdrive_command_switchtraverse()
int vdrive_command_switchtraverse (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd)
for CD: "CD:DIR" "CD/DIR" "CD/DIR/" "CD_" (<-) are acceptable
Referenced by vdrive_command_chdir(), vdrive_command_copy(), vdrive_command_lockunlock(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_renameheader(), vdrive_command_rmdir(), vdrive_command_scratch(), and vdrive_iec_open().
vdrive_command_time()
static int vdrive_command_time (vdrive_t * vdrive, uint8_t * cmd, int length) static
only process T-RA, T-RD, T-RB, and ignore T-WA, T-WD, T-WB; error out on everything else
Referenced by vdrive_command_execute().
vdrive_command_u1a2b()
static int vdrive_command_u1a2b (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
Referenced by vdrive_command_execute().
vdrive_command_validate()
int vdrive_command_validate (vdrive_t * vdrive)
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_command_format_worker(), and vdrive_command_validate_internal().
vdrive_command_validate_internal()
static int vdrive_command_validate_internal (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd) static
backup current partition information
Referenced by vdrive_command_execute().
vdrive_command_validate_worker()
static int vdrive_command_validate_worker (vdrive_t * vdrive, int geos, unsigned int * t_passed, unsigned int * s_passed) static
< 1581 partition
< should match FILEIO_TYPE_xxx
Referenced by vdrive_command_validate(), and vdrive_command_validate_worker().
vdrive_haswildcard()
static int vdrive_haswildcard (uint8_t * name, int length) static
Referenced by vdrive_command_copy(), vdrive_command_lockunlock(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_renameheader(), vdrive_command_renamepart(), and vdrive_command_rmdir().
Variable Documentation
vdrive_command_log
log_t vdrive_command_log = ((log_t)-1) static
Referenced by vdrive_command_block(), vdrive_command_execute(), vdrive_command_init(), vdrive_command_memory_exec(), vdrive_command_memory_read(), vdrive_command_memory_write(), vdrive_command_set_error(), and vdrive_command_u1a2b().