vsid: serial/serial-device.c File Reference
serial-device.c File Reference
#include "vice.h"
#include "serial.h"
Functions
serial_t * serial_device_get (unsigned int unit)
unsigned int serial_device_type_get (unsigned int unit)
void serial_device_type_set (unsigned int type, unsigned int unit)
Variables
static serial_t serialdevices [16]
Initialized serial devices.
Function Documentation
serial_device_get()
serial_t * serial_device_get (unsigned int unit)
Referenced by file_system_init(), fsdrive_listentalk(), fsdrive_open(), fsdrive_read(), fsdrive_reset(), fsdrive_unlisten(), fsdrive_write(), machine_bus_device_attach(), machine_bus_device_detach(), machine_bus_init(), parallel_trap_attention(), parallel_trap_receivebyte(), parallel_trap_sendbyte(), parallelcommand(), serial_device_type_get(), serial_device_type_set(), serial_trap_attention(), and serialcommand().
serial_device_type_get()
unsigned int serial_device_type_get (unsigned int unit)
Referenced by machine_bus_device_type_get(), serial_iec_bus_close(), serial_iec_bus_listen(), serial_iec_bus_open(), serial_iec_bus_read(), serial_iec_bus_talk(), serial_iec_bus_unlisten(), serial_iec_bus_untalk(), and serial_iec_bus_write().
serial_device_type_set()
void serial_device_type_set (unsigned int type, unsigned int unit)
Referenced by file_system_attach_disk_internal(), file_system_init(), interface_serial_attach(), and set_file_system_device().
Variable Documentation
serialdevices
serial_t serialdevices[16] static
Initialized serial devices.
Referenced by serial_device_get().