x128: drive/ieee/via1d2031.h File Reference
via1d2031.h File Reference
#include "types.h"
Functions
void via1d2031_setup_context (struct diskunit_context_s *ctxptr)
void via1d2031_init (struct diskunit_context_s *ctxptr)
void via1d2031_store (struct diskunit_context_s *ctxptr, uint16_t addr, uint8_t byte)
uint8_t via1d2031_read (struct diskunit_context_s *ctxptr, uint16_t addr)
uint8_t via1d2031_peek (struct diskunit_context_s *ctxptr, uint16_t addr)
void via1d2031_set_atn (struct via_context_s *via_context, int state)
Function Documentation
via1d2031_init()
void via1d2031_init (struct diskunit_context_s * ctxptr)
Referenced by ieee_drive_init().
via1d2031_peek()
uint8_t via1d2031_peek (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memieee_init().
via1d2031_read()
uint8_t via1d2031_read (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memieee_init().
via1d2031_set_atn()
void via1d2031_set_atn (struct via_context_s * via_context, int state)
Referenced by ieee_drive_parallel_set_atn().
via1d2031_setup_context()
void via1d2031_setup_context (struct diskunit_context_s * ctxptr)
Referenced by ieee_drive_setup_context().
via1d2031_store()
void via1d2031_store (struct diskunit_context_s * ctxptr, uint16_t addr, uint8_t byte)
Referenced by memieee_init().