vsid: imagecontents/diskcontents-iec.c File Reference
diskcontents-iec.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "diskcontents-iec.h"
#include "imagecontents.h"
#include "lib.h"
#include "serial.h"
Macros
#define STATE_LOAD_ADDRESS 0
#define STATE_LINK_ADDRESS 1
#define STATE_FILE_SIZE 2
#define STATE_FIND_MARK1 3
#define STATE_FIND_MARK2 4
#define STATE_FIND_TYPE 5
#define STATE_LINE_END 6
#define STATE_PARSE_END 7
#define STATE_ERROR 100
Functions
static int getbuf (uint8_t *buf, int length, int *index, uint8_t *data)
static int state_load_address (uint8_t *buf, int length, int *index)
static int state_link_address (uint8_t *buf, int length, int *index)
static int state_file_size (uint8_t *buf, int length, int *index)
static int state_find_mark1 (uint8_t *buf, int length, int *index)
static int state_find_mark2 (uint8_t *buf, int length, int *index)
static int state_find_type (uint8_t *buf, int length, int *index)
static int state_line_end (uint8_t *buf, int length, int *index)
static image_contents_t * parse_directory (uint8_t *buf, int length)
image_contents_t * diskcontents_iec_read (unsigned int unit)
Variables
static image_contents_t * contents
static image_contents_file_list_t currfl
static image_contents_file_list_t * last_list
static unsigned int image_contents_find_name
Macro Definition Documentation
STATE_ERROR
#define STATE_ERROR 100
STATE_FILE_SIZE
#define STATE_FILE_SIZE 2
STATE_FIND_MARK1
#define STATE_FIND_MARK1 3
STATE_FIND_MARK2
#define STATE_FIND_MARK2 4
STATE_FIND_TYPE
#define STATE_FIND_TYPE 5
STATE_LINE_END
#define STATE_LINE_END 6
STATE_LINK_ADDRESS
#define STATE_LINK_ADDRESS 1
STATE_LOAD_ADDRESS
#define STATE_LOAD_ADDRESS 0
STATE_PARSE_END
#define STATE_PARSE_END 7
Function Documentation
diskcontents_iec_read()
image_contents_t * diskcontents_iec_read (unsigned int unit)
Referenced by machine_diskcontents_bus_read().
getbuf()
static int getbuf (uint8_t * buf, int length, int * index, uint8_t * data) static
Referenced by state_file_size(), state_find_mark1(), state_find_mark2(), state_find_type(), state_link_address(), and state_load_address().
parse_directory()
static image_contents_t * parse_directory (uint8_t * buf, int length) static
Referenced by diskcontents_iec_read().
state_file_size()
static int state_file_size (uint8_t * buf, int length, int * index) static
Referenced by parse_directory().
state_find_mark1()
static int state_find_mark1 (uint8_t * buf, int length, int * index) static
Referenced by parse_directory().
state_find_mark2()
static int state_find_mark2 (uint8_t * buf, int length, int * index) static
< lenght of a PETSCII filename
< standard length of container names, such as D64
Referenced by parse_directory().
state_find_type()
static int state_find_type (uint8_t * buf, int length, int * index) static
< file type and flags, eg: '*PRG<'
< lenght of a PETSCII filename
Referenced by parse_directory().
state_line_end()
static int state_line_end (uint8_t * buf, int length, int * index) static
Referenced by parse_directory().
state_link_address()
static int state_link_address (uint8_t * buf, int length, int * index) static
Referenced by parse_directory().
state_load_address()
static int state_load_address (uint8_t * buf, int length, int * index) static
Referenced by parse_directory().
Variable Documentation
contents
image_contents_t* contents static
Referenced by autostart_disk(), create_model(), dir_menu_popup_create(), diskcontents_block_read(), diskcontents_filesystem_read(), image_contents_destroy(), image_contents_filename_by_number(), image_contents_to_string(), parse_directory(), state_find_mark1(), state_find_type(), and state_line_end().
currfl
image_contents_file_list_t currfl static
Referenced by state_file_size(), state_find_mark1(), state_find_mark2(), state_find_type(), and state_line_end().
image_contents_find_name
unsigned int image_contents_find_name static
Referenced by parse_directory(), and state_find_type().
last_list
image_contents_file_list_t * last_list static
Referenced by parse_directory(), and state_line_end().