x128: cartridge.h File Reference
cartridge.h File Reference
#include "types.h"
#include "sound.h"
Data Structures
struct cartridge_info_t
cartridge info for GUIs
Macros
#define CARTRIDGE_DIGIMAX -100
Carts that don't have a rom image.
#define CARTRIDGE_DQBB -101
dqbb.c
#define CARTRIDGE_GEORAM -102
georam.c
#define CARTRIDGE_ISEPIC -103
isepic.c
#define CARTRIDGE_RAMCART -104
ramcart.c
#define CARTRIDGE_REU -105
reu.c
#define CARTRIDGE_SFX_SOUND_EXPANDER -106
sfx_soundexpander.c, fmopl.c
#define CARTRIDGE_SFX_SOUND_SAMPLER -107
sfx_soundsampler.c
#define CARTRIDGE_MIDI_PASSPORT -108
c64-midi.c
#define CARTRIDGE_MIDI_DATEL -109
c64-midi.c
#define CARTRIDGE_MIDI_SEQUENTIAL -110
c64-midi.c
#define CARTRIDGE_MIDI_NAMESOFT -111
c64-midi.c
#define CARTRIDGE_MIDI_MAPLIN -112
c64-midi.c
#define CARTRIDGE_DS12C887RTC -113
ds12c887rtc.c
#define CARTRIDGE_TFE -116
ethernetcart.c
#define CARTRIDGE_TURBO232 -117
c64acia1.c
#define CARTRIDGE_SWIFTLINK -118
c64acia1.c
#define CARTRIDGE_ACIA -119
c64acia1.c
#define CARTRIDGE_PLUS60K -120
plus60k.c
#define CARTRIDGE_PLUS256K -121
plus256k.c
#define CARTRIDGE_C64_256K -122
c64_256k.c
#define CARTRIDGE_CPM -123
cpmcart.c
#define CARTRIDGE_DEBUGCART -124
debugcart.c
#define CARTRIDGE_ULTIMAX -6
Known cartridge types.
#define CARTRIDGE_GENERIC_8KB -3
generic.c
#define CARTRIDGE_GENERIC_16KB -2
generic.c
#define CARTRIDGE_NONE -1
#define CARTRIDGE_CRT 0
#define CARTRIDGE_ACTION_REPLAY 1
the following must match the CRT IDs
#define CARTRIDGE_KCS_POWER 2
kcs.c
#define CARTRIDGE_FINAL_III 3
final3.c
#define CARTRIDGE_SIMONS_BASIC 4
simonsbasic.c
#define CARTRIDGE_OCEAN 5
ocean.c
#define CARTRIDGE_EXPERT 6
expert.c
#define CARTRIDGE_FUNPLAY 7
funplay.c
#define CARTRIDGE_SUPER_GAMES 8
supergames.c
#define CARTRIDGE_ATOMIC_POWER 9
atomicpower.c
#define CARTRIDGE_EPYX_FASTLOAD 10
epyxfastload.c
#define CARTRIDGE_WESTERMANN 11
westermann.c
#define CARTRIDGE_REX 12
rexutility.c
#define CARTRIDGE_FINAL_I 13
final.c
#define CARTRIDGE_MAGIC_FORMEL 14
magicformel.c
#define CARTRIDGE_GS 15
gs.c
#define CARTRIDGE_WARPSPEED 16
warpspeed.c
#define CARTRIDGE_DINAMIC 17
dinamic.c
#define CARTRIDGE_ZAXXON 18
zaxxon.c
#define CARTRIDGE_MAGIC_DESK 19
magicdesk.c
#define CARTRIDGE_SUPER_SNAPSHOT_V5 20
supersnapshot.c
#define CARTRIDGE_COMAL80 21
comal80.c
#define CARTRIDGE_STRUCTURED_BASIC 22
stb.c
#define CARTRIDGE_ROSS 23
ross.c
#define CARTRIDGE_DELA_EP64 24
delaep64.c
#define CARTRIDGE_DELA_EP7x8 25
delaep7x8.c
#define CARTRIDGE_DELA_EP256 26
delaep256.c
#define CARTRIDGE_REX_EP256 27
rexep256.c
#define CARTRIDGE_MIKRO_ASSEMBLER 28
mikroass.c
#define CARTRIDGE_FINAL_PLUS 29
finalplus.c
#define CARTRIDGE_ACTION_REPLAY4 30
actionreplay4.c
#define CARTRIDGE_STARDOS 31
stardos.c
#define CARTRIDGE_EASYFLASH 32
easyflash.c
#define CARTRIDGE_EASYFLASH_XBANK 33
easyflash.c
#define CARTRIDGE_CAPTURE 34
capture.c
#define CARTRIDGE_ACTION_REPLAY3 35
actionreplay3.c
#define CARTRIDGE_RETRO_REPLAY 36
retroreplay.c
#define CARTRIDGE_MMC64 37
mmc64.c, spi-sdcard.c
#define CARTRIDGE_MMC_REPLAY 38
mmcreplay.c, ser-eeprom.c, spi-sdcard.c
#define CARTRIDGE_IDE64 39
ide64.c
#define CARTRIDGE_SUPER_SNAPSHOT 40
supersnapshot4.c
#define CARTRIDGE_IEEE488 41
c64tpi.c
#define CARTRIDGE_GAME_KILLER 42
gamekiller.c
#define CARTRIDGE_P64 43
prophet64.c
#define CARTRIDGE_EXOS 44
exos.c
#define CARTRIDGE_FREEZE_FRAME 45
freezeframe.c
#define CARTRIDGE_FREEZE_MACHINE 46
freezemachine.c
#define CARTRIDGE_SNAPSHOT64 47
snapshot64.c
#define CARTRIDGE_SUPER_EXPLODE_V5 48
superexplode5.c
#define CARTRIDGE_MAGIC_VOICE 49
magicvoice.c, tpicore.c, t6721.c
#define CARTRIDGE_ACTION_REPLAY2 50
actionreplay2.c
#define CARTRIDGE_MACH5 51
mach5.c
#define CARTRIDGE_DIASHOW_MAKER 52
diashowmaker.c
#define CARTRIDGE_PAGEFOX 53
pagefox.c
#define CARTRIDGE_KINGSOFT 54
kingsoft.c
#define CARTRIDGE_SILVERROCK_128 55
silverrock128.c
#define CARTRIDGE_FORMEL64 56
formel64.c
#define CARTRIDGE_RGCD 57
rgcd.c
#define CARTRIDGE_RRNETMK3 58
rrnetmk3.c
#define CARTRIDGE_EASYCALC 59
easycalc.c
#define CARTRIDGE_GMOD2 60
gmod2.c
#define CARTRIDGE_MAX_BASIC 61
maxbasic.c
#define CARTRIDGE_GMOD3 62
gmod3.c
#define CARTRIDGE_ZIPPCODE48 63
zippcode48.c
#define CARTRIDGE_BLACKBOX8 64
blackbox8.c
#define CARTRIDGE_BLACKBOX3 65
blackbox3.c
#define CARTRIDGE_BLACKBOX4 66
blackbox4.c
#define CARTRIDGE_REX_RAMFLOPPY 67
rexramfloppy.c
#define CARTRIDGE_BISPLUS 68
bisplus.c
#define CARTRIDGE_SDBOX 69
sdbox.c
#define CARTRIDGE_MULTIMAX 70
multimax.c
#define CARTRIDGE_BLACKBOX9 71
blackbox9.c
#define CARTRIDGE_LT_KERNAL 72
ltkernal.c
#define CARTRIDGE_RAMLINK 73
ramlink.c
#define CARTRIDGE_DREAN 74
drean.c
#define CARTRIDGE_IEEEFLASH64 75
ieeeflash64.c
#define CARTRIDGE_TURTLE_GRAPHICS_II 76
turtlegraphics.c
#define CARTRIDGE_FREEZE_FRAME_MK2 77
freezeframe2.c
#define CARTRIDGE_PARTNER64 78
partner64.c
#define CARTRIDGE_HYPERBASIC 79
hyperbasic.c
#define CARTRIDGE_LAST 79
cartconv: last cartridge in list
#define CARTRIDGE_NAME_ACIA "ACIA"
#define CARTRIDGE_NAME_ACTION_REPLAY "Action Replay V5"
http://rr.pokefinder.org/wiki/Action_Replay
#define CARTRIDGE_NAME_ACTION_REPLAY2 "Action Replay MK2"
http://rr.pokefinder.org/wiki/Action_Replay
#define CARTRIDGE_NAME_ACTION_REPLAY3 "Action Replay MK3"
http://rr.pokefinder.org/wiki/Action_Replay
#define CARTRIDGE_NAME_ACTION_REPLAY4 "Action Replay MK4"
http://rr.pokefinder.org/wiki/Action_Replay
#define CARTRIDGE_NAME_ATOMIC_POWER "Atomic Power" /* also: "Nordic Power" */
http://rr.pokefinder.org/wiki/Nordic_Power
#define CARTRIDGE_NAME_BISPLUS "BIS-Plus"
#define CARTRIDGE_NAME_BLACKBOX3 "Blackbox V3"
#define CARTRIDGE_NAME_BLACKBOX4 "Blackbox V4"
#define CARTRIDGE_NAME_BLACKBOX8 "Blackbox V8"
#define CARTRIDGE_NAME_BLACKBOX9 "Blackbox V9"
#define CARTRIDGE_NAME_GS "C64 Games System"
http://retro.lonningdal.net/home.php?page=Computers&select=c64gs&image=c64gs4.jpg
#define CARTRIDGE_NAME_CAPTURE "Capture"
see manual http://rr.pokefinder.org/wiki/Capture
#define CARTRIDGE_NAME_COMAL80 "Comal 80"
http://www.retroport.de/C64_C128_Hardware.html
#define CARTRIDGE_NAME_CPM "CP/M cartridge"
#define CARTRIDGE_NAME_DREAN "Drean"
#define CARTRIDGE_NAME_MIDI_DATEL "Datel MIDI"
#define CARTRIDGE_NAME_DEBUGCART "Debug Cartridge"
#define CARTRIDGE_NAME_DELA_EP64 "Dela EP64"
#define CARTRIDGE_NAME_DELA_EP7x8 "Dela EP7x8"
#define CARTRIDGE_NAME_DELA_EP256 "Dela EP256"
#define CARTRIDGE_NAME_DIASHOW_MAKER "Diashow-Maker"
http://www.retroport.de/Rex.html
#define CARTRIDGE_NAME_DIGIMAX "DigiMAX"
http://starbase.globalpc.net/~ezekowitz/vanessa/hobbies/projects.html
#define CARTRIDGE_NAME_DINAMIC "Dinamic"
#define CARTRIDGE_NAME_DQBB "Double Quick Brown Box"
on the cart itself its all uppercase ?
#define CARTRIDGE_NAME_DS12C887RTC "DS12C887 Real Time Clock"
Title of the page at http://ytm.bossstation.dnsalias.org/html/rtcds12c887.html.
#define CARTRIDGE_NAME_EASYCALC "Easy Calc Result"
on the cart itself it's "Calc Result EASY", in the manual it's EASYCALC, but we'll go with what is defined ;)
#define CARTRIDGE_NAME_EASYFLASH "EasyFlash"
see http://skoe.de/easyflash/
#define CARTRIDGE_NAME_EASYFLASH_XBANK "EasyFlash Xbank"
see http://skoe.de/easyflash/
#define CARTRIDGE_NAME_EPYX_FASTLOAD "Epyx FastLoad"
http://rr.pokefinder.org/wiki/Epyx_FastLoad
#define CARTRIDGE_NAME_ETHERNETCART "Ethernet cartridge"
#define CARTRIDGE_NAME_EXOS "EXOS"
http://rr.pokefinder.org/wiki/ExOS
#define CARTRIDGE_NAME_EXPERT "Expert Cartridge"
http://rr.pokefinder.org/wiki/Expert_Cartridge
#define CARTRIDGE_NAME_FINAL_I "The Final Cartridge"
http://rr.pokefinder.org/wiki/Final_Cartridge
#define CARTRIDGE_NAME_FINAL_III "The Final Cartridge III"
http://rr.pokefinder.org/wiki/Final_Cartridge
#define CARTRIDGE_NAME_FINAL_PLUS "Final Cartridge Plus"
http://rr.pokefinder.org/wiki/Final_Cartridge
#define CARTRIDGE_NAME_TFE "The Final Ethernet"
#define CARTRIDGE_NAME_FORMEL64 "Formel 64"
#define CARTRIDGE_NAME_FREEZE_FRAME "Freeze Frame"
http://rr.pokefinder.org/wiki/Freeze_Frame
#define CARTRIDGE_NAME_FREEZE_FRAME_MK2 "Freeze Frame MK2"
http://rr.pokefinder.org/wiki/Freeze_Frame
#define CARTRIDGE_NAME_FREEZE_MACHINE "Freeze Machine"
http://rr.pokefinder.org/wiki/Freeze_Frame
#define CARTRIDGE_NAME_FUNPLAY "Fun Play" /* also: "Power Play" */
http://home.nomansland.biz/~zerqent/commodore_salg/CIMG2132.JPG
#define CARTRIDGE_NAME_GAME_KILLER "Game Killer"
http://rr.pokefinder.org/wiki/Game_Killer
#define CARTRIDGE_NAME_GEORAM "GEO-RAM"
http://www.retroport.de/Rex.html
#define CARTRIDGE_NAME_GMOD2 "GMod2"
http://wiki.icomp.de/wiki/GMod2
#define CARTRIDGE_NAME_GMOD3 "GMod3"
http://wiki.icomp.de/wiki/GMod3
#define CARTRIDGE_NAME_HYPERBASIC "Hyper-BASIC"
#define CARTRIDGE_NAME_IDE64 "IDE64"
see http://www.ide64.org/
#define CARTRIDGE_NAME_IEEE488 "IEEE-488 Interface"
#define CARTRIDGE_NAME_IEEEFLASH64 "IEEE Flash! 64"
#define CARTRIDGE_NAME_ISEPIC "ISEPIC"
http://rr.pokefinder.org/wiki/Isepic
#define CARTRIDGE_NAME_KCS_POWER "KCS Power Cartridge"
http://rr.pokefinder.org/wiki/Power_Cartridge
#define CARTRIDGE_NAME_KINGSOFT "Kingsoft"
#define CARTRIDGE_NAME_LT_KERNAL "Lt. Kernal Host Adaptor"
#define CARTRIDGE_NAME_MACH5 "MACH 5"
http://rr.pokefinder.org/wiki/MACH_5
#define CARTRIDGE_NAME_MAGIC_DESK "Magic Desk"
also: "Domark, Hes Australia"
#define CARTRIDGE_NAME_MAGIC_FORMEL "Magic Formel"
http://rr.pokefinder.org/wiki/Magic_Formel
#define CARTRIDGE_NAME_MAGIC_VOICE "Magic Voice"
all lowercase on cart ?
#define CARTRIDGE_NAME_MIDI_MAPLIN "Maplin MIDI"
#define CARTRIDGE_NAME_MAX_BASIC "MAX Basic"
#define CARTRIDGE_NAME_MIKRO_ASSEMBLER "Mikro Assembler"
#define CARTRIDGE_NAME_MMC64 "MMC64"
see manual
#define CARTRIDGE_NAME_MMC_REPLAY "MMC Replay"
see manual
#define CARTRIDGE_NAME_MULTIMAX "MultiMAX"
http://www.multimax.co/
#define CARTRIDGE_NAME_MIDI_NAMESOFT "Namesoft MIDI"
#define CARTRIDGE_NAME_NORDIC_REPLAY "Nordic Replay"
"Retro Replay v2" see manual
#define CARTRIDGE_NAME_OCEAN "Ocean"
#define CARTRIDGE_NAME_PAGEFOX "Pagefox"
#define CARTRIDGE_NAME_PARTNER64 "Partner 64"
#define CARTRIDGE_NAME_MIDI_PASSPORT "Passport MIDI"
#define CARTRIDGE_NAME_P64 "Prophet64"
see http://www.prophet64.com/
#define CARTRIDGE_NAME_RAMCART "RamCart"
see cc65 driver
#define CARTRIDGE_NAME_RAMLINK "RAMLink"
#define CARTRIDGE_NAME_REU "RAM Expansion Module"
http://www.retroport.de/C64_C128_Hardware.html
#define CARTRIDGE_NAME_REX_EP256 "REX 256K EPROM Cart"
http://www.retroport.de/Rex.html
#define CARTRIDGE_NAME_REX "REX Utility"
#define CARTRIDGE_NAME_REX_RAMFLOPPY "REX RAM-Floppy"
#define CARTRIDGE_NAME_RGCD "RGCD"
#define CARTRIDGE_NAME_RRNET "RR-Net"
see manual
#define CARTRIDGE_NAME_RRNETMK3 "RR-Net MK3"
see manual
#define CARTRIDGE_NAME_RETRO_REPLAY "Retro Replay"
see manual
#define CARTRIDGE_NAME_ROSS "ROSS"
#define CARTRIDGE_NAME_SDBOX "SD-BOX"
http://c64.com.pl/index.php/sdbox106.html
#define CARTRIDGE_NAME_MIDI_SEQUENTIAL "Sequential MIDI"
#define CARTRIDGE_NAME_SFX_SOUND_EXPANDER "SFX Sound Expander"
http://www.floodgap.com/retrobits/ckb/secret/cbm-sfx-fmbport.jpg
#define CARTRIDGE_NAME_SFX_SOUND_SAMPLER "SFX Sound Sampler"
http://www.floodgap.com/retrobits/ckb/secret/cbm-ssm-box.jpg
#define CARTRIDGE_NAME_SILVERROCK_128 "Silverrock 128KiB Cartridge"
#define CARTRIDGE_NAME_SIMONS_BASIC "Simons' BASIC"
http://en.wikipedia.org/wiki/Simons'_BASIC
#define CARTRIDGE_NAME_SNAPSHOT64 "Snapshot 64"
http://rr.pokefinder.org/wiki/Super_Snapshot
#define CARTRIDGE_NAME_STARDOS "Stardos"
see manual http://rr.pokefinder.org/wiki/StarDOS
#define CARTRIDGE_NAME_STRUCTURED_BASIC "Structured BASIC"
#define CARTRIDGE_NAME_SUPER_EXPLODE_V5 "Super Explode V5.0"
http://rr.pokefinder.org/wiki/Super_Explode
#define CARTRIDGE_NAME_SUPER_GAMES "Super Games"
#define CARTRIDGE_NAME_SUPER_SNAPSHOT "Super Snapshot V4"
http://rr.pokefinder.org/wiki/Super_Snapshot
#define CARTRIDGE_NAME_SUPER_SNAPSHOT_V5 "Super Snapshot V5"
http://rr.pokefinder.org/wiki/Super_Snapshot
#define CARTRIDGE_NAME_SWIFTLINK "Swiftlink"
http://mikenaberezny.com/hardware/peripherals/swiftlink-rs232-interface/
#define CARTRIDGE_NAME_TURTLE_GRAPHICS_II "HES Turtle Graphics II"
#define CARTRIDGE_NAME_TURBO232 "Turbo232" /*!< also: "ACIA/SWIFTLINK" */ /*http://www.retroport.de/C64_C128_Hardware2.html */
#define CARTRIDGE_NAME_WARPSPEED "Warp Speed"
see manual http://rr.pokefinder.org/wiki/WarpSpeed
#define CARTRIDGE_NAME_WESTERMANN "Westermann Learning"
#define CARTRIDGE_NAME_ZAXXON "Zaxxon"
#define CARTRIDGE_NAME_ZIPPCODE48 "ZIPP-CODE 48"
#define CARTRIDGE_NAME_GENERIC_8KB "generic 8KiB game"
#define CARTRIDGE_NAME_GENERIC_16KB "generic 16KiB game"
#define CARTRIDGE_NAME_ULTIMAX "generic Ultimax"
#define CARTRIDGE_C128_FIRST_UNIQUE (CARTRIDGE_LAST + 1)
first unique number after the C64 cartridges
#define CARTRIDGE_C128_MAKEID(x) ((x) + CARTRIDGE_C128_FIRST_UNIQUE)
from CRT ID to internal ID
#define CARTRIDGE_C128_CRTID(x) ((x) - CARTRIDGE_C128_FIRST_UNIQUE)
from internal ID to CRT ID (for display)
#define CARTRIDGE_C128_ISID(x) ((x) >= CARTRIDGE_C128_FIRST_UNIQUE)
#define CARTRIDGE_C128_GENERIC 0
the following must match the CRT IDs
#define CARTRIDGE_C128_WARPSPEED128 1
#define CARTRIDGE_C128_PARTNER128 2
#define CARTRIDGE_C128_COMAL80 3
#define CARTRIDGE_C128_MAGICDESK128 4
#define CARTRIDGE_C128_GMOD2C128 5
#define CARTRIDGE_C128_LAST 5
#define CARTRIDGE_C128_NAME_GENERIC "generic function ROM"
#define CARTRIDGE_C128_NAME_GENERIC_16KB "generic 16KiB function ROM"
#define CARTRIDGE_C128_NAME_GENERIC_32KB "generic 32KiB function ROM"
#define CARTRIDGE_C128_NAME_COMAL80 "Comal 80 (C128)"
#define CARTRIDGE_C128_NAME_GMOD2C128 "Gmod2-C128"
#define CARTRIDGE_C128_NAME_MAGICDESK128 "Magic Desk 128"
#define CARTRIDGE_C128_NAME_PARTNER128 "Partner 128"
#define CARTRIDGE_C128_NAME_WARPSPEED128 "Warp Speed 128"
#define CARTRIDGE_VIC20_DIGIMAX -100
I/O only C64 cartridges can be used with the "Masquerade" adapter.
#define CARTRIDGE_VIC20_GEORAM -102
georam.c
#define CARTRIDGE_VIC20_SFX_SOUND_EXPANDER -106
sfx_soundexpander.c, fmopl.c
#define CARTRIDGE_VIC20_SFX_SOUND_SAMPLER -107
sfx_soundsampler.c
#define CARTRIDGE_VIC20_MIDI_PASSPORT -108
c64-midi.c
#define CARTRIDGE_VIC20_MIDI_DATEL -109
c64-midi.c
#define CARTRIDGE_VIC20_MIDI_SEQUENTIAL -110
c64-midi.c
#define CARTRIDGE_VIC20_MIDI_NAMESOFT -111
c64-midi.c
#define CARTRIDGE_VIC20_MIDI_MAPLIN -112
c64-midi.c
#define CARTRIDGE_VIC20_DS12C887RTC -113
ds12c887rtc.c
#define CARTRIDGE_VIC20_TFE -116
ethernetcart.c
#define CARTRIDGE_VIC20_TURBO232 -117
c64acia1.c
#define CARTRIDGE_VIC20_SWIFTLINK -118
c64acia1.c
#define CARTRIDGE_VIC20_ACIA -119
c64acia1.c
#define CARTRIDGE_VIC20_DEBUGCART -124
debugcart.c
#define CARTRIDGE_VIC20_GENERIC -2
generic.c
#define CARTRIDGE_VIC20_SIDCART -10
vic20-sidcart.c
#define CARTRIDGE_VIC20_IEEE488 -11
vic20-ieee488.c
#define CARTRIDGE_VIC20_IO2_RAM -12
ioramcart.c
#define CARTRIDGE_VIC20_IO3_RAM -13
ioramcart.c
#define CARTRIDGE_VIC20_MEGACART 1
the following must match the CRT IDs
#define CARTRIDGE_VIC20_BEHRBONZ 2
behrbonz.c
#define CARTRIDGE_VIC20_FP 3
vic-fp.c
#define CARTRIDGE_VIC20_UM 4
ultimem.c
#define CARTRIDGE_VIC20_FINAL_EXPANSION 5
finalexpansion.c
#define CARTRIDGE_VIC20_RABBIT 6
rabbit.c
#define CARTRIDGE_VIC20_SUPEREXPANDER 7
superexpander.c
#define CARTRIDGE_VIC20_MIKRO_ASSEMBLER 8
mikroassembler.c
#define CARTRIDGE_VIC20_LAST 8
cartconv: last cartridge in list
#define CARTRIDGE_VIC20_DETECT 0x8000
#define CARTRIDGE_VIC20_TYPEDEF(h, s1, s0, b1, b2, b3, b5) (0x8000 | ((h) << 6) | ((s1) << 5) | ((s0) << 4) | ((b1) << 3) | ((b2) << 2) | ((b3) << 1) | ((b5) << 0))
#define CARTRIDGE_VIC20_4KB_2000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 0, 1, 0, 0, 0)
block 1
#define CARTRIDGE_VIC20_8KB_2000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 1, 0, 0, 0)
#define CARTRIDGE_VIC20_4KB_3000 CARTRIDGE_VIC20_TYPEDEF(1, 1, 0, 1, 0, 0, 0)
#define CARTRIDGE_VIC20_4KB_4000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 0, 0, 1, 0, 0)
block 2
#define CARTRIDGE_VIC20_8KB_4000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 1, 0, 0)
#define CARTRIDGE_VIC20_4KB_5000 CARTRIDGE_VIC20_TYPEDEF(1, 1, 0, 0, 1, 0, 0)
#define CARTRIDGE_VIC20_4KB_6000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 0, 0, 0, 1, 0)
block 3
#define CARTRIDGE_VIC20_8KB_6000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 0, 1, 0)
#define CARTRIDGE_VIC20_4KB_7000 CARTRIDGE_VIC20_TYPEDEF(1, 1, 0, 0, 0, 1, 0)
#define CARTRIDGE_VIC20_4KB_A000 CARTRIDGE_VIC20_TYPEDEF(0, 0, 0, 0, 0, 0, 1)
block 5
#define CARTRIDGE_VIC20_8KB_A000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 0, 0, 1)
#define CARTRIDGE_VIC20_4KB_B000 CARTRIDGE_VIC20_TYPEDEF(1, 1, 0, 0, 0, 0, 1)
#define CARTRIDGE_VIC20_2KB_B000 CARTRIDGE_VIC20_TYPEDEF(1, 0, 1, 0, 0, 0, 1)
#define CARTRIDGE_VIC20_16KB_2000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 1, 1, 0, 0)
block 1 + block 2
#define CARTRIDGE_VIC20_16KB_2000_A000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 1, 0, 0, 1)
block 1 + block 5
#define CARTRIDGE_VIC20_16KB_4000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 1, 1, 0)
block 2 + block 3
#define CARTRIDGE_VIC20_16KB_4000_A000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 1, 0, 1)
block 2 + block 5
#define CARTRIDGE_VIC20_16KB_6000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 0, 1, 1)
block 3 + block 5
#define CARTRIDGE_VIC20_32KB_2000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 1, 1, 1, 1)
block 1,2,3,5
#define CARTRIDGE_VIC20_NAME_GENERIC "generic cartridge ROM"
list of canonical names for the VIC20 cartridges:
#define CARTRIDGE_VIC20_NAME_BEHRBONZ "Behr Bonz"
#define CARTRIDGE_VIC20_NAME_FINAL_EXPANSION "Final Expansion"
#define CARTRIDGE_VIC20_NAME_MEGACART "Mega-Cart"
http://mega-cart.com/
#define CARTRIDGE_VIC20_NAME_UM "UltiMem"
#define CARTRIDGE_VIC20_NAME_FP "Vic Flash Plugin"
http://www.ktverkko.fi/~msmakela/8bit/vfp/index.en.html
#define CARTRIDGE_VIC20_NAME_IO2_RAM "I/O-2 RAM"
#define CARTRIDGE_VIC20_NAME_IO3_RAM "I/O-3 RAM"
#define CARTRIDGE_VIC20_NAME_IEEE488 "VIC-1112 IEEE-488 Interface" /*https://sleepingelephant.com/denial/wiki/index.php/File:Chipitos.be-VIC-1112.jpg */
#define CARTRIDGE_VIC20_NAME_MIDI "MIDI"
#define CARTRIDGE_VIC20_NAME_SIDCART "SIDCART"
#define CARTRIDGE_VIC20_NAME_RABBIT "Rabbit Tape"
#define CARTRIDGE_VIC20_NAME_SUPEREXPANDER "Super Expander"
#define CARTRIDGE_VIC20_NAME_MIKRO_ASSEMBLER "Mikro Assembler"
#define CARTRIDGE_PLUS4_DIGIBLASTER -201
digiblaster.c
#define CARTRIDGE_PLUS4_SIDCART -200
plus4-sidcart.c
#define CARTRIDGE_PLUS4_GENERIC -2
plus4-generic.c
#define CARTRIDGE_PLUS4_MAGIC 1
c264 magic cart
#define CARTRIDGE_PLUS4_MULTI 2
plus4 multi cart
#define CARTRIDGE_PLUS4_JACINT1MB 3
1MB Cartridge
#define CARTRIDGE_PLUS4_LAST 3
#define CARTRIDGE_PLUS4_DETECT 0x8200
low byte must be 0x00
#define CARTRIDGE_PLUS4_GENERIC_TYPE_MASK 0x000f
#define CARTRIDGE_PLUS4_IS_GENERIC(x) (((x) & 0xff00) == 0x8200)
#define CARTRIDGE_PLUS4_GENERIC_C1LO 0x8201
#define CARTRIDGE_PLUS4_GENERIC_C1HI 0x8202
#define CARTRIDGE_PLUS4_GENERIC_C2LO 0x8204
#define CARTRIDGE_PLUS4_GENERIC_C2HI 0x8208
#define CARTRIDGE_PLUS4_GENERIC_C1 (CARTRIDGE_PLUS4_GENERIC_C1LO | CARTRIDGE_PLUS4_GENERIC_C1HI)
#define CARTRIDGE_PLUS4_GENERIC_C2 (CARTRIDGE_PLUS4_GENERIC_C2LO | CARTRIDGE_PLUS4_GENERIC_C2HI)
#define CARTRIDGE_PLUS4_GENERIC_ALL (CARTRIDGE_PLUS4_GENERIC_C1 | CARTRIDGE_PLUS4_GENERIC_C2)
#define CARTRIDGE_PLUS4_NAME_GENERIC "generic cartridge ROM"
list of canonical names for the Plus4 cartridges:
#define CARTRIDGE_PLUS4_NAME_DIGIBLASTER "Digiblaster Add-on"
#define CARTRIDGE_PLUS4_NAME_SIDCART "SID cartridge"
#define CARTRIDGE_PLUS4_NAME_JACINT1MB "1MB Cartridge"
#define CARTRIDGE_PLUS4_NAME_MAGIC "c264 magic cart"
#define CARTRIDGE_PLUS4_NAME_MULTI "Plus4 multi cart"
#define CARTRIDGE_CBM2_GENERIC -2
cbm2-generic.c
#define CARTRIDGE_CBM2_LAST 0
#define CARTRIDGE_CBM2_DETECT 0x8200
not implemented yet
#define CARTRIDGE_CBM2_GENERIC_TYPE_MASK 0x000f
#define CARTRIDGE_CBM2_IS_GENERIC(x) (((x) & 0xff00) == 0x8200)
#define CARTRIDGE_CBM2_GENERIC_C1 0x8201
4kb at 0x1000
#define CARTRIDGE_CBM2_GENERIC_C2 0x8202
8kb at 0x2000
#define CARTRIDGE_CBM2_GENERIC_C4 0x8204
8kb at 0x4000
#define CARTRIDGE_CBM2_GENERIC_C6 0x8208
8kb at 0x6000
#define CARTRIDGE_CBM2_NAME_GENERIC "generic cartridge ROM"
list of canonical names for the CBM2 cartridges:
#define CARTRIDGE_SIZE_2KB 0x00000800
#define CARTRIDGE_SIZE_4KB 0x00001000
#define CARTRIDGE_SIZE_8KB 0x00002000
#define CARTRIDGE_SIZE_12KB 0x00003000
#define CARTRIDGE_SIZE_16KB 0x00004000
#define CARTRIDGE_SIZE_20KB 0x00005000
#define CARTRIDGE_SIZE_24KB 0x00006000
#define CARTRIDGE_SIZE_32KB 0x00008000
#define CARTRIDGE_SIZE_64KB 0x00010000
#define CARTRIDGE_SIZE_96KB 0x00018000
#define CARTRIDGE_SIZE_128KB 0x00020000
#define CARTRIDGE_SIZE_256KB 0x00040000
#define CARTRIDGE_SIZE_512KB 0x00080000
#define CARTRIDGE_SIZE_1024KB 0x00100000
#define CARTRIDGE_SIZE_2048KB 0x00200000
#define CARTRIDGE_SIZE_4096KB 0x00400000
#define CARTRIDGE_SIZE_8192KB 0x00800000
#define CARTRIDGE_SIZE_16384KB 0x01000000
#define CARTRIDGE_SIZE_MAX CARTRIDGE_SIZE_16384KB
#define CARTRIDGE_SIZE_1MB CARTRIDGE_SIZE_1024KB
for convenience
#define CARTRIDGE_SIZE_2MB CARTRIDGE_SIZE_2048KB
#define CARTRIDGE_SIZE_4MB CARTRIDGE_SIZE_4096KB
#define CARTRIDGE_SIZE_8MB CARTRIDGE_SIZE_8192KB
#define CARTRIDGE_SIZE_16MB CARTRIDGE_SIZE_16384KB
#define CARTRIDGE_FILETYPE_BIN 1
#define CARTRIDGE_FILETYPE_CRT 2
#define CARTRIDGE_GROUP_GENERIC 0x0001
#define CARTRIDGE_GROUP_RAMEX 0x0002
#define CARTRIDGE_GROUP_FREEZER 0x0004
#define CARTRIDGE_GROUP_GAME 0x0008
#define CARTRIDGE_GROUP_UTIL 0x0010
Functions
void cartridge_init (void)
init the cartridge system
int cartridge_resources_init (void)
int cartridge_cmdline_options_init (void)
void cartridge_shutdown (void)
shutdown the cartridge system
void cartridge_resources_shutdown (void)
void cartridge_init_config (void)
init the cartridge config so the cartridge can start (or whatever)
int cartridge_detect (const char *filename)
detect cartridge type (takes crt and bin files)
int cartridge_attach_image (int type, const char *filename)
attach (and enable) a cartridge by type and filename (takes crt and bin files)
int cartridge_enable (int type)
int cartridge_disable (int type)
disable cartridge by type
void cartridge_detach_image (int type)
detaches/disables the cartridge with the associated id.
int cartridge_get_id (int slot)
char * cartridge_get_filename_by_slot (int slot)
char * cartridge_get_secondary_filename_by_slot (int slot)
void cartridge_set_default (void)
set current "Main Slot" cart as default
void cartridge_unset_default (void)
called from resources_set_defaults()
void cartridge_reset (void)
reset button pressed in UI
void cartridge_powerup (void)
powerup / hardreset
void cartridge_trigger_freeze (void)
freeze button pressed in UI
void cartridge_trigger_freeze_nmi_only (void)
trigger a freeze, but don't trigger the cartridge logic (which might release it).
void cartridge_release_freeze (void)
const char * cartridge_get_filename_by_type (int type)
int cartridge_type_enabled (int type)
int cartridge_save_image (int type, const char *filename)
save the primary (rom/ram)image of the give cart type to a file
int cartridge_bin_save (int type, const char *filename)
int cartridge_crt_save (int type, const char *filename)
int cartridge_flush_image (int type)
int cartridge_can_flush_image (int crtid)
returns 1 when cartridge (ROM) image can be flushed
int cartridge_can_save_image (int crtid)
returns 1 when cartridge (ROM) image can be saved
int cartridge_save_secondary_image (int type, const char *filename)
save the secondary image of the give cart type to a file
int cartridge_flush_secondary_image (int type)
int cartridge_can_flush_secondary_image (int crtid)
int cartridge_can_save_secondary_image (int crtid)
int cartridge_snapshot_read_modules (struct snapshot_s *s)
int cartridge_snapshot_write_modules (struct snapshot_s *s)
void cartridge_setup_context (struct machine_context_s *machine_context)
uint8_t cartridge_peek_mem (uint16_t addr)
generic cartridge memory peek for the monitor
void cartridge_mmu_translate (unsigned int addr, uint8_t **base, int *start, int *limit)
mmu translation
void cartridge_ram_init (void)
Initialize RAM for power-up.
void cartridge_sound_chip_init (void)
cartridge_info_t * cartridge_get_info_list (void)
Macro Definition Documentation
CARTRIDGE_ACIA
#define CARTRIDGE_ACIA -119
c64acia1.c
CARTRIDGE_ACTION_REPLAY
#define CARTRIDGE_ACTION_REPLAY 1
the following must match the CRT IDs
actionreplay.c
CARTRIDGE_ACTION_REPLAY2
#define CARTRIDGE_ACTION_REPLAY2 50
actionreplay2.c
CARTRIDGE_ACTION_REPLAY3
#define CARTRIDGE_ACTION_REPLAY3 35
actionreplay3.c
CARTRIDGE_ACTION_REPLAY4
#define CARTRIDGE_ACTION_REPLAY4 30
actionreplay4.c
CARTRIDGE_ATOMIC_POWER
#define CARTRIDGE_ATOMIC_POWER 9
atomicpower.c
CARTRIDGE_BISPLUS
#define CARTRIDGE_BISPLUS 68
bisplus.c
CARTRIDGE_BLACKBOX3
#define CARTRIDGE_BLACKBOX3 65
blackbox3.c
CARTRIDGE_BLACKBOX4
#define CARTRIDGE_BLACKBOX4 66
blackbox4.c
CARTRIDGE_BLACKBOX8
#define CARTRIDGE_BLACKBOX8 64
blackbox8.c
CARTRIDGE_BLACKBOX9
#define CARTRIDGE_BLACKBOX9 71
blackbox9.c
CARTRIDGE_C128_COMAL80
#define CARTRIDGE_C128_COMAL80 3
CARTRIDGE_C128_CRTID
#define CARTRIDGE_C128_CRTID (x) ((x) - CARTRIDGE_C128_FIRST_UNIQUE)
from internal ID to CRT ID (for display)
CARTRIDGE_C128_FIRST_UNIQUE
#define CARTRIDGE_C128_FIRST_UNIQUE (CARTRIDGE_LAST + 1)
first unique number after the C64 cartridges
CARTRIDGE_C128_GENERIC
#define CARTRIDGE_C128_GENERIC 0
the following must match the CRT IDs
external function rom
CARTRIDGE_C128_GMOD2C128
#define CARTRIDGE_C128_GMOD2C128 5
CARTRIDGE_C128_ISID
#define CARTRIDGE_C128_ISID (x) ((x) >= CARTRIDGE_C128_FIRST_UNIQUE)
CARTRIDGE_C128_LAST
#define CARTRIDGE_C128_LAST 5
CARTRIDGE_C128_MAGICDESK128
#define CARTRIDGE_C128_MAGICDESK128 4
CARTRIDGE_C128_MAKEID
#define CARTRIDGE_C128_MAKEID (x) ((x) + CARTRIDGE_C128_FIRST_UNIQUE)
from CRT ID to internal ID
CARTRIDGE_C128_NAME_COMAL80
#define CARTRIDGE_C128_NAME_COMAL80 "Comal 80 (C128)"
CARTRIDGE_C128_NAME_GENERIC
#define CARTRIDGE_C128_NAME_GENERIC "generic function ROM"
CARTRIDGE_C128_NAME_GENERIC_16KB
#define CARTRIDGE_C128_NAME_GENERIC_16KB "generic 16KiB function ROM"
CARTRIDGE_C128_NAME_GENERIC_32KB
#define CARTRIDGE_C128_NAME_GENERIC_32KB "generic 32KiB function ROM"
CARTRIDGE_C128_NAME_GMOD2C128
#define CARTRIDGE_C128_NAME_GMOD2C128 "Gmod2-C128"
CARTRIDGE_C128_NAME_MAGICDESK128
#define CARTRIDGE_C128_NAME_MAGICDESK128 "Magic Desk 128"
CARTRIDGE_C128_NAME_PARTNER128
#define CARTRIDGE_C128_NAME_PARTNER128 "Partner 128"
CARTRIDGE_C128_NAME_WARPSPEED128
#define CARTRIDGE_C128_NAME_WARPSPEED128 "Warp Speed 128"
CARTRIDGE_C128_PARTNER128
#define CARTRIDGE_C128_PARTNER128 2
CARTRIDGE_C128_WARPSPEED128
#define CARTRIDGE_C128_WARPSPEED128 1
CARTRIDGE_C64_256K
#define CARTRIDGE_C64_256K -122
c64_256k.c
CARTRIDGE_CAPTURE
#define CARTRIDGE_CAPTURE 34
capture.c
CARTRIDGE_CBM2_DETECT
#define CARTRIDGE_CBM2_DETECT 0x8200
not implemented yet
CARTRIDGE_CBM2_GENERIC
#define CARTRIDGE_CBM2_GENERIC -2
cbm2-generic.c
CARTRIDGE_CBM2_GENERIC_C1
#define CARTRIDGE_CBM2_GENERIC_C1 0x8201
4kb at 0x1000
CARTRIDGE_CBM2_GENERIC_C2
#define CARTRIDGE_CBM2_GENERIC_C2 0x8202
8kb at 0x2000
CARTRIDGE_CBM2_GENERIC_C4
#define CARTRIDGE_CBM2_GENERIC_C4 0x8204
8kb at 0x4000
CARTRIDGE_CBM2_GENERIC_C6
#define CARTRIDGE_CBM2_GENERIC_C6 0x8208
8kb at 0x6000
CARTRIDGE_CBM2_GENERIC_TYPE_MASK
#define CARTRIDGE_CBM2_GENERIC_TYPE_MASK 0x000f
CARTRIDGE_CBM2_IS_GENERIC
#define CARTRIDGE_CBM2_IS_GENERIC (x) (((x) & 0xff00) == 0x8200)
CARTRIDGE_CBM2_LAST
#define CARTRIDGE_CBM2_LAST 0
CARTRIDGE_CBM2_NAME_GENERIC
#define CARTRIDGE_CBM2_NAME_GENERIC "generic cartridge ROM"
list of canonical names for the CBM2 cartridges:
CARTRIDGE_COMAL80
#define CARTRIDGE_COMAL80 21
comal80.c
CARTRIDGE_CPM
#define CARTRIDGE_CPM -123
cpmcart.c
CARTRIDGE_CRT
#define CARTRIDGE_CRT 0
CARTRIDGE_DEBUGCART
#define CARTRIDGE_DEBUGCART -124
debugcart.c
CARTRIDGE_DELA_EP256
#define CARTRIDGE_DELA_EP256 26
delaep256.c
CARTRIDGE_DELA_EP64
#define CARTRIDGE_DELA_EP64 24
delaep64.c
CARTRIDGE_DELA_EP7x8
#define CARTRIDGE_DELA_EP7x8 25
delaep7x8.c
CARTRIDGE_DIASHOW_MAKER
#define CARTRIDGE_DIASHOW_MAKER 52
diashowmaker.c
CARTRIDGE_DIGIMAX
#define CARTRIDGE_DIGIMAX -100
Carts that don't have a rom image.
digimax.c
CARTRIDGE_DINAMIC
#define CARTRIDGE_DINAMIC 17
dinamic.c
CARTRIDGE_DQBB
#define CARTRIDGE_DQBB -101
dqbb.c
CARTRIDGE_DREAN
#define CARTRIDGE_DREAN 74
drean.c
CARTRIDGE_DS12C887RTC
#define CARTRIDGE_DS12C887RTC -113
ds12c887rtc.c
CARTRIDGE_EASYCALC
#define CARTRIDGE_EASYCALC 59
easycalc.c
CARTRIDGE_EASYFLASH
#define CARTRIDGE_EASYFLASH 32
easyflash.c
CARTRIDGE_EASYFLASH_XBANK
#define CARTRIDGE_EASYFLASH_XBANK 33
easyflash.c
Todo:
cartconv (no cart exists?)
CARTRIDGE_EPYX_FASTLOAD
#define CARTRIDGE_EPYX_FASTLOAD 10
epyxfastload.c
CARTRIDGE_EXOS
#define CARTRIDGE_EXOS 44
exos.c
CARTRIDGE_EXPERT
#define CARTRIDGE_EXPERT 6
expert.c
CARTRIDGE_FILETYPE_BIN
#define CARTRIDGE_FILETYPE_BIN 1
CARTRIDGE_FILETYPE_CRT
#define CARTRIDGE_FILETYPE_CRT 2
CARTRIDGE_FINAL_I
#define CARTRIDGE_FINAL_I 13
final.c
CARTRIDGE_FINAL_III
#define CARTRIDGE_FINAL_III 3
final3.c
CARTRIDGE_FINAL_PLUS
#define CARTRIDGE_FINAL_PLUS 29
finalplus.c
Todo:
cartconv (24k binary)
CARTRIDGE_FORMEL64
#define CARTRIDGE_FORMEL64 56
formel64.c
CARTRIDGE_FREEZE_FRAME
#define CARTRIDGE_FREEZE_FRAME 45
freezeframe.c
CARTRIDGE_FREEZE_FRAME_MK2
#define CARTRIDGE_FREEZE_FRAME_MK2 77
freezeframe2.c
CARTRIDGE_FREEZE_MACHINE
#define CARTRIDGE_FREEZE_MACHINE 46
freezemachine.c
CARTRIDGE_FUNPLAY
#define CARTRIDGE_FUNPLAY 7
funplay.c
CARTRIDGE_GAME_KILLER
#define CARTRIDGE_GAME_KILLER 42
gamekiller.c
CARTRIDGE_GENERIC_16KB
#define CARTRIDGE_GENERIC_16KB -2
generic.c
CARTRIDGE_GENERIC_8KB
#define CARTRIDGE_GENERIC_8KB -3
generic.c
CARTRIDGE_GEORAM
#define CARTRIDGE_GEORAM -102
georam.c
CARTRIDGE_GMOD2
#define CARTRIDGE_GMOD2 60
gmod2.c
CARTRIDGE_GMOD3
#define CARTRIDGE_GMOD3 62
gmod3.c
CARTRIDGE_GROUP_FREEZER
#define CARTRIDGE_GROUP_FREEZER 0x0004
CARTRIDGE_GROUP_GAME
#define CARTRIDGE_GROUP_GAME 0x0008
CARTRIDGE_GROUP_GENERIC
#define CARTRIDGE_GROUP_GENERIC 0x0001
CARTRIDGE_GROUP_RAMEX
#define CARTRIDGE_GROUP_RAMEX 0x0002
CARTRIDGE_GROUP_UTIL
#define CARTRIDGE_GROUP_UTIL 0x0010
CARTRIDGE_GS
#define CARTRIDGE_GS 15
gs.c
CARTRIDGE_HYPERBASIC
#define CARTRIDGE_HYPERBASIC 79
hyperbasic.c
CARTRIDGE_IDE64
#define CARTRIDGE_IDE64 39
ide64.c
CARTRIDGE_IEEE488
#define CARTRIDGE_IEEE488 41
c64tpi.c
CARTRIDGE_IEEEFLASH64
#define CARTRIDGE_IEEEFLASH64 75
ieeeflash64.c
CARTRIDGE_ISEPIC
#define CARTRIDGE_ISEPIC -103
isepic.c
CARTRIDGE_KCS_POWER
#define CARTRIDGE_KCS_POWER 2
kcs.c
CARTRIDGE_KINGSOFT
#define CARTRIDGE_KINGSOFT 54
kingsoft.c
CARTRIDGE_LAST
#define CARTRIDGE_LAST 79
cartconv: last cartridge in list
CARTRIDGE_LT_KERNAL
#define CARTRIDGE_LT_KERNAL 72
ltkernal.c
CARTRIDGE_MACH5
#define CARTRIDGE_MACH5 51
mach5.c
CARTRIDGE_MAGIC_DESK
#define CARTRIDGE_MAGIC_DESK 19
magicdesk.c
CARTRIDGE_MAGIC_FORMEL
#define CARTRIDGE_MAGIC_FORMEL 14
magicformel.c
CARTRIDGE_MAGIC_VOICE
#define CARTRIDGE_MAGIC_VOICE 49
magicvoice.c, tpicore.c, t6721.c
CARTRIDGE_MAX_BASIC
#define CARTRIDGE_MAX_BASIC 61
maxbasic.c
CARTRIDGE_MIDI_DATEL
#define CARTRIDGE_MIDI_DATEL -109
c64-midi.c
CARTRIDGE_MIDI_MAPLIN
#define CARTRIDGE_MIDI_MAPLIN -112
c64-midi.c
CARTRIDGE_MIDI_NAMESOFT
#define CARTRIDGE_MIDI_NAMESOFT -111
c64-midi.c
CARTRIDGE_MIDI_PASSPORT
#define CARTRIDGE_MIDI_PASSPORT -108
c64-midi.c
CARTRIDGE_MIDI_SEQUENTIAL
#define CARTRIDGE_MIDI_SEQUENTIAL -110
c64-midi.c
CARTRIDGE_MIKRO_ASSEMBLER
#define CARTRIDGE_MIKRO_ASSEMBLER 28
mikroass.c
CARTRIDGE_MMC64
#define CARTRIDGE_MMC64 37
mmc64.c, spi-sdcard.c
CARTRIDGE_MMC_REPLAY
#define CARTRIDGE_MMC_REPLAY 38
mmcreplay.c, ser-eeprom.c, spi-sdcard.c
CARTRIDGE_MULTIMAX
#define CARTRIDGE_MULTIMAX 70
multimax.c
CARTRIDGE_NAME_ACIA
#define CARTRIDGE_NAME_ACIA "ACIA"
CARTRIDGE_NAME_ACTION_REPLAY
#define CARTRIDGE_NAME_ACTION_REPLAY "Action Replay V5"
http://rr.pokefinder.org/wiki/Action_Replay
CARTRIDGE_NAME_ACTION_REPLAY2
#define CARTRIDGE_NAME_ACTION_REPLAY2 "Action Replay MK2"
http://rr.pokefinder.org/wiki/Action_Replay
CARTRIDGE_NAME_ACTION_REPLAY3
#define CARTRIDGE_NAME_ACTION_REPLAY3 "Action Replay MK3"
http://rr.pokefinder.org/wiki/Action_Replay
CARTRIDGE_NAME_ACTION_REPLAY4
#define CARTRIDGE_NAME_ACTION_REPLAY4 "Action Replay MK4"
http://rr.pokefinder.org/wiki/Action_Replay
CARTRIDGE_NAME_ATOMIC_POWER
#define CARTRIDGE_NAME_ATOMIC_POWER "Atomic Power" /* also: "Nordic Power" */
http://rr.pokefinder.org/wiki/Nordic_Power
CARTRIDGE_NAME_BISPLUS
#define CARTRIDGE_NAME_BISPLUS "BIS-Plus"
CARTRIDGE_NAME_BLACKBOX3
#define CARTRIDGE_NAME_BLACKBOX3 "Blackbox V3"
CARTRIDGE_NAME_BLACKBOX4
#define CARTRIDGE_NAME_BLACKBOX4 "Blackbox V4"
CARTRIDGE_NAME_BLACKBOX8
#define CARTRIDGE_NAME_BLACKBOX8 "Blackbox V8"
CARTRIDGE_NAME_BLACKBOX9
#define CARTRIDGE_NAME_BLACKBOX9 "Blackbox V9"
CARTRIDGE_NAME_CAPTURE
#define CARTRIDGE_NAME_CAPTURE "Capture"
see manual http://rr.pokefinder.org/wiki/Capture
CARTRIDGE_NAME_COMAL80
#define CARTRIDGE_NAME_COMAL80 "Comal 80"
http://www.retroport.de/C64_C128_Hardware.html
CARTRIDGE_NAME_CPM
#define CARTRIDGE_NAME_CPM "CP/M cartridge"
CARTRIDGE_NAME_DEBUGCART
#define CARTRIDGE_NAME_DEBUGCART "Debug Cartridge"
CARTRIDGE_NAME_DELA_EP256
#define CARTRIDGE_NAME_DELA_EP256 "Dela EP256"
CARTRIDGE_NAME_DELA_EP64
#define CARTRIDGE_NAME_DELA_EP64 "Dela EP64"
CARTRIDGE_NAME_DELA_EP7x8
#define CARTRIDGE_NAME_DELA_EP7x8 "Dela EP7x8"
CARTRIDGE_NAME_DIASHOW_MAKER
#define CARTRIDGE_NAME_DIASHOW_MAKER "Diashow-Maker"
http://www.retroport.de/Rex.html
CARTRIDGE_NAME_DIGIMAX
#define CARTRIDGE_NAME_DIGIMAX "DigiMAX"
http://starbase.globalpc.net/~ezekowitz/vanessa/hobbies/projects.html
CARTRIDGE_NAME_DINAMIC
#define CARTRIDGE_NAME_DINAMIC "Dinamic"
CARTRIDGE_NAME_DQBB
#define CARTRIDGE_NAME_DQBB "Double Quick Brown Box"
on the cart itself its all uppercase ?
CARTRIDGE_NAME_DREAN
#define CARTRIDGE_NAME_DREAN "Drean"
CARTRIDGE_NAME_DS12C887RTC
#define CARTRIDGE_NAME_DS12C887RTC "DS12C887 Real Time Clock"
Title of the page at http://ytm.bossstation.dnsalias.org/html/rtcds12c887.html.
CARTRIDGE_NAME_EASYCALC
#define CARTRIDGE_NAME_EASYCALC "Easy Calc Result"
on the cart itself it's "Calc Result EASY", in the manual it's EASYCALC, but we'll go with what is defined ;)
CARTRIDGE_NAME_EASYFLASH
#define CARTRIDGE_NAME_EASYFLASH "EasyFlash"
see http://skoe.de/easyflash/
CARTRIDGE_NAME_EASYFLASH_XBANK
#define CARTRIDGE_NAME_EASYFLASH_XBANK "EasyFlash Xbank"
see http://skoe.de/easyflash/
CARTRIDGE_NAME_EPYX_FASTLOAD
#define CARTRIDGE_NAME_EPYX_FASTLOAD "Epyx FastLoad"
http://rr.pokefinder.org/wiki/Epyx_FastLoad
CARTRIDGE_NAME_ETHERNETCART
#define CARTRIDGE_NAME_ETHERNETCART "Ethernet cartridge"
CARTRIDGE_NAME_EXOS
#define CARTRIDGE_NAME_EXOS "EXOS"
http://rr.pokefinder.org/wiki/ExOS
CARTRIDGE_NAME_EXPERT
#define CARTRIDGE_NAME_EXPERT "Expert Cartridge"
http://rr.pokefinder.org/wiki/Expert_Cartridge
CARTRIDGE_NAME_FINAL_I
#define CARTRIDGE_NAME_FINAL_I "The Final Cartridge"
http://rr.pokefinder.org/wiki/Final_Cartridge
CARTRIDGE_NAME_FINAL_III
#define CARTRIDGE_NAME_FINAL_III "The Final Cartridge III"
http://rr.pokefinder.org/wiki/Final_Cartridge
CARTRIDGE_NAME_FINAL_PLUS
#define CARTRIDGE_NAME_FINAL_PLUS "Final Cartridge Plus"
http://rr.pokefinder.org/wiki/Final_Cartridge
CARTRIDGE_NAME_FORMEL64
#define CARTRIDGE_NAME_FORMEL64 "Formel 64"
CARTRIDGE_NAME_FREEZE_FRAME
#define CARTRIDGE_NAME_FREEZE_FRAME "Freeze Frame"
http://rr.pokefinder.org/wiki/Freeze_Frame
CARTRIDGE_NAME_FREEZE_FRAME_MK2
#define CARTRIDGE_NAME_FREEZE_FRAME_MK2 "Freeze Frame MK2"
http://rr.pokefinder.org/wiki/Freeze_Frame
CARTRIDGE_NAME_FREEZE_MACHINE
#define CARTRIDGE_NAME_FREEZE_MACHINE "Freeze Machine"
http://rr.pokefinder.org/wiki/Freeze_Frame
CARTRIDGE_NAME_FUNPLAY
#define CARTRIDGE_NAME_FUNPLAY "Fun Play" /* also: "Power Play" */
http://home.nomansland.biz/~zerqent/commodore_salg/CIMG2132.JPG
CARTRIDGE_NAME_GAME_KILLER
#define CARTRIDGE_NAME_GAME_KILLER "Game Killer"
http://rr.pokefinder.org/wiki/Game_Killer
CARTRIDGE_NAME_GENERIC_16KB
#define CARTRIDGE_NAME_GENERIC_16KB "generic 16KiB game"
CARTRIDGE_NAME_GENERIC_8KB
#define CARTRIDGE_NAME_GENERIC_8KB "generic 8KiB game"
CARTRIDGE_NAME_GEORAM
#define CARTRIDGE_NAME_GEORAM "GEO-RAM"
http://www.retroport.de/Rex.html
CARTRIDGE_NAME_GMOD2
#define CARTRIDGE_NAME_GMOD2 "GMod2"
http://wiki.icomp.de/wiki/GMod2
CARTRIDGE_NAME_GMOD3
#define CARTRIDGE_NAME_GMOD3 "GMod3"
http://wiki.icomp.de/wiki/GMod3
CARTRIDGE_NAME_GS
#define CARTRIDGE_NAME_GS "C64 Games System"
http://retro.lonningdal.net/home.php?page=Computers&select=c64gs&image=c64gs4.jpg
CARTRIDGE_NAME_HYPERBASIC
#define CARTRIDGE_NAME_HYPERBASIC "Hyper-BASIC"
CARTRIDGE_NAME_IDE64
#define CARTRIDGE_NAME_IDE64 "IDE64"
see http://www.ide64.org/
CARTRIDGE_NAME_IEEE488
#define CARTRIDGE_NAME_IEEE488 "IEEE-488 Interface"
CARTRIDGE_NAME_IEEEFLASH64
#define CARTRIDGE_NAME_IEEEFLASH64 "IEEE Flash! 64"
CARTRIDGE_NAME_ISEPIC
#define CARTRIDGE_NAME_ISEPIC "ISEPIC"
http://rr.pokefinder.org/wiki/Isepic
CARTRIDGE_NAME_KCS_POWER
#define CARTRIDGE_NAME_KCS_POWER "KCS Power Cartridge"
http://rr.pokefinder.org/wiki/Power_Cartridge
CARTRIDGE_NAME_KINGSOFT
#define CARTRIDGE_NAME_KINGSOFT "Kingsoft"
CARTRIDGE_NAME_LT_KERNAL
#define CARTRIDGE_NAME_LT_KERNAL "Lt. Kernal Host Adaptor"
CARTRIDGE_NAME_MACH5
#define CARTRIDGE_NAME_MACH5 "MACH 5"
http://rr.pokefinder.org/wiki/MACH_5
CARTRIDGE_NAME_MAGIC_DESK
#define CARTRIDGE_NAME_MAGIC_DESK "Magic Desk"
also: "Domark, Hes Australia"
CARTRIDGE_NAME_MAGIC_FORMEL
#define CARTRIDGE_NAME_MAGIC_FORMEL "Magic Formel"
http://rr.pokefinder.org/wiki/Magic_Formel
CARTRIDGE_NAME_MAGIC_VOICE
#define CARTRIDGE_NAME_MAGIC_VOICE "Magic Voice"
all lowercase on cart ?
CARTRIDGE_NAME_MAX_BASIC
#define CARTRIDGE_NAME_MAX_BASIC "MAX Basic"
CARTRIDGE_NAME_MIDI_DATEL
#define CARTRIDGE_NAME_MIDI_DATEL "Datel MIDI"
CARTRIDGE_NAME_MIDI_MAPLIN
#define CARTRIDGE_NAME_MIDI_MAPLIN "Maplin MIDI"
CARTRIDGE_NAME_MIDI_NAMESOFT
#define CARTRIDGE_NAME_MIDI_NAMESOFT "Namesoft MIDI"
CARTRIDGE_NAME_MIDI_PASSPORT
#define CARTRIDGE_NAME_MIDI_PASSPORT "Passport MIDI"
CARTRIDGE_NAME_MIDI_SEQUENTIAL
#define CARTRIDGE_NAME_MIDI_SEQUENTIAL "Sequential MIDI"
CARTRIDGE_NAME_MIKRO_ASSEMBLER
#define CARTRIDGE_NAME_MIKRO_ASSEMBLER "Mikro Assembler"
CARTRIDGE_NAME_MMC64
#define CARTRIDGE_NAME_MMC64 "MMC64"
see manual
CARTRIDGE_NAME_MMC_REPLAY
#define CARTRIDGE_NAME_MMC_REPLAY "MMC Replay"
see manual
CARTRIDGE_NAME_MULTIMAX
#define CARTRIDGE_NAME_MULTIMAX "MultiMAX"
http://www.multimax.co/
CARTRIDGE_NAME_NORDIC_REPLAY
#define CARTRIDGE_NAME_NORDIC_REPLAY "Nordic Replay"
"Retro Replay v2" see manual
CARTRIDGE_NAME_OCEAN
#define CARTRIDGE_NAME_OCEAN "Ocean"
CARTRIDGE_NAME_P64
#define CARTRIDGE_NAME_P64 "Prophet64"
see http://www.prophet64.com/
CARTRIDGE_NAME_PAGEFOX
#define CARTRIDGE_NAME_PAGEFOX "Pagefox"
CARTRIDGE_NAME_PARTNER64
#define CARTRIDGE_NAME_PARTNER64 "Partner 64"
CARTRIDGE_NAME_RAMCART
#define CARTRIDGE_NAME_RAMCART "RamCart"
see cc65 driver
CARTRIDGE_NAME_RAMLINK
#define CARTRIDGE_NAME_RAMLINK "RAMLink"
CARTRIDGE_NAME_RETRO_REPLAY
#define CARTRIDGE_NAME_RETRO_REPLAY "Retro Replay"
see manual
CARTRIDGE_NAME_REU
#define CARTRIDGE_NAME_REU "RAM Expansion Module"
http://www.retroport.de/C64_C128_Hardware.html
CARTRIDGE_NAME_REX
#define CARTRIDGE_NAME_REX "REX Utility"
CARTRIDGE_NAME_REX_EP256
#define CARTRIDGE_NAME_REX_EP256 "REX 256K EPROM Cart"
http://www.retroport.de/Rex.html
CARTRIDGE_NAME_REX_RAMFLOPPY
#define CARTRIDGE_NAME_REX_RAMFLOPPY "REX RAM-Floppy"
CARTRIDGE_NAME_RGCD
#define CARTRIDGE_NAME_RGCD "RGCD"
CARTRIDGE_NAME_ROSS
#define CARTRIDGE_NAME_ROSS "ROSS"
CARTRIDGE_NAME_RRNET
#define CARTRIDGE_NAME_RRNET "RR-Net"
see manual
CARTRIDGE_NAME_RRNETMK3
#define CARTRIDGE_NAME_RRNETMK3 "RR-Net MK3"
see manual
CARTRIDGE_NAME_SDBOX
#define CARTRIDGE_NAME_SDBOX "SD-BOX"
http://c64.com.pl/index.php/sdbox106.html
CARTRIDGE_NAME_SFX_SOUND_EXPANDER
#define CARTRIDGE_NAME_SFX_SOUND_EXPANDER "SFX Sound Expander"
http://www.floodgap.com/retrobits/ckb/secret/cbm-sfx-fmbport.jpg
CARTRIDGE_NAME_SFX_SOUND_SAMPLER
#define CARTRIDGE_NAME_SFX_SOUND_SAMPLER "SFX Sound Sampler"
http://www.floodgap.com/retrobits/ckb/secret/cbm-ssm-box.jpg
CARTRIDGE_NAME_SILVERROCK_128
#define CARTRIDGE_NAME_SILVERROCK_128 "Silverrock 128KiB Cartridge"
CARTRIDGE_NAME_SIMONS_BASIC
#define CARTRIDGE_NAME_SIMONS_BASIC "Simons' BASIC"
http://en.wikipedia.org/wiki/Simons'_BASIC
CARTRIDGE_NAME_SNAPSHOT64
#define CARTRIDGE_NAME_SNAPSHOT64 "Snapshot 64"
http://rr.pokefinder.org/wiki/Super_Snapshot
CARTRIDGE_NAME_STARDOS
#define CARTRIDGE_NAME_STARDOS "Stardos"
see manual http://rr.pokefinder.org/wiki/StarDOS
CARTRIDGE_NAME_STRUCTURED_BASIC
#define CARTRIDGE_NAME_STRUCTURED_BASIC "Structured BASIC"
CARTRIDGE_NAME_SUPER_EXPLODE_V5
#define CARTRIDGE_NAME_SUPER_EXPLODE_V5 "Super Explode V5.0"
http://rr.pokefinder.org/wiki/Super_Explode
CARTRIDGE_NAME_SUPER_GAMES
#define CARTRIDGE_NAME_SUPER_GAMES "Super Games"
CARTRIDGE_NAME_SUPER_SNAPSHOT
#define CARTRIDGE_NAME_SUPER_SNAPSHOT "Super Snapshot V4"
http://rr.pokefinder.org/wiki/Super_Snapshot
CARTRIDGE_NAME_SUPER_SNAPSHOT_V5
#define CARTRIDGE_NAME_SUPER_SNAPSHOT_V5 "Super Snapshot V5"
http://rr.pokefinder.org/wiki/Super_Snapshot
CARTRIDGE_NAME_SWIFTLINK
#define CARTRIDGE_NAME_SWIFTLINK "Swiftlink"
http://mikenaberezny.com/hardware/peripherals/swiftlink-rs232-interface/
CARTRIDGE_NAME_TFE
#define CARTRIDGE_NAME_TFE "The Final Ethernet"
CARTRIDGE_NAME_TURBO232
#define CARTRIDGE_NAME_TURBO232 "Turbo232" /*!< also: "ACIA/SWIFTLINK" */ /*http://www.retroport.de/C64_C128_Hardware2.html */
CARTRIDGE_NAME_TURTLE_GRAPHICS_II
#define CARTRIDGE_NAME_TURTLE_GRAPHICS_II "HES Turtle Graphics II"
CARTRIDGE_NAME_ULTIMAX
#define CARTRIDGE_NAME_ULTIMAX "generic Ultimax"
CARTRIDGE_NAME_WARPSPEED
#define CARTRIDGE_NAME_WARPSPEED "Warp Speed"
see manual http://rr.pokefinder.org/wiki/WarpSpeed
CARTRIDGE_NAME_WESTERMANN
#define CARTRIDGE_NAME_WESTERMANN "Westermann Learning"
CARTRIDGE_NAME_ZAXXON
#define CARTRIDGE_NAME_ZAXXON "Zaxxon"
CARTRIDGE_NAME_ZIPPCODE48
#define CARTRIDGE_NAME_ZIPPCODE48 "ZIPP-CODE 48"
CARTRIDGE_NONE
#define CARTRIDGE_NONE -1
CARTRIDGE_OCEAN
#define CARTRIDGE_OCEAN 5
ocean.c
CARTRIDGE_P64
#define CARTRIDGE_P64 43
prophet64.c
CARTRIDGE_PAGEFOX
#define CARTRIDGE_PAGEFOX 53
pagefox.c
CARTRIDGE_PARTNER64
#define CARTRIDGE_PARTNER64 78
partner64.c
CARTRIDGE_PLUS256K
#define CARTRIDGE_PLUS256K -121
plus256k.c
CARTRIDGE_PLUS4_DETECT
#define CARTRIDGE_PLUS4_DETECT 0x8200
low byte must be 0x00
Todo:
FIXME: get rid of this
CARTRIDGE_PLUS4_DIGIBLASTER
#define CARTRIDGE_PLUS4_DIGIBLASTER -201
digiblaster.c
CARTRIDGE_PLUS4_GENERIC
#define CARTRIDGE_PLUS4_GENERIC -2
plus4-generic.c
CARTRIDGE_PLUS4_GENERIC_ALL
#define CARTRIDGE_PLUS4_GENERIC_ALL (CARTRIDGE_PLUS4_GENERIC_C1 | CARTRIDGE_PLUS4_GENERIC_C2)
CARTRIDGE_PLUS4_GENERIC_C1
#define CARTRIDGE_PLUS4_GENERIC_C1 (CARTRIDGE_PLUS4_GENERIC_C1LO | CARTRIDGE_PLUS4_GENERIC_C1HI)
CARTRIDGE_PLUS4_GENERIC_C1HI
#define CARTRIDGE_PLUS4_GENERIC_C1HI 0x8202
CARTRIDGE_PLUS4_GENERIC_C1LO
#define CARTRIDGE_PLUS4_GENERIC_C1LO 0x8201
CARTRIDGE_PLUS4_GENERIC_C2
#define CARTRIDGE_PLUS4_GENERIC_C2 (CARTRIDGE_PLUS4_GENERIC_C2LO | CARTRIDGE_PLUS4_GENERIC_C2HI)
CARTRIDGE_PLUS4_GENERIC_C2HI
#define CARTRIDGE_PLUS4_GENERIC_C2HI 0x8208
CARTRIDGE_PLUS4_GENERIC_C2LO
#define CARTRIDGE_PLUS4_GENERIC_C2LO 0x8204
CARTRIDGE_PLUS4_GENERIC_TYPE_MASK
#define CARTRIDGE_PLUS4_GENERIC_TYPE_MASK 0x000f
CARTRIDGE_PLUS4_IS_GENERIC
#define CARTRIDGE_PLUS4_IS_GENERIC (x) (((x) & 0xff00) == 0x8200)
CARTRIDGE_PLUS4_JACINT1MB
#define CARTRIDGE_PLUS4_JACINT1MB 3
1MB Cartridge
CARTRIDGE_PLUS4_LAST
#define CARTRIDGE_PLUS4_LAST 3
CARTRIDGE_PLUS4_MAGIC
#define CARTRIDGE_PLUS4_MAGIC 1
c264 magic cart
CARTRIDGE_PLUS4_MULTI
#define CARTRIDGE_PLUS4_MULTI 2
plus4 multi cart
CARTRIDGE_PLUS4_NAME_DIGIBLASTER
#define CARTRIDGE_PLUS4_NAME_DIGIBLASTER "Digiblaster Add-on"
CARTRIDGE_PLUS4_NAME_GENERIC
#define CARTRIDGE_PLUS4_NAME_GENERIC "generic cartridge ROM"
list of canonical names for the Plus4 cartridges:
CARTRIDGE_PLUS4_NAME_JACINT1MB
#define CARTRIDGE_PLUS4_NAME_JACINT1MB "1MB Cartridge"
CARTRIDGE_PLUS4_NAME_MAGIC
#define CARTRIDGE_PLUS4_NAME_MAGIC "c264 magic cart"
CARTRIDGE_PLUS4_NAME_MULTI
#define CARTRIDGE_PLUS4_NAME_MULTI "Plus4 multi cart"
CARTRIDGE_PLUS4_NAME_SIDCART
#define CARTRIDGE_PLUS4_NAME_SIDCART "SID cartridge"
CARTRIDGE_PLUS4_SIDCART
#define CARTRIDGE_PLUS4_SIDCART -200
plus4-sidcart.c
CARTRIDGE_PLUS60K
#define CARTRIDGE_PLUS60K -120
plus60k.c
CARTRIDGE_RAMCART
#define CARTRIDGE_RAMCART -104
ramcart.c
CARTRIDGE_RAMLINK
#define CARTRIDGE_RAMLINK 73
ramlink.c
CARTRIDGE_RETRO_REPLAY
#define CARTRIDGE_RETRO_REPLAY 36
retroreplay.c
CARTRIDGE_REU
#define CARTRIDGE_REU -105
reu.c
CARTRIDGE_REX
#define CARTRIDGE_REX 12
rexutility.c
CARTRIDGE_REX_EP256
#define CARTRIDGE_REX_EP256 27
rexep256.c
Todo:
cartconv
CARTRIDGE_REX_RAMFLOPPY
#define CARTRIDGE_REX_RAMFLOPPY 67
rexramfloppy.c
CARTRIDGE_RGCD
#define CARTRIDGE_RGCD 57
rgcd.c
CARTRIDGE_ROSS
#define CARTRIDGE_ROSS 23
ross.c
CARTRIDGE_RRNETMK3
#define CARTRIDGE_RRNETMK3 58
rrnetmk3.c
CARTRIDGE_SDBOX
#define CARTRIDGE_SDBOX 69
sdbox.c
CARTRIDGE_SFX_SOUND_EXPANDER
#define CARTRIDGE_SFX_SOUND_EXPANDER -106
sfx_soundexpander.c, fmopl.c
CARTRIDGE_SFX_SOUND_SAMPLER
#define CARTRIDGE_SFX_SOUND_SAMPLER -107
sfx_soundsampler.c
CARTRIDGE_SILVERROCK_128
#define CARTRIDGE_SILVERROCK_128 55
silverrock128.c
CARTRIDGE_SIMONS_BASIC
#define CARTRIDGE_SIMONS_BASIC 4
simonsbasic.c
CARTRIDGE_SIZE_1024KB
#define CARTRIDGE_SIZE_1024KB 0x00100000
CARTRIDGE_SIZE_128KB
#define CARTRIDGE_SIZE_128KB 0x00020000
CARTRIDGE_SIZE_12KB
#define CARTRIDGE_SIZE_12KB 0x00003000
CARTRIDGE_SIZE_16384KB
#define CARTRIDGE_SIZE_16384KB 0x01000000
CARTRIDGE_SIZE_16KB
#define CARTRIDGE_SIZE_16KB 0x00004000
CARTRIDGE_SIZE_16MB
#define CARTRIDGE_SIZE_16MB CARTRIDGE_SIZE_16384KB
CARTRIDGE_SIZE_1MB
#define CARTRIDGE_SIZE_1MB CARTRIDGE_SIZE_1024KB
for convenience
CARTRIDGE_SIZE_2048KB
#define CARTRIDGE_SIZE_2048KB 0x00200000
CARTRIDGE_SIZE_20KB
#define CARTRIDGE_SIZE_20KB 0x00005000
CARTRIDGE_SIZE_24KB
#define CARTRIDGE_SIZE_24KB 0x00006000
CARTRIDGE_SIZE_256KB
#define CARTRIDGE_SIZE_256KB 0x00040000
CARTRIDGE_SIZE_2KB
#define CARTRIDGE_SIZE_2KB 0x00000800
Todo:
FIXME: cartconv: the sizes are used in a bitfield and also by their absolute values
CARTRIDGE_SIZE_2MB
#define CARTRIDGE_SIZE_2MB CARTRIDGE_SIZE_2048KB
CARTRIDGE_SIZE_32KB
#define CARTRIDGE_SIZE_32KB 0x00008000
CARTRIDGE_SIZE_4096KB
#define CARTRIDGE_SIZE_4096KB 0x00400000
CARTRIDGE_SIZE_4KB
#define CARTRIDGE_SIZE_4KB 0x00001000
CARTRIDGE_SIZE_4MB
#define CARTRIDGE_SIZE_4MB CARTRIDGE_SIZE_4096KB
CARTRIDGE_SIZE_512KB
#define CARTRIDGE_SIZE_512KB 0x00080000
CARTRIDGE_SIZE_64KB
#define CARTRIDGE_SIZE_64KB 0x00010000
CARTRIDGE_SIZE_8192KB
#define CARTRIDGE_SIZE_8192KB 0x00800000
CARTRIDGE_SIZE_8KB
#define CARTRIDGE_SIZE_8KB 0x00002000
CARTRIDGE_SIZE_8MB
#define CARTRIDGE_SIZE_8MB CARTRIDGE_SIZE_8192KB
CARTRIDGE_SIZE_96KB
#define CARTRIDGE_SIZE_96KB 0x00018000
CARTRIDGE_SIZE_MAX
#define CARTRIDGE_SIZE_MAX CARTRIDGE_SIZE_16384KB
CARTRIDGE_SNAPSHOT64
#define CARTRIDGE_SNAPSHOT64 47
snapshot64.c
CARTRIDGE_STARDOS
#define CARTRIDGE_STARDOS 31
stardos.c
CARTRIDGE_STRUCTURED_BASIC
#define CARTRIDGE_STRUCTURED_BASIC 22
stb.c
CARTRIDGE_SUPER_EXPLODE_V5
#define CARTRIDGE_SUPER_EXPLODE_V5 48
superexplode5.c
CARTRIDGE_SUPER_GAMES
#define CARTRIDGE_SUPER_GAMES 8
supergames.c
CARTRIDGE_SUPER_SNAPSHOT
#define CARTRIDGE_SUPER_SNAPSHOT 40
supersnapshot4.c
CARTRIDGE_SUPER_SNAPSHOT_V5
#define CARTRIDGE_SUPER_SNAPSHOT_V5 20
supersnapshot.c
CARTRIDGE_SWIFTLINK
#define CARTRIDGE_SWIFTLINK -118
c64acia1.c
CARTRIDGE_TFE
#define CARTRIDGE_TFE -116
ethernetcart.c
CARTRIDGE_TURBO232
#define CARTRIDGE_TURBO232 -117
c64acia1.c
CARTRIDGE_TURTLE_GRAPHICS_II
#define CARTRIDGE_TURTLE_GRAPHICS_II 76
turtlegraphics.c
CARTRIDGE_ULTIMAX
#define CARTRIDGE_ULTIMAX -6
Known cartridge types.
Todo:
cartconv (4k and 12k binaries)
generic.c
CARTRIDGE_VIC20_16KB_2000
#define CARTRIDGE_VIC20_16KB_2000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 1, 1, 0, 0)
block 1 + block 2
CARTRIDGE_VIC20_16KB_2000_A000
#define CARTRIDGE_VIC20_16KB_2000_A000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 1, 0, 0, 1)
block 1 + block 5
CARTRIDGE_VIC20_16KB_4000
#define CARTRIDGE_VIC20_16KB_4000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 1, 1, 0)
block 2 + block 3
CARTRIDGE_VIC20_16KB_4000_A000
#define CARTRIDGE_VIC20_16KB_4000_A000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 1, 0, 1)
block 2 + block 5
CARTRIDGE_VIC20_16KB_6000
#define CARTRIDGE_VIC20_16KB_6000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 0, 1, 1)
block 3 + block 5
CARTRIDGE_VIC20_2KB_B000
#define CARTRIDGE_VIC20_2KB_B000 CARTRIDGE_VIC20_TYPEDEF(1, 0, 1, 0, 0, 0, 1)
CARTRIDGE_VIC20_32KB_2000
#define CARTRIDGE_VIC20_32KB_2000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 1, 1, 1, 1)
block 1,2,3,5
CARTRIDGE_VIC20_4KB_2000
#define CARTRIDGE_VIC20_4KB_2000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 0, 1, 0, 0, 0)
block 1
CARTRIDGE_VIC20_4KB_3000
#define CARTRIDGE_VIC20_4KB_3000 CARTRIDGE_VIC20_TYPEDEF(1, 1, 0, 1, 0, 0, 0)
CARTRIDGE_VIC20_4KB_4000
#define CARTRIDGE_VIC20_4KB_4000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 0, 0, 1, 0, 0)
block 2
CARTRIDGE_VIC20_4KB_5000
#define CARTRIDGE_VIC20_4KB_5000 CARTRIDGE_VIC20_TYPEDEF(1, 1, 0, 0, 1, 0, 0)
CARTRIDGE_VIC20_4KB_6000
#define CARTRIDGE_VIC20_4KB_6000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 0, 0, 0, 1, 0)
block 3
CARTRIDGE_VIC20_4KB_7000
#define CARTRIDGE_VIC20_4KB_7000 CARTRIDGE_VIC20_TYPEDEF(1, 1, 0, 0, 0, 1, 0)
CARTRIDGE_VIC20_4KB_A000
#define CARTRIDGE_VIC20_4KB_A000 CARTRIDGE_VIC20_TYPEDEF(0, 0, 0, 0, 0, 0, 1)
block 5
CARTRIDGE_VIC20_4KB_B000
#define CARTRIDGE_VIC20_4KB_B000 CARTRIDGE_VIC20_TYPEDEF(1, 1, 0, 0, 0, 0, 1)
CARTRIDGE_VIC20_8KB_2000
#define CARTRIDGE_VIC20_8KB_2000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 1, 0, 0, 0)
CARTRIDGE_VIC20_8KB_4000
#define CARTRIDGE_VIC20_8KB_4000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 1, 0, 0)
CARTRIDGE_VIC20_8KB_6000
#define CARTRIDGE_VIC20_8KB_6000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 0, 1, 0)
CARTRIDGE_VIC20_8KB_A000
#define CARTRIDGE_VIC20_8KB_A000 CARTRIDGE_VIC20_TYPEDEF(0, 1, 1, 0, 0, 0, 1)
CARTRIDGE_VIC20_ACIA
#define CARTRIDGE_VIC20_ACIA -119
c64acia1.c
CARTRIDGE_VIC20_BEHRBONZ
#define CARTRIDGE_VIC20_BEHRBONZ 2
behrbonz.c
CARTRIDGE_VIC20_DEBUGCART
#define CARTRIDGE_VIC20_DEBUGCART -124
debugcart.c
CARTRIDGE_VIC20_DETECT
#define CARTRIDGE_VIC20_DETECT 0x8000
CARTRIDGE_VIC20_DIGIMAX
#define CARTRIDGE_VIC20_DIGIMAX -100
I/O only C64 cartridges can be used with the "Masquerade" adapter.
Todo:
FIXME: currently we need to make sure to use the same IDs here as for C64
digimax.c
CARTRIDGE_VIC20_DS12C887RTC
#define CARTRIDGE_VIC20_DS12C887RTC -113
ds12c887rtc.c
CARTRIDGE_VIC20_FINAL_EXPANSION
#define CARTRIDGE_VIC20_FINAL_EXPANSION 5
finalexpansion.c
CARTRIDGE_VIC20_FP
#define CARTRIDGE_VIC20_FP 3
vic-fp.c
CARTRIDGE_VIC20_GENERIC
#define CARTRIDGE_VIC20_GENERIC -2
generic.c
CARTRIDGE_VIC20_GEORAM
#define CARTRIDGE_VIC20_GEORAM -102
georam.c
CARTRIDGE_VIC20_IEEE488
#define CARTRIDGE_VIC20_IEEE488 -11
vic20-ieee488.c
CARTRIDGE_VIC20_IO2_RAM
#define CARTRIDGE_VIC20_IO2_RAM -12
ioramcart.c
CARTRIDGE_VIC20_IO3_RAM
#define CARTRIDGE_VIC20_IO3_RAM -13
ioramcart.c
CARTRIDGE_VIC20_LAST
#define CARTRIDGE_VIC20_LAST 8
cartconv: last cartridge in list
CARTRIDGE_VIC20_MEGACART
#define CARTRIDGE_VIC20_MEGACART 1
the following must match the CRT IDs
megacart.c
CARTRIDGE_VIC20_MIDI_DATEL
#define CARTRIDGE_VIC20_MIDI_DATEL -109
c64-midi.c
CARTRIDGE_VIC20_MIDI_MAPLIN
#define CARTRIDGE_VIC20_MIDI_MAPLIN -112
c64-midi.c
CARTRIDGE_VIC20_MIDI_NAMESOFT
#define CARTRIDGE_VIC20_MIDI_NAMESOFT -111
c64-midi.c
CARTRIDGE_VIC20_MIDI_PASSPORT
#define CARTRIDGE_VIC20_MIDI_PASSPORT -108
c64-midi.c
CARTRIDGE_VIC20_MIDI_SEQUENTIAL
#define CARTRIDGE_VIC20_MIDI_SEQUENTIAL -110
c64-midi.c
CARTRIDGE_VIC20_MIKRO_ASSEMBLER
#define CARTRIDGE_VIC20_MIKRO_ASSEMBLER 8
mikroassembler.c
CARTRIDGE_VIC20_NAME_BEHRBONZ
#define CARTRIDGE_VIC20_NAME_BEHRBONZ "Behr Bonz"
CARTRIDGE_VIC20_NAME_FINAL_EXPANSION
#define CARTRIDGE_VIC20_NAME_FINAL_EXPANSION "Final Expansion"
CARTRIDGE_VIC20_NAME_FP
#define CARTRIDGE_VIC20_NAME_FP "Vic Flash Plugin"
http://www.ktverkko.fi/~msmakela/8bit/vfp/index.en.html
CARTRIDGE_VIC20_NAME_GENERIC
#define CARTRIDGE_VIC20_NAME_GENERIC "generic cartridge ROM"
list of canonical names for the VIC20 cartridges:
CARTRIDGE_VIC20_NAME_IEEE488
#define CARTRIDGE_VIC20_NAME_IEEE488 "VIC-1112 IEEE-488 Interface" /*https://sleepingelephant.com/denial/wiki/index.php/File:Chipitos.be-VIC-1112.jpg */
CARTRIDGE_VIC20_NAME_IO2_RAM
#define CARTRIDGE_VIC20_NAME_IO2_RAM "I/O-2 RAM"
CARTRIDGE_VIC20_NAME_IO3_RAM
#define CARTRIDGE_VIC20_NAME_IO3_RAM "I/O-3 RAM"
CARTRIDGE_VIC20_NAME_MEGACART
#define CARTRIDGE_VIC20_NAME_MEGACART "Mega-Cart"
http://mega-cart.com/
CARTRIDGE_VIC20_NAME_MIDI
#define CARTRIDGE_VIC20_NAME_MIDI "MIDI"
CARTRIDGE_VIC20_NAME_MIKRO_ASSEMBLER
#define CARTRIDGE_VIC20_NAME_MIKRO_ASSEMBLER "Mikro Assembler"
CARTRIDGE_VIC20_NAME_RABBIT
#define CARTRIDGE_VIC20_NAME_RABBIT "Rabbit Tape"
CARTRIDGE_VIC20_NAME_SIDCART
#define CARTRIDGE_VIC20_NAME_SIDCART "SIDCART"
CARTRIDGE_VIC20_NAME_SUPEREXPANDER
#define CARTRIDGE_VIC20_NAME_SUPEREXPANDER "Super Expander"
CARTRIDGE_VIC20_NAME_UM
#define CARTRIDGE_VIC20_NAME_UM "UltiMem"
CARTRIDGE_VIC20_RABBIT
#define CARTRIDGE_VIC20_RABBIT 6
rabbit.c
CARTRIDGE_VIC20_SFX_SOUND_EXPANDER
#define CARTRIDGE_VIC20_SFX_SOUND_EXPANDER -106
sfx_soundexpander.c, fmopl.c
CARTRIDGE_VIC20_SFX_SOUND_SAMPLER
#define CARTRIDGE_VIC20_SFX_SOUND_SAMPLER -107
sfx_soundsampler.c
CARTRIDGE_VIC20_SIDCART
#define CARTRIDGE_VIC20_SIDCART -10
vic20-sidcart.c
CARTRIDGE_VIC20_SUPEREXPANDER
#define CARTRIDGE_VIC20_SUPEREXPANDER 7
superexpander.c
CARTRIDGE_VIC20_SWIFTLINK
#define CARTRIDGE_VIC20_SWIFTLINK -118
c64acia1.c
CARTRIDGE_VIC20_TFE
#define CARTRIDGE_VIC20_TFE -116
ethernetcart.c
CARTRIDGE_VIC20_TURBO232
#define CARTRIDGE_VIC20_TURBO232 -117
c64acia1.c
CARTRIDGE_VIC20_TYPEDEF
#define CARTRIDGE_VIC20_TYPEDEF (h, s1, s0, b1, b2, b3, b5) (0x8000 | ((h) << 6) | ((s1) << 5) | ((s0) << 4) | ((b1) << 3) | ((b2) << 2) | ((b3) << 1) | ((b5) << 0))
CARTRIDGE_VIC20_UM
#define CARTRIDGE_VIC20_UM 4
ultimem.c
CARTRIDGE_WARPSPEED
#define CARTRIDGE_WARPSPEED 16
warpspeed.c
CARTRIDGE_WESTERMANN
#define CARTRIDGE_WESTERMANN 11
westermann.c
CARTRIDGE_ZAXXON
#define CARTRIDGE_ZAXXON 18
zaxxon.c
CARTRIDGE_ZIPPCODE48
#define CARTRIDGE_ZIPPCODE48 63
zippcode48.c
Function Documentation
cartridge_attach_image()
int cartridge_attach_image (int type, const char * filename)
attach (and enable) a cartridge by type and filename (takes crt and bin files)
Referenced by attach_cart_image(), autostart_autodetect(), c128cartridge_cmdline_options_init(), and do_smart_attach().
cartridge_bin_save()
int cartridge_bin_save (int type, const char * filename)
cartridge_can_flush_image()
int cartridge_can_flush_image (int crtid)
returns 1 when cartridge (ROM) image can be flushed
Referenced by create_cart_image_widget(), and update_buttons_sensitivity().
cartridge_can_flush_secondary_image()
int cartridge_can_flush_secondary_image (int crtid)
Referenced by update_buttons_sensitivity().
cartridge_can_save_image()
int cartridge_can_save_image (int crtid)
returns 1 when cartridge (ROM) image can be saved
Referenced by create_cart_image_widget(), and update_buttons_sensitivity().
cartridge_can_save_secondary_image()
int cartridge_can_save_secondary_image (int crtid)
Referenced by update_buttons_sensitivity().
cartridge_cmdline_options_init()
int cartridge_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
cartridge_crt_save()
int cartridge_crt_save (int type, const char * filename)
cartridge_detach_image()
void cartridge_detach_image (int type)
detaches/disables the cartridge with the associated id.
pass -1 to detach all
detaches/disables the cartridge with the associated id.
Referenced by c128cartridge_cmdline_options_init(), cart_detach_action(), machine_specific_shutdown(), and resources_set_defaults().
cartridge_detect()
int cartridge_detect (const char * filename)
detect cartridge type (takes crt and bin files)
cartridge_disable()
int cartridge_disable (int type)
disable cartridge by type
Referenced by on_cart_enable_check_button_toggled(), and on_enable_toggled().
cartridge_enable()
int cartridge_enable (int type)
Referenced by on_cart_enable_check_button_toggled(), and on_enable_toggled().
cartridge_flush_image()
int cartridge_flush_image (int type)
Referenced by on_flush_clicked().
cartridge_flush_secondary_image()
int cartridge_flush_secondary_image (int type)
Referenced by on_flush_clicked().
cartridge_get_filename_by_slot()
char * cartridge_get_filename_by_slot (int slot)
Todo:
FIXME: slot arg is ignored right now. this should return a pointer to a filename, or NULL
Referenced by update_cart_file_widget().
cartridge_get_filename_by_type()
const char * cartridge_get_filename_by_type (int type)
cartridge_get_id()
int cartridge_get_id (int slot)
Todo:
FIXME: slot arg is ignored right now. this should return a valid cartridge ID for a given slot, or CARTRIDGE_NONE
Referenced by c128cartridge_basic_hi_read(), c128cartridge_basic_hi_store(), c128cartridge_detach_image(), c128cartridge_freeze(), c128cartridge_freeze_allowed(), c128cartridge_hi_read(), c128cartridge_hi_store(), c128cartridge_mmu_translate(), c128cartridge_powerup(), c128cartridge_ram_read(), c128cartridge_ram_store(), c128cartridge_switch_mode(), external_function_rom_peek(), external_function_rom_read(), external_function_rom_store(), internal_function_rom_read(), internal_function_rom_store(), and update_cart_type_widget().
cartridge_get_info_list()
cartridge_info_t * cartridge_get_info_list (void)
Referenced by create_cart_id_model(), and settings_default_cart_widget_create().
cartridge_get_secondary_filename_by_slot()
char * cartridge_get_secondary_filename_by_slot (int slot)
cartridge_init()
void cartridge_init (void)
init the cartridge system
Referenced by machine_specific_init().
cartridge_init_config()
void cartridge_init_config (void)
init the cartridge config so the cartridge can start (or whatever)
Referenced by mem_initialize_memory().
cartridge_mmu_translate()
void cartridge_mmu_translate (unsigned int addr, uint8_t ** base, int * start, int * limit)
mmu translation
Referenced by mem_mmu_translate().
cartridge_peek_mem()
uint8_t cartridge_peek_mem (uint16_t addr)
generic cartridge memory peek for the monitor
Referenced by mem_bank_peek(), mem_bank_read(), and mem_peek_with_config_c64().
cartridge_powerup()
void cartridge_powerup (void)
powerup / hardreset
Referenced by machine_specific_powerup().
cartridge_ram_init()
void cartridge_ram_init (void)
Initialize RAM for power-up.
cartridge_release_freeze()
void cartridge_release_freeze (void)
Todo:
FIXME: this should also be made a generic function that takes the type
Referenced by partner128_io1_store().
cartridge_reset()
void cartridge_reset (void)
reset button pressed in UI
Referenced by machine_specific_reset().
cartridge_resources_init()
int cartridge_resources_init (void)
Referenced by machine_resources_init().
cartridge_resources_shutdown()
void cartridge_resources_shutdown (void)
Referenced by machine_resources_shutdown().
cartridge_save_image()
int cartridge_save_image (int type, const char * filename)
save the primary (rom/ram)image of the give cart type to a file
Referenced by on_save_response(), and save_filename_callback().
cartridge_save_secondary_image()
int cartridge_save_secondary_image (int type, const char * filename)
save the secondary image of the give cart type to a file
Referenced by on_save_response().
cartridge_set_default()
void cartridge_set_default (void)
set current "Main Slot" cart as default
Todo:
FIXME: this should also be made a generic function that takes the type
Referenced by attach_cart_image(), and on_set_default_clicked().
cartridge_setup_context()
void cartridge_setup_context (struct machine_context_s * machine_context)
Referenced by machine_setup_context().
cartridge_shutdown()
void cartridge_shutdown (void)
shutdown the cartridge system
Referenced by machine_specific_shutdown().
cartridge_snapshot_read_modules()
int cartridge_snapshot_read_modules (struct snapshot_s * s)
Referenced by c128_snapshot_read_module().
cartridge_snapshot_write_modules()
int cartridge_snapshot_write_modules (struct snapshot_s * s)
Referenced by c128_snapshot_write_module().
cartridge_sound_chip_init()
void cartridge_sound_chip_init (void)
Referenced by machine_specific_init().
cartridge_trigger_freeze()
void cartridge_trigger_freeze (void)
freeze button pressed in UI
Todo:
FIXME: this should also be made a generic function that takes the type
Referenced by c128cartridge_cmdline_options_init(), and cart_freeze_action().
cartridge_trigger_freeze_nmi_only()
void cartridge_trigger_freeze_nmi_only (void)
trigger a freeze, but don't trigger the cartridge logic (which might release it).
Todo:
FIXME: this should also be made a generic function that takes the type
used by monitor
Referenced by c128cartridge_cmdline_options_init().
cartridge_type_enabled()
int cartridge_type_enabled (int type)
Referenced by carthelpers_create_enable_check_button(), create_mmc64_enable_widget(), settings_ieee488_widget_create(), settings_ieeeflash64_widget_create(), and settings_ramlink_widget_create().
cartridge_unset_default()
void cartridge_unset_default (void)
called from resources_set_defaults()
Referenced by confirm_detach_callback(), on_remove_clicked(), and resources_set_defaults().