x128: arch/gtk3/exec_forwarder.c File Reference
exec_forwarder.c File Reference
#include <windows.h>
#include <stdio.h>
Functions
void our_wcscpy (WCHAR *dest, WCHAR *src)
void our_wcscat (WCHAR *dest, WCHAR *src)
int our_wcslen (WCHAR *str)
int needs_quotation (WCHAR *str)
void copy_quoted (WCHAR *dest, WCHAR *src)
WCHAR * skip_argument (WCHAR *src)
int main (int argc, char **argv)
Variables
WCHAR reported_path [32768]
WCHAR full_path [32768]
WCHAR cmdline [32768]
Function Documentation
copy_quoted()
void copy_quoted (WCHAR * dest, WCHAR * src)
Referenced by main().
main()
int main (int argc, char ** argv)
needs_quotation()
int needs_quotation (WCHAR * str)
Referenced by copy_quoted().
our_wcscat()
void our_wcscat (WCHAR * dest, WCHAR * src)
Referenced by main().
our_wcscpy()
void our_wcscpy (WCHAR * dest, WCHAR * src)
Referenced by copy_quoted(), main(), and our_wcscat().
our_wcslen()
int our_wcslen (WCHAR * str)
Referenced by main().
skip_argument()
WCHAR * skip_argument (WCHAR * src)
Referenced by main().
Variable Documentation
cmdline
WCHAR cmdline[32768]
Referenced by cmdline_log_active(), main(), and main_program().
full_path
WCHAR full_path[32768]
Referenced by archdep_boot_path(), and main().
reported_path
WCHAR reported_path[32768]
Referenced by main().