vsid: printerdrv/interface-serial.c File Reference
interface-serial.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cmdline.h"
#include "driver-select.h"
#include "interface-serial.h"
#include "log.h"
#include "machine-bus.h"
#include "printer.h"
#include "resources.h"
#include "serial.h"
#include "types.h"
#include "vdrive.h"
Macros
#define DBG(x)
#define FIRST_PRINTER_DEVICE_NUMBER 4
#define NUM_PRINTERS 3
4...6
#define NUM_PRINTER_DEVICE_NUMBERS 4
4...7
Functions
static int interface_serial_attach (unsigned int prnr)
static int interface_serial_detach (unsigned int prnr)
static int set_printer_enabled (int flag, void *param)
int interface_serial_init_resources (void)
int interface_serial_init_cmdline_options (void)
static int open_pr (unsigned int prnr, const uint8_t *name, unsigned int length, unsigned int secondary)
static int read_pr (unsigned int prnr, uint8_t *byte, unsigned int secondary)
static int write_pr (unsigned int prnr, uint8_t byte, unsigned int secondary)
static int close_pr (unsigned int prnr, unsigned int secondary)
static void flush_pr (unsigned int prnr, unsigned int secondary)
static int open_pr4 (struct vdrive_s *var, const uint8_t *name, unsigned int length, unsigned int secondary, struct cbmdos_cmd_parse_s *cmd_parse_ext)
static int read_pr4 (struct vdrive_s *var, uint8_t *byte, unsigned int secondary)
static int write_pr4 (struct vdrive_s *var, uint8_t byte, unsigned int secondary)
static int close_pr4 (struct vdrive_s *var, unsigned int secondary)
static void flush_pr4 (struct vdrive_s *var, unsigned int secondary)
static int open_pr5 (struct vdrive_s *var, const uint8_t *name, unsigned int length, unsigned int secondary, struct cbmdos_cmd_parse_s *cmd_parse_ext)
static int read_pr5 (struct vdrive_s *var, uint8_t *byte, unsigned int secondary)
static int write_pr5 (struct vdrive_s *var, uint8_t byte, unsigned int secondary)
static int close_pr5 (struct vdrive_s *var, unsigned int secondary)
static void flush_pr5 (struct vdrive_s *var, unsigned int secondary)
static int open_pr6 (struct vdrive_s *var, const uint8_t *name, unsigned int length, unsigned int secondary, struct cbmdos_cmd_parse_s *cmd_parse_ext)
static int read_pr6 (struct vdrive_s *var, uint8_t *byte, unsigned int secondary)
static int write_pr6 (struct vdrive_s *var, uint8_t byte, unsigned int secondary)
static int close_pr6 (struct vdrive_s *var, unsigned int secondary)
static void flush_pr6 (struct vdrive_s *var, unsigned int secondary)
int interface_serial_close (unsigned int unit)
int interface_serial_late_init (void)
void interface_serial_init (void)
void interface_serial_shutdown (void)
called by printer.serial.c:printer_serial_shutdown()
Variables
static log_t interface_serial_log = ((log_t)-1)
static int printer_enabled [4]
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
static unsigned int inuse_secadr [4]
Macro Definition Documentation
DBG
#define DBG (x)
FIRST_PRINTER_DEVICE_NUMBER
#define FIRST_PRINTER_DEVICE_NUMBER 4
NUM_PRINTER_DEVICE_NUMBERS
#define NUM_PRINTER_DEVICE_NUMBERS 4
4...7
NUM_PRINTERS
#define NUM_PRINTERS 3
4...6
Function Documentation
close_pr()
static int close_pr (unsigned int prnr, unsigned int secondary) static
Referenced by close_pr4(), close_pr5(), close_pr6(), interface_serial_close(), and interface_serial_detach().
close_pr4()
static int close_pr4 (struct vdrive_s * var, unsigned int secondary) static
Referenced by interface_serial_attach().
close_pr5()
static int close_pr5 (struct vdrive_s * var, unsigned int secondary) static
Referenced by interface_serial_attach().
close_pr6()
static int close_pr6 (struct vdrive_s * var, unsigned int secondary) static
Referenced by interface_serial_attach().
flush_pr()
static void flush_pr (unsigned int prnr, unsigned int secondary) static
Referenced by flush_pr4(), flush_pr5(), flush_pr6(), and interface_serial_detach().
flush_pr4()
static void flush_pr4 (struct vdrive_s * var, unsigned int secondary) static
Referenced by interface_serial_attach().
flush_pr5()
static void flush_pr5 (struct vdrive_s * var, unsigned int secondary) static
Referenced by interface_serial_attach().
flush_pr6()
static void flush_pr6 (struct vdrive_s * var, unsigned int secondary) static
Referenced by interface_serial_attach().
interface_serial_attach()
static int interface_serial_attach (unsigned int prnr) static
< filesystem
Referenced by interface_serial_late_init(), and set_printer_enabled().
interface_serial_close()
int interface_serial_close (unsigned int unit)
< 4...6
Referenced by printer_serial_close().
interface_serial_detach()
static int interface_serial_detach (unsigned int prnr) static
< 4...6
Referenced by interface_serial_shutdown(), and set_printer_enabled().
interface_serial_init()
void interface_serial_init (void)
Referenced by printer_serial_init().
interface_serial_init_cmdline_options()
int interface_serial_init_cmdline_options (void)
Referenced by printer_serial_init_cmdline_options().
interface_serial_init_resources()
int interface_serial_init_resources (void)
Referenced by printer_serial_init_resources().
interface_serial_late_init()
int interface_serial_late_init (void)
< 4...7
Referenced by printer_serial_late_init().
interface_serial_shutdown()
void interface_serial_shutdown (void)
called by printer.serial.c:printer_serial_shutdown()
< 4...7
Referenced by printer_serial_shutdown().
open_pr()
static int open_pr (unsigned int prnr, const uint8_t * name, unsigned int length, unsigned int secondary) static
< 4...6
Referenced by open_pr4(), open_pr5(), open_pr6(), and write_pr().
open_pr4()
static int open_pr4 (struct vdrive_s * var, const uint8_t * name, unsigned int length, unsigned int secondary, struct cbmdos_cmd_parse_s * cmd_parse_ext) static
Referenced by interface_serial_attach().
open_pr5()
static int open_pr5 (struct vdrive_s * var, const uint8_t * name, unsigned int length, unsigned int secondary, struct cbmdos_cmd_parse_s * cmd_parse_ext) static
Referenced by interface_serial_attach().
open_pr6()
static int open_pr6 (struct vdrive_s * var, const uint8_t * name, unsigned int length, unsigned int secondary, struct cbmdos_cmd_parse_s * cmd_parse_ext) static
Referenced by interface_serial_attach().
read_pr()
static int read_pr (unsigned int prnr, uint8_t * byte, unsigned int secondary) static
Referenced by read_pr4(), read_pr5(), and read_pr6().
read_pr4()
static int read_pr4 (struct vdrive_s * var, uint8_t * byte, unsigned int secondary) static
Referenced by interface_serial_attach().
read_pr5()
static int read_pr5 (struct vdrive_s * var, uint8_t * byte, unsigned int secondary) static
Referenced by interface_serial_attach().
read_pr6()
static int read_pr6 (struct vdrive_s * var, uint8_t * byte, unsigned int secondary) static
Referenced by interface_serial_attach().
set_printer_enabled()
static int set_printer_enabled (int flag, void * param) static
< 4...7
< 4...6
write_pr()
static int write_pr (unsigned int prnr, uint8_t byte, unsigned int secondary) static
Referenced by write_pr4(), write_pr5(), and write_pr6().
write_pr4()
static int write_pr4 (struct vdrive_s * var, uint8_t byte, unsigned int secondary) static
Referenced by interface_serial_attach().
write_pr5()
static int write_pr5 (struct vdrive_s * var, uint8_t byte, unsigned int secondary) static
Referenced by interface_serial_attach().
write_pr6()
static int write_pr6 (struct vdrive_s * var, uint8_t byte, unsigned int secondary) static
Referenced by interface_serial_attach().
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-device4", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer4", NULL,
      "<Type>", "Set device type for device #4 (0: None, 1: Filesystem, 2: Real)" },
    { "-device5", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer5", NULL,
      "<Type>", "Set device type for device #5 (0: None, 1: Filesystem, 2: Real)" },
    { "-device6", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer6", NULL,
      "<Type>", "Set device type for device #6 (0: None, 1: Filesystem, 2: Real)" },
    { "-device7", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer7", NULL,
      "<Type>", "Set device type for device #7 (0: None, 2: Real)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by interface_serial_init_cmdline_options().
interface_serial_log
log_t interface_serial_log = ((log_t)-1) static
Referenced by close_pr(), flush_pr(), interface_serial_attach(), interface_serial_init(), open_pr(), and write_pr().
inuse_secadr
unsigned int inuse_secadr[4] static
Referenced by close_pr(), flush_pr(), interface_serial_attach(), interface_serial_detach(), open_pr(), and write_pr().
printer_enabled
int printer_enabled[4] static
Referenced by interface_serial_late_init(), and set_printer_enabled().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "Printer4",  0 , RES_EVENT_STRICT, (resource_value_t)0,
      &printer_enabled[0], set_printer_enabled, (void *)0 },
    { "Printer5",  0 , RES_EVENT_STRICT, (resource_value_t)0,
      &printer_enabled[1], set_printer_enabled, (void *)1 },
    { "Printer6",  0 , RES_EVENT_STRICT, (resource_value_t)0,
      &printer_enabled[2], set_printer_enabled, (void *)2 },
    { "Printer7",  0 , RES_EVENT_STRICT, (resource_value_t)0,
      &printer_enabled[3], set_printer_enabled, (void *)3 },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by interface_serial_init_resources().