vsid: catweaselmkiii.h File Reference
catweaselmkiii.h File Reference
#include "types.h"
#include "sid-snapshot.h"
Macros
#define CW_VENDOR 0xe159
#define CW_DEVICE 0x0001
#define CW_MK3_SUBVENDOR 0x1212
#define CW_MK3_SUBDEVICE 0x0002
#define CW_MK4_SUBVENDOR1 0x5213
#define CW_MK4_SUBVENDOR2 0x5200
#define CW_MK4_SUBDEVICE1 0x0002
#define CW_MK4_SUBDEVICE2 0x0003
#define CW_DATA_DIRECTION 0x02
generic registers
#define CW_SELECT_BANK 0x03
#define CW_PORT_OUT_DIR CW_SELECT_BANK
#define CW_PORT_AUX 0x05
#define CW_PORT_IN_DIR 0x07
#define CW_BANK_RESETFPGA 0x00
values for CW_SELECT_BANK
#define CW_BANK_FIFO 0x01
#define CW_BANK_FLOPPY 0x41
#define CW_BANK_IO 0x81
#define CW_BANK_IRQ 0xC1
#define CW_FLOPPY_JOYDAT 0xC0
registers in FLOPPY bank
#define CW_FLOPPY_JOYBUT 0xC8
#define CW_FLOPPY_JOYBUT_DIR 0xCC
#define CW_FLOPPY_KEYDAT 0xD0
#define CW_FLOPPY_KEYSTATUS 0xD4
#define CW_FLOPPY_SIDDAT 0xD8
#define CW_FLOPPY_SIDADDR 0xDC
#define CW_FLOPPY_MEMORY 0xE0
#define CW_FLOPPY_RESETPOINTER 0xE4
#define CW_FLOPPY_CONTROL 0xE8
#define CW_FLOPPY_OPTION 0xEC
#define CW_FLOPPY_START_A 0xF0
#define CW_FLOPPY_START_B 0xF4
#define CW_FLOPPY_IRQ 0xFC
#define CW_IO_MOUSEY1 0xC0
registers in IO bank
#define CW_IO_MOUSEX1 0xC4
#define CW_IO_MOUSEY2 0xC8
#define CW_IO_MOUSEX2 0xCC
#define CW_IO_BUTTON 0xD0
#define CW_IRQ_R0 0xC0
registers in CW_BANK_IRQ
#define CW_IRQ_R1 0xC4
#define CW_IRQ_M0 0xC8
#define CW_IRQ_M1 0xCC
#define CW_IRQ_MK3FLOPPY 0x01
bits in registers in CW_BANK_IRQ
#define CW_IRQ_INDEX 0x02
#define CW_IRQ_FLOPPY_START 0x04
#define CW_IRQ_FLOPPY_END 0x08
#define CW_IRQ_SID_FIFO_HALF_EMPTY 0x10
#define CW_IRQ_SID_READ 0x20
#define CW_IRQ_MEM_EQUAL 0x40
#define CW_IRQ_KEYBOARD 0x80
#define CW_IRQ_SID_FIFO_EMPTY 0x01
#define CW_IRQ_SID_FEEDBACK 0x02
#define CW_MAXCARDS 4
Functions
int catweaselmkiii_open (void)
int catweaselmkiii_close (void)
int catweaselmkiii_read (uint16_t addr, int chipno)
void catweaselmkiii_store (uint16_t addr, uint8_t val, int chipno)
void catweaselmkiii_set_machine_parameter (long cycles_per_sec)
int catweaselmkiii_available (void)
int catweaselmkiii_drv_open (void)
int catweaselmkiii_drv_close (void)
int catweaselmkiii_drv_read (uint16_t addr, int chipno)
void catweaselmkiii_drv_store (uint16_t addr, uint8_t val, int chipno)
void catweaselmkiii_drv_set_machine_parameter (long cycles_per_sec)
int catweaselmkiii_drv_available (void)
int catweaselmkiii_get_ntsc (void)
void catweaselmkiii_state_read (int chipno, struct sid_cw3_snapshot_state_s *sid_state)
void catweaselmkiii_state_write (int chipno, struct sid_cw3_snapshot_state_s *sid_state)
Macro Definition Documentation
CW_BANK_FIFO
#define CW_BANK_FIFO 0x01
CW_BANK_FLOPPY
#define CW_BANK_FLOPPY 0x41
CW_BANK_IO
#define CW_BANK_IO 0x81
CW_BANK_IRQ
#define CW_BANK_IRQ 0xC1
CW_BANK_RESETFPGA
#define CW_BANK_RESETFPGA 0x00
values for CW_SELECT_BANK
CW_DATA_DIRECTION
#define CW_DATA_DIRECTION 0x02
generic registers
CW_DEVICE
#define CW_DEVICE 0x0001
CW_FLOPPY_CONTROL
#define CW_FLOPPY_CONTROL 0xE8
CW_FLOPPY_IRQ
#define CW_FLOPPY_IRQ 0xFC
CW_FLOPPY_JOYBUT
#define CW_FLOPPY_JOYBUT 0xC8
CW_FLOPPY_JOYBUT_DIR
#define CW_FLOPPY_JOYBUT_DIR 0xCC
CW_FLOPPY_JOYDAT
#define CW_FLOPPY_JOYDAT 0xC0
registers in FLOPPY bank
CW_FLOPPY_KEYDAT
#define CW_FLOPPY_KEYDAT 0xD0
CW_FLOPPY_KEYSTATUS
#define CW_FLOPPY_KEYSTATUS 0xD4
CW_FLOPPY_MEMORY
#define CW_FLOPPY_MEMORY 0xE0
CW_FLOPPY_OPTION
#define CW_FLOPPY_OPTION 0xEC
CW_FLOPPY_RESETPOINTER
#define CW_FLOPPY_RESETPOINTER 0xE4
CW_FLOPPY_SIDADDR
#define CW_FLOPPY_SIDADDR 0xDC
CW_FLOPPY_SIDDAT
#define CW_FLOPPY_SIDDAT 0xD8
CW_FLOPPY_START_A
#define CW_FLOPPY_START_A 0xF0
CW_FLOPPY_START_B
#define CW_FLOPPY_START_B 0xF4
CW_IO_BUTTON
#define CW_IO_BUTTON 0xD0
CW_IO_MOUSEX1
#define CW_IO_MOUSEX1 0xC4
CW_IO_MOUSEX2
#define CW_IO_MOUSEX2 0xCC
CW_IO_MOUSEY1
#define CW_IO_MOUSEY1 0xC0
registers in IO bank
CW_IO_MOUSEY2
#define CW_IO_MOUSEY2 0xC8
CW_IRQ_FLOPPY_END
#define CW_IRQ_FLOPPY_END 0x08
CW_IRQ_FLOPPY_START
#define CW_IRQ_FLOPPY_START 0x04
CW_IRQ_INDEX
#define CW_IRQ_INDEX 0x02
CW_IRQ_KEYBOARD
#define CW_IRQ_KEYBOARD 0x80
CW_IRQ_M0
#define CW_IRQ_M0 0xC8
CW_IRQ_M1
#define CW_IRQ_M1 0xCC
CW_IRQ_MEM_EQUAL
#define CW_IRQ_MEM_EQUAL 0x40
CW_IRQ_MK3FLOPPY
#define CW_IRQ_MK3FLOPPY 0x01
bits in registers in CW_BANK_IRQ
CW_IRQ_R0
#define CW_IRQ_R0 0xC0
registers in CW_BANK_IRQ
CW_IRQ_R1
#define CW_IRQ_R1 0xC4
CW_IRQ_SID_FEEDBACK
#define CW_IRQ_SID_FEEDBACK 0x02
CW_IRQ_SID_FIFO_EMPTY
#define CW_IRQ_SID_FIFO_EMPTY 0x01
CW_IRQ_SID_FIFO_HALF_EMPTY
#define CW_IRQ_SID_FIFO_HALF_EMPTY 0x10
CW_IRQ_SID_READ
#define CW_IRQ_SID_READ 0x20
CW_MAXCARDS
#define CW_MAXCARDS 4
CW_MK3_SUBDEVICE
#define CW_MK3_SUBDEVICE 0x0002
CW_MK3_SUBVENDOR
#define CW_MK3_SUBVENDOR 0x1212
CW_MK4_SUBDEVICE1
#define CW_MK4_SUBDEVICE1 0x0002
CW_MK4_SUBDEVICE2
#define CW_MK4_SUBDEVICE2 0x0003
CW_MK4_SUBVENDOR1
#define CW_MK4_SUBVENDOR1 0x5213
CW_MK4_SUBVENDOR2
#define CW_MK4_SUBVENDOR2 0x5200
CW_PORT_AUX
#define CW_PORT_AUX 0x05
CW_PORT_IN_DIR
#define CW_PORT_IN_DIR 0x07
CW_PORT_OUT_DIR
#define CW_PORT_OUT_DIR CW_SELECT_BANK
CW_SELECT_BANK
#define CW_SELECT_BANK 0x03
CW_VENDOR
#define CW_VENDOR 0xe159
Function Documentation
catweaselmkiii_available()
int catweaselmkiii_available (void)
Referenced by build_sid_cmdline_option(), and sid_get_engine_model_list().
catweaselmkiii_close()
int catweaselmkiii_close (void)
Referenced by sid_engine_set().
catweaselmkiii_drv_available()
int catweaselmkiii_drv_available (void)
catweaselmkiii_drv_close()
int catweaselmkiii_drv_close (void)
catweaselmkiii_drv_open()
int catweaselmkiii_drv_open (void)
catweaselmkiii_drv_read()
int catweaselmkiii_drv_read (uint16_t addr, int chipno)
catweaselmkiii_drv_set_machine_parameter()
void catweaselmkiii_drv_set_machine_parameter (long cycles_per_sec)
catweaselmkiii_drv_store()
void catweaselmkiii_drv_store (uint16_t addr, uint8_t val, int chipno)
catweaselmkiii_get_ntsc()
int catweaselmkiii_get_ntsc (void)
catweaselmkiii_open()
int catweaselmkiii_open (void)
Referenced by sid_engine_set().
catweaselmkiii_read()
int catweaselmkiii_read (uint16_t addr, int chipno)
Referenced by set_sound_func().
catweaselmkiii_set_machine_parameter()
void catweaselmkiii_set_machine_parameter (long cycles_per_sec)
Referenced by sid_set_machine_parameter().
catweaselmkiii_state_read()
void catweaselmkiii_state_read (int chipno, struct sid_cw3_snapshot_state_s * sid_state)
catweaselmkiii_state_write()
void catweaselmkiii_state_write (int chipno, struct sid_cw3_snapshot_state_s * sid_state)
catweaselmkiii_store()
void catweaselmkiii_store (uint16_t addr, uint8_t val, int chipno)
Referenced by set_sound_func().