x128: raster/raster-canvas.h File Reference
raster-canvas.h File Reference
Data Structures
struct raster_canvas_area_s
A simple convenience type for defining a rectangular area on the screen.
Typedefs
typedef struct raster_canvas_area_s raster_canvas_area_t
Functions
void raster_canvas_init (struct raster_s *raster)
void raster_canvas_shutdown (struct raster_s *raster)
void raster_canvas_handle_end_of_frame (struct raster_s *raster)
void raster_canvas_update_all (struct raster_s *raster)
Typedef Documentation
raster_canvas_area_t
typedef struct raster_canvas_area_s raster_canvas_area_t
Function Documentation
raster_canvas_handle_end_of_frame()
void raster_canvas_handle_end_of_frame (struct raster_s * raster)
Referenced by raster_line_emulate(), and vdc_raster_draw_alarm_handler().
raster_canvas_init()
void raster_canvas_init (struct raster_s * raster)
raster_canvas_shutdown()
void raster_canvas_shutdown (struct raster_s * raster)
Referenced by raster_shutdown().
raster_canvas_update_all()
void raster_canvas_update_all (struct raster_s * raster)