vsid: core/fmopl.c File Reference
fmopl.c File Reference
#include "vice.h"
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "fmopl.h"
#include "lib.h"
#include "maincpu.h"
#include "snapshot.h"
Macros
#define FINAL_SH (0)
#define MAXOUT (+32767)
#define MINOUT (-32768)
#define FREQ_SH 16
16.16 fixed point (frequency calculations)
#define EG_SH 16
16.16 fixed point (EG timing)
#define LFO_SH 24
8.24 fixed point (LFO calculations)
#define TIMER_SH 16
16.16 fixed point (timers calculations)
#define FREQ_MASK ((1 << FREQ_SH) - 1)
#define ENV_BITS 10
envelope output entries
#define ENV_LEN (1 << ENV_BITS)
#define ENV_STEP (128.0 / ENV_LEN)
#define MAX_ATT_INDEX ((1 << (ENV_BITS - 1)) - 1) /*511*/
#define MIN_ATT_INDEX (0)
#define SIN_BITS 10
sinwave entries
#define SIN_LEN (1u << SIN_BITS)
#define SIN_MASK (SIN_LEN - 1)
#define TL_RES_LEN (256)
8 bits addressing (real chip)
#define SLOT1 0
register number to channel number , slot offset
#define SLOT2 1
#define EG_ATT 4
Envelope Generator phases.
#define EG_DEC 3
#define EG_SUS 2
#define EG_REL 1
#define EG_OFF 0
#define OPL_TYPE_WAVESEL 0x01
waveform select
#define OPL_TYPE_ADPCM 0x02
DELTA-T ADPCM unit
#define OPL_TYPE_KEYBOARD 0x04
keyboard interface
#define OPL_TYPE_IO 0x08
I/O port
#define OPL_TYPE_YM3526 (0)
#define OPL_TYPE_YM3812 (OPL_TYPE_WAVESEL)
#define DV (0.1875 / 2.0)
key scale level
#define SC(db) (UINT32)(db * (2.0 / ENV_STEP))
sustain level table (3dB per step)
#define RATE_STEPS (8)
#define O(a) (a * RATE_STEPS)
#define O(a) (a * 1)
#define ML 2
multiple table
#define TL_TAB_LEN (12 * 2 * TL_RES_LEN)
#define ENV_QUIET (TL_TAB_LEN >> 4)
#define LFO_AM_TAB_ELEMENTS 210
#define volume_calc(OP) ((OP)->TLL + ((UINT32)(OP)->volume) + (LFO_AM & (OP)->AMmask))
#define MAX_OPL_CHIPS 2
#define CART_DUMP_VER_MAJOR 0
snapshot support functions
#define CART_DUMP_VER_MINOR 0
#define SNAP_MODULE_NAME "YM3526"
Functions
static int OPLTimerOver (FM_OPL *OPL, int c)
timer support functions
void fmopl_set_machine_parameter (long clock_rate)
static void fmopl_alarm_A (CLOCK offset, void *data)
static void fmopl_alarm_B (CLOCK offset, void *data)
static int limit (int val, int max, int min)
static void OPL_STATUS_SET (FM_OPL *OPL, int flag)
status set and IRQ handling
static void OPL_STATUS_RESET (FM_OPL *OPL, int flag)
status reset and IRQ handling
static void OPL_STATUSMASK_SET (FM_OPL *OPL, int flag)
IRQ mask set.
static void advance_lfo (FM_OPL *OPL)
advance LFO to next sample
static void advance (FM_OPL *OPL)
advance to next sample
static signed int op_calc (UINT32 phase, unsigned int env, signed int pm, unsigned int wave_tab)
static signed int op_calc1 (UINT32 phase, unsigned int env, signed int pm, unsigned int wave_tab)
static void OPL_CALC_CH (OPL_CH *CH)
calculate output
static void OPL_CALC_RH (OPL_CH *CH, unsigned int noise)
calculate rhythm
static int init_tables (void)
generic table initialize
static void OPLCloseTable (void)
static void OPL_initalize (FM_OPL *OPL)
static void FM_KEYON (OPL_SLOT *SLOT, UINT32 key_set)
static void FM_KEYOFF (OPL_SLOT *SLOT, UINT32 key_clr)
static void CALC_FCSLOT (OPL_CH *CH, OPL_SLOT *SLOT)
update phase increment counter of operator (also update the EG rates if necessary)
static void set_mul (FM_OPL *OPL, int slot, int v)
set multi,am,vib,EG-TYP,KSR,mul
static void set_ksl_tl (FM_OPL *OPL, int slot, int v)
set ksl & tl
static void set_ar_dr (FM_OPL *OPL, int slot, int v)
set attack rate & decay rate
static void set_sl_rr (FM_OPL *OPL, int slot, int v)
set sustain level & release rate
static void OPLWriteReg (FM_OPL *OPL, int r, int v)
write a value v to register r on OPL chip
static int OPL_LockTable (void)
lock/unlock for common table
static void OPL_UnLockTable (void)
static void OPLResetChip (FM_OPL *OPL)
static FM_OPL * OPLCreate (UINT32 clock, UINT32 rate, int type)
Create one of virtual YM3812/YM3526.
static void OPLDestroy (FM_OPL *OPL)
Destroy one of virtual YM3812.
static int OPLWrite (FM_OPL *OPL, int a, int v)
static unsigned char OPLRead (FM_OPL *OPL, int a)
static void CSMKeyControll (OPL_CH *CH)
CSM Key Controll.
FM_OPL * ym3812_init (UINT32 clock, UINT32 rate)
int connect1_is_output0 (int *connect)
void set_connect1 (FM_OPL *chip, int x, int y, int output0)
void ym3812_shutdown (FM_OPL *chip)
void ym3812_reset_chip (FM_OPL *chip)
int ym3812_write (FM_OPL *chip, int a, int v)
unsigned char ym3812_read (FM_OPL *chip, int a)
unsigned char ym3812_peek (FM_OPL *chip, int a)
int ym3812_timer_over (FM_OPL *chip, int c)
void ym3812_update_one (FM_OPL *chip, OPLSAMPLE *buffer, int length)
FM_OPL * ym3526_init (UINT32 clock, UINT32 rate)
void ym3526_shutdown (FM_OPL *chip)
void ym3526_reset_chip (FM_OPL *chip)
int ym3526_write (FM_OPL *chip, int a, int v)
unsigned char ym3526_read (FM_OPL *chip, int a)
unsigned char ym3526_peek (FM_OPL *chip, int a)
int ym3526_timer_over (FM_OPL *chip, int c)
void ym3526_update_one (FM_OPL *chip, OPLSAMPLE *buffer, int length)
int ym3526_snapshot_write_module (snapshot_t *s)
int ym3526_snapshot_read_module (snapshot_t *s)
Variables
static const int slot_array [32]
mapping of register number (offset) to slot number used by the emulator
static const double ksl_tab [8 *16]
static const UINT32 sl_tab [16]
static const unsigned char eg_inc [15 *(8)]
static const unsigned char eg_rate_select [16+64+16]
static const unsigned char eg_rate_shift [16+64+16]
static const double mul_tab [16]
static signed int tl_tab [(12 *2 *(256))]
static unsigned int sin_tab [(1u<< 10) *4]
sin waveform table in 'decibel' scale
static const UINT8 lfo_am_table [210]
static const INT8 lfo_pm_table [8 *8 *2]
LFO Phase Modulation table (verified on real YM3812)
static int num_lock = 0
lock level of common table
static void * cur_chip = NULL
static OPL_SLOT * SLOT7_1
static OPL_SLOT * SLOT7_2
static OPL_SLOT * SLOT8_1
static OPL_SLOT * SLOT8_2
static signed int phase_modulation
static signed int output [1]
static UINT32 LFO_AM
static INT32 LFO_PM
static UINT32 fmopl_timer_80 = 0
static UINT32 fmopl_timer_320 = 0
Macro Definition Documentation
CART_DUMP_VER_MAJOR
#define CART_DUMP_VER_MAJOR 0
snapshot support functions
CART_DUMP_VER_MINOR
#define CART_DUMP_VER_MINOR 0
DV
#define DV (0.1875 / 2.0)
key scale level
table is 3dB/octave , DV converts this into 6dB/octave
0.1875 is bit 0 weight of the envelope counter (volume) expressed in the 'decibel' scale
EG_ATT
#define EG_ATT 4
Envelope Generator phases.
EG_DEC
#define EG_DEC 3
EG_OFF
#define EG_OFF 0
EG_REL
#define EG_REL 1
EG_SH
#define EG_SH 16
16.16 fixed point (EG timing)
EG_SUS
#define EG_SUS 2
ENV_BITS
#define ENV_BITS 10
envelope output entries
ENV_LEN
#define ENV_LEN (1 << ENV_BITS)
ENV_QUIET
#define ENV_QUIET (TL_TAB_LEN >> 4)
ENV_STEP
#define ENV_STEP (128.0 / ENV_LEN)
FINAL_SH
#define FINAL_SH (0)
FREQ_MASK
#define FREQ_MASK ((1 << FREQ_SH) - 1)
FREQ_SH
#define FREQ_SH 16
16.16 fixed point (frequency calculations)
LFO_AM_TAB_ELEMENTS
#define LFO_AM_TAB_ELEMENTS 210
LFO_SH
#define LFO_SH 24
8.24 fixed point (LFO calculations)
MAX_ATT_INDEX
#define MAX_ATT_INDEX ((1 << (ENV_BITS - 1)) - 1) /*511*/
MAX_OPL_CHIPS
#define MAX_OPL_CHIPS 2
MAXOUT
#define MAXOUT (+32767)
MIN_ATT_INDEX
#define MIN_ATT_INDEX (0)
MINOUT
#define MINOUT (-32768)
ML
#define ML 2
multiple table
O [1/2]
#define O (a) (a * RATE_STEPS)
O [2/2]
#define O (a) (a * 1)
OPL_TYPE_ADPCM
#define OPL_TYPE_ADPCM 0x02
DELTA-T ADPCM unit
OPL_TYPE_IO
#define OPL_TYPE_IO 0x08
I/O port
OPL_TYPE_KEYBOARD
#define OPL_TYPE_KEYBOARD 0x04
keyboard interface
OPL_TYPE_WAVESEL
#define OPL_TYPE_WAVESEL 0x01
waveform select
OPL_TYPE_YM3526
#define OPL_TYPE_YM3526 (0)
OPL_TYPE_YM3812
#define OPL_TYPE_YM3812 (OPL_TYPE_WAVESEL)
RATE_STEPS
#define RATE_STEPS (8)
SC
#define SC (db) (UINT32)(db * (2.0 / ENV_STEP))
sustain level table (3dB per step)
SIN_BITS
#define SIN_BITS 10
sinwave entries
SIN_LEN
#define SIN_LEN (1u << SIN_BITS)
SIN_MASK
#define SIN_MASK (SIN_LEN - 1)
SLOT1
#define SLOT1 0
register number to channel number , slot offset
SLOT2
#define SLOT2 1
SNAP_MODULE_NAME
#define SNAP_MODULE_NAME "YM3526"
TIMER_SH
#define TIMER_SH 16
16.16 fixed point (timers calculations)
TL_RES_LEN
#define TL_RES_LEN (256)
8 bits addressing (real chip)
TL_TAB_LEN
#define TL_TAB_LEN (12 * 2 * TL_RES_LEN)
volume_calc
#define volume_calc (OP) ((OP)->TLL + ((UINT32)(OP)->volume) + (LFO_AM & (OP)->AMmask))
Function Documentation
advance()
static void advance (FM_OPL * OPL) inline static
advance to next sample
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
Referenced by ym3526_update_one(), and ym3812_update_one().
advance_lfo()
static void advance_lfo (FM_OPL * OPL) inline static
advance LFO to next sample
< 8.24 fixed point (LFO calculations)
< 8.24 fixed point (LFO calculations)
< 8.24 fixed point (LFO calculations)
< 8.24 fixed point (LFO calculations)
Referenced by ym3526_update_one(), and ym3812_update_one().
CALC_FCSLOT()
static void CALC_FCSLOT (OPL_CH * CH, OPL_SLOT * SLOT) inline static
update phase increment counter of operator (also update the EG rates if necessary)
Referenced by OPLWriteReg(), and set_mul().
connect1_is_output0()
int connect1_is_output0 (int * connect)
CSMKeyControll()
static void CSMKeyControll (OPL_CH * CH) inline static
CSM Key Controll.
Referenced by OPLTimerOver().
FM_KEYOFF()
static void FM_KEYOFF (OPL_SLOT * SLOT, UINT32 key_clr) inline static
Referenced by CSMKeyControll(), and OPLWriteReg().
FM_KEYON()
static void FM_KEYON (OPL_SLOT * SLOT, UINT32 key_set) inline static
Referenced by CSMKeyControll(), and OPLWriteReg().
fmopl_alarm_A()
static void fmopl_alarm_A (CLOCK offset, void * data) static
Referenced by OPLCreate().
fmopl_alarm_B()
static void fmopl_alarm_B (CLOCK offset, void * data) static
Referenced by OPLCreate().
fmopl_set_machine_parameter()
void fmopl_set_machine_parameter (long clock_rate)
Referenced by machine_change_timing(), and machine_specific_init().
init_tables()
static int init_tables (void) static
generic table initialize
< 8 bits addressing (real chip)
< 8 bits addressing (real chip)
< 8 bits addressing (real chip)
< 8 bits addressing (real chip)
< 8 bits addressing (real chip)
< 8 bits addressing (real chip)
Referenced by OPL_LockTable().
limit()
static int limit (int val, int max, int min) inline static
Referenced by cbmdos_command_parse_plus(), drivemem_set_func(), mem_mmu_translate(), mem_read_limit_set(), vdrive_dir_first_directory(), vdrive_dir_part_first_directory(), ym3526_update_one(), and ym3812_update_one().
op_calc()
static signed int op_calc (UINT32 phase, unsigned int env, signed int pm, unsigned int wave_tab) inline static
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 8 bits addressing (real chip)
Referenced by OPL_CALC_CH(), and OPL_CALC_RH().
op_calc1()
static signed int op_calc1 (UINT32 phase, unsigned int env, signed int pm, unsigned int wave_tab) inline static
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 8 bits addressing (real chip)
Referenced by OPL_CALC_CH(), and OPL_CALC_RH().
OPL_CALC_CH()
static void OPL_CALC_CH (OPL_CH * CH) inline static
calculate output
< 8 bits addressing (real chip)
< 8 bits addressing (real chip)
Referenced by ym3526_update_one(), and ym3812_update_one().
OPL_CALC_RH()
static void OPL_CALC_RH (OPL_CH * CH, unsigned int noise) inline static
calculate rhythm
< 8 bits addressing (real chip)
< 8 bits addressing (real chip)
< 8 bits addressing (real chip)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 8 bits addressing (real chip)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 8 bits addressing (real chip)
< 8 bits addressing (real chip)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (frequency calculations)
Referenced by ym3526_update_one(), and ym3812_update_one().
OPL_initalize()
static void OPL_initalize (FM_OPL * OPL) static
< 16.16 fixed point (frequency calculations)
< 8.24 fixed point (LFO calculations)
< 8.24 fixed point (LFO calculations)
< 16.16 fixed point (frequency calculations)
< 16.16 fixed point (EG timing)
< 16.16 fixed point (EG timing)
Referenced by OPLCreate().
OPL_LockTable()
static int OPL_LockTable (void) static
lock/unlock for common table
Referenced by OPLCreate().
OPL_STATUS_RESET()
static void OPL_STATUS_RESET (FM_OPL * OPL, int flag) inline static
status reset and IRQ handling
Referenced by OPL_STATUSMASK_SET(), OPLResetChip(), and OPLWriteReg().
OPL_STATUS_SET()
static void OPL_STATUS_SET (FM_OPL * OPL, int flag) inline static
status set and IRQ handling
Referenced by OPL_STATUSMASK_SET(), and OPLTimerOver().
OPL_STATUSMASK_SET()
static void OPL_STATUSMASK_SET (FM_OPL * OPL, int flag) inline static
IRQ mask set.
Referenced by OPLWriteReg().
OPL_UnLockTable()
static void OPL_UnLockTable (void) static
Referenced by OPLDestroy().
OPLCloseTable()
static void OPLCloseTable (void) static
Referenced by OPL_UnLockTable().
OPLCreate()
static FM_OPL * OPLCreate (UINT32 clock, UINT32 rate, int type) static
Create one of virtual YM3812/YM3526.
'clock' is chip clock in Hz
'rate' is sampling rate
Referenced by ym3526_init(), and ym3812_init().
OPLDestroy()
static void OPLDestroy (FM_OPL * OPL) static
Destroy one of virtual YM3812.
Referenced by ym3526_shutdown(), and ym3812_shutdown().
OPLRead()
static unsigned char OPLRead (FM_OPL * OPL, int a) static
Referenced by ym3526_peek(), ym3526_read(), ym3812_peek(), and ym3812_read().
OPLResetChip()
static void OPLResetChip (FM_OPL * OPL) static
Referenced by ym3526_reset_chip(), and ym3812_reset_chip().
OPLTimerOver()
static int OPLTimerOver (FM_OPL * OPL, int c) static
timer support functions
Referenced by fmopl_alarm_A(), fmopl_alarm_B(), ym3526_timer_over(), and ym3812_timer_over().
OPLWrite()
static int OPLWrite (FM_OPL * OPL, int a, int v) static
Referenced by ym3526_write(), and ym3812_write().
OPLWriteReg()
static void OPLWriteReg (FM_OPL * OPL, int r, int v) static
write a value v to register r on OPL chip
< waveform select
Referenced by OPLResetChip(), and OPLWrite().
set_ar_dr()
static void set_ar_dr (FM_OPL * OPL, int slot, int v) inline static
set attack rate & decay rate
Referenced by OPLWriteReg().
set_connect1()
void set_connect1 (FM_OPL * chip, int x, int y, int output0)
set_ksl_tl()
static void set_ksl_tl (FM_OPL * OPL, int slot, int v) inline static
set ksl & tl
Referenced by OPLWriteReg().
set_mul()
static void set_mul (FM_OPL * OPL, int slot, int v) inline static
set multi,am,vib,EG-TYP,KSR,mul
Referenced by OPLWriteReg().
set_sl_rr()
static void set_sl_rr (FM_OPL * OPL, int slot, int v) inline static
set sustain level & release rate
Referenced by OPLWriteReg().
ym3526_init()
FM_OPL * ym3526_init (UINT32 clock, UINT32 rate)
ym3526_peek()
unsigned char ym3526_peek (FM_OPL * chip, int a)
ym3526_read()
unsigned char ym3526_read (FM_OPL * chip, int a)
ym3526_reset_chip()
void ym3526_reset_chip (FM_OPL * chip)
Referenced by ym3526_init().
ym3526_shutdown()
void ym3526_shutdown (FM_OPL * chip)
ym3526_snapshot_read_module()
int ym3526_snapshot_read_module (snapshot_t * s)
ym3526_snapshot_write_module()
int ym3526_snapshot_write_module (snapshot_t * s)
Todo:
FIXME: implement snapshot support
ym3526_timer_over()
int ym3526_timer_over (FM_OPL * chip, int c)
ym3526_update_one()
void ym3526_update_one (FM_OPL * chip, OPLSAMPLE * buffer, int length)
ym3526_write()
int ym3526_write (FM_OPL * chip, int a, int v)
ym3812_init()
FM_OPL * ym3812_init (UINT32 clock, UINT32 rate)
< waveform select
ym3812_peek()
unsigned char ym3812_peek (FM_OPL * chip, int a)
ym3812_read()
unsigned char ym3812_read (FM_OPL * chip, int a)
ym3812_reset_chip()
void ym3812_reset_chip (FM_OPL * chip)
Referenced by ym3812_init().
ym3812_shutdown()
void ym3812_shutdown (FM_OPL * chip)
ym3812_timer_over()
int ym3812_timer_over (FM_OPL * chip, int c)
ym3812_update_one()
void ym3812_update_one (FM_OPL * chip, OPLSAMPLE * buffer, int length)
ym3812_write()
int ym3812_write (FM_OPL * chip, int a, int v)
Variable Documentation
cur_chip
void* cur_chip = NULL static
Referenced by OPL_LockTable(), OPL_UnLockTable(), ym3526_update_one(), and ym3812_update_one().
eg_inc
const unsigned char eg_inc[15 *(8)] static
Initial value:
= {
 0, 1, 0, 1, 0, 1, 0, 1,
 0, 1, 0, 1, 1, 1, 0, 1,
 0, 1, 1, 1, 0, 1, 1, 1,
 0, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 2, 1, 1, 1, 2,
 1, 2, 1, 2, 1, 2, 1, 2,
 1, 2, 2, 2, 1, 2, 2, 2,
 2, 2, 2, 2, 2, 2, 2, 2,
 2, 2, 2, 4, 2, 2, 2, 4,
 2, 4, 2, 4, 2, 4, 2, 4,
 2, 4, 4, 4, 2, 4, 4, 4,
 4, 4, 4, 4, 4, 4, 4, 4,
 8, 8, 8, 8, 8, 8, 8, 8,
 0, 0, 0, 0, 0, 0, 0, 0,
}
Referenced by advance().
eg_rate_select
const unsigned char eg_rate_select[16+64+16] static
Initial value:
= {
    ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ),
    ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ), ( 14  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 0  *  (8) ), ( 1  *  (8) ), ( 2  *  (8) ), ( 3  *  (8) ),
    ( 4  *  (8) ), ( 5  *  (8) ), ( 6  *  (8) ), ( 7  *  (8) ),
    ( 8  *  (8) ), ( 9  *  (8) ), ( 10  *  (8) ), ( 11  *  (8) ),
    ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ),
    ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ),
    ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ), ( 12  *  (8) ),
}
Referenced by CALC_FCSLOT(), set_ar_dr(), and set_sl_rr().
eg_rate_shift
const unsigned char eg_rate_shift[16+64+16] static
Initial value:
= {
    ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1),
    ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1),
    ( 12  * 1), ( 12  * 1), ( 12  * 1), ( 12  * 1),
    ( 11  * 1), ( 11  * 1), ( 11  * 1), ( 11  * 1),
    ( 10  * 1), ( 10  * 1), ( 10  * 1), ( 10  * 1),
    ( 9  * 1), ( 9  * 1), ( 9  * 1), ( 9  * 1),
    ( 8  * 1), ( 8  * 1), ( 8  * 1), ( 8  * 1),
    ( 7  * 1), ( 7  * 1), ( 7  * 1), ( 7  * 1),
    ( 6  * 1), ( 6  * 1), ( 6  * 1), ( 6  * 1),
    ( 5  * 1), ( 5  * 1), ( 5  * 1), ( 5  * 1),
    ( 4  * 1), ( 4  * 1), ( 4  * 1), ( 4  * 1),
    ( 3  * 1), ( 3  * 1), ( 3  * 1), ( 3  * 1),
    ( 2  * 1), ( 2  * 1), ( 2  * 1), ( 2  * 1),
    ( 1  * 1), ( 1  * 1), ( 1  * 1), ( 1  * 1),
    ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1),
    ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1),
    ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1),
    ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1),
    ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1),
    ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1), ( 0  * 1),
}
Referenced by CALC_FCSLOT(), set_ar_dr(), and set_sl_rr().
fmopl_timer_320
UINT32 fmopl_timer_320 = 0 static
Referenced by fmopl_alarm_B(), fmopl_set_machine_parameter(), and OPLWriteReg().
fmopl_timer_80
UINT32 fmopl_timer_80 = 0 static
Referenced by fmopl_alarm_A(), fmopl_set_machine_parameter(), and OPLWriteReg().
ksl_tab
const double ksl_tab[8 *16] static
Initial value:
= {
    0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) ,
    0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) ,
    0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) ,
    0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) ,
    0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) ,
    0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) ,
    0.000 /  (0.1875 / 2.0) , 0.750 /  (0.1875 / 2.0) , 1.125 /  (0.1875 / 2.0) , 1.500 /  (0.1875 / 2.0) ,
    1.875 /  (0.1875 / 2.0) , 2.250 /  (0.1875 / 2.0) , 2.625 /  (0.1875 / 2.0) , 3.000 /  (0.1875 / 2.0) ,
    0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) ,
    0.000 /  (0.1875 / 2.0) , 1.125 /  (0.1875 / 2.0) , 1.875 /  (0.1875 / 2.0) , 2.625 /  (0.1875 / 2.0) ,
    3.000 /  (0.1875 / 2.0) , 3.750 /  (0.1875 / 2.0) , 4.125 /  (0.1875 / 2.0) , 4.500 /  (0.1875 / 2.0) ,
    4.875 /  (0.1875 / 2.0) , 5.250 /  (0.1875 / 2.0) , 5.625 /  (0.1875 / 2.0) , 6.000 /  (0.1875 / 2.0) ,
    0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 0.000 /  (0.1875 / 2.0) , 1.875 /  (0.1875 / 2.0) ,
    3.000 /  (0.1875 / 2.0) , 4.125 /  (0.1875 / 2.0) , 4.875 /  (0.1875 / 2.0) , 5.625 /  (0.1875 / 2.0) ,
    6.000 /  (0.1875 / 2.0) , 6.750 /  (0.1875 / 2.0) , 7.125 /  (0.1875 / 2.0) , 7.500 /  (0.1875 / 2.0) ,
    7.875 /  (0.1875 / 2.0) , 8.250 /  (0.1875 / 2.0) , 8.625 /  (0.1875 / 2.0) , 9.000 /  (0.1875 / 2.0) ,
     0.000 /  (0.1875 / 2.0) ,  0.000 /  (0.1875 / 2.0) ,  3.000 /  (0.1875 / 2.0) ,  4.875 /  (0.1875 / 2.0) ,
     6.000 /  (0.1875 / 2.0) ,  7.125 /  (0.1875 / 2.0) ,  7.875 /  (0.1875 / 2.0) ,  8.625 /  (0.1875 / 2.0) ,
     9.000 /  (0.1875 / 2.0) ,  9.750 /  (0.1875 / 2.0) , 10.125 /  (0.1875 / 2.0) , 10.500 /  (0.1875 / 2.0) ,
    10.875 /  (0.1875 / 2.0) , 11.250 /  (0.1875 / 2.0) , 11.625 /  (0.1875 / 2.0) , 12.000 /  (0.1875 / 2.0) ,
     0.000 /  (0.1875 / 2.0) ,  3.000 /  (0.1875 / 2.0) ,  6.000 /  (0.1875 / 2.0) ,  7.875 /  (0.1875 / 2.0) ,
     9.000 /  (0.1875 / 2.0) , 10.125 /  (0.1875 / 2.0) , 10.875 /  (0.1875 / 2.0) , 11.625 /  (0.1875 / 2.0) ,
    12.000 /  (0.1875 / 2.0) , 12.750 /  (0.1875 / 2.0) , 13.125 /  (0.1875 / 2.0) , 13.500 /  (0.1875 / 2.0) ,
    13.875 /  (0.1875 / 2.0) , 14.250 /  (0.1875 / 2.0) , 14.625 /  (0.1875 / 2.0) , 15.000 /  (0.1875 / 2.0) ,
     0.000 /  (0.1875 / 2.0) ,  6.000 /  (0.1875 / 2.0) ,  9.000 /  (0.1875 / 2.0) , 10.875 /  (0.1875 / 2.0) ,
    12.000 /  (0.1875 / 2.0) , 13.125 /  (0.1875 / 2.0) , 13.875 /  (0.1875 / 2.0) , 14.625 /  (0.1875 / 2.0) ,
    15.000 /  (0.1875 / 2.0) , 15.750 /  (0.1875 / 2.0) , 16.125 /  (0.1875 / 2.0) , 16.500 /  (0.1875 / 2.0) ,
    16.875 /  (0.1875 / 2.0) , 17.250 /  (0.1875 / 2.0) , 17.625 /  (0.1875 / 2.0) , 18.000 /  (0.1875 / 2.0) ,
     0.000 /  (0.1875 / 2.0) ,  9.000 /  (0.1875 / 2.0) , 12.000 /  (0.1875 / 2.0) , 13.875 /  (0.1875 / 2.0) ,
    15.000 /  (0.1875 / 2.0) , 16.125 /  (0.1875 / 2.0) , 16.875 /  (0.1875 / 2.0) , 17.625 /  (0.1875 / 2.0) ,
    18.000 /  (0.1875 / 2.0) , 18.750 /  (0.1875 / 2.0) , 19.125 /  (0.1875 / 2.0) , 19.500 /  (0.1875 / 2.0) ,
    19.875 /  (0.1875 / 2.0) , 20.250 /  (0.1875 / 2.0) , 20.625 /  (0.1875 / 2.0) , 21.000 /  (0.1875 / 2.0)
}
Referenced by OPLWriteReg().
LFO_AM
UINT32 LFO_AM static
Referenced by advance_lfo().
lfo_am_table
const UINT8 lfo_am_table[210] static
Initial value:
= {
    0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1,
    2, 2, 2, 2,
    3, 3, 3, 3,
    4, 4, 4, 4,
    5, 5, 5, 5,
    6, 6, 6, 6,
    7, 7, 7, 7,
    8, 8, 8, 8,
    9, 9, 9, 9,
    10, 10, 10, 10,
    11, 11, 11, 11,
    12, 12, 12, 12,
    13, 13, 13, 13,
    14, 14, 14, 14,
    15, 15, 15, 15,
    16, 16, 16, 16,
    17, 17, 17, 17,
    18, 18, 18, 18,
    19, 19, 19, 19,
    20, 20, 20, 20,
    21, 21, 21, 21,
    22, 22, 22, 22,
    23, 23, 23, 23,
    24, 24, 24, 24,
    25, 25, 25, 25,
    26, 26, 26,
    25, 25, 25, 25,
    24, 24, 24, 24,
    23, 23, 23, 23,
    22, 22, 22, 22,
    21, 21, 21, 21,
    20, 20, 20, 20,
    19, 19, 19, 19,
    18, 18, 18, 18,
    17, 17, 17, 17,
    16, 16, 16, 16,
    15, 15, 15, 15,
    14, 14, 14, 14,
    13, 13, 13, 13,
    12, 12, 12, 12,
    11, 11, 11, 11,
    10, 10, 10, 10,
    9, 9, 9, 9,
    8, 8, 8, 8,
    7, 7, 7, 7,
    6, 6, 6, 6,
    5, 5, 5, 5,
    4, 4, 4, 4,
    3, 3, 3, 3,
    2, 2, 2, 2,
    1, 1, 1, 1
}
Referenced by advance_lfo().
LFO_PM
INT32 LFO_PM static
Referenced by advance(), and advance_lfo().
lfo_pm_table
const INT8 lfo_pm_table[8 *8 *2] static
Initial value:
= {
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    1, 0, 0, 0, -1, 0, 0, 0,
    1, 0, 0, 0, -1, 0, 0, 0,
    2, 1, 0, -1, -2, -1, 0, 1,
    1, 0, 0, 0, -1, 0, 0, 0,
    3, 1, 0, -1, -3, -1, 0, 1,
    2, 1, 0, -1, -2, -1, 0, 1,
    4, 2, 0, -2, -4, -2, 0, 2,
    2, 1, 0, -1, -2, -1, 0, 1,
    5, 2, 0, -2, -5, -2, 0, 2,
    3, 1, 0, -1, -3, -1, 0, 1,
    6, 3, 0, -3, -6, -3, 0, 3,
    3, 1, 0, -1, -3, -1, 0, 1,
    7, 3, 0, -3, -7, -3, 0, 3
}
LFO Phase Modulation table (verified on real YM3812)
Referenced by advance().
mul_tab
const double mul_tab[16] static
Initial value:
= {
    0.50 *  2 , 1.00 *  2 , 2.00 *  2 , 3.00 *  2 , 4.00 *  2 , 5.00 *  2 , 6.00 *  2 , 7.00 *  2 ,
    8.00 *  2 , 9.00 *  2 , 10.00 *  2 , 10.00 *  2 , 12.00 *  2 , 12.00 *  2 , 15.00 *  2 , 15.00 *  2
}
Referenced by set_mul().
num_lock
int num_lock = 0 static
lock level of common table
Referenced by OPL_LockTable(), and OPL_UnLockTable().
output
signed int output[1] static
Referenced by array_compact(), connect1_is_output0(), merge_aggregate_contexts(), OPL_CALC_CH(), OPL_CALC_RH(), OPLResetChip(), OPLWriteReg(), render_subframe(), set_connect1(), userport_spt_joystick_store_pbx(), write_string(), write_uint16(), write_uint32(), ym3526_update_one(), and ym3812_update_one().
phase_modulation
signed int phase_modulation static
Referenced by OPL_CALC_CH(), OPL_CALC_RH(), OPLWriteReg(), and set_connect1().
sin_tab
unsigned int sin_tab[(1u<< 10) *4] static
sin waveform table in 'decibel' scale
four waveforms on OPL2 type chips
Referenced by init_tables(), op_calc(), and op_calc1().
sl_tab
const UINT32 sl_tab[16] static
Initial value:
= {
    (UINT32)( 0  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 1  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 2  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 3  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 4  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 5  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 6  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 7  * (2.0 /  (128.0 /  (1 <<  10 ) ) )),
    (UINT32)( 8  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 9  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 10  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 11  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 12  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 13  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 14  * (2.0 /  (128.0 /  (1 <<  10 ) ) )), (UINT32)( 31  * (2.0 /  (128.0 /  (1 <<  10 ) ) ))
}
Referenced by set_sl_rr().
SLOT7_1
OPL_SLOT* SLOT7_1 static
Referenced by OPL_CALC_RH(), ym3526_update_one(), and ym3812_update_one().
SLOT7_2
OPL_SLOT * SLOT7_2 static
Referenced by OPL_CALC_RH(), ym3526_update_one(), and ym3812_update_one().
SLOT8_1
OPL_SLOT * SLOT8_1 static
Referenced by OPL_CALC_RH(), ym3526_update_one(), and ym3812_update_one().
SLOT8_2
OPL_SLOT * SLOT8_2 static
Referenced by OPL_CALC_RH(), ym3526_update_one(), and ym3812_update_one().
slot_array
const int slot_array[32] static
Initial value:
= {
    0, 2, 4, 1, 3, 5, -1, -1,
    6, 8, 10, 7, 9, 11, -1, -1,
    12, 14, 16, 13, 15, 17, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1
}
mapping of register number (offset) to slot number used by the emulator
Referenced by OPLWriteReg().
tl_tab
signed int tl_tab[(12 *2 *(256))] static
Referenced by init_tables(), op_calc(), and op_calc1().