vsid: arch/gtk3/uisettings.c File Reference
uisettings.c File Reference
GTK3 main settings dialog.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include "archdep.h"
#include "cartridge.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "ui.h"
#include "uiactions.h"
#include "uimachinewindow.h"
#include "util.h"
#include "vice_gtk3.h"
#include "settings_autofire.h"
#include "settings_autostart.h"
#include "settings_burstmode.h"
#include "settings_c128fullbanks.h"
#include "settings_c128functionrom.h"
#include "settings_c64memhacks.h"
#include "settings_c64dtvflash.h"
#include "settings_controlport.h"
#include "settings_cpm.h"
#include "settings_crt.h"
#include "settings_default_cart.h"
#include "settings_digimax.h"
#include "settings_dqbb.h"
#include "settings_drive.h"
#include "settings_ds12c887.h"
#include "settings_easyflash.h"
#include "settings_environment.h"
#include "settings_expert.h"
#include "settings_finalexpansion.h"
#include "settings_fsdevice.h"
#include "settings_georam.h"
#include "settings_gmod2.h"
#include "settings_gmod2c128.h"
#include "settings_gmod3.h"
#include "settings_host_display.h"
#include "settings_hotkeys.h"
#include "settings_hvsc.h"
#include "settings_ide64.h"
#include "settings_ieee488.h"
#include "settings_ieeeflash64.h"
#include "settings_io.h"
#include "settings_isepic.h"
#include "settings_jam.h"
#include "settings_joystick.h"
#include "settings_keyboard.h"
#include "settings_ltkernal.h"
#include "settings_magicvoice.h"
#include "settings_misc.h"
#include "settings_megacart.h"
#include "settings_mmc64.h"
#include "settings_mmcr.h"
#include "settings_model.h"
#include "settings_monitor.h"
#include "settings_netplay.h"
#include "settings_petcolourgraphics.h"
#include "settings_petdww.h"
#include "settings_pethre.h"
#include "settings_petreu.h"
#include "settings_plus4digiblaster.h"
#include "settings_printer.h"
#include "settings_ramcart.h"
#include "settings_ramlink.h"
#include "settings_ramreset.h"
#include "settings_retroreplay.h"
#include "settings_reu.h"
#include "settings_rexramfloppy.h"
#include "settings_rom.h"
#include "settings_rs232.h"
#include "settings_sampler.h"
#include "settings_scpu64.h"
#include "settings_sfxsoundexpander.h"
#include "settings_sfxsoundsampler.h"
#include "settings_sidcart.h"
#include "settings_snapshot.h"
#include "settings_sound.h"
#include "settings_soundchip.h"
#include "settings_speed.h"
#include "settings_supersnapshotv5.h"
#include "settings_tapeport.h"
#include "settings_ultimem.h"
#include "settings_userport.h"
#include "settings_vfli.h"
#include "settings_vicflashplugin.h"
#include "settings_vicieee488.h"
#include "settings_vicioram.h"
#include "settings_video.h"
#include "uisettings.h"
Macros
#define TREEVIEW_CSS
CSS to allow collapsing/expanding tree nodes with crsr keys.
#define NUM_COLUMNS 3
Number of columns in the tree model.
#define DIALOG_WIDTH 920
Initial dialog width.
#define DIALOG_WIDTH_TOLERANCE 20
Tolerated extra dialog width added by decorations/theme.
#define DIALOG_HEIGHT 560
Initial dialog height.
#define DIALOG_HEIGHT_TOLERANCE 60
Tolerated extra dialog height added by decorations/theme.
#define DIALOG_WIDTH_MAX 1024
Maximum width the UI can be.
#define DIALOG_HEIGHT_MAX 640
Maximum height the UI can be.
Enumerations
enum {
COLUMN_NAME = 0 ,
COLUMN_ID ,
COLUMN_CALLBACK
}
Column indici for the tree model.
enum {
RESPONSE_RESET = 1 ,
RESPONSE_FACTORY ,
RESPONSE_DEFAULT
}
Enum used for the "response" callback of the settings dialog.
Functions
static void ui_settings_set_central_widget (GtkWidget *widget)
}}}
static void on_settings_dialog_destroy (GtkWidget *widget, gpointer data)
Handler for the "destroy" event of the main dialog.
static void on_close_clicked (GtkWidget *widget, gpointer dialog)
Handler for the 'clicked' event of our own "Close" button.
static void on_row_activated (GtkTreeView *tree_view, GtkTreePath *path, GtkTreeViewColumn *column, gpointer user_data)
Handler for the double click event of a tree node.
static GtkWidget * ui_settings_inital_widget (GtkWidget *parent)
Create the widget that is initially shown in the settings UI.
static void on_tree_selection_changed (GtkTreeSelection *selection, gpointer user_data)
Handler for the "changed" event of the tree view.
static GtkWidget * create_save_on_exit_checkbox (void)
Create the 'Save on exit' checkbox.
static GtkWidget * create_confirm_on_exit_checkbox (void)
Create the 'Confirm on exit' checkbox.
static GtkWidget * create_pause_on_settings_checkbox (void)
Create the 'Pause on settings dialog' checkbox.
static void create_tree_model (void)
Create empty tree model for the settings tree.
static GtkTreeStore * populate_tree_model (void)
Create tree store containing settings items and children.
static gboolean row_separator_func (GtkTreeModel *model, GtkTreeIter *iter, gpointer data)
Determine if the current tree item should be a separator.
static GtkWidget * create_treeview (void)
Create treeview for settings side-menu.
static GtkWidget * create_content_widget (GtkWidget *dialog)
Create the 'content widget' of the settings dialog.
static void response_callback (GtkWidget *widget, gint response_id, gpointer user_data)
Handler for the 'response' event of the settings dialog.
static gboolean on_dialog_configure_event (GtkWidget *widget, GdkEvent *event, gpointer data)
Respond to window size changes.
static GtkWidget * dialog_create_helper (void)
Dialog create helper.
static gboolean ui_settings_dialog_activate_node (const char *path)
Find and activate node in the tree view via path.
static gboolean ui_settings_dialog_show_impl (gpointer user_data)
Threaded UI handler for the settings dialog constructor.
void ui_settings_dialog_show (const char *path)
Menu callback for the settings dialog.
void ui_settings_shutdown (void)
Clean up resources used on emu exit.
Variables
static ui_settings_tree_node_t c64_cartridges []
{{{ c64_cartridges
static ui_settings_tree_node_t scpu64_cartridges []
}}}
static ui_settings_tree_node_t c128_cartridges []
}}}
static ui_settings_tree_node_t vic20_cartridges []
}}}
static ui_settings_tree_node_t plus4_io_extensions []
}}}
static ui_settings_tree_node_t cbm2_io_extensions []
}}}
static ui_settings_tree_node_t pet_io_extensions []
}}}
static ui_settings_tree_node_t main_nodes_vsid []
}}}
static ui_settings_tree_node_t host_nodes_generic []
}}}
static ui_settings_tree_node_t machine_nodes_c64 []
}}}
static ui_settings_tree_node_t display_nodes_c64 []
}}}
static ui_settings_tree_node_t audio_nodes_c64 []
}}}
static ui_settings_tree_node_t input_nodes_c64 []
}}}
static ui_settings_tree_node_t peripheral_nodes_c64 []
}}}
static ui_settings_tree_node_t main_nodes_c64 []
}}}
static ui_settings_tree_node_t machine_nodes_c64dtv []
}}}
static ui_settings_tree_node_t display_nodes_c64dtv []
}}}
static ui_settings_tree_node_t audio_nodes_c64dtv []
}}}
static ui_settings_tree_node_t input_nodes_c64dtv []
}}}
static ui_settings_tree_node_t peripheral_nodes_c64dtv []
}}}
static ui_settings_tree_node_t main_nodes_c64dtv []
}}}
static ui_settings_tree_node_t machine_nodes_c128 []
}}}
static ui_settings_tree_node_t display_nodes_c128 []
}}}
static ui_settings_tree_node_t audio_nodes_c128 []
}}}
static ui_settings_tree_node_t input_nodes_c128 []
}}}
static ui_settings_tree_node_t peripheral_nodes_c128 []
}}}
static ui_settings_tree_node_t main_nodes_c128 []
}}}
static ui_settings_tree_node_t machine_nodes_scpu64 []
}}}
static ui_settings_tree_node_t display_nodes_scpu64 []
}}}
static ui_settings_tree_node_t audio_nodes_scpu64 []
}}}
static ui_settings_tree_node_t input_nodes_scpu64 []
}}}
static ui_settings_tree_node_t peripheral_nodes_scpu64 []
}}}
static ui_settings_tree_node_t main_nodes_scpu64 []
}}}
static ui_settings_tree_node_t machine_nodes_vic20 []
}}}
static ui_settings_tree_node_t display_nodes_vic20 []
}}}
static ui_settings_tree_node_t audio_nodes_vic20 []
}}}
static ui_settings_tree_node_t input_nodes_vic20 []
}}}
static ui_settings_tree_node_t peripheral_nodes_vic20 []
}}}
static ui_settings_tree_node_t main_nodes_vic20 []
}}}
static ui_settings_tree_node_t machine_nodes_plus4 []
}}}
static ui_settings_tree_node_t display_nodes_plus4 []
}}}
static ui_settings_tree_node_t audio_nodes_plus4 []
}}}
static ui_settings_tree_node_t input_nodes_plus4 []
}}}
static ui_settings_tree_node_t peripheral_nodes_plus4 []
}}}
static ui_settings_tree_node_t main_nodes_plus4 []
}}}
static ui_settings_tree_node_t machine_nodes_pet []
}}}
static ui_settings_tree_node_t display_nodes_pet []
}}}
static ui_settings_tree_node_t audio_nodes_pet []
}}}
static ui_settings_tree_node_t input_nodes_pet []
}}}
static ui_settings_tree_node_t peripheral_nodes_pet []
}}}
static ui_settings_tree_node_t main_nodes_pet []
}}}
static ui_settings_tree_node_t machine_nodes_cbm5x0 []
}}}
static ui_settings_tree_node_t display_nodes_cbm5x0 []
}}}
static ui_settings_tree_node_t audio_nodes_cbm5x0 []
}}}
static ui_settings_tree_node_t input_nodes_cbm5x0 []
}}}
static ui_settings_tree_node_t peripheral_nodes_cbm5x0 []
}}}
static ui_settings_tree_node_t main_nodes_cbm5x0 []
}}}
static ui_settings_tree_node_t machine_nodes_cbm6x0 []
}}}
static ui_settings_tree_node_t display_nodes_cbm6x0 []
}}}
static ui_settings_tree_node_t audio_nodes_cbm6x0 []
}}}
static ui_settings_tree_node_t input_nodes_cbm6x0 []
}}}
static ui_settings_tree_node_t peripheral_nodes_cbm6x0 []
}}}
static ui_settings_tree_node_t main_nodes_cbm6x0 []
}}}
static int settings_old_pause_state
Old pause state when popping up the dialog.
static GtkWidget * settings_window = NULL
Reference to the settings dialog.
static gint settings_xpos = INT_MIN
Previous X position of settings dialog.
static gint settings_ypos = INT_MIN
Previous Y position of settings dialog.
static GtkWidget * settings_grid = NULL
Reference to the 'content area' widget of the settings dialog.
static GtkTreeStore * settings_model = NULL
Reference to the tree model for the settings tree.
static GtkWidget * settings_tree = NULL
Reference to the tree view for the settings tree.
static GtkWidget * scrolled_window = NULL
Scroll window container for the settings treeview.
static GtkWidget * paned_widget = NULL
Widget containing the treeview and the settings 'page'.
static GtkTreePath * last_node_path = NULL
Path to the last used settings page.
Detailed Description
GTK3 main settings dialog.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
DIALOG_HEIGHT
#define DIALOG_HEIGHT 560
Initial dialog height.
This is not how tall the dialog will actually become, that is determined by the Gtk theme applied. But it's a rough estimate. With a 1280x720 resolution in Gnome (with the default top bar and a bottom application selector bar) a height of about 560-580 is the maximum that'll make the dialog with still fit.
DIALOG_HEIGHT_MAX
#define DIALOG_HEIGHT_MAX 640
Maximum height the UI can be.
This again is not a really a fixed value, but more of an indicator when the UI might get too large after any decorations are applied. The idea is to have a UI that works on a 1280x768 resolution without requiring scrollbars.
DIALOG_HEIGHT_TOLERANCE
#define DIALOG_HEIGHT_TOLERANCE 60
Tolerated extra dialog height added by decorations/theme.
Gtk has the annoying "feature" to not count any window decorations when we request a size. So when the dialog pops up, we immediately get a 'configure' event of the window triggered by a resize of said window. So in order for the debugging checks on the resizing of the dialog we need to allow some margin.
Gnome's "Adwaita-dark" theme appears to add 50 pixels.
DIALOG_WIDTH
#define DIALOG_WIDTH 920
Initial dialog width.
This is not how wide the dialog will actually become, that is determined by the Gtk theme applied. But it's a rough estimate. A little over 900 pixels will still fit the dialog on a 1024 pixels wide display.
DIALOG_WIDTH_MAX
#define DIALOG_WIDTH_MAX 1024
Maximum width the UI can be.
This again is not a really a fixed value, but more of an indicator when the UI might get too large after any decorations are applied. The idea is to have a UI that works on a 1280x768 resolution without requiring scrollbars.
DIALOG_WIDTH_TOLERANCE
#define DIALOG_WIDTH_TOLERANCE 20
Tolerated extra dialog width added by decorations/theme.
Gtk has the annoying "feature" to not count any window decorations when we request a size. So when the dialog pops up, we immediately get a 'configure' event of the window triggered by a resize of said window. So in order for the debugging checks on the resizing of the dialog we need to allow some margin.
Gnome's "Adwaita-dark" theme appears to add 16 pixels.
NUM_COLUMNS
#define NUM_COLUMNS 3
Number of columns in the tree model.
TREEVIEW_CSS
#define TREEVIEW_CSS
Value:
    "@binding-set SettingsTreeViewBinding\n" \
    "{\n" \
    "    bind \"Left\"  { \"select-cursor-parent\" ()\n" \
    "                     \"expand-collapse-cursor-row\" (0,0,0) };\n" \
    "    bind \"Right\" { \"expand-collapse-cursor-row\" (0,1,0) };\n" \
    "}\n" \
    "\n" \
    "treeview\n" \
    "{\n" \
    "    -gtk-key-bindings: SettingsTreeViewBinding;\n" \
    "}\n" \
    "treeview .separator\n" \
    "{\n" \
    "    color: darker (@theme_bg_color);\n" \
    "}\n"
CSS to allow collapsing/expanding tree nodes with crsr keys.
Note the 'treeview' rule, before Gtk+ 3.20 this was 'GtkTreeView'
Enumeration Type Documentation
anonymous enum
anonymous enum
Column indici for the tree model.
Enumerator
COLUMN_NAME
name
COLUMN_ID
id
COLUMN_CALLBACK
callback function
anonymous enum
anonymous enum
Enum used for the "response" callback of the settings dialog.
All values must be positive since Gtk reserves standard responses in its GtkResponse enum as negative values.
Enumerator
RESPONSE_RESET
reset current central widget
RESPONSE_FACTORY
set current central widget's resources to their factory settings
RESPONSE_DEFAULT
Restore default settings.
Function Documentation
create_confirm_on_exit_checkbox()
static GtkWidget * create_confirm_on_exit_checkbox (void) static
Create the 'Confirm on exit' checkbox.
The current position/display of the checkbox is a little lame at the moment
Returns
GtkCheckButton
Referenced by create_content_widget().
create_content_widget()
static GtkWidget * create_content_widget (GtkWidget * dialog) static
Create the 'content widget' of the settings dialog.
This creates the widget in the dialog used to display the treeview and room for the widget connected to that tree's currently selected item.
Parameters
[in] dialog settings dialog
Returns
GtkGrid
Referenced by dialog_create_helper().
create_pause_on_settings_checkbox()
static GtkWidget * create_pause_on_settings_checkbox (void) static
Create the 'Pause on settings dialog' checkbox.
Returns
GtkCheckButton
Referenced by create_content_widget().
create_save_on_exit_checkbox()
static GtkWidget * create_save_on_exit_checkbox (void) static
Create the 'Save on exit' checkbox.
The current position/display of the checkbox is a little lame at the moment
Returns
GtkCheckButton
Referenced by create_content_widget().
create_tree_model()
static void create_tree_model (void) static
Create empty tree model for the settings tree.
Referenced by create_treeview().
create_treeview()
static GtkWidget * create_treeview (void) static
Create treeview for settings side-menu.
Reads items from main_nodes and adds them to the tree view.
Returns
GtkTreeView
!
Todo:
Handle nested items, and write up somewhere how the hell I finally got the callbacks working. Split into a function creating the tree view and functions adding, altering or removing nodes.
Referenced by create_content_widget().
dialog_create_helper()
static GtkWidget * dialog_create_helper (void) static
Dialog create helper.
Create the GtkDialog and set it up, connecting signal handlers.
Returns
Settings dialog
Referenced by ui_settings_dialog_show_impl().
on_close_clicked()
static void on_close_clicked (GtkWidget * widget, gpointer dialog) static
Handler for the 'clicked' event of our own "Close" button.
Parameters
[in] widget button
[in] dialog settings dialog
Referenced by create_content_widget().
on_dialog_configure_event()
static gboolean on_dialog_configure_event (GtkWidget * widget, GdkEvent * event, gpointer data) static
Respond to window size changes.
This allows for quickly seeing if specific dialog is getting too large. It's also used to store the dialog position so it can be restored when respawning.
Parameters
[in] widget a GtkWindow
[in] event the GDK event
[in] data extra event data (unused)
Returns
boolean
Referenced by dialog_create_helper().
on_row_activated()
static void on_row_activated (GtkTreeView * tree_view, GtkTreePath * path, GtkTreeViewColumn * column, gpointer user_data) static
Handler for the double click event of a tree node.
Expands or collapses the node and its children (if any)
Parameters
[in,out] tree_view tree view instance
[in] path tree view path
[in] column tree view column (unused)
[in] user_data extra event data (unused)
Referenced by create_content_widget().
on_settings_dialog_destroy()
static void on_settings_dialog_destroy (GtkWidget * widget, gpointer data) static
Handler for the "destroy" event of the main dialog.
Stores the position of the dialog so it can be shown again at that position.
Parameters
[in] widget main dialog
[in] data extra event data (unused)
Referenced by dialog_create_helper().
on_tree_selection_changed()
static void on_tree_selection_changed (GtkTreeSelection * selection, gpointer user_data) static
Handler for the "changed" event of the tree view.
Parameters
[in] selection GtkTreeSelection associated with the tree model
[in] user_data data for the event (unused for now)
Referenced by create_content_widget().
populate_tree_model()
static GtkTreeStore * populate_tree_model (void) static
Create tree store containing settings items and children.
Returns
GtkTreeStore
Referenced by create_treeview().
response_callback()
static void response_callback (GtkWidget * widget, gint response_id, gpointer user_data) static
Handler for the 'response' event of the settings dialog.
This determines what to do based on the 'reponse ID' emitted by the dialog.
Parameters
[in,out] widget settings dialog
[in] response_id response ID
[in] user_data extra data (unused)
Referenced by dialog_create_helper().
row_separator_func()
static gboolean row_separator_func (GtkTreeModel * model, GtkTreeIter * iter, gpointer data) static
Determine if the current tree item should be a separator.
Callback function for the tree view to check item at iter in model and decide if the item is a separator.
Parameters
[in] model tree model
[in] iter tree iterator
[in] data extra event data (unused)
Returns
TRUE if the item is a separator
Referenced by create_treeview().
ui_settings_dialog_activate_node()
static gboolean ui_settings_dialog_activate_node (const char * path) static
Find and activate node in the tree view via path.
The path argument is expected to be in the form 'foo/bar/bah', each path item indicates a node in the tree view/model. For example: "display/vdc" would select the VDC settings dialog on x128, but would fail on any other machine.
Parameters
[in] path path to the node
Returns
bool
Referenced by ui_settings_dialog_show_impl().
ui_settings_dialog_show()
void ui_settings_dialog_show (const char * path)
Menu callback for the settings dialog.
Opens the main settings dialog and activates a node, if any.
Parameters
[in] path path to node
Returns
TRUE
Referenced by help_hotkeys_action(), on_configure_activate(), on_drive_configure_activate(), settings_dialog_action(), and ui_create_main_window().
ui_settings_dialog_show_impl()
static gboolean ui_settings_dialog_show_impl (gpointer user_data) static
Threaded UI handler for the settings dialog constructor.
Parameters
[in] user_data path to active node in the treeview
Returns
FALSE
Referenced by ui_settings_dialog_show().
ui_settings_inital_widget()
static GtkWidget * ui_settings_inital_widget (GtkWidget * parent) static
Create the widget that is initially shown in the settings UI.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
Referenced by create_content_widget().
ui_settings_set_central_widget()
static void ui_settings_set_central_widget (GtkWidget * widget) static
}}}
Set the 'central'/action widget for the settings dialog.
Reference to the current 'central' widget in the settings dialog
Destroys the old 'central' widget and sets the new one.
Parameters
[in,out] widget widget to use as the new 'central' widget
Referenced by create_content_widget(), and on_tree_selection_changed().
ui_settings_shutdown()
void ui_settings_shutdown (void)
Clean up resources used on emu exit.
This function cleans up the data used to present the user with the last used settings page.
Note
Do NOT call this when exiting the settings UI, the event handlers will take care of cleaning up resources used by the UI.
Referenced by ui_exit().
Variable Documentation
audio_nodes_c128
ui_settings_tree_node_t audio_nodes_c128[] static
Initial value:
= {
    { "Sound driver",
      "sound-driver",
      settings_sound_widget_create, NULL },
    { "SID",
      "sid",
      settings_soundchip_widget_create, NULL },
    { "Sampler",
      "sampler",
      settings_sampler_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ audio_nodes_c128
Child nodes for the C128 'Audio' node
audio_nodes_c64
ui_settings_tree_node_t audio_nodes_c64[] static
Initial value:
= {
    { "Sound driver",
      "sound-driver",
      settings_sound_widget_create, NULL },
    { "SID",
      "sid",
      settings_soundchip_widget_create, NULL },
    { "Sampler",
      "sampler",
      settings_sampler_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ audio_nodes_c64
Child nodes for the C64 'Audio' node
audio_nodes_c64dtv
ui_settings_tree_node_t audio_nodes_c64dtv[] static
Initial value:
= {
    { "Sound driver",
      "sound-driver",
      settings_sound_widget_create, NULL },
    { "SID",
      "sid",
      settings_soundchip_widget_create, NULL },
    { "Sampler",
      "sampler",
      settings_sampler_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ audio_nodes_c64dtv
Child nodes for the C64DTV 'Audio' node
audio_nodes_cbm5x0
ui_settings_tree_node_t audio_nodes_cbm5x0[] static
Initial value:
= {
    { "Sound driver",
      "sound-driver",
      settings_sound_widget_create, NULL },
    { "SID",
      "sid",
      settings_soundchip_widget_create, NULL },
    { "Sampler",
      "sampler",
      settings_sampler_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ audio_nodes_cbm5x0
Child nodes for the CBM5x0 'Audio' node
audio_nodes_cbm6x0
ui_settings_tree_node_t audio_nodes_cbm6x0[] static
Initial value:
= {
    { "Sound driver",
      "sound-driver",
      settings_sound_widget_create, NULL },
    { "SID",
      "sid",
      settings_soundchip_widget_create, NULL },
    { "Sampler",
      "sampler",
      settings_sampler_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ audio_nodes_cbm6x0
Child nodes for the CBM6x0 'Audio' node
audio_nodes_pet
ui_settings_tree_node_t audio_nodes_pet[] static
Initial value:
= {
    { "Sound driver",
      "sound-driver",
      settings_sound_widget_create, NULL },
    { "SID",
      "sid",
      settings_soundchip_widget_create, NULL },
    { "Sampler",
      "sampler",
      settings_sampler_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ audio_nodes_pet
Child nodes for the PET 'Audio' node
audio_nodes_plus4
ui_settings_tree_node_t audio_nodes_plus4[] static
Initial value:
= {
    { "Sound driver",
      "sound-driver",
      settings_sound_widget_create, NULL },
    { "SID",
      "sid",
      settings_soundchip_widget_create, NULL },
    { "Sampler",
      "sampler",
      settings_sampler_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ audio_nodes_plus4
Child nodes for the Plus4 'Audio' node
audio_nodes_scpu64
ui_settings_tree_node_t audio_nodes_scpu64[] static
Initial value:
= {
    { "Sound driver",
      "sound-driver",
      settings_sound_widget_create, NULL },
    { "SID",
      "sid",
      settings_soundchip_widget_create, NULL },
    { "Sampler",
      "sampler",
      settings_sampler_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ audio_nodes_scpu64
Child nodes for the SCPU64 'Peripheral devices' node
audio_nodes_vic20
ui_settings_tree_node_t audio_nodes_vic20[] static
Initial value:
= {
    { "Sound driver",
      "sound-driver",
      settings_sound_widget_create, NULL },
    { "SID",
      "sid",
      settings_soundchip_widget_create, NULL },
    { "Sampler",
      "sampler",
      settings_sampler_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ audio_nodes_vic20
Child nodes for the VIC20 'Audio' node
c128_cartridges
ui_settings_tree_node_t c128_cartridges[] static
}}}
{{{ c128_cartridges
I/O extensions for C128
c64_cartridges
ui_settings_tree_node_t c64_cartridges[] static
{{{ c64_cartridges
List of C64 cartidge settings (x64, x64sc)
cbm2_io_extensions
ui_settings_tree_node_t cbm2_io_extensions[] static
Initial value:
= {
    { "Default cartridge",
      "default-cart",
      settings_default_cart_widget_create, NULL },
     { "---", "(separator)", NULL, NULL } ,
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ cbm2_io_extensions
List of CBM2 I/O extensions
display_nodes_c128
ui_settings_tree_node_t display_nodes_c128[] static
Initial value:
= {
    { "Host display",
      "host-display",
      settings_host_display_widget_create, NULL },
    { "VIC-II",
      "vicii",
      settings_video_widget_create, NULL },
    { "VDC",
      "vdc",
      settings_video_widget_create_vdc, NULL },
    { "CRT",
      "crt",
      settings_crt_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ display_nodes_c128
Child nodes for the C128 'Display' node
display_nodes_c64
ui_settings_tree_node_t display_nodes_c64[] static
Initial value:
= {
    { "Host display",
      "host-display",
      settings_host_display_widget_create, NULL },
    { "VIC-II",
      "vicii",
      settings_video_widget_create, NULL },
    { "CRT",
      "crt",
      settings_crt_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ display_nodes_c64
Child nodes for the C64 'Display' node
display_nodes_c64dtv
ui_settings_tree_node_t display_nodes_c64dtv[] static
Initial value:
= {
    { "Host display",
      "host-display",
      settings_host_display_widget_create, NULL },
    { "VIC-II",
      "vicii",
      settings_video_widget_create, NULL },
    { "CRT",
      "CRT",
      settings_crt_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ display_nodes_c64dtv
Child nodes for the C64DTV 'Display' node
display_nodes_cbm5x0
ui_settings_tree_node_t display_nodes_cbm5x0[] static
Initial value:
= {
    { "Host display",
      "host-display",
      settings_host_display_widget_create, NULL },
    { "VIC-II",
      "vicii",
      settings_video_widget_create, NULL },
    { "CRT",
      "CRT",
      settings_crt_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ display_nodes_cbm5x0
Child nodes for the CBM5x0 'Display' node
display_nodes_cbm6x0
ui_settings_tree_node_t display_nodes_cbm6x0[] static
Initial value:
= {
    { "Host display",
      "host-display",
      settings_host_display_widget_create, NULL },
    { "CRTC",
      "crtc",
      settings_video_widget_create, NULL },
    { "CRT",
      "CRT",
      settings_crt_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ display_nodes_cbm6x0
Child nodes for the CBM6x0 'Display' node
display_nodes_pet
ui_settings_tree_node_t display_nodes_pet[] static
Initial value:
= {
    { "Host display",
      "host-display",
      settings_host_display_widget_create, NULL },
    { "CRTC",
      "crtc",
      settings_video_widget_create, NULL },
    { "CRT",
      "CRT",
      settings_crt_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ display_nodes_pet
Child nodes for the PET 'Display' node
display_nodes_plus4
ui_settings_tree_node_t display_nodes_plus4[] static
Initial value:
= {
    { "Host display",
      "host-display",
      settings_host_display_widget_create, NULL },
    { "TED",
      "ted",
      settings_video_widget_create, NULL },
    { "CRT",
      "CRT",
      settings_crt_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ display_nodes_plus4
Child nodes for the Plus4 'Display' node
display_nodes_scpu64
ui_settings_tree_node_t display_nodes_scpu64[] static
Initial value:
= {
    { "Host display",
      "host-display",
      settings_host_display_widget_create, NULL },
    { "VIC-II",
      "vicii",
      settings_video_widget_create, NULL },
    { "CRT",
      "CRT",
      settings_crt_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ display_nodes_scpu64
Child nodes for the SCPU64 'Display' node
display_nodes_vic20
ui_settings_tree_node_t display_nodes_vic20[] static
Initial value:
= {
    { "Host display",
      "host-display",
      settings_host_display_widget_create, NULL },
    { "VIC",
      "vic",
      settings_video_widget_create, NULL },
    { "CRT",
      "CRT",
      settings_crt_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ display_nodes_vic20
Child nodes for the VIC20 'Display' node
host_nodes_generic
ui_settings_tree_node_t host_nodes_generic[] static
Initial value:
= {
    { "Autostart",
      "autostart",
      settings_autostart_widget_create, NULL },
    { "Hotkeys",
      "hotkeys",
      settings_hotkeys_widget_create, NULL },
    { "Monitor",
      "monitor",
      settings_monitor_widget_create, NULL },
    { "Netplay",
      "netplay",
      settings_netplay_widget_create, NULL },
    { "Snapshot/event/media recording",
      "snapshot",
      settings_snapshot_widget_create, NULL },
    { "Environment",
      "environment",
      settings_environment_widget_create, NULL },
    { "CPU JAM action",
      "jam-action",
      settings_jam_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ host_nodes_generic
Child nodes for the 'Host' node for all machines
input_nodes_c128
ui_settings_tree_node_t input_nodes_c128[] static
Initial value:
= {
    { "Keyboard",
      "keyboard",
      settings_keyboard_widget_create, NULL },
    { "Joystick",
      "joystick",
      settings_joystick_widget_create, NULL },
    { "Control port",
      "control-port",
      settings_controlport_widget_create, NULL },
    { "Autofire",
      "autofire",
      settings_autofire_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ input_nodes_c128
Child nodes for the C128 'Input devices' node
input_nodes_c64
ui_settings_tree_node_t input_nodes_c64[] static
Initial value:
= {
    { "Keyboard",
      "keyboard",
      settings_keyboard_widget_create, NULL },
    { "Joystick",
      "joystick",
      settings_joystick_widget_create, NULL },
    { "Control port",
      "control-port",
      settings_controlport_widget_create, NULL },
    { "Autofire",
      "autofire",
      settings_autofire_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ input_nodes_c64
Child nodes for the C64 'Input devices' node
input_nodes_c64dtv
ui_settings_tree_node_t input_nodes_c64dtv[] static
Initial value:
= {
    { "Keyboard",
      "keyboard",
      settings_keyboard_widget_create, NULL },
    { "Joystick",
      "joystick",
      settings_joystick_widget_create, NULL },
    { "Control port",
      "control-port",
      settings_controlport_widget_create, NULL },
    { "Autofire",
      "autofire",
      settings_autofire_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ input_nodes_c64dtv
Child nodes for the C64DTV 'Input devices' node
input_nodes_cbm5x0
ui_settings_tree_node_t input_nodes_cbm5x0[] static
Initial value:
= {
    { "Keyboard",
      "keyboard",
      settings_keyboard_widget_create, NULL },
    { "Joystick",
      "joystick",
      settings_joystick_widget_create, NULL },
    { "Control port",
      "control-port",
      settings_controlport_widget_create, NULL },
    { "Autofire",
      "autofire",
      settings_autofire_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ input_nodes_cbm5x0
Child nodes for the CBM5x0 'Input devices' node
input_nodes_cbm6x0
ui_settings_tree_node_t input_nodes_cbm6x0[] static
Initial value:
= {
    { "Keyboard",
      "keyboard",
      settings_keyboard_widget_create, NULL },
    { "Joystick",
      "joystick",
      settings_joystick_widget_create, NULL },
    { "Control port",
      "control-port",
      settings_controlport_widget_create, NULL },
    { "Autofire",
      "autofire",
      settings_autofire_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ input_nodes_cbm6x0
Child nodes for the CBM6x0 'Input devices' node
input_nodes_pet
ui_settings_tree_node_t input_nodes_pet[] static
Initial value:
= {
    { "Keyboard",
      "keyboard",
      settings_keyboard_widget_create, NULL },
    { "Joystick",
      "joystick",
      settings_joystick_widget_create, NULL },
    { "Autofire",
      "autofire",
      settings_autofire_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ input_nodes_pet
Child nodes for the PET 'Input devices' node
input_nodes_plus4
ui_settings_tree_node_t input_nodes_plus4[] static
Initial value:
= {
    { "Keyboard",
      "keyboard",
      settings_keyboard_widget_create, NULL },
    { "Joystick",
      "joystick",
      settings_joystick_widget_create, NULL },
    { "Control port",
      "control-port",
      settings_controlport_widget_create, NULL },
    { "Autofire",
      "autofire",
      settings_autofire_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ input_nodes_plus4
Child nodes for the Plus4 'Input devices' node
input_nodes_scpu64
ui_settings_tree_node_t input_nodes_scpu64[] static
Initial value:
= {
    { "Keyboard",
      "keyboard",
      settings_keyboard_widget_create, NULL },
    { "Joystick",
      "joystick",
      settings_joystick_widget_create, NULL },
    { "Control port",
      "control-port",
      settings_controlport_widget_create, NULL },
    { "Autofire",
      "autofire",
      settings_autofire_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ input_nodes_scpu64
Child nodes for the SCPU64 'Input devices' node
input_nodes_vic20
ui_settings_tree_node_t input_nodes_vic20[] static
Initial value:
= {
    { "Keyboard",
      "keyboard",
      settings_keyboard_widget_create, NULL },
    { "Joystick",
      "joystick",
      settings_joystick_widget_create, NULL },
    { "Control port",
      "control-port",
      settings_controlport_widget_create, NULL },
    { "Autofire",
      "autofire",
      settings_autofire_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ input_nodes_vic20
Child nodes for the VIC20 'Input devices' node
last_node_path
GtkTreePath* last_node_path = NULL static
Path to the last used settings page.
Referenced by create_content_widget(), on_tree_selection_changed(), and ui_settings_shutdown().
machine_nodes_c128
ui_settings_tree_node_t machine_nodes_c128[] static
Initial value:
= {
    { "Model",
      "model",
      settings_model_widget_create, NULL },
    { "ROM",
      "rom",
      settings_rom_widget_create, NULL },
    { "RAM",
      "ram",
      settings_ramreset_widget_create, NULL },
    { "Function ROM",
      "function-rom",
      settings_c128functionrom_widget_create, NULL },
    { "Banks 2 & 3",
      "banks-23",
      settings_c128fullbanks_widget_create, NULL },
    { "I/O settings",
      "io",
      settings_io_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ machine_nodes_c128
Child nodes for the C128 'Machine' node
machine_nodes_c64
ui_settings_tree_node_t machine_nodes_c64[] static
Initial value:
= {
    { "Model",
      "model",
      settings_model_widget_create, NULL },
    { "ROM",
      "rom",
      settings_rom_widget_create, NULL },
    { "RAM",
      "ram",
      settings_ramreset_widget_create, NULL },
    { "Memory Expansion Hacks",
      "mem-hacks",
      settings_c64_memhacks_widget_create, NULL },
    { "I/O settings",
      "io",
      settings_io_widget_create, NULL },
    { "Burst Mode Modification",
      "burst-mode",
      settings_burstmode_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ machine_nodes_c64
Child nodes for the C64 'Machine' node
machine_nodes_c64dtv
ui_settings_tree_node_t machine_nodes_c64dtv[] static
Initial value:
= {
    { "Model",
      "model",
      settings_model_widget_create, NULL },
    { "ROM",
      "rom",
      settings_rom_widget_create, NULL },
    { "RAM",
      "ram",
      settings_ramreset_widget_create, NULL },
    { "Flash",
      "flash",
      settings_c64dtvflash_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ machine_nodes_c64dtv
Child nodes for the C64DTV 'Machine' node
machine_nodes_cbm5x0
ui_settings_tree_node_t machine_nodes_cbm5x0[] static
Initial value:
= {
    { "Model",
      "model",
      settings_model_widget_create, NULL },
    { "ROM",
      "rom",
      settings_rom_widget_create, NULL },
    { "RAM",
      "ram",
      settings_ramreset_widget_create, NULL },
    { "I/O settings",
      "io",
      settings_io_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ machine_nodes_cbm5x0
Child nodes for the CBM5x0 'Machine' node
machine_nodes_cbm6x0
ui_settings_tree_node_t machine_nodes_cbm6x0[] static
Initial value:
= {
    { "Model",
      "model",
      settings_model_widget_create, NULL },
    { "ROM",
      "rom",
      settings_rom_widget_create, NULL },
    { "RAM",
      "ram",
      settings_ramreset_widget_create, NULL },
    { "I/O settings",
      "io",
      settings_io_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ machine_nodes_cbm6x0
Child nodes for the CBM6x0 'Machine' node
machine_nodes_pet
ui_settings_tree_node_t machine_nodes_pet[] static
Initial value:
= {
    { "Model",
      "model",
      settings_model_widget_create, NULL },
    { "ROM",
      "rom",
      settings_rom_widget_create, NULL },
    { "RAM",
      "ram",
      settings_ramreset_widget_create, NULL },
    { "I/O settings",
      "io",
      settings_io_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ machine_nodes_pet
Child nodes for the PET 'Machine' node
machine_nodes_plus4
ui_settings_tree_node_t machine_nodes_plus4[] static
Initial value:
= {
    { "Model",
      "model",
       settings_model_widget_create, NULL },
    { "ROM",
      "rom",
       settings_rom_widget_create, NULL },
    { "RAM",
      "ram",
      settings_ramreset_widget_create, NULL },
    { "I/O settings",
      "io",
      settings_io_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ machine_nodes_plus4
Child nodes for the Plus4 'Machine' node
machine_nodes_scpu64
ui_settings_tree_node_t machine_nodes_scpu64[] static
Initial value:
= {
    { "Model",
      "model",
      settings_model_widget_create, NULL },
    { "SCPU64",
      "scpu64",
      settings_scpu64_widget_create, NULL },
    { "ROM",
      "rom",
      settings_rom_widget_create, NULL },
    { "RAM",
      "ram",
      settings_ramreset_widget_create, NULL },
    { "I/O settings",
      "io",
      settings_io_widget_create, NULL },
    { "Burst Mode Modification",
      "burst-mode",
      settings_burstmode_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ machine_nodes_scpu64
Child nodes for the SCPU64 'Machine' node
machine_nodes_vic20
ui_settings_tree_node_t machine_nodes_vic20[] static
Initial value:
= {
    { "Model",
      "model",
      settings_model_widget_create, NULL },
    { "ROM",
      "rom",
      settings_rom_widget_create, NULL },
    { "RAM",
      "ram",
      settings_ramreset_widget_create, NULL },
    { "I/O settings",
      "io",
      settings_io_widget_create, NULL },
    { "I/O RAM",
      "io-ram",
      settings_vicioram_widget_create, NULL },
    { "VFLI modification",
      "vfli",
      settings_vfli_widget_create, NULL },
    { "SID Card",
      "sid-card",
      settings_sidcart_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ machine_nodes_vic20
Child nodes for the VIC20 'Machine' node
main_nodes_c128
ui_settings_tree_node_t main_nodes_c128[] static
Initial value:
= {
    { "Host",               "host",         NULL,   host_nodes_generic },
    { "Machine",            "machine",      NULL,   machine_nodes_c128 },
    { "Display",            "display",      NULL,   display_nodes_c128 },
    { "Audio",              "audio",        NULL,   audio_nodes_c128 },
    { "Input devices",      "input",        NULL,   input_nodes_c128 },
    { "Peripheral devices", "peripheral",   NULL,   peripheral_nodes_c128 },
    { "Cartridges",         "cartridges",   NULL,   c128_cartridges },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ main_nodes_c128
Main tree nodes for x128
Referenced by populate_tree_model().
main_nodes_c64
ui_settings_tree_node_t main_nodes_c64[] static
Initial value:
= {
    { "Host",               "host",         NULL,   host_nodes_generic },
    { "Machine",            "machine",      NULL,   machine_nodes_c64 },
    { "Display",            "display",      NULL,   display_nodes_c64 },
    { "Audio",              "audio",        NULL,   audio_nodes_c64 },
    { "Input devices",      "input",        NULL,   input_nodes_c64 },
    { "Peripheral devices", "peripheral",   NULL,   peripheral_nodes_c64 },
    { "Cartridges",         "cartridges",   NULL,   c64_cartridges },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ main_nodes_c64
Main tree nodes for x64/x64sc
Referenced by populate_tree_model().
main_nodes_c64dtv
ui_settings_tree_node_t main_nodes_c64dtv[] static
Initial value:
= {
    { "Host",               "host",         NULL,   host_nodes_generic },
    { "Machine",            "machine",      NULL,   machine_nodes_c64dtv },
    { "Display",            "display",      NULL,   display_nodes_c64dtv },
    { "Audio",              "audio",        NULL,   audio_nodes_c64dtv },
    { "Input devices",      "input",        NULL,   input_nodes_c64dtv },
    { "Peripheral devices", "peripheral",   NULL,   peripheral_nodes_c64dtv },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ main_nodes_c64dtv
Main tree nodes for x64dtv
Referenced by populate_tree_model().
main_nodes_cbm5x0
ui_settings_tree_node_t main_nodes_cbm5x0[] static
Initial value:
= {
    { "Host",               "host",         NULL,   host_nodes_generic },
    { "Machine",            "machine",      NULL,   machine_nodes_cbm5x0 },
    { "Display",            "display",      NULL,   display_nodes_cbm5x0 },
    { "Audio",              "audio",        NULL,   audio_nodes_cbm5x0 },
    { "Input devices",      "input",        NULL,   input_nodes_cbm5x0 },
    { "Peripheral devices", "peripheral",   NULL,   peripheral_nodes_cbm5x0 },
    { "Cartridges",         "cartridges",   NULL,   cbm2_io_extensions },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ main_nodes_cbm5x0
Main tree nodes for xcbm5x0
Referenced by populate_tree_model().
main_nodes_cbm6x0
ui_settings_tree_node_t main_nodes_cbm6x0[] static
Initial value:
= {
    { "Host",               "host",         NULL,   host_nodes_generic },
    { "Machine",            "machine",      NULL,   machine_nodes_cbm6x0 },
    { "Display",            "display",      NULL,   display_nodes_cbm6x0 },
    { "Audio",              "audio",        NULL,   audio_nodes_cbm6x0 },
    { "Input devices",      "input",        NULL,   input_nodes_cbm6x0 },
    { "Peripheral devices", "peripheral",   NULL,   peripheral_nodes_cbm6x0 },
    { "Cartridges",         "cartridges",   NULL,   cbm2_io_extensions },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ main_nodes_cbm6x0
Main tree nodes for xcbm6x0
Referenced by populate_tree_model().
main_nodes_pet
ui_settings_tree_node_t main_nodes_pet[] static
Initial value:
= {
    { "Host",               "host",             NULL,   host_nodes_generic },
    { "Machine",            "machine",          NULL,   machine_nodes_pet },
    { "Display",            "display",          NULL,   display_nodes_pet },
    { "Audio",              "audio",            NULL,   audio_nodes_pet },
    { "Input devices",      "input",            NULL,   input_nodes_pet },
    { "Peripheral devices", "peripheral",       NULL,   peripheral_nodes_pet },
    { "I/O extensions",     "io-extensions",    NULL,   pet_io_extensions },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ main_nodes_pet
Main tree nodes for xpet
Referenced by populate_tree_model().
main_nodes_plus4
ui_settings_tree_node_t main_nodes_plus4[] static
Initial value:
= {
    { "Host",               "host",         NULL,   host_nodes_generic },
    { "Machine",            "machine",      NULL,   machine_nodes_plus4 },
    { "Display",            "display",      NULL,   display_nodes_plus4 },
    { "Audio",              "audio",        NULL,   audio_nodes_plus4 },
    { "Input devices",      "input",        NULL,   input_nodes_plus4 },
    { "Peripheral devices", "peripheral",   NULL,   peripheral_nodes_plus4 },
    { "Cartridges",         "cartridges",   NULL,   plus4_io_extensions },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ main_nodes_plus4
Main tree nodes for xplus4
Referenced by populate_tree_model().
main_nodes_scpu64
ui_settings_tree_node_t main_nodes_scpu64[] static
Initial value:
= {
    { "Host",               "host",         NULL,   host_nodes_generic },
    { "Machine",            "machine",      NULL,   machine_nodes_scpu64 },
    { "Display",            "display",      NULL,   display_nodes_scpu64 },
    { "Audio",              "audio",        NULL,   audio_nodes_scpu64 },
    { "Input devices",      "input",        NULL,   input_nodes_scpu64 },
    { "Peripheral devices", "peripheral",   NULL,   peripheral_nodes_scpu64 },
    { "Cartridges",         "cartridges",   NULL,   scpu64_cartridges },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ main_nodes_scpu64
Main tree nodes for xscpu64
Referenced by populate_tree_model().
main_nodes_vic20
ui_settings_tree_node_t main_nodes_vic20[] static
Initial value:
= {
    { "Host",               "host",         NULL,   host_nodes_generic },
    { "Machine",            "machine",      NULL,   machine_nodes_vic20 },
    { "Display",            "display",      NULL,   display_nodes_vic20 },
    { "Audio",              "audio",        NULL,   audio_nodes_vic20 },
    { "Input devices",      "input",        NULL,   input_nodes_vic20 },
    { "Peripheral devices", "peripheral",   NULL,   peripheral_nodes_vic20 },
    { "Cartridges",         "cartridges",   NULL,   vic20_cartridges },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ main_nodes_vic20
Main tree nodes for xvic
Referenced by populate_tree_model().
main_nodes_vsid
ui_settings_tree_node_t main_nodes_vsid[] static
Initial value:
= {
    { "Sound driver", "sound-driver", settings_sound_widget_create, NULL },
    { "SID",        "sid",      settings_soundchip_widget_create,   NULL },
    { "Model",      "model",    settings_model_widget_create,       NULL },
    { "Monitor",    "monitor",  settings_monitor_widget_create,     NULL },
    { "HVSC",       "hvsc",     settings_hvsc_widget_create,        NULL },
    { "Hotkeys",    "hotkeys",  settings_hotkeys_widget_create,     NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ main_nodes_vsid
Main tree nodes for VSID
Referenced by populate_tree_model().
paned_widget
GtkWidget* paned_widget = NULL static
Widget containing the treeview and the settings 'page'.
Allows resizing both the treeview and the setting with a 'grip'.
Referenced by create_content_widget(), and ui_settings_set_central_widget().
peripheral_nodes_c128
ui_settings_tree_node_t peripheral_nodes_c128[] static
Initial value:
= {
    { "Drive",
      "drive",
      settings_drive_widget_create, NULL },
    { "Host file system device",
      "fsdevice",
      settings_fsdevice_widget_create, NULL },
    { "Printer",
      "printer",
      settings_printer_widget_create, NULL },
    { "Userport devices",
      "userport-devices",
      settings_userport_widget_create, NULL },
    { "Tape port devices",
      "tapeport-devices",
      settings_tapeport_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ peripheral_nodes_c128
Child nodes for the C128 'Peripheral devices' node
peripheral_nodes_c64
ui_settings_tree_node_t peripheral_nodes_c64[] static
Initial value:
= {
    { "Drive",
      "drive",
      settings_drive_widget_create, NULL },
    { "Host file system device",
      "fsdevice",
      settings_fsdevice_widget_create, NULL },
    { "Printer",
      "printer",
      settings_printer_widget_create, NULL },
   { "Userport devices",
      "userport-devices",
      settings_userport_widget_create, NULL },
    { "Tape port devices",
      "tapeport-devices",
      settings_tapeport_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ peripheral_nodes_c64
Child nodes for the C64 'Peripheral devices' node
peripheral_nodes_c64dtv
ui_settings_tree_node_t peripheral_nodes_c64dtv[] static
Initial value:
= {
    { "Drive",
      "drive",
      settings_drive_widget_create, NULL },
    { "Host file system device",
      "fsdevice",
      settings_fsdevice_widget_create, NULL },
    { "Printer",
      "printer",
      settings_printer_widget_create, NULL },
    { "Userport devices",
      "userport-devices",
      settings_userport_widget_create, NULL },
       { NULL, NULL, NULL, NULL }
}
}}}
{{{ peripheral_nodes_c64dtv
Child nodes for the C64DTV 'Peripheral devices' node
peripheral_nodes_cbm5x0
ui_settings_tree_node_t peripheral_nodes_cbm5x0[] static
Initial value:
= {
    { "Drive",
      "drive",
      settings_drive_widget_create, NULL },
    { "Host file system device",
      "fsdevice",
      settings_fsdevice_widget_create, NULL },
    { "Printer",
      "printer",
      settings_printer_widget_create, NULL },
    { "Tape port devices",
      "tapeport-devices",
      settings_tapeport_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ peripheral_nodes_cbm5x0
Child nodes for the CBM5x0 'Peripheral devices' node
peripheral_nodes_cbm6x0
ui_settings_tree_node_t peripheral_nodes_cbm6x0[] static
Initial value:
= {
    { "Drive",
      "drive",
      settings_drive_widget_create, NULL },
    { "Host file system device",
      "fsdevice",
      settings_fsdevice_widget_create, NULL },
    { "Printer",
      "printer",
      settings_printer_widget_create, NULL },
    { "Userport devices",
      "userport-devices",
      settings_userport_widget_create, NULL },
    { "Tape port devices",
      "tapeport_devices",
      settings_tapeport_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ peripheral nodes_cbm6x0
Child nodes for the CBM6x0 'Peripheral devices' node
peripheral_nodes_pet
ui_settings_tree_node_t peripheral_nodes_pet[] static
Initial value:
= {
    { "Drive",
      "drive",
      settings_drive_widget_create, NULL },
    { "Host file system device",
      "fsdevice",
      settings_fsdevice_widget_create, NULL },
    { "Printer",
      "printer",
      settings_printer_widget_create, NULL },
    { "Userport devices",
      "userport-devices",
      settings_userport_widget_create, NULL },
    { "Tape port devices",
      "tapeport-devices",
      settings_tapeport_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ peripheral_nodes_pet
Child nodes for the PET 'Peripheral devices' node
peripheral_nodes_plus4
ui_settings_tree_node_t peripheral_nodes_plus4[] static
Initial value:
= {
    { "Drive",
      "drive",
      settings_drive_widget_create, NULL },
    { "Host file system device",
      "fsdevice",
      settings_fsdevice_widget_create, NULL },
    { "Printer",
      "printer",
      settings_printer_widget_create, NULL },
    { "Userport devices",
      "userport-devices",
      settings_userport_widget_create, NULL },
    { "Tape port devices",
      "tapeport-devices",
      settings_tapeport_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ peripheral_nodes_plus4
Child nodes for the Plus4 'Peripheral devices' node
peripheral_nodes_scpu64
ui_settings_tree_node_t peripheral_nodes_scpu64[] static
Initial value:
= {
    { "Drive",
      "drive",
      settings_drive_widget_create, NULL },
    { "Host file system device",
      "fsdevice",
      settings_fsdevice_widget_create, NULL },
    { "Printer",
      "printer",
      settings_printer_widget_create, NULL },
    { "Userport devices",
      "userport-devices",
      settings_userport_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ peripheral_nodes_scpu64
Child nodes for the SCPU64 'Peripheral devices' node
peripheral_nodes_vic20
ui_settings_tree_node_t peripheral_nodes_vic20[] static
Initial value:
= {
    { "Drive",
      "drive",
      settings_drive_widget_create, NULL },
    { "Host file system device",
      "fsdevice",
      settings_fsdevice_widget_create, NULL },
    { "Printer",
      "printer",
      settings_printer_widget_create, NULL },
    { "Userport devices",
      "userport-devices",
      settings_userport_widget_create, NULL },
    { "Tapeport devices",
      "tapeport-devices",
      settings_tapeport_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ peripheral_nodes_vic20
Child nodes for the VIC20 'Peripheral devices' node
pet_io_extensions
ui_settings_tree_node_t pet_io_extensions[] static
Initial value:
= {
    { "PET RAM Expansion Unit",
      "pet-reu",
      settings_petreu_widget_create, NULL },
     { "---", "(separator)", NULL, NULL } ,
    { "SID Card",
      "sid-card",
      settings_sidcart_widget_create, NULL },
     { "---", "(separator)", NULL, NULL } ,
    { "PET Colour graphics",
      "pet-colour",
      settings_petcolourgraphics_widget_create, NULL },
    { "PET DWW hi-res graphics",
      "pet-dww",
      settings_petdww_widget_create, NULL },
    { "PET HRE hi-res graphics",
      "pet-hre",
      settings_pethre_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ pet_io_extensions
List of PET I/O extensions
plus4_io_extensions
ui_settings_tree_node_t plus4_io_extensions[] static
Initial value:
= {
    { "Default cartridge",
      "default-cart",
      settings_default_cart_widget_create, NULL },
     { "---", "(separator)", NULL, NULL } ,
    { "Digi-Blaster add-on",
      "digi-blaster",
      settings_plus4_digiblaster_widget_create, NULL },
    { "SID Card",
      "sid-card",
      settings_sidcart_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ plus4_io_extensions
List of Plus4 I/O extensions
scpu64_cartridges
ui_settings_tree_node_t scpu64_cartridges[] static
}}}
{{{ scpu64_cartridges
List of SuperCPU64 extensions (xscpu64)
scrolled_window
GtkWidget* scrolled_window = NULL static
Scroll window container for the settings treeview.
Referenced by create_content_widget().
settings_grid
GtkWidget* settings_grid = NULL static
Reference to the 'content area' widget of the settings dialog.
Referenced by create_content_widget().
settings_model
GtkTreeStore* settings_model = NULL static
Reference to the tree model for the settings tree.
Referenced by create_content_widget(), create_tree_model(), on_tree_selection_changed(), populate_tree_model(), and ui_settings_dialog_activate_node().
settings_old_pause_state
int settings_old_pause_state static
Old pause state when popping up the dialog.
Used for the PauseOnSettings resource: if true, exiting the dialog will set the emulators pause state to this.
Referenced by response_callback(), and ui_settings_dialog_show().
settings_tree
GtkWidget* settings_tree = NULL static
Reference to the tree view for the settings tree.
Referenced by create_content_widget(), and ui_settings_dialog_activate_node().
settings_window
GtkWidget* settings_window = NULL static
Reference to the settings dialog.
Referenced by on_settings_dialog_destroy(), on_tree_selection_changed(), response_callback(), ui_settings_dialog_activate_node(), and ui_settings_dialog_show_impl().
settings_xpos
gint settings_xpos = INT_MIN static
Previous X position of settings dialog.
Referenced by on_dialog_configure_event(), and ui_settings_dialog_show_impl().
settings_ypos
gint settings_ypos = INT_MIN static
Previous Y position of settings dialog.
Referenced by on_dialog_configure_event(), and ui_settings_dialog_show_impl().
vic20_cartridges
ui_settings_tree_node_t vic20_cartridges[] static
Initial value:
= {
    { "Default cartridge",
      "default-cart",
      settings_default_cart_widget_create, NULL },
     { "---", "(separator)", NULL, NULL } ,
    {  "Final Expansion" ,
      "final-expansion",
      settings_finalexpansion_widget_create, NULL },
    {  "Mega-Cart"  ,
      "mega-cart",
      settings_megacart_widget_create, NULL },
    {  "UltiMem" ,
      "ultimem",
      settings_ultimem_widget_create, NULL },
    {  "Vic Flash Plugin"  ,
      "vic-flash-plugin",
      settings_vicflashplugin_widget_create, NULL },
     { "---", "(separator)", NULL, NULL } ,
    {  "VIC-1112 IEEE-488 Interface"  ,
      "ieee-488",
      settings_vicieee488_widget_create, NULL },
     { "---", "(separator)", NULL, NULL } ,
     { "---", "(separator)", NULL, NULL } ,
    {  "DigiMAX"   " (MasC=uerade)",
      "digimax",
      settings_digimax_widget_create, NULL },
    {  "DS12C887 Real Time Clock"   " (MasC=uerade)",
      "ds12c887-rtc",
      settings_ds12c887_widget_create, NULL },
    {  "GEO-RAM"   " (MasC=uerade)",
      "geo-ram",
      settings_georam_widget_create, NULL },
    {  "SFX Sound Expander"   " (MasC=uerade)",
      "sfx-sound-expander",
      settings_sfxsoundexpander_widget_create, NULL },
    {  "SFX Sound Sampler"   " (MasC=uerade)",
      "sfx-sound-sampler",
      settings_sfxsoundsampler_widget_create, NULL },
     { NULL, NULL, NULL, NULL }
}
}}}
{{{ vic20_cartridges
List of VIC-20 I/O extensions