vsid: drive/drivecpu65c02.h File Reference
drivecpu65c02.h File Reference
#include "types.h"
Macros
#define OPINFO_NUMBER_MSK 0xff
Masks to extract information.
#define OPINFO_NUMBER(opinfo) ((opinfo) & OPINFO_NUMBER_MSK)
Return the opcode number for ‘opinfo’.
Functions
void drivecpu65c02_setup_context (struct diskunit_context_s *drv, int i)
void drivecpu65c02_init (struct diskunit_context_s *drv, int type)
void drivecpu65c02_reset (struct diskunit_context_s *drv)
void drivecpu65c02_sleep (struct diskunit_context_s *drv)
void drivecpu65c02_wake_up (struct diskunit_context_s *drv)
void drivecpu65c02_shutdown (struct diskunit_context_s *drv)
void drivecpu65c02_reset_clk (struct diskunit_context_s *drv)
void drivecpu65c02_trigger_reset (unsigned int dnr)
void drivecpu65c02_execute (struct diskunit_context_s *drv, CLOCK clk_value)
int drivecpu65c02_snapshot_write_module (struct diskunit_context_s *drv, struct snapshot_s *s)
int drivecpu65c02_snapshot_read_module (struct diskunit_context_s *drv, struct snapshot_s *s)
Macro Definition Documentation
OPINFO_NUMBER
#define OPINFO_NUMBER (opinfo) ((opinfo) & OPINFO_NUMBER_MSK)
Return the opcode number for ‘opinfo’.
OPINFO_NUMBER_MSK
#define OPINFO_NUMBER_MSK 0xff
Masks to extract information.
Function Documentation
drivecpu65c02_execute()
void drivecpu65c02_execute (struct diskunit_context_s * drv, CLOCK clk_value)
Include the R65C02 CPU emulation core.
WDC_STP() and WDC_WAI() are not used on the R65C02.
Referenced by drive_cpu_execute_one().
drivecpu65c02_init()
void drivecpu65c02_init (diskunit_context_t * drv, int type)
Todo:
check type is always already set, and remove it as parameter
Referenced by drive_init(), and drive_set_disk_drive_type().
drivecpu65c02_reset()
void drivecpu65c02_reset (struct diskunit_context_s * drv)
Referenced by drive_cpu_trigger_reset(), drivecpu65c02_init(), and drivecpu65c02_snapshot_read_module().
drivecpu65c02_reset_clk()
void drivecpu65c02_reset_clk (struct diskunit_context_s * drv)
Referenced by drivecpu65c02_reset(), and set_drive_true_emulation().
drivecpu65c02_setup_context()
void drivecpu65c02_setup_context (struct diskunit_context_s * drv, int i)
Referenced by drive_set_disk_drive_type().
drivecpu65c02_shutdown()
void drivecpu65c02_shutdown (struct diskunit_context_s * drv)
Referenced by drive_shutdown().
drivecpu65c02_sleep()
void drivecpu65c02_sleep (struct diskunit_context_s * drv)
Referenced by drive_disable(), and drivecpu65c02_execute().
drivecpu65c02_snapshot_read_module()
int drivecpu65c02_snapshot_read_module (struct diskunit_context_s * drv, struct snapshot_s * s)
< ASCII for HD
Referenced by drive_snapshot_read_module().
drivecpu65c02_snapshot_write_module()
int drivecpu65c02_snapshot_write_module (struct diskunit_context_s * drv, struct snapshot_s * s)
< ASCII for HD
Referenced by drive_snapshot_write_module().
drivecpu65c02_trigger_reset()
void drivecpu65c02_trigger_reset (unsigned int dnr)
drivecpu65c02_wake_up()
void drivecpu65c02_wake_up (struct diskunit_context_s * drv)
Todo:
FIXME: this value could break some programs, or be way too high for others. Maybe we should put it into a user-definable resource.
Referenced by drive_enable(), and drivecpu65c02_execute().