vsid: arch/shared/uiactions.c File Reference
uiactions.c File Reference
UI actions interface.
#include "vice.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "drive.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "uiapi.h"
#include "vhkkeysyms.h"
#include "uiactions.h"
Data Structures
struct ui_action_info_private_s
Mapping of action names to descriptions and machine support.
Macros
#define ARRAY_LEN(arr) (sizeof (arr) / sizeof (arr[0]))
Enable debugging.
Typedefs
typedef struct ui_action_info_private_s ui_action_info_private_t
Mapping of action names to descriptions and machine support.
Functions
static bool is_current_machine_action (const ui_action_info_private_t *action)
Test if action is valid for the current machine.
static const ui_action_info_private_t * get_info_private (int action)
Get "private" info about a UI action.
int ui_action_get_id (const char *name)
Get action ID by name.
const char * ui_action_get_name (int action)
Get action name by ID.
const char * ui_action_get_desc (int action)
Get description of an action.
bool ui_action_is_valid (int action)
Determine if action is valid for the current machine.
ui_action_info_t * ui_action_get_info_list (void)
Get list of actions.
static int get_drive_action_id (const int ids[4][2], int unit, int drive)
Get action ID for a drive action.
int ui_action_id_fliplist_add (int unit, int drive)
Get fliplist-add action ID for unit and drive.
int ui_action_id_fliplist_remove (int unit, int drive)
Get fliplist-remove action ID for unit and drive.
int ui_action_id_fliplist_next (int unit, int drive)
Get fliplist-next action ID for unit and drive.
int ui_action_id_fliplist_previous (int unit, int drive)
Get fliplist-previous action ID for unit and drive.
int ui_action_id_fliplist_clear (int unit, int drive)
Get fliplist-clear action ID for unit and drive.
int ui_action_id_fliplist_load (int unit, int drive)
Get fliplist-load action ID for unit and drive.
int ui_action_id_fliplist_save (int unit, int drive)
Get fliplist-save action ID for unit and drive.
int ui_action_id_drive_attach (int unit, int drive)
Get drive-attach action ID for unit and drive.
int ui_action_id_drive_detach (int unit, int drive)
Get drive-detach action ID for unit and drive.
int ui_action_id_drive_reset (int unit)
Get reset-drive action ID for unit.
int ui_action_id_drive_reset_config (int unit)
Get reset-drive-config action ID for unit.
int ui_action_id_drive_reset_install (int unit)
Get reset-drive-install action ID for unit.
static ui_action_map_t * find_action_map (int action)
Find action mapping by action ID with valid handler.
void ui_actions_init (void)
Initialize UI actions system.
void ui_actions_set_dispatch (void(*dispatch)(ui_action_map_t *))
Set UI-specific function to dispatch UI action handlers.
void ui_actions_shutdown (void)
Free all resources used by the UI actions system.
void ui_actions_register (const ui_action_map_t *mappings)
Register UI action implementations.
void ui_action_trigger (int action)
Trigger a UI action.
void ui_action_finish (int action)
Mark a UI action as finished.
static bool is_valid_index (int action)
Check if action is a valid index in the mappings array.
ui_action_map_t * ui_action_map_get (int action)
Get UI action map by UI action ID.
ui_action_map_t * ui_action_map_get_by_hotkey (uint32_t vice_keysym, uint32_t vice_modmask)
Get UI action map by VICE hotkey.
ui_action_map_t * ui_action_map_get_by_arch_hotkey (uint32_t arch_keysym, uint32_t arch_modmask)
Get UI action map by arch hotkey.
void ui_action_map_clear_hotkey (ui_action_map_t *map)
Clear hotkey.
void ui_action_map_clear_hotkey_by_action (int action)
Clear hotkey.
void ui_action_map_clear_hotkey_by_hotkey (uint32_t vice_keysym, uint32_t vice_modmask)
Clear hotkey.
ui_action_map_t * ui_action_map_set_hotkey (int action, uint32_t vice_keysym, uint32_t vice_modmask, uint32_t arch_keysym, uint32_t arch_modmask)
Set hotkey for action.
void ui_action_map_set_hotkey_by_map (ui_action_map_t *map, uint32_t vice_keysym, uint32_t vice_modmask, uint32_t arch_keysym, uint32_t arch_modmask)
Set hotkey for action.
char * ui_action_map_get_hotkey_label (ui_action_map_t *map)
Get hotkey label for action map.
char * ui_action_get_hotkey_label (int action)
Get hotkey label for action ID.
Variables
static const ui_action_info_private_t action_info_list []
List of UI actions.
static const int fliplist_add_ids [4][2]
Action IDs for fliplist-add-[unit]:[drive].
static const int fliplist_remove_ids [4][2]
Action IDs for fliplist-remove-[unit]:[drive].
static const int fliplist_next_ids [4][2]
Action IDs for fliplist-next-[unit]:[drive].
static const int fliplist_previous_ids [4][2]
Action IDs for fliplist-previous-[unit]:[drive].
static const int fliplist_clear_ids [4][2]
Action IDs for fliplist-clear-[unit]:[drive].
static const int fliplist_load_ids [4][2]
Action IDs for fliplist-load-[unit]:[drive].
static const int fliplist_save_ids [4][2]
Action IDs for fliplist-save-[unit]:[drive].
static const int drive_attach_ids [4][2]
Action IDs for drive-attach-[unit]:[drive].
static const int drive_detach_ids [4][2]
Action IDs for drive-detach-[unit]:[drive].
static const int drive_reset_ids [4]
static const int drive_reset_config_ids [4]
static const int drive_reset_install_ids [4]
static ui_action_map_t action_mappings [ACTION_ID_COUNT]
List of mappings of action IDs to handlers.
static bool dialog_active = false
Flag indicating a dialog is active.
static void(* dispatch_handler)(ui_action_map_t *) = NULL
UI action dispatch handler.
Detailed Description
UI actions interface.
System to handle UI actions in an OS/UI-agnostic way.
Used by menu structs, hotkeys and joystick mappings. There will be no Doxygen docblocks for most of the defines, since they're self-explanatory. And obviously I will not bitch about keeping the text within 80 columns here :D
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
ARRAY_LEN
#define ARRAY_LEN (arr) (sizeof (arr) / sizeof (arr[0]))
Enable debugging.
Typedef Documentation
ui_action_info_private_t
typedef struct ui_action_info_private_s ui_action_info_private_t
Mapping of action names to descriptions and machine support.
The 'machine' members is a bitmask that indicates which machines support the action.
Function Documentation
find_action_map()
static ui_action_map_t * find_action_map (int action) static
Find action mapping by action ID with valid handler.
Parameters
[in] action action ID
Returns
action mapping or NULL when no handler registered
Referenced by ui_action_finish(), and ui_action_trigger().
get_drive_action_id()
static int get_drive_action_id (const int ids[4][2], int unit, int drive) static
Get action ID for a drive action.
Parameters
[in] ids array with action IDs for unit and drive
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by ui_action_id_drive_attach(), ui_action_id_drive_detach(), ui_action_id_fliplist_add(), ui_action_id_fliplist_clear(), ui_action_id_fliplist_load(), ui_action_id_fliplist_next(), ui_action_id_fliplist_previous(), ui_action_id_fliplist_remove(), and ui_action_id_fliplist_save().
get_info_private()
static const ui_action_info_private_t * get_info_private (int action) static
Get "private" info about a UI action.
Parameters
[in] id action ID
Returns
pointer to info or NULL on failure
Referenced by ui_action_get_desc(), ui_action_get_name(), and ui_action_is_valid().
is_current_machine_action()
static bool is_current_machine_action (const ui_action_info_private_t * action) static
Test if action is valid for the current machine.
Parameters
[in] action UI action
Returns
bool
Referenced by ui_action_get_info_list(), and ui_action_is_valid().
is_valid_index()
static bool is_valid_index (int action) static
Check if action is a valid index in the mappings array.
Parameters
[in] action UI action ID
Returns
true if valid index
Referenced by ui_action_map_get().
ui_action_finish()
void ui_action_finish (int action)
Mark a UI action as finished.
For actions that are blocking (ie dialogs) we need to notify the action handling system the action has finished and can be triggered again.
Parameters
[in] action_id
Referenced by about_destroy_callback(), cart_detach_action(), clear_playlist_callback(), confirm_detach_callback(), confirm_exit_callback(), fliplist_load_response(), fliplist_save_response(), fps_custom_callback(), help_manual_action(), load_snapshot_filename_callback(), on_destroy(), on_dialog_destroy(), on_response(), on_settings_dialog_destroy(), on_settings_save_to_filename(), playlist_load_callback(), playlist_save_dialog_callback(), quit_action(), restore_default_callback(), save_snapshot_dialog(), settings_load_action(), settings_load_filename_callback(), settings_save_action(), and speed_cpu_custom_callback().
ui_action_get_desc()
const char * ui_action_get_desc (int action)
Get description of an action.
Looks up the description for action.
Parameters
[in] action UI action ID
Returns
description or NULL when action not found
ui_action_get_hotkey_label()
char * ui_action_get_hotkey_label (int action)
Get hotkey label for action ID.
Parameters
[in] action UI action ID
Returns
label for hotkey, free with lib_free()
ui_action_get_id()
int ui_action_get_id (const char * name)
Get action ID by name.
Action info getters.
Get the action name as used by the vhk files.
Parameters
[in] name action name
Returns
ID or -1 when not found
Referenced by vhk_parser_handle_mapping().
ui_action_get_info_list()
ui_action_info_t * ui_action_get_info_list (void)
Get list of actions.
Returns
list of (id, name, desc) tuples for UI actions
Note
The returned list is allocated with lib_malloc() and should be freed after use with lib_free(), the members of each element should not be freed.
Referenced by create_hotkeys_model().
ui_action_get_name()
const char * ui_action_get_name (int action)
Get action name by ID.
Parameters
[in] action UI action ID
Returns
action name or NULL when not found
Note
Also returns NULL for NONE and INVALID
Referenced by dialog_accept_handler(), on_menu_item_toggled(), on_response(), push_button_callback(), speed_cpu_custom_action(), speed_fps_custom_action(), toggle_button_callback(), ui_action_finish(), ui_action_trigger(), ui_actions_register(), ui_hotkeys_arch_remove_by_map(), ui_hotkeys_remove_all(), ui_hotkeys_save_as(), and vhk_parser_do_undef().
ui_action_id_drive_attach()
int ui_action_id_drive_attach (int unit, int drive)
Get drive-attach action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by on_destroy(), on_disk_attach(), and ui_do_drive_popup().
ui_action_id_drive_detach()
int ui_action_id_drive_detach (int unit, int drive)
Get drive-detach action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by on_disk_detach(), and ui_do_drive_popup().
ui_action_id_drive_reset()
int ui_action_id_drive_reset (int unit)
Get reset-drive action ID for unit.
Parameters
[in] unit unit number (8-11)
Returns
action ID or ACTION_NONE for invalud unit
Referenced by ui_do_drive_popup().
ui_action_id_drive_reset_config()
int ui_action_id_drive_reset_config (int unit)
Get reset-drive-config action ID for unit.
Parameters
[in] unit unit number (8-11)
Returns
action ID or ACTION_NONE for invalud unit
ui_action_id_drive_reset_install()
int ui_action_id_drive_reset_install (int unit)
Get reset-drive-install action ID for unit.
Parameters
[in] unit unit number (8-11)
Returns
action ID or ACTION_NONE for invalud unit
ui_action_id_fliplist_add()
int ui_action_id_fliplist_add (int unit, int drive)
Get fliplist-add action ID for unit and drive.
Get action IDs for drive actions.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by ui_do_drive_popup().
ui_action_id_fliplist_clear()
int ui_action_id_fliplist_clear (int unit, int drive)
Get fliplist-clear action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by ui_do_drive_popup().
ui_action_id_fliplist_load()
int ui_action_id_fliplist_load (int unit, int drive)
Get fliplist-load action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by fliplist_load_response().
ui_action_id_fliplist_next()
int ui_action_id_fliplist_next (int unit, int drive)
Get fliplist-next action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by ui_populate_fliplist_menu().
ui_action_id_fliplist_previous()
int ui_action_id_fliplist_previous (int unit, int drive)
Get fliplist-previous action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by ui_populate_fliplist_menu().
ui_action_id_fliplist_remove()
int ui_action_id_fliplist_remove (int unit, int drive)
Get fliplist-remove action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
ui_action_id_fliplist_save()
int ui_action_id_fliplist_save (int unit, int drive)
Get fliplist-save action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by fliplist_save_response().
ui_action_is_valid()
bool ui_action_is_valid (int action)
Determine if action is valid for the current machine.
Parameters
[in] action UI action ID
Returns
true when valid for current machine
Referenced by actions_joystick_setup_ui(), and vhk_parser_handle_mapping().
ui_action_map_clear_hotkey()
void ui_action_map_clear_hotkey (ui_action_map_t * map)
Clear hotkey.
Set the VICE and arch keysyms and modifier masks to 0 in map.
Parameters
[in] map UI action map
Referenced by dialog_accept_handler(), ui_action_map_clear_hotkey_by_action(), ui_action_map_clear_hotkey_by_hotkey(), ui_hotkeys_remove_all(), ui_hotkeys_remove_by_map(), and vhk_parser_do_undef().
ui_action_map_clear_hotkey_by_action()
void ui_action_map_clear_hotkey_by_action (int action)
Clear hotkey.
Set VICE and arch keysyms and modifier masks to 0.
Parameters
[in] action UI action ID
ui_action_map_clear_hotkey_by_hotkey()
void ui_action_map_clear_hotkey_by_hotkey (uint32_t vice_keysym, uint32_t vice_modmask)
Clear hotkey.
Set VICE and arch keysyms and modifier masks to 0.
Parameters
[in] vice_keysym VICE keysym
[in] vice_modmask VICE modifier mask
ui_action_map_get()
ui_action_map_t * ui_action_map_get (int action)
Get UI action map by UI action ID.
Parameters
[in] action UI action ID
Returns
UI action map or NULL when action is invalid
Referenced by create_hotkeys_model(), dialog_accept_handler(), ui_action_get_hotkey_label(), ui_action_map_clear_hotkey_by_action(), ui_action_map_set_hotkey(), ui_hotkeys_arch_shutdown(), ui_hotkeys_remove_all(), ui_hotkeys_remove_by_action(), ui_hotkeys_save_as(), ui_hotkeys_update_by_action(), ui_menu_add(), vhk_gtk_get_accel_label_by_action(), vhk_gtk_get_menu_item_by_action_for_window(), vhk_gtk_set_check_item_blocked_by_action(), vhk_gtk_set_check_item_blocked_by_action_for_window(), and vhk_gtk_set_menu_item_accel_label().
ui_action_map_get_by_arch_hotkey()
ui_action_map_t * ui_action_map_get_by_arch_hotkey (uint32_t arch_keysym, uint32_t arch_modmask)
Get UI action map by arch hotkey.
Parameters
[in] arch_keysym arch keysym
[in] arch_modmask arch modifier mask
Returns
UI action map or NULL when not found
Referenced by dialog_accept_handler().
ui_action_map_get_by_hotkey()
ui_action_map_t * ui_action_map_get_by_hotkey (uint32_t vice_keysym, uint32_t vice_modmask)
Get UI action map by VICE hotkey.
Parameters
[in] vice_keysym VICE keysym
[in] vice_modmask VICE modifier mask
Returns
UI action map or NULL when not found
Referenced by ui_action_map_clear_hotkey_by_hotkey(), ui_action_map_get_by_arch_hotkey(), and vhk_parser_do_undef().
ui_action_map_get_hotkey_label()
char * ui_action_map_get_hotkey_label (ui_action_map_t * map)
Get hotkey label for action map.
Parameters
[in] map UI action map
Returns
label for hotkey, free with lib_free()
Referenced by ui_action_get_hotkey_label().
ui_action_map_set_hotkey()
ui_action_map_t * ui_action_map_set_hotkey (int action, uint32_t vice_keysym, uint32_t vice_modmask, uint32_t arch_keysym, uint32_t arch_modmask)
Set hotkey for action.
Parameters
[in] action action ID
[in] vice_keysym VICE keysym
[in] vice_modmask VICE modifier mask
[in] arch_keysym arch keysym
[in] arch_modmask arch modifier mask
Returns
pointer to map or NULL on error
Referenced by vhk_parser_handle_mapping().
ui_action_map_set_hotkey_by_map()
void ui_action_map_set_hotkey_by_map (ui_action_map_t * map, uint32_t vice_keysym, uint32_t vice_modmask, uint32_t arch_keysym, uint32_t arch_modmask)
Set hotkey for action.
Parameters
[in] map UI action map
[in] vice_keysym VICE keysym
[in] vice_modmask VICE modifier mask
[in] arch_keysym arch keysym
[in] arch_modmask arch modifier mask
ui_action_trigger()
void ui_action_trigger (int action)
Trigger a UI action.
Calls the action dispatch handler if conditions are met.
If an action is marked as a dialog then it will only be triggered when there is no other dialog active. If an action is marked as blocking i will only be triggered when it isn't marked as busy.
Parameters
[in] action action ID
See also
src/arch/shared/uiactions.h for IDs
Referenced by arch_ui_activate(), handle_accelerator(), on_action_item_activate(), on_clicked(), on_delete_event(), on_disk_attach(), on_disk_detach(), on_menu_item_activate(), on_menu_item_toggled(), on_swap_joysticks_toggled(), pause_led_callback(), push_button_callback(), rendering_area_event_handler(), restore_display_action(), toggle_button_callback(), trigger_ui_action(), vsid_control_widget_next_tune(), vsid_tune_info_widget_update(), and warp_led_callback().
ui_actions_init()
void ui_actions_init (void)
Initialize UI actions system.
Main API.
Note
This needs is called from the shared init code, the UI needs to subsequently call ui_actions_set_dispatch() to register the function that actually executes the action handler function
Referenced by main_program().
ui_actions_register()
void ui_actions_register (const ui_action_map_t * mappings)
Register UI action implementations.
Add action handlers in mappings to the runtime action mappings.
Parameters
[in] mappings list of action IDs mapped to action handlers
Referenced by actions_cartridge_register(), actions_clipboard_register(), actions_datasette_register(), actions_display_register(), actions_drive_register(), actions_help_register(), actions_hotkeys_register(), actions_joystick_register(), actions_machine_register(), actions_media_register(), actions_printer_register(), actions_settings_register(), actions_snapshot_register(), actions_speed_register(), and actions_vsid_register().
ui_actions_set_dispatch()
void ui_actions_set_dispatch (void(*)(ui_action_map_t *) dispatch)
Set UI-specific function to dispatch UI action handlers.
Parameters
[in] dispatch function to call with an action map as its argument to have the UI actually invoke the handler on the proper thread
Note
Installing a dispatch handler is optional, when not installed an action's handler is called directly by ui_action_trigger().
Referenced by ui_init_finalize().
ui_actions_shutdown()
void ui_actions_shutdown (void)
Free all resources used by the UI actions system.
Referenced by machine_shutdown().
Variable Documentation
action_info_list
const ui_action_info_private_t action_info_list[] static
List of UI actions.
Referenced by get_info_private(), ui_action_get_id(), and ui_action_get_info_list().
action_mappings
ui_action_map_t action_mappings[ACTION_ID_COUNT] static
List of mappings of action IDs to handlers.
A simple array indexed by action ID
Referenced by find_action_map(), is_valid_index(), ui_action_map_get(), ui_action_map_get_by_hotkey(), ui_actions_init(), and ui_actions_register().
dialog_active
bool dialog_active = false static
Flag indicating a dialog is active.
Used to avoid spawning multiple dialogs via UI actions, we don't want a user to map a controller button to "drive-attach-8:0" and then spam a ton of dialogs.
Referenced by ui_action_finish(), ui_action_trigger(), and ui_actions_init().
dispatch_handler
void(* dispatch_handler) (ui_action_map_t *) (ui_action_map_t *) = NULL static
UI action dispatch handler.
Function to trigger the action handler on the proper thread in a UI. This can remain NULL in which case the handler of an action is called directly on the thread that called ui_action_trigger().
Referenced by ui_action_trigger(), and ui_actions_set_dispatch().
drive_attach_ids
const int drive_attach_ids[4][2] static
Initial value:
= {
    { ACTION_DRIVE_ATTACH_8_0,  ACTION_DRIVE_ATTACH_8_1 },
    { ACTION_DRIVE_ATTACH_9_0,  ACTION_DRIVE_ATTACH_9_1 },
    { ACTION_DRIVE_ATTACH_10_0, ACTION_DRIVE_ATTACH_10_1 },
    { ACTION_DRIVE_ATTACH_11_0, ACTION_DRIVE_ATTACH_11_1 }
}
Action IDs for drive-attach-[unit]:[drive].
Referenced by ui_action_id_drive_attach().
drive_detach_ids
const int drive_detach_ids[4][2] static
Initial value:
= {
    { ACTION_DRIVE_DETACH_8_0,  ACTION_DRIVE_DETACH_8_1 },
    { ACTION_DRIVE_DETACH_9_0,  ACTION_DRIVE_DETACH_9_1 },
    { ACTION_DRIVE_DETACH_10_0, ACTION_DRIVE_DETACH_10_1 },
    { ACTION_DRIVE_DETACH_11_0, ACTION_DRIVE_DETACH_11_1 }
}
Action IDs for drive-detach-[unit]:[drive].
Referenced by ui_action_id_drive_detach().
drive_reset_config_ids
const int drive_reset_config_ids[4] static
Initial value:
= {
    ACTION_RESET_DRIVE_8_CONFIG,
    ACTION_RESET_DRIVE_9_CONFIG,
    ACTION_RESET_DRIVE_10_CONFIG,
    ACTION_RESET_DRIVE_11_CONFIG
}
Referenced by ui_action_id_drive_reset_config().
drive_reset_ids
const int drive_reset_ids[4] static
Initial value:
= {
    ACTION_RESET_DRIVE_8,
    ACTION_RESET_DRIVE_9,
    ACTION_RESET_DRIVE_10,
    ACTION_RESET_DRIVE_11
}
Referenced by ui_action_id_drive_reset().
drive_reset_install_ids
const int drive_reset_install_ids[4] static
Initial value:
= {
    ACTION_RESET_DRIVE_8_INSTALL,
    ACTION_RESET_DRIVE_9_INSTALL,
    ACTION_RESET_DRIVE_10_INSTALL,
    ACTION_RESET_DRIVE_11_INSTALL
}
Referenced by ui_action_id_drive_reset_install().
fliplist_add_ids
const int fliplist_add_ids[4][2] static
Initial value:
= {
    { ACTION_FLIPLIST_ADD_8_0,      ACTION_FLIPLIST_ADD_8_1 },
    { ACTION_FLIPLIST_ADD_9_0,      ACTION_FLIPLIST_ADD_9_1 },
    { ACTION_FLIPLIST_ADD_10_0,     ACTION_FLIPLIST_ADD_10_1 },
    { ACTION_FLIPLIST_ADD_11_0,     ACTION_FLIPLIST_ADD_11_1 }
}
Action IDs for fliplist-add-[unit]:[drive].
Referenced by ui_action_id_fliplist_add().
fliplist_clear_ids
const int fliplist_clear_ids[4][2] static
Initial value:
= {
    { ACTION_FLIPLIST_CLEAR_8_0,    ACTION_FLIPLIST_CLEAR_8_1 },
    { ACTION_FLIPLIST_CLEAR_9_0,    ACTION_FLIPLIST_CLEAR_9_1 },
    { ACTION_FLIPLIST_CLEAR_10_0,   ACTION_FLIPLIST_CLEAR_10_1 },
    { ACTION_FLIPLIST_CLEAR_11_0,   ACTION_FLIPLIST_CLEAR_11_1 }
}
Action IDs for fliplist-clear-[unit]:[drive].
Referenced by ui_action_id_fliplist_clear().
fliplist_load_ids
const int fliplist_load_ids[4][2] static
Initial value:
= {
    { ACTION_FLIPLIST_LOAD_8_0,     ACTION_FLIPLIST_LOAD_8_1 },
    { ACTION_FLIPLIST_LOAD_9_0,     ACTION_FLIPLIST_LOAD_9_1 },
    { ACTION_FLIPLIST_LOAD_10_0,    ACTION_FLIPLIST_LOAD_10_1 },
    { ACTION_FLIPLIST_LOAD_11_0,    ACTION_FLIPLIST_LOAD_11_1 }
}
Action IDs for fliplist-load-[unit]:[drive].
Referenced by ui_action_id_fliplist_load().
fliplist_next_ids
const int fliplist_next_ids[4][2] static
Initial value:
= {
    { ACTION_FLIPLIST_NEXT_8_0,     ACTION_FLIPLIST_NEXT_8_1 },
    { ACTION_FLIPLIST_NEXT_9_0,     ACTION_FLIPLIST_NEXT_9_1 },
    { ACTION_FLIPLIST_NEXT_10_0,    ACTION_FLIPLIST_NEXT_10_1 },
    { ACTION_FLIPLIST_NEXT_11_0,    ACTION_FLIPLIST_NEXT_11_1 }
}
Action IDs for fliplist-next-[unit]:[drive].
Referenced by ui_action_id_fliplist_next().
fliplist_previous_ids
const int fliplist_previous_ids[4][2] static
Initial value:
= {
    { ACTION_FLIPLIST_PREVIOUS_8_0,     ACTION_FLIPLIST_PREVIOUS_8_1 },
    { ACTION_FLIPLIST_PREVIOUS_9_0,     ACTION_FLIPLIST_PREVIOUS_9_1 },
    { ACTION_FLIPLIST_PREVIOUS_10_0,    ACTION_FLIPLIST_PREVIOUS_10_1 },
    { ACTION_FLIPLIST_PREVIOUS_11_0,    ACTION_FLIPLIST_PREVIOUS_11_1 }
}
Action IDs for fliplist-previous-[unit]:[drive].
Referenced by ui_action_id_fliplist_previous().
fliplist_remove_ids
const int fliplist_remove_ids[4][2] static
Initial value:
= {
    { ACTION_FLIPLIST_REMOVE_8_0,   ACTION_FLIPLIST_REMOVE_8_1 },
    { ACTION_FLIPLIST_REMOVE_9_0,   ACTION_FLIPLIST_REMOVE_9_1 },
    { ACTION_FLIPLIST_REMOVE_10_0,  ACTION_FLIPLIST_REMOVE_10_1 },
    { ACTION_FLIPLIST_REMOVE_11_0,  ACTION_FLIPLIST_REMOVE_11_1 }
}
Action IDs for fliplist-remove-[unit]:[drive].
Referenced by ui_action_id_fliplist_remove().
fliplist_save_ids
const int fliplist_save_ids[4][2] static
Initial value:
= {
    { ACTION_FLIPLIST_SAVE_8_0,     ACTION_FLIPLIST_SAVE_8_1 },
    { ACTION_FLIPLIST_SAVE_9_0,     ACTION_FLIPLIST_SAVE_9_1 },
    { ACTION_FLIPLIST_SAVE_10_0,    ACTION_FLIPLIST_SAVE_10_1 },
    { ACTION_FLIPLIST_SAVE_11_0,    ACTION_FLIPLIST_SAVE_11_1 }
}
Action IDs for fliplist-save-[unit]:[drive].
Referenced by ui_action_id_fliplist_save().