x128: monitor/mon_disassemble.c File Reference
mon_disassemble.c File Reference
The VICE built-in monitor, disassembler module.
#include "mem.h"
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "asm.h"
#include "console.h"
#include "log.h"
#include "mon_disassemble.h"
#include "mon_util.h"
#include "monitor.h"
#include "types.h"
#include "uimon.h"
Macros
#define SKIP_PREFIX_6809() remove_6809_prefix(mon_cpu_type->cpu_type, &prefix, opc)
#define SKIP_PREFIX_Z80() remove_z80_prefix(mon_cpu_type->cpu_type, opc, &ival)
#define x opc[0]
#define p1 opc[1]
#define p2 opc[2]
#define p3 opc[3]
#define p4 opc[4]
#define BAD_ADDR (new_addr(e_invalid_space, 0))
Functions
static void remove_6809_prefix (CPU_TYPE_t cpu_type, int *prefix, uint8_t *opc)
static const char * get_6309_bitwise_reg (uint8_t val)
static void remove_z80_prefix (CPU_TYPE_t cpu_type, uint8_t *opc, unsigned int *ival)
static const char * mon_disassemble_to_string_internal (MEMSPACE memspace, unsigned int addr, uint8_t opc[5], int hex_mode, unsigned *opc_size_p, monitor_cpu_type_t *mon_cpu_type)
static const char * mon_disassemble_instr_memconfig_internal (unsigned *opc_size, MON_ADDR addr)
static const char * mon_disassemble_instr_bank_internal (unsigned *opc_size, MON_ADDR addr)
const char * mon_disassemble_to_string (MEMSPACE memspace, unsigned int addr, unsigned int x, unsigned int p1, unsigned int p2, unsigned int p3, int hex_mode, const char *cpu_type)
Disassemble interace.
const char * mon_disassemble_to_string_ex (MEMSPACE memspace, unsigned int addr, unsigned int x, unsigned int p1, unsigned int p2, unsigned int p3, int hex_mode, unsigned *opc_size_p)
static unsigned mon_disassemble_instr (MON_ADDR addr, int *line_count)
void mon_disassemble_with_regdump (MEMSPACE mem, unsigned int addr)
void mon_disassemble_lines (MON_ADDR start_addr, MON_ADDR end_addr)
Variables
static const char *const reg6809 []
static const char *const reg6309 []
const char index_reg6809 [] = { 'X', 'Y', 'U', 'S' }
Detailed Description
The VICE built-in monitor, disassembler module.
Author
Daniel Sladic sladi.nosp@m.c@ee.nosp@m.cg.to.nosp@m.ront.nosp@m.o.edu
Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Macro Definition Documentation
BAD_ADDR
#define BAD_ADDR (new_addr(e_invalid_space, 0))
p1
#define p1 opc[1]
p2
#define p2 opc[2]
p3
#define p3 opc[3]
p4
#define p4 opc[4]
SKIP_PREFIX_6809
#define SKIP_PREFIX_6809 () remove_6809_prefix(mon_cpu_type->cpu_type, &prefix, opc)
SKIP_PREFIX_Z80
#define SKIP_PREFIX_Z80 () remove_z80_prefix(mon_cpu_type->cpu_type, opc, &ival)
x
#define x opc[0]
Function Documentation
get_6309_bitwise_reg()
static const char * get_6309_bitwise_reg (uint8_t val) static
Referenced by mon_disassemble_to_string_internal().
mon_disassemble_instr()
static unsigned mon_disassemble_instr (MON_ADDR addr, int * line_count) static
Referenced by mon_disassemble_lines().
mon_disassemble_instr_bank_internal()
static const char * mon_disassemble_instr_bank_internal (unsigned * opc_size, MON_ADDR addr) static
Referenced by mon_disassemble_instr().
mon_disassemble_instr_memconfig_internal()
static const char * mon_disassemble_instr_memconfig_internal (unsigned * opc_size, MON_ADDR addr) static
Referenced by mon_disassemble_with_regdump().
mon_disassemble_lines()
void mon_disassemble_lines (MON_ADDR start_addr, MON_ADDR end_addr)
mon_disassemble_to_string()
const char * mon_disassemble_to_string (MEMSPACE memspace, unsigned int addr, unsigned int x, unsigned int p1, unsigned int p2, unsigned int p3, int hex_mode, const char * cpu_type)
Disassemble interace.
Prototypes
Referenced by z80_maincpu_loop().
mon_disassemble_to_string_ex()
const char * mon_disassemble_to_string_ex (MEMSPACE memspace, unsigned int addr, unsigned int x, unsigned int p1, unsigned int p2, unsigned int p3, int hex_mode, unsigned * opc_size_p)
Referenced by mon_disassemble_oneline(), and mon_disassemble_with_label().
mon_disassemble_to_string_internal()
static const char * mon_disassemble_to_string_internal (MEMSPACE memspace, unsigned int addr, uint8_t opc[5], int hex_mode, unsigned * opc_size_p, monitor_cpu_type_t * mon_cpu_type) static
Referenced by mon_disassemble_instr_bank_internal(), mon_disassemble_instr_memconfig_internal(), mon_disassemble_to_string(), and mon_disassemble_to_string_ex().
mon_disassemble_with_regdump()
void mon_disassemble_with_regdump (MEMSPACE mem, unsigned int addr)
Referenced by mon_breakpoint_check_checkpoint(), and monitor_open().
remove_6809_prefix()
static void remove_6809_prefix (CPU_TYPE_t cpu_type, int * prefix, uint8_t * opc) static
remove_z80_prefix()
static void remove_z80_prefix (CPU_TYPE_t cpu_type, uint8_t * opc, unsigned int * ival) static
Variable Documentation
index_reg6809
const char index_reg6809[] = { 'X', 'Y', 'U', 'S' }
Referenced by mon_disassemble_to_string_internal().
reg6309
const char* const reg6309[] static
Initial value:
= {
    "D", "X", "Y", "U", "S", "PC", "W", "V",
    "A", "B", "CC", "DP", "0", "0", "E", "F"
}
Referenced by mon_disassemble_to_string_internal().
reg6809
const char* const reg6809[] static
Initial value:
= {
    "D", "X", "Y", "U", "S", "PC", "?R6", "?R7",
    "A", "B", "CC", "DP", "?RC", "?RD", "?RE", "?RF"
}
Referenced by mon_disassemble_to_string_internal().