x128: monitor/mon_breakpoint.c File Reference
mon_breakpoint.c File Reference
The VICE built-in monitor breakpoint functions.
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "mon_breakpoint.h"
#include "mon_disassemble.h"
#include "mon_util.h"
#include "montypes.h"
#include "monitor.h"
#include "uimon.h"
#include "monitor_binary.h"
Data Structures
struct checkpoint_list_s
Typedefs
typedef struct checkpoint_list_s checkpoint_list_t
Functions
void mon_breakpoint_init (void)
static void remove_checkpoint_from_list (checkpoint_list_t **head, mon_checkpoint_t *cp)
mon_checkpoint_t ** mon_breakpoint_checkpoint_list_get (unsigned int *len)
Get a list of all checkpoints.
mon_checkpoint_t * mon_breakpoint_find_checkpoint (int brknum)
find the breakpoint with number 'brknum' in the linked list
static void update_checkpoint_state (MEMSPACE mem)
void mon_update_all_checkpoint_state (void)
Ensure checkpoint state for memspaces is set correctly.
void mon_breakpoint_set_dummy_state (MEMSPACE mem, int state)
static void remove_checkpoint (mon_checkpoint_t *cp)
void mon_breakpoint_switch_checkpoint (int op, int cp_num)
void mon_breakpoint_set_ignore_count (int cp_num, int count)
static void print_checkpoint_info (mon_checkpoint_t *cp)
void mon_breakpoint_print_checkpoints (void)
void mon_breakpoint_delete_checkpoint (int cp_num)
void mon_breakpoint_set_checkpoint_condition (int cp_num, cond_node_t *cnode)
void mon_breakpoint_set_checkpoint_command (int cp_num, char *cmd)
static checkpoint_list_t * search_checkpoint_list (checkpoint_list_t *head, unsigned loc)
static int compare_checkpoints (mon_checkpoint_t *bp1, mon_checkpoint_t *bp2)
static void mon_breakpoint_event (mon_checkpoint_t *checkpt)
bool mon_breakpoint_check_checkpoint (MEMSPACE mem, unsigned int addr, unsigned int lastpc, MEMORY_OP op)
static void add_to_checkpoint_list (checkpoint_list_t **head, mon_checkpoint_t *cp)
static int breakpoint_add_checkpoint (MON_ADDR start_addr, MON_ADDR end_addr, bool stop, MEMORY_OP memory_op, bool is_temp, bool do_print)
int mon_breakpoint_add_checkpoint (MON_ADDR start_addr, MON_ADDR end_addr, bool stop, MEMORY_OP op, bool is_temp, bool do_print)
mon_breakpoint_type_t mon_breakpoint_is (MON_ADDR address)
void mon_breakpoint_set (MON_ADDR address)
void mon_breakpoint_unset (MON_ADDR address)
void mon_breakpoint_enable (MON_ADDR address)
void mon_breakpoint_disable (MON_ADDR address)
Variables
static int breakpoint_count
static checkpoint_list_t * all_checkpoints
static checkpoint_list_t * breakpoints [e_invalid_space]
static checkpoint_list_t * watchpoints_load [e_invalid_space]
static checkpoint_list_t * watchpoints_store [e_invalid_space]
Detailed Description
The VICE built-in monitor breakpoint functions.
Author
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Daniel Sladic sladi.nosp@m.c@ee.nosp@m.cg.to.nosp@m.ront.nosp@m.o.edu
Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it
Typedef Documentation
checkpoint_list_t
typedef struct checkpoint_list_s checkpoint_list_t
Function Documentation
add_to_checkpoint_list()
static void add_to_checkpoint_list (checkpoint_list_t ** head, mon_checkpoint_t * cp) static
Referenced by breakpoint_add_checkpoint().
breakpoint_add_checkpoint()
static int breakpoint_add_checkpoint (MON_ADDR start_addr, MON_ADDR end_addr, bool stop, MEMORY_OP memory_op, bool is_temp, bool do_print) static
Referenced by mon_breakpoint_add_checkpoint(), and mon_breakpoint_set().
compare_checkpoints()
static int compare_checkpoints (mon_checkpoint_t * bp1, mon_checkpoint_t * bp2) static
Referenced by add_to_checkpoint_list().
mon_breakpoint_add_checkpoint()
int mon_breakpoint_add_checkpoint (MON_ADDR start_addr, MON_ADDR end_addr, bool stop, MEMORY_OP op, bool is_temp, bool do_print)
Referenced by monitor_binary_process_checkpoint_set(), and monitor_init().
mon_breakpoint_check_checkpoint()
bool mon_breakpoint_check_checkpoint (MEMSPACE mem, unsigned int addr, unsigned int lastpc, MEMORY_OP op)
Referenced by monitor_check_breakpoints(), watchpoints_check_loads(), and watchpoints_check_stores().
mon_breakpoint_checkpoint_list_get()
mon_checkpoint_t ** mon_breakpoint_checkpoint_list_get (unsigned int * len)
Get a list of all checkpoints.
Parameters
[out] len length of the returned array
Returns
The list of checkpoints
Referenced by monitor_binary_process_checkpoint_list().
mon_breakpoint_delete_checkpoint()
void mon_breakpoint_delete_checkpoint (int cp_num)
Referenced by mon_breakpoint_check_checkpoint(), and monitor_binary_process_checkpoint_delete().
mon_breakpoint_disable()
void mon_breakpoint_disable (MON_ADDR address)
mon_breakpoint_enable()
void mon_breakpoint_enable (MON_ADDR address)
mon_breakpoint_event()
static void mon_breakpoint_event (mon_checkpoint_t * checkpt) static
Referenced by mon_breakpoint_check_checkpoint().
mon_breakpoint_find_checkpoint()
mon_checkpoint_t * mon_breakpoint_find_checkpoint (int brknum)
find the breakpoint with number 'brknum' in the linked list
Parameters
[in] brknum breakpoint number
Returns
The checkpoint that has brknum, or NULL
Referenced by mon_breakpoint_delete_checkpoint(), mon_breakpoint_print_checkpoints(), mon_breakpoint_set_checkpoint_command(), mon_breakpoint_set_checkpoint_condition(), mon_breakpoint_set_ignore_count(), mon_breakpoint_switch_checkpoint(), monitor_binary_process_checkpoint_delete(), monitor_binary_process_checkpoint_get(), monitor_binary_process_checkpoint_set(), monitor_binary_process_checkpoint_toggle(), and monitor_binary_process_condition_set().
mon_breakpoint_init()
void mon_breakpoint_init (void)
Referenced by monitor_init().
mon_breakpoint_is()
mon_breakpoint_type_t mon_breakpoint_is (MON_ADDR address)
mon_breakpoint_print_checkpoints()
void mon_breakpoint_print_checkpoints (void)
mon_breakpoint_set()
void mon_breakpoint_set (MON_ADDR address)
mon_breakpoint_set_checkpoint_command()
void mon_breakpoint_set_checkpoint_command (int cp_num, char * cmd)
mon_breakpoint_set_checkpoint_condition()
void mon_breakpoint_set_checkpoint_condition (int cp_num, cond_node_t * cnode)
mon_breakpoint_set_dummy_state()
void mon_breakpoint_set_dummy_state (MEMSPACE mem, int state)
Todo:
FIXME: some day we might want to toggle the break-on-dummy-access per MEMSPACE, for now its a global option
mon_breakpoint_set_ignore_count()
void mon_breakpoint_set_ignore_count (int cp_num, int count)
mon_breakpoint_switch_checkpoint()
void mon_breakpoint_switch_checkpoint (int op, int cp_num)
Referenced by monitor_binary_process_checkpoint_set(), and monitor_binary_process_checkpoint_toggle().
mon_breakpoint_unset()
void mon_breakpoint_unset (MON_ADDR address)
mon_update_all_checkpoint_state()
void mon_update_all_checkpoint_state (void)
Ensure checkpoint state for memspaces is set correctly.
Used to keep breakpoints working after a snapshot load.
Referenced by load_snapshot_trap().
print_checkpoint_info()
static void print_checkpoint_info (mon_checkpoint_t * cp) static
Referenced by breakpoint_add_checkpoint(), and mon_breakpoint_print_checkpoints().
remove_checkpoint()
static void remove_checkpoint (mon_checkpoint_t * cp) static
Referenced by mon_breakpoint_delete_checkpoint().
remove_checkpoint_from_list()
static void remove_checkpoint_from_list (checkpoint_list_t ** head, mon_checkpoint_t * cp) static
Referenced by mon_breakpoint_unset(), and remove_checkpoint().
search_checkpoint_list()
static checkpoint_list_t * search_checkpoint_list (checkpoint_list_t * head, unsigned loc) static
Referenced by mon_breakpoint_check_checkpoint(), mon_breakpoint_disable(), mon_breakpoint_enable(), mon_breakpoint_is(), mon_breakpoint_set(), and mon_breakpoint_unset().
update_checkpoint_state()
static void update_checkpoint_state (MEMSPACE mem) static
Referenced by breakpoint_add_checkpoint(), mon_breakpoint_set_dummy_state(), mon_update_all_checkpoint_state(), and remove_checkpoint().
Variable Documentation
all_checkpoints
checkpoint_list_t* all_checkpoints static
Referenced by breakpoint_add_checkpoint(), mon_breakpoint_checkpoint_list_get(), mon_breakpoint_find_checkpoint(), mon_breakpoint_unset(), and remove_checkpoint().
breakpoint_count
int breakpoint_count static
Referenced by breakpoint_add_checkpoint(), mon_breakpoint_delete_checkpoint(), mon_breakpoint_init(), mon_breakpoint_print_checkpoints(), and mon_breakpoint_switch_checkpoint().
breakpoints
checkpoint_list_t* breakpoints[e_invalid_space] static
Referenced by breakpoint_add_checkpoint(), mon_breakpoint_check_checkpoint(), mon_breakpoint_disable(), mon_breakpoint_enable(), mon_breakpoint_is(), mon_breakpoint_set(), mon_breakpoint_unset(), remove_checkpoint(), and update_checkpoint_state().
watchpoints_load
checkpoint_list_t* watchpoints_load[e_invalid_space] static
Referenced by breakpoint_add_checkpoint(), mon_breakpoint_check_checkpoint(), remove_checkpoint(), and update_checkpoint_state().
watchpoints_store
checkpoint_list_t* watchpoints_store[e_invalid_space] static
Referenced by breakpoint_add_checkpoint(), mon_breakpoint_check_checkpoint(), remove_checkpoint(), and update_checkpoint_state().