vsid: arch/gtk3/widgets/petvideosizewidget.c File Reference
petvideosizewidget.c File Reference
Widget to set the PET video size.
#include "vice.h"
#include <gtk/gtk.h>
#include "basewidgets.h"
#include "widgethelpers.h"
#include "debug_gtk3.h"
#include "resources.h"
#include "petvideosizewidget.h"
Functions
static void video_size_callback (GtkWidget *widget, int size)
Handler for the 'toggled' event of the radio buttons.
GtkWidget * pet_video_size_widget_create (void)
Create PET video size widget.
void pet_video_size_widget_set_callback (void(*func)(int))
Set user-defined callback to be triggered when the widget changes.
void pet_video_size_widget_sync (GtkWidget *widget)
Synchronize widget with its current resource value.
Variables
static const vice_gtk3_radiogroup_entry_t video_sizes []
Data for the radio buttons group.
static void(* user_callback)(int) = NULL
User-defined extra callback.
Detailed Description
Widget to set the PET video size.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
pet_video_size_widget_create()
GtkWidget * pet_video_size_widget_create (void)
Create PET video size widget.
Creates a widget to control the PET's video display number of columns
Returns
GtkGrid
Referenced by create_pet_layout().
pet_video_size_widget_set_callback()
void pet_video_size_widget_set_callback (void(*)(int) func)
Set user-defined callback to be triggered when the widget changes.
Parameters
[in] func user-defined callback
Referenced by create_pet_layout().
pet_video_size_widget_sync()
void pet_video_size_widget_sync (GtkWidget * widget)
Synchronize widget with its current resource value.
Parameters
[in,out] widget PET video size widget
Referenced by machine_model_handler_pet().
video_size_callback()
static void video_size_callback (GtkWidget * widget, int size) static
Handler for the 'toggled' event of the radio buttons.
Sets the VideoSize resource when it has been changed.
Parameters
[in] widget radio button triggering the event (unused)
[in] size value for the resource (int)
Referenced by pet_video_size_widget_create().
Variable Documentation
user_callback
void(* user_callback) (int) (int) = NULL static
User-defined extra callback.
Referenced by pet_video_size_widget_set_callback(), and video_size_callback().
video_sizes
const vice_gtk3_radiogroup_entry_t video_sizes[] static
Initial value:
= {
    { "Auto (from ROM)",  0 },
    { "40 Columns",      40 },
    { "80 Columns",      80 },
    { NULL,              -1 }
}
Data for the radio buttons group.
Referenced by pet_video_size_widget_create().