vsid: monitor/mon_memmap.c File Reference
mon_memmap.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "mon_disassemble.h"
#include "mon_memmap.h"
#include "monitor.h"
#include "montypes.h"
#include "screenshot.h"
#include "types.h"
Functions
static void mon_memmap_stub (void)
stubs
void mon_cpuhistory (int count, MEMSPACE filter1, MEMSPACE filter2, MEMSPACE filter3, MEMSPACE filter4, MEMSPACE filter5)
void mon_memmap_zap (void)
void mon_memmap_show (int mask, MON_ADDR start_addr, MON_ADDR end_addr)
void mon_memmap_save (const char *filename, int format)
void mon_memmap_init (void)
void mon_memmap_shutdown (void)
Variables
uint8_t memmap_state = 0
Globals.
Function Documentation
mon_cpuhistory()
void mon_cpuhistory (int count, MEMSPACE filter1, MEMSPACE filter2, MEMSPACE filter3, MEMSPACE filter4, MEMSPACE filter5)
mon_memmap_init()
void mon_memmap_init (void)
Referenced by monitor_init().
mon_memmap_save()
void mon_memmap_save (const char * filename, int format)
mon_memmap_show()
void mon_memmap_show (int mask, MON_ADDR start_addr, MON_ADDR end_addr)
mon_memmap_shutdown()
void mon_memmap_shutdown (void)
Referenced by monitor_shutdown().
mon_memmap_stub()
static void mon_memmap_stub (void) static
stubs
Referenced by mon_cpuhistory(), mon_memmap_save(), mon_memmap_show(), and mon_memmap_zap().
mon_memmap_zap()
void mon_memmap_zap (void)
Variable Documentation
memmap_state
uint8_t memmap_state = 0
Globals.
HACK to enable fetch/load separation.
Referenced by monitor_close(), monitor_open(), zero_read(), and zero_read_dma().