x128: arch/shared/archdep_program_name.c File Reference
archdep_program_name.c File Reference
Retrieve name of currently running binary.
#include "vice.h"
#include "archdep_defs.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lib.h"
#include "log.h"
#include <unistd.h>
#include "archdep_exit.h"
#include "archdep_program_path.h"
#include "archdep_program_name.h"
Functions
static char * prg_name_unix (const char *buf)
Helper function for Unix-ish systems.
const char * archdep_program_name (void)
Get name of the currently running binary.
void archdep_program_name_free (void)
Free program name.
Variables
static char * program_name = NULL
for readlink(2)
Detailed Description
Retrieve name of currently running binary.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Get name of running executable, stripping path and extension (if present).
OS support:
Linux
Windows
MacOS
BeOS/Haiku
Function Documentation
archdep_program_name()
const char * archdep_program_name (void)
Get name of the currently running binary.
Get the name of the running binary, striped from path and extension.
Returns
program name
Note
Use archdep_program_name_free on emulator shutdown to free memory.
Referenced by archdep_init(), cmdline_version(), and main_program().
archdep_program_name_free()
void archdep_program_name_free (void)
Free program name.
This function must be called on emulator shutdown to free the program name.
Referenced by archdep_shutdown(), and main_program().
prg_name_unix()
static char * prg_name_unix (const char * buf) static
Helper function for Unix-ish systems.
Parameters
[in] buf string to parse binary name from
Returns
binary name
Note
free after use with lib_free().
Referenced by archdep_program_name().
Variable Documentation
program_name
char* program_name = NULL static
for readlink(2)
for GetModuleFileName()
Program name
Heap allocated on the first call to archdep_program_name(), must be freed with archdep_program_name_free() on emulator shutdown.
Referenced by archdep_program_name(), archdep_program_name_free(), autostart_autodetect(), autostart_disk(), autostart_tape(), main_program(), and reboot_for_autostart().