vsid: monitor/mon_command.c File Reference
mon_command.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include "console.h"
#include "lib.h"
#include "mon_command.h"
#include "asm.h"
#include "montypes.h"
#include "mon_parse.h"
#include "mon_util.h"
#include "uimon.h"
#include "util.h"
Data Structures
struct mon_cmds_s
Macros
#define NO_FILENAME_ARG 0
#define FILENAME_ARG 1
Typedefs
typedef struct mon_cmds_s mon_cmds_t
Functions
int mon_get_nth_command (int index, char **full_name, char **short_name, int *takes_filename_as_arg)
static int mon_command_lookup_index (const char *str)
void mon_out_wordwrap (const char *text)
static void print_help_details (const char *cmd, int cmd_num)
static void print_help_topics (const char *filter)
void mon_command_print_help (const char *cmd)
Variables
static const mon_cmds_t mon_cmd_array []
Macro Definition Documentation
FILENAME_ARG
#define FILENAME_ARG 1
NO_FILENAME_ARG
#define NO_FILENAME_ARG 0
Typedef Documentation
mon_cmds_t
typedef struct mon_cmds_s mon_cmds_t
Todo:
FIXME: Removing const from str and abbrev fixes this warning: ../../../../vice/src/arch/gtk3/uimon.c: In function 'console_init': ../../../../vice/src/arch/gtk3/uimon.c:710:17: warning: to be safe all intermediate pointers in cast from 'char **' to 'const char **' must be 'const' qualified [-Wcast-qual (const char **)&full_name,
Also had to do some additional hacking, would be nice to see a better solution. See r36839.
Function Documentation
mon_command_lookup_index()
static int mon_command_lookup_index (const char * str) static
Referenced by mon_command_print_help().
mon_command_print_help()
void mon_command_print_help (const char * cmd)
mon_get_nth_command()
int mon_get_nth_command (int index, char ** full_name, char ** short_name, int * takes_filename_as_arg)
Referenced by console_init().
mon_out_wordwrap()
void mon_out_wordwrap (const char * text)
Todo:
FIXME: we should support some kind of token for marking suggested syllables
Todo:
FIXME: this should really be handled by the UI instead, ie the UI should always just give us valid numbers
Referenced by print_help_details().
print_help_details()
static void print_help_details (const char * cmd, int cmd_num) static
Referenced by mon_command_print_help(), and print_help_topics().
print_help_topics()
static void print_help_topics (const char * filter) static
Todo:
FIXME: this should really be handled by the UI instead, ie the UI should always just give us valid numbers
Referenced by mon_command_print_help().
Variable Documentation
mon_cmd_array
const mon_cmds_t mon_cmd_array[] static
Referenced by mon_command_lookup_index(), mon_get_nth_command(), print_help_details(), and print_help_topics().