vsid: vicii/vicii-fetch.c File Reference
vicii-fetch.c File Reference
#include "vice.h"
#include <string.h>
#include "alarm.h"
#include "debug.h"
#include "c64cart.h"
#include "c64cartmem.h"
#include "dma.h"
#include "log.h"
#include "maincpu.h"
#include "mem.h"
#include "raster-changes.h"
#include "raster-sprite-status.h"
#include "raster-sprite.h"
#include "raster.h"
#include "types.h"
#include "vicii-fetch.h"
#include "vicii-irq.h"
#include "vicii-sprites.h"
#include "viciitypes.h"
Functions
void vicii_fetch_matrix (int offs, int num, int num_0xff, int cycle)
static int do_matrix_fetch (CLOCK sub)
static int handle_fetch_matrix (long offset, CLOCK sub, CLOCK *write_offset)
static void swap_sprite_data_buffers (void)
static void turn_sprite_dma_on (unsigned int num)
Enable DMA for sprite ‘num’.
static void check_sprite_dma (void)
static int handle_check_sprite_dma (long offset, CLOCK sub)
static int handle_fetch_sprite (long offset, CLOCK sub, CLOCK *write_offset)
void vicii_fetch_alarm_handler (CLOCK offset, void *data)
void vicii_fetch_init (void)
Function Documentation
check_sprite_dma()
static void check_sprite_dma (void) inline static
Referenced by handle_check_sprite_dma().
do_matrix_fetch()
static int do_matrix_fetch (CLOCK sub) inline static
Referenced by handle_fetch_matrix().
handle_check_sprite_dma()
static int handle_check_sprite_dma (long offset, CLOCK sub) inline static
Referenced by vicii_fetch_alarm_handler().
handle_fetch_matrix()
static int handle_fetch_matrix (long offset, CLOCK sub, CLOCK * write_offset) inline static
Referenced by vicii_fetch_alarm_handler().
handle_fetch_sprite()
static int handle_fetch_sprite (long offset, CLOCK sub, CLOCK * write_offset) inline static
Todo:
FIXME: the 3 byte sprite data is instead taken during a Ph1/Ph2/Ph1 sequence. This is of minor interest, though, only for CBM-II...
Referenced by vicii_fetch_alarm_handler().
swap_sprite_data_buffers()
static void swap_sprite_data_buffers (void) inline static
Referenced by handle_check_sprite_dma().
turn_sprite_dma_on()
static void turn_sprite_dma_on (unsigned int num) inline static
Enable DMA for sprite ‘num’.
Referenced by check_sprite_dma().
vicii_fetch_alarm_handler()
void vicii_fetch_alarm_handler (CLOCK offset, void * data)
Referenced by vicii_fetch_init(), vicii_handle_pending_alarms(), and vicii_local_store_vbank().
vicii_fetch_init()
void vicii_fetch_init (void)
Referenced by vicii_init().
vicii_fetch_matrix()
void vicii_fetch_matrix (int offs, int num, int num_0xff, int cycle)
Todo:
FIXME: Crunch table in Multiplexer part of Krestage
Referenced by do_matrix_fetch(), and line_becomes_bad().