vsid: lib/p64/p64.h File Reference
p64.h File Reference
#include "p64config.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
Data Structures
struct TP64Pulse
struct TP64PulseStream
struct TP64Image
struct TP64MemoryStream
Macros
#define P64PulseSamplesPerRotation 3200000
(16 MHz * 60) / 300 = 3200000 samples per track rotation (at 5 rotations per second)
#define P64FirstHalfTrack 2
#define P64LastHalfTrack 85
including 42.5
Typedefs
typedef int8_t p64_int8_t
typedef int16_t p64_int16_t
typedef int32_t p64_int32_t
typedef uint8_t p64_uint8_t
typedef uint16_t p64_uint16_t
typedef uint32_t p64_uint32_t
typedef p64_uint8_t TP64HeaderSignature[8]
typedef TP64HeaderSignature * PP64HeaderSignature
typedef p64_uint8_t TP64ChunkSignature[4]
typedef TP64ChunkSignature * PP64ChunkSignature
typedef TP64Pulse * PP64Pulse
typedef TP64Pulse * PP64Pulses
typedef TP64PulseStream * PP64PulseStream
typedef TP64PulseStream TP64PulseStreams[2][(85 -0)+2]
typedef TP64PulseStreams * PP64PulseStreams
typedef TP64Image * PP64Image
typedef TP64MemoryStream * PP64MemoryStream
Functions
void P64MemoryStreamCreate (PP64MemoryStream Instance)
unused right now (2017-04-17, compyx)
void P64MemoryStreamDestroy (PP64MemoryStream Instance)
void P64MemoryStreamClear (PP64MemoryStream Instance)
p64_uint32_t P64MemoryStreamSeek (PP64MemoryStream Instance, p64_uint32_t Position)
p64_uint32_t P64MemoryStreamRead (PP64MemoryStream Instance, p64_uint8_t *Data, p64_uint32_t Count)
p64_uint32_t P64MemoryStreamWrite (PP64MemoryStream Instance, p64_uint8_t *Data, p64_uint32_t Count)
p64_int32_t P64MemoryStreamReadByte (PP64MemoryStream Instance, p64_uint8_t *Data)
p64_int32_t P64MemoryStreamReadWord (PP64MemoryStream Instance, p64_uint16_t *Data)
p64_int32_t P64MemoryStreamReadDWord (PP64MemoryStream Instance, p64_uint32_t *Data)
p64_int32_t P64MemoryStreamWriteByte (PP64MemoryStream Instance, p64_uint8_t *Data)
p64_int32_t P64MemoryStreamWriteWord (PP64MemoryStream Instance, p64_uint16_t *Data)
p64_int32_t P64MemoryStreamWriteDWord (PP64MemoryStream Instance, p64_uint32_t *Data)
p64_uint32_t P64MemoryStreamAssign (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
p64_uint32_t P64MemoryStreamAppend (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
p64_uint32_t P64MemoryStreamAppendFrom (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
p64_uint32_t P64MemoryStreamAppendFromCount (PP64MemoryStream Instance, PP64MemoryStream FromInstance, p64_uint32_t Count)
void P64PulseStreamCreate (PP64PulseStream Instance)
void P64PulseStreamDestroy (PP64PulseStream Instance)
void P64PulseStreamClear (PP64PulseStream Instance)
p64_int32_t P64PulseStreamAllocatePulse (PP64PulseStream Instance)
void P64PulseStreamFreePulse (PP64PulseStream Instance, p64_int32_t Index)
void P64PulseStreamAddPulse (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Strength)
void P64PulseStreamRemovePulses (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Count)
void P64PulseStreamRemovePulse (PP64PulseStream Instance, p64_uint32_t Position)
p64_uint32_t P64PulseStreamDeltaPositionToNextPulse (PP64PulseStream Instance, p64_uint32_t Position)
p64_uint32_t P64PulseStreamGetNextPulse (PP64PulseStream Instance, p64_uint32_t Position)
p64_uint32_t P64PulseStreamGetPulseCount (PP64PulseStream Instance)
p64_uint32_t P64PulseStreamGetPulse (PP64PulseStream Instance, p64_uint32_t Position)
void P64PulseStreamSetPulse (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Strength)
void P64PulseStreamSeek (PP64PulseStream Instance, p64_uint32_t Position)
void P64PulseStreamConvertFromGCR (PP64PulseStream Instance, p64_uint8_t *Bytes, p64_uint32_t Len)
void P64PulseStreamConvertToGCR (PP64PulseStream Instance, p64_uint8_t *Bytes, p64_uint32_t Len)
p64_uint32_t P64PulseStreamConvertToGCRWithLogic (PP64PulseStream Instance, p64_uint8_t *Bytes, p64_uint32_t Len, p64_uint32_t SpeedZone)
p64_uint32_t P64PulseStreamReadFromStream (PP64PulseStream Instance, PP64MemoryStream Stream)
p64_uint32_t P64PulseStreamWriteToStream (PP64PulseStream Instance, PP64MemoryStream Stream)
void P64ImageCreate (PP64Image Instance)
void P64ImageDestroy (PP64Image Instance)
void P64ImageClear (PP64Image Instance)
p64_uint32_t P64ImageReadFromStream (PP64Image Instance, PP64MemoryStream Stream)
p64_uint32_t P64ImageWriteToStream (PP64Image Instance, PP64MemoryStream Stream)
Macro Definition Documentation
P64FirstHalfTrack
#define P64FirstHalfTrack 2
P64LastHalfTrack
#define P64LastHalfTrack 85
including 42.5
P64PulseSamplesPerRotation
#define P64PulseSamplesPerRotation 3200000
(16 MHz * 60) / 300 = 3200000 samples per track rotation (at 5 rotations per second)
Typedef Documentation
p64_int16_t
typedef int16_t p64_int16_t
p64_int32_t
typedef int32_t p64_int32_t
p64_int8_t
typedef int8_t p64_int8_t
p64_uint16_t
typedef uint16_t p64_uint16_t
p64_uint32_t
typedef uint32_t p64_uint32_t
p64_uint8_t
typedef uint8_t p64_uint8_t
PP64ChunkSignature
typedef TP64ChunkSignature* PP64ChunkSignature
PP64HeaderSignature
typedef TP64HeaderSignature* PP64HeaderSignature
PP64Image
typedef TP64Image* PP64Image
PP64MemoryStream
typedef TP64MemoryStream* PP64MemoryStream
PP64Pulse
typedef TP64Pulse* PP64Pulse
PP64Pulses
typedef TP64Pulse* PP64Pulses
PP64PulseStream
typedef TP64PulseStream* PP64PulseStream
PP64PulseStreams
typedef TP64PulseStreams* PP64PulseStreams
TP64ChunkSignature
typedef p64_uint8_t TP64ChunkSignature[4]
TP64HeaderSignature
typedef p64_uint8_t TP64HeaderSignature[8]
TP64PulseStreams
typedef TP64PulseStream TP64PulseStreams[2][(85 -0)+2]
Function Documentation
P64ImageClear()
void P64ImageClear (PP64Image Instance)
Referenced by P64ImageCreate(), and P64ImageReadFromStream().
P64ImageCreate()
void P64ImageCreate (PP64Image Instance)
Referenced by drive_init(), fsimage_create_p64(), and vdrive_internal_open_fsimage().
P64ImageDestroy()
void P64ImageDestroy (PP64Image Instance)
Referenced by attach_disk_image(), detach_disk_image(), drive_shutdown(), fsimage_create_p64(), vdrive_internal_close_disk_image(), and vdrive_internal_open_fsimage().
P64ImageReadFromStream()
p64_uint32_t P64ImageReadFromStream (PP64Image Instance, PP64MemoryStream Stream)
Referenced by drive_snapshot_read_p64image_module(), and fsimage_read_p64_image().
P64ImageWriteToStream()
p64_uint32_t P64ImageWriteToStream (PP64Image Instance, PP64MemoryStream Stream)
Referenced by drive_snapshot_write_p64image_module(), fsimage_create_p64(), and fsimage_write_p64_image().
P64MemoryStreamAppend()
p64_uint32_t P64MemoryStreamAppend (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
P64MemoryStreamAppendFrom()
p64_uint32_t P64MemoryStreamAppendFrom (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
P64MemoryStreamAppendFromCount()
p64_uint32_t P64MemoryStreamAppendFromCount (PP64MemoryStream Instance, PP64MemoryStream FromInstance, p64_uint32_t Count)
Referenced by P64ImageReadFromStream(), and P64ImageWriteToStream().
P64MemoryStreamAssign()
p64_uint32_t P64MemoryStreamAssign (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
P64MemoryStreamClear()
void P64MemoryStreamClear (PP64MemoryStream Instance)
Referenced by drive_snapshot_read_p64image_module(), drive_snapshot_write_p64image_module(), fsimage_create_p64(), and fsimage_write_p64_image().
P64MemoryStreamCreate()
void P64MemoryStreamCreate (PP64MemoryStream Instance)
unused right now (2017-04-17, compyx)
unused right now (2017-04-17, compyx)
unused right now (2017-04-17, compyx)
Referenced by drive_snapshot_read_p64image_module(), drive_snapshot_write_p64image_module(), fsimage_create_p64(), fsimage_read_p64_image(), fsimage_write_p64_image(), P64ImageReadFromStream(), and P64ImageWriteToStream().
P64MemoryStreamDestroy()
void P64MemoryStreamDestroy (PP64MemoryStream Instance)
Referenced by drive_snapshot_read_p64image_module(), drive_snapshot_write_p64image_module(), fsimage_create_p64(), fsimage_read_p64_image(), fsimage_write_p64_image(), P64ImageReadFromStream(), and P64ImageWriteToStream().
P64MemoryStreamRead()
p64_uint32_t P64MemoryStreamRead (PP64MemoryStream Instance, p64_uint8_t * Data, p64_uint32_t Count)
Referenced by P64ImageReadFromStream(), P64MemoryStreamReadByte(), and P64PulseStreamReadFromStream().
P64MemoryStreamReadByte()
p64_int32_t P64MemoryStreamReadByte (PP64MemoryStream Instance, p64_uint8_t * Data)
Referenced by P64MemoryStreamReadWord().
P64MemoryStreamReadDWord()
p64_int32_t P64MemoryStreamReadDWord (PP64MemoryStream Instance, p64_uint32_t * Data)
Referenced by P64ImageReadFromStream(), and P64PulseStreamReadFromStream().
P64MemoryStreamReadWord()
p64_int32_t P64MemoryStreamReadWord (PP64MemoryStream Instance, p64_uint16_t * Data)
Referenced by P64MemoryStreamReadDWord().
P64MemoryStreamSeek()
p64_uint32_t P64MemoryStreamSeek (PP64MemoryStream Instance, p64_uint32_t Position)
Referenced by drive_snapshot_read_p64image_module(), fsimage_read_p64_image(), P64ImageReadFromStream(), and P64ImageWriteToStream().
P64MemoryStreamWrite()
p64_uint32_t P64MemoryStreamWrite (PP64MemoryStream Instance, p64_uint8_t * Data, p64_uint32_t Count)
Referenced by drive_snapshot_read_p64image_module(), fsimage_read_p64_image(), P64ImageWriteToStream(), P64MemoryStreamAppend(), P64MemoryStreamAppendFrom(), P64MemoryStreamAppendFromCount(), P64MemoryStreamWriteByte(), and P64PulseStreamWriteToStream().
P64MemoryStreamWriteByte()
p64_int32_t P64MemoryStreamWriteByte (PP64MemoryStream Instance, p64_uint8_t * Data)
Referenced by P64MemoryStreamWriteWord().
P64MemoryStreamWriteDWord()
p64_int32_t P64MemoryStreamWriteDWord (PP64MemoryStream Instance, p64_uint32_t * Data)
Referenced by P64ImageWriteToStream(), and P64PulseStreamWriteToStream().
P64MemoryStreamWriteWord()
p64_int32_t P64MemoryStreamWriteWord (PP64MemoryStream Instance, p64_uint16_t * Data)
Referenced by P64MemoryStreamWriteDWord().
P64PulseStreamAddPulse()
void P64PulseStreamAddPulse (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Strength)
Referenced by P64PulseStreamConvertFromGCR(), P64PulseStreamReadFromStream(), P64PulseStreamSetPulse(), and rotation_1541_p64().
P64PulseStreamAllocatePulse()
p64_int32_t P64PulseStreamAllocatePulse (PP64PulseStream Instance)
Referenced by P64PulseStreamAddPulse().
P64PulseStreamClear()
void P64PulseStreamClear (PP64PulseStream Instance)
Referenced by P64ImageClear(), P64PulseStreamConvertFromGCR(), and P64PulseStreamDestroy().
P64PulseStreamConvertFromGCR()
void P64PulseStreamConvertFromGCR (PP64PulseStream Instance, p64_uint8_t * Bytes, p64_uint32_t Len)
Referenced by fsimage_create_p64(), fsimage_p64_write_half_track(), and fsimage_p64_write_track().
P64PulseStreamConvertToGCR()
void P64PulseStreamConvertToGCR (PP64PulseStream Instance, p64_uint8_t * Bytes, p64_uint32_t Len)
P64PulseStreamConvertToGCRWithLogic()
p64_uint32_t P64PulseStreamConvertToGCRWithLogic (PP64PulseStream Instance, p64_uint8_t * Bytes, p64_uint32_t Len, p64_uint32_t SpeedZone)
Referenced by fsimage_p64_read_half_track().
P64PulseStreamCreate()
void P64PulseStreamCreate (PP64PulseStream Instance)
Referenced by P64ImageCreate().
P64PulseStreamDeltaPositionToNextPulse()
p64_uint32_t P64PulseStreamDeltaPositionToNextPulse (PP64PulseStream Instance, p64_uint32_t Position)
P64PulseStreamDestroy()
void P64PulseStreamDestroy (PP64PulseStream Instance)
Referenced by P64ImageDestroy().
P64PulseStreamFreePulse()
void P64PulseStreamFreePulse (PP64PulseStream Instance, p64_int32_t Index)
Referenced by P64PulseStreamRemovePulse(), P64PulseStreamRemovePulses(), and rotation_1541_p64().
P64PulseStreamGetNextPulse()
p64_uint32_t P64PulseStreamGetNextPulse (PP64PulseStream Instance, p64_uint32_t Position)
P64PulseStreamGetPulse()
p64_uint32_t P64PulseStreamGetPulse (PP64PulseStream Instance, p64_uint32_t Position)
P64PulseStreamGetPulseCount()
p64_uint32_t P64PulseStreamGetPulseCount (PP64PulseStream Instance)
P64PulseStreamReadFromStream()
p64_uint32_t P64PulseStreamReadFromStream (PP64PulseStream Instance, PP64MemoryStream Stream)
Referenced by P64ImageReadFromStream().
P64PulseStreamRemovePulse()
void P64PulseStreamRemovePulse (PP64PulseStream Instance, p64_uint32_t Position)
Referenced by P64PulseStreamSetPulse().
P64PulseStreamRemovePulses()
void P64PulseStreamRemovePulses (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Count)
P64PulseStreamSeek()
void P64PulseStreamSeek (PP64PulseStream Instance, p64_uint32_t Position)
P64PulseStreamSetPulse()
void P64PulseStreamSetPulse (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Strength)
P64PulseStreamWriteToStream()
p64_uint32_t P64PulseStreamWriteToStream (PP64PulseStream Instance, PP64MemoryStream Stream)
Referenced by P64ImageWriteToStream().