vsid: monitor/monitor_binary.h File Reference
monitor_binary.h File Reference
Monitor implementation - binary network access.
#include "types.h"
#include "uiapi.h"
#include "mon_breakpoint.h"
#include "vicesocket.h"
Functions
int monitor_binary_resources_init (void)
initialize the binary monitor resources
void monitor_binary_resources_shutdown (void)
uninitialize the network monitor resources
int monitor_binary_cmdline_options_init (void)
initialize the command-line options'
void monitor_binary_response_checkpoint_info (uint32_t request_id, mon_checkpoint_t *checkpt, bool hit)
Responds with information about a checkpoint.
void monitor_binary_event_opened (void)
called when the monitor is opened
void monitor_binary_event_closed (void)
called when the monitor is closed
void monitor_check_binary (void)
int monitor_binary_receive (unsigned char *buffer, size_t buffer_length)
int monitor_binary_transmit (const unsigned char *buffer, size_t buffer_length)
int monitor_binary_get_command_line (void)
int monitor_is_binary (void)
vice_network_socket_t * monitor_binary_get_connected_socket (void)
ui_jam_action_t monitor_binary_ui_jam_dialog (const char *format,...)
Detailed Description
Monitor implementation - binary network access.
Author
EmpathicQubit empat.nosp@m.hicq.nosp@m.ubit@.nosp@m.enta.nosp@m.n.gl
Function Documentation
monitor_binary_cmdline_options_init()
int monitor_binary_cmdline_options_init (void)
initialize the command-line options'
Returns
0 on success, else -1.
Remarks
Registers the command-line options
Referenced by init_cmdline_options().
monitor_binary_event_closed()
void monitor_binary_event_closed (void)
called when the monitor is closed
Referenced by mon_event_closed().
monitor_binary_event_opened()
void monitor_binary_event_opened (void)
called when the monitor is opened
Referenced by mon_event_opened().
monitor_binary_get_command_line()
int monitor_binary_get_command_line (void)
Referenced by uimon_in().
monitor_binary_get_connected_socket()
vice_network_socket_t * monitor_binary_get_connected_socket (void)
Referenced by uimon_in().
monitor_binary_receive()
int monitor_binary_receive (unsigned char * buffer, size_t buffer_length)
Referenced by monitor_binary_get_command_line().
monitor_binary_resources_init()
int monitor_binary_resources_init (void)
initialize the binary monitor resources
Returns
0 on success, else -1.
Remarks
Registers the string and the integer resources
Referenced by init_resources().
monitor_binary_resources_shutdown()
void monitor_binary_resources_shutdown (void)
uninitialize the network monitor resources
Referenced by cmdline_help(), and machine_shutdown().
monitor_binary_response_checkpoint_info()
void monitor_binary_response_checkpoint_info (uint32_t request_id, mon_checkpoint_t * checkpt, bool hit)
Responds with information about a checkpoint.
Parameters
request_id ID of the request
mon_checkpoint_t The checkpoint
hit Is the checkpoint hit in the emulator?
Referenced by mon_breakpoint_event(), monitor_binary_process_checkpoint_get(), monitor_binary_process_checkpoint_list(), and monitor_binary_process_checkpoint_set().
monitor_binary_transmit()
int monitor_binary_transmit (const unsigned char * buffer, size_t buffer_length)
Referenced by monitor_binary_response().
monitor_binary_ui_jam_dialog()
ui_jam_action_t monitor_binary_ui_jam_dialog (const char * format, ...)
Referenced by drive_jam(), and machine_jam().
monitor_check_binary()
void monitor_check_binary (void)
Referenced by monitor_vsync_hook(), and uimon_in().
monitor_is_binary()
int monitor_is_binary (void)
Referenced by drive_jam(), machine_jam(), mon_breakpoint_event(), mon_event_closed(), mon_event_opened(), monitor_close(), monitor_open(), and uimon_in().