vsid: arch/gtk3/widgets/sidmodelwidget.h File Reference
sidmodelwidget.h File Reference
Widget to set the SID model - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
GtkWidget * sid_model_widget_create (GtkWidget *machine_model_widget)
Create SID model widget.
void sid_model_widget_update (GtkWidget *widget, int model)
Update the SID model widget.
void sid_model_widget_sync (GtkWidget *widget)
Synchronize the widget with its resource.
void sid_model_widget_set_callback (GtkWidget *widget, void(*callback)(int))
Set extra callback to trigger when the model changes.
Detailed Description
Widget to set the SID model - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
sid_model_widget_create()
GtkWidget * sid_model_widget_create (GtkWidget * machine_model_widget)
Create SID model widget.
Creates a SID model widget, depending on machine_class. Also sets a callback to force an update of the 'machine model' widget.
Parameters
[in,out] machine_model_widget reference to machine model widget
Returns
GtkGrid
Referenced by create_c128_layout(), create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), create_vsid_layout(), and settings_sidcart_widget_create().
sid_model_widget_set_callback()
void sid_model_widget_set_callback (GtkWidget * widget, void(*)(int) callback)
Set extra callback to trigger when the model changes.
Parameters
[in] widget the SID model widget
[in] callback function to call on model change
Referenced by create_c128_layout(), create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), and create_cbm6x0_layout().
sid_model_widget_sync()
void sid_model_widget_sync (GtkWidget * widget)
Synchronize the widget with its resource.
Parameters
[in,out] widget SID model widget
sid_model_widget_update()
void sid_model_widget_update (GtkWidget * widget, int model)
Update the SID model widget.
Parameters
[in,out] widget SID model widget
[in] model SID model ID
Referenced by sid_model_widget_sync().