vsid: arch/gtk3/vsidstate.h File Reference
vsidstate.h File Reference
VSID UI state module - header.
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
Data Structures
struct vsid_state_s
VSID UI state object.
Typedefs
typedef struct vsid_state_s vsid_state_t
VSID UI state object.
Functions
vsid_state_t * vsid_state_lock (void)
Get the lock on the VSID state.
void vsid_state_unlock (void)
Unlock the VSID state.
void vsid_state_init (void)
Initialize UI state object.
void vsid_state_shutdown (void)
Clean up any resources used by the VSID state object.
void vsid_state_set_tune_played (int tune)
Set subtune played flag.
void vsid_state_set_current_tune_played (void)
Mark current tune as played.
bool vsid_state_get_tune_played (int tune)
Determine if a subtune has been played.
void vsid_state_unset_tune_played (int tune)
Clear subtune played flag.
void vsid_state_clear_tunes_played (void)
Clear all subtunes' played flags.
void vsid_state_print_tunes_played (void)
Debug helper: print tunes played bitmap on stdout.
void vsid_state_get_tunes_played_bitmap (uint8_t *bitmap)
Get bitmap of tunes played.
bool vsid_state_get_all_tunes_played (void)
Determine if all subtunes have been played.
void vsid_state_set_tune_played_unlocked (int tune)
Here be dragons: only use when having obtained the lock first!
void vsid_state_set_current_tune_played_unlocked (void)
Mark current tune as played without obtaining the lock.
void vsid_state_print_tunes_played_unlocked (void)
Debug helper: print tunes_played bitmap on stdout.
Detailed Description
VSID UI state module - header.
This module is a central place to keep track of the state of the VSID UI and handle communication between the VICE thread and the UI thread.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Typedef Documentation
vsid_state_t
typedef struct vsid_state_s vsid_state_t
VSID UI state object.
Used to handle communication between the main (VICE) thread and the UI thread.
The _pending flags indicate a new value has arrived for a widget. There are no flags for string values since non-NULL means a new value has arrived, and no flag for the play time update, since we keep track of the old time to avoid rendering the related widgets (play time/progress bar) again for the same time.
Function Documentation
vsid_state_clear_tunes_played()
void vsid_state_clear_tunes_played (void)
Clear all subtunes' played flags.
vsid_state_get_all_tunes_played()
bool vsid_state_get_all_tunes_played (void)
Determine if all subtunes have been played.
Returns
true if all subtunes have been played
Referenced by vsid_tune_info_widget_update().
vsid_state_get_tune_played()
bool vsid_state_get_tune_played (int tune)
Determine if a subtune has been played.
Parameters
[in] tune subtune number (1-255)
Returns
true if subtune has been played
Note
returns false when tune is out of range
vsid_state_get_tunes_played_bitmap()
void vsid_state_get_tunes_played_bitmap (uint8_t * bitmap)
Get bitmap of tunes played.
Parameters
[out] bitmap buffer to store bitmap, must be (at least) 8 bytes
vsid_state_init()
void vsid_state_init (void)
Initialize UI state object.
Referenced by ui_vsid_window_init().
vsid_state_lock()
vsid_state_t * vsid_state_lock (void)
Get the lock on the VSID state.
Returns
VSID state reference
Referenced by play_current_tune(), play_subtune(), psid_play_action(), psid_stop_action(), psid_subtune_next_action(), psid_subtune_previous_action(), ui_vsid_window_load_psid(), vsid_control_widget_set_tune_count(), vsid_control_widget_set_tune_current(), vsid_control_widget_set_tune_default(), vsid_state_clear_tunes_played(), vsid_state_get_all_tunes_played(), vsid_state_get_tune_played(), vsid_state_get_tunes_played_bitmap(), vsid_state_print_tunes_played(), vsid_state_set_current_tune_played(), vsid_state_set_tune_played(), vsid_state_shutdown(), vsid_state_unset_tune_played(), vsid_ui_display_author(), vsid_ui_display_copyright(), vsid_ui_display_irqtype(), vsid_ui_display_name(), vsid_ui_display_nr_of_tunes(), vsid_ui_display_sid_model(), vsid_ui_display_sync(), vsid_ui_display_time(), vsid_ui_display_tune_nr(), vsid_ui_set_data_size(), vsid_ui_set_default_tune(), vsid_ui_set_driver_addr(), vsid_ui_set_init_addr(), vsid_ui_set_load_addr(), vsid_ui_set_play_addr(), and vsid_ui_update().
vsid_state_print_tunes_played()
void vsid_state_print_tunes_played (void)
Debug helper: print tunes played bitmap on stdout.
Referenced by ui_vsid_window_load_psid(), and vsid_tune_info_widget_update().
vsid_state_print_tunes_played_unlocked()
void vsid_state_print_tunes_played_unlocked (void)
Debug helper: print tunes_played bitmap on stdout.
Careful! Direct access to state which assumes the caller locks and unlocks!
Referenced by play_subtune(), psid_subtune_next_action(), and vsid_state_print_tunes_played().
vsid_state_set_current_tune_played()
void vsid_state_set_current_tune_played (void)
Mark current tune as played.
Referenced by vsid_tune_info_widget_update().
vsid_state_set_current_tune_played_unlocked()
void vsid_state_set_current_tune_played_unlocked (void)
Mark current tune as played without obtaining the lock.
Make sure to have obtained the lock manually before using!
Referenced by vsid_state_set_current_tune_played().
vsid_state_set_tune_played()
void vsid_state_set_tune_played (int tune)
Set subtune played flag.
Parameters
[in] tune tune number (1-255)
vsid_state_set_tune_played_unlocked()
void vsid_state_set_tune_played_unlocked (int tune)
Here be dragons: only use when having obtained the lock first!
Here be dragons: only use when having obtained the lock first!
Here be dragons: only call this when having manually obtained the lock!
Parameters
[in] tune subtune number
Referenced by play_subtune(), and vsid_state_set_tune_played().
vsid_state_shutdown()
void vsid_state_shutdown (void)
Clean up any resources used by the VSID state object.
Referenced by on_widget_unrealized().
vsid_state_unlock()
void vsid_state_unlock (void)
Unlock the VSID state.
Referenced by play_current_tune(), play_subtune(), psid_play_action(), psid_stop_action(), psid_subtune_next_action(), psid_subtune_previous_action(), ui_vsid_window_load_psid(), vsid_control_widget_set_tune_count(), vsid_control_widget_set_tune_current(), vsid_control_widget_set_tune_default(), vsid_state_clear_tunes_played(), vsid_state_get_all_tunes_played(), vsid_state_get_tune_played(), vsid_state_get_tunes_played_bitmap(), vsid_state_print_tunes_played(), vsid_state_set_current_tune_played(), vsid_state_set_tune_played(), vsid_state_shutdown(), vsid_state_unset_tune_played(), vsid_ui_display_author(), vsid_ui_display_copyright(), vsid_ui_display_irqtype(), vsid_ui_display_name(), vsid_ui_display_nr_of_tunes(), vsid_ui_display_sid_model(), vsid_ui_display_sync(), vsid_ui_display_time(), vsid_ui_display_tune_nr(), vsid_ui_set_data_size(), vsid_ui_set_default_tune(), vsid_ui_set_driver_addr(), vsid_ui_set_init_addr(), vsid_ui_set_load_addr(), vsid_ui_set_play_addr(), and vsid_ui_update().
vsid_state_unset_tune_played()
void vsid_state_unset_tune_played (int tune)
Clear subtune played flag.
Parameters
[in] tune tune number (1-255)