x128: drive/ieee/fdc.c File Reference
fdc.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "alarm.h"
#include "attach.h"
#include "diskimage.h"
#include "drive-check.h"
#include "drive.h"
#include "drivetypes.h"
#include "fdc.h"
#include "lib.h"
#include "log.h"
#include "snapshot.h"
#include "types.h"
Data Structures
struct fdc_t
Macros
#define DOS_IS_90(type) (type == DRIVE_TYPE_9000)
#define DOS_IS_80(type) (type == DRIVE_TYPE_8050 || type == DRIVE_TYPE_8250 || type == DRIVE_TYPE_1001)
#define DOS_IS_40(type) (type == DRIVE_TYPE_4040)
#define DOS_IS_30(type) (type == DRIVE_TYPE_3040)
#define DOS_IS_20(type) (type == DRIVE_TYPE_2040)
#define NUM_FDC NUM_DISK_UNITS
dual disk drives
#define SNAP_MAJOR 0
#define SNAP_MINOR 0
Typedefs
typedef struct fdc_t fdc_t
Functions
void fdc_reset (unsigned int fnum, unsigned int drive_type)
static uint8_t fdc_do_format_D20 (unsigned int fnum, unsigned int dnr, unsigned int track, unsigned int sector, int buf, uint8_t *header)
static uint8_t fdc_do_format_D40 (unsigned int fnum, unsigned int dnr, unsigned int track, unsigned int sector, int buf, uint8_t *header)
static uint8_t fdc_do_format_D80 (unsigned int fnum, unsigned int dnr, unsigned int track, unsigned int sector, int buf, uint8_t *header)
static uint8_t fdc_do_format_D90 (unsigned int fnum, unsigned int dnr, unsigned int track, unsigned int sector, int buf, uint8_t *header)
static uint8_t fdc_do_job (unsigned int fnum, int buf, unsigned int drv, uint8_t job, uint8_t *header)
static void int_fdc (CLOCK offset, void *data)
void fdc_init (diskunit_context_t *drv)
int fdc_attach_image (disk_image_t *image, unsigned int unit, unsigned int drive)
int fdc_detach_image (disk_image_t *image, unsigned int unit, unsigned int drive)
int fdc_snapshot_write_module (snapshot_t *p, int fnum)
int fdc_snapshot_read_module (snapshot_t *p, int fnum)
Variables
static log_t fdc_log = ((log_t)-1)
static fdc_t fdc [4][2]
Macro Definition Documentation
DOS_IS_20
#define DOS_IS_20 (type) (type == DRIVE_TYPE_2040)
DOS_IS_30
#define DOS_IS_30 (type) (type == DRIVE_TYPE_3040)
DOS_IS_40
#define DOS_IS_40 (type) (type == DRIVE_TYPE_4040)
DOS_IS_80
#define DOS_IS_80 (type) (type == DRIVE_TYPE_8050 || type == DRIVE_TYPE_8250 || type == DRIVE_TYPE_1001)
DOS_IS_90
#define DOS_IS_90 (type) (type == DRIVE_TYPE_9000)
NUM_FDC
#define NUM_FDC NUM_DISK_UNITS
dual disk drives
SNAP_MAJOR
#define SNAP_MAJOR 0
SNAP_MINOR
#define SNAP_MINOR 0
Typedef Documentation
fdc_t
typedef struct fdc_t fdc_t
Function Documentation
fdc_attach_image()
int fdc_attach_image (disk_image_t * image, unsigned int unit, unsigned int drive)
Todo:
FIXME: hack - we need to save the image to be able to re-attach when the disk drive type changes, in particular from the initial DRIVE_TYPE_NONE to a proper drive.
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 3.0 hard drive
< D9090/D9060
Referenced by fdc_reset(), and ieee_drive_image_attach().
fdc_detach_image()
int fdc_detach_image (disk_image_t * image, unsigned int unit, unsigned int drive)
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 3.0 hard drive
< D9090/D9060
Referenced by fdc_reset(), and ieee_drive_image_detach().
fdc_do_format_D20()
static uint8_t fdc_do_format_D20 (unsigned int fnum, unsigned int dnr, unsigned int track, unsigned int sector, int buf, uint8_t * header) static
fdc_do_format_D40()
static uint8_t fdc_do_format_D40 (unsigned int fnum, unsigned int dnr, unsigned int track, unsigned int sector, int buf, uint8_t * header) static
fdc_do_format_D80()
static uint8_t fdc_do_format_D80 (unsigned int fnum, unsigned int dnr, unsigned int track, unsigned int sector, int buf, uint8_t * header) static
fdc_do_format_D90()
static uint8_t fdc_do_format_D90 (unsigned int fnum, unsigned int dnr, unsigned int track, unsigned int sector, int buf, uint8_t * header) static
fdc_do_job()
static uint8_t fdc_do_job (unsigned int fnum, int buf, unsigned int drv, uint8_t job, uint8_t * header) static
< DOS 3.0 hard drive
< DOS 3.0 hard drive
< DOS 3.0 hard drive
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 3.0 hard drive
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 1 dual floppy drive, 170k/disk
< DOS 3.0 hard drive
Referenced by int_fdc().
fdc_init()
void fdc_init (diskunit_context_t * drv)
Todo:
FIXME: hack, because 0x4000 is only ok for 1001/8050/8250. fdc.c:fdc_do_job() adds an offset for 2040/3040/4040 by itself :-(Why donlly get a table for that...!
Referenced by ieee_drive_init().
fdc_reset()
void fdc_reset (unsigned int fnum, unsigned int drive_type)
Referenced by ieee_drive_reset().
fdc_snapshot_read_module()
int fdc_snapshot_read_module (snapshot_t * p, int fnum)
Todo:
drive 1
Referenced by ieee_drive_snapshot_read().
fdc_snapshot_write_module()
int fdc_snapshot_write_module (snapshot_t * p, int fnum)
Todo:
drive 1
Referenced by ieee_drive_snapshot_write().
int_fdc()
static void int_fdc (CLOCK offset, void * data) static
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 3.0 hard drive
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 3.0 hard drive
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 3.0 hard drive
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 3.0 hard drive
< DOS 3.0 hard drive
Referenced by fdc_init().
Variable Documentation
fdc
fdc_t fdc[ 4][2] static
Referenced by fdc_attach_image(), fdc_detach_image(), fdc_do_format_D20(), fdc_do_format_D40(), fdc_do_format_D80(), fdc_do_format_D90(), fdc_init(), fdc_reset(), fdc_snapshot_read_module(), fdc_snapshot_write_module(), and int_fdc().
fdc_log
log_t fdc_log = ((log_t)-1) static
Referenced by fdc_attach_image(), fdc_detach_image(), fdc_do_format_D20(), fdc_do_format_D40(), fdc_do_format_D80(), fdc_do_format_D90(), fdc_do_job(), fdc_init(), fdc_reset(), fdc_snapshot_read_module(), and int_fdc().