vsid: serial/serial-iec-device.h File Reference
serial-iec-device.h File Reference
Functions
int serial_iec_device_resources_init (void)
int serial_iec_device_cmdline_options_init (void)
void serial_iec_device_init (void)
void serial_iec_device_reset (void)
Function Documentation
serial_iec_device_cmdline_options_init()
int serial_iec_device_cmdline_options_init (void)
Todo:
FIXME: xvic does not use the generic iec code in src/iecbus/iecbus.c, which makes iecdevice not work
Referenced by serial_cmdline_options_init().
serial_iec_device_init()
void serial_iec_device_init (void)
Referenced by serial_trap_init().
serial_iec_device_reset()
void serial_iec_device_reset (void)
Referenced by serial_traps_reset().
serial_iec_device_resources_init()
int serial_iec_device_resources_init (void)
Todo:
FIXME: xvic does not use the generic iec code in src/iecbus/iecbus.c, which makes iecdevice not work
Referenced by serial_resources_init().