vsid: arch/gtk3/widgets/videomodelwidget.c File Reference
videomodelwidget.c File Reference
Video chip model selection widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "resources.h"
#include "machine.h"
#include "log.h"
#include "videomodelwidget.h"
Functions
static int get_model_index (int model)
Get index in model list for model-ID model.
static void on_model_toggled (GtkWidget *widget, gpointer user_data)
Handler for the "toggled" event of the model radio buttons.
void video_model_widget_set_title (const char *title)
Set title of the widget.
void video_model_widget_set_resource (const char *resource)
Set resource name of the widget.
void video_model_widget_set_models (const vice_gtk3_radiogroup_entry_t *models)
Set list of valid models for the widget.
GtkWidget * video_model_widget_create (GtkWidget *machine)
Create widget to control video model.
void video_model_widget_update (GtkWidget *widget)
Update the video model widget.
void video_model_widget_connect_signals (GtkWidget *widget)
Setup signal handlers of the video model widget.
void video_model_widget_set_callback (GtkWidget *widget, void(*callback)(int))
Set extra callback to trigger when the model changes.
Variables
static const char * widget_title = NULL
Title for the widget.
static const char * resource_name = NULL
Name of the video model resource.
static const vice_gtk3_radiogroup_entry_t * model_list = NULL
List of video models.
Detailed Description
Video chip model selection widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
get_model_index()
static int get_model_index (int model) static
Get index in model list for model-ID model.
Parameters
[in] model model index
Returns
index in list or -1 when not found
Referenced by video_model_widget_update().
on_model_toggled()
static void on_model_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the "toggled" event of the model radio buttons.
Parameters
[in] widget radio button
[in] user_data model ID (int
Referenced by video_model_widget_connect_signals().
video_model_widget_connect_signals()
void video_model_widget_connect_signals (GtkWidget * widget)
Setup signal handlers of the video model widget.
Parameters
[in,out] widget video model widget
Referenced by settings_model_widget_create().
video_model_widget_create()
GtkWidget * video_model_widget_create (GtkWidget * machine)
Create widget to control video model.
The machine argument is used to
Parameters
[in,out] machine machine model widget
Returns
GtkGrid
Referenced by create_c128_layout(), create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), create_plus4_layout(), create_vic20_layout(), and create_vsid_layout().
video_model_widget_set_callback()
void video_model_widget_set_callback (GtkWidget * widget, void(*)(int) callback)
Set extra callback to trigger when the model changes.
Parameters
[in] widget the video model widget
[in] callback function to call on model change
Referenced by create_c128_layout(), create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), create_plus4_layout(), and create_vic20_layout().
video_model_widget_set_models()
void video_model_widget_set_models (const vice_gtk3_radiogroup_entry_t * models)
Set list of valid models for the widget.
Parameters
[in] models list of video models
Referenced by vsid_ui_init().
video_model_widget_set_resource()
void video_model_widget_set_resource (const char * resource)
Set resource name of the widget.
Parameters
[in] resource name of the resource
Referenced by vsid_ui_init().
video_model_widget_set_title()
void video_model_widget_set_title (const char * title)
Set title of the widget.
Called from the ${emu}ui.c file.
Parameters
[in] title title for the widget
Referenced by vsid_ui_init().
video_model_widget_update()
void video_model_widget_update (GtkWidget * widget)
Update the video model widget.
Parameters
[in,out] widget video model widget
Referenced by machine_model_handler_c128(), machine_model_handler_c64(), machine_model_handler_c64dtv(), machine_model_handler_cbm5x0(), machine_model_handler_cbm6x0(), machine_model_handler_plus4(), machine_model_handler_vic20(), and video_model_widget_create().
Variable Documentation
model_list
const vice_gtk3_radiogroup_entry_t* model_list = NULL static
List of video models.
Set once via ${emu}ui.c during UI initialization.
Referenced by get_model_index(), video_model_widget_connect_signals(), video_model_widget_create(), and video_model_widget_set_models().
resource_name
const char* resource_name = NULL static
Name of the video model resource.
Set once via ${emu}ui.c during UI initialization.
Referenced by add_rom_chooser(), cmdline_free(), cmdline_shutdown(), cs_state_new(), custom_get_display_value(), custom_new_helper(), drive_cmdline_options_init(), driverom_load(), exp_new_helper(), iec_cmdline_options_init(), monitor_binary_process_resource_get(), monitor_binary_process_resource_set(), on_model_toggled(), raster_cmdline_options_chip_init(), vice_gtk3_resource_scale_custom_new_printf(), vice_gtk3_resource_spin_custom_new(), vice_gtk3_resource_spin_custom_new_sprintf(), vice_gtk3_resource_spin_int_sync(), video_cmdline_options_chip_init(), video_model_widget_set_resource(), and video_model_widget_update().
widget_title
const char* widget_title = NULL static
Title for the widget.
Set once via ${emu}ui.c during UI initialization.
Referenced by video_model_widget_create(), and video_model_widget_set_title().