vsid: initcmdline.h File Reference
initcmdline.h File Reference
Functions
int initcmdline_init (void)
int initcmdline_check_psid (void)
int initcmdline_check_args (int argc, char **argv)
void initcmdline_check_attach (void)
int cmdline_get_autostart_mode (void)
Get autostart mode.
void cmdline_set_autostart_mode (int mode)
void initcmdline_shutdown (void)
Function Documentation
cmdline_get_autostart_mode()
int cmdline_get_autostart_mode (void)
Get autostart mode.
Returns
autostart mode
Referenced by autostart_finish(), and kbdbuf_init().
cmdline_set_autostart_mode()
void cmdline_set_autostart_mode (int mode)
initcmdline_check_args()
int initcmdline_check_args (int argc, char ** argv)
Referenced by main_program().
initcmdline_check_attach()
void initcmdline_check_attach (void)
Referenced by machine_reset().
initcmdline_check_psid()
int initcmdline_check_psid (void)
Referenced by main_program().
initcmdline_init()
int initcmdline_init (void)
Referenced by init_cmdline_options().
initcmdline_shutdown()
void initcmdline_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().