vsid: c64/c64memsc.c File Reference
c64memsc.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "alarm.h"
#include "c64.h"
#include "c64-memory-hacks.h"
#include "c64-resources.h"
#include "c64_256k.h"
#include "c64cart.h"
#include "c64cia.h"
#include "c64mem.h"
#include "c64meminit.h"
#include "c64memlimit.h"
#include "c64memrom.h"
#include "c64pla.h"
#include "c64ui.h"
#include "c64cartmem.h"
#include "cartio.h"
#include "cartridge.h"
#include "cia.h"
#include "cpmcart.h"
#include "machine.h"
#include "mainc64cpu.h"
#include "maincpu.h"
#include "mem.h"
#include "monitor.h"
#include "plus256k.h"
#include "plus60k.h"
#include "ram.h"
#include "resources.h"
#include "reu.h"
#include "sid.h"
#include "tpi.h"
#include "vicii-cycle.h"
#include "vicii-mem.h"
#include "vicii-phi1.h"
#include "vicii.h"
Macros
#define NUM_CONFIGS 32
C64 memory-related resources.
#define NUM_VBANKS 4
Number of possible video banks (16K each).
#define COLORRAM_SIZE 0x400
Internal color memory.
Functions
static uint8_t zero_read_watch (uint16_t addr)
static void zero_store_watch (uint16_t addr, uint8_t value)
static uint8_t read_watch (uint16_t addr)
static void store_watch (uint16_t addr, uint8_t value)
static void mem_update_tab_ptrs (int flag)
called by mem_pla_config_changed(), mem_toggle_watchpoints()
void mem_toggle_watchpoints (int flag, void *context)
void c64_mem_init (void)
int mem_get_current_bank_config (void)
void mem_pla_config_changed (void)
uint8_t zero_read_dma (uint16_t addr)
reads zeropage, 0/1 comes from RAM
uint8_t zero_read (uint16_t addr)
reads zeropage, 0/1 comes from CPU port
void zero_store_dma (uint16_t addr, uint8_t value)
store zeropage, 0/1 goes to RAM
void zero_store (uint16_t addr, uint8_t value)
store zeropage, 0/1 goes to CPU port
uint8_t chargen_read (uint16_t addr)
void chargen_store (uint16_t addr, uint8_t value)
uint8_t ram_read (uint16_t addr)
void ram_store (uint16_t addr, uint8_t value)
void ram_hi_store (uint16_t addr, uint8_t value)
static uint8_t void_read (uint16_t addr)
unconnected memory space
static void void_store (uint16_t addr, uint8_t value)
void mem_dma_store (uint16_t addr, uint8_t value)
uint8_t mem_dma_read (uint16_t addr)
void mem_store (uint16_t addr, uint8_t value)
Generic memory access.
uint8_t mem_read (uint16_t addr)
void mem_store_without_ultimax (uint16_t addr, uint8_t value)
uint8_t mem_read_without_ultimax (uint16_t addr)
void mem_store_without_romlh (uint16_t addr, uint8_t value)
void colorram_store (uint16_t addr, uint8_t value)
uint8_t colorram_read (uint16_t addr)
static int check_256k_ram_write (int i, int j)
init 256k memory table changes
static void c64_256k_init_config (void)
static void plus256k_init_config (void)
init plus256k memory table changes
static void plus60k_init_config (void)
init plus60k memory table changes
void mem_set_write_hook (int config, int page, store_func_t *f)
void mem_read_tab_set (unsigned int base, unsigned int index, read_func_ptr_t read_func)
void mem_read_base_set (unsigned int base, unsigned int index, uint8_t *mem_ptr)
void mem_read_limit_set (unsigned int base, unsigned int index, uint32_t limit)
void mem_initialize_memory (void)
void mem_mmu_translate (unsigned int addr, uint8_t **base, int *start, int *limit)
void mem_powerup (void)
Initialize RAM for power-up.
void mem_set_vbank (int new_vbank)
void mem_set_tape_sense (int sense)
Set the tape sense status.
void mem_set_tape_write_in (int val)
Set the tape write in.
void mem_set_tape_motor_in (int val)
Set the tape motor in.
void mem_get_basic_text (uint16_t *start, uint16_t *end)
void mem_set_basic_text (uint16_t start, uint16_t end)
uint8_t mem_read_screen (uint16_t addr)
void mem_inject (uint32_t addr, uint8_t value)
void mem_inject_key (uint16_t addr, uint8_t value)
int mem_rom_trap_allowed (uint16_t addr)
void store_bank_io (uint16_t addr, uint8_t byte)
Banked memory access functions for the monitor.
static void poke_bank_io (uint16_t addr, uint8_t byte)
uint8_t read_bank_io (uint16_t addr)
static uint8_t peek_bank_io (uint16_t addr)
const char ** mem_bank_list (void)
Memory access functions for the monitor.
const int * mem_bank_list_nos (void)
int mem_bank_from_name (const char *name)
return bank number for a given literal bank name
int mem_bank_index_from_bank (int bank)
return current index for a given bank
int mem_bank_flags_from_bank (int bank)
uint8_t mem_bank_read (int bank, uint16_t addr, void *context)
read memory with side-effects
uint8_t mem_peek_with_config (int config, uint16_t addr, void *context)
uint8_t mem_bank_peek (int bank, uint16_t addr, void *context)
void mem_bank_write (int bank, uint16_t addr, uint8_t byte, void *context)
void mem_bank_poke (int bank, uint16_t addr, uint8_t byte, void *context)
used by monitor if sfx off
static int mem_dump_io (void *context, uint16_t addr)
mem_ioreg_list_t * mem_ioreg_list_get (void *context)
void mem_get_screen_parameter (uint16_t *base, uint8_t *rows, uint8_t *columns, int *bank)
void mem_get_cursor_parameter (uint16_t *screen_addr, uint8_t *cursor_column, uint8_t *line_length, int *blinking)
void mem_color_ram_to_snapshot (uint8_t *color_ram)
void mem_color_ram_from_snapshot (uint8_t *color_ram)
int c64_mem_ui_init_early (void)
UI functions (used to distinguish between x64 and x64sc)
int c64_mem_ui_init (void)
void c64_mem_ui_shutdown (void)
Variables
int machine_class = (1U<<8)
Machine class (moved from c64.c to distinguish between x64 and x64sc)
uint8_t mem_ram [0x10000]
The C64 memory.
uint8_t mem_chargen_rom [0x1000]
static uint8_t mem_color_ram [0x400]
uint8_t * mem_color_ram_cpu
uint8_t * mem_color_ram_vicii
uint8_t * mem_chargen_rom_ptr
Pointer to the chargen ROM.
read_func_ptr_t * _mem_read_tab_ptr
Pointers to the currently used memory read and write tables.
store_func_ptr_t * _mem_write_tab_ptr
read_func_ptr_t * _mem_read_tab_ptr_dummy
store_func_ptr_t * _mem_write_tab_ptr_dummy
static uint8_t ** _mem_read_base_tab_ptr
static uint32_t * mem_read_limit_tab_ptr
static store_func_ptr_t mem_write_tab [32][0x101]
Memory read and write tables.
static read_func_ptr_t mem_read_tab [32][0x101]
static uint8_t * mem_read_base_tab [32][0x101]
static uint32_t mem_read_limit_tab [32][0x101]
static store_func_ptr_t mem_write_tab_watch [0x101]
static read_func_ptr_t mem_read_tab_watch [0x101]
static int vbank
Current video bank (0, 1, 2 or 3).
static int mem_config
Current memory configuration.
static int tape_sense = 0
Tape sense status: 1 = some button pressed, 0 = no buttons pressed.
static int tape_write_in = 0
static int tape_motor_in = 0
static int watchpoints_active = 0
static const char * banknames []
Exported banked memory access functions for the monitor.
static const int banknums [] = { 0, 0, 1, 2, 3, 4, -1 }
static const int bankindex [] = { -1, -1, -1, -1, -1, -1, -1 }
static const int bankflags [] = { 0, 0, 0, 0, 0, 0, -1 }
Macro Definition Documentation
COLORRAM_SIZE
#define COLORRAM_SIZE 0x400
Internal color memory.
NUM_CONFIGS
#define NUM_CONFIGS 32
C64 memory-related resources.
Number of possible memory configurations.
NUM_VBANKS
#define NUM_VBANKS 4
Number of possible video banks (16K each).
Function Documentation
c64_256k_init_config()
static void c64_256k_init_config (void) static
Referenced by mem_initialize_memory().
c64_mem_init()
void c64_mem_init (void)
c64_mem_ui_init()
int c64_mem_ui_init (void)
c64_mem_ui_init_early()
int c64_mem_ui_init_early (void)
UI functions (used to distinguish between x64 and x64sc)
c64_mem_ui_shutdown()
void c64_mem_ui_shutdown (void)
chargen_read()
uint8_t chargen_read (uint16_t addr)
Referenced by mem_initialize_memory().
chargen_store()
void chargen_store (uint16_t addr, uint8_t value)
check_256k_ram_write()
static int check_256k_ram_write (int i, int j) static
init 256k memory table changes
Referenced by c64_256k_init_config(), and plus256k_init_config().
colorram_read()
uint8_t colorram_read (uint16_t addr)
Referenced by peek_bank_io(), and read_bank_io().
colorram_store()
void colorram_store (uint16_t addr, uint8_t value)
Referenced by store_bank_io().
mem_bank_flags_from_bank()
int mem_bank_flags_from_bank (int bank)
mem_bank_from_name()
int mem_bank_from_name (const char * name)
return bank number for a given literal bank name
mem_bank_index_from_bank()
int mem_bank_index_from_bank (int bank)
return current index for a given bank
mem_bank_list()
const char ** mem_bank_list (void)
Memory access functions for the monitor.
mem_bank_list_nos()
const int * mem_bank_list_nos (void)
mem_bank_peek()
uint8_t mem_bank_peek (int bank, uint16_t addr, void * context)
mem_bank_poke()
void mem_bank_poke (int bank, uint16_t addr, uint8_t byte, void * context)
used by monitor if sfx off
mem_bank_read()
uint8_t mem_bank_read (int bank, uint16_t addr, void * context)
read memory with side-effects
mem_bank_write()
void mem_bank_write (int bank, uint16_t addr, uint8_t byte, void * context)
Referenced by mem_bank_poke().
mem_color_ram_from_snapshot()
void mem_color_ram_from_snapshot (uint8_t * color_ram)
mem_color_ram_to_snapshot()
void mem_color_ram_to_snapshot (uint8_t * color_ram)
mem_dma_read()
uint8_t mem_dma_read (uint16_t addr)
mem_dma_store()
void mem_dma_store (uint16_t addr, uint8_t value)
mem_dump_io()
static int mem_dump_io (void * context, uint16_t addr) static
Referenced by mem_ioreg_list_get().
mem_get_basic_text()
void mem_get_basic_text (uint16_t * start, uint16_t * end)
Todo:
FIXME: this part needs to be checked.
mem_get_current_bank_config()
int mem_get_current_bank_config (void)
mem_get_cursor_parameter()
void mem_get_cursor_parameter (uint16_t * screen_addr, uint8_t * cursor_column, uint8_t * line_length, int * blinking)
mem_get_screen_parameter()
void mem_get_screen_parameter (uint16_t * base, uint8_t * rows, uint8_t * columns, int * bank)
mem_initialize_memory()
void mem_initialize_memory (void)
mem_inject()
void mem_inject (uint32_t addr, uint8_t value)
Referenced by mem_inject_key().
mem_inject_key()
void mem_inject_key (uint16_t addr, uint8_t value)
mem_ioreg_list_get()
mem_ioreg_list_t * mem_ioreg_list_get (void * context)
< registered area contains no mirrors
mem_mmu_translate()
void mem_mmu_translate (unsigned int addr, uint8_t ** base, int * start, int * limit)
mem_peek_with_config()
uint8_t mem_peek_with_config (int config, uint16_t addr, void * context)
Referenced by mem_bank_peek().
mem_pla_config_changed()
void mem_pla_config_changed (void)
Referenced by mem_initialize_memory(), mem_set_tape_motor_in(), mem_set_tape_sense(), mem_set_tape_write_in(), and zero_store().
mem_powerup()
void mem_powerup (void)
Initialize RAM for power-up.
mem_read()
uint8_t mem_read (uint16_t addr)
Referenced by mem_bank_read(), and mem_peek_with_config().
mem_read_base_set()
void mem_read_base_set (unsigned int base, unsigned int index, uint8_t * mem_ptr)
mem_read_limit_set()
void mem_read_limit_set (unsigned int base, unsigned int index, uint32_t limit)
mem_read_screen()
uint8_t mem_read_screen (uint16_t addr)
mem_read_tab_set()
void mem_read_tab_set (unsigned int base, unsigned int index, read_func_ptr_t read_func)
mem_read_without_ultimax()
uint8_t mem_read_without_ultimax (uint16_t addr)
mem_rom_trap_allowed()
int mem_rom_trap_allowed (uint16_t addr)
mem_set_basic_text()
void mem_set_basic_text (uint16_t start, uint16_t end)
mem_set_tape_motor_in()
void mem_set_tape_motor_in (int val)
Set the tape motor in.
mem_set_tape_sense()
void mem_set_tape_sense (int sense)
Set the tape sense status.
mem_set_tape_write_in()
void mem_set_tape_write_in (int val)
Set the tape write in.
mem_set_vbank()
void mem_set_vbank (int new_vbank)
mem_set_write_hook()
void mem_set_write_hook (int config, int page, store_func_t * f)
Referenced by mem_initialize_memory().
mem_store()
void mem_store (uint16_t addr, uint8_t value)
Generic memory access.
Referenced by mem_bank_write().
mem_store_without_romlh()
void mem_store_without_romlh (uint16_t addr, uint8_t value)
mem_store_without_ultimax()
void mem_store_without_ultimax (uint16_t addr, uint8_t value)
mem_toggle_watchpoints()
void mem_toggle_watchpoints (int flag, void * context)
mem_update_tab_ptrs()
static void mem_update_tab_ptrs (int flag) static
called by mem_pla_config_changed(), mem_toggle_watchpoints()
Referenced by mem_pla_config_changed(), and mem_toggle_watchpoints().
peek_bank_io()
static uint8_t peek_bank_io (uint16_t addr) static
Referenced by mem_bank_peek(), and mem_peek_with_config().
plus256k_init_config()
static void plus256k_init_config (void) static
init plus256k memory table changes
Referenced by mem_initialize_memory().
plus60k_init_config()
static void plus60k_init_config (void) static
init plus60k memory table changes
Referenced by mem_initialize_memory().
poke_bank_io()
static void poke_bank_io (uint16_t addr, uint8_t byte) static
Todo:
FIXME: open ends
Referenced by mem_bank_poke().
ram_hi_store()
void ram_hi_store (uint16_t addr, uint8_t value)
Referenced by check_256k_ram_write(), mem_initialize_memory(), and plus60k_init_config().
ram_read()
uint8_t ram_read (uint16_t addr)
Referenced by c64_256k_init_config(), mem_initialize_memory(), mem_read_screen(), plus256k_init_config(), and plus60k_init_config().
ram_store()
void ram_store (uint16_t addr, uint8_t value)
Referenced by check_256k_ram_write(), mem_initialize_memory(), and plus60k_init_config().
read_bank_io()
uint8_t read_bank_io (uint16_t addr)
Referenced by mem_bank_read().
read_watch()
static uint8_t read_watch (uint16_t addr) static
Referenced by mem_initialize_memory().
store_bank_io()
void store_bank_io (uint16_t addr, uint8_t byte)
Banked memory access functions for the monitor.
Referenced by mem_bank_write(), and poke_bank_io().
store_watch()
static void store_watch (uint16_t addr, uint8_t value) static
Referenced by mem_initialize_memory().
void_read()
static uint8_t void_read (uint16_t addr) static
unconnected memory space
Referenced by mem_initialize_memory().
void_store()
static void void_store (uint16_t addr, uint8_t value) static
Referenced by mem_initialize_memory().
zero_read()
uint8_t zero_read (uint16_t addr)
reads zeropage, 0/1 comes from CPU port
Referenced by mem_initialize_memory().
zero_read_dma()
uint8_t zero_read_dma (uint16_t addr)
reads zeropage, 0/1 comes from RAM
Referenced by mem_dma_read(), and zero_read().
zero_read_watch()
static uint8_t zero_read_watch (uint16_t addr) static
Referenced by mem_initialize_memory().
zero_store()
void zero_store (uint16_t addr, uint8_t value)
store zeropage, 0/1 goes to CPU port
Referenced by mem_initialize_memory().
zero_store_dma()
void zero_store_dma (uint16_t addr, uint8_t value)
store zeropage, 0/1 goes to RAM
Referenced by mem_dma_store(), and zero_store().
zero_store_watch()
static void zero_store_watch (uint16_t addr, uint8_t value) static
Referenced by mem_initialize_memory().
Variable Documentation
_mem_read_base_tab_ptr
uint8_t** _mem_read_base_tab_ptr static
Referenced by mem_mmu_translate(), and mem_pla_config_changed().
_mem_read_tab_ptr
read_func_ptr_t* _mem_read_tab_ptr
Pointers to the currently used memory read and write tables.
Referenced by mem_dma_read(), mem_read(), and mem_update_tab_ptrs().
_mem_read_tab_ptr_dummy
read_func_ptr_t* _mem_read_tab_ptr_dummy
Referenced by mem_update_tab_ptrs().
_mem_write_tab_ptr
store_func_ptr_t* _mem_write_tab_ptr
Referenced by mem_dma_store(), mem_store(), and mem_update_tab_ptrs().
_mem_write_tab_ptr_dummy
store_func_ptr_t* _mem_write_tab_ptr_dummy
Referenced by mem_update_tab_ptrs().
bankflags
const int bankflags[] = { 0, 0, 0, 0, 0, 0, -1 } static
Referenced by mem_bank_flags_from_bank().
bankindex
const int bankindex[] = { -1, -1, -1, -1, -1, -1, -1 } static
Referenced by mem_bank_index_from_bank().
banknames
const char* banknames[] static
Initial value:
= {
    "default",
    "cpu",
    "ram",
    "rom",
    "io",
    "cart",
    NULL
}
Exported banked memory access functions for the monitor.
Referenced by mem_bank_from_name(), and mem_bank_list().
banknums
const int banknums[] = { 0, 0, 1, 2, 3, 4, -1 } static
Referenced by mem_bank_flags_from_bank(), mem_bank_from_name(), mem_bank_index_from_bank(), and mem_bank_list_nos().
machine_class
int machine_class = (1U<<8)
Machine class (moved from c64.c to distinguish between x64 and x64sc)
Machine class.
mem_chargen_rom
uint8_t mem_chargen_rom[0x1000]
Referenced by chargen_read(), chargen_store(), mem_bank_peek(), mem_bank_read(), mem_initialize_memory(), and mem_peek_with_config().
mem_chargen_rom_ptr
uint8_t* mem_chargen_rom_ptr
Pointer to the chargen ROM.
Referenced by mem_initialize_memory().
mem_color_ram
uint8_t mem_color_ram[0x400] static
Referenced by colorram_read(), colorram_store(), mem_color_ram_from_snapshot(), mem_color_ram_to_snapshot(), mem_initialize_memory(), and mem_powerup().
mem_color_ram_cpu
uint8_t* mem_color_ram_cpu
Referenced by mem_initialize_memory().
mem_color_ram_vicii
uint8_t * mem_color_ram_vicii
Referenced by mem_initialize_memory().
mem_config
int mem_config static
Current memory configuration.
Referenced by mem_bank_peek(), mem_bank_poke(), mem_get_current_bank_config(), mem_pla_config_changed(), mem_read_without_ultimax(), mem_rom_trap_allowed(), mem_store_without_ultimax(), mem_update_tab_ptrs(), read_watch(), store_watch(), zero_read_watch(), and zero_store_watch().
mem_ram
uint8_t mem_ram[0x10000]
The C64 memory.
Referenced by mem_bank_peek(), mem_bank_read(), mem_bank_write(), mem_get_basic_text(), mem_get_cursor_parameter(), mem_initialize_memory(), mem_inject(), mem_peek_with_config(), mem_powerup(), mem_set_basic_text(), ram_hi_store(), ram_read(), ram_store(), zero_read_dma(), zero_store(), and zero_store_dma().
mem_read_base_tab
uint8_t* mem_read_base_tab[32][0x101] static
Referenced by mem_initialize_memory(), mem_pla_config_changed(), and mem_read_base_set().
mem_read_limit_tab
uint32_t mem_read_limit_tab[32][0x101] static
Referenced by mem_pla_config_changed(), and mem_read_limit_set().
mem_read_limit_tab_ptr
uint32_t* mem_read_limit_tab_ptr static
Referenced by mem_mmu_translate(), and mem_pla_config_changed().
mem_read_tab
read_func_ptr_t mem_read_tab[32][0x101] static
Referenced by c64_256k_init_config(), mem_initialize_memory(), mem_read_tab_set(), mem_read_without_ultimax(), mem_update_tab_ptrs(), plus256k_init_config(), plus60k_init_config(), read_watch(), and zero_read_watch().
mem_read_tab_watch
read_func_ptr_t mem_read_tab_watch[0x101] static
Referenced by mem_initialize_memory(), and mem_update_tab_ptrs().
mem_write_tab
store_func_ptr_t mem_write_tab[32][0x101] static
Memory read and write tables.
Referenced by c64_256k_init_config(), check_256k_ram_write(), mem_initialize_memory(), mem_set_write_hook(), mem_store_without_romlh(), mem_store_without_ultimax(), mem_update_tab_ptrs(), plus256k_init_config(), plus60k_init_config(), store_watch(), and zero_store_watch().
mem_write_tab_watch
store_func_ptr_t mem_write_tab_watch[0x101] static
Referenced by mem_initialize_memory(), and mem_update_tab_ptrs().
tape_motor_in
int tape_motor_in = 0 static
Referenced by mem_pla_config_changed(), and mem_set_tape_motor_in().
tape_sense
int tape_sense = 0 static
Tape sense status: 1 = some button pressed, 0 = no buttons pressed.
Referenced by mem_pla_config_changed(), and mem_set_tape_sense().
tape_write_in
int tape_write_in = 0 static
Referenced by mem_pla_config_changed(), and mem_set_tape_write_in().
vbank
int vbank static
Current video bank (0, 1, 2 or 3).
Referenced by mem_set_vbank(), zero_store(), and zero_store_dma().
watchpoints_active
int watchpoints_active = 0 static
Referenced by mem_pla_config_changed(), and mem_toggle_watchpoints().