x128: arch/gtk3/render_queue.c File Reference
render_queue.c File Reference
Manage a queue of rendered backbuffers to display.
#include "vice.h"
#include "render_queue.h"
#include <assert.h>
#include <pthread.h>
#include <string.h>
#include "lib.h"
#include "vsyncapi.h"
Data Structures
struct vice_render_queue_s
Macros
#define LOCK() pthread_mutex_lock(&rq->lock)
#define UNLOCK() pthread_mutex_unlock(&rq->lock)
Typedefs
typedef struct vice_render_queue_s render_queue_t
Functions
static void free_backbuffer (backbuffer_t *backbuffer)
void * render_queue_create (void)
Allocate, initialise and return a new render queue.
void render_queue_destroy (void *render_queue)
Destroy a render queue.
backbuffer_t * render_queue_get_from_pool (void *render_queue, int pixel_data_size_bytes)
Obtain unused backbuffer for offscreen rendering, or NULL if none available.
void render_queue_enqueue_for_display (void *render_queue, backbuffer_t *backbuffer)
Add backbuffer to the queue of backbuffers to be displayed.
unsigned int render_queue_length (void *render_queue)
backbuffer_t * render_queue_dequeue_for_display (void *render_queue)
Obtain rendered backbuffer for display, or NULL if none available.
void render_queue_return_to_pool (void *render_queue, backbuffer_t *backbuffer)
Detailed Description
Manage a queue of rendered backbuffers to display.
Author
David Hogan david.nosp@m..q.h.nosp@m.ogan@.nosp@m.gmai.nosp@m.l.com
Macro Definition Documentation
LOCK
#define LOCK () pthread_mutex_lock(&rq->lock)
UNLOCK
#define UNLOCK () pthread_mutex_unlock(&rq->lock)
Typedef Documentation
render_queue_t
typedef struct vice_render_queue_s render_queue_t
Function Documentation
free_backbuffer()
static void free_backbuffer (backbuffer_t * backbuffer) static
Referenced by render_queue_destroy().
render_queue_create()
void * render_queue_create (void)
Allocate, initialise and return a new render queue.
Referenced by vice_opengl_initialise_canvas().
render_queue_dequeue_for_display()
backbuffer_t * render_queue_dequeue_for_display (void * render_queue)
Obtain rendered backbuffer for display, or NULL if none available.
Referenced by render().
render_queue_destroy()
void render_queue_destroy (void * render_queue)
Destroy a render queue.
Referenced by vice_opengl_destroy_context().
render_queue_enqueue_for_display()
void render_queue_enqueue_for_display (void * render_queue, backbuffer_t * backbuffer)
Add backbuffer to the queue of backbuffers to be displayed.
Referenced by vice_opengl_refresh_rect().
render_queue_get_from_pool()
backbuffer_t * render_queue_get_from_pool (void * render_queue, int pixel_data_size_bytes)
Obtain unused backbuffer for offscreen rendering, or NULL if none available.
Referenced by vice_opengl_refresh_rect().
render_queue_length()
unsigned int render_queue_length (void * render_queue)
Referenced by render_queue_length().
render_queue_return_to_pool()
void render_queue_return_to_pool (void * render_queue, backbuffer_t * backbuffer)
Referenced by render(), and vice_opengl_refresh_rect().