vsid: monitor/mon_breakpoint.h File Reference
mon_breakpoint.h File Reference
#include "montypes.h"
Data Structures
struct mon_checkpoint_s
Typedefs
typedef enum mon_breakpoint_type_e mon_breakpoint_type_t
typedef struct mon_checkpoint_s mon_checkpoint_t
Enumerations
enum mon_breakpoint_type_e {
BP_NONE ,
BP_INACTIVE ,
BP_ACTIVE
}
Functions
void mon_breakpoint_init (void)
void mon_breakpoint_switch_checkpoint (int op, int breakpt_num)
void mon_breakpoint_set_ignore_count (int breakpt_num, int count)
void mon_breakpoint_print_checkpoints (void)
void mon_breakpoint_delete_checkpoint (int brknum)
void mon_breakpoint_set_checkpoint_condition (int brk_num, struct cond_node_s *cnode)
void mon_breakpoint_set_checkpoint_command (int brk_num, char *cmd)
bool mon_breakpoint_check_checkpoint (MEMSPACE mem, unsigned int addr, unsigned int lastpc, MEMORY_OP op)
int mon_breakpoint_add_checkpoint (MON_ADDR start_addr, MON_ADDR end_addr, bool stop, MEMORY_OP op, bool is_temp, bool do_print)
mon_breakpoint_type_t mon_breakpoint_is (MON_ADDR address)
void mon_breakpoint_set (MON_ADDR address)
void mon_breakpoint_unset (MON_ADDR address)
void mon_breakpoint_enable (MON_ADDR address)
void mon_breakpoint_disable (MON_ADDR address)
mon_checkpoint_t * mon_breakpoint_find_checkpoint (int brknum)
find the breakpoint with number 'brknum' in the linked list
mon_checkpoint_t ** mon_breakpoint_checkpoint_list_get (unsigned int *len)
Get a list of all checkpoints.
int parse_and_execute_line (char *input)
defined in mon_parse.y, and thus, in mon_parse.c
Typedef Documentation
mon_breakpoint_type_t
typedef enum mon_breakpoint_type_e mon_breakpoint_type_t
mon_checkpoint_t
typedef struct mon_checkpoint_s mon_checkpoint_t
Enumeration Type Documentation
mon_breakpoint_type_e
enum mon_breakpoint_type_e
Enumerator
BP_NONE
BP_INACTIVE
BP_ACTIVE
Function Documentation
mon_breakpoint_add_checkpoint()
int mon_breakpoint_add_checkpoint (MON_ADDR start_addr, MON_ADDR end_addr, bool stop, MEMORY_OP op, bool is_temp, bool do_print)
Referenced by monitor_binary_process_checkpoint_set(), and monitor_init().
mon_breakpoint_check_checkpoint()
bool mon_breakpoint_check_checkpoint (MEMSPACE mem, unsigned int addr, unsigned int lastpc, MEMORY_OP op)
Referenced by monitor_check_breakpoints(), watchpoints_check_loads(), and watchpoints_check_stores().
mon_breakpoint_checkpoint_list_get()
mon_checkpoint_t ** mon_breakpoint_checkpoint_list_get (unsigned int * len)
Get a list of all checkpoints.
Parameters
[out] len length of the returned array
Returns
The list of checkpoints
Referenced by monitor_binary_process_checkpoint_list().
mon_breakpoint_delete_checkpoint()
void mon_breakpoint_delete_checkpoint (int brknum)
Referenced by mon_breakpoint_check_checkpoint(), and monitor_binary_process_checkpoint_delete().
mon_breakpoint_disable()
void mon_breakpoint_disable (MON_ADDR address)
mon_breakpoint_enable()
void mon_breakpoint_enable (MON_ADDR address)
mon_breakpoint_find_checkpoint()
mon_checkpoint_t * mon_breakpoint_find_checkpoint (int brknum)
find the breakpoint with number 'brknum' in the linked list
Parameters
[in] brknum breakpoint number
Returns
The checkpoint that has brknum, or NULL
Referenced by mon_breakpoint_delete_checkpoint(), mon_breakpoint_print_checkpoints(), mon_breakpoint_set_checkpoint_command(), mon_breakpoint_set_checkpoint_condition(), mon_breakpoint_set_ignore_count(), mon_breakpoint_switch_checkpoint(), monitor_binary_process_checkpoint_delete(), monitor_binary_process_checkpoint_get(), monitor_binary_process_checkpoint_set(), monitor_binary_process_checkpoint_toggle(), and monitor_binary_process_condition_set().
mon_breakpoint_init()
void mon_breakpoint_init (void)
Referenced by monitor_init().
mon_breakpoint_is()
mon_breakpoint_type_t mon_breakpoint_is (MON_ADDR address)
mon_breakpoint_print_checkpoints()
void mon_breakpoint_print_checkpoints (void)
mon_breakpoint_set()
void mon_breakpoint_set (MON_ADDR address)
mon_breakpoint_set_checkpoint_command()
void mon_breakpoint_set_checkpoint_command (int brk_num, char * cmd)
mon_breakpoint_set_checkpoint_condition()
void mon_breakpoint_set_checkpoint_condition (int brk_num, struct cond_node_s * cnode)
mon_breakpoint_set_ignore_count()
void mon_breakpoint_set_ignore_count (int breakpt_num, int count)
mon_breakpoint_switch_checkpoint()
void mon_breakpoint_switch_checkpoint (int op, int breakpt_num)
Referenced by monitor_binary_process_checkpoint_set(), and monitor_binary_process_checkpoint_toggle().
mon_breakpoint_unset()
void mon_breakpoint_unset (MON_ADDR address)
parse_and_execute_line()
int parse_and_execute_line (char * input)
defined in mon_parse.y, and thus, in mon_parse.c
Referenced by mon_breakpoint_check_checkpoint(), monitor_binary_process_condition_set(), monitor_process(), and playback_next_command().