vsid: gfxoutputdrv/bmpdrv.c File Reference
bmpdrv.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "archdep.h"
#include "bmpdrv.h"
#include "lib.h"
#include "log.h"
#include "gfxoutput.h"
#include "palette.h"
#include "screenshot.h"
#include "types.h"
#include "util.h"
Data Structures
struct gfxoutputdrv_data_s
Macros
#define BMP_HDR_OFFSET (14 + 40 + 4 * screenshot->palette->num_entries)
#define BMP_HDR_OFFSET24 (14 + 40)
Typedefs
typedef struct gfxoutputdrv_data_s gfxoutputdrv_data_t
Functions
static int bmpdrv_bytes_per_row (screenshot_t *screenshot)
static uint32_t bmpdrv_bmp_size (screenshot_t *screenshot)
static int bmpdrv_write_file_header (screenshot_t *screenshot)
static int bmpdrv_write_bitmap_info (screenshot_t *screenshot)
static int bmpdrv_open (screenshot_t *screenshot, const char *filename)
static int bmpdrv_write (screenshot_t *screenshot)
static int bmpdrv_close (screenshot_t *screenshot)
static int bmpdrv_save (screenshot_t *screenshot, const char *filename)
void gfxoutput_init_bmp (int help)
Variables
static gfxoutputdrv_t bmp_drv
Macro Definition Documentation
BMP_HDR_OFFSET
#define BMP_HDR_OFFSET (14 + 40 + 4 * screenshot->palette->num_entries)
BMP_HDR_OFFSET24
#define BMP_HDR_OFFSET24 (14 + 40)
Typedef Documentation
gfxoutputdrv_data_t
typedef struct gfxoutputdrv_data_s gfxoutputdrv_data_t
Function Documentation
bmpdrv_bmp_size()
static uint32_t bmpdrv_bmp_size (screenshot_t * screenshot) static
Referenced by bmpdrv_write_file_header().
bmpdrv_bytes_per_row()
static int bmpdrv_bytes_per_row (screenshot_t * screenshot) static
Referenced by bmpdrv_bmp_size(), bmpdrv_close(), bmpdrv_open(), and bmpdrv_write().
bmpdrv_close()
static int bmpdrv_close (screenshot_t * screenshot) static
Referenced by bmpdrv_save().
bmpdrv_open()
static int bmpdrv_open (screenshot_t * screenshot, const char * filename) static
< write mode (binary)
Referenced by bmpdrv_save().
bmpdrv_save()
static int bmpdrv_save (screenshot_t * screenshot, const char * filename) static
bmpdrv_write()
static int bmpdrv_write (screenshot_t * screenshot) static
Referenced by bmpdrv_save().
bmpdrv_write_bitmap_info()
static int bmpdrv_write_bitmap_info (screenshot_t * screenshot) static
Referenced by bmpdrv_open().
bmpdrv_write_file_header()
static int bmpdrv_write_file_header (screenshot_t * screenshot) static
Referenced by bmpdrv_open().
gfxoutput_init_bmp()
void gfxoutput_init_bmp (int help)
Referenced by gfxoutput_early_init().
Variable Documentation
bmp_drv
static gfxoutputdrv_t bmp_drv static
Initial value:
=
{
    GFXOUTPUTDRV_TYPE_SCREENSHOT_IMAGE,
    "BMP",
    "BMP screenshot",
    "bmp",
    NULL,
    bmpdrv_open,
    bmpdrv_close,
    bmpdrv_write,
    bmpdrv_save,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
}
Referenced by bmpdrv_open(), and gfxoutput_init_bmp().