vsid: parallel/parallel-trap.c File Reference
parallel-trap.c File Reference
#include "vice.h"
#include <stdio.h>
#include "attach.h"
#include "drive.h"
#include "drivetypes.h"
#include "log.h"
#include "parallel-trap.h"
#include "parallel.h"
#include "serial.h"
#include "types.h"
Macros
#define DBG(x)
#define SERIAL_NAMELENGTH 255
#define DELAYEDCLOSE
Functions
static int parallelcommand (void)
int parallel_trap_attention (int b)
int parallel_trap_sendbyte (uint8_t data)
int parallel_trap_receivebyte (uint8_t *data, int fake)
void parallel_trap_eof_callback_set (void(*func)(void))
Specify a function to call when EOF happens in ‘serialreceivebyte()’.
void parallel_trap_attention_callback_set (void(*func)(void))
Specify a function to call when the ‘serialattention()’ trap is called.
Variables
static uint8_t TrapDevice
On which channel did listen happen to?
static uint8_t TrapSecondary
static void(* eof_callback_func)(void)
Function to call when EOF happens in ‘serialreceivebyte()’.
static void(* attention_callback_func)(void)
Function to call when the ‘serialattention()’ trap is called.
static log_t parallel_log = ((log_t)-2)
Logging goes here.
static uint8_t SerialBuffer [255+1]
static int SerialPtr
Macro Definition Documentation
DBG
#define DBG (x)
DELAYEDCLOSE
#define DELAYEDCLOSE
SERIAL_NAMELENGTH
#define SERIAL_NAMELENGTH 255
Function Documentation
parallel_trap_attention()
int parallel_trap_attention (int b)
Referenced by In1_DAV_true().
parallel_trap_attention_callback_set()
void parallel_trap_attention_callback_set (void(*)(void) func)
Specify a function to call when the ‘serialattention()’ trap is called.
Referenced by machine_bus_attention_callback_set().
parallel_trap_eof_callback_set()
void parallel_trap_eof_callback_set (void(*)(void) func)
Specify a function to call when EOF happens in ‘serialreceivebyte()’.
Referenced by machine_bus_eof_callback_set().
parallel_trap_receivebyte()
int parallel_trap_receivebyte (uint8_t * data, int fake)
Referenced by Out1_NRFD_false(), Out2_NDAC_false(), and parallelcommand().
parallel_trap_sendbyte()
int parallel_trap_sendbyte (uint8_t data)
Referenced by In1_DAV_true().
parallelcommand()
static int parallelcommand (void) static
Referenced by parallel_trap_attention().
Variable Documentation
attention_callback_func
void(* attention_callback_func) (void) (void) static
Function to call when the ‘serialattention()’ trap is called.
Referenced by parallel_trap_attention(), and parallel_trap_attention_callback_set().
eof_callback_func
void(* eof_callback_func) (void) (void) static
Function to call when EOF happens in ‘serialreceivebyte()’.
Referenced by parallel_trap_eof_callback_set(), and parallel_trap_receivebyte().
parallel_log
log_t parallel_log = ((log_t)-2) static
Logging goes here.
Referenced by parallel_trap_attention(), parallel_trap_receivebyte(), parallel_trap_sendbyte(), and parallelcommand().
SerialBuffer
uint8_t SerialBuffer[255+1] static
Referenced by fsdrive_snapshot_read_module(), fsdrive_snapshot_write_module(), parallel_trap_sendbyte(), and parallelcommand().
SerialPtr
int SerialPtr static
Referenced by fsdrive_snapshot_read_module(), fsdrive_snapshot_write_module(), parallel_trap_sendbyte(), and parallelcommand().
TrapDevice
uint8_t TrapDevice static
On which channel did listen happen to?
Referenced by parallel_trap_attention(), parallel_trap_receivebyte(), parallel_trap_sendbyte(), and parallelcommand().
TrapSecondary
uint8_t TrapSecondary static
Referenced by parallel_trap_attention(), parallel_trap_receivebyte(), parallel_trap_sendbyte(), and parallelcommand().