vsid: tap.h File Reference
tap.h File Reference
#include <stdio.h>
#include "types.h"
Data Structures
struct tap_s
Macros
#define TAP_HDR_SIZE 20
#define TAP_HDR_MAGIC_OFFSET 0
#define TAP_HDR_VERSION 12
#define TAP_HDR_SYSTEM 13
#define TAP_HDR_VIDEO 14
#define TAP_HDR_LEN 16
#define TAP_HDR_SYSTEM_C64 0
#define TAP_HDR_SYSTEM_VIC20 1
#define TAP_HDR_SYSTEM_C16 2
#define TAP_HDR_SYSTEM_PET 3
#define TAP_HDR_SYSTEM_C500 4
#define TAP_HDR_SYSTEM_C600 5
#define TAP_HDR_VIDEO_PAL 0
#define TAP_HDR_VIDEO_NTSC 1
#define TAP_HDR_VIDEO_NTSCOLD 2
#define TAP_HDR_VIDEO_PALN 3
Typedefs
typedef struct tap_s tap_t
Functions
void tap_init (const struct tape_init_s *init)
tap_t * tap_open (const char *name, unsigned int *read_only)
int tap_close (tap_t *tap)
int tap_create (const char *name)
int tap_seek_start (tap_t *tap)
int tap_seek_to_file (tap_t *tap, unsigned int file_number)
int tap_seek_to_offset (tap_t *tap, unsigned long offset)
unsigned long tap_get_offset (tap_t *tap)
int tap_seek_to_next_file (tap_t *tap, unsigned int allow_rewind)
void tap_get_header (tap_t *tap, uint8_t *name)
struct tape_file_record_s * tap_get_current_file_record (tap_t *tap)
int tap_read (tap_t *tap, uint8_t *buf, size_t size)
used by virtual devices
int tap_cmdline_options_init (void)
Macro Definition Documentation
TAP_HDR_LEN
#define TAP_HDR_LEN 16
TAP_HDR_MAGIC_OFFSET
#define TAP_HDR_MAGIC_OFFSET 0
TAP_HDR_SIZE
#define TAP_HDR_SIZE 20
TAP_HDR_SYSTEM
#define TAP_HDR_SYSTEM 13
TAP_HDR_SYSTEM_C16
#define TAP_HDR_SYSTEM_C16 2
TAP_HDR_SYSTEM_C500
#define TAP_HDR_SYSTEM_C500 4
TAP_HDR_SYSTEM_C600
#define TAP_HDR_SYSTEM_C600 5
TAP_HDR_SYSTEM_C64
#define TAP_HDR_SYSTEM_C64 0
TAP_HDR_SYSTEM_PET
#define TAP_HDR_SYSTEM_PET 3
TAP_HDR_SYSTEM_VIC20
#define TAP_HDR_SYSTEM_VIC20 1
TAP_HDR_VERSION
#define TAP_HDR_VERSION 12
TAP_HDR_VIDEO
#define TAP_HDR_VIDEO 14
TAP_HDR_VIDEO_NTSC
#define TAP_HDR_VIDEO_NTSC 1
TAP_HDR_VIDEO_NTSCOLD
#define TAP_HDR_VIDEO_NTSCOLD 2
TAP_HDR_VIDEO_PAL
#define TAP_HDR_VIDEO_PAL 0
TAP_HDR_VIDEO_PALN
#define TAP_HDR_VIDEO_PALN 3
Typedef Documentation
tap_t
typedef struct tap_s tap_t
Function Documentation
tap_close()
int tap_close (tap_t * tap)
Referenced by tape_image_close().
tap_cmdline_options_init()
int tap_cmdline_options_init (void)
tap_create()
int tap_create (const char * name)
< write mode (binary)
Todo:
FIXME: saving v2 C16 format doesnt actually work
Todo:
FIXME: saving v2 C16 format doesnt actually work
Referenced by tape_image_create().
tap_get_current_file_record()
struct tape_file_record_s * tap_get_current_file_record (tap_t * tap)
Referenced by tape_get_current_file_record().
tap_get_header()
void tap_get_header (tap_t * tap, uint8_t * name)
Referenced by tape_get_header().
tap_get_offset()
unsigned long tap_get_offset (tap_t * tap)
Referenced by tape_get_offset().
tap_init()
void tap_init (const struct tape_init_s * init)
Referenced by tape_init().
tap_open()
tap_t * tap_open (const char * name, unsigned int * read_only)
< read/write mode
< read mode (binary)
Referenced by tape_image_open().
tap_read()
int tap_read (tap_t * tap, uint8_t * buf, size_t size)
used by virtual devices
Referenced by tape_read().
tap_seek_start()
int tap_seek_start (tap_t * tap)
Referenced by tap_seek_to_file(), tap_seek_to_next_file(), and tape_seek_start().
tap_seek_to_file()
int tap_seek_to_file (tap_t * tap, unsigned int file_number)
Referenced by tape_seek_to_file().
tap_seek_to_next_file()
int tap_seek_to_next_file (tap_t * tap, unsigned int allow_rewind)
Referenced by tap_read(), tap_seek_to_file(), and tape_seek_to_next_file().
tap_seek_to_offset()
int tap_seek_to_offset (tap_t * tap, unsigned long offset)
Referenced by tape_seek_to_offset().