vsid: arch/gtk3/uimon-fallback.c File Reference
uimon-fallback.c File Reference
Fallback implementation for the ML-Monitor for when the VTE library is not available.
#include "vice.h"
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include "console.h"
#include "debug_gtk3.h"
#include "log.h"
#include "monitor.h"
#include "uimon.h"
#include "uimon-fallback.h"
Functions
int consolefb_close_all (void)
NOP.
int consolefb_init (void)
NOP.
int consolefb_out (console_t *log, const char *format,...)
Output message on native console.
console_t * uimonfb_window_open (void)
Open console window.
void uimonfb_window_close (void)
Close console window.
void uimonfb_window_suspend (void)
Suspend console window.
console_t * uimonfb_window_resume (void)
Resume console window.
int uimonfb_out (const char *buffer)
Output string buffer to console_log_local.
int uimonfb_petscii_out (const char *buffer, int len)
int uimonfb_petscii_upper_out (const char *buffer, int len)
int uimonfb_scrcode_out (const char *buffer, int len)
char * uimonfb_get_in (char **ppchCommandLine, const char *prompt)
Read a string.
void uimonfb_notify_change (void)
NOP.
void uimonfb_set_interface (struct monitor_interface_s **monitor_interface_init, int count)
NOP.
Variables
static console_t * console_log_local = NULL
Reference to the log file.
Detailed Description
Fallback implementation for the ML-Monitor for when the VTE library is not available.
Author
Fabrizio Gennari fabri.nosp@m.zio..nosp@m.ge@ti.nosp@m.scal.nosp@m.i.it
Function Documentation
consolefb_close_all()
int consolefb_close_all (void)
NOP.
Returns
0
Referenced by console_close_all().
consolefb_init()
int consolefb_init (void)
NOP.
Returns
0
Referenced by console_init().
consolefb_out()
int consolefb_out (console_t * log, const char * format, ...)
Output message on native console.
Parameters
[in] log log (unused, console_log_local is used)
[in] format format string
[in] ... arguments for format
Returns
0
uimonfb_get_in()
char * uimonfb_get_in (char ** ppchCommandLine, const char * prompt)
Read a string.
Parameters
ppchCommandLine ? (unused)
[in] prompt prompt to display
Returns
string
Referenced by uimon_get_in().
uimonfb_notify_change()
void uimonfb_notify_change (void)
NOP.
Referenced by uimon_notify_change().
uimonfb_out()
int uimonfb_out (const char * buffer)
Output string buffer to console_log_local.
Parameters
[in] buffer message
Returns
0
Referenced by uimon_out().
uimonfb_petscii_out()
int uimonfb_petscii_out (const char * buffer, int len)
Referenced by uimon_petscii_out().
uimonfb_petscii_upper_out()
int uimonfb_petscii_upper_out (const char * buffer, int len)
Referenced by uimon_petscii_upper_out().
uimonfb_scrcode_out()
int uimonfb_scrcode_out (const char * buffer, int len)
Referenced by uimon_scrcode_out(), and uimon_scrcode_upper_out().
uimonfb_set_interface()
void uimonfb_set_interface (struct monitor_interface_s ** monitor_interface_init, int count)
NOP.
Parameters
[in] monitor_interface_init ? (unused)
[in] count ? (unused)
Referenced by uimon_set_interface().
uimonfb_window_close()
void uimonfb_window_close (void)
Close console window.
Referenced by uimon_window_close().
uimonfb_window_open()
console_t * uimonfb_window_open (void)
Open console window.
Returns
console reference
Referenced by uimon_window_open().
uimonfb_window_resume()
console_t * uimonfb_window_resume (void)
Resume console window.
Returns
console
Referenced by uimon_window_resume().
uimonfb_window_suspend()
void uimonfb_window_suspend (void)
Suspend console window.
Unused.
Referenced by uimon_window_suspend().
Variable Documentation
console_log_local
console_t* console_log_local = NULL static
Reference to the log file.
Todo:
FIXME: this code is simple enough to be merged back into uimon.c
Referenced by consolefb_out(), uimonfb_get_in(), uimonfb_out(), uimonfb_petscii_out(), uimonfb_petscii_upper_out(), uimonfb_scrcode_out(), uimonfb_window_close(), uimonfb_window_open(), and uimonfb_window_resume().