vsid: initcmdline.c File Reference
initcmdline.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "attach.h"
#include "autostart.h"
#include "cartridge.h"
#include "cmdline.h"
#include "console.h"
#include "drive.h"
#include "fliplist.h"
#include "fsdevice.h"
#include "gfxoutput.h"
#include "initcmdline.h"
#include "kbdbuf.h"
#include "keyboard.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "monitor.h"
#include "monitor_binary.h"
#include "monitor_network.h"
#include "network.h"
#include "printer.h"
#include "resources.h"
#include "romset.h"
#include "sysfile.h"
#include "tape.h"
#include "tapeport.h"
#include "traps.h"
#include "uiapi.h"
#include "util.h"
#include "vice-event.h"
#include "vicefeatures.h"
#include "video.h"
#include "vsync.h"
#include "zfile.h"
Macros
#define DBG(x)
#define NUM_STARTUP_DISK_IMAGES 8
Functions
int cmdline_get_autostart_mode (void)
Get autostart mode.
void cmdline_set_autostart_mode (int mode)
static void cmdline_free_autostart_string (void)
void initcmdline_shutdown (void)
static int cmdline_help (const char *param, void *extra_param)
static int cmdline_features (const char *param, void *extra_param)
static int cmdline_config (const char *param, void *extra_param)
static int cmdline_add_config (const char *param, void *extra_param)
static int cmdline_dumpconfig (const char *param, void *extra_param)
static int cmdline_default (const char *param, void *extra_param)
static int cmdline_chdir (const char *param, void *extra_param)
static int cmdline_limitcycles (const char *param, void *extra_param)
static int cmdline_autostart (const char *param, void *extra_param)
static int cmdline_autoload (const char *param, void *extra_param)
static int cmdline_console (const char *param, void *extra_param)
static int cmdline_seed (const char *param, void *extra_param)
static int cmdline_version (const char *param, void *extra_param)
static int cmdline_attach (const char *param, void *extra_param)
int initcmdline_init (void)
int initcmdline_check_psid (void)
int initcmdline_check_args (int argc, char **argv)
void initcmdline_check_attach (void)
Variables
static char * autostart_string = NULL
static char * startup_disk_images [8]
static char * startup_tape_image [TAPEPORT_MAX_PORTS]
static unsigned int autostart_mode = -1
static const cmdline_option_t common_cmdline_options []
static const cmdline_option_t cmdline_options []
These are the command-line options for the initialization sequence.
static const cmdline_option_t cmdline_pet_options []
Macro Definition Documentation
DBG
#define DBG (x)
NUM_STARTUP_DISK_IMAGES
#define NUM_STARTUP_DISK_IMAGES 8
Function Documentation
cmdline_add_config()
static int cmdline_add_config (const char * param, void * extra_param) static
cmdline_attach()
static int cmdline_attach (const char * param, void * extra_param) static
cmdline_autoload()
static int cmdline_autoload (const char * param, void * extra_param) static
cmdline_autostart()
static int cmdline_autostart (const char * param, void * extra_param) static
cmdline_chdir()
static int cmdline_chdir (const char * param, void * extra_param) static
cmdline_config()
static int cmdline_config (const char * param, void * extra_param) static
cmdline_console()
static int cmdline_console (const char * param, void * extra_param) static
cmdline_default()
static int cmdline_default (const char * param, void * extra_param) static
cmdline_dumpconfig()
static int cmdline_dumpconfig (const char * param, void * extra_param) static
cmdline_features()
static int cmdline_features (const char * param, void * extra_param) static
cmdline_free_autostart_string()
static void cmdline_free_autostart_string (void) static
Referenced by cmdline_autoload(), cmdline_autostart(), and initcmdline_check_attach().
cmdline_get_autostart_mode()
int cmdline_get_autostart_mode (void)
Get autostart mode.
Returns
autostart mode
Referenced by autostart_finish(), and kbdbuf_init().
cmdline_help()
static int cmdline_help (const char * param, void * extra_param) static
Todo:
FIXME: a hack to prevent -help crashing on the SDL ui. This needs to be fixed properly!!
cmdline_limitcycles()
static int cmdline_limitcycles (const char * param, void * extra_param) static
cmdline_seed()
static int cmdline_seed (const char * param, void * extra_param) static
cmdline_set_autostart_mode()
void cmdline_set_autostart_mode (int mode)
cmdline_version()
static int cmdline_version (const char * param, void * extra_param) static
initcmdline_check_args()
int initcmdline_check_args (int argc, char ** argv)
Referenced by main_program().
initcmdline_check_attach()
void initcmdline_check_attach (void)
Referenced by machine_reset().
initcmdline_check_psid()
int initcmdline_check_psid (void)
Referenced by main_program().
initcmdline_init()
int initcmdline_init (void)
Referenced by init_cmdline_options().
initcmdline_shutdown()
void initcmdline_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
Variable Documentation
autostart_mode
unsigned int autostart_mode = -1 static
Referenced by cmdline_autoload(), cmdline_autostart(), cmdline_get_autostart_mode(), cmdline_set_autostart_mode(), initcmdline_check_args(), and initcmdline_check_attach().
autostart_string
char* autostart_string = NULL static
Referenced by cmdline_autoload(), cmdline_autostart(), cmdline_free_autostart_string(), initcmdline_check_args(), initcmdline_check_attach(), and initcmdline_check_psid().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-autostart", CALL_FUNCTION,  (1 << 0) ,
      cmdline_autostart, NULL, NULL, NULL,
      "<Name>", "Attach and autostart tape/disk image <name>" },
    { "-autoload", CALL_FUNCTION,  (1 << 0) ,
      cmdline_autoload, NULL, NULL, NULL,
      "<Name>", "Attach and autoload tape/disk image <name>" },
    { "-1", CALL_FUNCTION,  (1 << 0) ,
      cmdline_attach, (void *)1, NULL, NULL,
      "<Name>", "Attach <name> as a tape image" },
    { "-8", CALL_FUNCTION,  (1 << 0) ,
      cmdline_attach, (void *)8, NULL, NULL,
      "<Name>", "Attach <name> as a disk image in unit #8" },
    { "-8d1", CALL_FUNCTION,  (1 << 0) ,
      cmdline_attach, (void *)64, NULL, NULL,
      "<Name>", "Attach <name> as a disk image in unit #8 drive #1" },
    { "-9", CALL_FUNCTION,  (1 << 0) ,
      cmdline_attach, (void *)9, NULL, NULL,
      "<Name>", "Attach <name> as a disk image in unit #9" },
    { "-9d1", CALL_FUNCTION,  (1 << 0) ,
      cmdline_attach, (void *)65, NULL, NULL,
      "<Name>", "Attach <name> as a disk image in unit #9 drive #1" },
    { "-10", CALL_FUNCTION,  (1 << 0) ,
      cmdline_attach, (void *)10, NULL, NULL,
      "<Name>", "Attach <name> as a disk image in unit #10" },
    { "-10d1", CALL_FUNCTION,  (1 << 0) ,
      cmdline_attach, (void *)66, NULL, NULL,
      "<Name>", "Attach <name> as a disk image in unit #10 drive #1" },
    { "-11", CALL_FUNCTION,  (1 << 0) ,
      cmdline_attach, (void *)11, NULL, NULL,
      "<Name>", "Attach <name> as a disk image in unit #11" },
    { "-11d1", CALL_FUNCTION,  (1 << 0) ,
      cmdline_attach, (void *)67, NULL, NULL,
      "<Name>", "Attach <name> as a disk image in unit #11 drive #1" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
These are the command-line options for the initialization sequence.
Referenced by initcmdline_init().
cmdline_pet_options
const cmdline_option_t cmdline_pet_options[] static
Initial value:
=
{
    { "-2", CALL_FUNCTION,  (1 << 0) ,
      cmdline_attach, (void *)2, NULL, NULL,
      "<Name>", "Attach <name> as a tape image" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by initcmdline_init().
common_cmdline_options
const cmdline_option_t common_cmdline_options[] static
Initial value:
=
{
    { "-help", CALL_FUNCTION,  0 ,
      cmdline_help, NULL, NULL, NULL,
      NULL, "Show a list of the available options and exit normally" },
    { "-?", CALL_FUNCTION,  0 ,
      cmdline_help, NULL, NULL, NULL,
      NULL, "Show a list of the available options and exit normally" },
    { "-h", CALL_FUNCTION,  0 ,
      cmdline_help, NULL, NULL, NULL,
      NULL, "Show a list of the available options and exit normally" },
    { "-version", CALL_FUNCTION,  0 ,
      cmdline_version, NULL, NULL, NULL,
      NULL, "Show the program name and version" },
    { "-features", CALL_FUNCTION,  0 ,
      cmdline_features, NULL, NULL, NULL,
      NULL, "Show a list of the available compile-time options and their configuration." },
    { "-default", CALL_FUNCTION,  0 ,
      cmdline_default, NULL, NULL, NULL,
      NULL, "Restore default settings" },
    { "-config", CALL_FUNCTION,  (1 << 0) ,
      cmdline_config, NULL, NULL, NULL,
      "<filename>", "Specify config file" },
    { "-addconfig", CALL_FUNCTION,  (1 << 0) ,
      cmdline_add_config, NULL, NULL, NULL,
      "<filename>", "Specify extra config file for loading additional resources." },
    { "-dumpconfig", CALL_FUNCTION,  (1 << 0) ,
      cmdline_dumpconfig, NULL, NULL, NULL,
      "<filename>", "Dump all resources to specified config file" },
    { "-chdir", CALL_FUNCTION,  (1 << 0) ,
      cmdline_chdir, NULL, NULL, NULL,
      "Directory", "Change current working directory." },
    { "-limitcycles", CALL_FUNCTION,  (1 << 0) ,
      cmdline_limitcycles, NULL, NULL, NULL,
      "<value>", "Specify number of cycles to run before quitting with an error." },
    { "-console", CALL_FUNCTION,  0 ,
      cmdline_console, NULL, NULL, NULL,
      NULL, "Console mode (for music playback)" },
    { "-seed", CALL_FUNCTION,  (1 << 0) ,
      cmdline_seed, NULL, NULL, NULL,
      "<value>", "Set random seed (for debugging)" },
    { "-core", SET_RESOURCE,  0 ,
      NULL, NULL, "DoCoreDump", (resource_value_t)1,
      NULL, "Allow production of core dumps" },
    { "+core", SET_RESOURCE,  0 ,
      NULL, NULL, "DoCoreDump", (resource_value_t)0,
      NULL, "Do not produce core dumps" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by initcmdline_init().
startup_disk_images
char* startup_disk_images[8] static
Referenced by cmdline_attach(), initcmdline_check_attach(), and initcmdline_shutdown().
startup_tape_image
char* startup_tape_image[TAPEPORT_MAX_PORTS] static
Referenced by cmdline_attach(), initcmdline_check_attach(), and initcmdline_shutdown().