x128: arch/shared/archdep_expand_path.c File Reference
archdep_expand_path.c File Reference
Expand a path into an absolute path.
#include "vice.h"
#include "archdep_defs.h"
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "archdep_getcwd.h"
#include "archdep_home_path.h"
#include "lib.h"
#include "log.h"
#include "util.h"
#include "archdep_expand_path.h"
Functions
int archdep_expand_path (char **return_path, const char *orig_name)
Generate heap-allocated full pathname of orig_name.
Detailed Description
Expand a path into an absolute path.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
archdep_expand_path()
int archdep_expand_path (char ** return_path, const char * orig_name)
Generate heap-allocated full pathname of orig_name.
Returns the absolute path of orig_name.
Expands '~' to the user's home path on Unix. If the prefix in orig_name is not '\' and not '/' and not '~/' (Unix) the file is assumed to reside in the current working directory, whatever that may be.
Parameters
[out] return_path pointer to expanded path destination
[in] orig_name original path
Returns
0
Referenced by archdep_filename_parameter(), attach_cmd(), autostart_prg_with_virtual_fs(), bread_cmd(), bwrite_cmd(), fliplist_load_list(), fliplist_save_list(), zfile_close_action(), and zfile_list_add().