x128: c128/z80mem.c File Reference
z80mem.c File Reference
Z80 memory handling.
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "c128cart.h"
#include "c128mem.h"
#include "c128mmu.h"
#include "c64cia.h"
#include "c128memrom.h"
#include "c64memrom.h"
#include "cartio.h"
#include "cmdline.h"
#include "functionrom.h"
#include "log.h"
#include "mem.h"
#include "resources.h"
#include "reu.h"
#include "sid.h"
#include "sysfile.h"
#include "types.h"
#include "vdc-mem.h"
#include "vdc.h"
#include "vicii-mem.h"
#include "vicii.h"
#include "z80mem.h"
#include "z80.h"
Macros
#define NUM_CONFIGS 16
#define NUM_Z80_C128MODE_CONFIGS 8
#define z80_c64io_d000_peek c64io_d000_peek
#define z80_c64io_d100_peek c64io_d100_peek
#define z80_c64io_d200_peek c64io_d200_peek
#define z80_c64io_d300_peek c64io_d300_peek
#define z80_c64io_d400_peek c64io_d400_peek
#define z80_mmu_peek mmu_peek
#define z80_vdc_peek vdc_peek
#define z80_c64io_d700_peek c64io_d700_peek
#define z80_colorram_peek colorram_peek
#define z80_cia1_peek cia1_peek
#define z80_cia2_peek cia2_peek
#define z80_c64io_de00_peek c64io_de00_peek
#define z80_c64io_df00_peek c64io_df00_peek
#define result(var)
Functions
uint8_t bios_read (uint16_t addr)
Generic memory access.
void bios_store (uint16_t addr, uint8_t value)
static uint8_t read_unconnected_io (uint16_t addr)
static void store_unconnected_io (uint16_t addr, uint8_t value)
static uint8_t z80_c64io_d000_read (uint16_t adr)
static void z80_c64io_d000_store (uint16_t adr, uint8_t val)
static uint8_t z80_c64io_d100_read (uint16_t adr)
static void z80_c64io_d100_store (uint16_t adr, uint8_t val)
static uint8_t z80_c64io_d200_read (uint16_t adr)
static void z80_c64io_d200_store (uint16_t adr, uint8_t val)
static uint8_t z80_c64io_d300_read (uint16_t adr)
static void z80_c64io_d300_store (uint16_t adr, uint8_t val)
static uint8_t z80_c64io_d400_read (uint16_t adr)
static void z80_c64io_d400_store (uint16_t adr, uint8_t val)
static uint8_t z80_mmu_read (uint16_t adr)
static void z80_mmu_store (uint16_t adr, uint8_t val)
static uint8_t z80_vdc_read (uint16_t adr)
static void z80_vdc_store (uint16_t adr, uint8_t val)
static uint8_t z80_c64io_d700_read (uint16_t adr)
static void z80_c64io_d700_store (uint16_t adr, uint8_t val)
static uint8_t z80_colorram_read (uint16_t adr)
static void z80_colorram_store (uint16_t adr, uint8_t val)
static uint8_t z80_cia1_read (uint16_t adr)
static void z80_cia1_store (uint16_t adr, uint8_t val)
static uint8_t z80_cia2_read (uint16_t adr)
static void z80_cia2_store (uint16_t adr, uint8_t val)
static uint8_t z80_c64io_de00_read (uint16_t adr)
static void z80_c64io_de00_store (uint16_t adr, uint8_t val)
static uint8_t z80_c64io_df00_read (uint16_t adr)
static void z80_c64io_df00_store (uint16_t adr, uint8_t val)
static uint8_t z80mem_lo_rom_area_read (uint16_t adr)
static uint8_t z80mem_lo_rom_area_peek (uint16_t adr)
static void z80mem_lo_rom_area_store (uint16_t adr, uint8_t val)
static uint8_t z80mem_mid_rom_area_read (uint16_t adr)
static uint8_t z80mem_mid_rom_area_peek (uint16_t adr)
static void z80mem_mid_rom_area_store (uint16_t adr, uint8_t val)
static uint8_t z80mem_editor_rom_area_read (uint16_t adr)
static uint8_t z80mem_editor_rom_area_peek (uint16_t adr)
static void z80mem_editor_rom_area_store (uint16_t adr, uint8_t val)
static uint8_t z80mem_chargen_rom_area_read (uint16_t adr)
static uint8_t z80mem_chargen_rom_area_peek (uint16_t adr)
static void z80mem_chargen_rom_area_store (uint16_t adr, uint8_t val)
static uint8_t z80mem_hi_rom_area_read (uint16_t adr)
static uint8_t z80mem_hi_rom_area_peek (uint16_t adr)
static void z80mem_hi_rom_area_store (uint16_t adr, uint8_t val)
static uint8_t z80_io_ram_bank0_read (uint16_t adr)
in() from $0000-$0fff in bank 0 get translated to memory read from RAM at $d000-$dfff
static void z80_io_ram_bank0_store (uint16_t adr, uint8_t val)
out() to $0000-$0fff in bank 0 get translated to memory store to RAM at $d000-$dfff
static uint8_t c64mode_colorram_read (uint16_t adr)
static void c64mode_colorram_store (uint16_t adr, uint8_t val)
static void z80_c64mode_ffxx_store (uint16_t addr, uint8_t value)
void z80mem_initialize (void)
void z80mem_update_config (int config)
int z80mem_load (void)
uint8_t z80mem_peek_with_config (int config, uint16_t addr, void *context)
"config" here is between 0 and 15
Variables
uint8_t z80bios_rom [0x1000]
Z80 boot BIOS.
static log_t z80mem_log = ((log_t)-1)
Logging.
read_func_ptr_t * _z80mem_read_tab_ptr
Pointers to the currently used memory read and write tables.
store_func_ptr_t * _z80mem_write_tab_ptr
uint8_t ** _z80mem_read_base_tab_ptr
int * z80mem_read_limit_tab_ptr
int z80mem_config
static store_func_ptr_t mem_write_tab [16][0x101]
Memory read and write tables.
static read_func_ptr_t mem_read_tab [16][0x101]
static uint8_t * mem_read_base_tab [16][0x101]
static int mem_read_limit_tab [16][0x101]
store_func_ptr_t io_write_tab [0x101]
read_func_ptr_t io_read_tab [0x101]
static int c64mode_bit = 0
Detailed Description
Z80 memory handling.
Author
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Macro Definition Documentation
NUM_CONFIGS
#define NUM_CONFIGS 16
NUM_Z80_C128MODE_CONFIGS
#define NUM_Z80_C128MODE_CONFIGS 8
result
#define result (var)
Value:
    res = var;           \
    ram_bank = old_bank; \
    return res;
z80_c64io_d000_peek
#define z80_c64io_d000_peek c64io_d000_peek
z80_c64io_d100_peek
#define z80_c64io_d100_peek c64io_d100_peek
z80_c64io_d200_peek
#define z80_c64io_d200_peek c64io_d200_peek
z80_c64io_d300_peek
#define z80_c64io_d300_peek c64io_d300_peek
z80_c64io_d400_peek
#define z80_c64io_d400_peek c64io_d400_peek
z80_c64io_d700_peek
#define z80_c64io_d700_peek c64io_d700_peek
z80_c64io_de00_peek
#define z80_c64io_de00_peek c64io_de00_peek
z80_c64io_df00_peek
#define z80_c64io_df00_peek c64io_df00_peek
z80_cia1_peek
#define z80_cia1_peek cia1_peek
z80_cia2_peek
#define z80_cia2_peek cia2_peek
z80_colorram_peek
#define z80_colorram_peek colorram_peek
z80_mmu_peek
#define z80_mmu_peek mmu_peek
z80_vdc_peek
#define z80_vdc_peek vdc_peek
Function Documentation
bios_read()
uint8_t bios_read (uint16_t addr)
Generic memory access.
Referenced by c128memrom_rom_read(), mem_bank_read(), z80mem_initialize(), and z80mem_peek_with_config().
bios_store()
void bios_store (uint16_t addr, uint8_t value)
Referenced by c128memrom_rom_store().
c64mode_colorram_read()
static uint8_t c64mode_colorram_read (uint16_t adr) static
Referenced by z80mem_initialize().
c64mode_colorram_store()
static void c64mode_colorram_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
read_unconnected_io()
static uint8_t read_unconnected_io (uint16_t addr) static
Referenced by z80mem_initialize(), and z80mem_update_config().
store_unconnected_io()
static void store_unconnected_io (uint16_t addr, uint8_t value) static
Referenced by z80mem_initialize(), and z80mem_update_config().
z80_c64io_d000_read()
static uint8_t z80_c64io_d000_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_c64io_d000_store()
static void z80_c64io_d000_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80_c64io_d100_read()
static uint8_t z80_c64io_d100_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_c64io_d100_store()
static void z80_c64io_d100_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80_c64io_d200_read()
static uint8_t z80_c64io_d200_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_c64io_d200_store()
static void z80_c64io_d200_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80_c64io_d300_read()
static uint8_t z80_c64io_d300_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_c64io_d300_store()
static void z80_c64io_d300_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80_c64io_d400_read()
static uint8_t z80_c64io_d400_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_c64io_d400_store()
static void z80_c64io_d400_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80_c64io_d700_read()
static uint8_t z80_c64io_d700_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_c64io_d700_store()
static void z80_c64io_d700_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80_c64io_de00_read()
static uint8_t z80_c64io_de00_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_c64io_de00_store()
static void z80_c64io_de00_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80_c64io_df00_read()
static uint8_t z80_c64io_df00_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_c64io_df00_store()
static void z80_c64io_df00_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80_c64mode_ffxx_store()
static void z80_c64mode_ffxx_store (uint16_t addr, uint8_t value) static
Referenced by z80mem_initialize().
z80_cia1_read()
static uint8_t z80_cia1_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_cia1_store()
static void z80_cia1_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80_cia2_read()
static uint8_t z80_cia2_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_cia2_store()
static void z80_cia2_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80_colorram_read()
static uint8_t z80_colorram_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_colorram_store()
static void z80_colorram_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80_io_ram_bank0_read()
static uint8_t z80_io_ram_bank0_read (uint16_t adr) static
in() from $0000-$0fff in bank 0 get translated to memory read from RAM at $d000-$dfff
Referenced by z80mem_initialize().
z80_io_ram_bank0_store()
static void z80_io_ram_bank0_store (uint16_t adr, uint8_t val) static
out() to $0000-$0fff in bank 0 get translated to memory store to RAM at $d000-$dfff
Referenced by z80mem_initialize().
z80_mmu_read()
static uint8_t z80_mmu_read (uint16_t adr) static
Referenced by z80mem_update_config().
z80_mmu_store()
static void z80_mmu_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_update_config().
z80_vdc_read()
static uint8_t z80_vdc_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80_vdc_store()
static void z80_vdc_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80mem_chargen_rom_area_peek()
static uint8_t z80mem_chargen_rom_area_peek (uint16_t adr) static
Z80 in 128 mode can't see charrom; see bug #1987
Referenced by z80mem_peek_with_config().
z80mem_chargen_rom_area_read()
static uint8_t z80mem_chargen_rom_area_read (uint16_t adr) static
Z80 in 128 mode can't see charrom; see bug #1987
Referenced by z80mem_initialize().
z80mem_chargen_rom_area_store()
static void z80mem_chargen_rom_area_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80mem_editor_rom_area_peek()
static uint8_t z80mem_editor_rom_area_peek (uint16_t adr) static
Referenced by z80mem_peek_with_config().
z80mem_editor_rom_area_read()
static uint8_t z80mem_editor_rom_area_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80mem_editor_rom_area_store()
static void z80mem_editor_rom_area_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80mem_hi_rom_area_peek()
static uint8_t z80mem_hi_rom_area_peek (uint16_t adr) static
Referenced by z80mem_peek_with_config().
z80mem_hi_rom_area_read()
static uint8_t z80mem_hi_rom_area_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80mem_hi_rom_area_store()
static void z80mem_hi_rom_area_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80mem_initialize()
void z80mem_initialize (void)
Referenced by machine_specific_reset(), and z80mem_load().
z80mem_lo_rom_area_peek()
static uint8_t z80mem_lo_rom_area_peek (uint16_t adr) static
Referenced by z80mem_peek_with_config().
z80mem_lo_rom_area_read()
static uint8_t z80mem_lo_rom_area_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80mem_lo_rom_area_store()
static void z80mem_lo_rom_area_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80mem_load()
int z80mem_load (void)
Referenced by machine_specific_init().
z80mem_mid_rom_area_peek()
static uint8_t z80mem_mid_rom_area_peek (uint16_t adr) static
Referenced by z80mem_peek_with_config().
z80mem_mid_rom_area_read()
static uint8_t z80mem_mid_rom_area_read (uint16_t adr) static
Referenced by z80mem_initialize().
z80mem_mid_rom_area_store()
static void z80mem_mid_rom_area_store (uint16_t adr, uint8_t val) static
Referenced by z80mem_initialize().
z80mem_peek_with_config()
uint8_t z80mem_peek_with_config (int config, uint16_t addr, void * context)
"config" here is between 0 and 15
Referenced by mem_peek_with_config().
z80mem_update_config()
void z80mem_update_config (int config)
Referenced by mmu_switch_to_c128mode(), mmu_switch_to_c64mode(), and z80mem_initialize().
Variable Documentation
_z80mem_read_base_tab_ptr
uint8_t** _z80mem_read_base_tab_ptr
Referenced by z80mem_read_base(), and z80mem_update_config().
_z80mem_read_tab_ptr
read_func_ptr_t* _z80mem_read_tab_ptr
Pointers to the currently used memory read and write tables.
Referenced by read_unconnected_io(), z80_io_ram_bank0_read(), and z80mem_update_config().
_z80mem_write_tab_ptr
store_func_ptr_t* _z80mem_write_tab_ptr
Referenced by store_unconnected_io(), z80_io_ram_bank0_store(), and z80mem_update_config().
c64mode_bit
int c64mode_bit = 0 static
Referenced by z80mem_update_config().
io_read_tab
read_func_ptr_t io_read_tab[0x101]
Referenced by z80mem_initialize(), and z80mem_update_config().
io_write_tab
store_func_ptr_t io_write_tab[0x101]
Referenced by z80mem_initialize(), and z80mem_update_config().
mem_read_base_tab
uint8_t* mem_read_base_tab[16][0x101] static
Referenced by z80mem_initialize(), and z80mem_update_config().
mem_read_limit_tab
int mem_read_limit_tab[16][0x101] static
Referenced by z80mem_initialize(), and z80mem_update_config().
mem_read_tab
read_func_ptr_t mem_read_tab[16][0x101] static
Referenced by z80mem_initialize(), and z80mem_update_config().
mem_write_tab
store_func_ptr_t mem_write_tab[16][0x101] static
Memory read and write tables.
Referenced by z80mem_initialize(), and z80mem_update_config().
z80bios_rom
uint8_t z80bios_rom[0x1000]
Z80 boot BIOS.
Referenced by bios_read(), bios_store(), and c128rom_kernal_setup().
z80mem_config
int z80mem_config
Referenced by mem_get_current_bank_config(), and z80mem_update_config().
z80mem_log
log_t z80mem_log = ((log_t)-1) static
Logging.
Referenced by z80mem_load().
z80mem_read_limit_tab_ptr
int* z80mem_read_limit_tab_ptr
Referenced by z80mem_read_limit(), and z80mem_update_config().