vsid: alarm.c File Reference
alarm.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include "alarm.h"
#include "lib.h"
#include "log.h"
#include "types.h"
Functions
alarm_context_t * alarm_context_new (const char *name)
void alarm_context_init (alarm_context_t *context, const char *name)
void alarm_context_destroy (alarm_context_t *context)
void alarm_context_time_warp (alarm_context_t *context, CLOCK warp_amount, int warp_direction)
static void alarm_init (alarm_t *alarm, alarm_context_t *context, const char *name, alarm_callback_t callback, void *data)
alarm_t * alarm_new (alarm_context_t *context, const char *name, alarm_callback_t callback, void *data)
void alarm_destroy (alarm_t *alarm)
void alarm_unset (alarm_t *alarm)
void alarm_log_too_many_alarms (void)
Function Documentation
alarm_context_destroy()
void alarm_context_destroy (alarm_context_t * context)
Referenced by drivecpu65c02_shutdown(), drivecpu_shutdown(), and machine_maincpu_shutdown().
alarm_context_init()
void alarm_context_init (alarm_context_t * context, const char * name)
Referenced by alarm_context_new().
alarm_context_new()
alarm_context_t * alarm_context_new (const char * name)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), and machine_early_init().
alarm_context_time_warp()
void alarm_context_time_warp (alarm_context_t * context, CLOCK warp_amount, int warp_direction)
alarm_destroy()
void alarm_destroy (alarm_t * alarm)
Referenced by alarm_context_destroy(), ata_shutdown(), and OPLDestroy().
alarm_init()
static void alarm_init (alarm_t * alarm, alarm_context_t * context, const char * name, alarm_callback_t callback, void * data) static
Referenced by alarm_new().
alarm_log_too_many_alarms()
void alarm_log_too_many_alarms (void)
Referenced by alarm_set().
alarm_new()
alarm_t * alarm_new (alarm_context_t * context, const char * name, alarm_callback_t callback, void * data)
Referenced by ata_init(), c64_glue_init(), c64dtv_ps2mouse_alarm_init(), ciacore_init(), cmdhd_setup_context(), event_init(), flash040core_init(), kbdbuf_init(), keyboard_init(), myacia_init(), OPLCreate(), pc8477d_init(), riotcore_init(), rsuser_init(), tapecart_enable(), viacore_init(), vicii_fetch_init(), vicii_init(), and vicii_irq_init().
alarm_unset()
void alarm_unset (alarm_t * alarm)
Referenced by acia_set_handshake_lines(), alarm_destroy(), ata_change_power_mode(), ata_head_alarm_handler(), ata_snapshot_read_module(), ata_spindle_alarm_handler(), ata_standby_alarm_handler(), c64dtv_ps2mouse_alarm_handler(), ciacore_disable(), ciacore_intsdr(), ciacore_reset(), ciacore_set_sdr(), ciacore_snapshot_read_module(), ciat_ack_alarm(), ciat_reset(), ciat_set_alarm(), cmdhd_snapshot_read_module(), cmdmode_receive_command(), erase_alarm_handler(), event_alarm_handler(), event_playback_stop(), event_record_stop(), flash040core_reset(), flash040core_store_internal(), fmopl_alarm_A(), fmopl_alarm_B(), glue_alarm_unset(), int_acia_rx(), int_acia_tx(), kbd_retrigger_alarm(), kbdbuf_flush_alarm_triggered(), keyboard_alarm_handler(), myacia_reset(), myacia_snapshot_read_module(), myacia_store(), OPLDestroy(), OPLResetChip(), OPLWriteReg(), reset_alarm_handler(), restore_alarm_triggered(), riotcore_disable(), riotcore_int_riot(), riotcore_reset(), riotcore_snapshot_read_module(), riotcore_store(), rsuser_reset(), rsuser_write_ctrl(), schedule_t2_zero_alarm(), seek_alarm_handler(), tapecart_enable(), tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), tapecart_set_mode(), userport_rs232_enable(), viacore_disable(), viacore_reset(), viacore_snapshot_read_module(), viacore_store(), viacore_t1_zero_alarm(), viacore_t2_shift_alarm(), viacore_t2_underflow_alarm(), viacore_t2_zero_alarm(), vicii_irq_set_raster_line(), vicii_snapshot_prepare(), and vicii_snapshot_read_module().