x128: machine-bus.h File Reference
machine-bus.h File Reference
#include "types.h"
Functions
void machine_bus_init (void)
void machine_bus_init_machine (void)
int machine_bus_lib_directory (unsigned int unit, const char *pattern, uint8_t **buf)
int machine_bus_lib_read_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t *buf)
int machine_bus_lib_write_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t *buf)
unsigned int machine_bus_device_type_get (unsigned int unit)
void machine_bus_status_truedrive_set (unsigned int unit, unsigned int enable)
void machine_bus_status_drivetype_set (unsigned int unit, unsigned int enable)
void machine_bus_status_virtualdevices_set (unsigned int unit, unsigned int enable)
void machine_bus_eof_callback_set (void(*func)(void))
void machine_bus_attention_callback_set (void(*func)(void))
int machine_bus_device_attach (unsigned int unit, const char *name, int(*getf)(struct vdrive_s *, uint8_t *, unsigned int), int(*putf)(struct vdrive_s *, uint8_t, unsigned int), int(*openf)(struct vdrive_s *, const uint8_t *, unsigned int, unsigned int, struct cbmdos_cmd_parse_s *), int(*closef)(struct vdrive_s *, unsigned int), void(*flushf)(struct vdrive_s *, unsigned int), void(*listenf)(struct vdrive_s *, unsigned int))
int machine_bus_device_detach (unsigned int unit)
Detach and kill serial devices.
Function Documentation
machine_bus_attention_callback_set()
void machine_bus_attention_callback_set (void(*)(void) func)
Referenced by advance_hasdisk(), and disk_attention_callback().
machine_bus_device_attach()
int machine_bus_device_attach (unsigned int unit, const char * name, int(*)(struct vdrive_s *, uint8_t *, unsigned int) getf, int(*)(struct vdrive_s *, uint8_t, unsigned int) putf, int(*)(struct vdrive_s *, const uint8_t *, unsigned int, unsigned int, struct cbmdos_cmd_parse_s *) openf, int(*)(struct vdrive_s *, unsigned int) closef, void(*)(struct vdrive_s *, unsigned int) flushf, void(*)(struct vdrive_s *, unsigned int) listenf)
Referenced by fsdevice_attach(), interface_serial_attach(), and vdrive_iec_attach().
machine_bus_device_detach()
int machine_bus_device_detach (unsigned int unit)
Detach and kill serial devices.
Referenced by file_system_shutdown(), interface_serial_detach(), machine_bus_device_attach(), and serial_shutdown().
machine_bus_device_type_get()
unsigned int machine_bus_device_type_get (unsigned int unit)
Referenced by mon_drive_is_fsdevice().
machine_bus_eof_callback_set()
void machine_bus_eof_callback_set (void(*)(void) func)
Referenced by disk_attention_callback(), and disk_eof_callback().
machine_bus_init()
void machine_bus_init (void)
Referenced by init_main().
machine_bus_init_machine()
void machine_bus_init_machine (void)
Referenced by machine_bus_init().
machine_bus_lib_directory()
int machine_bus_lib_directory (unsigned int unit, const char * pattern, uint8_t ** buf)
machine_bus_lib_read_sector()
int machine_bus_lib_read_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t * buf)
Referenced by realimage_read_sector().
machine_bus_lib_write_sector()
int machine_bus_lib_write_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t * buf)
machine_bus_status_drivetype_set()
void machine_bus_status_drivetype_set (unsigned int unit, unsigned int enable)
Referenced by drive_resources_type(), drive_snapshot_read_module(), and driverom_load().
machine_bus_status_truedrive_set()
void machine_bus_status_truedrive_set (unsigned int unit, unsigned int enable)
Referenced by set_drive_true_emulation().
machine_bus_status_virtualdevices_set()
void machine_bus_status_virtualdevices_set (unsigned int unit, unsigned int enable)
Referenced by set_traps_enabled().