vsid: arch/gtk3/widgets/settings_sampler.c File Reference
settings_sampler.c File Reference
Widget to control sampler settings.
#include "vice.h"
#include <gtk/gtk.h>
#include "resources.h"
#include "sampler.h"
#include "vice_gtk3.h"
#include "settings_sampler.h"
Macros
#define GAIN_STEP 25
Stepping for the gain slider (when using cursor left/right)
Functions
static void on_device_changed (GtkComboBoxText *combo, gpointer user_data)
Handler for the "changed" event of the devices combo box.
static GtkWidget * create_label (const char *text)
Create left-aligned label using Pango markup.
static GtkWidget * create_device_combo (void)
Create combo box for the devices list.
GtkWidget * settings_sampler_widget_create (GtkWidget *parent)
Create widget to control sampler settings.
Detailed Description
Widget to control sampler settings.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
GAIN_STEP
#define GAIN_STEP 25
Stepping for the gain slider (when using cursor left/right)
Function Documentation
create_device_combo()
static GtkWidget * create_device_combo (void) static
Create combo box for the devices list.
Returns
GtkComboBoxText
Referenced by settings_ethernet_widget_create(), and settings_sampler_widget_create().
create_label()
static GtkWidget * create_label (const char * text) static
Create left-aligned label using Pango markup.
Parameters
[in] text label text
Returns
GtkLabel
Referenced by settings_sampler_widget_create().
on_device_changed()
static void on_device_changed (GtkComboBoxText * combo, gpointer user_data) static
Handler for the "changed" event of the devices combo box.
Parameters
[in] combo combo box with devices
[in] user_data extra data (unused)
Referenced by create_device_combo().
settings_sampler_widget_create()
GtkWidget * settings_sampler_widget_create (GtkWidget * parent)
Create widget to control sampler settings.
Parameters
[in] parent parent widget
Returns
GtkGrid
Todo:
Use resourcebrowser to control the "SampleFile" resource
< 200%
< 200%
< 100%