vsid: arch/gtk3/widgets/base/lastdir.c File Reference
lastdir.c File Reference
Last directory used wrapper code.
#include "vice.h"
#include <stdio.h>
#include <gtk/gtk.h>
#include "lastdir.h"
Functions
void lastdir_set (GtkWidget *widget, gchar **last_dir, gchar **last_file)
Set directory of the GtkFileChooser widget using *last.
void lastdir_update (GtkWidget *widget, gchar **last_dir, gchar **last_file)
Update the last used directory and/or filename.
void lastdir_update_raw (char *dirname, char **last_dir, char *filename, char **last_file)
Update last used directory and/or filename.
void lastdir_shutdown (gchar **last_dir, gchar **last_file)
Free memory used by *last_dir and last_file.
Detailed Description
Last directory used wrapper code.
Simple code to handle last used directories for file dialogs.
Since Gtk3 refuses to remember the last used directory and the last used file for a file dialog (or even present a shitty 'last used files' list), we need something to remember the last used directory and last used file on a per-dialog basis.
This code will handle that, with a very little extra code. Currently this only works with GtkFileChooser-derived widgets, but that's basically all we use in Gtk3-VICE at the moment.
The basic API is this:
In the code using this API, declare static gchar * variables to hold the last used directory and last used file.
For example:
static gchar *last_dir = NULL;
static gchar *last_file = NULL;
In the dialog building code, add a call to lastdir_set():
lastdir_set(dialog, &last_dir, &last_file);
Whenever the last directory needs to be updated, for example when the user has selected a file, add a call to lastdir_update():
lastdir_update(dialog, &last_dir, &last_file);
And finally when shutting down the dialog/UI, don't forget to call
lastdir_shutdown(&last_dir, &last_file);
to clean up the resources used.
Both last_dir and last_file are allowed to be NULL, in which case the code ignores the directory or filename components of a dialog.
Maybe just look at src/arch/gtk3/uidiskattach.c to get an idea.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
lastdir_set()
void lastdir_set (GtkWidget * widget, gchar ** last_dir, gchar ** last_file)
Set directory of the GtkFileChooser widget using *last.
Parameters
[in,out] widget GtkFileChooser widget
[in] last_dir pointer to last directory string pointer
[in] last_file pointer to last file selected in directory
Referenced by cart_dialog_internal(), create_disk_attach_dialog(), create_sid_attach_dialog(), create_smart_attach_dialog(), create_tape_attach_dialog(), on_filename_icon_press(), on_load_romset_clicked(), on_save_clicked(), on_save_custom_keymap_clicked(), on_save_romset_clicked(), save_audio_recording_handler(), save_screenshot_handler(), save_video_recording_handler(), settings_load_from_action(), settings_save_to_action(), vsid_playlist_add_dialog_create(), vsid_playlist_load(), and vsid_playlist_save().
lastdir_shutdown()
void lastdir_shutdown (gchar ** last_dir, gchar ** last_file)
Free memory used by *last_dir and last_file.
Clean up memory used by last used directory and filename.
Parameters
[in] last_dir location of last used directory
[in] last_file location of last used filename
Referenced by actions_settings_shutdown(), cart_image_widgets_shutdown(), on_destroy(), settings_keyboard_widget_shutdown(), ui_cart_shutdown(), ui_disk_attach_shutdown(), ui_media_shutdown(), ui_smart_attach_shutdown(), ui_tape_attach_shutdown(), uisidattach_shutdown(), and vsid_playlist_add_dialog_free().
lastdir_update()
void lastdir_update (GtkWidget * widget, gchar ** last_dir, gchar ** last_file)
Update the last used directory and/or filename.
Updates *last to the directory currently used by widget
Parameters
[in] widget GtkFileChooser widget
[out] last_dir pointer to string pointer containing the last used dir
[out] last_file pointer to string pointer containing the last used file
Referenced by do_attach(), do_autostart(), do_smart_attach(), on_load_romset_callback(), on_open_response(), on_response(), on_save_audio_filename(), on_save_response(), on_save_screenshot_filename(), on_save_video_filename(), on_settings_save_to_filename(), playlist_load_callback(), playlist_save_dialog_callback(), save_filename_callback(), and settings_load_filename_callback().
lastdir_update_raw()
void lastdir_update_raw (char * dirname, char ** last_dir, char * filename, char ** last_file)
Update last used directory and/or filename.
Store new values for dir and filename freeing the old data.
If NULL is passed the related object will only be freed and set to NULL.
Parameters
[in] dirname new directory
[in] last_dir object to copy dirname to
[in] filename new filename
[in] last_file object to copy filename to
Referenced by on_response().