vsid: fileio.h File Reference
fileio.h File Reference
#include "types.h"
Data Structures
struct fileio_info_s
Macros
#define FILEIO_COMMAND_READ 0
#define FILEIO_COMMAND_READ_WRITE 1
#define FILEIO_COMMAND_WRITE 2
Will not overwrite existing file.
#define FILEIO_COMMAND_OVERWRITE 3
Overwrites existing file, if any.
#define FILEIO_COMMAND_APPEND 4
#define FILEIO_COMMAND_APPEND_READ 5
#define FILEIO_COMMAND_STAT 6
works with directories
#define FILEIO_COMMAND_MASK 15
#define FILEIO_COMMAND_FSNAME 16
#define FILEIO_FORMAT_RAW (1 << 0)
#define FILEIO_FORMAT_P00 (1 << 1)
#define FILEIO_TYPE_DEL 0
should match CBMDOS_FT_xxx
#define FILEIO_TYPE_SEQ 1
#define FILEIO_TYPE_PRG 2
#define FILEIO_TYPE_USR 3
#define FILEIO_TYPE_REL 4
#define FILEIO_TYPE_CBM 5
#define FILEIO_TYPE_DIR 6
#define FILEIO_TYPE_ANY 255
#define FILEIO_FILE_OK 0
#define FILEIO_FILE_NOT_FOUND 1
#define FILEIO_FILE_EXISTS 2
#define FILEIO_FILE_PERMISSION 3
#define FILEIO_FILE_SCRATCHED 4
Typedefs
typedef struct fileio_info_s fileio_info_t
Functions
fileio_info_t * fileio_open (const char *file_name, const char *path, unsigned int format, unsigned int command, unsigned int type, int *reclenp)
void fileio_close (fileio_info_t *info)
unsigned int fileio_read (fileio_info_t *info, uint8_t *buf, unsigned int len)
unsigned int fileio_write (fileio_info_t *info, uint8_t *buf, unsigned int len)
unsigned int fileio_ferror (fileio_info_t *info)
unsigned int fileio_rename (const char *src_name, const char *dest_name, const char *path, unsigned int format)
unsigned int fileio_scratch (const char *file_name, const char *path, unsigned int format)
unsigned int fileio_get_bytes_left (fileio_info_t *info)
unsigned int fileio_seek (fileio_info_t *info, off_t offset, int whence)
unsigned int fileio_tell (fileio_info_t *info)
Macro Definition Documentation
FILEIO_COMMAND_APPEND
#define FILEIO_COMMAND_APPEND 4
FILEIO_COMMAND_APPEND_READ
#define FILEIO_COMMAND_APPEND_READ 5
FILEIO_COMMAND_FSNAME
#define FILEIO_COMMAND_FSNAME 16
FILEIO_COMMAND_MASK
#define FILEIO_COMMAND_MASK 15
FILEIO_COMMAND_OVERWRITE
#define FILEIO_COMMAND_OVERWRITE 3
Overwrites existing file, if any.
FILEIO_COMMAND_READ
#define FILEIO_COMMAND_READ 0
FILEIO_COMMAND_READ_WRITE
#define FILEIO_COMMAND_READ_WRITE 1
FILEIO_COMMAND_STAT
#define FILEIO_COMMAND_STAT 6
works with directories
FILEIO_COMMAND_WRITE
#define FILEIO_COMMAND_WRITE 2
Will not overwrite existing file.
FILEIO_FILE_EXISTS
#define FILEIO_FILE_EXISTS 2
FILEIO_FILE_NOT_FOUND
#define FILEIO_FILE_NOT_FOUND 1
FILEIO_FILE_OK
#define FILEIO_FILE_OK 0
FILEIO_FILE_PERMISSION
#define FILEIO_FILE_PERMISSION 3
FILEIO_FILE_SCRATCHED
#define FILEIO_FILE_SCRATCHED 4
FILEIO_FORMAT_P00
#define FILEIO_FORMAT_P00 (1 << 1)
FILEIO_FORMAT_RAW
#define FILEIO_FORMAT_RAW (1 << 0)
FILEIO_TYPE_ANY
#define FILEIO_TYPE_ANY 255
FILEIO_TYPE_CBM
#define FILEIO_TYPE_CBM 5
FILEIO_TYPE_DEL
#define FILEIO_TYPE_DEL 0
should match CBMDOS_FT_xxx
FILEIO_TYPE_DIR
#define FILEIO_TYPE_DIR 6
FILEIO_TYPE_PRG
#define FILEIO_TYPE_PRG 2
FILEIO_TYPE_REL
#define FILEIO_TYPE_REL 4
FILEIO_TYPE_SEQ
#define FILEIO_TYPE_SEQ 1
FILEIO_TYPE_USR
#define FILEIO_TYPE_USR 3
Typedef Documentation
fileio_info_t
typedef struct fileio_info_s fileio_info_t
Function Documentation
fileio_close()
void fileio_close (fileio_info_t * info)
Referenced by autostart_prg(), command_directory_get(), and fsdevice_close().
fileio_ferror()
unsigned int fileio_ferror (fileio_info_t * info)
Referenced by command_read(), and relative_read().
fileio_get_bytes_left()
unsigned int fileio_get_bytes_left (fileio_info_t * info)
Referenced by fsdevice_relative_switch_record(), and load_prg().
fileio_open()
fileio_info_t * fileio_open (const char * file_name, const char * path, unsigned int format, unsigned int command, unsigned int type, int * reclenp)
Referenced by autostart_prg(), command_directory_get(), and fsdevice_open_file().
fileio_read()
unsigned int fileio_read (fileio_info_t * info, uint8_t * buf, unsigned int len)
Referenced by command_read(), fsdevice_relative_switch_record(), load_prg(), and relative_read().
fileio_rename()
unsigned int fileio_rename (const char * src_name, const char * dest_name, const char * path, unsigned int format)
Referenced by fsdevice_flush_rename().
fileio_scratch()
unsigned int fileio_scratch (const char * file_name, const char * path, unsigned int format)
Referenced by fsdevice_flush_scratch().
fileio_seek()
unsigned int fileio_seek (fileio_info_t * info, off_t offset, int whence)
Referenced by fsdevice_relative_pad_record(), fsdevice_relative_switch_record(), fsdevice_relfile_extend_if_needed(), and fsdevice_write().
fileio_tell()
unsigned int fileio_tell (fileio_info_t * info)
Referenced by fsdevice_relfile_extend_if_needed().
fileio_write()
unsigned int fileio_write (fileio_info_t * info, uint8_t * buf, unsigned int len)
Referenced by fsdevice_relative_pad_record(), fsdevice_relfile_extend_if_needed(), and fsdevice_write().