vsid: c1541-stubs.c File Reference
c1541-stubs.c File Reference
#include "vice.h"
#include "archdep_defs.h"
#include <stdbool.h>
#include <inttypes.h>
#include "attach.h"
#include "cartridge.h"
#include "cmdline.h"
#include "crt.h"
#include "drive.h"
#include "imagecontents.h"
#include "kbd.h"
#include "machine.h"
#include "machine-bus.h"
#include "machine-drive.h"
#include "main.h"
#include "mainlock.h"
#include "network.h"
#include "serial.h"
#include "tape.h"
#include "vdrive.h"
#include "vice-event.h"
#include "vsync.h"
#include "uiapi.h"
Functions
void cartridge_detach_image (int type)
called from resources_set_defaults()
void cartridge_unset_default (void)
called from resources_set_defaults()
int cmdline_register_options (const cmdline_option_t *c)
int network_connected (void)
int network_get_mode (void)
void network_event_record (unsigned int type, void *data, unsigned int size)
void event_record_in_list (event_list_state_t *list, unsigned int type, void *data, unsigned int size)
void ui_error (const char *format,...)
Print an error message.
void main_exit (void)
int machine_bus_device_attach (unsigned int unit, const char *name, int(*getf)(struct vdrive_s *, uint8_t *, unsigned int), int(*putf)(struct vdrive_s *, uint8_t, unsigned int), int(*openf)(struct vdrive_s *, const uint8_t *, unsigned int, unsigned int, struct cbmdos_cmd_parse_s *), int(*closef)(struct vdrive_s *, unsigned int), void(*flushf)(struct vdrive_s *, unsigned int), void(*listenf)(struct vdrive_s *, unsigned int))
snapshot_module_t * snapshot_module_create (snapshot_t *s, const char *name, uint8_t major_version, uint8_t minor_version)
snapshot_module_t * snapshot_module_open (snapshot_t *s, const char *name, uint8_t *major_version_return, uint8_t *minor_version_return)
int snapshot_module_close (snapshot_module_t *m)
int snapshot_module_read_dword_into_int (snapshot_module_t *m, int *value_return)
int snapshot_module_read_dword_into_uint (snapshot_module_t *m, unsigned int *value_return)
int snapshot_module_write_byte_array (snapshot_module_t *m, const uint8_t *data, unsigned int num)
int snapshot_module_read_byte_array (snapshot_module_t *m, uint8_t *b_return, unsigned int num)
int snapshot_module_write_word (snapshot_module_t *m, uint16_t data)
int snapshot_module_read_word_into_int (snapshot_module_t *m, int *value_return)
int snapshot_version_is_smaller (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
int snapshot_version_is_equal (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
int snapshot_version_is_bigger (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
void snapshot_set_error (int error)
int snapshot_get_error (void)
void vsync_suspend_speed_eval (void)
struct image_contents_s * machine_diskcontents_bus_read (unsigned int unit)
int machine_bus_lib_directory (unsigned int unit, const char *pattern, uint8_t **buf)
int machine_bus_lib_read_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t *buf)
int machine_bus_lib_write_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t *buf)
unsigned int machine_bus_device_type_get (unsigned int unit)
int machine_drive_rom_check_loaded (unsigned int type)
void machine_drive_flush (void)
const char * machine_get_name (void)
Get "real" name for machine.
uint8_t machine_tape_behaviour (void)
char * kbd_get_menu_keyname (void)
Only here for c1541-stubs.c, not used in the Gtk3 UI.
int crt_getid (const char *filename)
int drive_get_disk_drive_type (int dnr)
void tape_image_detach_all (void)
void file_system_detach_disk_all (void)
Variables
const char machine_name [] = "C1541"
Machine name.
int machine_class = 0
Machine class.
Function Documentation
cartridge_detach_image()
void cartridge_detach_image (int type)
called from resources_set_defaults()
detaches/disables the cartridge with the associated id.
Referenced by cart_detach_action(), io_source_detach(), machine_specific_shutdown(), and resources_set_defaults().
cartridge_unset_default()
void cartridge_unset_default (void)
called from resources_set_defaults()
Referenced by confirm_detach_callback(), on_remove_clicked(), and resources_set_defaults().
cmdline_register_options()
int cmdline_register_options (const cmdline_option_t * c)
Referenced by artstudiodrv_cmdline_options_init(), autostart_cmdline_options_init(), c64_256k_cmdline_options_init(), c64_cmdline_options_init(), c64_glue_cmdline_options_init(), cartio_cmdline_options_init(), debug_cmdline_options_init(), debugcart_cmdline_options_init(), drive_cmdline_options_init(), driver_select_init_cmdline_options(), driver_select_userport_init_cmdline_options(), event_cmdline_options_init(), ffmpegexedrv_cmdline_options_init(), file_system_cmdline_options_init(), fliplist_cmdline_options_init(), fsdevice_cmdline_options_init(), iec_cmdline_options_init(), initcmdline_init(), interface_serial_init_cmdline_options(), kbdbuf_cmdline_options_init(), keyboard_cmdline_options_init(), keymap_cmdline_options_init(), koaladrv_cmdline_options_init(), log_cmdline_options_init(), machine_common_cmdline_options_init(), memory_hacks_cmdline_options_init(), minipaintdrv_cmdline_options_init(), monitor_binary_cmdline_options_init(), monitor_cmdline_options_init(), monitor_network_cmdline_options_init(), mouse_ps2_cmdline_options_init(), myacia_init_cmdline_options(), network_cmdline_options_init(), output_select_init_cmdline_options(), output_select_userport_init_cmdline_options(), output_text_init_cmdline_options(), plus256k_cmdline_options_init(), plus60k_cmdline_options_init(), psid_cmdline_options_init(), ram_cmdline_options_init(), raster_cmdline_options_chip_init(), romset_cmdline_options_init(), rs232drv_cmdline_options_init(), rsuser_cmdline_options_init(), sampler_cmdline_options_init(), sampler_file_cmdline_options_init(), serial_iec_device_cmdline_options_init(), sid_cmdline_options_init(), sound_cmdline_options_init(), sysfile_cmdline_options_init(), tapecart_cmdline_options_init(), tapeport_cmdline_options_init(), tapertc_cmdline_options_init(), traps_cmdline_options_init(), ui_cmdline_options_init(), ui_hotkeys_cmdline_options_init(), userport_cmdline_options_init(), userport_rtc_58321a_cmdline_options_init(), userport_rtc_ds1307_cmdline_options_init(), vicii_cmdline_options_init(), video_cmdline_options_chip_init(), vsid_cmdline_options_init(), vsync_cmdline_options_init(), and zmbvdrv_cmdline_options_init().
crt_getid()
int crt_getid (const char * filename)
Referenced by disk_image_check_for_dhd().
drive_get_disk_drive_type()
int drive_get_disk_drive_type (int dnr)
Referenced by autostart_prg_with_disk_image(), and fsimage_read_dxx_image().
event_record_in_list()
void event_record_in_list (event_list_state_t * list, unsigned int type, void * data, unsigned int size)
Referenced by network_create_event_list(), network_event_record(), and resources_get_event_safe_list().
file_system_detach_disk_all()
void file_system_detach_disk_all (void)
kbd_get_menu_keyname()
char * kbd_get_menu_keyname (void)
Only here for c1541-stubs.c, not used in the Gtk3 UI.
Returns
NULL
Referenced by archdep_extra_title_text().
machine_bus_device_attach()
int machine_bus_device_attach (unsigned int unit, const char * name, int(*)(struct vdrive_s *, uint8_t *, unsigned int) getf, int(*)(struct vdrive_s *, uint8_t, unsigned int) putf, int(*)(struct vdrive_s *, const uint8_t *, unsigned int, unsigned int, struct cbmdos_cmd_parse_s *) openf, int(*)(struct vdrive_s *, unsigned int) closef, void(*)(struct vdrive_s *, unsigned int) flushf, void(*)(struct vdrive_s *, unsigned int) listenf)
Referenced by fsdevice_attach(), interface_serial_attach(), and vdrive_iec_attach().
machine_bus_device_type_get()
unsigned int machine_bus_device_type_get (unsigned int unit)
Referenced by mon_drive_is_fsdevice().
machine_bus_lib_directory()
int machine_bus_lib_directory (unsigned int unit, const char * pattern, uint8_t ** buf)
machine_bus_lib_read_sector()
int machine_bus_lib_read_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t * buf)
Referenced by realimage_read_sector().
machine_bus_lib_write_sector()
int machine_bus_lib_write_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t * buf)
machine_diskcontents_bus_read()
struct image_contents_s * machine_diskcontents_bus_read (unsigned int unit)
machine_drive_flush()
void machine_drive_flush (void)
Referenced by diskcontents_block_read(), and vdrive_internal_format_disk_image().
machine_drive_rom_check_loaded()
int machine_drive_rom_check_loaded (unsigned int type)
Referenced by disk_image_check_for_dhd(), drive_check_type(), drive_set_disk_drive_type(), and driverom_load_images().
machine_get_name()
const char * machine_get_name (void)
Get "real" name for machine.
May differ from machine_name.
Referenced by actions_speed_setup_ui(), archdep_default_autostart_disk_image_file_name(), archdep_default_fliplist_file_name(), archdep_default_joymap_file_name(), autostart_snapshot(), c64_snapshot_read(), c64_snapshot_write(), event_playback_start_trap(), init_resources(), mouse_grab_toggle_action(), quicksnap_filename(), save_header(), and ui_create_main_window().
machine_tape_behaviour()
uint8_t machine_tape_behaviour (void)
< tape interrupt is falling-edge triggered, normal tape blocks end with a long and a short pulse
Referenced by tap_cbm_read_block_once(), and tap_cbm_read_header().
main_exit()
void main_exit (void)
Referenced by actually_exit().
network_connected()
int network_connected (void)
Referenced by autostart_autodetect(), autostart_disk(), autostart_prg(), autostart_snapshot(), autostart_tape(), file_system_attach_disk(), file_system_detach_disk(), kbd_key_pressed(), keyboard_key_clear(), keyboard_latch_matrix(), keyboard_restore_pressed(), keyboard_restore_released(), machine_trigger_reset(), resources_set_int(), resources_set_string(), resources_set_value(), resources_toggle(), tape_image_attach(), tape_image_detach(), and vsync_do_vsync().
network_event_record()
void network_event_record (unsigned int type, void * data, unsigned int size)
Referenced by file_system_detach_disk(), kbd_key_pressed(), keyboard_key_clear(), keyboard_restore_pressed(), keyboard_restore_released(), machine_trigger_reset(), resource_record_event(), and tape_image_detach().
network_get_mode()
int network_get_mode (void)
Referenced by create_combo_box(), create_netplay_enable_widget(), netplay_update_status(), on_combo_changed(), on_netplay_notify_active(), resources_set_int(), resources_set_string(), resources_set_value(), and resources_toggle().
snapshot_get_error()
int snapshot_get_error (void)
Referenced by machine_read_snapshot(), and machine_write_snapshot().
snapshot_module_close()
int snapshot_module_close (snapshot_module_t * m)
Referenced by ata_snapshot_read_module(), ata_snapshot_write_module(), c64_256k_snapshot_read(), c64_256k_snapshot_write(), c64_glue_snapshot_read_module(), c64_glue_snapshot_write_module(), c64_snapshot_read_module(), c64_snapshot_read_rom_module(), c64_snapshot_write_module(), c64_snapshot_write_rom_module(), ciacore_snapshot_read_module(), ciacore_snapshot_write_module(), cmdhd_snapshot_read_module(), cmdhd_snapshot_write_module(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), drive_snapshot_write_gcrimage_module(), drive_snapshot_write_image_module(), drive_snapshot_write_module(), drive_snapshot_write_p64image_module(), drivecpu65c02_snapshot_read_module(), drivecpu65c02_snapshot_write_module(), drivecpu_snapshot_read_module(), drivecpu_snapshot_write_module(), driverom_snapshot_read(), driverom_snapshot_write(), dtlbasic_read_snapshot(), dtlbasic_write_snapshot(), eeprom_snapshot_read_module(), eeprom_snapshot_write_module(), event_snapshot_read_module(), event_snapshot_write_module(), fdd_snapshot_read_module(), fdd_snapshot_write_module(), flash040core_snapshot_read_module(), flash040core_snapshot_write_module(), fsdrive_snapshot_read_module(), fsdrive_snapshot_write_module(), keyboard_snapshot_read_module(), keyboard_snapshot_write_module(), m93c86_snapshot_read_module(), m93c86_snapshot_write_module(), maincpu_snapshot_read_module(), maincpu_snapshot_write_module(), memhacks_snapshot_read_modules(), memhacks_snapshot_write_modules(), mmc_snapshot_read_module(), mmc_snapshot_write_module(), myacia_snapshot_read_module(), myacia_snapshot_write_module(), mypia_snapshot_read_module(), mypia_snapshot_write_module(), plus256k_snapshot_read(), plus256k_snapshot_write(), plus60k_snapshot_read(), plus60k_snapshot_write(), riotcore_snapshot_read_module(), riotcore_snapshot_write_module(), scsi_snapshot_read_module(), scsi_snapshot_write_module(), sid_snapshot_read_module_extended(), sid_snapshot_read_module_simple(), sid_snapshot_write_module_extended(), sid_snapshot_write_module_simple(), spi_flash_snapshot_read_module(), spi_flash_snapshot_write_module(), t6721_snapshot_read_module(), t6721_snapshot_write_module(), tape_snapshot_read_module(), tape_snapshot_read_tapimage_module(), tape_snapshot_write_module(), tape_snapshot_write_tapimage_module(), tapeport_snapshot_read_module(), tapeport_snapshot_write_module(), tapertc_read_snapshot(), tapertc_write_snapshot(), tpicore_snapshot_read_module(), tpicore_snapshot_write_module(), userport_8bss_read_snapshot_module(), userport_8bss_write_snapshot_module(), userport_dac_read_snapshot_module(), userport_dac_write_snapshot_module(), userport_digimax_read_snapshot_module(), userport_digimax_write_snapshot_module(), userport_io_sim_read_snapshot_module(), userport_io_sim_write_snapshot_module(), userport_joystick_cga_read_snapshot_module(), userport_joystick_cga_write_snapshot_module(), userport_joystick_hit_read_snapshot_module(), userport_joystick_hit_write_snapshot_module(), userport_joystick_kingsoft_read_snapshot_module(), userport_joystick_kingsoft_write_snapshot_module(), userport_joystick_starbyte_read_snapshot_module(), userport_joystick_starbyte_write_snapshot_module(), userport_joystick_synergy_read_snapshot_module(), userport_joystick_synergy_write_snapshot_module(), userport_joystick_woj_read_snapshot_module(), userport_joystick_woj_write_snapshot_module(), userport_petscii_read_snapshot_module(), userport_petscii_write_snapshot_module(), userport_printer_read_snapshot_module(), userport_printer_write_snapshot_module(), userport_rtc_read_snapshot_module(), userport_rtc_write_snapshot_module(), userport_snapshot_read_module(), userport_snapshot_write_module(), userport_superpad64_read_snapshot_module(), userport_superpad64_write_snapshot_module(), vdrive_snapshot_module_read(), vdrive_snapshot_module_write(), viacore_snapshot_read_module(), viacore_snapshot_write_module(), vicii_snapshot_read_module(), vicii_snapshot_write_module(), wd1770_snapshot_read_module(), wd1770_snapshot_write_module(), ym3526_snapshot_read_module(), and ym3526_snapshot_write_module().
snapshot_module_create()
snapshot_module_t * snapshot_module_create (snapshot_t * s, const char * name, uint8_t major_version, uint8_t minor_version)
Referenced by ata_snapshot_write_module(), c64_256k_snapshot_write(), c64_glue_snapshot_write_module(), c64_snapshot_write_module(), c64_snapshot_write_rom_module(), ciacore_snapshot_write_module(), cmdhd_snapshot_write_module(), drive_snapshot_write_gcrimage_module(), drive_snapshot_write_image_module(), drive_snapshot_write_module(), drive_snapshot_write_p64image_module(), drivecpu65c02_snapshot_write_module(), drivecpu_snapshot_write_module(), driverom_snapshot_write(), dtlbasic_write_snapshot(), eeprom_snapshot_write_module(), event_snapshot_write_module(), fdd_snapshot_write_module(), flash040core_snapshot_write_module(), fsdrive_snapshot_write_module(), keyboard_snapshot_write_module(), m93c86_snapshot_write_module(), maincpu_snapshot_write_module(), memhacks_snapshot_write_modules(), mmc_snapshot_write_module(), myacia_snapshot_write_module(), mypia_snapshot_write_module(), plus256k_snapshot_write(), plus60k_snapshot_write(), riotcore_snapshot_write_module(), scsi_snapshot_write_module(), sid_snapshot_write_module_extended(), sid_snapshot_write_module_simple(), spi_flash_snapshot_write_module(), t6721_snapshot_write_module(), tape_snapshot_write_module(), tape_snapshot_write_tapimage_module(), tapeport_snapshot_write_module(), tapertc_write_snapshot(), tpicore_snapshot_write_module(), userport_8bss_write_snapshot_module(), userport_dac_write_snapshot_module(), userport_digimax_write_snapshot_module(), userport_io_sim_write_snapshot_module(), userport_joystick_cga_write_snapshot_module(), userport_joystick_hit_write_snapshot_module(), userport_joystick_kingsoft_write_snapshot_module(), userport_joystick_starbyte_write_snapshot_module(), userport_joystick_synergy_write_snapshot_module(), userport_joystick_woj_write_snapshot_module(), userport_petscii_write_snapshot_module(), userport_printer_write_snapshot_module(), userport_rtc_write_snapshot_module(), userport_snapshot_write_module(), userport_superpad64_write_snapshot_module(), vdrive_snapshot_module_write(), viacore_snapshot_write_module(), vicii_snapshot_write_module(), wd1770_snapshot_write_module(), and ym3526_snapshot_write_module().
snapshot_module_open()
snapshot_module_t * snapshot_module_open (snapshot_t * s, const char * name, uint8_t * major_version_return, uint8_t * minor_version_return)
Referenced by ata_snapshot_read_module(), c64_256k_snapshot_read(), c64_glue_snapshot_read_module(), c64_snapshot_read_module(), c64_snapshot_read_rom_module(), ciacore_snapshot_read_module(), cmdhd_snapshot_read_module(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), drivecpu65c02_snapshot_read_module(), drivecpu_snapshot_read_module(), driverom_snapshot_read(), dtlbasic_read_snapshot(), eeprom_snapshot_read_module(), event_snapshot_read_module(), fdd_snapshot_read_module(), flash040core_snapshot_read_module(), fsdrive_snapshot_read_module(), keyboard_snapshot_read_module(), m93c86_snapshot_read_module(), maincpu_snapshot_read_module(), memhacks_snapshot_read_modules(), mmc_snapshot_read_module(), myacia_snapshot_read_module(), mypia_snapshot_read_module(), plus256k_snapshot_read(), plus60k_snapshot_read(), riotcore_snapshot_read_module(), scsi_snapshot_read_module(), sid_snapshot_read_module_extended(), sid_snapshot_read_module_simple(), spi_flash_snapshot_read_module(), t6721_snapshot_read_module(), tape_snapshot_read_module(), tape_snapshot_read_tapimage_module(), tapeport_snapshot_read_module(), tapertc_read_snapshot(), tpicore_snapshot_read_module(), userport_8bss_read_snapshot_module(), userport_dac_read_snapshot_module(), userport_digimax_read_snapshot_module(), userport_io_sim_read_snapshot_module(), userport_joystick_cga_read_snapshot_module(), userport_joystick_hit_read_snapshot_module(), userport_joystick_kingsoft_read_snapshot_module(), userport_joystick_starbyte_read_snapshot_module(), userport_joystick_synergy_read_snapshot_module(), userport_joystick_woj_read_snapshot_module(), userport_petscii_read_snapshot_module(), userport_printer_read_snapshot_module(), userport_rtc_read_snapshot_module(), userport_snapshot_read_module(), userport_superpad64_read_snapshot_module(), vdrive_snapshot_module_read(), viacore_snapshot_read_module(), vicii_snapshot_read_module(), wd1770_snapshot_read_module(), and ym3526_snapshot_read_module().
snapshot_module_read_byte_array()
int snapshot_module_read_byte_array (snapshot_module_t * m, uint8_t * b_return, unsigned int num)
snapshot_module_read_dword_into_int()
int snapshot_module_read_dword_into_int (snapshot_module_t * m, int * value_return)
snapshot_module_read_dword_into_uint()
int snapshot_module_read_dword_into_uint (snapshot_module_t * m, unsigned int * value_return)
snapshot_module_read_word_into_int()
int snapshot_module_read_word_into_int (snapshot_module_t * m, int * value_return)
snapshot_module_write_byte_array()
int snapshot_module_write_byte_array (snapshot_module_t * m, const uint8_t * data, unsigned int num)
snapshot_module_write_word()
int snapshot_module_write_word (snapshot_module_t * m, uint16_t data)
snapshot_set_error()
void snapshot_set_error (int error)
Referenced by ata_snapshot_read_module(), c64_256k_snapshot_read(), c64_glue_snapshot_read_module(), c64_snapshot_read(), c64_snapshot_read_module(), c64_snapshot_read_rom_module(), cmdhd_snapshot_read_module(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), driverom_snapshot_read(), dtlbasic_read_snapshot(), eeprom_snapshot_write_module(), fdd_snapshot_read_module(), fsdrive_snapshot_read_module(), keyboard_snapshot_read_module(), machine_read_snapshot(), machine_write_snapshot(), memhacks_snapshot_read_modules(), mmc_snapshot_write_module(), myacia_snapshot_read_module(), plus256k_snapshot_read(), plus60k_snapshot_read(), riotcore_snapshot_read_module(), scsi_snapshot_read_module(), sid_snapshot_read_module_extended(), sid_snapshot_read_module_simple(), t6721_snapshot_write_module(), tapertc_read_snapshot(), tpicore_snapshot_read_module(), userport_8bss_read_snapshot_module(), userport_dac_read_snapshot_module(), userport_digimax_read_snapshot_module(), userport_io_sim_read_snapshot_module(), userport_joystick_cga_read_snapshot_module(), userport_joystick_hit_read_snapshot_module(), userport_joystick_kingsoft_read_snapshot_module(), userport_joystick_starbyte_read_snapshot_module(), userport_joystick_synergy_read_snapshot_module(), userport_joystick_woj_read_snapshot_module(), userport_petscii_read_snapshot_module(), userport_printer_read_snapshot_module(), userport_rtc_read_snapshot_module(), userport_superpad64_read_snapshot_module(), viacore_snapshot_read_module(), and wd1770_snapshot_read_module().
snapshot_version_is_bigger()
int snapshot_version_is_bigger (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
Referenced by c64_256k_snapshot_read(), c64_glue_snapshot_read_module(), c64_snapshot_read_module(), c64_snapshot_read_rom_module(), cmdhd_snapshot_read_module(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), driverom_snapshot_read(), dtlbasic_read_snapshot(), fdd_snapshot_read_module(), fsdrive_snapshot_read_module(), keyboard_snapshot_read_module(), m93c86_snapshot_read_module(), memhacks_snapshot_read_modules(), myacia_snapshot_read_module(), plus256k_snapshot_read(), plus60k_snapshot_read(), riotcore_snapshot_read_module(), scsi_snapshot_read_module(), sid_snapshot_read_module_extended(), sid_snapshot_read_module_simple(), spi_flash_snapshot_read_module(), tape_snapshot_read_tapimage_module(), tapertc_read_snapshot(), tpicore_snapshot_read_module(), userport_8bss_read_snapshot_module(), userport_dac_read_snapshot_module(), userport_digimax_read_snapshot_module(), userport_io_sim_read_snapshot_module(), userport_joystick_cga_read_snapshot_module(), userport_joystick_hit_read_snapshot_module(), userport_joystick_kingsoft_read_snapshot_module(), userport_joystick_starbyte_read_snapshot_module(), userport_joystick_synergy_read_snapshot_module(), userport_joystick_woj_read_snapshot_module(), userport_petscii_read_snapshot_module(), userport_printer_read_snapshot_module(), userport_rtc_read_snapshot_module(), userport_superpad64_read_snapshot_module(), viacore_snapshot_read_module(), vicii_snapshot_read_module(), and wd1770_snapshot_read_module().
snapshot_version_is_equal()
int snapshot_version_is_equal (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
Referenced by ata_snapshot_read_module(), c64_snapshot_read(), sid_snapshot_read_module_simple(), tapeport_snapshot_read_module(), and userport_snapshot_read_module().
snapshot_version_is_smaller()
int snapshot_version_is_smaller (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
Referenced by c64_snapshot_read_module(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), sid_snapshot_read_module_extended(), and sid_snapshot_read_module_simple().
tape_image_detach_all()
void tape_image_detach_all (void)
Referenced by resources_set_defaults().
ui_error()
void ui_error (const char * format, ...)
Print an error message.
Referenced by archdep_startup_log_error(), artstudio_ted_save(), artstudio_vdc_save(), artstudio_vicii_save(), artstudiodrv_save(), autostart_prg_with_disk_image(), check_resource_file_version(), display_error_with_vice_version(), event_playback_attach_image(), event_playback_start_trap(), event_record_reset_milestone_trap(), event_record_set_milestone_trap(), event_record_start_trap(), event_record_stop_trap(), ffmpegexedrv_init_file(), io_source_msg_detach_all(), io_source_msg_detach_last(), koala_ted_save(), koala_vdc_save(), koala_vicii_save(), koaladrv_save(), minipaintdrv_save(), network_client_connect_trap(), network_connect_client(), network_hook_connected_receive(), network_server_connect_trap(), network_start_server(), sampler_start(), screenshot_save(), set_video_halve_framerate(), snapshot_display_error(), sound_error(), sound_open(), tapeport_set_device(), userport_joystick_cga_enable(), userport_joystick_hit_enable(), userport_joystick_hummer_enable(), userport_joystick_kingsoft_enable(), userport_joystick_oem_enable(), userport_joystick_pet_enable(), userport_joystick_starbyte_enable(), userport_joystick_synergy_enable(), userport_joystick_woj_enable(), userport_petscii_enable(), userport_set_device(), userport_spt_joystick_enable(), userport_superpad64_enable(), and zmbvdrv_init_file().
vsync_suspend_speed_eval()
void vsync_suspend_speed_eval (void)
Referenced by drive_jam(), load_snapshot_trap(), machine_jam(), monitor_close(), monitor_open(), monitor_open_action(), network_client_connect_trap(), network_connect_client(), network_hook_connected_receive(), network_server_connect_trap(), network_start_server(), pause_loop(), psid_ui_set_tune(), quickload_snapshot_trap(), quicksave_snapshot_trap(), save_snapshot_trap(), snapshot_open(), sound_close(), sound_open(), and ui_vsid_window_load_psid().
Variable Documentation
machine_class
int machine_class = 0
Machine class.
Referenced by acia_get_status(), actions_display_register(), actions_display_setup_ui(), actions_machine_register(), actions_speed_register(), actions_speed_setup_ui(), add_machine_symbols(), add_sliders(), archdep_app_icon_path_png(), artstudiodrv_cmdline_options_init(), artstudiodrv_resources_init(), attach_cart_image(), autostart_autodetect(), autostart_cmdline_options_init(), autostart_resources_init(), c64_glue_resources_init(), c64keyboard_init(), c64meminit(), c64rom_load_kernal(), cart_dialog_internal(), cbm2_hardwired_switches_widget_create(), cbm2_memory_size_widget_create(), charset_petscii_to_ucs(), cia1_setup_context(), cia2_setup_context(), cmdline_attach(), create_acia_base_widget(), create_base_widget(), create_c64_layout(), create_c64_misc_widget(), create_cart_type_model(), create_extra_sid_address_widget(), create_extra_widget(), create_layout(), create_num_sids_widget(), create_prg_layout(), create_screenshot_param_widget(), create_serial_baud_widget(), create_sidcart_address_widget(), create_sidcart_clock_widget(), create_stack_child_widget(), crt_control_widget_create(), crt_open(), crt_preview_widget_create(), crt_preview_widget_update(), dir_menu_popup_create(), do_smart_attach(), drive_cmdline_options_init(), drive_get_type_by_devnr(), drive_parallel_cable_widget_create(), drive_resources_init(), drive_update_ui_status(), expected_header_error(), export_dump(), generate_sid_address_range(), get_default_icon(), get_iec_device_state(), has_iec(), help_hotkeys_action(), init_cmdline_options(), init_main(), init_raster(), initcmdline_check_attach(), initcmdline_check_psid(), initcmdline_init(), is_current_machine_action(), joystick_swap_possible(), keyboard_cmdline_options_init(), keyboard_resources_init(), keyboard_resources_shutdown(), keymap_cmdline_options_init(), keymap_init(), keymap_resources_init(), koaladrv_cmdline_options_init(), koaladrv_resources_init(), machine_common_cmdline_options_init(), machine_common_resources_init(), machine_drive_resources_init(), machine_get_name(), machine_has_acia(), machine_has_iec(), machine_has_second_tape_port(), machine_has_tapecart(), machine_has_userport(), machine_model_callback(), machine_model_handler_c64(), machine_model_widget_connect_signals(), machine_model_widget_update(), machine_window_create(), main_init_hack(), main_program(), minipaintdrv_cmdline_options_init(), minipaintdrv_resources_init(), mixer_widget_create(), mixer_widget_sid_type_changed(), mon_attach(), mon_detach(), mon_file_load(), mon_file_verify(), mon_joyport_set_output(), mon_userport_set_output(), monitor_binary_process_display_get(), monitor_binary_process_palette_get(), on_cart_type_changed(), on_control_port_changed(), on_dialog_destroy(), on_iec_toggled(), on_model_toggled(), on_response(), on_vsync_set_border_mode(), output_text_init_cmdline_options(), output_text_init_resources(), palette_read_info(), populate_tree_model(), psid_init_tune(), ram_cmdline_options_init(), ram_resources_init(), raster_cmdline_options_chip_init(), raster_resources_chip_init(), rendering_area_event_handler(), screenshot_at_exit(), serial_iec_device_cmdline_options_init(), serial_iec_device_resources_init(), set_buffer_size(), set_datasette_active(), set_iec_device_state(), set_kernal_revision(), set_sid_model(), set_sid_stereo(), set_video_cache_enabled(), set_video_standard(), set_widgets_sensitivity(), settings_autofire_widget_create(), settings_controlport_widget_create(), settings_crt_widget_create(), settings_digimax_widget_create(), settings_drive_widget_create(), settings_ethernet_widget_create(), settings_georam_widget_create(), settings_host_display_widget_create(), settings_io_widget_create(), settings_joystick_widget_create(), settings_model_widget_create(), settings_rom_widget_create(), settings_rs232_widget_create(), settings_sfxsoundexpander_widget_create(), settings_sfxsoundsampler_widget_create(), settings_sidcart_widget_create(), settings_speed_widget_create(), settings_userport_widget_create(), sid_check_engine_model(), sid_cmdline_options_init(), sid_common_resources_init(), sid_get_engine_model_list(), sid_machine_get_max_sids(), sid_model_widget_create(), sid_read_chip(), sid_sound_widget_create(), statusbar_speed_widget_create(), statusbar_speed_widget_update(), tap_create(), tap_header_read(), tapeport_check_valid_device(), tapeport_device_resources_init(), tapeport_devices_cmdline_options_init(), traps_resources_init(), ui_about_dialog_show(), ui_create_datasette_control_menu(), ui_create_main_window(), ui_display_main_window(), ui_exit(), ui_hotkeys_vhk_filename_user(), ui_hotkeys_vhk_filename_vice(), ui_init_finalize(), ui_is_fullscreen(), ui_is_fullscreen_from_canvas(), ui_machine_menu_bar_create(), ui_media_dialog_show(), ui_resources_init(), ui_set_window_geometries(), ui_statusbar_create(), ui_statusbar_set_kbd_debug(), ui_statusbar_update_kbd_debug(), ui_tape_widget_create(), ui_update_fullscreen_decorations(), ui_update_lightpen(), uivideo_chip_has_border_mode(), uivideo_chip_has_sprites(), uivideo_chip_has_vert_stretch(), uivideo_chip_has_vsp_bug(), uivideo_chip_id(), uivideo_chip_name(), update_sid_addresses_sensitivity(), userport_io_sim_resources_init(), userport_io_sim_set_pax_out_lines(), userport_io_sim_set_pbx_out_lines(), userport_rsinterface_widget_create(), vicii_cmdline_options_init(), vicii_color_update_palette(), vicii_dump(), vicii_resources_init(), video_cmdline_options_chip_init(), video_model_callback(), video_resources_chip_init(), and video_sound_init().
machine_name
const char machine_name[] = "C1541"
Machine name.
The following stuff must be defined once per every emulated CBM machine.
Referenced by archdep_get_vice_machinedir(), archdep_init(), c64rom_load_basic(), c64rom_load_chargen(), c64rom_load_kernal(), create_prg_layout(), dialog_create_helper(), emulation_speed_submenu_create(), get_default_icon(), keyboard_is_keymap_valid(), keyboard_parse_keymap(), machine_get_name(), main_program(), on_tree_selection_changed(), palette_get_info_list(), romset_file_load(), settings_ethernet_widget_create(), settings_rs232_widget_create(), try_set_keymap_file(), ui_hotkeys_load_vice_default(), ui_hotkeys_vhk_filename_user(), uicmdline_dialog_show(), uicompiletimefeatures_dialog_show(), and video_load_palette().