vsid: gfxoutputdrv/pcxdrv.c File Reference
pcxdrv.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "archdep.h"
#include "pcxdrv.h"
#include "lib.h"
#include "log.h"
#include "gfxoutput.h"
#include "palette.h"
#include "screenshot.h"
#include "types.h"
#include "util.h"
Data Structures
struct gfxoutputdrv_data_s
Typedefs
typedef struct gfxoutputdrv_data_s gfxoutputdrv_data_t
Functions
static int pcxdrv_write_file_header (screenshot_t *screenshot)
static int pcxdrv_open (screenshot_t *screenshot, const char *filename)
static int pcxdrv_write (screenshot_t *screenshot)
static int pcxdrv_close (screenshot_t *screenshot)
static int pcxdrv_save (screenshot_t *screenshot, const char *filename)
void gfxoutput_init_pcx (int help)
Variables
static gfxoutputdrv_t pcx_drv
Typedef Documentation
gfxoutputdrv_data_t
typedef struct gfxoutputdrv_data_s gfxoutputdrv_data_t
Function Documentation
gfxoutput_init_pcx()
void gfxoutput_init_pcx (int help)
Referenced by gfxoutput_early_init().
pcxdrv_close()
static int pcxdrv_close (screenshot_t * screenshot) static
Referenced by pcxdrv_save().
pcxdrv_open()
static int pcxdrv_open (screenshot_t * screenshot, const char * filename) static
Referenced by pcxdrv_save().
pcxdrv_save()
static int pcxdrv_save (screenshot_t * screenshot, const char * filename) static
pcxdrv_write()
static int pcxdrv_write (screenshot_t * screenshot) static
Referenced by pcxdrv_save().
pcxdrv_write_file_header()
static int pcxdrv_write_file_header (screenshot_t * screenshot) static
Referenced by pcxdrv_open().
Variable Documentation
pcx_drv
static gfxoutputdrv_t pcx_drv static
Initial value:
=
{
    GFXOUTPUTDRV_TYPE_SCREENSHOT_IMAGE,
    "PCX",
    "PCX screenshot",
    "pcx",
    NULL,
    pcxdrv_open,
    pcxdrv_close,
    pcxdrv_write,
    pcxdrv_save,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
}
Referenced by gfxoutput_init_pcx(), and pcxdrv_open().