vsid: arch/shared/archdep_user_config_path.c File Reference
archdep_user_config_path.c File Reference
Retrieve path to the user's configuration directory.
#include "vice.h"
#include "archdep_defs.h"
#include <stddef.h>
#include "archdep_xdg.h"
#include "lib.h"
#include "util.h"
#include "archdep_user_config_path.h"
Functions
const char * archdep_user_config_path (void)
Get path to the user's VICE configuration directory.
void archdep_user_config_path_free (void)
Free memory used by the user's config path.
Variables
static char * user_config_dir = NULL
User's VICE configuration directory reference.
Detailed Description
Retrieve path to the user's configuration directory.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Get path to user's VICE configuration directory, this is where the vice files like vicerc/vice.ini, vice.log, autostart-$emu.d64 will be.
OS support:
Linux
Windows
MacOS
BeOS/Haiku (untested)
AmigaOS (untested)
OS/2 (untested)
Function Documentation
archdep_user_config_path()
const char * archdep_user_config_path (void)
Get path to the user's VICE configuration directory.
On systems supporting home directories this will return a directory inside the home directory, depending on OS:
Windows: $HOME\AppData\Roaming\vice
Unix: $HOME/.config/vice (rather: XDG_CONFIG_HOME)
BeOS: $HOME/config/settings/vice (Haiku sets $XDG_CONFIG_HOME to '/boot/home/config/settings')
On other systems the path to the executable is returned.
Free memory used on emulator exit with archdep_user_config_path_free()
Returns
path to VICE config directory
Referenced by archdep_create_user_config_dir(), archdep_default_fliplist_file_name(), archdep_default_joymap_file_name(), archdep_default_resource_file_name(), archdep_default_rtc_file_name(), archdep_default_sysfile_pathlist(), archdep_init(), quicksnap_filename(), settings_load_from_action(), settings_save_to_action(), and ui_hotkeys_vhk_full_path_user().
archdep_user_config_path_free()
void archdep_user_config_path_free (void)
Free memory used by the user's config path.
Referenced by archdep_shutdown().
Variable Documentation
user_config_dir
char* user_config_dir = NULL static
User's VICE configuration directory reference.
Todo:
Haiku is a lot more POSIX-like than classic BeOS, so perhaps we should test for classic BeOS or Haiku and act accordingly.
Allocated once in the first call to archdep_user_config_path(), should be freed on emulator exit with archdep_user_config_path_free()
Referenced by archdep_user_config_path(), and archdep_user_config_path_free().