vsid: sound.h File Reference
sound.h File Reference
#include "vice.h"
#include <stdio.h>
#include "types.h"
Data Structures
struct sound_device_s
device structure
struct sound_register_devices_s
struct sound_desc_s
struct sound_chip_s
This structure is used by sound producing chips/devices.
struct sound_dac_s
Macros
#define SOUND_SAMPLE_RATE 44000
Sound defaults.
#define SOUND_SAMPLE_BUFFER_SIZE 30
#define SOUND_FRAGMENT_SIZE SOUND_FRAGMENT_MEDIUM
#define SOUND_OUTPUT_CHANNELS_MAX 2
#define SOUND_CHIP_CHANNELS_MAX 8
#define SOUND_SIDS_MAX 8
Maximum number of SIDs supported by the emulation.
#define SOUND_SIDS_MAX_PSID 3
Maximum number of SIDs supported by PSID files.
#define SOUND_CHIPS_MAX 20
#define SOUND_SAMPLE_MAX_BUFFER_SIZE 350
largest value in the UIs.
#define SOUND_DEVICE_MOVIE_RECORD_SOUNDMOVIE 0
Sound movie record device ID numbers.
#define SOUND_DEVICE_MOVIE_RECORD_MAX 1
#define MASTER_VOLUME_MAX 100
100%
#define MASTER_VOLUME_ONE 100
100%
#define MASTER_VOLUME_DEFAULT MASTER_VOLUME_MAX
Typedefs
typedef struct sound_device_s sound_device_t
device structure
typedef struct sound_register_devices_s sound_register_devices_t
typedef struct sound_desc_s sound_desc_t
typedef struct sound_s sound_t
functions and structs implemented by each machine
typedef struct sound_chip_s sound_chip_t
This structure is used by sound producing chips/devices.
typedef struct sound_dac_s sound_dac_t
Enumerations
enum {
SOUND_FRAGMENT_VERY_SMALL = 0 ,
SOUND_FRAGMENT_SMALL ,
SOUND_FRAGMENT_MEDIUM ,
SOUND_FRAGMENT_LARGE ,
SOUND_FRAGMENT_VERY_LARGE
}
OSS: check if needed defines are present.
enum {
SOUND_OUTPUT_SYSTEM = 0 ,
SOUND_OUTPUT_MONO ,
SOUND_OUTPUT_STEREO
}
Sound output modes.
enum {
SOUND_1_DEVICE = 1 ,
SOUND_2_DEVICES ,
SOUND_3_DEVICES ,
SOUND_4_DEVICES ,
SOUND_5_DEVICES ,
SOUND_6_DEVICES ,
SOUND_7_DEVICES ,
SOUND_8_DEVICES
}
Sound device amounts.
enum {
SOUND_CHANNEL_1 = 1 ,
SOUND_CHANNEL_2 ,
SOUND_CHANNELS_1_AND_2
}
Sound channels.
enum {
SOUND_RECORD_DEVICE = 0 ,
SOUND_PLAYBACK_DEVICE ,
SOUND_MOVIE_RECORD_DEVICE
}
Sound device types.
enum {
SOUND_DEVICE_PLAYBACK_PULSE = 0 ,
SOUND_DEVICE_PLAYBACK_ALSA ,
SOUND_DEVICE_PLAYBACK_COREAUDIO ,
SOUND_DEVICE_PLAYBACK_SUN_NETBSD ,
SOUND_DEVICE_PLAYBACK_DX ,
SOUND_DEVICE_PLAYBACK_WMM ,
SOUND_DEVICE_PLAYBACK_BEOS ,
SOUND_DEVICE_PLAYBACK_BSP ,
SOUND_DEVICE_PLAYBACK_SDL ,
SOUND_DEVICE_PLAYBACK_DUMMY ,
SOUND_DEVICE_PLAYBACK_MAX
}
Sound playback device ID numbers.
enum {
SOUND_DEVICE_RECORD_FS = 0 ,
SOUND_DEVICE_RECORD_DUMP ,
SOUND_DEVICE_RECORD_WAV ,
SOUND_DEVICE_RECORD_VOC ,
SOUND_DEVICE_RECORD_IFF ,
SOUND_DEVICE_RECORD_AIFF ,
SOUND_DEVICE_RECORD_MP3 ,
SOUND_DEVICE_RECORD_FLAC ,
SOUND_DEVICE_RECORD_OGG ,
SOUND_DEVICE_RECORD_MAX
}
Sound record device ID numbers.
Functions
static int16_t sound_audio_mix (int ch1, int ch2)
sound_desc_t * sound_get_valid_devices (int type, int sort)
void sound_init (unsigned int clock_rate, unsigned int ticks_per_frame)
external functions for vice
void sound_reset (void)
reset sid
bool sound_flush (void)
flush all generated samples from buffer to sounddevice.
void sound_suspend (void)
suspend sid (eg.
void sound_resume (void)
resume sid
int sound_open (void)
open sound device
void sound_close (void)
close sid
void sound_set_relative_speed (int value)
void sound_set_warp_mode (int value)
void sound_set_machine_parameter (long clock_rate, long ticks_per_frame)
set PAL/NTSC clock speed
void sound_snapshot_prepare (void)
void sound_snapshot_finish (void)
int sound_resources_init (void)
void sound_resources_shutdown (void)
int sound_cmdline_options_init (void)
int sound_init_alsa_device (void)
device initialization prototypes
int sound_init_dummy_device (void)
int sound_init_dump_device (void)
int sound_init_fs_device (void)
int sound_init_wav_device (void)
int sound_init_sdl_device (void)
int sound_init_sun_device (void)
int sound_init_dx_device (void)
int sound_init_beos_device (void)
int sound_init_bsp_device (void)
int sound_init_wmm_device (void)
int sound_init_movie_device (void)
int sound_init_coreaudio_device (void)
int sound_init_voc_device (void)
int sound_init_iff_device (void)
int sound_init_aiff_device (void)
int sound_init_mp3_device (void)
int sound_init_flac_device (void)
int sound_init_vorbis_device (void)
int sound_init_pulse_device (void)
int sound_register_device (const sound_device_t *pdevice)
internal function for sound device registration
int sound_read (uint16_t addr, int chipno)
other internal functions used around sound -code
void sound_store (uint16_t addr, uint8_t val, int chipno)
long sound_sample_position (void)
int sound_dump (int chipno)
char * sound_machine_dump_state (sound_t *psid)
void sound_machine_enable (int enable)
unsigned int sound_device_num (void)
const char * sound_device_name (unsigned int num)
sound_t * sound_get_psid (unsigned int channel)
uint16_t sound_chip_register (sound_chip_t *chip)
void sound_dac_init (sound_dac_t *dac, int speed)
int sound_dac_calculate_samples (sound_dac_t *dac, int16_t *pbuf, int value, int nr, int soc, int cs)
void sound_stop_recording (void)
recording related functions, equivalent to screenshot_...
int sound_is_recording (void)
Variables
int sound_state_changed
int sound_playdev_reopen
int sid_state_changed
Macro Definition Documentation
MASTER_VOLUME_DEFAULT
#define MASTER_VOLUME_DEFAULT MASTER_VOLUME_MAX
MASTER_VOLUME_MAX
#define MASTER_VOLUME_MAX 100
100%
MASTER_VOLUME_ONE
#define MASTER_VOLUME_ONE 100
100%
SOUND_CHIP_CHANNELS_MAX
#define SOUND_CHIP_CHANNELS_MAX 8
SOUND_CHIPS_MAX
#define SOUND_CHIPS_MAX 20
SOUND_DEVICE_MOVIE_RECORD_MAX
#define SOUND_DEVICE_MOVIE_RECORD_MAX 1
SOUND_DEVICE_MOVIE_RECORD_SOUNDMOVIE
#define SOUND_DEVICE_MOVIE_RECORD_SOUNDMOVIE 0
Sound movie record device ID numbers.
SOUND_FRAGMENT_SIZE
#define SOUND_FRAGMENT_SIZE SOUND_FRAGMENT_MEDIUM
SOUND_OUTPUT_CHANNELS_MAX
#define SOUND_OUTPUT_CHANNELS_MAX 2
SOUND_SAMPLE_BUFFER_SIZE
#define SOUND_SAMPLE_BUFFER_SIZE 30
SOUND_SAMPLE_MAX_BUFFER_SIZE
#define SOUND_SAMPLE_MAX_BUFFER_SIZE 350
largest value in the UIs.
also used by VSID as default
SOUND_SAMPLE_RATE
#define SOUND_SAMPLE_RATE 44000
Sound defaults.
SOUND_SIDS_MAX
#define SOUND_SIDS_MAX 8
Maximum number of SIDs supported by the emulation.
SOUND_SIDS_MAX_PSID
#define SOUND_SIDS_MAX_PSID 3
Maximum number of SIDs supported by PSID files.
Maximum number of SIDs for .psid files and thus VSID.
Typedef Documentation
sound_chip_t
typedef struct sound_chip_s sound_chip_t
This structure is used by sound producing chips/devices.
sound_dac_t
typedef struct sound_dac_s sound_dac_t
sound_desc_t
typedef struct sound_desc_s sound_desc_t
sound_device_t
typedef struct sound_device_s sound_device_t
device structure
sound_register_devices_t
typedef struct sound_register_devices_s sound_register_devices_t
sound_t
typedef struct sound_s sound_t
functions and structs implemented by each machine
Enumeration Type Documentation
anonymous enum
anonymous enum
OSS: check if needed defines are present.
Fragment sizes
Enumerator
SOUND_FRAGMENT_VERY_SMALL
SOUND_FRAGMENT_SMALL
SOUND_FRAGMENT_MEDIUM
SOUND_FRAGMENT_LARGE
SOUND_FRAGMENT_VERY_LARGE
anonymous enum
anonymous enum
Sound output modes.
Enumerator
SOUND_OUTPUT_SYSTEM
SOUND_OUTPUT_MONO
SOUND_OUTPUT_STEREO
anonymous enum
anonymous enum
Sound device amounts.
Enumerator
SOUND_1_DEVICE
SOUND_2_DEVICES
SOUND_3_DEVICES
SOUND_4_DEVICES
SOUND_5_DEVICES
SOUND_6_DEVICES
SOUND_7_DEVICES
SOUND_8_DEVICES
anonymous enum
anonymous enum
Sound channels.
Enumerator
SOUND_CHANNEL_1
SOUND_CHANNEL_2
SOUND_CHANNELS_1_AND_2
anonymous enum
anonymous enum
Sound device types.
Enumerator
SOUND_RECORD_DEVICE
SOUND_PLAYBACK_DEVICE
SOUND_MOVIE_RECORD_DEVICE
anonymous enum
anonymous enum
Sound playback device ID numbers.
Enumerator
SOUND_DEVICE_PLAYBACK_PULSE
SOUND_DEVICE_PLAYBACK_ALSA
SOUND_DEVICE_PLAYBACK_COREAUDIO
SOUND_DEVICE_PLAYBACK_SUN_NETBSD
SOUND_DEVICE_PLAYBACK_DX
SOUND_DEVICE_PLAYBACK_WMM
SOUND_DEVICE_PLAYBACK_BEOS
SOUND_DEVICE_PLAYBACK_BSP
SOUND_DEVICE_PLAYBACK_SDL
SOUND_DEVICE_PLAYBACK_DUMMY
SOUND_DEVICE_PLAYBACK_MAX
anonymous enum
anonymous enum
Sound record device ID numbers.
Enumerator
SOUND_DEVICE_RECORD_FS
SOUND_DEVICE_RECORD_DUMP
SOUND_DEVICE_RECORD_WAV
SOUND_DEVICE_RECORD_VOC
SOUND_DEVICE_RECORD_IFF
SOUND_DEVICE_RECORD_AIFF
SOUND_DEVICE_RECORD_MP3
SOUND_DEVICE_RECORD_FLAC
SOUND_DEVICE_RECORD_OGG
SOUND_DEVICE_RECORD_MAX
Function Documentation
sound_audio_mix()
static int16_t sound_audio_mix (int ch1, int ch2) inline static
Referenced by drive_sound_machine_calculate_samples(), sid_sound_machine_calculate_samples(), sound_dac_calculate_samples(), and video_sound_machine_calculate_samples().
sound_chip_register()
uint16_t sound_chip_register (sound_chip_t * chip)
Referenced by drive_sound_init(), sid_sound_chip_init(), userport_dac_sound_chip_init(), userport_digimax_sound_chip_init(), and video_sound_init().
sound_close()
void sound_close (void)
close sid
Referenced by machine_shutdown(), sid_snapshot_read_module_simple(), sound_error(), and sound_flush().
sound_cmdline_options_init()
int sound_cmdline_options_init (void)
Referenced by init_cmdline_options().
sound_dac_calculate_samples()
int sound_dac_calculate_samples (sound_dac_t * dac, int16_t * pbuf, int value, int nr, int soc, int cs)
Todo:
FIXME: this should use bandlimited step synthesis. Sadly, VICE does not have an easy-to-use infrastructure for blep generation. We should write this code.
Referenced by digimax_sound_machine_calculate_samples(), and userport_dac_sound_machine_calculate_samples().
sound_dac_init()
void sound_dac_init (sound_dac_t * dac, int speed)
Referenced by digimax_sound_machine_init(), and userport_dac_sound_machine_init().
sound_device_name()
const char * sound_device_name (unsigned int num)
Referenced by create_device_combobox().
sound_device_num()
unsigned int sound_device_num (void)
Referenced by create_device_combobox().
sound_dump()
int sound_dump (int chipno)
Referenced by set_sound_func().
sound_flush()
bool sound_flush (void)
flush all generated samples from buffer to sounddevice.
Referenced by vsync_do_end_of_line().
sound_get_psid()
sound_t * sound_get_psid (unsigned int channel)
Referenced by sid_snapshot_read_fastsid_module(), sid_snapshot_write_fastsid_module(), sid_state_read(), and sid_state_write().
sound_get_valid_devices()
sound_desc_t * sound_get_valid_devices (int type, int sort)
sound_init()
void sound_init (unsigned int clock_rate, unsigned int ticks_per_frame)
external functions for vice
external functions for vice
Referenced by machine_specific_init().
sound_init_aiff_device()
int sound_init_aiff_device (void)
sound_init_alsa_device()
int sound_init_alsa_device (void)
device initialization prototypes
sound_init_beos_device()
int sound_init_beos_device (void)
sound_init_bsp_device()
int sound_init_bsp_device (void)
sound_init_coreaudio_device()
int sound_init_coreaudio_device (void)
sound_init_dummy_device()
int sound_init_dummy_device (void)
sound_init_dump_device()
int sound_init_dump_device (void)
sound_init_dx_device()
int sound_init_dx_device (void)
sound_init_flac_device()
int sound_init_flac_device (void)
sound_init_fs_device()
int sound_init_fs_device (void)
sound_init_iff_device()
int sound_init_iff_device (void)
sound_init_movie_device()
int sound_init_movie_device (void)
sound_init_mp3_device()
int sound_init_mp3_device (void)
sound_init_pulse_device()
int sound_init_pulse_device (void)
sound_init_sdl_device()
int sound_init_sdl_device (void)
sound_init_sun_device()
int sound_init_sun_device (void)
sound_init_voc_device()
int sound_init_voc_device (void)
sound_init_vorbis_device()
int sound_init_vorbis_device (void)
sound_init_wav_device()
int sound_init_wav_device (void)
sound_init_wmm_device()
int sound_init_wmm_device (void)
sound_is_recording()
int sound_is_recording (void)
Referenced by statusbar_recording_widget_set_recording_status(), and ui_media_stop_recording().
sound_machine_dump_state()
char * sound_machine_dump_state (sound_t * psid)
Referenced by sound_dump(), and sound_flush().
sound_machine_enable()
void sound_machine_enable (int enable)
Referenced by set_playback_enabled().
sound_open()
int sound_open (void)
open sound device
Referenced by sid_snapshot_read_module_simple(), and sound_run_sound().
sound_read()
int sound_read (uint16_t addr, int chipno)
other internal functions used around sound -code
Referenced by set_sound_func().
sound_register_device()
int sound_register_device (const sound_device_t * pdevice)
internal function for sound device registration
Referenced by sound_init_aiff_device(), sound_init_dummy_device(), sound_init_dump_device(), sound_init_fs_device(), sound_init_iff_device(), sound_init_movie_device(), sound_init_sdl_device(), sound_init_voc_device(), and sound_init_wav_device().
sound_reset()
void sound_reset (void)
reset sid
Referenced by sid_reset().
sound_resources_init()
int sound_resources_init (void)
Referenced by init_resources().
sound_resources_shutdown()
void sound_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
sound_resume()
void sound_resume (void)
resume sid
Referenced by sound_flush(), and sound_set_warp_mode().
sound_sample_position()
long sound_sample_position (void)
Referenced by fastsid_read().
sound_set_machine_parameter()
void sound_set_machine_parameter (long clock_rate, long ticks_per_frame)
set PAL/NTSC clock speed
Referenced by machine_change_timing().
sound_set_relative_speed()
void sound_set_relative_speed (int value)
Referenced by set_relative_speed().
sound_set_warp_mode()
void sound_set_warp_mode (int value)
Referenced by vsync_set_warp_mode().
sound_snapshot_finish()
void sound_snapshot_finish (void)
Referenced by c64_snapshot_read().
sound_snapshot_prepare()
void sound_snapshot_prepare (void)
Referenced by c64_snapshot_write().
sound_stop_recording()
void sound_stop_recording (void)
recording related functions, equivalent to screenshot_...
Referenced by machine_shutdown(), and ui_media_stop_recording().
sound_store()
void sound_store (uint16_t addr, uint8_t val, int chipno)
Referenced by drive_sound_head(), drive_sound_update(), set_sound_func(), userport_dac_store_pbx(), and userport_digimax_store_pbx().
sound_suspend()
void sound_suspend (void)
suspend sid (eg.
before pause)
Referenced by drive_jam(), load_snapshot_trap(), machine_jam(), monitor_open(), network_client_connect_trap(), network_server_connect_trap(), network_start_server(), pause_loop(), quickload_snapshot_trap(), quicksave_snapshot_trap(), save_snapshot_trap(), and sound_set_warp_mode().
Variable Documentation
sid_state_changed
int sid_state_changed extern
Referenced by set_sid_filters_enabled(), set_sid_model(), sound_flush(), sound_init(), sound_open(), sound_set_machine_parameter(), and sound_set_relative_speed().
sound_playdev_reopen
int sound_playdev_reopen extern
Referenced by set_buffer_size(), set_device_arg(), set_fragment_size(), sound_close(), and sound_flush().
sound_state_changed
int sound_state_changed extern
Referenced by set_device_name(), set_output_option(), set_recorddevice_arg(), set_recorddevice_name(), set_sample_rate(), set_sid_engine(), set_sid_stereo(), sound_close(), sound_flush(), sound_init(), and sound_open().