vsid: uimon.h File Reference
uimon.h File Reference
#include <stdbool.h>
Functions
struct console_s * uimon_window_open (bool display_now)
void uimon_window_suspend (void)
struct console_s * uimon_window_resume (void)
void uimon_window_close (void)
int uimon_out (const char *buffer)
int uimon_petscii_out (const char *buffer, int len)
int uimon_petscii_upper_out (const char *buffer, int len)
int uimon_scrcode_out (const char *buffer, int len)
output screencode, lowercase
int uimon_scrcode_upper_out (const char *buffer, int len)
output screencode, uppercase
char * uimon_in (const char *prompt)
void uimon_notify_change (void)
void uimon_set_interface (struct monitor_interface_s **, int)
char * uimon_get_in (char **, const char *)
int uimon_get_columns (struct console_private_s *t)
void uimon_write_to_terminal (struct console_private_s *t, const char *data, long length)
int uimon_get_string (struct console_private_s *t, char *string, int string_len)
Block until some monitor input event happens.
bool uimon_set_font (void)
Gtk3-specific, so far.
bool uimon_set_foreground_color (const char *color)
Set foreground color.
bool uimon_set_background_color (const char *color)
Set foreground color.
Function Documentation
uimon_get_columns()
int uimon_get_columns (struct console_private_s * t)
Referenced by linenoisePrompt().
uimon_get_in()
char * uimon_get_in (char ** ppchCommandLine, const char * prompt)
Referenced by uimon_in().
uimon_get_string()
int uimon_get_string (struct console_private_s * t, char * string, int string_len)
Block until some monitor input event happens.
Todo:
Not sure if this check makes sense anymore, needs testing without
Referenced by completeLine(), and linenoisePrompt().
uimon_in()
char * uimon_in (const char * prompt)
Referenced by monitor_startup().
uimon_notify_change()
void uimon_notify_change (void)
Referenced by monitor_cpu_type_set(), monitor_cpu_type_set_value(), monitor_open(), and monitor_process().
uimon_out()
int uimon_out (const char * buffer)
Referenced by linenoisePrompt(), mon_buffer_flush(), and mon_out_buffered().
uimon_petscii_out()
int uimon_petscii_out (const char * buffer, int len)
< https://www.kreativekorp.com/software/fonts/c64/
< https://www.kreativekorp.com/software/fonts/c64/
Referenced by mon_buffer_flush(), and mon_out_buffered().
uimon_petscii_upper_out()
int uimon_petscii_upper_out (const char * buffer, int len)
< https://www.kreativekorp.com/software/fonts/c64/
< https://www.kreativekorp.com/software/fonts/c64/
Referenced by mon_buffer_flush(), and mon_out_buffered().
uimon_scrcode_out()
int uimon_scrcode_out (const char * buffer, int len)
output screencode, lowercase
< https://www.kreativekorp.com/software/fonts/c64/
Todo:
FIXME: regular PETSCII capable ("PET Me") font
< https://www.kreativekorp.com/software/fonts/c64/
Todo:
FIXME: regular PETSCII capable ("PET Me") font
Referenced by mon_buffer_flush(), and mon_out_buffered().
uimon_scrcode_upper_out()
int uimon_scrcode_upper_out (const char * buffer, int len)
output screencode, uppercase
< https://www.kreativekorp.com/software/fonts/c64/
Todo:
FIXME: regular PETSCII capable ("PET Me") font
< https://www.kreativekorp.com/software/fonts/c64/
Todo:
FIXME: regular PETSCII capable ("PET Me") font
Referenced by mon_buffer_flush(), and mon_out_buffered().
uimon_set_background_color()
bool uimon_set_background_color (const char * color)
Set foreground color.
Set VTE terminal foreground color to color.
Parameters
[in] color Gdk RGBA color string
Returns
bool
See also
https://docs.gtk.org/gdk3/method.RGBA.parse.html
Referenced by set_monitor_bg().
uimon_set_font()
bool uimon_set_font (void)
Gtk3-specific, so far.
< https://www.kreativekorp.com/software/fonts/c64/
< https://www.kreativekorp.com/software/fonts/c64/
Referenced by on_font_set(), and uimon_window_open_impl().
uimon_set_foreground_color()
bool uimon_set_foreground_color (const char * color)
Set foreground color.
Set VTE terminal foreground color to color.
Parameters
[in] color Gdk RGBA color string
Returns
bool
See also
https://docs.gtk.org/gdk3/method.RGBA.parse.html
Referenced by set_monitor_fg().
uimon_set_interface()
void uimon_set_interface (struct monitor_interface_s ** interf, int i)
Referenced by monitor_open().
uimon_window_close()
void uimon_window_close (void)
Referenced by monitor_close().
uimon_window_open()
struct console_s * uimon_window_open (bool display_now)
Referenced by monitor_open(), and uimonfb_window_resume().
uimon_window_resume()
struct console_s * uimon_window_resume (void)
Referenced by monitor_open().
uimon_window_suspend()
void uimon_window_suspend (void)
Referenced by monitor_close(), and uimonfb_window_close().
uimon_write_to_terminal()
void uimon_write_to_terminal (struct console_private_s * t, const char * data, long length)
Referenced by beep(), refreshLine(), vte_linenoise(), and vte_linenoiseClearScreen().