x128: arch/gtk3/widgets/vic20memoryexpansionwidget.c File Reference
vic20memoryexpansionwidget.c File Reference
VIC20 memory expansion widget.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdbool.h>
#include "debug_gtk3.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "vic20memoryexpansionwidget.h"
Data Structures
struct common_config_s
Struct containing information on the "common configurations".
Macros
#define RAM_BLOCK_COUNT 5
Number of RAM blocks that can be enabled in xvic.
Typedefs
typedef struct common_config_s common_config_t
Struct containing information on the "common configurations".
Functions
static int get_common_config_index (GtkWidget *widget)
Get index in common configs array.
static void update_common_config_combo (GtkWidget *widget)
Update the common configs combo box when a RAM block toggle changed.
static void on_ram_block_toggled (GtkWidget *widget, gpointer user_data)
Handler for the "toggled" event of the check buttons.
static void on_common_config_changed (GtkWidget *widget, gpointer user_data)
Handler for the "changed" event of the "commong config" combobox.
static GtkWidget * vic20_common_config_widget_create (void)
Create VIC20 common RAM configurations widget.
static GtkWidget * vic20_ram_blocks_widget_create (void)
Create VIC20 RAM blocks widget.
GtkWidget * vic20_memory_expansion_widget_create (void)
Create VIC20 memory expansion widget.
Variables
static const vice_gtk3_radiogroup_entry_t ram_blocks []
List of available RAM expansions.
static const common_config_t common_configs []
List of common memory expansion configurations.
static GtkWidget * blocks_widget = NULL
Reference to the RAM blocks widget.
static GtkWidget * configs_combo = NULL
Reference to the common configs combo box.
Detailed Description
VIC20 memory expansion widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Allow enabling/disabling VIC-20 RAM expansions, and also provides a list of common memory expansion configurations.
Macro Definition Documentation
RAM_BLOCK_COUNT
#define RAM_BLOCK_COUNT 5
Number of RAM blocks that can be enabled in xvic.
Typedef Documentation
common_config_t
typedef struct common_config_s common_config_t
Struct containing information on the "common configurations".
Function Documentation
get_common_config_index()
static int get_common_config_index (GtkWidget * widget) static
Get index in common configs array.
Inspects the various RAM blocks and tries to find a matching entry in the common configs array.
Parameters
[in] widget widget containing the check buttons
Returns
index in the common configs array, or -1 when not found
Note
Probably can remove the widget argument, we have a reference to that with the 'blocks_widget'.
Referenced by update_common_config_combo(), and vic20_memory_expansion_widget_create().
on_common_config_changed()
static void on_common_config_changed (GtkWidget * widget, gpointer user_data) static
Handler for the "changed" event of the "commong config" combobox.
If a valid item is selected, this sets the check buttons determining which RAM expansions are enabled. The event handlers of the check buttons will set the proper resources.
Parameters
[in] widget "common config" combo box
[in] user_data data for the event (unused)
Referenced by vic20_common_config_widget_create().
on_ram_block_toggled()
static void on_ram_block_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the "toggled" event of the check buttons.
Parameters
[in] widget check button triggering the event
[in] user_data RAM block ID (int)
Referenced by vic20_ram_blocks_widget_create().
update_common_config_combo()
static void update_common_config_combo (GtkWidget * widget) static
Update the common configs combo box when a RAM block toggle changed.
Collects the current configuration of enabled RAM blocks and checks that against commenly used configs and sets the combo box accordingly.
Parameters
[in] widget RAM block toggle button
Referenced by on_ram_block_toggled().
vic20_common_config_widget_create()
static GtkWidget * vic20_common_config_widget_create (void) static
Create VIC20 common RAM configurations widget.
Returns
GtkGrid
Referenced by vic20_memory_expansion_widget_create().
vic20_memory_expansion_widget_create()
GtkWidget * vic20_memory_expansion_widget_create (void)
Create VIC20 memory expansion widget.
Contains two sub-widgets, one "common configurations" combo box, and one group of check buttons to enable/disable each RAM expansion
Returns
GtkGrid
Referenced by create_vic20_layout().
vic20_ram_blocks_widget_create()
static GtkWidget * vic20_ram_blocks_widget_create (void) static
Create VIC20 RAM blocks widget.
Returns
GtkGrid
Referenced by vic20_memory_expansion_widget_create().
Variable Documentation
blocks_widget
GtkWidget* blocks_widget = NULL static
Reference to the RAM blocks widget.
Used by the combo box to set the proper check buttons
Referenced by on_common_config_changed(), and vic20_memory_expansion_widget_create().
common_configs
const common_config_t common_configs[] static
Initial value:
= {
    { "No expansion memory",    { false, false, false, false, false } },
    { "3KiB (block 0)",         { true,  false, false, false, false } },
    { "8KiB (block 1)",         { false, true,  false, false, false } },
    { "16KiB (blocks 1+2)",     { false, true,  true,  false, false } },
    { "24KiB (blocks 1+2+3)",   { false, true,  true,  true,  false } },
    { "All (blocks 0+1+2+3+5)", { true,  true,  true,  true,  true  } },
    { NULL,                     { false, false, false, false, false } }
}
List of common memory expansion configurations.
Taken from the Gtk2 UI, kinda.
Referenced by get_common_config_index(), on_common_config_changed(), and vic20_common_config_widget_create().
configs_combo
GtkWidget* configs_combo = NULL static
Reference to the common configs combo box.
Used by the toggle buttons to set the proper common config
Referenced by update_common_config_combo(), vic20_common_config_widget_create(), and vic20_memory_expansion_widget_create().
ram_blocks
const vice_gtk3_radiogroup_entry_t ram_blocks[] static
Initial value:
= {
    { "Block 0 (3KiB at $0400-$0FFF)", 0 },
    { "Block 1 (8KiB at $2000-$3FFF)", 1 },
    { "Block 2 (8KiB at $4000-$5FFF)", 2 },
    { "Block 3 (8KiB at $6000-$7FFF)", 3 },
    { "Block 5 (8KiB at $A000-$BFFF)", 5 },
     { NULL, -1 }
}
List of available RAM expansions.
Referenced by vic20_ram_blocks_widget_create().