vsid: monitor_cartridge_commands_s Struct Reference
monitor_cartridge_commands_s Struct Reference
#include <monitor.h>
Data Fields
int(* cartridge_attach_image)(int type, const char *filename)
void(* cartridge_detach_image)(int type)
void(* cartridge_trigger_freeze)(void)
void(* cartridge_trigger_freeze_nmi_only)(void)
void(* export_dump)(void)
Field Documentation
cartridge_attach_image
int(* monitor_cartridge_commands_s::cartridge_attach_image) (int type, const char *filename)
Referenced by mon_attach(), and monitor_cmdline_options_init().
cartridge_detach_image
void(* monitor_cartridge_commands_s::cartridge_detach_image) (int type)
Referenced by mon_detach(), and monitor_cmdline_options_init().
cartridge_trigger_freeze
void(* monitor_cartridge_commands_s::cartridge_trigger_freeze) (void)
Referenced by mon_cart_freeze(), and monitor_cmdline_options_init().
cartridge_trigger_freeze_nmi_only
void(* monitor_cartridge_commands_s::cartridge_trigger_freeze_nmi_only) (void)
Referenced by monitor_cmdline_options_init().
export_dump
void(* monitor_cartridge_commands_s::export_dump) (void)
Referenced by mon_export().
The documentation for this struct was generated from the following file:
monitor.h