vsid: drive/viad.h File Reference
viad.h File Reference
#include "types.h"
Functions
void via2d_setup_context (struct diskunit_context_s *ctxptr)
void via2d_init (struct diskunit_context_s *ctxptr)
void via2d_store (struct diskunit_context_s *ctxptr, uint16_t addr, uint8_t byte)
uint8_t via2d_read (struct diskunit_context_s *ctxptr, uint16_t addr)
uint8_t via2d_peek (struct diskunit_context_s *ctxptr, uint16_t addr)
int via2d_dump (struct diskunit_context_s *ctxptr, uint16_t addr)
void via2d_update_pcr (int pcrval, struct drive_s *dptr)
Function Documentation
via2d_dump()
int via2d_dump (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by drivemem_ioreg_list_get().
via2d_init()
void via2d_init (struct diskunit_context_s * ctxptr)
via2d_peek()
uint8_t via2d_peek (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memiec_init().
via2d_read()
uint8_t via2d_read (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memiec_init().
via2d_setup_context()
void via2d_setup_context (struct diskunit_context_s * ctxptr)
via2d_store()
void via2d_store (struct diskunit_context_s * ctxptr, uint16_t addr, uint8_t byte)
Referenced by memiec_init().
via2d_update_pcr()
void via2d_update_pcr (int pcrval, struct drive_s * dptr)
Referenced by undump_pcr().