vsid: arch/shared/hotkeys/boolexpr.h File Reference
boolexpr.h File Reference
Boolean expression evaluation - header.
#include <stdbool.h>
Enumerations
enum {
BEXPR_INVALID = -1 ,
BEXPR_FALSE ,
BEXPR_TRUE ,
BEXPR_LPAREN ,
BEXPR_RPAREN ,
BEXPR_NOT ,
BEXPR_AND ,
BEXPR_OR
}
enum {
BEXPR_ERR_OK = 0 ,
BEXPR_ERR_FATAL ,
BEXPR_ERR_EXPECTED_TOKEN ,
BEXPR_ERR_INVALID_TOKEN ,
BEXPR_ERR_EXPECTED_LPAREN ,
BEXPR_ERR_EXPECTED_RPAREN ,
BEXPR_ERR_UNMATCHED_PARENS ,
BEXPR_ERR_EMPTY_EXPRESSION ,
BEXPR_ERR_MISSING_OPERAND ,
BEXPR_ERROR_COUNT
}
Error codes.
Functions
const char * bexpr_strerror (int errnum)
Get error message for error number.
void bexpr_init (void)
Initialize expression for use.
void bexpr_reset (void)
Reset tokenizer and evaluator for new expression.
void bexpr_free (void)
Free memory used by expression.
void bexpr_print (void)
Print tokenized expression on stdout.
int bexpr_token_parse (const char *text, const char **endptr)
Parse text for a valid token.
bool bexpr_token_add (int token)
Add token to expression.
bool bexpr_tokenize (const char *text)
Generate expression from a string.
bool bexpr_evaluate (bool *result)
Evaluate boolean expression.
Variables
int bexpr_errno
Error code.
Detailed Description
Boolean expression evaluation - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BEXPR_INVALID
invalid token
BEXPR_FALSE
FALSE constant.
BEXPR_TRUE
TRUE constant.
BEXPR_LPAREN
left parenthesis '('
BEXPR_RPAREN
right parenthesis ')'
BEXPR_NOT
logical NOT operator '&&'
BEXPR_AND
logical AND operator '!'
BEXPR_OR
logical OR operator '||'
anonymous enum
anonymous enum
Error codes.
Enumerator
BEXPR_ERR_OK
OK (no error)
BEXPR_ERR_FATAL
fatal error, should not normally happen
BEXPR_ERR_EXPECTED_TOKEN
parser expected a token
BEXPR_ERR_INVALID_TOKEN
parser didn't recognize token
BEXPR_ERR_EXPECTED_LPAREN
expected left parenthesis
BEXPR_ERR_EXPECTED_RPAREN
expected right parenthesis
BEXPR_ERR_UNMATCHED_PARENS
unmatched parenthesis
BEXPR_ERR_EMPTY_EXPRESSION
empty expression
BEXPR_ERR_MISSING_OPERAND
missing operand for operator
BEXPR_ERROR_COUNT
Function Documentation
bexpr_evaluate()
bool bexpr_evaluate (bool * result)
Evaluate boolean expression.
Evaluate boolean expression, either obtained by bexpr_parse() or by adding tokens with bexpr_add_token().
Parameters
[out] result result of evaluation
Returns
true on succes
Referenced by vhk_parser_do_if().
bexpr_free()
void bexpr_free (void)
Free memory used by expression.
Free all memory used by the expression, including the operator stack and the output queue.
Referenced by vhk_parser_shutdown().
bexpr_init()
void bexpr_init (void)
Initialize expression for use.
Allocate memory for tokenizer and evaluator.
Referenced by vhk_parser_init().
bexpr_print()
void bexpr_print (void)
Print tokenized expression on stdout.
bexpr_reset()
void bexpr_reset (void)
Reset tokenizer and evaluator for new expression.
Reset internal data structures for new expression, without freeing and then allocating resources again.
If using this module multiple times during the lifetime of a program (which is likely), do not call bexpr_free() followed by bexpr_init() when having to handle another expression, but call this function instead.
Referenced by vhk_parser_do_if().
bexpr_strerror()
const char * bexpr_strerror (int errnum)
Get error message for error number.
Parameters
[in] errnum error number
Returns
error message
Referenced by vhk_parser_do_if().
bexpr_token_add()
bool bexpr_token_add (int id)
Add token to expression.
Parameters
[in] id token ID
Returns
false if token id is invalid
Referenced by bexpr_tokenize(), and vhk_parser_do_if().
bexpr_token_parse()
int bexpr_token_parse (const char * text, const char ** endptr)
Parse text for a valid token.
Parse text looking for a valid token text, and if found return the ID. A pointer to the first non-valid character in text is stored in endptr if endptr isn't NULL.
Parameters
[in] text text to parse
[out] endptr location in text of first non-token character
Returns
token ID or BEXPR_INVALID on error
Exceptions
BEXPR_ERR_EXPECTED_TOKEN
BEXPR_ERR_INVALID_TOKEN
Referenced by bexpr_tokenize(), and vhk_parser_do_if().
bexpr_tokenize()
bool bexpr_tokenize (const char * text)
Generate expression from a string.
Parse text and tokenize into an expression. There is no syntax checking performed, only splitting the text into tokens for the evaluator.
Parameters
[in] text string to tokenize
Returns
true on success
Variable Documentation
bexpr_errno
int bexpr_errno extern
Error code.
Referenced by bexpr_evaluate(), bexpr_init(), bexpr_reset(), and vhk_parser_do_if().