vsid: c64/plus60k.c File Reference
plus60k.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "c64cart.h"
#include "c64mem.h"
#include "cartio.h"
#include "cartridge.h"
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "mem.h"
#include "monitor.h"
#include "resources.h"
#include "plus60k.h"
#include "snapshot.h"
#include "types.h"
#include "uiapi.h"
#include "util.h"
#include "vicii.h"
#include "vicii-mem.h"
Macros
#define SNAP_MAJOR 0
#define SNAP_MINOR 1
Functions
static int plus60k_activate (void)
static int plus60k_deactivate (void)
static int plus60k_dump (void)
static uint8_t plus60k_ff_read (uint16_t addr)
static uint8_t plus60k_peek (uint16_t addr)
static void plus60k_vicii_store (uint16_t addr, uint8_t value)
int set_plus60k_enabled (int value, int disable_reset)
static int set_plus60k_filename (const char *name, void *param)
static int set_plus60k_base (int val, void *param)
int plus60k_resources_init (void)
void plus60k_resources_shutdown (void)
int plus60k_cmdline_options_init (void)
void plus60k_init (void)
void plus60k_reset (void)
void plus60k_shutdown (void)
static void plus60k_memory_store (uint16_t addr, uint8_t value)
static void vicii_mem_vbank_store_wrapper (uint16_t addr, uint8_t value)
static void vicii_mem_vbank_39xx_store_wrapper (uint16_t addr, uint8_t value)
static void vicii_mem_vbank_3fxx_store_wrapper (uint16_t addr, uint8_t value)
static void ram_hi_store_wrapper (uint16_t addr, uint8_t value)
void plus60k_vicii_mem_vbank_store (uint16_t addr, uint8_t value)
void plus60k_vicii_mem_vbank_39xx_store (uint16_t addr, uint8_t value)
void plus60k_vicii_mem_vbank_3fxx_store (uint16_t addr, uint8_t value)
void plus60k_ram_hi_store (uint16_t addr, uint8_t value)
uint8_t plus60k_ram_read (uint16_t addr)
void plus60k_ram_store (uint16_t addr, uint8_t value)
void plus60k_ram_inject (uint16_t addr, uint8_t value)
int plus60k_snapshot_write (struct snapshot_s *s)
int plus60k_snapshot_read (struct snapshot_s *s)
Variables
static uint8_t plus60k_reg = 0
PLUS60K registers.
static log_t plus60k_log = ((log_t)-1)
int plus60k_enabled = 0
int plus60k_base = 0xd100
static char * plus60k_filename = NULL
Filename of the +60K image.
static uint8_t * plus60k_ram
static io_source_t vicii_d000_device
When the +60K device is active and the device base is at $d040, this device is used instead of the default VICII device.
static io_source_t vicii_d000_full_device
When the +60K device is active and the device base is at $d100, this device is used instead of the default VICII device.
static io_source_t vicii_d040_device
static io_source_t vicii_d100_device
static io_source_list_t * vicii_d000_list_item = NULL
static io_source_list_t * vicii_d000_full_list_item = NULL
static io_source_list_t * vicii_d040_list_item = NULL
static io_source_list_t * vicii_d100_list_item = NULL
static const resource_string_t resources_string []
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
static store_func_ptr_t plus60k_mem_write_tab []
static char snap_module_name [] = "PLUS60K"
Macro Definition Documentation
SNAP_MAJOR
#define SNAP_MAJOR 0
SNAP_MINOR
#define SNAP_MINOR 1
Function Documentation
plus60k_activate()
static int plus60k_activate (void) static
Referenced by set_plus60k_base(), set_plus60k_enabled(), and set_plus60k_filename().
plus60k_cmdline_options_init()
int plus60k_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
plus60k_deactivate()
static int plus60k_deactivate (void) static
Referenced by plus60k_shutdown(), set_plus60k_base(), set_plus60k_enabled(), and set_plus60k_filename().
plus60k_dump()
static int plus60k_dump (void) static
plus60k_ff_read()
static uint8_t plus60k_ff_read (uint16_t addr) static
plus60k_init()
void plus60k_init (void)
Referenced by machine_specific_init().
plus60k_memory_store()
static void plus60k_memory_store (uint16_t addr, uint8_t value) static
plus60k_peek()
static uint8_t plus60k_peek (uint16_t addr) static
plus60k_ram_hi_store()
void plus60k_ram_hi_store (uint16_t addr, uint8_t value)
Referenced by plus60k_init_config().
plus60k_ram_inject()
void plus60k_ram_inject (uint16_t addr, uint8_t value)
Referenced by memory_hacks_ram_inject().
plus60k_ram_read()
uint8_t plus60k_ram_read (uint16_t addr)
Referenced by plus60k_init_config().
plus60k_ram_store()
void plus60k_ram_store (uint16_t addr, uint8_t value)
Referenced by plus60k_init_config(), and plus60k_ram_inject().
plus60k_reset()
void plus60k_reset (void)
Referenced by machine_specific_reset(), and plus60k_activate().
plus60k_resources_init()
int plus60k_resources_init (void)
Referenced by machine_resources_init().
plus60k_resources_shutdown()
void plus60k_resources_shutdown (void)
Referenced by machine_resources_shutdown().
plus60k_shutdown()
void plus60k_shutdown (void)
Referenced by machine_specific_shutdown().
plus60k_snapshot_read()
int plus60k_snapshot_read (struct snapshot_s * s)
Referenced by memhacks_snapshot_read_modules().
plus60k_snapshot_write()
int plus60k_snapshot_write (struct snapshot_s * s)
Referenced by memhacks_snapshot_write_modules().
plus60k_vicii_mem_vbank_39xx_store()
void plus60k_vicii_mem_vbank_39xx_store (uint16_t addr, uint8_t value)
Referenced by plus60k_init_config().
plus60k_vicii_mem_vbank_3fxx_store()
void plus60k_vicii_mem_vbank_3fxx_store (uint16_t addr, uint8_t value)
Referenced by plus60k_init_config().
plus60k_vicii_mem_vbank_store()
void plus60k_vicii_mem_vbank_store (uint16_t addr, uint8_t value)
Referenced by plus60k_init_config().
plus60k_vicii_store()
static void plus60k_vicii_store (uint16_t addr, uint8_t value) static
ram_hi_store_wrapper()
static void ram_hi_store_wrapper (uint16_t addr, uint8_t value) static
set_plus60k_base()
static int set_plus60k_base (int val, void * param) static
set_plus60k_enabled()
int set_plus60k_enabled (int value, int disable_reset)
Referenced by memhacks_snapshot_read_modules(), plus60k_snapshot_read(), and set_memory_hack().
set_plus60k_filename()
static int set_plus60k_filename (const char * name, void * param) static
vicii_mem_vbank_39xx_store_wrapper()
static void vicii_mem_vbank_39xx_store_wrapper (uint16_t addr, uint8_t value) static
vicii_mem_vbank_3fxx_store_wrapper()
static void vicii_mem_vbank_3fxx_store_wrapper (uint16_t addr, uint8_t value) static
vicii_mem_vbank_store_wrapper()
static void vicii_mem_vbank_store_wrapper (uint16_t addr, uint8_t value) static
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-plus60kimage", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "PLUS60Kfilename", NULL,
      "<Name>", "Specify name of PLUS60K image" },
    { "-plus60kbase", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "PLUS60Kbase", NULL,
      "<Base address>", "Base address of the PLUS60K expansion. (0xD040/0xD100)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by plus60k_cmdline_options_init().
plus60k_base
int plus60k_base = 0xd100
Referenced by plus60k_activate(), plus60k_snapshot_read(), plus60k_snapshot_write(), and set_plus60k_base().
plus60k_enabled
int plus60k_enabled = 0
Referenced by plus60k_init_config(), plus60k_ram_read(), plus60k_ram_store(), plus60k_shutdown(), set_plus60k_base(), set_plus60k_enabled(), and set_plus60k_filename().
plus60k_filename
char* plus60k_filename = NULL static
Filename of the +60K image.
Referenced by plus60k_activate(), plus60k_deactivate(), plus60k_resources_shutdown(), and set_plus60k_filename().
plus60k_log
log_t plus60k_log = ((log_t)-1) static
Referenced by plus60k_activate(), plus60k_deactivate(), plus60k_init(), and set_plus60k_base().
plus60k_mem_write_tab
store_func_ptr_t plus60k_mem_write_tab[] static
Initial value:
= {
    vicii_mem_vbank_store_wrapper,
    plus60k_memory_store,
    vicii_mem_vbank_39xx_store_wrapper,
    plus60k_memory_store,
    vicii_mem_vbank_3fxx_store_wrapper,
    plus60k_memory_store,
    ram_hi_store_wrapper,
    plus60k_memory_store
}
Referenced by plus60k_ram_hi_store(), plus60k_vicii_mem_vbank_39xx_store(), plus60k_vicii_mem_vbank_3fxx_store(), and plus60k_vicii_mem_vbank_store().
plus60k_ram
uint8_t* plus60k_ram static
Referenced by plus60k_activate(), plus60k_deactivate(), plus60k_memory_store(), plus60k_ram_read(), plus60k_ram_store(), plus60k_snapshot_read(), and plus60k_snapshot_write().
plus60k_reg
uint8_t plus60k_reg = 0 static
PLUS60K registers.
Referenced by plus60k_dump(), plus60k_peek(), plus60k_ram_hi_store(), plus60k_ram_read(), plus60k_ram_store(), plus60k_reset(), plus60k_snapshot_read(), plus60k_snapshot_write(), plus60k_vicii_mem_vbank_39xx_store(), plus60k_vicii_mem_vbank_3fxx_store(), plus60k_vicii_mem_vbank_store(), and plus60k_vicii_store().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "PLUS60Kbase", 0xd100, RES_EVENT_NO, NULL,
      &plus60k_base, set_plus60k_base, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by plus60k_resources_init().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "PLUS60Kfilename", "", RES_EVENT_NO, NULL,
      &plus60k_filename, set_plus60k_filename, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by plus60k_resources_init().
snap_module_name
char snap_module_name[] = "PLUS60K" static
Referenced by plus60k_snapshot_read(), and plus60k_snapshot_write().
vicii_d000_device
io_source_t vicii_d000_device static
Initial value:
= {
    "VIC-II",
     2 ,
     NULL ,
    0xd000, 0xd03f, 0x3f,
    1,
    vicii_store,
    NULL,
    vicii_read,
    vicii_peek,
    vicii_dump,
    0,
     1  ,
    0,
     0
}
When the +60K device is active and the device base is at $d040, this device is used instead of the default VICII device.
Referenced by plus60k_activate().
vicii_d000_full_device
io_source_t vicii_d000_full_device static
Initial value:
= {
    "VIC-II",
     2 ,
     NULL ,
    0xd000, 0xd0ff, 0x3f,
    1,
    vicii_store,
    NULL,
    vicii_read,
    vicii_peek,
    vicii_dump,
    0,
     1  ,
    0,
     0
}
When the +60K device is active and the device base is at $d100, this device is used instead of the default VICII device.
Referenced by plus60k_activate().
vicii_d000_full_list_item
io_source_list_t* vicii_d000_full_list_item = NULL static
Referenced by plus60k_activate(), and plus60k_deactivate().
vicii_d000_list_item
io_source_list_t* vicii_d000_list_item = NULL static
Referenced by plus60k_activate(), and plus60k_deactivate().
vicii_d040_device
io_source_t vicii_d040_device static
Initial value:
= {
    "+60K",
     1 ,
    "PLUS60K",
    0xd040, 0xd0ff, 0x00,
    1,
    plus60k_vicii_store,
    NULL,
    plus60k_ff_read,
    plus60k_peek,
    plus60k_dump,
     -120  ,
     0  ,
    0,
     0
}
Referenced by plus60k_activate().
vicii_d040_list_item
io_source_list_t* vicii_d040_list_item = NULL static
Referenced by plus60k_activate(), and plus60k_deactivate().
vicii_d100_device
io_source_t vicii_d100_device static
Initial value:
= {
    "+60K",
     1 ,
    "PLUS60K",
    0xd100, 0xd1ff, 0x00,
    1,
    plus60k_vicii_store,
    NULL,
    plus60k_ff_read,
    plus60k_peek,
    plus60k_dump,
     -120  ,
     0  ,
    0,
     0
}
Referenced by plus60k_activate().
vicii_d100_list_item
io_source_list_t* vicii_d100_list_item = NULL static
Referenced by plus60k_activate(), and plus60k_deactivate().