vsid: vdrive/vdrive-internal.h File Reference
vdrive-internal.h File Reference
Functions
void vdrive_internal_init (void)
struct vdrive_s * vdrive_internal_open_fsimage (const char *name, unsigned int read_only)
int vdrive_internal_close_disk_image (struct vdrive_s *vdrive)
int vdrive_internal_create_format_disk_image (const char *filename, const char *diskname, unsigned int type)
Function Documentation
vdrive_internal_close_disk_image()
int vdrive_internal_close_disk_image (struct vdrive_s * vdrive)
Referenced by diskcontents_filesystem_read(), and vdrive_internal_format_disk_image().
vdrive_internal_create_format_disk_image()
int vdrive_internal_create_format_disk_image (const char * filename, const char * diskname, unsigned int type)
< HD in ASCII for CMDHD
Referenced by autostart_prg_with_disk_image(), and create_disk_image().
vdrive_internal_init()
void vdrive_internal_init (void)
Referenced by vdrive_init().
vdrive_internal_open_fsimage()
struct vdrive_s * vdrive_internal_open_fsimage (const char * name, unsigned int read_only)
Referenced by diskcontents_filesystem_read(), and vdrive_internal_format_disk_image().