vsid: parallel/parallel-trap.h File Reference
parallel-trap.h File Reference
#include "types.h"
Macros
#define PAR_STATUS_TIME_OUT_ON_WRITE 0x01
Same as SERIAL_EOF and SERIAL_DEVICE_NOT_PRESENT.
#define PAR_STATUS_TIME_OUT_ON_READ 0x02
#define PAR_STATUS_EOI 0x40
#define PAR_STATUS_DEVICE_NOT_PRESENT 0x80
Functions
int parallel_trap_attention (int b)
int parallel_trap_sendbyte (uint8_t data)
int parallel_trap_receivebyte (uint8_t *data, int fake)
Macro Definition Documentation
PAR_STATUS_DEVICE_NOT_PRESENT
#define PAR_STATUS_DEVICE_NOT_PRESENT 0x80
PAR_STATUS_EOI
#define PAR_STATUS_EOI 0x40
PAR_STATUS_TIME_OUT_ON_READ
#define PAR_STATUS_TIME_OUT_ON_READ 0x02
PAR_STATUS_TIME_OUT_ON_WRITE
#define PAR_STATUS_TIME_OUT_ON_WRITE 0x01
Same as SERIAL_EOF and SERIAL_DEVICE_NOT_PRESENT.
Function Documentation
parallel_trap_attention()
int parallel_trap_attention (int b)
Referenced by In1_DAV_true().
parallel_trap_receivebyte()
int parallel_trap_receivebyte (uint8_t * data, int fake)
Referenced by Out1_NRFD_false(), Out2_NDAC_false(), and parallelcommand().
parallel_trap_sendbyte()
int parallel_trap_sendbyte (uint8_t data)
Referenced by In1_DAV_true().