x128: init.c File Reference
init.c File Reference
#include "vice.h"
#include "archdep.h"
#include "attach.h"
#include "cmdline.h"
#include "console.h"
#include "debug.h"
#include "drive.h"
#include "initcmdline.h"
#include "keyboard.h"
#include "log.h"
#include "machine-bus.h"
#include "machine-video.h"
#include "machine.h"
#include "maincpu.h"
#include "monitor.h"
#include "monitor_binary.h"
#include "monitor_network.h"
#include "palette.h"
#include "ram.h"
#include "resources.h"
#include "romset.h"
#include "screenshot.h"
#include "signals.h"
#include "sysfile.h"
#include "uiapi.h"
#include "vdrive.h"
#include "video.h"
#include "vsync.h"
#include "init.h"
Macros
#define DBGINIT 1
#define DBG(x) printf x
Functions
int init_main_is_done (void)
returns true once everything is initialized and the UI has started up
void init_resource_fail (const char *module)
int init_resources (void)
void init_cmdline_options_fail (const char *module)
int init_cmdline_options (void)
static int main_init_hack (void)
int init_main (void)
Variables
static int init_done = 0
Macro Definition Documentation
DBG
#define DBG (x) printf x
DBGINIT
#define DBGINIT 1
Function Documentation
init_cmdline_options()
int init_cmdline_options (void)
Referenced by main_program().
init_cmdline_options_fail()
void init_cmdline_options_fail (const char * module)
Referenced by init_cmdline_options(), machine_cmdline_options_init(), and main_program().
init_main()
int init_main (void)
Todo:
FIXME: what's about uimon_init???
Referenced by main_program().
init_main_is_done()
int init_main_is_done (void)
returns true once everything is initialized and the UI has started up
Referenced by userport_set_device().
init_resource_fail()
void init_resource_fail (const char * module)
Referenced by init_resources(), and machine_resources_init().
init_resources()
int init_resources (void)
Referenced by main_program().
main_init_hack()
static int main_init_hack (void) static
Referenced by init_main().
Variable Documentation
init_done
int init_done = 0 static
Referenced by init_main(), init_main_is_done(), and socket_init().