x128: vicii/vicii-irq.c File Reference
vicii-irq.c File Reference
#include "vice.h"
#include "alarm.h"
#include "interrupt.h"
#include "maincpu.h"
#include "types.h"
#include "vicii-irq.h"
#include "viciitypes.h"
#include "c64dtvblitter.h"
#include "c64dtvdma.h"
Functions
void vicii_irq_set_line (void)
static void vicii_irq_set_line_clk (CLOCK mclk)
void vicii_irq_raster_set (CLOCK mclk)
void vicii_irq_raster_clear (CLOCK mclk)
void vicii_irq_sbcoll_set (void)
void vicii_irq_sbcoll_clear (void)
void vicii_irq_sscoll_set (void)
void vicii_irq_sscoll_clear (void)
void vicii_irq_lightpen_set (CLOCK mclk)
void vicii_irq_lightpen_clear (CLOCK mclk)
void vicii_irq_set_raster_line (unsigned int line)
void vicii_irq_check_state (uint8_t value, unsigned int high)
void vicii_irq_next_frame (void)
void vicii_irq_alarm_handler (CLOCK offset, void *data)
void vicii_irq_init (void)
Function Documentation
vicii_irq_alarm_handler()
void vicii_irq_alarm_handler (CLOCK offset, void * data)
Referenced by d019_store(), handle_fetch_sprite(), and vicii_irq_init().
vicii_irq_check_state()
void vicii_irq_check_state (uint8_t value, unsigned int high)
Referenced by d011_store(), and d012_store().
vicii_irq_init()
void vicii_irq_init (void)
Referenced by vicii_init().
vicii_irq_lightpen_clear()
void vicii_irq_lightpen_clear (CLOCK mclk)
vicii_irq_lightpen_set()
void vicii_irq_lightpen_set (CLOCK mclk)
Referenced by vicii_trigger_light_pen().
vicii_irq_next_frame()
void vicii_irq_next_frame (void)
Referenced by d019_store(), and vicii_irq_alarm_handler().
vicii_irq_raster_clear()
void vicii_irq_raster_clear (CLOCK mclk)
vicii_irq_raster_set()
void vicii_irq_raster_set (CLOCK mclk)
Referenced by vicii_irq_alarm_handler(), and vicii_irq_check_state().
vicii_irq_sbcoll_clear()
void vicii_irq_sbcoll_clear (void)
Referenced by d01f_read().
vicii_irq_sbcoll_set()
void vicii_irq_sbcoll_set (void)
Referenced by vicii_raster_draw_alarm_handler().
vicii_irq_set_line()
void vicii_irq_set_line (void)
Referenced by d019_store(), d01a_store(), vicii_irq_sbcoll_clear(), vicii_irq_sbcoll_set(), vicii_irq_sscoll_clear(), and vicii_irq_sscoll_set().
vicii_irq_set_line_clk()
static void vicii_irq_set_line_clk (CLOCK mclk) inline static
Referenced by vicii_irq_lightpen_clear(), vicii_irq_lightpen_set(), vicii_irq_raster_clear(), and vicii_irq_raster_set().
vicii_irq_set_raster_line()
void vicii_irq_set_raster_line (unsigned int line)
Referenced by d044_store(), vicii_irq_check_state(), and vicii_snapshot_read_module().
vicii_irq_sscoll_clear()
void vicii_irq_sscoll_clear (void)
Referenced by d01e_read().
vicii_irq_sscoll_set()
void vicii_irq_sscoll_set (void)
Referenced by vicii_raster_draw_alarm_handler().