x128: arch/gtk3/widgets/base/filechooserhelpers.h File Reference
filechooserhelpers.h File Reference
GtkFileChooser helper functions - header.
#include "vice.h"
#include <gtk/gtk.h>
Data Structures
struct ui_file_filter_s
Object to construct a GtkFileFilter with.
Typedefs
typedef struct ui_file_filter_s ui_file_filter_t
Object to construct a GtkFileFilter with.
Functions
GtkFileFilter * create_file_chooser_filter (const ui_file_filter_t filter, gboolean show_globs)
Create a GtkFileFilter instance from filter.
gchar * file_chooser_convert_to_locale (const gchar *text)
Convert UTF-8 encoded string text to the current locale.
gchar * file_chooser_convert_from_locale (const gchar *text)
Convert locale encoded string text to UTF-8.
Variables
const char * file_chooser_pattern_all []
Patterns for all files.
const char * file_chooser_pattern_cart []
Patterns for cartridge images.
const char * file_chooser_pattern_disk []
Patterns for disk images.
const char * file_chooser_pattern_floppy []
Patterns for disk images (non-GCR floppies only)
const char * file_chooser_pattern_tape []
Patterns for tapes.
const char * file_chooser_pattern_sid []
Patterns for PSID/SID/MUS files.
const char * file_chooser_pattern_fliplist []
Patterns for fliplists.
const char * file_chooser_pattern_playlist []
Patterns for playlists.
const char * file_chooser_pattern_program []
Patterns for program files.
const char * file_chooser_pattern_archive []
C64 native archives.
const char * file_chooser_pattern_compressed []
Patterns for host-compressed files.
const char * file_chooser_pattern_snapshot []
Patterns for snapshot files.
const char * file_chooser_pattern_hotkeys []
Patterns for hotkeys files.
const ui_file_filter_t file_chooser_filter_all
Filter for all files.
const ui_file_filter_t file_chooser_filter_cart
Filter for cartridge images.
const ui_file_filter_t file_chooser_filter_disk
Filter for disk images.
const ui_file_filter_t file_chooser_filter_tape
Filter for tape images.
const ui_file_filter_t file_chooser_filter_sid
Filter for SID files.
const ui_file_filter_t file_chooser_filter_fliplist
Filter for fliplist files.
const ui_file_filter_t file_chooser_filter_playlist
Filter for playlist files.
const ui_file_filter_t file_chooser_filter_program
Filter for program files.
const ui_file_filter_t file_chooser_filter_archive
Filter for archives.
const ui_file_filter_t file_chooser_filter_compressed
Filter for compressed files.
const ui_file_filter_t file_chooser_filter_snapshot
Filter for snapshot files.
const ui_file_filter_t file_chooser_filter_hotkeys
Filter for hotkeys files.
Detailed Description
GtkFileChooser helper functions - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Typedef Documentation
ui_file_filter_t
typedef struct ui_file_filter_s ui_file_filter_t
Object to construct a GtkFileFilter with.
Function Documentation
create_file_chooser_filter()
GtkFileFilter * create_file_chooser_filter (const ui_file_filter_t filter, gboolean show_globs)
Create a GtkFileFilter instance from filter.
Parameters
[in] filter name and patterns for the filter
[in] show_globs show file globbing pattern in the filter description
Example:
const ui_file_filter_t data = {
    "disk image",
    { "*.d64", "*.d71", "*.d8[0-2]", "*.dhd", NULL }
};
GtkFileFilter *filter = create_file_chooser_filter(data);
Returns
GtkFileFilter
Referenced by cart_dialog_internal(), create_disk_attach_dialog(), create_sid_attach_dialog(), create_smart_attach_dialog(), create_tape_attach_dialog(), save_snapshot_dialog(), ui_disk_create_dialog_show(), ui_fliplist_load_dialog_show(), ui_fliplist_save_dialog_show(), and vice_gtk3_open_file_dialog().
file_chooser_convert_from_locale()
gchar * file_chooser_convert_from_locale (const gchar * text)
Convert locale encoded string text to UTF-8.
Parameters
[in] text string in the current locale
Returns
text encoded to UTF-8, or the original string on failure
Note
the result must be freed after use with g_free()
Referenced by joystick_device_widget_create(), and ui_populate_fliplist_menu().
file_chooser_convert_to_locale()
gchar * file_chooser_convert_to_locale (const gchar * text)
Convert UTF-8 encoded string text to the current locale.
Parameters
[in] text UTF-8 encoded string
Returns
text encoded to the locale, or the original string on failure
Note
the result must be freed after use with g_free()
Referenced by do_attach(), do_autostart(), do_smart_attach(), on_response(), on_save_audio_filename(), on_save_screenshot_filename(), on_save_video_filename(), on_update_preview(), and update_preview().
Variable Documentation
file_chooser_filter_all
const ui_file_filter_t file_chooser_filter_all extern
Filter for all files.
Referenced by ui_fliplist_load_dialog_show(), and vice_gtk3_open_file_dialog().
file_chooser_filter_archive
const ui_file_filter_t file_chooser_filter_archive extern
Filter for archives.
file_chooser_filter_cart
const ui_file_filter_t file_chooser_filter_cart extern
Filter for cartridge images.
file_chooser_filter_compressed
const ui_file_filter_t file_chooser_filter_compressed extern
Filter for compressed files.
file_chooser_filter_disk
const ui_file_filter_t file_chooser_filter_disk extern
Filter for disk images.
Referenced by ui_disk_create_dialog_show().
file_chooser_filter_fliplist
const ui_file_filter_t file_chooser_filter_fliplist extern
Filter for fliplist files.
Referenced by ui_fliplist_load_dialog_show(), and ui_fliplist_save_dialog_show().
file_chooser_filter_hotkeys
const ui_file_filter_t file_chooser_filter_hotkeys extern
Filter for hotkeys files.
file_chooser_filter_playlist
const ui_file_filter_t file_chooser_filter_playlist extern
Filter for playlist files.
file_chooser_filter_program
const ui_file_filter_t file_chooser_filter_program extern
Filter for program files.
file_chooser_filter_sid
const ui_file_filter_t file_chooser_filter_sid extern
Filter for SID files.
file_chooser_filter_snapshot
const ui_file_filter_t file_chooser_filter_snapshot extern
Filter for snapshot files.
Referenced by save_snapshot_dialog().
file_chooser_filter_tape
const ui_file_filter_t file_chooser_filter_tape extern
Filter for tape images.
file_chooser_pattern_all
const char* file_chooser_pattern_all[] extern
Patterns for all files.
file_chooser_pattern_archive
const char* file_chooser_pattern_archive[] extern
C64 native archives.
Not all of these are supported, Lynx and ZipCoded disks are supported through calling c1541.
file_chooser_pattern_cart
const char* file_chooser_pattern_cart[] extern
Patterns for cartridge images.
file_chooser_pattern_compressed
const char* file_chooser_pattern_compressed[] extern
Patterns for host-compressed files.
XXX: Once we have libarchive implemented, we could probably query libarchive for the extensions supported
file_chooser_pattern_disk
const char* file_chooser_pattern_disk[] extern
Patterns for disk images.
file_chooser_pattern_fliplist
const char* file_chooser_pattern_fliplist[] extern
Patterns for fliplists.
file_chooser_pattern_floppy
const char* file_chooser_pattern_floppy[] extern
Patterns for disk images (non-GCR floppies only)
Used in the AutostartPrgDiskImage widget
file_chooser_pattern_hotkeys
const char* file_chooser_pattern_hotkeys[] extern
Patterns for hotkeys files.
Referenced by ui_hotkeys_load_dialog_show().
file_chooser_pattern_playlist
const char* file_chooser_pattern_playlist[] extern
Patterns for playlists.
Referenced by vsid_playlist_load().
file_chooser_pattern_program
const char* file_chooser_pattern_program[] extern
Patterns for program files.
file_chooser_pattern_sid
const char* file_chooser_pattern_sid[] extern
Patterns for PSID/SID/MUS files.
file_chooser_pattern_snapshot
const char* file_chooser_pattern_snapshot[] extern
Patterns for snapshot files.
file_chooser_pattern_tape
const char* file_chooser_pattern_tape[] extern
Patterns for tapes.
T64 is NOT a tape, so probably should be moved to a 'archive' pattern group, together with ZipCode, Lynx, Ark, etc.