vsid: keyboard.c File Reference
keyboard.c File Reference
Common keyboard emulation.
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>
#include "alarm.h"
#include "archdep.h"
#include "cmdline.h"
#include "joystick.h"
#include "kbd.h"
#include "keyboard.h"
#include "keymap.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "network.h"
#include "resources.h"
#include "snapshot.h"
#include "sysfile.h"
#include "types.h"
#include "util.h"
#include "vice-event.h"
Data Structures
struct KBD_QUEUE
Macros
#define RAND_MAX INT_MAX
#define DBG(x)
#define DBGKEY(x)
#define DBGMOD(x)
#define DBGMTX(x)
#define KEYBOARD_RAND() lib_unsigned_rand(1, (unsigned int)machine_get_cycles_per_frame())
#define KBD_QUEUE_MAX 8
that should be enough really
#define SNAP_MAJOR 1
#define SNAP_MINOR 1
#define SNAP_NAME "KEYBOARD"
Functions
static int keyboard_restore_pressed (void)
static int keyboard_restore_released (void)
static void keyboard_event_record (void)
static int keyboard_custom_key_func_by_keysym (int keysym, int pressed)
custom keys
static void keyboard_key_clear_internal (void)
static void keyboard_alarm_handler (CLOCK offset, void *data)
keyboard alarm handler, this consumes the host keyboard queue
void keyboard_clear_keymatrix (void)
void keyboard_register_machine (keyboard_machine_func_t func)
register a machine specific utility function that is called after the keyboard was latched
void keyboard_register_delay (unsigned int delay)
void keyboard_register_clear (void)
used from event code, queue a keyboard reset
static CLOCK kbd_make_event_timestap (CLOCK offset, int num)
static void kbd_limit_pointers (void)
static void kbd_retrigger_alarm (void)
static int kbd_queue_pushkey (int key, int mod, int pressed)
static int kbd_queue_popkey (int *key, int *mod, int *pressed)
static void keyboard_latch_matrix (CLOCK offset)
copy the latched keyarr (or what comes from the network) to the real keyarr
static int keyboard_set_latch_keyarr (int row, int col, int pressed)
update keyboard latch, returns 0 on success, -1 on error
void keyboard_set_keyarr (int row, int col, int value)
used for event playback, triggering keys from Joystick events, virtual keyboard
static void clear_modifier_flags (void)
static void clear_virtual_modifier_flags (void)
static void update_virtual_modifier_flags (void)
combine virtual modifier flags from all keys
static void keyboard_key_pressed_modifier (int row, int column, int shift)
press virtual modifier per key
static void keyboard_key_released_modifier (int row, int column, int shift)
release virtual modifier per key
static void keyboard_latch_modifier_states (void)
combine virtual and "real" modifier flags and latch them into the latch_keyarr matrix
static int keyboard_key_pressed_matrix (int row, int column, int shift)
static int keyboard_key_released_matrix (int row, int column, int shift)
static int keyboard_key_matrix_pressed (int row, int column, int shift, int pressed)
static int keyb_find_in_keyconvtab (int sym, int mod)
static void kbd_key_pressed (signed long key, int mod, int pressed)
void keyboard_key_pressed (signed long key, int mod)
press a key, this is called by the UI.
void keyboard_key_released (signed long key, int mod)
release a key, this is called by the UI.
void keyboard_key_clear (void)
called by the ui
void keyboard_set_keyarr_any (int row, int col, int value)
used for event playback, triggering keys from Joystick events, virtual keyboard
static void restore_alarm_triggered (CLOCK offset, void *data)
static int key_restore1_pressed (int pressed)
static int key_restore2_pressed (int pressed)
void keyboard_register_joy_keypad (key_joy_keypad_func_t func)
joyport attached keypad.
int keyboard_get_shiftlock (void)
return emulated shift lock state to the UI
void keyboard_set_shiftlock (int state)
shift/lock handling, the emulation may also call this
void keyboard_register_custom_key (int id, key_custom_func_t func, char *name, int *keysym, int *keyflags)
CAUTION: the registered function MUST NOT call keyboard_custom_key_set()
int keyboard_custom_key_get (int id)
int keyboard_custom_key_set (int id, int state)
int keyboard_custom_key_toggle (int id)
void keyboard_alternative_set (int alternative)
switch to alternative set (x128)
static int keyboard_set_keyboard_statusbar (int val, void *param)
Resource handler for 'KbdStatusbar'.
int keyboard_statusbar_enabled (void)
Get "KbdStatusbar" directly.
void keyboard_event_playback (CLOCK offset, void *data)
void keyboard_restore_event_playback (CLOCK offset, void *data)
void keyboard_event_delayed_playback (void *data)
int keyboard_snapshot_write_module (snapshot_t *s)
int keyboard_snapshot_read_module (snapshot_t *s)
int keyboard_resources_init (void)
int keyboard_cmdline_options_init (void)
void keyboard_init (void)
void keyboard_shutdown (void)
Variables
static log_t keyboard_log = ((log_t)-2)
int keyarr [16]
int rev_keyarr [8]
static int latch_keyarr [16]
Keyboard status to be latched into the keyboard array.
static int latch_rev_keyarr [8]
static int network_keyarr [16]
static int network_rev_keyarr [8]
static int keyboard_shiftlock = 0
Shift lock state.
static alarm_t * keyboard_alarm = NULL
static keyboard_machine_func_t keyboard_machine_func = NULL
machine specific utility function that is called after the keyboard was latched
static CLOCK keyboard_delay = 0
static int keyboard_clear = 0
static int key_alternative = 0
Is an alternative mapping active?
static int left_shift_down
host modifier flags
static int right_shift_down
static int left_cbm_down
static int left_ctrl_down
static int virtual_shift_down
virtual modifiers (combined)
static int virtual_cbm_down
static int virtual_ctrl_down
static int virtual_deshift
static int virtual_modifier_flags [16][8]
virtual modifiers per emulated/mapped key
static CLOCK keyboard_latch_timestamp = 0
the last timestamp/delay goes here
static key_joy_keypad_func_t key_joy_keypad_func = NULL
joyport attached keypad.
signed long key_joy_keypad [4][5]
joyport attached keypad.
static int kbd_statusbar_enabled = 0
Resource value for KdbStatusbar.
static int kbd_queue_read = 0
static int kbd_queue_write = 0
static KBD_QUEUE kbd_queue [8]
static int restore_raw = 0
static int restore_delayed = 0
static int restore_quick_release = 0
static alarm_t * restore_alarm = NULL
static key_custom_info_t key_custom_info [5]
static const resource_int_t resources_int []
static cmdline_option_t const cmdline_options []
Detailed Description
Common keyboard emulation.
Author
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it
Jouko Valta jopi@.nosp@m.stek.nosp@m.t.oul.nosp@m.u.fi
Andre Fachat facha.nosp@m.t@ph.nosp@m.ysik..nosp@m.tu-c.nosp@m.hemni.nosp@m.tz.d.nosp@m.e
Bernhard Kuhn kuhn@.nosp@m.eiko.nosp@m.n.e-t.nosp@m.echn.nosp@m.ik.tu.nosp@m.-mue.nosp@m.nchen.nosp@m..de
groepaz groep.nosp@m.az@g.nosp@m.mx.ne.nosp@m.t
Macro Definition Documentation
DBG
#define DBG (x)
DBGKEY
#define DBGKEY (x)
DBGMOD
#define DBGMOD (x)
DBGMTX
#define DBGMTX (x)
KBD_QUEUE_MAX
#define KBD_QUEUE_MAX 8
that should be enough really
KEYBOARD_RAND
#define KEYBOARD_RAND () lib_unsigned_rand(1, (unsigned int)machine_get_cycles_per_frame())
RAND_MAX
#define RAND_MAX INT_MAX
SNAP_MAJOR
#define SNAP_MAJOR 1
SNAP_MINOR
#define SNAP_MINOR 1
SNAP_NAME
#define SNAP_NAME "KEYBOARD"
Function Documentation
clear_modifier_flags()
static void clear_modifier_flags (void) static
Referenced by keyboard_key_clear_internal().
clear_virtual_modifier_flags()
static void clear_virtual_modifier_flags (void) static
Referenced by keyboard_key_clear_internal().
kbd_key_pressed()
static void kbd_key_pressed (signed long key, int mod, int pressed) static
Referenced by keyboard_alarm_handler().
kbd_limit_pointers()
static void kbd_limit_pointers (void) static
< that should be enough really
< that should be enough really
Referenced by kbd_queue_popkey(), kbd_queue_pushkey(), and kbd_retrigger_alarm().
kbd_make_event_timestap()
static CLOCK kbd_make_event_timestap (CLOCK offset, int num) static
Referenced by kbd_limit_pointers(), kbd_retrigger_alarm(), keyboard_restore_pressed(), keyboard_restore_released(), keyboard_set_keyarr(), and restore_alarm_triggered().
kbd_queue_popkey()
static int kbd_queue_popkey (int * key, int * mod, int * pressed) static
< that should be enough really
Referenced by keyboard_alarm_handler().
kbd_queue_pushkey()
static int kbd_queue_pushkey (int key, int mod, int pressed) static
< that should be enough really
< that should be enough really
Referenced by keyboard_key_pressed(), and keyboard_key_released().
kbd_retrigger_alarm()
static void kbd_retrigger_alarm (void) static
Referenced by kbd_queue_pushkey(), keyboard_alarm_handler(), keyboard_key_pressed(), and keyboard_key_released().
key_restore1_pressed()
static int key_restore1_pressed (int pressed) static
key_restore2_pressed()
static int key_restore2_pressed (int pressed) static
keyb_find_in_keyconvtab()
static int keyb_find_in_keyconvtab (int sym, int mod) static
Referenced by kbd_key_pressed(), and keyboard_key_released().
keyboard_alarm_handler()
static void keyboard_alarm_handler (CLOCK offset, void * data) static
keyboard alarm handler, this consumes the host keyboard queue
< that should be enough really
< that should be enough really
Referenced by kbd_queue_pushkey(), and keyboard_init().
keyboard_alternative_set()
void keyboard_alternative_set (int alternative)
switch to alternative set (x128)
keyboard_clear_keymatrix()
void keyboard_clear_keymatrix (void)
Todo:
FIXME: the SDL port uses this directly
Referenced by keyboard_key_clear_internal().
keyboard_cmdline_options_init()
int keyboard_cmdline_options_init (void)
Referenced by init_cmdline_options().
keyboard_custom_key_func_by_keysym()
static int keyboard_custom_key_func_by_keysym (int keysym, int pressed) static
custom keys
called when custom key was pressed or released
Referenced by keyboard_key_pressed(), and keyboard_key_released().
keyboard_custom_key_get()
int keyboard_custom_key_get (int id)
Referenced by statusbar_speed_widget_update().
keyboard_custom_key_set()
int keyboard_custom_key_set (int id, int state)
keyboard_custom_key_toggle()
int keyboard_custom_key_toggle (int id)
Referenced by capslock_led_callback(), and mode4080_led_callback().
keyboard_event_delayed_playback()
void keyboard_event_delayed_playback (void * data)
alarm_set(keyboard_alarm, maincpu_clk + keyboard_delay);
Referenced by event_playback_event_list().
keyboard_event_playback()
void keyboard_event_playback (CLOCK offset, void * data)
Referenced by event_alarm_handler().
keyboard_event_record()
static void keyboard_event_record (void) static
Referenced by keyboard_alarm_handler().
keyboard_get_shiftlock()
int keyboard_get_shiftlock (void)
return emulated shift lock state to the UI
Referenced by ciapb_forcelow(), kbd_debug_widget_update(), kbd_sync_caps_lock(), and statusbar_speed_widget_update().
keyboard_init()
void keyboard_init (void)
Referenced by init_main().
keyboard_key_clear()
void keyboard_key_clear (void)
called by the ui
Referenced by kbd_event_handler().
keyboard_key_clear_internal()
static void keyboard_key_clear_internal (void) static
Referenced by kbd_limit_pointers(), kbd_queue_pushkey(), keyboard_event_delayed_playback(), and keyboard_key_clear().
keyboard_key_matrix_pressed()
static int keyboard_key_matrix_pressed (int row, int column, int shift, int pressed) static
Referenced by kbd_key_pressed().
keyboard_key_pressed()
void keyboard_key_pressed (signed long key, int mod)
press a key, this is called by the UI.
called by the ui
this fills the host keyboard queue.
Referenced by kbd_event_handler(), and keyboard_set_keyarr_any().
keyboard_key_pressed_matrix()
static int keyboard_key_pressed_matrix (int row, int column, int shift) static
Referenced by keyboard_key_matrix_pressed().
keyboard_key_pressed_modifier()
static void keyboard_key_pressed_modifier (int row, int column, int shift) inline static
press virtual modifier per key
Referenced by keyboard_key_pressed_matrix().
keyboard_key_released()
void keyboard_key_released (signed long key, int mod)
release a key, this is called by the UI.
this fills the host keyboard queue.
Referenced by kbd_event_handler(), and keyboard_set_keyarr_any().
keyboard_key_released_matrix()
static int keyboard_key_released_matrix (int row, int column, int shift) static
Referenced by keyboard_key_matrix_pressed().
keyboard_key_released_modifier()
static void keyboard_key_released_modifier (int row, int column, int shift) inline static
release virtual modifier per key
Referenced by keyboard_key_released_matrix().
keyboard_latch_matrix()
static void keyboard_latch_matrix (CLOCK offset) static
copy the latched keyarr (or what comes from the network) to the real keyarr
Referenced by keyboard_alarm_handler(), keyboard_event_delayed_playback(), keyboard_event_playback(), keyboard_set_keyarr(), and keyboard_set_shiftlock().
keyboard_latch_modifier_states()
static void keyboard_latch_modifier_states (void) static
combine virtual and "real" modifier flags and latch them into the latch_keyarr matrix
Referenced by keyboard_key_pressed_matrix(), keyboard_key_released_matrix(), and keyboard_set_shiftlock().
keyboard_register_clear()
void keyboard_register_clear (void)
used from event code, queue a keyboard reset
Referenced by event_playback_event_list().
keyboard_register_custom_key()
void keyboard_register_custom_key (int id, key_custom_func_t func, char * name, int * keysym, int * keyflags)
CAUTION: the registered function MUST NOT call keyboard_custom_key_set()
extra custom keys (see above)
keyboard_register_delay()
void keyboard_register_delay (unsigned int delay)
Referenced by event_playback_event_list().
keyboard_register_joy_keypad()
void keyboard_register_joy_keypad (key_joy_keypad_func_t func)
joyport attached keypad.
keyboard_register_machine()
void keyboard_register_machine (keyboard_machine_func_t func)
register a machine specific utility function that is called after the keyboard was latched
Referenced by c64keyboard_init().
keyboard_resources_init()
int keyboard_resources_init (void)
Referenced by init_resources().
keyboard_restore_event_playback()
void keyboard_restore_event_playback (CLOCK offset, void * data)
Referenced by event_alarm_handler(), and event_playback_event_list().
keyboard_restore_pressed()
static int keyboard_restore_pressed (void) static
Referenced by key_restore1_pressed(), and key_restore2_pressed().
keyboard_restore_released()
static int keyboard_restore_released (void) static
Referenced by key_restore1_pressed(), and key_restore2_pressed().
keyboard_set_keyarr()
void keyboard_set_keyarr (int row, int col, int value)
used for event playback, triggering keys from Joystick events, virtual keyboard
Todo:
FIXME: perhaps trigger alarm here?
Referenced by keyboard_set_keyarr_any().
keyboard_set_keyarr_any()
void keyboard_set_keyarr_any (int row, int col, int value)
used for event playback, triggering keys from Joystick events, virtual keyboard
keyboard_set_keyboard_statusbar()
static int keyboard_set_keyboard_statusbar (int val, void * param) static
Resource handler for 'KbdStatusbar'.
Enables/disables the display of the keyboard debugging on the statusbar
Parameters
[in] val enable display of widget
[in] param extra data (unused)
Returns
0
keyboard_set_latch_keyarr()
static int keyboard_set_latch_keyarr (int row, int col, int pressed) static
update keyboard latch, returns 0 on success, -1 on error
Referenced by kbd_key_pressed(), keyboard_event_playback(), keyboard_latch_modifier_states(), and keyboard_set_keyarr().
keyboard_set_shiftlock()
void keyboard_set_shiftlock (int state)
shift/lock handling, the emulation may also call this
Referenced by kbd_sync_caps_lock().
keyboard_shutdown()
void keyboard_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
keyboard_snapshot_read_module()
int keyboard_snapshot_read_module (snapshot_t * s)
Referenced by c64_snapshot_read().
keyboard_snapshot_write_module()
int keyboard_snapshot_write_module (snapshot_t * s)
Referenced by c64_snapshot_write().
keyboard_statusbar_enabled()
int keyboard_statusbar_enabled (void)
Get "KbdStatusbar" directly.
For UIs: get "KbdStatusbar" resource value without going through the resource system.
Returns
current value of "KbdStatusbar" resource
restore_alarm_triggered()
static void restore_alarm_triggered (CLOCK offset, void * data) static
Referenced by keyboard_init().
update_virtual_modifier_flags()
static void update_virtual_modifier_flags (void) inline static
combine virtual modifier flags from all keys
Referenced by keyboard_key_pressed_modifier(), and keyboard_key_released_modifier().
Variable Documentation
cmdline_options
cmdline_option_t const cmdline_options[] static
Initial value:
=
{
    { "-kbdstatusbar", SET_RESOURCE,  0 ,
        NULL, NULL, "KbdStatusbar", (resource_value_t)1,
        NULL, "Enable keyboard-status bar" },
    { "+kbdstatusbar", SET_RESOURCE,  0 ,
        NULL, NULL, "KbdStatusbar", (resource_value_t)0,
        NULL, "Disable keyboard-status bar" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by keyboard_cmdline_options_init().
kbd_queue
KBD_QUEUE kbd_queue[8] static
Referenced by kbd_queue_popkey(), kbd_queue_pushkey(), and keyboard_alarm_handler().
kbd_queue_read
int kbd_queue_read = 0 static
Referenced by kbd_limit_pointers(), kbd_queue_popkey(), kbd_queue_pushkey(), kbd_retrigger_alarm(), and keyboard_alarm_handler().
kbd_queue_write
int kbd_queue_write = 0 static
Referenced by kbd_limit_pointers(), kbd_queue_popkey(), kbd_queue_pushkey(), kbd_retrigger_alarm(), and keyboard_alarm_handler().
kbd_statusbar_enabled
int kbd_statusbar_enabled = 0 static
Resource value for KdbStatusbar.
Determines whether to show the keyboard debugging widget on the statusbar.
Referenced by keyboard_set_keyboard_statusbar(), and keyboard_statusbar_enabled().
key_alternative
int key_alternative = 0 static
Is an alternative mapping active?
Referenced by keyb_find_in_keyconvtab(), and keyboard_alternative_set().
key_custom_info
key_custom_info_t key_custom_info[5] static
Initial value:
= {
    { "NONE"    , NULL                ,  0     , 0, 0, NULL              , NULL                },
    { "RESTORE1", key_restore1_pressed,  1 , 0, 0, &key_ctrl_restore1, &key_flags_restore1 },
    { "RESTORE2", key_restore2_pressed,  2 , 0, 0, &key_ctrl_restore2, &key_flags_restore2 },
}
Referenced by keyboard_custom_key_func_by_keysym(), keyboard_custom_key_get(), keyboard_custom_key_set(), keyboard_custom_key_toggle(), and keyboard_register_custom_key().
key_joy_keypad
signed long key_joy_keypad[4][5]
joyport attached keypad.
Referenced by keyboard_key_pressed(), keyboard_key_released(), keyboard_keymap_dump(), keyboard_keyword_clear(), keyboard_parse_set_neg_row(), and keyboard_set_keyarr_any().
key_joy_keypad_func
key_joy_keypad_func_t key_joy_keypad_func = NULL static
joyport attached keypad.
Referenced by keyboard_key_pressed(), keyboard_key_released(), and keyboard_register_joy_keypad().
keyarr
int keyarr[16]
Todo:
FIXME: These ugly externs should go away sooner or later. currently these two arrays are the interface to the emulation (eg CIA core)
Referenced by keyboard_clear_keymatrix(), keyboard_event_playback(), keyboard_event_record(), keyboard_latch_matrix(), keyboard_snapshot_read_module(), keyboard_snapshot_write_module(), and matrix_activate_row().
keyboard_alarm
alarm_t* keyboard_alarm = NULL static
Referenced by kbd_limit_pointers(), kbd_retrigger_alarm(), keyboard_alarm_handler(), and keyboard_init().
keyboard_clear
int keyboard_clear = 0 static
Referenced by keyboard_event_delayed_playback(), and keyboard_register_clear().
keyboard_delay
CLOCK keyboard_delay = 0 static
Referenced by keyboard_register_delay().
keyboard_latch_timestamp
CLOCK keyboard_latch_timestamp = 0 static
the last timestamp/delay goes here
Referenced by kbd_make_event_timestap().
keyboard_log
log_t keyboard_log = ((log_t)-2) static
Referenced by kbd_limit_pointers(), keyboard_custom_key_func_by_keysym(), keyboard_init(), and update_virtual_modifier_flags().
keyboard_machine_func
keyboard_machine_func_t keyboard_machine_func = NULL static
machine specific utility function that is called after the keyboard was latched
Referenced by keyboard_latch_matrix(), and keyboard_register_machine().
keyboard_shiftlock
int keyboard_shiftlock = 0 static
Shift lock state.
(emulated keyboard)
Referenced by clear_modifier_flags(), keyboard_clear_keymatrix(), keyboard_get_shiftlock(), keyboard_key_pressed_matrix(), keyboard_key_pressed_modifier(), keyboard_key_released_matrix(), keyboard_key_released_modifier(), keyboard_latch_modifier_states(), and keyboard_set_shiftlock().
latch_keyarr
int latch_keyarr[16] static
Keyboard status to be latched into the keyboard array.
Referenced by kbd_key_pressed(), keyboard_clear_keymatrix(), keyboard_event_playback(), keyboard_latch_matrix(), and keyboard_set_latch_keyarr().
latch_rev_keyarr
int latch_rev_keyarr[8] static
Referenced by keyboard_clear_keymatrix(), keyboard_latch_matrix(), and keyboard_set_latch_keyarr().
left_cbm_down
int left_cbm_down static
Referenced by clear_modifier_flags(), keyboard_key_pressed_matrix(), keyboard_key_released_matrix(), keyboard_latch_modifier_states(), and update_virtual_modifier_flags().
left_ctrl_down
int left_ctrl_down static
Referenced by clear_modifier_flags(), keyboard_key_pressed_matrix(), keyboard_key_released_matrix(), keyboard_latch_modifier_states(), and update_virtual_modifier_flags().
left_shift_down
int left_shift_down static
host modifier flags
Referenced by clear_modifier_flags(), keyboard_key_pressed_matrix(), keyboard_key_released_matrix(), keyboard_latch_modifier_states(), and update_virtual_modifier_flags().
network_keyarr
int network_keyarr[16] static
Referenced by keyboard_event_delayed_playback(), and keyboard_latch_matrix().
network_rev_keyarr
int network_rev_keyarr[8] static
Referenced by keyboard_event_delayed_playback(), and keyboard_latch_matrix().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "KbdStatusbar", 0, RES_EVENT_NO, NULL,
      &kbd_statusbar_enabled, keyboard_set_keyboard_statusbar, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by keyboard_resources_init().
restore_alarm
alarm_t* restore_alarm = NULL static
Referenced by keyboard_init(), keyboard_restore_pressed(), keyboard_restore_released(), and restore_alarm_triggered().
restore_delayed
int restore_delayed = 0 static
Referenced by keyboard_restore_pressed(), keyboard_restore_released(), and restore_alarm_triggered().
restore_quick_release
int restore_quick_release = 0 static
Referenced by keyboard_restore_pressed(), keyboard_restore_released(), and restore_alarm_triggered().
restore_raw
int restore_raw = 0 static
Referenced by keyboard_restore_pressed(), and keyboard_restore_released().
rev_keyarr
int rev_keyarr[8]
Referenced by keyboard_clear_keymatrix(), keyboard_latch_matrix(), keyboard_snapshot_read_module(), keyboard_snapshot_write_module(), and matrix_activate_column().
right_shift_down
int right_shift_down static
Referenced by clear_modifier_flags(), keyboard_key_pressed_matrix(), keyboard_key_released_matrix(), keyboard_latch_modifier_states(), and update_virtual_modifier_flags().
virtual_cbm_down
int virtual_cbm_down static
Referenced by clear_modifier_flags(), keyboard_key_pressed_modifier(), keyboard_key_released_modifier(), keyboard_latch_modifier_states(), and update_virtual_modifier_flags().
virtual_ctrl_down
int virtual_ctrl_down static
Referenced by keyboard_key_pressed_modifier(), keyboard_key_released_modifier(), keyboard_latch_modifier_states(), and update_virtual_modifier_flags().
virtual_deshift
int virtual_deshift static
Referenced by clear_modifier_flags(), keyboard_key_pressed_modifier(), keyboard_key_released_modifier(), keyboard_latch_modifier_states(), and update_virtual_modifier_flags().
virtual_modifier_flags
int virtual_modifier_flags[16][8] static
virtual modifiers per emulated/mapped key
Referenced by clear_virtual_modifier_flags(), keyboard_key_pressed_modifier(), keyboard_key_released_modifier(), and update_virtual_modifier_flags().
virtual_shift_down
int virtual_shift_down static
virtual modifiers (combined)
Referenced by clear_modifier_flags(), keyboard_key_pressed_matrix(), keyboard_key_pressed_modifier(), keyboard_key_released_matrix(), keyboard_key_released_modifier(), keyboard_latch_modifier_states(), and update_virtual_modifier_flags().