x128: drive/ieee/fdc.h File Reference
fdc.h File Reference
#include "types.h"
Macros
#define FDC_UNUSED 0
FDC states.
#define FDC_RESET0 1
#define FDC_RESET1 2
#define FDC_RESET2 3
#define FDC_RUN 4
#define FDC_LAST_STATE 4
#define FDC_ERR_OK 1
fdc error codes to return to drive CPU
#define FDC_ERR_HEADER 2
#define FDC_ERR_SYNC 3
#define FDC_ERR_NOBLOCK 4
#define FDC_ERR_DCHECK 5
#define FDC_ERR_VERIFY 7
#define FDC_ERR_WPROT 8
#define FDC_ERR_HCHECK 9
#define FDC_ERR_BLENGTH 10
#define FDC_ERR_ID 11
#define FDC_ERR_FSPEED 12
#define FDC_ERR_DRIVE 15
#define FDC_ERR_DECODE 16
Functions
void fdc_init (struct diskunit_context_s *drv)
void fdc_reset (unsigned int fnum, unsigned int enabled)
int fdc_snapshot_read_module (struct snapshot_s *s, int drv)
int fdc_snapshot_write_module (struct snapshot_s *s, int drv)
int fdc_attach_image (struct disk_image_s *image, unsigned int unit, unsigned int drive)
int fdc_detach_image (struct disk_image_s *image, unsigned int unit, unsigned int drive)
Macro Definition Documentation
FDC_ERR_BLENGTH
#define FDC_ERR_BLENGTH 10
FDC_ERR_DCHECK
#define FDC_ERR_DCHECK 5
FDC_ERR_DECODE
#define FDC_ERR_DECODE 16
FDC_ERR_DRIVE
#define FDC_ERR_DRIVE 15
FDC_ERR_FSPEED
#define FDC_ERR_FSPEED 12
FDC_ERR_HCHECK
#define FDC_ERR_HCHECK 9
FDC_ERR_HEADER
#define FDC_ERR_HEADER 2
FDC_ERR_ID
#define FDC_ERR_ID 11
FDC_ERR_NOBLOCK
#define FDC_ERR_NOBLOCK 4
FDC_ERR_OK
#define FDC_ERR_OK 1
fdc error codes to return to drive CPU
FDC_ERR_SYNC
#define FDC_ERR_SYNC 3
FDC_ERR_VERIFY
#define FDC_ERR_VERIFY 7
FDC_ERR_WPROT
#define FDC_ERR_WPROT 8
FDC_LAST_STATE
#define FDC_LAST_STATE 4
FDC_RESET0
#define FDC_RESET0 1
FDC_RESET1
#define FDC_RESET1 2
FDC_RESET2
#define FDC_RESET2 3
FDC_RUN
#define FDC_RUN 4
FDC_UNUSED
#define FDC_UNUSED 0
FDC states.
Function Documentation
fdc_attach_image()
int fdc_attach_image (struct disk_image_s * image, unsigned int unit, unsigned int drive)
Todo:
FIXME: hack - we need to save the image to be able to re-attach when the disk drive type changes, in particular from the initial DRIVE_TYPE_NONE to a proper drive.
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 3.0 hard drive
< D9090/D9060
Referenced by fdc_reset(), and ieee_drive_image_attach().
fdc_detach_image()
int fdc_detach_image (struct disk_image_s * image, unsigned int unit, unsigned int drive)
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 3.0 hard drive
< D9090/D9060
Referenced by fdc_reset(), and ieee_drive_image_detach().
fdc_init()
void fdc_init (diskunit_context_t * drv)
Todo:
FIXME: hack, because 0x4000 is only ok for 1001/8050/8250. fdc.c:fdc_do_job() adds an offset for 2040/3040/4040 by itself :-(Why donlly get a table for that...!
Referenced by ieee_drive_init().
fdc_reset()
void fdc_reset (unsigned int fnum, unsigned int enabled)
Referenced by ieee_drive_reset().
fdc_snapshot_read_module()
int fdc_snapshot_read_module (struct snapshot_s * s, int drv)
Todo:
drive 1
Referenced by ieee_drive_snapshot_read().
fdc_snapshot_write_module()
int fdc_snapshot_write_module (struct snapshot_s * s, int drv)
Todo:
drive 1
Referenced by ieee_drive_snapshot_write().