x128: arch/gtk3/widgets/crtpreviewwidget.c File Reference
crtpreviewwidget.c File Reference
Widget to show CRT cart image data before attaching.
#include "vice.h"
#include <gtk/gtk.h>
#include <errno.h>
#include <string.h>
#include "vice_gtk3.h"
#include "crt.h"
#include "cartridge.h"
#include "log.h"
#include "machine.h"
#include "crtpreviewwidget.h"
Functions
static void load_to_hex (GtkTreeViewColumn *column, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
Renderer handler to print CHIP packet load address as hex.
static void size_to_hex (GtkTreeViewColumn *column, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
Renderer handler to print CHIP packet size as hex.
static GtkWidget * create_label (const char *s)
Create left-indented label.
static GtkWidget * create_tree_view (void)
Create CHIP packets view and model.
static void chip_packets_clear (void)
Delete all rows from the model.
static void chip_packet_add (uint16_t type, uint16_t load, uint16_t size, uint16_t bank)
Add a row to the CHIP packet table.
GtkWidget * crt_preview_widget_create (void)
Create cartridge preview widget.
void crt_preview_widget_update (const gchar *path)
Update widget with data from CTR image path.
Variables
static const gchar * packet_type [4]
CHIP packet type descriptions.
static const gchar * romstate [2]
Game/Exrom line state descriptions.
static GtkWidget * crtid_label = NULL
CRT ID label.
static GtkWidget * crtrevision_label = NULL
CRT revision label.
static GtkWidget * crtname_label = NULL
'brief CRT name label
static GtkWidget * exrom_label = NULL
EX ROM label.
static GtkWidget * game_label = NULL
Game title label.
static GtkWidget * chip_tree = NULL
GtkTreeView used for the CRT data display.
Detailed Description
Widget to show CRT cart image data before attaching.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
chip_packet_add()
static void chip_packet_add (uint16_t type, uint16_t load, uint16_t size, uint16_t bank) static
Add a row to the CHIP packet table.
Parameters
[in] type packet type
[in] load load address
[in] size packet size
[in] bank packet bank index
Referenced by crt_preview_widget_update().
chip_packets_clear()
static void chip_packets_clear (void) static
Delete all rows from the model.
Referenced by crt_preview_widget_update().
create_label()
static GtkWidget * create_label (const char * s) static
Create left-indented label.
Parameters
[in] s text for label
Returns
GtkLabel
Referenced by crt_preview_widget_create().
create_tree_view()
static GtkWidget * create_tree_view (void) static
Create CHIP packets view and model.
Returns
GtkTreeView
Referenced by crt_preview_widget_create().
crt_preview_widget_create()
GtkWidget * crt_preview_widget_create (void)
Create cartridge preview widget.
Returns
GtkGrid
Referenced by cart_dialog_internal().
crt_preview_widget_update()
void crt_preview_widget_update (const gchar * path)
Update widget with data from CTR image path.
Parameters
[in] path path to CRT file
Referenced by update_preview().
load_to_hex()
static void load_to_hex (GtkTreeViewColumn * column, GtkCellRenderer * renderer, GtkTreeModel * model, GtkTreeIter * iter, gpointer user_data) static
Renderer handler to print CHIP packet load address as hex.
Parameters
[in] column tree view column
[in,out] renderer cell renderer
[in] model tree model
[in] iter tree iterator
[in] user_data extra event data (unused)
Referenced by create_tree_view().
size_to_hex()
static void size_to_hex (GtkTreeViewColumn * column, GtkCellRenderer * renderer, GtkTreeModel * model, GtkTreeIter * iter, gpointer user_data) static
Renderer handler to print CHIP packet size as hex.
Parameters
[in] column tree view column
[in,out] renderer cell renderer
[in] model tree model
[in] iter tree iterator
[in] user_data extra event data (unused)
Referenced by create_tree_view().
Variable Documentation
chip_tree
GtkWidget* chip_tree = NULL static
GtkTreeView used for the CRT data display.
Referenced by chip_packet_add(), chip_packets_clear(), and crt_preview_widget_create().
crtid_label
GtkWidget* crtid_label = NULL static
CRT ID label.
Todo:
FIXME: Do we actually need all these references? Perhaps get them via gtk_grid_get_child_at() ?
Referenced by crt_preview_widget_create(), and crt_preview_widget_update().
crtname_label
GtkWidget* crtname_label = NULL static
'brief CRT name label
Referenced by crt_preview_widget_create(), and crt_preview_widget_update().
crtrevision_label
GtkWidget* crtrevision_label = NULL static
CRT revision label.
Referenced by crt_preview_widget_create(), and crt_preview_widget_update().
exrom_label
GtkWidget* exrom_label = NULL static
EX ROM label.
Referenced by crt_preview_widget_create(), and crt_preview_widget_update().
game_label
GtkWidget* game_label = NULL static
Game title label.
Referenced by crt_preview_widget_create(), and crt_preview_widget_update().
packet_type
const gchar* packet_type[4] static
Initial value:
= {
    "ROM", "RAM", "Flash", "<invalid>"
}
CHIP packet type descriptions.
Used for column 0
Referenced by chip_packet_add().
romstate
const gchar* romstate[2] static
Initial value:
= {
    "active (lo)", "inactive (hi)"
}
Game/Exrom line state descriptions.
Referenced by crt_preview_widget_update().