x128: rs232drv/rs232net.h File Reference
rs232net.h File Reference
#include "types.h"
Functions
void rs232net_init (void)
Initializes all RS232 stuff.
void rs232net_reset (void)
Reset for RS232 interfaces.
int rs232net_open (int device)
Opens a rs232 window, returns handle to give to functions below.
void rs232net_close (int fd)
Closes the rs232 window again.
int rs232net_putc (int fd, uint8_t b)
Sends a byte to the RS232 line.
int rs232net_getc (int fd, uint8_t *b)
Gets a byte to the RS232 line, returns !=1 if byte received, byte in *b.
int rs232net_set_status (int fd, enum rs232handshake_out status)
write the output handshake lines
enum rs232handshake_in rs232net_get_status (int fd)
write the output handshake lines
int rs232net_resources_init (void)
void rs232net_resources_shutdown (void)
int rs232net_cmdline_options_init (void)
Function Documentation
rs232net_close()
void rs232net_close (int fd)
Closes the rs232 window again.
Closes the rs232 window again.
< original patch only sends this once on rs232 reset
Referenced by rs232_close(), and rs232net_reset().
rs232net_cmdline_options_init()
int rs232net_cmdline_options_init (void)
Referenced by rs232_cmdline_options_init().
rs232net_get_status()
enum rs232handshake_in rs232net_get_status (int fd)
write the output handshake lines
write the output handshake lines
return RS232_HSI_CTS | RS232_HSI_DSR;
Referenced by rs232_get_status().
rs232net_getc()
int rs232net_getc (int fd, uint8_t * b)
Gets a byte to the RS232 line, returns !=1 if byte received, byte in *b.
Gets a byte to the RS232 line, returns !=1 if byte received, byte in *b.
Referenced by rs232_getc(), and rs232net_get_status().
rs232net_init()
void rs232net_init (void)
Initializes all RS232 stuff.
Initializes all RS232 stuff.
Referenced by rs232_init().
rs232net_open()
int rs232net_open (int device)
Opens a rs232 window, returns handle to give to functions below.
Opens a rs232 window, returns handle to give to functions below.
Referenced by rs232_open().
rs232net_putc()
int rs232net_putc (int fd, uint8_t b)
Sends a byte to the RS232 line.
Sends a byte to the RS232 line.
Referenced by rs232_putc().
rs232net_reset()
void rs232net_reset (void)
Reset for RS232 interfaces.
Reset for RS232 interfaces.
Referenced by rs232_reset().
rs232net_resources_init()
int rs232net_resources_init (void)
Referenced by rs232_resources_init().
rs232net_resources_shutdown()
void rs232net_resources_shutdown (void)
Referenced by rs232_resources_shutdown().
rs232net_set_status()
int rs232net_set_status (int fd, enum rs232handshake_out status)
write the output handshake lines
write the output handshake lines
< original patch only sends this once on 0->1 transition
< original patch only sends this once on rs232 reset
Referenced by rs232_set_status().