x128: arch/gtk3/widgets/settings_ds12c887.c File Reference
settings_ds12c887.c File Reference
Settings widget controlling DS12C887 RTC resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "cartridge.h"
#include "debug_gtk3.h"
#include "machine.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "settings_ds12c887.h"
Functions
static void set_widgets_sensitivity (gboolean sensitive)
Set sensitivity of widgets.
static void on_enable_toggled (GtkWidget *widget, gpointer user_data)
Handler for the "toggled" event of the enable widget.
static GtkWidget * create_base_widget (void)
Create widget to set I/O base for the RTC thing.
GtkWidget * settings_ds12c887_widget_create (GtkWidget *parent)
Create widget to control the DS12C887 RTC.
Variables
static const int io_base_c64 [] = { 0xd500, 0xd600, 0xd700, 0xde00, 0xdf00, -1 }
Values for I/O base on C64/C128.
static const int io_base_vic20 [] = { 0x9800, 0x9c00, -1 }
Values for I/O base on VIC-20.
static GtkWidget * oscil_widget = NULL
Reference to the oscilattor checkbox.
static GtkWidget * base_widget = NULL
Reference to the base widget.
static GtkWidget * rtc_widget = NULL
Reference to the 'RTC' widget.
Detailed Description
Settings widget controlling DS12C887 RTC resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_base_widget()
static GtkWidget * create_base_widget (void) static
Create widget to set I/O base for the RTC thing.
Sets the correct I/O base list for the current machine
Returns
GktComboBox
Referenced by settings_ds12c887_widget_create().
on_enable_toggled()
static void on_enable_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the "toggled" event of the enable widget.
Parameters
[in,out] widget "enable" toggle button
[in] user_data extra event data (unused)
Referenced by settings_ds12c887_widget_create().
set_widgets_sensitivity()
static void set_widgets_sensitivity (gboolean sensitive) static
Set sensitivity of widgets.
Parameters
[in] sensitive sensitivity
Referenced by on_enable_toggled(), and settings_ds12c887_widget_create().
settings_ds12c887_widget_create()
GtkWidget * settings_ds12c887_widget_create (GtkWidget * parent)
Create widget to control the DS12C887 RTC.
Parameters
[in] parent parent widget
Returns
GtkGrid
< Title of the page at http://ytm.bossstation.dnsalias.org/html/rtcds12c887.html
< ds12c887rtc.c
Variable Documentation
base_widget
GtkWidget* base_widget = NULL static
Reference to the base widget.
Referenced by set_widgets_sensitivity(), and settings_ds12c887_widget_create().
io_base_c64
const int io_base_c64[] = { 0xd500, 0xd600, 0xd700, 0xde00, 0xdf00, -1 } static
Values for I/O base on C64/C128.
The hardware appears to allow $d100, $d200 and $d300 as I/O-base but that's not emulated and thus not in this list.
Referenced by create_base_widget().
io_base_vic20
const int io_base_vic20[] = { 0x9800, 0x9c00, -1 } static
Values for I/O base on VIC-20.
Referenced by create_base_widget().
oscil_widget
GtkWidget* oscil_widget = NULL static
Reference to the oscilattor checkbox.
Referenced by set_widgets_sensitivity(), and settings_ds12c887_widget_create().
rtc_widget
GtkWidget* rtc_widget = NULL static
Reference to the 'RTC' widget.
Referenced by set_widgets_sensitivity(), and settings_ds12c887_widget_create().