vsid: arch/shared/archdep_home_path.c File Reference
archdep_home_path.c File Reference
Retrieve home directory of current user.
#include "vice.h"
#include "archdep_defs.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lib.h"
#include "log.h"
#include <unistd.h>
#include <sys/types.h>
#include <pwd.h>
#include "archdep_home_path.h"
Functions
const char * archdep_home_path (void)
Get user's home directory.
void archdep_home_path_free (void)
Free memory used by the home path.
Variables
static char * home_dir = NULL
home directory reference
Detailed Description
Retrieve home directory of current user.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Retrieve the home directory of the current user on systems that have a concept of a home directory. On systems that don't have a home dir '.' is returned (PROGDIR: in the case of AmigaOS). Of course on systems that don't have a home dir, this function simply shouldn't be used, archdep_boot_path() might be a better function.
OS support:
Linux
Windows
MacOS
BeOS/Haiku (always returns '/boot/home')
Function Documentation
archdep_home_path()
const char * archdep_home_path (void)
Get user's home directory.
Returns
user's home directory
Note
Free memory used on emulator exit with archdep_home_path_free().
Referenced by archdep_create_user_cache_dir(), archdep_create_user_config_dir(), archdep_default_portable_resource_file_name(), archdep_expand_path(), archdep_init(), archdep_xdg_cache_home(), archdep_xdg_config_home(), archdep_xdg_data_home(), archdep_xdg_state_home(), and mon_change_dir().
archdep_home_path_free()
void archdep_home_path_free (void)
Free memory used by the home path.
Referenced by archdep_shutdown().
Variable Documentation
home_dir
char* home_dir = NULL static
home directory reference
Allocated once in the first call to archdep_home_path(), should be freed on emulator exit with archdep_home_path_free()
Referenced by archdep_home_path(), and archdep_home_path_free().