vsid: gfxoutput.h File Reference
gfxoutput.h File Reference
#include "types.h"
Data Structures
struct gfxoutputdrv_codec_s
struct gfxoutputdrv_format_s
struct gfxoutputdrv_s
Macros
#define GFXOUTPUTDRV_HAS_AUDIO_CODECS (1 << 0)
bits for flags in gfxoutputdrv_format_t
#define GFXOUTPUTDRV_HAS_VIDEO_CODECS (1 << 1)
#define GFXOUTPUTDRV_HAS_AUDIO_BITRATE (1 << 2)
#define GFXOUTPUTDRV_HAS_VIDEO_BITRATE (1 << 3)
#define GFXOUTPUTDRV_HAS_HALF_VIDEO_FRAMERATE (1 << 4)
#define VICE_FFMPEG_VIDEO_RATE_MIN 100000
FFMPEG bitrate constants.
#define VICE_FFMPEG_VIDEO_RATE_MAX 10000000
#define VICE_FFMPEG_VIDEO_RATE_DEFAULT 800000
#define VICE_FFMPEG_AUDIO_RATE_MIN 16000
#define VICE_FFMPEG_AUDIO_RATE_MAX 384000
#define VICE_FFMPEG_AUDIO_RATE_DEFAULT 64000
Typedefs
typedef struct gfxoutputdrv_codec_s gfxoutputdrv_codec_t
typedef struct gfxoutputdrv_format_s gfxoutputdrv_format_t
typedef struct gfxoutputdrv_s gfxoutputdrv_t
Enumerations
enum {
NATIVE_SS_OVERSIZE_SCALE = 0 ,
NATIVE_SS_OVERSIZE_CROP_LEFT_TOP ,
NATIVE_SS_OVERSIZE_CROP_CENTER_TOP ,
NATIVE_SS_OVERSIZE_CROP_RIGHT_TOP ,
NATIVE_SS_OVERSIZE_CROP_LEFT_CENTER ,
NATIVE_SS_OVERSIZE_CROP_CENTER ,
NATIVE_SS_OVERSIZE_CROP_RIGHT_CENTER ,
NATIVE_SS_OVERSIZE_CROP_LEFT_BOTTOM ,
NATIVE_SS_OVERSIZE_CROP_CENTER_BOTTOM ,
NATIVE_SS_OVERSIZE_CROP_RIGHT_BOTTOM
}
Native screenshot drivers definitions.
enum {
NATIVE_SS_UNDERSIZE_SCALE = 0 ,
NATIVE_SS_UNDERSIZE_BORDERIZE
}
enum {
NATIVE_SS_MC2HR_BLACK_WHITE = 0 ,
NATIVE_SS_MC2HR_2_COLORS ,
NATIVE_SS_MC2HR_4_COLORS ,
NATIVE_SS_MC2HR_GRAY ,
NATIVE_SS_MC2HR_DITHER
}
enum {
NATIVE_SS_TED_LUM_IGNORE = 0 ,
NATIVE_SS_TED_LUM_DITHER
}
enum {
NATIVE_SS_CRTC_WHITE = 0 ,
NATIVE_SS_CRTC_AMBER ,
NATIVE_SS_CRTC_GREEN
}
enum {
GFXOUTPUTDRV_TYPE_SCREENSHOT_NATIVE = 0 ,
GFXOUTPUTDRV_TYPE_SCREENSHOT_IMAGE ,
GFXOUTPUTDRV_TYPE_VIDEO ,
GFXOUTPUTDRV_TYPE_MAX
}
Functions
int gfxoutput_resources_init (void)
Functions called by external emulator code.
int gfxoutput_cmdline_options_init (void)
int gfxoutput_early_init (int help)
int gfxoutput_init (void)
void gfxoutput_shutdown (void)
int gfxoutput_num_drivers (void)
gfxoutputdrv_t * gfxoutput_drivers_iter_init (void)
gfxoutputdrv_t * gfxoutput_drivers_iter_next (void)
gfxoutputdrv_t * gfxoutput_get_driver (const char *drvname)
int gfxoutput_register (gfxoutputdrv_t *drv)
Functions called by graphic output driver modules.
Macro Definition Documentation
GFXOUTPUTDRV_HAS_AUDIO_BITRATE
#define GFXOUTPUTDRV_HAS_AUDIO_BITRATE (1 << 2)
GFXOUTPUTDRV_HAS_AUDIO_CODECS
#define GFXOUTPUTDRV_HAS_AUDIO_CODECS (1 << 0)
bits for flags in gfxoutputdrv_format_t
GFXOUTPUTDRV_HAS_HALF_VIDEO_FRAMERATE
#define GFXOUTPUTDRV_HAS_HALF_VIDEO_FRAMERATE (1 << 4)
GFXOUTPUTDRV_HAS_VIDEO_BITRATE
#define GFXOUTPUTDRV_HAS_VIDEO_BITRATE (1 << 3)
GFXOUTPUTDRV_HAS_VIDEO_CODECS
#define GFXOUTPUTDRV_HAS_VIDEO_CODECS (1 << 1)
VICE_FFMPEG_AUDIO_RATE_DEFAULT
#define VICE_FFMPEG_AUDIO_RATE_DEFAULT 64000
VICE_FFMPEG_AUDIO_RATE_MAX
#define VICE_FFMPEG_AUDIO_RATE_MAX 384000
VICE_FFMPEG_AUDIO_RATE_MIN
#define VICE_FFMPEG_AUDIO_RATE_MIN 16000
VICE_FFMPEG_VIDEO_RATE_DEFAULT
#define VICE_FFMPEG_VIDEO_RATE_DEFAULT 800000
VICE_FFMPEG_VIDEO_RATE_MAX
#define VICE_FFMPEG_VIDEO_RATE_MAX 10000000
VICE_FFMPEG_VIDEO_RATE_MIN
#define VICE_FFMPEG_VIDEO_RATE_MIN 100000
FFMPEG bitrate constants.
Typedef Documentation
gfxoutputdrv_codec_t
typedef struct gfxoutputdrv_codec_s gfxoutputdrv_codec_t
gfxoutputdrv_format_t
typedef struct gfxoutputdrv_format_s gfxoutputdrv_format_t
gfxoutputdrv_t
typedef struct gfxoutputdrv_s gfxoutputdrv_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NATIVE_SS_TED_LUM_IGNORE
NATIVE_SS_TED_LUM_DITHER
anonymous enum
anonymous enum
Enumerator
NATIVE_SS_CRTC_WHITE
NATIVE_SS_CRTC_AMBER
NATIVE_SS_CRTC_GREEN
anonymous enum
anonymous enum
Enumerator
GFXOUTPUTDRV_TYPE_SCREENSHOT_NATIVE
GFXOUTPUTDRV_TYPE_SCREENSHOT_IMAGE
GFXOUTPUTDRV_TYPE_VIDEO
GFXOUTPUTDRV_TYPE_MAX
anonymous enum
anonymous enum
Native screenshot drivers definitions.
Enumerator
NATIVE_SS_OVERSIZE_SCALE
NATIVE_SS_OVERSIZE_CROP_LEFT_TOP
NATIVE_SS_OVERSIZE_CROP_CENTER_TOP
NATIVE_SS_OVERSIZE_CROP_RIGHT_TOP
NATIVE_SS_OVERSIZE_CROP_LEFT_CENTER
NATIVE_SS_OVERSIZE_CROP_CENTER
NATIVE_SS_OVERSIZE_CROP_RIGHT_CENTER
NATIVE_SS_OVERSIZE_CROP_LEFT_BOTTOM
NATIVE_SS_OVERSIZE_CROP_CENTER_BOTTOM
NATIVE_SS_OVERSIZE_CROP_RIGHT_BOTTOM
anonymous enum
anonymous enum
Enumerator
NATIVE_SS_UNDERSIZE_SCALE
NATIVE_SS_UNDERSIZE_BORDERIZE
anonymous enum
anonymous enum
Enumerator
NATIVE_SS_MC2HR_BLACK_WHITE
NATIVE_SS_MC2HR_2_COLORS
NATIVE_SS_MC2HR_4_COLORS
NATIVE_SS_MC2HR_GRAY
NATIVE_SS_MC2HR_DITHER
Function Documentation
gfxoutput_cmdline_options_init()
int gfxoutput_cmdline_options_init (void)
Referenced by main_program().
gfxoutput_drivers_iter_init()
gfxoutputdrv_t * gfxoutput_drivers_iter_init (void)
Todo:
FIXME: this stub can be removed once all GUI's have been adapted to not use this call for vsid
Referenced by create_video_driver_list(), and settings_snapshot_widget_create().
gfxoutput_drivers_iter_next()
gfxoutputdrv_t * gfxoutput_drivers_iter_next (void)
Todo:
FIXME: this stub can be removed once all GUI's have been adapted to not use this call for vsid
Referenced by create_video_driver_list(), and settings_snapshot_widget_create().
gfxoutput_early_init()
int gfxoutput_early_init (int help)
Referenced by main_program().
gfxoutput_get_driver()
gfxoutputdrv_t * gfxoutput_get_driver (const char * drvname)
Todo:
FIXME: this stub can be removed once all GUI's have been adapted to not use this call for vsid
Referenced by ffmpeg_widget_create(), output_graphics_open(), screenshot_get_fext_for_format(), and screenshot_save().
gfxoutput_init()
int gfxoutput_init (void)
Referenced by machine_specific_init().
gfxoutput_num_drivers()
int gfxoutput_num_drivers (void)
Referenced by create_video_driver_list().
gfxoutput_register()
int gfxoutput_register (gfxoutputdrv_t * drv)
Functions called by graphic output driver modules.
Referenced by gfxoutput_init_artstudio(), gfxoutput_init_bmp(), gfxoutput_init_ffmpegexe(), gfxoutput_init_godot(), gfxoutput_init_iff(), gfxoutput_init_koala(), gfxoutput_init_minipaint(), gfxoutput_init_pcx(), gfxoutput_init_ppm(), and gfxoutput_init_zmbv().
gfxoutput_resources_init()
int gfxoutput_resources_init (void)
Functions called by external emulator code.
Referenced by main_program().
gfxoutput_shutdown()
void gfxoutput_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().