vsid: raster/raster-sprite-status.c File Reference
raster-sprite-status.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "lib.h"
#include "raster-sprite-cache.h"
#include "raster-sprite-status.h"
#include "raster-sprite.h"
#include "raster.h"
#include "types.h"
Functions
static void raster_sprite_status_init (raster_sprite_status_t *status, unsigned int num_sprites, int sprite_offset)
static void raster_sprite_status_shutdown (raster_sprite_status_t *status, unsigned int num_sprites)
void raster_sprite_status_new (raster_t *raster, unsigned int num_sprites, int sprite_offset)
void raster_sprite_status_destroy (raster_t *raster)
void raster_sprite_status_reset (raster_sprite_status_t *status, int sprite_offset)
void raster_sprite_status_set_draw_function (raster_sprite_status_t *status, raster_sprite_status_draw_function_t function)
void raster_sprite_status_set_cache_function (raster_sprite_status_t *status, raster_sprite_status_cache_function_t function)
void raster_sprite_status_set_draw_partial_function (raster_sprite_status_t *status, raster_sprite_status_draw_partial_function_t function)
Function Documentation
raster_sprite_status_destroy()
void raster_sprite_status_destroy (raster_t * raster)
Referenced by vicii_shutdown().
raster_sprite_status_init()
static void raster_sprite_status_init (raster_sprite_status_t * status, unsigned int num_sprites, int sprite_offset) static
Referenced by raster_sprite_status_new().
raster_sprite_status_new()
void raster_sprite_status_new (raster_t * raster, unsigned int num_sprites, int sprite_offset)
Referenced by init_raster().
raster_sprite_status_reset()
void raster_sprite_status_reset (raster_sprite_status_t * status, int sprite_offset)
Referenced by raster_sprite_status_init(), and vicii_reset_registers().
raster_sprite_status_set_cache_function()
void raster_sprite_status_set_cache_function (raster_sprite_status_t * status, raster_sprite_status_cache_function_t function)
Referenced by vicii_sprites_init().
raster_sprite_status_set_draw_function()
void raster_sprite_status_set_draw_function (raster_sprite_status_t * status, raster_sprite_status_draw_function_t function)
Referenced by vicii_sprites_init().
raster_sprite_status_set_draw_partial_function()
void raster_sprite_status_set_draw_partial_function (raster_sprite_status_t * status, raster_sprite_status_draw_partial_function_t function)
Referenced by vicii_sprites_init().
raster_sprite_status_shutdown()
static void raster_sprite_status_shutdown (raster_sprite_status_t * status, unsigned int num_sprites) static
Referenced by raster_sprite_status_destroy().