x128: sysfile.c File Reference
sysfile.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "cmdline.h"
#include "findpath.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "sysfile.h"
#include "util.h"
Macros
#define DBG(x)
Functions
static int set_system_path (const char *val, void *param)
const char * get_system_path (void)
get the full search path
int sysfile_init (const char *emu_id)
void sysfile_shutdown (void)
int sysfile_resources_init (void)
void sysfile_resources_shutdown (void)
int sysfile_cmdline_options_init (void)
FILE * sysfile_open (const char *name, const char *subpath, char **complete_path_return, const char *open_mode)
Functions to locate/open/load files from the system path.
int sysfile_locate (const char *name, const char *subpath, char **complete_path_return)
int sysfile_load (const char *name, const char *subpath, uint8_t *dest, int minsize, int maxsize)
Variables
static char * default_path = NULL
Resources.
static char * system_path = NULL
static char * expanded_system_path = NULL
static const resource_string_t resources_string []
static const cmdline_option_t cmdline_options []
Command-line options.
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
get_system_path()
const char * get_system_path (void)
get the full search path
Referenced by sysfile_get_system_path_start().
set_system_path()
static int set_system_path (const char * val, void * param) static
< directory separator as a string
< directory separator as a string
Referenced by sysfile_init().
sysfile_cmdline_options_init()
int sysfile_cmdline_options_init (void)
Referenced by init_cmdline_options().
sysfile_init()
int sysfile_init (const char * emu_id)
Referenced by main_program().
sysfile_load()
int sysfile_load (const char * name, const char * subpath, uint8_t * dest, int minsize, int maxsize)
< read mode (binary)
< directory separator as an integer
< read mode (binary)
Referenced by c128rom_load_basic64(), c128rom_load_basichi(), c128rom_load_basiclo(), c128rom_load_chargen_ch(), c128rom_load_chargen_de(), c128rom_load_chargen_fi(), c128rom_load_chargen_fr(), c128rom_load_chargen_int(), c128rom_load_chargen_it(), c128rom_load_chargen_no(), c128rom_load_chargen_se(), c128rom_load_kernal64(), c128rom_load_kernal_ch(), c128rom_load_kernal_de(), c128rom_load_kernal_fi(), c128rom_load_kernal_fr(), c128rom_load_kernal_int(), c128rom_load_kernal_it(), c128rom_load_kernal_no(), c128rom_load_kernal_se(), driverom_load(), drv_2022_open(), drv_4023_open(), drv_8023_open(), drv_mps801_open(), drv_mps802_open(), drv_mps803_open(), and drv_nl10_init_charset().
sysfile_locate()
int sysfile_locate (const char * name, const char * subpath, char ** complete_path_return)
< read mode (binary)
Referenced by archdep_app_icon_path_png(), keyboard_is_keymap_valid(), try_set_keymap_file(), uidata_init(), and vhk_parser_open_file().
sysfile_open()
FILE * sysfile_open (const char * name, const char * subpath, char ** complete_path_return, const char * open_mode)
Functions to locate/open/load files from the system path.
Referenced by create_shader_program(), keyboard_parse_keymap(), mon_playback_commands(), palette_load(), romset_file_load(), sysfile_load(), and sysfile_locate().
sysfile_resources_init()
int sysfile_resources_init (void)
Referenced by init_resources().
sysfile_resources_shutdown()
void sysfile_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
sysfile_shutdown()
void sysfile_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-directory", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Directory", NULL,
      "<Path>", "Define search path to locate system files" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Command-line options.
Referenced by sysfile_cmdline_options_init().
default_path
char* default_path = NULL static
Resources.
Referenced by set_system_path(), sysfile_init(), and sysfile_shutdown().
expanded_system_path
char* expanded_system_path = NULL static
Referenced by get_system_path(), set_system_path(), sysfile_open(), and sysfile_shutdown().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "Directory", "$$", RES_EVENT_NO, NULL,
      &system_path, set_system_path, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by sysfile_resources_init().
system_path
char* system_path = NULL static
Referenced by set_system_path(), and sysfile_resources_shutdown().