vsid: arch/gtk3/widgets/drivenowidget.c File Reference
drivenowidget.c File Reference
GTK3 drive number selection widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "widgethelpers.h"
#include "debug_gtk3.h"
#include "drive.h"
#include "drivenowidget.h"
Functions
static void on_radio_toggled (GtkWidget *widget, gpointer user_data)
Handler for the "toggled" events of the radio buttons.
static GtkWidget * create_radio_group (int number)
Create a GtkGrid with radio buttons in a group for drive numbers.
GtkWidget * drive_no_widget_create (int number, int *target, void(*callback)(int))
Create a drive#-selection widget.
void drive_no_widget_update (GtkWidget *widget, int drive)
Update widget by setting a drive number.
Variables
static int * number_target
Destination of the drive number when changed.
static void(* number_callback)(int) = NULL
Callback triggered on drive number change.
Detailed Description
GTK3 drive number selection widget.
Author
Andre Fachat
Function Documentation
create_radio_group()
static GtkWidget * create_radio_group (int number) static
Create a GtkGrid with radio buttons in a group for drive numbers.
Sets up event handler to change the number_target variable passed in create_drive_no_widget().
Parameters
[in] number default drive number
Returns
GtkGrid
Referenced by drive_no_widget_create().
drive_no_widget_create()
GtkWidget * drive_no_widget_create (int number, int * target, void(*)(int) callback)
Create a drive#-selection widget.
Parameters
[in] number currently selected drive number (0/1)
[out] target destination of the drive number on radio button clicks
[in] callback user callback function to receieve drive number
Returns
GtkGrid
Referenced by create_extra_widget().
drive_no_widget_update()
void drive_no_widget_update (GtkWidget * widget, int drive)
Update widget by setting a drive number.
Parameters
[in,out] widget drive number widget
[in] drive drive number
Referenced by on_unit_changed().
on_radio_toggled()
static void on_radio_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the "toggled" events of the radio buttons.
Parameters
[in] widget radio button triggering the event
[in] user_data drive number (int)
Referenced by drive_no_widget_create().
Variable Documentation
number_callback
void(* number_callback) (int) (int) = NULL static
Callback triggered on drive number change.
This is an optional callback to allow updating other widgets depending on the selected drive number. Pass NULL as the callback argument to create_drive_no_widget() to disable this.
Referenced by drive_no_widget_create(), and on_radio_toggled().
number_target
int* number_target static
Destination of the drive number when changed.
Set when the drive number in the widget changes, pass NULL as the target argument to disable this.
Referenced by drive_no_widget_create(), and on_radio_toggled().