vsid: gfxoutputdrv/nativedrv.h File Reference
nativedrv.h File Reference
#include "screenshot.h"
#include "types.h"
Data Structures
struct native_data_s
struct native_color_sort_s
Typedefs
typedef struct native_data_s native_data_t
typedef struct native_color_sort_s native_color_sort_t
Functions
void gfxoutput_init_artstudio (int help)
void gfxoutput_init_koala (int help)
void gfxoutput_init_minipaint (int help)
native_data_t * native_borderize_colormap (native_data_t *source, uint8_t bordercolor, int xsize, int ysize)
void native_smooth_scroll_borderize_colormap(native_data_t *source, uint8_t bordercolor, uint8_t xcover, uint8_t ycover);
native_data_t * native_crop_and_borderize_colormap (native_data_t *source, uint8_t bordercolor, int xsize, int ysize, int oversize_handling)
native_data_t * native_scale_colormap (native_data_t *source, int xsize, int ysize)
native_data_t * native_resize_colormap (native_data_t *source, int xsize, int ysize, uint8_t bordercolor, int oversize_handling, int undersize_handling)
scale and/or crop and/or borderize according to the options
native_color_sort_t * native_sort_colors_colormap (native_data_t *source, int color_amount)
int native_is_colormap_multicolor (native_data_t *source)
returns 1 if any 8x8 cell contains more than two colors
void vicii_color_to_vicii_bw_colormap (native_data_t *source)
void vicii_color_to_vicii_gray_colormap (native_data_t *source)
void vicii_color_to_nearest_vicii_color_colormap (native_data_t *source, native_color_sort_t *colors)
void vic_color_to_nearest_vic_color_colormap (native_data_t *source, native_color_sort_t *colors)
void ted_color_to_vicii_color_colormap (native_data_t *source, int ted_lum_handling)
void ted_color_to_vic_color_colormap (native_data_t *source, int ted_lum_handling)
void vic_color_to_vicii_color_colormap (native_data_t *source)
void vicii_color_to_vic_color_colormap (native_data_t *source)
void vdc_color_to_vicii_color_colormap (native_data_t *source)
void vdc_color_to_vic_color_colormap (native_data_t *source)
native_data_t * native_vicii_render (screenshot_t *screenshot, const char *filename)
native_data_t * native_ted_render (screenshot_t *screenshot, const char *filename)
native_data_t * native_vic_render (screenshot_t *screenshot, const char *filename)
native_data_t * native_vdc_render (screenshot_t *screenshot, const char *filename)
native_data_t * native_crtc_render (screenshot_t *screenshot, const char *filename)
Typedef Documentation
native_color_sort_t
typedef struct native_color_sort_s native_color_sort_t
native_data_t
typedef struct native_data_s native_data_t
Function Documentation
gfxoutput_init_artstudio()
void gfxoutput_init_artstudio (int help)
Referenced by gfxoutput_early_init().
gfxoutput_init_koala()
void gfxoutput_init_koala (int help)
Referenced by gfxoutput_early_init().
gfxoutput_init_minipaint()
void gfxoutput_init_minipaint (int help)
Referenced by gfxoutput_early_init().
native_borderize_colormap()
native_data_t * native_borderize_colormap (native_data_t * source, uint8_t bordercolor, int xsize, int ysize)
void native_smooth_scroll_borderize_colormap(native_data_t *source, uint8_t bordercolor, uint8_t xcover, uint8_t ycover);
Referenced by native_resize_colormap().
native_crop_and_borderize_colormap()
native_data_t * native_crop_and_borderize_colormap (native_data_t * source, uint8_t bordercolor, int xsize, int ysize, int oversize_handling)
Referenced by native_resize_colormap().
native_crtc_render()
native_data_t * native_crtc_render (screenshot_t * screenshot, const char * filename)
Todo:
FIXME: screenshot->gfx_position.x/y does not match actual black border
"hre" and "petdww_ram" is broken
Todo:
FIXME: handle inter-character gap
Todo:
FIXME: If we're in an 80 column screen we need to horizontally double all pixels, since DWW only has 40 characters worth of pixels.
Todo:
FIXME: this should be defined elsewhere in the crtc code
Referenced by artstudio_crtc_save(), koala_crtc_save(), and minipaint_crtc_save().
native_is_colormap_multicolor()
int native_is_colormap_multicolor (native_data_t * source)
returns 1 if any 8x8 cell contains more than two colors
Referenced by native_generic_render().
native_resize_colormap()
native_data_t * native_resize_colormap (native_data_t * source, int xsize, int ysize, uint8_t bordercolor, int oversize_handling, int undersize_handling)
scale and/or crop and/or borderize according to the options
Referenced by artstudio_crtc_save(), artstudio_vdc_save(), artstudio_vic_save(), koala_crtc_save(), koala_vdc_save(), koala_vic_save(), minipaint_crtc_save(), minipaint_ted_save(), minipaint_vdc_save(), minipaint_vic_save(), and minipaint_vicii_save().
native_scale_colormap()
native_data_t * native_scale_colormap (native_data_t * source, int xsize, int ysize)
Referenced by native_resize_colormap().
native_sort_colors_colormap()
native_color_sort_t * native_sort_colors_colormap (native_data_t * source, int color_amount)
Referenced by artstudio_check_and_correct_cell(), artstudio_multicolor_render(), artstudio_vic_save(), koala_check_and_correct_cell(), koala_find_bgcolor(), minipaint_check_and_correct_cell(), minipaint_find_hires_colors(), minipaint_find_shared_colors_pass(), and native_is_colormap_multicolor().
native_ted_render()
native_data_t * native_ted_render (screenshot_t * screenshot, const char * filename)
Referenced by artstudio_ted_save(), koala_ted_save(), and minipaint_ted_save().
native_vdc_render()
native_data_t * native_vdc_render (screenshot_t * screenshot, const char * filename)
Todo:
FIXME: screenshot->gfx_position.x/y does not match actual black border
Todo:
FIXME: this should be set elsewhere in the vdc code
Todo:
FIXME: is this correct?
Referenced by artstudio_vdc_save(), koala_vdc_save(), and minipaint_vdc_save().
native_vic_render()
native_data_t * native_vic_render (screenshot_t * screenshot, const char * filename)
Referenced by artstudio_vic_save(), koala_vic_save(), and minipaint_vic_save().
native_vicii_render()
native_data_t * native_vicii_render (screenshot_t * screenshot, const char * filename)
Referenced by artstudio_vicii_save(), koala_vicii_save(), and minipaint_vicii_save().
ted_color_to_vic_color_colormap()
void ted_color_to_vic_color_colormap (native_data_t * source, int ted_lum_handling)
Referenced by minipaint_ted_save().
ted_color_to_vicii_color_colormap()
void ted_color_to_vicii_color_colormap (native_data_t * source, int ted_lum_handling)
Referenced by artstudio_ted_save(), godotdrv_write(), and koala_ted_save().
vdc_color_to_vic_color_colormap()
void vdc_color_to_vic_color_colormap (native_data_t * source)
Referenced by minipaint_vdc_save().
vdc_color_to_vicii_color_colormap()
void vdc_color_to_vicii_color_colormap (native_data_t * source)
Referenced by artstudio_vdc_save(), godotdrv_write(), and koala_vdc_save().
vic_color_to_nearest_vic_color_colormap()
void vic_color_to_nearest_vic_color_colormap (native_data_t * source, native_color_sort_t * colors)
Referenced by minipaint_check_and_correct_cell().
vic_color_to_vicii_color_colormap()
void vic_color_to_vicii_color_colormap (native_data_t * source)
Referenced by artstudio_vic_save(), godotdrv_write(), and koala_vic_save().
vicii_color_to_nearest_vicii_color_colormap()
void vicii_color_to_nearest_vicii_color_colormap (native_data_t * source, native_color_sort_t * colors)
Referenced by artstudio_check_and_correct_cell(), artstudio_multicolor_render(), artstudio_vic_save(), and koala_check_and_correct_cell().
vicii_color_to_vic_color_colormap()
void vicii_color_to_vic_color_colormap (native_data_t * source)
Referenced by minipaint_vicii_save().
vicii_color_to_vicii_bw_colormap()
void vicii_color_to_vicii_bw_colormap (native_data_t * source)
Referenced by artstudio_multicolor_render(), and artstudio_vic_save().
vicii_color_to_vicii_gray_colormap()
void vicii_color_to_vicii_gray_colormap (native_data_t * source)
Referenced by artstudio_multicolor_render(), and artstudio_vic_save().