vsid: vdrive/vdrive.h File Reference
vdrive.h File Reference
#include "types.h"
#include "vdrive-dir.h"
Data Structures
struct bufferinfo_s
struct vdrive_s
Run-time data struct for each drive.
Macros
#define NUM_DRIVES 2
#define VDRIVE_PART_SUPPORTED(a) (vdrive->ptype[a]>=1 && vdrive->ptype[a]<=4)
#define VDRIVE_IS_FD(a) (a->image && (a->image->type == DISK_IMAGE_TYPE_D1M || a->image->type == DISK_IMAGE_TYPE_D2M || a->image->type == DISK_IMAGE_TYPE_D4M))
#define VDRIVE_IS_HD(a) (a->image && (a->image->type == DISK_IMAGE_TYPE_DHD))
#define VDRIVE_IS_READONLY(a) (a->image_mode > 0)
#define VDRIVE_IMAGE_FORMAT_1541 0
#define VDRIVE_IMAGE_FORMAT_1571 1
#define VDRIVE_IMAGE_FORMAT_1581 2
#define VDRIVE_IMAGE_FORMAT_8050 3
Dual Disk Drive.
#define VDRIVE_IMAGE_FORMAT_8250 4
Dual Disk Drive.
#define VDRIVE_IMAGE_FORMAT_2040 5
Dual Disk Drive.
#define VDRIVE_IMAGE_FORMAT_NP 6
#define VDRIVE_IMAGE_FORMAT_SYS 7
#define VDRIVE_IMAGE_FORMAT_9000 8
#define VDRIVE_IMAGE_FORMAT_NONE 10
#define BUFFER_NOT_IN_USE 0
#define BUFFER_DIRECTORY_READ 1
#define BUFFER_SEQUENTIAL 2
#define BUFFER_MEMORY_BUFFER 3
#define BUFFER_RELATIVE 4
#define BUFFER_COMMAND_CHANNEL 5
#define BUFFER_PARTITION_READ 6
#define BUFFER_DIRECTORY_MORE_READ 7
#define VDRIVE_BAM_MAX_STATES 33
#define WRITE_BLOCK 512
#define SET_LO_HI(p, val)
#define DRIVE_RAMSIZE 0x400
#define BAM_MAXSIZE (VDRIVE_BAM_MAX_STATES * 256)
#define SERIAL_OK 0
Serial Error Codes.
#define SERIAL_WRITE_TIMEOUT 1
#define SERIAL_READ_TIMEOUT 2
#define SERIAL_FILE_NOT_FOUND 64
EOF.
#define SERIAL_NO_DEVICE 128
#define SERIAL_ERROR (2)
#define SERIAL_EOF (0x40)
#define SERIAL_DEVICE_NOT_PRESENT (0x80)
#define FLOPPY_COMMAND_OK 0
Actually, serial-code errors ...
#define FLOPPY_ERROR 2
#define FD_OK 0
Return values used around.
#define FD_EXIT 1
-1,0, 1 are fixed values
#define FD_NOTREADY -2
#define FD_CHANGED -3
File has changed on disk.
#define FD_NOTRD -4
#define FD_NOTWRT -5
#define FD_WRTERR -6
#define FD_RDERR -7
#define FD_INCOMP -8
DOS Format Mismatch.
#define FD_BADIMAGE -9
ID mismatch (Disk or tape)
#define FD_BADNAME -10
Illegal filename.
#define FD_BADVAL -11
Illegal value.
#define FD_BADDEV -12
#define FD_BAD_TS -13
Track or sector.
#define FD_BAD_TRKNUM -14
Illegal track number.
#define FD_BAD_SECNUM -15
Illegal sector number.
#define CHK_NUM 0
#define CHK_RDY 1
Typedefs
typedef struct bufferinfo_s bufferinfo_t
typedef struct vdrive_s vdrive_t
Run-time data struct for each drive.
Functions
void vdrive_init (void)
int vdrive_device_setup (vdrive_t *vdrive, unsigned int unit)
void vdrive_device_shutdown (vdrive_t *vdrive)
int vdrive_attach_image (struct disk_image_s *image, unsigned int unit, unsigned int drive, vdrive_t *vdrive)
void vdrive_detach_image (struct disk_image_s *image, unsigned int unit, unsigned int drive, vdrive_t *vdrive)
void vdrive_close_all_channels (vdrive_t *vdrive)
void vdrive_close_all_channels_partition (vdrive_t *vdrive, int part)
int vdrive_get_max_sectors (vdrive_t *vdrive, unsigned int track)
int vdrive_get_max_sectors_per_head (vdrive_t *vdrive, unsigned int track)
void vdrive_get_last_read (unsigned int *track, unsigned int *sector, uint8_t **buffer)
void vdrive_set_last_read (unsigned int track, unsigned int sector, uint8_t *buffer)
void vdrive_alloc_buffer (struct bufferinfo_s *p, int mode)
void vdrive_free_buffer (struct bufferinfo_s *p)
void vdrive_set_disk_geometry (vdrive_t *vdrive)
int vdrive_read_sector (vdrive_t *vdrive, uint8_t *buf, unsigned int track, unsigned int sector)
This is where logical sectors are turned to physical.
int vdrive_write_sector (vdrive_t *vdrive, const uint8_t *buf, unsigned int track, unsigned int sector)
int vdrive_read_sector_physical (vdrive_t *vdrive, uint8_t *buf, unsigned int track, unsigned int sector)
int vdrive_write_sector_physical (vdrive_t *vdrive, const uint8_t *buf, unsigned int track, unsigned int sector)
struct disk_image_s * vdrive_get_image (vdrive_t *vdrive, unsigned int drive)
void vdrive_refresh (unsigned int unit)
called to start attached images from new
void vdrive_flush (unsigned int unit)
called to flush out attached images
int vdrive_find_sys (vdrive_t *vdrive)
0 = found, anything else DOS ERROR or not found
int vdrive_read_partition_table (vdrive_t *vdrive)
0 = okay, anything else, dos error
int vdrive_ispartvalid (vdrive_t *vdrive, int part)
int vdrive_write_partition_table (vdrive_t *vdrive)
return DOS error
int vdrive_pack_parts (vdrive_t *vdrive)
int vdrive_switch (vdrive_t *vdrive, int part)
0 okay, anything else, bad
int vdrive_realpart (vdrive_t *vdrive, int part)
return the "real" partition when passed a 0 for CMD
int vdrive_ext_read_sector (vdrive_t *vdrive, int drive, uint8_t *buf, unsigned int track, unsigned int sector)
For external access to individual drives.
int vdrive_ext_write_sector (vdrive_t *vdrive, int drive, const uint8_t *buf, unsigned int track, unsigned int sector)
Macro Definition Documentation
BAM_MAXSIZE
#define BAM_MAXSIZE (VDRIVE_BAM_MAX_STATES * 256)
BUFFER_COMMAND_CHANNEL
#define BUFFER_COMMAND_CHANNEL 5
BUFFER_DIRECTORY_MORE_READ
#define BUFFER_DIRECTORY_MORE_READ 7
BUFFER_DIRECTORY_READ
#define BUFFER_DIRECTORY_READ 1
BUFFER_MEMORY_BUFFER
#define BUFFER_MEMORY_BUFFER 3
BUFFER_NOT_IN_USE
#define BUFFER_NOT_IN_USE 0
BUFFER_PARTITION_READ
#define BUFFER_PARTITION_READ 6
BUFFER_RELATIVE
#define BUFFER_RELATIVE 4
BUFFER_SEQUENTIAL
#define BUFFER_SEQUENTIAL 2
CHK_NUM
#define CHK_NUM 0
CHK_RDY
#define CHK_RDY 1
DRIVE_RAMSIZE
#define DRIVE_RAMSIZE 0x400
FD_BAD_SECNUM
#define FD_BAD_SECNUM -15
Illegal sector number.
FD_BAD_TRKNUM
#define FD_BAD_TRKNUM -14
Illegal track number.
FD_BAD_TS
#define FD_BAD_TS -13
Track or sector.
FD_BADDEV
#define FD_BADDEV -12
FD_BADIMAGE
#define FD_BADIMAGE -9
ID mismatch (Disk or tape)
FD_BADNAME
#define FD_BADNAME -10
Illegal filename.
FD_BADVAL
#define FD_BADVAL -11
Illegal value.
FD_CHANGED
#define FD_CHANGED -3
File has changed on disk.
FD_EXIT
#define FD_EXIT 1
-1,0, 1 are fixed values
FD_INCOMP
#define FD_INCOMP -8
DOS Format Mismatch.
FD_NOTRD
#define FD_NOTRD -4
FD_NOTREADY
#define FD_NOTREADY -2
FD_NOTWRT
#define FD_NOTWRT -5
FD_OK
#define FD_OK 0
Return values used around.
FD_RDERR
#define FD_RDERR -7
FD_WRTERR
#define FD_WRTERR -6
FLOPPY_COMMAND_OK
#define FLOPPY_COMMAND_OK 0
Actually, serial-code errors ...
FLOPPY_ERROR
#define FLOPPY_ERROR 2
NUM_DRIVES
#define NUM_DRIVES 2
SERIAL_DEVICE_NOT_PRESENT
#define SERIAL_DEVICE_NOT_PRESENT (0x80)
SERIAL_EOF
#define SERIAL_EOF (0x40)
SERIAL_ERROR
#define SERIAL_ERROR (2)
SERIAL_FILE_NOT_FOUND
#define SERIAL_FILE_NOT_FOUND 64
EOF.
SERIAL_NO_DEVICE
#define SERIAL_NO_DEVICE 128
SERIAL_OK
#define SERIAL_OK 0
Serial Error Codes.
SERIAL_READ_TIMEOUT
#define SERIAL_READ_TIMEOUT 2
SERIAL_WRITE_TIMEOUT
#define SERIAL_WRITE_TIMEOUT 1
SET_LO_HI
#define SET_LO_HI (p, val)
Value:
    do {                                \
        *((p)++) = (val) & 0xff;        \
        *((p)++) = ((val) >> 8) & 0xff; \
    } while (0)
VDRIVE_BAM_MAX_STATES
#define VDRIVE_BAM_MAX_STATES 33
VDRIVE_IMAGE_FORMAT_1541
#define VDRIVE_IMAGE_FORMAT_1541 0
VDRIVE_IMAGE_FORMAT_1571
#define VDRIVE_IMAGE_FORMAT_1571 1
VDRIVE_IMAGE_FORMAT_1581
#define VDRIVE_IMAGE_FORMAT_1581 2
VDRIVE_IMAGE_FORMAT_2040
#define VDRIVE_IMAGE_FORMAT_2040 5
Dual Disk Drive.
VDRIVE_IMAGE_FORMAT_8050
#define VDRIVE_IMAGE_FORMAT_8050 3
Dual Disk Drive.
VDRIVE_IMAGE_FORMAT_8250
#define VDRIVE_IMAGE_FORMAT_8250 4
Dual Disk Drive.
VDRIVE_IMAGE_FORMAT_9000
#define VDRIVE_IMAGE_FORMAT_9000 8
VDRIVE_IMAGE_FORMAT_NONE
#define VDRIVE_IMAGE_FORMAT_NONE 10
VDRIVE_IMAGE_FORMAT_NP
#define VDRIVE_IMAGE_FORMAT_NP 6
VDRIVE_IMAGE_FORMAT_SYS
#define VDRIVE_IMAGE_FORMAT_SYS 7
VDRIVE_IS_FD
#define VDRIVE_IS_FD (a) (a->image && (a->image->type == DISK_IMAGE_TYPE_D1M || a->image->type == DISK_IMAGE_TYPE_D2M || a->image->type == DISK_IMAGE_TYPE_D4M))
VDRIVE_IS_HD
#define VDRIVE_IS_HD (a) (a->image && (a->image->type == DISK_IMAGE_TYPE_DHD))
VDRIVE_IS_READONLY
#define VDRIVE_IS_READONLY (a) (a->image_mode > 0)
VDRIVE_PART_SUPPORTED
#define VDRIVE_PART_SUPPORTED (a) (vdrive->ptype[a]>=1 && vdrive->ptype[a]<=4)
WRITE_BLOCK
#define WRITE_BLOCK 512
Typedef Documentation
bufferinfo_t
typedef struct bufferinfo_s bufferinfo_t
vdrive_t
typedef struct vdrive_s vdrive_t
Run-time data struct for each drive.
Function Documentation
vdrive_alloc_buffer()
void vdrive_alloc_buffer (struct bufferinfo_s * p, int mode)
Referenced by iec_open_read_directory(), iec_open_read_sequential(), iec_open_write(), vdrive_device_setup(), vdrive_dir_create_slot(), and vdrive_iec_open().
vdrive_attach_image()
int vdrive_attach_image (struct disk_image_s * image, unsigned int unit, unsigned int drive, vdrive_t * vdrive)
< number of tracks on a standard 1541 floppy
< Dual Disk Drive
< number of tracks on a 1571 floppy
< Dual Disk Drive
< Dual Disk Drive
< number of tracks on a standard 1541 floppy
< number of tracks on a 1571 floppy
Todo:
FIXME: extra checks might be needed for supporting other drives
< number of tracks on a 1571 floppy
< number of tracks on a standard 1541 floppy
< HD in ASCII for CMDHD
< D9090/D9060
vdrive->dir_part = drive;
< HD in ASCII for CMDHD
Referenced by attach_disk_image(), and vdrive_internal_open_fsimage().
vdrive_close_all_channels()
void vdrive_close_all_channels (vdrive_t * vdrive)
Referenced by vdrive_command_execute(), vdrive_command_format_internal(), and vdrive_detach_image().
vdrive_close_all_channels_partition()
void vdrive_close_all_channels_partition (vdrive_t * vdrive, int part)
Referenced by vdrive_command_format_worker(), vdrive_command_initialize(), vdrive_command_validate(), and vdrive_detach_image().
vdrive_detach_image()
void vdrive_detach_image (struct disk_image_s * image, unsigned int unit, unsigned int drive, vdrive_t * vdrive)
Referenced by detach_disk_image(), and vdrive_internal_close_disk_image().
vdrive_device_setup()
int vdrive_device_setup (vdrive_t * vdrive, unsigned int unit)
Referenced by file_system_init(), set_file_system_device(), and vdrive_internal_open_fsimage().
vdrive_device_shutdown()
void vdrive_device_shutdown (vdrive_t * vdrive)
Referenced by file_system_shutdown(), vdrive_internal_close_disk_image(), and vdrive_internal_open_fsimage().
vdrive_ext_read_sector()
int vdrive_ext_read_sector (vdrive_t * vdrive, int drive, uint8_t * buf, unsigned int track, unsigned int sector)
For external access to individual drives.
Referenced by mon_drive_block_cmd().
vdrive_ext_write_sector()
int vdrive_ext_write_sector (vdrive_t * vdrive, int drive, const uint8_t * buf, unsigned int track, unsigned int sector)
Referenced by mon_drive_block_cmd().
vdrive_find_sys()
int vdrive_find_sys (vdrive_t * vdrive)
0 = found, anything else DOS ERROR or not found
< HD in ASCII for CMDHD
stop for now short
Referenced by vdrive_read_partition_table().
vdrive_flush()
void vdrive_flush (unsigned int unit)
called to flush out attached images
Referenced by set_drive_true_emulation().
vdrive_free_buffer()
void vdrive_free_buffer (struct bufferinfo_s * p)
Referenced by iec_close_sequential(), iec_open_write(), vdrive_device_shutdown(), and vdrive_iec_close().
vdrive_get_image()
struct disk_image_s * vdrive_get_image (vdrive_t * vdrive, unsigned int drive)
Referenced by detach_disk_image_and_free(), file_system_attach_disk_internal(), file_system_detach_disk_shutdown(), file_system_detach_disk_single(), file_system_get_disk_name(), file_system_get_image(), vdrive_detach_disk_image_and_free(), and vdrive_snapshot_module_write().
vdrive_get_last_read()
void vdrive_get_last_read (unsigned int * track, unsigned int * sector, uint8_t ** buffer)
Referenced by disk_eof_callback().
vdrive_get_max_sectors()
int vdrive_get_max_sectors (vdrive_t * vdrive, unsigned int track)
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_bam_alloc_add_interleave(), vdrive_bam_alloc_worker(), vdrive_command_format_worker(), vdrive_command_validate(), vdrive_dir_find_next_slot(), and vdrive_get_max_sectors_per_head().
vdrive_get_max_sectors_per_head()
int vdrive_get_max_sectors_per_head (vdrive_t * vdrive, unsigned int track)
Referenced by vdrive_bam_alloc_add_interleave(), vdrive_bam_alloc_next_free_sector_interleave(), vdrive_bam_alloc_next_free_sector_reset(), vdrive_bam_alloc_worker(), and vdrive_dir_find_next_slot().
vdrive_init()
void vdrive_init (void)
Referenced by init_main().
vdrive_ispartvalid()
int vdrive_ispartvalid (vdrive_t * vdrive, int part)
Referenced by vdrive_command_chcmdpart(), and vdrive_iec_open().
vdrive_pack_parts()
int vdrive_pack_parts (vdrive_t * vdrive)
< HD in ASCII for CMDHD
Referenced by vdrive_command_deletepart().
vdrive_read_partition_table()
int vdrive_read_partition_table (vdrive_t * vdrive)
0 = okay, anything else, dos error
< HD in ASCII for CMDHD
Todo:
check for D?M without partition table
Referenced by vdrive_attach_image(), vdrive_change_part(), vdrive_command_execute(), vdrive_command_format_internal(), and vdrive_ispartvalid().
vdrive_read_sector()
int vdrive_read_sector (vdrive_t * vdrive, uint8_t * buf, unsigned int track, unsigned int sector)
This is where logical sectors are turned to physical.
Not yet, but soon.
Referenced by diskcontents_block_read(), iec_open_read_sequential(), iec_open_write(), iec_read_sequential(), vdrive_bam_allocate_chain(), vdrive_bam_allocate_chain_255(), vdrive_bam_read_bam_block(), vdrive_command_allocate_chain(), vdrive_command_block(), vdrive_command_copy(), vdrive_command_getpartinfo(), vdrive_command_memory_write(), vdrive_command_renameheader(), vdrive_command_scratch(), vdrive_command_switchtraverse(), vdrive_command_u1a2b(), vdrive_command_validate_worker(), vdrive_dir_find_first_slot(), vdrive_dir_find_next_slot(), vdrive_dir_first_directory(), vdrive_dir_free_chain(), vdrive_dir_part_find_next_slot(), vdrive_ext_read_sector(), vdrive_find_sys(), vdrive_iec_update_dirent(), vdrive_pack_parts(), vdrive_read_partition_table(), vdrive_rel_listen(), vdrive_rel_open_existing(), vdrive_rel_position_internal(), vdrive_rel_read(), vdrive_rel_record_max(), vdrive_rel_scratch(), vdrive_rel_write(), vdrive_set_disk_geometry(), and vdrive_write_partition_table().
vdrive_read_sector_physical()
int vdrive_read_sector_physical (vdrive_t * vdrive, uint8_t * buf, unsigned int track, unsigned int sector)
vdrive_realpart()
int vdrive_realpart (vdrive_t * vdrive, int part)
return the "real" partition when passed a 0 for CMD
otherwiese return 0 if we exceed the number of drives
Referenced by vdrive_command_chdir(), vdrive_command_copy(), vdrive_iec_open(), and vdrive_switch().
vdrive_refresh()
void vdrive_refresh (unsigned int unit)
called to start attached images from new
Referenced by set_drive_true_emulation().
vdrive_set_disk_geometry()
void vdrive_set_disk_geometry (vdrive_t * vdrive)
< 1541 BAM track number
< 1541 BAM sector number
< 1541 BAM track number
< 1541 BAM sector number
< offset in BAM of the disk name in PETSCII, 16 bytes, padded with 0xa0
< offset in BAM of the disk ID in PETSCII, 2 bytes for standard DOS
< 1541 directory track number
< 1541 directory sector number
< Dual Disk Drive
< BAM track number
< BAM sector number
< BAM track number
< BAM sector number
< offset in BAM of the disk name in PETSCII, 16 bytes, padded with 0xa0
< offset in BAM of the disk ID in PETSCII, 2 bytes
< directory track number
< directory sector number
< BAM track number (side 1 BAM)
< BAM sector number (side 1 BAM)
< BAM track number (side 1 BAM)
< BAM sector number (side 1 BAM)
< offset in BAM of the disk name in PETSCII, 16 bytes, padded with 0xa0
< offset in BAM of the disk ID in PETSCII, 2 bytes
< directory track number
< directory sector number
< BAM track number
< BAM first sector number (the BAM of a 1581 diskette is three sectors)
< BAM track number
< BAM first sector number (the BAM of a 1581 diskette is three sectors)
< offset in BAM of disk name in PETSCII, 16 bytes, padded with 0xa0
< offset in BAM of disk ID in PETSCII, 2 bytes
< directory track number
< directory sector number
< Dual Disk Drive
< block w/disk name
< block w/disk name
< pos. of disk name in header blk
< pos. of disk id in header blk
< Dual Disk Drive
< block w/disk name
< block w/disk name
< pos. of disk name in header blk
< pos. of disk name in hdr blk
< pos. of disk id in header blk
< pos. of disk id in hdr blk
Referenced by vdrive_command_chpart(), vdrive_command_format_worker(), vdrive_command_initialize(), vdrive_command_return(), vdrive_command_rmdir(), and vdrive_switch().
vdrive_set_last_read()
void vdrive_set_last_read (unsigned int track, unsigned int sector, uint8_t * buffer)
Referenced by iec_open_read_sequential(), and iec_read_sequential().
vdrive_switch()
int vdrive_switch (vdrive_t * vdrive, int part)
0 okay, anything else, bad
Referenced by vdrive_attach_image(), vdrive_bam_get_disk_id(), vdrive_bam_set_disk_id(), vdrive_command_chcmdpart(), vdrive_command_getpartinfo(), vdrive_command_memory_write(), vdrive_command_renamepart(), vdrive_command_switch(), vdrive_ext_read_sector(), vdrive_ext_write_sector(), and vdrive_iec_switch().
vdrive_write_partition_table()
int vdrive_write_partition_table (vdrive_t * vdrive)
return DOS error
< HD in ASCII for CMDHD
Todo:
check for D?M without partition table
Referenced by vdrive_pack_parts().
vdrive_write_sector()
int vdrive_write_sector (vdrive_t * vdrive, const uint8_t * buf, unsigned int track, unsigned int sector)
Referenced by find_next_directory_sector(), iec_open_write(), iec_write_sequential(), vdrive_bam_create_empty_bam(), vdrive_bam_write_bam(), vdrive_command_block(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_format_internal(), vdrive_command_format_worker(), vdrive_command_lockunlock(), vdrive_command_memory_write(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_renameheader(), vdrive_command_renamepart(), vdrive_command_u1a2b(), vdrive_command_validate_worker(), vdrive_dir_find_next_slot(), vdrive_dir_remove_slot(), vdrive_ext_write_sector(), vdrive_iec_update_dirent(), vdrive_pack_parts(), vdrive_rel_add_sector(), vdrive_rel_commit(), vdrive_rel_flush_sidesectors(), vdrive_rel_open_new(), and vdrive_write_partition_table().
vdrive_write_sector_physical()
int vdrive_write_sector_physical (vdrive_t * vdrive, const uint8_t * buf, unsigned int track, unsigned int sector)