x128: userport/userport_digimax.c File Reference
userport_digimax.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cmdline.h"
#include "lib.h"
#include "machine.h"
#include "maincpu.h"
#include "resources.h"
#include "snapshot.h"
#include "sound.h"
#include "uiapi.h"
#include "joyport.h"
#include "userport.h"
#include "userport_digimax.h"
#include "util.h"
#include "digimaxcore.c"
Macros
#define SNAP_MAJOR 0
#define SNAP_MINOR 1
Functions
static void userport_digimax_store_pbx (uint8_t value, int pulse)
Some prototypes are needed.
static void userport_digimax_store_pa2 (uint8_t value)
static void userport_digimax_store_pa3 (uint8_t value)
static int userport_digimax_write_snapshot_module (snapshot_t *s)
static int userport_digimax_read_snapshot_module (snapshot_t *s)
static int digimax_enable (int value)
void userport_digimax_sound_chip_init (void)
int userport_digimax_resources_init (void)
Variables
static userport_device_t digimax_device
static uint8_t userport_digimax_address = 3
static const char snap_module_name [] = "UPDIGIMAX"
Macro Definition Documentation
SNAP_MAJOR
#define SNAP_MAJOR 0
SNAP_MINOR
#define SNAP_MINOR 1
Function Documentation
digimax_enable()
static int digimax_enable (int value) static
Referenced by create_ide64_shortbus_layout(), and on_digimax_toggled().
userport_digimax_read_snapshot_module()
static int userport_digimax_read_snapshot_module (snapshot_t * s) static
userport_digimax_resources_init()
int userport_digimax_resources_init (void)
Referenced by machine_resources_init().
userport_digimax_sound_chip_init()
void userport_digimax_sound_chip_init (void)
Referenced by machine_specific_init().
userport_digimax_store_pa2()
static void userport_digimax_store_pa2 (uint8_t value) static
userport_digimax_store_pa3()
static void userport_digimax_store_pa3 (uint8_t value) static
userport_digimax_store_pbx()
static void userport_digimax_store_pbx (uint8_t value, int pulse) static
Some prototypes are needed.
userport_digimax_write_snapshot_module()
static int userport_digimax_write_snapshot_module (snapshot_t * s) static
Variable Documentation
digimax_device
userport_device_t digimax_device static
Initial value:
= {
    "Userport DigiMAX",
    JOYSTICK_ADAPTER_ID_NONE,
    USERPORT_DEVICE_TYPE_AUDIO_OUTPUT,
    digimax_enable,
    NULL,
    userport_digimax_store_pbx,
    NULL,
    userport_digimax_store_pa2,
    NULL,
    userport_digimax_store_pa3,
    1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    userport_digimax_write_snapshot_module,
    userport_digimax_read_snapshot_module
}
Referenced by userport_digimax_resources_init().
snap_module_name
const char snap_module_name[] = "UPDIGIMAX" static
Referenced by userport_digimax_read_snapshot_module(), and userport_digimax_write_snapshot_module().
userport_digimax_address
uint8_t userport_digimax_address = 3 static
Referenced by userport_digimax_read_snapshot_module(), userport_digimax_store_pa2(), userport_digimax_store_pa3(), userport_digimax_store_pbx(), and userport_digimax_write_snapshot_module().