vsid: arch/gtk3/widgets/vsidplaylistadddialog.c File Reference
vsidplaylistadddialog.c File Reference
GTK3 Add SID files dialog for the playlist widget.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include "archdep_get_hvsc_dir.h"
#include "vice_gtk3.h"
#include "debug_gtk3.h"
#include "filechooserhelpers.h"
#include "lastdir.h"
#include "resources.h"
#include "ui.h"
#include "uiactions.h"
#include "vsidplaylistadddialog.h"
Functions
static void on_destroy (GtkWidget *widget, gpointer data)
Handler for the 'destroy' event of the dialog.
static void on_response (GtkDialog *dialog, gint response_id, gpointer data)
Handler for the 'response' event of the dialog.
static GtkWidget * vsid_playlist_add_dialog_create (void)
Create GtkFileChooser instance to open SID files.
void vsid_playlist_add_dialog_exec (void(*callback)(GSList *files))
Run dialog to add SID files to the playlist.
void vsid_playlist_add_dialog_free (void)
Free memory used by the lastdir.c functions.
Variables
static void(* dialog_cb)(GSList *) = NULL
callback function of the dialog
static gchar * last_used_dir = NULL
Last used directory of the dialog.
static gchar * last_used_file = NULL
Last used file of the dialog.
Detailed Description
GTK3 Add SID files dialog for the playlist widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_destroy()
static void on_destroy (GtkWidget * widget, gpointer data) static
Handler for the 'destroy' event of the dialog.
Parameters
[in] widget dialog (unused)
[in] data extra event data (unused)
XXX: Currently does nothing. Not sure what I meant to do with this –compyx
Referenced by vsid_playlist_add_dialog_create().
on_response()
static void on_response (GtkDialog * dialog, gint response_id, gpointer data) static
Handler for the 'response' event of the dialog.
Calls the registered callback with a list of files.
Parameters
[in] dialog dialog triggering the event
[in] response_id ID of response of the dialog
[in] data extra event data (unused)
Referenced by vsid_playlist_add_dialog_create().
vsid_playlist_add_dialog_create()
static GtkWidget * vsid_playlist_add_dialog_create (void) static
Create GtkFileChooser instance to open SID files.
Returns
GtkFileChooser
Referenced by vsid_playlist_add_dialog_exec().
vsid_playlist_add_dialog_exec()
void vsid_playlist_add_dialog_exec (void(*)(GSList *files) callback)
Run dialog to add SID files to the playlist.
Parameters
[in] callback function accepting a list of selected files
Referenced by open_add_dialog(), and vsid_playlist_add().
vsid_playlist_add_dialog_free()
void vsid_playlist_add_dialog_free (void)
Free memory used by the lastdir.c functions.
Frees the last_used_dir and last_used_file strings.
Called on emulator shutdown.
Referenced by on_destroy().
Variable Documentation
dialog_cb
void(* dialog_cb) (GSList *) (GSList *) = NULL static
callback function of the dialog
Referenced by on_response(), and vsid_playlist_add_dialog_exec().
last_used_dir
gchar* last_used_dir = NULL static
Last used directory of the dialog.
Used by the functions in lastdir.c
Referenced by on_response(), vsid_playlist_add_dialog_create(), and vsid_playlist_add_dialog_free().
last_used_file
gchar* last_used_file = NULL static
Last used file of the dialog.
Used by the functions in lastdir.c
Referenced by on_response(), vsid_playlist_add_dialog_create(), and vsid_playlist_add_dialog_free().