x128: arch/gtk3/widgets/base/resourcescale.h File Reference
resourcescale.h File Reference
Scale to control an integer resource - header.
#include "vice.h"
#include <gtk/gtk.h>
#include "basewidget_types.h"
Functions
GtkWidget * vice_gtk3_resource_scale_int_new (const char *resource, GtkOrientation orientation, int low, int high, int step)
Create a scale for an integer resource.
GtkWidget * vice_gtk3_resource_scale_int_new_sprintf (const char *fmt, GtkOrientation orientation, int low, int high, int step,...)
Create a scale for an integer resource.
gboolean vice_gtk3_resource_scale_int_set (GtkWidget *widget, int value)
Set the integer scale widget to value.
gboolean vice_gtk3_resource_scale_int_get (GtkWidget *widget, int *value)
Get the value of the integer scale widget.
void vice_gtk3_resource_scale_int_set_marks (GtkWidget *widget, int step)
Add marks to integer scale widget at each step increment.
gboolean vice_gtk3_resource_scale_int_reset (GtkWidget *widget)
Restore the scale to the resource's value on instanciation.
gboolean vice_gtk3_resource_scale_int_factory (GtkWidget *widget)
Reset widget to the resource factory value.
gboolean vice_gtk3_resource_scale_int_sync (GtkWidget *widget)
Synchronize widget with its resource.
GtkWidget * vice_gtk3_resource_scale_custom_new (const gchar *resource, GtkOrientation orientation, gint resource_low, gint resource_high, gdouble display_low, gdouble display_high, gdouble display_step, const gchar *display_fmt)
Create scale widget displaying custom value bound to resource.
GtkWidget * vice_gtk3_resource_scale_custom_new_printf (const gchar *resource, GtkOrientation orientation, gint resource_low, gint resource_high, gdouble display_low, gdouble display_high, gdouble display_step, const gchar *display_fmt,...)
Create scale widget displaying custom value bound to resource.
gboolean vice_gtk3_resource_scale_custom_set (GtkWidget *widget, int value)
Set the raw resource-bound value.
gboolean vice_gtk3_resource_scale_custom_get (GtkWidget *widget, int *value)
Get the raw resource-bound value.
gboolean vice_gtk3_resource_scale_custom_reset (GtkWidget *widget)
Reset widget to the state it had when instanciated.
gboolean vice_gtk3_resource_scale_custom_factory (GtkWidget *widget)
Set widget to the factory value of its resource.
gboolean vice_gtk3_resource_scale_custom_sync (GtkWidget *widget)
Synchronize the widget state with its resource.
GtkWidget * vice_gtk3_resource_scale_exp_new (const gchar *resource, GtkOrientation orientation, gdouble power, gint resource_low, gint resource_high, gint display_step, const gchar *display_fmt)
Create exponential scale widget displaying value bound to resource.
void vice_gtk3_resource_exp_range_set_value (GtkRange *self, gdouble value)
Detailed Description
Scale to control an integer resource - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
vice_gtk3_resource_exp_range_set_value()
void vice_gtk3_resource_exp_range_set_value (GtkRange * self, gdouble value)
Referenced by exp_new_helper(), and on_reset_clicked().
vice_gtk3_resource_scale_custom_factory()
gboolean vice_gtk3_resource_scale_custom_factory (GtkWidget * widget)
Set widget to the factory value of its resource.
Reset the widget to the value its resource had when the widget was instanciated.
Parameters
[in] widget custom scale widget
Returns
TRUE on success
Referenced by on_reset_clicked(), and reset_sliders().
vice_gtk3_resource_scale_custom_get()
gboolean vice_gtk3_resource_scale_custom_get (GtkWidget * widget, int * value)
Get the raw resource-bound value.
Get the bound resource's current value.
Parameters
[in] widget custom scale widget
[out] value current value of the resource
Returns
TRUE
vice_gtk3_resource_scale_custom_new()
GtkWidget * vice_gtk3_resource_scale_custom_new (const gchar * resource, GtkOrientation orientation, gint resource_low, gint resource_high, gdouble display_low, gdouble display_high, gdouble display_step, const gchar * display_fmt)
Create scale widget displaying custom value bound to resource.
Create a scale widget that maps an integer resource's range to a custom range using double with a custom format string.
Parameters
[in] resource resource name
[in] orientation GtkScale orientation
[in] resource_low resource lower bound (inclusive)
[in] resource_high resource upper bound (inclusive)
[in] display_low display lower bound (inclusive)
[in] display_high display upper bound (inclusive)
[in] display_step display stepping
[in] display_fmt display format string
Returns
new custom resource-bound scale widget
vice_gtk3_resource_scale_custom_new_printf()
GtkWidget * vice_gtk3_resource_scale_custom_new_printf (const gchar * resource, GtkOrientation orientation, gint resource_low, gint resource_high, gdouble display_low, gdouble display_high, gdouble display_step, const gchar * display_fmt, ...)
Create scale widget displaying custom value bound to resource.
Create a scale widget that maps an integer resource's range to a custom range using double with a custom format string. This version uses resource as a printf format string to generate the resource name.
Parameters
[in] resource resource name format string
[in] orientation GtkScale orientation
[in] resource_low resource lower bound (inclusive)
[in] resource_high resource upper bound (inclusive)
[in] display_low display lower bound (inclusive)
[in] display_high display upper bound (inclusive)
[in] display_step display stepping
[in] display_fmt display format string
[in] ... resource name format string arguments
Returns
new custom resource-bound scale widget
Referenced by create_autofire_speed_widget(), create_datasette_widget(), create_slider(), settings_sampler_widget_create(), and settings_sound_widget_create().
vice_gtk3_resource_scale_custom_reset()
gboolean vice_gtk3_resource_scale_custom_reset (GtkWidget * widget)
Reset widget to the state it had when instanciated.
Reset the widget to its resource value when the widget was instanciated.
Parameters
[in] widget custom scale widget
Returns
TRUE on success
vice_gtk3_resource_scale_custom_set()
gboolean vice_gtk3_resource_scale_custom_set (GtkWidget * widget, int value)
Set the raw resource-bound value.
Set the bound resource's new value and update the widget.
Parameters
[in] widget custom scale widget
[in] value new value for widget
Returns
true on success
Referenced by reset_sliders_neutral(), vice_gtk3_resource_scale_custom_factory(), vice_gtk3_resource_scale_custom_reset(), and vice_gtk3_resource_scale_custom_sync().
vice_gtk3_resource_scale_custom_sync()
gboolean vice_gtk3_resource_scale_custom_sync (GtkWidget * widget)
Synchronize the widget state with its resource.
Update the widget's state in case its resource was altered through other means than this widget.
Parameters
[in] widget custom scale widget
Returns
TRUE on success
vice_gtk3_resource_scale_exp_new()
GtkWidget * vice_gtk3_resource_scale_exp_new (const gchar * resource, GtkOrientation orientation, gdouble power, gint resource_low, gint resource_high, gint display_step, const gchar * display_fmt)
Create exponential scale widget displaying value bound to resource.
Create a scale widget that displays an integer resource's range to a slider which reacts exponentially.
Parameters
[in] resource resource name
[in] orientation GtkScale orientation
[in] power exponent
[in] resource_low lower bound (inclusive)
[in] resource_high upper bound (inclusive)
[in] display_step stepping
[in] display_fmt display format string
Returns
new exponential resource-bound scale widget
Referenced by create_exp_slider().
vice_gtk3_resource_scale_int_factory()
gboolean vice_gtk3_resource_scale_int_factory (GtkWidget * widget)
Reset widget to the resource factory value.
Parameters
[in,out] widget integer scale widget
Returns
TRUE if the widget was restored to its factory value
vice_gtk3_resource_scale_int_get()
gboolean vice_gtk3_resource_scale_int_get (GtkWidget * widget, int * value)
Get the value of the integer scale widget.
Parameters
[in] widget integer scale widget
[out] value location to store value
Returns
TRUE
vice_gtk3_resource_scale_int_new()
GtkWidget * vice_gtk3_resource_scale_int_new (const char * resource, GtkOrientation orientation, int low, int high, int step)
Create a scale for an integer resource.
Parameters
[in] resource resource name
[in] orientation scale orientation (
See also
GtkOrientation)
Parameters
[in] low lowest value for scale
[in] high highest value for scale
[in] step value to incr/decr value with cursor keys
Returns
GtkScale
Referenced by drive_sound_widget_create().
vice_gtk3_resource_scale_int_new_sprintf()
GtkWidget * vice_gtk3_resource_scale_int_new_sprintf (const char * fmt, GtkOrientation orientation, int low, int high, int step, ...)
Create a scale for an integer resource.
Parameters
[in] fmt resource name format string
[in] orientation scale orientation (
See also
GtkOrientation)
Parameters
[in] low lowest value for scale
[in] high highest value for scale
[in] step value to incr/decr value with cursor keys
Returns
GtkScale
vice_gtk3_resource_scale_int_reset()
gboolean vice_gtk3_resource_scale_int_reset (GtkWidget * widget)
Restore the scale to the resource's value on instanciation.
Restores the widget to the resource value on instanciantion.
Parameters
[in,out] widget integer scale widget
Returns
TRUE if the widget was reset to its original value
vice_gtk3_resource_scale_int_set()
gboolean vice_gtk3_resource_scale_int_set (GtkWidget * widget, int value)
Set the integer scale widget to value.
Parameters
[in,out] widget integer scale widget
[in] value new value for scale
Returns
TRUE
Referenced by vice_gtk3_resource_scale_int_factory(), vice_gtk3_resource_scale_int_reset(), and vice_gtk3_resource_scale_int_sync().
vice_gtk3_resource_scale_int_set_marks()
void vice_gtk3_resource_scale_int_set_marks (GtkWidget * widget, int step)
Add marks to integer scale widget at each step increment.
Parameters
[in,out] widget integer scale widget
[in] step distance between marks
vice_gtk3_resource_scale_int_sync()
gboolean vice_gtk3_resource_scale_int_sync (GtkWidget * widget)
Synchronize widget with its resource.
Parameters
[in,out] widget integer scale widget
Returns
TRUE if the widget was synchronized with its resource