x128: arch/gtk3/widgets/base/resourcebrowser.c File Reference
resourcebrowser.c File Reference
Text entry with label and browse button connected to a resource.
#include "vice.h"
#include <gtk/gtk.h>
#include <string.h>
#include "archdep.h"
#include "debug_gtk3.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "openfiledialog.h"
#include "savefiledialog.h"
#include "widgethelpers.h"
#include "resourcehelpers.h"
#include "resourceentry.h"
#include "ui.h"
#include "util.h"
#include "resourcebrowser.h"
Data Structures
struct rb_state_s
Object keeping track of the state of the widget.
Typedefs
typedef struct rb_state_s rb_state_t
Object keeping track of the state of the widget.
Functions
static rb_state_t * rb_state_new (void)
Allocate new state object and initialize all members to NULL.
static void rb_state_set_directory (rb_state_t *state, const char *directory)
Set/update directory in state object.
static void rb_state_free_patterns (rb_state_t *state)
Free memory used by file type patterns.
static void rb_state_set_patterns (rb_state_t *state, const char *const *patterns)
Set file type patterns.
static void rb_state_free (rb_state_t *state)
Free state object and all its members.
static void on_resource_browser_destroy (GtkWidget *widget, gpointer data)
Clean up memory used by the main widget.
static void browse_filename_callback (GtkDialog *dialog, char *filename, gpointer data)
Callback for the dialog.
static void save_filename_callback (GtkDialog *dialog, char *filename, gpointer data)
Callback for the save dialog.
static void on_resource_browser_browse_clicked (GtkWidget *widget, gpointer data)
Handler for the "clicked" event of the browse button.
static void on_resource_browser_save_clicked (GtkWidget *widget, gpointer data)
Handler for the "clicked" event of the save button.
GtkWidget * vice_gtk3_resource_browser_new (const char *resource, const char *const *patterns, const char *pattern_name, const char *title, const char *label, void(*callback)(GtkWidget *, gpointer))
Create file selection widget with browse button.
gboolean vice_gtk3_resource_browser_set (GtkWidget *widget, const char *new)
Set widget value to new.
gboolean vice_gtk3_resource_browser_get (GtkWidget *widget, const char **dest)
Get the current value of widget.
gboolean vice_gtk3_resource_browser_reset (GtkWidget *widget)
Restore resource in widget to its original value.
gboolean vice_gtk3_resource_browser_sync (GtkWidget *widget)
Synchronize widget with current resource value.
gboolean vice_gtk3_resource_browser_factory (GtkWidget *widget)
Reset widget to the resource's factory value.
GtkWidget * vice_gtk3_resource_browser_save_new (const char *resource, const char *title, const char *label, const char *suggested, void(*callback)(GtkWidget *, gpointer))
Resource browser widget to select a file to save.
void vice_gtk3_resource_browser_set_directory (GtkWidget *widget, const char *directory)
Set the directory to use when the resource only contains a filename.
Detailed Description
Text entry with label and browse button connected to a resource.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
This class presents a text entry box and a "Browse ..." button to update a resource, optionally providing a label before the text entry. It is meant as a widget to set a resource that represents a file, such as a kernal image.
Internally this widget is a GtkGrid, so when a dialog/widget needs multiple instances of this class, the best thing to do is to set the label to NULL and add the labels manually in another GtkGrid or other container to keep things aligned.
The constructor is slightly convoluted, but flexible, see vice_gtk3_resource_browser_new (todo: figure out how to get Doxygen to print the function prototype here)
The first argument is required, it's the VICE resource we wish to change, for example "Kernal". The second argument is a list of strings representing file name globbing patterns, for example {"*.bin", "*.rom", NULL}
Typedef Documentation
rb_state_t
typedef struct rb_state_s rb_state_t
Object keeping track of the state of the widget.
Function Documentation
browse_filename_callback()
static void browse_filename_callback (GtkDialog * dialog, char * filename, gpointer data) static
Callback for the dialog.
Parameters
[in,out] dialog Open file dialog reference
[in] filename filename or NULL on cancel
[in,out] data browser state
Referenced by on_resource_browser_browse_clicked().
on_resource_browser_browse_clicked()
static void on_resource_browser_browse_clicked (GtkWidget * widget, gpointer data) static
Handler for the "clicked" event of the browse button.
Shows a file open dialog to select a file.
If the connected resource value contains a valid filename/path, the dialog's directory is set to that file's directory. If only a filename is given, such as the default KERNAL, $datadir/$machine_name is used for the directory. In the dialog's directory listing the current file is selected.
Parameters
[in] widget browse button
[in] data state object pointer
Referenced by vice_gtk3_resource_browser_new().
on_resource_browser_destroy()
static void on_resource_browser_destroy (GtkWidget * widget, gpointer data) static
Clean up memory used by the main widget.
Parameters
[in,out] widget resource browser widget
[in] data state object pointer
Referenced by vice_gtk3_resource_browser_new(), and vice_gtk3_resource_browser_save_new().
on_resource_browser_save_clicked()
static void on_resource_browser_save_clicked (GtkWidget * widget, gpointer data) static
Handler for the "clicked" event of the save button.
Parameters
[in] widget save button
[in] data state object pointer
Referenced by vice_gtk3_resource_browser_save_new().
rb_state_free()
static void rb_state_free (rb_state_t * state) static
Free state object and all its members.
Parameters
[in] state state object
Referenced by on_resource_browser_destroy().
rb_state_free_patterns()
static void rb_state_free_patterns (rb_state_t * state) static
Free memory used by file type patterns.
Parameters
[in] state state object
Referenced by rb_state_free(), and rb_state_set_patterns().
rb_state_new()
static rb_state_t * rb_state_new (void) static
Allocate new state object and initialize all members to NULL.
Returns
new state object
Referenced by vice_gtk3_resource_browser_new(), and vice_gtk3_resource_browser_save_new().
rb_state_set_directory()
static void rb_state_set_directory (rb_state_t * state, const char * directory) static
Set/update directory in state object.
Frees the old directory string and sets it to directory. Passing NULL or "" for directory will free the directory string.
Parameters
[in] state state object
[in] directory new directory to use
Referenced by vice_gtk3_resource_browser_set_directory().
rb_state_set_patterns()
static void rb_state_set_patterns (rb_state_t * state, const char *const * patterns) static
Set file type patterns.
Make a deep copy of patterns in state. Calling with patterns set to NULL will free the patterns in state.
Parameters
[in] state state object
[in] patterns list of file type patterns
Referenced by vice_gtk3_resource_browser_new().
save_filename_callback()
static void save_filename_callback (GtkDialog * dialog, char * filename, gpointer data) static
Callback for the save dialog.
Parameters
[in,out] dialog Save file dialog reference
[in] filename filename or NULL on cancel
[in,out] data browser state
Referenced by on_resource_browser_save_clicked().
vice_gtk3_resource_browser_factory()
gboolean vice_gtk3_resource_browser_factory (GtkWidget * widget)
Reset widget to the resource's factory value.
Parameters
[in,out] widget resource browser widget
Returns
bool
vice_gtk3_resource_browser_get()
gboolean vice_gtk3_resource_browser_get (GtkWidget * widget, const char ** dest)
Get the current value of widget.
Get the current resource value of widget and store it in dest. If getting the resource value fails for some reason, FALSE is returned and dest is set to NULL.
Parameters
[in] widget resource browser widget
[out] dest destination of value
Returns
TRUE when the resource value was retrieved
vice_gtk3_resource_browser_new()
GtkWidget * vice_gtk3_resource_browser_new (const char * resource, const char *const * patterns, const char * pattern_name, const char * title, const char * label, void(*)(GtkWidget *, gpointer) callback)
Create file selection widget with browse button.
Parameters
[in] resource resource name
[in] patterns file match patterns (optional)
[in] pattern_name name to use for patterns in the file dialog (optional)
[in] browser_title title to display in the file dialog (optional, defaults to "Select file")
[in] label label (optional)
[in] callback user callback (optional, not implemented yet)
Note
both patterns and pattern_name need to be defined (ie not NULL for the patterns to work.
Returns
GtkGrid
Referenced by create_memhack_widget(), create_rom_file_widget(), and create_rs232_devices_widget().
vice_gtk3_resource_browser_reset()
gboolean vice_gtk3_resource_browser_reset (GtkWidget * widget)
Restore resource in widget to its original value.
Parameters
[in,out] widget resource browser widget
Returns
bool
vice_gtk3_resource_browser_save_new()
GtkWidget * vice_gtk3_resource_browser_save_new (const char * resource, const char * title, const char * label, const char * suggested, void(*)(GtkWidget *, gpointer) callback)
Resource browser widget to select a file to save.
Parameters
[in] resource resource name
[in] title dialog title
[in] label optional label before the text entry
[in] suggested suggested filename (unimplemented)
[in] callback callback
Returns
GtkGrid
Referenced by settings_monitor_widget_create().
vice_gtk3_resource_browser_set()
gboolean vice_gtk3_resource_browser_set (GtkWidget * widget, const char * new)
Set widget value to new.
Parameters
[in,out] widget resource browser widget
[in] new new value for widget
Returns
bool
Referenced by vice_gtk3_resource_browser_factory().
vice_gtk3_resource_browser_set_directory()
void vice_gtk3_resource_browser_set_directory (GtkWidget * widget, const char * directory)
Set the directory to use when the resource only contains a filename.
Set directory to append to a filename with directory component, or to use as the default directory for the 'save' variant of the resource browser.
Parameters
[in,out] widget resource browser widget
[in] path directory to use
vice_gtk3_resource_browser_sync()
gboolean vice_gtk3_resource_browser_sync (GtkWidget * widget)
Synchronize widget with current resource value.
Only needed to call if the resource's value is changed from code other than this widget's code.
Parameters
[in,out] widget resource browser widget
Returns
TRUE if the resource value was retrieved