x128: autostart-prg.h File Reference
autostart-prg.h File Reference
#include "types.h"
#include "log.h"
#include "fileio.h"
Data Structures
struct autostart_prg_s
Macros
#define AUTOSTART_PRG_MODE_VFS 0
#define AUTOSTART_PRG_MODE_INJECT 1
#define AUTOSTART_PRG_MODE_DISK 2
#define AUTOSTART_PRG_MODE_LAST 2
#define AUTOSTART_PRG_MODE_DEFAULT AUTOSTART_PRG_MODE_DISK
Typedefs
typedef struct autostart_prg_s autostart_prg_t
Functions
void autostart_prg_init (void)
void autostart_prg_shutdown (void)
int autostart_prg_with_virtual_fs (int unit, int drive, const char *file_name, fileio_info_t *fh, log_t log)
int autostart_prg_with_ram_injection (const char *file_name, fileio_info_t *fh, log_t log)
int autostart_prg_with_disk_image (int unit, int drive, const char *file_name, fileio_info_t *fh, log_t log, const char *image_name)
int autostart_prg_perform_injection (log_t log)
Macro Definition Documentation
AUTOSTART_PRG_MODE_DEFAULT
#define AUTOSTART_PRG_MODE_DEFAULT AUTOSTART_PRG_MODE_DISK
AUTOSTART_PRG_MODE_DISK
#define AUTOSTART_PRG_MODE_DISK 2
AUTOSTART_PRG_MODE_INJECT
#define AUTOSTART_PRG_MODE_INJECT 1
AUTOSTART_PRG_MODE_LAST
#define AUTOSTART_PRG_MODE_LAST 2
AUTOSTART_PRG_MODE_VFS
#define AUTOSTART_PRG_MODE_VFS 0
Typedef Documentation
autostart_prg_t
typedef struct autostart_prg_s autostart_prg_t
Function Documentation
autostart_prg_init()
void autostart_prg_init (void)
Referenced by autostart_init().
autostart_prg_perform_injection()
int autostart_prg_perform_injection (log_t log)
Referenced by advance_inject().
autostart_prg_shutdown()
void autostart_prg_shutdown (void)
Referenced by autostart_shutdown().
autostart_prg_with_disk_image()
int autostart_prg_with_disk_image (int unit, int drive, const char * file_name, fileio_info_t * fh, log_t log, const char * image_name)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 2.7 single floppy drive, 1M/disk
Referenced by autostart_prg().
autostart_prg_with_ram_injection()
int autostart_prg_with_ram_injection (const char * file_name, fileio_info_t * fh, log_t log)
Referenced by autostart_prg().
autostart_prg_with_virtual_fs()
int autostart_prg_with_virtual_fs (int unit, int drive, const char * file_name, fileio_info_t * fh, log_t log)
Todo:
FIXME: We should actually eat .'s and..'s from ‘directory’ instead.
Todo:
FIXME: not restored
< filesystem
Referenced by autostart_prg().