x128: arch/shared/hotkeys/ifstack.h File Reference
ifstack.h File Reference
IF stack implementation - header.
#include <stdbool.h>
Enumerations
enum {
IFSTACK_ERR_OK ,
IFSTACK_ERR_ELSE_WITHOUT_IF ,
IFSTACK_ERR_ENDIF_WITHOUT_IF
}
Functions
void ifstack_init (void)
Initialize stack for use.
void ifstack_reset (void)
Reset stack for reuse.
void ifstack_free (void)
Free the stack.
void ifstack_print (void)
Print stack contents on stdout.
void ifstack_if (bool state)
Push new IF condition on stack, update global condition.
bool ifstack_else (void)
Process ELSE branch.
bool ifstack_endif (void)
Process ENDIF.
bool ifstack_true (void)
Get global condition of stack.
bool ifstack_is_empty (void)
Determine if stack is empty.
const char * ifstack_strerror (int errnum)
Get error message for error number.
Variables
int ifstack_errno
Error code.
Detailed Description
IF stack implementation - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IFSTACK_ERR_OK
IFSTACK_ERR_ELSE_WITHOUT_IF
IFSTACK_ERR_ENDIF_WITHOUT_IF
Function Documentation
ifstack_else()
bool ifstack_else (void)
Process ELSE branch.
Notify the stack an ELSE branch should now be taken.
Returns
false if no preceeding IF or already in ELSE branch
Referenced by vhk_parser_do_else().
ifstack_endif()
bool ifstack_endif (void)
Process ENDIF.
Notify the stack an ENDIF statement should be handled.
Returns
false if there's no preceeding IF/ELSE
Referenced by vhk_parser_do_endif().
ifstack_free()
void ifstack_free (void)
Free the stack.
Referenced by ifstack_reset(), and vhk_parser_shutdown().
ifstack_if()
void ifstack_if (bool state)
Push new IF condition on stack, update global condition.
Parameters
[in] state condition of IF statement
Referenced by vhk_parser_do_if().
ifstack_init()
void ifstack_init (void)
Initialize stack for use.
Referenced by ifstack_reset(), and vhk_parser_init().
ifstack_is_empty()
bool ifstack_is_empty (void)
Determine if stack is empty.
Returns
true if stack is empty
Referenced by vhk_parser_parse().
ifstack_print()
void ifstack_print (void)
Print stack contents on stdout.
Print the current stack as an array of 0's and 1's.
Note
Doesn't print a newline at the end.
ifstack_reset()
void ifstack_reset (void)
Reset stack for reuse.
Frees any old stack remaining and initializes the stack for reuse.
Referenced by vhk_parser_parse().
ifstack_strerror()
const char * ifstack_strerror (int errnum)
Get error message for error number.
Parameters
[in] errnum error number
Returns
error message
Referenced by vhk_parser_do_else(), and vhk_parser_do_endif().
ifstack_true()
bool ifstack_true (void)
Get global condition of stack.
Returns
current condition
Referenced by vhk_parser_do_clear(), vhk_parser_do_debug(), vhk_parser_do_undef(), vhk_parser_do_warning(), vhk_parser_handle_keyword(), vhk_parser_handle_mapping(), and vhk_parser_parse().
Variable Documentation
ifstack_errno
int ifstack_errno extern
Error code.
Referenced by ifstack_else(), ifstack_endif(), ifstack_init(), vhk_parser_do_else(), and vhk_parser_do_endif().