vsid: arch/gtk3/widgets/settings_rom.c File Reference
settings_rom.c File Reference
Settings dialog to manage ROMs.
#include <gtk/gtk.h>
#include <stdbool.h>
#include "debug_gtk3.h"
#include "drive.h"
#include "lastdir.h"
#include "lib.h"
#include "petrom.h"
#include "resources.h"
#include "resourcewidgetmediator.h"
#include "romset.h"
#include "uiapi.h"
#include "vice_gtk3.h"
#include "settings_rom.h"
Data Structures
struct machine_rom_s
Machine ROM information.
struct drive_rom_s
Drive ROM information.
struct drive_exp_rom_s
Drive expansion ROM information.
Macros
#define LISTBOX_CSS "list { background-color: @theme_bg_color; }"
CSS for the GtkListBoxes used for the ROMs.
#define ARRAY_LEN(arr) (sizeof arr / sizeof arr[0])
Array length helper.
Typedefs
typedef struct machine_rom_s machine_rom_t
Machine ROM information.
typedef struct drive_rom_s drive_rom_t
Drive ROM information.
typedef struct drive_exp_rom_s drive_exp_rom_t
Drive expansion ROM information.
Functions
static const char ** string_list_append_list (const char **list1, const char **list2)
Forward declarations.
static const char ** get_all_resource_names (void)
Get list of all resource names for valid ROMs.
static const char ** expandable_list_get_resources (GtkWidget *list)
Get list of resource name and value pairs for a ROM list.
static void expandable_list_sync_resources (GtkWidget *list)
Synchronize all widgets in a ROM widget list with their resources.
static GtkWidget * expandable_list_get_chooser_by_resource (GtkWidget *list, const char *resource)
Find a resource filechooser in a ROMs list widget by resource name.
static void on_load_romset_callback (GtkDialog *dialog, gchar *filename, gpointer data)
{{{ Event handlers
static void on_load_romset_clicked (GtkButton *self, gpointer data)
Handler for the 'clicked' event of the "Load ROM set" button.
static void on_romset_save_callback (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the ROM set save dialog.
static void on_save_romset_clicked (GtkButton *self, gpointer data)
Handler for the 'clicked' event of the "Save ROM set" button.
static void on_reset_to_defaults_clicked (GtkButton *self, gpointer data)
Handler for the 'clicked' event of the "Reset to defaults" button.
static void on_reset_icon_clicked (GtkWidget *self, gpointer data)
Handler for the 'clicked' event of the reset-to-default icon button.
static void on_eject_icon_clicked (GtkWidget *self, gpointer data)
Handler for the 'clicked' event of the eject icon button.
static void on_chooser_drag_data_received (GtkWidget *self, GdkDragContext *context, gint x, gint y, GtkSelectionData *data, guint info, guint time, gpointer user_data)
Handler for the 'drag-data-received' event of a resource file chooser.
static void on_pet_charset_load_clicked (GtkWidget *self, gpointer data)
Handler for the 'clicked' event of a PET charset selection button.
static GtkWidget * label_helper (const char *markup, GtkAlign halign)
Create horizontally aligned label using Pango markup.
static GtkWidget * expandable_list_new (const char *title)
Create expandable list of file choosers.
static GList * expandable_list_get_children (GtkWidget *list)
Get list of GtkListBoxRows for a given ROM widget list.
static void add_rom_chooser (GtkWidget *list, const char *label_text, const char *resource_name)
Add resource file chooser with label to a ROMs section.
GtkWidget * settings_rom_widget_create (GtkWidget *parent)
}}}
void settings_rom_widget_shutdown (void)
Free resources used by the ROM settings.
Variables
static const machine_rom_t machine_rom_list []
List of machine ROM names and resources.
static const drive_rom_t drive_rom_list []
List of drive ROM IDs, names and resources.
static const drive_exp_rom_t drive_exp_rom_list []
List of drive expansion ROMs names and resources.
static const char * rom_patterns [] = { "*.bin", "*.rom", NULL }
Patterns for the ROM file chooser widgets.
static const char * romset_patterns [] = { "*.vrs", NULL }
Patterns for the ROM set file dialogs.
static GtkWidget * root_list
Main GtkListBox.
static GtkWidget * machine_roms
Machine ROMs widget.
static GtkWidget * drive_roms
Drive ROMs widget.
static GtkWidget * drive_exp_roms
Drive expansion ROMs widget.
static gchar * last_directory
Last directory used in a ROM set file dialog.
static gchar * last_filename
Last filename used in a ROM set file dialog.
static GtkCssProvider * listbox_css_provider
CSS provided used for the GtkListBox widgets.
Detailed Description
Settings dialog to manage ROMs.
Presents a GtkListBox with expandable rows for machine, drive and drive expansion ROMs, using a resource file chooser widget for each ROM. Drag-n-drop should also work, though I've only tested that on my Debian box with Gnome so far.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
ARRAY_LEN
#define ARRAY_LEN (arr) (sizeof arr / sizeof arr[0])
Array length helper.
Parameters
[in] arr array
Returns
length of arr in number of elements
LISTBOX_CSS
#define LISTBOX_CSS "list { background-color: @theme_bg_color; }"
CSS for the GtkListBoxes used for the ROMs.
We use the theme background color to avoid ugly white (light theme) or black areas (dark theme) areas around the widgets and in the unused space of the GtkScrolledWindow.
Typedef Documentation
drive_exp_rom_t
typedef struct drive_exp_rom_s drive_exp_rom_t
Drive expansion ROM information.
drive_rom_t
typedef struct drive_rom_s drive_rom_t
Drive ROM information.
machine_rom_t
typedef struct machine_rom_s machine_rom_t
Machine ROM information.
Function Documentation
add_rom_chooser()
static void add_rom_chooser (GtkWidget * list, const char * label_text, const char * resource_name) static
Add resource file chooser with label to a ROMs section.
Parameters
[in] list ROMs section
[in] label_text text for the label
[in] resource_name resource name for the resource file chooser
Referenced by settings_rom_widget_create().
expandable_list_get_children()
static GList * expandable_list_get_children (GtkWidget * list) static
Get list of GtkListBoxRows for a given ROM widget list.
Parameters
[in] list ROM widget list
Returns
all children of list
Note
free after use with g_list_free()
Referenced by expandable_list_get_chooser_by_resource(), expandable_list_get_resources(), and expandable_list_sync_resources().
expandable_list_get_chooser_by_resource()
static GtkWidget * expandable_list_get_chooser_by_resource (GtkWidget * list, const char * resource) static
Find a resource filechooser in a ROMs list widget by resource name.
Parameters
[in] list ROMs list
[in] resource resource name
Returns
resource filechooser widget or NULL if not found
Referenced by on_pet_charset_load_clicked().
expandable_list_get_resources()
static const char ** expandable_list_get_resources (GtkWidget * list) static
Get list of resource name and value pairs for a ROM list.
Parameters
[in] list ROM list (GtkListBoxRow)
Returns
list of ROM resources in the list, NULL terminated
Note
Free the list after use with lib_free()
Referenced by get_all_resource_names().
expandable_list_new()
static GtkWidget * expandable_list_new (const char * title) static
Create expandable list of file choosers.
Create a GtkListBoxRow with a GtkExpander that contains a GtkListBox for GtkListBoxRows with file chooser widgets (and labels).
Parameters
[in] title title for the expander
Returns
GtkListBoxRow
Referenced by settings_rom_widget_create().
expandable_list_sync_resources()
static void expandable_list_sync_resources (GtkWidget * list) static
Synchronize all widgets in a ROM widget list with their resources.
Parameters
[in] list ROM widget list
Referenced by on_load_romset_callback(), and on_reset_to_defaults_clicked().
get_all_resource_names()
static const char ** get_all_resource_names (void) static
Get list of all resource names for valid ROMs.
Returns
list of resource names, NULL terminated
Note
free list after use with lib_free()
Referenced by on_reset_to_defaults_clicked(), and on_romset_save_callback().
label_helper()
static GtkWidget * label_helper (const char * markup, GtkAlign halign) static
Create horizontally aligned label using Pango markup.
Parameters
[in] markup Pango markup text for the label
[in] halign horizontal alignment for the label
Returns
GtkLabel
Referenced by add_rom_chooser().
on_chooser_drag_data_received()
static void on_chooser_drag_data_received (GtkWidget * self, GdkDragContext * context, gint x, gint y, GtkSelectionData * data, guint info, guint time, gpointer user_data) static
Handler for the 'drag-data-received' event of a resource file chooser.
Parameters
[in] self resource file chooser
[in] context drag context
[in] x ignored
[in] y ignored
[in] data drag data
[in] info ignored
[in] time timestamp of drag event
[in] user_data extra event data (ignored)
Referenced by add_rom_chooser().
on_eject_icon_clicked()
static void on_eject_icon_clicked (GtkWidget * self, gpointer data) static
Handler for the 'clicked' event of the eject icon button.
"Eject" a ROM by clearing a resource.
Parameters
[in] self button (ignored)
[in] data resource file chooser for the ROM
Referenced by add_rom_chooser().
on_load_romset_callback()
static void on_load_romset_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
{{{ Event handlers
Callback for the ROM set open dialog
Parameters
[in] dialog ROM set load dialog
[in] filename filename (or NULL when canceled)
[in] data extra callback data (ignored)
Referenced by on_load_romset_clicked().
on_load_romset_clicked()
static void on_load_romset_clicked (GtkButton * self, gpointer data) static
Handler for the 'clicked' event of the "Load ROM set" button.
Shows dialog to open a ROM set file.
Parameters
[in] self button (ignored)
[in] data extra event data (unused)
Referenced by settings_rom_widget_create().
on_pet_charset_load_clicked()
static void on_pet_charset_load_clicked (GtkWidget * self, gpointer data) static
Handler for the 'clicked' event of a PET charset selection button.
Load a chargen ROM by setting the resource "ChargenName" to data.
Parameters
[in] self button (ignored)
[in] data new value for the "ChargenName" resource
Referenced by settings_rom_widget_create().
on_reset_icon_clicked()
static void on_reset_icon_clicked (GtkWidget * self, gpointer data) static
Handler for the 'clicked' event of the reset-to-default icon button.
Reset a ROM resource to its default value
Parameters
[in] self button (ignored)
[in] data resource file chooser for the ROM
Referenced by add_rom_chooser().
on_reset_to_defaults_clicked()
static void on_reset_to_defaults_clicked (GtkButton * self, gpointer data) static
Handler for the 'clicked' event of the "Reset to defaults" button.
Resets all ROM resources to factory values.
Parameters
[in] self button (ignored)
[in] data extra event data (unused)
Referenced by settings_rom_widget_create().
on_romset_save_callback()
static void on_romset_save_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the ROM set save dialog.
Parameters
[in] dialog ROM set save dialog
[in] filename filename (or NULL when canceled)
[in] data extra callback data (ignored)
Referenced by on_save_romset_clicked().
on_save_romset_clicked()
static void on_save_romset_clicked (GtkButton * self, gpointer data) static
Handler for the 'clicked' event of the "Save ROM set" button.
Shows dialog to save a ROM set file.
Parameters
[in] self button (ignored)
[in] data extra event data (unused)
Referenced by settings_rom_widget_create().
settings_rom_widget_create()
GtkWidget * settings_rom_widget_create (GtkWidget * parent)
}}}
Create ROM settings widget
Parameters
[in] parent unused
Returns
GtkGrid
settings_rom_widget_shutdown()
void settings_rom_widget_shutdown (void)
Free resources used by the ROM settings.
Frees the last used directory and filename of the file dialogs.
Referenced by ui_shutdown().
string_list_append_list()
static const char ** string_list_append_list (const char ** to, const char ** from) static
Forward declarations.
}}}
{{{ Helper functions
Append list of strings to another list of strings
Reallocate to to make space for all elements of from and append all elements from from to to.
Parameters
[in] to list of strings to append to
[in] from list of strings to append
Returns
to, possibly relocated
Referenced by get_all_resource_names().
Variable Documentation
drive_exp_rom_list
const drive_exp_rom_t drive_exp_rom_list[] static
Initial value:
= {
    { "Professional DOS 1571",  "DriveProfDOS1571Name" },
    { "Supercard+",             "DriveSuperCardName" },
    { "StarDOS",                "DriveStarDosName" },
}
List of drive expansion ROMs names and resources.
Referenced by settings_rom_widget_create().
drive_exp_roms
GtkWidget* drive_exp_roms static
Drive expansion ROMs widget.
GtkListBoxRow containing a GtkExpander containing a GtkListBox.
Referenced by get_all_resource_names(), on_load_romset_callback(), on_reset_to_defaults_clicked(), and settings_rom_widget_create().
drive_rom_list
const drive_rom_t drive_rom_list[] static
Initial value:
= {
    {  1540 ,       "CBM 1540" ,    "DosName1540" },
    {  1541 ,       "CBM 1541" ,    "DosName1541" },
    {  1542 ,     "CBM 1541-II" ,  "DosName1541ii" },
    {  1551 ,       "CBM 1551" ,    "DosName1551" },
    {  1571 ,       "CBM 1571" ,    "DosName1571" },
    {  1573 ,     "CBM 1571 CR" ,  "DosName1571cr" },
    {  1581 ,       "CBM 1581" ,    "DosName1581" },
    {  2000 ,       "CMD FD-2000" ,    "DosName2000" },
    {  4000 ,       "CMD FD-4000" ,    "DosName4000" },
    {  2031 ,       "CBM 2031" ,    "DosName2031" },
    {  2040  ,       "CBM 2040" ,    "DosName2040" },
    {  3040  ,       "CBM 3040" ,    "DosName3040" },
    {  4040  ,       "CBM 4040" ,    "DosName4040" },
    {  1001  ,       "CBM SFD-1001" ,    "DosName1001" },
    {  8050  ,       "CBM 8050" ,    NULL },
    {  8250  ,       "CBM 8250" ,    NULL },
    {  9000  ,       "CBM D9090/60" ,    "DosName9000" },
    {  4844  ,      "CMD HD" ,   "DosNameCMDHD" }
}
List of drive ROM IDs, names and resources.
!
Todo:
FIXME: shouldn't be here but somewhere in core code, but alas.
Referenced by settings_rom_widget_create().
drive_roms
GtkWidget* drive_roms static
Drive ROMs widget.
GtkListBoxRow containing a GtkExpander containing a GtkListBox.
Referenced by get_all_resource_names(), on_load_romset_callback(), on_reset_to_defaults_clicked(), and settings_rom_widget_create().
last_directory
gchar* last_directory static
Last directory used in a ROM set file dialog.
Referenced by on_load_romset_callback(), on_load_romset_clicked(), on_save_romset_clicked(), and settings_rom_widget_shutdown().
last_filename
gchar* last_filename static
Last filename used in a ROM set file dialog.
Referenced by on_load_romset_callback(), on_load_romset_clicked(), on_save_romset_clicked(), and settings_rom_widget_shutdown().
listbox_css_provider
GtkCssProvider* listbox_css_provider static
CSS provided used for the GtkListBox widgets.
Referenced by expandable_list_new(), settings_rom_widget_create(), and settings_rom_widget_shutdown().
machine_rom_list
const machine_rom_t machine_rom_list[] static
Initial value:
= {
    { "Kernal",                 "KernalName" },
    { "International kernal",   "KernalIntName" },
    { "Finish kernal",          "KernalFIName" },
    { "French kernal",          "KernalFRName" },
    { "German kernal",          "KernalDEName" },
    { "Italian kernal",         "KernalITName" },
    { "Norwegian kernal",       "KernalNOName" },
    { "Swedish kernal",         "KernalSEName" },
    { "Swiss kernal",           "KernalCHName" },
    { "C64 mode kernal",        "Kernal64Name" },
    { "SCPU64",                 "SCPU64Name" },
    { "Basic",                  "BasicName" },
    { "Basic low",              "BasicLoName" },
    { "Basic high",             "BasicHiName" },
    { "C64 mode Basic",         "Basic64Name" },
    { "Chargen",                "ChargenName" },
    { "International chargen",  "ChargenIntName" },
    { "Finish chargen",         "ChargenFIName" },
    { "French chargen",         "ChargenFRName" },
    { "German chargen",         "ChargenDEName" },
    { "Italian chargen",        "ChargenITName" },
    { "Norwegian chargen",      "ChargenNOName" },
    { "Swedish chargen",        "ChargenSEName" },
    { "Swiss chargen",          "ChargenCHName" },
    { "Function low",           "FunctionLowName" },
    { "Function high",          "FunctionHighName" },
    { "C1 low",                 "c1loName" },
    { "C1 high",                "c1hiName" },
    { "C2 low",                 "c2loName" },
    { "C2 high",                "c2hiName" },
    { "Editor",                 "EditorName" },
    { "$9000-$9FFF ROM",        "RomModule9Name" },
    { "$A000-$AFFF ROM",        "RomModuleAName" },
    { "$B000-$BFFF ROM",        "RomModuleBName" },
    { "H6809 ROM A",            "H6809RomAName" },
    { "H6809 ROM B",            "H6809RomBName" },
    { "H6809 ROM C",            "H6809RomCName" },
    { "H6809 ROM D",            "H6809RomDName" },
    { "H6809 ROM E",            "H6809RomEName" },
    { "H6809 ROM F",            "H6809RomFName" },
}
List of machine ROM names and resources.
Referenced by settings_rom_widget_create().
machine_roms
GtkWidget* machine_roms static
Machine ROMs widget.
GtkListBoxRow containing a GtkExpander containing a GtkListBox.
Referenced by get_all_resource_names(), on_load_romset_callback(), on_pet_charset_load_clicked(), on_reset_to_defaults_clicked(), and settings_rom_widget_create().
rom_patterns
const char* rom_patterns[] = { "*.bin", "*.rom", NULL } static
Patterns for the ROM file chooser widgets.
Referenced by add_rom_chooser().
romset_patterns
const char* romset_patterns[] = { "*.vrs", NULL } static
Patterns for the ROM set file dialogs.
Referenced by on_load_romset_clicked().
root_list
GtkWidget* root_list static
Main GtkListBox.
Referenced by settings_rom_widget_create().