vsid: crt.h File Reference
crt.h File Reference
#include "types.h"
Data Structures
struct crt_header_s
struct crt_chip_header_s
Typedefs
typedef struct crt_header_s crt_header_t
typedef struct crt_chip_header_s crt_chip_header_t
Functions
FILE * crt_open (const char *filename, crt_header_t *header)
int crt_getid (const char *filename)
int crt_read_chip_header (crt_chip_header_t *header, FILE *fd)
int crt_read_chip (uint8_t *rawcart, int offset, crt_chip_header_t *chip, FILE *fd)
int crt_write_chip (uint8_t *data, crt_chip_header_t *header, FILE *fd)
FILE * crt_create (const char *filename, int type, int exrom, int game, const char *name)
create classic v1.0 header
FILE * crt_create_v11 (const char *filename, int type, int subtype, int exrom, int game, const char *name)
create v1.1 header with sub type
FILE * crt_create_v20 (const char *filename, int type, int subtype, int exrom, int game, const char *name, int machine)
create 2.0 header
FILE * crt_create_vic20 (const char *filename, int type, int subtype, const char *name)
convenience functions for VIC20 etc
Typedef Documentation
crt_chip_header_t
typedef struct crt_chip_header_s crt_chip_header_t
crt_header_t
typedef struct crt_header_s crt_header_t
Function Documentation
crt_create()
FILE * crt_create (const char * filename, int type, int exrom, int game, const char * name)
create classic v1.0 header
< write mode (binary)
crt_create_v11()
FILE * crt_create_v11 (const char * filename, int type, int subtype, int exrom, int game, const char * name)
create v1.1 header with sub type
< write mode (binary)
crt_create_v20()
FILE * crt_create_v20 (const char * filename, int type, int subtype, int exrom, int game, const char * name, int machine)
create 2.0 header
create 2.0 header
< write mode (binary)
Referenced by crt_create_vic20().
crt_create_vic20()
FILE * crt_create_vic20 (const char * filename, int type, int subtype, const char * name)
convenience functions for VIC20 etc
crt_getid()
int crt_getid (const char * filename)
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by disk_image_check_for_dhd().
crt_open()
FILE * crt_open (const char * filename, crt_header_t * header)
< read mode (binary)
Referenced by crt_getid(), and crt_preview_widget_update().
crt_read_chip()
int crt_read_chip (uint8_t * rawcart, int offset, crt_chip_header_t * chip, FILE * fd)
crt_read_chip_header()
int crt_read_chip_header (crt_chip_header_t * header, FILE * fd)
Referenced by crt_preview_widget_update().
crt_write_chip()
int crt_write_chip (uint8_t * data, crt_chip_header_t * header, FILE * fd)