vsid: monitor/mon_util.h File Reference
mon_util.h File Reference
#include "monitor.h"
#include "types.h"
Functions
char * mon_disassemble_with_label (MEMSPACE memspace, uint16_t loc, int hex, unsigned *opc_size_p, unsigned *label_p)
char * mon_dump_with_label (MEMSPACE memspace, uint16_t loc, int hex, unsigned *label_p)
void mon_set_command (struct console_s *console_log, char *command, void(*)(void))
void mon_event_opened (void)
Notify interested interfaces that the monitor opened.
void mon_event_closed (void)
Notify interested interfaces that the monitor closed.
int mon_log_file_open (const char *name)
void mon_log_file_close (void)
Function Documentation
mon_disassemble_with_label()
char * mon_disassemble_with_label (MEMSPACE memspace, uint16_t loc, int hex, unsigned * opc_size_p, unsigned * label_p)
mon_dump_with_label()
char * mon_dump_with_label (MEMSPACE memspace, uint16_t loc, int hex, unsigned * label_p)
mon_event_closed()
void mon_event_closed (void)
Notify interested interfaces that the monitor closed.
Referenced by monitor_close().
mon_event_opened()
void mon_event_opened (void)
Notify interested interfaces that the monitor opened.
Referenced by monitor_open().
mon_log_file_close()
void mon_log_file_close (void)
Referenced by mon_log_file_open(), monitor_shutdown(), set_monitor_log_enabled(), and set_monitor_log_filename().
mon_log_file_open()
int mon_log_file_open (const char * name)
< append mode
Referenced by set_monitor_log_enabled(), and set_monitor_log_filename().
mon_set_command()
void mon_set_command (struct console_s * console_log, char * command, void(*)(void) pAfter)
Referenced by uimon_in().