vsid: arch/shared/uiactions.h File Reference
uiactions.h File Reference
UI actions interface - header.
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <ctype.h>
#include "machine.h"
Data Structures
struct ui_action_info_s
this header is required if the macro IS_ACTION_NAME_CHAR() is used:
struct ui_action_map_s
Mapping of an action ID to a handler.
Macros
#define UI_ACTION_MAP_TERMINATOR { .action = ACTION_NONE, .handler = NULL }
Terminator of action maps.
#define IS_ACTION_NAME_CHAR(ch)
Check for valid action name character.
Typedefs
typedef struct ui_action_info_s ui_action_info_t
this header is required if the macro IS_ACTION_NAME_CHAR() is used:
typedef struct ui_action_map_s ui_action_map_t
Mapping of an action ID to a handler.
Enumerations
enum {
ACTION_INVALID = -1 ,
ACTION_NONE = 0 ,
ACTION_ADVANCE_FRAME ,
ACTION_CART_ATTACH ,
ACTION_CART_ATTACH_RAW ,
ACTION_CART_ATTACH_RAW_1000 ,
ACTION_CART_ATTACH_RAW_2000 ,
ACTION_CART_ATTACH_RAW_4000 ,
ACTION_CART_ATTACH_RAW_6000 ,
ACTION_CART_ATTACH_RAW_A000 ,
ACTION_CART_ATTACH_RAW_B000 ,
ACTION_CART_ATTACH_RAW_BEHRBONZ ,
ACTION_CART_ATTACH_RAW_FINAL ,
ACTION_CART_ATTACH_RAW_MEGACART ,
ACTION_CART_ATTACH_RAW_ULTIMEM ,
ACTION_CART_ATTACH_RAW_VICFP ,
ACTION_CART_ATTACH_RAW_JACINT1MB ,
ACTION_CART_ATTACH_RAW_MAGIC ,
ACTION_CART_ATTACH_RAW_MULTI ,
ACTION_CART_ATTACH_RAW_C1_FULL ,
ACTION_CART_ATTACH_RAW_C1_LOW ,
ACTION_CART_ATTACH_RAW_C1_HIGH ,
ACTION_CART_ATTACH_RAW_C2_FULL ,
ACTION_CART_ATTACH_RAW_C2_LOW ,
ACTION_CART_ATTACH_RAW_C2_HIGH ,
ACTION_CART_DETACH ,
ACTION_CART_DETACH_1000 ,
ACTION_CART_DETACH_2000 ,
ACTION_CART_DETACH_4000 ,
ACTION_CART_DETACH_6000 ,
ACTION_CART_FREEZE ,
ACTION_DEBUG_AUTOPLAYBACK_FRAMES ,
ACTION_DEBUG_BLITTER_LOG_TOGGLE ,
ACTION_DEBUG_CORE_DUMP_TOGGLE ,
ACTION_DEBUG_DMA_LOG_TOGGLE ,
ACTION_DEBUG_FLASH_LOG_TOGGLE ,
ACTION_DEBUG_TRACE_CPU_TOGGLE ,
ACTION_DEBUG_TRACE_DRIVE_10_TOGGLE ,
ACTION_DEBUG_TRACE_DRIVE_11_TOGGLE ,
ACTION_DEBUG_TRACE_DRIVE_8_TOGGLE ,
ACTION_DEBUG_TRACE_DRIVE_9_TOGGLE ,
ACTION_DEBUG_TRACE_IEC_TOGGLE ,
ACTION_DEBUG_TRACE_IEEE488_TOGGLE ,
ACTION_DEBUG_TRACE_MODE ,
ACTION_DRIVE_ATTACH_10_0 ,
ACTION_DRIVE_ATTACH_10_1 ,
ACTION_DRIVE_ATTACH_11_0 ,
ACTION_DRIVE_ATTACH_11_1 ,
ACTION_DRIVE_ATTACH_8_0 ,
ACTION_DRIVE_ATTACH_8_1 ,
ACTION_DRIVE_ATTACH_9_0 ,
ACTION_DRIVE_ATTACH_9_1 ,
ACTION_DRIVE_CREATE ,
ACTION_DRIVE_DETACH_10_0 ,
ACTION_DRIVE_DETACH_10_1 ,
ACTION_DRIVE_DETACH_11_0 ,
ACTION_DRIVE_DETACH_11_1 ,
ACTION_DRIVE_DETACH_8_0 ,
ACTION_DRIVE_DETACH_8_1 ,
ACTION_DRIVE_DETACH_9_0 ,
ACTION_DRIVE_DETACH_9_1 ,
ACTION_DRIVE_DETACH_ALL ,
ACTION_EDIT_COPY ,
ACTION_EDIT_PASTE ,
ACTION_FLIPLIST_ADD_8_0 ,
ACTION_FLIPLIST_CLEAR_8_0 ,
ACTION_FLIPLIST_LOAD_8_0 ,
ACTION_FLIPLIST_NEXT_8_0 ,
ACTION_FLIPLIST_PREVIOUS_8_0 ,
ACTION_FLIPLIST_REMOVE_8_0 ,
ACTION_FLIPLIST_SAVE_8_0 ,
ACTION_FLIPLIST_ADD_8_1 ,
ACTION_FLIPLIST_CLEAR_8_1 ,
ACTION_FLIPLIST_LOAD_8_1 ,
ACTION_FLIPLIST_NEXT_8_1 ,
ACTION_FLIPLIST_PREVIOUS_8_1 ,
ACTION_FLIPLIST_REMOVE_8_1 ,
ACTION_FLIPLIST_SAVE_8_1 ,
ACTION_FLIPLIST_ADD_9_0 ,
ACTION_FLIPLIST_CLEAR_9_0 ,
ACTION_FLIPLIST_LOAD_9_0 ,
ACTION_FLIPLIST_NEXT_9_0 ,
ACTION_FLIPLIST_PREVIOUS_9_0 ,
ACTION_FLIPLIST_REMOVE_9_0 ,
ACTION_FLIPLIST_SAVE_9_0 ,
ACTION_FLIPLIST_ADD_9_1 ,
ACTION_FLIPLIST_CLEAR_9_1 ,
ACTION_FLIPLIST_LOAD_9_1 ,
ACTION_FLIPLIST_NEXT_9_1 ,
ACTION_FLIPLIST_PREVIOUS_9_1 ,
ACTION_FLIPLIST_REMOVE_9_1 ,
ACTION_FLIPLIST_SAVE_9_1 ,
ACTION_FLIPLIST_ADD_10_0 ,
ACTION_FLIPLIST_CLEAR_10_0 ,
ACTION_FLIPLIST_LOAD_10_0 ,
ACTION_FLIPLIST_NEXT_10_0 ,
ACTION_FLIPLIST_PREVIOUS_10_0 ,
ACTION_FLIPLIST_REMOVE_10_0 ,
ACTION_FLIPLIST_SAVE_10_0 ,
ACTION_FLIPLIST_ADD_10_1 ,
ACTION_FLIPLIST_CLEAR_10_1 ,
ACTION_FLIPLIST_LOAD_10_1 ,
ACTION_FLIPLIST_NEXT_10_1 ,
ACTION_FLIPLIST_PREVIOUS_10_1 ,
ACTION_FLIPLIST_REMOVE_10_1 ,
ACTION_FLIPLIST_SAVE_10_1 ,
ACTION_FLIPLIST_ADD_11_0 ,
ACTION_FLIPLIST_CLEAR_11_0 ,
ACTION_FLIPLIST_LOAD_11_0 ,
ACTION_FLIPLIST_NEXT_11_0 ,
ACTION_FLIPLIST_PREVIOUS_11_0 ,
ACTION_FLIPLIST_REMOVE_11_0 ,
ACTION_FLIPLIST_SAVE_11_0 ,
ACTION_FLIPLIST_ADD_11_1 ,
ACTION_FLIPLIST_CLEAR_11_1 ,
ACTION_FLIPLIST_LOAD_11_1 ,
ACTION_FLIPLIST_NEXT_11_1 ,
ACTION_FLIPLIST_PREVIOUS_11_1 ,
ACTION_FLIPLIST_REMOVE_11_1 ,
ACTION_FLIPLIST_SAVE_11_1 ,
ACTION_FULLSCREEN_DECORATIONS_TOGGLE ,
ACTION_FULLSCREEN_TOGGLE ,
ACTION_HELP_ABOUT ,
ACTION_HELP_COMMAND_LINE ,
ACTION_HELP_COMPILE_TIME ,
ACTION_HELP_HOTKEYS ,
ACTION_HELP_MANUAL ,
ACTION_HISTORY_MILESTONE_RESET ,
ACTION_HISTORY_MILESTONE_SET ,
ACTION_HISTORY_PLAYBACK_START ,
ACTION_HISTORY_PLAYBACK_STOP ,
ACTION_HISTORY_RECORD_START ,
ACTION_HISTORY_RECORD_STOP ,
ACTION_HOTKEYS_CLEAR ,
ACTION_HOTKEYS_DEFAULT ,
ACTION_HOTKEYS_LOAD ,
ACTION_HOTKEYS_LOAD_FROM ,
ACTION_HOTKEYS_SAVE ,
ACTION_HOTKEYS_SAVE_TO ,
ACTION_KEYSET_JOYSTICK_TOGGLE ,
ACTION_MEDIA_RECORD ,
ACTION_MEDIA_RECORD_AUDIO ,
ACTION_MEDIA_RECORD_SCREENSHOT ,
ACTION_MEDIA_RECORD_VIDEO ,
ACTION_MEDIA_STOP ,
ACTION_MONITOR_OPEN ,
ACTION_MOUSE_GRAB_TOGGLE ,
ACTION_PAUSE_TOGGLE ,
ACTION_QUIT ,
ACTION_MACHINE_RESET_CPU ,
ACTION_MACHINE_POWER_CYCLE ,
ACTION_RESET_DRIVE_8 ,
ACTION_RESET_DRIVE_8_CONFIG ,
ACTION_RESET_DRIVE_8_INSTALL ,
ACTION_RESET_DRIVE_9 ,
ACTION_RESET_DRIVE_9_CONFIG ,
ACTION_RESET_DRIVE_9_INSTALL ,
ACTION_RESET_DRIVE_10 ,
ACTION_RESET_DRIVE_10_CONFIG ,
ACTION_RESET_DRIVE_10_INSTALL ,
ACTION_RESET_DRIVE_11 ,
ACTION_RESET_DRIVE_11_CONFIG ,
ACTION_RESET_DRIVE_11_INSTALL ,
ACTION_RESTORE_DISPLAY ,
ACTION_SCREENSHOT_QUICKSAVE ,
ACTION_SETTINGS_DEFAULT ,
ACTION_SETTINGS_DIALOG ,
ACTION_SETTINGS_LOAD_EXTRA ,
ACTION_SETTINGS_LOAD_FROM ,
ACTION_SETTINGS_LOAD ,
ACTION_SETTINGS_SAVE ,
ACTION_SETTINGS_SAVE_TO ,
ACTION_SHOW_STATUSBAR_TOGGLE ,
ACTION_SHOW_STATUSBAR_SECONDARY_TOGGLE ,
ACTION_SMART_ATTACH ,
ACTION_SNAPSHOT_LOAD ,
ACTION_SNAPSHOT_QUICKLOAD ,
ACTION_SNAPSHOT_QUICKSAVE ,
ACTION_SNAPSHOT_SAVE ,
ACTION_SPEED_CPU_10 ,
ACTION_SPEED_CPU_25 ,
ACTION_SPEED_CPU_50 ,
ACTION_SPEED_CPU_100 ,
ACTION_SPEED_CPU_200 ,
ACTION_SPEED_CPU_CUSTOM ,
ACTION_SPEED_FPS_50 ,
ACTION_SPEED_FPS_60 ,
ACTION_SPEED_FPS_CUSTOM ,
ACTION_SPEED_FPS_REAL ,
ACTION_SWAP_CONTROLPORT_TOGGLE ,
ACTION_TAPE_ATTACH_1 ,
ACTION_TAPE_ATTACH_2 ,
ACTION_TAPE_CREATE_1 ,
ACTION_TAPE_CREATE_2 ,
ACTION_TAPE_DETACH_1 ,
ACTION_TAPE_DETACH_2 ,
ACTION_TAPE_FFWD_1 ,
ACTION_TAPE_FFWD_2 ,
ACTION_TAPE_PLAY_1 ,
ACTION_TAPE_PLAY_2 ,
ACTION_TAPE_RECORD_1 ,
ACTION_TAPE_RECORD_2 ,
ACTION_TAPE_RESET_1 ,
ACTION_TAPE_RESET_2 ,
ACTION_TAPE_RESET_COUNTER_1 ,
ACTION_TAPE_RESET_COUNTER_2 ,
ACTION_TAPE_REWIND_1 ,
ACTION_TAPE_REWIND_2 ,
ACTION_TAPE_STOP_1 ,
ACTION_TAPE_STOP_2 ,
ACTION_WARP_MODE_TOGGLE ,
ACTION_PSID_LOAD ,
ACTION_PSID_OVERRIDE_TOGGLE ,
ACTION_PSID_SUBTUNE_1 ,
ACTION_PSID_SUBTUNE_2 ,
ACTION_PSID_SUBTUNE_3 ,
ACTION_PSID_SUBTUNE_4 ,
ACTION_PSID_SUBTUNE_5 ,
ACTION_PSID_SUBTUNE_6 ,
ACTION_PSID_SUBTUNE_7 ,
ACTION_PSID_SUBTUNE_8 ,
ACTION_PSID_SUBTUNE_9 ,
ACTION_PSID_SUBTUNE_10 ,
ACTION_PSID_SUBTUNE_11 ,
ACTION_PSID_SUBTUNE_12 ,
ACTION_PSID_SUBTUNE_13 ,
ACTION_PSID_SUBTUNE_14 ,
ACTION_PSID_SUBTUNE_15 ,
ACTION_PSID_SUBTUNE_16 ,
ACTION_PSID_SUBTUNE_17 ,
ACTION_PSID_SUBTUNE_18 ,
ACTION_PSID_SUBTUNE_19 ,
ACTION_PSID_SUBTUNE_20 ,
ACTION_PSID_SUBTUNE_21 ,
ACTION_PSID_SUBTUNE_22 ,
ACTION_PSID_SUBTUNE_23 ,
ACTION_PSID_SUBTUNE_24 ,
ACTION_PSID_SUBTUNE_25 ,
ACTION_PSID_SUBTUNE_26 ,
ACTION_PSID_SUBTUNE_27 ,
ACTION_PSID_SUBTUNE_28 ,
ACTION_PSID_SUBTUNE_29 ,
ACTION_PSID_SUBTUNE_30 ,
ACTION_PSID_SUBTUNE_DEFAULT ,
ACTION_PSID_SUBTUNE_NEXT ,
ACTION_PSID_SUBTUNE_PREVIOUS ,
ACTION_PSID_PLAY ,
ACTION_PSID_PAUSE ,
ACTION_PSID_STOP ,
ACTION_PSID_FFWD ,
ACTION_PSID_LOOP_TOGGLE ,
ACTION_PSID_PLAYLIST_FIRST ,
ACTION_PSID_PLAYLIST_PREVIOUS ,
ACTION_PSID_PLAYLIST_NEXT ,
ACTION_PSID_PLAYLIST_LAST ,
ACTION_PSID_PLAYLIST_ADD ,
ACTION_PSID_PLAYLIST_LOAD ,
ACTION_PSID_PLAYLIST_SAVE ,
ACTION_PSID_PLAYLIST_CLEAR ,
ACTION_DIAGNOSTIC_PIN_TOGGLE ,
ACTION_PRINTER_FORMFEED_4 ,
ACTION_PRINTER_FORMFEED_5 ,
ACTION_PRINTER_FORMFEED_6 ,
ACTION_PRINTER_FORMFEED_USERPORT ,
ACTION_VIRTUAL_KEYBOARD ,
ACTION_BORDER_MODE_NORMAL ,
ACTION_BORDER_MODE_FULL ,
ACTION_BORDER_MODE_DEBUG ,
ACTION_BORDER_MODE_NONE ,
ACTION_SCPU_JIFFY_SWITCH_TOGGLE ,
ACTION_SCPU_SPEED_SWITCH_TOGGLE ,
ACTION_ID_COUNT
}
IDs for the UI actions.
Functions
int ui_action_get_id (const char *name)
Action info getters.
const char * ui_action_get_name (int action)
Get action name by ID.
const char * ui_action_get_desc (int action)
Get description of an action.
ui_action_info_t * ui_action_get_info_list (void)
Get list of actions.
bool ui_action_is_valid (int action)
Determine if action is valid for the current machine.
int ui_action_id_fliplist_add (int unit, int drive)
Get action IDs for drive actions.
int ui_action_id_fliplist_remove (int unit, int drive)
Get fliplist-remove action ID for unit and drive.
int ui_action_id_fliplist_next (int unit, int drive)
Get fliplist-next action ID for unit and drive.
int ui_action_id_fliplist_previous (int unit, int drive)
Get fliplist-previous action ID for unit and drive.
int ui_action_id_fliplist_clear (int unit, int drive)
Get fliplist-clear action ID for unit and drive.
int ui_action_id_fliplist_load (int unit, int drive)
Get fliplist-load action ID for unit and drive.
int ui_action_id_fliplist_save (int unit, int drive)
Get fliplist-save action ID for unit and drive.
int ui_action_id_drive_attach (int unit, int drive)
Get drive-attach action ID for unit and drive.
int ui_action_id_drive_detach (int unit, int drive)
Get drive-detach action ID for unit and drive.
int ui_action_id_drive_reset (int unit)
Get reset-drive action ID for unit.
int ui_action_id_drive_reset_config (int unit)
Get reset-drive-config action ID for unit.
int ui_action_id_drive_reset_install (int unit)
Get reset-drive-install action ID for unit.
void ui_actions_init (void)
Main API.
void ui_actions_set_dispatch (void(*dispatch)(ui_action_map_t *))
Set UI-specific function to dispatch UI action handlers.
void ui_actions_shutdown (void)
Free all resources used by the UI actions system.
void ui_actions_register (const ui_action_map_t *mappings)
Register UI action implementations.
void ui_action_trigger (int action)
Trigger a UI action.
void ui_action_finish (int action)
Mark a UI action as finished.
bool ui_action_def (int action, const char *hotkey)
bool ui_action_redef (int action, const char *hotkey)
bool ui_action_undef (int action)
ui_action_map_t * ui_action_map_get (int action)
Get UI action map by UI action ID.
ui_action_map_t * ui_action_map_get_by_hotkey (uint32_t vice_keysym, uint32_t vice_modmask)
Get UI action map by VICE hotkey.
ui_action_map_t * ui_action_map_get_by_arch_hotkey (uint32_t arch_keysym, uint32_t arch_modmask)
Get UI action map by arch hotkey.
void ui_action_map_clear_hotkey (ui_action_map_t *map)
Clear hotkey.
void ui_action_map_clear_hotkey_by_action (int action)
Clear hotkey.
void ui_action_map_clear_hotkey_by_hotkey (uint32_t vice_keysym, uint32_t vice_modmask)
Clear hotkey.
ui_action_map_t * ui_action_map_set_hotkey (int action, uint32_t vice_keysym, uint32_t vice_modmask, uint32_t arch_keysym, uint32_t arch_modmask)
Set hotkey for action.
void ui_action_map_set_hotkey_by_map (ui_action_map_t *map, uint32_t vice_keysym, uint32_t vice_modmask, uint32_t arch_keysym, uint32_t arch_modmask)
Set hotkey for action.
char * ui_action_map_get_hotkey_label (ui_action_map_t *map)
Get hotkey label for action map.
char * ui_action_get_hotkey_label (int action)
Get hotkey label for action ID.
Detailed Description
UI actions interface - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
IS_ACTION_NAME_CHAR
#define IS_ACTION_NAME_CHAR (ch)
Value:
    (isalpha((unsigned char)(ch)) || isdigit((unsigned char)(ch)) || \
     ch == '_' || ch == '-' || ch == ':')
Check for valid action name character.
Check if ch is a valid character in an action name.
Supported characters are:
a-z
A-Z
0-9
'_', '-' and ':'
UI_ACTION_MAP_TERMINATOR
#define UI_ACTION_MAP_TERMINATOR { .action = ACTION_NONE, .handler = NULL }
Terminator of action maps.
Typedef Documentation
ui_action_info_t
typedef struct ui_action_info_s ui_action_info_t
this header is required if the macro IS_ACTION_NAME_CHAR() is used:
for the VICE_MACHINE_* masks
Mapping of action IDs to names and descriptions
ui_action_map_t
typedef struct ui_action_map_s ui_action_map_t
Mapping of an action ID to a handler.
Enumeration Type Documentation
anonymous enum
anonymous enum
IDs for the UI actions.
These IDs are used to refer to specific UI actions/dialogs.
Enumerator
ACTION_INVALID
ACTION_NONE
ACTION_ADVANCE_FRAME
ACTION_CART_ATTACH
ACTION_CART_ATTACH_RAW
ACTION_CART_ATTACH_RAW_1000
ACTION_CART_ATTACH_RAW_2000
ACTION_CART_ATTACH_RAW_4000
ACTION_CART_ATTACH_RAW_6000
ACTION_CART_ATTACH_RAW_A000
ACTION_CART_ATTACH_RAW_B000
ACTION_CART_ATTACH_RAW_BEHRBONZ
ACTION_CART_ATTACH_RAW_FINAL
ACTION_CART_ATTACH_RAW_MEGACART
ACTION_CART_ATTACH_RAW_ULTIMEM
ACTION_CART_ATTACH_RAW_VICFP
ACTION_CART_ATTACH_RAW_JACINT1MB
ACTION_CART_ATTACH_RAW_MAGIC
ACTION_CART_ATTACH_RAW_MULTI
ACTION_CART_ATTACH_RAW_C1_FULL
ACTION_CART_ATTACH_RAW_C1_LOW
ACTION_CART_ATTACH_RAW_C1_HIGH
ACTION_CART_ATTACH_RAW_C2_FULL
ACTION_CART_ATTACH_RAW_C2_LOW
ACTION_CART_ATTACH_RAW_C2_HIGH
ACTION_CART_DETACH
ACTION_CART_DETACH_1000
ACTION_CART_DETACH_2000
ACTION_CART_DETACH_4000
ACTION_CART_DETACH_6000
ACTION_CART_FREEZE
ACTION_DEBUG_AUTOPLAYBACK_FRAMES
ACTION_DEBUG_BLITTER_LOG_TOGGLE
ACTION_DEBUG_CORE_DUMP_TOGGLE
ACTION_DEBUG_DMA_LOG_TOGGLE
ACTION_DEBUG_FLASH_LOG_TOGGLE
ACTION_DEBUG_TRACE_CPU_TOGGLE
ACTION_DEBUG_TRACE_DRIVE_10_TOGGLE
ACTION_DEBUG_TRACE_DRIVE_11_TOGGLE
ACTION_DEBUG_TRACE_DRIVE_8_TOGGLE
ACTION_DEBUG_TRACE_DRIVE_9_TOGGLE
ACTION_DEBUG_TRACE_IEC_TOGGLE
ACTION_DEBUG_TRACE_IEEE488_TOGGLE
ACTION_DEBUG_TRACE_MODE
ACTION_DRIVE_ATTACH_10_0
ACTION_DRIVE_ATTACH_10_1
ACTION_DRIVE_ATTACH_11_0
ACTION_DRIVE_ATTACH_11_1
ACTION_DRIVE_ATTACH_8_0
ACTION_DRIVE_ATTACH_8_1
ACTION_DRIVE_ATTACH_9_0
ACTION_DRIVE_ATTACH_9_1
ACTION_DRIVE_CREATE
ACTION_DRIVE_DETACH_10_0
ACTION_DRIVE_DETACH_10_1
ACTION_DRIVE_DETACH_11_0
ACTION_DRIVE_DETACH_11_1
ACTION_DRIVE_DETACH_8_0
ACTION_DRIVE_DETACH_8_1
ACTION_DRIVE_DETACH_9_0
ACTION_DRIVE_DETACH_9_1
ACTION_DRIVE_DETACH_ALL
ACTION_EDIT_COPY
ACTION_EDIT_PASTE
ACTION_FLIPLIST_ADD_8_0
ACTION_FLIPLIST_CLEAR_8_0
ACTION_FLIPLIST_LOAD_8_0
ACTION_FLIPLIST_NEXT_8_0
ACTION_FLIPLIST_PREVIOUS_8_0
ACTION_FLIPLIST_REMOVE_8_0
ACTION_FLIPLIST_SAVE_8_0
ACTION_FLIPLIST_ADD_8_1
ACTION_FLIPLIST_CLEAR_8_1
ACTION_FLIPLIST_LOAD_8_1
ACTION_FLIPLIST_NEXT_8_1
ACTION_FLIPLIST_PREVIOUS_8_1
ACTION_FLIPLIST_REMOVE_8_1
ACTION_FLIPLIST_SAVE_8_1
ACTION_FLIPLIST_ADD_9_0
ACTION_FLIPLIST_CLEAR_9_0
ACTION_FLIPLIST_LOAD_9_0
ACTION_FLIPLIST_NEXT_9_0
ACTION_FLIPLIST_PREVIOUS_9_0
ACTION_FLIPLIST_REMOVE_9_0
ACTION_FLIPLIST_SAVE_9_0
ACTION_FLIPLIST_ADD_9_1
ACTION_FLIPLIST_CLEAR_9_1
ACTION_FLIPLIST_LOAD_9_1
ACTION_FLIPLIST_NEXT_9_1
ACTION_FLIPLIST_PREVIOUS_9_1
ACTION_FLIPLIST_REMOVE_9_1
ACTION_FLIPLIST_SAVE_9_1
ACTION_FLIPLIST_ADD_10_0
ACTION_FLIPLIST_CLEAR_10_0
ACTION_FLIPLIST_LOAD_10_0
ACTION_FLIPLIST_NEXT_10_0
ACTION_FLIPLIST_PREVIOUS_10_0
ACTION_FLIPLIST_REMOVE_10_0
ACTION_FLIPLIST_SAVE_10_0
ACTION_FLIPLIST_ADD_10_1
ACTION_FLIPLIST_CLEAR_10_1
ACTION_FLIPLIST_LOAD_10_1
ACTION_FLIPLIST_NEXT_10_1
ACTION_FLIPLIST_PREVIOUS_10_1
ACTION_FLIPLIST_REMOVE_10_1
ACTION_FLIPLIST_SAVE_10_1
ACTION_FLIPLIST_ADD_11_0
ACTION_FLIPLIST_CLEAR_11_0
ACTION_FLIPLIST_LOAD_11_0
ACTION_FLIPLIST_NEXT_11_0
ACTION_FLIPLIST_PREVIOUS_11_0
ACTION_FLIPLIST_REMOVE_11_0
ACTION_FLIPLIST_SAVE_11_0
ACTION_FLIPLIST_ADD_11_1
ACTION_FLIPLIST_CLEAR_11_1
ACTION_FLIPLIST_LOAD_11_1
ACTION_FLIPLIST_NEXT_11_1
ACTION_FLIPLIST_PREVIOUS_11_1
ACTION_FLIPLIST_REMOVE_11_1
ACTION_FLIPLIST_SAVE_11_1
ACTION_FULLSCREEN_DECORATIONS_TOGGLE
ACTION_FULLSCREEN_TOGGLE
ACTION_HELP_ABOUT
ACTION_HELP_COMMAND_LINE
ACTION_HELP_COMPILE_TIME
ACTION_HELP_HOTKEYS
ACTION_HELP_MANUAL
ACTION_HISTORY_MILESTONE_RESET
ACTION_HISTORY_MILESTONE_SET
ACTION_HISTORY_PLAYBACK_START
ACTION_HISTORY_PLAYBACK_STOP
ACTION_HISTORY_RECORD_START
ACTION_HISTORY_RECORD_STOP
ACTION_HOTKEYS_CLEAR
ACTION_HOTKEYS_DEFAULT
ACTION_HOTKEYS_LOAD
ACTION_HOTKEYS_LOAD_FROM
ACTION_HOTKEYS_SAVE
ACTION_HOTKEYS_SAVE_TO
ACTION_KEYSET_JOYSTICK_TOGGLE
ACTION_MEDIA_RECORD
ACTION_MEDIA_RECORD_AUDIO
ACTION_MEDIA_RECORD_SCREENSHOT
ACTION_MEDIA_RECORD_VIDEO
ACTION_MEDIA_STOP
ACTION_MONITOR_OPEN
ACTION_MOUSE_GRAB_TOGGLE
ACTION_PAUSE_TOGGLE
ACTION_QUIT
ACTION_MACHINE_RESET_CPU
ACTION_MACHINE_POWER_CYCLE
ACTION_RESET_DRIVE_8
Todo:
rework into DRIVE_[9-11]RESET_BUTTON/POWER_CYCLE_ etc.
ACTION_RESET_DRIVE_8_CONFIG
ACTION_RESET_DRIVE_8_INSTALL
ACTION_RESET_DRIVE_9
ACTION_RESET_DRIVE_9_CONFIG
ACTION_RESET_DRIVE_9_INSTALL
ACTION_RESET_DRIVE_10
ACTION_RESET_DRIVE_10_CONFIG
ACTION_RESET_DRIVE_10_INSTALL
ACTION_RESET_DRIVE_11
ACTION_RESET_DRIVE_11_CONFIG
ACTION_RESET_DRIVE_11_INSTALL
ACTION_RESTORE_DISPLAY
ACTION_SCREENSHOT_QUICKSAVE
ACTION_SETTINGS_DEFAULT
ACTION_SETTINGS_DIALOG
ACTION_SETTINGS_LOAD_EXTRA
ACTION_SETTINGS_LOAD_FROM
ACTION_SETTINGS_LOAD
ACTION_SETTINGS_SAVE
ACTION_SETTINGS_SAVE_TO
ACTION_SHOW_STATUSBAR_TOGGLE
ACTION_SHOW_STATUSBAR_SECONDARY_TOGGLE
ACTION_SMART_ATTACH
ACTION_SNAPSHOT_LOAD
ACTION_SNAPSHOT_QUICKLOAD
ACTION_SNAPSHOT_QUICKSAVE
ACTION_SNAPSHOT_SAVE
ACTION_SPEED_CPU_10
ACTION_SPEED_CPU_25
ACTION_SPEED_CPU_50
ACTION_SPEED_CPU_100
ACTION_SPEED_CPU_200
ACTION_SPEED_CPU_CUSTOM
ACTION_SPEED_FPS_50
ACTION_SPEED_FPS_60
ACTION_SPEED_FPS_CUSTOM
ACTION_SPEED_FPS_REAL
ACTION_SWAP_CONTROLPORT_TOGGLE
ACTION_TAPE_ATTACH_1
ACTION_TAPE_ATTACH_2
ACTION_TAPE_CREATE_1
ACTION_TAPE_CREATE_2
ACTION_TAPE_DETACH_1
ACTION_TAPE_DETACH_2
ACTION_TAPE_FFWD_1
ACTION_TAPE_FFWD_2
ACTION_TAPE_PLAY_1
ACTION_TAPE_PLAY_2
ACTION_TAPE_RECORD_1
ACTION_TAPE_RECORD_2
ACTION_TAPE_RESET_1
ACTION_TAPE_RESET_2
ACTION_TAPE_RESET_COUNTER_1
ACTION_TAPE_RESET_COUNTER_2
ACTION_TAPE_REWIND_1
ACTION_TAPE_REWIND_2
ACTION_TAPE_STOP_1
ACTION_TAPE_STOP_2
ACTION_WARP_MODE_TOGGLE
ACTION_PSID_LOAD
ACTION_PSID_OVERRIDE_TOGGLE
ACTION_PSID_SUBTUNE_1
ACTION_PSID_SUBTUNE_2
ACTION_PSID_SUBTUNE_3
ACTION_PSID_SUBTUNE_4
ACTION_PSID_SUBTUNE_5
ACTION_PSID_SUBTUNE_6
ACTION_PSID_SUBTUNE_7
ACTION_PSID_SUBTUNE_8
ACTION_PSID_SUBTUNE_9
ACTION_PSID_SUBTUNE_10
ACTION_PSID_SUBTUNE_11
ACTION_PSID_SUBTUNE_12
ACTION_PSID_SUBTUNE_13
ACTION_PSID_SUBTUNE_14
ACTION_PSID_SUBTUNE_15
ACTION_PSID_SUBTUNE_16
ACTION_PSID_SUBTUNE_17
ACTION_PSID_SUBTUNE_18
ACTION_PSID_SUBTUNE_19
ACTION_PSID_SUBTUNE_20
ACTION_PSID_SUBTUNE_21
ACTION_PSID_SUBTUNE_22
ACTION_PSID_SUBTUNE_23
ACTION_PSID_SUBTUNE_24
ACTION_PSID_SUBTUNE_25
ACTION_PSID_SUBTUNE_26
ACTION_PSID_SUBTUNE_27
ACTION_PSID_SUBTUNE_28
ACTION_PSID_SUBTUNE_29
ACTION_PSID_SUBTUNE_30
ACTION_PSID_SUBTUNE_DEFAULT
ACTION_PSID_SUBTUNE_NEXT
ACTION_PSID_SUBTUNE_PREVIOUS
ACTION_PSID_PLAY
ACTION_PSID_PAUSE
ACTION_PSID_STOP
ACTION_PSID_FFWD
ACTION_PSID_LOOP_TOGGLE
ACTION_PSID_PLAYLIST_FIRST
ACTION_PSID_PLAYLIST_PREVIOUS
ACTION_PSID_PLAYLIST_NEXT
ACTION_PSID_PLAYLIST_LAST
ACTION_PSID_PLAYLIST_ADD
ACTION_PSID_PLAYLIST_LOAD
ACTION_PSID_PLAYLIST_SAVE
ACTION_PSID_PLAYLIST_CLEAR
ACTION_DIAGNOSTIC_PIN_TOGGLE
Todo:
VSID playlist controls?
ACTION_PRINTER_FORMFEED_4
ACTION_PRINTER_FORMFEED_5
ACTION_PRINTER_FORMFEED_6
ACTION_PRINTER_FORMFEED_USERPORT
ACTION_VIRTUAL_KEYBOARD
ACTION_BORDER_MODE_NORMAL
ACTION_BORDER_MODE_FULL
ACTION_BORDER_MODE_DEBUG
ACTION_BORDER_MODE_NONE
ACTION_SCPU_JIFFY_SWITCH_TOGGLE
ACTION_SCPU_SPEED_SWITCH_TOGGLE
ACTION_ID_COUNT
number of action IDs
Function Documentation
ui_action_def()
bool ui_action_def (int action, const char * hotkey)
Todo:
implement the following:
ui_action_finish()
void ui_action_finish (int action)
Mark a UI action as finished.
For actions that are blocking (ie dialogs) we need to notify the action handling system the action has finished and can be triggered again.
Parameters
[in] action_id
Referenced by about_destroy_callback(), cart_detach_action(), clear_playlist_callback(), confirm_detach_callback(), confirm_exit_callback(), fliplist_load_response(), fliplist_save_response(), fps_custom_callback(), help_manual_action(), load_snapshot_filename_callback(), on_destroy(), on_dialog_destroy(), on_response(), on_settings_dialog_destroy(), on_settings_save_to_filename(), playlist_load_callback(), playlist_save_dialog_callback(), quit_action(), restore_default_callback(), save_snapshot_dialog(), settings_load_action(), settings_load_filename_callback(), settings_save_action(), and speed_cpu_custom_callback().
ui_action_get_desc()
const char * ui_action_get_desc (int action)
Get description of an action.
Looks up the description for action.
Parameters
[in] action UI action ID
Returns
description or NULL when action not found
ui_action_get_hotkey_label()
char * ui_action_get_hotkey_label (int action)
Get hotkey label for action ID.
Parameters
[in] action UI action ID
Returns
label for hotkey, free with lib_free()
ui_action_get_id()
int ui_action_get_id (const char * name)
Action info getters.
Action info getters.
Get the action name as used by the vhk files.
Parameters
[in] name action name
Returns
ID or -1 when not found
Referenced by vhk_parser_handle_mapping().
ui_action_get_info_list()
ui_action_info_t * ui_action_get_info_list (void)
Get list of actions.
Returns
list of (id, name, desc) tuples for UI actions
Note
The returned list is allocated with lib_malloc() and should be freed after use with lib_free(), the members of each element should not be freed.
Referenced by create_hotkeys_model().
ui_action_get_name()
const char * ui_action_get_name (int action)
Get action name by ID.
Parameters
[in] action UI action ID
Returns
action name or NULL when not found
Note
Also returns NULL for NONE and INVALID
Referenced by dialog_accept_handler(), on_menu_item_toggled(), on_response(), push_button_callback(), speed_cpu_custom_action(), speed_fps_custom_action(), toggle_button_callback(), ui_action_finish(), ui_action_trigger(), ui_actions_register(), ui_hotkeys_arch_remove_by_map(), ui_hotkeys_remove_all(), ui_hotkeys_save_as(), and vhk_parser_do_undef().
ui_action_id_drive_attach()
int ui_action_id_drive_attach (int unit, int drive)
Get drive-attach action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by on_destroy(), on_disk_attach(), and ui_do_drive_popup().
ui_action_id_drive_detach()
int ui_action_id_drive_detach (int unit, int drive)
Get drive-detach action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by on_disk_detach(), and ui_do_drive_popup().
ui_action_id_drive_reset()
int ui_action_id_drive_reset (int unit)
Get reset-drive action ID for unit.
Parameters
[in] unit unit number (8-11)
Returns
action ID or ACTION_NONE for invalud unit
Referenced by ui_do_drive_popup().
ui_action_id_drive_reset_config()
int ui_action_id_drive_reset_config (int unit)
Get reset-drive-config action ID for unit.
Parameters
[in] unit unit number (8-11)
Returns
action ID or ACTION_NONE for invalud unit
ui_action_id_drive_reset_install()
int ui_action_id_drive_reset_install (int unit)
Get reset-drive-install action ID for unit.
Parameters
[in] unit unit number (8-11)
Returns
action ID or ACTION_NONE for invalud unit
ui_action_id_fliplist_add()
int ui_action_id_fliplist_add (int unit, int drive)
Get action IDs for drive actions.
Get action IDs for drive actions.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by ui_do_drive_popup().
ui_action_id_fliplist_clear()
int ui_action_id_fliplist_clear (int unit, int drive)
Get fliplist-clear action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by ui_do_drive_popup().
ui_action_id_fliplist_load()
int ui_action_id_fliplist_load (int unit, int drive)
Get fliplist-load action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by fliplist_load_response().
ui_action_id_fliplist_next()
int ui_action_id_fliplist_next (int unit, int drive)
Get fliplist-next action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by ui_populate_fliplist_menu().
ui_action_id_fliplist_previous()
int ui_action_id_fliplist_previous (int unit, int drive)
Get fliplist-previous action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by ui_populate_fliplist_menu().
ui_action_id_fliplist_remove()
int ui_action_id_fliplist_remove (int unit, int drive)
Get fliplist-remove action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
ui_action_id_fliplist_save()
int ui_action_id_fliplist_save (int unit, int drive)
Get fliplist-save action ID for unit and drive.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
action ID or ACTION_NONE for invalid unit or drive
Referenced by fliplist_save_response().
ui_action_is_valid()
bool ui_action_is_valid (int action)
Determine if action is valid for the current machine.
Parameters
[in] action UI action ID
Returns
true when valid for current machine
Referenced by actions_joystick_setup_ui(), and vhk_parser_handle_mapping().
ui_action_map_clear_hotkey()
void ui_action_map_clear_hotkey (ui_action_map_t * map)
Clear hotkey.
Set the VICE and arch keysyms and modifier masks to 0 in map.
Parameters
[in] map UI action map
Referenced by dialog_accept_handler(), ui_action_map_clear_hotkey_by_action(), ui_action_map_clear_hotkey_by_hotkey(), ui_hotkeys_remove_all(), ui_hotkeys_remove_by_map(), and vhk_parser_do_undef().
ui_action_map_clear_hotkey_by_action()
void ui_action_map_clear_hotkey_by_action (int action)
Clear hotkey.
Set VICE and arch keysyms and modifier masks to 0.
Parameters
[in] action UI action ID
ui_action_map_clear_hotkey_by_hotkey()
void ui_action_map_clear_hotkey_by_hotkey (uint32_t vice_keysym, uint32_t vice_modmask)
Clear hotkey.
Set VICE and arch keysyms and modifier masks to 0.
Parameters
[in] vice_keysym VICE keysym
[in] vice_modmask VICE modifier mask
ui_action_map_get()
ui_action_map_t * ui_action_map_get (int action)
Get UI action map by UI action ID.
Parameters
[in] action UI action ID
Returns
UI action map or NULL when action is invalid
Referenced by create_hotkeys_model(), dialog_accept_handler(), ui_action_get_hotkey_label(), ui_action_map_clear_hotkey_by_action(), ui_action_map_set_hotkey(), ui_hotkeys_arch_shutdown(), ui_hotkeys_remove_all(), ui_hotkeys_remove_by_action(), ui_hotkeys_save_as(), ui_hotkeys_update_by_action(), ui_menu_add(), vhk_gtk_get_accel_label_by_action(), vhk_gtk_get_menu_item_by_action_for_window(), vhk_gtk_set_check_item_blocked_by_action(), vhk_gtk_set_check_item_blocked_by_action_for_window(), and vhk_gtk_set_menu_item_accel_label().
ui_action_map_get_by_arch_hotkey()
ui_action_map_t * ui_action_map_get_by_arch_hotkey (uint32_t arch_keysym, uint32_t arch_modmask)
Get UI action map by arch hotkey.
Parameters
[in] arch_keysym arch keysym
[in] arch_modmask arch modifier mask
Returns
UI action map or NULL when not found
Referenced by dialog_accept_handler().
ui_action_map_get_by_hotkey()
ui_action_map_t * ui_action_map_get_by_hotkey (uint32_t vice_keysym, uint32_t vice_modmask)
Get UI action map by VICE hotkey.
Parameters
[in] vice_keysym VICE keysym
[in] vice_modmask VICE modifier mask
Returns
UI action map or NULL when not found
Referenced by ui_action_map_clear_hotkey_by_hotkey(), ui_action_map_get_by_arch_hotkey(), and vhk_parser_do_undef().
ui_action_map_get_hotkey_label()
char * ui_action_map_get_hotkey_label (ui_action_map_t * map)
Get hotkey label for action map.
Parameters
[in] map UI action map
Returns
label for hotkey, free with lib_free()
Referenced by ui_action_get_hotkey_label().
ui_action_map_set_hotkey()
ui_action_map_t * ui_action_map_set_hotkey (int action, uint32_t vice_keysym, uint32_t vice_modmask, uint32_t arch_keysym, uint32_t arch_modmask)
Set hotkey for action.
Parameters
[in] action action ID
[in] vice_keysym VICE keysym
[in] vice_modmask VICE modifier mask
[in] arch_keysym arch keysym
[in] arch_modmask arch modifier mask
Returns
pointer to map or NULL on error
Referenced by vhk_parser_handle_mapping().
ui_action_map_set_hotkey_by_map()
void ui_action_map_set_hotkey_by_map (ui_action_map_t * map, uint32_t vice_keysym, uint32_t vice_modmask, uint32_t arch_keysym, uint32_t arch_modmask)
Set hotkey for action.
Parameters
[in] map UI action map
[in] vice_keysym VICE keysym
[in] vice_modmask VICE modifier mask
[in] arch_keysym arch keysym
[in] arch_modmask arch modifier mask
ui_action_redef()
bool ui_action_redef (int action, const char * hotkey)
ui_action_trigger()
void ui_action_trigger (int action)
Trigger a UI action.
Calls the action dispatch handler if conditions are met.
If an action is marked as a dialog then it will only be triggered when there is no other dialog active. If an action is marked as blocking i will only be triggered when it isn't marked as busy.
Parameters
[in] action action ID
See also
src/arch/shared/uiactions.h for IDs
Referenced by arch_ui_activate(), handle_accelerator(), on_action_item_activate(), on_clicked(), on_delete_event(), on_disk_attach(), on_disk_detach(), on_menu_item_activate(), on_menu_item_toggled(), on_swap_joysticks_toggled(), pause_led_callback(), push_button_callback(), rendering_area_event_handler(), restore_display_action(), toggle_button_callback(), trigger_ui_action(), vsid_control_widget_next_tune(), vsid_tune_info_widget_update(), and warp_led_callback().
ui_action_undef()
bool ui_action_undef (int action)
ui_actions_init()
void ui_actions_init (void)
Main API.
Main API.
Note
This needs is called from the shared init code, the UI needs to subsequently call ui_actions_set_dispatch() to register the function that actually executes the action handler function
Referenced by main_program().
ui_actions_register()
void ui_actions_register (const ui_action_map_t * mappings)
Register UI action implementations.
Add action handlers in mappings to the runtime action mappings.
Parameters
[in] mappings list of action IDs mapped to action handlers
Referenced by actions_cartridge_register(), actions_clipboard_register(), actions_datasette_register(), actions_display_register(), actions_drive_register(), actions_help_register(), actions_hotkeys_register(), actions_joystick_register(), actions_machine_register(), actions_media_register(), actions_printer_register(), actions_settings_register(), actions_snapshot_register(), actions_speed_register(), and actions_vsid_register().
ui_actions_set_dispatch()
void ui_actions_set_dispatch (void(*)(ui_action_map_t *) dispatch)
Set UI-specific function to dispatch UI action handlers.
Parameters
[in] dispatch function to call with an action map as its argument to have the UI actually invoke the handler on the proper thread
Note
Installing a dispatch handler is optional, when not installed an action's handler is called directly by ui_action_trigger().
Referenced by ui_init_finalize().
ui_actions_shutdown()
void ui_actions_shutdown (void)
Free all resources used by the UI actions system.
Referenced by machine_shutdown().