vsid: arch/gtk3/widgets/base/widgethelpers.c File Reference
widgethelpers.c File Reference
Helpers for creating Gtk3 widgets.
#include "vice.h"
#include <gtk/gtk.h>
#include <string.h>
#include <stdbool.h>
#include "lib.h"
#include "resources.h"
#include "vice_gtk3_settings.h"
#include "debug_gtk3.h"
#include "widgethelpers.h"
Functions
int vice_gtk3_radiogroup_get_list_index (const vice_gtk3_radiogroup_entry_t *list, int value)
Get index of value in list.
void vice_gtk3_radiogroup_set_index (GtkWidget *grid, int index)
Set a radio button to active in a GktGrid.
GtkWidget * vice_gtk3_create_indented_label (const char *text)
Create a left-aligned, 16 units indented label.
GtkWidget * vice_gtk3_grid_new_spaced (int column_spacing, int row_spacing)
Create a new GtkGrid, setting column and row spacing.
GtkWidget * vice_gtk3_grid_new_spaced_with_label (int column_spacing, int row_spacing, const char *label, int span)
Create a new GtkGrid with label, setting column and row spacing.
void vice_gtk3_grid_set_title_margin (GtkWidget *grid, int margin)
Set 'margin-bottom' property of the title of a grid with title.
void vice_gtk3_grid_set_margins (GtkWidget *grid, gint top, gint bottom, gint start, gint end)
Set margin on grid.
Detailed Description
Helpers for creating Gtk3 widgets.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
This file is supposed to contain some helper functions for boiler plate code, such as creating layout widgets, creating lists of radio or check boxes, etc.
Todo:
turn the margin/padding values into defines and move into a file like uidefs.h (partially done, see vice_gtk3_settings.h)
Todo:
rename/replace functions (partially done)
Function Documentation
vice_gtk3_create_indented_label()
GtkWidget * vice_gtk3_create_indented_label (const char * text)
Create a left-aligned, 16 units indented label.
pretty useless, should be removed
XXX: This function is of little use an should probably be removed in favour of something a little more flexible.
Parameters
[in] text label text
Returns
GtkLabel
vice_gtk3_grid_new_spaced()
GtkWidget * vice_gtk3_grid_new_spaced (int column_spacing, int row_spacing)
Create a new GtkGrid, setting column and row spacing.
new stuff
Parameters
[in] column_spacing column spacing (< 0 to use default)
[in] row_spacing row spacing (< 0 to use default)
Returns
GtkGrid
Referenced by create_content_widget(), create_driver_info_widget(), create_extra_widget(), create_inner_grid(), create_p00_widget(), create_printer_widget(), create_radio_group(), create_screenshot_param_widget(), create_stack_child_widget(), create_video_widget(), drive_fsdevice_widget_create(), drive_no_widget_create(), drive_sound_widget_create(), drive_unit_widget_create(), ffmpeg_widget_create(), hvsc_stil_widget_create(), kbd_debug_widget_create(), mixer_widget_create(), settings_autofire_widget_create(), settings_c128functionrom_widget_create(), settings_c64_memhacks_widget_create(), settings_default_cart_widget_create(), settings_dqbb_widget_create(), settings_ethernet_widget_create(), settings_fsdevice_widget_create(), settings_gmod2c128_widget_create(), settings_host_display_widget_create(), settings_hvsc_widget_create(), settings_ieee488_widget_create(), settings_joystick_widget_create(), settings_misc_widget_create(), settings_mixer_widget_create(), settings_mmcr_widget_create(), settings_petdww_widget_create(), settings_retroreplay_widget_create(), settings_rs232_widget_create(), settings_speed_widget_create(), sid_sound_widget_create(), statusbar_recording_widget_create(), ui_settings_inital_widget(), ui_statusbar_create(), userport_rsinterface_widget_create(), vice_gtk3_grid_new_spaced_with_label(), vice_gtk3_resource_browser_new(), vice_gtk3_resource_browser_save_new(), vsid_control_widget_create(), vsid_main_widget_create(), vsid_playlist_controls_create(), vsid_playlist_widget_create(), and vsid_tune_info_widget_create().
vice_gtk3_grid_new_spaced_with_label()
GtkWidget * vice_gtk3_grid_new_spaced_with_label (int column_spacing, int row_spacing, const char * label, int span)
Create a new GtkGrid with label, setting column and row spacing.
Parameters
[in] column_spacing column spacing (< 0 to use default)
[in] row_spacing row spacing (< 0 to use default)
[in] label label text
[in] span number of columns for the label to span
Returns
GtkGrid
Referenced by cbm2_hardwired_switches_widget_create(), cbm2_memory_size_widget_create(), cbm2_ram_mapping_widget_create(), cia_model_widget_create(), create_acia_widget(), create_cart_image_widget(), create_collision_widget(), create_eeprom_image_widget(), create_memhack_widget(), create_printer_text_devices_widget(), create_rom_widget(), create_rs232_devices_widget(), create_screenshot_widget(), create_sid_address_widgets(), create_sound_widget(), create_userport_widget(), create_video_widget(), crt_preview_widget_create(), drive_model_widget_create(), drive_ram_widget_create(), drive_rpm_widget_create(), kernal_revision_widget_create(), memory_hacks_device_widget_create(), pet_io_size_widget_create(), pet_keyboard_type_widget_create(), pet_misc_widget_create(), pet_ram9_widget_create(), pet_ram_size_widget_create(), pet_rama_widget_create(), pet_video_size_widget_create(), plus4_memory_expansion_widget_create(), plus4_memory_size_widget_create(), printer_driver_widget_create(), printer_emulation_type_widget_create(), printer_output_device_widget_create(), printer_output_mode_widget_create(), settings_ramreset_widget_create(), sound_sync_mode_widget_create(), speed_widget_create(), vic20_memory_expansion_widget_create(), and video_palette_widget_create().
vice_gtk3_grid_set_margins()
void vice_gtk3_grid_set_margins (GtkWidget * grid, gint top, gint bottom, gint start, gint end)
Set margin on grid.
Set margins on a GtkGrid. passing a value of <0 means skipping that property.
Parameters
[in,out] grid GtkGrid instance
[in] top top margin
[in] bottom bottom margin
[in] start start (left) margin
[in] end end (right) margin
vice_gtk3_grid_set_title_margin()
void vice_gtk3_grid_set_title_margin (GtkWidget * grid, int margin)
Set 'margin-bottom' property of the title of a grid with title.
Since we've switched to using a lot of grids with 0 row spacing, it's often desired to have a little space between a grid's title and its content.
Parameters
[in] grid GtkGrid created with vice_gtk3_grid_new_spaced_with_label()
[in] margin bottom-margin property value
Referenced by cbm2_hardwired_switches_widget_create(), cbm2_memory_size_widget_create(), cbm2_ram_mapping_widget_create(), cia_model_widget_create(), create_collision_widget(), create_userport_widget(), drive_ram_widget_create(), kernal_revision_widget_create(), pet_keyboard_type_widget_create(), pet_misc_widget_create(), pet_ram_size_widget_create(), pet_video_size_widget_create(), plus4_memory_expansion_widget_create(), plus4_memory_size_widget_create(), printer_driver_widget_create(), printer_emulation_type_widget_create(), printer_output_device_widget_create(), printer_output_mode_widget_create(), and video_palette_widget_create().
vice_gtk3_radiogroup_get_list_index()
int vice_gtk3_radiogroup_get_list_index (const vice_gtk3_radiogroup_entry_t * list, int value)
Get index of value in list.
Get the index in list for value. This function is required for custom radiogroups that add 'unknown' options or something similar.
Parameters
[in] list radio button group array
[in] value value to find in list
Returns
index of value or -1 when not found
Referenced by get_model_index(), get_revision_index(), and vdc_model_widget_update().
vice_gtk3_radiogroup_set_index()
void vice_gtk3_radiogroup_set_index (GtkWidget * grid, int index)
Set a radio button to active in a GktGrid.
This function only checks for radio buttons in the first row of the grid, so it works fine with widgets created through uihelpers_uihelpers_create_int_radiogroup_with_label(), but not much else. So it might need some refactoring
Parameters
[in] grid GtkGrid containing radio buttons
[in] index index of the radio button (the actual index of the radio button, other widgets are skipped)
Referenced by sid_model_widget_update().