vsid: vicii/vicii-draw.c File Reference
vicii-draw.c File Reference
#include "vice.h"
#include <string.h>
#include "raster-cache-fill.h"
#include "raster-cache-fill-1fff.h"
#include "raster-cache-fill-39ff.h"
#include "raster-cache-text-ext.h"
#include "raster-cache-text-std.h"
#include "raster-cache.h"
#include "raster-modes.h"
#include "raster.h"
#include "types.h"
#include "vicii-draw.h"
#include "viciitypes.h"
#include "viewport.h"
Macros
#define GFX_MSK_LEFTBORDER_SIZE
#define GFX_PTR()
Pointer to the start of the graphics area on the frame buffer.
#define ALIGN_DRAW_FUNC(name, xs, xe, gfx_msk_ptr)
#define DRAW_STD_TEXT_BYTE(p, b, f)
#define DRAW_MC_BYTE(p, b, f1, f2, f3)
Functions
static void draw_std_background (unsigned int start_pixel, unsigned int end_pixel)
These functions draw the background from ‘start_pixel’ to ‘end_pixel’.
static void draw_idle_std_background (unsigned int start_pixel, unsigned int end_pixel)
static int get_std_text (raster_cache_t *cache, unsigned int *xs, unsigned int *xe, int rr)
Standard text mode.
static void _draw_std_text (uint8_t *p, unsigned int xs, unsigned int xe, uint8_t *gfx_msk_ptr)
static void _draw_std_text_cached (uint8_t *p, unsigned int xs, unsigned int xe, raster_cache_t *cache)
static void draw_std_text_cached (raster_cache_t *cache, unsigned int xs, unsigned int xe)
static void draw_std_text (void)
static void draw_std_text_foreground (unsigned int start_char, unsigned int end_char)
static int get_hires_bitmap (raster_cache_t *cache, unsigned int *xs, unsigned int *xe, int rr)
Hires Bitmap mode.
static void _draw_hires_bitmap (uint8_t *p, unsigned int xs, unsigned int xe, uint8_t *gfx_msk_ptr)
static void _draw_hires_bitmap_cached (uint8_t *p, unsigned int xs, unsigned int xe, raster_cache_t *cache)
static void draw_hires_bitmap (void)
static void draw_hires_bitmap_cached (raster_cache_t *cache, unsigned int xs, unsigned int xe)
static void _draw_hires_bitmap_foreground (uint8_t *p, unsigned int xs, unsigned int xe, uint8_t *gfx_msk_ptr)
static void draw_hires_bitmap_foreground (unsigned int start_char, unsigned int end_char)
static int get_mc_text (raster_cache_t *cache, unsigned int *xs, unsigned int *xe, int rr)
Multicolor text mode.
static void _draw_mc_text (uint8_t *p, unsigned int xs, unsigned int xe, uint8_t *gfx_msk_ptr)
static void _draw_mc_text_cached (uint8_t *p, unsigned int xs, unsigned int xe, raster_cache_t *cache)
static void draw_mc_text (void)
static void draw_mc_text_cached (raster_cache_t *cache, unsigned int xs, unsigned int xe)
static void draw_mc_text_foreground (unsigned int start_char, unsigned int end_char)
static int get_mc_bitmap (raster_cache_t *cache, unsigned int *xs, unsigned int *xe, int rr)
Multicolor Bitmap Mode.
static void _draw_mc_bitmap (uint8_t *p, unsigned int xs, unsigned int xe, uint8_t *gfx_msk_ptr)
static void _draw_mc_bitmap_cached (uint8_t *p, unsigned int xs, unsigned int xe, raster_cache_t *cache)
static void draw_mc_bitmap (void)
static void draw_mc_bitmap_cached (raster_cache_t *cache, unsigned int xs, unsigned int xe)
static void draw_mc_bitmap_foreground (unsigned int start_char, unsigned int end_char)
static int get_ext_text (raster_cache_t *cache, unsigned int *xs, unsigned int *xe, int rr)
Extended Text Mode.
static void _draw_ext_text (uint8_t *p, unsigned int xs, unsigned int xe, uint8_t *gfx_msk_ptr)
static void _draw_ext_text_cached (uint8_t *p, unsigned int xs, unsigned int xe, raster_cache_t *cache)
static void draw_ext_text (void)
static void draw_ext_text_cached (raster_cache_t *cache, unsigned int xs, unsigned int xe)
static void draw_ext_text_foreground (unsigned int start_char, unsigned int end_char)
static int get_illegal_text (raster_cache_t *cache, unsigned int *xs, unsigned int *xe, int rr)
Illegal text mode.
static void _draw_illegal_text (uint8_t *p, unsigned int xs, unsigned int xe, uint8_t *gfx_msk_ptr)
static void _draw_illegal_text_cached (uint8_t *p, unsigned int xs, unsigned int xe, raster_cache_t *cache)
static void draw_illegal_text (void)
static void draw_illegal_text_cached (raster_cache_t *cache, unsigned int xs, unsigned int xe)
static void draw_illegal_text_foreground (unsigned int start_char, unsigned int end_char)
static int get_illegal_bitmap_mode1 (raster_cache_t *cache, unsigned int *xs, unsigned int *xe, int rr)
Illegal bitmap mode 1.
static void _draw_illegal_bitmap_mode1 (uint8_t *p, unsigned int xs, unsigned int xe, uint8_t *gfx_msk_ptr)
static void _draw_illegal_bitmap_mode1_cached (uint8_t *p, unsigned int xs, unsigned int xe, raster_cache_t *cache)
static void draw_illegal_bitmap_mode1 (void)
static void draw_illegal_bitmap_mode1_cached (raster_cache_t *cache, unsigned int xs, unsigned int xe)
static void draw_illegal_bitmap_mode1_foreground (unsigned int start_char, unsigned int end_char)
static int get_illegal_bitmap_mode2 (raster_cache_t *cache, unsigned int *xs, unsigned int *xe, int rr)
Illegal bitmap mode 2.
static void _draw_illegal_bitmap_mode2 (uint8_t *p, unsigned int xs, unsigned int xe, uint8_t *gfx_msk_ptr)
static void _draw_illegal_bitmap_mode2_cached (uint8_t *p, unsigned int xs, unsigned int xe, raster_cache_t *cache)
static void draw_illegal_bitmap_mode2 (void)
static void draw_illegal_bitmap_mode2_cached (raster_cache_t *cache, unsigned int xs, unsigned int xe)
static void draw_illegal_bitmap_mode2_foreground (unsigned int start_char, unsigned int end_char)
static int get_idle (raster_cache_t *cache, unsigned int *xs, unsigned int *xe, int rr)
Idle state.
static void _draw_idle (uint8_t *p, unsigned int xs, unsigned int xe, uint8_t *gfx_msk_ptr)
static void draw_idle (void)
static void draw_idle_cached (raster_cache_t *cache, unsigned int xs, unsigned int xe)
static void draw_idle_foreground (unsigned int start_char, unsigned int end_char)
static void setup_modes (void)
static void init_drawing_tables (void)
Initialize the drawing tables.
void vicii_draw_init (void)
Variables
static uint32_t hr_table [16 *16 *16]
foreground(4) | background(4) | nibble(4) -> 4 pixels.
static uint8_t mc_table [3 *256]
mc flag(1) | idx(2) | byte(8) -> index into double-pixel table.
static uint8_t mcmsktable [256]
static uint32_t _aligned_line_buffer [320/2+1]
static uint8_t *const aligned_line_buffer = (uint8_t *)_aligned_line_buffer
Macro Definition Documentation
ALIGN_DRAW_FUNC
#define ALIGN_DRAW_FUNC (name, xs, xe, gfx_msk_ptr)
Value:
    do {                                                      \
        name(aligned_line_buffer, (xs), (xe), (gfx_msk_ptr)); \
        memcpy(GFX_PTR() + (xs) * 8,                          \
               aligned_line_buffer + (xs) * 8,                \
               ((xe) - (xs) + 1) * 8);                        \
    } while (0)
DRAW_MC_BYTE
#define DRAW_MC_BYTE (p, b, f1, f2, f3)
Value:
    do {                                        \
        if ((b) & 0x80) {                       \
            if ((b) & 0x40) {                   \
                *(p) = *((p) + 1) = (f3);       \
            } else {                            \
                *(p) = *((p) + 1) = (f2);       \
            }                                   \
        } else if ((b) & 0x40) {                \
            *(p) = *((p) + 1) = (f1);           \
        }                                       \
                                                \
        if ((b) & 0x20) {                       \
            if ((b) & 0x10) {                   \
                *((p) + 2) = *((p) + 3) = (f3); \
            } else {                            \
                *((p) + 2) = *((p) + 3) = (f2); \
            }                                   \
        } else if ((b) & 0x10) {                \
            *((p) + 2) = *((p) + 3) = (f1);     \
        }                                       \
                                                \
        if ((b) & 0x08) {                       \
            if ((b) & 0x04) {                   \
                *((p) + 4) = *((p) + 5) = (f3); \
            } else {                            \
                *((p) + 4) = *((p) + 5) = (f2); \
            }                                   \
        } else if ((b) & 0x04) {                \
            *((p) + 4) = *((p) + 5) = (f1);     \
        }                                       \
                                                \
        if ((b) & 0x02) {                       \
            if ((b) & 0x01) {                   \
                *((p) + 6) = *((p) + 7) = (f3); \
            } else {                            \
                *((p) + 6) = *((p) + 7) = (f2); \
            }                                   \
        } else if ((b) & 0x01) {                \
            *((p) + 6) = *((p) + 7) = (f1);     \
        }                                       \
    } while (0)
Todo:
FIXME: aligned/unaligned versions.
DRAW_STD_TEXT_BYTE
#define DRAW_STD_TEXT_BYTE (p, b, f)
Value:
    do {                            \
        if ((b) & 0x80) {           \
            *(p) = (f);             \
        }                           \
        if ((b) & 0x40) {           \
            *((p) + 1) = (f);       \
        }                           \
        if ((b) & 0x20) {           \
            *((p) + 2) = (f);       \
        }                           \
        if ((b) & 0x10) {           \
            *((p) + 3) = (f);       \
        }                           \
        if ((b) & 0x08) {           \
            *((p) + 4) = (f);       \
        }                           \
        if ((b) & 0x04) {           \
            *((p) + 5) = (f);       \
        }                           \
        if ((b) & 0x02) {           \
            *((p) + 6) = (f);       \
        }                           \
        if ((b) & 0x01) {           \
            *((p) + 7) = (f);       \
        }                           \
    } while (0)
GFX_MSK_LEFTBORDER_SIZE
#define GFX_MSK_LEFTBORDER_SIZE
Value:
                                  ((VICII_MAX_SPRITE_WIDTH - VICII_RASTER_X(0) \
                                  + vicii.screen_leftborderwidth ) / 8 + 1)
GFX_PTR
#define GFX_PTR ()
Value:
    (vicii.raster.draw_buffer_ptr \
     + (vicii.screen_leftborderwidth + vicii.raster.xsmooth))
Pointer to the start of the graphics area on the frame buffer.
Function Documentation
_draw_ext_text()
static void _draw_ext_text (uint8_t * p, unsigned int xs, unsigned int xe, uint8_t * gfx_msk_ptr) inline static
< expanded sprite in bug area
Referenced by draw_ext_text().
_draw_ext_text_cached()
static void _draw_ext_text_cached (uint8_t * p, unsigned int xs, unsigned int xe, raster_cache_t * cache) inline static
< expanded sprite in bug area
Referenced by draw_ext_text_cached().
_draw_hires_bitmap()
static void _draw_hires_bitmap (uint8_t * p, unsigned int xs, unsigned int xe, uint8_t * gfx_msk_ptr) inline static
< expanded sprite in bug area
Referenced by draw_hires_bitmap().
_draw_hires_bitmap_cached()
static void _draw_hires_bitmap_cached (uint8_t * p, unsigned int xs, unsigned int xe, raster_cache_t * cache) inline static
< expanded sprite in bug area
Referenced by draw_hires_bitmap_cached().
_draw_hires_bitmap_foreground()
static void _draw_hires_bitmap_foreground (uint8_t * p, unsigned int xs, unsigned int xe, uint8_t * gfx_msk_ptr) inline static
< expanded sprite in bug area
Referenced by draw_hires_bitmap_foreground().
_draw_idle()
static void _draw_idle (uint8_t * p, unsigned int xs, unsigned int xe, uint8_t * gfx_msk_ptr) inline static
< expanded sprite in bug area
Todo:
FIXME: Could be optimized
Referenced by draw_idle(), and draw_idle_cached().
_draw_illegal_bitmap_mode1()
static void _draw_illegal_bitmap_mode1 (uint8_t * p, unsigned int xs, unsigned int xe, uint8_t * gfx_msk_ptr) inline static
< expanded sprite in bug area
Referenced by draw_illegal_bitmap_mode1(), and draw_illegal_bitmap_mode1_foreground().
_draw_illegal_bitmap_mode1_cached()
static void _draw_illegal_bitmap_mode1_cached (uint8_t * p, unsigned int xs, unsigned int xe, raster_cache_t * cache) inline static
< expanded sprite in bug area
Referenced by draw_illegal_bitmap_mode1_cached().
_draw_illegal_bitmap_mode2()
static void _draw_illegal_bitmap_mode2 (uint8_t * p, unsigned int xs, unsigned int xe, uint8_t * gfx_msk_ptr) inline static
< expanded sprite in bug area
Referenced by draw_illegal_bitmap_mode2(), and draw_illegal_bitmap_mode2_foreground().
_draw_illegal_bitmap_mode2_cached()
static void _draw_illegal_bitmap_mode2_cached (uint8_t * p, unsigned int xs, unsigned int xe, raster_cache_t * cache) inline static
< expanded sprite in bug area
Referenced by draw_illegal_bitmap_mode2_cached().
_draw_illegal_text()
static void _draw_illegal_text (uint8_t * p, unsigned int xs, unsigned int xe, uint8_t * gfx_msk_ptr) inline static
< expanded sprite in bug area
Referenced by draw_illegal_text().
_draw_illegal_text_cached()
static void _draw_illegal_text_cached (uint8_t * p, unsigned int xs, unsigned int xe, raster_cache_t * cache) inline static
< expanded sprite in bug area
Referenced by draw_illegal_text_cached().
_draw_mc_bitmap()
static void _draw_mc_bitmap (uint8_t * p, unsigned int xs, unsigned int xe, uint8_t * gfx_msk_ptr) inline static
< expanded sprite in bug area
Referenced by draw_mc_bitmap().
_draw_mc_bitmap_cached()
static void _draw_mc_bitmap_cached (uint8_t * p, unsigned int xs, unsigned int xe, raster_cache_t * cache) inline static
< expanded sprite in bug area
Referenced by draw_mc_bitmap_cached().
_draw_mc_text()
static void _draw_mc_text (uint8_t * p, unsigned int xs, unsigned int xe, uint8_t * gfx_msk_ptr) inline static
< expanded sprite in bug area
Referenced by draw_mc_text().
_draw_mc_text_cached()
static void _draw_mc_text_cached (uint8_t * p, unsigned int xs, unsigned int xe, raster_cache_t * cache) inline static
< expanded sprite in bug area
Referenced by draw_mc_text_cached().
_draw_std_text()
static void _draw_std_text (uint8_t * p, unsigned int xs, unsigned int xe, uint8_t * gfx_msk_ptr) inline static
< expanded sprite in bug area
Referenced by draw_std_text().
_draw_std_text_cached()
static void _draw_std_text_cached (uint8_t * p, unsigned int xs, unsigned int xe, raster_cache_t * cache) inline static
< expanded sprite in bug area
Referenced by draw_std_text_cached().
draw_ext_text()
static void draw_ext_text (void) static
Referenced by setup_modes().
draw_ext_text_cached()
static void draw_ext_text_cached (raster_cache_t * cache, unsigned int xs, unsigned int xe) static
Referenced by setup_modes().
draw_ext_text_foreground()
static void draw_ext_text_foreground (unsigned int start_char, unsigned int end_char) static
< expanded sprite in bug area
Referenced by setup_modes().
draw_hires_bitmap()
static void draw_hires_bitmap (void) static
Referenced by setup_modes().
draw_hires_bitmap_cached()
static void draw_hires_bitmap_cached (raster_cache_t * cache, unsigned int xs, unsigned int xe) static
Referenced by setup_modes().
draw_hires_bitmap_foreground()
static void draw_hires_bitmap_foreground (unsigned int start_char, unsigned int end_char) static
Referenced by setup_modes().
draw_idle()
static void draw_idle (void) static
Referenced by setup_modes().
draw_idle_cached()
static void draw_idle_cached (raster_cache_t * cache, unsigned int xs, unsigned int xe) static
Referenced by setup_modes().
draw_idle_foreground()
static void draw_idle_foreground (unsigned int start_char, unsigned int end_char) static
< expanded sprite in bug area
Referenced by setup_modes().
draw_idle_std_background()
static void draw_idle_std_background (unsigned int start_pixel, unsigned int end_pixel) static
Referenced by setup_modes().
draw_illegal_bitmap_mode1()
static void draw_illegal_bitmap_mode1 (void) static
Referenced by setup_modes().
draw_illegal_bitmap_mode1_cached()
static void draw_illegal_bitmap_mode1_cached (raster_cache_t * cache, unsigned int xs, unsigned int xe) static
Referenced by setup_modes().
draw_illegal_bitmap_mode1_foreground()
static void draw_illegal_bitmap_mode1_foreground (unsigned int start_char, unsigned int end_char) static
Referenced by setup_modes().
draw_illegal_bitmap_mode2()
static void draw_illegal_bitmap_mode2 (void) static
Referenced by setup_modes().
draw_illegal_bitmap_mode2_cached()
static void draw_illegal_bitmap_mode2_cached (raster_cache_t * cache, unsigned int xs, unsigned int xe) static
Referenced by setup_modes().
draw_illegal_bitmap_mode2_foreground()
static void draw_illegal_bitmap_mode2_foreground (unsigned int start_char, unsigned int end_char) static
Referenced by setup_modes().
draw_illegal_text()
static void draw_illegal_text (void) static
Referenced by setup_modes().
draw_illegal_text_cached()
static void draw_illegal_text_cached (raster_cache_t * cache, unsigned int xs, unsigned int xe) static
Referenced by setup_modes().
draw_illegal_text_foreground()
static void draw_illegal_text_foreground (unsigned int start_char, unsigned int end_char) static
< expanded sprite in bug area
Referenced by setup_modes().
draw_mc_bitmap()
static void draw_mc_bitmap (void) static
Referenced by setup_modes().
draw_mc_bitmap_cached()
static void draw_mc_bitmap_cached (raster_cache_t * cache, unsigned int xs, unsigned int xe) static
Referenced by setup_modes().
draw_mc_bitmap_foreground()
static void draw_mc_bitmap_foreground (unsigned int start_char, unsigned int end_char) static
< expanded sprite in bug area
Referenced by setup_modes().
draw_mc_text()
static void draw_mc_text (void) static
Referenced by setup_modes().
draw_mc_text_cached()
static void draw_mc_text_cached (raster_cache_t * cache, unsigned int xs, unsigned int xe) static
Referenced by setup_modes().
draw_mc_text_foreground()
static void draw_mc_text_foreground (unsigned int start_char, unsigned int end_char) static
< expanded sprite in bug area
Referenced by setup_modes().
draw_std_background()
static void draw_std_background (unsigned int start_pixel, unsigned int end_pixel) static
These functions draw the background from ‘start_pixel’ to ‘end_pixel’.
Referenced by setup_modes().
draw_std_text()
static void draw_std_text (void) static
Referenced by setup_modes().
draw_std_text_cached()
static void draw_std_text_cached (raster_cache_t * cache, unsigned int xs, unsigned int xe) static
Referenced by setup_modes().
draw_std_text_foreground()
static void draw_std_text_foreground (unsigned int start_char, unsigned int end_char) static
< expanded sprite in bug area
Referenced by setup_modes().
get_ext_text()
static int get_ext_text (raster_cache_t * cache, unsigned int * xs, unsigned int * xe, int rr) static
Extended Text Mode.
Referenced by setup_modes().
get_hires_bitmap()
static int get_hires_bitmap (raster_cache_t * cache, unsigned int * xs, unsigned int * xe, int rr) static
Hires Bitmap mode.
Referenced by setup_modes().
get_idle()
static int get_idle (raster_cache_t * cache, unsigned int * xs, unsigned int * xe, int rr) static
Idle state.
Referenced by setup_modes().
get_illegal_bitmap_mode1()
static int get_illegal_bitmap_mode1 (raster_cache_t * cache, unsigned int * xs, unsigned int * xe, int rr) static
Illegal bitmap mode 1.
Referenced by setup_modes().
get_illegal_bitmap_mode2()
static int get_illegal_bitmap_mode2 (raster_cache_t * cache, unsigned int * xs, unsigned int * xe, int rr) static
Illegal bitmap mode 2.
Referenced by setup_modes().
get_illegal_text()
static int get_illegal_text (raster_cache_t * cache, unsigned int * xs, unsigned int * xe, int rr) static
Illegal text mode.
Referenced by setup_modes().
get_mc_bitmap()
static int get_mc_bitmap (raster_cache_t * cache, unsigned int * xs, unsigned int * xe, int rr) static
Multicolor Bitmap Mode.
Referenced by setup_modes().
get_mc_text()
static int get_mc_text (raster_cache_t * cache, unsigned int * xs, unsigned int * xe, int rr) static
Multicolor text mode.
Referenced by setup_modes().
get_std_text()
static int get_std_text (raster_cache_t * cache, unsigned int * xs, unsigned int * xe, int rr) static
Standard text mode.
Referenced by setup_modes().
init_drawing_tables()
static void init_drawing_tables (void) static
Initialize the drawing tables.
Referenced by vicii_draw_init().
setup_modes()
static void setup_modes (void) static
Referenced by vicii_draw_init().
vicii_draw_init()
void vicii_draw_init (void)
Referenced by vicii_init().
Variable Documentation
_aligned_line_buffer
uint32_t _aligned_line_buffer[320/2+1] static
aligned_line_buffer
uint8_t* const aligned_line_buffer = (uint8_t *)_aligned_line_buffer static
hr_table
uint32_t hr_table[16 *16 *16] static
foreground(4) | background(4) | nibble(4) -> 4 pixels.
Referenced by _draw_ext_text(), _draw_ext_text_cached(), _draw_hires_bitmap(), _draw_hires_bitmap_cached(), _draw_hires_bitmap_foreground(), _draw_idle(), _draw_mc_text(), _draw_mc_text_cached(), _draw_std_text(), _draw_std_text_cached(), and init_drawing_tables().
mc_table
uint8_t mc_table[3 *256] static
mc flag(1) | idx(2) | byte(8) -> index into double-pixel table.
Referenced by _draw_idle(), _draw_mc_bitmap(), _draw_mc_bitmap_cached(), _draw_mc_text(), _draw_mc_text_cached(), and init_drawing_tables().
mcmsktable
uint8_t mcmsktable[256] static
Referenced by _draw_idle(), _draw_illegal_bitmap_mode2(), _draw_illegal_bitmap_mode2_cached(), _draw_illegal_text(), _draw_illegal_text_cached(), _draw_mc_bitmap(), _draw_mc_bitmap_cached(), _draw_mc_text(), _draw_mc_text_cached(), draw_illegal_text_foreground(), draw_mc_bitmap_foreground(), draw_mc_text_foreground(), and init_drawing_tables().