x128: arch/gtk3/widgets/settings_rs232.c File Reference
settings_rs232.c File Reference
Widget to control various RS232 resources.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdbool.h>
#include "vice_gtk3.h"
#include "lib.h"
#include "machine.h"
#include "resources.h"
#include "userport.h"
#include "userportdevicecheckbutton.h"
#include "userportrsinterfacewidget.h"
#include "settings_rs232.h"
#include "rsuser.h"
#include "acia.h"
Functions
static bool machine_has_acia (void)
Determine if the current machine supports ACIA.
static void on_rsinterface_changed (GtkWidget *widget)
Extra event handler for the userport RS-232 interface type changes.
static GtkWidget * create_indented_label (const char *text)
Helper: create left-aligned, 16 px indented label.
static GtkWidget * create_acia_enable_widget (void)
{{{ ACIA widgets
static GtkWidget * create_acia_base_widget (void)
Create a group of radio buttons to set the ACIA chip address.
static GtkWidget * create_acia_irq_widget (void)
Create a group of radio buttons to set the ACIA IRQ source.
static GtkWidget * create_acia_mode_widget (void)
Create a group of radio buttons to set the RS232 mode.
static GtkWidget * create_acia_widget (void)
Create RS232 ACIA settings widget.
static GtkWidget * create_serial_baud_widget (const char *resource)
}}}
static GtkWidget * create_userport_widget (void)
Create user-port RS232 emulation settings widget.
static GtkWidget * create_rs232_devices_widget (void)
Create RS232 devices widget.
GtkWidget * settings_rs232_widget_create (GtkWidget *parent)
Create RS232 settings widget.
Variables
static const vice_gtk3_combo_entry_int_t acia_devices []
List of ACIA devices.
static const vice_gtk3_radiogroup_entry_t acia_base_c64 []
List of base addresses for the emulated chip (x64/x64sc/xscpu64)
static const vice_gtk3_radiogroup_entry_t acia_base_c128 []
List of base addresses for the emulated chip (x128)
static const vice_gtk3_radiogroup_entry_t acia_base_vic20 []
List of base addresses for the emulated chip (xvic)
static const vice_gtk3_radiogroup_entry_t acia_irqs []
List of ACIA IRQ sources (x64/x64sc/xscpu64/x128/xvic)
static const vice_gtk3_radiogroup_entry_t acia_modes []
List of emulated RS232 modes (x64/x64sc/xscpu64/x128/xvic)
static const vice_gtk3_combo_entry_int_t rsuser_baud_rates []
List of user-port RS232 baud rates (x64/x64sc/xscpu64/x128/xvic)
static const vice_gtk3_combo_entry_int_t serial_baud_rates_c64 []
List of baud rates for C64/C128/VIC-20 serial devices.
static const vice_gtk3_combo_entry_int_t serial_baud_rates_plus4 []
List of baud rates for Plus4/CBM-II.
static GtkWidget * rsuser_baud_widget
Userport baud rate widget.
Detailed Description
Widget to control various RS232 resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_acia_base_widget()
static GtkWidget * create_acia_base_widget (void) static
Create a group of radio buttons to set the ACIA chip address.
Returns
GtkGrid with radio buttons or NULL when the current machine doesn't support selecting a base address
Referenced by create_acia_widget().
create_acia_enable_widget()
static GtkWidget * create_acia_enable_widget (void) static
{{{ ACIA widgets
Create a check button to enable/disable ACIA emulation
Returns
GtkCheckButton or NULL when the current machine doesn't support toggling emulation
Referenced by create_acia_widget().
create_acia_irq_widget()
static GtkWidget * create_acia_irq_widget (void) static
Create a group of radio buttons to set the ACIA IRQ source.
Returns
GtkGrid with radio buttons or NULL when the current machine doesn't support selecting an IRQ
Referenced by create_acia_widget().
create_acia_mode_widget()
static GtkWidget * create_acia_mode_widget (void) static
Create a group of radio buttons to set the RS232 mode.
Returns
GtkGrid with radio buttons or NULL when the current machine doesn't support selecting an interface
Referenced by create_acia_widget().
create_acia_widget()
static GtkWidget * create_acia_widget (void) static
Create RS232 ACIA settings widget.
Returns
GtkGrid
Referenced by settings_rs232_widget_create().
create_indented_label()
static GtkWidget * create_indented_label (const char * text) static
Helper: create left-aligned, 16 px indented label.
Parameters
[in] text label text
Returns
GtkLabel
Referenced by create_acia_widget(), create_rs232_devices_widget(), and create_userport_widget().
create_rs232_devices_widget()
static GtkWidget * create_rs232_devices_widget (void) static
Create RS232 devices widget.
XXX: only supports Unix, Windows appears do things differently.
Returns
GtkGrid
Referenced by settings_rs232_widget_create().
create_serial_baud_widget()
static GtkWidget * create_serial_baud_widget (const char * resource) static
}}}
Create combo box with baud rates for serial devices
Parameters
[in] resource resource that contains the baud rate
Returns
GtkComboBox
Referenced by create_rs232_devices_widget().
create_userport_widget()
static GtkWidget * create_userport_widget (void) static
Create user-port RS232 emulation settings widget.
Note
C64,C128 and VIC-20 only
Returns
GtkGrid
Referenced by settings_rs232_widget_create().
machine_has_acia()
static bool machine_has_acia (void) static
Determine if the current machine supports ACIA.
Returns
true if ACIA either native or through expansions
Referenced by create_acia_base_widget(), create_acia_enable_widget(), create_acia_irq_widget(), and create_acia_mode_widget().
on_rsinterface_changed()
static void on_rsinterface_changed (GtkWidget * widget) static
Extra event handler for the userport RS-232 interface type changes.
Parameters
[in] widget Userport RS-232 interface type combobox
Referenced by create_userport_widget().
settings_rs232_widget_create()
GtkWidget * settings_rs232_widget_create (GtkWidget * parent)
Create RS232 settings widget.
Invalid for PET, C64DTV and VSID
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
Variable Documentation
acia_base_c128
const vice_gtk3_radiogroup_entry_t acia_base_c128[] static
Initial value:
= {
    { "$D700", 0xd700 },
    { "$DE00", 0xde00 },
    { "$DF00", 0xdf00 },
    { NULL,        -1 }
}
List of base addresses for the emulated chip (x128)
Referenced by create_acia_base_widget().
acia_base_c64
const vice_gtk3_radiogroup_entry_t acia_base_c64[] static
Initial value:
= {
    { "$DE00", 0xde00 },
    { "$DF00", 0xdf00 },
    { NULL,        -1 }
}
List of base addresses for the emulated chip (x64/x64sc/xscpu64)
Referenced by create_acia_base_widget().
acia_base_vic20
const vice_gtk3_radiogroup_entry_t acia_base_vic20[] static
Initial value:
= {
    { "$9800", 0x9800 },
    { "$9C00", 0x9c00 },
    { NULL,        -1 }
}
List of base addresses for the emulated chip (xvic)
Referenced by create_acia_base_widget().
acia_devices
const vice_gtk3_combo_entry_int_t acia_devices[] static
Initial value:
= {
    { "Serial 1",   0  },
    { "Serial 2",   1  },
    { "Serial 3",   2  },
    { "Serial 4",   3  },
    { NULL,       -1 }
}
List of ACIA devices.
Note
Also used by the Userport RS232 Device list combo box
Referenced by create_acia_widget(), and create_userport_widget().
acia_irqs
const vice_gtk3_radiogroup_entry_t acia_irqs[] static
Initial value:
= {
    { "None",   0  },
    { "NMI",    1  },
    { "IRQ",    2  },
    { NULL,   -1 }
}
List of ACIA IRQ sources (x64/x64sc/xscpu64/x128/xvic)
Referenced by create_acia_irq_widget().
acia_modes
const vice_gtk3_radiogroup_entry_t acia_modes[] static
Initial value:
= {
    { "Normal",      0   },
    { "Swiftlink",   1   },
    { "Turbo232",    2   },
    { NULL,        -1 }
}
List of emulated RS232 modes (x64/x64sc/xscpu64/x128/xvic)
Referenced by create_acia_mode_widget().
rsuser_baud_rates
const vice_gtk3_combo_entry_int_t rsuser_baud_rates[] static
Initial value:
= {
    { "300",     300 },
    { "600",     600 },
    { "1200",   1200 },
    { "2400",   2400 },
    { "4800",   4800 },
    { "9600",   9600 },
    { "38400", 38400 },
    { "57600", 57600 },
    { NULL,       -1 }
}
List of user-port RS232 baud rates (x64/x64sc/xscpu64/x128/xvic)
Referenced by create_userport_widget().
rsuser_baud_widget
GtkWidget* rsuser_baud_widget static
Userport baud rate widget.
Referenced by create_userport_widget(), and on_rsinterface_changed().
serial_baud_rates_c64
const vice_gtk3_combo_entry_int_t serial_baud_rates_c64[] static
Initial value:
= {
    { "300",       300 },
    { "1200",     1200 },
    { "2400",     2400 },
    { "9600",     9600 },
    { "19200",   19200 },
    { "38400",   38400 },
    { "57600",   57600 },
    { "115200", 115200 },
    { NULL,         -1 }
}
List of baud rates for C64/C128/VIC-20 serial devices.
Referenced by create_serial_baud_widget().
serial_baud_rates_plus4
const vice_gtk3_combo_entry_int_t serial_baud_rates_plus4[] static
Initial value:
= {
    { "300",     300 },
    { "1200",   1200 },
    { "2400",   2400 },
    { "9600",   9600 },
    { "19200", 19200 },
    { NULL,       -1 }
}
List of baud rates for Plus4/CBM-II.
Referenced by create_serial_baud_widget().