vsid: c64/vsidcia1.c File Reference
vsidcia1.c File Reference
#include "vice.h"
#include <stdio.h>
#include "c64fastiec.h"
#include "c64-resources.h"
#include "c64.h"
#include "c64cia.h"
#include "cia.h"
#include "interrupt.h"
#include "drive.h"
#include "joystick.h"
#include "keyboard.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "types.h"
#include "vicii.h"
Functions
void cia1_store (uint16_t addr, uint8_t data)
uint8_t cia1_read (uint16_t addr)
uint8_t cia1_peek (uint16_t addr)
void cia1_update_model (void)
static void cia_set_int_clk (cia_context_t *cia_context, int value, CLOCK clk)
static void cia_restore_int (cia_context_t *cia_context, int value)
void cia1_set_extended_keyboard_rows_mask (uint8_t value)
static void pulse_ciapc (cia_context_t *cia_context, CLOCK rclk)
static void pre_store (void)
static void pre_read (void)
static void pre_peek (void)
static void do_reset_cia (cia_context_t *cia_context)
static void cia1_internal_lightpen_check (uint8_t pa, uint8_t pb)
void cia1_check_lightpen (void)
static void store_ciapa (cia_context_t *cia_context, CLOCK rclk, uint8_t b)
static void undump_ciapa (cia_context_t *cia_context, CLOCK rclk, uint8_t b)
static void store_ciapb (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static void undump_ciapb (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static uint8_t read_ciapa (cia_context_t *cia_context)
static uint8_t read_ciapb (cia_context_t *cia_context)
static void read_ciaicr (cia_context_t *cia_context)
static void read_sdr (cia_context_t *cia_context)
static void store_sdr (cia_context_t *cia_context, uint8_t byte)
void cia1_init (cia_context_t *cia_context)
void cia1_setup_context (machine_context_t *machine_ctx)
void cia1_set_timing (cia_context_t *cia_context, int tickspersec, int powerfreq)
Function Documentation
cia1_check_lightpen()
void cia1_check_lightpen (void)
Referenced by c64joystick_machine_func(), and c64keyboard_machine_func().
cia1_init()
void cia1_init (cia_context_t * cia_context)
Referenced by machine_specific_init().
cia1_internal_lightpen_check()
static void cia1_internal_lightpen_check (uint8_t pa, uint8_t pb) static
Referenced by cia1_check_lightpen(), store_ciapa(), and store_ciapb().
cia1_peek()
uint8_t cia1_peek (uint16_t addr)
Referenced by peek_bank_io().
cia1_read()
uint8_t cia1_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
cia1_set_extended_keyboard_rows_mask()
void cia1_set_extended_keyboard_rows_mask (uint8_t value)
Referenced by d02f_store().
cia1_set_timing()
void cia1_set_timing (cia_context_t * cia_context, int tickspersec, int powerfreq)
Referenced by cia1_setup_context(), and machine_change_timing().
cia1_setup_context()
void cia1_setup_context (machine_context_t * machine_ctx)
Referenced by machine_setup_context().
cia1_store()
void cia1_store (uint16_t addr, uint8_t data)
< Control register A
Referenced by c64meminit(), and store_bank_io().
cia1_update_model()
void cia1_update_model (void)
Referenced by set_cia1_model().
cia_restore_int()
static void cia_restore_int (cia_context_t * cia_context, int value) static
Referenced by cia1_setup_context().
cia_set_int_clk()
static void cia_set_int_clk (cia_context_t * cia_context, int value, CLOCK clk) static
Referenced by cia1_setup_context().
do_reset_cia()
static void do_reset_cia (cia_context_t * cia_context) static
Referenced by cia1_setup_context().
pre_peek()
static void pre_peek (void) static
Referenced by cia1_setup_context().
pre_read()
static void pre_read (void) static
Referenced by cia1_setup_context().
pre_store()
static void pre_store (void) static
Referenced by cia1_setup_context().
pulse_ciapc()
static void pulse_ciapc (cia_context_t * cia_context, CLOCK rclk) static
Referenced by cia1_setup_context().
read_ciaicr()
static void read_ciaicr (cia_context_t * cia_context) static
Referenced by cia1_setup_context().
read_ciapa()
static uint8_t read_ciapa (cia_context_t * cia_context) static
< Port A
< Data direction register for port A
Referenced by cia1_setup_context().
read_ciapb()
static uint8_t read_ciapb (cia_context_t * cia_context) static
< Port B
< Data direction register for port B
< Data direction register for port A
< Data direction register for port B
< Port B
Referenced by cia1_setup_context().
read_sdr()
static void read_sdr (cia_context_t * cia_context) static
Referenced by cia1_setup_context().
store_ciapa()
static void store_ciapa (cia_context_t * cia_context, CLOCK rclk, uint8_t b) static
Referenced by cia1_setup_context().
store_ciapb()
static void store_ciapb (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
Referenced by cia1_setup_context().
store_sdr()
static void store_sdr (cia_context_t * cia_context, uint8_t byte) static
Referenced by cia1_setup_context().
undump_ciapa()
static void undump_ciapa (cia_context_t * cia_context, CLOCK rclk, uint8_t b) static
Referenced by cia1_setup_context().
undump_ciapb()
static void undump_ciapb (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
Referenced by cia1_setup_context().