x128: arch/gtk3/widgets/settings_mmcr.c File Reference
settings_mmcr.c File Reference
Settings widget to control MMC Replay resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "c64cart.h"
#include "cartridge.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "settings_mmcr.h"
Macros
#define CARTNAME CARTRIDGE_NAME_MMC_REPLAY
Temporary define to make editing easier.
#define NUM_COLS 4
Functions
static void save_filename_callback (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the save-dialog response handler.
static void on_save_clicked (GtkWidget *widget, gpointer user_data)
Handler for the "clicked" event of the Save Image button.
static void on_flush_clicked (GtkWidget *widget, gpointer user_data)
Handler for the "clicked" event of the Flush Image button.
static GtkWidget * create_rescue_mode_widget (void)
Create grid with switch and label for the MMCRRescueMode resource.
static int create_eeprom_layout (GtkWidget *grid, int row, int columns)
Add EEPROM widgets to main grid.
static int create_card_layout (GtkWidget *grid, int row, int columns)
Add widgets for the SD/MCC card.
static int create_cart_image_layout (GtkWidget *grid, int row, int columns)
Add cartridge image widgets to main grid.
GtkWidget * settings_mmcr_widget_create (GtkWidget *parent)
Create widget to control MMC Replay resources.
Variables
static const vice_gtk3_radiogroup_entry_t card_types []
List of memory card types.
Detailed Description
Settings widget to control MMC Replay resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
CARTNAME
#define CARTNAME CARTRIDGE_NAME_MMC_REPLAY
Temporary define to make editing easier.
NUM_COLS
#define NUM_COLS 4
Function Documentation
create_card_layout()
static int create_card_layout (GtkWidget * grid, int row, int columns) static
Add widgets for the SD/MCC card.
Parameters
[in] grid main grid
[in] row row in grid to add widgets
[in] columns number of columns in grid, for proper column span
Returns
row in grid to add more widgets
< see manual
< see manual
Referenced by settings_mmcr_widget_create().
create_cart_image_layout()
static int create_cart_image_layout (GtkWidget * grid, int row, int columns) static
Add cartridge image widgets to main grid.
Parameters
[in] grid main grid
[in] row row in grid to add widgets
[in] columns number of columns in grid, for proper column span
Returns
row in grid to add more widgets
< see manual
Referenced by settings_mmcr_widget_create().
create_eeprom_layout()
static int create_eeprom_layout (GtkWidget * grid, int row, int columns) static
Add EEPROM widgets to main grid.
Parameters
[in] grid main grid
[in] row row in grid to add widgets
[in] columns number of columns in grid, for proper column span
Returns
row in grid to add more widgets
< see manual
< see manual
Referenced by settings_mmcr_widget_create().
create_rescue_mode_widget()
static GtkWidget * create_rescue_mode_widget (void) static
Create grid with switch and label for the MMCRRescueMode resource.
Returns
GtkGrid
Referenced by settings_mmcr_widget_create().
on_flush_clicked()
static void on_flush_clicked (GtkWidget * widget, gpointer user_data) static
Handler for the "clicked" event of the Flush Image button.
Parameters
[in] widget button
[in] user_data unused
< mmcreplay.c, ser-eeprom.c, spi-sdcard.c
< see manual
Referenced by create_cart_image_layout().
on_save_clicked()
static void on_save_clicked (GtkWidget * widget, gpointer user_data) static
Handler for the "clicked" event of the Save Image button.
Parameters
[in] widget button (unused)
[in] user_data extra event data (unused)
< see manual
Referenced by create_cart_image_layout().
save_filename_callback()
static void save_filename_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the save-dialog response handler.
Parameters
[in,out] dialog save-file dialog
[in,out] filename filename
[in] data extra data (unused)
< mmcreplay.c, ser-eeprom.c, spi-sdcard.c
< see manual
Referenced by on_save_clicked().
settings_mmcr_widget_create()
GtkWidget * settings_mmcr_widget_create (GtkWidget * parent)
Create widget to control MMC Replay resources.
Parameters
[in] parent parent widget (used for dialogs)
Returns
GtkGrid
Variable Documentation
card_types
const vice_gtk3_radiogroup_entry_t card_types[] static
Initial value:
= {
    { "Auto", MMCR_TYPE_AUTO },
    { "MMC",  MMCR_TYPE_MMC },
    { "SD",   MMCR_TYPE_SD },
    { "SDHC", MMCR_TYPE_SDHC },
    { NULL,   -1 }
}
List of memory card types.
Referenced by create_card_layout().