vsid: arch/gtk3/widgets/vdcmodelwidget.c File Reference
vdcmodelwidget.c File Reference
VDC settings widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "debug_gtk3.h"
#include "machine.h"
#include "resources.h"
#include "vdc.h"
#include "vice_gtk3.h"
#include "vdcmodelwidget.h"
Functions
static void on_revision_toggled (GtkWidget *widget, gpointer revision)
Handler for the 'toggled' event of the revision radio buttons.
static void on_64kb_ram_toggled (GtkWidget *widget, gpointer data)
brief Extra event handler to update C128 model setting
static GtkWidget * create_64kb_widget (void)
Create check button to toggle 64KB video ram.
static void vdc_model_widget_connect_signals (GtkWidget *widget)
Connect extra signal handlers to the VDC revision radiogroup.
GtkWidget * vdc_model_widget_create (void)
Create widget to manipulate VDC settings.
void vdc_model_widget_update (GtkWidget *widget)
Update the VDC model widget.
void vdc_model_widget_set_revision_callback (void(*func)(int))
Set callback function to trigger on revision changes.
void vdc_model_widget_set_ram_callback (void(*func)(int))
Set callback function to trigger on RAM size changes.
Variables
static const vice_gtk3_radiogroup_entry_t vdc_revs []
List of VDC revisions.
static void(* vdc_revision_func)(int)
Callback function for revision changes.
static void(* vdc_ram_func)(int)
Callback function for RAM size changes.
Detailed Description
VDC settings widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Todo:
Block signal handlers from being invoked in the update() function
Function Documentation
create_64kb_widget()
static GtkWidget * create_64kb_widget (void) static
Create check button to toggle 64KB video ram.
Returns
GtkCheckButton
Referenced by vdc_model_widget_create().
on_64kb_ram_toggled()
static void on_64kb_ram_toggled (GtkWidget * widget, gpointer data) static
brief Extra event handler to update C128 model setting
Parameters
[in] widget 64KB check button
[in] data extra event data (unused)
Referenced by vdc_model_widget_create().
on_revision_toggled()
static void on_revision_toggled (GtkWidget * widget, gpointer revision) static
Handler for the 'toggled' event of the revision radio buttons.
Parameters
[in] widget radio button
[in] revision VDC revision (int)
Referenced by vdc_model_widget_connect_signals().
vdc_model_widget_connect_signals()
static void vdc_model_widget_connect_signals (GtkWidget * widget) static
Connect extra signal handlers to the VDC revision radiogroup.
Add signal handlers to the revision radio buttons to trigger the extra callback.
Parameters
[in,out] widget VDC revision widget
Referenced by vdc_model_widget_create().
vdc_model_widget_create()
GtkWidget * vdc_model_widget_create (void)
Create widget to manipulate VDC settings.
Returns
GtkGrid
Referenced by create_c128_layout().
vdc_model_widget_set_ram_callback()
void vdc_model_widget_set_ram_callback (void(*)(int) func)
Set callback function to trigger on RAM size changes.
Parameters
[in] func callback
Referenced by create_c128_layout().
vdc_model_widget_set_revision_callback()
void vdc_model_widget_set_revision_callback (void(*)(int) func)
Set callback function to trigger on revision changes.
Parameters
[in] func callback
Referenced by create_c128_layout().
vdc_model_widget_update()
void vdc_model_widget_update (GtkWidget * widget)
Update the VDC model widget.
Parameters
[in,out] widget VDC model widget
Referenced by machine_model_handler_c128().
Variable Documentation
vdc_ram_func
void(* vdc_ram_func) (int) (int) static
Callback function for RAM size changes.
Referenced by on_64kb_ram_toggled(), and vdc_model_widget_set_ram_callback().
vdc_revision_func
void(* vdc_revision_func) (int) (int) static
Callback function for revision changes.
Referenced by on_revision_toggled(), and vdc_model_widget_set_revision_callback().
vdc_revs
const vice_gtk3_radiogroup_entry_t vdc_revs[] static
Initial value:
= {
    { "Revision 0",  VDC_REVISION_0 },
    { "Revision 1",  VDC_REVISION_1 },
    { "Revision 2",  VDC_REVISION_2 },
    { NULL,         -1 }
}
List of VDC revisions.
Referenced by vdc_model_widget_connect_signals(), vdc_model_widget_create(), and vdc_model_widget_update().