vsid: serial/serial-iec-bus.c File Reference
serial-iec-bus.c File Reference
#include "vice.h"
#include "fsdrive.h"
#include "realdevice.h"
#include "serial-iec-bus.h"
#include "serial.h"
#include "types.h"
Macros
#define DBG(x)
Functions
void serial_iec_bus_open (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void serial_iec_bus_close (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void serial_iec_bus_listen (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void serial_iec_bus_talk (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void serial_iec_bus_unlisten (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void serial_iec_bus_untalk (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void serial_iec_bus_write (unsigned int device, uint8_t secondary, uint8_t data, void(*st_func)(uint8_t))
uint8_t serial_iec_bus_read (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void serial_iec_bus_reset (void)
void serial_iec_bus_init (void)
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
serial_iec_bus_close()
void serial_iec_bus_close (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_close(), serial_iec_device_exec_main(), and serial_trap_attention().
serial_iec_bus_init()
void serial_iec_bus_init (void)
Referenced by machine_specific_init().
serial_iec_bus_listen()
void serial_iec_bus_listen (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by send_listen_talk_secondary(), serial_iec_device_exec_main(), and serial_iec_write().
serial_iec_bus_open()
void serial_iec_bus_open (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_device_exec_main(), serial_iec_open(), and serial_trap_attention().
serial_iec_bus_read()
uint8_t serial_iec_bus_read (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_device_exec_main(), serial_iec_read(), and serial_trap_receive().
serial_iec_bus_reset()
void serial_iec_bus_reset (void)
Referenced by serial_traps_reset().
serial_iec_bus_talk()
void serial_iec_bus_talk (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by send_listen_talk_secondary(), serial_iec_device_exec_main(), and serial_iec_read().
serial_iec_bus_unlisten()
void serial_iec_bus_unlisten (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_close(), serial_iec_device_exec_main(), serial_iec_open(), serial_iec_read(), and serial_trap_attention().
serial_iec_bus_untalk()
void serial_iec_bus_untalk (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_close(), serial_iec_device_exec_main(), serial_iec_write(), and serial_trap_attention().
serial_iec_bus_write()
void serial_iec_bus_write (unsigned int device, uint8_t secondary, uint8_t data, void(*)(uint8_t) st_func)
Referenced by serial_iec_device_exec_main(), serial_iec_open(), serial_iec_write(), and serial_trap_send().