vsid: tapeport/tapeport.c File Reference
tapeport.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "cmdline.h"
#include "cp-clockf83.h"
#include "datasette.h"
#include "dtl-basic-dongle.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "sense-dongle.h"
#include "snapshot.h"
#include "tapecart.h"
#include "tapeport.h"
#include "uiapi.h"
#include "util.h"
Data Structures
struct type2text_s
struct tapeport_opt_s
Macros
#define DUMP_VER_MAJOR 1
#define DUMP_VER_MINOR 0
Typedefs
typedef struct type2text_s type2text_t
Functions
static const char * tapeport_type2text (int type)
int tapeport_device_register (int id, tapeport_device_t *device)
register a device to be used in the tapeport system
static int tapeport_check_valid_device (int port, int id)
check if the selected device can be attached to the indicated port
static int tapeport_set_device (int port, int id)
attach device 'id' to a tapeport
static int tapeport_valid_devices_compare_names (const void *a, const void *b)
int tapeport_valid_port (int port)
tapeport_desc_t * tapeport_get_valid_devices (int port, int sort)
const char * tapeport_get_device_type_desc (int type)
void tapeport_set_motor (int port, int flag)
void tapeport_toggle_write_bit (int port, int write_bit)
void tapeport_set_sense_out (int port, int sense)
void tapeport_powerup (void)
void tapeport_trigger_flux_change (unsigned int on, int port)
void tapeport_set_tape_sense (int sense, int port)
void tapeport_set_write_in (int val, int port)
void tapeport_set_motor_in (int val, int port)
static int set_tapeport_device (int val, void *param)
static int tapeport_device_resources_init (int amount)
int tapeport_resources_init (int amount)
void tapeport_resources_shutdown (void)
static int is_a_number (const char *str)
static int set_tapeport_cmdline_device (const char *param, void *extra_param)
static char * build_tapeport_string (int port)
static int tapeport_devices_cmdline_options_init (void)
int tapeport_cmdline_options_init (void)
void tapeport_enable (int val)
int tapeport_get_active_state (void)
int tapeport_snapshot_write_module (snapshot_t *s, int write_image)
int tapeport_snapshot_read_module (struct snapshot_s *s)
Variables
static int tapeport_active = 1
flag indicating if the tapeport exists on the current emulated model
static int tapeport_current_device [TAPEPORT_MAX_PORTS] = { TAPEPORT_DEVICE_NONE, TAPEPORT_DEVICE_NONE }
current tapeport devices
static tapeport_device_t tapeport_device [TAPEPORT_MAX_DEVICES] = {0}
static int tapeport_ports = 0
static type2text_t device_type_desc []
static const resource_int_t resources_int_port1 []
static const resource_int_t resources_int_port2 []
static const struct tapeport_opt_s id_match []
static cmdline_option_t cmdline_options_port1 []
static cmdline_option_t cmdline_options_port2 []
static const char snap_module_name [] = "TAPEPORT"
Macro Definition Documentation
DUMP_VER_MAJOR
#define DUMP_VER_MAJOR 1
DUMP_VER_MINOR
#define DUMP_VER_MINOR 0
Typedef Documentation
type2text_t
typedef struct type2text_s type2text_t
Function Documentation
build_tapeport_string()
static char * build_tapeport_string (int port) static
Referenced by tapeport_cmdline_options_init().
is_a_number()
static int is_a_number (const char * str) static
Referenced by set_tapeport_cmdline_device().
set_tapeport_cmdline_device()
static int set_tapeport_cmdline_device (const char * param, void * extra_param) static
set_tapeport_device()
static int set_tapeport_device (int val, void * param) static
Referenced by set_tapeport_cmdline_device().
tapeport_check_valid_device()
static int tapeport_check_valid_device (int port, int id) static
check if the selected device can be attached to the indicated port
Referenced by tapeport_get_valid_devices(), and tapeport_set_device().
tapeport_cmdline_options_init()
int tapeport_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
tapeport_device_register()
int tapeport_device_register (int id, tapeport_device_t * device)
register a device to be used in the tapeport system
Referenced by dtlbasic_dongle_resources_init(), sense_dongle_resources_init(), tapecart_resources_init(), and tapertc_resources_init().
tapeport_device_resources_init()
static int tapeport_device_resources_init (int amount) static
Referenced by tapeport_resources_init().
tapeport_devices_cmdline_options_init()
static int tapeport_devices_cmdline_options_init (void) static
Referenced by tapeport_cmdline_options_init().
tapeport_enable()
void tapeport_enable (int val)
Referenced by c64model_set().
tapeport_get_active_state()
int tapeport_get_active_state (void)
tapeport_get_device_type_desc()
const char * tapeport_get_device_type_desc (int type)
Referenced by create_device_model().
tapeport_get_valid_devices()
tapeport_desc_t * tapeport_get_valid_devices (int port, int sort)
Referenced by build_tapeport_string(), and create_device_model().
tapeport_powerup()
void tapeport_powerup (void)
Referenced by machine_specific_powerup().
tapeport_resources_init()
int tapeport_resources_init (int amount)
Referenced by machine_resources_init().
tapeport_resources_shutdown()
void tapeport_resources_shutdown (void)
Referenced by machine_resources_shutdown().
tapeport_set_device()
static int tapeport_set_device (int port, int id) static
attach device 'id' to a tapeport
Referenced by set_tapeport_device(), and tapeport_snapshot_read_module().
tapeport_set_motor()
void tapeport_set_motor (int port, int flag)
Referenced by c64pla_config_changed().
tapeport_set_motor_in()
void tapeport_set_motor_in (int val, int port)
tapeport_set_sense_out()
void tapeport_set_sense_out (int port, int sense)
Referenced by c64pla_config_changed().
tapeport_set_tape_sense()
void tapeport_set_tape_sense (int sense, int port)
Referenced by check_sense(), sense_dongle_enable(), sense_dongle_powerup(), and set_sense().
tapeport_set_write_in()
void tapeport_set_write_in (int val, int port)
Referenced by set_write().
tapeport_snapshot_read_module()
int tapeport_snapshot_read_module (struct snapshot_s * s)
Referenced by c64_snapshot_read().
tapeport_snapshot_write_module()
int tapeport_snapshot_write_module (snapshot_t * s, int write_image)
Referenced by c64_snapshot_write().
tapeport_toggle_write_bit()
void tapeport_toggle_write_bit (int port, int write_bit)
Referenced by c64pla_config_changed().
tapeport_trigger_flux_change()
void tapeport_trigger_flux_change (unsigned int on, int port)
Referenced by cmdmode_send_pulses(), dtlbasic_write(), and tapecart_pulse_alarm_handler().
tapeport_type2text()
static const char * tapeport_type2text (int type) static
Referenced by tapeport_get_device_type_desc().
tapeport_valid_devices_compare_names()
static int tapeport_valid_devices_compare_names (const void * a, const void * b) static
Referenced by tapeport_get_valid_devices().
tapeport_valid_port()
int tapeport_valid_port (int port)
Variable Documentation
cmdline_options_port1
cmdline_option_t cmdline_options_port1[] static
Initial value:
=
{
    { "-tapeport1device", CALL_FUNCTION,  (1 << 0)  |  (1 << 2) ,
      set_tapeport_cmdline_device, (void *)TAPEPORT_PORT_1, "TapePort1Device", NULL,
      "Device", NULL },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by tapeport_cmdline_options_init().
cmdline_options_port2
cmdline_option_t cmdline_options_port2[] static
Initial value:
=
{
    { "-tapeport2device", CALL_FUNCTION,  (1 << 0)  |  (1 << 2) ,
      set_tapeport_cmdline_device, (void *)TAPEPORT_PORT_2, "TapePort2Device", NULL,
      "Device", NULL },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by tapeport_cmdline_options_init().
device_type_desc
type2text_t device_type_desc[] static
Initial value:
= {
    { TAPEPORT_DEVICE_TYPE_NONE, "None" },
    { TAPEPORT_DEVICE_TYPE_TAPE, "Tape" },
    { TAPEPORT_DEVICE_TYPE_STORAGE, "Storage" },
    { TAPEPORT_DEVICE_TYPE_RTC, "Real-time clock" },
    { TAPEPORT_DEVICE_TYPE_DONGLE, "Dongle" },
    { -1, NULL }
}
Referenced by tapeport_type2text().
id_match
const struct tapeport_opt_s id_match[] static
Initial value:
= {
    { "none",           TAPEPORT_DEVICE_NONE },
    { "datasette",      TAPEPORT_DEVICE_DATASETTE },
    { "casette",        TAPEPORT_DEVICE_DATASETTE },
    { "tape",           TAPEPORT_DEVICE_DATASETTE },
    { "tapecart",       TAPEPORT_DEVICE_TAPECART },
    { "rtc",            TAPEPORT_DEVICE_CP_CLOCK_F83 },
    { "sensedongle",    TAPEPORT_DEVICE_SENSE_DONGLE },
    { "tapedongle",     TAPEPORT_DEVICE_SENSE_DONGLE },
    { "playdongle",     TAPEPORT_DEVICE_SENSE_DONGLE },
    { "dtl",            TAPEPORT_DEVICE_DTL_BASIC_DONGLE },
    { "dtldongle",      TAPEPORT_DEVICE_DTL_BASIC_DONGLE },
    { "dtlbasic",       TAPEPORT_DEVICE_DTL_BASIC_DONGLE },
    { "dtlbasicdongle", TAPEPORT_DEVICE_DTL_BASIC_DONGLE },
    { NULL, -1 }
}
Referenced by set_tapeport_cmdline_device().
resources_int_port1
const resource_int_t resources_int_port1[] static
Initial value:
= {
    { "TapePort1Device", TAPEPORT_DEVICE_DATASETTE, RES_EVENT_NO, NULL,
      &tapeport_current_device[TAPEPORT_PORT_1], set_tapeport_device, (void *)TAPEPORT_PORT_1 },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by tapeport_resources_init().
resources_int_port2
const resource_int_t resources_int_port2[] static
Initial value:
= {
    { "TapePort2Device", TAPEPORT_DEVICE_DATASETTE, RES_EVENT_NO, NULL,
      &tapeport_current_device[TAPEPORT_PORT_2], set_tapeport_device, (void *)TAPEPORT_PORT_2 },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by tapeport_resources_init().
snap_module_name
const char snap_module_name[] = "TAPEPORT" static
Referenced by tapeport_snapshot_read_module(), and tapeport_snapshot_write_module().
tapeport_active
int tapeport_active = 1 static
flag indicating if the tapeport exists on the current emulated model
Referenced by tapeport_enable(), tapeport_get_active_state(), tapeport_powerup(), tapeport_resources_shutdown(), tapeport_snapshot_read_module(), and tapeport_snapshot_write_module().
tapeport_current_device
int tapeport_current_device[TAPEPORT_MAX_PORTS] = { TAPEPORT_DEVICE_NONE, TAPEPORT_DEVICE_NONE } static
current tapeport devices
Referenced by tapeport_powerup(), tapeport_set_device(), tapeport_set_motor(), tapeport_set_sense_out(), tapeport_snapshot_read_module(), tapeport_snapshot_write_module(), and tapeport_toggle_write_bit().
tapeport_device
tapeport_device_t tapeport_device[TAPEPORT_MAX_DEVICES] = {0} static
Referenced by tapeport_check_valid_device(), tapeport_device_register(), tapeport_get_valid_devices(), tapeport_powerup(), tapeport_resources_init(), tapeport_resources_shutdown(), tapeport_set_device(), tapeport_set_motor(), tapeport_set_sense_out(), tapeport_snapshot_read_module(), tapeport_snapshot_write_module(), and tapeport_toggle_write_bit().
tapeport_ports
int tapeport_ports = 0 static
Referenced by tapeport_cmdline_options_init(), tapeport_resources_init(), tapeport_snapshot_read_module(), tapeport_snapshot_write_module(), and tapeport_valid_port().