x128: arch/gtk3/hotkeys.h File Reference
hotkeys.h File Reference
Gtk3 custom hotkeys handling - header.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdbool.h>
#include "archdep_defs.h"
#include "hotkeystypes.h"
#include "uiactions.h"
#include "uitypes.h"
Data Structures
struct vhk_gtk_map_s
Gtk3-specific user_data object in vhk_map_t
Macros
#define VHK_ACCEPTED_MODIFIERS (GDK_SHIFT_MASK|GDK_CONTROL_MASK|GDK_MOD1_MASK)
Accepted GDK modifiers for hotkeys.
Typedefs
typedef struct vhk_gtk_map_s vhk_gtk_map_t
Gtk3-specific user_data object in vhk_map_t
Functions
vhk_gtk_map_t * vhk_gtk_map_new (const ui_menu_item_t *decl)
Create gtk3-specific hotkey data object.
void vhk_gtk_map_free (vhk_gtk_map_t *map)
Free memory used by gtk3-specific hotkey data object.
void vhk_gtk_init_accelerators (GtkWidget *window)
Create accelerator group and add it to window.
gboolean vhk_gtk_remove_accelerator (guint keysym, GdkModifierType modifier)
Remove accelerator from global accelerator group.
gchar * vhk_gtk_get_accel_label_by_action (int action)
Get accelerator label for UI action, if any.
gchar * vhk_gtk_get_accel_label_by_map (const ui_action_map_t *map)
Get accelerator label for hotkey in map.
GtkWidget * vhk_gtk_get_menu_item_by_action_for_window (int action, int window_id)
Get runtime menu item for UI action and main window.
void vhk_gtk_set_menu_item_accel_label (GtkWidget *item, int action)
Set accelerator label to the hotkey associated with UI action.
void vhk_gtk_set_check_item_blocked (GtkWidget *item, gboolean checked)
Check/uncheck check menu item while blocking its handler.
void vhk_gtk_set_check_item_blocked_by_action (int action, gboolean checked)
Check/uncheck check menu item(s) mapped to UI action.
void vhk_gtk_set_check_item_blocked_by_action_for_window (int action, int window_id, gboolean checked)
Check/uncheck check menu item mapped to UI action for a window.
Detailed Description
Gtk3 custom hotkeys handling - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
VHK_ACCEPTED_MODIFIERS
#define VHK_ACCEPTED_MODIFIERS (GDK_SHIFT_MASK|GDK_CONTROL_MASK|GDK_MOD1_MASK)
Accepted GDK modifiers for hotkeys.
This is required to avoid keys like NumLock showing up in the accelerators, and sometimes GDK will pass along reserved bits (MOD27 etc).
GDK_MOD1_MASK refers to Alt/Option. GDK_MOD2_MASK refers to NumLock, so we filter it out. GDK_META_MASK refers to the Command key on MacOS, doesn't appear to do anything on Linux. GDK_SUPER_MASK refers to the "Windows key" on PC keyboards. Since window managers on Linux, and Windows itself, use this key for all sorts of things, we filter it out.
Control, Alt, Shift
Typedef Documentation
vhk_gtk_map_t
typedef struct vhk_gtk_map_s vhk_gtk_map_t
Gtk3-specific user_data object in vhk_map_t
Todo:
Perhaps move to src/arch/gtk3/widget/settings_hotkeys.c ?
Function Documentation
vhk_gtk_get_accel_label_by_action()
gchar * vhk_gtk_get_accel_label_by_action (int action)
Get accelerator label for UI action, if any.
Parameters
[in] action UI action ID
Returns
accelerator label or `NULL when action not found or no hotkey exists for the action
Todo:
Rename
Referenced by isresethotkey(), mouse_grab_toggle_action(), and ui_create_main_window().
vhk_gtk_get_accel_label_by_map()
gchar * vhk_gtk_get_accel_label_by_map (const ui_action_map_t * map)
Get accelerator label for hotkey in map.
Parameters
[in] map hotkey map
Returns
accelerator label or NULL when no hotkey defined
Note
The value returned is allocated by Gtk and should be freed after use with g_free()
Todo:
Rename
Referenced by create_hotkeys_model(), and vhk_gtk_get_accel_label_by_action().
vhk_gtk_get_menu_item_by_action_for_window()
GtkWidget * vhk_gtk_get_menu_item_by_action_for_window (int action, int window_id)
Get runtime menu item for UI action and main window.
Parameters
[in] action UI action ID
[in] window_id window ID (PRIMARY_WINDOW or SECONDARY_WINDOW)
Returns
menu item or NULL when not found
!
Todo:
Nothing Gtk-specific in this function: could be moved to shared code and return a void*.
Referenced by actions_speed_setup_ui(), speed_cpu_custom_action(), and speed_fps_custom_action().
vhk_gtk_init_accelerators()
void vhk_gtk_init_accelerators (GtkWidget * window)
Create accelerator group and add it to window.
Parameters
[in] window top level window
Note
Allocating the accel group in ui_hotkeys_arch_init() cannot be done since it's too late in the UI setup process.
Referenced by ui_create_main_window().
vhk_gtk_map_free()
void vhk_gtk_map_free (vhk_gtk_map_t * arch_map)
Free memory used by gtk3-specific hotkey data object.
Free memory used by arch_map and its members.
Parameters
[in] arch_map gtk3-specific hotkey data object
Referenced by ui_hotkeys_arch_shutdown().
vhk_gtk_map_new()
vhk_gtk_map_t * vhk_gtk_map_new (const ui_menu_item_t * decl)
Create gtk3-specific hotkey data object.
Create object with a reference to the menu item declaration for a UI action and signal handler IDs to allow the UI code to block/unblock signal handlers. The menu item declaration contains a bool indicating whether to connect a signal handler directly or through the VICE locking mechanism. The signal handler IDs are used to temporarily block signal handlers from triggering when updating their menu items' state (e.g. check/radio buttons).
Parameters
[in] decl UI menu item declaration
Returns
new gtk3-specific hotkey data object
Note
Free object with vhk_map_gtk_free()
Referenced by ui_menu_add().
vhk_gtk_remove_accelerator()
gboolean vhk_gtk_remove_accelerator (guint keysym, GdkModifierType modifier)
Remove accelerator from global accelerator group.
Parameters
[in] keysym Gdk keysym
[in] modifier Gdk modifier mask
Returns
TRUE on success
Referenced by dialog_accept_handler(), on_menu_item_destroy(), and ui_hotkeys_arch_remove_by_map().
vhk_gtk_set_check_item_blocked()
void vhk_gtk_set_check_item_blocked (GtkWidget * item, gboolean checked)
Check/uncheck check menu item while blocking its handler.
Set a checkbox menu item's state while blocking the 'activate' handler so the handler won't recursively call itself.
Parameters
[in] item GtkCheckMenuItem instance
[in] checked new check button state
Referenced by vhk_gtk_set_check_item_blocked_by_action(), and vhk_gtk_set_check_item_blocked_by_action_for_window().
vhk_gtk_set_check_item_blocked_by_action()
void vhk_gtk_set_check_item_blocked_by_action (int action, gboolean checked)
Check/uncheck check menu item(s) mapped to UI action.
Set menu item or items (x128) that are registered for UI action to checked.
Note
This will usually suffice for most items, but in cases where x128 can have different states for a menu item per window (status bar enable/disable, fullscreen, fulllscreen-decorations) the function vhk_gtk_set_check_item_blocked_by_action_for_window() is available.
Parameters
[in] action UI action ID
[in] checked new checked state for menu item(s)
Referenced by actions_display_setup_ui(), actions_joystick_setup_ui(), actions_speed_setup_ui(), actions_vsid_setup_ui(), advance_frame_action(), fullscreen_decorations_toggle_action(), keyset_joystick_toggle_action(), mouse_grab_toggle_action(), pause_toggle_action(), psid_override_toggle_action(), swap_controlport_toggle_action(), ui_action_toggle_show_statusbar(), ui_create_main_window(), update_cpu_radio_buttons(), update_fps_radio_buttons(), and warp_mode_toggle_action().
vhk_gtk_set_check_item_blocked_by_action_for_window()
void vhk_gtk_set_check_item_blocked_by_action_for_window (int action, int window_id, gboolean checked)
Check/uncheck check menu item mapped to UI action for a window.
Set menu item for a main window that is registered for UI action to checked.
Parameters
[in] action UI action ID
[in] window_id window ID (PRIMARY_WINDOW or SECONDARY_WINDOW)
[in] checked new checked state for menu item(s)
Referenced by actions_display_setup_ui(), fullscreen_toggle_action(), show_statusbar_secondary_toggle_action(), and show_statusbar_toggle_action().
vhk_gtk_set_menu_item_accel_label()
void vhk_gtk_set_menu_item_accel_label (GtkWidget * item, int action)
Set accelerator label to the hotkey associated with UI action.
Look up action and if found set the accelerator label of item to the hotkey defined for action, if the action is not found the accelerator label will be cleared. This allows context menus to display an accelerator next to an item. Only sets the label of a menu item, no action handler is set for the item.
Parameters
[in] item runtime menu item
[in] action UI action ID
Referenced by joystick_menu_popup_create(), popup_menu_item_action_new(), popup_menu_new(), speed_menu_popup_create(), ui_do_datasette_popup(), and ui_do_drive_popup().