vsid: drive/iec/ciad.h File Reference
ciad.h File Reference
#include "types.h"
Functions
void cia1571_setup_context (struct diskunit_context_s *ctxptr)
void cia1581_setup_context (struct diskunit_context_s *ctxptr)
void cia1571_init (struct diskunit_context_s *ctxptr)
void cia1571_store (struct diskunit_context_s *ctxptr, uint16_t addr, uint8_t value)
uint8_t cia1571_read (struct diskunit_context_s *ctxptr, uint16_t addr)
uint8_t cia1571_peek (struct diskunit_context_s *ctxptr, uint16_t addr)
int cia1571_dump (struct diskunit_context_s *ctxptr, uint16_t addr)
void mos5710_store (struct diskunit_context_s *ctxptr, uint16_t addr, uint8_t value)
uint8_t mos5710_read (struct diskunit_context_s *ctxptr, uint16_t addr)
uint8_t mos5710_peek (struct diskunit_context_s *ctxptr, uint16_t addr)
int mos5710_dump (struct diskunit_context_s *ctxptr, uint16_t addr)
void cia1581_init (struct diskunit_context_s *ctxptr)
void cia1581_store (struct diskunit_context_s *ctxptr, uint16_t addr, uint8_t value)
uint8_t cia1581_read (struct diskunit_context_s *ctxptr, uint16_t addr)
uint8_t cia1581_peek (struct diskunit_context_s *ctxptr, uint16_t addr)
int cia1581_dump (struct diskunit_context_s *ctxptr, uint16_t addr)
void cia1571_set_timing (struct cia_context_s *cia_context, int tickspersec, int powerfreq)
void cia1581_set_timing (struct cia_context_s *cia_context, int tickspersec, int powerfreq)
Function Documentation
cia1571_dump()
int cia1571_dump (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by drivemem_ioreg_list_get().
cia1571_init()
void cia1571_init (struct diskunit_context_s * ctxptr)
Referenced by iec_drive_init().
cia1571_peek()
uint8_t cia1571_peek (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memiec_init().
cia1571_read()
uint8_t cia1571_read (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memiec_init().
cia1571_set_timing()
void cia1571_set_timing (struct cia_context_s * cia_context, int tickspersec, int powerfreq)
Referenced by cia1571_setup_context().
cia1571_setup_context()
void cia1571_setup_context (struct diskunit_context_s * ctxptr)
Referenced by iec_drive_setup_context().
cia1571_store()
void cia1571_store (struct diskunit_context_s * ctxptr, uint16_t addr, uint8_t value)
Referenced by memiec_init().
cia1581_dump()
int cia1581_dump (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by drivemem_ioreg_list_get().
cia1581_init()
void cia1581_init (struct diskunit_context_s * ctxptr)
Referenced by iec_drive_init().
cia1581_peek()
uint8_t cia1581_peek (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memiec_init().
cia1581_read()
uint8_t cia1581_read (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memiec_init().
cia1581_set_timing()
void cia1581_set_timing (struct cia_context_s * cia_context, int tickspersec, int powerfreq)
Referenced by cia1581_setup_context().
cia1581_setup_context()
void cia1581_setup_context (struct diskunit_context_s * ctxptr)
Todo:
FIXME: incorrect, J1 closed = 1, J1 open, no ticks at all
Referenced by iec_drive_setup_context().
cia1581_store()
void cia1581_store (struct diskunit_context_s * ctxptr, uint16_t addr, uint8_t value)
Referenced by memiec_init().
mos5710_dump()
int mos5710_dump (struct diskunit_context_s * ctxptr, uint16_t addr)
Todo:
extra MFM registers
Referenced by drivemem_ioreg_list_get().
mos5710_peek()
uint8_t mos5710_peek (diskunit_context_t * ctxptr, uint16_t addr)
Todo:
FIXME: need to confirm how it actually mirrors on the real drive
Todo:
extra MFM registers
Todo:
FIXME: all other registers are not implemented
Referenced by memiec_init().
mos5710_read()
uint8_t mos5710_read (diskunit_context_t * ctxptr, uint16_t addr)
Todo:
FIXME: need to confirm how it actually mirrors on the real drive
Todo:
extra MFM registers
Todo:
FIXME: all other registers are not implemented
Referenced by memiec_init().
mos5710_store()
void mos5710_store (diskunit_context_t * ctxptr, uint16_t addr, uint8_t data)
Todo:
FIXME: need to confirm how it actually mirrors on the real drive
Todo:
extra MFM registers
Referenced by memiec_init().