vsid: arch/shared/coproc.c File Reference
coproc.c File Reference
co-process fork
#include "vice.h"
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include "archdep.h"
#include "log.h"
#include "coproc.h"
Macros
#define SHELL "/bin/sh"
#define sigset_t int
Functions
int fork_coproc (int *fd_wr, int *fd_rd, char *cmd, vice_pid_t *childpid)
void kill_coproc (vice_pid_t pid)
Variables
static struct sigaction ignore
Detailed Description
co-process fork
Author
Andre Fachat a.fac.nosp@m.hat@.nosp@m.physi.nosp@m.k.tu.nosp@m.-chem.nosp@m.nitz.nosp@m..de
Macro Definition Documentation
SHELL
#define SHELL "/bin/sh"
Todo:
Perhaps implement fork_coproc() on Haiku using Haiku-specific code instead of relying on the POSIX compatibility layer?
sigset_t
#define sigset_t int
Function Documentation
fork_coproc()
int fork_coproc (int * fd_wr, int * fd_rd, char * cmd, vice_pid_t * childpid)
Referenced by fopen_or_pipe(), and start_ffmpeg_executable().
kill_coproc()
void kill_coproc (vice_pid_t pid)
Referenced by close_stream(), and output_text_close().
Variable Documentation
ignore
struct sigaction ignore static
Referenced by fork_coproc().