vsid: vdrive/vdrive-iec.c File Reference
vdrive-iec.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "cbmdos.h"
#include "diskimage.h"
#include "lib.h"
#include "log.h"
#include "machine-bus.h"
#include "types.h"
#include "vdrive-bam.h"
#include "vdrive-command.h"
#include "vdrive-dir.h"
#include "vdrive-iec.h"
#include "vdrive-rel.h"
#include "vdrive.h"
#include "diskconstants.h"
Macros
#define DBG(x)
#define OFFSET_SUPER_POINTER 3
#define SIDE_SECTORS_MAX 6
#define OFFSET_RECORD_LEN 3
Functions
void vdrive_iec_init (void)
int vdrive_iec_switch (vdrive_t *vdrive, bufferinfo_t *p)
static int iec_open_read_sequential (vdrive_t *vdrive, unsigned int secondary, unsigned int track, unsigned int sector)
static int iec_open_read (vdrive_t *vdrive, unsigned int secondary)
static int iec_open_read_directory (vdrive_t *vdrive, unsigned int secondary, cbmdos_cmd_parse_plus_t *cmd_parse)
static int iec_open_write (vdrive_t *vdrive, unsigned int secondary, cbmdos_cmd_parse_plus_t *cmd_parse)
int vdrive_iec_open (vdrive_t *vdrive, const uint8_t *name, unsigned int length, unsigned int secondary, cbmdos_cmd_parse_t *cmd_parse_ext)
Generic IEC interface.
static int iec_write_sequential (vdrive_t *vdrive, bufferinfo_t *bi, int length)
static int iec_close_sequential (vdrive_t *vdrive, unsigned int secondary)
int vdrive_iec_close (vdrive_t *vdrive, unsigned int secondary)
static int iec_read_sequential (vdrive_t *vdrive, uint8_t *data, unsigned int secondary)
int vdrive_iec_read (vdrive_t *vdrive, uint8_t *data, unsigned int secondary)
int vdrive_iec_write (vdrive_t *vdrive, uint8_t data, unsigned int secondary)
void vdrive_iec_flush (vdrive_t *vdrive, unsigned int secondary)
int vdrive_iec_attach (unsigned int unit, const char *name)
void vdrive_iec_listen (vdrive_t *vdrive, unsigned int secondary)
int vdrive_iec_update_dirent (vdrive_t *vdrive, unsigned int channel)
called by vdrive-rel
Variables
static log_t vdrive_iec_log = ((log_t)-1)
Macro Definition Documentation
DBG
#define DBG (x)
OFFSET_RECORD_LEN
#define OFFSET_RECORD_LEN 3
OFFSET_SUPER_POINTER
#define OFFSET_SUPER_POINTER 3
SIDE_SECTORS_MAX
#define SIDE_SECTORS_MAX 6
Function Documentation
iec_close_sequential()
static int iec_close_sequential (vdrive_t * vdrive, unsigned int secondary) static
Referenced by vdrive_iec_close().
iec_open_read()
static int iec_open_read (vdrive_t * vdrive, unsigned int secondary) static
Referenced by vdrive_iec_open().
iec_open_read_directory()
static int iec_open_read_directory (vdrive_t * vdrive, unsigned int secondary, cbmdos_cmd_parse_plus_t * cmd_parse) static
Referenced by vdrive_iec_open().
iec_open_read_sequential()
static int iec_open_read_sequential (vdrive_t * vdrive, unsigned int secondary, unsigned int track, unsigned int sector) static
Referenced by iec_open_read(), and iec_open_read_directory().
iec_open_write()
static int iec_open_write (vdrive_t * vdrive, unsigned int secondary, cbmdos_cmd_parse_plus_t * cmd_parse) static
< 1581
Todo:
FIXME: should we unallocate the block we just reserved?
Referenced by vdrive_iec_open().
iec_read_sequential()
static int iec_read_sequential (vdrive_t * vdrive, uint8_t * data, unsigned int secondary) static
Referenced by vdrive_iec_read().
iec_write_sequential()
static int iec_write_sequential (vdrive_t * vdrive, bufferinfo_t * bi, int length) static
< 1581
vdrive_command_set_error(vdrive, CBMDOS_IPE_DISK_FULL, 0, 0);
< 1581
vdrive_command_set_error(vdrive, CBMDOS_IPE_DISK_FULL, 0, 0);
Referenced by iec_close_sequential(), and vdrive_iec_write().
vdrive_iec_attach()
int vdrive_iec_attach (unsigned int unit, const char * name)
Referenced by file_system_set_serial_hooks().
vdrive_iec_close()
int vdrive_iec_close (vdrive_t * vdrive, unsigned int secondary)
Todo:
FIXME: Is this correct?
vdrive_close_all_channels(vdrive);
Referenced by autostart_prg_with_disk_image(), iec_open_read(), iec_open_read_sequential(), iec_open_write(), mon_file_close(), vdrive_close_all_channels(), vdrive_close_all_channels_partition(), and vdrive_iec_attach().
vdrive_iec_flush()
void vdrive_iec_flush (vdrive_t * vdrive, unsigned int secondary)
Referenced by vdrive_iec_attach().
vdrive_iec_init()
void vdrive_iec_init (void)
Referenced by vdrive_init().
vdrive_iec_listen()
void vdrive_iec_listen (vdrive_t * vdrive, unsigned int secondary)
Referenced by vdrive_iec_attach().
vdrive_iec_open()
int vdrive_iec_open (struct vdrive_s * vdrive, const uint8_t * name, unsigned int length, unsigned int secondary, struct cbmdos_cmd_parse_s * cmd_parse_ext)
Generic IEC interface.
Todo:
FIXME: "file" has requested buffer
< should match FILEIO_TYPE_xxx
< should match FILEIO_TYPE_xxx
< for relative files
< for relative files
Referenced by autostart_prg_with_disk_image(), mon_file_open(), and vdrive_iec_attach().
vdrive_iec_read()
int vdrive_iec_read (vdrive_t * vdrive, uint8_t * data, unsigned int secondary)
Referenced by mon_file_read(), and vdrive_iec_attach().
vdrive_iec_switch()
int vdrive_iec_switch (vdrive_t * vdrive, bufferinfo_t * p)
< directory sector number
vdrive_bam_read_bam(vdrive);
Referenced by iec_close_sequential(), iec_open_read_directory(), iec_read_sequential(), vdrive_dir_next_directory(), vdrive_iec_write(), vdrive_rel_close(), vdrive_rel_listen(), vdrive_rel_position(), vdrive_rel_read(), and vdrive_rel_write().
vdrive_iec_update_dirent()
int vdrive_iec_update_dirent (vdrive_t * vdrive, unsigned int channel)
called by vdrive-rel
Referenced by iec_close_sequential(), vdrive_rel_add_sector(), and vdrive_rel_grow().
vdrive_iec_write()
int vdrive_iec_write (vdrive_t * vdrive, uint8_t data, unsigned int secondary)
Referenced by autostart_prg_with_disk_image(), mon_file_write(), vdrive_iec_attach(), and vdrive_iec_open().
Variable Documentation
vdrive_iec_log
log_t vdrive_iec_log = ((log_t)-1) static
Referenced by vdrive_iec_close(), vdrive_iec_init(), vdrive_iec_open(), vdrive_iec_read(), and vdrive_iec_write().