vsid: arch/gtk3/widgets/logfilewidget.c File Reference
logfilewidget.c File Reference
Widget to set the log file.
#include "vice.h"
#include <gtk/gtk.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "ui.h"
#include "vice_gtk3.h"
#include "logfilewidget.h"
Functions
static void on_logfile_entry_changed (GtkWidget *entry, gpointer check)
Handler for the 'changed' event of the entry.
static void on_stdout_check_toggled (GtkWidget *check, gpointer chooser)
Handler for the 'toggled' event of the check button.
static void on_launcher_clicked (GtkWidget *button, gpointer data)
Open directory containing the log file.
static GtkWidget * label_helper (const char *text)
Create left-aligned label with Pango markup.
GtkWidget * logfile_widget_create (void)
Create widget to set the LogFileName resource.
Variables
static gulong check_handler = 0
ID of the 'changed' signal handler of the "stdout" check button.
static GtkWidget * launcher = NULL
Button to open a file manager in the logfile directory.
Detailed Description
Widget to set the log file.
/author Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
label_helper()
static GtkWidget * label_helper (const char * text) static
Create left-aligned label with Pango markup.
Parameters
[in] text label text, can contain Pango markup
Returns
GtkLabel
Referenced by logfile_widget_create().
logfile_widget_create()
GtkWidget * logfile_widget_create (void)
Create widget to set the LogFileName resource.
Returns
GtkGrid
Referenced by settings_environment_widget_create().
on_launcher_clicked()
static void on_launcher_clicked (GtkWidget * button, gpointer data) static
Open directory containing the log file.
Parameters
[in] button button (unused)
[in] data extra event data (unused)
Referenced by logfile_widget_create().
on_logfile_entry_changed()
static void on_logfile_entry_changed (GtkWidget * entry, gpointer check) static
Handler for the 'changed' event of the entry.
Set check state depending on whether entry contains "-".
Parameters
[in] entry GtkEntry containing the LogFileName contents
[in] check GtkCheckButton for "log to stdout"
Referenced by logfile_widget_create().
on_stdout_check_toggled()
static void on_stdout_check_toggled (GtkWidget * check, gpointer chooser) static
Handler for the 'toggled' event of the check button.
Set browser contents to "-" when check is toggled on, clear browser contents when check is toggled off.
Parameters
[in] check GtkCheckButton for "log to stdout"
[in] chooser resource file chooser containing the LogFileName contents
Referenced by logfile_widget_create().
Variable Documentation
check_handler
gulong check_handler = 0 static
ID of the 'changed' signal handler of the "stdout" check button.
This ID is used to temporarily block the signal to avoid signal handlers of the check button and the text entry triggering each other.
Referenced by logfile_widget_create(), and on_logfile_entry_changed().
launcher
GtkWidget* launcher = NULL static
Button to open a file manager in the logfile directory.
Referenced by logfile_widget_create(), and on_logfile_entry_changed().