vsid: diskimage/fsimage-dxx.c File Reference
fsimage-dxx.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "diskconstants.h"
#include "diskimage.h"
#include "drive.h"
#include "cbmdos.h"
#include "fsimage-dxx.h"
#include "fsimage.h"
#include "gcr.h"
#include "log.h"
#include "lib.h"
#include "types.h"
#include "util.h"
#include "x64.h"
Functions
int fsimage_dxx_write_half_track (disk_image_t *image, unsigned int half_track, const disk_track_t *raw)
int fsimage_read_dxx_image (const disk_image_t *image)
int fsimage_dxx_read_sector (const disk_image_t *image, uint8_t *buf, const disk_addr_t *dadr)
int fsimage_dxx_write_sector (disk_image_t *image, const uint8_t *buf, const disk_addr_t *dadr)
void fsimage_dxx_init (void)
Variables
static log_t fsimage_dxx_log = ((log_t)-1)
Function Documentation
fsimage_dxx_init()
void fsimage_dxx_init (void)
Referenced by fsimage_init().
fsimage_dxx_read_sector()
int fsimage_dxx_read_sector (const disk_image_t * image, uint8_t * buf, const disk_addr_t * dadr)
Referenced by fsimage_read_sector().
fsimage_dxx_write_half_track()
int fsimage_dxx_write_half_track (disk_image_t * image, unsigned int half_track, const disk_track_t * raw)
Referenced by disk_image_write_half_track().
fsimage_dxx_write_sector()
int fsimage_dxx_write_sector (disk_image_t * image, const uint8_t * buf, const disk_addr_t * dadr)
Referenced by fsimage_write_sector().
fsimage_read_dxx_image()
int fsimage_read_dxx_image (const disk_image_t * image)
< pos. of disk id in header blk
< 1541 BAM track number
< 1541 BAM sector number
< offset in BAM of the disk ID in PETSCII, 2 bytes for standard DOS
< BAM track number (side 1 BAM)
< BAM sector number (side 1 BAM)
< offset in BAM of the disk ID in PETSCII, 2 bytes
< offset in BAM of the disk ID in PETSCII, 2 bytes
< offset in BAM of the disk ID in PETSCII, 2 bytes
< offset in BAM of the disk ID in PETSCII, 2 bytes
Referenced by disk_image_read_image().
Variable Documentation
fsimage_dxx_log
log_t fsimage_dxx_log = ((log_t)-1) static
Referenced by fsimage_dxx_init(), fsimage_dxx_read_sector(), fsimage_dxx_write_half_track(), and fsimage_dxx_write_sector().