vsid: core/scsi.h File Reference
scsi.h File Reference
#include "types.h"
Data Structures
struct scsi_context_s
Macros
#define SCSI_STATE_DATAOUT 0x00
#define SCSI_STATE_DATAIN 0x01
#define SCSI_STATE_COMMAND 0x02
#define SCSI_STATE_STATUS 0x03
#define SCSI_STATE_MESSAGEOUT 0x04
#define SCSI_STATE_MESSAGEIN 0x05
#define SCSI_STATE_BUSFREE 0x10
#define SCSI_STATE_SELECTION 0x20
#define SCSI_STATUS_GOOD 0x00
will be bitshifted left by 1 before sent: see table 14-2 of scsi spec
#define SCSI_STATUS_CHECKCONDITION 0x01
#define SCSI_STATUS_CONDITIONMET 0x02
#define SCSI_STATUS_BUSY 0x04
#define SCSI_STATUS_INTERMEDIATE 0x08
#define SCSI_STATUS_INTERMEDIATECONDITIONMET 0x0A
#define SCSI_STATUS_RESERVATIONCONFLICT 0x0C
#define SCSI_STATUS_COMMANDTERMINATED 0x11
#define SCSI_STATUS_QUEUEFULL 0x14
#define SCSI_SENSEKEY_NOSENSE 0x00
#define SCSI_SENSEKEY_RECOVEREDERROR 0x01
#define SCSI_SENSEKEY_NOTREADY 0x02
#define SCSI_SENSEKEY_MEDIUMERROR 0x03
#define SCSI_SENSEKEY_HARDWAREERROR 0x04
#define SCSI_SENSEKEY_ILLEGALREQUEST 0x05
#define SCSI_SENSEKEY_UNITATTENTION 0x06
#define SCSI_SENSEKEY_DATAPROTECT 0x07
#define SCSI_SENSEKEY_BLANKCHECK 0x08
#define SCSI_SENSEKEY_VENDORSPECIFIC 0x09
#define SCSI_SENSEKEY_COPYABORTED 0x0a
#define SCSI_SENSEKEY_ABORTEDCOMMAND 0x0b
#define SCSI_SENSEKEY_EQUAL 0x0c
#define SCSI_SENSEKEY_VOLUMEOVERFLOW 0x0d
#define SCSI_SENSEKEY_MISCOMPARE 0x0e
#define SCSI_SENSEKEY_COMPLETED 0x0f
#define SCSI_SASC_LOGICALBLOCKADDRESSOUTOFRANGE 0x21
#define SCSI_SASC_INVALIDFIELDINCDB 0x24
#define SCSI_SASC_INVALIDFIELDINPARAMETERLIST 0x26
#define SCSI_LOG_NODISK0 0x01
#define SCSI_COMMAND_TEST_UNIT_READY 0x00
#define SCSI_COMMAND_REZERO_UNIT 0x01
#define SCSI_COMMAND_REQUEST_SENSE 0x03
#define SCSI_COMMAND_FORMAT_UNIT 0x04
#define SCSI_COMMAND_REASSIGN_BLOCKS 0x07
#define SCSI_COMMAND_READ_6 0x08
#define SCSI_COMMAND_WRITE_6 0x0a
#define SCSI_COMMAND_INQUIRY 0x12
#define SCSI_COMMAND_MODE_SENSE 0x1a
#define SCSI_COMMAND_START_STOP 0x1b
#define SCSI_COMMAND_SEND_DIAGNOSTIC 0x1d
#define SCSI_COMMAND_READ_CAPACITY 0x25
#define SCSI_COMMAND_READ_10 0x28
#define SCSI_COMMAND_WRITE_10 0x2a
#define SCSI_COMMAND_VERIFY 0x2f
#define SCSI_COMMAND_MODE_SENSE_10 0x5a
#define SCSI_COMMAND_WRITE_VERIFY 0x2e
commands users have requested to be implemented
#define SCSI_COMMAND_READ_BLOCK_LIMITS 0x05
unimplemented commands
#define SCSI_COMMAND_SEEK_6 0x0b
#define SCSI_COMMAND_READ_REVERSE 0x0f
#define SCSI_COMMAND_WRITE_FILEMARKS 0x10
#define SCSI_COMMAND_SPACE 0x11
#define SCSI_COMMAND_RECOVER_BUFFERED_DATA 0x14
#define SCSI_COMMAND_MODE_SELECT 0x15
#define SCSI_COMMAND_RESERVE 0x16
#define SCSI_COMMAND_RELEASE 0x17
#define SCSI_COMMAND_COPY 0x18
#define SCSI_COMMAND_ERASE 0x19
#define SCSI_COMMAND_RECEIVE_DIAGNOSTIC 0x1c
#define SCSI_COMMAND_ALLOW_MEDIUM_REMOVAL 0x1e
#define SCSI_COMMAND_SET_WINDOW 0x24
#define SCSI_COMMAND_SEEK_10 0x2b
#define SCSI_COMMAND_SEARCH_HIGH 0x30
#define SCSI_COMMAND_SEARCH_EQUAL 0x31
#define SCSI_COMMAND_SEARCH_LOW 0x32
#define SCSI_COMMAND_SET_LIMITS 0x33
#define SCSI_COMMAND_PRE_FETCH 0x34
#define SCSI_COMMAND_READ_POSITION 0x34
#define SCSI_COMMAND_SYNCHRONIZE_CACHE 0x35
#define SCSI_COMMAND_LOCK_UNLOCK_CACHE 0x36
#define SCSI_COMMAND_READ_DEFECT_DATA 0x37
#define SCSI_COMMAND_MEDIUM_SCAN 0x38
#define SCSI_COMMAND_COMPARE 0x39
#define SCSI_COMMAND_COPY_VERIFY 0x3a
#define SCSI_COMMAND_WRITE_BUFFER 0x3b
#define SCSI_COMMAND_READ_BUFFER 0x3c
#define SCSI_COMMAND_UPDATE_BLOCK 0x3d
#define SCSI_COMMAND_READ_LONG 0x3e
#define SCSI_COMMAND_WRITE_LONG 0x3f
#define SCSI_COMMAND_CHANGE_DEFINITION 0x40
#define SCSI_COMMAND_WRITE_SAME 0x41
#define SCSI_COMMAND_READ_TOC 0x43
#define SCSI_COMMAND_LOG_SELECT 0x4c
#define SCSI_COMMAND_LOG_SENSE 0x4d
#define SCSI_COMMAND_MODE_SELECT_10 0x55
#define SCSI_COMMAND_RESERVE_10 0x56
#define SCSI_COMMAND_RELEASE_10 0x57
#define SCSI_COMMAND_PERSISTENT_RESERVE_IN 0x5e
#define SCSI_COMMAND_PERSISTENT_RESERVE_OUT 0x5f
#define SCSI_COMMAND_MOVE_MEDIUM 0xa5
#define SCSI_COMMAND_READ_12 0xa8
#define SCSI_COMMAND_WRITE_12 0xaa
#define SCSI_COMMAND_WRITE_VERIFY_12 0xae
#define SCSI_COMMAND_SEARCH_HIGH_12 0xb0
#define SCSI_COMMAND_SEARCH_EQUAL_12 0xb1
#define SCSI_COMMAND_SEARCH_LOW_12 0xb2
#define SCSI_COMMAND_READ_ELEMENT_STATUS 0xb8
#define SCSI_COMMAND_SEND_VOLUME_TAG 0xb6
#define SCSI_COMMAND_WRITE_LONG_2 0xea
Typedefs
typedef struct scsi_context_s scsi_context_t
Functions
int scsi_image_detach (struct scsi_context_s *context, int disk)
void scsi_image_detach_all (struct scsi_context_s *context)
int scsi_image_attach (struct scsi_context_s *context, int disk, char *filename)
int32_t scsi_image_read (struct scsi_context_s *context)
int32_t scsi_image_write (struct scsi_context_s *context)
uint8_t scsi_get_bus (struct scsi_context_s *context)
int scsi_set_bus (struct scsi_context_s *context, uint8_t value)
void scsi_process_noack (struct scsi_context_s *context)
void scsi_process_ack (struct scsi_context_s *context)
void scsi_reset (struct scsi_context_s *context)
int scsi_snapshot_write_module (struct scsi_context_s *context, snapshot_t *s)
int scsi_snapshot_read_module (struct scsi_context_s *context, snapshot_t *s)
Macro Definition Documentation
SCSI_COMMAND_ALLOW_MEDIUM_REMOVAL
#define SCSI_COMMAND_ALLOW_MEDIUM_REMOVAL 0x1e
SCSI_COMMAND_CHANGE_DEFINITION
#define SCSI_COMMAND_CHANGE_DEFINITION 0x40
SCSI_COMMAND_COMPARE
#define SCSI_COMMAND_COMPARE 0x39
SCSI_COMMAND_COPY
#define SCSI_COMMAND_COPY 0x18
SCSI_COMMAND_COPY_VERIFY
#define SCSI_COMMAND_COPY_VERIFY 0x3a
SCSI_COMMAND_ERASE
#define SCSI_COMMAND_ERASE 0x19
SCSI_COMMAND_FORMAT_UNIT
#define SCSI_COMMAND_FORMAT_UNIT 0x04
SCSI_COMMAND_INQUIRY
#define SCSI_COMMAND_INQUIRY 0x12
SCSI_COMMAND_LOCK_UNLOCK_CACHE
#define SCSI_COMMAND_LOCK_UNLOCK_CACHE 0x36
SCSI_COMMAND_LOG_SELECT
#define SCSI_COMMAND_LOG_SELECT 0x4c
SCSI_COMMAND_LOG_SENSE
#define SCSI_COMMAND_LOG_SENSE 0x4d
SCSI_COMMAND_MEDIUM_SCAN
#define SCSI_COMMAND_MEDIUM_SCAN 0x38
SCSI_COMMAND_MODE_SELECT
#define SCSI_COMMAND_MODE_SELECT 0x15
SCSI_COMMAND_MODE_SELECT_10
#define SCSI_COMMAND_MODE_SELECT_10 0x55
SCSI_COMMAND_MODE_SENSE
#define SCSI_COMMAND_MODE_SENSE 0x1a
SCSI_COMMAND_MODE_SENSE_10
#define SCSI_COMMAND_MODE_SENSE_10 0x5a
SCSI_COMMAND_MOVE_MEDIUM
#define SCSI_COMMAND_MOVE_MEDIUM 0xa5
SCSI_COMMAND_PERSISTENT_RESERVE_IN
#define SCSI_COMMAND_PERSISTENT_RESERVE_IN 0x5e
SCSI_COMMAND_PERSISTENT_RESERVE_OUT
#define SCSI_COMMAND_PERSISTENT_RESERVE_OUT 0x5f
SCSI_COMMAND_PRE_FETCH
#define SCSI_COMMAND_PRE_FETCH 0x34
SCSI_COMMAND_READ_10
#define SCSI_COMMAND_READ_10 0x28
SCSI_COMMAND_READ_12
#define SCSI_COMMAND_READ_12 0xa8
SCSI_COMMAND_READ_6
#define SCSI_COMMAND_READ_6 0x08
SCSI_COMMAND_READ_BLOCK_LIMITS
#define SCSI_COMMAND_READ_BLOCK_LIMITS 0x05
unimplemented commands
SCSI_COMMAND_READ_BUFFER
#define SCSI_COMMAND_READ_BUFFER 0x3c
SCSI_COMMAND_READ_CAPACITY
#define SCSI_COMMAND_READ_CAPACITY 0x25
SCSI_COMMAND_READ_DEFECT_DATA
#define SCSI_COMMAND_READ_DEFECT_DATA 0x37
SCSI_COMMAND_READ_ELEMENT_STATUS
#define SCSI_COMMAND_READ_ELEMENT_STATUS 0xb8
SCSI_COMMAND_READ_LONG
#define SCSI_COMMAND_READ_LONG 0x3e
SCSI_COMMAND_READ_POSITION
#define SCSI_COMMAND_READ_POSITION 0x34
SCSI_COMMAND_READ_REVERSE
#define SCSI_COMMAND_READ_REVERSE 0x0f
SCSI_COMMAND_READ_TOC
#define SCSI_COMMAND_READ_TOC 0x43
SCSI_COMMAND_REASSIGN_BLOCKS
#define SCSI_COMMAND_REASSIGN_BLOCKS 0x07
SCSI_COMMAND_RECEIVE_DIAGNOSTIC
#define SCSI_COMMAND_RECEIVE_DIAGNOSTIC 0x1c
SCSI_COMMAND_RECOVER_BUFFERED_DATA
#define SCSI_COMMAND_RECOVER_BUFFERED_DATA 0x14
SCSI_COMMAND_RELEASE
#define SCSI_COMMAND_RELEASE 0x17
SCSI_COMMAND_RELEASE_10
#define SCSI_COMMAND_RELEASE_10 0x57
SCSI_COMMAND_REQUEST_SENSE
#define SCSI_COMMAND_REQUEST_SENSE 0x03
SCSI_COMMAND_RESERVE
#define SCSI_COMMAND_RESERVE 0x16
SCSI_COMMAND_RESERVE_10
#define SCSI_COMMAND_RESERVE_10 0x56
SCSI_COMMAND_REZERO_UNIT
#define SCSI_COMMAND_REZERO_UNIT 0x01
SCSI_COMMAND_SEARCH_EQUAL
#define SCSI_COMMAND_SEARCH_EQUAL 0x31
SCSI_COMMAND_SEARCH_EQUAL_12
#define SCSI_COMMAND_SEARCH_EQUAL_12 0xb1
SCSI_COMMAND_SEARCH_HIGH
#define SCSI_COMMAND_SEARCH_HIGH 0x30
SCSI_COMMAND_SEARCH_HIGH_12
#define SCSI_COMMAND_SEARCH_HIGH_12 0xb0
SCSI_COMMAND_SEARCH_LOW
#define SCSI_COMMAND_SEARCH_LOW 0x32
SCSI_COMMAND_SEARCH_LOW_12
#define SCSI_COMMAND_SEARCH_LOW_12 0xb2
SCSI_COMMAND_SEEK_10
#define SCSI_COMMAND_SEEK_10 0x2b
SCSI_COMMAND_SEEK_6
#define SCSI_COMMAND_SEEK_6 0x0b
SCSI_COMMAND_SEND_DIAGNOSTIC
#define SCSI_COMMAND_SEND_DIAGNOSTIC 0x1d
SCSI_COMMAND_SEND_VOLUME_TAG
#define SCSI_COMMAND_SEND_VOLUME_TAG 0xb6
SCSI_COMMAND_SET_LIMITS
#define SCSI_COMMAND_SET_LIMITS 0x33
SCSI_COMMAND_SET_WINDOW
#define SCSI_COMMAND_SET_WINDOW 0x24
SCSI_COMMAND_SPACE
#define SCSI_COMMAND_SPACE 0x11
SCSI_COMMAND_START_STOP
#define SCSI_COMMAND_START_STOP 0x1b
SCSI_COMMAND_SYNCHRONIZE_CACHE
#define SCSI_COMMAND_SYNCHRONIZE_CACHE 0x35
SCSI_COMMAND_TEST_UNIT_READY
#define SCSI_COMMAND_TEST_UNIT_READY 0x00
SCSI_COMMAND_UPDATE_BLOCK
#define SCSI_COMMAND_UPDATE_BLOCK 0x3d
SCSI_COMMAND_VERIFY
#define SCSI_COMMAND_VERIFY 0x2f
SCSI_COMMAND_WRITE_10
#define SCSI_COMMAND_WRITE_10 0x2a
SCSI_COMMAND_WRITE_12
#define SCSI_COMMAND_WRITE_12 0xaa
SCSI_COMMAND_WRITE_6
#define SCSI_COMMAND_WRITE_6 0x0a
SCSI_COMMAND_WRITE_BUFFER
#define SCSI_COMMAND_WRITE_BUFFER 0x3b
SCSI_COMMAND_WRITE_FILEMARKS
#define SCSI_COMMAND_WRITE_FILEMARKS 0x10
SCSI_COMMAND_WRITE_LONG
#define SCSI_COMMAND_WRITE_LONG 0x3f
SCSI_COMMAND_WRITE_LONG_2
#define SCSI_COMMAND_WRITE_LONG_2 0xea
SCSI_COMMAND_WRITE_SAME
#define SCSI_COMMAND_WRITE_SAME 0x41
SCSI_COMMAND_WRITE_VERIFY
#define SCSI_COMMAND_WRITE_VERIFY 0x2e
commands users have requested to be implemented
SCSI_COMMAND_WRITE_VERIFY_12
#define SCSI_COMMAND_WRITE_VERIFY_12 0xae
SCSI_LOG_NODISK0
#define SCSI_LOG_NODISK0 0x01
SCSI_SASC_INVALIDFIELDINCDB
#define SCSI_SASC_INVALIDFIELDINCDB 0x24
SCSI_SASC_INVALIDFIELDINPARAMETERLIST
#define SCSI_SASC_INVALIDFIELDINPARAMETERLIST 0x26
SCSI_SASC_LOGICALBLOCKADDRESSOUTOFRANGE
#define SCSI_SASC_LOGICALBLOCKADDRESSOUTOFRANGE 0x21
SCSI_SENSEKEY_ABORTEDCOMMAND
#define SCSI_SENSEKEY_ABORTEDCOMMAND 0x0b
SCSI_SENSEKEY_BLANKCHECK
#define SCSI_SENSEKEY_BLANKCHECK 0x08
SCSI_SENSEKEY_COMPLETED
#define SCSI_SENSEKEY_COMPLETED 0x0f
SCSI_SENSEKEY_COPYABORTED
#define SCSI_SENSEKEY_COPYABORTED 0x0a
SCSI_SENSEKEY_DATAPROTECT
#define SCSI_SENSEKEY_DATAPROTECT 0x07
SCSI_SENSEKEY_EQUAL
#define SCSI_SENSEKEY_EQUAL 0x0c
SCSI_SENSEKEY_HARDWAREERROR
#define SCSI_SENSEKEY_HARDWAREERROR 0x04
SCSI_SENSEKEY_ILLEGALREQUEST
#define SCSI_SENSEKEY_ILLEGALREQUEST 0x05
SCSI_SENSEKEY_MEDIUMERROR
#define SCSI_SENSEKEY_MEDIUMERROR 0x03
SCSI_SENSEKEY_MISCOMPARE
#define SCSI_SENSEKEY_MISCOMPARE 0x0e
SCSI_SENSEKEY_NOSENSE
#define SCSI_SENSEKEY_NOSENSE 0x00
SCSI_SENSEKEY_NOTREADY
#define SCSI_SENSEKEY_NOTREADY 0x02
SCSI_SENSEKEY_RECOVEREDERROR
#define SCSI_SENSEKEY_RECOVEREDERROR 0x01
SCSI_SENSEKEY_UNITATTENTION
#define SCSI_SENSEKEY_UNITATTENTION 0x06
SCSI_SENSEKEY_VENDORSPECIFIC
#define SCSI_SENSEKEY_VENDORSPECIFIC 0x09
SCSI_SENSEKEY_VOLUMEOVERFLOW
#define SCSI_SENSEKEY_VOLUMEOVERFLOW 0x0d
SCSI_STATE_BUSFREE
#define SCSI_STATE_BUSFREE 0x10
SCSI_STATE_COMMAND
#define SCSI_STATE_COMMAND 0x02
SCSI_STATE_DATAIN
#define SCSI_STATE_DATAIN 0x01
SCSI_STATE_DATAOUT
#define SCSI_STATE_DATAOUT 0x00
SCSI_STATE_MESSAGEIN
#define SCSI_STATE_MESSAGEIN 0x05
SCSI_STATE_MESSAGEOUT
#define SCSI_STATE_MESSAGEOUT 0x04
SCSI_STATE_SELECTION
#define SCSI_STATE_SELECTION 0x20
SCSI_STATE_STATUS
#define SCSI_STATE_STATUS 0x03
SCSI_STATUS_BUSY
#define SCSI_STATUS_BUSY 0x04
SCSI_STATUS_CHECKCONDITION
#define SCSI_STATUS_CHECKCONDITION 0x01
SCSI_STATUS_COMMANDTERMINATED
#define SCSI_STATUS_COMMANDTERMINATED 0x11
SCSI_STATUS_CONDITIONMET
#define SCSI_STATUS_CONDITIONMET 0x02
SCSI_STATUS_GOOD
#define SCSI_STATUS_GOOD 0x00
will be bitshifted left by 1 before sent: see table 14-2 of scsi spec
SCSI_STATUS_INTERMEDIATE
#define SCSI_STATUS_INTERMEDIATE 0x08
SCSI_STATUS_INTERMEDIATECONDITIONMET
#define SCSI_STATUS_INTERMEDIATECONDITIONMET 0x0A
SCSI_STATUS_QUEUEFULL
#define SCSI_STATUS_QUEUEFULL 0x14
SCSI_STATUS_RESERVATIONCONFLICT
#define SCSI_STATUS_RESERVATIONCONFLICT 0x0C
Typedef Documentation
scsi_context_t
typedef struct scsi_context_s scsi_context_t
Function Documentation
scsi_get_bus()
uint8_t scsi_get_bus (struct scsi_context_s * context)
Referenced by read_pra9().
scsi_image_attach()
int scsi_image_attach (struct scsi_context_s * context, int disk, char * filename)
scsi_image_detach()
int scsi_image_detach (struct scsi_context_s * context, int disk)
Referenced by scsi_image_attach(), and scsi_image_detach_all().
scsi_image_detach_all()
void scsi_image_detach_all (struct scsi_context_s * context)
scsi_image_read()
int32_t scsi_image_read (struct scsi_context_s * context)
Referenced by cmdhd_scsiformat(), and scsi_process_ack().
scsi_image_write()
int32_t scsi_image_write (struct scsi_context_s * context)
Referenced by cmdhd_scsiformat(), scsi_format_sector0(), and scsi_process_ack().
scsi_process_ack()
void scsi_process_ack (struct scsi_context_s * context)
Limit size returned as some tools can't handle large disks
SCSI spec says return last accessable block number
CMD drive info tool looks at page 20h, so lets put that one in
Referenced by read_pra9(), and store_pra9().
scsi_process_noack()
void scsi_process_noack (struct scsi_context_s * context)
Referenced by read_pra9(), read_prb9(), scsi_reset(), set_pc(), store_pra9(), and store_prb9().
scsi_reset()
void scsi_reset (struct scsi_context_s * context)
Referenced by cmdhd_init().
scsi_set_bus()
int scsi_set_bus (struct scsi_context_s * context, uint8_t value)
Referenced by store_pra9().
scsi_snapshot_read_module()
int scsi_snapshot_read_module (struct scsi_context_s * context, snapshot_t * s)
Referenced by cmdhd_snapshot_read_module().
scsi_snapshot_write_module()
int scsi_snapshot_write_module (struct scsi_context_s * context, snapshot_t * s)
Referenced by cmdhd_snapshot_write_module().