vsid: tapeport/tapecart.c File Reference
tapecart.c File Reference
tapecart emulation
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "alarm.h"
#include "archdep.h"
#include "cmdline.h"
#include "crc32.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "resources.h"
#include "snapshot.h"
#include "tapeport.h"
#include "tapecart.h"
#include "tapecart-loader.h"
Data Structures
struct pulse_t
stream mode variables
struct tapecart_buffers_s
common data
Macros
#define TCRT_MAGIC_LEN 13
#define max(a, b) ((a) > (b) ? (a) : (b))
#define min(a, b) ((a) < (b) ? (a) : (b))
#define VICE_MACHINE_MASK (VICE_MACHINE_C64|VICE_MACHINE_C64SC|VICE_MACHINE_C128)
#define CBMPULSE_SHORT 0x30
tapecart-internal definitions and variables
#define CBMPULSE_MEDIUM 0x42
#define CBMPULSE_LONG 0x56
#define PULSE_CYCLES 8
#define SREG_MAGIC_VALUE_FASTLOAD 0xca65
trigger values for mode changes
#define SREG_MAGIC_VALUE_COMMAND 0xfce2
#define FLASH_PAGE_SIZE 256
flash parameters
#define FLASH_ERASE_SIZE 4096
#define TCRT_VERSION 1
TCRT handling
#define TCRT_SIGNATURE_SIZE 16
#define TCRT_OFFSET_VERSION 16
#define TCRT_OFFSET_DATAADDR 18
#define TCRT_OFFSET_DATALENGTH 20
#define TCRT_OFFSET_CALLADDR 22
#define TCRT_OFFSET_FILENAME 24
#define TCRT_OFFSET_FLAGS 40
#define TCRT_FLAG_LOADERPRESENT 1
#define TCRT_FLAG_DATABLOCKOFFSET 2
#define TCRT_OFFSET_LOADER 41
#define TCRT_OFFSET_FLASHLENGTH 212
#define TCRT_OFFSET_FLASHDATA 216
#define TCRT_HEADER_SIZE TCRT_OFFSET_FLASHDATA
Typedefs
typedef clock_t(* wait_handler_t) (void)
typedef struct tapecart_buffers_s tapecart_buffers_t
common data
Enumerations
enum tapecart_mode_t {
MODE_UNINITIALIZED ,
MODE_STREAM ,
MODE_FASTLOAD ,
MODE_COMMAND ,
MODE_REINIT
}
tapecart major modes
enum tapesignal_t {
SIGNAL_MOTOR ,
SIGNAL_WRITE ,
SIGNAL_SENSE
}
enum fasttx_state_t {
FASTTX_INIT ,
FASTTX_WAIT_WRITE_HIGH ,
FASTTX_BITS_54 ,
FASTTX_BITS_76 ,
FASTTX_BITS_10 ,
FASTTX_BITS_32 ,
FASTTX_HOLD_DONE ,
FASTTX_WAIT_WRITE_LOW ,
FASTTX_BUSY_DELAY
}
fastload mode variables
enum command_t {
CMD_EXIT = 0 ,
CMD_READ_DEVICEINFO ,
CMD_READ_DEVICESIZES ,
CMD_READ_CAPABILITIES ,
CMD_READ_FLASH = 0x10 ,
CMD_READ_FLASH_FAST ,
CMD_WRITE_FLASH ,
CMD_WRITE_FLASH_FAST ,
CMD_ERASE_FLASH_64K ,
CMD_ERASE_FLASH_BLOCK ,
CMD_CRC32_FLASH ,
CMD_READ_LOADER = 0x20 ,
CMD_READ_LOADINFO ,
CMD_WRITE_LOADER ,
CMD_WRITE_LOADINFO ,
CMD_LED_OFF = 0x30 ,
CMD_LED_ON ,
CMD_READ_DEBUGFLAGS ,
CMD_WRITE_DEBUGFLAGS ,
CMD_DIR_SETPARAMS = 0x40 ,
CMD_DIR_LOOKUP
}
command mode variables
enum rx1bit_state_t {
RX1BIT_RECEIVE ,
RX1BIT_WAIT_WRITE_LOW ,
RX1BIT_WAIT_SENSE_HIGH ,
RX1BIT_WAIT_SENSE_LOW ,
RX1BIT_DELAY ,
RX1BIT_PROCESSING
}
enum tx1bit_state_t {
TX1BIT_PREPARE_SEND ,
TX1BIT_SEND ,
TX1BIT_WAIT_WRITE_LOW ,
TX1BIT_WAIT_WRITE_HIGH ,
TX1BIT_PROCESSING
}
enum statewait_t {
WAIT_NONE ,
WAIT_WRITE_LOW ,
WAIT_WRITE_HIGH ,
WAIT_SENSE_LOW ,
WAIT_SENSE_HIGH
}
callback system for waiting for specific signal levels
Functions
static void tapecart_shutdown (void)
a few forward declarations
static void tapecart_store_motor (int port, int state)
static void tapecart_store_write (int port, int state)
static void tapecart_store_sense (int port, int state)
static int tapecart_enable (int port, int val)
static int tapecart_write_snapshot (int port, struct snapshot_s *s, int write_image)
snapshots
static int tapecart_read_snapshot (int port, struct snapshot_s *s)
static void tapecart_pulse_alarm_handler (CLOCK offset, void *unused)
static void tapecart_logic_alarm_handler (CLOCK offset, void *unused)
static void tapecart_set_mode (tapecart_mode_t mode)
common fastload/command mode functions
static clock_t fasttx_byte_advance (void)
static clock_t cmdmode_receive_command (void)
static int load_tcrt (const char *filename, tapecart_memory_t *tcmem)
static void update_tcrt (void)
update TCRT if updates enabled and changes pending
static void set_sense (int value)
workaround for inverted tapeport functions to keep my sanity
static void set_write (int value)
static void clear_memory (tapecart_memory_t *memory)
command line and resource stuff
static int set_tapecart_update_tcrt (int value, void *unused_param)
static int set_tapecart_optimize_tcrt (int value, void *unused_param)
static int set_tapecart_loglevel (int value, void *unused_param)
int tapecart_resources_init (int amount)
int tapecart_cmdline_options_init (void)
static uint32_t get_u32_le (const uint8_t *buf)
endian-independent buffer access functions
static uint32_t get_u24_le (const uint8_t *buffer)
static uint16_t get_u16_le (const uint8_t *buffer)
static uint8_t * put_u32_le (uint8_t *buf, uint32_t value)
static uint8_t * put_u24_le (uint8_t *buf, uint32_t value)
static uint8_t * put_u16_le (uint8_t *buf, uint16_t value)
static int check_pulsebuffer_size (void)
static void pulse_store (const unsigned char pulselen)
static void pulse_store_sync (unsigned int length)
static void pulse_store_bit (const unsigned int index, const unsigned char bit)
static void pulse_store_byte (unsigned char byte)
static void construct_header (void)
static void construct_startvector (void)
static void construct_countdown (int repeat)
static void construct_datablock (void(*datafunc)(void))
static void construct_pulsestream (void)
static int get_next_pulse (void)
static clock_t fasttx_nibble_advance (void)
fastload mode functions
static clock_t fastload_complete (void)
static clock_t fastload_postdelay (void)
static clock_t transmit_fast (clock_t delay, uint8_t *buffer, unsigned int length, wait_handler_t complete_callback)
static clock_t fastload_mode_init (void)
static int validate_flashaddress (unsigned int address, unsigned int length)
command mode functions
static clock_t receive_1bit_callback (void)
static clock_t receive_1bit_delayed (void)
static clock_t receive_1bit (clock_t delay, uint8_t *buffer, unsigned int length, wait_handler_t complete_callback)
static clock_t transmit_1bit_callback (void)
static clock_t transmit_1bit_delayed (void)
static clock_t transmit_1bit (clock_t delay, uint8_t *buffer, unsigned int length, wait_handler_t complete_callback)
static clock_t cmd_read_flash (void)
static clock_t cmd_read_flash_fast (void)
static clock_t cmdmode_write_flash_page (void)
static clock_t cmd_write_flash (void)
static clock_t cmd_erase_flash_64k (void)
static clock_t cmd_erase_flash_block (void)
static clock_t cmd_crc32_flash (void)
static clock_t cmd_write_loadinfo (void)
static clock_t cmd_dir_setparams (void)
static clock_t cmd_dir_lookup (void)
static clock_t cmdmode_dispatch_command (void)
static clock_t cmdmode_send_pulses (void)
static clock_t command_mode_init (void)
static int save_tcrt (const char *filename, tapecart_memory_t *tcmem)
int tapecart_is_valid (const char *filename)
Check magic of the tapecart filename.
int tapecart_attach_tcrt (const char *filename, void *unused)
int tapecart_flush_tcrt (void)
Flush current tapecart data to image file.
void tapecart_exit (void)
Clean up memory used by the tapecart emulation.
Variables
static const char idstring [] = "TAPECART V1.0 W25QFLASH"
static int tapecart_enabled = 0
static int tapecart_update_tcrt = 0
static int tapecart_optimize_tcrt = 0
static int tapecart_loglevel = 0
static tapeport_device_t tapecart_device
static alarm_t * tapecart_logic_alarm
static alarm_t * tapecart_pulse_alarm
static log_t tapecart_log = ((log_t)-1)
static int motor_state
current physical state of tape port lines
static int write_state
static int sense_state
static const uint8_t tape_header []
first five bytes of the header block
static const uint8_t tape_startvector []
two-byte autostart address plus checksum
static pulse_t current_pulse
static unsigned int pulse_read_index
static unsigned int pulse_count
static unsigned int sense_pause_ticks
static unsigned short tapecart_shiftreg
static fasttx_state_t fasttx_state
static wait_handler_t transfer_complete
shared between fastload mode and command mode
static uint8_t transfer_buffer [((256) >(256) ?(256) :(256))]
256 bytes needed for dir_lookup
static uint8_t * transfer_ptr
static uint8_t transfer_byte
static unsigned int transfer_bit
static unsigned int transfer_remaining
static rx1bit_state_t rx1bit_state
static tx1bit_state_t tx1bit_state
static uint8_t tapecart_debugflags [2]
static unsigned int dir_base
static unsigned int dir_entries
static unsigned int dir_name_len
static unsigned int dir_data_len
static unsigned int flash_address
static unsigned int total_length
static unsigned int block_length
static clock_t flash_erase_64k_time
static clock_t flash_erase_page_time
static clock_t flash_page_write_time
static statewait_t wait_for_signal
static wait_handler_t wait_handler
static char * tcrt_filename
static tapecart_buffers_t * tapecart_buffers
static tapecart_memory_t * tapecart_memory
static tapecart_mode_t tapecart_mode = MODE_UNINITIALIZED
static tapecart_mode_t requested_mode = MODE_STREAM
static wait_handler_t alarm_trigger_callback
static const resource_int_t resources_int []
static const resource_string_t resources_string []
static const cmdline_option_t cmdline_options []
static unsigned int needed_space = 0
stream mode functions
const uint8_t tcrt_signature [16]
static const unsigned char default_loader [171]
the default tapecart loader, in case it isn't included in the TCRT file
Detailed Description
tapecart emulation
Author
Ingo Korb ingo@.nosp@m.akan.nosp@m.a.de
based on sense-dongle.c by Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Macro Definition Documentation
CBMPULSE_LONG
#define CBMPULSE_LONG 0x56
CBMPULSE_MEDIUM
#define CBMPULSE_MEDIUM 0x42
CBMPULSE_SHORT
#define CBMPULSE_SHORT 0x30
tapecart-internal definitions and variables
nominal TAP pulse lengths
FLASH_ERASE_SIZE
#define FLASH_ERASE_SIZE 4096
FLASH_PAGE_SIZE
#define FLASH_PAGE_SIZE 256
flash parameters
max
#define max (a, b) ((a) > (b) ? (a) : (b))
min
#define min (a, b) ((a) < (b) ? (a) : (b))
PULSE_CYCLES
#define PULSE_CYCLES 8
SREG_MAGIC_VALUE_COMMAND
#define SREG_MAGIC_VALUE_COMMAND 0xfce2
SREG_MAGIC_VALUE_FASTLOAD
#define SREG_MAGIC_VALUE_FASTLOAD 0xca65
trigger values for mode changes
TCRT_FLAG_DATABLOCKOFFSET
#define TCRT_FLAG_DATABLOCKOFFSET 2
TCRT_FLAG_LOADERPRESENT
#define TCRT_FLAG_LOADERPRESENT 1
TCRT_HEADER_SIZE
#define TCRT_HEADER_SIZE TCRT_OFFSET_FLASHDATA
TCRT_MAGIC_LEN
#define TCRT_MAGIC_LEN 13
TCRT_OFFSET_CALLADDR
#define TCRT_OFFSET_CALLADDR 22
TCRT_OFFSET_DATAADDR
#define TCRT_OFFSET_DATAADDR 18
TCRT_OFFSET_DATALENGTH
#define TCRT_OFFSET_DATALENGTH 20
TCRT_OFFSET_FILENAME
#define TCRT_OFFSET_FILENAME 24
TCRT_OFFSET_FLAGS
#define TCRT_OFFSET_FLAGS 40
TCRT_OFFSET_FLASHDATA
#define TCRT_OFFSET_FLASHDATA 216
TCRT_OFFSET_FLASHLENGTH
#define TCRT_OFFSET_FLASHLENGTH 212
TCRT_OFFSET_LOADER
#define TCRT_OFFSET_LOADER 41
TCRT_OFFSET_VERSION
#define TCRT_OFFSET_VERSION 16
TCRT_SIGNATURE_SIZE
#define TCRT_SIGNATURE_SIZE 16
TCRT_VERSION
#define TCRT_VERSION 1
TCRT handling
VICE_MACHINE_MASK
#define VICE_MACHINE_MASK (VICE_MACHINE_C64|VICE_MACHINE_C64SC|VICE_MACHINE_C128)
Typedef Documentation
tapecart_buffers_t
typedef struct tapecart_buffers_s tapecart_buffers_t
common data
semi-memory-intensive data that is only allocated when tapecart is enabled
wait_handler_t
typedef clock_t(* wait_handler_t) (void)
Enumeration Type Documentation
command_t
enum command_t
command mode variables
Enumerator
CMD_EXIT
CMD_READ_DEVICEINFO
CMD_READ_DEVICESIZES
CMD_READ_CAPABILITIES
CMD_READ_FLASH
CMD_READ_FLASH_FAST
CMD_WRITE_FLASH
CMD_WRITE_FLASH_FAST
CMD_ERASE_FLASH_64K
CMD_ERASE_FLASH_BLOCK
CMD_CRC32_FLASH
CMD_READ_LOADER
CMD_READ_LOADINFO
CMD_WRITE_LOADER
CMD_WRITE_LOADINFO
CMD_LED_OFF
CMD_LED_ON
CMD_READ_DEBUGFLAGS
CMD_WRITE_DEBUGFLAGS
CMD_DIR_SETPARAMS
CMD_DIR_LOOKUP
fasttx_state_t
enum fasttx_state_t
fastload mode variables
state list for 2-bit transmission
Enumerator
FASTTX_INIT
FASTTX_WAIT_WRITE_HIGH
FASTTX_BITS_54
FASTTX_BITS_76
FASTTX_BITS_10
FASTTX_BITS_32
FASTTX_HOLD_DONE
FASTTX_WAIT_WRITE_LOW
FASTTX_BUSY_DELAY
rx1bit_state_t
enum rx1bit_state_t
Enumerator
RX1BIT_RECEIVE
RX1BIT_WAIT_WRITE_LOW
RX1BIT_WAIT_SENSE_HIGH
RX1BIT_WAIT_SENSE_LOW
RX1BIT_DELAY
RX1BIT_PROCESSING
statewait_t
enum statewait_t
callback system for waiting for specific signal levels
Enumerator
WAIT_NONE
WAIT_WRITE_LOW
WAIT_WRITE_HIGH
WAIT_SENSE_LOW
WAIT_SENSE_HIGH
tapecart_mode_t
enum tapecart_mode_t
tapecart major modes
Enumerator
MODE_UNINITIALIZED
MODE_STREAM
MODE_FASTLOAD
MODE_COMMAND
MODE_REINIT
tapesignal_t
enum tapesignal_t
Enumerator
SIGNAL_MOTOR
SIGNAL_WRITE
SIGNAL_SENSE
tx1bit_state_t
enum tx1bit_state_t
Enumerator
TX1BIT_PREPARE_SEND
TX1BIT_SEND
TX1BIT_WAIT_WRITE_LOW
TX1BIT_WAIT_WRITE_HIGH
TX1BIT_PROCESSING
Function Documentation
check_pulsebuffer_size()
static int check_pulsebuffer_size (void) static
Referenced by pulse_store(), and pulse_store_sync().
clear_memory()
static void clear_memory (tapecart_memory_t * memory) static
command line and resource stuff
Referenced by tapecart_attach_tcrt(), and tapecart_enable().
cmd_crc32_flash()
static clock_t cmd_crc32_flash (void) static
Referenced by cmdmode_dispatch_command().
cmd_dir_lookup()
static clock_t cmd_dir_lookup (void) static
Referenced by cmdmode_dispatch_command().
cmd_dir_setparams()
static clock_t cmd_dir_setparams (void) static
Referenced by cmdmode_dispatch_command().
cmd_erase_flash_64k()
static clock_t cmd_erase_flash_64k (void) static
Referenced by cmdmode_dispatch_command().
cmd_erase_flash_block()
static clock_t cmd_erase_flash_block (void) static
Referenced by cmdmode_dispatch_command().
cmd_read_flash()
static clock_t cmd_read_flash (void) static
Referenced by cmdmode_dispatch_command().
cmd_read_flash_fast()
static clock_t cmd_read_flash_fast (void) static
Referenced by cmdmode_dispatch_command().
cmd_write_flash()
static clock_t cmd_write_flash (void) static
Referenced by cmdmode_dispatch_command().
cmd_write_loadinfo()
static clock_t cmd_write_loadinfo (void) static
Referenced by cmdmode_dispatch_command().
cmdmode_dispatch_command()
static clock_t cmdmode_dispatch_command (void) static
Referenced by cmdmode_receive_command().
cmdmode_receive_command()
static clock_t cmdmode_receive_command (void) static
Referenced by cmd_crc32_flash(), cmd_dir_lookup(), cmd_dir_setparams(), cmd_erase_flash_64k(), cmd_erase_flash_block(), cmd_read_flash(), cmd_read_flash_fast(), cmd_write_loadinfo(), cmdmode_dispatch_command(), cmdmode_send_pulses(), and cmdmode_write_flash_page().
cmdmode_send_pulses()
static clock_t cmdmode_send_pulses (void) static
Referenced by cmdmode_send_pulses(), and command_mode_init().
cmdmode_write_flash_page()
static clock_t cmdmode_write_flash_page (void) static
Referenced by cmd_write_flash(), and cmdmode_write_flash_page().
command_mode_init()
static clock_t command_mode_init (void) static
Referenced by tapecart_set_mode().
construct_countdown()
static void construct_countdown (int repeat) static
Referenced by construct_datablock().
construct_datablock()
static void construct_datablock (void(*)(void) datafunc) static
Referenced by construct_pulsestream().
construct_header()
static void construct_header (void) static
Referenced by construct_pulsestream().
construct_pulsestream()
static void construct_pulsestream (void) static
Referenced by tapecart_set_mode().
construct_startvector()
static void construct_startvector (void) static
Referenced by construct_pulsestream().
fastload_complete()
static clock_t fastload_complete (void) static
Referenced by fastload_postdelay().
fastload_mode_init()
static clock_t fastload_mode_init (void) static
Referenced by tapecart_set_mode().
fastload_postdelay()
static clock_t fastload_postdelay (void) static
Referenced by fastload_mode_init().
fasttx_byte_advance()
static clock_t fasttx_byte_advance (void) static
Referenced by fasttx_nibble_advance().
fasttx_nibble_advance()
static clock_t fasttx_nibble_advance (void) static
fastload mode functions
common fasttx for fastload mode and READ_FLASH_FAST
Todo:
FIXME: This assumes that 1 cycle == 1 microsecond
Referenced by fasttx_byte_advance(), fasttx_nibble_advance(), and transmit_fast().
get_next_pulse()
static int get_next_pulse (void) static
Referenced by tapecart_pulse_alarm_handler(), and tapecart_set_mode().
get_u16_le()
static uint16_t get_u16_le (const uint8_t * buffer) static
Referenced by cmd_dir_setparams(), cmd_read_flash(), cmd_read_flash_fast(), cmd_write_flash(), cmd_write_loadinfo(), and load_tcrt().
get_u24_le()
static uint32_t get_u24_le (const uint8_t * buffer) static
Referenced by cmd_crc32_flash(), cmd_dir_setparams(), cmd_erase_flash_64k(), cmd_erase_flash_block(), cmd_read_flash(), cmd_read_flash_fast(), and cmd_write_flash().
get_u32_le()
static uint32_t get_u32_le (const uint8_t * buf) static
endian-independent buffer access functions
Referenced by load_tcrt().
load_tcrt()
static int load_tcrt (const char * filename, tapecart_memory_t * tcmem) static
< read mode (binary)
Referenced by tapecart_attach_tcrt(), and tapecart_enable().
pulse_store()
static void pulse_store (const unsigned char pulselen) static
Referenced by construct_datablock(), pulse_store_bit(), and pulse_store_byte().
pulse_store_bit()
static void pulse_store_bit (const unsigned int index, const unsigned char bit) static
Referenced by pulse_store_byte().
pulse_store_byte()
static void pulse_store_byte (unsigned char byte) static
Referenced by construct_countdown(), construct_header(), and construct_startvector().
pulse_store_sync()
static void pulse_store_sync (unsigned int length) static
Referenced by construct_datablock(), and construct_pulsestream().
put_u16_le()
static uint8_t * put_u16_le (uint8_t * buf, uint16_t value) static
Referenced by cmdmode_dispatch_command(), fastload_mode_init(), and save_tcrt().
put_u24_le()
static uint8_t * put_u24_le (uint8_t * buf, uint32_t value) static
Referenced by cmdmode_dispatch_command().
put_u32_le()
static uint8_t * put_u32_le (uint8_t * buf, uint32_t value) static
Referenced by cmd_crc32_flash(), and save_tcrt().
receive_1bit()
static clock_t receive_1bit (clock_t delay, uint8_t * buffer, unsigned int length, wait_handler_t complete_callback) static
Referenced by cmd_write_flash(), cmdmode_dispatch_command(), cmdmode_receive_command(), and cmdmode_write_flash_page().
receive_1bit_callback()
static clock_t receive_1bit_callback (void) static
Referenced by receive_1bit(), and receive_1bit_callback().
receive_1bit_delayed()
static clock_t receive_1bit_delayed (void) static
Referenced by receive_1bit().
save_tcrt()
static int save_tcrt (const char * filename, tapecart_memory_t * tcmem) static
< write mode (binary)
Referenced by tapecart_flush_tcrt(), and update_tcrt().
set_sense()
static void set_sense (int value) static
workaround for inverted tapeport functions to keep my sanity
Referenced by command_mode_init(), fasttx_nibble_advance(), receive_1bit(), receive_1bit_callback(), receive_1bit_delayed(), tapecart_enable(), tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), tapecart_set_mode(), transmit_1bit(), transmit_1bit_callback(), and transmit_1bit_delayed().
set_tapecart_loglevel()
static int set_tapecart_loglevel (int value, void * unused_param) static
set_tapecart_optimize_tcrt()
static int set_tapecart_optimize_tcrt (int value, void * unused_param) static
set_tapecart_update_tcrt()
static int set_tapecart_update_tcrt (int value, void * unused_param) static
set_write()
static void set_write (int value) static
Referenced by fasttx_nibble_advance().
tapecart_attach_tcrt()
int tapecart_attach_tcrt (const char * filename, void * unused)
Referenced by autostart_tapecart(), and try_attach_tapecart().
tapecart_cmdline_options_init()
int tapecart_cmdline_options_init (void)
Referenced by tapeport_devices_cmdline_options_init().
tapecart_enable()
static int tapecart_enable (int port, int val) static
tapecart_exit()
void tapecart_exit (void)
Clean up memory used by the tapecart emulation.
trct_filename is allocated even when the tapecart is disabled, but never freed. This will clean up the memory used by the filename. Also, tapecart_memory and tapecart_buffers weren't properly freed.
And yes, I know we use ${module}_shutdown() as the name for a cleanup function, but tapecart_shutdown is already taken.
Referenced by machine_resources_shutdown().
tapecart_flush_tcrt()
int tapecart_flush_tcrt (void)
Flush current tapecart data to image file.
Returns
0 on success, < 0 on failure
Referenced by on_tcrt_flush_clicked().
tapecart_is_valid()
int tapecart_is_valid (const char * filename)
Check magic of the tapecart filename.
Checks the first 13 bytes for 'tapecartImage', which seems to be the TCRT header magic.
Returns
bool
Referenced by autostart_tapecart(), and try_attach_tapecart().
tapecart_logic_alarm_handler()
static void tapecart_logic_alarm_handler (CLOCK offset, void * unused) static
Referenced by tapecart_enable().
tapecart_pulse_alarm_handler()
static void tapecart_pulse_alarm_handler (CLOCK offset, void * unused) static
Referenced by tapecart_enable().
tapecart_read_snapshot()
static int tapecart_read_snapshot (int port, struct snapshot_s * s) static
Todo:
FIXME: Implement
tapecart_resources_init()
int tapecart_resources_init (int amount)
Referenced by tapeport_device_resources_init().
tapecart_set_mode()
static void tapecart_set_mode (tapecart_mode_t mode) static
common fastload/command mode functions
Referenced by cmdmode_dispatch_command(), fastload_complete(), tapecart_attach_tcrt(), tapecart_logic_alarm_handler(), and tapecart_store_motor().
tapecart_shutdown()
static void tapecart_shutdown (void) static
a few forward declarations
tapecart_store_motor()
static void tapecart_store_motor (int port, int state) static
tapecart_store_sense()
static void tapecart_store_sense (int port, int state) static
tapecart_store_write()
static void tapecart_store_write (int port, int state) static
tapecart_write_snapshot()
static int tapecart_write_snapshot (int port, struct snapshot_s * s, int write_image) static
snapshots
Todo:
FIXME: Implement
transmit_1bit()
static clock_t transmit_1bit (clock_t delay, uint8_t * buffer, unsigned int length, wait_handler_t complete_callback) static
Referenced by cmd_crc32_flash(), cmd_dir_lookup(), cmd_read_flash(), and cmdmode_dispatch_command().
transmit_1bit_callback()
static clock_t transmit_1bit_callback (void) static
Referenced by transmit_1bit(), and transmit_1bit_callback().
transmit_1bit_delayed()
static clock_t transmit_1bit_delayed (void) static
Referenced by transmit_1bit().
transmit_fast()
static clock_t transmit_fast (clock_t delay, uint8_t * buffer, unsigned int length, wait_handler_t complete_callback) static
Referenced by cmd_read_flash_fast(), and fastload_mode_init().
update_tcrt()
static void update_tcrt (void) static
update TCRT if updates enabled and changes pending
Referenced by tapecart_attach_tcrt(), and tapecart_shutdown().
validate_flashaddress()
static int validate_flashaddress (unsigned int address, unsigned int length) static
command mode functions
Referenced by cmd_crc32_flash(), cmd_dir_setparams(), cmd_erase_flash_64k(), cmd_erase_flash_block(), cmd_read_flash(), cmd_read_flash_fast(), and cmd_write_flash().
Variable Documentation
alarm_trigger_callback
wait_handler_t alarm_trigger_callback static
Referenced by cmd_erase_flash_64k(), cmd_erase_flash_block(), cmdmode_send_pulses(), cmdmode_write_flash_page(), fastload_postdelay(), fasttx_nibble_advance(), receive_1bit(), receive_1bit_callback(), tapecart_logic_alarm_handler(), tapecart_set_mode(), transmit_1bit(), transmit_1bit_callback(), and transmit_fast().
block_length
unsigned int block_length static
Referenced by cmd_write_flash(), and cmdmode_write_flash_page().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-tcrt", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "TapecartTCRTFilename", NULL,
      "<Name>", "Attach TCRT tapecart image" },
    { "-tapecartupdatetcrt", SET_RESOURCE,  0 ,
      NULL, NULL, "TapecartUpdateTCRT", (resource_value_t)1,
      NULL, "Enable updating tapecart .tcrt image" },
    { "+tapecartupdatetcrt", SET_RESOURCE,  0 ,
      NULL, NULL, "TapecartUpdateTCRT", (resource_value_t)0,
      NULL, "Disable updating tapecart .tcrt image" },
    { "-tapecartoptimizetcrt", SET_RESOURCE,  0 ,
      NULL, NULL, "TapecartOptimizeTCRT", (resource_value_t)1,
      NULL, "Enable tapecart .tcrt image optimization on write" },
    { "+tapecartoptimizetcrt", SET_RESOURCE,  0 ,
      NULL, NULL, "TapecartOptimizeTCRT", (resource_value_t)0,
      NULL, "Disable tapecart .tcrt image optimization on write" },
    { "-tapecartloglevel", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "TapecartLogLevel", NULL,
      "<Loglevel>", "Set tapecart log verbosity" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by tapecart_cmdline_options_init().
current_pulse
pulse_t current_pulse static
Referenced by construct_pulsestream(), and get_next_pulse().
default_loader
const unsigned char default_loader[171] static
Initial value:
= {
}
the default tapecart loader, in case it isn't included in the TCRT file
Referenced by load_tcrt().
dir_base
unsigned int dir_base static
Referenced by cmd_dir_lookup(), and cmd_dir_setparams().
dir_data_len
unsigned int dir_data_len static
Referenced by cmd_dir_lookup(), and cmd_dir_setparams().
dir_entries
unsigned int dir_entries static
Referenced by cmd_dir_lookup(), and cmd_dir_setparams().
dir_name_len
unsigned int dir_name_len static
Referenced by cmd_dir_lookup(), cmd_dir_setparams(), and cmdmode_dispatch_command().
fasttx_state
fasttx_state_t fasttx_state static
Referenced by fasttx_byte_advance(), fasttx_nibble_advance(), and transmit_fast().
flash_address
unsigned int flash_address static
Referenced by cmd_write_flash(), and cmdmode_write_flash_page().
flash_erase_64k_time
clock_t flash_erase_64k_time static
Referenced by cmd_erase_flash_64k(), and tapecart_enable().
flash_erase_page_time
clock_t flash_erase_page_time static
Referenced by cmd_erase_flash_block(), and tapecart_enable().
flash_page_write_time
clock_t flash_page_write_time static
Referenced by cmd_write_flash(), cmdmode_write_flash_page(), and tapecart_enable().
idstring
const char idstring[] = "TAPECART V1.0 W25QFLASH" static
Referenced by cmdmode_dispatch_command().
motor_state
int motor_state static
current physical state of tape port lines
Referenced by tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), and tapecart_store_motor().
needed_space
unsigned int needed_space = 0 static
stream mode functions
Referenced by check_pulsebuffer_size().
pulse_count
unsigned int pulse_count static
Referenced by check_pulsebuffer_size(), construct_pulsestream(), get_next_pulse(), pulse_store(), and pulse_store_sync().
pulse_read_index
unsigned int pulse_read_index static
Referenced by construct_pulsestream(), and get_next_pulse().
requested_mode
tapecart_mode_t requested_mode = MODE_STREAM static
Referenced by get_next_pulse(), tapecart_logic_alarm_handler(), tapecart_set_mode(), and tapecart_store_motor().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "TapecartUpdateTCRT", 1, RES_EVENT_STRICT, (resource_value_t)0,
      &tapecart_update_tcrt, set_tapecart_update_tcrt, NULL },
    { "TapecartOptimizeTCRT", 1, RES_EVENT_STRICT, (resource_value_t)0,
      &tapecart_optimize_tcrt, set_tapecart_optimize_tcrt, NULL },
    { "TapecartLogLevel", 0, RES_EVENT_NO, (resource_value_t)0,
      &tapecart_loglevel, set_tapecart_loglevel, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by tapecart_resources_init().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "TapecartTCRTFilename", "", RES_EVENT_NO, NULL,
      &tcrt_filename, tapecart_attach_tcrt, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by tapecart_resources_init().
rx1bit_state
rx1bit_state_t rx1bit_state static
Referenced by receive_1bit(), and receive_1bit_callback().
sense_pause_ticks
unsigned int sense_pause_ticks static
Referenced by tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), and tapecart_set_mode().
sense_state
int sense_state static
Referenced by receive_1bit_callback(), and tapecart_store_sense().
tape_header
const uint8_t tape_header[] static
Initial value:
= {
    0x03,
    0x02, 0x03,
    0x04, 0x03
}
first five bytes of the header block
Referenced by construct_header().
tape_startvector
const uint8_t tape_startvector[] static
Initial value:
= {
    0x51,
    0x03,
    0x51 ^ 0x03
}
two-byte autostart address plus checksum
Referenced by construct_startvector().
tapecart_buffers
tapecart_buffers_t* tapecart_buffers static
Referenced by check_pulsebuffer_size(), fastload_mode_init(), get_next_pulse(), pulse_store(), pulse_store_sync(), tapecart_enable(), and tapecart_exit().
tapecart_debugflags
uint8_t tapecart_debugflags[2] static
Referenced by cmdmode_dispatch_command().
tapecart_device
tapeport_device_t tapecart_device static
Initial value:
= {
    "tapecart",
    TAPEPORT_DEVICE_TYPE_STORAGE,
     ( (1U<<0) | (1U<<8) | (1U<<1) ) ,
     (1 << TAPEPORT_PORT_1) ,
    tapecart_enable,
    NULL,
    tapecart_shutdown,
    tapecart_store_motor,
    tapecart_store_write,
    tapecart_store_sense,
    NULL,
    tapecart_write_snapshot,
    tapecart_read_snapshot
}
Referenced by tapecart_resources_init().
tapecart_enabled
int tapecart_enabled = 0 static
Referenced by tapecart_attach_tcrt(), and tapecart_enable().
tapecart_log
log_t tapecart_log = ((log_t)-1) static
Referenced by check_pulsebuffer_size(), cmd_crc32_flash(), cmd_dir_lookup(), cmd_dir_setparams(), cmd_erase_flash_64k(), cmd_erase_flash_block(), cmd_read_flash(), cmd_read_flash_fast(), cmd_write_flash(), cmd_write_loadinfo(), cmdmode_dispatch_command(), cmdmode_write_flash_page(), fasttx_nibble_advance(), receive_1bit(), tapecart_enable(), tapecart_logic_alarm_handler(), tapecart_read_snapshot(), tapecart_store_motor(), and tapecart_write_snapshot().
tapecart_logic_alarm
alarm_t* tapecart_logic_alarm static
Referenced by cmdmode_receive_command(), tapecart_enable(), tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), tapecart_set_mode(), tapecart_store_sense(), and tapecart_store_write().
tapecart_loglevel
int tapecart_loglevel = 0 static
Referenced by cmd_crc32_flash(), cmd_dir_lookup(), cmd_dir_setparams(), cmd_erase_flash_64k(), cmd_erase_flash_block(), cmd_read_flash(), cmd_read_flash_fast(), cmd_write_flash(), cmd_write_loadinfo(), cmdmode_dispatch_command(), cmdmode_write_flash_page(), set_tapecart_loglevel(), tapecart_logic_alarm_handler(), and tapecart_store_motor().
tapecart_memory
tapecart_memory_t* tapecart_memory static
Referenced by cmd_crc32_flash(), cmd_dir_lookup(), cmd_erase_flash_64k(), cmd_erase_flash_block(), cmd_read_flash(), cmd_read_flash_fast(), cmd_write_loadinfo(), cmdmode_dispatch_command(), cmdmode_write_flash_page(), construct_header(), fastload_mode_init(), save_tcrt(), tapecart_attach_tcrt(), tapecart_enable(), tapecart_exit(), tapecart_flush_tcrt(), and update_tcrt().
tapecart_mode
tapecart_mode_t tapecart_mode = MODE_UNINITIALIZED static
Referenced by fasttx_nibble_advance(), tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), tapecart_set_mode(), and tapecart_store_motor().
tapecart_optimize_tcrt
int tapecart_optimize_tcrt = 0 static
Referenced by save_tcrt(), and set_tapecart_optimize_tcrt().
tapecart_pulse_alarm
alarm_t* tapecart_pulse_alarm static
Referenced by tapecart_enable(), tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), tapecart_set_mode(), and tapecart_store_motor().
tapecart_shiftreg
unsigned short tapecart_shiftreg static
Referenced by tapecart_store_motor().
tapecart_update_tcrt
int tapecart_update_tcrt = 0 static
Referenced by set_tapecart_update_tcrt(), and update_tcrt().
tcrt_filename
char* tcrt_filename static
Referenced by tapecart_attach_tcrt(), tapecart_enable(), tapecart_exit(), tapecart_flush_tcrt(), and update_tcrt().
tcrt_signature
const uint8_t tcrt_signature[16]
Initial value:
= {
    0x74, 0x61, 0x70, 0x65,
    0x63, 0x61, 0x72, 0x74,
    0x49, 0x6d, 0x61, 0x67,
    0x65, 0x0d, 0x0a, 0x1a
}
Referenced by load_tcrt(), save_tcrt(), and tapecart_is_valid().
total_length
unsigned int total_length static
Referenced by cmd_write_flash(), and cmdmode_write_flash_page().
transfer_bit
unsigned int transfer_bit static
Referenced by receive_1bit(), receive_1bit_callback(), transmit_1bit(), and transmit_1bit_callback().
transfer_buffer
uint8_t transfer_buffer[((256) >(256) ?(256) :(256))] static
256 bytes needed for dir_lookup
Referenced by cmd_crc32_flash(), cmd_dir_lookup(), cmd_dir_setparams(), cmd_erase_flash_64k(), cmd_erase_flash_block(), cmd_read_flash(), cmd_read_flash_fast(), cmd_write_flash(), cmd_write_loadinfo(), cmdmode_dispatch_command(), cmdmode_receive_command(), and cmdmode_write_flash_page().
transfer_byte
uint8_t transfer_byte static
Referenced by fasttx_nibble_advance(), and transmit_1bit_callback().
transfer_complete
wait_handler_t transfer_complete static
shared between fastload mode and command mode
Referenced by fasttx_byte_advance(), receive_1bit(), receive_1bit_callback(), transmit_1bit(), transmit_1bit_callback(), and transmit_fast().
transfer_ptr
uint8_t* transfer_ptr static
Referenced by fasttx_nibble_advance(), receive_1bit(), receive_1bit_callback(), transmit_1bit(), transmit_1bit_callback(), and transmit_fast().
transfer_remaining
unsigned int transfer_remaining static
Referenced by fasttx_byte_advance(), fasttx_nibble_advance(), receive_1bit(), receive_1bit_callback(), transmit_1bit(), transmit_1bit_callback(), and transmit_fast().
tx1bit_state
tx1bit_state_t tx1bit_state static
Referenced by transmit_1bit(), and transmit_1bit_callback().
wait_for_signal
statewait_t wait_for_signal static
Referenced by cmdmode_send_pulses(), command_mode_init(), fasttx_nibble_advance(), receive_1bit(), receive_1bit_callback(), receive_1bit_delayed(), tapecart_store_sense(), tapecart_store_write(), transmit_1bit(), transmit_1bit_callback(), and transmit_1bit_delayed().
wait_handler
wait_handler_t wait_handler static
Referenced by cmdmode_send_pulses(), command_mode_init(), fasttx_nibble_advance(), receive_1bit(), tapecart_store_sense(), tapecart_store_write(), and transmit_1bit().
write_state
int write_state static
Referenced by tapecart_store_motor(), and tapecart_store_write().