x128: video/video-color.c File Reference
video-color.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "videoarch.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "palette.h"
#include "resources.h"
#include "viewport.h"
#include "video-canvas.h"
#include "video-color.h"
#include "video.h"
Data Structures
struct video_ycbcr_color_s
struct video_ycbcr_palette_s
Macros
#define DBG(_x_)
use all neutral settings in the color calculations
#define RMIN(x, min) (((x) < (min)) ? (min) : (x))
#define RMAX(x, max) (((x) > (max)) ? (max) : (x))
#define RMINMAX(x, min, max) RMIN(RMAX(x,max),min)
#define MATH_PI 3.141592653589793238462643383279
#define INT_LUMA_ADJ (1.00f)
#define INT_SAT_ADJ (1.75f)
#define CRT_SAT_MUL (1.5f+0.25f)
Typedefs
typedef struct video_ycbcr_color_s video_ycbcr_color_t
typedef struct video_ycbcr_palette_s video_ycbcr_palette_t
Functions
void video_render_setrawrgb (video_render_color_tables_t *color_tab, unsigned int index, uint32_t r, uint32_t g, uint32_t b)
void video_render_setrawalpha (video_render_color_tables_t *color_tab, uint32_t a)
static video_ycbcr_palette_t * video_ycbcr_palette_create (unsigned int num_entries)
static void video_ycbcr_palette_free (video_ycbcr_palette_t *p)
static void video_convert_ycbcr_to_yuv (video_ycbcr_color_t *src, video_ycbcr_color_t *dst)
static void video_convert_yuv_to_ycbcr (video_ycbcr_color_t *src, video_ycbcr_color_t *dst)
currently unused
static void video_convert_ycbcr_to_rgb (const video_ycbcr_color_t *src, int *r, int *g, int *b)
currently unused
static void video_convert_yiq_to_rgb (video_ycbcr_color_t *src, int *r, int *g, int *b)
static void video_convert_rgb_to_yiq (const palette_entry_t *src, video_ycbcr_color_t *dst)
static void video_convert_rgb_to_ycbcr (const palette_entry_t *src, video_ycbcr_color_t *dst)
static void video_convert_cbm_to_ycbcr (const video_cbm_color_t *src, float phase, video_ycbcr_color_t *dst, int video)
static float video_gamma (float value, double factor, float gamma, float bri, float con)
gamma correction
static void video_convert_renderer_to_rgb (video_ycbcr_color_t *src, palette_entry_t *dst, int video)
static void video_convert_renderer_to_rgb_gamma (video_ycbcr_color_t *src, float sat, float bri, float con, float gam, float tin, palette_entry_t *dst, int video)
static void video_convert_rgb_to_renderer (const palette_entry_t *src, video_ycbcr_color_t *dst, int video)
static float video_get_gamma (video_resources_t *video_resources, int video)
static void video_calc_gammatable (video_render_color_tables_t *color_tab, video_resources_t *video_resources, int video)
gammatable calculation
static void video_calc_ycbcrtable (video_resources_t *video_resources, const video_ycbcr_palette_t *p, video_render_color_tables_t *color_tab, int video)
ycbcr table calculation
static void video_calc_ycbcrtable_oddlines (video_resources_t *video_resources, const video_ycbcr_palette_t *p, video_render_color_tables_t *color_tab, int video)
static void video_palette_to_ycbcr (const palette_t *p, video_ycbcr_palette_t *ycbcr, int video)
Convert an RGB palette to YCbCr.
static void video_palette_to_ycbcr_oddlines (const palette_t *p, video_ycbcr_palette_t *ycbcr, int video)
Convert an RGB palette to YCbCr.
static void video_cbm_palette_to_ycbcr (const video_cbm_palette_t *p, video_ycbcr_palette_t *ycbcr, int video)
Convert the internal videochip palette to YCbCr.
static void video_cbm_palette_to_ycbcr_oddlines (video_resources_t *video_resources, const video_cbm_palette_t *p, video_ycbcr_palette_t *ycbcr, int video)
static palette_t * video_calc_palette (struct video_canvas_s *canvas, const video_ycbcr_palette_t *p, int video)
static palette_t * video_load_palette (const video_cbm_palette_t *p, const char *name)
Load RGB palette.
int video_color_update_palette (struct video_canvas_s *canvas)
Calculate or load a palette, depending on configuration.
void video_color_palette_internal (struct video_canvas_s *canvas, struct video_cbm_palette_s *cbm_palette)
void video_color_palette_free (struct palette_s *palette)
void video_render_initraw (struct video_render_config_s *videoconfig)
called by archdep code for first initial setup
Macro Definition Documentation
CRT_SAT_MUL
#define CRT_SAT_MUL (1.5f+0.25f)
Todo:
FIXME: this is a hack to adjust the output of the internal color generator somewhat to align with the pepto palette when all neutral parameters are used
DBG
#define DBG (_x_)
use all neutral settings in the color calculations
INT_LUMA_ADJ
#define INT_LUMA_ADJ (1.00f)
INT_SAT_ADJ
#define INT_SAT_ADJ (1.75f)
MATH_PI
#define MATH_PI 3.141592653589793238462643383279
RMAX
#define RMAX (x, max) (((x) > (max)) ? (max) : (x))
RMIN
#define RMIN (x, min) (((x) < (min)) ? (min) : (x))
RMINMAX
#define RMINMAX (x, min, max) RMIN(RMAX(x,max),min)
Typedef Documentation
video_ycbcr_color_t
typedef struct video_ycbcr_color_s video_ycbcr_color_t
video_ycbcr_palette_t
typedef struct video_ycbcr_palette_s video_ycbcr_palette_t
Function Documentation
video_calc_gammatable()
static void video_calc_gammatable (video_render_color_tables_t * color_tab, video_resources_t * video_resources, int video) static
gammatable calculation
Referenced by video_color_update_palette(), and video_render_initraw().
video_calc_palette()
static palette_t * video_calc_palette (struct video_canvas_s * canvas, const video_ycbcr_palette_t * p, int video) static
Referenced by video_color_update_palette().
video_calc_ycbcrtable()
static void video_calc_ycbcrtable (video_resources_t * video_resources, const video_ycbcr_palette_t * p, video_render_color_tables_t * color_tab, int video) static
ycbcr table calculation
called by video_color_update_palette, internal and external palette
Todo:
FIXME: tint for NTSC
Todo:
FIXME: convert IQ to UV (used by YUV renderers)
Todo:
FIXME: convert IQ to UV (used by YUV renderers)
Todo:
FIXME: we need to check more and clamp the values accordingly - it is still possible to "overdrive" the renderer in NTSC mode
Referenced by video_color_update_palette().
video_calc_ycbcrtable_oddlines()
static void video_calc_ycbcrtable_oddlines (video_resources_t * video_resources, const video_ycbcr_palette_t * p, video_render_color_tables_t * color_tab, int video) static
Referenced by video_color_update_palette().
video_cbm_palette_to_ycbcr()
static void video_cbm_palette_to_ycbcr (const video_cbm_palette_t * p, video_ycbcr_palette_t * ycbcr, int video) static
Convert the internal videochip palette to YCbCr.
Referenced by video_color_update_palette().
video_cbm_palette_to_ycbcr_oddlines()
static void video_cbm_palette_to_ycbcr_oddlines (video_resources_t * video_resources, const video_cbm_palette_t * p, video_ycbcr_palette_t * ycbcr, int video) static
Referenced by video_color_update_palette().
video_color_palette_free()
void video_color_palette_free (struct palette_s * palette)
Referenced by raster_shutdown(), and video_canvas_palette_set().
video_color_palette_internal()
void video_color_palette_internal (struct video_canvas_s * canvas, struct video_cbm_palette_s * cbm_palette)
Referenced by vdc_color_update_palette(), and vicii_color_update_palette().
video_color_update_palette()
int video_color_update_palette (struct video_canvas_s * canvas)
Calculate or load a palette, depending on configuration.
Referenced by realize_canvas(), and video_canvas_render().
video_convert_cbm_to_ycbcr()
static void video_convert_cbm_to_ycbcr (const video_cbm_color_t * src, float phase, video_ycbcr_color_t * dst, int video) static
Todo:
FIXME: this is a hack to adjust the output of the internal color generator somewhat to align with the pepto palette when all neutral parameters are used
Referenced by video_cbm_palette_to_ycbcr(), and video_cbm_palette_to_ycbcr_oddlines().
video_convert_renderer_to_rgb()
static void video_convert_renderer_to_rgb (video_ycbcr_color_t * src, palette_entry_t * dst, int video) static
Referenced by video_calc_ycbcrtable(), and video_palette_to_ycbcr().
video_convert_renderer_to_rgb_gamma()
static void video_convert_renderer_to_rgb_gamma (video_ycbcr_color_t * src, float sat, float bri, float con, float gam, float tin, palette_entry_t * dst, int video) static
Todo:
FIXME: tint for ntsc
Referenced by video_calc_palette().
video_convert_rgb_to_renderer()
static void video_convert_rgb_to_renderer (const palette_entry_t * src, video_ycbcr_color_t * dst, int video) static
Referenced by video_cbm_palette_to_ycbcr(), video_palette_to_ycbcr(), and video_palette_to_ycbcr_oddlines().
video_convert_rgb_to_ycbcr()
static void video_convert_rgb_to_ycbcr (const palette_entry_t * src, video_ycbcr_color_t * dst) inline static
Referenced by video_convert_rgb_to_renderer().
video_convert_rgb_to_yiq()
static void video_convert_rgb_to_yiq (const palette_entry_t * src, video_ycbcr_color_t * dst) inline static
Referenced by video_convert_rgb_to_renderer(), and video_palette_to_ycbcr().
video_convert_ycbcr_to_rgb()
static void video_convert_ycbcr_to_rgb (const video_ycbcr_color_t * src, int * r, int * g, int * b) inline static
currently unused
Referenced by video_convert_renderer_to_rgb(), and video_convert_renderer_to_rgb_gamma().
video_convert_ycbcr_to_yuv()
static void video_convert_ycbcr_to_yuv (video_ycbcr_color_t * src, video_ycbcr_color_t * dst) inline static
Referenced by video_cbm_palette_to_ycbcr().
video_convert_yiq_to_rgb()
static void video_convert_yiq_to_rgb (video_ycbcr_color_t * src, int * r, int * g, int * b) inline static
Referenced by video_convert_renderer_to_rgb(), video_convert_renderer_to_rgb_gamma(), and video_palette_to_ycbcr().
video_convert_yuv_to_ycbcr()
static void video_convert_yuv_to_ycbcr (video_ycbcr_color_t * src, video_ycbcr_color_t * dst) inline static
currently unused
Referenced by video_convert_cbm_to_ycbcr().
video_gamma()
static float video_gamma (float value, double factor, float gamma, float bri, float con) static
gamma correction
Referenced by video_calc_gammatable(), video_calc_ycbcrtable(), and video_convert_renderer_to_rgb_gamma().
video_get_gamma()
static float video_get_gamma (video_resources_t * video_resources, int video) static
Todo:
FIXME: handle gamma for CRT emulation (CGA and Monochrom video) too
Referenced by video_calc_gammatable(), video_calc_palette(), and video_calc_ycbcrtable().
video_load_palette()
static palette_t * video_load_palette (const video_cbm_palette_t * p, const char * name) static
Load RGB palette.
Referenced by video_color_update_palette().
video_palette_to_ycbcr()
static void video_palette_to_ycbcr (const palette_t * p, video_ycbcr_palette_t * ycbcr, int video) static
Convert an RGB palette to YCbCr.
(used when custom palette is loaded)
Referenced by video_color_update_palette().
video_palette_to_ycbcr_oddlines()
static void video_palette_to_ycbcr_oddlines (const palette_t * p, video_ycbcr_palette_t * ycbcr, int video) static
Convert an RGB palette to YCbCr.
(used when custom palette is loaded)
Referenced by video_color_update_palette().
video_render_initraw()
void video_render_initraw (struct video_render_config_s * videoconfig)
called by archdep code for first initial setup
Referenced by vice_opengl_set_palette().
video_render_setrawalpha()
void video_render_setrawalpha (video_render_color_tables_t * color_tab, uint32_t a)
Referenced by vice_opengl_set_palette().
video_render_setrawrgb()
void video_render_setrawrgb (video_render_color_tables_t * color_tab, unsigned int index, uint32_t r, uint32_t g, uint32_t b)
Referenced by vice_opengl_set_palette().
video_ycbcr_palette_create()
static video_ycbcr_palette_t * video_ycbcr_palette_create (unsigned int num_entries) static
Referenced by video_color_update_palette().
video_ycbcr_palette_free()
static void video_ycbcr_palette_free (video_ycbcr_palette_t * p) static
Referenced by video_color_update_palette().