vsid: arch/gtk3/widgets/statusbarspeedwidget.h File Reference
statusbarspeedwidget.h File Reference
CPU speed, FPS display widget for the statusbar - header.
#include "vice.h"
#include <gtk/gtk.h>
#include "archdep.h"
#include "vice_gtk3.h"
Data Structures
struct statusbar_speed_widget_state_s
Used to optimise display updates.
Typedefs
typedef struct statusbar_speed_widget_state_s statusbar_speed_widget_state_t
Used to optimise display updates.
Functions
GtkWidget * speed_menu_popup_create (void)
Create popup menu for the statusbar speed widget.
GtkWidget * statusbar_speed_widget_create (statusbar_speed_widget_state_t *state)
Create widget to display CPU/FPS/pause.
void statusbar_speed_widget_update (GtkWidget *widget, statusbar_speed_widget_state_t *state, int window_identity)
Update the speed widget's display state.
Detailed Description
CPU speed, FPS display widget for the statusbar - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Typedef Documentation
statusbar_speed_widget_state_t
typedef struct statusbar_speed_widget_state_s statusbar_speed_widget_state_t
Used to optimise display updates.
Function Documentation
speed_menu_popup_create()
GtkWidget * speed_menu_popup_create (void)
Create popup menu for the statusbar speed widget.
Returns
GtkMenu
Referenced by on_widget_clicked().
statusbar_speed_widget_create()
GtkWidget * statusbar_speed_widget_create (statusbar_speed_widget_state_t * state)
Create widget to display CPU/FPS/pause.
Parameters
[in,out] state current widget state
Returns
GtkEventBox
Referenced by ui_statusbar_create().
statusbar_speed_widget_update()
void statusbar_speed_widget_update (GtkWidget * widget, statusbar_speed_widget_state_t * state, int window_identity)
Update the speed widget's display state.
Parameters
[in,out] widget GtkEventBox containing the CPU/FPS widgets
[in,out] state current widget state
[in] window_identity window index (primary/secondary)
Referenced by ui_update_statusbars(), and ui_update_vsid_statusbar().