vsid: arch/gtk3/widgets/base/resourceentry.c File Reference
resourceentry.c File Reference
Text entry connected to a resource.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdarg.h>
#include "debug_gtk3.h"
#include "log.h"
#include "resources.h"
#include "resourcewidgetmediator.h"
#include "resourceentry.h"
Functions
static gboolean resource_entry_update_resource (GtkEntry *entry, const char *text)
Update bound resource.
static gboolean on_focus_out_event (GtkEntry *entry, GdkEvent *event, gpointer data)
Handler for the 'focus-out' event.
static gboolean on_key_press_event (GtkEntry *entry, GdkEvent *event, gpointer data)
Handler for the 'on-key-press' event.
GtkWidget * vice_gtk3_resource_entry_new (const char *resource)
Create resource entry box that only reacts to 'full' entries.
GtkWidget * vice_gtk3_resource_entry_new_sprintf (const char *fmt,...)
Create resource entry box that only reacts to 'full' entries.
gboolean vice_gtk3_resource_entry_reset (GtkWidget *widget)
Reset the widget to the original resource value.
gboolean vice_gtk3_resource_entry_set (GtkWidget *widget, const char *text)
Set new string for resource entry.
gboolean vice_gtk3_resource_entry_sync (GtkWidget *widget)
Synchronize widget with its resource.
gboolean vice_gtk3_resource_entry_factory (GtkWidget *widget)
Reset entry to its resource factory value.
Detailed Description
Text entry connected to a resource.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_focus_out_event()
static gboolean on_focus_out_event (GtkEntry * entry, GdkEvent * event, gpointer data) static
Handler for the 'focus-out' event.
Parameters
[in,out] entry entry box
[in] event event object (unused)
[in] data extra event data (unused)
Returns
FALSE to propagate the event further
Referenced by vice_gtk3_resource_entry_new().
on_key_press_event()
static gboolean on_key_press_event (GtkEntry * entry, GdkEvent * event, gpointer data) static
Handler for the 'on-key-press' event.
Parameters
[in,out] entry entry box
[in] event event object
[in] data unused
Returns
TRUE if Enter was pushed, FALSE otherwise (makes the pushed key propagate to the entry)
Referenced by vice_gtk3_resource_entry_new().
resource_entry_update_resource()
static gboolean resource_entry_update_resource (GtkEntry * entry, const char * text) static
Update bound resource.
When text differs from the resource value (or when the GtkEntry's text differs in case text is NULL) we update the resource and store the new value as the current valid value in the mediator.
Parameters
[in] entry full resource entry box
[in] text text for resource, pass NULL to get text from entry
Returns
TRUE when the entry was updated
Referenced by on_focus_out_event(), on_key_press_event(), and vice_gtk3_resource_entry_set().
vice_gtk3_resource_entry_factory()
gboolean vice_gtk3_resource_entry_factory (GtkWidget * widget)
Reset entry to its resource factory value.
Parameters
[in] widget resource entry
Returns
TRUE when the entry was restored to its factory value
vice_gtk3_resource_entry_new()
GtkWidget * vice_gtk3_resource_entry_new (const char * resource)
Create resource entry box that only reacts to 'full' entries.
Creates a resource-connected entry box that only updates the resource when the either the widget looses focus (due to Tab or mouse click somewhere else in the UI) or when the user presses 'Enter'. This behaviour differs from the other resource entry which updates its resource on every key press.
Parameters
[in] resource resource name
Returns
GtkEntry
Referenced by create_argument_entry(), create_eeprom_image_widget(), create_fsdir_entry_widget(), create_ide64_usb_layout(), settings_hvsc_widget_create(), settings_monitor_widget_create(), settings_netplay_widget_create(), vice_gtk3_resource_browser_new(), vice_gtk3_resource_browser_save_new(), and vice_gtk3_resource_entry_new_sprintf().
vice_gtk3_resource_entry_new_sprintf()
GtkWidget * vice_gtk3_resource_entry_new_sprintf (const char * fmt, ...)
Create resource entry box that only reacts to 'full' entries.
Creates a resource-connected entry box that only updates the resource when the either the widget looses focus (due to Tab or mouse click somewhere else in the UI) or when the user presses 'Enter'. This behaviour differs from the other resource entry which updates its resource on every key press.
This is a variant of vice_gtk3_resource_entry_new() that allows using a printf format string to specify the resource name.
Parameters
[in] fmt resource name format string (printf-style)
[in] ... format string arguments
Returns
GtkEntry
Referenced by create_printer_text_devices_widget().
vice_gtk3_resource_entry_reset()
gboolean vice_gtk3_resource_entry_reset (GtkWidget * widget)
Reset the widget to the original resource value.
Resets the widget and the connect resource to the value the resource contained when the widget was created.
Parameters
[in,out] widget resource entry box
Returns
TRUE when the entry was reset to its original value
vice_gtk3_resource_entry_set()
gboolean vice_gtk3_resource_entry_set (GtkWidget * widget, const char * text)
Set new string for resource entry.
Sets value as the new text for widget and also updates the connected resource. Returns TRUE on success, FALSE on failure. It is assumed that a failure to set a resource in only due to some registered resource handler failing, not due to an invalid resource name.
Parameters
[in,out] widget resource entry
[in] text new text for entry
Returns
TRUE on success
Referenced by browse_callback(), browse_filename_callback(), fsdir_browse_callback(), save_filename_callback(), vice_gtk3_resource_entry_factory(), and vice_gtk3_resource_entry_reset().
vice_gtk3_resource_entry_sync()
gboolean vice_gtk3_resource_entry_sync (GtkWidget * widget)
Synchronize widget with its resource.
Parameters
[in,out] widget resource entry
Returns
TRUE on success