vsid: m3u.c File Reference
m3u.c File Reference
Extended M3U playlist handling.
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <errno.h>
#include <ctype.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "util.h"
#include "m3u.h"
Data Structures
struct m3u_ext_s
M3U directive data.
Macros
#define ARRAY_LEN(arr) (sizeof arr / sizeof arr[0])
Array length helper.
#define INITIAL_BUFSIZE 80
Initial size of buffer for reading the playlist.
#define M3U_COMMENT '#'
Token indicating comment or directive.
#define M3U_HEADER "#EXTM3U"
Extended M3U header.
Typedefs
typedef struct m3u_ext_s m3u_ext_t
M3U directive data.
Functions
static m3u_ext_id_t get_directive_id (const char *s, const char **endptr)
Parse string for m3u directive.
static ssize_t strip_trailing (ssize_t pos)
Strip trailing whitespace from buffer.
static void free_current_dir (void)
Free playlist_current_dir and set to NULL
static char * prepend_current_dir (const char *path)
Join current directory with path.
static void update_current_dir (const char *path)
Update current directory for relative entries.
static bool read_line (size_t *len)
Read a line of text from the playlist.
bool m3u_open (const char *path, bool(*entry_callback)(const char *arg, size_t len), bool(*directive_callback)(m3u_ext_id_t id, const char *arg, size_t len))
Open m3u file for parsing.
static bool have_output_file (void)
Check if we have an open file.
static bool m3u_append_string (const char *s)
Append string to current playlist file.
bool m3u_create (const char *path)
Create new M3U playlist file.
bool m3u_set_playlist_title (const char *title)
Set playlist title.
bool m3u_append_entry (const char *entry)
Append normal entry to playlist file.
bool m3u_append_comment (const char *comment)
Append comment to playlist file.
bool m3u_append_newline (void)
Append newline to playlist file.
void m3u_close (void)
Close m3u file and clean up resources.
bool m3u_parse (void)
Parse the playlist.
long m3u_linenum (void)
Get current line number of playlist being processed.
const char * m3u_directive_str (m3u_ext_id_t id)
Get directive string for ID.
Variables
static char * playlist_path = NULL
Path to playlist file.
static FILE * playlist_fp = NULL
File pointer for the parser.
static long playlist_linenum = 0
Current line number in the playlist.
static bool have_playlist_title = false
Title has been set via m3u_set_playlist_title()
static char * playlist_buf = NULL
Buffer used for reading lines from the playlist.
static size_t playlist_bufsize = 0
Size of the buffer.
static bool(* entry_cb)(const char *, size_t) = NULL
Callback for normal entries.
static bool(* directive_cb)(int, const char *, size_t) = NULL
Callback for directives.
static char * playlist_current_dir = NULL
Current directory for relative entries.
static const m3u_ext_t extensions []
List of extended m3u directives.
Detailed Description
Extended M3U playlist handling.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Simple API for reading and writing extended M3U playlist files, tailored towards use in VSID.
There is no formal specification of the file format, so information was used from various places on the internet, among which: https://en.wikipedia.org/wiki/M3U
Only a few directives of the extended m3u format are supported. Inline comments are not supported (can't find any reference about whether or not they should be).
Macro Definition Documentation
ARRAY_LEN
#define ARRAY_LEN (arr) (sizeof arr / sizeof arr[0])
Array length helper.
Parameters
arr array
INITIAL_BUFSIZE
#define INITIAL_BUFSIZE 80
Initial size of buffer for reading the playlist.
M3U_COMMENT
#define M3U_COMMENT '#'
Token indicating comment or directive.
M3U_HEADER
#define M3U_HEADER "#EXTM3U"
Extended M3U header.
This header must be the first line in an m3u 1.1 file.
Note
A newline is added automagically when calling m3u_create()
Typedef Documentation
m3u_ext_t
typedef struct m3u_ext_s m3u_ext_t
M3U directive data.
Function Documentation
free_current_dir()
static void free_current_dir (void) static
Free playlist_current_dir and set to NULL
Referenced by m3u_close(), m3u_open(), and update_current_dir().
get_directive_id()
static m3u_ext_id_t get_directive_id (const char * s, const char ** endptr) static
Parse string for m3u directive.
Parse string s for a valid directive (excluding the starting '#') and return the directive ID, optionally setting endptr to the first non-directive character (whitspace, colon or eol).
Parameters
[in] s string to parse
[out] endptr pointer to character after the directive in s (optional, pass NULL to ignore)
Returns
directive ID or M3U_ERROR (-1) when no valid directive found
Referenced by m3u_parse().
have_output_file()
static bool have_output_file (void) static
Check if we have an open file.
Test if we have an open file and report an error if not.
Returns
true when a file is open
Referenced by m3u_append_comment(), m3u_append_entry(), m3u_append_string(), and m3u_set_playlist_title().
m3u_append_comment()
bool m3u_append_comment (const char * comment)
Append comment to playlist file.
Parameters
[in] comment comment text
Note
The caller should not use the '#' comment token, the function will add it.
Returns
true on success
Referenced by playlist_save_dialog_callback().
m3u_append_entry()
bool m3u_append_entry (const char * entry)
Append normal entry to playlist file.
Append path to SID file to playlist file.
Parameters
[in] entry path to SID file
Returns
true on success
Todo:
Support relative paths
Referenced by playlist_save_dialog_callback().
m3u_append_newline()
bool m3u_append_newline (void)
Append newline to playlist file.
Returns
true on success
Referenced by m3u_append_string(), and playlist_save_dialog_callback().
m3u_append_string()
static bool m3u_append_string (const char * s) static
Append string to current playlist file.
Parameters
[in] s string to write
Note
Obviously requires calling m3u_create() first
Returns
true on success
Referenced by m3u_append_entry(), and m3u_create().
m3u_close()
void m3u_close (void)
Close m3u file and clean up resources.
Cleans up resources and resets internal state for subsequent reading or writing of m3u files.
Referenced by playlist_load_callback(), and playlist_save_dialog_callback().
m3u_create()
bool m3u_create (const char * path)
Create new M3U playlist file.
Open path for writing and write the M3U header.
Parameters
[in] path filename and path
Returns
true on success
Referenced by playlist_save_dialog_callback().
m3u_directive_str()
const char * m3u_directive_str (m3u_ext_id_t id)
Get directive string for ID.
Parameters
[in] id directive ID
See also
m3u_ext_id_t
m3u_linenum()
long m3u_linenum (void)
Get current line number of playlist being processed.
Returns
line number
m3u_open()
bool m3u_open (const char * path, bool(*)(const char *arg, size_t len) entry_callback, bool(*)(m3u_ext_id_t id, const char *arg, size_t len) directive_callback)
Open m3u file for parsing.
Try to open path for reading and set up the parser.
The entry_callback argument is required and will be called by m3u_parse() whenever a normal entry is encountered in path. Its first argument is the entry text and the second argument is the lenght of the entry excluding the terminating nul character.
The directive_callback argument is optional and can be used to handle extended M3U directives. The first argument is the directive ID (
See also
m3u_ext_id_t), the second argument is the text following the directive and the third argument is the length of the text excluding the terminating nul character.
To stop the parser the callbacks must return false.
Parameters
[in] path path to m3u file
[in] entry_callback callback for normal entries
[in] directive_callback callback for extended m3u directives (optional, pass NULL to ignore)
Returns
true on success
Referenced by playlist_load_callback().
m3u_parse()
bool m3u_parse (void)
Parse the playlist.
Parse playlist file triggering the callbacks registered with m3u_open().
Returns
true on success
Referenced by playlist_load_callback().
m3u_set_playlist_title()
bool m3u_set_playlist_title (const char * title)
Set playlist title.
Parameters
[in] title playlist title
Returns
true on success
Note
Normally one would call this after m3u_create() and before adding any entries.
Referenced by playlist_save_dialog_callback().
prepend_current_dir()
static char * prepend_current_dir (const char * path) static
Join current directory with path.
Parameters
[in] path pathname
Returns
heap-allocated string, free with lib_free() after use
Referenced by m3u_parse().
read_line()
static bool read_line (size_t * len) static
Read a line of text from the playlist.
Parameters
[out] len length of line read (excluding trailing whitespace)
Note
trailing whitespace is stripped
Returns
false on EOF
Referenced by m3u_parse().
strip_trailing()
static ssize_t strip_trailing (ssize_t pos) static
Strip trailing whitespace from buffer.
Strip trailing whitespace starting at pos - 1 in the buffer.
Returns
position in the string of the terminating nul character
Referenced by read_line().
update_current_dir()
static void update_current_dir (const char * path) static
Update current directory for relative entries.
Parameters
[in] path new directory (may be relative)
Referenced by m3u_parse().
Variable Documentation
directive_cb
bool(* directive_cb) (int, const char *, size_t) (int , const char * , size_t) = NULL static
Callback for directives.
The first argument the directive type, the second argument is the data following the entry and the third argument is the length of the data excluding the terminating nul character.
Referenced by m3u_open(), and m3u_parse().
entry_cb
bool(* entry_cb) (const char *, size_t) (const char * , size_t) = NULL static
Callback for normal entries.
The first argument is the entry as a string, the second the length of the entry excluding the terminating nul character.
Referenced by m3u_open(), and m3u_parse().
extensions
const m3u_ext_t extensions[] static
Initial value:
= {
    { M3U_EXTM3U,   "EXTM3U",   "file header" },
    { M3U_EXTINF,   "EXTINF",   "track information" },
    { M3U_PLAYLIST, "PLAYLIST", "playlist title" },
    { M3U_EXTALB,   "EXTALB",   "album title" },
    { M3U_EXTART,   "EXTART",   "album artist" },
}
List of extended m3u directives.
Referenced by get_directive_id(), and m3u_directive_str().
have_playlist_title
bool have_playlist_title = false static
Title has been set via m3u_set_playlist_title()
Avoid writing title multiple times.
Referenced by m3u_close(), m3u_create(), and m3u_set_playlist_title().
playlist_buf
char* playlist_buf = NULL static
Buffer used for reading lines from the playlist.
Dynamically allocated and resized when required, freed with m3u_close()
Referenced by m3u_close(), m3u_open(), m3u_parse(), read_line(), and strip_trailing().
playlist_bufsize
size_t playlist_bufsize = 0 static
Size of the buffer.
Referenced by m3u_open(), and read_line().
playlist_current_dir
char* playlist_current_dir = NULL static
Current directory for relative entries.
M3UEXT allows using directory-only entries and relative paths, so we keep track of that here.
Initially the directory is set by m3u_open() to the directory of the playlist file being parsed. When a non-file entry is found the contents are either appended to the current dir (if relative) or the current directory is set to the entry (if absolute).
Referenced by free_current_dir(), m3u_open(), prepend_current_dir(), and update_current_dir().
playlist_fp
FILE* playlist_fp = NULL static
File pointer for the parser.
Referenced by have_output_file(), m3u_append_comment(), m3u_append_newline(), m3u_append_string(), m3u_close(), m3u_create(), m3u_open(), m3u_parse(), m3u_set_playlist_title(), and read_line().
playlist_linenum
long playlist_linenum = 0 static
Current line number in the playlist.
Referenced by m3u_close(), m3u_create(), m3u_linenum(), m3u_open(), and m3u_parse().
playlist_path
char* playlist_path = NULL static
Path to playlist file.
Referenced by m3u_append_newline(), m3u_append_string(), m3u_close(), m3u_create(), and m3u_open().