x128: arch/gtk3/widgets/superpetwidget.h File Reference
superpetwidget.h File Reference
Widget to control various SuperPET related resources - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
GtkWidget * superpet_widget_create (void)
Create a SuperPET-specific widget to be used in the PET model widget.
void pet_superpet_enable_widget_sync (void)
Synchronize widget with its resource.
void pet_superpet_widget_set_superpet_enable_callback (void(*func)(int))
Set function to trigger on SuperPET enable checkbox toggle.
Detailed Description
Widget to control various SuperPET related resources - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
pet_superpet_enable_widget_sync()
void pet_superpet_enable_widget_sync (void)
Synchronize widget with its resource.
Parameters
[in,out] widget SuperPET I/O enabled widget
Referenced by machine_model_handler_pet().
pet_superpet_widget_set_superpet_enable_callback()
void pet_superpet_widget_set_superpet_enable_callback (void(*)(int) func)
Set function to trigger on SuperPET enable checkbox toggle.
Parameters
[in] func callback function
Referenced by create_pet_layout().
superpet_widget_create()
GtkWidget * superpet_widget_create (void)
Create a SuperPET-specific widget to be used in the PET model widget.
Returns
GtkGrid
Referenced by create_pet_layout().