vsid: arch/gtk3/render_thread.c File Reference
render_thread.c File Reference
#include "vice.h"
#include "render_thread.h"
#include <glib.h>
#include <pthread.h>
#include <stdbool.h>
#include <string.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
Data Structures
struct render_thread_s
Macros
#define RENDER_THREAD_MAX 2
Current max of two windows (x128)
#define LOCK() pthread_mutex_lock(&lock)
#define UNLOCK() pthread_mutex_unlock(&lock)
Functions
render_thread_t render_thread_create (render_thread_callback_t callback, void *thread_context)
void render_thread_initiate_shutdown (render_thread_t thread)
void render_thread_join (render_thread_t thread)
void render_thread_shutdown_and_join_all (void)
void render_thread_push_job (render_thread_t thread, render_job_t job)
Variables
static struct render_thread_s threads [2]
static int thread_count
static pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER
Macro Definition Documentation
LOCK
#define LOCK () pthread_mutex_lock(&lock)
RENDER_THREAD_MAX
#define RENDER_THREAD_MAX 2
Current max of two windows (x128)
UNLOCK
#define UNLOCK () pthread_mutex_unlock(&lock)
Function Documentation
render_thread_create()
render_thread_t render_thread_create (render_thread_callback_t callback, void * thread_context)
< Current max of two windows (x128)
< Current max of two windows (x128)
Referenced by on_widget_realized().
render_thread_initiate_shutdown()
void render_thread_initiate_shutdown (render_thread_t thread)
Referenced by render_thread_shutdown_and_join_all().
render_thread_join()
void render_thread_join (render_thread_t thread)
Todo:
We should block until all jobs are done - but there's a race condition deadlock outcome here. Fix needed
Referenced by render_thread_shutdown_and_join_all().
render_thread_push_job()
void render_thread_push_job (render_thread_t thread, render_job_t job)
Referenced by vice_opengl_on_ui_frame_clock(), and vice_opengl_refresh_rect().
render_thread_shutdown_and_join_all()
void render_thread_shutdown_and_join_all (void)
Referenced by main_exit().
Variable Documentation
lock
pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER static
thread_count
int thread_count static
Referenced by render_thread_create(), and render_thread_shutdown_and_join_all().
threads
struct render_thread_s threads[2] static
Referenced by render_thread_create(), and render_thread_shutdown_and_join_all().