x128: drive/iec/iecrom.h File Reference
iecrom.h File Reference
#include "types.h"
Functions
void iecrom_init (void)
void iecrom_setup_image (struct diskunit_context_s *unit)
int iecrom_check_loaded (unsigned int type)
void iecrom_do_checksum (struct diskunit_context_s *unit)
int iecrom_load_1540 (void)
int iecrom_load_1541 (void)
int iecrom_load_1541ii (void)
int iecrom_load_1570 (void)
int iecrom_load_1571 (void)
int iecrom_load_1581 (void)
int iecrom_load_2000 (void)
int iecrom_load_4000 (void)
int iecrom_load_CMDHD (void)
Function Documentation
iecrom_check_loaded()
int iecrom_check_loaded (unsigned int type)
< ASCII for HD
Referenced by iec_drive_rom_check_loaded().
iecrom_do_checksum()
void iecrom_do_checksum (struct diskunit_context_s * unit)
Referenced by iec_drive_rom_do_checksum().
iecrom_init()
void iecrom_init (void)
Referenced by iec_drive_init().
iecrom_load_1540()
int iecrom_load_1540 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1540().
iecrom_load_1541()
int iecrom_load_1541 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1541().
iecrom_load_1541ii()
int iecrom_load_1541ii (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1541ii().
iecrom_load_1570()
int iecrom_load_1570 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1570().
iecrom_load_1571()
int iecrom_load_1571 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1571().
iecrom_load_1581()
int iecrom_load_1581 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1581().
iecrom_load_2000()
int iecrom_load_2000 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_2000().
iecrom_load_4000()
int iecrom_load_4000 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_4000().
iecrom_load_CMDHD()
int iecrom_load_CMDHD (void)
< ASCII for HD
Referenced by iec_drive_rom_load(), and set_dos_rom_name_CMDHD().
iecrom_setup_image()
void iecrom_setup_image (struct diskunit_context_s * unit)
< ASCII for HD
Referenced by iec_drive_rom_setup_image().