x128: arch/gtk3/widgets/settings_ramreset.c File Reference
settings_ramreset.c File Reference
Widget to control the RAM reset pattern settings.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "vice_gtk3.h"
#include "ram.h"
#include "resources.h"
#include "settings_ramreset.h"
Macros
#define PREVIEWPATTERNBYTES 0x10000
Number of bytes to show for the preview.
#define PREVIEWTEXTBYTES (PREVIEWPATTERNBYTES * 4)
Size of the text buffer for the preview.
#define PREVIEW_CSS
CSS for the preview of the pattern.
Functions
static void on_value_changed (GtkWidget *widget, gpointer data)
Handler for the 'value-changed' event of the widgets in this dialog.
static GtkWidget * create_preview_widget (void)
Create textview for the RAM init preview hexdump.
GtkWidget * settings_ramreset_widget_create (GtkWidget *parent)
Create widget to control RAM init settings.
Variables
static const vice_gtk3_combo_entry_int_t powers_of_two []
List of powers of two used for the widgets.
static char printbuffer [(0x10000 *4)]
Buffer used to print the raw text of the hexdump.
Detailed Description
Widget to control the RAM reset pattern settings.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
groepaz groep.nosp@m.az@g.nosp@m.mx.ne.nosp@m.t
Macro Definition Documentation
PREVIEW_CSS
#define PREVIEW_CSS
Value:
    "text {\n" \
    "    font-family: \"Monospace\";\n" \
    "    background-color: black;\n" \
    "    color: limegreen;\n" \
    "}\n"
CSS for the preview of the pattern.
Since Gtk's CSS doesn't allow using colors from the current theme, we make the widget green text on black, like old terminals. That avoids making the widget look odd with themes other than Adwaita.
PREVIEWPATTERNBYTES
#define PREVIEWPATTERNBYTES 0x10000
Number of bytes to show for the preview.
PREVIEWTEXTBYTES
#define PREVIEWTEXTBYTES (PREVIEWPATTERNBYTES * 4)
Size of the text buffer for the preview.
Function Documentation
create_preview_widget()
static GtkWidget * create_preview_widget (void) static
Create textview for the RAM init preview hexdump.
We use a textview here and not a label since a textview communicates with its scrolled winded to determine what to render and what not. We used to render inside a label, which had the advantage of keeping the scrolled window at the position the user had scrolled to when updating the contents. The downside is that the view now scrolls back to the top when changing contents. But keep in mind it took 5-8 seconds on a Win10 VM with 2 cores at 3GHz to render, making the UI unresponsive during this time.
Returns
GtkTextView
Referenced by settings_ramreset_widget_create().
on_value_changed()
static void on_value_changed (GtkWidget * widget, gpointer data) static
Handler for the 'value-changed' event of the widgets in this dialog.
Updates the preview widget.
Parameters
[in] widget widget triggering the event (unused)
[in] data label for the preview
Referenced by settings_ramreset_widget_create().
settings_ramreset_widget_create()
GtkWidget * settings_ramreset_widget_create (GtkWidget * parent)
Create widget to control RAM init settings.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
< 100%
Todo:
Look into setting the size based on the contents/font size –compyx
Variable Documentation
powers_of_two
const vice_gtk3_combo_entry_int_t powers_of_two[] static
Initial value:
= {
    { "0 bytes",         0 },
    { "1 byte",          1 },
    { "2 bytes",         2 },
    { "4 bytes",         4 },
    { "8 bytes",         8 },
    { "16 bytes",       16 },
    { "32 bytes",       32 },
    { "64 bytes",       64 },
    { "128 bytes",     128 },
    { "256 bytes",     256 },
    { "512 bytes",     512 },
    { "1024 bytes",   1024 },
    { "2048 bytes",   2048 },
    { "4096 bytes",   4096 },
    { "8192 bytes",   8192 },
    { "16384 bytes", 16384 },
    { "32768 bytes", 32768 },
    { NULL,             -1 }
}
List of powers of two used for the widgets.
Yes, this looks silly, but allows me to use vice-gtk3 widgets.
Referenced by settings_ramreset_widget_create().
printbuffer
char printbuffer[(0x10000 *4)] static
Buffer used to print the raw text of the hexdump.
Referenced by on_value_changed().