vsid: c64/c64-memory-hacks.h File Reference
c64-memory-hacks.h File Reference
#include "snapshot.h"
#include "types.h"
Enumerations
enum {
MEMORY_HACK_NONE = 0 ,
MEMORY_HACK_C64_256K ,
MEMORY_HACK_PLUS60K ,
MEMORY_HACK_PLUS256K
}
Functions
int memory_hacks_ram_inject (uint16_t addr, uint8_t value)
int memory_hacks_resources_init (void)
int memory_hacks_cmdline_options_init (void)
int memhacks_snapshot_write_modules (struct snapshot_s *s)
int memhacks_snapshot_read_modules (struct snapshot_s *s)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MEMORY_HACK_NONE
MEMORY_HACK_C64_256K
MEMORY_HACK_PLUS60K
MEMORY_HACK_PLUS256K
Function Documentation
memhacks_snapshot_read_modules()
int memhacks_snapshot_read_modules (struct snapshot_s * s)
Referenced by c64_snapshot_read().
memhacks_snapshot_write_modules()
int memhacks_snapshot_write_modules (struct snapshot_s * s)
Referenced by c64_snapshot_write().
memory_hacks_cmdline_options_init()
int memory_hacks_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
memory_hacks_ram_inject()
int memory_hacks_ram_inject (uint16_t addr, uint8_t value)
Referenced by mem_inject().
memory_hacks_resources_init()
int memory_hacks_resources_init (void)
Referenced by machine_resources_init().