x128: c128/functionrom.h File Reference
functionrom.h File Reference
#include "types.h"
Enumerations
enum {
INT_FUNCTION_NONE = 0 ,
INT_FUNCTION_ROM ,
INT_FUNCTION_RAM ,
INT_FUNCTION_RTC
}
Functions
uint8_t internal_function_rom_read (uint16_t addr)
void internal_function_rom_store (uint16_t addr, uint8_t value)
void internal_function_top_shared_store (uint16_t addr, uint8_t value)
uint8_t internal_function_rom_peek (uint16_t addr)
int functionrom_resources_init (void)
void functionrom_resources_shutdown (void)
int functionrom_cmdline_options_init (void)
Variables
uint8_t int_function_rom []
Image of the internal function ROM.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
INT_FUNCTION_NONE
INT_FUNCTION_ROM
INT_FUNCTION_RAM
INT_FUNCTION_RTC
Function Documentation
functionrom_cmdline_options_init()
int functionrom_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
functionrom_resources_init()
int functionrom_resources_init (void)
Referenced by machine_resources_init().
functionrom_resources_shutdown()
void functionrom_resources_shutdown (void)
Referenced by machine_resources_shutdown().
internal_function_rom_peek()
uint8_t internal_function_rom_peek (uint16_t addr)
Todo:
FIXME: this RTC should have a peek function
return bq4830y_peek(rtc1_context, (uint16_t)(addr & 0x7fff));
Referenced by mem_bank_peek(), mem_peek_with_config_c128(), z80mem_chargen_rom_area_peek(), z80mem_editor_rom_area_peek(), z80mem_hi_rom_area_peek(), and z80mem_mid_rom_area_peek().
internal_function_rom_read()
uint8_t internal_function_rom_read (uint16_t addr)
< ltkernal.c
< ramlink.c
Referenced by c128meminit(), mem_bank_read(), mmu_ffxx_read(), z80mem_chargen_rom_area_read(), z80mem_editor_rom_area_read(), z80mem_hi_rom_area_read(), and z80mem_mid_rom_area_read().
internal_function_rom_store()
void internal_function_rom_store (uint16_t addr, uint8_t value)
< ltkernal.c
Referenced by c128meminit(), z80mem_chargen_rom_area_store(), z80mem_editor_rom_area_store(), z80mem_hi_rom_area_store(), and z80mem_mid_rom_area_store().
internal_function_top_shared_store()
void internal_function_top_shared_store (uint16_t addr, uint8_t value)
Referenced by c128meminit().
Variable Documentation
int_function_rom
uint8_t int_function_rom[] extern
Image of the internal function ROM.
Referenced by functionrom_load_internal(), internal_function_rom_peek(), internal_function_rom_read(), internal_function_rom_store(), internal_function_top_shared_store(), and set_internal_function_rom_enabled().