x128: arch/gtk3/widgets/mixerwidget.h File Reference
mixerwidget.h File Reference
GTK3 mixer widget for emus other than vsid - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
GtkWidget * mixer_widget_create (gboolean minimal, GtkAlign alignment)
Create mixer widget.
void mixer_widget_sid_type_changed (void)
Depending on what SID type is being used, show the right widgets.
Detailed Description
GTK3 mixer widget for emus other than vsid - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
mixer_widget_create()
GtkWidget * mixer_widget_create (gboolean minimal, GtkAlign alignment)
Create mixer widget.
Parameters
[in] minimal minimize side of sliders and labels
[in] alignment alignment of labels
Returns
GtkGrid
Referenced by settings_mixer_widget_create(), and ui_create_main_window().
mixer_widget_sid_type_changed()
void mixer_widget_sid_type_changed (void)
Depending on what SID type is being used, show the right widgets.
Referenced by mixer_widget_create(), on_reset_clicked(), settings_mixer_widget_create(), sid_model_callback(), and sid_model_widget_update().