x128: gfxoutputdrv/godotdrv.c File Reference
godotdrv.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "archdep.h"
#include "godotdrv.h"
#include "lib.h"
#include "log.h"
#include "gfxoutput.h"
#include "palette.h"
#include "screenshot.h"
#include "types.h"
#include "util.h"
#include "nativedrv.h"
Data Structures
struct gfxoutputdrv_data_s
Typedefs
typedef struct gfxoutputdrv_data_s gfxoutputdrv_data_t
Functions
static int godotdrv_write_file_header (screenshot_t *screenshot)
static int godotdrv_open (screenshot_t *screenshot, const char *filename)
static int godotdrv_write (screenshot_t *screenshot)
static int godotdrv_close (screenshot_t *screenshot)
static int godotdrv_save (screenshot_t *screenshot, const char *filename)
void gfxoutput_init_godot (int help)
Variables
static gfxoutputdrv_t godot_drv
static const unsigned char godotpalette [16]
Typedef Documentation
gfxoutputdrv_data_t
typedef struct gfxoutputdrv_data_s gfxoutputdrv_data_t
Function Documentation
gfxoutput_init_godot()
void gfxoutput_init_godot (int help)
Referenced by gfxoutput_early_init().
godotdrv_close()
static int godotdrv_close (screenshot_t * screenshot) static
Referenced by godotdrv_save().
godotdrv_open()
static int godotdrv_open (screenshot_t * screenshot, const char * filename) static
Referenced by godotdrv_save().
godotdrv_save()
static int godotdrv_save (screenshot_t * screenshot, const char * filename) static
godotdrv_write()
static int godotdrv_write (screenshot_t * screenshot) static
Referenced by godotdrv_save().
godotdrv_write_file_header()
static int godotdrv_write_file_header (screenshot_t * screenshot) static
Referenced by godotdrv_open().
Variable Documentation
godot_drv
static gfxoutputdrv_t godot_drv static
Initial value:
=
{
    GFXOUTPUTDRV_TYPE_SCREENSHOT_NATIVE,
    "4BT",
    "Godot screenshot",
    "4bt",
    NULL,
    godotdrv_open,
    godotdrv_close,
    godotdrv_write,
    godotdrv_save,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
}
Referenced by gfxoutput_init_godot(), and godotdrv_open().
godotpalette
const unsigned char godotpalette[16] static
Initial value:
={
    0, 15, 4, 12, 5, 10, 1, 13, 6, 2, 9, 3, 7, 14, 8, 11
}
Referenced by godotdrv_write().