vsid: c64/psid.h File Reference
psid.h File Reference
#include "types.h"
Functions
int psid_resources_init (void)
int psid_cmdline_options_init (void)
void psid_shutdown (void)
int psid_load_file (const char *filename)
void psid_init_tune (int install_driver_hook)
void psid_set_tune (int tune)
called from machine_play_psid
int psid_tunes (int *default_tune)
int psid_basic_rsid_to_autostart (uint16_t *address, uint8_t **data, uint16_t *length)
void psid_init_driver (void)
unsigned int psid_increment_frames (void)
int reloc65 (char **buf, int *fsize, int addr)
int psid_ui_set_tune (int, void *param)
used for setting the PSIDtune resource
Function Documentation
psid_basic_rsid_to_autostart()
int psid_basic_rsid_to_autostart (uint16_t * address, uint8_t ** data, uint16_t * length)
Referenced by machine_specific_reset().
psid_cmdline_options_init()
int psid_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
psid_increment_frames()
unsigned int psid_increment_frames (void)
Referenced by machine_vsync_hook().
psid_init_driver()
void psid_init_driver (void)
Todo:
FIXME: second chip model is ignored, but it is stored at (flags >> 6) & 3.
Referenced by machine_specific_reset(), play_current_tune(), psid_play_action(), psid_stop_action(), select_tune_from_menu(), and ui_vsid_window_load_psid().
psid_init_tune()
void psid_init_tune (int install_driver_hook)
Referenced by machine_specific_reset(), and machine_vsync_hook().
psid_load_file()
int psid_load_file (const char * filename)
< read mode (binary)
Referenced by machine_autodetect_psid(), play_current_tune(), and psid_play_action().
psid_resources_init()
int psid_resources_init (void)
Referenced by machine_resources_init().
psid_set_tune()
void psid_set_tune (int tune)
called from machine_play_psid
Referenced by machine_play_psid(), psid_init_driver(), and psid_ui_set_tune().
psid_shutdown()
void psid_shutdown (void)
Referenced by machine_specific_shutdown().
psid_tunes()
int psid_tunes (int * default_tune)
psid_ui_set_tune()
int psid_ui_set_tune (int tune, void * param)
used for setting the PSIDtune resource
reloc65()
int reloc65 (char ** buf, int * fsize, int addr)
< 16 bit header
< 16 bit header
Referenced by psid_init_driver().