vsid: cbmdos.c File Reference
cbmdos.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "cbmdos.h"
#include "lib.h"
#include "log.h"
Data Structures
struct cbmdos_errortext_s
Typedefs
typedef struct cbmdos_errortext_s cbmdos_errortext_t
Functions
const char * cbmdos_errortext (unsigned int code)
const char * cbmdos_filetype_get (unsigned int filetype)
unsigned int cbmdos_parse_wildcard_check (const char *name, unsigned int len)
unsigned int cbmdos_parse_wildcard_compare (const uint8_t *name1, const uint8_t *name2)
uint8_t * cbmdos_dir_slot_create (const char *name, unsigned int len)
unsigned int cbmdos_command_parse (cbmdos_cmd_parse_t *cmd_parse)
unsigned int cbmdos_command_parse_plus (cbmdos_cmd_parse_plus_t *cmd_parse)
Variables
static const cbmdos_errortext_t cbmdos_error_messages []
static const char *const cbmdos_ft []
Typedef Documentation
cbmdos_errortext_t
typedef struct cbmdos_errortext_s cbmdos_errortext_t
Function Documentation
cbmdos_command_parse()
unsigned int cbmdos_command_parse (cbmdos_cmd_parse_t * cmd_parse)
Referenced by fsdevice_open().
cbmdos_command_parse_plus()
unsigned int cbmdos_command_parse_plus (cbmdos_cmd_parse_plus_t * cmd_parse)
Todo:
CMD limits paths by having them begin and end with a '/'
Referenced by vdrive_command_copy(), vdrive_command_execute(), vdrive_command_format(), vdrive_command_rename(), vdrive_command_renamepart(), vdrive_command_scratch(), and vdrive_iec_open().
cbmdos_dir_slot_create()
uint8_t * cbmdos_dir_slot_create (const char * name, unsigned int len)
Referenced by cbmfile_find_file(), p00_file_find(), vdrive_dir_find_first_slot(), and vdrive_dir_part_find_first_slot().
cbmdos_errortext()
const char * cbmdos_errortext (unsigned int code)
Referenced by fsdevice_error(), and vdrive_command_set_error().
cbmdos_filetype_get()
const char * cbmdos_filetype_get (unsigned int filetype)
Referenced by diskcontents_block_read(), and vdrive_dir_next_directory().
cbmdos_parse_wildcard_check()
unsigned int cbmdos_parse_wildcard_check (const char * name, unsigned int len)
Referenced by cbmfile_open(), fsdevice_open_directory(), and fsdevice_open_file().
cbmdos_parse_wildcard_compare()
unsigned int cbmdos_parse_wildcard_compare (const uint8_t * name1, const uint8_t * name2)
Referenced by cbmfile_find_file(), p00_file_find(), vdrive_dir_name_match(), and vdrive_dir_part_name_match().
Variable Documentation
cbmdos_error_messages
const cbmdos_errortext_t cbmdos_error_messages[] static
Initial value:
=
{
    {  0, " OK" },
    {  1, "FILES SCRATCHED" },
    {  2, "SELECTED PARTITION" },
    {  3, "UNIMPLEMENTED" },
    { 20, "READ ERROR" },
    { 21, "READ ERROR" },
    { 22, "READ ERROR" },
    { 23, "READ ERROR" },
    { 24, "READ ERROR" },
    { 25, "WRITE ERROR" },
    { 26, "WRITE PROTECT ON" },
    { 27, "READ ERROR" },
    { 28, "WRITE ERROR" },
    { 29, "DISK ID MISMATCH" },
    { 30, "SYNTAX ERROR" },
    { 31, "SYNTAX ERROR" },
    { 32, "SYNTAX ERROR" },
    { 33, "SYNTAX ERROR" },
    { 34, "SYNTAX ERROR" },
    { 39, "FILE NOT FOUND" },
    { 50, "RECORD NOT PRESENT" },
    { 51, "OVERFLOW IN RECORD" },
    { 52, "FILE TOO LARGE" },
    { 60, "WRITE FILE OPEN" },
    { 61, "FILE NOT OPEN" },
    { 62, "FILE NOT FOUND" },
    { 63, "FILE EXISTS" },
    { 64, "FILE TYPE MISMATCH" },
    { 65, "NO BLOCK" },
    { 66, "ILLEGAL TRACK OR SECTOR" },
    { 67, "ILLEGAL SYSTEM T OR S" },
    { 70, "NO CHANNEL" },
    { 71, "DIRECTORY ERROR" },
    { 72, "DISK FULL" },
    { 73, "VIRTUAL DRIVE EMULATION V3.5" },
    { 74, "DRIVE NOT READY" },
    { 75, "FORMAT ERROR" },
    { 77, "SELECTED PARTITION ILLEGAL" },
    { 80, "DIRECTORY NOT EMPTY" },
    { 81, "PERMISSION DENIED" },
    { 255, NULL }
}
Referenced by cbmdos_errortext().
cbmdos_ft
const char* const cbmdos_ft[] static
Initial value:
= {
    "DEL", "SEQ", "PRG", "USR", "REL", "CBM", "DIR", "???"
}
Referenced by cbmdos_filetype_get().