x128: printerdrv/drv-1520.c File Reference
drv-1520.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include "archdep.h"
#include "driver-select.h"
#include "drv-1520.h"
#include "lib.h"
#include "log.h"
#include "output-select.h"
#include "output.h"
#include "palette.h"
#include "types.h"
Data Structures
struct plot_s
Macros
#define MAX_Y_COORD 998
#define MIN_Y_COORD -998
#define STEPS_PER_MM 5
#define MAX_COL 480
#define MAX_ROW (MAX_Y_COORD - MIN_Y_COORD + 1)
#define VERTICAL_CLEARANCE (10 * STEPS_PER_MM)
10 mm
#define PIXELS_PER_STEP 5
#define X_PIXELS (PIXELS_PER_STEP * (MAX_COL+1))
#define Y_PIXELS (PIXELS_PER_STEP * (MAX_ROW+1))
#define CR 13
#define SHIFT_CR (CR + 128)
#define LF 10
#define PIXEL_INDEX_WHITE 0
#define PIXEL_INDEX_BLACK 1
#define Assert(val, expr)
#define LINE_HEIGHT 10
line height
#define LW 4
letter width
#define SW 6
letter pitch
#define LH 7
letter height
#define INCOMPLETE 99999
#define FNUM_START 0x01
#define FNUM_MINUS 0x02
#define FNUM_DOT 0x04
#define FNUM_E 0x08
#define SZ (4 * STEPS_PER_MM)
Typedefs
typedef struct plot_s plot_t
Enumerations
enum command_stage {
start ,
letter_seen ,
x_seen ,
y_seen ,
skip_rest
}
Functions
static void reset_scribe_state (plot_t *mps)
static void write_lines (plot_t *mps, int lines)
1520 plotter engine.
static void reset_abs_origin (plot_t *mps)
static void set_rel_origin (plot_t *mps)
static void eject (plot_t *mps)
static int vice_min (int a, int b)
static void mix (uint8_t *old, int new)
Used in DEBUG code only.
static void plot (plot_t *mps, int x, int y)
static void bresenham (plot_t *mps, int x0, int y0, int x1, int y1)
static void bresenham_par (plot_t *mps, int x0, int y0, int x1, int y1, int wd)
static void draw (plot_t *mps, int from_x, int from_y, int to_x, int to_y)
static void draw_char (plot_t *mps, const char *commands)
static void move_left_side (plot_t *mps)
static void line_feed (plot_t *mps)
static void carriage_return (plot_t *mps)
static void print_char_cr (plot_t *mps)
static void print_char_shcr (plot_t *mps)
static void print_char_text (plot_t *mps, uint8_t c)
static int numparser (int *accu, uint8_t c)
static int fnumsparser (int *accu, int *state, uint8_t c)
static void print_char_plot (plot_t *mps, const uint8_t c)
static void print_char_select_colour (plot_t *mps, const uint8_t c)
static void print_char_select_character_size (plot_t *mps, const uint8_t c)
static void print_char_select_character_rotation (plot_t *mps, const uint8_t c)
static void print_char_select_scribe (plot_t *mps, const uint8_t c)
static void print_char_select_lowercase (plot_t *mps, const uint8_t c)
static void draw_one_square (plot_t *mps, int colour)
static void draw_four_squares (plot_t *mps)
static void power_on_reset (plot_t *mps)
static void print_char_reset (plot_t *mps, const uint8_t c)
static int drv_1520_open (unsigned int prnr, unsigned int secondary)
Interface to the upper layer.
static void drv_1520_close (unsigned int prnr, unsigned int secondary)
static int drv_1520_putc (unsigned int prnr, unsigned int secondary, uint8_t b)
static int drv_1520_getc (unsigned int prnr, unsigned int secondary, uint8_t *b)
static int drv_1520_flush (unsigned int prnr, unsigned int secondary)
static int drv_1520_formfeed (unsigned int prnr)
int drv_1520_init_resources (void)
int drv_1520_init (void)
void drv_1520_shutdown (void)
Variables
static plot_t drv_1520 [4]
static palette_t * palette = NULL
static log_t drv1520_log = ((log_t)-1)
Logging goes here.
static const uint8_t tochar []
static const char *const punct [32]
static const char *const uppercase [32]
typically 4 units wide, and 7 units high (baseline 1).
static const char *const lowercase [32]
Typically 3 units wide and 5 high (plus ascenders / descenders).
static const int dir [20]
Macro Definition Documentation
Assert
#define Assert (val, expr)
Value:
        do {  \
        if (!(expr)) {          \
            log_error(drv1520_log, "%s %d: assertion %s failed: %d", __FILE__, __LINE__, #expr, val);\
        }                       \
    } while (0)
CR
#define CR 13
FNUM_DOT
#define FNUM_DOT 0x04
FNUM_E
#define FNUM_E 0x08
FNUM_MINUS
#define FNUM_MINUS 0x02
FNUM_START
#define FNUM_START 0x01
INCOMPLETE
#define INCOMPLETE 99999
LF
#define LF 10
LH
#define LH 7
letter height
LINE_HEIGHT
#define LINE_HEIGHT 10
line height
LW
#define LW 4
letter width
MAX_COL
#define MAX_COL 480
MAX_ROW
#define MAX_ROW (MAX_Y_COORD - MIN_Y_COORD + 1)
MAX_Y_COORD
#define MAX_Y_COORD 998
MIN_Y_COORD
#define MIN_Y_COORD -998
PIXEL_INDEX_BLACK
#define PIXEL_INDEX_BLACK 1
PIXEL_INDEX_WHITE
#define PIXEL_INDEX_WHITE 0
PIXELS_PER_STEP
#define PIXELS_PER_STEP 5
SHIFT_CR
#define SHIFT_CR (CR + 128)
STEPS_PER_MM
#define STEPS_PER_MM 5
SW
#define SW 6
letter pitch
SZ
#define SZ (4 * STEPS_PER_MM)
VERTICAL_CLEARANCE
#define VERTICAL_CLEARANCE (10 * STEPS_PER_MM)
10 mm
X_PIXELS
#define X_PIXELS (PIXELS_PER_STEP * (MAX_COL+1))
Y_PIXELS
#define Y_PIXELS (PIXELS_PER_STEP * (MAX_ROW+1))
Typedef Documentation
plot_t
typedef struct plot_s plot_t
Enumeration Type Documentation
command_stage
enum command_stage
Enumerator
start
letter_seen
x_seen
y_seen
skip_rest
Function Documentation
bresenham()
static void bresenham (plot_t * mps, int x0, int y0, int x1, int y1) static
Referenced by bresenham_par().
bresenham_par()
static void bresenham_par (plot_t * mps, int x0, int y0, int x1, int y1, int wd) static
Referenced by draw().
carriage_return()
static void carriage_return (plot_t * mps) static
Referenced by print_char_cr(), and print_char_text().
draw()
static void draw (plot_t * mps, int from_x, int from_y, int to_x, int to_y) static
Referenced by draw_char(), draw_one_square(), and print_char_plot().
draw_char()
static void draw_char (plot_t * mps, const char * commands) static
< letter height
Todo:
this is probably not how it was really handled:
Referenced by print_char_text().
draw_four_squares()
static void draw_four_squares (plot_t * mps) static
Referenced by power_on_reset().
draw_one_square()
static void draw_one_square (plot_t * mps, int colour) static
< 4 mm
< 4 mm
< 4 mm
< 4 mm
< 4 mm
< 4 mm
< 4 mm
< 4 mm
< 4 mm
Referenced by draw_four_squares().
drv_1520_close()
static void drv_1520_close (unsigned int prnr, unsigned int secondary) static
Referenced by drv_1520_init_resources().
drv_1520_flush()
static int drv_1520_flush (unsigned int prnr, unsigned int secondary) static
Referenced by drv_1520_init_resources().
drv_1520_formfeed()
static int drv_1520_formfeed (unsigned int prnr) static
Referenced by drv_1520_init_resources().
drv_1520_getc()
static int drv_1520_getc (unsigned int prnr, unsigned int secondary, uint8_t * b) static
Referenced by drv_1520_init_resources().
drv_1520_init()
int drv_1520_init (void)
Referenced by printer_init().
drv_1520_init_resources()
int drv_1520_init_resources (void)
Referenced by printer_resources_init().
drv_1520_open()
static int drv_1520_open (unsigned int prnr, unsigned int secondary) static
Interface to the upper layer.
Referenced by drv_1520_init_resources().
drv_1520_putc()
static int drv_1520_putc (unsigned int prnr, unsigned int secondary, uint8_t b) static
Referenced by drv_1520_init_resources().
drv_1520_shutdown()
void drv_1520_shutdown (void)
Referenced by printer_shutdown().
eject()
static void eject (plot_t * mps) static
< 10 mm
Referenced by add_rom_chooser(), drv_1520_close(), drv_1520_formfeed(), and print_char_reset().
fnumsparser()
static int fnumsparser (int * accu, int * state, uint8_t c) static
Todo:
what to do here?
Referenced by print_char_plot().
line_feed()
static void line_feed (plot_t * mps) static
< line height
Referenced by carriage_return().
mix()
static void mix (uint8_t * old, int new) static
Used in DEBUG code only.
Referenced by plot().
move_left_side()
static void move_left_side (plot_t * mps) static
Referenced by carriage_return(), and print_char_shcr().
numparser()
static int numparser (int * accu, uint8_t c) static
Referenced by print_char_select_character_rotation(), print_char_select_character_size(), print_char_select_colour(), print_char_select_lowercase(), and print_char_select_scribe().
plot()
static void plot (plot_t * mps, int x, int y) static
Referenced by bresenham(), reSID::interpolate(), reSID::interpolate_brute_force(), and reSID::interpolate_forward_difference().
power_on_reset()
static void power_on_reset (plot_t * mps) static
< 10 mm
Referenced by drv_1520_open(), and print_char_reset().
print_char_cr()
static void print_char_cr (plot_t * mps) static
Referenced by print_char_text().
print_char_plot()
static void print_char_plot (plot_t * mps, const uint8_t c) static
Todo:
Q: what if not enough numbers are given? A: It seems that 0 is used.
!
Todo:
Q: what if the numbers are too large? >= 999 A1: x > 480: head tries to move there anyway; motor buzzes.
Referenced by drv_1520_putc().
print_char_reset()
static void print_char_reset (plot_t * mps, const uint8_t c) static
Referenced by drv_1520_putc().
print_char_select_character_rotation()
static void print_char_select_character_rotation (plot_t * mps, const uint8_t c) static
Referenced by drv_1520_putc().
print_char_select_character_size()
static void print_char_select_character_size (plot_t * mps, const uint8_t c) static
Referenced by drv_1520_putc().
print_char_select_colour()
static void print_char_select_colour (plot_t * mps, const uint8_t c) static
Referenced by drv_1520_putc().
print_char_select_lowercase()
static void print_char_select_lowercase (plot_t * mps, const uint8_t c) static
Referenced by drv_1520_putc().
print_char_select_scribe()
static void print_char_select_scribe (plot_t * mps, const uint8_t c) static
Referenced by drv_1520_putc().
print_char_shcr()
static void print_char_shcr (plot_t * mps) static
Referenced by print_char_text().
print_char_text()
static void print_char_text (plot_t * mps, uint8_t c) static
< letter pitch
Referenced by drv_1520_putc().
reset_abs_origin()
static void reset_abs_origin (plot_t * mps) static
Referenced by draw_four_squares(), and line_feed().
reset_scribe_state()
static void reset_scribe_state (plot_t * mps) static
Referenced by draw_char(), print_char_plot(), and reset_abs_origin().
set_rel_origin()
static void set_rel_origin (plot_t * mps) static
Referenced by draw_char(), and print_char_plot().
vice_min()
static int vice_min (int a, int b) inline static
Referenced by draw(), and draw_char().
write_lines()
static void write_lines (plot_t * mps, int lines) static
1520 plotter engine.
Referenced by eject(), and reset_abs_origin().
Variable Documentation
dir
const int dir[20] static
Initial value:
= {
     0,  0,
    -1, -1,
     0, -1,
     1, -1,
    -1,  0,
     0,  0,
     1,  0,
    -1,  1,
     0,  1,
     1,  1,
}
Referenced by add_dir_entry(), add_file_entry(), archdep_closedir(), archdep_opendir(), archdep_readdir(), archdep_readdir_get_dir(), archdep_readdir_get_entry(), archdep_readdir_get_file(), archdep_readdir_num_dirs(), archdep_readdir_num_entries(), archdep_readdir_num_files(), archdep_rewinddir(), archdep_seekdir(), archdep_telldir(), draw_char(), drive_sound_head(), event_box_scroll_cb(), fdd_seek_pulse(), find_next_directory_sector(), fsdevice_open_directory(), fsdevice_shutdown(), mon_show_dir(), monitor_completions(), on_launcher_clicked(), on_response(), prepend_dir_to_path(), romset_file_load(), scan_directory(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_lockunlock(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_renamepart(), vdrive_command_rmdir(), vdrive_command_scratch(), vdrive_command_switchtraverse(), vdrive_command_validate_worker(), vdrive_dir_find_first_slot(), vdrive_dir_find_next_slot(), vdrive_dir_part_find_first_slot(), vdrive_dir_part_find_next_slot(), vdrive_dir_remove_slot(), and write_geos_cmd().
drv1520_log
log_t drv1520_log = ((log_t)-1) static
Logging goes here.
Referenced by bresenham(), bresenham_par(), draw(), drv_1520_close(), drv_1520_flush(), drv_1520_formfeed(), drv_1520_init(), drv_1520_init_resources(), drv_1520_open(), drv_1520_putc(), drv_1520_shutdown(), eject(), plot(), print_char_plot(), print_char_select_scribe(), reset_abs_origin(), and write_lines().
drv_1520
plot_t drv_1520[4] static
Referenced by drv_1520_close(), drv_1520_formfeed(), drv_1520_open(), and drv_1520_putc().
lowercase
const char* const lowercase[32] static
Initial value:
= {
     "8888 d 6666666",
     "996 d 1478963 u 774 d 663223",
     "8888888 d 22222266988744",
     "996 d 14788963",
     "99988 d 44122366888888",
     "888 d 666874122366",
     "96 d 8888886 u 112 d 66",
     "8 d 3698887412369",
     "8 d 888888 u 22 d 663222",
     "69 d 888 u 8 d 8",
     "8 d 369888 u 8 d 8",
     "669 d 77 u 7888 d 222222 u 8 d 999",
     "8888889 d 222222 6",
     "8 d 8888 u 2 d 93222 u 888 d 93222",
     "8 d 8888 2 963222",
     "88 d 8896322147",
     "88 d 669874422222",
     "6666 d 4888884412366",
     "88888 d 3222 u 888 d 96",
     "88 d 369747963",
     "88888 d 66 u 78 d 2222226",
     "88888 d 22226668888",
     "88888 d 22339988",
     "88888 d 22239 82 39888",
     "8 d 9999 u 4444 d 3333",
     "88888 d 233 u 998 d 21111",
     "88888 d 666611116666",
     "666 d 8888888",
     "d 6666666",
     "8 d 999333 444444",
     "888 d 966222 u 44 d 888669",
     "8 d 8888886666622222244444",
}
Typically 3 units wide and 5 high (plus ascenders / descenders).
Referenced by print_char_text(), vice_gtk3_petscii_to_utf8(), vice_gtk3_petscii_to_utf8_petme(), vice_gtk3_petscii_to_utf8_petme64(), vice_gtk3_scrcode_to_utf8(), vice_gtk3_scrcode_to_utf8_petme(), and vice_gtk3_scrcode_to_utf8_petme64().
palette
palette_t* palette = NULL static
Referenced by create_layout(), drv_1520_close(), drv_1520_init(), drv_1520_open(), drv_1520_shutdown(), palette_save(), vice_opengl_set_palette(), video_canvas_palette_set(), video_canvas_set_palette(), video_color_palette_free(), video_color_update_palette(), and video_load_palette().
punct
const char* const punct[32] static
Initial value:
= {
     NULL,
     "96 d 8624 u 88 d 8888622224",
     "9888888 d 2 u 96 d 2",
     "98 d 8888 u 66 d 2222 u 9 d 4444 u 88 d 6666",
     "98 d 6697447966 u 7 d 222222",
     "88 d 9999 u 444 d 4268 u 332 d 6248",
     "9666 d 777789321123699",
     "88899 d 88",
     "966 d 47888896",
     "96  d 69888874",
     "88 d 9999 u 4444 d 3333 u 7788 d 2222",
     "99 d 8888 u 11 d 6666",
     "66 d 98426",
     "8888 d 6666",
     "96 d 8624",
     "8 d 99999",
     "88 d 9999 74412222 36698888",
     "988888 d 9222222 u 4 d 66",
     "888888 d 9663211116666",
     "888888 d 9663214 u 6 d 321447",
     "9996 d 44448999222222",
     "88 d 3669887444886666",
     "8888 d 966322144788889663",
     "8 d 9999884444",
     "8889 d 789663213214478966",
     "88 d 36698888744123669",
     "89 d 8624 u 888 d 8624",
     "9 d 98426 u 888 d 8426",
     "9666 d 777999",
     "988 d 666 u 774 d 666",
     "8 d 999777",
     "888888 d 96632142 u 2 d 2"
}
Referenced by print_char_text().
tochar
const uint8_t tochar[] static
Initial value:
= {
     ' ' ,
     '*' ,
     'B' ,
     'G' ,
     'R' ,
}
Referenced by write_lines().
uppercase
const char* const uppercase[32] static
Initial value:
= {
     "999 d 884422266 98874412223666",
     "8 d 888899332222 u 888 d 4444",
     "8 d 888888666321444 u 666 d 321444",
     "9966 d 144788889663",
     "8 d 888888666322221444",
     "9666 d 4444 888888 6666 u 122 d 444",
     "8 d 8888886666 u 1114 d 666",
     "999988 d 74412222366688844",
     "8 d 888888 u 6666 d 222222 u 7774 d 6666",
     "9 d 66 u 4 d 888888 u 4 d 66",
     "88 d 36988888",
     "8 d 888888 u 6666 d 1111 u 9 d 333",
     "8888888 d 222222 6666",
     "8 d 88888833 28 99222222",
     "8 d 888888 u 2 d 3333 u 88888 d 222222",
     "88 d 8888966322221447",
     "8 d 888888666321444",
     "998 d 33 u 4 d 4478888966322221",
     "8 d 888888666321444 u 6 d 333",
     "88 d 36698744789663",
     "96 d 888888 u 44 d 6666",
     "8888888 d 22222366988888",
     "8888888 d 222233998888",
     "8888888 d 22222299 u 8 d 233888888",
     "8 d 899998 u 4444 d 233332 ",
     "69 d 888998 u 4444 d 233",
     "8888888 d 66662111126666",
     "69 d 44 888888 66",
 "999998 d 4122214793366 u 777 d 66",
     "9 d 66 888888 44 ",
     "69 d 88888 11 u 99 d 33",
     "99 d 7799 u 11 d 66666",
}
typically 4 units wide, and 7 units high (baseline 1).
Referenced by print_char_text().