x128: ram.h File Reference
ram.h File Reference
#include "types.h"
Data Structures
struct _RAMINITPARAM
Macros
#define RAM_INIT_RANDOM_CHANCE_MAX 10000
100%
#define RAM_INIT_RANDOM_CHANCE_DEFAULT 10
0.1%
Typedefs
typedef struct _RAMINITPARAM RAMINITPARAM
Functions
int ram_resources_init (void)
int ram_cmdline_options_init (void)
void ram_init (uint8_t *memram, unsigned int ramsize)
used to initialize the main memory of the machine
void ram_init_with_pattern (uint8_t *memram, unsigned int ramsize, RAMINITPARAM *ramparam)
this can be used to init arbitrary memory
void ram_init_print_pattern (char *s, int len, char *eol)
Macro Definition Documentation
RAM_INIT_RANDOM_CHANCE_DEFAULT
#define RAM_INIT_RANDOM_CHANCE_DEFAULT 10
0.1%
RAM_INIT_RANDOM_CHANCE_MAX
#define RAM_INIT_RANDOM_CHANCE_MAX 10000
100%
Typedef Documentation
RAMINITPARAM
typedef struct _RAMINITPARAM RAMINITPARAM
Function Documentation
ram_cmdline_options_init()
int ram_cmdline_options_init (void)
Referenced by init_cmdline_options().
ram_init()
void ram_init (uint8_t * memram, unsigned int ramsize)
used to initialize the main memory of the machine
Referenced by mem_powerup(), and ram_init_print_pattern().
ram_init_print_pattern()
void ram_init_print_pattern (char * s, int len, char * eol)
Referenced by on_value_changed().
ram_init_with_pattern()
void ram_init_with_pattern (uint8_t * memram, unsigned int ramsize, RAMINITPARAM * ramparam)
this can be used to init arbitrary memory
< 100%
< 100%
< 100%
< 100%
< 100%
Referenced by ram_init().
ram_resources_init()
int ram_resources_init (void)
Todo:
FIXME: tweak and test defaults for the various machines
< 0.1%
< 0.1%
Referenced by init_resources().