vsid: drive/iec/cia1571d.c File Reference
cia1571d.c File Reference
#include "vice.h"
#include <stdio.h>
#include "cia.h"
#include "ciad.h"
#include "drivetypes.h"
#include "iecdrive.h"
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "types.h"
Data Structures
struct drivecia1571_context_s
Typedefs
typedef struct drivecia1571_context_s drivecia1571_context_t
Functions
void cia1571_store (diskunit_context_t *ctxptr, uint16_t addr, uint8_t data)
uint8_t cia1571_read (diskunit_context_t *ctxptr, uint16_t addr)
uint8_t cia1571_peek (diskunit_context_t *ctxptr, uint16_t addr)
int cia1571_dump (diskunit_context_t *ctxptr, uint16_t addr)
void mos5710_store (diskunit_context_t *ctxptr, uint16_t addr, uint8_t data)
uint8_t mos5710_read (diskunit_context_t *ctxptr, uint16_t addr)
uint8_t mos5710_peek (diskunit_context_t *ctxptr, uint16_t addr)
int mos5710_dump (diskunit_context_t *ctxptr, uint16_t addr)
static void cia_set_int_clk (cia_context_t *cia_context, int value, CLOCK clk)
static void cia_restore_int (cia_context_t *cia_context, int value)
static void do_reset_cia (cia_context_t *cia_context)
static void pulse_ciapc (cia_context_t *cia_context, CLOCK rclk)
static void undump_ciapa (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static void undump_ciapb (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static void store_ciapa (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static void store_ciapb (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static uint8_t read_ciapa (cia_context_t *cia_context)
static uint8_t read_ciapb (cia_context_t *cia_context)
static void read_ciaicr (cia_context_t *cia_context)
static void read_sdr (cia_context_t *cia_context)
static void store_sdr (cia_context_t *cia_context, uint8_t byte)
void cia1571_init (diskunit_context_t *ctxptr)
void cia1571_setup_context (diskunit_context_t *ctxptr)
void cia1571_set_timing (cia_context_t *cia_context, int tickspersec, int powerfreq)
Typedef Documentation
drivecia1571_context_t
typedef struct drivecia1571_context_s drivecia1571_context_t
Function Documentation
cia1571_dump()
int cia1571_dump (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by drivemem_ioreg_list_get().
cia1571_init()
void cia1571_init (diskunit_context_t * ctxptr)
Referenced by iec_drive_init().
cia1571_peek()
uint8_t cia1571_peek (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by memiec_init().
cia1571_read()
uint8_t cia1571_read (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by memiec_init().
cia1571_set_timing()
void cia1571_set_timing (cia_context_t * cia_context, int tickspersec, int powerfreq)
Referenced by cia1571_setup_context().
cia1571_setup_context()
void cia1571_setup_context (diskunit_context_t * ctxptr)
Referenced by iec_drive_setup_context().
cia1571_store()
void cia1571_store (diskunit_context_t * ctxptr, uint16_t addr, uint8_t data)
Referenced by memiec_init().
cia_restore_int()
static void cia_restore_int (cia_context_t * cia_context, int value) static
Referenced by cia1571_setup_context().
cia_set_int_clk()
static void cia_set_int_clk (cia_context_t * cia_context, int value, CLOCK clk) static
Referenced by cia1571_setup_context().
do_reset_cia()
static void do_reset_cia (cia_context_t * cia_context) static
Referenced by cia1571_setup_context().
mos5710_dump()
int mos5710_dump (diskunit_context_t * ctxptr, uint16_t addr)
Todo:
extra MFM registers
Referenced by drivemem_ioreg_list_get().
mos5710_peek()
uint8_t mos5710_peek (diskunit_context_t * ctxptr, uint16_t addr)
Todo:
FIXME: need to confirm how it actually mirrors on the real drive
Todo:
extra MFM registers
Todo:
FIXME: all other registers are not implemented
Referenced by memiec_init().
mos5710_read()
uint8_t mos5710_read (diskunit_context_t * ctxptr, uint16_t addr)
Todo:
FIXME: need to confirm how it actually mirrors on the real drive
Todo:
extra MFM registers
Todo:
FIXME: all other registers are not implemented
Referenced by memiec_init().
mos5710_store()
void mos5710_store (diskunit_context_t * ctxptr, uint16_t addr, uint8_t data)
Todo:
FIXME: need to confirm how it actually mirrors on the real drive
Todo:
extra MFM registers
Referenced by memiec_init().
pulse_ciapc()
static void pulse_ciapc (cia_context_t * cia_context, CLOCK rclk) static
< speed-dos userport cable
< speed-dos userport cable
< set flag (cia2)
Referenced by cia1571_setup_context().
read_ciaicr()
static void read_ciaicr (cia_context_t * cia_context) static
Referenced by cia1571_setup_context().
read_ciapa()
static uint8_t read_ciapa (cia_context_t * cia_context) static
< Data direction register for port A
< Port A
< Data direction register for port A
Referenced by cia1571_setup_context().
read_ciapb()
static uint8_t read_ciapb (cia_context_t * cia_context) static
< speed-dos userport cable
< Data direction register for port B
< Port B
< Data direction register for port B
Referenced by cia1571_setup_context().
read_sdr()
static void read_sdr (cia_context_t * cia_context) static
Referenced by cia1571_setup_context().
store_ciapa()
static void store_ciapa (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
Referenced by cia1571_setup_context().
store_ciapb()
static void store_ciapb (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
< speed-dos userport cable
< speed-dos userport cable
< write data
Referenced by cia1571_setup_context().
store_sdr()
static void store_sdr (cia_context_t * cia_context, uint8_t byte) static
Referenced by cia1571_setup_context().
undump_ciapa()
static void undump_ciapa (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
Referenced by cia1571_setup_context().
undump_ciapb()
static void undump_ciapb (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
< speed-dos userport cable
< speed-dos userport cable
< write data
Referenced by cia1571_setup_context().