vsid: util.c File Reference
util.c File Reference
#include "vice.h"
#include <assert.h>
#include <ctype.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <strings.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "util.h"
Macros
#define _FILE_OFFSET_BITS 64
#define DBG(x)
#define _CONCAT_MAX_ARGS 128
#define BUFCAT_GRANULARITY 0x1000
Functions
char * util_concat (const char *s,...)
char * util_strjoin (const char **list, const char *sep)
Join the strings in list with sep as separator.
void util_addline (char **list, const char *line)
Add a line to a string.
void util_addline_free (char **list, char *line)
Add a line to a string and free the line.
uint8_t * util_bufcat (uint8_t *buf, int *buf_size, size_t *max_buf_size, const uint8_t *src, int src_size)
void util_remove_spaces (char *s)
int util_string_set (char **str, const char *new_value)
int util_check_null_string (const char *string)
int util_check_filename_access (const char *filename)
char * util_subst (const char *s, const char *string, const char *replacement)
int util_file_load (const char *name, uint8_t *dest, size_t size, unsigned int load_flag)
int util_file_load_string (FILE *fd, char **dest)
int util_file_save (const char *name, uint8_t *src, int size)
int util_get_line (char *buf, int bufsize, FILE *f)
void util_fname_split (const char *path, char **directory_return, char **name_return)
int util_fpread (FILE *fd, void *buf, size_t num, long offset)
Read bytes from a position in a file.
int util_fpwrite (FILE *fd, const void *buf, size_t num, long offset)
Write bytes to a position in a file.
void util_dword_to_be_buf (uint8_t *buf, uint32_t data)
void util_dword_to_le_buf (uint8_t *buf, uint32_t data)
uint32_t util_le_buf_to_dword (uint8_t *buf)
uint32_t util_be_buf_to_dword (uint8_t *buf)
void util_int_to_be_buf4 (uint8_t *buf, int data)
void util_int_to_le_buf4 (uint8_t *buf, int data)
int util_le_buf4_to_int (uint8_t *buf)
int util_be_buf4_to_int (uint8_t *buf)
void util_word_to_be_buf (uint8_t *buf, uint16_t data)
void util_word_to_le_buf (uint8_t *buf, uint16_t data)
uint16_t util_le_buf_to_word (uint8_t *buf)
uint16_t util_be_buf_to_word (uint8_t *buf)
int util_file_exists (const char *name)
Check for existance of file named ‘name’.
char * util_find_next_line (const char *pos)
char * util_find_prev_line (const char *text, const char *pos)
void util_add_extension (char **name, const char *extension)
Add extension to a\ name if missing.
char * util_add_extension_const (const char *filename, const char *extension)
Like util_add_extension() but a const filename is passed.
void util_add_extension_maxpath (char *name, const char *extension, unsigned int maxpath)
char * util_get_extension (const char *filename)
char util_tolower (char c)
char util_toupper (char c)
const char * util_skip_whitespace (const char *s)
Skip leading whitespace in string.
const char * util_skip_whitespace_trailing (const char *s)
Skip trailing whitespace in string.
char * util_gen_hex_address_list (int start, int stop, int step)
generate a list in the form "%X/%X/.../%X"
char * util_join_paths (const char *path,...)
Join multiple paths into a single path.
int util_strcasecmp (const char *s1, const char *s2)
Compare strings, ignoring case.
int util_strncasecmp (const char *s1, const char *s2, size_t n)
Compare strings, ignoring case, comparing at most n chars.
char ** util_strsplit (const char *string, const char *delimiter, int max_tokens)
Split string into substrings.
Detailed Description
Author
Ettore Perazzoli, Andreas Boose
Miscellaneous utility functions.
util.c - Miscellaneous utility functions.
Written by Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Macro Definition Documentation
_CONCAT_MAX_ARGS
#define _CONCAT_MAX_ARGS 128
_FILE_OFFSET_BITS
#define _FILE_OFFSET_BITS 64
BUFCAT_GRANULARITY
#define BUFCAT_GRANULARITY 0x1000
DBG
#define DBG (x)
Function Documentation
util_add_extension()
void util_add_extension (char ** name, const char * extension)
Add extension to a\ name if missing.
Parameters
[in,out] name input and final 'string'
[in] extension extension to add to name
Warning
Since adding extension can trigger a realloc(3) of *name, make sure to handle the output pointer properly.
Referenced by create_combo_box(), palette_load(), and util_add_extension_const().
util_add_extension_const()
char * util_add_extension_const (const char * filename, const char * extension)
Like util_add_extension() but a const filename is passed.
Referenced by artstudio_render_and_save(), bmpdrv_open(), create_disk_image(), create_tape_image(), godotdrv_open(), iffdrv_open(), koala_render_and_save(), minipaint_render_and_save(), pcxdrv_open(), playlist_save_dialog_callback(), ppmdrv_open(), romset_archive_save(), romset_file_save(), save_as_callback(), save_filename_callback(), and save_snapshot_dialog().
util_add_extension_maxpath()
void util_add_extension_maxpath (char * name, const char * extension, unsigned int maxpath)
util_addline()
void util_addline (char ** list, const char * line)
Add a line to a string.
Referenced by util_addline_free().
util_addline_free()
void util_addline_free (char ** list, char * line)
Add a line to a string and free the line.
Referenced by romset_archive_list(), and romset_file_list().
util_be_buf4_to_int()
int util_be_buf4_to_int (uint8_t * buf)
util_be_buf_to_dword()
uint32_t util_be_buf_to_dword (uint8_t * buf)
Referenced by crt_open(), crt_read_chip_header(), and util_be_buf4_to_int().
util_be_buf_to_word()
uint16_t util_be_buf_to_word (uint8_t * buf)
Referenced by crt_open(), and crt_read_chip_header().
util_bufcat()
uint8_t * util_bufcat (uint8_t * buf, int * buf_size, size_t * max_buf_size, const uint8_t * src, int src_size)
Referenced by serial_iec_lib_directory().
util_check_filename_access()
int util_check_filename_access (const char * filename)
< read mode (binary)
< write mode (binary)
Referenced by set_c64_256k_filename(), set_plus256k_filename(), set_plus60k_filename(), and set_sample_name().
util_check_null_string()
int util_check_null_string (const char * string)
Referenced by c64_256k_activate(), c64_256k_deactivate(), crc32_file(), plus256k_activate(), plus256k_deactivate(), plus60k_activate(), plus60k_deactivate(), print_help_details(), print_help_topics(), set_drive_fixed(), util_file_load(), and util_file_save().
util_concat()
char * util_concat (const char * s, ...)
Referenced by advance_hastape(), advance_outfile_name(), archdep_default_autostart_disk_image_file_name(), archdep_default_fliplist_file_name(), archdep_expand_path(), archdep_extra_title_text(), archdep_filename_parameter(), archdep_make_backup_filename(), archdep_mkstemp_fd(), archdep_quote_parameter(), archdep_quote_unzip(), build_printer_output_names(), build_sid_cmdline_option(), build_tapeport_string(), build_userport_string(), cmdline_log_active(), cmdline_options_string(), create_disk_image(), create_file_chooser_filter(), create_model(), dir_menu_popup_create(), event_snapshot_path(), fsdevice_flush_mkdir(), fsdevice_flush_rmdir(), fsdevice_open_file(), generate_sid_address_range(), io_source_log_collisions(), io_source_msg_detach_all(), io_source_msg_detach_last(), keyboard_get_keymap_name(), main_program(), mon_show_dir(), output_graphics_open(), p00_filename_create(), prepend_dir_to_path(), raster_cmdline_options_chip_init(), raster_resources_chip_init(), rawfile_open(), rawfile_remove(), rawfile_rename(), sampler_cmdline_options_init(), scan_directory(), set_chip_rendermode(), set_event_snapshot_dir(), set_system_path(), sound_cmdline_options_init(), sysfile_load(), uidata_get_bytes(), uidata_get_pixbuf(), uidata_get_pixbuf_at_scale(), util_addline(), util_gen_hex_address_list(), video_cmdline_options_chip_init(), and video_resources_chip_init().
util_dword_to_be_buf()
void util_dword_to_be_buf (uint8_t * buf, uint32_t data)
Referenced by crt_create(), crt_create_v11(), crt_create_v20(), crt_write_chip(), iffdrv_write_file_header(), and util_int_to_be_buf4().
util_dword_to_le_buf()
void util_dword_to_le_buf (uint8_t * buf, uint32_t data)
Referenced by bmpdrv_write_bitmap_info(), bmpdrv_write_file_header(), fsimage_create_gcr(), fsimage_gcr_write_half_track(), network_create_event_buffer(), network_event_record_sync_test(), tap_close(), tap_create(), and util_int_to_le_buf4().
util_file_exists()
int util_file_exists (const char * name)
Check for existance of file named ‘name’.
< read mode (binary)
Referenced by advance_outfile_name(), autostart_autodetect_opt_prgname(), p00_file_create(), and resources_save().
util_file_load()
int util_file_load (const char * name, uint8_t * dest, size_t size, unsigned int load_flag)
< read mode (binary)
Referenced by c64_256k_activate(), plus256k_activate(), and plus60k_activate().
util_file_load_string()
int util_file_load_string (FILE * fd, char ** dest)
Referenced by create_shader_program().
util_file_save()
int util_file_save (const char * name, uint8_t * src, int size)
< write mode (binary)
Referenced by c64_256k_activate(), c64_256k_deactivate(), plus256k_activate(), plus256k_deactivate(), plus60k_activate(), and plus60k_deactivate().
util_find_next_line()
char * util_find_next_line (const char * pos)
util_find_prev_line()
char * util_find_prev_line (const char * text, const char * pos)
util_fname_split()
void util_fname_split (const char * path, char ** directory_return, char ** name_return)
< directory separator as an integer
Referenced by autostart_prg(), autostart_prg_with_virtual_fs(), dir_menu_popup_create(), event_record_attach_in_list(), fileio_open(), fliplist_load_list(), fliplist_save_list(), m3u_open(), rawfile_open(), romset_archive_load(), romset_file_load(), try_uncompress_zipcode(), and ui_populate_fliplist_menu().
util_fpread()
int util_fpread (FILE * fd, void * buf, size_t num, long offset)
Read bytes from a position in a file.
Parameters
fd file descriptor as obtained by fopen().
buf pointer where to from the file
num number of bytes to read.
offset the offset from start of file
Returns
0 on success, else -1.
Referenced by disk_image_check_for_d64(), disk_image_check_for_d71(), disk_image_check_for_d81(), disk_image_check_for_gcr(), disk_image_check_for_p64(), fsimage_dxx_read_sector(), fsimage_gcr_read_half_track(), fsimage_gcr_seek_half_track(), fsimage_read_dxx_image(), and fsimage_read_p64_image().
util_fpwrite()
int util_fpwrite (FILE * fd, const void * buf, size_t num, long offset)
Write bytes to a position in a file.
Parameters
fd file descriptor as obtained by fopen().
buf pointer to the data to be written to the file
num number of bytes to write.
offset the offset from start of file
Returns
0 on success, else -1.
Referenced by fsimage_dxx_write_half_track(), fsimage_dxx_write_sector(), fsimage_gcr_write_half_track(), fsimage_write_p64_image(), and tap_close().
util_gen_hex_address_list()
char * util_gen_hex_address_list (int start, int stop, int step)
generate a list in the form "%X/%X/.../%X"
Referenced by generate_sid_address_range().
util_get_extension()
char * util_get_extension (const char * filename)
Referenced by create_combo_box(), disk_image_check_for_d1m(), and disk_image_check_for_d81().
util_get_line()
int util_get_line (char * buf, int bufsize, FILE * f)
Referenced by check_resource_file_version(), load_resource_file(), palette_load_core(), palette_read_tag(), resources_read_item_from_file(), and resources_save().
util_int_to_be_buf4()
void util_int_to_be_buf4 (uint8_t * buf, int data)
util_int_to_le_buf4()
void util_int_to_le_buf4 (uint8_t * buf, int data)
Referenced by network_hook_connected_send(), and network_server_connect_trap().
util_join_paths()
char * util_join_paths (const char * path, ...)
Join multiple paths into a single path.
Joins a list of strings into a path for use with the current arch
Parameters
[in] path list of paths to join, NULL-terminated
Returns
heap-allocated string, free with lib_free()
< directory separator as an integer
< directory separator as an integer
Referenced by archdep_create_user_cache_dir(), archdep_create_user_config_dir(), archdep_default_autostart_disk_image_file_name(), archdep_default_fliplist_file_name(), archdep_default_joymap_file_name(), archdep_default_logfile(), archdep_default_portable_resource_file_name(), archdep_default_resource_file_name(), archdep_default_rtc_file_name(), archdep_default_sysfile_pathlist(), archdep_get_vice_datadir(), archdep_get_vice_docsdir(), archdep_get_vice_drivesdir(), archdep_get_vice_hotkeysdir(), archdep_get_vice_machinedir(), archdep_user_cache_path(), archdep_user_config_path(), archdep_user_state_path(), archdep_xdg_cache_home(), archdep_xdg_config_home(), archdep_xdg_data_home(), archdep_xdg_state_home(), argv_fallback(), get_config_file_path(), help_manual_action(), mon_file_open(), on_resource_browser_browse_clicked(), palette_get_info_list(), palette_read_info(), prepend_current_dir(), quicksnap_filename(), ui_hotkeys_load_vice_default(), ui_hotkeys_save_dialog_show(), ui_hotkeys_vhk_full_path_user(), ui_hotkeys_vhk_full_path_vice(), and update_current_dir().
util_le_buf4_to_int()
int util_le_buf4_to_int (uint8_t * buf)
Referenced by network_client_connect_trap(), network_connect_client(), and network_hook_connected_receive().
util_le_buf_to_dword()
uint32_t util_le_buf_to_dword (uint8_t * buf)
Referenced by fsimage_gcr_seek_half_track(), network_create_event_list(), and util_le_buf4_to_int().
util_le_buf_to_word()
uint16_t util_le_buf_to_word (uint8_t * buf)
Referenced by disk_image_check_for_gcr(), fsimage_gcr_read_half_track(), fsimage_gcr_seek_half_track(), and vdrive_command_memory().
util_remove_spaces()
void util_remove_spaces (char * s)
Referenced by set_drive_fixed().
util_skip_whitespace()
const char * util_skip_whitespace (const char * s)
Skip leading whitespace in string.
Parameters
[in] s string
Returns
pointer to first non-whitespace character or terminating nul
Referenced by m3u_append_entry(), m3u_parse(), playlist_directive_handler(), playlist_entry_handler(), vhk_parser_do_debug(), vhk_parser_do_if(), vhk_parser_do_include(), vhk_parser_do_undef(), vhk_parser_do_warning(), vhk_parser_handle_mapping(), and vhk_parser_strtrim().
util_skip_whitespace_trailing()
const char * util_skip_whitespace_trailing (const char * s)
Skip trailing whitespace in string.
Parameters
[in] s string
Returns
pointer to first non-whitespace character or terminating nul, starting from the end of the string
Referenced by vhk_parser_strtrim().
util_strcasecmp()
int util_strcasecmp (const char * s1, const char * s2)
Compare strings, ignoring case.
Parameters
[in] s1 string to compare
[in] s2 string to compare
Returns
-1 if s1 < s2, 0 if s1 == s2, 1 if s1 > s2
Note
Does naive case-folding, so don't rely on this for sorting strings in non-ASCII encoding (for example when e-umlaut exists but E-umlaut doesn't exist)
Referenced by autostart_prg(), autostart_prg_with_disk_image(), file_is_gzip(), is_valid_extension(), lookup(), mon_assemble_instr(), mon_command_lookup_index(), palette_find_name(), palette_get_info_list(), sound_open(), try_uncompress_archive(), try_uncompress_with_bzip(), try_uncompress_with_tzx(), util_add_extension(), and util_add_extension_maxpath().
util_string_set()
int util_string_set (char ** str, const char * new_value)
Referenced by ata_image_attach(), keyboard_set_keymap_file(), keymap_resources_init(), set_aspect_ratio(), set_autosave_screenshot_format(), set_autostart_prg_disk_image(), set_basic_rom_name(), set_binary_server_address(), set_c64_256k_filename(), set_chargen_rom_name(), set_container_format(), set_devfile(), set_device_arg(), set_device_name(), set_dos_rom_name_1540(), set_dos_rom_name_1541(), set_dos_rom_name_1541ii(), set_dos_rom_name_1570(), set_dos_rom_name_1571(), set_dos_rom_name_1581(), set_dos_rom_name_2000(), set_dos_rom_name_4000(), set_dos_rom_name_CMDHD(), set_event_end_snapshot(), set_event_snapshot_dir(), set_event_start_snapshot(), set_exit_screenshot_name(), set_exit_screenshot_name1(), set_fliplist_file_name(), set_fsdevice_dir(), set_hvsc_root(), set_kernal_rom_name(), set_log_file_name(), set_monitor_bg(), set_monitor_fg(), set_monitor_font(), set_monitor_log_filename(), set_palette_file_name(), set_plus256k_filename(), set_plus60k_filename(), set_printer_device_name(), set_recorddevice_arg(), set_recorddevice_name(), set_sample_name(), set_server_address(), set_server_bind_address(), set_server_name(), set_system_path(), try_set_keymap_file(), ui_hotkeys_load(), ui_hotkeys_save_as(), vhk_filename_set(), and video_resources_chip_init().
util_strjoin()
char * util_strjoin (const char ** list, const char * sep)
Join the strings in list with sep as separator.
Parameters
[in] list list of strings, NULL-terminated
[in] sep separator string (optional)
Example:
const char **list[] = { "foo", "bar", "meloen", NULL };
char *s = util_strjoin(list, ";");
// returns: foo;bar;meloen
Returns
heap-allocated string, deallocate with lib_free()
Referenced by archdep_default_sysfile_pathlist(), create_file_chooser_filter(), and vice_gtk3_resource_filechooser_set_filter().
util_strncasecmp()
int util_strncasecmp (const char * s1, const char * s2, size_t n)
Compare strings, ignoring case, comparing at most n chars.
Parameters
[in] s1 string to compare
[in] s2 string to compare
Returns
-1 if s1 < s2, 0 if s1 == s2, 1 if s1 > s2
Note
Does naive case-folding, so don't rely on this for sorting strings in non-ASCII encoding (for example when e-umlaut exists but E-umlaut doesn't exist)
Referenced by get_directive_id(), and vhk_parser_do_debug().
util_strsplit()
char ** util_strsplit (const char * string, const char * delimiter, int max_tokens)
Split string into substrings.
Split string into substrings on delimiter, returning at most max_tokens substrings, plus the remainder as a final substring if there is anything left in string. The delimiter is not among the substrings, except in the remainder if there is a remainder.
If string is NULL or "" NULL is returned. If \a delimiter isNULL` or "" an array of a single element is returned, with the single element being a copy of the full string. If max_tokens is reached the remaining characters in string are returned as the final array element. Consecutive instances of delimiter are treated as a single delimiter, there are no empty tokens returned.
Parameters
[in] string string to split on delimiter
[in] delimiter string delimiter
[in] max_tokens maximum number of substrings to generate
Returns
array of substrings, NULL-terminated
Note
free both the array and its elements with lib_free() after use
Referenced by archdep_mkdir_recursive().
util_subst()
char * util_subst (const char * s, const char * string, const char * replacement)
Referenced by archdep_quote_parameter(), archdep_quote_unzip(), and set_system_path().
util_tolower()
char util_tolower (char c)
util_toupper()
char util_toupper (char c)
Referenced by charset_hexstring_to_byte(), p00_check_name(), p00_evaluate_name(), and set_drive_fixed().
util_word_to_be_buf()
void util_word_to_be_buf (uint8_t * buf, uint16_t data)
Referenced by crt_create(), crt_create_v11(), crt_create_v20(), crt_write_chip(), and iffdrv_write_file_header().
util_word_to_le_buf()
void util_word_to_le_buf (uint8_t * buf, uint16_t data)
Referenced by fsimage_create_gcr(), fsimage_create_p64(), fsimage_gcr_write_half_track(), and pcxdrv_write_file_header().