vsid: diskimage/fsimage-probe.c File Reference
fsimage-probe.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "archdep.h"
#include "crt.h"
#include "diskconstants.h"
#include "diskimage.h"
#include "gcr.h"
#include "fsimage-gcr.h"
#include "fsimage-p64.h"
#include "fsimage-probe.h"
#include "fsimage.h"
#include "lib.h"
#include "log.h"
#include "machine-drive.h"
#include "types.h"
#include "util.h"
#include "x64.h"
Macros
#define IS_D67_LEN(x) ((x) == D67_FILE_SIZE)
#define IS_D71_LEN(x) (((x) == D71_FILE_SIZE) || ((x) == D71_FILE_SIZE_E))
#define IS_D81_LEN(x)
#define IS_D80_LEN(x) ((x) == D80_FILE_SIZE)
#define IS_D82_LEN(x) ((x) == D82_FILE_SIZE)
#define IS_D1M_LEN(x) (((x) == D1M_FILE_SIZE) || ((x) == D1M_FILE_SIZE_E))
#define IS_D2M_LEN(x) (((x) == D2M_FILE_SIZE) || ((x) == D2M_FILE_SIZE_E))
#define IS_D4M_LEN(x) (((x) == D4M_FILE_SIZE) || ((x) == D4M_FILE_SIZE_E))
Functions
static void disk_image_check_log (disk_image_t *image, const char *type)
static int disk_image_check_min_block (unsigned int blk, unsigned int length)
static int disk_image_check_for_d64 (disk_image_t *image)
static int disk_image_check_for_d67 (disk_image_t *image)
static int disk_image_check_for_d71 (disk_image_t *image)
static int disk_image_check_for_d81 (disk_image_t *image)
static int disk_image_check_for_d80 (disk_image_t *image)
static int disk_image_check_for_d82 (disk_image_t *image)
static int disk_image_check_for_gcr (disk_image_t *image)
static int disk_image_check_for_p64 (disk_image_t *image)
static int disk_image_check_for_d1m (disk_image_t *image)
static int disk_image_check_for_d2m (disk_image_t *image)
static int disk_image_check_for_d4m (disk_image_t *image)
static int disk_image_check_for_dhd (disk_image_t *image)
static int disk_image_check_for_d90 (disk_image_t *image)
int fsimage_probe (disk_image_t *image)
void fsimage_probe_init (void)
Variables
static log_t disk_image_probe_log = ((log_t)-1)
Macro Definition Documentation
IS_D1M_LEN
#define IS_D1M_LEN (x) (((x) == D1M_FILE_SIZE) || ((x) == D1M_FILE_SIZE_E))
IS_D2M_LEN
#define IS_D2M_LEN (x) (((x) == D2M_FILE_SIZE) || ((x) == D2M_FILE_SIZE_E))
IS_D4M_LEN
#define IS_D4M_LEN (x) (((x) == D4M_FILE_SIZE) || ((x) == D4M_FILE_SIZE_E))
IS_D67_LEN
#define IS_D67_LEN (x) ((x) == D67_FILE_SIZE)
IS_D71_LEN
#define IS_D71_LEN (x) (((x) == D71_FILE_SIZE) || ((x) == D71_FILE_SIZE_E))
IS_D80_LEN
#define IS_D80_LEN (x) ((x) == D80_FILE_SIZE)
IS_D81_LEN
#define IS_D81_LEN (x)
Value:
                       (((x) == D81_FILE_SIZE) || ((x) == D81_FILE_SIZE_E) || \
                       ((x) == D81_FILE_SIZE_81) || ((x) == D81_FILE_SIZE_81E) || \
                       ((x) == D81_FILE_SIZE_82) || ((x) == D81_FILE_SIZE_82E) || \
                       ((x) == D81_FILE_SIZE_83) || ((x) == D81_FILE_SIZE_83E))
IS_D82_LEN
#define IS_D82_LEN (x) ((x) == D82_FILE_SIZE)
Function Documentation
disk_image_check_for_d1m()
static int disk_image_check_for_d1m (disk_image_t * image) static
< D1M image, 81 tracks
< D1M image, 81 tracks with errors
Referenced by fsimage_probe().
disk_image_check_for_d2m()
static int disk_image_check_for_d2m (disk_image_t * image) static
< D2M image, 81 tracks
< D2M image, 81 tracks with errors
Referenced by fsimage_probe().
disk_image_check_for_d4m()
static int disk_image_check_for_d4m (disk_image_t * image) static
< D4M image, 81 tracks
< D4M image, 81 tracks with errors
Referenced by fsimage_probe().
disk_image_check_for_d64()
static int disk_image_check_for_d64 (disk_image_t * image) static
< number of tracks on a standard 1541 floppy
< D64 image, 35 tracks
< maximum number of accessible tracks for a 1541 drive: not all 1541 drives can do this
< maximum number of accessible tracks for a 1541 drive: not all 1541 drives can do this
Referenced by fsimage_probe().
disk_image_check_for_d67()
static int disk_image_check_for_d67 (disk_image_t * image) static
< D67 image, 35 tracks DOS1
< number of tracks on a 2040 floppy
< maximum number of tracks on a 2040 floppy
< number of blocks on a 2040 floppy (670 free
< number of blocks on a 2040 floppy (670 free
< number of blocks on a 2040 floppy (670 free
< number of tracks on a 2040 floppy
< maximum number of tracks on a 2040 floppy
Referenced by fsimage_probe().
disk_image_check_for_d71()
static int disk_image_check_for_d71 (disk_image_t * image) static
< D71 image, 70 tracks
< number of tracks on a 1571 floppy
< maximum number of tracks on a 1571 floppy
< number of blocks on a 1571 floppy (1328 blocks free)
< number of blocks on a 1571 floppy (1328 blocks free)
Referenced by fsimage_probe().
disk_image_check_for_d80()
static int disk_image_check_for_d80 (disk_image_t * image) static
< D80 image, 77 tracks
< 2052 free
< 2052 free
< 2052 free
Referenced by fsimage_probe().
disk_image_check_for_d81()
static int disk_image_check_for_d81 (disk_image_t * image) static
< D81 image, 80 tracks
< D81 image, 80 tracks with errors
< D81 image, 81 tracks (! sams as D1M)
< D81 image, 81 tracks with errors (! sams as D1M)
< D81 image, 82 tracks
< D81 image, 82 tracks with errors
< D81 image, 83 tracks
< D81 image, 83 tracks with errors
< maximum number of blocks on a 1581 diskette when using 83 tracks
< number of blocks on a 1581 diskette (3160 blocks free)
< number of blocks on a 1581 diskette (3160 blocks free)
< number of blocks on a 1581 diskette (3160 blocks free)
< number of tracks on a 1581 diskette
< number of blocks on a 1581 diskette (3160 blocks free)
< number of blocks on a 1581 diskette (3160 blocks free)
< number of tracks on a 1581 diskette
< number of blocks on a 1581 diskette (3160 blocks free)
< number of blocks on a 1581 diskette (3160 blocks free)
< number of tracks on a 1581 diskette
< number of blocks on a 1581 diskette (3160 blocks free)
< number of blocks on a 1581 diskette (3160 blocks free)
< number of tracks on a 1581 diskette
< maximum number of tracks on a 1581 diskette
< number of blocks on a 1581 diskette (3160 blocks free)
< number of blocks on a 1581 diskette (3160 blocks free)
< number of blocks on a 1581 diskette (3160 blocks free)
< number of blocks on a 1581 diskette (3160 blocks free)
Referenced by fsimage_probe().
disk_image_check_for_d82()
static int disk_image_check_for_d82 (disk_image_t * image) static
< D82 image, 77 tracks
< 4133 free
< 4133 free
< 4133 free
Referenced by fsimage_probe().
disk_image_check_for_d90()
static int disk_image_check_for_d90 (disk_image_t * image) static
< D90 image, 153 tracks, 32 sectors, 4 heads
< D90 image, 153 tracks, 32 sectors, 6 heads
< D9090/D9060
Referenced by fsimage_probe().
disk_image_check_for_dhd()
static int disk_image_check_for_dhd (disk_image_t * image) static
< HD in ASCII for CMDHD
Todo:
FIXME: perhaps this can be made more strict to prevent false positives?
Todo:
FIXME: perhaps other headers (g64, t64, p64...) need to be checked here
< HD in ASCII for CMDHD
< HD in ASCII for CMDHD
Referenced by fsimage_probe().
disk_image_check_for_gcr()
static int disk_image_check_for_gcr (disk_image_t * image) static
Referenced by fsimage_probe().
disk_image_check_for_p64()
static int disk_image_check_for_p64 (disk_image_t * image) static
< maximum number of accessible tracks for a 1541 drive: not all 1541 drives can do this
< maximum number of accessible tracks for a 1541 drive: not all 1541 drives can do this
Referenced by fsimage_probe().
disk_image_check_log()
static void disk_image_check_log (disk_image_t * image, const char * type) static
Referenced by disk_image_check_for_d1m(), disk_image_check_for_d2m(), disk_image_check_for_d4m(), disk_image_check_for_d64(), disk_image_check_for_d67(), disk_image_check_for_d71(), disk_image_check_for_d80(), disk_image_check_for_d81(), disk_image_check_for_d82(), disk_image_check_for_d90(), disk_image_check_for_dhd(), disk_image_check_for_gcr(), and disk_image_check_for_p64().
disk_image_check_min_block()
static int disk_image_check_min_block (unsigned int blk, unsigned int length) static
Referenced by disk_image_check_for_d1m(), disk_image_check_for_d2m(), disk_image_check_for_d4m(), disk_image_check_for_d67(), disk_image_check_for_d71(), disk_image_check_for_d80(), disk_image_check_for_d81(), and disk_image_check_for_d82().
fsimage_probe()
int fsimage_probe (disk_image_t * image)
Referenced by fsimage_open().
fsimage_probe_init()
void fsimage_probe_init (void)
Referenced by fsimage_init().
Variable Documentation
disk_image_probe_log
log_t disk_image_probe_log = ((log_t)-1) static
Referenced by disk_image_check_for_d1m(), disk_image_check_for_d2m(), disk_image_check_for_d4m(), disk_image_check_for_d64(), disk_image_check_for_d67(), disk_image_check_for_d80(), disk_image_check_for_d81(), disk_image_check_for_d82(), disk_image_check_for_dhd(), disk_image_check_for_gcr(), disk_image_check_for_p64(), disk_image_check_min_block(), and fsimage_probe_init().