x128: rawfile.c File Reference
rawfile.c File Reference
#include "vice.h"
#include <stddef.h>
#include <stdio.h>
#include <stdint.h>
#include <errno.h>
#include "archdep.h"
#include "fileio.h"
#include "lib.h"
#include "util.h"
#include "rawfile.h"
Data Structures
struct rawfile_info_s
Macros
#define DBG(x)
Typedefs
typedef struct rawfile_info_s rawfile_info_t
Functions
rawfile_info_t * rawfile_open (const char *file_name, const char *path, unsigned int command)
void rawfile_destroy (rawfile_info_t *info)
unsigned int rawfile_read (rawfile_info_t *info, uint8_t *buf, unsigned int len)
unsigned int rawfile_write (rawfile_info_t *info, uint8_t *buf, unsigned int len)
unsigned int rawfile_get_bytes_left (struct rawfile_info_s *info)
unsigned int rawfile_seek (struct rawfile_info_s *info, off_t offset, int whence)
unsigned int rawfile_tell (struct rawfile_info_s *info)
unsigned int rawfile_ferror (rawfile_info_t *info)
unsigned int rawfile_rename (const char *src_name, const char *dst_name, const char *path)
unsigned int rawfile_remove (const char *src_name, const char *path)
Macro Definition Documentation
DBG
#define DBG (x)
Typedef Documentation
rawfile_info_t
typedef struct rawfile_info_s rawfile_info_t
Function Documentation
rawfile_destroy()
void rawfile_destroy (rawfile_info_t * info)
Referenced by cbmfile_close(), p00_close(), p00_file_find(), p00_open(), and p00_rename().
rawfile_ferror()
unsigned int rawfile_ferror (rawfile_info_t * info)
Referenced by cbmfile_ferror(), and p00_ferror().
rawfile_get_bytes_left()
unsigned int rawfile_get_bytes_left (struct rawfile_info_s * info)
Referenced by cbmfile_get_bytes_left(), and p00_get_bytes_left().
rawfile_open()
rawfile_info_t * rawfile_open (const char * file_name, const char * path, unsigned int command)
< directory separator as a string
< works with directories
< read mode (binary)
< read/write mode
< Will not overwrite existing file
< Overwrites existing file, if any
< write mode (binary)
< append mode
< append mode and read/write(?)
< Will not overwrite existing file
< Overwrites existing file, if any
< Will not overwrite existing file
< works with directories
Referenced by cbmfile_open(), p00_file_find(), p00_open(), and p00_rename().
rawfile_read()
unsigned int rawfile_read (rawfile_info_t * info, uint8_t * buf, unsigned int len)
Referenced by cbmfile_read(), p00_read(), and p00_read_header().
rawfile_remove()
unsigned int rawfile_remove (const char * src_name, const char * path)
< directory separator as a string
Referenced by cbmfile_scratch(), and p00_scratch().
rawfile_rename()
unsigned int rawfile_rename (const char * src_name, const char * dst_name, const char * path)
< directory separator as a string
< directory separator as a string
Referenced by cbmfile_rename(), and p00_rename().
rawfile_seek()
unsigned int rawfile_seek (struct rawfile_info_s * info, off_t offset, int whence)
Referenced by cbmfile_seek(), p00_seek(), and p00_write_header().
rawfile_tell()
unsigned int rawfile_tell (struct rawfile_info_s * info)
Referenced by cbmfile_tell(), and p00_tell().
rawfile_write()
unsigned int rawfile_write (rawfile_info_t * info, uint8_t * buf, unsigned int len)
Referenced by cbmfile_write(), p00_write(), and p00_write_header().