vsid: arch/gtk3/uivsidwindow.h File Reference
uivsidwindow.h File Reference
Native GTK3 main vsid window code - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
int ui_vsid_window_load_psid (const char *filename)
Load and play PSID/SID file filename.
void ui_vsid_window_init (void)
Initialize VSID window.
Detailed Description
Native GTK3 main vsid window code - header.
Author
Marcus Sutton logge.nosp@m.doub.nosp@m.t@gma.nosp@m.il.c.nosp@m.om
Function Documentation
ui_vsid_window_init()
void ui_vsid_window_init (void)
Initialize VSID window.
Referenced by vsid_ui_init().
ui_vsid_window_load_psid()
int ui_vsid_window_load_psid (const char * filename)
Load and play PSID/SID file filename.
Parameters
[in] filename file to play
Returns
0 on success, -1 on failure
Note
sets player UI state to either VSID_PLAYING or VSID_ERROR
Referenced by on_drag_data_received(), on_response(), on_row_activated(), ui_vsid_window_init(), vsid_playlist_first(), vsid_playlist_last(), vsid_playlist_next(), and vsid_playlist_previous().