vsid: c64/c64gluelogic.h File Reference
c64gluelogic.h File Reference
#include "types.h"
Macros
#define GLUE_LOGIC_DISCRETE 0
#define GLUE_LOGIC_CUSTOM_IC 1
Functions
void c64_glue_set_vbank (int vbank, int ddr_flag)
void c64_glue_undump (int vbank)
void c64_glue_reset (void)
void c64_glue_init (void)
int c64_glue_resources_init (void)
int c64_glue_cmdline_options_init (void)
int c64_glue_snapshot_write_module (struct snapshot_s *s)
int c64_glue_snapshot_read_module (struct snapshot_s *s)
Macro Definition Documentation
GLUE_LOGIC_CUSTOM_IC
#define GLUE_LOGIC_CUSTOM_IC 1
GLUE_LOGIC_DISCRETE
#define GLUE_LOGIC_DISCRETE 0
Function Documentation
c64_glue_cmdline_options_init()
int c64_glue_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
c64_glue_init()
void c64_glue_init (void)
Referenced by machine_specific_init().
c64_glue_reset()
void c64_glue_reset (void)
Referenced by do_reset_cia().
c64_glue_resources_init()
int c64_glue_resources_init (void)
Referenced by machine_resources_init().
c64_glue_set_vbank()
void c64_glue_set_vbank (int vbank, int ddr_flag)
Referenced by store_ciapa().
c64_glue_snapshot_read_module()
int c64_glue_snapshot_read_module (struct snapshot_s * s)
Referenced by c64_snapshot_read().
c64_glue_snapshot_write_module()
int c64_glue_snapshot_write_module (struct snapshot_s * s)
Referenced by c64_snapshot_write().
c64_glue_undump()
void c64_glue_undump (int vbank)
Referenced by undump_ciapa().