x128: romset.h File Reference
romset.h File Reference
Functions
void romset_init (void)
int romset_resources_init (void)
void romset_resources_shutdown (void)
int romset_cmdline_options_init (void)
int romset_file_load (const char *filename)
int romset_file_save (const char *filename, const char *const *resource_list)
char * romset_file_list (const char *const *resource_list)
int romset_archive_load (const char *filename, int autostart)
int romset_archive_save (const char *filename)
char * romset_archive_list (void)
int romset_archive_item_save (const char *filename, const char *romset_name)
int romset_archive_item_select (const char *romset_name)
int romset_archive_item_create (const char *romset_name, const char *const *resource_list)
int romset_archive_item_delete (const char *romset_name)
void romset_archive_clear (void)
int romset_archive_get_number (void)
char * romset_archive_get_item (int number)
Function Documentation
romset_archive_clear()
void romset_archive_clear (void)
romset_archive_get_item()
char * romset_archive_get_item (int number)
romset_archive_get_number()
int romset_archive_get_number (void)
romset_archive_item_create()
int romset_archive_item_create (const char * romset_name, const char *const * resource_list)
Referenced by machine_romset_archive_item_create().
romset_archive_item_delete()
int romset_archive_item_delete (const char * romset_name)
romset_archive_item_save()
int romset_archive_item_save (const char * filename, const char * romset_name)
< write mode (text)
romset_archive_item_select()
int romset_archive_item_select (const char * romset_name)
Todo:
FIXME: Apparently there are no boundary checks!
Referenced by option_romsetarchiveselect(), and romset_archive_load().
romset_archive_list()
char * romset_archive_list (void)
Referenced by romset_archive_save().
romset_archive_load()
int romset_archive_load (const char * filename, int autostart)
< read mode (text)
Referenced by option_romsetarchive().
romset_archive_save()
int romset_archive_save (const char * filename)
< write mode (binary)
romset_cmdline_options_init()
int romset_cmdline_options_init (void)
Referenced by init_cmdline_options().
romset_file_list()
char * romset_file_list (const char *const * resource_list)
Referenced by machine_romset_file_list().
romset_file_load()
int romset_file_load (const char * filename)
< read mode (text)
Referenced by machine_romset_file_load(), on_load_romset_callback(), and option_romsetfile().
romset_file_save()
int romset_file_save (const char * filename, const char *const * resource_list)
< write mode (text)
Referenced by machine_romset_file_save(), and on_romset_save_callback().
romset_init()
void romset_init (void)
Referenced by init_main().
romset_resources_init()
int romset_resources_init (void)
Referenced by init_resources().
romset_resources_shutdown()
void romset_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().