x128: zfile.c File Reference
zfile.c File Reference
Transparent handling of compressed files.
#include "vice.h"
#include <ctype.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <errno.h>
#include <strings.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "util.h"
#include "zipcode.h"
#include "zfile.h"
Data Structures
struct zfile_s
struct valid_archives_s
Macros
#define ZDEBUG(a)
This code might be improved a lot...
#define C1541_NAME "c1541"
Typedefs
typedef struct zfile_s zfile_t
typedef struct valid_archives_s valid_archives_t
Enumerations
enum compression_type {
COMPR_NONE ,
COMPR_GZIP ,
COMPR_BZIP ,
COMPR_ARCHIVE ,
COMPR_ZIPCODE ,
COMPR_LYNX ,
COMPR_TZX
}
We could add more here...
Functions
static int file_is_gzip (const char *name)
@brief 'Check' is file name is a gzip or compress file
static void zfile_list_destroy (void)
static int zinit (void)
static void zfile_list_add (const char *tmp_name, const char *orig_name, enum compression_type type, int write_mode, FILE *stream, FILE *fd)
void zfile_shutdown (void)
static char * try_uncompress_with_gzip (const char *name)
Uncompression.
static char * try_uncompress_with_bzip (const char *name)
static char * try_uncompress_with_tzx (const char *name)
static int is_zipcode_name (char *name)
is the name zipcode -name?
static int is_valid_extension (char *end, size_t l, int nameoffset)
static char * try_uncompress_archive (const char *name, int write_mode, const char *program, const char *listopts, const char *extractopts, const char *extension, const char *search)
static char * try_uncompress_zipcode (const char *name, int write_mode)
static char * try_uncompress_lynx (const char *name, int write_mode)
static enum compression_type try_uncompress (const char *name, char **tmp_name, int write_mode)
static int compress_with_gzip (const char *src, const char *dest)
Compression.
static int compress_with_bzip (const char *src, const char *dest)
Compress ‘src’ into ‘dest’ using bzip.
static int zfile_compress (const char *src, const char *dest, enum compression_type type)
Compress ‘src’ into ‘dest’ using algorithm ‘type’.
FILE * zfile_fopen (const char *name, const char *mode)
‘fopen()’ wrapper.
static int handle_close_action (zfile_t *ptr)
Handle close-action of a file.
static int handle_close (zfile_t *ptr)
Handle close of a (compressed file).
int zfile_fclose (FILE *stream)
‘fclose()’ wrapper.
int zfile_close_action (const char *filename, zfile_action_t action, const char *request_str)
Variables
static zfile_t * zfile_list = NULL
static log_t zlog = ((log_t)-1)
static int zinit_done = 0
static const char *const extensions []
Extensions we know about.
static const valid_archives_t valid_archives []
Detailed Description
Transparent handling of compressed files.
Author
Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
ARCHIVE, ZIPCODE and LYNX supports added by Teemu Rantanen tvr@c.nosp@m.s.hu.nosp@m.t.fi
Macro Definition Documentation
C1541_NAME
#define C1541_NAME "c1541"
ZDEBUG
#define ZDEBUG (a)
This code might be improved a lot...
Typedef Documentation
valid_archives_t
typedef struct valid_archives_s valid_archives_t
zfile_t
typedef struct zfile_s zfile_t
Enumeration Type Documentation
compression_type
enum compression_type
We could add more here...
Enumerator
COMPR_NONE
COMPR_GZIP
COMPR_BZIP
COMPR_ARCHIVE
COMPR_ZIPCODE
COMPR_LYNX
COMPR_TZX
Function Documentation
compress_with_bzip()
static int compress_with_bzip (const char * src, const char * dest) static
Compress ‘src’ into ‘dest’ using bzip.
Referenced by zfile_compress().
compress_with_gzip()
static int compress_with_gzip (const char * src, const char * dest) static
Compression.
Compress ‘src’ into ‘dest’ using gzip.
Referenced by zfile_compress().
file_is_gzip()
static int file_is_gzip (const char * name) static
@brief 'Check' is file name is a gzip or compress file
Parameters
[in] name filename or path
Returns
bool
Todo:
FIXME: this is a silly function and should be reimplemented using the 2-byte header of the file
Referenced by try_uncompress_with_gzip().
handle_close()
static int handle_close (zfile_t * ptr) static
Handle close of a (compressed file).
‘ptr’ points to the zfile to close.
Referenced by zfile_fclose().
handle_close_action()
static int handle_close_action (zfile_t * ptr) static
Handle close-action of a file.
‘ptr’ points to the zfile to close.
Referenced by handle_close().
is_valid_extension()
static int is_valid_extension (char * end, size_t l, int nameoffset) static
Referenced by try_uncompress_archive().
is_zipcode_name()
static int is_zipcode_name (char * name) static
is the name zipcode -name?
Referenced by is_valid_extension(), and try_uncompress_archive().
try_uncompress()
static enum compression_type try_uncompress (const char * name, char ** tmp_name, int write_mode) static
Referenced by zfile_fopen().
try_uncompress_archive()
static char * try_uncompress_archive (const char * name, int write_mode, const char * program, const char * listopts, const char * extractopts, const char * extension, const char * search) static
< read mode (binary)
Referenced by try_uncompress().
try_uncompress_lynx()
static char * try_uncompress_lynx (const char * name, int write_mode) static
< read mode (binary)
Referenced by try_uncompress().
try_uncompress_with_bzip()
static char * try_uncompress_with_bzip (const char * name) static
Referenced by try_uncompress().
try_uncompress_with_gzip()
static char * try_uncompress_with_gzip (const char * name) static
Uncompression.
Referenced by try_uncompress().
try_uncompress_with_tzx()
static char * try_uncompress_with_tzx (const char * name) static
Referenced by try_uncompress().
try_uncompress_zipcode()
static char * try_uncompress_zipcode (const char * name, int write_mode) static
< read mode (binary)
Referenced by try_uncompress().
zfile_close_action()
int zfile_close_action (const char * filename, zfile_action_t action, const char * request_str)
Referenced by drive_snapshot_read_image_module().
zfile_compress()
static int zfile_compress (const char * src, const char * dest, enum compression_type type) static
Compress ‘src’ into ‘dest’ using algorithm ‘type’.
Referenced by handle_close().
zfile_fclose()
int zfile_fclose (FILE * stream)
‘fclose()’ wrapper.
Referenced by fsimage_close(), snapshot_close(), t64_close(), t64_destroy(), tap_close(), and tap_open().
zfile_fopen()
FILE * zfile_fopen (const char * name, const char * mode)
‘fopen()’ wrapper.
Referenced by fsimage_open(), snapshot_open(), t64_open(), and tap_open().
zfile_list_add()
static void zfile_list_add (const char * tmp_name, const char * orig_name, enum compression_type type, int write_mode, FILE * stream, FILE * fd) static
Referenced by zfile_fopen().
zfile_list_destroy()
static void zfile_list_destroy (void) static
Referenced by zfile_shutdown(), and zinit().
zfile_shutdown()
void zfile_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
zinit()
static int zinit (void) static
Referenced by zfile_fopen().
Variable Documentation
extensions
const char* const extensions[] static
Initial value:
= {
    ".d64",
    ".d67",
    ".d71",
    ".d80",
    ".d81",
    ".d82",
    ".d1m",
    ".d2m",
    ".d4m",
    ".g64",
    ".p64",
    ".g41",
    ".x64",
    ".dsk",
    ".t64",
    ".p00",
    ".prg",
    ".lnx",
    ".tap",
    NULL
}
Extensions we know about.
Referenced by is_valid_extension().
valid_archives
const valid_archives_t valid_archives[] static
Initial value:
= {
    { "unzip",   "-l",   "-p",    ".zip",    "Name" },
    { "lha",     "lv",   "pq",    ".lzh",    NULL },
    { "lha",     "lv",   "pq",    ".lha",    NULL },
    { "gtar",    "-tf",  "-xOf",  ".tar",    NULL },
    { "tar",     "-tf",  "-xOf",  ".tar",    NULL },
    { "gtar",    "-ztf", "-zxOf", ".tar.gz", NULL },
    { "tar",     "-ztf", "-zxOf", ".tar.gz", NULL },
    { "gtar",    "-ztf", "-zxOf", ".tgz",    NULL },
    { "tar",     "-ztf", "-zxOf", ".tgz",    NULL },
    { "zoo",     "lf1q", "xpq",   ".zoo",    NULL },
    { NULL, NULL, NULL, NULL, NULL }
}
Referenced by try_uncompress().
zfile_list
zfile_t* zfile_list = NULL static
Referenced by handle_close(), zfile_close_action(), zfile_fclose(), zfile_list_add(), and zfile_list_destroy().
zinit_done
int zinit_done = 0 static
Referenced by zfile_fclose(), zfile_fopen(), and zinit().
zlog
log_t zlog = ((log_t)-1) static
Referenced by handle_close(), handle_close_action(), zfile_compress(), and zinit().