vsid: drive/drive.c File Reference
drive.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include "attach.h"
#include "archdep.h"
#include "diskconstants.h"
#include "diskimage.h"
#include "drive-check.h"
#include "drive.h"
#include "drivecpu.h"
#include "drivecpu65c02.h"
#include "driveimage.h"
#include "drivesync.h"
#include "driverom.h"
#include "drivetypes.h"
#include "gcr.h"
#include "iecbus.h"
#include "iecdrive.h"
#include "lib.h"
#include "log.h"
#include "machine-drive.h"
#include "machine.h"
#include "maincpu.h"
#include "resources.h"
#include "rotation.h"
#include "sound.h"
#include "types.h"
#include "uiapi.h"
#include "ds1216e.h"
#include "drive-sound.h"
#include "p64.h"
#include "monitor.h"
#include "monitor_network.h"
#include "monitor_binary.h"
#include "vsync.h"
Macros
#define DBG(x)
Functions
void drive_set_disk_memory (uint8_t *id, unsigned int track, unsigned int sector, struct diskunit_context_s *unit)
void drive_set_last_read (unsigned int track, unsigned int sector, uint8_t *buffer, struct diskunit_context_s *unit)
int drive_init (void)
void drive_shutdown (void)
void drive_set_active_led_color (unsigned int type, unsigned int dnr)
int drive_set_disk_drive_type (unsigned int type, struct diskunit_context_s *drv)
int drive_get_disk_drive_type (int dnr)
void drive_enable_update_ui (diskunit_context_t *drv)
int drive_enable (diskunit_context_t *drv)
Activate full drive emulation.
void drive_disable (diskunit_context_t *drv)
Disable full drive emulation.
monitor_interface_t * drive_cpu_monitor_interface_get (unsigned int dnr)
Don't use these pointers before the context is set up!
void drive_cpu_early_init_all (void)
void drive_cpu_trigger_reset (unsigned int dnr)
reset one drive only
void drive_reset (void)
called by machine_specific_reset()
unsigned int drive_jam (int mynumber, const char *format,...)
bool drive_is_jammed (int mynumber)
char * drive_jam_reason (int mynumber)
void drive_set_half_track (int num, int side, drive_t *dptr)
Move the head to half track ‘num’.
void drive_move_head (int step, drive_t *drive)
void drive_gcr_data_writeback (drive_t *drive)
void drive_gcr_data_writeback_all (void)
static void drive_led_update (diskunit_context_t *unit, drive_t *drive, int base)
void drive_update_ui_status (void)
Update the status bar in the UI.
int drive_num_leds (unsigned int dnr)
void drive_cpu_execute_one (diskunit_context_t *drv, CLOCK clk_value)
void drive_cpu_execute_all (CLOCK clk_value)
void drive_cpu_set_overflow (diskunit_context_t *drv)
void drive_vsync_hook (void)
This is called at every vsync.
static void drive_setup_context_for_unit (diskunit_context_t *drv, unsigned int unr)
void drive_setup_context (void)
int drive_has_buttons (unsigned int dnr)
void drive_cpu_trigger_reset_button (unsigned int dnr, unsigned int button)
Variables
static int drive_init_was_called = 0
diskunit_context_t * diskunit_context [4]
static log_t drive_log = ((log_t)-1)
Generic drive logging goes here.
int rom_loaded = 0
If nonzero, at least one vaild drive ROM has already been loaded.
static int drive_led_color [4]
static bool is_jammed [4] = { false, false, false, false }
static char * jam_reason [4] = { NULL, NULL, NULL, NULL }
static int jam_action = 0
Macro Definition Documentation
DBG
#define DBG (x)
Todo:
more accurate emulation of disk rotation.
different speeds within one track.
check for byte ready within ‘BVC’, ‘BVS’ and ‘PHP’.
serial bus handling might be faster.
Function Documentation
drive_cpu_early_init_all()
void drive_cpu_early_init_all (void)
Referenced by init_main().
drive_cpu_execute_all()
void drive_cpu_execute_all (CLOCK clk_value)
Referenced by c64_snapshot_write(), iecbus_cpu_read_conf1(), iecbus_cpu_read_conf2(), iecbus_cpu_read_conf3(), iecbus_cpu_write_conf3(), monitor_binary_process_command(), read_ciaicr(), and read_sdr().
drive_cpu_execute_one()
void drive_cpu_execute_one (diskunit_context_t * drv, CLOCK clk_value)
< ASCII for HD
Referenced by c64fastiec_fast_cpu_write(), drive_cpu_execute_all(), drive_vsync_hook(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), and parallel_cable_cpu_execute().
drive_cpu_monitor_interface_get()
monitor_interface_t * drive_cpu_monitor_interface_get (unsigned int dnr)
Don't use these pointers before the context is set up!
Referenced by c64_monitor_init().
drive_cpu_set_overflow()
void drive_cpu_set_overflow (diskunit_context_t * drv)
< ASCII for HD
drive_cpu_trigger_reset()
void drive_cpu_trigger_reset (unsigned int dnr)
reset one drive only
< ASCII for HD
Referenced by autostart_disk(), autostart_prg(), cmdhd_attach_image(), drive_cpu_trigger_reset_button(), drive_reset(), driverom_load(), mon_reset_machine(), and reset_drive_action().
drive_cpu_trigger_reset_button()
void drive_cpu_trigger_reset_button (unsigned int dnr, unsigned int button)
Referenced by on_drive_reset_config_clicked().
drive_disable()
void drive_disable (diskunit_context_t * drv)
Disable full drive emulation.
< ASCII for HD
Referenced by drive_resources_type(), drive_snapshot_read_module(), driverom_load(), and set_drive_true_emulation().
drive_enable()
int drive_enable (diskunit_context_t * drv)
Activate full drive emulation.
< ASCII for HD
Referenced by drive_init(), drive_resources_type(), drive_snapshot_read_module(), and set_drive_true_emulation().
drive_enable_update_ui()
void drive_enable_update_ui (diskunit_context_t * drv)
Todo:
drive 1
Referenced by drive_disable(), drive_enable(), and drive_resources_type().
drive_gcr_data_writeback()
void drive_gcr_data_writeback (drive_t * drive)
Todo:
FIXME: why would the offset be different for D71 and G71?
Todo:
FIXME: doublesided images cant be extended with this logic, so never do it
Referenced by drive_disable(), drive_gcr_data_writeback_all(), drive_image_detach(), drive_move_head(), drive_set_last_read(), and glue1571_side_set().
drive_gcr_data_writeback_all()
void drive_gcr_data_writeback_all (void)
Referenced by drive_snapshot_read_module(), drive_snapshot_write_module(), and machine_drive_flush().
drive_get_disk_drive_type()
int drive_get_disk_drive_type (int dnr)
drive_has_buttons()
int drive_has_buttons (unsigned int dnr)
< ASCII for HD
Referenced by ui_do_drive_popup().
drive_init()
int drive_init (void)
Todo:
rotation code is not drive1 aware
< ASCII for HD
Referenced by machine_specific_init().
drive_is_jammed()
bool drive_is_jammed (int mynumber)
Referenced by statusbar_speed_widget_update().
drive_jam()
unsigned int drive_jam (int mynumber, const char * format, ...)
Todo:
FIXME: perhaps we want a seperate setting for drives?
Referenced by drivecpu_jam().
drive_jam_reason()
char * drive_jam_reason (int mynumber)
Referenced by statusbar_speed_widget_update().
drive_led_update()
static void drive_led_update (diskunit_context_t * unit, drive_t * drive, int base) static
Referenced by drive_update_ui_status().
drive_move_head()
void drive_move_head (int step, drive_t * drive)
drive_num_leds()
int drive_num_leds (unsigned int dnr)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
< ASCII for HD
drive_reset()
void drive_reset (void)
called by machine_specific_reset()
reset all drives
Referenced by machine_specific_reset().
drive_set_active_led_color()
void drive_set_active_led_color (unsigned int type, unsigned int dnr)
< ASCII for HD
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 3.0 hard drive
< DOS 2.7 dual floppy drive, 1M/disk
Referenced by drive_init(), drive_set_disk_drive_type(), and drive_snapshot_read_module().
drive_set_disk_drive_type()
int drive_set_disk_drive_type (unsigned int type, struct diskunit_context_s * drv)
Todo:
drive 1?
< ASCII for HD
< ASCII for HD
Referenced by drive_resources_type().
drive_set_disk_memory()
void drive_set_disk_memory (uint8_t * id, unsigned int track, unsigned int sector, struct diskunit_context_s * unit)
Referenced by disk_eof_callback().
drive_set_half_track()
void drive_set_half_track (int num, int side, drive_t * dptr)
Move the head to half track ‘num’.
Todo:
FIXME: why would the offset be different for D71 and G71?
Referenced by drive_image_attach(), drive_image_detach(), drive_init(), drive_move_head(), drive_set_last_read(), drive_snapshot_read_module(), and glue1571_side_set().
drive_set_last_read()
void drive_set_last_read (unsigned int track, unsigned int sector, uint8_t * buffer, struct diskunit_context_s * unit)
Todo:
drive 1 ?
Todo:
drive 1 ?
Referenced by disk_eof_callback().
drive_setup_context()
void drive_setup_context (void)
Referenced by main_program().
drive_setup_context_for_unit()
static void drive_setup_context_for_unit (diskunit_context_t * drv, unsigned int unr) static
Todo:
init functions for allocated memory
Referenced by drive_setup_context().
drive_shutdown()
void drive_shutdown (void)
< ASCII for HD
Referenced by cmdline_help(), and machine_shutdown().
drive_update_ui_status()
void drive_update_ui_status (void)
Update the status bar in the UI.
Referenced by drive_snapshot_read_module(), and drive_vsync_hook().
drive_vsync_hook()
void drive_vsync_hook (void)
This is called at every vsync.
Todo:
drive 1
Referenced by machine_vsync_hook().
Variable Documentation
diskunit_context
diskunit_context_t* diskunit_context[4]
Referenced by c64fastiec_fast_cpu_write(), cmdbus_update(), cmdhd_attach_image(), cmdhd_detach_image(), cmdhd_init(), cmdhd_patn_changed(), cmdhd_update_maxsize(), disk_eof_callback(), drive_check_image_format(), drive_cpu_early_init_all(), drive_cpu_execute_all(), drive_cpu_monitor_interface_get(), drive_cpu_trigger_reset(), drive_cpu_trigger_reset_button(), drive_enable_update_ui(), drive_gcr_data_writeback_all(), drive_get_disk_drive_type(), drive_has_buttons(), drive_image_attach(), drive_image_detach(), drive_init(), drive_num_leds(), drive_resources_init(), drive_resources_type(), drive_resources_type_init(), drive_set_machine_parameter(), drive_setup_context(), drive_shutdown(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), drive_snapshot_write_gcrimage_module(), drive_snapshot_write_image_module(), drive_snapshot_write_module(), drive_snapshot_write_p64image_module(), drive_update_ui_status(), drive_vsync_hook(), driverom_load(), iec_drive_rom_do_checksum(), iec_drive_rom_setup_image(), iec_resources_init(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), iecbus_cpu_write_conf3(), layout_statusbar_drives(), parallel_atn_signal(), parallel_cable_cpu_execute(), parallel_cable_cpu_pulse(), parallel_cable_value(), parallel_trap_attention(), parallel_trap_receivebyte(), parallel_trap_sendbyte(), parallelcommand(), pc8477_attach_image(), pc8477_detach_image(), rotation_table_get(), rotation_table_set(), set_drive_extend_image_policy(), set_drive_fixed(), set_drive_idling_method(), set_drive_ram(), set_drive_ram2(), set_drive_ram4(), set_drive_ram6(), set_drive_ram8(), set_drive_rama(), set_drive_rpm(), set_drive_rtc_save(), set_drive_true_emulation(), set_drive_wobble_amplitude(), set_drive_wobble_frequency(), wd1770_attach_image(), and wd1770_detach_image().
drive_init_was_called
int drive_init_was_called = 0 static
Referenced by drive_init(), and drive_shutdown().
drive_led_color
int drive_led_color[4] static
Referenced by drive_enable_update_ui(), drive_set_active_led_color(), and ui_enable_drive_status().
drive_log
log_t drive_log = ((log_t)-1) static
Generic drive logging goes here.
Referenced by drive_init(), and drive_move_head().
is_jammed
bool is_jammed[4] = { false, false, false, false } static
Referenced by drive_cpu_trigger_reset(), drive_is_jammed(), and drive_jam().
jam_action
int jam_action = 0 static
Referenced by drive_jam().
jam_reason
char* jam_reason[4] = { NULL, NULL, NULL, NULL } static
Referenced by drive_jam(), and drive_jam_reason().
rom_loaded
int rom_loaded = 0
If nonzero, at least one vaild drive ROM has already been loaded.
Referenced by drive_disable(), drive_enable(), drive_init(), drivesync_set_1571(), drivesync_set_4000(), iecrom_check_loaded(), iecrom_setup_image(), and set_drive_idling_method().