vsid: drive/drivecpu.c File Reference
drivecpu.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "6510core.h"
#include "alarm.h"
#include "debug.h"
#include "drive.h"
#include "drivecpu.h"
#include "drive-check.h"
#include "drivemem.h"
#include "drivetypes.h"
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "machine-drive.h"
#include "machine.h"
#include "mainlock.h"
#include "mem.h"
#include "monitor.h"
#include "mos6510.h"
#include "rotation.h"
#include "snapshot.h"
#include "types.h"
#include "uiapi.h"
#include "6510core.c"
Macros
#define DRIVE_CPU
#define LOAD(a) (*drv->cpud->read_func_ptr[(a) >> 8])(drv, (uint16_t)(a))
#define LOAD_ZERO(a) (*drv->cpud->read_func_ptr[0])(drv, (uint16_t)(a))
#define LOAD_ADDR(a) (LOAD((a)) | (LOAD((a) + 1) << 8))
#define LOAD_ZERO_ADDR(a) (LOAD_ZERO((a)) | (LOAD_ZERO((a) + 1) << 8))
#define STORE(a, b) (*drv->cpud->store_func_ptr[(a) >> 8])(drv, (uint16_t)(a), (uint8_t)(b))
#define STORE_ZERO(a, b) (*drv->cpud->store_func_ptr[0])(drv, (uint16_t)(a), (uint8_t)(b))
#define LOAD_DUMMY(a) (*drv->cpud->read_func_ptr_dummy[(a) >> 8])(drv, (uint16_t)(a))
#define LOAD_ZERO_DUMMY(a) (*drv->cpud->read_func_ptr_dummy[0])(drv, (uint16_t)(a))
#define LOAD_ADDR_DUMMY(a) (LOAD_DUMMY((a)) | (LOAD_DUMMY((a) + 1) << 8))
#define LOAD_ZERO_ADDR_DUMMY(a) (LOAD_ZERO_DUMMY((a)) | (LOAD_ZERO_DUMMY((a) + 1) << 8))
#define STORE_DUMMY(a, b) (*drv->cpud->store_func_ptr_dummy[(a) >> 8])(drv, (uint16_t)(a), (uint8_t)(b))
#define STORE_ZERO_DUMMY(a, b) (*drv->cpud->store_func_ptr_dummy[0])(drv, (uint16_t)(a), (uint8_t)(b))
#define JUMP(addr)
#define reg_a (cpu->cpu_regs.a)
#define reg_x (cpu->cpu_regs.x)
#define reg_y (cpu->cpu_regs.y)
#define reg_pc (cpu->cpu_regs.pc)
#define reg_sp (cpu->cpu_regs.sp)
#define reg_p (cpu->cpu_regs.p)
#define flag_z (cpu->cpu_regs.z)
#define flag_n (cpu->cpu_regs.n)
#define ORIGIN_MEMSPACE (drv->mynumber + e_disk8_space)
#define CLK (*(drv->clk_ptr))
#define RMW_FLAG (cpu->rmw_flag)
#define PAGE_ONE (cpu->pageone)
#define LAST_OPCODE_INFO (cpu->last_opcode_info)
#define LAST_OPCODE_ADDR (cpu->last_opcode_addr)
#define TRACEFLG (debug.drivecpu_traceflg[drv->mynumber])
#define CPU_INT_STATUS (cpu->int_status)
#define ALARM_CONTEXT (cpu->alarm_context)
#define JAM() drivecpu_jam(drv)
#define ROM_TRAP_ALLOWED() 1
#define ROM_TRAP_HANDLER() drive_trap_handler(drv)
#define CALLER (cpu->monspace)
#define DMA_FUNC drive_generic_dma()
#define DMA_ON_RESET
#define drivecpu_byte_ready_egde_clear()
#define drivecpu_rotate()
#define drivecpu_byte_ready() (drv->drives[0]->byte_ready_edge)
#define cpu_reset() (cpu_reset)(drv)
#define bank_limit (cpu->d_bank_limit)
#define bank_start (cpu->d_bank_start)
#define bank_base (cpu->d_bank_base)
#define SNAP_MAJOR 1
#define SNAP_MINOR 3
Functions
static void drivecpu_jam (diskunit_context_t *drv)
Inlining this fuction makes no sense and would only bloat the code.
static void drivecpu_set_bank_base (void *context)
void drivecpu_setup_context (struct diskunit_context_s *drv, int i)
static void cpu_reset (diskunit_context_t *drv)
void drivecpu_reset_clk (diskunit_context_t *drv)
void drivecpu_reset (diskunit_context_t *drv)
called by drive_reset() (via machine_specific_reset())
void drivecpu_trigger_reset (unsigned int dnr)
called by drive_cpu_trigger_reset()
void drivecpu_set_overflow (diskunit_context_t *drv)
void drivecpu_shutdown (diskunit_context_t *drv)
void drivecpu_init (diskunit_context_t *drv, int type)
void drivecpu_wake_up (diskunit_context_t *drv)
void drivecpu_sleep (diskunit_context_t *drv)
static uint32_t drive_trap_handler (diskunit_context_t *drv)
Handle a ROM trap.
static void drive_generic_dma (void)
static int interrupt_check_nmi_delay (interrupt_cpu_status_t *cs, CLOCK cpu_clk)
static int interrupt_check_irq_delay (interrupt_cpu_status_t *cs, CLOCK cpu_clk)
void drivecpu_execute (diskunit_context_t *drv, CLOCK clk_value)
int drivecpu_snapshot_write_module (diskunit_context_t *drv, snapshot_t *s)
int drivecpu_snapshot_read_module (diskunit_context_t *drv, snapshot_t *s)
Variables
CLOCK diskunit_clk [4]
Global clock counters.
static interrupt_cpu_status_t * drivecpu_int_status_ptr [4]
Macro Definition Documentation
ALARM_CONTEXT
#define ALARM_CONTEXT (cpu->alarm_context)
bank_base
#define bank_base (cpu->d_bank_base)
bank_limit
#define bank_limit (cpu->d_bank_limit)
bank_start
#define bank_start (cpu->d_bank_start)
CALLER
#define CALLER (cpu->monspace)
CLK
#define CLK (*(drv->clk_ptr))
CPU_INT_STATUS
#define CPU_INT_STATUS (cpu->int_status)
cpu_reset
#define cpu_reset (void) (cpu_reset)(drv)
DMA_FUNC
#define DMA_FUNC drive_generic_dma()
DMA_ON_RESET
#define DMA_ON_RESET
DRIVE_CPU
#define DRIVE_CPU
drivecpu_byte_ready
#define drivecpu_byte_ready () (drv->drives[0]->byte_ready_edge)
drivecpu_byte_ready_egde_clear
#define drivecpu_byte_ready_egde_clear ()
Value:
    do {                                  \
        drv->drives[0]->byte_ready_edge = 0;  \
    } while (0)
drivecpu_rotate
#define drivecpu_rotate ()
Value:
    do {                                  \
        rotation_rotate_disk(drv->drives[0]); \
    } while (0)
flag_n
#define flag_n (cpu->cpu_regs.n)
flag_z
#define flag_z (cpu->cpu_regs.z)
JAM
#define JAM () drivecpu_jam(drv)
JUMP
#define JUMP (addr)
Value:
    do {                                                                   \
        reg_pc = (unsigned int)(addr);                                     \
        if (reg_pc >= cpu->d_bank_limit || reg_pc < cpu->d_bank_start) {   \
            uint8_t *p = drv->cpud->read_base_tab_ptr[reg_pc >> 8];           \
            cpu->d_bank_base = p;                                          \
                                                                           \
            if (p != NULL) {                                               \
                uint32_t limits = drv->cpud->read_limit_tab_ptr[reg_pc >> 8]; \
                cpu->d_bank_limit = limits & 0xffff;                       \
                cpu->d_bank_start = limits >> 16;                          \
            } else {                                                       \
                cpu->d_bank_start = 0;                                     \
                cpu->d_bank_limit = 0;                                     \
            }                                                              \
        }                                                                  \
    } while (0)
LAST_OPCODE_ADDR
#define LAST_OPCODE_ADDR (cpu->last_opcode_addr)
LAST_OPCODE_INFO
#define LAST_OPCODE_INFO (cpu->last_opcode_info)
LOAD
#define LOAD (a) (*drv->cpud->read_func_ptr[(a) >> 8])(drv, (uint16_t)(a))
LOAD_ADDR
#define LOAD_ADDR (a) (LOAD((a)) | (LOAD((a) + 1) << 8))
LOAD_ADDR_DUMMY
#define LOAD_ADDR_DUMMY (a) (LOAD_DUMMY((a)) | (LOAD_DUMMY((a) + 1) << 8))
LOAD_DUMMY
#define LOAD_DUMMY (a) (*drv->cpud->read_func_ptr_dummy[(a) >> 8])(drv, (uint16_t)(a))
LOAD_ZERO
#define LOAD_ZERO (a) (*drv->cpud->read_func_ptr[0])(drv, (uint16_t)(a))
LOAD_ZERO_ADDR
#define LOAD_ZERO_ADDR (a) (LOAD_ZERO((a)) | (LOAD_ZERO((a) + 1) << 8))
LOAD_ZERO_ADDR_DUMMY
#define LOAD_ZERO_ADDR_DUMMY (a) (LOAD_ZERO_DUMMY((a)) | (LOAD_ZERO_DUMMY((a) + 1) << 8))
LOAD_ZERO_DUMMY
#define LOAD_ZERO_DUMMY (a) (*drv->cpud->read_func_ptr_dummy[0])(drv, (uint16_t)(a))
ORIGIN_MEMSPACE
#define ORIGIN_MEMSPACE (drv->mynumber + e_disk8_space)
PAGE_ONE
#define PAGE_ONE (cpu->pageone)
reg_a
#define reg_a (cpu->cpu_regs.a)
reg_p
#define reg_p (cpu->cpu_regs.p)
reg_pc
#define reg_pc (cpu->cpu_regs.pc)
reg_sp
#define reg_sp (cpu->cpu_regs.sp)
reg_x
#define reg_x (cpu->cpu_regs.x)
reg_y
#define reg_y (cpu->cpu_regs.y)
RMW_FLAG
#define RMW_FLAG (cpu->rmw_flag)
ROM_TRAP_ALLOWED
#define ROM_TRAP_ALLOWED () 1
ROM_TRAP_HANDLER
#define ROM_TRAP_HANDLER () drive_trap_handler(drv)
SNAP_MAJOR
#define SNAP_MAJOR 1
SNAP_MINOR
#define SNAP_MINOR 3
STORE
#define STORE (a, b) (*drv->cpud->store_func_ptr[(a) >> 8])(drv, (uint16_t)(a), (uint8_t)(b))
STORE_DUMMY
#define STORE_DUMMY (a, b) (*drv->cpud->store_func_ptr_dummy[(a) >> 8])(drv, (uint16_t)(a), (uint8_t)(b))
STORE_ZERO
#define STORE_ZERO (a, b) (*drv->cpud->store_func_ptr[0])(drv, (uint16_t)(a), (uint8_t)(b))
STORE_ZERO_DUMMY
#define STORE_ZERO_DUMMY (a, b) (*drv->cpud->store_func_ptr_dummy[0])(drv, (uint16_t)(a), (uint8_t)(b))
TRACEFLG
#define TRACEFLG (debug.drivecpu_traceflg[drv->mynumber])
Function Documentation
cpu_reset()
static void cpu_reset (diskunit_context_t * drv) static
drive_generic_dma()
static void drive_generic_dma (void) static
drive_trap_handler()
static uint32_t drive_trap_handler (diskunit_context_t * drv) inline static
Handle a ROM trap.
drivecpu_execute()
void drivecpu_execute (diskunit_context_t * drv, CLOCK clk_value)
Include the 6502/6510 CPU emulation core.
Referenced by drive_cpu_execute_one().
drivecpu_init()
void drivecpu_init (diskunit_context_t * drv, int type)
Todo:
check type is already set, and remove type from parameters
Referenced by drive_init(), and drive_set_disk_drive_type().
drivecpu_jam()
static void drivecpu_jam (diskunit_context_t * drv) static
Inlining this fuction makes no sense and would only bloat the code.
< DOS 2.7 single floppy drive, 1M/disk
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
drivecpu_reset()
void drivecpu_reset (diskunit_context_t * drv)
called by drive_reset() (via machine_specific_reset())
Referenced by drive_cpu_trigger_reset(), drivecpu_init(), and drivecpu_snapshot_read_module().
drivecpu_reset_clk()
void drivecpu_reset_clk (diskunit_context_t * drv)
Referenced by drivecpu_reset(), and set_drive_true_emulation().
drivecpu_set_bank_base()
static void drivecpu_set_bank_base (void * context) static
Referenced by drivecpu_jam(), and drivecpu_setup_context().
drivecpu_set_overflow()
void drivecpu_set_overflow (diskunit_context_t * drv)
Referenced by drive_cpu_set_overflow().
drivecpu_setup_context()
void drivecpu_setup_context (struct diskunit_context_s * drv, int i)
Referenced by drive_set_disk_drive_type(), and drive_setup_context_for_unit().
drivecpu_shutdown()
void drivecpu_shutdown (diskunit_context_t * drv)
Referenced by drive_shutdown().
drivecpu_sleep()
void drivecpu_sleep (diskunit_context_t * drv) inline
Referenced by drive_disable(), and drivecpu_execute().
drivecpu_snapshot_read_module()
int drivecpu_snapshot_read_module (diskunit_context_t * drv, snapshot_t * s)
Referenced by drive_snapshot_read_module().
drivecpu_snapshot_write_module()
int drivecpu_snapshot_write_module (diskunit_context_t * drv, snapshot_t * s)
Referenced by drive_snapshot_write_module().
drivecpu_trigger_reset()
void drivecpu_trigger_reset (unsigned int dnr)
called by drive_cpu_trigger_reset()
drivecpu_wake_up()
void drivecpu_wake_up (diskunit_context_t * drv) inline
Todo:
FIXME: this value could break some programs, or be way too high for others. Maybe we should put it into a user-definable resource.
Referenced by drive_enable(), and drivecpu_execute().
interrupt_check_irq_delay()
static int interrupt_check_irq_delay (interrupt_cpu_status_t * cs, CLOCK cpu_clk) inline static
interrupt_check_nmi_delay()
static int interrupt_check_nmi_delay (interrupt_cpu_status_t * cs, CLOCK cpu_clk) inline static
Variable Documentation
diskunit_clk
CLOCK diskunit_clk[4]
Global clock counters.
Referenced by drive_image_attach(), drive_image_detach(), drive_init(), drive_setup_context_for_unit(), drivecpu65c02_setup_context(), drivecpu65c02_trigger_reset(), drivecpu_setup_context(), and drivecpu_trigger_reset().
drivecpu_int_status_ptr
interrupt_cpu_status_t* drivecpu_int_status_ptr[4] static
Referenced by drivecpu_setup_context(), and drivecpu_trigger_reset().