vsid: imagecontents/diskcontents.c File Reference
diskcontents.c File Reference
#include "vice.h"
#include <stdio.h>
#include "diskcontents-block.h"
#include "diskcontents-iec.h"
#include "diskcontents.h"
#include "imagecontents.h"
#include "lib.h"
#include "machine-bus.h"
#include "machine.h"
#include "serial.h"
#include "attach.h"
#include "vdrive.h"
#include "vdrive-internal.h"
Functions
image_contents_t * diskcontents_filesystem_read (const char *file_name)
Function Documentation
diskcontents_filesystem_read()
image_contents_t * diskcontents_filesystem_read (const char * file_name)
Referenced by autostart_disk(), create_disk_attach_dialog(), read_contents_wrapper(), and ui_do_drive_popup().