x128: c128/cart/magicdesk128.c File Reference
magicdesk128.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cartridge.h"
#include "cartio.h"
#include "log.h"
#include "util.h"
#include "monitor.h"
#include "vicii-phi1.h"
#include "c64cart.h"
#include "export.h"
#include "c128cart.h"
#include "functionrom.h"
#include "crt.h"
#include "magicdesk128.h"
Macros
#define DBG(x)
#define MD128_ROM_BANKS 0x40
#define MD128_BANK_SIZE 0x4000
#define MD128_ROM_SIZE (MD128_BANK_SIZE * MD128_ROM_BANKS)
#define SNAP_MAJOR 0
#define SNAP_MINOR 0
Functions
static uint8_t magicdesk128_io1_peek (uint16_t addr)
some prototypes are needed
static uint8_t magicdesk128_io1_read (uint16_t addr)
static void magicdesk128_io1_store (uint16_t addr, uint8_t value)
static int magicdesk128_dump (void)
void magicdesk128_config_setup (uint8_t *rawcart)
static int magicdesk128_common_attach (void)
int magicdesk128_bin_attach (const char *filename, uint8_t *rawcart)
int magicdesk128_crt_attach (FILE *fd, uint8_t *rawcart)
void magicdesk128_detach (void)
void magicdesk128_reset (void)
int magicdesk128_snapshot_write_module (snapshot_t *s)
int magicdesk128_snapshot_read_module (snapshot_t *s)
Variables
static unsigned int md128reg = 0
static unsigned int rombank = 0
static unsigned int bankmask = (0x40 - 1)
static io_source_t magicdesk128_io1_device
static io_source_list_t * magicdesk128_io1_list_item = NULL
static const export_resource_t export_res
static char snap_module_name [] = "MAGICDESK128"
Macro Definition Documentation
DBG
#define DBG (x)
MD128_BANK_SIZE
#define MD128_BANK_SIZE 0x4000
MD128_ROM_BANKS
#define MD128_ROM_BANKS 0x40
MD128_ROM_SIZE
#define MD128_ROM_SIZE (MD128_BANK_SIZE * MD128_ROM_BANKS)
SNAP_MAJOR
#define SNAP_MAJOR 0
SNAP_MINOR
#define SNAP_MINOR 0
Function Documentation
magicdesk128_bin_attach()
int magicdesk128_bin_attach (const char * filename, uint8_t * rawcart)
Referenced by c128cartridge_bin_attach().
magicdesk128_common_attach()
static int magicdesk128_common_attach (void) static
Referenced by magicdesk128_bin_attach(), magicdesk128_crt_attach(), and magicdesk128_snapshot_read_module().
magicdesk128_config_setup()
void magicdesk128_config_setup (uint8_t * rawcart)
Referenced by c128cartridge_config_setup().
magicdesk128_crt_attach()
int magicdesk128_crt_attach (FILE * fd, uint8_t * rawcart)
Referenced by c128cartridge_attach_crt().
magicdesk128_detach()
void magicdesk128_detach (void)
Referenced by c128cartridge_detach_image().
magicdesk128_dump()
static int magicdesk128_dump (void) static
magicdesk128_io1_peek()
static uint8_t magicdesk128_io1_peek (uint16_t addr) static
some prototypes are needed
magicdesk128_io1_read()
static uint8_t magicdesk128_io1_read (uint16_t addr) static
magicdesk128_io1_store()
static void magicdesk128_io1_store (uint16_t addr, uint8_t value) static
Referenced by magicdesk128_common_attach().
magicdesk128_reset()
void magicdesk128_reset (void)
Referenced by c128cartridge_reset().
magicdesk128_snapshot_read_module()
int magicdesk128_snapshot_read_module (snapshot_t * s)
Referenced by c128cartridge_snapshot_read().
magicdesk128_snapshot_write_module()
int magicdesk128_snapshot_write_module (snapshot_t * s)
Referenced by c128cartridge_snapshot_write().
Variable Documentation
bankmask
unsigned int bankmask = (0x40 - 1) static
Referenced by magicdesk128_bin_attach(), magicdesk128_crt_attach(), magicdesk128_dump(), magicdesk128_io1_read(), and magicdesk128_io1_store().
export_res
const export_resource_t export_res static
Initial value:
= {
     "Magic Desk 128" , 1, 1, &magicdesk128_io1_device, NULL, ((  4  ) +  ( 79   + 1) )
}
Referenced by magicdesk128_common_attach(), and magicdesk128_detach().
magicdesk128_io1_device
io_source_t magicdesk128_io1_device static
Initial value:
= {
     "Magic Desk 128" ,
     0 ,
     NULL ,
    0xde00, 0xdeff, 0xff,
    1,
    magicdesk128_io1_store,
    NULL,
    magicdesk128_io1_read,
    magicdesk128_io1_peek,
    magicdesk128_dump,
    ((  4  ) +  ( 79   + 1) ) ,
     0  ,
    0,
     0
}
Referenced by magicdesk128_common_attach().
magicdesk128_io1_list_item
io_source_list_t* magicdesk128_io1_list_item = NULL static
Referenced by magicdesk128_common_attach(), and magicdesk128_detach().
md128reg
unsigned int md128reg = 0 static
Referenced by magicdesk128_dump(), magicdesk128_io1_store(), and magicdesk128_reset().
rombank
unsigned int rombank = 0 static
Referenced by magicdesk128_dump(), magicdesk128_io1_peek(), magicdesk128_io1_read(), magicdesk128_io1_store(), and magicdesk128_reset().
snap_module_name
char snap_module_name[] = "MAGICDESK128" static
Referenced by magicdesk128_snapshot_read_module(), and magicdesk128_snapshot_write_module().