vsid: c64/c64io.c File Reference
c64io.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "archdep.h"
#include "cartio.h"
#include "cartridge.h"
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "monitor.h"
#include "resources.h"
#include "types.h"
#include "uiapi.h"
#include "util.h"
#include "vicii-phi1.h"
#include "vicii.h"
Macros
#define DBG(x)
#define DBGRW(x)
Functions
static void io_source_detach (io_source_detach_t *source)
static void io_source_msg_detach_all (uint16_t addr, int amount, io_source_list_t *start)
static void io_source_msg_detach_last (uint16_t addr, int amount, io_source_list_t *start, unsigned int lowest)
static void io_source_log_collisions (uint16_t addr, int amount, io_source_list_t *start)
static uint8_t io_read (io_source_list_t *list, uint16_t addr)
static uint8_t io_peek (io_source_list_t *list, uint16_t addr)
peek from I/O area with no side-effects
static void io_store (io_source_list_t *list, uint16_t addr, uint8_t value)
io_source_list_t * io_source_register (io_source_t *device)
void io_source_unregister (io_source_list_t *device)
void cartio_shutdown (void)
void cartio_set_highest_order (unsigned int nr)
uint8_t c64io_d000_read (uint16_t addr)
uint8_t c64io_d000_peek (uint16_t addr)
void c64io_d000_store (uint16_t addr, uint8_t value)
uint8_t c64io_d100_read (uint16_t addr)
uint8_t c64io_d100_peek (uint16_t addr)
void c64io_d100_store (uint16_t addr, uint8_t value)
uint8_t c64io_d200_read (uint16_t addr)
uint8_t c64io_d200_peek (uint16_t addr)
void c64io_d200_store (uint16_t addr, uint8_t value)
uint8_t c64io_d300_read (uint16_t addr)
uint8_t c64io_d300_peek (uint16_t addr)
void c64io_d300_store (uint16_t addr, uint8_t value)
uint8_t c64io_d400_read (uint16_t addr)
uint8_t c64io_d400_peek (uint16_t addr)
void c64io_d400_store (uint16_t addr, uint8_t value)
uint8_t c64io_d500_read (uint16_t addr)
uint8_t c64io_d500_peek (uint16_t addr)
void c64io_d500_store (uint16_t addr, uint8_t value)
uint8_t c64io_d600_read (uint16_t addr)
uint8_t c64io_d600_peek (uint16_t addr)
void c64io_d600_store (uint16_t addr, uint8_t value)
uint8_t c64io_d700_read (uint16_t addr)
uint8_t c64io_d700_peek (uint16_t addr)
void c64io_d700_store (uint16_t addr, uint8_t value)
uint8_t c64io_dd00_read (uint16_t addr)
uint8_t c64io_dd00_peek (uint16_t addr)
void c64io_dd00_store (uint16_t addr, uint8_t value)
uint8_t c64io_de00_read (uint16_t addr)
uint8_t c64io_de00_peek (uint16_t addr)
void c64io_de00_store (uint16_t addr, uint8_t value)
uint8_t c64io_df00_read (uint16_t addr)
uint8_t c64io_df00_peek (uint16_t addr)
void c64io_df00_store (uint16_t addr, uint8_t value)
static void io_source_ioreg_add_onelist (struct mem_ioreg_list_s **mem_ioreg_list, io_source_list_t *current)
void io_source_ioreg_add_list (struct mem_ioreg_list_s **mem_ioreg_list)
add all registered I/O devices to the list for the monitor
static int set_io_source_collision_handling (int val, void *param)
int cartio_resources_init (void)
int cartio_cmdline_options_init (void)
Variables
static int io_source_collision_handling = 0
static unsigned int order = 0
static io_source_list_t c64io_d000_head = { NULL, NULL, NULL }
static io_source_list_t c64io_d100_head = { NULL, NULL, NULL }
static io_source_list_t c64io_d200_head = { NULL, NULL, NULL }
static io_source_list_t c64io_d300_head = { NULL, NULL, NULL }
static io_source_list_t c64io_d400_head = { NULL, NULL, NULL }
static io_source_list_t c64io_d500_head = { NULL, NULL, NULL }
static io_source_list_t c64io_d600_head = { NULL, NULL, NULL }
static io_source_list_t c64io_d700_head = { NULL, NULL, NULL }
static io_source_list_t c64io_dd00_head = { NULL, NULL, NULL }
static io_source_list_t c64io_de00_head = { NULL, NULL, NULL }
static io_source_list_t c64io_df00_head = { NULL, NULL, NULL }
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
Macro Definition Documentation
DBG
#define DBG (x)
DBGRW
#define DBGRW (x)
Function Documentation
c64io_d000_peek()
uint8_t c64io_d000_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d000_read()
uint8_t c64io_d000_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
c64io_d000_store()
void c64io_d000_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
c64io_d100_peek()
uint8_t c64io_d100_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d100_read()
uint8_t c64io_d100_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
c64io_d100_store()
void c64io_d100_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
c64io_d200_peek()
uint8_t c64io_d200_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d200_read()
uint8_t c64io_d200_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
c64io_d200_store()
void c64io_d200_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
c64io_d300_peek()
uint8_t c64io_d300_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d300_read()
uint8_t c64io_d300_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
c64io_d300_store()
void c64io_d300_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
c64io_d400_peek()
uint8_t c64io_d400_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d400_read()
uint8_t c64io_d400_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
c64io_d400_store()
void c64io_d400_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
c64io_d500_peek()
uint8_t c64io_d500_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d500_read()
uint8_t c64io_d500_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
c64io_d500_store()
void c64io_d500_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
c64io_d600_peek()
uint8_t c64io_d600_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d600_read()
uint8_t c64io_d600_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
c64io_d600_store()
void c64io_d600_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
c64io_d700_peek()
uint8_t c64io_d700_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d700_read()
uint8_t c64io_d700_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
c64io_d700_store()
void c64io_d700_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
c64io_dd00_peek()
uint8_t c64io_dd00_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_dd00_read()
uint8_t c64io_dd00_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
c64io_dd00_store()
void c64io_dd00_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
c64io_de00_peek()
uint8_t c64io_de00_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_de00_read()
uint8_t c64io_de00_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
c64io_de00_store()
void c64io_de00_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
c64io_df00_peek()
uint8_t c64io_df00_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_df00_read()
uint8_t c64io_df00_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
c64io_df00_store()
void c64io_df00_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
cartio_cmdline_options_init()
int cartio_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
cartio_resources_init()
int cartio_resources_init (void)
Referenced by machine_resources_init().
cartio_set_highest_order()
void cartio_set_highest_order (unsigned int nr)
cartio_shutdown()
void cartio_shutdown (void)
Referenced by machine_resources_shutdown().
io_peek()
static uint8_t io_peek (io_source_list_t * list, uint16_t addr) inline static
peek from I/O area with no side-effects
Referenced by c64io_d000_peek(), c64io_d100_peek(), c64io_d200_peek(), c64io_d300_peek(), c64io_d400_peek(), c64io_d500_peek(), c64io_d600_peek(), c64io_d700_peek(), c64io_dd00_peek(), c64io_de00_peek(), and c64io_df00_peek().
io_read()
static uint8_t io_read (io_source_list_t * list, uint16_t addr) inline static
< override others on collisions
< overridden by others on collisions
< overridden by others on collisions
< overridden by others on collisions
Referenced by c64io_d000_read(), c64io_d100_read(), c64io_d200_read(), c64io_d300_read(), c64io_d400_read(), c64io_d500_read(), c64io_d600_read(), c64io_d700_read(), c64io_dd00_read(), c64io_de00_read(), and c64io_df00_read().
io_source_detach()
static void io_source_detach (io_source_detach_t * source) static
Referenced by io_source_msg_detach_all(), and io_source_msg_detach_last().
io_source_ioreg_add_list()
void io_source_ioreg_add_list (struct mem_ioreg_list_s ** mem_ioreg_list)
add all registered I/O devices to the list for the monitor
Referenced by mem_ioreg_list_get().
io_source_ioreg_add_onelist()
static void io_source_ioreg_add_onelist (struct mem_ioreg_list_s ** mem_ioreg_list, io_source_list_t * current) static
Referenced by io_source_ioreg_add_list().
io_source_log_collisions()
static void io_source_log_collisions (uint16_t addr, int amount, io_source_list_t * start) static
< handle collisions
Referenced by io_read().
io_source_msg_detach_all()
static void io_source_msg_detach_all (uint16_t addr, int amount, io_source_list_t * start) static
< handle collisions
Referenced by io_read().
io_source_msg_detach_last()
static void io_source_msg_detach_last (uint16_t addr, int amount, io_source_list_t * start, unsigned int lowest) static
< handle collisions
Referenced by io_read().
io_source_register()
io_source_list_t * io_source_register (io_source_t * device)
Referenced by c64_cia2_enable(), c64io_init(), c64io_vicii_reinit(), machine_sid2_enable(), plus256k_activate(), plus60k_activate(), set_c64_256k_base(), and set_c64_256k_enabled().
io_source_unregister()
void io_source_unregister (io_source_list_t * device)
Referenced by c64_cia2_enable(), c64io_vicii_deinit(), cartio_shutdown(), machine_sid2_enable(), plus256k_deactivate(), plus60k_deactivate(), set_c64_256k_base(), and set_c64_256k_enabled().
io_store()
static void io_store (io_source_list_t * list, uint16_t addr, uint8_t value) inline static
< overridden by others on collisions
Referenced by c64io_d000_store(), c64io_d100_store(), c64io_d200_store(), c64io_d300_store(), c64io_d400_store(), c64io_d500_store(), c64io_d600_store(), c64io_d700_store(), c64io_dd00_store(), c64io_de00_store(), and c64io_df00_store().
set_io_source_collision_handling()
static int set_io_source_collision_handling (int val, void * param) static
Variable Documentation
c64io_d000_head
io_source_list_t c64io_d000_head = { NULL, NULL, NULL } static
Referenced by c64io_d000_peek(), c64io_d000_read(), c64io_d000_store(), cartio_shutdown(), io_source_ioreg_add_list(), and io_source_register().
c64io_d100_head
io_source_list_t c64io_d100_head = { NULL, NULL, NULL } static
Referenced by c64io_d100_peek(), c64io_d100_read(), c64io_d100_store(), cartio_shutdown(), io_source_ioreg_add_list(), and io_source_register().
c64io_d200_head
io_source_list_t c64io_d200_head = { NULL, NULL, NULL } static
Referenced by c64io_d200_peek(), c64io_d200_read(), c64io_d200_store(), cartio_shutdown(), io_source_ioreg_add_list(), and io_source_register().
c64io_d300_head
io_source_list_t c64io_d300_head = { NULL, NULL, NULL } static
Referenced by c64io_d300_peek(), c64io_d300_read(), c64io_d300_store(), cartio_shutdown(), io_source_ioreg_add_list(), and io_source_register().
c64io_d400_head
io_source_list_t c64io_d400_head = { NULL, NULL, NULL } static
Referenced by c64io_d400_peek(), c64io_d400_read(), c64io_d400_store(), cartio_shutdown(), io_source_ioreg_add_list(), and io_source_register().
c64io_d500_head
io_source_list_t c64io_d500_head = { NULL, NULL, NULL } static
Referenced by c64io_d500_peek(), c64io_d500_read(), c64io_d500_store(), cartio_shutdown(), io_source_ioreg_add_list(), and io_source_register().
c64io_d600_head
io_source_list_t c64io_d600_head = { NULL, NULL, NULL } static
Referenced by c64io_d600_peek(), c64io_d600_read(), c64io_d600_store(), cartio_shutdown(), io_source_ioreg_add_list(), and io_source_register().
c64io_d700_head
io_source_list_t c64io_d700_head = { NULL, NULL, NULL } static
Referenced by c64io_d700_peek(), c64io_d700_read(), c64io_d700_store(), cartio_shutdown(), io_source_ioreg_add_list(), and io_source_register().
c64io_dd00_head
io_source_list_t c64io_dd00_head = { NULL, NULL, NULL } static
Referenced by c64io_dd00_peek(), c64io_dd00_read(), c64io_dd00_store(), cartio_shutdown(), io_source_ioreg_add_list(), and io_source_register().
c64io_de00_head
io_source_list_t c64io_de00_head = { NULL, NULL, NULL } static
Referenced by c64io_de00_peek(), c64io_de00_read(), c64io_de00_store(), cartio_shutdown(), io_source_ioreg_add_list(), and io_source_register().
c64io_df00_head
io_source_list_t c64io_df00_head = { NULL, NULL, NULL } static
Referenced by c64io_df00_peek(), c64io_df00_read(), c64io_df00_store(), cartio_shutdown(), io_source_ioreg_add_list(), and io_source_register().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-iocollision", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "IOCollisionHandling", NULL,
      "<method>", "Select the way the I/O collisions should be handled, (0: error message and detach all involved carts, 1: error message and detach last attached involved carts, 2: warning in log and 'AND' the valid return values" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by cartio_cmdline_options_init().
io_source_collision_handling
int io_source_collision_handling = 0 static
Referenced by io_read(), and set_io_source_collision_handling().
order
unsigned int order = 0 static
Referenced by cartio_set_highest_order(), io_source_msg_detach_last(), io_source_register(), and io_source_unregister().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "IOCollisionHandling",  0 , RES_EVENT_STRICT, (resource_value_t)0,
      &io_source_collision_handling, set_io_source_collision_handling, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by cartio_resources_init().