vsid: printerdrv/printer.h File Reference
printer.h File Reference
#include "types.h"
Macros
#define PRINTER_IEC_NUM 2
Serial interface.
#define PRINTER_DEVICE_NONE 0
#define PRINTER_DEVICE_FS 1
#define PRINTER_DEVICE_REAL 2
#define PRINTER_TEXT_DEVICE_1 0
#define PRINTER_TEXT_DEVICE_2 1
#define PRINTER_TEXT_DEVICE_3 2
#define PRINTER_IEC_4 0
CBM devnr 4.
#define PRINTER_IEC_5 1
CBM devnr 5.
#define PRINTER_IEC_6 2
CBM devnr 6.
#define PRINTER_USERPORT 3
#define MPS801_ROM_SIZE (4 * 1024)
#define CBM1526_ROM_SIZE (8 * 1024)
#define MPS802_ROM_SIZE CBM1526_ROM_SIZE
#define MPS803_ROM_SIZE (4 * 1024)
#define C2022_ROM_SIZE (4 * 1024)
#define C2023_ROM_SIZE (4 * 1024)
#define C4023_ROM_SIZE (8 * 1024)
#define C8023_ROM_SIZE (8 * 1024)
#define MPS801_ROM_NAME "mps801.bin"
c1fbd1f3
#define CBM1526_ROM_NAME "cbm1526-325341-08.bin"
same as mps802 ?
#define MPS802_ROM_NAME CBM1526_ROM_NAME
#define MPS803_ROM_NAME "mps803-D7811G-111-U32053A.bin"
#define C2022_ROM_NAME "2022-901472-04.bin"
2022/2023
#define C4023_ROM_NAME "4023-325360-02.bin"
4023
#define C8023_ROM_NAME "8023-325320-02.bin"
8023
#define NL10_ROM_NAME "nl10.bin"
Functions
int printer_resources_init (void)
Generic interface.
int printer_userport_resources_init (void)
void printer_resources_shutdown (void)
int printer_cmdline_options_init (void)
int printer_userport_cmdline_options_init (void)
void printer_init (void)
void printer_reset (void)
void printer_formfeed (unsigned int unit)
Send formfeed to printer.
void printer_shutdown (void)
int printer_serial_init_resources (void)
int printer_serial_init_cmdline_options (void)
void printer_serial_init (void)
int printer_serial_close (unsigned int unit)
int printer_serial_late_init (void)
void printer_serial_shutdown (void)
int printer_userport_init_resources (void)
Userport interface.
Macro Definition Documentation
C2022_ROM_NAME
#define C2022_ROM_NAME "2022-901472-04.bin"
2022/2023
C2022_ROM_SIZE
#define C2022_ROM_SIZE (4 * 1024)
C2023_ROM_SIZE
#define C2023_ROM_SIZE (4 * 1024)
C4023_ROM_NAME
#define C4023_ROM_NAME "4023-325360-02.bin"
4023
C4023_ROM_SIZE
#define C4023_ROM_SIZE (8 * 1024)
C8023_ROM_NAME
#define C8023_ROM_NAME "8023-325320-02.bin"
8023
C8023_ROM_SIZE
#define C8023_ROM_SIZE (8 * 1024)
CBM1526_ROM_NAME
#define CBM1526_ROM_NAME "cbm1526-325341-08.bin"
same as mps802 ?
CBM1526_ROM_SIZE
#define CBM1526_ROM_SIZE (8 * 1024)
MPS801_ROM_NAME
#define MPS801_ROM_NAME "mps801.bin"
c1fbd1f3
MPS801_ROM_SIZE
#define MPS801_ROM_SIZE (4 * 1024)
MPS802_ROM_NAME
#define MPS802_ROM_NAME CBM1526_ROM_NAME
MPS802_ROM_SIZE
#define MPS802_ROM_SIZE CBM1526_ROM_SIZE
MPS803_ROM_NAME
#define MPS803_ROM_NAME "mps803-D7811G-111-U32053A.bin"
MPS803_ROM_SIZE
#define MPS803_ROM_SIZE (4 * 1024)
NL10_ROM_NAME
#define NL10_ROM_NAME "nl10.bin"
PRINTER_DEVICE_FS
#define PRINTER_DEVICE_FS 1
PRINTER_DEVICE_NONE
#define PRINTER_DEVICE_NONE 0
PRINTER_DEVICE_REAL
#define PRINTER_DEVICE_REAL 2
PRINTER_IEC_4
#define PRINTER_IEC_4 0
CBM devnr 4.
PRINTER_IEC_5
#define PRINTER_IEC_5 1
CBM devnr 5.
PRINTER_IEC_6
#define PRINTER_IEC_6 2
CBM devnr 6.
PRINTER_IEC_NUM
#define PRINTER_IEC_NUM 2
Serial interface.
PRINTER_TEXT_DEVICE_1
#define PRINTER_TEXT_DEVICE_1 0
PRINTER_TEXT_DEVICE_2
#define PRINTER_TEXT_DEVICE_2 1
PRINTER_TEXT_DEVICE_3
#define PRINTER_TEXT_DEVICE_3 2
PRINTER_USERPORT
#define PRINTER_USERPORT 3
Function Documentation
printer_cmdline_options_init()
int printer_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
printer_formfeed()
void printer_formfeed (unsigned int prnr)
Send formfeed to printer.
Parameters
[in] prnr device index (0-2: 4-6, 3: userport)
Todo:
FIXME: this stub can be removed once all GUI's have been adapted to not use this call for vsid
Referenced by on_formfeed_clicked(), and printer_formfeed_action().
printer_init()
void printer_init (void)
Referenced by machine_specific_init().
printer_reset()
void printer_reset (void)
Referenced by machine_specific_reset().
printer_resources_init()
int printer_resources_init (void)
Generic interface.
Referenced by machine_resources_init().
printer_resources_shutdown()
void printer_resources_shutdown (void)
Referenced by machine_resources_shutdown().
printer_serial_close()
int printer_serial_close (unsigned int unit)
printer_serial_init()
void printer_serial_init (void)
Referenced by machine_printer_init().
printer_serial_init_cmdline_options()
int printer_serial_init_cmdline_options (void)
Referenced by machine_printer_cmdline_options_init().
printer_serial_init_resources()
int printer_serial_init_resources (void)
Referenced by machine_printer_resources_init().
printer_serial_late_init()
int printer_serial_late_init (void)
Referenced by serial_init().
printer_serial_shutdown()
void printer_serial_shutdown (void)
Referenced by machine_printer_shutdown().
printer_shutdown()
void printer_shutdown (void)
< serial dev 4, 5, 6 and user port
Referenced by cmdline_help(), and machine_shutdown().
printer_userport_cmdline_options_init()
int printer_userport_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
printer_userport_init_resources()
int printer_userport_init_resources (void)
Userport interface.
Referenced by machine_printer_resources_init().
printer_userport_resources_init()
int printer_userport_resources_init (void)
Referenced by machine_resources_init().