x128: core/spi-sdcard.h File Reference
spi-sdcard.h File Reference
#include "types.h"
Functions
void spi_mmc_trigger_mode_write (uint8_t value)
TODO.
uint8_t spi_mmc_trigger_mode_read (void)
TODO.
uint8_t spi_mmc_card_inserted (void)
TODO.
uint8_t spi_mmc_busy (void)
TODO.
uint8_t spi_mmc_card_write_enabled (void)
TODO.
uint8_t spi_mmc_card_selected_read (void)
void spi_mmc_card_selected_write (uint8_t value)
TODO.
uint8_t spi_mmc_enable_8mhz_read (void)
TODO.
void spi_mmc_enable_8mhz_write (uint8_t value)
TODO.
uint8_t spi_mmc_data_read (void)
TODO.
void spi_mmc_data_write (uint8_t value)
TODO.
int mmc_open_card_image (char *name, int rw)
void mmc_close_card_image (void)
uint8_t mmc_set_card_type (uint8_t value)
int mmc_snapshot_read_module (struct snapshot_s *s)
int mmc_snapshot_write_module (struct snapshot_s *s)
Function Documentation
mmc_close_card_image()
void mmc_close_card_image (void)
Referenced by mmc_open_card_image().
mmc_open_card_image()
int mmc_open_card_image (char * name, int rw)
mmc_set_card_type()
uint8_t mmc_set_card_type (uint8_t value)
mmc_snapshot_read_module()
int mmc_snapshot_read_module (struct snapshot_s * s)
mmc_snapshot_write_module()
int mmc_snapshot_write_module (snapshot_t * s)
Todo:
FIXME: implement snapshot support
spi_mmc_busy()
uint8_t spi_mmc_busy (void)
TODO.
0 = SPI ready, 1 = SPI busy
spi_mmc_card_inserted()
uint8_t spi_mmc_card_inserted (void)
TODO.
0 = card inserted, 1 = no card inserted (R)
Referenced by mmc_execute_cmd(), spi_mmc_data_read(), and spi_mmc_set_card_inserted().
spi_mmc_card_selected_read()
uint8_t spi_mmc_card_selected_read (void)
spi_mmc_card_selected_write()
void spi_mmc_card_selected_write (uint8_t value)
TODO.
Referenced by mmc_reset_card().
spi_mmc_card_write_enabled()
uint8_t spi_mmc_card_write_enabled (void)
TODO.
0 = card write enabled, 1 = card write disabled (R)
spi_mmc_data_read()
uint8_t spi_mmc_data_read (void)
TODO.
Todo:
FIXME: wrap strcpy/strcat into macros so they are removed when not debugging
spi_mmc_data_write()
void spi_mmc_data_write (uint8_t value)
TODO.
spi_mmc_enable_8mhz_read()
uint8_t spi_mmc_enable_8mhz_read (void)
TODO.
spi_mmc_enable_8mhz_write()
void spi_mmc_enable_8mhz_write (uint8_t value)
TODO.
spi_mmc_trigger_mode_read()
uint8_t spi_mmc_trigger_mode_read (void)
TODO.
Referenced by spi_mmc_data_read().
spi_mmc_trigger_mode_write()
void spi_mmc_trigger_mode_write (uint8_t value)
TODO.
Referenced by mmc_reset_card().