vsid: machine-bus.c File Reference
machine-bus.c File Reference
#include "vice.h"
#include <stdio.h>
#include "lib.h"
#include "log.h"
#include "machine-bus.h"
#include "serial.h"
#include "types.h"
Macros
#define DBG(x)
#define SERIAL_DEVICE_NOT_PRESENT (0x80)
Functions
static int fn_getf (struct vdrive_s *foo, uint8_t *bar, unsigned int bas)
Call this if device is not attached: -128 == device not present.
static int fn_putf (struct vdrive_s *foo, uint8_t bar, unsigned int bas)
static int fn_openf (struct vdrive_s *foo, const uint8_t *bar, unsigned int bas, unsigned int meloen, struct cbmdos_cmd_parse_s *appel)
static int fn_closef (struct vdrive_s *foo, unsigned int bar)
static void fn_flushf (struct vdrive_s *foo, unsigned int bar)
static void fn_listenf (struct vdrive_s *foo, unsigned int bar)
void machine_bus_init (void)
int machine_bus_device_attach (unsigned int unit, const char *name, int(*getf)(struct vdrive_s *, uint8_t *, unsigned int), int(*putf)(struct vdrive_s *, uint8_t, unsigned int), int(*openf)(struct vdrive_s *, const uint8_t *, unsigned int, unsigned int, struct cbmdos_cmd_parse_s *), int(*closef)(struct vdrive_s *, unsigned int), void(*flushf)(struct vdrive_s *, unsigned int), void(*listenf)(struct vdrive_s *, unsigned int))
int machine_bus_device_detach (unsigned int unit)
Detach and kill serial devices.
Macro Definition Documentation
DBG
#define DBG (x)
SERIAL_DEVICE_NOT_PRESENT
#define SERIAL_DEVICE_NOT_PRESENT (0x80)
Function Documentation
fn_closef()
static int fn_closef (struct vdrive_s * foo, unsigned int bar) static
Referenced by machine_bus_device_detach(), and machine_bus_init().
fn_flushf()
static void fn_flushf (struct vdrive_s * foo, unsigned int bar) static
Referenced by machine_bus_device_detach(), and machine_bus_init().
fn_getf()
static int fn_getf (struct vdrive_s * foo, uint8_t * bar, unsigned int bas) static
Call this if device is not attached: -128 == device not present.
Referenced by machine_bus_device_detach(), and machine_bus_init().
fn_listenf()
static void fn_listenf (struct vdrive_s * foo, unsigned int bar) static
Referenced by machine_bus_device_detach(), and machine_bus_init().
fn_openf()
static int fn_openf (struct vdrive_s * foo, const uint8_t * bar, unsigned int bas, unsigned int meloen, struct cbmdos_cmd_parse_s * appel) static
Referenced by machine_bus_device_detach(), and machine_bus_init().
fn_putf()
static int fn_putf (struct vdrive_s * foo, uint8_t bar, unsigned int bas) static
Referenced by machine_bus_device_detach(), and machine_bus_init().
machine_bus_device_attach()
int machine_bus_device_attach (unsigned int unit, const char * name, int(*)(struct vdrive_s *, uint8_t *, unsigned int) getf, int(*)(struct vdrive_s *, uint8_t, unsigned int) putf, int(*)(struct vdrive_s *, const uint8_t *, unsigned int, unsigned int, struct cbmdos_cmd_parse_s *) openf, int(*)(struct vdrive_s *, unsigned int) closef, void(*)(struct vdrive_s *, unsigned int) flushf, void(*)(struct vdrive_s *, unsigned int) listenf)
machine_bus_device_detach()
int machine_bus_device_detach (unsigned int unit)
Detach and kill serial devices.
Referenced by file_system_shutdown(), interface_serial_detach(), machine_bus_device_attach(), and serial_shutdown().
machine_bus_init()
void machine_bus_init (void)
Referenced by init_main().