vsid: arch/gtk3/widgets/aciawidget.c File Reference
aciawidget.c File Reference
Widget to control various ACIA related resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "lib.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "aciawidget.h"
Functions
static void generate_baud_rate_list (void)
Generate heap-allocated list to use in a resourcecombobox.
static void free_baud_rate_list (void)
Free memory used by baud_rate_list
static void on_destroy (GtkWidget *widget, gpointer user_data)
Handler for the 'destroy' event of the main widget.
static GtkWidget * label_helper (const char *markup)
Create left-aligned label using Pango markup.
static GtkWidget * create_acia_device_widget (void)
Create an ACIA device widget.
static GtkWidget * create_acia_serial_device_widget (int num)
Create a widget to set an ACIA serial device (path + baud rate)
GtkWidget * acia_widget_create (int *baud)
Create ACIA settings widget.
Variables
static int * acia_baud_rates
Reference to baud rates list.
static vice_gtk3_combo_entry_int_t * baud_rate_list = NULL
List of baud rates.
static const vice_gtk3_radiogroup_entry_t acia_device_list []
List of ACIA devices.
Detailed Description
Widget to control various ACIA related resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
acia_widget_create()
GtkWidget * acia_widget_create (int * baud)
Create ACIA settings widget.
XXX: currently designed for PET, might need updating when used in other UIs
Parameters
[in] baud list of baud rates (list of int's, terminated by -1)
Returns
GtkGrid
Referenced by superpet_widget_create().
create_acia_device_widget()
static GtkWidget * create_acia_device_widget (void) static
Create an ACIA device widget.
Creates a widget to select an ACIA device.
Returns
GtkGrid
Referenced by acia_widget_create().
create_acia_serial_device_widget()
static GtkWidget * create_acia_serial_device_widget (int num) static
Create a widget to set an ACIA serial device (path + baud rate)
Parameters
[in] num serial device number
Returns
GtkGrid
Referenced by acia_widget_create().
free_baud_rate_list()
static void free_baud_rate_list (void) static
Free memory used by baud_rate_list
Referenced by on_destroy().
generate_baud_rate_list()
static void generate_baud_rate_list (void) static
Generate heap-allocated list to use in a resourcecombobox.
Creates a list of ui_combo_box_int_t entries from the acia_baud_rates list
Referenced by acia_widget_create().
label_helper()
static GtkWidget * label_helper (const char * markup) static
Create left-aligned label using Pango markup.
Parameters
[in] markup text of the label using Pango markup
Returns
GtkLabel
Referenced by acia_widget_create(), create_acia_device_widget(), and create_acia_serial_device_widget().
on_destroy()
static void on_destroy (GtkWidget * widget, gpointer user_data) static
Handler for the 'destroy' event of the main widget.
Frees memory used by the baud rate list
Parameters
[in] widget main widget (unused)
[in] user_data extra event data (unused)
Referenced by acia_widget_create().
Variable Documentation
acia_baud_rates
int* acia_baud_rates static
Reference to baud rates list.
Referenced by acia_widget_create(), and generate_baud_rate_list().
acia_device_list
const vice_gtk3_radiogroup_entry_t acia_device_list[] static
Initial value:
= {
    { "Serial 1",      0 },
    { "Serial 2",      1 },
    { "Dump to file",  2 },
    { "Exec process",  3 },
    { NULL,           -1 }
}
List of ACIA devices.
Referenced by create_acia_device_widget().
baud_rate_list
vice_gtk3_combo_entry_int_t* baud_rate_list = NULL static
List of baud rates.
Set in acia_widget_create()
Referenced by create_acia_serial_device_widget(), free_baud_rate_list(), and generate_baud_rate_list().