x128: drive/iec/pc8477.c File Reference
pc8477.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "diskimage.h"
#include "drive.h"
#include "drivetypes.h"
#include "log.h"
#include "lib.h"
#include "types.h"
#include "pc8477.h"
#include "alarm.h"
#include "drivesync.h"
#include "fdd.h"
#include "monitor.h"
Data Structures
struct pc8477_s
Macros
#define debug(_x_)
#define STEP_RATE ((16 - drv->step_rate) * drv->mycontext->clock_frequency * 500000 / drv->rate)
#define BYTE_RATE (drv->mycontext->clock_frequency * 8000 / drv->rate)
Typedefs
typedef enum pc8477_state_e pc8477_state_t
typedef enum pc8477_cmd_e pc8477_cmd_t
Enumerations
enum pc8477_state_e {
PC8477_WAIT ,
PC8477_COMMAND ,
PC8477_READ ,
PC8477_WRITE ,
PC8477_EXEC ,
PC8477_RESULT
}
enum pc8477_cmd_e {
PC8477_CMD_INVALID = 0x00 ,
PC8477_CMD_MODE = 0x01 ,
PC8477_CMD_READ_A_TRACK = 0x02 ,
PC8477_CMD_SPECIFY = 0x03 ,
PC8477_CMD_SENSE_DRIVE_STATUS = 0x04 ,
PC8477_CMD_WRITE_DATA = 0x05 ,
PC8477_CMD_READ_DATA = 0x06 ,
PC8477_CMD_RECALIBRATE = 0x07 ,
PC8477_CMD_SENSE_INTERRUPT = 0x08 ,
PC8477_CMD_WRITE_DELETED_DATA = 0x09 ,
PC8477_CMD_READ_ID = 0x0a ,
PC8477_CMD_READ_DELETED_DATA = 0x0c ,
PC8477_CMD_FORMAT_A_TRACK = 0x0d ,
PC8477_CMD_DUMPREG = 0x0e ,
PC8477_CMD_SEEK = 0x0f ,
PC8477_CMD_VERSION = 0x10 ,
PC8477_CMD_SCAN_EQUAL = 0x11 ,
PC8477_CMD_PERPENDICULAR_MODE = 0x12 ,
PC8477_CMD_CONFIGURE = 0x13 ,
PC8477_CMD_LOCK = 0x14 ,
PC8477_CMD_VERIFY = 0x16 ,
PC8477_CMD_NSC = 0x18 ,
PC8477_CMD_SCAN_LOW_OR_EQUAL = 0x19 ,
PC8477_CMD_SCAN_HIGH_OR_EQUAL = 0x1d ,
PC8477_CMD_SET_TRACK = 0x21 ,
PC8477_CMD_RELATIVE_SEEK = 0x8f
}
enum pc8477_st0_e {
PC8477_ST0_EC = 0x10 ,
PC8477_ST0_SE = 0x20
}
enum pc8477_st1_e {
PC8477_ST1_MA = 0x01 ,
PC8477_ST1_NW = 0x02 ,
PC8477_ST1_ND = 0x04 ,
PC8477_ST1_OR = 0x10 ,
PC8477_ST1_CE = 0x20 ,
PC8477_ST1_EOT = 0x80
}
enum pc8477_st2_e {
PC8477_ST2_MD = 0x01 ,
PC8477_ST2_BT = 0x02 ,
PC8477_ST2_SNS = 0x04 ,
PC8477_ST2_SEH = 0x08 ,
PC8477_ST2_WT = 0x10 ,
PC8477_ST2_CM = 0x20
}
enum pc8477_st3_e {
PC8477_ST3_TK0 = 0x10 ,
PC8477_ST3_WP = 0x40
}
enum pc8477_flags_e {
PC8477_FLAGS_DS = 0x01 ,
PC8477_FLAGS_HDS = 0x02 ,
PC8477_FLAGS_MOT = 0x04
}
Functions
static void seek_alarm_handler (CLOCK offset, void *data)
void pc8477d_init (diskunit_context_t *drv)
Functions using drive context.
void pc8477_setup_context (diskunit_context_t *drv)
void pc8477_shutdown (pc8477_t *drv)
static void pc8477_software_reset (pc8477_t *drv)
WD1770 register read/write access.
static void pc8477_result (pc8477_t *drv)
static int pc8477_micro_find_sync (pc8477_t *drv)
static int pc8477_micro_readid (pc8477_t *drv)
static pc8477_state_t pc8477_execute (pc8477_t *drv)
static void pc8477_store (pc8477_t *drv, uint16_t addr, uint8_t byte)
static uint8_t pc8477_read (pc8477_t *drv, uint16_t addr)
static uint8_t pc8477_peek (pc8477_t *drv, uint16_t addr)
read from I/O without side effects
void pc8477d_dump (diskunit_context_t *ctx)
void pc8477_reset (pc8477_t *drv, int is8477)
int pc8477_irq (pc8477_t *drv)
void pc8477d_store (diskunit_context_t *drv, uint16_t addr, uint8_t byte)
uint8_t pc8477d_read (diskunit_context_t *drv, uint16_t addr)
uint8_t pc8477d_peek (diskunit_context_t *drv, uint16_t addr)
int pc8477_attach_image (disk_image_t *image, unsigned int unit)
int pc8477_detach_image (disk_image_t *image, unsigned int unit)
Variables
struct {
uint8_t mask
pc8477_cmd_t command
uint8_t len
uint8_t rlen
uint8_t flags
} pc8477_commands [15]
static log_t pc8477_log = ((log_t)-1)
Macro Definition Documentation
BYTE_RATE
#define BYTE_RATE (drv->mycontext->clock_frequency * 8000 / drv->rate)
debug
#define debug (_x_)
STEP_RATE
#define STEP_RATE ((16 - drv->step_rate) * drv->mycontext->clock_frequency * 500000 / drv->rate)
Typedef Documentation
pc8477_cmd_t
typedef enum pc8477_cmd_e pc8477_cmd_t
pc8477_state_t
typedef enum pc8477_state_e pc8477_state_t
Enumeration Type Documentation
pc8477_cmd_e
enum pc8477_cmd_e
Enumerator
PC8477_CMD_INVALID
PC8477_CMD_MODE
PC8477_CMD_READ_A_TRACK
PC8477_CMD_SPECIFY
PC8477_CMD_SENSE_DRIVE_STATUS
PC8477_CMD_WRITE_DATA
PC8477_CMD_READ_DATA
PC8477_CMD_RECALIBRATE
PC8477_CMD_SENSE_INTERRUPT
PC8477_CMD_WRITE_DELETED_DATA
PC8477_CMD_READ_ID
PC8477_CMD_READ_DELETED_DATA
PC8477_CMD_FORMAT_A_TRACK
PC8477_CMD_DUMPREG
PC8477_CMD_SEEK
PC8477_CMD_VERSION
PC8477_CMD_SCAN_EQUAL
PC8477_CMD_PERPENDICULAR_MODE
PC8477_CMD_CONFIGURE
PC8477_CMD_LOCK
PC8477_CMD_VERIFY
PC8477_CMD_NSC
PC8477_CMD_SCAN_LOW_OR_EQUAL
PC8477_CMD_SCAN_HIGH_OR_EQUAL
PC8477_CMD_SET_TRACK
PC8477_CMD_RELATIVE_SEEK
pc8477_flags_e
enum pc8477_flags_e
Enumerator
PC8477_FLAGS_DS
PC8477_FLAGS_HDS
PC8477_FLAGS_MOT
pc8477_st0_e
enum pc8477_st0_e
Enumerator
PC8477_ST0_EC
PC8477_ST0_SE
pc8477_st1_e
enum pc8477_st1_e
Enumerator
PC8477_ST1_MA
PC8477_ST1_NW
PC8477_ST1_ND
PC8477_ST1_OR
PC8477_ST1_CE
PC8477_ST1_EOT
pc8477_st2_e
enum pc8477_st2_e
Enumerator
PC8477_ST2_MD
PC8477_ST2_BT
PC8477_ST2_SNS
PC8477_ST2_SEH
PC8477_ST2_WT
PC8477_ST2_CM
pc8477_st3_e
enum pc8477_st3_e
Enumerator
PC8477_ST3_TK0
PC8477_ST3_WP
pc8477_state_e
enum pc8477_state_e
Enumerator
PC8477_WAIT
PC8477_COMMAND
PC8477_READ
PC8477_WRITE
PC8477_EXEC
PC8477_RESULT
Function Documentation
pc8477_attach_image()
int pc8477_attach_image (disk_image_t * image, unsigned int unit)
Referenced by iec_drive_image_attach().
pc8477_detach_image()
int pc8477_detach_image (disk_image_t * image, unsigned int unit)
Referenced by iec_drive_image_detach().
pc8477_execute()
static pc8477_state_t pc8477_execute (pc8477_t * drv) static
Todo:
Too early
Referenced by pc8477_read(), and pc8477_store().
pc8477_irq()
int pc8477_irq (pc8477_t * drv)
Referenced by read_prb().
pc8477_micro_find_sync()
static int pc8477_micro_find_sync (pc8477_t * drv) static
Referenced by pc8477_execute().
pc8477_micro_readid()
static int pc8477_micro_readid (pc8477_t * drv) static
Referenced by pc8477_execute().
pc8477_peek()
static uint8_t pc8477_peek (pc8477_t * drv, uint16_t addr) static
read from I/O without side effects
Referenced by pc8477d_peek().
pc8477_read()
static uint8_t pc8477_read (pc8477_t * drv, uint16_t addr) static
Referenced by pc8477d_read().
pc8477_reset()
void pc8477_reset (pc8477_t * drv, int is8477)
Referenced by iec_drive_reset().
pc8477_result()
static void pc8477_result (pc8477_t * drv) static
Referenced by pc8477_read().
pc8477_setup_context()
void pc8477_setup_context (diskunit_context_t * drv)
Referenced by iec_drive_setup_context().
pc8477_shutdown()
void pc8477_shutdown (pc8477_t * drv)
Referenced by iec_drive_shutdown().
pc8477_software_reset()
static void pc8477_software_reset (pc8477_t * drv) static
WD1770 register read/write access.
Referenced by pc8477_reset(), and pc8477_store().
pc8477_store()
static void pc8477_store (pc8477_t * drv, uint16_t addr, uint8_t byte) static
Referenced by pc8477d_store().
pc8477d_dump()
void pc8477d_dump (diskunit_context_t * ctx)
Referenced by drivemem_ioreg_list_get().
pc8477d_init()
void pc8477d_init (diskunit_context_t * drv)
Functions using drive context.
Referenced by iec_drive_init().
pc8477d_peek()
uint8_t pc8477d_peek (diskunit_context_t * drv, uint16_t addr)
Referenced by memiec_init().
pc8477d_read()
uint8_t pc8477d_read (diskunit_context_t * drv, uint16_t addr)
Referenced by memiec_init().
pc8477d_store()
void pc8477d_store (diskunit_context_t * drv, uint16_t addr, uint8_t byte)
Referenced by memiec_init().
seek_alarm_handler()
static void seek_alarm_handler (CLOCK offset, void * data) static
Referenced by pc8477d_init().
Variable Documentation
command
pc8477_cmd_t command
Referenced by pc8477_store().
flags
uint8_t flags
Referenced by linenoise_ng::ConvertUTF16toUTF32(), linenoise_ng::ConvertUTF16toUTF8(), linenoise_ng::ConvertUTF32toUTF16(), linenoise_ng::ConvertUTF32toUTF8(), linenoise_ng::ConvertUTF8toUTF16(), linenoise_ng::ConvertUTF8toUTF32(), create_cart_id_model(), ffmpeg_widget_create(), on_format_changed(), vice_network_receive(), vice_network_send(), and zmbvdrv_record().
len
uint8_t len
mask
uint8_t mask
Referenced by archdep_fix_permissions(), close_pr(), compute_drives_enabled_mask(), create_cart_id_combo_box(), flush_pr(), fsdevice_open_directory(), mon_add_number_masked_to_buffer(), on_cart_type_changed(), on_key_release_event(), on_menu_item_destroy(), on_server_mask_toggled(), open_pr(), parallel_clr_atn(), parallel_clr_dav(), parallel_clr_eoi(), parallel_clr_ndac(), parallel_clr_nrfd(), parallel_restore_clr_atn(), parallel_restore_set_atn(), parallel_set_atn(), parallel_set_dav(), parallel_set_eoi(), parallel_set_ndac(), parallel_set_nrfd(), reSID::Filter::set_voice_mask(), reSID::SID::set_voice_mask(), show_hotkey_dialog(), ui_hotkeys_arch_modmask_from_arch(), ui_hotkeys_arch_modmask_to_arch(), userport_io_sim_set_pax_out_lines(), userport_io_sim_set_pbx_out_lines(), vhk_modifier_name(), vhk_parser_do_undef(), vicii_set_chargen_addr_options(), vicii_set_phi1_addr_options(), vicii_set_phi1_chargen_addr_options(), vicii_set_phi2_addr_options(), vicii_set_phi2_chargen_addr_options(), and write_pr().
const struct { ... } pc8477_commands[15]
Initial value:
= {
    {0x1f, PC8477_CMD_READ_DATA,          9, 7,  PC8477_FLAGS_DS | PC8477_FLAGS_HDS | PC8477_FLAGS_MOT},
    {0xbf, PC8477_CMD_READ_ID,            2, 7,  PC8477_FLAGS_DS | PC8477_FLAGS_HDS | PC8477_FLAGS_MOT},
    {0xbf, PC8477_CMD_FORMAT_A_TRACK,     6, 7,  PC8477_FLAGS_DS | PC8477_FLAGS_HDS | PC8477_FLAGS_MOT},
    {0x3f, PC8477_CMD_WRITE_DATA,         9, 7,  PC8477_FLAGS_DS | PC8477_FLAGS_HDS | PC8477_FLAGS_MOT},
    {0xff, PC8477_CMD_SENSE_DRIVE_STATUS, 2, 1,  PC8477_FLAGS_DS | PC8477_FLAGS_HDS},
    {0xff, PC8477_CMD_SPECIFY,            3, 0,  0},
    {0xff, PC8477_CMD_SEEK,               3, 0,  PC8477_FLAGS_DS | PC8477_FLAGS_HDS | PC8477_FLAGS_MOT},
    {0xff, PC8477_CMD_RECALIBRATE,        2, 0,  PC8477_FLAGS_DS},
    {0xbf, PC8477_CMD_SET_TRACK,          3, 0,  PC8477_FLAGS_DS},
    {0xff, PC8477_CMD_SENSE_INTERRUPT,    1, 2,  0},
    {0xff, PC8477_CMD_VERSION,            1, 1,  0},
    {0xff, PC8477_CMD_NSC,                1, 1,  0},
    {0xff, PC8477_CMD_DUMPREG,            1, 10, 0},
    {0xff, PC8477_CMD_PERPENDICULAR_MODE, 2, 0,  0},
    {0x00, PC8477_CMD_INVALID,            1, 1,  0}
}
Referenced by pc8477_store().
pc8477_log
log_t pc8477_log = ((log_t)-1) static
Referenced by pc8477_attach_image(), pc8477_detach_image(), pc8477_execute(), pc8477_result(), pc8477_store(), and pc8477d_init().
rlen
uint8_t rlen
Referenced by voc_close(), voc_write(), and wav_close().