vsid: c64/c64-resources.h File Reference
c64-resources.h File Reference
Functions
int c64_resources_init (void)
void c64_resources_shutdown (void)
void c64_resources_update_cia_models (int model)
Variables
int acia_de_enabled
int cia1_model
"old"
int cia2_model
"old"
Function Documentation
c64_resources_init()
int c64_resources_init (void)
Referenced by machine_resources_init().
c64_resources_shutdown()
void c64_resources_shutdown (void)
Referenced by machine_resources_shutdown().
c64_resources_update_cia_models()
void c64_resources_update_cia_models (int model)
Referenced by set_cia_model().
Variable Documentation
acia_de_enabled
int acia_de_enabled extern
cia1_model
int cia1_model extern
"old"
Referenced by cia1_setup_context(), cia1_update_model(), and set_cia1_model().
cia2_model
int cia2_model extern
"old"
Referenced by cia2_setup_context(), cia2_update_model(), and set_cia2_model().