x128: drive/tcbm/tcbmrom.h File Reference
tcbmrom.h File Reference
#include "types.h"
Functions
void tcbmrom_init (void)
void tcbmrom_setup_image (struct diskunit_context_s *unit)
int tcbmrom_check_loaded (unsigned int type)
int tcbmrom_load_1551 (void)
Function Documentation
tcbmrom_check_loaded()
int tcbmrom_check_loaded (unsigned int type)
Referenced by tcbm_drive_rom_check_loaded().
tcbmrom_init()
void tcbmrom_init (void)
Referenced by tcbm_drive_init().
tcbmrom_load_1551()
int tcbmrom_load_1551 (void)
Referenced by set_dos_rom_name_1551(), and tcbm_drive_rom_load().
tcbmrom_setup_image()
void tcbmrom_setup_image (struct diskunit_context_s * unit)
Referenced by tcbm_drive_rom_setup_image().