vsid: iecdrive.h File Reference
iecdrive.h File Reference
#include "types.h"
Macros
#define IEC_BUS_IEC 0x01
return value for iec_available_busses() (can be ored)
#define IEC_BUS_IEEE 0x02
parallel IEEE bus
#define IEC_BUS_TCBM 0x04
parallel TCBM bus
#define PARALLEL_WRITE 0
write data
#define PARALLEL_WRITE_HS 1
write data, set flag (cia2)
#define PARALLEL_HS 2
set flag (cia2)
Functions
int iec_available_busses (void)
This function is called from ui_update_menus()
void iec_update_ports_embedded (void)
void iec_drive_write (uint8_t data, unsigned int dnr)
uint8_t iec_drive_read (unsigned int dnr)
void parallel_cable_drive_write (int port, uint8_t data, int handshake, unsigned int dnr)
uint8_t parallel_cable_drive_read (int port, int handshake)
void iec_fast_drive_write (uint8_t data, unsigned int dnr)
void iec_fast_drive_direction (int direction, unsigned int dnr)
void iec_update_cpu_bus (uint8_t data)
void iec_update_ports (void)
void plus4tcbm_update_pa (uint8_t byte, unsigned int dnr)
void plus4tcbm_update_pb (uint8_t byte, unsigned int dnr)
void plus4tcbm_update_pc (uint8_t byte, unsigned int dnr)
Variables
uint8_t plus4tcbm_outputa [2]
KLUDGES: dummy to satisfy linker, unused.
uint8_t plus4tcbm_outputb [2]
uint8_t plus4tcbm_outputc [2]
Macro Definition Documentation
IEC_BUS_IEC
#define IEC_BUS_IEC 0x01
return value for iec_available_busses() (can be ored)
serial IEC bus
IEC_BUS_IEEE
#define IEC_BUS_IEEE 0x02
parallel IEEE bus
IEC_BUS_TCBM
#define IEC_BUS_TCBM 0x04
parallel TCBM bus
PARALLEL_HS
#define PARALLEL_HS 2
set flag (cia2)
PARALLEL_WRITE
#define PARALLEL_WRITE 0
write data
PARALLEL_WRITE_HS
#define PARALLEL_WRITE_HS 1
write data, set flag (cia2)
Function Documentation
iec_available_busses()
int iec_available_busses (void)
This function is called from ui_update_menus()
< c64tpi.c
< ieeeflash64.c
< serial IEC bus
< parallel IEEE bus
< serial IEC bus
Referenced by drive_check_type(), and drive_resources_type().
iec_drive_read()
uint8_t iec_drive_read (unsigned int dnr)
Referenced by read_ciapb(), read_pra(), read_prb(), and read_prb10().
iec_drive_write()
void iec_drive_write (uint8_t data, unsigned int dnr)
Referenced by store_ciapb(), store_pra(), store_prb(), store_prb10(), undump_pra(), undump_prb(), and undump_prb10().
iec_fast_drive_direction()
void iec_fast_drive_direction (int direction, unsigned int dnr)
Referenced by store_ciapb(), store_pra(), and store_prb10().
iec_fast_drive_write()
void iec_fast_drive_write (uint8_t data, unsigned int dnr)
Referenced by store_sdr(), store_sr(), and store_sr10().
iec_update_cpu_bus()
void iec_update_cpu_bus (uint8_t data)
Referenced by iecbus_cpu_undump(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), and iecbus_cpu_write_conf3().
iec_update_ports()
void iec_update_ports (void)
Referenced by c64iec_init(), iec_drive_write(), iec_update_ports_embedded(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), and iecbus_cpu_write_conf3().
iec_update_ports_embedded()
void iec_update_ports_embedded (void)
Referenced by drive_snapshot_read_module().
parallel_cable_drive_read()
uint8_t parallel_cable_drive_read (int port, int handshake)
Referenced by read_ciapb(), and read_pra().
parallel_cable_drive_write()
void parallel_cable_drive_write (int port, uint8_t data, int handshake, unsigned int dnr)
< write data, set flag (cia2)
< set flag (cia2)
< write data, set flag (cia2)
< write data
Referenced by drive_snapshot_read_module(), pulse_ciapc(), store_ciapb(), store_pra(), undump_ciapb(), and undump_pra().
plus4tcbm_update_pa()
void plus4tcbm_update_pa (uint8_t byte, unsigned int dnr)
plus4tcbm_update_pb()
void plus4tcbm_update_pb (uint8_t byte, unsigned int dnr)
plus4tcbm_update_pc()
void plus4tcbm_update_pc (uint8_t byte, unsigned int dnr)
Variable Documentation
plus4tcbm_outputa
uint8_t plus4tcbm_outputa[2] extern
KLUDGES: dummy to satisfy linker, unused.
plus4tcbm_outputb
uint8_t plus4tcbm_outputb[2]
plus4tcbm_outputc
uint8_t plus4tcbm_outputc[2]