vsid: c64/vsidsound.c File Reference
vsidsound.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "cartio.h"
#include "cartridge.h"
#include "machine.h"
#include "sid.h"
#include "sid-resources.h"
#include "sound.h"
#include "types.h"
Macros
#define SIDx_CHECK_RANGE(sid_nr)
Functions
void sid_sound_chip_init (void)
int machine_sid2_check_range (unsigned int sid_adr)
Check the base address for the second sid chip.
int machine_sid3_check_range (unsigned int sid_adr)
Check the base address for the third sid chip.
int machine_sid4_check_range (unsigned int sid_adr)
Check the base address for the fourth sid chip.
int machine_sid5_check_range (unsigned int sid_adr)
Check the base address for the fifth sid chip.
int machine_sid6_check_range (unsigned int sid_adr)
Check the base address for the sixth sid chip.
int machine_sid7_check_range (unsigned int sid_adr)
Check the base address for the seventh sid chip.
int machine_sid8_check_range (unsigned int sid_adr)
Check the base address for the eighth sid chip.
void machine_sid2_enable (int val)
char * sound_machine_dump_state (sound_t *psid)
void sound_machine_enable (int enable)
Variables
static sound_chip_t sid_sound_chip
VSID SID sound chip.
static uint16_t sid_sound_chip_offset = 0
Macro Definition Documentation
SIDx_CHECK_RANGE
#define SIDx_CHECK_RANGE (sid_nr)
Value:
    int machine_sid##sid_nr##_check_range(unsigned int sid_adr) \
    {                                                           \
        if (sid_adr >= 0xd400 && sid_adr <= 0xdfe0) {           \
            sid##sid_nr##_address_start = sid_adr;              \
            sid##sid_nr##_address_end = sid_adr + 0x1f;         \
            return 0;                                           \
        }                                                       \
        return -1;                                              \
    }
Function Documentation
machine_sid2_check_range()
int machine_sid2_check_range (unsigned int sid_adr)
Check the base address for the second sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid2_enable()
void machine_sid2_enable (int val)
machine_sid3_check_range()
int machine_sid3_check_range (unsigned int sid_adr)
Check the base address for the third sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid4_check_range()
int machine_sid4_check_range (unsigned int sid_adr)
Check the base address for the fourth sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid5_check_range()
int machine_sid5_check_range (unsigned int sid_adr)
Check the base address for the fifth sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid6_check_range()
int machine_sid6_check_range (unsigned int sid_adr)
Check the base address for the sixth sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid7_check_range()
int machine_sid7_check_range (unsigned int sid_adr)
Check the base address for the seventh sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid8_check_range()
int machine_sid8_check_range (unsigned int sid_adr)
Check the base address for the eighth sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
sid_sound_chip_init()
void sid_sound_chip_init (void)
sound_machine_dump_state()
char * sound_machine_dump_state (sound_t * psid)
Referenced by sound_dump(), and sound_flush().
sound_machine_enable()
void sound_machine_enable (int enable)
Referenced by set_playback_enabled().
Variable Documentation
sid_sound_chip
sound_chip_t sid_sound_chip static
Initial value:
= {
    sid_sound_machine_open,
    sid_sound_machine_init,
    sid_sound_machine_close,
    sid_sound_machine_calculate_samples,
    sid_sound_machine_store,
    sid_sound_machine_read,
    sid_sound_machine_reset,
    sid_sound_machine_cycle_based,
    sid_sound_machine_channels,
    1
}
VSID SID sound chip.
Referenced by sid_sound_chip_init().
sid_sound_chip_offset
uint16_t sid_sound_chip_offset = 0 static
Referenced by sid_sound_chip_init().