vsid: drive/iec/cia1581d.c File Reference
cia1581d.c File Reference
#include "vice.h"
#include <stdio.h>
#include "cia.h"
#include "ciad.h"
#include "debug.h"
#include "drive.h"
#include "drivetypes.h"
#include "iecbus.h"
#include "iecdrive.h"
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "types.h"
#include "wd1770.h"
Data Structures
struct drivecia1581_context_s
Macros
#define PRE_STORE_CIA
#define PRE_READ_CIA
#define PRE_PEEK_CIA
Typedefs
typedef struct drivecia1581_context_s drivecia1581_context_t
Functions
void cia1581_store (diskunit_context_t *ctxptr, uint16_t addr, uint8_t data)
uint8_t cia1581_read (diskunit_context_t *ctxptr, uint16_t addr)
uint8_t cia1581_peek (diskunit_context_t *ctxptr, uint16_t addr)
int cia1581_dump (diskunit_context_t *ctxptr, uint16_t addr)
static void cia_set_int_clk (cia_context_t *cia_context, int value, CLOCK clk)
static void cia_restore_int (cia_context_t *cia_context, int value)
static void do_reset_cia (cia_context_t *cia_context)
static void pulse_ciapc (cia_context_t *cia_context, CLOCK rclk)
static void undump_ciapa (cia_context_t *cia_context, CLOCK rclk, uint8_t b)
static void undump_ciapb (cia_context_t *cia_context, CLOCK rclk, uint8_t b)
static void store_ciapa (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static void store_ciapb (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static uint8_t read_ciapa (cia_context_t *cia_context)
static uint8_t read_ciapb (cia_context_t *cia_context)
static void read_ciaicr (cia_context_t *cia_context)
static void read_sdr (cia_context_t *cia_context)
static void store_sdr (cia_context_t *cia_context, uint8_t byte)
void cia1581_init (diskunit_context_t *ctxptr)
void cia1581_setup_context (diskunit_context_t *ctxptr)
void cia1581_set_timing (cia_context_t *cia_context, int tickspersec, int powerfreq)
Macro Definition Documentation
PRE_PEEK_CIA
#define PRE_PEEK_CIA
PRE_READ_CIA
#define PRE_READ_CIA
PRE_STORE_CIA
#define PRE_STORE_CIA
Typedef Documentation
drivecia1581_context_t
typedef struct drivecia1581_context_s drivecia1581_context_t
Function Documentation
cia1581_dump()
int cia1581_dump (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by drivemem_ioreg_list_get().
cia1581_init()
void cia1581_init (diskunit_context_t * ctxptr)
Referenced by iec_drive_init().
cia1581_peek()
uint8_t cia1581_peek (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by memiec_init().
cia1581_read()
uint8_t cia1581_read (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by memiec_init().
cia1581_set_timing()
void cia1581_set_timing (cia_context_t * cia_context, int tickspersec, int powerfreq)
Referenced by cia1581_setup_context().
cia1581_setup_context()
void cia1581_setup_context (diskunit_context_t * ctxptr)
Todo:
FIXME: incorrect, J1 closed = 1, J1 open, no ticks at all
Referenced by iec_drive_setup_context().
cia1581_store()
void cia1581_store (diskunit_context_t * ctxptr, uint16_t addr, uint8_t data)
Referenced by memiec_init().
cia_restore_int()
static void cia_restore_int (cia_context_t * cia_context, int value) static
Referenced by cia1581_setup_context().
cia_set_int_clk()
static void cia_set_int_clk (cia_context_t * cia_context, int value, CLOCK clk) static
Referenced by cia1581_setup_context().
do_reset_cia()
static void do_reset_cia (cia_context_t * cia_context) static
Referenced by cia1581_setup_context().
pulse_ciapc()
static void pulse_ciapc (cia_context_t * cia_context, CLOCK rclk) static
Referenced by cia1581_setup_context().
read_ciaicr()
static void read_ciaicr (cia_context_t * cia_context) static
Referenced by cia1581_setup_context().
read_ciapa()
static uint8_t read_ciapa (cia_context_t * cia_context) static
< Data direction register for port A
< Port A
< Data direction register for port A
Referenced by cia1581_setup_context().
read_ciapb()
static uint8_t read_ciapb (cia_context_t * cia_context) static
< Port B
< Port B
Referenced by cia1581_setup_context().
read_sdr()
static void read_sdr (cia_context_t * cia_context) static
Referenced by cia1581_setup_context().
store_ciapa()
static void store_ciapa (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
Referenced by cia1581_setup_context().
store_ciapb()
static void store_ciapb (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
Referenced by cia1581_setup_context().
store_sdr()
static void store_sdr (cia_context_t * cia_context, uint8_t byte) static
Referenced by cia1581_setup_context().
undump_ciapa()
static void undump_ciapa (cia_context_t * cia_context, CLOCK rclk, uint8_t b) static
Referenced by cia1581_setup_context().
undump_ciapb()
static void undump_ciapb (cia_context_t * cia_context, CLOCK rclk, uint8_t b) static
Referenced by cia1581_setup_context().