vsid: 6510core.c File Reference
6510core.c File Reference
#include "traps.h"
#include "profiler.h"
Macros
#define CPU_STR "Main CPU"
This file is included by CPU definition files.
#define reg_a_write(c) reg_a = (c)
The C64DTV can use different shadow registers for accu read/write.
#define reg_a_read reg_a
#define reg_x_write(c) reg_x = (c)
#define reg_x_read reg_x
#define reg_y_write(c) reg_y = (c)
#define reg_y_read reg_y
#define CLK_RTS 3
Opcode execution time may vary on the C64DTV.
#define CLK_RTI 4
#define CLK_BRK 5
#define CLK_ABS_I_STORE2 2
#define CLK_STACK_PUSH 1
#define CLK_STACK_PULL 2
#define CLK_ZERO_I_STORE 2
#define CLK_ZERO_I2 2
#define CLK_BRANCH2 1
#define CLK_INT_CYCLE 1
#define CLK_JSR_INT_CYCLE 1
#define CLK_IND_Y_W 2
#define CLK_NOOP_ZERO_X 2
#define IRQ_CYCLES 7
#define NMI_CYCLES 7
#define RESET_CYCLES 6
#define LOAD_IND(a) LOAD(a)
Backup for non-6509 CPUs.
#define STORE_IND(a, b) STORE(a, b)
#define CLK_ADD(clock, amount) ((clock) += (amount))
Backup for non-variable cycle CPUs.
#define CLK_ADD_DUMMY(clock, amount) CLK_ADD(clock, amount)
#define REWIND_FETCH_OPCODE(clock) ((clock) -= 2)
#define CPU_DELAY_CLK
Hook for additional delay.
#define CPU_REFRESH_CLK
#define PROCESS_ALARMS
#define LOCAL_SET_NZ(val) (flag_z = flag_n = (val))
#define LOCAL_SET_OVERFLOW(val)
#define LOCAL_SET_BREAK(val)
#define LOCAL_SET_DECIMAL(val)
#define LOCAL_SET_INTERRUPT(val)
#define LOCAL_SET_CARRY(val)
#define LOCAL_SET_SIGN(val) (flag_n = (val) ? 0x80 : 0)
#define LOCAL_SET_ZERO(val) (flag_z = !(val))
#define LOCAL_SET_STATUS(val)
#define LOCAL_OVERFLOW() (reg_p & P_OVERFLOW)
#define LOCAL_BREAK() (reg_p & P_BREAK)
#define LOCAL_DECIMAL() (reg_p & P_DECIMAL)
#define LOCAL_INTERRUPT() (reg_p & P_INTERRUPT)
#define LOCAL_CARRY() (reg_p & P_CARRY)
#define LOCAL_SIGN() (flag_n & 0x80)
#define LOCAL_ZERO() (!flag_z)
#define LOCAL_STATUS()
#define SET_LAST_OPCODE(x)
Info about the last opcode is not needed.
#define OPCODE_DELAYS_INTERRUPT()
#define OPCODE_DISABLES_IRQ()
#define OPCODE_ENABLES_IRQ()
#define EXPORT_REGISTERS()
Export the local version of the registers.
#define IMPORT_REGISTERS()
Import the public version of the registers.
#define PUSH(val) { STORE(0x100 + reg_sp, (val)); reg_sp--; }
Stack operations.
#define PULL() (++reg_sp, LOAD(0x100 + reg_sp))
#define CHECK_PROFILE_INTERRUPT(dest_addr, handler)
#define CHECK_PROFILE_JSR(dest_addr)
#define CHECK_PROFILE_RTS()
#define CHECK_PROFILE_RTI()
#define TRACE_NMI(clk)
#define TRACE_IRQ(clk)
#define TRACE_BRK()
#define DO_INTERRUPT(int_kind)
#define FETCH_PARAM(addr) (LOAD(addr))
#define FETCH_PARAM_DUMMY(addr) (LOAD_DUMMY(addr))
#define LOAD_ABS(addr) LOAD(addr)
#define LOAD_ABS_X(addr)
#define NOOP_LOAD_ABS_X(addr)
#define LOAD_ABS_X_RMW(addr)
#define LOAD_ABS_Y(addr)
#define LOAD_ABS_Y_RMW(addr)
#define LOAD_IND_X(addr)
#define LOAD_IND_Y(addr)
#define LOAD_ZERO_X(addr)
#define NOOP_LOAD_ZERO_X(addr)
#define LOAD_ZERO_Y(addr)
#define LOAD_IND_Y_BANK(addr)
#define STORE_ABS(addr, value, inc)
#define STORE_ABS_X(addr, value, inc)
#define STORE_ABS_X_RMW(addr, value, inc)
#define STORE_ABS_SH_X(addr, value, inc)
#define STORE_ABS_Y(addr, value, inc)
#define STORE_ABS_Y_RMW(addr, value, inc)
#define STORE_ABS_SH_Y(addr, value, inc)
#define INC_PC(value) (reg_pc += (value))
#define DUMMY_STORE_ABS_RMW(addr, value)
#define DUMMY_STORE_ABS_X_RMW(addr, value)
#define DUMMY_STORE_ABS_Y_RMW(addr, value)
#define ADC(value, clk_inc, pc_inc)
Opcodes.
#define ANC(value, pc_inc)
#define AND(value, clk_inc, pc_inc)
#define ANE_MAGIC 0xef
#define ANE_RDY_MAGIC 0xee
#define ANE(value, pc_inc)
#define ARR(value, pc_inc)
The fanciest opcode ever... ARR!
#define ASL(addr, pc_inc, load_func, store_func, dummy_func)
#define ASL_A()
#define ASR(value, pc_inc)
#define BIT(value, pc_inc)
#define BRANCH(cond, value)
#define BRK()
#define CLC()
#define CLD()
#define CLI()
#define CLV()
#define CMP(value, clk_inc, pc_inc)
#define CPX(value, clk_inc, pc_inc)
#define CPY(value, clk_inc, pc_inc)
#define DCP(addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
#define DCP_IND_Y(addr)
#define DEC(addr, pc_inc, load_func, store_func, dummy_func)
#define DEX()
#define DEY()
#define EOR(value, clk_inc, pc_inc)
#define INC(addr, pc_inc, load_func, store_func, dummy_func)
#define INX()
#define INY()
#define ISB(addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
#define ISB_IND_Y(addr)
#define JAM_02()
#define JMP(addr)
#define JMP_IND()
#define JSR_FIXUP_MSB(x)
HACK: fix JSR MSB in monitor CPU history.
#define JSR()
#define LAS(value, clk_inc, pc_inc)
#define LAX(value, clk_inc, pc_inc)
#define LDA(value, clk_inc, pc_inc)
#define LDX(value, clk_inc, pc_inc)
#define LDY(value, clk_inc, pc_inc)
#define LSR(addr, pc_inc, load_func, store_func, dummy_func)
#define LSR_A()
#define LXA_MAGIC 0xee
needs to be 0xee for wizball
#define LXA_RDY_MAGIC 0xee
#define LXA(value, pc_inc)
#define ORA(value, clk_inc, pc_inc)
#define NOOP(clk_inc, pc_inc) (CLK_ADD(CLK, (clk_inc)), INC_PC(pc_inc))
#define NOOP_IMM(pc_inc) INC_PC(pc_inc)
#define NOOP_ABS()
#define NOOP_ABS_X()
#define NOP() NOOP_IMM(1)
#define PHA()
#define PHP()
#define PLA()
#define PLP()
#define RLA(addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
#define RLA_IND_Y(addr)
#define ROL(addr, pc_inc, load_func, store_func, dummy_func)
#define ROL_A()
#define ROR(addr, pc_inc, load_func, store_func, dummy_func)
#define ROR_A()
#define RRA(addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
#define RRA_IND_Y(addr)
#define RTI()
#define RTS()
#define SAX(addr, clk_inc1, clk_inc2, pc_inc)
#define SAX_ZERO(addr, clk_inc, pc_inc)
#define SBC(value, clk_inc, pc_inc)
#define SBX(value, pc_inc)
#define SEC()
#define SED()
#define SEI()
#define SHA_ABS_Y(addr)
#define SHA_IND_Y(addr)
#define SHX_ABS_Y(addr)
#define SHY_ABS_X(addr)
#define SHS_ABS_Y(addr)
#define SLO(addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
#define SLO_IND_Y(addr)
#define SRE(addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
#define SRE_IND_Y(addr)
#define STA(addr, clk_inc1, clk_inc2, pc_inc, store_func)
#define STA_ZERO(addr, clk_inc, pc_inc)
#define STA_IND_Y(addr)
#define STX(addr, clk_inc, pc_inc)
#define STX_ZERO(addr, clk_inc, pc_inc)
#define STY(addr, clk_inc, pc_inc)
#define STY_ZERO(addr, clk_inc, pc_inc)
#define TAX()
#define TAY()
#define TSX()
#define TXA()
#define TXS()
#define TYA()
#define opcode_t
#define FETCH_OPCODE(o)
#define p0 (opcode.ins)
#define p2 (opcode.op.op16)
#define p1 (opcode.op.op8[0])
#define SET_OPCODE(o)
SET_OPCODE for traps.
Functions
while (CLK >=alarm_context_next_pending_clk(ALARM_CONTEXT))
if (cpu_is_jammed)
if (!(CPU_INT_STATUS->global_pending_int &IK_IRQ) &&(CPU_INT_STATUS->global_pending_int &IK_IRQPEND) &&CPU_INT_STATUS->irq_pending_clk<=CLK)
if (pending_interrupt !=IK_NONE)
if (maincpu_profiling)
SET_LAST_ADDR (reg_pc)
switch ((opcode.ins))
Variables
static const uint8_t fetch_tab []
unsigned int tmpa
Here, the CPU is emulated.
CLOCK profiling_clock_start = CLK
pending_interrupt = CPU_INT_STATUS->global_pending_int
do { if (((int)reg_pc) < bank_limit) { (opcode).ins = *(bank_base + reg_pc); (opcode).op.op16 = (*(bank_base + reg_pc + 1) | (*(bank_base + reg_pc + 2) << 8)); ((CLK) += (2)); if (fetch_tab[(opcode).ins]) { ((CLK) += (1)); } } else { (opcode).ins = LOAD(reg_pc); ((CLK) += (1)); (opcode).op.op16 = LOAD(reg_pc + 1); ((CLK) += (1)); if (fetch_tab[(opcode).ins]) { (opcode).op.op16 |= (LOAD(reg_pc + 2) << 8); ((CLK) += (1)); } } } while (0)
trap_skipped __pad0__
Macro Definition Documentation
ADC
#define ADC (value, clk_inc, pc_inc)
Value:
    do {                                                                                            \
        unsigned int tmp_value;                                                                     \
        unsigned int tmp;                                                                           \
                                                                                                    \
        tmp_value = (value);                                                                        \
        CLK_ADD(CLK, (clk_inc));                                                                    \
                                                                                                    \
        if (LOCAL_DECIMAL()) {                                                                      \
            tmp = (reg_a_read & 0xf) + (tmp_value & 0xf) + (reg_p & 0x1);                           \
            if (tmp > 0x9) {                                                                        \
                tmp += 0x6;                                                                         \
            }                                                                                       \
            if (tmp <= 0x0f) {                                                                      \
                tmp = (tmp & 0xf) + (reg_a_read & 0xf0) + (tmp_value & 0xf0);                       \
            } else {                                                                                \
                tmp = (tmp & 0xf) + (reg_a_read & 0xf0) + (tmp_value & 0xf0) + 0x10;                \
            }                                                                                       \
            LOCAL_SET_ZERO(!((reg_a_read + tmp_value + (reg_p & 0x1)) & 0xff));                     \
            LOCAL_SET_SIGN(tmp & 0x80);                                                             \
            LOCAL_SET_OVERFLOW(((reg_a_read ^ tmp) & 0x80)  && !((reg_a_read ^ tmp_value) & 0x80)); \
            if ((tmp & 0x1f0) > 0x90) {                                                             \
                tmp += 0x60;                                                                        \
            }                                                                                       \
            LOCAL_SET_CARRY((tmp & 0xff0) > 0xf0);                                                  \
        } else {                                                                                    \
            tmp = tmp_value + reg_a_read + (reg_p & P_CARRY);                                       \
            LOCAL_SET_NZ(tmp & 0xff);                                                               \
            LOCAL_SET_OVERFLOW(!((reg_a_read ^ tmp_value) & 0x80)  && ((reg_a_read ^ tmp) & 0x80)); \
            LOCAL_SET_CARRY(tmp > 0xff);                                                            \
        }                                                                                           \
        reg_a_write(tmp);                                                                           \
        INC_PC(pc_inc);                                                                             \
    } while (0)
Opcodes.
ANC
#define ANC (value, pc_inc)
Value:
    do {                                         \
        uint8_t tmp = (uint8_t)(reg_a_read & (value)); \
        reg_a_write(tmp);                        \
        LOCAL_SET_NZ(tmp);                       \
        LOCAL_SET_CARRY(LOCAL_SIGN());           \
        INC_PC(pc_inc);                          \
    } while (0)
AND
#define AND (value, clk_inc, pc_inc)
Value:
    do {                                         \
        uint8_t tmp = (uint8_t)(reg_a_read & (value)); \
        reg_a_write(tmp);                        \
        LOCAL_SET_NZ(tmp);                       \
        CLK_ADD(CLK, (clk_inc));                 \
        INC_PC(pc_inc);                          \
    } while (0)
ANE
#define ANE (value, pc_inc)
Value:
    do {                                                                            \
        uint8_t tmp = ((reg_a_read | ANE_MAGIC) & reg_x_read & ((uint8_t)(value))); \
        reg_a_write(tmp);                                                           \
        LOCAL_SET_NZ(tmp);                                                          \
        INC_PC(pc_inc);                                                             \
    } while (0)
ANE_MAGIC
#define ANE_MAGIC 0xef
ANE_RDY_MAGIC
#define ANE_RDY_MAGIC 0xee
ARR
#define ARR (value, pc_inc)
Value:
    do {                                                            \
        unsigned int tmp;                                           \
                                                                    \
        tmp = reg_a_read & (value);                                 \
        if (LOCAL_DECIMAL()) {                                      \
            int tmp_2 = tmp;                                        \
            tmp_2 |= (reg_p & P_CARRY) << 8;                        \
            tmp_2 >>= 1;                                            \
            LOCAL_SET_SIGN(LOCAL_CARRY());                          \
            LOCAL_SET_ZERO(!tmp_2);                                 \
            LOCAL_SET_OVERFLOW((tmp_2 ^ tmp) & 0x40);               \
            if (((tmp & 0xf) + (tmp & 0x1)) > 0x5) {                \
                tmp_2 = (tmp_2 & 0xf0) | ((tmp_2 + 0x6) & 0xf);     \
            }                                                       \
            if (((tmp & 0xf0) + (tmp & 0x10)) > 0x50) {             \
                tmp_2 = (tmp_2 & 0x0f) | ((tmp_2 + 0x60) & 0xf0);   \
                LOCAL_SET_CARRY(1);                                 \
            } else {                                                \
                LOCAL_SET_CARRY(0);                                 \
            }                                                       \
            reg_a_write(tmp_2);                                     \
        } else {                                                    \
            tmp |= (reg_p & P_CARRY) << 8;                          \
            tmp >>= 1;                                              \
            LOCAL_SET_NZ(tmp);                                      \
            LOCAL_SET_CARRY(tmp & 0x40);                            \
            LOCAL_SET_OVERFLOW((tmp & 0x40) ^ ((tmp & 0x20) << 1)); \
            reg_a_write(tmp);                                       \
        }                                                           \
        INC_PC(pc_inc);                                             \
    } while (0)
The fanciest opcode ever... ARR!
ASL
#define ASL (addr, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                  \
        unsigned int tmp_value, tmp_addr;                 \
                                                          \
        tmp_addr = (addr);                                \
        tmp_value = load_func(tmp_addr);                  \
        CLK_ADD(CLK, 1);                                  \
        CLK_ADD_DUMMY(CLK, 1);                            \
        dummy_func(tmp_addr, tmp_value);                  \
        LOCAL_SET_CARRY(tmp_value & 0x80);                \
        tmp_value = (tmp_value << 1) & 0xff;              \
        LOCAL_SET_NZ(tmp_value);                          \
        INC_PC(pc_inc);                                   \
        store_func(tmp_addr, tmp_value, 1);               \
    } while (0)
ASL_A
#define ASL_A ()
Value:
    do {                             \
        uint8_t tmp = reg_a_read;       \
        LOCAL_SET_CARRY(tmp & 0x80); \
        tmp <<= 1;                   \
        reg_a_write(tmp);            \
        LOCAL_SET_NZ(tmp);           \
        INC_PC(1);                   \
    } while (0)
ASR
#define ASR (value, pc_inc)
Value:
    do {                                         \
        unsigned int tmp = reg_a_read & (value); \
        LOCAL_SET_CARRY(tmp & 0x01);             \
        tmp >>= 1;                               \
        reg_a_write(tmp);                        \
        LOCAL_SET_NZ(tmp);                       \
        INC_PC(pc_inc);                          \
    } while (0)
BIT
#define BIT (value, pc_inc)
Value:
    do {                                     \
        unsigned int tmp;                    \
                                             \
        tmp = (value);                       \
        CLK_ADD(CLK, 1);                     \
        LOCAL_SET_SIGN(tmp & 0x80);          \
        LOCAL_SET_OVERFLOW(tmp & 0x40);      \
        LOCAL_SET_ZERO(!(tmp & reg_a_read)); \
        INC_PC(pc_inc);                      \
    } while (0)
BRANCH
#define BRANCH (cond, value)
Value:
    do {                                                                  \
        INC_PC(2);                                                        \
                                                                          \
        if (cond) {                                                       \
            unsigned int dest_addr = reg_pc + (signed char)(value);       \
                                                                          \
            FETCH_PARAM_DUMMY(reg_pc);                                    \
            CLK_ADD(CLK, CLK_BRANCH2);                                    \
            if ((reg_pc ^ dest_addr) & 0xff00) {                          \
                LOAD_DUMMY((reg_pc & 0xff00) | (dest_addr & 0xff));       \
                CLK_ADD(CLK, CLK_BRANCH2);                                \
            } else {                                                      \
                OPCODE_DELAYS_INTERRUPT();                                \
            }                                                             \
            JUMP(dest_addr & 0xffff);                                     \
        }                                                                 \
    } while (0)
BRK
#define BRK ()
Value:
    do {                                                                                          \
        uint16_t addr, handler_vector;                                                            \
        EXPORT_REGISTERS();                                                                       \
        INC_PC(2);                                                                                \
        LOCAL_SET_BREAK(1);                                                                       \
        PUSH(reg_pc >> 8);                                                                        \
        PUSH(reg_pc & 0xff);                                                                      \
        CLK_ADD(CLK, CLK_BRK - 3);                                                                \
        PUSH(LOCAL_STATUS());                                                                     \
        CLK_ADD(CLK, 1);                                                                          \
        CPU_DELAY_CLK  /* process alarms for cartridge freeze */                                  \
        PROCESS_ALARMS                                                                            \
        if ((CPU_INT_STATUS->global_pending_int & IK_NMI)                                         \
            && (CLK >= (CPU_INT_STATUS->nmi_clk + INTERRUPT_DELAY))) {                            \
            LOCAL_SET_INTERRUPT(1);                                                               \
            TRACE_NMI(CLK - CLK_BRK);                                                             \
            if (monitor_mask[CALLER] & (MI_STEP)) {                                               \
                monitor_check_icount_interrupt();                                                 \
            }                                                                                     \
            interrupt_ack_nmi(CPU_INT_STATUS);                                                    \
            handler_vector = 0xfffa;                                                              \
        } else if ((CPU_INT_STATUS->global_pending_int & (IK_IRQ | IK_IRQPEND))                   \
                 && !LOCAL_INTERRUPT() && (CLK >= (CPU_INT_STATUS->irq_clk + INTERRUPT_DELAY))) { \
            LOCAL_SET_INTERRUPT(1);                                                               \
            TRACE_IRQ(CLK - CLK_BRK);                                                             \
            if (monitor_mask[CALLER] & (MI_STEP)) {                                               \
                monitor_check_icount_interrupt();                                                 \
            }                                                                                     \
            interrupt_ack_irq(CPU_INT_STATUS);                                                    \
            handler_vector = 0xfffe;                                                              \
        } else {                                                                                  \
            TRACE_BRK();                                                                          \
            LOCAL_SET_INTERRUPT(1);                                                               \
            handler_vector = 0xfffe;                                                              \
        }                                                                                         \
        addr = LOAD_ADDR(handler_vector);                                                         \
        CHECK_PROFILE_INTERRUPT(addr, handler_vector);                                            \
        JUMP(addr);                                                                               \
        CLK_ADD(CLK, 2);                                                                          \
    } while (0)
CHECK_PROFILE_INTERRUPT
#define CHECK_PROFILE_INTERRUPT (dest_addr, handler)
Value:
do {                                                                   \
        profile_int(dest_addr, handler, reg_sp + 1, CLK - profiling_clock_start); \
} while (0)
CHECK_PROFILE_JSR
#define CHECK_PROFILE_JSR (dest_addr)
Value:
    do {                                 \
        profile_jsr(dest_addr, reg_pc, reg_sp); \
} while (0)
CHECK_PROFILE_RTI
#define CHECK_PROFILE_RTI ()
Value:
        do {                             \
            profile_rtx(reg_sp + 1); \
    } while (0)
CHECK_PROFILE_RTS
#define CHECK_PROFILE_RTS ()
Value:
    do {                         \
            profile_rtx(reg_sp); \
    } while (0)
CLC
#define CLC ()
Value:
    do {                    \
        INC_PC(1);          \
        LOCAL_SET_CARRY(0); \
    } while (0)
CLD
#define CLD ()
Value:
    do {                      \
        INC_PC(1);            \
        LOCAL_SET_DECIMAL(0); \
    } while (0)
CLI
#define CLI ()
Value:
    do {                          \
        INC_PC(1);                \
        if (LOCAL_INTERRUPT()) {  \
            OPCODE_ENABLES_IRQ(); \
        }                         \
        LOCAL_SET_INTERRUPT(0);   \
    } while (0)
CLK_ABS_I_STORE2
#define CLK_ABS_I_STORE2 2
CLK_ADD
#define CLK_ADD (clock, amount) ((clock) += (amount))
Backup for non-variable cycle CPUs.
CLK_ADD_DUMMY
#define CLK_ADD_DUMMY (clock, amount) CLK_ADD(clock, amount)
CLK_BRANCH2
#define CLK_BRANCH2 1
CLK_BRK
#define CLK_BRK 5
CLK_IND_Y_W
#define CLK_IND_Y_W 2
CLK_INT_CYCLE
#define CLK_INT_CYCLE 1
CLK_JSR_INT_CYCLE
#define CLK_JSR_INT_CYCLE 1
CLK_NOOP_ZERO_X
#define CLK_NOOP_ZERO_X 2
CLK_RTI
#define CLK_RTI 4
CLK_RTS
#define CLK_RTS 3
Opcode execution time may vary on the C64DTV.
CLK_STACK_PULL
#define CLK_STACK_PULL 2
CLK_STACK_PUSH
#define CLK_STACK_PUSH 1
CLK_ZERO_I2
#define CLK_ZERO_I2 2
CLK_ZERO_I_STORE
#define CLK_ZERO_I_STORE 2
CLV
#define CLV ()
Value:
    do {                       \
        INC_PC(1);             \
        LOCAL_SET_OVERFLOW(0); \
    } while (0)
CMP
#define CMP (value, clk_inc, pc_inc)
Value:
    do {                              \
        unsigned int tmp;             \
                                      \
        tmp = reg_a_read - (value);   \
        LOCAL_SET_CARRY(tmp < 0x100); \
        LOCAL_SET_NZ(tmp & 0xff);     \
        CLK_ADD(CLK, (clk_inc));      \
        INC_PC(pc_inc);               \
    } while (0)
CPU_DELAY_CLK
#define CPU_DELAY_CLK
Hook for additional delay.
CPU_REFRESH_CLK
#define CPU_REFRESH_CLK
CPU_STR
#define CPU_STR "Main CPU"
This file is included by CPU definition files.
CPX
#define CPX (value, clk_inc, pc_inc)
Value:
    do {                              \
        unsigned int tmp;             \
                                      \
        tmp = reg_x_read - (value);   \
        LOCAL_SET_CARRY(tmp < 0x100); \
        LOCAL_SET_NZ(tmp & 0xff);     \
        CLK_ADD(CLK, (clk_inc));      \
        INC_PC(pc_inc);               \
    } while (0)
CPY
#define CPY (value, clk_inc, pc_inc)
Value:
    do {                              \
        unsigned int tmp;             \
                                      \
        tmp = reg_y_read - (value);   \
        LOCAL_SET_CARRY(tmp < 0x100); \
        LOCAL_SET_NZ(tmp & 0xff);     \
        CLK_ADD(CLK, (clk_inc));      \
        INC_PC(pc_inc);               \
    } while (0)
DCP
#define DCP (addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                             \
        unsigned int tmp, tmp_addr;                                  \
                                                                     \
        tmp_addr = (addr);                                           \
        CLK_ADD(CLK, (clk_inc1));                                    \
        tmp = load_func(tmp_addr);                                   \
        CLK_ADD(CLK, 1);                                             \
        CLK_ADD_DUMMY(CLK, 1);                                       \
        dummy_func(tmp_addr, tmp);                                   \
        tmp = (tmp - 1) & 0xff;                                      \
        LOCAL_SET_CARRY(reg_a_read >= tmp);                          \
        LOCAL_SET_NZ((reg_a_read - tmp));                            \
        INC_PC(pc_inc);                                              \
        store_func(tmp_addr, tmp, 1);                                \
    } while (0)
DCP_IND_Y
#define DCP_IND_Y (addr)
Value:
    do {                                                                    \
        unsigned int tmp;                                                   \
        unsigned int tmp_addr = LOAD_ZERO_ADDR(addr);                       \
                                                                            \
        CLK_ADD(CLK, 2);                                                    \
        LOAD_DUMMY((tmp_addr & 0xff00) | ((tmp_addr + reg_y_read) & 0xff)); \
        CLK_ADD_DUMMY(CLK, 1);                                              \
        tmp_addr += reg_y_read;                                             \
        tmp = LOAD(tmp_addr);                                               \
        CLK_ADD(CLK, 1);                                                    \
        CLK_ADD_DUMMY(CLK, 1);                                              \
        DUMMY_STORE_ABS_RMW(tmp_addr, tmp);                                 \
        tmp = (tmp - 1) & 0xff;                                             \
        LOCAL_SET_CARRY(reg_a_read >= tmp);                                 \
        LOCAL_SET_NZ((reg_a_read - tmp));                                   \
        INC_PC(2);                                                          \
        STORE_ABS(tmp_addr, tmp, 1);                                        \
    } while (0)
DEC
#define DEC (addr, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                  \
        unsigned int tmp, tmp_addr;                       \
                                                          \
        tmp_addr = (addr);                                \
        tmp = load_func(tmp_addr);                        \
        CLK_ADD(CLK, 1);                                  \
        CLK_ADD_DUMMY(CLK, 1);                            \
        dummy_func(tmp_addr, tmp);                        \
        tmp = (tmp - 1) & 0xff;                           \
        LOCAL_SET_NZ(tmp);                                \
        INC_PC(pc_inc);                                   \
        store_func(tmp_addr, tmp, 1);                     \
    } while (0)
DEX
#define DEX ()
Value:
    do {                             \
        reg_x_write(reg_x_read - 1); \
        LOCAL_SET_NZ(reg_x_read);    \
        INC_PC(1);                   \
    } while (0)
DEY
#define DEY ()
Value:
    do {                             \
        reg_y_write(reg_y_read - 1); \
        LOCAL_SET_NZ(reg_y_read);    \
        INC_PC(1);                   \
    } while (0)
DO_INTERRUPT
#define DO_INTERRUPT (int_kind)
Value:
    do {                                                                                       \
        uint8_t ik = (int_kind);                                                               \
        uint16_t addr, handler_vector;                                                         \
                                                                                               \
        if (ik & (IK_IRQ | IK_IRQPEND | IK_NMI)) {                                             \
            if (((ik & IK_NMI)                                                                 \
                 && interrupt_check_nmi_delay(CPU_INT_STATUS, CLK))                            \
                || ((ik & (IK_IRQ | IK_IRQPEND)) && (!LOCAL_INTERRUPT()                        \
                                                     || OPINFO_DISABLES_IRQ(LAST_OPCODE_INFO)) \
                    && interrupt_check_irq_delay(CPU_INT_STATUS, CLK))) {                      \
                if (monitor_mask[CALLER] & (MI_STEP)) {                                        \
                    monitor_check_icount_interrupt();                                          \
                }                                                                              \
                if (NMI_CYCLES == 7) {                                                         \
                    FETCH_PARAM_DUMMY(reg_pc);   /* dummy reads */                             \
                    CLK_ADD(CLK, 1);                                                           \
                    FETCH_PARAM_DUMMY(reg_pc);                                                 \
                    CLK_ADD(CLK, 1);                                                           \
                }                                                                              \
                LOCAL_SET_BREAK(0);                                                            \
                PUSH(reg_pc >> 8);                                                             \
                PUSH(reg_pc & 0xff);                                                           \
                CLK_ADD(CLK, 2);                                                               \
                PUSH(LOCAL_STATUS());                                                          \
                CLK_ADD(CLK, 1);                                                               \
                LOCAL_SET_INTERRUPT(1);                                                        \
                CPU_DELAY_CLK; /* process alarms for cartridge freeze */                       \
                PROCESS_ALARMS;                                                                \
                if ((CPU_INT_STATUS->global_pending_int & IK_NMI)                              \
                    && (CLK >= (CPU_INT_STATUS->nmi_clk + INTERRUPT_DELAY))) {                 \
                    TRACE_NMI(CLK - NMI_CYCLES + 2);                                           \
                    interrupt_ack_nmi(CPU_INT_STATUS);                                         \
                    handler_vector = 0xfffa;                                                   \
                } else {                                                                       \
                    TRACE_IRQ(CLK - IRQ_CYCLES + 2);                                           \
                    interrupt_ack_irq(CPU_INT_STATUS);                                         \
                    handler_vector = 0xfffe;                                                   \
                }                                                                              \
                addr = LOAD_ADDR(handler_vector);                                              \
                CHECK_PROFILE_INTERRUPT(addr, handler_vector);                                 \
                JUMP(addr);                                                                    \
                SET_LAST_OPCODE(0);                                                            \
                CLK_ADD(CLK, 2);                                                               \
            }                                                                                  \
        }                                                                                      \
        if (ik & (IK_TRAP | IK_RESET)) {                                                       \
            if (ik & IK_TRAP) {                                                                \
                EXPORT_REGISTERS();                                                            \
                interrupt_do_trap(CPU_INT_STATUS, (uint16_t)reg_pc);                           \
                IMPORT_REGISTERS();                                                            \
                if (CPU_INT_STATUS->global_pending_int & IK_RESET) {                           \
                    ik |= IK_RESET;                                                            \
                }                                                                              \
            }                                                                                  \
            if (ik & IK_RESET) {                                                               \
                cpu_reset();                                                                   \
                interrupt_ack_reset(CPU_INT_STATUS);                                           \
                bank_start = bank_limit = 0; /* prevent caching */                             \
                LOCAL_SET_INTERRUPT(1);                                                        \
                cpu_is_jammed = 0;                                                             \
                DMA_ON_RESET;                                                                  \
                addr = LOAD_ADDR(0xfffc);                                                      \
                CHECK_PROFILE_INTERRUPT(addr, 0xfffc);                                         \
                JUMP(addr);                                                                    \
            }                                                                                  \
        }                                                                                      \
        if (ik & (IK_MONITOR | IK_DMA)) {                                                      \
            if (ik & IK_MONITOR) {                                                             \
                if (monitor_mask[CALLER] & (MI_STEP)) {                                        \
                    EXPORT_REGISTERS();                                                        \
                    monitor_check_icount((uint16_t)reg_pc);                                    \
                    IMPORT_REGISTERS();                                                        \
                }                                                                              \
                if (monitor_mask[CALLER] & (MI_BREAK)) {                                       \
                    EXPORT_REGISTERS();                                                        \
                    if (monitor_check_breakpoints(CALLER, (uint16_t)reg_pc)) {                 \
                        monitor_startup(CALLER);                                               \
                    }                                                                          \
                    IMPORT_REGISTERS();                                                        \
                }                                                                              \
                if (monitor_mask[CALLER] & (MI_WATCH)) {                                       \
                    EXPORT_REGISTERS();                                                        \
                    monitor_check_watchpoints(LAST_OPCODE_ADDR, (uint16_t)reg_pc);             \
                    IMPORT_REGISTERS();                                                        \
                }                                                                              \
            }                                                                                  \
            if (ik & IK_DMA) {                                                                 \
                EXPORT_REGISTERS();                                                            \
                DMA_FUNC;                                                                      \
                interrupt_ack_dma(CPU_INT_STATUS);                                             \
                IMPORT_REGISTERS();                                                            \
            }                                                                                  \
        }                                                                                      \
    } while (0)
Todo:
FIXME: LOCAL_STATUS() should check byte ready first.
DUMMY_STORE_ABS_RMW
#define DUMMY_STORE_ABS_RMW (addr, value)
Value:
    do {                                 \
        STORE_DUMMY(addr, value);        \
    } while (0)
DUMMY_STORE_ABS_X_RMW
#define DUMMY_STORE_ABS_X_RMW (addr, value)
Value:
    do {                                           \
        STORE_DUMMY((addr) + reg_x_read, (value)); \
    } while (0)
DUMMY_STORE_ABS_Y_RMW
#define DUMMY_STORE_ABS_Y_RMW (addr, value)
Value:
    do {                                           \
        STORE_DUMMY((addr) + reg_y_read, (value)); \
    } while (0)
EOR
#define EOR (value, clk_inc, pc_inc)
Value:
    do {                                         \
        uint8_t tmp = (uint8_t)(reg_a_read ^ (value)); \
        reg_a_write(tmp);                        \
        LOCAL_SET_NZ(tmp);                       \
        CLK_ADD(CLK, (clk_inc));                 \
        INC_PC(pc_inc);                          \
    } while (0)
EXPORT_REGISTERS
#define EXPORT_REGISTERS ()
Value:
    do {                            \
        GLOBAL_REGS.pc = reg_pc;    \
        GLOBAL_REGS.a = reg_a_read; \
        GLOBAL_REGS.x = reg_x_read; \
        GLOBAL_REGS.y = reg_y_read; \
        GLOBAL_REGS.sp = reg_sp;    \
        GLOBAL_REGS.p = reg_p;      \
        GLOBAL_REGS.n = flag_n;     \
        GLOBAL_REGS.z = flag_z;     \
    } while (0)
Export the local version of the registers.
FETCH_OPCODE
#define FETCH_OPCODE (o)
Value:
    do {                                                                                  \
        if (((int)reg_pc) < bank_limit) {                                                 \
            (o).ins = *(bank_base + reg_pc);                                              \
            (o).op.op16 = (*(bank_base + reg_pc + 1) | (*(bank_base + reg_pc + 2) << 8)); \
            CLK_ADD(CLK, 2);                                                              \
            if (fetch_tab[(o).ins]) {                                                     \
                CLK_ADD(CLK, 1);                                                          \
            }                                                                             \
        } else {                                                                          \
            (o).ins = LOAD(reg_pc);                                                       \
            CLK_ADD(CLK, 1);                                                              \
            (o).op.op16 = LOAD(reg_pc + 1);                                               \
            CLK_ADD(CLK, 1);                                                              \
            if (fetch_tab[(o).ins]) {                                                     \
                (o).op.op16 |= (LOAD(reg_pc + 2) << 8);                                   \
                CLK_ADD(CLK, 1);                                                          \
            }                                                                             \
        }                                                                                 \
    } while (0)
FETCH_PARAM
#define FETCH_PARAM (addr) (LOAD(addr))
Todo:
FIXME: we need to check if this shortcut will not make checkpoints not trigger in certain cases.
FETCH_PARAM_DUMMY
#define FETCH_PARAM_DUMMY (addr) (LOAD_DUMMY(addr))
IMPORT_REGISTERS
#define IMPORT_REGISTERS ()
Value:
    do {                                                   \
        reg_a_write(GLOBAL_REGS.a); /*TODO*/               \
        reg_x_write(GLOBAL_REGS.x);                        \
        reg_y_write(GLOBAL_REGS.y);                        \
        reg_sp = GLOBAL_REGS.sp;                           \
        reg_p = GLOBAL_REGS.p;                             \
        flag_n = GLOBAL_REGS.n;                            \
        flag_z = GLOBAL_REGS.z;                            \
        bank_start = bank_limit = 0; /* prevent caching */ \
        JUMP(GLOBAL_REGS.pc);                              \
    } while (0)
Import the public version of the registers.
INC
#define INC (addr, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                              \
        unsigned int tmp, tmp_addr;                                   \
                                                                      \
        tmp_addr = (addr);                                            \
        tmp = load_func(tmp_addr);                                    \
        CLK_ADD(CLK, 1);                                              \
        CLK_ADD_DUMMY(CLK, 1);                                        \
        dummy_func(tmp_addr, tmp);                                    \
        tmp = (tmp + 1) & 0xff;                                       \
        LOCAL_SET_NZ(tmp);                                            \
        INC_PC(pc_inc);                                               \
        store_func(tmp_addr, tmp, 1);                                 \
    } while (0)
INC_PC
#define INC_PC (value) (reg_pc += (value))
INX
#define INX ()
Value:
    do {                             \
        reg_x_write(reg_x_read + 1); \
        LOCAL_SET_NZ(reg_x_read);    \
        INC_PC(1);                   \
    } while (0)
INY
#define INY ()
Value:
    do {                             \
        reg_y_write(reg_y_read + 1); \
        LOCAL_SET_NZ(reg_y_read);    \
        INC_PC(1);                   \
    } while (0)
IRQ_CYCLES
#define IRQ_CYCLES 7
ISB
#define ISB (addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                             \
        uint8_t my_src;                                              \
        int my_addr = (addr);                                        \
                                                                     \
        CLK_ADD(CLK, (clk_inc1));                                    \
        my_src = load_func(my_addr);                                 \
        CLK_ADD(CLK, 1);                                             \
        CLK_ADD_DUMMY(CLK, 1);                                       \
        dummy_func(my_addr, my_src);                                 \
        my_src = (my_src + 1) & 0xff;                                \
        SBC(my_src, 0, 0);                                           \
        INC_PC(pc_inc);                                              \
        store_func(my_addr, my_src, 1);                              \
    } while (0)
ISB_IND_Y
#define ISB_IND_Y (addr)
Value:
    do {                                                                  \
        uint8_t my_src;                                                   \
        int my_addr = LOAD_ZERO_ADDR(addr);                               \
                                                                          \
        CLK_ADD(CLK, 2);                                                  \
        LOAD_DUMMY((my_addr & 0xff00) | ((my_addr + reg_y_read) & 0xff)); \
        CLK_ADD_DUMMY(CLK, 1);                                            \
        my_addr += reg_y_read;                                            \
        my_src = LOAD(my_addr);                                           \
        CLK_ADD(CLK, 1);                                                  \
        CLK_ADD_DUMMY(CLK, 1);                                            \
        DUMMY_STORE_ABS_RMW(my_addr, my_src);                             \
        my_src = (my_src + 1) & 0xff;                                     \
        SBC(my_src, 0, 0);                                                \
        INC_PC(2);                                                        \
        STORE_ABS(my_addr, my_src, 1);                                    \
    } while (0)
JAM_02
#define JAM_02 ()
Value:
    do {                                                                                 \
        uint32_t trap_result;                                                            \
        EXPORT_REGISTERS();                                                              \
        if (!ROM_TRAP_ALLOWED() || (trap_result = ROM_TRAP_HANDLER()) == (uint32_t)-1) { \
            cpu_is_jammed = 1;                                                           \
            REWIND_FETCH_OPCODE(CLK);                                                    \
            JAM();                                                                       \
        } else {                                                                         \
            if (trap_result) {                                                           \
                REWIND_FETCH_OPCODE(CLK);                                                \
                SET_OPCODE(trap_result);                                                 \
                IMPORT_REGISTERS();                                                      \
                goto trap_skipped;                                                       \
            } else {                                                                     \
                IMPORT_REGISTERS();                                                      \
            }                                                                            \
        }                                                                                \
    } while (0)
JMP
#define JMP (addr)
Value:
    do {            \
        JUMP(addr); \
    } while (0)
JMP_IND
#define JMP_IND ()
Value:
    do {                                                             \
        uint16_t dest_addr;                                          \
        dest_addr = LOAD(p2);                                        \
        CLK_ADD(CLK, 1);                                             \
        dest_addr |= (LOAD((p2 & 0xff00) | ((p2 + 1) & 0xff)) << 8); \
        CLK_ADD(CLK, 1);                                             \
        JUMP(dest_addr);                                             \
    } while (0)
JSR
#define JSR ()
Value:
    do {                                              \
        uint8_t addr_msb;                             \
        unsigned int tmp_addr;                        \
                                                      \
        LOAD_DUMMY(0x100 + reg_sp);                   \
        CLK_ADD(CLK, 1);                              \
        INC_PC(2);                                    \
        CLK_ADD(CLK, 2);                              \
        PUSH(((reg_pc) >> 8) & 0xff);                 \
        PUSH((reg_pc) & 0xff);                        \
        addr_msb = LOAD(reg_pc);                      \
        JSR_FIXUP_MSB(addr_msb);                      \
        tmp_addr = (p1 | (addr_msb << 8));            \
        CLK_ADD(CLK, CLK_JSR_INT_CYCLE);              \
        CHECK_PROFILE_JSR(tmp_addr);                  \
        JUMP(tmp_addr);                               \
    } while (0)
JSR_FIXUP_MSB
#define JSR_FIXUP_MSB (x)
HACK: fix JSR MSB in monitor CPU history.
LAS
#define LAS (value, clk_inc, pc_inc)
Value:
    do {                            \
        reg_sp = reg_sp & (value);  \
        reg_x_write(reg_sp);        \
        reg_a_write(reg_sp);        \
        LOCAL_SET_NZ(reg_sp);       \
        CLK_ADD(CLK, (clk_inc));    \
        INC_PC(pc_inc);             \
    } while (0)
LAX
#define LAX (value, clk_inc, pc_inc)
Value:
    do {                            \
        uint8_t tmp = (value);         \
        reg_x_write(tmp);           \
        reg_a_write(tmp);           \
        LOCAL_SET_NZ(tmp);          \
        CLK_ADD(CLK, (clk_inc));    \
        INC_PC(pc_inc);             \
    } while (0)
LDA
#define LDA (value, clk_inc, pc_inc)
Value:
    do {                            \
        uint8_t tmp = (uint8_t)(value);   \
        reg_a_write(tmp);           \
        CLK_ADD(CLK, (clk_inc));    \
        LOCAL_SET_NZ(tmp);          \
        INC_PC(pc_inc);             \
    } while (0)
LDX
#define LDX (value, clk_inc, pc_inc)
Value:
    do {                            \
        reg_x_write((uint8_t)(value)); \
        LOCAL_SET_NZ(reg_x_read);   \
        CLK_ADD(CLK, (clk_inc));    \
        INC_PC(pc_inc);             \
    } while (0)
LDY
#define LDY (value, clk_inc, pc_inc)
Value:
    do {                            \
        reg_y_write((uint8_t)(value)); \
        LOCAL_SET_NZ(reg_y_read);   \
        CLK_ADD(CLK, (clk_inc));    \
        INC_PC(pc_inc);             \
    } while (0)
LOAD_ABS
#define LOAD_ABS (addr) LOAD(addr)
LOAD_ABS_X
#define LOAD_ABS_X (addr)
Value:
    ((((addr) & 0xff) + reg_x_read) > 0xff                              \
     ? (LOAD_DUMMY(((addr) & 0xff00) | (((addr) + reg_x_read) & 0xff)), \
        CLK_ADD(CLK, CLK_INT_CYCLE),                                    \
        LOAD((addr) + reg_x_read))                                      \
     : LOAD((addr) + reg_x_read))
LOAD_ABS_X_RMW
#define LOAD_ABS_X_RMW (addr)
Value:
    (LOAD_DUMMY(((addr) & 0xff00) | (((addr) + reg_x_read) & 0xff)), \
     CLK_ADD(CLK, CLK_INT_CYCLE),                                    \
     LOAD((addr) + reg_x_read))
LOAD_ABS_Y
#define LOAD_ABS_Y (addr)
Value:
    ((((addr) & 0xff) + reg_y_read) > 0xff                              \
     ? (LOAD_DUMMY(((addr) & 0xff00) | (((addr) + reg_y_read) & 0xff)), \
        CLK_ADD(CLK, CLK_INT_CYCLE),                                    \
        LOAD((addr) + reg_y_read))                                      \
     : LOAD((addr) + reg_y_read))
LOAD_ABS_Y_RMW
#define LOAD_ABS_Y_RMW (addr)
Value:
    (LOAD_DUMMY(((addr) & 0xff00) | (((addr) + reg_y_read) & 0xff)), \
     CLK_ADD(CLK, CLK_INT_CYCLE),                                    \
     LOAD((addr) + reg_y_read))
LOAD_IND
#define LOAD_IND (a) LOAD(a)
Backup for non-6509 CPUs.
LOAD_IND_X
#define LOAD_IND_X (addr)
Value:
    (CLK_ADD(CLK, 3),                                           \
    LOAD_ZERO_DUMMY(addr),                                      \
    tmpa = LOAD_ZERO((addr + reg_x_read) & 0xff),               \
    tmpa |= (LOAD_ZERO(((addr + reg_x_read) + 1) & 0xff) << 8), \
    LOAD(tmpa))
LOAD_IND_Y
#define LOAD_IND_Y (addr)
Value:
    (CLK_ADD(CLK, 2),                                               \
    tmpa = LOAD_ZERO(addr),                                         \
    tmpa |= (LOAD_ZERO((addr + 1)) << 8),                           \
    ((((tmpa & 0xff) + reg_y_read) > 0xff) ?                        \
        (CLK_ADD(CLK, CLK_INT_CYCLE),                               \
        LOAD_DUMMY((tmpa & 0xff00) | ((tmpa + reg_y_read) & 0xff)), \
        LOAD(tmpa + reg_y_read)) :                                  \
        LOAD(tmpa + reg_y_read)))
LOAD_IND_Y_BANK
#define LOAD_IND_Y_BANK (addr)
Value:
    (CLK_ADD(CLK, 2),                                                   \
    tmpa = LOAD_ZERO(addr),                                             \
    tmpa |= (LOAD_ZERO(addr + 1) << 8),                                 \
    ((((tmpa & 0xff) + reg_y_read) > 0xff) ?                            \
        (CLK_ADD(CLK, CLK_INT_CYCLE),                                   \
        LOAD_DUMMY((tmpa & 0xff00) | ((tmpa + reg_y_read) & 0xff)),     \
        LOAD_IND(tmpa + reg_y_read)) :                                  \
        LOAD_IND(tmpa + reg_y_read)))
LOAD_ZERO_X
#define LOAD_ZERO_X (addr)
Value:
    (LOAD_ZERO_DUMMY(addr),             \
    LOAD_ZERO(addr + reg_x_read))
LOAD_ZERO_Y
#define LOAD_ZERO_Y (addr)
Value:
    (LOAD_ZERO_DUMMY(addr),             \
    LOAD_ZERO(addr + reg_y_read))
LOCAL_BREAK
#define LOCAL_BREAK () (reg_p & P_BREAK)
LOCAL_CARRY
#define LOCAL_CARRY () (reg_p & P_CARRY)
LOCAL_DECIMAL
#define LOCAL_DECIMAL () (reg_p & P_DECIMAL)
LOCAL_INTERRUPT
#define LOCAL_INTERRUPT () (reg_p & P_INTERRUPT)
LOCAL_OVERFLOW
#define LOCAL_OVERFLOW () (reg_p & P_OVERFLOW)
LOCAL_SET_BREAK
#define LOCAL_SET_BREAK (val)
Value:
    do {                       \
        if (val) {             \
            reg_p |= P_BREAK;  \
        } else {               \
            reg_p &= ~P_BREAK; \
        }                      \
    } while (0)
LOCAL_SET_CARRY
#define LOCAL_SET_CARRY (val)
Value:
    do {                       \
        if (val) {             \
            reg_p |= P_CARRY;  \
        } else {               \
            reg_p &= ~P_CARRY; \
        }                      \
    } while (0)
LOCAL_SET_DECIMAL
#define LOCAL_SET_DECIMAL (val)
Value:
    do {                         \
        if (val) {               \
            reg_p |= P_DECIMAL;  \
        } else {                 \
            reg_p &= ~P_DECIMAL; \
        }                        \
    } while (0)
LOCAL_SET_INTERRUPT
#define LOCAL_SET_INTERRUPT (val)
Value:
    do {                           \
        if (val) {                 \
            reg_p |= P_INTERRUPT;  \
        } else {                   \
            reg_p &= ~P_INTERRUPT; \
        }                          \
    } while (0)
LOCAL_SET_NZ
#define LOCAL_SET_NZ (val) (flag_z = flag_n = (val))
LOCAL_SET_OVERFLOW
#define LOCAL_SET_OVERFLOW (val)
Value:
    do {                          \
        if (val) {                \
            reg_p |= P_OVERFLOW;  \
        } else {                  \
            reg_p &= ~P_OVERFLOW; \
        }                         \
    } while (0)
LOCAL_SET_SIGN
#define LOCAL_SET_SIGN (val) (flag_n = (val) ? 0x80 : 0)
LOCAL_SET_STATUS
#define LOCAL_SET_STATUS (val)
Value:
                                  (reg_p = ((val) & ~(P_ZERO | P_SIGN)), \
                                  LOCAL_SET_ZERO((val) & P_ZERO),       \
                                  flag_n = (val))
LOCAL_SET_ZERO
#define LOCAL_SET_ZERO (val) (flag_z = !(val))
LOCAL_SIGN
#define LOCAL_SIGN () (flag_n & 0x80)
LOCAL_STATUS
#define LOCAL_STATUS ()
Value:
                                  (reg_p | (flag_n & 0x80) | P_UNUSED    \
                                  | (LOCAL_ZERO() ? P_ZERO : 0))
LOCAL_ZERO
#define LOCAL_ZERO () (!flag_z)
LSR
#define LSR (addr, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                  \
        unsigned int tmp, tmp_addr;                       \
                                                          \
        tmp_addr = (addr);                                \
        tmp = load_func(tmp_addr);                        \
        CLK_ADD(CLK, 1);                                  \
        CLK_ADD_DUMMY(CLK, 1);                            \
        dummy_func(tmp_addr, tmp);                        \
        LOCAL_SET_CARRY(tmp & 0x01);                      \
        tmp >>= 1;                                        \
        LOCAL_SET_NZ(tmp);                                \
        INC_PC(pc_inc);                                   \
        store_func(tmp_addr, tmp, 1);                     \
    } while (0)
LSR_A
#define LSR_A ()
Value:
    do {                               \
        unsigned int tmp = reg_a_read; \
        LOCAL_SET_CARRY(tmp & 0x01);   \
        tmp >>= 1;                     \
        reg_a_write(tmp);              \
        LOCAL_SET_NZ(tmp);             \
        INC_PC(1);                     \
    } while (0)
LXA
#define LXA (value, pc_inc)
Value:
    do {                                                               \
        uint8_t tmp = ((reg_a_read | LXA_MAGIC) & ((uint8_t)(value))); \
        reg_x_write(tmp);                                              \
        reg_a_write(tmp);                                              \
        LOCAL_SET_NZ(tmp);                                             \
        INC_PC(pc_inc);                                                \
    } while (0)
LXA_MAGIC
#define LXA_MAGIC 0xee
needs to be 0xee for wizball
LXA_RDY_MAGIC
#define LXA_RDY_MAGIC 0xee
NMI_CYCLES
#define NMI_CYCLES 7
NOOP
#define NOOP (clk_inc, pc_inc) (CLK_ADD(CLK, (clk_inc)), INC_PC(pc_inc))
NOOP_ABS
#define NOOP_ABS ()
Value:
    do {                 \
        LOAD(p2);        \
        CLK_ADD(CLK, 1); \
        INC_PC(3);       \
    } while (0)
NOOP_ABS_X
#define NOOP_ABS_X ()
Value:
    do {                 \
        NOOP_LOAD_ABS_X(p2);  \
        CLK_ADD(CLK, 1); \
        INC_PC(3);       \
    } while (0)
NOOP_IMM
#define NOOP_IMM (pc_inc) INC_PC(pc_inc)
NOOP_LOAD_ABS_X
#define NOOP_LOAD_ABS_X (addr)
Value:
    ((((addr) & 0xff) + reg_x_read) > 0xff                              \
     ? (LOAD_DUMMY(((addr) & 0xff00) | (((addr) + reg_x_read) & 0xff)), \
        CLK_ADD(CLK, CLK_INT_CYCLE),                                    \
        LOAD_DUMMY((addr) + reg_x_read))                                \
     : LOAD_DUMMY((addr) + reg_x_read))
NOOP_LOAD_ZERO_X
#define NOOP_LOAD_ZERO_X (addr)
Value:
    (LOAD_ZERO_DUMMY(addr),             \
    LOAD_ZERO_DUMMY(addr + reg_x_read))
NOP
#define NOP () NOOP_IMM(1)
OPCODE_DELAYS_INTERRUPT
#define OPCODE_DELAYS_INTERRUPT ()
OPCODE_DISABLES_IRQ
#define OPCODE_DISABLES_IRQ ()
OPCODE_ENABLES_IRQ
#define OPCODE_ENABLES_IRQ ()
opcode_t
#define opcode_t
Value:
    struct {             \
        uint8_t ins;        \
        union {          \
            uint8_t op8[2]; \
            uint16_t op16;   \
        } op;            \
    }
ORA
#define ORA (value, clk_inc, pc_inc)
Value:
    do {                                         \
        uint8_t tmp = (uint8_t)(reg_a_read | (value)); \
        reg_a_write(tmp);                        \
        LOCAL_SET_NZ(tmp);                       \
        CLK_ADD(CLK, (clk_inc));                 \
        INC_PC(pc_inc);                          \
    } while (0)
p0
#define p0 (opcode.ins)
p1
#define p1 (opcode.op.op8[0])
p2
#define p2 (opcode.op.op16)
PHA
#define PHA ()
Value:
    do {                              \
        CLK_ADD(CLK, CLK_STACK_PUSH); \
        PUSH(reg_a_read);             \
        INC_PC(1);                    \
    } while (0)
PHP
#define PHP ()
Value:
    do {                                \
        CLK_ADD(CLK, CLK_STACK_PUSH);   \
        PUSH(LOCAL_STATUS() | P_BREAK); \
        INC_PC(1);                      \
    } while (0)
PLA
#define PLA ()
Value:
    do {                              \
        uint8_t tmp;                  \
        CLK_ADD(CLK, CLK_STACK_PULL); \
        LOAD_DUMMY(0x100 + reg_sp);   \
        tmp = PULL();                 \
        reg_a_write(tmp);             \
        LOCAL_SET_NZ(tmp);            \
        INC_PC(1);                    \
    } while (0)
PLP
#define PLP ()
Value:
    do {                                                      \
        uint8_t s;                                            \
        LOAD_DUMMY(0x100 + reg_sp);                           \
        s = PULL();                                           \
                                                              \
        if (!(s & P_INTERRUPT) && LOCAL_INTERRUPT()) {        \
            OPCODE_ENABLES_IRQ();                             \
        } else if ((s & P_INTERRUPT) && !LOCAL_INTERRUPT()) { \
            OPCODE_DISABLES_IRQ();                            \
        }                                                     \
        CLK_ADD(CLK, CLK_STACK_PULL);                         \
        LOCAL_SET_STATUS(s);                                  \
        INC_PC(1);                                            \
    } while (0)
Todo:
FIXME: Rotate disk before executing LOCAL_SET_STATUS().
PROCESS_ALARMS
#define PROCESS_ALARMS
Value:
    while (CLK >= alarm_context_next_pending_clk(ALARM_CONTEXT)) { \
        alarm_context_dispatch(ALARM_CONTEXT, CLK);                \
        CPU_DELAY_CLK                                              \
    }
PULL
#define PULL () (++reg_sp, LOAD(0x100 + reg_sp))
PUSH
#define PUSH (val) { STORE(0x100 + reg_sp, (val)); reg_sp--; }
Stack operations.
reg_a_read
#define reg_a_read reg_a
reg_a_write
#define reg_a_write (c) reg_a = (c)
The C64DTV can use different shadow registers for accu read/write.
For standard 6510, this is not the case.
reg_x_read
#define reg_x_read reg_x
reg_x_write
#define reg_x_write (c) reg_x = (c)
reg_y_read
#define reg_y_read reg_y
reg_y_write
#define reg_y_write (c) reg_y = (c)
RESET_CYCLES
#define RESET_CYCLES 6
REWIND_FETCH_OPCODE
#define REWIND_FETCH_OPCODE (clock) ((clock) -= 2)
RLA
#define RLA (addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                             \
        unsigned int tmp, tmp2, tmp_addr;                            \
                                                                     \
        tmp_addr = (addr);                                           \
        CLK_ADD(CLK, (clk_inc1));                                    \
        tmp = load_func(tmp_addr);                                   \
        CLK_ADD(CLK, 1);                                             \
        CLK_ADD_DUMMY(CLK, 1);                                       \
        dummy_func(tmp_addr, tmp);                                   \
        tmp = ((tmp << 1) | (reg_p & P_CARRY));                      \
        LOCAL_SET_CARRY(tmp & 0x100);                                \
        tmp2 = reg_a_read & tmp;                                     \
        reg_a_write(tmp2);                                           \
        LOCAL_SET_NZ(tmp2);                                          \
        INC_PC(pc_inc);                                              \
        store_func(tmp_addr, tmp, 1);                                \
    } while (0)
RLA_IND_Y
#define RLA_IND_Y (addr)
Value:
    do {                                                                    \
        unsigned int tmp, tmp2;                                             \
        unsigned int tmp_addr = LOAD_ZERO_ADDR(addr);                       \
                                                                            \
        CLK_ADD(CLK, 2);                                                    \
        LOAD_DUMMY((tmp_addr & 0xff00) | ((tmp_addr + reg_y_read) & 0xff)); \
        CLK_ADD_DUMMY(CLK, 1);                                              \
        tmp_addr += reg_y_read;                                             \
        tmp = LOAD(tmp_addr);                                               \
        CLK_ADD(CLK, 1);                                                    \
        CLK_ADD_DUMMY(CLK, 1);                                              \
        DUMMY_STORE_ABS_RMW(tmp_addr, tmp);                                 \
        tmp = ((tmp << 1) | (reg_p & P_CARRY));                             \
        LOCAL_SET_CARRY(tmp & 0x100);                                       \
        tmp2 = reg_a_read & tmp;                                            \
        reg_a_write(tmp2);                                                  \
        LOCAL_SET_NZ(tmp2);                                                 \
        INC_PC(2);                                                          \
        STORE_ABS(tmp_addr, tmp, 1);                                        \
    } while (0)
ROL
#define ROL (addr, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                  \
        unsigned int tmp, tmp_addr;                       \
                                                          \
        tmp_addr = (addr);                                \
        tmp = load_func(tmp_addr);                        \
        CLK_ADD(CLK, 1);                                  \
        CLK_ADD_DUMMY(CLK, 1);                            \
        dummy_func(tmp_addr, tmp);                        \
        tmp = (tmp << 1) | (reg_p & P_CARRY);             \
        LOCAL_SET_CARRY(tmp & 0x100);                     \
        LOCAL_SET_NZ(tmp & 0xff);                         \
        INC_PC(pc_inc);                                   \
        store_func(tmp_addr, tmp, 1);                     \
    } while (0)
ROL_A
#define ROL_A ()
Value:
    do {                                    \
        unsigned int tmp = reg_a_read << 1; \
                                            \
        tmp |= (reg_p & P_CARRY);           \
        reg_a_write(tmp);                   \
        LOCAL_SET_NZ(tmp);                  \
        LOCAL_SET_CARRY(tmp & 0x100);       \
        INC_PC(1);                          \
    } while (0)
ROR
#define ROR (addr, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                  \
        unsigned int src, tmp_addr;                       \
                                                          \
        tmp_addr = (addr);                                \
        src = load_func(tmp_addr);                        \
        CLK_ADD(CLK, 1);                                  \
        CLK_ADD_DUMMY(CLK, 1);                            \
        dummy_func(tmp_addr, src);                        \
        if (reg_p & P_CARRY) {                            \
            src |= 0x100;                                 \
        }                                                 \
        LOCAL_SET_CARRY(src & 0x01);                      \
        src >>= 1;                                        \
        LOCAL_SET_NZ(src);                                \
        INC_PC(pc_inc);                                   \
        store_func(tmp_addr, src, 1);                     \
    } while (0)
ROR_A
#define ROR_A ()
Value:
    do {                                     \
        unsigned int tmp = reg_a_read, tmp2; \
        tmp2 = (tmp >> 1) | (reg_p << 7);    \
        LOCAL_SET_CARRY(tmp & 0x01);         \
        reg_a_write(tmp2);                   \
        LOCAL_SET_NZ(tmp2);                  \
        INC_PC(1);                           \
    } while (0)
RRA
#define RRA (addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                             \
        uint8_t src;                                                 \
        unsigned int my_temp, tmp_addr;                              \
                                                                     \
        tmp_addr = (addr);                                           \
        CLK_ADD(CLK, (clk_inc1));                                    \
        src = load_func(tmp_addr);                                   \
        CLK_ADD(CLK, 1);                                             \
        CLK_ADD_DUMMY(CLK, 1);                                       \
        dummy_func(tmp_addr, src);                                   \
        my_temp = src >> 1;                                          \
        if (reg_p & P_CARRY) {                                       \
            my_temp |= 0x80;                                         \
        }                                                            \
        LOCAL_SET_CARRY(src & 0x1);                                  \
        INC_PC(pc_inc);                                              \
        ADC(my_temp, 0, 0);                                          \
        store_func(tmp_addr, my_temp, 1);                            \
    } while (0)
RRA_IND_Y
#define RRA_IND_Y (addr)
Value:
    do {                                                                          \
        uint8_t src;                                                              \
        unsigned int my_tmp_addr;                                                 \
        unsigned int my_temp;                                                     \
                                                                                  \
        my_tmp_addr = LOAD_ZERO_ADDR(addr);                                       \
        CLK_ADD(CLK, 2);                                                          \
        LOAD_DUMMY((my_tmp_addr & 0xff00) | ((my_tmp_addr + reg_y_read) & 0xff)); \
        CLK_ADD_DUMMY(CLK, 1);                                                    \
        my_tmp_addr += reg_y_read;                                                \
        src = LOAD(my_tmp_addr);                                                  \
        CLK_ADD(CLK, 1);                                                          \
        CLK_ADD_DUMMY(CLK, 1);                                                    \
        DUMMY_STORE_ABS_RMW(my_tmp_addr, src);                                    \
        INC_PC(2);                                                                \
        my_temp = src >> 1;                                                       \
        if (reg_p & P_CARRY) {                                                    \
            my_temp |= 0x80;                                                      \
        }                                                                         \
        LOCAL_SET_CARRY(src & 0x1);                                               \
        ADC(my_temp, 0, 0);                                                       \
        STORE_ABS(my_tmp_addr, my_temp, 1);                                       \
    } while (0)
RTI
#define RTI ()
Value:
    do {                                \
        uint16_t tmp;                   \
                                        \
        CHECK_PROFILE_RTI();            \
        CLK_ADD(CLK, CLK_RTI);          \
        LOAD_DUMMY(0x100 + reg_sp);     \
        tmp = (uint16_t)PULL();         \
        LOCAL_SET_STATUS((uint8_t)tmp); \
        tmp = (uint16_t)PULL();         \
        tmp |= (uint16_t)PULL() << 8;   \
        JUMP(tmp);                      \
    } while (0)
Todo:
FIXME: Rotate disk before executing LOCAL_SET_STATUS().
RTS
#define RTS ()
Value:
    do {                             \
        uint16_t tmp;                \
                                     \
        CHECK_PROFILE_RTS();         \
        CLK_ADD(CLK, CLK_RTS);       \
        LOAD_DUMMY(0x100 + reg_sp);  \
        tmp = PULL();                \
        tmp = tmp | (PULL() << 8);   \
        JUMP(tmp);                   \
        FETCH_PARAM(reg_pc);         \
        CLK_ADD(CLK, CLK_INT_CYCLE); \
        INC_PC(1);                   \
    } while (0)
SAX
#define SAX (addr, clk_inc1, clk_inc2, pc_inc)
Value:
    do {                                      \
        unsigned int tmp;                     \
                                              \
        CLK_ADD(CLK, (clk_inc1));             \
        tmp = (addr);                         \
        CLK_ADD(CLK, (clk_inc2));             \
        INC_PC(pc_inc);                       \
        STORE(tmp, reg_a_read & reg_x_read);  \
    } while (0)
SAX_ZERO
#define SAX_ZERO (addr, clk_inc, pc_inc)
Value:
    do {                                             \
        CLK_ADD(CLK, (clk_inc));                     \
        STORE_ZERO((addr), reg_a_read & reg_x_read); \
        INC_PC(pc_inc);                              \
    } while (0)
SBC
#define SBC (value, clk_inc, pc_inc)
Value:
    do {                                                                                    \
        uint16_t src, tmp;                                                                      \
                                                                                            \
        src = (uint16_t)(value);                                                                \
        CLK_ADD(CLK, (clk_inc));                                                            \
        tmp = reg_a_read - src - ((reg_p & P_CARRY) ? 0 : 1);                               \
        if (reg_p & P_DECIMAL) {                                                            \
            unsigned int tmp_a;                                                             \
            tmp_a = (reg_a_read & 0xf) - (src & 0xf) - ((reg_p & P_CARRY) ? 0 : 1);         \
            if (tmp_a & 0x10) {                                                             \
                tmp_a = ((tmp_a - 6) & 0xf) | ((reg_a_read & 0xf0) - (src & 0xf0) - 0x10);  \
            } else {                                                                        \
                tmp_a = (tmp_a & 0xf) | ((reg_a_read & 0xf0) - (src & 0xf0));               \
            }                                                                               \
            if (tmp_a & 0x100) {                                                            \
                tmp_a -= 0x60;                                                              \
            }                                                                               \
            LOCAL_SET_CARRY(tmp < 0x100);                                                   \
            LOCAL_SET_NZ(tmp & 0xff);                                                       \
            LOCAL_SET_OVERFLOW(((reg_a_read ^ tmp) & 0x80) && ((reg_a_read ^ src) & 0x80)); \
            reg_a_write((uint8_t) tmp_a);                                                      \
        } else {                                                                            \
            LOCAL_SET_NZ(tmp & 0xff);                                                       \
            LOCAL_SET_CARRY(tmp < 0x100);                                                   \
            LOCAL_SET_OVERFLOW(((reg_a_read ^ tmp) & 0x80) && ((reg_a_read ^ src) & 0x80)); \
            reg_a_write((uint8_t) tmp);                                                        \
        }                                                                                   \
        INC_PC(pc_inc);                                                                     \
    } while (0)
SBX
#define SBX (value, pc_inc)
Value:
    do {                                       \
        unsigned int tmp;                      \
                                               \
        tmp = (value);                         \
        INC_PC(pc_inc);                        \
        tmp = (reg_a_read & reg_x_read) - tmp; \
        LOCAL_SET_CARRY(tmp < 0x100);          \
        reg_x_write(tmp & 0xff);               \
        LOCAL_SET_NZ(reg_x_read);              \
    } while (0)
SEC
#define SEC ()
Value:
    do {                    \
        LOCAL_SET_CARRY(1); \
        INC_PC(1);          \
    } while (0)
SED
#define SED ()
Value:
    do {                      \
        LOCAL_SET_DECIMAL(1); \
        INC_PC(1);            \
    } while (0)
SEI
#define SEI ()
Value:
    do {                           \
        if (!LOCAL_INTERRUPT()) {  \
            OPCODE_DISABLES_IRQ(); \
        }                          \
        LOCAL_SET_INTERRUPT(1);    \
        INC_PC(1);                 \
    } while (0)
SET_LAST_OPCODE
#define SET_LAST_OPCODE (x)
Info about the last opcode is not needed.
SET_OPCODE
#define SET_OPCODE (o)
Value:
    do {                                       \
        opcode.ins = (o) & 0xff;               \
        opcode.op.op8[0] = ((o) >> 8) & 0xff;  \
        opcode.op.op8[1] = ((o) >> 16) & 0xff; \
    } while (0)
SET_OPCODE for traps.
SHA_ABS_Y
#define SHA_ABS_Y (addr)
Value:
    do {                                                                                   \
        unsigned int tmp;                                                                  \
                                                                                           \
        tmp = (addr);                                                                      \
        INC_PC(3);                                                                         \
        STORE_ABS_SH_Y(tmp, reg_a_read & reg_x_read & ((tmp >> 8) + 1), CLK_ABS_I_STORE2); \
    } while (0)
SHA_IND_Y
#define SHA_IND_Y (addr)
Value:
    do {                                                    \
        unsigned int tmp;                                   \
        uint8_t val;                                        \
                                                            \
        tmp = LOAD_ZERO_ADDR(addr);                         \
        CLK_ADD(CLK, 2);                                    \
        LOAD((tmp & 0xff00) | ((tmp + reg_y_read) & 0xff)); \
        CLK_ADD(CLK, CLK_IND_Y_W);                          \
        val = reg_a_read & reg_x_read & ((tmp >> 8) + 1);   \
        if ((tmp & 0xff) + reg_y_read > 0xff) {             \
            tmp = ((tmp + reg_y_read) & 0xff) | (val << 8); \
        } else {                                            \
            tmp += reg_y_read;                              \
        }                                                   \
        INC_PC(2);                                          \
        STORE(tmp, val);                                    \
    } while (0)
SHS_ABS_Y
#define SHS_ABS_Y (addr)
Value:
    do {                                                                                   \
        int tmp = (addr);                                                                  \
                                                                                           \
        INC_PC(3);                                                                         \
        STORE_ABS_SH_Y(tmp, reg_a_read & reg_x_read & ((tmp >> 8) + 1), CLK_ABS_I_STORE2); \
        reg_sp = reg_a_read & reg_x_read;                                                  \
    } while (0)
SHX_ABS_Y
#define SHX_ABS_Y (addr)
Value:
    do {                                                                      \
        unsigned int tmp;                                                     \
                                                                              \
        tmp = (addr);                                                         \
        INC_PC(3);                                                            \
        STORE_ABS_SH_Y(tmp, reg_x_read & ((tmp >> 8) + 1), CLK_ABS_I_STORE2); \
    } while (0)
SHY_ABS_X
#define SHY_ABS_X (addr)
Value:
    do {                                                                      \
        unsigned int tmp;                                                     \
                                                                              \
        tmp = (addr);                                                         \
        INC_PC(3);                                                            \
        STORE_ABS_SH_X(tmp, reg_y_read & ((tmp >> 8) + 1), CLK_ABS_I_STORE2); \
    } while (0)
SLO
#define SLO (addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                             \
        uint8_t tmp, tmp2;                                           \
        int tmp_addr;                                                \
                                                                     \
        tmp_addr = (addr);                                           \
        CLK_ADD(CLK, (clk_inc1));                                    \
        tmp = load_func(tmp_addr);                                   \
        CLK_ADD(CLK, 1);                                             \
        CLK_ADD_DUMMY(CLK, 1);                                       \
        dummy_func(tmp_addr, tmp);                                   \
        LOCAL_SET_CARRY(tmp & 0x80);                                 \
        tmp <<= 1;                                                   \
        tmp2 = reg_a_read | tmp;                                     \
        reg_a_write(tmp2);                                           \
        LOCAL_SET_NZ(tmp2);                                          \
        INC_PC(pc_inc);                                              \
        store_func(tmp_addr, tmp, 1);                                \
    } while (0)
SLO_IND_Y
#define SLO_IND_Y (addr)
Value:
    do {                                                                    \
        uint8_t tmp, tmp2;                                                  \
        unsigned int tmp_addr;                                              \
                                                                            \
        tmp_addr = LOAD_ZERO_ADDR(addr);                                    \
        CLK_ADD(CLK, 2);                                                    \
        LOAD_DUMMY((tmp_addr & 0xff00) | ((tmp_addr + reg_y_read) & 0xff)); \
        CLK_ADD_DUMMY(CLK, 1);                                              \
        tmp_addr += reg_y_read;                                             \
        tmp = LOAD(tmp_addr);                                               \
        CLK_ADD(CLK, 1);                                                    \
        CLK_ADD_DUMMY(CLK, 1);                                              \
        DUMMY_STORE_ABS_RMW(tmp_addr, tmp);                                 \
        LOCAL_SET_CARRY(tmp & 0x80);                                        \
        tmp <<= 1;                                                          \
        tmp2 = reg_a_read | tmp;                                            \
        reg_a_write(tmp2);                                                  \
        LOCAL_SET_NZ(tmp2);                                                 \
        INC_PC(2);                                                          \
        STORE_ABS(tmp_addr, tmp, 1);                                        \
    } while (0)
SRE
#define SRE (addr, clk_inc1, pc_inc, load_func, store_func, dummy_func)
Value:
    do {                                                             \
        unsigned int tmp, tmp2;                                      \
        unsigned int tmp_addr;                                       \
                                                                     \
        tmp_addr = (addr);                                           \
        CLK_ADD(CLK, (clk_inc1));                                    \
        tmp = load_func(tmp_addr);                                   \
        CLK_ADD(CLK, 1);                                             \
        CLK_ADD_DUMMY(CLK, 1);                                       \
        dummy_func(tmp_addr, tmp);                                   \
        LOCAL_SET_CARRY(tmp & 0x01);                                 \
        tmp >>= 1;                                                   \
        tmp2 = reg_a_read ^ tmp;                                     \
        reg_a_write(tmp2);                                           \
        LOCAL_SET_NZ(tmp2);                                          \
        INC_PC(pc_inc);                                              \
        store_func(tmp_addr, tmp, 1);                                \
    } while (0)
SRE_IND_Y
#define SRE_IND_Y (addr)
Value:
    do {                                                                    \
        unsigned int tmp, tmp2;                                             \
        unsigned int tmp_addr = LOAD_ZERO_ADDR(addr);                       \
                                                                            \
        CLK_ADD(CLK, 2);                                                    \
        LOAD_DUMMY((tmp_addr & 0xff00) | ((tmp_addr + reg_y_read) & 0xff)); \
        CLK_ADD_DUMMY(CLK, 1);                                              \
        tmp_addr += reg_y_read;                                             \
        tmp = LOAD(tmp_addr);                                               \
        CLK_ADD(CLK, 1);                                                    \
        CLK_ADD_DUMMY(CLK, 1);                                              \
        DUMMY_STORE_ABS_RMW(tmp_addr, tmp);                                 \
        LOCAL_SET_CARRY(tmp & 0x01);                                        \
        tmp >>= 1;                                                          \
        tmp2 = reg_a_read ^ tmp;                                            \
        reg_a_write(tmp2);                                                  \
        LOCAL_SET_NZ(tmp2);                                                 \
        INC_PC(2);                                                          \
        STORE_ABS(tmp_addr, tmp, 1);                                        \
    } while (0)
STA
#define STA (addr, clk_inc1, clk_inc2, pc_inc, store_func)
Value:
    do {                                                  \
        unsigned int tmp;                                 \
                                                          \
        CLK_ADD(CLK, (clk_inc1));                         \
        tmp = (addr);                                     \
        INC_PC(pc_inc);                                   \
        store_func(tmp, reg_a_read, clk_inc2);            \
    } while (0)
STA_IND_Y
#define STA_IND_Y (addr)
Value:
    do {                                                        \
        unsigned int tmp;                                       \
                                                                \
        tmp = LOAD_ZERO_ADDR(addr);                             \
        CLK_ADD(CLK, 2);                                        \
        LOAD_DUMMY((tmp & 0xff00) | ((tmp + reg_y_read) & 0xff)); \
        CLK_ADD(CLK, CLK_IND_Y_W);                              \
        INC_PC(2);                                              \
        STORE_IND(tmp + reg_y_read, reg_a_read);                \
    } while (0)
STA_ZERO
#define STA_ZERO (addr, clk_inc, pc_inc)
Value:
    do {                                \
        CLK_ADD(CLK, (clk_inc));        \
        STORE_ZERO((addr), reg_a_read); \
        INC_PC(pc_inc);                 \
    } while (0)
STORE_ABS
#define STORE_ABS (addr, value, inc)
Value:
    do {                            \
        CLK_ADD(CLK, (inc));        \
        STORE((addr), (value));     \
    } while (0)
STORE_ABS_SH_X
#define STORE_ABS_SH_X (addr, value, inc)
Value:
    do {                                                                \
        unsigned int tmp2;                                              \
                                                                        \
        CLK_ADD(CLK, (inc) - 2);                                        \
        LOAD_DUMMY((((addr) + reg_x_read) & 0xff) | ((addr) & 0xff00)); \
        CLK_ADD(CLK, 2);                                                \
        tmp2 = (addr) + reg_x_read;                                     \
        if (((addr) & 0xff) + reg_x_read > 0xff) {                      \
            tmp2 = (tmp2 & 0xff) | ((value) << 8);                      \
        }                                                               \
        STORE(tmp2, (value));                                           \
    } while (0)
STORE_ABS_SH_Y
#define STORE_ABS_SH_Y (addr, value, inc)
Value:
    do {                                                                \
        unsigned int tmp2;                                              \
                                                                        \
        CLK_ADD(CLK, (inc) - 2);                                        \
        LOAD_DUMMY((((addr) + reg_y_read) & 0xff) | ((addr) & 0xff00)); \
        CLK_ADD(CLK, 2);                                                \
        tmp2 = (addr) + reg_y_read;                                     \
        if (((addr) & 0xff) + reg_y_read > 0xff) {                      \
            tmp2 = (tmp2 & 0xff) | ((value) << 8);                      \
        }                                                               \
        STORE(tmp2, (value));                                           \
    } while (0)
STORE_ABS_X
#define STORE_ABS_X (addr, value, inc)
Value:
    do {                                                                \
        CLK_ADD(CLK, (inc) - 2);                                        \
        LOAD_DUMMY((((addr) + reg_x_read) & 0xff) | ((addr) & 0xff00)); \
        CLK_ADD(CLK, 2);                                                \
        STORE((addr) + reg_x_read, (value));                            \
    } while (0)
STORE_ABS_X_RMW
#define STORE_ABS_X_RMW (addr, value, inc)
Value:
    do {                                     \
        CLK_ADD(CLK, (inc));                 \
        STORE((addr) + reg_x_read, (value)); \
    } while (0)
STORE_ABS_Y
#define STORE_ABS_Y (addr, value, inc)
Value:
    do {                                                                \
        CLK_ADD(CLK, (inc) - 2);                                        \
        LOAD_DUMMY((((addr) + reg_y_read) & 0xff) | ((addr) & 0xff00)); \
        CLK_ADD(CLK, 2);                                                \
        STORE((addr) + reg_y_read, (value));                            \
    } while (0)
STORE_ABS_Y_RMW
#define STORE_ABS_Y_RMW (addr, value, inc)
Value:
    do {                                     \
        CLK_ADD(CLK, (inc));                 \
        STORE((addr) + reg_y_read, (value)); \
    } while (0)
STORE_IND
#define STORE_IND (a, b) STORE(a, b)
STX
#define STX (addr, clk_inc, pc_inc)
Value:
    do {                           \
        unsigned int tmp;          \
                                   \
        tmp = (addr);              \
        CLK_ADD(CLK, (clk_inc));   \
        INC_PC(pc_inc);            \
        STORE(tmp, reg_x_read);    \
    } while (0)
STX_ZERO
#define STX_ZERO (addr, clk_inc, pc_inc)
Value:
    do {                                \
        CLK_ADD(CLK, (clk_inc));        \
        STORE_ZERO((addr), reg_x_read); \
        INC_PC(pc_inc);                 \
    } while (0)
STY
#define STY (addr, clk_inc, pc_inc)
Value:
    do {                           \
        unsigned int tmp;          \
                                   \
        tmp = (addr);              \
        CLK_ADD(CLK, (clk_inc));   \
        INC_PC(pc_inc);            \
        STORE(tmp, reg_y_read);    \
    } while (0)
STY_ZERO
#define STY_ZERO (addr, clk_inc, pc_inc)
Value:
    do {                                \
        CLK_ADD(CLK, (clk_inc));        \
        STORE_ZERO((addr), reg_y_read); \
        INC_PC(pc_inc);                 \
    } while (0)
TAX
#define TAX ()
Value:
    do {                          \
        reg_x_write(reg_a_read);  \
        LOCAL_SET_NZ(reg_x_read); \
        INC_PC(1);                \
    } while (0)
TAY
#define TAY ()
Value:
    do {                          \
        reg_y_write(reg_a_read);  \
        LOCAL_SET_NZ(reg_y_read); \
        INC_PC(1);                \
    } while (0)
TRACE_BRK
#define TRACE_BRK ()
TRACE_IRQ
#define TRACE_IRQ (clk)
TRACE_NMI
#define TRACE_NMI (clk)
TSX
#define TSX ()
Value:
    do {                      \
        reg_x_write(reg_sp);  \
        LOCAL_SET_NZ(reg_sp); \
        INC_PC(1);            \
    } while (0)
TXA
#define TXA ()
Value:
    do {                          \
        reg_a_write(reg_x_read);  \
        LOCAL_SET_NZ(reg_x_read); \
        INC_PC(1);                \
    } while (0)
TXS
#define TXS ()
Value:
    do {                     \
        reg_sp = reg_x_read; \
        INC_PC(1);           \
    } while (0)
TYA
#define TYA ()
Value:
    do {                          \
        reg_a_write(reg_y_read);  \
        LOCAL_SET_NZ(reg_y_read); \
        INC_PC(1);                \
    } while (0)
Function Documentation
if() [1/4]
if (!(CPU_INT_STATUS->global_pending_int &IK_IRQ) &&(CPU_INT_STATUS->global_pending_int &IK_IRQPEND) &&CPU_INT_STATUS->irq_pending_clk<= CLK)
if() [2/4]
if (cpu_is_jammed)
Referenced by draw_char_nlq(), draw_std_background(), drive_image_attach(), drive_snapshot_read_p64image_module(), drive_snapshot_write_p64image_module(), fastsid_state_read(), fdd_read(), fsimage_p64_read_half_track(), fsimage_p64_write_half_track(), fsimage_p64_write_track(), get_idle(), print_disass_context(), render(), resid_state_write(), rotation_1541_gcr(), rotation_1541_p64(), scsi_image_read(), scsi_image_write(), sound_dac_calculate_samples(), undump_pra(), vdrive_command_validate_worker(), vicii_memory_refresh_alarm_handler(), vicii_sprites_set_x_position(), and video_viewport_resize().
if() [3/4]
if (maincpu_profiling)
if() [4/4]
if (pending_interrupt ! = IK_NONE)
SET_LAST_ADDR()
SET_LAST_ADDR (reg_pc)
switch()
switch ((opcode.ins))
< needs to be 0xee for wizball
Referenced by fastsid_state_write().
while()
while (CLK >= alarm_context_next_pending_clkALARM_CONTEXT)
Referenced by raster_changes_add_sorted_int().
Variable Documentation
__pad0__
trap_skipped __pad0__
do
do { if (((int)reg_pc) < bank_limit) { (opcode).ins = *(bank_base + reg_pc); (opcode).op.op16 = (*(bank_base + reg_pc + 1) | (*(bank_base + reg_pc + 2) << 8)); ((CLK) += (2)); if (fetch_tab[(opcode).ins]) { ((CLK) += (1)); } } else { (opcode).ins = LOAD(reg_pc); ((CLK) += (1)); (opcode).op.op16 = LOAD(reg_pc + 1); ((CLK) += (1)); if (fetch_tab[(opcode).ins]) { (opcode).op.op16 |= (LOAD(reg_pc + 2) << 8); ((CLK) += (1)); } } } while (0)
fetch_tab
const uint8_t fetch_tab[] static
Initial value:
= {
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1
}
pending_interrupt
pending_interrupt = CPU_INT_STATUS->global_pending_int
Referenced by if(), and z80_maincpu_loop().
profiling_clock_start
profiling_clock_start = CLK
Referenced by if().
tmpa
unsigned int tmpa
Initial value:
{
    static int cpu_is_jammed = 0
Here, the CPU is emulated.