vsid: arch/gtk3/widgets/settings_c64memhacks.c File Reference
settings_c64memhacks.c File Reference
Settings widget to control C64 memory expansion hacks.
#include "vice.h"
#include <gtk/gtk.h>
#include "c64-memory-hacks.h"
#include "debug_gtk3.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "settings_c64memhacks.h"
Functions
static GtkWidget * create_label (const char *text)
Create left-aligned, 8 pixels left-indented label.
static void update_widgets_sensitivity (int hack_id)
Update sensitivity of memory hack widgets based on active hack.
static void on_hack_toggled (GtkWidget *widget, gpointer hack_id)
Extra handler for the "toggled" event of the mem hack radio buttons.
static GtkWidget * memory_hacks_device_widget_create (void)
Create widget to select the memory hacks device.
static GtkWidget * create_memhack_widget (const char *title, const char *base_resource, const vice_gtk3_radiogroup_entry_t *base_addresses, const char *image_resource, const char *image_browser_title)
Create widget for memory hack.
GtkWidget * settings_c64_memhacks_widget_create (GtkWidget *parent)
Create widget controlling C64 memory hacks.
Variables
static const vice_gtk3_radiogroup_entry_t mem_hack_devices []
List of C64 memory hack devices.
static const vice_gtk3_radiogroup_entry_t c64_256k_base_addresses []
List of I/O base addresses for the C64_256K memory hack.
static const vice_gtk3_radiogroup_entry_t plus_60k_base_addresses []
List of I/O base addresses for the +60K memory hack.
static GtkWidget * c64_256k_widget = NULL
c64 256K widget reference
static GtkWidget * plus_60k_widget = NULL
Plus60K widget reference.
static GtkWidget * plus_256k_widget = NULL
Plus256K image widget reference.
Detailed Description
Settings widget to control C64 memory expansion hacks.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_label()
static GtkWidget * create_label (const char * text) static
Create left-aligned, 8 pixels left-indented label.
Parameters
[in] text text for the label
Returns
new GtkLabel
Referenced by create_memhack_widget().
create_memhack_widget()
static GtkWidget * create_memhack_widget (const char * title, const char * base_resource, const vice_gtk3_radiogroup_entry_t * base_addresses, const char * image_resource, const char * image_browser_title) static
Create widget for memory hack.
Create a grid with title and I/O base and/or image file browser widgets.
Parameters
[in] title widget title
[in] base_resource resource name of the memhack I/O base address (optional)
[in] base_addresses radio group entries for the I/O base address (optional)
[in] image_resource resource name of the memhack image file (optional)
[in] image_browser_title title of the file chooser dialog to select image file (optional)
Returns
GtkGrid
Referenced by settings_c64_memhacks_widget_create().
memory_hacks_device_widget_create()
static GtkWidget * memory_hacks_device_widget_create (void) static
Create widget to select the memory hacks device.
Returns
GtkGrid
Referenced by settings_c64_memhacks_widget_create().
on_hack_toggled()
static void on_hack_toggled (GtkWidget * widget, gpointer hack_id) static
Extra handler for the "toggled" event of the mem hack radio buttons.
This handler enables/disables the widgets related to the memory hack selected
Parameters
[in] widget radio button of the select hack
[in] hack_id hack ID
Referenced by memory_hacks_device_widget_create().
settings_c64_memhacks_widget_create()
GtkWidget * settings_c64_memhacks_widget_create (GtkWidget * parent)
Create widget controlling C64 memory hacks.
Parameters
[in] parent parent widhet, used for dialog
Returns
GtkGrid
update_widgets_sensitivity()
static void update_widgets_sensitivity (int hack_id) static
Update sensitivity of memory hack widgets based on active hack.
Parameters
[in] hack_id ID of currently active memory hack
Referenced by on_hack_toggled(), and settings_c64_memhacks_widget_create().
Variable Documentation
c64_256k_base_addresses
const vice_gtk3_radiogroup_entry_t c64_256k_base_addresses[] static
Initial value:
= {
    { "$DE00", 0xde00 },
    { "$DE80", 0xde80 },
    { "$DF00", 0xdf00 },
    { "$DF80", 0xdf80 },
    { NULL,        -1 }
}
List of I/O base addresses for the C64_256K memory hack.
Referenced by settings_c64_memhacks_widget_create().
c64_256k_widget
GtkWidget* c64_256k_widget = NULL static
c64 256K widget reference
Referenced by settings_c64_memhacks_widget_create(), and update_widgets_sensitivity().
mem_hack_devices
const vice_gtk3_radiogroup_entry_t mem_hack_devices[] static
Initial value:
= {
    { "None",       MEMORY_HACK_NONE },
    { "C64 256K",   MEMORY_HACK_C64_256K },
    { "+60K",       MEMORY_HACK_PLUS60K },
    { "+256K",      MEMORY_HACK_PLUS256K },
    { NULL,         -1 }
}
List of C64 memory hack devices.
Referenced by memory_hacks_device_widget_create().
plus_256k_widget
GtkWidget* plus_256k_widget = NULL static
Plus256K image widget reference.
Referenced by settings_c64_memhacks_widget_create(), and update_widgets_sensitivity().
plus_60k_base_addresses
const vice_gtk3_radiogroup_entry_t plus_60k_base_addresses[] static
Initial value:
= {
    { "$D040", 0xd040 },
    { "$D100", 0xd100 },
    { NULL,        -1 }
}
List of I/O base addresses for the +60K memory hack.
Referenced by settings_c64_memhacks_widget_create().
plus_60k_widget
GtkWidget* plus_60k_widget = NULL static
Plus60K widget reference.
Referenced by settings_c64_memhacks_widget_create(), and update_widgets_sensitivity().