x128: m3u.h File Reference
m3u.h File Reference
Extended M3U playlist handling - header.
#include <stddef.h>
#include <stdbool.h>
Enumerations
enum m3u_ext_id_t {
M3U_ERROR = -1 ,
M3U_EXTM3U ,
M3U_EXTINF ,
M3U_PLAYLIST ,
M3U_EXTALB ,
M3U_EXTART
}
m3u directives
Functions
bool m3u_open (const char *path, bool(*entry_callback)(const char *arg, size_t len), bool(*directive_callback)(m3u_ext_id_t id, const char *arg, size_t len))
Open m3u file for parsing.
bool m3u_parse (void)
Parse the playlist.
void m3u_close (void)
Close m3u file and clean up resources.
bool m3u_create (const char *path)
Create new M3U playlist file.
bool m3u_set_playlist_title (const char *title)
Set playlist title.
bool m3u_append_entry (const char *entry)
Append normal entry to playlist file.
bool m3u_append_comment (const char *comment)
Append comment to playlist file.
bool m3u_append_newline (void)
Append newline to playlist file.
long m3u_linenum (void)
Get current line number of playlist being processed.
const char * m3u_directive_str (m3u_ext_id_t id)
Get directive string for ID.
Detailed Description
Extended M3U playlist handling - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
m3u_ext_id_t
enum m3u_ext_id_t
m3u directives
Enumerator
M3U_ERROR
for error reporting, not part of m3u
M3U_EXTM3U
extended M3U header "\#EXTM3U"
M3U_EXTINF
track info, key=value pairs
M3U_PLAYLIST
playlist title
M3U_EXTALB
album title
M3U_EXTART
album artist
Function Documentation
m3u_append_comment()
bool m3u_append_comment (const char * comment)
Append comment to playlist file.
Parameters
[in] comment comment text
Note
The caller should not use the '#' comment token, the function will add it.
Returns
true on success
Referenced by playlist_save_dialog_callback().
m3u_append_entry()
bool m3u_append_entry (const char * entry)
Append normal entry to playlist file.
Append path to SID file to playlist file.
Parameters
[in] entry path to SID file
Returns
true on success
Todo:
Support relative paths
Referenced by playlist_save_dialog_callback().
m3u_append_newline()
bool m3u_append_newline (void)
Append newline to playlist file.
Returns
true on success
Referenced by m3u_append_string(), and playlist_save_dialog_callback().
m3u_close()
void m3u_close (void)
Close m3u file and clean up resources.
Cleans up resources and resets internal state for subsequent reading or writing of m3u files.
Referenced by playlist_load_callback(), and playlist_save_dialog_callback().
m3u_create()
bool m3u_create (const char * path)
Create new M3U playlist file.
Open path for writing and write the M3U header.
Parameters
[in] path filename and path
Returns
true on success
Referenced by playlist_save_dialog_callback().
m3u_directive_str()
const char * m3u_directive_str (m3u_ext_id_t id)
Get directive string for ID.
Parameters
[in] id directive ID
See also
m3u_ext_id_t
m3u_linenum()
long m3u_linenum (void)
Get current line number of playlist being processed.
Returns
line number
m3u_open()
bool m3u_open (const char * path, bool(*)(const char *arg, size_t len) entry_callback, bool(*)(m3u_ext_id_t id, const char *arg, size_t len) directive_callback)
Open m3u file for parsing.
Try to open path for reading and set up the parser.
The entry_callback argument is required and will be called by m3u_parse() whenever a normal entry is encountered in path. Its first argument is the entry text and the second argument is the lenght of the entry excluding the terminating nul character.
The directive_callback argument is optional and can be used to handle extended M3U directives. The first argument is the directive ID (
See also
m3u_ext_id_t), the second argument is the text following the directive and the third argument is the length of the text excluding the terminating nul character.
To stop the parser the callbacks must return false.
Parameters
[in] path path to m3u file
[in] entry_callback callback for normal entries
[in] directive_callback callback for extended m3u directives (optional, pass NULL to ignore)
Returns
true on success
Referenced by playlist_load_callback().
m3u_parse()
bool m3u_parse (void)
Parse the playlist.
Parse playlist file triggering the callbacks registered with m3u_open().
Returns
true on success
Referenced by playlist_load_callback().
m3u_set_playlist_title()
bool m3u_set_playlist_title (const char * title)
Set playlist title.
Parameters
[in] title playlist title
Returns
true on success
Note
Normally one would call this after m3u_create() and before adding any entries.
Referenced by playlist_save_dialog_callback().