vsid: arch/shared/coproc.h File Reference
coproc.h File Reference
co-process fork - header
#include <sys/types.h>
Typedefs
typedef pid_t vice_pid_t
Functions
int fork_coproc (int *fd_wr, int *fd_rd, char *cmd, vice_pid_t *childpid)
void kill_coproc (vice_pid_t pid)
Detailed Description
co-process fork - header
Author
Andre Fachat a.fac.nosp@m.hat@.nosp@m.physi.nosp@m.k.tu.nosp@m.-chem.nosp@m.nitz.nosp@m..de
Typedef Documentation
vice_pid_t
typedef pid_t vice_pid_t
Function Documentation
fork_coproc()
int fork_coproc (int * fd_wr, int * fd_rd, char * cmd, vice_pid_t * childpid)
Referenced by fopen_or_pipe(), and start_ffmpeg_executable().
kill_coproc()
void kill_coproc (vice_pid_t pid)
Referenced by close_stream(), and output_text_close().