vsid: arch/gtk3/uicart.h File Reference
uicart.h File Reference
Widget to attach carts - header.
#include "vice.h"
#include <gtk/gtk.h>
#include "cartridge.h"
Functions
void ui_cart_show_dialog (void)
Pop up the cart-attach dialog.
void ui_cart_default_attach (GtkWidget *widget, void(*callback)(void))
Attach dialog for the settings->default cart page.
void ui_cart_shutdown (void)
Clean up the last directory string.
Detailed Description
Widget to attach carts - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
ui_cart_default_attach()
void ui_cart_default_attach (GtkWidget * widget, void(*)(void) callback)
Attach dialog for the settings->default cart page.
Parameters
[in] widget parent widget (unused)
[in] callback function to call on succesfull attach
Referenced by on_attach_clicked().
ui_cart_show_dialog()
void ui_cart_show_dialog (void)
Pop up the cart-attach dialog.
Referenced by cart_attach_action().
ui_cart_shutdown()
void ui_cart_shutdown (void)
Clean up the last directory string.
Referenced by ui_exit().