vsid: arch/gtk3/kbd.h File Reference
kbd.h File Reference
Native GTK3 specfic keyboard driver - header.
#include <gtk/gtk.h>
Data Structures
struct kbd_gtk3_hotkey_s
Gtk3 keyboard shortcut to be used without Gtk3's accelerators.
Macros
#define KBD_PORT_PREFIX "gtk3"
Prefix for the Gtk3 port keymap files.
Typedefs
typedef struct kbd_gtk3_hotkey_s kbd_gtk3_hotkey_t
Gtk3 keyboard shortcut to be used without Gtk3's accelerators.
Functions
void kbd_arch_init (void)
Initialize keyboard handling.
void kbd_arch_shutdown (void)
Shutdown keyboard handling (NOP)
void kbd_initialize_numpad_joykeys (int *joykeys)
Initialize numpad joystick key mapping.
void kbd_connect_handlers (GtkWidget *widget, void *data)
Connect keyboard event handlers to the current window.
signed long kbd_arch_keyname_to_keynum (char *keyname)
add more function prototypes as needed below
const char * kbd_arch_keynum_to_keyname (signed long keynum)
Get keyname from keynum.
const char * kbd_get_menu_keyname (void)
Only here for c1541-stubs.c, not used in the Gtk3 UI.
Detailed Description
Native GTK3 specfic keyboard driver - header.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Macro Definition Documentation
KBD_PORT_PREFIX
#define KBD_PORT_PREFIX "gtk3"
Prefix for the Gtk3 port keymap files.
Typedef Documentation
kbd_gtk3_hotkey_t
typedef struct kbd_gtk3_hotkey_s kbd_gtk3_hotkey_t
Gtk3 keyboard shortcut to be used without Gtk3's accelerators.
In Gtk3 there is no normal method to create a keyboard shortcut without it being connected to a G(tk)MenuItem. This object "solves" this problem by having the kbd_event_handler() function scan a list of these objects and trigger a callback when a specific key press matches.
Function Documentation
kbd_arch_init()
void kbd_arch_init (void)
Initialize keyboard handling.
Referenced by keyboard_init().
kbd_arch_keyname_to_keynum()
signed long kbd_arch_keyname_to_keynum (char * keyname)
add more function prototypes as needed below
add more function prototypes as needed below
Parameters
[in] keyname key name as a string
Returns
keynum or -1 on error
Note
You don't see "signed $type-not-plain-char" too often :)
Referenced by keyboard_keyword_undef(), and keyboard_parse_entry().
kbd_arch_keynum_to_keyname()
const char * kbd_arch_keynum_to_keyname (signed long keynum)
Get keyname from keynum.
Parameters
[in] keynum key number
Returns
key value for keynum
Referenced by keyboard_keymap_dump().
kbd_arch_shutdown()
void kbd_arch_shutdown (void)
Shutdown keyboard handling (NOP)
kbd_connect_handlers()
void kbd_connect_handlers (GtkWidget * widget, void * data)
Connect keyboard event handlers to the current window.
Parameters
[in] widget GtkWindow instance
[in] data extra event data
Referenced by ui_create_main_window().
kbd_get_menu_keyname()
const char * kbd_get_menu_keyname (void)
Only here for c1541-stubs.c, not used in the Gtk3 UI.
Returns
NULL
Referenced by archdep_extra_title_text().
kbd_initialize_numpad_joykeys()
void kbd_initialize_numpad_joykeys (int * joykeys)
Initialize numpad joystick key mapping.
Parameters
[out] joykeys pointer to joykey array