vsid: via.h File Reference
via.h File Reference
#include "types.h"
Data Structures
struct via_context_s
Macros
#define VIA_PRB 0
MOS 6522 registers.
#define VIA_PRA 1
Port A.
#define VIA_DDRB 2
Data direction register for port B.
#define VIA_DDRA 3
Data direction register for port A.
#define VIA_T1CL 4
Timer 1 count low.
#define VIA_T1CH 5
Timer 1 count high.
#define VIA_T1LL 6
Timer 1 latch low.
#define VIA_T1LH 7
Timer 1 latch high.
#define VIA_T2CL 8
Timer 2 count low - read only.
#define VIA_T2LL 8
Timer 2 latch low - write only.
#define VIA_T2CH 9
Timer 2 count high - read only.
#define VIA_T2LH 9
Timer 2 latch high - write only.
#define VIA_SR 10
Serial port shift register.
#define VIA_ACR 11
Auxiliary control register.
#define VIA_PCR 12
Peripheral control register.
#define VIA_IFR 13
Interrupt flag register.
#define VIA_IER 14
Interrupt control register.
#define VIA_PRA_NHS 15
Port A with no handshake.
#define VIA_IM_IRQ 128
Interrupt Masks
#define VIA_IM_T1 64
Timer 1 underflow.
#define VIA_IM_T2 32
Timer 2 underflow.
#define VIA_IM_CB1 16
Handshake.
#define VIA_IM_CB2 8
Handshake.
#define VIA_IM_SR 4
Shift Register completion.
#define VIA_IM_CA1 2
Handshake.
#define VIA_IM_CA2 1
Handshake.
#define VIA_ACR_T1_CONTROL 0xC0
#define VIA_ACR_T1_PB7_UNUSED 0x00
#define VIA_ACR_T1_PB7_USED 0x80
#define VIA_ACR_T1_ONE_SHOT 0x00
#define VIA_ACR_T1_FREE_RUN 0x40
#define VIA_ACR_T2_CONTROL 0x20
#define VIA_ACR_T2_TIMER 0x00
#define VIA_ACR_T2_COUNTPB6 0x20
#define VIA_ACR_SR_CONTROL 0x1C
#define VIA_ACR_SR_IN 0x00
#define VIA_ACR_SR_OUT 0x10
#define VIA_ACR_SR_DISABLED 0x00 /* mode 0 Shift register disabled */
#define VIA_ACR_SR_IN_T2 0x04 /* mode 1 Shift in under control of Timer 2*/
#define VIA_ACR_SR_IN_PHI2 0x08 /* mode 2 Shift at System Clock Rate */
#define VIA_ACR_SR_IN_CB1 0x0C /* mode 3 Shift under Control of External Clock */
#define VIA_ACR_SR_OUT_FREE_T2 0x10 /* mode 4 Free-running output */
#define VIA_ACR_SR_OUT_T2 0x14 /* mode 5 Shift out under control of T2 */
#define VIA_ACR_SR_OUT_PHI2 0x18 /* mode 6 Shift out at System Clock Rate */
#define VIA_ACR_SR_OUT_CB1 0x1C /* mode 7 Shift out under control of an External Pulse */
#define VIA_ACR_PB_LATCH 0x02
#define VIA_ACR_PA_LATCH 0x01
#define VIA_PCR_CB2_CONTROL 0xE0
3 bits
#define VIA_PCR_CB2_I_OR_O 0x80
bit
#define VIA_PCR_CB2_INPUT 0x00
bit
#define VIA_PCR_CB2_INPUT_NEG_ACTIVE_EDGE 0x00
bit
#define VIA_PCR_CB2_INPUT_POS_ACTIVE_EDGE 0x40
bit
#define VIA_PCR_CB2_INDEPENDENT_INTERRUPT 0x20
bit
#define VIA_PCR_CB2_HANDSHAKE_OUTPUT 0x80
If INDEPENDENT_INTERRUPT is set, "reading or writing ORB does not clear the CB2 interrupt flag".
#define VIA_PCR_CB2_PULSE_OUTPUT 0xA0
3 bits
#define VIA_PCR_CB2_LOW_OUTPUT 0xC0
3 bits
#define VIA_PCR_CB2_HIGH_OUTPUT 0xE0
3 bits
#define VIA_PCR_CB1_CONTROL 0x10
1 bit
#define VIA_PCR_CB1_NEG_ACTIVE_EDGE 0x00
bit
#define VIA_PCR_CB1_POS_ACTIVE_EDGE 0x10
bit
#define VIA_PCR_CA2_CONTROL 0x0E
3 bits
#define VIA_PCR_CA2_I_OR_O 0x08
bit
#define VIA_PCR_CA2_INPUT 0x00
bit
#define VIA_PCR_CA2_INPUT_NEG_ACTIVE_EDGE 0x00
bit
#define VIA_PCR_CA2_INPUT_POS_ACTIVE_EDGE 0x04
bit
#define VIA_PCR_CA2_INDEPENDENT_INTERRUPT 0x02
bit
#define VIA_PCR_CA2_HANDSHAKE_OUTPUT 0x08
If INDEPENDENT_INTERRUPT is set, "reading or writing ORA does not clear the CA2 interrupt flag".
#define VIA_PCR_CA2_PULSE_OUTPUT 0x0A
3 bits
#define VIA_PCR_CA2_LOW_OUTPUT 0x0C
3 bits
#define VIA_PCR_CA2_HIGH_OUTPUT 0x0E
3 bits
#define VIA_PCR_CA1_CONTROL 0x01
1 bit
#define VIA_PCR_CA1_NEG_ACTIVE_EDGE 0x00
bit
#define VIA_PCR_CA1_POS_ACTIVE_EDGE 0x01
bit
#define VIA_SIG_CA1 0
Signal values (for signaling edges on the control lines)
#define VIA_SIG_CA2 1
#define VIA_SIG_CB1 2
#define VIA_SIG_CB2 3
#define VIA_SIG_FALL 0
#define VIA_SIG_RISE 1
#define START_SHIFTING 0
#define FINISHED_SHIFTING 16
Typedefs
typedef struct via_context_s via_context_t
Functions
void viacore_setup_context (struct via_context_s *via_context)
void viacore_init (struct via_context_s *via_context, struct alarm_context_s *alarm_context, struct interrupt_cpu_status_s *int_status)
void viacore_shutdown (struct via_context_s *via_context)
void viacore_reset (struct via_context_s *via_context)
void viacore_disable (struct via_context_s *via_context)
void viacore_signal (struct via_context_s *via_context, int line, int edge)
void viacore_store (struct via_context_s *via_context, uint16_t addr, uint8_t data)
uint8_t viacore_read (struct via_context_s *via_context, uint16_t addr)
uint8_t viacore_peek (struct via_context_s *via_context, uint16_t addr)
return value of a register without side effects
void viacore_set_sr (via_context_t *via_context, uint8_t data)
WARNING: this is a hack.
void viacore_set_cb1 (struct via_context_s *via_context, bool data)
void viacore_set_cb2 (struct via_context_s *via_context, bool data)
int viacore_snapshot_write_module (struct via_context_s *via_context, struct snapshot_s *s)
FIXME!!! Error check.
int viacore_snapshot_read_module (struct via_context_s *via_context, struct snapshot_s *s)
int viacore_dump (via_context_t *via_context)
Macro Definition Documentation
FINISHED_SHIFTING
#define FINISHED_SHIFTING 16
START_SHIFTING
#define START_SHIFTING 0
VIA_ACR
#define VIA_ACR 11
Auxiliary control register.
VIA_ACR_PA_LATCH
#define VIA_ACR_PA_LATCH 0x01
VIA_ACR_PB_LATCH
#define VIA_ACR_PB_LATCH 0x02
VIA_ACR_SR_CONTROL
#define VIA_ACR_SR_CONTROL 0x1C
VIA_ACR_SR_DISABLED
#define VIA_ACR_SR_DISABLED 0x00 /* mode 0 Shift register disabled */
VIA_ACR_SR_IN
#define VIA_ACR_SR_IN 0x00
VIA_ACR_SR_IN_CB1
#define VIA_ACR_SR_IN_CB1 0x0C /* mode 3 Shift under Control of External Clock */
VIA_ACR_SR_IN_PHI2
#define VIA_ACR_SR_IN_PHI2 0x08 /* mode 2 Shift at System Clock Rate */
VIA_ACR_SR_IN_T2
#define VIA_ACR_SR_IN_T2 0x04 /* mode 1 Shift in under control of Timer 2*/
VIA_ACR_SR_OUT
#define VIA_ACR_SR_OUT 0x10
VIA_ACR_SR_OUT_CB1
#define VIA_ACR_SR_OUT_CB1 0x1C /* mode 7 Shift out under control of an External Pulse */
VIA_ACR_SR_OUT_FREE_T2
#define VIA_ACR_SR_OUT_FREE_T2 0x10 /* mode 4 Free-running output */
VIA_ACR_SR_OUT_PHI2
#define VIA_ACR_SR_OUT_PHI2 0x18 /* mode 6 Shift out at System Clock Rate */
VIA_ACR_SR_OUT_T2
#define VIA_ACR_SR_OUT_T2 0x14 /* mode 5 Shift out under control of T2 */
VIA_ACR_T1_CONTROL
#define VIA_ACR_T1_CONTROL 0xC0
VIA_ACR_T1_FREE_RUN
#define VIA_ACR_T1_FREE_RUN 0x40
VIA_ACR_T1_ONE_SHOT
#define VIA_ACR_T1_ONE_SHOT 0x00
VIA_ACR_T1_PB7_UNUSED
#define VIA_ACR_T1_PB7_UNUSED 0x00
VIA_ACR_T1_PB7_USED
#define VIA_ACR_T1_PB7_USED 0x80
VIA_ACR_T2_CONTROL
#define VIA_ACR_T2_CONTROL 0x20
VIA_ACR_T2_COUNTPB6
#define VIA_ACR_T2_COUNTPB6 0x20
VIA_ACR_T2_TIMER
#define VIA_ACR_T2_TIMER 0x00
VIA_DDRA
#define VIA_DDRA 3
Data direction register for port A.
VIA_DDRB
#define VIA_DDRB 2
Data direction register for port B.
VIA_IER
#define VIA_IER 14
Interrupt control register.
VIA_IFR
#define VIA_IFR 13
Interrupt flag register.
VIA_IM_CA1
#define VIA_IM_CA1 2
Handshake.
VIA_IM_CA2
#define VIA_IM_CA2 1
Handshake.
VIA_IM_CB1
#define VIA_IM_CB1 16
Handshake.
VIA_IM_CB2
#define VIA_IM_CB2 8
Handshake.
VIA_IM_IRQ
#define VIA_IM_IRQ 128
Interrupt Masks
MOS 6522 Control Bit
VIA_IM_SR
#define VIA_IM_SR 4
Shift Register completion.
VIA_IM_T1
#define VIA_IM_T1 64
Timer 1 underflow.
VIA_IM_T2
#define VIA_IM_T2 32
Timer 2 underflow.
VIA_PCR
#define VIA_PCR 12
Peripheral control register.
VIA_PCR_CA1_CONTROL
#define VIA_PCR_CA1_CONTROL 0x01
1 bit
VIA_PCR_CA1_NEG_ACTIVE_EDGE
#define VIA_PCR_CA1_NEG_ACTIVE_EDGE 0x00
bit
VIA_PCR_CA1_POS_ACTIVE_EDGE
#define VIA_PCR_CA1_POS_ACTIVE_EDGE 0x01
bit
VIA_PCR_CA2_CONTROL
#define VIA_PCR_CA2_CONTROL 0x0E
3 bits
VIA_PCR_CA2_HANDSHAKE_OUTPUT
#define VIA_PCR_CA2_HANDSHAKE_OUTPUT 0x08
If INDEPENDENT_INTERRUPT is set, "reading or writing ORA does not clear the CA2 interrupt flag".
3 bits
VIA_PCR_CA2_HIGH_OUTPUT
#define VIA_PCR_CA2_HIGH_OUTPUT 0x0E
3 bits
VIA_PCR_CA2_I_OR_O
#define VIA_PCR_CA2_I_OR_O 0x08
bit
VIA_PCR_CA2_INDEPENDENT_INTERRUPT
#define VIA_PCR_CA2_INDEPENDENT_INTERRUPT 0x02
bit
VIA_PCR_CA2_INPUT
#define VIA_PCR_CA2_INPUT 0x00
bit
VIA_PCR_CA2_INPUT_NEG_ACTIVE_EDGE
#define VIA_PCR_CA2_INPUT_NEG_ACTIVE_EDGE 0x00
bit
VIA_PCR_CA2_INPUT_POS_ACTIVE_EDGE
#define VIA_PCR_CA2_INPUT_POS_ACTIVE_EDGE 0x04
bit
VIA_PCR_CA2_LOW_OUTPUT
#define VIA_PCR_CA2_LOW_OUTPUT 0x0C
3 bits
VIA_PCR_CA2_PULSE_OUTPUT
#define VIA_PCR_CA2_PULSE_OUTPUT 0x0A
3 bits
VIA_PCR_CB1_CONTROL
#define VIA_PCR_CB1_CONTROL 0x10
1 bit
VIA_PCR_CB1_NEG_ACTIVE_EDGE
#define VIA_PCR_CB1_NEG_ACTIVE_EDGE 0x00
bit
VIA_PCR_CB1_POS_ACTIVE_EDGE
#define VIA_PCR_CB1_POS_ACTIVE_EDGE 0x10
bit
VIA_PCR_CB2_CONTROL
#define VIA_PCR_CB2_CONTROL 0xE0
3 bits
VIA_PCR_CB2_HANDSHAKE_OUTPUT
#define VIA_PCR_CB2_HANDSHAKE_OUTPUT 0x80
If INDEPENDENT_INTERRUPT is set, "reading or writing ORB does not clear the CB2 interrupt flag".
3 bits
VIA_PCR_CB2_HIGH_OUTPUT
#define VIA_PCR_CB2_HIGH_OUTPUT 0xE0
3 bits
VIA_PCR_CB2_I_OR_O
#define VIA_PCR_CB2_I_OR_O 0x80
bit
VIA_PCR_CB2_INDEPENDENT_INTERRUPT
#define VIA_PCR_CB2_INDEPENDENT_INTERRUPT 0x20
bit
VIA_PCR_CB2_INPUT
#define VIA_PCR_CB2_INPUT 0x00
bit
VIA_PCR_CB2_INPUT_NEG_ACTIVE_EDGE
#define VIA_PCR_CB2_INPUT_NEG_ACTIVE_EDGE 0x00
bit
VIA_PCR_CB2_INPUT_POS_ACTIVE_EDGE
#define VIA_PCR_CB2_INPUT_POS_ACTIVE_EDGE 0x40
bit
VIA_PCR_CB2_LOW_OUTPUT
#define VIA_PCR_CB2_LOW_OUTPUT 0xC0
3 bits
VIA_PCR_CB2_PULSE_OUTPUT
#define VIA_PCR_CB2_PULSE_OUTPUT 0xA0
3 bits
VIA_PRA
#define VIA_PRA 1
Port A.
VIA_PRA_NHS
#define VIA_PRA_NHS 15
Port A with no handshake.
VIA_PRB
#define VIA_PRB 0
MOS 6522 registers.
Port B
VIA_SIG_CA1
#define VIA_SIG_CA1 0
Signal values (for signaling edges on the control lines)
VIA_SIG_CA2
#define VIA_SIG_CA2 1
VIA_SIG_CB1
#define VIA_SIG_CB1 2
VIA_SIG_CB2
#define VIA_SIG_CB2 3
VIA_SIG_FALL
#define VIA_SIG_FALL 0
VIA_SIG_RISE
#define VIA_SIG_RISE 1
VIA_SR
#define VIA_SR 10
Serial port shift register.
VIA_T1CH
#define VIA_T1CH 5
Timer 1 count high.
VIA_T1CL
#define VIA_T1CL 4
Timer 1 count low.
VIA_T1LH
#define VIA_T1LH 7
Timer 1 latch high.
VIA_T1LL
#define VIA_T1LL 6
Timer 1 latch low.
VIA_T2CH
#define VIA_T2CH 9
Timer 2 count high - read only.
VIA_T2CL
#define VIA_T2CL 8
Timer 2 count low - read only.
VIA_T2LH
#define VIA_T2LH 9
Timer 2 latch high - write only.
VIA_T2LL
#define VIA_T2LL 8
Timer 2 latch low - write only.
Typedef Documentation
via_context_t
typedef struct via_context_s via_context_t
Function Documentation
viacore_disable()
void viacore_disable (struct via_context_s * via_context)
Referenced by iec_drive_reset().
viacore_dump()
int viacore_dump (via_context_t * via_context)
< Port A
< Data direction register for port A
< Port A with no handshake
< Port B
< Data direction register for port B
< Timer 1 count low
< Timer 1 count high
< Timer 1 latch low
< Timer 1 latch high
< Timer 2 count low - read only
< Timer 2 count high - read only
< Timer 2 latch low - write only
< Auxiliary control register
< Peripheral control register
< Interrupt flag register
< Interrupt control register
< Serial port shift register
< Auxiliary control register
< Auxiliary control register
Referenced by drivemem_ioreg_list_get(), via1d1541_dump(), and via4000_dump().
viacore_init()
void viacore_init (struct via_context_s * via_context, struct alarm_context_s * alarm_context, struct interrupt_cpu_status_s * int_status)
Referenced by cmdhd_init(), via1d1541_init(), and via4000_init().
viacore_peek()
uint8_t viacore_peek (via_context_t * via_context, uint16_t addr)
return value of a register without side effects
Todo:
FIXME: this is buggy/incomplete
< Port A
< Port A with no handshake
Todo:
FIXME: side effects ?
< Port B
Todo:
FIXME: side effects ?
< Data direction register for port B
< Port B
< Data direction register for port B
< Auxiliary control register
< Data direction register for port A
< Data direction register for port B
< Timer 1 count low
< Timer 1 count high
< Timer 1 latch low
< Timer 1 latch high
< Timer 2 count low - read only
< Timer 2 count high - read only
< Interrupt flag register
< Interrupt control register
< Peripheral control register
< Auxiliary control register
< Serial port shift register
Referenced by via1d1541_peek(), via4000_peek(), and viacore_dump().
viacore_read()
uint8_t viacore_read (struct via_context_s * via_context, uint16_t addr)
< Port B
< Timer 1 count low
< Interrupt control register
< Port A
< Handshake
< Peripheral control register
< Handshake
< Peripheral control register
< Peripheral control register
< Handshake
< Handshake
< Port A with no handshake
< Port B
< Handshake
< Peripheral control register
< Handshake
< Handshake
< Handshake
< Data direction register for port B
< Port B
< Data direction register for port B
< Auxiliary control register
< Timer 1 count low
< Timer 1 underflow
< Timer 1 count high
< Timer 2 count low - read only
< Timer 2 underflow
< Timer 2 count high - read only
< Serial port shift register
< Shift Register completion
< Shift Register completion
< Interrupt flag register
< Interrupt control register
Referenced by cmdhd_read(), via1d1541_read(), and via4000_read().
viacore_reset()
void viacore_reset (struct via_context_s * via_context)
Referenced by cmdhd_reset(), and iec_drive_reset().
viacore_set_cb1()
void viacore_set_cb1 (struct via_context_s * via_context, bool data)
Todo:
FIXME: Is this the right way to start shifting a byte?
< Serial port shift register
< Serial port shift register
< Serial port shift register
Todo:
the case of VIA_ACR_SR_OUT_CB1 0x1C mode 7 Shift out under control of an External Pulse which happens on the falling edge of CB1. (maybe keep separate cb1_drives_shifting flag?) From http://forum.6502.org/viewtopic.php?f=4&t=7241&start=15#p94001 The CB1 pad also works as the shift clock from/to the outerworld when enabling "10) shift register", and that's why we have another (conceptually different) edge detector sensing the CB1 pad, gated with PHI0=1 AND PHI2=1.
If ACR4=0, the shift register shifts in, and the detector scans for CB1 rising edge. If ACR4=1, the shift register shifts out, and the detector scans for CB1 falling edge.
Low_active signal SR_CB1_DET# generated by the detector tells "22) shift register control" to shift/count the next Bit.
< Peripheral control register
< 1 bit
< bit
< Peripheral control register
< Handshake
Referenced by viacore_signal().
viacore_set_cb2()
void viacore_set_cb2 (struct via_context_s * via_context, bool data)
< Peripheral control register
< bit
< Handshake
Referenced by viacore_signal().
viacore_set_sr()
void viacore_set_sr (via_context_t * via_context, uint8_t data)
WARNING: this is a hack.
WARNING: this is a hack.
< Auxiliary control register
< Auxiliary control register
< Serial port shift register
Todo:
Setting VIA_IM_SR may need a delay of 1 clock
< Shift Register completion
Referenced by c64fastiec_fast_cpu_write(), and viacore_set_cb1().
viacore_setup_context()
void viacore_setup_context (struct via_context_s * via_context)
Referenced by cmdhd_setup_context(), via1d1541_setup_context(), and via4000_setup_context().
viacore_shutdown()
void viacore_shutdown (struct via_context_s * via_context)
Referenced by cmdhd_shutdown(), and iec_drive_shutdown().
viacore_signal()
void viacore_signal (struct via_context_s * via_context, int line, int edge)
< Peripheral control register
< 1 bit
< Peripheral control register
< Handshake
< Peripheral control register
< bit
< bit
< Peripheral control register
< Handshake
Referenced by iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), iecbus_cpu_write_conf3(), and parallel_cable_cpu_pulse().
viacore_snapshot_read_module()
int viacore_snapshot_read_module (struct via_context_s * via_context, struct snapshot_s * s)
Todo:
load from snapshot
< Port A
< Data direction register for port A
< Port B
< Data direction register for port B
< Timer 2 latch low - write only
< Timer 2 latch high - write only
< Serial port shift register
< Auxiliary control register
< Peripheral control register
< Data direction register for port A
< Port A
< Data direction register for port A
< Data direction register for port B
< Port B
< Data direction register for port B
< Timer 1 latch low
< Timer 1 latch high
< Auxiliary control register
< Auxiliary control register
< Auxiliary control register
Todo:
FIXME: SR alarm
< Auxiliary control register
< Peripheral control register
< Serial port shift register
< Auxiliary control register
Referenced by cmdhd_snapshot_read_module(), and iec_drive_snapshot_read().
viacore_snapshot_write_module()
int viacore_snapshot_write_module (via_context_t * via_context, snapshot_t * s)
FIXME!!! Error check.
< Port A
< Data direction register for port A
< Port B
< Data direction register for port B
< Timer 2 latch low - write only
< Timer 2 latch high - write only
< Serial port shift register
< Auxiliary control register
< Peripheral control register
Referenced by cmdhd_snapshot_write_module(), and iec_drive_snapshot_write().
viacore_store()
void viacore_store (struct via_context_s * via_context, uint16_t addr, uint8_t data)
< Port B
< Timer 1 count low
< Interrupt control register
< Port A
< Handshake
< Peripheral control register
< Handshake
< Peripheral control register
< Peripheral control register
< Handshake
< Handshake
< Port A with no handshake
< Port A with no handshake
< Port A
< Data direction register for port A
< Port A
< Data direction register for port A
< Port B
< Handshake
< Peripheral control register
< Handshake
< Peripheral control register
< Peripheral control register
Todo:
FIXME: This pulse is a bit short...
< Handshake
< Handshake
< Data direction register for port B
< Port B
< Data direction register for port B
< Auxiliary control register
< Serial port shift register
< Shift Register completion
< Shift Register completion
< Timer 1 count low
< Timer 1 latch low
< Timer 1 latch low
< Timer 1 count high
< Timer 1 latch high
< Timer 1 underflow
< Timer 1 latch high
< Timer 1 underflow
< Timer 2 latch low - write only
< Timer 2 latch low - write only
< Timer 2 count high - read only
< Timer 2 latch high - write only
< Timer 2 latch low - write only
< Auxiliary control register
< Timer 2 underflow
< Interrupt flag register
Todo:
FIXME: clearing any timer interrupt should set the relevant timer alarm. (It is unclear what was meant with that...
< Interrupt control register
< Control Bit
< Auxiliary control register
< Auxiliary control register
< Auxiliary control register
< Shift Register completion
< Shift Register completion
< Peripheral control register
< Auxiliary control register
< Auxiliary control register
< SR modes 0x04, 0x14, 0x10
Todo:
Out not emulated
< Peripheral control register
< 3 bits
< 3 bits
< 3 bits
< 3 bits
Todo:
FIXME: is this correct if handshake is already active?
< Auxiliary control register
Referenced by cmdhd_store(), via1d1541_store(), via4000_store(), and viacore_store().