x128: monitor/mon_disassemble.h File Reference
mon_disassemble.h File Reference
#include "montypes.h"
#include "types.h"
Functions
const char * mon_disassemble_to_string_ex (MEMSPACE, unsigned int addr, unsigned int x, unsigned int p1, unsigned int p2, unsigned int p3, int hex_mode, unsigned *len)
void mon_disassemble_with_regdump (MEMSPACE mem, unsigned int addr)
void mon_disassemble_lines (MON_ADDR start_addr, MON_ADDR end_addr)
Function Documentation
mon_disassemble_lines()
void mon_disassemble_lines (MON_ADDR start_addr, MON_ADDR end_addr)
mon_disassemble_to_string_ex()
const char * mon_disassemble_to_string_ex (MEMSPACE memspace, unsigned int addr, unsigned int x, unsigned int p1, unsigned int p2, unsigned int p3, int hex_mode, unsigned * len)
Referenced by mon_disassemble_oneline(), and mon_disassemble_with_label().
mon_disassemble_with_regdump()
void mon_disassemble_with_regdump (MEMSPACE mem, unsigned int addr)
Referenced by mon_breakpoint_check_checkpoint(), and monitor_open().