x128: fileio/p00.c File Reference
p00.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include "archdep.h"
#include "cbmdos.h"
#include "fileio.h"
#include "lib.h"
#include "log.h"
#include "p00.h"
#include "rawfile.h"
#include "types.h"
#include "util.h"
Macros
#define P00_HDR_MAGIC_OFFSET 0
#define P00_HDR_MAGIC_LEN 8
#define P00_HDR_CBMNAME_OFFSET 8
#define P00_HDR_CBMNAME_LEN 17
#define P00_HDR_RECORDSIZE_OFFSET 25
#define P00_HDR_RECORDSIZE_LEN 1
#define P00_HDR_LEN 26
Functions
static int p00_check_name (const char *name)
static int p00_read_header (struct rawfile_info_s *info, uint8_t *cbmname_return, int *recsize_return)
static int p00_write_header (struct rawfile_info_s *info, const uint8_t *cbmname, uint8_t recsize)
static void p00_pad_a0 (uint8_t *slot)
static char * p00_file_find (const char *file_name, const char *path)
static size_t p00_eliminate_char_p00 (char *filename, int pos)
static int p00_reduce_filename_p00 (char *filename, int len)
static char * p00_evaluate_name (const char *name, int length)
char * p00_filename_create (const char *file_name, unsigned int type)
static char * p00_file_create (const char *file_name, const char *path, unsigned int type)
fileio_info_t * p00_open (const char *file_name, const char *path, unsigned int command, unsigned int open_type, int *reclenp)
void p00_close (fileio_info_t *info)
unsigned int p00_read (fileio_info_t *info, uint8_t *buf, unsigned int len)
unsigned int p00_write (fileio_info_t *info, uint8_t *buf, unsigned int len)
unsigned int p00_ferror (fileio_info_t *info)
unsigned int p00_rename (const char *src_name, const char *dst_name, const char *path)
unsigned int p00_scratch (const char *file_name, const char *path)
unsigned int p00_get_bytes_left (struct fileio_info_s *info)
unsigned int p00_seek (struct fileio_info_s *info, off_t offset, int whence)
unsigned int p00_tell (struct fileio_info_s *info)
Variables
static const unsigned char p00_hdr_magic_string [8] = "C64File"
Macro Definition Documentation
P00_HDR_CBMNAME_LEN
#define P00_HDR_CBMNAME_LEN 17
P00_HDR_CBMNAME_OFFSET
#define P00_HDR_CBMNAME_OFFSET 8
P00_HDR_LEN
#define P00_HDR_LEN 26
P00_HDR_MAGIC_LEN
#define P00_HDR_MAGIC_LEN 8
P00_HDR_MAGIC_OFFSET
#define P00_HDR_MAGIC_OFFSET 0
P00_HDR_RECORDSIZE_LEN
#define P00_HDR_RECORDSIZE_LEN 1
P00_HDR_RECORDSIZE_OFFSET
#define P00_HDR_RECORDSIZE_OFFSET 25
Function Documentation
p00_check_name()
static int p00_check_name (const char * name) static
Todo:
FIXME: There should be an enum for file types.
< should match FILEIO_TYPE_xxx
Referenced by p00_file_find(), p00_open(), and p00_rename().
p00_close()
void p00_close (fileio_info_t * info)
Referenced by fileio_close().
p00_eliminate_char_p00()
static size_t p00_eliminate_char_p00 (char * filename, int pos) static
Referenced by p00_reduce_filename_p00().
p00_evaluate_name()
static char * p00_evaluate_name (const char * name, int length) static
Referenced by p00_filename_create().
p00_ferror()
unsigned int p00_ferror (fileio_info_t * info)
Referenced by fileio_ferror().
p00_file_create()
static char * p00_file_create (const char * file_name, const char * path, unsigned int type) static
Referenced by p00_open(), and p00_rename().
p00_file_find()
static char * p00_file_find (const char * file_name, const char * path) static
Referenced by p00_open(), p00_rename(), and p00_scratch().
p00_filename_create()
char * p00_filename_create (const char * file_name, unsigned int type)
< should match CBMDOS_FT_xxx
Referenced by extract_cmd_common(), and p00_file_create().
p00_get_bytes_left()
unsigned int p00_get_bytes_left (struct fileio_info_s * info)
Referenced by fileio_get_bytes_left().
p00_open()
fileio_info_t * p00_open (const char * file_name, const char * path, unsigned int command, unsigned int open_type, int * reclenp)
< works with directories
< Will not overwrite existing file
< Overwrites existing file, if any
< Will not overwrite existing file
< works with directories
< Will not overwrite existing file
< Overwrites existing file, if any
Referenced by fileio_open().
p00_pad_a0()
static void p00_pad_a0 (uint8_t * slot) static
Referenced by p00_file_find().
p00_read()
unsigned int p00_read (fileio_info_t * info, uint8_t * buf, unsigned int len)
Referenced by fileio_read().
p00_read_header()
static int p00_read_header (struct rawfile_info_s * info, uint8_t * cbmname_return, int * recsize_return) static
Referenced by p00_file_find(), and p00_open().
p00_reduce_filename_p00()
static int p00_reduce_filename_p00 (char * filename, int len) static
Referenced by p00_evaluate_name().
p00_rename()
unsigned int p00_rename (const char * src_name, const char * dst_name, const char * path)
Referenced by fileio_rename().
p00_scratch()
unsigned int p00_scratch (const char * file_name, const char * path)
Referenced by fileio_scratch().
p00_seek()
unsigned int p00_seek (struct fileio_info_s * info, off_t offset, int whence)
Referenced by fileio_seek().
p00_tell()
unsigned int p00_tell (struct fileio_info_s * info)
Referenced by fileio_tell().
p00_write()
unsigned int p00_write (fileio_info_t * info, uint8_t * buf, unsigned int len)
Referenced by fileio_write().
p00_write_header()
static int p00_write_header (struct rawfile_info_s * info, const uint8_t * cbmname, uint8_t recsize) static
Referenced by p00_open(), and p00_rename().
Variable Documentation
p00_hdr_magic_string
const unsigned char p00_hdr_magic_string[8] = "C64File" static
Referenced by p00_read_header(), and p00_write_header().