x128: drive/driverom.c File Reference
driverom.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "drive.h"
#include "drivetypes.h"
#include "driverom.h"
#include "log.h"
#include "machine-bus.h"
#include "machine-drive.h"
#include "resources.h"
#include "sysfile.h"
#include "traps.h"
#include "types.h"
#include "snapshot.h"
Macros
#define DBG(x)
#define ROM_SNAP_MAJOR 1
#define ROM_SNAP_MINOR 0
Functions
int driverom_load (const char *resource_name, uint8_t *drive_rom, unsigned int *loaded, int min, int max, const char *name, unsigned int type, unsigned int *size)
int driverom_load_images (void)
void driverom_initialize_traps (diskunit_context_t *unit)
int driverom_snapshot_write (snapshot_t *s, const drive_t *drive)
int driverom_snapshot_read (snapshot_t *s, drive_t *drive)
void driverom_init (void)
Variables
static log_t driverom_log
patch for 1541 driverom at $EAAF
static int drive_rom_load_ok = 0
If nonzero, we are far enough in init that we can load ROMs.
Macro Definition Documentation
DBG
#define DBG (x)
ROM_SNAP_MAJOR
#define ROM_SNAP_MAJOR 1
ROM_SNAP_MINOR
#define ROM_SNAP_MINOR 0
Function Documentation
driverom_init()
void driverom_init (void)
Referenced by drive_init().
driverom_initialize_traps()
void driverom_initialize_traps (diskunit_context_t * unit)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
Referenced by drive_init(), drive_resources_type(), drive_snapshot_read_module(), driverom_load(), and set_drive_idling_method().
driverom_load()
int driverom_load (const char * resource_name, uint8_t * drive_rom, unsigned int * loaded, int min, int max, const char * name, unsigned int type, unsigned int * size)
Referenced by iec128dcrrom_load_1571cr(), iecrom_load_1540(), iecrom_load_1541(), iecrom_load_1541ii(), iecrom_load_1570(), iecrom_load_1571(), iecrom_load_1581(), iecrom_load_2000(), iecrom_load_4000(), iecrom_load_CMDHD(), ieeerom_load_1001(), ieeerom_load_2031(), ieeerom_load_2040(), ieeerom_load_3040(), ieeerom_load_4040(), ieeerom_load_9000(), and tcbmrom_load_1551().
driverom_load_images()
int driverom_load_images (void)
Referenced by drive_init().
driverom_snapshot_read()
int driverom_snapshot_read (snapshot_t * s, drive_t * drive)
< ASCII for HD
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< same as ROM8050 and ROM8250 !
< DOS 3.0 hard drive
Referenced by drive_snapshot_read_module().
driverom_snapshot_write()
int driverom_snapshot_write (snapshot_t * s, const drive_t * drive)
Todo:
pass diskunit_context_t as parameter instead
< ASCII for HD
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< same as ROM8050 and ROM8250 !
< DOS 3.0 hard drive
Referenced by drive_snapshot_write_module().
Variable Documentation
drive_rom_load_ok
int drive_rom_load_ok = 0 static
If nonzero, we are far enough in init that we can load ROMs.
Referenced by driverom_load(), and driverom_load_images().
driverom_log
log_t driverom_log static
patch for 1541 driverom at $EAAF
skips RAM and ROM check for fast drive reset
Logging goes here.
Referenced by driverom_init(), driverom_load(), driverom_load_images(), and driverom_snapshot_read().