vsid: arch/shared/archdep_filename_parameter.c File Reference
archdep_filename_parameter.c File Reference
Quote filename parameters on systems that need it.
#include "vice.h"
#include "archdep_defs.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lib.h"
#include "log.h"
#include "util.h"
#include "archdep_expand_path.h"
#include "archdep_filename_parameter.h"
Functions
char * archdep_filename_parameter (const char *name)
Quote name with double quotes.
Detailed Description
Quote filename parameters on systems that need it.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
archdep_filename_parameter()
char * archdep_filename_parameter (const char * name)
Quote name with double quotes.
Parameters
[in] name string to quote
Returns
quoted (win32) and heap-allocated copy of name
Referenced by try_uncompress_archive(), try_uncompress_lynx(), try_uncompress_with_bzip(), try_uncompress_with_gzip(), try_uncompress_with_tzx(), and try_uncompress_zipcode().