vsid: network.h File Reference
network.h File Reference
Macros
#define NETWORK_CONTROL_KEYB (1 << 0)
#define NETWORK_CONTROL_JOY1 (1 << 1)
#define NETWORK_CONTROL_JOY2 (1 << 2)
#define NETWORK_CONTROL_DEVC (1 << 3)
#define NETWORK_CONTROL_RSRC (1 << 4)
#define NETWORK_CONTROL_CLIENTOFFSET 8
#define NETWORK_CONTROL_DEFAULT
Enumerations
enum network_mode_t {
NETWORK_IDLE ,
NETWORK_SERVER ,
NETWORK_SERVER_CONNECTED ,
NETWORK_CLIENT
}
Functions
int network_resources_init (void)
int network_cmdline_options_init (void)
int network_start_server (void)
int network_connect_client (void)
void network_disconnect (void)
void network_suspend (void)
void network_hook (void)
int network_connected (void)
int network_get_mode (void)
void network_event_record (unsigned int type, void *data, unsigned int size)
void network_attach_image (unsigned int unit, const char *filename)
void network_shutdown (void)
Macro Definition Documentation
NETWORK_CONTROL_CLIENTOFFSET
#define NETWORK_CONTROL_CLIENTOFFSET 8
NETWORK_CONTROL_DEFAULT
#define NETWORK_CONTROL_DEFAULT
Value:
    ( NETWORK_CONTROL_KEYB      \
      | NETWORK_CONTROL_JOY2    \
      | NETWORK_CONTROL_RSRC    \
      | NETWORK_CONTROL_DEVC    \
      | (NETWORK_CONTROL_KEYB   \
      | NETWORK_CONTROL_JOY1)   \
        << NETWORK_CONTROL_CLIENTOFFSET)
NETWORK_CONTROL_DEVC
#define NETWORK_CONTROL_DEVC (1 << 3)
NETWORK_CONTROL_JOY1
#define NETWORK_CONTROL_JOY1 (1 << 1)
NETWORK_CONTROL_JOY2
#define NETWORK_CONTROL_JOY2 (1 << 2)
NETWORK_CONTROL_KEYB
#define NETWORK_CONTROL_KEYB (1 << 0)
NETWORK_CONTROL_RSRC
#define NETWORK_CONTROL_RSRC (1 << 4)
Enumeration Type Documentation
network_mode_t
enum network_mode_t
Enumerator
NETWORK_IDLE
NETWORK_SERVER
NETWORK_SERVER_CONNECTED
NETWORK_CLIENT
Function Documentation
network_attach_image()
void network_attach_image (unsigned int unit, const char * filename)
Todo:
drive 1?
Referenced by file_system_attach_disk(), and tape_image_attach().
network_cmdline_options_init()
int network_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
network_connect_client()
int network_connect_client (void)
< write mode (binary)
Referenced by on_netplay_notify_active().
network_connected()
int network_connected (void)
Referenced by autostart_autodetect(), autostart_disk(), autostart_prg(), autostart_snapshot(), autostart_tape(), file_system_attach_disk(), file_system_detach_disk(), kbd_key_pressed(), keyboard_key_clear(), keyboard_latch_matrix(), keyboard_restore_pressed(), keyboard_restore_released(), machine_trigger_reset(), network_hook(), network_shutdown(), network_suspend(), resources_set_int(), resources_set_string(), resources_set_value(), resources_toggle(), tape_image_attach(), tape_image_detach(), and vsync_do_vsync().
network_disconnect()
void network_disconnect (void)
Referenced by network_hook_connected_receive(), network_hook_connected_send(), network_shutdown(), and on_netplay_notify_active().
network_event_record()
void network_event_record (unsigned int type, void * data, unsigned int size)
Referenced by file_system_detach_disk(), kbd_key_pressed(), keyboard_key_clear(), keyboard_restore_pressed(), keyboard_restore_released(), machine_trigger_reset(), network_event_record_sync_test(), network_hook_connected_send(), resource_record_event(), and tape_image_detach().
network_get_mode()
int network_get_mode (void)
Referenced by create_combo_box(), create_netplay_enable_widget(), netplay_update_status(), network_attach_image(), network_event_record(), on_combo_changed(), on_netplay_notify_active(), resources_set_int(), resources_set_string(), resources_set_value(), and resources_toggle().
network_hook()
void network_hook (void)
Referenced by machine_vsync_hook().
network_resources_init()
int network_resources_init (void)
Referenced by machine_resources_init().
network_shutdown()
void network_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
network_start_server()
int network_start_server (void)
Referenced by on_netplay_notify_active().
network_suspend()
void network_suspend (void)
Referenced by vsync_suspend_speed_eval().