x128: monitor/mon_drive.c File Reference
mon_drive.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "attach.h"
#include "charset.h"
#include "diskcontents-block.h"
#include "diskimage.h"
#include "imagecontents.h"
#include "lib.h"
#include "machine-bus.h"
#include "montypes.h"
#include "mon_drive.h"
#include "mon_util.h"
#include "resources.h"
#include "serial.h"
#include "types.h"
#include "uimon.h"
#include "vdrive.h"
#include "vdrive-command.h"
Macros
#define ADDR_LIMIT(x) ((uint16_t)(addr_mask(x)))
Functions
void mon_drive_block_cmd (int op, int track, int sector, MON_ADDR addr)
void mon_drive_execute_disk_cmd (char *cmd)
int mon_drive_is_fsdevice (int drive_unit)
check if a drive is associated with a filesystem/directory
const char * mon_drive_get_fsdevice_path (int drive_unit)
void mon_drive_list (int drive_unit)
Macro Definition Documentation
ADDR_LIMIT
#define ADDR_LIMIT (x) ((uint16_t)(addr_mask(x)))
Function Documentation
mon_drive_block_cmd()
void mon_drive_block_cmd (int op, int track, int sector, MON_ADDR addr)
Todo:
drive 1?
mon_drive_execute_disk_cmd()
void mon_drive_execute_disk_cmd (char * cmd)
Todo:
FIXME: Unit/Drive?
mon_drive_get_fsdevice_path()
const char * mon_drive_get_fsdevice_path (int drive_unit)
Todo:
FIXME: this function should perhaps live elsewhere
Referenced by mon_drive_list(), and mon_file_open().
mon_drive_is_fsdevice()
int mon_drive_is_fsdevice (int drive_unit)
check if a drive is associated with a filesystem/directory
Todo:
FIXME: this function should perhaps live elsewhere
Todo:
FIXME: unsure if this check really works as advertised
< filesystem
Referenced by mon_drive_get_fsdevice_path().
mon_drive_list()
void mon_drive_list (int drive_unit)
Todo:
drive 1?
< return string in PETSCII form
Todo:
FIXME: the string should ideally be shown in reverse
Todo:
FIXME: do not use strlen
< return string in PETSCII form
Todo:
FIXME: do not use strlen