vsid: c64/c64datasette.c File Reference
c64datasette.c File Reference
#include "vice.h"
#include "c64.h"
#include "c64mem.h"
#include "cia.h"
#include "datasette.h"
#include "tapeport.h"
Functions
void machine_trigger_flux_change (int port, unsigned int on)
void machine_set_tape_sense (int port, int sense)
void machine_set_tape_write_in (int port, int val)
void machine_set_tape_motor_in (int port, int val)
Function Documentation
machine_set_tape_motor_in()
void machine_set_tape_motor_in (int port, int val)
Referenced by c64_diag_586220_store_tapeport(), and tapeport_set_motor_in().
machine_set_tape_sense()
void machine_set_tape_sense (int port, int sense)
Referenced by c64_diag_586220_store_tapeport(), and tapeport_set_tape_sense().
machine_set_tape_write_in()
void machine_set_tape_write_in (int port, int val)
Referenced by c64_diag_586220_store_tapeport(), and tapeport_set_write_in().
machine_trigger_flux_change()
void machine_trigger_flux_change (int port, unsigned int on)
Referenced by c64_diag_586220_store_tapeport(), and tapeport_trigger_flux_change().