vsid: sha1.h File Reference
sha1.h File Reference
#include <stdint.h>
Data Structures
struct SHA1_CTX
Functions
void SHA1Transform (uint32_t state[5], const unsigned char buffer[64])
void SHA1Init (SHA1_CTX *context)
SHA1Init - Initialize new context.
void SHA1Update (SHA1_CTX *context, const unsigned char *data, uint32_t len)
Run your data through this.
void SHA1Final (unsigned char digest[20], SHA1_CTX *context)
Add padding and return the message digest.
void SHA1 (unsigned char *hash_out, const unsigned char *str, uint32_t len)
void SHA1String (char *hash_string_out, const unsigned char *str, uint32_t len)
Function Documentation
SHA1()
void SHA1 (unsigned char * hash_out, const unsigned char * str, uint32_t len)
Referenced by SHA1String().
SHA1Final()
void SHA1Final (unsigned char digest[20], SHA1_CTX * context)
Add padding and return the message digest.
Referenced by SHA1().
SHA1Init()
void SHA1Init (SHA1_CTX * context)
SHA1Init - Initialize new context.
Referenced by SHA1().
SHA1String()
void SHA1String (char * hash_string_out, const unsigned char * str, uint32_t len)
Referenced by c64rom_get_kernal_chksum_id().
SHA1Transform()
void SHA1Transform (uint32_t state[5], const unsigned char buffer[64])
Referenced by SHA1Update().
SHA1Update()
void SHA1Update (SHA1_CTX * context, const unsigned char * data, uint32_t len)
Run your data through this.
Referenced by SHA1(), and SHA1Final().