vsid: c64/vsid.c File Reference
vsid.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "c64-resources.h"
#include "c64-snapshot.h"
#include "c64.h"
#include "c64cia.h"
#include "c64gluelogic.h"
#include "c64mem.h"
#include "cia.h"
#include "debug.h"
#include "drive.h"
#include "imagecontents.h"
#include "init.h"
#include "joystick.h"
#include "kbdbuf.h"
#include "log.h"
#include "machine-drive.h"
#include "machine-video.h"
#include "machine.h"
#include "maincpu.h"
#include "monitor.h"
#include "psid.h"
#include "resources.h"
#include "screenshot.h"
#include "sid-cmdline-options.h"
#include "sid-resources.h"
#include "sid.h"
#include "vicii.h"
#include "vicii-mem.h"
#include "video.h"
#include "vsid-cmdline-options.h"
#include "vsidui.h"
#include "vsid-debugcart.h"
#include "vsync.h"
Functions
static void machine_vsync_hook (void)
This hook is called at the end of every frame.
int machine_resources_init (void)
void machine_resources_shutdown (void)
int machine_cmdline_options_init (void)
C64-specific command-line option initialization.
static void c64_monitor_init (void)
void machine_setup_context (void)
Initialize the machine.
int machine_specific_init (void)
C64-specific initialization.
void machine_specific_reset (void)
C64-specific reset sequence.
void machine_specific_powerup (void)
void machine_specific_shutdown (void)
void machine_handle_pending_alarms (CLOCK num_write_cycles)
handle pending interrupts - needed by libsid.a.
void machine_set_restore_key (int v)
Set the state of the RESTORE key (!=0 means pressed)
int machine_has_restore_key (void)
returns 1 if key is present
long machine_get_cycles_per_second (void)
Get the number of CPU cylces per second.
long machine_get_cycles_per_frame (void)
Get the number of CPU cylces per frame.
void machine_get_line_cycle (unsigned int *line, unsigned int *cycle, int *half_cycle)
Get current line and cycle.
void machine_change_timing (int timeval, int powerfreq, int border_mode)
Change the timing parameters of the maching (for example PAL/NTSC).
int machine_write_snapshot (const char *name, int save_roms, int save_disks, int event_mode)
Write a snapshot.
int machine_read_snapshot (const char *name, int event_mode)
Read a snapshot.
int machine_autodetect_psid (const char *name)
Autodetect PSID file.
void machine_play_psid (int tune)
int machine_screenshot (screenshot_t *screenshot, struct video_canvas_s *canvas)
int machine_canvas_async_refresh (struct canvas_refresh_s *refresh, struct video_canvas_s *canvas)
void machine_update_memory_ptrs (void)
Update memory pointers if memory mapping has changed.
struct image_contents_s * machine_diskcontents_bus_read (unsigned int unit)
uint8_t machine_tape_type_default (void)
uint8_t machine_tape_behaviour (void)
int machine_addr_in_ram (unsigned int addr)
Check if address is in RAM (for autostart)
const char * machine_get_name (void)
Get "real" name for machine.
char * machine_get_keyboard_type_name (int type)
Variables
machine_context_t machine_context
const char machine_name [] = "C64"
The following stuff must be defined once per every emulated CBM machine.
char * psid_autostart_image = NULL
PSID file loaded from commandline.
static log_t c64_log = ((log_t)-1)
static machine_timing_t machine_timing
static int vsid_autostart_delay = 0
static uint16_t vsid_autostart_load_addr = 0
static uint8_t * vsid_autostart_data = NULL
static uint16_t vsid_autostart_length = 0
Function Documentation
c64_monitor_init()
static void c64_monitor_init (void) static
Referenced by machine_specific_init().
machine_addr_in_ram()
int machine_addr_in_ram (unsigned int addr)
Check if address is in RAM (for autostart)
Check if address is in RAM (for autostart)
Referenced by check_rom_area().
machine_autodetect_psid()
int machine_autodetect_psid (const char * name)
Autodetect PSID file.
Todo:
FIXME: those two shouldnt be here anymore
Todo:
FIXME: show error message box
Referenced by initcmdline_check_psid(), and ui_vsid_window_load_psid().
machine_canvas_async_refresh()
int machine_canvas_async_refresh (struct canvas_refresh_s * refresh, struct video_canvas_s * canvas)
machine_change_timing()
void machine_change_timing (int timeval, int powerfreq, int border_mode)
Change the timing parameters of the maching (for example PAL/NTSC).
Referenced by on_vsync_set_border_mode(), set_power_freq(), and set_sync_factor().
machine_cmdline_options_init()
int machine_cmdline_options_init (void)
C64-specific command-line option initialization.
Referenced by init_cmdline_options().
machine_diskcontents_bus_read()
struct image_contents_s * machine_diskcontents_bus_read (unsigned int unit)
machine_get_cycles_per_frame()
long machine_get_cycles_per_frame (void)
Get the number of CPU cylces per frame.
Referenced by ffmpegexedrv_init_video(), file_load_sample(), kbd_make_event_timestap(), kbdbuf_flush(), reboot_for_autostart(), sound_set_relative_speed(), and zmbvdrv_init_video().
machine_get_cycles_per_second()
long machine_get_cycles_per_second (void)
Get the number of CPU cylces per second.
This is used in various parts.
Referenced by c64_rsuser_init(), event_alarm_handler(), event_snapshot_read_module(), fastload_mode_init(), fastload_postdelay(), ffmpegexedrv_init_video(), file_load_sample(), print_cycle_time(), reboot_for_autostart(), receive_1bit_callback(), set_acia_ticks(), sound_set_relative_speed(), tapecart_enable(), tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), tapecart_set_mode(), and zmbvdrv_init_video().
machine_get_keyboard_type_name()
char * machine_get_keyboard_type_name (int type)
Referenced by keyboard_get_keymap_name().
machine_get_line_cycle()
void machine_get_line_cycle (unsigned int * line, unsigned int * cycle, int * half_cycle)
Get current line and cycle.
Referenced by maincpu_monitor_interface_get().
machine_get_name()
const char * machine_get_name (void)
Get "real" name for machine.
May differ from machine_name.
machine_handle_pending_alarms()
void machine_handle_pending_alarms (CLOCK num_write_cycles)
handle pending interrupts - needed by libsid.a.
Referenced by sid_read_chip(), sid_store_chip(), and zero_store().
machine_has_restore_key()
int machine_has_restore_key (void)
returns 1 if key is present
Referenced by key_restore1_pressed(), and key_restore2_pressed().
machine_play_psid()
void machine_play_psid (int tune)
Referenced by play_current_tune(), psid_play_action(), psid_stop_action(), select_tune_from_menu(), and ui_vsid_window_load_psid().
machine_read_snapshot()
int machine_read_snapshot (const char * name, int even_mode)
Read a snapshot.
Referenced by event_playback_start_trap(), event_record_reset_milestone_trap(), event_record_start_trap(), load_snapshot_filename_callback(), load_snapshot_trap(), mon_read_snapshot(), network_client_connect_trap(), and quickload_snapshot_trap().
machine_resources_init()
int machine_resources_init (void)
Referenced by init_resources().
machine_resources_shutdown()
void machine_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
machine_screenshot()
int machine_screenshot (screenshot_t * screenshot, struct video_canvas_s * canvas)
Referenced by monitor_binary_process_display_get(), monitor_binary_process_palette_get(), screenshot_record(), and screenshot_save().
machine_set_restore_key()
void machine_set_restore_key (int v)
Set the state of the RESTORE key (!=0 means pressed)
Referenced by keyboard_restore_event_playback(), and restore_alarm_triggered().
machine_setup_context()
void machine_setup_context (void)
Initialize the machine.
Referenced by main_program().
machine_specific_init()
int machine_specific_init (void)
C64-specific initialization.
Referenced by machine_init().
machine_specific_powerup()
void machine_specific_powerup (void)
Referenced by machine_powerup().
machine_specific_reset()
void machine_specific_reset (void)
C64-specific reset sequence.
Todo:
FIXME: whats actually broken here?
Referenced by machine_reset().
machine_specific_shutdown()
void machine_specific_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
machine_tape_behaviour()
uint8_t machine_tape_behaviour (void)
< tape interrupt is falling-edge triggered, normal tape blocks end with a long and a short pulse
< tape interrupt is falling-edge triggered, normal tape blocks end with a long and a short pulse
machine_tape_type_default()
uint8_t machine_tape_type_default (void)
< Binary Program (absolute load, SAVE "",1,1 (VIC-20 and later))
Referenced by default_tape_header_type().
machine_update_memory_ptrs()
void machine_update_memory_ptrs (void)
Update memory pointers if memory mapping has changed.
machine_vsync_hook()
static void machine_vsync_hook (void) static
This hook is called at the end of every frame.
Referenced by machine_specific_init().
machine_write_snapshot()
int machine_write_snapshot (const char * name, int save_roms, int save_disks, int even_mode)
Write a snapshot.
Referenced by event_record_set_milestone_trap(), event_record_start_trap(), event_record_stop_trap(), mon_write_snapshot(), network_server_connect_trap(), quicksave_snapshot_trap(), and save_snapshot_dialog().
Variable Documentation
c64_log
log_t c64_log = ((log_t)-1) static
Referenced by machine_change_timing(), machine_specific_init(), and machine_vsync_hook().
machine_context
machine_context_t machine_context
Todo:
FIXME: remove more unneeded stuff
all iec/drive/printer/cartridge can be removed and replaced by stubs in vsidstubs.c
Referenced by machine_change_timing(), machine_setup_context(), machine_specific_init(), machine_specific_reset(), and machine_specific_shutdown().
machine_name
const char machine_name[] = "C64"
The following stuff must be defined once per every emulated CBM machine.
Name of the machine.
The following stuff must be defined once per every emulated CBM machine.
machine_timing
machine_timing_t machine_timing static
Referenced by machine_change_timing(), machine_get_cycles_per_frame(), machine_get_cycles_per_second(), machine_get_line_cycle(), machine_specific_init(), machine_specific_reset(), and machine_vsync_hook().
psid_autostart_image
char* psid_autostart_image = NULL
PSID file loaded from commandline.
Todo:
FIXME: this must be c64 currently, else the roms can not be loaded
The UI needs to attempt to retrieve STIL info for a file "autostarted" from the command line.
Referenced by machine_autodetect_psid(), and vsid_main_widget_create().
vsid_autostart_data
uint8_t* vsid_autostart_data = NULL static
Referenced by machine_specific_reset(), and machine_vsync_hook().
vsid_autostart_delay
int vsid_autostart_delay = 0 static
Referenced by machine_specific_reset(), and machine_vsync_hook().
vsid_autostart_length
uint16_t vsid_autostart_length = 0 static
Referenced by machine_specific_reset(), and machine_vsync_hook().
vsid_autostart_load_addr
uint16_t vsid_autostart_load_addr = 0 static
Referenced by machine_specific_reset(), and machine_vsync_hook().