x128: c128/functionrom.c File Reference
functionrom.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "archdep.h"
#include "bq4830y.h"
#include "c128mem.h"
#include "cmdline.h"
#include "functionrom.h"
#include "lib.h"
#include "resources.h"
#include "types.h"
#include "util.h"
#include "viciitypes.h"
#include "vicii-phi1.h"
#include "cartridge.h"
#include "c64cart.h"
#include "c64cartsystem.h"
#include "ltkernal.h"
#include "ramlink.h"
Macros
#define INTERNAL_FUNCTION_ROM_SIZE 0x8000
Functions
static int functionrom_load_internal (void)
Some prototypes are needed.
static int set_internal_function_rom_enabled (int val, void *param)
static int set_internal_function_rtc_save (int val, void *param)
static int set_internal_function_rom_name (const char *val, void *param)
int functionrom_resources_init (void)
void functionrom_resources_shutdown (void)
int functionrom_cmdline_options_init (void)
uint8_t internal_function_rom_read (uint16_t addr)
uint8_t internal_function_rom_peek (uint16_t addr)
void internal_function_rom_store (uint16_t addr, uint8_t value)
void internal_function_top_shared_store (uint16_t addr, uint8_t value)
Variables
static int internal_function_rom_enabled
Flag: Do we enable the internal function ROM?
static char * internal_function_rom_name = NULL
Name of the internal function ROM.
uint8_t int_function_rom [0x8000]
Image of the internal function ROM.
static int internal_function_rtc_save
Flag: Do we save RTC info when changed?
static rtc_bq4830y_t * rtc1_context = NULL
bq4830y context
static const resource_string_t resources_string []
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
Macro Definition Documentation
INTERNAL_FUNCTION_ROM_SIZE
#define INTERNAL_FUNCTION_ROM_SIZE 0x8000
Function Documentation
functionrom_cmdline_options_init()
int functionrom_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
functionrom_load_internal()
static int functionrom_load_internal (void) static
Some prototypes are needed.
Referenced by set_internal_function_rom_enabled(), and set_internal_function_rom_name().
functionrom_resources_init()
int functionrom_resources_init (void)
Referenced by machine_resources_init().
functionrom_resources_shutdown()
void functionrom_resources_shutdown (void)
Referenced by machine_resources_shutdown().
internal_function_rom_peek()
uint8_t internal_function_rom_peek (uint16_t addr)
Todo:
FIXME: this RTC should have a peek function
return bq4830y_peek(rtc1_context, (uint16_t)(addr & 0x7fff));
Referenced by mem_bank_peek(), mem_peek_with_config_c128(), z80mem_chargen_rom_area_peek(), z80mem_editor_rom_area_peek(), z80mem_hi_rom_area_peek(), and z80mem_mid_rom_area_peek().
internal_function_rom_read()
uint8_t internal_function_rom_read (uint16_t addr)
< ltkernal.c
< ramlink.c
Referenced by c128meminit(), mem_bank_read(), mmu_ffxx_read(), z80mem_chargen_rom_area_read(), z80mem_editor_rom_area_read(), z80mem_hi_rom_area_read(), and z80mem_mid_rom_area_read().
internal_function_rom_store()
void internal_function_rom_store (uint16_t addr, uint8_t value)
< ltkernal.c
Referenced by c128meminit(), z80mem_chargen_rom_area_store(), z80mem_editor_rom_area_store(), z80mem_hi_rom_area_store(), and z80mem_mid_rom_area_store().
internal_function_top_shared_store()
void internal_function_top_shared_store (uint16_t addr, uint8_t value)
Referenced by c128meminit().
set_internal_function_rom_enabled()
static int set_internal_function_rom_enabled (int val, void * param) static
set_internal_function_rom_name()
static int set_internal_function_rom_name (const char * val, void * param) static
set_internal_function_rtc_save()
static int set_internal_function_rtc_save (int val, void * param) static
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-intfrom", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "InternalFunctionName", NULL,
      "<Name>", "Specify name of internal Function ROM image" },
    { "-intfunc", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "InternalFunctionROM", NULL,
      "<Type>", "Type of internal Function ROM: (0: None, 1: ROM, 2: RAM, 3: RTC)" },
    { "-intfuncrtcsave", SET_RESOURCE,  0 ,
      NULL, NULL, "InternalFunctionROMRTCSave", (resource_value_t)1,
      NULL, "Enable saving of the internal function RTC data when changed." },
    { "+intfuncrtcsave", SET_RESOURCE,  0 ,
      NULL, NULL, "InternalFunctionROMRTCSave", (resource_value_t)0,
      NULL, "Disable saving of the internal function RTC data when changed." },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by functionrom_cmdline_options_init().
int_function_rom
uint8_t int_function_rom[0x8000]
Image of the internal function ROM.
Referenced by functionrom_load_internal(), internal_function_rom_peek(), internal_function_rom_read(), internal_function_rom_store(), internal_function_top_shared_store(), and set_internal_function_rom_enabled().
internal_function_rom_enabled
int internal_function_rom_enabled static
Flag: Do we enable the internal function ROM?
Referenced by functionrom_load_internal(), internal_function_rom_peek(), internal_function_rom_read(), internal_function_rom_store(), internal_function_top_shared_store(), and set_internal_function_rom_enabled().
internal_function_rom_name
char* internal_function_rom_name = NULL static
Name of the internal function ROM.
Referenced by functionrom_load_internal(), functionrom_resources_shutdown(), and set_internal_function_rom_name().
internal_function_rtc_save
int internal_function_rtc_save static
Flag: Do we save RTC info when changed?
Referenced by functionrom_resources_shutdown(), set_internal_function_rom_enabled(), and set_internal_function_rtc_save().
resources_int
const resource_int_t resources_int[] static
Initial value:
=
{
    { "InternalFunctionROM", INT_FUNCTION_NONE, RES_EVENT_STRICT, (resource_value_t)0,
      &internal_function_rom_enabled,
      set_internal_function_rom_enabled, NULL },
    { "InternalFunctionROMRTCSave", 0, RES_EVENT_NO, NULL,
      &internal_function_rtc_save,
      set_internal_function_rtc_save, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by functionrom_resources_init().
resources_string
const resource_string_t resources_string[] static
Initial value:
=
{
    { "InternalFunctionName", "", RES_EVENT_NO, NULL,
      &internal_function_rom_name,
      set_internal_function_rom_name, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by functionrom_resources_init().
rtc1_context
rtc_bq4830y_t* rtc1_context = NULL static
bq4830y context
Referenced by functionrom_resources_shutdown(), internal_function_rom_read(), internal_function_rom_store(), internal_function_top_shared_store(), and set_internal_function_rom_enabled().