x128: core/viacore.c File Reference
viacore.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <inttypes.h>
#include "alarm.h"
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "monitor.h"
#include "snapshot.h"
#include "types.h"
#include "via.h"
Macros
#define CHECK_CPU_VS_ALARM_CLOCKS 0
Timer debugging.
#define VIADEBUG 0
#define VIALOG(...)
#define VIALOG2(...)
#define VIALOG9(...)
#define IS_CA2_OUTPUT() ((via_context->via[VIA_PCR] & 0x0c) == 0x0c)
#define IS_CA2_INDINPUT() ((via_context->via[VIA_PCR] & 0x0a) == 0x02)
#define IS_CA2_HANDSHAKE() ((via_context->via[VIA_PCR] & 0x0c) == 0x08)
#define IS_CA2_PULSE_MODE() ((via_context->via[VIA_PCR] & 0x0e) == 0x0A)
#define IS_CA2_TOGGLE_MODE() ((via_context->via[VIA_PCR] & 0x0e) == 0x08)
#define IS_CB2_OUTPUT() ((via_context->via[VIA_PCR] & 0xc0) == 0xc0)
#define IS_CB2_INDINPUT() ((via_context->via[VIA_PCR] & 0xa0) == 0x20)
#define IS_CB2_HANDSHAKE() ((via_context->via[VIA_PCR] & 0xc0) == 0x80)
#define IS_CB2_PULSE_MODE() ((via_context->via[VIA_PCR] & 0xe0) == 0xA0)
#define IS_CB2_TOGGLE_MODE() ((via_context->via[VIA_PCR] & 0xe0) == 0x80)
#define IS_PA_INPUT_LATCH() (via_context->via[VIA_ACR] & 0x01)
#define IS_PB_INPUT_LATCH() (via_context->via[VIA_ACR] & 0x02)
#define IS_SR_SHIFTING_OUT() (((via_context->via[VIA_ACR]) & 0x10))
#define IS_SR_SHIFT_OUT_BY_T2() (((via_context->via[VIA_ACR]) & 0x1c) == 0x14)
#define IS_SR_FREE_RUNNING() (((via_context->via[VIA_ACR]) & 0x1c) == 0x10)
#define IS_SR_SHIFT_IN_BY_EXT(byte) (((byte) & 0x1c) == 0x0C)
#define IS_SR_T2_CONTROLLED(byte) ((((byte) & 0x0c) == 0x04) || (((byte) & 0x1c) == 0x10))
SR modes 0x04, 0x14, 0x10.
#define IS_T2_PULSE_COUNTING(byte) (((byte) & VIA_ACR_T2_CONTROL) == VIA_ACR_T2_COUNTPB6)
#define IS_T2_TIMER(byte) (((byte) & VIA_ACR_T2_CONTROL) == VIA_ACR_T2_TIMER)
#define FULL_CYCLE_2 2
#define TBI_OFFSET 1
#define SR_PHI2_FIRST_OFFSET 3
#define SR_PHI2_NEXT_OFFSET 1
#define VIA_DUMP_VER_MAJOR 2
The name of the modul must be defined before including this file.
#define VIA_DUMP_VER_MINOR 2
Functions
static void viacore_t1_zero_alarm (CLOCK offset, void *data)
static void viacore_t2_zero_alarm (CLOCK offset, void *data)
static void viacore_t2_underflow_alarm (CLOCK offset, void *data)
static void do_shiftregister (CLOCK offset, via_context_t *via_context)
static void schedule_t2_zero_alarm (via_context_t *via_context, CLOCK rclk)
static void viacore_cache_cb12_io_status (via_context_t *via_context)
static void set_cb2_output_state (via_context_t *via_context, uint8_t pcr, int offset)
static void via_restore_int (via_context_t *via_context, int value)
static void update_myviairq_rclk (via_context_t *via_context, CLOCK rclk)
static void update_myviairq (via_context_t *via_context)
static uint16_t viacore_t1 (via_context_t *via_context, CLOCK rclk)
the next two are used in viacore_read()
static uint16_t viacore_t2 (via_context_t *via_context, CLOCK rclk)
static void update_via_t1_latch (via_context_t *via_context, CLOCK rclk)
void viacore_disable (via_context_t *via_context)
void viacore_reset (via_context_t *via_context)
void viacore_signal (via_context_t *via_context, int line, int edge)
static CLOCK alarm_clk (alarm_t *alarm)
static void run_pending_alarms (CLOCK clk, int offset, alarm_context_t *alarm_context)
static int alarm_is_pending (alarm_t *alarm)
static void alarm_set_if_not_pending (alarm_t *alarm, CLOCK cpu_clk)
static void setup_shifting (via_context_t *via_context, CLOCK rclk)
void viacore_store (via_context_t *via_context, uint16_t addr, uint8_t byte)
uint8_t viacore_read (via_context_t *via_context, uint16_t addr)
uint8_t viacore_peek (via_context_t *via_context, uint16_t addr)
return value of a register without side effects
void viacore_set_cb1 (via_context_t *via_context, bool data)
void viacore_set_cb2 (via_context_t *via_context, bool data)
void viacore_set_sr (via_context_t *via_context, uint8_t data)
WARNING: this is a hack, used to interface with c64fastiec.c, c128fastiec.c.
static void viacore_t2_shift_alarm (CLOCK offset, void *data)
static void viacore_phi2_sr_alarm (CLOCK offset, void *data)
alarm callback for the case when the shift register is under phi2 control
void viacore_setup_context (via_context_t *via_context)
void viacore_init (via_context_t *via_context, alarm_context_t *alarm_context, interrupt_cpu_status_t *int_status)
void viacore_shutdown (via_context_t *via_context)
int viacore_snapshot_write_module (via_context_t *via_context, snapshot_t *s)
FIXME!!! Error check.
int viacore_snapshot_read_module (via_context_t *via_context, snapshot_t *s)
int viacore_dump (via_context_t *via_context)
Macro Definition Documentation
CHECK_CPU_VS_ALARM_CLOCKS
#define CHECK_CPU_VS_ALARM_CLOCKS 0
Timer debugging.
Todo:
FIXME: this doesnt even work anymore
FULL_CYCLE_2
#define FULL_CYCLE_2 2
IS_CA2_HANDSHAKE
#define IS_CA2_HANDSHAKE () ((via_context->via[VIA_PCR] & 0x0c) == 0x08)
IS_CA2_INDINPUT
#define IS_CA2_INDINPUT () ((via_context->via[VIA_PCR] & 0x0a) == 0x02)
IS_CA2_OUTPUT
#define IS_CA2_OUTPUT () ((via_context->via[VIA_PCR] & 0x0c) == 0x0c)
IS_CA2_PULSE_MODE
#define IS_CA2_PULSE_MODE () ((via_context->via[VIA_PCR] & 0x0e) == 0x0A)
IS_CA2_TOGGLE_MODE
#define IS_CA2_TOGGLE_MODE () ((via_context->via[VIA_PCR] & 0x0e) == 0x08)
IS_CB2_HANDSHAKE
#define IS_CB2_HANDSHAKE () ((via_context->via[VIA_PCR] & 0xc0) == 0x80)
IS_CB2_INDINPUT
#define IS_CB2_INDINPUT () ((via_context->via[VIA_PCR] & 0xa0) == 0x20)
IS_CB2_OUTPUT
#define IS_CB2_OUTPUT () ((via_context->via[VIA_PCR] & 0xc0) == 0xc0)
IS_CB2_PULSE_MODE
#define IS_CB2_PULSE_MODE () ((via_context->via[VIA_PCR] & 0xe0) == 0xA0)
IS_CB2_TOGGLE_MODE
#define IS_CB2_TOGGLE_MODE () ((via_context->via[VIA_PCR] & 0xe0) == 0x80)
IS_PA_INPUT_LATCH
#define IS_PA_INPUT_LATCH () (via_context->via[VIA_ACR] & 0x01)
IS_PB_INPUT_LATCH
#define IS_PB_INPUT_LATCH () (via_context->via[VIA_ACR] & 0x02)
IS_SR_FREE_RUNNING
#define IS_SR_FREE_RUNNING () (((via_context->via[VIA_ACR]) & 0x1c) == 0x10)
IS_SR_SHIFT_IN_BY_EXT
#define IS_SR_SHIFT_IN_BY_EXT (byte) (((byte) & 0x1c) == 0x0C)
IS_SR_SHIFT_OUT_BY_T2
#define IS_SR_SHIFT_OUT_BY_T2 () (((via_context->via[VIA_ACR]) & 0x1c) == 0x14)
IS_SR_SHIFTING_OUT
#define IS_SR_SHIFTING_OUT () (((via_context->via[VIA_ACR]) & 0x10))
IS_SR_T2_CONTROLLED
#define IS_SR_T2_CONTROLLED (byte) ((((byte) & 0x0c) == 0x04) || (((byte) & 0x1c) == 0x10))
SR modes 0x04, 0x14, 0x10.
IS_T2_PULSE_COUNTING
#define IS_T2_PULSE_COUNTING (byte) (((byte) & VIA_ACR_T2_CONTROL) == VIA_ACR_T2_COUNTPB6)
IS_T2_TIMER
#define IS_T2_TIMER (byte) (((byte) & VIA_ACR_T2_CONTROL) == VIA_ACR_T2_TIMER)
SR_PHI2_FIRST_OFFSET
#define SR_PHI2_FIRST_OFFSET 3
SR_PHI2_NEXT_OFFSET
#define SR_PHI2_NEXT_OFFSET 1
TBI_OFFSET
#define TBI_OFFSET 1
VIA_DUMP_VER_MAJOR
#define VIA_DUMP_VER_MAJOR 2
The name of the modul must be defined before including this file.
VIA_DUMP_VER_MINOR
#define VIA_DUMP_VER_MINOR 2
VIADEBUG
#define VIADEBUG 0
VIALOG
#define VIALOG (...)
VIALOG2
#define VIALOG2 (...)
VIALOG9
#define VIALOG9 (...)
Function Documentation
alarm_clk()
static CLOCK alarm_clk (alarm_t * alarm) inline static
Referenced by schedule_t2_zero_alarm(), viacore_dump(), and viacore_snapshot_write_module().
alarm_is_pending()
static int alarm_is_pending (alarm_t * alarm) inline static
Referenced by alarm_set_if_not_pending(), viacore_dump(), and viacore_store().
alarm_set_if_not_pending()
static void alarm_set_if_not_pending (alarm_t * alarm, CLOCK cpu_clk) inline static
Referenced by viacore_store().
do_shiftregister()
static void do_shiftregister (CLOCK offset, via_context_t * via_context) inline static
< Auxiliary control register
Todo:
FIXME: and set interrupt flag according to edge detection in PCR? In hardware, there is also a special SR-related edge detector which triggers the actual shifting and counting, the code for which is cut short and duplicated here.
< Serial port shift register
< Serial port shift register
< Serial port shift register
Todo:
FIXME: and set interrupt flag according to edge detection in PCR?
< Serial port shift register
< Serial port shift register
< Auxiliary control register
< Shift Register completion
Referenced by viacore_phi2_sr_alarm(), and viacore_t2_shift_alarm().
run_pending_alarms()
static void run_pending_alarms (CLOCK clk, int offset, alarm_context_t * alarm_context) inline static
Referenced by viacore_snapshot_write_module(), and viacore_store().
schedule_t2_zero_alarm()
static void schedule_t2_zero_alarm (via_context_t * via_context, CLOCK rclk) inline static
Referenced by viacore_store().
set_cb2_output_state()
static void set_cb2_output_state (via_context_t * via_context, uint8_t pcr, int offset) static
< 3 bits
< bit
< bit
< 3 bits
< 3 bits
< 3 bits
< 3 bits
Todo:
FIXME: is this correct if handshake is already active?
Referenced by viacore_store().
setup_shifting()
static void setup_shifting (via_context_t * via_context, CLOCK rclk) inline static
< Auxiliary control register
Referenced by viacore_store().
update_myviairq()
static void update_myviairq (via_context_t * via_context) inline static
Referenced by viacore_reset(), viacore_set_cb1(), viacore_set_cb2(), viacore_set_sr(), and viacore_signal().
update_myviairq_rclk()
static void update_myviairq_rclk (via_context_t * via_context, CLOCK rclk) inline static
Referenced by do_shiftregister(), update_myviairq(), viacore_store(), viacore_t1_zero_alarm(), and viacore_t2_zero_alarm().
update_via_t1_latch()
static void update_via_t1_latch (via_context_t * via_context, CLOCK rclk) inline static
< Timer 1 latch low
< Timer 1 latch high
Referenced by viacore_store().
via_restore_int()
static void via_restore_int (via_context_t * via_context, int value) static
Referenced by viacore_snapshot_read_module().
viacore_cache_cb12_io_status()
static void viacore_cache_cb12_io_status (via_context_t * via_context) static
< Auxiliary control register
< Peripheral control register
< bit
< bit
Referenced by viacore_reset(), viacore_snapshot_read_module(), and viacore_store().
viacore_disable()
void viacore_disable (via_context_t * via_context)
Referenced by iec_drive_reset(), iecieee_drive_reset(), and ieee_drive_reset().
viacore_dump()
int viacore_dump (via_context_t * via_context)
< Port A
< Data direction register for port A
< Port A with no handshake
< Port B
< Data direction register for port B
< Timer 1 count low
< Timer 1 count high
< Timer 1 latch low
< Timer 1 latch high
< Timer 2 count low - read only
< Timer 2 count high - read only
< Timer 2 latch low - write only
< Auxiliary control register
< Peripheral control register
< Interrupt flag register
< Interrupt control register
< Serial port shift register
< Auxiliary control register
< Auxiliary control register
Referenced by drivemem_ioreg_list_get(), via1d1541_dump(), via2d_dump(), and via4000_dump().
viacore_init()
void viacore_init (via_context_t * via_context, alarm_context_t * alarm_context, interrupt_cpu_status_t * int_status)
Referenced by cmdhd_init(), via1d1541_init(), via1d2031_init(), via2d_init(), and via4000_init().
viacore_peek()
uint8_t viacore_peek (via_context_t * via_context, uint16_t addr)
return value of a register without side effects
Todo:
FIXME: this is buggy/incomplete
< Port A
< Port A with no handshake
Todo:
FIXME: side effects ?
< Port B
Todo:
FIXME: side effects ?
< Data direction register for port B
< Port B
< Data direction register for port B
< Auxiliary control register
< Data direction register for port A
< Data direction register for port B
< Timer 1 count low
< Timer 1 count high
< Timer 1 latch low
< Timer 1 latch high
< Timer 2 count low - read only
< Timer 2 count high - read only
< Interrupt flag register
< Interrupt control register
< Peripheral control register
< Auxiliary control register
< Serial port shift register
Referenced by via1d1541_peek(), via1d2031_peek(), via2d_peek(), via4000_peek(), and viacore_dump().
viacore_phi2_sr_alarm()
static void viacore_phi2_sr_alarm (CLOCK offset, void * data) static
alarm callback for the case when the shift register is under phi2 control
Referenced by viacore_init().
viacore_read()
uint8_t viacore_read (via_context_t * via_context, uint16_t addr)
< Port B
< Timer 1 count low
< Interrupt control register
< Port A
< Handshake
< Peripheral control register
< Handshake
< Peripheral control register
< Peripheral control register
< Handshake
< Handshake
< Port A with no handshake
< Port B
< Handshake
< Peripheral control register
< Handshake
< Handshake
< Handshake
< Data direction register for port B
< Port B
< Data direction register for port B
< Auxiliary control register
< Timer 1 count low
< Timer 1 underflow
< Timer 1 count high
< Timer 2 count low - read only
< Timer 2 underflow
< Timer 2 count high - read only
< Serial port shift register
< Shift Register completion
< Shift Register completion
< Interrupt flag register
< Interrupt control register
Referenced by cmdhd_read(), via1d1541_read(), via1d2031_read(), via2d_read(), and via4000_read().
viacore_reset()
void viacore_reset (via_context_t * via_context)
Referenced by cmdhd_reset(), iec_drive_reset(), iecieee_drive_reset(), and ieee_drive_reset().
viacore_set_cb1()
void viacore_set_cb1 (via_context_t * via_context, bool data)
Todo:
FIXME: Is this the right way to start shifting a byte?
< Serial port shift register
< Serial port shift register
< Serial port shift register
Todo:
the case of VIA_ACR_SR_OUT_CB1 0x1C mode 7 Shift out under control of an External Pulse which happens on the falling edge of CB1. (maybe keep separate cb1_drives_shifting flag?) From http://forum.6502.org/viewtopic.php?f=4&t=7241&start=15#p94001 The CB1 pad also works as the shift clock from/to the outerworld when enabling "10) shift register", and that's why we have another (conceptually different) edge detector sensing the CB1 pad, gated with PHI0=1 AND PHI2=1.
If ACR4=0, the shift register shifts in, and the detector scans for CB1 rising edge. If ACR4=1, the shift register shifts out, and the detector scans for CB1 falling edge.
Low_active signal SR_CB1_DET# generated by the detector tells "22) shift register control" to shift/count the next Bit.
< Peripheral control register
< 1 bit
< bit
< Peripheral control register
< Handshake
Referenced by viacore_signal().
viacore_set_cb2()
void viacore_set_cb2 (via_context_t * via_context, bool data)
< Peripheral control register
< bit
< Handshake
Referenced by viacore_signal().
viacore_set_sr()
void viacore_set_sr (via_context_t * via_context, uint8_t data)
WARNING: this is a hack, used to interface with c64fastiec.c, c128fastiec.c.
WARNING: this is a hack.
< Auxiliary control register
< Auxiliary control register
< Serial port shift register
Todo:
Setting VIA_IM_SR may need a delay of 1 clock
< Shift Register completion
Referenced by c128fastiec_fast_cpu_write(), and viacore_set_cb1().
viacore_setup_context()
void viacore_setup_context (via_context_t * via_context)
Referenced by cmdhd_setup_context(), via1d1541_setup_context(), via1d2031_setup_context(), via2d_setup_context(), and via4000_setup_context().
viacore_shutdown()
void viacore_shutdown (via_context_t * via_context)
Referenced by cmdhd_shutdown(), iec_drive_shutdown(), iecieee_drive_shutdown(), and ieee_drive_shutdown().
viacore_signal()
void viacore_signal (via_context_t * via_context, int line, int edge)
< Peripheral control register
< 1 bit
< Peripheral control register
< Handshake
< Peripheral control register
< bit
< bit
< Peripheral control register
< Handshake
Referenced by iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), iecbus_cpu_write_conf3(), and via1d2031_set_atn().
viacore_snapshot_read_module()
int viacore_snapshot_read_module (via_context_t * via_context, snapshot_t * s)
Todo:
load from snapshot
< Port A
< Data direction register for port A
< Port B
< Data direction register for port B
< Timer 2 latch low - write only
< Timer 2 latch high - write only
< Serial port shift register
< Auxiliary control register
< Peripheral control register
< Data direction register for port A
< Port A
< Data direction register for port A
< Data direction register for port B
< Port B
< Data direction register for port B
< Timer 1 latch low
< Timer 1 latch high
< Auxiliary control register
< Auxiliary control register
< Auxiliary control register
Todo:
FIXME: SR alarm
< Auxiliary control register
< Peripheral control register
< Serial port shift register
< Auxiliary control register
Referenced by cmdhd_snapshot_read_module(), iec_drive_snapshot_read(), iecieee_drive_snapshot_read(), and ieee_drive_snapshot_read().
viacore_snapshot_write_module()
int viacore_snapshot_write_module (via_context_t * via_context, snapshot_t * s)
FIXME!!! Error check.
< Port A
< Data direction register for port A
< Port B
< Data direction register for port B
< Timer 2 latch low - write only
< Timer 2 latch high - write only
< Serial port shift register
< Auxiliary control register
< Peripheral control register
Referenced by cmdhd_snapshot_write_module(), iec_drive_snapshot_write(), iecieee_drive_snapshot_write(), and ieee_drive_snapshot_write().
viacore_store()
void viacore_store (via_context_t * via_context, uint16_t addr, uint8_t byte)
< Port B
< Timer 1 count low
< Interrupt control register
< Port A
< Handshake
< Peripheral control register
< Handshake
< Peripheral control register
< Peripheral control register
< Handshake
< Handshake
< Port A with no handshake
< Port A with no handshake
< Port A
< Data direction register for port A
< Port A
< Data direction register for port A
< Port B
< Handshake
< Peripheral control register
< Handshake
< Peripheral control register
< Peripheral control register
Todo:
FIXME: This pulse is a bit short...
< Handshake
< Handshake
< Data direction register for port B
< Port B
< Data direction register for port B
< Auxiliary control register
< Serial port shift register
< Shift Register completion
< Shift Register completion
< Timer 1 count low
< Timer 1 latch low
< Timer 1 latch low
< Timer 1 count high
< Timer 1 latch high
< Timer 1 underflow
< Timer 1 latch high
< Timer 1 underflow
< Timer 2 latch low - write only
< Timer 2 latch low - write only
< Timer 2 count high - read only
< Timer 2 latch high - write only
< Timer 2 latch low - write only
< Auxiliary control register
< Timer 2 underflow
< Interrupt flag register
Todo:
FIXME: clearing any timer interrupt should set the relevant timer alarm. (It is unclear what was meant with that...
< Interrupt control register
< Control Bit
< Auxiliary control register
< Auxiliary control register
< Auxiliary control register
< Shift Register completion
< Shift Register completion
< Peripheral control register
< Auxiliary control register
< Auxiliary control register
< SR modes 0x04, 0x14, 0x10
Todo:
Out not emulated
< Peripheral control register
< 3 bits
< 3 bits
< 3 bits
< 3 bits
Todo:
FIXME: is this correct if handshake is already active?
< Auxiliary control register
Referenced by cmdhd_store(), via1d1541_store(), via1d2031_store(), via2d_store(), via4000_store(), and viacore_store().
viacore_t1()
static uint16_t viacore_t1 (via_context_t * via_context, CLOCK rclk) inline static
the next two are used in viacore_read()
Referenced by update_via_t1_latch(), viacore_peek(), viacore_snapshot_write_module(), and viacore_t1_zero_alarm().
viacore_t1_zero_alarm()
static void viacore_t1_zero_alarm (CLOCK offset, void * data) static
< Auxiliary control register
< Timer 1 underflow
Referenced by viacore_init().
viacore_t2()
static uint16_t viacore_t2 (via_context_t * via_context, CLOCK rclk) inline static
< Auxiliary control register
Referenced by viacore_peek(), viacore_snapshot_write_module(), viacore_store(), and viacore_t2_zero_alarm().
viacore_t2_shift_alarm()
static void viacore_t2_shift_alarm (CLOCK offset, void * data) static
Referenced by viacore_init().
viacore_t2_underflow_alarm()
static void viacore_t2_underflow_alarm (CLOCK offset, void * data) static
< Auxiliary control register
< Timer 2 latch low - write only
< Timer 2 latch low - write only
< Auxiliary control register
< Timer 2 latch low - write only
< Timer 2 latch low - write only
Referenced by viacore_init().
viacore_t2_zero_alarm()
static void viacore_t2_zero_alarm (CLOCK offset, void * data) static
< Timer 2 underflow
Referenced by viacore_init().