vsid: sound_chip_s Struct Reference
sound_chip_s Struct Reference
This structure is used by sound producing chips/devices.
#include <sound.h>
Data Fields
sound_t *(* open)(int chipno)
int(* init)(sound_t *psid, int speed, int cycles_per_sec)
void(* close)(sound_t *psid)
int(* calculate_samples)(sound_t **psid, int16_t *pbuf, int nr, int sound_output_channels, int sound_chip_channels, CLOCK *delta_t)
void(* store)(sound_t *psid, uint16_t addr, uint8_t val)
uint8_t(* read)(sound_t *psid, uint16_t addr)
void(* reset)(sound_t *psid, CLOCK cpu_clk)
int(* cycle_based)(void)
int(* channels)(void)
int chip_enabled
Detailed Description
This structure is used by sound producing chips/devices.
Field Documentation
calculate_samples
int(* sound_chip_s::calculate_samples) (sound_t **psid, int16_t *pbuf, int nr, int sound_output_channels, int sound_chip_channels, CLOCK *delta_t)
Referenced by sound_machine_calculate_samples().
channels
int(* sound_chip_s::channels) (void)
Referenced by sound_machine_calculate_samples(), and sound_machine_channels().
chip_enabled
int sound_chip_s::chip_enabled
Referenced by digimax_enable(), drive_sound_head(), drive_sound_machine_calculate_samples(), drive_sound_stop(), drive_sound_update(), sound_machine_calculate_samples(), userport_dac_set_enabled(), and video_sound_update().
close
void(* sound_chip_s::close) (sound_t *psid)
Referenced by sound_machine_close().
cycle_based
int(* sound_chip_s::cycle_based) (void)
Referenced by sound_machine_calculate_samples(), and sound_machine_cycle_based().
init
int(* sound_chip_s::init) (sound_t *psid, int speed, int cycles_per_sec)
Referenced by sound_machine_init().
open
sound_t *(* sound_chip_s::open) (int chipno)
Referenced by sound_machine_open().
read
uint8_t(* sound_chip_s::read) (sound_t *psid, uint16_t addr)
Referenced by sound_machine_read().
reset
void(* sound_chip_s::reset) (sound_t *psid, CLOCK cpu_clk)
Referenced by sound_machine_reset().
store
void(* sound_chip_s::store) (sound_t *psid, uint16_t addr, uint8_t val)
Referenced by sound_machine_store().
The documentation for this struct was generated from the following file:
sound.h