x128: serial.h File Reference
serial.h File Reference
#include "types.h"
Data Structures
struct serial_s
Macros
#define SERIAL_MAXDEVICES 16
#define SERIAL_DEVICE_NONE 0
#define SERIAL_DEVICE_FS 1
filesystem
#define SERIAL_DEVICE_REAL 2
real IEC device (opencbm)
#define SERIAL_DEVICE_RAW 3
raw device
#define SERIAL_DEVICE_VIRT 4
non-tde drive/image
#define ISOPEN_CLOSED 0
#define ISOPEN_AWAITING_NAME 1
#define ISOPEN_OPEN 2
Typedefs
typedef struct serial_s serial_t
Functions
int serial_init (const struct trap_s *trap_list)
int serial_resources_init (void)
int serial_cmdline_options_init (void)
void serial_shutdown (void)
int serial_install_traps (void)
int serial_remove_traps (void)
void serial_trap_init (uint16_t tmpin)
int serial_trap_attention (void)
int serial_trap_send (void)
Send one byte on the serial bus.
int serial_trap_receive (void)
Receive one byte from the serial bus.
int serial_trap_ready (void)
void serial_traps_reset (void)
called by machine_specific_reset()
void serial_trap_eof_callback_set (void(*func)(void))
Specify a function to call when EOF happens in ‘serialreceivebyte()’.
void serial_trap_attention_callback_set (void(*func)(void))
Specify a function to call when the ‘serialattention()’ trap is called.
void serial_trap_truedrive_set (unsigned int unit, unsigned int flag)
int serial_realdevice_enable (void)
void serial_realdevice_disable (void)
int serial_iec_lib_directory (unsigned int unit, const char *pattern, uint8_t **buf)
int serial_iec_lib_read_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t *buf)
int serial_iec_lib_write_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t *buf)
serial_t * serial_device_get (unsigned int unit)
unsigned int serial_device_type_get (unsigned int unit)
void serial_device_type_set (unsigned int type, unsigned int unit)
void serial_iec_device_set_machine_parameter (long cycles_per_sec)
void serial_iec_device_exec (CLOCK clk_value)
void serial_iec_bus_init (void)
void fsdrive_snapshot_prepare (void)
int fsdrive_snapshot_write_module (struct snapshot_s *s)
int fsdrive_snapshot_read_module (struct snapshot_s *s)
Macro Definition Documentation
ISOPEN_AWAITING_NAME
#define ISOPEN_AWAITING_NAME 1
ISOPEN_CLOSED
#define ISOPEN_CLOSED 0
ISOPEN_OPEN
#define ISOPEN_OPEN 2
SERIAL_DEVICE_FS
#define SERIAL_DEVICE_FS 1
filesystem
SERIAL_DEVICE_NONE
#define SERIAL_DEVICE_NONE 0
SERIAL_DEVICE_RAW
#define SERIAL_DEVICE_RAW 3
raw device
SERIAL_DEVICE_REAL
#define SERIAL_DEVICE_REAL 2
real IEC device (opencbm)
SERIAL_DEVICE_VIRT
#define SERIAL_DEVICE_VIRT 4
non-tde drive/image
SERIAL_MAXDEVICES
#define SERIAL_MAXDEVICES 16
Typedef Documentation
serial_t
typedef struct serial_s serial_t
Function Documentation
fsdrive_snapshot_prepare()
void fsdrive_snapshot_prepare (void)
fsdrive_snapshot_read_module()
int fsdrive_snapshot_read_module (struct snapshot_s * s)
Referenced by c128_snapshot_read().
fsdrive_snapshot_write_module()
int fsdrive_snapshot_write_module (struct snapshot_s * s)
Referenced by c128_snapshot_write().
serial_cmdline_options_init()
int serial_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
serial_device_get()
serial_t * serial_device_get (unsigned int unit)
Referenced by file_system_init(), fsdrive_listentalk(), fsdrive_open(), fsdrive_read(), fsdrive_reset(), fsdrive_unlisten(), fsdrive_write(), machine_bus_device_attach(), machine_bus_device_detach(), machine_bus_init(), parallel_trap_attention(), parallel_trap_receivebyte(), parallel_trap_sendbyte(), parallelcommand(), serial_device_type_get(), serial_device_type_set(), serial_trap_attention(), and serialcommand().
serial_device_type_get()
unsigned int serial_device_type_get (unsigned int unit)
Referenced by machine_bus_device_type_get(), serial_iec_bus_close(), serial_iec_bus_listen(), serial_iec_bus_open(), serial_iec_bus_read(), serial_iec_bus_talk(), serial_iec_bus_unlisten(), serial_iec_bus_untalk(), and serial_iec_bus_write().
serial_device_type_set()
void serial_device_type_set (unsigned int type, unsigned int unit)
Referenced by file_system_attach_disk_internal(), file_system_init(), interface_serial_attach(), open_disk_image(), and set_file_system_device().
serial_iec_bus_init()
void serial_iec_bus_init (void)
Referenced by machine_specific_init().
serial_iec_device_exec()
void serial_iec_device_exec (CLOCK clk_value)
Referenced by iecbus_cpu_read_conf3(), and iecbus_cpu_write_conf3().
serial_iec_device_set_machine_parameter()
void serial_iec_device_set_machine_parameter (long cycles_per_sec)
Referenced by machine_change_timing().
serial_iec_lib_directory()
int serial_iec_lib_directory (unsigned int unit, const char * pattern, uint8_t ** buf)
Referenced by diskcontents_iec_read(), and machine_bus_lib_directory().
serial_iec_lib_read_sector()
int serial_iec_lib_read_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t * buf)
Referenced by machine_bus_lib_read_sector().
serial_iec_lib_write_sector()
int serial_iec_lib_write_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t * buf)
Referenced by machine_bus_lib_write_sector().
serial_init()
int serial_init (const struct trap_s * trap_list)
Referenced by machine_specific_init().
serial_install_traps()
int serial_install_traps (void)
Referenced by serial_init().
serial_realdevice_disable()
void serial_realdevice_disable (void)
Referenced by close_disk_image(), file_system_detach_disk_shutdown(), open_disk_image(), and set_file_system_device().
serial_realdevice_enable()
int serial_realdevice_enable (void)
Referenced by open_disk_image(), and set_file_system_device().
serial_remove_traps()
int serial_remove_traps (void)
Referenced by serial_init().
serial_resources_init()
int serial_resources_init (void)
Referenced by machine_resources_init().
serial_shutdown()
void serial_shutdown (void)
Referenced by machine_resources_shutdown().
serial_trap_attention()
int serial_trap_attention (void)
< Buffered Character for IEEE Bus
< LISTEN with dev=31 correct?
< TALK with dev=31 correct?
< should be 0x1F
< LISTEN with dev=31 correct?
< TALK with dev=31 correct?
< LISTEN with dev=31 correct?
< TALK with dev=31 correct?
< should be 0x1F
serial_trap_attention_callback_set()
void serial_trap_attention_callback_set (void(*)(void) func)
Specify a function to call when the ‘serialattention()’ trap is called.
serial_trap_eof_callback_set()
void serial_trap_eof_callback_set (void(*)(void) func)
Specify a function to call when EOF happens in ‘serialreceivebyte()’.
serial_trap_init()
void serial_trap_init (uint16_t tmpin)
Referenced by machine_specific_init().
serial_trap_ready()
int serial_trap_ready (void)
serial_trap_receive()
int serial_trap_receive (void)
Receive one byte from the serial bus.
serial_trap_send()
int serial_trap_send (void)
Send one byte on the serial bus.
< Buffered Character for IEEE Bus
serial_trap_truedrive_set()
void serial_trap_truedrive_set (unsigned int unit, unsigned int flag)
serial_traps_reset()
void serial_traps_reset (void)
called by machine_specific_reset()
Todo:
FIXME: bad name, this function is basically the main/top entry point for doing a IEC reset that distributes to all drives. It does however NOT reset the true-drive emulated drive CPUs (that is done in drive_reset)
Referenced by machine_specific_reset().