x128: arch/gtk3/widgets/base/resourceradiogroup.c File Reference
resourceradiogroup.c File Reference
Group of radio buttons controlling a resource.
#include "vice.h"
#include <gtk/gtk.h>
#include "basewidget_types.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "resourcehelpers.h"
#include "resourceradiogroup.h"
Functions
static void on_radio_toggled (GtkWidget *radio, gpointer user_data)
Handler for the 'toggled' event of a radio button.
static GtkWidget * resource_radiogroup_new_helper (GtkWidget *grid, const vice_gtk3_radiogroup_entry_t *entries, GtkOrientation orientation)
Helper function for the new() functions.
GtkWidget * vice_gtk3_resource_radiogroup_new (const char *resource, const vice_gtk3_radiogroup_entry_t *entries, GtkOrientation orientation)
Create a radiogroup widget.
GtkWidget * vice_gtk3_resource_radiogroup_new_sprintf (const char *fmt, const vice_gtk3_radiogroup_entry_t *entries, GtkOrientation orientation,...)
Create a radiogroup widget, using sprintf()-style formatting of the resource name.
gboolean vice_gtk3_resource_radiogroup_set (GtkWidget *widget, int id)
Set widget to id.
gboolean vice_gtk3_resource_radiogroup_get (GtkWidget *widget, int *id)
Get resource value of widget.
gboolean vice_gtk3_resource_radiogroup_item_set_sensitive (GtkWidget *widget, int index, int sensitive)
Set sensitive flag of item at index.
gboolean vice_gtk3_resource_radiogroup_sync (GtkWidget *widget)
Synchronize widget with its current resource value.
gboolean vice_gtk3_resource_radiogroup_factory (GtkWidget *widget)
Reset radio group to its factory default.
gboolean vice_gtk3_resource_radiogroup_reset (GtkWidget *widget)
Reset radio group to its value on instanciation.
void vice_gtk3_resource_radiogroup_add_callback (GtkWidget *widget, void(*callback)(GtkWidget *, int))
Add an extra callback to widget.
Detailed Description
Group of radio buttons controlling a resource.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Todo:
Make a copy of the entries argument to the new() functions, that way the entries don't have to be kept in memory during the lifetime of the widgets.
Function Documentation
on_radio_toggled()
static void on_radio_toggled (GtkWidget * radio, gpointer user_data) static
Handler for the 'toggled' event of a radio button.
Parameters
[in] radio radio button triggering the event
[in] user_data new value for the radio group (int)
Referenced by resource_radiogroup_new_helper().
resource_radiogroup_new_helper()
static GtkWidget * resource_radiogroup_new_helper (GtkWidget * grid, const vice_gtk3_radiogroup_entry_t * entries, GtkOrientation orientation) static
Helper function for the new() functions.
Parameters
[in,out] grid containing grid
[in] entries list of entries for the group
[in] orientation layout direction of the radio buttons
Returns
GtkGrid
Referenced by vice_gtk3_resource_radiogroup_new(), and vice_gtk3_resource_radiogroup_new_sprintf().
vice_gtk3_resource_radiogroup_add_callback()
void vice_gtk3_resource_radiogroup_add_callback (GtkWidget * widget, void(*)(GtkWidget *, int) callback)
Add an extra callback to widget.
This callback should allow widgets interacting with other widgets without using any global references.
The widget returned is the actual radio group GtkGrid, the integer value is the curent ID of the radiogroup's currently selected radio button.
Parameters
[in,out] widget radiogroup widget
[in] callback function to call when the radiogroup selection changes
Referenced by cbm2_hardwired_switches_widget_set_callback(), cbm2_memory_size_widget_set_callback(), create_c64dtv_revision_widget(), create_cia_widget(), machine_power_frequency_widget_add_callback(), pet_io_size_widget_create(), pet_ram9_widget_create(), pet_ram_size_widget_set_callback(), pet_rama_widget_create(), pet_video_size_widget_create(), plus4_memory_expansion_widget_add_callback(), plus4_memory_size_widget_add_callback(), sid_model_widget_create(), video_aspect_widget_add_callback(), and video_render_filter_widget_add_callback().
vice_gtk3_resource_radiogroup_factory()
gboolean vice_gtk3_resource_radiogroup_factory (GtkWidget * widget)
Reset radio group to its factory default.
Parameters
[in,out] widget resource radio group
Returns
TRUE if widget is set to its factory value
vice_gtk3_resource_radiogroup_get()
gboolean vice_gtk3_resource_radiogroup_get (GtkWidget * widget, int * id)
Get resource value of widget.
Parameters
[in] widget resource radio group
[out] id object to store resource value
Returns
TRUE if id was set
vice_gtk3_resource_radiogroup_item_set_sensitive()
gboolean vice_gtk3_resource_radiogroup_item_set_sensitive (GtkWidget * widget, int index, int sensitive)
Set sensitive flag of item at index.
Parameters
[in,out] widget radiogroup widget
[in] index item index
[in] sensitive sensitive flag for item at index
Returns
TRUE
Todo:
Perhaps make void since it only ever returns TRUE?
Referenced by kbdmapping_widget_update().
vice_gtk3_resource_radiogroup_new()
GtkWidget * vice_gtk3_resource_radiogroup_new (const char * resource, const vice_gtk3_radiogroup_entry_t * entries, GtkOrientation orientation)
Create a radiogroup widget.
A radiogroup widget is a composite widget consisting of a GtkGrid with a number of GtkRadioButton's, laid out according to orientation
Three GObject properties are set: "ResourceName", a heap-allocated copy of the resource argument, "Entries", a reference to the entries and "Orientation", the orientation argument. These are all required to make the event handlers and resource_radiogroup_update() work properly.
The entries passed to this function need to be available during the widget's lifetime, since only a pointer to them is stored, no copies are made.
Parameters
[in] resource resource name
[in] entries list of entries for the group
[in] orientation layout direction of the radio buttons
Returns
GtkGrid
Referenced by c128_machine_type_widget_create(), cbm2_hardwired_switches_widget_create(), cbm2_memory_size_widget_create(), create_acia_base_widget(), create_acia_device_widget(), create_acia_irq_widget(), create_acia_mode_widget(), create_c64dtv_revision_widget(), create_card_image_layout(), create_card_layout(), create_collision_widget(), create_expert_mode_widget(), create_ide64_revision_layout(), create_io_address_widget(), create_memhack_widget(), create_mmc64_revision_widget(), create_prg_layout(), create_sfx_chip_widget(), create_sidcart_address_widget(), create_sidcart_clock_widget(), create_superpet_cpu_widget(), kbdmapping_widget_create(), machine_power_frequency_widget_new(), memory_hacks_device_widget_create(), pet_io_size_widget_create(), pet_ram9_widget_create(), pet_ram_size_widget_create(), pet_rama_widget_create(), pet_video_size_widget_create(), plus4_memory_expansion_widget_create(), plus4_memory_size_widget_create(), printer_output_device_widget_create(), ram_size_radiogroup_new(), settings_burstmode_widget_create(), settings_jam_widget_create(), settings_petcolourgraphics_widget_create(), settings_ramlink_widget_create(), settings_snapshot_widget_create(), sid_model_widget_create(), sound_fragment_size_widget_create(), sound_output_mode_widget_create(), sound_sample_rate_widget_create(), sound_sync_mode_widget_create(), speed_widget_create(), and vdc_model_widget_create().
vice_gtk3_resource_radiogroup_new_sprintf()
GtkWidget * vice_gtk3_resource_radiogroup_new_sprintf (const char * fmt, const vice_gtk3_radiogroup_entry_t * entries, GtkOrientation orientation, ...)
Create a radiogroup widget, using sprintf()-style formatting of the resource name.
A radiogroup widget is a composite widget consisting of a GtkGrid with a number of GtkRadioButton's, laid out according to orientation
Three GObject properties are set: "ResourceName", a heap-allocated copy of the resource argument, "Entries", a reference to the entries and "Orientation", the orientation argument. These are all required to make the event handlers and resource_radiogroup_update() work properly.
The entries passed to this function need to be available during the widget's lifetime, since only a pointer to them is stored, no copies are made.
Parameters
[in] fmt resource name format string
[in] entries list of entries for the group
[in] orientation layout direction of the radio buttons
Returns
GtkGrid
Referenced by canvas_render_filter_widget_create(), create_autofire_mode_widget(), create_cia_widget(), create_rom_type_widget(), printer_emulation_type_widget_create(), video_aspect_widget_create(), video_border_mode_widget_create(), and video_render_filter_widget_create().
vice_gtk3_resource_radiogroup_reset()
gboolean vice_gtk3_resource_radiogroup_reset (GtkWidget * widget)
Reset radio group to its value on instanciation.
Parameters
[in,out] widget resource radio group
Returns
TRUE is widget is reset to its original value
vice_gtk3_resource_radiogroup_set()
gboolean vice_gtk3_resource_radiogroup_set (GtkWidget * widget, int id)
Set widget to id.
Parameters
[in,out] widget radiogroup widget
[in] id new value for widget
Returns
bool
Referenced by machine_model_handler_c64dtv(), open_pos_file_callback(), open_sym_file_callback(), pet_io_size_widget_sync(), pet_ram9_widget_sync(), pet_rama_widget_sync(), printer_emulation_type_widget_update(), vice_gtk3_resource_radiogroup_factory(), vice_gtk3_resource_radiogroup_reset(), and vice_gtk3_resource_radiogroup_sync().
vice_gtk3_resource_radiogroup_sync()
gboolean vice_gtk3_resource_radiogroup_sync (GtkWidget * widget)
Synchronize widget with its current resource value.
Parameters
[in,out] widget radiogroup widget
Returns
TRUE if widget was synchronized
Referenced by cbm2_memory_size_widget_update(), cia_model_widget_sync(), machine_model_handler_c128(), machine_model_handler_c64(), machine_power_frequency_widget_sync(), pet_ram_size_widget_sync(), pet_video_size_widget_sync(), plus4_memory_expansion_widget_sync(), and plus4_memory_size_widget_sync().