vsid: arch/shared/archdep_access.c File Reference
archdep_access.c File Reference
Test access mode of a file - header.
#include "vice.h"
#include "archdep_defs.h"
#include <errno.h>
#include "archdep_access.h"
Functions
int archdep_access (const char *pathname, int mode)
Appropriate headers for access(2)/_access() are included in archdep_access.h.
Detailed Description
Test access mode of a file - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
archdep_access()
int archdep_access (const char * pathname, int mode)
Appropriate headers for access(2)/_access() are included in archdep_access.h.
Test access of pathname against mode
Parameters
[in] pathname path to file or directory to test
[in] mode access modes bitmask
Returns
0 on success, -1 on failure
Referenced by archdep_mkdir_recursive(), command_directory_get(), findpath(), fliplist_load_list(), resources_load(), resources_save(), zfile_compress(), and zfile_fopen().