vsid: arch/gtk3/uidatasette.h File Reference
uidatasette.h File Reference
Independent datasette control widgets - header.
#include <gtk/gtk.h>
Functions
int ui_datasette_command_to_action (int port, int command)
Translate datasette command codes to UI action IDs.
GtkWidget * ui_create_datasette_control_menu (int port)
Create datasette control menu.
void ui_datasette_update_sensitive (GtkWidget *menu, int port)
Update sensitivity of the datasettet controls.
Detailed Description
Independent datasette control widgets - header.
Author
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
Function Documentation
ui_create_datasette_control_menu()
GtkWidget * ui_create_datasette_control_menu (int port)
Create datasette control menu.
Parameters
[in] port datasette port number (1 or 2)
Returns
GtkMenu with datasette controls
Todo:
Update for second datasette on PET
Referenced by ui_statusbar_create().
ui_datasette_command_to_action()
int ui_datasette_command_to_action (int port, int command)
Translate datasette command codes to UI action IDs.
Parameters
[in] command datasette command code
[in] port port number (1 or 2)
Returns
action ID or ACTION_NONE for invalid control or port values
See also
src/datasette/datasette.h for the command codes
Referenced by ui_create_datasette_control_menu().
ui_datasette_update_sensitive()
void ui_datasette_update_sensitive (GtkWidget * menu, int port)
Update sensitivity of the datasettet controls.
Disables/enables the datasette controls (keys), depending on whether the datasette is enabled.
Parameters
[in] menu tape menu
[in] port tape port number (1 or 2)
Referenced by ui_do_datasette_popup().