vsid: c64/c64rom.c File Reference
c64rom.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "c64-resources.h"
#include "c64mem.h"
#include "c64memrom.h"
#include "c64rom.h"
#include "log.h"
#include "machine.h"
#include "mem.h"
#include "resources.h"
#include "sha1.h"
#include "sysfile.h"
#include "types.h"
Data Structures
struct kernal_s
Macros
#define LOG(x)
#define NUM_TRAP_DEVICES 9 /*! \todo FIXME: is there a better constant ? */
Functions
int c64rom_isloaded (void)
int c64rom_get_kernal_chksum_id (uint16_t *sumout, int *idout, char *hash)
int c64rom_print_kernal_info (void)
print ROM ID, checksum, sha1 hash.
static void get_trapflags (void)
static void clear_trapflags (void)
static void restore_trapflags (void)
int c64rom_load_kernal (const char *rom_name, uint8_t *cartkernal)
int c64rom_print_basic_info (void)
int c64rom_load_basic (const char *rom_name)
int c64rom_load_chargen (const char *rom_name)
int mem_load (void)
Variables
static log_t c64rom_log = ((log_t)-1)
static int rom_loaded = 0
Flag: nonzero if the Kernal and BASIC ROMs have been loaded.
static struct kernal_s kernal_match []
NOTE: also update the table in c64-resources.c.
int c64rom_cartkernal_active = 0
static int trapfl [9]
static int trapdevices [9+1] = { 1, 4, 5, 6, 7, 8, 9, 10, 11, -1 }
Macro Definition Documentation
LOG
#define LOG (x)
NUM_TRAP_DEVICES
#define NUM_TRAP_DEVICES 9 /*! \todo FIXME: is there a better constant ? */
Function Documentation
c64rom_get_kernal_chksum_id()
int c64rom_get_kernal_chksum_id (uint16_t * sumout, int * idout, char * hash)
< used for the MAX machine, which has no kernal
Referenced by c64rom_print_kernal_info().
c64rom_isloaded()
int c64rom_isloaded (void)
Referenced by set_kernal_revision().
c64rom_load_basic()
int c64rom_load_basic (const char * rom_name)
Referenced by mem_load(), and set_basic_rom_name().
c64rom_load_chargen()
int c64rom_load_chargen (const char * rom_name)
Referenced by mem_load(), and set_chargen_rom_name().
c64rom_load_kernal()
int c64rom_load_kernal (const char * rom_name, uint8_t * cartkernal)
< dummy, used for the MAX machine, which has no kernal
Referenced by mem_load(), and set_kernal_rom_name().
c64rom_print_basic_info()
int c64rom_print_basic_info (void)
Referenced by c64_snapshot_read_rom_module(), and c64rom_load_basic().
c64rom_print_kernal_info()
int c64rom_print_kernal_info (void)
print ROM ID, checksum, sha1 hash.
Todo:
FIXME: this function has a misleading name, only called from snapshot stuff atm it was used to patch the kernal before, but not anymore
< used for the MAX machine, which has no kernal
Referenced by c64_snapshot_read_rom_module(), and c64rom_load_kernal().
clear_trapflags()
static void clear_trapflags (void) static
Referenced by c64rom_load_kernal().
get_trapflags()
static void get_trapflags (void) static
Referenced by c64rom_load_kernal().
mem_load()
int mem_load (void)
Referenced by machine_specific_init().
restore_trapflags()
static void restore_trapflags (void) static
Referenced by c64rom_load_kernal().
Variable Documentation
c64rom_cartkernal_active
int c64rom_cartkernal_active = 0
Referenced by c64rom_load_kernal().
c64rom_log
log_t c64rom_log = ((log_t)-1) static
Referenced by c64rom_load_basic(), c64rom_load_chargen(), c64rom_load_kernal(), c64rom_print_basic_info(), c64rom_print_kernal_info(), and mem_load().
kernal_match
struct kernal_s kernal_match[] static
Initial value:
= {
    {  0xaa  ,     54525  ,     "87cc04d61fc748b82df09856847bb5c2754a2033"  ,     1   },
    {  0x00  ,     50955  ,     "0e2e4ee3f2d41f00bed72f9ab588b83e306fdb13"  ,     2   },
    {  0x03  ,     50954  ,     "1d503e56df85a62fee696e7618dc5b4e781df1bb"  ,     3   },
    {  0x00  ,     53635  ,     "4ff0f11e80f4b57430d8f0c3799ed0f0e0f4565d"  ,     0   },
    {  0x43  ,     50955  ,     "aa136e91ecf3c5ac64f696b3dbcbfc5ba0871c98"  ,     67   },
    {  0x03  ,    46538  ,    "3ad6cc1837c679a11f551ad1cf1a32dd84ace719"  ,    39   },
    {  0x64  ,     49680  ,     "6c4fa9465f6091b174df27dfe679499df447503c"  ,     100   },
    { 0,                    0,                          NULL,                    -1  }
}
NOTE: also update the table in c64-resources.c.
Referenced by c64rom_get_kernal_chksum_id().
rom_loaded
int rom_loaded = 0 static
Flag: nonzero if the Kernal and BASIC ROMs have been loaded.
Referenced by c64rom_isloaded(), c64rom_load_basic(), c64rom_load_chargen(), c64rom_load_kernal(), and mem_load().
trapdevices
int trapdevices[9+1] = { 1, 4, 5, 6, 7, 8, 9, 10, 11, -1 } static
Referenced by clear_trapflags(), get_trapflags(), and restore_trapflags().
trapfl
int trapfl[9] static
Referenced by get_trapflags(), and restore_trapflags().