vsid: cbmdos.h File Reference
cbmdos.h File Reference
#include "types.h"
Data Structures
struct cbmdos_cmd_parse_s
struct cbmdos_cmd_parse_plus_s
Macros
#define CBMDOS_IPE_OK 0
CBM DOS Input Processor Error Codes.
#define CBMDOS_IPE_DELETED 1
#define CBMDOS_IPE_SEL_PARTN 2
1581
#define CBMDOS_IPE_UNIMPL 3
#define CBMDOS_IPE_MEMORY_READ 4
#define CBMDOS_IPE_READ_ERROR_BNF 20
#define CBMDOS_IPE_READ_ERROR_SYNC 21
#define CBMDOS_IPE_READ_ERROR_DATA 22
#define CBMDOS_IPE_READ_ERROR_CHK 23
#define CBMDOS_IPE_READ_ERROR_GCR 24
#define CBMDOS_IPE_WRITE_ERROR_VER 25
#define CBMDOS_IPE_WRITE_PROTECT_ON 26
#define CBMDOS_IPE_READ_ERROR_BCHK 27
#define CBMDOS_IPE_WRITE_ERROR_BIG 28
#define CBMDOS_IPE_DISK_ID_MISMATCH 29
#define CBMDOS_IPE_SYNTAX 30
#define CBMDOS_IPE_INVAL 31
#define CBMDOS_IPE_LONG_LINE 32
#define CBMDOS_IPE_BAD_NAME 33
#define CBMDOS_IPE_NO_NAME 34
#define CBMDOS_IPE_PATH_NOT_FOUND 39
#define CBMDOS_IPE_NO_RECORD 50
#define CBMDOS_IPE_OVERFLOW 51
#define CBMDOS_IPE_TOOLARGE 52
1581
#define CBMDOS_IPE_NOT_WRITE 60
#define CBMDOS_IPE_NOT_OPEN 61
#define CBMDOS_IPE_NOT_FOUND 62
#define CBMDOS_IPE_FILE_EXISTS 63
#define CBMDOS_IPE_BAD_TYPE 64
#define CBMDOS_IPE_NO_BLOCK 65
#define CBMDOS_IPE_ILLEGAL_TRACK_OR_SECTOR 66
#define CBMDOS_IPE_ILLEGAL_SYSTEM_T_OR_S 67
1581
#define CBMDOS_IPE_NO_CHANNEL 70
#define CBMDOS_IPE_DIRECTORY_ERROR 71
#define CBMDOS_IPE_DISK_FULL 72
#define CBMDOS_IPE_DOS_VERSION 73
#define CBMDOS_IPE_NOT_READY 74
#define CBMDOS_IPE_FORMAT_ERROR 75
#define CBMDOS_IPE_BAD_PARTN 77
1581
#define CBMDOS_IPE_NOT_EMPTY 80
dir to remove not empty
#define CBMDOS_IPE_PERMISSION 81
permission denied
#define CBMDOS_FT_DEL 0
CBM DOS File Types.
#define CBMDOS_FT_SEQ 1
#define CBMDOS_FT_PRG 2
#define CBMDOS_FT_USR 3
#define CBMDOS_FT_REL 4
#define CBMDOS_FT_CBM 5
1581 partition
#define CBMDOS_FT_DIR 6
#define CBMDOS_FT_REPLACEMENT 0x20
#define CBMDOS_FT_LOCKED 0x40
#define CBMDOS_FT_CLOSED 0x80
#define CBMDOS_FAM_READ 0
CBM DOS Access Control Methods.
#define CBMDOS_FAM_WRITE 1
#define CBMDOS_FAM_APPEND 2
#define CBMDOS_FAM_EOF 4
#define CBMDOS_SLOT_NAME_LENGTH 16
CBM DOS directory definitions.
Typedefs
typedef enum fdc_err_e fdc_err_t
typedef struct cbmdos_cmd_parse_s cbmdos_cmd_parse_t
typedef struct cbmdos_cmd_parse_plus_s cbmdos_cmd_parse_plus_t
Enumerations
enum fdc_err_e {
CBMDOS_FDC_ERR_OK = 1 ,
CBMDOS_FDC_ERR_HEADER = 2 ,
CBMDOS_FDC_ERR_SYNC = 3 ,
CBMDOS_FDC_ERR_NOBLOCK = 4 ,
CBMDOS_FDC_ERR_DCHECK = 5 ,
CBMDOS_FDC_ERR_VERIFY = 7 ,
CBMDOS_FDC_ERR_WPROT = 8 ,
CBMDOS_FDC_ERR_HCHECK = 9 ,
CBMDOS_FDC_ERR_BLENGTH = 10 ,
CBMDOS_FDC_ERR_ID = 11 ,
CBMDOS_FDC_ERR_FSPEED = 12 ,
CBMDOS_FDC_ERR_DRIVE = 15 ,
CBMDOS_FDC_ERR_DECODE = 16
}
fdc error codes to return to drive CPU
Functions
const char * cbmdos_errortext (unsigned int code)
const char * cbmdos_filetype_get (unsigned int filetype)
unsigned int cbmdos_parse_wildcard_check (const char *name, unsigned int len)
unsigned int cbmdos_parse_wildcard_compare (const uint8_t *name1, const uint8_t *name2)
uint8_t * cbmdos_dir_slot_create (const char *name, unsigned int len)
unsigned int cbmdos_command_parse (cbmdos_cmd_parse_t *cmd_parse)
unsigned int cbmdos_command_parse_plus (cbmdos_cmd_parse_plus_t *cmd_parse)
Macro Definition Documentation
CBMDOS_FAM_APPEND
#define CBMDOS_FAM_APPEND 2
CBMDOS_FAM_EOF
#define CBMDOS_FAM_EOF 4
CBMDOS_FAM_READ
#define CBMDOS_FAM_READ 0
CBM DOS Access Control Methods.
CBMDOS_FAM_WRITE
#define CBMDOS_FAM_WRITE 1
CBMDOS_FT_CBM
#define CBMDOS_FT_CBM 5
1581 partition
CBMDOS_FT_CLOSED
#define CBMDOS_FT_CLOSED 0x80
CBMDOS_FT_DEL
#define CBMDOS_FT_DEL 0
CBM DOS File Types.
should match FILEIO_TYPE_xxx
CBMDOS_FT_DIR
#define CBMDOS_FT_DIR 6
CBMDOS_FT_LOCKED
#define CBMDOS_FT_LOCKED 0x40
CBMDOS_FT_PRG
#define CBMDOS_FT_PRG 2
CBMDOS_FT_REL
#define CBMDOS_FT_REL 4
CBMDOS_FT_REPLACEMENT
#define CBMDOS_FT_REPLACEMENT 0x20
CBMDOS_FT_SEQ
#define CBMDOS_FT_SEQ 1
CBMDOS_FT_USR
#define CBMDOS_FT_USR 3
CBMDOS_IPE_BAD_NAME
#define CBMDOS_IPE_BAD_NAME 33
CBMDOS_IPE_BAD_PARTN
#define CBMDOS_IPE_BAD_PARTN 77
1581
CBMDOS_IPE_BAD_TYPE
#define CBMDOS_IPE_BAD_TYPE 64
CBMDOS_IPE_DELETED
#define CBMDOS_IPE_DELETED 1
CBMDOS_IPE_DIRECTORY_ERROR
#define CBMDOS_IPE_DIRECTORY_ERROR 71
CBMDOS_IPE_DISK_FULL
#define CBMDOS_IPE_DISK_FULL 72
CBMDOS_IPE_DISK_ID_MISMATCH
#define CBMDOS_IPE_DISK_ID_MISMATCH 29
CBMDOS_IPE_DOS_VERSION
#define CBMDOS_IPE_DOS_VERSION 73
CBMDOS_IPE_FILE_EXISTS
#define CBMDOS_IPE_FILE_EXISTS 63
CBMDOS_IPE_FORMAT_ERROR
#define CBMDOS_IPE_FORMAT_ERROR 75
CBMDOS_IPE_ILLEGAL_SYSTEM_T_OR_S
#define CBMDOS_IPE_ILLEGAL_SYSTEM_T_OR_S 67
1581
CBMDOS_IPE_ILLEGAL_TRACK_OR_SECTOR
#define CBMDOS_IPE_ILLEGAL_TRACK_OR_SECTOR 66
CBMDOS_IPE_INVAL
#define CBMDOS_IPE_INVAL 31
CBMDOS_IPE_LONG_LINE
#define CBMDOS_IPE_LONG_LINE 32
CBMDOS_IPE_MEMORY_READ
#define CBMDOS_IPE_MEMORY_READ 4
CBMDOS_IPE_NO_BLOCK
#define CBMDOS_IPE_NO_BLOCK 65
CBMDOS_IPE_NO_CHANNEL
#define CBMDOS_IPE_NO_CHANNEL 70
CBMDOS_IPE_NO_NAME
#define CBMDOS_IPE_NO_NAME 34
CBMDOS_IPE_NO_RECORD
#define CBMDOS_IPE_NO_RECORD 50
CBMDOS_IPE_NOT_EMPTY
#define CBMDOS_IPE_NOT_EMPTY 80
dir to remove not empty
CBMDOS_IPE_NOT_FOUND
#define CBMDOS_IPE_NOT_FOUND 62
CBMDOS_IPE_NOT_OPEN
#define CBMDOS_IPE_NOT_OPEN 61
CBMDOS_IPE_NOT_READY
#define CBMDOS_IPE_NOT_READY 74
CBMDOS_IPE_NOT_WRITE
#define CBMDOS_IPE_NOT_WRITE 60
CBMDOS_IPE_OK
#define CBMDOS_IPE_OK 0
CBM DOS Input Processor Error Codes.
CBMDOS_IPE_OVERFLOW
#define CBMDOS_IPE_OVERFLOW 51
CBMDOS_IPE_PATH_NOT_FOUND
#define CBMDOS_IPE_PATH_NOT_FOUND 39
CBMDOS_IPE_PERMISSION
#define CBMDOS_IPE_PERMISSION 81
permission denied
CBMDOS_IPE_READ_ERROR_BCHK
#define CBMDOS_IPE_READ_ERROR_BCHK 27
CBMDOS_IPE_READ_ERROR_BNF
#define CBMDOS_IPE_READ_ERROR_BNF 20
CBMDOS_IPE_READ_ERROR_CHK
#define CBMDOS_IPE_READ_ERROR_CHK 23
CBMDOS_IPE_READ_ERROR_DATA
#define CBMDOS_IPE_READ_ERROR_DATA 22
CBMDOS_IPE_READ_ERROR_GCR
#define CBMDOS_IPE_READ_ERROR_GCR 24
CBMDOS_IPE_READ_ERROR_SYNC
#define CBMDOS_IPE_READ_ERROR_SYNC 21
CBMDOS_IPE_SEL_PARTN
#define CBMDOS_IPE_SEL_PARTN 2
1581
CBMDOS_IPE_SYNTAX
#define CBMDOS_IPE_SYNTAX 30
CBMDOS_IPE_TOOLARGE
#define CBMDOS_IPE_TOOLARGE 52
1581
CBMDOS_IPE_UNIMPL
#define CBMDOS_IPE_UNIMPL 3
CBMDOS_IPE_WRITE_ERROR_BIG
#define CBMDOS_IPE_WRITE_ERROR_BIG 28
CBMDOS_IPE_WRITE_ERROR_VER
#define CBMDOS_IPE_WRITE_ERROR_VER 25
CBMDOS_IPE_WRITE_PROTECT_ON
#define CBMDOS_IPE_WRITE_PROTECT_ON 26
CBMDOS_SLOT_NAME_LENGTH
#define CBMDOS_SLOT_NAME_LENGTH 16
CBM DOS directory definitions.
Length of a CBMDOS PETSCII file name
Typedef Documentation
cbmdos_cmd_parse_plus_t
typedef struct cbmdos_cmd_parse_plus_s cbmdos_cmd_parse_plus_t
cbmdos_cmd_parse_t
typedef struct cbmdos_cmd_parse_s cbmdos_cmd_parse_t
fdc_err_t
typedef enum fdc_err_e fdc_err_t
Enumeration Type Documentation
fdc_err_e
enum fdc_err_e
fdc error codes to return to drive CPU
Enumerator
CBMDOS_FDC_ERR_OK
CBMDOS_FDC_ERR_HEADER
CBMDOS_FDC_ERR_SYNC
CBMDOS_FDC_ERR_NOBLOCK
CBMDOS_FDC_ERR_DCHECK
CBMDOS_FDC_ERR_VERIFY
CBMDOS_FDC_ERR_WPROT
CBMDOS_FDC_ERR_HCHECK
CBMDOS_FDC_ERR_BLENGTH
CBMDOS_FDC_ERR_ID
CBMDOS_FDC_ERR_FSPEED
CBMDOS_FDC_ERR_DRIVE
CBMDOS_FDC_ERR_DECODE
Function Documentation
cbmdos_command_parse()
unsigned int cbmdos_command_parse (cbmdos_cmd_parse_t * cmd_parse)
Referenced by fsdevice_open().
cbmdos_command_parse_plus()
unsigned int cbmdos_command_parse_plus (cbmdos_cmd_parse_plus_t * cmd_parse)
Todo:
CMD limits paths by having them begin and end with a '/'
Referenced by vdrive_command_copy(), vdrive_command_execute(), vdrive_command_format(), vdrive_command_rename(), vdrive_command_renamepart(), vdrive_command_scratch(), and vdrive_iec_open().
cbmdos_dir_slot_create()
uint8_t * cbmdos_dir_slot_create (const char * name, unsigned int len)
Referenced by cbmfile_find_file(), p00_file_find(), vdrive_dir_find_first_slot(), and vdrive_dir_part_find_first_slot().
cbmdos_errortext()
const char * cbmdos_errortext (unsigned int code)
Referenced by fsdevice_error(), and vdrive_command_set_error().
cbmdos_filetype_get()
const char * cbmdos_filetype_get (unsigned int filetype)
Referenced by diskcontents_block_read(), and vdrive_dir_next_directory().
cbmdos_parse_wildcard_check()
unsigned int cbmdos_parse_wildcard_check (const char * name, unsigned int len)
Referenced by cbmfile_open(), fsdevice_open_directory(), and fsdevice_open_file().
cbmdos_parse_wildcard_compare()
unsigned int cbmdos_parse_wildcard_compare (const uint8_t * name1, const uint8_t * name2)
Referenced by cbmfile_find_file(), p00_file_find(), vdrive_dir_name_match(), and vdrive_dir_part_name_match().