x128: autostart.h File Reference
autostart.h File Reference
#include "types.h"
Macros
#define AUTOSTART_MODE_NONE -1
#define AUTOSTART_MODE_RUN 0
#define AUTOSTART_MODE_LOAD 1
Enumerations
enum {
AUTOSTART_DROP_MODE_ATTACH ,
AUTOSTART_DROP_MODE_LOAD ,
AUTOSTART_DROP_MODE_RUN
}
Behaviour for autostart when dropping media onto the emulator window.
Functions
int autostart_resources_init (void)
initialize the resources
void autostart_resources_shutdown (void)
int autostart_cmdline_options_init (void)
initialize the command-line options
int autostart_init (int default_seconds, int handle_drive_true_emulation)
Initialize autostart.
void autostart_shutdown (void)
int autostart_autodetect (const char *file_name, const char *program_name, unsigned int program_number, unsigned int runmode)
void autostart_reinit(int default_seconds, int handle_drive_true_emulation);
int autostart_autodetect_opt_prgname (const char *file_prog_name, unsigned int alt_prg_number, unsigned int runmode)
int autostart_disk (int unit, int drive, const char *file_name, const char *program_name, unsigned int program_number, unsigned int runmode)
Autostart disk image ‘file_name’.
int autostart_tape (const char *file_name, const char *program_name, unsigned int program_number, unsigned int runmode, unsigned int tapeport)
Autostart tape image ‘file_name’.
int autostart_prg (const char *file_name, unsigned int runmode)
int autostart_snapshot (const char *file_name, const char *program_name)
Autostart snapshot file ‘file_name’.
int autostart_tapecart (const char *file_name, void *unused)
Autostart tapecart image file_name.
void autostart_disable (void)
void autostart_advance (void)
void autostart_reset (void)
int autostart_device(int unit);
int autostart_in_progress (void)
void autostart_trigger_monitor (int enable)
Control if the monitor will be triggered after an autostart.
int autostart_set_initial_tap_offset (unsigned long offset)
Variables
int autostart_ignore_reset
int autostart_tape_basic_load
Macro Definition Documentation
AUTOSTART_MODE_LOAD
#define AUTOSTART_MODE_LOAD 1
AUTOSTART_MODE_NONE
#define AUTOSTART_MODE_NONE -1
AUTOSTART_MODE_RUN
#define AUTOSTART_MODE_RUN 0
Enumeration Type Documentation
anonymous enum
anonymous enum
Behaviour for autostart when dropping media onto the emulator window.
Enumerator
AUTOSTART_DROP_MODE_ATTACH
attach only
AUTOSTART_DROP_MODE_LOAD
attach and load
AUTOSTART_DROP_MODE_RUN
attach, load and run
Function Documentation
autostart_advance()
void autostart_advance (void)
Referenced by maincpu_mainloop().
autostart_autodetect()
int autostart_autodetect (const char * file_name, const char * program_name, unsigned int program_number, unsigned int runmode)
void autostart_reinit(int default_seconds, int handle_drive_true_emulation);
Referenced by autostart_autodetect_opt_prgname(), do_autostart(), and on_drag_data_received().
autostart_autodetect_opt_prgname()
int autostart_autodetect_opt_prgname (const char * file_prog_name, unsigned int alt_prg_number, unsigned int runmode)
Referenced by initcmdline_check_attach(), and mon_autostart().
autostart_cmdline_options_init()
int autostart_cmdline_options_init (void)
initialize the command-line options
Returns
0 on success, else -1.
Remarks
Registers the command-line options
Referenced by machine_cmdline_options_init().
autostart_disable()
void autostart_disable (void)
Referenced by advance_hasdisk(), advance_hassnapshot(), advance_hastape(), advance_inject(), advance_loadingtape(), advance_pressplayontape(), advance_waitloading(), advance_waitloadready(), and advance_waitsearchingfor().
autostart_disk()
int autostart_disk (int unit, int drive, const char * file_name, const char * program_name, unsigned int program_number, unsigned int runmode)
Autostart disk image ‘file_name’.
Referenced by autostart_autodetect(), disk_dir_autostart_callback(), and do_autostart().
autostart_in_progress()
int autostart_in_progress (void)
Todo:
FIXME: dead code?
Referenced by default_tape_header_type(), event_playback_start(), and event_record_start().
autostart_init()
int autostart_init (int default_seconds, int handle_drive_true_emulation)
Initialize autostart.
Todo:
FIXME: cbm2 and pet pass 0,0 into this function before loading kernal ... why is this?
default_seconds : initial delay before checking for READY handle_tde : if zero, "handle tde at autostart" will never be done
Referenced by machine_specific_init().
autostart_prg()
int autostart_prg (const char * file_name, unsigned int runmode)
Todo:
FIXME: if we want to be able to autostart prg files from different devices than device nr 8, either pass the device nr here, or use some resource for this
Referenced by autostart_autodetect(), and do_smart_attach().
autostart_reset()
void autostart_reset (void)
int autostart_device(int unit);
int autostart_device(int unit);
Todo:
FIXME: pass device nr into this function
Referenced by machine_reset().
autostart_resources_init()
int autostart_resources_init (void)
initialize the resources
Returns
0 on success, else -1.
Remarks
Registers the integer resources
Referenced by machine_resources_init().
autostart_resources_shutdown()
void autostart_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
autostart_set_initial_tap_offset()
int autostart_set_initial_tap_offset (unsigned long offset)
autostart_shutdown()
void autostart_shutdown (void)
Referenced by machine_shutdown().
autostart_snapshot()
int autostart_snapshot (const char * file_name, const char * program_name)
Autostart snapshot file ‘file_name’.
Referenced by autostart_autodetect(), and do_smart_attach().
autostart_tape()
int autostart_tape (const char * file_name, const char * program_name, unsigned int program_number, unsigned int runmode, unsigned int tapeport)
Autostart tape image ‘file_name’.
Todo:
FIXME: this should perhaps be handled differently for tape
Referenced by autostart_autodetect(), do_autostart(), and tape_dir_autostart_callback().
autostart_tapecart()
int autostart_tapecart (const char * file_name, void * unused)
Autostart tapecart image file_name.
Parameters
[in] file_name path to tapecart image
[in] unused unused
Returns
0 on success, -1 on failure
Todo:
FIXME: make sure init_drive_emulation_state() does the right thing in this function (perhaps we need to handle all drives?)
Todo:
FIXME: this likely needs to be handled differently for tapecart
Todo:
FIXME: may be 2 on xpet
Referenced by autostart_autodetect().
autostart_trigger_monitor()
void autostart_trigger_monitor (int enable)
Control if the monitor will be triggered after an autostart.
Referenced by mon_autostart().
Variable Documentation
autostart_ignore_reset
int autostart_ignore_reset extern
Referenced by autostart_reset(), and reboot_for_autostart().
autostart_tape_basic_load
int autostart_tape_basic_load extern
Referenced by default_tape_header_type(), and set_autostart_tape_basic_load().