vsid: arch/shared/sounddrv/soundmovie.c File Reference
soundmovie.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "log.h"
#include "sound.h"
#include "resources.h"
#include "types.h"
#include "archdep.h"
#include "soundmovie.h"
Functions
int soundmovie_start (soundmovie_funcs_t *f)
int soundmovie_stop (void)
static int soundmovie_init (const char *param, int *speed, int *fragsize, int *fragnr, int *channels)
static int soundmovie_write (int16_t *pbuf, size_t nr)
encode nr samples from pbuf
static void soundmovie_close (void)
int sound_init_movie_device (void)
Variables
static soundmovie_buffer_t * buffer = NULL
static soundmovie_funcs_t * funcs = NULL
static const sound_device_t soundmovie_device
Function Documentation
sound_init_movie_device()
int sound_init_movie_device (void)
soundmovie_close()
static void soundmovie_close (void) static
soundmovie_init()
static int soundmovie_init (const char * param, int * speed, int * fragsize, int * fragnr, int * channels) static
soundmovie_start()
int soundmovie_start (soundmovie_funcs_t * f)
Referenced by ffmpegexedrv_save(), and zmbvdrv_save().
soundmovie_stop()
int soundmovie_stop (void)
Referenced by ffmpegexedrv_close(), and zmbvdrv_close().
soundmovie_write()
static int soundmovie_write (int16_t * pbuf, size_t nr) static
encode nr samples from pbuf
Variable Documentation
buffer
soundmovie_buffer_t* buffer = NULL static
Referenced by soundmovie_init(), and soundmovie_write().
funcs
soundmovie_funcs_t* funcs = NULL static
Referenced by mousedrv_resources_init(), soundmovie_close(), soundmovie_init(), soundmovie_start(), and soundmovie_write().
soundmovie_device
const sound_device_t soundmovie_device static
Initial value:
=
{
    "soundmovie",
    soundmovie_init,
    soundmovie_write,
    NULL,
    NULL,
    NULL,
    soundmovie_close,
    NULL,
    NULL,
    0,
    2,
    false
}
Referenced by sound_init_movie_device().