x128: printerdrv/output-graphics.c File Reference
output-graphics.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lib.h"
#include "log.h"
#include "cmdline.h"
#include "gfxoutput.h"
#include "output-select.h"
#include "output-graphics.h"
#include "output.h"
#include "palette.h"
#include "resources.h"
#include "screenshot.h"
#include "types.h"
#include "util.h"
Data Structures
struct output_gfx_s
Macros
#define DBG(x)
Typedefs
typedef struct output_gfx_s output_gfx_t
Functions
static uint8_t output_pixel_to_palette_index (uint8_t pix)
static void output_graphics_line_data (screenshot_t *screenshot, uint8_t *data, unsigned int line, unsigned int mode)
static int advance_outfile_name (unsigned int prnr)
static int output_graphics_open (unsigned int prnr, output_parameter_t *output_parameter)
static void output_graphics_close (unsigned int prnr)
static int output_graphics_putc (unsigned int prnr, uint8_t b)
static int output_graphics_getc (unsigned int prnr, uint8_t *b)
static int output_graphics_flush (unsigned int prnr)
static int output_graphics_formfeed (unsigned int prnr)
void output_graphics_init (void)
void output_graphics_shutdown (void)
int output_graphics_init_resources (void)
Variables
static output_gfx_t output_gfx [4]
static unsigned int current_prnr
Macro Definition Documentation
DBG
#define DBG (x)
Typedef Documentation
output_gfx_t
typedef struct output_gfx_s output_gfx_t
Function Documentation
advance_outfile_name()
static int advance_outfile_name (unsigned int prnr) static
Referenced by output_graphics_open(), and output_graphics_putc().
output_graphics_close()
static void output_graphics_close (unsigned int prnr) static
Referenced by output_graphics_formfeed(), and output_graphics_init_resources().
output_graphics_flush()
static int output_graphics_flush (unsigned int prnr) static
Referenced by output_graphics_init_resources().
output_graphics_formfeed()
static int output_graphics_formfeed (unsigned int prnr) static
Referenced by output_graphics_init_resources().
output_graphics_getc()
static int output_graphics_getc (unsigned int prnr, uint8_t * b) static
Referenced by output_graphics_init_resources().
output_graphics_init()
void output_graphics_init (void)
< serial dev 4, 5, 6 and user port
Referenced by printer_init().
output_graphics_init_resources()
int output_graphics_init_resources (void)
Referenced by printer_resources_init().
output_graphics_line_data()
static void output_graphics_line_data (screenshot_t * screenshot, uint8_t * data, unsigned int line, unsigned int mode) static
Referenced by output_graphics_open().
output_graphics_open()
static int output_graphics_open (unsigned int prnr, output_parameter_t * output_parameter) static
Referenced by output_graphics_init_resources().
output_graphics_putc()
static int output_graphics_putc (unsigned int prnr, uint8_t b) static
Referenced by output_graphics_init_resources().
output_graphics_shutdown()
void output_graphics_shutdown (void)
< serial dev 4, 5, 6 and user port
Referenced by printer_shutdown().
output_pixel_to_palette_index()
static uint8_t output_pixel_to_palette_index (uint8_t pix) static
Referenced by output_graphics_line_data().
Variable Documentation
current_prnr
unsigned int current_prnr static
Referenced by output_graphics_close(), output_graphics_formfeed(), output_graphics_line_data(), and output_graphics_putc().
output_gfx
output_gfx_t output_gfx[4] static
Referenced by advance_outfile_name(), output_graphics_close(), output_graphics_formfeed(), output_graphics_init(), output_graphics_line_data(), output_graphics_open(), output_graphics_putc(), and output_graphics_shutdown().