vsid: c64/plus256k.h File Reference
plus256k.h File Reference
#include "snapshot.h"
#include "types.h"
Functions
int plus256k_resources_init (void)
void plus256k_resources_shutdown (void)
int plus256k_cmdline_options_init (void)
void plus256k_init (void)
void plus256k_reset (void)
void plus256k_shutdown (void)
void plus256k_ram_inject (uint16_t addr, uint8_t value)
void plus256k_ram_low_store (uint16_t addr, uint8_t value)
void plus256k_ram_high_store (uint16_t addr, uint8_t value)
uint8_t plus256k_ram_low_read (uint16_t addr)
uint8_t plus256k_ram_high_read (uint16_t addr)
int set_plus256k_enabled (int value, int disable_reset)
int plus256k_snapshot_write (struct snapshot_s *s)
int plus256k_snapshot_read (struct snapshot_s *s)
Variables
int plus256k_enabled
Function Documentation
plus256k_cmdline_options_init()
int plus256k_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
plus256k_init()
void plus256k_init (void)
Referenced by machine_specific_init().
plus256k_ram_high_read()
uint8_t plus256k_ram_high_read (uint16_t addr)
Referenced by plus256k_init_config().
plus256k_ram_high_store()
void plus256k_ram_high_store (uint16_t addr, uint8_t value)
Referenced by plus256k_init_config(), and plus256k_ram_inject().
plus256k_ram_inject()
void plus256k_ram_inject (uint16_t addr, uint8_t value)
Referenced by memory_hacks_ram_inject().
plus256k_ram_low_read()
uint8_t plus256k_ram_low_read (uint16_t addr)
Referenced by plus256k_init_config(), and zero_read_dma().
plus256k_ram_low_store()
void plus256k_ram_low_store (uint16_t addr, uint8_t value)
Referenced by plus256k_init_config(), plus256k_ram_inject(), zero_store(), and zero_store_dma().
plus256k_reset()
void plus256k_reset (void)
Referenced by machine_specific_reset(), and plus256k_activate().
plus256k_resources_init()
int plus256k_resources_init (void)
Referenced by machine_resources_init().
plus256k_resources_shutdown()
void plus256k_resources_shutdown (void)
Referenced by machine_resources_shutdown().
plus256k_shutdown()
void plus256k_shutdown (void)
Referenced by machine_specific_shutdown().
plus256k_snapshot_read()
int plus256k_snapshot_read (struct snapshot_s * s)
Referenced by memhacks_snapshot_read_modules().
plus256k_snapshot_write()
int plus256k_snapshot_write (struct snapshot_s * s)
Referenced by memhacks_snapshot_write_modules().
set_plus256k_enabled()
int set_plus256k_enabled (int value, int disable_reset)
Referenced by memhacks_snapshot_read_modules(), plus256k_snapshot_read(), and set_memory_hack().
Variable Documentation
plus256k_enabled
int plus256k_enabled extern
Referenced by plus256k_init_config(), plus256k_reset(), plus256k_shutdown(), set_plus256k_enabled(), set_plus256k_filename(), zero_read_dma(), zero_store(), and zero_store_dma().