x128: arch/gtk3/uihotkeyssave.c File Reference
uihotkeyssave.c File Reference
File dialog to save a hotkeys file.
#include "vice.h"
#include <gtk/gtk.h>
#include "archdep.h"
#include "debug_gtk3.h"
#include "filechooserhelpers.h"
#include "hotkeys.h"
#include "lib.h"
#include "savefiledialog.h"
#include "resources.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uihotkeys.h"
#include "util.h"
#include "uihotkeyssave.h"
Functions
static void on_destroy (GtkDialog *dialog, gpointer data)
Handler for the 'destroy' event of the dialog.
static void save_callback (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the save dialog.
void ui_hotkeys_save_dialog_show (void)
Show dialog to save a hotkeys file.
Detailed Description
File dialog to save a hotkeys file.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_destroy()
static void on_destroy (GtkDialog * dialog, gpointer data) static
Handler for the 'destroy' event of the dialog.
Parameters
[in] dialog dialog
[in] data extra event data (unused)
Referenced by ui_hotkeys_save_dialog_show().
save_callback()
static void save_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the save dialog.
Parameters
[in] dialog dialog
[in] filename filename entered by user
[in] data extra event data (unused)
Referenced by ui_hotkeys_save_dialog_show().
ui_hotkeys_save_dialog_show()
void ui_hotkeys_save_dialog_show (void)
Show dialog to save a hotkeys file.
Referenced by hotkeys_save_to_action().