x128: arch/gtk3/vice_gtk3_locking.c File Reference
vice_gtk3_locking.c File Reference
GTK3 signal handling helper functions.
#include "vice.h"
#include <stdlib.h>
#include "vice_gtk3_locking.h"
#include "mainlock.h"
Functions
static void vice_gtk3_lock (gpointer data, GClosure *closure)
static void vice_gtk3_unlock (gpointer data, GClosure *closure)
gulong vice_locking_g_signal_connect (gpointer instance, const gchar *detailed_signal, GCallback signal_handler, gpointer data, const char *signal_handler_name)
gulong vice_locking_g_signal_connect_swapped (gpointer instance, const gchar *detailed_signal, GCallback c_handler, gpointer data, const char *signal_handler_name)
Replacement for g_signal_connect_swapped() implementing locking.
void vice_locking_gtk_accel_group_connect (GtkAccelGroup *accel_group, guint accel_key, GdkModifierType accel_mods, GtkAccelFlags accel_flags, GClosure *closure)
Detailed Description
GTK3 signal handling helper functions.
Author
David Hogan david.nosp@m..q.h.nosp@m.ogan@.nosp@m.gmai.nosp@m.l.com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
vice_gtk3_lock()
static void vice_gtk3_lock (gpointer data, GClosure * closure) static
Referenced by vice_locking_g_signal_connect(), vice_locking_g_signal_connect_swapped(), and vice_locking_gtk_accel_group_connect().
vice_gtk3_unlock()
static void vice_gtk3_unlock (gpointer data, GClosure * closure) static
Referenced by vice_locking_g_signal_connect(), vice_locking_g_signal_connect_swapped(), and vice_locking_gtk_accel_group_connect().
vice_locking_g_signal_connect()
gulong vice_locking_g_signal_connect (gpointer instance, const gchar * detailed_signal, GCallback signal_handler, gpointer data, const char * signal_handler_name)
vice_locking_g_signal_connect_swapped()
gulong vice_locking_g_signal_connect_swapped (gpointer instance, const gchar * detailed_signal, GCallback c_handler, gpointer data, const char * signal_handler_name)
Replacement for g_signal_connect_swapped() implementing locking.
Replacement for g_signal_connect_swapped() that obtains the VICE lock before triggering c_handler and releases the lock afterwards.
Parameters
[in] instance object to connect c_handler to
[in] detailed_signal signal name
[in] c_handler user-defined callback to call for detailed_signal
[in] data object to call c_handler on
[in] signal_handler_name signal handler name ("detailed_signal[${c_handler}]")
Returns
signal handler ID
vice_locking_gtk_accel_group_connect()
void vice_locking_gtk_accel_group_connect (GtkAccelGroup * accel_group, guint accel_key, GdkModifierType accel_mods, GtkAccelFlags accel_flags, GClosure * closure)
Referenced by connect_accelerator().