vsid: sysfile.h File Reference
sysfile.h File Reference
#include <stdio.h>
#include "types.h"
Functions
int sysfile_init (const char *emu_id)
void sysfile_shutdown (void)
int sysfile_resources_init (void)
void sysfile_resources_shutdown (void)
int sysfile_cmdline_options_init (void)
FILE * sysfile_open (const char *name, const char *subpath, char **complete_path_return, const char *open_mode)
Functions to locate/open/load files from the system path.
int sysfile_locate (const char *name, const char *subpath, char **complete_path_return)
int sysfile_load (const char *name, const char *subpath, uint8_t *dest, int minsize, int maxsize)
const char * get_system_path (void)
get the full search path
Function Documentation
get_system_path()
const char * get_system_path (void)
get the full search path
Referenced by sysfile_get_system_path_start().
sysfile_cmdline_options_init()
int sysfile_cmdline_options_init (void)
Referenced by init_cmdline_options().
sysfile_init()
int sysfile_init (const char * emu_id)
Referenced by main_program().
sysfile_load()
int sysfile_load (const char * name, const char * subpath, uint8_t * dest, int minsize, int maxsize)
< read mode (binary)
< directory separator as an integer
< read mode (binary)
Referenced by c64rom_load_basic(), c64rom_load_chargen(), c64rom_load_kernal(), driverom_load(), drv_2022_open(), drv_4023_open(), drv_8023_open(), drv_mps801_open(), drv_mps802_open(), drv_mps803_open(), and drv_nl10_init_charset().
sysfile_locate()
int sysfile_locate (const char * name, const char * subpath, char ** complete_path_return)
< read mode (binary)
Referenced by archdep_app_icon_path_png(), keyboard_is_keymap_valid(), try_set_keymap_file(), uidata_init(), and vhk_parser_open_file().
sysfile_open()
FILE * sysfile_open (const char * name, const char * subpath, char ** complete_path_return, const char * open_mode)
Functions to locate/open/load files from the system path.
Referenced by create_shader_program(), keyboard_parse_keymap(), mon_playback_commands(), palette_load(), romset_file_load(), sysfile_load(), and sysfile_locate().
sysfile_resources_init()
int sysfile_resources_init (void)
Referenced by init_resources().
sysfile_resources_shutdown()
void sysfile_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
sysfile_shutdown()
void sysfile_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().