vsid: arch/gtk3/uifliplist.h File Reference
uifliplist.h File Reference
Fliplist menu management - header.
#include <gtk/gtk.h>
Functions
void ui_populate_fliplist_menu (GtkWidget *menu, int unit, int separator_count)
Fill in a menu with controls for fliplist control.
void ui_fliplist_load_dialog_show (int unit)
Create and show the "load fliplist" dialog.
void ui_fliplist_save_dialog_show (int unit)
Create and show the "save fliplist" dialog.
Detailed Description
Fliplist menu management - header.
Author
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
Function Documentation
ui_fliplist_load_dialog_show()
void ui_fliplist_load_dialog_show (int unit)
Create and show the "load fliplist" dialog.
Parameters
[in] unit Disk unit to load fliplist to, or FLIPLIST_ALL_UNITS
Todo:
add a separate "extra widget" that will let the user select autoattach
Referenced by fliplist_load_action().
ui_fliplist_save_dialog_show()
void ui_fliplist_save_dialog_show (int unit)
Create and show the "save fliplist" dialog.
Parameters
[in] unit Drive unit to save fliplist from, or FLIPLIST_ALL_UNITS
Referenced by fliplist_save_action().
ui_populate_fliplist_menu()
void ui_populate_fliplist_menu (GtkWidget * menu, int unit, int separator_count)
Fill in a menu with controls for fliplist control.
Fliplist controls are placed at the end of a menu, after a separator. Any previously-existing fliplist controls within the menu will be removed.
Parameters
menu The menu to be edited.
unit The drive unit (8-11) that this menu will control.
separator_count The number of menu separators in the part of the menu that does not involve the fliplist.
Todo:
Add/Remove current image to/from fliplist should really be here too.
Referenced by ui_do_drive_popup(), and ui_drive_menu_create().