vsid: core/ciatimer.h File Reference
ciatimer.h File Reference
#include "alarm.h"
#include "types.h"
Data Structures
struct ciat_s
Macros
#define CIAT_TABLEN (2 << 13)
constants
#define CIAT_CR_MASK 0x039
#define CIAT_CR_START 0x001
#define CIAT_CR_ONESHOT 0x008
#define CIAT_CR_FLOAD 0x010
#define CIAT_PHI2IN 0x020
#define CIAT_STEP 0x004
#define CIAT_COUNT2 0x002
#define CIAT_COUNT3 0x040
#define CIAT_COUNT 0x800
#define CIAT_LOAD1 0x080
#define CIAT_ONESHOT0 0x100
#define CIAT_ONESHOT 0x1000
#define CIAT_LOAD 0x200
#define CIAT_OUT 0x400
#define CIAT_LOGIN(a)
Timer debug stuff.
#define CIAT_LOG(a)
#define CIAT_LOGOUT(a)
#define INLINE_CIAT_FUNCS
#define _CIAT_FUNC inline static
Typedefs
typedef uint16_t ciat_tstate_t
types
typedef struct ciat_s ciat_t
Functions
void ciat_init_table (void)
static void ciat_set_alarm (ciat_t *state, CLOCK cclk)
check when the next underflow will occur and set the alarm
static CLOCK ciat_alarm_clk (ciat_t *state)
static int ciat_update (ciat_t *state, CLOCK cclk)
static uint16_t ciat_read_latch (ciat_t *state, CLOCK cclk)
read timer value - ciat_update must have been called before!
static uint16_t ciat_read_timer (ciat_t *state, CLOCK cclk)
read timer value - ciat_update must have been called before!
static uint16_t ciat_is_underflow_clk (ciat_t *state, CLOCK cclk)
static uint16_t ciat_is_running (ciat_t *state, CLOCK cclk)
return 1 when the timer is running - update must have ...
static int ciat_single_step (ciat_t *state, CLOCK cclk)
single-step a timer.
static void ciat_set_latchhi (ciat_t *state, CLOCK cclk, uint8_t byte)
static void ciat_set_latchlo (ciat_t *state, CLOCK cclk, uint8_t byte)
static void ciat_set_ctrl (ciat_t *state, CLOCK cclk, uint8_t byte)
needs update before
static void ciat_ack_alarm (ciat_t *state, CLOCK cclk)
void ciat_init (ciat_t *state, const char *name, CLOCK cclk, alarm_t *alarm)
void ciat_reset (ciat_t *state, CLOCK cclk)
timer reset
void ciat_prevent_clock_overflow (ciat_t *state, CLOCK sub)
handle clock overflow.
void ciat_save_snapshot (ciat_t *cia_state, CLOCK cclk, struct snapshot_module_s *m, int ver)
void ciat_load_snapshot (ciat_t *state, CLOCK cclk, uint16_t cnt, uint16_t latch, uint8_t cr, struct snapshot_module_s *m, int ver)
Variables
ciat_tstate_t ciat_table [(2<< 13)]
external prototypes
Macro Definition Documentation
_CIAT_FUNC
#define _CIAT_FUNC inline static
CIAT_COUNT
#define CIAT_COUNT 0x800
CIAT_COUNT2
#define CIAT_COUNT2 0x002
CIAT_COUNT3
#define CIAT_COUNT3 0x040
CIAT_CR_FLOAD
#define CIAT_CR_FLOAD 0x010
CIAT_CR_MASK
#define CIAT_CR_MASK 0x039
CIAT_CR_ONESHOT
#define CIAT_CR_ONESHOT 0x008
CIAT_CR_START
#define CIAT_CR_START 0x001
CIAT_LOAD
#define CIAT_LOAD 0x200
CIAT_LOAD1
#define CIAT_LOAD1 0x080
CIAT_LOG
#define CIAT_LOG (a)
CIAT_LOGIN
#define CIAT_LOGIN (a)
Timer debug stuff.
CIAT_LOGOUT
#define CIAT_LOGOUT (a)
CIAT_ONESHOT
#define CIAT_ONESHOT 0x1000
CIAT_ONESHOT0
#define CIAT_ONESHOT0 0x100
CIAT_OUT
#define CIAT_OUT 0x400
CIAT_PHI2IN
#define CIAT_PHI2IN 0x020
CIAT_STEP
#define CIAT_STEP 0x004
CIAT_TABLEN
#define CIAT_TABLEN (2 << 13)
constants
INLINE_CIAT_FUNCS
#define INLINE_CIAT_FUNCS
Typedef Documentation
ciat_t
typedef struct ciat_s ciat_t
ciat_tstate_t
typedef uint16_t ciat_tstate_t
types
Function Documentation
ciat_ack_alarm()
static void ciat_ack_alarm (ciat_t * state, CLOCK cclk) inline static
Referenced by ciacore_intta(), and ciacore_inttb().
ciat_alarm_clk()
static CLOCK ciat_alarm_clk (ciat_t * state) inline static
Referenced by cia_ifr_current(), cia_update_ta(), and cia_update_tb().
ciat_init()
void ciat_init (ciat_t * state, const char * name, CLOCK cclk, alarm_t * alarm)
Referenced by ciacore_init().
ciat_init_table()
void ciat_init_table (void)
Referenced by ciacore_init().
ciat_is_running()
static uint16_t ciat_is_running (ciat_t * state, CLOCK cclk) inline static
return 1 when the timer is running - update must have ...
ciat_is_underflow_clk()
static uint16_t ciat_is_underflow_clk (ciat_t * state, CLOCK cclk) inline static
Referenced by ciacore_snapshot_write_module(), and ciacore_update_pb67().
ciat_load_snapshot()
void ciat_load_snapshot (ciat_t * state, CLOCK cclk, uint16_t cnt, uint16_t latch, uint8_t cr, struct snapshot_module_s * m, int ver)
Referenced by ciacore_snapshot_read_module().
ciat_prevent_clock_overflow()
void ciat_prevent_clock_overflow (ciat_t * state, CLOCK sub)
handle clock overflow.
needs update
ciat_read_latch()
static uint16_t ciat_read_latch (ciat_t * state, CLOCK cclk) inline static
read timer value - ciat_update must have been called before!
Referenced by ciacore_intta(), and ciacore_snapshot_write_module().
ciat_read_timer()
static uint16_t ciat_read_timer (ciat_t * state, CLOCK cclk) inline static
read timer value - ciat_update must have been called before!
Referenced by ciacore_snapshot_write_module().
ciat_reset()
void ciat_reset (ciat_t * state, CLOCK cclk)
timer reset
Referenced by ciacore_reset().
ciat_save_snapshot()
void ciat_save_snapshot (ciat_t * cia_state, CLOCK cclk, struct snapshot_module_s * m, int ver)
Referenced by ciacore_snapshot_write_module().
ciat_set_alarm()
static void ciat_set_alarm (ciat_t * state, CLOCK cclk) inline static
check when the next underflow will occur and set the alarm
needs update before
Referenced by ciacore_intta(), ciacore_inttb(), ciacore_store_internal(), ciat_load_snapshot(), ciat_set_ctrl(), ciat_set_latchhi(), ciat_set_latchlo(), and ciat_single_step().
ciat_set_ctrl()
static void ciat_set_ctrl (ciat_t * state, CLOCK cclk, uint8_t byte) inline static
needs update before
Referenced by ciacore_snapshot_read_module(), and ciacore_store_internal().
ciat_set_latchhi()
static void ciat_set_latchhi (ciat_t * state, CLOCK cclk, uint8_t byte) inline static
Referenced by ciacore_store_internal().
ciat_set_latchlo()
static void ciat_set_latchlo (ciat_t * state, CLOCK cclk, uint8_t byte) inline static
Referenced by ciacore_store_internal().
ciat_single_step()
static int ciat_single_step (ciat_t * state, CLOCK cclk) inline static
single-step a timer.
update must have been called before
Referenced by cia_do_step_tb().
ciat_update()
static int ciat_update (ciat_t * state, CLOCK cclk) inline static
Referenced by cia_do_update_ta(), and cia_do_update_tb().
Variable Documentation
ciat_table
ciat_tstate_t ciat_table[(2<< 13)] extern
external prototypes
Referenced by ciat_init_table(), ciat_set_alarm(), and ciat_update().