x128: vdrive/vdrive-bam.h File Reference
vdrive-bam.h File Reference
#include "types.h"
Macros
#define BAM_FIRST_TRACK 0
#define BAM_FIRST_SECTOR 1
#define BAM_FORMAT_TYPE 2
#define BAM_BIT_MAP 4
start of bitmap in each BAM blk
#define BAM_BIT_MAP_1581 16
#define BAM_BIT_MAP_8050 6
#define BAM_BIT_MAP_8250 BAM_BIT_MAP_8050
#define BAM_BIT_MAP_NP 32
#define BAM_BIT_MAP_9000 16
#define BAM_VERSION_1541
#define BAM_VERSION_1581 25
#define BAM_VERSION_8050 27
#define BAM_VERSION_8250 BAM_VERSION_8050
#define BAM_VERSION_NP 25
#define BAM_VERSION_9000 27
Functions
int vdrive_bam_allocate_chain (struct vdrive_s *vdrive, unsigned int t, unsigned int s)
follow a passed t/s location and allocate all used sectors (used for validate)
int vdrive_bam_allocate_chain_255 (struct vdrive_s *vdrive, unsigned int t, unsigned int s)
returns DOS error values, 0 = okay, etc
int vdrive_bam_alloc_first_free_sector (struct vdrive_s *vdrive, unsigned int *track, unsigned int *sector)
int vdrive_bam_alloc_next_free_sector (struct vdrive_s *vdrive, unsigned int *track, unsigned int *sector)
similar to above, but the default interleave is used.
int vdrive_bam_alloc_next_free_sector_interleave (struct vdrive_s *vdrive, unsigned int *track, unsigned int *sector, unsigned int interleave)
int vdrive_bam_allocate_sector (struct vdrive_s *vdrive, unsigned int track, unsigned int sector)
allocate a t/s in the bam
int vdrive_bam_is_sector_allocated (struct vdrive_s *vdrive, unsigned int track, unsigned int sector)
check to see if a sector is allocated
void vdrive_bam_clear_all (struct vdrive_s *vdrive)
used by validate to clear out bam - sets all blocks as used
void vdrive_bam_create_empty_bam (struct vdrive_s *vdrive, const char *name, uint8_t *id)
used by format to setup bam/dir values
int unsigned vdrive_bam_free_block_count (struct vdrive_s *vdrive)
int vdrive_bam_free_sector (struct vdrive_s *vdrive, unsigned int track, unsigned int sector)
unallocate a t/s in the bam
int vdrive_bam_int_get_disk_id (struct vdrive_s *vdrive, uint8_t *id)
get disk id internally
int vdrive_bam_get_disk_id (unsigned int unit, unsigned int drive, uint8_t *id)
get disk id
int vdrive_bam_set_disk_id (unsigned int unit, unsigned int drive, uint8_t *id)
set disk id
int vdrive_bam_read_bam (struct vdrive_s *vdrive)
int vdrive_bam_write_bam (struct vdrive_s *vdrive)
Update ALL bam data back to image.
int vdrive_bam_isgeos (struct vdrive_s *vdrive)
void vdrive_bam_setup_bam (struct vdrive_s *vdrive)
Macro Definition Documentation
BAM_BIT_MAP
#define BAM_BIT_MAP 4
start of bitmap in each BAM blk
BAM_BIT_MAP_1581
#define BAM_BIT_MAP_1581 16
BAM_BIT_MAP_8050
#define BAM_BIT_MAP_8050 6
BAM_BIT_MAP_8250
#define BAM_BIT_MAP_8250 BAM_BIT_MAP_8050
BAM_BIT_MAP_9000
#define BAM_BIT_MAP_9000 16
BAM_BIT_MAP_NP
#define BAM_BIT_MAP_NP 32
BAM_FIRST_SECTOR
#define BAM_FIRST_SECTOR 1
BAM_FIRST_TRACK
#define BAM_FIRST_TRACK 0
BAM_FORMAT_TYPE
#define BAM_FORMAT_TYPE 2
BAM_VERSION_1541
#define BAM_VERSION_1541
Value:
                                           165     /* position of DOS version (2A/2C)
                                           in BAM blk */
BAM_VERSION_1581
#define BAM_VERSION_1581 25
BAM_VERSION_8050
#define BAM_VERSION_8050 27
BAM_VERSION_8250
#define BAM_VERSION_8250 BAM_VERSION_8050
BAM_VERSION_9000
#define BAM_VERSION_9000 27
BAM_VERSION_NP
#define BAM_VERSION_NP 25
Function Documentation
vdrive_bam_alloc_first_free_sector()
int vdrive_bam_alloc_first_free_sector (struct vdrive_s * vdrive, unsigned int * track, unsigned int * sector)
Referenced by iec_open_write(), iec_write_sequential(), internal_write_geos_file(), vdrive_command_copy(), and vdrive_rel_add_sector().
vdrive_bam_alloc_next_free_sector()
int vdrive_bam_alloc_next_free_sector (struct vdrive_s * vdrive, unsigned int * track, unsigned int * sector)
similar to above, but the default interleave is used.
Referenced by iec_write_sequential(), internal_write_geos_file(), vdrive_bam_alloc_first_free_sector(), vdrive_command_block(), vdrive_command_copy(), vdrive_command_mkdir(), and vdrive_rel_add_sector().
vdrive_bam_alloc_next_free_sector_interleave()
int vdrive_bam_alloc_next_free_sector_interleave (struct vdrive_s * vdrive, unsigned int * track, unsigned int * sector, unsigned int interleave)
Referenced by vdrive_bam_alloc_next_free_sector(), and vdrive_dir_find_next_slot().
vdrive_bam_allocate_chain()
int vdrive_bam_allocate_chain (vdrive_t * vdrive, unsigned int t, unsigned int s)
follow a passed t/s location and allocate all used sectors (used for validate)
returns DOS error values, 0 = okay, etc
Referenced by vdrive_command_validate().
vdrive_bam_allocate_chain_255()
int vdrive_bam_allocate_chain_255 (struct vdrive_s * vdrive, unsigned int t, unsigned int s)
returns DOS error values, 0 = okay, etc
Referenced by vdrive_command_validate().
vdrive_bam_allocate_sector()
int vdrive_bam_allocate_sector (vdrive_t * vdrive, unsigned int track, unsigned int sector)
allocate a t/s in the bam
return of 1 if okay, 0 if failed (1571 > 70 tracks) or already allocated
< number of tracks on a 1571 floppy
Referenced by find_next_directory_sector(), vdrive_bam_alloc_next_free_sector_interleave(), vdrive_bam_alloc_worker(), vdrive_bam_allocate_chain(), vdrive_bam_allocate_chain_255(), vdrive_command_allocate_chain(), vdrive_command_block(), vdrive_command_chpart(), vdrive_command_validate(), and vdrive_command_validate_worker().
vdrive_bam_clear_all()
void vdrive_bam_clear_all (struct vdrive_s * vdrive)
used by validate to clear out bam - sets all blocks as used
< BAM bitmap entries for tracks 36-40 for extended floppies, only valid for SpeedDOS
< Dual Disk Drive
< start of bitmap in each BAM blk
< number of tracks on a standard 1541 floppy
< start of bitmap in each BAM blk
< number of tracks on a 1571 floppy
< BAM bitmap entries for tracks 36-40 for extended floppies (did these exist?)
< number of tracks on a 1571 floppy
< number of tracks on a 1571 floppy
< number of tracks on a 1581 diskette
< number of tracks on a 1581 diskette
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_command_validate().
vdrive_bam_create_empty_bam()
void vdrive_bam_create_empty_bam (struct vdrive_s * vdrive, const char * name, uint8_t * id)
used by format to setup bam/dir values
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_command_format_worker().
vdrive_bam_free_block_count()
int unsigned vdrive_bam_free_block_count (struct vdrive_s * vdrive)
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
< number of tracks on a 1571 floppy
< BAM bitmap entries for tracks 36-40 for extended floppies (did these exist?)
< number of tracks on a 1571 floppy
Referenced by diskcontents_block_read(), vdrive_command_copy(), vdrive_command_mkdir(), and vdrive_dir_next_directory().
vdrive_bam_free_sector()
int vdrive_bam_free_sector (vdrive_t * vdrive, unsigned int track, unsigned int sector)
unallocate a t/s in the bam
return of 1 if okay, 0 if failed (1571 > 70 tracks) or already allocated
< number of tracks on a 1571 floppy
Referenced by vdrive_command_block(), vdrive_command_copy(), vdrive_command_mkdir(), vdrive_command_scratch(), vdrive_command_validate(), vdrive_dir_find_next_slot(), and vdrive_dir_free_chain().
vdrive_bam_get_disk_id()
int vdrive_bam_get_disk_id (unsigned int unit, unsigned int drive, uint8_t * id)
get disk id
Referenced by disk_eof_callback(), and file_system_bam_get_disk_id().
vdrive_bam_int_get_disk_id()
int vdrive_bam_int_get_disk_id (struct vdrive_s * vdrive, uint8_t * id)
get disk id internally
Referenced by vdrive_bam_get_disk_id(), and vdrive_command_format_worker().
vdrive_bam_is_sector_allocated()
int vdrive_bam_is_sector_allocated (struct vdrive_s * vdrive, unsigned int track, unsigned int sector)
check to see if a sector is allocated
return of 1 if yes, 0 if not, -1 if failed (1571 > 70 tracks)
< number of tracks on a 1571 floppy
Referenced by bam_print_tracks(), and vdrive_command_chpart().
vdrive_bam_isgeos()
int vdrive_bam_isgeos (struct vdrive_s * vdrive)
Referenced by vdrive_command_scratch(), and vdrive_command_validate().
vdrive_bam_read_bam()
int vdrive_bam_read_bam (struct vdrive_s * vdrive)
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by diskcontents_block_read(), name_cmd(), vdrive_attach_image(), vdrive_bam_clear_all(), vdrive_bam_free_block_count(), and vdrive_command_validate().
vdrive_bam_set_disk_id()
int vdrive_bam_set_disk_id (unsigned int unit, unsigned int drive, uint8_t * id)
set disk id
Referenced by file_system_bam_set_disk_id().
vdrive_bam_setup_bam()
void vdrive_bam_setup_bam (struct vdrive_s * vdrive)
< BAM track number (side 1 BAM)
< BAM sector number (side 1 BAM)
< Dual Disk Drive
< 1541 BAM track number
< 1541 BAM sector number
< Dual Disk Drive
< Dual Disk Drive
< block w/disk name
< block w/disk name
Referenced by vdrive_bam_create_empty_bam(), vdrive_command_chpart(), vdrive_command_initialize(), vdrive_command_renameheader(), vdrive_iec_switch(), vdrive_refresh(), and vdrive_switch().
vdrive_bam_write_bam()
int vdrive_bam_write_bam (struct vdrive_s * vdrive)
Update ALL bam data back to image.
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by iec_close_sequential(), name_cmd(), vdrive_attach_image(), vdrive_bam_set_disk_id(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_format_worker(), vdrive_command_initialize(), vdrive_command_mkdir(), vdrive_command_renameheader(), vdrive_command_validate(), vdrive_dir_remove_slot(), vdrive_flush(), vdrive_iec_switch(), vdrive_rel_grow(), vdrive_switch(), and write_geos_cmd().