vsid: raster/raster-resources.c File Reference
raster-resources.c File Reference
#include "vice.h"
#include <stdio.h>
#include "lib.h"
#include "machine.h"
#include "raster.h"
#include "raster-resources.h"
#include "resources.h"
#include "types.h"
#include "util.h"
#include "video.h"
Data Structures
struct raster_resource_chip_s
Macros
#define DEFAULT_VideoCache_VALUE 0
Typedefs
typedef struct raster_resource_chip_s raster_resource_chip_t
Functions
static int set_video_cache_enabled (int val, void *param)
int raster_resources_chip_init (const char *chipname, raster_t *raster, struct video_chip_cap_s *video_chip_cap)
void raster_resources_chip_shutdown (raster_t *raster)
Variables
static const char *const rname_chip [] = { "VideoCache", NULL }
static resource_int_t resources_chip []
Macro Definition Documentation
DEFAULT_VideoCache_VALUE
#define DEFAULT_VideoCache_VALUE 0
Typedef Documentation
raster_resource_chip_t
typedef struct raster_resource_chip_s raster_resource_chip_t
Function Documentation
raster_resources_chip_init()
int raster_resources_chip_init (const char * chipname, raster_t * raster, struct video_chip_cap_s * video_chip_cap)
Referenced by vicii_resources_init().
raster_resources_chip_shutdown()
void raster_resources_chip_shutdown (raster_t * raster)
Referenced by raster_shutdown().
set_video_cache_enabled()
static int set_video_cache_enabled (int val, void * param) static
Referenced by raster_resources_chip_init().
Variable Documentation
resources_chip
resource_int_t resources_chip[] static
Initial value:
=
{
    { NULL,  0 , RES_EVENT_NO, NULL,
      NULL, set_video_cache_enabled, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by raster_resources_chip_init().
rname_chip
const char* const rname_chip[] = { "VideoCache", NULL } static
Referenced by raster_resources_chip_init().