vsid: raster/raster-sprite-status.h File Reference
raster-sprite-status.h File Reference
#include "types.h"
Data Structures
struct raster_sprite_status_s
Typedefs
typedef void(* raster_sprite_status_draw_function_t) (uint8_t *line_ptr, uint8_t *gfx_msk_ptr)
typedef void(* raster_sprite_status_cache_function_t) (struct raster_cache_s *cache)
typedef void(* raster_sprite_status_draw_partial_function_t) (uint8_t *line_ptr, uint8_t *gfx_msk_ptr, int xs, int xe)
typedef struct raster_sprite_status_s raster_sprite_status_t
Functions
void raster_sprite_status_new (struct raster_s *raster, unsigned int num_sprites, int sprite_offset)
void raster_sprite_status_destroy (struct raster_s *raster)
void raster_sprite_status_reset (raster_sprite_status_t *status, int sprite_offset)
void raster_sprite_status_set_draw_function (raster_sprite_status_t *status, raster_sprite_status_draw_function_t function)
void raster_sprite_status_set_cache_function (raster_sprite_status_t *status, raster_sprite_status_cache_function_t function)
void raster_sprite_status_set_draw_partial_function (raster_sprite_status_t *status, raster_sprite_status_draw_partial_function_t function)
Typedef Documentation
raster_sprite_status_cache_function_t
typedef void(* raster_sprite_status_cache_function_t) (struct raster_cache_s *cache)
raster_sprite_status_draw_function_t
typedef void(* raster_sprite_status_draw_function_t) (uint8_t *line_ptr, uint8_t *gfx_msk_ptr)
raster_sprite_status_draw_partial_function_t
typedef void(* raster_sprite_status_draw_partial_function_t) (uint8_t *line_ptr, uint8_t *gfx_msk_ptr, int xs, int xe)
raster_sprite_status_t
typedef struct raster_sprite_status_s raster_sprite_status_t
Function Documentation
raster_sprite_status_destroy()
void raster_sprite_status_destroy (struct raster_s * raster)
Referenced by vicii_shutdown().
raster_sprite_status_new()
void raster_sprite_status_new (struct raster_s * raster, unsigned int num_sprites, int sprite_offset)
Referenced by init_raster().
raster_sprite_status_reset()
void raster_sprite_status_reset (raster_sprite_status_t * status, int sprite_offset)
Referenced by raster_sprite_status_init(), and vicii_reset_registers().
raster_sprite_status_set_cache_function()
void raster_sprite_status_set_cache_function (raster_sprite_status_t * status, raster_sprite_status_cache_function_t function)
Referenced by vicii_sprites_init().
raster_sprite_status_set_draw_function()
void raster_sprite_status_set_draw_function (raster_sprite_status_t * status, raster_sprite_status_draw_function_t function)
Referenced by vicii_sprites_init().
raster_sprite_status_set_draw_partial_function()
void raster_sprite_status_set_draw_partial_function (raster_sprite_status_t * status, raster_sprite_status_draw_partial_function_t function)
Referenced by vicii_sprites_init().