vsid: gfxoutputdrv/minipaintdrv.c File Reference
minipaintdrv.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "archdep.h"
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "mem.h"
#include "gfxoutput.h"
#include "nativedrv.h"
#include "palette.h"
#include "resources.h"
#include "screenshot.h"
#include "types.h"
#include "uiapi.h"
#include "util.h"
#include "vsync.h"
Macros
#define DBG(_x_)
#define VIC_NUM_COLORS_BG_AUX 16
#define MINIPAINT_SCREEN_PIXEL_WIDTH 160
#define MINIPAINT_SCREEN_PIXEL_HEIGHT 192
#define MINIPAINT_BLOCK_WIDTH 8
#define MINIPAINT_BLOCK_HEIGHT 16
#define MINIPAINT_SCREEN_CHARS_WIDTH (MINIPAINT_SCREEN_PIXEL_WIDTH / MINIPAINT_BLOCK_WIDTH)
#define MINIPAINT_SCREEN_CHARS_HEIGHT (MINIPAINT_SCREEN_PIXEL_HEIGHT / MINIPAINT_BLOCK_HEIGHT)
#define AUXCOLOR_OFFSET 15
define offsets in the minipaint file
#define BGCOLOR_OFFSET 16
#define BITMAP_OFFSET 17
#define VIDEORAM_OFFSET 3857
#define DISPLAYER_OFFSET 3977
#define MINIPAINT_SIZE 4097
#define UNASSIGNED_COLOR 16
Functions
static int set_oversize_handling (int val, void *param)
static int set_undersize_handling (int val, void *param)
static int set_ted_lum_handling (int val, void *param)
static int minipaintdrv_resources_init (void)
static int minipaintdrv_cmdline_options_init (void)
static void minipaint_find_hires_colors (native_data_t *source, uint8_t *bgcolor)
static void minipaint_find_shared_colors_pass (native_data_t *source, uint8_t *bgcolor, uint8_t *auxcolor, uint8_t *bordercolor, int pass, int auxbg)
static void minipaint_find_shared_colors (native_data_t *source, uint8_t *bgcolor, uint8_t *auxcolor, uint8_t *bordercolor)
static void minipaint_check_and_correct_cell (native_data_t *source, uint8_t bgcolor, uint8_t auxcolor, uint8_t bordercolor)
static int minipaint_render_and_save (native_data_t *source, int original_bordercolor)
static int minipaint_vicii_save (screenshot_t *screenshot, const char *filename)
static int minipaint_ted_save (screenshot_t *screenshot, const char *filename)
static int minipaint_vic_save (screenshot_t *screenshot, const char *filename)
static int minipaint_crtc_save (screenshot_t *screenshot, const char *filename)
static int minipaint_vdc_save (screenshot_t *screenshot, const char *filename)
static int minipaintdrv_save (screenshot_t *screenshot, const char *filename)
void gfxoutput_init_minipaint (int help)
Variables
static gfxoutputdrv_t minipaint_drv
static unsigned char headerdata [17]
static unsigned char displaycode [120]
static unsigned char hiresmap [(192/16)][(160/8)]
static int containshires
static int oversize_handling
static int undersize_handling
static int ted_lum_handling
static const resource_int_t resources_int []
static const resource_int_t resources_int_plus4 []
static const cmdline_option_t cmdline_options []
static const cmdline_option_t cmdline_options_plus4 []
Macro Definition Documentation
AUXCOLOR_OFFSET
#define AUXCOLOR_OFFSET 15
define offsets in the minipaint file
BGCOLOR_OFFSET
#define BGCOLOR_OFFSET 16
BITMAP_OFFSET
#define BITMAP_OFFSET 17
DBG
#define DBG (_x_)
DISPLAYER_OFFSET
#define DISPLAYER_OFFSET 3977
MINIPAINT_BLOCK_HEIGHT
#define MINIPAINT_BLOCK_HEIGHT 16
MINIPAINT_BLOCK_WIDTH
#define MINIPAINT_BLOCK_WIDTH 8
MINIPAINT_SCREEN_CHARS_HEIGHT
#define MINIPAINT_SCREEN_CHARS_HEIGHT (MINIPAINT_SCREEN_PIXEL_HEIGHT / MINIPAINT_BLOCK_HEIGHT)
MINIPAINT_SCREEN_CHARS_WIDTH
#define MINIPAINT_SCREEN_CHARS_WIDTH (MINIPAINT_SCREEN_PIXEL_WIDTH / MINIPAINT_BLOCK_WIDTH)
MINIPAINT_SCREEN_PIXEL_HEIGHT
#define MINIPAINT_SCREEN_PIXEL_HEIGHT 192
MINIPAINT_SCREEN_PIXEL_WIDTH
#define MINIPAINT_SCREEN_PIXEL_WIDTH 160
MINIPAINT_SIZE
#define MINIPAINT_SIZE 4097
UNASSIGNED_COLOR
#define UNASSIGNED_COLOR 16
VIC_NUM_COLORS_BG_AUX
#define VIC_NUM_COLORS_BG_AUX 16
VIDEORAM_OFFSET
#define VIDEORAM_OFFSET 3857
Function Documentation
gfxoutput_init_minipaint()
void gfxoutput_init_minipaint (int help)
Referenced by gfxoutput_early_init().
minipaint_check_and_correct_cell()
static void minipaint_check_and_correct_cell (native_data_t * source, uint8_t bgcolor, uint8_t auxcolor, uint8_t bordercolor) static
Referenced by minipaint_render_and_save().
minipaint_crtc_save()
static int minipaint_crtc_save (screenshot_t * screenshot, const char * filename) static
Referenced by minipaintdrv_save().
minipaint_find_hires_colors()
static void minipaint_find_hires_colors (native_data_t * source, uint8_t * bgcolor) static
Referenced by minipaint_find_shared_colors().
minipaint_find_shared_colors()
static void minipaint_find_shared_colors (native_data_t * source, uint8_t * bgcolor, uint8_t * auxcolor, uint8_t * bordercolor) static
Referenced by minipaint_render_and_save().
minipaint_find_shared_colors_pass()
static void minipaint_find_shared_colors_pass (native_data_t * source, uint8_t * bgcolor, uint8_t * auxcolor, uint8_t * bordercolor, int pass, int auxbg) static
Referenced by minipaint_find_shared_colors().
minipaint_render_and_save()
static int minipaint_render_and_save (native_data_t * source, int original_bordercolor) static
< write mode (binary)
Referenced by minipaint_crtc_save(), minipaint_ted_save(), minipaint_vdc_save(), minipaint_vic_save(), and minipaint_vicii_save().
minipaint_ted_save()
static int minipaint_ted_save (screenshot_t * screenshot, const char * filename) static
Referenced by minipaintdrv_save().
minipaint_vdc_save()
static int minipaint_vdc_save (screenshot_t * screenshot, const char * filename) static
Referenced by minipaintdrv_save().
minipaint_vic_save()
static int minipaint_vic_save (screenshot_t * screenshot, const char * filename) static
Referenced by minipaintdrv_save().
minipaint_vicii_save()
static int minipaint_vicii_save (screenshot_t * screenshot, const char * filename) static
Referenced by minipaintdrv_save().
minipaintdrv_cmdline_options_init()
static int minipaintdrv_cmdline_options_init (void) static
minipaintdrv_resources_init()
static int minipaintdrv_resources_init (void) static
minipaintdrv_save()
static int minipaintdrv_save (screenshot_t * screenshot, const char * filename) static
set_oversize_handling()
static int set_oversize_handling (int val, void * param) static
set_ted_lum_handling()
static int set_ted_lum_handling (int val, void * param) static
set_undersize_handling()
static int set_undersize_handling (int val, void * param) static
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-minipaintoversize", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "MiniPaintOversizeHandling", NULL,
      "<method>", "Select the way the oversized input should be handled,"
      " (0: scale down, 1: crop left top, 2: crop center top,  3: crop right top,"
      " 4: crop left center, 5: crop center, 6: crop right center, 7: crop left bottom,"
      " 8: crop center bottom, 9:  crop right bottom)" },
    { "-minipaintundersize", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "MiniPaintUndersizeHandling", NULL,
      "<method>", "Select the way the undersized input should be handled,"
      " (0: scale up, 1: borderize)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by minipaintdrv_cmdline_options_init().
cmdline_options_plus4
const cmdline_option_t cmdline_options_plus4[] static
Initial value:
=
{
    { "-minipainttedlum", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "MiniPaintTEDLumHandling", NULL,
      "<method>", "Select the way the TED luminosity should be handled,"
      " (0: ignore, 1: dither)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by minipaintdrv_cmdline_options_init().
containshires
int containshires static
Referenced by minipaint_find_hires_colors(), and minipaint_render_and_save().
displaycode
unsigned char displaycode[120] static
Initial value:
= {
    0x18, 0xA9, 0x10, 0xA8, 0x99, 0xF0, 0x0F, 0x69, 0x0C, 0x90, 0x02, 0xE9, 0xEF, 0xC8, 0xD0, 0xF4,
    0xA0, 0x05, 0x18, 0xB9, 0xE4, 0xED, 0x79, 0xFA, 0x21, 0x99, 0x00, 0x90, 0x88, 0x10, 0xF3, 0xAD,
    0x0E, 0x90, 0x29, 0x0F, 0x0D, 0x0E, 0x12, 0x8D, 0x0E, 0x90, 0xAD, 0x0F, 0x12, 0x8D, 0x0F, 0x90,
    0xA9, 0x10, 0x85, 0xFB, 0xA9, 0x12, 0x85, 0xFC, 0xA9, 0x00, 0x85, 0xFD, 0xA9, 0x11, 0x85, 0xFE,
    0xA2, 0x0F, 0xA0, 0x00, 0xB1, 0xFB, 0x91, 0xFD, 0xC8, 0xD0, 0xF9, 0xE6, 0xFC, 0xE6, 0xFE, 0xCA,
    0xD0, 0xF2, 0xA2, 0x00, 0xA0, 0x00, 0xBD, 0x10, 0x21, 0xE8, 0x99, 0x00, 0x94, 0xC8, 0x4A, 0x4A,
    0x4A, 0x4A, 0x99, 0x00, 0x94, 0xC8, 0xC0, 0xF0, 0xD0, 0xEC, 0x20, 0xE4, 0xFF, 0xF0, 0xFB, 0x4C,
    0x32, 0xFD, 0x02, 0xFE, 0xFE, 0xEB, 0x00, 0x0C
}
Referenced by minipaint_render_and_save().
headerdata
unsigned char headerdata[17] static
Initial value:
= {
    0xf1, 0x10, 0x0c, 0x12, 0xd8, 0x07, 0x9e, 0x20, 0x38, 0x35, 0x38, 0x34, 0x00, 0x00, 0x00, 0x60, 0x0d
}
Referenced by minipaint_render_and_save().
hiresmap
unsigned char hiresmap[(192/ 16)][(160/ 8)] static
Referenced by minipaint_check_and_correct_cell(), minipaint_find_hires_colors(), minipaint_find_shared_colors_pass(), and minipaint_render_and_save().
minipaint_drv
static gfxoutputdrv_t minipaint_drv static
Initial value:
=
{
    GFXOUTPUTDRV_TYPE_SCREENSHOT_NATIVE,
    "MINIPAINT",
    "MiniPaint screenshot",
    "prg",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    minipaintdrv_save,
    NULL,
    NULL,
    minipaintdrv_resources_init,
    minipaintdrv_cmdline_options_init
}
Referenced by gfxoutput_init_minipaint(), and minipaint_render_and_save().
oversize_handling
int oversize_handling static
Referenced by minipaint_crtc_save(), minipaint_ted_save(), minipaint_vdc_save(), minipaint_vic_save(), minipaint_vicii_save(), and set_oversize_handling().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "MiniPaintOversizeHandling", NATIVE_SS_OVERSIZE_SCALE, RES_EVENT_NO, NULL,
      &oversize_handling, set_oversize_handling, NULL },
    { "MiniPaintUndersizeHandling", NATIVE_SS_UNDERSIZE_BORDERIZE, RES_EVENT_NO, NULL,
      &undersize_handling, set_undersize_handling, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by minipaintdrv_resources_init().
resources_int_plus4
const resource_int_t resources_int_plus4[] static
Initial value:
= {
    { "MiniPaintTEDLumHandling", NATIVE_SS_TED_LUM_DITHER, RES_EVENT_NO, NULL,
      &ted_lum_handling, set_ted_lum_handling, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by minipaintdrv_resources_init().
ted_lum_handling
int ted_lum_handling static
Referenced by minipaint_ted_save(), and set_ted_lum_handling().
undersize_handling
int undersize_handling static
Referenced by minipaint_crtc_save(), minipaint_ted_save(), minipaint_vdc_save(), minipaint_vic_save(), minipaint_vicii_save(), and set_undersize_handling().