vsid: diskimage/realimage.h File Reference
realimage.h File Reference
#include "types.h"
Data Structures
struct realimage_s
Typedefs
typedef struct realimage_s realimage_t
Functions
void realimage_init (void)
int realimage_open (struct disk_image_s *image)
int realimage_close (struct disk_image_s *image)
int realimage_read_sector (const struct disk_image_s *image, uint8_t *buf, const struct disk_addr_s *dadr)
int realimage_write_sector (struct disk_image_s *image, const uint8_t *buf, const struct disk_addr_s *dadr)
void realimage_media_create (struct disk_image_s *image)
void realimage_media_destroy (struct disk_image_s *image)
Typedef Documentation
realimage_t
typedef struct realimage_s realimage_t
Function Documentation
realimage_close()
int realimage_close (struct disk_image_s * image)
Referenced by disk_image_close().
realimage_init()
void realimage_init (void)
Referenced by disk_image_init().
realimage_media_create()
void realimage_media_create (struct disk_image_s * image)
Referenced by disk_image_media_create().
realimage_media_destroy()
void realimage_media_destroy (struct disk_image_s * image)
Referenced by disk_image_media_destroy().
realimage_open()
int realimage_open (struct disk_image_s * image)
Referenced by disk_image_open().
realimage_read_sector()
int realimage_read_sector (const struct disk_image_s * image, uint8_t * buf, const struct disk_addr_s * dadr)
realimage_write_sector()
int realimage_write_sector (struct disk_image_s * image, const uint8_t * buf, const struct disk_addr_s * dadr)