vsid: arch/shared/hotkeys/parser.h File Reference
parser.h File Reference
Parsing functions for hotkeys - header.
#include <stdbool.h>
Functions
void vhk_parser_init (void)
Initialize parser for use.
void vhk_parser_shutdown (void)
Clean up resources used by the parser.
bool vhk_parser_parse (const char *path)
Parse hotkeys file.
Detailed Description
Parsing functions for hotkeys - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
vhk_parser_init()
void vhk_parser_init (void)
Initialize parser for use.
Set up and fill the symbol table. This function should only be called once, during general init, and not before each call to vkh_parser_parse().
Referenced by ui_hotkeys_init().
vhk_parser_parse()
bool vhk_parser_parse (const char * path)
Parse hotkeys file.
Parameters
[in] path path to hotkeys file
Returns
true on success
Todo:
check if EOF or error
Referenced by ui_hotkeys_load().
vhk_parser_shutdown()
void vhk_parser_shutdown (void)
Clean up resources used by the parser.
Free symbol table. This function should only be called once, during general shutdown, and not before each call to vkh_parser_parse().
Referenced by ui_hotkeys_shutdown().