vsid: arch/gtk3/uitapeattach.c File Reference
uitapeattach.c File Reference
GTK3 tape-attach dialog.
#include "vice.h"
#include <gtk/gtk.h>
#include "attach.h"
#include "autostart.h"
#include "log.h"
#include "tape.h"
#include "debug_gtk3.h"
#include "basedialogs.h"
#include "contentpreviewwidget.h"
#include "filechooserhelpers.h"
#include "imagecontents.h"
#include "lastdir.h"
#include "resources.h"
#include "tapecontents.h"
#include "tapeport.h"
#include "ui.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uimachinewindow.h"
#include "uitapeattach.h"
Functions
static void on_update_preview (GtkFileChooser *chooser, gpointer data)
Handler for the "update-preview" event.
static void on_hidden_toggled (GtkWidget *widget, gpointer user_data)
Handler for the 'toggled' event of the 'show hidden files' checkbox.
static void do_autostart (GtkWidget *widget, int port, int index, int autostart)
Trigger autostart.
static void do_attach (GtkWidget *widget, int port)
Attach image to datasette.
static void on_selection_changed (GtkFileChooser *chooser, gpointer data)
Handler for 'selection-changed' event of the preview widget.
static void on_destroy (GtkWidget *dialog, gpointer port)
Handler for the 'destroy' event of the dialog.
static void on_response (GtkWidget *widget, gint response_id, gpointer user_data)
Handler for 'response' event of the dialog.
static GtkWidget * create_extra_widget (GtkWidget *parent)
Create the 'extra' widget.
static GtkWidget * create_tape_attach_dialog (int port)
Create the tape attach dialog.
void ui_tape_attach_show_dialog (int port)
Show dialog to attach a tape image to a datasette.
void ui_tape_attach_shutdown (void)
Clean up the last directory string.
Variables
static ui_file_filter_t filters []
File type filters for the dialog.
static GtkWidget * preview_widget = NULL
Reference to the preview widget.
static gchar * last_dir = NULL
Last directory used.
static gchar * last_file = NULL
Last filename used.
static GtkWidget * autostart_button
Reference to the custom 'Autostart' button.
Detailed Description
GTK3 tape-attach dialog.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
Function Documentation
create_extra_widget()
static GtkWidget * create_extra_widget (GtkWidget * parent) static
Create the 'extra' widget.
Parameters
[in] parent parent widget
Returns
GtkGrid
!
Todo:
'grey-out'/disable units without a proper drive attached
Referenced by create_tape_attach_dialog().
create_tape_attach_dialog()
static GtkWidget * create_tape_attach_dialog (int port) static
Create the tape attach dialog.
Parameters
[in] port tape port (1 or 2 (xpet))
Returns
GtkFileChooserDialog
Referenced by ui_tape_attach_show_dialog().
do_attach()
static void do_attach (GtkWidget * widget, int port) static
Attach image to datasette.
Parameters
[in] widget dialog
[in] port datasette port (1 or 2 (xpet))
Referenced by on_response().
do_autostart()
static void do_autostart (GtkWidget * widget, int port, int index, int autostart) static
Trigger autostart.
Parameters
[in] widget dialog
[in] port tape port number (1 or 2)
[in] index file index in the directory preview
[in] autostart issue "RUN:" after loading
Referenced by on_response().
on_destroy()
static void on_destroy (GtkWidget * dialog, gpointer port) static
Handler for the 'destroy' event of the dialog.
Marks the appropriate UI action as finished.
Parameters
[in] dialog dialog (unused)
[in] port port number
Referenced by create_tape_attach_dialog().
on_hidden_toggled()
static void on_hidden_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the 'toggled' event of the 'show hidden files' checkbox.
Parameters
[in] widget checkbox triggering the event
[in] user_data data for the event (the dialog)
Referenced by create_extra_widget().
on_response()
static void on_response (GtkWidget * widget, gint response_id, gpointer user_data) static
Handler for 'response' event of the dialog.
This handler is called when the user clicks a button in the dialog.
Parameters
[in] widget the dialog
[in] response_id response ID
[in] user_data unit number
Referenced by create_tape_attach_dialog().
on_selection_changed()
static void on_selection_changed (GtkFileChooser * chooser, gpointer data) static
Handler for 'selection-changed' event of the preview widget.
Checks if a proper selection was made and activates the 'Autostart' button if so, disabled it otherwise
Parameters
[in] chooser Parent dialog
[in] data Extra event data (unused)
Referenced by create_tape_attach_dialog().
on_update_preview()
static void on_update_preview (GtkFileChooser * chooser, gpointer data) static
Handler for the "update-preview" event.
Parameters
[in] chooser file chooser dialog
[in] data extra event data (unused)
Referenced by create_tape_attach_dialog().
ui_tape_attach_show_dialog()
void ui_tape_attach_show_dialog (int port)
Show dialog to attach a tape image to a datasette.
Parameters
[in] port tape port (1 or 2)
Returns
TRUE (signal to Gtk the event was 'consumed')
Referenced by tape_attach_action().
ui_tape_attach_shutdown()
void ui_tape_attach_shutdown (void)
Clean up the last directory string.
Referenced by ui_exit().
Variable Documentation
autostart_button
GtkWidget* autostart_button static
Reference to the custom 'Autostart' button.
Referenced by create_tape_attach_dialog(), and on_selection_changed().
filters
ui_file_filter_t filters[] static
Initial value:
= {
    { "Tape images", file_chooser_pattern_tape },
    { "All files", file_chooser_pattern_all },
    { NULL, NULL }
}
File type filters for the dialog.
Referenced by create_tape_attach_dialog().
last_dir
gchar* last_dir = NULL static
Last directory used.
When a tape is attached, this is set to the directory of that file. Since it's heap-allocated by Gtk3, it must be freed with a call to ui_tape_attach_shutdown() on emulator shutdown.
Referenced by create_tape_attach_dialog(), do_attach(), do_autostart(), and ui_tape_attach_shutdown().
last_file
gchar* last_file = NULL static
Last filename used.
Referenced by create_tape_attach_dialog(), do_attach(), do_autostart(), and ui_tape_attach_shutdown().
preview_widget
GtkWidget* preview_widget = NULL static
Reference to the preview widget.
Referenced by create_tape_attach_dialog(), on_response(), and on_update_preview().