x128: arch/gtk3/widgets/settings_c128functionrom.c File Reference
settings_c128functionrom.c File Reference
Settings widget to control C128 Function ROMs.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "functionrom.h"
#include "settings_c128functionrom.h"
Functions
static GtkWidget * create_rom_type_widget (const char *prefix)
Create ROM type widget.
static GtkWidget * create_rom_file_widget (const char *prefix)
Create ROM file selection widget.
static GtkWidget * create_rom_widget (const char *prefix)
Create External/Internal ROM widget.
GtkWidget * settings_c128functionrom_widget_create (GtkWidget *parent)
Create widget to select Internal/External function ROMs.
Variables
static const vice_gtk3_radiogroup_entry_t rom_types []
List of possible ROM bla things.
Detailed Description
Settings widget to control C128 Function ROMs.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_rom_file_widget()
static GtkWidget * create_rom_file_widget (const char * prefix) static
Create ROM file selection widget.
Parameters
[in] prefix resource prefix
Returns
GtkGrid
Referenced by create_rom_widget().
create_rom_type_widget()
static GtkWidget * create_rom_type_widget (const char * prefix) static
Create ROM type widget.
Parameters
[in] prefix resource prefix
Returns
GtkGrid
Referenced by create_rom_widget().
create_rom_widget()
static GtkWidget * create_rom_widget (const char * prefix) static
Create External/Internal ROM widget.
Parameters
[in] prefix resource prefix
Returns
GtkGrid
Referenced by settings_c128functionrom_widget_create().
settings_c128functionrom_widget_create()
GtkWidget * settings_c128functionrom_widget_create (GtkWidget * parent)
Create widget to select Internal/External function ROMs.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
Variable Documentation
rom_types
const vice_gtk3_radiogroup_entry_t rom_types[] static
Initial value:
= {
    { "None",   INT_FUNCTION_NONE },
    { "ROM",    INT_FUNCTION_ROM },
    { "RAM",    INT_FUNCTION_RAM },
    { "RTC",    INT_FUNCTION_RTC },
    { NULL, - 1 },
}
List of possible ROM bla things.
Seems to be the same for ext ROMS
Referenced by create_rom_type_widget().