vsid: vdrive/vdrive-rel.c File Reference
vdrive-rel.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "cbmdos.h"
#include "diskimage.h"
#include "lib.h"
#include "log.h"
#include "vdrive-bam.h"
#include "vdrive-command.h"
#include "vdrive-dir.h"
#include "vdrive-iec.h"
#include "vdrive-rel.h"
#include "vdrive.h"
Macros
#define DIRTY_SECTOR 1
#define DIRTY_RECORD 2
#define WRITTEN_RECORD 4
Functions
static unsigned int vdrive_rel_record_max (vdrive_t *vdrive, unsigned int secondary)
static int vdrive_rel_position_internal (vdrive_t *vdrive, unsigned int secondary, unsigned int rec_lo, unsigned int rec_hi, unsigned int position)
void vdrive_rel_init (void)
static unsigned int vdrive_rel_has_super (vdrive_t *vdrive)
static unsigned int vdrive_rel_blocks_max (vdrive_t *vdrive)
static void vdrive_rel_commit (vdrive_t *vdrive, bufferinfo_t *p)
static int vdrive_rel_add_sector (vdrive_t *vdrive, unsigned int secondary, unsigned int *track, unsigned int *sector)
static void vdrive_rel_fillrecord (vdrive_t *vdrive, unsigned int secondary)
static void vdrive_rel_flush_sidesectors (vdrive_t *vdrive, bufferinfo_t *p)
static int vdrive_rel_grow (vdrive_t *vdrive, unsigned int secondary, unsigned int records)
static int vdrive_rel_open_existing (vdrive_t *vdrive, unsigned int secondary)
int vdrive_rel_setup_ss_buffers (vdrive_t *vdrive, unsigned int secondary)
void vdrive_rel_shutdown_ss_buffers (vdrive_t *vdrive, unsigned int secondary)
static int vdrive_rel_open_new (vdrive_t *vdrive, unsigned int secondary, cbmdos_cmd_parse_plus_t *cmd_parse)
int vdrive_rel_open (vdrive_t *vdrive, unsigned int secondary, cbmdos_cmd_parse_plus_t *cmd_parse)
static void vdrive_rel_track_sector (vdrive_t *vdrive, unsigned int secondary, unsigned int record, unsigned int *track, unsigned int *sector, unsigned int *rec_start)
int vdrive_rel_position (vdrive_t *vdrive, unsigned int secondary, unsigned int rec_lo, unsigned int rec_hi, unsigned int position)
int vdrive_rel_read (vdrive_t *vdrive, uint8_t *data, unsigned int secondary)
int vdrive_rel_write (vdrive_t *vdrive, uint8_t data, unsigned int secondary)
int vdrive_rel_close (vdrive_t *vdrive, unsigned int secondary)
void vdrive_rel_listen (vdrive_t *vdrive, unsigned int secondary)
void vdrive_rel_scratch (vdrive_t *vdrive, unsigned int t, unsigned int s)
un-allocate super/sidesector blocks
Variables
static log_t vdrive_rel_log = ((log_t)-1)
Macro Definition Documentation
DIRTY_RECORD
#define DIRTY_RECORD 2
DIRTY_SECTOR
#define DIRTY_SECTOR 1
WRITTEN_RECORD
#define WRITTEN_RECORD 4
Function Documentation
vdrive_rel_add_sector()
static int vdrive_rel_add_sector (vdrive_t * vdrive, unsigned int secondary, unsigned int * track, unsigned int * sector) static
< 1581
Todo:
FIXME: why is this commented out?
< for relative files
< for relative files
Referenced by vdrive_rel_grow().
vdrive_rel_blocks_max()
static unsigned int vdrive_rel_blocks_max (vdrive_t * vdrive) static
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_rel_add_sector().
vdrive_rel_close()
int vdrive_rel_close (vdrive_t * vdrive, unsigned int secondary)
Referenced by vdrive_iec_close().
vdrive_rel_commit()
static void vdrive_rel_commit (vdrive_t * vdrive, bufferinfo_t * p) static
Referenced by vdrive_rel_add_sector(), vdrive_rel_close(), vdrive_rel_position_internal(), vdrive_rel_read(), and vdrive_rel_write().
vdrive_rel_fillrecord()
static void vdrive_rel_fillrecord (vdrive_t * vdrive, unsigned int secondary) static
Referenced by vdrive_rel_close(), vdrive_rel_listen(), and vdrive_rel_position_internal().
vdrive_rel_flush_sidesectors()
static void vdrive_rel_flush_sidesectors (vdrive_t * vdrive, bufferinfo_t * p) static
Referenced by vdrive_rel_grow().
vdrive_rel_grow()
static int vdrive_rel_grow (vdrive_t * vdrive, unsigned int secondary, unsigned int records) static
< for relative files
Referenced by vdrive_rel_open(), and vdrive_rel_write().
vdrive_rel_has_super()
static unsigned int vdrive_rel_has_super (vdrive_t * vdrive) static
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_rel_add_sector(), vdrive_rel_scratch(), and vdrive_rel_setup_ss_buffers().
vdrive_rel_init()
void vdrive_rel_init (void)
Referenced by vdrive_init().
vdrive_rel_listen()
void vdrive_rel_listen (vdrive_t * vdrive, unsigned int secondary)
Referenced by vdrive_iec_listen().
vdrive_rel_open()
int vdrive_rel_open (vdrive_t * vdrive, unsigned int secondary, cbmdos_cmd_parse_plus_t * cmd_parse)
Referenced by vdrive_iec_open().
vdrive_rel_open_existing()
static int vdrive_rel_open_existing (vdrive_t * vdrive, unsigned int secondary) static
Referenced by vdrive_rel_open().
vdrive_rel_open_new()
static int vdrive_rel_open_new (vdrive_t * vdrive, unsigned int secondary, cbmdos_cmd_parse_plus_t * cmd_parse) static
< for relative files
Referenced by vdrive_rel_open().
vdrive_rel_position()
int vdrive_rel_position (vdrive_t * vdrive, unsigned int secondary, unsigned int rec_lo, unsigned int rec_hi, unsigned int position)
Referenced by vdrive_command_position().
vdrive_rel_position_internal()
static int vdrive_rel_position_internal (vdrive_t * vdrive, unsigned int secondary, unsigned int rec_lo, unsigned int rec_hi, unsigned int position) static
< for relative files
Referenced by vdrive_rel_add_sector(), vdrive_rel_open(), and vdrive_rel_position().
vdrive_rel_read()
int vdrive_rel_read (vdrive_t * vdrive, uint8_t * data, unsigned int secondary)
Referenced by vdrive_iec_read().
vdrive_rel_record_max()
static unsigned int vdrive_rel_record_max (vdrive_t * vdrive, unsigned int secondary) static
< for relative files
Referenced by vdrive_rel_open().
vdrive_rel_scratch()
void vdrive_rel_scratch (vdrive_t * vdrive, unsigned int t, unsigned int s)
un-allocate super/sidesector blocks
Referenced by vdrive_dir_remove_slot().
vdrive_rel_setup_ss_buffers()
int vdrive_rel_setup_ss_buffers (vdrive_t * vdrive, unsigned int secondary)
Referenced by vdrive_command_copy(), and vdrive_rel_open_new().
vdrive_rel_shutdown_ss_buffers()
void vdrive_rel_shutdown_ss_buffers (vdrive_t * vdrive, unsigned int secondary)
Referenced by vdrive_command_copy(), and vdrive_rel_close().
vdrive_rel_track_sector()
static void vdrive_rel_track_sector (vdrive_t * vdrive, unsigned int secondary, unsigned int record, unsigned int * track, unsigned int * sector, unsigned int * rec_start) static
< for relative files
Referenced by vdrive_rel_position_internal().
vdrive_rel_write()
int vdrive_rel_write (vdrive_t * vdrive, uint8_t data, unsigned int secondary)
Referenced by vdrive_iec_write(), and vdrive_rel_fillrecord().
Variable Documentation
vdrive_rel_log
log_t vdrive_rel_log = ((log_t)-1) static
Referenced by vdrive_rel_add_sector(), vdrive_rel_blocks_max(), vdrive_rel_has_super(), vdrive_rel_init(), vdrive_rel_open_existing(), vdrive_rel_position_internal(), vdrive_rel_read(), vdrive_rel_record_max(), and vdrive_rel_write().