vsid: gfxoutputdrv/gfxoutput.c File Reference
gfxoutput.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "bmpdrv.h"
#include "gfxoutput.h"
#include "gifdrv.h"
#include "lib.h"
#include "log.h"
#include "iffdrv.h"
#include "nativedrv.h"
#include "pcxdrv.h"
#include "ppmdrv.h"
#include "godotdrv.h"
#include "ffmpegexedrv.h"
#include "zmbvdrv.h"
Data Structures
struct gfxoutputdrv_list_s
Typedefs
typedef struct gfxoutputdrv_list_s gfxoutputdrv_list_t
Functions
int gfxoutput_num_drivers (void)
gfxoutputdrv_t * gfxoutput_drivers_iter_init (void)
gfxoutputdrv_t * gfxoutput_drivers_iter_next (void)
int gfxoutput_early_init (int help)
int gfxoutput_init (void)
void gfxoutput_shutdown (void)
int gfxoutput_register (gfxoutputdrv_t *drv)
Functions called by graphic output driver modules.
gfxoutputdrv_t * gfxoutput_get_driver (const char *drvname)
int gfxoutput_resources_init (void)
Functions called by external emulator code.
int gfxoutput_cmdline_options_init (void)
Variables
static gfxoutputdrv_list_t * gfxoutputdrv_list = NULL
static int gfxoutputdrv_list_count = 0
static log_t gfxoutput_log = ((log_t)-1)
static gfxoutputdrv_list_t * gfxoutputdrv_list_iter = NULL
Typedef Documentation
gfxoutputdrv_list_t
typedef struct gfxoutputdrv_list_s gfxoutputdrv_list_t
Function Documentation
gfxoutput_cmdline_options_init()
int gfxoutput_cmdline_options_init (void)
gfxoutput_drivers_iter_init()
gfxoutputdrv_t * gfxoutput_drivers_iter_init (void)
gfxoutput_drivers_iter_next()
gfxoutputdrv_t * gfxoutput_drivers_iter_next (void)
gfxoutput_early_init()
int gfxoutput_early_init (int help)
gfxoutput_get_driver()
gfxoutputdrv_t * gfxoutput_get_driver (const char * drvname)
gfxoutput_init()
int gfxoutput_init (void)
Referenced by machine_specific_init().
gfxoutput_num_drivers()
int gfxoutput_num_drivers (void)
gfxoutput_register()
int gfxoutput_register (gfxoutputdrv_t * drv)
Functions called by graphic output driver modules.
Referenced by gfxoutput_init_artstudio(), gfxoutput_init_bmp(), gfxoutput_init_ffmpegexe(), gfxoutput_init_godot(), gfxoutput_init_iff(), gfxoutput_init_koala(), gfxoutput_init_minipaint(), gfxoutput_init_pcx(), gfxoutput_init_ppm(), and gfxoutput_init_zmbv().
gfxoutput_resources_init()
int gfxoutput_resources_init (void)
Functions called by external emulator code.
gfxoutput_shutdown()
void gfxoutput_shutdown (void)
Variable Documentation
gfxoutput_log
log_t gfxoutput_log = ((log_t)-1) static
Referenced by gfxoutput_get_driver(), and gfxoutput_init().
gfxoutputdrv_list
gfxoutputdrv_list_t* gfxoutputdrv_list = NULL static
Referenced by gfxoutput_cmdline_options_init(), gfxoutput_drivers_iter_init(), gfxoutput_early_init(), gfxoutput_get_driver(), gfxoutput_register(), gfxoutput_resources_init(), and gfxoutput_shutdown().
gfxoutputdrv_list_count
int gfxoutputdrv_list_count = 0 static
Referenced by gfxoutput_num_drivers(), and gfxoutput_register().
gfxoutputdrv_list_iter
gfxoutputdrv_list_t* gfxoutputdrv_list_iter = NULL static
Referenced by gfxoutput_drivers_iter_init(), and gfxoutput_drivers_iter_next().