x128: arch/gtk3/widgets/driveramwidget.c File Reference
driveramwidget.c File Reference
Drive RAM expansions widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "drive-check.h"
#include "drive.h"
#include "machine.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "driveramwidget.h"
Data Structures
struct drive_ram_exp_s
Data on placement and memory location of drive RAM expansions.
Macros
#define RAM_EXP_COUNT 5
Number of possibile RAM expansions.
Typedefs
typedef struct drive_ram_exp_s drive_ram_exp_t
Data on placement and memory location of drive RAM expansions.
Functions
static GtkWidget * create_ram_check_button (int unit, unsigned int base)
Create drive RAM expansion check button.
GtkWidget * drive_ram_widget_create (int unit)
Create extra drive RAM expansions widget.
void drive_ram_widget_update (GtkWidget *widget, int model)
Update sensitivity of check buttons based on drive model.
Variables
static const drive_ram_exp_t expansions [5]
List of RAM expansions.
Detailed Description
Drive RAM expansions widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
RAM_EXP_COUNT
#define RAM_EXP_COUNT 5
Number of possibile RAM expansions.
Typedef Documentation
drive_ram_exp_t
typedef struct drive_ram_exp_s drive_ram_exp_t
Data on placement and memory location of drive RAM expansions.
Todo:
check drives against emus to turn this into a proper table: Drive[8-11]RAM2000 (1540, 1541 and 1541-II) Drive[8-11]RAM4000 (1540, 1541, 1541-II, 1570, 1571 and 1751CR) Drive[8-11]RAM6000 (1540, 1541, 1541-II, 1570, 1571 and 1751CR) Drive[8-11]RAM8000 (1540, 1541 and 1541-II) Drive[8-11]RAMA000 (1540, 1541 and 1541-II)
This probably not quite correct:
$VICERES Drive8RAM2000 -vsid $VICERES Drive9RAM2000 -vsid $VICERES Drive10RAM2000 -vsid $VICERES Drive11RAM2000 -vsid $VICERES Drive8RAM4000 -vsid $VICERES Drive9RAM4000 -vsid $VICERES Drive10RAM4000 -vsid $VICERES Drive11RAM4000 -vsid $VICERES Drive8RAM6000 -vsid $VICERES Drive9RAM6000 -vsid $VICERES Drive10RAM6000 -vsid $VICERES Drive11RAM6000 -vsid $VICERES Drive8RAM8000 -vsid $VICERES Drive9RAM8000 -vsid $VICERES Drive10RAM8000 -vsid $VICERES Drive11RAM8000 -vsid $VICERES Drive8RAMA000 -vsid $VICERES Drive9RAMA000 -vsid $VICERES Drive10RAMA000 -vsid $VICERES Drive11RAMA000 -vsid
Function Documentation
create_ram_check_button()
static GtkWidget * create_ram_check_button (int unit, unsigned int base) static
Create drive RAM expansion check button.
Parameters
[in] unit unit number (8-11)
[in] base RAM base address (word)
Returns
GtkCheckButton
Referenced by drive_ram_widget_create().
drive_ram_widget_create()
GtkWidget * drive_ram_widget_create (int unit)
Create extra drive RAM expansions widget.
Create a group of check buttons to enable/disable RAM expansions in a drive.
The check buttons that can be toggled is dependent on the drive type, see drive_ram_widget_update().
Parameters
[in] unit drive unit (8-11)
Returns
GtkGrid
Referenced by create_c64_layout(), create_plus4_layout(), and create_vic20_layout().
drive_ram_widget_update()
void drive_ram_widget_update (GtkWidget * widget, int model)
Update sensitivity of check buttons based on drive model.
Parameters
[in] widget drive RAM expansions widget
[in] model drive model ID
Referenced by drive_ram_widget_create(), and on_model_changed().
Variable Documentation
expansions
const drive_ram_exp_t expansions[5] static
Initial value:
= {
    { 0, 0, 0x2000, drive_check_expansion2000 },
    { 0, 1, 0x4000, drive_check_expansion4000 },
    { 0, 2, 0x6000, drive_check_expansion6000 },
    { 1, 0, 0x8000, drive_check_expansion8000 },
    { 1, 1, 0xa000, drive_check_expansionA000 }
}
List of RAM expansions.
Referenced by drive_ram_widget_create(), and drive_ram_widget_update().