vsid: iecbus/iecbus.c File Reference
iecbus.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "cia.h"
#include "drive.h"
#include "drivetypes.h"
#include "iecbus.h"
#include "iecdrive.h"
#include "printer.h"
#include "via.h"
#include "types.h"
#include "serial.h"
#include "drive/iec/cmdhd.h"
#include "debug.h"
Macros
#define DBG(x)
#define IECBUS_DEVICE_NONE 0
#define IECBUS_DEVICE_TRUEDRIVE 1
#define IECBUS_DEVICE_IECDEVICE 2
#define DEBUG_IEC_CPU_WRITE(_data)
#define DEBUG_IEC_CPU_READ(_data)
Functions
void iecbus_init (void)
void iecbus_cpu_undump (uint8_t data)
static uint8_t iecbus_cpu_read_conf0 (CLOCK clock)
No drive is enabled.
static void iecbus_cpu_write_conf0 (uint8_t data, CLOCK clock)
static uint8_t iecbus_cpu_read_conf1 (CLOCK clock)
Only the first disk unit (drive 8) is enabled.
static void iecbus_cpu_write_conf1 (uint8_t data, CLOCK clock)
NOTE: when adding drives, do the equivalent change in src/vic20/vic20iec.c.
static uint8_t iecbus_cpu_read_conf2 (CLOCK clock)
Only the second disk unit (drive 9) is enabled.
static void iecbus_cpu_write_conf2 (uint8_t data, CLOCK clock)
NOTE: when adding drives, do the equivalent change in src/vic20/vic20iec.c.
static uint8_t iecbus_cpu_read_conf3 (CLOCK clock)
static void iecbus_cpu_write_conf3 (uint8_t data, CLOCK clock)
NOTE: when adding drives, do the equivalent change in src/vic20/vic20iec.c.
static void calculate_callback_index (void)
void iecbus_status_set (unsigned int type, unsigned int unit, unsigned int enable)
uint8_t iecbus_device_read (void)
int iecbus_device_write (unsigned int unit, uint8_t data)
Variables
uint8_t(* iecbus_callback_read)(CLOCK) = NULL
void(* iecbus_callback_write)(uint8_t, CLOCK) = NULL
void(* iecbus_update_ports)(void) = NULL
iecbus_t iecbus
static unsigned int iecbus_device [16]
static uint8_t iec_old_atn = 0x10
static const unsigned int iecbus_device_index [16]
Macro Definition Documentation
DBG
#define DBG (x)
DEBUG_IEC_CPU_READ
#define DEBUG_IEC_CPU_READ (_data)
DEBUG_IEC_CPU_WRITE
#define DEBUG_IEC_CPU_WRITE (_data)
IECBUS_DEVICE_IECDEVICE
#define IECBUS_DEVICE_IECDEVICE 2
IECBUS_DEVICE_NONE
#define IECBUS_DEVICE_NONE 0
IECBUS_DEVICE_TRUEDRIVE
#define IECBUS_DEVICE_TRUEDRIVE 1
Function Documentation
calculate_callback_index()
static void calculate_callback_index (void) static
Referenced by iecbus_status_set().
iecbus_cpu_read_conf0()
static uint8_t iecbus_cpu_read_conf0 (CLOCK clock) static
No drive is enabled.
Referenced by calculate_callback_index().
iecbus_cpu_read_conf1()
static uint8_t iecbus_cpu_read_conf1 (CLOCK clock) static
Only the first disk unit (drive 8) is enabled.
Referenced by calculate_callback_index().
iecbus_cpu_read_conf2()
static uint8_t iecbus_cpu_read_conf2 (CLOCK clock) static
Only the second disk unit (drive 9) is enabled.
Referenced by calculate_callback_index().
iecbus_cpu_read_conf3()
static uint8_t iecbus_cpu_read_conf3 (CLOCK clock) static
Referenced by calculate_callback_index().
iecbus_cpu_undump()
void iecbus_cpu_undump (uint8_t data)
Referenced by undump_ciapa().
iecbus_cpu_write_conf0()
static void iecbus_cpu_write_conf0 (uint8_t data, CLOCK clock) static
Referenced by calculate_callback_index().
iecbus_cpu_write_conf1()
static void iecbus_cpu_write_conf1 (uint8_t data, CLOCK clock) static
NOTE: when adding drives, do the equivalent change in src/vic20/vic20iec.c.
< ASCII for HD
< ASCII for HD
Referenced by calculate_callback_index().
iecbus_cpu_write_conf2()
static void iecbus_cpu_write_conf2 (uint8_t data, CLOCK clock) static
NOTE: when adding drives, do the equivalent change in src/vic20/vic20iec.c.
< ASCII for HD
< ASCII for HD
Referenced by calculate_callback_index().
iecbus_cpu_write_conf3()
static void iecbus_cpu_write_conf3 (uint8_t data, CLOCK clock) static
NOTE: when adding drives, do the equivalent change in src/vic20/vic20iec.c.
< ASCII for HD
< ASCII for HD
Referenced by calculate_callback_index().
iecbus_device_read()
uint8_t iecbus_device_read (void)
iecbus_device_write()
int iecbus_device_write (unsigned int unit, uint8_t data)
iecbus_init()
void iecbus_init (void)
Referenced by machine_bus_init_machine().
iecbus_status_set()
void iecbus_status_set (unsigned int type, unsigned int unit, unsigned int enable)
Variable Documentation
iec_old_atn
uint8_t iec_old_atn = 0x10 static
Referenced by iecbus_cpu_undump(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), and iecbus_cpu_write_conf3().
iecbus
iecbus_t iecbus
Referenced by iecbus_cpu_read_conf0(), iecbus_cpu_read_conf1(), iecbus_cpu_read_conf2(), iecbus_cpu_read_conf3(), iecbus_cpu_undump(), iecbus_cpu_write_conf0(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), iecbus_cpu_write_conf3(), iecbus_device_read(), iecbus_device_write(), and iecbus_init().
iecbus_callback_read
uint8_t(* iecbus_callback_read) (CLOCK) (CLOCK) = NULL
Referenced by calculate_callback_index().
iecbus_callback_write
void(* iecbus_callback_write) (uint8_t, CLOCK) (uint8_t , CLOCK) = NULL
Referenced by calculate_callback_index().
iecbus_device
unsigned int iecbus_device[16] static
Referenced by calculate_callback_index(), iecbus_cpu_write_conf3(), and iecbus_status_set().
iecbus_device_index
const unsigned int iecbus_device_index[16] static
Initial value:
= {
     0 ,
     0 ,
     2 ,
     2 ,
     0 ,
     0 ,
     2 ,
     2 ,
     0 ,
     0 ,
     2 ,
     2 ,
     1 ,
     1 ,
     2 ,
     2
}
Referenced by iecbus_status_set().
iecbus_update_ports
void(* iecbus_update_ports) (void) (void) = NULL
Referenced by iecbus_device_write().