x128: piacore.c File Reference
piacore.c File Reference
#include "monitor.h"
#include "snapshot.h"
Macros
#define PIA_DUMP_VER_MAJOR 1
#define PIA_DUMP_VER_MINOR 0
Functions
void mypia_init (void)
void mypia_reset (void)
static void mypia_update_irq (CLOCK offset)
void mypia_signal (int line, int edge, CLOCK offset)
void mypia_store (uint16_t addr, uint8_t byte)
PIA.
uint8_t mypia_read (uint16_t addr)
uint8_t mypia_peek (uint16_t addr)
int mypia_dump (void)
int mypia_snapshot_write_module (snapshot_t *p)
FIXME!!! Error check.
int mypia_snapshot_read_module (snapshot_t *p)
Variables
static uint8_t pia_last_read = 0
static unsigned int pia_int_num
static char snap_module_name [] = MYPIA_NAME
Macro Definition Documentation
PIA_DUMP_VER_MAJOR
#define PIA_DUMP_VER_MAJOR 1
PIA_DUMP_VER_MINOR
#define PIA_DUMP_VER_MINOR 0
Function Documentation
mypia_dump()
int mypia_dump (void)
mypia_init()
void mypia_init (void)
mypia_peek()
uint8_t mypia_peek (uint16_t addr)
mypia_read()
uint8_t mypia_read (uint16_t addr)
Referenced by mypia_peek().
mypia_reset()
void mypia_reset (void)
mypia_signal()
void mypia_signal (int line, int edge, CLOCK offset)
mypia_snapshot_read_module()
int mypia_snapshot_read_module (snapshot_t * p)
mypia_snapshot_write_module()
int mypia_snapshot_write_module (snapshot_t * p)
FIXME!!! Error check.
mypia_store()
void mypia_store (uint16_t addr, uint8_t byte)
PIA.
Referenced by mypia_store().
mypia_update_irq()
static void mypia_update_irq (CLOCK offset) static
Referenced by mypia_read(), mypia_signal(), and mypia_store().
Variable Documentation
pia_int_num
unsigned int pia_int_num static
Referenced by mypia_init(), mypia_reset(), mypia_snapshot_read_module(), and mypia_update_irq().
pia_last_read
uint8_t pia_last_read = 0 static
Referenced by mypia_read(), and mypia_store().
snap_module_name
char snap_module_name[] = MYPIA_NAME static
Referenced by mypia_snapshot_read_module(), and mypia_snapshot_write_module().