x128: c128/c128rom.c File Reference
c128rom.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "c128.h"
#include "c128mem.h"
#include "c128memrom.h"
#include "c128rom.h"
#include "c64memrom.h"
#include "c64rom.h"
#include "machine.h"
#include "mem.h"
#include "log.h"
#include "resources.h"
#include "sysfile.h"
#include "types.h"
#include "util.h"
#include "z80mem.h"
Data Structures
struct ROMINFO
Macros
#define NUM_TRAP_DEVICES 9 /*! \todo FIXME: is there a better constant ? */
Functions
static char * checkrominfo (ROMINFO *info, uint16_t checksum, int id)
int c128rom_kernal_checksum (void)
int c128rom_load_kernal_int (const char *rom_name)
int c128rom_load_kernal_de (const char *rom_name)
int c128rom_load_kernal_fi (const char *rom_name)
int c128rom_load_kernal_fr (const char *rom_name)
int c128rom_load_kernal_it (const char *rom_name)
int c128rom_load_kernal_no (const char *rom_name)
int c128rom_load_kernal_se (const char *rom_name)
int c128rom_load_kernal_ch (const char *rom_name)
static void get_trapflags (void)
static void clear_trapflags (void)
static void restore_trapflags (void)
int c128rom_kernal_setup (void)
int c128rom_basic_checksum (void)
int c128rom_load_basiclo (const char *rom_name)
int c128rom_load_basichi (const char *rom_name)
int c128rom_chargen_setup (void)
int c128rom_load_chargen_int (const char *rom_name)
int c128rom_load_chargen_de (const char *rom_name)
int c128rom_load_chargen_fr (const char *rom_name)
int c128rom_load_chargen_se (const char *rom_name)
int c128rom_load_chargen_ch (const char *rom_name)
int c128rom_load_chargen_no (const char *rom_name)
int c128rom_load_chargen_fi (const char *rom_name)
int c128rom_load_chargen_it (const char *rom_name)
int c128rom_load_kernal64 (const char *rom_name, uint8_t *cartkernal)
int c128rom_load_basic64 (const char *rom_name)
int mem_load (void)
int c64rom_load_kernal (const char *rom_name, uint8_t *cartkernal)
Variables
static log_t c128rom_log = ((log_t)-1)
static int rom_loaded = 0
Flag: nonzero if the Kernal and BASIC ROMs have been loaded.
static uint8_t kernal_int [0x4000]
National Kernal ROM images.
static uint8_t kernal_ch [0x4000]
static uint8_t kernal_de [0x4000]
static uint8_t kernal_fi [0x4000]
static uint8_t kernal_fr [0x4000]
static uint8_t kernal_it [0x4000]
static uint8_t kernal_no [0x4000]
static uint8_t kernal_se [0x4000]
static uint8_t chargen_int [0x2000]
National Chargen ROM images.
static uint8_t chargen_ch [0x2000]
static uint8_t chargen_de [0x2000]
static uint8_t chargen_fi [0x2000]
static uint8_t chargen_fr [0x2000]
static uint8_t chargen_it [0x2000]
static uint8_t chargen_no [0x2000]
static uint8_t chargen_se [0x2000]
static ROMINFO kernalinfo []
static int trapfl [9]
static int trapdevices [9+1] = { 1, 4, 5, 6, 7, 8, 9, 10, 11, -1 }
static ROMINFO machineinfo []
static ROMINFO basicinfo []
static ROMINFO editorinfo []
int c64rom_cartkernal_active = 0
Macro Definition Documentation
NUM_TRAP_DEVICES
#define NUM_TRAP_DEVICES 9 /*! \todo FIXME: is there a better constant ? */
Function Documentation
c128rom_basic_checksum()
int c128rom_basic_checksum (void)
< BASICLO + BASICHI
< BASICLO + BASICHI
< BASICLO + BASICHI
< 0x0000 - 0x0fff in kernal image
Referenced by c128rom_kernal_setup(), and mem_read_rom_snapshot_module().
c128rom_chargen_setup()
int c128rom_chargen_setup (void)
Referenced by mem_load(), set_chargen_ch_rom_name(), set_chargen_de_rom_name(), set_chargen_fi_rom_name(), set_chargen_fr_rom_name(), set_chargen_int_rom_name(), set_chargen_it_rom_name(), set_chargen_no_rom_name(), set_chargen_se_rom_name(), and set_machine_type().
c128rom_kernal_checksum()
int c128rom_kernal_checksum (void)
< 0x2000 - 0x3fff in kernal image
Referenced by c128rom_kernal_setup(), and mem_read_rom_snapshot_module().
c128rom_kernal_setup()
int c128rom_kernal_setup (void)
< second 8k in 318081-01
< second 8k OF 325179-01
< second 8k OF 325182-01
< BASICLO + BASICHI
< 0x0000 - 0x0fff in kernal image
< 0x0000 - 0x0fff in kernal image
< 0x1000 - 0x1fff in kernal image
< 0x0000 - 0x0fff in kernal image
< 0x1000 - 0x1fff in kernal image
< 0x2000 - 0x3fff in kernal image
< 0x2000 - 0x3fff in kernal image
Referenced by mem_load(), set_kernal_ch_rom_name(), set_kernal_de_rom_name(), set_kernal_fi_rom_name(), set_kernal_fr_rom_name(), set_kernal_int_rom_name(), set_kernal_it_rom_name(), set_kernal_no_rom_name(), set_kernal_se_rom_name(), and set_machine_type().
c128rom_load_basic64()
int c128rom_load_basic64 (const char * rom_name)
Referenced by mem_load(), and set_basic64_rom_name().
c128rom_load_basichi()
int c128rom_load_basichi (const char * rom_name)
Referenced by mem_load(), and set_basichi_rom_name().
c128rom_load_basiclo()
int c128rom_load_basiclo (const char * rom_name)
Referenced by mem_load(), and set_basiclo_rom_name().
c128rom_load_chargen_ch()
int c128rom_load_chargen_ch (const char * rom_name)
Referenced by mem_load(), and set_chargen_ch_rom_name().
c128rom_load_chargen_de()
int c128rom_load_chargen_de (const char * rom_name)
Referenced by mem_load(), and set_chargen_de_rom_name().
c128rom_load_chargen_fi()
int c128rom_load_chargen_fi (const char * rom_name)
Referenced by mem_load(), and set_chargen_fi_rom_name().
c128rom_load_chargen_fr()
int c128rom_load_chargen_fr (const char * rom_name)
Referenced by mem_load(), and set_chargen_fr_rom_name().
c128rom_load_chargen_int()
int c128rom_load_chargen_int (const char * rom_name)
Referenced by mem_load(), and set_chargen_int_rom_name().
c128rom_load_chargen_it()
int c128rom_load_chargen_it (const char * rom_name)
Referenced by mem_load(), and set_chargen_it_rom_name().
c128rom_load_chargen_no()
int c128rom_load_chargen_no (const char * rom_name)
Referenced by mem_load(), and set_chargen_no_rom_name().
c128rom_load_chargen_se()
int c128rom_load_chargen_se (const char * rom_name)
Referenced by mem_load(), and set_chargen_se_rom_name().
c128rom_load_kernal64()
int c128rom_load_kernal64 (const char * rom_name, uint8_t * cartkernal)
Referenced by c64rom_load_kernal(), mem_load(), and set_kernal64_rom_name().
c128rom_load_kernal_ch()
int c128rom_load_kernal_ch (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_ch_rom_name().
c128rom_load_kernal_de()
int c128rom_load_kernal_de (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_de_rom_name().
c128rom_load_kernal_fi()
int c128rom_load_kernal_fi (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_fi_rom_name().
c128rom_load_kernal_fr()
int c128rom_load_kernal_fr (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_fr_rom_name().
c128rom_load_kernal_int()
int c128rom_load_kernal_int (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_int_rom_name().
c128rom_load_kernal_it()
int c128rom_load_kernal_it (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_it_rom_name().
c128rom_load_kernal_no()
int c128rom_load_kernal_no (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_no_rom_name().
c128rom_load_kernal_se()
int c128rom_load_kernal_se (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_se_rom_name().
c64rom_load_kernal()
int c64rom_load_kernal (const char * rom_name, uint8_t * cartkernal)
checkrominfo()
static char * checkrominfo (ROMINFO * info, uint16_t checksum, int id) static
Referenced by c128rom_basic_checksum(), c128rom_kernal_checksum(), and c128rom_kernal_setup().
clear_trapflags()
static void clear_trapflags (void) static
Referenced by c128rom_kernal_setup().
get_trapflags()
static void get_trapflags (void) static
Referenced by c128rom_kernal_setup().
mem_load()
int mem_load (void)
Referenced by machine_specific_init().
restore_trapflags()
static void restore_trapflags (void) static
Referenced by c128rom_kernal_setup().
Variable Documentation
basicinfo
ROMINFO basicinfo[] static
Initial value:
= {
    { "85",  38592 , 0 },
    { "86",  2496 , 0 },
    { NULL, 0, 0 }
}
Referenced by c128rom_basic_checksum().
c128rom_log
log_t c128rom_log = ((log_t)-1) static
Referenced by c128rom_basic_checksum(), c128rom_chargen_setup(), c128rom_kernal_checksum(), c128rom_kernal_setup(), c128rom_load_basic64(), c128rom_load_basichi(), c128rom_load_basiclo(), c128rom_load_chargen_ch(), c128rom_load_chargen_de(), c128rom_load_chargen_fi(), c128rom_load_chargen_fr(), c128rom_load_chargen_int(), c128rom_load_chargen_it(), c128rom_load_chargen_no(), c128rom_load_chargen_se(), c128rom_load_kernal64(), c128rom_load_kernal_ch(), c128rom_load_kernal_de(), c128rom_load_kernal_fi(), c128rom_load_kernal_fr(), c128rom_load_kernal_int(), c128rom_load_kernal_it(), c128rom_load_kernal_no(), c128rom_load_kernal_se(), and mem_load().
c64rom_cartkernal_active
int c64rom_cartkernal_active = 0
Referenced by c128rom_load_kernal64().
chargen_ch
uint8_t chargen_ch[0x2000] static
Referenced by c128rom_chargen_setup(), and c128rom_load_chargen_ch().
chargen_de
uint8_t chargen_de[0x2000] static
Referenced by c128rom_chargen_setup(), and c128rom_load_chargen_de().
chargen_fi
uint8_t chargen_fi[0x2000] static
Referenced by c128rom_chargen_setup(), and c128rom_load_chargen_fi().
chargen_fr
uint8_t chargen_fr[0x2000] static
Referenced by c128rom_chargen_setup(), and c128rom_load_chargen_fr().
chargen_int
uint8_t chargen_int[0x2000] static
National Chargen ROM images.
Referenced by c128rom_chargen_setup(), and c128rom_load_chargen_int().
chargen_it
uint8_t chargen_it[0x2000] static
Referenced by c128rom_chargen_setup(), and c128rom_load_chargen_it().
chargen_no
uint8_t chargen_no[0x2000] static
Referenced by c128rom_chargen_setup(), and c128rom_load_chargen_no().
chargen_se
uint8_t chargen_se[0x2000] static
Referenced by c128rom_chargen_setup(), and c128rom_load_chargen_se().
editorinfo
ROMINFO editorinfo[] static
Initial value:
= {
    { "international r1",  56682 , 1 },
    { "swedish r1",  9364 , 1 },
    { "german r1",  9619 , 1 },
    { NULL, 0, 0 }
}
Referenced by c128rom_basic_checksum().
kernal_ch
uint8_t kernal_ch[0x4000] static
Referenced by c128rom_kernal_setup(), and c128rom_load_kernal_ch().
kernal_de
uint8_t kernal_de[0x4000] static
Referenced by c128rom_kernal_setup(), and c128rom_load_kernal_de().
kernal_fi
uint8_t kernal_fi[0x4000] static
Referenced by c128rom_kernal_setup(), and c128rom_load_kernal_fi().
kernal_fr
uint8_t kernal_fr[0x4000] static
Referenced by c128rom_kernal_setup(), and c128rom_load_kernal_fr().
kernal_int
uint8_t kernal_int[0x4000] static
National Kernal ROM images.
Referenced by c128rom_kernal_setup(), and c128rom_load_kernal_int().
kernal_it
uint8_t kernal_it[0x4000] static
Referenced by c128rom_kernal_setup(), and c128rom_load_kernal_it().
kernal_no
uint8_t kernal_no[0x4000] static
Referenced by c128rom_kernal_setup(), and c128rom_load_kernal_no().
kernal_se
uint8_t kernal_se[0x4000] static
Referenced by c128rom_kernal_setup(), and c128rom_load_kernal_se().
kernalinfo
ROMINFO kernalinfo[] static
Initial value:
= {
    { "international r1",  22353 , 1 },
    { "swedish r1",  24139  , 1 },
    { "german r1",  22098  , 1 },
    { "swiss r1",  21376 , 1 },
    { NULL, 0, 0 }
}
Referenced by c128rom_kernal_checksum().
machineinfo
ROMINFO machineinfo[] static
Initial value:
= {
    { "international", C128_MACHINE_INT, 0 },
    { "finnish", C128_MACHINE_FINNISH, 0 },
    { "french", C128_MACHINE_FRENCH, 0 },
    { "german", C128_MACHINE_GERMAN, 0 },
    { "italian", C128_MACHINE_ITALIAN, 0 },
    { "norwegian", C128_MACHINE_NORWEGIAN, 0 },
    { "swedish", C128_MACHINE_SWEDISH, 0 },
    { "swiss", C128_MACHINE_SWISS, 0 },
    { NULL, 0, 0 }
}
Referenced by c128rom_kernal_setup().
rom_loaded
int rom_loaded = 0 static
Flag: nonzero if the Kernal and BASIC ROMs have been loaded.
Referenced by c128rom_chargen_setup(), c128rom_kernal_setup(), c128rom_load_basic64(), c128rom_load_basichi(), c128rom_load_basiclo(), c128rom_load_chargen_ch(), c128rom_load_chargen_de(), c128rom_load_chargen_fi(), c128rom_load_chargen_fr(), c128rom_load_chargen_int(), c128rom_load_chargen_it(), c128rom_load_chargen_no(), c128rom_load_chargen_se(), c128rom_load_kernal64(), c128rom_load_kernal_ch(), c128rom_load_kernal_de(), c128rom_load_kernal_fi(), c128rom_load_kernal_fr(), c128rom_load_kernal_int(), c128rom_load_kernal_it(), c128rom_load_kernal_no(), c128rom_load_kernal_se(), and mem_load().
trapdevices
int trapdevices[9+1] = { 1, 4, 5, 6, 7, 8, 9, 10, 11, -1 } static
Referenced by clear_trapflags(), get_trapflags(), and restore_trapflags().
trapfl
int trapfl[9] static
Referenced by get_trapflags(), and restore_trapflags().