x128: driver_select_s Struct Reference
driver_select_s Struct Reference
Printer driver data.
#include <driver-select.h>
Data Fields
char * drv_name
driver name
char * ui_name
driver name to display in UIs
int(* drv_open)(unsigned int prnr, unsigned int secondary)
void(* drv_close)(unsigned int prnr, unsigned int secondary)
int(* drv_putc)(unsigned int prnr, unsigned int secondary, uint8_t b)
int(* drv_getc)(unsigned int prnr, unsigned int secondary, uint8_t *b)
int(* drv_flush)(unsigned int prnr, unsigned int secondary)
int(* drv_formfeed)(unsigned int prnr)
int(* drv_select)(unsigned int prnr)
bool printer
device is a printer
bool plotter
device is a plotter
bool iec
device can be connected through IEC bus
bool ieee488
device can be connected through IEEE-488 bus
bool userport
device can be connected through userport
bool text
device supports text mode
bool graphics
device supports graphics mode
Detailed Description
Printer driver data.
Field Documentation
drv_close
void(* driver_select_s::drv_close) (unsigned int prnr, unsigned int secondary)
Referenced by driver_select_close().
drv_flush
int(* driver_select_s::drv_flush) (unsigned int prnr, unsigned int secondary)
Referenced by driver_select_flush().
drv_formfeed
int(* driver_select_s::drv_formfeed) (unsigned int prnr)
Referenced by driver_select_formfeed().
drv_getc
int(* driver_select_s::drv_getc) (unsigned int prnr, unsigned int secondary, uint8_t *b)
Referenced by driver_select_getc().
drv_name
char* driver_select_s::drv_name
driver name
Referenced by check_property(), driver_select_register(), driver_select_shutdown(), drv_1520_init_resources(), printer_driver_widget_create(), and set_printer_driver().
drv_open
int(* driver_select_s::drv_open) (unsigned int prnr, unsigned int secondary)
Referenced by driver_select_open().
drv_putc
int(* driver_select_s::drv_putc) (unsigned int prnr, unsigned int secondary, uint8_t b)
Referenced by driver_select_putc().
drv_select
int(* driver_select_s::drv_select) (unsigned int prnr)
Referenced by driver_select(), and set_printer_driver().
graphics
bool driver_select_s::graphics
device supports graphics mode
iec
bool driver_select_s::iec
device can be connected through IEC bus
ieee488
bool driver_select_s::ieee488
device can be connected through IEEE-488 bus
plotter
bool driver_select_s::plotter
device is a plotter
printer
bool driver_select_s::printer
device is a printer
text
bool driver_select_s::text
device supports text mode
ui_name
char* driver_select_s::ui_name
driver name to display in UIs
Referenced by driver_select_register(), driver_select_shutdown(), and printer_driver_widget_create().
userport
bool driver_select_s::userport
device can be connected through userport
The documentation for this struct was generated from the following file:
printerdrv/driver-select.h