vsid: arch/gtk3/uimachinewindow.c File Reference
uimachinewindow.c File Reference
Native GTK3 main emulator window code.
#include "vice.h"
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include <string.h>
#include "opengl_renderer.h"
#include "lightpen.h"
#include "log.h"
#include "machine.h"
#include "mousedrv.h"
#include "resources.h"
#include "ui.h"
#include "uimachinemenu.h"
#include "videoarch.h"
#include "vsyncapi.h"
#include "uimachinewindow.h"
Macros
#define VICE_EMPTY_POINTER canvas->blank_ptr
Functions
static gboolean event_box_stillness_tick_cb (GtkWidget *widget, GdkFrameClock *clock, gpointer user_data)
Frame-advance callback for the hide-mouse-when-idle logic.
void ui_set_ignore_mouse_hide (gboolean state)
Set mouse-hide-ignore state.
static void warp (int x, int y)
Mouse warp for each platform.
static void mouse_host_capture (int warp_x, int warp_y)
static void mouse_host_uncapture (void)
static void mouse_host_moved (float x, float y)
Calculate mouse movement delta and warp back to the origin.
static gboolean event_box_motion_cb (GtkWidget *widget, GdkEvent *event, gpointer user_data)
Callback for handling mouse motion events over the emulated screen.
static gboolean event_box_mouse_button_cb (GtkWidget *widget, GdkEvent *event, gpointer user_data)
Callback for handling mouse button events over the emulated screen.
static gboolean event_box_scroll_cb (GtkWidget *widget, GdkEvent *event, gpointer user_data)
Callback for handling mouse scroll wheel events over the emulated screen.
static GdkCursor * make_cursor (GtkWidget *widget, const char *name)
Create a reusable cursor that may be used as part of this widget.
static gboolean event_box_cross_cb (GtkWidget *widget, GdkEvent *event, gpointer user_data)
Callback for managing the hide-pointer-on-idle timings.
static void machine_window_create (video_canvas_t *canvas)
Create a new machine window.
void ui_machine_window_init (void)
Set up any resources needed to create new machine windows.
void ui_mouse_grab_pointer (void)
Grab the mouse pointer when mouse emulation is enabled.
void ui_mouse_ungrab_pointer (void)
Ungrab the mouse pointer when it was grabbed before.
Variables
static gboolean ignore_mouse_hide = FALSE
Ignore the hide-mouse-cursor event handlers.
static bool enable_capture = false
Whether or not to capture mouse movements and warp back.
static int host_delta_origin_x = 0.0
Host mouse deltas are calculated from this X value.
static int host_delta_origin_y = 0.0
Host mouse deltas are calculated from this Y value.
static int _mouse_still_frames = 0
Number of frames the mouse didn't move, used for pointer hiding.
Detailed Description
Native GTK3 main emulator window code.
Author
Marcus Sutton logge.nosp@m.doub.nosp@m.t@gma.nosp@m.il.c.nosp@m.om
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
Macro Definition Documentation
VICE_EMPTY_POINTER
#define VICE_EMPTY_POINTER canvas->blank_ptr
Todo:
FIXME: someone please add Doxygen docs for this, I can guess what it means but I'll probably get it wrong. –compyx
Function Documentation
event_box_cross_cb()
static gboolean event_box_cross_cb (GtkWidget * widget, GdkEvent * event, gpointer user_data) static
Callback for managing the hide-pointer-on-idle timings.
This callback fires whenever the machine window's canvas gains or loses focus over the mouse pointer. It manages the logic that hides the mouse pointer after inactivity. Entering the window will start the timer, and leaving it will stop it.
Leaving the window entirely will also be interpreted as removing the light pen from the screen.
Parameters
widget The widget that sent the event.
event The GdkEventCrossing event itself.
user_data The video canvas data structure associated with this machine window.
Returns
TRUE if no further event processing is necessary.
See also
event_box_stillness_tick_cb The timer managed by this function.
Referenced by machine_window_create().
event_box_motion_cb()
static gboolean event_box_motion_cb (GtkWidget * widget, GdkEvent * event, gpointer user_data) static
Callback for handling mouse motion events over the emulated screen.
Mouse motion events influence three different subsystems: the light-pen (if any), the emulated mouse (if any), and the UI-level routines that hide the mouse pointer if it comes to rest over the machine's screen.
Moving the mouse pointer resets the number of frames the mouse was held still.
Light pen position information is computed based on the new mouse position and what part of the machine window is actually in use based on current scaling and aspect ratio settings.
Mouse information is computed based on the difference between the current mouse location and the last recorded mouse location. If the mouse has been captured by the emulator, this also then warps the mouse pointer back to the middle of the emulated screen. (These warps will trigger an additional call to this function, but an additional flag will prevent them from being processed as true input.)
Information relevant to these processes is cached in the video_canvas_s structure for use as needed.
Parameters
widget The widget that sent the event.
event The GdkEventMotion event itself.
user_data The video canvas data structure associated with this machine window.
Returns
TRUE if no further event processing is necessary.
Todo:
Information involving mouse-warping is not cached with the canvas yet, and should be for cleaner C128 support.
Todo:
Pointer warping does not work on Wayland. GTK3 and its GDK substrate simply do not provide an implementation for gdk_device_warp(), and Wayland's window model doesn't really support pointer warping the way GDK envisions. Wayland's window model envisions using pointer constraints to confine the mouse pointer within a target window, and then using relative mouse motion events to capture additional attempts at motion outside of it. SDL2 implements this and it may provide a useful starting point for this alternative implementation.
See also
event_box_mouse_button_cb Further light pen and mouse button handling.
event_box_scroll_cb Further mouse button handling.
event_box_stillness_tick_cb More of the hide-idle-mouse-pointer logic.
event_box_cross_cb More of the hide-idle-mouse-pointer logic.
Referenced by machine_window_create().
event_box_mouse_button_cb()
static gboolean event_box_mouse_button_cb (GtkWidget * widget, GdkEvent * event, gpointer user_data) static
Callback for handling mouse button events over the emulated screen.
This forwards any button press or release events on to the light pen and mouse subsystems.
Parameters
widget The widget that sent the event.
event The GdkEventButton event itself.
user_data The video canvas data structure associated with this machine window.
Returns
TRUE if no further event processing is necessary.
See also
event_box_mouse_motion_cb Further handling of light pen and mouse events.
event_box_scroll_cb Further handling of mouse button events.
Referenced by machine_window_create().
event_box_scroll_cb()
static gboolean event_box_scroll_cb (GtkWidget * widget, GdkEvent * event, gpointer user_data) static
Callback for handling mouse scroll wheel events over the emulated screen.
GTK generates these by translating button presses on buttons 4 and 5 into scroll events; we convert them back and forward them on to the mouse subsystem.
"Smooth scroll" events are also processed, interpreted as "up scroll" or "down scroll" based on the vertical component of the smooth-scroll event.
Parameters
widget The widget that sent the event.
event The GdkEventScroll event itself.
user_data The video canvas data structure associated with this machine window.
Returns
TRUE if no further event processing is necessary.
See also
event_box_scroll_cb Further handling of mouse button events.
Referenced by machine_window_create().
event_box_stillness_tick_cb()
static gboolean event_box_stillness_tick_cb (GtkWidget * widget, GdkFrameClock * clock, gpointer user_data) static
Frame-advance callback for the hide-mouse-when-idle logic.
This function is called as the "tick callback" whenever the mouse is hovering over the machine's screen. Its job is primarily to manage the mouse cursor:
If the light pen is active, the cursor is always visible and is shaped like a crosshair.
If the mouse is grabbed, the cursor is never visible.
Otherwise, the cursor is visible as a normal mouse pointer as long as it's been 60 or fewer ticks since the last time the mouse moved.
Parameters
widget The widget that sent the event.
clock The GdkFrameClock that's managing our ticks.
user_data The video canvas data structure associated with this machine window.
Returns
TRUE if no further event processing is necessary.
See also
event_box_cross_cb Manages the lifecycle of this tick callback.
event_box_motion_cb Manages the "ticks since the last time the mouse moved" counter.
Referenced by event_box_cross_cb(), and event_box_motion_cb().
machine_window_create()
static void machine_window_create (video_canvas_t * canvas) static
Create a new machine window.
A machine window is a GtkGrid that has a menu bar on top, a status bar on the bottom, and a renderer-backend specific drawing area in the middle. The canvas argument has its relevant fields populated by this process.
Parameters
canvas The video canvas to populate.
Todo:
At the moment, the renderer backend is selected at compile time and cannot be changed. It would be nice to be able to fall back to simpler backends if more specialized ones fail. This is difficult at present because we cannot know if OpenGL is available until long after the window is created and realized.
Referenced by ui_machine_window_init().
make_cursor()
static GdkCursor * make_cursor (GtkWidget * widget, const char * name) static
Create a reusable cursor that may be used as part of this widget.
GDK cursors are tied to specific displays, so they need to be created for each machine window individually.
Parameters
widget The widget that will be using this cursor.
name The name of the cursor to create.
Returns
A new, non-floating, GdkCursor reference, or NULL on failure.
Note
Users coming to this code from the more X11-centric GTK2 will notice that the array of guaranteed-available cursors is much smaller. Please continue to only use the cursors listed in the documentation for gdk_cursor_new_from_name() here.
Referenced by event_box_stillness_tick_cb().
mouse_host_capture()
static void mouse_host_capture (int warp_x, int warp_y) static
Referenced by ui_mouse_grab_pointer().
mouse_host_moved()
static void mouse_host_moved (float x, float y) static
Calculate mouse movement delta and warp back to the origin.
Referenced by event_box_motion_cb().
mouse_host_uncapture()
static void mouse_host_uncapture (void) static
Referenced by ui_mouse_ungrab_pointer().
ui_machine_window_init()
void ui_machine_window_init (void)
Set up any resources needed to create new machine windows.
ui_mouse_grab_pointer()
void ui_mouse_grab_pointer (void)
Grab the mouse pointer when mouse emulation is enabled.
Referenced by event_box_cross_cb(), mousedrv_mouse_changed(), and on_focus_in_event().
ui_mouse_ungrab_pointer()
void ui_mouse_ungrab_pointer (void)
Ungrab the mouse pointer when it was grabbed before.
Referenced by mousedrv_mouse_changed(), and on_focus_out_event().
ui_set_ignore_mouse_hide()
void ui_set_ignore_mouse_hide (gboolean state)
Set mouse-hide-ignore state.
Parameters
[in] state enable/disable ignoring the mouse pointer hiding
Referenced by on_focus_in_event(), and on_focus_out_event().
warp()
static void warp (int x, int y) static
Mouse warp for each platform.
Referenced by create_warp_checkbox(), mouse_host_capture(), mouse_host_moved(), settings_autostart_widget_create(), and warp_callback().
Variable Documentation
_mouse_still_frames
int _mouse_still_frames = 0 static
Number of frames the mouse didn't move, used for pointer hiding.
Referenced by event_box_cross_cb(), event_box_motion_cb(), event_box_stillness_tick_cb(), and ui_mouse_ungrab_pointer().
enable_capture
bool enable_capture = false static
Whether or not to capture mouse movements and warp back.
Referenced by event_box_motion_cb(), mouse_host_capture(), mouse_host_moved(), and mouse_host_uncapture().
host_delta_origin_x
int host_delta_origin_x = 0.0 static
Host mouse deltas are calculated from this X value.
After the delta is calculated, the mouse is warped back to this location.
Referenced by mouse_host_capture(), and mouse_host_moved().
host_delta_origin_y
int host_delta_origin_y = 0.0 static
Host mouse deltas are calculated from this Y value.
After the delta is calculated, the mouse is warped back to this location.
Referenced by mouse_host_capture(), and mouse_host_moved().
ignore_mouse_hide
gboolean ignore_mouse_hide = FALSE static
Ignore the hide-mouse-cursor event handlers.
Used during dialogs
Referenced by event_box_stillness_tick_cb(), and ui_set_ignore_mouse_hide().