x128: c128/c128fastiec.h File Reference
c128fastiec.h File Reference
#include "types.h"
Functions
void c128fastiec_init (void)
void c128fastiec_fast_cpu_write (uint8_t data)
void c128fastiec_fast_cpu_direction (int direction)
void c64fastiec_fast_cpu_write (uint8_t data)
Variables
int burst_mod
Function Documentation
c128fastiec_fast_cpu_direction()
void c128fastiec_fast_cpu_direction (int direction)
Referenced by mmu_store().
c128fastiec_fast_cpu_write()
void c128fastiec_fast_cpu_write (uint8_t data)
< ASCII for HD
Referenced by store_sdr().
c128fastiec_init()
void c128fastiec_init (void)
Referenced by machine_specific_init().
c64fastiec_fast_cpu_write()
void c64fastiec_fast_cpu_write (uint8_t data)
Variable Documentation
burst_mod
int burst_mod extern