vsid: c64/c64keyboard.c File Reference
c64keyboard.c File Reference
#include "vice.h"
#include "c64cia.h"
#include "c64keyboard.h"
#include "interrupt.h"
#include "joystick.h"
#include "keyboard.h"
#include "machine.h"
#include "maincpu.h"
#include "vicii.h"
Functions
static void c64keyboard_machine_func (int *karr)
static void c64joystick_machine_func (void)
void c64keyboard_restore_key (int v)
void c64keyboard_init (void)
void c64keyboard_enable (int val)
Variables
int c64keyboard_active = 1
static unsigned int c64keyboard_int_num
Function Documentation
c64joystick_machine_func()
static void c64joystick_machine_func (void) static
Referenced by c64keyboard_init().
c64keyboard_enable()
void c64keyboard_enable (int val)
Referenced by c64model_set().
c64keyboard_init()
void c64keyboard_init (void)
Referenced by machine_specific_init().
c64keyboard_machine_func()
static void c64keyboard_machine_func (int * karr) static
Referenced by c64keyboard_init().
c64keyboard_restore_key()
void c64keyboard_restore_key (int v)
Referenced by machine_set_restore_key().
Variable Documentation
c64keyboard_active
int c64keyboard_active = 1
Referenced by c64keyboard_enable(), cia1_internal_lightpen_check(), ciapb_forcelow(), read_ciapa(), and read_ciapb().
c64keyboard_int_num
unsigned int c64keyboard_int_num static
Referenced by c64keyboard_init(), and c64keyboard_restore_key().