vsid: arch/gtk3/widgets/sidenginemodelwidget.c File Reference
sidenginemodelwidget.c File Reference
Widget to select SID engine and model.
#include "vice.h"
#include <gtk/gtk.h>
#include "resources.h"
#include "sid.h"
#include "vice_gtk3.h"
#include "sidenginemodelwidget.h"
Functions
static void on_radio_toggled (GtkWidget *radio, gpointer data)
Handler for the 'toggled' event of the SID engine/model radio buttons.
GtkWidget * sid_engine_model_widget_create (void)
Create SID engine/model selection widget.
void sid_engine_model_widget_set_callback (void(*callback)(int, int))
Set callback to be triggered on SID model or engine changes.
Variables
static void(* extra_callback)(int, int) = NULL
Optional extra callback for the SID settings glue logic.
Detailed Description
Widget to select SID engine and model.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_radio_toggled()
static void on_radio_toggled (GtkWidget * radio, gpointer data) static
Handler for the 'toggled' event of the SID engine/model radio buttons.
Parameters
[in] radio radio button triggering the event
[in] data new value for the SID engine/model
Referenced by sid_engine_model_widget_create().
sid_engine_model_widget_create()
GtkWidget * sid_engine_model_widget_create (void)
Create SID engine/model selection widget.
Returns
GtkGrid
Referenced by sid_sound_widget_create().
sid_engine_model_widget_set_callback()
void sid_engine_model_widget_set_callback (void(*)(int, int) callback)
Set callback to be triggered on SID model or engine changes.
The callback function will receive (engine, model).
Parameters
[in] callback function to call on model/engine change
Referenced by sid_sound_widget_create().
Variable Documentation
extra_callback
void(* extra_callback) (int, int) (int , int) = NULL static
Optional extra callback for the SID settings glue logic.
Referenced by on_radio_toggled(), and sid_engine_model_widget_set_callback().