vsid: c64/c64cia.h File Reference
c64cia.h File Reference
#include "types.h"
Functions
void cia1_setup_context (struct machine_context_s *machine_context)
void cia2_setup_context (struct machine_context_s *machine_context)
void cia1_init (struct cia_context_s *cia_context)
void cia1_store (uint16_t addr, uint8_t value)
uint8_t cia1_read (uint16_t addr)
uint8_t cia1_peek (uint16_t addr)
void cia1_set_extended_keyboard_rows_mask (uint8_t value)
void cia2_init (struct cia_context_s *cia_context)
void cia2_store (uint16_t addr, uint8_t value)
uint8_t cia2_read (uint16_t addr)
uint8_t cia2_peek (uint16_t addr)
void cia2_set_flagx (void)
Temporary!
void cia2_set_sdrx (uint8_t received_byte)
void cia1_check_lightpen (void)
void cia1_update_model (void)
void cia2_update_model (void)
void cia1_set_timing (struct cia_context_s *cia_context, int tickspersec, int powerfreq)
void cia2_set_timing (struct cia_context_s *cia_context, int tickspersec, int powerfreq)
Function Documentation
cia1_check_lightpen()
void cia1_check_lightpen (void)
Referenced by c64joystick_machine_func(), and c64keyboard_machine_func().
cia1_init()
void cia1_init (struct cia_context_s * cia_context)
Referenced by machine_specific_init().
cia1_peek()
uint8_t cia1_peek (uint16_t addr)
Referenced by peek_bank_io().
cia1_read()
uint8_t cia1_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
cia1_set_extended_keyboard_rows_mask()
void cia1_set_extended_keyboard_rows_mask (uint8_t value)
Referenced by d02f_store().
cia1_set_timing()
void cia1_set_timing (struct cia_context_s * cia_context, int tickspersec, int powerfreq)
Referenced by cia1_setup_context(), and machine_change_timing().
cia1_setup_context()
void cia1_setup_context (struct machine_context_s * machine_context)
Referenced by machine_setup_context().
cia1_store()
void cia1_store (uint16_t addr, uint8_t value)
< Control register A
Referenced by c64meminit(), and store_bank_io().
cia1_update_model()
void cia1_update_model (void)
Referenced by set_cia1_model().
cia2_init()
void cia2_init (struct cia_context_s * cia_context)
Referenced by machine_specific_init().
cia2_peek()
uint8_t cia2_peek (uint16_t addr)
Referenced by peek_bank_io().
cia2_read()
uint8_t cia2_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
cia2_set_flagx()
void cia2_set_flagx (void)
Temporary!
Referenced by c64_rsuser_init().
cia2_set_sdrx()
void cia2_set_sdrx (uint8_t received_byte)
Referenced by c64_rsuser_init().
cia2_set_timing()
void cia2_set_timing (struct cia_context_s * cia_context, int tickspersec, int powerfreq)
Referenced by cia2_setup_context(), and machine_change_timing().
cia2_setup_context()
void cia2_setup_context (struct machine_context_s * machine_context)
Referenced by machine_setup_context().
cia2_store()
void cia2_store (uint16_t addr, uint8_t value)
< Control register A
< Data direction register for port A
< Data direction register for port A
< Data direction register for port A
< Data direction register for port A
Referenced by c64meminit(), and store_bank_io().
cia2_update_model()
void cia2_update_model (void)
Referenced by set_cia2_model().