vsid: cia.h File Reference
cia.h File Reference
Definitions for MOS6526 (CIA) chip emulation.
#include "types.h"
Data Structures
struct cia_context_s
Macros
#define CIA_MODEL_6526 0
MOS 6526 models.
#define CIA_MODEL_6526A 1
"new"
#define CIA_PRA 0
MOS 6526 registers.
#define CIA_PRB 1
Port B.
#define CIA_DDRA 2
Data direction register for port A.
#define CIA_DDRB 3
Data direction register for port B.
#define CIA_TAL 4
Timer A low.
#define CIA_TAH 5
Timer A high.
#define CIA_TBL 6
Timer B low.
#define CIA_TBH 7
Timer B high.
#define CIA_TOD_TEN 8
Time Of Day clock 1/10 s.
#define CIA_TOD_SEC 9
Time Of Day clock sec.
#define CIA_TOD_MIN 10
Time Of Day clock min.
#define CIA_TOD_HR 11
Time Of Day clock hour.
#define CIA_SDR 12
Serial port shift register.
#define CIA_ICR 13
Interrupt control register.
#define CIA_CRA 14
Control register A.
#define CIA_CRB 15
Control register B.
#define CIA_CR_START 0x01
Common control register bits.
#define CIA_CR_PBON 0x02
#define CIA_CR_OUTMODE 0x04
#define CIA_CR_OUTMODE_TOGGLE 0x04
#define CIA_CR_OUTMODE_PULSE 0x00
#define CIA_CR_RUNMODE 0x08
#define CIA_CR_RUNMODE_ONE_SHOT 0x08
#define CIA_CR_RUNMODE_CONTINUOUS 0x00
#define CIA_CR_LOAD 0x10
#define CIA_CR_FORCE_LOAD 0x10
#define CIA_CRA_INMODE 0x20
CR A control register bits.
#define CIA_CRA_INMODE_CNT 0x20
#define CIA_CRA_INMODE_PHI2 0x00
#define CIA_CRA_SPMODE 0x40
#define CIA_CRA_SPMODE_OUT 0x40
#define CIA_CRA_SPMODE_IN 0x00
#define CIA_CRA_TODIN 0x80
#define CIA_CRA_TODIN_50HZ 0x80
#define CIA_CRA_TODIN_60HZ 0x00
#define CIA_CRB_INMODE 0x60
CR B control register bits.
#define CIA_CRB_INMODE_PHI2 0x00
#define CIA_CRB_INMODE_CNT 0x20
#define CIA_CRB_INMODE_TA 0x40
#define CIA_CRB_INMODE_TA_CNT 0x60
#define CIA_CRB_ALARM 0x80
#define CIA_CRB_ALARM_ALARM 0x80
#define CIA_CRB_ALARM_TOD 0x00
#define CIA_IM_SET 0x80
Interrupt Masks.
#define CIA_IM_TA 1
Timer A underflow.
#define CIA_IM_TB 2
Timer B underflow.
#define CIA_IM_TOD 4
TOD Clock Alarm.
#define CIA_IM_SDR 8
Shift Register completion.
#define CIA_IM_FLG 16
Handshake.
#define CIA_IM_TBB 0x100
Timer B bug flag.
Typedefs
typedef struct cia_context_s cia_context_t
Functions
void ciacore_setup_context (struct cia_context_s *cia_context)
void ciacore_init (struct cia_context_s *cia_context, struct alarm_context_s *alarm_context, struct interrupt_cpu_status_s *int_status)
void ciacore_shutdown (cia_context_t *cia_context)
void ciacore_reset (struct cia_context_s *cia_context)
void ciacore_disable (struct cia_context_s *cia_context)
void ciacore_store (struct cia_context_s *cia_context, uint16_t addr, uint8_t data)
uint8_t ciacore_read (struct cia_context_s *cia_context, uint16_t addr)
uint8_t ciacore_peek (struct cia_context_s *cia_context, uint16_t addr)
void ciacore_set_flag (struct cia_context_s *cia_context)
void ciacore_set_sdr (struct cia_context_s *cia_context, uint8_t data)
void ciacore_set_cnt (struct cia_context_s *cia_context, bool data)
void ciacore_set_sp (struct cia_context_s *cia_context, bool data)
int ciacore_snapshot_write_module (struct cia_context_s *cia_context, struct snapshot_s *s)
FIXME!!! Error check.
int ciacore_snapshot_read_module (struct cia_context_s *cia_context, struct snapshot_s *s)
int ciacore_dump (cia_context_t *cia_context)
Detailed Description
Definitions for MOS6526 (CIA) chip emulation.
Author
Jouko Valta jopi@.nosp@m.stek.nosp@m.t.oul.nosp@m.u.fi
Andre Fachat facha.nosp@m.t@ph.nosp@m.ysik..nosp@m.tu-c.nosp@m.hemni.nosp@m.tz.d.nosp@m.e
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Macro Definition Documentation
CIA_CR_FORCE_LOAD
#define CIA_CR_FORCE_LOAD 0x10
CIA_CR_LOAD
#define CIA_CR_LOAD 0x10
CIA_CR_OUTMODE
#define CIA_CR_OUTMODE 0x04
CIA_CR_OUTMODE_PULSE
#define CIA_CR_OUTMODE_PULSE 0x00
CIA_CR_OUTMODE_TOGGLE
#define CIA_CR_OUTMODE_TOGGLE 0x04
CIA_CR_PBON
#define CIA_CR_PBON 0x02
CIA_CR_RUNMODE
#define CIA_CR_RUNMODE 0x08
CIA_CR_RUNMODE_CONTINUOUS
#define CIA_CR_RUNMODE_CONTINUOUS 0x00
CIA_CR_RUNMODE_ONE_SHOT
#define CIA_CR_RUNMODE_ONE_SHOT 0x08
CIA_CR_START
#define CIA_CR_START 0x01
Common control register bits.
CIA_CRA
#define CIA_CRA 14
Control register A.
CIA_CRA_INMODE
#define CIA_CRA_INMODE 0x20
CR A control register bits.
CIA_CRA_INMODE_CNT
#define CIA_CRA_INMODE_CNT 0x20
CIA_CRA_INMODE_PHI2
#define CIA_CRA_INMODE_PHI2 0x00
CIA_CRA_SPMODE
#define CIA_CRA_SPMODE 0x40
CIA_CRA_SPMODE_IN
#define CIA_CRA_SPMODE_IN 0x00
CIA_CRA_SPMODE_OUT
#define CIA_CRA_SPMODE_OUT 0x40
CIA_CRA_TODIN
#define CIA_CRA_TODIN 0x80
CIA_CRA_TODIN_50HZ
#define CIA_CRA_TODIN_50HZ 0x80
CIA_CRA_TODIN_60HZ
#define CIA_CRA_TODIN_60HZ 0x00
CIA_CRB
#define CIA_CRB 15
Control register B.
CIA_CRB_ALARM
#define CIA_CRB_ALARM 0x80
CIA_CRB_ALARM_ALARM
#define CIA_CRB_ALARM_ALARM 0x80
CIA_CRB_ALARM_TOD
#define CIA_CRB_ALARM_TOD 0x00
CIA_CRB_INMODE
#define CIA_CRB_INMODE 0x60
CR B control register bits.
CIA_CRB_INMODE_CNT
#define CIA_CRB_INMODE_CNT 0x20
CIA_CRB_INMODE_PHI2
#define CIA_CRB_INMODE_PHI2 0x00
CIA_CRB_INMODE_TA
#define CIA_CRB_INMODE_TA 0x40
CIA_CRB_INMODE_TA_CNT
#define CIA_CRB_INMODE_TA_CNT 0x60
CIA_DDRA
#define CIA_DDRA 2
Data direction register for port A.
CIA_DDRB
#define CIA_DDRB 3
Data direction register for port B.
CIA_ICR
#define CIA_ICR 13
Interrupt control register.
CIA_IM_FLG
#define CIA_IM_FLG 16
Handshake.
CIA_IM_SDR
#define CIA_IM_SDR 8
Shift Register completion.
CIA_IM_SET
#define CIA_IM_SET 0x80
Interrupt Masks.
Control Bit
CIA_IM_TA
#define CIA_IM_TA 1
Timer A underflow.
CIA_IM_TB
#define CIA_IM_TB 2
Timer B underflow.
CIA_IM_TBB
#define CIA_IM_TBB 0x100
Timer B bug flag.
CIA_IM_TOD
#define CIA_IM_TOD 4
TOD Clock Alarm.
CIA_MODEL_6526
#define CIA_MODEL_6526 0
MOS 6526 models.
"old"
CIA_MODEL_6526A
#define CIA_MODEL_6526A 1
"new"
CIA_PRA
#define CIA_PRA 0
MOS 6526 registers.
Port A
CIA_PRB
#define CIA_PRB 1
Port B.
CIA_SDR
#define CIA_SDR 12
Serial port shift register.
CIA_TAH
#define CIA_TAH 5
Timer A high.
CIA_TAL
#define CIA_TAL 4
Timer A low.
CIA_TBH
#define CIA_TBH 7
Timer B high.
CIA_TBL
#define CIA_TBL 6
Timer B low.
CIA_TOD_HR
#define CIA_TOD_HR 11
Time Of Day clock hour.
CIA_TOD_MIN
#define CIA_TOD_MIN 10
Time Of Day clock min.
CIA_TOD_SEC
#define CIA_TOD_SEC 9
Time Of Day clock sec.
CIA_TOD_TEN
#define CIA_TOD_TEN 8
Time Of Day clock 1/10 s.
Typedef Documentation
cia_context_t
typedef struct cia_context_s cia_context_t
Function Documentation
ciacore_disable()
void ciacore_disable (struct cia_context_s * cia_context)
Referenced by iec_drive_reset().
ciacore_dump()
int ciacore_dump (cia_context_t * cia_context)
< Interrupt control register
< Interrupt control register
< Interrupt control register
< Interrupt control register
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Interrupt control register
< Interrupt control register
Referenced by cia1571_dump(), cia1581_dump(), cia2_dump(), mem_dump_io(), and mos5710_dump().
ciacore_init()
void ciacore_init (struct cia_context_s * cia_context, struct alarm_context_s * alarm_context, struct interrupt_cpu_status_s * int_status)
Referenced by cia1571_init(), cia1581_init(), cia1_init(), and cia2_init().
ciacore_peek()
uint8_t ciacore_peek (cia_context_t * cia_context, uint16_t addr)
Todo:
FIXME: this function should return the current state of the registers without affecting the state of the emulation.
< Port A
< Port B
< Data direction register for port A
< Data direction register for port B
< Timer A low
< Timer A high
< Timer B low
< Timer B high
< Time Of Day clock 1/10 s
< Time Of Day clock sec
< Time Of Day clock min
< Time Of Day clock hour
< Serial port shift register
< Serial port shift register
< Interrupt control register
< Control register A
< Control register B
Todo:
FIXME: perhaps we need to restore some of the state from before reading. needs testing. NOTE: cia_context->last_read is only used to handle RMW instructions, since we only ever call this function in between instructions, we dont have to restore it's value.
Referenced by cia1571_peek(), cia1581_peek(), cia1_peek(), cia2_peek(), ciacore_dump(), ciacore_snapshot_write_module(), and mos5710_peek().
ciacore_read()
uint8_t ciacore_read (struct cia_context_s * cia_context, uint16_t addr)
< Port A
< Port B
< Control register A
< Control register B
< Control register A
< Control register A
< Control register B
< Control register B
< Timer A low
< Timer A high
< Timer B low
< Timer B high
< Time Of Day clock 1/10 s
< Time Of Day clock sec
< Time Of Day clock min
< Time Of Day clock hour
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Time Of Day clock hour
< Time Of Day clock 1/10 s
< Serial port shift register
< Serial port shift register
< Interrupt control register
< Timer B bug flag
< Timer B bug flag
< Timer B underflow
< "old"
< Interrupt1
< Control Bit
< ClearIcr0 Countdown to ack-ing (resetting) irq source bits
< Interrupt1
< SetIcr1
< ClearIcr0 Countdown to ack-ing (resetting) irq source bits
< Interrupt1
< Control Bit
< ReadIcr0 How long since ICR was read
< Control register A
< Control register A
< Control register B
< Control register B
Referenced by cia1571_read(), cia1581_read(), cia1_read(), cia2_read(), ciacore_peek(), and mos5710_read().
ciacore_reset()
void ciacore_reset (struct cia_context_s * cia_context)
< history of the CNT output value
< After all these bits are set or
< reset, we can stop updating them
< until CNT is toggled.
< Time Of Day clock hour
< Time Of Day clock 1/10 s
Referenced by ciacore_snapshot_read_module(), iec_drive_reset(), and machine_specific_reset().
ciacore_set_cnt()
void ciacore_set_cnt (struct cia_context_s * cia_context, bool data)
< Control register A
Todo:
Handle Timer B if it is in CNT pulse counting mode
ciacore_set_flag()
void ciacore_set_flag (struct cia_context_s * cia_context)
< Handshake
Referenced by c64_userport_set_flag(), cia2_set_flagx(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), iecbus_cpu_write_conf3(), machine_trigger_flux_change(), parallel_cable_cpu_pulse(), parallel_cable_drive_read(), and parallel_cable_drive_write().
ciacore_set_sdr()
void ciacore_set_sdr (struct cia_context_s * cia_context, uint8_t data)
< Control register A
< Serial port shift register
< Shift Register completion
Referenced by c64fastiec_fast_cpu_write(), cia2_set_sdrx(), ciacore_set_cnt(), and iec_fast_drive_write().
ciacore_set_sp()
void ciacore_set_sp (struct cia_context_s * cia_context, bool data)
ciacore_setup_context()
void ciacore_setup_context (struct cia_context_s * cia_context)
Referenced by cia1571_setup_context(), cia1581_setup_context(), cia1_setup_context(), and cia2_setup_context().
ciacore_shutdown()
void ciacore_shutdown (cia_context_t * cia_context)
Referenced by iec_drive_shutdown(), and machine_specific_shutdown().
ciacore_snapshot_read_module()
int ciacore_snapshot_read_module (struct cia_context_s * cia_context, struct snapshot_s * s)
< Port A
< Port B
< Data direction register for port A
< Data direction register for port B
< Port A
< Data direction register for port A
< Port B
< Data direction register for port B
< Time Of Day clock 1/10 s
< Time Of Day clock sec
< Time Of Day clock min
< Time Of Day clock hour
< Serial port shift register
< Interrupt control register
< Control register A
< Control register B
< Control register A
< Control register B
< Interrupt control register
< Control Bit
Referenced by c64_snapshot_read(), and iec_drive_snapshot_read().
ciacore_snapshot_write_module()
int ciacore_snapshot_write_module (cia_context_t * cia_context, snapshot_t * s)
FIXME!!! Error check.
< Port A
< Port B
< Data direction register for port A
< Data direction register for port B
< Time Of Day clock 1/10 s
< Time Of Day clock sec
< Time Of Day clock min
< Time Of Day clock hour
< Serial port shift register
< Interrupt control register
< Control register A
< Control register B
< Interrupt control register
Referenced by c64_snapshot_write(), and iec_drive_snapshot_write().
ciacore_store()
void ciacore_store (struct cia_context_s * cia_context, uint16_t addr, uint8_t data)
Referenced by cia1571_store(), cia1581_store(), cia1_store(), cia2_store(), and mos5710_store().