vsid: arch/gtk3/widgets/petkeyboardtypewidget.h File Reference
petkeyboardtypewidget.h File Reference
PET keyboard type widget - header.
#include "vice.h"
#include <gtk/gtk.h>
#include "machine.h"
Functions
void pet_keyboard_type_widget_set_keyboard_num_get (int(*f)(void))
Set the getter function for the number of keyboard types.
void pet_keyboard_type_widget_set_keyboard_list_get (kbdtype_info_t *(*f)(void))
Set the getter function for the keyboard types list.
GtkWidget * pet_keyboard_type_widget_create (void)
Create PET keyboard type widget.
void pet_keyboard_type_widget_set_callback (GtkWidget *widget, void(*func)(int))
Set user-defined callback to be triggered when the widget changes.
void pet_keyboard_type_widget_sync (GtkWidget *widget)
Synchronize widget with its current resource value.
Detailed Description
PET keyboard type widget - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
pet_keyboard_type_widget_create()
GtkWidget * pet_keyboard_type_widget_create (void)
Create PET keyboard type widget.
Returns
GtkGrid
Referenced by create_pet_layout().
pet_keyboard_type_widget_set_callback()
void pet_keyboard_type_widget_set_callback (GtkWidget * widget, void(*)(int) func)
Set user-defined callback to be triggered when the widget changes.
Parameters
[in] widget PET keyboard type widget
[in] func user-defined callback
Referenced by create_pet_layout().
pet_keyboard_type_widget_set_keyboard_list_get()
void pet_keyboard_type_widget_set_keyboard_list_get (kbdtype_info_t *(*)(void) func)
Set the getter function for the keyboard types list.
Parameters
[in] func function pointer
pet_keyboard_type_widget_set_keyboard_num_get()
void pet_keyboard_type_widget_set_keyboard_num_get (int(*)(void) func)
Set the getter function for the number of keyboard types.
This doesn't seem strictly required for PET, since the keyboard info list has a terminator
Parameters
[in] func function pointer
pet_keyboard_type_widget_sync()
void pet_keyboard_type_widget_sync (GtkWidget * widget)
Synchronize widget with its current resource value.
Parameters
[in,out] widget PET keyboard type widget
Referenced by machine_model_handler_pet().