vsid: arch/gtk3/uiabout.c File Reference
uiabout.c File Reference
GTK3 about dialog.
#include "vice.h"
#include <gtk/gtk.h>
#include <string.h>
#include "archdep.h"
#include "debug_gtk3.h"
#include "info.h"
#include "lib.h"
#include "ui.h"
#include "uiactions.h"
#include "uidata.h"
#include "version.h"
#include "vicedate.h"
#include "uiabout.h"
Macros
#define VERSION_STRING_MAX 8192
Maximum length of generated version string.
Functions
static char ** create_current_team_list (void)
Create list of current team members.
static void destroy_current_team_list (char **list)
Deallocate current team list.
static GdkPixbuf * get_vice_logo (void)
Create VICE logo.
static void about_destroy_callback (GtkWidget *widget, gpointer user_data)
Handler for the "destroy" event.
static void about_response_callback (GtkWidget *widget, gint response_id, gpointer user_data)
Handler for the "response" event.
void ui_about_dialog_show (void)
Show the about dialog.
Variables
static char ** authors
List of current team members.
Detailed Description
GTK3 about dialog.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Greg King gregd.nosp@m.k@us.nosp@m.ers.s.nosp@m.f.ne.nosp@m.t
Macro Definition Documentation
VERSION_STRING_MAX
#define VERSION_STRING_MAX 8192
Maximum length of generated version string.
Function Documentation
about_destroy_callback()
static void about_destroy_callback (GtkWidget * widget, gpointer user_data) static
Handler for the "destroy" event.
Parameters
[in,out] widget widget triggering the event (unused)
[in] user_data data for the event (unused)
Referenced by ui_about_dialog_show().
about_response_callback()
static void about_response_callback (GtkWidget * widget, gint response_id, gpointer user_data) static
Handler for the "response" event.
This handles the "response" event, which is triggered for various standard buttons, although which buttons trigger this is a little unclear at the moment.
Parameters
[in,out] widget widget triggering the event (the dialog)
[in] response_id response ID
[in] user_data extra data (unused)
Referenced by ui_about_dialog_show().
create_current_team_list()
static char ** create_current_team_list (void) static
Create list of current team members.
Returns
heap-allocated list of strings
Referenced by ui_about_dialog_show().
destroy_current_team_list()
static void destroy_current_team_list (char ** list) static
Deallocate current team list.
Parameters
[in,out] list list of team member names
Referenced by about_destroy_callback().
get_vice_logo()
static GdkPixbuf * get_vice_logo (void) static
Create VICE logo.
Returns
GdkPixbuf instance
Referenced by ui_about_dialog_show().
ui_about_dialog_show()
void ui_about_dialog_show (void)
Show the about dialog.
Referenced by help_about_action().
Variable Documentation
authors
char** authors static
List of current team members.
This list is allocated in create_current_team_list() and deallocated in the "destroy" callback of the About dialog
Referenced by about_destroy_callback(), and ui_about_dialog_show().