x128: gfxoutputdrv/artstudiodrv.c File Reference
artstudiodrv.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "archdep.h"
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "mem.h"
#include "gfxoutput.h"
#include "nativedrv.h"
#include "palette.h"
#include "resources.h"
#include "screenshot.h"
#include "types.h"
#include "uiapi.h"
#include "util.h"
#include "vsync.h"
Macros
#define ARTSTUDIO_SCREEN_PIXEL_WIDTH 320
#define ARTSTUDIO_SCREEN_PIXEL_HEIGHT 200
#define ARTSTUDIO_SCREEN_BYTE_WIDTH ARTSTUDIO_SCREEN_PIXEL_WIDTH / 8
#define ARTSTUDIO_SCREEN_BYTE_HEIGHT ARTSTUDIO_SCREEN_PIXEL_HEIGHT / 8
#define VIDEORAM_OFFSET 0x1f42
define offsets in the artstudio file
#define BITMAP_OFFSET 2
#define ARTSTUDIO_SIZE 9002 + 7
Functions
static int set_oversize_handling (int val, void *param)
static int set_undersize_handling (int val, void *param)
static int set_multicolor_handling (int val, void *param)
static int set_ted_lum_handling (int val, void *param)
static int artstudiodrv_resources_init (void)
static int artstudiodrv_cmdline_options_init (void)
static void artstudio_check_and_correct_cell (native_data_t *source)
static int artstudio_render_and_save (native_data_t *source)
static int artstudio_multicolor_render (native_data_t *data)
static int artstudio_vicii_save (screenshot_t *screenshot, const char *filename)
static int artstudio_ted_save (screenshot_t *screenshot, const char *filename)
static int artstudio_vic_save (screenshot_t *screenshot, const char *filename)
static int artstudio_crtc_save (screenshot_t *screenshot, const char *filename)
static int artstudio_vdc_save (screenshot_t *screenshot, const char *filename)
static int artstudiodrv_save (screenshot_t *screenshot, const char *filename)
void gfxoutput_init_artstudio (int help)
Variables
static gfxoutputdrv_t artstudio_drv
static int oversize_handling
static int undersize_handling
static int multicolor_handling
static int ted_lum_handling
static const resource_int_t resources_int []
static const resource_int_t resources_int_plus4 []
static const cmdline_option_t cmdline_options []
static const cmdline_option_t cmdline_options_plus4 []
Macro Definition Documentation
ARTSTUDIO_SCREEN_BYTE_HEIGHT
#define ARTSTUDIO_SCREEN_BYTE_HEIGHT ARTSTUDIO_SCREEN_PIXEL_HEIGHT / 8
ARTSTUDIO_SCREEN_BYTE_WIDTH
#define ARTSTUDIO_SCREEN_BYTE_WIDTH ARTSTUDIO_SCREEN_PIXEL_WIDTH / 8
ARTSTUDIO_SCREEN_PIXEL_HEIGHT
#define ARTSTUDIO_SCREEN_PIXEL_HEIGHT 200
ARTSTUDIO_SCREEN_PIXEL_WIDTH
#define ARTSTUDIO_SCREEN_PIXEL_WIDTH 320
ARTSTUDIO_SIZE
#define ARTSTUDIO_SIZE 9002 + 7
BITMAP_OFFSET
#define BITMAP_OFFSET 2
VIDEORAM_OFFSET
#define VIDEORAM_OFFSET 0x1f42
define offsets in the artstudio file
Function Documentation
artstudio_check_and_correct_cell()
static void artstudio_check_and_correct_cell (native_data_t * source) static
Referenced by artstudio_multicolor_render(), and artstudio_vic_save().
artstudio_crtc_save()
static int artstudio_crtc_save (screenshot_t * screenshot, const char * filename) static
Referenced by artstudiodrv_save().
artstudio_multicolor_render()
static int artstudio_multicolor_render (native_data_t * data) static
Referenced by artstudio_ted_save(), and artstudio_vicii_save().
artstudio_render_and_save()
static int artstudio_render_and_save (native_data_t * source) static
< write mode (binary)
Referenced by artstudio_crtc_save(), artstudio_ted_save(), artstudio_vdc_save(), artstudio_vic_save(), and artstudio_vicii_save().
artstudio_ted_save()
static int artstudio_ted_save (screenshot_t * screenshot, const char * filename) static
Referenced by artstudiodrv_save().
artstudio_vdc_save()
static int artstudio_vdc_save (screenshot_t * screenshot, const char * filename) static
Referenced by artstudiodrv_save().
artstudio_vic_save()
static int artstudio_vic_save (screenshot_t * screenshot, const char * filename) static
Referenced by artstudiodrv_save().
artstudio_vicii_save()
static int artstudio_vicii_save (screenshot_t * screenshot, const char * filename) static
Referenced by artstudiodrv_save().
artstudiodrv_cmdline_options_init()
static int artstudiodrv_cmdline_options_init (void) static
artstudiodrv_resources_init()
static int artstudiodrv_resources_init (void) static
artstudiodrv_save()
static int artstudiodrv_save (screenshot_t * screenshot, const char * filename) static
gfxoutput_init_artstudio()
void gfxoutput_init_artstudio (int help)
Referenced by gfxoutput_early_init().
set_multicolor_handling()
static int set_multicolor_handling (int val, void * param) static
set_oversize_handling()
static int set_oversize_handling (int val, void * param) static
set_ted_lum_handling()
static int set_ted_lum_handling (int val, void * param) static
set_undersize_handling()
static int set_undersize_handling (int val, void * param) static
Variable Documentation
artstudio_drv
static gfxoutputdrv_t artstudio_drv static
Initial value:
=
{
    GFXOUTPUTDRV_TYPE_SCREENSHOT_NATIVE,
    "ARTSTUDIO",
    "OCP Artstudio screenshot",
    "ocp",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    artstudiodrv_save,
    NULL,
    NULL,
    artstudiodrv_resources_init,
    artstudiodrv_cmdline_options_init
}
Referenced by artstudio_render_and_save(), and gfxoutput_init_artstudio().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-ocpoversize", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "OCPOversizeHandling", NULL,
      "<method>", "Select the way the oversized input should be handled,"
      " (0: scale down, 1: crop left top, 2: crop center top,  3: crop right top,"
      " 4: crop left center, 5: crop center, 6: crop right center, 7: crop left bottom,"
      " 8: crop center bottom, 9:  crop right bottom)" },
    { "-ocpundersize", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "OCPUndersizeHandling", NULL,
      "<method>", "Select the way the undersized input should be handled,"
      " (0: scale up, 1: borderize)" },
    { "-ocpmc", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "OCPMultiColorHandling", NULL,
      "<method>", "Select the way the multicolor to hires should be handled,"
      " (0: b&w, 1: 2 colors, 2: 4 colors, 3: gray scale,  4: best cell colors)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by artstudiodrv_cmdline_options_init().
cmdline_options_plus4
const cmdline_option_t cmdline_options_plus4[] static
Initial value:
=
{
    { "-ocptedlum", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "OCPTEDLumHandling", NULL,
      "<method>", "Select the way the TED luminosity should be handled, (0: ignore, 1: dither)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by artstudiodrv_cmdline_options_init().
multicolor_handling
int multicolor_handling static
Referenced by artstudio_multicolor_render(), artstudio_vic_save(), and set_multicolor_handling().
oversize_handling
int oversize_handling static
Referenced by artstudio_crtc_save(), artstudio_vdc_save(), artstudio_vic_save(), native_crop_and_borderize_colormap(), native_resize_colormap(), and set_oversize_handling().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "OCPOversizeHandling", NATIVE_SS_OVERSIZE_SCALE, RES_EVENT_NO, NULL,
      &oversize_handling, set_oversize_handling, NULL },
    { "OCPUndersizeHandling", NATIVE_SS_UNDERSIZE_BORDERIZE, RES_EVENT_NO, NULL,
      &undersize_handling, set_undersize_handling, NULL },
    { "OCPMultiColorHandling", NATIVE_SS_MC2HR_DITHER, RES_EVENT_NO, NULL,
      &multicolor_handling, set_multicolor_handling, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by artstudiodrv_resources_init().
resources_int_plus4
const resource_int_t resources_int_plus4[] static
Initial value:
= {
    { "OCPTEDLumHandling", NATIVE_SS_TED_LUM_DITHER, RES_EVENT_NO, NULL,
      &ted_lum_handling, set_ted_lum_handling, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by artstudiodrv_resources_init().
ted_lum_handling
int ted_lum_handling static
Referenced by artstudio_ted_save(), set_ted_lum_handling(), ted_color_to_vic_color_colormap(), and ted_color_to_vicii_color_colormap().
undersize_handling
int undersize_handling static
Referenced by artstudio_crtc_save(), artstudio_vdc_save(), artstudio_vic_save(), native_resize_colormap(), and set_undersize_handling().