vsid: c64/c64gluelogic.c File Reference
c64gluelogic.c File Reference
#include "vice.h"
#include <stdio.h>
#include "alarm.h"
#include "c64_256k.h"
#include "c64gluelogic.h"
#include "c64mem.h"
#include "cmdline.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "resources.h"
#include "snapshot.h"
#include "types.h"
#include "vicii.h"
Macros
#define SNAP_MAJOR 1
#define SNAP_MINOR 0
Functions
static void perform_vbank_switch (int vbank)
static void glue_alarm_set (void)
static void glue_alarm_unset (void)
static void glue_alarm_handler (CLOCK offset, void *data)
void c64_glue_undump (int vbank)
void c64_glue_set_vbank (int vbank, int ddr_flag)
void c64_glue_reset (void)
static int set_glue_type (int val, void *param)
int c64_glue_resources_init (void)
int c64_glue_cmdline_options_init (void)
void c64_glue_init (void)
int c64_glue_snapshot_write_module (snapshot_t *s)
int c64_glue_snapshot_read_module (snapshot_t *s)
Variables
static int glue_logic_type = 0
static int old_vbank = 0
static int glue_alarm_active = 0
static alarm_t * glue_alarm = NULL
static resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
static char snap_module_name [] = "GLUE"
Macro Definition Documentation
SNAP_MAJOR
#define SNAP_MAJOR 1
SNAP_MINOR
#define SNAP_MINOR 0
Function Documentation
c64_glue_cmdline_options_init()
int c64_glue_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
c64_glue_init()
void c64_glue_init (void)
Referenced by machine_specific_init().
c64_glue_reset()
void c64_glue_reset (void)
Referenced by do_reset_cia().
c64_glue_resources_init()
int c64_glue_resources_init (void)
Referenced by machine_resources_init().
c64_glue_set_vbank()
void c64_glue_set_vbank (int vbank, int ddr_flag)
Referenced by store_ciapa().
c64_glue_snapshot_read_module()
int c64_glue_snapshot_read_module (snapshot_t * s)
Referenced by c64_snapshot_read().
c64_glue_snapshot_write_module()
int c64_glue_snapshot_write_module (snapshot_t * s)
Referenced by c64_snapshot_write().
c64_glue_undump()
void c64_glue_undump (int vbank)
Referenced by undump_ciapa().
glue_alarm_handler()
static void glue_alarm_handler (CLOCK offset, void * data) static
Referenced by c64_glue_init().
glue_alarm_set()
static void glue_alarm_set (void) static
Referenced by c64_glue_set_vbank(), and c64_glue_snapshot_read_module().
glue_alarm_unset()
static void glue_alarm_unset (void) static
Referenced by c64_glue_reset(), c64_glue_snapshot_read_module(), and glue_alarm_handler().
perform_vbank_switch()
static void perform_vbank_switch (int vbank) static
Referenced by c64_glue_reset(), c64_glue_set_vbank(), c64_glue_undump(), and glue_alarm_handler().
set_glue_type()
static int set_glue_type (int val, void * param) static
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-gluelogictype", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "GlueLogic", NULL,
      "<Type>", "Set glue logic type (0 = discrete, 1 = 252535-01)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by c64_glue_cmdline_options_init().
glue_alarm
alarm_t* glue_alarm = NULL static
Referenced by c64_glue_init(), glue_alarm_set(), and glue_alarm_unset().
glue_alarm_active
int glue_alarm_active = 0 static
Referenced by c64_glue_reset(), c64_glue_snapshot_read_module(), c64_glue_snapshot_write_module(), glue_alarm_set(), and glue_alarm_unset().
glue_logic_type
int glue_logic_type = 0 static
Referenced by c64_glue_set_vbank(), c64_glue_snapshot_read_module(), c64_glue_snapshot_write_module(), and set_glue_type().
old_vbank
int old_vbank = 0 static
Referenced by c64_glue_reset(), c64_glue_set_vbank(), c64_glue_snapshot_read_module(), c64_glue_snapshot_write_module(), c64_glue_undump(), and glue_alarm_handler().
resources_int
resource_int_t resources_int[] static
Initial value:
= {
    { "GlueLogic",  1 , RES_EVENT_NO, NULL,
      &glue_logic_type, set_glue_type, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by c64_glue_resources_init().
snap_module_name
char snap_module_name[] = "GLUE" static
Referenced by c64_glue_snapshot_read_module(), and c64_glue_snapshot_write_module().