x128: arch/gtk3/widgets/driveunitwidget.c File Reference
driveunitwidget.c File Reference
GTK3 drive unit selection widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "debug_gtk3.h"
#include "drive.h"
#include "widgethelpers.h"
#include "driveunitwidget.h"
Functions
static void on_radio_toggled (GtkWidget *widget, gpointer user_data)
Handler for the 'toggled' events of the radio buttons.
static GtkWidget * create_radio_group (int unit)
Create a GtkGrid with radio buttons in a group for unit numbers.
GtkWidget * drive_unit_widget_create (int unit, int *target, void(*callback)(int))
Create a unit#-selection widget.
Variables
static int * unit_target
Destination of the unit number when changed.
static void(* unit_callback)(int) = NULL
Callback triggered on unit number change.
Detailed Description
GTK3 drive unit selection widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_radio_group()
static GtkWidget * create_radio_group (int unit) static
Create a GtkGrid with radio buttons in a group for unit numbers.
Sets up event handler to change the unit_target variable passed in create_drive_unit_widget().
Parameters
[in] unit default unit
Returns
GtkGrid
Referenced by drive_unit_widget_create().
drive_unit_widget_create()
GtkWidget * drive_unit_widget_create (int unit, int * target, void(*)(int) callback)
Create a unit#-selection widget.
Parameters
[in] unit currently selected unit number (8-11)
[out] target destination of the unit number on radio button clicks
[in] callback function to call on unit number changes
Returns
GtkGrid
Referenced by create_extra_widget().
on_radio_toggled()
static void on_radio_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the 'toggled' events of the radio buttons.
Parameters
[in] widget radio button triggering the event
[in] user_data unit number (int)
Referenced by drive_unit_widget_create().
Variable Documentation
unit_callback
void(* unit_callback) (int) (int) = NULL static
Callback triggered on unit number change.
This is an optional callback to allow updating other widgets depending on the selected unit number. Pass NULL as the callback argument to create_drive_unit_widget() to disable this.
Referenced by drive_unit_widget_create(), and on_radio_toggled().
unit_target
int* unit_target static
Destination of the unit number when changed.
Set when the unit number in the widget changes, pass NULL as the target argument to disable this.
Referenced by drive_unit_widget_create(), and on_radio_toggled().