vsid: machine.h File Reference
machine.h File Reference
#include "types.h"
#include <stdbool.h>
Data Structures
struct machine_timing_s
struct kbdtype_info_t
mapping info for GUIs
Macros
#define VICE_MACHINE_NONE 0
A little handier way to identify the machine:
#define VICE_MACHINE_C64 (1U<<0)
#define VICE_MACHINE_C128 (1U<<1)
#define VICE_MACHINE_VIC20 (1U<<2)
#define VICE_MACHINE_PET (1U<<3)
#define VICE_MACHINE_CBM5x0 (1U<<4)
#define VICE_MACHINE_CBM6x0 (1U<<5)
#define VICE_MACHINE_PLUS4 (1U<<6)
#define VICE_MACHINE_C64DTV (1U<<7)
#define VICE_MACHINE_C64SC (1U<<8)
#define VICE_MACHINE_VSID (1U<<9)
#define VICE_MACHINE_SCPU64 (1U<<10)
#define VICE_MACHINE_ALL (VICE_MACHINE_C64|VICE_MACHINE_C64SC|VICE_MACHINE_C64DTV|VICE_MACHINE_SCPU64|VICE_MACHINE_C128|VICE_MACHINE_VIC20|VICE_MACHINE_PLUS4|VICE_MACHINE_PET|VICE_MACHINE_CBM5x0|VICE_MACHINE_CBM6x0|VICE_MACHINE_VSID)
#define MACHINE_SYNC_PAL 1
Sync factors (changed to positive 2016-11-07, BW)
#define MACHINE_SYNC_NTSC 2
#define MACHINE_SYNC_NTSCOLD 3
#define MACHINE_SYNC_PALN 4
#define MACHINE_JAM_ACTION_DIALOG 0
#define MACHINE_JAM_ACTION_CONTINUE 1
#define MACHINE_JAM_ACTION_MONITOR 2
#define MACHINE_JAM_ACTION_RESET_CPU 3
#define MACHINE_JAM_ACTION_POWER_CYCLE 4
#define MACHINE_JAM_ACTION_QUIT 5
#define MACHINE_NUM_JAM_ACTIONS 6
#define MACHINE_RESET_MODE_RESET_CPU 0
Reset the machine.
#define MACHINE_RESET_MODE_POWER_CYCLE 1
#define JAM_NONE 0
#define JAM_RESET_CPU 1
#define JAM_POWER_CYCLE 2
#define JAM_MONITOR 3
Typedefs
typedef struct machine_timing_s machine_timing_t
Functions
int machine_common_resources_init (void)
Initialize the machine's resources.
int machine_resources_init (void)
void machine_common_resources_shutdown (void)
void machine_resources_shutdown (void)
int machine_common_cmdline_options_init (void)
Initialize the machine's command-line options.
int machine_cmdline_options_init (void)
C64-specific command-line option initialization.
void machine_setup_context (void)
Initialize the machine.
int machine_init (void)
int machine_specific_init (void)
C64-specific initialization.
void machine_early_init (void)
void machine_maincpu_init (void)
Initialize the main CPU of the machine.
void machine_maincpu_shutdown (void)
Shutdown the main CPU of the machine.
void machine_trigger_reset (const unsigned int reset_mode)
void machine_reset (void)
called via cpu_reset()
void machine_specific_reset (void)
C64-specific reset sequence.
void machine_reset_event_playback (CLOCK offset, void *data)
void machine_powerup (void)
Power-up the machine.
void machine_specific_powerup (void)
void machine_shutdown (void)
Shutdown the emachine.
void machine_specific_shutdown (void)
void machine_set_restore_key (int v)
Set the state of the RESTORE key (!=0 means pressed)
int machine_has_restore_key (void)
returns 1 if key is present
long machine_get_cycles_per_second (void)
Get the number of CPU cylces per second.
long machine_get_cycles_per_frame (void)
Get the number of CPU cylces per frame.
void machine_set_cycles_per_frame (long cpf)
Set the screen refresh rate, as this is variable in the CRTC.
void machine_get_line_cycle (unsigned int *line, unsigned int *cycle, int *half_cycle)
Get current line and cycle.
int machine_write_snapshot (const char *name, int save_roms, int save_disks, int even_mode)
Write a snapshot.
int machine_read_snapshot (const char *name, int even_mode)
Read a snapshot.
void machine_handle_pending_alarms (CLOCK num_write_cycles)
handle pending interrupts - needed by libsid.a.
int machine_autodetect_psid (const char *name)
Autodetect PSID file.
void machine_play_psid (int tune)
int machine_sid2_check_range (unsigned int sid_adr)
Check the base address for the second sid chip.
int machine_sid3_check_range (unsigned int sid_adr)
Check the base address for the third sid chip.
int machine_sid4_check_range (unsigned int sid_adr)
Check the base address for the fourth sid chip.
int machine_sid5_check_range (unsigned int sid_adr)
Check the base address for the fifth sid chip.
int machine_sid6_check_range (unsigned int sid_adr)
Check the base address for the sixth sid chip.
int machine_sid7_check_range (unsigned int sid_adr)
Check the base address for the seventh sid chip.
int machine_sid8_check_range (unsigned int sid_adr)
Check the base address for the eighth sid chip.
void machine_change_timing (int timeval, int powerfreq, int border_mode)
Change the timing parameters of the maching (for example PAL/NTSC).
int machine_screenshot (struct screenshot_s *screenshot, struct video_canvas_s *canvas)
int machine_canvas_async_refresh (struct canvas_refresh_s *ref, struct video_canvas_s *canvas)
unsigned int machine_jam (const char *format,...)
bool machine_is_jammed (void)
char * machine_jam_reason (void)
void machine_update_memory_ptrs (void)
Update memory pointers if memory mapping has changed.
int machine_num_keyboard_mappings (void)
struct image_contents_s * machine_diskcontents_bus_read (unsigned int unit)
void machine_romset_init (void)
Romset handling.
int machine_romset_file_load (const char *filename)
int machine_romset_file_save (const char *filename)
char * machine_romset_file_list (void)
int machine_romset_archive_item_create (const char *romset_name)
uint8_t machine_tape_type_default (void)
uint8_t machine_tape_behaviour (void)
int machine_addr_in_ram (unsigned int addr)
Check if address is in RAM (for autostart)
const char * machine_get_name (void)
Get "real" name for machine.
char * machine_get_keymap_res_name (int val)
Get keymap res name with range checking.
int machine_get_num_keyboard_types (void)
return number of available keyboard types for this machine
kbdtype_info_t * machine_get_keyboard_info_list (void)
int machine_get_keyboard_type (void)
char * machine_get_keyboard_type_name (int type)
int machine_register_userport (void)
Variables
const char machine_name []
The following stuff must be defined once per every emulated CBM machine.
int machine_class
Machine class.
bool console_mode
These variable live in src/main.c:
bool video_disabled_mode
bool help_requested
Help was requested on the command line.
bool default_settings_requested
Default setting were requested on the command line.
int machine_keymap_index
char * machine_keymap_file_list []
Macro Definition Documentation
JAM_MONITOR
#define JAM_MONITOR 3
JAM_NONE
#define JAM_NONE 0
JAM_POWER_CYCLE
#define JAM_POWER_CYCLE 2
JAM_RESET_CPU
#define JAM_RESET_CPU 1
MACHINE_JAM_ACTION_CONTINUE
#define MACHINE_JAM_ACTION_CONTINUE 1
MACHINE_JAM_ACTION_DIALOG
#define MACHINE_JAM_ACTION_DIALOG 0
MACHINE_JAM_ACTION_MONITOR
#define MACHINE_JAM_ACTION_MONITOR 2
MACHINE_JAM_ACTION_POWER_CYCLE
#define MACHINE_JAM_ACTION_POWER_CYCLE 4
MACHINE_JAM_ACTION_QUIT
#define MACHINE_JAM_ACTION_QUIT 5
MACHINE_JAM_ACTION_RESET_CPU
#define MACHINE_JAM_ACTION_RESET_CPU 3
MACHINE_NUM_JAM_ACTIONS
#define MACHINE_NUM_JAM_ACTIONS 6
MACHINE_RESET_MODE_POWER_CYCLE
#define MACHINE_RESET_MODE_POWER_CYCLE 1
MACHINE_RESET_MODE_RESET_CPU
#define MACHINE_RESET_MODE_RESET_CPU 0
Reset the machine.
MACHINE_SYNC_NTSC
#define MACHINE_SYNC_NTSC 2
MACHINE_SYNC_NTSCOLD
#define MACHINE_SYNC_NTSCOLD 3
MACHINE_SYNC_PAL
#define MACHINE_SYNC_PAL 1
Sync factors (changed to positive 2016-11-07, BW)
MACHINE_SYNC_PALN
#define MACHINE_SYNC_PALN 4
VICE_MACHINE_ALL
#define VICE_MACHINE_ALL (VICE_MACHINE_C64|VICE_MACHINE_C64SC|VICE_MACHINE_C64DTV|VICE_MACHINE_SCPU64|VICE_MACHINE_C128|VICE_MACHINE_VIC20|VICE_MACHINE_PLUS4|VICE_MACHINE_PET|VICE_MACHINE_CBM5x0|VICE_MACHINE_CBM6x0|VICE_MACHINE_VSID)
VICE_MACHINE_C128
#define VICE_MACHINE_C128 (1U<<1)
VICE_MACHINE_C64
#define VICE_MACHINE_C64 (1U<<0)
VICE_MACHINE_C64DTV
#define VICE_MACHINE_C64DTV (1U<<7)
VICE_MACHINE_C64SC
#define VICE_MACHINE_C64SC (1U<<8)
VICE_MACHINE_CBM5x0
#define VICE_MACHINE_CBM5x0 (1U<<4)
VICE_MACHINE_CBM6x0
#define VICE_MACHINE_CBM6x0 (1U<<5)
VICE_MACHINE_NONE
#define VICE_MACHINE_NONE 0
A little handier way to identify the machine:
VICE_MACHINE_PET
#define VICE_MACHINE_PET (1U<<3)
VICE_MACHINE_PLUS4
#define VICE_MACHINE_PLUS4 (1U<<6)
VICE_MACHINE_SCPU64
#define VICE_MACHINE_SCPU64 (1U<<10)
VICE_MACHINE_VIC20
#define VICE_MACHINE_VIC20 (1U<<2)
VICE_MACHINE_VSID
#define VICE_MACHINE_VSID (1U<<9)
Typedef Documentation
machine_timing_t
typedef struct machine_timing_s machine_timing_t
Function Documentation
machine_addr_in_ram()
int machine_addr_in_ram (unsigned int addr)
Check if address is in RAM (for autostart)
Check if address is in RAM (for autostart)
Referenced by check_rom_area().
machine_autodetect_psid()
int machine_autodetect_psid (const char * name)
Autodetect PSID file.
Todo:
FIXME: those two shouldnt be here anymore
Todo:
FIXME: show error message box
Referenced by initcmdline_check_psid(), and ui_vsid_window_load_psid().
machine_canvas_async_refresh()
int machine_canvas_async_refresh (struct canvas_refresh_s * ref, struct video_canvas_s * canvas)
machine_change_timing()
void machine_change_timing (int timeval, int powerfreq, int border_mode)
Change the timing parameters of the maching (for example PAL/NTSC).
Referenced by on_vsync_set_border_mode(), set_power_freq(), and set_sync_factor().
machine_cmdline_options_init()
int machine_cmdline_options_init (void)
C64-specific command-line option initialization.
Referenced by init_cmdline_options().
machine_common_cmdline_options_init()
int machine_common_cmdline_options_init (void)
Initialize the machine's command-line options.
Referenced by init_cmdline_options().
machine_common_resources_init()
int machine_common_resources_init (void)
Initialize the machine's resources.
Referenced by init_resources().
machine_common_resources_shutdown()
void machine_common_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
machine_diskcontents_bus_read()
struct image_contents_s * machine_diskcontents_bus_read (unsigned int unit)
machine_early_init()
void machine_early_init (void)
Referenced by main_program().
machine_get_cycles_per_frame()
long machine_get_cycles_per_frame (void)
Get the number of CPU cylces per frame.
Referenced by ffmpegexedrv_init_video(), file_load_sample(), kbd_make_event_timestap(), kbdbuf_flush(), reboot_for_autostart(), sound_set_relative_speed(), and zmbvdrv_init_video().
machine_get_cycles_per_second()
long machine_get_cycles_per_second (void)
Get the number of CPU cylces per second.
This is used in various parts.
Referenced by c64_rsuser_init(), event_alarm_handler(), event_snapshot_read_module(), fastload_mode_init(), fastload_postdelay(), ffmpegexedrv_init_video(), file_load_sample(), print_cycle_time(), reboot_for_autostart(), receive_1bit_callback(), set_acia_ticks(), sound_set_relative_speed(), tapecart_enable(), tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), tapecart_set_mode(), and zmbvdrv_init_video().
machine_get_keyboard_info_list()
kbdtype_info_t * machine_get_keyboard_info_list (void)
Referenced by keyboard_is_hosttype_valid().
machine_get_keyboard_type()
int machine_get_keyboard_type (void)
machine_get_keyboard_type_name()
char * machine_get_keyboard_type_name (int type)
Referenced by keyboard_get_keymap_name().
machine_get_keymap_res_name()
char * machine_get_keymap_res_name (int val)
Get keymap res name with range checking.
Referenced by load_keymap_file().
machine_get_line_cycle()
void machine_get_line_cycle (unsigned int * line, unsigned int * cycle, int * half_cycle)
Get current line and cycle.
Referenced by maincpu_monitor_interface_get().
machine_get_name()
const char * machine_get_name (void)
Get "real" name for machine.
May differ from machine_name.
Referenced by actions_speed_setup_ui(), archdep_default_autostart_disk_image_file_name(), archdep_default_fliplist_file_name(), archdep_default_joymap_file_name(), autostart_snapshot(), c64_snapshot_read(), c64_snapshot_write(), event_playback_start_trap(), init_resources(), mouse_grab_toggle_action(), quicksnap_filename(), save_header(), and ui_create_main_window().
machine_get_num_keyboard_types()
int machine_get_num_keyboard_types (void)
return number of available keyboard types for this machine
Referenced by keyboard_is_hosttype_valid().
machine_handle_pending_alarms()
void machine_handle_pending_alarms (CLOCK num_write_cycles)
handle pending interrupts - needed by libsid.a.
Referenced by sid_read_chip(), sid_store_chip(), and zero_store().
machine_has_restore_key()
int machine_has_restore_key (void)
returns 1 if key is present
Referenced by key_restore1_pressed(), and key_restore2_pressed().
machine_init()
int machine_init (void)
Referenced by init_main().
machine_is_jammed()
bool machine_is_jammed (void)
Referenced by statusbar_speed_widget_update(), and vice_opengl_on_ui_frame_clock().
machine_jam()
unsigned int machine_jam (const char * format, ...)
machine_jam_reason()
char * machine_jam_reason (void)
Referenced by statusbar_speed_widget_update().
machine_maincpu_init()
void machine_maincpu_init (void)
Initialize the main CPU of the machine.
Referenced by init_main().
machine_maincpu_shutdown()
void machine_maincpu_shutdown (void)
Shutdown the main CPU of the machine.
Referenced by cmdline_help(), and machine_shutdown().
machine_num_keyboard_mappings()
int machine_num_keyboard_mappings (void)
Referenced by keyboard_set_keymap_file().
machine_play_psid()
void machine_play_psid (int tune)
Referenced by play_current_tune(), psid_play_action(), psid_stop_action(), select_tune_from_menu(), and ui_vsid_window_load_psid().
machine_powerup()
void machine_powerup (void)
Power-up the machine.
Referenced by machine_reset(), and machine_trigger_reset_internal().
machine_read_snapshot()
int machine_read_snapshot (const char * name, int even_mode)
Read a snapshot.
Referenced by event_playback_start_trap(), event_record_reset_milestone_trap(), event_record_start_trap(), load_snapshot_filename_callback(), load_snapshot_trap(), mon_read_snapshot(), network_client_connect_trap(), and quickload_snapshot_trap().
machine_register_userport()
int machine_register_userport (void)
Referenced by userport_resources_init().
machine_reset()
void machine_reset (void)
called via cpu_reset()
Referenced by cpu_reset().
machine_reset_event_playback()
void machine_reset_event_playback (CLOCK offset, void * data)
Referenced by event_alarm_handler(), and event_playback_event_list().
machine_resources_init()
int machine_resources_init (void)
Referenced by init_resources().
machine_resources_shutdown()
void machine_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
machine_romset_archive_item_create()
int machine_romset_archive_item_create (const char * romset_name)
machine_romset_file_list()
char * machine_romset_file_list (void)
machine_romset_file_load()
int machine_romset_file_load (const char * filename)
machine_romset_file_save()
int machine_romset_file_save (const char * filename)
machine_romset_init()
void machine_romset_init (void)
Romset handling.
Referenced by romset_init().
machine_screenshot()
int machine_screenshot (struct screenshot_s * screenshot, struct video_canvas_s * canvas)
Referenced by monitor_binary_process_display_get(), monitor_binary_process_palette_get(), screenshot_record(), and screenshot_save().
machine_set_cycles_per_frame()
void machine_set_cycles_per_frame (long cpf)
Set the screen refresh rate, as this is variable in the CRTC.
machine_set_restore_key()
void machine_set_restore_key (int v)
Set the state of the RESTORE key (!=0 means pressed)
Referenced by keyboard_restore_event_playback(), and restore_alarm_triggered().
machine_setup_context()
void machine_setup_context (void)
Initialize the machine.
Referenced by main_program().
machine_shutdown()
void machine_shutdown (void)
Shutdown the emachine.
Referenced by main_exit().
machine_sid2_check_range()
int machine_sid2_check_range (unsigned int sid_adr)
Check the base address for the second sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid3_check_range()
int machine_sid3_check_range (unsigned int sid_adr)
Check the base address for the third sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid4_check_range()
int machine_sid4_check_range (unsigned int sid_adr)
Check the base address for the fourth sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid5_check_range()
int machine_sid5_check_range (unsigned int sid_adr)
Check the base address for the fifth sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid6_check_range()
int machine_sid6_check_range (unsigned int sid_adr)
Check the base address for the sixth sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid7_check_range()
int machine_sid7_check_range (unsigned int sid_adr)
Check the base address for the seventh sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_sid8_check_range()
int machine_sid8_check_range (unsigned int sid_adr)
Check the base address for the eighth sid chip.
< override others on collisions
< handle collisions
< override others on collisions
< handle collisions
machine_specific_init()
int machine_specific_init (void)
C64-specific initialization.
Referenced by machine_init().
machine_specific_powerup()
void machine_specific_powerup (void)
Referenced by machine_powerup().
machine_specific_reset()
void machine_specific_reset (void)
C64-specific reset sequence.
Todo:
FIXME: whats actually broken here?
Referenced by machine_reset().
machine_specific_shutdown()
void machine_specific_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
machine_tape_behaviour()
uint8_t machine_tape_behaviour (void)
< tape interrupt is falling-edge triggered, normal tape blocks end with a long and a short pulse
< tape interrupt is falling-edge triggered, normal tape blocks end with a long and a short pulse
Referenced by tap_cbm_read_block_once(), and tap_cbm_read_header().
machine_tape_type_default()
uint8_t machine_tape_type_default (void)
< Binary Program (absolute load, SAVE "",1,1 (VIC-20 and later))
Referenced by default_tape_header_type().
machine_trigger_reset()
void machine_trigger_reset (const unsigned int reset_mode)
Referenced by c64_snapshot_read(), drivecpu_jam(), event_playback_start_trap(), event_record_start_trap(), machine_change_timing(), machine_reset_action(), maincpu_mainloop(), mon_reset_machine(), play_current_tune(), psid_play_action(), psid_stop_action(), psid_ui_set_tune(), reboot_for_autostart(), select_tune_from_menu(), set_basic_rom_name(), set_board_type(), set_c64_256k_enabled(), set_kernal_revision(), set_kernal_rom_name(), set_plus256k_enabled(), set_plus60k_enabled(), and ui_vsid_window_load_psid().
machine_update_memory_ptrs()
void machine_update_memory_ptrs (void)
Update memory pointers if memory mapping has changed.
machine_write_snapshot()
int machine_write_snapshot (const char * name, int save_roms, int save_disks, int even_mode)
Write a snapshot.
Referenced by event_record_set_milestone_trap(), event_record_start_trap(), event_record_stop_trap(), mon_write_snapshot(), network_server_connect_trap(), quicksave_snapshot_trap(), and save_snapshot_dialog().
Variable Documentation
console_mode
bool console_mode extern
These variable live in src/main.c:
These variable live in src/main.c:
The command line contained -console
Referenced by cmdline_console(), cmdline_help(), drive_jam(), drive_update_ui_status(), machine_jam(), machine_shutdown(), machine_specific_init(), machine_specific_shutdown(), main_program(), monitor_open(), psid_init_tune(), sound_error(), ui_extend_image_dialog(), ui_init_finalize(), video_canvas_create(), and video_canvas_refresh().
default_settings_requested
bool default_settings_requested extern
Default setting were requested on the command line.
The command line contained -default, which has implications for loading of configuration and ROM files from certain user directories.
Referenced by main_program(), and ui_hotkeys_init().
help_requested
bool help_requested extern
Help was requested on the command line.
The command line contained -?/-h/-help/–help.
Include "machine.h" to use this variable.
Referenced by main_program(), and vhk_filename_set().
machine_class
int machine_class extern
Machine class.
Machine class.
Referenced by acia_get_status(), actions_display_register(), actions_display_setup_ui(), actions_machine_register(), actions_speed_register(), actions_speed_setup_ui(), add_machine_symbols(), add_sliders(), archdep_app_icon_path_png(), artstudiodrv_cmdline_options_init(), artstudiodrv_resources_init(), attach_cart_image(), autostart_autodetect(), autostart_cmdline_options_init(), autostart_resources_init(), c64_glue_resources_init(), c64keyboard_init(), c64meminit(), c64rom_load_kernal(), cart_dialog_internal(), cbm2_hardwired_switches_widget_create(), cbm2_memory_size_widget_create(), charset_petscii_to_ucs(), cia1_setup_context(), cia2_setup_context(), cmdline_attach(), create_acia_base_widget(), create_base_widget(), create_c64_layout(), create_c64_misc_widget(), create_cart_type_model(), create_extra_sid_address_widget(), create_extra_widget(), create_layout(), create_num_sids_widget(), create_prg_layout(), create_screenshot_param_widget(), create_serial_baud_widget(), create_sidcart_address_widget(), create_sidcart_clock_widget(), create_stack_child_widget(), crt_control_widget_create(), crt_open(), crt_preview_widget_create(), crt_preview_widget_update(), dir_menu_popup_create(), do_smart_attach(), drive_cmdline_options_init(), drive_get_type_by_devnr(), drive_parallel_cable_widget_create(), drive_resources_init(), drive_update_ui_status(), expected_header_error(), export_dump(), generate_sid_address_range(), get_default_icon(), get_iec_device_state(), has_iec(), help_hotkeys_action(), init_cmdline_options(), init_main(), init_raster(), initcmdline_check_attach(), initcmdline_check_psid(), initcmdline_init(), is_current_machine_action(), joystick_swap_possible(), keyboard_cmdline_options_init(), keyboard_resources_init(), keyboard_resources_shutdown(), keymap_cmdline_options_init(), keymap_init(), keymap_resources_init(), koaladrv_cmdline_options_init(), koaladrv_resources_init(), machine_common_cmdline_options_init(), machine_common_resources_init(), machine_drive_resources_init(), machine_get_name(), machine_has_acia(), machine_has_iec(), machine_has_second_tape_port(), machine_has_tapecart(), machine_has_userport(), machine_model_callback(), machine_model_handler_c64(), machine_model_widget_connect_signals(), machine_model_widget_update(), machine_window_create(), main_init_hack(), main_program(), minipaintdrv_cmdline_options_init(), minipaintdrv_resources_init(), mixer_widget_create(), mixer_widget_sid_type_changed(), mon_attach(), mon_detach(), mon_file_load(), mon_file_verify(), mon_joyport_set_output(), mon_userport_set_output(), monitor_binary_process_display_get(), monitor_binary_process_palette_get(), on_cart_type_changed(), on_control_port_changed(), on_dialog_destroy(), on_iec_toggled(), on_model_toggled(), on_response(), on_vsync_set_border_mode(), output_text_init_cmdline_options(), output_text_init_resources(), palette_read_info(), populate_tree_model(), psid_init_tune(), ram_cmdline_options_init(), ram_resources_init(), raster_cmdline_options_chip_init(), raster_resources_chip_init(), rendering_area_event_handler(), screenshot_at_exit(), serial_iec_device_cmdline_options_init(), serial_iec_device_resources_init(), set_buffer_size(), set_datasette_active(), set_iec_device_state(), set_kernal_revision(), set_sid_model(), set_sid_stereo(), set_video_cache_enabled(), set_video_standard(), set_widgets_sensitivity(), settings_autofire_widget_create(), settings_controlport_widget_create(), settings_crt_widget_create(), settings_digimax_widget_create(), settings_drive_widget_create(), settings_ethernet_widget_create(), settings_georam_widget_create(), settings_host_display_widget_create(), settings_io_widget_create(), settings_joystick_widget_create(), settings_model_widget_create(), settings_rom_widget_create(), settings_rs232_widget_create(), settings_sfxsoundexpander_widget_create(), settings_sfxsoundsampler_widget_create(), settings_sidcart_widget_create(), settings_speed_widget_create(), settings_userport_widget_create(), sid_check_engine_model(), sid_cmdline_options_init(), sid_common_resources_init(), sid_get_engine_model_list(), sid_machine_get_max_sids(), sid_model_widget_create(), sid_read_chip(), sid_sound_widget_create(), statusbar_speed_widget_create(), statusbar_speed_widget_update(), tap_create(), tap_header_read(), tapeport_check_valid_device(), tapeport_device_resources_init(), tapeport_devices_cmdline_options_init(), traps_resources_init(), ui_about_dialog_show(), ui_create_datasette_control_menu(), ui_create_main_window(), ui_display_main_window(), ui_exit(), ui_hotkeys_vhk_filename_user(), ui_hotkeys_vhk_filename_vice(), ui_init_finalize(), ui_is_fullscreen(), ui_is_fullscreen_from_canvas(), ui_machine_menu_bar_create(), ui_media_dialog_show(), ui_resources_init(), ui_set_window_geometries(), ui_statusbar_create(), ui_statusbar_set_kbd_debug(), ui_statusbar_update_kbd_debug(), ui_tape_widget_create(), ui_update_fullscreen_decorations(), ui_update_lightpen(), uivideo_chip_has_border_mode(), uivideo_chip_has_sprites(), uivideo_chip_has_vert_stretch(), uivideo_chip_has_vsp_bug(), uivideo_chip_id(), uivideo_chip_name(), update_sid_addresses_sensitivity(), userport_io_sim_resources_init(), userport_io_sim_set_pax_out_lines(), userport_io_sim_set_pbx_out_lines(), userport_rsinterface_widget_create(), vicii_cmdline_options_init(), vicii_color_update_palette(), vicii_dump(), vicii_resources_init(), video_cmdline_options_chip_init(), video_model_callback(), video_resources_chip_init(), and video_sound_init().
machine_keymap_file_list
char* machine_keymap_file_list[] extern
Referenced by keyboard_resources_shutdown(), keyboard_set_keymap_file(), keymap_resources_init(), and try_set_keymap_file().
machine_keymap_index
int machine_keymap_index extern
Referenced by keyboard_set_default_keymap_file(), keyboard_set_keyboard_mapping(), keyboard_set_keyboard_type(), keyboard_set_keymap_index(), and keymap_init().
machine_name
const char machine_name[] extern
The following stuff must be defined once per every emulated CBM machine.
Name of the machine.
The following stuff must be defined once per every emulated CBM machine.
Referenced by archdep_get_vice_machinedir(), archdep_init(), c64rom_load_basic(), c64rom_load_chargen(), c64rom_load_kernal(), create_prg_layout(), dialog_create_helper(), emulation_speed_submenu_create(), get_default_icon(), keyboard_is_keymap_valid(), keyboard_parse_keymap(), machine_get_name(), main_program(), on_tree_selection_changed(), palette_get_info_list(), romset_file_load(), settings_ethernet_widget_create(), settings_rs232_widget_create(), try_set_keymap_file(), ui_hotkeys_load_vice_default(), ui_hotkeys_vhk_filename_user(), uicmdline_dialog_show(), uicompiletimefeatures_dialog_show(), and video_load_palette().
video_disabled_mode
bool video_disabled_mode extern
Todo:
FIXME: currently never set to true
Referenced by init_cmdline_options(), init_main(), machine_specific_init(), perform_mode_change(), raster_canvas_handle_end_of_frame(), realize_canvas(), sound_error(), video_canvas_refresh(), video_canvas_refresh_all(), video_load_palette(), and video_viewport_resize().