vsid: drive/drivecpu65c02.c File Reference
drivecpu65c02.c File Reference
65C02 processor emulation of CMD FD2000/4000 and HD drives
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "6510core.h"
#include "alarm.h"
#include "debug.h"
#include "drive.h"
#include "drivecpu65c02.h"
#include "drive-check.h"
#include "drivemem.h"
#include "drivetypes.h"
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "machine-drive.h"
#include "machine.h"
#include "mem.h"
#include "monitor.h"
#include "r65c02.h"
#include "rotation.h"
#include "snapshot.h"
#include "types.h"
#include "uiapi.h"
#include "65c02core.c"
Macros
#define DRIVE_CPU
#define LOAD(a) (*drv->cpud->read_func_ptr[(a) >> 8])(drv, (uint16_t)(a))
#define LOAD_ZERO(a) (*drv->cpud->read_func_ptr[0])(drv, (uint16_t)(a))
#define LOAD_ADDR(a) (LOAD((a)) | (LOAD((a) + 1) << 8))
#define LOAD_ZERO_ADDR(a) (LOAD_ZERO((a)) | (LOAD_ZERO((a) + 1) << 8))
#define STORE(a, b) (*drv->cpud->store_func_ptr[(a) >> 8])(drv, (uint16_t)(a), (uint8_t)(b))
#define STORE_ZERO(a, b) (*drv->cpud->store_func_ptr[0])(drv, (uint16_t)(a), (uint8_t)(b))
#define JUMP(addr)
#define CPU_WDC65C02 0
#define CPU_R65C02 1
#define CPU_65SC02 2
#define reg_a (cpu->cpu_R65C02_regs.a)
#define reg_x (cpu->cpu_R65C02_regs.x)
#define reg_y (cpu->cpu_R65C02_regs.y)
#define reg_pc (cpu->cpu_R65C02_regs.pc)
#define reg_sp (cpu->cpu_R65C02_regs.sp)
#define reg_p (cpu->cpu_R65C02_regs.p)
#define flag_z (cpu->cpu_R65C02_regs.z)
#define flag_n (cpu->cpu_R65C02_regs.n)
#define ORIGIN_MEMSPACE (drv->mynumber + e_disk8_space)
#define CLK (*(drv->clk_ptr))
#define RMW_FLAG (cpu->rmw_flag)
#define PAGE_ONE (cpu->pageone)
#define LAST_OPCODE_INFO (cpu->last_opcode_info)
#define LAST_OPCODE_ADDR (cpu->last_opcode_addr)
#define TRACEFLG (debug.drivecpu_traceflg[drv->mynumber])
#define CPU_INT_STATUS (cpu->int_status)
#define ALARM_CONTEXT (cpu->alarm_context)
#define ROM_TRAP_ALLOWED() 1
#define ROM_TRAP_HANDLER() drive_trap_handler(drv)
#define CALLER (cpu->monspace)
#define DMA_FUNC drive_generic_dma()
#define DMA_ON_RESET
#define cpu_reset() (cpu_reset)(drv)
#define bank_limit (cpu->d_bank_limit)
#define bank_start (cpu->d_bank_start)
#define bank_base (cpu->d_bank_base)
#define WDC_STP()
#define WDC_WAI()
#define SNAP_MAJOR 1
#define SNAP_MINOR 3
Functions
static void drivecpu65c02_set_bank_base (void *context)
void drivecpu65c02_setup_context (struct diskunit_context_s *drv, int i)
static void cpu_reset (diskunit_context_t *drv)
void drivecpu65c02_reset_clk (diskunit_context_t *drv)
void drivecpu65c02_reset (diskunit_context_t *drv)
void drivecpu65c02_trigger_reset (unsigned int dnr)
void drivecpu65c02_shutdown (diskunit_context_t *drv)
void drivecpu65c02_init (diskunit_context_t *drv, int type)
void drivecpu65c02_wake_up (diskunit_context_t *drv)
void drivecpu65c02_sleep (diskunit_context_t *drv)
static uint32_t drive_trap_handler (diskunit_context_t *drv)
Handle a ROM trap.
static void drive_generic_dma (void)
static int interrupt_check_nmi_delay (interrupt_cpu_status_t *cs, CLOCK cpu_clk)
static int interrupt_check_irq_delay (interrupt_cpu_status_t *cs, CLOCK cpu_clk)
void drivecpu65c02_execute (diskunit_context_t *drv, CLOCK clk_value)
int drivecpu65c02_snapshot_write_module (diskunit_context_t *drv, snapshot_t *s)
int drivecpu65c02_snapshot_read_module (diskunit_context_t *drv, snapshot_t *s)
Variables
static interrupt_cpu_status_t * drivecpu_int_status_ptr [4]
Detailed Description
65C02 processor emulation of CMD FD2000/4000 and HD drives
Author
Kajtar Zsolt soci@.nosp@m.c64..nosp@m.rulez.nosp@m..org
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Macro Definition Documentation
ALARM_CONTEXT
#define ALARM_CONTEXT (cpu->alarm_context)
bank_base
#define bank_base (cpu->d_bank_base)
bank_limit
#define bank_limit (cpu->d_bank_limit)
bank_start
#define bank_start (cpu->d_bank_start)
CALLER
#define CALLER (cpu->monspace)
CLK
#define CLK (*(drv->clk_ptr))
CPU_65SC02
#define CPU_65SC02 2
CPU_INT_STATUS
#define CPU_INT_STATUS (cpu->int_status)
CPU_R65C02
#define CPU_R65C02 1
cpu_reset
#define cpu_reset (void) (cpu_reset)(drv)
CPU_WDC65C02
#define CPU_WDC65C02 0
DMA_FUNC
#define DMA_FUNC drive_generic_dma()
DMA_ON_RESET
#define DMA_ON_RESET
DRIVE_CPU
#define DRIVE_CPU
flag_n
#define flag_n (cpu->cpu_R65C02_regs.n)
flag_z
#define flag_z (cpu->cpu_R65C02_regs.z)
JUMP
#define JUMP (addr)
Value:
    do {                                                                   \
        reg_pc = (unsigned int)(addr);                                     \
        if (reg_pc >= cpu->d_bank_limit || reg_pc < cpu->d_bank_start) {   \
            uint8_t *p = drv->cpud->read_base_tab_ptr[reg_pc >> 8];           \
            cpu->d_bank_base = p;                                          \
                                                                           \
            if (p != NULL) {                                               \
                uint32_t limits = drv->cpud->read_limit_tab_ptr[reg_pc >> 8]; \
                cpu->d_bank_limit = limits & 0xffff;                       \
                cpu->d_bank_start = limits >> 16;                          \
            } else {                                                       \
                cpu->d_bank_start = 0;                                     \
                cpu->d_bank_limit = 0;                                     \
            }                                                              \
        }                                                                  \
    } while (0)
LAST_OPCODE_ADDR
#define LAST_OPCODE_ADDR (cpu->last_opcode_addr)
LAST_OPCODE_INFO
#define LAST_OPCODE_INFO (cpu->last_opcode_info)
LOAD
#define LOAD (a) (*drv->cpud->read_func_ptr[(a) >> 8])(drv, (uint16_t)(a))
LOAD_ADDR
#define LOAD_ADDR (a) (LOAD((a)) | (LOAD((a) + 1) << 8))
LOAD_ZERO
#define LOAD_ZERO (a) (*drv->cpud->read_func_ptr[0])(drv, (uint16_t)(a))
LOAD_ZERO_ADDR
#define LOAD_ZERO_ADDR (a) (LOAD_ZERO((a)) | (LOAD_ZERO((a) + 1) << 8))
ORIGIN_MEMSPACE
#define ORIGIN_MEMSPACE (drv->mynumber + e_disk8_space)
PAGE_ONE
#define PAGE_ONE (cpu->pageone)
reg_a
#define reg_a (cpu->cpu_R65C02_regs.a)
reg_p
#define reg_p (cpu->cpu_R65C02_regs.p)
reg_pc
#define reg_pc (cpu->cpu_R65C02_regs.pc)
reg_sp
#define reg_sp (cpu->cpu_R65C02_regs.sp)
reg_x
#define reg_x (cpu->cpu_R65C02_regs.x)
reg_y
#define reg_y (cpu->cpu_R65C02_regs.y)
RMW_FLAG
#define RMW_FLAG (cpu->rmw_flag)
ROM_TRAP_ALLOWED
#define ROM_TRAP_ALLOWED () 1
ROM_TRAP_HANDLER
#define ROM_TRAP_HANDLER () drive_trap_handler(drv)
SNAP_MAJOR
#define SNAP_MAJOR 1
SNAP_MINOR
#define SNAP_MINOR 3
STORE
#define STORE (a, b) (*drv->cpud->store_func_ptr[(a) >> 8])(drv, (uint16_t)(a), (uint8_t)(b))
STORE_ZERO
#define STORE_ZERO (a, b) (*drv->cpud->store_func_ptr[0])(drv, (uint16_t)(a), (uint8_t)(b))
TRACEFLG
#define TRACEFLG (debug.drivecpu_traceflg[drv->mynumber])
WDC_STP
#define WDC_STP ()
WDC_WAI
#define WDC_WAI ()
Function Documentation
cpu_reset()
static void cpu_reset (diskunit_context_t * drv) static
drive_generic_dma()
static void drive_generic_dma (void) static
drive_trap_handler()
static uint32_t drive_trap_handler (diskunit_context_t * drv) inline static
Handle a ROM trap.
drivecpu65c02_execute()
void drivecpu65c02_execute (diskunit_context_t * drv, CLOCK clk_value)
Include the R65C02 CPU emulation core.
WDC_STP() and WDC_WAI() are not used on the R65C02.
Referenced by drive_cpu_execute_one().
drivecpu65c02_init()
void drivecpu65c02_init (diskunit_context_t * drv, int type)
Todo:
check type is always already set, and remove it as parameter
Referenced by drive_init(), and drive_set_disk_drive_type().
drivecpu65c02_reset()
void drivecpu65c02_reset (diskunit_context_t * drv)
Referenced by drive_cpu_trigger_reset(), drivecpu65c02_init(), and drivecpu65c02_snapshot_read_module().
drivecpu65c02_reset_clk()
void drivecpu65c02_reset_clk (diskunit_context_t * drv)
Referenced by drivecpu65c02_reset(), and set_drive_true_emulation().
drivecpu65c02_set_bank_base()
static void drivecpu65c02_set_bank_base (void * context) static
Referenced by drivecpu65c02_setup_context().
drivecpu65c02_setup_context()
void drivecpu65c02_setup_context (struct diskunit_context_s * drv, int i)
Referenced by drive_set_disk_drive_type().
drivecpu65c02_shutdown()
void drivecpu65c02_shutdown (diskunit_context_t * drv)
Referenced by drive_shutdown().
drivecpu65c02_sleep()
void drivecpu65c02_sleep (diskunit_context_t * drv)
Referenced by drive_disable(), and drivecpu65c02_execute().
drivecpu65c02_snapshot_read_module()
int drivecpu65c02_snapshot_read_module (diskunit_context_t * drv, snapshot_t * s)
< ASCII for HD
Referenced by drive_snapshot_read_module().
drivecpu65c02_snapshot_write_module()
int drivecpu65c02_snapshot_write_module (diskunit_context_t * drv, snapshot_t * s)
< ASCII for HD
Referenced by drive_snapshot_write_module().
drivecpu65c02_trigger_reset()
void drivecpu65c02_trigger_reset (unsigned int dnr)
drivecpu65c02_wake_up()
void drivecpu65c02_wake_up (diskunit_context_t * drv)
Todo:
FIXME: this value could break some programs, or be way too high for others. Maybe we should put it into a user-definable resource.
Referenced by drive_enable(), and drivecpu65c02_execute().
interrupt_check_irq_delay()
static int interrupt_check_irq_delay (interrupt_cpu_status_t * cs, CLOCK cpu_clk) inline static
interrupt_check_nmi_delay()
static int interrupt_check_nmi_delay (interrupt_cpu_status_t * cs, CLOCK cpu_clk) inline static
Variable Documentation
drivecpu_int_status_ptr
interrupt_cpu_status_t* drivecpu_int_status_ptr[4] static
Referenced by drivecpu65c02_setup_context(), and drivecpu65c02_trigger_reset().