vsid: raster/raster-line.c File Reference
raster-line.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "raster-cache.h"
#include "raster-canvas.h"
#include "raster-changes.h"
#include "raster-line.h"
#include "raster-modes.h"
#include "raster-sprite-status.h"
#include "raster-sprite.h"
#include "raster.h"
#include "viewport.h"
Functions
unsigned int raster_line_get_real_mode (raster_t *raster)
static void add_line_to_area (raster_canvas_area_t *area, unsigned int y, unsigned int xs, unsigned int xe)
Increase ‘area’ so that it also includes [xs; xe] at line y.
void raster_line_draw_blank (raster_t *raster, unsigned int start, unsigned int end)
static void update_sprite_collisions (raster_t *raster)
static int map_current_line_to_area (raster_t *raster)
map the current line so that lines 0+ in the lower border on NTSC
static void handle_blank_line_cached (raster_t *raster)
static void handle_blank_line (raster_t *raster)
static void draw_sprites (raster_t *raster)
static void draw_sprites_partial (raster_t *raster, int xs, int xe)
void raster_line_draw_borders (raster_t *raster)
void raster_line_fill_xsmooth_region (raster_t *raster)
static int update_for_minor_changes (raster_t *raster, unsigned int *changed_start, unsigned int *changed_end)
static void fill_background (raster_t *raster)
static void handle_visible_line_with_cache (raster_t *raster)
static void handle_visible_line_without_cache (raster_t *raster)
static void handle_visible_line_with_changes (raster_t *raster)
static void handle_visible_line (raster_t *raster)
void raster_line_emulate (raster_t *raster)
Function Documentation
add_line_to_area()
static void add_line_to_area (raster_canvas_area_t * area, unsigned int y, unsigned int xs, unsigned int xe) inline static
Increase ‘area’ so that it also includes [xs; xe] at line y.
Referenced by handle_blank_line(), handle_blank_line_cached(), handle_visible_line_with_cache(), handle_visible_line_with_changes(), and handle_visible_line_without_cache().
draw_sprites()
static void draw_sprites (raster_t * raster) inline static
Referenced by handle_visible_line_with_changes(), and handle_visible_line_without_cache().
draw_sprites_partial()
static void draw_sprites_partial (raster_t * raster, int xs, int xe) inline static
Referenced by handle_visible_line_with_changes().
fill_background()
static void fill_background (raster_t * raster) inline static
Referenced by handle_visible_line_with_cache(), and handle_visible_line_without_cache().
handle_blank_line()
static void handle_blank_line (raster_t * raster) static
Referenced by raster_line_emulate().
handle_blank_line_cached()
static void handle_blank_line_cached (raster_t * raster) inline static
Referenced by handle_blank_line().
handle_visible_line()
static void handle_visible_line (raster_t * raster) inline static
Todo:
FIXME: shortcut!
Referenced by raster_line_emulate().
handle_visible_line_with_cache()
static void handle_visible_line_with_cache (raster_t * raster) static
Referenced by handle_visible_line().
handle_visible_line_with_changes()
static void handle_visible_line_with_changes (raster_t * raster) static
Referenced by handle_visible_line().
handle_visible_line_without_cache()
static void handle_visible_line_without_cache (raster_t * raster) static
Todo:
FIXME: Done differently in another place.
Referenced by handle_visible_line().
map_current_line_to_area()
static int map_current_line_to_area (raster_t * raster) inline static
map the current line so that lines 0+ in the lower border on NTSC
VIC-II are put correctly to the lower frame buffer area
Referenced by handle_blank_line(), handle_blank_line_cached(), handle_visible_line_with_cache(), handle_visible_line_with_changes(), and handle_visible_line_without_cache().
raster_line_draw_blank()
void raster_line_draw_blank (raster_t * raster, unsigned int start, unsigned int end) inline
Referenced by handle_blank_line(), handle_blank_line_cached(), handle_visible_line_with_changes(), raster_line_draw_borders(), and update_for_minor_changes_sprite().
raster_line_draw_borders()
void raster_line_draw_borders (raster_t * raster)
Referenced by handle_visible_line_with_cache(), handle_visible_line_without_cache(), update_for_minor_changes(), and update_for_minor_changes_sprite().
raster_line_emulate()
void raster_line_emulate (raster_t * raster)
Referenced by vicii_raster_draw_alarm_handler().
raster_line_fill_xsmooth_region()
void raster_line_fill_xsmooth_region (raster_t * raster)
Referenced by fill_background(), and update_for_minor_changes_sprite().
raster_line_get_real_mode()
unsigned int raster_line_get_real_mode (raster_t * raster)
Referenced by handle_visible_line_with_cache(), handle_visible_line_with_changes(), handle_visible_line_without_cache(), update_for_minor_changes(), and update_for_minor_changes_sprite().
update_for_minor_changes()
static int update_for_minor_changes (raster_t * raster, unsigned int * changed_start, unsigned int * changed_end) inline static
Referenced by handle_visible_line_with_cache().
update_sprite_collisions()
static void update_sprite_collisions (raster_t * raster) inline static
Referenced by handle_blank_line(), and raster_line_emulate().