x128: monitor_cpu_type_s Struct Reference
monitor_cpu_type_s Struct Reference
#include <monitor.h>
Data Fields
CPU_TYPE_t cpu_type
unsigned int(* asm_addr_mode_get_size)(unsigned int mode, unsigned int p0, unsigned int p1, unsigned int p2, unsigned int p3)
const struct asm_opcode_info_s *(* asm_opcode_info_get)(unsigned int p0, unsigned int p1, unsigned int p2, unsigned int p3)
int(* mon_assemble_instr)(const char *opcode_name, asm_mode_addr_info_t operand)
unsigned int(* mon_register_get_val)(int mem, int reg_id)
void(* mon_register_set_val)(int mem, int reg_id, uint16_t val)
void(* mon_register_print)(int mem)
const char *(* mon_register_print_ex)(int mem)
struct mon_reg_list_s *(* mon_register_list_get)(int mem)
Field Documentation
asm_addr_mode_get_size
unsigned int(* monitor_cpu_type_s::asm_addr_mode_get_size) (unsigned int mode, unsigned int p0, unsigned int p1, unsigned int p2, unsigned int p3)
Referenced by asm6502_init(), asm6502dtv_init(), asm65816_init(), asm6809_init(), asmR65C02_init(), asmz80_init(), mon_assemble_instr(), and mon_disassemble_to_string_internal().
asm_opcode_info_get
const struct asm_opcode_info_s *(* monitor_cpu_type_s::asm_opcode_info_get) (unsigned int p0, unsigned int p1, unsigned int p2, unsigned int p3)
Referenced by asm6502_init(), asm6502dtv_init(), asm65816_init(), asm6809_init(), asmR65C02_init(), asmz80_init(), mon_assemble_instr(), and mon_disassemble_to_string_internal().
cpu_type
CPU_TYPE_t monitor_cpu_type_s::cpu_type
Referenced by asm6502_init(), asm6502dtv_init(), asm65816_init(), asm6809_init(), asmR65C02_init(), asmz80_init(), find_monitor_cpu_type(), monitor_find_cpu_for_memspace(), and monitor_print_cpu_types_supported().
mon_assemble_instr
int(* monitor_cpu_type_s::mon_assemble_instr) (const char *opcode_name, asm_mode_addr_info_t operand)
Referenced by mon_assemble6502_init(), mon_assemble65816_init(), mon_assemble6809_init(), mon_assembleR65C02_init(), and mon_assemblez80_init().
mon_register_get_val
unsigned int(* monitor_cpu_type_s::mon_register_get_val) (int mem, int reg_id)
Referenced by mon_backtrace(), mon_breakpoint_check_checkpoint(), mon_evaluate_conditional(), mon_register6502_init(), mon_register6502dtv_init(), mon_register65816_init(), mon_register6809_init(), mon_registerR65C02_init(), and mon_registerz80_init().
mon_register_list_get
struct mon_reg_list_s *(* monitor_cpu_type_s::mon_register_list_get) (int mem)
Referenced by mon_register6502_init(), mon_register6502dtv_init(), mon_register65816_init(), mon_register6809_init(), mon_register_list_get(), mon_registerR65C02_init(), and mon_registerz80_init().
mon_register_print
void(* monitor_cpu_type_s::mon_register_print) (int mem)
Referenced by mon_register6502_init(), mon_register6502dtv_init(), mon_register65816_init(), mon_register6809_init(), mon_registerR65C02_init(), and mon_registerz80_init().
mon_register_print_ex
const char *(* monitor_cpu_type_s::mon_register_print_ex) (int mem)
Referenced by mon_disassemble_with_regdump(), mon_register6502_init(), mon_register6502dtv_init(), mon_register65816_init(), mon_register6809_init(), mon_registerR65C02_init(), and mon_registerz80_init().
mon_register_set_val
void(* monitor_cpu_type_s::mon_register_set_val) (int mem, int reg_id, uint16_t val)
Referenced by mon_jump(), mon_register6502_init(), mon_register6502dtv_init(), mon_register65816_init(), mon_register6809_init(), mon_registerR65C02_init(), mon_registerz80_init(), and monitor_binary_process_registers_set().
The documentation for this struct was generated from the following file:
monitor.h