x128: arch/gtk3/widgets/statusbarledwidget.h File Reference
statusbarledwidget.h File Reference
Small LED widgets for the status bar - header.
#include <gtk/gtk.h>
Functions
GtkWidget * statusbar_led_widget_create (const gchar *text, const gchar *on, const gchar *off)
Create LED widget for status bar.
void statusbar_led_widget_set_toggleable (GtkWidget *widget, gboolean toggleable)
Make widget toggleable, toggling state on mouse click.
gboolean statusbar_led_widget_get_toggleable (GtkWidget *widget)
Get toggleable state of widget.
void statusbar_led_widget_set_toggle_callback (GtkWidget *widget, void(*cb)(GtkWidget *, gboolean))
Set callback to trigger on state change.
gboolean statusbar_led_widget_get_active (GtkWidget *widget)
Get status bar LED widget state.
void statusbar_led_widget_set_active (GtkWidget *widget, gboolean active)
Set status bar LED widget state.
Detailed Description
Small LED widgets for the status bar - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
statusbar_led_widget_create()
GtkWidget * statusbar_led_widget_create (const gchar * text, const gchar * on, const gchar * off)
Create LED widget for status bar.
Create a small widget with a label and a two-state LED.
The colors are parsed with gdk_rgba_parse(), and if parsing fails default to #00ff00 (green) for 'on' and #ff0000 for 'off'.
Parameters
[in] text label text
[in] on color for on (use NULL for default green)
[in] off color for off (used NULL for default red)
Returns
GtkGrid
Referenced by capslock_led_create(), diagnosticpin_led_create(), mode4080_led_create(), pause_led_create(), shiftlock_led_create(), statusbar_speed_widget_create(), supercpu_jiffy_led_create(), supercpu_turbo_led_create(), and warp_led_create().
statusbar_led_widget_get_active()
gboolean statusbar_led_widget_get_active (GtkWidget * widget)
Get status bar LED widget state.
Parameters
[in] widget status bar led widget
Returns
TRUE for on, FALSE for off
Referenced by on_button_press_event().
statusbar_led_widget_get_toggleable()
gboolean statusbar_led_widget_get_toggleable (GtkWidget * widget)
Get toggleable state of widget.
Returns
LED widget is toggleable via mouse click
Referenced by on_button_press_event().
statusbar_led_widget_set_active()
void statusbar_led_widget_set_active (GtkWidget * widget, gboolean active)
Set status bar LED widget state.
Parameters
[in] widget status bar led widget
[in] active new state (TRUE = on, FALSE = off)
Referenced by capslock_led_set_active(), diagnosticpin_led_set_active(), mode4080_led_set_active(), on_button_press_event(), pause_led_set_active(), shiftlock_led_set_active(), supercpu_jiffy_led_create(), supercpu_jiffy_led_set_active(), supercpu_turbo_led_create(), supercpu_turbo_led_set_active(), and warp_led_set_active().
statusbar_led_widget_set_toggle_callback()
void statusbar_led_widget_set_toggle_callback (GtkWidget * widget, void(*)(GtkWidget *, gboolean) cb)
Set callback to trigger on state change.
Set callback function cb to be triggered on LED status change, which means through mouse clicks (enabled via statusbar_led_widget_set_toggleable()) but not through statusbar_led_widget_set_active().
Parameters
[in] widget status bar led widget
[in] cb callback function
Referenced by capslock_led_create(), diagnosticpin_led_create(), mode4080_led_create(), pause_led_create(), supercpu_jiffy_led_create(), supercpu_turbo_led_create(), and warp_led_create().
statusbar_led_widget_set_toggleable()
void statusbar_led_widget_set_toggleable (GtkWidget * widget, gboolean toggleable)
Make widget toggleable, toggling state on mouse click.
Make the widget accept mouse clicks, toggling its state.
Parameters
[in] widget status bar led widget
[in] toggleable accept mouse clicks to toggle state
Referenced by capslock_led_create(), diagnosticpin_led_create(), mode4080_led_create(), pause_led_create(), supercpu_jiffy_led_create(), supercpu_turbo_led_create(), and warp_led_create().