x128: arch/gtk3/widgets/keysetdialog.c File Reference
keysetdialog.c File Reference
Widget to set joystick keyset mappings.
#include "vice.h"
#include <gtk/gtk.h>
#include "basewidgets.h"
#include "debug_gtk3.h"
#include "log.h"
#include "resources.h"
#include "widgethelpers.h"
#include "ui.h"
#include "keysetdialog.h"
Macros
#define ROWS 6
Number of rows in the grid.
#define COLS 3
Number of columns in the grid.
Functions
static void set_button_text (GtkWidget *button, int row, int col)
Update label of button at row, col.
static gboolean set_keyset_resources (void)
Update resources with current keycodes.
static void on_response (GtkDialog *dialog, gint response_id, gpointer user_data)
Handler for the 'response' event of the dialog.
static void on_button_toggled (GtkWidget *button, gpointer data)
Handler for the "toggled" event of the keyset buttons.
static gboolean on_key_pressed (GtkWidget *widget, GdkEventKey *event, gpointer data)
Handler for the "key-press-event" event of the dialog.
static gboolean get_keyset_resources (void)
Retrieve current key codes from resources.
static GtkWidget * create_button (int row, int col)
Create a toggle button with two rows of text.
static GtkWidget * create_content_widget (void)
Create content widget for the dialog.
void keyset_dialog_show (int keyset)
Show dialog to configure keysets.
Variables
static int keyset_index = 0
Keyset index.
static guint keyset_codes [6][3]
GDK key codes for the current keyset.
static const char * keyset_labels [6][3]
Names of the directions of the keyset keys.
static GtkWidget * keyset_buttons [6][3]
Matrix of keyset buttons.
Detailed Description
Widget to set joystick keyset mappings.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
COLS
#define COLS 3
Number of columns in the grid.
ROWS
#define ROWS 6
Number of rows in the grid.
Function Documentation
create_button()
static GtkWidget * create_button (int row, int col) static
Create a toggle button with two rows of text.
Create a toggle button with to rows of text, a direction, and the key used for that direction in bold.
Parameters
[in] row row in the keys matrix
[in] col column in the keys matrix
Returns
GtkToggleButton
Referenced by create_content_widget().
create_content_widget()
static GtkWidget * create_content_widget (void) static
Create content widget for the dialog.
Returns
GtkGrid
Referenced by keyset_dialog_show().
get_keyset_resources()
static gboolean get_keyset_resources (void) static
Retrieve current key codes from resources.
Returns
bool
Referenced by keyset_dialog_show().
keyset_dialog_show()
void keyset_dialog_show (int keyset)
Show dialog to configure keysets.
Parameters
[in] keyset keyset number (1 or 2)
Referenced by on_keyset_configure_button_clicked().
on_button_toggled()
static void on_button_toggled (GtkWidget * button, gpointer data) static
Handler for the "toggled" event of the keyset buttons.
Parameters
[in,out] button gtk toggle button
[in] data extra event data (unused)
Referenced by create_button().
on_key_pressed()
static gboolean on_key_pressed (GtkWidget * widget, GdkEventKey * event, gpointer data) static
Handler for the "key-press-event" event of the dialog.
Updates a keyset key. Use Escape to unset a key.
Parameters
[in] widget dialog
[in] event key event
[in] data extra event data (unused)
Returns
bool
Referenced by keyset_dialog_show().
on_response()
static void on_response (GtkDialog * dialog, gint response_id, gpointer user_data) static
Handler for the 'response' event of the dialog.
Parameters
[in,out] dialog dialog triggering the event
[in] response_id response ID
[in] user_data extra event data (unused)
Referenced by keyset_dialog_show().
set_button_text()
static void set_button_text (GtkWidget * button, int row, int col) static
Update label of button at row, col.
Set label of button to "{direction}\n<b>{GDK key code}</b>".
Parameters
[in,out] button gtk toggle button
[in] row row in the keycodes matrix
[in] col column in the keycodes matrix
Referenced by create_button(), and on_key_pressed().
set_keyset_resources()
static gboolean set_keyset_resources (void) static
Update resources with current keycodes.
Returns
bool
Referenced by on_response().
Variable Documentation
keyset_buttons
GtkWidget* keyset_buttons[6][3] static
Matrix of keyset buttons.
There can be only one (active)
Referenced by create_content_widget(), on_button_toggled(), and on_key_pressed().
keyset_codes
guint keyset_codes[6][3] static
GDK key codes for the current keyset.
Referenced by get_keyset_resources(), on_key_pressed(), set_button_text(), and set_keyset_resources().
keyset_index
int keyset_index = 0 static
Keyset index.
Either 1 or 2
Referenced by get_keyset_resources(), keyset_dialog_show(), and set_keyset_resources().
keyset_labels
const char* keyset_labels[6][3] static
Initial value:
= {
    { "NorthWest",  "North",    "NorthEast" },
    { "West",       NULL,       "East"      },
    { "SouthWest",  "South",    "SouthEast" },
    { "Fire",       "Fire2",    "Fire3"     },
    { "Fire4",      "Fire5",    "Fire6"     },
    { "Fire7",      "Fire8",    NULL        }
}
Names of the directions of the keyset keys.
Do NOT change these, as they are used to construct resource names. Capitalization can be changed if required, since resources are not case-sensitive.
Referenced by create_content_widget(), get_keyset_resources(), on_button_toggled(), on_key_pressed(), set_button_text(), and set_keyset_resources().