x128: arch/gtk3/widgets/drivefsdevicewidget.c File Reference
drivefsdevicewidget.c File Reference
Drive file system device widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "drive.h"
#include "machine.h"
#include "mainlock.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "drivefsdevicewidget.h"
Functions
static void fsdir_browse_callback (GtkDialog *dialog, gchar *filename, gpointer entry)
Callback for the directory-select dialog.
static void on_fsdir_browse_clicked (GtkWidget *button, gpointer entry)
Handler for the 'clicked' event of the FS directory browse button.
static GtkWidget * create_fsdir_entry_widget (int unit)
Create text entry for file system directory for unit.
static GtkWidget * create_p00_widget (int unit)
Create widget to control P00-settings.
GtkWidget * drive_fsdevice_widget_create (int unit)
Create widget to control file system device settings of unit.
Detailed Description
Drive file system device widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_fsdir_entry_widget()
static GtkWidget * create_fsdir_entry_widget (int unit) static
Create text entry for file system directory for unit.
Parameters
[in] unit unit number (8-11)
Returns
GtkEntry
Referenced by drive_fsdevice_widget_create().
create_p00_widget()
static GtkWidget * create_p00_widget (int unit) static
Create widget to control P00-settings.
Parameters
[in] unit unit number (8-11)
Returns
GtkGrid
Referenced by drive_fsdevice_widget_create().
drive_fsdevice_widget_create()
GtkWidget * drive_fsdevice_widget_create (int unit)
Create widget to control file system device settings of unit.
Parameters
[in] unit unit number
Returns
GtkGrid
Referenced by create_stack_child_widget().
fsdir_browse_callback()
static void fsdir_browse_callback (GtkDialog * dialog, gchar * filename, gpointer entry) static
Callback for the directory-select dialog.
Parameters
[in] dialog directory-select dialog
[in] filename filename (NULL if canceled)
[in] entry entry box for the filename
Referenced by on_fsdir_browse_clicked().
on_fsdir_browse_clicked()
static void on_fsdir_browse_clicked (GtkWidget * button, gpointer entry) static
Handler for the 'clicked' event of the FS directory browse button.
Parameters
[in] button FS directory browse button (unused)
[in] entry FS directory text entry
Referenced by drive_fsdevice_widget_create().