vsid: arch/shared/archdep_real_path.c File Reference
archdep_real_path.c File Reference
Normalize path names.
#include "vice.h"
#include "archdep_defs.h"
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include "archdep_real_path.h"
Functions
char * archdep_real_path (const char *pathname, char *resolved_pathname)
Resolve pathname to its canonicalized absolute form.
int archdep_real_path_equal (const char *path1, const char *path2)
Compare path1 to path2 in their canonicalized forms.
Detailed Description
Normalize path names.
Author
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
Function Documentation
archdep_real_path()
char * archdep_real_path (const char * pathname, char * resolved_pathname)
Resolve pathname to its canonicalized absolute form.
Parameters
[in] pathname pathname to normalize. This file must exist.
[out] resolved_pathname buffer for result (must be at least PATH_MAX/_MAX_PATH long)
Returns
resolved_pathname on success, NULL on failure. On failure, contents of resolved_pathname are undefined.
Referenced by archdep_real_path_equal(), m3u_parse(), and vsid_main_widget_create().
archdep_real_path_equal()
int archdep_real_path_equal (const char * path1, const char * path2)
Compare path1 to path2 in their canonicalized forms.
Parameters
[in] path1 The first path to compare
[in] path2 The second path to compare
Returns
nonzero if path1 and path2 both refer to the same canonicalized path; zero otherwise. If path1 or path2 do not actually exist the results are unspecified.
Referenced by attach_disk_image(), and tape_image_attach_internal().