x128: sid/sid.h File Reference
sid.h File Reference
MOS6581 (SID) emulation, hooks to actual implementation - header.
#include <stdbool.h>
#include "types.h"
#include "sound.h"
Data Structures
struct sid_engine_s
struct sid_engine_model_s
Macros
#define SID_SETTINGS_DIALOG
#define SID_ENGINE_DEFAULT 99
#define SID_ENGINE_FASTSID_NUM_SIDS 4
Maximum number of supported SIDs for the FastSID engine.
#define SID_ENGINE_RESID_NUM_SIDS 4
Maximum number of supported SIDs for the ReSID engine.
#define SID_ENGINE_CATWEASELMKIII_NUM_SIDS 2
Maximum number of supported SIDs for the Catweasel Mk3 engine.
#define SID_ENGINE_HARDSID_NUM_SIDS 2
Maximum number of supported SIDs for the HardSID engine.
#define SID_ENGINE_PARSID_NUM_SIDS 1
Maximum number of supported SIDs for the ParSID engine.
#define SID_MODEL_DEFAULT 99
#define SID_FASTSID_6581 ((SID_ENGINE_FASTSID << 8) | SID_MODEL_6581)
#define SID_FASTSID_8580 ((SID_ENGINE_FASTSID << 8) | SID_MODEL_8580)
#define SID_RESID_6581 ((SID_ENGINE_RESID << 8) | SID_MODEL_6581)
#define SID_RESID_8580 ((SID_ENGINE_RESID << 8) | SID_MODEL_8580)
#define SID_RESID_8580D ((SID_ENGINE_RESID << 8) | SID_MODEL_8580D)
#define SID_RESID_DTVSID ((SID_ENGINE_RESID << 8) | SID_MODEL_DTVSID)
#define SID_CATWEASELMKIII (SID_ENGINE_CATWEASELMKIII << 8)
#define SID_HARDSID (SID_ENGINE_HARDSID << 8)
#define SID_PARSID (SID_ENGINE_PARSID << 8)
#define SIDTYPE_SID 0
#define SIDTYPE_SIDDTV 1
#define SIDTYPE_SIDCART 2
#define SID_MACHINE_MAX_SID_C64 8
#define SID_MACHINE_MAX_SID_C64DTV 1
#define SID_MACHINE_MAX_SID_C128 8
#define SID_MACHINE_MAX_SID_VIC20 1
The VIC20 has an optional SID cartridge.
#define SID_MACHINE_MAX_SID_PLUS4 1
The Plus4 has an optional SIDCard expansion.
#define SID_MACHINE_MAX_SID_CBM5x0 1
#define SID_MACHINE_MAX_SID_CBM6x0 0
#define SID_MACHINE_MAX_SID_PET 1
The PET has an optional SID Card expansion.
#define SID_MACHINE_MAX_SID_VSID 3
VSID supports up to three SIDS.
#define RESID_6581_PASSBAND_MIN 0
#define RESID_6581_PASSBAND_MAX 90
#define RESID_6581_PASSBAND_ONE 1
#define RESID_6581_PASSBAND_DEFAULT 90
#define RESID_6581_FILTER_GAIN_MIN 90
#define RESID_6581_FILTER_GAIN_MAX 100
#define RESID_6581_FILTER_GAIN_ONE 1
#define RESID_6581_FILTER_GAIN_DEFAULT 97
#define RESID_6581_FILTER_BIAS_MIN -5000
#define RESID_6581_FILTER_BIAS_MAX 5000
#define RESID_6581_FILTER_BIAS_ONE 1000
#define RESID_6581_FILTER_BIAS_DEFAULT 500
#define RESID_8580_PASSBAND_MIN 0
#define RESID_8580_PASSBAND_MAX 90
#define RESID_8580_PASSBAND_ONE 1
#define RESID_8580_PASSBAND_DEFAULT 90
#define RESID_8580_FILTER_GAIN_MIN 90
#define RESID_8580_FILTER_GAIN_MAX 100
#define RESID_8580_FILTER_GAIN_ONE 1
#define RESID_8580_FILTER_GAIN_DEFAULT 97
#define RESID_8580_FILTER_BIAS_MIN -5000
#define RESID_8580_FILTER_BIAS_MAX 5000
#define RESID_8580_FILTER_BIAS_ONE 1000
#define RESID_8580_FILTER_BIAS_DEFAULT 0
Typedefs
typedef struct sid_engine_s sid_engine_t
typedef struct sid_engine_model_s sid_engine_model_t
Enumerations
enum {
SID_ENGINE_FASTSID = 0 ,
SID_ENGINE_RESID ,
SID_ENGINE_CATWEASELMKIII ,
SID_ENGINE_HARDSID ,
SID_ENGINE_PARSID
}
enum {
SID_RESID_SAMPLING_FAST = 0 ,
SID_RESID_SAMPLING_INTERPOLATION ,
SID_RESID_SAMPLING_RESAMPLING ,
SID_RESID_SAMPLING_FAST_RESAMPLING
}
enum {
SID_MODEL_6581 = 0 ,
SID_MODEL_8580 ,
SID_MODEL_8580D ,
SID_MODEL_DTVSID
}
Functions
void machine_sid2_enable (int val)
uint8_t sid_read (uint16_t address)
uint8_t sid2_read (uint16_t address)
uint8_t sid3_read (uint16_t address)
uint8_t sid4_read (uint16_t address)
uint8_t sid5_read (uint16_t address)
uint8_t sid6_read (uint16_t address)
uint8_t sid7_read (uint16_t address)
uint8_t sid8_read (uint16_t address)
uint8_t sid_peek (uint16_t address)
uint8_t sid2_peek (uint16_t address)
uint8_t sid3_peek (uint16_t address)
uint8_t sid4_peek (uint16_t address)
uint8_t sid5_peek (uint16_t address)
uint8_t sid6_peek (uint16_t address)
uint8_t sid7_peek (uint16_t address)
uint8_t sid8_peek (uint16_t address)
void sid_store (uint16_t address, uint8_t byte)
void sid2_store (uint16_t address, uint8_t byte)
void sid3_store (uint16_t address, uint8_t byte)
void sid4_store (uint16_t address, uint8_t byte)
void sid5_store (uint16_t address, uint8_t byte)
void sid6_store (uint16_t address, uint8_t byte)
void sid7_store (uint16_t address, uint8_t byte)
void sid8_store (uint16_t address, uint8_t byte)
int sid_dump (void)
int sid2_dump (void)
int sid3_dump (void)
int sid4_dump (void)
int sid5_dump (void)
int sid6_dump (void)
int sid7_dump (void)
int sid8_dump (void)
void sid_reset (void)
void sid_set_machine_parameter (long clock_rate)
uint8_t * sid_get_siddata (unsigned int channel)
int sid_engine_set (int engine)
void sid_state_read (unsigned int channel, struct sid_snapshot_state_s *sid_state)
void sid_state_write (unsigned int channel, struct sid_snapshot_state_s *sid_state)
bool sid_sound_machine_set_engine_hooks (void)
sound_t * sid_sound_machine_open (int chipno)
int sid_sound_machine_init_vbr (sound_t *psid, int speed, int cycles_per_sec, int factor)
int sid_sound_machine_init (sound_t *psid, int speed, int cycles_per_sec)
void sid_sound_machine_close (sound_t *psid)
uint8_t sid_sound_machine_read (sound_t *psid, uint16_t addr)
void sid_sound_machine_store (sound_t *psid, uint16_t addr, uint8_t byte)
void sid_sound_machine_reset (sound_t *psid, CLOCK cpu_clk)
char * sid_sound_machine_dump_state (sound_t *psid)
int sid_sound_machine_cycle_based (void)
int sid_sound_machine_channels (void)
void sid_sound_machine_enable (int enable)
sid_engine_model_t ** sid_get_engine_model_list (void)
int sid_set_engine_model (int engine, int model)
void sid_sound_chip_init (void)
int sid_sound_machine_calculate_samples (sound_t **psid, int16_t *pbuf, int nr, int sound_output_channels, int sound_chip_channels, CLOCK *delta_t)
void sid_set_enable (int value)
int sid_engine_get_max_sids (int engine)
Get maximum number of support SIDs for engine.
int sid_machine_get_max_sids (void)
Get maximum number of SIDs for the current machine, using actual HW.
int sid_machine_engine_get_max_sids (int engine)
Determine maximum number of SIDs for current machine and a \engine.
int sid_machine_can_have_multiple_sids (void)
Determine if the current machine can support multiple SIDs.
Detailed Description
MOS6581 (SID) emulation, hooks to actual implementation - header.
Author
Dag Lem resid.nosp@m.@nim.nosp@m.rod.n.nosp@m.o
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Macro Definition Documentation
RESID_6581_FILTER_BIAS_DEFAULT
#define RESID_6581_FILTER_BIAS_DEFAULT 500
RESID_6581_FILTER_BIAS_MAX
#define RESID_6581_FILTER_BIAS_MAX 5000
RESID_6581_FILTER_BIAS_MIN
#define RESID_6581_FILTER_BIAS_MIN -5000
RESID_6581_FILTER_BIAS_ONE
#define RESID_6581_FILTER_BIAS_ONE 1000
RESID_6581_FILTER_GAIN_DEFAULT
#define RESID_6581_FILTER_GAIN_DEFAULT 97
RESID_6581_FILTER_GAIN_MAX
#define RESID_6581_FILTER_GAIN_MAX 100
RESID_6581_FILTER_GAIN_MIN
#define RESID_6581_FILTER_GAIN_MIN 90
RESID_6581_FILTER_GAIN_ONE
#define RESID_6581_FILTER_GAIN_ONE 1
RESID_6581_PASSBAND_DEFAULT
#define RESID_6581_PASSBAND_DEFAULT 90
RESID_6581_PASSBAND_MAX
#define RESID_6581_PASSBAND_MAX 90
RESID_6581_PASSBAND_MIN
#define RESID_6581_PASSBAND_MIN 0
RESID_6581_PASSBAND_ONE
#define RESID_6581_PASSBAND_ONE 1
RESID_8580_FILTER_BIAS_DEFAULT
#define RESID_8580_FILTER_BIAS_DEFAULT 0
RESID_8580_FILTER_BIAS_MAX
#define RESID_8580_FILTER_BIAS_MAX 5000
RESID_8580_FILTER_BIAS_MIN
#define RESID_8580_FILTER_BIAS_MIN -5000
RESID_8580_FILTER_BIAS_ONE
#define RESID_8580_FILTER_BIAS_ONE 1000
RESID_8580_FILTER_GAIN_DEFAULT
#define RESID_8580_FILTER_GAIN_DEFAULT 97
RESID_8580_FILTER_GAIN_MAX
#define RESID_8580_FILTER_GAIN_MAX 100
RESID_8580_FILTER_GAIN_MIN
#define RESID_8580_FILTER_GAIN_MIN 90
RESID_8580_FILTER_GAIN_ONE
#define RESID_8580_FILTER_GAIN_ONE 1
RESID_8580_PASSBAND_DEFAULT
#define RESID_8580_PASSBAND_DEFAULT 90
RESID_8580_PASSBAND_MAX
#define RESID_8580_PASSBAND_MAX 90
RESID_8580_PASSBAND_MIN
#define RESID_8580_PASSBAND_MIN 0
RESID_8580_PASSBAND_ONE
#define RESID_8580_PASSBAND_ONE 1
SID_CATWEASELMKIII
#define SID_CATWEASELMKIII (SID_ENGINE_CATWEASELMKIII << 8)
SID_ENGINE_CATWEASELMKIII_NUM_SIDS
#define SID_ENGINE_CATWEASELMKIII_NUM_SIDS 2
Maximum number of supported SIDs for the Catweasel Mk3 engine.
SID_ENGINE_DEFAULT
#define SID_ENGINE_DEFAULT 99
SID_ENGINE_FASTSID_NUM_SIDS
#define SID_ENGINE_FASTSID_NUM_SIDS 4
Maximum number of supported SIDs for the FastSID engine.
SID_ENGINE_HARDSID_NUM_SIDS
#define SID_ENGINE_HARDSID_NUM_SIDS 2
Maximum number of supported SIDs for the HardSID engine.
SID_ENGINE_PARSID_NUM_SIDS
#define SID_ENGINE_PARSID_NUM_SIDS 1
Maximum number of supported SIDs for the ParSID engine.
SID_ENGINE_RESID_NUM_SIDS
#define SID_ENGINE_RESID_NUM_SIDS 4
Maximum number of supported SIDs for the ReSID engine.
SID_FASTSID_6581
#define SID_FASTSID_6581 ((SID_ENGINE_FASTSID << 8) | SID_MODEL_6581)
SID_FASTSID_8580
#define SID_FASTSID_8580 ((SID_ENGINE_FASTSID << 8) | SID_MODEL_8580)
SID_HARDSID
#define SID_HARDSID (SID_ENGINE_HARDSID << 8)
SID_MACHINE_MAX_SID_C128
#define SID_MACHINE_MAX_SID_C128 8
SID_MACHINE_MAX_SID_C64
#define SID_MACHINE_MAX_SID_C64 8
SID_MACHINE_MAX_SID_C64DTV
#define SID_MACHINE_MAX_SID_C64DTV 1
SID_MACHINE_MAX_SID_CBM5x0
#define SID_MACHINE_MAX_SID_CBM5x0 1
SID_MACHINE_MAX_SID_CBM6x0
#define SID_MACHINE_MAX_SID_CBM6x0 0
SID_MACHINE_MAX_SID_PET
#define SID_MACHINE_MAX_SID_PET 1
The PET has an optional SID Card expansion.
SID_MACHINE_MAX_SID_PLUS4
#define SID_MACHINE_MAX_SID_PLUS4 1
The Plus4 has an optional SIDCard expansion.
SID_MACHINE_MAX_SID_VIC20
#define SID_MACHINE_MAX_SID_VIC20 1
The VIC20 has an optional SID cartridge.
SID_MACHINE_MAX_SID_VSID
#define SID_MACHINE_MAX_SID_VSID 3
VSID supports up to three SIDS.
This can be the same as C64 in emulation, but PSID currently only manages 3 SIDs.
SID_MODEL_DEFAULT
#define SID_MODEL_DEFAULT 99
SID_PARSID
#define SID_PARSID (SID_ENGINE_PARSID << 8)
SID_RESID_6581
#define SID_RESID_6581 ((SID_ENGINE_RESID << 8) | SID_MODEL_6581)
SID_RESID_8580
#define SID_RESID_8580 ((SID_ENGINE_RESID << 8) | SID_MODEL_8580)
SID_RESID_8580D
#define SID_RESID_8580D ((SID_ENGINE_RESID << 8) | SID_MODEL_8580D)
SID_RESID_DTVSID
#define SID_RESID_DTVSID ((SID_ENGINE_RESID << 8) | SID_MODEL_DTVSID)
SID_SETTINGS_DIALOG
#define SID_SETTINGS_DIALOG
SIDTYPE_SID
#define SIDTYPE_SID 0
SIDTYPE_SIDCART
#define SIDTYPE_SIDCART 2
SIDTYPE_SIDDTV
#define SIDTYPE_SIDDTV 1
Typedef Documentation
sid_engine_model_t
typedef struct sid_engine_model_s sid_engine_model_t
sid_engine_t
typedef struct sid_engine_s sid_engine_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SID_ENGINE_FASTSID
SID_ENGINE_RESID
SID_ENGINE_CATWEASELMKIII
SID_ENGINE_HARDSID
SID_ENGINE_PARSID
anonymous enum
anonymous enum
Enumerator
SID_RESID_SAMPLING_FAST
SID_RESID_SAMPLING_INTERPOLATION
SID_RESID_SAMPLING_RESAMPLING
SID_RESID_SAMPLING_FAST_RESAMPLING
anonymous enum
anonymous enum
Enumerator
SID_MODEL_6581
SID_MODEL_8580
SID_MODEL_8580D
SID_MODEL_DTVSID
Function Documentation
machine_sid2_enable()
void machine_sid2_enable (int val)
Referenced by set_sid_stereo().
sid2_dump()
int sid2_dump (void)
sid2_peek()
uint8_t sid2_peek (uint16_t address)
sid2_read()
uint8_t sid2_read (uint16_t address)
Referenced by d7xx_read().
sid2_store()
void sid2_store (uint16_t address, uint8_t byte)
Referenced by d7xx_store(), and sid_snapshot_read_module_extended().
sid3_dump()
int sid3_dump (void)
sid3_peek()
uint8_t sid3_peek (uint16_t address)
sid3_read()
uint8_t sid3_read (uint16_t address)
Referenced by d7xx_read().
sid3_store()
void sid3_store (uint16_t address, uint8_t byte)
Referenced by d7xx_store(), and sid_snapshot_read_module_extended().
sid4_dump()
int sid4_dump (void)
sid4_peek()
uint8_t sid4_peek (uint16_t address)
sid4_read()
uint8_t sid4_read (uint16_t address)
Referenced by d7xx_read().
sid4_store()
void sid4_store (uint16_t address, uint8_t byte)
Referenced by d7xx_store(), and sid_snapshot_read_module_extended().
sid5_dump()
int sid5_dump (void)
sid5_peek()
uint8_t sid5_peek (uint16_t address)
sid5_read()
uint8_t sid5_read (uint16_t address)
Referenced by d7xx_read().
sid5_store()
void sid5_store (uint16_t address, uint8_t byte)
Referenced by d7xx_store(), and sid_snapshot_read_module_extended().
sid6_dump()
int sid6_dump (void)
sid6_peek()
uint8_t sid6_peek (uint16_t address)
sid6_read()
uint8_t sid6_read (uint16_t address)
Referenced by d7xx_read().
sid6_store()
void sid6_store (uint16_t address, uint8_t byte)
Referenced by d7xx_store(), and sid_snapshot_read_module_extended().
sid7_dump()
int sid7_dump (void)
sid7_peek()
uint8_t sid7_peek (uint16_t address)
sid7_read()
uint8_t sid7_read (uint16_t address)
Referenced by d7xx_read().
sid7_store()
void sid7_store (uint16_t address, uint8_t byte)
Referenced by d7xx_store(), and sid_snapshot_read_module_extended().
sid8_dump()
int sid8_dump (void)
sid8_peek()
uint8_t sid8_peek (uint16_t address)
sid8_read()
uint8_t sid8_read (uint16_t address)
Referenced by d7xx_read().
sid8_store()
void sid8_store (uint16_t address, uint8_t byte)
Referenced by d7xx_store(), and sid_snapshot_read_module_extended().
sid_dump()
int sid_dump (void)
sid_engine_get_max_sids()
int sid_engine_get_max_sids (int engine)
Get maximum number of support SIDs for engine.
Helper function for UIs: determine number of supported SIDs to allow UIs to not display impossible settings.
Parameters
[in] engine engine ID
See also
sid.h for engine IDs
Referenced by sid_machine_engine_get_max_sids().
sid_engine_set()
int sid_engine_set (int engine)
Referenced by set_sid_engine().
sid_get_engine_model_list()
sid_engine_model_t ** sid_get_engine_model_list (void)
Referenced by sid_engine_model_widget_create().
sid_get_siddata()
uint8_t * sid_get_siddata (unsigned int channel)
Referenced by sid_snapshot_read_module_extended(), sid_snapshot_read_module_simple(), and sid_snapshot_write_module_simple().
sid_machine_can_have_multiple_sids()
int sid_machine_can_have_multiple_sids (void)
Determine if the current machine can support multiple SIDs.
This ignores any expansions and the SID engine, just gives the theoretical maximum that can be done with the current HW available.
Returns
boolean
Referenced by sid_sound_widget_create(), and update_sid_addresses_sensitivity().
sid_machine_engine_get_max_sids()
int sid_machine_engine_get_max_sids (int engine)
Determine maximum number of SIDs for current machine and a \engine.
Only assumes actually available HW expansion and actual old HW, so no Ultimate64 etc.
Parameters
[in] engine SID engine
Returns
maximum number of SIDs
sid_machine_get_max_sids()
int sid_machine_get_max_sids (void)
Get maximum number of SIDs for the current machine, using actual HW.
Returns
number of SIDs
Referenced by create_sid_address_widgets(), sid_machine_can_have_multiple_sids(), and sid_machine_engine_get_max_sids().
sid_peek()
uint8_t sid_peek (uint16_t address)
sid_read()
uint8_t sid_read (uint16_t address)
sid_reset()
void sid_reset (void)
Todo:
FIXME: we should really use an alarm to update the POT values every 512 cycles. unfortunately the current mouse code will not work with this approach
Referenced by machine_specific_reset().
sid_set_enable()
void sid_set_enable (int value)
sid_set_engine_model()
int sid_set_engine_model (int engine, int model)
Referenced by c128model_set(), on_radio_toggled(), and sid_common_set_engine_model().
sid_set_machine_parameter()
void sid_set_machine_parameter (long clock_rate)
Referenced by machine_change_timing().
sid_sound_chip_init()
void sid_sound_chip_init (void)
Referenced by machine_specific_init().
sid_sound_machine_calculate_samples()
int sid_sound_machine_calculate_samples (sound_t ** psid, int16_t * pbuf, int nr, int sound_output_channels, int sound_chip_channels, CLOCK * delta_t)
sid_sound_machine_channels()
int sid_sound_machine_channels (void)
sid_sound_machine_close()
void sid_sound_machine_close (sound_t * psid)
sid_sound_machine_cycle_based()
int sid_sound_machine_cycle_based (void)
sid_sound_machine_dump_state()
char * sid_sound_machine_dump_state (sound_t * psid)
sid_sound_machine_enable()
void sid_sound_machine_enable (int enable)
sid_sound_machine_init()
int sid_sound_machine_init (sound_t * psid, int speed, int cycles_per_sec)
sid_sound_machine_init_vbr()
int sid_sound_machine_init_vbr (sound_t * psid, int speed, int cycles_per_sec, int factor)
sid_sound_machine_open()
sound_t * sid_sound_machine_open (int chipno)
sid_sound_machine_read()
uint8_t sid_sound_machine_read (sound_t * psid, uint16_t addr)
sid_sound_machine_reset()
void sid_sound_machine_reset (sound_t * psid, CLOCK cpu_clk)
sid_sound_machine_set_engine_hooks()
bool sid_sound_machine_set_engine_hooks (void)
Referenced by sid_snapshot_write_module(), and sid_sound_machine_open().
sid_sound_machine_store()
void sid_sound_machine_store (sound_t * psid, uint16_t addr, uint8_t byte)
sid_state_read()
void sid_state_read (unsigned int channel, struct sid_snapshot_state_s * sid_state)
sid_state_write()
void sid_state_write (unsigned int channel, struct sid_snapshot_state_s * sid_state)
sid_store()
void sid_store (uint16_t address, uint8_t byte)
Referenced by sid_snapshot_read_module_extended().