vsid: c64/c64cia1.c File Reference
c64cia1.c File Reference
#include "vice.h"
#include <stdio.h>
#include "c64fastiec.h"
#include "c64-resources.h"
#include "c64.h"
#include "c64cia.h"
#include "c64iec.h"
#include "c64keyboard.h"
#include "cia.h"
#include "interrupt.h"
#include "drive.h"
#include "joyport.h"
#include "joystick.h"
#include "keyboard.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "types.h"
#include "userport.h"
#include "vicii.h"
Macros
#define DBG(x)
#define DBGA(x)
#define DBGB(x)
Functions
void cia1_store (uint16_t addr, uint8_t data)
uint8_t cia1_read (uint16_t addr)
uint8_t cia1_peek (uint16_t addr)
void cia1_update_model (void)
static void cia_set_int_clk (cia_context_t *cia_context, int value, CLOCK clk)
static void cia_restore_int (cia_context_t *cia_context, int value)
void cia1_set_extended_keyboard_rows_mask (uint8_t value)
static void pulse_ciapc (cia_context_t *cia_context, CLOCK rclk)
static void pre_store (void)
static void pre_read (void)
static void pre_peek (void)
static void do_reset_cia (cia_context_t *cia_context)
static void cia1_internal_lightpen_check (uint8_t pa, uint8_t pb)
void cia1_check_lightpen (void)
static void store_ciapa (cia_context_t *cia_context, CLOCK rclk, uint8_t b)
static void undump_ciapa (cia_context_t *cia_context, CLOCK rclk, uint8_t b)
static void store_ciapb (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static void undump_ciapb (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static void matrix_activate_column (int column, uint8_t *activerows, uint8_t *activecolumns)
static void matrix_activate_row (int row, uint8_t *activerows, uint8_t *activecolumns)
static uint8_t matrix_get_active_rows_by_column (int column)
get all connected rows for one active column
static uint8_t matrix_get_active_rows_by_row (int row)
get all connected rows for one active row
static uint8_t matrix_get_active_columns_by_column (int column)
get all connected columns for one active row
static uint8_t matrix_get_active_columns_by_row (int row)
get all connected columns for one active row
static uint8_t read_ciapa (cia_context_t *cia_context)
static int ciapb_forcelow (int row, uint8_t mask)
static uint8_t read_ciapb (cia_context_t *cia_context)
static void read_ciaicr (cia_context_t *cia_context)
static void read_sdr (cia_context_t *cia_context)
static void store_sdr (cia_context_t *cia_context, uint8_t byte)
void cia1_init (cia_context_t *cia_context)
void cia1_setup_context (machine_context_t *machinecontext)
void cia1_set_timing (cia_context_t *cia_context, int tickspersec, int powerfreq)
Variables
static uint8_t cia1_cra = 0
Macro Definition Documentation
DBG
#define DBG (x)
DBGA
#define DBGA (x)
DBGB
#define DBGB (x)
Function Documentation
cia1_check_lightpen()
void cia1_check_lightpen (void)
cia1_init()
void cia1_init (cia_context_t * cia_context)
cia1_internal_lightpen_check()
static void cia1_internal_lightpen_check (uint8_t pa, uint8_t pb) static
Referenced by cia1_check_lightpen(), store_ciapa(), and store_ciapb().
cia1_peek()
uint8_t cia1_peek (uint16_t addr)
cia1_read()
uint8_t cia1_read (uint16_t addr)
cia1_set_extended_keyboard_rows_mask()
void cia1_set_extended_keyboard_rows_mask (uint8_t value)
cia1_set_timing()
void cia1_set_timing (cia_context_t * cia_context, int tickspersec, int powerfreq)
Referenced by cia1_setup_context().
cia1_setup_context()
void cia1_setup_context (machine_context_t * machinecontext)
cia1_store()
void cia1_store (uint16_t addr, uint8_t data)
< Control register A
cia1_update_model()
void cia1_update_model (void)
cia_restore_int()
static void cia_restore_int (cia_context_t * cia_context, int value) static
Referenced by cia1_setup_context().
cia_set_int_clk()
static void cia_set_int_clk (cia_context_t * cia_context, int value, CLOCK clk) static
Referenced by cia1_setup_context().
ciapb_forcelow()
static int ciapb_forcelow (int row, uint8_t mask) inline static
Todo:
check joysticks?
Referenced by read_ciapb().
do_reset_cia()
static void do_reset_cia (cia_context_t * cia_context) static
Referenced by cia1_setup_context().
matrix_activate_column()
static void matrix_activate_column (int column, uint8_t * activerows, uint8_t * activecolumns) static
Referenced by matrix_activate_row(), matrix_get_active_columns_by_column(), and matrix_get_active_rows_by_column().
matrix_activate_row()
static void matrix_activate_row (int row, uint8_t * activerows, uint8_t * activecolumns) static
Referenced by matrix_activate_column(), matrix_get_active_columns_by_row(), and matrix_get_active_rows_by_row().
matrix_get_active_columns_by_column()
static uint8_t matrix_get_active_columns_by_column (int column) inline static
get all connected columns for one active row
Referenced by read_ciapa().
matrix_get_active_columns_by_row()
static uint8_t matrix_get_active_columns_by_row (int row) inline static
get all connected columns for one active row
Referenced by read_ciapb().
matrix_get_active_rows_by_column()
static uint8_t matrix_get_active_rows_by_column (int column) inline static
get all connected rows for one active column
matrix_get_active_rows_by_row()
static uint8_t matrix_get_active_rows_by_row (int row) inline static
get all connected rows for one active row
Referenced by ciapb_forcelow().
pre_peek()
static void pre_peek (void) static
Referenced by cia1_setup_context().
pre_read()
static void pre_read (void) static
Referenced by cia1_setup_context().
pre_store()
static void pre_store (void) static
Referenced by cia1_setup_context().
pulse_ciapc()
static void pulse_ciapc (cia_context_t * cia_context, CLOCK rclk) static
Referenced by cia1_setup_context().
read_ciaicr()
static void read_ciaicr (cia_context_t * cia_context) static
Referenced by cia1_setup_context().
read_ciapa()
static uint8_t read_ciapa (cia_context_t * cia_context) static
< Port B
< Data direction register for port B
< Port A
< Data direction register for port A
Referenced by cia1_setup_context().
read_ciapb()
static uint8_t read_ciapb (cia_context_t * cia_context) static
< Data direction register for port B
< Port B
< Data direction register for port A
< Port A
< Data direction register for port B
< Port B
< Data direction register for port A
< Port A
< Port B
< Data direction register for port B
Referenced by cia1_setup_context().
read_sdr()
static void read_sdr (cia_context_t * cia_context) static
< Serial port shift register
< Serial port shift register
Referenced by cia1_setup_context().
store_ciapa()
static void store_ciapa (cia_context_t * cia_context, CLOCK rclk, uint8_t b) static
Referenced by cia1_setup_context().
store_ciapb()
static void store_ciapb (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
Referenced by cia1_setup_context().
store_sdr()
static void store_sdr (cia_context_t * cia_context, uint8_t byte) static
Referenced by cia1_setup_context().
undump_ciapa()
static void undump_ciapa (cia_context_t * cia_context, CLOCK rclk, uint8_t b) static
Referenced by cia1_setup_context().
undump_ciapb()
static void undump_ciapb (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
Referenced by cia1_setup_context().
Variable Documentation
cia1_cra
uint8_t cia1_cra = 0 static
Referenced by cia1_store(), and store_sdr().