vsid: palette.c File Reference
palette.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "palette.h"
#include "resources.h"
#include "sysfile.h"
#include "types.h"
#include "util.h"
Macros
#define DBG(x)
#define MAX_PALETTE_FILES 60
#define MAX_TAG_LEN 63
Functions
palette_t * palette_create (unsigned int num_entries, const char *entry_names[])
void palette_free (palette_t *p)
static int palette_set_entry (palette_t *p, unsigned int number, uint8_t red, uint8_t green, uint8_t blue)
static int palette_copy (palette_t *dest, const palette_t *src)
static const char * next_nonspace (const char *p)
static int palette_load_core (FILE *f, const char *file_name, palette_t *tmp_palette, palette_t *palette_return)
int palette_load (const char *file_name, const char *subpath, palette_t *palette_return)
int palette_save (const char *file_name, const palette_t *palette)
static int palette_read_tag (FILE *f, char *tag, char *outbuf, int len)
static int palette_read_info (const char *pathname, const char *filename, palette_info_t *list)
static char * sysfile_get_system_path_start (void)
kindof like "opendir" but returns all search pathes one by one
static char * sysfile_get_system_path_next (char *syspath)
kindof like "readdir" but returns all search pathes one by one
static int palette_find_name (const char *name)
check if a palette associated with this "file" exists, return number of times
static void palette_list_free (palette_info_t *list)
free all memory associated with pointers in the palette info struct/list
const palette_info_t * palette_get_info_list (void)
returns pointer to palette_info_t entries.
void palette_init (void)
void palette_shutdown (void)
Variables
static log_t palette_log = ((log_t)-1)
static palette_info_t palettelist [60+2]
static char * sysfile_system_path_ptr
Macro Definition Documentation
DBG
#define DBG (x)
MAX_PALETTE_FILES
#define MAX_PALETTE_FILES 60
Todo:
FIXME: we might want to use a dynamically allocated list instead. meh
MAX_TAG_LEN
#define MAX_TAG_LEN 63
Function Documentation
next_nonspace()
static const char * next_nonspace (const char * p) static
Referenced by palette_load_core().
palette_copy()
static int palette_copy (palette_t * dest, const palette_t * src) static
Referenced by palette_load_core().
palette_create()
palette_t * palette_create (unsigned int num_entries, const char * entry_names[])
Referenced by drv_1520_init(), drv_mps803_init(), drv_nl10_init(), palette_load(), video_calc_palette(), and video_load_palette().
palette_find_name()
static int palette_find_name (const char * name) static
check if a palette associated with this "file" exists, return number of times
Referenced by palette_get_info_list().
palette_free()
void palette_free (palette_t * p)
Referenced by drv_1520_shutdown(), drv_mps803_shutdown(), drv_nl10_shutdown(), palette_load(), video_color_palette_free(), video_color_update_palette(), and video_load_palette().
palette_get_info_list()
const palette_info_t * palette_get_info_list (void)
returns pointer to palette_info_t entries.
may return an empty list.
Todo:
FIXME: limit the list here. we may really want a dynamically allocated list here, but its not worth the trouble right now :=P
Todo:
sort list by name(s)
Referenced by create_combo_box().
palette_init()
void palette_init (void)
Referenced by init_main().
palette_list_free()
static void palette_list_free (palette_info_t * list) static
free all memory associated with pointers in the palette info struct/list
Referenced by palette_get_info_list(), and palette_shutdown().
palette_load()
int palette_load (const char * file_name, const char * subpath, palette_t * palette_return)
< read mode (text)
< read mode (text)
Referenced by drv_1520_init(), drv_mps803_init(), drv_nl10_init(), and video_load_palette().
palette_load_core()
static int palette_load_core (FILE * f, const char * file_name, palette_t * tmp_palette, palette_t * palette_return) static
Referenced by palette_load().
palette_read_info()
static int palette_read_info (const char * pathname, const char * filename, palette_info_t * list) static
Referenced by palette_get_info_list().
palette_read_tag()
static int palette_read_tag (FILE * f, char * tag, char * outbuf, int len) static
Referenced by palette_read_info().
palette_save()
int palette_save (const char * file_name, const palette_t * palette)
Todo:
FIXME: output NAME and TYPE tags!
< write mode (binary)
palette_set_entry()
static int palette_set_entry (palette_t * p, unsigned int number, uint8_t red, uint8_t green, uint8_t blue) static
Referenced by palette_copy(), and palette_load_core().
palette_shutdown()
void palette_shutdown (void)
Referenced by machine_shutdown().
sysfile_get_system_path_next()
static char * sysfile_get_system_path_next (char * syspath) static
kindof like "readdir" but returns all search pathes one by one
Referenced by palette_get_info_list().
sysfile_get_system_path_start()
static char * sysfile_get_system_path_start (void) static
kindof like "opendir" but returns all search pathes one by one
Referenced by palette_get_info_list().
Variable Documentation
palette_log
log_t palette_log = ((log_t)-1) static
Referenced by palette_copy(), palette_get_info_list(), palette_init(), palette_load(), and palette_load_core().
palettelist
palette_info_t palettelist[60+2] static
Referenced by palette_find_name(), palette_get_info_list(), palette_list_free(), and palette_shutdown().
sysfile_system_path_ptr
char* sysfile_system_path_ptr static
Todo:
FIXME: we might want to make the following two functions more generic and not use this global state variable, and then move it to sysfile.c
Referenced by sysfile_get_system_path_next(), and sysfile_get_system_path_start().