x128: arch/gtk3/widgets/settings_hotkeys.c File Reference
settings_hotkeys.c File Reference
Hotkeys settings.
#include "vice.h"
#include <gtk/gtk.h>
#include <time.h>
#include <string.h>
#include "vice_gtk3.h"
#include "archdep.h"
#include "hotkeys.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "ui.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uihotkeysload.h"
#include "uihotkeys.h"
#include "uimenu.h"
#include "uitypes.h"
#include "util.h"
#include "settings_hotkeys.h"
Data Structures
struct mod_mask_s
Macros
#define ARRAY_LEN(arr) (sizeof arr / sizeof arr[0])
Typedefs
typedef struct mod_mask_s mod_mask_t
Enumerations
enum {
COL_ACTION_ID ,
COL_ACTION_NAME ,
COL_ACTION_DESC ,
COL_HOTKEY
}
Columns for the hotkeys table.
enum { RESPONSE_CLEAR }
Set/Unset hotkey dialog custom response IDs.
Functions
static GtkWidget * label_helper (const char *text)
Create left-aligned label using Pango markup.
static void clear_all_hotkeys (void)
Clear all hotkeys and update the view.
static void update_hotkeys_info (void)
Update hotkeys path and source widgets.
static GtkListStore * create_hotkeys_model (void)
Create model for the hotkeys table.
static gboolean on_key_release_event (GtkWidget *dialog, GdkEventKey *event, gpointer data)
Handler for the 'key-release-event'.
static gboolean update_treeview_hotkey (const gchar *accel)
Update the hotkey string of the currently selected row.
static void update_treeview_full (void)
Update treeview by regenerating model with current hotkeys.
static gboolean remove_treeview_hotkey (const gchar *accel)
Remove the accelerator label accel from the model.
static void dialog_accept_handler (int action)
Set/update hotkey in accelerator group, connect to item(s), if any.
static void dialog_clear_handler (int action)
Clear hotkey from accelerator group and item(s), if any.
static void on_response (GtkDialog *dialog, gint response_id, gpointer data)
Handler for the 'response' event of the dialog.
static GtkWidget * create_content_widget (const gchar *action, const gchar *hotkey)
Create content widget for the hotkey dialog.
static void show_hotkey_dialog (GtkTreePath *path)
Show dialog to set/edit hotkey for an action.
static void on_row_activated (GtkTreeView *view, GtkTreePath *path, GtkTreeViewColumn *column, gpointer data)
Handler for the 'row-activated' event of the treeview.
static void on_context_edit_activate (GtkWidget *item, gpointer treepath)
Handler for the 'activate' event of the context menu 'set'/'edit' item.
static void on_context_clear_activate (GtkWidget *unused, gpointer treepath)
Handler for the 'activate' event of the context menu 'clear' item.
static void clear_dialog_callback (GtkDialog *dialog, gboolean result)
Callback for the 'clear all' confirmation dialog.
static void show_clear_all_confirm_dialog (void)
Show confirmation dialog for clearing all hotkeys.
static void on_context_clear_all_activate (GtkWidget *item, gpointer unused)
Handler for the 'activate' event of the context menu 'clear all' item.
static GtkWidget * create_context_menu (GtkTreePath *path)
Create context menu for the tree view.
static gboolean on_button_press_event (GtkWidget *view, GdkEvent *event, gpointer data)
Handler for the 'button-press-event' event of the treeview.
static GtkWidget * create_hotkeys_view (void)
Create the table view of the hotkeys.
static void on_defaults_clicked (GtkButton *button, gpointer unused)
Handler for the 'clicked' event handler of the 'Reset to default' button.
static void on_reload_clicked (GtkButton *button, gpointer unused)
Handler for the 'clicked' event handler of the 'Reload' button.
static void load_from_callback (gboolean result)
Callback for the hotkeys load dialog.
static void on_load_from_clicked (GtkButton *button, gpointer unused)
Handler for the 'clicked' event handler of the 'Load from' button.
static void save_as_callback (GtkDialog *dialog, gchar *path, gpointer data)
Call for the save-as dialog.
static void on_save_as_clicked (GtkButton *button, gpointer unused)
Handler for the 'clicked' event handler of the 'Save as' button.
static void on_save_clicked (GtkButton *button, gpointer unused)
Handler for the 'clicked' event handler of the 'Save' button.
static GtkWidget * create_hotkey_file_grid (void)
Create grid with hotkey file info and buttons.
GtkWidget * settings_hotkeys_widget_create (GtkWidget *parent)
Create main widget.
Variables
static GtkWidget * hotkeys_view
Reference to the hotkeys table widget.
static GtkWidget * hotkeys_path
static GtkWidget * hotkeys_source
static GtkWidget * hotkey_string
Label holding the hotkey string.
static guint hotkey_keysym
static guint hotkey_mask
static guint hotkey_keysym_old
static guint hotkey_mask_old
static guint accepted_mods = (GDK_SHIFT_MASK|GDK_CONTROL_MASK|GDK_MOD1_MASK)
Bitmask with accepted modifiers.
Detailed Description
Hotkeys settings.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
ARRAY_LEN
#define ARRAY_LEN (arr) (sizeof arr / sizeof arr[0])
Typedef Documentation
mod_mask_t
typedef struct mod_mask_s mod_mask_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Columns for the hotkeys table.
Enumerator
COL_ACTION_ID
action ID (integer)
COL_ACTION_NAME
action name (string)
COL_ACTION_DESC
action description (string)
COL_HOTKEY
key and modifiers (string)
anonymous enum
anonymous enum
Set/Unset hotkey dialog custom response IDs.
Enumerator
RESPONSE_CLEAR
clear hotkey for selected item
Function Documentation
clear_all_hotkeys()
static void clear_all_hotkeys (void) static
Clear all hotkeys and update the view.
Referenced by clear_dialog_callback().
clear_dialog_callback()
static void clear_dialog_callback (GtkDialog * dialog, gboolean result) static
Callback for the 'clear all' confirmation dialog.
Parameters
[in] dialog confirmation dialog
[in] result result of the dialog
Referenced by show_clear_all_confirm_dialog().
create_content_widget()
static GtkWidget * create_content_widget (const gchar * action, const gchar * hotkey) static
Create content widget for the hotkey dialog.
Parameters
[in] action hotkey action name
[in] hotkey hotkey string
Returns
GtkGrid
Referenced by show_hotkey_dialog().
create_context_menu()
static GtkWidget * create_context_menu (GtkTreePath * path) static
Create context menu for the tree view.
Parameters
[in] path tree view path of selected row
Returns
GtkMenu
Referenced by on_button_press_event().
create_hotkey_file_grid()
static GtkWidget * create_hotkey_file_grid (void) static
Create grid with hotkey file info and buttons.
Returns
GtkGrid
Referenced by settings_hotkeys_widget_create().
create_hotkeys_model()
static GtkListStore * create_hotkeys_model (void) static
Create model for the hotkeys table.
Returns
new list store
Referenced by create_hotkeys_view(), and update_treeview_full().
create_hotkeys_view()
static GtkWidget * create_hotkeys_view (void) static
Create the table view of the hotkeys.
Create a table with 'action', 'description' and 'hotkey' columns. Columns are resizable and the table is sortable by clicking the column headers.
Returns
GtkTreeView
Referenced by settings_hotkeys_widget_create().
dialog_accept_handler()
static void dialog_accept_handler (int action) static
Set/update hotkey in accelerator group, connect to item(s), if any.
Parameters
[in] action UI action ID
Todo:
Simplify this function, it does too much.
Referenced by on_response().
dialog_clear_handler()
static void dialog_clear_handler (int action) static
Clear hotkey from accelerator group and item(s), if any.
Parameters
[in] action UI action ID
Referenced by on_response().
label_helper()
static GtkWidget * label_helper (const char * text) static
Create left-aligned label using Pango markup.
Parameters
[in] text text using Pango markup
Returns
GtkLabel
Referenced by create_content_widget(), and create_hotkey_file_grid().
load_from_callback()
static void load_from_callback (gboolean result) static
Callback for the hotkeys load dialog.
Parameters
[in] result user loaded a file
Referenced by on_load_from_clicked().
on_button_press_event()
static gboolean on_button_press_event (GtkWidget * view, GdkEvent * event, gpointer data) static
Handler for the 'button-press-event' event of the treeview.
Parameters
[in] view tree view
[in] event button press event data
[in] unused extra event data (unused)
Returns
TRUE to stop event propagation (right-click), FALSE to continue event propagation (other clicks)
Referenced by create_hotkeys_view().
on_context_clear_activate()
static void on_context_clear_activate (GtkWidget * unused, gpointer treepath) static
Handler for the 'activate' event of the context menu 'clear' item.
Clears selected hotkey from the menu(s) and updated the table.
Parameters
[in] unused menu item (unused)
[in] treepath GtkTreePath to the selected row in the table
Referenced by create_context_menu().
on_context_clear_all_activate()
static void on_context_clear_all_activate (GtkWidget * item, gpointer unused) static
Handler for the 'activate' event of the context menu 'clear all' item.
Clears all hotkeys.
Parameters
[in] unused menu item (unused)
[in] treepath GtkTreePath to the selected row in the table
Referenced by create_context_menu().
on_context_edit_activate()
static void on_context_edit_activate (GtkWidget * item, gpointer treepath) static
Handler for the 'activate' event of the context menu 'set'/'edit' item.
Pops up dialog to set/edit/clear the selected hotkey.
Parameters
[in] unused menu item (unused)
[in] treepath GtkTreePath to the selected row in the table
Referenced by create_context_menu().
on_defaults_clicked()
static void on_defaults_clicked (GtkButton * button, gpointer unused) static
Handler for the 'clicked' event handler of the 'Reset to default' button.
Parameters
[in] button button (unused)
[in] unused extra event data (unused)
Referenced by create_hotkey_file_grid().
on_key_release_event()
static gboolean on_key_release_event (GtkWidget * dialog, GdkEventKey * event, gpointer data) static
Handler for the 'key-release-event'.
Parameters
[in] dialog window triggering the event
[in] event event info
[in] data extra event data (unused)
Returns
TRUE to propagate events further
Referenced by show_hotkey_dialog().
on_load_from_clicked()
static void on_load_from_clicked (GtkButton * button, gpointer unused) static
Handler for the 'clicked' event handler of the 'Load from' button.
Parameters
[in] button button (unused)
[in] unused extra event data (unused)
Referenced by create_hotkey_file_grid().
on_reload_clicked()
static void on_reload_clicked (GtkButton * button, gpointer unused) static
Handler for the 'clicked' event handler of the 'Reload' button.
Parameters
[in] button button (unused)
[in] unused extra event data (unused)
Referenced by create_hotkey_file_grid().
on_response()
static void on_response (GtkDialog * dialog, gint response_id, gpointer data) static
Handler for the 'response' event of the dialog.
Parameters
[in] dialog hotkey dialog
[in] response_id response ID
[in] data action ID
Referenced by show_hotkey_dialog().
on_row_activated()
static void on_row_activated (GtkTreeView * view, GtkTreePath * path, GtkTreeViewColumn * column, gpointer data) static
Handler for the 'row-activated' event of the treeview.
Handler triggered by double-clicked or pressing Return on a tree row.
Parameters
[in] view tree view (unused)
[in] path tree path to activated row
[in] column activated column (unused)
[in] unused extra event data (unused)
Referenced by create_hotkeys_view().
on_save_as_clicked()
static void on_save_as_clicked (GtkButton * button, gpointer unused) static
Handler for the 'clicked' event handler of the 'Save as' button.
Parameters
[in] button button (unused)
[in] unused extra event data (unused)
Referenced by create_hotkey_file_grid().
on_save_clicked()
static void on_save_clicked (GtkButton * button, gpointer unused) static
Handler for the 'clicked' event handler of the 'Save' button.
Parameters
[in] button button (unused)
[in] unused extra event data (unused)
Referenced by create_hotkey_file_grid().
remove_treeview_hotkey()
static gboolean remove_treeview_hotkey (const gchar * accel) static
Remove the accelerator label accel from the model.
Parameters
[in] accel accelerator label
Returns
TRUE on success
Referenced by dialog_accept_handler().
save_as_callback()
static void save_as_callback (GtkDialog * dialog, gchar * path, gpointer data) static
Call for the save-as dialog.
Save current hotkeys as path, update source path and type widgets.
Parameters
[in] dialog file dialog
[in] path path to save hotkeys to
[in] extra extra callback data (unused)
Referenced by on_save_as_clicked().
settings_hotkeys_widget_create()
GtkWidget * settings_hotkeys_widget_create (GtkWidget * parent)
Create main widget.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
show_clear_all_confirm_dialog()
static void show_clear_all_confirm_dialog (void) static
Show confirmation dialog for clearing all hotkeys.
Referenced by on_context_clear_all_activate().
show_hotkey_dialog()
static void show_hotkey_dialog (GtkTreePath * path) static
Show dialog to set/edit hotkey for an action.
Parameters
[in] path tree path to selected item in tree view
Referenced by on_context_edit_activate(), and on_row_activated().
update_hotkeys_info()
static void update_hotkeys_info (void) static
Update hotkeys path and source widgets.
Referenced by create_hotkey_file_grid(), load_from_callback(), on_defaults_clicked(), on_reload_clicked(), on_save_clicked(), and save_as_callback().
update_treeview_full()
static void update_treeview_full (void) static
Update treeview by regenerating model with current hotkeys.
Referenced by load_from_callback(), on_defaults_clicked(), and on_reload_clicked().
update_treeview_hotkey()
static gboolean update_treeview_hotkey (const gchar * accel) static
Update the hotkey string of the currently selected row.
Parameters
[in] accel hotkey string
Returns
TRUE on success
Referenced by dialog_accept_handler(), dialog_clear_handler(), and on_context_clear_activate().
Variable Documentation
accepted_mods
guint accepted_mods = (GDK_SHIFT_MASK|GDK_CONTROL_MASK|GDK_MOD1_MASK) static
Bitmask with accepted modifiers.
Referenced by dialog_accept_handler(), and on_key_release_event().
hotkey_keysym
guint hotkey_keysym static
Referenced by create_content_widget(), dialog_accept_handler(), on_key_release_event(), on_response(), and show_hotkey_dialog().
hotkey_keysym_old
guint hotkey_keysym_old static
Referenced by show_hotkey_dialog().
hotkey_mask
guint hotkey_mask static
Referenced by create_content_widget(), dialog_accept_handler(), on_key_release_event(), and show_hotkey_dialog().
hotkey_mask_old
guint hotkey_mask_old static
Referenced by show_hotkey_dialog().
hotkey_string
GtkWidget* hotkey_string static
Label holding the hotkey string.
Referenced by create_content_widget(), and on_key_release_event().
hotkeys_path
GtkWidget* hotkeys_path static
Referenced by create_hotkey_file_grid(), and update_hotkeys_info().
hotkeys_source
GtkWidget* hotkeys_source static
Referenced by create_hotkey_file_grid(), and update_hotkeys_info().
hotkeys_view
GtkWidget* hotkeys_view static
Reference to the hotkeys table widget.
Used for easier event handling.
Referenced by clear_all_hotkeys(), create_context_menu(), on_context_clear_activate(), remove_treeview_hotkey(), settings_hotkeys_widget_create(), show_hotkey_dialog(), update_treeview_full(), and update_treeview_hotkey().