vsid: arch/gtk3/widgets/base/cartridgewidgets.c File Reference
cartridgewidgets.c File Reference
Widgets to control cartridge resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "basedialogs.h"
#include "cartridge.h"
#include "debug_gtk3.h"
#include "lastdir.h"
#include "log.h"
#include "resourcecheckbutton.h"
#include "resourcewidgetmediator.h"
#include "ui.h"
#include "cartridgewidgets.h"
Data Structures
struct ci_state_s
State object containing per-image data.
Typedefs
typedef struct ci_state_s ci_state_t
State object containing per-image data.
Functions
static GtkWidget * open_dialog_new (ci_state_t *state)
Forward declarations.
static GtkWidget * save_dialog_new (ci_state_t *state)
Create save-as dialog for cartridge images.
static gboolean update_resource (ci_state_t *state, const char *filename)
Update filename resource of cartridge image.
static void on_open_response (GtkDialog *self, gint response, gpointer data)
Handler for the 'response' event of the open dialog.
static void on_save_response (GtkDialog *self, gint response, gpointer data)
Handler for the 'response' event of the save-as dialog.
static void on_save_clicked (GtkButton *self, gpointer data)
Handler for the 'clicked' event of the save-as button.
static void on_flush_clicked (GtkButton *self, gpointer data)
Handler for the 'clicked' event of the flush button.
static gboolean on_filename_focus_out_event (GtkEntry *self, GdkEvent *event, gpointer data)
Handler for the 'focus-out-event' event of the filename entry.
static gboolean on_filename_key_press_event (GtkEntry *self, GdkEvent *event, gpointer data)
Handler for the 'key-press-event' event of the filename entry.
static void on_filename_icon_press (GtkEntry *self, GtkEntryIconPosition icon_pos, GdkEvent *event, gpointer data)
Handler for the 'icon-press' event of the filename entry.
static ci_state_t * ci_state_new (int cart_id, const char *cart_name, cart_img_t image_num, const char *image_tag)
Allocate and initialize widget state object.
static void ci_state_free (void *state)
Free state and its members.
static gboolean valid_image_num (cart_img_t num)
Test if image number is valid.
static void update_buttons_sensitivity (const ci_state_t *state)
Update sensitivity of flush/save buttons.
static GtkWidget * create_filename_entry (ci_state_t *state)
Create entry with clickable icon for image filename.
static GtkWidget * label_helper (const char *text)
Create left-aligned label with Pango markup.
GtkWidget * cart_image_widget_new (int cart_id, const char *cart_name, cart_img_t image_num, const char *image_tag, const char *resource, gboolean flush_button, gboolean save_button)
Create new cartridge image widget.
void cart_image_widget_append_check (GtkWidget *widget, const char *resource, const char *text)
Append a check button for a resource.
void cart_image_widgets_shutdown (void)
Clean up resources used by this file on emulator shutdown.
Variables
static const char * tag_defaults [CART_IMAGE_COUNT]
Default image tags.
static char * last_dir = NULL
Last used directory in file dialogs.
static char * last_file = NULL
Last used filename in file dialogs.
Detailed Description
Widgets to control cartridge resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Typedef Documentation
ci_state_t
typedef struct ci_state_s ci_state_t
State object containing per-image data.
This object is set as the resource mediator's extra data object so we can access all relevant data on a cartridge image for the widgets.
Function Documentation
cart_image_widget_append_check()
void cart_image_widget_append_check (GtkWidget * widget, const char * resource, const char * text)
Append a check button for a resource.
Append a check button for resource to the cartridge image widget.
Parameters
[in] widget cartridge image widget
[in] resource resource name
[in] text text for the check button
Referenced by create_dqbb_image_widget(), create_expert_image_widget(), create_georam_image_widget(), create_isepic_image_widget(), create_primary_image_widget(), create_ramcart_image_widget(), create_reu_image_widget(), create_secondary_image_widget(), and settings_gmod2_widget_create().
cart_image_widget_new()
GtkWidget * cart_image_widget_new (int cart_id, const char * cart_name, cart_img_t image_num, const char * image_tag, const char * resource, gboolean flush_button, gboolean save_button)
Create new cartridge image widget.
Create widget to select/save/flush a cartridge image.
If image_tag is NULL a default "primary", "secondary" etc tag will be used. If resource is NULL the GtkEntry to select an image file won't be added.
Parameters
[in] cart_id cartridge ID
[in] cart_name cartridge name
[in] image_num cartridge image number
[in] image_tag cartridge image tag (can be NULL)
[in] resource cartridge image file resource (can be NULL)
[in] flush_button cartridge widget needs "flush image" button
[in] save_button cartridge widget needs "save image as" button
Returns
GtkGrid
See also
cartridge.h for constants for cart_id and cart_name.
cart_img_t for valid values for image_num.
Referenced by create_dqbb_image_widget(), create_expert_image_widget(), create_georam_image_widget(), create_isepic_image_widget(), create_primary_image_widget(), create_ramcart_image_widget(), create_reu_image_widget(), create_secondary_image_widget(), and settings_gmod2_widget_create().
cart_image_widgets_shutdown()
void cart_image_widgets_shutdown (void)
Clean up resources used by this file on emulator shutdown.
Free the last used directory/filename which might be allocated by the cartridge image widgets. This function should be called once on emulator shutdown.
Referenced by ui_shutdown().
ci_state_free()
static void ci_state_free (void * state) static
Free state and its members.
Free the state object and its members. This is called by the 'destroy' signal handler of the main widget, which is registered by the resource mediator.
Parameters
[in] state widget state object
Referenced by cart_image_widget_new().
ci_state_new()
static ci_state_t * ci_state_new (int cart_id, const char * cart_name, cart_img_t image_num, const char * image_tag) static
Allocate and initialize widget state object.
Parameters
[in] cart_id cartridge ID
[in] cart_name cartridge name
[in] image_num cartridge image number
[in] image_tag cartridge image tag (can be NULL)
Returns
new initialized state object
Referenced by cart_image_widget_new().
create_filename_entry()
static GtkWidget * create_filename_entry (ci_state_t * state) static
Create entry with clickable icon for image filename.
Parameters
[in] state widget state object
Returns
GtkEntry
Referenced by cart_image_widget_new().
label_helper()
static GtkWidget * label_helper (const char * text) static
Create left-aligned label with Pango markup.
Parameters
[in] text text for the label using Pango markup
Returns
GtkLabel
Referenced by cart_image_widget_new().
on_filename_focus_out_event()
static gboolean on_filename_focus_out_event (GtkEntry * self, GdkEvent * event, gpointer data) static
Handler for the 'focus-out-event' event of the filename entry.
Update filename resource with the text in self if the widget looses focus.
Parameters
[in] self filename entry
[in] event event info
[in] data widget state object
Returns
GDK_EVENT_PROPAGATE
Referenced by create_filename_entry().
on_filename_icon_press()
static void on_filename_icon_press (GtkEntry * self, GtkEntryIconPosition icon_pos, GdkEvent * event, gpointer data) static
Handler for the 'icon-press' event of the filename entry.
Show a file chooser dialog to select cartridge image.
Parameters
[in] self filename entry
[in] icon_pos icon position in self (ignored)
[in] event event information (ignored)
[in] data widget state object
Referenced by create_filename_entry().
on_filename_key_press_event()
static gboolean on_filename_key_press_event (GtkEntry * self, GdkEvent * event, gpointer data) static
Handler for the 'key-press-event' event of the filename entry.
Update filename resource with the text in self if the user presses Enter, Return or "tabs out".
Parameters
[in] self filename entry
[in] event event info
[in] data widget state object
Returns
GDK_EVENT_PROPAGATE
Referenced by create_filename_entry().
on_flush_clicked()
static void on_flush_clicked (GtkButton * self, gpointer data) static
Handler for the 'clicked' event of the flush button.
Parameters
[in] self button (ignored)
[in] data widget state object
Referenced by cart_image_widget_new().
on_open_response()
static void on_open_response (GtkDialog * self, gint response, gpointer data) static
Handler for the 'response' event of the open dialog.
Set image filename resource and update last used dir/file on success.
Parameters
[in] self open dialog
[in] response response ID
[in] data widget state object
Referenced by open_dialog_new().
on_save_clicked()
static void on_save_clicked (GtkButton * self, gpointer data) static
Handler for the 'clicked' event of the save-as button.
Show file chooser dialog to save copy of image file.
Parameters
[in] self button (ignored)
[in] data widget state object
Referenced by cart_image_widget_new().
on_save_response()
static void on_save_response (GtkDialog * self, gint response, gpointer data) static
Handler for the 'response' event of the save-as dialog.
Call the proper cartridge API function to save the image to file and update the last used directory/filename on success.
Parameters
[in] self save-as dialog
[in] response response ID
[in] data widget state object
Referenced by save_dialog_new().
open_dialog_new()
static GtkWidget * open_dialog_new (ci_state_t * state) static
Forward declarations.
Create open dialog for cartridge images.
Parameters
[in] state widget state object
Returns
GtkFileChooserDialog
Referenced by on_filename_icon_press().
save_dialog_new()
static GtkWidget * save_dialog_new (ci_state_t * state) static
Create save-as dialog for cartridge images.
Parameters
[in] state widget state object
Returns
GtkFileChooserDialog
Referenced by on_save_clicked().
update_buttons_sensitivity()
static void update_buttons_sensitivity (const ci_state_t * state) static
Update sensitivity of flush/save buttons.
Use the _can_flush()/_can_save() cartridge functions to set the sensitivity of the save/flush buttons.
Parameters
[in] state widget state object
Referenced by cart_image_widget_new(), and update_resource().
update_resource()
static gboolean update_resource (ci_state_t * state, const char * filename) static
Update filename resource of cartridge image.
Update the resource for the cartridge image to filename, if updating fails an error message is displayed.
Parameters
[in] state widget state object
[in] filename new value for the resource
Returns
TRUE on success
Referenced by on_filename_focus_out_event(), on_filename_key_press_event(), and on_open_response().
valid_image_num()
static gboolean valid_image_num (cart_img_t num) static
Test if image number is valid.
Parameters
[in] num cartridge image number
Returns
TRUE if valid
Referenced by cart_image_widget_new().
Variable Documentation
last_dir
char* last_dir = NULL static
Last used directory in file dialogs.
Referenced by cart_image_widgets_shutdown(), on_filename_icon_press(), on_open_response(), on_save_clicked(), and on_save_response().
last_file
char* last_file = NULL static
Last used filename in file dialogs.
Referenced by cart_image_widgets_shutdown(), on_filename_icon_press(), on_open_response(), on_save_clicked(), and on_save_response().
tag_defaults
const char* tag_defaults[CART_IMAGE_COUNT] static
Initial value:
= {
    "primary",
    "secondary",
    "tertiary",
    "quaternary"
}
Default image tags.
Tags used for images in case the user doesn't provide one.
Referenced by ci_state_new(), on_flush_clicked(), and on_save_response().