vsid: vicii/vicii-sprites.h File Reference
vicii-sprites.h File Reference
Data Structures
struct vicii_sprites_fetch_s
This defines the stolen sprite cycles for all the values of ‘dma_msk’.
Typedefs
typedef struct vicii_sprites_fetch_s vicii_sprites_fetch_t
Functions
void vicii_sprites_init (void)
void vicii_sprites_shutdown (void)
void vicii_sprites_set_x_position (unsigned int num, int new_x, int raster_x)
void vicii_sprites_reset_sprline (void)
void vicii_sprites_init_sprline (void)
void vicii_sprites_reset_xshift (void)
int vicii_sprite_offset (void)
Variables
const vicii_sprites_fetch_t vicii_sprites_fetch_table [256][4]
Sprite fetch data.
const int vicii_sprites_crunch_table [64]
Typedef Documentation
vicii_sprites_fetch_t
typedef struct vicii_sprites_fetch_s vicii_sprites_fetch_t
Function Documentation
vicii_sprite_offset()
int vicii_sprite_offset (void)
Referenced by init_raster(), vicii_reset_registers(), and vicii_sprites_set_x_position().
vicii_sprites_init()
void vicii_sprites_init (void)
Referenced by vicii_init().
vicii_sprites_init_sprline()
void vicii_sprites_init_sprline (void)
Referenced by vicii_timing_set().
vicii_sprites_reset_sprline()
void vicii_sprites_reset_sprline (void)
Referenced by handle_check_sprite_dma().
vicii_sprites_reset_xshift()
void vicii_sprites_reset_xshift (void)
Referenced by vicii_raster_draw_alarm_handler().
vicii_sprites_set_x_position()
void vicii_sprites_set_x_position (unsigned int num, int new_x, int raster_x)
Referenced by store_sprite_x_position_lsb(), store_sprite_x_position_msb(), and vicii_snapshot_read_module().
vicii_sprites_shutdown()
void vicii_sprites_shutdown (void)
Referenced by vicii_shutdown().
Variable Documentation
vicii_sprites_crunch_table
const int vicii_sprites_crunch_table[64] extern
Referenced by d017_store().
vicii_sprites_fetch_table
const vicii_sprites_fetch_t vicii_sprites_fetch_table[256][4] extern
Sprite fetch data.
!
Todo:
FIXME: This can do with some proper explanation!
Referenced by handle_check_sprite_dma(), handle_fetch_sprite(), and vicii_snapshot_read_module().