x128: drive/iecieee.h File Reference
iecieee.h File Reference
#include "types.h"
Functions
void iecieee_drive_init (struct diskunit_context_s *drv)
void iecieee_drive_shutdown (struct diskunit_context_s *drv)
void iecieee_drive_reset (struct diskunit_context_s *drv)
void iecieee_drive_setup_context (struct diskunit_context_s *drv)
int iecieee_drive_snapshot_read (struct diskunit_context_s *ctxptr, struct snapshot_s *s)
int iecieee_drive_snapshot_write (struct diskunit_context_s *ctxptr, struct snapshot_s *s)
Function Documentation
iecieee_drive_init()
void iecieee_drive_init (struct diskunit_context_s * drv)
Referenced by machine_drive_init().
iecieee_drive_reset()
void iecieee_drive_reset (struct diskunit_context_s * drv)
Referenced by machine_drive_reset().
iecieee_drive_setup_context()
void iecieee_drive_setup_context (struct diskunit_context_s * drv)
Referenced by machine_drive_setup_context().
iecieee_drive_shutdown()
void iecieee_drive_shutdown (struct diskunit_context_s * drv)
Referenced by machine_drive_shutdown().
iecieee_drive_snapshot_read()
int iecieee_drive_snapshot_read (struct diskunit_context_s * ctxptr, struct snapshot_s * s)
Referenced by machine_drive_snapshot_read().
iecieee_drive_snapshot_write()
int iecieee_drive_snapshot_write (struct diskunit_context_s * ctxptr, struct snapshot_s * s)
Referenced by machine_drive_snapshot_write().