x128: video/render2x2rgbi.c File Reference
render2x2rgbi.c File Reference
#include "vice.h"
#include <stdio.h>
#include "render2x2.h"
#include "render2x2rgbi.h"
#include "types.h"
#include "video-color.h"
Functions
static void yuv_to_rgb (int32_t y, int32_t u, int32_t v, int16_t *red, int16_t *grn, int16_t *blu)
static void store_line_and_scanline_4 (video_render_color_tables_t *color_tab, uint8_t *const line, uint8_t *const scanline, int16_t *const prevline, const int shade, const int32_t y, const int32_t u, const int32_t v)
static void get_yuv_from_video (const int32_t unew, const int32_t vnew, const int off_flip, int32_t *const u, int32_t *const v)
static void render_generic_2x2_rgbi (video_render_color_tables_t *color_tab, const uint8_t *src, uint8_t *trg, unsigned int width, const unsigned int height, unsigned int xs, const unsigned int ys, unsigned int xt, const unsigned int yt, const unsigned int pitchs, const unsigned int pitcht, unsigned int viewport_first_line, unsigned int viewport_last_line, unsigned int pixelstride, const int write_interpolated_pixels, video_render_config_t *config)
void render_32_2x2_rgbi (video_render_color_tables_t *color_tab, const uint8_t *src, uint8_t *trg, unsigned int width, const unsigned int height, const unsigned int xs, const unsigned int ys, const unsigned int xt, const unsigned int yt, const unsigned int pitchs, const unsigned int pitcht, unsigned int viewport_first_line, unsigned int viewport_last_line, video_render_config_t *config)
Function Documentation
get_yuv_from_video()
static void get_yuv_from_video (const int32_t unew, const int32_t vnew, const int off_flip, int32_t *const u, int32_t *const v) inline static
Referenced by render_generic_2x2_rgbi().
render_32_2x2_rgbi()
void render_32_2x2_rgbi (video_render_color_tables_t * color_tab, const uint8_t * src, uint8_t * trg, unsigned int width, const unsigned int height, const unsigned int xs, const unsigned int ys, const unsigned int xt, const unsigned int yt, const unsigned int pitchs, const unsigned int pitcht, unsigned int viewport_first_line, unsigned int viewport_last_line, video_render_config_t * config)
Referenced by video_render_crt_mono_main(), and video_render_rgbi_main().
render_generic_2x2_rgbi()
static void render_generic_2x2_rgbi (video_render_color_tables_t * color_tab, const uint8_t * src, uint8_t * trg, unsigned int width, const unsigned int height, unsigned int xs, const unsigned int ys, unsigned int xt, const unsigned int yt, const unsigned int pitchs, const unsigned int pitcht, unsigned int viewport_first_line, unsigned int viewport_last_line, unsigned int pixelstride, const int write_interpolated_pixels, video_render_config_t * config) inline static
Referenced by render_32_2x2_rgbi().
store_line_and_scanline_4()
static void store_line_and_scanline_4 (video_render_color_tables_t * color_tab, uint8_t *const line, uint8_t *const scanline, int16_t *const prevline, const int shade, const int32_t y, const int32_t u, const int32_t v) inline static
Referenced by render_generic_2x2_rgbi().
yuv_to_rgb()
static void yuv_to_rgb (int32_t y, int32_t u, int32_t v, int16_t * red, int16_t * grn, int16_t * blu) inline static
Referenced by store_line_and_scanline_4().