vsid: iecbus.h File Reference
iecbus.h File Reference
IEC bus handling.
#include "types.h"
Data Structures
struct iecbus_s
Macros
#define IECBUS_NUM 16
#define IECBUS_STATUS_TRUEDRIVE 0
#define IECBUS_STATUS_DRIVETYPE 1
#define IECBUS_STATUS_IECDEVICE 2
#define IECBUS_STATUS_VIRTUALDEVICES 3
Typedefs
typedef struct iecbus_s iecbus_t
Enumerations
enum {
IECBUS_DEVICE_READ_DATA = 0x01 ,
IECBUS_DEVICE_READ_CLK = 0x04 ,
IECBUS_DEVICE_READ_ATN = 0x80 ,
IECBUS_DEVICE_ATNA = 0x10 ,
IECBUS_DEVICE_WRITE_CLK = 0x40 ,
IECBUS_DEVICE_WRITE_DATA = 0x80
}
Functions
iecbus_t * iecbus_drive_port (void)
void iecbus_init (void)
void iecbus_cpu_undump (uint8_t data)
void iecbus_status_set (unsigned int type, unsigned int unit, unsigned int enable)
uint8_t iecbus_device_read (void)
int iecbus_device_write (unsigned int unit, uint8_t data)
Variables
iecbus_t iecbus
uint8_t(* iecbus_callback_read)(CLOCK)
void(* iecbus_callback_write)(uint8_t, CLOCK)
void(* iecbus_update_ports)(void)
Detailed Description
IEC bus handling.
Author
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Macro Definition Documentation
IECBUS_NUM
#define IECBUS_NUM 16
IECBUS_STATUS_DRIVETYPE
#define IECBUS_STATUS_DRIVETYPE 1
IECBUS_STATUS_IECDEVICE
#define IECBUS_STATUS_IECDEVICE 2
IECBUS_STATUS_TRUEDRIVE
#define IECBUS_STATUS_TRUEDRIVE 0
IECBUS_STATUS_VIRTUALDEVICES
#define IECBUS_STATUS_VIRTUALDEVICES 3
Typedef Documentation
iecbus_t
typedef struct iecbus_s iecbus_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IECBUS_DEVICE_READ_DATA
IECBUS_DEVICE_READ_CLK
IECBUS_DEVICE_READ_ATN
IECBUS_DEVICE_ATNA
IECBUS_DEVICE_WRITE_CLK
IECBUS_DEVICE_WRITE_DATA
Function Documentation
iecbus_cpu_undump()
void iecbus_cpu_undump (uint8_t data)
Referenced by undump_ciapa().
iecbus_device_read()
uint8_t iecbus_device_read (void)
Referenced by serial_iec_device_exec_main().
iecbus_device_write()
int iecbus_device_write (unsigned int unit, uint8_t data)
Referenced by serial_iec_device_disable(), serial_iec_device_exec_main(), serial_iec_device_init(), and serial_iec_device_reset().
iecbus_drive_port()
iecbus_t * iecbus_drive_port (void)
Referenced by cia1581_setup_context(), cmdhd_setup_context(), iec_drive_port_default(), via1d1541_setup_context(), and via4000_setup_context().
iecbus_init()
void iecbus_init (void)
Referenced by machine_bus_init_machine().
iecbus_status_set()
void iecbus_status_set (unsigned int type, unsigned int unit, unsigned int enable)
Referenced by machine_bus_status_drivetype_set(), machine_bus_status_truedrive_set(), machine_bus_status_virtualdevices_set(), and set_iec_device_enable().
Variable Documentation
iecbus
iecbus_t iecbus extern
Referenced by iecbus_cpu_read_conf0(), iecbus_cpu_read_conf1(), iecbus_cpu_read_conf2(), iecbus_cpu_read_conf3(), iecbus_cpu_undump(), iecbus_cpu_write_conf0(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), iecbus_cpu_write_conf3(), iecbus_device_read(), iecbus_device_write(), and iecbus_init().
iecbus_callback_read
uint8_t(* iecbus_callback_read) (CLOCK) (CLOCK) extern
Referenced by calculate_callback_index().
iecbus_callback_write
void(* iecbus_callback_write) (uint8_t, CLOCK) (uint8_t , CLOCK) extern
Referenced by calculate_callback_index().
iecbus_update_ports
void(* iecbus_update_ports) (void) (void) extern
Referenced by c64iec_init(), and iecbus_device_write().