x128: arch/gtk3/widgets/drivemodelwidget.h File Reference
drivemodelwidget.h File Reference
Drive model selection widget - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
GtkWidget * drive_model_widget_create (int unit)
Create a drive unit selection widget.
void drive_model_widget_update (GtkWidget *widget)
Update the drive type widget.
void drive_model_widget_add_callback (GtkWidget *widget, void(*cb_func)(GtkWidget *, gpointer), gpointer cb_data)
Add custom callback to widget.
GtkWidget * drive_model_widget_create_combo (int unit, gboolean show_all)
Create drive model combo box.
gboolean drive_model_widget_sync_combo (GtkWidget *widget)
Synchronize the widget with its resource.
int drive_model_widget_value_combo (GtkWidget *widget)
Get current drive model.
Detailed Description
Drive model selection widget - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
drive_model_widget_add_callback()
void drive_model_widget_add_callback (GtkWidget * widget, void(*)(GtkWidget *, gpointer) cb_func, gpointer cb_data)
Add custom callback to widget.
Adds a user-defined callback function on drive type changes.
Parameters
[in,out] widget drive options widget
[in] cb_func callback function
[in] cb_data data passed with cb_func
Referenced by create_left_layout().
drive_model_widget_create()
GtkWidget * drive_model_widget_create (int unit)
Create a drive unit selection widget.
Creates a widget with four radio buttons, horizontally aligned, to select a drive unit (8-11).
Parameters
[in] unit default drive unit (8-11)
Returns
GtkGrid
drive_model_widget_create_combo()
GtkWidget * drive_model_widget_create_combo (int unit, gboolean show_all)
Create drive model combo box.
Parameters
[in] unit drive unit (8-11)
[in] show_all show all drive types, use FALSE to only show types supported by the current machine config
Returns
GtkComboBox
Referenced by create_left_layout().
drive_model_widget_sync_combo()
gboolean drive_model_widget_sync_combo (GtkWidget * widget)
Synchronize the widget with its resource.
Select current item based on resource without triggering the 'changed' event.
Parameters
[in] widget drive model widget
Returns
TRUE if an item matched the current resource value
Referenced by drive_model_widget_create_combo().
drive_model_widget_update()
void drive_model_widget_update (GtkWidget * widget)
Update the drive type widget.
This reiterates the drive info list to see if any setting changes made drive types available/unavailable.
Parameters
[in,out] widget drive type widget
Todo:
temporary block the resource-set callback
Todo:
temporary block the resource-set callback
Referenced by drive_model_widget_create().
drive_model_widget_value_combo()
int drive_model_widget_value_combo (GtkWidget * widget)
Get current drive model.
Parameters
[in] widget drive model widget
Returns
drive model ID or -1 when no item is selected in the widget
Referenced by on_combo_changed(), and on_model_changed().