x128: arch/gtk3/widgets/petiosizewidget.c File Reference
petiosizewidget.c File Reference
Widget to set the PET I/O area size (PET 8296 only)
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "resources.h"
#include "petiosizewidget.h"
Functions
static void on_io_size_changed (GtkWidget *widget, int id)
Handler for the 'toggled' event of the radio buttons.
GtkWidget * pet_io_size_widget_create (void)
Create PET I/O area size widget.
void pet_io_size_widget_set_callback (void(*func)(int))
Set callback for radio button 'toggle' events.
void pet_io_size_widget_sync (GtkWidget *widget)
Synchronize widget with its resource.
Variables
static const vice_gtk3_radiogroup_entry_t io_sizes []
Available I/O sizes.
static void(* user_callback)(int) = NULL
Function to call on 'toggle' events of the radio buttons.
Detailed Description
Widget to set the PET I/O area size (PET 8296 only)
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_io_size_changed()
static void on_io_size_changed (GtkWidget * widget, int id) static
Handler for the 'toggled' event of the radio buttons.
Triggers the optional callback with the current radio button ID.
Parameters
[in] widget radio button (unused)
[in] id ID of the radio button
Referenced by pet_io_size_widget_create().
pet_io_size_widget_create()
GtkWidget * pet_io_size_widget_create (void)
Create PET I/O area size widget.
Returns
GtkGrid
Referenced by create_pet_layout().
pet_io_size_widget_set_callback()
void pet_io_size_widget_set_callback (void(*)(int) func)
Set callback for radio button 'toggle' events.
Parameters
[in] func function to trigger
Referenced by create_pet_layout().
pet_io_size_widget_sync()
void pet_io_size_widget_sync (GtkWidget * widget)
Synchronize widget with its resource.
Parameters
[in,out] widget PET I/O size widget
Referenced by machine_model_handler_pet().
Variable Documentation
io_sizes
const vice_gtk3_radiogroup_entry_t io_sizes[] static
Initial value:
= {
    { "256 bytes", 256 },
    { "2048 bytes", 2048 },
    { NULL, -1 }
}
Available I/O sizes.
Referenced by pet_io_size_widget_create().
user_callback
void(* user_callback) (int) (int) = NULL static
Function to call on 'toggle' events of the radio buttons.
Allows the PET settings glue logic to update related widgets.
Referenced by on_io_size_changed(), pet_io_size_widget_create(), and pet_io_size_widget_set_callback().