vsid: printerdrv/drv-nl10.h File Reference
drv-nl10.h File Reference
Functions
int drv_nl10_init_resources (void)
int drv_nl10_init (void)
void drv_nl10_shutdown (void)
void drv_nl10_reset (void)
Function Documentation
drv_nl10_init()
int drv_nl10_init (void)
< serial dev 4, 5, 6 and user port
Referenced by printer_init().
drv_nl10_init_resources()
int drv_nl10_init_resources (void)
Referenced by printer_resources_init().
drv_nl10_reset()
void drv_nl10_reset (void)
< serial dev 4, 5, 6 and user port
Referenced by printer_reset().
drv_nl10_shutdown()
void drv_nl10_shutdown (void)
< serial dev 4, 5, 6 and user port
Referenced by printer_shutdown().