vsid: attach.c File Reference
attach.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "attach.h"
#include "cmdline.h"
#include "diskimage.h"
#include "driveimage.h"
#include "drive.h"
#include "fsdevice.h"
#include "fliplist.h"
#include "lib.h"
#include "log.h"
#include "machine-bus.h"
#include "machine-drive.h"
#include "network.h"
#include "resources.h"
#include "serial.h"
#include "types.h"
#include "uiapi.h"
#include "vdrive-bam.h"
#include "vdrive-iec.h"
#include "vdrive.h"
#include "vice-event.h"
#include "p64.h"
Data Structures
struct file_system_t
Macros
#define DBG(x)
#define NUM_DISK_UNITS 4
#define NUM_DRIVES 2
#define UNIT_AND_DRIVE(unit, drive) ((unit << 8) | drive)
#define GET_UNIT(du) ((du >> 8) & 0xFF)
#define GET_DRIVE(du) (du & 0xFF)
Functions
static int set_attach_device_readonly (int val, void *param)
static int set_file_system_device (int val, void *param)
static void vdrive_detach_disk_image_and_free (vdrive_t *vdrive, unsigned int unit, unsigned int drive)
static void detach_disk_image_and_free (disk_image_t *image, vdrive_t *vdrive, unsigned int unit, unsigned int drive)
static void detach_disk_image (disk_image_t *image, vdrive_t *vdrive, unsigned int unit, unsigned int drive)
static int attach_disk_image (disk_image_t *oldimage, vdrive_t *vdrive, const char *filename, unsigned int unit, unsigned int drive, int devicetype)
int file_system_resources_init (void)
int file_system_cmdline_options_init (void)
static int file_system_set_serial_hooks (unsigned int unit, int fs)
void file_system_init (void)
void file_system_shutdown (void)
struct vdrive_s * file_system_get_vdrive (unsigned int unit)
struct disk_image_s * file_system_get_image (unsigned int unit, unsigned int drive)
const char * file_system_get_disk_name (unsigned int unit, unsigned int drive)
int file_system_bam_get_disk_id (unsigned int unit, unsigned int drive, uint8_t *id)
int file_system_bam_set_disk_id (unsigned int unit, unsigned int drive, uint8_t *id)
static int file_system_attach_disk_internal (unsigned int unit, unsigned int drive, const char *filename)
int file_system_attach_disk (unsigned int unit, unsigned int drive, const char *filename)
static void file_system_detach_disk_single (unsigned int unit, unsigned int drive)
static void file_system_detach_disk_internal (unsigned int unit, unsigned int drive)
void file_system_detach_disk (unsigned int unit, unsigned int drive)
void file_system_detach_disk_all (void)
void file_system_detach_disk_shutdown (void)
void file_system_event_playback (unsigned int unit, unsigned int drive, const char *filename)
Variables
static file_system_t file_system [4]
static log_t attach_log = ((log_t)-2)
static int attach_device_readonly_enabled [4][2]
static int file_system_device_enabled [4] = { -1, -1, -1, -1 }
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
Macro Definition Documentation
DBG
#define DBG (x)
GET_DRIVE
#define GET_DRIVE (du) (du & 0xFF)
GET_UNIT
#define GET_UNIT (du) ((du >> 8) & 0xFF)
NUM_DISK_UNITS
#define NUM_DISK_UNITS 4
NUM_DRIVES
#define NUM_DRIVES 2
UNIT_AND_DRIVE
#define UNIT_AND_DRIVE (unit, drive) ((unit << 8) | drive)
Function Documentation
attach_disk_image()
static int attach_disk_image (disk_image_t * oldimage, vdrive_t * vdrive, const char * filename, unsigned int unit, unsigned int drive, int devicetype) static
< non-tde drive/image
< filesystem
< non-tde drive/image
< filesystem
Referenced by file_system_attach_disk_internal().
detach_disk_image()
static void detach_disk_image (disk_image_t * image, vdrive_t * vdrive, unsigned int unit, unsigned int drive) static
Referenced by detach_disk_image_and_free().
detach_disk_image_and_free()
static void detach_disk_image_and_free (disk_image_t * image, vdrive_t * vdrive, unsigned int unit, unsigned int drive) static
Referenced by attach_disk_image(), file_system_detach_disk_shutdown(), file_system_detach_disk_single(), and vdrive_detach_disk_image_and_free().
file_system_attach_disk()
int file_system_attach_disk (unsigned int unit, unsigned int drive, const char * filename)
Todo:
drive 1?
Referenced by autostart_disk(), autostart_prg_with_disk_image(), create_disk_image(), do_attach(), drive_snapshot_read_image_module(), fliplist_attach_head(), initcmdline_check_attach(), mon_attach(), on_drag_data_received(), set_attach_device_readonly(), try_attach_disk(), and ui_fliplist_select_cb().
file_system_attach_disk_internal()
static int file_system_attach_disk_internal (unsigned int unit, unsigned int drive, const char * filename) static
< non-tde drive/image
Referenced by file_system_attach_disk(), and file_system_event_playback().
file_system_bam_get_disk_id()
int file_system_bam_get_disk_id (unsigned int unit, unsigned int drive, uint8_t * id)
file_system_bam_set_disk_id()
int file_system_bam_set_disk_id (unsigned int unit, unsigned int drive, uint8_t * id)
file_system_cmdline_options_init()
int file_system_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
file_system_detach_disk()
void file_system_detach_disk (unsigned int unit, unsigned int drive)
Referenced by autostart_disk(), autostart_prg_with_virtual_fs(), drive_detach_action(), drive_resources_type(), drive_snapshot_read_image_module(), file_system_detach_disk_all(), mon_detach(), set_attach_device_readonly(), and try_attach_disk().
file_system_detach_disk_all()
void file_system_detach_disk_all (void)
Referenced by drive_detach_all_action(), and resources_set_defaults().
file_system_detach_disk_internal()
static void file_system_detach_disk_internal (unsigned int unit, unsigned int drive) static
< filesystem
Todo:
drive 1 for EVENT_ATTACHDISK
Referenced by file_system_detach_disk(), and file_system_event_playback().
file_system_detach_disk_shutdown()
void file_system_detach_disk_shutdown (void)
< real IEC device (opencbm)
Referenced by cmdline_help(), and machine_shutdown().
file_system_detach_disk_single()
static void file_system_detach_disk_single (unsigned int unit, unsigned int drive) static
Referenced by file_system_detach_disk_internal().
file_system_event_playback()
void file_system_event_playback (unsigned int unit, unsigned int drive, const char * filename)
Referenced by event_alarm_handler(), event_playback_attach_image(), and event_playback_event_list().
file_system_get_disk_name()
const char * file_system_get_disk_name (unsigned int unit, unsigned int drive)
Referenced by attach_disk_image(), and set_attach_device_readonly().
file_system_get_image()
struct disk_image_s * file_system_get_image (unsigned int unit, unsigned int drive)
Referenced by autostart_disk(), dir_menu_popup_create(), try_attach_disk(), and ui_do_drive_popup().
file_system_get_vdrive()
struct vdrive_s * file_system_get_vdrive (unsigned int unit)
Referenced by autostart_prg(), autostart_prg_with_disk_image(), drive_resources_type(), file_system_attach_disk_internal(), file_system_detach_disk_all(), file_system_detach_disk_shutdown(), file_system_detach_disk_single(), file_system_get_disk_name(), file_system_get_image(), fsdevice_attach(), fsdrive_listentalk(), fsdrive_open(), fsdrive_read(), fsdrive_reset(), fsdrive_unlisten(), fsdrive_write(), mon_drive_block_cmd(), mon_drive_execute_disk_cmd(), mon_drive_list(), mon_file_open(), parallel_trap_attention(), parallel_trap_receivebyte(), parallel_trap_sendbyte(), parallelcommand(), serialcommand(), set_file_system_device(), vdrive_bam_get_disk_id(), vdrive_bam_set_disk_id(), vdrive_flush(), vdrive_refresh(), and vdrive_snapshot_module_write().
file_system_init()
void file_system_init (void)
< non-tde drive/image
< filesystem
< filesystem
< real IEC device (opencbm)
< real IEC device (opencbm)
Referenced by machine_init().
file_system_resources_init()
int file_system_resources_init (void)
Referenced by machine_resources_init().
file_system_set_serial_hooks()
static int file_system_set_serial_hooks (unsigned int unit, int fs) static
Referenced by file_system_attach_disk_internal(), file_system_detach_disk_internal(), file_system_init(), and set_file_system_device().
file_system_shutdown()
void file_system_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
set_attach_device_readonly()
static int set_attach_device_readonly (int val, void * param) static
set_file_system_device()
static int set_file_system_device (int val, void * param) static
< real IEC device (opencbm)
< real IEC device (opencbm)
< filesystem
< non-tde drive/image
< non-tde drive/image
< filesystem
< filesystem
< filesystem
Referenced by set_file_system_device().
vdrive_detach_disk_image_and_free()
static void vdrive_detach_disk_image_and_free (vdrive_t * vdrive, unsigned int unit, unsigned int drive) static
Referenced by set_file_system_device().
Variable Documentation
attach_device_readonly_enabled
int attach_device_readonly_enabled[4][2] static
Referenced by attach_disk_image(), and set_attach_device_readonly().
attach_log
log_t attach_log = ((log_t)-2) static
Referenced by attach_disk_image(), detach_disk_image(), file_system_detach_disk_internal(), file_system_get_vdrive(), file_system_init(), file_system_set_serial_hooks(), and set_file_system_device().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-device8", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "FileSystemDevice8", (void *) 1  ,
      "<Type>", "Set device type for device #8 (0: None, 1: Filesystem, 2: OpenCBM)" },
    { "-device9", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "FileSystemDevice9", (void *) 1  ,
      "<Type>", "Set device type for device #9 (0: None, 1: Filesystem, 2: OpenCBM)" },
    { "-device10", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "FileSystemDevice10", (void *) 1  ,
      "<Type>", "Set device type for device #10 (0: None, 1: Filesystem, 2: OpenCBM)" },
    { "-device11", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "FileSystemDevice11", (void *) 1  ,
      "<Type>", "Set device type for device #11 (0: None, 1: Filesystem, 2: OpenCBM)" },
    { "-attach8ro", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice8d0Readonly", (resource_value_t)1,
      NULL, "Attach disk image for drive #8:0 read only" },
    { "-attach8rw", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice8d0Readonly", (resource_value_t)0,
      NULL, "Attach disk image for drive #8:0 read write (if possible)" },
    { "-attach9ro", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice9d0Readonly", (resource_value_t)1,
      NULL, "Attach disk image for drive #9:0 read only" },
    { "-attach9rw", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice9d0Readonly", (resource_value_t)0,
      NULL, "Attach disk image for drive #9:0 read write (if possible)" },
    { "-attach10ro", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice10d0Readonly", (resource_value_t)1,
      NULL, "Attach disk image for drive #10:0 read only" },
    { "-attach10rw", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice10d0Readonly", (resource_value_t)0,
      NULL, "Attach disk image for drive #10:0 read write (if possible)" },
    { "-attach11ro", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice11d0Readonly", (resource_value_t)1,
      NULL, "Attach disk image for drive #11:0 read only" },
    { "-attach11rw", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice11d0Readonly", (resource_value_t)0,
      NULL, "Attach disk image for drive #11:0 read write (if possible)" },
    { "-attach8d1ro", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice8d1Readonly", (resource_value_t)1,
      NULL, "Attach disk image for drive #8:1 read only" },
    { "-attach8d1rw", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice8d1Readonly", (resource_value_t)0,
      NULL, "Attach disk image for drive #8:1 read write (if possible)" },
    { "-attach9d1ro", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice9d1Readonly", (resource_value_t)1,
      NULL, "Attach disk image for drive #9:1 read only" },
    { "-attach9d1rw", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice9d1Readonly", (resource_value_t)0,
      NULL, "Attach disk image for drive #9:1 read write (if possible)" },
    { "-attach10d1ro", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice10d1Readonly", (resource_value_t)1,
      NULL, "Attach disk image for drive #10:1 read only" },
    { "-attach10d1rw", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice10d1Readonly", (resource_value_t)0,
      NULL, "Attach disk image for drive #10:1 read write (if possible)" },
    { "-attach11d1ro", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice11d1Readonly", (resource_value_t)1,
      NULL, "Attach disk image for drive #11:1 read only" },
    { "-attach11d1rw", SET_RESOURCE,  0 ,
      NULL, NULL, "AttachDevice11d1Readonly", (resource_value_t)0,
      NULL, "Attach disk image for drive #11:1 read write (if possible)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by file_system_cmdline_options_init().
file_system
file_system_t file_system[4] static
Referenced by file_system_get_vdrive(), file_system_init(), and file_system_shutdown().
file_system_device_enabled
int file_system_device_enabled[4] = { -1, -1, -1, -1 } static
Referenced by file_system_attach_disk_internal(), file_system_detach_disk_shutdown(), file_system_init(), and set_file_system_device().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "AttachDevice8d0Readonly", 0, RES_EVENT_SAME, NULL,
      &attach_device_readonly_enabled[0][0],
      set_attach_device_readonly, (void *)(( 8  << 8) |  0 ) },
    { "AttachDevice9d0Readonly", 0, RES_EVENT_SAME, NULL,
      &attach_device_readonly_enabled[1][0],
      set_attach_device_readonly, (void *)(( 9  << 8) |  0 ) },
    { "AttachDevice10d0Readonly", 0, RES_EVENT_SAME, NULL,
      &attach_device_readonly_enabled[2][0],
      set_attach_device_readonly, (void *)(( 10  << 8) |  0 ) },
    { "AttachDevice11d0Readonly", 0, RES_EVENT_SAME, NULL,
      &attach_device_readonly_enabled[3][0],
      set_attach_device_readonly, (void *)(( 11  << 8) |  0 ) },
    { "AttachDevice8d1Readonly", 0, RES_EVENT_SAME, NULL,
      &attach_device_readonly_enabled[0][1],
      set_attach_device_readonly, (void *)(( 8  << 8) |  1 ) },
    { "AttachDevice9d1Readonly", 0, RES_EVENT_SAME, NULL,
      &attach_device_readonly_enabled[1][1],
      set_attach_device_readonly, (void *)(( 9  << 8) |  1 ) },
    { "AttachDevice10d1Readonly", 0, RES_EVENT_SAME, NULL,
      &attach_device_readonly_enabled[2][1],
      set_attach_device_readonly, (void *)(( 10  << 8) |  1 ) },
    { "AttachDevice11d1Readonly", 0, RES_EVENT_SAME, NULL,
      &attach_device_readonly_enabled[3][1],
      set_attach_device_readonly, (void *)(( 11  << 8) |  1 ) },
    { "FileSystemDevice8",  1  ,
      RES_EVENT_STRICT, (resource_value_t) 1  ,
      &file_system_device_enabled[0],
      set_file_system_device, (void *)8 },
    { "FileSystemDevice9",  1  ,
      RES_EVENT_STRICT, (resource_value_t) 1  ,
      &file_system_device_enabled[1],
      set_file_system_device, (void *)9 },
    { "FileSystemDevice10",  1  ,
      RES_EVENT_STRICT, (resource_value_t) 1  ,
      &file_system_device_enabled[2],
      set_file_system_device, (void *)10 },
    { "FileSystemDevice11",  1  ,
      RES_EVENT_STRICT, (resource_value_t) 1  ,
      &file_system_device_enabled[3],
      set_file_system_device, (void *)11 },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by file_system_resources_init().