vsid: arch/shared/archdep_stat.c File Reference
archdep_stat.c File Reference
Simplified stat(2) call.
#include "vice.h"
#include "archdep_defs.h"
#include "lib.h"
#include "util.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "archdep_stat.h"
Functions
int archdep_stat (const char *path, size_t *len, unsigned int *isdir)
Determine the size of path and whether it's a directory.
Detailed Description
Simplified stat(2) call.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Determine if file exists, its length and if its a directory.
Function Documentation
archdep_stat()
int archdep_stat (const char * path, size_t * len, unsigned int * isdir)
Determine the size of path and whether it's a directory.
Parameters
[in] path pathname
[out] len length of file path (pass NULL to ignore)
[out] isdir path is a directory (pass NULL to ignore)
Returns
0 on success, -1 on failure
Referenced by archdep_mkdir_recursive(), command_directory_get(), fsimage_open(), m3u_parse(), mon_show_dir(), rawfile_open(), scan_directory(), and sysfile_open().