x128: vice_renderer_backend_s Struct Reference
vice_renderer_backend_s Struct Reference
A collection of methods that abstract away the underlying display API.
#include <videoarch.h>
Data Fields
void(* initialise)(video_canvas_t *canvas)
Add event handlers to the event box and create context.
void(* update_context)(video_canvas_t *canvas, unsigned int width, unsigned int height)
Creates or resizes the pixel buffer that this renderer backend is using for the screen.
void(* destroy_context)(video_canvas_t *canvas)
Clean up any resources used by this renderer backend, in preparation for destruction or recreation.
void(* refresh_rect)(video_canvas_t *canvas, unsigned int xs, unsigned int ys, unsigned int xi, unsigned int yi, unsigned int w, unsigned int h)
Render pixels in the specified rectangle.
void(* queue_redraw)(GdkFrameClock *clock, video_canvas_t *canvas)
Queue a redraw operation from the UI thread.
void(* set_palette)(video_canvas_t *canvas)
Initialize the palette for this renderer.
Detailed Description
A collection of methods that abstract away the underlying display API.
GTK3's default software rendering (Cairo) and its accelerated one (OpenGL) use very different mechanisms for displaying (possibly scaled) pixel content or incrementally updating it. These routines let us keep those differences contained.
Field Documentation
destroy_context
void(* vice_renderer_backend_s::destroy_context) (video_canvas_t *canvas)
Clean up any resources used by this renderer backend, in preparation for destruction or recreation.
Parameters
canvas The canvas whose renderer_context is to be deleted
Referenced by video_canvas_destroy().
initialise
void(* vice_renderer_backend_s::initialise) (video_canvas_t *canvas)
Add event handlers to the event box and create context.
Parameters
canvas The canvas to initialise.
Returns
The newly created widget.
Referenced by machine_window_create().
queue_redraw
void(* vice_renderer_backend_s::queue_redraw) (GdkFrameClock *clock, video_canvas_t *canvas)
Queue a redraw operation from the UI thread.
Parameters
clock The window GtkFrameClock generating the event
widget UI widget to queue a redraw for
Referenced by ui_display_main_window().
refresh_rect
void(* vice_renderer_backend_s::refresh_rect) (video_canvas_t *canvas, unsigned int xs, unsigned int ys, unsigned int xi, unsigned int yi, unsigned int w, unsigned int h)
Render pixels in the specified rectangle.
This asks the emulator core to update the renderer context.
Parameters
canvas The canvas being rendered to
xs A parameter to forward to video_canvas_render()
ys A parameter to forward to video_canvas_render()
xi X coordinate of the leftmost pixel to update
yi Y coordinate of the topmost pixel to update
w Width of the rectangle to update
h Height of the rectangle to update
Referenced by video_canvas_refresh().
set_palette
void(* vice_renderer_backend_s::set_palette) (video_canvas_t *canvas)
Initialize the palette for this renderer.
Parameters
canvas The canvas being initialized
Referenced by video_canvas_set_palette().
update_context
void(* vice_renderer_backend_s::update_context) (video_canvas_t *canvas, unsigned int width, unsigned int height)
Creates or resizes the pixel buffer that this renderer backend is using for the screen.
This is an expensive operation if the width and height have changed since the last call.
Parameters
canvas The canvas being resized or initially created.
width The new width for the machine's screen.
height The new height for the machine's screen.
Referenced by video_canvas_create(), and video_canvas_resize().
The documentation for this struct was generated from the following file:
arch/gtk3/videoarch.h