vsid: arch/gtk3/widgets/vdcmodelwidget.h File Reference
vdcmodelwidget.h File Reference
VDC settings widget - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
GtkWidget * vdc_model_widget_create (void)
Create widget to manipulate VDC settings.
void vdc_model_widget_update (GtkWidget *widget)
Update the VDC model widget.
void vdc_model_widget_set_revision_callback (void(*func)(int))
Set callback function to trigger on revision changes.
void vdc_model_widget_set_ram_callback (void(*func)(int))
Set callback function to trigger on RAM size changes.
Detailed Description
VDC settings widget - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
vdc_model_widget_create()
GtkWidget * vdc_model_widget_create (void)
Create widget to manipulate VDC settings.
Returns
GtkGrid
Referenced by create_c128_layout().
vdc_model_widget_set_ram_callback()
void vdc_model_widget_set_ram_callback (void(*)(int) func)
Set callback function to trigger on RAM size changes.
Parameters
[in] func callback
Referenced by create_c128_layout().
vdc_model_widget_set_revision_callback()
void vdc_model_widget_set_revision_callback (void(*)(int) func)
Set callback function to trigger on revision changes.
Parameters
[in] func callback
Referenced by create_c128_layout().
vdc_model_widget_update()
void vdc_model_widget_update (GtkWidget * widget)
Update the VDC model widget.
Parameters
[in,out] widget VDC model widget
Referenced by machine_model_handler_c128().