vsid: arch/shared/archdep_remove.h File Reference
archdep_remove.h File Reference
Remove a file - header.
Functions
int archdep_remove (const char *path)
Remove a file.
Detailed Description
Remove a file - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
archdep_remove()
int archdep_remove (const char * path)
Remove a file.
Parameters
[in] path file to remove
Returns
0 on success, -1 on failure
Referenced by c64_snapshot_write(), handle_close(), handle_close_action(), rawfile_remove(), resources_save(), snapshot_create(), try_uncompress_archive(), try_uncompress_lynx(), try_uncompress_with_bzip(), try_uncompress_with_gzip(), try_uncompress_with_tzx(), try_uncompress_zipcode(), util_check_filename_access(), and zfile_compress().