vsid: vdrive/vdrive-dir.c File Reference
vdrive-dir.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
#include "cbmdos.h"
#include "diskconstants.h"
#include "diskimage.h"
#include "lib.h"
#include "log.h"
#include "types.h"
#include "vdrive-bam.h"
#include "vdrive-dir.h"
#include "vdrive-iec.h"
#include "vdrive-rel.h"
#include "vdrive.h"
Functions
void vdrive_dir_init (void)
static int vdrive_dir_get_interleave (unsigned int type)
Returns the interleave for directory sectors of a given image type.
static unsigned int vdrive_dir_name_match (uint8_t *slot, uint8_t *nslot, int length, int type)
void vdrive_dir_free_chain (vdrive_t *vdrive, int t, int s)
static uint8_t * find_next_directory_sector (vdrive_dir_context_t *dir, unsigned int track, unsigned int sector)
Tries to allocate the given track/sector and link it.
void vdrive_dir_create_slot (bufferinfo_t *p, uint8_t *realname, int reallength, int filetype)
void vdrive_dir_remove_slot (vdrive_dir_context_t *dir)
void vdrive_dir_find_first_slot (vdrive_t *vdrive, const uint8_t *name, int length, unsigned int type, vdrive_dir_context_t *dir)
static unsigned int date_to_int (int year, int month, int day, int hour, int minute)
convert date/time into a single 32-bit unsigned value
uint8_t * vdrive_dir_find_next_slot (vdrive_dir_context_t *dir)
void vdrive_dir_no_a0_pads (uint8_t *ptr, int l)
int vdrive_dir_filetype (const uint8_t *name, int length)
static unsigned int asciidate_to_int (const char *p, unsigned int def)
convert CMD ASCII date format to a single value; see above
int vdrive_dir_next_directory (vdrive_t *vdrive, bufferinfo_t *b)
int vdrive_dir_first_directory (vdrive_t *vdrive, cbmdos_cmd_parse_plus_t *cmd_parse, bufferinfo_t *p)
void vdrive_dir_updatetime (vdrive_t *vdrive, uint8_t *slot)
void vdrive_dir_part_find_first_slot (vdrive_t *vdrive, const uint8_t *name, int length, unsigned int type, vdrive_dir_context_t *dir)
shamelessly duplicate dir code from above to do the partition listings
static unsigned int vdrive_dir_part_name_match (uint8_t *slot, uint8_t *nslot, int type)
uint8_t * vdrive_dir_part_find_next_slot (vdrive_dir_context_t *dir)
int vdrive_dir_part_next_directory (vdrive_t *vdrive, bufferinfo_t *b)
int vdrive_dir_part_first_directory (vdrive_t *vdrive, const uint8_t *name, int length, bufferinfo_t *p)
Variables
static log_t vdrive_dir_log = ((log_t)-1)
Function Documentation
asciidate_to_int()
static unsigned int asciidate_to_int (const char * p, unsigned int def) static
convert CMD ASCII date format to a single value; see above
MM/DD/YY HH:MM xM - : or .
01234567890123456
1111111
Referenced by vdrive_dir_first_directory().
date_to_int()
static unsigned int date_to_int (int year, int month, int day, int hour, int minute) static
convert date/time into a single 32-bit unsigned value
Referenced by asciidate_to_int(), and vdrive_dir_find_next_slot().
find_next_directory_sector()
static uint8_t * find_next_directory_sector (vdrive_dir_context_t * dir, unsigned int track, unsigned int sector) static
Tries to allocate the given track/sector and link it.
to the current directory sector of vdrive.
Returns NULL if the allocation failed.
Referenced by vdrive_dir_find_next_slot().
vdrive_dir_create_slot()
void vdrive_dir_create_slot (bufferinfo_t * p, uint8_t * realname, int reallength, int filetype)
Referenced by iec_open_write().
vdrive_dir_filetype()
int vdrive_dir_filetype (const uint8_t * name, int length)
< should match FILEIO_TYPE_xxx
< 1581 partition
Referenced by vdrive_command_scratch().
vdrive_dir_find_first_slot()
void vdrive_dir_find_first_slot (vdrive_t * vdrive, const uint8_t * name, int length, unsigned int type, vdrive_dir_context_t * dir)
Referenced by iec_open_write(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_lockunlock(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_rmdir(), vdrive_command_scratch(), vdrive_command_switchtraverse(), vdrive_command_validate_worker(), vdrive_dir_first_directory(), vdrive_iec_open(), and vdrive_rel_open_new().
vdrive_dir_find_next_slot()
uint8_t * vdrive_dir_find_next_slot (vdrive_dir_context_t * dir)
< same on CMD (year to minute)
Referenced by iec_open_write(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_lockunlock(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_rmdir(), vdrive_command_scratch(), vdrive_command_switchtraverse(), vdrive_command_validate_worker(), vdrive_dir_next_directory(), vdrive_iec_open(), and vdrive_rel_open_new().
vdrive_dir_first_directory()
int vdrive_dir_first_directory (vdrive_t * vdrive, cbmdos_cmd_parse_plus_t * cmd_parse, bufferinfo_t * p)
< should match FILEIO_TYPE_xxx
< 1581 partition
Referenced by iec_open_read_directory(), and iec_read_sequential().
vdrive_dir_free_chain()
void vdrive_dir_free_chain (vdrive_t * vdrive, int t, int s)
Todo:
FIXME: This seems to be redundant. AB19981124
Referenced by iec_close_sequential(), vdrive_command_scratch(), vdrive_dir_remove_slot(), and vdrive_rel_scratch().
vdrive_dir_get_interleave()
static int vdrive_dir_get_interleave (unsigned int type) static
Returns the interleave for directory sectors of a given image type.
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_dir_find_next_slot().
vdrive_dir_init()
void vdrive_dir_init (void)
Referenced by vdrive_init().
vdrive_dir_name_match()
static unsigned int vdrive_dir_name_match (uint8_t * slot, uint8_t * nslot, int length, int type) static
< should match FILEIO_TYPE_xxx
Referenced by vdrive_dir_find_next_slot().
vdrive_dir_next_directory()
int vdrive_dir_next_directory (vdrive_t * vdrive, bufferinfo_t * b)
< same on CMD (year to minute)
Referenced by iec_read_sequential().
vdrive_dir_no_a0_pads()
void vdrive_dir_no_a0_pads (uint8_t * ptr, int l)
Referenced by vdrive_dir_first_directory(), vdrive_dir_next_directory(), vdrive_dir_part_first_directory(), and vdrive_dir_part_next_directory().
vdrive_dir_part_find_first_slot()
void vdrive_dir_part_find_first_slot (vdrive_t * vdrive, const uint8_t * name, int length, unsigned int type, vdrive_dir_context_t * dir)
shamelessly duplicate dir code from above to do the partition listings
Referenced by vdrive_command_renamepart(), and vdrive_dir_part_first_directory().
vdrive_dir_part_find_next_slot()
uint8_t * vdrive_dir_part_find_next_slot (vdrive_dir_context_t * dir)
Referenced by vdrive_command_renamepart(), and vdrive_dir_part_next_directory().
vdrive_dir_part_first_directory()
int vdrive_dir_part_first_directory (vdrive_t * vdrive, const uint8_t * name, int length, bufferinfo_t * p)
< HD in ASCII for CMDHD
< HD in ASCII for CMDHD
Referenced by iec_open_read_directory().
vdrive_dir_part_name_match()
static unsigned int vdrive_dir_part_name_match (uint8_t * slot, uint8_t * nslot, int type) static
Referenced by vdrive_dir_part_find_next_slot().
vdrive_dir_part_next_directory()
int vdrive_dir_part_next_directory (vdrive_t * vdrive, bufferinfo_t * b)
Referenced by iec_read_sequential(), and vdrive_dir_part_first_directory().
vdrive_dir_remove_slot()
void vdrive_dir_remove_slot (vdrive_dir_context_t * dir)
Referenced by vdrive_command_rmdir(), and vdrive_command_scratch().
vdrive_dir_updatetime()
void vdrive_dir_updatetime (vdrive_t * vdrive, uint8_t * slot)
CMDHD's don't like the year > 99, it will screw up the date/time output
< same on CMD (year to minute)
Referenced by iec_close_sequential(), vdrive_command_copy(), and vdrive_command_mkdir().
Variable Documentation
vdrive_dir_log
log_t vdrive_dir_log = ((log_t)-1) static
Referenced by vdrive_dir_init().