x128: arch/gtk3/widgets/base/popupmenu.c File Reference
popupmenu.c File Reference
Gtk3 popup menu helpers.
#include "vice.h"
#include <gtk/gtk.h>
#include "hotkeys.h"
#include "uiactions.h"
#include "popupmenu.h"
Functions
static void on_action_item_activate (GtkWidget *item, gpointer action)
Handler for the 'activate' event of a UI action menu item.
static void on_custom_item_activate (GtkWidget *item, gpointer action)
Handler for the 'activate' event of a menu item with custom handler.
GtkWidget * popup_menu_item_action_new (const char *text, int action)
Create menu item that triggers a UI action.
void popup_menu_add_separator (GtkWidget *menu)
Add separator item to menu.
GtkWidget * popup_menu_nth_item (GtkWidget *menu, guint n)
Get item of menu by index.
GtkWidget * popup_menu_new (const popup_item_t *items)
Create popup menu.
Detailed Description
Gtk3 popup menu helpers.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_action_item_activate()
static void on_action_item_activate (GtkWidget * item, gpointer action) static
Handler for the 'activate' event of a UI action menu item.
Triggers UI action action.
Parameters
[in] item menu item (unused)
[in] action UI action ID
Referenced by popup_menu_item_action_new(), and popup_menu_new().
on_custom_item_activate()
static void on_custom_item_activate (GtkWidget * item, gpointer action) static
Handler for the 'activate' event of a menu item with custom handler.
Triggers UI action action.
Parameters
[in] item menu item
[in] action UI action ID
Referenced by popup_menu_new().
popup_menu_add_separator()
void popup_menu_add_separator (GtkWidget * menu)
Add separator item to menu.
Parameters
[in] menu menu
Referenced by ui_do_drive_popup().
popup_menu_item_action_new()
GtkWidget * popup_menu_item_action_new (const char * text, int action)
Create menu item that triggers a UI action.
Creates menu item to trigger action, setting the appropriate accelerator if a hotkey is defined for action.
Parameters
[in] text text for the item
[in] action UI action ID
Referenced by ui_do_drive_popup().
popup_menu_new()
GtkWidget * popup_menu_new (const popup_item_t * items)
Create popup menu.
Create popup menu from items.
Parameters
[in] items list of items for the new menu
Returns
GtkMenu
Referenced by popup_menu_new().
popup_menu_nth_item()
GtkWidget * popup_menu_nth_item (GtkWidget * menu, guint n)
Get item of menu by index.
Parameters
[in] menu popup menu
[in] n index of item to retrieve
Returns
GtkMenuItem or NULL when not found