x128: c128/c128mem.h File Reference
c128mem.h File Reference
#include "mem.h"
#include "types.h"
Macros
#define C128_RAM_SIZE 0x40000
#define C128_EDITOR_ROM_SIZE 0x1000
0x0000 - 0x0fff in kernal image
#define C128_Z80BIOS_ROM_SIZE 0x1000
0x1000 - 0x1fff in kernal image
#define C128_KERNAL_ROM_SIZE 0x2000
0x2000 - 0x3fff in kernal image
#define C128_BASIC_ROM_SIZE 0x8000
BASICLO + BASICHI.
#define C128_CHARGEN_ROM_SIZE 0x2000
#define C128_BASIC_ROM_IMAGELO_SIZE 0x4000
#define C128_BASIC_ROM_IMAGEHI_SIZE 0x4000
#define C128_KERNAL_ROM_IMAGE_SIZE 0x4000
Editor + Z80BIOS + Kernal.
#define C128_KERNAL64_ROM_SIZE 0x2000
#define C128_BASIC64_ROM_SIZE 0x2000
Functions
int c128_mem_init_resources (void)
int c128_mem_init_cmdline_options (void)
void mem_update_config (int config)
void mem_set_machine_type (unsigned type)
void mem_set_ram_config (uint8_t value)
void mem_set_ram_bank (uint8_t value)
void mem_set_vbank (int new_vbank)
void mem_set_tape_sense (int sense)
Set the tape sense status.
void mem_pla_config_changed (void)
void mem_set_write_hook (int config, int page, store_func_t *f)
void mem_read_tab_set (unsigned int base, unsigned int index, read_func_ptr_t read_func)
void mem_read_base_set (unsigned int base, unsigned int index, uint8_t *mem_ptr)
void mem_read_limit_set (unsigned int base, unsigned int index, uint32_t limit)
uint8_t ram_read (uint16_t addr)
void ram_store (uint16_t addr, uint8_t value)
uint8_t ram_peek (uint16_t addr)
uint8_t one_read (uint16_t addr)
void one_store (uint16_t addr, uint8_t value)
uint8_t one_peek (uint16_t addr)
uint8_t z80_read_zero (uint16_t addr)
z80 versions of reading and writing the zero page under mmu control.
void z80_store_zero (uint16_t addr, uint8_t value)
uint8_t z80_peek_zero (uint16_t addr)
void colorram_store (uint16_t addr, uint8_t value)
uint8_t colorram_read (uint16_t addr)
uint8_t colorram_peek (uint16_t addr)
uint8_t d7xx_read (uint16_t addr)
void d7xx_store (uint16_t addr, uint8_t value)
uint8_t lo_read (uint16_t addr)
$0200 - $3FFF: RAM (normal or shared).
void lo_store (uint16_t addr, uint8_t value)
uint8_t lo_peek (uint16_t addr)
uint8_t hi_read (uint16_t addr)
$E000 - $FFFF: RAM or Kernal.
void hi_store (uint16_t addr, uint8_t value)
uint8_t top_shared_read (uint16_t addr)
void top_shared_store (uint16_t addr, uint8_t value)
uint8_t top_shared_peek (uint16_t addr)
uint8_t editor_read (uint16_t addr)
$C000 - $CFFF: RAM (normal or shared) or Editor ROM.
void editor_store (uint16_t addr, uint8_t value)
uint8_t basic_read (uint16_t addr)
void basic_store (uint16_t addr, uint8_t value)
uint8_t kernal_read (uint16_t addr)
void kernal_store (uint16_t addr, uint8_t value)
uint8_t chargen_read (uint16_t addr)
External memory access functions.
void chargen_store (uint16_t addr, uint8_t value)
uint8_t basic_lo_read (uint16_t addr)
$4000 - $7FFF: RAM or low BASIC ROM.
void basic_lo_store (uint16_t addr, uint8_t value)
uint8_t basic_hi_read (uint16_t addr)
$8000 - $BFFF: RAM or high BASIC ROM.
void basic_hi_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d000_read (uint16_t addr)
8502 specific I/O function wrappers for 2mhz mode cycle stretching
void c128_c64io_d000_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d100_read (uint16_t addr)
void c128_c64io_d100_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d200_read (uint16_t addr)
void c128_c64io_d200_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d300_read (uint16_t addr)
void c128_c64io_d300_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d400_read (uint16_t addr)
void c128_c64io_d400_store (uint16_t addr, uint8_t value)
uint8_t c128_d5xx_read (uint16_t addr)
void c128_d5xx_store (uint16_t addr, uint8_t value)
uint8_t c128_mmu_read (uint16_t addr)
void c128_mmu_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d600_read (uint16_t addr)
void c128_c64io_d600_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_d700_read (uint16_t addr)
void c128_c64io_d700_store (uint16_t addr, uint8_t value)
uint8_t c128_colorram_read (uint16_t addr)
void c128_colorram_store (uint16_t addr, uint8_t value)
uint8_t c128_cia1_read (uint16_t addr)
void c128_cia1_store (uint16_t addr, uint8_t value)
uint8_t c128_cia2_read (uint16_t addr)
void c128_cia2_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_de00_read (uint16_t addr)
void c128_c64io_de00_store (uint16_t addr, uint8_t value)
uint8_t c128_c64io_df00_read (uint16_t addr)
void c128_c64io_df00_store (uint16_t addr, uint8_t value)
void mem_initialize_go64_memory_bank (uint8_t shared_mem)
Set up the memory map for the c64 mode.
uint8_t mem_read_without_ultimax (uint16_t addr)
add due to incompatibilities with c64mem.h
void mem_store_without_ultimax (uint16_t addr, uint8_t value)
void mem_store_without_romlh (uint16_t addr, uint8_t value)
void ram_hi_store (uint16_t addr, uint8_t value)
void mem_set_tape_write_in (int val)
Set the tape write in.
void mem_set_tape_motor_in (int val)
Set the tape motor in.
void store_bank_io (uint16_t addr, uint8_t byte)
Banked memory access functions for the monitor.
uint8_t read_bank_io (uint16_t addr)
Variables
uint8_t * ram_bank
Currently selected RAM bank.
uint8_t * dma_bank
Currently selected DMA bank.
uint8_t mem_chargen_rom [0x2000]
Macro Definition Documentation
C128_BASIC64_ROM_SIZE
#define C128_BASIC64_ROM_SIZE 0x2000
C128_BASIC_ROM_IMAGEHI_SIZE
#define C128_BASIC_ROM_IMAGEHI_SIZE 0x4000
C128_BASIC_ROM_IMAGELO_SIZE
#define C128_BASIC_ROM_IMAGELO_SIZE 0x4000
C128_BASIC_ROM_SIZE
#define C128_BASIC_ROM_SIZE 0x8000
BASICLO + BASICHI.
C128_CHARGEN_ROM_SIZE
#define C128_CHARGEN_ROM_SIZE 0x2000
C128_EDITOR_ROM_SIZE
#define C128_EDITOR_ROM_SIZE 0x1000
0x0000 - 0x0fff in kernal image
C128_KERNAL64_ROM_SIZE
#define C128_KERNAL64_ROM_SIZE 0x2000
C128_KERNAL_ROM_IMAGE_SIZE
#define C128_KERNAL_ROM_IMAGE_SIZE 0x4000
Editor + Z80BIOS + Kernal.
C128_KERNAL_ROM_SIZE
#define C128_KERNAL_ROM_SIZE 0x2000
0x2000 - 0x3fff in kernal image
C128_RAM_SIZE
#define C128_RAM_SIZE 0x40000
C128_Z80BIOS_ROM_SIZE
#define C128_Z80BIOS_ROM_SIZE 0x1000
0x1000 - 0x1fff in kernal image
Function Documentation
basic_hi_read()
uint8_t basic_hi_read (uint16_t addr)
$8000 - $BFFF: RAM or high BASIC ROM.
Referenced by c128meminit(), and z80mem_mid_rom_area_read().
basic_hi_store()
void basic_hi_store (uint16_t addr, uint8_t value)
Todo:
FIXME: basic replacement and dma?
Referenced by c128meminit(), and z80mem_mid_rom_area_store().
basic_lo_read()
uint8_t basic_lo_read (uint16_t addr)
$4000 - $7FFF: RAM or low BASIC ROM.
Referenced by c128meminit(), and z80mem_lo_rom_area_read().
basic_lo_store()
void basic_lo_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and z80mem_lo_rom_area_store().
basic_read()
uint8_t basic_read (uint16_t addr)
basic_store()
void basic_store (uint16_t addr, uint8_t value)
c128_c64io_d000_read()
uint8_t c128_c64io_d000_read (uint16_t addr)
8502 specific I/O function wrappers for 2mhz mode cycle stretching
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d000_store()
void c128_c64io_d000_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d100_read()
uint8_t c128_c64io_d100_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d100_store()
void c128_c64io_d100_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d200_read()
uint8_t c128_c64io_d200_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d200_store()
void c128_c64io_d200_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d300_read()
uint8_t c128_c64io_d300_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d300_store()
void c128_c64io_d300_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d400_read()
uint8_t c128_c64io_d400_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d400_store()
void c128_c64io_d400_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d600_read()
uint8_t c128_c64io_d600_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d600_store()
void c128_c64io_d600_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d700_read()
uint8_t c128_c64io_d700_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_d700_store()
void c128_c64io_d700_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_de00_read()
uint8_t c128_c64io_de00_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_de00_store()
void c128_c64io_de00_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_df00_read()
uint8_t c128_c64io_df00_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_c64io_df00_store()
void c128_c64io_df00_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_cia1_read()
uint8_t c128_cia1_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_cia1_store()
void c128_cia1_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_cia2_read()
uint8_t c128_cia2_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_cia2_store()
void c128_cia2_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_colorram_read()
uint8_t c128_colorram_read (uint16_t addr)
Referenced by c128meminit(), and mem_initialize_memory().
c128_colorram_store()
void c128_colorram_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and mem_initialize_memory().
c128_d5xx_read()
uint8_t c128_d5xx_read (uint16_t addr)
Referenced by mem_initialize_memory().
c128_d5xx_store()
void c128_d5xx_store (uint16_t addr, uint8_t value)
Referenced by mem_initialize_memory().
c128_mem_init_cmdline_options()
int c128_mem_init_cmdline_options (void)
c128_mem_init_resources()
int c128_mem_init_resources (void)
c128_mmu_read()
uint8_t c128_mmu_read (uint16_t addr)
Referenced by c128meminit().
c128_mmu_store()
void c128_mmu_store (uint16_t addr, uint8_t value)
Referenced by c128meminit().
chargen_read()
uint8_t chargen_read (uint16_t addr)
External memory access functions.
Referenced by c128meminit(), mem_initialize_memory(), and z80mem_initialize().
chargen_store()
void chargen_store (uint16_t addr, uint8_t value)
colorram_peek()
uint8_t colorram_peek (uint16_t addr)
colorram_read()
uint8_t colorram_read (uint16_t addr)
Referenced by c128_colorram_read(), c64mode_colorram_read(), peek_bank_io(), read_bank_io(), z80_colorram_read(), z80mem_initialize(), and z80mem_peek_with_config().
colorram_store()
void colorram_store (uint16_t addr, uint8_t value)
Referenced by c128_colorram_store(), c64mode_colorram_store(), store_bank_io(), z80_colorram_store(), and z80mem_initialize().
d7xx_read()
uint8_t d7xx_read (uint16_t addr)
d7xx_store()
void d7xx_store (uint16_t addr, uint8_t value)
editor_read()
uint8_t editor_read (uint16_t addr)
$C000 - $CFFF: RAM (normal or shared) or Editor ROM.
Referenced by c128meminit(), and z80mem_editor_rom_area_read().
editor_store()
void editor_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), and z80mem_editor_rom_area_store().
hi_read()
uint8_t hi_read (uint16_t addr)
$E000 - $FFFF: RAM or Kernal.
Referenced by c128meminit(), mmu_ffxx_read(), and z80mem_hi_rom_area_read().
hi_store()
void hi_store (uint16_t addr, uint8_t value)
Todo:
FIXME: kernal replacement and dma?
Referenced by c128meminit(), mmu_ffxx_store(), z80mem_chargen_rom_area_store(), and z80mem_hi_rom_area_store().
kernal_read()
uint8_t kernal_read (uint16_t addr)
kernal_store()
void kernal_store (uint16_t addr, uint8_t value)
lo_peek()
uint8_t lo_peek (uint16_t addr)
Referenced by mem_peek_with_config_c128(), and z80mem_peek_with_config().
lo_read()
uint8_t lo_read (uint16_t addr)
$0200 - $3FFF: RAM (normal or shared).
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU shared ram translation.
Referenced by c128meminit(), c64mode_colorram_read(), mem_initialize_memory(), and z80mem_initialize().
lo_store()
void lo_store (uint16_t addr, uint8_t value)
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU shared ram translation.
Referenced by c128meminit(), c64mode_colorram_store(), mem_initialize_memory(), and z80mem_initialize().
mem_initialize_go64_memory_bank()
void mem_initialize_go64_memory_bank (uint8_t shared_mem)
Set up the memory map for the c64 mode.
Todo:
FIXME: Do we need this again?
Referenced by mmu_switch_to_c128mode(), and mmu_switch_to_c64mode().
mem_pla_config_changed()
void mem_pla_config_changed (void)
Referenced by mem_caps_key_event(), mem_set_machine_type(), mem_set_tape_motor_in(), mem_set_tape_sense(), mem_set_tape_write_in(), mmu_4080_key_event(), and zero_store().
mem_read_base_set()
void mem_read_base_set (unsigned int base, unsigned int index, uint8_t * mem_ptr)
Referenced by c128meminit().
mem_read_limit_set()
void mem_read_limit_set (unsigned int base, unsigned int index, uint32_t limit)
Referenced by c128meminit().
mem_read_tab_set()
void mem_read_tab_set (unsigned int base, unsigned int index, read_func_ptr_t read_func)
Referenced by c128meminit().
mem_read_without_ultimax()
uint8_t mem_read_without_ultimax (uint16_t addr)
add due to incompatibilities with c64mem.h
mem_set_machine_type()
void mem_set_machine_type (unsigned type)
Referenced by set_machine_type().
mem_set_ram_bank()
void mem_set_ram_bank (uint8_t value)
mem_set_ram_config()
void mem_set_ram_config (uint8_t value)
Referenced by mmu_store().
mem_set_tape_motor_in()
void mem_set_tape_motor_in (int val)
Set the tape motor in.
mem_set_tape_sense()
void mem_set_tape_sense (int sense)
Set the tape sense status.
mem_set_tape_write_in()
void mem_set_tape_write_in (int val)
Set the tape write in.
mem_set_vbank()
void mem_set_vbank (int new_vbank)
mem_set_write_hook()
void mem_set_write_hook (int config, int page, store_func_t * f)
Referenced by c128meminit(), and mem_initialize_memory().
mem_store_without_romlh()
void mem_store_without_romlh (uint16_t addr, uint8_t value)
mem_store_without_ultimax()
void mem_store_without_ultimax (uint16_t addr, uint8_t value)
mem_update_config()
void mem_update_config (int config)
Referenced by mmu_switch_to_c128mode(), and mmu_switch_to_c64mode().
one_peek()
uint8_t one_peek (uint16_t addr)
Referenced by mem_peek_with_config_c128(), ram_peek_c64(), and z80mem_peek_with_config().
one_read()
uint8_t one_read (uint16_t addr)
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU page 1 translation.
Referenced by c128meminit(), mem_initialize_memory(), and z80mem_initialize().
one_store()
void one_store (uint16_t addr, uint8_t value)
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU page 1 translation.
Referenced by c128meminit(), mem_initialize_memory(), and z80mem_initialize().
ram_hi_store()
void ram_hi_store (uint16_t addr, uint8_t value)
ram_peek()
uint8_t ram_peek (uint16_t addr)
Referenced by mem_peek_with_config_c128(), z80mem_lo_rom_area_peek(), z80mem_mid_rom_area_peek(), and z80mem_peek_with_config().
ram_read()
uint8_t ram_read (uint16_t addr)
Referenced by c128meminit(), mem_initialize_memory(), z80mem_initialize(), z80mem_lo_rom_area_read(), and z80mem_mid_rom_area_read().
ram_store()
void ram_store (uint16_t addr, uint8_t value)
Todo:
FIXME: basic replacement and dma?
Referenced by c128meminit(), external_function_rom_store(), internal_function_rom_store(), mem_initialize_memory(), z80mem_initialize(), z80mem_lo_rom_area_store(), and z80mem_mid_rom_area_store().
read_bank_io()
uint8_t read_bank_io (uint16_t addr)
Referenced by mem_bank_read().
store_bank_io()
void store_bank_io (uint16_t addr, uint8_t byte)
Banked memory access functions for the monitor.
Todo:
FIXME: peek, cartridge support
Referenced by mem_bank_write().
top_shared_peek()
uint8_t top_shared_peek (uint16_t addr)
Referenced by mem_peek_with_config_c128(), z80mem_chargen_rom_area_peek(), z80mem_editor_rom_area_peek(), z80mem_hi_rom_area_peek(), and z80mem_peek_with_config().
top_shared_read()
uint8_t top_shared_read (uint16_t addr)
Referenced by c128meminit(), mem_initialize_memory(), mmu_ffxx_read(), z80_io_ram_bank0_read(), z80mem_chargen_rom_area_read(), z80mem_editor_rom_area_read(), z80mem_hi_rom_area_read(), and z80mem_initialize().
top_shared_store()
void top_shared_store (uint16_t addr, uint8_t value)
Referenced by c128meminit(), c64mode_ffxx_store(), external_function_top_shared_store(), internal_function_top_shared_store(), mem_initialize_memory(), z80_c64mode_ffxx_store(), z80_io_ram_bank0_store(), z80mem_chargen_rom_area_store(), z80mem_editor_rom_area_store(), z80mem_hi_rom_area_store(), and z80mem_initialize().
z80_peek_zero()
uint8_t z80_peek_zero (uint16_t addr)
Referenced by z80mem_peek_with_config().
z80_read_zero()
uint8_t z80_read_zero (uint16_t addr)
z80 versions of reading and writing the zero page under mmu control.
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU page 0 translation.
Referenced by z80mem_initialize().
z80_store_zero()
void z80_store_zero (uint16_t addr, uint8_t value)
Todo:
FIXME: it is assumed that DMA transfers do NOT follow the MMU page 0 translation.
Referenced by z80mem_initialize().
Variable Documentation
dma_bank
uint8_t* dma_bank extern
Currently selected DMA bank.
Referenced by basic_hi_store(), basic_lo_store(), c64mode_ffxx_store(), c64mode_vicii_mem_vbank_39xx_lo_store(), c64mode_vicii_mem_vbank_39xx_ram_store(), c64mode_vicii_mem_vbank_39xx_top_shared_store(), c64mode_vicii_mem_vbank_3fxx_lo_store(), c64mode_vicii_mem_vbank_3fxx_ram_store(), c64mode_vicii_mem_vbank_3fxx_top_shared_store(), c64mode_vicii_mem_vbank_lo_store(), c64mode_vicii_mem_vbank_ram_store(), c64mode_vicii_mem_vbank_top_shared_store(), hi_store(), lo_read(), lo_store(), mem_set_ram_config(), mmu_set_dma_bank(), one_read(), one_store(), ram_hi_store(), ram_read(), ram_store(), top_shared_read(), top_shared_store(), z80_read_zero(), z80_store_zero(), zero_read_dma(), and zero_store_dma().
mem_chargen_rom
uint8_t mem_chargen_rom[0x2000] extern
Referenced by c128rom_chargen_setup(), mem_bank_read(), mem_initialize_memory(), mem_peek_with_config_c64(), mem_read_rom_snapshot_module(), mem_update_chargen(), and mem_write_rom_snapshot_module().
ram_bank
uint8_t* ram_bank extern
Currently selected RAM bank.
Referenced by basic_hi_store(), basic_lo_store(), mem_initialize_go64_memory_bank(), mem_initialize_memory(), mem_peek_with_config_c128(), mmu_set_ram_bank(), ram_hi_store(), ram_peek(), ram_read(), ram_store(), and z80mem_peek_with_config().