x128: vicii/vicii-sprites.c File Reference
vicii-sprites.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lib.h"
#include "raster-cache.h"
#include "raster-changes.h"
#include "raster-sprite-status.h"
#include "raster-sprite.h"
#include "types.h"
#include "vicii-sprites.h"
#include "viciitypes.h"
#include "viewport.h"
Macros
#define X_OFFSET vicii.screen_leftborderwidth
margin definitions of where sprite data fetches interfere with
#define SPRITE_EXPANDED_REPEAT_PIXELS_START(n)
#define SPRITE_NORMAL_REPEAT_PIXELS_START(n)
#define SPRITE_REPEAT_PIXELS_END(n)
#define SPRITE_REPEAT_BEGIN(n) (SPRITE_REPEAT_PIXELS_END(n) - 0xc)
where the sprite pixels start repeating
#define SPRITE_DISPLAY_PREVIOUS_PATTERN (0x14c + X_OFFSET)
maximum x where sprite data fetched in the previous line is displayed
#define SPRITE_DISPLAY_IMMEDIATE_DATA_FETCHED(n) (0x156 + X_OFFSET + n * 0x10)
Minimum X where sprite starts immediately with data already fetched.
#define SF_END_3 { -1, -1, 0, 0 }, { -1, -1, 0, 0 }, { -1, -1, 0, 0 }
Three sprite fetch table entry terminators.
#define SF_END_2 { -1, -1, 0, 0 }, { -1, -1, 0, 0 }
Two sprite fetch table entry terminators.
#define SF_END_1 { -1, -1, 0, 0 }
A single Schwarzenegger.
#define SPRITE_PIXEL(do_draw, sprite_bit, imgptr, collmskptr, pos, color, collmsk_return)
Sprite drawing macros.
#define _SPRITE_MASK(msk, gfxmsk, size, sprite_bit, imgptr, collmskptr, color, collmsk_return, DRAW)
Hires sprites.
#define SPRITE_MASK(msk, gfxmsk, size, sprite_bit, imgptr, collmskptr, color, collmsk_return)
#define _MCSPRITE_MASK(mcmsk, gfxmsk, trmsk, size, sprite_bit, imgptr, collmskptr, pixel_table, collmsk_return, DRAW)
Multicolor sprites.
#define MCSPRITE_MASK(mcmsk, gfxmsk, trmsk, size, sprite_bit, imgptr, collmskptr, pixel_table, collmsk_return)
#define _MCSPRITE_DOUBLE_MASK(mcmsk, gfxmsk, trmsk, size, sprite_bit, imgptr, collmskptr, pixel_table, collmsk_return, DRAW)
#define MCSPRITE_DOUBLE_MASK(mcmsk, gfxmsk, trmsk, size, sprite_bit, imgptr, collmskptr, pixel_table, collmsk_return)
#define TRIM_MSK(msk, size)
Functions
static void init_drawing_tables (void)
static void draw_hires_sprite_expanded (uint8_t *data_ptr, int n, uint8_t *msk_ptr, uint8_t *ptr, int lshift, uint8_t *sptr, raster_sprite_status_t *sprite_status, int sprite_xs, int sprite_xe)
static void draw_hires_sprite_normal (uint8_t *data_ptr, int n, uint8_t *msk_ptr, uint8_t *ptr, int lshift, uint8_t *sptr, raster_sprite_status_t *sprite_status, int sprite_xs, int sprite_xe)
static void draw_hires_sprite (uint8_t *gfx_msk_ptr, uint8_t *data_ptr, int n, uint8_t *msk_ptr, uint8_t *ptr, int lshift, uint8_t *sptr, raster_sprite_status_t *sprite_status, int sprite_xs, int sprite_xe)
Draw one hires sprite.
static void draw_mc_sprite_expanded (uint8_t *data_ptr, int n, uint32_t *c, uint8_t *msk_ptr, uint8_t *ptr, int lshift, uint8_t *sptr, raster_sprite_status_t *sprite_status, int sprite_xs, int sprite_xe)
static void draw_mc_sprite_normal (uint8_t *data_ptr, int n, uint32_t *c, uint8_t *msk_ptr, uint8_t *ptr, int lshift, uint8_t *sptr, raster_sprite_status_t *sprite_status, int sprite_xs, int sprite_xe)
static void draw_mc_sprite (uint8_t *gfx_msk_ptr, uint8_t *data_ptr, int n, uint8_t *msk_ptr, uint8_t *ptr, int lshift, uint8_t *sptr, raster_sprite_status_t *sprite_status, int sprite_xs, int sprite_xe)
Draw one multicolor sprite.
static void calculate_idle_sprite_data (uint8_t *data, unsigned int n)
static void draw_sprite_partial (uint8_t *line_ptr, uint8_t *gfx_msk_ptr, int sprite_xs, int sprite_xe, raster_sprite_status_t *sprite_status, int n, int sprite_offset)
static void draw_all_sprites_partial (uint8_t *line_ptr, uint8_t *gfx_msk_ptr, int xs, int xe)
static void draw_all_sprites (uint8_t *line_ptr, uint8_t *gfx_msk_ptr)
static void update_cached_sprite_collisions (raster_cache_t *cache)
void vicii_sprites_init (void)
void vicii_sprites_set_x_position (unsigned int num, int new_x, int raster_x)
void vicii_sprites_reset_xshift (void)
void vicii_sprites_reset_sprline (void)
void vicii_sprites_init_sprline (void)
void vicii_sprites_shutdown (void)
int vicii_sprite_offset (void)
Variables
const vicii_sprites_fetch_t vicii_sprites_fetch_table [256][4]
Sprite fetch data.
const int vicii_sprites_crunch_table [64]
static uint8_t * sprline = NULL
static uint16_t sprite_doubling_table [256]
Sprite tables.
static uint8_t mcsprtable [256]
Macro Definition Documentation
_MCSPRITE_DOUBLE_MASK
#define _MCSPRITE_DOUBLE_MASK (mcmsk, gfxmsk, trmsk, size, sprite_bit, imgptr, collmskptr, pixel_table, collmsk_return, DRAW)
Value:
    do {                                                              \
        uint32_t __m;                                                    \
        int __p, __i;                                                 \
                                                                      \
        for (__m = 1U << ((size) - 1), __p = 0; __p < (size);         \
             __p += 4, (mcmsk) <<= 2, (trmsk) <<= 4) {                \
            uint8_t __c;                                                 \
            uint8_t __t;                                                 \
                                                                      \
            __c = (uint8_t)(((mcmsk) >> 22) & 0x3);                      \
            __t = (uint8_t)(((trmsk) >> (size - 4)) & 0xf);              \
                                                                      \
            for (__i = 0; __i < 4; __i++, __m >>= 1, __t <<= 1) {     \
                if (__c && (__t & 0x8)) {                             \
                    if ((gfxmsk) & __m) {                             \
                        DRAW(0, sprite_bit, imgptr, collmskptr,       \
                             __p + __i, pixel_table[__c],             \
                             collmsk_return);                         \
                    } else {                                          \
                        DRAW(1, sprite_bit, imgptr, collmskptr,       \
                             __p + __i, pixel_table[__c],             \
                             collmsk_return);                         \
                    }                                                 \
                }                                                     \
            }                                                         \
        }                                                             \
    } while (0)
_MCSPRITE_MASK
#define _MCSPRITE_MASK (mcmsk, gfxmsk, trmsk, size, sprite_bit, imgptr, collmskptr, pixel_table, collmsk_return, DRAW)
Value:
    do {                                                                 \
        uint32_t __m;                                                       \
        int __p;                                                         \
                                                                         \
        for (__m = 1 << ((size) - 1), __p = 0;                           \
             __p < (size);                                               \
             __p += 2, __m >>= 2, (mcmsk) <<= 2, (trmsk) <<= 2) {        \
            uint8_t __c, __t;                                               \
                                                                         \
            __c = (uint8_t)(((mcmsk) >> 22) & 0x3);                         \
            __t = (uint8_t)(((trmsk) >> 22) & 0x3);                         \
                                                                         \
            if (__c) {                                                   \
                if (__t & 2) {                                           \
                    if ((gfxmsk) & __m) {                                \
                        DRAW(0, sprite_bit, imgptr, collmskptr, __p,     \
                             pixel_table[__c], collmsk_return);          \
                    } else {                                             \
                        DRAW(1, sprite_bit, imgptr, collmskptr, __p,     \
                             pixel_table[__c], collmsk_return);          \
                    }                                                    \
                }                                                        \
                                                                         \
                if (__t & 1) {                                           \
                    if ((gfxmsk) & (__m >> 1)) {                         \
                        DRAW(0, sprite_bit, imgptr, collmskptr, __p + 1, \
                             pixel_table[__c], collmsk_return);          \
                    } else {                                             \
                        DRAW(1, sprite_bit, imgptr, collmskptr, __p + 1, \
                             pixel_table[__c], collmsk_return);          \
                    }                                                    \
                }                                                        \
            }                                                            \
        }                                                                \
    } while (0)
Multicolor sprites.
_SPRITE_MASK
#define _SPRITE_MASK (msk, gfxmsk, size, sprite_bit, imgptr, collmskptr, color, collmsk_return, DRAW)
Value:
    do {                                                         \
        uint32_t __m;                                               \
        int __p;                                                 \
                                                                 \
        for (__m = 1 << ((size) - 1), __p = 0;                   \
             __p < (size);                                       \
             __p++, __m >>= 1) {                                 \
            if ((msk) & __m) {                                   \
                if ((gfxmsk) & __m) {                            \
                    DRAW(0, sprite_bit, imgptr, collmskptr, __p, \
                         color, collmsk_return);                 \
                } else {                                         \
                    DRAW(1, sprite_bit, imgptr, collmskptr, __p, \
                         color, collmsk_return); }               \
            }                                                    \
        }                                                        \
    } while (0)
Hires sprites.
MCSPRITE_DOUBLE_MASK
#define MCSPRITE_DOUBLE_MASK (mcmsk, gfxmsk, trmsk, size, sprite_bit, imgptr, collmskptr, pixel_table, collmsk_return)
Value:
    _MCSPRITE_DOUBLE_MASK(mcmsk, gfxmsk, trmsk, size, sprite_bit, imgptr,   \
                          collmskptr, pixel_table, collmsk_return,          \
                          SPRITE_PIXEL)
MCSPRITE_MASK
#define MCSPRITE_MASK (mcmsk, gfxmsk, trmsk, size, sprite_bit, imgptr, collmskptr, pixel_table, collmsk_return)
Value:
    _MCSPRITE_MASK(mcmsk, gfxmsk, trmsk, size, sprite_bit, imgptr,    \
                   collmskptr, pixel_table, collmsk_return,           \
                   SPRITE_PIXEL)
SF_END_1
#define SF_END_1 { -1, -1, 0, 0 }
A single Schwarzenegger.
SF_END_2
#define SF_END_2 { -1, -1, 0, 0 }, { -1, -1, 0, 0 }
Two sprite fetch table entry terminators.
SF_END_3
#define SF_END_3 { -1, -1, 0, 0 }, { -1, -1, 0, 0 }, { -1, -1, 0, 0 }
Three sprite fetch table entry terminators.
SPRITE_DISPLAY_IMMEDIATE_DATA_FETCHED
#define SPRITE_DISPLAY_IMMEDIATE_DATA_FETCHED (n) (0x156 + X_OFFSET + n * 0x10)
Minimum X where sprite starts immediately with data already fetched.
SPRITE_DISPLAY_PREVIOUS_PATTERN
#define SPRITE_DISPLAY_PREVIOUS_PATTERN (0x14c + X_OFFSET)
maximum x where sprite data fetched in the previous line is displayed
SPRITE_EXPANDED_REPEAT_PIXELS_START
#define SPRITE_EXPANDED_REPEAT_PIXELS_START (n)
Value:
                                                (vicii.sprite_wrap_x < 0x200 ? \
                                                (0x11a + X_OFFSET + n * 0x10) : \
                                                (0x122 + X_OFFSET + n * 0x10))
SPRITE_MASK
#define SPRITE_MASK (msk, gfxmsk, size, sprite_bit, imgptr, collmskptr, color, collmsk_return)
Value:
    _SPRITE_MASK(msk, gfxmsk, size, sprite_bit, imgptr, collmskptr, \
                 color, collmsk_return, SPRITE_PIXEL)
SPRITE_NORMAL_REPEAT_PIXELS_START
#define SPRITE_NORMAL_REPEAT_PIXELS_START (n)
Value:
                                              (vicii.sprite_wrap_x < 0x200 ? \
                                              (0x132 + X_OFFSET + n * 0x10) : \
                                              (0x13a + X_OFFSET + n * 0x10))
SPRITE_PIXEL
#define SPRITE_PIXEL (do_draw, sprite_bit, imgptr, collmskptr, pos, color, collmsk_return)
Value:
    do {                                                      \
        if ((do_draw) && (collmskptr)[(pos)] == 0) {          \
            (imgptr)[(pos)] = (uint8_t)(color); }                \
        (collmsk_return) |= (collmskptr)[(pos)];              \
        (collmskptr)[(pos)] |= (sprite_bit);                  \
    } while (0)
Sprite drawing macros.
SPRITE_REPEAT_BEGIN
#define SPRITE_REPEAT_BEGIN (n) (SPRITE_REPEAT_PIXELS_END(n) - 0xc)
where the sprite pixels start repeating
SPRITE_REPEAT_PIXELS_END
#define SPRITE_REPEAT_PIXELS_END (n)
Value:
                                     (vicii.sprite_wrap_x < 0x200 ? \
                                     (0x157 + X_OFFSET + n * 0x10) :  \
                                     (0x15f + X_OFFSET + n * 0x10))
TRIM_MSK
#define TRIM_MSK (msk, size)
Value:
    do {                                                                    \
        int trm_msk_i;                                                              \
        int display_width = (MIN(sprite_xe + 1, size) - MAX(0, sprite_xs)); \
        msk = 0;                                                            \
        if (display_width > 0) {                                            \
            for (trm_msk_i = 0; trm_msk_i < display_width; trm_msk_i++) {                           \
                msk = (msk << 1) | 1;                                       \
            }                                                               \
            for (trm_msk_i = 0; trm_msk_i < size - sprite_xe - 1; trm_msk_i++) {                    \
                msk <<= 1;                                                  \
            }                                                               \
        }                                                                   \
    } while (0)
X_OFFSET
#define X_OFFSET vicii.screen_leftborderwidth
margin definitions of where sprite data fetches interfere with
actual sprite data display, resulting in repeated pixels or
ineffective sprite pattern data fetches
sprite #n repeats pixel SPRITE_REPEAT_BEGIN(n)-1 up to SPRITE_REPEAT_BEGIN(n)+6
no display from SPRITE_REPEAT_BEGIN(n)+7 to SPRITE_REPEAT_BEGIN(n)+11
Function Documentation
calculate_idle_sprite_data()
static void calculate_idle_sprite_data (uint8_t * data, unsigned int n) inline static
Referenced by draw_sprite_partial().
draw_all_sprites()
static void draw_all_sprites (uint8_t * line_ptr, uint8_t * gfx_msk_ptr) static
Referenced by vicii_sprites_init().
draw_all_sprites_partial()
static void draw_all_sprites_partial (uint8_t * line_ptr, uint8_t * gfx_msk_ptr, int xs, int xe) static
Referenced by draw_all_sprites(), and vicii_sprites_init().
draw_hires_sprite()
static void draw_hires_sprite (uint8_t * gfx_msk_ptr, uint8_t * data_ptr, int n, uint8_t * msk_ptr, uint8_t * ptr, int lshift, uint8_t * sptr, raster_sprite_status_t * sprite_status, int sprite_xs, int sprite_xe) inline static
Draw one hires sprite.
Referenced by draw_sprite_partial().
draw_hires_sprite_expanded()
static void draw_hires_sprite_expanded (uint8_t * data_ptr, int n, uint8_t * msk_ptr, uint8_t * ptr, int lshift, uint8_t * sptr, raster_sprite_status_t * sprite_status, int sprite_xs, int sprite_xe) inline static
Referenced by draw_hires_sprite().
draw_hires_sprite_normal()
static void draw_hires_sprite_normal (uint8_t * data_ptr, int n, uint8_t * msk_ptr, uint8_t * ptr, int lshift, uint8_t * sptr, raster_sprite_status_t * sprite_status, int sprite_xs, int sprite_xe) inline static
Referenced by draw_hires_sprite().
draw_mc_sprite()
static void draw_mc_sprite (uint8_t * gfx_msk_ptr, uint8_t * data_ptr, int n, uint8_t * msk_ptr, uint8_t * ptr, int lshift, uint8_t * sptr, raster_sprite_status_t * sprite_status, int sprite_xs, int sprite_xe) inline static
Draw one multicolor sprite.
Referenced by draw_sprite_partial().
draw_mc_sprite_expanded()
static void draw_mc_sprite_expanded (uint8_t * data_ptr, int n, uint32_t * c, uint8_t * msk_ptr, uint8_t * ptr, int lshift, uint8_t * sptr, raster_sprite_status_t * sprite_status, int sprite_xs, int sprite_xe) inline static
Referenced by draw_mc_sprite().
draw_mc_sprite_normal()
static void draw_mc_sprite_normal (uint8_t * data_ptr, int n, uint32_t * c, uint8_t * msk_ptr, uint8_t * ptr, int lshift, uint8_t * sptr, raster_sprite_status_t * sprite_status, int sprite_xs, int sprite_xe) inline static
Referenced by draw_mc_sprite().
draw_sprite_partial()
static void draw_sprite_partial (uint8_t * line_ptr, uint8_t * gfx_msk_ptr, int sprite_xs, int sprite_xe, raster_sprite_status_t * sprite_status, int n, int sprite_offset) static
< expanded sprite in bug area
Referenced by draw_all_sprites_partial().
init_drawing_tables()
static void init_drawing_tables (void) static
Referenced by vicii_sprites_init().
update_cached_sprite_collisions()
static void update_cached_sprite_collisions (raster_cache_t * cache) static
Referenced by vicii_sprites_init().
vicii_sprite_offset()
int vicii_sprite_offset (void)
Referenced by init_raster(), vicii_reset_registers(), and vicii_sprites_set_x_position().
vicii_sprites_init()
void vicii_sprites_init (void)
Referenced by vicii_init().
vicii_sprites_init_sprline()
void vicii_sprites_init_sprline (void)
Referenced by vicii_timing_set().
vicii_sprites_reset_sprline()
void vicii_sprites_reset_sprline (void)
Referenced by handle_check_sprite_dma().
vicii_sprites_reset_xshift()
void vicii_sprites_reset_xshift (void)
Referenced by vicii_raster_draw_alarm_handler().
vicii_sprites_set_x_position()
void vicii_sprites_set_x_position (unsigned int num, int new_x, int raster_x)
Referenced by store_sprite_x_position_lsb(), store_sprite_x_position_msb(), and vicii_snapshot_read_module().
vicii_sprites_shutdown()
void vicii_sprites_shutdown (void)
Referenced by vicii_shutdown().
Variable Documentation
mcsprtable
uint8_t mcsprtable[256] static
Referenced by draw_mc_sprite_expanded(), draw_mc_sprite_normal(), and init_drawing_tables().
sprite_doubling_table
uint16_t sprite_doubling_table[256] static
Sprite tables.
Referenced by draw_hires_sprite_expanded(), draw_mc_sprite_expanded(), and init_drawing_tables().
sprline
uint8_t* sprline = NULL static
Referenced by draw_sprite_partial(), vicii_sprites_init_sprline(), vicii_sprites_reset_sprline(), and vicii_sprites_shutdown().
vicii_sprites_crunch_table
const int vicii_sprites_crunch_table[64]
Initial value:
=
{
     1,   4,   3,
     4,   1,   0,
    -1,   0,   1,
     4,   3,   4,
     1,   8,   7,
     8,   1,   4,
     3,   4,   1,
     0,  -1,   0,
     1,   4,   3,
     4,   1,  -8,
    -9,  -8,   1,
     4,   3,   4,
     1,   0,  -1,
     0,   1,   4,
     3,   4,   1,
     8,   7,   8,
     1,   4,   3,
     4,   1,   0,
    -1,   0,   1,
     4,   3,   4,
     1, -40, -41,
     0
}
Referenced by d017_store().
vicii_sprites_fetch_table
const vicii_sprites_fetch_t vicii_sprites_fetch_table[256][4]
Sprite fetch data.
!
Todo:
FIXME: This can do with some proper explanation!
Referenced by handle_check_sprite_dma(), handle_fetch_sprite(), and vicii_snapshot_read_module().