vsid: arch/gtk3/widgets/statusbarrecordingwidget.h File Reference
statusbarrecordingwidget.h File Reference
Widget to display and control recording of events/audio/video - header.
#include <gtk/gtk.h>
Functions
GtkWidget * statusbar_recording_widget_create (void)
Create recording status widget.
void statusbar_recording_widget_set_recording_status (GtkWidget *widget, int status)
Set recording status.
void statusbar_recording_widget_set_time (GtkWidget *widget, unsigned int current, unsigned int total)
Update recording/playback time display.
void statusbar_recording_widget_set_event_playback (GtkWidget *widget, char *version)
Set event playback status.
void statusbar_recording_widget_hide_all (GtkWidget *widget, guint timeout)
Clear the labels and hide the button after timeout seconds.
Detailed Description
Widget to display and control recording of events/audio/video - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
statusbar_recording_widget_create()
GtkWidget * statusbar_recording_widget_create (void)
Create recording status widget.
Generate a widget to show on the statusbar to display recording state.
Returns
GtkGrid
gtk_widget_set_hexpand(label, TRUE);
Referenced by ui_statusbar_create().
statusbar_recording_widget_hide_all()
void statusbar_recording_widget_hide_all (GtkWidget * widget, guint timeout)
Clear the labels and hide the button after timeout seconds.
Use a timeout of 0 to immediately clear the labels and hide the button, skipping timer setup.
Parameters
[in,out] widget recording widget
[in] timeout timeout in seconds
Referenced by on_stop_clicked(), and ui_media_stop_recording().
statusbar_recording_widget_set_event_playback()
void statusbar_recording_widget_set_event_playback (GtkWidget * widget, char * version)
Set event playback status.
Parameters
[in,out] widget statusbar recording status widget
[in] version VICE version major.minor string during playback, NULL when playback is done
Referenced by ui_display_playback().
statusbar_recording_widget_set_recording_status()
void statusbar_recording_widget_set_recording_status (GtkWidget * widget, int status)
Set recording status.
Sets the type of recording and the status (ie 'Recording $rec-type or 'Recording stopped).
Note
Somehow getting the recording state of events doesn't work yet, so that currently displays 'inactive'.
Parameters
[in,out] widget statusbar recording status widget
[in] status recording status (boolean)
Todo:
FIXME: sound_is_recording() returns false when using the UI, it uses a variable that only gets set when using command-line options. Triggering the recording from the UI doesn't set the variable but does set the related resource, which I use in the function used to update the UI display.
So this needs some serious refactoring.
Referenced by ui_display_recording().
statusbar_recording_widget_set_time()
void statusbar_recording_widget_set_time (GtkWidget * widget, unsigned int current, unsigned int total)
Update recording/playback time display.
Parameters
[in,out] widget recording widget
[in] current current time in seconds
[in] total total time in seconds
Note
total only makes sense when replaying events. I could make the time display '–:–' when total is 0, but it it possible, though unlikely, we're replaying a sequence of events which take less than a second.
Todo:
FIXME: Determining the recording status/type is currently very flaky. When triggering a recording from the UI the variables that should indicate the recording type aren't set yet. So for now we have to check them in this timer callback. Also the sound recording status function is broken in src/sound.c.
Referenced by ui_display_event_time(), and update_timer().