vsid: arch/gtk3/widgets/petramsizewidget.c File Reference
petramsizewidget.c File Reference
Widget to set the PET RAM size.
#include "vice.h"
#include <gtk/gtk.h>
#include "basewidgets.h"
#include "widgethelpers.h"
#include "debug_gtk3.h"
#include "resources.h"
#include "petramsizewidget.h"
Functions
static void ram_size_callback (GtkWidget *widget, int size)
Callback for the radio group widget.
GtkWidget * pet_ram_size_widget_create (void)
Create PET RAM size widget.
void pet_ram_size_widget_set_callback (GtkWidget *widget, void(*func)(int))
Set callback on RAM size change.
void pet_ram_size_widget_sync (GtkWidget *widget)
Syncronize widget with its resource.
Variables
static const vice_gtk3_radiogroup_entry_t ram_sizes []
Data for the radio buttons group.
static void(* glue_func)(int)
User-defined callback function.
Detailed Description
Widget to set the PET RAM size.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
pet_ram_size_widget_create()
GtkWidget * pet_ram_size_widget_create (void)
Create PET RAM size widget.
Creates a widget to control the PET's RAM size
Returns
GtkGrid
Referenced by create_pet_layout().
pet_ram_size_widget_set_callback()
void pet_ram_size_widget_set_callback (GtkWidget * widget, void(*)(int) func)
Set callback on RAM size change.
Parameters
[in] widget PET RAM size widget
[in] func callback function
Referenced by create_pet_layout().
pet_ram_size_widget_sync()
void pet_ram_size_widget_sync (GtkWidget * widget)
Syncronize widget with its resource.
Parameters
[in,out] widget PET RAM size widget
Referenced by machine_model_handler_pet().
ram_size_callback()
static void ram_size_callback (GtkWidget * widget, int size) static
Callback for the radio group widget.
Parameters
[in] widget radio group widget
[in] size RAM size in KiB
Referenced by pet_ram_size_widget_set_callback().
Variable Documentation
glue_func
void(* glue_func) (int) (int) static
User-defined callback function.
Set with pet_ram_size_widget_set_callback()
Referenced by pet_ram_size_widget_set_callback(), and ram_size_callback().
ram_sizes
const vice_gtk3_radiogroup_entry_t ram_sizes[] static
Initial value:
= {
    { "4KiB",     4 },
    { "8KiB",     8 },
    { "16KiB",   16 },
    { "32KiB",   32 },
    { "96KiB",   96 },
    { "128KiB", 128 },
    { NULL,      -1 }
}
Data for the radio buttons group.
Referenced by cbm2_memory_size_widget_create(), and pet_ram_size_widget_create().