vsid: arch/gtk3/actions-joystick.c File Reference
actions-joystick.c File Reference
UI action implementations for joysticks and mouse.
#include "vice.h"
#include <gtk/gtk.h>
#include <stddef.h>
#include <stdbool.h>
#include "hotkeys.h"
#include "resources.h"
#include "ui.h"
#include "uiactions.h"
#include "uimenu.h"
#include "actions-joystick.h"
Functions
bool ui_get_controlport_swapped (void)
Get controlport swapped state.
static void swap_controlport_toggle_action (ui_action_map_t *self)
Swap joysticks and their associated devices.
static void keyset_joystick_toggle_action (ui_action_map_t *self)
Toggle keyset joysticks.
static void mouse_grab_toggle_action (ui_action_map_t *self)
Toggle mouse grab.
void actions_joystick_register (void)
Register joystick/mouse actions.
void actions_joystick_setup_ui (void)
Set joystick/mouse-related check buttons.
Variables
static bool controlport_swapped = false
Joysticks swapped state.
static const ui_action_map_t joystick_actions []
List of joystick/mouse avtions.
Detailed Description
UI action implementations for joysticks and mouse.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
actions_joystick_register()
void actions_joystick_register (void)
Register joystick/mouse actions.
Referenced by ui_init_finalize().
actions_joystick_setup_ui()
void actions_joystick_setup_ui (void)
Set joystick/mouse-related check buttons.
Set check buttons for 'controlport-swapped', mouse-grab' and 'keyset-joystick'.
Referenced by ui_init_finalize().
keyset_joystick_toggle_action()
static void keyset_joystick_toggle_action (ui_action_map_t * self) static
Toggle keyset joysticks.
Parameters
[in] self action map
mouse_grab_toggle_action()
static void mouse_grab_toggle_action (ui_action_map_t * self) static
Toggle mouse grab.
Parameters
[in] self action map
swap_controlport_toggle_action()
static void swap_controlport_toggle_action (ui_action_map_t * self) static
Swap joysticks and their associated devices.
Parameters
[in] self action map
ui_get_controlport_swapped()
bool ui_get_controlport_swapped (void)
Get controlport swapped state.
Returns
true if swapped
Referenced by create_swap_joysticks_button(), joystick_menu_popup_create(), and on_swap_joysticks_toggled().
Variable Documentation
controlport_swapped
bool controlport_swapped = false static
Joysticks swapped state.
Referenced by actions_joystick_setup_ui(), swap_controlport_toggle_action(), and ui_get_controlport_swapped().
joystick_actions
const ui_action_map_t joystick_actions[] static
Initial value:
= {
    {   .action   = ACTION_SWAP_CONTROLPORT_TOGGLE,
        .handler  = swap_controlport_toggle_action,
        .uithread = true
    },
    {   .action   = ACTION_KEYSET_JOYSTICK_TOGGLE,
        .handler  = keyset_joystick_toggle_action,
        .uithread = true
    },
    {   .action   = ACTION_MOUSE_GRAB_TOGGLE,
        .handler  = mouse_grab_toggle_action,
        .uithread = true
    },
     { .action = ACTION_NONE, .handler = NULL }
}
List of joystick/mouse avtions.
Referenced by actions_joystick_register().