x128: c128/cart/generic.h File Reference
generic.h File Reference
Functions
int c128generic_bin_attach (const char *filename, uint8_t *rawcart)
int c128generic_crt_attach (FILE *fd, uint8_t *rawcart)
void c128generic_detach (void)
void c128generic_reset (void)
void c128generic_config_setup (uint8_t *rawcart)
int c128generic_snapshot_write_module (struct snapshot_s *s, int type)
int c128generic_snapshot_read_module (struct snapshot_s *s, int type)
Function Documentation
c128generic_bin_attach()
int c128generic_bin_attach (const char * filename, uint8_t * rawcart)
Referenced by c128cartridge_bin_attach().
c128generic_config_setup()
void c128generic_config_setup (uint8_t * rawcart)
Referenced by c128cartridge_config_setup().
c128generic_crt_attach()
int c128generic_crt_attach (FILE * fd, uint8_t * rawcart)
< external function rom
< external function rom
Referenced by c128cartridge_attach_crt().
c128generic_detach()
void c128generic_detach (void)
Referenced by c128cartridge_detach_image().
c128generic_reset()
void c128generic_reset (void)
Referenced by c128cartridge_reset().
c128generic_snapshot_read_module()
int c128generic_snapshot_read_module (struct snapshot_s * s, int type)
Referenced by c128cartridge_snapshot_read().
c128generic_snapshot_write_module()
int c128generic_snapshot_write_module (struct snapshot_s * s, int type)
Referenced by c128cartridge_snapshot_write().