vsid: serial/serial-realdevice.c File Reference
serial-realdevice.c File Reference
#include "vice.h"
#include "realdevice.h"
#include "serial.h"
Functions
int serial_realdevice_enable (void)
void serial_realdevice_disable (void)
Function Documentation
serial_realdevice_disable()
void serial_realdevice_disable (void)
Referenced by file_system_detach_disk_shutdown(), and set_file_system_device().
serial_realdevice_enable()
int serial_realdevice_enable (void)
Referenced by set_file_system_device().