vsid: raster/raster-canvas.c File Reference
raster-canvas.c File Reference
#include "vice.h"
#include <stdio.h>
#include "videoarch.h"
#include "lib.h"
#include "machine.h"
#include "raster-canvas.h"
#include "raster.h"
#include "video.h"
#include "viewport.h"
#include "vsync.h"
Functions
static void refresh_canvas (raster_t *raster)
void raster_canvas_handle_end_of_frame (raster_t *raster)
void raster_canvas_init (raster_t *raster)
void raster_canvas_shutdown (raster_t *raster)
Function Documentation
raster_canvas_handle_end_of_frame()
void raster_canvas_handle_end_of_frame (raster_t * raster)
Referenced by raster_line_emulate().
raster_canvas_init()
void raster_canvas_init (raster_t * raster)
Referenced by raster_init().
raster_canvas_shutdown()
void raster_canvas_shutdown (raster_t * raster)
Referenced by raster_shutdown().
refresh_canvas()
static void refresh_canvas (raster_t * raster) inline static
Referenced by raster_canvas_handle_end_of_frame().