vsid: diskimage/fsimage-create.h File Reference
fsimage-create.h File Reference
Create disk images on the host file system - header.
Functions
void fsimage_create_init (void)
Initialize module.
int fsimage_create (const char *name, unsigned int type)
Create a disk image of type type called name on the host OS.
int fsimage_create_dxm (const char *name, const char *diskname, unsigned int type)
Create a DxM disk image on the host file system.
int fsimage_create_dhd (const char *name, const char *diskname, unsigned int type)
Create a DHD (hard)disk image on the host file system.
Detailed Description
Create disk images on the host file system - header.
Function Documentation
fsimage_create()
int fsimage_create (const char * name, unsigned int type)
Create a disk image of type type called name on the host OS.
Parameters
[in] name disk image name/path
[in] type disk image type
Returns
0 on success, < 0 on failure
< write mode (binary)
< D9090/D9060
Referenced by disk_image_fsimage_create().
fsimage_create_dhd()
int fsimage_create_dhd (const char * name, const char * diskname, unsigned int type)
Create a DHD (hard)disk image on the host file system.
This handles CMD HD (hard)disk images supported by VICE.
!
Todo:
FIXME: Right now this simply creates a zero-byte file, which then has to be partitioned/formatted using the CMD tools.
!
Todo:
FIXME: Once creating formatted images was implemented, the type and number of params passed to this function perhaps needs to be adjusted. In that case make sure to fix them the entire call chain. Maybe even the UIs will have to be updated so extra parameters can be provided.
Parameters
[in] name disk image name/path
[in] diskname disk name and id
[in] type disk image type
Returns
0 on success, < 0 on failure
< write mode (binary)
< HD in ASCII for CMDHD
Referenced by disk_image_fsimage_create_dhd().
fsimage_create_dxm()
int fsimage_create_dxm (const char * name, const char * diskname, unsigned int type)
Create a DxM disk image on the host file system.
This handles any 'FD2000 or FD4000 disk image supported by VICE.
Parameters
[in] name disk image name/path
[in] diskname disk name and id
[in] type disk image type
Returns
0 on success, < 0 on failure
< write mode (binary)
< D1M image, 81 tracks
< D2M image, 81 tracks
< D4M image, 81 tracks
Referenced by disk_image_fsimage_create_dxm().
fsimage_create_init()
void fsimage_create_init (void)
Initialize module.
In this case: just open a log
Referenced by disk_image_init().