x128: diskimage/diskimage.c File Reference
diskimage.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "diskconstants.h"
#include "diskimage.h"
#include "fsimage-check.h"
#include "fsimage-create.h"
#include "fsimage-dxx.h"
#include "fsimage-gcr.h"
#include "fsimage-p64.h"
#include "fsimage.h"
#include "lib.h"
#include "log.h"
#include "realimage.h"
#include "types.h"
#include "p64.h"
Macros
#define DBG(x)
#define SPEED_ZONE_COUNT 4
Number of speed zones for a given floppy.
Functions
unsigned int disk_image_speed_map (unsigned int format, unsigned int track)
Speed zones.
unsigned int disk_image_sector_per_track (unsigned int format, unsigned int track)
Get number of sectors for track in format.
unsigned int disk_image_raw_track_size (unsigned int format, unsigned int track)
Get the raw (GCR) track size.
unsigned int disk_image_gap_size (unsigned int format, unsigned int track)
unsigned int disk_image_header_gap_size (unsigned int format, unsigned int track)
Gap between header and sector.
unsigned int disk_image_sync_size (unsigned int format, unsigned int track)
length of a SYNC
int disk_image_check_sector (const disk_image_t *image, unsigned int track, unsigned int sector)
Check out of bound.
static const char * disk_image_type (const disk_image_t *image)
Get image type identifier string for image.
void disk_image_attach_log (const disk_image_t *image, signed int lognum, unsigned int unit, unsigned int drive)
Log attachment of disk image.
void disk_image_detach_log (const disk_image_t *image, signed int lognum, unsigned int unit, unsigned int drive)
Log detachment of disk image.
void disk_image_fsimage_name_set (disk_image_t *image, const char *name)
Set disk image name.
const char * disk_image_fsimage_name_get (const disk_image_t *image)
Get disk image name.
void * disk_image_fsimage_fd_get (const disk_image_t *image)
Get file descriptor for image.
int disk_image_fsimage_create (const char *name, unsigned int type)
int disk_image_fsimage_create_dxm (const char *name, const char *diskname, unsigned int type)
int disk_image_fsimage_create_dhd (const char *name, const char *diskname, unsigned int type)
void disk_image_name_set (disk_image_t *image, const char *name)
const char * disk_image_name_get (const disk_image_t *image)
disk_image_t * disk_image_create (void)
void disk_image_destroy (disk_image_t *image)
void disk_image_media_create (disk_image_t *image)
void disk_image_media_destroy (disk_image_t *image)
int disk_image_open (disk_image_t *image)
int disk_image_close (disk_image_t *image)
int disk_image_read_sector (const disk_image_t *image, uint8_t *buf, const disk_addr_t *dadr)
int disk_image_write_sector (disk_image_t *image, const uint8_t *buf, const disk_addr_t *dadr)
int disk_image_write_half_track (disk_image_t *image, unsigned int half_track, const struct disk_track_s *raw)
int disk_image_read_image (const disk_image_t *image)
int disk_image_write_p64_image (const disk_image_t *image)
void disk_image_init (void)
Initialization.
int disk_image_resources_init (void)
void disk_image_resources_shutdown (void)
int disk_image_cmdline_options_init (void)
off_t disk_image_size (const disk_image_t *image)
Variables
static log_t disk_image_log = ((log_t)-2)
Log destination for module.
static const unsigned int sector_map_d64 [4]
Number of sectors per track.
static const unsigned int sector_map_d67 [4]
Sectors per speed zone for D67 images.
static const unsigned int sector_map_d80 [4]
Sectors per speed zone for D80/D82 images.
static const unsigned int raw_track_size_d64 [4]
Bytes per track.
static const unsigned int raw_track_size_d67 [4]
Size of a raw (GCR) track in bytes in a D67 image per speed zone.
static const unsigned int raw_track_size_d80 [4]
Size of a raw (GCR) track in bytes in a D80 image per speed zone.
static const unsigned int gap_size_d64 [4]
Gap between sectors.
static const unsigned int gap_size_d67 [4]
the 2040 tried to squeeze one more sector into speed zone 2
Macro Definition Documentation
DBG
#define DBG (x)
SPEED_ZONE_COUNT
#define SPEED_ZONE_COUNT 4
Number of speed zones for a given floppy.
Function Documentation
disk_image_attach_log()
void disk_image_attach_log (const disk_image_t * image, signed int lognum, unsigned int unit, unsigned int drive)
Log attachment of disk image.
Parameters
[in] image disk image attached
[in] lognum (unused)
[in] unit unit the image is attached to
Referenced by cmdhd_attach_image(), drive_image_attach(), fdc_attach_image(), pc8477_attach_image(), vdrive_attach_image(), and wd1770_attach_image().
disk_image_check_sector()
int disk_image_check_sector (const disk_image_t * image, unsigned int track, unsigned int sector)
Check out of bound.
Check if a (track, sector) is inside bounds for image
Parameters
[in] image disk image
[in] track track number
[in] sector sector number
Returns
bool
Referenced by bcopy_cmd(), bfill_cmd(), block_cmd(), bpoke_cmd(), bread_cmd(), bwrite_cmd(), chain_cmd(), fsimage_dxx_read_sector(), fsimage_dxx_write_half_track(), fsimage_dxx_write_sector(), fsimage_read_dxx_image(), print_side_sector_group(), vdrive_bam_allocate_chain(), vdrive_bam_allocate_chain_255(), vdrive_command_allocate_chain(), vdrive_command_validate_worker(), and vdrive_dir_free_chain().
disk_image_close()
int disk_image_close (disk_image_t * image)
Referenced by attach_disk_image(), close_disk_image(), detach_disk_image(), and vdrive_internal_close_disk_image().
disk_image_cmdline_options_init()
int disk_image_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
disk_image_create()
disk_image_t * disk_image_create (void)
Referenced by attach_disk_image(), and open_disk_image().
disk_image_destroy()
void disk_image_destroy (disk_image_t * image)
Referenced by attach_disk_image(), close_disk_image(), detach_disk_image_and_free(), and open_disk_image().
disk_image_detach_log()
void disk_image_detach_log (const disk_image_t * image, signed int lognum, unsigned int unit, unsigned int drive)
Log detachment of disk image.
Parameters
[in] image disk image detached
[in] lognum (unused)
[in] unit unit the image is detached from
Referenced by cmdhd_detach_image(), drive_image_detach(), fdc_detach_image(), pc8477_detach_image(), vdrive_detach_image(), and wd1770_detach_image().
disk_image_fsimage_create()
int disk_image_fsimage_create (const char * name, unsigned int type)
Referenced by cbmimage_create_image().
disk_image_fsimage_create_dhd()
int disk_image_fsimage_create_dhd (const char * name, const char * diskname, unsigned int type)
Referenced by cbmimage_create_dhd_image().
disk_image_fsimage_create_dxm()
int disk_image_fsimage_create_dxm (const char * name, const char * diskname, unsigned int type)
Referenced by cbmimage_create_dxm_image().
disk_image_fsimage_fd_get()
void * disk_image_fsimage_fd_get (const disk_image_t * image)
Get file descriptor for image.
Parameters
[in] image disk image
Returns
file descriptor
Referenced by vdrive_command_format().
disk_image_fsimage_name_get()
const char * disk_image_fsimage_name_get (const disk_image_t * image)
Get disk image name.
Parameters
[in] image disk image
Returns
disk image name
Referenced by file_system_get_disk_name().
disk_image_fsimage_name_set()
void disk_image_fsimage_name_set (disk_image_t * image, const char * name)
Set disk image name.
Parameters
[in,out] image disk image
[in] name disk image name
Referenced by attach_disk_image().
disk_image_gap_size()
unsigned int disk_image_gap_size (unsigned int format, unsigned int track)
Referenced by fsimage_create_gcr(), fsimage_create_p64(), and fsimage_read_dxx_image().
disk_image_header_gap_size()
unsigned int disk_image_header_gap_size (unsigned int format, unsigned int track)
Gap between header and sector.
Todo:
FIXME: is this correct ?
Referenced by fsimage_create_gcr(), fsimage_create_p64(), and fsimage_read_dxx_image().
disk_image_init()
void disk_image_init (void)
Initialization.
Referenced by machine_specific_init().
disk_image_media_create()
void disk_image_media_create (disk_image_t * image)
Referenced by attach_disk_image(), open_disk_image(), and vdrive_internal_open_fsimage().
disk_image_media_destroy()
void disk_image_media_destroy (disk_image_t * image)
Referenced by attach_disk_image(), close_disk_image(), detach_disk_image(), open_disk_image(), vdrive_internal_close_disk_image(), and vdrive_internal_open_fsimage().
disk_image_name_get()
const char * disk_image_name_get (const disk_image_t * image)
disk_image_name_set()
void disk_image_name_set (disk_image_t * image, const char * name)
Referenced by open_disk_image(), and vdrive_internal_open_fsimage().
disk_image_open()
int disk_image_open (disk_image_t * image)
Referenced by attach_disk_image(), open_disk_image(), and vdrive_internal_open_fsimage().
disk_image_raw_track_size()
unsigned int disk_image_raw_track_size (unsigned int format, unsigned int track)
Get the raw (GCR) track size.
Parameters
[in] format disk image format enumerator
[in] track track number
Returns
number of bytes for track
Referenced by fsimage_create_gcr(), fsimage_create_p64(), fsimage_gcr_read_half_track(), fsimage_p64_read_half_track(), fsimage_read_dxx_image(), and fsimage_read_gcr_image().
disk_image_read_image()
int disk_image_read_image (const disk_image_t * image)
Referenced by drive_image_attach().
disk_image_read_sector()
int disk_image_read_sector (const disk_image_t * image, uint8_t * buf, const disk_addr_t * dadr)
Referenced by cmdhd_findbaselba(), drive_snapshot_write_image_module(), fdd_update_raw(), vdrive_read_sector(), and vdrive_read_sector_physical().
disk_image_resources_init()
int disk_image_resources_init (void)
Referenced by machine_resources_init().
disk_image_resources_shutdown()
void disk_image_resources_shutdown (void)
Referenced by machine_resources_shutdown().
disk_image_sector_per_track()
unsigned int disk_image_sector_per_track (unsigned int format, unsigned int track)
Get number of sectors for track in format.
Determines the number of sectors for a given track and disk image format.
Parameters
[in] format disk image type enumerator
[in] track track number
Returns
number of sectors or 0 on error
Referenced by fsimage_check_sector(), fsimage_create_gcr(), fsimage_create_p64(), fsimage_dxx_write_half_track(), fsimage_read_dxx_image(), unzip_cmd(), and vdrive_get_max_sectors().
disk_image_size()
off_t disk_image_size (const disk_image_t * image)
Referenced by cmdhd_attach_image().
disk_image_speed_map()
unsigned int disk_image_speed_map (unsigned int format, unsigned int track)
Speed zones.
Determine the speed zone for track in format
The speed zone determines the number of sectors containing in a track for a given image type. Speed zone 0 is closest to the disk center (containing the smallest number of sectors for a speed zone), 3 is farthest away (containing the largest number of sectors for a speed zone).
Parameters
[in] format disk image type enumerator
[in] track track number
Returns
speed zone (0-3)
Todo:
FIXME: what about 80 track D82s?
Todo:
FIXME: what about 40 track D71s?
Todo:
FIXME: is this correct?
Referenced by disk_image_gap_size(), disk_image_raw_track_size(), disk_image_sector_per_track(), fsimage_create_gcr(), fsimage_gcr_write_half_track(), and fsimage_p64_read_half_track().
disk_image_sync_size()
unsigned int disk_image_sync_size (unsigned int format, unsigned int track)
length of a SYNC
Todo:
FIXME: the value of 5 bytes for sync is also hardcoded in gcr.c
Todo:
FIXME: is this correct ?
Referenced by fsimage_create_gcr(), fsimage_create_p64(), and fsimage_read_dxx_image().
disk_image_type()
static const char * disk_image_type (const disk_image_t * image) static
Get image type identifier string for image.
Parameters
[in] image disk image
Returns
disk image identifier (nul-terminated 3-char string)
< HD in ASCII for CMDHD
< D9090/D9060
Referenced by autostart_prg_with_disk_image(), disk_image_attach_log(), and disk_image_detach_log().
disk_image_write_half_track()
int disk_image_write_half_track (disk_image_t * image, unsigned int half_track, const struct disk_track_s * raw)
Referenced by drive_gcr_data_writeback().
disk_image_write_p64_image()
int disk_image_write_p64_image (const disk_image_t * image)
Referenced by drive_gcr_data_writeback_all(), and drive_image_detach().
disk_image_write_sector()
int disk_image_write_sector (disk_image_t * image, const uint8_t * buf, const disk_addr_t * dadr)
Referenced by drive_snapshot_read_image_module(), fdc_do_format_D20(), fdc_do_format_D40(), fdc_do_format_D80(), fdc_do_format_D90(), fdd_flush_raw(), vdrive_write_sector(), and vdrive_write_sector_physical().
Variable Documentation
disk_image_log
log_t disk_image_log = ((log_t)-2) static
Log destination for module.
Referenced by disk_image_close(), disk_image_gap_size(), disk_image_header_gap_size(), disk_image_init(), disk_image_media_create(), disk_image_media_destroy(), disk_image_open(), disk_image_raw_track_size(), disk_image_read_sector(), disk_image_sector_per_track(), disk_image_size(), disk_image_speed_map(), disk_image_sync_size(), disk_image_write_half_track(), and disk_image_write_sector().
gap_size_d64
const unsigned int gap_size_d64[4] static
Initial value:
= {
    9,
    12,
    17,
    8
}
Gap between sectors.
Referenced by disk_image_gap_size().
gap_size_d67
const unsigned int gap_size_d67[4] static
Initial value:
= {
    9,
    12,
    4,
    8
}
the 2040 tried to squeeze one more sector into speed zone 2
Todo:
FIXME: D67 has 20 sectors per track for speed zone 2, D64/D71 has 19 sectors for that speed zone
Referenced by disk_image_gap_size().
raw_track_size_d64
const unsigned int raw_track_size_d64[4] static
Initial value:
= {
    6250,
    6666,
    7142,
    7692
}
Bytes per track.
Size of a raw (GCR) track in bytes in a D64 image per speed zone
Referenced by disk_image_raw_track_size().
raw_track_size_d67
const unsigned int raw_track_size_d67[4] static
Initial value:
= {
    6250,
    6666,
    7142,
    7692
}
Size of a raw (GCR) track in bytes in a D67 image per speed zone.
the 2040 tried to squeeze one more sector into speed zone 2
Todo:
FIXME: D67 has 20 sectors per track for speed zone 2, D64/D71 has 19 sectors for that speed zone
note: the number of GCR bits per track "should" be the same as in D64, as that is pretty much defined by the clock and rotation speed.
Referenced by disk_image_raw_track_size().
raw_track_size_d80
const unsigned int raw_track_size_d80[4] static
Initial value:
= {
    9375,
    10000,
    10714,
    11538
}
Size of a raw (GCR) track in bytes in a D80 image per speed zone.
Referenced by disk_image_raw_track_size().
sector_map_d64
const unsigned int sector_map_d64[4] static
Initial value:
= {
    17,
    18,
    19,
    21
}
Number of sectors per track.
Sectors per speed zone for D64/D71 images
Referenced by disk_image_sector_per_track().
sector_map_d67
const unsigned int sector_map_d67[4] static
Initial value:
= {
    17,
    18,
    20,
    21
}
Sectors per speed zone for D67 images.
the 2040 tried to squeeze one more sector into speed zone 2
Referenced by disk_image_sector_per_track().
sector_map_d80
const unsigned int sector_map_d80[4] static
Initial value:
= {
    23,
    25,
    27,
    29
}
Sectors per speed zone for D80/D82 images.
Referenced by disk_image_sector_per_track().