x128: drive/iec128dcr/iec128dcrrom.h File Reference
iec128dcrrom.h File Reference
#include "types.h"
Functions
void iec128dcrrom_init (void)
void iec128dcrrom_setup_image (struct diskunit_context_s *drive)
int iec128dcrrom_check_loaded (unsigned int type)
int iec128dcrrom_load_1571cr (void)
Function Documentation
iec128dcrrom_check_loaded()
int iec128dcrrom_check_loaded (unsigned int type)
Referenced by iec128dcr_drive_rom_check_loaded().
iec128dcrrom_init()
void iec128dcrrom_init (void)
Referenced by iec128dcr_drive_init().
iec128dcrrom_load_1571cr()
int iec128dcrrom_load_1571cr (void)
Referenced by iec128dcr_drive_rom_load(), and set_dos_rom_name_1571cr().
iec128dcrrom_setup_image()
void iec128dcrrom_setup_image (struct diskunit_context_s * drive)
Referenced by iec128dcr_drive_rom_setup_image().