vsid: core/scsi.c File Reference
scsi.c File Reference
#include <stdio.h>
#include <string.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "types.h"
#include "snapshot.h"
#include "scsi.h"
Macros
#define _FILE_OFFSET_BITS 64
#define LOG LOG_DEFAULT
#define ERR LOG_ERR
#define LOG1(_x_)
#define LOG2(_x_)
#define SDBG(_x_)
#define CRIT(_x_) log_message _x_
#define MAXIDS 7
#define MAXLUNS 8
#define SNAP_MAJOR 0
#define SNAP_MINOR 0
Functions
static off_t scsi_getmaxsize (struct scsi_context_s *context)
static int32_t scsi_imagecheck (struct scsi_context_s *context)
int scsi_image_detach (struct scsi_context_s *context, int disk)
void scsi_image_detach_all (struct scsi_context_s *context)
int scsi_image_attach (struct scsi_context_s *context, int disk, char *filename)
int32_t scsi_image_read (struct scsi_context_s *context)
int32_t scsi_image_write (struct scsi_context_s *context)
static void scsi_format_sector0 (struct scsi_context_s *context)
default format handler
uint8_t scsi_get_bus (struct scsi_context_s *context)
int scsi_set_bus (struct scsi_context_s *context, uint8_t value)
void scsi_process_noack (struct scsi_context_s *context)
void scsi_process_ack (struct scsi_context_s *context)
void scsi_reset (struct scsi_context_s *context)
int scsi_snapshot_write_module (struct scsi_context_s *context, snapshot_t *s)
int scsi_snapshot_read_module (struct scsi_context_s *context, snapshot_t *s)
Macro Definition Documentation
_FILE_OFFSET_BITS
#define _FILE_OFFSET_BITS 64
CRIT
#define CRIT (_x_) log_message _x_
ERR
#define ERR LOG_ERR
LOG
#define LOG LOG_DEFAULT
LOG1
#define LOG1 (_x_)
LOG2
#define LOG2 (_x_)
MAXIDS
#define MAXIDS 7
MAXLUNS
#define MAXLUNS 8
SDBG
#define SDBG (_x_)
SNAP_MAJOR
#define SNAP_MAJOR 0
SNAP_MINOR
#define SNAP_MINOR 0
Function Documentation
scsi_format_sector0()
static void scsi_format_sector0 (struct scsi_context_s * context) static
default format handler
We don't actually format the disk, we just zero out the first sector
Referenced by scsi_reset().
scsi_get_bus()
uint8_t scsi_get_bus (struct scsi_context_s * context)
Referenced by read_pra9().
scsi_getmaxsize()
static off_t scsi_getmaxsize (struct scsi_context_s * context) static
Referenced by scsi_process_ack().
scsi_image_attach()
int scsi_image_attach (struct scsi_context_s * context, int disk, char * filename)
scsi_image_detach()
int scsi_image_detach (struct scsi_context_s * context, int disk)
Referenced by scsi_image_attach(), and scsi_image_detach_all().
scsi_image_detach_all()
void scsi_image_detach_all (struct scsi_context_s * context)
scsi_image_read()
int32_t scsi_image_read (struct scsi_context_s * context)
Referenced by cmdhd_scsiformat(), and scsi_process_ack().
scsi_image_write()
int32_t scsi_image_write (struct scsi_context_s * context)
Referenced by cmdhd_scsiformat(), scsi_format_sector0(), and scsi_process_ack().
scsi_imagecheck()
static int32_t scsi_imagecheck (struct scsi_context_s * context) static
Referenced by scsi_image_read(), scsi_image_write(), and scsi_process_ack().
scsi_process_ack()
void scsi_process_ack (struct scsi_context_s * context)
Limit size returned as some tools can't handle large disks
SCSI spec says return last accessable block number
CMD drive info tool looks at page 20h, so lets put that one in
Referenced by read_pra9(), and store_pra9().
scsi_process_noack()
void scsi_process_noack (struct scsi_context_s * context)
Referenced by read_pra9(), read_prb9(), scsi_reset(), set_pc(), store_pra9(), and store_prb9().
scsi_reset()
void scsi_reset (struct scsi_context_s * context)
Referenced by cmdhd_init().
scsi_set_bus()
int scsi_set_bus (struct scsi_context_s * context, uint8_t value)
Referenced by store_pra9().
scsi_snapshot_read_module()
int scsi_snapshot_read_module (struct scsi_context_s * context, snapshot_t * s)
Referenced by cmdhd_snapshot_read_module().
scsi_snapshot_write_module()
int scsi_snapshot_write_module (struct scsi_context_s * context, snapshot_t * s)
Referenced by cmdhd_snapshot_write_module().