vsid: keyboard.h File Reference
keyboard.h File Reference
#include "types.h"
Data Structures
struct key_custom_info_t
Macros
#define KBD_ROWS 16
#define KBD_COLS 8
(This is actually the same for all the machines.)
#define KBD_ROW_JOY_KEYMAP_A -1
negative rows/columns for extra keys
#define KBD_ROW_JOY_KEYMAP_B -2
#define KBD_ROW_RESTORE_1 -3
#define KBD_ROW_RESTORE_2 -3
#define KBD_COL_RESTORE_1 0
#define KBD_COL_RESTORE_2 1
#define KBD_ROW_4080COLUMN -4
#define KBD_ROW_CAPSLOCK -4
#define KBD_COL_4080COLUMN 0
#define KBD_COL_CAPSLOCK 1
#define KBD_ROW_JOY_KEYPAD -5
#define KBD_JOY_KEYPAD_ROWS 4
joystick port attached keypad
#define KBD_JOY_KEYPAD_COLS 5
#define KBD_JOY_KEYPAD_NUMKEYS (KBD_JOY_KEYPAD_ROWS * KBD_JOY_KEYPAD_COLS)
#define KBD_MOD_LSHIFT (1 << 0)
#define KBD_MOD_RSHIFT (1 << 1)
#define KBD_MOD_LCTRL (1 << 2)
#define KBD_MOD_RCTRL (1 << 3)
#define KBD_MOD_LALT (1 << 4)
#define KBD_MOD_RALT (1 << 5)
#define KBD_MOD_SHIFTLOCK (1 << 6)
#define KBD_CUSTOM_NONE 0
#define KBD_CUSTOM_RESTORE1 1
#define KBD_CUSTOM_RESTORE2 2
#define KBD_CUSTOM_CAPS 3
#define KBD_CUSTOM_4080 4
#define KBD_CUSTOM_NUM 5
Typedefs
typedef int(* key_custom_func_t) (int pressed)
typedef void(* key_joy_keypad_func_t) (int row, int col, int pressed)
extra handler for keypad on the joystick port
typedef void(* keyboard_machine_func_t) (int *)
machine specific utility function that is called after the keyboard was latched
Functions
void keyboard_init (void)
void keyboard_shutdown (void)
int keyboard_resources_init (void)
int keyboard_cmdline_options_init (void)
int keyboard_snapshot_write_module (struct snapshot_s *s)
int keyboard_snapshot_read_module (struct snapshot_s *s)
void keyboard_set_keyarr (int row, int col, int value)
used for event playback, triggering keys from Joystick events, virtual keyboard
void keyboard_set_keyarr_any (int row, int col, int value)
used for event playback, triggering keys from Joystick events, virtual keyboard
void keyboard_clear_keymatrix (void)
void keyboard_event_playback (CLOCK offset, void *data)
void keyboard_restore_event_playback (CLOCK offset, void *data)
void keyboard_event_delayed_playback (void *data)
void keyboard_register_delay (unsigned int delay)
void keyboard_register_clear (void)
used from event code, queue a keyboard reset
void keyboard_key_pressed (signed long key, int mod)
called by the ui
void keyboard_key_released (signed long key, int mod)
release a key, this is called by the UI.
void keyboard_key_clear (void)
called by the ui
void keyboard_set_shiftlock (int state)
shift/lock handling, the emulation may also call this
int keyboard_get_shiftlock (void)
return emulated shift lock state to the UI
void keyboard_register_custom_key (int id, key_custom_func_t func, char *name, int *keysym, int *keyflags)
extra custom keys (see above)
int keyboard_custom_key_get (int id)
int keyboard_custom_key_set (int id, int pressed)
int keyboard_custom_key_toggle (int id)
void keyboard_register_joy_keypad (key_joy_keypad_func_t func)
joyport attached keypad.
void keyboard_register_machine (keyboard_machine_func_t func)
register a machine specific utility function that is called after the keyboard was latched
void keyboard_alternative_set (int alternative)
switch to alternative set (x128)
int keyboard_statusbar_enabled (void)
Get "KbdStatusbar" directly.
Variables
int keyarr [16]
int rev_keyarr [8]
Macro Definition Documentation
KBD_COL_4080COLUMN
#define KBD_COL_4080COLUMN 0
KBD_COL_CAPSLOCK
#define KBD_COL_CAPSLOCK 1
KBD_COL_RESTORE_1
#define KBD_COL_RESTORE_1 0
KBD_COL_RESTORE_2
#define KBD_COL_RESTORE_2 1
KBD_COLS
#define KBD_COLS 8
(This is actually the same for all the machines.)
(All have 8, except CBM-II that has 6)
KBD_CUSTOM_4080
#define KBD_CUSTOM_4080 4
KBD_CUSTOM_CAPS
#define KBD_CUSTOM_CAPS 3
KBD_CUSTOM_NONE
#define KBD_CUSTOM_NONE 0
KBD_CUSTOM_NUM
#define KBD_CUSTOM_NUM 5
KBD_CUSTOM_RESTORE1
#define KBD_CUSTOM_RESTORE1 1
KBD_CUSTOM_RESTORE2
#define KBD_CUSTOM_RESTORE2 2
KBD_JOY_KEYPAD_COLS
#define KBD_JOY_KEYPAD_COLS 5
KBD_JOY_KEYPAD_NUMKEYS
#define KBD_JOY_KEYPAD_NUMKEYS (KBD_JOY_KEYPAD_ROWS * KBD_JOY_KEYPAD_COLS)
KBD_JOY_KEYPAD_ROWS
#define KBD_JOY_KEYPAD_ROWS 4
joystick port attached keypad
KBD_MOD_LALT
#define KBD_MOD_LALT (1 << 4)
KBD_MOD_LCTRL
#define KBD_MOD_LCTRL (1 << 2)
KBD_MOD_LSHIFT
#define KBD_MOD_LSHIFT (1 << 0)
KBD_MOD_RALT
#define KBD_MOD_RALT (1 << 5)
KBD_MOD_RCTRL
#define KBD_MOD_RCTRL (1 << 3)
KBD_MOD_RSHIFT
#define KBD_MOD_RSHIFT (1 << 1)
KBD_MOD_SHIFTLOCK
#define KBD_MOD_SHIFTLOCK (1 << 6)
KBD_ROW_4080COLUMN
#define KBD_ROW_4080COLUMN -4
KBD_ROW_CAPSLOCK
#define KBD_ROW_CAPSLOCK -4
KBD_ROW_JOY_KEYMAP_A
#define KBD_ROW_JOY_KEYMAP_A -1
negative rows/columns for extra keys
KBD_ROW_JOY_KEYMAP_B
#define KBD_ROW_JOY_KEYMAP_B -2
KBD_ROW_JOY_KEYPAD
#define KBD_ROW_JOY_KEYPAD -5
KBD_ROW_RESTORE_1
#define KBD_ROW_RESTORE_1 -3
KBD_ROW_RESTORE_2
#define KBD_ROW_RESTORE_2 -3
KBD_ROWS
#define KBD_ROWS 16
Typedef Documentation
key_custom_func_t
typedef int(* key_custom_func_t) (int pressed)
key_joy_keypad_func_t
typedef void(* key_joy_keypad_func_t) (int row, int col, int pressed)
extra handler for keypad on the joystick port
keyboard_machine_func_t
typedef void(* keyboard_machine_func_t) (int *)
machine specific utility function that is called after the keyboard was latched
Function Documentation
keyboard_alternative_set()
void keyboard_alternative_set (int alternative)
switch to alternative set (x128)
keyboard_clear_keymatrix()
void keyboard_clear_keymatrix (void)
Todo:
FIXME: the SDL port uses this directly
Referenced by keyboard_key_clear_internal().
keyboard_cmdline_options_init()
int keyboard_cmdline_options_init (void)
Referenced by init_cmdline_options().
keyboard_custom_key_get()
int keyboard_custom_key_get (int id)
Referenced by statusbar_speed_widget_update().
keyboard_custom_key_set()
int keyboard_custom_key_set (int id, int pressed)
keyboard_custom_key_toggle()
int keyboard_custom_key_toggle (int id)
Referenced by capslock_led_callback(), and mode4080_led_callback().
keyboard_event_delayed_playback()
void keyboard_event_delayed_playback (void * data)
alarm_set(keyboard_alarm, maincpu_clk + keyboard_delay);
Referenced by event_playback_event_list().
keyboard_event_playback()
void keyboard_event_playback (CLOCK offset, void * data)
Referenced by event_alarm_handler().
keyboard_get_shiftlock()
int keyboard_get_shiftlock (void)
return emulated shift lock state to the UI
Referenced by ciapb_forcelow(), kbd_debug_widget_update(), kbd_sync_caps_lock(), and statusbar_speed_widget_update().
keyboard_init()
void keyboard_init (void)
Referenced by init_main().
keyboard_key_clear()
void keyboard_key_clear (void)
called by the ui
Referenced by kbd_event_handler().
keyboard_key_pressed()
void keyboard_key_pressed (signed long key, int mod)
called by the ui
called by the ui
this fills the host keyboard queue.
Referenced by kbd_event_handler(), and keyboard_set_keyarr_any().
keyboard_key_released()
void keyboard_key_released (signed long key, int mod)
release a key, this is called by the UI.
this fills the host keyboard queue.
Referenced by kbd_event_handler(), and keyboard_set_keyarr_any().
keyboard_register_clear()
void keyboard_register_clear (void)
used from event code, queue a keyboard reset
Referenced by event_playback_event_list().
keyboard_register_custom_key()
void keyboard_register_custom_key (int id, key_custom_func_t func, char * name, int * keysym, int * keyflags)
extra custom keys (see above)
extra custom keys (see above)
keyboard_register_delay()
void keyboard_register_delay (unsigned int delay)
Referenced by event_playback_event_list().
keyboard_register_joy_keypad()
void keyboard_register_joy_keypad (key_joy_keypad_func_t func)
joyport attached keypad.
keyboard_register_machine()
void keyboard_register_machine (keyboard_machine_func_t func)
register a machine specific utility function that is called after the keyboard was latched
Referenced by c64keyboard_init().
keyboard_resources_init()
int keyboard_resources_init (void)
Referenced by init_resources().
keyboard_restore_event_playback()
void keyboard_restore_event_playback (CLOCK offset, void * data)
Referenced by event_alarm_handler(), and event_playback_event_list().
keyboard_set_keyarr()
void keyboard_set_keyarr (int row, int col, int value)
used for event playback, triggering keys from Joystick events, virtual keyboard
Todo:
FIXME: perhaps trigger alarm here?
Referenced by keyboard_set_keyarr_any().
keyboard_set_keyarr_any()
void keyboard_set_keyarr_any (int row, int col, int value)
used for event playback, triggering keys from Joystick events, virtual keyboard
keyboard_set_shiftlock()
void keyboard_set_shiftlock (int state)
shift/lock handling, the emulation may also call this
Referenced by kbd_sync_caps_lock().
keyboard_shutdown()
void keyboard_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
keyboard_snapshot_read_module()
int keyboard_snapshot_read_module (struct snapshot_s * s)
Referenced by c64_snapshot_read().
keyboard_snapshot_write_module()
int keyboard_snapshot_write_module (struct snapshot_s * s)
Referenced by c64_snapshot_write().
keyboard_statusbar_enabled()
int keyboard_statusbar_enabled (void)
Get "KbdStatusbar" directly.
For UIs: get "KbdStatusbar" resource value without going through the resource system.
Returns
current value of "KbdStatusbar" resource
Variable Documentation
keyarr
int keyarr[16] extern
Todo:
FIXME: These ugly externs should go away sooner or later. currently these two arrays are the interface to the emulation (eg CIA core)
Referenced by keyboard_clear_keymatrix(), keyboard_event_playback(), keyboard_event_record(), keyboard_latch_matrix(), keyboard_snapshot_read_module(), keyboard_snapshot_write_module(), and matrix_activate_row().
rev_keyarr
int rev_keyarr[8] extern
Referenced by keyboard_clear_keymatrix(), keyboard_latch_matrix(), keyboard_snapshot_read_module(), keyboard_snapshot_write_module(), and matrix_activate_column().