vsid: arch/gtk3/widgets/cbm2hardwiredswitcheswidget.c File Reference
cbm2hardwiredswitcheswidget.c File Reference
Widget to select ModelLine.
#include "vice.h"
#include <gtk/gtk.h>
#include "machine.h"
#include "vice_gtk3.h"
#include "cbm2hardwiredswitcheswidget.h"
Functions
GtkWidget * cbm2_hardwired_switches_widget_create (void)
Create widget to control the 'hardwired switches', whatever those may be.
void cbm2_hardwired_switches_widget_set_callback (GtkWidget *widget, void(*callback)(GtkWidget *, int))
Set user-defined callback.
Variables
static const vice_gtk3_radiogroup_entry_t models_cbm5x0 []
Hardwired switches for 5x0 models.
static const vice_gtk3_radiogroup_entry_t models_cbm6x0 []
Hardwired switches for 6x0 models.
Detailed Description
Widget to select ModelLine.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
cbm2_hardwired_switches_widget_create()
GtkWidget * cbm2_hardwired_switches_widget_create (void)
Create widget to control the 'hardwired switches', whatever those may be.
Returns
GtkGrid
Referenced by create_cbm5x0_layout(), and create_cbm6x0_layout().
cbm2_hardwired_switches_widget_set_callback()
void cbm2_hardwired_switches_widget_set_callback (GtkWidget * widget, void(*)(GtkWidget *, int) callback)
Set user-defined callback.
The callback is called with the ModelLine as its argument
Parameters
[in,out] widget ModelLine widget
[in] callback user-defined callback
Referenced by create_cbm5x0_layout(), and create_cbm6x0_layout().
Variable Documentation
models_cbm5x0
const vice_gtk3_radiogroup_entry_t models_cbm5x0[] static
Initial value:
= {
    { "50Hz 5x0",  2 },
    { "60Hz 5x0",  1 },
    { NULL,       -1 }
}
Hardwired switches for 5x0 models.
Referenced by cbm2_hardwired_switches_widget_create().
models_cbm6x0
const vice_gtk3_radiogroup_entry_t models_cbm6x0[] static
Initial value:
= {
    { "50Hz 6x0",   2 },
    { "60Hz 6x0",   1 },
    { "50Hz 7x0",   0 },
    { NULL,         -1 }
}
Hardwired switches for 6x0 models.
Referenced by cbm2_hardwired_switches_widget_create().