vsid: arch/gtk3/widgets/base/resourcefilechooser.c File Reference
resourcefilechooser.c File Reference
Resource file chooser widget.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdarg.h>
#include "debug_gtk3.h"
#include "lib.h"
#include "resourcewidgetmediator.h"
#include "ui.h"
#include "util.h"
#include "resourcefilechooser.h"
Data Structures
struct fc_state_s
Additional state for the widget.
Typedefs
typedef struct fc_state_s fc_state_t
Additional state for the widget.
Functions
static fc_state_t * fc_state_new (void)
Create file chooser state object.
static void fc_state_free (void *state)
Free state object and its members.
static void fc_state_set_directory (fc_state_t *state, const char *directory)
Set default directory.
static gboolean set_resource_and_entry (GtkEntry *entry, const char *text)
Set resource value and update entry.
static const char * title_for_action (GtkFileChooserAction action)
Get title for file chooser dialog/icon tooltip based on action.
static void on_response (GtkDialog *dialog, gint response_id, gpointer data)
Handler for 'response' event of a file chooser dialog.
static void on_icon_press (GtkEntry *self, GtkEntryIconPosition icon_pos, GdkEvent *event, gpointer data)
Handler for the 'icon-press' event of the widget.
static gboolean on_focus_out_event (GtkEntry *self, GdkEvent *event, gpointer data)
Handler for the 'focus-out' event of the resource file chooser.
static gboolean on_key_press_event (GtkEntry *self, GdkEvent *event, gpointer data)
Handler for the 'key-press-event' event of the resource file chooser.
GtkWidget * vice_gtk3_resource_filechooser_new (const char *resource, GtkFileChooserAction action)
Create file chooser widget set select or create file or directory.
GtkWidget * vice_gtk3_resource_filechooser_new_sprintf (const char *format, GtkFileChooserAction action,...)
Create file chooser widget set select or create file or directory.
gboolean vice_gtk3_resource_filechooser_set (GtkWidget *widget, const char *pathname)
Set new pathname for the resource file chooser and its resource.
void vice_gtk3_resource_filechooser_set_directory (GtkWidget *widget, const char *directory)
Set default directory to use in the file chooser dialogs.
void vice_gtk3_resource_filechooser_set_confirm (GtkWidget *widget, gboolean confirm_overwrite)
Set whether the dialog should ask for confirmation before overwriting.
void vice_gtk3_resource_filechooser_set_filter (GtkWidget *widget, const char *name, const char **patterns, gboolean show_patterns)
Add file filter for the file chooser dialog.
void vice_gtk3_resource_filechooser_set_custom_title (GtkWidget *widget, const char *title)
Set custom title to use for file chooser dialogs.
void vice_gtk3_resource_filechooser_set_callback (GtkWidget *widget, void(*callback)(GtkEntry *, gchar *))
Set function to be called on succesfull update of the resource.
void vice_gtk3_resource_filechooser_sync (GtkWidget *widget)
Synchronize resource file chooser with its resource.
Detailed Description
Resource file chooser widget.
Presents a GtkEntry with an "open document" icon that serves as the "browse" button to open a file chooser dialog. By default no file matching pattern is used and no overwrite confirmation dialog is shown in case of the GTK_FILE_CHOOSER_ACTION_SAVE action.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Typedef Documentation
fc_state_t
typedef struct fc_state_s fc_state_t
Additional state for the widget.
Function Documentation
fc_state_free()
static void fc_state_free (void * state) static
Free state object and its members.
Parameters
[in] state file chooser state object
Referenced by vice_gtk3_resource_filechooser_new().
fc_state_new()
static fc_state_t * fc_state_new (void) static
Create file chooser state object.
This object is freed on widget destruction
Referenced by vice_gtk3_resource_filechooser_new().
fc_state_set_directory()
static void fc_state_set_directory (fc_state_t * state, const char * directory) static
Set default directory.
Set default directory in state, or unset when using NULL or an empty string string for directory.
Parameters
[in] directory default directory
Referenced by vice_gtk3_resource_filechooser_set_directory().
on_focus_out_event()
static gboolean on_focus_out_event (GtkEntry * self, GdkEvent * event, gpointer data) static
Handler for the 'focus-out' event of the resource file chooser.
Update resource when the resource file chooser widget looses focus.
Parameters
[in] self resource file chooser
[in] event event information (ignored)
[in] data extra event data (unused)
Returns
GDK_EVENT_PROPAGATE to keep propagating (required by Gdk)
Referenced by vice_gtk3_resource_filechooser_new().
on_icon_press()
static void on_icon_press (GtkEntry * self, GtkEntryIconPosition icon_pos, GdkEvent * event, gpointer data) static
Handler for the 'icon-press' event of the widget.
Show a file choose dialog to select or create a file or directory.
Parameters
[in] self resource file chooser
[in] icon_pos icon position in self (ignored)
[in] event event information (ignored)
[in] data extra event data (unused)
Referenced by vice_gtk3_resource_filechooser_new().
on_key_press_event()
static gboolean on_key_press_event (GtkEntry * self, GdkEvent * event, gpointer data) static
Handler for the 'key-press-event' event of the resource file chooser.
Update resource when the user presses Return or Enter.
Parameters
[in] self resource file chooser
[in] event event information
[in] data extra event data (unused)
Returns
GDK_EVENT_PROPAGATE to keep propagating or GDK_EVENT_STOP when the user pressed Return or Enter
Referenced by vice_gtk3_resource_filechooser_new().
on_response()
static void on_response (GtkDialog * dialog, gint response_id, gpointer data) static
Handler for 'response' event of a file chooser dialog.
Parameters
[in] dialog dialog emitting the event
[in] response_id response ID
[in] data resource file chooser to receive the dialog result
Referenced by on_icon_press().
set_resource_and_entry()
static gboolean set_resource_and_entry (GtkEntry * entry, const char * text) static
Set resource value and update entry.
Parameters
[in] entry text entry
[in] text new text for resource and entry
Returns
TRUE when the resource was succesfully set
Referenced by on_focus_out_event(), on_key_press_event(), on_response(), and vice_gtk3_resource_filechooser_set().
title_for_action()
static const char * title_for_action (GtkFileChooserAction action) static
Get title for file chooser dialog/icon tooltip based on action.
Parameters
[in] action file chooser action
Returns
title for dialog/tooltip
Referenced by on_icon_press(), and vice_gtk3_resource_filechooser_new().
vice_gtk3_resource_filechooser_new()
GtkWidget * vice_gtk3_resource_filechooser_new (const char * resource, GtkFileChooserAction action)
Create file chooser widget set select or create file or directory.
Parameters
[in] resource resource name
[in] action file chooser action
Returns
GtkEntry with icon to pop up file chooser dialog
See also
https://docs.gtk.org/gtk3/enum.FileChooserAction.html
Referenced by add_rom_chooser(), create_bios_image_layout(), create_card_image_layout(), create_card_layout(), create_eeprom_layout(), create_flash_dir_widget(), create_positional_keymap_browser(), create_prg_layout(), create_rom_widget(), create_symbolic_keymap_browser(), create_tapecart_widget(), logfile_widget_create(), settings_ieee488_widget_create(), settings_ieeeflash64_widget_create(), settings_magicvoice_widget_create(), settings_monitor_widget_create(), settings_petdww_widget_create(), settings_petreu_widget_create(), settings_sampler_widget_create(), settings_snapshot_widget_create(), and vice_gtk3_resource_filechooser_new_sprintf().
vice_gtk3_resource_filechooser_new_sprintf()
GtkWidget * vice_gtk3_resource_filechooser_new_sprintf (const char * format, GtkFileChooserAction action, ...)
Create file chooser widget set select or create file or directory.
Parameters
[in] format resource name format string
[in] action file chooser action
[in] ... arguments for format
Returns
GtkEntry with icon to pop up file chooser dialog
Referenced by create_acia_serial_device_widget(), create_hd_images_layout(), and create_ide64_device_widget().
vice_gtk3_resource_filechooser_set()
gboolean vice_gtk3_resource_filechooser_set (GtkWidget * widget, const char * pathname)
Set new pathname for the resource file chooser and its resource.
Parameters
[in] widget resource file chooser
[in] pathname new value
Returns
TRUE on success
Referenced by on_chooser_drag_data_received().
vice_gtk3_resource_filechooser_set_callback()
void vice_gtk3_resource_filechooser_set_callback (GtkWidget * widget, void(*)(GtkEntry *, gchar *) callback)
Set function to be called on succesfull update of the resource.
Set function that will be called with the new resource value and a reference to the widget when the bound resource is successfully updated.
The string passed to the callback is allocated using g_strdup() and should be freed with g_free().
Parameters
[in] widget resource filechooser widget
[in] callback function to call on succesfull resource update
Referenced by create_positional_keymap_browser(), and create_symbolic_keymap_browser().
vice_gtk3_resource_filechooser_set_confirm()
void vice_gtk3_resource_filechooser_set_confirm (GtkWidget * widget, gboolean confirm_overwrite)
Set whether the dialog should ask for confirmation before overwriting.
Set if the file chooser dialog for save file actions should show a confirmation dialog if the selected file should cause it to be overwritten. This is FALSE by default and only has effect for GTK_FILE_CHOOSER_ACTION_SAVE.
Parameters
[in] widget resource file chooser
[in] confirm_overwrite show confirmation dialog when selecting an existing file
vice_gtk3_resource_filechooser_set_custom_title()
void vice_gtk3_resource_filechooser_set_custom_title (GtkWidget * widget, const char * title)
Set custom title to use for file chooser dialogs.
Parameters
[in] widget resource file chooser
[in] title custom title for dialog of the icon
Referenced by add_rom_chooser(), create_bios_image_layout(), create_card_image_layout(), create_card_layout(), create_eeprom_layout(), create_flash_dir_widget(), create_hd_images_layout(), create_positional_keymap_browser(), create_prg_layout(), create_rom_widget(), create_symbolic_keymap_browser(), create_tapecart_widget(), logfile_widget_create(), settings_magicvoice_widget_create(), settings_monitor_widget_create(), settings_petdww_widget_create(), settings_petreu_widget_create(), settings_sampler_widget_create(), and settings_snapshot_widget_create().
vice_gtk3_resource_filechooser_set_directory()
void vice_gtk3_resource_filechooser_set_directory (GtkWidget * widget, const char * directory)
Set default directory to use in the file chooser dialogs.
Set default directory to use when the resource is empty or only contains a filename.
Parameters
[in] widget resource file chooser
[in] directory default directory
Referenced by create_positional_keymap_browser(), create_symbolic_keymap_browser(), and logfile_widget_create().
vice_gtk3_resource_filechooser_set_filter()
void vice_gtk3_resource_filechooser_set_filter (GtkWidget * widget, const char * name, const char ** patterns, gboolean show_patterns)
Add file filter for the file chooser dialog.
Add glob-style patterns to filter displayed files in the dialog. If show_patterns is true, the name will be combined with the patterns into "name (pattern1,pattern2,patter3)".
Parameters
[in] widget resource file chooser
[in] name name of filter
[in] patterns shell glob-style patterns, terminated with NULL
[in] show_patterns display list of patterns after the name
Referenced by add_rom_chooser(), create_hd_images_layout(), create_ide64_device_widget(), create_positional_keymap_browser(), create_prg_layout(), create_rom_widget(), create_symbolic_keymap_browser(), create_tapecart_widget(), settings_ieee488_widget_create(), settings_ieeeflash64_widget_create(), settings_magicvoice_widget_create(), and settings_monitor_widget_create().
vice_gtk3_resource_filechooser_sync()
void vice_gtk3_resource_filechooser_sync (GtkWidget * widget)
Synchronize resource file chooser with its resource.
Parameters
[in] widget resource file chooser
Referenced by expandable_list_sync_resources(), on_eject_icon_clicked(), on_pet_charset_load_clicked(), and on_reset_icon_clicked().