vsid: core/t6721.c File Reference
t6721.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "lib.h"
#include "maincpu.h"
#include "monitor.h"
#include "snapshot.h"
#include "t6721.h"
Data Structures
struct param_s
Macros
#define WRITEWAVFILE 1
write "test.wav" containing all generated output
#define DBG(x)
#define DBGADD(x)
#define DBG_STATUS()
#define PARCOR_OUTPUT_HZ (8000)
#define PARCOR_BUFFER_LEN (0x400)
#define RBSTATE_STOP 0
#define RBSTATE_PLAY 1
#define RBSTATE_DELAY_SAMPLES (PARCOR_OUTPUT_HZ / 200)
5 ms
#define PARMVALUE(ctx, x) (parcor_param[x] >> (16 - parcor_param_len[(ctx)->cond2_framebits][x]))
#define CART_DUMP_VER_MAJOR 0
snapshot support functions
#define CART_DUMP_VER_MINOR 0
#define SNAP_MODULE_NAME "T6721"
Typedefs
typedef struct param_s param_t
Functions
static void set_dtrd (t6721_state *t6721, int dtrd)
static void set_apd (t6721_state *t6721, int apd)
static void set_eos (t6721_state *t6721, int eos)
static void set_playing (t6721_state *t6721, int playing)
static int write_header (void)
static int fix_header (void)
static void wav_close_file (void)
static int wav_create_file (const char *filename)
static int wav_write_sample (int16_t data)
static void ringbuffer_reset (void)
static int parcor_output_sample (t6721_state *t6721, int16_t value)
static int16_t output_update_sample (t6721_state *t6721)
static int get_frame_samples (t6721_state *t6721)
static int get_subframe_samples (t6721_state *t6721)
static double filter (int i, double ef, double k)
static int render_subframe (t6721_state *t6721, int sub_i, int voiced)
static int render_silence (t6721_state *t6721)
static int parcor_render_frame (t6721_state *t6721, uint16_t *new_param)
static void reset_di_fifo (void)
read nibbles from FIFO and re-arrange into a parcor frame
static int read_di_fifo (t6721_state *t6721)
void t6721_update_tick (t6721_state *t6721)
run chip for exactly one CPU/System Cycle
void t6721_update_ticks (t6721_state *t6721, int ticks)
run chip for N CPU/System Cycles
void t6721_update_output (t6721_state *t6721, int16_t *buf, int num)
render num samples into output buffer, run remaining cycles (if any)
void t6721_store (t6721_state *t6721, uint8_t data)
uint8_t t6721_read (t6721_state *t6721)
read/write from/to d0..d3
void t6721_reset (t6721_state *t6721)
void t6721_sound_machine_init (t6721_state *t6721, int speed, int cycles_per_sec)
void t6721_sound_machine_init_vbr (t6721_state *t6721, int speed, int cycles_per_sec, int factor)
int t6721_dump (t6721_state *t6721)
int t6721_snapshot_write_module (snapshot_t *s, t6721_state *t6721)
int t6721_snapshot_read_module (snapshot_t *s, t6721_state *t6721)
Variables
int16_t ringbuffer [(0x400)]
int ringbuffer_rptr = 0
int ringbuffer_wptr = 0
int phrase_sample_len = 0
static int ringbuffer_state = 0
float upsmpcnt = 0
float upsmp = 0
static param_t p_from = { 0, 0x21, { 0 } }
static param_t p_to = { 0, 0x21, { 0 } }
static double p_z [11] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }
static uint16_t parcor_param [1+1+10]
static const int parcor_param_len [2][1+1+10]
parameter lengths (bits)
static uint16_t chip_buf = 0
static int chip_bit_i = 0
static int param_i = 0
static FILE * wav_fp = NULL
static size_t wavsize = 0
static const uint8_t wav_header []
static const int framestretch [0x10]
static int parcor_framelen = 12
static int parcor_frametype
static int phrase_samples = 0
static int zero_frames = 0
float up2smp = 0
Macro Definition Documentation
CART_DUMP_VER_MAJOR
#define CART_DUMP_VER_MAJOR 0
snapshot support functions
CART_DUMP_VER_MINOR
#define CART_DUMP_VER_MINOR 0
DBG
#define DBG (x)
DBG_STATUS
#define DBG_STATUS ()
DBGADD
#define DBGADD (x)
PARCOR_BUFFER_LEN
#define PARCOR_BUFFER_LEN (0x400)
PARCOR_OUTPUT_HZ
#define PARCOR_OUTPUT_HZ (8000)
PARMVALUE
#define PARMVALUE (ctx, x) (parcor_param[x] >> (16 - parcor_param_len[(ctx)->cond2_framebits][x]))
RBSTATE_DELAY_SAMPLES
#define RBSTATE_DELAY_SAMPLES (PARCOR_OUTPUT_HZ / 200)
5 ms
RBSTATE_PLAY
#define RBSTATE_PLAY 1
RBSTATE_STOP
#define RBSTATE_STOP 0
SNAP_MODULE_NAME
#define SNAP_MODULE_NAME "T6721"
WRITEWAVFILE
#define WRITEWAVFILE 1
write "test.wav" containing all generated output
Typedef Documentation
param_t
typedef struct param_s param_t
Function Documentation
filter()
static double filter (int i, double ef, double k) static
Referenced by create_file_chooser_filter(), create_layout(), legacy_render(), modern_render(), print_help_topics(), render_subframe(), set_chip_rendermode(), set_pattern(), ui_disk_create_dialog_show(), ui_tape_create_dialog_show(), vice_gtk3_open_file_dialog(), vice_gtk3_resource_filechooser_set_filter(), and vice_gtk3_select_directory_dialog().
fix_header()
static int fix_header (void) static
Referenced by wav_close_file().
get_frame_samples()
static int get_frame_samples (t6721_state * t6721) static
Referenced by set_eos(), and t6721_update_tick().
get_subframe_samples()
static int get_subframe_samples (t6721_state * t6721) static
Referenced by render_silence(), and render_subframe().
output_update_sample()
static int16_t output_update_sample (t6721_state * t6721) static
< 5 ms
Referenced by t6721_update_output().
parcor_output_sample()
static int parcor_output_sample (t6721_state * t6721, int16_t value) static
Referenced by render_silence(), and render_subframe().
parcor_render_frame()
static int parcor_render_frame (t6721_state * t6721, uint16_t * new_param) static
Referenced by t6721_update_tick().
read_di_fifo()
static int read_di_fifo (t6721_state * t6721) static
< 1
< 1
DBGADD(("(%x)", bit));
DBGADD(("<%03x>", chip_buf));
< 6
< 1
< 12
Referenced by t6721_update_tick().
render_silence()
static int render_silence (t6721_state * t6721) static
Referenced by parcor_render_frame().
render_subframe()
static int render_subframe (t6721_state * t6721, int sub_i, int voiced) static
DBG(("voiced %i, energy %f, pitch %02x, phase_inc %f, k: ", voiced, energy, pitch, phase_inc));
DBGADD(("%f, ", k[i]));
DBGADD(("\n"));
Todo:
FIXME: implement the actual pseudo random number generator used on the chip
Referenced by parcor_render_frame().
reset_di_fifo()
static void reset_di_fifo (void) static
read nibbles from FIFO and re-arrange into a parcor frame
Referenced by read_di_fifo(), and set_playing().
ringbuffer_reset()
static void ringbuffer_reset (void) static
Referenced by set_playing().
set_apd()
static void set_apd (t6721_state * t6721, int apd) static
Referenced by t6721_reset(), and t6721_store().
set_dtrd()
static void set_dtrd (t6721_state * t6721, int dtrd) static
Referenced by t6721_reset(), and t6721_update_tick().
set_eos()
static void set_eos (t6721_state * t6721, int eos) static
Todo:
FIXME: confirm: is this correct ?
Referenced by read_di_fifo(), t6721_reset(), t6721_store(), and t6721_update_tick().
set_playing()
static void set_playing (t6721_state * t6721, int playing) static
Todo:
FIXME: find out real value
Referenced by read_di_fifo(), t6721_reset(), and t6721_store().
t6721_dump()
int t6721_dump (t6721_state * t6721)
t6721_read()
uint8_t t6721_read (t6721_state * t6721)
read/write from/to d0..d3
Todo:
FIXME: read-through from speech ROM is missing
t6721_reset()
void t6721_reset (t6721_state * t6721)
t6721_snapshot_read_module()
int t6721_snapshot_read_module (snapshot_t * s, t6721_state * t6721)
t6721_snapshot_write_module()
int t6721_snapshot_write_module (snapshot_t * s, t6721_state * t6721)
Todo:
FIXME: implement snapshot support
t6721_sound_machine_init()
void t6721_sound_machine_init (t6721_state * t6721, int speed, int cycles_per_sec)
t6721_sound_machine_init_vbr()
void t6721_sound_machine_init_vbr (t6721_state * t6721, int speed, int cycles_per_sec, int factor)
t6721_store()
void t6721_store (t6721_state * t6721, uint8_t data)
DBG(("write %2x\n", data));
< filter stages 0: 10 1: 8
< repeat 0: available 1: none
< frame lemgth 0: 20ms 1: 10ms
< bits per frame 0: 48 1: 96
t6721_update_output()
void t6721_update_output (t6721_state * t6721, int16_t * buf, int num)
render num samples into output buffer, run remaining cycles (if any)
update output sound buffer, run chip (remaining ticks)
t6721_update_tick()
void t6721_update_tick (t6721_state * t6721)
run chip for exactly one CPU/System Cycle
run chip for N cpu/system cycles
< 1
< 12
< 6
Todo:
FIXME: confirm: is this correct ?
Referenced by t6721_update_ticks().
t6721_update_ticks()
void t6721_update_ticks (t6721_state * t6721, int ticks)
run chip for N CPU/System Cycles
Referenced by t6721_update_output().
wav_close_file()
static void wav_close_file (void) static
Referenced by wav_create_file().
wav_create_file()
static int wav_create_file (const char * filename) static
Referenced by wav_write_sample().
wav_write_sample()
static int wav_write_sample (int16_t data) static
Referenced by parcor_output_sample().
write_header()
static int write_header (void) static
Referenced by wav_create_file().
Variable Documentation
chip_bit_i
int chip_bit_i = 0 static
Referenced by read_di_fifo(), and reset_di_fifo().
chip_buf
uint16_t chip_buf = 0 static
Referenced by read_di_fifo(), and reset_di_fifo().
framestretch
const int framestretch[0x10] static
Initial value:
=
{
    100,
     70,
     80,
     90,
    100,
    110,
    120,
    130,
    140,
    150,
    155,
    100,
    100,
    100,
    100,
    100
}
Referenced by get_frame_samples(), get_subframe_samples(), and t6721_update_tick().
p_from
param_t p_from = { 0, 0x21, { 0 } } static
Referenced by parcor_render_frame(), and render_subframe().
p_to
param_t p_to = { 0, 0x21, { 0 } } static
Referenced by parcor_render_frame(), and render_subframe().
p_z
double p_z[11] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } static
Referenced by filter().
param_i
int param_i = 0 static
Referenced by read_di_fifo(), and reset_di_fifo().
parcor_framelen
int parcor_framelen = 12 static
Referenced by read_di_fifo(), and t6721_update_tick().
parcor_frametype
int parcor_frametype static
Referenced by read_di_fifo(), and t6721_update_tick().
parcor_param
uint16_t parcor_param[1+1+10] static
Todo:
FIXME: MOVE parcor parameters: energy + pitch + k1..10
Referenced by read_di_fifo(), and t6721_update_tick().
parcor_param_len
const int parcor_param_len[2][1+1+10] static
Initial value:
= {
    {6, 6,   6,  5,  5,  5,   3, 3, 3, 2, 2, 2},
    { 7, 7,  10, 10, 10, 8,   8, 8, 7, 7, 7, 7 }
}
parameter lengths (bits)
Referenced by read_di_fifo(), and t6721_update_tick().
phrase_sample_len
int phrase_sample_len = 0
Referenced by output_update_sample(), parcor_output_sample(), and ringbuffer_reset().
phrase_samples
int phrase_samples = 0 static
Referenced by t6721_update_tick().
ringbuffer
int16_t ringbuffer[(0x400)]
Referenced by output_update_sample(), and parcor_output_sample().
ringbuffer_rptr
int ringbuffer_rptr = 0
Referenced by output_update_sample(), parcor_output_sample(), and ringbuffer_reset().
ringbuffer_state
int ringbuffer_state = 0 static
Referenced by output_update_sample(), and ringbuffer_reset().
ringbuffer_wptr
int ringbuffer_wptr = 0
Referenced by output_update_sample(), parcor_output_sample(), and ringbuffer_reset().
up2smp
float up2smp = 0
Referenced by t6721_sound_machine_init(), t6721_sound_machine_init_vbr(), and t6721_update_output().
upsmp
float upsmp = 0
Referenced by output_update_sample(), t6721_sound_machine_init(), and t6721_sound_machine_init_vbr().
upsmpcnt
float upsmpcnt = 0
Referenced by output_update_sample().
wav_fp
FILE* wav_fp = NULL static
Referenced by fix_header(), wav_close_file(), wav_create_file(), wav_write_sample(), and write_header().
wav_header
const uint8_t wav_header[] static
Initial value:
= {
    'R', 'I', 'F', 'F',
    0, 0, 0, 0,
    'W', 'A', 'V', 'E',
    'f', 'm', 't', ' ',
    16, 0, 0, 0,
    1, 0,
    1, 0,
    0x40, 0x1f, 0, 0,
    0x80, 0x3e, 0, 0,
    2, 0,
    16, 0,
    'd', 'a', 't', 'a',
    0, 0, 0, 0
}
Referenced by fix_header(), and write_header().
wavsize
size_t wavsize = 0 static
Referenced by fix_header(), and wav_write_sample().
zero_frames
int zero_frames = 0 static
Referenced by read_di_fifo().