vsid: monitor/mon_profile.c File Reference
mon_profile.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "lib.h"
#include "machine.h"
#include "maincpu.h"
#include "mon_profile.h"
#include "profiler.h"
#include "profiler_data.h"
Data Structures
struct context_array_s
struct aggregate_stats_s
Typedefs
typedef struct context_array_s context_array_t
typedef struct aggregate_stats_s aggregate_stats_t
Enumerations
enum ContextType {
CONTEXT_ALIASED = 1 ,
CONTEXT_MERGED = 2
}
Functions
static void print_disass_context (profiling_context_t *context, bool print_subcontexts)
static void print_function_line (profiling_context_t *context, int indent, profiling_counter_t total_cycles)
static bool is_aliased (profiling_context_t *context)
static bool is_merged (profiling_context_t *context)
void mon_profile (void)
monitor commands
void mon_profile_action (ACTION action)
static bool init_profiling_data (void)
static void merge_aggregate_contexts (profiling_context_t *output, profiling_context_t *source)
static bool are_aggregates_compatible (profiling_context_t *a, profiling_context_t *b)
static uint16_t parent_function (profiling_context_t *context)
static int pc_dst_compare (void const *a, void const *b)
acending based on pc_dst
static int sort_by_parent_function (void const *a, void const *b)
acending based on pc_dst
static int self_time (void const *a, void const *b)
descending based on total_cycles_self
static int total_time (void const *a, void const *b)
descending based on total_cycles
static void array_sort (context_array_t *arr, int(*compar)(const void *, const void *))
static int binary_search (context_array_t *arr, profiling_context_t *ref, int(*compar)(const void *, const void *))
static void array_append (context_array_t *arr, profiling_context_t *context)
static void array_free (context_array_t *arr)
static aggregate_stats_t * alloc_aggregate_stats (void)
static void free_aggregate_stats (aggregate_stats_t *c)
static void mark_aliases (context_array_t *contexts)
static void recursively_aggregate_matching_functions (profiling_context_t *query_context, uint16_t addr, aggregate_stats_t **stat_list)
static void recursively_aggregate_all_functions (profiling_context_t *query_context, context_array_t *all_functions)
static void array_compact (context_array_t *output, context_array_t const *source, int(*compar)(const void *, const void *))
assuming sorted source array
void mon_profile_flat (int num)
static void print_context_graph (profiling_context_t *context, int depth, int max_depth, profiling_counter_t total_cycles)
void mon_profile_graph (int context_id, int depth)
void mon_profile_func (MON_ADDR function)
static bool is_interrupt (uint16_t src)
static void print_src (uint16_t src)
static void print_dst (uint16_t dst, int max_width, int memory_config)
memory_config -2 will print "{*}"
static int context_memory_config (profiling_context_t *context)
static void print_context_id (profiling_context_t *context, int max_width)
static void print_context_name (profiling_context_t *context, int indent, int max_indent)
static void print_context_line (profiling_context_t *context, int indent, int max_indent, profiling_counter_t total_cycles)
static void print_all_contexts (context_array_t *context_list)
void mon_profile_disass (MON_ADDR function)
static void print_cycle_time (double cycles, int align_column)
static void merge_all_pages (profiling_context_t *target, profiling_context_t *source)
static void merge_all_memory_configs (profiling_context_t *context)
static bool is_branch_instruction (uint16_t mem_config, uint16_t addr, unsigned *opc_size, uint16_t *dest_addr)
void mon_profile_disass_context (int context_id)
static void clear_context_pages (profiling_context_t *context)
static void clear_recursively (profiling_context_t *context, uint16_t addr)
void mon_profile_clear (MON_ADDR function)
Variables
const int min_label_width = 15
Typedef Documentation
aggregate_stats_t
typedef struct aggregate_stats_s aggregate_stats_t
context_array_t
typedef struct context_array_s context_array_t
Enumeration Type Documentation
ContextType
enum ContextType
Enumerator
CONTEXT_ALIASED
CONTEXT_MERGED
Function Documentation
alloc_aggregate_stats()
static aggregate_stats_t * alloc_aggregate_stats (void) static
Referenced by recursively_aggregate_matching_functions().
are_aggregates_compatible()
static bool are_aggregates_compatible (profiling_context_t * a, profiling_context_t * b) static
Referenced by array_compact(), recursively_aggregate_all_functions(), and recursively_aggregate_matching_functions().
array_append()
static void array_append (context_array_t * arr, profiling_context_t * context) static
Referenced by array_compact(), recursively_aggregate_all_functions(), and recursively_aggregate_matching_functions().
array_compact()
static void array_compact (context_array_t * output, context_array_t const * source, int(*)(const void *, const void *) compar) static
assuming sorted source array
Referenced by mon_profile_func().
array_free()
static void array_free (context_array_t * arr) static
Referenced by free_aggregate_stats(), mon_profile_flat(), and mon_profile_func().
array_sort()
static void array_sort (context_array_t * arr, int(*)(const void *, const void *) compar) static
Referenced by mon_profile_flat(), mon_profile_func(), and recursively_aggregate_all_functions().
binary_search()
static int binary_search (context_array_t * arr, profiling_context_t * ref, int(*)(const void *, const void *) compar) static
Referenced by recursively_aggregate_all_functions().
clear_context_pages()
static void clear_context_pages (profiling_context_t * context) static
Referenced by clear_context_pages(), and clear_recursively().
clear_recursively()
static void clear_recursively (profiling_context_t * context, uint16_t addr) static
Referenced by clear_recursively(), and mon_profile_clear().
context_memory_config()
static int context_memory_config (profiling_context_t * context) static
Referenced by print_context_name(), and print_function_line().
free_aggregate_stats()
static void free_aggregate_stats (aggregate_stats_t * c) static
Referenced by free_aggregate_stats(), mon_profile_disass(), and mon_profile_func().
init_profiling_data()
static bool init_profiling_data (void) static
Referenced by mon_profile_clear(), mon_profile_disass(), mon_profile_disass_context(), mon_profile_flat(), mon_profile_func(), and mon_profile_graph().
is_aliased()
static bool is_aliased (profiling_context_t * context) static
Referenced by context_memory_config().
is_branch_instruction()
static bool is_branch_instruction (uint16_t mem_config, uint16_t addr, unsigned * opc_size, uint16_t * dest_addr) static
Referenced by print_disass_context().
is_interrupt()
static bool is_interrupt (uint16_t src) static
Referenced by print_disass_context().
is_merged()
static bool is_merged (profiling_context_t * context) static
Referenced by context_memory_config(), mon_profile_disass(), and print_disass_context().
mark_aliases()
static void mark_aliases (context_array_t * contexts) static
Referenced by mon_profile_flat().
merge_aggregate_contexts()
static void merge_aggregate_contexts (profiling_context_t * output, profiling_context_t * source) static
Referenced by array_compact(), recursively_aggregate_all_functions(), and recursively_aggregate_matching_functions().
merge_all_memory_configs()
static void merge_all_memory_configs (profiling_context_t * context) static
Referenced by print_disass_context().
merge_all_pages()
static void merge_all_pages (profiling_context_t * target, profiling_context_t * source) static
Referenced by merge_all_memory_configs().
mon_profile()
void mon_profile (void)
monitor commands
mon_profile_action()
void mon_profile_action (ACTION action)
Referenced by mon_profile_action().
mon_profile_clear()
void mon_profile_clear (MON_ADDR function)
mon_profile_disass()
void mon_profile_disass (MON_ADDR function)
mon_profile_disass_context()
void mon_profile_disass_context (int context_id)
mon_profile_flat()
void mon_profile_flat (int num)
mon_profile_func()
void mon_profile_func (MON_ADDR function)
mon_profile_graph()
void mon_profile_graph (int context_id, int depth)
parent_function()
static uint16_t parent_function (profiling_context_t * context) static
Referenced by array_compact(), and sort_by_parent_function().
pc_dst_compare()
static int pc_dst_compare (void const * a, void const * b) static
acending based on pc_dst
Referenced by mon_profile_func(), and recursively_aggregate_all_functions().
print_all_contexts()
static void print_all_contexts (context_array_t * context_list) static
Referenced by mon_profile_disass().
print_context_graph()
static void print_context_graph (profiling_context_t * context, int depth, int max_depth, profiling_counter_t total_cycles) static
Referenced by mon_profile_graph(), and print_context_graph().
print_context_id()
static void print_context_id (profiling_context_t * context, int max_width) static
Referenced by print_context_name(), and print_disass_context().
print_context_line()
static void print_context_line (profiling_context_t * context, int indent, int max_indent, profiling_counter_t total_cycles) static
Referenced by print_context_graph().
print_context_name()
static void print_context_name (profiling_context_t * context, int indent, int max_indent) static
Referenced by mon_profile_disass_context(), and print_context_line().
print_cycle_time()
static void print_cycle_time (double cycles, int align_column) static
Referenced by print_disass_context().
print_disass_context()
static void print_disass_context (profiling_context_t * context, bool print_subcontexts) static
Referenced by mon_profile_disass(), and mon_profile_disass_context().
print_dst()
static void print_dst (uint16_t dst, int max_width, int memory_config) static
memory_config -2 will print "{*}"
Referenced by mon_profile_disass(), print_context_name(), and print_function_line().
print_function_line()
static void print_function_line (profiling_context_t * context, int indent, profiling_counter_t total_cycles) static
Referenced by mon_profile_flat(), and mon_profile_func().
print_src()
static void print_src (uint16_t src) static
Referenced by print_context_name(), and print_disass_context().
recursively_aggregate_all_functions()
static void recursively_aggregate_all_functions (profiling_context_t * query_context, context_array_t * all_functions) static
Referenced by mon_profile_flat(), and recursively_aggregate_all_functions().
recursively_aggregate_matching_functions()
static void recursively_aggregate_matching_functions (profiling_context_t * query_context, uint16_t addr, aggregate_stats_t ** stat_list) static
Referenced by mon_profile_disass(), mon_profile_func(), and recursively_aggregate_matching_functions().
self_time()
static int self_time (void const * a, void const * b) static
descending based on total_cycles_self
Referenced by mon_profile_flat(), and mon_profile_func().
sort_by_parent_function()
static int sort_by_parent_function (void const * a, void const * b) static
acending based on pc_dst
Referenced by mon_profile_func().
total_time()
static int total_time (void const * a, void const * b) static
descending based on total_cycles
Referenced by mon_profile_func().
Variable Documentation
min_label_width
const int min_label_width = 15
Referenced by mon_profile_graph(), and print_context_name().