vsid: arch/gtk3/widgets/settings_default_cart.c File Reference
settings_default_cart.c File Reference
GTK3 default cartridge settings.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "debug_gtk3.h"
#include "cartridge.h"
#include "carthelpers.h"
#include "resources.h"
#include "machine.h"
#include "uicart.h"
#include "settings_default_cart.h"
Functions
static const char * get_cart_name_by_id (int id)
Get cartridge name by looking up id in the cartridge info list.
static void update_cart_default_file_widget (void)
Update the file widget by inspecting the CartridgeFile resource.
static void update_cart_default_type_widget (void)
Update the type widget by inspecting the CartridgeType resource.
static void update_cart_file_widget (void)
static void update_cart_type_widget (void)
static void update_buttons (void)
Set button sensitivity based on whether there is a default cart.
static void update_widgets (void)
Update all widgets.
static void attach_callback (void)
Callback triggered from the attach dialog.
static void on_set_default_clicked (GtkWidget *widget, gpointer data)
Handler for the 'clicked' event of the 'set default' button.
static void on_attach_clicked (GtkWidget *widget, gpointer data)
Callback for the attach dialog.
static void on_remove_clicked (GtkWidget *widget, gpointer data)
Handler for the 'clicked' event of the 'Remove' button.
static GtkWidget * create_label (const char *text)
Create left aligned, 8 pixels indented label.
static GtkWidget * create_disabled_entry (void)
Create non-sensitive, non-editable GtkEntry.
static GtkWidget * create_cart_default_file_widget (void)
Create default cart file entry.
static GtkWidget * create_cart_default_type_widget (void)
Create default cart type entry.
static GtkWidget * create_cart_file_widget (void)
Create default cart file entry.
static GtkWidget * create_cart_type_widget (void)
Create cart type entry.
GtkWidget * settings_default_cart_widget_create (GtkWidget *parent)
Create a default cart settings widget for the settings UI.
Variables
static GtkWidget * cart_default_file_widget = NULL
Default cartridge file widget.
static GtkWidget * cart_default_type_widget = NULL
Default cartridge type widget.
static GtkWidget * cart_file_widget = NULL
Current cartridge file widget.
static GtkWidget * cart_type_widget = NULL
Current cartridge type widget.
static GtkWidget * set_default_button = NULL
Button used to set the current cartridge as default.
static GtkWidget * attach_button = NULL
Button to attach a cart.
static GtkWidget * remove_button = NULL
Button to remove the current cart.
static const cartridge_info_t * cart_info_list = NULL
List of cartridge types/names.
Detailed Description
GTK3 default cartridge settings.
Settings UI widget to control default cartridge
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
attach_callback()
static void attach_callback (void) static
Callback triggered from the attach dialog.
Referenced by on_attach_clicked().
create_cart_default_file_widget()
static GtkWidget * create_cart_default_file_widget (void) static
Create default cart file entry.
Returns
GtkEntry
Referenced by settings_default_cart_widget_create().
create_cart_default_type_widget()
static GtkWidget * create_cart_default_type_widget (void) static
Create default cart type entry.
Returns
GtkEntry
Referenced by settings_default_cart_widget_create().
create_cart_file_widget()
static GtkWidget * create_cart_file_widget (void) static
Create default cart file entry.
Returns
GtkEntry
Referenced by settings_default_cart_widget_create().
create_cart_type_widget()
static GtkWidget * create_cart_type_widget (void) static
Create cart type entry.
Returns
GtkEntry
Referenced by settings_default_cart_widget_create().
create_disabled_entry()
static GtkWidget * create_disabled_entry (void) static
Create non-sensitive, non-editable GtkEntry.
Returns
GtkEntry
Referenced by create_cart_default_file_widget(), create_cart_default_type_widget(), create_cart_file_widget(), and create_cart_type_widget().
create_label()
static GtkWidget * create_label (const char * text) static
Create left aligned, 8 pixels indented label.
Parameters
[in] text label text (uses Pango markup)
Returns
GtkLabel
Referenced by settings_default_cart_widget_create().
get_cart_name_by_id()
static const char * get_cart_name_by_id (int id) static
Get cartridge name by looking up id in the cartridge info list.
Parameters
[in] id cartridge ID
Returns
cartridge name
Referenced by update_cart_default_type_widget(), and update_cart_type_widget().
on_attach_clicked()
static void on_attach_clicked (GtkWidget * widget, gpointer data) static
Callback for the attach dialog.
Parameters
[in] widget parent widget
[in] data extra even data (unused)
Referenced by settings_default_cart_widget_create().
on_remove_clicked()
static void on_remove_clicked (GtkWidget * widget, gpointer data) static
Handler for the 'clicked' event of the 'Remove' button.
Unsets the current default cart.
Parameters
[in] widget button triggering the event
[in] data extra event data (unused)
Referenced by settings_default_cart_widget_create().
on_set_default_clicked()
static void on_set_default_clicked (GtkWidget * widget, gpointer data) static
Handler for the 'clicked' event of the 'set default' button.
Parameters
[in] widget button triggering the event
[in] data extra event data (unused)
Referenced by settings_default_cart_widget_create().
settings_default_cart_widget_create()
GtkWidget * settings_default_cart_widget_create (GtkWidget * parent)
Create a default cart settings widget for the settings UI.
Parameters
[in] parent parent widget (ignored)
Returns
GtkGrid
update_buttons()
static void update_buttons (void) static
Set button sensitivity based on whether there is a default cart.
Referenced by settings_default_cart_widget_create(), and update_widgets().
update_cart_default_file_widget()
static void update_cart_default_file_widget (void) static
Update the file widget by inspecting the CartridgeFile resource.
Referenced by settings_default_cart_widget_create(), and update_widgets().
update_cart_default_type_widget()
static void update_cart_default_type_widget (void) static
Update the type widget by inspecting the CartridgeType resource.
Referenced by settings_default_cart_widget_create(), and update_widgets().
update_cart_file_widget()
static void update_cart_file_widget (void) static
Todo:
FIXME: slot
Referenced by settings_default_cart_widget_create(), and update_widgets().
update_cart_type_widget()
static void update_cart_type_widget (void) static
Todo:
FIXME: slot
Referenced by settings_default_cart_widget_create(), and update_widgets().
update_widgets()
static void update_widgets (void) static
Update all widgets.
Referenced by attach_callback(), on_remove_clicked(), and on_set_default_clicked().
Variable Documentation
attach_button
GtkWidget* attach_button = NULL static
Button to attach a cart.
Referenced by settings_default_cart_widget_create().
cart_default_file_widget
GtkWidget* cart_default_file_widget = NULL static
Default cartridge file widget.
Read-only GtkEntry
Referenced by settings_default_cart_widget_create(), and update_cart_default_file_widget().
cart_default_type_widget
GtkWidget* cart_default_type_widget = NULL static
Default cartridge type widget.
Read-only GtkEntry
Referenced by settings_default_cart_widget_create(), and update_cart_default_type_widget().
cart_file_widget
GtkWidget* cart_file_widget = NULL static
Current cartridge file widget.
Read-only GtkEntry
Referenced by settings_default_cart_widget_create(), and update_cart_file_widget().
cart_info_list
const cartridge_info_t* cart_info_list = NULL static
List of cartridge types/names.
Set once in the constructor, using cartridge_get_info_list() via a carthelpers function pointer.
Referenced by get_cart_name_by_id(), settings_default_cart_widget_create(), update_cart_default_type_widget(), and update_cart_type_widget().
cart_type_widget
GtkWidget* cart_type_widget = NULL static
Current cartridge type widget.
Read-only GtkEntry
Referenced by settings_default_cart_widget_create(), and update_cart_type_widget().
remove_button
GtkWidget* remove_button = NULL static
Button to remove the current cart.
Referenced by settings_default_cart_widget_create(), and update_buttons().
set_default_button
GtkWidget* set_default_button = NULL static
Button used to set the current cartridge as default.
Referenced by settings_default_cart_widget_create(), and update_buttons().