x128: arch/gtk3/widgets/petmiscwidget.c File Reference
petmiscwidget.c File Reference
Widget to set the PET Crtc and EoiBlank resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "resources.h"
#include "vice_gtk3.h"
#include "petmiscwidget.h"
Functions
static void on_crtc_toggled (GtkWidget *widget, gpointer user_data)
Handler for the "toggled" event of the CRTC check button.
static void on_blank_toggled (GtkWidget *widget, gpointer user_data)
Handler for the "toggled" event of the EOI Blank check button.
static void on_screen2001_toggled (GtkWidget *widget, gpointer user_data)
Handler for the "toggled" event of the Screen2001 check button.
GtkWidget * pet_misc_widget_create (void)
Create PET miscellaneous settings widget.
void pet_misc_widget_set_crtc_callback (void(*func)(int))
Set function to trigger on Crtc checkbox toggle.
void pet_misc_widget_set_blank_callback (void(*func)(int))
Set function to trigger on EOI-blank checkbox toggle.
void pet_misc_widget_set_screen2001_callback (void(*func)(int))
Set function to trigger on Screen2001 checkbox toggle.
void pet_misc_widget_sync (GtkWidget *widget)
Synchronize widget with its resources.
Variables
static GtkWidget * crtc_widget = NULL
Crtc checkbox.
static GtkWidget * blank_widget = NULL
Blank-on-EOI checkbox.
static GtkWidget * screen2001_widget = NULL
Screen mirrors like the 2001 checkbox.
static void(* user_callback_crtc)(int) = NULL
User-defined callback for changes in the Crtc resource.
static void(* user_callback_blank)(int) = NULL
User-defined callback for changes in the EoiBlank resource.
static void(* user_callback_screen2001)(int) = NULL
User-defined callback for changes in the Screen2001 resource.
Detailed Description
Widget to set the PET Crtc and EoiBlank resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_blank_toggled()
static void on_blank_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the "toggled" event of the EOI Blank check button.
Sets the EoiBlank resource when it has been changed.
Parameters
[in] widget radio button triggering the event
[in] user_data extra data (unused)
Referenced by pet_misc_widget_create().
on_crtc_toggled()
static void on_crtc_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the "toggled" event of the CRTC check button.
Sets the Crtc resource when it has been changed.
Parameters
[in] widget radio button triggering the event
[in] user_data extra data (unused)
Referenced by pet_misc_widget_create().
on_screen2001_toggled()
static void on_screen2001_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the "toggled" event of the Screen2001 check button.
Sets the Screen2001 resource when it has been changed.
Parameters
[in] widget radio button triggering the event
[in] user_data extra data (unused)
Referenced by pet_misc_widget_create().
pet_misc_widget_create()
GtkWidget * pet_misc_widget_create (void)
Create PET miscellaneous settings widget.
Adds check buttons for the Crtc and EoiBlank resources.
Returns
GtkGrid
Referenced by create_pet_layout().
pet_misc_widget_set_blank_callback()
void pet_misc_widget_set_blank_callback (void(*)(int) func)
Set function to trigger on EOI-blank checkbox toggle.
Parameters
[in] func callback function
Referenced by create_pet_layout().
pet_misc_widget_set_crtc_callback()
void pet_misc_widget_set_crtc_callback (void(*)(int) func)
Set function to trigger on Crtc checkbox toggle.
Parameters
[in] func callback function
Referenced by create_pet_layout().
pet_misc_widget_set_screen2001_callback()
void pet_misc_widget_set_screen2001_callback (void(*)(int) func)
Set function to trigger on Screen2001 checkbox toggle.
Parameters
[in] func callback function
Referenced by create_pet_layout().
pet_misc_widget_sync()
void pet_misc_widget_sync (GtkWidget * widget)
Synchronize widget with its resources.
Synchronize the PET misc widget's child widgets with their resources.
Parameters
[in,out] widget PET misc widget
Referenced by machine_model_handler_pet().
Variable Documentation
blank_widget
GtkWidget* blank_widget = NULL static
Blank-on-EOI checkbox.
Referenced by pet_misc_widget_create(), and pet_misc_widget_sync().
crtc_widget
GtkWidget* crtc_widget = NULL static
Crtc checkbox.
Referenced by pet_misc_widget_create(), and pet_misc_widget_sync().
screen2001_widget
GtkWidget* screen2001_widget = NULL static
Screen mirrors like the 2001 checkbox.
Referenced by pet_misc_widget_create(), and pet_misc_widget_sync().
user_callback_blank
void(* user_callback_blank) (int) (int) = NULL static
User-defined callback for changes in the EoiBlank resource.
Referenced by on_blank_toggled(), pet_misc_widget_create(), and pet_misc_widget_set_blank_callback().
user_callback_crtc
void(* user_callback_crtc) (int) (int) = NULL static
User-defined callback for changes in the Crtc resource.
Referenced by on_crtc_toggled(), pet_misc_widget_create(), and pet_misc_widget_set_crtc_callback().
user_callback_screen2001
void(* user_callback_screen2001) (int) (int) = NULL static
User-defined callback for changes in the Screen2001 resource.
Referenced by on_screen2001_toggled(), pet_misc_widget_create(), and pet_misc_widget_set_screen2001_callback().