x128: arch/shared/archdep_boot_path.h File Reference
archdep_boot_path.h File Reference
Retrieve dirname of currently running binary - header.
Functions
const char * archdep_boot_path (void)
Get dirname of currently running binary.
void archdep_boot_path_free (void)
Free memory used by boot path.
Detailed Description
Retrieve dirname of currently running binary - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
archdep_boot_path()
const char * archdep_boot_path (void)
Get dirname of currently running binary.
Retrieve the path to the running binary, excluding binary name.
Note
The path is allocated internally by VICE on the first call and should be freed on emulator shutdown with archdep_boot_path_free().
Returns
directory of running binary
< directory separator as an integer
Referenced by archdep_default_joymap_file_name(), archdep_default_portable_resource_file_name(), archdep_default_sysfile_pathlist(), archdep_get_vice_datadir(), archdep_get_vice_docsdir(), archdep_init(), archdep_user_cache_path(), archdep_user_config_path(), and archdep_user_state_path().
archdep_boot_path_free()
void archdep_boot_path_free (void)
Free memory used by boot path.
This must be called from the emulator shutdown code.
Referenced by archdep_shutdown().