vsid: arch/gtk3/widgets/petramsizewidget.h File Reference
petramsizewidget.h File Reference
Widget to set the PET RAM size - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
GtkWidget * pet_ram_size_widget_create (void)
Create PET RAM size widget.
void pet_ram_size_widget_set_callback (GtkWidget *widget, void(*func)(int))
Set callback on RAM size change.
void pet_ram_size_widget_sync (GtkWidget *widget)
Syncronize widget with its resource.
Detailed Description
Widget to set the PET RAM size - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
pet_ram_size_widget_create()
GtkWidget * pet_ram_size_widget_create (void)
Create PET RAM size widget.
Creates a widget to control the PET's RAM size
Returns
GtkGrid
Referenced by create_pet_layout().
pet_ram_size_widget_set_callback()
void pet_ram_size_widget_set_callback (GtkWidget * widget, void(*)(int) func)
Set callback on RAM size change.
Parameters
[in] widget PET RAM size widget
[in] func callback function
Referenced by create_pet_layout().
pet_ram_size_widget_sync()
void pet_ram_size_widget_sync (GtkWidget * widget)
Syncronize widget with its resource.
Parameters
[in,out] widget PET RAM size widget
Referenced by machine_model_handler_pet().