x128: _i8255a_state Struct Reference
_i8255a_state Struct Reference
#include <i8255a.h>
Data Fields
uint8_t ctrl
uint8_t data [3]
void(* set_pa)(struct _i8255a_state *, uint8_t, int8_t)
void(* set_pb)(struct _i8255a_state *, uint8_t, int8_t)
void(* set_pc)(struct _i8255a_state *, uint8_t, int8_t)
uint8_t(* get_pa)(struct _i8255a_state *, int8_t)
uint8_t(* get_pb)(struct _i8255a_state *, int8_t)
uint8_t(* get_pc)(struct _i8255a_state *, int8_t)
void * p
Field Documentation
ctrl
uint8_t _i8255a_state::ctrl
Referenced by i8255a_peek(), i8255a_read(), i8255a_reset(), i8255a_snapshot_read_data(), i8255a_snapshot_write_data(), and i8255a_store().
data
uint8_t _i8255a_state::data[3]
Referenced by i8255a_read(), i8255a_reset(), i8255a_snapshot_read_data(), i8255a_snapshot_write_data(), and i8255a_store().
get_pa
uint8_t(* _i8255a_state::get_pa) (struct _i8255a_state *, int8_t)
Referenced by cmdhd_setup_context(), i8255a_read(), i8255a_reset(), and i8255a_store().
get_pb
uint8_t(* _i8255a_state::get_pb) (struct _i8255a_state *, int8_t)
Referenced by cmdhd_setup_context(), i8255a_read(), i8255a_reset(), and i8255a_store().
get_pc
uint8_t(* _i8255a_state::get_pc) (struct _i8255a_state *, int8_t)
Referenced by cmdhd_setup_context(), i8255a_read(), i8255a_reset(), and i8255a_store().
p
void* _i8255a_state::p
Referenced by cmdhd_setup_context(), get_pb(), get_pc(), set_pa(), set_pb(), and set_pc().
set_pa
void(* _i8255a_state::set_pa) (struct _i8255a_state *, uint8_t, int8_t)
Referenced by cmdhd_setup_context(), i8255a_reset(), and i8255a_store().
set_pb
void(* _i8255a_state::set_pb) (struct _i8255a_state *, uint8_t, int8_t)
Referenced by cmdhd_setup_context(), i8255a_reset(), and i8255a_store().
set_pc
void(* _i8255a_state::set_pc) (struct _i8255a_state *, uint8_t, int8_t)
Referenced by cmdhd_setup_context(), i8255a_reset(), and i8255a_store().
The documentation for this struct was generated from the following file:
core/i8255a.h