vsid: diskimage/fsimage-p64.h File Reference
fsimage-p64.h File Reference
#include "types.h"
Functions
void fsimage_p64_init (void)
int fsimage_read_p64_image (const disk_image_t *image)
Intial P64 buffer setup.
int fsimage_write_p64_image (const disk_image_t *image)
int fsimage_p64_read_half_track (const struct disk_image_s *image, unsigned int half_track, struct disk_track_s *raw)
int fsimage_p64_write_half_track (struct disk_image_s *image, unsigned int half_track, const struct disk_track_s *raw)
int fsimage_p64_read_sector (const struct disk_image_s *image, uint8_t *buf, const struct disk_addr_s *dadr)
int fsimage_p64_write_sector (struct disk_image_s *image, const uint8_t *buf, const struct disk_addr_s *dadr)
Function Documentation
fsimage_p64_init()
void fsimage_p64_init (void)
Referenced by fsimage_init().
fsimage_p64_read_half_track()
int fsimage_p64_read_half_track (const struct disk_image_s * image, unsigned int half_track, struct disk_track_s * raw)
fsimage_p64_read_sector()
int fsimage_p64_read_sector (const struct disk_image_s * image, uint8_t * buf, const struct disk_addr_s * dadr)
fsimage_p64_write_half_track()
int fsimage_p64_write_half_track (struct disk_image_s * image, unsigned int half_track, const struct disk_track_s * raw)
fsimage_p64_write_sector()
int fsimage_p64_write_sector (struct disk_image_s * image, const uint8_t * buf, const struct disk_addr_s * dadr)
fsimage_read_p64_image()
int fsimage_read_p64_image (const disk_image_t * image)
Intial P64 buffer setup.
Referenced by disk_image_check_for_p64(), and disk_image_read_image().
fsimage_write_p64_image()
int fsimage_write_p64_image (const disk_image_t * image)
Referenced by disk_image_write_p64_image(), fsimage_close(), fsimage_p64_write_half_track(), and fsimage_p64_write_track().