vsid: arch/gtk3/widgets/settings_sidcart.c File Reference
settings_sidcart.c File Reference
Settings widget for SID Cart (Plus4/PET)
#include "vice.h"
#include <gtk/gtk.h>
#include "archdep.h"
#include "machine.h"
#include "sidcart.h"
#include "sidmodelwidget.h"
#include "vice_gtk3.h"
#include "settings_sidcart.h"
Functions
static void set_widgets_sensitivity (gboolean sensitive)
Set sensitivity of widgets.
static void on_sidcart_enable_toggled (GtkWidget *widget, gpointer user_data)
Handler for the 'toggled' event of the SidCart enable widget.
static GtkWidget * label_helper (const char *text)
Create left-aligned label using Pango markup.
static GtkWidget * create_sidcart_enable_widget (void)
Create toggle button to switch the "SidCart" resource.
static GtkWidget * create_sidcart_address_widget (void)
Create widget to set SID I/O base address.
static GtkWidget * create_sidcart_clock_widget (void)
Create widget to set SID clock.
static GtkWidget * create_sidcart_joy_widget (void)
Create SidCart joyport emulation widget (plus4 only)
GtkWidget * settings_sidcart_widget_create (GtkWidget *parent)
Create widget to conrol SID cartridge settings.
Variables
static GtkWidget * sidcart_enable = NULL
SID cart enable toggle button.
static GtkWidget * sid_model = NULL
SID model radiogroup.
static GtkWidget * sid_address = NULL
SID I/O address combobox.
static GtkWidget * sid_clock = NULL
SID clock radiogroup.
static GtkWidget * sid_joy = NULL
SID cart joyport emulation checkbox.
static const vice_gtk3_radiogroup_entry_t sid_base_vic20 []
SID cart I/O base addresses for VIC-20.
static const vice_gtk3_radiogroup_entry_t sid_base_plus4 []
SID cart I/O base addresses for Plus4.
static const vice_gtk3_radiogroup_entry_t sid_base_pet []
SID cart I/O base addresses for PET.
static const vice_gtk3_radiogroup_entry_t sid_clock_vic20 []
SID cart clock for VIC-20.
static const vice_gtk3_radiogroup_entry_t sid_clock_plus4 []
SID cart clock for Plus4.
static const vice_gtk3_radiogroup_entry_t sid_clock_pet []
SID cart clock for PET.
Detailed Description
Settings widget for SID Cart (Plus4/PET)
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_sidcart_address_widget()
static GtkWidget * create_sidcart_address_widget (void) static
Create widget to set SID I/O base address.
Returns
GtkGrid
Referenced by settings_sidcart_widget_create().
create_sidcart_clock_widget()
static GtkWidget * create_sidcart_clock_widget (void) static
Create widget to set SID clock.
Returns
GtkGrid
Referenced by settings_sidcart_widget_create().
create_sidcart_enable_widget()
static GtkWidget * create_sidcart_enable_widget (void) static
Create toggle button to switch the "SidCart" resource.
Returns
GtkGrid
Referenced by settings_sidcart_widget_create().
create_sidcart_joy_widget()
static GtkWidget * create_sidcart_joy_widget (void) static
Create SidCart joyport emulation widget (plus4 only)
Returns
GtkCheckButton
Referenced by settings_sidcart_widget_create().
label_helper()
static GtkWidget * label_helper (const char * text) static
Create left-aligned label using Pango markup.
Parameters
[in] text text for label
Returns
GtkLabel
Referenced by create_sidcart_address_widget(), and create_sidcart_clock_widget().
on_sidcart_enable_toggled()
static void on_sidcart_enable_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the 'toggled' event of the SidCart enable widget.
Enables/disables the model, address and clock widgets depending on the SidCart enabled state.
Parameters
[in] widget SidCart toggle button
[in] user_data unused
Referenced by settings_sidcart_widget_create().
set_widgets_sensitivity()
static void set_widgets_sensitivity (gboolean sensitive) static
Set sensitivity of widgets.
Parameters
[in] sensitive new sensitivity
Referenced by on_sidcart_enable_toggled(), and settings_sidcart_widget_create().
settings_sidcart_widget_create()
GtkWidget * settings_sidcart_widget_create (GtkWidget * parent)
Create widget to conrol SID cartridge settings.
Parameters
[in] parent parent widget
Returns
GtkGrid
Variable Documentation
sid_address
GtkWidget* sid_address = NULL static
SID I/O address combobox.
Referenced by set_widgets_sensitivity(), settings_sidcart_widget_create(), sid_snapshot_read_module_simple(), and sid_snapshot_write_module_simple().
sid_base_pet
const vice_gtk3_radiogroup_entry_t sid_base_pet[] static
Initial value:
= {
    { "$8F00", 0x8f00 },
    { "$E900", 0xe900 },
    { NULL,        -1 }
}
SID cart I/O base addresses for PET.
Referenced by create_sidcart_address_widget().
sid_base_plus4
const vice_gtk3_radiogroup_entry_t sid_base_plus4[] static
Initial value:
= {
    { "$FD40", 0xfd40 },
    { "$FE80", 0xfe80 },
    { NULL,        -1 }
}
SID cart I/O base addresses for Plus4.
Referenced by create_sidcart_address_widget().
sid_base_vic20
const vice_gtk3_radiogroup_entry_t sid_base_vic20[] static
Initial value:
= {
    { "$9800", 0x9800 },
    { "$9C00", 0x9c00 },
    { NULL,        -1 }
}
SID cart I/O base addresses for VIC-20.
Referenced by create_sidcart_address_widget().
sid_clock
GtkWidget* sid_clock = NULL static
SID clock radiogroup.
Referenced by set_widgets_sensitivity(), and settings_sidcart_widget_create().
sid_clock_pet
const vice_gtk3_radiogroup_entry_t sid_clock_pet[] static
Initial value:
= {
    { "C64",  0  },
    { "PET",  1  },
    { NULL,  -1 }
}
SID cart clock for PET.
Referenced by create_sidcart_clock_widget().
sid_clock_plus4
const vice_gtk3_radiogroup_entry_t sid_clock_plus4[] static
Initial value:
= {
    { "C64",    0  },
    { "Plus4",  1  },
    { NULL,    -1 }
}
SID cart clock for Plus4.
Referenced by create_sidcart_clock_widget().
sid_clock_vic20
const vice_gtk3_radiogroup_entry_t sid_clock_vic20[] static
Initial value:
= {
    { "C64",     0  },
    { "VIC-20",  1  },
    { NULL,     -1 }
}
SID cart clock for VIC-20.
Referenced by create_sidcart_clock_widget().
sid_joy
GtkWidget* sid_joy = NULL static
SID cart joyport emulation checkbox.
Plus4 only: emulate the joyport on the SID cart.
Referenced by set_widgets_sensitivity(), and settings_sidcart_widget_create().
sid_model
GtkWidget* sid_model = NULL static
SID model radiogroup.
Referenced by set_widgets_sensitivity(), and settings_sidcart_widget_create().
sidcart_enable
GtkWidget* sidcart_enable = NULL static
SID cart enable toggle button.
Referenced by settings_sidcart_widget_create().