vsid: vicii.h File Reference
vicii.h File Reference
#include "types.h"
Macros
#define VICII_STANDARD 0
#define VICII_EXTENDED 1
#define VICII_DTV 2
#define VICII_NORMAL_BORDERS 0
VICII border mode defines.
#define VICII_FULL_BORDERS 1
#define VICII_DEBUG_BORDERS 2
#define VICII_NO_BORDERS 3
#define VICII_BORDER_MODE(v) (v << 12)
#define VICII_MODEL_PALG 0
VICII model defines (for vicii/) FIXME enum instead?
#define VICII_MODEL_PALG_OLD 1
#define VICII_MODEL_NTSCM 2
#define VICII_MODEL_NTSCM_OLD 3
#define VICII_MODEL_PALN 4
#define VICII_MODEL_6569 0
VICII model defines (for viciisc/) FIXME enum instead?
#define VICII_MODEL_8565 1
PAL, 63 cycle, 9 luma, "new".
#define VICII_MODEL_6569R1 2
PAL, 63 cycle, 5 luma, "old".
#define VICII_MODEL_6567 3
NTSC, 65 cycle, 9 luma, "old".
#define VICII_MODEL_8562 4
NTSC, 65 cycle, 9 luma, "new".
#define VICII_MODEL_6567R56A 5
NTSC, 64 cycle, ? luma, "old".
#define VICII_MODEL_6572 6
PAL-N, 65 cycle, ? luma, "?".
#define VICII_MODEL_NUM 7
Functions
int vicii_resources_init (void)
int vicii_cmdline_options_init (void)
struct raster_s * vicii_init (unsigned int flag)
Initialize the VIC-II emulation.
struct video_canvas_s * vicii_get_canvas (void)
void vicii_reset (void)
Reset the VIC-II chip.
void vicii_set_light_pen (CLOCK mclk, int state)
Set light pen input state.
void vicii_trigger_light_pen (CLOCK mclk)
Trigger the light pen.
CLOCK vicii_lightpen_timing (int x, int y)
Calculate lightpen pulse time based on x/y.
void vicii_set_vbank (int new_vbank)
Phi1 and Phi2 accesses.
void vicii_set_ram_base (uint8_t *base)
void vicii_powerup (void)
void vicii_set_canvas_refresh (int enable)
void vicii_reset_registers (void)
void vicii_update_memory_ptrs_external (void)
void vicii_handle_pending_alarms_external (CLOCK num_write_cycles)
void vicii_handle_pending_alarms_external_write (void)
void vicii_screenshot (struct screenshot_s *screenshot)
void vicii_shutdown (void)
void vicii_change_timing (struct machine_timing_s *machine_timing, int border_mode)
int vicii_dump (void)
void vicii_snapshot_prepare (void)
int vicii_snapshot_write_module (struct snapshot_s *s)
int vicii_snapshot_read_module (struct snapshot_s *s)
void vicii_async_refresh (struct canvas_refresh_s *r)
void vicii_set_phi1_vbank (int num_vbank)
Phi1 accesses.
void vicii_set_phi2_vbank (int num_vbank)
Phi2 accesses.
void vicii_set_phi1_ram_base (uint8_t *base)
void vicii_set_phi2_ram_base (uint8_t *base)
void vicii_set_phi1_addr_options (uint16_t mask, uint16_t offset)
void vicii_set_phi2_addr_options (uint16_t mask, uint16_t offset)
void vicii_set_chargen_addr_options (uint16_t mask, uint16_t value)
void vicii_set_phi1_chargen_addr_options (uint16_t mask, uint16_t value)
void vicii_set_phi2_chargen_addr_options (uint16_t mask, uint16_t value)
CLOCK vicii_clock_add (CLOCK clock, int64_t amount)
8502 specific functions
void vicii_clock_read_stretch (void)
if half cycle is 0, add extra half cycle to stretch
void vicii_clock_write_stretch (void)
int vicii_get_half_cycle (void)
void vicii_memory_refresh_alarm_handler (void)
int vicii_check_memory_refresh (CLOCK clock)
Macro Definition Documentation
VICII_BORDER_MODE
#define VICII_BORDER_MODE (v) (v << 12)
VICII_DEBUG_BORDERS
#define VICII_DEBUG_BORDERS 2
VICII_DTV
#define VICII_DTV 2
VICII_EXTENDED
#define VICII_EXTENDED 1
VICII_FULL_BORDERS
#define VICII_FULL_BORDERS 1
VICII_MODEL_6567
#define VICII_MODEL_6567 3
NTSC, 65 cycle, 9 luma, "old".
VICII_MODEL_6567R56A
#define VICII_MODEL_6567R56A 5
NTSC, 64 cycle, ? luma, "old".
VICII_MODEL_6569
#define VICII_MODEL_6569 0
VICII model defines (for viciisc/) FIXME enum instead?
PAL, 63 cycle, 9 luma, "old"
VICII_MODEL_6569R1
#define VICII_MODEL_6569R1 2
PAL, 63 cycle, 5 luma, "old".
VICII_MODEL_6572
#define VICII_MODEL_6572 6
PAL-N, 65 cycle, ? luma, "?".
VICII_MODEL_8562
#define VICII_MODEL_8562 4
NTSC, 65 cycle, 9 luma, "new".
VICII_MODEL_8565
#define VICII_MODEL_8565 1
PAL, 63 cycle, 9 luma, "new".
VICII_MODEL_NTSCM
#define VICII_MODEL_NTSCM 2
VICII_MODEL_NTSCM_OLD
#define VICII_MODEL_NTSCM_OLD 3
VICII_MODEL_NUM
#define VICII_MODEL_NUM 7
VICII_MODEL_PALG
#define VICII_MODEL_PALG 0
VICII model defines (for vicii/) FIXME enum instead?
VICII_MODEL_PALG_OLD
#define VICII_MODEL_PALG_OLD 1
VICII_MODEL_PALN
#define VICII_MODEL_PALN 4
VICII_NO_BORDERS
#define VICII_NO_BORDERS 3
VICII_NORMAL_BORDERS
#define VICII_NORMAL_BORDERS 0
VICII border mode defines.
VICII_STANDARD
#define VICII_STANDARD 0
Function Documentation
vicii_async_refresh()
void vicii_async_refresh (struct canvas_refresh_s * r)
Referenced by machine_canvas_async_refresh().
vicii_change_timing()
void vicii_change_timing (struct machine_timing_s * machine_timing, int border_mode)
Referenced by machine_change_timing().
vicii_check_memory_refresh()
int vicii_check_memory_refresh (CLOCK clock)
vicii_clock_add()
CLOCK vicii_clock_add (CLOCK clock, int64_t amount)
8502 specific functions
Referenced by vicii_check_memory_refresh(), vicii_clock_write_stretch(), and vicii_memory_refresh_alarm_handler().
vicii_clock_read_stretch()
void vicii_clock_read_stretch (void)
if half cycle is 0, add extra half cycle to stretch
Referenced by vicii_clock_write_stretch().
vicii_clock_write_stretch()
void vicii_clock_write_stretch (void)
vicii_cmdline_options_init()
int vicii_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
vicii_dump()
int vicii_dump (void)
Todo:
FIXME: how does cbm510 work ?
vicii_get_canvas()
struct video_canvas_s * vicii_get_canvas (void)
Referenced by identify_canvas(), machine_canvas_async_refresh(), machine_screenshot(), machine_video_canvas_get(), and vsid_ui_init().
vicii_get_half_cycle()
int vicii_get_half_cycle (void)
vicii_handle_pending_alarms_external()
void vicii_handle_pending_alarms_external (CLOCK num_write_cycles)
Referenced by io_read(), machine_handle_pending_alarms(), pre_peek(), and pre_read().
vicii_handle_pending_alarms_external_write()
void vicii_handle_pending_alarms_external_write (void)
Referenced by io_store(), pre_store(), vicii_handle_pending_alarms_external(), and vicii_store().
vicii_init()
struct raster_s * vicii_init (unsigned int flag)
Initialize the VIC-II emulation.
Referenced by machine_specific_init().
vicii_lightpen_timing()
CLOCK vicii_lightpen_timing (int x, int y)
Calculate lightpen pulse time based on x/y.
Referenced by machine_specific_init().
vicii_memory_refresh_alarm_handler()
void vicii_memory_refresh_alarm_handler (void)
Referenced by vicii_clock_read_stretch().
vicii_powerup()
void vicii_powerup (void)
Referenced by vicii_init().
vicii_reset()
void vicii_reset (void)
Reset the VIC-II chip.
Todo:
FIXME: I am not sure this is exact emulation.
Referenced by machine_specific_reset(), and vicii_powerup().
vicii_reset_registers()
void vicii_reset_registers (void)
Referenced by machine_specific_powerup().
vicii_resources_init()
int vicii_resources_init (void)
< VICII double size
< VICII double size
< VICII double scan
Referenced by machine_resources_init().
vicii_screenshot()
void vicii_screenshot (struct screenshot_s * screenshot)
Referenced by machine_screenshot().
vicii_set_canvas_refresh()
void vicii_set_canvas_refresh (int enable)
vicii_set_chargen_addr_options()
void vicii_set_chargen_addr_options (uint16_t mask, uint16_t value)
Referenced by mem_initialize_memory().
vicii_set_light_pen()
void vicii_set_light_pen (CLOCK mclk, int state)
Set light pen input state.
Referenced by cia1_internal_lightpen_check().
vicii_set_phi1_addr_options()
void vicii_set_phi1_addr_options (uint16_t mask, uint16_t offset)
Todo:
speed optimizations;
faster sprites and registers.
vicii_set_phi1_chargen_addr_options()
void vicii_set_phi1_chargen_addr_options (uint16_t mask, uint16_t value)
vicii_set_phi1_ram_base()
void vicii_set_phi1_ram_base (uint8_t * base)
vicii_set_phi1_vbank()
void vicii_set_phi1_vbank (int num_vbank)
Phi1 accesses.
vicii_set_phi2_addr_options()
void vicii_set_phi2_addr_options (uint16_t mask, uint16_t offset)
vicii_set_phi2_chargen_addr_options()
void vicii_set_phi2_chargen_addr_options (uint16_t mask, uint16_t value)
vicii_set_phi2_ram_base()
void vicii_set_phi2_ram_base (uint8_t * base)
vicii_set_phi2_vbank()
void vicii_set_phi2_vbank (int num_vbank)
Phi2 accesses.
vicii_set_ram_base()
void vicii_set_ram_base (uint8_t * base)
Referenced by c64_256k_cia_set_vbank(), c64_256k_deactivate(), c64_256k_reset(), pia_set_vbank(), plus256k_deactivate(), plus256k_reset(), and plus256k_vicii_store().
vicii_set_vbank()
void vicii_set_vbank (int new_vbank)
Phi1 and Phi2 accesses.
Referenced by mem_set_vbank().
vicii_shutdown()
void vicii_shutdown (void)
Referenced by machine_specific_shutdown().
vicii_snapshot_prepare()
void vicii_snapshot_prepare (void)
Referenced by c64_snapshot_read().
vicii_snapshot_read_module()
int vicii_snapshot_read_module (struct snapshot_s * s)
Todo:
FIXME: initialize changes?
Todo:
FIXME: Recalculate alarms and derived values.
Todo:
FIXME: ‘vicii.ycounter_reset_checked’?
Todo:
FIXME: ‘vicii.force_display_state’?
Todo:
FIXME: initialize changes?
Todo:
FIXME: Recalculate alarms and derived values.
Todo:
FIXME: ‘vicii.ycounter_reset_checked’?
Todo:
FIXME: ‘vicii.force_display_state’?
Referenced by c64_snapshot_read().
vicii_snapshot_write_module()
int vicii_snapshot_write_module (struct snapshot_s * s)
Todo:
FIXME: Dispatch all events?
Todo:
FIXME: Dispatch all events?
Referenced by c64_snapshot_write().
vicii_trigger_light_pen()
void vicii_trigger_light_pen (CLOCK mclk)
Trigger the light pen.
Todo:
FIXME: why ‘+2’?
Referenced by machine_specific_init(), vicii_raster_draw_alarm_handler(), and vicii_set_light_pen().
vicii_update_memory_ptrs_external()
void vicii_update_memory_ptrs_external (void)
Referenced by machine_update_memory_ptrs(), vicii_set_chargen_addr_options(), vicii_set_phi1_addr_options(), vicii_set_phi1_chargen_addr_options(), vicii_set_phi2_addr_options(), and vicii_set_phi2_chargen_addr_options().