vsid: arch/gtk3/widgets/base/selectdirectorydialog.c File Reference
selectdirectorydialog.c File Reference
GtkFileChooser wrapper to select/create a directory.
#include "vice.h"
#include <gtk/gtk.h>
#include "filechooserhelpers.h"
#include "mainlock.h"
#include "ui.h"
#include "selectdirectorydialog.h"
Functions
static void on_response (GtkDialog *dialog, gint response_id, gpointer data)
Handler for 'response' event of the directory-select dialog.
GtkWidget * vice_gtk3_select_directory_dialog (const char *title, const char *proposed, gboolean allow_create, const char *path, void(*callback)(GtkDialog *, char *, gpointer), gpointer param)
Create a 'select directory' dialog.
Variables
static void(* filename_cb)(GtkDialog *, gchar *, gpointer)
Function to call in the response hander.
Detailed Description
GtkFileChooser wrapper to select/create a directory.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_response()
static void on_response (GtkDialog * dialog, gint response_id, gpointer data) static
Handler for 'response' event of the directory-select dialog.
Parameters
[in] dialog directory-select dialog
[in] response_id response ID
[in] data optional data of callback
Referenced by vice_gtk3_select_directory_dialog().
vice_gtk3_select_directory_dialog()
GtkWidget * vice_gtk3_select_directory_dialog (const char * title, const char * proposed, gboolean allow_create, const char * path, void(*)(GtkDialog *, char *, gpointer) callback, gpointer param)
Create a 'select directory' dialog.
The callback is expected to accept three arguments: the dialog, the filename returned from the dialog (NULL indicates the user canceled the dialog) and an optional extra argument passed here as param.
Parameters
[in] title dialog title
[in] proposed proposed directory name (optional)
[in] allow_create allow creating a new directory
[in] path set starting directory (optional)
[in] callback user function to call on response
[in] param optional extra param for the callback
Returns
dialog
Referenced by on_browse_clicked(), and on_fsdir_browse_clicked().
Variable Documentation
filename_cb
void(* filename_cb) (GtkDialog *, gchar *, gpointer) (GtkDialog * , gchar * , gpointer) static
Function to call in the response hander.
This function is called to pass the result back to the user.
Three values are passed: the dialog, the resulting filename (or NULL when the user selected 'Cancel') and an optional gpointer that was passed in the constructor.
Referenced by on_response(), and vice_gtk3_select_directory_dialog().