vsid: core/ciatimer.c File Reference
ciatimer.c File Reference
#include "vice.h"
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include "alarm.h"
#include "ciatimer.h"
#include "snapshot.h"
#include "types.h"
Macros
#define _CIATIMER_C
Functions
void ciat_init_table (void)
void ciat_init (ciat_t *state, const char *name, CLOCK cclk, alarm_t *alarm)
void ciat_reset (ciat_t *state, CLOCK cclk)
timer reset
void ciat_prevent_clock_overflow (ciat_t *state, CLOCK sub)
handle clock overflow.
void ciat_save_snapshot (ciat_t *cia_state, CLOCK cclk, snapshot_module_t *m, int ver)
void ciat_load_snapshot (ciat_t *state, CLOCK cclk, uint16_t cnt, uint16_t latch, uint8_t cr, snapshot_module_t *m, int ver)
Variables
ciat_tstate_t ciat_table [(2<< 13)]
external prototypes
static unsigned int ciat_init_table_initialized = 0
Macro Definition Documentation
_CIATIMER_C
#define _CIATIMER_C
Function Documentation
ciat_init()
void ciat_init (ciat_t * state, const char * name, CLOCK cclk, alarm_t * alarm)
Referenced by ciacore_init().
ciat_init_table()
void ciat_init_table (void)
Referenced by ciacore_init().
ciat_load_snapshot()
void ciat_load_snapshot (ciat_t * state, CLOCK cclk, uint16_t cnt, uint16_t latch, uint8_t cr, snapshot_module_t * m, int ver)
Referenced by ciacore_snapshot_read_module().
ciat_prevent_clock_overflow()
void ciat_prevent_clock_overflow (ciat_t * state, CLOCK sub)
handle clock overflow.
needs update
ciat_reset()
void ciat_reset (ciat_t * state, CLOCK cclk)
timer reset
Referenced by ciacore_reset().
ciat_save_snapshot()
void ciat_save_snapshot (ciat_t * cia_state, CLOCK cclk, snapshot_module_t * m, int ver)
Referenced by ciacore_snapshot_write_module().
Variable Documentation
ciat_init_table_initialized
unsigned int ciat_init_table_initialized = 0 static
Referenced by ciat_init_table().
ciat_table
ciat_tstate_t ciat_table[(2<< 13)]
external prototypes
Referenced by ciat_init_table(), ciat_set_alarm(), and ciat_update().