x128: drive/iec/via4000.h File Reference
via4000.h File Reference
#include "types.h"
Functions
void via4000_setup_context (struct diskunit_context_s *ctxptr)
void via4000_init (struct diskunit_context_s *ctxptr)
void via4000_store (struct diskunit_context_s *ctxptr, uint16_t addr, uint8_t byte)
uint8_t via4000_read (struct diskunit_context_s *ctxptr, uint16_t addr)
uint8_t via4000_peek (struct diskunit_context_s *ctxptr, uint16_t addr)
int via4000_dump (diskunit_context_t *ctxptr, uint16_t addr)
Function Documentation
via4000_dump()
int via4000_dump (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by drivemem_ioreg_list_get().
via4000_init()
void via4000_init (struct diskunit_context_s * ctxptr)
Referenced by iec_drive_init().
via4000_peek()
uint8_t via4000_peek (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memiec_init().
via4000_read()
uint8_t via4000_read (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memiec_init().
via4000_setup_context()
void via4000_setup_context (struct diskunit_context_s * ctxptr)
Referenced by iec_drive_setup_context().
via4000_store()
void via4000_store (struct diskunit_context_s * ctxptr, uint16_t addr, uint8_t byte)
Referenced by memiec_init().