vsid: arch/gtk3/widgets/kernalrevisionwidget.c File Reference
kernalrevisionwidget.c File Reference
GTK3 KERNAL revision widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "types.h"
#include "c64rom.h"
#include "lib.h"
#include "resources.h"
#include "vsync.h"
#include "kernalrevisionwidget.h"
Functions
static int get_revision_index (int rev)
Look up index of revision ID rev.
static void on_revision_toggled (GtkWidget *widget, gpointer user_data)
Handler for the "toggled" event of the revision radio buttons.
GtkWidget * kernal_revision_widget_create (void)
Create KERNAL revision widget (c64/c64sc/c64dtv only)
void kernal_revision_widget_update (GtkWidget *widget, int revision)
Update KERNAL revision widget.
void kernal_revision_widget_sync (GtkWidget *widget)
Synchronize the KERNAL widget with its current value.
void kernal_revision_widget_add_callback (void(*callback)(int))
Add extra callback.
Variables
static const vice_gtk3_radiogroup_entry_t revisions []
List of KERNAL revisions for the C64.
static void(* widget_callback)(int) = NULL
Optional extra callback function.
Detailed Description
GTK3 KERNAL revision widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Groepaz groep.nosp@m.az@g.nosp@m.mx.de
Function Documentation
get_revision_index()
static int get_revision_index (int rev) static
Look up index of revision ID rev.
Parameters
[in] rev revision ID
Returns
index in revisions array or -1 when not found
Referenced by kernal_revision_widget_create(), kernal_revision_widget_sync(), and kernal_revision_widget_update().
kernal_revision_widget_add_callback()
void kernal_revision_widget_add_callback (void(*)(int) callback)
Add extra callback.
Parameters
[in] callback extra callback for widget changes
Referenced by create_c64_layout().
kernal_revision_widget_create()
GtkWidget * kernal_revision_widget_create (void)
Create KERNAL revision widget (c64/c64sc/c64dtv only)
Returns
GtkGrid
Referenced by create_c64_layout().
kernal_revision_widget_sync()
void kernal_revision_widget_sync (GtkWidget * widget)
Synchronize the KERNAL widget with its current value.
Parameters
[in,out] widget KERNAL version widget
Referenced by machine_model_handler_c64().
kernal_revision_widget_update()
void kernal_revision_widget_update (GtkWidget * widget, int revision)
Update KERNAL revision widget.
Parameters
[in,out] widget KERNAL revision widget
[in] revision new revision (
See also
src/c64/c64-resources.h)
on_revision_toggled()
static void on_revision_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the "toggled" event of the revision radio buttons.
Parameters
[in] widget radio button triggering the event
[in] user_data revision ID (int)
Referenced by kernal_revision_widget_create().
Variable Documentation
revisions
const vice_gtk3_radiogroup_entry_t revisions[] static
Initial value:
= {
    { "Revision 1",          1   },
    { "Revision 2",          2   },
    { "Revision 3",          3   },
    { "SX-64",               67   },
    { "C64 GS",              39   },
    { "PET64/Educator64",    100   },
    { "Japanese",            0   },
    { NULL,                 -1 }
}
List of KERNAL revisions for the C64.
Taken from scr/c64/c64-resources.h
Referenced by get_revision_index(), kernal_revision_widget_create(), and vdc_model_widget_create().
widget_callback
void(* widget_callback) (int) (int) = NULL static
Optional extra callback function.
Referenced by kernal_revision_widget_add_callback(), and on_revision_toggled().