vsid: arch/shared/hotkeys/vhkkeysyms.h File Reference
vhkkeysyms.h File Reference
UI-agnostic key symbols and names.
#include <stdint.h>
#include "hotkeystypes.h"
Macros
#define VHK_KEY_BackSpace 0xff08
Back space, back char.
#define VHK_KEY_Tab 0xff09
#define VHK_KEY_Linefeed 0xff0a
Linefeed, LF.
#define VHK_KEY_Clear 0xff0b
#define VHK_KEY_Return 0xff0d
Return, enter.
#define VHK_KEY_Pause 0xff13
Pause, hold.
#define VHK_KEY_Scroll_Lock 0xff14
#define VHK_KEY_Sys_Req 0xff15
#define VHK_KEY_Escape 0xff1b
#define VHK_KEY_Delete 0xffff
Delete, rubout.
#define VHK_KEY_Home 0xff50
#define VHK_KEY_Left 0xff51
Move left, left arrow.
#define VHK_KEY_Up 0xff52
Move up, up arrow.
#define VHK_KEY_Right 0xff53
Move right, right arrow.
#define VHK_KEY_Down 0xff54
Move down, down arrow.
#define VHK_KEY_Prior 0xff55
Prior, previous.
#define VHK_KEY_Page_Up 0xff55
#define VHK_KEY_Next 0xff56
Next.
#define VHK_KEY_Page_Down 0xff56
#define VHK_KEY_End 0xff57
EOL.
#define VHK_KEY_Begin 0xff58
BOL.
#define VHK_KEY_Select 0xff60
Misc functions.
#define VHK_KEY_Print 0xff61
#define VHK_KEY_Execute 0xff62
Execute, run, do.
#define VHK_KEY_Insert 0xff63
Insert, insert here.
#define VHK_KEY_Undo 0xff65
#define VHK_KEY_Redo 0xff66
Redo, again.
#define VHK_KEY_Menu 0xff67
#define VHK_KEY_Find 0xff68
Find, search.
#define VHK_KEY_Cancel 0xff69
Cancel, stop, abort, exit.
#define VHK_KEY_Help 0xff6a
Help.
#define VHK_KEY_Break 0xff6b
#define VHK_KEY_Mode_switch 0xff7e
Character set switch.
#define VHK_KEY_script_switch 0xff7e
Alias for mode_switch.
#define VHK_KEY_KP_Space 0xff80
Keypad functions, keypad numbers cleverly chosen to map to ASCII.
#define VHK_KEY_KP_Tab 0xff89
#define VHK_KEY_KP_Enter 0xff8d
Enter.
#define VHK_KEY_KP_F1 0xff91
PF1, KP_A, ...
#define VHK_KEY_KP_F2 0xff92
#define VHK_KEY_KP_F3 0xff93
#define VHK_KEY_KP_F4 0xff94
#define VHK_KEY_KP_Home 0xff95
#define VHK_KEY_KP_Left 0xff96
#define VHK_KEY_KP_Up 0xff97
#define VHK_KEY_KP_Right 0xff98
#define VHK_KEY_KP_Down 0xff99
#define VHK_KEY_KP_Prior 0xff9a
#define VHK_KEY_KP_Page_Up 0xff9a
#define VHK_KEY_KP_Next 0xff9b
#define VHK_KEY_KP_Page_Down 0xff9b
#define VHK_KEY_KP_End 0xff9c
#define VHK_KEY_KP_Begin 0xff9d
#define VHK_KEY_KP_Insert 0xff9e
#define VHK_KEY_KP_Delete 0xff9f
#define VHK_KEY_KP_Equal 0xffbd
Equals.
#define VHK_KEY_KP_Multiply 0xffaa
#define VHK_KEY_KP_Add 0xffab
#define VHK_KEY_KP_Separator 0xffac
Separator, often comma.
#define VHK_KEY_KP_Subtract 0xffad
#define VHK_KEY_KP_Decimal 0xffae
#define VHK_KEY_KP_Divide 0xffaf
#define VHK_KEY_KP_0 0xffb0
#define VHK_KEY_KP_1 0xffb1
#define VHK_KEY_KP_2 0xffb2
#define VHK_KEY_KP_3 0xffb3
#define VHK_KEY_KP_4 0xffb4
#define VHK_KEY_KP_5 0xffb5
#define VHK_KEY_KP_6 0xffb6
#define VHK_KEY_KP_7 0xffb7
#define VHK_KEY_KP_8 0xffb8
#define VHK_KEY_KP_9 0xffb9
#define VHK_KEY_F1 0xffbe
Function keys.
#define VHK_KEY_F2 0xffbf
#define VHK_KEY_F3 0xffc0
#define VHK_KEY_F4 0xffc1
#define VHK_KEY_F5 0xffc2
#define VHK_KEY_F6 0xffc3
#define VHK_KEY_F7 0xffc4
#define VHK_KEY_F8 0xffc5
#define VHK_KEY_F9 0xffc6
#define VHK_KEY_F10 0xffc7
#define VHK_KEY_F11 0xffc8
#define VHK_KEY_F12 0xffc9
#define VHK_KEY_F13 0xffca
#define VHK_KEY_F14 0xffcb
#define VHK_KEY_F15 0xffcc
#define VHK_KEY_F16 0xffcd
#define VHK_KEY_F17 0xffce
#define VHK_KEY_F18 0xffcf
#define VHK_KEY_F19 0xffd0
#define VHK_KEY_F20 0xffd1
#define VHK_KEY_F21 0xffd2
#define VHK_KEY_F22 0xffd3
#define VHK_KEY_F23 0xffd4
#define VHK_KEY_F24 0xffd5
#define VHK_KEY_F25 0xffd6
#define VHK_KEY_F26 0xffd7
#define VHK_KEY_F27 0xffd8
#define VHK_KEY_F28 0xffd9
#define VHK_KEY_F29 0xffda
#define VHK_KEY_F30 0xffdb
#define VHK_KEY_F31 0xffdc
#define VHK_KEY_F32 0xffdd
#define VHK_KEY_F33 0xffde
#define VHK_KEY_F34 0xffdf
#define VHK_KEY_F35 0xffe0
#define VHK_KEY_space 0x0020
U+0020 SPACE.
#define VHK_KEY_exclam 0x0021
U+0021 EXCLAMATION MARK.
#define VHK_KEY_quotedbl 0x0022
U+0022 QUOTATION MARK.
#define VHK_KEY_numbersign 0x0023
U+0023 NUMBER SIGN.
#define VHK_KEY_dollar 0x0024
U+0024 DOLLAR SIGN.
#define VHK_KEY_percent 0x0025
U+0025 PERCENT SIGN.
#define VHK_KEY_ampersand 0x0026
U+0026 AMPERSAND.
#define VHK_KEY_apostrophe 0x0027
U+0027 APOSTROPHE.
#define VHK_KEY_quoteright 0x0027
deprecated
#define VHK_KEY_parenleft 0x0028
U+0028 LEFT PARENTHESIS.
#define VHK_KEY_parenright 0x0029
U+0029 RIGHT PARENTHESIS.
#define VHK_KEY_asterisk 0x002a
U+002A ASTERISK.
#define VHK_KEY_plus 0x002b
U+002B PLUS SIGN.
#define VHK_KEY_comma 0x002c
U+002C COMMA.
#define VHK_KEY_minus 0x002d
U+002D HYPHEN-MINUS.
#define VHK_KEY_period 0x002e
U+002E FULL STOP.
#define VHK_KEY_slash 0x002f
U+002F SOLIDUS.
#define VHK_KEY_0 0x0030
U+0030 DIGIT ZERO.
#define VHK_KEY_1 0x0031
U+0031 DIGIT ONE.
#define VHK_KEY_2 0x0032
U+0032 DIGIT TWO.
#define VHK_KEY_3 0x0033
U+0033 DIGIT THREE.
#define VHK_KEY_4 0x0034
U+0034 DIGIT FOUR.
#define VHK_KEY_5 0x0035
U+0035 DIGIT FIVE.
#define VHK_KEY_6 0x0036
U+0036 DIGIT SIX.
#define VHK_KEY_7 0x0037
U+0037 DIGIT SEVEN.
#define VHK_KEY_8 0x0038
U+0038 DIGIT EIGHT.
#define VHK_KEY_9 0x0039
U+0039 DIGIT NINE.
#define VHK_KEY_colon 0x003a
U+003A COLON.
#define VHK_KEY_semicolon 0x003b
U+003B SEMICOLON.
#define VHK_KEY_less 0x003c
U+003C LESS-THAN SIGN.
#define VHK_KEY_equal 0x003d
U+003D EQUALS SIGN.
#define VHK_KEY_greater 0x003e
U+003E GREATER-THAN SIGN.
#define VHK_KEY_question 0x003f
U+003F QUESTION MARK.
#define VHK_KEY_at 0x0040
U+0040 COMMERCIAL AT.
#define VHK_KEY_A 0x0041
Upper case letters, conveniently mapping to ASCII.
#define VHK_KEY_B 0x0042
#define VHK_KEY_C 0x0043
#define VHK_KEY_D 0x0044
#define VHK_KEY_E 0x0045
#define VHK_KEY_F 0x0046
#define VHK_KEY_G 0x0047
#define VHK_KEY_H 0x0048
#define VHK_KEY_I 0x0049
#define VHK_KEY_J 0x004a
#define VHK_KEY_K 0x004b
#define VHK_KEY_L 0x004c
#define VHK_KEY_M 0x004d
#define VHK_KEY_N 0x004e
#define VHK_KEY_O 0x004f
#define VHK_KEY_P 0x0050
#define VHK_KEY_Q 0x0051
#define VHK_KEY_R 0x0052
#define VHK_KEY_S 0x0053
#define VHK_KEY_T 0x0054
#define VHK_KEY_U 0x0055
#define VHK_KEY_V 0x0056
#define VHK_KEY_W 0x0057
#define VHK_KEY_X 0x0058
#define VHK_KEY_Y 0x0059
#define VHK_KEY_Z 0x005a
#define VHK_KEY_bracketleft 0x005b
U+005B LEFT SQUARE BRACKET.
#define VHK_KEY_backslash 0x005c
U+005C REVERSE SOLIDUS.
#define VHK_KEY_bracketright 0x005d
U+005D RIGHT SQUARE BRACKET.
#define VHK_KEY_asciicircum 0x005e
U+005E CIRCUMFLEX ACCENT.
#define VHK_KEY_underscore 0x005f
U+005F LOW LINE.
#define VHK_KEY_grave 0x0060
U+0060 GRAVE ACCENT.
#define VHK_KEY_quoteleft 0x0060
deprecated
#define VHK_KEY_a 0x0061
Lower case letters, conveniently mapping to ASCII.
#define VHK_KEY_b 0x0062
#define VHK_KEY_c 0x0063
#define VHK_KEY_d 0x0064
#define VHK_KEY_e 0x0065
#define VHK_KEY_f 0x0066
#define VHK_KEY_g 0x0067
#define VHK_KEY_h 0x0068
#define VHK_KEY_i 0x0069
#define VHK_KEY_j 0x006a
#define VHK_KEY_k 0x006b
#define VHK_KEY_l 0x006c
#define VHK_KEY_m 0x006d
#define VHK_KEY_n 0x006e
#define VHK_KEY_o 0x006f
#define VHK_KEY_p 0x0070
#define VHK_KEY_q 0x0071
#define VHK_KEY_r 0x0072
#define VHK_KEY_s 0x0073
#define VHK_KEY_t 0x0074
#define VHK_KEY_u 0x0075
#define VHK_KEY_v 0x0076
#define VHK_KEY_w 0x0077
#define VHK_KEY_x 0x0078
#define VHK_KEY_y 0x0079
#define VHK_KEY_z 0x007a
#define VHK_KEY_braceleft 0x007b
U+007B LEFT CURLY BRACKET.
#define VHK_KEY_bar 0x007c
U+007C VERTICAL LINE.
#define VHK_KEY_braceright 0x007d
U+007D RIGHT CURLY BRACKET.
#define VHK_KEY_asciitilde 0x007e
U+007E TILDE.
#define VHK_KEY_nobreakspace 0x00a0
Special, "international", keys.
#define VHK_KEY_exclamdown 0x00a1
U+00A1 INVERTED EXCLAMATION MARK.
#define VHK_KEY_cent 0x00a2
U+00A2 CENT SIGN.
#define VHK_KEY_sterling 0x00a3
U+00A3 POUND SIGN.
#define VHK_KEY_currency 0x00a4
U+00A4 CURRENCY SIGN.
#define VHK_KEY_yen 0x00a5
U+00A5 YEN SIGN.
#define VHK_KEY_brokenbar 0x00a6
U+00A6 BROKEN BAR.
#define VHK_KEY_section 0x00a7
U+00A7 SECTION SIGN.
#define VHK_KEY_diaeresis 0x00a8
U+00A8 DIAERESIS.
#define VHK_KEY_copyright 0x00a9
U+00A9 COPYRIGHT SIGN.
#define VHK_KEY_ordfeminine 0x00aa
U+00AA FEMININE ORDINAL INDICATOR.
#define VHK_KEY_guillemotleft 0x00ab
U+00AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK.
#define VHK_KEY_notsign 0x00ac
U+00AC NOT SIGN.
#define VHK_KEY_hyphen 0x00ad
U+00AD SOFT HYPHEN.
#define VHK_KEY_registered 0x00ae
U+00AE REGISTERED SIGN.
#define VHK_KEY_macron 0x00af
U+00AF MACRON.
#define VHK_KEY_degree 0x00b0
U+00B0 DEGREE SIGN.
#define VHK_KEY_plusminus 0x00b1
U+00B1 PLUS-MINUS SIGN.
#define VHK_KEY_twosuperior 0x00b2
U+00B2 SUPERSCRIPT TWO.
#define VHK_KEY_threesuperior 0x00b3
U+00B3 SUPERSCRIPT THREE.
#define VHK_KEY_acute 0x00b4
U+00B4 ACUTE ACCENT.
#define VHK_KEY_mu 0x00b5
U+00B5 MICRO SIGN.
#define VHK_KEY_paragraph 0x00b6
U+00B6 PILCROW SIGN.
#define VHK_KEY_periodcentered 0x00b7
U+00B7 MIDDLE DOT.
#define VHK_KEY_cedilla 0x00b8
U+00B8 CEDILLA.
#define VHK_KEY_onesuperior 0x00b9
U+00B9 SUPERSCRIPT ONE.
#define VHK_KEY_masculine 0x00ba
U+00BA MASCULINE ORDINAL INDICATOR.
#define VHK_KEY_guillemotright 0x00bb
U+00BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK.
#define VHK_KEY_onequarter 0x00bc
U+00BC VULGAR FRACTION ONE QUARTER.
#define VHK_KEY_onehalf 0x00bd
U+00BD VULGAR FRACTION ONE HALF.
#define VHK_KEY_threequarters 0x00be
U+00BE VULGAR FRACTION THREE QUARTERS.
#define VHK_KEY_questiondown 0x00bf
U+00BF INVERTED QUESTION MARK.
#define VHK_KEY_Agrave 0x00c0
U+00C0 LATIN CAPITAL LETTER A WITH GRAVE.
#define VHK_KEY_Aacute 0x00c1
U+00C1 LATIN CAPITAL LETTER A WITH ACUTE.
#define VHK_KEY_Acircumflex 0x00c2
U+00C2 LATIN CAPITAL LETTER A WITH CIRCUMFLEX.
#define VHK_KEY_Atilde 0x00c3
U+00C3 LATIN CAPITAL LETTER A WITH TILDE.
#define VHK_KEY_Adiaeresis 0x00c4
U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS.
#define VHK_KEY_Aring 0x00c5
U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE.
#define VHK_KEY_AE 0x00c6
U+00C6 LATIN CAPITAL LETTER AE.
#define VHK_KEY_Ccedilla 0x00c7
U+00C7 LATIN CAPITAL LETTER C WITH CEDILLA.
#define VHK_KEY_Egrave 0x00c8
U+00C8 LATIN CAPITAL LETTER E WITH GRAVE.
#define VHK_KEY_Eacute 0x00c9
U+00C9 LATIN CAPITAL LETTER E WITH ACUTE.
#define VHK_KEY_Ecircumflex 0x00ca
U+00CA LATIN CAPITAL LETTER E WITH CIRCUMFLEX.
#define VHK_KEY_Ediaeresis 0x00cb
U+00CB LATIN CAPITAL LETTER E WITH DIAERESIS.
#define VHK_KEY_Igrave 0x00cc
U+00CC LATIN CAPITAL LETTER I WITH GRAVE.
#define VHK_KEY_Iacute 0x00cd
U+00CD LATIN CAPITAL LETTER I WITH ACUTE.
#define VHK_KEY_Icircumflex 0x00ce
U+00CE LATIN CAPITAL LETTER I WITH CIRCUMFLEX.
#define VHK_KEY_Idiaeresis 0x00cf
U+00CF LATIN CAPITAL LETTER I WITH DIAERESIS.
#define VHK_KEY_ETH 0x00d0
U+00D0 LATIN CAPITAL LETTER ETH.
#define VHK_KEY_Eth 0x00d0
deprecated
#define VHK_KEY_Ntilde 0x00d1
U+00D1 LATIN CAPITAL LETTER N WITH TILDE.
#define VHK_KEY_Ograve 0x00d2
U+00D2 LATIN CAPITAL LETTER O WITH GRAVE.
#define VHK_KEY_Oacute 0x00d3
U+00D3 LATIN CAPITAL LETTER O WITH ACUTE.
#define VHK_KEY_Ocircumflex 0x00d4
U+00D4 LATIN CAPITAL LETTER O WITH CIRCUMFLEX.
#define VHK_KEY_Otilde 0x00d5
U+00D5 LATIN CAPITAL LETTER O WITH TILDE.
#define VHK_KEY_Odiaeresis 0x00d6
U+00D6 LATIN CAPITAL LETTER O WITH DIAERESIS.
#define VHK_KEY_multiply 0x00d7
U+00D7 MULTIPLICATION SIGN.
#define VHK_KEY_Oslash 0x00d8
U+00D8 LATIN CAPITAL LETTER O WITH STROKE.
#define VHK_KEY_Ooblique 0x00d8
U+00D8 LATIN CAPITAL LETTER O WITH STROKE.
#define VHK_KEY_Ugrave 0x00d9
U+00D9 LATIN CAPITAL LETTER U WITH GRAVE.
#define VHK_KEY_Uacute 0x00da
U+00DA LATIN CAPITAL LETTER U WITH ACUTE.
#define VHK_KEY_Ucircumflex 0x00db
U+00DB LATIN CAPITAL LETTER U WITH CIRCUMFLEX.
#define VHK_KEY_Udiaeresis 0x00dc
U+00DC LATIN CAPITAL LETTER U WITH DIAERESIS.
#define VHK_KEY_Yacute 0x00dd
U+00DD LATIN CAPITAL LETTER Y WITH ACUTE.
#define VHK_KEY_THORN 0x00de
U+00DE LATIN CAPITAL LETTER THORN.
#define VHK_KEY_Thorn 0x00de
deprecated
#define VHK_KEY_ssharp 0x00df
U+00DF LATIN SMALL LETTER SHARP S.
#define VHK_KEY_agrave 0x00e0
U+00E0 LATIN SMALL LETTER A WITH GRAVE.
#define VHK_KEY_aacute 0x00e1
U+00E1 LATIN SMALL LETTER A WITH ACUTE.
#define VHK_KEY_acircumflex 0x00e2
U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX.
#define VHK_KEY_atilde 0x00e3
U+00E3 LATIN SMALL LETTER A WITH TILDE.
#define VHK_KEY_adiaeresis 0x00e4
U+00E4 LATIN SMALL LETTER A WITH DIAERESIS.
#define VHK_KEY_aring 0x00e5
U+00E5 LATIN SMALL LETTER A WITH RING ABOVE.
#define VHK_KEY_ae 0x00e6
U+00E6 LATIN SMALL LETTER AE.
#define VHK_KEY_ccedilla 0x00e7
U+00E7 LATIN SMALL LETTER C WITH CEDILLA.
#define VHK_KEY_egrave 0x00e8
U+00E8 LATIN SMALL LETTER E WITH GRAVE.
#define VHK_KEY_eacute 0x00e9
U+00E9 LATIN SMALL LETTER E WITH ACUTE.
#define VHK_KEY_ecircumflex 0x00ea
U+00EA LATIN SMALL LETTER E WITH CIRCUMFLEX.
#define VHK_KEY_ediaeresis 0x00eb
U+00EB LATIN SMALL LETTER E WITH DIAERESIS.
#define VHK_KEY_igrave 0x00ec
U+00EC LATIN SMALL LETTER I WITH GRAVE.
#define VHK_KEY_iacute 0x00ed
U+00ED LATIN SMALL LETTER I WITH ACUTE.
#define VHK_KEY_icircumflex 0x00ee
U+00EE LATIN SMALL LETTER I WITH CIRCUMFLEX.
#define VHK_KEY_idiaeresis 0x00ef
U+00EF LATIN SMALL LETTER I WITH DIAERESIS.
#define VHK_KEY_eth 0x00f0
U+00F0 LATIN SMALL LETTER ETH.
#define VHK_KEY_ntilde 0x00f1
U+00F1 LATIN SMALL LETTER N WITH TILDE.
#define VHK_KEY_ograve 0x00f2
U+00F2 LATIN SMALL LETTER O WITH GRAVE.
#define VHK_KEY_oacute 0x00f3
U+00F3 LATIN SMALL LETTER O WITH ACUTE.
#define VHK_KEY_ocircumflex 0x00f4
U+00F4 LATIN SMALL LETTER O WITH CIRCUMFLEX.
#define VHK_KEY_otilde 0x00f5
U+00F5 LATIN SMALL LETTER O WITH TILDE.
#define VHK_KEY_odiaeresis 0x00f6
U+00F6 LATIN SMALL LETTER O WITH DIAERESIS.
#define VHK_KEY_division 0x00f7
U+00F7 DIVISION SIGN.
#define VHK_KEY_oslash 0x00f8
U+00F8 LATIN SMALL LETTER O WITH STROKE.
#define VHK_KEY_ooblique 0x00f8
U+00F8 LATIN SMALL LETTER O WITH STROKE.
#define VHK_KEY_ugrave 0x00f9
U+00F9 LATIN SMALL LETTER U WITH GRAVE.
#define VHK_KEY_uacute 0x00fa
U+00FA LATIN SMALL LETTER U WITH ACUTE.
#define VHK_KEY_ucircumflex 0x00fb
U+00FB LATIN SMALL LETTER U WITH CIRCUMFLEX.
#define VHK_KEY_udiaeresis 0x00fc
U+00FC LATIN SMALL LETTER U WITH DIAERESIS.
#define VHK_KEY_yacute 0x00fd
U+00FD LATIN SMALL LETTER Y WITH ACUTE.
#define VHK_KEY_thorn 0x00fe
U+00FE LATIN SMALL LETTER THORN.
#define VHK_KEY_ydiaeresis 0x00ff
U+00FF LATIN SMALL LETTER Y WITH DIAERESIS.
#define VHK_MOD_NONE 0x0000
Key modifier masks.
#define VHK_MOD_ALT 0x0001
#define VHK_MOD_COMMAND 0x0002
#define VHK_MOD_CONTROL 0x0004
#define VHK_MOD_HYPER 0x0008
#define VHK_MOD_META 0x0010
#define VHK_MOD_OPTION 0x0020
#define VHK_MOD_SHIFT 0x0040
#define VHK_MOD_SUPER 0x0080
Functions
uint32_t vhk_keysym_from_name (const char *name)
Get keysym value from name.
const char * vhk_keysym_name (uint32_t vice_keysym)
Get keysym name from value.
uint32_t vhk_modifier_from_name (const char *name, const char **endptr)
Parse string for modifier name and return modifier bit.
const char * vhk_modifier_name (uint32_t vice_modifier)
Get modifier name.
char * vhk_modmask_name (uint32_t vice_modmask)
Get string of modifier names for a modifier mask.
char * vhk_hotkey_label (uint32_t vice_keysym, uint32_t vice_modmask)
Get accelerator label for a hotkey.
Detailed Description
UI-agnostic key symbols and names.
UI-agnostic key symbols and names - header.
List of keysym identifiers used by the hotkeys in VICE. Each UI toolkit has its own key symbols and names, so we need a way to refer to keys that isn't toolkit-specific.
The keysyms provided here are taken from /usr/include/X11/keysymdef.h.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
VHK_KEY_0
#define VHK_KEY_0 0x0030
U+0030 DIGIT ZERO.
VHK_KEY_1
#define VHK_KEY_1 0x0031
U+0031 DIGIT ONE.
VHK_KEY_2
#define VHK_KEY_2 0x0032
U+0032 DIGIT TWO.
VHK_KEY_3
#define VHK_KEY_3 0x0033
U+0033 DIGIT THREE.
VHK_KEY_4
#define VHK_KEY_4 0x0034
U+0034 DIGIT FOUR.
VHK_KEY_5
#define VHK_KEY_5 0x0035
U+0035 DIGIT FIVE.
VHK_KEY_6
#define VHK_KEY_6 0x0036
U+0036 DIGIT SIX.
VHK_KEY_7
#define VHK_KEY_7 0x0037
U+0037 DIGIT SEVEN.
VHK_KEY_8
#define VHK_KEY_8 0x0038
U+0038 DIGIT EIGHT.
VHK_KEY_9
#define VHK_KEY_9 0x0039
U+0039 DIGIT NINE.
VHK_KEY_A
#define VHK_KEY_A 0x0041
Upper case letters, conveniently mapping to ASCII.
VHK_KEY_a
#define VHK_KEY_a 0x0061
Lower case letters, conveniently mapping to ASCII.
VHK_KEY_Aacute
#define VHK_KEY_Aacute 0x00c1
U+00C1 LATIN CAPITAL LETTER A WITH ACUTE.
VHK_KEY_aacute
#define VHK_KEY_aacute 0x00e1
U+00E1 LATIN SMALL LETTER A WITH ACUTE.
VHK_KEY_Acircumflex
#define VHK_KEY_Acircumflex 0x00c2
U+00C2 LATIN CAPITAL LETTER A WITH CIRCUMFLEX.
VHK_KEY_acircumflex
#define VHK_KEY_acircumflex 0x00e2
U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX.
VHK_KEY_acute
#define VHK_KEY_acute 0x00b4
U+00B4 ACUTE ACCENT.
VHK_KEY_Adiaeresis
#define VHK_KEY_Adiaeresis 0x00c4
U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS.
VHK_KEY_adiaeresis
#define VHK_KEY_adiaeresis 0x00e4
U+00E4 LATIN SMALL LETTER A WITH DIAERESIS.
VHK_KEY_AE
#define VHK_KEY_AE 0x00c6
U+00C6 LATIN CAPITAL LETTER AE.
VHK_KEY_ae
#define VHK_KEY_ae 0x00e6
U+00E6 LATIN SMALL LETTER AE.
VHK_KEY_Agrave
#define VHK_KEY_Agrave 0x00c0
U+00C0 LATIN CAPITAL LETTER A WITH GRAVE.
VHK_KEY_agrave
#define VHK_KEY_agrave 0x00e0
U+00E0 LATIN SMALL LETTER A WITH GRAVE.
VHK_KEY_ampersand
#define VHK_KEY_ampersand 0x0026
U+0026 AMPERSAND.
VHK_KEY_apostrophe
#define VHK_KEY_apostrophe 0x0027
U+0027 APOSTROPHE.
VHK_KEY_Aring
#define VHK_KEY_Aring 0x00c5
U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE.
VHK_KEY_aring
#define VHK_KEY_aring 0x00e5
U+00E5 LATIN SMALL LETTER A WITH RING ABOVE.
VHK_KEY_asciicircum
#define VHK_KEY_asciicircum 0x005e
U+005E CIRCUMFLEX ACCENT.
VHK_KEY_asciitilde
#define VHK_KEY_asciitilde 0x007e
U+007E TILDE.
VHK_KEY_asterisk
#define VHK_KEY_asterisk 0x002a
U+002A ASTERISK.
VHK_KEY_at
#define VHK_KEY_at 0x0040
U+0040 COMMERCIAL AT.
VHK_KEY_Atilde
#define VHK_KEY_Atilde 0x00c3
U+00C3 LATIN CAPITAL LETTER A WITH TILDE.
VHK_KEY_atilde
#define VHK_KEY_atilde 0x00e3
U+00E3 LATIN SMALL LETTER A WITH TILDE.
VHK_KEY_B
#define VHK_KEY_B 0x0042
VHK_KEY_b
#define VHK_KEY_b 0x0062
VHK_KEY_backslash
#define VHK_KEY_backslash 0x005c
U+005C REVERSE SOLIDUS.
VHK_KEY_BackSpace
#define VHK_KEY_BackSpace 0xff08
Back space, back char.
VHK_KEY_bar
#define VHK_KEY_bar 0x007c
U+007C VERTICAL LINE.
VHK_KEY_Begin
#define VHK_KEY_Begin 0xff58
BOL.
VHK_KEY_braceleft
#define VHK_KEY_braceleft 0x007b
U+007B LEFT CURLY BRACKET.
VHK_KEY_braceright
#define VHK_KEY_braceright 0x007d
U+007D RIGHT CURLY BRACKET.
VHK_KEY_bracketleft
#define VHK_KEY_bracketleft 0x005b
U+005B LEFT SQUARE BRACKET.
VHK_KEY_bracketright
#define VHK_KEY_bracketright 0x005d
U+005D RIGHT SQUARE BRACKET.
VHK_KEY_Break
#define VHK_KEY_Break 0xff6b
VHK_KEY_brokenbar
#define VHK_KEY_brokenbar 0x00a6
U+00A6 BROKEN BAR.
VHK_KEY_C
#define VHK_KEY_C 0x0043
VHK_KEY_c
#define VHK_KEY_c 0x0063
VHK_KEY_Cancel
#define VHK_KEY_Cancel 0xff69
Cancel, stop, abort, exit.
VHK_KEY_Ccedilla
#define VHK_KEY_Ccedilla 0x00c7
U+00C7 LATIN CAPITAL LETTER C WITH CEDILLA.
VHK_KEY_ccedilla
#define VHK_KEY_ccedilla 0x00e7
U+00E7 LATIN SMALL LETTER C WITH CEDILLA.
VHK_KEY_cedilla
#define VHK_KEY_cedilla 0x00b8
U+00B8 CEDILLA.
VHK_KEY_cent
#define VHK_KEY_cent 0x00a2
U+00A2 CENT SIGN.
VHK_KEY_Clear
#define VHK_KEY_Clear 0xff0b
VHK_KEY_colon
#define VHK_KEY_colon 0x003a
U+003A COLON.
VHK_KEY_comma
#define VHK_KEY_comma 0x002c
U+002C COMMA.
VHK_KEY_copyright
#define VHK_KEY_copyright 0x00a9
U+00A9 COPYRIGHT SIGN.
VHK_KEY_currency
#define VHK_KEY_currency 0x00a4
U+00A4 CURRENCY SIGN.
VHK_KEY_D
#define VHK_KEY_D 0x0044
VHK_KEY_d
#define VHK_KEY_d 0x0064
VHK_KEY_degree
#define VHK_KEY_degree 0x00b0
U+00B0 DEGREE SIGN.
VHK_KEY_Delete
#define VHK_KEY_Delete 0xffff
Delete, rubout.
VHK_KEY_diaeresis
#define VHK_KEY_diaeresis 0x00a8
U+00A8 DIAERESIS.
VHK_KEY_division
#define VHK_KEY_division 0x00f7
U+00F7 DIVISION SIGN.
VHK_KEY_dollar
#define VHK_KEY_dollar 0x0024
U+0024 DOLLAR SIGN.
VHK_KEY_Down
#define VHK_KEY_Down 0xff54
Move down, down arrow.
VHK_KEY_E
#define VHK_KEY_E 0x0045
VHK_KEY_e
#define VHK_KEY_e 0x0065
VHK_KEY_Eacute
#define VHK_KEY_Eacute 0x00c9
U+00C9 LATIN CAPITAL LETTER E WITH ACUTE.
VHK_KEY_eacute
#define VHK_KEY_eacute 0x00e9
U+00E9 LATIN SMALL LETTER E WITH ACUTE.
VHK_KEY_Ecircumflex
#define VHK_KEY_Ecircumflex 0x00ca
U+00CA LATIN CAPITAL LETTER E WITH CIRCUMFLEX.
VHK_KEY_ecircumflex
#define VHK_KEY_ecircumflex 0x00ea
U+00EA LATIN SMALL LETTER E WITH CIRCUMFLEX.
VHK_KEY_Ediaeresis
#define VHK_KEY_Ediaeresis 0x00cb
U+00CB LATIN CAPITAL LETTER E WITH DIAERESIS.
VHK_KEY_ediaeresis
#define VHK_KEY_ediaeresis 0x00eb
U+00EB LATIN SMALL LETTER E WITH DIAERESIS.
VHK_KEY_Egrave
#define VHK_KEY_Egrave 0x00c8
U+00C8 LATIN CAPITAL LETTER E WITH GRAVE.
VHK_KEY_egrave
#define VHK_KEY_egrave 0x00e8
U+00E8 LATIN SMALL LETTER E WITH GRAVE.
VHK_KEY_End
#define VHK_KEY_End 0xff57
EOL.
VHK_KEY_equal
#define VHK_KEY_equal 0x003d
U+003D EQUALS SIGN.
VHK_KEY_Escape
#define VHK_KEY_Escape 0xff1b
VHK_KEY_ETH
#define VHK_KEY_ETH 0x00d0
U+00D0 LATIN CAPITAL LETTER ETH.
VHK_KEY_Eth
#define VHK_KEY_Eth 0x00d0
deprecated
VHK_KEY_eth
#define VHK_KEY_eth 0x00f0
U+00F0 LATIN SMALL LETTER ETH.
VHK_KEY_exclam
#define VHK_KEY_exclam 0x0021
U+0021 EXCLAMATION MARK.
VHK_KEY_exclamdown
#define VHK_KEY_exclamdown 0x00a1
U+00A1 INVERTED EXCLAMATION MARK.
VHK_KEY_Execute
#define VHK_KEY_Execute 0xff62
Execute, run, do.
VHK_KEY_F
#define VHK_KEY_F 0x0046
VHK_KEY_f
#define VHK_KEY_f 0x0066
VHK_KEY_F1
#define VHK_KEY_F1 0xffbe
Function keys.
VHK_KEY_F10
#define VHK_KEY_F10 0xffc7
VHK_KEY_F11
#define VHK_KEY_F11 0xffc8
VHK_KEY_F12
#define VHK_KEY_F12 0xffc9
VHK_KEY_F13
#define VHK_KEY_F13 0xffca
VHK_KEY_F14
#define VHK_KEY_F14 0xffcb
VHK_KEY_F15
#define VHK_KEY_F15 0xffcc
VHK_KEY_F16
#define VHK_KEY_F16 0xffcd
VHK_KEY_F17
#define VHK_KEY_F17 0xffce
VHK_KEY_F18
#define VHK_KEY_F18 0xffcf
VHK_KEY_F19
#define VHK_KEY_F19 0xffd0
VHK_KEY_F2
#define VHK_KEY_F2 0xffbf
VHK_KEY_F20
#define VHK_KEY_F20 0xffd1
VHK_KEY_F21
#define VHK_KEY_F21 0xffd2
VHK_KEY_F22
#define VHK_KEY_F22 0xffd3
VHK_KEY_F23
#define VHK_KEY_F23 0xffd4
VHK_KEY_F24
#define VHK_KEY_F24 0xffd5
VHK_KEY_F25
#define VHK_KEY_F25 0xffd6
VHK_KEY_F26
#define VHK_KEY_F26 0xffd7
VHK_KEY_F27
#define VHK_KEY_F27 0xffd8
VHK_KEY_F28
#define VHK_KEY_F28 0xffd9
VHK_KEY_F29
#define VHK_KEY_F29 0xffda
VHK_KEY_F3
#define VHK_KEY_F3 0xffc0
VHK_KEY_F30
#define VHK_KEY_F30 0xffdb
VHK_KEY_F31
#define VHK_KEY_F31 0xffdc
VHK_KEY_F32
#define VHK_KEY_F32 0xffdd
VHK_KEY_F33
#define VHK_KEY_F33 0xffde
VHK_KEY_F34
#define VHK_KEY_F34 0xffdf
VHK_KEY_F35
#define VHK_KEY_F35 0xffe0
VHK_KEY_F4
#define VHK_KEY_F4 0xffc1
VHK_KEY_F5
#define VHK_KEY_F5 0xffc2
VHK_KEY_F6
#define VHK_KEY_F6 0xffc3
VHK_KEY_F7
#define VHK_KEY_F7 0xffc4
VHK_KEY_F8
#define VHK_KEY_F8 0xffc5
VHK_KEY_F9
#define VHK_KEY_F9 0xffc6
VHK_KEY_Find
#define VHK_KEY_Find 0xff68
Find, search.
VHK_KEY_G
#define VHK_KEY_G 0x0047
VHK_KEY_g
#define VHK_KEY_g 0x0067
VHK_KEY_grave
#define VHK_KEY_grave 0x0060
U+0060 GRAVE ACCENT.
VHK_KEY_greater
#define VHK_KEY_greater 0x003e
U+003E GREATER-THAN SIGN.
VHK_KEY_guillemotleft
#define VHK_KEY_guillemotleft 0x00ab
U+00AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK.
VHK_KEY_guillemotright
#define VHK_KEY_guillemotright 0x00bb
U+00BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK.
VHK_KEY_H
#define VHK_KEY_H 0x0048
VHK_KEY_h
#define VHK_KEY_h 0x0068
VHK_KEY_Help
#define VHK_KEY_Help 0xff6a
Help.
VHK_KEY_Home
#define VHK_KEY_Home 0xff50
VHK_KEY_hyphen
#define VHK_KEY_hyphen 0x00ad
U+00AD SOFT HYPHEN.
VHK_KEY_I
#define VHK_KEY_I 0x0049
VHK_KEY_i
#define VHK_KEY_i 0x0069
VHK_KEY_Iacute
#define VHK_KEY_Iacute 0x00cd
U+00CD LATIN CAPITAL LETTER I WITH ACUTE.
VHK_KEY_iacute
#define VHK_KEY_iacute 0x00ed
U+00ED LATIN SMALL LETTER I WITH ACUTE.
VHK_KEY_Icircumflex
#define VHK_KEY_Icircumflex 0x00ce
U+00CE LATIN CAPITAL LETTER I WITH CIRCUMFLEX.
VHK_KEY_icircumflex
#define VHK_KEY_icircumflex 0x00ee
U+00EE LATIN SMALL LETTER I WITH CIRCUMFLEX.
VHK_KEY_Idiaeresis
#define VHK_KEY_Idiaeresis 0x00cf
U+00CF LATIN CAPITAL LETTER I WITH DIAERESIS.
VHK_KEY_idiaeresis
#define VHK_KEY_idiaeresis 0x00ef
U+00EF LATIN SMALL LETTER I WITH DIAERESIS.
VHK_KEY_Igrave
#define VHK_KEY_Igrave 0x00cc
U+00CC LATIN CAPITAL LETTER I WITH GRAVE.
VHK_KEY_igrave
#define VHK_KEY_igrave 0x00ec
U+00EC LATIN SMALL LETTER I WITH GRAVE.
VHK_KEY_Insert
#define VHK_KEY_Insert 0xff63
Insert, insert here.
VHK_KEY_J
#define VHK_KEY_J 0x004a
VHK_KEY_j
#define VHK_KEY_j 0x006a
VHK_KEY_K
#define VHK_KEY_K 0x004b
VHK_KEY_k
#define VHK_KEY_k 0x006b
VHK_KEY_KP_0
#define VHK_KEY_KP_0 0xffb0
VHK_KEY_KP_1
#define VHK_KEY_KP_1 0xffb1
VHK_KEY_KP_2
#define VHK_KEY_KP_2 0xffb2
VHK_KEY_KP_3
#define VHK_KEY_KP_3 0xffb3
VHK_KEY_KP_4
#define VHK_KEY_KP_4 0xffb4
VHK_KEY_KP_5
#define VHK_KEY_KP_5 0xffb5
VHK_KEY_KP_6
#define VHK_KEY_KP_6 0xffb6
VHK_KEY_KP_7
#define VHK_KEY_KP_7 0xffb7
VHK_KEY_KP_8
#define VHK_KEY_KP_8 0xffb8
VHK_KEY_KP_9
#define VHK_KEY_KP_9 0xffb9
VHK_KEY_KP_Add
#define VHK_KEY_KP_Add 0xffab
VHK_KEY_KP_Begin
#define VHK_KEY_KP_Begin 0xff9d
VHK_KEY_KP_Decimal
#define VHK_KEY_KP_Decimal 0xffae
VHK_KEY_KP_Delete
#define VHK_KEY_KP_Delete 0xff9f
VHK_KEY_KP_Divide
#define VHK_KEY_KP_Divide 0xffaf
VHK_KEY_KP_Down
#define VHK_KEY_KP_Down 0xff99
VHK_KEY_KP_End
#define VHK_KEY_KP_End 0xff9c
VHK_KEY_KP_Enter
#define VHK_KEY_KP_Enter 0xff8d
Enter.
VHK_KEY_KP_Equal
#define VHK_KEY_KP_Equal 0xffbd
Equals.
VHK_KEY_KP_F1
#define VHK_KEY_KP_F1 0xff91
PF1, KP_A, ...
VHK_KEY_KP_F2
#define VHK_KEY_KP_F2 0xff92
VHK_KEY_KP_F3
#define VHK_KEY_KP_F3 0xff93
VHK_KEY_KP_F4
#define VHK_KEY_KP_F4 0xff94
VHK_KEY_KP_Home
#define VHK_KEY_KP_Home 0xff95
VHK_KEY_KP_Insert
#define VHK_KEY_KP_Insert 0xff9e
VHK_KEY_KP_Left
#define VHK_KEY_KP_Left 0xff96
VHK_KEY_KP_Multiply
#define VHK_KEY_KP_Multiply 0xffaa
VHK_KEY_KP_Next
#define VHK_KEY_KP_Next 0xff9b
VHK_KEY_KP_Page_Down
#define VHK_KEY_KP_Page_Down 0xff9b
VHK_KEY_KP_Page_Up
#define VHK_KEY_KP_Page_Up 0xff9a
VHK_KEY_KP_Prior
#define VHK_KEY_KP_Prior 0xff9a
VHK_KEY_KP_Right
#define VHK_KEY_KP_Right 0xff98
VHK_KEY_KP_Separator
#define VHK_KEY_KP_Separator 0xffac
Separator, often comma.
VHK_KEY_KP_Space
#define VHK_KEY_KP_Space 0xff80
Keypad functions, keypad numbers cleverly chosen to map to ASCII.
Space
VHK_KEY_KP_Subtract
#define VHK_KEY_KP_Subtract 0xffad
VHK_KEY_KP_Tab
#define VHK_KEY_KP_Tab 0xff89
VHK_KEY_KP_Up
#define VHK_KEY_KP_Up 0xff97
VHK_KEY_L
#define VHK_KEY_L 0x004c
VHK_KEY_l
#define VHK_KEY_l 0x006c
VHK_KEY_Left
#define VHK_KEY_Left 0xff51
Move left, left arrow.
VHK_KEY_less
#define VHK_KEY_less 0x003c
U+003C LESS-THAN SIGN.
VHK_KEY_Linefeed
#define VHK_KEY_Linefeed 0xff0a
Linefeed, LF.
VHK_KEY_M
#define VHK_KEY_M 0x004d
VHK_KEY_m
#define VHK_KEY_m 0x006d
VHK_KEY_macron
#define VHK_KEY_macron 0x00af
U+00AF MACRON.
VHK_KEY_masculine
#define VHK_KEY_masculine 0x00ba
U+00BA MASCULINE ORDINAL INDICATOR.
VHK_KEY_Menu
#define VHK_KEY_Menu 0xff67
VHK_KEY_minus
#define VHK_KEY_minus 0x002d
U+002D HYPHEN-MINUS.
VHK_KEY_Mode_switch
#define VHK_KEY_Mode_switch 0xff7e
Character set switch.
VHK_KEY_mu
#define VHK_KEY_mu 0x00b5
U+00B5 MICRO SIGN.
VHK_KEY_multiply
#define VHK_KEY_multiply 0x00d7
U+00D7 MULTIPLICATION SIGN.
VHK_KEY_N
#define VHK_KEY_N 0x004e
VHK_KEY_n
#define VHK_KEY_n 0x006e
VHK_KEY_Next
#define VHK_KEY_Next 0xff56
Next.
VHK_KEY_nobreakspace
#define VHK_KEY_nobreakspace 0x00a0
Special, "international", keys.
U+00A0 NO-BREAK SPACE
VHK_KEY_notsign
#define VHK_KEY_notsign 0x00ac
U+00AC NOT SIGN.
VHK_KEY_Ntilde
#define VHK_KEY_Ntilde 0x00d1
U+00D1 LATIN CAPITAL LETTER N WITH TILDE.
VHK_KEY_ntilde
#define VHK_KEY_ntilde 0x00f1
U+00F1 LATIN SMALL LETTER N WITH TILDE.
VHK_KEY_numbersign
#define VHK_KEY_numbersign 0x0023
U+0023 NUMBER SIGN.
VHK_KEY_O
#define VHK_KEY_O 0x004f
VHK_KEY_o
#define VHK_KEY_o 0x006f
VHK_KEY_Oacute
#define VHK_KEY_Oacute 0x00d3
U+00D3 LATIN CAPITAL LETTER O WITH ACUTE.
VHK_KEY_oacute
#define VHK_KEY_oacute 0x00f3
U+00F3 LATIN SMALL LETTER O WITH ACUTE.
VHK_KEY_Ocircumflex
#define VHK_KEY_Ocircumflex 0x00d4
U+00D4 LATIN CAPITAL LETTER O WITH CIRCUMFLEX.
VHK_KEY_ocircumflex
#define VHK_KEY_ocircumflex 0x00f4
U+00F4 LATIN SMALL LETTER O WITH CIRCUMFLEX.
VHK_KEY_Odiaeresis
#define VHK_KEY_Odiaeresis 0x00d6
U+00D6 LATIN CAPITAL LETTER O WITH DIAERESIS.
VHK_KEY_odiaeresis
#define VHK_KEY_odiaeresis 0x00f6
U+00F6 LATIN SMALL LETTER O WITH DIAERESIS.
VHK_KEY_Ograve
#define VHK_KEY_Ograve 0x00d2
U+00D2 LATIN CAPITAL LETTER O WITH GRAVE.
VHK_KEY_ograve
#define VHK_KEY_ograve 0x00f2
U+00F2 LATIN SMALL LETTER O WITH GRAVE.
VHK_KEY_onehalf
#define VHK_KEY_onehalf 0x00bd
U+00BD VULGAR FRACTION ONE HALF.
VHK_KEY_onequarter
#define VHK_KEY_onequarter 0x00bc
U+00BC VULGAR FRACTION ONE QUARTER.
VHK_KEY_onesuperior
#define VHK_KEY_onesuperior 0x00b9
U+00B9 SUPERSCRIPT ONE.
VHK_KEY_Ooblique
#define VHK_KEY_Ooblique 0x00d8
U+00D8 LATIN CAPITAL LETTER O WITH STROKE.
VHK_KEY_ooblique
#define VHK_KEY_ooblique 0x00f8
U+00F8 LATIN SMALL LETTER O WITH STROKE.
VHK_KEY_ordfeminine
#define VHK_KEY_ordfeminine 0x00aa
U+00AA FEMININE ORDINAL INDICATOR.
VHK_KEY_Oslash
#define VHK_KEY_Oslash 0x00d8
U+00D8 LATIN CAPITAL LETTER O WITH STROKE.
VHK_KEY_oslash
#define VHK_KEY_oslash 0x00f8
U+00F8 LATIN SMALL LETTER O WITH STROKE.
VHK_KEY_Otilde
#define VHK_KEY_Otilde 0x00d5
U+00D5 LATIN CAPITAL LETTER O WITH TILDE.
VHK_KEY_otilde
#define VHK_KEY_otilde 0x00f5
U+00F5 LATIN SMALL LETTER O WITH TILDE.
VHK_KEY_P
#define VHK_KEY_P 0x0050
VHK_KEY_p
#define VHK_KEY_p 0x0070
VHK_KEY_Page_Down
#define VHK_KEY_Page_Down 0xff56
VHK_KEY_Page_Up
#define VHK_KEY_Page_Up 0xff55
VHK_KEY_paragraph
#define VHK_KEY_paragraph 0x00b6
U+00B6 PILCROW SIGN.
VHK_KEY_parenleft
#define VHK_KEY_parenleft 0x0028
U+0028 LEFT PARENTHESIS.
VHK_KEY_parenright
#define VHK_KEY_parenright 0x0029
U+0029 RIGHT PARENTHESIS.
VHK_KEY_Pause
#define VHK_KEY_Pause 0xff13
Pause, hold.
VHK_KEY_percent
#define VHK_KEY_percent 0x0025
U+0025 PERCENT SIGN.
VHK_KEY_period
#define VHK_KEY_period 0x002e
U+002E FULL STOP.
VHK_KEY_periodcentered
#define VHK_KEY_periodcentered 0x00b7
U+00B7 MIDDLE DOT.
VHK_KEY_plus
#define VHK_KEY_plus 0x002b
U+002B PLUS SIGN.
VHK_KEY_plusminus
#define VHK_KEY_plusminus 0x00b1
U+00B1 PLUS-MINUS SIGN.
VHK_KEY_Print
#define VHK_KEY_Print 0xff61
VHK_KEY_Prior
#define VHK_KEY_Prior 0xff55
Prior, previous.
VHK_KEY_Q
#define VHK_KEY_Q 0x0051
VHK_KEY_q
#define VHK_KEY_q 0x0071
VHK_KEY_question
#define VHK_KEY_question 0x003f
U+003F QUESTION MARK.
VHK_KEY_questiondown
#define VHK_KEY_questiondown 0x00bf
U+00BF INVERTED QUESTION MARK.
VHK_KEY_quotedbl
#define VHK_KEY_quotedbl 0x0022
U+0022 QUOTATION MARK.
VHK_KEY_quoteleft
#define VHK_KEY_quoteleft 0x0060
deprecated
VHK_KEY_quoteright
#define VHK_KEY_quoteright 0x0027
deprecated
VHK_KEY_R
#define VHK_KEY_R 0x0052
VHK_KEY_r
#define VHK_KEY_r 0x0072
VHK_KEY_Redo
#define VHK_KEY_Redo 0xff66
Redo, again.
VHK_KEY_registered
#define VHK_KEY_registered 0x00ae
U+00AE REGISTERED SIGN.
VHK_KEY_Return
#define VHK_KEY_Return 0xff0d
Return, enter.
VHK_KEY_Right
#define VHK_KEY_Right 0xff53
Move right, right arrow.
VHK_KEY_S
#define VHK_KEY_S 0x0053
VHK_KEY_s
#define VHK_KEY_s 0x0073
VHK_KEY_script_switch
#define VHK_KEY_script_switch 0xff7e
Alias for mode_switch.
VHK_KEY_Scroll_Lock
#define VHK_KEY_Scroll_Lock 0xff14
VHK_KEY_section
#define VHK_KEY_section 0x00a7
U+00A7 SECTION SIGN.
VHK_KEY_Select
#define VHK_KEY_Select 0xff60
Misc functions.
Select, mark
VHK_KEY_semicolon
#define VHK_KEY_semicolon 0x003b
U+003B SEMICOLON.
VHK_KEY_slash
#define VHK_KEY_slash 0x002f
U+002F SOLIDUS.
VHK_KEY_space
#define VHK_KEY_space 0x0020
U+0020 SPACE.
VHK_KEY_ssharp
#define VHK_KEY_ssharp 0x00df
U+00DF LATIN SMALL LETTER SHARP S.
VHK_KEY_sterling
#define VHK_KEY_sterling 0x00a3
U+00A3 POUND SIGN.
VHK_KEY_Sys_Req
#define VHK_KEY_Sys_Req 0xff15
VHK_KEY_T
#define VHK_KEY_T 0x0054
VHK_KEY_t
#define VHK_KEY_t 0x0074
VHK_KEY_Tab
#define VHK_KEY_Tab 0xff09
VHK_KEY_THORN
#define VHK_KEY_THORN 0x00de
U+00DE LATIN CAPITAL LETTER THORN.
VHK_KEY_Thorn
#define VHK_KEY_Thorn 0x00de
deprecated
VHK_KEY_thorn
#define VHK_KEY_thorn 0x00fe
U+00FE LATIN SMALL LETTER THORN.
VHK_KEY_threequarters
#define VHK_KEY_threequarters 0x00be
U+00BE VULGAR FRACTION THREE QUARTERS.
VHK_KEY_threesuperior
#define VHK_KEY_threesuperior 0x00b3
U+00B3 SUPERSCRIPT THREE.
VHK_KEY_twosuperior
#define VHK_KEY_twosuperior 0x00b2
U+00B2 SUPERSCRIPT TWO.
VHK_KEY_U
#define VHK_KEY_U 0x0055
VHK_KEY_u
#define VHK_KEY_u 0x0075
VHK_KEY_Uacute
#define VHK_KEY_Uacute 0x00da
U+00DA LATIN CAPITAL LETTER U WITH ACUTE.
VHK_KEY_uacute
#define VHK_KEY_uacute 0x00fa
U+00FA LATIN SMALL LETTER U WITH ACUTE.
VHK_KEY_Ucircumflex
#define VHK_KEY_Ucircumflex 0x00db
U+00DB LATIN CAPITAL LETTER U WITH CIRCUMFLEX.
VHK_KEY_ucircumflex
#define VHK_KEY_ucircumflex 0x00fb
U+00FB LATIN SMALL LETTER U WITH CIRCUMFLEX.
VHK_KEY_Udiaeresis
#define VHK_KEY_Udiaeresis 0x00dc
U+00DC LATIN CAPITAL LETTER U WITH DIAERESIS.
VHK_KEY_udiaeresis
#define VHK_KEY_udiaeresis 0x00fc
U+00FC LATIN SMALL LETTER U WITH DIAERESIS.
VHK_KEY_Ugrave
#define VHK_KEY_Ugrave 0x00d9
U+00D9 LATIN CAPITAL LETTER U WITH GRAVE.
VHK_KEY_ugrave
#define VHK_KEY_ugrave 0x00f9
U+00F9 LATIN SMALL LETTER U WITH GRAVE.
VHK_KEY_underscore
#define VHK_KEY_underscore 0x005f
U+005F LOW LINE.
VHK_KEY_Undo
#define VHK_KEY_Undo 0xff65
VHK_KEY_Up
#define VHK_KEY_Up 0xff52
Move up, up arrow.
VHK_KEY_V
#define VHK_KEY_V 0x0056
VHK_KEY_v
#define VHK_KEY_v 0x0076
VHK_KEY_W
#define VHK_KEY_W 0x0057
VHK_KEY_w
#define VHK_KEY_w 0x0077
VHK_KEY_X
#define VHK_KEY_X 0x0058
VHK_KEY_x
#define VHK_KEY_x 0x0078
VHK_KEY_Y
#define VHK_KEY_Y 0x0059
VHK_KEY_y
#define VHK_KEY_y 0x0079
VHK_KEY_Yacute
#define VHK_KEY_Yacute 0x00dd
U+00DD LATIN CAPITAL LETTER Y WITH ACUTE.
VHK_KEY_yacute
#define VHK_KEY_yacute 0x00fd
U+00FD LATIN SMALL LETTER Y WITH ACUTE.
VHK_KEY_ydiaeresis
#define VHK_KEY_ydiaeresis 0x00ff
U+00FF LATIN SMALL LETTER Y WITH DIAERESIS.
VHK_KEY_yen
#define VHK_KEY_yen 0x00a5
U+00A5 YEN SIGN.
VHK_KEY_Z
#define VHK_KEY_Z 0x005a
VHK_KEY_z
#define VHK_KEY_z 0x007a
VHK_MOD_ALT
#define VHK_MOD_ALT 0x0001
VHK_MOD_COMMAND
#define VHK_MOD_COMMAND 0x0002
VHK_MOD_CONTROL
#define VHK_MOD_CONTROL 0x0004
VHK_MOD_HYPER
#define VHK_MOD_HYPER 0x0008
VHK_MOD_META
#define VHK_MOD_META 0x0010
VHK_MOD_NONE
#define VHK_MOD_NONE 0x0000
Key modifier masks.
VHK_MOD_OPTION
#define VHK_MOD_OPTION 0x0020
VHK_MOD_SHIFT
#define VHK_MOD_SHIFT 0x0040
VHK_MOD_SUPER
#define VHK_MOD_SUPER 0x0080
Function Documentation
vhk_hotkey_label()
char * vhk_hotkey_label (uint32_t vice_keysym, uint32_t vice_modmask)
Get accelerator label for a hotkey.
Create a string to present a hotkey's key name and modifier mask to the user. This function is very much like gtk_accelerator_get_label() and meant for UI toolkits that do not provide such a function, such as SDL.
Parameters
[in] vice_keysym VICE keysym
[in] vice_modmask VICE modifier mask
Returns
heap-allocated string, free with lib_free()
Note
returns NULL for invalid vice_keysym values
Referenced by ui_action_map_get_hotkey_label().
vhk_keysym_from_name()
uint32_t vhk_keysym_from_name (const char * name)
Get keysym value from name.
Parameters
[in] name keysym name
Returns
keysym value as defined in vhkkeysyms.h, or 0 when not found
Referenced by vhk_parser_get_keysym_and_modmask().
vhk_keysym_name()
const char * vhk_keysym_name (uint32_t keysym)
Get keysym name from value.
Parameters
keysym keysym value
Returns
name or NULL when keysym isn't valid
Referenced by ui_hotkeys_save_as(), vhk_hotkey_label(), vhk_parser_do_undef(), and vhk_parser_handle_mapping().
vhk_modifier_from_name()
uint32_t vhk_modifier_from_name (const char * name, const char ** endptr)
Parse string for modifier name and return modifier bit.
Parse name for a valid modifier name and return its value, storing the position in name after either end-of-string or '>' in endptr. The name is allowed to start with a '>' opening tag.
Parameters
[in] name string to parse
[out] endptr position in name of the closing '>' tag or the nul character (optional)
Returns
VICE modifier value
Referenced by parser_get_modifier().
vhk_modifier_name()
const char * vhk_modifier_name (uint32_t vice_modifier)
Get modifier name.
Get a string representing a keyboard modifier. The returned string is the unadorned name, so no '<' or '>' around the name like in the hotkeys files.
Parameters
[in] vice_modifier VICE modifier
Returns
modifier name
Referenced by vhk_hotkey_label().
vhk_modmask_name()
char * vhk_modmask_name (uint32_t vice_modmask)
Get string of modifier names for a modifier mask.
Generate string with modifier names enclosed by angled brackets from modifier mask vice_modmask.
Parameters
[in] vice_modmask VICE modifier mask
Returns
heap-allocated string, free with lib_free()
Note
Always returns an allocated string, being the empty string for a modifier mask of 0 (VHK_MOD_NONE).
Referenced by ui_hotkeys_save_as().