x128: arch/gtk3/widgets/crtcontrolwidget.c File Reference
crtcontrolwidget.c File Reference
GTK3 CRT settings widget.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdbool.h>
#include <string.h>
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "crtcontrolwidget.h"
Data Structures
struct crt_control_info_s
CRT resource info.
struct crt_control_data_s
Object holding internal state of a CRT control widget.
Macros
#define SCALE_CSS_STATUSBAR
CSS for the scale widgets in the status bar CRT widget.
#define SCALE_CSS_DIALOG
CSS used to tweak looks of CRT sliders in the settings dialog.
#define CHECKBUTTON_CSS_STATUSBAR
CSS for the "U-only delayline" check button on the status bar.
#define BUTTON_CSS_STATUSBAR
CSS for the reset button when used on the status bar.
#define LABEL_CSS
CSS for the labels.
#define RESOURCE_COUNT 9
Size of array required for all resources.
Typedefs
typedef struct crt_control_info_s crt_control_info_t
CRT resource info.
typedef struct crt_control_data_s crt_control_data_t
Object holding internal state of a CRT control widget.
Functions
static bool is_pal (const char *chip)
Determine if the PAL-specific controls must be enabled.
static void reset_sliders (crt_control_data_t *data)
Reset all sliders to their factory value.
static void reset_sliders_neutral (crt_control_data_t *data)
Reset all sliders to their neutral value.
static void on_reset_clicked (GtkWidget *button, gpointer data)
Reset all sliders to their factory value.
static gboolean on_reset_right_clicked (GtkWidget *self, GdkEventButton *event, gpointer data)
static void on_widget_destroy (GtkWidget *widget, gpointer data)
Clean up memory used by the internal state of widget.
static gboolean create_css_providers (void)
Create reusable CSS providers for the widgets.
static GtkWidget * create_label (const char *text, gboolean minimal)
Create right-aligned label with a smaller font.
static GtkWidget * create_slider (const char *resource, const char *chip, int resource_low, int resource_high, double display_low, double display_high, double display_step, const char *display_format, gboolean minimal)
Create a customized GtkScale for resource.
static GtkWidget * create_delayline_widget (const char *chip)
Create "U-only delayline" check button.
static int add_sliders (GtkGrid *grid, crt_control_data_t *data, gboolean minimal)
Add GtkScale sliders to grid.
static crt_control_data_t * create_control_data (const char *chip)
Create heap-allocated CRT controls state object.
static GtkWidget * create_header (const char *chip, gboolean minimal, crt_control_data_t *data)
Create header with label and reset button.
GtkWidget * crt_control_widget_create (GtkWidget *parent, const char *chip, gboolean minimal)
Create CRT control widget for chip.
void crt_control_widget_shutdown (void)
Free memory used by CSS providers for the sliders.
Variables
static const crt_control_info_t control_info [9]
List of CRT emulation resources.
static GtkCssProvider * label_css = NULL
CSS provider for labels.
static GtkCssProvider * button_css = NULL
CSS provider for the reset button on the status bar.
static GtkCssProvider * checkbutton_css = NULL
CSS provider for the U-delayline check button on the status bar.
static GtkCssProvider * scale_css_statusbar = NULL
CSS provider for scales in the CRT widget for the statusbar.
static GtkCssProvider * scale_css_dialog = NULL
CSS provider for scales in the settings dialog.
static int standard = 0
MachineVideoStandard resource value on construction.
Detailed Description
GTK3 CRT settings widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Provides a list of GtkScale widgets to alter CRT settings.
Supported settings per chip/video mode:
Setting VICIIP VICIIN VDC VICP VICN TEDP TEDN CRTC
Brightness yes yes yes yes yes yes yes yes
Contrast yes yes yes yes yes yes yes yes
Saturation yes yes yes yes yes yes yes yes
Tint yes yes yes yes yes yes yes yes
Gamma yes yes yes yes yes yes yes yes
Blur yes yes yes yes yes yes yes yes
Scanline shade yes yes yes yes yes yes yes yes
Odd lines phase yes no no yes no yes no no
Odd lines offset yes no no yes no yes no no
U-only delayline yes no no yes no yes no no
!
Todo:
Fix display of sliders when switching between PAL and NTSC
Macro Definition Documentation
BUTTON_CSS_STATUSBAR
#define BUTTON_CSS_STATUSBAR
Value:
    "button {\n" \
    "  min-width: 12px;\n" \
    "  min-height: 12px;\n" \
    "  padding-top: 2px;\n " \
    "  padding-left: 2px;\n " \
    "  padding-bottom: 2px;\n " \
    "  padding-right: 2px;\n " \
    "}"
CSS for the reset button when used on the status bar.
CHECKBUTTON_CSS_STATUSBAR
#define CHECKBUTTON_CSS_STATUSBAR
Value:
    "checkbutton {\n" \
    "  font-size: 80%;\n" \
    "}\n" \
    "checkbutton check {\n" \
    "  min-width: 12px;\n" \
    "  min-height: 12px;\n" \
    "}"
CSS for the "U-only delayline" check button on the status bar.
LABEL_CSS
#define LABEL_CSS
Value:
    "label {\n" \
    "  font-size: 80%;\n" \
    "  margin-top: -2px;\n" \
    "  margin-bottom: -2px;\n" \
    "}"
CSS for the labels.
Make font smaller and reduce the vertical size the labels use
Here Be Dragons!
RESOURCE_COUNT
#define RESOURCE_COUNT 9
Size of array required for all resources.
SCALE_CSS_DIALOG
#define SCALE_CSS_DIALOG
Value:
    "scale value {\n" \
    "  font-family: monospace;\n" \
    "}"
CSS used to tweak looks of CRT sliders in the settings dialog.
We use monospace for the value labels to keep them aligned on the decimal point and to keep the width of the sliders consistent.
SCALE_CSS_STATUSBAR
#define SCALE_CSS_STATUSBAR
Value:
    "scale slider {\n" \
    "  min-width: 10px;\n" \
    "  min-height: 10px;\n" \
    "  margin: -3px;\n" \
    "}\n\n" \
    "scale value {\n" \
    "  font-family: monospace;\n" \
    "  font-size: 80%;\n" \
    "}\n" \
    "scale {\n" \
    "  margin-top: -8px;\n" \
    "  margin-bottom: -8px;\n" \
    "}"
CSS for the scale widgets in the status bar CRT widget.
This makes the sliders take up less vertical space. The margin can be set to a negative value (in px) to allow the slider to be larger than the scale itself.
Probably will require some testing/tweaking to get this to look acceptable with various themes (and OSes).
Typedef Documentation
crt_control_data_t
typedef struct crt_control_data_s crt_control_data_t
Object holding internal state of a CRT control widget.
Since we can have two video chips (C128's VICII+VDC), we cannot use static references to widgets and need to allocate memory for the references and clean that memory up once the widget is destroyed.
crt_control_info_t
typedef struct crt_control_info_s crt_control_info_t
CRT resource info.
Function Documentation
add_sliders()
static int add_sliders (GtkGrid * grid, crt_control_data_t * data, gboolean minimal) static
Add GtkScale sliders to grid.
Parameters
[in,out] grid grid to add widgets to
[in,out] data internal data of the main widget
[in] minimal minimize size of the slider, no spinboxes
Returns
row number of last widget added
Referenced by crt_control_widget_create().
create_control_data()
static crt_control_data_t * create_control_data (const char * chip) static
Create heap-allocated CRT controls state object.
We need this since we share this code with the CRT controls available via the statusbar.
Parameters
[in] chip video chip name
Returns
heap-allocated CRT controls state object
Referenced by crt_control_widget_create().
create_css_providers()
static gboolean create_css_providers (void) static
Create reusable CSS providers for the widgets.
Create CSS providers once when needed and only unref on emulator shutdown. Keeping them around after a widget using them has been destroyed avoids having to recreate them every time a dialog/widget is recreated that uses said widget.
Returns
TRUE when all CSS was successfully parsed
Referenced by crt_control_widget_create().
create_delayline_widget()
static GtkWidget * create_delayline_widget (const char * chip) static
Create "U-only delayline" check button.
Parameters
[in] chip video chip name
Returns
GtkCheckButton
Referenced by crt_control_widget_create().
create_header()
static GtkWidget * create_header (const char * chip, gboolean minimal, crt_control_data_t * data) static
Create header with label and reset button.
Create grid with label mentioning chip and reset button, adjust size depending on whether minimal is TRUE.
Parameters
[in] chip video chip name
[in] minimal reduce size of widgets for use on the status bar
[in] data CRT controls runtime data object
Returns
GtkGrid
Referenced by crt_control_widget_create().
create_label()
static GtkWidget * create_label (const char * text, gboolean minimal) static
Create right-aligned label with a smaller font.
Parameters
[in] text label text
[in] minimal reduce label to minimum size
Returns
GtkLabel
Referenced by add_sliders().
create_slider()
static GtkWidget * create_slider (const char * resource, const char * chip, int resource_low, int resource_high, double display_low, double display_high, double display_step, const char * display_format, gboolean minimal) static
Create a customized GtkScale for resource.
Parameters
[in] resource resource name without the chip prefix
[in] chip video chip name
[in] resource_low resource value lower bound
[in] resource_high resource value upper bound
[in] display_low display value lower bound
[in] display_high display value upper bound
[in] display_step display value stepping
[in] display_format format string for displaying value
[in] minimal reduced size (for the statusbar widget)
Returns
GtkScale
Referenced by add_sliders().
crt_control_widget_create()
GtkWidget * crt_control_widget_create (GtkWidget * parent, const char * chip, gboolean minimal)
Create CRT control widget for chip.
Parameters
[in] parent parent widget (unused)
[in] chip video chip name (all caps)
[in] minimal reduce slider sizes for use in the status bar
Todo:
Add a way to force update of all sliders and their sensitivity when MachineVideoStandard is changed (ie CRT sliders in the statusbar are shown and the user switches from PAL to NTSC)
Returns
GtkGrid
Referenced by settings_crt_widget_create(), and ui_statusbar_recreate_crt_controls().
crt_control_widget_shutdown()
void crt_control_widget_shutdown (void)
Free memory used by CSS providers for the sliders.
Call this function on UI shutdown.
Referenced by ui_exit().
is_pal()
static bool is_pal (const char * chip) static
Determine if the PAL-specific controls must be enabled.
Check video standard and chip for PAL support.
Parameters
[in] chip video chip name
Returns
true if PAL controls must be enabled
Referenced by add_sliders(), and crt_control_widget_create().
on_reset_clicked()
static void on_reset_clicked (GtkWidget * button, gpointer data) static
Reset all sliders to their factory value.
Parameters
[in] button reset button
[in] data crt control data
Referenced by create_header().
on_reset_right_clicked()
static gboolean on_reset_right_clicked (GtkWidget * self, GdkEventButton * event, gpointer data) static
Referenced by create_header().
on_widget_destroy()
static void on_widget_destroy (GtkWidget * widget, gpointer data) static
Clean up memory used by the internal state of widget.
Parameters
[in] widget widget
[in] data crt control dat
Referenced by crt_control_widget_create().
reset_sliders()
static void reset_sliders (crt_control_data_t * data) static
Reset all sliders to their factory value.
Parameters
[in] data crt control data
Referenced by on_reset_clicked().
reset_sliders_neutral()
static void reset_sliders_neutral (crt_control_data_t * data) static
Reset all sliders to their neutral value.
Parameters
[in] data crt control data
Referenced by on_reset_right_clicked().
Variable Documentation
button_css
GtkCssProvider* button_css = NULL static
CSS provider for the reset button on the status bar.
Referenced by create_css_providers(), create_header(), and crt_control_widget_shutdown().
checkbutton_css
GtkCssProvider* checkbutton_css = NULL static
CSS provider for the U-delayline check button on the status bar.
Referenced by create_css_providers(), crt_control_widget_create(), and crt_control_widget_shutdown().
control_info
const crt_control_info_t control_info[9] static
Initial value:
= {
    { "Brightness",     "ColorBrightness",  true,  0, 2000, 1000, 100,   0.0, 200.0,  0.1, "%5.1f%%",       ( (1U<<0) | (1U<<8) | (1U<<7) | (1U<<10) | (1U<<1) | (1U<<2) | (1U<<6) | (1U<<3) | (1U<<4) | (1U<<5) | (1U<<9) )  },
    { "Contrast",       "ColorContrast",    true,  0, 2000, 1000, 100,   0.0, 200.0,  0.1, "%5.1f%%",       ( (1U<<0) | (1U<<8) | (1U<<7) | (1U<<10) | (1U<<1) | (1U<<2) | (1U<<6) | (1U<<3) | (1U<<4) | (1U<<5) | (1U<<9) )  },
    { "Saturation",     "ColorSaturation",  true,  0, 2000, 1000, 100,   0.0, 200.0,  0.1, "%5.1f%%",       ( (1U<<0) | (1U<<8) | (1U<<7) | (1U<<10) | (1U<<1) | (1U<<2) | (1U<<6) | (1U<<3) | (1U<<4) | (1U<<5) | (1U<<9) )  },
    { "Tint",           "ColorTint",        true,  0, 2000, 1000, 100, -25.0,  25.0,  0.1, "%+5.1f%%",      ( (1U<<0) | (1U<<8) | (1U<<7) | (1U<<10) | (1U<<1) | (1U<<2) | (1U<<6) | (1U<<3) | (1U<<4) | (1U<<5) | (1U<<9) )  },
    { "Gamma",          "ColorGamma",       true,  0, 4000, 1000, 200,   0.0,   4.0, 0.01, "%6.2f",         ( (1U<<0) | (1U<<8) | (1U<<7) | (1U<<10) | (1U<<1) | (1U<<2) | (1U<<6) | (1U<<3) | (1U<<4) | (1U<<5) | (1U<<9) )  },
    { "Blur",           "PALBlur",          true,  0, 1000,    0,  50,   0.0, 100.0,  0.1, "%5.1f%%",       ( (1U<<0) | (1U<<8) | (1U<<7) | (1U<<10) | (1U<<1) | (1U<<2) | (1U<<6) | (1U<<3) | (1U<<4) | (1U<<5) | (1U<<9) )  },
    { "Scanline shade", "PALScanLineShade", true,  0, 1000, 1000,  50,   0.0, 100.0,  0.1, "%5.1f%%",       ( (1U<<0) | (1U<<8) | (1U<<7) | (1U<<10) | (1U<<1) | (1U<<2) | (1U<<6) | (1U<<3) | (1U<<4) | (1U<<5) | (1U<<9) )  },
    { "Oddline phase",  "PALOddLinePhase",  false, 0, 2000, 1000, 100, -25.0,  25.0,  0.1, "%+5.1f\u00b0",  ( (1U<<0) | (1U<<8) | (1U<<7) | (1U<<10) | (1U<<1) | (1U<<2) | (1U<<6) | (1U<<3) | (1U<<4) | (1U<<5) | (1U<<9) ) ^ (1U<<5) ^ (1U<<3)  },
    { "Oddline offset", "PALOddLineOffset", false, 0, 2000, 1000, 100, -50.0,  50.0,  0.1, "%+4.1f%%",      ( (1U<<0) | (1U<<8) | (1U<<7) | (1U<<10) | (1U<<1) | (1U<<2) | (1U<<6) | (1U<<3) | (1U<<4) | (1U<<5) | (1U<<9) ) ^ (1U<<5) ^ (1U<<3)  }
}
List of CRT emulation resources.
Referenced by add_sliders(), crt_control_widget_create(), and reset_sliders_neutral().
label_css
GtkCssProvider* label_css = NULL static
CSS provider for labels.
Referenced by create_css_providers(), create_label(), and crt_control_widget_shutdown().
scale_css_dialog
GtkCssProvider* scale_css_dialog = NULL static
CSS provider for scales in the settings dialog.
Referenced by create_css_providers(), create_slider(), and crt_control_widget_shutdown().
scale_css_statusbar
GtkCssProvider* scale_css_statusbar = NULL static
CSS provider for scales in the CRT widget for the statusbar.
Referenced by create_css_providers(), create_slider(), and crt_control_widget_shutdown().
standard
int standard = 0 static
MachineVideoStandard resource value on construction.
Referenced by crt_control_widget_create(), and is_pal().