vsid: arch/gtk3/widgets/cwdwidget.c File Reference
cwdwidget.c File Reference
Widget to set the current working directory.
#include "vice.h"
#include <gtk/gtk.h>
#include <glib/gstdio.h>
#include "log.h"
#include "ui.h"
#include "vice_gtk3.h"
#include "cwdwidget.h"
Macros
#define INVALID_PATH_CSS "entry { text-decoration: crimson wavy underline; }"
CSS used to mark invalid paths.
Functions
static void create_css_provider (void)
Create CSS provider to mark invalid paths.
static void add_css_provider (GtkEditable *entry)
Add CSS provider marking invalid paths.
static void remove_css_provider (GtkEditable *entry)
Remove CSS provider marking invalid paths.
static void on_changed (GtkEditable *self, gpointer data)
Handler for the "changed" event of the text entry box.
static void on_destroy (GtkWidget *self, gpointer data)
Handler for the 'destroy' event of the entry.
static void on_response (GtkDialog *self, gint response_id, gpointer data)
Handler for the 'response' event of the file chooser dialog.
static void on_icon_press (GtkEntry *self, GtkEntryIconPosition icon_pos, GdkEvent *event, gpointer data)
Handler for the 'icon-press' event of the entry.
GtkWidget * cwd_widget_create (void)
Create widget to change the current working directory.
Variables
static GtkCssProvider * provider = NULL
CSS provider reference.
Detailed Description
Widget to set the current working directory.
GtkEntry with clickable icon to pop up a directory selection dialog to set the current working directory. Failures of g_chdir() will be marked by squiggly crimson lines under the text.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
INVALID_PATH_CSS
#define INVALID_PATH_CSS "entry { text-decoration: crimson wavy underline; }"
CSS used to mark invalid paths.
Function Documentation
add_css_provider()
static void add_css_provider (GtkEditable * entry) static
Add CSS provider marking invalid paths.
Parameters
[in] entry entry widget
Referenced by on_changed().
create_css_provider()
static void create_css_provider (void) static
Create CSS provider to mark invalid paths.
Referenced by cwd_widget_create().
cwd_widget_create()
GtkWidget * cwd_widget_create (void)
Create widget to change the current working directory.
Create a GtkEntry with a clickable icon to pop up a file chooser to select an existing directory to use for the current working directory.
Returns
GtkEntry
Referenced by settings_environment_widget_create().
on_changed()
static void on_changed (GtkEditable * self, gpointer data) static
Handler for the "changed" event of the text entry box.
Try to set the current working directory with g_chdir(), on failure CSS is added to the entry marking the text invalid.
Parameters
[in] self entry widget
[in] data event data (NULL)
Referenced by cwd_widget_create().
on_destroy()
static void on_destroy (GtkWidget * self, gpointer data) static
Handler for the 'destroy' event of the entry.
Unrefs the CSS provider.
Parameters
[in] self entry widget (ignored)
[in] data event data (NULL)
Referenced by cwd_widget_create().
on_icon_press()
static void on_icon_press (GtkEntry * self, GtkEntryIconPosition icon_pos, GdkEvent * event, gpointer data) static
Handler for the 'icon-press' event of the entry.
Show file chooser dialog to select an existing directory.
Parameters
[in] self entry widget
[in] icon_pos icon position in self (ignored)
[in] event event object (ignored)
[in] data event data (NULL)
Referenced by cwd_widget_create().
on_response()
static void on_response (GtkDialog * self, gint response_id, gpointer data) static
Handler for the 'response' event of the file chooser dialog.
In case of GTK_RESPONSE_ACCEPT the path of the dialog will be used to set the current working directory.
Parameters
[in] self file chooser dialog
[in] response_id response ID
[in] data event data (entry widget)
Referenced by on_icon_press().
remove_css_provider()
static void remove_css_provider (GtkEditable * entry) static
Remove CSS provider marking invalid paths.
Parameters
[in] entry entry widget
Referenced by on_changed().
Variable Documentation
provider
GtkCssProvider* provider = NULL static
CSS provider reference.
Use to add and remove the style for invalid paths.
Referenced by add_css_provider(), create_css_provider(), on_destroy(), on_entry_changed(), remove_css_provider(), vice_gtk3_css_add(), vice_gtk3_css_provider_add(), vice_gtk3_css_provider_new(), vice_gtk3_css_provider_remove(), and vice_gtk3_resource_numeric_string_new().