vsid: c64/vsid-stubs.c File Reference
vsid-stubs.c File Reference
#include "vice.h"
#include <stdbool.h>
#include "c64.h"
#include "c64-midi.h"
#include "c64cart.h"
#include "c64cartmem.h"
#include "c64fastiec.h"
#include "c64iec.h"
#include "c64mem.h"
#include "c64-cmdline-options.h"
#include "c64_256k.h"
#include "cartridge.h"
#include "cbmdos.h"
#include "cia.h"
#include "clockport.h"
#include "diskcontents.h"
#include "diskcontents-block.h"
#include "diskimage.h"
#include "drive.h"
#include "drive-check.h"
#include "driveimage.h"
#include "driver-select.h"
#include "drivetypes.h"
#include "ds1602.h"
#include "fileio.h"
#include "fsdevice.h"
#include "fsdevice-filename.h"
#include "gfxoutput.h"
#include "iecbus.h"
#include "iecdrive.h"
#include "imagecontents.h"
#include "midi.h"
#include "machine.h"
#include "machine-bus.h"
#include "machine-drive.h"
#include "machine-printer.h"
#include "pet/petpia.h"
#include "printer.h"
#include "sampler.h"
#include "snapshot.h"
#include "tap.h"
#include "tape.h"
#include "tapecart.h"
#include "tapeport.h"
#include "tapecontents.h"
#include "tape-snapshot.h"
#include "userport.h"
#include "userport_io_sim.h"
#include "vdrive.h"
#include "vdrive-bam.h"
#include "vdrive-command.h"
#include "vdrive-iec.h"
#include "vdrive-internal.h"
#include "vicii-phi1.h"
#include "ds1202_1302.h"
Functions
void c64_256k_cia_set_vbank (int ciabank)
needed from c64gluelogic.c
int machine_drive_image_attach (struct disk_image_s *image, unsigned int unit, unsigned int drive)
int machine_drive_image_detach (struct disk_image_s *image, unsigned int unit, unsigned int drive)
void machine_drive_stub (void)
drive_type_info_t * machine_drive_get_type_info_list (void)
Dummy function.
int drive_check_expansion2000 (int type)
int drive_check_expansion4000 (int type)
int drive_check_expansion6000 (int type)
int drive_check_expansion8000 (int type)
int drive_check_expansionA000 (int type)
int drive_check_profdos (int type)
int drive_check_stardos (int type)
int drive_check_supercard (int type)
int drive_check_rtc (int type)
Check if drive_type supports a real-time clock.
int drive_check_iec (int type)
int drive_check_image_format (unsigned int format, unsigned int dnr)
int cartridge_attach_image (int type, const char *filename)
attach (and enable) a cartridge by type and filename (takes crt and bin files)
void cartridge_detach_image (int type)
detaches/disables the cartridge with the associated id.
uint8_t * ultimax_romh_phi1_ptr (uint16_t addr)
uint8_t * ultimax_romh_phi2_ptr (uint16_t addr)
int cartridge_save_image (int type, const char *filename)
save the primary (rom/ram)image of the give cart type to a file
int cartridge_save_secondary_image (int type, const char *filename)
save the secondary image of the give cart type to a file
int cartridge_flush_image (int type)
int cartridge_flush_secondary_image (int type)
int cartridge_can_save_image (int crtid)
returns 1 when cartridge (ROM) image can be saved
int cartridge_can_flush_image (int crtid)
returns 1 when cartridge (ROM) image can be flushed
int cartridge_can_save_secondary_image (int crtid)
int cartridge_can_flush_secondary_image (int crtid)
int cartridge_enable (int crtid)
int cartridge_disable (int crtid)
disable cartridge by type
int cartridge_type_enabled (int crtid)
void cartridge_set_default (void)
set current "Main Slot" cart as default
void cartridge_unset_default (void)
called from resources_set_defaults()
cartridge_info_t * cartridge_get_info_list (void)
int cartridge_get_id (int slot)
char * cartridge_get_filename_by_slot (int slot)
void cartridge_trigger_freeze (void)
freeze button pressed in UI
int gfxoutput_early_init (int help)
void gfxoutput_shutdown (void)
int gfxoutput_num_drivers (void)
gfxoutputdrv_t * gfxoutput_get_driver (const char *drvname)
gfxoutputdrv_t * gfxoutput_drivers_iter_next (void)
gfxoutputdrv_t * gfxoutput_drivers_iter_init (void)
int gfxoutput_resources_init (void)
Functions called by external emulator code.
int gfxoutput_cmdline_options_init (void)
void printer_shutdown (void)
int printer_serial_late_init (void)
void printer_formfeed (unsigned int prnr)
Send formfeed to printer.
rtc_ds1216e_t * ds1216e_init (char *device)
void ds1216e_destroy (rtc_ds1216e_t *context, int save)
uint8_t ds1216e_read (rtc_ds1216e_t *context, uint16_t address, uint8_t origbyte)
rtc_ds1202_1302_t * ds1202_1302_init (char *device, int rtc_type)
void ds1202_1302_set_lines (rtc_ds1202_1302_t *context, unsigned int ce_line, unsigned int sclk_line, unsigned int input_bit)
uint8_t ds1202_1302_read_data_line (rtc_ds1202_1302_t *context)
void ds1202_1302_destroy (rtc_ds1202_1302_t *context, int save)
int ds1202_1302_write_snapshot (rtc_ds1202_1302_t *context, snapshot_t *s)
int ds1202_1302_read_snapshot (rtc_ds1202_1302_t *context, snapshot_t *s)
int ds1602_write_snapshot (rtc_ds1602_t *context, snapshot_t *s)
void ds1602_destroy (rtc_ds1602_t *context, int save)
rtc_ds1602_t * ds1602_init (char *device, time_t offset0)
uint8_t ds1602_read_data_line (rtc_ds1602_t *context)
void ds1602_set_data_line (rtc_ds1602_t *context, uint8_t data)
void ds1602_set_clk_line (rtc_ds1602_t *context, uint8_t data)
void ds1602_set_reset_line (rtc_ds1602_t *context, uint8_t data)
int ds1602_read_snapshot (rtc_ds1602_t *context, snapshot_t *s)
int tape_image_attach (unsigned int unit, const char *name)
void tape_shutdown (void)
int tape_tap_attached (int port)
int tape_seek_start (tape_image_t *tape_image)
int tape_seek_to_file (tape_image_t *tape_image, unsigned int file_number)
void tape_image_event_playback (unsigned int unit, const char *filename)
int tape_image_detach (unsigned int unit)
External tape image interface.
void tape_image_detach_all (void)
int tap_seek_start (tap_t *tap)
int tape_image_create (const char *name, unsigned int type)
int tape_snapshot_write_module (int port, snapshot_t *s, int save_image)
int tape_snapshot_read_module (int port, snapshot_t *s)
int tape_read (tape_image_t *tape_image, uint8_t *buf, size_t size)
used by virtual devices
tape_file_record_t * tape_get_current_file_record (tape_image_t *tape_image)
int tape_image_open (tape_image_t *tape_image)
int tape_image_close (tape_image_t *tape_image)
int tape_internal_close_tape_image (tape_image_t *tape_image)
tape_image_t * tape_internal_open_tape_image (const char *name, unsigned int read_only)
int tape_seek_to_next_file (tape_image_t *tape_image, unsigned int allow_rewind)
unsigned long tape_get_offset (tape_image_t *tape_image)
void tape_get_header (tape_image_t *tape_image, uint8_t *name)
const char * tape_get_file_name (int port)
int tapeport_valid_port (int port)
int tapecart_is_valid (const char *filename)
Check magic of the tapecart filename.
int tapecart_attach_tcrt (const char *filename, void *unused)
int tapecart_flush_tcrt (void)
Flush current tapecart data to image file.
image_contents_screencode_t * image_contents_to_screencode (image_contents_t *contents)
char * image_contents_filename_by_number (image_contents_t *contents, unsigned int file_index)
Get image contents file name by index.
image_contents_t * diskcontents_filesystem_read (const char *file_name)
void image_contents_destroy (image_contents_t *contents)
Free memory used by contents and its members.
char * image_contents_file_to_string (image_contents_file_list_t *p, char convert_to_ascii)
Generate a '<blocks> "<filename>" *prg<' line from p.
char * image_contents_to_string (image_contents_t *contents, char convert_to_ascii)
Generate the first line of a directory listing (0 name id)
image_contents_t * tapecontents_read (const char *file_name)
image_contents_t * diskcontents_block_read (struct vdrive_s *vdrive, int part)
void fileio_close (fileio_info_t *info)
fileio_info_t * fileio_open (const char *file_name, const char *path, unsigned int format, unsigned int command, unsigned int type, int *reclenp)
unsigned int fileio_read (fileio_info_t *info, uint8_t *buf, unsigned int len)
unsigned int fileio_get_bytes_left (fileio_info_t *info)
unsigned int fileio_ferror (fileio_info_t *info)
unsigned int fileio_write (fileio_info_t *info, uint8_t *buf, unsigned int len)
unsigned int fileio_rename (const char *src_name, const char *dest_name, const char *path, unsigned int format)
unsigned int fileio_scratch (const char *file_name, const char *path, unsigned int format)
void fsdevice_init (void)
void fsdevice_shutdown (void)
int fsdevice_attach (unsigned int device, unsigned int drive, const char *name)
void fsdevice_set_directory (char *filename, unsigned int unit)
int fsdevice_limit_namelength (vdrive_t *vdrive, uint8_t *name)
void disk_image_init (void)
Initialization.
const char * disk_image_fsimage_name_get (const disk_image_t *image)
Get disk image name.
void disk_image_media_destroy (disk_image_t *image)
int disk_image_close (disk_image_t *image)
void disk_image_destroy (disk_image_t *image)
disk_image_t * disk_image_create (void)
int disk_image_open (disk_image_t *image)
void disk_image_rawimage_driver_name_set (disk_image_t *image)
void disk_image_fsimage_name_set (disk_image_t *image, const char *name)
Set disk image name.
void disk_image_media_create (disk_image_t *image)
int disk_image_fsimage_create (const char *name, unsigned int type)
int disk_image_fsimage_create_dxm (const char *name, const char *dname, unsigned int type)
int disk_image_fsimage_create_dhd (const char *name, const char *dname, unsigned int type)
int disk_image_write_sector (disk_image_t *image, const uint8_t *buf, const disk_addr_t *dadr)
int disk_image_read_sector (const disk_image_t *image, uint8_t *buf, const disk_addr_t *dadr)
const char * disk_image_name_get (const disk_image_t *image)
unsigned int disk_image_sector_per_track (unsigned int format, unsigned int track)
Get number of sectors for track in format.
int disk_image_write_p64_image (const disk_image_t *image)
void disk_image_attach_log (const disk_image_t *image, signed int lognum, unsigned int unit, unsigned int drive)
Log attachment of disk image.
void disk_image_detach_log (const disk_image_t *image, signed int lognum, unsigned int unit, unsigned int drive)
Log detachment of disk image.
int disk_image_check_sector (const disk_image_t *image, unsigned int track, unsigned int sector)
Check out of bound.
void disk_image_name_set (disk_image_t *image, const char *name)
void * disk_image_fsimage_fd_get (const disk_image_t *image)
Get file descriptor for image.
void P64ImageDestroy (PP64Image Instance)
int machine_bus_lib_directory (unsigned int unit, const char *pattern, uint8_t **buf)
int machine_bus_lib_read_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t *buf)
int machine_bus_lib_write_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t *buf)
unsigned int machine_bus_device_type_get (unsigned int unit)
void machine_bus_status_truedrive_set (unsigned int unit, unsigned int enable)
void machine_bus_status_drivetype_set (unsigned int unit, unsigned int enable)
void machine_bus_status_virtualdevices_set (unsigned int unit, unsigned int enable)
void machine_bus_eof_callback_set (void(*func)(void))
void machine_bus_attention_callback_set (void(*func)(void))
void machine_bus_init_machine (void)
void iecbus_status_set (unsigned int type, unsigned int unit, unsigned int enable)
int iecbus_device_write (unsigned int unit, uint8_t data)
uint8_t iecbus_device_read (void)
void drive_setup_context (void)
void drive_cpu_early_init_all (void)
void drive_cpu_trigger_reset (unsigned int dnr)
reset one drive only
void drive_shutdown (void)
int drive_image_detach (disk_image_t *image, unsigned int unit, unsigned int drive)
Detach a disk image from the true drive emulation.
int drive_image_attach (disk_image_t *image, unsigned int unit, unsigned int drive)
Attach a disk image to the true drive emulation.
void drive_set_last_read (unsigned int track, unsigned int sector, uint8_t *buffer, struct diskunit_context_s *drv)
void drive_set_disk_memory (uint8_t *id, unsigned int track, unsigned int sector, struct diskunit_context_s *drv)
void drive_cpu_execute_one (diskunit_context_t *drv, CLOCK clk_value)
void drive_cpu_execute_all (CLOCK clk_value)
int drive_num_leds (unsigned int dnr)
int drive_check_type (unsigned int drive_type, unsigned int dnr)
int drive_check_extend_policy (int drive_type)
int drive_check_idle_method (int drive_type)
int drive_check_parallel_cable (int drive_type)
int drive_get_disk_drive_type (int dnr)
int drive_is_dualdrive_by_devnr (int devnr)
int drive_get_type_by_devnr (int devnr)
void vdrive_init (void)
int vdrive_device_setup (vdrive_t *vdrive, unsigned int unit)
void vdrive_device_shutdown (vdrive_t *vdrive)
int vdrive_iec_attach (unsigned int unit, const char *name)
int vdrive_bam_get_disk_id (unsigned int unit, unsigned int drive, uint8_t *id)
get disk id
int vdrive_bam_set_disk_id (unsigned int unit, unsigned int drive, uint8_t *id)
set disk id
void vdrive_detach_image (disk_image_t *image, unsigned int unit, unsigned int drive, vdrive_t *vdrive)
int vdrive_attach_image (disk_image_t *image, unsigned int unit, unsigned int drive, vdrive_t *vdrive)
void vdrive_get_last_read (unsigned int *track, unsigned int *sector, uint8_t **buffer)
int vdrive_internal_create_format_disk_image (const char *filename, const char *diskname, unsigned int type)
int vdrive_iec_close (vdrive_t *vdrive, unsigned int secondary)
int vdrive_iec_write (vdrive_t *vdrive, uint8_t data, unsigned int secondary)
int vdrive_iec_open (vdrive_t *vdrive, const uint8_t *name, unsigned int length, unsigned int secondary, cbmdos_cmd_parse_t *cmd_parse_ext)
Generic IEC interface.
int vdrive_iec_read (vdrive_t *vdrive, uint8_t *data, unsigned int secondary)
int vdrive_command_execute (vdrive_t *vdrive, const uint8_t *buf, unsigned int length)
called by vdrive-iec.c; return code not used
int vdrive_ext_write_sector (vdrive_t *vdrive, int drive, const uint8_t *buf, unsigned int track, unsigned int sector)
int vdrive_ext_read_sector (vdrive_t *vdrive, int drive, uint8_t *buf, unsigned int track, unsigned int sector)
For external access to individual drives.
struct disk_image_s * vdrive_get_image (vdrive_t *vdrive, unsigned int drive)
int tapeport_device_register (int id, tapeport_device_t *device)
register a device to be used in the tapeport system
void tapeport_trigger_flux_change (unsigned int on, int port)
void tapeport_set_tape_sense (int sense, int port)
int tape_seek_to_offset (tape_image_t *tape_image, unsigned long offset)
int tap_seek_to_offset (tap_t *tap, unsigned long offset)
int iec_available_busses (void)
This function is called from ui_update_menus()
int machine_get_num_keyboard_types (void)
return number of available keyboard types for this machine
kbdtype_info_t * machine_get_keyboard_info_list (void)
void drive_cpu_trigger_reset_button (unsigned int dnr, unsigned int button)
int drive_has_buttons (unsigned int dnr)
int drive_image_type_to_drive_type (unsigned int type)
unsigned int drive_check_dual (unsigned int type)
unsigned int drive_get_num_heads (unsigned int type)
return number of heads for given drive
unsigned int drive_get_half_tracks (unsigned int type)
return number of physical half tracks for given drive
bool drive_is_jammed (int mynumber)
char * drive_jam_reason (int mynumber)
userport_desc_t * userport_get_valid_devices (int sort)
const char * userport_get_device_type_desc (int type)
Get short description of of userport device type.
void userport_io_sim_set_pbx_out_lines (uint8_t val)
int userport_device_register (int id, userport_device_t *device)
register a device to be used in the userport system if possible
bool pia1_get_diagnostic_pin (void)
sampler_device_t * sampler_get_devices (void)
void sampler_stop (void)
void sampler_start (int channels, char *devname)
uint8_t sampler_get_sample (int channel)
const driver_select_list_t * driver_select_get_drivers (void)
Get list of registered printer drivers.
bool driver_select_is_printer (const char *drv_name)
Determine if drive is a printer driver.
bool driver_select_is_plotter (const char *drv_name)
Determine if driver is a plotter driver.
bool driver_select_has_iec_bus (const char *drv_name)
Determine if driver supports an IEC bus-connected device.
bool driver_select_has_ieee488_bus (const char *drv_name)
Determine if driver supports an IEEE-488 bus-connected device.
bool driver_select_has_userport (const char *drv_name)
Determine if driver supports a userport-connected device.
bool driver_select_has_text_output (const char *drv_name)
Determine if driver supports text output.
bool driver_select_has_graphics_output (const char *drv_name)
Determine if driver supports graphics output.
Variables
int c64_256k_enabled = 0
static drive_type_info_t drive_dummy_list []
export_t export = { 0, 0, 0, 0 }
Expansion port signals.
static uint8_t mem_phi [0x1000]
the following two are used by the old non cycle exact vic-ii emulation
midi_interface_t midi_interface []
clockport_supported_devices_t clockport_supported_devices [] = { { 0, NULL } }
gfxoutputdrv_format_t ffmpegdrv_formatlist []
deprecated access for UIs that do not use the gfxoutputdrv->formatlist yet:
tape_image_t * tape_image_dev [TAPEPORT_MAX_PORTS] = { NULL }
The tape image for device 1.
iecbus_t iecbus
void(* iecbus_update_ports)(void) = NULL
diskunit_context_t * diskunit_context [4]
Function Documentation
c64_256k_cia_set_vbank()
void c64_256k_cia_set_vbank (int ciabank)
needed from c64gluelogic.c
cartridge_attach_image()
int cartridge_attach_image (int type, const char * filename)
attach (and enable) a cartridge by type and filename (takes crt and bin files)
Referenced by attach_cart_image(), autostart_autodetect(), and do_smart_attach().
cartridge_can_flush_image()
int cartridge_can_flush_image (int crtid)
returns 1 when cartridge (ROM) image can be flushed
Referenced by create_cart_image_widget(), and update_buttons_sensitivity().
cartridge_can_flush_secondary_image()
int cartridge_can_flush_secondary_image (int crtid)
Referenced by update_buttons_sensitivity().
cartridge_can_save_image()
int cartridge_can_save_image (int crtid)
returns 1 when cartridge (ROM) image can be saved
Referenced by create_cart_image_widget(), and update_buttons_sensitivity().
cartridge_can_save_secondary_image()
int cartridge_can_save_secondary_image (int crtid)
Referenced by update_buttons_sensitivity().
cartridge_detach_image()
void cartridge_detach_image (int type)
detaches/disables the cartridge with the associated id.
pass -1 to detach all
detaches/disables the cartridge with the associated id.
cartridge_disable()
int cartridge_disable (int crtid)
disable cartridge by type
Referenced by on_cart_enable_check_button_toggled(), and on_enable_toggled().
cartridge_enable()
int cartridge_enable (int crtid)
Referenced by on_cart_enable_check_button_toggled(), and on_enable_toggled().
cartridge_flush_image()
int cartridge_flush_image (int type)
Referenced by on_flush_clicked().
cartridge_flush_secondary_image()
int cartridge_flush_secondary_image (int type)
Referenced by on_flush_clicked().
cartridge_get_filename_by_slot()
char * cartridge_get_filename_by_slot (int slot)
Todo:
FIXME: slot arg is ignored right now. this should return a pointer to a filename, or NULL
Referenced by update_cart_file_widget().
cartridge_get_id()
int cartridge_get_id (int slot)
Todo:
FIXME: slot arg is ignored right now. this should return a valid cartridge ID for a given slot, or CARTRIDGE_NONE
Referenced by update_cart_type_widget().
cartridge_get_info_list()
cartridge_info_t * cartridge_get_info_list (void)
Referenced by create_cart_id_model(), and settings_default_cart_widget_create().
cartridge_save_image()
int cartridge_save_image (int type, const char * filename)
save the primary (rom/ram)image of the give cart type to a file
Referenced by on_save_response(), and save_filename_callback().
cartridge_save_secondary_image()
int cartridge_save_secondary_image (int type, const char * filename)
save the secondary image of the give cart type to a file
Referenced by on_save_response().
cartridge_set_default()
void cartridge_set_default (void)
set current "Main Slot" cart as default
Todo:
FIXME: this should also be made a generic function that takes the type
Referenced by attach_cart_image(), and on_set_default_clicked().
cartridge_trigger_freeze()
void cartridge_trigger_freeze (void)
freeze button pressed in UI
Todo:
FIXME: this should also be made a generic function that takes the type
Referenced by cart_freeze_action().
cartridge_type_enabled()
int cartridge_type_enabled (int crtid)
Referenced by carthelpers_create_enable_check_button(), create_mmc64_enable_widget(), iec_available_busses(), settings_ieee488_widget_create(), settings_ieeeflash64_widget_create(), and settings_ramlink_widget_create().
cartridge_unset_default()
void cartridge_unset_default (void)
called from resources_set_defaults()
disk_image_attach_log()
void disk_image_attach_log (const disk_image_t * image, signed int lognum, unsigned int unit, unsigned int drive)
Log attachment of disk image.
Parameters
[in] image disk image attached
[in] lognum (unused)
[in] unit unit the image is attached to
Referenced by cmdhd_attach_image(), drive_image_attach(), pc8477_attach_image(), vdrive_attach_image(), and wd1770_attach_image().
disk_image_check_sector()
int disk_image_check_sector (const disk_image_t * image, unsigned int track, unsigned int sector)
Check out of bound.
Check if a (track, sector) is inside bounds for image
Parameters
[in] image disk image
[in] track track number
[in] sector sector number
Returns
bool
Referenced by fsimage_dxx_read_sector(), fsimage_dxx_write_half_track(), fsimage_dxx_write_sector(), fsimage_read_dxx_image(), vdrive_bam_allocate_chain(), vdrive_bam_allocate_chain_255(), vdrive_command_allocate_chain(), vdrive_command_validate_worker(), and vdrive_dir_free_chain().
disk_image_close()
int disk_image_close (disk_image_t * image)
Referenced by attach_disk_image(), detach_disk_image(), and vdrive_internal_close_disk_image().
disk_image_create()
disk_image_t * disk_image_create (void)
Referenced by attach_disk_image().
disk_image_destroy()
void disk_image_destroy (disk_image_t * image)
Referenced by attach_disk_image(), and detach_disk_image_and_free().
disk_image_detach_log()
void disk_image_detach_log (const disk_image_t * image, signed int lognum, unsigned int unit, unsigned int drive)
Log detachment of disk image.
Parameters
[in] image disk image detached
[in] lognum (unused)
[in] unit unit the image is detached from
Referenced by cmdhd_detach_image(), drive_image_detach(), pc8477_detach_image(), vdrive_detach_image(), and wd1770_detach_image().
disk_image_fsimage_create()
int disk_image_fsimage_create (const char * name, unsigned int type)
Referenced by cbmimage_create_image().
disk_image_fsimage_create_dhd()
int disk_image_fsimage_create_dhd (const char * name, const char * dname, unsigned int type)
Referenced by cbmimage_create_dhd_image().
disk_image_fsimage_create_dxm()
int disk_image_fsimage_create_dxm (const char * name, const char * dname, unsigned int type)
Referenced by cbmimage_create_dxm_image().
disk_image_fsimage_fd_get()
void * disk_image_fsimage_fd_get (const disk_image_t * image)
Get file descriptor for image.
Parameters
[in] image disk image
Returns
file descriptor
Referenced by vdrive_command_format().
disk_image_fsimage_name_get()
const char * disk_image_fsimage_name_get (const disk_image_t * image)
Get disk image name.
Parameters
[in] image disk image
Returns
disk image name
Referenced by file_system_get_disk_name().
disk_image_fsimage_name_set()
void disk_image_fsimage_name_set (disk_image_t * image, const char * name)
Set disk image name.
Parameters
[in,out] image disk image
[in] name disk image name
Referenced by attach_disk_image().
disk_image_init()
void disk_image_init (void)
Initialization.
Referenced by machine_specific_init().
disk_image_media_create()
void disk_image_media_create (disk_image_t * image)
Referenced by attach_disk_image(), and vdrive_internal_open_fsimage().
disk_image_media_destroy()
void disk_image_media_destroy (disk_image_t * image)
Referenced by attach_disk_image(), detach_disk_image(), vdrive_internal_close_disk_image(), and vdrive_internal_open_fsimage().
disk_image_name_get()
const char * disk_image_name_get (const disk_image_t * image)
disk_image_name_set()
void disk_image_name_set (disk_image_t * image, const char * name)
Referenced by vdrive_internal_open_fsimage().
disk_image_open()
int disk_image_open (disk_image_t * image)
Referenced by attach_disk_image(), and vdrive_internal_open_fsimage().
disk_image_rawimage_driver_name_set()
void disk_image_rawimage_driver_name_set (disk_image_t * image)
disk_image_read_sector()
int disk_image_read_sector (const disk_image_t * image, uint8_t * buf, const disk_addr_t * dadr)
Referenced by cmdhd_findbaselba(), drive_snapshot_write_image_module(), fdd_update_raw(), vdrive_read_sector(), and vdrive_read_sector_physical().
disk_image_sector_per_track()
unsigned int disk_image_sector_per_track (unsigned int format, unsigned int track)
Get number of sectors for track in format.
Determines the number of sectors for a given track and disk image format.
Parameters
[in] format disk image type enumerator
[in] track track number
Returns
number of sectors or 0 on error
Referenced by fsimage_check_sector(), fsimage_create_gcr(), fsimage_create_p64(), fsimage_dxx_write_half_track(), fsimage_read_dxx_image(), and vdrive_get_max_sectors().
disk_image_write_p64_image()
int disk_image_write_p64_image (const disk_image_t * image)
Referenced by drive_gcr_data_writeback_all(), and drive_image_detach().
disk_image_write_sector()
int disk_image_write_sector (disk_image_t * image, const uint8_t * buf, const disk_addr_t * dadr)
Referenced by drive_snapshot_read_image_module(), fdd_flush_raw(), vdrive_write_sector(), and vdrive_write_sector_physical().
diskcontents_block_read()
image_contents_t * diskcontents_block_read (struct vdrive_s * vdrive, int part)
< standard length of container names, such as D64
< standard length of container names, such as D64
< length of a disk ID
< length of a disk ID
< lenght of a PETSCII filename
< lenght of a PETSCII filename
diskcontents_filesystem_read()
image_contents_t * diskcontents_filesystem_read (const char * file_name)
drive_check_dual()
unsigned int drive_check_dual (unsigned int type)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
drive_check_expansion2000()
int drive_check_expansion2000 (int type)
drive_check_expansion4000()
int drive_check_expansion4000 (int type)
drive_check_expansion6000()
int drive_check_expansion6000 (int type)
drive_check_expansion8000()
int drive_check_expansion8000 (int type)
drive_check_expansionA000()
int drive_check_expansionA000 (int type)
drive_check_extend_policy()
int drive_check_extend_policy (int drive_type)
Todo:
FIXME: will be always extended
Todo:
FIXME: will be always extended
Todo:
FIXME: will be always extended
Todo:
FIXME: will be always extended
drive_check_idle_method()
int drive_check_idle_method (int drive_type)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
drive_check_iec()
int drive_check_iec (int type)
< ASCII for HD
drive_check_image_format()
int drive_check_image_format (unsigned int format, unsigned int dnr)
< DOS 1 dual floppy drive, 170k/disk
Todo:
FIXME: only read compat
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< D9090/D9060
< DOS 3.0 hard drive
< HD in ASCII for CMDHD
< ASCII for HD
drive_check_parallel_cable()
int drive_check_parallel_cable (int drive_type)
drive_check_profdos()
int drive_check_profdos (int type)
drive_check_rtc()
int drive_check_rtc (int type)
Check if drive_type supports a real-time clock.
Parameters
[in] drive_type drive type
Returns
bool
< ASCII for HD
drive_check_stardos()
int drive_check_stardos (int type)
Todo:
FIXME: stardos apparently exists for 157x, needs more research
drive_check_supercard()
int drive_check_supercard (int type)
drive_check_type()
int drive_check_type (unsigned int drive_type, unsigned int dnr)
drive_cpu_early_init_all()
void drive_cpu_early_init_all (void)
drive_cpu_execute_all()
void drive_cpu_execute_all (CLOCK clk_value)
drive_cpu_execute_one()
void drive_cpu_execute_one (diskunit_context_t * drv, CLOCK clk_value)
< ASCII for HD
drive_cpu_trigger_reset()
void drive_cpu_trigger_reset (unsigned int dnr)
reset one drive only
< ASCII for HD
drive_cpu_trigger_reset_button()
void drive_cpu_trigger_reset_button (unsigned int dnr, unsigned int button)
drive_get_disk_drive_type()
int drive_get_disk_drive_type (int dnr)
drive_get_half_tracks()
unsigned int drive_get_half_tracks (unsigned int type)
return number of physical half tracks for given drive
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
drive_get_num_heads()
unsigned int drive_get_num_heads (unsigned int type)
return number of heads for given drive
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 1M/disk
drive_get_type_by_devnr()
int drive_get_type_by_devnr (int devnr)
Todo:
FIXME: xvic has its own IEC code and doesn't use "IECDevice[8-11]"
drive_has_buttons()
int drive_has_buttons (unsigned int dnr)
< ASCII for HD
drive_image_attach()
int drive_image_attach (disk_image_t * image, unsigned int unit, unsigned int drive)
Attach a disk image to the true drive emulation.
drive_image_detach()
int drive_image_detach (disk_image_t * image, unsigned int unit, unsigned int drive)
Detach a disk image from the true drive emulation.
drive_image_type_to_drive_type()
int drive_image_type_to_drive_type (unsigned int type)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< D9090/D9060
< DOS 3.0 hard drive
< HD in ASCII for CMDHD
< ASCII for HD
drive_is_dualdrive_by_devnr()
int drive_is_dualdrive_by_devnr (int devnr)
drive_is_jammed()
bool drive_is_jammed (int mynumber)
drive_jam_reason()
char * drive_jam_reason (int mynumber)
drive_num_leds()
int drive_num_leds (unsigned int dnr)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
< ASCII for HD
drive_set_disk_memory()
void drive_set_disk_memory (uint8_t * id, unsigned int track, unsigned int sector, struct diskunit_context_s * drv)
drive_set_last_read()
void drive_set_last_read (unsigned int track, unsigned int sector, uint8_t * buffer, struct diskunit_context_s * drv)
Todo:
drive 1 ?
Todo:
drive 1 ?
drive_setup_context()
void drive_setup_context (void)
drive_shutdown()
void drive_shutdown (void)
< ASCII for HD
driver_select_get_drivers()
const driver_select_list_t * driver_select_get_drivers (void)
Get list of registered printer drivers.
Returns
singly-linked list of registered drivers
driver_select_has_graphics_output()
bool driver_select_has_graphics_output (const char * drv_name)
Determine if driver supports graphics output.
Parameters
[in] drv_name driver name
Returns
true if drv_name supports graphics output
driver_select_has_iec_bus()
bool driver_select_has_iec_bus (const char * drv_name)
Determine if driver supports an IEC bus-connected device.
Parameters
[in] drv_name driver name
Returns
true if drv_name is an IEC driver
driver_select_has_ieee488_bus()
bool driver_select_has_ieee488_bus (const char * drv_name)
Determine if driver supports an IEEE-488 bus-connected device.
Parameters
[in] drv_name driver name
Returns
true if drv_name is an IEEE-488 driver
driver_select_has_text_output()
bool driver_select_has_text_output (const char * drv_name)
Determine if driver supports text output.
Parameters
[in] drv_name driver name
Returns
true if drv_name supports text output
driver_select_has_userport()
bool driver_select_has_userport (const char * drv_name)
Determine if driver supports a userport-connected device.
Parameters
[in] drv_name driver name
Returns
true if drv_name is a userport driver
driver_select_is_plotter()
bool driver_select_is_plotter (const char * drv_name)
Determine if driver is a plotter driver.
Parameters
[in] drv_name driver name
Returns
true if drv_name is a plotter driver
driver_select_is_printer()
bool driver_select_is_printer (const char * drv_name)
Determine if drive is a printer driver.
Parameters
[in] drv_name driver name
Returns
true if drv_name is a printer driver
ds1202_1302_destroy()
void ds1202_1302_destroy (rtc_ds1202_1302_t * context, int save)
ds1202_1302_init()
rtc_ds1202_1302_t * ds1202_1302_init (char * device, int rtc_type)
ds1202_1302_read_data_line()
uint8_t ds1202_1302_read_data_line (rtc_ds1202_1302_t * context)
ds1202_1302_read_snapshot()
int ds1202_1302_read_snapshot (rtc_ds1202_1302_t * context, snapshot_t * s)
ds1202_1302_set_lines()
void ds1202_1302_set_lines (rtc_ds1202_1302_t * context, unsigned int ce_line, unsigned int sclk_line, unsigned int input_bit)
ds1202_1302_write_snapshot()
int ds1202_1302_write_snapshot (rtc_ds1202_1302_t * context, snapshot_t * s)
ds1216e_destroy()
void ds1216e_destroy (rtc_ds1216e_t * context, int save)
Todo:
FIXME: this stub can be removed once the drive code has been stubbed
Referenced by drive_resources_type(), and drive_shutdown().
ds1216e_init()
rtc_ds1216e_t * ds1216e_init (char * device)
Todo:
FIXME: this stub can be removed once the drive code has been stubbed
Referenced by drive_resources_type().
ds1216e_read()
uint8_t ds1216e_read (rtc_ds1216e_t * context, uint16_t address, uint8_t origbyte)
Referenced by drive_read_rom_ds1216().
ds1602_destroy()
void ds1602_destroy (rtc_ds1602_t * context, int save)
ds1602_init()
rtc_ds1602_t * ds1602_init (char * device, time_t offset0)
ds1602_read_data_line()
uint8_t ds1602_read_data_line (rtc_ds1602_t * context)
ds1602_read_snapshot()
int ds1602_read_snapshot (rtc_ds1602_t * context, snapshot_t * s)
ds1602_set_clk_line()
void ds1602_set_clk_line (rtc_ds1602_t * context, uint8_t data)
ds1602_set_data_line()
void ds1602_set_data_line (rtc_ds1602_t * context, uint8_t data)
ds1602_set_reset_line()
void ds1602_set_reset_line (rtc_ds1602_t * context, uint8_t data)
ds1602_write_snapshot()
int ds1602_write_snapshot (rtc_ds1602_t * context, snapshot_t * s)
fileio_close()
void fileio_close (fileio_info_t * info)
Referenced by autostart_prg(), command_directory_get(), and fsdevice_close().
fileio_ferror()
unsigned int fileio_ferror (fileio_info_t * info)
Referenced by command_read(), and relative_read().
fileio_get_bytes_left()
unsigned int fileio_get_bytes_left (fileio_info_t * info)
Referenced by fsdevice_relative_switch_record(), and load_prg().
fileio_open()
fileio_info_t * fileio_open (const char * file_name, const char * path, unsigned int format, unsigned int command, unsigned int type, int * reclenp)
Referenced by autostart_prg(), command_directory_get(), and fsdevice_open_file().
fileio_read()
unsigned int fileio_read (fileio_info_t * info, uint8_t * buf, unsigned int len)
Referenced by command_read(), fsdevice_relative_switch_record(), load_prg(), and relative_read().
fileio_rename()
unsigned int fileio_rename (const char * src_name, const char * dest_name, const char * path, unsigned int format)
Referenced by fsdevice_flush_rename().
fileio_scratch()
unsigned int fileio_scratch (const char * file_name, const char * path, unsigned int format)
Referenced by fsdevice_flush_scratch().
fileio_write()
unsigned int fileio_write (fileio_info_t * info, uint8_t * buf, unsigned int len)
Referenced by fsdevice_relative_pad_record(), fsdevice_relfile_extend_if_needed(), and fsdevice_write().
fsdevice_attach()
int fsdevice_attach (unsigned int device, unsigned int drive, const char * name)
Referenced by file_system_set_serial_hooks().
fsdevice_init()
void fsdevice_init (void)
Referenced by machine_init().
fsdevice_limit_namelength()
int fsdevice_limit_namelength (vdrive_t * vdrive, uint8_t * name)
fsdevice_set_directory()
void fsdevice_set_directory (char * filename, unsigned int unit)
Referenced by autostart_prg_with_virtual_fs(), cmdline_fsdirectory(), and fsdevice_flush_cd().
fsdevice_shutdown()
void fsdevice_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
gfxoutput_cmdline_options_init()
int gfxoutput_cmdline_options_init (void)
Referenced by main_program().
gfxoutput_drivers_iter_init()
gfxoutputdrv_t * gfxoutput_drivers_iter_init (void)
Todo:
FIXME: this stub can be removed once all GUI's have been adapted to not use this call for vsid
Referenced by create_video_driver_list(), and settings_snapshot_widget_create().
gfxoutput_drivers_iter_next()
gfxoutputdrv_t * gfxoutput_drivers_iter_next (void)
Todo:
FIXME: this stub can be removed once all GUI's have been adapted to not use this call for vsid
Referenced by create_video_driver_list(), and settings_snapshot_widget_create().
gfxoutput_early_init()
int gfxoutput_early_init (int help)
Referenced by main_program().
gfxoutput_get_driver()
gfxoutputdrv_t * gfxoutput_get_driver (const char * drvname)
Todo:
FIXME: this stub can be removed once all GUI's have been adapted to not use this call for vsid
Referenced by ffmpeg_widget_create(), output_graphics_open(), screenshot_get_fext_for_format(), and screenshot_save().
gfxoutput_num_drivers()
int gfxoutput_num_drivers (void)
Referenced by create_video_driver_list().
gfxoutput_resources_init()
int gfxoutput_resources_init (void)
Functions called by external emulator code.
Referenced by main_program().
gfxoutput_shutdown()
void gfxoutput_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
iec_available_busses()
int iec_available_busses (void)
This function is called from ui_update_menus()
< c64tpi.c
< ieeeflash64.c
< serial IEC bus
< parallel IEEE bus
< serial IEC bus
Referenced by drive_check_type(), and drive_resources_type().
iecbus_device_read()
uint8_t iecbus_device_read (void)
Referenced by serial_iec_device_exec_main().
iecbus_device_write()
int iecbus_device_write (unsigned int unit, uint8_t data)
Referenced by serial_iec_device_disable(), serial_iec_device_exec_main(), serial_iec_device_init(), and serial_iec_device_reset().
iecbus_status_set()
void iecbus_status_set (unsigned int type, unsigned int unit, unsigned int enable)
Referenced by machine_bus_status_drivetype_set(), machine_bus_status_truedrive_set(), machine_bus_status_virtualdevices_set(), and set_iec_device_enable().
image_contents_destroy()
void image_contents_destroy (image_contents_t * contents)
Free memory used by contents and its members.
Parameters
[in/out] contents image contents object
Referenced by autostart_disk(), create_model(), and dir_menu_popup_create().
image_contents_file_to_string()
char * image_contents_file_to_string (image_contents_file_list_t * p, char convert_to_ascii)
Generate a '<blocks> "<filename>" *prg<' line from p.
Parameters
[in] p image contents file list
[in] out_charset selects output charset
Returns
allocated string, free with lib_free()
< return string in PETSCII form
Referenced by create_model(), dir_menu_popup_create(), and mon_drive_list().
image_contents_filename_by_number()
char * image_contents_filename_by_number (image_contents_t * contents, unsigned int file_index)
Get image contents file name by index.
Parameters
[in] contents image contents object
[in] file_index index in contents' file list
Returns
allocated string, free with lib_free(), or NULL when file_index was too large
Referenced by autostart_disk().
image_contents_to_screencode()
image_contents_screencode_t * image_contents_to_screencode (image_contents_t * contents)
image_contents_to_string()
char * image_contents_to_string (image_contents_t * contents, char convert_to_ascii)
Generate the first line of a directory listing (0 name id)
Todo:
FIXME: DEAD CODE Also this function formats the listing slightly wrong (different than a real drive would)
Parameters
[in] contents image contents object
[in] out_charset selects output charset
Returns
heap allocated string, free with lib_free()
< return string in PETSCII form
Referenced by create_model(), dir_menu_popup_create(), and mon_drive_list().
machine_bus_attention_callback_set()
void machine_bus_attention_callback_set (void(*)(void) func)
Referenced by advance_hasdisk(), and disk_attention_callback().
machine_bus_device_type_get()
unsigned int machine_bus_device_type_get (unsigned int unit)
machine_bus_eof_callback_set()
void machine_bus_eof_callback_set (void(*)(void) func)
Referenced by disk_attention_callback(), and disk_eof_callback().
machine_bus_init_machine()
void machine_bus_init_machine (void)
Referenced by machine_bus_init().
machine_bus_lib_directory()
int machine_bus_lib_directory (unsigned int unit, const char * pattern, uint8_t ** buf)
machine_bus_lib_read_sector()
int machine_bus_lib_read_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t * buf)
machine_bus_lib_write_sector()
int machine_bus_lib_write_sector (unsigned int unit, unsigned int track, unsigned int sector, uint8_t * buf)
machine_bus_status_drivetype_set()
void machine_bus_status_drivetype_set (unsigned int unit, unsigned int enable)
Referenced by drive_resources_type(), drive_snapshot_read_module(), and driverom_load().
machine_bus_status_truedrive_set()
void machine_bus_status_truedrive_set (unsigned int unit, unsigned int enable)
Referenced by set_drive_true_emulation().
machine_bus_status_virtualdevices_set()
void machine_bus_status_virtualdevices_set (unsigned int unit, unsigned int enable)
Referenced by set_traps_enabled().
machine_drive_get_type_info_list()
drive_type_info_t * machine_drive_get_type_info_list (void)
Dummy function.
Get a list of (name, id) tuples for the drives handles by C64.
Added here to make gtk3/widgets/drivetypewidget.c compile, due to using static libraries. This function will not be used in the VSID Gtk3 UI
Referenced by create_combo_model(), drive_model_widget_create(), and drive_model_widget_update().
machine_drive_image_attach()
int machine_drive_image_attach (struct disk_image_s * image, unsigned int unit, unsigned int drive)
Referenced by attach_disk_image().
machine_drive_image_detach()
int machine_drive_image_detach (struct disk_image_s * image, unsigned int unit, unsigned int drive)
Referenced by detach_disk_image().
machine_drive_stub()
void machine_drive_stub (void)
Referenced by machine_specific_init().
machine_get_keyboard_info_list()
kbdtype_info_t * machine_get_keyboard_info_list (void)
Referenced by keyboard_is_hosttype_valid().
machine_get_num_keyboard_types()
int machine_get_num_keyboard_types (void)
return number of available keyboard types for this machine
Referenced by keyboard_is_hosttype_valid().
P64ImageDestroy()
void P64ImageDestroy (PP64Image Instance)
Referenced by attach_disk_image(), detach_disk_image(), drive_shutdown(), fsimage_create_p64(), vdrive_internal_close_disk_image(), and vdrive_internal_open_fsimage().
pia1_get_diagnostic_pin()
bool pia1_get_diagnostic_pin (void)
printer_formfeed()
void printer_formfeed (unsigned int prnr)
Send formfeed to printer.
Todo:
FIXME: this stub can be removed once all GUI's have been adapted to not use this call for vsid
printer_serial_late_init()
int printer_serial_late_init (void)
printer_shutdown()
void printer_shutdown (void)
< serial dev 4, 5, 6 and user port
sampler_get_devices()
sampler_device_t * sampler_get_devices (void)
sampler_get_sample()
uint8_t sampler_get_sample (int channel)
< 100%
sampler_start()
void sampler_start (int channels, char * devname)
sampler_stop()
void sampler_stop (void)
tap_seek_start()
int tap_seek_start (tap_t * tap)
Referenced by tape_seek_start().
tap_seek_to_offset()
int tap_seek_to_offset (tap_t * tap, unsigned long offset)
Referenced by tape_seek_to_offset().
tape_get_current_file_record()
tape_file_record_t * tape_get_current_file_record (tape_image_t * tape_image)
Referenced by fsdevice_open_file(), and tape_read_contents().
tape_get_file_name()
const char * tape_get_file_name (int port)
tape_get_header()
void tape_get_header (tape_image_t * tape_image, uint8_t * name)
Referenced by tape_read_contents().
tape_get_offset()
unsigned long tape_get_offset (tape_image_t * tape_image)
Referenced by mon_tape_offs().
tape_image_attach()
int tape_image_attach (unsigned int unit, const char * name)
Referenced by autostart_tape(), create_tape_image(), do_attach(), do_smart_attach(), initcmdline_check_attach(), mon_attach(), and tape_snapshot_read_tapimage_module().
tape_image_close()
int tape_image_close (tape_image_t * tape_image)
Referenced by fsdevice_close(), tape_image_detach_internal(), and tape_internal_close_tape_image().
tape_image_create()
int tape_image_create (const char * name, unsigned int type)
Referenced by cbmimage_create_image().
tape_image_detach()
int tape_image_detach (unsigned int unit)
External tape image interface.
Referenced by autostart_tape(), mon_detach(), and tape_detach_action().
tape_image_detach_all()
void tape_image_detach_all (void)
tape_image_event_playback()
void tape_image_event_playback (unsigned int unit, const char * filename)
Referenced by event_alarm_handler(), event_playback_attach_image(), and event_playback_event_list().
tape_image_open()
int tape_image_open (tape_image_t * tape_image)
Referenced by fsdevice_open_file(), tape_image_attach_internal(), and tape_internal_open_tape_image().
tape_internal_close_tape_image()
int tape_internal_close_tape_image (tape_image_t * tape_image)
Referenced by tapecontents_read().
tape_internal_open_tape_image()
tape_image_t * tape_internal_open_tape_image (const char * name, unsigned int read_only)
Referenced by tapecontents_read().
tape_read()
int tape_read (tape_image_t * tape_image, uint8_t * buf, size_t size)
used by virtual devices
Referenced by command_read().
tape_seek_start()
int tape_seek_start (tape_image_t * tape_image)
Referenced by autostart_tape(), and fsdevice_open_file().
tape_seek_to_file()
int tape_seek_to_file (tape_image_t * tape_image, unsigned int file_number)
Referenced by autostart_tape(), and fsdevice_open_file().
tape_seek_to_next_file()
int tape_seek_to_next_file (tape_image_t * tape_image, unsigned int allow_rewind)
Referenced by tape_read_contents().
tape_seek_to_offset()
int tape_seek_to_offset (tape_image_t * tape_image, unsigned long offset)
Referenced by autostart_tape(), and mon_tape_offs().
tape_shutdown()
void tape_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
tape_snapshot_read_module()
int tape_snapshot_read_module (int port, snapshot_t * s)
tape_snapshot_write_module()
int tape_snapshot_write_module (int port, snapshot_t * s, int save_image)
tape_tap_attached()
int tape_tap_attached (int port)
Referenced by autostart_tape().
tapecart_attach_tcrt()
int tapecart_attach_tcrt (const char * filename, void * unused)
tapecart_flush_tcrt()
int tapecart_flush_tcrt (void)
Flush current tapecart data to image file.
Returns
0 on success, < 0 on failure
tapecart_is_valid()
int tapecart_is_valid (const char * filename)
Check magic of the tapecart filename.
Checks the first 13 bytes for 'tapecartImage', which seems to be the TCRT header magic.
Returns
bool
tapecontents_read()
image_contents_t * tapecontents_read (const char * file_name)
tapeport_device_register()
int tapeport_device_register (int id, tapeport_device_t * device)
register a device to be used in the tapeport system
tapeport_set_tape_sense()
void tapeport_set_tape_sense (int sense, int port)
tapeport_trigger_flux_change()
void tapeport_trigger_flux_change (unsigned int on, int port)
tapeport_valid_port()
int tapeport_valid_port (int port)
ultimax_romh_phi1_ptr()
uint8_t * ultimax_romh_phi1_ptr (uint16_t addr)
Referenced by handle_fetch_sprite(), and vicii_update_memory_ptrs().
ultimax_romh_phi2_ptr()
uint8_t * ultimax_romh_phi2_ptr (uint16_t addr)
Referenced by handle_fetch_sprite(), and vicii_update_memory_ptrs().
userport_device_register()
int userport_device_register (int id, userport_device_t * device)
register a device to be used in the userport system if possible
userport_get_device_type_desc()
const char * userport_get_device_type_desc (int type)
Get short description of of userport device type.
Parameters
[in] type userport device type
userport_get_valid_devices()
userport_desc_t * userport_get_valid_devices (int sort)
userport_io_sim_set_pbx_out_lines()
void userport_io_sim_set_pbx_out_lines (uint8_t val)
vdrive_attach_image()
int vdrive_attach_image (disk_image_t * image, unsigned int unit, unsigned int drive, vdrive_t * vdrive)
< number of tracks on a standard 1541 floppy
< Dual Disk Drive
< number of tracks on a 1571 floppy
< Dual Disk Drive
< Dual Disk Drive
< number of tracks on a standard 1541 floppy
< number of tracks on a 1571 floppy
Todo:
FIXME: extra checks might be needed for supporting other drives
< number of tracks on a 1571 floppy
< number of tracks on a standard 1541 floppy
< HD in ASCII for CMDHD
< D9090/D9060
vdrive->dir_part = drive;
< HD in ASCII for CMDHD
vdrive_bam_get_disk_id()
int vdrive_bam_get_disk_id (unsigned int unit, unsigned int drive, uint8_t * id)
get disk id
vdrive_bam_set_disk_id()
int vdrive_bam_set_disk_id (unsigned int unit, unsigned int drive, uint8_t * id)
set disk id
vdrive_command_execute()
int vdrive_command_execute (vdrive_t * vdrive, const uint8_t * buf, unsigned int length)
called by vdrive-iec.c; return code not used
< real 58
check for unabbreviated commands
check for abbreviated commands
vdrive_detach_image()
void vdrive_detach_image (disk_image_t * image, unsigned int unit, unsigned int drive, vdrive_t * vdrive)
vdrive_device_setup()
int vdrive_device_setup (vdrive_t * vdrive, unsigned int unit)
vdrive_device_shutdown()
void vdrive_device_shutdown (vdrive_t * vdrive)
vdrive_ext_read_sector()
int vdrive_ext_read_sector (vdrive_t * vdrive, int drive, uint8_t * buf, unsigned int track, unsigned int sector)
For external access to individual drives.
vdrive_ext_write_sector()
int vdrive_ext_write_sector (vdrive_t * vdrive, int drive, const uint8_t * buf, unsigned int track, unsigned int sector)
vdrive_get_image()
struct disk_image_s * vdrive_get_image (vdrive_t * vdrive, unsigned int drive)
vdrive_get_last_read()
void vdrive_get_last_read (unsigned int * track, unsigned int * sector, uint8_t ** buffer)
vdrive_iec_attach()
int vdrive_iec_attach (unsigned int unit, const char * name)
vdrive_iec_close()
int vdrive_iec_close (vdrive_t * vdrive, unsigned int secondary)
Todo:
FIXME: Is this correct?
vdrive_close_all_channels(vdrive);
vdrive_iec_open()
int vdrive_iec_open (struct vdrive_s * vdrive, const uint8_t * name, unsigned int length, unsigned int secondary, struct cbmdos_cmd_parse_s * cmd_parse_ext)
Generic IEC interface.
Todo:
FIXME: "file" has requested buffer
< should match FILEIO_TYPE_xxx
< should match FILEIO_TYPE_xxx
< for relative files
< for relative files
vdrive_iec_read()
int vdrive_iec_read (vdrive_t * vdrive, uint8_t * data, unsigned int secondary)
vdrive_iec_write()
int vdrive_iec_write (vdrive_t * vdrive, uint8_t data, unsigned int secondary)
vdrive_init()
void vdrive_init (void)
vdrive_internal_create_format_disk_image()
int vdrive_internal_create_format_disk_image (const char * filename, const char * diskname, unsigned int type)
< HD in ASCII for CMDHD
Variable Documentation
c64_256k_enabled
int c64_256k_enabled = 0
clockport_supported_devices
clockport_supported_devices_t clockport_supported_devices[] = { { 0, NULL } }
Referenced by clockport_device_widget_create().
diskunit_context
diskunit_context_t* diskunit_context[4]
drive_dummy_list
drive_type_info_t drive_dummy_list[] static
Initial value:
= {
    { NULL, -1 }
}
Referenced by machine_drive_get_type_info_list().
export
export_t export = { 0, 0, 0, 0 }
Expansion port signals.
this is referenced by the VICII emulation
Referenced by c64_snapshot_read_module(), c64_snapshot_write_module(), export_dump(), handle_fetch_sprite(), mem_initialize_memory(), mem_pla_config_changed(), and vicii_update_memory_ptrs().
ffmpegdrv_formatlist
gfxoutputdrv_format_t ffmpegdrv_formatlist[]
Initial value:
=
{
    { NULL, NULL, NULL, 0 }
}
deprecated access for UIs that do not use the gfxoutputdrv->formatlist yet:
Todo:
FIXME: this table can be removed once all GUI's have been adapted to not use this table for vsid
iecbus
iecbus_t iecbus
iecbus_update_ports
void(* iecbus_update_ports) (void) (void) = NULL
Referenced by c64iec_init().
mem_phi
uint8_t mem_phi[0x1000] static
the following two are used by the old non cycle exact vic-ii emulation
Referenced by ultimax_romh_phi1_ptr(), and ultimax_romh_phi2_ptr().
midi_interface
midi_interface_t midi_interface[]
Initial value:
= {
     { NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
}
tape_image_dev
tape_image_t* tape_image_dev[TAPEPORT_MAX_PORTS] = { NULL }
The tape image for device 1.
Referenced by autostart_tape(), dir_menu_popup_create(), mon_tape_offs(), tape_snapshot_read_module(), tape_snapshot_write_module(), and tape_snapshot_write_tapimage_module().