vsid: autostart.c File Reference
autostart.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "autostart.h"
#include "autostart-prg.h"
#include "attach.h"
#include "cartridge.h"
#include "charset.h"
#include "cmdline.h"
#include "datasette.h"
#include "diskimage.h"
#include "drive.h"
#include "driveimage.h"
#include "fileio.h"
#include "fsdevice.h"
#include "fsdevice-filename.h"
#include "imagecontents.h"
#include "tapecontents.h"
#include "diskcontents.h"
#include "initcmdline.h"
#include "interrupt.h"
#include "kbdbuf.h"
#include "lib.h"
#include "log.h"
#include "machine-bus.h"
#include "machine.h"
#include "maincpu.h"
#include "mainlock.h"
#include "mem.h"
#include "monitor.h"
#include "mon_breakpoint.h"
#include "network.h"
#include "resources.h"
#include "snapshot.h"
#include "tape.h"
#include "tapecart.h"
#include "tapeport.h"
#include "types.h"
#include "uiapi.h"
#include "util.h"
#include "vdrive.h"
#include "vdrive-bam.h"
#include "vice-event.h"
#include "vsync.h"
Macros
#define DBG(_x_)
#define DBGWAIT(_x_)
#define AUTOSTART_WAIT_BLINK 0
#define AUTOSTART_NOWAIT_BLINK 1
#define AUTOSTART_CHECK_ANY_COLUMN 0
#define AUTOSTART_CHECK_FIRST_COLUMN 1
#define AUTOSTART_DISK_IMAGE 0
#define AUTOSTART_PRG_VFS 1
#define AUTOSTART_PRG_DISK 2
#define AUTOSTART_PRG_INJECT 3
Enumerations
enum {
AUTOSTART_NONE ,
AUTOSTART_ERROR ,
AUTOSTART_HASTAPE ,
AUTOSTART_PRESSPLAYONTAPE ,
AUTOSTART_LOADINGTAPE ,
AUTOSTART_HASDISK ,
AUTOSTART_LOADINGDISK ,
AUTOSTART_HASSNAPSHOT ,
AUTOSTART_WAITLOADREADY ,
AUTOSTART_WAITLOADING ,
AUTOSTART_WAITSEARCHINGFOR ,
AUTOSTART_INJECT ,
AUTOSTART_DONE
}
Current state of the autostart routine.
enum CHECKYESNO {
YES ,
NO ,
NOT_YET
}
Functions
static void autostart_done (void)
This is called if all steps of an autostart operation were passed successfully.
static void autostart_finish (void)
this is called after successful loading
static void set_handle_true_drive_emulation_state (void)
static int set_autostart_basic_load (int val, void *param)
set if autostart should use LOAD ... ,1
static int set_autostart_tape_basic_load (int val, void *param)
set if autostart from tape should use LOAD ... ,1
static int set_autostart_run_with_colon (int val, void *param)
set if autostart should execute with a colon or not
static int set_autostart_handle_tde (int val, void *param)
set if autostart should handle TDE or not
static int set_autostart_warp (int val, void *param)
set if autostart should enable warp mode
static int set_autostart_delay (int val, void *param)
set initial autostart delay. 0 means default.
static int set_autostart_delayrandom (int val, void *param)
set initial autostart random delay. 0 means off, 1 means on.
static int set_autostart_prg_mode (int val, void *param)
set autostart prg mode
static int set_autostart_prg_disk_image (const char *val, void *param)
set disk image name of autostart prg mode
static int set_autostart_drop_mode (int mode, void *unused)
Resource setter for "AutostartDropMode" resource.
static int cmdline_set_autostart_drop_mode (const char *value, void *unused)
Command line resource setter for "AutostartDropMode" resource.
int autostart_resources_init (void)
initialize the resources
void autostart_resources_shutdown (void)
int autostart_set_initial_tap_offset (unsigned long offset)
static int cmdline_set_tap_offset (const char *arg, void *param)
int autostart_cmdline_options_init (void)
initialize the command-line options
static void deallocate_program_name (void)
Deallocate program name if we have one.
static CHECKYESNO check2 (const char *s, unsigned int blink_mode, int lineoffset, int checkcursor)
static CHECKYESNO check (const char *s, unsigned int blink_mode)
static void set_true_drive_emulation_mode (int on, int unit)
static int get_true_drive_emulation_state (int unit)
static void set_iec_device_state (int on, int unit)
static int get_iec_device_state (int unit)
static void set_warp_mode (int on)
static int get_device_traps_state (int unit)
static void set_device_traps_state (int unit, int on)
static void enable_warp_if_requested (void)
static void disable_warp_if_was_requested (void)
static int check_rom_area (void)
returns 0 if we left ROM area and should disable autostart
static void init_drive_emulation_state (int unit, int drive)
static void restore_drive_emulation_state (int unit, int drive)
static void load_snapshot_trap (uint16_t unused_addr, void *unused_data)
static void autostart_reinit (int default_seconds, int handle_tde)
Reset autostart.
int autostart_init (int default_seconds, int handle_drive_true_emulation)
Initialize autostart.
void autostart_disable (void)
void autostart_trigger_monitor (int enable)
Control if the monitor will be triggered after an autostart.
static void disk_eof_callback (void)
static void disk_attention_callback (void)
static void advance_hastape (void)
static void advance_pressplayontape (void)
static void advance_loadingtape (void)
static void setup_for_disk_ready (int unit, int drive)
static void advance_hasdisk (int unit, int drive)
static void advance_hassnapshot (void)
static void advance_waitsearchingfor (void)
static void advance_waitloading (void)
static void advance_waitloadready (void)
static void advance_inject (void)
After a reset a PRG file has to be injected into RAM.
void autostart_advance (void)
static void reboot_for_autostart (const char *program_name, unsigned int mode, unsigned int runmode)
Clean memory and reboot for autostart.
int autostart_snapshot (const char *file_name, const char *program_name)
Autostart snapshot file ‘file_name’.
int autostart_tape (const char *file_name, const char *program_name, unsigned int program_number, unsigned int runmode, unsigned int tapeport)
Autostart tape image ‘file_name’.
static void autostart_disk_cook_name (char **name)
Cope with 0xa0 padded file names.
static void setup_for_disk (int unit, int drive)
int autostart_disk (int unit, int drive, const char *file_name, const char *program_name, unsigned int program_number, unsigned int runmode)
Autostart disk image ‘file_name’.
static void setup_for_prg_vfs (int unit)
int autostart_prg (const char *file_name, unsigned int runmode)
int autostart_tapecart (const char *file_name, void *unused)
Autostart tapecart image file_name.
int autostart_autodetect_opt_prgname (const char *file_prog_name, unsigned int alt_prg_number, unsigned int runmode)
static void set_tapeport_device (int datasette, int tapecart)
int autostart_autodetect (const char *file_name, const char *program_name, unsigned int program_number, unsigned int runmode)
void autostart_reinit(int default_seconds, int handle_drive_true_emulation);
int autostart_in_progress (void)
void autostart_reset (void)
Disable autostart on reset.
void autostart_shutdown (void)
Variables
static enum { ... } autostartmode = AUTOSTART_NONE
Current state of the autostart routine.
log_t autostart_log = ((log_t)-1)
Log descriptor.
static int orig_drive_true_emulation_state = -1
Flag: was true drive emulation turned on when we started booting the disk image?
static int orig_device_traps_state = -1
Flag: were device traps turned on when we started booting the disk image?
static int orig_iec_device_state = -1
Flag: was iec device turned on when we started booting the disk image?
static int orig_warp_mode = -1
Flag: warp mode state before booting.
static int orig_FileSystemDevice8 = -1
static int orig_FSDevice8ConvertP00 = -1
static int orig_FSDeviceLongNames = -1
static char * autostart_program_name = NULL
PETSCII name of the program to load.
static CLOCK autostart_initial_delay_cycles
Minimum number of cycles before we feed BASIC with commands.
static int handle_drive_true_emulation_overridden
static int handle_drive_true_emulation_by_machine
Flag: Does the machine want us to switch true drive emulation on/off during autostart?
static int autostart_enabled = 0
Flag: autostart is initialized.
static unsigned int autostart_run_mode
Flag: Autostart the file or just load it?
static int autostart_wait_for_reset
Flag: maincpu_clk isn't resetted yet.
static int entered_rom = 0
Flag: load stage after LOADING enters ROM area.
static int trigger_monitor = 0
Flag: trap monitor after done.
int autostart_ignore_reset = 0
static int autostart_disk_unit = 8
static int autostart_disk_drive = 0
static int autostart_tape_unit = 1
static int autostart_type = -1
static size_t tap_initial_raw_offset = 0
int autostart_basic_load = 0
int autostart_tape_basic_load = 1
static int AutostartRunWithColon = 0
static int AutostartHandleTrueDriveEmulation = 0
static int AutostartWarp = 0
static int AutostartDelay = 0
static int AutostartDelayDefaultSeconds = 0
static int AutostartDelayRandom = 0
static int AutostartPrgMode = 0
static char * AutostartPrgDiskImage = NULL
static int AutostartDropMode = AUTOSTART_DROP_MODE_RUN
static const char *const AutostartRunCommandsAvailable []
static char * autostart_default_diskimage = NULL
Keep track of the generated 'factory' value for the default disk.
static const char * AutostartRunCommand = NULL
static resource_string_t resources_string []
string resources used by autostart
static resource_int_t resources_int_basicload []
integer resources used by autostart
static resource_int_t resources_int_basicload_pet []
static resource_int_t resources_int []
static const cmdline_option_t cmdline_options_basicload []
static const cmdline_option_t cmdline_options_basicload_pet []
static const cmdline_option_t cmdline_options []
Macro Definition Documentation
AUTOSTART_CHECK_ANY_COLUMN
#define AUTOSTART_CHECK_ANY_COLUMN 0
AUTOSTART_CHECK_FIRST_COLUMN
#define AUTOSTART_CHECK_FIRST_COLUMN 1
AUTOSTART_DISK_IMAGE
#define AUTOSTART_DISK_IMAGE 0
AUTOSTART_NOWAIT_BLINK
#define AUTOSTART_NOWAIT_BLINK 1
AUTOSTART_PRG_DISK
#define AUTOSTART_PRG_DISK 2
AUTOSTART_PRG_INJECT
#define AUTOSTART_PRG_INJECT 3
AUTOSTART_PRG_VFS
#define AUTOSTART_PRG_VFS 1
AUTOSTART_WAIT_BLINK
#define AUTOSTART_WAIT_BLINK 0
DBG
#define DBG (_x_)
DBGWAIT
#define DBGWAIT (_x_)
Enumeration Type Documentation
anonymous enum
anonymous enum
Current state of the autostart routine.
Enumerator
AUTOSTART_NONE
AUTOSTART_ERROR
AUTOSTART_HASTAPE
AUTOSTART_PRESSPLAYONTAPE
AUTOSTART_LOADINGTAPE
AUTOSTART_HASDISK
AUTOSTART_LOADINGDISK
AUTOSTART_HASSNAPSHOT
AUTOSTART_WAITLOADREADY
AUTOSTART_WAITLOADING
AUTOSTART_WAITSEARCHINGFOR
AUTOSTART_INJECT
AUTOSTART_DONE
CHECKYESNO
enum CHECKYESNO
Enumerator
YES
NO
NOT_YET
Function Documentation
advance_hasdisk()
static void advance_hasdisk (int unit, int drive) static
Todo:
FIXME: before, the code selected one of three different code pathes, depending on the state of traps and warpmode. it seems a bit strange that this is needed, and also that simple doing the same will work better too. i am leaving the following here for experimentation while completely debugging the autostart madness
Referenced by autostart_advance().
advance_hassnapshot()
static void advance_hassnapshot (void) static
Referenced by autostart_advance().
advance_hastape()
static void advance_hastape (void) static
Referenced by autostart_advance().
advance_inject()
static void advance_inject (void) static
After a reset a PRG file has to be injected into RAM.
Referenced by autostart_advance().
advance_loadingtape()
static void advance_loadingtape (void) static
Referenced by autostart_advance().
advance_pressplayontape()
static void advance_pressplayontape (void) static
Referenced by autostart_advance().
advance_waitloading()
static void advance_waitloading (void) static
Referenced by autostart_advance().
advance_waitloadready()
static void advance_waitloadready (void) static
Referenced by autostart_advance().
advance_waitsearchingfor()
static void advance_waitsearchingfor (void) static
Referenced by autostart_advance().
autostart_advance()
void autostart_advance (void)
Referenced by maincpu_mainloop().
autostart_autodetect()
int autostart_autodetect (const char * file_name, const char * program_name, unsigned int program_number, unsigned int runmode)
void autostart_reinit(int default_seconds, int handle_drive_true_emulation);
Referenced by autostart_autodetect_opt_prgname(), do_autostart(), and on_drag_data_received().
autostart_autodetect_opt_prgname()
int autostart_autodetect_opt_prgname (const char * file_prog_name, unsigned int alt_prg_number, unsigned int runmode)
Referenced by initcmdline_check_attach(), and mon_autostart().
autostart_cmdline_options_init()
int autostart_cmdline_options_init (void)
initialize the command-line options
Returns
0 on success, else -1.
Remarks
Registers the command-line options
Referenced by machine_cmdline_options_init().
autostart_disable()
void autostart_disable (void)
Referenced by advance_hasdisk(), advance_hassnapshot(), advance_hastape(), advance_inject(), advance_loadingtape(), advance_pressplayontape(), advance_waitloading(), advance_waitloadready(), and advance_waitsearchingfor().
autostart_disk()
int autostart_disk (int unit, int drive, const char * file_name, const char * program_name, unsigned int program_number, unsigned int runmode)
Autostart disk image ‘file_name’.
Referenced by autostart_autodetect(), disk_dir_autostart_callback(), and do_autostart().
autostart_disk_cook_name()
static void autostart_disk_cook_name (char ** name) static
Cope with 0xa0 padded file names.
Referenced by autostart_disk().
autostart_done()
static void autostart_done (void) static
This is called if all steps of an autostart operation were passed successfully.
Referenced by advance_hasdisk(), advance_hassnapshot(), advance_loadingtape(), advance_waitloadready(), advance_waitsearchingfor(), check_rom_area(), and disk_eof_callback().
autostart_finish()
static void autostart_finish (void) static
this is called after successful loading
Referenced by advance_hasdisk(), advance_loadingtape(), advance_waitloadready(), advance_waitsearchingfor(), and disk_eof_callback().
autostart_in_progress()
int autostart_in_progress (void)
Todo:
FIXME: dead code?
Referenced by default_tape_header_type(), event_playback_start(), and event_record_start().
autostart_init()
int autostart_init (int default_seconds, int handle_drive_true_emulation)
Initialize autostart.
Todo:
FIXME: cbm2 and pet pass 0,0 into this function before loading kernal ... why is this?
default_seconds : initial delay before checking for READY handle_tde : if zero, "handle tde at autostart" will never be done
Referenced by machine_specific_init().
autostart_prg()
int autostart_prg (const char * file_name, unsigned int runmode)
Todo:
FIXME: if we want to be able to autostart prg files from different devices than device nr 8, either pass the device nr here, or use some resource for this
Referenced by autostart_autodetect(), and do_smart_attach().
autostart_reinit()
static void autostart_reinit (int default_seconds, int handle_tde) static
Reset autostart.
Todo:
FIXME: cbm2 and pet pass 0,0 into this function before loading kernal ... why is this?
default_seconds : initial delay before checking for READY handle_tde : if zero, "handle tde at autostart" will never be done
Todo:
FIXME: pet and cbm2 need this for some reason, see comment above
Referenced by autostart_init().
autostart_reset()
void autostart_reset (void)
Disable autostart on reset.
int autostart_device(int unit);
Todo:
FIXME: pass device nr into this function
Referenced by machine_reset().
autostart_resources_init()
int autostart_resources_init (void)
initialize the resources
Returns
0 on success, else -1.
Remarks
Registers the integer resources
Referenced by machine_resources_init().
autostart_resources_shutdown()
void autostart_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
autostart_set_initial_tap_offset()
int autostart_set_initial_tap_offset (unsigned long offset)
autostart_shutdown()
void autostart_shutdown (void)
Referenced by machine_shutdown().
autostart_snapshot()
int autostart_snapshot (const char * file_name, const char * program_name)
Autostart snapshot file ‘file_name’.
Referenced by autostart_autodetect(), and do_smart_attach().
autostart_tape()
int autostart_tape (const char * file_name, const char * program_name, unsigned int program_number, unsigned int runmode, unsigned int tapeport)
Autostart tape image ‘file_name’.
Todo:
FIXME: this should perhaps be handled differently for tape
Referenced by autostart_autodetect(), do_autostart(), and tape_dir_autostart_callback().
autostart_tapecart()
int autostart_tapecart (const char * file_name, void * unused)
Autostart tapecart image file_name.
Parameters
[in] file_name path to tapecart image
[in] unused unused
Returns
0 on success, -1 on failure
Todo:
FIXME: make sure init_drive_emulation_state() does the right thing in this function (perhaps we need to handle all drives?)
Todo:
FIXME: this likely needs to be handled differently for tapecart
Todo:
FIXME: may be 2 on xpet
Referenced by autostart_autodetect().
autostart_trigger_monitor()
void autostart_trigger_monitor (int enable)
Control if the monitor will be triggered after an autostart.
Referenced by mon_autostart().
check()
static CHECKYESNO check (const char * s, unsigned int blink_mode) static
Referenced by advance_hasdisk(), advance_hassnapshot(), advance_hastape(), advance_loadingtape(), advance_waitloading(), advance_waitloadready(), advance_waitsearchingfor(), cart_image_widget_append_check(), carthelpers_create_enable_check_button(), cbm2_ram_mapping_widget_create(), create_64kb_widget(), create_cart_reset_widget(), create_controls_layout(), create_drive_virtual_device_widget(), create_dww_check_button(), create_iec_check_button(), create_mmc64_enable_widget(), create_pause_checkbox(), create_readonly_check_button(), create_real_device7_check_button(), create_rtc_check_button(), create_superpet_enable_widget(), create_virtual_device_check_button(), create_warp_checkbox(), drive_ram_widget_create(), drive_ram_widget_update(), drive_sound_widget_create(), handle_voc_file(), layout_add_bbrtc_widget(), layout_add_ps2mouse_widget(), layout_add_smartmouse_rtc_widget(), on_common_config_changed(), on_enable_toggled(), on_hide_vdc_toggled(), on_logfile_entry_changed(), on_real_device7_toggled(), on_stdout_check_toggled(), pet_diagnosticpin_widget_create(), settings_finalexpansion_widget_create(), settings_pethre_widget_create(), settings_plus4_digiblaster_widget_create(), settings_rom_widget_create(), settings_supersnapshotv5_widget_create(), settings_ultimem_widget_create(), settings_vicflashplugin_widget_create(), settings_vicieee488_widget_create(), userport_device_check_button_new(), vdrive_haswildcard(), vic20_ram_blocks_widget_create(), and vice_gtk3_resource_check_button_new().
check2()
static CHECKYESNO check2 (const char * s, unsigned int blink_mode, int lineoffset, int checkcursor) static
Referenced by advance_pressplayontape(), advance_waitloading(), advance_waitsearchingfor(), and check().
check_rom_area()
static int check_rom_area (void) static
returns 0 if we left ROM area and should disable autostart
Referenced by advance_hasdisk(), advance_loadingtape(), advance_waitloading(), advance_waitloadready(), and advance_waitsearchingfor().
cmdline_set_autostart_drop_mode()
static int cmdline_set_autostart_drop_mode (const char * value, void * unused) static
Command line resource setter for "AutostartDropMode" resource.
Parameters
[in] value new mode (0, 1, 2 or "attach", "load", "run")
[in] unused unused
Returns
0 on success, -1 on error
cmdline_set_tap_offset()
static int cmdline_set_tap_offset (const char * arg, void * param) static
deallocate_program_name()
static void deallocate_program_name (void) static
Deallocate program name if we have one.
Referenced by advance_hasdisk(), advance_hastape(), autostart_disable(), autostart_disk(), autostart_reset(), autostart_shutdown(), autostart_snapshot(), autostart_tape(), and reboot_for_autostart().
disable_warp_if_was_requested()
static void disable_warp_if_was_requested (void) static
Referenced by advance_hasdisk(), advance_hastape(), advance_inject(), advance_loadingtape(), advance_pressplayontape(), advance_waitloading(), advance_waitloadready(), advance_waitsearchingfor(), check_rom_area(), and disk_eof_callback().
disk_attention_callback()
static void disk_attention_callback (void) static
Referenced by advance_hasdisk().
disk_eof_callback()
static void disk_eof_callback (void) static
Todo:
FIXME: shouldnt this loop over all drives?
Todo:
FIXME: what exactly is this stuff supposed to do?
Referenced by autostart_reset(), and disk_attention_callback().
enable_warp_if_requested()
static void enable_warp_if_requested (void) static
Referenced by reboot_for_autostart().
get_device_traps_state()
static int get_device_traps_state (int unit) static
Referenced by advance_hasdisk(), autostart_tape(), init_drive_emulation_state(), restore_drive_emulation_state(), setup_for_disk(), setup_for_disk_ready(), and setup_for_prg_vfs().
get_iec_device_state()
static int get_iec_device_state (int unit) static
Referenced by advance_hasdisk(), init_drive_emulation_state(), restore_drive_emulation_state(), setup_for_disk(), and setup_for_disk_ready().
get_true_drive_emulation_state()
static int get_true_drive_emulation_state (int unit) static
Referenced by advance_hasdisk(), autostart_disk(), autostart_prg(), init_drive_emulation_state(), restore_drive_emulation_state(), setup_for_disk(), setup_for_disk_ready(), and setup_for_prg_vfs().
init_drive_emulation_state()
static void init_drive_emulation_state (int unit, int drive) static
Todo:
FIXME: perhaps we should not call this when autostarting from tape
Referenced by autostart_autodetect(), autostart_disk(), autostart_prg(), autostart_tape(), and autostart_tapecart().
load_snapshot_trap()
static void load_snapshot_trap (uint16_t unused_addr, void * unused_data) static
Referenced by advance_hassnapshot().
reboot_for_autostart()
static void reboot_for_autostart (const char * program_name, unsigned int mode, unsigned int runmode) static
Clean memory and reboot for autostart.
Referenced by autostart_disk(), autostart_prg(), autostart_snapshot(), autostart_tape(), and autostart_tapecart().
restore_drive_emulation_state()
static void restore_drive_emulation_state (int unit, int drive) static
Todo:
FIXME: perhaps we should not call this when autostarting from tape
Referenced by autostart_advance(), and autostart_done().
set_autostart_basic_load()
static int set_autostart_basic_load (int val, void * param) static
set if autostart should use LOAD ... ,1
set_autostart_delay()
static int set_autostart_delay (int val, void * param) static
set initial autostart delay. 0 means default.
set_autostart_delayrandom()
static int set_autostart_delayrandom (int val, void * param) static
set initial autostart random delay. 0 means off, 1 means on.
set_autostart_drop_mode()
static int set_autostart_drop_mode (int mode, void * unused) static
Resource setter for "AutostartDropMode" resource.
Parameters
[in] mode new mode
[in] unused unused
Returns
0 on success, -1 on error
set_autostart_handle_tde()
static int set_autostart_handle_tde (int val, void * param) static
set if autostart should handle TDE or not
Parameters
val if 0, autostart does not handle TDE even if the machine says it can handle it.
param unused
Returns
0 on success. else -1.
set_autostart_prg_disk_image()
static int set_autostart_prg_disk_image (const char * val, void * param) static
set disk image name of autostart prg mode
set_autostart_prg_mode()
static int set_autostart_prg_mode (int val, void * param) static
set autostart prg mode
set_autostart_run_with_colon()
static int set_autostart_run_with_colon (int val, void * param) static
set if autostart should execute with a colon or not
Parameters
val if 0, the "RUN" command at the end of autostart is executed without a colon; else, it will be executed with a colon.
param unused
Returns
0 on success. else -1.
set_autostart_tape_basic_load()
static int set_autostart_tape_basic_load (int val, void * param) static
set if autostart from tape should use LOAD ... ,1
set_autostart_warp()
static int set_autostart_warp (int val, void * param) static
set if autostart should enable warp mode
set_device_traps_state()
static void set_device_traps_state (int unit, int on) static
Referenced by autostart_tape(), restore_drive_emulation_state(), setup_for_disk(), setup_for_disk_ready(), and setup_for_prg_vfs().
set_handle_true_drive_emulation_state()
static void set_handle_true_drive_emulation_state (void) static
Referenced by autostart_reinit(), and set_autostart_handle_tde().
set_iec_device_state()
static void set_iec_device_state (int on, int unit) static
Referenced by restore_drive_emulation_state().
set_tapeport_device()
static void set_tapeport_device (int datasette, int tapecart) static
Referenced by autostart_autodetect().
set_true_drive_emulation_mode()
static void set_true_drive_emulation_mode (int on, int unit) static
Referenced by autostart_disk(), autostart_prg(), restore_drive_emulation_state(), setup_for_disk(), setup_for_disk_ready(), and setup_for_prg_vfs().
set_warp_mode()
static void set_warp_mode (int on) static
Referenced by disable_warp_if_was_requested(), enable_warp_if_requested(), and restore_drive_emulation_state().
setup_for_disk()
static void setup_for_disk (int unit, int drive) static
Referenced by autostart_disk(), and autostart_prg().
setup_for_disk_ready()
static void setup_for_disk_ready (int unit, int drive) static
Referenced by advance_hasdisk().
setup_for_prg_vfs()
static void setup_for_prg_vfs (int unit) static
Referenced by autostart_prg().
Variable Documentation
autostart_basic_load
int autostart_basic_load = 0
Referenced by advance_hasdisk(), autostart_prg_perform_injection(), and set_autostart_basic_load().
autostart_default_diskimage
char* autostart_default_diskimage = NULL static
Keep track of the generated 'factory' value for the default disk.
Factory values are const, so we need a little extra code to avoid free'ing a const.
Referenced by autostart_resources_init(), and autostart_resources_shutdown().
autostart_disk_drive
int autostart_disk_drive = 0 static
Referenced by autostart_advance(), autostart_done(), disk_eof_callback(), restore_drive_emulation_state(), and setup_for_disk().
autostart_disk_unit
int autostart_disk_unit = 8 static
Todo:
FIXME: only used by datasette.c, does it really have to be global?
Referenced by autostart_advance(), autostart_done(), disk_eof_callback(), restore_drive_emulation_state(), and setup_for_disk().
autostart_enabled
int autostart_enabled = 0 static
Flag: autostart is initialized.
Referenced by autostart_advance(), autostart_autodetect(), autostart_disable(), autostart_disk(), autostart_reinit(), autostart_reset(), autostart_snapshot(), autostart_tape(), and reboot_for_autostart().
autostart_ignore_reset
int autostart_ignore_reset = 0
Referenced by autostart_reset(), and reboot_for_autostart().
autostart_initial_delay_cycles
CLOCK autostart_initial_delay_cycles static
Minimum number of cycles before we feed BASIC with commands.
Referenced by autostart_advance(), and reboot_for_autostart().
autostart_log
log_t autostart_log = ((log_t)-1)
Log descriptor.
Referenced by advance_hasdisk(), advance_hassnapshot(), advance_hastape(), advance_inject(), advance_waitloading(), advance_waitloadready(), advance_waitsearchingfor(), autostart_advance(), autostart_autodetect(), autostart_disable(), autostart_disk(), autostart_done(), autostart_finish(), autostart_init(), autostart_prg(), autostart_prg_perform_injection(), autostart_prg_with_virtual_fs(), autostart_reset(), autostart_snapshot(), autostart_tape(), check_rom_area(), disk_eof_callback(), load_snapshot_trap(), reboot_for_autostart(), restore_drive_emulation_state(), set_device_traps_state(), set_iec_device_state(), set_true_drive_emulation_mode(), and set_warp_mode().
autostart_program_name
char* autostart_program_name = NULL static
PETSCII name of the program to load.
NULL if default
Referenced by advance_hasdisk(), advance_hastape(), deallocate_program_name(), load_snapshot_trap(), and reboot_for_autostart().
autostart_run_mode
unsigned int autostart_run_mode static
Flag: Autostart the file or just load it?
Referenced by autostart_finish(), and reboot_for_autostart().
autostart_tape_basic_load
int autostart_tape_basic_load = 1
Referenced by default_tape_header_type(), and set_autostart_tape_basic_load().
autostart_tape_unit
int autostart_tape_unit = 1 static
Referenced by advance_hastape(), advance_pressplayontape(), autostart_tape(), autostart_tapecart(), and restore_drive_emulation_state().
autostart_type
int autostart_type = -1 static
Referenced by advance_hasdisk(), autostart_disk(), autostart_prg(), and restore_drive_emulation_state().
autostart_wait_for_reset
int autostart_wait_for_reset static
Flag: maincpu_clk isn't resetted yet.
Referenced by autostart_advance(), and reboot_for_autostart().
AutostartDelay
int AutostartDelay = 0 static
Referenced by reboot_for_autostart(), and set_autostart_delay().
AutostartDelayDefaultSeconds
int AutostartDelayDefaultSeconds = 0 static
Referenced by autostart_reinit(), and reboot_for_autostart().
AutostartDelayRandom
int AutostartDelayRandom = 0 static
Referenced by autostart_finish(), and set_autostart_delayrandom().
AutostartDropMode
int AutostartDropMode = AUTOSTART_DROP_MODE_RUN static
Referenced by cmdline_set_autostart_drop_mode(), and set_autostart_drop_mode().
AutostartHandleTrueDriveEmulation
int AutostartHandleTrueDriveEmulation = 0 static
Referenced by set_autostart_handle_tde(), and set_handle_true_drive_emulation_state().
enum { ... } autostartmode
Current state of the autostart routine.
Referenced by advance_hasdisk(), advance_hastape(), advance_inject(), advance_pressplayontape(), advance_waitloading(), advance_waitsearchingfor(), autostart_advance(), autostart_disable(), autostart_disk(), autostart_done(), autostart_in_progress(), autostart_reset(), autostart_snapshot(), autostart_tape(), check_rom_area(), disk_eof_callback(), and reboot_for_autostart().
AutostartPrgDiskImage
char* AutostartPrgDiskImage = NULL static
Referenced by autostart_prg(), autostart_resources_shutdown(), and set_autostart_prg_disk_image().
AutostartPrgMode
int AutostartPrgMode = 0 static
Referenced by autostart_prg(), and set_autostart_prg_mode().
AutostartRunCommand
const char* AutostartRunCommand = NULL static
Referenced by autostart_finish(), and set_autostart_run_with_colon().
AutostartRunCommandsAvailable
const char* const AutostartRunCommandsAvailable[] static
Initial value:
= {
    "RUN\r", "RUN:\r"
}
Referenced by set_autostart_run_with_colon().
AutostartRunWithColon
int AutostartRunWithColon = 0 static
Referenced by set_autostart_run_with_colon().
AutostartWarp
int AutostartWarp = 0 static
Referenced by advance_hasdisk(), disable_warp_if_was_requested(), enable_warp_if_requested(), and set_autostart_warp().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-autostartwithcolon", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartRunWithColon", (resource_value_t)1,
      NULL, "On autostart, use the 'RUN' command with a colon, i.e., 'RUN:'" },
    { "+autostartwithcolon", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartRunWithColon", (resource_value_t)0,
      NULL, "On autostart, do not use the 'RUN' command with a colon; i.e., 'RUN'" },
    { "-autostart-handle-tde", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartHandleTrueDriveEmulation", (resource_value_t)1,
      NULL, "Handle True Drive Emulation on autostart" },
    { "+autostart-handle-tde", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartHandleTrueDriveEmulation", (resource_value_t)0,
      NULL, "Do not handle True Drive Emulation on autostart" },
    { "-autostart-warp", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartWarp", (resource_value_t)1,
      NULL, "Enable warp mode during autostart" },
    { "+autostart-warp", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartWarp", (resource_value_t)0,
      NULL, "Disable warp mode during autostart" },
    { "-autostartprgmode", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "AutostartPrgMode", NULL,
      "<Mode>", "Set autostart mode for PRG files (0: VirtualFS, 1: Inject, 2: Disk image)" },
    { "-autostartprgdiskimage", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "AutostartPrgDiskImage", NULL,
      "<Name>", "Set disk image for autostart of PRG files" },
    { "-autostart-delay", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "AutostartDelay", NULL,
      "<seconds>", "Set initial autostart delay (0: use default)" },
    { "-autostart-delay-random", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartDelayRandom", (resource_value_t)1,
      NULL, "Enable random initial autostart delay." },
    { "+autostart-delay-random", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartDelayRandom", (resource_value_t)0,
      NULL, "Disable random initial autostart delay." },
    { "-autostarttapoffset", CALL_FUNCTION,  (1 << 0) ,
      &cmdline_set_tap_offset, NULL, NULL, NULL,
      "<value>", "Set initial offset in .tap file" },
    { "-autostart-drop-mode", CALL_FUNCTION,  (1 << 0) ,
      &cmdline_set_autostart_drop_mode, NULL, NULL, NULL, "<Mode>",
      "Set autostart drop mode (0/attach: attach only, 1/load: attach and load, "
      "2/run: attach, load and run)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by autostart_cmdline_options_init().
cmdline_options_basicload
const cmdline_option_t cmdline_options_basicload[] static
Initial value:
=
{
    { "-basicload", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartBasicLoad", (resource_value_t)1,
      NULL, "On autostart from disk, load to BASIC start (without ',1')" },
    { "+basicload", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartBasicLoad", (resource_value_t)0,
      NULL, "On autostart from disk, load with ',1'" },
    { "-tapebasicload", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartTapeBasicLoad", (resource_value_t)1,
      NULL, "On autostart from tape, load to BASIC start (without ',1')" },
    { "+tapebasicload", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartTapeBasicLoad", (resource_value_t)0,
      NULL, "On autostart from tape, load with ',1'" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by autostart_cmdline_options_init().
cmdline_options_basicload_pet
const cmdline_option_t cmdline_options_basicload_pet[] static
Initial value:
=
{
    { "-basicload", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartBasicLoad", (resource_value_t)1,
      NULL, "On autostart from disk, load to BASIC start (without ',1')" },
    { "+basicload", SET_RESOURCE,  0 ,
      NULL, NULL, "AutostartBasicLoad", (resource_value_t)0,
      NULL, "On autostart from disk, load with ',1'" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by autostart_cmdline_options_init().
entered_rom
int entered_rom = 0 static
Flag: load stage after LOADING enters ROM area.
Referenced by advance_hastape(), advance_waitloading(), advance_waitsearchingfor(), and check_rom_area().
handle_drive_true_emulation_by_machine
int handle_drive_true_emulation_by_machine static
Flag: Does the machine want us to switch true drive emulation on/off during autostart?
Referenced by autostart_reinit(), and set_handle_true_drive_emulation_state().
handle_drive_true_emulation_overridden
int handle_drive_true_emulation_overridden static
Referenced by disk_eof_callback(), set_handle_true_drive_emulation_state(), setup_for_disk(), setup_for_disk_ready(), and setup_for_prg_vfs().
orig_device_traps_state
int orig_device_traps_state = -1 static
Flag: were device traps turned on when we started booting the disk image?
Referenced by advance_hasdisk(), init_drive_emulation_state(), restore_drive_emulation_state(), setup_for_disk(), setup_for_disk_ready(), and setup_for_prg_vfs().
orig_drive_true_emulation_state
int orig_drive_true_emulation_state = -1 static
Flag: was true drive emulation turned on when we started booting the disk image?
Referenced by advance_hasdisk(), autostart_disk(), autostart_prg(), disk_eof_callback(), init_drive_emulation_state(), restore_drive_emulation_state(), setup_for_disk(), setup_for_disk_ready(), and setup_for_prg_vfs().
orig_FileSystemDevice8
int orig_FileSystemDevice8 = -1 static
Referenced by init_drive_emulation_state(), and restore_drive_emulation_state().
orig_FSDevice8ConvertP00
int orig_FSDevice8ConvertP00 = -1 static
Referenced by init_drive_emulation_state(), and restore_drive_emulation_state().
orig_FSDeviceLongNames
int orig_FSDeviceLongNames = -1 static
Referenced by init_drive_emulation_state(), and restore_drive_emulation_state().
orig_iec_device_state
int orig_iec_device_state = -1 static
Flag: was iec device turned on when we started booting the disk image?
Referenced by advance_hasdisk(), init_drive_emulation_state(), restore_drive_emulation_state(), and setup_for_disk_ready().
orig_warp_mode
int orig_warp_mode = -1 static
Flag: warp mode state before booting.
Referenced by disable_warp_if_was_requested(), enable_warp_if_requested(), init_drive_emulation_state(), and restore_drive_emulation_state().
resources_int
resource_int_t resources_int[] static
Initial value:
= {
    { "AutostartRunWithColon", 0, RES_EVENT_NO, (resource_value_t)1,
      &AutostartRunWithColon, set_autostart_run_with_colon, NULL },
    { "AutostartHandleTrueDriveEmulation", 0, RES_EVENT_NO, (resource_value_t)0,
      &AutostartHandleTrueDriveEmulation, set_autostart_handle_tde, NULL },
    { "AutostartWarp", 1, RES_EVENT_NO, (resource_value_t)0,
      &AutostartWarp, set_autostart_warp, NULL },
    { "AutostartPrgMode",   2  , RES_EVENT_NO, (resource_value_t)0,
      &AutostartPrgMode, set_autostart_prg_mode, NULL },
    { "AutostartDelay", 0, RES_EVENT_NO, (resource_value_t)0,
      &AutostartDelay, set_autostart_delay, NULL },
    { "AutostartDelayRandom", 1, RES_EVENT_NO, (resource_value_t)0,
      &AutostartDelayRandom, set_autostart_delayrandom, NULL },
    { "AutostartDropMode",  AUTOSTART_DROP_MODE_RUN, RES_EVENT_NO, (resource_value_t)0,
      &AutostartDropMode, set_autostart_drop_mode, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by autostart_resources_init().
resources_int_basicload
resource_int_t resources_int_basicload[] static
Initial value:
= {
    { "AutostartBasicLoad", 0, RES_EVENT_NO, (resource_value_t)0,
      &autostart_basic_load, set_autostart_basic_load, NULL },
    { "AutostartTapeBasicLoad", 0, RES_EVENT_NO, (resource_value_t)1,
      &autostart_tape_basic_load, set_autostart_tape_basic_load, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
integer resources used by autostart
Referenced by autostart_resources_init().
resources_int_basicload_pet
resource_int_t resources_int_basicload_pet[] static
Initial value:
= {
    { "AutostartBasicLoad", 1, RES_EVENT_NO, (resource_value_t)0,
      &autostart_basic_load, set_autostart_basic_load, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by autostart_resources_init().
resources_string
resource_string_t resources_string[] static
Initial value:
= {
    { "AutostartPrgDiskImage", NULL, RES_EVENT_NO, NULL,
      &AutostartPrgDiskImage, set_autostart_prg_disk_image, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
string resources used by autostart
Referenced by autostart_resources_init().
tap_initial_raw_offset
size_t tap_initial_raw_offset = 0 static
Referenced by autostart_set_initial_tap_offset(), autostart_tape(), and cmdline_set_tap_offset().
trigger_monitor
int trigger_monitor = 0 static
Flag: trap monitor after done.
Referenced by autostart_disable(), autostart_reset(), autostart_trigger_monitor(), and load_snapshot_trap().