x128: alarm.h File Reference
alarm.h File Reference
#include "types.h"
Data Structures
struct alarm_s
An alarm.
struct pending_alarms_s
struct alarm_context_s
An alarm context.
Macros
#define ALARM_CONTEXT_MAX_PENDING_ALARMS 0x100
Typedefs
typedef void(* alarm_callback_t) (CLOCK offset, void *data)
typedef struct alarm_s alarm_t
typedef struct pending_alarms_s pending_alarms_t
typedef struct alarm_context_s alarm_context_t
Functions
alarm_context_t * alarm_context_new (const char *name)
void alarm_context_init (alarm_context_t *context, const char *name)
void alarm_context_destroy (alarm_context_t *context)
void alarm_context_time_warp (alarm_context_t *context, CLOCK warp_amount, int warp_direction)
alarm_t * alarm_new (alarm_context_t *context, const char *name, alarm_callback_t callback, void *data)
void alarm_destroy (alarm_t *alarm)
void alarm_unset (alarm_t *alarm)
void alarm_log_too_many_alarms (void)
static CLOCK alarm_context_next_pending_clk (alarm_context_t *context)
Inline functions.
static void alarm_context_update_next_pending (alarm_context_t *context)
static void alarm_context_dispatch (alarm_context_t *context, CLOCK cpu_clk)
static void alarm_set (alarm_t *alarm, CLOCK cpu_clk)
Macro Definition Documentation
ALARM_CONTEXT_MAX_PENDING_ALARMS
#define ALARM_CONTEXT_MAX_PENDING_ALARMS 0x100
Typedef Documentation
alarm_callback_t
typedef void(* alarm_callback_t) (CLOCK offset, void *data)
alarm_context_t
typedef struct alarm_context_s alarm_context_t
alarm_t
typedef struct alarm_s alarm_t
pending_alarms_t
typedef struct pending_alarms_s pending_alarms_t
Function Documentation
alarm_context_destroy()
void alarm_context_destroy (alarm_context_t * context)
Referenced by drivecpu65c02_shutdown(), drivecpu_shutdown(), and machine_maincpu_shutdown().
alarm_context_dispatch()
static void alarm_context_dispatch (alarm_context_t * context, CLOCK cpu_clk) inline static
Referenced by if(), interrupt_delay(), maincpu_steal_cycles(), run_pending_alarms(), while(), and z80_maincpu_loop().
alarm_context_init()
void alarm_context_init (alarm_context_t * context, const char * name)
Referenced by alarm_context_new().
alarm_context_new()
alarm_context_t * alarm_context_new (const char * name)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), and machine_early_init().
alarm_context_next_pending_clk()
static CLOCK alarm_context_next_pending_clk (alarm_context_t * context) inline static
Inline functions.
Referenced by drive_trap_handler(), if(), interrupt_delay(), maincpu_steal_cycles(), run_pending_alarms(), and z80_maincpu_loop().
alarm_context_time_warp()
void alarm_context_time_warp (alarm_context_t * context, CLOCK warp_amount, int warp_direction)
alarm_context_update_next_pending()
static void alarm_context_update_next_pending (alarm_context_t * context) inline static
Referenced by alarm_set(), alarm_unset(), and keyboard_alarm_handler().
alarm_destroy()
void alarm_destroy (alarm_t * alarm)
Referenced by alarm_context_destroy(), ata_shutdown(), and OPLDestroy().
alarm_log_too_many_alarms()
void alarm_log_too_many_alarms (void)
Referenced by alarm_set().
alarm_new()
alarm_t * alarm_new (alarm_context_t * context, const char * name, alarm_callback_t callback, void * data)
Referenced by ata_init(), c64dtv_ps2mouse_alarm_init(), ciacore_init(), cmdhd_setup_context(), event_init(), fdc_init(), flash040core_init(), glue1551_init(), kbdbuf_init(), keyboard_init(), myacia_init(), OPLCreate(), pc8477d_init(), riotcore_init(), rsuser_init(), tapecart_enable(), vdc_init(), viacore_init(), vicii_fetch_init(), vicii_init(), and vicii_irq_init().
alarm_set()
static void alarm_set (alarm_t * alarm, CLOCK cpu_clk) inline static
Referenced by acia_set_handshake_lines(), alarm_set_if_not_pending(), ata_change_power_mode(), ata_snapshot_read_module(), ata_standby_alarm_handler(), c64dtv_ps2mouse_alarm_handler(), cia_ifr_current(), ciacore_async_interrupt(), ciacore_idle(), ciacore_intsdr(), ciacore_inttod(), ciacore_reset(), ciacore_snapshot_read_module(), ciat_set_alarm(), cmdhd_reset(), d015_store(), erase_alarm_handler(), event_alarm_handler(), event_record_reset_milestone_trap(), event_record_start_trap(), event_reset_ack(), fdc_reset(), fdc_snapshot_read_module(), flash040core_snapshot_read_module(), flash040core_store_internal(), fmopl_alarm_A(), fmopl_alarm_B(), glue1551_reset(), glue1551_timer(), handle_check_sprite_dma(), handle_fetch_matrix(), handle_fetch_sprite(), int_acia_rx(), int_acia_tx(), int_fdc(), int_rsuser(), kbd_limit_pointers(), kbd_retrigger_alarm(), kbdbuf_flush(), keyboard_restore_pressed(), keyboard_restore_released(), myacia_snapshot_read_module(), myacia_store(), next_alarm_set(), OPLWriteReg(), pc8477_execute(), ps2mouse_store(), restore_alarm_triggered(), riotcore_snapshot_read_module(), riotcore_store(), rsuser_setup(), schedule_sdr_alarm(), schedule_t2_zero_alarm(), seek_alarm_handler(), seek_sector(), set_acia_ticks(), setup_shifting(), store_sprite_y_position(), tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), tapecart_set_mode(), tapecart_store_motor(), tapecart_store_sense(), tapecart_store_write(), vdc_set_next_alarm(), viacore_phi2_sr_alarm(), viacore_snapshot_read_module(), viacore_store(), viacore_t1_zero_alarm(), viacore_t2_underflow_alarm(), viacore_t2_zero_alarm(), vicii_irq_next_frame(), vicii_irq_set_raster_line(), vicii_raster_draw_alarm_handler(), vicii_reset(), and vicii_snapshot_read_module().
alarm_unset()
void alarm_unset (alarm_t * alarm)
Referenced by acia_set_handshake_lines(), alarm_destroy(), ata_change_power_mode(), ata_head_alarm_handler(), ata_snapshot_read_module(), ata_spindle_alarm_handler(), ata_standby_alarm_handler(), c64dtv_ps2mouse_alarm_handler(), ciacore_disable(), ciacore_intsdr(), ciacore_reset(), ciacore_set_sdr(), ciacore_snapshot_read_module(), ciat_ack_alarm(), ciat_reset(), ciat_set_alarm(), cmdhd_snapshot_read_module(), cmdmode_receive_command(), erase_alarm_handler(), event_alarm_handler(), event_playback_stop(), event_record_stop(), fdc_reset(), flash040core_reset(), flash040core_store_internal(), fmopl_alarm_A(), fmopl_alarm_B(), glue1551_reset(), int_acia_rx(), int_acia_tx(), kbd_retrigger_alarm(), kbdbuf_flush_alarm_triggered(), keyboard_alarm_handler(), myacia_reset(), myacia_snapshot_read_module(), myacia_store(), OPLDestroy(), OPLResetChip(), OPLWriteReg(), reset_alarm_handler(), restore_alarm_triggered(), riotcore_disable(), riotcore_int_riot(), riotcore_reset(), riotcore_snapshot_read_module(), riotcore_store(), rsuser_reset(), rsuser_write_ctrl(), schedule_t2_zero_alarm(), seek_alarm_handler(), tapecart_enable(), tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), tapecart_set_mode(), userport_rs232_enable(), viacore_disable(), viacore_reset(), viacore_snapshot_read_module(), viacore_store(), viacore_t1_zero_alarm(), viacore_t2_shift_alarm(), viacore_t2_underflow_alarm(), viacore_t2_zero_alarm(), vicii_irq_set_raster_line(), vicii_snapshot_prepare(), and vicii_snapshot_read_module().