vsid: gfxoutputdrv/koaladrv.c File Reference
koaladrv.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "archdep.h"
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "mem.h"
#include "gfxoutput.h"
#include "nativedrv.h"
#include "palette.h"
#include "resources.h"
#include "screenshot.h"
#include "types.h"
#include "uiapi.h"
#include "util.h"
#include "vsync.h"
Macros
#define KOALA_SCREEN_PIXEL_WIDTH 320
#define KOALA_SCREEN_PIXEL_HEIGHT 200
#define KOALA_SCREEN_BYTE_WIDTH KOALA_SCREEN_PIXEL_WIDTH / 8
#define KOALA_SCREEN_BYTE_HEIGHT KOALA_SCREEN_PIXEL_HEIGHT / 8
#define BITMAP_OFFSET 2
define offsets in the koala file
#define SCREENRAM_OFFSET 8002
#define VIDEORAM_OFFSET 9002
#define BGCOLOR_OFFSET 10002
#define KOALA_SIZE 10003
Functions
static int set_oversize_handling (int val, void *param)
static int set_undersize_handling (int val, void *param)
static int set_ted_lum_handling (int val, void *param)
static int koaladrv_resources_init (void)
static int koaladrv_cmdline_options_init (void)
static void koala_multicolorize_colormap (native_data_t *source)
make all pixels double pixels
static uint8_t koala_find_bgcolor (native_data_t *source)
static void koala_check_and_correct_cell (native_data_t *source, uint8_t bgcolor)
static int koala_render_and_save (native_data_t *source)
static int koala_vicii_save (screenshot_t *screenshot, const char *filename)
static int koala_ted_save (screenshot_t *screenshot, const char *filename)
static int koala_vic_save (screenshot_t *screenshot, const char *filename)
static int koala_crtc_save (screenshot_t *screenshot, const char *filename)
static int koala_vdc_save (screenshot_t *screenshot, const char *filename)
static int koaladrv_save (screenshot_t *screenshot, const char *filename)
void gfxoutput_init_koala (int help)
Variables
static gfxoutputdrv_t koala_drv
static int oversize_handling
static int undersize_handling
static int ted_lum_handling
static const resource_int_t resources_int []
static const resource_int_t resources_int_plus4 []
static const cmdline_option_t cmdline_options []
static const cmdline_option_t cmdline_options_plus4 []
Macro Definition Documentation
BGCOLOR_OFFSET
#define BGCOLOR_OFFSET 10002
BITMAP_OFFSET
#define BITMAP_OFFSET 2
define offsets in the koala file
KOALA_SCREEN_BYTE_HEIGHT
#define KOALA_SCREEN_BYTE_HEIGHT KOALA_SCREEN_PIXEL_HEIGHT / 8
KOALA_SCREEN_BYTE_WIDTH
#define KOALA_SCREEN_BYTE_WIDTH KOALA_SCREEN_PIXEL_WIDTH / 8
KOALA_SCREEN_PIXEL_HEIGHT
#define KOALA_SCREEN_PIXEL_HEIGHT 200
KOALA_SCREEN_PIXEL_WIDTH
#define KOALA_SCREEN_PIXEL_WIDTH 320
Todo:
when all is done, remove if 0'ed code
KOALA_SIZE
#define KOALA_SIZE 10003
SCREENRAM_OFFSET
#define SCREENRAM_OFFSET 8002
VIDEORAM_OFFSET
#define VIDEORAM_OFFSET 9002
Function Documentation
gfxoutput_init_koala()
void gfxoutput_init_koala (int help)
Referenced by gfxoutput_early_init().
koala_check_and_correct_cell()
static void koala_check_and_correct_cell (native_data_t * source, uint8_t bgcolor) static
Referenced by koala_render_and_save().
koala_crtc_save()
static int koala_crtc_save (screenshot_t * screenshot, const char * filename) static
Referenced by koaladrv_save().
koala_find_bgcolor()
static uint8_t koala_find_bgcolor (native_data_t * source) static
Referenced by koala_render_and_save().
koala_multicolorize_colormap()
static void koala_multicolorize_colormap (native_data_t * source) static
make all pixels double pixels
Referenced by koala_render_and_save().
koala_render_and_save()
static int koala_render_and_save (native_data_t * source) static
< write mode (binary)
Referenced by koala_crtc_save(), koala_ted_save(), koala_vdc_save(), koala_vic_save(), and koala_vicii_save().
koala_ted_save()
static int koala_ted_save (screenshot_t * screenshot, const char * filename) static
Referenced by koaladrv_save().
koala_vdc_save()
static int koala_vdc_save (screenshot_t * screenshot, const char * filename) static
Referenced by koaladrv_save().
koala_vic_save()
static int koala_vic_save (screenshot_t * screenshot, const char * filename) static
Referenced by koaladrv_save().
koala_vicii_save()
static int koala_vicii_save (screenshot_t * screenshot, const char * filename) static
Referenced by koaladrv_save().
koaladrv_cmdline_options_init()
static int koaladrv_cmdline_options_init (void) static
koaladrv_resources_init()
static int koaladrv_resources_init (void) static
koaladrv_save()
static int koaladrv_save (screenshot_t * screenshot, const char * filename) static
set_oversize_handling()
static int set_oversize_handling (int val, void * param) static
set_ted_lum_handling()
static int set_ted_lum_handling (int val, void * param) static
set_undersize_handling()
static int set_undersize_handling (int val, void * param) static
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-koalaoversize", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "KoalaOversizeHandling", NULL,
      "<method>", "Select the way the oversized input should be handled,"
      " (0: scale down, 1: crop left top, 2: crop center top,  3: crop right top,"
      " 4: crop left center, 5: crop center, 6: crop right center, 7: crop left bottom,"
      " 8: crop center bottom, 9:  crop right bottom)" },
    { "-koalaundersize", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "KoalaUndersizeHandling", NULL,
      "<method>", "Select the way the undersized input should be handled,"
      " (0: scale up, 1: borderize)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by koaladrv_cmdline_options_init().
cmdline_options_plus4
const cmdline_option_t cmdline_options_plus4[] static
Initial value:
=
{
    { "-koalatedlum", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "KoalaTEDLumHandling", NULL,
      "<method>", "Select the way the TED luminosity should be handled,"
      " (0: ignore, 1: dither)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by koaladrv_cmdline_options_init().
koala_drv
static gfxoutputdrv_t koala_drv static
Initial value:
=
{
    GFXOUTPUTDRV_TYPE_SCREENSHOT_NATIVE,
    "KOALA",
    "Koalapainter screenshot",
    "koa",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    koaladrv_save,
    NULL,
    NULL,
    koaladrv_resources_init,
    koaladrv_cmdline_options_init
}
Referenced by gfxoutput_init_koala(), and koala_render_and_save().
oversize_handling
int oversize_handling static
Referenced by koala_crtc_save(), koala_vdc_save(), koala_vic_save(), and set_oversize_handling().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "KoalaOversizeHandling", NATIVE_SS_OVERSIZE_SCALE, RES_EVENT_NO, NULL,
      &oversize_handling, set_oversize_handling, NULL },
    { "KoalaUndersizeHandling", NATIVE_SS_UNDERSIZE_BORDERIZE, RES_EVENT_NO, NULL,
      &undersize_handling, set_undersize_handling, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by koaladrv_resources_init().
resources_int_plus4
const resource_int_t resources_int_plus4[] static
Initial value:
= {
    { "KoalaTEDLumHandling", NATIVE_SS_TED_LUM_DITHER, RES_EVENT_NO, NULL,
      &ted_lum_handling, set_ted_lum_handling, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by koaladrv_resources_init().
ted_lum_handling
int ted_lum_handling static
Referenced by koala_ted_save(), and set_ted_lum_handling().
undersize_handling
int undersize_handling static
Referenced by koala_crtc_save(), koala_vdc_save(), koala_vic_save(), and set_undersize_handling().