x128: serial/serial-iec.c File Reference
serial-iec.c File Reference
#include "vice.h"
#include "serial-iec-bus.h"
#include "serial-iec.h"
#include "types.h"
Functions
static void serial_iec_set_st (uint8_t st)
int serial_iec_open (unsigned int unit, unsigned int secondary, const char *name, unsigned int length)
int serial_iec_close (unsigned int unit, unsigned int secondary)
int serial_iec_read (unsigned int unit, unsigned int secondary, uint8_t *data)
int serial_iec_write (unsigned int unit, unsigned int secondary, uint8_t data)
int serial_iec_flush (unsigned int unit, unsigned int secondary)
Variables
static int serial_iec_st = 0
static unsigned int listen_active = 0
static unsigned int talk = 0
Function Documentation
serial_iec_close()
int serial_iec_close (unsigned int unit, unsigned int secondary)
Referenced by serial_iec_lib_directory(), and serial_iec_lib_read_sector().
serial_iec_flush()
int serial_iec_flush (unsigned int unit, unsigned int secondary)
serial_iec_open()
int serial_iec_open (unsigned int unit, unsigned int secondary, const char * name, unsigned int length)
Referenced by serial_iec_lib_directory(), and serial_iec_lib_read_sector().
serial_iec_read()
int serial_iec_read (unsigned int unit, unsigned int secondary, uint8_t * data)
Referenced by serial_iec_lib_directory(), and serial_iec_lib_read_sector().
serial_iec_set_st()
static void serial_iec_set_st (uint8_t st) static
Referenced by serial_iec_close(), serial_iec_open(), serial_iec_read(), and serial_iec_write().
serial_iec_write()
int serial_iec_write (unsigned int unit, unsigned int secondary, uint8_t data)
Variable Documentation
listen_active
unsigned int listen_active = 0 static
Referenced by serial_iec_close(), serial_iec_read(), and serial_iec_write().
serial_iec_st
int serial_iec_st = 0 static
Referenced by serial_iec_read(), serial_iec_set_st(), and serial_iec_write().
talk
unsigned int talk = 0 static
Referenced by serial_iec_close(), serial_iec_read(), and serial_iec_write().