vsid: vdrive/vdrive.c File Reference
vdrive.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "archdep.h"
#include "attach.h"
#include "cbmdos.h"
#include "diskconstants.h"
#include "diskimage.h"
#include "fsdevice.h"
#include "lib.h"
#include "log.h"
#include "types.h"
#include "vdrive-bam.h"
#include "vdrive-command.h"
#include "vdrive-dir.h"
#include "vdrive-iec.h"
#include "vdrive-internal.h"
#include "vdrive-rel.h"
#include "vdrive-snapshot.h"
#include "vdrive.h"
Macros
#define DBG(x)
#define min(a, b) ((a) < (b) ? (a) : (b))
#define MOVE_LBA_CHUNKS 32
do not set MOVE_LBA_CHUNKS to more than 128
Functions
void vdrive_init (void)
void vdrive_alloc_buffer (bufferinfo_t *p, int mode)
void vdrive_free_buffer (bufferinfo_t *p)
int vdrive_device_setup (vdrive_t *vdrive, unsigned int unit)
void vdrive_device_shutdown (vdrive_t *vdrive)
void vdrive_refresh (unsigned int unit)
called to start attached images from new
void vdrive_flush (unsigned int unit)
called to flush out attached images
void vdrive_close_all_channels (vdrive_t *vdrive)
void vdrive_close_all_channels_partition (vdrive_t *vdrive, int part)
int vdrive_get_max_sectors (vdrive_t *vdrive, unsigned int track)
int vdrive_get_max_sectors_per_head (vdrive_t *vdrive, unsigned int track)
void vdrive_detach_image (disk_image_t *image, unsigned int unit, unsigned int drive, vdrive_t *vdrive)
struct disk_image_s * vdrive_get_image (vdrive_t *vdrive, unsigned int drive)
int vdrive_attach_image (disk_image_t *image, unsigned int unit, unsigned int drive, vdrive_t *vdrive)
void vdrive_set_disk_geometry (vdrive_t *vdrive)
void vdrive_get_last_read (unsigned int *track, unsigned int *sector, uint8_t **buffer)
void vdrive_set_last_read (unsigned int track, unsigned int sector, uint8_t *buffer)
static int vdrive_log_to_phy (vdrive_t *vdrive, disk_addr_t *dadr, unsigned int track, unsigned int sector)
int vdrive_read_sector (vdrive_t *vdrive, uint8_t *buf, unsigned int track, unsigned int sector)
This is where logical sectors are turned to physical.
int vdrive_write_sector (vdrive_t *vdrive, const uint8_t *buf, unsigned int track, unsigned int sector)
int vdrive_read_sector_physical (vdrive_t *vdrive, uint8_t *buf, unsigned int track, unsigned int sector)
int vdrive_write_sector_physical (vdrive_t *vdrive, const uint8_t *buf, unsigned int track, unsigned int sector)
int vdrive_ext_read_sector (vdrive_t *vdrive, int drive, uint8_t *buf, unsigned int track, unsigned int sector)
For external access to individual drives.
int vdrive_ext_write_sector (vdrive_t *vdrive, int drive, const uint8_t *buf, unsigned int track, unsigned int sector)
int vdrive_find_sys (vdrive_t *vdrive)
0 = found, anything else DOS ERROR or not found
static uint32_t vdrive_buf3_to_word (uint8_t *buf)
static void vdrive_word_to_buf3 (uint8_t *buf, uint32_t value)
int vdrive_read_partition_table (vdrive_t *vdrive)
0 = okay, anything else, dos error
int vdrive_write_partition_table (vdrive_t *vdrive)
return DOS error
static int vdrive_change_part (vdrive_t *vdrive, int part)
0 if okay, anything else, dos error
int vdrive_ispartvalid (vdrive_t *vdrive, int part)
int vdrive_pack_parts (vdrive_t *vdrive)
int vdrive_switch (vdrive_t *vdrive, int part)
0 okay, anything else, bad
int vdrive_realpart (vdrive_t *vdrive, int part)
return the "real" partition when passed a 0 for CMD
Variables
static log_t vdrive_log = ((log_t)-1)
static unsigned int last_read_track
static unsigned int last_read_sector
static uint8_t last_read_buffer [256]
static const signed int tosec4171 [71]
static const signed int max4171 [71]
Macro Definition Documentation
DBG
#define DBG (x)
min
#define min (a, b) ((a) < (b) ? (a) : (b))
MOVE_LBA_CHUNKS
#define MOVE_LBA_CHUNKS 32
do not set MOVE_LBA_CHUNKS to more than 128
Function Documentation
vdrive_alloc_buffer()
void vdrive_alloc_buffer (bufferinfo_t * p, int mode)
Referenced by iec_open_read_directory(), iec_open_read_sequential(), iec_open_write(), vdrive_device_setup(), vdrive_dir_create_slot(), and vdrive_iec_open().
vdrive_attach_image()
int vdrive_attach_image (disk_image_t * image, unsigned int unit, unsigned int drive, vdrive_t * vdrive)
< number of tracks on a standard 1541 floppy
< Dual Disk Drive
< number of tracks on a 1571 floppy
< Dual Disk Drive
< Dual Disk Drive
< number of tracks on a standard 1541 floppy
< number of tracks on a 1571 floppy
Todo:
FIXME: extra checks might be needed for supporting other drives
< number of tracks on a 1571 floppy
< number of tracks on a standard 1541 floppy
< HD in ASCII for CMDHD
< D9090/D9060
vdrive->dir_part = drive;
< HD in ASCII for CMDHD
Referenced by attach_disk_image(), and vdrive_internal_open_fsimage().
vdrive_buf3_to_word()
static uint32_t vdrive_buf3_to_word (uint8_t * buf) static
Referenced by vdrive_read_partition_table().
vdrive_change_part()
static int vdrive_change_part (vdrive_t * vdrive, int part) static
0 if okay, anything else, dos error
< number of tracks on a standard 1541 floppy
< number of tracks on a 1571 floppy
< number of tracks on a 1581 diskette
Referenced by vdrive_switch().
vdrive_close_all_channels()
void vdrive_close_all_channels (vdrive_t * vdrive)
Referenced by vdrive_command_execute(), vdrive_command_format_internal(), and vdrive_detach_image().
vdrive_close_all_channels_partition()
void vdrive_close_all_channels_partition (vdrive_t * vdrive, int part)
Referenced by vdrive_command_format_worker(), vdrive_command_initialize(), vdrive_command_validate(), and vdrive_detach_image().
vdrive_detach_image()
void vdrive_detach_image (disk_image_t * image, unsigned int unit, unsigned int drive, vdrive_t * vdrive)
Referenced by detach_disk_image(), and vdrive_internal_close_disk_image().
vdrive_device_setup()
int vdrive_device_setup (vdrive_t * vdrive, unsigned int unit)
Referenced by file_system_init(), set_file_system_device(), and vdrive_internal_open_fsimage().
vdrive_device_shutdown()
void vdrive_device_shutdown (vdrive_t * vdrive)
Referenced by file_system_shutdown(), vdrive_internal_close_disk_image(), and vdrive_internal_open_fsimage().
vdrive_ext_read_sector()
int vdrive_ext_read_sector (vdrive_t * vdrive, int drive, uint8_t * buf, unsigned int track, unsigned int sector)
For external access to individual drives.
Referenced by mon_drive_block_cmd().
vdrive_ext_write_sector()
int vdrive_ext_write_sector (vdrive_t * vdrive, int drive, const uint8_t * buf, unsigned int track, unsigned int sector)
Referenced by mon_drive_block_cmd().
vdrive_find_sys()
int vdrive_find_sys (vdrive_t * vdrive)
0 = found, anything else DOS ERROR or not found
< HD in ASCII for CMDHD
stop for now short
Referenced by vdrive_read_partition_table().
vdrive_flush()
void vdrive_flush (unsigned int unit)
called to flush out attached images
Referenced by set_drive_true_emulation().
vdrive_free_buffer()
void vdrive_free_buffer (bufferinfo_t * p)
Referenced by iec_close_sequential(), iec_open_write(), vdrive_device_shutdown(), and vdrive_iec_close().
vdrive_get_image()
struct disk_image_s * vdrive_get_image (vdrive_t * vdrive, unsigned int drive)
Referenced by detach_disk_image_and_free(), file_system_attach_disk_internal(), file_system_detach_disk_shutdown(), file_system_detach_disk_single(), file_system_get_disk_name(), file_system_get_image(), vdrive_detach_disk_image_and_free(), and vdrive_snapshot_module_write().
vdrive_get_last_read()
void vdrive_get_last_read (unsigned int * track, unsigned int * sector, uint8_t ** buffer)
Referenced by disk_eof_callback().
vdrive_get_max_sectors()
int vdrive_get_max_sectors (vdrive_t * vdrive, unsigned int track)
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by vdrive_bam_alloc_add_interleave(), vdrive_bam_alloc_worker(), vdrive_command_format_worker(), vdrive_command_validate(), vdrive_dir_find_next_slot(), and vdrive_get_max_sectors_per_head().
vdrive_get_max_sectors_per_head()
int vdrive_get_max_sectors_per_head (vdrive_t * vdrive, unsigned int track)
Referenced by vdrive_bam_alloc_add_interleave(), vdrive_bam_alloc_next_free_sector_interleave(), vdrive_bam_alloc_next_free_sector_reset(), vdrive_bam_alloc_worker(), and vdrive_dir_find_next_slot().
vdrive_init()
void vdrive_init (void)
Referenced by init_main().
vdrive_ispartvalid()
int vdrive_ispartvalid (vdrive_t * vdrive, int part)
Referenced by vdrive_command_chcmdpart(), and vdrive_iec_open().
vdrive_log_to_phy()
static int vdrive_log_to_phy (vdrive_t * vdrive, disk_addr_t * dadr, unsigned int track, unsigned int sector) static
< HD in ASCII for CMDHD
< HD in ASCII for CMDHD
Referenced by vdrive_read_sector(), and vdrive_write_sector().
vdrive_pack_parts()
int vdrive_pack_parts (vdrive_t * vdrive)
< HD in ASCII for CMDHD
Referenced by vdrive_command_deletepart().
vdrive_read_partition_table()
int vdrive_read_partition_table (vdrive_t * vdrive)
0 = okay, anything else, dos error
< HD in ASCII for CMDHD
Todo:
check for D?M without partition table
Referenced by vdrive_attach_image(), vdrive_change_part(), vdrive_command_execute(), vdrive_command_format_internal(), and vdrive_ispartvalid().
vdrive_read_sector()
int vdrive_read_sector (vdrive_t * vdrive, uint8_t * buf, unsigned int track, unsigned int sector)
This is where logical sectors are turned to physical.
Not yet, but soon.
Referenced by diskcontents_block_read(), iec_open_read_sequential(), iec_open_write(), iec_read_sequential(), vdrive_bam_allocate_chain(), vdrive_bam_allocate_chain_255(), vdrive_bam_read_bam_block(), vdrive_command_allocate_chain(), vdrive_command_block(), vdrive_command_copy(), vdrive_command_getpartinfo(), vdrive_command_memory_write(), vdrive_command_renameheader(), vdrive_command_scratch(), vdrive_command_switchtraverse(), vdrive_command_u1a2b(), vdrive_command_validate_worker(), vdrive_dir_find_first_slot(), vdrive_dir_find_next_slot(), vdrive_dir_first_directory(), vdrive_dir_free_chain(), vdrive_dir_part_find_next_slot(), vdrive_ext_read_sector(), vdrive_find_sys(), vdrive_iec_update_dirent(), vdrive_pack_parts(), vdrive_read_partition_table(), vdrive_rel_listen(), vdrive_rel_open_existing(), vdrive_rel_position_internal(), vdrive_rel_read(), vdrive_rel_record_max(), vdrive_rel_scratch(), vdrive_rel_write(), vdrive_set_disk_geometry(), and vdrive_write_partition_table().
vdrive_read_sector_physical()
int vdrive_read_sector_physical (vdrive_t * vdrive, uint8_t * buf, unsigned int track, unsigned int sector)
vdrive_realpart()
int vdrive_realpart (vdrive_t * vdrive, int part)
return the "real" partition when passed a 0 for CMD
otherwiese return 0 if we exceed the number of drives
Referenced by vdrive_command_chdir(), vdrive_command_copy(), vdrive_iec_open(), and vdrive_switch().
vdrive_refresh()
void vdrive_refresh (unsigned int unit)
called to start attached images from new
Referenced by set_drive_true_emulation().
vdrive_set_disk_geometry()
void vdrive_set_disk_geometry (vdrive_t * vdrive)
< 1541 BAM track number
< 1541 BAM sector number
< 1541 BAM track number
< 1541 BAM sector number
< offset in BAM of the disk name in PETSCII, 16 bytes, padded with 0xa0
< offset in BAM of the disk ID in PETSCII, 2 bytes for standard DOS
< 1541 directory track number
< 1541 directory sector number
< Dual Disk Drive
< BAM track number
< BAM sector number
< BAM track number
< BAM sector number
< offset in BAM of the disk name in PETSCII, 16 bytes, padded with 0xa0
< offset in BAM of the disk ID in PETSCII, 2 bytes
< directory track number
< directory sector number
< BAM track number (side 1 BAM)
< BAM sector number (side 1 BAM)
< BAM track number (side 1 BAM)
< BAM sector number (side 1 BAM)
< offset in BAM of the disk name in PETSCII, 16 bytes, padded with 0xa0
< offset in BAM of the disk ID in PETSCII, 2 bytes
< directory track number
< directory sector number
< BAM track number
< BAM first sector number (the BAM of a 1581 diskette is three sectors)
< BAM track number
< BAM first sector number (the BAM of a 1581 diskette is three sectors)
< offset in BAM of disk name in PETSCII, 16 bytes, padded with 0xa0
< offset in BAM of disk ID in PETSCII, 2 bytes
< directory track number
< directory sector number
< Dual Disk Drive
< block w/disk name
< block w/disk name
< pos. of disk name in header blk
< pos. of disk id in header blk
< Dual Disk Drive
< block w/disk name
< block w/disk name
< pos. of disk name in header blk
< pos. of disk name in hdr blk
< pos. of disk id in header blk
< pos. of disk id in hdr blk
Referenced by vdrive_command_chpart(), vdrive_command_format_worker(), vdrive_command_initialize(), vdrive_command_return(), vdrive_command_rmdir(), and vdrive_switch().
vdrive_set_last_read()
void vdrive_set_last_read (unsigned int track, unsigned int sector, uint8_t * buffer)
Referenced by iec_open_read_sequential(), and iec_read_sequential().
vdrive_switch()
int vdrive_switch (vdrive_t * vdrive, int part)
0 okay, anything else, bad
Referenced by vdrive_attach_image(), vdrive_bam_get_disk_id(), vdrive_bam_set_disk_id(), vdrive_command_chcmdpart(), vdrive_command_getpartinfo(), vdrive_command_memory_write(), vdrive_command_renamepart(), vdrive_command_switch(), vdrive_ext_read_sector(), vdrive_ext_write_sector(), and vdrive_iec_switch().
vdrive_word_to_buf3()
static void vdrive_word_to_buf3 (uint8_t * buf, uint32_t value) static
Referenced by vdrive_write_partition_table().
vdrive_write_partition_table()
int vdrive_write_partition_table (vdrive_t * vdrive)
return DOS error
< HD in ASCII for CMDHD
Todo:
check for D?M without partition table
Referenced by vdrive_pack_parts().
vdrive_write_sector()
int vdrive_write_sector (vdrive_t * vdrive, const uint8_t * buf, unsigned int track, unsigned int sector)
Referenced by find_next_directory_sector(), iec_open_write(), iec_write_sequential(), vdrive_bam_create_empty_bam(), vdrive_bam_write_bam(), vdrive_command_block(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_format_internal(), vdrive_command_format_worker(), vdrive_command_lockunlock(), vdrive_command_memory_write(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_renameheader(), vdrive_command_renamepart(), vdrive_command_u1a2b(), vdrive_command_validate_worker(), vdrive_dir_find_next_slot(), vdrive_dir_remove_slot(), vdrive_ext_write_sector(), vdrive_iec_update_dirent(), vdrive_pack_parts(), vdrive_rel_add_sector(), vdrive_rel_commit(), vdrive_rel_flush_sidesectors(), vdrive_rel_open_new(), and vdrive_write_partition_table().
vdrive_write_sector_physical()
int vdrive_write_sector_physical (vdrive_t * vdrive, const uint8_t * buf, unsigned int track, unsigned int sector)
Variable Documentation
last_read_buffer
uint8_t last_read_buffer[256] static
Referenced by vdrive_get_last_read(), and vdrive_set_last_read().
last_read_sector
unsigned int last_read_sector static
Referenced by vdrive_get_last_read(), and vdrive_set_last_read().
last_read_track
unsigned int last_read_track static
Referenced by vdrive_get_last_read(), and vdrive_set_last_read().
max4171
const signed int max4171[71] static
Initial value:
= {
    -1,
    21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
    21, 21, 21, 21, 21, 21, 21, 19, 19, 19,
    19, 19, 19, 19, 18, 18, 18, 18, 18, 18,
    17, 17, 17, 17, 17,
    21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
    21, 21, 21, 21, 21, 21, 21, 19, 19, 19,
    19, 19, 19, 19, 18, 18, 18, 18, 18, 18,
    17, 17, 17, 17, 17
}
Referenced by vdrive_log_to_phy().
tosec4171
const signed int tosec4171[71] static
Initial value:
= {
      -1,
       0,   21,   42,   63,   84,  105,  126,  147,  168,  189,
     210,  231,  252,  273,  294,  315,  336,  357,  376,  395,
     414,  433,  452,  471,  490,  508,  526,  544,  562,  580,
     598,  615,  632,  649,  666,
     683,  704,  725,  746,  767,  788,  809,  830,  851,  872,
     893,  914,  935,  956,  977,  998, 1019, 1040, 1059, 1078,
    1097, 1116, 1135, 1154, 1173, 1191, 1209, 1227, 1245, 1263,
    1281, 1298, 1315, 1332, 1349
}
Referenced by vdrive_log_to_phy().
vdrive_log
log_t vdrive_log = ((log_t)-1) static
Referenced by vdrive_attach_image(), vdrive_detach_image(), vdrive_get_max_sectors(), vdrive_init(), vdrive_log_to_phy(), and vdrive_set_disk_geometry().