vsid: arch/gtk3/widgets/joystickmenupopup.c File Reference
joystickmenupopup.c File Reference
Create a menu to swap joysticks.
#include "vice.h"
#include <gtk/gtk.h>
#include "actions-joystick.h"
#include "debug_gtk3.h"
#include "hotkeys.h"
#include "machine.h"
#include "resources.h"
#include "uiactions.h"
#include "uimenu.h"
#include "uisettings.h"
#include "widgethelpers.h"
#include "joystickmenupopup.h"
Functions
static gboolean joystick_swap_possible (void)
Determine if joystick swapping is possible.
static void on_configure_activate (GtkWidget *widget, gpointer user_data)
Handler for the 'activate' event of the "configure ..." menu item.
static void trigger_ui_action (GtkWidget *item, gpointer action)
Trigger a UI action.
GtkWidget * joystick_menu_popup_create (void)
Create joystick menu popup for the statusbar.
Detailed Description
Create a menu to swap joysticks.
This module contains a popup menu that can be triggered via the statusbar's joysticks widget. With it, the user can swap joystick ports.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
joystick_menu_popup_create()
GtkWidget * joystick_menu_popup_create (void)
Create joystick menu popup for the statusbar.
Returns
GtkMenu
Referenced by on_joystick_widget_button_press().
joystick_swap_possible()
static gboolean joystick_swap_possible (void) static
Determine if joystick swapping is possible.
Returns
bool
Referenced by joystick_menu_popup_create().
on_configure_activate()
static void on_configure_activate (GtkWidget * widget, gpointer user_data) static
Handler for the 'activate' event of the "configure ..." menu item.
Opens the joystick configuration settings page.
Parameters
[in] widget menu item (unused)
[in] user_data extra event data (unused)
Referenced by joystick_menu_popup_create().
trigger_ui_action()
static void trigger_ui_action (GtkWidget * item, gpointer action) static
Trigger a UI action.
Parameters
[in] item menu item (unused)
[in] action UI action ID
Referenced by joystick_menu_popup_create().