vsid: drive/iec/memiec.c File Reference
memiec.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include "ciad.h"
#include "drivemem.h"
#include "drivetypes.h"
#include "lib.h"
#include "memiec.h"
#include "types.h"
#include "via1d1541.h"
#include "viad.h"
#include "wd1770.h"
#include "via4000.h"
#include "pc8477.h"
#include "cmdhd.h"
Functions
static uint8_t drive_read_rom (diskunit_context_t *drv, uint16_t address)
static uint8_t drive_read_rom_ds1216 (diskunit_context_t *drv, uint16_t address)
static uint8_t drive_read_ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_ram (diskunit_context_t *drv, uint16_t address, uint8_t value)
static uint8_t drive_read_1541ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_1541ram (diskunit_context_t *drv, uint16_t address, uint8_t value)
static uint8_t drive_read_zero (diskunit_context_t *drv, uint16_t address)
static void drive_store_zero (diskunit_context_t *drv, uint16_t address, uint8_t value)
void memiec_init (struct diskunit_context_s *drv, unsigned int type)
Function Documentation
drive_read_1541ram()
static uint8_t drive_read_1541ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memiec_init().
drive_read_ram()
static uint8_t drive_read_ram (diskunit_context_t * drv, uint16_t address) static
Referenced by memiec_init().
drive_read_rom()
static uint8_t drive_read_rom (diskunit_context_t * drv, uint16_t address) static
Referenced by memiec_init().
drive_read_rom_ds1216()
static uint8_t drive_read_rom_ds1216 (diskunit_context_t * drv, uint16_t address) static
Referenced by memiec_init().
drive_read_zero()
static uint8_t drive_read_zero (diskunit_context_t * drv, uint16_t address) static
Referenced by memiec_init().
drive_store_1541ram()
static void drive_store_1541ram (diskunit_context_t * drv, uint16_t address, uint8_t value) static
Referenced by memiec_init().
drive_store_ram()
static void drive_store_ram (diskunit_context_t * drv, uint16_t address, uint8_t value) static
Referenced by memiec_init().
drive_store_zero()
static void drive_store_zero (diskunit_context_t * drv, uint16_t address, uint8_t value) static
Referenced by memiec_init().
memiec_init()
void memiec_init (struct diskunit_context_s * drv, unsigned int type)
Todo:
FIXME: the following is very incorrect
< ASCII for HD
Referenced by iec_drive_mem_init().