vsid: arch/gtk3/widgets/superpetwidget.c File Reference
superpetwidget.c File Reference
Widget to control various SuperPET related resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "aciawidget.h"
#include "resources.h"
#include "ui.h"
#include "superpetwidget.h"
Functions
static void superpet_enable_callback (GtkWidget *widget, int enabled)
Callback for the check button widget.
static GtkWidget * create_superpet_enable_widget (void)
Create check button for the SuperPET resource.
static GtkWidget * create_superpet_cpu_widget (void)
Create SuperPET CPU selection widget.
GtkWidget * superpet_widget_create (void)
Create a SuperPET-specific widget to be used in the PET model widget.
void pet_superpet_widget_set_superpet_enable_callback (void(*func)(int))
Set function to trigger on SuperPET enable checkbox toggle.
void pet_superpet_enable_widget_sync (void)
Synchronize widget with its resource.
Variables
static int baud_rates [] = { 300, 1200, 2400, 9600, 19200, -1 }
List of baud rates for the ACIA widget.
static const vice_gtk3_radiogroup_entry_t cpu_types []
List of CPU types.
static GtkWidget * enable_widget = NULL
SuperPET enable toggle button.
static GtkWidget * acia1_widget = NULL
ACIA widget.
static GtkWidget * cpu_widget = NULL
CPU widget.
static void(* user_callback_enable)(int)
User-defined callback function.
Detailed Description
Widget to control various SuperPET related resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_superpet_cpu_widget()
static GtkWidget * create_superpet_cpu_widget (void) static
Create SuperPET CPU selection widget.
Select between 'MOS 6502, 'Motorola 6809' or 'programmable'
Returns
GtkGrid
Referenced by superpet_widget_create().
create_superpet_enable_widget()
static GtkWidget * create_superpet_enable_widget (void) static
Create check button for the SuperPET resource.
Create a grid with a check button and some informative text under it.
Returns
GtkGrid
Referenced by superpet_widget_create().
pet_superpet_enable_widget_sync()
void pet_superpet_enable_widget_sync (void)
Synchronize widget with its resource.
Parameters
[in,out] widget SuperPET I/O enabled widget
Referenced by machine_model_handler_pet().
pet_superpet_widget_set_superpet_enable_callback()
void pet_superpet_widget_set_superpet_enable_callback (void(*)(int) func)
Set function to trigger on SuperPET enable checkbox toggle.
Parameters
[in] func callback function
Referenced by create_pet_layout().
superpet_enable_callback()
static void superpet_enable_callback (GtkWidget * widget, int enabled) static
Callback for the check button widget.
Parameters
[in] widget check button widget
[in] enabled enabled or not
Referenced by create_superpet_enable_widget().
superpet_widget_create()
GtkWidget * superpet_widget_create (void)
Create a SuperPET-specific widget to be used in the PET model widget.
Returns
GtkGrid
Referenced by create_pet_layout().
Variable Documentation
acia1_widget
GtkWidget* acia1_widget = NULL static
ACIA widget.
Referenced by superpet_widget_create().
baud_rates
int baud_rates[] = { 300, 1200, 2400, 9600, 19200, -1 } static
List of baud rates for the ACIA widget.
Referenced by superpet_widget_create().
cpu_types
const vice_gtk3_radiogroup_entry_t cpu_types[] static
Initial value:
= {
    { "MOS 6502", 0 },
    { "Motorola 6809", 1 },
    { "Programmable", 2 },
    { NULL, -1 },
}
List of CPU types.
Referenced by create_superpet_cpu_widget().
cpu_widget
GtkWidget* cpu_widget = NULL static
CPU widget.
Referenced by superpet_widget_create().
enable_widget
GtkWidget* enable_widget = NULL static
SuperPET enable toggle button.
Referenced by pet_superpet_enable_widget_sync(), settings_mmc64_widget_create(), and superpet_widget_create().
user_callback_enable
void(* user_callback_enable) (int) (int) static
User-defined callback function.
Set with pet_superpet_widget_set_superpet_enable_callback()
Referenced by pet_superpet_widget_set_superpet_enable_callback(), and superpet_enable_callback().