vsid: arch/gtk3/uimon.c File Reference
uimon.c File Reference
Native GTK3 UI monitor stuff.
#include "vice.h"
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <limits.h>
#include "novte/novte.h"
#include <dirent.h>
#include <ctype.h>
#include <unistd.h>
#include "archdep.h"
#include "charset.h"
#include "console.h"
#include "debug_gtk3.h"
#include "machine.h"
#include "monitor.h"
#include "mainlock.h"
#include "resources.h"
#include "lib.h"
#include "log.h"
#include "ui.h"
#include "linenoise.h"
#include "unicodehelpers.h"
#include "uimon.h"
#include "uimon-fallback.h"
#include "mon_command.h"
#include "vsync.h"
#include "vsyncapi.h"
#include "widgethelpers.h"
#include "uidata.h"
Data Structures
struct console_private_s
Monitor console window object.
Macros
#define vte_terminal_new novte_terminal_new
#define vte_terminal_feed novte_terminal_feed
#define vte_terminal_get_column_count novte_terminal_get_column_count
#define vte_terminal_copy_clipboard novte_terminal_copy_clipboard
#define vte_terminal_copy_clipboard_format novte_terminal_copy_clipboard_format
#define vte_terminal_get_row_count novte_terminal_get_row_count
#define vte_terminal_set_scrollback_lines novte_terminal_set_scrollback_lines
#define vte_terminal_set_scroll_on_output novte_terminal_set_scroll_on_output
#define vte_terminal_get_char_width novte_terminal_get_char_width
#define vte_terminal_get_char_height novte_terminal_get_char_height
#define VTE_TERMINAL(x) NOVTE_TERMINAL(x)
#define VteTerminal NoVteTerminal
#define VTE_CSS "vte-terminal { font-size: 300%; }"
#define DEFAULT_COLUMNS 80
#define DEFAULT_ROWS 50
#define FONT_TYPE_ASCII 0
#define FONT_TYPE_C64PRO 1
#define FONT_TYPE_PETME 2
https://www.kreativekorp.com/software/fonts/c64/
#define FONT_TYPE_PETME64 3
https://www.kreativekorp.com/software/fonts/c64/
Functions
static gboolean uimon_window_open_impl (gpointer user_data)
static gboolean uimon_window_resume_impl (gpointer user_data)
static int is_dir (struct dirent *de)
static int native_monitor (void)
static gboolean write_to_terminal (gpointer _)
void uimon_write_to_terminal (struct console_private_s *t, const char *data, glong length)
int uimon_out (const char *buffer)
int uimon_petscii_out (const char *buffer, int len)
int uimon_petscii_upper_out (const char *buffer, int len)
int uimon_scrcode_out (const char *buffer, int len)
output screencode, lowercase
int uimon_scrcode_upper_out (const char *buffer, int len)
output screencode, uppercase
int uimon_get_columns (struct console_private_s *t)
static char * append_char_to_input_buffer (char *old_input_buffer, char new_char)
static char * append_string_to_input_buffer (char *old_input_buffer, GtkWidget *terminal, GdkAtom clipboard_to_use)
static gboolean plain_key_pressed (char **input_buffer, guint keyval)
static gboolean ctrl_plus_key_pressed (char **input_buffer, guint keyval, GtkWidget *terminal)
static gboolean on_window_delete_event (GtkWidget *window, GdkEvent *event, gpointer user_data)
Handler for the 'delete-event' event of monitor window.
static gboolean on_term_key_press_event (GtkWidget *widget, GdkEventKey *event, gpointer user_data)
Handler for the 'key-press-event' event of the the VTE terminal.
static gboolean on_term_button_press_event (GtkWidget *widget, GdkEvent *event, gpointer user_data)
Handler for the 'button-press-event' event of the the VTE terminal.
int uimon_get_string (struct console_private_s *t, char *string, int string_len)
Block until some monitor input event happens.
static void get_terminal_size_in_chars (NoVteTerminal *terminal, glong *width, glong *height)
static void printfontinfo (const PangoFontDescription *desc, const char *name)
static void scale_terminal_set (gdouble scale)
static void scale_terminal (gdouble delta)
static gboolean on_term_scrolled (NoVteTerminal *terminal, GdkEvent *event, gpointer user_data)
static void on_term_text_modified (NoVteTerminal *terminal, gpointer user_data)
Handler for the 'text-modified event of the VTE terminal.
static void on_window_configure_event (GtkWidget *window, GdkEvent *event, gpointer user_data)
Handler for the 'configure-event' event of the monitor window.
static GdkPixbuf * get_default_icon (void)
Create an icon by loading it from the vice.gresource file.
console_t * uimonfb_window_open (void)
Open console window.
static PangoFontDescription * getfontdesc (const char *name)
Try to set VTE monitor font.
bool uimon_set_font (void)
Gtk3-specific, so far.
bool uimon_set_foreground_color (const char *color)
Set foreground color.
bool uimon_set_background_color (const char *color)
Set foreground color.
static gboolean uimon_window_suspend_impl (gpointer user_data)
static gboolean uimon_window_close_impl (gpointer user_data)
console_t * uimon_window_open (bool display_now)
console_t * uimon_window_resume (void)
void uimon_window_suspend (void)
void uimon_window_close (void)
void uimon_notify_change (void)
void uimon_set_interface (struct monitor_interface_s **interf, int i)
static char * concat_strings (const char *string1, int nchars, const char *string2)
static void fill_completions (const char *string_so_far, int initial_chars, int token_len, const linenoiseCompletions *possible_lc, linenoiseCompletions *lc)
static void find_next_token (const char *string_so_far, int start_of_search, int *start_of_token, int *token_len)
static gboolean is_token_in (const char *string_so_far, int token_len, const linenoiseCompletions *lc)
static void monitor_completions (const char *string_so_far, linenoiseCompletions *lc)
char * uimon_get_in (char **ppchCommandLine, const char *prompt)
int console_init (void)
int console_close_all (void)
Variables
static struct console_private_s fixed
static console_t vte_console = { 80 , 50 , 0, 1, NULL }
static linenoiseCompletions command_lc = {0, NULL}
static linenoiseCompletions need_filename_lc = {0, NULL}
static int font_type = 0
Detailed Description
Native GTK3 UI monitor stuff.
Author
Fabrizio Gennari fabri.nosp@m.zio..nosp@m.ge@ti.nosp@m.scal.nosp@m.i.it
David Hogan david.nosp@m..q.h.nosp@m.ogan@.nosp@m.gmai.nosp@m.l.com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
!
Todo:
Properly document this, please.
Macro Definition Documentation
DEFAULT_COLUMNS
#define DEFAULT_COLUMNS 80
DEFAULT_ROWS
#define DEFAULT_ROWS 50
FONT_TYPE_ASCII
#define FONT_TYPE_ASCII 0
FONT_TYPE_C64PRO
#define FONT_TYPE_C64PRO 1
FONT_TYPE_PETME
#define FONT_TYPE_PETME 2
https://www.kreativekorp.com/software/fonts/c64/
FONT_TYPE_PETME64
#define FONT_TYPE_PETME64 3
https://www.kreativekorp.com/software/fonts/c64/
VTE_CSS
#define VTE_CSS "vte-terminal { font-size: 300%; }"
VTE_TERMINAL
#define VTE_TERMINAL (x) NOVTE_TERMINAL(x)
vte_terminal_copy_clipboard
#define vte_terminal_copy_clipboard novte_terminal_copy_clipboard
vte_terminal_copy_clipboard_format
#define vte_terminal_copy_clipboard_format novte_terminal_copy_clipboard_format
vte_terminal_feed
#define vte_terminal_feed novte_terminal_feed
vte_terminal_get_char_height
#define vte_terminal_get_char_height novte_terminal_get_char_height
vte_terminal_get_char_width
#define vte_terminal_get_char_width novte_terminal_get_char_width
vte_terminal_get_column_count
#define vte_terminal_get_column_count novte_terminal_get_column_count
vte_terminal_get_row_count
#define vte_terminal_get_row_count novte_terminal_get_row_count
vte_terminal_new
#define vte_terminal_new novte_terminal_new
vte_terminal_set_scroll_on_output
#define vte_terminal_set_scroll_on_output novte_terminal_set_scroll_on_output
vte_terminal_set_scrollback_lines
#define vte_terminal_set_scrollback_lines novte_terminal_set_scrollback_lines
VteTerminal
#define VteTerminal NoVteTerminal
Function Documentation
append_char_to_input_buffer()
static char * append_char_to_input_buffer (char * old_input_buffer, char new_char) static
Referenced by ctrl_plus_key_pressed(), and plain_key_pressed().
append_string_to_input_buffer()
static char * append_string_to_input_buffer (char * old_input_buffer, GtkWidget * terminal, GdkAtom clipboard_to_use) static
Referenced by ctrl_plus_key_pressed(), and on_term_button_press_event().
concat_strings()
static char * concat_strings (const char * string1, int nchars, const char * string2) static
Referenced by fill_completions(), and monitor_completions().
console_close_all()
int console_close_all (void)
Referenced by cmdline_help(), and machine_shutdown().
console_init()
int console_init (void)
Referenced by init_main().
ctrl_plus_key_pressed()
static gboolean ctrl_plus_key_pressed (char ** input_buffer, guint keyval, GtkWidget * terminal) static
Referenced by on_term_key_press_event().
fill_completions()
static void fill_completions (const char * string_so_far, int initial_chars, int token_len, const linenoiseCompletions * possible_lc, linenoiseCompletions * lc) static
Referenced by monitor_completions().
find_next_token()
static void find_next_token (const char * string_so_far, int start_of_search, int * start_of_token, int * token_len) static
Referenced by monitor_completions().
get_default_icon()
static GdkPixbuf * get_default_icon (void) static
Create an icon by loading it from the vice.gresource file.
Returns
Current emulator's icon
Note
If we want something else, we should ask whoever created the current icon set.
Referenced by uimon_window_open_impl().
get_terminal_size_in_chars()
static void get_terminal_size_in_chars (NoVteTerminal * terminal, glong * width, glong * height) static
Referenced by on_term_text_modified().
getfontdesc()
static PangoFontDescription * getfontdesc (const char * name) static
Try to set VTE monitor font.
Returns
boolean
Referenced by uimon_set_font().
is_dir()
static int is_dir (struct dirent * de) static
Todo:
FIXME: this should perhaps be done using some function from archdep
Referenced by monitor_completions().
is_token_in()
static gboolean is_token_in (const char * string_so_far, int token_len, const linenoiseCompletions * lc) static
Referenced by monitor_completions().
monitor_completions()
static void monitor_completions (const char * string_so_far, linenoiseCompletions * lc) static
Referenced by uimon_get_in().
native_monitor()
static int native_monitor (void) static
Referenced by console_close_all(), console_init(), uimon_get_in(), uimon_notify_change(), uimon_out(), uimon_petscii_out(), uimon_petscii_upper_out(), uimon_scrcode_out(), uimon_scrcode_upper_out(), uimon_set_interface(), uimon_window_close(), uimon_window_open(), uimon_window_resume(), and uimon_window_suspend().
on_term_button_press_event()
static gboolean on_term_button_press_event (GtkWidget * widget, GdkEvent * event, gpointer user_data) static
Handler for the 'button-press-event' event of the the VTE terminal.
Parameters
[in] widget VTE terminal
[in] event event information
[in] user_data extra event data (unused)
Returns
TRUE to stop propagation of event, or FALSE to propagate further
Referenced by uimon_window_open_impl().
on_term_key_press_event()
static gboolean on_term_key_press_event (GtkWidget * widget, GdkEventKey * event, gpointer user_data) static
Handler for the 'key-press-event' event of the the VTE terminal.
Parameters
[in] widget VTE terminal
[in] event event information
[in] user_data extra event data (unused)
Returns
TRUE to stop propagation of event, or FALSE to propagate further
Referenced by uimon_window_open_impl().
on_term_scrolled()
static gboolean on_term_scrolled (NoVteTerminal * terminal, GdkEvent * event, gpointer user_data) static
Referenced by uimon_window_open_impl().
on_term_text_modified()
static void on_term_text_modified (NoVteTerminal * terminal, gpointer user_data) static
Handler for the 'text-modified event of the VTE terminal.
Parameters
[in] terminal VTE terminal
[in] user_data extra event data (unused)
Referenced by uimon_window_open_impl(), and uimon_window_resume_impl().
on_window_configure_event()
static void on_window_configure_event (GtkWidget * window, GdkEvent * event, gpointer user_data) static
Handler for the 'configure-event' event of the monitor window.
Resize the terminal when the window is resized, and store monitor window geometry in resources.
Parameters
[in] window terminal window (unused)
[in] event event information (unused)
[in] user_data extra event data (unused
Referenced by uimon_window_open_impl().
on_window_delete_event()
static gboolean on_window_delete_event (GtkWidget * window, GdkEvent * event, gpointer user_data) static
Handler for the 'delete-event' event of monitor window.
Parameters
[in] window monitor window
[in] event event information (unused)
[in] user_data extra event data (unused)
Returns
TRUE to stop propagating the event further
Referenced by uimon_window_open_impl().
plain_key_pressed()
static gboolean plain_key_pressed (char ** input_buffer, guint keyval) static
Referenced by on_term_key_press_event().
printfontinfo()
static void printfontinfo (const PangoFontDescription * desc, const char * name) static
Referenced by on_term_scrolled(), and uimon_set_font().
scale_terminal()
static void scale_terminal (gdouble delta) static
Referenced by on_term_scrolled().
scale_terminal_set()
static void scale_terminal_set (gdouble scale) static
Referenced by uimon_set_font().
uimon_get_columns()
int uimon_get_columns (struct console_private_s * t)
Referenced by linenoisePrompt().
uimon_get_in()
char * uimon_get_in (char ** ppchCommandLine, const char * prompt)
Referenced by uimon_in().
uimon_get_string()
int uimon_get_string (struct console_private_s * t, char * string, int string_len)
Block until some monitor input event happens.
Todo:
Not sure if this check makes sense anymore, needs testing without
Referenced by completeLine(), and linenoisePrompt().
uimon_notify_change()
void uimon_notify_change (void)
Referenced by monitor_cpu_type_set(), monitor_cpu_type_set_value(), monitor_open(), and monitor_process().
uimon_out()
int uimon_out (const char * buffer)
Referenced by linenoisePrompt(), mon_buffer_flush(), and mon_out_buffered().
uimon_petscii_out()
int uimon_petscii_out (const char * buffer, int len)
< https://www.kreativekorp.com/software/fonts/c64/
< https://www.kreativekorp.com/software/fonts/c64/
Referenced by mon_buffer_flush(), and mon_out_buffered().
uimon_petscii_upper_out()
int uimon_petscii_upper_out (const char * buffer, int len)
< https://www.kreativekorp.com/software/fonts/c64/
< https://www.kreativekorp.com/software/fonts/c64/
Referenced by mon_buffer_flush(), and mon_out_buffered().
uimon_scrcode_out()
int uimon_scrcode_out (const char * buffer, int len)
output screencode, lowercase
< https://www.kreativekorp.com/software/fonts/c64/
Todo:
FIXME: regular PETSCII capable ("PET Me") font
< https://www.kreativekorp.com/software/fonts/c64/
Todo:
FIXME: regular PETSCII capable ("PET Me") font
Referenced by mon_buffer_flush(), and mon_out_buffered().
uimon_scrcode_upper_out()
int uimon_scrcode_upper_out (const char * buffer, int len)
output screencode, uppercase
< https://www.kreativekorp.com/software/fonts/c64/
Todo:
FIXME: regular PETSCII capable ("PET Me") font
< https://www.kreativekorp.com/software/fonts/c64/
Todo:
FIXME: regular PETSCII capable ("PET Me") font
Referenced by mon_buffer_flush(), and mon_out_buffered().
uimon_set_background_color()
bool uimon_set_background_color (const char * color)
Set foreground color.
Set VTE terminal foreground color to color.
Parameters
[in] color Gdk RGBA color string
Returns
bool
See also
https://docs.gtk.org/gdk3/method.RGBA.parse.html
Referenced by set_monitor_bg().
uimon_set_font()
bool uimon_set_font (void)
Gtk3-specific, so far.
< https://www.kreativekorp.com/software/fonts/c64/
< https://www.kreativekorp.com/software/fonts/c64/
Referenced by on_font_set(), and uimon_window_open_impl().
uimon_set_foreground_color()
bool uimon_set_foreground_color (const char * color)
Set foreground color.
Set VTE terminal foreground color to color.
Parameters
[in] color Gdk RGBA color string
Returns
bool
See also
https://docs.gtk.org/gdk3/method.RGBA.parse.html
Referenced by set_monitor_fg().
uimon_set_interface()
void uimon_set_interface (struct monitor_interface_s ** interf, int i)
Referenced by monitor_open().
uimon_window_close()
void uimon_window_close (void)
Referenced by monitor_close().
uimon_window_close_impl()
static gboolean uimon_window_close_impl (gpointer user_data) static
Referenced by uimon_window_close().
uimon_window_open()
console_t * uimon_window_open (bool display_now)
Referenced by monitor_open(), and uimonfb_window_resume().
uimon_window_open_impl()
static gboolean uimon_window_open_impl (gpointer user_data) static
Referenced by uimon_window_open().
uimon_window_resume()
console_t * uimon_window_resume (void)
Referenced by monitor_open().
uimon_window_resume_impl()
static gboolean uimon_window_resume_impl (gpointer user_data) static
Referenced by uimon_window_open_impl(), and uimon_window_resume().
uimon_window_suspend()
void uimon_window_suspend (void)
Referenced by monitor_close(), and uimonfb_window_close().
uimon_window_suspend_impl()
static gboolean uimon_window_suspend_impl (gpointer user_data) static
Referenced by uimon_window_suspend().
uimon_write_to_terminal()
void uimon_write_to_terminal (struct console_private_s * t, const char * data, glong length)
Referenced by uimon_out(), uimon_petscii_out(), uimon_petscii_upper_out(), uimon_scrcode_out(), and uimon_scrcode_upper_out().
uimonfb_window_open()
console_t * uimonfb_window_open (void)
Open console window.
Returns
console reference
Referenced by uimon_window_open().
write_to_terminal()
static gboolean write_to_terminal (gpointer _) static
Referenced by uimon_window_close_impl(), uimon_window_open_impl(), and uimon_write_to_terminal().
Variable Documentation
command_lc
linenoiseCompletions command_lc = {0, NULL} static
Referenced by console_close_all(), console_init(), and monitor_completions().
fixed
struct console_private_s fixed static
Referenced by console_close_all(), console_init(), on_term_button_press_event(), on_term_key_press_event(), on_term_scrolled(), on_window_configure_event(), on_window_delete_event(), printfontinfo(), scale_terminal(), scale_terminal_set(), uimon_get_in(), uimon_out(), uimon_petscii_out(), uimon_petscii_upper_out(), uimon_scrcode_out(), uimon_scrcode_upper_out(), uimon_set_background_color(), uimon_set_font(), uimon_set_foreground_color(), uimon_window_close_impl(), uimon_window_open_impl(), uimon_window_resume_impl(), uimon_window_suspend_impl(), uimon_write_to_terminal(), and write_to_terminal().
font_type
int font_type = 0 static
Referenced by printfontinfo(), uimon_petscii_out(), uimon_petscii_upper_out(), uimon_scrcode_out(), uimon_scrcode_upper_out(), and uimon_set_font().
need_filename_lc
linenoiseCompletions need_filename_lc = {0, NULL} static
Referenced by console_close_all(), console_init(), and monitor_completions().
vte_console
console_t vte_console = { 80 , 50 , 0, 1, NULL } static
Referenced by on_term_text_modified(), on_window_configure_event(), uimon_window_open(), uimon_window_open_impl(), and uimon_window_resume().