vsid: tapeport/tapecart.h File Reference
tapecart.h File Reference
#include <stdint.h>
Data Structures
struct tapecart_memory_s
all the important data from a TCRT file
Macros
#define TAPECART_FLASH_SIZE (2 * 1024 * 1024)
#define TAPECART_LOADER_SIZE 171
#define TAPECART_FILENAME_SIZE 16
Typedefs
typedef struct tapecart_memory_s tapecart_memory_t
all the important data from a TCRT file
Functions
int tapecart_resources_init (int amount)
int tapecart_cmdline_options_init (void)
int tapecart_attach_tcrt (const char *filename, void *unused)
int tapecart_flush_tcrt (void)
Flush current tapecart data to image file.
void tapecart_exit (void)
Clean up memory used by the tapecart emulation.
int tapecart_is_valid (const char *filename)
Check magic of the tapecart filename.
Macro Definition Documentation
TAPECART_FILENAME_SIZE
#define TAPECART_FILENAME_SIZE 16
TAPECART_FLASH_SIZE
#define TAPECART_FLASH_SIZE (2 * 1024 * 1024)
TAPECART_LOADER_SIZE
#define TAPECART_LOADER_SIZE 171
Typedef Documentation
tapecart_memory_t
typedef struct tapecart_memory_s tapecart_memory_t
all the important data from a TCRT file
(aka "everything a real tapecart stores in non-volatile memory")
Function Documentation
tapecart_attach_tcrt()
int tapecart_attach_tcrt (const char * filename, void * unused)
Referenced by autostart_tapecart(), and try_attach_tapecart().
tapecart_cmdline_options_init()
int tapecart_cmdline_options_init (void)
Referenced by tapeport_devices_cmdline_options_init().
tapecart_exit()
void tapecart_exit (void)
Clean up memory used by the tapecart emulation.
trct_filename is allocated even when the tapecart is disabled, but never freed. This will clean up the memory used by the filename. Also, tapecart_memory and tapecart_buffers weren't properly freed.
And yes, I know we use ${module}_shutdown() as the name for a cleanup function, but tapecart_shutdown is already taken.
Referenced by machine_resources_shutdown().
tapecart_flush_tcrt()
int tapecart_flush_tcrt (void)
Flush current tapecart data to image file.
Returns
0 on success, < 0 on failure
Referenced by on_tcrt_flush_clicked().
tapecart_is_valid()
int tapecart_is_valid (const char * filename)
Check magic of the tapecart filename.
Checks the first 13 bytes for 'tapecartImage', which seems to be the TCRT header magic.
Returns
bool
Referenced by autostart_tapecart(), and try_attach_tapecart().
tapecart_resources_init()
int tapecart_resources_init (int amount)
Referenced by tapeport_device_resources_init().