vsid: arch/shared/hotkeys/vhkkeysyms.c File Reference
vhkkeysyms.c File Reference
#include "vice.h"
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "lib.h"
#include "hotkeystypes.h"
#include "vhkkeysyms.h"
#include "keysymtable.h"
Data Structures
struct vhk_key_s
Mapping of key name to value.
Macros
#define ARR_ELEMENTS(arr) (sizeof arr / sizeof arr[0])
Typedefs
typedef struct vhk_key_s vhk_key_t
Mapping of key name to value.
Functions
static int compar (const void *p1, const void *p2)
include generated keysyms table: static vhk_key_t keys[]
uint32_t vhk_keysym_from_name (const char *name)
Get keysym value from name.
const char * vhk_keysym_name (uint32_t keysym)
Get keysym name from value.
uint32_t vhk_modifier_from_name (const char *name, const char **endptr)
Parse string for modifier name and return modifier bit.
char * vhk_modmask_name (uint32_t vice_modmask)
Get string of modifier names for a modifier mask.
const char * vhk_modifier_name (uint32_t vice_modifier)
Get modifier name.
char * vhk_hotkey_label (uint32_t vice_keysym, uint32_t vice_modmask)
Get accelerator label for a hotkey.
Variables
static const vhk_modifier_t vhk_modifier_list []
List of UI-agnostic modifier keys.
static const uint32_t mod_order []
Order in which modifier names should appear in hotkey labels.
Macro Definition Documentation
ARR_ELEMENTS
#define ARR_ELEMENTS (arr) (sizeof arr / sizeof arr[0])
Typedef Documentation
vhk_key_t
typedef struct vhk_key_s vhk_key_t
Mapping of key name to value.
Function Documentation
compar()
static int compar (const void * p1, const void * p2) static
include generated keysyms table: static vhk_key_t keys[]
Comparison function for bsearch(3)
Compare the name members of key table elements p1 and p1 with strcmp(3).
Parameters
p1 pointer to first element
p2 pointer to second element
Returns
< 0 if p1 < p2, 0 if p1 == p2, > 0 if p1 > p2
Referenced by array_compact(), array_sort(), binary_search(), and vhk_keysym_from_name().
vhk_hotkey_label()
char * vhk_hotkey_label (uint32_t vice_keysym, uint32_t vice_modmask)
Get accelerator label for a hotkey.
Create a string to present a hotkey's key name and modifier mask to the user. This function is very much like gtk_accelerator_get_label() and meant for UI toolkits that do not provide such a function, such as SDL.
Parameters
[in] vice_keysym VICE keysym
[in] vice_modmask VICE modifier mask
Returns
heap-allocated string, free with lib_free()
Note
returns NULL for invalid vice_keysym values
Referenced by ui_action_map_get_hotkey_label().
vhk_keysym_from_name()
uint32_t vhk_keysym_from_name (const char * name)
Get keysym value from name.
Parameters
[in] name keysym name
Returns
keysym value as defined in vhkkeysyms.h, or 0 when not found
Referenced by vhk_parser_get_keysym_and_modmask().
vhk_keysym_name()
const char * vhk_keysym_name (uint32_t keysym)
Get keysym name from value.
Parameters
keysym keysym value
Returns
name or NULL when keysym isn't valid
Referenced by ui_hotkeys_save_as(), vhk_hotkey_label(), vhk_parser_do_undef(), and vhk_parser_handle_mapping().
vhk_modifier_from_name()
uint32_t vhk_modifier_from_name (const char * name, const char ** endptr)
Parse string for modifier name and return modifier bit.
Parse name for a valid modifier name and return its value, storing the position in name after either end-of-string or '>' in endptr. The name is allowed to start with a '>' opening tag.
Parameters
[in] name string to parse
[out] endptr position in name of the closing '>' tag or the nul character (optional)
Returns
VICE modifier value
Referenced by parser_get_modifier().
vhk_modifier_name()
const char * vhk_modifier_name (uint32_t vice_modifier)
Get modifier name.
Get a string representing a keyboard modifier. The returned string is the unadorned name, so no '<' or '>' around the name like in the hotkeys files.
Parameters
[in] vice_modifier VICE modifier
Returns
modifier name
Referenced by vhk_hotkey_label().
vhk_modmask_name()
char * vhk_modmask_name (uint32_t vice_modmask)
Get string of modifier names for a modifier mask.
Generate string with modifier names enclosed by angled brackets from modifier mask vice_modmask.
Parameters
[in] vice_modmask VICE modifier mask
Returns
heap-allocated string, free with lib_free()
Note
Always returns an allocated string, being the empty string for a modifier mask of 0 (VHK_MOD_NONE).
Referenced by ui_hotkeys_save_as().
Variable Documentation
mod_order
const uint32_t mod_order[] static
Initial value:
= {
     0x0004 ,
     0x0001 ,
     0x0020 ,
     0x0040 ,
     0x0002 ,
     0x0080 ,
     0x0010 ,
     0x0008
}
Order in which modifier names should appear in hotkey labels.
Referenced by vhk_hotkey_label().
vhk_modifier_list
const vhk_modifier_t vhk_modifier_list[] static
Initial value:
= {
    {  0x0001 ,      "Alt",      "Alt" },
    {  0x0002 ,  "Command",  "Command \u2318" },
    {  0x0004 ,  "Control",  "Control \u2303" },
    {  0x0008 ,    "Hyper",    "Hyper" },
    {  0x0010 ,     "Meta",     "Meta" },
    {  0x0020 ,   "Option",   "Option \u2325" },
    {  0x0040 ,    "Shift",    "Shift \u21e7" },
    {  0x0080 ,    "Super",    "Super" }
}
List of UI-agnostic modifier keys.
Referenced by vhk_modifier_from_name(), vhk_modifier_name(), and vhk_modmask_name().