vsid: drive/iec/fdd.c File Reference
fdd.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "lib.h"
#include "log.h"
#include "types.h"
#include "fdd.h"
#include "diskconstants.h"
#include "diskimage.h"
#include "drive.h"
#include "snapshot.h"
Data Structures
struct fd_drive_s
Macros
#define FDD_MAX_TRACK (80 + 3)
#define FDD_NUM_TRACKS (80 + 3)
#define INDEXLEN (16)
#define fdd_raw_write(b)
#define fdd_raw_write_sync(b)
#define FDD_SNAP_MAJOR 1
#define FDD_SNAP_MINOR 0
Functions
static void fdd_flush_raw (fd_drive_t *drv)
fd_drive_t * fdd_init (int num, drive_t *drive)
static void fdd_init_crc1021 (void)
void fdd_shutdown (fd_drive_t *drv)
void fdd_image_attach (fd_drive_t *drv, struct disk_image_s *image)
void fdd_image_detach (fd_drive_t *drv)
uint16_t fdd_crc (uint16_t crc, uint8_t b)
static void fdd_update_raw (fd_drive_t *drv)
uint64_t fdd_rotate (fd_drive_t *drv, uint64_t bytes_in)
int fdd_index (fd_drive_t *drv)
void fdd_index_count_reset (fd_drive_t *drv)
unsigned int fdd_index_count (fd_drive_t *drv)
int fdd_track0 (fd_drive_t *drv)
int fdd_write_protect (fd_drive_t *drv)
int fdd_disk_change (fd_drive_t *drv)
uint16_t fdd_read (fd_drive_t *drv)
int fdd_write (fd_drive_t *drv, uint16_t data)
void fdd_flush (fd_drive_t *drv)
void fdd_seek_pulse (fd_drive_t *drv, int dir)
void fdd_select_head (fd_drive_t *drv, int head)
void fdd_set_motor (fd_drive_t *drv, int motor)
void fdd_set_rate (fd_drive_t *drv, int rate)
int fdd_snapshot_write_module (fd_drive_t *drv, struct snapshot_s *s)
int fdd_snapshot_read_module (fd_drive_t *drv, struct snapshot_s *s)
Variables
const int fdd_data_rates [4] = { 500, 300, 250, 1000 }
static uint16_t * crc1021 = NULL
Macro Definition Documentation
FDD_MAX_TRACK
#define FDD_MAX_TRACK (80 + 3)
FDD_NUM_TRACKS
#define FDD_NUM_TRACKS (80 + 3)
fdd_raw_write
#define fdd_raw_write (b)
Value:
    {                                                       \
        drv->raw.data[p] = b;                \
        drv->raw.sync[p >> 3] &= (uint8_t)(0xff7f >> (p & 7)); \
        p++;                                                \
        if (p >= drv->raw.size) {                           \
            p = 0;                                          \
        }                                                   \
    }
fdd_raw_write_sync
#define fdd_raw_write_sync (b)
Value:
    {                                                       \
        drv->raw.data[p] = b;                \
        drv->raw.sync[p >> 3] |= (uint8_t)(0x80 >> (p & 7));   \
        p++;                                                \
        if (p >= drv->raw.size) {                           \
            p = 0;                                          \
        }                                                   \
    }
FDD_SNAP_MAJOR
#define FDD_SNAP_MAJOR 1
FDD_SNAP_MINOR
#define FDD_SNAP_MINOR 0
INDEXLEN
#define INDEXLEN (16)
Function Documentation
fdd_crc()
uint16_t fdd_crc (uint16_t crc, uint8_t b) inline
Referenced by fdd_update_raw(), and wd1770_execute().
fdd_disk_change()
int fdd_disk_change (fd_drive_t * drv)
Referenced by pc8477_peek(), pc8477_read(), and wd1770_disk_change().
fdd_flush()
void fdd_flush (fd_drive_t * drv)
fdd_flush_raw()
static void fdd_flush_raw (fd_drive_t * drv) static
Referenced by fdd_flush(), fdd_image_detach(), and fdd_update_raw().
fdd_image_attach()
void fdd_image_attach (fd_drive_t * drv, struct disk_image_s * image)
< maximum number of tracks on a 1581 diskette
Referenced by pc8477_attach_image(), and wd1770_attach_image().
fdd_image_detach()
void fdd_image_detach (fd_drive_t * drv)
Referenced by pc8477_detach_image(), and wd1770_detach_image().
fdd_index()
int fdd_index (fd_drive_t * drv)
Referenced by wd1770_execute().
fdd_index_count()
unsigned int fdd_index_count (fd_drive_t * drv)
Referenced by pc8477_execute(), pc8477_micro_find_sync(), pc8477_micro_readid(), and wd1770_execute().
fdd_index_count_reset()
void fdd_index_count_reset (fd_drive_t * drv)
Referenced by pc8477_execute(), pc8477_store(), and wd1770_execute().
fdd_init()
fd_drive_t * fdd_init (int num, drive_t * drive)
Todo:
What about the other fields in raw?
Referenced by pc8477_setup_context(), and wd1770d_init().
fdd_init_crc1021()
static void fdd_init_crc1021 (void) static
Referenced by fdd_crc().
fdd_read()
uint16_t fdd_read (fd_drive_t * drv)
Referenced by pc8477_execute(), pc8477_micro_find_sync(), pc8477_micro_readid(), and wd1770_execute().
fdd_rotate()
uint64_t fdd_rotate (fd_drive_t * drv, uint64_t bytes_in)
Referenced by pc8477_execute(), pc8477_store(), wd1770_execute(), and wd1770_store().
fdd_seek_pulse()
void fdd_seek_pulse (fd_drive_t * drv, int dir)
Todo:
FIXME: actually extend the image here
Referenced by seek_alarm_handler(), and wd1770_execute().
fdd_select_head()
void fdd_select_head (fd_drive_t * drv, int head)
Referenced by pc8477_store(), and wd1770_set_side().
fdd_set_motor()
void fdd_set_motor (fd_drive_t * drv, int motor)
Referenced by pc8477_setup_context(), and wd1770_set_motor().
fdd_set_rate()
void fdd_set_rate (fd_drive_t * drv, int rate)
Referenced by pc8477_store().
fdd_shutdown()
void fdd_shutdown (fd_drive_t * drv)
Referenced by pc8477_shutdown(), and wd1770_shutdown().
fdd_snapshot_read_module()
int fdd_snapshot_read_module (fd_drive_t * drv, struct snapshot_s * s)
Referenced by wd1770_snapshot_read_module().
fdd_snapshot_write_module()
int fdd_snapshot_write_module (fd_drive_t * drv, struct snapshot_s * s)
Todo:
Disk image save
Referenced by wd1770_snapshot_write_module().
fdd_track0()
int fdd_track0 (fd_drive_t * drv)
Referenced by pc8477_result(), seek_alarm_handler(), and wd1770_execute().
fdd_update_raw()
static void fdd_update_raw (fd_drive_t * drv) static
Referenced by fdd_read(), and fdd_write().
fdd_write()
int fdd_write (fd_drive_t * drv, uint16_t data)
Referenced by pc8477_execute(), and wd1770_execute().
fdd_write_protect()
int fdd_write_protect (fd_drive_t * drv)
Referenced by pc8477_execute(), pc8477_result(), and wd1770_execute().
Variable Documentation
crc1021
uint16_t* crc1021 = NULL static
Referenced by fdd_crc(), and fdd_init_crc1021().
fdd_data_rates
const int fdd_data_rates[4] = { 500, 300, 250, 1000 }
Referenced by fdd_image_attach(), fdd_snapshot_read_module(), and pc8477_store().