x128: userport_device_s Struct Reference
userport_device_s Struct Reference
this structure is used by userport devices
#include <userport.h>
Data Fields
char * name
int joystick_adapter_id
int device_type
int(* enable)(int val)
uint8_t(* read_pbx)(uint8_t orig)
void(* store_pbx)(uint8_t val, int pulse)
uint8_t(* read_pa2)(uint8_t orig)
void(* store_pa2)(uint8_t val)
uint8_t(* read_pa3)(uint8_t orig)
void(* store_pa3)(uint8_t val)
int needs_pc
void(* store_sp1)(uint8_t val)
uint8_t(* read_sp1)(uint8_t orig)
void(* store_sp2)(uint8_t val)
uint8_t(* read_sp2)(uint8_t orig)
void(* reset)(void)
void(* powerup)(void)
int(* write_snapshot)(struct snapshot_s *s)
int(* read_snapshot)(struct snapshot_s *s)
Detailed Description
this structure is used by userport devices
Field Documentation
device_type
int userport_device_s::device_type
Referenced by userport_device_register(), and userport_get_valid_devices().
enable
int(* userport_device_s::enable) (int val)
Referenced by userport_device_register(), and userport_set_device().
joystick_adapter_id
int userport_device_s::joystick_adapter_id
Referenced by userport_device_register(), and userport_resources_init().
name
char* userport_device_s::name
Referenced by userport_device_register(), userport_get_valid_devices(), userport_petscii_enable(), userport_resources_init(), userport_spt_joystick_enable(), and userport_superpad64_enable().
needs_pc
int userport_device_s::needs_pc
Referenced by userport_device_register(), and valid_device().
powerup
void(* userport_device_s::powerup) (void)
Referenced by userport_device_register(), and userport_powerup().
read_pa2
uint8_t(* userport_device_s::read_pa2) (uint8_t orig)
Referenced by read_userport_pa2(), userport_device_register(), and valid_device().
read_pa3
uint8_t(* userport_device_s::read_pa3) (uint8_t orig)
Referenced by read_userport_pa3(), userport_device_register(), and valid_device().
read_pbx
uint8_t(* userport_device_s::read_pbx) (uint8_t orig)
Referenced by read_userport_pbx(), and userport_device_register().
read_snapshot
int(* userport_device_s::read_snapshot) (struct snapshot_s *s)
Referenced by userport_device_register().
read_sp1
uint8_t(* userport_device_s::read_sp1) (uint8_t orig)
Referenced by read_userport_sp1(), userport_device_register(), and valid_device().
read_sp2
uint8_t(* userport_device_s::read_sp2) (uint8_t orig)
Referenced by read_userport_sp2(), userport_device_register(), and valid_device().
reset
void(* userport_device_s::reset) (void)
Referenced by userport_device_register(), and userport_reset().
store_pa2
void(* userport_device_s::store_pa2) (uint8_t val)
Referenced by store_userport_pa2(), userport_device_register(), and valid_device().
store_pa3
void(* userport_device_s::store_pa3) (uint8_t val)
Referenced by store_userport_pa3(), userport_device_register(), and valid_device().
store_pbx
void(* userport_device_s::store_pbx) (uint8_t val, int pulse)
Referenced by store_userport_pbx(), and userport_device_register().
store_sp1
void(* userport_device_s::store_sp1) (uint8_t val)
Referenced by store_userport_sp1(), userport_device_register(), and valid_device().
store_sp2
void(* userport_device_s::store_sp2) (uint8_t val)
Referenced by store_userport_sp2(), userport_device_register(), and valid_device().
write_snapshot
int(* userport_device_s::write_snapshot) (struct snapshot_s *s)
Referenced by userport_device_register().
The documentation for this struct was generated from the following file:
userport/userport.h