x128: arch/gtk3/uimedia.c File Reference
uimedia.c File Reference
Media recording dialog.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "gfxoutput.h"
#include "lastdir.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "mainlock.h"
#include "monitor.h"
#include "resources.h"
#include "screenshot.h"
#include "sound.h"
#include "statusbarrecordingwidget.h"
#include "ui.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uistatusbar.h"
#include "vice_gtk3.h"
#include "videoarch.h"
#include "vsync.h"
#include "ffmpegwidget.h"
#include "uimedia.h"
Data Structures
struct video_driver_info_s
Struct to hold information on available video recording drivers.
struct audio_driver_info_s
Struct to hold information on available audio recording drivers.
Macros
#define CHILD_SCREENSHOT "Screenshot"
Name of the stack child for screenshots.
#define CHILD_SOUND "Sound"
Name of the stack child for sound recording.
#define CHILD_VIDEO "Video"
Name of the stack child for video recording.
Typedefs
typedef struct video_driver_info_s video_driver_info_t
Struct to hold information on available video recording drivers.
typedef struct audio_driver_info_s audio_driver_info_t
Struct to hold information on available audio recording drivers.
Enumerations
enum { RESPONSE_SAVE = 1 }
Custom response IDs for the dialog.
Functions
static GtkWidget * create_screenshot_param_widget (const char *prefix)
forward declarations of helper functions
static void save_screenshot_handler (GtkWidget *parent)
Save a screenshot.
static void save_audio_recording_handler (GtkWidget *parent)
Start an audio recording.
static void save_video_recording_handler (GtkWidget *parent)
Start recording a video.
static void on_dialog_destroy (GtkWidget *widget, gpointer data)
Handler for the "destroy" event of the dialog.
static void update_screenshot_options_grid (GtkWidget *new)
Set new widget for the screenshot options, replacing the old one.
static void update_video_driver_options_grid (GtkWidget *new)
Set new widget for the movie options, replacing the old one.
static void on_response (GtkDialog *dialog, gint response_id, gpointer data)
Handler for the "response" event of the dialog.
static void on_screenshot_driver_toggled (GtkWidget *widget, gpointer data)
Handler for the "toggled" event of the screenshot driver radios.
static void on_audio_driver_toggled (GtkWidget *widget, gpointer data)
Handler for the "toggled" event of the audio driver radios.
static void on_video_driver_toggled (GtkWidget *widget, gpointer data)
Handler for the "toggled" event of the video driver dropdown list.
static const char * ffmpeg_kludges (const char *name)
static char * create_proposed_video_recording_name (const char *ext)
Create a filename based on the current datetime and ext.
static char * create_proposed_audio_recording_name (const char *ext)
Create a filename based on the current datetime and ext.
static gboolean save_screenshot_error_impl (gpointer data)
UI error message handler for saving screenshots.
static void save_screenshot_vsync_callback (void *param)
Callback to make a screenshot on vsync to avoid tearing.
static void on_save_screenshot_filename (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the save-screenshot dialog.
static void on_save_audio_filename (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the save-audio dialog.
static void on_save_video_filename (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the save-video dialog.
static void create_video_driver_list (void)
Create heap-allocated list of available video drivers.
static GtkWidget * create_screenshot_widget (void)
Create the main 'screenshot' widget.
static GtkWidget * create_sound_widget (void)
Create the main 'sound recording' widget.
static GtkWidget * create_video_widget (void)
Create the main 'video recording' widget.
static GtkWidget * create_content_widget (void)
Create the content widget for the dialog.
void ui_media_dialog_show (void)
Show dialog to save screenshot, record sound and/or video.
void ui_media_stop_recording (void)
Stop audio or video recording, if active.
void ui_media_shutdown (void)
Clean up resources used.
Variables
static video_driver_info_t * video_driver_list = NULL
List of available video drivers, gotten during runtime.
static int video_driver_count = 0
Number of available video drivers.
static int screenshot_driver_index = -1
Index of currently selected screenshot driver.
static int video_driver_index = 0
Index of currently selected video driver.
static const char * video_driver = NULL
static int audio_driver_index = -1
Index of currently selected audio driver.
static gchar * media_last_dir = NULL
Last used directory of the file chooser dialogs.
static audio_driver_info_t audio_driver_list []
List of available audio recording drivers.
static vice_gtk3_combo_entry_int_t oversize_modes []
List of 'oversize modes' for some screenshot output drivers.
static vice_gtk3_combo_entry_int_t undersize_modes []
List of 'undersize modes' for some screenshot output drivers.
static const vice_gtk3_combo_entry_int_t multicolor_modes []
List of multi color modes for some screenshot output drivers.
static const vice_gtk3_combo_entry_int_t ted_luma_modes []
TED output driver Luma modes.
static char * screenshot_filename = NULL
Screenshot filename for save_screenshot_vsync_callback()
static char * screenshot_driver = NULL
Screenshot driver name for save_screenshot_vsync_callback()
static GtkWidget * main_dialog = NULL
Reference to the dialog for the vysnc callback.
static GtkWidget * stack
Reference to the GtkStack containing the media types.
static int old_pause_state = 0
Pause state when activating the dialog.
static GtkWidget * screenshot_options_grid = NULL
references to widgets, used from various event handlers
static GtkWidget * oversize_widget = NULL
Screenshot "Oversize" widget reference.
static GtkWidget * undersize_widget = NULL
Screenshot "Undersize" widget reference.
static GtkWidget * multicolor_widget = NULL
Screenshot "Multicolor mode" widget reference.
static GtkWidget * ted_luma_widget = NULL
Screenshot "TED luma" widget reference.
static GtkWidget * video_driver_options_grid = NULL
FFMPEG video driver options grid reference.
Detailed Description
Media recording dialog.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
CHILD_SCREENSHOT
#define CHILD_SCREENSHOT "Screenshot"
Name of the stack child for screenshots.
CHILD_SOUND
#define CHILD_SOUND "Sound"
Name of the stack child for sound recording.
CHILD_VIDEO
#define CHILD_VIDEO "Video"
Name of the stack child for video recording.
Typedef Documentation
audio_driver_info_t
typedef struct audio_driver_info_s audio_driver_info_t
Struct to hold information on available audio recording drivers.
video_driver_info_t
typedef struct video_driver_info_s video_driver_info_t
Struct to hold information on available video recording drivers.
Enumeration Type Documentation
anonymous enum
anonymous enum
Custom response IDs for the dialog.
Enumerator
RESPONSE_SAVE
Save button clicked.
Function Documentation
create_content_widget()
static GtkWidget * create_content_widget (void) static
Create the content widget for the dialog.
Contains a GtkStack and GtkStackSwitcher to switch between 'screenshot', 'sound' and 'video' sub widgets.
Returns
GtkGrid
Referenced by ui_media_dialog_show().
create_proposed_audio_recording_name()
static char * create_proposed_audio_recording_name (const char * ext) static
Create a filename based on the current datetime and ext.
Parameters
[in] ext file extension (without the dot)
Returns
heap-allocated string, owned by VICE, free with lib_free()
Referenced by save_audio_recording_handler().
create_proposed_video_recording_name()
static char * create_proposed_video_recording_name (const char * ext) static
Create a filename based on the current datetime and ext.
Parameters
[in] ext file extension (without the dot)
Returns
heap-allocated string, owned by VICE, free with lib_free()
Referenced by save_video_recording_handler().
create_screenshot_param_widget()
static GtkWidget * create_screenshot_param_widget (const char * prefix) static
forward declarations of helper functions
Create widget to control screenshot parameters.
This widget exposes controls to alter screenshot parameters, depending on machine class and output file format
Parameters
[in] prefix resource prefix (either "OCP", "Koala", or ""/NULL)
Returns
GtkGrid
Referenced by create_screenshot_widget(), and on_screenshot_driver_toggled().
create_screenshot_widget()
static GtkWidget * create_screenshot_widget (void) static
Create the main 'screenshot' widget.
Returns
GtkGrid
Referenced by create_content_widget().
create_sound_widget()
static GtkWidget * create_sound_widget (void) static
Create the main 'sound recording' widget.
Returns
GtkGrid
Referenced by create_content_widget(), and ui_media_dialog_show().
create_video_driver_list()
static void create_video_driver_list (void) static
Create heap-allocated list of available video drivers.
Queries the gfxoutputdrv subsystem and builds a list of currently available drivers and stores it in driver_list. Must be freed with lib_free() after use.
Referenced by ui_media_dialog_show().
create_video_widget()
static GtkWidget * create_video_widget (void) static
Create the main 'video recording' widget.
Returns
GtkGrid
Referenced by create_content_widget().
ffmpeg_kludges()
static const char * ffmpeg_kludges (const char * name) static
Referenced by save_video_recording_handler().
on_audio_driver_toggled()
static void on_audio_driver_toggled (GtkWidget * widget, gpointer data) static
Handler for the "toggled" event of the audio driver radios.
Parameters
[in] widget radio button riggering the event
[in] data extra event data (unused)
Referenced by create_sound_widget().
on_dialog_destroy()
static void on_dialog_destroy (GtkWidget * widget, gpointer data) static
Handler for the "destroy" event of the dialog.
Parameters
[in] widget dialog
[in] data extra event data (unused)
Referenced by ui_media_dialog_show().
on_response()
static void on_response (GtkDialog * dialog, gint response_id, gpointer data) static
Handler for the "response" event of the dialog.
Parameters
[in,out] dialog dialog triggering the event
[in] response_id response ID
[in] data parent dialog
Referenced by ui_media_dialog_show().
on_save_audio_filename()
static void on_save_audio_filename (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the save-audio dialog.
Parameters
[in,out] dialog dialog
[in,out] filename audio recording filename
[in] data extra data (unused)
Referenced by save_audio_recording_handler().
on_save_screenshot_filename()
static void on_save_screenshot_filename (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the save-screenshot dialog.
Parameters
[in,out] dialog dialog
[in,out] filename screenshot filename
[in] data extra data (unused)
Todo:
add extension if not present?
Referenced by save_screenshot_handler().
on_save_video_filename()
static void on_save_video_filename (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the save-video dialog.
Parameters
[in,out] dialog dialog
[in,out] filename video recording filename
[in] data extra data (unused)
Todo:
add extension if not present?
Referenced by save_video_recording_handler().
on_screenshot_driver_toggled()
static void on_screenshot_driver_toggled (GtkWidget * widget, gpointer data) static
Handler for the "toggled" event of the screenshot driver radios.
Parameters
[in] widget radio button riggering the event
[in] data extra event data (unused)
Referenced by create_screenshot_widget().
on_video_driver_toggled()
static void on_video_driver_toggled (GtkWidget * widget, gpointer data) static
Handler for the "toggled" event of the video driver dropdown list.
Parameters
[in] widget widget riggering the event
[in] data extra event data (unused)
Referenced by create_video_widget().
save_audio_recording_handler()
static void save_audio_recording_handler (GtkWidget * parent) static
Start an audio recording.
Pops up a save-file dialog with a proposed filename (ie 'audio-recording-197411151210.png'.
Note
Destroys parent along with the dialog
Parameters
[in,out] parent dialog
Referenced by on_response().
save_screenshot_error_impl()
static gboolean save_screenshot_error_impl (gpointer data) static
UI error message handler for saving screenshots.
Parameters
[in] data filename of screenshot
Returns
G_SOURCE_REMOVE to make this a one-shot timer event
Referenced by save_screenshot_vsync_callback().
save_screenshot_handler()
static void save_screenshot_handler (GtkWidget * parent) static
Save a screenshot.
Pops up a save-file dialog with a proposed filename (ie 'screenshot-197411151210.png'.
Note
Destroys parent along with the dialog
Parameters
[in,out] parent parent dialog
Referenced by on_response().
save_screenshot_vsync_callback()
static void save_screenshot_vsync_callback (void * param) static
Callback to make a screenshot on vsync to avoid tearing.
The screenshot_filename variable is allocated by the UI thread and freed and set to NULL by this function, thus indicating to the UI it is allowed to queue another screenshot on vsync.
Parameters
[in] param video canvas to take screenshot of
Referenced by on_save_screenshot_filename().
save_video_recording_handler()
static void save_video_recording_handler (GtkWidget * parent) static
Start recording a video.
Pops up a save-file dialog with a proposed filename (ie 'video-recording-197411151210.png'.
Note
Destroys parent along with the dialog
Parameters
[in,out] parent parent dialog
Referenced by on_response().
ui_media_dialog_show()
void ui_media_dialog_show (void)
Show dialog to save screenshot, record sound and/or video.
Referenced by media_record_action().
ui_media_shutdown()
void ui_media_shutdown (void)
Clean up resources used.
Frees the last dir/file strings
Referenced by ui_exit().
ui_media_stop_recording()
void ui_media_stop_recording (void)
Stop audio or video recording, if active.
Referenced by media_stop_action(), and on_stop_clicked().
update_screenshot_options_grid()
static void update_screenshot_options_grid (GtkWidget * new) static
Set new widget for the screenshot options, replacing the old one.
Destroys any widget present before setting the new widget.
Parameters
[in] new new widget
Referenced by create_screenshot_widget(), and on_screenshot_driver_toggled().
update_video_driver_options_grid()
static void update_video_driver_options_grid (GtkWidget * new) static
Set new widget for the movie options, replacing the old one.
Destroys any widget present before setting the new widget.
Parameters
[in] new new widget
Referenced by on_video_driver_toggled().
Variable Documentation
audio_driver_index
int audio_driver_index = -1 static
Index of currently selected audio driver.
Initially set to -1 to select WAV as default in the audio driver list. Set to last selected driver on subsequent uses of the dialog.
Referenced by create_sound_widget(), on_audio_driver_toggled(), on_save_audio_filename(), and save_audio_recording_handler().
audio_driver_list
audio_driver_info_t audio_driver_list[] static
Initial value:
= {
    { "WAV",        "wav",  "wav" },
    { "AIFF",       "aiff", "aif" },
    { "VOC",        "voc",  "voc" },
    { "IFF",        "iff",  "iff" },
    { NULL,         NULL,   NULL }
}
List of available audio recording drivers.
This list is dependent on compile-time options
Referenced by create_sound_widget(), on_save_audio_filename(), and save_audio_recording_handler().
main_dialog
GtkWidget* main_dialog = NULL static
Reference to the dialog for the vysnc callback.
Referenced by on_dialog_destroy(), save_screenshot_error_impl(), and ui_media_dialog_show().
media_last_dir
gchar* media_last_dir = NULL static
Last used directory of the file chooser dialogs.
We only remember the directory, not the last filename, since we propose a filename with a timestamp in it to quickly save new media files without having to type a new name. Using last_file would mean the generated filename gets overwritten with the old one, so the convenience of the generated filenames would be lost.
Referenced by on_save_audio_filename(), on_save_screenshot_filename(), on_save_video_filename(), save_audio_recording_handler(), save_screenshot_handler(), save_video_recording_handler(), and ui_media_shutdown().
multicolor_modes
const vice_gtk3_combo_entry_int_t multicolor_modes[] static
Initial value:
= {
    { "Black & White",      NATIVE_SS_MC2HR_BLACK_WHITE },
    { "2 colors",           NATIVE_SS_MC2HR_2_COLORS },
    { "4 colors",           NATIVE_SS_MC2HR_4_COLORS },
    { "Grayscale",          NATIVE_SS_MC2HR_GRAY },
    { "Best cell colors",   NATIVE_SS_MC2HR_DITHER },
    { NULL,                 -1 }
}
List of multi color modes for some screenshot output drivers.
Referenced by create_screenshot_param_widget().
multicolor_widget
GtkWidget* multicolor_widget = NULL static
Screenshot "Multicolor mode" widget reference.
Referenced by create_screenshot_param_widget().
old_pause_state
int old_pause_state = 0 static
Pause state when activating the dialog.
Referenced by on_dialog_destroy(), and ui_media_dialog_show().
oversize_modes
vice_gtk3_combo_entry_int_t oversize_modes[] static
Initial value:
= {
    { "scale down",         NATIVE_SS_OVERSIZE_SCALE },
    { "crop left top",      NATIVE_SS_OVERSIZE_CROP_LEFT_TOP, },
    { "crop center top",    NATIVE_SS_OVERSIZE_CROP_CENTER_TOP },
    { "crop right top",     NATIVE_SS_OVERSIZE_CROP_RIGHT_TOP },
    { "crop left center",   NATIVE_SS_OVERSIZE_CROP_LEFT_CENTER },
    { "crop center",        NATIVE_SS_OVERSIZE_CROP_CENTER },
    { "crop right center",  NATIVE_SS_OVERSIZE_CROP_RIGHT_CENTER },
    { "crop left bottom",   NATIVE_SS_OVERSIZE_CROP_LEFT_BOTTOM },
    { "crop center bottom", NATIVE_SS_OVERSIZE_CROP_CENTER_BOTTOM },
    { "crop right bottom",  NATIVE_SS_OVERSIZE_CROP_RIGHT_BOTTOM },
    { NULL,                 -1 }
}
List of 'oversize modes' for some screenshot output drivers.
Referenced by create_screenshot_param_widget().
oversize_widget
GtkWidget* oversize_widget = NULL static
Screenshot "Oversize" widget reference.
Referenced by create_screenshot_param_widget().
screenshot_driver
char* screenshot_driver = NULL static
Screenshot driver name for save_screenshot_vsync_callback()
When the dialog is closed the video drive list is also destroyed, so we cannot access the list in the vsync callback. The UI thread created a copy of the requested driver and the VICE thread then frees it in the vsync callback function.
Referenced by on_save_screenshot_filename(), and save_screenshot_vsync_callback().
screenshot_driver_index
int screenshot_driver_index = -1 static
Index of currently selected screenshot driver.
Initially set to -1 to select PNG as default in the screenshot driver list. Set to last selected driver on subsequent uses of the dialog.
Referenced by create_screenshot_widget(), on_save_screenshot_filename(), on_screenshot_driver_toggled(), and save_screenshot_handler().
screenshot_filename
char* screenshot_filename = NULL static
Screenshot filename for save_screenshot_vsync_callback()
This gets allocated by the UI thread and freed by the VICE thread.
If non-NULL the UI thread will not free and reallocate, it simply refuses to queue another screenshot. Queuing a second screenshot while the vsync handler hasn't processed the current one is an unlikely scenario, but could happen with a very low custom emulation speed and a quick user. Once the vsync handler has used the filename, it is deallocated and set to NULL to indicate to the UI another screenshot can be queued.
Referenced by on_save_screenshot_filename(), and save_screenshot_vsync_callback().
screenshot_options_grid
GtkWidget* screenshot_options_grid = NULL static
references to widgets, used from various event handlers
Screenshot options grid reference
Referenced by create_screenshot_widget(), and update_screenshot_options_grid().
stack
GtkWidget* stack static
Reference to the GtkStack containing the media types.
Used in the dialog response callback to determine recording mode and params
Referenced by create_content_widget(), and on_response().
ted_luma_modes
const vice_gtk3_combo_entry_int_t ted_luma_modes[] static
Initial value:
= {
    { "ignore",             NATIVE_SS_TED_LUM_IGNORE },
    { "Best cell colors",   NATIVE_SS_TED_LUM_DITHER },
    { NULL,                 -1 },
}
TED output driver Luma modes.
Referenced by create_screenshot_param_widget().
ted_luma_widget
GtkWidget* ted_luma_widget = NULL static
Screenshot "TED luma" widget reference.
Referenced by create_screenshot_param_widget().
undersize_modes
vice_gtk3_combo_entry_int_t undersize_modes[] static
Initial value:
= {
    { "scale up",   NATIVE_SS_UNDERSIZE_SCALE },
    { "bordize",    NATIVE_SS_UNDERSIZE_BORDERIZE },
    { NULL,         -1 }
}
List of 'undersize modes' for some screenshot output drivers.
Referenced by create_screenshot_param_widget().
undersize_widget
GtkWidget* undersize_widget = NULL static
Screenshot "Undersize" widget reference.
Referenced by create_screenshot_param_widget().
video_driver
const char* video_driver = NULL static
Referenced by create_video_widget(), on_save_video_filename(), on_video_driver_toggled(), and save_video_recording_handler().
video_driver_count
int video_driver_count = 0 static
Number of available video drivers.
Referenced by create_video_driver_list().
video_driver_index
int video_driver_index = 0 static
Index of currently selected video driver.
Referenced by create_video_widget(), and save_video_recording_handler().
video_driver_list
video_driver_info_t* video_driver_list = NULL static
List of available video drivers, gotten during runtime.
Referenced by create_screenshot_widget(), create_video_driver_list(), create_video_widget(), on_dialog_destroy(), on_save_screenshot_filename(), on_screenshot_driver_toggled(), save_screenshot_handler(), and save_video_recording_handler().
video_driver_options_grid
GtkWidget* video_driver_options_grid = NULL static
FFMPEG video driver options grid reference.
Referenced by create_video_widget(), and update_video_driver_options_grid().