vsid: arch/shared/archdep_boot_path.c File Reference
archdep_boot_path.c File Reference
Retrieve dirname of currently running binary.
#include "vice.h"
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "lib.h"
#include "archdep_program_path.h"
#include "archdep_boot_path.h"
Functions
const char * archdep_boot_path (void)
Get dirname of currently running binary.
void archdep_boot_path_free (void)
Free memory used by boot path.
Variables
static char * boot_path = NULL
Boot path.
Detailed Description
Retrieve dirname of currently running binary.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Get path to running executable, stripping executable name and extension.
OS support:
Linux
Windows
MacOS
BeOS/Haiku (untested)
Function Documentation
archdep_boot_path()
const char * archdep_boot_path (void)
Get dirname of currently running binary.
Retrieve the path to the running binary, excluding binary name.
Note
The path is allocated internally by VICE on the first call and should be freed on emulator shutdown with archdep_boot_path_free().
Returns
directory of running binary
< directory separator as an integer
Referenced by archdep_default_joymap_file_name(), archdep_default_portable_resource_file_name(), archdep_default_sysfile_pathlist(), archdep_get_vice_datadir(), archdep_get_vice_docsdir(), archdep_init(), archdep_user_cache_path(), archdep_user_config_path(), and archdep_user_state_path().
archdep_boot_path_free()
void archdep_boot_path_free (void)
Free memory used by boot path.
This must be called from the emulator shutdown code.
Referenced by archdep_shutdown().
Variable Documentation
boot_path
char* boot_path = NULL static
Boot path.
Heap allocated on the first call, must be free when exiting the program with lib_free().
See also
archdep_boot_path_free()
Referenced by archdep_boot_path(), archdep_boot_path_free(), and archdep_default_sysfile_pathlist().