x128: drive/ieee.h File Reference
ieee.h File Reference
#include "types.h"
Functions
int ieee_drive_resources_init (void)
void ieee_drive_resources_shutdown (void)
int ieee_drive_cmdline_options_init (void)
void ieee_drive_init (struct diskunit_context_s *drv)
void ieee_drive_shutdown (struct diskunit_context_s *drv)
void ieee_drive_reset (struct diskunit_context_s *drv)
void ieee_drive_mem_init (struct diskunit_context_s *drv, unsigned int type)
void ieee_drive_setup_context (struct diskunit_context_s *drv)
void ieee_drive_rom_load (void)
void ieee_drive_rom_setup_image (unsigned int dnr)
int ieee_drive_rom_check_loaded (unsigned int type)
void ieee_drive_rom_do_checksum (unsigned int dnr)
int ieee_drive_snapshot_read (struct diskunit_context_s *ctxptr, struct snapshot_s *s)
int ieee_drive_snapshot_write (struct diskunit_context_s *ctxptr, struct snapshot_s *s)
int ieee_drive_image_attach (struct disk_image_s *image, unsigned int unit, unsigned int drive)
int ieee_drive_image_detach (struct disk_image_s *image, unsigned int unit, unsigned int drive)
void ieee_drive_parallel_set_atn (int state, struct diskunit_context_s *drv)
Function Documentation
ieee_drive_cmdline_options_init()
int ieee_drive_cmdline_options_init (void)
Referenced by machine_drive_cmdline_options_init().
ieee_drive_image_attach()
int ieee_drive_image_attach (struct disk_image_s * image, unsigned int unit, unsigned int drive)
Referenced by machine_drive_image_attach().
ieee_drive_image_detach()
int ieee_drive_image_detach (struct disk_image_s * image, unsigned int unit, unsigned int drive)
Referenced by machine_drive_image_detach().
ieee_drive_init()
void ieee_drive_init (struct diskunit_context_s * drv)
Referenced by machine_drive_init().
ieee_drive_mem_init()
void ieee_drive_mem_init (struct diskunit_context_s * drv, unsigned int type)
Referenced by machine_drive_mem_init().
ieee_drive_parallel_set_atn()
void ieee_drive_parallel_set_atn (int state, struct diskunit_context_s * drv)
Referenced by parallel_atn_signal().
ieee_drive_reset()
void ieee_drive_reset (struct diskunit_context_s * drv)
Referenced by machine_drive_reset().
ieee_drive_resources_init()
int ieee_drive_resources_init (void)
Referenced by machine_drive_resources_init().
ieee_drive_resources_shutdown()
void ieee_drive_resources_shutdown (void)
Referenced by machine_drive_resources_shutdown().
ieee_drive_rom_check_loaded()
int ieee_drive_rom_check_loaded (unsigned int type)
Referenced by machine_drive_rom_check_loaded().
ieee_drive_rom_do_checksum()
void ieee_drive_rom_do_checksum (unsigned int dnr)
Referenced by machine_drive_rom_do_checksum().
ieee_drive_rom_load()
void ieee_drive_rom_load (void)
Referenced by machine_drive_rom_load().
ieee_drive_rom_setup_image()
void ieee_drive_rom_setup_image (unsigned int dnr)
Referenced by machine_drive_rom_setup_image().
ieee_drive_setup_context()
void ieee_drive_setup_context (struct diskunit_context_s * drv)
Referenced by machine_drive_setup_context().
ieee_drive_shutdown()
void ieee_drive_shutdown (struct diskunit_context_s * drv)
Referenced by machine_drive_shutdown().
ieee_drive_snapshot_read()
int ieee_drive_snapshot_read (struct diskunit_context_s * ctxptr, struct snapshot_s * s)
Referenced by machine_drive_snapshot_read().
ieee_drive_snapshot_write()
int ieee_drive_snapshot_write (struct diskunit_context_s * ctxptr, struct snapshot_s * s)
Referenced by machine_drive_snapshot_write().