vsid: serial/serial.c File Reference
serial.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include "log.h"
#include "machine-bus.h"
#include "printer.h"
#include "serial-trap.h"
#include "serial.h"
#include "traps.h"
#include "types.h"
Functions
int serial_init (const trap_t *trap_list)
void serial_shutdown (void)
int serial_install_traps (void)
int serial_remove_traps (void)
Variables
static int traps_installed = 0
Flag: Have traps been installed?
static const trap_t * serial_traps
Pointer to list of traps we are using.
static log_t serial_log = ((log_t)-1)
Logging goes here.
Function Documentation
serial_init()
int serial_init (const trap_t * trap_list)
serial_install_traps()
int serial_install_traps (void)
Referenced by serial_init().
serial_remove_traps()
int serial_remove_traps (void)
Referenced by serial_init().
serial_shutdown()
void serial_shutdown (void)
Referenced by machine_resources_shutdown().
Variable Documentation
serial_log
log_t serial_log = ((log_t)-1) static
Logging goes here.
Referenced by serial_init().
serial_traps
const trap_t* serial_traps static
Pointer to list of traps we are using.
Referenced by serial_init(), serial_install_traps(), and serial_remove_traps().
traps_installed
int traps_installed = 0 static
Flag: Have traps been installed?
Referenced by serial_install_traps(), and serial_remove_traps().