vsid: arch/gtk3/widgets/drivedoswidget.c File Reference
drivedoswidget.c File Reference
Drive DOS expansions widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "drive-check.h"
#include "drive.h"
#include "machine.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "drivedoswidget.h"
Data Structures
struct drive_dos_exp_s
DOS expansion entry in the list.
Typedefs
typedef struct drive_dos_exp_s drive_dos_exp_t
DOS expansion entry in the list.
Enumerations
enum {
COL_NAME ,
COL_INDEX ,
COL_COUNT
}
Combo box model columns.
Functions
static int get_unit_number (GtkWidget *self)
Forward declarations.
static int get_drive_type (GtkWidget *self)
Get drive type (called model in the UI)
static void on_combo_changed (GtkWidget *self, gpointer data)
static GtkListStore * create_combo_model (GtkWidget *self)
GtkWidget * drive_dos_widget_create_combo (int unit)
Create combo box to select drive DOS expansion.
static void disable_invalid_expansions (GtkWidget *self)
Disable invalid DOS expansions.
void drive_dos_widget_sync_combo (GtkWidget *widget)
Synchronize widget with the current machine configuration.
Variables
static const drive_dos_exp_t expansions []
List of possible expansions, terminated by .name == NULL.
Detailed Description
Drive DOS expansions widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Typedef Documentation
drive_dos_exp_t
typedef struct drive_dos_exp_s drive_dos_exp_t
DOS expansion entry in the list.
Enumeration Type Documentation
anonymous enum
anonymous enum
Combo box model columns.
Enumerator
COL_NAME
expansion name
COL_INDEX
index in the list of expansions
COL_COUNT
number of columns in the model
Function Documentation
create_combo_model()
static GtkListStore * create_combo_model (GtkWidget * self) static
Referenced by drive_dos_widget_create_combo(), and drive_dos_widget_sync_combo().
disable_invalid_expansions()
static void disable_invalid_expansions (GtkWidget * self) static
Disable invalid DOS expansions.
Disable all DOS expansions that are invalid for the current drive model.
Parameters
[in] self drive DOS expansion widget
Referenced by drive_dos_widget_sync_combo().
drive_dos_widget_create_combo()
GtkWidget * drive_dos_widget_create_combo (int unit)
Create combo box to select drive DOS expansion.
Create combo box that allows selecting a DOS expansion that is valid for the current unit's drive type.
Contains the following GObject keys:
UnitNumber: Drive unit number (8-11)
ModelDriveType: Drive type used for (re)construction of the model of the combo box, to avoid rebuilding the model on every sync() call
ChangedHandlerID: ID of the 'changed' event handler, used to block the changed event when calling sync()
Parameters
[in] unit drive unit number (8-11)
Returns
GtkComboBox
Referenced by create_c64_layout().
drive_dos_widget_sync_combo()
void drive_dos_widget_sync_combo (GtkWidget * widget)
Synchronize widget with the current machine configuration.
Update the available expansions in the combo box, disable any invalid DOS expansions for the current drive model.
Parameters
[in] widget drive DOS expansion widget
Referenced by drive_dos_widget_create_combo(), and on_model_changed().
get_drive_type()
static int get_drive_type (GtkWidget * self) static
Get drive type (called model in the UI)
Parameters
[in] self combo box
Returns
drive type
Referenced by create_combo_model(), disable_invalid_expansions(), drive_dos_widget_create_combo(), and drive_dos_widget_sync_combo().
get_unit_number()
static int get_unit_number (GtkWidget * self) static
Forward declarations.
Get drive unit number.
Parameters
[in] self combo box
Returns
unit number
Referenced by disable_invalid_expansions(), drive_dos_widget_sync_combo(), get_drive_type(), and on_combo_changed().
on_combo_changed()
static void on_combo_changed (GtkWidget * self, gpointer data) static
Referenced by drive_dos_widget_create_combo().
Variable Documentation
expansions
const drive_dos_exp_t expansions[] static
Initial value:
= {
    { "None",               NULL,               NULL },
    { "StarDOS",            "Drive%dStarDOS",   drive_check_stardos },
    { "Supercard+",         "Drive%dSuperCard", drive_check_supercard },
    { NULL,                 NULL,               NULL }
}
List of possible expansions, terminated by .name == NULL.
Referenced by create_combo_model(), disable_invalid_expansions(), drive_dos_widget_sync_combo(), and on_combo_changed().