vsid: lib/p64/p64.c File Reference
p64.c File Reference
#include "p64.h"
Data Structures
struct TP64RangeCoder
Macros
#define ModelPosition 0
#define ModelStrength 4
#define ModelPositionFlag 8
#define ModelStrengthFlag 9
#define ProbabilityModelCount 10
#define ReadBit(Model) (RangeCoderProbabilityStates[Model] = P64RangeCoderDecodeBit(&RangeCoderInstance, RangeCoderProbabilities + (RangeCoderProbabilityOffsets[Model] + RangeCoderProbabilityStates[Model]), 4))
#define ReadDWord(Model)
#define WriteBit(Model, BitValue) RangeCoderProbabilityStates[Model] = P64RangeCoderEncodeBit(&RangeCoderInstance, RangeCoderProbabilities + (RangeCoderProbabilityOffsets[Model] + RangeCoderProbabilityStates[Model]), 4, BitValue)
#define WriteDWord(Model, DWordValue)
#define WriteChunk()
Typedefs
typedef p64_uint32_t * PP64RangeCoderProbabilities
typedef TP64RangeCoder * PP64RangeCoder
Functions
static p64_uint32_t P64CRC32 (p64_uint8_t *Data, p64_uint32_t Len)
static PP64RangeCoderProbabilities P64RangeCoderProbabilitiesAllocate (p64_uint32_t Count)
static void P64RangeCoderProbabilitiesFree (PP64RangeCoderProbabilities Probabilities)
static void P64RangeCoderProbabilitiesReset (PP64RangeCoderProbabilities Probabilities, p64_uint32_t Count)
static p64_uint8_t P64RangeCoderRead (PP64RangeCoder Instance)
static void P64RangeCoderWrite (PP64RangeCoder Instance, p64_uint8_t Value)
static void P64RangeCoderInit (PP64RangeCoder Instance)
static void P64RangeCoderStart (PP64RangeCoder Instance)
static void P64RangeCoderFlush (PP64RangeCoder Instance)
static void P64RangeCoderEncodeNormalize (PP64RangeCoder Instance)
static p64_uint32_t P64RangeCoderEncodeBit (PP64RangeCoder Instance, p64_uint32_t *Probability, p64_uint32_t Shift, p64_uint32_t BitValue)
static void P64RangeCoderDecodeNormalize (PP64RangeCoder Instance)
unused right now (2017-04-17, compyx)
static p64_uint32_t P64RangeCoderDecodeBit (PP64RangeCoder Instance, p64_uint32_t *Probability, p64_uint32_t Shift)
void P64MemoryStreamCreate (PP64MemoryStream Instance)
unused right now (2017-04-17, compyx)
void P64MemoryStreamDestroy (PP64MemoryStream Instance)
void P64MemoryStreamClear (PP64MemoryStream Instance)
p64_uint32_t P64MemoryStreamSeek (PP64MemoryStream Instance, p64_uint32_t Position)
p64_uint32_t P64MemoryStreamRead (PP64MemoryStream Instance, p64_uint8_t *Data, p64_uint32_t Count)
p64_uint32_t P64MemoryStreamWrite (PP64MemoryStream Instance, p64_uint8_t *Data, p64_uint32_t Count)
p64_int32_t P64MemoryStreamReadByte (PP64MemoryStream Instance, p64_uint8_t *Data)
p64_int32_t P64MemoryStreamReadWord (PP64MemoryStream Instance, p64_uint16_t *Data)
p64_int32_t P64MemoryStreamReadDWord (PP64MemoryStream Instance, p64_uint32_t *Data)
p64_int32_t P64MemoryStreamWriteByte (PP64MemoryStream Instance, p64_uint8_t *Data)
p64_int32_t P64MemoryStreamWriteWord (PP64MemoryStream Instance, p64_uint16_t *Data)
p64_int32_t P64MemoryStreamWriteDWord (PP64MemoryStream Instance, p64_uint32_t *Data)
p64_uint32_t P64MemoryStreamAssign (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
p64_uint32_t P64MemoryStreamAppend (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
p64_uint32_t P64MemoryStreamAppendFrom (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
p64_uint32_t P64MemoryStreamAppendFromCount (PP64MemoryStream Instance, PP64MemoryStream FromInstance, p64_uint32_t Count)
void P64PulseStreamCreate (PP64PulseStream Instance)
void P64PulseStreamDestroy (PP64PulseStream Instance)
void P64PulseStreamClear (PP64PulseStream Instance)
p64_int32_t P64PulseStreamAllocatePulse (PP64PulseStream Instance)
void P64PulseStreamFreePulse (PP64PulseStream Instance, p64_int32_t Index)
void P64PulseStreamAddPulse (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Strength)
void P64PulseStreamRemovePulses (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Count)
void P64PulseStreamRemovePulse (PP64PulseStream Instance, p64_uint32_t Position)
p64_uint32_t P64PulseStreamDeltaPositionToNextPulse (PP64PulseStream Instance, p64_uint32_t Position)
p64_uint32_t P64PulseStreamGetNextPulse (PP64PulseStream Instance, p64_uint32_t Position)
p64_uint32_t P64PulseStreamGetPulseCount (PP64PulseStream Instance)
p64_uint32_t P64PulseStreamGetPulse (PP64PulseStream Instance, p64_uint32_t Position)
void P64PulseStreamSetPulse (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Strength)
void P64PulseStreamSeek (PP64PulseStream Instance, p64_uint32_t Position)
void P64PulseStreamConvertFromGCR (PP64PulseStream Instance, p64_uint8_t *Bytes, p64_uint32_t Len)
void P64PulseStreamConvertToGCR (PP64PulseStream Instance, p64_uint8_t *Bytes, p64_uint32_t Len)
p64_uint32_t P64PulseStreamConvertToGCRWithLogic (PP64PulseStream Instance, p64_uint8_t *Bytes, p64_uint32_t Len, p64_uint32_t SpeedZone)
p64_uint32_t P64PulseStreamReadFromStream (PP64PulseStream Instance, PP64MemoryStream Stream)
p64_uint32_t P64PulseStreamWriteToStream (PP64PulseStream Instance, PP64MemoryStream Stream)
void P64ImageCreate (PP64Image Instance)
void P64ImageDestroy (PP64Image Instance)
void P64ImageClear (PP64Image Instance)
p64_uint32_t P64ImageReadFromStream (PP64Image Instance, PP64MemoryStream Stream)
p64_uint32_t P64ImageWriteToStream (PP64Image Instance, PP64MemoryStream Stream)
Variables
const p64_uint32_t ProbabilityCounts [10] = {65536, 65536, 65536, 65536, 65536, 65536, 65536, 65536, 4, 4}
Macro Definition Documentation
ModelPosition
#define ModelPosition 0
ModelPositionFlag
#define ModelPositionFlag 8
ModelStrength
#define ModelStrength 4
ModelStrengthFlag
#define ModelStrengthFlag 9
ProbabilityModelCount
#define ProbabilityModelCount 10
ReadBit
#define ReadBit (Model) (RangeCoderProbabilityStates[Model] = P64RangeCoderDecodeBit(&RangeCoderInstance, RangeCoderProbabilities + (RangeCoderProbabilityOffsets[Model] + RangeCoderProbabilityStates[Model]), 4))
ReadDWord
#define ReadDWord (Model)
Value:
          { \
            p64_uint32_t ByteValue, ByteIndex, Context; \
            p64_int32_t Bit; \
                      result = 0; \
                      for (ByteIndex = 0; ByteIndex < 4; ByteIndex++) { \
                          Context = 1; \
                          for (Bit = 7; Bit >= 0; Bit--) { \
                              Context = (Context << 1) | P64RangeCoderDecodeBit(&RangeCoderInstance, RangeCoderProbabilities + (RangeCoderProbabilityOffsets[Model + ByteIndex] + (((RangeCoderProbabilityStates[Model + ByteIndex] << 8) | Context) & 0xffffUL)), 4); \
                          } \
                          ByteValue = Context & 0xffUL; \
                          RangeCoderProbabilityStates[Model + ByteIndex] = ByteValue; \
                          result |= (p64_uint32_t)(((ByteValue & 0xffUL) << (ByteIndex << 3))); \
            } \
                    } \
WriteBit
#define WriteBit (Model, BitValue) RangeCoderProbabilityStates[Model] = P64RangeCoderEncodeBit(&RangeCoderInstance, RangeCoderProbabilities + (RangeCoderProbabilityOffsets[Model] + RangeCoderProbabilityStates[Model]), 4, BitValue)
WriteChunk
#define WriteChunk ()
Value:
{ \
    WriteChunkResult = 0; \
    Size = ChunkMemoryStream.Size; \
    Checksum = (ChunkMemoryStream.Size > 0) ? P64CRC32(ChunkMemoryStream.Data,ChunkMemoryStream.Size) : 0; \
    if (P64MemoryStreamWrite(&ChunksMemoryStream, (void*)&ChunkSignature, sizeof(TP64ChunkSignature)) == sizeof(TP64ChunkSignature)) { \
        if (P64MemoryStreamWriteDWord(&ChunksMemoryStream, &Size)) { \
            if (P64MemoryStreamWriteDWord(&ChunksMemoryStream, &Checksum)) { \
                if (ChunkMemoryStream.Size == 0) { \
                    WriteChunkResult = 1; \
                }else{ \
                    if (P64MemoryStreamSeek(&ChunkMemoryStream, 0) == 0) { \
                        if (P64MemoryStreamAppendFromCount(&ChunksMemoryStream, &ChunkMemoryStream, ChunkMemoryStream.Size) == ChunkMemoryStream.Size) { \
                            WriteChunkResult = 1; \
                        } \
                    } \
          } \
            } \
        } \
    } \
}
WriteDWord
#define WriteDWord (Model, DWordValue)
Value:
      { \
        p64_uint32_t ByteValue, ByteIndex, Context, Value; \
        p64_int32_t Bit; \
        Value = DWordValue; \
               for (ByteIndex = 0; ByteIndex < 4; ByteIndex++) { \
                  ByteValue = (Value >> (ByteIndex << 3)) & 0xffUL; \
                  Context = 1; \
                  for (Bit = 7; Bit >= 0; Bit--) { \
                      Context = (Context << 1) | P64RangeCoderEncodeBit(&RangeCoderInstance, RangeCoderProbabilities + (RangeCoderProbabilityOffsets[Model + ByteIndex] + (((RangeCoderProbabilityStates[Model+ByteIndex] << 8) | Context) & 0xffffUL)), 4, (ByteValue >> Bit) & 1); \
                  } \
                  RangeCoderProbabilityStates[Model + ByteIndex] = ByteValue; \
              }    \
            }
Typedef Documentation
PP64RangeCoder
typedef TP64RangeCoder* PP64RangeCoder
PP64RangeCoderProbabilities
typedef p64_uint32_t* PP64RangeCoderProbabilities
Function Documentation
P64CRC32()
static p64_uint32_t P64CRC32 (p64_uint8_t * Data, p64_uint32_t Len) static
Referenced by P64ImageReadFromStream(), and P64ImageWriteToStream().
P64ImageClear()
void P64ImageClear (PP64Image Instance)
Referenced by P64ImageCreate(), and P64ImageReadFromStream().
P64ImageCreate()
void P64ImageCreate (PP64Image Instance)
Referenced by drive_init(), fsimage_create_p64(), and vdrive_internal_open_fsimage().
P64ImageDestroy()
void P64ImageDestroy (PP64Image Instance)
P64ImageReadFromStream()
p64_uint32_t P64ImageReadFromStream (PP64Image Instance, PP64MemoryStream Stream)
Referenced by drive_snapshot_read_p64image_module(), and fsimage_read_p64_image().
P64ImageWriteToStream()
p64_uint32_t P64ImageWriteToStream (PP64Image Instance, PP64MemoryStream Stream)
Referenced by drive_snapshot_write_p64image_module(), fsimage_create_p64(), and fsimage_write_p64_image().
P64MemoryStreamAppend()
p64_uint32_t P64MemoryStreamAppend (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
P64MemoryStreamAppendFrom()
p64_uint32_t P64MemoryStreamAppendFrom (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
P64MemoryStreamAppendFromCount()
p64_uint32_t P64MemoryStreamAppendFromCount (PP64MemoryStream Instance, PP64MemoryStream FromInstance, p64_uint32_t Count)
Referenced by P64ImageReadFromStream(), and P64ImageWriteToStream().
P64MemoryStreamAssign()
p64_uint32_t P64MemoryStreamAssign (PP64MemoryStream Instance, PP64MemoryStream FromInstance)
P64MemoryStreamClear()
void P64MemoryStreamClear (PP64MemoryStream Instance)
Referenced by drive_snapshot_read_p64image_module(), drive_snapshot_write_p64image_module(), fsimage_create_p64(), and fsimage_write_p64_image().
P64MemoryStreamCreate()
void P64MemoryStreamCreate (PP64MemoryStream Instance)
unused right now (2017-04-17, compyx)
unused right now (2017-04-17, compyx)
unused right now (2017-04-17, compyx)
Referenced by drive_snapshot_read_p64image_module(), drive_snapshot_write_p64image_module(), fsimage_create_p64(), fsimage_read_p64_image(), fsimage_write_p64_image(), P64ImageReadFromStream(), and P64ImageWriteToStream().
P64MemoryStreamDestroy()
void P64MemoryStreamDestroy (PP64MemoryStream Instance)
Referenced by drive_snapshot_read_p64image_module(), drive_snapshot_write_p64image_module(), fsimage_create_p64(), fsimage_read_p64_image(), fsimage_write_p64_image(), P64ImageReadFromStream(), and P64ImageWriteToStream().
P64MemoryStreamRead()
p64_uint32_t P64MemoryStreamRead (PP64MemoryStream Instance, p64_uint8_t * Data, p64_uint32_t Count)
Referenced by P64ImageReadFromStream(), P64MemoryStreamReadByte(), and P64PulseStreamReadFromStream().
P64MemoryStreamReadByte()
p64_int32_t P64MemoryStreamReadByte (PP64MemoryStream Instance, p64_uint8_t * Data)
Referenced by P64MemoryStreamReadWord().
P64MemoryStreamReadDWord()
p64_int32_t P64MemoryStreamReadDWord (PP64MemoryStream Instance, p64_uint32_t * Data)
Referenced by P64ImageReadFromStream(), and P64PulseStreamReadFromStream().
P64MemoryStreamReadWord()
p64_int32_t P64MemoryStreamReadWord (PP64MemoryStream Instance, p64_uint16_t * Data)
Referenced by P64MemoryStreamReadDWord().
P64MemoryStreamSeek()
p64_uint32_t P64MemoryStreamSeek (PP64MemoryStream Instance, p64_uint32_t Position)
Referenced by drive_snapshot_read_p64image_module(), fsimage_read_p64_image(), P64ImageReadFromStream(), and P64ImageWriteToStream().
P64MemoryStreamWrite()
p64_uint32_t P64MemoryStreamWrite (PP64MemoryStream Instance, p64_uint8_t * Data, p64_uint32_t Count)
Referenced by drive_snapshot_read_p64image_module(), fsimage_read_p64_image(), P64ImageWriteToStream(), P64MemoryStreamAppend(), P64MemoryStreamAppendFrom(), P64MemoryStreamAppendFromCount(), P64MemoryStreamWriteByte(), and P64PulseStreamWriteToStream().
P64MemoryStreamWriteByte()
p64_int32_t P64MemoryStreamWriteByte (PP64MemoryStream Instance, p64_uint8_t * Data)
Referenced by P64MemoryStreamWriteWord().
P64MemoryStreamWriteDWord()
p64_int32_t P64MemoryStreamWriteDWord (PP64MemoryStream Instance, p64_uint32_t * Data)
Referenced by P64ImageWriteToStream(), and P64PulseStreamWriteToStream().
P64MemoryStreamWriteWord()
p64_int32_t P64MemoryStreamWriteWord (PP64MemoryStream Instance, p64_uint16_t * Data)
Referenced by P64MemoryStreamWriteDWord().
P64PulseStreamAddPulse()
void P64PulseStreamAddPulse (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Strength)
Referenced by P64PulseStreamConvertFromGCR(), P64PulseStreamReadFromStream(), P64PulseStreamSetPulse(), and rotation_1541_p64().
P64PulseStreamAllocatePulse()
p64_int32_t P64PulseStreamAllocatePulse (PP64PulseStream Instance)
Referenced by P64PulseStreamAddPulse().
P64PulseStreamClear()
void P64PulseStreamClear (PP64PulseStream Instance)
Referenced by P64ImageClear(), P64PulseStreamConvertFromGCR(), and P64PulseStreamDestroy().
P64PulseStreamConvertFromGCR()
void P64PulseStreamConvertFromGCR (PP64PulseStream Instance, p64_uint8_t * Bytes, p64_uint32_t Len)
Referenced by fsimage_create_p64(), fsimage_p64_write_half_track(), and fsimage_p64_write_track().
P64PulseStreamConvertToGCR()
void P64PulseStreamConvertToGCR (PP64PulseStream Instance, p64_uint8_t * Bytes, p64_uint32_t Len)
P64PulseStreamConvertToGCRWithLogic()
p64_uint32_t P64PulseStreamConvertToGCRWithLogic (PP64PulseStream Instance, p64_uint8_t * Bytes, p64_uint32_t Len, p64_uint32_t SpeedZone)
Referenced by fsimage_p64_read_half_track().
P64PulseStreamCreate()
void P64PulseStreamCreate (PP64PulseStream Instance)
Referenced by P64ImageCreate().
P64PulseStreamDeltaPositionToNextPulse()
p64_uint32_t P64PulseStreamDeltaPositionToNextPulse (PP64PulseStream Instance, p64_uint32_t Position)
P64PulseStreamDestroy()
void P64PulseStreamDestroy (PP64PulseStream Instance)
Referenced by P64ImageDestroy().
P64PulseStreamFreePulse()
void P64PulseStreamFreePulse (PP64PulseStream Instance, p64_int32_t Index)
Referenced by P64PulseStreamRemovePulse(), P64PulseStreamRemovePulses(), and rotation_1541_p64().
P64PulseStreamGetNextPulse()
p64_uint32_t P64PulseStreamGetNextPulse (PP64PulseStream Instance, p64_uint32_t Position)
P64PulseStreamGetPulse()
p64_uint32_t P64PulseStreamGetPulse (PP64PulseStream Instance, p64_uint32_t Position)
P64PulseStreamGetPulseCount()
p64_uint32_t P64PulseStreamGetPulseCount (PP64PulseStream Instance)
P64PulseStreamReadFromStream()
p64_uint32_t P64PulseStreamReadFromStream (PP64PulseStream Instance, PP64MemoryStream Stream)
Referenced by P64ImageReadFromStream().
P64PulseStreamRemovePulse()
void P64PulseStreamRemovePulse (PP64PulseStream Instance, p64_uint32_t Position)
Referenced by P64PulseStreamSetPulse().
P64PulseStreamRemovePulses()
void P64PulseStreamRemovePulses (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Count)
P64PulseStreamSeek()
void P64PulseStreamSeek (PP64PulseStream Instance, p64_uint32_t Position)
P64PulseStreamSetPulse()
void P64PulseStreamSetPulse (PP64PulseStream Instance, p64_uint32_t Position, p64_uint32_t Strength)
P64PulseStreamWriteToStream()
p64_uint32_t P64PulseStreamWriteToStream (PP64PulseStream Instance, PP64MemoryStream Stream)
Referenced by P64ImageWriteToStream().
P64RangeCoderDecodeBit()
static p64_uint32_t P64RangeCoderDecodeBit (PP64RangeCoder Instance, p64_uint32_t * Probability, p64_uint32_t Shift) static
P64RangeCoderDecodeNormalize()
static void P64RangeCoderDecodeNormalize (PP64RangeCoder Instance) static
unused right now (2017-04-17, compyx)
Referenced by P64RangeCoderDecodeBit().
P64RangeCoderEncodeBit()
static p64_uint32_t P64RangeCoderEncodeBit (PP64RangeCoder Instance, p64_uint32_t * Probability, p64_uint32_t Shift, p64_uint32_t BitValue) static
P64RangeCoderEncodeNormalize()
static void P64RangeCoderEncodeNormalize (PP64RangeCoder Instance) static
Referenced by P64RangeCoderEncodeBit().
P64RangeCoderFlush()
static void P64RangeCoderFlush (PP64RangeCoder Instance) static
Referenced by P64PulseStreamWriteToStream().
P64RangeCoderInit()
static void P64RangeCoderInit (PP64RangeCoder Instance) static
Referenced by P64PulseStreamReadFromStream(), and P64PulseStreamWriteToStream().
P64RangeCoderProbabilitiesAllocate()
static PP64RangeCoderProbabilities P64RangeCoderProbabilitiesAllocate (p64_uint32_t Count) static
Referenced by P64PulseStreamReadFromStream(), and P64PulseStreamWriteToStream().
P64RangeCoderProbabilitiesFree()
static void P64RangeCoderProbabilitiesFree (PP64RangeCoderProbabilities Probabilities) static
Referenced by P64PulseStreamReadFromStream(), and P64PulseStreamWriteToStream().
P64RangeCoderProbabilitiesReset()
static void P64RangeCoderProbabilitiesReset (PP64RangeCoderProbabilities Probabilities, p64_uint32_t Count) static
Referenced by P64PulseStreamReadFromStream(), and P64PulseStreamWriteToStream().
P64RangeCoderRead()
static p64_uint8_t P64RangeCoderRead (PP64RangeCoder Instance) static
Referenced by P64RangeCoderDecodeNormalize(), and P64RangeCoderStart().
P64RangeCoderStart()
static void P64RangeCoderStart (PP64RangeCoder Instance) static
Referenced by P64PulseStreamReadFromStream().
P64RangeCoderWrite()
static void P64RangeCoderWrite (PP64RangeCoder Instance, p64_uint8_t Value) static
Referenced by P64RangeCoderEncodeNormalize(), and P64RangeCoderFlush().
Variable Documentation
ProbabilityCounts
const p64_uint32_t ProbabilityCounts[10] = {65536, 65536, 65536, 65536, 65536, 65536, 65536, 65536, 4, 4}
Referenced by P64PulseStreamReadFromStream(), and P64PulseStreamWriteToStream().