x128: arch/gtk3/widgets/vsidtuneinfowidget.h File Reference
vsidtuneinfowidget.h File Reference
GTK3 tune info widget for VSID - header.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdbool.h>
Functions
GtkWidget * vsid_tune_info_widget_create (void)
Create widget to show tune information.
void vsid_tune_info_widget_update (void)
Update play time based ui elements.
void vsid_tune_info_widget_set_name (const char *name)
Set tune name.
void vsid_tune_info_widget_set_author (const char *author)
Set author.
void vsid_tune_info_widget_set_copyright (const char *copyright)
Set copyright info string.
void vsid_tune_info_widget_set_tune_count (int count)
Set number of tunes.
void vsid_tune_info_widget_set_tune_default (int num)
Set default tune.
void vsid_tune_info_widget_set_tune_current (int num)
Set current tune.
void vsid_tune_info_widget_set_model (int model)
Set SID model.
void vsid_tune_info_widget_set_sync (int sync)
Set sync factor.
void vsid_tune_info_widget_set_irq (const char *irq)
Set IRQ source.
void vsid_tune_info_widget_set_time (unsigned int sec)
Set current run time.
void vsid_tune_info_widget_set_driver_addr (uint16_t addr)
Set driver address.
void vsid_tune_info_widget_set_load_addr (uint16_t addr)
Set load address.
void vsid_tune_info_widget_set_init_addr (uint16_t addr)
Set init routine address.
void vsid_tune_info_widget_set_play_addr (uint16_t addr)
Set play routine address.
void vsid_tune_info_widget_set_data_size (uint16_t size)
Set size of SID on actual machine.
bool vsid_tune_info_widget_set_song_lengths (const char *sid)
Set song lengths for each sub-tune.
bool vsid_tune_info_widget_set_song_lengths_md5 (const char *digest)
int vsid_tune_info_widget_get_song_lengths (long **dest)
Retrieve songlengths.
gchar * convert_to_utf8 (const char *s)
Convert a string from a SID header field to UTF-8.
Detailed Description
GTK3 tune info widget for VSID - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
convert_to_utf8()
gchar * convert_to_utf8 (const char * s)
Convert a string from a SID header field to UTF-8.
Todo:
move and rename
Parameters
[in] s string from SID header, nul-terminated
Returns
UTF-8 encoded string, or the original when conversion failed
Note
the string returned needs to be freed with g_free()
Referenced by stil_widget_populate(), vsid_playlist_append_file(), vsid_tune_info_widget_set_author(), vsid_tune_info_widget_set_copyright(), and vsid_tune_info_widget_set_name().
vsid_tune_info_widget_create()
GtkWidget * vsid_tune_info_widget_create (void)
Create widget to show tune information.
Returns
GtkGrid
Referenced by vsid_main_widget_create().
vsid_tune_info_widget_get_song_lengths()
int vsid_tune_info_widget_get_song_lengths (long ** dest)
Retrieve songlengths.
Get the list of subtunes lengths in seconds.
Parameters
[out] dest object to store pointer to list
Returns
number of items in the list
vsid_tune_info_widget_set_author()
void vsid_tune_info_widget_set_author (const char * name)
Set author.
Parameters
[in] name author name
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_copyright()
void vsid_tune_info_widget_set_copyright (const char * name)
Set copyright info string.
Parameters
[in] name copyright string
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_data_size()
void vsid_tune_info_widget_set_data_size (uint16_t size)
Set size of SID on actual machine.
Parameters
[in] size size of SID
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_driver_addr()
void vsid_tune_info_widget_set_driver_addr (uint16_t addr)
Set driver address.
Parameters
[in] addr driver address
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_init_addr()
void vsid_tune_info_widget_set_init_addr (uint16_t addr)
Set init routine address.
Parameters
[in] addr init routine address
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_irq()
void vsid_tune_info_widget_set_irq (const char * irq)
Set IRQ source.
Parameters
[in] irq irq source string
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_load_addr()
void vsid_tune_info_widget_set_load_addr (uint16_t addr)
Set load address.
Parameters
[in] addr load address
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_model()
void vsid_tune_info_widget_set_model (int model)
Set SID model.
Parameters
[in] model model ID (0 = 6581, 1 = 8580)
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_name()
void vsid_tune_info_widget_set_name (const char * name)
Set tune name.
Parameters
[in] name tune name
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_play_addr()
void vsid_tune_info_widget_set_play_addr (uint16_t addr)
Set play routine address.
Parameters
[in] addr play routine address
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_song_lengths()
bool vsid_tune_info_widget_set_song_lengths (const char * psid)
Set song lengths for each sub-tune.
Parameters
[in] psid SID file
Returns
true if a songlengths entry was found
vsid_tune_info_widget_set_song_lengths_md5()
bool vsid_tune_info_widget_set_song_lengths_md5 (const char * digest)
Referenced by ui_vsid_window_load_psid(), and vsid_main_widget_create().
vsid_tune_info_widget_set_sync()
void vsid_tune_info_widget_set_sync (int sync)
Set sync factor.
Parameters
[in] sync sync factor (0 = 60Hz/NTSC, 1 = 50Hz/PAL)
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_time()
void vsid_tune_info_widget_set_time (unsigned int dsec)
Set current run time.
Also sets progress in current tune and handles skipping to the next tune if HVSC SLDB is found. So it probably does too much.
Parameters
[in] dsec run time in decaseconds
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_tune_count()
void vsid_tune_info_widget_set_tune_count (int num)
Set number of tunes.
Parameters
[in] num tune count
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_tune_current()
void vsid_tune_info_widget_set_tune_current (int num)
Set current tune.
Parameters
[in] num tune number
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_tune_default()
void vsid_tune_info_widget_set_tune_default (int num)
Set default tune.
Parameters
[in] num tune number
Referenced by vsid_ui_update().
vsid_tune_info_widget_update()
void vsid_tune_info_widget_update (void)
Update play time based ui elements.
This function also determines if vsid should play the next subtune or play the next SID in the playlist, so it's probably doing too much or just misnamed.
Referenced by vsid_main_widget_update().