x128: gfxoutputdrv/nativedrv.c File Reference
nativedrv.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "mem.h"
#include "gfxoutput.h"
#include "nativedrv.h"
#include "palette.h"
#include "resources.h"
#include "screenshot.h"
#include "types.h"
#include "uiapi.h"
#include "util.h"
#include "vsync.h"
Macros
#define DBG(_x_)
#define VIC_NUM_COLORS 16
#define VICII_NUM_COLORS 16
Functions
native_data_t * native_borderize_colormap (native_data_t *source, uint8_t bordercolor, int xsize, int ysize)
void native_smooth_scroll_borderize_colormap(native_data_t *source, uint8_t bordercolor, uint8_t xcover, uint8_t ycover);
native_data_t * native_crop_and_borderize_colormap (native_data_t *source, uint8_t bordercolor, int xsize, int ysize, int oversize_handling)
native_data_t * native_scale_colormap (native_data_t *source, int xsize, int ysize)
native_data_t * native_resize_colormap (native_data_t *source, int xsize, int ysize, uint8_t bordercolor, int oversize_handling, int undersize_handling)
scale and/or crop and/or borderize according to the options
native_color_sort_t * native_sort_colors_colormap (native_data_t *source, int color_amount)
int native_is_colormap_multicolor (native_data_t *source)
returns 1 if any 8x8 cell contains more than two colors
static uint8_t vicii_color_to_bw (uint8_t color)
void vicii_color_to_vicii_bw_colormap (native_data_t *source)
static uint8_t vicii_color_to_gray (uint8_t color)
void vicii_color_to_vicii_gray_colormap (native_data_t *source)
static uint8_t vicii_color_to_nearest_color (uint8_t color, native_color_sort_t *altcolors)
altcolors[n].color == 255 marks the end of the list
void vicii_color_to_nearest_vicii_color_colormap (native_data_t *source, native_color_sort_t *colors)
static uint8_t vic_color_to_nearest_color (uint8_t color, native_color_sort_t *altcolors)
altcolors[n].color == 255 marks the end of the list
void vic_color_to_nearest_vic_color_colormap (native_data_t *source, native_color_sort_t *colors)
static native_data_t * native_generic_render (screenshot_t *screenshot, const char *filename, int xsize, int ysize, int xstep)
native_data_t * native_vicii_render (screenshot_t *screenshot, const char *filename)
native_data_t * native_ted_render (screenshot_t *screenshot, const char *filename)
native_data_t * native_vic_render (screenshot_t *screenshot, const char *filename)
native_data_t * native_crtc_render (screenshot_t *screenshot, const char *filename)
native_data_t * native_vdc_render (screenshot_t *screenshot, const char *filename)
static uint8_t ted_to_vicii_color (uint8_t color)
static uint8_t ted_to_vic_color (uint8_t color)
static uint8_t ted_lum_to_vicii_color (uint8_t color, uint8_t lum)
void ted_color_to_vicii_color_colormap (native_data_t *source, int ted_lum_handling)
static uint8_t ted_lum_to_vic_color (uint8_t color, uint8_t lum)
void ted_color_to_vic_color_colormap (native_data_t *source, int ted_lum_handling)
static uint8_t vic_to_vicii_color (uint8_t color)
void vic_color_to_vicii_color_colormap (native_data_t *source)
static uint8_t vicii_to_vic_color (uint8_t color)
void vicii_color_to_vic_color_colormap (native_data_t *source)
static uint8_t vdc_to_vicii_color (uint8_t color)
void vdc_color_to_vicii_color_colormap (native_data_t *source)
static uint8_t vdc_to_vic_color (uint8_t color)
void vdc_color_to_vic_color_colormap (native_data_t *source)
Variables
static uint8_t vicii_color_bw_translate [16]
static uint8_t vicii_color_gray_translate [16]
static uint8_t vicii_closest_color [16][16]
most similar -> least similar color
static uint8_t vic_closest_color [16][16]
most similar -> least similar color
static uint8_t ted_vicii_translate [16]
static uint8_t ted_vic_translate [16]
static uint8_t ted_lum_vicii_translate [16 *8]
static uint8_t ted_lum_vic_translate [16 *8]
static uint8_t vic_vicii_translate [16]
static uint8_t vicii_vic_translate [16]
static uint8_t vdc_vicii_translate [16]
static uint8_t vdc_vic_translate [16]
Macro Definition Documentation
DBG
#define DBG (_x_)
VIC_NUM_COLORS
#define VIC_NUM_COLORS 16
VICII_NUM_COLORS
#define VICII_NUM_COLORS 16
Function Documentation
native_borderize_colormap()
native_data_t * native_borderize_colormap (native_data_t * source, uint8_t bordercolor, int xsize, int ysize)
void native_smooth_scroll_borderize_colormap(native_data_t *source, uint8_t bordercolor, uint8_t xcover, uint8_t ycover);
Referenced by native_resize_colormap().
native_crop_and_borderize_colormap()
native_data_t * native_crop_and_borderize_colormap (native_data_t * source, uint8_t bordercolor, int xsize, int ysize, int oversize_handling)
Referenced by native_resize_colormap().
native_crtc_render()
native_data_t * native_crtc_render (screenshot_t * screenshot, const char * filename)
Todo:
FIXME: screenshot->gfx_position.x/y does not match actual black border
"hre" and "petdww_ram" is broken
Todo:
FIXME: handle inter-character gap
Todo:
FIXME: If we're in an 80 column screen we need to horizontally double all pixels, since DWW only has 40 characters worth of pixels.
Todo:
FIXME: this should be defined elsewhere in the crtc code
Referenced by artstudio_crtc_save(), koala_crtc_save(), and minipaint_crtc_save().
native_generic_render()
static native_data_t * native_generic_render (screenshot_t * screenshot, const char * filename, int xsize, int ysize, int xstep) static
Referenced by native_crtc_render(), native_ted_render(), native_vdc_render(), native_vic_render(), and native_vicii_render().
native_is_colormap_multicolor()
int native_is_colormap_multicolor (native_data_t * source)
returns 1 if any 8x8 cell contains more than two colors
Referenced by native_generic_render().
native_resize_colormap()
native_data_t * native_resize_colormap (native_data_t * source, int xsize, int ysize, uint8_t bordercolor, int oversize_handling, int undersize_handling)
scale and/or crop and/or borderize according to the options
Referenced by artstudio_crtc_save(), artstudio_vdc_save(), artstudio_vic_save(), koala_crtc_save(), koala_vdc_save(), koala_vic_save(), minipaint_crtc_save(), minipaint_ted_save(), minipaint_vdc_save(), minipaint_vic_save(), and minipaint_vicii_save().
native_scale_colormap()
native_data_t * native_scale_colormap (native_data_t * source, int xsize, int ysize)
Referenced by native_resize_colormap().
native_sort_colors_colormap()
native_color_sort_t * native_sort_colors_colormap (native_data_t * source, int color_amount)
Referenced by artstudio_check_and_correct_cell(), artstudio_multicolor_render(), artstudio_vic_save(), koala_check_and_correct_cell(), koala_find_bgcolor(), minipaint_check_and_correct_cell(), minipaint_find_hires_colors(), minipaint_find_shared_colors_pass(), and native_is_colormap_multicolor().
native_ted_render()
native_data_t * native_ted_render (screenshot_t * screenshot, const char * filename)
Referenced by artstudio_ted_save(), koala_ted_save(), and minipaint_ted_save().
native_vdc_render()
native_data_t * native_vdc_render (screenshot_t * screenshot, const char * filename)
Todo:
FIXME: screenshot->gfx_position.x/y does not match actual black border
Todo:
FIXME: this should be set elsewhere in the vdc code
Todo:
FIXME: is this correct?
Referenced by artstudio_vdc_save(), koala_vdc_save(), and minipaint_vdc_save().
native_vic_render()
native_data_t * native_vic_render (screenshot_t * screenshot, const char * filename)
Referenced by artstudio_vic_save(), koala_vic_save(), and minipaint_vic_save().
native_vicii_render()
native_data_t * native_vicii_render (screenshot_t * screenshot, const char * filename)
Referenced by artstudio_vicii_save(), koala_vicii_save(), and minipaint_vicii_save().
ted_color_to_vic_color_colormap()
void ted_color_to_vic_color_colormap (native_data_t * source, int ted_lum_handling)
Referenced by minipaint_ted_save().
ted_color_to_vicii_color_colormap()
void ted_color_to_vicii_color_colormap (native_data_t * source, int ted_lum_handling)
Referenced by artstudio_ted_save(), godotdrv_write(), and koala_ted_save().
ted_lum_to_vic_color()
static uint8_t ted_lum_to_vic_color (uint8_t color, uint8_t lum) static
Referenced by ted_color_to_vic_color_colormap().
ted_lum_to_vicii_color()
static uint8_t ted_lum_to_vicii_color (uint8_t color, uint8_t lum) static
Referenced by ted_color_to_vicii_color_colormap().
ted_to_vic_color()
static uint8_t ted_to_vic_color (uint8_t color) static
Referenced by ted_color_to_vic_color_colormap().
ted_to_vicii_color()
static uint8_t ted_to_vicii_color (uint8_t color) static
Referenced by ted_color_to_vicii_color_colormap().
vdc_color_to_vic_color_colormap()
void vdc_color_to_vic_color_colormap (native_data_t * source)
Referenced by minipaint_vdc_save().
vdc_color_to_vicii_color_colormap()
void vdc_color_to_vicii_color_colormap (native_data_t * source)
Referenced by artstudio_vdc_save(), godotdrv_write(), and koala_vdc_save().
vdc_to_vic_color()
static uint8_t vdc_to_vic_color (uint8_t color) inline static
Referenced by vdc_color_to_vic_color_colormap().
vdc_to_vicii_color()
static uint8_t vdc_to_vicii_color (uint8_t color) inline static
Referenced by vdc_color_to_vicii_color_colormap().
vic_color_to_nearest_color()
static uint8_t vic_color_to_nearest_color (uint8_t color, native_color_sort_t * altcolors) inline static
altcolors[n].color == 255 marks the end of the list
Referenced by vic_color_to_nearest_vic_color_colormap().
vic_color_to_nearest_vic_color_colormap()
void vic_color_to_nearest_vic_color_colormap (native_data_t * source, native_color_sort_t * colors)
Referenced by minipaint_check_and_correct_cell().
vic_color_to_vicii_color_colormap()
void vic_color_to_vicii_color_colormap (native_data_t * source)
Referenced by artstudio_vic_save(), godotdrv_write(), and koala_vic_save().
vic_to_vicii_color()
static uint8_t vic_to_vicii_color (uint8_t color) inline static
Referenced by vic_color_to_vicii_color_colormap().
vicii_color_to_bw()
static uint8_t vicii_color_to_bw (uint8_t color) inline static
Referenced by vicii_color_to_vicii_bw_colormap().
vicii_color_to_gray()
static uint8_t vicii_color_to_gray (uint8_t color) inline static
Referenced by vicii_color_to_vicii_gray_colormap().
vicii_color_to_nearest_color()
static uint8_t vicii_color_to_nearest_color (uint8_t color, native_color_sort_t * altcolors) inline static
altcolors[n].color == 255 marks the end of the list
Referenced by vicii_color_to_nearest_vicii_color_colormap().
vicii_color_to_nearest_vicii_color_colormap()
void vicii_color_to_nearest_vicii_color_colormap (native_data_t * source, native_color_sort_t * colors)
Referenced by artstudio_check_and_correct_cell(), artstudio_multicolor_render(), artstudio_vic_save(), and koala_check_and_correct_cell().
vicii_color_to_vic_color_colormap()
void vicii_color_to_vic_color_colormap (native_data_t * source)
Referenced by minipaint_vicii_save().
vicii_color_to_vicii_bw_colormap()
void vicii_color_to_vicii_bw_colormap (native_data_t * source)
Referenced by artstudio_multicolor_render(), and artstudio_vic_save().
vicii_color_to_vicii_gray_colormap()
void vicii_color_to_vicii_gray_colormap (native_data_t * source)
Referenced by artstudio_multicolor_render(), and artstudio_vic_save().
vicii_to_vic_color()
static uint8_t vicii_to_vic_color (uint8_t color) inline static
Referenced by vicii_color_to_vic_color_colormap().
Variable Documentation
ted_lum_vic_translate
uint8_t ted_lum_vic_translate[16 *8] static
Todo:
this table needs more tweaking
Referenced by ted_lum_to_vic_color().
ted_lum_vicii_translate
uint8_t ted_lum_vicii_translate[16 *8] static
Referenced by ted_lum_to_vicii_color().
ted_vic_translate
uint8_t ted_vic_translate[16] static
Initial value:
= {
    0x0,
    0x1,
    0x2,
    0x3,
    0x4,
    0x5,
    0x6,
    0x7,
    0x8,
    0x9,
    0xF,
    0xA,
    0xB,
    0xE,
    0x6,
    0xD
}
Referenced by ted_to_vic_color().
ted_vicii_translate
uint8_t ted_vicii_translate[16] static
Initial value:
= {
    0x0,
    0x1,
    0x2,
    0x3,
    0x4,
    0x5,
    0x6,
    0x7,
    0x8,
    0x9,
    0xD,
    0xA,
    0xE,
    0xE,
    0x6,
    0xD
}
Referenced by ted_to_vicii_color().
vdc_vic_translate
uint8_t vdc_vic_translate[16] static
Initial value:
= {
    0x0,
    0x0,
    0x6,
    0xe,
    0x5,
    0xd,
    0x3,
    0xb,
    0x2,
    0xa,
    0x4,
    0xc,
    0x7,
    0xe,
    0xe,
    0x1
}
Referenced by vdc_to_vic_color().
vdc_vicii_translate
uint8_t vdc_vicii_translate[16] static
Initial value:
= {
    0x0,
    0xB,
    0x6,
    0xE,
    0x5,
    0xD,
    0x6,
    0x3,
    0x2,
    0x8,
    0x4,
    0xA,
    0x7,
    0x7,
    0xF,
    0x1
}
Referenced by vdc_to_vicii_color().
vic_closest_color
uint8_t vic_closest_color[16][16] static
Initial value:
= {
    { 0, 11, 2, 6, 8, 5, 12, 4, 10, 9, 14, 3, 13, 15, 7, 1 },
    { 1, 15, 9, 13, 7, 3, 10, 14, 12, 4, 5, 11, 8, 6, 2, 0 },
    { 2, 8, 9, 11, 0, 10, 12, 5, 4, 6, 7, 14, 15, 3, 13, 1 },
    { 3, 13, 14, 15, 12, 10, 5, 7, 4, 11, 1, 6, 8, 9, 2, 0 },
    { 4, 10, 12, 11, 15, 14, 6, 8, 2, 3, 13, 9, 7, 5, 1, 0 },
    { 5, 11, 12, 8, 9, 3, 10, 2, 13, 7, 14, 15, 0, 4, 6, 1 },
    { 6, 11, 9, 0, 4, 12, 14, 2, 8, 10, 3, 5, 13, 15, 7, 1 },
    { 7, 13, 15, 10, 3, 12, 1, 5, 8, 4, 14, 11, 2, 9, 6, 0 },
    { 8, 2, 9, 11, 10, 5, 12, 4, 0, 7, 6, 15, 3, 14, 13, 1 },
    { 9, 11, 2, 0, 8, 6, 5, 12, 4, 10, 14, 3, 15, 13, 7, 1 },
    { 10, 12, 4, 15, 7, 8, 3, 11, 13, 14, 2, 5, 9, 1, 6, 0 },
    { 11, 9, 12, 6, 2, 8, 5, 0, 4, 10, 14, 3, 15, 13, 7, 1 },
    { 12, 10, 4, 3, 14, 11, 15, 5, 13, 8, 9, 6, 7, 2, 1, 0 },
    { 13, 3, 15, 7, 12, 15, 1, 10, 5, 4, 11, 8, 9, 2, 6, 0 },
    { 14, 3, 12, 11, 4, 13, 6, 11, 10, 5, 9, 1, 7, 8, 2, 0 },
    { 15, 13, 3, 7, 1, 12, 14, 10, 4, 5, 11, 8, 6, 9, 2, 0 }
}
most similar -> least similar color
Referenced by vic_color_to_nearest_color().
vic_vicii_translate
uint8_t vic_vicii_translate[16] static
Initial value:
= {
    0x0,
    0x1,
    0x2,
    0x3,
    0x4,
    0x5,
    0x6,
    0x7,
    0x8,
    0x8,
    0xa,
    0xD,
    0x4,
    0xD,
    0xE,
    0xF
}
Referenced by vic_to_vicii_color().
vicii_closest_color
uint8_t vicii_closest_color[16][16] static
Initial value:
= {
    { 0, 9, 11, 2, 6, 8, 5, 12, 4, 10, 14, 3, 13, 15, 7, 1 },
    { 1, 15, 13, 7, 3, 10, 14, 12, 4, 5, 11, 8, 6, 2, 9, 0 },
    { 2, 8, 9, 11, 0, 10, 12, 5, 4, 6, 7, 14, 15, 3, 13, 1 },
    { 3, 13, 14, 15, 12, 10, 5, 7, 4, 11, 1, 6, 8, 9, 2, 0 },
    { 4, 10, 12, 11, 15, 14, 6, 8, 2, 3, 13, 9, 7, 5, 1, 0 },
    { 5, 11, 12, 8, 9, 3, 10, 2, 13, 7, 14, 15, 0, 4, 6, 1 },
    { 6, 11, 9, 0, 4, 12, 14, 2, 8, 10, 3, 5, 13, 15, 7, 1 },
    { 7, 13, 15, 10, 3, 12, 1, 5, 8, 4, 14, 11, 2, 9, 6, 0 },
    { 8, 2, 9, 11, 10, 5, 12, 4, 0, 7, 6, 15, 3, 14, 13, 1 },
    { 9, 11, 2, 0, 8, 6, 5, 12, 4, 10, 14, 3, 15, 13, 7, 1 },
    { 10, 12, 4, 15, 7, 8, 3, 11, 13, 14, 2, 5, 9, 1, 6, 0 },
    { 11, 9, 12, 6, 2, 8, 5, 0, 4, 10, 14, 3, 15, 13, 7, 1 },
    { 12, 10, 4, 3, 14, 11, 15, 5, 13, 8, 9, 6, 7, 2, 1, 0 },
    { 13, 3, 15, 7, 12, 15, 1, 10, 5, 4, 11, 8, 9, 2, 6, 0 },
    { 14, 3, 12, 11, 4, 13, 6, 11, 10, 5, 9, 1, 7, 8, 2, 0 },
    { 15, 13, 3, 12, 14, 10, 7, 1, 4, 5, 11, 8, 6, 9, 2, 0 }
}
most similar -> least similar color
Referenced by vicii_color_to_nearest_color().
vicii_color_bw_translate
uint8_t vicii_color_bw_translate[16] static
Initial value:
= {
    0,
    1,
    0,
    1,
    1,
    0,
    0,
    1,
    0,
    0,
    1,
    0,
    1,
    1,
    1,
    1
}
Referenced by vicii_color_to_bw().
vicii_color_gray_translate
uint8_t vicii_color_gray_translate[16] static
Initial value:
= {
    0x0,
    0xF,
    0xB,
    0xC,
    0xC,
    0xB,
    0xB,
    0xC,
    0xC,
    0xB,
    0xC,
    0xB,
    0xC,
    0xF,
    0xC,
    0xF
}
Referenced by vicii_color_to_gray().
vicii_vic_translate
uint8_t vicii_vic_translate[16] static
Initial value:
= {
    0x0,
    0x1,
    0x2,
    0x3,
    0x4,
    0x5,
    0x6,
    0x7,
    0x9,
    0x8,
    0xa,
    0x2,
    0x8,
    0xd,
    0xe,
    0xf
}
Referenced by vicii_to_vic_color().