vsid: raster/raster-modes.c File Reference
raster-modes.c File Reference
#include "vice.h"
#include <stdio.h>
#include "lib.h"
#include "raster-modes.h"
Functions
void raster_modes_init (raster_modes_t *modes, unsigned int num_modes)
void raster_modes_shutdown (raster_modes_t *modes)
raster_modes_t * raster_modes_new (unsigned int num_modes)
void raster_modes_set (raster_modes_t *modes, unsigned int num_mode, raster_modes_fill_cache_function_t fill_cache, raster_modes_draw_line_cached_function_t draw_line_cached, raster_modes_draw_line_function_t draw_line, raster_modes_draw_background_function_t draw_background, raster_modes_draw_foreground_function_t draw_foreground)
int raster_modes_set_idle_mode (raster_modes_t *modes, unsigned int num_mode)
Function Documentation
raster_modes_init()
void raster_modes_init (raster_modes_t * modes, unsigned int num_modes)
Referenced by raster_init(), and raster_modes_new().
raster_modes_new()
raster_modes_t * raster_modes_new (unsigned int num_modes)
raster_modes_set()
void raster_modes_set (raster_modes_t * modes, unsigned int num_mode, raster_modes_fill_cache_function_t fill_cache, raster_modes_draw_line_cached_function_t draw_line_cached, raster_modes_draw_line_function_t draw_line, raster_modes_draw_background_function_t draw_background, raster_modes_draw_foreground_function_t draw_foreground)
Referenced by setup_modes().
raster_modes_set_idle_mode()
int raster_modes_set_idle_mode (raster_modes_t * modes, unsigned int num_mode)
Referenced by init_raster().
raster_modes_shutdown()
void raster_modes_shutdown (raster_modes_t * modes)
Referenced by raster_shutdown().