vsid: arch/gtk3/widgets/base/cartridgewidgets.h File Reference
cartridgewidgets.h File Reference
Widgets to control cartridge resources - header.
#include <gtk/gtk.h>
Enumerations
enum cart_img_t {
_CART_IMAGE_FORCE_SIGNED = -1 ,
CART_IMAGE_PRIMARY = 1 ,
CART_IMAGE_SECONDARY ,
CART_IMAGE_TERTIARY ,
CART_IMAGE_QUATERNARY ,
CART_IMAGE_COUNT = CART_IMAGE_QUATERNARY
}
Cartridge image number type.
Functions
GtkWidget * cart_image_widget_new (int cart_id, const char *cart_name, cart_img_t image_num, const char *image_tag, const char *resource, gboolean flush_button, gboolean save_button)
Create new cartridge image widget.
void cart_image_widget_append_check (GtkWidget *widget, const char *resource, const char *text)
Append a check button for a resource.
void cart_image_widgets_shutdown (void)
Clean up resources used by this file on emulator shutdown.
Detailed Description
Widgets to control cartridge resources - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
cart_img_t
enum cart_img_t
Cartridge image number type.
Enumerator
_CART_IMAGE_FORCE_SIGNED
enum constants are signed, but an enum type can be unsigned if the range of values fits in an unsigned type
CART_IMAGE_PRIMARY
primary cartridge image
CART_IMAGE_SECONDARY
secondary cartridge image
CART_IMAGE_TERTIARY
unused for now
CART_IMAGE_QUATERNARY
unused for now
CART_IMAGE_COUNT
number of possible images, used for range checks
Function Documentation
cart_image_widget_append_check()
void cart_image_widget_append_check (GtkWidget * widget, const char * resource, const char * text)
Append a check button for a resource.
Append a check button for resource to the cartridge image widget.
Parameters
[in] widget cartridge image widget
[in] resource resource name
[in] text text for the check button
Referenced by create_dqbb_image_widget(), create_expert_image_widget(), create_georam_image_widget(), create_isepic_image_widget(), create_primary_image_widget(), create_ramcart_image_widget(), create_reu_image_widget(), create_secondary_image_widget(), and settings_gmod2_widget_create().
cart_image_widget_new()
GtkWidget * cart_image_widget_new (int cart_id, const char * cart_name, cart_img_t image_num, const char * image_tag, const char * resource, gboolean flush_button, gboolean save_button)
Create new cartridge image widget.
Create widget to select/save/flush a cartridge image.
If image_tag is NULL a default "primary", "secondary" etc tag will be used. If resource is NULL the GtkEntry to select an image file won't be added.
Parameters
[in] cart_id cartridge ID
[in] cart_name cartridge name
[in] image_num cartridge image number
[in] image_tag cartridge image tag (can be NULL)
[in] resource cartridge image file resource (can be NULL)
[in] flush_button cartridge widget needs "flush image" button
[in] save_button cartridge widget needs "save image as" button
Returns
GtkGrid
See also
cartridge.h for constants for cart_id and cart_name.
cart_img_t for valid values for image_num.
Referenced by create_dqbb_image_widget(), create_expert_image_widget(), create_georam_image_widget(), create_isepic_image_widget(), create_primary_image_widget(), create_ramcart_image_widget(), create_reu_image_widget(), create_secondary_image_widget(), and settings_gmod2_widget_create().
cart_image_widgets_shutdown()
void cart_image_widgets_shutdown (void)
Clean up resources used by this file on emulator shutdown.
Free the last used directory/filename which might be allocated by the cartridge image widgets. This function should be called once on emulator shutdown.
Referenced by ui_shutdown().