x128: c128/cart/generic.c File Reference
generic.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cartridge.h"
#include "util.h"
#include "log.h"
#include "c64cart.h"
#include "export.h"
#include "c128cart.h"
#include "functionrom.h"
#include "crt.h"
#include "generic.h"
Macros
#define DBG(x)
#define SNAP_MAJOR 0
#define SNAP_MINOR 1
Functions
void c128generic_config_setup (uint8_t *rawcart)
static int c128generic_common_attach (void)
int c128generic_bin_attach (const char *filename, uint8_t *rawcart)
int c128generic_crt_attach (FILE *fd, uint8_t *rawcart)
void c128generic_detach (void)
void c128generic_reset (void)
int c128generic_snapshot_write_module (snapshot_t *s, int type)
int c128generic_snapshot_read_module (snapshot_t *s, int type)
Variables
static const export_resource_t export_res
static char snap_module_name [] = "CART128GENERIC"
Macro Definition Documentation
DBG
#define DBG (x)
SNAP_MAJOR
#define SNAP_MAJOR 0
SNAP_MINOR
#define SNAP_MINOR 1
Function Documentation
c128generic_bin_attach()
int c128generic_bin_attach (const char * filename, uint8_t * rawcart)
Referenced by c128cartridge_bin_attach().
c128generic_common_attach()
static int c128generic_common_attach (void) static
Referenced by c128generic_bin_attach(), c128generic_crt_attach(), and c128generic_snapshot_read_module().
c128generic_config_setup()
void c128generic_config_setup (uint8_t * rawcart)
Referenced by c128cartridge_config_setup().
c128generic_crt_attach()
int c128generic_crt_attach (FILE * fd, uint8_t * rawcart)
< external function rom
< external function rom
Referenced by c128cartridge_attach_crt().
c128generic_detach()
void c128generic_detach (void)
Referenced by c128cartridge_detach_image().
c128generic_reset()
void c128generic_reset (void)
Referenced by c128cartridge_reset().
c128generic_snapshot_read_module()
int c128generic_snapshot_read_module (snapshot_t * s, int type)
Referenced by c128cartridge_snapshot_read().
c128generic_snapshot_write_module()
int c128generic_snapshot_write_module (snapshot_t * s, int type)
Referenced by c128cartridge_snapshot_write().
Variable Documentation
export_res
const export_resource_t export_res static
Initial value:
= {
     "generic function ROM" , 1, 1, NULL, NULL, ((  0   ) +  ( 79   + 1) )
}
Referenced by c128generic_common_attach(), and c128generic_detach().
snap_module_name
char snap_module_name[] = "CART128GENERIC" static
Referenced by c128generic_snapshot_read_module(), and c128generic_snapshot_write_module().