x128: userport/userport_wic64.h File Reference
userport_wic64.h File Reference
#include "types.h"
Data Structures
struct tzones
Macros
#define WIC64_DEFAULT_TRANSFER_TIMEOUT 1
supervise userport transfer
#define WIC64_DEFAULT_REMOTE_TIMEOUT 5
supervise remote URL fetch
#define WIC64_MAXTRACELEVEL 3
adjust if needed more
Typedefs
typedef struct tzones tzones_t
Functions
int userport_wic64_resources_init (void)
void userport_wic64_resources_shutdown (void)
int userport_wic64_cmdline_options_init (void)
void userport_wic64_factory_reset (void)
const tzones_t * userport_wic64_get_timezones (size_t *num_zones)
Macro Definition Documentation
WIC64_DEFAULT_REMOTE_TIMEOUT
#define WIC64_DEFAULT_REMOTE_TIMEOUT 5
supervise remote URL fetch
WIC64_DEFAULT_TRANSFER_TIMEOUT
#define WIC64_DEFAULT_TRANSFER_TIMEOUT 1
supervise userport transfer
WIC64_MAXTRACELEVEL
#define WIC64_MAXTRACELEVEL 3
adjust if needed more
Typedef Documentation
tzones_t
typedef struct tzones tzones_t
Function Documentation
userport_wic64_cmdline_options_init()
int userport_wic64_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
userport_wic64_factory_reset()
void userport_wic64_factory_reset (void)
userport_wic64_get_timezones()
const tzones_t * userport_wic64_get_timezones (size_t * num_zones)
userport_wic64_resources_init()
int userport_wic64_resources_init (void)
Referenced by machine_resources_init().
userport_wic64_resources_shutdown()
void userport_wic64_resources_shutdown (void)
Referenced by machine_resources_shutdown().