vsid: arch/gtk3/uistatusbar.c File Reference
uistatusbar.c File Reference
Native GTK3 UI statusbar stuff.
#include "vice.h"
#include <stdio.h>
#include <gtk/gtk.h>
#include "archdep_defs.h"
#include "archdep.h"
#include "attach.h"
#include "autostart.h"
#include "contentpreviewwidget.h"
#include "crtcontrolwidget.h"
#include "datasette.h"
#include "dirmenupopup.h"
#include "diskcontents.h"
#include "diskimage.h"
#include "diskimage/fsimage.h"
#include "drive-check.h"
#include "drive.h"
#include "drivetypes.h"
#include "fliplist.h"
#include "hotkeys.h"
#include "joyport.h"
#include "joystickmenupopup.h"
#include "kbddebugwidget.h"
#include "keyboard.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "mainlock.h"
#include "resources.h"
#include "statusbarledwidget.h"
#include "statusbarrecordingwidget.h"
#include "statusbarspeedwidget.h"
#include "tapecontents.h"
#include "tapeport.h"
#include "types.h"
#include "ui.h"
#include "uiapi.h"
#include "uiactions.h"
#include "uidatasette.h"
#include "uidiskattach.h"
#include "uifliplist.h"
#include "uimenu.h"
#include "uisettings.h"
#include "userport/userport_joystick.h"
#include "vice_gtk3.h"
#include "uistatusbar.h"
Data Structures
struct ui_sb_state_s
Global data that custom status bar widgets base their rendering on.
struct ui_statusbar_s
The full structure representing a status bar widget.
Macros
#define MAX_STATUS_BARS 3
The maximum number of status bars we will permit to exist at once.
#define MESSAGE_TIMEOUT 5
Timeout for statusbar messages in seconds.
#define DRIVE_UNIT_STR_MAX_LEN 8
Maximum length for drive unit status string.
#define DRIVE_TRACK_STR_MAX_LEN 16
Maximum length for drive track status string.
#define UNIT_8_COL 0
#define UNIT_8_ROW 0
#define UNIT_9_COL 0
#define UNIT_9_ROW 1
#define UNIT_10_COL 1
#define UNIT_10_ROW 0
#define UNIT_11_COL 1
#define UNIT_11_ROW 1
#define DRIVE_WIDGET_CSS
CSS for the drive widgets.
#define JOYSTICK_COL_LABEL 0
Joysticks widget: column of label.
#define JOYSTICK_COL_STATUS 1
Joysticks widget: column of first joystick indicator widget.
#define SB_COL_LEDS 0
Status bar column indexes.
#define SB_COL_WIDGETS 0
#define SB_COL_MESSAGES 0
#define SB_COL_KBD_DEBUG 0
#define SB_COL_MESSAGES_VSEP (SB_COL_MESSAGES + 1)
#define SB_COL_RECORDING (SB_COL_MESSAGES_VSEP + 1)
#define SB_COLUMN_COUNT (SB_COL_RECORDING + 1)
#define MESSAGE_TEXT_SIZE 1024
Size of a statusbar message, including nul character.
Typedefs
typedef struct ui_sb_state_s ui_sb_state_t
Global data that custom status bar widgets base their rendering on.
typedef struct ui_statusbar_s ui_statusbar_t
The full structure representing a status bar widget.
Enumerations
enum {
TAPE_STATUS_COL_HEADER ,
TAPE_STATUS_COL_COUNTER ,
TAPE_STATUS_COL_MOTOR
}
Tape status widget column indexes.
enum {
DRIVE_UNIT_DRIVE_0 ,
DRIVE_UNIT_DRIVE_1 ,
DRIVE_UNIT_DRIVE_MAX
}
Diskdrive drive indexes per unit.
enum {
DRIVE_STATUS_NUMBER ,
DRIVE_STATUS_HEAD ,
DRIVE_STATUS_LED
}
Column indexes for the drive status widgets.
enum {
SB_ROW_LEDS ,
SB_ROW_LEDS_HSEP ,
SB_ROW_WIDGETS ,
SB_ROW_WIDGETS_HSEP ,
SB_ROW_MESSAGES ,
SB_ROW_MESSAGES_HSEP ,
SB_ROW_KBD_DEBUG
}
Status bar row indexes.
Functions
static void tape_dir_autostart_callback (const char *image, int index, int device, unsigned int drive)
Forward decl.
static void disk_dir_autostart_callback (const char *image, int index, int device, unsigned int drive)
Callback for the disk directory popup menu.
static gboolean redraw_widget_on_ui_thread_impl (gpointer user_data)
Trigger redraw of a widget on the UI thread.
static void redraw_widget_on_ui_thread (GtkWidget *widget)
Queue a redraw of widget on the ui thread.
static ui_sb_state_t * lock_sb_state (void)
Get a locked reference to sb_state.
static void unlock_sb_state (void)
Release a locked reference to sb_state_do_not_use_directly.
static gboolean message_timeout_handler (gpointer data)
Timeout callback for the stausbar message widget.
static gboolean draw_tape_icon_cb (GtkWidget *widget, cairo_t *cr, gpointer data)
Draws the tape icon based on the current control and motor status.
static void on_drive_configure_activate (GtkWidget *widget, gpointer data)
Handler for the 'activate' event of the 'Configure drives' item.
static void on_drive_reset_config_clicked (GtkWidget *widget, gpointer data)
Handler for the 'activate' event of the 'Reset drive #X in ... mode' item.
static gboolean draw_drive_led_cb (GtkWidget *widget, cairo_t *cr, gpointer data)
Draw the LED associated with some drive's LED state.
static gboolean draw_joyport_cb (GtkWidget *widget, cairo_t *cr, gpointer data)
Draw the current input status from a joyport.
static gboolean ui_do_datasette_popup (GtkWidget *widget, GdkEvent *event, gpointer data)
Respond to mouse clicks on the tape status widget.
static gboolean ui_do_drive_popup (GtkWidget *widget, GdkEvent *event, gpointer data)
Respond to mouse clicks on a disk drive status widget.
static gboolean on_joystick_widget_hover (GtkWidget *widget, GdkEvent *event, gpointer user_data)
Handler for the enter/leave-notify events of the joysticks widget.
static gboolean on_joystick_widget_button_press (GtkWidget *widget, GdkEvent *event, gpointer user_data)
Handler for button-press events of the joysticks widget.
static gboolean ui_statusbar_cross_cb (GtkWidget *widget, GdkEvent *event, gpointer user_data)
Event handler for hovering over a clickable part of the status bar.
static void destroy_statusbar_cb (GtkWidget *sb, gpointer index)
Widget destruction callback for status bars.
static void on_crt_toggled (GtkWidget *widget, gpointer data)
Handler for the 'toggled' event of the CRT controls checkbox.
static void on_mixer_toggled (GtkWidget *widget, gpointer data)
Handler for the 'toggled' event of the mixer controls checkbox.
static void on_volume_value_changed (GtkScaleButton *widget, gdouble value, gpointer data)
Handler for the 'value-changed' event of the volume control.
static int compute_drives_enabled_mask (void)
Extracts the list of enabled drives from the DriveType resources.
static GtkWidget * ui_drive_widget_create (int unit, int bar_index)
Create a new drive widget for inclusion in the status bar.
static GtkWidget * drive_get_unit_widget (int bar, int unit)
Get disk unit widget.
static GtkWidget * drive_get_drive_widget (int bar, int unit, int drive)
Get drive status widget.
static GtkWidget * drive_get_child_widget (int bar, int unit, int drive, int column)
Get child widget of a drive status widget.
static GtkWidget * drive_get_number_widget (int bar, int unit, int drive)
Get widget displaying the unit[:drive] number.
static GtkWidget * drive_get_head_widget (int bar, int unit, int drive)
Get widget displaying the drive head position.
static GtkWidget * drive_get_led_widget (int bar, int unit, int drive)
Get widget displaying the LED.
static GtkWidget * ui_tape_widget_create (int port, int bar)
Create a new tape widget for inclusion in the status bar.
static uint32_t build_active_joyport_mask (void)
Create a bitfield of enabled joyports for detecting changes.
static void update_joyport_layout (void)
Alter widget visibility within the joyport widget so that only currently existing joystick ports are displayed.
static GtkWidget * ui_joystick_widget_create (void)
Create a master joyport widget for inclusion in the status bar.
static void layout_statusbar_drives (ui_sb_state_t *state_snapshot, int bar_index)
Lay out the disk drive widgets inside a status bar.
static gboolean on_disk_attach (GtkWidget *item, gpointer data)
Callback for the 'attach' disk popup menu item.
static gboolean on_disk_detach (GtkWidget *item, gpointer data)
Callback for the 'attach' disk popup menu item.
static GtkWidget * ui_drive_menu_create (gint unit, gint drive)
Create a popup menu to attach to a disk drive widget.
static GtkWidget * ui_volume_button_create (void)
Create volume button for the status bar.
static void warp_led_callback (GtkWidget *widget, gboolean active)
Callback function for the Warp mode LED.
static GtkWidget * warp_led_create (void)
Create status bar LED for Warp mode.
void warp_led_set_active (int bar, gboolean active)
Set Warp mode LED state.
static void pause_led_callback (GtkWidget *widget, gboolean active)
Callback function for the Pause LED.
static GtkWidget * pause_led_create (void)
Create status bar LED for Pause.
void pause_led_set_active (int bar, gboolean active)
Set Pause LED state.
static GtkWidget * shiftlock_led_create (void)
Create status bar LED for shiftlock.
void shiftlock_led_set_active (int bar, gboolean active)
Set shiftlock LED state.
static void mode4080_led_callback (GtkWidget *widget, gboolean active)
Callback function for the 40/80 LED.
static GtkWidget * mode4080_led_create (void)
Create status bar LED for 40/80 key.
void mode4080_led_set_active (int bar, gboolean active)
Set 40/80 LED state.
static void capslock_led_callback (GtkWidget *widget, gboolean active)
Callback function for the capslock LED.
static GtkWidget * capslock_led_create (void)
Create status bar LED for capslock key.
void capslock_led_set_active (int bar, gboolean active)
Set capslock LED state.
static void diagnosticpin_led_callback (GtkWidget *widget, gboolean active)
Callback function for the PET diagnostic pin LED.
static GtkWidget * diagnosticpin_led_create (void)
void diagnosticpin_led_set_active (int bar, gboolean active)
Set PET userport diagnostic pin led state.
static void supercpu_turbo_led_callback (GtkWidget *self, gboolean active)
Callback for the SuperCPU turbo LED.
static GtkWidget * supercpu_turbo_led_create (void)
Create SuperCPU "turbo" led widget.
void supercpu_turbo_led_set_active (int bar, gboolean active)
Set SCPU64 turbo led state.
static void supercpu_jiffy_led_callback (GtkWidget *self, gboolean active)
Callback for the SuperCPU JiffyDOS LED.
static GtkWidget * supercpu_jiffy_led_create (void)
Create SuperCPU JiffyDOS LED widget.
void supercpu_jiffy_led_set_active (int bar, gboolean active)
Set SCPU64 JiffyDOS LED state.
int ui_statusbar_index_for_window (GtkWidget *window)
Get status bar index for window.
static void statusbar_append_led (int bar, GtkWidget *led, gboolean separator)
Append a widget to the LEDs row of a status bar.
static void statusbar_append_widget (int bar, GtkWidget *widget, gboolean separator)
Append a widget to the widgets row of a status bar.
static void statusbar_append_widget_end (int bar, GtkWidget *widget)
Append a widget to the top row of a status bar at the end.
void ui_statusbar_init (void)
Initialize the status bar subsystem.
void ui_statusbar_shutdown (void)
Clean up any resources the statusbar system uses that weren't cleaned up when the status bars themselves were destroyed.
GtkWidget * ui_statusbar_create (int window_identity)
Create a new status bar.
void ui_display_event_time (unsigned int current, unsigned int total)
Statusbar API function to register an elapsed time.
void ui_display_playback (int playback_status, char *version)
Statusbar API function to display playback status.
void ui_display_recording (int recording_status)
Statusbar API function to display recording status.
void ui_display_statustext (const char *text, bool fadeout)
Statusbar API function to display a message in the status bar.
void ui_display_volume (int vol)
Statusbar API function to display current volume.
void ui_display_joyport (uint16_t *joyport)
Statusbar API function to display current joyport inputs.
static GtkWidget * tape_get_motor_widget (int bar, int port)
Get tape motor widget by tape port index.
void ui_display_tape_control_status (int port, int control)
Statusbar API function to report changes in tape control status.
void ui_display_tape_counter (int port, int counter)
Statusbar API function to report changes in tape position.
void ui_display_tape_motor_status (int port, int motor)
Statusbar API function to report changes in the tape motor.
void ui_set_tape_status (int port, int tape_status)
Statusbar API function to report changes in tape status.
void ui_display_tape_current_image (int port, const char *image)
Statusbar API function to report mounting or unmounting of a tape image.
void ui_display_drive_led (unsigned int drive_number, unsigned int drive_base, unsigned int led_pwm1, unsigned int led_pwm2)
Statusbar API function to report changes in drive LED intensity.
void ui_display_drive_track (unsigned int drive_number, unsigned int drive_base, unsigned int half_track_number, unsigned int drive_side)
Statusbar API function to report changes in drive head location.
void ui_enable_drive_status (ui_drive_enable_t state, int *drive_led_color)
Update information about each drive.
void ui_display_drive_current_image (unsigned int unit_number, unsigned int drive_number, const char *image)
Statusbar API function to report mounting or unmounting of a disk image.
gboolean ui_statusbar_crt_controls_enabled (GtkWidget *window)
Determine if the CRT controls widget is enabled in window.
gboolean ui_statusbar_mixer_controls_enabled (GtkWidget *window)
Determine if the mixer controls widget is enabled in window.
static void statusbar_update_message (ui_sb_state_t *sb_state)
Update status bar message widget.
void ui_update_vsid_statusbar (void)
Update VSID-specific status bar.
void ui_update_statusbars (void)
Update status bars for non-VSID machines.
static void kbd_statusbar_widget_enable (GtkWidget *window, gboolean state)
Show/hide the statusbar kdb debug widget of window.
void ui_statusbar_set_kbd_debug_for_window (GtkWidget *window, gboolean state)
Show/hide the keyboard debugging widget on the status bar.
void ui_statusbar_set_kbd_debug (gboolean state)
Show/hide the keyboard debugging widget on the status bar.
GtkWidget * ui_statusbar_get_recording_widget (void)
Get active 'Recording' widget.
void ui_display_reset (int device, int mode)
Show reset on statusbar.
void ui_statusbar_update_kbd_debug (GdkEvent *report)
Update status bar debug widget instances.
gboolean ui_statusbar_set_visible_for_window (GtkWidget *window, gboolean visible)
Set visibility of the status bar for a main window.
gboolean ui_action_toggle_show_statusbar (void)
Show/Hide statusbar of the active window.
void ui_statusbar_recreate_crt_controls (void)
Recreate CRT controls on the status bars.
Variables
static const int unit_cols [4]
Column indexes for the drive widgets.
static const int unit_rows [4]
Row indexes for the drive widgets.
static pthread_mutex_t sb_state_lock = PTHREAD_MUTEX_INITIALIZER
Used to safely access sb_state between threads.
static ui_sb_state_t sb_state_do_not_use_directly
The current state of the status bars across the UI.
static ui_statusbar_t allocated_bars [3]
The collection of status bars currently active.
static GdkCursor * joywidget_mouse_ptr = NULL
Cursor used when hovering over the joysticks widgets.
static guint timeout_id = 0
Timeout ID of the message widget.
Detailed Description
Native GTK3 UI statusbar stuff.
The status bar widget is part of every machine window. This widget reacts to UI notifications from the emulation core and otherwise does not interact with the rest of the main menu.
Functions described as "Statusbar API functions" are called by the rest of the UI or the emulation system itself to report that the status displays must be updated to reflect possibly new information. It is not necessary for the data to be truly new; the statusbar implementation will treat repeated reports of the same state as no-ops when necessary for performance.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
David Hogan david.nosp@m..q.h.nosp@m.ogan@.nosp@m.gmai.nosp@m.l.com
Macro Definition Documentation
DRIVE_TRACK_STR_MAX_LEN
#define DRIVE_TRACK_STR_MAX_LEN 16
Maximum length for drive track status string.
DRIVE_UNIT_STR_MAX_LEN
#define DRIVE_UNIT_STR_MAX_LEN 8
Maximum length for drive unit status string.
DRIVE_WIDGET_CSS
#define DRIVE_WIDGET_CSS
Value:
    "label {\n" \
    "    font-family: monospace;\n" \
    "    font-size:100%;\n" \
    "    margin-top: 0px;\n" \
    "    margin-bottom: -4px;\n" \
    "}\n"
CSS for the drive widgets.
The negative margins look weird, but otherwise we have a lot of padding, and the drive widgets already take up a lot of space when having dual-drives enabled.
JOYSTICK_COL_LABEL
#define JOYSTICK_COL_LABEL 0
Joysticks widget: column of label.
JOYSTICK_COL_STATUS
#define JOYSTICK_COL_STATUS 1
Joysticks widget: column of first joystick indicator widget.
MAX_STATUS_BARS
#define MAX_STATUS_BARS 3
The maximum number of status bars we will permit to exist at once.
MESSAGE_TEXT_SIZE
#define MESSAGE_TEXT_SIZE 1024
Size of a statusbar message, including nul character.
MESSAGE_TIMEOUT
#define MESSAGE_TIMEOUT 5
Timeout for statusbar messages in seconds.
SB_COL_KBD_DEBUG
#define SB_COL_KBD_DEBUG 0
SB_COL_LEDS
#define SB_COL_LEDS 0
Status bar column indexes.
SB_COL_MESSAGES
#define SB_COL_MESSAGES 0
SB_COL_MESSAGES_VSEP
#define SB_COL_MESSAGES_VSEP (SB_COL_MESSAGES + 1)
SB_COL_RECORDING
#define SB_COL_RECORDING (SB_COL_MESSAGES_VSEP + 1)
SB_COL_WIDGETS
#define SB_COL_WIDGETS 0
SB_COLUMN_COUNT
#define SB_COLUMN_COUNT (SB_COL_RECORDING + 1)
UNIT_10_COL
#define UNIT_10_COL 1
UNIT_10_ROW
#define UNIT_10_ROW 0
UNIT_11_COL
#define UNIT_11_COL 1
UNIT_11_ROW
#define UNIT_11_ROW 1
UNIT_8_COL
#define UNIT_8_COL 0
UNIT_8_ROW
#define UNIT_8_ROW 0
UNIT_9_COL
#define UNIT_9_COL 0
UNIT_9_ROW
#define UNIT_9_ROW 1
Typedef Documentation
ui_sb_state_t
typedef struct ui_sb_state_s ui_sb_state_t
Global data that custom status bar widgets base their rendering on.
This data is usually set by calls from the emulation core or from other parts of the UI in response to user commands or I/O events.
Todo:
The PET can have two tape drives.
Todo:
Two-unit drive units are not covered by this structure.
ui_statusbar_t
typedef struct ui_statusbar_s ui_statusbar_t
The full structure representing a status bar widget.
This includes the top-level widget and then every subwidget that needs to be individually addressed or manipulated by the status-report API.
Enumeration Type Documentation
anonymous enum
anonymous enum
Tape status widget column indexes.
Enumerator
TAPE_STATUS_COL_HEADER
label with 'datasette [12]
TAPE_STATUS_COL_COUNTER
label with counter
TAPE_STATUS_COL_MOTOR
custom motor widget
anonymous enum
anonymous enum
Diskdrive drive indexes per unit.
A dual-drive unit has two drives as the name implies.
Enumerator
DRIVE_UNIT_DRIVE_0
first drive, always valid
DRIVE_UNIT_DRIVE_1
second drive (2040, 3040, 4040, 8050, 8250)
DRIVE_UNIT_DRIVE_MAX
maximum number of drives per unit
anonymous enum
anonymous enum
Column indexes for the drive status widgets.
Each status widget has a label for the unit number (8-11), suffixed with a drive number for dual-drive units, ie '8:0 and 8:1' for unit 8. Another label is used to display the current position of the head, currently only the track number is displayed, not the sector number. The third widget is the drive LED.
Enumerator
DRIVE_STATUS_NUMBER
label containing unit number and drive number
DRIVE_STATUS_HEAD
label containing position of the head
DRIVE_STATUS_LED
led custom widget
anonymous enum
anonymous enum
Status bar row indexes.
Enumerator
SB_ROW_LEDS
row with small LEDs
SB_ROW_LEDS_HSEP
horizontal separator between LEDs and large widgets
SB_ROW_WIDGETS
large widgets/containers
SB_ROW_WIDGETS_HSEP
horizontal separator between large widgets and messages/recording
SB_ROW_MESSAGES
messages AND separator AND recording
SB_ROW_MESSAGES_HSEP
horizontal separator between messages/recording and the keyboard debugging widget
SB_ROW_KBD_DEBUG
keyboard debugging
Function Documentation
build_active_joyport_mask()
static uint32_t build_active_joyport_mask (void) static
Create a bitfield of enabled joyports for detecting changes.
Referenced by ui_update_statusbars().
capslock_led_callback()
static void capslock_led_callback (GtkWidget * widget, gboolean active) static
Callback function for the capslock LED.
Parameters
[in] led capslock LED
[in] active new state of the LED
Referenced by capslock_led_create().
capslock_led_create()
static GtkWidget * capslock_led_create (void) static
Create status bar LED for capslock key.
Returns
LED widget
Referenced by ui_statusbar_create().
capslock_led_set_active()
void capslock_led_set_active (int bar, gboolean active)
Set capslock LED state.
Parameters
[in] bar status bar index
[in] active LED status
Referenced by statusbar_speed_widget_update().
compute_drives_enabled_mask()
static int compute_drives_enabled_mask (void) static
Extracts the list of enabled drives from the DriveType resources.
Returns
A bitmask value suitable for ui_sb_state_s::drives_enabled.
Referenced by ui_enable_drive_status().
destroy_statusbar_cb()
static void destroy_statusbar_cb (GtkWidget * sb, gpointer index) static
Widget destruction callback for status bars.
Parameters
[in] sb The status bar being destroyed. This should be registered in some ui_statusbar_t structure as the bar field.
[in] index status bar index
Referenced by ui_statusbar_create().
diagnosticpin_led_callback()
static void diagnosticpin_led_callback (GtkWidget * widget, gboolean active) static
Callback function for the PET diagnostic pin LED.
Parameters
[in] led diagnostic pin LED
[in] active new state of the LED
Referenced by diagnosticpin_led_create().
diagnosticpin_led_create()
static GtkWidget * diagnosticpin_led_create (void) static
Referenced by ui_statusbar_create().
diagnosticpin_led_set_active()
void diagnosticpin_led_set_active (int bar, gboolean active)
Set PET userport diagnostic pin led state.
Parameters
[in] bar status bar index
[in] active new state for led
Referenced by statusbar_speed_widget_update().
disk_dir_autostart_callback()
static void disk_dir_autostart_callback (const char * image, int index, int device, unsigned int drive) static
Callback for the disk directory popup menu.
Autostarts the selected file in the directory
Parameters
[in] image image name
[in] index directory index of the file to start
[in] device device number (0-3)
[in] drive drive number (0 or 1) of device
Referenced by ui_do_drive_popup().
draw_drive_led_cb()
static gboolean draw_drive_led_cb (GtkWidget * widget, cairo_t * cr, gpointer data) static
Draw the LED associated with some drive's LED state.
Parameters
widget The drive LED GtkDrawingArea being drawn to.
cr The cairo context that handles the drawing.
data The index (0-3) of which drive this represents.
Returns
FALSE, telling GTK to continue event processing
Todo:
FIXME: this should display two LEDs some day, right now we combine the two LEDs of a drive into one that we display.
Referenced by ui_drive_widget_create().
draw_joyport_cb()
static gboolean draw_joyport_cb (GtkWidget * widget, cairo_t * cr, gpointer data) static
Draw the current input status from a joyport.
This produces five squares arranged in a + shape, with directions represented as green squares when active and black when not. The fire buttons are represented by the central square, with red, green, and blue components representing the three possible buttons.
For traditional Commodore joysticks, there is only one fire button and this will be diplayed as a red square when the button is pressed.
Parameters
widget The joyport GtkDrawingArea being drawn to.
cr The cairo context that handles the drawing.
data The index (0-4) of which joyport this represents.
Returns
FALSE, telling GTK to continue event processing
Referenced by ui_joystick_widget_create().
draw_tape_icon_cb()
static gboolean draw_tape_icon_cb (GtkWidget * widget, cairo_t * cr, gpointer data) static
Draws the tape icon based on the current control and motor status.
Parameters
widget The tape icon GtkDrawingArea being drawn to.
cr The cairo context that handles the drawing.
data tape port index
Returns
FALSE, telling GTK to continue event processing
Todo:
Should RESET_COUNTER be wiped out by the time it gets here?
Referenced by ui_tape_widget_create().
drive_get_child_widget()
static GtkWidget * drive_get_child_widget (int bar, int unit, int drive, int column) static
Get child widget of a drive status widget.
Parameters
[in] bar status bar index (0 or 1)
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
[in] column column, see DRIVE_STATUS_NUMBER, DRIVE_STATUS_HEAD, DRIVE_STATUS_LED
Returns
Child widget
Referenced by drive_get_head_widget(), drive_get_led_widget(), and drive_get_number_widget().
drive_get_drive_widget()
static GtkWidget * drive_get_drive_widget (int bar, int unit, int drive) static
Get drive status widget.
Parameters
[in] bar status bar index (0 or 1)
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
GtkEventBox containing the GtkGrid with the drive widgets
Note
Perhaps this can be changed to return the contained GtkGrid if we find out we never need to work directly with the GtkEventBox.
Referenced by drive_get_child_widget(), and layout_statusbar_drives().
drive_get_head_widget()
static GtkWidget * drive_get_head_widget (int bar, int unit, int drive) static
Get widget displaying the drive head position.
Parameters
[in] bar status bar index (0 or 1)
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
GtkLabel
Referenced by ui_update_statusbars().
drive_get_led_widget()
static GtkWidget * drive_get_led_widget (int bar, int unit, int drive) static
Get widget displaying the LED.
Parameters
[in] bar status bar index (0 or 1)
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
GtkDrawingArea
Referenced by layout_statusbar_drives(), and ui_update_statusbars().
drive_get_number_widget()
static GtkWidget * drive_get_number_widget (int bar, int unit, int drive) static
Get widget displaying the unit[:drive] number.
Parameters
[in] bar status bar index (0 or 1)
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
GtkLabel
Referenced by ui_update_statusbars().
drive_get_unit_widget()
static GtkWidget * drive_get_unit_widget (int bar, int unit) static
Get disk unit widget.
Parameters
[in] bar status bar index (0 or 1)
[in] unit unit number (8-11)
Returns
GtkGrid
Referenced by layout_statusbar_drives().
kbd_statusbar_widget_enable()
static void kbd_statusbar_widget_enable (GtkWidget * window, gboolean state) static
Show/hide the statusbar kdb debug widget of window.
Parameters
[in,out] window GtkWindow instance
[in] state Display state
Todo:
Replace integer literals
Referenced by ui_statusbar_set_kbd_debug(), and ui_statusbar_set_kbd_debug_for_window().
layout_statusbar_drives()
static void layout_statusbar_drives (ui_sb_state_t * state_snapshot, int bar_index) static
Lay out the disk drive widgets inside a status bar.
Enable/disable unit, drive, LED widgets based on current configuration.
Parameters
[in] bar_index Which status bar to lay out.
Referenced by ui_update_statusbars().
lock_sb_state()
static ui_sb_state_t * lock_sb_state (void) static
Get a locked reference to sb_state.
Referenced by draw_drive_led_cb(), draw_joyport_cb(), draw_tape_icon_cb(), ui_display_drive_led(), ui_display_drive_track(), ui_display_joyport(), ui_display_statustext(), ui_display_tape_control_status(), ui_display_tape_counter(), ui_display_tape_motor_status(), ui_enable_drive_status(), ui_statusbar_init(), ui_update_statusbars(), and ui_update_vsid_statusbar().
message_timeout_handler()
static gboolean message_timeout_handler (gpointer data) static
Timeout callback for the stausbar message widget.
Parameters
[in,out] data message widget
Returns
FALSE (delete timer source)
Referenced by statusbar_update_message().
mode4080_led_callback()
static void mode4080_led_callback (GtkWidget * widget, gboolean active) static
Callback function for the 40/80 LED.
Parameters
[in] led 40/80 LED
[in] active new state of the LED
Referenced by mode4080_led_create().
mode4080_led_create()
static GtkWidget * mode4080_led_create (void) static
Create status bar LED for 40/80 key.
Returns
LED widget
Referenced by ui_statusbar_create().
mode4080_led_set_active()
void mode4080_led_set_active (int bar, gboolean active)
Set 40/80 LED state.
Parameters
[in] bar status bar index
[in] active LED status
Referenced by statusbar_speed_widget_update().
on_crt_toggled()
static void on_crt_toggled (GtkWidget * widget, gpointer data) static
Handler for the 'toggled' event of the CRT controls checkbox.
Toggles the display state of the CRT controls
Parameters
[in] widget checkbox triggering the event
[in] data extra event data (unused
Referenced by ui_statusbar_create().
on_disk_attach()
static gboolean on_disk_attach (GtkWidget * item, gpointer data) static
Callback for the 'attach' disk popup menu item.
Trigger the proper 'attach' UI action for the given unit and drive.
Parameters
[in] item menu item (unused)
[in] data unit and drive number
Returns
TRUE
Referenced by ui_drive_menu_create().
on_disk_detach()
static gboolean on_disk_detach (GtkWidget * item, gpointer data) static
Callback for the 'attach' disk popup menu item.
Trigger the proper 'detach' UI action for the given unit and drive.
Parameters
[in] item menu item (unused)
[in] data unit and drive number
Returns
TRUE
Referenced by ui_drive_menu_create().
on_drive_configure_activate()
static void on_drive_configure_activate (GtkWidget * widget, gpointer data) static
Handler for the 'activate' event of the 'Configure drives' item.
Opens the settings UI at the drive settings "page".
Parameters
[in] widget menu item triggering the event (unused)
[in] data extra event data (unused)
Referenced by ui_do_drive_popup(), and ui_drive_menu_create().
on_drive_reset_config_clicked()
static void on_drive_reset_config_clicked (GtkWidget * widget, gpointer data) static
Handler for the 'activate' event of the 'Reset drive #X in ... mode' item.
Triggers a reset for drive ((int)data + 8).
Parameters
[in] widget menu item triggering the event (unused)
[in] data drive number (0-3)
Referenced by ui_do_drive_popup().
on_joystick_widget_button_press()
static gboolean on_joystick_widget_button_press (GtkWidget * widget, GdkEvent * event, gpointer user_data) static
Handler for button-press events of the joysticks widget.
Parameters
[in] widget widget triggering the event
[in] event event reference
[in] user_data extra event data (unused)
Returns
TRUE to stop other handlers, FALSE to propagate event further
Referenced by ui_joystick_widget_create().
on_joystick_widget_hover()
static gboolean on_joystick_widget_hover (GtkWidget * widget, GdkEvent * event, gpointer user_data) static
Handler for the enter/leave-notify events of the joysticks widget.
Parameters
[in] widget widget triggering the event
[in] event event reference
[in] user_data extra event data (unused)
Returns
bool (FALSE = keep propagating event, TRUE = stop)
Referenced by ui_joystick_widget_create().
on_mixer_toggled()
static void on_mixer_toggled (GtkWidget * widget, gpointer data) static
Handler for the 'toggled' event of the mixer controls checkbox.
Toggles the display state of the mixer controls
Parameters
[in] widget checkbox triggering the event
[in] data extra event data (unused
Referenced by ui_statusbar_create().
on_volume_value_changed()
static void on_volume_value_changed (GtkScaleButton * widget, gdouble value, gpointer data) static
Handler for the 'value-changed' event of the volume control.
Updates the master volume
Parameters
[in] widget GtkVolumeButton control
[in] value new volume value (1.0 - 0.0)
[in] data extra event data (unused
Referenced by ui_volume_button_create().
pause_led_callback()
static void pause_led_callback (GtkWidget * widget, gboolean active) static
Callback function for the Pause LED.
Parameters
[in] led pause LED
[in] active new state of the LED
Referenced by pause_led_create().
pause_led_create()
static GtkWidget * pause_led_create (void) static
Create status bar LED for Pause.
Returns
LED widget
Referenced by ui_statusbar_create().
pause_led_set_active()
void pause_led_set_active (int bar, gboolean active)
Set Pause LED state.
Parameters
[in] bar status bar index
[in] active LED status
Referenced by statusbar_speed_widget_update().
redraw_widget_on_ui_thread()
static void redraw_widget_on_ui_thread (GtkWidget * widget) static
Queue a redraw of widget on the ui thread.
It's not safe to ask a widget to redraw from the vice thread.
Parameters
[in,out] widget widget to redraw
Referenced by ui_display_joyport(), ui_display_tape_control_status(), and ui_display_tape_motor_status().
redraw_widget_on_ui_thread_impl()
static gboolean redraw_widget_on_ui_thread_impl (gpointer user_data) static
Trigger redraw of a widget on the UI thread.
Parameters
[in,out] user_data widget to redraw
Returns
FALSE
Referenced by redraw_widget_on_ui_thread().
shiftlock_led_create()
static GtkWidget * shiftlock_led_create (void) static
Create status bar LED for shiftlock.
Returns
LED widget
Referenced by ui_statusbar_create().
shiftlock_led_set_active()
void shiftlock_led_set_active (int bar, gboolean active)
Set shiftlock LED state.
Parameters
[in] bar status bar index
[in] active LED status
Referenced by statusbar_speed_widget_update().
statusbar_append_led()
static void statusbar_append_led (int bar, GtkWidget * led, gboolean separator) static
Append a widget to the LEDs row of a status bar.
Append led to status bar with index bar, optionally adding a separator before the new widget.
Parameters
[in] bar status bar index
[in] widget widget to append
[in] separator append separator before appending the widget
Referenced by ui_statusbar_create().
statusbar_append_widget()
static void statusbar_append_widget (int bar, GtkWidget * widget, gboolean separator) static
Append a widget to the widgets row of a status bar.
Append widget to status bar with index bar, optionally adding a separator before the new widget.
Parameters
[in] bar status bar index
[in] widget widget to append
[in] separator append separator before appending the widget
Referenced by ui_statusbar_create().
statusbar_append_widget_end()
static void statusbar_append_widget_end (int bar, GtkWidget * widget) static
Append a widget to the top row of a status bar at the end.
Append widget to status bar with index bar.
Parameters
[in] bar status bar index
[in] widget widget to append
[in] separator append separator before appending the widget
Referenced by ui_statusbar_create().
statusbar_update_message()
static void statusbar_update_message (ui_sb_state_t * sb_state) static
Update status bar message widget.
Parameters
[in] state statusbar state, obtained through lock_sb_state()
Referenced by ui_update_statusbars(), and ui_update_vsid_statusbar().
supercpu_jiffy_led_callback()
static void supercpu_jiffy_led_callback (GtkWidget * self, gboolean active) static
Callback for the SuperCPU JiffyDOS LED.
Set resource "SpeedSwitch" to active.
Parameters
[in] self turbo LED (ignored)
[in] active new LED state
Referenced by supercpu_jiffy_led_create().
supercpu_jiffy_led_create()
static GtkWidget * supercpu_jiffy_led_create (void) static
Create SuperCPU JiffyDOS LED widget.
Returns
LED widget
Referenced by ui_statusbar_create().
supercpu_jiffy_led_set_active()
void supercpu_jiffy_led_set_active (int bar, gboolean active)
Set SCPU64 JiffyDOS LED state.
Parameters
[in] bar status bar index
[in] active new state for led
Referenced by jiffy_switch_callback(), and scpu_jiffy_switch_toggle_action().
supercpu_turbo_led_callback()
static void supercpu_turbo_led_callback (GtkWidget * self, gboolean active) static
Callback for the SuperCPU turbo LED.
Set resource "SpeedSwitch" to active.
Parameters
[in] self turbo LED (ignored)
[in] active new LED state
Referenced by supercpu_turbo_led_create().
supercpu_turbo_led_create()
static GtkWidget * supercpu_turbo_led_create (void) static
Create SuperCPU "turbo" led widget.
Returns
LED widget
Referenced by ui_statusbar_create().
supercpu_turbo_led_set_active()
void supercpu_turbo_led_set_active (int bar, gboolean active)
Set SCPU64 turbo led state.
Parameters
[in] bar status bar index
[in] active new state for led
Referenced by scpu_speed_switch_toggle_action(), and speed_switch_callback().
tape_dir_autostart_callback()
static void tape_dir_autostart_callback (const char * image, int index, int device, unsigned int drive) static
Forward decl.
Callback for the tape directory popup menu.
Autostarts the selected file in the directory
Parameters
[in] image image name
[in] index directory index of the file to start
[in] device device number (unused, but perhaps useful for PET)
[in] drive drive number (unused)
Referenced by ui_do_datasette_popup().
tape_get_motor_widget()
static GtkWidget * tape_get_motor_widget (int bar, int port) static
Get tape motor widget by tape port index.
Parameters
[in] bar status bar index
[in] port tape port index
Returns
tape motor widget or NULL if not present
Referenced by ui_display_tape_control_status(), and ui_display_tape_motor_status().
ui_action_toggle_show_statusbar()
gboolean ui_action_toggle_show_statusbar (void)
Show/Hide statusbar of the active window.
Toggle visibility of statusbar based on "${chip}HideStatusbar" resource.
Returns
TRUE (don't pass event along further)
ui_display_drive_current_image()
void ui_display_drive_current_image (unsigned int unit_number, unsigned int drive_number, const char * image)
Statusbar API function to report mounting or unmounting of a disk image.
Parameters
unit_number 0-3 to represent disk units at device 8-11.
drive_number 0-1 to represent the drives in a unit
image The filename of the disk image (if mounted), or the empty string or NULL (if unmounting).
Todo:
This API is insufficient to describe drives with two disk units.
Referenced by file_system_attach_disk_internal(), file_system_detach_disk_single(), and set_file_system_device().
ui_display_drive_led()
void ui_display_drive_led (unsigned int drive_number, unsigned int drive_base, unsigned int led_pwm1, unsigned int led_pwm2)
Statusbar API function to report changes in drive LED intensity.
The pwm value will vary between 0 and 1000.
This function simply updates global state, rendering occurs in ui_update_statusbars().
Parameters
drive_number The unit to update (0-3 for drives 8-11)
drive_base Drive 0 or 1 of dualdrives
led_pwm1 The intensity of the first LED (0=off, 1000=maximum intensity)
led_pwm2 The intensity of the second LED (0=off, 1000=maximum intensity)
Todo:
Dual drive code doesn't have its separate Error LED. Its setting is mixed in in the led_status of drive 0. Also those error LEDs don't flash but are just on (or on some models, change the green/red LED to red).
Todo:
Fatal error?
Referenced by drive_led_update().
ui_display_drive_track()
void ui_display_drive_track (unsigned int drive_number, unsigned int drive_base, unsigned int half_track_number, unsigned int drive_side)
Statusbar API function to report changes in drive head location.
This function simply updates global state, rendering occurs in ui_update_statusbars().
Parameters
drive_number The unit to update (0-3 for drives 8-11)
drive_base Drive 0 or 1 of dualdrives
half_track_number Twice the value of the head location. 18.0 is 36, while 18.5 would be 37.
drive_side drive side for dual-head drives (0 or 1)
Todo:
The statusbar API does not yet support dual-unit disk drives. The drive_base argument will likely come into play once it does.
Todo:
Fatal error?
Referenced by drive_update_ui_status(), vdrive_read_sector(), and vdrive_write_sector().
ui_display_event_time()
void ui_display_event_time (unsigned int current, unsigned int total)
Statusbar API function to register an elapsed time.
Parameters
current The current time value in seconds
total The maximum time value in seconds
Referenced by event_alarm_handler().
ui_display_joyport()
void ui_display_joyport (uint16_t * joyport)
Statusbar API function to display current joyport inputs.
Joystick UI.
Parameters
joyport An array of bytes of size at least JOYPORT_MAX_PORTS+1, with data regarding each active joyport.
Warning
The joyport array is, for all practical purposes, 1-indexed. joyport[0] is unused.
See also
ui_sb_state_s::current_joyports Describes the format of the data encoded in the joyport array. Note that current_joyports is 0-indexed as is typical for C arrays.
Todo:
FIXME: during the joystick data extension the joyport type has become uint16_t, I did not change anything except the parameter of the function
ui_display_playback()
void ui_display_playback (int playback_status, char * version)
Statusbar API function to display playback status.
Recording UI.
Parameters
playback_status Unknown.
version seems to be the VICE version major.minor during playback and NULL when playback is done.
Todo:
This function is not implemented and its API is not understood.
Note
Since the statusbar message display widget has been removed, we have some space to implement a widget to display information regarding playback/recording.
Referenced by event_playback_start_trap(), and event_playback_stop().
ui_display_recording()
void ui_display_recording (int recording_status)
Statusbar API function to display recording status.
Parameters
recording_status seems to be bool indicating recording active
Todo:
This function is not implemented and its API is not understood.
Note
Since the statusbar message display widget has been removed, we have some space to implement a widget to display information regarding playback/recording.
Referenced by event_record_start_trap(), event_record_stop(), history_record_start_action(), history_record_stop_action(), on_response(), and ui_media_stop_recording().
ui_display_reset()
void ui_display_reset (int device, int mode)
Show reset on statusbar.
Reset.
A device was reset, so we show it on the statusbar
Parameters
[in] device device number
[in] mode reset mode (soft(0) or hard(1) ,only for device 0)
Referenced by cpu_reset(), and machine_trigger_reset_internal().
ui_display_statustext()
void ui_display_statustext (const char * text, bool fadeout)
Statusbar API function to display a message in the status bar.
Display a mesage without interrupting emulation.
Parameters
text The text to display.
fadeout Erase the text after five* seconds unless it has already been replaced.
Note
Safe to call from VICE thread.
See also
MESSAGE_TIMEOUT for the actual timeout in seconds
Referenced by do_attach(), fliplist_add_action(), fliplist_clear_action(), fliplist_load_response(), fliplist_next_action(), fliplist_previous_action(), fliplist_remove_action(), fliplist_save_response(), hotkeys_clear_action(), hotkeys_default_action(), hotkeys_load_action(), hotkeys_save_action(), network_connect_client(), network_disconnect(), network_hook_connected_receive(), network_hook_connected_send(), network_server_connect_trap(), network_start_server(), network_test_delay(), on_response(), on_row_activated(), playlist_load_callback(), save_callback(), statusbar_speed_widget_update(), ui_fliplist_select_cb(), and vsid_playlist_save().
ui_display_tape_control_status()
void ui_display_tape_control_status (int port, int control)
Statusbar API function to report changes in tape control status.
Parameters
[in] port tape port index (0 or 1)
[in] control The new tape control. See the DATASETTE_CONTROL_* constants in datasette.h for legal values of this parameter.
ui_display_tape_counter()
void ui_display_tape_counter (int port, int counter)
Statusbar API function to report changes in tape position.
Parameters
[in] port tape port index (0 or 1)
[in] counter the new value of the position counter
Note
Only the last three digits of the counter will be displayed.
ui_display_tape_current_image()
void ui_display_tape_current_image (int port, const char * image)
Statusbar API function to report mounting or unmounting of a tape image.
Parameters
image The filename of the tape image (if mounted), or the empty string or NULL (if unmounting).
Referenced by tape_image_attach_internal(), and tape_image_detach_internal().
ui_display_tape_motor_status()
void ui_display_tape_motor_status (int port, int motor)
Statusbar API function to report changes in the tape motor.
Parameters
[in] port tape port index (0 or 1)
[in] motor Nonzero if the tape motor is now on.
ui_display_volume()
void ui_display_volume (int vol)
Statusbar API function to display current volume.
Volume UI.
This function is a NOP since the volume can be checked and altered via the Mixer Controls via the statusbar.
Parameters
[in] vol new volume level
Referenced by set_volume().
ui_do_datasette_popup()
static gboolean ui_do_datasette_popup (GtkWidget * widget, GdkEvent * event, gpointer data) static
Respond to mouse clicks on the tape status widget.
This displays the tape control popup menu.
Parameters
widget The GtkWidget that received the click. Ignored.
event The event representing the bottom operation.
data An integer representing which window's status bar was clicked and thus where the popup window should go, and tape unit number shifted 8 bits to the right.
Returns
TRUE if further event processing should be skipped.
Todo:
This callback and the way it is configured both will need to be significantly reworked to manage multiple tape drives.
Referenced by ui_statusbar_create().
ui_do_drive_popup()
static gboolean ui_do_drive_popup (GtkWidget * widget, GdkEvent * event, gpointer data) static
Respond to mouse clicks on a disk drive status widget.
This displays the drive control popup menu.
Parameters
[in] widget The GtkWidget that received the click. Ignored.
[in] event The event representing the bottom operation.
[in] data Unit index (bits 0-7) and drive number (bit 8)
Returns
TRUE if further event processing should be skipped.
Referenced by ui_drive_widget_create().
ui_drive_menu_create()
static GtkWidget * ui_drive_menu_create (gint unit, gint drive) static
Create a popup menu to attach to a disk drive widget.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0 or 1)
Returns
The GtkMenu for use as a popup, as a floating reference.
Referenced by ui_statusbar_create().
ui_drive_widget_create()
static GtkWidget * ui_drive_widget_create (int unit, int bar_index) static
Create a new drive widget for inclusion in the status bar.
Parameters
unit The drive unit to create (0-3, indicating devices 8-11)
Returns
The constructed widget. This widget will be a floating reference.
Todo:
FIXME: unit number should be passed as-is, not as index!
Referenced by ui_statusbar_create().
ui_enable_drive_status()
void ui_enable_drive_status (ui_drive_enable_t state, int * drive_led_color)
Update information about each drive.
Drive related UI.
Parameters
state A bitmask int, where bits 0-3 indicate whether or not drives 8-11 respectively are being emulated carefully enough to provide LED information.
drive_led_color An array of size at least NUM_DISK_UNITS that provides information about the LEDs on this drive. An element of this array will only be checked if the corresponding bit in state is 1.
Note
Before calling this function, the drive configuration resources (Drive8Type, Drive9Type, etc) should all be set to the values you wish to display.
Warning
If a drive's LEDs are active when its LED values change, the UI will not reflect the LED type change until the next time the led's values are updated. This should not happen under normal circumstances.
See also
compute_drives_enabled_mask() for how this function determines which drives are truly active
ui_sb_state_s::drive_led_types for the data in each element of drive_led_color
Referenced by drive_enable_update_ui().
ui_joystick_widget_create()
static GtkWidget * ui_joystick_widget_create (void) static
Create a master joyport widget for inclusion in the status bar.
Individual joyport representations are part of this widget and update functions will index the GtkGrid in the master widget to reach them.
Returns
The constructed widget. This widget will be a floating reference.
Referenced by ui_statusbar_create().
ui_set_tape_status()
void ui_set_tape_status (int port, int tape_status)
Statusbar API function to report changes in tape status.
Parameters
tape_status The new tape status.
Note
This function does nothing and its API is not understood. Furthermore, no other extant UIs appear to react to this call.
ui_statusbar_create()
GtkWidget * ui_statusbar_create (int window_identity)
Create a new status bar.
This function should be called once as part of creating a new machine window.
Parameters
[in] window_identity window identity
Returns
A new status bar, as a floating reference, or NULL if all possible status bars have been allocated already.
Referenced by ui_create_main_window().
ui_statusbar_cross_cb()
static gboolean ui_statusbar_cross_cb (GtkWidget * widget, GdkEvent * event, gpointer user_data) static
Event handler for hovering over a clickable part of the status bar.
This will switch to or from the "hand" cursor as needed, creating it if necessary.
Parameters
widget The widget firing the event
event The GdkEventCross that caused the callback
user_data The ui_statusbar_t object containing widget
Returns
TRUE if further event processing should be blocked.
Referenced by ui_drive_widget_create(), ui_statusbar_create(), and ui_tape_widget_create().
ui_statusbar_crt_controls_enabled()
gboolean ui_statusbar_crt_controls_enabled (GtkWidget * window)
Determine if the CRT controls widget is enabled in window.
Parameters
[in] window GtkWindow instance
Returns
bool
Referenced by ui_update_fullscreen_decorations().
ui_statusbar_get_recording_widget()
GtkWidget * ui_statusbar_get_recording_widget (void)
Get active 'Recording' widget.
Returns
recording widget
Referenced by ui_media_stop_recording().
ui_statusbar_index_for_window()
int ui_statusbar_index_for_window (GtkWidget * window)
Get status bar index for window.
Parameters
[in] window GtkWindow instance
Returns
index or -1 on error
Referenced by ui_statusbar_crt_controls_enabled(), and ui_statusbar_mixer_controls_enabled().
ui_statusbar_init()
void ui_statusbar_init (void)
Initialize the status bar subsystem.
Warning
This function must be called before any call to ui_statusbar_create() and must not be called after any call to it.
Referenced by ui_init().
ui_statusbar_mixer_controls_enabled()
gboolean ui_statusbar_mixer_controls_enabled (GtkWidget * window)
Determine if the mixer controls widget is enabled in window.
Parameters
[in] window GtkWindow instance
Returns
bool
Referenced by ui_update_fullscreen_decorations().
ui_statusbar_recreate_crt_controls()
void ui_statusbar_recreate_crt_controls (void)
Recreate CRT controls on the status bars.
Destroy the old CRT controls and create new ones. To be called whenever the video standard changes.
Referenced by update_crt_controls().
ui_statusbar_set_kbd_debug()
void ui_statusbar_set_kbd_debug (gboolean state)
Show/hide the keyboard debugging widget on the status bar.
Show/hide the keyboard debugging widget on the status bar (of both windows in the case of x128).
Parameters
[in] state visible state
Note
Only call from a finalized UI.
Referenced by on_kbd_debug_toggled().
ui_statusbar_set_kbd_debug_for_window()
void ui_statusbar_set_kbd_debug_for_window (GtkWidget * window, gboolean state)
Show/hide the keyboard debugging widget on the status bar.
Show/hide the keyboard debugging widget on the status bar of a single window.
Parameters
[in] window main window instance
[in] state visible state
Referenced by ui_create_main_window().
ui_statusbar_set_visible_for_window()
gboolean ui_statusbar_set_visible_for_window (GtkWidget * window, gboolean visible)
Set visibility of the status bar for a main window.
Parameters
[in] window main window
[in] visible visibility of status bar for window
Returns
TRUE on success
Referenced by show_statusbar_secondary_toggle_action(), show_statusbar_toggle_action(), ui_action_toggle_show_statusbar(), and ui_init_finalize().
ui_statusbar_shutdown()
void ui_statusbar_shutdown (void)
Clean up any resources the statusbar system uses that weren't cleaned up when the status bars themselves were destroyed.
Referenced by ui_shutdown().
ui_statusbar_update_kbd_debug()
void ui_statusbar_update_kbd_debug (GdkEvent * report)
Update status bar debug widget instances.
Parameters
[in] report Gdk key event
Note
Can only be called from the UI thread.
Referenced by kbd_event_handler().
ui_tape_widget_create()
static GtkWidget * ui_tape_widget_create (int port, int bar) static
Create a new tape widget for inclusion in the status bar.
Parameters
[in] port port number
[in] bar status bar index
Returns
The constructed widget. This widget will be a floating reference.
Referenced by ui_statusbar_create().
ui_update_statusbars()
void ui_update_statusbars (void)
Update status bars for non-VSID machines.
Todo:
Don't call this for each top level window as it updates all statusbars
Todo:
Another LED for dual drive
Referenced by vice_opengl_on_ui_frame_clock().
ui_update_vsid_statusbar()
void ui_update_vsid_statusbar (void)
Update VSID-specific status bar.
Referenced by on_frame_clock_update().
ui_volume_button_create()
static GtkWidget * ui_volume_button_create (void) static
Create volume button for the status bar.
Returns
GtkVolumeButton
Referenced by ui_statusbar_create().
unlock_sb_state()
static void unlock_sb_state (void) static
Release a locked reference to sb_state_do_not_use_directly.
Referenced by draw_drive_led_cb(), draw_joyport_cb(), draw_tape_icon_cb(), ui_display_drive_led(), ui_display_drive_track(), ui_display_joyport(), ui_display_statustext(), ui_display_tape_control_status(), ui_display_tape_counter(), ui_display_tape_motor_status(), ui_enable_drive_status(), ui_statusbar_init(), ui_update_statusbars(), and ui_update_vsid_statusbar().
update_joyport_layout()
static void update_joyport_layout (void) static
Alter widget visibility within the joyport widget so that only currently existing joystick ports are displayed.
Referenced by ui_update_statusbars().
warp_led_callback()
static void warp_led_callback (GtkWidget * widget, gboolean active) static
Callback function for the Warp mode LED.
Parameters
[in] led warp mode LED
[in] active new state of the LED
Referenced by warp_led_create().
warp_led_create()
static GtkWidget * warp_led_create (void) static
Create status bar LED for Warp mode.
Returns
LED widget
Referenced by ui_statusbar_create().
warp_led_set_active()
void warp_led_set_active (int bar, gboolean active)
Set Warp mode LED state.
Parameters
[in] bar status bar index
[in] active LED status
Referenced by statusbar_speed_widget_update().
Variable Documentation
allocated_bars
ui_statusbar_t allocated_bars[3] static
The collection of status bars currently active.
Inactive status bars have a NULL pointer for their "bar" field.
Referenced by capslock_led_set_active(), destroy_statusbar_cb(), diagnosticpin_led_set_active(), drive_get_drive_widget(), drive_get_unit_widget(), layout_statusbar_drives(), mode4080_led_set_active(), pause_led_set_active(), shiftlock_led_set_active(), statusbar_append_led(), statusbar_append_widget(), statusbar_append_widget_end(), statusbar_update_message(), supercpu_jiffy_led_set_active(), supercpu_turbo_led_set_active(), tape_get_motor_widget(), ui_display_event_time(), ui_display_joyport(), ui_display_playback(), ui_display_recording(), ui_do_datasette_popup(), ui_do_drive_popup(), ui_drive_widget_create(), ui_statusbar_create(), ui_statusbar_crt_controls_enabled(), ui_statusbar_get_recording_widget(), ui_statusbar_index_for_window(), ui_statusbar_init(), ui_statusbar_mixer_controls_enabled(), ui_statusbar_recreate_crt_controls(), ui_statusbar_update_kbd_debug(), ui_tape_widget_create(), ui_update_statusbars(), ui_update_vsid_statusbar(), update_joyport_layout(), and warp_led_set_active().
joywidget_mouse_ptr
GdkCursor* joywidget_mouse_ptr = NULL static
Cursor used when hovering over the joysticks widgets.
!
Todo:
figure out if I need to clean this up or that Gtk will?
Referenced by on_joystick_widget_hover().
sb_state_do_not_use_directly
ui_sb_state_t sb_state_do_not_use_directly static
The current state of the status bars across the UI.
Don't use directly! Use lock_sb_state / unlock_sb_state instead. I thought this pattern would make it more obvious to future developers that they shouldn't just use sb_state without locking.
Referenced by lock_sb_state().
sb_state_lock
pthread_mutex_t sb_state_lock = PTHREAD_MUTEX_INITIALIZER static
Used to safely access sb_state between threads.
Referenced by lock_sb_state(), and unlock_sb_state().
timeout_id
guint timeout_id = 0 static
Timeout ID of the message widget.
Referenced by message_timeout_handler(), and statusbar_update_message().
unit_cols
const int unit_cols[4] static
Initial value:
= {
     0 ,  0 ,  1 ,  1
}
Column indexes for the drive widgets.
These are columns in their containing grid, not the status bar grid.
Referenced by ui_statusbar_create().
unit_rows
const int unit_rows[4] static
Initial value:
= {
     0 ,  1 ,  0 ,  1
}
Row indexes for the drive widgets.
These are rows in their containing grid, not the status bar grid.
Referenced by ui_statusbar_create().