vsid: arch/gtk3/uivsidwindow.c File Reference
uivsidwindow.c File Reference
Native GTK3 main vsid window code.
#include "vice.h"
#include <gtk/gtk.h>
#include "archdep.h"
#include "hvsc.h"
#include "hvscstilwidget.h"
#include "lib.h"
#include "machine.h"
#include "mainlock.h"
#include "psid.h"
#include "ui.h"
#include "uiapi.h"
#include "uivsidmenu.h"
#include "vice_gtk3.h"
#include "videoarch.h"
#include "videomodelwidget.h"
#include "vsidcontrolwidget.h"
#include "vsidmainwidget.h"
#include "vsidmixerwidget.h"
#include "vsidstate.h"
#include "vsidtuneinfowidget.h"
#include "vsidui.h"
#include "vsync.h"
#include "uistatusbar.h"
#include "uivsidwindow.h"
Functions
static void vsid_ui_update (void)
UI update handler.
static void on_frame_clock_update (GdkFrameClock *clock, gpointer user_data)
Called once per frame for frequent asynchronous UI updates.
static void on_widget_realized (GtkWidget *widget, gpointer data)
static void on_widget_unrealized (GtkWidget *widget, gpointer data)
static void vsid_window_create (video_canvas_t *canvas)
Create VSID window.
int ui_vsid_window_load_psid (const char *filename)
Load and play PSID/SID file filename.
void ui_vsid_window_init (void)
Initialize VSID window.
void vsid_ui_display_name (const char *name)
Display tune name in the UI.
void vsid_ui_display_author (const char *author)
Display tune author in the UI.
void vsid_ui_display_copyright (const char *copyright)
Display tune copyright info in the UI.
void vsid_ui_display_irqtype (const char *irq)
Set IRQ type for the UI.
void vsid_ui_display_sid_model (int model)
Set SID model for the UI.
void vsid_ui_display_sync (int sync)
Set sync factor for the UI.
void vsid_ui_display_time (unsigned int dsec)
Set run time of tune in the UI.
void vsid_ui_display_nr_of_tunes (int count)
Set number of tunes for the UI.
void vsid_ui_set_default_tune (int nr)
Set default tune number in the UI.
void vsid_ui_display_tune_nr (int nr)
Set current tune number in the UI.
void vsid_ui_setdrv (char *driver_info_text)
Set driver info text for the UI.
void vsid_ui_set_driver_addr (uint16_t addr)
Set driver address.
void vsid_ui_set_load_addr (uint16_t addr)
Set load address.
void vsid_ui_set_init_addr (uint16_t addr)
Set init routine address.
void vsid_ui_set_play_addr (uint16_t addr)
Set play routine address.
void vsid_ui_set_data_size (uint16_t size)
Set size of SID on actual machine.
Variables
static GtkWidget * main_widget = NULL
Main widget of VSID.
static gulong frame_clock_update_handler
ID of the frame clock update event handler.
Detailed Description
Native GTK3 main vsid window code.
Author
Marcus Sutton logge.nosp@m.doub.nosp@m.t@gma.nosp@m.il.c.nosp@m.om
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_frame_clock_update()
static void on_frame_clock_update (GdkFrameClock * clock, gpointer user_data) static
Called once per frame for frequent asynchronous UI updates.
For example, vsid.c provides an updated play time from the VICE thread. It's not safe for the VICE thread to call GTK code - so instead we just store the value and update the UI each frame in here.
Referenced by on_widget_realized().
on_widget_realized()
static void on_widget_realized (GtkWidget * widget, gpointer data) static
Referenced by vsid_window_create().
on_widget_unrealized()
static void on_widget_unrealized (GtkWidget * widget, gpointer data) static
Referenced by vsid_window_create().
ui_vsid_window_init()
void ui_vsid_window_init (void)
Initialize VSID window.
Referenced by vsid_ui_init().
ui_vsid_window_load_psid()
int ui_vsid_window_load_psid (const char * filename)
Load and play PSID/SID file filename.
Parameters
[in] filename file to play
Returns
0 on success, -1 on failure
Note
sets player UI state to either VSID_PLAYING or VSID_ERROR
Referenced by on_drag_data_received(), on_response(), on_row_activated(), ui_vsid_window_init(), vsid_playlist_first(), vsid_playlist_last(), vsid_playlist_next(), and vsid_playlist_previous().
vsid_ui_display_author()
void vsid_ui_display_author (const char * author)
Display tune author in the UI.
Parameters
[in] author author name
Referenced by psid_init_tune().
vsid_ui_display_copyright()
void vsid_ui_display_copyright (const char * copyright)
Display tune copyright info in the UI.
Parameters
[in] copright copyright info
Referenced by psid_init_tune().
vsid_ui_display_irqtype()
void vsid_ui_display_irqtype (const char * irq)
Set IRQ type for the UI.
Parameters
[in] irq IRQ type
Referenced by psid_init_tune().
vsid_ui_display_name()
void vsid_ui_display_name (const char * name)
Display tune name in the UI.
Parameters
[in] name tune name
Referenced by psid_init_tune().
vsid_ui_display_nr_of_tunes()
void vsid_ui_display_nr_of_tunes (int count)
Set number of tunes for the UI.
Parameters
[in] count number of tunes
Referenced by psid_init_tune(), and psid_load_file().
vsid_ui_display_sid_model()
void vsid_ui_display_sid_model (int model)
Set SID model for the UI.
Parameters
[in] model SID model
Referenced by psid_init_tune().
vsid_ui_display_sync()
void vsid_ui_display_sync (int sync)
Set sync factor for the UI.
Parameters
[in] sync sync factor
Referenced by psid_init_tune().
vsid_ui_display_time()
void vsid_ui_display_time (unsigned int dsec)
Set run time of tune in the UI.
Parameters
[in] sec seconds of play time
Referenced by machine_vsync_hook(), and psid_init_tune().
vsid_ui_display_tune_nr()
void vsid_ui_display_tune_nr (int nr)
Set current tune number in the UI.
Parameters
[in] nr tune number
Referenced by psid_init_tune().
vsid_ui_set_data_size()
void vsid_ui_set_data_size (uint16_t size)
Set size of SID on actual machine.
Parameters
[in] size size of SID
Referenced by psid_init_tune().
vsid_ui_set_default_tune()
void vsid_ui_set_default_tune (int nr)
Set default tune number in the UI.
Parameters
[in] nr tune number
Referenced by psid_init_tune(), and psid_load_file().
vsid_ui_set_driver_addr()
void vsid_ui_set_driver_addr (uint16_t addr)
Set driver address.
Parameters
[in] addr driver address
Referenced by psid_init_tune().
vsid_ui_set_init_addr()
void vsid_ui_set_init_addr (uint16_t addr)
Set init routine address.
Parameters
[in] addr init routine address
Referenced by psid_init_tune().
vsid_ui_set_load_addr()
void vsid_ui_set_load_addr (uint16_t addr)
Set load address.
Parameters
[in] addr load address
Referenced by psid_init_tune().
vsid_ui_set_play_addr()
void vsid_ui_set_play_addr (uint16_t addr)
Set play routine address.
Parameters
[in] addr play routine address
Referenced by psid_init_tune().
vsid_ui_setdrv()
void vsid_ui_setdrv (char * driver_info_text)
Set driver info text for the UI.
Parameters
[in] driver_info_text text with driver info (duh)
Referenced by psid_init_tune().
vsid_ui_update()
static void vsid_ui_update (void) static
UI update handler.
Referenced by on_frame_clock_update().
vsid_window_create()
static void vsid_window_create (video_canvas_t * canvas) static
Create VSID window.
Parameters
[in] canvas something
Referenced by ui_vsid_window_init().
Variable Documentation
frame_clock_update_handler
gulong frame_clock_update_handler static
ID of the frame clock update event handler.
Referenced by on_widget_realized(), and on_widget_unrealized().
main_widget
GtkWidget* main_widget = NULL static
Main widget of VSID.
Referenced by vsid_window_create().