x128: cartio.h File Reference
cartio.h File Reference
#include "types.h"
Data Structures
struct io_source_s
struct io_source_list_s
The I/O source list structure is a double linked list for easy insertion/removal of devices.
struct io_source_detach_s
Macros
#define IO_DETACH_CART 0
#define IO_DETACH_RESOURCE 1
#define IO_DETACH_NEVER 2
#define IO_DETACH_NO_RESOURCE NULL
#define IO_COLLISION_METHOD_DETACH_ALL 0
#define IO_COLLISION_METHOD_DETACH_LAST 1
#define IO_COLLISION_METHOD_AND_WIRES 2
#define IO_PRIO_HIGH 1
override others on collisions
#define IO_PRIO_NORMAL 0
handle collisions
#define IO_PRIO_LOW -1
overridden by others on collisions
#define IO_CART_ID_NONE 0
#define IO_MIRROR_NONE 0
registered area contains no mirrors
#define IO_MIRROR_OTHER 1
registered area contains mirrors of another registered area
#define IO_MIRROR_MASK 2
registered area contains mirrors of itself, determined by address_mask
Typedefs
typedef struct io_source_s io_source_t
typedef struct io_source_list_s io_source_list_t
The I/O source list structure is a double linked list for easy insertion/removal of devices.
typedef struct io_source_detach_s io_source_detach_t
Functions
uint8_t c64io_d000_read (uint16_t addr)
uint8_t c64io_d000_peek (uint16_t addr)
void c64io_d000_store (uint16_t addr, uint8_t value)
uint8_t c64io_d100_read (uint16_t addr)
uint8_t c64io_d100_peek (uint16_t addr)
void c64io_d100_store (uint16_t addr, uint8_t value)
uint8_t c64io_d200_read (uint16_t addr)
uint8_t c64io_d200_peek (uint16_t addr)
void c64io_d200_store (uint16_t addr, uint8_t value)
uint8_t c64io_d300_read (uint16_t addr)
uint8_t c64io_d300_peek (uint16_t addr)
void c64io_d300_store (uint16_t addr, uint8_t value)
uint8_t c64io_d400_read (uint16_t addr)
uint8_t c64io_d400_peek (uint16_t addr)
void c64io_d400_store (uint16_t addr, uint8_t value)
uint8_t c64io_d500_read (uint16_t addr)
uint8_t c64io_d500_peek (uint16_t addr)
void c64io_d500_store (uint16_t addr, uint8_t value)
uint8_t c64io_d600_read (uint16_t addr)
uint8_t c64io_d600_peek (uint16_t addr)
void c64io_d600_store (uint16_t addr, uint8_t value)
uint8_t c64io_d700_read (uint16_t addr)
uint8_t c64io_d700_peek (uint16_t addr)
void c64io_d700_store (uint16_t addr, uint8_t value)
uint8_t c64io_dd00_read (uint16_t addr)
uint8_t c64io_dd00_peek (uint16_t addr)
void c64io_dd00_store (uint16_t addr, uint8_t value)
uint8_t c64io_de00_read (uint16_t addr)
uint8_t c64io_de00_peek (uint16_t addr)
void c64io_de00_store (uint16_t addr, uint8_t value)
uint8_t c64io_df00_read (uint16_t addr)
uint8_t c64io_df00_peek (uint16_t addr)
void c64io_df00_store (uint16_t addr, uint8_t value)
uint8_t vic20io0_read (uint16_t addr)
uint8_t vic20io0_peek (uint16_t addr)
void vic20io0_store (uint16_t addr, uint8_t value)
uint8_t vic20io2_read (uint16_t addr)
uint8_t vic20io2_peek (uint16_t addr)
void vic20io2_store (uint16_t addr, uint8_t value)
uint8_t vic20io3_read (uint16_t addr)
uint8_t vic20io3_peek (uint16_t addr)
void vic20io3_store (uint16_t addr, uint8_t value)
uint8_t cbm2io_d800_read (uint16_t addr)
uint8_t cbm2io_d800_peek (uint16_t addr)
void cbm2io_d800_store (uint16_t addr, uint8_t value)
uint8_t cbm2io_d900_read (uint16_t addr)
uint8_t cbm2io_d900_peek (uint16_t addr)
void cbm2io_d900_store (uint16_t addr, uint8_t value)
uint8_t cbm2io_da00_read (uint16_t addr)
uint8_t cbm2io_da00_peek (uint16_t addr)
void cbm2io_da00_store (uint16_t addr, uint8_t value)
uint8_t cbm2io_db00_read (uint16_t addr)
uint8_t cbm2io_db00_peek (uint16_t addr)
void cbm2io_db00_store (uint16_t addr, uint8_t value)
uint8_t cbm2io_dc00_read (uint16_t addr)
uint8_t cbm2io_dc00_peek (uint16_t addr)
void cbm2io_dc00_store (uint16_t addr, uint8_t value)
uint8_t cbm2io_dd00_read (uint16_t addr)
uint8_t cbm2io_dd00_peek (uint16_t addr)
void cbm2io_dd00_store (uint16_t addr, uint8_t value)
uint8_t cbm2io_de00_read (uint16_t addr)
uint8_t cbm2io_de00_peek (uint16_t addr)
void cbm2io_de00_store (uint16_t addr, uint8_t value)
uint8_t cbm2io_df00_read (uint16_t addr)
uint8_t cbm2io_df00_peek (uint16_t addr)
void cbm2io_df00_store (uint16_t addr, uint8_t value)
uint8_t petio_8800_read (uint16_t addr)
uint8_t petio_8800_peek (uint16_t addr)
void petio_8800_store (uint16_t addr, uint8_t value)
uint8_t petio_8900_read (uint16_t addr)
uint8_t petio_8900_peek (uint16_t addr)
void petio_8900_store (uint16_t addr, uint8_t value)
uint8_t petio_8a00_read (uint16_t addr)
uint8_t petio_8a00_peek (uint16_t addr)
void petio_8a00_store (uint16_t addr, uint8_t value)
uint8_t petio_8b00_read (uint16_t addr)
uint8_t petio_8b00_peek (uint16_t addr)
void petio_8b00_store (uint16_t addr, uint8_t value)
uint8_t petio_8c00_read (uint16_t addr)
uint8_t petio_8c00_peek (uint16_t addr)
void petio_8c00_store (uint16_t addr, uint8_t value)
uint8_t petio_8d00_read (uint16_t addr)
uint8_t petio_8d00_peek (uint16_t addr)
void petio_8d00_store (uint16_t addr, uint8_t value)
uint8_t petio_8e00_read (uint16_t addr)
uint8_t petio_8e00_peek (uint16_t addr)
void petio_8e00_store (uint16_t addr, uint8_t value)
uint8_t petio_8f00_read (uint16_t addr)
uint8_t petio_8f00_peek (uint16_t addr)
void petio_8f00_store (uint16_t addr, uint8_t value)
uint8_t petio_e900_read (uint16_t addr)
uint8_t petio_e900_peek (uint16_t addr)
void petio_e900_store (uint16_t addr, uint8_t value)
uint8_t petio_ea00_read (uint16_t addr)
uint8_t petio_ea00_peek (uint16_t addr)
void petio_ea00_store (uint16_t addr, uint8_t value)
uint8_t petio_eb00_read (uint16_t addr)
uint8_t petio_eb00_peek (uint16_t addr)
void petio_eb00_store (uint16_t addr, uint8_t value)
uint8_t petio_ec00_read (uint16_t addr)
uint8_t petio_ec00_peek (uint16_t addr)
void petio_ec00_store (uint16_t addr, uint8_t value)
uint8_t petio_ed00_read (uint16_t addr)
uint8_t petio_ed00_peek (uint16_t addr)
void petio_ed00_store (uint16_t addr, uint8_t value)
uint8_t petio_ee00_read (uint16_t addr)
uint8_t petio_ee00_peek (uint16_t addr)
void petio_ee00_store (uint16_t addr, uint8_t value)
uint8_t petio_ef00_read (uint16_t addr)
uint8_t petio_ef00_peek (uint16_t addr)
void petio_ef00_store (uint16_t addr, uint8_t value)
uint8_t plus4io_fd00_read (uint16_t addr)
uint8_t plus4io_fd00_peek (uint16_t addr)
void plus4io_fd00_store (uint16_t addr, uint8_t value)
uint8_t plus4io_fe00_read (uint16_t addr)
uint8_t plus4io_fe00_peek (uint16_t addr)
void plus4io_fe00_store (uint16_t addr, uint8_t value)
void io_source_ioreg_add_list (struct mem_ioreg_list_s **mem_ioreg_list)
io_source_list_t * io_source_register (io_source_t *device)
void io_source_unregister (io_source_list_t *device)
void cartio_shutdown (void)
void c64io_vicii_init (void)
void c64io_vicii_deinit (void)
void c64io_vicii_reinit (void)
int cartio_resources_init (void)
int cartio_cmdline_options_init (void)
void cartio_set_highest_order (unsigned int nr)
Macro Definition Documentation
IO_CART_ID_NONE
#define IO_CART_ID_NONE 0
IO_COLLISION_METHOD_AND_WIRES
#define IO_COLLISION_METHOD_AND_WIRES 2
IO_COLLISION_METHOD_DETACH_ALL
#define IO_COLLISION_METHOD_DETACH_ALL 0
IO_COLLISION_METHOD_DETACH_LAST
#define IO_COLLISION_METHOD_DETACH_LAST 1
IO_DETACH_CART
#define IO_DETACH_CART 0
IO_DETACH_NEVER
#define IO_DETACH_NEVER 2
IO_DETACH_NO_RESOURCE
#define IO_DETACH_NO_RESOURCE NULL
IO_DETACH_RESOURCE
#define IO_DETACH_RESOURCE 1
IO_MIRROR_MASK
#define IO_MIRROR_MASK 2
registered area contains mirrors of itself, determined by address_mask
IO_MIRROR_NONE
#define IO_MIRROR_NONE 0
registered area contains no mirrors
IO_MIRROR_OTHER
#define IO_MIRROR_OTHER 1
registered area contains mirrors of another registered area
IO_PRIO_HIGH
#define IO_PRIO_HIGH 1
override others on collisions
IO_PRIO_LOW
#define IO_PRIO_LOW -1
overridden by others on collisions
IO_PRIO_NORMAL
#define IO_PRIO_NORMAL 0
handle collisions
Typedef Documentation
io_source_detach_t
typedef struct io_source_detach_s io_source_detach_t
io_source_list_t
typedef struct io_source_list_s io_source_list_t
The I/O source list structure is a double linked list for easy insertion/removal of devices.
io_source_t
typedef struct io_source_s io_source_t
Function Documentation
c64io_d000_peek()
uint8_t c64io_d000_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d000_read()
uint8_t c64io_d000_read (uint16_t addr)
Referenced by c128_c64io_d000_read(), read_bank_io(), and z80_c64io_d000_read().
c64io_d000_store()
void c64io_d000_store (uint16_t addr, uint8_t value)
Referenced by c128_c64io_d000_store(), store_bank_io(), and z80_c64io_d000_store().
c64io_d100_peek()
uint8_t c64io_d100_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d100_read()
uint8_t c64io_d100_read (uint16_t addr)
Referenced by c128_c64io_d100_read(), read_bank_io(), and z80_c64io_d100_read().
c64io_d100_store()
void c64io_d100_store (uint16_t addr, uint8_t value)
Referenced by c128_c64io_d100_store(), store_bank_io(), and z80_c64io_d100_store().
c64io_d200_peek()
uint8_t c64io_d200_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d200_read()
uint8_t c64io_d200_read (uint16_t addr)
Referenced by c128_c64io_d200_read(), read_bank_io(), and z80_c64io_d200_read().
c64io_d200_store()
void c64io_d200_store (uint16_t addr, uint8_t value)
Referenced by c128_c64io_d200_store(), store_bank_io(), and z80_c64io_d200_store().
c64io_d300_peek()
uint8_t c64io_d300_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d300_read()
uint8_t c64io_d300_read (uint16_t addr)
Referenced by c128_c64io_d300_read(), read_bank_io(), and z80_c64io_d300_read().
c64io_d300_store()
void c64io_d300_store (uint16_t addr, uint8_t value)
Referenced by c128_c64io_d300_store(), store_bank_io(), and z80_c64io_d300_store().
c64io_d400_peek()
uint8_t c64io_d400_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d400_read()
uint8_t c64io_d400_read (uint16_t addr)
Referenced by c128_c64io_d400_read(), read_bank_io(), and z80_c64io_d400_read().
c64io_d400_store()
void c64io_d400_store (uint16_t addr, uint8_t value)
Referenced by c128_c64io_d400_store(), store_bank_io(), and z80_c64io_d400_store().
c64io_d500_peek()
uint8_t c64io_d500_peek (uint16_t addr)
c64io_d500_read()
uint8_t c64io_d500_read (uint16_t addr)
c64io_d500_store()
void c64io_d500_store (uint16_t addr, uint8_t value)
c64io_d600_peek()
uint8_t c64io_d600_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d600_read()
uint8_t c64io_d600_read (uint16_t addr)
Referenced by c128_c64io_d600_read(), and read_bank_io().
c64io_d600_store()
void c64io_d600_store (uint16_t addr, uint8_t value)
Referenced by c128_c64io_d600_store(), and store_bank_io().
c64io_d700_peek()
uint8_t c64io_d700_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_d700_read()
uint8_t c64io_d700_read (uint16_t addr)
Referenced by c128_c64io_d700_read(), read_bank_io(), and z80_c64io_d700_read().
c64io_d700_store()
void c64io_d700_store (uint16_t addr, uint8_t value)
Referenced by c128_c64io_d700_store(), store_bank_io(), and z80_c64io_d700_store().
c64io_dd00_peek()
uint8_t c64io_dd00_peek (uint16_t addr)
c64io_dd00_read()
uint8_t c64io_dd00_read (uint16_t addr)
c64io_dd00_store()
void c64io_dd00_store (uint16_t addr, uint8_t value)
c64io_de00_peek()
uint8_t c64io_de00_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_de00_read()
uint8_t c64io_de00_read (uint16_t addr)
Referenced by c128_c64io_de00_read(), read_bank_io(), and z80_c64io_de00_read().
c64io_de00_store()
void c64io_de00_store (uint16_t addr, uint8_t value)
Referenced by c128_c64io_de00_store(), store_bank_io(), and z80_c64io_de00_store().
c64io_df00_peek()
uint8_t c64io_df00_peek (uint16_t addr)
Referenced by peek_bank_io().
c64io_df00_read()
uint8_t c64io_df00_read (uint16_t addr)
Referenced by c128_c64io_df00_read(), read_bank_io(), and z80_c64io_df00_read().
c64io_df00_store()
void c64io_df00_store (uint16_t addr, uint8_t value)
Referenced by c128_c64io_df00_store(), store_bank_io(), and z80_c64io_df00_store().
c64io_vicii_deinit()
void c64io_vicii_deinit (void)
c64io_vicii_init()
void c64io_vicii_init (void)
Referenced by c128io_init().
c64io_vicii_reinit()
void c64io_vicii_reinit (void)
cartio_cmdline_options_init()
int cartio_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
cartio_resources_init()
int cartio_resources_init (void)
Referenced by machine_resources_init().
cartio_set_highest_order()
void cartio_set_highest_order (unsigned int nr)
cartio_shutdown()
void cartio_shutdown (void)
Referenced by machine_resources_shutdown().
cbm2io_d800_peek()
uint8_t cbm2io_d800_peek (uint16_t addr)
cbm2io_d800_read()
uint8_t cbm2io_d800_read (uint16_t addr)
cbm2io_d800_store()
void cbm2io_d800_store (uint16_t addr, uint8_t value)
cbm2io_d900_peek()
uint8_t cbm2io_d900_peek (uint16_t addr)
cbm2io_d900_read()
uint8_t cbm2io_d900_read (uint16_t addr)
cbm2io_d900_store()
void cbm2io_d900_store (uint16_t addr, uint8_t value)
cbm2io_da00_peek()
uint8_t cbm2io_da00_peek (uint16_t addr)
cbm2io_da00_read()
uint8_t cbm2io_da00_read (uint16_t addr)
cbm2io_da00_store()
void cbm2io_da00_store (uint16_t addr, uint8_t value)
cbm2io_db00_peek()
uint8_t cbm2io_db00_peek (uint16_t addr)
cbm2io_db00_read()
uint8_t cbm2io_db00_read (uint16_t addr)
cbm2io_db00_store()
void cbm2io_db00_store (uint16_t addr, uint8_t value)
cbm2io_dc00_peek()
uint8_t cbm2io_dc00_peek (uint16_t addr)
cbm2io_dc00_read()
uint8_t cbm2io_dc00_read (uint16_t addr)
cbm2io_dc00_store()
void cbm2io_dc00_store (uint16_t addr, uint8_t value)
cbm2io_dd00_peek()
uint8_t cbm2io_dd00_peek (uint16_t addr)
cbm2io_dd00_read()
uint8_t cbm2io_dd00_read (uint16_t addr)
cbm2io_dd00_store()
void cbm2io_dd00_store (uint16_t addr, uint8_t value)
cbm2io_de00_peek()
uint8_t cbm2io_de00_peek (uint16_t addr)
cbm2io_de00_read()
uint8_t cbm2io_de00_read (uint16_t addr)
cbm2io_de00_store()
void cbm2io_de00_store (uint16_t addr, uint8_t value)
cbm2io_df00_peek()
uint8_t cbm2io_df00_peek (uint16_t addr)
cbm2io_df00_read()
uint8_t cbm2io_df00_read (uint16_t addr)
cbm2io_df00_store()
void cbm2io_df00_store (uint16_t addr, uint8_t value)
io_source_ioreg_add_list()
void io_source_ioreg_add_list (struct mem_ioreg_list_s ** mem_ioreg_list)
Referenced by mem_ioreg_list_get().
io_source_register()
io_source_list_t * io_source_register (io_source_t * device)
Referenced by c128comal80_common_attach(), c128gmod2_common_attach(), c128io_init(), c64io_vicii_init(), magicdesk128_common_attach(), partner128_common_attach(), and warpspeed128_common_attach().
io_source_unregister()
void io_source_unregister (io_source_list_t * device)
Referenced by c128comal80_detach(), c128gmod2_detach(), c64io_vicii_deinit(), magicdesk128_detach(), partner128_detach(), and warpspeed128_detach().
petio_8800_peek()
uint8_t petio_8800_peek (uint16_t addr)
petio_8800_read()
uint8_t petio_8800_read (uint16_t addr)
petio_8800_store()
void petio_8800_store (uint16_t addr, uint8_t value)
petio_8900_peek()
uint8_t petio_8900_peek (uint16_t addr)
petio_8900_read()
uint8_t petio_8900_read (uint16_t addr)
petio_8900_store()
void petio_8900_store (uint16_t addr, uint8_t value)
petio_8a00_peek()
uint8_t petio_8a00_peek (uint16_t addr)
petio_8a00_read()
uint8_t petio_8a00_read (uint16_t addr)
petio_8a00_store()
void petio_8a00_store (uint16_t addr, uint8_t value)
petio_8b00_peek()
uint8_t petio_8b00_peek (uint16_t addr)
petio_8b00_read()
uint8_t petio_8b00_read (uint16_t addr)
petio_8b00_store()
void petio_8b00_store (uint16_t addr, uint8_t value)
petio_8c00_peek()
uint8_t petio_8c00_peek (uint16_t addr)
petio_8c00_read()
uint8_t petio_8c00_read (uint16_t addr)
petio_8c00_store()
void petio_8c00_store (uint16_t addr, uint8_t value)
petio_8d00_peek()
uint8_t petio_8d00_peek (uint16_t addr)
petio_8d00_read()
uint8_t petio_8d00_read (uint16_t addr)
petio_8d00_store()
void petio_8d00_store (uint16_t addr, uint8_t value)
petio_8e00_peek()
uint8_t petio_8e00_peek (uint16_t addr)
petio_8e00_read()
uint8_t petio_8e00_read (uint16_t addr)
petio_8e00_store()
void petio_8e00_store (uint16_t addr, uint8_t value)
petio_8f00_peek()
uint8_t petio_8f00_peek (uint16_t addr)
petio_8f00_read()
uint8_t petio_8f00_read (uint16_t addr)
petio_8f00_store()
void petio_8f00_store (uint16_t addr, uint8_t value)
petio_e900_peek()
uint8_t petio_e900_peek (uint16_t addr)
petio_e900_read()
uint8_t petio_e900_read (uint16_t addr)
petio_e900_store()
void petio_e900_store (uint16_t addr, uint8_t value)
petio_ea00_peek()
uint8_t petio_ea00_peek (uint16_t addr)
petio_ea00_read()
uint8_t petio_ea00_read (uint16_t addr)
petio_ea00_store()
void petio_ea00_store (uint16_t addr, uint8_t value)
petio_eb00_peek()
uint8_t petio_eb00_peek (uint16_t addr)
petio_eb00_read()
uint8_t petio_eb00_read (uint16_t addr)
petio_eb00_store()
void petio_eb00_store (uint16_t addr, uint8_t value)
petio_ec00_peek()
uint8_t petio_ec00_peek (uint16_t addr)
petio_ec00_read()
uint8_t petio_ec00_read (uint16_t addr)
petio_ec00_store()
void petio_ec00_store (uint16_t addr, uint8_t value)
petio_ed00_peek()
uint8_t petio_ed00_peek (uint16_t addr)
petio_ed00_read()
uint8_t petio_ed00_read (uint16_t addr)
petio_ed00_store()
void petio_ed00_store (uint16_t addr, uint8_t value)
petio_ee00_peek()
uint8_t petio_ee00_peek (uint16_t addr)
petio_ee00_read()
uint8_t petio_ee00_read (uint16_t addr)
petio_ee00_store()
void petio_ee00_store (uint16_t addr, uint8_t value)
petio_ef00_peek()
uint8_t petio_ef00_peek (uint16_t addr)
petio_ef00_read()
uint8_t petio_ef00_read (uint16_t addr)
petio_ef00_store()
void petio_ef00_store (uint16_t addr, uint8_t value)
plus4io_fd00_peek()
uint8_t plus4io_fd00_peek (uint16_t addr)
plus4io_fd00_read()
uint8_t plus4io_fd00_read (uint16_t addr)
plus4io_fd00_store()
void plus4io_fd00_store (uint16_t addr, uint8_t value)
plus4io_fe00_peek()
uint8_t plus4io_fe00_peek (uint16_t addr)
plus4io_fe00_read()
uint8_t plus4io_fe00_read (uint16_t addr)
plus4io_fe00_store()
void plus4io_fe00_store (uint16_t addr, uint8_t value)
vic20io0_peek()
uint8_t vic20io0_peek (uint16_t addr)
vic20io0_read()
uint8_t vic20io0_read (uint16_t addr)
vic20io0_store()
void vic20io0_store (uint16_t addr, uint8_t value)
vic20io2_peek()
uint8_t vic20io2_peek (uint16_t addr)
vic20io2_read()
uint8_t vic20io2_read (uint16_t addr)
vic20io2_store()
void vic20io2_store (uint16_t addr, uint8_t value)
vic20io3_peek()
uint8_t vic20io3_peek (uint16_t addr)
vic20io3_read()
uint8_t vic20io3_read (uint16_t addr)
vic20io3_store()
void vic20io3_store (uint16_t addr, uint8_t value)