vsid: arch/shared/hotkeys/symtab.c File Reference
symtab.c File Reference
Symbol table for hotkeys.
#include "vice.h"
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include "lib.h"
#include "symtab.h"
Functions
static symbol_t * node_new (const char *name, bool value)
Allocate memory for symbol table node.
static void node_free (symbol_t *node)
Free memory used by node and its children.
static symbol_t * node_add (symbol_t *node, const char *name, bool value)
Add node to symbol table.
static symbol_t * node_find (symbol_t *node, const char *name)
Find node in symbol table.
static void node_dump (symbol_t *node)
Debug hook: dump info on (part of) symbol table on stdout.
void symbol_table_init (void)
Initialize symbol table.
void symbol_table_free (void)
Free memory used by symbol table.
void symbol_table_dump (void)
Debug hook: dump symbol table on stdout.
bool symbol_add (const char *name, bool value)
Add symbol to symbol table.
symbol_t * symbol_find (const char *name)
Look up symbol by name.
Variables
static symbol_t * symbols = NULL
Symbol table root node.
Detailed Description
Symbol table for hotkeys.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
node_add()
static symbol_t * node_add (symbol_t * node, const char * name, bool value) static
Add node to symbol table.
Parameters
[in] node node to start looking for empty leaf node
[in] name name for new node
[in] value value for new node
Returns
new node or NULL on name collision
Referenced by node_add(), and symbol_add().
node_dump()
static void node_dump (symbol_t * node) static
Debug hook: dump info on (part of) symbol table on stdout.
Print symbol table in ascending alphabetical order on stdout.
Parameters
[in] node starting node
Referenced by node_dump(), and symbol_table_dump().
node_find()
static symbol_t * node_find (symbol_t * node, const char * name) static
Find node in symbol table.
Look up node by name in symbol table, starting at node.
Parameters
[in] node starting node in symbol table
[in] name symbol name
Returns
node or NULL when not found
Referenced by node_find(), and symbol_find().
node_free()
static void node_free (symbol_t * node) static
Free memory used by node and its children.
Free node and recursively its child nodes.
Parameters
[in] node node to free
Referenced by node_free(), and symbol_table_free().
node_new()
static symbol_t * node_new (const char * name, bool value) static
Allocate memory for symbol table node.
Allocate new symbol table node with name and value set.
Parameters
[in] name symbol name
[in] value symbol value
Returns
new node, free with symbol_free()
Referenced by node_add(), and symbol_add().
symbol_add()
bool symbol_add (const char * name, bool value)
Add symbol to symbol table.
Add symbol called name with value value to symbol table.
Parameters
[in] name symbol name
[in] value symbol value
Returns
false on name collision
Referenced by add_machine_symbols(), and add_predef_symbols().
symbol_find()
symbol_t * symbol_find (const char * name)
Look up symbol by name.
Parameters
[in] name symbol name
Returns
node or NULL when not found
Referenced by get_identifier().
symbol_table_dump()
void symbol_table_dump (void)
Debug hook: dump symbol table on stdout.
Print symbol table in alphabetical order on stdout.
Referenced by vhk_parser_init().
symbol_table_free()
void symbol_table_free (void)
Free memory used by symbol table.
Referenced by vhk_parser_shutdown().
symbol_table_init()
void symbol_table_init (void)
Initialize symbol table.
Referenced by vhk_parser_init().
Variable Documentation
symbols
symbol_t* symbols = NULL static
Symbol table root node.
Referenced by symbol_add(), symbol_find(), symbol_table_dump(), symbol_table_free(), and symbol_table_init().