vsid: arch/shared/archdep_unix.h File Reference
archdep_unix.h File Reference
Miscellaneous UNIX-specific stuff - header.
#include "vice.h"
#include "archapi.h"
Macros
#define VICE_ARCHAPI_PRIVATE_API
#define ARCHDEP_MIDI_IN_DEV "/dev/midi"
Default MIDI devices.
#define ARCHDEP_MIDI_OUT_DEV "/dev/midi"
MIDI output dev.
#define ARCHDEP_FSDEVICE_DEFAULT_DIR "."
Filesystem-dependent constants.
#define ARCHDEP_DIR_SEP_STR "/"
directory separator as a string
#define ARCHDEP_DIR_SEP_CHR '/'
directory separator as an integer
#define ARCHDEP_FINDPATH_SEPARATOR_CHAR ':'
Path separator.
#define ARCHDEP_FINDPATH_SEPARATOR_STRING ":"
Separator character to split directory lists, as a string.
#define MODE_READ "r"
read mode (binary)
#define MODE_READ_TEXT "r"
read mode (text)
#define MODE_READ_WRITE "r+"
read/write mode
#define MODE_WRITE "w"
write mode (binary)
#define MODE_WRITE_TEXT "w"
write mode (text)
#define MODE_APPEND "a"
append mode
#define MODE_APPEND_READ_WRITE "a+"
append mode and read/write(?)
#define ARCHDEP_PRINTER_DEFAULT_DEV1 "print.dump"
Printer default devices.
#define ARCHDEP_PRINTER_DEFAULT_DEV2 "|lpr"
#define ARCHDEP_PRINTER_DEFAULT_DEV3 "|petlp -F PS|lpr"
#define ARCHDEP_RS232_DEV1 "/dev/ttyS0"
Default RS232 devices.
#define ARCHDEP_RS232_DEV2 "/dev/ttyS1"
#define ARCHDEP_RS232_DEV3 "127.0.0.1:25232"
#define ARCHDEP_RS232_DEV4 "|nc 127.0.0.1 25232"
#define ARCHDEP_MIDI_IN_DEV "/dev/midi"
Default MIDI devices.
#define ARCHDEP_MIDI_OUT_DEV "/dev/midi"
MIDI output dev.
#define ARCHDEP_RAWDRIVE_DEFAULT "/dev/fd0"
Default location of raw disk images.
#define ARCHDEP_LINE_DELIMITER "\n"
Standard line delimiter.
#define ARCHDEP_ETHERNET_DEFAULT_DEVICE "eth0"
Ethernet default device.
#define MAKE_SO_NAME_VERSION_PROTO(name, version) "lib" #name ".so." #version
#define ARCHDEP_MAKE_SO_NAME_VERSION(n, v) MAKE_SO_NAME_VERSION_PROTO(n, v)
add second level macro to allow expansion and stringification
#define ARCHDEP_OPENCBM_SO_NAME "libopencbm.so"
#define ARCHDEP_LAME_SO_NAME "libmp3lame.so"
#define ARCHDEP_SOCKET_ERROR errno
Functions
void archdep_signals_init (int do_core_dumps)
Set up signal handlers at emu init.
void archdep_signals_pipe_set (void)
void archdep_signals_pipe_unset (void)
Detailed Description
Miscellaneous UNIX-specific stuff - header.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Macro Definition Documentation
ARCHDEP_DIR_SEP_CHR
#define ARCHDEP_DIR_SEP_CHR '/'
directory separator as an integer
ARCHDEP_DIR_SEP_STR
#define ARCHDEP_DIR_SEP_STR "/"
directory separator as a string
ARCHDEP_ETHERNET_DEFAULT_DEVICE
#define ARCHDEP_ETHERNET_DEFAULT_DEVICE "eth0"
Ethernet default device.
ARCHDEP_FINDPATH_SEPARATOR_CHAR
#define ARCHDEP_FINDPATH_SEPARATOR_CHAR ':'
Path separator.
Separator character to split directory lists, as an integer
ARCHDEP_FINDPATH_SEPARATOR_STRING
#define ARCHDEP_FINDPATH_SEPARATOR_STRING ":"
Separator character to split directory lists, as a string.
ARCHDEP_FSDEVICE_DEFAULT_DIR
#define ARCHDEP_FSDEVICE_DEFAULT_DIR "."
Filesystem-dependent constants.
CWD
ARCHDEP_LAME_SO_NAME
#define ARCHDEP_LAME_SO_NAME "libmp3lame.so"
ARCHDEP_LINE_DELIMITER
#define ARCHDEP_LINE_DELIMITER "\n"
Standard line delimiter.
ARCHDEP_MAKE_SO_NAME_VERSION
#define ARCHDEP_MAKE_SO_NAME_VERSION (n, v) MAKE_SO_NAME_VERSION_PROTO(n, v)
add second level macro to allow expansion and stringification
ARCHDEP_MIDI_IN_DEV [1/2]
#define ARCHDEP_MIDI_IN_DEV "/dev/midi"
Default MIDI devices.
MIDI input dev
ARCHDEP_MIDI_IN_DEV [2/2]
#define ARCHDEP_MIDI_IN_DEV "/dev/midi"
Default MIDI devices.
MIDI input dev
ARCHDEP_MIDI_OUT_DEV [1/2]
#define ARCHDEP_MIDI_OUT_DEV "/dev/midi"
MIDI output dev.
ARCHDEP_MIDI_OUT_DEV [2/2]
#define ARCHDEP_MIDI_OUT_DEV "/dev/midi"
MIDI output dev.
ARCHDEP_OPENCBM_SO_NAME
#define ARCHDEP_OPENCBM_SO_NAME "libopencbm.so"
ARCHDEP_PRINTER_DEFAULT_DEV1
#define ARCHDEP_PRINTER_DEFAULT_DEV1 "print.dump"
Printer default devices.
ARCHDEP_PRINTER_DEFAULT_DEV2
#define ARCHDEP_PRINTER_DEFAULT_DEV2 "|lpr"
ARCHDEP_PRINTER_DEFAULT_DEV3
#define ARCHDEP_PRINTER_DEFAULT_DEV3 "|petlp -F PS|lpr"
ARCHDEP_RAWDRIVE_DEFAULT
#define ARCHDEP_RAWDRIVE_DEFAULT "/dev/fd0"
Default location of raw disk images.
ARCHDEP_RS232_DEV1
#define ARCHDEP_RS232_DEV1 "/dev/ttyS0"
Default RS232 devices.
ARCHDEP_RS232_DEV2
#define ARCHDEP_RS232_DEV2 "/dev/ttyS1"
ARCHDEP_RS232_DEV3
#define ARCHDEP_RS232_DEV3 "127.0.0.1:25232"
ARCHDEP_RS232_DEV4
#define ARCHDEP_RS232_DEV4 "|nc 127.0.0.1 25232"
ARCHDEP_SOCKET_ERROR
#define ARCHDEP_SOCKET_ERROR errno
MAKE_SO_NAME_VERSION_PROTO
#define MAKE_SO_NAME_VERSION_PROTO (name, version) "lib" #name ".so." #version
MODE_APPEND
#define MODE_APPEND "a"
append mode
MODE_APPEND_READ_WRITE
#define MODE_APPEND_READ_WRITE "a+"
append mode and read/write(?)
MODE_READ
#define MODE_READ "r"
read mode (binary)
MODE_READ_TEXT
#define MODE_READ_TEXT "r"
read mode (text)
MODE_READ_WRITE
#define MODE_READ_WRITE "r+"
read/write mode
MODE_WRITE
#define MODE_WRITE "w"
write mode (binary)
MODE_WRITE_TEXT
#define MODE_WRITE_TEXT "w"
write mode (text)
VICE_ARCHAPI_PRIVATE_API
#define VICE_ARCHAPI_PRIVATE_API
Function Documentation
archdep_signals_init()
void archdep_signals_init (int do_core_dumps)
Set up signal handlers at emu init.
Parameters
[in] do_core_dumps Do core dumps
Referenced by signals_init().
archdep_signals_pipe_set()
void archdep_signals_pipe_set (void)
Referenced by signals_pipe_set().
archdep_signals_pipe_unset()
void archdep_signals_pipe_unset (void)
Referenced by signals_pipe_unset().