vsid: arch/gtk3/vsidui.c File Reference
vsidui.c File Reference
Native GTK3 VSID UI.
#include "vice.h"
#include <stdio.h>
#include "vice_gtk3.h"
#include "lib.h"
#include "machine.h"
#include "ui.h"
#include "uisidattach.h"
#include "uivsidwindow.h"
#include "vicii.h"
#include "resources.h"
#include "actions-vsid.h"
#include "videomodelwidget.h"
#include "vsidcontrolwidget.h"
#include "vsidtuneinfowidget.h"
#include "vsidmainwidget.h"
#include "hvsc.h"
#include "vsidui.h"
Functions
void vsid_ui_close (void)
static int identify_canvas (video_canvas_t *canvas)
Identify the canvas used to create a window.
int vsid_ui_init (void)
Initialize the VSID UI.
Variables
static const vice_gtk3_radiogroup_entry_t vsid_vicii_models []
Video standard list for the model settings.
Detailed Description
Native GTK3 VSID UI.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
identify_canvas()
static int identify_canvas (video_canvas_t * canvas) static
Identify the canvas used to create a window.
Returns
window index on success, -1 on failure
Referenced by vsid_ui_init().
vsid_ui_close()
void vsid_ui_close (void)
Referenced by machine_specific_shutdown().
vsid_ui_init()
int vsid_ui_init (void)
Initialize the VSID UI.
Returns
0 on success, -1 on failure
Referenced by machine_specific_init().
Variable Documentation
vsid_vicii_models
const vice_gtk3_radiogroup_entry_t vsid_vicii_models[] static
Initial value:
= {
    { "PAL",             1  },
    { "NTSC",            2  },
    { "NTSC (old)",      3  },
    { "PAL-N/Drean",     4  },
    { NULL,             -1 }
}
Video standard list for the model settings.
Referenced by vsid_ui_init().