vsid: arch/shared/hotkeys/symtab.h File Reference
symtab.h File Reference
Symbol table for hotkeys - header.
#include <stdbool.h>
Data Structures
struct symbol_s
Symbol table node.
Typedefs
typedef struct symbol_s symbol_t
Symbol table node.
Functions
void symbol_table_init (void)
Initialize symbol table.
void symbol_table_free (void)
Free memory used by symbol table.
void symbol_table_dump (void)
Debug hook: dump symbol table on stdout.
bool symbol_add (const char *name, bool value)
Add symbol to symbol table.
symbol_t * symbol_find (const char *name)
Look up symbol by name.
Detailed Description
Symbol table for hotkeys - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Typedef Documentation
symbol_t
typedef struct symbol_s symbol_t
Symbol table node.
Binary search tree node making up the symbol table.
Function Documentation
symbol_add()
bool symbol_add (const char * name, bool value)
Add symbol to symbol table.
Add symbol called name with value value to symbol table.
Parameters
[in] name symbol name
[in] value symbol value
Returns
false on name collision
Referenced by add_machine_symbols(), and add_predef_symbols().
symbol_find()
symbol_t * symbol_find (const char * name)
Look up symbol by name.
Parameters
[in] name symbol name
Returns
node or NULL when not found
Referenced by get_identifier().
symbol_table_dump()
void symbol_table_dump (void)
Debug hook: dump symbol table on stdout.
Print symbol table in alphabetical order on stdout.
Referenced by vhk_parser_init().
symbol_table_free()
void symbol_table_free (void)
Free memory used by symbol table.
Referenced by vhk_parser_shutdown().
symbol_table_init()
void symbol_table_init (void)
Initialize symbol table.
Referenced by vhk_parser_init().