x128: fsdevice/fsdevice-filename.h File Reference
fsdevice-filename.h File Reference
#include "vdrive.h"
Functions
int fsdevice_limit_createnamelength (vdrive_t *vdrive, char *name)
int fsdevice_limit_namelength (vdrive_t *vdrive, uint8_t *name)
int fsdevice_limit_namelength_ascii (vdrive_t *vdrive, char *name)
char * fsdevice_expand_shortname (vdrive_t *vdrive, char *name)
char * fsdevice_expand_shortname_ascii (vdrive_t *vdrive, char *name)
Function Documentation
fsdevice_expand_shortname()
char * fsdevice_expand_shortname (vdrive_t * vdrive, char * name)
Referenced by fsdevice_flush(), fsdevice_flush_rename(), and fsdevice_open_file().
fsdevice_expand_shortname_ascii()
char * fsdevice_expand_shortname_ascii (vdrive_t * vdrive, char * name)
Referenced by fsdevice_flush().
fsdevice_limit_createnamelength()
int fsdevice_limit_createnamelength (vdrive_t * vdrive, char * name)
Referenced by fsdevice_flush(), fsdevice_flush_rename(), and fsdevice_open_file().
fsdevice_limit_namelength()
int fsdevice_limit_namelength (vdrive_t * vdrive, uint8_t * name)
Referenced by autostart_prg(), and command_directory_get().
fsdevice_limit_namelength_ascii()
int fsdevice_limit_namelength_ascii (vdrive_t * vdrive, char * name)