vsid: arch/gtk3/widgets/vsidplaylistwidget.h File Reference
vsidplaylistwidget.h File Reference
GTK3 playlist widget for VSID - header.
#include <gtk/gtk.h>
Functions
GtkWidget * vsid_playlist_widget_create (void)
Create main playlist widget.
gboolean vsid_playlist_append_file (const gchar *path)
Append path to the playlist.
void vsid_playlist_remove_file (gint row)
void vsid_playlist_first (void)
Play first tune in the playlist.
void vsid_playlist_previous (void)
Play previous tune in the playlist.
void vsid_playlist_next (void)
Play next tune in the playlist.
void vsid_playlist_last (void)
Play last tune in the playlist.
void vsid_playlist_add (void)
Show dialog to add files to the playlist.
void vsid_playlist_remove (gint row)
void vsid_playlist_remove_selection (void)
Remove selected tunes from the playlist.
void vsid_playlist_clear (void)
Clear playlist.
void vsid_playlist_load (void)
Show dialog to load a playlist.
void vsid_playlist_save (void)
Show dialog to save the playlist.
gint vsid_playlist_get_current_row (const gchar **path)
Get row number of currently selected tune.
Detailed Description
GTK3 playlist widget for VSID - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
vsid_playlist_add()
void vsid_playlist_add (void)
Show dialog to add files to the playlist.
vsid_playlist_append_file()
gboolean vsid_playlist_append_file (const gchar * path)
Append path to the playlist.
Parameters
[in] path path to SID file
Returns
TRUE on success, FALSE on failure
Referenced by add_files_callback(), on_drag_data_received(), and playlist_entry_handler().
vsid_playlist_clear()
void vsid_playlist_clear (void)
Clear playlist.
Shows confirmation dialog box before clearing.
Referenced by clear_playlist_callback(), and on_ctx_delete_all().
vsid_playlist_first()
void vsid_playlist_first (void)
Play first tune in the playlist.
Todo:
check result
vsid_playlist_get_current_row()
gint vsid_playlist_get_current_row (const gchar ** path)
Get row number of currently selected tune.
Parameters
[out] path path to SID file (optional, pass NULL to ignore
Returns
row number or -1 when no selection or multiple rows selected
Referenced by update_current_and_total(), and vsid_tune_info_widget_update().
vsid_playlist_last()
void vsid_playlist_last (void)
Play last tune in the playlist.
vsid_playlist_load()
void vsid_playlist_load (void)
Show dialog to load a playlist.
vsid_playlist_next()
void vsid_playlist_next (void)
Play next tune in the playlist.
Referenced by vsid_tune_info_widget_update().
vsid_playlist_previous()
void vsid_playlist_previous (void)
Play previous tune in the playlist.
vsid_playlist_remove()
void vsid_playlist_remove (gint row)
vsid_playlist_remove_file()
void vsid_playlist_remove_file (gint row)
vsid_playlist_remove_selection()
void vsid_playlist_remove_selection (void)
Remove selected tunes from the playlist.
Referenced by on_btn_playlist_remove_clicked(), and on_ctx_delete_selected().
vsid_playlist_save()
void vsid_playlist_save (void)
Show dialog to save the playlist.
vsid_playlist_widget_create()
GtkWidget * vsid_playlist_widget_create (void)
Create main playlist widget.
Returns
GtkGrid
Referenced by vsid_main_widget_create().