vsid: c64/c64parallel.h File Reference
c64parallel.h File Reference
#include "types.h"
Functions
void parallel_cable_cpu_execute (int type)
void parallel_cable_cpu_write (int type, uint8_t data)
void parallel_cable_cpu_pulse (int type)
uint8_t parallel_cable_cpu_read (int type, uint8_t data)
void parallel_cable_cpu_undump (int type, uint8_t data)
int parallel_cable_cpu_resources_init (void)
Function Documentation
parallel_cable_cpu_execute()
void parallel_cable_cpu_execute (int type)
Referenced by parallel_cable_cpu_pulse(), parallel_cable_cpu_read(), parallel_cable_cpu_write(), and read_ciaicr().
parallel_cable_cpu_pulse()
void parallel_cable_cpu_pulse (int type)
< dolphin-dos 3 userport cable
< formel 64 cartridge
< 21 second backup userport cable
Todo:
FIXME: don't do this for the 21.sec cable
Referenced by userport_par_cable_store_pbx().
parallel_cable_cpu_read()
uint8_t parallel_cable_cpu_read (int type, uint8_t data)
Referenced by userport_par_cable_read_pbx().
parallel_cable_cpu_resources_init()
int parallel_cable_cpu_resources_init (void)
Referenced by machine_resources_init().
parallel_cable_cpu_undump()
void parallel_cable_cpu_undump (int type, uint8_t data)
Referenced by undump_ciapb().
parallel_cable_cpu_write()
void parallel_cable_cpu_write (int type, uint8_t data)
Referenced by userport_par_cable_store_pbx().