vsid: arch/gtk3/widgets/base/resourceswitch.h File Reference
resourceswitch.h File Reference
Gtk switch connected to a resource - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
GtkWidget * vice_gtk3_resource_switch_new (const char *resource)
Create switch to toggle resource.
GtkWidget * vice_gtk3_resource_switch_new_sprintf (const char *fmt,...)
Create switch to toggle a resource.
gboolean vice_gtk3_resource_switch_set (GtkWidget *widget, gboolean value)
Set new value for widget.
gboolean vice_gtk3_resource_switch_reset (GtkWidget *widget)
Reset state to the value during instanciation.
gboolean vice_gtk3_resource_switch_factory (GtkWidget *widget)
Reset switch to factory value.
gboolean vice_gtk3_resource_switch_sync (GtkWidget *widget)
Synchronize widget with its associated resource value.
void vice_gtk3_resource_switch_add_callback (GtkWidget *widget, void(*callback)(GtkWidget *, gboolean))
Add user callback to resource switch.
Detailed Description
Gtk switch connected to a resource - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
vice_gtk3_resource_switch_add_callback()
void vice_gtk3_resource_switch_add_callback (GtkWidget * widget, void(*)(GtkWidget *, gboolean) callback)
Add user callback to resource switch.
Parameters
[in] widget resource switch
[in] callback function to call on succesfull resource changes
Referenced by settings_scpu64_widget_create().
vice_gtk3_resource_switch_factory()
gboolean vice_gtk3_resource_switch_factory (GtkWidget * widget)
Reset switch to factory value.
Parameters
[in,out] widget check button
Returns
TRUE if the widget was set to its factory value
vice_gtk3_resource_switch_new()
GtkWidget * vice_gtk3_resource_switch_new (const char * resource)
Create switch to toggle resource.
Creates a switch to toggle resource. Makes a heap-allocated copyof the resource name so that initializing this widget with a constructed/temporary resource name works as well.
Parameters
[in] resource resource name
Note
The resource name is stored in the "ResourceName" property.
Returns
GtkSwitch
Referenced by create_isepic_switch_widget(), create_mmc64_jumper_widget(), create_rescue_mode_widget(), create_switch(), settings_easyflash_widget_create(), settings_rrnetmk3_widget_create(), settings_scpu64_widget_create(), and vice_gtk3_resource_switch_new_sprintf().
vice_gtk3_resource_switch_new_sprintf()
GtkWidget * vice_gtk3_resource_switch_new_sprintf (const char * fmt, ...)
Create switch to toggle a resource.
Creates a switch to toggle a resource. Makes a heap-allocated copy of the resource name so initializing this widget with a constructed/temporary resource name works as well. The resource name can be constructed with a printf() format string.
Parameters
[in] fmt resource name format string
Note
The resource name is stored in the "ResourceName" property.
Returns
new switch
Referenced by create_autofire_enable_widget().
vice_gtk3_resource_switch_reset()
gboolean vice_gtk3_resource_switch_reset (GtkWidget * widget)
Reset state to the value during instanciation.
Parameters
[in,out] widget resource switch
Returns
TRUE if the widget was reset to its original state
vice_gtk3_resource_switch_set()
gboolean vice_gtk3_resource_switch_set (GtkWidget * widget, gboolean value)
Set new value for widget.
Parameters
[in,out] widget switch
[in] value new value
Returns
bool
Referenced by vice_gtk3_resource_switch_factory(), and vice_gtk3_resource_switch_reset().
vice_gtk3_resource_switch_sync()
gboolean vice_gtk3_resource_switch_sync (GtkWidget * widget)
Synchronize widget with its associated resource value.
Parameters
[in,out] widget resource switch widget
Returns
TRUE if the widget was synchronized