x128: monitor/monitor_network.c File Reference
monitor_network.c File Reference
Monitor implementation - network access.
#include "vice.h"
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "monitor.h"
#include "monitor_network.h"
#include "montypes.h"
#include "resources.h"
#include "ui.h"
#include "uiapi.h"
#include "util.h"
#include "vicesocket.h"
Macros
#define ADDR_LIMIT(x) ((uint16_t)(addr_mask(x)))
Functions
int monitor_network_transmit (const char *buffer, size_t buffer_length)
static void monitor_network_quit (void)
int monitor_network_receive (char *buffer, size_t buffer_length)
static int monitor_network_data_available (void)
void monitor_check_remote (void)
static char * monitor_network_extract_text_command_line (char *pbuffer, int buffer_size, int *pbuffer_pos)
int monitor_network_get_command_line (char **prompt)
static int monitor_network_activate (void)
static int monitor_network_deactivate (void)
static int set_monitor_enabled (int value, void *param)
set the network monitor to the enabled or disabled state
static int set_server_address (const char *name, void *param)
set the network address of the network monitor
int monitor_network_resources_init (void)
initialize the network monitor resources
void monitor_network_resources_shutdown (void)
uninitialize the network monitor resources
int monitor_network_cmdline_options_init (void)
initialize the command-line options'
vice_network_socket_t * monitor_get_connected_socket (void)
int monitor_is_remote (void)
ui_jam_action_t monitor_network_ui_jam_dialog (const char *format,...)
Variables
static vice_network_socket_t * listen_socket = NULL
static vice_network_socket_t * connected_socket = NULL
static char * monitor_server_address = NULL
static int monitor_enabled = 0
static const resource_string_t resources_string []
string resources used by the network monitor module
static const resource_int_t resources_int []
integer resources used by the network monitor module
static const cmdline_option_t cmdline_options []
Detailed Description
Monitor implementation - network access.
Author
Spiro Trikaliotis spiro.nosp@m..tri.nosp@m.kalio.nosp@m.tis@.nosp@m.gmx.d.nosp@m.e
Macro Definition Documentation
ADDR_LIMIT
#define ADDR_LIMIT (x) ((uint16_t)(addr_mask(x)))
Function Documentation
monitor_check_remote()
void monitor_check_remote (void)
Referenced by monitor_vsync_hook(), and uimon_in().
monitor_get_connected_socket()
vice_network_socket_t * monitor_get_connected_socket (void)
Referenced by uimon_in().
monitor_is_remote()
int monitor_is_remote (void)
Referenced by drive_jam(), machine_jam(), mon_out(), mon_petscii_out(), mon_petscii_upper_out(), mon_scrcode_out(), mon_scrcode_upper_out(), monitor_close(), monitor_open(), and uimon_in().
monitor_network_activate()
static int monitor_network_activate (void) static
Referenced by set_monitor_enabled(), and set_server_address().
monitor_network_cmdline_options_init()
int monitor_network_cmdline_options_init (void)
initialize the command-line options'
Returns
0 on success, else -1.
Remarks
Registers the command-line options
Referenced by init_cmdline_options().
monitor_network_data_available()
static int monitor_network_data_available (void) static
Referenced by monitor_check_remote(), and monitor_network_get_command_line().
monitor_network_deactivate()
static int monitor_network_deactivate (void) static
Referenced by monitor_network_resources_shutdown(), set_monitor_enabled(), and set_server_address().
monitor_network_extract_text_command_line()
static char * monitor_network_extract_text_command_line (char * pbuffer, int buffer_size, int * pbuffer_pos) static
Referenced by monitor_network_get_command_line().
monitor_network_get_command_line()
int monitor_network_get_command_line (char ** prompt)
Referenced by uimon_in().
monitor_network_quit()
static void monitor_network_quit (void) static
Referenced by monitor_network_get_command_line(), monitor_network_receive(), and monitor_network_resources_shutdown().
monitor_network_receive()
int monitor_network_receive (char * buffer, size_t buffer_length)
Referenced by monitor_network_get_command_line().
monitor_network_resources_init()
int monitor_network_resources_init (void)
initialize the network monitor resources
Returns
0 on success, else -1.
Remarks
Registers the string and the integer resources
Referenced by init_resources().
monitor_network_resources_shutdown()
void monitor_network_resources_shutdown (void)
uninitialize the network monitor resources
Referenced by cmdline_help(), and machine_shutdown().
monitor_network_transmit()
int monitor_network_transmit (const char * buffer, size_t buffer_length)
Referenced by mon_out(), mon_petscii_out(), mon_petscii_upper_out(), mon_scrcode_out(), mon_scrcode_upper_out(), monitor_network_ui_jam_dialog(), and uimon_in().
monitor_network_ui_jam_dialog()
ui_jam_action_t monitor_network_ui_jam_dialog (const char * format, ...)
Referenced by drive_jam(), and machine_jam().
set_monitor_enabled()
static int set_monitor_enabled (int value, void * param) static
set the network monitor to the enabled or disabled state
Parameters
val if 0, disable the network monitor; else, enable it.
param unused
Returns
0 on success. else -1.
set_server_address()
static int set_server_address (const char * name, void * param) static
set the network address of the network monitor
Parameters
name pointer to a buffer which holds the network server addresss.
param unused
Returns
0 on success, else -1.
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-remotemonitor", SET_RESOURCE,  0 ,
      NULL, NULL, "MonitorServer", (resource_value_t)1,
      NULL, "Enable remote monitor" },
    { "+remotemonitor", SET_RESOURCE,  0 ,
      NULL, NULL, "MonitorServer", (resource_value_t)0,
      NULL, "Disable remote monitor" },
    { "-remotemonitoraddress", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "MonitorServerAddress", NULL,
      "<Name>", "The local address the remote monitor should bind to" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by monitor_network_cmdline_options_init().
connected_socket
vice_network_socket_t* connected_socket = NULL static
Referenced by monitor_get_connected_socket(), monitor_is_remote(), monitor_network_data_available(), monitor_network_quit(), monitor_network_receive(), and monitor_network_transmit().
listen_socket
vice_network_socket_t* listen_socket = NULL static
Referenced by monitor_network_activate(), monitor_network_data_available(), and monitor_network_deactivate().
monitor_enabled
int monitor_enabled = 0 static
Referenced by set_monitor_enabled(), and set_server_address().
monitor_server_address
char* monitor_server_address = NULL static
Referenced by monitor_network_activate(), monitor_network_resources_shutdown(), and set_server_address().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "MonitorServer", 0, RES_EVENT_STRICT, (resource_value_t)0,
      &monitor_enabled, set_monitor_enabled, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
integer resources used by the network monitor module
Referenced by monitor_network_resources_init().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "MonitorServerAddress", "ip4://127.0.0.1:6510", RES_EVENT_NO, NULL,
      &monitor_server_address, set_server_address, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
string resources used by the network monitor module
Referenced by monitor_network_resources_init().