vsid: diskimage/realimage.c File Reference
realimage.c File Reference
#include "vice.h"
#include <stdio.h>
#include "diskimage.h"
#include "log.h"
#include "machine-bus.h"
#include "realimage.h"
#include "types.h"
Functions
void realimage_media_create (disk_image_t *image)
void realimage_media_destroy (disk_image_t *image)
int realimage_open (disk_image_t *image)
int realimage_close (disk_image_t *image)
int realimage_read_sector (const disk_image_t *image, uint8_t *buf, const disk_addr_t *dadr)
int realimage_write_sector (disk_image_t *image, const uint8_t *buf, const disk_addr_t *dadr)
void realimage_init (void)
Variables
static log_t realimage_log = ((log_t)-2)
Function Documentation
realimage_close()
int realimage_close (disk_image_t * image)
Referenced by disk_image_close().
realimage_init()
void realimage_init (void)
Referenced by disk_image_init().
realimage_media_create()
void realimage_media_create (disk_image_t * image)
Referenced by disk_image_media_create().
realimage_media_destroy()
void realimage_media_destroy (disk_image_t * image)
Referenced by disk_image_media_destroy().
realimage_open()
int realimage_open (disk_image_t * image)
Referenced by disk_image_open().
realimage_read_sector()
int realimage_read_sector (const disk_image_t * image, uint8_t * buf, const disk_addr_t * dadr)
Referenced by disk_image_read_sector().
realimage_write_sector()
int realimage_write_sector (disk_image_t * image, const uint8_t * buf, const disk_addr_t * dadr)
Referenced by disk_image_write_sector().
Variable Documentation
realimage_log
log_t realimage_log = ((log_t)-2) static
Referenced by realimage_init().