vsid: arch/gtk3/archdep.c File Reference
archdep.c File Reference
Wrappers for architecture/OS-specific code.
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <glib.h>
#include <glib/gstdio.h>
#include "archdep.h"
#include "debug_gtk3.h"
#include "findpath.h"
#include "hotkeys.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "util.h"
#include "uiapi.h"
Functions
int archdep_init (int *argc, char **argv)
Arch-dependent init.
void archdep_shutdown (void)
Architecture-dependent shutdown handler.
Variables
static char * argv0 = NULL
Reference to argv[0].
Detailed Description
Wrappers for architecture/OS-specific code.
I've decided to use GLib's use of the XDG specification and the standard way of using paths on Windows. So some files may not be where the older ports expect them to be. For example, vicerc will be in $HOME/.config/vice now, not $HOME/.vice. – compyx
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
archdep_init()
int archdep_init (int * argc, char ** argv)
Arch-dependent init.
Do not include this header file, include ‘archdep.h’ instead.
Parameters
[in] argc pointer to argument count
[in] argv argument vector
Returns
0
Referenced by main_program().
archdep_shutdown()
void archdep_shutdown (void)
Architecture-dependent shutdown handler.
Free everything on exit.
Referenced by cmdline_help(), and machine_shutdown().
Variable Documentation
argv0
char* argv0 = NULL static
Reference to argv[0].
!
Todo:
FIXME: this is only used twice I think, better pass this as an argument to the functions using it
Referenced by archdep_init(), archdep_program_path_set_argv0(), and archdep_shutdown().