x128: vdrive/vdrive-iec.h File Reference
vdrive-iec.h File Reference
#include "types.h"
Functions
void vdrive_iec_init (void)
int vdrive_iec_open (struct vdrive_s *vdrive, const uint8_t *name, unsigned int length, unsigned int secondary, struct cbmdos_cmd_parse_s *cmd_parse_ext)
Generic IEC interface.
int vdrive_iec_close (struct vdrive_s *vdrive, unsigned int secondary)
int vdrive_iec_read (struct vdrive_s *vdrive, uint8_t *data, unsigned int secondary)
int vdrive_iec_write (struct vdrive_s *vdrive, uint8_t data, unsigned int secondary)
void vdrive_iec_flush (struct vdrive_s *vdrive, unsigned int secondary)
int vdrive_iec_attach (unsigned int unit, const char *name)
void vdrive_iec_listen (struct vdrive_s *vdrive, unsigned int secondary)
int vdrive_iec_update_dirent (struct vdrive_s *vdrive, unsigned int channel)
called by vdrive-rel
void vdrive_iec_unswitch (struct vdrive_s *vdrive, struct bufferinfo_s *p)
int vdrive_iec_switch (struct vdrive_s *vdrive, struct bufferinfo_s *p)
Function Documentation
vdrive_iec_attach()
int vdrive_iec_attach (unsigned int unit, const char * name)
Referenced by file_system_set_serial_hooks().
vdrive_iec_close()
int vdrive_iec_close (struct vdrive_s * vdrive, unsigned int secondary)
Todo:
FIXME: Is this correct?
vdrive_close_all_channels(vdrive);
Referenced by autostart_prg_with_disk_image(), chain_cmd(), copy_cmd(), entry_cmd(), extract_cmd_common(), iec_open_read(), iec_open_read_sequential(), iec_open_write(), mon_file_close(), read_cmd(), read_geos_cmd(), unlynx_loop(), vdrive_close_all_channels(), vdrive_close_all_channels_partition(), and vdrive_iec_attach().
vdrive_iec_flush()
void vdrive_iec_flush (struct vdrive_s * vdrive, unsigned int secondary)
Referenced by vdrive_iec_attach().
vdrive_iec_init()
void vdrive_iec_init (void)
Referenced by vdrive_init().
vdrive_iec_listen()
void vdrive_iec_listen (struct vdrive_s * vdrive, unsigned int secondary)
Referenced by vdrive_iec_attach().
vdrive_iec_open()
int vdrive_iec_open (struct vdrive_s * vdrive, const uint8_t * name, unsigned int length, unsigned int secondary, struct cbmdos_cmd_parse_s * cmd_parse_ext)
Generic IEC interface.
Todo:
FIXME: "file" has requested buffer
< should match FILEIO_TYPE_xxx
< should match FILEIO_TYPE_xxx
< for relative files
< for relative files
Referenced by autostart_prg_with_disk_image(), chain_cmd(), copy_cmd(), entry_cmd(), extract_cmd_common(), mon_file_open(), read_cmd(), read_geos_cmd(), unlynx_loop(), vdrive_iec_attach(), and write_geos_cmd().
vdrive_iec_read()
int vdrive_iec_read (struct vdrive_s * vdrive, uint8_t * data, unsigned int secondary)
Referenced by copy_cmd(), extract_cmd_common(), mon_file_read(), read_cmd(), and vdrive_iec_attach().
vdrive_iec_switch()
int vdrive_iec_switch (struct vdrive_s * vdrive, struct bufferinfo_s * p)
< directory sector number
vdrive_bam_read_bam(vdrive);
Referenced by iec_close_sequential(), iec_open_read_directory(), iec_read_sequential(), vdrive_dir_next_directory(), vdrive_iec_write(), vdrive_rel_close(), vdrive_rel_listen(), vdrive_rel_position(), vdrive_rel_read(), and vdrive_rel_write().
vdrive_iec_unswitch()
void vdrive_iec_unswitch (struct vdrive_s * vdrive, struct bufferinfo_s * p)
Referenced by iec_close_sequential(), iec_open_read_directory(), iec_read_sequential(), vdrive_iec_open(), vdrive_iec_write(), vdrive_rel_close(), vdrive_rel_listen(), vdrive_rel_position(), vdrive_rel_position_internal(), vdrive_rel_read(), and vdrive_rel_write().
vdrive_iec_update_dirent()
int vdrive_iec_update_dirent (struct vdrive_s * vdrive, unsigned int channel)
called by vdrive-rel
Referenced by iec_close_sequential(), vdrive_rel_add_sector(), and vdrive_rel_grow().
vdrive_iec_write()
int vdrive_iec_write (struct vdrive_s * vdrive, uint8_t data, unsigned int secondary)
Referenced by autostart_prg_with_disk_image(), copy_cmd(), mon_file_write(), unlynx_loop(), vdrive_iec_attach(), and vdrive_iec_open().