vsid: debug.h File Reference
debug.h File Reference
#include "types.h"
Data Structures
struct debug_s
Macros
#define DEBUG_NORMAL 0
Manually defined.
#define DEBUG_SMALL 1
#define DEBUG_HISTORY 2
#define DEBUG_AUTOPLAY 3
#define DEBUG_HISTORY_MAXFILESIZE 4000000
#define DEBUG_MAXLINELEN 128
#define DEBUG_IEC_DRV_WRITE(_data)
#define DEBUG_IEC_DRV_READ(_data)
#define DEBUG_IEC_BUS_WRITE(_data)
#define DEBUG_IEC_BUS_READ(_data)
#define STATIC_ASSERT(_x)
Typedefs
typedef struct debug_s debug_t
Functions
int debug_resources_init (void)
int debug_cmdline_options_init (void)
void debug_set_machine_parameter (unsigned int cycles, unsigned int lines)
void debug_maincpu (uint32_t reg_pc, CLOCK mclk, const char *dis, uint8_t reg_a, uint8_t reg_x, uint8_t reg_y, uint8_t reg_sp)
void debug_main65816cpu (uint32_t reg_pc, CLOCK mclk, const char *dis, uint16_t reg_c, uint16_t reg_x, uint16_t reg_y, uint16_t reg_sp, uint8_t reg_pbr)
void debug_drive (uint32_t reg_pc, CLOCK mclk, const char *dis, uint8_t reg_a, uint8_t reg_x, uint8_t reg_y, uint8_t reg_sp, unsigned int driveno)
void debug_irq (struct interrupt_cpu_status_s *cs, CLOCK iclk)
void debug_nmi (struct interrupt_cpu_status_s *cs, CLOCK iclk)
void debug_dma (const char *txt, CLOCK dclk, CLOCK num)
void debug_text (const char *text)
void debug_start_recording (void)
void debug_stop_recording (void)
void debug_start_playback (void)
void debug_stop_playback (void)
void debug_set_milestone (void)
void debug_reset_milestone (void)
void debug_check_autoplay_mode (void)
Variables
debug_t debug
Macro Definition Documentation
DEBUG_AUTOPLAY
#define DEBUG_AUTOPLAY 3
DEBUG_HISTORY
#define DEBUG_HISTORY 2
DEBUG_HISTORY_MAXFILESIZE
#define DEBUG_HISTORY_MAXFILESIZE 4000000
DEBUG_IEC_BUS_READ
#define DEBUG_IEC_BUS_READ (_data)
DEBUG_IEC_BUS_WRITE
#define DEBUG_IEC_BUS_WRITE (_data)
DEBUG_IEC_DRV_READ
#define DEBUG_IEC_DRV_READ (_data)
DEBUG_IEC_DRV_WRITE
#define DEBUG_IEC_DRV_WRITE (_data)
DEBUG_MAXLINELEN
#define DEBUG_MAXLINELEN 128
DEBUG_NORMAL
#define DEBUG_NORMAL 0
Manually defined.
To enable/disable this option by hand change the 0 below to 1.
configure defined, not valid when using an IDE
IDE defined.
DEBUG_SMALL
#define DEBUG_SMALL 1
STATIC_ASSERT
#define STATIC_ASSERT (_x)
Value:
    { \
        uint8_t dummy[1 - 2 * ((_x) == 0)]; \
        dummy[0] = dummy[0] - dummy[0]; /* prevent "unused variable" warning */ \
    }
Typedef Documentation
debug_t
typedef struct debug_s debug_t
Function Documentation
debug_check_autoplay_mode()
void debug_check_autoplay_mode (void)
Referenced by vsync_do_vsync().
debug_cmdline_options_init()
int debug_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
debug_dma()
void debug_dma (const char * txt, CLOCK dclk, CLOCK num)
Referenced by dma_maincpu_steal_cycles().
debug_drive()
void debug_drive (uint32_t reg_pc, CLOCK mclk, const char * dis, uint8_t reg_a, uint8_t reg_x, uint8_t reg_y, uint8_t reg_sp, unsigned int driveno)
debug_irq()
void debug_irq (struct interrupt_cpu_status_s * cs, CLOCK iclk)
debug_main65816cpu()
void debug_main65816cpu (uint32_t reg_pc, CLOCK mclk, const char * dis, uint16_t reg_c, uint16_t reg_x, uint16_t reg_y, uint16_t reg_sp, uint8_t reg_pbr)
debug_maincpu()
void debug_maincpu (uint32_t reg_pc, CLOCK mclk, const char * dis, uint8_t reg_a, uint8_t reg_x, uint8_t reg_y, uint8_t reg_sp)
debug_nmi()
void debug_nmi (struct interrupt_cpu_status_s * cs, CLOCK iclk)
debug_reset_milestone()
void debug_reset_milestone (void)
Referenced by event_record_reset_milestone_trap().
debug_resources_init()
int debug_resources_init (void)
Referenced by machine_resources_init().
debug_set_machine_parameter()
void debug_set_machine_parameter (unsigned int cycles, unsigned int lines)
Referenced by machine_change_timing().
debug_set_milestone()
void debug_set_milestone (void)
Referenced by event_record_set_milestone_trap().
debug_start_playback()
void debug_start_playback (void)
Referenced by event_playback_start_trap().
debug_start_recording()
void debug_start_recording (void)
Referenced by event_record_start_trap().
debug_stop_playback()
void debug_stop_playback (void)
Referenced by event_playback_stop().
debug_stop_recording()
void debug_stop_recording (void)
Referenced by event_record_stop_trap().
debug_text()
void debug_text (const char * text)
Variable Documentation
debug
debug_t debug extern
Referenced by set_do_core_dumps().