x128: arch/gtk3/widgets/base/openfiledialog.c File Reference
openfiledialog.c File Reference
GtkFileChooser wrapper to open a file.
#include "vice.h"
#include <gtk/gtk.h>
#include "debug_gtk3.h"
#include "filechooserhelpers.h"
#include "log.h"
#include "mainlock.h"
#include "ui.h"
#include "openfiledialog.h"
Functions
static void on_response (GtkDialog *dialog, gint response_id, gpointer data)
Response handler for the open-file dialog.
GtkWidget * vice_gtk3_open_file_dialog (const char *title, const char *filter_desc, const char **filter_list, const char *path, void(*callback)(GtkDialog *, gchar *, gpointer), gpointer param)
Create an 'open file' dialog.
GtkWidget * vice_gtk3_open_create_file_dialog (const char *title, const char *proposed, gboolean confirm, const char *path, void(*callback)(GtkDialog *, gchar *, gpointer), gpointer param)
Create a 'open or create file' dialog.
Variables
static void(* filename_cb)(GtkDialog *, char *, gpointer)
Function to call on file-dialog's "accept" action.
Detailed Description
GtkFileChooser wrapper to open a file.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_response()
static void on_response (GtkDialog * dialog, gint response_id, gpointer data) static
Response handler for the open-file dialog.
Parameters
[in] dialog open-file dialog
[in] response_id response ID
[in] data optional data of callback
Referenced by vice_gtk3_open_create_file_dialog(), and vice_gtk3_open_file_dialog().
vice_gtk3_open_create_file_dialog()
GtkWidget * vice_gtk3_open_create_file_dialog (const char * title, const char * proposed, gboolean confirm, const char * path, void(*)(GtkDialog *, gchar *, gpointer) callback, gpointer param)
Create a 'open or create file' dialog.
Parameters
[in] title dialog title
[in] proposed proposed file name (optional)
[in] confirm confirm overwriting an existing file
[in] path set starting directory (optional)
[in] callback callback to trigger on response
[in] param extra data for callback (optional)
Returns
GtkDialog
Note
the filename passed to the callback is allocated by GLib and needs to be freed after use with g_free()
vice_gtk3_open_file_dialog()
GtkWidget * vice_gtk3_open_file_dialog (const char * title, const char * filter_desc, const char ** filter_list, const char * path, void(*)(GtkDialog *, gchar *, gpointer) callback, gpointer param)
Create an 'open file' dialog.
Parameters
[in] title dialog title
[in] filter_desc file filter name
[in] filter_list list of file type filters, NULL-terminated
[in] path directory to use (optional)
[in] callback callback to trigger on response
[in] param extra data for callback (optional)
Returns
GtkDialog
Note
the filename passed to the callback is allocated by GLib and needs to be freed after use with g_free()
Referenced by load_snapshot_trap_impl(), on_browse_clicked(), on_eeprom_browse_clicked(), on_load_romset_clicked(), on_resource_browser_browse_clicked(), settings_load_from_action(), ui_hotkeys_load_dialog_show(), and vsid_playlist_load().
Variable Documentation
filename_cb
void(* filename_cb) (GtkDialog *, char *, gpointer) (GtkDialog * , char * , gpointer) static
Function to call on file-dialog's "accept" action.
Referenced by on_response(), vice_gtk3_open_create_file_dialog(), and vice_gtk3_open_file_dialog().