vsid: c64/c64scmodel.c File Reference
c64scmodel.c File Reference
#include "vice.h"
#include <string.h>
#include "c64.h"
#include "c64iec.h"
#include "c64keyboard.h"
#include "c64model.h"
#include "c64rom.h"
#include "cia.h"
#include "machine.h"
#include "resources.h"
#include "sid.h"
#include "tapeport.h"
#include "types.h"
#include "userport.h"
#include "vicii.h"
Data Structures
struct model_s
Macros
#define CIA_MODEL_DEFAULT_OLD CIA_MODEL_6526
#define CIA_MODEL_DEFAULT_NEW CIA_MODEL_6526A
Functions
static int c64model_get_temp (int vicii_model, int sid_model, int glue_logic, int cia1model, int cia2model, int board, int iecreset, const char *chargen, int kernalrev)
static void c64model_set_temp (int model, int *vicii_model, int *sid_model, int *glue_logic, int *cia1model, int *cia2model, int *board, int *iecreset, const char *chargen, int *kernalrev)
static int is_new_sid (int model)
static int is_new_cia (int model)
int c64model_get_model (c64model_details_t *details)
get model from details
int c64model_get (void)
void c64model_set_details (c64model_details_t *details, int model)
get details for model
void c64model_set (int model)
Variables
static const struct model_s c64models []
Macro Definition Documentation
CIA_MODEL_DEFAULT_NEW
#define CIA_MODEL_DEFAULT_NEW CIA_MODEL_6526A
CIA_MODEL_DEFAULT_OLD
#define CIA_MODEL_DEFAULT_OLD CIA_MODEL_6526
Function Documentation
c64model_get()
int c64model_get (void)
Referenced by c64model_set().
c64model_get_model()
int c64model_get_model (c64model_details_t * details)
get model from details
c64model_get_temp()
static int c64model_get_temp (int vicii_model, int sid_model, int glue_logic, int cia1model, int cia2model, int board, int iecreset, const char * chargen, int kernalrev) static
Referenced by c64model_get(), c64model_get_model(), and c64model_set_temp().
c64model_set()
void c64model_set (int model)
c64model_set_details()
void c64model_set_details (c64model_details_t * details, int model)
get details for model
c64model_set_temp()
static void c64model_set_temp (int model, int * vicii_model, int * sid_model, int * glue_logic, int * cia1model, int * cia2model, int * board, int * iecreset, const char * chargen, int * kernalrev) static
Referenced by c64model_set_details().
is_new_cia()
static int is_new_cia (int model) static
< "old"
< "new"
Referenced by c64model_get_temp().
is_new_sid()
static int is_new_sid (int model) static
Referenced by c64model_get_temp(), c64model_set(), and c64model_set_temp().
Variable Documentation
c64models
const struct model_s c64models[] static
Initial value:
= {
    {  0 ,  1 ,  0 ,
        0   ,  0 ,  0 ,  0 ,
       1 ,  1 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-901225-01.bin" ,  3   },
    {  1 ,  1 ,  0 ,
        1   ,  1 ,  1 ,  0 ,
       0 ,  1 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-901225-01.bin" ,  3   },
    {  2 ,  1 ,  0 ,
        0   ,  0 ,  0 ,  0 ,
       1 ,  1 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-901225-01.bin" ,  2   },
    {  3 ,  2 ,  0 ,
        0   ,  0 ,  0 ,  0 ,
       1 ,  1 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-901225-01.bin" ,  3   },
    {  4 ,  2 ,  0 ,
        1   ,  1 ,  1 ,  0 ,
       0 ,  1 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-901225-01.bin" ,  3   },
    {  5 ,  3 ,  0 ,
        0   ,  0 ,  0 ,  0 ,
       1 ,  1 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-901225-01.bin" ,  1   },
    {  6 ,  4 ,  0 ,
        0   ,  0 ,  0 ,  0 ,
       1 ,  1 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-901225-01.bin" ,  3   },
    {  0 ,  1 ,  1 ,
        0   ,  0 ,  0 ,  0 ,
       1 ,  0 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-901225-01.bin" ,  67   },
    {  3 ,  2 ,  1 ,
        0   ,  0 ,  0 ,  0 ,
       1 ,  0 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-901225-01.bin" ,  67   },
    {  3 ,  2 ,  0 ,
        0   ,  0 ,  0 ,  0 ,
       1 ,  1 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-906143-02.bin" ,  0   },
    {  1 ,  1 ,  0 ,
        1   ,  1 ,  1 ,  0 ,
       0 ,  0 ,  0 ,  0 ,  0 ,  1 ,
       "chargen-901225-01.bin" ,  39   },
    {  0 ,  1 ,  0 ,
        0   ,  0 ,  0 ,  0 ,
       1 ,  1 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-901225-01.bin" ,  100   },
    {  3 ,  2 ,  0 ,
        0   ,  0 ,  0 ,  0 ,
       1 ,  1 ,  1 ,  1 ,  1 ,  1 ,
       "chargen-901225-01.bin" ,  100   },
    {  3 ,  2 ,  0 ,
        0   ,  0 ,  0 ,  1 ,
       1 ,  1 ,  0 ,  0 ,  1 ,  0 ,
       "chargen-901225-01.bin" ,  -2   },
}
Referenced by c64model_get_temp(), c64model_set(), and c64model_set_temp().