x128: reSID Namespace Reference
reSID Namespace Reference
Data Structures
class EnvelopeGenerator
class ExternalFilter
class Filter
struct mixer_offset
struct mixer_offset< 0 >
struct mixer_offset< 1 >
struct model_filter_init_t
class PointPlotter
class Potentiometer
class SID
struct summer_offset
struct summer_offset< 0 >
class Voice
class WaveformGenerator
Functions
void build_dac_table (unsigned short *dac, int bits, double _2R_div_R, bool term)
static double log1p (double x)
static double log1p (double x)
short clip (int input)
short amplify (int input, int scaleFactor)
void cubic_coefficients (double x1, double y1, double x2, double y2, double k1, double k2, double &a, double &b, double &c, double &d)
template<class PointPlotter >
void interpolate_brute_force (double x1, double y1, double x2, double y2, double k1, double k2, PointPlotter plot, double res)
template<class PointPlotter >
void interpolate_forward_difference (double x1, double y1, double x2, double y2, double k1, double k2, PointPlotter plot, double res)
template<class PointIter >
double x (PointIter p)
template<class PointIter >
double y (PointIter p)
template<class PointIter , class PointPlotter >
void interpolate (PointIter p0, PointIter pn, PointPlotter plot, double res)
bool do_pre_writeback (reg8 waveform_prev, reg8 waveform, bool is6581)
Variables
static const double MOSFET_LEAKAGE_6581 = 0.0075
static const double MOSFET_LEAKAGE_8580 = 0.0035
static double_point opamp_voltage_6581 []
static double_point opamp_voltage_8580 []
static model_filter_init_t model_filter_init [2]
static double_point opamp_voltage_6581 []
static double_point opamp_voltage_8580 []
static double resGain [16]
static model_filter_init_t model_filter_init [2]
static const double Vref = 4.75
const cycle_count SHIFT_REGISTER_RESET_START_6581 = 35000
const cycle_count SHIFT_REGISTER_RESET_BIT_6581 = 1000
const cycle_count SHIFT_REGISTER_RESET_START_8580 = 2519864
const cycle_count SHIFT_REGISTER_RESET_BIT_8580 = 315000
const cycle_count FLOATING_OUTPUT_TTL_START_6581 = 182000
const cycle_count FLOATING_OUTPUT_TTL_BIT_6581 = 1500
const cycle_count FLOATING_OUTPUT_TTL_START_8580 = 4400000
const cycle_count FLOATING_OUTPUT_TTL_BIT_8580 = 50000
Function Documentation
amplify()
short reSID::amplify (int input, int scaleFactor) inline
Referenced by reSID::SID::clock_fast(), reSID::SID::clock_interpolate(), reSID::SID::clock_resample(), and reSID::SID::clock_resample_fastmem().
build_dac_table()
void reSID::build_dac_table (unsigned short * dac, int bits, double _2R_div_R, bool term)
Referenced by reSID::EnvelopeGenerator::EnvelopeGenerator(), reSID::Filter::Filter(), and reSID::WaveformGenerator::WaveformGenerator().
clip()
short reSID::clip (int input) inline
Referenced by amplify(), reSID::SID::clock_interpolate(), reSID::SID::clock_resample(), and reSID::SID::clock_resample_fastmem().
cubic_coefficients()
void reSID::cubic_coefficients (double x1, double y1, double x2, double y2, double k1, double k2, double & a, double & b, double & c, double & d) inline
Referenced by interpolate_brute_force(), and interpolate_forward_difference().
do_pre_writeback()
bool reSID::do_pre_writeback (reg8 waveform_prev, reg8 waveform, bool is6581)
Referenced by reSID::WaveformGenerator::writeCONTROL_REG().
interpolate()
template<class PointIter , class PointPlotter > void reSID::interpolate (PointIter p0, PointIter pn, PointPlotter plot, double res) inline
Referenced by reSID::Filter::Filter().
interpolate_brute_force()
template<class PointPlotter > void reSID::interpolate_brute_force (double x1, double y1, double x2, double y2, double k1, double k2, PointPlotter plot, double res) inline
interpolate_forward_difference()
template<class PointPlotter > void reSID::interpolate_forward_difference (double x1, double y1, double x2, double y2, double k1, double k2, PointPlotter plot, double res) inline
log1p() [1/2]
static double reSID::log1p (double x) static
Referenced by reSID::Filter::Filter(), ram_init_with_pattern(), and random_method_geom_next().
log1p() [2/2]
static double reSID::log1p (double x) static
x()
template<class PointIter > double reSID::x (PointIter p) inline
Referenced by reSID::Filter::Filter(), build_dac_table(), reSID::SID::I0(), interpolate(), interpolate_brute_force(), interpolate_forward_difference(), log1p(), and reSID::PointPlotter< F >::operator()().
y()
template<class PointIter > double reSID::y (PointIter p) inline
Referenced by add_line_to_area(), calculateScreenPosition(), clear_buffer(), draw_char(), draw_drive_led_cb(), draw_joyport_cb(), draw_point2(), draw_point3(), draw_tape_icon_cb(), drivecpu65c02_snapshot_read_module(), drivecpu_snapshot_read_module(), godotdrv_write(), interpolate(), interpolate_brute_force(), interpolate_forward_difference(), maincpu_set_y(), maincpu_snapshot_read_module(), mon_memory_display_data(), mouse_host_moved(), reSID::PointPlotter< F >::operator()(), plot(), print_bitmask(), print_cbm_char(), refresh_canvas(), render_32_1x1_04(), render_32_1x2_interlaced(), render_32_1x2_non_interlaced(), render_32_2x2_interlaced(), render_32_2x2_non_interlaced(), render_32_2x4_interlaced(), render_32_2x4_non_interlaced(), render_32_scale2x(), render_generic_1x1_ntsc(), render_generic_1x1_pal(), render_generic_1x1_rgbi(), render_generic_1x2_rgbi(), render_generic_2x2_ntsc(), render_generic_2x2_pal(), render_generic_2x2_pal_u(), render_generic_2x2_rgbi(), render_generic_2x4_rgbi(), set_connect1(), store_line_and_scanline_4(), ui_datasette_update_sensitive(), vdc_lightpen_timing(), vicii_lightpen_timing(), video_calc_ycbcrtable(), video_fill_rgb_image(), video_sound_update(), warp(), write_line(), write_lines(), yuv_to_rgb(), zmbvdrv_fill_rgb_image(), and zmbvdrv_record().
Variable Documentation
FLOATING_OUTPUT_TTL_BIT_6581
const cycle_count reSID::FLOATING_OUTPUT_TTL_BIT_6581 = 1500
Referenced by reSID::WaveformGenerator::wave_bitfade().
FLOATING_OUTPUT_TTL_BIT_8580
const cycle_count reSID::FLOATING_OUTPUT_TTL_BIT_8580 = 50000
Referenced by reSID::WaveformGenerator::wave_bitfade().
FLOATING_OUTPUT_TTL_START_6581
const cycle_count reSID::FLOATING_OUTPUT_TTL_START_6581 = 182000
Referenced by reSID::WaveformGenerator::writeCONTROL_REG().
FLOATING_OUTPUT_TTL_START_8580
const cycle_count reSID::FLOATING_OUTPUT_TTL_START_8580 = 4400000
Referenced by reSID::WaveformGenerator::writeCONTROL_REG().
model_filter_init [1/2]
model_filter_init_t reSID::model_filter_init[2] static
Initial value:
= {
    {
        opamp_voltage_6581,
        sizeof(opamp_voltage_6581)/sizeof(*opamp_voltage_6581),
        1.5,
        5.0,
        470e-12,
        12.18,
        1.31,
        26.0e-3,
        1.0,
        20e-6,
        9.0/1,
        1.0/115,
        6.65,
        2.63,
        2.20,
        false
    },
    {
        opamp_voltage_8580,
        sizeof(opamp_voltage_8580)/sizeof(*opamp_voltage_8580),
        1.0,
        1.30,
        22e-9,
        9.09,
        0.80,
        26.0e-3,
        1.0,
        10e-6,
        0,
        0,
        0,
        0,
        2.00,
        true
    }
}
Referenced by reSID::Filter::Filter().
model_filter_init [2/2]
model_filter_init_t reSID::model_filter_init[2] static
Initial value:
= {
  {
    opamp_voltage_6581,
    sizeof(opamp_voltage_6581)/sizeof(*opamp_voltage_6581),
    1.5,
    5.075,
    470e-12,
    12.18,
    1.31,
    26.0e-3,
    1.0,
    20e-6,
    9.0/1.0,
    1.0/115,
    6.65,
    2.63,
    2.20,
    false
  },
  {
    opamp_voltage_8580,
    sizeof(opamp_voltage_8580)/sizeof(*opamp_voltage_8580),
    0.24,
    4.84,
    22e-9,
    9.09,
    0.80,
    26.0e-3,
    1.0,
    100e-6,
    0,
    0,
    0,
    0,
    2.00,
    true
  }
}
MOSFET_LEAKAGE_6581
const double reSID::MOSFET_LEAKAGE_6581 = 0.0075 static
Referenced by build_dac_table().
MOSFET_LEAKAGE_8580
const double reSID::MOSFET_LEAKAGE_8580 = 0.0035 static
Referenced by build_dac_table().
opamp_voltage_6581 [1/2]
double_point reSID::opamp_voltage_6581[] static
Initial value:
= {
    {  0.81, 10.31 },
    {  0.81, 10.31 },
    {  2.40, 10.31 },
    {  2.60, 10.30 },
    {  2.70, 10.29 },
    {  2.80, 10.26 },
    {  2.90, 10.17 },
    {  3.00, 10.04 },
    {  3.10,  9.83 },
    {  3.20,  9.58 },
    {  3.30,  9.32 },
    {  3.50,  8.69 },
    {  3.70,  8.00 },
    {  4.00,  6.89 },
    {  4.40,  5.21 },
    {  4.54,  4.54 },
    {  4.60,  4.19 },
    {  4.80,  3.00 },
    {  4.90,  2.30 },
    {  4.95,  2.03 },
    {  5.00,  1.88 },
    {  5.05,  1.77 },
    {  5.10,  1.69 },
    {  5.20,  1.58 },
    {  5.40,  1.44 },
    {  5.60,  1.33 },
    {  5.80,  1.26 },
    {  6.00,  1.21 },
    {  6.40,  1.12 },
    {  7.00,  1.02 },
    {  7.50,  0.97 },
    {  8.50,  0.89 },
    { 10.00,  0.81 },
    { 10.31,  0.81 },
    { 10.31,  0.81 }
}
opamp_voltage_6581 [2/2]
double_point reSID::opamp_voltage_6581[] static
Initial value:
= {
  {  0.81, 10.31 },
  {  0.81, 10.31 },
  {  2.40, 10.31 },
  {  2.60, 10.30 },
  {  2.70, 10.29 },
  {  2.80, 10.26 },
  {  2.90, 10.17 },
  {  3.00, 10.04 },
  {  3.10,  9.83 },
  {  3.20,  9.58 },
  {  3.30,  9.32 },
  {  3.50,  8.69 },
  {  3.70,  8.00 },
  {  4.00,  6.89 },
  {  4.40,  5.21 },
  {  4.54,  4.54 },
  {  4.60,  4.19 },
  {  4.80,  3.00 },
  {  4.90,  2.30 },
  {  4.95,  2.03 },
  {  5.00,  1.88 },
  {  5.05,  1.77 },
  {  5.10,  1.69 },
  {  5.20,  1.58 },
  {  5.40,  1.44 },
  {  5.60,  1.33 },
  {  5.80,  1.26 },
  {  6.00,  1.21 },
  {  6.40,  1.12 },
  {  7.00,  1.02 },
  {  7.50,  0.97 },
  {  8.50,  0.89 },
  { 10.00,  0.81 },
  { 10.31,  0.81 },
  { 10.31,  0.81 }
}
opamp_voltage_8580 [1/2]
double_point reSID::opamp_voltage_8580[] static
Initial value:
= {
    {  1.30,  8.91 },
    {  1.30,  8.91 },
    {  4.76,  8.91 },
    {  4.77,  8.90 },
    {  4.78,  8.88 },
    {  4.785, 8.86 },
    {  4.79,  8.80 },
    {  4.795, 8.60 },
    {  4.80,  8.25 },
    {  4.805, 7.50 },
    {  4.81,  6.10 },
    {  4.815, 4.05 },
    {  4.82,  2.27 },
    {  4.825, 1.65 },
    {  4.83,  1.55 },
    {  4.84,  1.47 },
    {  4.85,  1.43 },
    {  4.87,  1.37 },
    {  4.90,  1.34 },
    {  5.00,  1.30 },
    {  5.10,  1.30 },
    {  8.91,  1.30 },
    {  8.91,  1.30 }
}
opamp_voltage_8580 [2/2]
double_point reSID::opamp_voltage_8580[] static
Initial value:
= {
  {  1.30,  8.91 },
  {  1.30,  8.91 },
  {  4.76,  8.91 },
  {  4.77,  8.90 },
  {  4.78,  8.88 },
  {  4.785, 8.86 },
  {  4.79,  8.80 },
  {  4.795, 8.60 },
  {  4.80,  8.25 },
  {  4.805, 7.50 },
  {  4.81,  6.10 },
  {  4.815, 4.05 },
  {  4.82,  2.27 },
  {  4.825, 1.65 },
  {  4.83,  1.55 },
  {  4.84,  1.47 },
  {  4.85,  1.43 },
  {  4.87,  1.37 },
  {  4.90,  1.34 },
  {  5.00,  1.30 },
  {  5.10,  1.30 },
  {  8.91,  1.30 },
  {  8.91,  1.30 }
}
resGain
double reSID::resGain[16] static
Initial value:
=
{
  ((1.4/1.0)),
  ((((1.4*15.3)/(1.4+15.3))/1.0)),
  ((((1.4*7.3)/(1.4+7.3))/1.0)),
  ((((1.4*4.7)/(1.4+4.7))/1.0)),
  ((1.4/1.4)),
  ((((1.4*15.3)/(1.4+15.3))/1.4)),
  ((((1.4*7.3)/(1.4+7.3))/1.4)),
  ((((1.4*4.7)/(1.4+4.7))/1.4)),
  ((1.4/2.0)),
  ((((1.4*15.3)/(1.4+15.3))/2.0)),
  ((((1.4*7.3)/(1.4+7.3))/2.0)),
  ((((1.4*4.7)/(1.4+4.7))/2.0)),
  ((1.4/2.8)),
  ((((1.4*15.3)/(1.4+15.3))/2.8)),
  ((((1.4*7.3)/(1.4+7.3))/2.8)),
  ((((1.4*4.7)/(1.4+4.7))/2.8)),
}
SHIFT_REGISTER_RESET_BIT_6581
const cycle_count reSID::SHIFT_REGISTER_RESET_BIT_6581 = 1000
Referenced by reSID::WaveformGenerator::shiftreg_bitfade().
SHIFT_REGISTER_RESET_BIT_8580
const cycle_count reSID::SHIFT_REGISTER_RESET_BIT_8580 = 315000
Referenced by reSID::WaveformGenerator::shiftreg_bitfade().
SHIFT_REGISTER_RESET_START_6581
const cycle_count reSID::SHIFT_REGISTER_RESET_START_6581 = 35000
Referenced by reSID::WaveformGenerator::writeCONTROL_REG().
SHIFT_REGISTER_RESET_START_8580
const cycle_count reSID::SHIFT_REGISTER_RESET_START_8580 = 2519864
Referenced by reSID::WaveformGenerator::writeCONTROL_REG().
Vref
const double reSID::Vref = 4.75 static