x128: printerdrv/printer.c File Reference
printer.c File Reference
#include "vice.h"
#include "driver-select.h"
#include "drv-ascii.h"
#include "drv-mps803.h"
#include "drv-nl10.h"
#include "drv-1520.h"
#include "drv-raw.h"
#include "interface-serial.h"
#include "interface-userport.h"
#include "log.h"
#include "machine-printer.h"
#include "output-graphics.h"
#include "output-select.h"
#include "output-text.h"
#include "printer.h"
Macros
#define DBG(x)
Functions
int printer_resources_init (void)
Generic interface.
int printer_userport_resources_init (void)
void printer_resources_shutdown (void)
int printer_cmdline_options_init (void)
int printer_userport_cmdline_options_init (void)
void printer_init (void)
void printer_reset (void)
void printer_shutdown (void)
void printer_formfeed (unsigned int prnr)
Send formfeed to printer.
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
printer_cmdline_options_init()
int printer_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
printer_formfeed()
void printer_formfeed (unsigned int prnr)
Send formfeed to printer.
Parameters
[in] prnr device index (0-2: 4-6, 3: userport)
Referenced by on_formfeed_clicked(), and printer_formfeed_action().
printer_init()
void printer_init (void)
Referenced by machine_specific_init().
printer_reset()
void printer_reset (void)
Referenced by machine_specific_reset().
printer_resources_init()
int printer_resources_init (void)
Generic interface.
Referenced by machine_resources_init().
printer_resources_shutdown()
void printer_resources_shutdown (void)
Referenced by machine_resources_shutdown().
printer_shutdown()
void printer_shutdown (void)
< serial dev 4, 5, 6 and user port
Referenced by cmdline_help(), and machine_shutdown().
printer_userport_cmdline_options_init()
int printer_userport_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
printer_userport_resources_init()
int printer_userport_resources_init (void)
Referenced by machine_resources_init().