x128: monitor_interface_s Struct Reference
monitor_interface_s Struct Reference
#include <monitor.h>
Data Fields
struct mos6510_regs_s * cpu_regs
struct R65C02_regs_s * cpu_R65C02_regs
struct WDC65816_regs_s * cpu_65816_regs
struct z80_regs_s * z80_cpu_regs
struct mos6510dtv_regs_s * dtv_cpu_regs
struct h6809_regs_s * h6809_cpu_regs
struct interrupt_cpu_status_s * int_status
CLOCK * clk
int current_bank
int current_bank_index
const char **(* mem_bank_list)(void)
const int *(* mem_bank_list_nos)(void)
int(* mem_bank_from_name)(const char *name)
int(* mem_bank_index_from_bank)(int bank)
int(* mem_bank_flags_from_bank)(int bank)
uint8_t(* mem_bank_read)(int bank, uint16_t addr, void *context)
uint8_t(* mem_bank_peek)(int bank, uint16_t addr, void *context)
uint8_t(* mem_peek_with_config)(int config, uint16_t addr, void *context)
void(* mem_bank_write)(int bank, uint16_t addr, uint8_t byte, void *context)
void(* mem_bank_poke)(int bank, uint16_t addr, uint8_t byte, void *context)
struct mem_ioreg_list_s *(* mem_ioreg_list_get)(void *context)
void(* toggle_watchpoints_func)(int value, void *context)
void(* set_bank_base)(void *context)
void(* get_line_cycle)(unsigned int *line, unsigned int *cycle, int *half_cycle)
void * context
Field Documentation
clk
CLOCK* monitor_interface_s::clk
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), mon_stopwatch_reset(), and mon_stopwatch_show().
context
void* monitor_interface_s::context
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
cpu_65816_regs
struct WDC65816_regs_s* monitor_interface_s::cpu_65816_regs
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), find_supported_monitor_cpu_types(), maincpu_monitor_interface_get(), mon_register_get_val(), mon_register_print(), and mon_register_set_val().
cpu_R65C02_regs
struct R65C02_regs_s* monitor_interface_s::cpu_R65C02_regs
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), find_supported_monitor_cpu_types(), maincpu_monitor_interface_get(), mon_register_get_val(), mon_register_print(), mon_register_print_ex(), and mon_register_set_val().
cpu_regs
struct mos6510_regs_s* monitor_interface_s::cpu_regs
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), find_supported_monitor_cpu_types(), maincpu_monitor_interface_get(), mon_register_get_val(), mon_register_print(), mon_register_print_ex(), and mon_register_set_val().
current_bank
int monitor_interface_s::current_bank
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), mon_bank(), mon_breakpoint_check_checkpoint(), mon_disassemble_instr_bank_internal(), mon_display_io_regs(), mon_display_screen(), mon_register_list_get6502(), mon_register_list_get6502dtv(), mon_register_print(), mon_set_mem_val(), monitor_init(), and monitor_open().
current_bank_index
int monitor_interface_s::current_bank_index
Referenced by maincpu_monitor_interface_get(), and mon_bank().
dtv_cpu_regs
struct mos6510dtv_regs_s* monitor_interface_s::dtv_cpu_regs
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), find_supported_monitor_cpu_types(), maincpu_monitor_interface_get(), mon_register_get_val(), mon_register_print(), and mon_register_set_val().
get_line_cycle
void(* monitor_interface_s::get_line_cycle) (unsigned int *line, unsigned int *cycle, int *half_cycle)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), mon_breakpoint_check_checkpoint(), mon_evaluate_conditional(), mon_register_get_val(), and mon_register_print().
h6809_cpu_regs
struct h6809_regs_s* monitor_interface_s::h6809_cpu_regs
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), find_supported_monitor_cpu_types(), maincpu_monitor_interface_get(), mon_register_get_val(), mon_register_print(), mon_register_print_ex(), and mon_register_set_val().
int_status
struct interrupt_cpu_status_s* monitor_interface_s::int_status
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), and maincpu_monitor_interface_get().
mem_bank_flags_from_bank
int(* monitor_interface_s::mem_bank_flags_from_bank) (int bank)
Referenced by maincpu_monitor_interface_get(), and mon_get_bank_flags_for_bank().
mem_bank_from_name
int(* monitor_interface_s::mem_bank_from_name) (const char *name)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), mon_bank(), mon_banknum_from_bank(), mon_breakpoint_check_checkpoint(), mon_display_io_regs(), mon_register_list_get6502(), mon_register_list_get6502dtv(), mon_register_print(), monitor_init(), and monitor_open().
mem_bank_index_from_bank
int(* monitor_interface_s::mem_bank_index_from_bank) (int bank)
Referenced by maincpu_monitor_interface_get(), and mon_get_bank_index_for_bank().
mem_bank_list
const char **(* monitor_interface_s::mem_bank_list) (void)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), mon_bank(), mon_get_bank_name_for_bank(), and monitor_binary_process_banks_available().
mem_bank_list_nos
const int *(* monitor_interface_s::mem_bank_list_nos) (void)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), mon_banknum_validate(), and monitor_binary_process_banks_available().
mem_bank_peek
uint8_t(* monitor_interface_s::mem_bank_peek) (int bank, uint16_t addr, void *context)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), mon_get_mem_val_ex(), mon_get_mem_val_ex_nosfx(), and mon_get_mem_val_nosfx().
mem_bank_poke
void(* monitor_interface_s::mem_bank_poke) (int bank, uint16_t addr, uint8_t byte, void *context)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), mon_set_mem_val(), and mon_set_mem_val_ex().
mem_bank_read
uint8_t(* monitor_interface_s::mem_bank_read) (int bank, uint16_t addr, void *context)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), mon_get_mem_val_ex(), mon_get_mem_val_ex_nosfx(), and mon_get_mem_val_nosfx().
mem_bank_write
void(* monitor_interface_s::mem_bank_write) (int bank, uint16_t addr, uint8_t byte, void *context)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), mon_set_mem_val(), and mon_set_mem_val_ex().
mem_ioreg_list_get
struct mem_ioreg_list_s *(* monitor_interface_s::mem_ioreg_list_get) (void *context)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), and mon_display_io_regs().
mem_peek_with_config
uint8_t(* monitor_interface_s::mem_peek_with_config) (int config, uint16_t addr, void *context)
Referenced by maincpu_monitor_interface_get(), and mon_get_mem_val_nosfx().
set_bank_base
void(* monitor_interface_s::set_bank_base) (void *context)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), and mon_register_set_val().
toggle_watchpoints_func
void(* monitor_interface_s::toggle_watchpoints_func) (int value, void *context)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), maincpu_monitor_interface_get(), and update_checkpoint_state().
z80_cpu_regs
struct z80_regs_s* monitor_interface_s::z80_cpu_regs
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), find_supported_monitor_cpu_types(), maincpu_monitor_interface_get(), mon_register_get_val(), and mon_register_set_val().
The documentation for this struct was generated from the following file:
monitor.h