vsid: drive/drive-snapshot.c File Reference
drive-snapshot.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include "archdep.h"
#include "attach.h"
#include "diskconstants.h"
#include "diskimage.h"
#include "drive-snapshot.h"
#include "drive-sound.h"
#include "drive.h"
#include "drivecpu.h"
#include "drivecpu65c02.h"
#include "drivemem.h"
#include "driverom.h"
#include "drivetypes.h"
#include "gcr.h"
#include "iecbus.h"
#include "iecdrive.h"
#include "lib.h"
#include "log.h"
#include "machine-bus.h"
#include "machine-drive.h"
#include "resources.h"
#include "rotation.h"
#include "snapshot.h"
#include "types.h"
#include "vdrive-bam.h"
#include "vdrive-snapshot.h"
#include "zfile.h"
#include "p64.h"
Macros
#define DBG(x)
#define DRIVE_SNAP_MAJOR 2
#define DRIVE_SNAP_MINOR 0
#define IMAGE_SNAP_MAJOR 1
read/write "normal" disk image snapshot module
#define IMAGE_SNAP_MINOR 0
#define GCRIMAGE_SNAP_MAJOR 3
read/write GCR disk image snapshot module
#define GCRIMAGE_SNAP_MINOR 1
#define P64IMAGE_SNAP_MAJOR 1
read/write P64 disk image snapshot module
#define P64IMAGE_SNAP_MINOR 0
Functions
static int drive_snapshot_write_image_module (snapshot_t *s, unsigned int dnr)
static int drive_snapshot_write_gcrimage_module (snapshot_t *s, unsigned int dnr)
static int drive_snapshot_write_p64image_module (snapshot_t *s, unsigned int dnr)
static int drive_snapshot_read_image_module (snapshot_t *s, unsigned int dnr)
static int drive_snapshot_read_gcrimage_module (snapshot_t *s, unsigned int dnr)
static int drive_snapshot_read_p64image_module (snapshot_t *s, unsigned int dnr)
int drive_snapshot_write_module (snapshot_t *s, int save_disks, int save_roms)
int drive_snapshot_read_module (snapshot_t *s)
Variables
static log_t drive_snapshot_log = ((log_t)-1)
Macro Definition Documentation
DBG
#define DBG (x)
DRIVE_SNAP_MAJOR
#define DRIVE_SNAP_MAJOR 2
DRIVE_SNAP_MINOR
#define DRIVE_SNAP_MINOR 0
GCRIMAGE_SNAP_MAJOR
#define GCRIMAGE_SNAP_MAJOR 3
read/write GCR disk image snapshot module
GCRIMAGE_SNAP_MINOR
#define GCRIMAGE_SNAP_MINOR 1
IMAGE_SNAP_MAJOR
#define IMAGE_SNAP_MAJOR 1
read/write "normal" disk image snapshot module
IMAGE_SNAP_MINOR
#define IMAGE_SNAP_MINOR 0
P64IMAGE_SNAP_MAJOR
#define P64IMAGE_SNAP_MAJOR 1
read/write P64 disk image snapshot module
P64IMAGE_SNAP_MINOR
#define P64IMAGE_SNAP_MINOR 0
Function Documentation
drive_snapshot_read_gcrimage_module()
static int drive_snapshot_read_gcrimage_module (snapshot_t * s, unsigned int dnr) static
Todo:
verify if it's really like this
Referenced by drive_snapshot_read_module().
drive_snapshot_read_image_module()
static int drive_snapshot_read_image_module (snapshot_t * s, unsigned int dnr) static
Todo:
drive 1?
< ASCII for HD
< D81 image, 80 tracks
< D80 image, 77 tracks
< D82 image, 77 tracks
< write mode (binary)
Todo:
drive 1
Referenced by drive_snapshot_read_module().
drive_snapshot_read_module()
int drive_snapshot_read_module (snapshot_t * s)
Todo:
FIXME: does this really have to go into the drive snapshot?
< ASCII for HD
< DOS 2.7 single floppy drive, 1M/disk
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
< write data
< write data
Todo:
FIXME: what about the second drive of a unit?
< ASCII for HD
Todo:
FIXME: what about the second drive of a unit?
Todo:
FIXME: shouldnt we save the image also for vdrive?
Todo:
FIXME: is this correct? does the submodule save 2 images or do we have to do it here?
Todo:
FIXME: what about the second drive of a unit?
Todo:
FIXME: what about the current track in a virtual drive?
Todo:
FIXME: what about the second drive of a unit?
Referenced by c64_snapshot_read().
drive_snapshot_read_p64image_module()
static int drive_snapshot_read_p64image_module (snapshot_t * s, unsigned int dnr) static
Referenced by drive_snapshot_read_module().
drive_snapshot_write_gcrimage_module()
static int drive_snapshot_write_gcrimage_module (snapshot_t * s, unsigned int dnr) static
< maximum number of tracks on a 1571 floppy
Referenced by drive_snapshot_write_module().
drive_snapshot_write_image_module()
static int drive_snapshot_write_image_module (snapshot_t * s, unsigned int dnr) static
Todo:
drive 1?
< ASCII for HD
< ASCII for HD
Referenced by drive_snapshot_write_module().
drive_snapshot_write_module()
int drive_snapshot_write_module (snapshot_t * s, int save_disks, int save_roms)
Todo:
FIXME: should this not be per drive rather than unit?
Todo:
FIXME: does this really have to go into the drive snapshot?
Todo:
FIXME: what about the second drive of a unit?
< ASCII for HD
Todo:
FIXME: what about the second drive of a unit?
Todo:
FIXME: shouldnt we save the image also for vdrive?
Todo:
FIXME: is this correct? does the submodule save 2 images or do we have to do it here?
Referenced by c64_snapshot_write().
drive_snapshot_write_p64image_module()
static int drive_snapshot_write_p64image_module (snapshot_t * s, unsigned int dnr) static
Referenced by drive_snapshot_write_module().
Variable Documentation
drive_snapshot_log
log_t drive_snapshot_log = ((log_t)-1) static
Referenced by drive_snapshot_read_image_module().