vsid: arch/gtk3/widgets/base/basedialogs.c File Reference
basedialogs.c File Reference
Gtk3 basic dialogs (Info, Yes/No, etc)
#include "vice.h"
#include <gtk/gtk.h>
#include <string.h>
#include "debug_gtk3.h"
#include "lib.h"
#include "uimachinewindow.h"
#include "ui.h"
#include "basedialogs.h"
Functions
static gboolean entry_get_int (GtkWidget *entry, int *value)
Try to convert the text in entry into an integer value.
static void on_response_info (GtkWidget *dialog, gint response_id, gpointer data)
Handler for the 'response' event of the Info dialog.
static void on_response_confirm (GtkDialog *dialog, gint response_id, gpointer callback)
Handler for the 'response' event of the Confirm dialog.
static void on_response_integer (GtkDialog *dialog, gint response_id, gpointer data)
Handler for the 'response' event of the Error dialog.
static void on_response_error (GtkWidget *dialog, gint response_id, gpointer data)
Handler for the 'response' event of the Integer dialog.
static void on_dialog_destroy (GtkWidget *dialog, gpointer data)
Handler for the 'destroy' event of a dialog.
static GtkWidget * create_dialog (GtkWindow *parent, GtkMessageType type, GtkButtonsType buttons, const char *title, const char *text)
Create a GtkMessageDialog.
GtkWidget * vice_gtk3_message_info (GtkWindow *parent, const char *title, const char *fmt,...)
Create 'info' dialog.
GtkWidget * vice_gtk3_message_confirm (GtkWindow *parent, void(*callback)(GtkDialog *, gboolean), const char *title, const char *fmt,...)
Create 'confirm' dialog.
GtkWidget * vice_gtk3_message_error (GtkWindow *parent, const char *title, const char *fmt,...)
Create 'error' dialog.
static gboolean on_integer_key_press_event (GtkEntry *entry, GdkEvent *event, gpointer data)
Handler for the key-press event of the integer input box.
GtkWidget * vice_gtk3_integer_input_box (void(*callback)(GtkDialog *, int, gboolean), const char *title, const char *message, int old_value, int min, int max)
Create a dialog to enter an integer value.
Variables
static void(* integer_cb)(GtkDialog *, int, gboolean)
Callback function for the integer input dialog.
Detailed Description
Gtk3 basic dialogs (Info, Yes/No, etc)
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_dialog()
static GtkWidget * create_dialog (GtkWindow * parent, GtkMessageType type, GtkButtonsType buttons, const char * title, const char * text) static
Create a GtkMessageDialog.
Parameters
[in] parent parent window (can be NULL)
[in] type message type
[in] buttons buttons to use
[in] title dialog title
[in] text dialog text, optional marked-up with Pango
Returns
GtkMessageDialog
Referenced by vice_gtk3_message_confirm(), vice_gtk3_message_error(), and vice_gtk3_message_info().
entry_get_int()
static gboolean entry_get_int (GtkWidget * entry, int * value) static
Try to convert the text in entry into an integer value.
Parameters
[in] entry GtkTextEntry
[out] value object to store integer result
Returns
TRUE when conversion succeeded, FALSE otherwise
Note
When FALSE is returned, the value pointed at by value is unchanged
Referenced by on_response_integer().
on_dialog_destroy()
static void on_dialog_destroy (GtkWidget * dialog, gpointer data) static
Handler for the 'destroy' event of a dialog.
Destroys the temporary parent widget data
Parameters
[in] dialog unused
[in] data temporary parent widget
Referenced by create_dialog().
on_integer_key_press_event()
static gboolean on_integer_key_press_event (GtkEntry * entry, GdkEvent * event, gpointer data) static
Handler for the key-press event of the integer input box.
Signals ACCEPT to the dialog.
Parameters
[in] entry entry box
[in] event event object
[in] data dialog reference
Returns
TRUE if Enter was pushed, FALSE otherwise (makes the pushed key propagate to the entry
Referenced by vice_gtk3_integer_input_box().
on_response_confirm()
static void on_response_confirm (GtkDialog * dialog, gint response_id, gpointer callback) static
Handler for the 'response' event of the Confirm dialog.
Parameters
[in,out] dialog Info dialog
[in] response_id response ID (ignored)
[in] callback user-defined callback
Referenced by vice_gtk3_message_confirm().
on_response_error()
static void on_response_error (GtkWidget * dialog, gint response_id, gpointer data) static
Handler for the 'response' event of the Integer dialog.
Parameters
[in,out] dialog integer dialog
[in] response_id response ID
[in] data extra event data (ignored)
Referenced by vice_gtk3_message_error().
on_response_info()
static void on_response_info (GtkWidget * dialog, gint response_id, gpointer data) static
Handler for the 'response' event of the Info dialog.
Parameters
[in,out] dialog Info dialog
[in] response_id response ID (ignored)
[in] data extra event data (ignored)
Referenced by vice_gtk3_message_info().
on_response_integer()
static void on_response_integer (GtkDialog * dialog, gint response_id, gpointer data) static
Handler for the 'response' event of the Error dialog.
Parameters
[in,out] dialog error dialog
[in] response_id response ID (ignored)
[in] data extra event data (ignored)
Referenced by vice_gtk3_integer_input_box().
vice_gtk3_integer_input_box()
GtkWidget * vice_gtk3_integer_input_box (void(*)(GtkDialog *, int, gboolean) callback, const char * title, const char * message, int old_value, int min, int max)
Create a dialog to enter an integer value.
Parameters
[in] callback callback function to accept result
[in] title dialog title
[in] message dialog body text
[in] old_value current value of whatever needs to be changed
[in] min minimal valid value
[in] max maximum valid value
Returns
dialog
!
Todo:
check input while entering (marking any invalid value red or so)
Referenced by speed_cpu_custom_action(), and speed_fps_custom_action().
vice_gtk3_message_confirm()
GtkWidget * vice_gtk3_message_confirm (GtkWindow * parent, void(*)(GtkDialog *, gboolean) callback, const char * title, const char * fmt, ...)
Create 'confirm' dialog.
Parameters
[in] parent parent window (can be NULL)
[in] callback callback function to accept the dialog's result
[in] title dialog title
[in] fmt message format string and arguments
Returns
dialog
Referenced by cart_detach_action(), quit_action(), settings_default_action(), show_clear_all_confirm_dialog(), and vsid_playlist_clear().
vice_gtk3_message_error()
GtkWidget * vice_gtk3_message_error (GtkWindow * parent, const char * title, const char * fmt, ...)
Create 'error' dialog.
Create modal error dialog with either parent as parentm or if parent is NULL the active emu window as parent or if that one isn't created yet, a temporary empty (non-visible) parent window.
Parameters
[in] parent parent window/dialog
[in] title dialog title
[in] fmt message format string and arguments
Returns
dialog
Referenced by create_disk_image(), create_tape_image(), do_attach(), do_autostart(), eeprom_filename_callback(), help_manual_action(), on_dww_toggled(), on_enable_toggled(), on_flush_clicked(), on_load_romset_callback(), on_response(), on_romset_save_callback(), on_save_clicked(), on_save_response(), on_save_video_filename(), on_settings_save_to_filename(), playlist_save_dialog_callback(), save_as_callback(), save_filename_callback(), save_screenshot_error_impl(), settings_load_action(), settings_load_filename_callback(), settings_save_action(), ui_error_impl(), ui_vsid_window_load_psid(), update_resource(), and vsid_playlist_append_file().
vice_gtk3_message_info()
GtkWidget * vice_gtk3_message_info (GtkWindow * parent, const char * title, const char * fmt, ...)
Create 'info' dialog.
Parameters
[in] parent parent window (can be NULL)
[in] title dialog title
[in] fmt message format string and arguments
Returns
dialog
Referenced by on_save_clicked(), save_as_callback(), save_filename_callback(), and ui_message_impl().
Variable Documentation
integer_cb
void(* integer_cb) (GtkDialog *, int, gboolean) (GtkDialog * , int , gboolean) static
Callback function for the integer input dialog.
Referenced by on_response_integer(), and vice_gtk3_integer_input_box().