x128: c128/c128video.c File Reference
c128video.c File Reference
#include "vice.h"
#include <stdio.h>
#include "machine-video.h"
#include "vdc.h"
#include "vicii.h"
#include "video.h"
Functions
int machine_video_resources_init (void)
struct video_canvas_s * machine_video_canvas_get (unsigned int window)
Function Documentation
machine_video_canvas_get()
struct video_canvas_s * machine_video_canvas_get (unsigned int window)
Referenced by mon_screenshot_save(), monitor_binary_process_display_get(), monitor_binary_process_palette_get(), and screenshot_at_exit().
machine_video_resources_init()
int machine_video_resources_init (void)
Referenced by init_resources().