vsid: arch/gtk3/widgets/settings_gmod2c128.c File Reference
settings_gmod2c128.c File Reference
Settings widget to control GMod2-C128 resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "cartridge.h"
#include "machine.h"
#include "resources.h"
#include "ui.h"
#include "settings_gmod2c128.h"
Functions
static void save_filename_callback (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the open-file dialog.
static void on_save_clicked (GtkWidget *widget, gpointer user_data)
Handler for the "clicked" event of the Save Image button.
static void on_flush_clicked (GtkWidget *widget, gpointer user_data)
Handler for the "clicked" event of the Flush Image button.
static void eeprom_filename_callback (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the EEPROM file selection dialog.
static void on_eeprom_browse_clicked (GtkWidget *widget, gpointer user_data)
Handler for the "clicked" event of the EEPROM browse button.
static GtkWidget * create_cart_image_widget (void)
Create widget to handle Cartridge image resources and save/flush.
static GtkWidget * create_eeprom_image_widget (void)
Create widget to control GMod2 EEPROM.
GtkWidget * settings_gmod2c128_widget_create (GtkWidget *parent)
Create widget to control GMOD2-C128 resources.
Variables
static GtkWidget * eeprom_entry
Text entry used for the EEPROM filename.
Detailed Description
Settings widget to control GMod2-C128 resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_cart_image_widget()
static GtkWidget * create_cart_image_widget (void) static
Create widget to handle Cartridge image resources and save/flush.
Returns
GtkGrid
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by settings_gmod2c128_widget_create().
create_eeprom_image_widget()
static GtkWidget * create_eeprom_image_widget (void) static
Create widget to control GMod2 EEPROM.
Returns
GtkGrid
Referenced by settings_gmod2c128_widget_create().
eeprom_filename_callback()
static void eeprom_filename_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the EEPROM file selection dialog.
Parameters
[in,out] dialog file chooser dialog
[in,out] filename name of the EEPROM file
[in] data extra data (unused)
Referenced by on_eeprom_browse_clicked().
on_eeprom_browse_clicked()
static void on_eeprom_browse_clicked (GtkWidget * widget, gpointer user_data) static
Handler for the "clicked" event of the EEPROM browse button.
Parameters
[in] widget button
[in] user_data text entry
Referenced by create_eeprom_image_widget().
on_flush_clicked()
static void on_flush_clicked (GtkWidget * widget, gpointer user_data) static
Handler for the "clicked" event of the Flush Image button.
Parameters
[in] widget button
[in] user_data unused
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by create_cart_image_widget().
on_save_clicked()
static void on_save_clicked (GtkWidget * widget, gpointer user_data) static
Handler for the "clicked" event of the Save Image button.
Parameters
[in] widget button
[in] user_data unused
Todo:
retrieve filename of cart image
Referenced by create_cart_image_widget().
save_filename_callback()
static void save_filename_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the open-file dialog.
Parameters
[in,out] dialog open-file dialog
[in,out] filename filename or NULL on cancel
[in] data extra data (unused)
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by on_save_clicked().
settings_gmod2c128_widget_create()
GtkWidget * settings_gmod2c128_widget_create (GtkWidget * parent)
Create widget to control GMOD2-C128 resources.
Parameters
[in] parent parent widget, used for dialogs
Returns
GtkGrid
Variable Documentation
eeprom_entry
GtkWidget* eeprom_entry static
Text entry used for the EEPROM filename.
Referenced by create_eeprom_image_widget(), and eeprom_filename_callback().