vsid: arch/gtk3/widgets/base/resourcebrowser.h File Reference
resourcebrowser.h File Reference
Text entry with label and browse button connected to a resource - header.
#include <gtk/gtk.h>
Functions
GtkWidget * vice_gtk3_resource_browser_new (const char *resource, const char *const *patterns, const char *pattern_name, const char *title, const char *label, void(*callback)(GtkWidget *, gpointer))
Create file selection widget with browse button.
GtkWidget * vice_gtk3_resource_browser_save_new (const char *resource, const char *title, const char *label, const char *suggested, void(*callback)(GtkWidget *, gpointer))
Resource browser widget to select a file to save.
gboolean vice_gtk3_resource_browser_set (GtkWidget *widget, const char *new)
Set widget value to new.
gboolean vice_gtk3_resource_browser_get (GtkWidget *widget, const char **dest)
Get the current value of widget.
gboolean vice_gtk3_resource_browser_reset (GtkWidget *widget)
Restore resource in widget to its original value.
gboolean vice_gtk3_resource_browser_sync (GtkWidget *widget)
Synchronize widget with current resource value.
gboolean vice_gtk3_resource_browser_factory (GtkWidget *widget)
Reset widget to the resource's factory value.
void vice_gtk3_resource_browser_set_directory (GtkWidget *widget, const char *directory)
Set the directory to use when the resource only contains a filename.
Detailed Description
Text entry with label and browse button connected to a resource - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
vice_gtk3_resource_browser_factory()
gboolean vice_gtk3_resource_browser_factory (GtkWidget * widget)
Reset widget to the resource's factory value.
Parameters
[in,out] widget resource browser widget
Returns
bool
vice_gtk3_resource_browser_get()
gboolean vice_gtk3_resource_browser_get (GtkWidget * widget, const char ** dest)
Get the current value of widget.
Get the current resource value of widget and store it in dest. If getting the resource value fails for some reason, FALSE is returned and dest is set to NULL.
Parameters
[in] widget resource browser widget
[out] dest destination of value
Returns
TRUE when the resource value was retrieved
vice_gtk3_resource_browser_new()
GtkWidget * vice_gtk3_resource_browser_new (const char * resource, const char *const * patterns, const char * pattern_name, const char * title, const char * label, void(*)(GtkWidget *, gpointer) callback)
Create file selection widget with browse button.
Parameters
[in] resource resource name
[in] patterns file match patterns (optional)
[in] pattern_name name to use for patterns in the file dialog (optional)
[in] browser_title title to display in the file dialog (optional, defaults to "Select file")
[in] label label (optional)
[in] callback user callback (optional, not implemented yet)
Note
both patterns and pattern_name need to be defined (ie not NULL for the patterns to work.
Returns
GtkGrid
Referenced by create_memhack_widget(), create_rom_file_widget(), and create_rs232_devices_widget().
vice_gtk3_resource_browser_reset()
gboolean vice_gtk3_resource_browser_reset (GtkWidget * widget)
Restore resource in widget to its original value.
Parameters
[in,out] widget resource browser widget
Returns
bool
vice_gtk3_resource_browser_save_new()
GtkWidget * vice_gtk3_resource_browser_save_new (const char * resource, const char * title, const char * label, const char * suggested, void(*)(GtkWidget *, gpointer) callback)
Resource browser widget to select a file to save.
Parameters
[in] resource resource name
[in] title dialog title
[in] label optional label before the text entry
[in] suggested suggested filename (unimplemented)
[in] callback callback
Returns
GtkGrid
Referenced by settings_monitor_widget_create().
vice_gtk3_resource_browser_set()
gboolean vice_gtk3_resource_browser_set (GtkWidget * widget, const char * new)
Set widget value to new.
Parameters
[in,out] widget resource browser widget
[in] new new value for widget
Returns
bool
Referenced by vice_gtk3_resource_browser_factory().
vice_gtk3_resource_browser_set_directory()
void vice_gtk3_resource_browser_set_directory (GtkWidget * widget, const char * directory)
Set the directory to use when the resource only contains a filename.
Set directory to append to a filename with directory component, or to use as the default directory for the 'save' variant of the resource browser.
Parameters
[in,out] widget resource browser widget
[in] path directory to use
vice_gtk3_resource_browser_sync()
gboolean vice_gtk3_resource_browser_sync (GtkWidget * widget)
Synchronize widget with current resource value.
Only needed to call if the resource's value is changed from code other than this widget's code.
Parameters
[in,out] widget resource browser widget
Returns
TRUE if the resource value was retrieved