vsid: printerdrv/drv-ascii.c File Reference
drv-ascii.c File Reference
#include "vice.h"
#include <stdbool.h>
#include "archdep.h"
#include "charset.h"
#include "driver-select.h"
#include "drv-ascii.h"
#include "log.h"
#include "userport.h"
#include "output-select.h"
#include "output.h"
#include "palette.h"
#include "printer.h"
#include "types.h"
Data Structures
struct ascii_s
Macros
#define CHARSPERLINE 74
#define DBG(x)
Typedefs
typedef struct ascii_s ascii_t
Functions
static int print_lineend (ascii_t *ascii, unsigned int prnr)
static int print_char (ascii_t *ascii, unsigned int prnr, uint8_t c)
static int drv_ascii_open (unsigned int prnr, unsigned int secondary)
static void drv_ascii_close (unsigned int prnr, unsigned int secondary)
static int drv_ascii_putc (unsigned int prnr, unsigned int secondary, uint8_t b)
static int drv_ascii_getc (unsigned int prnr, unsigned int secondary, uint8_t *b)
static int drv_ascii_flush (unsigned int prnr, unsigned int secondary)
static int drv_ascii_formfeed (unsigned int prnr)
static int drv_ascii_select (unsigned int prnr)
int drv_ascii_init_resources (void)
int drv_ascii_init (void)
Variables
static ascii_t drv_ascii [4]
static log_t drv_ascii_log = ((log_t)-1)
Macro Definition Documentation
CHARSPERLINE
#define CHARSPERLINE 74
DBG
#define DBG (x)
Typedef Documentation
ascii_t
typedef struct ascii_s ascii_t
Function Documentation
drv_ascii_close()
static void drv_ascii_close (unsigned int prnr, unsigned int secondary) static
Referenced by drv_ascii_init_resources().
drv_ascii_flush()
static int drv_ascii_flush (unsigned int prnr, unsigned int secondary) static
Referenced by drv_ascii_init_resources().
drv_ascii_formfeed()
static int drv_ascii_formfeed (unsigned int prnr) static
Referenced by drv_ascii_init_resources().
drv_ascii_getc()
static int drv_ascii_getc (unsigned int prnr, unsigned int secondary, uint8_t * b) static
Referenced by drv_ascii_init_resources().
drv_ascii_init()
int drv_ascii_init (void)
Referenced by printer_init().
drv_ascii_init_resources()
int drv_ascii_init_resources (void)
Referenced by printer_resources_init().
drv_ascii_open()
static int drv_ascii_open (unsigned int prnr, unsigned int secondary) static
Referenced by drv_ascii_init_resources(), and drv_ascii_select().
drv_ascii_putc()
static int drv_ascii_putc (unsigned int prnr, unsigned int secondary, uint8_t b) static
Referenced by drv_ascii_init_resources().
drv_ascii_select()
static int drv_ascii_select (unsigned int prnr) static
Referenced by drv_ascii_init_resources().
print_char()
static int print_char (ascii_t * ascii, unsigned int prnr, uint8_t c) static
Referenced by drv_ascii_open(), and drv_ascii_putc().
print_lineend()
static int print_lineend (ascii_t * ascii, unsigned int prnr) static
Referenced by print_char().
Variable Documentation
drv_ascii
ascii_t drv_ascii[4] static
Referenced by drv_ascii_open(), and drv_ascii_putc().
drv_ascii_log
log_t drv_ascii_log = ((log_t)-1) static
Referenced by drv_ascii_flush(), drv_ascii_formfeed(), drv_ascii_init(), and drv_ascii_putc().