vsid: event.c File Reference
event.c File Reference
Event handling.
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "alarm.h"
#include "archdep.h"
#include "attach.h"
#include "autostart.h"
#include "cmdline.h"
#include "crc32.h"
#include "datasette.h"
#include "debug.h"
#include "interrupt.h"
#include "joystick.h"
#include "keyboard.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "network.h"
#include "resources.h"
#include "snapshot.h"
#include "tape.h"
#include "tapeport.h"
#include "types.h"
#include "uiapi.h"
#include "util.h"
#include "version.h"
#include "vice-event.h"
Data Structures
struct event_image_list_s
Macros
#define DBG(x)
#define EVENT_START_SNAPSHOT "start.vsf"
#define EVENT_END_SNAPSHOT "end.vsf"
#define EVENT_MILESTONE_SNAPSHOT "milestone.vsf"
#define CRC32_SIZE (sizeof(uint32_t))
Size of the CRC32 entries.
Typedefs
typedef struct event_image_list_s event_image_list_t
Functions
static char * event_snapshot_path (const char *snapshot_file)
static int event_image_append (const char *filename, char **mapped_name, int append)
searches for a filename in the image list
void event_record_attach_in_list (event_list_state_t *list, unsigned int unit, unsigned int drive, const char *filename, unsigned int read_only)
void event_record_attach_image (unsigned int unit, unsigned int drive, const char *filename, unsigned int read_only)
static void event_playback_attach_image (void *data, unsigned int size)
void event_record_in_list (event_list_state_t *list, unsigned int type, void *data, unsigned int size)
void event_record (unsigned int type, void *data, unsigned int size)
static void next_alarm_set (void)
static void next_current_list (void)
static void event_alarm_handler (CLOCK offset, void *data)
void event_playback_event_list (event_list_state_t *list)
void event_register_event_list (event_list_state_t *list)
void event_init_image_list (void)
static void create_list (void)
static void cut_list (event_list_t *cut_base)
void event_destroy_image_list (void)
void event_clear_list (event_list_state_t *list)
static void destroy_list (void)
static void warp_end_list (void)
static void event_write_version (void)
writes or replaces version string in the initial event
static void event_initial_write (void)
static void event_record_start_trap (uint16_t addr, void *data)
int event_record_start (void)
static void event_record_stop_trap (uint16_t addr, void *data)
int event_record_stop (void)
void event_reset_ack (void)
static void event_playback_start_trap (uint16_t addr, void *unused)
int event_playback_start (void)
int event_playback_stop (void)
static void event_record_set_milestone_trap (uint16_t addr, void *data)
int event_record_set_milestone (void)
static void event_record_reset_milestone_trap (uint16_t addr, void *data)
int event_record_reset_milestone (void)
int event_record_active (void)
int event_playback_active (void)
int event_snapshot_read_module (struct snapshot_s *s, int event_mode)
int event_snapshot_write_module (struct snapshot_s *s, int event_mode)
static int set_event_snapshot_dir (const char *val, void *param)
static int set_event_start_snapshot (const char *val, void *param)
static int set_event_end_snapshot (const char *val, void *param)
static int set_event_start_mode (int mode, void *param)
static int set_event_image_include (int enable, void *param)
int event_resources_init (void)
void event_shutdown (void)
static int cmdline_help (const char *param, void *extra_param)
int event_cmdline_options_init (void)
void event_init (void)
Variables
static event_list_state_t * event_list = NULL
static event_image_list_t * event_image_list_base = NULL
static int image_number
static alarm_t * event_alarm = NULL
static log_t event_log = ((log_t)-2)
static unsigned int playback_active = 0
static unsigned int record_active = 0
static unsigned int current_timestamp
static unsigned int milestone_timestamp
static unsigned int playback_time
static CLOCK next_timestamp_clk
static CLOCK milestone_timestamp_alarm
static char event_version [16]
the VICE version an event history was made with
static char * event_snapshot_dir = NULL
static char * event_start_snapshot = NULL
static char * event_end_snapshot = NULL
static char * event_snapshot_path_str = NULL
static int event_start_mode
static int event_image_include
static unsigned int playback_reset_ack = 0
static const resource_string_t resources_string []
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
Detailed Description
Event handling.
Author
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Andreas Matthies <aDOTmatthiesATgmxDOTnet>
Macro Definition Documentation
CRC32_SIZE
#define CRC32_SIZE (sizeof(uint32_t))
Size of the CRC32 entries.
CRC32 entries are stored as little endian values
DBG
#define DBG (x)
EVENT_END_SNAPSHOT
#define EVENT_END_SNAPSHOT "end.vsf"
EVENT_MILESTONE_SNAPSHOT
#define EVENT_MILESTONE_SNAPSHOT "milestone.vsf"
EVENT_START_SNAPSHOT
#define EVENT_START_SNAPSHOT "start.vsf"
Typedef Documentation
event_image_list_t
typedef struct event_image_list_s event_image_list_t
Function Documentation
cmdline_help()
static int cmdline_help (const char * param, void * extra_param) static
create_list()
static void create_list (void) static
Referenced by event_playback_start_trap(), event_record_start_trap(), and event_snapshot_read_module().
cut_list()
static void cut_list (event_list_t * cut_base) static
Referenced by event_clear_list(), and event_record_start_trap().
destroy_list()
static void destroy_list (void) static
Referenced by event_playback_start_trap(), event_record_start_trap(), event_shutdown(), and event_snapshot_read_module().
event_alarm_handler()
static void event_alarm_handler (CLOCK offset, void * data) static
Todo:
drive 1?
Referenced by event_init().
event_clear_list()
void event_clear_list (event_list_state_t * list)
Referenced by destroy_list(), network_client_connect_trap(), network_free_frame_event_list(), network_hook_connected_receive(), network_prepare_next_frame(), and network_server_connect_trap().
event_cmdline_options_init()
int event_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
event_destroy_image_list()
void event_destroy_image_list (void)
Referenced by destroy_list(), event_record_start_trap(), and network_free_frame_event_list().
event_image_append()
static int event_image_append (const char * filename, char ** mapped_name, int append) static
searches for a filename in the image list
returns 0 if found
returns 1 and appends it if not found
Referenced by event_playback_attach_image(), event_record_attach_in_list(), and warp_end_list().
event_init()
void event_init (void)
Referenced by machine_specific_init().
event_init_image_list()
void event_init_image_list (void)
Referenced by create_list(), and network_init_frame_event_list().
event_initial_write()
static void event_initial_write (void) static
Referenced by event_record_start_trap().
event_playback_active()
int event_playback_active (void)
Referenced by autostart_autodetect(), autostart_disk(), autostart_prg(), autostart_snapshot(), autostart_tape(), file_system_attach_disk(), file_system_detach_disk(), keyboard_key_clear(), keyboard_key_pressed(), keyboard_key_released(), machine_trigger_reset(), tape_image_attach(), and tape_image_detach().
event_playback_attach_image()
static void event_playback_attach_image (void * data, unsigned int size) static
< write mode (binary)
Todo:
FIXME: read_only isn't handled for tape
Referenced by event_alarm_handler(), and event_playback_event_list().
event_playback_event_list()
void event_playback_event_list (event_list_state_t * list)
Todo:
drive 1?
Referenced by network_client_connect_trap(), and network_hook_connected_receive().
event_playback_start()
int event_playback_start (void)
Referenced by cmdline_help(), and history_playback_start_action().
event_playback_start_trap()
static void event_playback_start_trap (uint16_t addr, void * unused) static
Referenced by event_playback_start().
event_playback_stop()
int event_playback_stop (void)
Referenced by event_alarm_handler(), event_record_start(), and history_playback_stop_action().
event_record()
void event_record (unsigned int type, void * data, unsigned int size)
Referenced by event_initial_write(), event_record_stop(), file_system_detach_disk_internal(), keyboard_event_record(), machine_trigger_reset(), restore_alarm_triggered(), and tape_image_detach_internal().
event_record_active()
int event_record_active (void)
Referenced by autostart_autodetect(), autostart_disk(), autostart_prg(), autostart_snapshot(), autostart_tape(), on_stop_clicked(), statusbar_recording_widget_set_recording_status(), and statusbar_recording_widget_set_time().
event_record_attach_image()
void event_record_attach_image (unsigned int unit, unsigned int drive, const char * filename, unsigned int read_only)
Referenced by file_system_attach_disk_internal(), and tape_image_attach_internal().
event_record_attach_in_list()
void event_record_attach_in_list (event_list_state_t * list, unsigned int unit, unsigned int drive, const char * filename, unsigned int read_only)
< read mode (binary)
Referenced by event_record_attach_image(), and network_attach_image().
event_record_in_list()
void event_record_in_list (event_list_state_t * list, unsigned int type, void * data, unsigned int size)
Referenced by event_record().
event_record_reset_milestone()
int event_record_reset_milestone (void)
Referenced by history_milestone_reset_action().
event_record_reset_milestone_trap()
static void event_record_reset_milestone_trap (uint16_t addr, void * data) static
Referenced by event_record_reset_milestone().
event_record_set_milestone()
int event_record_set_milestone (void)
Referenced by history_milestone_set_action().
event_record_set_milestone_trap()
static void event_record_set_milestone_trap (uint16_t addr, void * data) static
Referenced by event_record_set_milestone().
event_record_start()
int event_record_start (void)
Referenced by history_record_start_action().
event_record_start_trap()
static void event_record_start_trap (uint16_t addr, void * data) static
Referenced by event_record_start().
event_record_stop()
int event_record_stop (void)
Referenced by history_record_stop_action(), and on_stop_clicked().
event_record_stop_trap()
static void event_record_stop_trap (uint16_t addr, void * data) static
Referenced by event_record_stop().
event_register_event_list()
void event_register_event_list (event_list_state_t * list)
Referenced by create_list(), network_create_event_list(), network_init_frame_event_list(), network_prepare_next_frame(), and network_server_connect_trap().
event_reset_ack()
void event_reset_ack (void)
Referenced by machine_reset().
event_resources_init()
int event_resources_init (void)
Referenced by machine_resources_init().
event_shutdown()
void event_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
event_snapshot_path()
static char * event_snapshot_path (const char * snapshot_file) static
Referenced by event_playback_start_trap(), event_record_reset_milestone_trap(), event_record_set_milestone_trap(), event_record_start_trap(), and event_record_stop_trap().
event_snapshot_read_module()
int event_snapshot_read_module (struct snapshot_s * s, int event_mode)
Referenced by c64_snapshot_read(), and event_playback_start_trap().
event_snapshot_write_module()
int event_snapshot_write_module (struct snapshot_s * s, int event_mode)
Referenced by c64_snapshot_write().
event_write_version()
static void event_write_version (void) static
writes or replaces version string in the initial event
Referenced by event_initial_write(), and event_record_start_trap().
next_alarm_set()
static void next_alarm_set (void) static
Referenced by event_alarm_handler(), event_playback_start_trap(), and event_reset_ack().
next_current_list()
static void next_current_list (void) static
Referenced by event_alarm_handler(), event_playback_start_trap(), and event_reset_ack().
set_event_end_snapshot()
static int set_event_end_snapshot (const char * val, void * param) static
set_event_image_include()
static int set_event_image_include (int enable, void * param) static
set_event_snapshot_dir()
static int set_event_snapshot_dir (const char * val, void * param) static
< directory separator as an integer
< directory separator as a string
set_event_start_mode()
static int set_event_start_mode (int mode, void * param) static
set_event_start_snapshot()
static int set_event_start_snapshot (const char * val, void * param) static
warp_end_list()
static void warp_end_list (void) static
Referenced by event_record_reset_milestone_trap(), and event_record_start_trap().
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-playback", CALL_FUNCTION,  0 ,
      cmdline_help, NULL, NULL, NULL,
      NULL, "Playback recorded events" },
    { "-eventsnapshotdir", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "EventSnapshotDir", NULL,
      "<Name>", "Set event snapshot directory" },
    { "-eventstartsnapshot", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "EventStartSnapshot", NULL,
      "<Name>", "Set event start snapshot" },
    { "-eventendsnapshot", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "EventEndSnapshot", NULL,
      "<Name>", "Set event end snapshot" },
    { "-eventstartmode", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "EventStartMode", NULL,
      "<Mode>", "Set event start mode (0: file save, 1: file load, 2: reset, 3: playback)" },
    { "-eventimageinc", SET_RESOURCE,  0 ,
      NULL, NULL, "EventImageInclude", (resource_value_t)1,
      NULL, "Enable including disk images" },
    { "+eventimageinc", SET_RESOURCE,  0 ,
      NULL, NULL, "EventImageInclude", (resource_value_t)0,
      NULL, "Disable including disk images" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by event_cmdline_options_init().
current_timestamp
unsigned int current_timestamp static
Referenced by event_alarm_handler(), event_playback_start_trap(), event_record_reset_milestone_trap(), event_record_set_milestone_trap(), and event_record_start_trap().
event_alarm
alarm_t* event_alarm = NULL static
Referenced by event_alarm_handler(), event_init(), event_playback_stop(), event_record_reset_milestone_trap(), event_record_start_trap(), event_record_stop(), event_reset_ack(), and next_alarm_set().
event_end_snapshot
char* event_end_snapshot = NULL static
Referenced by event_playback_start_trap(), event_record_reset_milestone_trap(), event_record_set_milestone_trap(), event_record_start_trap(), event_record_stop_trap(), event_shutdown(), and set_event_end_snapshot().
event_image_include
int event_image_include static
Referenced by event_record_attach_in_list(), and set_event_image_include().
event_image_list_base
event_image_list_t* event_image_list_base = NULL static
Referenced by event_destroy_image_list(), event_image_append(), and event_init_image_list().
event_list
event_list_state_t* event_list = NULL static
Referenced by create_list(), destroy_list(), event_alarm_handler(), event_playback_start_trap(), event_record(), event_record_attach_image(), event_record_start_trap(), event_reset_ack(), event_snapshot_read_module(), event_snapshot_write_module(), event_write_version(), next_alarm_set(), next_current_list(), and warp_end_list().
event_log
log_t event_log = ((log_t)-2) static
Referenced by event_alarm_handler(), event_init(), event_playback_event_list(), event_record_attach_in_list(), event_record_in_list(), and event_record_start_trap().
event_snapshot_dir
char* event_snapshot_dir = NULL static
Referenced by event_shutdown(), event_snapshot_path(), and set_event_snapshot_dir().
event_snapshot_path_str
char* event_snapshot_path_str = NULL static
Referenced by event_shutdown(), and event_snapshot_path().
event_start_mode
int event_start_mode static
Referenced by event_initial_write(), event_record_start(), event_record_start_trap(), and set_event_start_mode().
event_start_snapshot
char* event_start_snapshot = NULL static
Referenced by event_initial_write(), event_playback_start_trap(), event_record_start_trap(), event_shutdown(), event_write_version(), and set_event_start_snapshot().
event_version
char event_version[16] static
the VICE version an event history was made with
Referenced by event_playback_start_trap().
image_number
int image_number static
Referenced by event_init_image_list().
milestone_timestamp
unsigned int milestone_timestamp static
Referenced by event_record_reset_milestone_trap(), and event_record_set_milestone_trap().
milestone_timestamp_alarm
CLOCK milestone_timestamp_alarm static
Referenced by event_record_reset_milestone_trap(), event_record_set_milestone_trap(), and event_record_start_trap().
next_timestamp_clk
CLOCK next_timestamp_clk static
Referenced by event_alarm_handler(), event_record_in_list(), event_record_reset_milestone_trap(), event_record_set_milestone_trap(), event_record_start_trap(), event_reset_ack(), and event_snapshot_read_module().
playback_active
unsigned int playback_active = 0 static
Referenced by event_playback_active(), event_playback_start(), event_playback_start_trap(), event_playback_stop(), event_record_reset_milestone(), and event_record_start().
playback_reset_ack
unsigned int playback_reset_ack = 0 static
Referenced by event_playback_start_trap(), and event_reset_ack().
playback_time
unsigned int playback_time static
Referenced by event_alarm_handler(), event_record_start_trap(), and event_snapshot_read_module().
record_active
unsigned int record_active = 0 static
Referenced by event_alarm_handler(), event_playback_start(), event_record(), event_record_active(), event_record_attach_image(), event_record_reset_milestone(), event_record_reset_milestone_trap(), event_record_set_milestone(), event_record_start(), event_record_start_trap(), event_record_stop(), event_record_stop_trap(), and event_reset_ack().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "EventStartMode",  0 , RES_EVENT_NO, NULL,
      &event_start_mode, set_event_start_mode, NULL },
    { "EventImageInclude", 1, RES_EVENT_NO, NULL,
      &event_image_include, set_event_image_include, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by event_resources_init().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "EventSnapshotDir",
       "."    "/"  , RES_EVENT_NO, NULL,
      &event_snapshot_dir, set_event_snapshot_dir, NULL },
    { "EventStartSnapshot",  "start.vsf" , RES_EVENT_NO, NULL,
      &event_start_snapshot, set_event_start_snapshot, NULL },
    { "EventEndSnapshot",  "end.vsf" , RES_EVENT_NO, NULL,
      &event_end_snapshot, set_event_end_snapshot, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by event_resources_init().