vsid: c64/c64cia2.c File Reference
c64cia2.c File Reference
#include "vice.h"
#include <stdio.h>
#include "c64fastiec.h"
#include "c64-resources.h"
#include "c64.h"
#include "c64mem.h"
#include "c64iec.h"
#include "c64cia.h"
#include "c64gluelogic.h"
#include "c64parallel.h"
#include "cia.h"
#include "drive.h"
#include "iecbus.h"
#include "interrupt.h"
#include "keyboard.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "types.h"
#include "userport.h"
#include "vicii.h"
Macros
#define MYCIA CIA2
Functions
void cia2_store (uint16_t addr, uint8_t data)
uint8_t cia2_read (uint16_t addr)
uint8_t cia2_peek (uint16_t addr)
static void cia_set_int_clk (cia_context_t *cia_context, int value, CLOCK clk)
static void cia_restore_int (cia_context_t *cia_context, int value)
void cia2_update_model (void)
static void do_reset_cia (cia_context_t *cia_context)
static void pre_store (void)
static void pre_read (void)
static void pre_peek (void)
static void store_ciapa (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static void undump_ciapa (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static void store_ciapb (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static void pulse_ciapc (cia_context_t *cia_context, CLOCK rclk)
static void undump_ciapb (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
FIXME!
static uint8_t read_ciapa (cia_context_t *cia_context)
read_* functions must return 0xff if nothing to read!!!
static uint8_t read_ciapb (cia_context_t *cia_context)
read_* functions must return 0xff if nothing to read!!!
static void read_ciaicr (cia_context_t *cia_context)
static void read_sdr (cia_context_t *cia_context)
static void store_sdr (cia_context_t *cia_context, uint8_t byte)
void cia2_set_flagx (void)
Temporary!
void cia2_set_sdrx (uint8_t received_byte)
void cia2_init (cia_context_t *cia_context)
void cia2_setup_context (machine_context_t *machinecontext)
void cia2_set_timing (cia_context_t *cia_context, int tickspersec, int powerfreq)
Variables
static int pa_ddr_change = 0
Flag for recording port A DDR changes (for c64gluelogic)
static uint8_t cia2_cra = 0
static int vbank
Current video bank (0, 1, 2 or 3).
Macro Definition Documentation
MYCIA
#define MYCIA CIA2
Function Documentation
cia2_init()
void cia2_init (cia_context_t * cia_context)
cia2_peek()
uint8_t cia2_peek (uint16_t addr)
cia2_read()
uint8_t cia2_read (uint16_t addr)
cia2_set_flagx()
void cia2_set_flagx (void)
Temporary!
cia2_set_sdrx()
void cia2_set_sdrx (uint8_t received_byte)
cia2_set_timing()
void cia2_set_timing (cia_context_t * cia_context, int tickspersec, int powerfreq)
Referenced by cia2_setup_context().
cia2_setup_context()
void cia2_setup_context (machine_context_t * machinecontext)
cia2_store()
void cia2_store (uint16_t addr, uint8_t data)
< Control register A
< Data direction register for port A
< Data direction register for port A
cia2_update_model()
void cia2_update_model (void)
cia_restore_int()
static void cia_restore_int (cia_context_t * cia_context, int value) static
Referenced by cia2_setup_context().
cia_set_int_clk()
static void cia_set_int_clk (cia_context_t * cia_context, int value, CLOCK clk) static
Referenced by cia2_setup_context().
do_reset_cia()
static void do_reset_cia (cia_context_t * cia_context) static
Referenced by cia2_setup_context().
pre_peek()
static void pre_peek (void) static
Referenced by cia2_setup_context().
pre_read()
static void pre_read (void) static
Referenced by cia2_setup_context().
pre_store()
static void pre_store (void) static
Referenced by cia2_setup_context().
pulse_ciapc()
static void pulse_ciapc (cia_context_t * cia_context, CLOCK rclk) static
Referenced by cia2_setup_context().
read_ciaicr()
static void read_ciaicr (cia_context_t * cia_context) static
< speed-dos userport cable
Referenced by cia2_setup_context().
read_ciapa()
static uint8_t read_ciapa (cia_context_t * cia_context) static
read_* functions must return 0xff if nothing to read!!!
< Port A
< Data direction register for port A
< Data direction register for port A
< Data direction register for port A
Referenced by cia2_setup_context().
read_ciapb()
static uint8_t read_ciapb (cia_context_t * cia_context) static
read_* functions must return 0xff if nothing to read!!!
< Data direction register for port B
< Port B
< Data direction register for port B
Referenced by cia2_setup_context().
read_sdr()
static void read_sdr (cia_context_t * cia_context) static
< Serial port shift register
< Serial port shift register
Referenced by cia2_setup_context().
store_ciapa()
static void store_ciapa (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
Referenced by cia2_setup_context().
store_ciapb()
static void store_ciapb (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
Referenced by cia2_setup_context().
store_sdr()
static void store_sdr (cia_context_t * cia_context, uint8_t byte) static
Referenced by cia2_setup_context().
undump_ciapa()
static void undump_ciapa (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) static
Referenced by cia2_setup_context().
undump_ciapb()
static void undump_ciapb (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) inline static
FIXME!
< speed-dos userport cable
Referenced by cia2_setup_context().
Variable Documentation
cia2_cra
uint8_t cia2_cra = 0 static
Referenced by cia2_store(), and store_sdr().
pa_ddr_change
int pa_ddr_change = 0 static
Flag for recording port A DDR changes (for c64gluelogic)
Referenced by cia2_store(), and store_ciapa().
vbank
int vbank static
Current video bank (0, 1, 2 or 3).
Referenced by c64_glue_set_vbank(), c64_glue_undump(), do_reset_cia(), perform_vbank_switch(), store_ciapa(), and undump_ciapa().