vsid: rs232drv/rs232.c File Reference
rs232.c File Reference
#include "vice.h"
#include <assert.h>
#include <errno.h>
#include <string.h>
#include "log.h"
#include "rs232.h"
#include "rs232dev.h"
#include "rs232net.h"
#include "types.h"
#include "util.h"
#include "vicesocket.h"
Macros
#define DEBUG
#define DBG(_xxx) log_debug _xxx
Enumerations
enum { RS232_IS_PHYSICAL_DEVICE = 0x4000 }
Functions
int rs232_resources_init (void)
void rs232_resources_shutdown (void)
int rs232_cmdline_options_init (void)
void rs232_init (void)
initializes all RS232 stuff
void rs232_reset (void)
reset RS232 stuff
static int rs232_is_physical_device (int device)
int rs232_open (int device)
opens a rs232 window, returns handle to give to functions below.
void rs232_close (int fd)
closes the rs232 window again
int rs232_putc (int fd, uint8_t b)
sends a byte to the RS232 line
int rs232_getc (int fd, uint8_t *b)
gets a byte to the RS232 line, returns !=0 if byte received, byte in *b.
int rs232_set_status (int fd, enum rs232handshake_out status)
set the status lines of the RS232 device
enum rs232handshake_in rs232_get_status (int fd)
get the status lines of the RS232 device
void rs232_set_bps (int fd, unsigned int bps)
set the bps rate of the physical device
Macro Definition Documentation
DBG
#define DBG (_xxx) log_debug _xxx
DEBUG
#define DEBUG
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RS232_IS_PHYSICAL_DEVICE
Function Documentation
rs232_close()
void rs232_close (int fd)
closes the rs232 window again
Closes the rs232 window again.
Referenced by rs232drv_close().
rs232_cmdline_options_init()
int rs232_cmdline_options_init (void)
Referenced by rs232drv_cmdline_options_init().
rs232_get_status()
enum rs232handshake_in rs232_get_status (int fd)
get the status lines of the RS232 device
write the output handshake lines
Referenced by rs232drv_get_status().
rs232_getc()
int rs232_getc (int fd, uint8_t * b)
gets a byte to the RS232 line, returns !=0 if byte received, byte in *b.
Gets a byte to the RS232 line, returns !=1 if byte received, byte in *b.
Referenced by rs232drv_getc().
rs232_init()
void rs232_init (void)
initializes all RS232 stuff
Initializes all RS232 stuff.
Referenced by rs232drv_init().
rs232_is_physical_device()
static int rs232_is_physical_device (int device) static
find out if the rs232 channel is for a physical device (COMx:) or for networking.
An RS232 channel is for a physical device if its name is NOT a network acceptable address
Referenced by rs232_open().
rs232_open()
int rs232_open (int device)
opens a rs232 window, returns handle to give to functions below.
Opens a rs232 window, returns handle to give to functions below.
Referenced by rs232drv_open().
rs232_putc()
int rs232_putc (int fd, uint8_t b)
sends a byte to the RS232 line
Sends a byte to the RS232 line.
Referenced by rs232drv_putc().
rs232_reset()
void rs232_reset (void)
reset RS232 stuff
Reset for RS232 interfaces.
Referenced by rs232drv_reset().
rs232_resources_init()
int rs232_resources_init (void)
Referenced by rs232drv_resources_init().
rs232_resources_shutdown()
void rs232_resources_shutdown (void)
Referenced by rs232drv_resources_shutdown().
rs232_set_bps()
void rs232_set_bps (int fd, unsigned int bps)
set the bps rate of the physical device
Referenced by rs232drv_set_bps().
rs232_set_status()
int rs232_set_status (int fd, enum rs232handshake_out status)
set the status lines of the RS232 device
write the output handshake lines
Referenced by rs232drv_set_status().