x128: fsdevice/fsdevicetypes.h File Reference
fsdevicetypes.h File Reference
#include "types.h"
#include "archdep_dir.h"
Data Structures
struct bufinfo_s
struct fsdevice_dev_s
Macros
#define FSDEVICE_BUFFER_MAX 16
#define FSDEVICE_DEVICE_MAX 4
#define FSDEVICE_TRACK_MAX 80
#define FSDEVICE_SECTOR_MAX 32
Typedefs
typedef struct bufinfo_s bufinfo_t
typedef struct fsdevice_dev_s fsdevice_dev_t
Enumerations
enum fsmode {
Write ,
Read ,
Append ,
Directory ,
Relative
}
Functions
void fsdevice_error (struct vdrive_s *vdrive, int code)
char * fsdevice_get_path (unsigned int unit)
int fsdevice_error_get_byte (struct vdrive_s *vdrive, uint8_t *data)
int fsdevice_flush_write_byte (struct vdrive_s *vdrive, uint8_t data)
Variables
fsdevice_dev_t fsdevice_dev [4]
Macro Definition Documentation
FSDEVICE_BUFFER_MAX
#define FSDEVICE_BUFFER_MAX 16
FSDEVICE_DEVICE_MAX
#define FSDEVICE_DEVICE_MAX 4
FSDEVICE_SECTOR_MAX
#define FSDEVICE_SECTOR_MAX 32
FSDEVICE_TRACK_MAX
#define FSDEVICE_TRACK_MAX 80
Typedef Documentation
bufinfo_t
typedef struct bufinfo_s bufinfo_t
fsdevice_dev_t
typedef struct fsdevice_dev_s fsdevice_dev_t
Enumeration Type Documentation
fsmode
enum fsmode
Enumerator
Write
Read
Append
Directory
Relative
Function Documentation
fsdevice_error()
void fsdevice_error (struct vdrive_s * vdrive, int code)
Referenced by fsdevice_attach(), fsdevice_close(), fsdevice_error_get_byte(), fsdevice_flush(), fsdevice_flush_write_byte(), fsdevice_open(), fsdevice_open_buffer(), fsdevice_open_directory(), fsdevice_open_file(), fsdevice_relative_switch_record(), fsdevice_write(), and relative_read().
fsdevice_error_get_byte()
int fsdevice_error_get_byte (struct vdrive_s * vdrive, uint8_t * data)
Referenced by fsdevice_read().
fsdevice_flush_write_byte()
int fsdevice_flush_write_byte (struct vdrive_s * vdrive, uint8_t data)
Todo:
FIXME: Consider the real size of the input buffer.
Referenced by fsdevice_write().
fsdevice_get_path()
char * fsdevice_get_path (unsigned int unit)
Referenced by expand_shortname(), fsdevice_flush_cd(), fsdevice_flush_mkdir(), fsdevice_flush_rename(), fsdevice_flush_rmdir(), fsdevice_flush_scratch(), fsdevice_open_directory(), fsdevice_open_file(), and limit_longname().
Variable Documentation
fsdevice_dev
fsdevice_dev_t fsdevice_dev[4] extern
Referenced by fsdevice_close(), fsdevice_error(), fsdevice_error_get_byte(), fsdevice_flush(), fsdevice_flush_ba(), fsdevice_flush_be(), fsdevice_flush_bf(), fsdevice_flush_br(), fsdevice_flush_bw(), fsdevice_flush_initialize(), fsdevice_flush_new(), fsdevice_flush_position(), fsdevice_flush_rename(), fsdevice_flush_scratch(), fsdevice_flush_u1(), fsdevice_flush_u2(), fsdevice_flush_validate(), fsdevice_flush_write_byte(), fsdevice_init(), fsdevice_listen(), fsdevice_open(), fsdevice_read(), fsdevice_shutdown(), and fsdevice_write().