vsid: palette.h File Reference
palette.h File Reference
#include "types.h"
Data Structures
struct palette_entry_s
struct palette_s
struct palette_info_t
palette info for GUIs
Typedefs
typedef struct palette_entry_s palette_entry_t
typedef struct palette_s palette_t
Functions
void palette_init (void)
void palette_shutdown (void)
palette_t * palette_create (unsigned int num_entries, const char *entry_names[])
void palette_free (palette_t *p)
int palette_load (const char *file_name, const char *subpath, palette_t *palette_return)
int palette_save (const char *file_name, const palette_t *palette)
const palette_info_t * palette_get_info_list (void)
returns pointer to palette_info_t entries.
Typedef Documentation
palette_entry_t
typedef struct palette_entry_s palette_entry_t
palette_t
typedef struct palette_s palette_t
Function Documentation
palette_create()
palette_t * palette_create (unsigned int num_entries, const char * entry_names[])
Referenced by drv_1520_init(), drv_mps803_init(), drv_nl10_init(), palette_load(), video_calc_palette(), and video_load_palette().
palette_free()
void palette_free (palette_t * p)
Referenced by drv_1520_shutdown(), drv_mps803_shutdown(), drv_nl10_shutdown(), palette_load(), video_color_palette_free(), video_color_update_palette(), and video_load_palette().
palette_get_info_list()
const palette_info_t * palette_get_info_list (void)
returns pointer to palette_info_t entries.
may return an empty list.
Todo:
FIXME: limit the list here. we may really want a dynamically allocated list here, but its not worth the trouble right now :=P
Todo:
sort list by name(s)
Referenced by create_combo_box().
palette_init()
void palette_init (void)
Referenced by init_main().
palette_load()
int palette_load (const char * file_name, const char * subpath, palette_t * palette_return)
< read mode (text)
< read mode (text)
Referenced by drv_1520_init(), drv_mps803_init(), drv_nl10_init(), and video_load_palette().
palette_save()
int palette_save (const char * file_name, const palette_t * palette)
Todo:
FIXME: output NAME and TYPE tags!
< write mode (binary)
palette_shutdown()
void palette_shutdown (void)
Referenced by machine_shutdown().