x128: drive/tcbm/tcbmrom.c File Reference
tcbmrom.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "drive.h"
#include "driverom.h"
#include "drivetypes.h"
#include "log.h"
#include "resources.h"
#include "sysfile.h"
#include "tcbmrom.h"
Functions
int tcbmrom_load_1551 (void)
void tcbmrom_setup_image (diskunit_context_t *unit)
int tcbmrom_check_loaded (unsigned int type)
void tcbmrom_init (void)
Variables
static log_t tcbmrom_log
Logging goes here.
static uint8_t drive_rom1551 [0x4000]
static unsigned int rom1551_loaded = 0
If nonzero, the ROM image has been loaded.
Function Documentation
tcbmrom_check_loaded()
int tcbmrom_check_loaded (unsigned int type)
Referenced by tcbm_drive_rom_check_loaded().
tcbmrom_init()
void tcbmrom_init (void)
Referenced by tcbm_drive_init().
tcbmrom_load_1551()
int tcbmrom_load_1551 (void)
Referenced by set_dos_rom_name_1551(), and tcbm_drive_rom_load().
tcbmrom_setup_image()
void tcbmrom_setup_image (diskunit_context_t * unit)
Referenced by tcbm_drive_rom_setup_image().
Variable Documentation
drive_rom1551
uint8_t drive_rom1551[0x4000] static
Referenced by tcbmrom_load_1551(), and tcbmrom_setup_image().
rom1551_loaded
unsigned int rom1551_loaded = 0 static
If nonzero, the ROM image has been loaded.
Referenced by tcbmrom_check_loaded(), and tcbmrom_load_1551().
tcbmrom_log
log_t tcbmrom_log static
Logging goes here.
Referenced by tcbmrom_init().