x128: lib/linenoise-ng/linenoise.h File Reference
linenoise.h File Reference
Macros
#define LINENOISE_VERSION "1.0.0"
#define LINENOISE_VERSION_MAJOR 1
#define LINENOISE_VERSION_MINOR 1
Typedefs
typedef struct linenoiseCompletions linenoiseCompletions
typedef void() linenoiseCompletionCallback(const char *, linenoiseCompletions *)
Functions
void linenoiseSetCompletionCallback (linenoiseCompletionCallback *fn)
Register a callback function to be called for tab-completion.
void linenoiseAddCompletion (linenoiseCompletions *lc, const char *str)
char * linenoise (const char *prompt)
linenoise is a readline replacement.
void linenoisePreloadBuffer (const char *preloadText)
linenoisePreloadBuffer provides text to be inserted into the command buffer
int linenoiseHistoryAdd (const char *line)
int linenoiseHistorySetMaxLen (int len)
char * linenoiseHistoryLine (int index)
int linenoiseHistorySave (const char *filename)
int linenoiseHistoryLoad (const char *filename)
void linenoiseHistoryFree (void)
void linenoiseClearScreen (void)
Clear the screen ONLY (no redisplay of anything)
void linenoiseSetMultiLine (int ml)
Set if to use or not the multi line mode.
void linenoisePrintKeyCodes (void)
int linenoiseInstallWindowChangeHandler (void)
the following are extensions to the original linenoise API
int linenoiseKeyType (void)
returns type of key pressed: 1 = CTRL-C, 2 = CTRL-D, 0 = other
Macro Definition Documentation
LINENOISE_VERSION
#define LINENOISE_VERSION "1.0.0"
LINENOISE_VERSION_MAJOR
#define LINENOISE_VERSION_MAJOR 1
LINENOISE_VERSION_MINOR
#define LINENOISE_VERSION_MINOR 1
Typedef Documentation
linenoiseCompletionCallback
typedef void() linenoiseCompletionCallback(const char *, linenoiseCompletions *)
linenoiseCompletions
typedef struct linenoiseCompletions linenoiseCompletions
Function Documentation
linenoise()
char * linenoise (const char * prompt)
linenoise is a readline replacement.
call it with a prompt to display and it will return a line of input from the user
Parameters
prompt text of prompt to display to the user
Returns
the returned string belongs to the caller on return and must be freed to prevent memory leaks
Referenced by native_console_in().
linenoiseAddCompletion()
void linenoiseAddCompletion (linenoiseCompletions * lc, const char * str)
linenoiseClearScreen()
void linenoiseClearScreen (void)
Clear the screen ONLY (no redisplay of anything)
Referenced by InputBuffer::clearScreen().
linenoiseHistoryAdd()
int linenoiseHistoryAdd (const char * line)
Referenced by InputBuffer::getInputLine(), linenoiseHistoryLoad(), and native_console_in().
linenoiseHistoryFree()
void linenoiseHistoryFree (void)
Referenced by native_console_close(), and quit_cmd().
linenoiseHistoryLine()
char * linenoiseHistoryLine (int index)
linenoiseHistoryLoad()
int linenoiseHistoryLoad (const char * filename)
linenoiseHistorySave()
int linenoiseHistorySave (const char * filename)
linenoiseHistorySetMaxLen()
int linenoiseHistorySetMaxLen (int len)
Referenced by native_console_open().
linenoiseInstallWindowChangeHandler()
int linenoiseInstallWindowChangeHandler (void)
the following are extensions to the original linenoise API
linenoiseKeyType()
int linenoiseKeyType (void)
returns type of key pressed: 1 = CTRL-C, 2 = CTRL-D, 0 = other
linenoisePreloadBuffer()
void linenoisePreloadBuffer (const char * preloadText)
linenoisePreloadBuffer provides text to be inserted into the command buffer
the provided text will be processed to be usable and will be used to preload the input buffer on the next call to linenoise()
Parameters
preloadText text to begin with on the next call to linenoise()
linenoisePrintKeyCodes()
void linenoisePrintKeyCodes (void)
linenoiseSetCompletionCallback()
void linenoiseSetCompletionCallback (linenoiseCompletionCallback * fn)
Register a callback function to be called for tab-completion.
linenoiseSetMultiLine()
void linenoiseSetMultiLine (int ml)
Set if to use or not the multi line mode.
note that this is a stub only, as linenoise-ng always multi-line