vsid: arch/gtk3/widgets/base/resourcehelpers.h File Reference
resourcehelpers.h File Reference
Helper functions for resource widgets - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
void resource_widget_set_int (GtkWidget *widget, const char *key, int value)
Helper functions for resource widgets.
int resource_widget_get_int (GtkWidget *widget, const char *key)
Get integer value of property key of widget.
void resource_widget_set_string (GtkWidget *widget, const char *key, const char *value)
Set property key of widget to string value.
const char * resource_widget_get_string (GtkWidget *widget, const char *key)
Get string value for property key of widget.
void resource_widget_free_string (GtkWidget *widget, const char *key)
Free memory used by property key in widget.
void resource_widget_set_resource_name (GtkWidget *widget, const char *resource)
Set the "ResourceName" property of widget to resoucre.
void resource_widget_set_resource_name_valist (GtkWidget *widget, const char *format, va_list args)
Set resource name using a valist.
const char * resource_widget_get_resource_name (GtkWidget *widget)
Get name of resource currently registerd to widget.
Detailed Description
Helper functions for resource widgets - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
resource_widget_free_string()
void resource_widget_free_string (GtkWidget * widget, const char * key)
Free memory used by property key in widget.
Frees the string allocated on the heap by lib_strdup().
Parameters
[in,out] widget widget
[in] key property name
Referenced by on_scale_custom_destroy(), on_scale_exp_destroy(), and on_spin_button_double_destroy().
resource_widget_get_int()
int resource_widget_get_int (GtkWidget * widget, const char * key)
Get integer value of property key of widget.
Parameters
[in,out] widget widget
[in] key property name
Returns
integer value of property key
Referenced by custom_get_params(), exponential_get_params(), on_spin_button_input(), on_spin_button_output(), vice_gtk3_resource_radiogroup_reset(), vice_gtk3_resource_scale_custom_reset(), vice_gtk3_resource_scale_int_reset(), and vice_gtk3_resource_spin_int_reset().
resource_widget_get_resource_name()
const char * resource_widget_get_resource_name (GtkWidget * widget)
Get name of resource currently registerd to widget.
Parameters
[in] widget widget
Returns
value of the "ResourceName" property of widget
Referenced by custom_get_display_value(), custom_new_helper(), exp_new_helper(), on_custom_changed(), on_device_changed(), on_exp_changed(), on_radio_toggled(), on_scale_int_changed(), on_spin_button_double_value_changed(), on_spin_button_value_changed(), resource_radiogroup_new_helper(), resource_scale_int_new_helper(), resource_spin_int_new_helper(), vice_gtk3_resource_radiogroup_factory(), vice_gtk3_resource_radiogroup_get(), vice_gtk3_resource_radiogroup_sync(), vice_gtk3_resource_scale_custom_factory(), vice_gtk3_resource_scale_custom_set(), vice_gtk3_resource_scale_custom_sync(), vice_gtk3_resource_scale_int_factory(), vice_gtk3_resource_scale_int_sync(), vice_gtk3_resource_spin_double_factory(), vice_gtk3_resource_spin_double_sync(), vice_gtk3_resource_spin_int_factory(), vice_gtk3_resource_spin_int_get(), and vice_gtk3_resource_spin_int_sync().
resource_widget_get_string()
const char * resource_widget_get_string (GtkWidget * widget, const char * key)
Get string value for property key of widget.
Parameters
[in] widget widget
[in] key property name
Returns
value for key
Referenced by resource_widget_get_resource_name(), and vice_gtk3_resource_spin_double_reset().
resource_widget_set_int()
void resource_widget_set_int (GtkWidget * widget, const char * key, int value)
Helper functions for resource widgets.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Set property key of widget to integer value
Sets key to value using g_object_set_data(). Since this is a simple scalar, it shouldn't be freed.
Parameters
[in,out] widget widget
[in] key property name
[in] value property value
Referenced by custom_new_helper(), exp_new_helper(), resource_radiogroup_new_helper(), resource_scale_int_new_helper(), vice_gtk3_resource_spin_int_new(), and vice_gtk3_resource_spin_int_set_fake_digits().
resource_widget_set_resource_name()
void resource_widget_set_resource_name (GtkWidget * widget, const char * resource)
Set the "ResourceName" property of widget to resoucre.
Stores a copy of resource in widget using lib_strdup(). The copy will be freed on widget destruction.
Parameters
[in,out] widget widget
[in] resource resource name
Referenced by clockport_device_widget_create(), printer_driver_widget_create(), printer_output_mode_widget_create(), resource_widget_set_resource_name_valist(), vice_gtk3_resource_browser_new(), vice_gtk3_resource_browser_save_new(), vice_gtk3_resource_radiogroup_new(), vice_gtk3_resource_scale_custom_new(), vice_gtk3_resource_scale_custom_new_printf(), vice_gtk3_resource_scale_exp_new(), vice_gtk3_resource_scale_int_new(), vice_gtk3_resource_spin_double_new(), and vice_gtk3_resource_spin_int_new().
resource_widget_set_resource_name_valist()
void resource_widget_set_resource_name_valist (GtkWidget * widget, const char * format, va_list args)
Set resource name using a valist.
The caller is required to release args after using this function.
Parameters
[in] widget widget to set resource name property
[in] format format string for the resource name
[in] args argument list of format
Referenced by vice_gtk3_resource_radiogroup_new_sprintf(), vice_gtk3_resource_scale_int_new_sprintf(), and vice_gtk3_resource_spin_int_new_sprintf().
resource_widget_set_string()
void resource_widget_set_string (GtkWidget * widget, const char * key, const char * value)
Set property key of widget to string value.
Sets key to value using g_object_set_data() with lib_strdup(), so this function can be called with temporary data from the caller. This function can be used to update key with a new value, the old string is freed before setting a new one.
Parameters
[in,out] widget widget
[in] key property name
[in] value property value
Note
Call resource_widget_free_string(widget, key) to free memory used by value.
Referenced by custom_new_helper(), exp_new_helper(), resource_widget_set_resource_name(), and vice_gtk3_resource_spin_double_new().