x128: core/i8255a.c File Reference
i8255a.c File Reference
#include "vice.h"
#include "log.h"
#include "types.h"
#include "snapshot.h"
#include "monitor.h"
#include "i8255a.h"
Macros
#define LOG LOG_DEFAULT
#define ERR LOG_ERR
#define LOG1(_x_)
#define DBG(_x_)
#define CRIT(_x_) log_message _x_
Functions
void i8255a_reset (i8255a_state *ctx)
uint8_t i8255a_read (i8255a_state *ctx, int8_t reg)
uint8_t i8255a_peek (i8255a_state *ctx, int8_t reg)
void i8255a_store (i8255a_state *ctx, int8_t reg, uint8_t data)
int i8255a_snapshot_write_data (i8255a_state *ctx, snapshot_module_t *m)
int i8255a_snapshot_read_data (i8255a_state *ctx, snapshot_module_t *m)
int i8255a_dump (i8255a_state *ctx)
Macro Definition Documentation
CRIT
#define CRIT (_x_) log_message _x_
DBG
#define DBG (_x_)
ERR
#define ERR LOG_ERR
LOG
#define LOG LOG_DEFAULT
LOG1
#define LOG1 (_x_)
Function Documentation
i8255a_dump()
int i8255a_dump (i8255a_state * ctx)
Referenced by drivemem_ioreg_list_get().
i8255a_peek()
uint8_t i8255a_peek (i8255a_state * ctx, int8_t reg)
Referenced by i8255a_dump().
i8255a_read()
uint8_t i8255a_read (i8255a_state * ctx, int8_t reg)
Referenced by cmdhd_read(), and i8255a_peek().
i8255a_reset()
void i8255a_reset (i8255a_state * ctx)
Referenced by cmdhd_reset().
i8255a_snapshot_read_data()
int i8255a_snapshot_read_data (i8255a_state * ctx, snapshot_module_t * m)
Referenced by cmdhd_snapshot_read_module().
i8255a_snapshot_write_data()
int i8255a_snapshot_write_data (i8255a_state * ctx, snapshot_module_t * m)
Referenced by cmdhd_snapshot_write_module().
i8255a_store()
void i8255a_store (i8255a_state * ctx, int8_t reg, uint8_t data)
Referenced by cmdhd_store().