x128: tape.h File Reference
tape.h File Reference
#include <stdio.h>
#include "types.h"
Data Structures
struct tape_image_s
struct tape_init_s
struct tape_file_record_s
Macros
#define TAPE_TYPE_T64 0
#define TAPE_TYPE_TAP 1
#define TAPE_ENCODING_NONE 0
#define TAPE_ENCODING_CBM 1
#define TAPE_ENCODING_TURBOTAPE 2
#define TAPE_CAS_TYPE_BAS 1
Note: PETs and CBM2 machines use (only) type 1, but they always load absolute anyway.
#define TAPE_CAS_TYPE_DATA_BLOCK 2
Data Block (SEQ)
#define TAPE_CAS_TYPE_PRG 3
Binary Program (absolute load, SAVE "",1,1 (VIC-20 and later))
#define TAPE_CAS_TYPE_DATA 4
Data File Header (SEQ)
#define TAPE_CAS_TYPE_EOF 5
End of Tape marker (SAVE "",1,n+2)
#define TAPE_BEHAVIOUR_NORMAL 0
tape interrupt is falling-edge triggered, normal tape blocks end with a long and a short pulse
#define TAPE_BEHAVIOUR_C16 1
tape senses both falling edges and rising edges, normal tape blocks end with a medium and a short pulse
Typedefs
typedef struct tape_image_s tape_image_t
typedef struct tape_init_s tape_init_t
typedef struct tape_file_record_s tape_file_record_t
Functions
int tape_init (const tape_init_t *init)
Initialize the tape emulation, using the traps in ‘trap_list’.
int tape_reinit (const tape_init_t *init)
re-init the traps, needed to switch between different configurations in x128
void tape_shutdown (void)
int tape_deinstall (void)
void tape_get_header (tape_image_t *tape_image, uint8_t *name)
int tape_find_header_trap (void)
Find the next Tape Header and load it onto the Tape Buffer.
int tape_receive_trap (void)
int tape_find_header_trap_plus4 (void)
int tape_receive_trap_plus4 (void)
const char * tape_get_file_name (int port)
int tape_tap_attached (int port)
void tape_traps_install (void)
void tape_traps_deinstall (void)
tape_file_record_t * tape_get_current_file_record (tape_image_t *tape_image)
int tape_seek_start (tape_image_t *tape_image)
int tape_seek_to_file (tape_image_t *tape_image, unsigned int file_number)
int tape_seek_to_next_file (tape_image_t *tape_image, unsigned int allow_rewind)
int tape_seek_to_offset (tape_image_t *tape_image, unsigned long offset)
unsigned long tape_get_offset (tape_image_t *tape_image)
int tape_read (tape_image_t *tape_image, uint8_t *buf, size_t size)
used by virtual devices
int tape_internal_close_tape_image (tape_image_t *tape_image)
tape_image_t * tape_internal_open_tape_image (const char *name, unsigned int read_only)
int tape_image_detach (unsigned int unit)
External tape image interface.
void tape_image_detach_all (void)
int tape_image_detach_internal (unsigned int unit)
Detach.
int tape_image_attach (unsigned int unit, const char *name)
int tape_image_open (tape_image_t *tape_image)
int tape_image_close (tape_image_t *tape_image)
int tape_image_create (const char *name, unsigned int type)
void tape_image_event_playback (unsigned int unit, const char *filename)
Variables
tape_image_t * tape_image_dev []
The tape image for device 1.
Macro Definition Documentation
TAPE_BEHAVIOUR_C16
#define TAPE_BEHAVIOUR_C16 1
tape senses both falling edges and rising edges, normal tape blocks end with a medium and a short pulse
TAPE_BEHAVIOUR_NORMAL
#define TAPE_BEHAVIOUR_NORMAL 0
tape interrupt is falling-edge triggered, normal tape blocks end with a long and a short pulse
TAPE_CAS_TYPE_BAS
#define TAPE_CAS_TYPE_BAS 1
Note: PETs and CBM2 machines use (only) type 1, but they always load absolute anyway.
Relocatable Program (loaded to basic start, SAVE "",1,0)
TAPE_CAS_TYPE_DATA
#define TAPE_CAS_TYPE_DATA 4
Data File Header (SEQ)
TAPE_CAS_TYPE_DATA_BLOCK
#define TAPE_CAS_TYPE_DATA_BLOCK 2
Data Block (SEQ)
TAPE_CAS_TYPE_EOF
#define TAPE_CAS_TYPE_EOF 5
End of Tape marker (SAVE "",1,n+2)
TAPE_CAS_TYPE_PRG
#define TAPE_CAS_TYPE_PRG 3
Binary Program (absolute load, SAVE "",1,1 (VIC-20 and later))
TAPE_ENCODING_CBM
#define TAPE_ENCODING_CBM 1
TAPE_ENCODING_NONE
#define TAPE_ENCODING_NONE 0
TAPE_ENCODING_TURBOTAPE
#define TAPE_ENCODING_TURBOTAPE 2
TAPE_TYPE_T64
#define TAPE_TYPE_T64 0
TAPE_TYPE_TAP
#define TAPE_TYPE_TAP 1
Typedef Documentation
tape_file_record_t
typedef struct tape_file_record_s tape_file_record_t
tape_image_t
typedef struct tape_image_s tape_image_t
tape_init_t
typedef struct tape_init_s tape_init_t
Function Documentation
tape_deinstall()
int tape_deinstall (void)
tape_find_header_trap()
int tape_find_header_trap (void)
Find the next Tape Header and load it onto the Tape Buffer.
< start address
< start address
< end address
< end address
< filename
< End of Tape marker (SAVE "",1,n+2)
tape_find_header_trap_plus4()
int tape_find_header_trap_plus4 (void)
< start address
< start address
< end address
< end address
< filename
< End of Tape marker (SAVE "",1,n+2)
tape_get_current_file_record()
tape_file_record_t * tape_get_current_file_record (tape_image_t * tape_image)
Referenced by fsdevice_open_file(), and tape_read_contents().
tape_get_file_name()
const char * tape_get_file_name (int port)
tape_get_header()
void tape_get_header (tape_image_t * tape_image, uint8_t * name)
Referenced by tape_read_contents().
tape_get_offset()
unsigned long tape_get_offset (tape_image_t * tape_image)
Referenced by mon_tape_offs().
tape_image_attach()
int tape_image_attach (unsigned int unit, const char * name)
Referenced by autostart_tape(), create_tape_image(), do_attach(), do_smart_attach(), initcmdline_check_attach(), mon_attach(), and tape_snapshot_read_tapimage_module().
tape_image_close()
int tape_image_close (tape_image_t * tape_image)
Referenced by fsdevice_close(), tape_image_detach_internal(), and tape_internal_close_tape_image().
tape_image_create()
int tape_image_create (const char * name, unsigned int type)
Referenced by cbmimage_create_image().
tape_image_detach()
int tape_image_detach (unsigned int unit)
External tape image interface.
Referenced by autostart_tape(), mon_detach(), tape_detach_action(), and tape_image_detach_all().
tape_image_detach_all()
void tape_image_detach_all (void)
Referenced by resources_set_defaults().
tape_image_detach_internal()
int tape_image_detach_internal (unsigned int unit)
Detach.
Referenced by machine_specific_shutdown(), tape_deinstall(), tape_image_attach_internal(), tape_image_detach(), tape_image_event_playback(), and tape_snapshot_read_module().
tape_image_event_playback()
void tape_image_event_playback (unsigned int unit, const char * filename)
Referenced by event_alarm_handler(), event_playback_attach_image(), and event_playback_event_list().
tape_image_open()
int tape_image_open (tape_image_t * tape_image)
Referenced by fsdevice_open_file(), tape_image_attach_internal(), and tape_internal_open_tape_image().
tape_init()
int tape_init (const tape_init_t * init)
Initialize the tape emulation, using the traps in ‘trap_list’.
Todo:
FIXME: This should be passed through a struct.
Referenced by machine_tape_init_c128(), and machine_tape_init_c64().
tape_internal_close_tape_image()
int tape_internal_close_tape_image (tape_image_t * tape_image)
Referenced by tapecontents_read().
tape_internal_open_tape_image()
tape_image_t * tape_internal_open_tape_image (const char * name, unsigned int read_only)
Referenced by tapecontents_read().
tape_read()
int tape_read (tape_image_t * tape_image, uint8_t * buf, size_t size)
used by virtual devices
Referenced by command_read().
tape_receive_trap()
int tape_receive_trap (void)
tape_receive_trap_plus4()
int tape_receive_trap_plus4 (void)
tape_reinit()
int tape_reinit (const tape_init_t * init)
re-init the traps, needed to switch between different configurations in x128
Referenced by machine_tape_init_c128(), and machine_tape_init_c64().
tape_seek_start()
int tape_seek_start (tape_image_t * tape_image)
Referenced by autostart_tape(), and fsdevice_open_file().
tape_seek_to_file()
int tape_seek_to_file (tape_image_t * tape_image, unsigned int file_number)
Referenced by autostart_tape(), and fsdevice_open_file().
tape_seek_to_next_file()
int tape_seek_to_next_file (tape_image_t * tape_image, unsigned int allow_rewind)
Referenced by tape_read_contents().
tape_seek_to_offset()
int tape_seek_to_offset (tape_image_t * tape_image, unsigned long offset)
Referenced by autostart_tape(), and mon_tape_offs().
tape_shutdown()
void tape_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
tape_tap_attached()
int tape_tap_attached (int port)
Referenced by autostart_tape().
tape_traps_deinstall()
void tape_traps_deinstall (void)
Referenced by tape_deinstall(), tape_image_attach_internal(), and tape_reinit().
tape_traps_install()
void tape_traps_install (void)
Referenced by tape_image_detach_internal(), tape_init(), and tape_reinit().
Variable Documentation
tape_image_dev
tape_image_t* tape_image_dev[] extern
The tape image for device 1.
Referenced by autostart_tape(), dir_menu_popup_create(), mon_tape_offs(), tape_deinstall(), tape_find_header_trap(), tape_find_header_trap_plus4(), tape_get_file_name(), tape_image_attach_internal(), tape_image_detach_internal(), tape_init(), tape_receive_trap(), tape_receive_trap_plus4(), tape_shutdown(), tape_snapshot_read_module(), tape_snapshot_write_module(), tape_snapshot_write_tapimage_module(), and tape_tap_attached().