vsid: arch/gtk3/widgets/settings_joystick.c File Reference
settings_joystick.c File Reference
Widget to control settings for joysticks.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include "actions-joystick.h"
#include "debug_gtk3.h"
#include "joyport.h"
#include "joystick.h"
#include "joystickdevicewidget.h"
#include "keysetdialog.h"
#include "lib.h"
#include "machine.h"
#include "resources.h"
#include "ui.h"
#include "uiactions.h"
#include "vice_gtk3.h"
#include "settings_joystick.h"
Macros
#define ADAPTER_PORT_COUNT_C64 8
Number of joystick adapter ports for C64.
#define ADAPTER_PORT_COUNT_C64DTV 8
Number of joystick adapter ports for C64 DTV.
#define ADAPTER_PORT_COUNT_SCPU64 8
Number of joystick adapter ports for SCPU64.
#define ADAPTER_PORT_COUNT_C128 8
Number of joystick adapter ports for C128.
#define ADAPTER_PORT_COUNT_VIC20 8
Number of joystick adapter ports for VIC-20.
#define ADAPTER_PORT_COUNT_PLUS4 3
Number of joystick adapter ports for Plus4.
#define ADAPTER_PORT_COUNT_CBM5x0 8
Number of joystick adapter ports for CBM-II 5x0/P.
#define ADAPTER_PORT_COUNT_CBM6x0 8
Number of joystick adapter ports for CBM-II 6x0/7x0/B.
#define ADAPTER_PORT_COUNT_PET 3
Number of joystick adapter ports for PET.
Functions
static void on_swap_joysticks_toggled (GtkWidget *button, gpointer data)
Handler for the 'toggled' event of the "Swap joysticks" button.
static void on_keyset_configure_button_clicked (GtkWidget *widget, gpointer data)
Handler for the 'clicked' event of the "Configure keysets" button.
static GtkWidget * create_swap_joysticks_button (void)
Create a button to swap joysticks #1 and #2.
static GtkWidget * create_keyset_enable_checkbox (void)
Create a check button to enable "user-defined keysets".
static GtkWidget * create_opposite_enable_checkbox (void)
Create a check button to enable "Allow opposite directions".
static GtkWidget * create_keyset_configure_button (int keyset)
Create button to pop up dialog to configure a keyset.
static int layout_add_control_ports (GtkGrid *layout, int row, int count)
Add control port joysticks.
static int layout_add_adapter_ports (GtkGrid *layout, int row, int count)
Add Joystick Adapter ports.
static int layout_add_sidcard_port (GtkGrid *layout, int row)
Add SIDCard joystick port.
static int layout_add_swap_button (GtkGrid *layout, int row)
Add "Swap joystick" button.
static int create_c64_layout (GtkGrid *grid)
Create layout for x64/x64sc/xscpu64/x128.
static int create_c64dtv_layout (GtkGrid *grid)
Create layout for x64dtv.
static int create_vic20_layout (GtkGrid *grid)
Create layout for xvic.
static int create_plus4_layout (GtkGrid *grid)
Create layout for xplus4.
static int create_cbm5x0_layout (GtkGrid *grid)
Create layout for xcbm5x0.
static int create_cbm6x0_layout (GtkGrid *grid)
Create layout for xcbm2.
static int create_pet_layout (GtkGrid *grid)
Create layout for xpet.
GtkWidget * settings_joystick_widget_create (GtkWidget *parent)
Create joystick settings main widget.
Variables
static GtkWidget * device_widgets [JOYPORT_MAX_PORTS]
References to the joystick device widgets.
Detailed Description
Widget to control settings for joysticks.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
ADAPTER_PORT_COUNT_C128
#define ADAPTER_PORT_COUNT_C128 8
Number of joystick adapter ports for C128.
ADAPTER_PORT_COUNT_C64
#define ADAPTER_PORT_COUNT_C64 8
Number of joystick adapter ports for C64.
ADAPTER_PORT_COUNT_C64DTV
#define ADAPTER_PORT_COUNT_C64DTV 8
Number of joystick adapter ports for C64 DTV.
ADAPTER_PORT_COUNT_CBM5x0
#define ADAPTER_PORT_COUNT_CBM5x0 8
Number of joystick adapter ports for CBM-II 5x0/P.
ADAPTER_PORT_COUNT_CBM6x0
#define ADAPTER_PORT_COUNT_CBM6x0 8
Number of joystick adapter ports for CBM-II 6x0/7x0/B.
ADAPTER_PORT_COUNT_PET
#define ADAPTER_PORT_COUNT_PET 3
Number of joystick adapter ports for PET.
ADAPTER_PORT_COUNT_PLUS4
#define ADAPTER_PORT_COUNT_PLUS4 3
Number of joystick adapter ports for Plus4.
The xplus4 code currently supports three userport joysticks and one joystick via the SIDCard expansion.
Should this change in the future, just change the value (to 8).
ADAPTER_PORT_COUNT_SCPU64
#define ADAPTER_PORT_COUNT_SCPU64 8
Number of joystick adapter ports for SCPU64.
ADAPTER_PORT_COUNT_VIC20
#define ADAPTER_PORT_COUNT_VIC20 8
Number of joystick adapter ports for VIC-20.
Function Documentation
create_c64_layout()
static int create_c64_layout (GtkGrid * grid) static
Create layout for x64/x64sc/xscpu64/x128.
Parameters
[in,out] grid main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_joystick_widget_create().
create_c64dtv_layout()
static int create_c64dtv_layout (GtkGrid * grid) static
Create layout for x64dtv.
Parameters
[in,out] grid main widget grid
Returns
number of rows added to grid
Referenced by settings_joystick_widget_create().
create_cbm5x0_layout()
static int create_cbm5x0_layout (GtkGrid * grid) static
Create layout for xcbm5x0.
Parameters
[in,out] grid main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_joystick_widget_create().
create_cbm6x0_layout()
static int create_cbm6x0_layout (GtkGrid * grid) static
Create layout for xcbm2.
Parameters
[in,out] grid main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_joystick_widget_create().
create_keyset_configure_button()
static GtkWidget * create_keyset_configure_button (int keyset) static
Create button to pop up dialog to configure a keyset.
Parameters
[in] keyset keyset number (1 for 'A', 2 for 'B')
Returns
GtkButton
Referenced by settings_joystick_widget_create().
create_keyset_enable_checkbox()
static GtkWidget * create_keyset_enable_checkbox (void) static
Create a check button to enable "user-defined keysets".
Returns
GtkCheckButton
Referenced by settings_joystick_widget_create().
create_opposite_enable_checkbox()
static GtkWidget * create_opposite_enable_checkbox (void) static
Create a check button to enable "Allow opposite directions".
Returns
GtkCheckButton
Referenced by settings_joystick_widget_create().
create_pet_layout()
static int create_pet_layout (GtkGrid * grid) static
Create layout for xpet.
Parameters
[in,out] grid main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_joystick_widget_create().
create_plus4_layout()
static int create_plus4_layout (GtkGrid * grid) static
Create layout for xplus4.
Parameters
[in,out] grid main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_joystick_widget_create().
create_swap_joysticks_button()
static GtkWidget * create_swap_joysticks_button (void) static
Create a button to swap joysticks #1 and #2.
Returns
GtkButton
Referenced by layout_add_swap_button().
create_vic20_layout()
static int create_vic20_layout (GtkGrid * grid) static
Create layout for xvic.
Parameters
[in,out] grid main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_joystick_widget_create().
layout_add_adapter_ports()
static int layout_add_adapter_ports (GtkGrid * layout, int row, int count) static
Add Joystick Adapter ports.
Add widgets to the layout for the joystick adapter ports.
The ports start numbered at 1, but the internal resources ("JoyDeviceX") start at 3 ("JoyDevice3").
Parameters
[in,out] layout main widget grid
[in] row starting row in layout
[in] count number of widgets to add to the layout
Returns
row in the layout for additional widgets
Referenced by create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), create_pet_layout(), create_plus4_layout(), and create_vic20_layout().
layout_add_control_ports()
static int layout_add_control_ports (GtkGrid * layout, int row, int count) static
Add control port joysticks.
Add widgets to the layout for the control port joysticks.
Parameters
[in,out] layout main widget grid
[in] row starting row in layout
[in] count number of widgets to add to the layout
Returns
row in the layout for additional widgets
Referenced by create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_plus4_layout(), and create_vic20_layout().
layout_add_sidcard_port()
static int layout_add_sidcard_port (GtkGrid * layout, int row) static
Add SIDCard joystick port.
Add widget to the layout for the SIDVCard joystick.
This device is currently mappend to JOYDEV_5 (resource "JoyDevice5").
Parameters
[in,out] layout main widget grid
[in] row starting row in layout
Returns
row in the layout for additional widgets
Referenced by create_plus4_layout().
layout_add_swap_button()
static int layout_add_swap_button (GtkGrid * layout, int row) static
Add "Swap joystick" button.
Add widget to the layout to swap control port
Parameters
[in,out] layout main widget grid
[in] row starting row in layout
Returns
row in the layout for additional widgets
Referenced by create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), and create_plus4_layout().
on_keyset_configure_button_clicked()
static void on_keyset_configure_button_clicked (GtkWidget * widget, gpointer data) static
Handler for the 'clicked' event of the "Configure keysets" button.
Parameters
[in] widget button (unused)
[in] data keyset number (int)
Referenced by create_keyset_configure_button().
on_swap_joysticks_toggled()
static void on_swap_joysticks_toggled (GtkWidget * button, gpointer data) static
Handler for the 'toggled' event of the "Swap joysticks" button.
Swaps resources JoyDevice1/JoyDevice2 and JoyPort1Device/JoyPort2Device and updates the UI accordingly.
Parameters
[in] button toggle button
[in] data extra event data (unused)
Referenced by create_swap_joysticks_button().
settings_joystick_widget_create()
GtkWidget * settings_joystick_widget_create (GtkWidget * parent)
Create joystick settings main widget.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
Variable Documentation
device_widgets
GtkWidget* device_widgets[JOYPORT_MAX_PORTS] static
References to the joystick device widgets.
These references are used to update the UI when swapping joysticks.
Referenced by layout_add_adapter_ports(), layout_add_control_ports(), layout_add_sidcard_port(), and on_swap_joysticks_toggled().