vsid: c64/c64drive.c File Reference
c64drive.c File Reference
#include "vice.h"
#include <stdio.h>
#include "drive.h"
#include "iec-c64exp.h"
#include "iec.h"
#include "iecieee.h"
#include "ieee.h"
#include "machine.h"
#include "machine-drive.h"
#include "types.h"
Functions
int machine_drive_resources_init (void)
void machine_drive_resources_shutdown (void)
int machine_drive_cmdline_options_init (void)
void machine_drive_init (struct diskunit_context_s *drv)
void machine_drive_shutdown (struct diskunit_context_s *drv)
void machine_drive_reset (struct diskunit_context_s *drv)
void machine_drive_mem_init (struct diskunit_context_s *drv, unsigned int type)
void machine_drive_setup_context (struct diskunit_context_s *drv)
void machine_drive_idling_method (unsigned int dnr)
void machine_drive_rom_load (void)
void machine_drive_rom_setup_image (unsigned int dnr)
int machine_drive_rom_check_loaded (unsigned int type)
void machine_drive_rom_do_checksum (unsigned int dnr)
int machine_drive_snapshot_read (struct diskunit_context_s *ctxptr, struct snapshot_s *s)
int machine_drive_snapshot_write (struct diskunit_context_s *ctxptr, struct snapshot_s *s)
int machine_drive_image_attach (struct disk_image_s *image, unsigned int unit, unsigned int drive)
int machine_drive_image_detach (struct disk_image_s *image, unsigned int unit, unsigned int drive)
void machine_drive_port_default (struct diskunit_context_s *drv)
void machine_drive_flush (void)
void machine_drive_stub (void)
Function Documentation
machine_drive_cmdline_options_init()
int machine_drive_cmdline_options_init (void)
Referenced by drive_cmdline_options_init().
machine_drive_flush()
void machine_drive_flush (void)
machine_drive_idling_method()
void machine_drive_idling_method (unsigned int dnr)
Referenced by drive_resources_type().
machine_drive_image_attach()
int machine_drive_image_attach (struct disk_image_s * image, unsigned int unit, unsigned int drive)
machine_drive_image_detach()
int machine_drive_image_detach (struct disk_image_s * image, unsigned int unit, unsigned int drive)
machine_drive_init()
void machine_drive_init (struct diskunit_context_s * drv)
Referenced by drive_cpu_early_init_all().
machine_drive_mem_init()
void machine_drive_mem_init (struct diskunit_context_s * drv, unsigned int type)
Referenced by drivemem_init().
machine_drive_port_default()
void machine_drive_port_default (struct diskunit_context_s * drv)
Referenced by drive_disable(), and drive_init().
machine_drive_reset()
void machine_drive_reset (struct diskunit_context_s * drv)
Referenced by cpu_reset(), drivecpu65c02_snapshot_read_module(), and drivecpu_snapshot_read_module().
machine_drive_resources_init()
int machine_drive_resources_init (void)
Referenced by drive_resources_init().
machine_drive_resources_shutdown()
void machine_drive_resources_shutdown (void)
Referenced by drive_resources_shutdown().
machine_drive_rom_check_loaded()
int machine_drive_rom_check_loaded (unsigned int type)
machine_drive_rom_do_checksum()
void machine_drive_rom_do_checksum (unsigned int dnr)
Referenced by driverom_snapshot_read().
machine_drive_rom_load()
void machine_drive_rom_load (void)
Referenced by driverom_load_images().
machine_drive_rom_setup_image()
void machine_drive_rom_setup_image (unsigned int dnr)
Referenced by drive_init(), drive_set_disk_drive_type(), drive_snapshot_read_module(), and driverom_load().
machine_drive_setup_context()
void machine_drive_setup_context (struct diskunit_context_s * drv)
Referenced by drive_setup_context_for_unit().
machine_drive_shutdown()
void machine_drive_shutdown (struct diskunit_context_s * drv)
Referenced by drivecpu65c02_shutdown(), and drivecpu_shutdown().
machine_drive_snapshot_read()
int machine_drive_snapshot_read (struct diskunit_context_s * ctxptr, struct snapshot_s * s)
Referenced by drive_snapshot_read_module().
machine_drive_snapshot_write()
int machine_drive_snapshot_write (struct diskunit_context_s * ctxptr, struct snapshot_s * s)
Referenced by drive_snapshot_write_module().
machine_drive_stub()
void machine_drive_stub (void)