vsid: monitor/mon_registerz80.c File Reference
mon_registerz80.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "lib.h"
#include "log.h"
#include "mon_register.h"
#include "mon_util.h"
#include "montypes.h"
#include "uimon.h"
#include "z80regs.h"
Macros
#define DBG(_x_)
#define REG_LIST_Z80_SIZE (29 + 1)
Functions
static unsigned int mon_register_get_val (int mem, int reg_id)
static void mon_register_set_val (int mem, int reg_id, uint16_t val)
static void mon_register_print (int mem)
static mon_reg_list_t * mon_register_list_getz80 (int mem)
void mon_registerz80_init (monitor_cpu_type_t *monitor_cpu_type)
Variables
static const mon_reg_list_t mon_reg_list_z80 [(29+1)]
Macro Definition Documentation
DBG
#define DBG (_x_)
REG_LIST_Z80_SIZE
#define REG_LIST_Z80_SIZE (29 + 1)
Todo:
make the other functions here use this table. when done also do the same with the other CPUs and finally move common code to mon_register.c
Function Documentation
mon_register_get_val()
static unsigned int mon_register_get_val (int mem, int reg_id) static
Referenced by mon_register_list_getz80(), mon_register_print(), and mon_registerz80_init().
mon_register_list_getz80()
static mon_reg_list_t * mon_register_list_getz80 (int mem) static
Todo:
try to make this a generic function, move it into mon_register.c and remove mon_register_list_get from the monitor_cpu_type_t struct
Referenced by mon_registerz80_init().
mon_register_print()
static void mon_register_print (int mem) static
Todo:
should use mon_register_list_get
Referenced by mon_registerz80_init().
mon_register_set_val()
static void mon_register_set_val (int mem, int reg_id, uint16_t val) static
Referenced by mon_registerz80_init().
mon_registerz80_init()
void mon_registerz80_init (monitor_cpu_type_t * monitor_cpu_type)
Variable Documentation
mon_reg_list_z80
const mon_reg_list_t mon_reg_list_z80[(29+1)] static
Initial value:
= {
    {       "PC",        e_PC, 16,                      0, 0, 0 },
    {        "A",         e_A,  8,                      0, 0, 0 },
    {       "AF",        e_AF, 16,                      0, 0, 0 },
    {        "B",         e_B,  8,                      0, 0, 0 },
    {        "C",         e_C,  8,                      0, 0, 0 },
    {       "BC",        e_BC, 16,                      0, 0, 0 },
    {        "D",         e_D,  8,                      0, 0, 0 },
    {        "E",         e_E,  8,                      0, 0, 0 },
    {       "DE",        e_DE, 16,                      0, 0, 0 },
    {        "H",         e_H,  8,                      0, 0, 0 },
    {        "L",         e_L,  8,                      0, 0, 0 },
    {       "HL",        e_HL, 16,                      0, 0, 0 },
    {      "IXH",       e_IXH,  8,                      0, 0, 0 },
    {      "IXL",       e_IXL,  8,                      0, 0, 0 },
    {      "IX",         e_IX, 16,                      0, 0, 0 },
    {      "IYH",       e_IYH,  8,                      0, 0, 0 },
    {      "IYL",       e_IYL,  8,                      0, 0, 0 },
    {       "IY",        e_IY, 16,                      0, 0, 0 },
    {       "SP",        e_SP, 16,                      0, 0, 0 },
    {        "I",         e_I,  8,                      0, 0, 0 },
    {        "R",         e_R,  8,                      0, 0, 0 },
    {      "AF'",       e_AF2, 16,                      0, 0, 0 },
    {      "BC'",       e_BC2, 16,                      0, 0, 0 },
    {      "DE'",       e_DE2, 16,                      0, 0, 0 },
    {      "HL'",       e_HL2, 16,                      0, 0, 0 },
    {      "FL",      e_FLAGS,  8,                      0, 0, 0 },
    { "SZIH-P-C",     e_FLAGS,  8,   0x01  , 0, 0 },
    {     "LIN", e_Rasterline, 16,                      0, 0, 0 },
    {     "CYC",      e_Cycle, 16,                      0, 0, 0 },
    { NULL, -1,  0,  0, 0, 0 }
}
Referenced by mon_register_list_getz80().