vsid: monitor/monitor.c File Reference
monitor.c File Reference
The VICE built-in monitor.
#include "vice.h"
#include <assert.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <errno.h>
#include <strings.h>
#include "archdep.h"
#include "archdep_defs.h"
#include "cartio.h"
#include "charset.h"
#include "cmdline.h"
#include "console.h"
#include "datasette.h"
#include "drive.h"
#include "interrupt.h"
#include "kbdbuf.h"
#include "lib.h"
#include "util.h"
#include "log.h"
#include "machine.h"
#include "machine-video.h"
#include "mem.h"
#include "mon_breakpoint.h"
#include "mon_disassemble.h"
#include "mon_memmap.h"
#include "mon_memory.h"
#include "asm.h"
#include "mon_parse.h"
#include "mon_register.h"
#include "mon_util.h"
#include "monitor.h"
#include "monitor_network.h"
#include "monitor_binary.h"
#include "montypes.h"
#include "userport_io_sim.h"
#include "joyport_io_sim.h"
#include "joyport.h"
#include "resources.h"
#include "screenshot.h"
#include "sysfile.h"
#include "tape.h"
#include "traps.h"
#include "types.h"
#include "ui.h"
#include "uiapi.h"
#include "uimon.h"
#include "video.h"
#include "vsync.h"
Data Structures
struct symbol_entry
Types.
struct symbol_table
struct monitor_cpu_type_list_s
Macros
#define MAX_LABEL_LEN 255
Defines.
#define MAX_MEMSPACE_NAME_LEN 10
#define HASH_ARRAY_SIZE 256
#define HASH_ADDR(x) ((x) % 0xff)
#define OP_JSR 0x20
#define OP_RTI 0x40
#define OP_RTS 0x60
#define ADDR_LIMIT(x) (addr_mask(x))
#define BAD_ADDR (new_addr(e_invalid_space, 0))
#define MONITOR_GET_PC(mem) ((uint16_t)((monitor_cpu_for_memspace[mem]->mon_register_get_val)(mem, e_PC)))
#define MONITOR_GET_OPCODE(mem) (mon_get_mem_val_nosfx(mem, mem == e_comp_space ? mem_get_current_bank_config() : 0, MONITOR_GET_PC(mem)))
#define PLAYBACK_MAX_FP_DEPTH 128
#define TTY_COLUMNS 80
#define TTY_ROWS 25
Typedefs
typedef struct symbol_entry symbol_entry_t
typedef struct symbol_table symbol_table_t
typedef struct monitor_cpu_type_list_s monitor_cpu_type_list_t
Enumerations
enum init_break_mode_t {
NONE ,
ON_EXECUTE ,
ON_RESET ,
ON_READY
}
Functions
void set_yydebug (int debug)
Global variables.
static void playback_end_file (void)
static void monitor_close (bool check_exit)
static int monitor_set_moncommands_file (const char *param, void *extra_param)
bool monitor_is_inside_monitor (void)
static bool is_machine_ready (void)
void monitor_reset_hook (void)
void monitor_vsync_hook (void)
static int find_cpu_type_from_string (const char *cpu_string)
Some local helper functions.
static monitor_cpu_type_t * monitor_find_cpu_for_memspace (MEMSPACE mem, CPU_TYPE_t cpu)
static void monitor_print_cpu_types_supported (MEMSPACE mem)
static void set_addr_memspace (MON_ADDR *a, MEMSPACE m)
*** ADDRESS FUNCTIONS ***
bool mon_is_valid_addr (MON_ADDR a)
bool mon_inc_addr_location (MON_ADDR *a, unsigned inc)
void mon_evaluate_default_addr (MON_ADDR *a)
bool mon_is_in_range (MON_ADDR start_addr, MON_ADDR end_addr, unsigned loc)
static bool is_valid_addr_range (MON_ADDR start_addr, MON_ADDR end_addr)
static unsigned get_range_len (MON_ADDR addr1, MON_ADDR addr2)
long mon_evaluate_address_range (MON_ADDR *start_addr, MON_ADDR *end_addr, bool must_be_range, uint16_t default_len)
mon_reg_list_t * mon_register_list_get (int mem)
*** REGISTER AND MEMORY OPERATIONS ***
bool check_drive_emu_level_ok (int drive_num)
void monitor_cpu_type_set (const char *cpu_type)
void monitor_cpu_type_set_value (int searchcpu)
basically above code but faster as the type is passed; used by x128
int mon_banknum_from_bank (MEMSPACE mem, const char *bankname)
void mon_bank (MEMSPACE mem, const char *bankname)
const int mon_banknum_validate (MEMSPACE mem, int banknum)
check if the bank number is valid for memspace
const char * mon_get_bank_name_for_bank (MEMSPACE mem, int banknum)
return the literal bank name for a given bank in a given memspace
int mon_get_bank_index_for_bank (MEMSPACE mem, int banknum)
return the current bank index for a given bank in a given memspace
int mon_get_bank_flags_for_bank (MEMSPACE mem, int banknum)
return the current bank flags for a given bank in a given memspace
const char * mon_get_current_bank_name (MEMSPACE mem)
uint8_t mon_get_mem_val_ex (MEMSPACE mem, int bank, uint16_t mem_addr)
uint8_t mon_get_mem_val (MEMSPACE mem, uint16_t mem_addr)
uint8_t mon_get_mem_val_ex_nosfx (MEMSPACE mem, int bank, uint16_t mem_addr)
uint8_t mon_get_mem_val_nosfx (MEMSPACE mem, uint16_t mem_config, uint16_t mem_addr)
void mon_get_mem_block_ex (MEMSPACE mem, int bank, uint16_t start, uint16_t end, uint8_t *data)
void mon_get_mem_block (MEMSPACE mem, uint16_t start, uint16_t end, uint8_t *data)
void mon_set_mem_val (MEMSPACE mem, uint16_t mem_addr, uint8_t val)
void mon_set_mem_val_ex (MEMSPACE mem, int bank, uint16_t mem_addr, uint8_t val)
set a byte of memory in a specific bank, not the current.
void mon_jump (MON_ADDR addr)
exit monitor
void mon_go (void)
exit monitor
void mon_exit (void)
exit monitor, close monitor window
void mon_quit (void)
void mon_keyboard_feed (const char *string)
void mon_print_bin (int val, char on, char off)
*** ULTILITY FUNCTIONS ***
static void print_hex (int val)
static void print_octal (int val)
void mon_print_convert (int val)
void mon_clear_buffer (void)
Function declarations.
void mon_add_number_to_buffer (int number)
void mon_add_number_masked_to_buffer (int number, int mask)
void mon_add_string_to_buffer (char *str)
static monitor_cpu_type_list_t * monitor_list_new (void)
static void montor_list_destroy (monitor_cpu_type_list_t *list)
unsigned mon_disassemble_oneline (MEMSPACE memspace, uint16_t mem_config, uint16_t addr)
void mon_backtrace (void)
void mon_screenshot_save (const char *filename, int format)
void mon_show_pwd (void)
Display current working directory.
void mon_show_dir (const char *path)
void mon_resource_get (const char *name)
void mon_resource_set (const char *name, const char *value)
void mon_reset_machine (int type)
void mon_tape_ctrl (int port, int command)
void mon_tape_offs (int port, int offset)
void mon_cart_freeze (void)
IO_SIM_RESULT mon_userport_set_output (int value)
IO_SIM_RESULT mon_joyport_set_output (int port, int value)
void mon_export (void)
void mon_stopwatch_show (const char *prefix, const char *suffix)
void mon_stopwatch_reset (void)
static monitor_cpu_type_t * find_monitor_cpu_type (CPU_TYPE_t cputype)
Local helper functions for building the lists.
static void add_monitor_cpu_type_supported (supported_cpu_type_list_t **list_ptr, monitor_cpu_type_t *mon_cpu_type)
static void find_supported_monitor_cpu_types (supported_cpu_type_list_t **list_ptr, monitor_interface_t *mon_interface)
monitor_cpu_type_t * monitor_find_cpu_type_from_string (const char *cpu_type)
*** MISC COMMANDS ***
void monitor_init (monitor_interface_t *maincpu_interface_init, monitor_interface_t *drive_interface_init[], monitor_cpu_type_t **asmarray)
void monitor_shutdown (void)
static int monitor_set_initial_breakpoint (const char *param, void *extra_param)
static int set_keep_monitor_open (int val, void *param)
static int set_refresh_on_break (int val, void *param)
static int set_monitor_log_filename (const char *val, void *param)
static int set_monitor_log_enabled (int val, void *param)
static int set_monitor_scrollback_lines (int val, void *param)
int monitor_resources_init (void)
void monitor_resources_shutdown (void)
int monitor_cmdline_options_init (void)
monitor_interface_t * monitor_interface_new (void)
void monitor_interface_destroy (monitor_interface_t *monitor_interface)
void mon_start_assemble_mode (MON_ADDR addr, char *asm_line)
void mon_display_screen (long addr)
Memory.
void mon_display_io_regs (MON_ADDR addr)
void mon_ioreg_add_list (mem_ioreg_list_t **list, const char *name, int start_, int end_, void *dump, void *context, int mirror_mode)
void mon_change_dir (const char *path)
*** FILE COMMANDS ***
void mon_make_dir (const char *path)
void mon_remove_dir (const char *path)
void mon_save_symbols (MEMSPACE mem, const char *filename)
void mon_record_commands (char *filename)
*** COMMAND FILES ***
void mon_end_recording (void)
int mon_playback_commands (const char *filename, bool interrupt_current_playback)
static void playback_next_command (void)
static void free_symbol_table (MEMSPACE mem)
*** SYMBOL TABLE ***
char * mon_symbol_table_lookup_name (MEMSPACE mem, uint16_t addr)
int mon_symbol_table_lookup_addr (MEMSPACE mem, char *name)
look up a symbol in the given memspace, returns address or -1 on error
char * mon_prepend_dot_to_name (char *name)
void mon_add_name_to_symbol_table (MON_ADDR addr, char *name)
void mon_remove_name_from_symbol_table (MEMSPACE mem, char *name)
void mon_print_symbol_table (MEMSPACE mem)
void mon_clear_symbol_table (MEMSPACE mem)
void mon_instructions_step (int count)
*** INSTRUCTION COMMANDS ***
void mon_instructions_next (int count)
void mon_instruction_return (void)
void mon_stack_up (int count)
void mon_stack_down (int count)
void mon_print_conditional (cond_node_t *cnode)
*** CONDITIONAL EXPRESSIONS ***
int mon_evaluate_conditional (cond_node_t *cnode)
void mon_delete_conditional (cond_node_t *cnode)
int mon_write_snapshot (const char *name, int save_roms, int save_disks, int even_mode)
*** SNAPSHOTS ***
int mon_read_snapshot (const char *name, int even_mode)
void monitor_watch_push_load_addr (uint16_t addr, MEMSPACE mem)
*** WATCHPOINTS ***
void monitor_watch_push_store_addr (uint16_t addr, MEMSPACE mem)
static bool watchpoints_check_loads (MEMSPACE mem, unsigned int lastpc, unsigned int pc)
static bool watchpoints_check_stores (MEMSPACE mem, unsigned int lastpc, unsigned int pc)
void monitor_check_icount (uint16_t pc)
*** CPU INTERFACES ***
void monitor_check_icount_interrupt (void)
called by cpu core
int monitor_check_breakpoints (MEMSPACE mem, uint16_t addr)
Prototypes.
void monitor_check_watchpoints (unsigned int lastpc, unsigned int pc)
called by macro DO_INTERRUPT() in 6510(dtv)core.c
int monitor_diskspace_dnr (int mem)
int monitor_diskspace_mem (int dnr)
void monitor_change_device (MEMSPACE mem)
static void make_prompt (char *str)
void monitor_abort (void)
static void monitor_open (void)
static int monitor_process (char *cmd)
void monitor_startup (MEMSPACE mem)
static void monitor_trap (uint16_t addr, void *unused_data)
void monitor_startup_trap (void)
void mon_maincpu_trace (void)
void mon_maincpu_toggle_trace (int state)
Variables
int mon_stop_output
static enum init_break_mode_t init_break_mode = NONE
static int init_break_address = -1
console_t * console_log = NULL
monitor_cartridge_commands_t mon_cart_cmd
static char * last_cmd = NULL
int exit_mon = 0
static int mon_console_suspend_on_leaving = 1
static int mon_console_close_on_leaving = 0
int sidefx = 0
int break_on_dummy_access = 0
RADIXTYPE default_radix
MEMSPACE default_memspace = e_comp_space
static bool inside_monitor = false
static bool should_pause_on_exit_mon = false
static bool pause_on_exit_mon = false
static unsigned int instruction_count
static bool skip_jsrs
static int wait_for_return_level
const char *const _mon_space_strings []
Global variables.
static uint16_t watch_load_array [9+1][e_invalid_space]
static uint16_t watch_store_array [9+1][e_invalid_space]
static unsigned int watch_load_count [e_invalid_space]
static unsigned int watch_store_count [e_invalid_space]
static symbol_table_t monitor_labels [e_invalid_space]
static CLOCK stopwatch_start_time [e_invalid_space]
monitor_interface_t * mon_interfaces [e_invalid_space]
MON_ADDR dot_addr [e_invalid_space]
unsigned char data_buf [256]
unsigned char data_mask_buf [256]
unsigned int data_buf_len
bool asm_mode
MON_ADDR asm_mode_addr
static unsigned int next_or_step_stop
unsigned monitor_mask [e_invalid_space]
Externals.
static bool watch_load_occurred
static bool watch_store_occurred
static bool recording
static FILE * recording_fp
static char * recording_name
static char ** playback_filename_stack = NULL
static FILE ** playback_fp_stack = NULL
static FILE * playback_fp = NULL
static int playback_fp_stack_size = 0
static int playback_fp_stack_size_max = 0
static bool playback_exit_after_all_playback = false
if true, control returns to emulator after the last script completes
static int disassemble_on_entry = 0
Disassemble the current opcode on entry.
monitor_cpu_type_t * monitor_cpu_for_memspace [e_invalid_space]
We now have an array of pointers to the current monitor_cpu_type for each memspace.
supported_cpu_type_list_t * monitor_cpu_type_supported [e_invalid_space]
A linked list of supported monitor_cpu_types for each memspace.
static monitor_cpu_type_list_t * monitor_cpu_type_list = NULL
static const char *const cond_op_string []
const char *const mon_memspace_string [] = { "default", "C", "8", "9", "10", "11" }
static const char *const register_string []
CAUTION: must match order in enum t_reg_id, and contain all of its elements.
static int keep_monitor_open = 0
static int refresh_on_break = 0
static char * monitorlogfilename = NULL
static int monitorlogenabled = 0
static int monitorscrollbacklines = 0
static const resource_string_t resources_string []
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
Detailed Description
The VICE built-in monitor.
Author
Daniel Sladic sladi.nosp@m.c@ee.nosp@m.cg.to.nosp@m.ront.nosp@m.o.edu
Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Daniel Kahlin danie.nosp@m.l@ka.nosp@m.hlin..nosp@m.net
Thomas Giesel skoe@.nosp@m.dire.nosp@m.ctbox.nosp@m..com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
ADDR_LIMIT
#define ADDR_LIMIT (x) (addr_mask(x))
BAD_ADDR
#define BAD_ADDR (new_addr(e_invalid_space, 0))
HASH_ADDR
#define HASH_ADDR (x) ((x) % 0xff)
HASH_ARRAY_SIZE
#define HASH_ARRAY_SIZE 256
MAX_LABEL_LEN
#define MAX_LABEL_LEN 255
Defines.
MAX_MEMSPACE_NAME_LEN
#define MAX_MEMSPACE_NAME_LEN 10
MONITOR_GET_OPCODE
#define MONITOR_GET_OPCODE (mem) (mon_get_mem_val_nosfx(mem, mem == e_comp_space ? mem_get_current_bank_config() : 0, MONITOR_GET_PC(mem)))
MONITOR_GET_PC
#define MONITOR_GET_PC (mem) ((uint16_t)((monitor_cpu_for_memspace[mem]->mon_register_get_val)(mem, e_PC)))
OP_JSR
#define OP_JSR 0x20
OP_RTI
#define OP_RTI 0x40
OP_RTS
#define OP_RTS 0x60
PLAYBACK_MAX_FP_DEPTH
#define PLAYBACK_MAX_FP_DEPTH 128
TTY_COLUMNS
#define TTY_COLUMNS 80
TTY_ROWS
#define TTY_ROWS 25
Typedef Documentation
monitor_cpu_type_list_t
typedef struct monitor_cpu_type_list_s monitor_cpu_type_list_t
symbol_entry_t
typedef struct symbol_entry symbol_entry_t
symbol_table_t
typedef struct symbol_table symbol_table_t
Enumeration Type Documentation
init_break_mode_t
enum init_break_mode_t
Enumerator
NONE
ON_EXECUTE
ON_RESET
ON_READY
Function Documentation
add_monitor_cpu_type_supported()
static void add_monitor_cpu_type_supported (supported_cpu_type_list_t ** list_ptr, monitor_cpu_type_t * mon_cpu_type) static
Referenced by find_supported_monitor_cpu_types().
check_drive_emu_level_ok()
bool check_drive_emu_level_ok (int drive_num)
Referenced by mon_get_mem_val_ex(), mon_get_mem_val_ex_nosfx(), mon_get_mem_val_nosfx(), mon_register_get_val(), mon_register_print(), mon_register_print_ex(), mon_register_set_val(), mon_register_valid(), mon_set_mem_val(), and mon_set_mem_val_ex().
find_cpu_type_from_string()
static int find_cpu_type_from_string (const char * cpu_string) static
Some local helper functions.
Referenced by monitor_cpu_type_set(), and monitor_find_cpu_type_from_string().
find_monitor_cpu_type()
static monitor_cpu_type_t * find_monitor_cpu_type (CPU_TYPE_t cputype) static
Local helper functions for building the lists.
Referenced by find_supported_monitor_cpu_types(), and monitor_find_cpu_type_from_string().
find_supported_monitor_cpu_types()
static void find_supported_monitor_cpu_types (supported_cpu_type_list_t ** list_ptr, monitor_interface_t * mon_interface) static
Referenced by monitor_init(), and monitor_open().
free_symbol_table()
static void free_symbol_table (MEMSPACE mem) static
*** SYMBOL TABLE ***
Referenced by mon_clear_symbol_table(), and mon_remove_name_from_symbol_table().
get_range_len()
static unsigned get_range_len (MON_ADDR addr1, MON_ADDR addr2) static
Referenced by mon_evaluate_address_range().
is_machine_ready()
static bool is_machine_ready (void) static
Referenced by monitor_vsync_hook().
is_valid_addr_range()
static bool is_valid_addr_range (MON_ADDR start_addr, MON_ADDR end_addr) static
Referenced by mon_evaluate_address_range().
make_prompt()
static void make_prompt (char * str) static
Referenced by monitor_startup().
mon_add_name_to_symbol_table()
void mon_add_name_to_symbol_table (MON_ADDR addr, char * name)
mon_add_number_masked_to_buffer()
void mon_add_number_masked_to_buffer (int number, int mask)
mon_add_number_to_buffer()
void mon_add_number_to_buffer (int number)
mon_add_string_to_buffer()
void mon_add_string_to_buffer (char * str)
mon_backtrace()
void mon_backtrace (void)
mon_bank()
void mon_bank (MEMSPACE mem, const char * bankname)
< part of a bank group, eg "ram00, ram01 ..."
< first in a bank group, eg "ram00"
< last in a bank group, eg "ramff"
mon_banknum_from_bank()
int mon_banknum_from_bank (MEMSPACE mem, const char * bankname)
mon_banknum_validate()
const int mon_banknum_validate (MEMSPACE mem, int banknum)
check if the bank number is valid for memspace
Parameters
mem The memspace of the bank
banknum The number of the bank
Returns
-1: Memspace doesn't have banks 0: Bank number invalid 1: Bank number valid
Referenced by monitor_binary_process_mem_get(), and monitor_binary_process_mem_set().
mon_cart_freeze()
void mon_cart_freeze (void)
mon_change_dir()
void mon_change_dir (const char * path)
*** FILE COMMANDS ***
mon_clear_buffer()
void mon_clear_buffer (void)
Function declarations.
Referenced by mon_memory_fill(), and mon_memory_hunt().
mon_clear_symbol_table()
void mon_clear_symbol_table (MEMSPACE mem)
mon_delete_conditional()
void mon_delete_conditional (cond_node_t * cnode)
Referenced by mon_delete_conditional(), and remove_checkpoint().
mon_disassemble_oneline()
unsigned mon_disassemble_oneline (MEMSPACE memspace, uint16_t mem_config, uint16_t addr)
Referenced by mon_backtrace(), and print_disass_context().
mon_display_io_regs()
void mon_display_io_regs (MON_ADDR addr)
< registered area contains mirrors of another registered area
mon_display_screen()
void mon_display_screen (long addr)
Memory.
Display screen memory
Display (current) screen memory, converting PETSCII to ASCII.
The lex/yuck stuff will pass in either -1 when no arg has been given or an address.
Parameters
[in] address address of screen memory, -1 to show current screen
Note
Currently doesn't show the addresses in the SDL monitor, since the SDL monitor is only 40 columns
Todo:
FIXME: this should really be handled by the UI instead, ie the UI should always just give us valid numbers
mon_end_recording()
void mon_end_recording (void)
mon_evaluate_address_range()
long mon_evaluate_address_range (MON_ADDR * start_addr, MON_ADDR * end_addr, bool must_be_range, uint16_t default_len)
Referenced by breakpoint_add_checkpoint(), mon_disassemble_lines(), mon_file_save(), mon_memory_compare(), mon_memory_display(), mon_memory_display_data(), mon_memory_fill(), mon_memory_hunt(), and mon_memory_move().
mon_evaluate_conditional()
int mon_evaluate_conditional (cond_node_t * cnode)
Referenced by mon_breakpoint_check_checkpoint(), and mon_evaluate_conditional().
mon_evaluate_default_addr()
void mon_evaluate_default_addr (MON_ADDR * a)
Referenced by mon_drive_block_cmd(), mon_evaluate_address_range(), mon_file_load(), mon_file_verify(), mon_jump(), mon_memory_compare(), mon_memory_move(), and mon_start_assemble_mode().
mon_exit()
void mon_exit (void)
exit monitor, close monitor window
Referenced by monitor_startup(), and playback_end_file().
mon_export()
void mon_export (void)
mon_get_bank_flags_for_bank()
int mon_get_bank_flags_for_bank (MEMSPACE mem, int banknum)
return the current bank flags for a given bank in a given memspace
Referenced by mon_bank().
mon_get_bank_index_for_bank()
int mon_get_bank_index_for_bank (MEMSPACE mem, int banknum)
return the current bank index for a given bank in a given memspace
Referenced by mon_bank().
mon_get_bank_name_for_bank()
const char * mon_get_bank_name_for_bank (MEMSPACE mem, int banknum)
return the literal bank name for a given bank in a given memspace
Referenced by mon_get_current_bank_name(), and mon_print_conditional().
mon_get_current_bank_name()
const char * mon_get_current_bank_name (MEMSPACE mem)
mon_get_mem_block()
void mon_get_mem_block (MEMSPACE mem, uint16_t start, uint16_t end, uint8_t * data)
mon_get_mem_block_ex()
void mon_get_mem_block_ex (MEMSPACE mem, int bank, uint16_t start, uint16_t end, uint8_t * data)
Referenced by mon_get_mem_block(), and monitor_binary_process_mem_get().
mon_get_mem_val()
uint8_t mon_get_mem_val (MEMSPACE mem, uint16_t mem_addr)
Referenced by mon_disassemble_with_label(), mon_drive_block_cmd(), mon_dump_with_label(), mon_file_save(), mon_file_verify(), mon_memory_compare(), mon_memory_display(), mon_memory_display_data(), mon_memory_hunt(), mon_memory_move(), mon_register_list_get6502(), mon_register_list_get6502dtv(), mon_register_list_getR65C02(), and mon_register_print().
mon_get_mem_val_ex()
uint8_t mon_get_mem_val_ex (MEMSPACE mem, int bank, uint16_t mem_addr)
Referenced by mon_evaluate_conditional(), mon_get_mem_block_ex(), and mon_get_mem_val().
mon_get_mem_val_ex_nosfx()
uint8_t mon_get_mem_val_ex_nosfx (MEMSPACE mem, int bank, uint16_t mem_addr)
Referenced by mon_disassemble_instr_bank_internal(), mon_display_screen(), and mon_get_mem_val_nosfx().
mon_get_mem_val_nosfx()
uint8_t mon_get_mem_val_nosfx (MEMSPACE mem, uint16_t mem_config, uint16_t mem_addr)
Referenced by are_aggregates_compatible(), is_branch_instruction(), mon_backtrace(), mon_disassemble_instr_memconfig_internal(), and mon_disassemble_oneline().
mon_go()
void mon_go (void)
exit monitor
mon_inc_addr_location()
bool mon_inc_addr_location (MON_ADDR * a, unsigned inc)
Referenced by mon_assemble_instr(), mon_disassemble_lines(), and mon_evaluate_address_range().
mon_instruction_return()
void mon_instruction_return (void)
Referenced by monitor_binary_process_execute_until_return().
mon_instructions_next()
void mon_instructions_next (int count)
Referenced by monitor_binary_process_advance_instructions().
mon_instructions_step()
void mon_instructions_step (int count)
*** INSTRUCTION COMMANDS ***
Referenced by monitor_binary_process_advance_instructions().
mon_ioreg_add_list()
void mon_ioreg_add_list (mem_ioreg_list_t ** list, const char * name, int start_, int end_, void * dump, void * context, int mirror_mode)
Referenced by drivemem_ioreg_list_get(), io_source_ioreg_add_onelist(), and mem_ioreg_list_get().
mon_is_in_range()
bool mon_is_in_range (MON_ADDR start_addr, MON_ADDR end_addr, unsigned loc)
Referenced by mon_breakpoint_check_checkpoint(), and search_checkpoint_list().
mon_is_valid_addr()
bool mon_is_valid_addr (MON_ADDR a)
Referenced by mon_drive_block_cmd(), mon_evaluate_address_range(), mon_file_load(), mon_file_verify(), mon_is_in_range(), mon_memory_fill(), and print_checkpoint_info().
mon_joyport_set_output()
IO_SIM_RESULT mon_joyport_set_output (int port, int value)
Referenced by monitor_binary_process_joyport_set().
mon_jump()
void mon_jump (MON_ADDR addr)
exit monitor
mon_keyboard_feed()
void mon_keyboard_feed (const char * string)
mon_maincpu_toggle_trace()
void mon_maincpu_toggle_trace (int state)
mon_maincpu_trace()
void mon_maincpu_trace (void)
Referenced by mon_maincpu_toggle_trace().
mon_make_dir()
void mon_make_dir (const char * path)
mon_playback_commands()
int mon_playback_commands (const char * filename, bool interrupt_current_playback)
< read mode (text)
< read mode (text)
Referenced by monitor_set_moncommands_file().
mon_prepend_dot_to_name()
char * mon_prepend_dot_to_name (char * name)
mon_print_bin()
void mon_print_bin (int val, char on, char off)
*** ULTILITY FUNCTIONS ***
Referenced by mon_memory_display(), mon_memory_display_data(), and mon_print_convert().
mon_print_conditional()
void mon_print_conditional (cond_node_t * cnode)
*** CONDITIONAL EXPRESSIONS ***
Referenced by mon_breakpoint_set_checkpoint_condition(), mon_print_conditional(), and print_checkpoint_info().
mon_print_convert()
void mon_print_convert (int val)
mon_print_symbol_table()
void mon_print_symbol_table (MEMSPACE mem)
mon_quit()
void mon_quit (void)
Referenced by monitor_binary_process_quit().
mon_read_snapshot()
int mon_read_snapshot (const char * name, int even_mode)
Referenced by monitor_binary_process_undump().
mon_record_commands()
void mon_record_commands (char * filename)
*** COMMAND FILES ***
< write mode (binary)
mon_register_list_get()
mon_reg_list_t * mon_register_list_get (int mem)
*** REGISTER AND MEMORY OPERATIONS ***
Register interface.
Referenced by mon_register_name_to_id(), mon_register_valid(), monitor_binary_process_registers_available(), and monitor_binary_response_register_info().
mon_remove_dir()
void mon_remove_dir (const char * path)
mon_remove_name_from_symbol_table()
void mon_remove_name_from_symbol_table (MEMSPACE mem, char * name)
Referenced by mon_add_name_to_symbol_table().
mon_reset_machine()
void mon_reset_machine (int type)
Referenced by monitor_binary_process_reset().
mon_resource_get()
void mon_resource_get (const char * name)
mon_resource_set()
void mon_resource_set (const char * name, const char * value)
mon_save_symbols()
void mon_save_symbols (MEMSPACE mem, const char * filename)
< write mode (binary)
Todo:
FIXME: Write out all memspaces?
mon_screenshot_save()
void mon_screenshot_save (const char * filename, int format)
mon_set_mem_val()
void mon_set_mem_val (MEMSPACE mem, uint16_t mem_addr, uint8_t val)
Referenced by mon_assemble_instr(), mon_drive_block_cmd(), mon_file_load(), mon_memory_fill(), and mon_memory_move().
mon_set_mem_val_ex()
void mon_set_mem_val_ex (MEMSPACE mem, int bank, uint16_t mem_addr, uint8_t val)
set a byte of memory in a specific bank, not the current.
Parameters
mem Memspace of bank
bank The bank number
mem_addr The 16 bit memory address
val The byte to write
Referenced by monitor_binary_process_mem_set().
mon_show_dir()
void mon_show_dir (const char * path)
< directory separator as a string
Referenced by mon_drive_list().
mon_show_pwd()
void mon_show_pwd (void)
Display current working directory.
mon_stack_down()
void mon_stack_down (int count)
mon_stack_up()
void mon_stack_up (int count)
mon_start_assemble_mode()
void mon_start_assemble_mode (MON_ADDR addr, char * asm_line)
mon_stopwatch_reset()
void mon_stopwatch_reset (void)
mon_stopwatch_show()
void mon_stopwatch_show (const char * prefix, const char * suffix)
Referenced by mon_disassemble_with_regdump(), and mon_register_print().
mon_symbol_table_lookup_addr()
int mon_symbol_table_lookup_addr (MEMSPACE mem, char * name)
look up a symbol in the given memspace, returns address or -1 on error
Referenced by mon_add_name_to_symbol_table(), and mon_remove_name_from_symbol_table().
mon_symbol_table_lookup_name()
char * mon_symbol_table_lookup_name (MEMSPACE mem, uint16_t addr)
Referenced by mon_add_name_to_symbol_table(), mon_disassemble_instr(), mon_disassemble_lines(), mon_disassemble_to_string_internal(), mon_disassemble_with_label(), mon_dump_with_label(), and print_dst().
mon_tape_ctrl()
void mon_tape_ctrl (int port, int command)
mon_tape_offs()
void mon_tape_offs (int port, int offset)
mon_userport_set_output()
IO_SIM_RESULT mon_userport_set_output (int value)
Referenced by monitor_binary_process_userport_set().
mon_write_snapshot()
int mon_write_snapshot (const char * name, int save_roms, int save_disks, int even_mode)
*** SNAPSHOTS ***
Referenced by monitor_binary_process_dump().
monitor_abort()
void monitor_abort (void)
Referenced by mon_out(), mon_petscii_out(), mon_petscii_upper_out(), mon_scrcode_out(), and mon_scrcode_upper_out().
monitor_change_device()
void monitor_change_device (MEMSPACE mem)
monitor_check_breakpoints()
int monitor_check_breakpoints (MEMSPACE mem, uint16_t addr)
Prototypes.
monitor_check_icount()
void monitor_check_icount (uint16_t pc)
*** CPU INTERFACES ***
called by cpu core
monitor_check_icount_interrupt()
void monitor_check_icount_interrupt (void)
called by cpu core
monitor_check_watchpoints()
void monitor_check_watchpoints (unsigned int lastpc, unsigned int pc)
called by macro DO_INTERRUPT() in 6510(dtv)core.c
monitor_close()
static void monitor_close (bool check_exit) static
Referenced by monitor_shutdown(), and monitor_startup().
monitor_cmdline_options_init()
int monitor_cmdline_options_init (void)
Referenced by init_cmdline_options().
monitor_cpu_type_set()
void monitor_cpu_type_set (const char * cpu_type)
monitor_cpu_type_set_value()
void monitor_cpu_type_set_value (int searchcpu)
basically above code but faster as the type is passed; used by x128
monitor_diskspace_dnr()
int monitor_diskspace_dnr (int mem)
Referenced by mon_get_mem_val_ex(), mon_get_mem_val_ex_nosfx(), mon_get_mem_val_nosfx(), mon_register_get_val(), mon_register_print(), mon_register_print_ex(), mon_register_set_val(), mon_register_valid(), mon_set_mem_val(), and mon_set_mem_val_ex().
monitor_diskspace_mem()
int monitor_diskspace_mem (int dnr)
Referenced by check_drive_emu_level_ok(), drivecpu65c02_setup_context(), drivecpu_setup_context(), monitor_check_watchpoints(), monitor_init(), and monitor_open().
monitor_find_cpu_for_memspace()
static monitor_cpu_type_t * monitor_find_cpu_for_memspace (MEMSPACE mem, CPU_TYPE_t cpu) static
Referenced by monitor_cpu_type_set(), and monitor_cpu_type_set_value().
monitor_find_cpu_type_from_string()
monitor_cpu_type_t * monitor_find_cpu_type_from_string (const char * cpu_type)
*** MISC COMMANDS ***
Prototypes.
Referenced by mon_disassemble_to_string().
monitor_init()
void monitor_init (monitor_interface_t * maincpu_interface_init, monitor_interface_t * drive_interface_init[], monitor_cpu_type_t ** asmarray)
Referenced by c64_monitor_init().
monitor_interface_destroy()
void monitor_interface_destroy (monitor_interface_t * monitor_interface)
Referenced by drivecpu65c02_shutdown(), and drivecpu_shutdown().
monitor_interface_new()
monitor_interface_t * monitor_interface_new (void)
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
monitor_is_inside_monitor()
bool monitor_is_inside_monitor (void)
Referenced by on_save_screenshot_filename(), screenshot_ui_auto_screenshot(), and vice_opengl_on_ui_frame_clock().
monitor_list_new()
static monitor_cpu_type_list_t * monitor_list_new (void) static
Referenced by monitor_init().
monitor_open()
static void monitor_open (void) static
Todo:
FIXME: this makes no sense at all
Referenced by monitor_startup().
monitor_print_cpu_types_supported()
static void monitor_print_cpu_types_supported (MEMSPACE mem) static
Referenced by monitor_cpu_type_set().
monitor_process()
static int monitor_process (char * cmd) static
Referenced by monitor_startup().
monitor_reset_hook()
void monitor_reset_hook (void)
Referenced by machine_reset().
monitor_resources_init()
int monitor_resources_init (void)
Referenced by init_resources().
monitor_resources_shutdown()
void monitor_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
monitor_set_initial_breakpoint()
static int monitor_set_initial_breakpoint (const char * param, void * extra_param) static
monitor_set_moncommands_file()
static int monitor_set_moncommands_file (const char * param, void * extra_param) static
monitor_shutdown()
void monitor_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
monitor_startup()
void monitor_startup (MEMSPACE mem)
Referenced by drivecpu_jam(), monitor_check_icount(), monitor_check_watchpoints(), and monitor_trap().
monitor_startup_trap()
void monitor_startup_trap (void)
Referenced by load_snapshot_trap(), monitor_check_binary(), monitor_check_remote(), monitor_open_action(), monitor_reset_hook(), monitor_vsync_hook(), and ui_pause_loop_iteration().
monitor_trap()
static void monitor_trap (uint16_t addr, void * unused_data) static
Referenced by monitor_startup_trap().
monitor_vsync_hook()
void monitor_vsync_hook (void)
Referenced by vsync_do_vsync().
monitor_watch_push_load_addr()
void monitor_watch_push_load_addr (uint16_t addr, MEMSPACE mem)
*** WATCHPOINTS ***
Referenced by drive_read_watch(), drive_zero_read_watch(), read_watch(), and zero_read_watch().
monitor_watch_push_store_addr()
void monitor_watch_push_store_addr (uint16_t addr, MEMSPACE mem)
Referenced by drive_store_watch(), drive_zero_store_watch(), store_watch(), and zero_store_watch().
montor_list_destroy()
static void montor_list_destroy (monitor_cpu_type_list_t * list) static
Referenced by monitor_shutdown().
playback_end_file()
static void playback_end_file (void) static
Referenced by monitor_shutdown(), and playback_next_command().
playback_next_command()
static void playback_next_command (void) static
Referenced by monitor_startup(), and playback_next_command().
print_hex()
static void print_hex (int val) static
Referenced by mon_print_convert().
print_octal()
static void print_octal (int val) static
Referenced by mon_print_convert().
set_addr_memspace()
static void set_addr_memspace (MON_ADDR * a, MEMSPACE m) static
*** ADDRESS FUNCTIONS ***
Referenced by mon_evaluate_address_range(), and mon_evaluate_default_addr().
set_keep_monitor_open()
static int set_keep_monitor_open (int val, void * param) static
set_monitor_log_enabled()
static int set_monitor_log_enabled (int val, void * param) static
set_monitor_log_filename()
static int set_monitor_log_filename (const char * val, void * param) static
set_monitor_scrollback_lines()
static int set_monitor_scrollback_lines (int val, void * param) static
set_refresh_on_break()
static int set_refresh_on_break (int val, void * param) static
set_yydebug()
void set_yydebug (int debug)
Global variables.
Defined in file generated by bison.
Referenced by monitor_init().
watchpoints_check_loads()
static bool watchpoints_check_loads (MEMSPACE mem, unsigned int lastpc, unsigned int pc) static
Referenced by monitor_check_watchpoints().
watchpoints_check_stores()
static bool watchpoints_check_stores (MEMSPACE mem, unsigned int lastpc, unsigned int pc) static
Referenced by monitor_check_watchpoints().
Variable Documentation
_mon_space_strings
const char* const _mon_space_strings[]
Initial value:
= {
    "Default", "Computer", "Disk8", "Disk9", "Disk10", "Disk11", "<<Invalid>>"
}
Global variables.
Referenced by monitor_change_device(), and monitor_cpu_type_set().
asm_mode
bool asm_mode
Referenced by make_prompt(), mon_start_assemble_mode(), monitor_init(), and monitor_process().
asm_mode_addr
MON_ADDR asm_mode_addr
Referenced by make_prompt(), mon_assemble_instr(), mon_start_assemble_mode(), and monitor_init().
break_on_dummy_access
int break_on_dummy_access = 0
Referenced by mon_breakpoint_set_dummy_state(), and update_checkpoint_state().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-moncommands", CALL_FUNCTION,  (1 << 0) ,
      monitor_set_moncommands_file, NULL, NULL, NULL,
      "<Name>", "Execute monitor commands from file" },
    { "-monlogname", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "MonitorLogFileName", NULL,
      "<Name>", "Set name of monitor log file" },
    { "-monlog", SET_RESOURCE,  0 ,
      NULL, NULL, "MonitorLogEnabled", (resource_value_t)1,
      NULL, "Enable logging monitor output to a file" },
    { "+monlog", SET_RESOURCE,  0 ,
      NULL, NULL, "MonitorLogEnabled", (resource_value_t)0,
      NULL, "Disable logging monitor output to a file" },
    { "-initbreak", CALL_FUNCTION,  (1 << 0) ,
      monitor_set_initial_breakpoint, NULL, NULL, NULL,
      "<value>", "Set an initial breakpoint for the monitor: <address>, ready, or reset" },
    { "-keepmonopen", SET_RESOURCE,  0 ,
      NULL, NULL, "KeepMonitorOpen", (resource_value_t)1,
      NULL, "Keep the monitor open" },
    { "+keepmonopen", SET_RESOURCE,  0 ,
      NULL, NULL, "KeepMonitorOpen", (resource_value_t)0,
      NULL, "Do not keep the monitor open" },
    { "-refreshonbreak", SET_RESOURCE,  0 ,
      NULL, NULL, "RefreshOnBreak", (resource_value_t)1,
      NULL, "Refresh display after monitor command" },
    { "+refreshonbreak", SET_RESOURCE,  0 ,
      NULL, NULL, "RefreshOnBreak", (resource_value_t)0,
      NULL, "Do not refresh display after monitor command" },
    { "-monscrollbacklines", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "MonitorScrollbackLines", NULL,
      "<value>", "Set number of lines to keep in the monitor scrollback buffer" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by monitor_cmdline_options_init().
cond_op_string
const char* const cond_op_string[] static
Initial value:
= {
    "",
    "==",
    "!=",
    ">",
    "<",
    ">=",
    "<=",
    "&&",
    "||",
    "+",
    "-",
    "*",
    "/",
    "&",
    "|"
}
Referenced by mon_print_conditional().
console_log
console_t* console_log = NULL
Referenced by mon_disassemble_lines(), mon_display_screen(), mon_memory_display(), mon_out_buffered(), mon_out_wordwrap(), monitor_close(), monitor_open(), and print_help_topics().
data_buf
unsigned char data_buf[256]
Referenced by mon_add_number_masked_to_buffer(), mon_add_number_to_buffer(), mon_add_string_to_buffer(), mon_memory_fill(), and mon_memory_hunt().
data_buf_len
unsigned int data_buf_len
Referenced by mon_add_number_masked_to_buffer(), mon_add_number_to_buffer(), mon_add_string_to_buffer(), mon_clear_buffer(), mon_memory_fill(), mon_memory_hunt(), and monitor_init().
data_mask_buf
unsigned char data_mask_buf[256]
Referenced by mon_add_number_masked_to_buffer(), mon_add_number_to_buffer(), mon_add_string_to_buffer(), and mon_memory_hunt().
default_memspace
MEMSPACE default_memspace = e_comp_space
Referenced by make_prompt(), mon_add_name_to_symbol_table(), mon_backtrace(), mon_bank(), mon_banknum_from_bank(), mon_breakpoint_set_dummy_state(), mon_clear_symbol_table(), mon_display_io_regs(), mon_evaluate_address_range(), mon_evaluate_default_addr(), mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), mon_print_conditional(), mon_print_symbol_table(), mon_remove_name_from_symbol_table(), mon_save_symbols(), mon_stopwatch_reset(), mon_stopwatch_show(), mon_symbol_table_lookup_addr(), mon_symbol_table_lookup_name(), monitor_change_device(), monitor_check_icount(), monitor_cpu_type_set(), monitor_cpu_type_set_value(), monitor_find_cpu_for_memspace(), monitor_init(), monitor_open(), monitor_startup(), and print_dst().
default_radix
RADIXTYPE default_radix
Referenced by monitor_init().
disassemble_on_entry
int disassemble_on_entry = 0 static
Disassemble the current opcode on entry.
Used for single step.
Referenced by monitor_check_icount(), and monitor_open().
dot_addr
MON_ADDR dot_addr[e_invalid_space]
Referenced by make_prompt(), mon_assemble_instr(), mon_disassemble_lines(), mon_evaluate_address_range(), mon_memory_display(), mon_memory_display_data(), mon_read_snapshot(), monitor_binary_process_undump(), monitor_init(), and monitor_open().
exit_mon
int exit_mon = 0
Referenced by breakpoint_add_checkpoint(), mon_autostart(), mon_exit(), mon_go(), mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), mon_jump(), mon_quit(), mon_reset_machine(), monitor_binary_get_command_line(), monitor_binary_process_exit(), monitor_close(), monitor_init(), monitor_open(), monitor_process(), and monitor_startup().
init_break_address
int init_break_address = -1 static
Referenced by monitor_init(), and monitor_set_initial_breakpoint().
init_break_mode
enum init_break_mode_t init_break_mode = NONE static
Referenced by monitor_init(), monitor_reset_hook(), monitor_set_initial_breakpoint(), monitor_set_moncommands_file(), and monitor_vsync_hook().
inside_monitor
bool inside_monitor = false static
Referenced by monitor_close(), monitor_is_inside_monitor(), monitor_open(), monitor_shutdown(), monitor_startup(), monitor_startup_trap(), monitor_watch_push_load_addr(), and monitor_watch_push_store_addr().
instruction_count
unsigned int instruction_count static
Referenced by mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), monitor_check_icount(), monitor_check_icount_interrupt(), and monitor_init().
keep_monitor_open
int keep_monitor_open = 0 static
Referenced by monitor_close(), and set_keep_monitor_open().
last_cmd
char* last_cmd = NULL static
Referenced by monitor_process(), and monitor_shutdown().
mon_cart_cmd
monitor_cartridge_commands_t mon_cart_cmd
Referenced by mon_attach(), mon_cart_freeze(), mon_detach(), mon_export(), and monitor_cmdline_options_init().
mon_console_close_on_leaving
int mon_console_close_on_leaving = 0 static
Referenced by mon_exit(), monitor_close(), and monitor_open().
mon_console_suspend_on_leaving
int mon_console_suspend_on_leaving = 1 static
Referenced by mon_instructions_next(), mon_instructions_step(), monitor_close(), monitor_open(), and monitor_process().
mon_interfaces
monitor_interface_t* mon_interfaces[e_invalid_space]
Referenced by check_drive_emu_level_ok(), mon_bank(), mon_banknum_from_bank(), mon_banknum_validate(), mon_breakpoint_check_checkpoint(), mon_disassemble_instr_bank_internal(), mon_display_io_regs(), mon_display_screen(), mon_evaluate_conditional(), mon_get_bank_flags_for_bank(), mon_get_bank_index_for_bank(), mon_get_bank_name_for_bank(), mon_get_current_bank_name(), mon_get_mem_block(), mon_get_mem_val(), mon_get_mem_val_ex(), mon_get_mem_val_ex_nosfx(), mon_get_mem_val_nosfx(), mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), mon_register_get_val(), mon_register_list_get6502(), mon_register_list_get6502dtv(), mon_register_print(), mon_register_print_ex(), mon_register_set_val(), mon_set_mem_val(), mon_set_mem_val_ex(), mon_stopwatch_reset(), mon_stopwatch_show(), monitor_binary_process_banks_available(), monitor_check_icount(), monitor_init(), monitor_open(), and update_checkpoint_state().
mon_memspace_string
const char* const mon_memspace_string[] = { "default", "C", "8", "9", "10", "11" }
Referenced by make_prompt(), mon_disassemble_instr(), mon_disassemble_instr_bank_internal(), mon_disassemble_instr_memconfig_internal(), mon_disassemble_oneline(), mon_memory_display(), mon_memory_display_data(), mon_save_symbols(), and print_checkpoint_info().
mon_stop_output
int mon_stop_output
Referenced by mon_disassemble_lines(), mon_memory_display(), mon_memory_display_data(), monitor_abort(), monitor_process(), and print_help_topics().
monitor_cpu_for_memspace
monitor_cpu_type_t* monitor_cpu_for_memspace[e_invalid_space]
We now have an array of pointers to the current monitor_cpu_type for each memspace.
This gets initialized in monitor_init().
Referenced by mon_assemble_instr(), mon_backtrace(), mon_breakpoint_check_checkpoint(), mon_disassemble_instr_bank_internal(), mon_disassemble_instr_memconfig_internal(), mon_disassemble_to_string_ex(), mon_disassemble_to_string_internal(), mon_disassemble_with_regdump(), mon_evaluate_conditional(), mon_jump(), mon_read_snapshot(), mon_register_id_to_value(), mon_register_list_get(), monitor_binary_process_registers_set(), monitor_binary_process_undump(), monitor_binary_response_resumed(), monitor_binary_response_stopped(), monitor_binary_ui_jam_dialog(), monitor_cpu_type_set(), monitor_cpu_type_set_value(), monitor_init(), and monitor_open().
monitor_cpu_type_list
monitor_cpu_type_list_t* monitor_cpu_type_list = NULL static
Referenced by find_monitor_cpu_type(), monitor_init(), and monitor_shutdown().
monitor_cpu_type_supported
supported_cpu_type_list_t* monitor_cpu_type_supported[e_invalid_space]
A linked list of supported monitor_cpu_types for each memspace.
Referenced by mon_breakpoint_check_checkpoint(), monitor_find_cpu_for_memspace(), monitor_init(), monitor_open(), monitor_print_cpu_types_supported(), and monitor_shutdown().
monitor_labels
symbol_table_t monitor_labels[e_invalid_space] static
Referenced by free_symbol_table(), mon_add_name_to_symbol_table(), mon_clear_symbol_table(), mon_print_symbol_table(), mon_remove_name_from_symbol_table(), mon_save_symbols(), mon_symbol_table_lookup_addr(), mon_symbol_table_lookup_name(), and monitor_init().
monitor_mask
unsigned monitor_mask[e_invalid_space]
Externals.
Referenced by mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), monitor_check_icount(), monitor_init(), and update_checkpoint_state().
monitorlogenabled
int monitorlogenabled = 0 static
Referenced by set_monitor_log_enabled(), and set_monitor_log_filename().
monitorlogfilename
char* monitorlogfilename = NULL static
Referenced by monitor_resources_shutdown(), set_monitor_log_enabled(), and set_monitor_log_filename().
monitorscrollbacklines
int monitorscrollbacklines = 0 static
Referenced by set_monitor_scrollback_lines().
next_or_step_stop
unsigned int next_or_step_stop static
Referenced by monitor_init().
pause_on_exit_mon
bool pause_on_exit_mon = false static
Referenced by mon_exit(), mon_go(), and monitor_startup().
playback_exit_after_all_playback
bool playback_exit_after_all_playback = false static
if true, control returns to emulator after the last script completes
Referenced by monitor_set_moncommands_file(), and playback_end_file().
playback_filename_stack
char** playback_filename_stack = NULL static
Referenced by mon_playback_commands(), monitor_shutdown(), and playback_end_file().
playback_fp
FILE* playback_fp = NULL static
Referenced by mon_add_name_to_symbol_table(), mon_playback_commands(), monitor_open(), monitor_startup(), playback_end_file(), and playback_next_command().
playback_fp_stack
FILE** playback_fp_stack = NULL static
Referenced by mon_playback_commands(), monitor_shutdown(), and playback_end_file().
playback_fp_stack_size
int playback_fp_stack_size = 0 static
Referenced by mon_playback_commands(), monitor_shutdown(), and playback_end_file().
playback_fp_stack_size_max
int playback_fp_stack_size_max = 0 static
Referenced by mon_playback_commands(), and monitor_shutdown().
recording
bool recording static
Referenced by reSID::SID::debugoutput(), mon_end_recording(), mon_record_commands(), monitor_init(), monitor_process(), and ui_statusbar_create().
recording_fp
FILE* recording_fp static
Referenced by mon_end_recording(), mon_record_commands(), and monitor_process().
recording_name
char* recording_name static
Referenced by mon_end_recording(), and mon_record_commands().
refresh_on_break
int refresh_on_break = 0 static
Referenced by monitor_startup(), and set_refresh_on_break().
register_string
const char* const register_string[] static
Initial value:
= {
    "A",
    "X",
    "Y",
    "PC",
    "SP",
    "FL",
    "AF",
    "BC",
    "DE",
    "HL",
    "IX",
    "IY",
    "I",
    "R",
    "AF2",
    "BC2",
    "DE2",
    "HL2",
    "R3",
    "R4",
    "R5",
    "R6",
    "R7",
    "R8",
    "R9",
    "R10",
    "R11",
    "R12",
    "R13",
    "R14",
    "R15",
    "ACM",
    "YXM",
    "B",
    "C",
    "DPR",
    "PBR",
    "DBR",
    "D",
    "U",
    "DP",
    "E",
    "F",
    "W",
    "Q",
    "V",
    "MD",
    "H",
    "L",
    "IXL",
    "IXH",
    "IYL",
    "IYH",
    "RL",
    "CY",
    "P00",
    "P01"
}
CAUTION: must match order in enum t_reg_id, and contain all of its elements.
Referenced by mon_print_conditional().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "KeepMonitorOpen", 1, RES_EVENT_NO, NULL,
      &keep_monitor_open, set_keep_monitor_open, NULL },
    { "RefreshOnBreak", 1, RES_EVENT_NO, NULL,
      &refresh_on_break, set_refresh_on_break, NULL },
    { "MonitorLogEnabled", 0, RES_EVENT_NO, NULL,
      &monitorlogenabled, set_monitor_log_enabled, NULL },
    { "MonitorScrollbackLines", 8192, RES_EVENT_NO, NULL,
      &monitorscrollbacklines, set_monitor_scrollback_lines, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by monitor_resources_init().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "MonitorLogFileName", "monitor.log", RES_EVENT_NO, NULL,
      &monitorlogfilename, set_monitor_log_filename, (void *)0 },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by monitor_resources_init().
should_pause_on_exit_mon
bool should_pause_on_exit_mon = false static
Referenced by mon_exit(), mon_go(), and monitor_startup().
sidefx
int sidefx = 0
Referenced by mon_evaluate_conditional(), mon_get_mem_val_ex(), mon_register_list_get6502(), mon_register_print(), mon_set_mem_val(), mon_set_mem_val_ex(), monitor_binary_process_mem_get(), monitor_binary_process_mem_set(), and monitor_init().
skip_jsrs
bool skip_jsrs static
Referenced by mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), monitor_check_icount(), monitor_check_icount_interrupt(), and monitor_init().
stopwatch_start_time
CLOCK stopwatch_start_time[e_invalid_space] static
Referenced by mon_stopwatch_reset(), and mon_stopwatch_show().
wait_for_return_level
int wait_for_return_level static
Referenced by mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), monitor_check_icount(), monitor_check_icount_interrupt(), and monitor_init().
watch_load_array
uint16_t watch_load_array[9+1][e_invalid_space] static
Referenced by monitor_watch_push_load_addr(), and watchpoints_check_loads().
watch_load_count
unsigned int watch_load_count[e_invalid_space] static
Referenced by monitor_init(), monitor_watch_push_load_addr(), and watchpoints_check_loads().
watch_load_occurred
bool watch_load_occurred static
Referenced by monitor_check_watchpoints(), monitor_init(), and monitor_watch_push_load_addr().
watch_store_array
uint16_t watch_store_array[9+1][e_invalid_space] static
Referenced by monitor_watch_push_store_addr(), and watchpoints_check_stores().
watch_store_count
unsigned int watch_store_count[e_invalid_space] static
Referenced by monitor_init(), monitor_watch_push_store_addr(), and watchpoints_check_stores().
watch_store_occurred
bool watch_store_occurred static
Referenced by monitor_check_watchpoints(), monitor_init(), and monitor_watch_push_store_addr().