x128: drive/driveimage.c File Reference
driveimage.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "diskconstants.h"
#include "diskimage.h"
#include "drive.h"
#include "driveimage.h"
#include "drivetypes.h"
#include "gcr.h"
#include "log.h"
#include "types.h"
Functions
int drive_image_type_to_drive_type (unsigned int type)
int drive_check_image_format (unsigned int format, unsigned int dnr)
int drive_image_attach (disk_image_t *image, unsigned int unit, unsigned int drv)
Attach a disk image to the true drive emulation.
int drive_image_detach (disk_image_t *image, unsigned int unit, unsigned int drv)
Detach a disk image from the true drive emulation.
void drive_image_init (void)
Variables
static log_t driveimage_log = ((log_t)-2)
Logging goes here.
Function Documentation
drive_check_image_format()
int drive_check_image_format (unsigned int format, unsigned int dnr)
< DOS 1 dual floppy drive, 170k/disk
Todo:
FIXME: only read compat
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< D9090/D9060
< DOS 3.0 hard drive
< HD in ASCII for CMDHD
< ASCII for HD
Referenced by autostart_disk(), drive_image_attach(), and try_attach_disk().
drive_image_attach()
int drive_image_attach (disk_image_t * image, unsigned int unit, unsigned int drv)
Attach a disk image to the true drive emulation.
Referenced by attach_disk_image(), and drive_enable().
drive_image_detach()
int drive_image_detach (disk_image_t * image, unsigned int unit, unsigned int drv)
Detach a disk image from the true drive emulation.
Referenced by detach_disk_image().
drive_image_init()
void drive_image_init (void)
Referenced by drive_init().
drive_image_type_to_drive_type()
int drive_image_type_to_drive_type (unsigned int type)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< D9090/D9060
< DOS 3.0 hard drive
< HD in ASCII for CMDHD
< ASCII for HD
Referenced by autostart_disk(), and try_attach_disk().
Variable Documentation
driveimage_log
log_t driveimage_log = ((log_t)-2) static
Logging goes here.
Referenced by drive_image_attach(), drive_image_detach(), and drive_image_init().