vsid: video.h File Reference
video.h File Reference
#include "types.h"
Data Structures
struct canvas_refresh_s
struct draw_buffer_s
struct cap_render_s
struct cap_fullscreen_s
struct video_chip_cap_s
struct video_render_color_tables_s
struct video_resources_s
options for the color generator and crt emulation
struct video_render_config_s
render config for a specific canvas and video chip
struct video_cbm_color_s
struct video_cbm_palette_s
Macros
#define VIDEO_CHIP_VICII 0
video chip type
#define VIDEO_CHIP_VDC 1
#define VIDEO_FILTER_NONE 0
video filter type, resource "CHIPFilter"
#define VIDEO_FILTER_CRT 1
#define VIDEO_FILTER_SCALE2X 2
#define VIDEO_GLFILTER_NEAREST 0
video filter type, resource "CHIPGLFilter"
#define VIDEO_GLFILTER_BILINEAR 1
#define VIDEO_GLFILTER_BICUBIC 2
#define VIDEO_RENDER_NULL 0
These constants are used to configure the video output.
#define VIDEO_RENDER_PAL_NTSC_1X1 1
PAL or NTSC TV/Monitor (like VIC, VIC-II or TED)
#define VIDEO_RENDER_PAL_NTSC_2X2 2
#define VIDEO_RENDER_CRT_MONO_1X1 3
monochrome Monitor (CRTC)
#define VIDEO_RENDER_CRT_MONO_1X2 4
needed for y-stretch
#define VIDEO_RENDER_CRT_MONO_2X2 5
#define VIDEO_RENDER_CRT_MONO_2X4 6
needed for y-stretch
#define VIDEO_RENDER_RGBI_1X1 7
RGB(I) Monitor (VDC)
#define VIDEO_RENDER_RGBI_1X2 8
needed for y-stretch
#define VIDEO_RENDER_RGBI_2X2 9
#define VIDEO_RENDER_RGBI_2X4 10
needed for y-stretch
#define VIDEO_CRT_TYPE_NTSC 0
type of monitor/display that is connected
#define VIDEO_CRT_TYPE_PAL 1
#define VIDEO_CRT_TYPE_RGB 2
#define VIDEO_CRT_TYPE_MONO 3
#define VIDEO_ASPECT_MODE_NONE 0
aspect ration mode (<CHIP>AspectMode)
#define VIDEO_ASPECT_MODE_CUSTOM 1
#define VIDEO_ASPECT_MODE_TRUE 2
#define FULLSCREEN_MAXDEV 4
#define VIDEO_MAX_OUTPUT_WIDTH 2048
#define CBM_PALETTE_YUV 0
Video render interface.
#define CBM_PALETTE_RGB 1
Typedefs
typedef struct canvas_refresh_s canvas_refresh_t
typedef struct draw_buffer_s draw_buffer_t
typedef struct cap_render_s cap_render_t
typedef struct cap_fullscreen_s cap_fullscreen_t
typedef struct video_chip_cap_s video_chip_cap_t
typedef struct video_render_color_tables_s video_render_color_tables_t
typedef struct video_resources_s video_resources_t
options for the color generator and crt emulation
typedef struct video_render_config_s video_render_config_t
typedef struct video_cbm_color_s video_cbm_color_t
typedef struct video_cbm_palette_s video_cbm_palette_t
Functions
void video_render_initconfig (video_render_config_t *config)
void video_render_setphysicalcolor (video_render_config_t *config, int index, uint32_t color, int depth)
called from archdep code
void video_render_setrawrgb (video_render_color_tables_t *color_tab, unsigned int index, uint32_t r, uint32_t g, uint32_t b)
void video_render_setrawalpha (video_render_color_tables_t *color_tab, uint32_t a)
void video_render_initraw (struct video_render_config_s *videoconfig)
called by archdep code for first initial setup
int video_arch_cmdline_options_init (void)
Initialize command line options for generic video resouces.
int video_cmdline_options_init (void)
int video_init (void)
Perform any frontend-specific initialization.
void video_shutdown (void)
Perform any frontend-specific uninitialization.
struct video_canvas_s * video_canvas_create (struct video_canvas_s *canvas, unsigned int *width, unsigned int *height, int mapped)
Create a new video_canvas_s.
void video_arch_canvas_init (struct video_canvas_s *canvas)
Arch-specific initialization for a video canvas.
int video_arch_get_active_chip (void)
void video_canvas_shutdown (struct video_canvas_s *canvas)
struct video_canvas_s * video_canvas_init (void)
called from raster/raster-resources.c:raster_resources_chip_init
void video_canvas_refresh_all_tracked (void)
Force refresh all tracked canvases.
void video_canvas_refresh (struct video_canvas_s *canvas, unsigned int xs, unsigned int ys, unsigned int xi, unsigned int yi, unsigned int w, unsigned int h)
Update the display on a video canvas to reflect the machine state.
int video_canvas_set_palette (struct video_canvas_s *canvas, struct palette_s *palette)
Assign a palette to the canvas.
int video_canvas_palette_set (struct video_canvas_s *canvas, struct palette_s *palette)
This will go away.
void video_canvas_create_set (struct video_canvas_s *canvas)
void video_canvas_destroy (struct video_canvas_s *canvas)
Free a previously created video canvas and all its components.
void video_canvas_map (struct video_canvas_s *canvas)
void video_canvas_unmap (struct video_canvas_s *canvas)
void video_canvas_resize (struct video_canvas_s *canvas, char resize_canvas)
Update canvas size to match the draw buffer size requested by the emulation core.
void video_canvas_render (struct video_canvas_s *canvas, uint8_t *trg, int width, int height, int xs, int ys, int xt, int yt, int pitcht)
void video_canvas_refresh_all (struct video_canvas_s *canvas)
char video_canvas_can_resize (struct video_canvas_s *canvas)
Query whether a canvas is resizable.
void video_viewport_get (struct video_canvas_s *canvas, struct viewport_s **viewport, struct geometry_s **geometry)
void video_viewport_resize (struct video_canvas_s *canvas, char resize_canvas)
int video_resources_init (void)
global resources.
void video_resources_shutdown (void)
int video_resources_chip_init (const char *chipname, struct video_canvas_s **canvas, video_chip_cap_t *video_chip_cap)
void video_resources_chip_shutdown (struct video_canvas_s *canvas)
int video_cmdline_options_chip_init (const char *chipname, video_chip_cap_t *video_chip_cap)
int video_arch_resources_init (void)
Initialize video-related resources.
void video_arch_resources_shutdown (void)
Clean up any memory held by arch-specific video resources.
void video_color_palette_internal (struct video_canvas_s *canvas, struct video_cbm_palette_s *cbm_palette)
int video_color_update_palette (struct video_canvas_s *canvas)
Calculate or load a palette, depending on configuration.
void video_color_palette_free (struct palette_s *palette)
Macro Definition Documentation
CBM_PALETTE_RGB
#define CBM_PALETTE_RGB 1
CBM_PALETTE_YUV
#define CBM_PALETTE_YUV 0
Video render interface.
Videochip related color/palette types
FULLSCREEN_MAXDEV
#define FULLSCREEN_MAXDEV 4
Todo:
FIXME: get rid of this
VIDEO_ASPECT_MODE_CUSTOM
#define VIDEO_ASPECT_MODE_CUSTOM 1
VIDEO_ASPECT_MODE_NONE
#define VIDEO_ASPECT_MODE_NONE 0
aspect ration mode (<CHIP>AspectMode)
VIDEO_ASPECT_MODE_TRUE
#define VIDEO_ASPECT_MODE_TRUE 2
VIDEO_CHIP_VDC
#define VIDEO_CHIP_VDC 1
VIDEO_CHIP_VICII
#define VIDEO_CHIP_VICII 0
video chip type
VIDEO_CRT_TYPE_MONO
#define VIDEO_CRT_TYPE_MONO 3
VIDEO_CRT_TYPE_NTSC
#define VIDEO_CRT_TYPE_NTSC 0
type of monitor/display that is connected
VIDEO_CRT_TYPE_PAL
#define VIDEO_CRT_TYPE_PAL 1
VIDEO_CRT_TYPE_RGB
#define VIDEO_CRT_TYPE_RGB 2
VIDEO_FILTER_CRT
#define VIDEO_FILTER_CRT 1
VIDEO_FILTER_NONE
#define VIDEO_FILTER_NONE 0
video filter type, resource "CHIPFilter"
VIDEO_FILTER_SCALE2X
#define VIDEO_FILTER_SCALE2X 2
VIDEO_GLFILTER_BICUBIC
#define VIDEO_GLFILTER_BICUBIC 2
VIDEO_GLFILTER_BILINEAR
#define VIDEO_GLFILTER_BILINEAR 1
VIDEO_GLFILTER_NEAREST
#define VIDEO_GLFILTER_NEAREST 0
video filter type, resource "CHIPGLFilter"
VIDEO_MAX_OUTPUT_WIDTH
#define VIDEO_MAX_OUTPUT_WIDTH 2048
VIDEO_RENDER_CRT_MONO_1X1
#define VIDEO_RENDER_CRT_MONO_1X1 3
monochrome Monitor (CRTC)
VIDEO_RENDER_CRT_MONO_1X2
#define VIDEO_RENDER_CRT_MONO_1X2 4
needed for y-stretch
VIDEO_RENDER_CRT_MONO_2X2
#define VIDEO_RENDER_CRT_MONO_2X2 5
VIDEO_RENDER_CRT_MONO_2X4
#define VIDEO_RENDER_CRT_MONO_2X4 6
needed for y-stretch
VIDEO_RENDER_NULL
#define VIDEO_RENDER_NULL 0
These constants are used to configure the video output.
no video output (dummy)
VIDEO_RENDER_PAL_NTSC_1X1
#define VIDEO_RENDER_PAL_NTSC_1X1 1
PAL or NTSC TV/Monitor (like VIC, VIC-II or TED)
VIDEO_RENDER_PAL_NTSC_2X2
#define VIDEO_RENDER_PAL_NTSC_2X2 2
VIDEO_RENDER_RGBI_1X1
#define VIDEO_RENDER_RGBI_1X1 7
RGB(I) Monitor (VDC)
VIDEO_RENDER_RGBI_1X2
#define VIDEO_RENDER_RGBI_1X2 8
needed for y-stretch
VIDEO_RENDER_RGBI_2X2
#define VIDEO_RENDER_RGBI_2X2 9
VIDEO_RENDER_RGBI_2X4
#define VIDEO_RENDER_RGBI_2X4 10
needed for y-stretch
Typedef Documentation
canvas_refresh_t
typedef struct canvas_refresh_s canvas_refresh_t
cap_fullscreen_t
typedef struct cap_fullscreen_s cap_fullscreen_t
cap_render_t
typedef struct cap_render_s cap_render_t
draw_buffer_t
typedef struct draw_buffer_s draw_buffer_t
video_cbm_color_t
typedef struct video_cbm_color_s video_cbm_color_t
video_cbm_palette_t
typedef struct video_cbm_palette_s video_cbm_palette_t
video_chip_cap_t
typedef struct video_chip_cap_s video_chip_cap_t
video_render_color_tables_t
typedef struct video_render_color_tables_s video_render_color_tables_t
video_render_config_t
typedef struct video_render_config_s video_render_config_t
video_resources_t
typedef struct video_resources_s video_resources_t
options for the color generator and crt emulation
Function Documentation
video_arch_canvas_init()
void video_arch_canvas_init (struct video_canvas_s * canvas)
Arch-specific initialization for a video canvas.
Parameters
[in,out] canvas The canvas being initialized
See also
video_canvas_create
Referenced by video_canvas_init().
video_arch_cmdline_options_init()
int video_arch_cmdline_options_init (void)
Initialize command line options for generic video resouces.
Returns
0 on success, < 0 on failure
Referenced by video_cmdline_options_init().
video_arch_get_active_chip()
int video_arch_get_active_chip (void)
video_arch_resources_init()
int video_arch_resources_init (void)
Initialize video-related resources.
Returns
0 on success, < on failure
Referenced by video_resources_init().
video_arch_resources_shutdown()
void video_arch_resources_shutdown (void)
Clean up any memory held by arch-specific video resources.
Referenced by video_resources_shutdown().
video_canvas_can_resize()
char video_canvas_can_resize (video_canvas_t * canvas)
Query whether a canvas is resizable.
Parameters
canvas The canvas to query
Returns
TRUE if the canvas can be resized.
Referenced by video_viewport_resize().
video_canvas_create()
struct video_canvas_s * video_canvas_create (video_canvas_t * canvas, unsigned int * width, unsigned int * height, int mapped)
Create a new video_canvas_s.
Parameters
[in,out] canvas A freshly allocated canvas object.
[in] width Pointer to a width value. May be NULL if canvas size is not yet known.
[in] height Pointer to a height value. May be NULL if canvas size is not yet known.
mapped Unused.
Returns
The completely initialized canvas. The window that holds it will be visible in the UI at time of return.
Referenced by realize_canvas().
video_canvas_create_set()
void video_canvas_create_set (struct video_canvas_s * canvas)
Referenced by realize_canvas().
video_canvas_destroy()
void video_canvas_destroy (struct video_canvas_s * canvas)
Free a previously created video canvas and all its components.
Parameters
[in] canvas The canvas to destroy.
Referenced by raster_shutdown().
video_canvas_init()
struct video_canvas_s * video_canvas_init (void)
called from raster/raster-resources.c:raster_resources_chip_init
Referenced by raster_resources_chip_init().
video_canvas_map()
void video_canvas_map (struct video_canvas_s * canvas)
video_canvas_palette_set()
int video_canvas_palette_set (struct video_canvas_s * canvas, struct palette_s * palette)
This will go away.
Referenced by video_color_update_palette().
video_canvas_refresh()
void video_canvas_refresh (struct video_canvas_s * canvas, unsigned int xs, unsigned int ys, unsigned int xi, unsigned int yi, unsigned int w, unsigned int h)
Update the display on a video canvas to reflect the machine state.
Parameters
canvas The canvas to update.
xs A parameter to forward to video_canvas_render()
ys A parameter to forward to video_canvas_render()
xi X coordinate of the leftmost pixel to update
yi Y coordinate of the topmost pixel to update
w Width of the rectangle to update
h Height of the rectangle to update
Referenced by refresh_canvas(), and video_canvas_refresh_all().
video_canvas_refresh_all()
void video_canvas_refresh_all (struct video_canvas_s * canvas)
Referenced by raster_canvas_handle_end_of_frame(), raster_realize(), set_chip_rendermode(), set_double_scan_enabled(), video_canvas_palette_set(), video_canvas_refresh_all_tracked(), and video_viewport_resize().
video_canvas_refresh_all_tracked()
void video_canvas_refresh_all_tracked (void)
Force refresh all tracked canvases.
Added to enable visible updates each time the monitor prompts for input.
Referenced by monitor_startup().
video_canvas_render()
void video_canvas_render (struct video_canvas_s * canvas, uint8_t * trg, int width, int height, int xs, int ys, int xt, int yt, int pitcht)
Referenced by vice_opengl_refresh_rect().
video_canvas_resize()
void video_canvas_resize (struct video_canvas_s * canvas, char resize_canvas)
Update canvas size to match the draw buffer size requested by the emulation core.
Parameters
canvas The video canvas to update.
resize_canvas Ignored - the canvas will always resize.
Referenced by video_viewport_resize().
video_canvas_set_palette()
int video_canvas_set_palette (struct video_canvas_s * canvas, struct palette_s * palette)
Assign a palette to the canvas.
Parameters
canvas The canvas to update the palette
palette The new palette to assign
Returns
Zero on success, nonzero on failure
Referenced by perform_mode_change(), video_canvas_palette_set(), and video_canvas_resize().
video_canvas_shutdown()
void video_canvas_shutdown (struct video_canvas_s * canvas)
Referenced by raster_resources_chip_shutdown().
video_canvas_unmap()
void video_canvas_unmap (struct video_canvas_s * canvas)
video_cmdline_options_chip_init()
int video_cmdline_options_chip_init (const char * chipname, video_chip_cap_t * video_chip_cap)
Referenced by raster_cmdline_options_chip_init().
video_cmdline_options_init()
int video_cmdline_options_init (void)
Referenced by init_cmdline_options().
video_color_palette_free()
void video_color_palette_free (struct palette_s * palette)
Referenced by raster_shutdown(), and video_canvas_palette_set().
video_color_palette_internal()
void video_color_palette_internal (struct video_canvas_s * canvas, struct video_cbm_palette_s * cbm_palette)
Referenced by vicii_color_update_palette().
video_color_update_palette()
int video_color_update_palette (struct video_canvas_s * canvas)
Calculate or load a palette, depending on configuration.
Referenced by realize_canvas(), and video_canvas_render().
video_init()
int video_init (void)
Perform any frontend-specific initialization.
Returns
0 on success, nonzero on failure
Referenced by main_program().
video_render_initconfig()
void video_render_initconfig (video_render_config_t * config)
Referenced by video_resources_chip_init().
video_render_initraw()
void video_render_initraw (struct video_render_config_s * videoconfig)
called by archdep code for first initial setup
Referenced by vice_opengl_set_palette().
video_render_setphysicalcolor()
void video_render_setphysicalcolor (video_render_config_t * config, int index, uint32_t color, int depth)
called from archdep code
Referenced by vice_opengl_set_palette().
video_render_setrawalpha()
void video_render_setrawalpha (video_render_color_tables_t * color_tab, uint32_t a)
Referenced by vice_opengl_set_palette().
video_render_setrawrgb()
void video_render_setrawrgb (video_render_color_tables_t * color_tab, unsigned int index, uint32_t r, uint32_t g, uint32_t b)
Referenced by vice_opengl_set_palette().
video_resources_chip_init()
int video_resources_chip_init (const char * chipname, struct video_canvas_s ** canvas, video_chip_cap_t * video_chip_cap)
Todo:
perhaps we should not do this and let the user decide about cranking up brightness/saturation/contrast if needed?
Referenced by raster_resources_chip_init().
video_resources_chip_shutdown()
void video_resources_chip_shutdown (struct video_canvas_s * canvas)
Referenced by raster_resources_chip_shutdown().
video_resources_init()
int video_resources_init (void)
global resources.
Referenced by machine_video_resources_init().
video_resources_shutdown()
void video_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
video_shutdown()
void video_shutdown (void)
Perform any frontend-specific uninitialization.
Referenced by cmdline_help(), and machine_shutdown().
video_viewport_get()
void video_viewport_get (struct video_canvas_s * canvas, struct viewport_s ** viewport, struct geometry_s ** geometry)
Referenced by raster_init().
video_viewport_resize()
void video_viewport_resize (struct video_canvas_s * canvas, char resize_canvas)
Referenced by perform_mode_change(), realize_canvas(), and set_double_size_enabled().