vsid: printerdrv/printer-serial.c File Reference
printer-serial.c File Reference
#include "vice.h"
#include "interface-serial.h"
#include "printer.h"
Functions
int printer_serial_init_resources (void)
int printer_serial_init_cmdline_options (void)
void printer_serial_init (void)
int printer_serial_late_init (void)
int printer_serial_close (unsigned int unit)
void printer_serial_shutdown (void)
Function Documentation
printer_serial_close()
int printer_serial_close (unsigned int unit)
printer_serial_init()
void printer_serial_init (void)
Referenced by machine_printer_init().
printer_serial_init_cmdline_options()
int printer_serial_init_cmdline_options (void)
Referenced by machine_printer_cmdline_options_init().
printer_serial_init_resources()
int printer_serial_init_resources (void)
Referenced by machine_printer_resources_init().
printer_serial_late_init()
int printer_serial_late_init (void)
Referenced by serial_init().
printer_serial_shutdown()
void printer_serial_shutdown (void)
Referenced by machine_printer_shutdown().