x128: c128/c128model.c File Reference
c128model.c File Reference
#include "vice.h"
#include "c128-resources.h"
#include "c128model.h"
#include "cia.h"
#include "drive.h"
#include "machine.h"
#include "resources.h"
#include "sid.h"
#include "types.h"
#include "vicii.h"
#include "vdc.h"
#include "vdctypes.h"
Data Structures
struct model_s
Macros
#define CIA_MODEL_DEFAULT_OLD CIA_MODEL_6526
#define CIA_MODEL_DEFAULT_NEW CIA_MODEL_6526A
Functions
static int is_new_sid (int model)
static int is_new_cia (int model)
static int c128model_get_temp (int video, int sid_model, int vdc_revision, int vdc_64k, int cia1model, int cia2model, int board, int drive)
int c128model_get (void)
void c128model_set (int model)
Variables
static const struct model_s c128models []
Macro Definition Documentation
CIA_MODEL_DEFAULT_NEW
#define CIA_MODEL_DEFAULT_NEW CIA_MODEL_6526A
CIA_MODEL_DEFAULT_OLD
#define CIA_MODEL_DEFAULT_OLD CIA_MODEL_6526
Function Documentation
c128model_get()
int c128model_get (void)
Referenced by c128model_set().
c128model_get_temp()
static int c128model_get_temp (int video, int sid_model, int vdc_revision, int vdc_64k, int cia1model, int cia2model, int board, int drive) static
Referenced by c128model_get().
c128model_set()
void c128model_set (int model)
Referenced by set_c128_model().
is_new_cia()
static int is_new_cia (int model) static
< "old"
< "new"
Referenced by c128model_get_temp().
is_new_sid()
static int is_new_sid (int model) static
Referenced by c128model_get_temp(), and c128model_set().
Variable Documentation
c128models
const struct model_s c128models[] static
Initial value:
= {
    {  1 ,   0 ,  0 ,  1  ,  0 ,  0 ,   0  },
    {  1 ,   0 ,  0 ,  1  ,  0 ,  1 ,  1571  },
    {  1 ,   1 ,  1 ,  2  ,  1 ,  1 ,  1573  },
    {  2 ,  0 ,  0 ,  1  ,  0 ,  0 ,   0  },
    {  2 ,  0 ,  0 ,  1  ,  0 ,  1 ,  1571  },
    {  2 ,  1 ,  1 ,  2  ,  1 ,  1 ,  1573  },
}
Referenced by c128model_get_temp(), and c128model_set().