x128: arch/gtk3/widgets/settings_userport.c File Reference
settings_userport.c File Reference
Settings widget for userport devices.
#include "vice.h"
#include <gtk/gtk.h>
#include "debug_gtk3.h"
#include "petdiagnosticpinwidget.h"
#include "lib.h"
#include "machine.h"
#include "resources.h"
#include "userport.h"
#include "vice_gtk3.h"
#include "settings_userport.h"
Enumerations
enum {
COL_DEVICE_ID ,
COL_DEVICE_NAME ,
COL_DEVICE_TYPE_ID ,
COL_DEVICE_TYPE_DESC ,
COLUMN_COUNT
}
Column indexes in the useport devices model.
Functions
static GtkWidget * label_helper (const char *markup)
Create left-aligned label with Pango markup.
static GtkWidget * create_rtc_58321a_save_widget (void)
Create widget for the "UserportRTC58321aSave" resource.
static GtkWidget * create_rtc_ds1307_save_widget (void)
Create widget for the "UserportRTCDS1307Save" resource.
static void set_widgets_sensitivity (int id)
Set the RTC checkboxes' or WiC64 settings sensitivity based on device ID.
static void on_device_changed (GtkComboBox *combo, gpointer user_data)
Handler for the 'changed' event of the device combobox.
static gboolean set_device_id (GtkComboBox *combo, gint id, gboolean blocked)
Set userport device ID.
static GtkListStore * create_device_model (void)
Create model for the device combobox.
static GtkWidget * create_device_combobox (void)
Create combobox for the userport devices.
GtkWidget * settings_userport_widget_create (GtkWidget *parent)
Create widget to select userport devices.
Variables
static GtkWidget * rtc_58321a_save = NULL
58321a save enable toggle button
static GtkWidget * rtc_ds1307_save = NULL
ds1307 save enable toggle button
Detailed Description
Settings widget for userport devices.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
anonymous enum
anonymous enum
Column indexes in the useport devices model.
Enumerator
COL_DEVICE_ID
device ID (int)
COL_DEVICE_NAME
device name (str)
COL_DEVICE_TYPE_ID
device type (int)
COL_DEVICE_TYPE_DESC
device type description (str)
COLUMN_COUNT
number of columns in the model
Function Documentation
create_device_combobox()
static GtkWidget * create_device_combobox (void) static
Create combobox for the userport devices.
Create a combobox with valid userport devices for current machine.
The model of the combobox contains device ID, name and type, of which name is shown and ID is used to set the related resource.
Returns
GtkComboBox
Todo:
Try using the device type to create little headers in the combobox, grouping the devices by type. Might be overkill for some machines that only have a few userport devices, we'll see. I tried using a second column for the device type description, and althought it doesn't look bad in the popup list, when the popup isn't active it looks weird ;) So for now the device type isn't used.
Referenced by settings_userport_widget_create().
create_device_model()
static GtkListStore * create_device_model (void) static
Create model for the device combobox.
Create a model with (dev-id, dev-name, dev-type-id, dev-type-desc).
Returns
model
Referenced by create_device_combobox().
create_rtc_58321a_save_widget()
static GtkWidget * create_rtc_58321a_save_widget (void) static
Create widget for the "UserportRTC58321aSave" resource.
Returns
GtkCheckButton
Referenced by settings_userport_widget_create().
create_rtc_ds1307_save_widget()
static GtkWidget * create_rtc_ds1307_save_widget (void) static
Create widget for the "UserportRTCDS1307Save" resource.
Returns
GtkCheckButton
Referenced by settings_userport_widget_create().
label_helper()
static GtkWidget * label_helper (const char * markup) static
Create left-aligned label with Pango markup.
Parameters
[in] markup text using Pango markup
Returns
GtkLabel
Referenced by settings_userport_widget_create().
on_device_changed()
static void on_device_changed (GtkComboBox * combo, gpointer user_data) static
Handler for the 'changed' event of the device combobox.
Sets the active userport device via the "UserportDevice" resource.
Parameters
[in] combo device combo box
[in] user_data extra event data (unused)
Referenced by create_device_combobox(), and set_device_id().
set_device_id()
static gboolean set_device_id (GtkComboBox * combo, gint id, gboolean blocked) static
Set userport device ID.
Sets the currently selected combobox item via device ID.
To avoid updating the related resource via the combobox' event handler, use the blocked argument.
Parameters
[in] combo device combo box
[in] id device ID
[in] blocked block 'changed' signal handler
Referenced by settings_userport_widget_create().
set_widgets_sensitivity()
static void set_widgets_sensitivity (int id) static
Set the RTC checkboxes' or WiC64 settings sensitivity based on device ID.
Use userport device id to determine which widget to 'grey-out'.
Parameters
[in] id userport device ID
Referenced by on_device_changed(), and set_device_id().
settings_userport_widget_create()
GtkWidget * settings_userport_widget_create (GtkWidget * parent)
Create widget to select userport devices.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
Variable Documentation
rtc_58321a_save
GtkWidget* rtc_58321a_save = NULL static
58321a save enable toggle button
Referenced by set_widgets_sensitivity(), and settings_userport_widget_create().
rtc_ds1307_save
GtkWidget* rtc_ds1307_save = NULL static
ds1307 save enable toggle button
Referenced by set_widgets_sensitivity(), and settings_userport_widget_create().