vsid: arch/shared/archdep_dir.h File Reference
archdep_dir.h File Reference
Read host directory - header.
#include <stddef.h>
#include "archdep_defs.h"
Data Structures
struct archdep_dir_s
Directory object.
Macros
#define ARCHDEP_OPENDIR_NO_HIDDEN_FILES 1
Do not display hidden files.
#define ARCHDEP_OPENDIR_ALL_FILES 0
Show all files.
Typedefs
typedef struct archdep_dir_s archdep_dir_t
Directory object.
Functions
archdep_dir_t * archdep_opendir (const char *path, int mode)
Scan directory and return a directory object.
const char * archdep_readdir (archdep_dir_t *dir)
Get an entry from the directory.
void archdep_closedir (archdep_dir_t *dir)
Close directory.
void archdep_rewinddir (archdep_dir_t *dir)
Rewind position in directory.
void archdep_seekdir (archdep_dir_t *dir, int pos)
Set position in directory.
int archdep_telldir (const archdep_dir_t *dir)
Get position in directory.
const char * archdep_readdir_get_entry (const archdep_dir_t *dir, int pos)
Get entry from directory object.
const char * archdep_readdir_get_dir (const archdep_dir_t *dir, int pos)
Get directory entry from directory object.
const char * archdep_readdir_get_file (const archdep_dir_t *dir, int pos)
Get filename entry from directory object.
int archdep_readdir_num_entries (const archdep_dir_t *dir)
Get total number of entries.
int archdep_readdir_num_dirs (const archdep_dir_t *dir)
Get number of directory entries.
int archdep_readdir_num_files (const archdep_dir_t *dir)
Get number of file entries.
Detailed Description
Read host directory - header.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Macro Definition Documentation
ARCHDEP_OPENDIR_ALL_FILES
#define ARCHDEP_OPENDIR_ALL_FILES 0
Show all files.
ARCHDEP_OPENDIR_NO_HIDDEN_FILES
#define ARCHDEP_OPENDIR_NO_HIDDEN_FILES 1
Do not display hidden files.
Do not display "dotfiles" on Unix or files with the hidden attribute on Windows. Will still display the special files '.' and '..'.
Typedef Documentation
archdep_dir_t
typedef struct archdep_dir_s archdep_dir_t
Directory object.
Contains a list of directories and a list of files for a given host directory.
For the position in the directory the API concatenates the dirs and files with the dirs coming first. The directories and files are sorted in ascending order in a case-sensitive manner and thus sorted Unix-style and not Windows- style (where case folding is normally applied).
Function Documentation
archdep_closedir()
void archdep_closedir (archdep_dir_t * dir)
Close directory.
Free memory used by dir and its members.
Parameters
[in] dir directory object
Referenced by archdep_opendir(), cbmfile_find_file(), expand_shortname(), fsdevice_close(), limit_longname(), mon_show_dir(), p00_file_find(), and palette_get_info_list().
archdep_opendir()
archdep_dir_t * archdep_opendir (const char * path, int mode)
Scan directory and return a directory object.
Parameters
[in] path directory to scan
[in] mode filter to apply on each directory entry
Returns
directory object or NULL on failure
Referenced by cbmfile_find_file(), expand_shortname(), fsdevice_open_directory(), limit_longname(), mon_show_dir(), p00_file_find(), and palette_get_info_list().
archdep_readdir()
const char * archdep_readdir (archdep_dir_t * dir)
Get an entry from the directory.
Parameters
[in] dir directory object
Returns
entry or NULL when the directory is exhausted
Referenced by _limit_longname(), cbmfile_find_file(), command_directory_get(), expand_shortname(), mon_show_dir(), p00_file_find(), and palette_get_info_list().
archdep_readdir_get_dir()
const char * archdep_readdir_get_dir (const archdep_dir_t * dir, int pos)
Get directory entry from directory object.
Parameters
[in] dir directory object
[in] pos position in directories list in dir
Returns
directory name or NULL when pos is out of bounds
Referenced by archdep_readdir_get_entry().
archdep_readdir_get_entry()
const char * archdep_readdir_get_entry (const archdep_dir_t * dir, int pos)
Get entry from directory object.
Get entry from dir with the assumption that the directories come before the files, joining the two lists as a single list for the pos argument.
Parameters
[in] dir directory object
[in] pos position in directories and files list in dir
Returns
entry or NULL when pos is out of bounds
archdep_readdir_get_file()
const char * archdep_readdir_get_file (const archdep_dir_t * dir, int pos)
Get filename entry from directory object.
Parameters
[in] dir directory object
[in] pos position in files list in dir
Returns
filename or NULL when pos is out of bounds
Referenced by archdep_readdir_get_entry().
archdep_readdir_num_dirs()
int archdep_readdir_num_dirs (const archdep_dir_t * dir)
Get number of directory entries.
Parameters
[in] dir directory object
Returns
number of directory entries
archdep_readdir_num_entries()
int archdep_readdir_num_entries (const archdep_dir_t * dir)
Get total number of entries.
Parameters
[in] dir directory object
Returns
total number of entries (dirs + files)
archdep_readdir_num_files()
int archdep_readdir_num_files (const archdep_dir_t * dir)
Get number of file entries.
Parameters
[in] dir directory object
Returns
number of file entries
archdep_rewinddir()
void archdep_rewinddir (archdep_dir_t * dir)
Rewind position in directory.
Rewind position in dir to the first entry.
Parameters
[in] dir directory object
Referenced by _limit_longname().
archdep_seekdir()
void archdep_seekdir (archdep_dir_t * dir, int pos)
Set position in directory.
Parameters
[in] dir directory object
[in] pos new position
Referenced by _limit_longname().
archdep_telldir()
int archdep_telldir (const archdep_dir_t * dir)
Get position in directory.
Parameters
[in] dir directory object
Returns
position in dir or -1 when dir is exhausted
Referenced by _limit_longname().