vsid: raster/raster-modes.h File Reference
raster-modes.h File Reference
#include "raster-cache.h"
Data Structures
struct raster_modes_def_s
struct raster_modes_s
Typedefs
typedef int(* raster_modes_fill_cache_function_t) (struct raster_cache_s *c, unsigned int *changed_start, unsigned int *changed_end, int no_check)
typedef void(* raster_modes_draw_line_cached_function_t) (struct raster_cache_s *c, unsigned int start, unsigned int end)
Draw part of one line to the buffer.
typedef void(* raster_modes_draw_line_function_t) (void)
Draw the whole line to the buffer.
typedef void(* raster_modes_draw_background_function_t) (unsigned int start_pixel, unsigned int end_pixel)
Draw part of the background to the buffer.
typedef void(* raster_modes_draw_foreground_function_t) (unsigned int start_char, unsigned int end_char)
Draw part of the foreground to the buffer.
typedef struct raster_modes_def_s raster_modes_def_t
typedef struct raster_modes_s raster_modes_t
Functions
void raster_modes_init (raster_modes_t *modes, unsigned int num_modes)
void raster_modes_shutdown (raster_modes_t *modes)
raster_modes_t * raster_modes_new (unsigned int num_modes)
void raster_modes_set (raster_modes_t *modes, unsigned int num_mode, raster_modes_fill_cache_function_t fill_cache, raster_modes_draw_line_cached_function_t draw_line_cached, raster_modes_draw_line_function_t draw_line, raster_modes_draw_background_function_t draw_background, raster_modes_draw_foreground_function_t draw_foreground)
int raster_modes_set_idle_mode (raster_modes_t *modes, unsigned int num_mode)
static int raster_modes_fill_cache (raster_modes_t *modes, unsigned int mode_num, struct raster_cache_s *c, unsigned int *changed_start, unsigned int *changed_end, int no_check)
static void raster_modes_draw_line_cached (raster_modes_t *modes, unsigned int mode_num, struct raster_cache_s *c, int start, int end)
static void raster_modes_draw_line (raster_modes_t *modes, unsigned int mode_num)
static void raster_modes_draw_background (raster_modes_t *modes, unsigned int mode_num, unsigned int start_pixel, unsigned int end_pixel)
static void raster_modes_draw_foreground (raster_modes_t *modes, unsigned int mode_num, int start_char, int end_char)
static int raster_modes_get_idle_mode (raster_modes_t *modes)
Typedef Documentation
raster_modes_def_t
typedef struct raster_modes_def_s raster_modes_def_t
raster_modes_draw_background_function_t
typedef void(* raster_modes_draw_background_function_t) (unsigned int start_pixel, unsigned int end_pixel)
Draw part of the background to the buffer.
raster_modes_draw_foreground_function_t
typedef void(* raster_modes_draw_foreground_function_t) (unsigned int start_char, unsigned int end_char)
Draw part of the foreground to the buffer.
raster_modes_draw_line_cached_function_t
typedef void(* raster_modes_draw_line_cached_function_t) (struct raster_cache_s *c, unsigned int start, unsigned int end)
Draw part of one line to the buffer.
raster_modes_draw_line_function_t
typedef void(* raster_modes_draw_line_function_t) (void)
Draw the whole line to the buffer.
raster_modes_fill_cache_function_t
typedef int(* raster_modes_fill_cache_function_t) (struct raster_cache_s *c, unsigned int *changed_start, unsigned int *changed_end, int no_check)
raster_modes_t
typedef struct raster_modes_s raster_modes_t
Function Documentation
raster_modes_draw_background()
static void raster_modes_draw_background (raster_modes_t * modes, unsigned int mode_num, unsigned int start_pixel, unsigned int end_pixel) inline static
Referenced by handle_visible_line_with_changes().
raster_modes_draw_foreground()
static void raster_modes_draw_foreground (raster_modes_t * modes, unsigned int mode_num, int start_char, int end_char) inline static
Referenced by handle_visible_line_with_changes().
raster_modes_draw_line()
static void raster_modes_draw_line (raster_modes_t * modes, unsigned int mode_num) inline static
Referenced by handle_visible_line_without_cache().
raster_modes_draw_line_cached()
static void raster_modes_draw_line_cached (raster_modes_t * modes, unsigned int mode_num, struct raster_cache_s * c, int start, int end) inline static
Referenced by handle_visible_line_with_cache(), update_for_minor_changes(), and update_for_minor_changes_sprite().
raster_modes_fill_cache()
static int raster_modes_fill_cache (raster_modes_t * modes, unsigned int mode_num, struct raster_cache_s * c, unsigned int * changed_start, unsigned int * changed_end, int no_check) inline static
Referenced by handle_visible_line_with_cache(), update_for_minor_changes(), and update_for_minor_changes_sprite().
raster_modes_get_idle_mode()
static int raster_modes_get_idle_mode (raster_modes_t * modes) inline static
Referenced by raster_line_get_real_mode().
raster_modes_init()
void raster_modes_init (raster_modes_t * modes, unsigned int num_modes)
Referenced by raster_init(), and raster_modes_new().
raster_modes_new()
raster_modes_t * raster_modes_new (unsigned int num_modes)
raster_modes_set()
void raster_modes_set (raster_modes_t * modes, unsigned int num_mode, raster_modes_fill_cache_function_t fill_cache, raster_modes_draw_line_cached_function_t draw_line_cached, raster_modes_draw_line_function_t draw_line, raster_modes_draw_background_function_t draw_background, raster_modes_draw_foreground_function_t draw_foreground)
Referenced by setup_modes().
raster_modes_set_idle_mode()
int raster_modes_set_idle_mode (raster_modes_t * modes, unsigned int num_mode)
Referenced by init_raster().
raster_modes_shutdown()
void raster_modes_shutdown (raster_modes_t * modes)
Referenced by raster_shutdown().