vsid: printerdrv/drv-mps803.h File Reference
drv-mps803.h File Reference
#include <stdio.h>
Functions
int drv_mps803_init_resources (void)
Register drivers.
int drv_mps803_init (void)
void drv_mps803_shutdown (void)
Function Documentation
drv_mps803_init()
int drv_mps803_init (void)
Todo:
FIXME: rename the palette somehow?
Referenced by printer_init().
drv_mps803_init_resources()
int drv_mps803_init_resources (void)
Register drivers.
Register printer drivers.
Commodore MPS 801
Commodore MPS 802
Commodore MPS 803
Commodore 2022
Commodore 4034
Commodore 8034
Returns
0
Referenced by printer_resources_init().
drv_mps803_shutdown()
void drv_mps803_shutdown (void)
Referenced by printer_shutdown().