vsid: arch/gtk3/uicmdline.c File Reference
uicmdline.c File Reference
Dialog to display command line options.
#include "vice.h"
#include <gtk/gtk.h>
#include "widgethelpers.h"
#include "debug_gtk3.h"
#include "machine.h"
#include "cmdline.h"
#include "ui.h"
#include "uiactions.h"
#include "uicmdline.h"
Functions
static void on_destroy (GtkWidget *dialog, gpointer unused)
Handler for the 'destroy' event of the dialog.
static void on_response (GtkDialog *dialog, gint response_id, gpointer user_data)
Handler for the 'response' event of the dialog.
static GtkWidget * create_content_widget (void)
Create textview with scrollbars.
void uicmdline_dialog_show (void)
Show list of command line options.
Detailed Description
Dialog to display command line options.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_content_widget()
static GtkWidget * create_content_widget (void) static
Create textview with scrollbars.
Returns
GtkScrolledWindow
Referenced by uicmdline_dialog_show().
on_destroy()
static void on_destroy (GtkWidget * dialog, gpointer unused) static
Handler for the 'destroy' event of the dialog.
Parameters
[in] dialog dialog triggering the event
[in] unused extra event data (unused)
Referenced by uicmdline_dialog_show().
on_response()
static void on_response (GtkDialog * dialog, gint response_id, gpointer user_data) static
Handler for the 'response' event of the dialog.
Parameters
[in,out] dialog dialog triggering the event
[in] response_id response ID
[in] user_data extra event data (unused)
Referenced by uicmdline_dialog_show().
uicmdline_dialog_show()
void uicmdline_dialog_show (void)
Show list of command line options.
Referenced by help_command_line_action().