x128: c128/c128rom.h File Reference
c128rom.h File Reference
Macros
#define C128_BASIC_85_CHECKSUM 38592
BASICLO + BASICHI.
#define C128_BASIC_86_CHECKSUM 2496
#define C128_EDITOR_R01_CHECKSUM 56682
0x0000 - 0x0fff in kernal image
#define C128_EDITOR_SE_R01_CHECKSUM 9364
#define C128_EDITOR_DE_R01_CHECKSUM 9619
#define C128_KERNAL_R01_CHECKSUM 22353
0x2000 - 0x3fff in kernal image
#define C128_KERNAL_SE_R01_CHECKSUM 24139 /*! \todo FIXME: 23086 ? */
#define C128_KERNAL_DE_R01_CHECKSUM 22098 /*! \todo FIXME: 19680 ? */
#define C128_KERNAL_CH_R01_CHECKSUM 21376
#define C128_CHARGEN_NAME "chargen-390059-01.bin"
C128 chargen.
#define C128_CHARGEN_BE_NAME "chargen-325167-02.bin"
italian/french/belgium
#define C128_CHARGEN_CH_NAME "chargen-325173-01D.bin"
#define C128_CHARGEN_DE_NAME "chargen-315079-01.bin"
#define C128_CHARGEN_FI_NAME "chargen-325181-01.bin"
same as swedish
#define C128_CHARGEN_FR_NAME "chargen-325167-02.bin"
italian/french/belgium
#define C128_CHARGEN_IT_NAME "chargen-325167-02.bin"
italian/french/belgium
#define C128_CHARGEN_NO_NAME "chargen-325078-02.bin"
#define C128_CHARGEN_SE_NAME "chargen-325181-01.bin"
#define C128_KERNAL_NAME "kernal-318020-05.bin"
C128 Kernal (Editor + Z80BIOS + Kernal)
#define C128_KERNAL_CH_NAME "kernal-325172-01.bin"
second half in 318081-01
#define C128_KERNAL_DE_NAME "kernal-315078-03.bin"
#define C128_KERNAL_FI_NAME "kernalfi" /*! \todo FIXME: identify */
#define C128_KERNAL_FR_NAME "kernalfr" /*! \todo FIXME: identify */
#define C128_KERNAL_IT_NAME "kernalit" /*! \todo FIXME: identify */
#define C128_KERNAL_NO_NAME "kernalno" /*! \todo FIXME: identify */
#define C128_KERNAL_SE_NAME "kernal-318034-01.bin"
#define C128_BASICLO_NAME "basiclo-318018-04.bin"
C128 BASIC.
#define C128_BASICHI_NAME "basichi-318019-04.bin"
Editor.
#define C128_BASIC64_NAME "basic64-901226-01.bin"
C64 BASIC.
#define C128_KERNAL64_NAME "kernal64-901227-03.bin"
C64 Kernal.
#define C128_KERNAL64_DK_NAME "kernal64-325176-07.bin"
second 8k OF 325176-07
#define C128_KERNAL64_NO_NAME "kernal64-325179-01.bin"
second 8k OF 325179-01
#define C128_KERNAL64_SE_NAME "kernal64-325182-01.bin"
second 8k OF 325182-01
Functions
int c128rom_load_kernal_int (const char *rom_name)
int c128rom_load_kernal_ch (const char *rom_name)
int c128rom_load_kernal_de (const char *rom_name)
int c128rom_load_kernal_fi (const char *rom_name)
int c128rom_load_kernal_fr (const char *rom_name)
int c128rom_load_kernal_it (const char *rom_name)
int c128rom_load_kernal_no (const char *rom_name)
int c128rom_load_kernal_se (const char *rom_name)
int c128rom_load_basiclo (const char *rom_name)
int c128rom_load_basichi (const char *rom_name)
int c128rom_load_chargen_int (const char *rom_name)
int c128rom_load_chargen_ch (const char *rom_name)
int c128rom_load_chargen_de (const char *rom_name)
int c128rom_load_chargen_fi (const char *rom_name)
int c128rom_load_chargen_fr (const char *rom_name)
int c128rom_load_chargen_it (const char *rom_name)
int c128rom_load_chargen_no (const char *rom_name)
int c128rom_load_chargen_se (const char *rom_name)
int c128rom_load_kernal64 (const char *rom_name, uint8_t *cartkernal)
int c128rom_load_basic64 (const char *rom_name)
int c128rom_basic_checksum (void)
int c128rom_kernal_checksum (void)
int c128rom_kernal_setup (void)
int c128rom_chargen_setup (void)
Macro Definition Documentation
C128_BASIC64_NAME
#define C128_BASIC64_NAME "basic64-901226-01.bin"
C64 BASIC.
first 8k in 318081-01
C128_BASIC_85_CHECKSUM
#define C128_BASIC_85_CHECKSUM 38592
BASICLO + BASICHI.
C128_BASIC_86_CHECKSUM
#define C128_BASIC_86_CHECKSUM 2496
C128_BASICHI_NAME
#define C128_BASICHI_NAME "basichi-318019-04.bin"
Editor.
C128_BASICLO_NAME
#define C128_BASICLO_NAME "basiclo-318018-04.bin"
C128 BASIC.
BASIC
C128_CHARGEN_BE_NAME
#define C128_CHARGEN_BE_NAME "chargen-325167-02.bin"
italian/french/belgium
C128_CHARGEN_CH_NAME
#define C128_CHARGEN_CH_NAME "chargen-325173-01D.bin"
C128_CHARGEN_DE_NAME
#define C128_CHARGEN_DE_NAME "chargen-315079-01.bin"
C128_CHARGEN_FI_NAME
#define C128_CHARGEN_FI_NAME "chargen-325181-01.bin"
same as swedish
C128_CHARGEN_FR_NAME
#define C128_CHARGEN_FR_NAME "chargen-325167-02.bin"
italian/french/belgium
C128_CHARGEN_IT_NAME
#define C128_CHARGEN_IT_NAME "chargen-325167-02.bin"
italian/french/belgium
C128_CHARGEN_NAME
#define C128_CHARGEN_NAME "chargen-390059-01.bin"
C128 chargen.
C128_CHARGEN_NO_NAME
#define C128_CHARGEN_NO_NAME "chargen-325078-02.bin"
C128_CHARGEN_SE_NAME
#define C128_CHARGEN_SE_NAME "chargen-325181-01.bin"
C128_EDITOR_DE_R01_CHECKSUM
#define C128_EDITOR_DE_R01_CHECKSUM 9619
C128_EDITOR_R01_CHECKSUM
#define C128_EDITOR_R01_CHECKSUM 56682
0x0000 - 0x0fff in kernal image
C128_EDITOR_SE_R01_CHECKSUM
#define C128_EDITOR_SE_R01_CHECKSUM 9364
C128_KERNAL64_DK_NAME
#define C128_KERNAL64_DK_NAME "kernal64-325176-07.bin"
second 8k OF 325176-07
C128_KERNAL64_NAME
#define C128_KERNAL64_NAME "kernal64-901227-03.bin"
C64 Kernal.
second 8k in 318081-01
C128_KERNAL64_NO_NAME
#define C128_KERNAL64_NO_NAME "kernal64-325179-01.bin"
second 8k OF 325179-01
C128_KERNAL64_SE_NAME
#define C128_KERNAL64_SE_NAME "kernal64-325182-01.bin"
second 8k OF 325182-01
C128_KERNAL_CH_NAME
#define C128_KERNAL_CH_NAME "kernal-325172-01.bin"
second half in 318081-01
C128_KERNAL_CH_R01_CHECKSUM
#define C128_KERNAL_CH_R01_CHECKSUM 21376
C128_KERNAL_DE_NAME
#define C128_KERNAL_DE_NAME "kernal-315078-03.bin"
C128_KERNAL_DE_R01_CHECKSUM
#define C128_KERNAL_DE_R01_CHECKSUM 22098 /*! \todo FIXME: 19680 ? */
C128_KERNAL_FI_NAME
#define C128_KERNAL_FI_NAME "kernalfi" /*! \todo FIXME: identify */
C128_KERNAL_FR_NAME
#define C128_KERNAL_FR_NAME "kernalfr" /*! \todo FIXME: identify */
C128_KERNAL_IT_NAME
#define C128_KERNAL_IT_NAME "kernalit" /*! \todo FIXME: identify */
C128_KERNAL_NAME
#define C128_KERNAL_NAME "kernal-318020-05.bin"
C128 Kernal (Editor + Z80BIOS + Kernal)
C128_KERNAL_NO_NAME
#define C128_KERNAL_NO_NAME "kernalno" /*! \todo FIXME: identify */
C128_KERNAL_R01_CHECKSUM
#define C128_KERNAL_R01_CHECKSUM 22353
0x2000 - 0x3fff in kernal image
C128_KERNAL_SE_NAME
#define C128_KERNAL_SE_NAME "kernal-318034-01.bin"
C128_KERNAL_SE_R01_CHECKSUM
#define C128_KERNAL_SE_R01_CHECKSUM 24139 /*! \todo FIXME: 23086 ? */
Function Documentation
c128rom_basic_checksum()
int c128rom_basic_checksum (void)
< BASICLO + BASICHI
< BASICLO + BASICHI
< BASICLO + BASICHI
< 0x0000 - 0x0fff in kernal image
Referenced by c128rom_kernal_setup(), and mem_read_rom_snapshot_module().
c128rom_chargen_setup()
int c128rom_chargen_setup (void)
Referenced by mem_load(), set_chargen_ch_rom_name(), set_chargen_de_rom_name(), set_chargen_fi_rom_name(), set_chargen_fr_rom_name(), set_chargen_int_rom_name(), set_chargen_it_rom_name(), set_chargen_no_rom_name(), set_chargen_se_rom_name(), and set_machine_type().
c128rom_kernal_checksum()
int c128rom_kernal_checksum (void)
< 0x2000 - 0x3fff in kernal image
Referenced by c128rom_kernal_setup(), and mem_read_rom_snapshot_module().
c128rom_kernal_setup()
int c128rom_kernal_setup (void)
< second 8k in 318081-01
< second 8k OF 325179-01
< second 8k OF 325182-01
< BASICLO + BASICHI
< 0x0000 - 0x0fff in kernal image
< 0x0000 - 0x0fff in kernal image
< 0x1000 - 0x1fff in kernal image
< 0x0000 - 0x0fff in kernal image
< 0x1000 - 0x1fff in kernal image
< 0x2000 - 0x3fff in kernal image
< 0x2000 - 0x3fff in kernal image
Referenced by mem_load(), set_kernal_ch_rom_name(), set_kernal_de_rom_name(), set_kernal_fi_rom_name(), set_kernal_fr_rom_name(), set_kernal_int_rom_name(), set_kernal_it_rom_name(), set_kernal_no_rom_name(), set_kernal_se_rom_name(), and set_machine_type().
c128rom_load_basic64()
int c128rom_load_basic64 (const char * rom_name)
Referenced by mem_load(), and set_basic64_rom_name().
c128rom_load_basichi()
int c128rom_load_basichi (const char * rom_name)
Referenced by mem_load(), and set_basichi_rom_name().
c128rom_load_basiclo()
int c128rom_load_basiclo (const char * rom_name)
Referenced by mem_load(), and set_basiclo_rom_name().
c128rom_load_chargen_ch()
int c128rom_load_chargen_ch (const char * rom_name)
Referenced by mem_load(), and set_chargen_ch_rom_name().
c128rom_load_chargen_de()
int c128rom_load_chargen_de (const char * rom_name)
Referenced by mem_load(), and set_chargen_de_rom_name().
c128rom_load_chargen_fi()
int c128rom_load_chargen_fi (const char * rom_name)
Referenced by mem_load(), and set_chargen_fi_rom_name().
c128rom_load_chargen_fr()
int c128rom_load_chargen_fr (const char * rom_name)
Referenced by mem_load(), and set_chargen_fr_rom_name().
c128rom_load_chargen_int()
int c128rom_load_chargen_int (const char * rom_name)
Referenced by mem_load(), and set_chargen_int_rom_name().
c128rom_load_chargen_it()
int c128rom_load_chargen_it (const char * rom_name)
Referenced by mem_load(), and set_chargen_it_rom_name().
c128rom_load_chargen_no()
int c128rom_load_chargen_no (const char * rom_name)
Referenced by mem_load(), and set_chargen_no_rom_name().
c128rom_load_chargen_se()
int c128rom_load_chargen_se (const char * rom_name)
Referenced by mem_load(), and set_chargen_se_rom_name().
c128rom_load_kernal64()
int c128rom_load_kernal64 (const char * rom_name, uint8_t * cartkernal)
Referenced by c64rom_load_kernal(), mem_load(), and set_kernal64_rom_name().
c128rom_load_kernal_ch()
int c128rom_load_kernal_ch (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_ch_rom_name().
c128rom_load_kernal_de()
int c128rom_load_kernal_de (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_de_rom_name().
c128rom_load_kernal_fi()
int c128rom_load_kernal_fi (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_fi_rom_name().
c128rom_load_kernal_fr()
int c128rom_load_kernal_fr (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_fr_rom_name().
c128rom_load_kernal_int()
int c128rom_load_kernal_int (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_int_rom_name().
c128rom_load_kernal_it()
int c128rom_load_kernal_it (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_it_rom_name().
c128rom_load_kernal_no()
int c128rom_load_kernal_no (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_no_rom_name().
c128rom_load_kernal_se()
int c128rom_load_kernal_se (const char * rom_name)
< Editor + Z80BIOS + Kernal
< Editor + Z80BIOS + Kernal
Referenced by mem_load(), and set_kernal_se_rom_name().