x128: uiapi.h File Reference
uiapi.h File Reference
#include "types.h"
#include <stdbool.h>
#include <stdint.h>
#include "arch/shared/uiactions.h"
Enumerations
enum ui_jam_action_t {
UI_JAM_INVALID = -1 ,
UI_JAM_RESET_CPU ,
UI_JAM_POWER_CYCLE ,
UI_JAM_MONITOR ,
UI_JAM_NONE
}
Do not include this header file, include ‘ui.h’ instead.
enum ui_extendimage_action_t {
UI_EXTEND_IMAGE_INVALID = -1 ,
UI_EXTEND_IMAGE_NEVER ,
UI_EXTEND_IMAGE_ALWAYS
}
enum ui_drive_enable_t {
UI_DRIVE_ENABLE_NONE = 0 ,
UI_DRIVE_ENABLE_0 = 1 << 0 ,
UI_DRIVE_ENABLE_1 = 1 << 1 ,
UI_DRIVE_ENABLE_2 = 1 << 2 ,
UI_DRIVE_ENABLE_3 = 1 << 3
}
Functions
int ui_resources_init (void)
Initialization
void ui_resources_shutdown (void)
Clean up memory used by VICE resources.
int ui_cmdline_options_init (void)
Initialize command line options (generic)
void ui_init_with_args (int *argc, char **argv)
Initialize Gtk3/GLib.
int ui_init_finalize (void)
Finalize initialization after creating the main window(s)
void ui_shutdown (void)
Clean up memory used by the UI system itself.
int ui_init (void)
Initialize UI.
void ui_message (const char *format,...)
Print a message.
void ui_error (const char *format,...)
Print an error message.
void ui_display_statustext (const char *text, bool fadeout)
Display a mesage without interrupting emulation.
char * ui_get_file (const char *format,...)
Let the user browse for a filename; display format as a titel.
void ui_enable_drive_status (ui_drive_enable_t state, int *drive_led_color)
Drive related UI.
void ui_display_drive_track (unsigned int drive_number, unsigned int drive_base, unsigned int half_track_number, unsigned int disk_side)
Statusbar API function to report changes in drive head location.
void ui_display_drive_led (unsigned int drive_number, unsigned int drive_base, unsigned int led_pwm1, unsigned int led_pwm2)
The pwm value will vary between 0 and 1000.
void ui_display_drive_current_image (unsigned int unit_number, unsigned int drive_number, const char *image)
Statusbar API function to report mounting or unmounting of a disk image.
int ui_extend_image_dialog (void)
Display the "Do you want to extend the disk image?" dialog.
void ui_set_tape_status (int port, int tape_status)
Statusbar API function to report changes in tape status.
void ui_display_tape_motor_status (int port, int motor)
Statusbar API function to report changes in the tape motor.
void ui_display_tape_control_status (int port, int control)
Statusbar API function to report changes in tape control status.
void ui_display_tape_counter (int port, int counter)
Statusbar API function to report changes in tape position.
void ui_display_tape_current_image (int port, const char *image)
Statusbar API function to report mounting or unmounting of a tape image.
ui_jam_action_t ui_jam_dialog (const char *format,...)
Show a CPU JAM dialog.
void ui_display_reset (int device, int mode)
Reset.
void ui_display_playback (int playback_status, char *version)
Recording UI.
void ui_display_recording (int recording_status)
Statusbar API function to display recording status.
void ui_display_event_time (unsigned int current, unsigned int total)
Statusbar API function to register an elapsed time.
void ui_display_joyport (uint16_t *joyport)
Joystick UI.
void arch_ui_activate (void)
Show settings dialog from a joystick button.
void ui_display_volume (int vol)
Volume UI.
void ui_hotkeys_arch_init (void)
Run UI-specific hotkeys initialization code.
void ui_hotkeys_arch_shutdown (void)
Run UI-specific hotkeys shutdown code.
void ui_hotkeys_arch_install_by_map (ui_action_map_t *map)
Install hotkey.
void ui_hotkeys_arch_update_by_map (ui_action_map_t *map, uint32_t vice_keysym, uint32_t vice_modmask)
Update hotkey.
void ui_hotkeys_arch_remove_by_map (ui_action_map_t *map)
Remove hotkey.
uint32_t ui_hotkeys_arch_keysym_from_arch (uint32_t arch_keysym)
Translate arch keysym to VICE keysysm.
uint32_t ui_hotkeys_arch_keysym_to_arch (uint32_t vice_keysym)
Translate VICE keysym to arch keysysm.
uint32_t ui_hotkeys_arch_modifier_from_arch (uint32_t arch_mod)
Translate arch modifier to VICE modifier.
uint32_t ui_hotkeys_arch_modifier_to_arch (uint32_t vice_mod)
Translate VICE modifier to arch modifier.
uint32_t ui_hotkeys_arch_modmask_from_arch (uint32_t arch_modmask)
Translate arch modifier mask to VICE modifier mask.
uint32_t ui_hotkeys_arch_modmask_to_arch (uint32_t vice_modmask)
Translate VICE modifier mask to arch modifier.
Enumeration Type Documentation
ui_drive_enable_t
enum ui_drive_enable_t
Enumerator
UI_DRIVE_ENABLE_NONE
UI_DRIVE_ENABLE_0
UI_DRIVE_ENABLE_1
UI_DRIVE_ENABLE_2
UI_DRIVE_ENABLE_3
ui_extendimage_action_t
enum ui_extendimage_action_t
Enumerator
UI_EXTEND_IMAGE_INVALID
UI_EXTEND_IMAGE_NEVER
UI_EXTEND_IMAGE_ALWAYS
ui_jam_action_t
enum ui_jam_action_t
Do not include this header file, include ‘ui.h’ instead.
Enumerator
UI_JAM_INVALID
error
UI_JAM_RESET_CPU
reset machine/drivee CPU
UI_JAM_POWER_CYCLE
power cycle macine/drive
UI_JAM_MONITOR
break into the monitor
UI_JAM_NONE
don't do anything
Function Documentation
arch_ui_activate()
void arch_ui_activate (void)
Show settings dialog from a joystick button.
ui_cmdline_options_init()
int ui_cmdline_options_init (void)
Initialize command line options (generic)
Returns
0 on success, -1 on failure
Referenced by init_cmdline_options().
ui_display_drive_current_image()
void ui_display_drive_current_image (unsigned int unit_number, unsigned int drive_number, const char * image)
Statusbar API function to report mounting or unmounting of a disk image.
Parameters
unit_number 0-3 to represent disk units at device 8-11.
drive_number 0-1 to represent the drives in a unit
image The filename of the disk image (if mounted), or the empty string or NULL (if unmounting).
Todo:
This API is insufficient to describe drives with two disk units.
Referenced by file_system_attach_disk_internal(), file_system_detach_disk_single(), and set_file_system_device().
ui_display_drive_led()
void ui_display_drive_led (unsigned int drive_number, unsigned int drive_base, unsigned int led_pwm1, unsigned int led_pwm2)
The pwm value will vary between 0 and 1000.
The pwm value will vary between 0 and 1000.
This function simply updates global state, rendering occurs in ui_update_statusbars().
Parameters
drive_number The unit to update (0-3 for drives 8-11)
drive_base Drive 0 or 1 of dualdrives
led_pwm1 The intensity of the first LED (0=off, 1000=maximum intensity)
led_pwm2 The intensity of the second LED (0=off, 1000=maximum intensity)
Todo:
Dual drive code doesn't have its separate Error LED. Its setting is mixed in in the led_status of drive 0. Also those error LEDs don't flash but are just on (or on some models, change the green/red LED to red).
Todo:
Fatal error?
Referenced by drive_led_update().
ui_display_drive_track()
void ui_display_drive_track (unsigned int drive_number, unsigned int drive_base, unsigned int half_track_number, unsigned int drive_side)
Statusbar API function to report changes in drive head location.
This function simply updates global state, rendering occurs in ui_update_statusbars().
Parameters
drive_number The unit to update (0-3 for drives 8-11)
drive_base Drive 0 or 1 of dualdrives
half_track_number Twice the value of the head location. 18.0 is 36, while 18.5 would be 37.
drive_side drive side for dual-head drives (0 or 1)
Todo:
The statusbar API does not yet support dual-unit disk drives. The drive_base argument will likely come into play once it does.
Todo:
Fatal error?
Referenced by drive_update_ui_status(), vdrive_read_sector(), and vdrive_write_sector().
ui_display_event_time()
void ui_display_event_time (unsigned int current, unsigned int total)
Statusbar API function to register an elapsed time.
Parameters
current The current time value in seconds
total The maximum time value in seconds
Referenced by event_alarm_handler().
ui_display_joyport()
void ui_display_joyport (uint16_t * joyport)
Joystick UI.
Joystick UI.
Parameters
joyport An array of bytes of size at least JOYPORT_MAX_PORTS+1, with data regarding each active joyport.
Warning
The joyport array is, for all practical purposes, 1-indexed. joyport[0] is unused.
See also
ui_sb_state_s::current_joyports Describes the format of the data encoded in the joyport array. Note that current_joyports is 0-indexed as is typical for C arrays.
Todo:
FIXME: during the joystick data extension the joyport type has become uint16_t, I did not change anything except the parameter of the function
ui_display_playback()
void ui_display_playback (int playback_status, char * version)
Recording UI.
Recording UI.
Parameters
playback_status Unknown.
version seems to be the VICE version major.minor during playback and NULL when playback is done.
Todo:
This function is not implemented and its API is not understood.
Note
Since the statusbar message display widget has been removed, we have some space to implement a widget to display information regarding playback/recording.
Referenced by event_playback_start_trap(), and event_playback_stop().
ui_display_recording()
void ui_display_recording (int recording_status)
Statusbar API function to display recording status.
Parameters
recording_status seems to be bool indicating recording active
Todo:
This function is not implemented and its API is not understood.
Note
Since the statusbar message display widget has been removed, we have some space to implement a widget to display information regarding playback/recording.
Referenced by event_record_start_trap(), event_record_stop(), history_record_start_action(), history_record_stop_action(), on_response(), and ui_media_stop_recording().
ui_display_reset()
void ui_display_reset (int device, int mode)
Reset.
Reset.
A device was reset, so we show it on the statusbar
Parameters
[in] device device number
[in] mode reset mode (soft(0) or hard(1) ,only for device 0)
Referenced by cpu_reset(), and machine_trigger_reset_internal().
ui_display_statustext()
void ui_display_statustext (const char * text, bool fadeout)
Display a mesage without interrupting emulation.
Display a mesage without interrupting emulation.
Parameters
text The text to display.
fadeout Erase the text after five* seconds unless it has already been replaced.
Note
Safe to call from VICE thread.
See also
MESSAGE_TIMEOUT for the actual timeout in seconds
Referenced by do_attach(), fliplist_add_action(), fliplist_clear_action(), fliplist_load_response(), fliplist_next_action(), fliplist_previous_action(), fliplist_remove_action(), fliplist_save_response(), hotkeys_clear_action(), hotkeys_default_action(), hotkeys_load_action(), hotkeys_save_action(), network_connect_client(), network_disconnect(), network_hook_connected_receive(), network_hook_connected_send(), network_server_connect_trap(), network_start_server(), network_test_delay(), on_response(), on_row_activated(), playlist_load_callback(), save_callback(), statusbar_speed_widget_update(), ui_fliplist_select_cb(), and vsid_playlist_save().
ui_display_tape_control_status()
void ui_display_tape_control_status (int port, int control)
Statusbar API function to report changes in tape control status.
Parameters
[in] port tape port index (0 or 1)
[in] control The new tape control. See the DATASETTE_CONTROL_* constants in datasette.h for legal values of this parameter.
ui_display_tape_counter()
void ui_display_tape_counter (int port, int counter)
Statusbar API function to report changes in tape position.
Parameters
[in] port tape port index (0 or 1)
[in] counter the new value of the position counter
Note
Only the last three digits of the counter will be displayed.
ui_display_tape_current_image()
void ui_display_tape_current_image (int port, const char * image)
Statusbar API function to report mounting or unmounting of a tape image.
Parameters
image The filename of the tape image (if mounted), or the empty string or NULL (if unmounting).
Referenced by tape_image_attach_internal(), and tape_image_detach_internal().
ui_display_tape_motor_status()
void ui_display_tape_motor_status (int port, int motor)
Statusbar API function to report changes in the tape motor.
Parameters
[in] port tape port index (0 or 1)
[in] motor Nonzero if the tape motor is now on.
ui_display_volume()
void ui_display_volume (int vol)
Volume UI.
Volume UI.
This function is a NOP since the volume can be checked and altered via the Mixer Controls via the statusbar.
Parameters
[in] vol new volume level
Referenced by set_volume().
ui_enable_drive_status()
void ui_enable_drive_status (ui_drive_enable_t state, int * drive_led_color)
Drive related UI.
Drive related UI.
Parameters
state A bitmask int, where bits 0-3 indicate whether or not drives 8-11 respectively are being emulated carefully enough to provide LED information.
drive_led_color An array of size at least NUM_DISK_UNITS that provides information about the LEDs on this drive. An element of this array will only be checked if the corresponding bit in state is 1.
Note
Before calling this function, the drive configuration resources (Drive8Type, Drive9Type, etc) should all be set to the values you wish to display.
Warning
If a drive's LEDs are active when its LED values change, the UI will not reflect the LED type change until the next time the led's values are updated. This should not happen under normal circumstances.
See also
compute_drives_enabled_mask() for how this function determines which drives are truly active
ui_sb_state_s::drive_led_types for the data in each element of drive_led_color
Referenced by drive_enable_update_ui().
ui_error()
void ui_error (const char * format, ...)
Print an error message.
Print an error message.
Parameters
[in] format format string for the error
Referenced by archdep_startup_log_error(), artstudio_ted_save(), artstudio_vdc_save(), artstudio_vicii_save(), artstudiodrv_save(), autostart_prg_with_disk_image(), check_resource_file_version(), display_error_with_vice_version(), event_playback_attach_image(), event_playback_start_trap(), event_record_reset_milestone_trap(), event_record_set_milestone_trap(), event_record_start_trap(), event_record_stop_trap(), ffmpegexedrv_init_file(), koala_ted_save(), koala_vdc_save(), koala_vicii_save(), koaladrv_save(), minipaintdrv_save(), network_client_connect_trap(), network_connect_client(), network_hook_connected_receive(), network_server_connect_trap(), network_start_server(), sampler_start(), screenshot_save(), set_video_halve_framerate(), snapshot_display_error(), sound_error(), sound_open(), tapeport_set_device(), userport_joystick_cga_enable(), userport_joystick_hit_enable(), userport_joystick_hummer_enable(), userport_joystick_kingsoft_enable(), userport_joystick_oem_enable(), userport_joystick_pet_enable(), userport_joystick_starbyte_enable(), userport_joystick_synergy_enable(), userport_joystick_woj_enable(), userport_petscii_enable(), userport_set_device(), userport_spt_joystick_enable(), userport_superpad64_enable(), and zmbvdrv_init_file().
ui_extend_image_dialog()
int ui_extend_image_dialog (void)
Display the "Do you want to extend the disk image?" dialog.
Returns
nonzero to extend the image, 0 otherwise
Todo:
FIXME: ideally we would somehow get the drive and perhaps name of the mounted image and put it into the message.
Referenced by drive_gcr_data_writeback().
ui_get_file()
char * ui_get_file (const char * format, ...)
Let the user browse for a filename; display format as a titel.
Let the user browse for a filename; display format as a titel.
Parameters
[in] format format string for the dialog's title
Returns
a copy of the chosen file's name; free it with lib_free()
Note
This is currently only called by event_playback_attach_image()
Warning
This function is unimplemented and will intentionally crash VICE if it is called.
Referenced by event_playback_attach_image().
ui_hotkeys_arch_init()
void ui_hotkeys_arch_init (void)
Run UI-specific hotkeys initialization code.
This function is called after the generic hotkeys code has initialized and allows UIs to do their own additional initialization. For example, Gtk3 will set up its GtkAccelGroup here.
Run UI-specific hotkeys initialization code.
Note
Does not initialize command line options or vice resources, that is done separately in hotkeys_cmdline_options_init() and hotkeys_resources_init().
ui_hotkeys_arch_install_by_map()
void ui_hotkeys_arch_install_by_map (ui_action_map_t * map)
Install hotkey.
Run UI-specific code to register the hotkey in map. The map contains a UI action ID, a VICE keysym and a VICE modifier mask, the UI needs to register the hotkey using its API and, if present, set the menu item pointer(s) in map.
Parameters
[in] map UI action map object
Install hotkey.
Referenced by ui_hotkeys_install_by_map(), and ui_hotkeys_update_by_map().
ui_hotkeys_arch_keysym_from_arch()
uint32_t ui_hotkeys_arch_keysym_from_arch (uint32_t arch_keysym)
Translate arch keysym to VICE keysysm.
Parameters
[in] arch_keysym arch keysym
Returns
VICE keysym
Translate arch keysym to VICE keysysm.
Parameters
[in] arch_keysym UI-specific keysym
Returns
VICE-specific keysym
See also
src/arch/shared/hotkeys/vhkkeysyms.h
Referenced by dialog_accept_handler(), and ui_action_map_get_by_arch_hotkey().
ui_hotkeys_arch_keysym_to_arch()
uint32_t ui_hotkeys_arch_keysym_to_arch (uint32_t vice_keysym)
Translate VICE keysym to arch keysysm.
Parameters
[in] vice_keysym VICE keysym
Returns
arch keysym
Translate VICE keysym to arch keysysm.
Parameters
[in] vice_keysym VICE-specific keysym
Returns
UI-specific keysym
See also
src/arch/shared/hotkeys/vhkkeysyms.h
Referenced by ui_hotkeys_update_by_map(), and vhk_parser_get_keysym_and_modmask().
ui_hotkeys_arch_modifier_from_arch()
uint32_t ui_hotkeys_arch_modifier_from_arch (uint32_t arch_mod)
Translate arch modifier to VICE modifier.
Parameters
[in] arch_mod arch modifier
Returns
VICE modifier
Translate arch modifier to VICE modifier.
Parameters
[in] arch_mod GDK modifier mask bit
Returns
VICE modifier mask bit
Note
Returns different values on MacOS vs normal OSes.
Referenced by ui_hotkeys_arch_modmask_from_arch().
ui_hotkeys_arch_modifier_to_arch()
uint32_t ui_hotkeys_arch_modifier_to_arch (uint32_t vice_mod)
Translate VICE modifier to arch modifier.
Parameters
[in] vice_mod VICE modifier
Returns
arch modifier
Translate VICE modifier to arch modifier.
Get GDK modifier mask bit from VICE modifier mask bit
Parameters
[in] vice_mod VICE modifier mask bit
Returns
GDK modifier mask bit
Note
Only works on single-bit values, for combined values we'll need another (UI-agnostic) function.
Referenced by ui_hotkeys_arch_modmask_to_arch(), and vhk_parser_get_keysym_and_modmask().
ui_hotkeys_arch_modmask_from_arch()
uint32_t ui_hotkeys_arch_modmask_from_arch (uint32_t arch_modmask)
Translate arch modifier mask to VICE modifier mask.
Parameters
[in] arch_modmask arch modifier mask
Returns
VICE modifier mask
Translate arch modifier mask to VICE modifier mask.
Parameters
[in] arch_modmask Gdk modifier mask
Returns
VICE modifier mask
Todo:
We might be able to move this into shared/hotkeys, reducing the number of virtual methods required for a UI.
Referenced by dialog_accept_handler(), and ui_action_map_get_by_arch_hotkey().
ui_hotkeys_arch_modmask_to_arch()
uint32_t ui_hotkeys_arch_modmask_to_arch (uint32_t vice_modmask)
Translate VICE modifier mask to arch modifier.
Parameters
[in] vice_modmask VICE modifier mask
Returns
arch modifier mask
Translate VICE modifier mask to arch modifier.
Parameters
[in] vice_modmask VICE modifier mask
Returns
Gdk modifier mask
Todo:
We might be able to move this into shared/hotkeys, reducing the number of virtual methods required for a UI.
Referenced by ui_hotkeys_update_by_map().
ui_hotkeys_arch_remove_by_map()
void ui_hotkeys_arch_remove_by_map (ui_action_map_t * map)
Remove hotkey.
Remove hotkey from the UI. The map contains the keysym and modifier mask of the hotkey to remove. The shared hotkeys code will take care of removing the keysyms/modifier masks from map, the arch-specific code is expected to remove any accelerator (labels) from the UI and disconnecting any signal handlers connected for the hotkey.
Parameters
[in] map UI action map object
Remove hotkey.
Referenced by ui_hotkeys_remove_all(), ui_hotkeys_remove_by_map(), and ui_hotkeys_update_by_map().
ui_hotkeys_arch_shutdown()
void ui_hotkeys_arch_shutdown (void)
Run UI-specific hotkeys shutdown code.
This function is called in ui_hotkeys_shutdown() before any other cleanup happens, allowing UIs to do their own additional cleanup if required.
Run UI-specific hotkeys shutdown code.
Implements virtual method in uiapi.h that's called on generic hotkeys shut down. Frees the Gtk3-specific hotkey data in the generic hotkeys array.
Referenced by ui_hotkeys_shutdown().
ui_hotkeys_arch_update_by_map()
void ui_hotkeys_arch_update_by_map (ui_action_map_t * map, uint32_t vice_keysym, uint32_t vice_modmask)
Update hotkey.
The map should contain a valid action ID and the keysym and modmask of the currently registered hotkey for that action. The function is expected to remove the old hotkey from its menu items, if any, set the hotkey for the action to vice_keysym + vice_modmask, and if menu items are present update their accelator labels to the new hotkey. The generic hotkeys code takes care of updating the internals of map.
Parameters
[in] map UI action map object
[in] vice_keysym new VICE keysym
[in] vice_modmask new VICE modifier mask
ui_init()
int ui_init (void)
Initialize UI.
Loads gresource data, disables F10 as the accelerator for the menu bar, registers the CBM font with the host and initializes the statusbar.
Returns
0
Referenced by main_program().
ui_init_finalize()
int ui_init_finalize (void)
Finalize initialization after creating the main window(s)
Currently sets the proper state for the CHIPShowStatusbar toggle buttons since the resources aren't yet initialized when creating the menu structure(s) and the main window(s) is/are created.
Returns
0 on success, -1 on failure
Referenced by init_main().
ui_init_with_args()
void ui_init_with_args (int * argc, char ** argv)
Initialize Gtk3/GLib.
Parameters
[in] argc pointer to main()'s argc
[in] argv main()'s argv
Returns
0 on success, -1 on failure
Referenced by main_program().
ui_jam_dialog()
ui_jam_action_t ui_jam_dialog (const char * format, ...)
Show a CPU JAM dialog.
Show a CPU JAM dialog.
Parameters
[in] format format string for the message to display
Returns
the action the user selected in response to the jam
Referenced by drive_jam(), and machine_jam().
ui_message()
void ui_message (const char * format, ...)
Print a message.
Print a message.
Parameters
[in] format format string for message
Referenced by userport_set_device().
ui_resources_init()
int ui_resources_init (void)
Initialization
Initialization
Returns
0 on success, -1 on failure
Referenced by init_resources().
ui_resources_shutdown()
void ui_resources_shutdown (void)
Clean up memory used by VICE resources.
Referenced by cmdline_help(), and machine_shutdown().
ui_set_tape_status()
void ui_set_tape_status (int port, int tape_status)
Statusbar API function to report changes in tape status.
Parameters
tape_status The new tape status.
Note
This function does nothing and its API is not understood. Furthermore, no other extant UIs appear to react to this call.
ui_shutdown()
void ui_shutdown (void)
Clean up memory used by the UI system itself.
Referenced by cmdline_help(), and machine_shutdown().