x128: arch/gtk3/widgets/plus4memorysizewidget.c File Reference
plus4memorysizewidget.c File Reference
Plus4 memory size widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "plus4memorysizewidget.h"
Functions
GtkWidget * plus4_memory_size_widget_create (void)
Create Plus/4 memory size widget.
void plus4_memory_size_widget_add_callback (void(*callback)(GtkWidget *, int))
Set extra callback to trigger when the resource changes.
gboolean plus4_memory_size_widget_sync (void)
Synchronize the widget with its resource.
Variables
static const vice_gtk3_radiogroup_entry_t ram_sizes []
List of RAM sizes in KiB.
static GtkWidget * memory_size_widget = NULL
Reference to the memory size widget.
Detailed Description
Plus4 memory size widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
plus4_memory_size_widget_add_callback()
void plus4_memory_size_widget_add_callback (void(*)(GtkWidget *, int) callback)
Set extra callback to trigger when the resource changes.
Parameters
[in] callback function to trigger
Referenced by create_plus4_layout().
plus4_memory_size_widget_create()
GtkWidget * plus4_memory_size_widget_create (void)
Create Plus/4 memory size widget.
Returns
GtkGrid
Referenced by create_plus4_layout().
plus4_memory_size_widget_sync()
gboolean plus4_memory_size_widget_sync (void)
Synchronize the widget with its resource.
Returns
TRUE if the widget was synchronized
Referenced by machine_model_handler_plus4(), and plus4_mem_hack_callback().
Variable Documentation
memory_size_widget
GtkWidget* memory_size_widget = NULL static
Reference to the memory size widget.
Referenced by plus4_memory_size_widget_add_callback(), plus4_memory_size_widget_create(), and plus4_memory_size_widget_sync().
ram_sizes
const vice_gtk3_radiogroup_entry_t ram_sizes[] static
Initial value:
= {
    { "16KiB",  16 },
    { "32KiB",  32 },
    { "64KiB",  64 },
    { NULL,     -1 }
}
List of RAM sizes in KiB.
Referenced by plus4_memory_size_widget_create().