x128: fileio/cbmfile.c File Reference
cbmfile.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "archdep.h"
#include "cbmdos.h"
#include "charset.h"
#include "fileio.h"
#include "lib.h"
#include "rawfile.h"
#include "types.h"
#include "cbmfile.h"
Macros
#define DBG(x)
Functions
static char * cbmfile_find_file (const char *fsname, const char *path)
fileio_info_t * cbmfile_open (const char *file_name, const char *path, unsigned int command, unsigned int type)
void cbmfile_close (fileio_info_t *info)
unsigned int cbmfile_read (fileio_info_t *info, uint8_t *buf, unsigned int len)
unsigned int cbmfile_write (fileio_info_t *info, uint8_t *buf, unsigned int len)
unsigned int cbmfile_ferror (fileio_info_t *info)
unsigned int cbmfile_rename (const char *src_name, const char *dst_name, const char *path)
unsigned int cbmfile_scratch (const char *file_name, const char *path)
unsigned int cbmfile_get_bytes_left (struct fileio_info_s *info)
unsigned int cbmfile_seek (struct fileio_info_s *info, off_t offset, int whence)
unsigned int cbmfile_tell (struct fileio_info_s *info)
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
cbmfile_close()
void cbmfile_close (fileio_info_t * info)
Referenced by fileio_close().
cbmfile_ferror()
unsigned int cbmfile_ferror (fileio_info_t * info)
Referenced by fileio_ferror().
cbmfile_find_file()
static char * cbmfile_find_file (const char * fsname, const char * path) static
Referenced by cbmfile_open().
cbmfile_get_bytes_left()
unsigned int cbmfile_get_bytes_left (struct fileio_info_s * info)
Referenced by fileio_get_bytes_left().
cbmfile_open()
fileio_info_t * cbmfile_open (const char * file_name, const char * path, unsigned int command, unsigned int type)
Referenced by fileio_open().
cbmfile_read()
unsigned int cbmfile_read (fileio_info_t * info, uint8_t * buf, unsigned int len)
Referenced by fileio_read().
cbmfile_rename()
unsigned int cbmfile_rename (const char * src_name, const char * dst_name, const char * path)
Referenced by fileio_rename().
cbmfile_scratch()
unsigned int cbmfile_scratch (const char * file_name, const char * path)
Referenced by fileio_scratch().
cbmfile_seek()
unsigned int cbmfile_seek (struct fileio_info_s * info, off_t offset, int whence)
Referenced by fileio_seek().
cbmfile_tell()
unsigned int cbmfile_tell (struct fileio_info_s * info)
Referenced by fileio_tell().
cbmfile_write()
unsigned int cbmfile_write (fileio_info_t * info, uint8_t * buf, unsigned int len)
Referenced by fileio_write().