vsid: arch/gtk3/widgets/joystickautofirewidget.c File Reference
joystickautofirewidget.c File Reference
Widget to set joystick autofire resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "joystick.h"
#include "vice_gtk3.h"
#include "joystickautofirewidget.h"
Data Structures
struct coord_s
Coordinates of widgets in a grid.
Macros
#define ROW_TOP_BAR 0
rows of widgets in the main grid
#define ROW_MODE_LABEL 1
#define ROW_MODE_WIDGET 1
#define ROW_SPEED_LABEL 2
#define ROW_SPEED_WIDGET 2
#define COL_TOP_BAR 0
columns of widgets in the main grid
#define COL_MODE_LABEL 0
#define COL_MODE_WIDGET 1
#define COL_SPEED_LABEL 0
#define COL_SPEED_WIDGET 1
Typedefs
typedef struct coord_s coord_t
Coordinates of widgets in a grid.
Functions
static void set_widgets_sensitivity (GtkWidget *grid, gboolean sensitive)
Set sensitivity of the button mode and speed widgets.
static GtkWidget * create_label (const char *text)
Create left-aligned label using Pango markup.
static void on_autofire_notify_active (GtkWidget *widget, gpointer joy)
Handler for the 'notify:active' event of the autofire enable switch.
static GtkWidget * create_autofire_enable_widget (int joy)
Create widget to toggle autofire for a joystick.
static GtkWidget * create_autofire_mode_widget (int joy)
Create widget to set the autofire mode of a joystick.
static GtkWidget * create_autofire_speed_widget (int joy)
Create widget to set the autofire speed of a joystick.
GtkWidget * joystick_autofire_widget_create (int joy, const char *title)
Create widget to set autofire resources for a joystick.
Variables
static const coord_t coords []
Coordinates of widgets which will be enabled/disabled.
static const vice_gtk3_radiogroup_entry_t autofire_modes []
List of autofire modes.
Detailed Description
Widget to set joystick autofire resources.
Allows setting the autofire options for a joystick.
Three settings are available:
autofire enable (resource JoyStick[1-10]AutoFire)
autofire mode (resource JoyStick[1-10]AutoFireMode)
autofire speed (resource Joystick[1-10]AutoFireSpeed)
Autofire mode has two settings:
autofire when button is pressed (0)
autofire when button is not pressed (1)
Autofire speed is in button presses per second, with a range of 1-255 inclusive.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
COL_MODE_LABEL
#define COL_MODE_LABEL 0
COL_MODE_WIDGET
#define COL_MODE_WIDGET 1
COL_SPEED_LABEL
#define COL_SPEED_LABEL 0
COL_SPEED_WIDGET
#define COL_SPEED_WIDGET 1
COL_TOP_BAR
#define COL_TOP_BAR 0
columns of widgets in the main grid
ROW_MODE_LABEL
#define ROW_MODE_LABEL 1
ROW_MODE_WIDGET
#define ROW_MODE_WIDGET 1
ROW_SPEED_LABEL
#define ROW_SPEED_LABEL 2
ROW_SPEED_WIDGET
#define ROW_SPEED_WIDGET 2
ROW_TOP_BAR
#define ROW_TOP_BAR 0
rows of widgets in the main grid
Typedef Documentation
coord_t
typedef struct coord_s coord_t
Coordinates of widgets in a grid.
Function Documentation
create_autofire_enable_widget()
static GtkWidget * create_autofire_enable_widget (int joy) static
Create widget to toggle autofire for a joystick.
Parameters
[in] joy joystick number (1-10)
Returns
GtkSwitch
Referenced by joystick_autofire_widget_create().
create_autofire_mode_widget()
static GtkWidget * create_autofire_mode_widget (int joy) static
Create widget to set the autofire mode of a joystick.
Parameters
[in] joy joystick number (1-10)
Returns
GtkGrid
Referenced by joystick_autofire_widget_create().
create_autofire_speed_widget()
static GtkWidget * create_autofire_speed_widget (int joy) static
Create widget to set the autofire speed of a joystick.
Parameters
[in] joy joystick number (1-10)
Returns
GtkScale
Referenced by joystick_autofire_widget_create().
create_label()
static GtkWidget * create_label (const char * text) static
Create left-aligned label using Pango markup.
Parameters
[in] text label text
Returns
GtkLabel
Referenced by joystick_autofire_widget_create().
joystick_autofire_widget_create()
GtkWidget * joystick_autofire_widget_create (int joy, const char * title)
Create widget to set autofire resources for a joystick.
Parameters
[in] joy joystick number in the resource names (1-10)
[in] title title for the widget
Returns
GtkGrid
Referenced by add_userport_widgets(), create_c64_layout(), create_plus4_layout(), and create_vic20_layout().
on_autofire_notify_active()
static void on_autofire_notify_active (GtkWidget * widget, gpointer joy) static
Handler for the 'notify:active' event of the autofire enable switch.
Extra event handler for setting the other widgets' sensitivity base on the state of the switch.
Parameters
[in] widget autofire enable switch
[in] joy joyport number (unused)
Referenced by create_autofire_enable_widget().
set_widgets_sensitivity()
static void set_widgets_sensitivity (GtkWidget * grid, gboolean sensitive) static
Set sensitivity of the button mode and speed widgets.
Parameters
[in] grid autofire settings grid
[in] sensitive sensitivity for the widgets
Referenced by joystick_autofire_widget_create(), and on_autofire_notify_active().
Variable Documentation
autofire_modes
const vice_gtk3_radiogroup_entry_t autofire_modes[] static
Initial value:
= {
    { "Pressed",     JOYSTICK_AUTOFIRE_MODE_PRESS },
    { "Released",    JOYSTICK_AUTOFIRE_MODE_PERMANENT },
     { NULL, -1 }
}
List of autofire modes.
Note
Currently only two modes, so perhaps a different widget can be used, such as a switch or toggle button?
Referenced by create_autofire_mode_widget().
coords
const coord_t coords[] static
Initial value:
= {
    {  0 ,    1  },
    {  1 ,   1  },
    {  0 ,   2  },
    {  1 ,  2  }
}
Coordinates of widgets which will be enabled/disabled.
Might seem overkill, but when the layout changes again, this should make things a bit easier.
Referenced by set_widgets_sensitivity().