vsid: arch/gtk3/widgets/hvscstilwidget.c File Reference
hvscstilwidget.c File Reference
High Voltage SID Collection STIL widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "debug_gtk3.h"
#include "hvsc.h"
#include "resources.h"
#include "ui.h"
#include "vice_gtk3.h"
#include "vsidtuneinfowidget.h"
#include "hvscstilwidget.h"
Functions
static void hvsc_stil_widget_create_tags (void)
Create tags for the textview displaying info on a SID via STIL.
static GtkWidget * create_view (void)
Create TextView widget for the STIL entry text.
GtkWidget * hvsc_stil_widget_create (void)
Create HVSC STIL widget.
static gboolean stil_widget_populate (hvsc_stil_t *stil)
static void stil_widget_show_error (void)
gboolean hvsc_stil_widget_set_psid (const char *filename)
Set new PSID file.
gboolean hvsc_stil_widget_set_psid_md5 (const char *digest)
Set new PSID fill.
GtkWidget * hvsc_stil_widget_get_view (void)
Return reference to the view.
Variables
static GtkWidget * stil_view
GtkTextArea used to present the STIL entry.
Detailed Description
High Voltage SID Collection STIL widget.
Widget providing access to the SID Tune Information List, a document containing extra information of SID tunes (author comments, trivia, which songs were covered (if any)).
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_view()
static GtkWidget * create_view (void) static
Create TextView widget for the STIL entry text.
Returns
GtkTextView
Referenced by hvsc_stil_widget_create().
hvsc_stil_widget_create()
GtkWidget * hvsc_stil_widget_create (void)
Create HVSC STIL widget.
Returns
GtkGrid
Referenced by vsid_main_widget_create().
hvsc_stil_widget_create_tags()
static void hvsc_stil_widget_create_tags (void) static
Create tags for the textview displaying info on a SID via STIL.
Referenced by hvsc_stil_widget_create().
hvsc_stil_widget_get_view()
GtkWidget * hvsc_stil_widget_get_view (void)
Return reference to the view.
This is currently required to make drag-n-drop on the STIL widget work
Returns
view
Referenced by on_drag_data_received(), and vsid_main_widget_create().
hvsc_stil_widget_set_psid()
gboolean hvsc_stil_widget_set_psid (const char * filename)
Set new PSID file.
Parameters
[in] psid path to .sid file
Returns
TRUE if a STIL entry was found
hvsc_stil_widget_set_psid_md5()
gboolean hvsc_stil_widget_set_psid_md5 (const char * digest)
Set new PSID fill.
Parameters
[in] digest md5 digest of .sid file
Returns
TRUE if a STIL entry was found
Referenced by ui_vsid_window_load_psid(), and vsid_main_widget_create().
stil_widget_populate()
static gboolean stil_widget_populate (hvsc_stil_t * stil) static
Todo:
FIXME: might be a bug in my HVSC 'lib'
Referenced by hvsc_stil_widget_set_psid(), and hvsc_stil_widget_set_psid_md5().
stil_widget_show_error()
static void stil_widget_show_error (void) static
Referenced by hvsc_stil_widget_set_psid(), and hvsc_stil_widget_set_psid_md5().
Variable Documentation
stil_view
GtkWidget* stil_view static
GtkTextArea used to present the STIL entry.
Referenced by hvsc_stil_widget_create(), hvsc_stil_widget_create_tags(), hvsc_stil_widget_get_view(), stil_widget_populate(), and stil_widget_show_error().