vsid: arch/gtk3/widgets/settings_ramlink.c File Reference
settings_ramlink.c File Reference
Settings widget to control RAMLink resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "carthelpers.h"
#include "cartridge.h"
#include "debug_gtk3.h"
#include "log.h"
#include "ramlink.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "settings_ramlink.h"
Macros
#define CARTNAME CARTRIDGE_NAME_RAMLINK
Temporary define to ease typing and copy/paste.
Functions
static GtkWidget * label_helper (const char *text)
Create left-aligned label with Pango markup.
static void on_enable_toggled (GtkWidget *widget, gpointer data)
Handler for the 'toggled' event of the 'enable' check button.
static GtkWidget * create_primary_image_widget (void)
Create RAMLink BIOS image widget.
static GtkWidget * create_secondary_image_widget (void)
Create RAMLink RAM image widget.
GtkWidget * settings_ramlink_widget_create (GtkWidget *parent)
Create RAMLink widget.
Variables
static const vice_gtk3_radiogroup_entry_t ramlink_modes []
RAMLINK modes.
Detailed Description
Settings widget to control RAMLink resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
CARTNAME
#define CARTNAME CARTRIDGE_NAME_RAMLINK
Temporary define to ease typing and copy/paste.
Function Documentation
create_primary_image_widget()
static GtkWidget * create_primary_image_widget (void) static
Create RAMLink BIOS image widget.
Returns
GtkGrid
< ramlink.c
Referenced by settings_ramlink_widget_create().
create_secondary_image_widget()
static GtkWidget * create_secondary_image_widget (void) static
Create RAMLink RAM image widget.
Returns
GtkGrid
< ramlink.c
Referenced by settings_ramlink_widget_create().
label_helper()
static GtkWidget * label_helper (const char * text) static
Create left-aligned label with Pango markup.
Parameters
[in] text label text (uses Pango markup)
Returns
GtkLabel
Referenced by settings_ramlink_widget_create().
on_enable_toggled()
static void on_enable_toggled (GtkWidget * widget, gpointer data) static
Handler for the 'toggled' event of the 'enable' check button.
Toggles the 'enabled' state of the RAMlink adapter/cart, but only if a ROM image has been specified, otherwise when trying to set the check button to 'true', an error message is displayed and the check button is reverted to 'off'.
Parameters
[in,out] widget check button
[in] data unused
< ramlink.c
< ramlink.c
Referenced by settings_ramlink_widget_create().
settings_ramlink_widget_create()
GtkWidget * settings_ramlink_widget_create (GtkWidget * parent)
Create RAMLink widget.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
< ramlink.c
Variable Documentation
ramlink_modes
const vice_gtk3_radiogroup_entry_t ramlink_modes[] static
Initial value:
= {
    { "Normal",   RL_MODE_NORMAL },
    { "Direct",   RL_MODE_DIRECT },
    { NULL,      -1 }
}
RAMLINK modes.
Referenced by settings_ramlink_widget_create().