vsid: arch/gtk3/opengl_renderer.c File Reference
opengl_renderer.c File Reference
OpenGL renderer for the GTK3 backend.
#include "vice.h"
#include "opengl_renderer.h"
#include <assert.h>
#include <gtk/gtk.h>
#include <math.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "monitor.h"
#include "palette.h"
#include "render_queue.h"
#include "resources.h"
#include "sysfile.h"
#include "ui.h"
#include "uistatusbar.h"
#include "util.h"
#include "vsync.h"
#include "vsyncapi.h"
Macros
#define CANVAS_LOCK() pthread_mutex_lock(&canvas->lock)
#define CANVAS_UNLOCK() pthread_mutex_unlock(&canvas->lock)
#define RENDER_LOCK() pthread_mutex_lock(&context->render_lock)
#define RENDER_UNLOCK() pthread_mutex_unlock(&context->render_lock)
Typedefs
typedef vice_opengl_renderer_context_t context_t
Functions
static void on_widget_realized (GtkWidget *widget, gpointer data)
static void on_widget_unrealized (GtkWidget *widget, gpointer data)
static void on_widget_resized (GtkWidget *widget, GdkRectangle *allocation, gpointer data)
static void on_widget_monitors_changed (GdkScreen *screen, gpointer data)
static void render (void *job_data, void *pool_data)
static GLuint create_shader (GLenum shader_type, const char *text)
Compile a shader.
static GLuint create_shader_program (char *vertex_shader_filename, char *fragment_shader_filename)
Compile and return a gl program for the given vertext and fragment shader files.
static void vice_opengl_initialise_canvas (video_canvas_t *canvas)
static void vice_opengl_destroy_context (video_canvas_t *canvas)
static void on_widget_resized (GtkWidget *widget, GtkAllocation *allocation, gpointer data)
The underlying GtkDrawingArea has changed size (possibly before being realised)
static void invoke_widget_layout (video_canvas_t *canvas)
static void vice_opengl_update_context (video_canvas_t *canvas, unsigned int width, unsigned int height)
The emulated screen size or aspect ratio has changed.
static void vice_opengl_refresh_rect (video_canvas_t *canvas, unsigned int xs, unsigned int ys, unsigned int xi, unsigned int yi, unsigned int w, unsigned int h)
It's time to draw a complete emulated frame.
static void vice_opengl_on_ui_frame_clock (GdkFrameClock *clock, video_canvas_t *canvas)
static void update_frame_textures (context_t *context, backbuffer_t *backbuffer)
static void legacy_render (video_canvas_t *canvas, float scale_x, float scale_y)
static void modern_render (video_canvas_t *canvas, float scale_x, float scale_y)
static void vice_opengl_set_palette (video_canvas_t *canvas)
Variables
static float vertexData []
Raw geometry for the machine screen.
vice_renderer_backend_t vice_opengl_backend
A renderer that uses OpenGL to render to a native child window.
Detailed Description
OpenGL renderer for the GTK3 backend.
Author
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
David Hogan david.nosp@m..q.h.nosp@m.ogan@.nosp@m.gmai.nosp@m.l.com
Macro Definition Documentation
CANVAS_LOCK
#define CANVAS_LOCK () pthread_mutex_lock(&canvas->lock)
CANVAS_UNLOCK
#define CANVAS_UNLOCK () pthread_mutex_unlock(&canvas->lock)
RENDER_LOCK
#define RENDER_LOCK () pthread_mutex_lock(&context->render_lock)
RENDER_UNLOCK
#define RENDER_UNLOCK () pthread_mutex_unlock(&context->render_lock)
Typedef Documentation
context_t
typedef vice_opengl_renderer_context_t context_t
Function Documentation
create_shader()
static GLuint create_shader (GLenum shader_type, const char * text) static
Compile a shader.
If the shader cannot be compiled, error messages from OpenGL will be dumped to stdout.
Parameters
shader_type The kind of shader being compiled. Must be either GL_VERTEX_SHADER or GL_FRAGMENT_SHADER.
text The shader source.
Returns
The identifier of the shader.
Referenced by create_shader_program().
create_shader_program()
static GLuint create_shader_program (char * vertex_shader_filename, char * fragment_shader_filename) static
Compile and return a gl program for the given vertext and fragment shader files.
Referenced by on_widget_realized().
invoke_widget_layout()
static void invoke_widget_layout (video_canvas_t * canvas) static
Referenced by on_widget_monitors_changed().
legacy_render()
static void legacy_render (video_canvas_t * canvas, float scale_x, float scale_y) static
Todo:
FIXME: add support for flipx/flipy/rotate
Referenced by render().
modern_render()
static void modern_render (video_canvas_t * canvas, float scale_x, float scale_y) static
Todo:
FIXME: add support for flipx/flipy/rotate
Referenced by render().
on_widget_monitors_changed()
static void on_widget_monitors_changed (GdkScreen * screen, gpointer data) static
Referenced by on_widget_realized(), and on_widget_unrealized().
on_widget_realized()
static void on_widget_realized (GtkWidget * widget, gpointer data) static
Referenced by vice_opengl_initialise_canvas().
on_widget_resized() [1/2]
static void on_widget_resized (GtkWidget * widget, GdkRectangle * allocation, gpointer data) static
Referenced by invoke_widget_layout(), and vice_opengl_initialise_canvas().
on_widget_resized() [2/2]
static void on_widget_resized (GtkWidget * widget, GtkAllocation * allocation, gpointer data) static
The underlying GtkDrawingArea has changed size (possibly before being realised)
on_widget_unrealized()
static void on_widget_unrealized (GtkWidget * widget, gpointer data) static
Referenced by vice_opengl_initialise_canvas().
render()
static void render (void * job_data, void * pool_data) static
Todo:
BSD thread prio stuff
Referenced by create_layout(), on_widget_realized(), and video_render_filter_widget_create().
update_frame_textures()
static void update_frame_textures (context_t * context, backbuffer_t * backbuffer) static
Referenced by render().
vice_opengl_destroy_context()
static void vice_opengl_destroy_context (video_canvas_t * canvas) static
vice_opengl_initialise_canvas()
static void vice_opengl_initialise_canvas (video_canvas_t * canvas) static
vice_opengl_on_ui_frame_clock()
static void vice_opengl_on_ui_frame_clock (GdkFrameClock * clock, video_canvas_t * canvas) static
vice_opengl_refresh_rect()
static void vice_opengl_refresh_rect (video_canvas_t * canvas, unsigned int xs, unsigned int ys, unsigned int xi, unsigned int yi, unsigned int w, unsigned int h) static
It's time to draw a complete emulated frame.
vice_opengl_set_palette()
static void vice_opengl_set_palette (video_canvas_t * canvas) static
vice_opengl_update_context()
static void vice_opengl_update_context (video_canvas_t * canvas, unsigned int width, unsigned int height) static
The emulated screen size or aspect ratio has changed.
Variable Documentation
vertexData
float vertexData[] static
Initial value:
= {
        -1.0f, -1.0f, 0.0f, 1.0f,
         1.0f, -1.0f, 0.0f, 1.0f,
        -1.0f,  1.0f, 0.0f, 1.0f,
         1.0f,  1.0f, 0.0f, 1.0f,
        0.0f,  1.0f,
        1.0f,  1.0f,
        0.0f,  0.0f,
        1.0f,  0.0f
}
Raw geometry for the machine screen.
The first sixteen elements describe a rectangle the size of the entire display area, and the last eight assign texture coordinates to each corner.
Referenced by on_widget_realized().
vice_opengl_backend
vice_renderer_backend_t vice_opengl_backend
Initial value:
= {
    vice_opengl_initialise_canvas,
    vice_opengl_update_context,
    vice_opengl_destroy_context,
    vice_opengl_refresh_rect,
    vice_opengl_on_ui_frame_clock,
    vice_opengl_set_palette
}
A renderer that uses OpenGL to render to a native child window.
Because OpenGL + GTK3 just doesn't work that well, this.
Referenced by machine_window_create().