vsid: parallel.h File Reference
parallel.h File Reference
#include "types.h"
Macros
#define PARALLEL_EMU 0x01
Each device has a mask bit in the parallel_* handshake lines.
#define PARALLEL_CPU 0x02
#define PARALLEL_DRV0 0x04
#define PARALLEL_DRV1 0x08
#define PARALLEL_DRV2 0x10
#define PARALLEL_DRV3 0x20
#define PARALLEL_SET_LINE(line, dev, mask)
methods to set output lines for the computer
#define PARALLEL_RESTORE_LINE(line, dev, mask)
Functions
void parallel_bus_enable (unsigned int unit, unsigned int enable)
to switch on/off IEEE488 filesystem engine
void parallel_trap_eof_callback_set (void(*func)(void))
Specify a function to call when EOF happens in ‘serialreceivebyte()’.
void parallel_trap_attention_callback_set (void(*func)(void))
Specify a function to call when the ‘serialattention()’ trap is called.
void parallel_set_eoi (uint8_t mask)
methods to set handshake lines active for the devices
void parallel_set_ndac (uint8_t mask)
void parallel_set_nrfd (uint8_t mask)
void parallel_set_dav (uint8_t mask)
void parallel_set_atn (uint8_t mask)
void parallel_restore_set_atn (uint8_t mask)
void parallel_clr_eoi (uint8_t mask)
methods to set handshake lines inactive for the devices
void parallel_clr_ndac (uint8_t mask)
void parallel_clr_nrfd (uint8_t mask)
void parallel_clr_dav (uint8_t mask)
void parallel_clr_atn (uint8_t mask)
void parallel_restore_clr_atn (uint8_t mask)
static void parallel_emu_set_eoi (uint8_t val)
Emulator functions.
static void parallel_emu_set_dav (uint8_t val)
static void parallel_emu_set_nrfd (uint8_t val)
static void parallel_emu_set_ndac (uint8_t val)
void parallel_emu_set_bus (uint8_t b)
static void parallel_cpu_set_eoi (uint8_t val)
CPU functions.
static void parallel_cpu_set_dav (uint8_t val)
static void parallel_cpu_set_nrfd (uint8_t val)
static void parallel_cpu_set_ndac (uint8_t val)
void parallel_cpu_set_atn (char val)
static void parallel_cpu_restore_atn (uint8_t val)
void parallel_cpu_set_bus (uint8_t b)
static void parallel_drv0_set_eoi (uint8_t val)
Drive 0 functions.
static void parallel_drv0_set_dav (uint8_t val)
static void parallel_drv0_set_nrfd (uint8_t val)
static void parallel_drv0_set_ndac (uint8_t val)
void parallel_drv0_set_bus (uint8_t b)
static void parallel_drv1_set_eoi (uint8_t val)
Drive 1 functions.
static void parallel_drv1_set_dav (uint8_t val)
static void parallel_drv1_set_nrfd (uint8_t val)
static void parallel_drv1_set_ndac (uint8_t val)
void parallel_drv1_set_bus (uint8_t b)
static void parallel_drv2_set_eoi (uint8_t val)
Drive 2 functions.
static void parallel_drv2_set_dav (uint8_t val)
static void parallel_drv2_set_nrfd (uint8_t val)
static void parallel_drv2_set_ndac (uint8_t val)
void parallel_drv2_set_bus (uint8_t b)
static void parallel_drv3_set_eoi (uint8_t val)
Drive 3 functions.
static void parallel_drv3_set_dav (uint8_t val)
static void parallel_drv3_set_nrfd (uint8_t val)
static void parallel_drv3_set_ndac (uint8_t val)
void parallel_drv3_set_bus (uint8_t b)
Variables
uint8_t parallel_eoi
state of the bus lines -> "if (parallel_eoi) { eoi is active }"
uint8_t parallel_ndac
uint8_t parallel_nrfd
uint8_t parallel_dav
uint8_t parallel_atn
uint8_t parallel_bus
Macro Definition Documentation
PARALLEL_CPU
#define PARALLEL_CPU 0x02
PARALLEL_DRV0
#define PARALLEL_DRV0 0x04
PARALLEL_DRV1
#define PARALLEL_DRV1 0x08
PARALLEL_DRV2
#define PARALLEL_DRV2 0x10
PARALLEL_DRV3
#define PARALLEL_DRV3 0x20
PARALLEL_EMU
#define PARALLEL_EMU 0x01
Each device has a mask bit in the parallel_* handshake lines.
PARALLEL_RESTORE_LINE
#define PARALLEL_RESTORE_LINE (line, dev, mask)
Value:
    static inline void parallel_##dev##_restore_##line(uint8_t val)  \
    {                                                             \
        if (val) {                                                \
            parallel_restore_set_##line(PARALLEL_##mask);         \
        } else {                                                  \
            parallel_restore_clr_##line(~PARALLEL_##mask);        \
        }                                                         \
    }
PARALLEL_SET_LINE
#define PARALLEL_SET_LINE (line, dev, mask)
Value:
    static inline void parallel_##dev##_set_##line(uint8_t val) \
    {                                                        \
        if (val) {                                           \
            parallel_set_##line(PARALLEL_##mask);            \
        } else {                                             \
            parallel_clr_##line(~PARALLEL_##mask);           \
        }                                                    \
    }
methods to set output lines for the computer
Function Documentation
parallel_bus_enable()
void parallel_bus_enable (unsigned int unit, unsigned int enable)
to switch on/off IEEE488 filesystem engine
Referenced by machine_bus_status_virtualdevices_set().
parallel_clr_atn()
void parallel_clr_atn (uint8_t mask)
parallel_clr_dav()
void parallel_clr_dav (uint8_t mask)
parallel_clr_eoi()
void parallel_clr_eoi (uint8_t mask)
methods to set handshake lines inactive for the devices
parallel_clr_ndac()
void parallel_clr_ndac (uint8_t mask)
parallel_clr_nrfd()
void parallel_clr_nrfd (uint8_t mask)
parallel_cpu_restore_atn()
static void parallel_cpu_restore_atn (uint8_t val) inline static
parallel_cpu_set_atn()
void parallel_cpu_set_atn (char val)
parallel_cpu_set_bus()
void parallel_cpu_set_bus (uint8_t b)
parallel_cpu_set_dav()
static void parallel_cpu_set_dav (uint8_t val) inline static
parallel_cpu_set_eoi()
static void parallel_cpu_set_eoi (uint8_t val) inline static
CPU functions.
parallel_cpu_set_ndac()
static void parallel_cpu_set_ndac (uint8_t val) inline static
parallel_cpu_set_nrfd()
static void parallel_cpu_set_nrfd (uint8_t val) inline static
parallel_drv0_set_bus()
void parallel_drv0_set_bus (uint8_t b)
parallel_drv0_set_dav()
static void parallel_drv0_set_dav (uint8_t val) inline static
parallel_drv0_set_eoi()
static void parallel_drv0_set_eoi (uint8_t val) inline static
Drive 0 functions.
parallel_drv0_set_ndac()
static void parallel_drv0_set_ndac (uint8_t val) inline static
parallel_drv0_set_nrfd()
static void parallel_drv0_set_nrfd (uint8_t val) inline static
parallel_drv1_set_bus()
void parallel_drv1_set_bus (uint8_t b)
parallel_drv1_set_dav()
static void parallel_drv1_set_dav (uint8_t val) inline static
parallel_drv1_set_eoi()
static void parallel_drv1_set_eoi (uint8_t val) inline static
Drive 1 functions.
parallel_drv1_set_ndac()
static void parallel_drv1_set_ndac (uint8_t val) inline static
parallel_drv1_set_nrfd()
static void parallel_drv1_set_nrfd (uint8_t val) inline static
parallel_drv2_set_bus()
void parallel_drv2_set_bus (uint8_t b)
parallel_drv2_set_dav()
static void parallel_drv2_set_dav (uint8_t val) inline static
parallel_drv2_set_eoi()
static void parallel_drv2_set_eoi (uint8_t val) inline static
Drive 2 functions.
parallel_drv2_set_ndac()
static void parallel_drv2_set_ndac (uint8_t val) inline static
parallel_drv2_set_nrfd()
static void parallel_drv2_set_nrfd (uint8_t val) inline static
parallel_drv3_set_bus()
void parallel_drv3_set_bus (uint8_t b)
parallel_drv3_set_dav()
static void parallel_drv3_set_dav (uint8_t val) inline static
parallel_drv3_set_eoi()
static void parallel_drv3_set_eoi (uint8_t val) inline static
Drive 3 functions.
parallel_drv3_set_ndac()
static void parallel_drv3_set_ndac (uint8_t val) inline static
parallel_drv3_set_nrfd()
static void parallel_drv3_set_nrfd (uint8_t val) inline static
parallel_emu_set_bus()
void parallel_emu_set_bus (uint8_t b)
Referenced by Out1_NRFD_false(), Out2_NDAC_false(), ResetBus(), and WATN_ATN_true().
parallel_emu_set_dav()
static void parallel_emu_set_dav (uint8_t val) inline static
Referenced by Out1_NRFD_false(), Out2_NDAC_false(), ResetBus(), and WATN_ATN_true().
parallel_emu_set_eoi()
static void parallel_emu_set_eoi (uint8_t val) inline static
Emulator functions.
Referenced by Out1_NRFD_false(), Out2_NDAC_false(), ResetBus(), and WATN_ATN_true().
parallel_emu_set_ndac()
static void parallel_emu_set_ndac (uint8_t val) inline static
Referenced by In1_DAV_true(), In2_DAV_false(), ResetBus(), and WATN_ATN_true().
parallel_emu_set_nrfd()
static void parallel_emu_set_nrfd (uint8_t val) inline static
Referenced by In1_DAV_true(), In2_DAV_false(), ResetBus(), and WATN_ATN_true().
parallel_restore_clr_atn()
void parallel_restore_clr_atn (uint8_t mask)
parallel_restore_set_atn()
void parallel_restore_set_atn (uint8_t mask)
parallel_set_atn()
void parallel_set_atn (uint8_t mask)
< active low: 0 on the physical bus
< active low: 0 on the physical bus
parallel_set_dav()
void parallel_set_dav (uint8_t mask)
< active low: 0 on the physical bus
< active low: 0 on the physical bus
parallel_set_eoi()
void parallel_set_eoi (uint8_t mask)
methods to set handshake lines active for the devices
parallel_set_ndac()
void parallel_set_ndac (uint8_t mask)
< active low: 0 on the physical bus
< active low: 0 on the physical bus
parallel_set_nrfd()
void parallel_set_nrfd (uint8_t mask)
< active low: 0 on the physical bus
< active low: 0 on the physical bus
parallel_trap_attention_callback_set()
void parallel_trap_attention_callback_set (void(*)(void) func)
Specify a function to call when the ‘serialattention()’ trap is called.
Referenced by machine_bus_attention_callback_set().
parallel_trap_eof_callback_set()
void parallel_trap_eof_callback_set (void(*)(void) func)
Specify a function to call when EOF happens in ‘serialreceivebyte()’.
Referenced by machine_bus_eof_callback_set().
Variable Documentation
parallel_atn
uint8_t parallel_atn extern
Referenced by In1_DAV_true(), In1_NDAC_true(), In1_NRFD_false(), In1_NRFD_true(), In2_NDAC_false(), parallel_clr_atn(), parallel_restore_clr_atn(), parallel_restore_set_atn(), and parallel_set_atn().
parallel_bus
uint8_t parallel_bus extern
Referenced by In1_DAV_true(), parallel_cpu_set_bus(), parallel_drv0_set_bus(), parallel_drv1_set_bus(), parallel_drv2_set_bus(), parallel_drv3_set_bus(), and parallel_emu_set_bus().
parallel_dav
uint8_t parallel_dav extern
Referenced by parallel_clr_dav(), and parallel_set_dav().
parallel_eoi
uint8_t parallel_eoi extern
state of the bus lines -> "if (parallel_eoi) { eoi is active }"
Referenced by parallel_clr_eoi(), and parallel_set_eoi().
parallel_ndac
uint8_t parallel_ndac extern
Referenced by In1_ATN_false(), parallel_clr_ndac(), and parallel_set_ndac().
parallel_nrfd
uint8_t parallel_nrfd extern
Referenced by OPet_NDAC_true(), parallel_clr_nrfd(), and parallel_set_nrfd().