vsid: monitor.h File Reference
monitor.h File Reference
#include "types.h"
#include "monitor/asm.h"
Data Structures
struct monitor_cpu_type_s
struct supported_cpu_type_list_s
struct monitor_interface_s
struct monitor_cartridge_commands_s
Macros
#define NUM_MEMSPACES e_invalid_space
Generic interface.
#define FIRST_SPACE e_comp_space
#define LAST_SPACE e_disk11_space
#define MONITOR_MAX_CHECKPOINTS 9
Breakpoint interface.
#define MEMMAP_UNINITIALIZED_EXEC (1 << 11)
memmap defines
#define MEMMAP_UNINITIALIZED_READ (1 << 10)
was read before written to
#define MEMMAP_REGULAR_READ (1 << 9)
NOT just a dummy read.
#define MEMMAP_I_O_R (1 << 8)
#define MEMMAP_I_O_W (1 << 7)
#define MEMMAP_I_O_X (1 << 6)
#define MEMMAP_ROM_R (1 << 5)
#define MEMMAP_ROM_W (1 << 4)
#define MEMMAP_ROM_X (1 << 3)
#define MEMMAP_RAM_R (1 << 2)
#define MEMMAP_RAM_W (1 << 1)
#define MEMMAP_RAM_X (1 << 0)
#define MEMMAP_STATE_OPCODE 0x01
#define MEMMAP_STATE_INSTR 0x02
#define MEMMAP_STATE_IGNORE 0x04
#define MEMMAP_STATE_IN_MONITOR 0x08
Typedefs
typedef enum t_memspace MEMSPACE
typedef enum CPU_TYPE_s CPU_TYPE_t
typedef struct monitor_cpu_type_s monitor_cpu_type_t
typedef struct supported_cpu_type_list_s supported_cpu_type_list_t
typedef struct monitor_interface_s monitor_interface_t
typedef struct monitor_cartridge_commands_s monitor_cartridge_commands_t
Enumerations
enum mon_int {
MI_NONE = 0 ,
MI_BREAK = 1 << 0 ,
MI_WATCH = 1 << 1 ,
MI_STEP = 1 << 2
}
enum t_memspace {
e_default_space = 0 ,
e_comp_space ,
e_disk8_space ,
e_disk9_space ,
e_disk10_space ,
e_disk11_space ,
e_invalid_space
}
enum CPU_TYPE_s {
CPU_6502 ,
CPU_WDC65C02 ,
CPU_R65C02 ,
CPU_65SC02 ,
CPU_65816 ,
CPU_Z80 ,
CPU_6502DTV ,
CPU_6809
}
Functions
monitor_cpu_type_t * monitor_find_cpu_type_from_string (const char *cpu_type)
Prototypes.
void monitor_init (monitor_interface_t *maincpu_interface, monitor_interface_t *drive_interface_init[], struct monitor_cpu_type_s **asmarray)
void monitor_shutdown (void)
int monitor_cmdline_options_init (void)
int monitor_resources_init (void)
void monitor_resources_shutdown (void)
void monitor_startup (MEMSPACE mem)
void monitor_startup_trap (void)
bool monitor_is_inside_monitor (void)
void monitor_reset_hook (void)
void monitor_vsync_hook (void)
void monitor_abort (void)
void monitor_check_icount (uint16_t a)
*** CPU INTERFACES ***
void monitor_check_icount_interrupt (void)
called by cpu core
void monitor_check_watchpoints (unsigned int lastpc, unsigned int pc)
called by macro DO_INTERRUPT() in 6510(dtv)core.c
void monitor_cpu_type_set (const char *cpu_type)
void monitor_cpu_type_set_value (int searchcpu)
basically above code but faster as the type is passed; used by x128
void monitor_watch_push_load_addr (uint16_t addr, MEMSPACE mem)
*** WATCHPOINTS ***
void monitor_watch_push_store_addr (uint16_t addr, MEMSPACE mem)
monitor_interface_t * monitor_interface_new (void)
void monitor_interface_destroy (monitor_interface_t *monitor_interface)
int monitor_diskspace_dnr (int mem)
int monitor_diskspace_mem (int dnr)
int mon_out (const char *format,...)
int mon_petscii_out (int maxlen, const char *format,...)
int mon_petscii_upper_out (int maxlen, const char *format,...)
int mon_scrcode_out (int maxlen, const char *format,...)
int mon_scrcode_upper_out (int maxlen, const char *format,...)
int monitor_check_breakpoints (MEMSPACE mem, uint16_t addr)
Prototypes.
const char * mon_disassemble_to_string (MEMSPACE, unsigned int addr, unsigned int x, unsigned int p1, unsigned int p2, unsigned int p3, int hex_mode, const char *cpu_type)
Disassemble interace.
unsigned mon_disassemble_oneline (MEMSPACE memspace, uint16_t mem_config, uint16_t addr)
struct mon_reg_list_s * mon_register_list_get (int mem)
Register interface.
void mon_ioreg_add_list (struct mem_ioreg_list_s **list, const char *name, int start, int end, void *dump, void *context, int mirror_mode)
void asm6502_init (struct monitor_cpu_type_s *monitor_cpu_type)
Assembler initialization.
void asmR65C02_init (struct monitor_cpu_type_s *monitor_cpu_type)
void asm65816_init (struct monitor_cpu_type_s *monitor_cpu_type)
void asm6502dtv_init (struct monitor_cpu_type_s *monitor_cpu_type)
void asm6809_init (struct monitor_cpu_type_s *monitor_cpu_type)
void asmz80_init (struct monitor_cpu_type_s *monitor_cpu_type)
void monitor_cpuhistory_store (CLOCK cycle, unsigned int addr, unsigned int op, unsigned int p1, unsigned int p2, uint8_t reg_a, uint8_t reg_x, uint8_t reg_y, uint8_t reg_sp, unsigned int reg_st, MEMSPACE origin)
CPU history/memmap prototypes.
void monitor_cpuhistory_fix_p2 (unsigned int p2)
void monitor_memmap_store (unsigned int addr, unsigned int type)
Variables
supported_cpu_type_list_t * monitor_cpu_type_supported [e_invalid_space]
A linked list of supported monitor_cpu_types for each memspace.
unsigned monitor_mask [e_invalid_space]
Externals.
monitor_cartridge_commands_t mon_cart_cmd
uint8_t memmap_state
HACK to enable fetch/load separation.
Macro Definition Documentation
FIRST_SPACE
#define FIRST_SPACE e_comp_space
LAST_SPACE
#define LAST_SPACE e_disk11_space
MEMMAP_I_O_R
#define MEMMAP_I_O_R (1 << 8)
MEMMAP_I_O_W
#define MEMMAP_I_O_W (1 << 7)
MEMMAP_I_O_X
#define MEMMAP_I_O_X (1 << 6)
MEMMAP_RAM_R
#define MEMMAP_RAM_R (1 << 2)
MEMMAP_RAM_W
#define MEMMAP_RAM_W (1 << 1)
MEMMAP_RAM_X
#define MEMMAP_RAM_X (1 << 0)
MEMMAP_REGULAR_READ
#define MEMMAP_REGULAR_READ (1 << 9)
NOT just a dummy read.
MEMMAP_ROM_R
#define MEMMAP_ROM_R (1 << 5)
MEMMAP_ROM_W
#define MEMMAP_ROM_W (1 << 4)
MEMMAP_ROM_X
#define MEMMAP_ROM_X (1 << 3)
MEMMAP_STATE_IGNORE
#define MEMMAP_STATE_IGNORE 0x04
MEMMAP_STATE_IN_MONITOR
#define MEMMAP_STATE_IN_MONITOR 0x08
MEMMAP_STATE_INSTR
#define MEMMAP_STATE_INSTR 0x02
MEMMAP_STATE_OPCODE
#define MEMMAP_STATE_OPCODE 0x01
MEMMAP_UNINITIALIZED_EXEC
#define MEMMAP_UNINITIALIZED_EXEC (1 << 11)
memmap defines
was executed before written to
MEMMAP_UNINITIALIZED_READ
#define MEMMAP_UNINITIALIZED_READ (1 << 10)
was read before written to
MONITOR_MAX_CHECKPOINTS
#define MONITOR_MAX_CHECKPOINTS 9
Breakpoint interface.
NUM_MEMSPACES
#define NUM_MEMSPACES e_invalid_space
Generic interface.
Typedef Documentation
CPU_TYPE_t
typedef enum CPU_TYPE_s CPU_TYPE_t
MEMSPACE
typedef enum t_memspace MEMSPACE
monitor_cartridge_commands_t
typedef struct monitor_cartridge_commands_s monitor_cartridge_commands_t
monitor_cpu_type_t
typedef struct monitor_cpu_type_s monitor_cpu_type_t
monitor_interface_t
typedef struct monitor_interface_s monitor_interface_t
supported_cpu_type_list_t
typedef struct supported_cpu_type_list_s supported_cpu_type_list_t
Enumeration Type Documentation
CPU_TYPE_s
enum CPU_TYPE_s
Enumerator
CPU_6502
CPU_WDC65C02
CPU_R65C02
CPU_65SC02
CPU_65816
CPU_Z80
CPU_6502DTV
CPU_6809
mon_int
enum mon_int
Enumerator
MI_NONE
MI_BREAK
MI_WATCH
MI_STEP
t_memspace
enum t_memspace
Enumerator
e_default_space
e_comp_space
e_disk8_space
e_disk9_space
e_disk10_space
e_disk11_space
e_invalid_space
Function Documentation
asm6502_init()
void asm6502_init (struct monitor_cpu_type_s * monitor_cpu_type)
Assembler initialization.
Referenced by c64_monitor_init().
asm6502dtv_init()
void asm6502dtv_init (struct monitor_cpu_type_s * monitor_cpu_type)
asm65816_init()
void asm65816_init (struct monitor_cpu_type_s * monitor_cpu_type)
asm6809_init()
void asm6809_init (struct monitor_cpu_type_s * monitor_cpu_type)
asmR65C02_init()
void asmR65C02_init (struct monitor_cpu_type_s * monitor_cpu_type)
Referenced by c64_monitor_init().
asmz80_init()
void asmz80_init (struct monitor_cpu_type_s * monitor_cpu_type)
Referenced by c64_monitor_init().
mon_disassemble_oneline()
unsigned mon_disassemble_oneline (MEMSPACE memspace, uint16_t mem_config, uint16_t addr)
Referenced by mon_backtrace(), and print_disass_context().
mon_disassemble_to_string()
const char * mon_disassemble_to_string (MEMSPACE memspace, unsigned int addr, unsigned int x, unsigned int p1, unsigned int p2, unsigned int p3, int hex_mode, const char * cpu_type)
Disassemble interace.
Prototypes
Referenced by z80_maincpu_loop().
mon_ioreg_add_list()
void mon_ioreg_add_list (struct mem_ioreg_list_s ** list, const char * name, int start, int end, void * dump, void * context, int mirror_mode)
Referenced by drivemem_ioreg_list_get(), io_source_ioreg_add_onelist(), and mem_ioreg_list_get().
mon_out()
int mon_out (const char * format, ...)
Referenced by acia_dump(), ata_register_dump(), c64_256k_dump(), check_drive_emu_level_ok(), ciacore_dump(), export_dump(), i8255a_dump(), init_profiling_data(), make_offset_mode(), mc6821core_dump(), mon_add_name_to_symbol_table(), mon_assemble_instr(), mon_attach(), mon_autostart(), mon_backtrace(), mon_bank(), mon_banknum_from_bank(), mon_banknum_validate(), mon_breakpoint_check_checkpoint(), mon_breakpoint_delete_checkpoint(), mon_breakpoint_print_checkpoints(), mon_breakpoint_set_checkpoint_command(), mon_breakpoint_set_checkpoint_condition(), mon_breakpoint_set_ignore_count(), mon_breakpoint_switch_checkpoint(), mon_cart_freeze(), mon_change_dir(), mon_detach(), mon_disassemble_instr(), mon_disassemble_oneline(), mon_disassemble_to_string_internal(), mon_disassemble_with_regdump(), mon_display_io_regs(), mon_display_screen(), mon_drive_block_cmd(), mon_drive_execute_disk_cmd(), mon_drive_list(), mon_end_recording(), mon_export(), mon_file_load(), mon_file_save(), mon_file_verify(), mon_instructions_next(), mon_instructions_step(), mon_joyport_set_output(), mon_maincpu_trace(), mon_make_dir(), mon_memmap_stub(), mon_memory_compare(), mon_memory_display(), mon_memory_display_data(), mon_memory_fill(), mon_memory_hunt(), mon_memory_move(), mon_out_wordwrap(), mon_playback_commands(), mon_print_bin(), mon_print_conditional(), mon_print_convert(), mon_print_symbol_table(), mon_profile(), mon_profile_action(), mon_profile_clear(), mon_profile_disass(), mon_profile_disass_context(), mon_profile_flat(), mon_profile_func(), mon_profile_graph(), mon_record_commands(), mon_register_print(), mon_remove_dir(), mon_remove_name_from_symbol_table(), mon_resource_get(), mon_resource_set(), mon_save_symbols(), mon_screenshot_save(), mon_set_command(), mon_show_dir(), mon_show_pwd(), mon_stack_down(), mon_stack_up(), mon_stopwatch_reset(), mon_stopwatch_show(), mon_tape_ctrl(), mon_tape_offs(), mon_userport_set_output(), monitor_change_device(), monitor_cpu_type_set(), monitor_open(), monitor_print_cpu_types_supported(), monitor_process(), mypia_dump(), pc8477d_dump(), plus256k_dump(), plus60k_dump(), print_all_contexts(), print_checkpoint_info(), print_context_graph(), print_context_id(), print_context_line(), print_context_name(), print_cycle_time(), print_disass_context(), print_dst(), print_function_line(), print_help_details(), print_help_topics(), print_hex(), print_octal(), print_src(), riotcore_dump(), sound_dump(), t6721_dump(), tpicore_dump(), viacore_dump(), vicii_dump(), and wd1770d_dump().
mon_petscii_out()
int mon_petscii_out (int maxlen, const char * format, ...)
Referenced by mon_memory_display(), and monitor_open().
mon_petscii_upper_out()
int mon_petscii_upper_out (int maxlen, const char * format, ...)
Referenced by mon_drive_list(), and monitor_open().
mon_register_list_get()
struct mon_reg_list_s * mon_register_list_get (int mem)
Register interface.
Register interface.
Referenced by mon_register_name_to_id(), mon_register_valid(), monitor_binary_process_registers_available(), and monitor_binary_response_register_info().
mon_scrcode_out()
int mon_scrcode_out (int maxlen, const char * format, ...)
Referenced by mon_display_screen(), mon_memory_display(), and monitor_open().
mon_scrcode_upper_out()
int mon_scrcode_upper_out (int maxlen, const char * format, ...)
Referenced by monitor_open().
monitor_abort()
void monitor_abort (void)
Referenced by mon_out(), mon_petscii_out(), mon_petscii_upper_out(), mon_scrcode_out(), and mon_scrcode_upper_out().
monitor_check_breakpoints()
int monitor_check_breakpoints (MEMSPACE mem, uint16_t addr)
Prototypes.
monitor_check_icount()
void monitor_check_icount (uint16_t pc)
*** CPU INTERFACES ***
called by cpu core
monitor_check_icount_interrupt()
void monitor_check_icount_interrupt (void)
called by cpu core
monitor_check_watchpoints()
void monitor_check_watchpoints (unsigned int lastpc, unsigned int pc)
called by macro DO_INTERRUPT() in 6510(dtv)core.c
monitor_cmdline_options_init()
int monitor_cmdline_options_init (void)
Referenced by init_cmdline_options().
monitor_cpu_type_set()
void monitor_cpu_type_set (const char * cpu_type)
monitor_cpu_type_set_value()
void monitor_cpu_type_set_value (int searchcpu)
basically above code but faster as the type is passed; used by x128
monitor_cpuhistory_fix_p2()
void monitor_cpuhistory_fix_p2 (unsigned int p2)
monitor_cpuhistory_store()
void monitor_cpuhistory_store (CLOCK cycle, unsigned int addr, unsigned int op, unsigned int p1, unsigned int p2, uint8_t reg_a, uint8_t reg_x, uint8_t reg_y, uint8_t reg_sp, unsigned int reg_st, MEMSPACE origin)
CPU history/memmap prototypes.
monitor_diskspace_dnr()
int monitor_diskspace_dnr (int mem)
Referenced by mon_get_mem_val_ex(), mon_get_mem_val_ex_nosfx(), mon_get_mem_val_nosfx(), mon_register_get_val(), mon_register_print(), mon_register_print_ex(), mon_register_set_val(), mon_register_valid(), mon_set_mem_val(), and mon_set_mem_val_ex().
monitor_diskspace_mem()
int monitor_diskspace_mem (int dnr)
Referenced by check_drive_emu_level_ok(), drivecpu65c02_setup_context(), drivecpu_setup_context(), monitor_check_watchpoints(), monitor_init(), and monitor_open().
monitor_find_cpu_type_from_string()
monitor_cpu_type_t * monitor_find_cpu_type_from_string (const char * cpu_type)
Prototypes.
Prototypes.
Referenced by mon_disassemble_to_string().
monitor_init()
void monitor_init (monitor_interface_t * maincpu_interface, monitor_interface_t * drive_interface_init[], struct monitor_cpu_type_s ** asmarray)
Referenced by c64_monitor_init().
monitor_interface_destroy()
void monitor_interface_destroy (monitor_interface_t * monitor_interface)
Referenced by drivecpu65c02_shutdown(), and drivecpu_shutdown().
monitor_interface_new()
monitor_interface_t * monitor_interface_new (void)
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
monitor_is_inside_monitor()
bool monitor_is_inside_monitor (void)
Referenced by on_save_screenshot_filename(), screenshot_ui_auto_screenshot(), and vice_opengl_on_ui_frame_clock().
monitor_memmap_store()
void monitor_memmap_store (unsigned int addr, unsigned int type)
Referenced by zero_read(), zero_read_dma(), zero_store(), and zero_store_dma().
monitor_reset_hook()
void monitor_reset_hook (void)
Referenced by machine_reset().
monitor_resources_init()
int monitor_resources_init (void)
Referenced by init_resources().
monitor_resources_shutdown()
void monitor_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
monitor_shutdown()
void monitor_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
monitor_startup()
void monitor_startup (MEMSPACE mem)
Referenced by drivecpu_jam(), monitor_check_icount(), monitor_check_watchpoints(), and monitor_trap().
monitor_startup_trap()
void monitor_startup_trap (void)
Referenced by load_snapshot_trap(), monitor_check_binary(), monitor_check_remote(), monitor_open_action(), monitor_reset_hook(), monitor_vsync_hook(), and ui_pause_loop_iteration().
monitor_vsync_hook()
void monitor_vsync_hook (void)
Referenced by vsync_do_vsync().
monitor_watch_push_load_addr()
void monitor_watch_push_load_addr (uint16_t addr, MEMSPACE mem)
*** WATCHPOINTS ***
Referenced by drive_read_watch(), drive_zero_read_watch(), read_watch(), and zero_read_watch().
monitor_watch_push_store_addr()
void monitor_watch_push_store_addr (uint16_t addr, MEMSPACE mem)
Referenced by drive_store_watch(), drive_zero_store_watch(), store_watch(), and zero_store_watch().
Variable Documentation
memmap_state
uint8_t memmap_state extern
HACK to enable fetch/load separation.
HACK to enable fetch/load separation.
Referenced by monitor_close(), monitor_open(), zero_read(), and zero_read_dma().
mon_cart_cmd
monitor_cartridge_commands_t mon_cart_cmd extern
Referenced by mon_attach(), mon_cart_freeze(), mon_detach(), mon_export(), and monitor_cmdline_options_init().
monitor_cpu_type_supported
supported_cpu_type_list_t* monitor_cpu_type_supported[e_invalid_space] extern
A linked list of supported monitor_cpu_types for each memspace.
Referenced by mon_breakpoint_check_checkpoint(), monitor_find_cpu_for_memspace(), monitor_init(), monitor_open(), monitor_print_cpu_types_supported(), and monitor_shutdown().
monitor_mask
unsigned monitor_mask[e_invalid_space] extern
Externals.
Referenced by mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), monitor_check_icount(), monitor_init(), and update_checkpoint_state().