vsid: userport/userport.c File Reference
userport.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "cmdline.h"
#include "drive.h"
#include "joyport.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "snapshot.h"
#include "uiapi.h"
#include "userport.h"
#include "util.h"
#include "init.h"
Data Structures
struct type2text_s
struct userport_opt_s
Macros
#define DUMP_VER_MAJOR 1
#define DUMP_VER_MINOR 0
Typedefs
typedef struct type2text_s type2text_t
Functions
static const char * userport_type2text (int type)
static int valid_device (userport_device_t *device)
void userport_port_register (userport_port_props_t *props)
int userport_device_register (int id, userport_device_t *device)
register a device to be used in the userport system if possible
int userport_get_device (void)
static int userport_set_device (int id)
attach device 'id' to the userport
static int userport_valid_devices_compare_names (const void *a, const void *b)
userport_desc_t * userport_get_valid_devices (int sort)
const char * userport_get_device_type_desc (int type)
Get short description of of userport device type.
uint8_t read_userport_pbx (uint8_t orig)
void store_userport_pbx (uint8_t val, int pulse)
uint8_t read_userport_pa2 (uint8_t orig)
void store_userport_pa2 (uint8_t val)
uint8_t read_userport_pa3 (uint8_t orig)
void store_userport_pa3 (uint8_t val)
void set_userport_flag (uint8_t val)
use this function from userport device code to set the userport flag
void store_userport_sp1 (uint8_t val)
uint8_t read_userport_sp1 (uint8_t orig)
void store_userport_sp2 (uint8_t val)
uint8_t read_userport_sp2 (uint8_t orig)
void userport_powerup (void)
void userport_reset (void)
void userport_reset_start (void)
void userport_reset_end (void)
static int set_userport_device (int val, void *param)
int userport_resources_init (void)
static int is_a_number (const char *str)
static int set_userport_cmdline_device (const char *param, void *extra_param)
static char * build_userport_string (int something)
int userport_cmdline_options_init (void)
void userport_enable (int val)
int userport_get_active_state (void)
int userport_snapshot_write_module (snapshot_t *s)
int userport_snapshot_read_module (struct snapshot_s *s)
Variables
static type2text_t device_type_desc []
static int userport_active = 1
flag indicating if the userport exists on the current emulated model
static int userport_current_device = USERPORT_DEVICE_NONE
current userport device
static userport_device_t userport_device [USERPORT_MAX_DEVICES] = {0}
this will hold all the information about the userport devices
static userport_port_props_t userport_props
this will hold all the information about the userport itself
static int userport_reset_started = 0
static const resource_int_t resources_int []
static const struct userport_opt_s id_match []
static cmdline_option_t cmdline_options []
static char snap_module_name [] = "USERPORT"
Macro Definition Documentation
DUMP_VER_MAJOR
#define DUMP_VER_MAJOR 1
DUMP_VER_MINOR
#define DUMP_VER_MINOR 0
Typedef Documentation
type2text_t
typedef struct type2text_s type2text_t
Function Documentation
build_userport_string()
static char * build_userport_string (int something) static
Referenced by userport_cmdline_options_init().
is_a_number()
static int is_a_number (const char * str) static
Referenced by set_userport_cmdline_device().
read_userport_pa2()
uint8_t read_userport_pa2 (uint8_t orig)
Referenced by read_ciapa().
read_userport_pa3()
uint8_t read_userport_pa3 (uint8_t orig)
Referenced by read_ciapa().
read_userport_pbx()
uint8_t read_userport_pbx (uint8_t orig)
Referenced by read_ciapb().
read_userport_sp1()
uint8_t read_userport_sp1 (uint8_t orig)
Referenced by read_sdr().
read_userport_sp2()
uint8_t read_userport_sp2 (uint8_t orig)
Referenced by read_sdr().
set_userport_cmdline_device()
static int set_userport_cmdline_device (const char * param, void * extra_param) static
set_userport_device()
static int set_userport_device (int val, void * param) static
Referenced by set_userport_cmdline_device().
set_userport_flag()
void set_userport_flag (uint8_t val)
use this function from userport device code to set the userport flag
Referenced by userport_printer_store_pa2().
store_userport_pa2()
void store_userport_pa2 (uint8_t val)
Referenced by do_reset_cia(), store_ciapa(), and undump_ciapa().
store_userport_pa3()
void store_userport_pa3 (uint8_t val)
Referenced by store_ciapa(), and undump_ciapa().
store_userport_pbx()
void store_userport_pbx (uint8_t val, int pulse)
Referenced by do_reset_cia(), pulse_ciapc(), store_ciapb(), and undump_ciapb().
store_userport_sp1()
void store_userport_sp1 (uint8_t val)
Referenced by store_sdr().
store_userport_sp2()
void store_userport_sp2 (uint8_t val)
Referenced by store_sdr().
userport_cmdline_options_init()
int userport_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
userport_device_register()
int userport_device_register (int id, userport_device_t * device)
register a device to be used in the userport system if possible
Referenced by interface_userport_init_resources(), parallel_cable_cpu_resources_init(), rsuser_resources_init(), userport_4bit_sampler_resources_init(), userport_8bss_resources_init(), userport_dac_resources_init(), userport_digimax_resources_init(), userport_io_sim_resources_init(), userport_joystick_cga_resources_init(), userport_joystick_hit_resources_init(), userport_joystick_hummer_resources_init(), userport_joystick_kingsoft_resources_init(), userport_joystick_oem_resources_init(), userport_joystick_pet_resources_init(), userport_joystick_starbyte_resources_init(), userport_joystick_synergy_resources_init(), userport_joystick_woj_resources_init(), userport_petscii_snespad_resources_init(), userport_rtc_58321a_resources_init(), userport_rtc_ds1307_resources_init(), userport_spt_joystick_resources_init(), and userport_superpad64_resources_init().
userport_enable()
void userport_enable (int val)
Referenced by c64model_set().
userport_get_active_state()
int userport_get_active_state (void)
userport_get_device()
int userport_get_device (void)
Referenced by drv_ascii_select(), drv_nl10_select(), and drv_raw_select().
userport_get_device_type_desc()
const char * userport_get_device_type_desc (int type)
Get short description of of userport device type.
Parameters
[in] type userport device type
Referenced by create_device_model().
userport_get_valid_devices()
userport_desc_t * userport_get_valid_devices (int sort)
Referenced by build_userport_string(), and create_device_model().
userport_port_register()
void userport_port_register (userport_port_props_t * props)
Referenced by machine_register_userport().
userport_powerup()
void userport_powerup (void)
Referenced by machine_specific_powerup().
userport_reset()
void userport_reset (void)
Referenced by machine_specific_reset().
userport_reset_end()
void userport_reset_end (void)
userport_reset_start()
void userport_reset_start (void)
userport_resources_init()
int userport_resources_init (void)
Referenced by machine_resources_init().
userport_set_device()
static int userport_set_device (int id) static
attach device 'id' to the userport
Referenced by set_userport_device(), and userport_snapshot_read_module().
userport_snapshot_read_module()
int userport_snapshot_read_module (struct snapshot_s * s)
Referenced by c64_snapshot_read().
userport_snapshot_write_module()
int userport_snapshot_write_module (snapshot_t * s)
Referenced by c64_snapshot_write().
userport_type2text()
static const char * userport_type2text (int type) static
Referenced by userport_get_device_type_desc().
userport_valid_devices_compare_names()
static int userport_valid_devices_compare_names (const void * a, const void * b) static
Referenced by userport_get_valid_devices().
valid_device()
static int valid_device (userport_device_t * device) static
Referenced by userport_device_register().
Variable Documentation
cmdline_options
cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-userportdevice", CALL_FUNCTION,  (1 << 0)  |  (1 << 2) ,
      set_userport_cmdline_device, NULL, "UserportDevice", NULL,
      "<device>", NULL },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by userport_cmdline_options_init().
device_type_desc
type2text_t device_type_desc[] static
Initial value:
= {
    { USERPORT_DEVICE_TYPE_NONE, "None" },
    { USERPORT_DEVICE_TYPE_PRINTER, "Printer" },
    { USERPORT_DEVICE_TYPE_MODEM, "Modem" },
    { USERPORT_DEVICE_TYPE_DRIVE_PAR_CABLE, "Parallel drive cable" },
    { USERPORT_DEVICE_TYPE_JOYSTICK_ADAPTER, "Joystick adapter" },
    { USERPORT_DEVICE_TYPE_AUDIO_OUTPUT, "Audio output" },
    { USERPORT_DEVICE_TYPE_SAMPLER, "Sampler" },
    { USERPORT_DEVICE_TYPE_RTC, "Real-time clock" },
    { -1, NULL }
}
Referenced by userport_type2text().
id_match
const struct userport_opt_s id_match[] static
Initial value:
= {
    { "none",               USERPORT_DEVICE_NONE },
    { "printer",            USERPORT_DEVICE_PRINTER },
    { "plotter",            USERPORT_DEVICE_PRINTER },
    { "modem",              USERPORT_DEVICE_RS232_MODEM },
    { "cga",                USERPORT_DEVICE_JOYSTICK_CGA },
    { "cgajoy",             USERPORT_DEVICE_JOYSTICK_CGA },
    { "cgajoystick",        USERPORT_DEVICE_JOYSTICK_CGA },
    { "pet",                USERPORT_DEVICE_JOYSTICK_PET },
    { "petjoy",             USERPORT_DEVICE_JOYSTICK_PET },
    { "petjoystick",        USERPORT_DEVICE_JOYSTICK_PET },
    { "hummer",             USERPORT_DEVICE_JOYSTICK_HUMMER },
    { "hummerjoy",          USERPORT_DEVICE_JOYSTICK_HUMMER },
    { "hummerjoystick",     USERPORT_DEVICE_JOYSTICK_HUMMER },
    { "oem",                USERPORT_DEVICE_JOYSTICK_OEM },
    { "oemjoy",             USERPORT_DEVICE_JOYSTICK_OEM },
    { "oemjoystick",        USERPORT_DEVICE_JOYSTICK_OEM },
    { "hit",                USERPORT_DEVICE_JOYSTICK_HIT },
    { "dxs",                USERPORT_DEVICE_JOYSTICK_HIT },
    { "hitjoy",             USERPORT_DEVICE_JOYSTICK_HIT },
    { "dxsjoy",             USERPORT_DEVICE_JOYSTICK_HIT },
    { "hitjoystick",        USERPORT_DEVICE_JOYSTICK_HIT },
    { "dxsjoystick",        USERPORT_DEVICE_JOYSTICK_HIT },
    { "kingsoft",           USERPORT_DEVICE_JOYSTICK_KINGSOFT },
    { "kingsoftjoy",        USERPORT_DEVICE_JOYSTICK_KINGSOFT },
    { "kingsoftjoystick",   USERPORT_DEVICE_JOYSTICK_KINGSOFT },
    { "starbyte",           USERPORT_DEVICE_JOYSTICK_STARBYTE },
    { "starbytejoy",        USERPORT_DEVICE_JOYSTICK_STARBYTE },
    { "starbytejoystick",   USERPORT_DEVICE_JOYSTICK_STARBYTE },
    { "synergy",            USERPORT_DEVICE_JOYSTICK_SYNERGY },
    { "synergyjoy",         USERPORT_DEVICE_JOYSTICK_SYNERGY },
    { "synergyjoystick",    USERPORT_DEVICE_JOYSTICK_SYNERGY },
    { "dac",                USERPORT_DEVICE_DAC },
    { "digimax",            USERPORT_DEVICE_DIGIMAX },
    { "4bitsampler",        USERPORT_DEVICE_4BIT_SAMPLER },
    { "8bss",               USERPORT_DEVICE_8BSS },
    { "58321a",             USERPORT_DEVICE_RTC_58321A },
    { "58321artc",          USERPORT_DEVICE_RTC_58321A },
    { "58321rtc",           USERPORT_DEVICE_RTC_58321A },
    { "rtc58321a",          USERPORT_DEVICE_RTC_58321A },
    { "rtc58321",           USERPORT_DEVICE_RTC_58321A },
    { "ds1307",             USERPORT_DEVICE_RTC_DS1307 },
    { "ds1307rtc",          USERPORT_DEVICE_RTC_DS1307 },
    { "rtcds1307",          USERPORT_DEVICE_RTC_DS1307 },
    { "rtc1307",            USERPORT_DEVICE_RTC_DS1307 },
    { "petscii",            USERPORT_DEVICE_PETSCII_SNESPAD },
    { "petsciisnes",        USERPORT_DEVICE_PETSCII_SNESPAD },
    { "petsciisnespad",     USERPORT_DEVICE_PETSCII_SNESPAD },
    { "superpad",           USERPORT_DEVICE_SUPERPAD64 },
    { "superpad64",         USERPORT_DEVICE_SUPERPAD64 },
    { "parcable",           USERPORT_DEVICE_DRIVE_PAR_CABLE },
    { "driveparcable",      USERPORT_DEVICE_DRIVE_PAR_CABLE },
    { "driveparallelcable", USERPORT_DEVICE_DRIVE_PAR_CABLE },
    { "io",                 USERPORT_DEVICE_IO_SIMULATION },
    { "iosim",              USERPORT_DEVICE_IO_SIMULATION },
    { "iosimulation",       USERPORT_DEVICE_IO_SIMULATION },
    { "space",              USERPORT_DEVICE_SPACEBALLS },
    { "spaceballs",         USERPORT_DEVICE_SPACEBALLS },
    { NULL, -1 }
}
Referenced by set_userport_cmdline_device().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "UserportDevice", USERPORT_DEVICE_NONE, RES_EVENT_NO, NULL,
      &userport_current_device, set_userport_device, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by userport_resources_init().
snap_module_name
char snap_module_name[] = "USERPORT" static
Referenced by userport_snapshot_read_module(), and userport_snapshot_write_module().
userport_active
int userport_active = 1 static
flag indicating if the userport exists on the current emulated model
Referenced by read_userport_pa2(), read_userport_pa3(), read_userport_pbx(), read_userport_sp1(), read_userport_sp2(), set_userport_flag(), store_userport_pa2(), store_userport_pa3(), store_userport_pbx(), store_userport_sp1(), store_userport_sp2(), userport_enable(), userport_get_active_state(), userport_snapshot_read_module(), and userport_snapshot_write_module().
userport_current_device
int userport_current_device = USERPORT_DEVICE_NONE static
current userport device
Referenced by read_userport_pa2(), read_userport_pa3(), read_userport_pbx(), read_userport_sp1(), read_userport_sp2(), store_userport_pa2(), store_userport_pa3(), store_userport_pbx(), store_userport_sp1(), store_userport_sp2(), userport_get_device(), userport_powerup(), userport_reset(), userport_set_device(), userport_snapshot_read_module(), and userport_snapshot_write_module().
userport_device
userport_device_t userport_device[USERPORT_MAX_DEVICES] = {0} static
this will hold all the information about the userport devices
Referenced by read_userport_pa2(), read_userport_pa3(), read_userport_pbx(), read_userport_sp1(), read_userport_sp2(), store_userport_pa2(), store_userport_pa3(), store_userport_pbx(), store_userport_sp1(), store_userport_sp2(), userport_device_register(), userport_get_valid_devices(), userport_powerup(), userport_reset(), userport_resources_init(), userport_set_device(), userport_snapshot_read_module(), and userport_snapshot_write_module().
userport_props
userport_port_props_t userport_props static
this will hold all the information about the userport itself
Referenced by set_userport_flag(), userport_port_register(), userport_reset(), and valid_device().
userport_reset_started
int userport_reset_started = 0 static
Referenced by store_userport_pbx(), userport_reset_end(), and userport_reset_start().