x128: arch/gtk3/widgets/printeroutputmodewidget.c File Reference
printeroutputmodewidget.c File Reference
Widget to control printer output mode settings.
#include "vice.h"
#include <gtk/gtk.h>
#include <string.h>
#include "log.h"
#include "printer.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "printeroutputmodewidget.h"
Enumerations
enum {
ROW_TEXT_MODE = 1 ,
ROW_GRAPHICS_MODE = 2
}
Output mode radio button rows.
Functions
static void on_radio_toggled (GtkWidget *radio, gpointer mode)
Handler for the 'toggled' event of the radio buttons.
GtkWidget * printer_output_mode_widget_create (int device)
Create widget to control Printer[device]TextDevice resource.
void printer_output_mode_widget_set_mode (GtkWidget *widget, const char *mode)
Set printer output mode.
Detailed Description
Widget to control printer output mode settings.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
anonymous enum
anonymous enum
Output mode radio button rows.
Enumerator
ROW_TEXT_MODE
ROW_GRAPHICS_MODE
Function Documentation
on_radio_toggled()
static void on_radio_toggled (GtkWidget * radio, gpointer mode) static
Handler for the 'toggled' event of the radio buttons.
Parameters
[in] radio radio button
[in] mode new output mode
Referenced by printer_output_mode_widget_create().
printer_output_mode_widget_create()
GtkWidget * printer_output_mode_widget_create (int device)
Create widget to control Printer[device]TextDevice resource.
Parameters
[in] device device number (4-6 or 3 for userport)
Returns
GtkGrid
Referenced by create_printer_widget().
printer_output_mode_widget_set_mode()
void printer_output_mode_widget_set_mode (GtkWidget * widget, const char * mode)
Set printer output mode.
Parameters
[in] widget printer output mode widget
[in] mode mode ("text or "graphics")
Referenced by driver_radio_callback().