x128: c128/cart/c128cart.c File Reference
c128cart.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "c128mem.h"
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "viciitypes.h"
#include "vicii-phi1.h"
#include "cartridge.h"
#include "export.h"
#include "monitor.h"
#include "c64cart.h"
#include "c64cartsystem.h"
#include "c128cart.h"
#include "functionrom.h"
#include "generic.h"
#include "comal80.h"
#include "gmod2c128.h"
#include "magicdesk128.h"
#include "partner128.h"
#include "warpspeed128.h"
#include "ltkernal.h"
#include "ramlink.h"
Macros
#define DBG(x)
#define EXT_FUNCTION_NONE 0
#define EXT_FUNCTION_ROM 1
Functions
static cartridge_info_t * c128cartridge_get_info_list (void)
static void c128cartridge_config_init (int type)
static void c128cartridge_config_setup (int type, uint8_t *rawcart)
copy data from rawcart into actually used ROM array(s).
static int c128cartridge_attach_crt (int type, FILE *fd, const char *filename, uint8_t *rawcart)
static int c128cartridge_bin_attach (int type, const char *filename, uint8_t *rawcart)
static int c128cartridge_bin_save (int type, const char *filename)
static int c128cartridge_save_secondary_image (int type, const char *filename)
static int c128cartridge_crt_save (int type, const char *filename)
static int c128cartridge_flush_image (int type)
static int c128cartridge_flush_secondary_image (int type)
static int c128cartridge_can_save_image (int crtid)
static int c128cartridge_can_flush_image (int crtid)
static int c128cartridge_can_save_secondary_image (int crtid)
static int c128cartridge_can_flush_secondary_image (int crtid)
static void c128cartridge_detach_image (int type)
static void c128cartridge_reset (void)
static int c128cartridge_freeze_allowed (void)
static void c128cartridge_freeze (void)
static void c128cartridge_powerup (void)
static int c128cartridge_snapshot_read (int type, snapshot_t *s)
static int c128cartridge_snapshot_write (int type, snapshot_t *s)
void c128cartridge_setup_interface (void)
only x128 actually implements this function
int c128cartridge_resources_init (void)
void c128cartridge_resources_shutdown (void)
static void c128cartridge_export_dump (void)
int c128cartridge_cmdline_options_init (void)
void external_function_rom_set_bank (int value)
set the bank for generic function rom access
uint8_t external_function_rom_read (uint16_t addr)
ROML and ROMH reads at the cartridge port.
uint8_t external_function_rom_peek (uint16_t addr)
ROML and ROMH peeks at the cartridge port.
void external_function_rom_store (uint16_t addr, uint8_t value)
ROML and ROMH stores at the cartridge port.
void external_function_top_shared_store (uint16_t addr, uint8_t value)
uint8_t c128cartridge_basic_hi_read (uint16_t addr, uint8_t *value)
basic hi replacement reads at the cartridge port
uint8_t c128cartridge_basic_hi_store (uint16_t addr, uint8_t value)
basic hi replacement store at the cartridge port
uint8_t c128cartridge_hi_read (uint16_t addr, uint8_t *value)
kernal replacement reads at the cartridge port
uint8_t c128cartridge_hi_store (uint16_t addr, uint8_t value)
kernal replacement store at the cartridge port
uint8_t c128cartridge_ram_read (uint16_t addr, uint8_t *value)
memory replacement reads at the cartridge port
uint8_t c128cartridge_ram_store (uint16_t addr, uint8_t value)
kernal replacement store at the cartridge port
int c128cartridge_mmu_translate (unsigned int addr, uint8_t **base, int *start, int *limit, int mem_config)
mmu translation: return 0 if no translation applied, leave it for the tables
void c128cartridge_switch_mode (int mode)
notify cartridge of mode change
Variables
c128cartridge_interface_t * c128cartridge
static c128cartridge_interface_t c128interface
uint8_t ext_function_rom [0x8000 *0x40]
uint8_t ext_function_rom_bank = 0
static int external_function_rom_enabled = 0
Flag: Do we enable the external function ROM?
static cartridge_info_t cartlist []
CAUTION: keep in sync with the list in c64/c64cart.c.
static const cmdline_option_t cmdline_options []
Macro Definition Documentation
DBG
#define DBG (x)
EXT_FUNCTION_NONE
#define EXT_FUNCTION_NONE 0
Todo:
FIXME: get rid of these
EXT_FUNCTION_ROM
#define EXT_FUNCTION_ROM 1
Function Documentation
c128cartridge_attach_crt()
static int c128cartridge_attach_crt (int type, FILE * fd, const char * filename, uint8_t * rawcart) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Todo:
FIXME: get rid of this flag
Referenced by c128cartridge_setup_interface().
c128cartridge_basic_hi_read()
uint8_t c128cartridge_basic_hi_read (uint16_t addr, uint8_t * value)
basic hi replacement reads at the cartridge port
< ltkernal.c
Referenced by basic_hi_peek(), and basic_hi_read().
c128cartridge_basic_hi_store()
uint8_t c128cartridge_basic_hi_store (uint16_t addr, uint8_t value)
basic hi replacement store at the cartridge port
< ltkernal.c
Referenced by basic_hi_store().
c128cartridge_bin_attach()
static int c128cartridge_bin_attach (int type, const char * filename, uint8_t * rawcart) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Todo:
FIXME: get rid of this flag
Referenced by c128cartridge_setup_interface().
c128cartridge_bin_save()
static int c128cartridge_bin_save (int type, const char * filename) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_can_flush_image()
static int c128cartridge_can_flush_image (int crtid) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_can_flush_secondary_image()
static int c128cartridge_can_flush_secondary_image (int crtid) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_can_save_image()
static int c128cartridge_can_save_image (int crtid) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_can_save_secondary_image()
static int c128cartridge_can_save_secondary_image (int crtid) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_cmdline_options_init()
int c128cartridge_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
c128cartridge_config_init()
static void c128cartridge_config_init (int type) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_config_setup()
static void c128cartridge_config_setup (int type, uint8_t * rawcart) static
copy data from rawcart into actually used ROM array(s).
(called from c64carthooks:cart_attach())
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_crt_save()
static int c128cartridge_crt_save (int type, const char * filename) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_detach_image()
static void c128cartridge_detach_image (int type) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< max: "Magic Desk 128" has 64
Todo:
FIXME: get rid of this flag
Referenced by c128cartridge_setup_interface().
c128cartridge_export_dump()
static void c128cartridge_export_dump (void) static
Todo:
FIXME: make seperate flags
Referenced by c128cartridge_cmdline_options_init().
c128cartridge_flush_image()
static int c128cartridge_flush_image (int type) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_flush_secondary_image()
static int c128cartridge_flush_secondary_image (int type) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_freeze()
static void c128cartridge_freeze (void) static
< cartconv: last cartridge in list
< from CRT ID to internal ID
< ltkernal.c
Referenced by c128cartridge_setup_interface().
c128cartridge_freeze_allowed()
static int c128cartridge_freeze_allowed (void) static
< cartconv: last cartridge in list
< from CRT ID to internal ID
< ltkernal.c
Referenced by c128cartridge_setup_interface().
c128cartridge_get_info_list()
static cartridge_info_t * c128cartridge_get_info_list (void) static
Referenced by c128cartridge_setup_interface().
c128cartridge_hi_read()
uint8_t c128cartridge_hi_read (uint16_t addr, uint8_t * value)
kernal replacement reads at the cartridge port
< ramlink.c
< ltkernal.c
Referenced by hi_peek(), and hi_read().
c128cartridge_hi_store()
uint8_t c128cartridge_hi_store (uint16_t addr, uint8_t value)
kernal replacement store at the cartridge port
< ltkernal.c
Referenced by hi_store().
c128cartridge_mmu_translate()
int c128cartridge_mmu_translate (unsigned int addr, uint8_t ** base, int * start, int * limit, int mem_config)
mmu translation: return 0 if no translation applied, leave it for the tables
< ramlink.c
< ltkernal.c
Referenced by mem_mmu_translate().
c128cartridge_powerup()
static void c128cartridge_powerup (void) static
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_ram_read()
uint8_t c128cartridge_ram_read (uint16_t addr, uint8_t * value)
memory replacement reads at the cartridge port
< ltkernal.c
Referenced by ram_peek(), and ram_read().
c128cartridge_ram_store()
uint8_t c128cartridge_ram_store (uint16_t addr, uint8_t value)
kernal replacement store at the cartridge port
< ltkernal.c
Referenced by ram_store().
c128cartridge_reset()
static void c128cartridge_reset (void) static
Referenced by c128cartridge_setup_interface().
c128cartridge_resources_init()
int c128cartridge_resources_init (void)
Referenced by machine_resources_init().
c128cartridge_resources_shutdown()
void c128cartridge_resources_shutdown (void)
c128cartridge_save_secondary_image()
static int c128cartridge_save_secondary_image (int type, const char * filename) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_setup_interface()
void c128cartridge_setup_interface (void)
only x128 actually implements this function
Referenced by machine_resources_init().
c128cartridge_snapshot_read()
static int c128cartridge_snapshot_read (int type, snapshot_t * s) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_snapshot_write()
static int c128cartridge_snapshot_write (int type, snapshot_t * s) static
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128cartridge_setup_interface().
c128cartridge_switch_mode()
void c128cartridge_switch_mode (int mode)
notify cartridge of mode change
< ramlink.c
< ltkernal.c
< mmcreplay.c, ser-eeprom.c, spi-sdcard.c
Referenced by mmu_reset(), and mmu_store().
external_function_rom_peek()
uint8_t external_function_rom_peek (uint16_t addr)
ROML and ROMH peeks at the cartridge port.
Todo:
FIXME: What should we return here? is vicii_read_phi1() safe for a peek?
< ramlink.c
< cartconv: last cartridge in list
< from CRT ID to internal ID
Todo:
FIXME: gmod2 needs a peek
val = c128gmod2_roml_peek(addr);
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< mmcreplay.c, ser-eeprom.c, spi-sdcard.c
< ltkernal.c
Referenced by mem_bank_peek(), mem_peek_with_config_c128(), z80mem_chargen_rom_area_peek(), z80mem_editor_rom_area_peek(), z80mem_hi_rom_area_peek(), and z80mem_mid_rom_area_peek().
external_function_rom_read()
uint8_t external_function_rom_read (uint16_t addr)
ROML and ROMH reads at the cartridge port.
< ramlink.c
< cartconv: last cartridge in list
< from CRT ID to internal ID
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< mmcreplay.c, ser-eeprom.c, spi-sdcard.c
< ltkernal.c
Referenced by c128meminit(), mem_bank_read(), mmu_ffxx_read(), z80mem_chargen_rom_area_read(), z80mem_editor_rom_area_read(), z80mem_hi_rom_area_read(), and z80mem_mid_rom_area_read().
external_function_rom_set_bank()
void external_function_rom_set_bank (int value)
set the bank for generic function rom access
Referenced by c128comal80_io1_store(), c128comal80_reset(), magicdesk128_io1_read(), magicdesk128_io1_store(), and magicdesk128_reset().
external_function_rom_store()
void external_function_rom_store (uint16_t addr, uint8_t value)
ROML and ROMH stores at the cartridge port.
< cartconv: last cartridge in list
< from CRT ID to internal ID
< ltkernal.c
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128meminit(), z80mem_chargen_rom_area_store(), z80mem_editor_rom_area_store(), z80mem_hi_rom_area_store(), and z80mem_mid_rom_area_store().
external_function_top_shared_store()
void external_function_top_shared_store (uint16_t addr, uint8_t value)
Referenced by c128meminit().
Variable Documentation
c128cartridge
c128cartridge_interface_t* c128cartridge extern
Referenced by c128cartridge_setup_interface().
c128interface
c128cartridge_interface_t c128interface static
Referenced by c128cartridge_setup_interface().
cartlist
cartridge_info_t cartlist[] static
CAUTION: keep in sync with the list in c64/c64cart.c.
Referenced by c128cartridge_get_info_list().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-cartfrom", CALL_FUNCTION,  (1 << 0) ,
      cart_attach_cmdline, (void *)((  0   ) +  ( 79   + 1) ) , NULL, NULL,
      "<Name>", "Attach generic external function ROM cartridge image" },
    { "-cartcomal128", CALL_FUNCTION,  (1 << 0) ,
      cart_attach_cmdline, (void *)((  3  ) +  ( 79   + 1) ) , NULL, NULL,
      "<Name>", "Attach 96k "  "Comal 80 (C128)"  " cartridge image" },
    { "-cartgmod128", CALL_FUNCTION,  (1 << 0) ,
      cart_attach_cmdline, (void *)((  5  ) +  ( 79   + 1) ) , NULL, NULL,
      "<Name>", "Attach 516k "  "Gmod2-C128"  " cartridge image" },
    { "-cartmd128", CALL_FUNCTION,  (1 << 0) ,
      cart_attach_cmdline, (void *)((  4  ) +  ( 79   + 1) ) , NULL, NULL,
      "<Name>", "Attach 16/32/64/128/256/512k/1M "  "Magic Desk 128"  " cartridge image" },
    { "-cartpartner128", CALL_FUNCTION,  (1 << 0) ,
      cart_attach_cmdline, (void *)((  2  ) +  ( 79   + 1) ) , NULL, NULL,
      "<Name>", "Attach 16k "  "Partner 128"  " cartridge image" },
    { "-cartws128", CALL_FUNCTION,  (1 << 0) ,
      cart_attach_cmdline, (void *)((  1  ) +  ( 79   + 1) ) , NULL, NULL,
      "<Name>", "Attach 16k "  "Warp Speed 128"  " cartridge image" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by c128cartridge_cmdline_options_init().
ext_function_rom
uint8_t ext_function_rom[0x8000 * 0x40]
Referenced by c128cartridge_detach_image(), c128comal80_config_setup(), c128comal80_io1_peek(), c128comal80_io2_peek(), c128comal80_io2_read(), c128comal80_snapshot_read_module(), c128comal80_snapshot_write_module(), c128generic_config_setup(), c128generic_snapshot_read_module(), c128generic_snapshot_write_module(), c128gmod2_bin_save(), c128gmod2_config_setup(), c128gmod2_crt_save(), c128gmod2_snapshot_read_module(), external_function_rom_peek(), external_function_rom_read(), magicdesk128_config_setup(), partner128_config_setup(), partner128_io1_peek(), partner128_io1_read(), warpspeed128_config_setup(), warpspeed128_io1_peek(), warpspeed128_io1_read(), warpspeed128_io2_peek(), warpspeed128_io2_read(), warpspeed128_snapshot_read_module(), and warpspeed128_snapshot_write_module().
ext_function_rom_bank
uint8_t ext_function_rom_bank = 0
Referenced by external_function_rom_peek(), external_function_rom_read(), and external_function_rom_set_bank().
external_function_rom_enabled
int external_function_rom_enabled = 0 static
Flag: Do we enable the external function ROM?
Todo:
FIXME: get rid of this
Referenced by c128cartridge_attach_crt(), c128cartridge_bin_attach(), c128cartridge_detach_image(), and c128cartridge_export_dump().