vsid: diskimage/fsimage.h File Reference
fsimage.h File Reference
#include <stdio.h>
#include "types.h"
Data Structures
struct fsimage_s
Typedefs
typedef struct fsimage_s fsimage_t
Functions
void fsimage_init (void)
void fsimage_name_set (struct disk_image_s *image, const char *name)
Set image name.
const char * fsimage_name_get (const struct disk_image_s *image)
void * fsimage_fd_get (const disk_image_t *image)
Get file descriptor for image.
void fsimage_media_create (struct disk_image_s *image)
void fsimage_media_destroy (struct disk_image_s *image)
int fsimage_open (struct disk_image_s *image)
int fsimage_close (struct disk_image_s *image)
int fsimage_read_sector (const struct disk_image_s *image, uint8_t *buf, const struct disk_addr_s *dadr)
int fsimage_write_sector (struct disk_image_s *image, const uint8_t *buf, const struct disk_addr_s *dadr)
off_t fsimage_size (const disk_image_t *image)
Typedef Documentation
fsimage_t
typedef struct fsimage_s fsimage_t
Function Documentation
fsimage_close()
int fsimage_close (struct disk_image_s * image)
Referenced by disk_image_close(), fsimage_media_destroy(), and fsimage_open().
fsimage_fd_get()
void * fsimage_fd_get (const disk_image_t * image)
Get file descriptor for image.
Parameters
[in] image disk image
Returns
file descriptor
XXX: image should not be const, since we return the a member we later use to manipulate the image.
Referenced by disk_image_fsimage_fd_get().
fsimage_init()
void fsimage_init (void)
Referenced by disk_image_init().
fsimage_media_create()
void fsimage_media_create (struct disk_image_s * image)
Referenced by disk_image_media_create().
fsimage_media_destroy()
void fsimage_media_destroy (struct disk_image_s * image)
Referenced by disk_image_media_destroy().
fsimage_name_get()
const char * fsimage_name_get (const struct disk_image_s * image)
fsimage_name_set()
void fsimage_name_set (disk_image_t * image, const char * name)
Set image name.
Parameters
[in] name image name
Referenced by disk_image_fsimage_name_set(), and disk_image_name_set().
fsimage_open()
int fsimage_open (struct disk_image_s * image)
< read mode (binary)
< read/write mode
< read mode (binary)
Referenced by disk_image_open().
fsimage_read_sector()
int fsimage_read_sector (const struct disk_image_s * image, uint8_t * buf, const struct disk_addr_s * dadr)
fsimage_size()
off_t fsimage_size (const disk_image_t * image)
Referenced by disk_image_size().
fsimage_write_sector()
int fsimage_write_sector (struct disk_image_s * image, const uint8_t * buf, const struct disk_addr_s * dadr)