vsid: c64/plus60k.h File Reference
plus60k.h File Reference
#include "types.h"
Functions
int plus60k_resources_init (void)
void plus60k_resources_shutdown (void)
int plus60k_cmdline_options_init (void)
void plus60k_init (void)
void plus60k_reset (void)
void plus60k_shutdown (void)
void plus60k_ram_inject (uint16_t addr, uint8_t value)
void plus60k_vicii_mem_vbank_store (uint16_t addr, uint8_t value)
void plus60k_vicii_mem_vbank_39xx_store (uint16_t addr, uint8_t value)
void plus60k_vicii_mem_vbank_3fxx_store (uint16_t addr, uint8_t value)
void plus60k_ram_hi_store (uint16_t addr, uint8_t value)
uint8_t plus60k_ram_read (uint16_t addr)
void plus60k_ram_store (uint16_t addr, uint8_t value)
int set_plus60k_enabled (int value, int disable_reset)
int plus60k_snapshot_write (struct snapshot_s *s)
int plus60k_snapshot_read (struct snapshot_s *s)
Variables
int plus60k_enabled
int plus60k_base
Function Documentation
plus60k_cmdline_options_init()
int plus60k_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
plus60k_init()
void plus60k_init (void)
Referenced by machine_specific_init().
plus60k_ram_hi_store()
void plus60k_ram_hi_store (uint16_t addr, uint8_t value)
Referenced by plus60k_init_config().
plus60k_ram_inject()
void plus60k_ram_inject (uint16_t addr, uint8_t value)
Referenced by memory_hacks_ram_inject().
plus60k_ram_read()
uint8_t plus60k_ram_read (uint16_t addr)
Referenced by plus60k_init_config().
plus60k_ram_store()
void plus60k_ram_store (uint16_t addr, uint8_t value)
Referenced by plus60k_init_config(), and plus60k_ram_inject().
plus60k_reset()
void plus60k_reset (void)
Referenced by machine_specific_reset(), and plus60k_activate().
plus60k_resources_init()
int plus60k_resources_init (void)
Referenced by machine_resources_init().
plus60k_resources_shutdown()
void plus60k_resources_shutdown (void)
Referenced by machine_resources_shutdown().
plus60k_shutdown()
void plus60k_shutdown (void)
Referenced by machine_specific_shutdown().
plus60k_snapshot_read()
int plus60k_snapshot_read (struct snapshot_s * s)
Referenced by memhacks_snapshot_read_modules().
plus60k_snapshot_write()
int plus60k_snapshot_write (struct snapshot_s * s)
Referenced by memhacks_snapshot_write_modules().
plus60k_vicii_mem_vbank_39xx_store()
void plus60k_vicii_mem_vbank_39xx_store (uint16_t addr, uint8_t value)
Referenced by plus60k_init_config().
plus60k_vicii_mem_vbank_3fxx_store()
void plus60k_vicii_mem_vbank_3fxx_store (uint16_t addr, uint8_t value)
Referenced by plus60k_init_config().
plus60k_vicii_mem_vbank_store()
void plus60k_vicii_mem_vbank_store (uint16_t addr, uint8_t value)
Referenced by plus60k_init_config().
set_plus60k_enabled()
int set_plus60k_enabled (int value, int disable_reset)
Referenced by memhacks_snapshot_read_modules(), plus60k_snapshot_read(), and set_memory_hack().
Variable Documentation
plus60k_base
int plus60k_base extern
Referenced by plus60k_activate(), plus60k_snapshot_read(), plus60k_snapshot_write(), and set_plus60k_base().
plus60k_enabled
int plus60k_enabled extern
Referenced by plus60k_init_config(), plus60k_ram_read(), plus60k_ram_store(), plus60k_shutdown(), set_plus60k_base(), set_plus60k_enabled(), and set_plus60k_filename().