x128: c1541.c File Reference
c1541.c File Reference
Stand-alone disk image maintenance program.
#include "vice.h"
#include <stdio.h>
#include <ctype.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include <errno.h>
#include <limits.h>
#include <string.h>
#include "attach.h"
#include "diskconstants.h"
#include "diskimage.h"
#include "fsimage.h"
#include "diskcontents-block.h"
#include "machine.h"
#include "version.h"
#include "vicedate.h"
#include <fcntl.h>
#include <strings.h>
#include "archdep.h"
#include "cbmdos.h"
#include "cbmimage.h"
#include "charset.h"
#include "cmdline.h"
#include "drive.h"
#include "fileio.h"
#include "fsimage-check.h"
#include "gcr.h"
#include "imagecontents.h"
#include "lib.h"
#include "log.h"
#include "serial.h"
#include "tape.h"
#include "util.h"
#include "vdrive-bam.h"
#include "vdrive-command.h"
#include "vdrive-dir.h"
#include "vdrive-iec.h"
#include "vdrive-rel.h"
#include "vdrive.h"
#include "zipcode.h"
#include "p64.h"
#include "fileio/p00.h"
#include "lib/linenoise-ng/linenoise.h"
#include <unistd.h>
Data Structures
struct link_s
Track/Sector link object.
struct command_s
c1541 command data struct
Macros
#define MAXARG 256 + 5
we want the NG header, not the old one in arch/gtk3:
#define RAW_BLOCK_SIZE 256
size of a block/sector, including the (track,sector) pointer
#define BLOCK_CMD_WIDTH 16
Number of bytes to display per line for the block command.
#define LOOKUP_NOTFOUND -1
Return code for lookup_command(): command not found.
#define LOOKUP_AMBIGUOUS -2
Return code for lookup_command(): input matches multiple commands.
#define BAM_SECTOR_HEADER_MAX_SECTORS 256
Maximum sector numbers to print in the sector header.
#define BAM_SECTOR_HEADER_MAX_STRLEN
Size of a sector number header line.
#define P00_HDR_LEN 0x1a
#define P00_HDR_MAGIC 0x00
#define P00_HDR_MAGIC_LEN 0x08
#define P00_HDR_NAME 0x08
#define P00_HDR_NAME_LEN 0x10
#define P00_HDR_REL_RECLEN 0x19
#define SLOT_GEOS_FILE_STRUC 23
Offset to geos file structure byte.
#define SLOT_GEOS_FILE_TYPE
#define GEOS_FILE_STRUC_SEQ 0
Geos file structure sequential (no vlir)
#define GEOS_FILE_STRUC_VLIR 1
Geos file structure VLIR (index block, max.
Typedefs
typedef struct link_s link_t
Track/Sector link object.
typedef struct command_s command_t
Functions
static int check_drive_unit (int unit)
helpers
static int check_drive_index (int index)
Check if index is a valid index into the vdrive array.
static int check_drive_ready (int index)
Check if vdrive at index is ready.
static int parse_track_sector (const char *trk_str, const char *sec_str, unsigned int *trk_num, unsigned int *sec_num)
Parse trk_str and sec_str for track and sector numbers.
static const char * image_format_name (unsigned int type)
Get image type name from type number.
static int attach_cmd (int nargs, char **args)
command handlers
static int bam_cmd (int nargs, char **args)
Show BAM of an attached image.
static int bcopy_cmd (int nargs, char **args)
Copy block to another block.
static int bfill_cmd (int nargs, char **args)
Fill a block using a single value.
static int block_cmd (int nargs, char **args)
'block' command handler
static int bpeek_cmd (int nargs, char **args)
'peek' some data from a block
static int bpoke_cmd (int nargs, char **args)
'poke' some data into a block
static int bread_cmd (int nargs, char **args)
Read a block from an image and write it to the host file system.
static int bwrite_cmd (int nargs, char **args)
Read a block from the host file system and write it to an image.
static int cd_cmd (int nargs, char **args)
Change current host directory path.
static int chain_cmd (int nargs, char **args)
Follow and print a block chain.
static int copy_cmd (int nargs, char **args)
Copy one or more files.
static int delete_cmd (int nargs, char **args)
Delete (scratch) file(s) from disk image(s)
static int entry_cmd (int nargs, char **args)
Show directory entries of file(s) on disk image(s) in low-level detail.
static int extract_cmd (int nargs, char **args)
static int extract_geos_cmd (int nargs, char **args)
static int format_cmd (int nargs, char **args)
Format a virtual floppy.
static int help_cmd (int nargs, char **args)
static int info_cmd (int nargs, char **args)
'info' command handler
static int list_cmd (int nargs, char **args)
Show directory listing of a drive.
static int name_cmd (int nargs, char **args)
Change disk name and id.
static int p00save_cmd (int nargs, char **args)
Enable\disable saving of files as P00.
static int pwd_cmd (int nargs, char **args)
Print current working directory.
static int quit_cmd (int nargs, char **args)
static int raw_cmd (int nargs, char **args)
static int read_cmd (int nargs, char **args)
static int read_geos_cmd (int nargs, char **args)
static int rename_cmd (int nargs, char **args)
Rename a file.
static int silent_cmd (int nargs, char **args)
Disable all logging.
static int tape_cmd (int nargs, char **args)
Copy files from a tape image to current drive unit.
static int unit_cmd (int nargs, char **args)
Select current device.
static int unlynx_cmd (int nargs, char **args)
Unlynx a Lynx container onto a virtual device.
static int unzip_cmd (int nargs, char **args)
static int validate_cmd (int nargs, char **args)
Validate contents of a drive.
static int verbose_cmd (int nargs, char **args)
Be verbose - enable output of extra logging information.
static int version_cmd (int nargs, char **args)
Display version number.
static int write_cmd (int nargs, char **args)
Write a file from the host FS to a virtual device.
static int write_geos_cmd (int nargs, char **args)
static int disable_libdebug_output_cmd (int nargs, char **args)
Disable lib.c debug output.
static int open_image (int dev, char *name, int create, int disktype)
other functions
int internal_read_geos_file (int unit, FILE *outf, char *src_name_ascii)
static int fix_ts (int unit, unsigned int trk, unsigned int sec, unsigned int next_trk, unsigned int next_sec, unsigned int blk_offset)
static int internal_write_geos_file (int unit, FILE *f)
struct vdrive_s * file_system_get_vdrive (unsigned int unit)
static int split_args (const char *line, int *nargs, char **args)
Split line into a list of arguments.
static int arg_to_int (const char *arg, int *return_value)
Convert arg to int.
static void print_error_message (int errval)
Print error message for errval on stderr.
static int lookup_command (const char *cmd)
Look up cmd in the command list.
static int lookup_and_execute_command (int nargs, char **args)
Look up cmd and execute.
static int extract_unit_from_file_name (char *name, char **endptr)
Parse and validate unit number from a '<unit>:' string.
static int is_valid_cbm_file_name (const char *name)
Check if name is a valid filename.
static link_t * link_add (link_t *link, unsigned int track, unsigned int sector)
Add (track, sector) to links.
static void link_free (link_t *link)
unused at the moment, but useful for debugging
static link_t * link_find (link_t *link, unsigned int track, unsigned int sector)
Find linked list node for (track, sector)
static int open_disk_image (vdrive_t *vdrive, const char *name, unsigned int unit)
Open a disk image.
static void close_disk_image (vdrive_t *vdrive, int unit)
Close disk (image) attached to vdrive.
static int parse_unit_number (const char *s)
Parse s for a unit number.
static int use_opencbm (char *name)
Here are the commands.
static void bam_print_sector_header (int sectors)
Print a sector numbers header for a BAM dump.
static int bam_print_tracks (vdrive_t *vdrive, unsigned int track_min, unsigned int track_max)
Print BAM bitmap for tracks track_min to track_max inclusive.
static void print_side_sector_group (vdrive_t *vdrive, unsigned track, unsigned sector, int group, unsigned *side_sector_number, unsigned *data_block_number)
Print a side-sector-group, which is at most 6 side sectors.
static int write_p00_header (FILE *fd, const uint8_t *petname)
static int extract_cmd_common (int nargs, char **args, int geos)
Extract all files gwesp.nosp@m.@cos.nosp@m.y.sbg.nosp@m..ac..nosp@m.at.
static int match_sub_pattern (const char *name, int type, const char *pattern, int plen)
Match name and type against pattern.
static int list_file_matches_pattern (const char *name, const char *type, const char *pattern)
Test a file name and type against pattern.
static int check_geos_convert_file (FILE *f)
do some sanity checks, reject files that are clearly not valid convert files
static int unlynx_loop (FILE *f, FILE *f2, vdrive_t *vdrive, long dentries)
int main (int argc, char **argv)
Program driver.
Variables
static const char * cbm_filetypes []
CBM DOS file type strings.
static const char p00_header [] = "C64File"
Magic bytes for a P00 header.
static unsigned int p00save [4] = { 0, 0, 0, 0 }
Flags for each virtual drive indicating P00 mode.
static int drive_index = 0
Current virtual drive used.
static int interactive_mode = 0
Flag indicating if c1541 is used in interactive mode.
static vdrive_t * drives [4] = { NULL, NULL, NULL, NULL }
Array of virtual drives.
const command_t command_list []
List of commands.
Detailed Description
Stand-alone disk image maintenance program.
Author
Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it
Teemu Rantanen tvr@c.nosp@m.s.hu.nosp@m.t.fi
Jouko Valta jopi@.nosp@m.zomb.nosp@m.ie.ou.nosp@m.lu.f.nosp@m.i
Gerhard Wesp gwesp.nosp@m.@cos.nosp@m.y.sbg.nosp@m..ac..nosp@m.at
Daniel Sladic sladi.nosp@m.c@ee.nosp@m.cg.to.nosp@m.ront.nosp@m.o.edu
Ricardo Ferreira storm.nosp@m.@eso.nosp@m.teric.nosp@m.a.pt
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Patches by Olaf Seibert rhial.nosp@m.to@f.nosp@m.alu.n.nosp@m.l Dirk Schnorpfeil D.Sch.nosp@m.norp.nosp@m.feil@.nosp@m.web..nosp@m.de (GEOS stuff)
Zipcode implementation based on ‘zip2disk’ by Paul David Doherty h0142.nosp@m.kdd@.nosp@m.rz.hu.nosp@m.-ber.nosp@m.lin.d.nosp@m.e
Macro Definition Documentation
BAM_SECTOR_HEADER_MAX_SECTORS
#define BAM_SECTOR_HEADER_MAX_SECTORS 256
Maximum sector numbers to print in the sector header.
BAM_SECTOR_HEADER_MAX_STRLEN
#define BAM_SECTOR_HEADER_MAX_STRLEN
Value:
        (BAM_SECTOR_HEADER_MAX_SECTORS + \
        ((BAM_SECTOR_HEADER_MAX_SECTORS / 8) - 1))
Size of a sector number header line.
BLOCK_CMD_WIDTH
#define BLOCK_CMD_WIDTH 16
Number of bytes to display per line for the block command.
Normally, on 80 character terminals, 16 bytes is a decent number.
GEOS_FILE_STRUC_SEQ
#define GEOS_FILE_STRUC_SEQ 0
Geos file structure sequential (no vlir)
GEOS_FILE_STRUC_VLIR
#define GEOS_FILE_STRUC_VLIR 1
Geos file structure VLIR (index block, max.
127 chains)
LOOKUP_AMBIGUOUS
#define LOOKUP_AMBIGUOUS -2
Return code for lookup_command(): input matches multiple commands.
LOOKUP_NOTFOUND
#define LOOKUP_NOTFOUND -1
Return code for lookup_command(): command not found.
MAXARG
#define MAXARG 256 + 5
we want the NG header, not the old one in arch/gtk3:
maximum number arguments to a command, the +5 comes from the bpoke() command, that one uses 5 args for its name, unit, track, sector, offset. And another max 256 for its data
P00_HDR_LEN
#define P00_HDR_LEN 0x1a
P00_HDR_MAGIC
#define P00_HDR_MAGIC 0x00
P00_HDR_MAGIC_LEN
#define P00_HDR_MAGIC_LEN 0x08
P00_HDR_NAME
#define P00_HDR_NAME 0x08
P00_HDR_NAME_LEN
#define P00_HDR_NAME_LEN 0x10
P00_HDR_REL_RECLEN
#define P00_HDR_REL_RECLEN 0x19
RAW_BLOCK_SIZE
#define RAW_BLOCK_SIZE 256
size of a block/sector, including the (track,sector) pointer
SLOT_GEOS_FILE_STRUC
#define SLOT_GEOS_FILE_STRUC 23
Offset to geos file structure byte.
SLOT_GEOS_FILE_TYPE
#define SLOT_GEOS_FILE_TYPE
Value:
          24  /* Offset to geos file type
          */
Typedef Documentation
command_t
typedef struct command_s command_t
link_t
typedef struct link_s link_t
Track/Sector link object.
Used in the chain command to detect cyclic references. Could perhaps be reused for other commands, in which case it would make sense to add a prev node to be able to iterate both ways and print links in their proper order.
Function Documentation
arg_to_int()
static int arg_to_int (const char * arg, int * return_value) static
Convert arg to int.
This function accepts multiple bases, depending on the prefix of the arg.
Basically it comes down to this (all resolve to 42 decimal)
prefix base example
[none] 10 042
% 2 %101010
& 8 &52
$ 16 $2a
0[bB] 2 0b%101010
0[xX] 16 0x2a
Parameters
[in] arg string containing a possible integer literal
[out] return_value arg convert to int
Returns
0 on success, -1 on failure
Note
on error, return_value is set to INT_MIN
Referenced by attach_cmd(), bcopy_cmd(), bfill_cmd(), block_cmd(), bpeek_cmd(), bpoke_cmd(), bread_cmd(), bwrite_cmd(), chain_cmd(), extract_cmd_common(), format_cmd(), info_cmd(), name_cmd(), parse_track_sector(), and parse_unit_number().
attach_cmd()
static int attach_cmd (int nargs, char ** args) static
command handlers
'attach' command handler
Attach a disk image to a virtual drive. Syntax: attach <image-file> [<unit-number>], where unit-number must be 8-11.
Parameters
[in] nargs number of arguments
[in] args argument list
Returns
0 on success, FD_BADDEV on failure
bam_cmd()
static int bam_cmd (int nargs, char ** args) static
Show BAM of an attached image.
Display a bitmap of used/free sectors for each track in the image
Syntax:
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK on success, < 0 on failure
< Illegal track number
< Illegal value
< Illegal value
bam_print_sector_header()
static void bam_print_sector_header (int sectors) static
Print a sector numbers header for a BAM dump.
Prints a two line header with sector numbers, with a space between each block of eight sectors
Parameters
[in] sectors number of sector number to print
Referenced by bam_cmd().
bam_print_tracks()
static int bam_print_tracks (vdrive_t * vdrive, unsigned int track_min, unsigned int track_max) static
Print BAM bitmap for tracks track_min to track_max inclusive.
Parameters
[in] vdrive vdrive object
[in] track_min starting track number
[in] track_max last track number
Returns
FD_OK on success, < 0 on failure
unsigned char *bitmap = vdrive_bam_get_track_entry(vdrive, track, 0);
Referenced by bam_cmd().
bcopy_cmd()
static int bcopy_cmd (int nargs, char ** args) static
Copy block to another block.
Copies a single block (sector) to another block, optionally between different units.
Syntax: bcopy <src_trk> <src_sec> <dst_trk> <dst_sec> [<src_unit> [<dst_unit>]]
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK on success < 0 on failure
< size of a block/sector, including the (track,sector) pointer
don't do this as vdrive does the logical to physical sector mapping
bfill_cmd()
static int bfill_cmd (int nargs, char ** args) static
Fill a block using a single value.
Syntax: bfill <track> <sector>
[<unit>]
Parameters
nargs number of args (including the command name)
args argument list
Returns
FD_OK on success, < 0 on failure
< size of a block/sector, including the (track,sector) pointer
< Illegal value
don't do this as vdrive does the logical to physical sector mapping
< size of a block/sector, including the (track,sector) pointer
block_cmd()
static int block_cmd (int nargs, char ** args) static
'block' command handler
Display a hex dump of a block on a device Syntax: block <track> <sector> [<offset>] [<unit>]
Parameters
[in] nargs number of arguments
[in] args argument list
Returns
0 on success, < 0 on failure: FD_BAD_TS, FD_BADVAL, FD_BADDEC, FD_NOTREADY, FD_RDERR
< size of a block/sector, including the (track,sector) pointer
< Illegal value
< size of a block/sector, including the (track,sector) pointer
< Illegal value
don't do this as vdrive does the logical to physical sector mapping
< size of a block/sector, including the (track,sector) pointer
< size of a block/sector, including the (track,sector) pointer
bpeek_cmd()
static int bpeek_cmd (int nargs, char ** args) static
'peek' some data from a block
Syntax: bpeek [unit-specifier] track sector [start=0 [end=$ff]]
For example: `bpoke @11: 18 0 0x90 $af
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK, or < 0 on failure
< size of a block/sector, including the (track,sector) pointer
< Illegal value
< Illegal value
< Illegal value
< Illegal value
bpoke_cmd()
static int bpoke_cmd (int nargs, char ** args) static
'poke' some data into a block
Syntax: bpoke [unit-specifier] track sector data ...
For example: bpoke @11: 18 0 $90 $43 $4f $4d $50 $58 $59, this will write 'compyx' to the disk name of a 1541 image attached at unit 11.
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK, or < 0 on failure
< size of a block/sector, including the (track,sector) pointer
< Illegal value
don't do this as vdrive does the logical to physical sector mapping
< size of a block/sector, including the (track,sector) pointer
< Illegal value
bread_cmd()
static int bread_cmd (int nargs, char ** args) static
Read a block from an image and write it to the host file system.
Syntax: bread <filename> <track> <sector> [<unit>]
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK on success, < 0 on failure
Todo:
Add tilde expansion on filename for *nix systems
< size of a block/sector, including the (track,sector) pointer
don't do this as vdrive does the logical to physical sector mapping
< size of a block/sector, including the (track,sector) pointer
< size of a block/sector, including the (track,sector) pointer
bwrite_cmd()
static int bwrite_cmd (int nargs, char ** args) static
Read a block from the host file system and write it to an image.
Syntax: bwrite <filename> <track> <sector> [<unit>]
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK on success, < 0 on failure
Todo:
Add tilde expansion on filename for *nix systems
< size of a block/sector, including the (track,sector) pointer
don't do this as vdrive does the logical to physical sector mapping
< size of a block/sector, including the (track,sector) pointer
< size of a block/sector, including the (track,sector) pointer
cd_cmd()
static int cd_cmd (int nargs, char ** args) static
Change current host directory path.
Syntax: cd <hostdir>
Where hostdir is the path to directory on the host
Parameters
[in] nargs number of arguments
[in] args optional arguments (unused
Returns
0 on success, < 0 on failure
< Illegal filename
chain_cmd()
static int chain_cmd (int nargs, char ** args) static
Follow and print a block chain.
Parameters
[in] nargs number of arguments
[in] args argument list
Returns
FD_OK on success, < 0 on failure
Todo:
proper layout, it's a bit ugly now
< Illegal filename
don't do this as vdrive does the logical to physical sector mapping
< size of a block/sector, including the (track,sector) pointer
check_drive_index()
static int check_drive_index (int index) static
Check if index is a valid index into the vdrive array.
Parameters
[in] index index in vdrive array
Returns
0 (FD_OK) on success, < 0 (FD_BADDEV) on failure
Referenced by check_drive_ready(), and list_cmd().
check_drive_ready()
static int check_drive_ready (int index) static
Check if vdrive at index is ready.
Parameters
[in] index index in the vdrive array
Returns
0 (FD_OK) on success, < 0 (FD_BADDEV or FD_NOTREADY) on failure
Referenced by bam_cmd(), bcopy_cmd(), bfill_cmd(), block_cmd(), bpoke_cmd(), bread_cmd(), bwrite_cmd(), chain_cmd(), copy_cmd(), delete_cmd(), entry_cmd(), extract_cmd_common(), format_cmd(), info_cmd(), list_cmd(), name_cmd(), read_cmd(), read_geos_cmd(), and write_geos_cmd().
check_drive_unit()
static int check_drive_unit (int unit) static
helpers
Check if unit is a valid drive unit number.
Parameters
[in] unit number as on the real machine
Returns
0 (FD_OK) on success, < 0 (FD_BADDEV) on failure
Referenced by attach_cmd(), bcopy_cmd(), bfill_cmd(), block_cmd(), bread_cmd(), bwrite_cmd(), chain_cmd(), extract_cmd_common(), extract_unit_from_file_name(), format_cmd(), info_cmd(), name_cmd(), and parse_unit_number().
check_geos_convert_file()
static int check_geos_convert_file (FILE * f) static
do some sanity checks, reject files that are clearly not valid convert files
Referenced by write_geos_cmd().
close_disk_image()
static void close_disk_image (vdrive_t * vdrive, int unit) static
Close disk (image) attached to vdrive.
Parameters
[in,out] vdrive virtual drive
[in] unit unit number
< opencbm
Referenced by quit_cmd().
copy_cmd()
static int copy_cmd (int nargs, char ** args) static
Copy one or more files.
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK on success, or < 0 on failure
< Illegal filename
< for relative files
delete_cmd()
static int delete_cmd (int nargs, char ** args) static
Delete (scratch) file(s) from disk image(s)
Delete one or more files. Each file can have a unit number (\<unit>:) in front of it to indicate which unit to use.
Parameters
[in] nargs argument count
[in] args argument list
Returns
0 on success, < 0 on failure
disable_libdebug_output_cmd()
static int disable_libdebug_output_cmd (int nargs, char ** args) static
Disable lib.c debug output.
Debug hook: This should only be used when testing c1541's output with the test bench, so the c1541 test bench can be used on both no-debug and debug builds when parsing the output of c1541, without the output of lib.c getting in the way.
Parameters
[in] nargs argument count
[in args argument list
Returns
0
entry_cmd()
static int entry_cmd (int nargs, char ** args) static
Show directory entries of file(s) on disk image(s) in low-level detail.
Parameters
[in] nargs argument count
[in] args argument list
Returns
0 on success, < 0 on failure
< for relative files
< same on CMD (year to minute)
extract_cmd()
static int extract_cmd (int nargs, char ** args) static
extract_cmd_common()
static int extract_cmd_common (int nargs, char ** args, int geos) static
Extract all files gwesp.nosp@m.@cos.nosp@m.y.sbg.nosp@m..ac..nosp@m.at.
Todo:
FIXME: This does not work with non-standard file names.
Todo:
FIXME: I added P00 support, but it's a little shitty
< D64 image, 35 tracks
< D64 image, 35 tracks
< lenght of a PETSCII filename
< lenght of a PETSCII filename
< lenght of a PETSCII filename
Todo:
clean up this mess
< write mode (binary)
< write mode (binary)
Todo:
FIXME: status is never read
Referenced by extract_cmd(), and extract_geos_cmd().
extract_geos_cmd()
static int extract_geos_cmd (int nargs, char ** args) static
extract_unit_from_file_name()
static int extract_unit_from_file_name (char * name, char ** endptr) static
Parse and validate unit number from a '<unit>:' string.
Parameters
[in] name string to parse
[out] endptr pointer to string after the '<unit>:' stuff
Returns
unit number if successful, 0 if no '<unit>:' was found, -1 if the parsed unit number is invalid
Referenced by bpeek_cmd(), bpoke_cmd(), chain_cmd(), copy_cmd(), delete_cmd(), entry_cmd(), list_cmd(), read_cmd(), and read_geos_cmd().
file_system_get_vdrive()
struct vdrive_s * file_system_get_vdrive (unsigned int unit)
fix_ts()
static int fix_ts (int unit, unsigned int trk, unsigned int sec, unsigned int next_trk, unsigned int next_sec, unsigned int blk_offset) static
Referenced by internal_write_geos_file().
format_cmd()
static int format_cmd (int nargs, char ** args) static
Format a virtual floppy.
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK on success, or < 0 on failure
Todo:
change into table lookup
< D9090/D9060
< Illegal value
< ID mismatch (Disk or tape)
< Illegal value
< Illegal filename
help_cmd()
static int help_cmd (int nargs, char ** args) static
image_format_name()
static const char * image_format_name (unsigned int type) static
Get image type name from type number.
Parameters
[in] type on of the VDRIVE_FORMAT_TYPE constants
Returns
image type string or NULL when not found
XXX: Should probably be moved to vdrive somewhere
< Dual Disk Drive
< Dual Disk Drive
< Dual Disk Drive
Referenced by bam_cmd(), and info_cmd().
info_cmd()
static int info_cmd (int nargs, char ** args) static
'info' command handler
Parameters
[in] nargs argument count
[in] args argument list
Returns
0 on success, < 0 on failure (FD_BADDEV, FD_NOTREADY)
internal_read_geos_file()
int internal_read_geos_file (int unit, FILE * outf, char * src_name_ascii)
< Offset to geos file structure byte
Referenced by extract_cmd_common(), and read_geos_cmd().
internal_write_geos_file()
static int internal_write_geos_file (int unit, FILE * f) static
< Offset to geos file structure byte
Referenced by write_geos_cmd().
is_valid_cbm_file_name()
static int is_valid_cbm_file_name (const char * name) static
Check if name is a valid filename.
Parameters
[in] name filename
Returns
bool
Referenced by chain_cmd(), copy_cmd(), delete_cmd(), entry_cmd(), read_cmd(), and read_geos_cmd().
link_add()
static link_t * link_add (link_t * link, unsigned int track, unsigned int sector) static
Add (track, sector) to links.
Parameters
[in] link linked list with track/sector links
[in] track track number
[in] sector sector number
Returns
new head of the linked list
Referenced by chain_cmd().
link_find()
static link_t * link_find (link_t * link, unsigned int track, unsigned int sector) static
Find linked list node for (track, sector)
Parameters
[in] link linked list node to start looking
[in] track track number
[in] sector track sector
Returns
node when found or NULL when not found
Referenced by chain_cmd().
link_free()
static void link_free (link_t * link) static
unused at the moment, but useful for debugging
Free linked list
Parameters
[in] link linked list node
Referenced by chain_cmd().
list_cmd()
static int list_cmd (int nargs, char ** args) static
Show directory listing of a drive.
Parameters
[in] nargs number of arguments
[in] args argument list
Returns
0 on success, < 0 on failure (FD_NOTREADY)
!
Todo:
FIXME: diskcontents_read internally opens/closes the disk image, including a complete reset of internal vdrive variables. this makes things like changing sub partitions and sub directories inside images impossible from the c1541 shell.
unsigned int drive = 0;
name = disk_image_name_get(vdrive->image);
listing = diskcontents_read(name, (unsigned int)(dnr + DRIVE_UNIT_MIN), drive);
< convert string to ASCII
< convert string to ASCII
< convert string to ASCII
< convert string to ASCII
list_file_matches_pattern()
static int list_file_matches_pattern (const char * name, const char * type, const char * pattern) static
Test a file name and type against pattern.
This function can handle multiple patterns separated by commas, and supports specifying a file type per sub pattern.
Example: "foo*=p,b?r*=s", will match PRG files against "foo*" and SEQ files against "b?r*". A match is found if any of the sub patterns matches (in other words: OR).
WARNING: It appears CBM DOS only allows a single file type test, use two or more results in a ?FILE NOT FOUND ERROR. The =X specifier can also only come last, anything after =X results in an error. (In C1541 this doesn't matter, but in VDrive it does).
Parameters
[in] name filename
[in] type filetype (eg " prg<")
[in] pattern pattern to match against
Returns
bool
Referenced by list_cmd().
lookup_and_execute_command()
static int lookup_and_execute_command (int nargs, char ** args) static
Look up cmd and execute.
Parameters
[in] nargs number of arguments in args
[in] args arguments
Returns
0 on success, -1 on failure
lookup_command()
static int lookup_command (const char * cmd) static
Look up cmd in the command list.
Parameters
[in] cmd command name or part of command name
Returns
index in command array on success, < 0 on failure
Referenced by help_cmd(), and lookup_and_execute_command().
main()
int main (int argc, char ** argv)
Program driver.
Parameters
[in] argc argument count
[in] argv argument vector
Returns
EXIT_SUCCESS or EXIT_FAILURE
< maximum number arguments to a command, the +5 comes from the bpoke() command, that one uses 5 args for its name, unit, track, sector, offset. And another max 256 for its data
< maximum number arguments to a command, the +5 comes from the bpoke() command, that one uses 5 args for its name, unit, track, sector, offset. And another max 256 for its data
Todo:
Add completions on Windows, somehow, or perhaps not
< maximum number arguments to a command, the +5 comes from the bpoke() command, that one uses 5 args for its name, unit, track, sector, offset. And another max 256 for its data
match_sub_pattern()
static int match_sub_pattern (const char * name, int type, const char * pattern, int plen) static
Match name and type against pattern.
Matches name against pattern and optionally against filetype type if present in the pattern. The pattern is the standard CBM wildcard pattern: '*' and '?' with optional '=X' where X is one of S, P or R.
Parameters
[in] name filename
[in] type filetype
[in] pattern wildcard pattern
]in] plen length of pattern
return bool
Referenced by list_file_matches_pattern().
name_cmd()
static int name_cmd (int nargs, char ** args) static
Change disk name and id.
Syntax: name "diskname[,id]" [unit]
Parameters
[in] nargs argument count
[in] args argument list
Returns
0 on succes, < 0 on failure (FD_BADEV or FD_NOTREADY)
< standard length of container names, such as D64
< length of a disk ID
open_disk_image()
static int open_disk_image (vdrive_t * vdrive, const char * name, unsigned int unit) static
Open a disk image.
Depending on name, this either opens a block device (a seekable device, such as an USB stick), a character device (a real drive using OpenCBM) or an image stored on the host file system.
Parameters
[in,out] vdrive virtual drive
[in] name path to disk image file/data
[in] unit unit to attach disk to
Returns
0 on success <0 on failure
< raw device
< opencbm
< real IEC device (opencbm)
< opencbm
< real IEC device (opencbm)
Todo:
FIXME: this will only work with a 1541 drive
< maximum number of accessible tracks for a 1541 drive: not all 1541 drives can do this
< maximum number of accessible tracks for a 1541 drive: not all 1541 drives can do this
< filesystem
Referenced by attach_cmd(), and open_image().
open_image()
static int open_image (int dev, char * name, int create, int disktype) static
other functions
Open image or create a new one.
If the file exists, it must have valid header.
The dev parameter is also used as a unit number by add 8 to it, meaning units 8-11 can be used.
Parameters
[in] dev index in the virtual drive array, must be in the range [0 .. NUM_DISK_UNITS-1]
[in] name disk/device name
[in] create create image (boolean)
[in] disktype disk type enumerator
Returns
0 on success, < 0 on failure
Referenced by format_cmd(), and unzip_cmd().
p00save_cmd()
static int p00save_cmd (int nargs, char ** args) static
Enable\disable saving of files as P00.
Syntax: p00save [<enable> [<unit>]]
Where enable is either 0 or 1.
Parameters
[in] nargs argument count
[in] args argument list
Returns
0 on success, < 0 on failure
parse_track_sector()
static int parse_track_sector (const char * trk_str, const char * sec_str, unsigned int * trk_num, unsigned int * sec_num) static
Parse trk_str and sec_str for track and sector numbers.
Parses its string arguments for track and sector numbers, no actual checking against an image is performed, so a track and sector of 100 will pass. Use drive_image_check_sector() to check if the track and sector are valid for a given image.
Parameters
[in] trk_str string containing a track number
[in] sec_str string containing a sector number
[out] trk_num object to store track number
[out] sec_num object to store sector number
Returns
FD_OK on success, FD_BAD_TRKNUM or FD_BAD_SECNUM on failure
< Illegal track number
< Illegal sector number
Referenced by bam_cmd(), bcopy_cmd(), bfill_cmd(), block_cmd(), bpeek_cmd(), bpoke_cmd(), bread_cmd(), bwrite_cmd(), and chain_cmd().
parse_unit_number()
static int parse_unit_number (const char * s) static
Parse s for a unit number.
Parses string s for a unit number, and checks if it's a valid unit number. No check if performed if the unit is actually ready (wouldn't make sense when creating/attaching to a unit)
Parameters
[in] s string to parse
Returns
unit number or FD_BADDEV on error
Referenced by bam_cmd().
print_error_message()
static void print_error_message (int errval) static
Print error message for errval on stderr.
Parameters
[in] errval error code
< File has changed on disk
< DOS Format Mismatch
< ID mismatch (Disk or tape)
< Illegal filename
< Illegal value
< Track or sector
< Illegal track number
< Illegal sector number
Referenced by lookup_and_execute_command().
print_side_sector_group()
static void print_side_sector_group (vdrive_t * vdrive, unsigned track, unsigned sector, int group, unsigned * side_sector_number, unsigned * data_block_number) static
Print a side-sector-group, which is at most 6 side sectors.
Parameters
[in] vdrive the virtual drive from which we read the sectors
[in] track the track number of the first side sector.
[in] sector the sector number of the first side sector.
[in] group when iterating over a super side sector, this is the number of the group within it.
[in,out] side_sector_number a pointer to a running counter for all side sectors belonging to the same file.
[in,out] data_block_number a pointer to a running counter for all data blocks belonging to the same file.
Returns
FD_OK on success, or < 0 on failure
don't do this as vdrive does the logical to physical sector mapping
Referenced by entry_cmd().
pwd_cmd()
static int pwd_cmd (int nargs, char ** args) static
Print current working directory.
Parameters
[in] nargs number of arguments
[in] args optional arguments (unused
Returns
0
quit_cmd()
static int quit_cmd (int nargs, char ** args) static
raw_cmd()
static int raw_cmd (int nargs, char ** args) static
read_cmd()
static int read_cmd (int nargs, char ** args) static
< Illegal filename
< Illegal filename
< lenght of a PETSCII filename
< lenght of a PETSCII filename
< lenght of a PETSCII filename
< for relative files
< Overwrites existing file, if any
< for relative files
< Overwrites existing file, if any
< for relative files
read_geos_cmd()
static int read_geos_cmd (int nargs, char ** args) static
< Illegal filename
< Illegal filename
< Illegal filename
< write mode (binary)
rename_cmd()
static int rename_cmd (int nargs, char ** args) static
Rename a file.
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK on success, < 0 on failure
< Illegal filename
< Illegal filename
silent_cmd()
static int silent_cmd (int narg, char ** args) static
Disable all logging.
split_args()
static int split_args (const char * line, int * nargs, char ** args) static
Split line into a list of arguments.
The args array is reused on each call, (re)allocating elements when required.
Parameters
[in] line input string
[out] nargs number of arguments parsed from line
[out] args arguments parsed from line
Returns
0 on success, -1 on failure
< maximum number arguments to a command, the +5 comes from the bpoke() command, that one uses 5 args for its name, unit, track, sector, offset. And another max 256 for its data
tape_cmd()
static int tape_cmd (int nargs, char ** args) static
Copy files from a tape image to current drive unit.
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK on success, < 0 on failure
< Illegal filename
unit_cmd()
static int unit_cmd (int nargs, char ** args) static
Select current device.
Parameters
[in] nargs number of arguments
[in] args argument list
Returns
0 on success, < 0 on failure
unlynx_cmd()
static int unlynx_cmd (int nargs, char ** args) static
Unlynx a Lynx container onto a virtual device.
Syntax: unlynx <filename> [<unit>]
Parameters
[in] nargs argument count
[in] args argument list
Returns
0 on success, < 0 on failure
< read mode (binary)
< read mode (binary)
unlynx_loop()
static int unlynx_loop (FILE * f, FILE * f2, vdrive_t * vdrive, long dentries) static
Todo:
FIXME: remove magic number
Todo:
FIXME: using fread() to read a single byte?
< should match FILEIO_TYPE_xxx
unzip_cmd()
static int unzip_cmd (int nargs, char ** args) static
< ID mismatch (Disk or tape)
< directory separator as an integer
Todo:
FIXME: Close image?
< read mode (binary)
< read mode (binary)
< ID mismatch (Disk or tape)
use_opencbm()
static int use_opencbm (char * name) static
Here are the commands.
Referenced by attach_cmd().
validate_cmd()
static int validate_cmd (int nargs, char ** args) static
Validate contents of a drive.
Parameters
[in] nargs argument count
[in] args argument list
Returns
0 on success, < 0 on failure
verbose_cmd()
static int verbose_cmd (int nargs, char ** args) static
Be verbose - enable output of extra logging information.
If 'off' is given as an argument, verbose is turned off again.
Parameters
[in] nargs argument count
[in] args argument list
Returns
0
version_cmd()
static int version_cmd (int nargs, char ** args) static
Display version number.
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK
write_cmd()
static int write_cmd (int nargs, char ** args) static
Write a file from the host FS to a virtual device.
Parameters
[in] nargs argument count
[in] args argument list
Returns
FD_OK on success, < 0 on failure
write_geos_cmd()
static int write_geos_cmd (int nargs, char ** args) static
< read mode (binary)
write_p00_header()
static int write_p00_header (FILE * fd, const uint8_t * petname) static
Referenced by extract_cmd_common().
Variable Documentation
cbm_filetypes
const char* cbm_filetypes[] static
Initial value:
= {
    "del", "seq", "prg", "usr", "rel", "cbm", "dir", "007" }
CBM DOS file type strings.
Referenced by entry_cmd().
command_list
const command_t command_list[]
List of commands.
Referenced by help_cmd(), lookup_and_execute_command(), and lookup_command().
drive_index
int drive_index = 0 static
Current virtual drive used.
This is an index into the drives array, NOT a device/unit number
Referenced by attach_cmd(), bam_cmd(), bcopy_cmd(), bfill_cmd(), block_cmd(), bpeek_cmd(), bpoke_cmd(), bread_cmd(), bwrite_cmd(), chain_cmd(), copy_cmd(), delete_cmd(), entry_cmd(), format_cmd(), info_cmd(), list_cmd(), name_cmd(), raw_cmd(), read_cmd(), read_geos_cmd(), unzip_cmd(), and write_geos_cmd().
drives
vdrive_t* drives[4] = { NULL, NULL, NULL, NULL } static
Array of virtual drives.
!
Todo:
FIXME: this should be in c1541-stubs.c
Referenced by attach_cmd(), bam_cmd(), bcopy_cmd(), bfill_cmd(), block_cmd(), bpeek_cmd(), bpoke_cmd(), bread_cmd(), bwrite_cmd(), chain_cmd(), check_drive_ready(), copy_cmd(), delete_cmd(), entry_cmd(), extract_cmd_common(), fdc_reset(), file_system_get_vdrive(), fix_ts(), format_cmd(), info_cmd(), internal_read_geos_file(), internal_write_geos_file(), list_cmd(), name_cmd(), open_image(), quit_cmd(), raw_cmd(), read_cmd(), read_geos_cmd(), set_drive_true_emulation(), unzip_cmd(), and write_geos_cmd().
interactive_mode
int interactive_mode = 0 static
Flag indicating if c1541 is used in interactive mode.
Referenced by quit_cmd().
p00_header
const char p00_header[] = "C64File" static
Magic bytes for a P00 header.
Referenced by write_p00_header().
p00save
unsigned int p00save[4] = { 0, 0, 0, 0 } static
Flags for each virtual drive indicating P00 mode.
When zero, reading files from the host OS is done with FILEIO_MODE_RAW, if non-zero, reading files is done with FILEIO_MODE_P00
Referenced by extract_cmd_common(), and read_cmd().