vsid: arch/shared/archdep_chdir.c File Reference
archdep_chdir.c File Reference
Change current working directory.
#include "vice.h"
#include "archdep_defs.h"
#include <stddef.h>
#include <unistd.h>
#include "archdep_chdir.h"
Functions
int archdep_chdir (const char *path)
Change current working directory.
Detailed Description
Change current working directory.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
OS support:
Linux
Windows
BSD
MacOS
Haiku
Function Documentation
archdep_chdir()
int archdep_chdir (const char * path)
Change current working directory.
Parameters
[in] path new working directiory
Returns
0 on success, -1 on failure
Referenced by cmdline_chdir(), fliplist_load_list(), fsdevice_flush_cd(), and mon_change_dir().