vsid: screenshot.c File Reference
screenshot.c File Reference
Screenshot/video recording module.
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/time.h>
#include "gfxoutput.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "palette.h"
#include "resources.h"
#include "screenshot.h"
#include "uiapi.h"
#include "util.h"
#include "video.h"
#include "monitor.h"
#include "ui.h"
#include "vsync.h"
Macros
#define BUFFER_LINE_START(i, n) ((i)->draw_buffer + (n) * (i)->draw_buffer_line_size)
Functions
int screenshot_init (void)
Initialize module.
void screenshot_shutdown (void)
Clean up memory resources used by the module.
static void screenshot_line_data (screenshot_t *screenshot, uint8_t *data, unsigned int line, unsigned int mode)
static int screenshot_save_core (screenshot_t *screenshot, gfxoutputdrv_t *drv, const char *filename)
int screenshot_save (const char *drvname, const char *filename, struct video_canvas_s *canvas)
int screenshot_record (void)
void screenshot_stop_recording (void)
int screenshot_is_recording (void)
void screenshot_prepare_reopen (void)
void screenshot_try_reopen (void)
const char * screenshot_get_fext_for_format (const char *format)
const char * screenshot_get_quickscreenshot_format (void)
char * screenshot_create_datetime_string (void)
char * screenshot_create_quickscreenshot_filename (const char *format)
static int set_autosave_screenshot_format (const char *val, void *param)
int screenshot_resources_init (void)
static void screenshot_auto_screenshot_vsync_callback (void *param)
Callback for vsync_on_vsync_do()
void screenshot_ui_auto_screenshot (void)
Create screenshot with autogenerated filename.
Variables
static log_t screenshot_log = ((log_t)-1)
static gfxoutputdrv_t * recording_driver
static struct video_canvas_s * recording_canvas
static int reopen = 0
static char * reopen_recording_drivername
static struct video_canvas_s * reopen_recording_canvas
static char * reopen_filename
static char * autosave_screenshot_format
static resource_string_t resources_string []
Detailed Description
Screenshot/video recording module.
screenshot.c - Create a screenshot.
Written by Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de Andreas Matthies andre.nosp@m.as.m.nosp@m.atthi.nosp@m.es@g.nosp@m.mx.ne.nosp@m.t Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Macro Definition Documentation
BUFFER_LINE_START
#define BUFFER_LINE_START (i, n) ((i)->draw_buffer + (n) * (i)->draw_buffer_line_size)
Function Documentation
screenshot_auto_screenshot_vsync_callback()
static void screenshot_auto_screenshot_vsync_callback (void * param) static
Callback for vsync_on_vsync_do()
Create a screenshot on vsync to avoid tearing.
This function is called on the VICE thread, so the canvas is retrieved in ui_media_auto_screenshot() on the UI thread and passed via param.
Parameters
[in] param video canvas
Referenced by screenshot_ui_auto_screenshot().
screenshot_create_datetime_string()
char * screenshot_create_datetime_string (void)
Referenced by create_proposed_audio_recording_name(), create_proposed_video_recording_name(), and screenshot_create_quickscreenshot_filename().
screenshot_create_quickscreenshot_filename()
char * screenshot_create_quickscreenshot_filename (const char * format)
Referenced by save_screenshot_handler(), and screenshot_auto_screenshot_vsync_callback().
screenshot_get_fext_for_format()
const char * screenshot_get_fext_for_format (const char * format)
Referenced by screenshot_create_quickscreenshot_filename(), and set_autosave_screenshot_format().
screenshot_get_quickscreenshot_format()
const char * screenshot_get_quickscreenshot_format (void)
Referenced by screenshot_auto_screenshot_vsync_callback().
screenshot_init()
int screenshot_init (void)
Initialize module.
Functions called by external emulator code.
Returns
0 on success (always)
Referenced by init_main().
screenshot_is_recording()
int screenshot_is_recording (void)
Referenced by screenshot_prepare_reopen(), set_video_halve_framerate(), statusbar_recording_widget_set_recording_status(), statusbar_recording_widget_set_time(), and ui_media_stop_recording().
screenshot_line_data()
static void screenshot_line_data (screenshot_t * screenshot, uint8_t * data, unsigned int line, unsigned int mode) static
Referenced by screenshot_save_core().
screenshot_prepare_reopen()
void screenshot_prepare_reopen (void)
Referenced by sid_snapshot_read_module_simple().
screenshot_record()
int screenshot_record (void)
Referenced by machine_vsync_hook().
screenshot_resources_init()
int screenshot_resources_init (void)
Referenced by init_resources().
screenshot_save()
int screenshot_save (const char * drvname, const char * filename, struct video_canvas_s * canvas)
Referenced by mon_screenshot_save(), on_save_video_filename(), save_screenshot_vsync_callback(), screenshot_at_exit(), screenshot_auto_screenshot_vsync_callback(), and screenshot_try_reopen().
screenshot_save_core()
static int screenshot_save_core (screenshot_t * screenshot, gfxoutputdrv_t * drv, const char * filename) static
Referenced by screenshot_record(), and screenshot_save().
screenshot_shutdown()
void screenshot_shutdown (void)
Clean up memory resources used by the module.
Referenced by machine_shutdown().
screenshot_stop_recording()
void screenshot_stop_recording (void)
Referenced by ffmpegexe_soundmovie_close(), ffmpegexedrv_init_file(), ui_media_stop_recording(), zmbv_soundmovie_close(), and zmbvdrv_init_file().
screenshot_try_reopen()
void screenshot_try_reopen (void)
Referenced by sid_snapshot_read_module_simple().
screenshot_ui_auto_screenshot()
void screenshot_ui_auto_screenshot (void)
Create screenshot with autogenerated filename.
Creates a screenshot with an autogenerated filename with an ISO-8601-ish timestamp. See screenshot.c screenshot_get_quickscreenshot_filename().
Referenced by screenshot_quicksave_action().
set_autosave_screenshot_format()
static int set_autosave_screenshot_format (const char * val, void * param) static
Variable Documentation
autosave_screenshot_format
char* autosave_screenshot_format static
Referenced by screenshot_shutdown(), and set_autosave_screenshot_format().
recording_canvas
struct video_canvas_s* recording_canvas static
Referenced by screenshot_init(), screenshot_record(), screenshot_save(), and screenshot_stop_recording().
recording_driver
gfxoutputdrv_t* recording_driver static
Referenced by screenshot_init(), screenshot_is_recording(), screenshot_record(), screenshot_save(), screenshot_save_core(), and screenshot_stop_recording().
reopen
int reopen = 0 static
Referenced by screenshot_prepare_reopen(), and screenshot_try_reopen().
reopen_filename
char* reopen_filename static
Referenced by screenshot_init(), screenshot_save(), screenshot_shutdown(), and screenshot_try_reopen().
reopen_recording_canvas
struct video_canvas_s* reopen_recording_canvas static
Referenced by screenshot_save(), and screenshot_try_reopen().
reopen_recording_drivername
char* reopen_recording_drivername static
Referenced by screenshot_init(), screenshot_save(), screenshot_shutdown(), and screenshot_try_reopen().
resources_string
resource_string_t resources_string[] static
Initial value:
= {
    { "QuicksaveScreenshotFormat",  "BMP" , RES_EVENT_NO, NULL,
      &autosave_screenshot_format, set_autosave_screenshot_format, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by screenshot_resources_init().
screenshot_log
log_t screenshot_log = ((log_t)-1) static
Referenced by screenshot_init(), screenshot_line_data(), screenshot_record(), screenshot_save(), and screenshot_save_core().