vsid: arch/gtk3/widgets/plus4aciawidget.c File Reference
plus4aciawidget.c File Reference
Widget to control Plus 4 ACIA.
#include "vice.h"
#include <gtk/gtk.h>
#include "machine.h"
#include "resources.h"
#include "debug_gtk3.h"
#include "widgethelpers.h"
#include "basewidgets.h"
#include "plus4aciawidget.h"
Functions
static void on_acia_widget_toggled (GtkToggleButton *button, gpointer data)
Extra handler for the 'toggled' event of the ACIA widget.
GtkWidget * plus4_acia_widget_create (void)
Create widget to control Plus4 ACIA.
void plus4_acia_widget_sync (void)
Synchronize ACIA widget's state with its resource.
void plus4_acia_widget_add_callback (void(*callback)(GtkWidget *, int value))
Add user callback to trigger on widget changes.
Variables
static GtkWidget * instance = NULL
Reference to the Plus4 ACIA widget.
static void(* user_callback)(GtkWidget *, int) = NULL
User callback to trigger on widget value changes.
Detailed Description
Widget to control Plus 4 ACIA.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_acia_widget_toggled()
static void on_acia_widget_toggled (GtkToggleButton * button, gpointer data) static
Extra handler for the 'toggled' event of the ACIA widget.
Calls the user callback function if that is defined.
Parameters
[in] button ACIA widget
[in] data extra event data (unused)
Referenced by plus4_acia_widget_create().
plus4_acia_widget_add_callback()
void plus4_acia_widget_add_callback (void(*)(GtkWidget *, int value) callback)
Add user callback to trigger on widget changes.
When the state of the ACIA widget changes, the callback is called with two arguments: the ACIA widget and the new value (bool).
Parameters
[in] callback user callback function
Referenced by create_plus4_layout().
plus4_acia_widget_create()
GtkWidget * plus4_acia_widget_create (void)
Create widget to control Plus4 ACIA.
Returns
GtkCheckButton
Referenced by create_plus4_layout().
plus4_acia_widget_sync()
void plus4_acia_widget_sync (void)
Synchronize ACIA widget's state with its resource.
Referenced by machine_model_handler_plus4().
Variable Documentation
instance
GtkWidget* instance = NULL static
Reference to the Plus4 ACIA widget.
We can get away with this since there will only ever be a single Plus4 ACIA widget active in the UI.
Referenced by plus4_acia_widget_create(), plus4_acia_widget_sync(), vice_locking_g_signal_connect(), and vice_locking_g_signal_connect_swapped().
user_callback
void(* user_callback) (GtkWidget *, int) (GtkWidget * , int) = NULL static
User callback to trigger on widget value changes.
Optional, set via plus4_acia_widget_add_callback()
Referenced by on_acia_widget_toggled(), plus4_acia_widget_add_callback(), and plus4_acia_widget_create().