vsid: arch/gtk3/render_thread.h File Reference
render_thread.h File Reference
Centralised management of render threads enabling controlled shutdown.
#include <stdbool.h>
#include <string.h>
Typedefs
typedef enum render_job render_job_t
typedef void(* render_thread_callback_t) (void *thread_context, void *job_context)
typedef struct render_thread_s * render_thread_t
Enumerations
enum render_job {
render_thread_init = 1 ,
render_thread_render ,
render_thread_shutdown
}
Functions
render_thread_t render_thread_create (render_thread_callback_t callback, void *thread_context)
void render_thread_initiate_shutdown (render_thread_t render_thread)
void render_thread_join (render_thread_t render_thread)
void render_thread_shutdown_and_join_all (void)
void render_thread_push_job (render_thread_t render_thread, render_job_t job_context)
Detailed Description
Centralised management of render threads enabling controlled shutdown.
Author
David Hogan david.nosp@m..q.h.nosp@m.ogan@.nosp@m.gmai.nosp@m.l.com
Typedef Documentation
render_job_t
typedef enum render_job render_job_t
render_thread_callback_t
typedef void(* render_thread_callback_t) (void *thread_context, void *job_context)
render_thread_t
typedef struct render_thread_s* render_thread_t
Enumeration Type Documentation
render_job
enum render_job
Enumerator
render_thread_init
render_thread_render
render_thread_shutdown
Function Documentation
render_thread_create()
render_thread_t render_thread_create (render_thread_callback_t callback, void * thread_context)
< Current max of two windows (x128)
< Current max of two windows (x128)
Referenced by on_widget_realized().
render_thread_initiate_shutdown()
void render_thread_initiate_shutdown (render_thread_t render_thread)
Referenced by render_thread_shutdown_and_join_all().
render_thread_join()
void render_thread_join (render_thread_t render_thread)
Todo:
We should block until all jobs are done - but there's a race condition deadlock outcome here. Fix needed
Referenced by render_thread_shutdown_and_join_all().
render_thread_push_job()
void render_thread_push_job (render_thread_t render_thread, render_job_t job_context)
Referenced by vice_opengl_on_ui_frame_clock(), and vice_opengl_refresh_rect().
render_thread_shutdown_and_join_all()
void render_thread_shutdown_and_join_all (void)
Referenced by main_exit().