vsid: vsync.h File Reference
vsync.h File Reference
Data Structures
struct vsync_callback
Typedefs
typedef void(* vsync_callback_func_t) (void *param)
Manually defined.
typedef struct vsync_callback vsync_callback_t
Functions
void vsync_suspend_speed_eval (void)
void vsync_reset_hook (void)
int vsync_resources_init (void)
int vsync_cmdline_options_init (void)
void vsync_init (void(*hook)(void))
void vsync_shutdown (void)
void vsync_set_machine_parameter (double refresh_rate, long cycles)
double vsync_get_refresh_frequency (void)
void vsync_do_end_of_line (void)
bool vsync_should_skip_frame (struct video_canvas_s *canvas)
void vsync_do_vsync (struct video_canvas_s *c)
This is called at the end of each screen frame.
void vsync_on_vsync_do (vsync_callback_func_t callback_func, void *callback_param)
Call callback_func(callback_param) once at vsync time (or machine reset)
void vsync_set_warp_mode (int val)
int vsync_get_warp_mode (void)
Typedef Documentation
vsync_callback_func_t
typedef void(* vsync_callback_func_t) (void *param)
Manually defined.
To enable/disable this option by hand change the 0 below to 1.
vsync_callback_t
typedef struct vsync_callback vsync_callback_t
Function Documentation
vsync_cmdline_options_init()
int vsync_cmdline_options_init (void)
Referenced by init_cmdline_options().
vsync_do_end_of_line()
void vsync_do_end_of_line (void)
Todo:
BSD thread prio stuff
Referenced by vicii_raster_draw_alarm_handler().
vsync_do_vsync()
void vsync_do_vsync (struct video_canvas_s * c)
This is called at the end of each screen frame.
Referenced by vicii_raster_draw_alarm_handler().
vsync_get_refresh_frequency()
double vsync_get_refresh_frequency (void)
Referenced by network_test_delay().
vsync_get_warp_mode()
int vsync_get_warp_mode (void)
Referenced by actions_speed_setup_ui(), create_warp_checkbox(), enable_warp_if_requested(), init_drive_emulation_state(), restore_drive_emulation_state(), speed_menu_popup_create(), ui_create_main_window(), and warp_mode_toggle_action().
vsync_init()
void vsync_init (void(*)(void) hook)
Referenced by machine_specific_init().
vsync_on_vsync_do()
void vsync_on_vsync_do (vsync_callback_func_t callback_func, void * callback_param)
Call callback_func(callback_param) once at vsync time (or machine reset)
Referenced by on_save_screenshot_filename(), pause_loop(), screenshot_ui_auto_screenshot(), set_border_mode(), and ui_pause_enable().
vsync_reset_hook()
void vsync_reset_hook (void)
Referenced by machine_reset().
vsync_resources_init()
int vsync_resources_init (void)
Referenced by init_resources().
vsync_set_machine_parameter()
void vsync_set_machine_parameter (double refresh_rate, long cycles)
Referenced by machine_change_timing(), and machine_specific_init().
vsync_set_warp_mode()
void vsync_set_warp_mode (int val)
Referenced by set_warp_mode(), vsync_init(), warp_callback(), and warp_mode_toggle_action().
vsync_should_skip_frame()
bool vsync_should_skip_frame (struct video_canvas_s * canvas)
Referenced by raster_canvas_handle_end_of_frame().
vsync_shutdown()
void vsync_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
vsync_suspend_speed_eval()
void vsync_suspend_speed_eval (void)
Referenced by drive_jam(), load_snapshot_trap(), machine_jam(), monitor_close(), monitor_open(), monitor_open_action(), network_client_connect_trap(), network_connect_client(), network_hook_connected_receive(), network_server_connect_trap(), network_start_server(), pause_loop(), psid_ui_set_tune(), quickload_snapshot_trap(), quicksave_snapshot_trap(), save_snapshot_trap(), set_timer_speed(), snapshot_open(), sound_close(), sound_open(), ui_vsid_window_load_psid(), vsync_init(), vsync_reset_hook(), and vsync_set_warp_mode().