vsid: lib.h File Reference
lib.h File Reference
#include "vice.h"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include "debug.h"
Functions
void lib_init (void)
unsigned int lib_unsigned_rand (unsigned int min, unsigned int max)
float lib_float_rand (float min, float max)
Generate a uniform random float in the range [min, max] inclusive.
double lib_double_rand_unit (void)
void lib_rand_seed (uint64_t seed)
void lib_rand_printseed (void)
char * lib_msprintf (const char *fmt,...)
char * lib_mvsprintf (const char *fmt, va_list args)
void * lib_malloc (size_t size)
!defined LIB_DEBUG_PINPOINT
void * lib_calloc (size_t nmemb, size_t size)
Like calloc, but abort if not enough memory is available.
void * lib_realloc (void *p, size_t size)
Like realloc, but abort if not enough memory is available.
void lib_free (void *ptr)
char * lib_strdup (const char *str)
char * lib_strdup_trimmed (char *str)
Return a copy of str with leading and trailing whitespace removed.
void lib_debug_set_output (int state)
Function Documentation
lib_calloc()
void * lib_calloc (size_t nmemb, size_t size)
Like calloc, but abort if not enough memory is available.
Referenced by alloc_aggregate_stats(), alloc_profiling_context(), alloc_profiling_page(), attach_disk_image(), cbmdos_command_parse(), cbmdos_command_parse_plus(), cia1571_setup_context(), cia1581_setup_context(), cia1_setup_context(), cia2_setup_context(), ciacore_init(), cmdhd_setup_context(), disk_image_check_for_d64(), disk_image_check_for_d71(), disk_image_check_for_d81(), drive_init(), drive_setup_context(), drive_setup_context_for_unit(), drive_snapshot_read_gcrimage_module(), drivecpu65c02_setup_context(), drivecpu_setup_context(), event_image_append(), event_init_image_list(), event_record_attach_in_list(), event_record_in_list(), event_register_event_list(), event_snapshot_read_module(), event_write_version(), fakesid_open(), fastsid_open(), fdd_image_attach(), file_system_init(), fsdevice_init(), fsimage_dxx_write_half_track(), fsimage_gcr_read_half_track(), fsimage_gcr_write_half_track(), fsimage_media_create(), gcr_create_image(), getbuf(), iec_open_write(), image_contents_new(), initcmdline_check_args(), interrupt_cpu_status_new(), machine_maincpu_init(), monitor_interface_new(), mus_load_file(), p00_evaluate_name(), palette_create(), pc8477_setup_context(), power_on_reset(), print_dst(), psid_load_file(), raster_cache_new(), raster_changes_init(), raster_draw_buffer_alloc(), raster_resources_chip_init(), render_queue_create(), screenshot_save_core(), sdl_init(), t64_new(), tap_new(), tap_open(), tape_init(), tapecart_enable(), util_join_paths(), vdrive_command_rename(), vdrive_command_renamepart(), vdrive_command_scratch(), vdrive_dir_create_slot(), vdrive_internal_open_fsimage(), vdrive_rel_open_existing(), vdrive_rel_open_new(), vhk_parser_strtrim(), via1d1541_setup_context(), via4000_setup_context(), vice_opengl_initialise_canvas(), video_canvas_init(), video_ycbcr_palette_create(), and wd1770d_init().
lib_debug_set_output()
void lib_debug_set_output (int state)
lib_double_rand_unit()
double lib_double_rand_unit (void)
Referenced by random_method_geom_next().
lib_float_rand()
float lib_float_rand (float min, float max)
Generate a uniform random float in the range [min, max] inclusive.
Referenced by render_subframe().
lib_free()
void lib_free (void * ptr)
Referenced by advance_hasdisk(), advance_hastape(), advance_outfile_name(), alarm_context_destroy(), alarm_destroy(), append_char_to_input_buffer(), archdep_boot_path_free(), archdep_closedir(), archdep_create_user_cache_dir(), archdep_create_user_config_dir(), archdep_default_autostart_disk_image_file_name(), archdep_default_fliplist_file_name(), archdep_default_sysfile_pathlist(), archdep_default_sysfile_pathlist_free(), archdep_extra_title_text(), archdep_extra_title_text_free(), archdep_filename_parameter(), archdep_get_vice_drivesdir(), archdep_get_vice_hotkeysdir(), archdep_get_vice_machinedir(), archdep_home_path_free(), archdep_init(), archdep_mkdir_recursive(), archdep_mkstemp_fd(), archdep_open_default_log_file(), archdep_program_name_free(), archdep_program_path_free(), archdep_quote_parameter(), archdep_quote_unzip(), archdep_shutdown(), archdep_startup_log_error(), archdep_tmpnam(), archdep_user_cache_path(), archdep_user_cache_path_free(), archdep_user_config_path(), archdep_user_config_path_free(), archdep_user_state_path(), archdep_user_state_path_free(), argv_fallback(), array_free(), artstudio_check_and_correct_cell(), artstudio_multicolor_render(), artstudio_render_and_save(), artstudio_vic_save(), ata_init(), ata_shutdown(), ata_snapshot_read_module(), attach_disk_image(), autostart_autodetect_opt_prgname(), autostart_disk(), autostart_disk_cook_name(), autostart_prg(), autostart_prg_with_virtual_fs(), autostart_resources_shutdown(), bexpr_free(), bexpr_reset(), bmpdrv_close(), bmpdrv_open(), bmpdrv_save(), bmpdrv_write_bitmap_info(), build_printer_output_names(), build_sid_cmdline_option(), build_tapeport_string(), build_userport_string(), c64_256k_deactivate(), c64_256k_resources_shutdown(), c64_resources_shutdown(), cbmfile_find_file(), cbmfile_open(), cbmfile_rename(), cbmfile_scratch(), ciacore_init(), ciacore_shutdown(), circular_check_free(), cmdhd_attach_image(), cmdhd_setup_context(), cmdhd_shutdown(), cmdline_attach(), cmdline_free(), cmdline_free_autostart_string(), cmdline_init(), cmdline_log_active(), cmdline_options_get_description(), cmdline_options_string(), cmdline_shutdown(), compress_with_bzip(), compress_with_gzip(), console_close_all(), convert_alaw_buffer(), convert_double_buffer(), convert_float_buffer(), convert_pcm_buffer(), convert_ulaw_buffer(), crc32_file(), create_combo_box(), create_device_model(), create_disk_image(), create_file_chooser_filter(), create_hotkey_file_grid(), create_hotkeys_model(), create_joyport_combo(), create_model(), create_positional_keymap_browser(), create_proposed_audio_recording_name(), create_proposed_video_recording_name(), create_shader(), create_shader_program(), create_symbolic_keymap_browser(), create_tape_image(), cut_list(), deallocate_program_name(), destroy_current_team_list(), destroy_list(), detach_disk_image(), dir_menu_popup_create(), disk_dir_autostart_callback(), disk_image_destroy(), display_error_with_vice_version(), drive_cmdline_options_init(), drive_image_detach(), drive_init(), drive_jam(), drive_resources_init(), drive_resources_type(), drive_resources_type_init(), drive_shutdown(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_p64image_module(), drivecpu65c02_shutdown(), drivecpu_shutdown(), driver_select_shutdown(), drv_1520_close(), drv_nl10_shutdown(), event_destroy_image_list(), event_initial_write(), event_playback_attach_image(), event_playback_start_trap(), event_record_attach_in_list(), event_shutdown(), event_snapshot_path(), event_write_version(), export_remove(), fakesid_close(), fastsid_close(), fdd_flush_raw(), fdd_image_detach(), fdd_shutdown(), fdd_snapshot_read_module(), ffmpegexedrv_close(), ffmpegexedrv_close_audio(), ffmpegexedrv_shutdown(), file_free_sample(), file_load_sample(), file_system_shutdown(), fileio_close(), fileio_open(), fill_completions(), fliplist_clear_list(), fliplist_load_list(), fliplist_remove(), fliplist_resources_shutdown(), fliplist_save_list(), fliplist_set_current(), fliplist_shutdown(), free_aggregate_stats(), free_backbuffer(), free_baud_rate_list(), free_current_dir(), free_prg(), free_profiling_context(), free_symbol_table(), fsdevice_flush(), fsdevice_flush_cd(), fsdevice_flush_mkdir(), fsdevice_flush_rename(), fsdevice_flush_rmdir(), fsdevice_open(), fsdevice_open_directory(), fsdevice_open_file(), fsdevice_resources_shutdown(), fsdevice_shutdown(), fsimage_close(), fsimage_create(), fsimage_create_dxm(), fsimage_dxx_write_half_track(), fsimage_gcr_read_sector(), fsimage_gcr_write_half_track(), fsimage_gcr_write_sector(), fsimage_media_destroy(), fsimage_p64_read_sector(), fsimage_p64_write_sector(), fsimage_read_dxx_image(), fsimage_read_gcr_image(), fsimage_read_p64_image(), gcr_destroy_image(), generate_sid_address_range(), get_all_resource_names(), getbuf(), gfxoutput_shutdown(), godotdrv_close(), godotdrv_open(), handle_close(), handle_voc_file(), help_manual_action(), iec_close_sequential(), iec_cmdline_options_init(), iec_drive_idling_method(), iec_drive_shutdown(), iec_resources_init(), iec_resources_shutdown(), iffdrv_close(), iffdrv_open(), ifstack_free(), ifstack_pull(), image_contents_destroy(), image_contents_file_to_string(), image_contents_screencode_destroy(), image_contents_to_string(), initcmdline_check_args(), initcmdline_check_attach(), initcmdline_shutdown(), interrupt_cpu_status_destroy(), io_source_log_collisions(), io_source_msg_detach_all(), io_source_msg_detach_last(), io_source_unregister(), kbdbuf_shutdown(), kbdhostlayout_widget_create(), keyboard_is_keymap_valid(), keyboard_keyconvmap_free(), keyboard_parse_keymap(), keyboard_resources_shutdown(), koala_check_and_correct_cell(), koala_find_bgcolor(), koala_render_and_save(), lib_strdup_trimmed(), load_prg(), log_archdep(), log_close(), log_close_all(), log_helper(), log_resources_shutdown(), logfile_widget_create(), m3u_close(), m3u_create(), m3u_parse(), machine_bus_device_attach(), machine_bus_device_detach(), machine_common_resources_shutdown(), machine_jam(), machine_maincpu_shutdown(), machine_reset(), machine_trigger_reset_internal(), main_program(), minipaint_check_and_correct_cell(), minipaint_find_hires_colors(), minipaint_find_shared_colors_pass(), minipaint_render_and_save(), mon_add_string_to_buffer(), mon_bank(), mon_delete_conditional(), mon_display_io_regs(), mon_drive_list(), mon_file_open(), mon_memory_display(), mon_memory_hunt(), mon_memory_move(), mon_out(), mon_petscii_out(), mon_petscii_upper_out(), mon_prepend_dot_to_name(), mon_register_name_to_id(), mon_register_valid(), mon_remove_name_from_symbol_table(), mon_scrcode_out(), mon_scrcode_upper_out(), mon_show_dir(), mon_show_pwd(), monitor_binary_process_banks_available(), monitor_binary_process_checkpoint_list(), monitor_binary_process_condition_set(), monitor_binary_process_display_get(), monitor_binary_process_mem_get(), monitor_binary_process_palette_get(), monitor_binary_process_registers_available(), monitor_binary_process_resource_get(), monitor_binary_resources_shutdown(), monitor_binary_response_register_info(), monitor_completions(), monitor_interface_destroy(), monitor_network_resources_shutdown(), monitor_network_ui_jam_dialog(), monitor_open(), monitor_process(), monitor_resources_shutdown(), monitor_shutdown(), montor_list_destroy(), mus_load_file(), native_borderize_colormap(), native_console_close(), native_console_open(), native_console_out(), native_console_petscii_out(), native_console_petscii_upper_out(), native_console_scrcode_out(), native_crop_and_borderize_colormap(), native_is_colormap_multicolor(), native_scale_colormap(), network_client_connect_trap(), network_connect_client(), network_free_frame_event_list(), network_hook_connected_receive(), network_hook_connected_send(), network_server_connect_trap(), network_shutdown(), node_free(), on_destroy(), on_destroy_resource_name(), on_dialog_destroy(), on_launcher_clicked(), on_resource_browser_browse_clicked(), on_romset_save_callback(), on_save_clicked(), on_widget_destroy(), on_window_delete_event(), OPLDestroy(), output_graphics_init(), output_graphics_open(), output_graphics_shutdown(), output_select_shutdown(), output_text_shutdown_resources(), p00_file_find(), p00_filename_create(), p00_open(), p00_rename(), p00_scratch(), palette_free(), palette_get_info_list(), palette_list_free(), palette_load(), palette_read_info(), parse_quoted_argument(), paste_callback(), pc8477_shutdown(), pc8477d_init(), pcxdrv_close(), pcxdrv_open(), playback_end_file(), playback_next_command(), playlist_save_dialog_callback(), plus256k_deactivate(), plus256k_resources_shutdown(), plus60k_deactivate(), plus60k_resources_shutdown(), power_on_reset(), ppmdrv_close(), ppmdrv_open(), prepend_dir_to_path(), print_dst(), print_help_details(), profile_reset(), psid_init_tune(), psid_load_file(), psid_set_tune(), psid_shutdown(), quickload_snapshot_trap(), quicksave_snapshot_trap(), ram_init_print_pattern(), raster_cache_destroy(), raster_canvas_shutdown(), raster_changes_shutdown(), raster_cmdline_options_chip_init(), raster_destroy_raster(), raster_draw_buffer_free(), raster_modes_shutdown(), raster_resources_chip_init(), raster_resources_chip_shutdown(), raster_shutdown(), raster_sprite_status_destroy(), raster_sprite_status_shutdown(), rawfile_destroy(), rawfile_open(), rawfile_remove(), rawfile_rename(), rb_state_free(), rb_state_free_patterns(), rb_state_set_directory(), reboot_for_autostart(), remove_checkpoint(), remove_checkpoint_from_list(), render_queue_destroy(), render_queue_get_from_pool(), resid_close(), resource_record_event(), resource_widget_free_string(), resource_widget_set_string(), resources_free(), resources_get_event_safe_list(), resources_get_int_sprintf(), resources_get_string_sprintf(), resources_load(), resources_log_active(), resources_save(), resources_set_int_sprintf(), resources_set_string_sprintf(), resources_shutdown(), restore_path(), riotcore_init(), riotcore_shutdown(), romset_archive_clear(), romset_archive_item_create(), romset_archive_item_delete(), romset_archive_load(), romset_archive_save(), romset_file_load(), romset_file_save(), rs232drv_resources_shutdown(), sampler_cmdline_options_init(), sampler_file_resources_shutdown(), sampler_resources_shutdown(), save_as_callback(), save_audio_recording_handler(), save_filename_callback(), save_screenshot_error_impl(), save_screenshot_handler(), save_screenshot_vsync_callback(), save_snapshot_dialog(), save_video_recording_handler(), scan_directory(), screenshot_auto_screenshot_vsync_callback(), screenshot_create_quickscreenshot_filename(), screenshot_save_core(), screenshot_shutdown(), scsi_process_ack(), sdl_close(), serial_iec_lib_read_sector(), set_attach_device_readonly(), set_chip_rendermode(), set_container_format(), set_drive_fixed(), set_event_snapshot_dir(), set_hvsc_root(), set_system_path(), settings_load_from_action(), settings_save_to_action(), shutdown_resource_chip_mode(), sid_cmdline_options_shutdown(), sid_sound_machine_close(), snapshot_close(), snapshot_module_close(), snapshot_module_create(), snapshot_module_open(), snapshot_read_string(), sound_close(), sound_cmdline_options_init(), sound_flush(), sound_init(), sound_machine_calculate_samples(), sound_open(), sound_resources_shutdown(), statusbar_speed_widget_update(), sysfile_load(), sysfile_open(), sysfile_resources_shutdown(), sysfile_shutdown(), t64_destroy(), tap_close(), tap_open(), tap_read_file(), tap_seek_start(), tap_seek_to_next_file(), tap_skip_file(), tape_dir_autostart_callback(), tape_image_attach_internal(), tape_image_close(), tape_init(), tape_internal_close_tape_image(), tape_internal_open_tape_image(), tape_shutdown(), tape_snapshot_read_tapimage_module(), tapecart_attach_tcrt(), tapecart_enable(), tapecart_exit(), textfile_entry_free(), textfile_reader_free(), token_list_free(), tpicore_shutdown(), traps_remove(), traps_shutdown(), try_set_keymap_file(), try_uncompress_archive(), try_uncompress_lynx(), try_uncompress_with_bzip(), try_uncompress_with_gzip(), try_uncompress_with_tzx(), try_uncompress_zipcode(), ui_error_impl(), ui_hotkeys_load_user_default(), ui_hotkeys_load_vice_default(), ui_hotkeys_save(), ui_hotkeys_save_as(), ui_hotkeys_save_dialog_show(), ui_hotkeys_shutdown(), ui_hotkeys_vhk_full_path_user(), ui_hotkeys_vhk_full_path_vice(), ui_jam_dialog(), ui_message_impl(), ui_populate_fliplist_menu(), ui_resources_shutdown(), ui_vsid_window_load_psid(), uidata_get_bytes(), uidata_get_pixbuf(), uidata_get_pixbuf_at_scale(), uidata_init(), uimon_in(), uimon_petscii_out(), uimon_petscii_upper_out(), uimon_scrcode_out(), uimon_scrcode_upper_out(), update_hotkeys_info(), update_vhk_source_type(), util_addline(), util_addline_free(), util_file_load_string(), util_gen_hex_address_list(), util_string_set(), vdrive_bam_setup_bam(), vdrive_cmdfree_abbrv(), vdrive_cmdfree_command(), vdrive_cmdfree_file(), vdrive_cmdfree_full(), vdrive_cmdfree_more(), vdrive_cmdfree_path(), vdrive_command_copy(), vdrive_command_format(), vdrive_command_format_internal(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_renamepart(), vdrive_command_rmdir(), vdrive_command_validate(), vdrive_detach_image(), vdrive_device_shutdown(), vdrive_dir_find_first_slot(), vdrive_dir_find_next_slot(), vdrive_dir_part_find_first_slot(), vdrive_iec_open(), vdrive_internal_close_disk_image(), vdrive_internal_open_fsimage(), vdrive_pack_parts(), vdrive_rel_close(), vdrive_rel_open_existing(), vdrive_rel_shutdown_ss_buffers(), vhk_gtk_map_free(), vhk_parser_do_include(), vhk_parser_open_file(), vhk_parser_parse(), viacore_init(), viacore_shutdown(), vice_gtk3_grid_new_spaced_with_label(), vice_gtk3_integer_input_box(), vice_gtk3_message_confirm(), vice_gtk3_message_error(), vice_gtk3_message_info(), vice_gtk3_resource_filechooser_set_filter(), vice_gtk3_resource_scale_custom_new_printf(), vice_network_address_generate_ipv4(), vice_opengl_destroy_context(), vicii_shutdown(), vicii_sprites_shutdown(), video_alloc_picture(), video_canvas_shutdown(), video_cmdline_options_chip_init(), video_free_picture(), video_resources_chip_init(), video_resources_chip_shutdown(), video_ycbcr_palette_free(), voc_handle_silence(), voc_handle_sound_1(), voc_handle_sound_2(), voc_handle_sound_9(), vsid_main_widget_create(), vsid_playlist_free_path(), vsid_playlist_free_title(), vsid_state_shutdown(), vsid_tune_info_widget_set_song_lengths(), vsid_tune_info_widget_set_song_lengths_md5(), vsid_ui_update(), vsync_shutdown(), wd1770_shutdown(), write_resource_item(), write_to_terminal(), zfile_close_action(), zfile_compress(), zfile_fopen(), zfile_list_destroy(), zmbvdrv_close_audio(), zmbvdrv_close_video(), and zmbvdrv_shutdown().
lib_init()
void lib_init (void)
Referenced by main_program().
lib_malloc()
void * lib_malloc (size_t size)
!defined LIB_DEBUG_PINPOINT
!defined LIB_DEBUG_PINPOINT
Referenced by add_monitor_cpu_type_supported(), add_to_checkpoint_list(), alarm_context_new(), alarm_new(), archdep_boot_path(), archdep_current_dir(), archdep_opendir(), archdep_tmpnam(), artstudio_check_and_correct_cell(), artstudio_render_and_save(), ata_init(), autostart_disk_cook_name(), bexpr_tokenize(), bmpdrv_open(), bmpdrv_write_bitmap_info(), breakpoint_add_checkpoint(), cbmdos_dir_slot_create(), cbmfile_open(), charset_petconv_stralloc(), charset_petscii_to_screencode_line(), cia1571_setup_context(), cia1581_setup_context(), circular_check(), clipboard_read_screen_output(), cmdhd_setup_context(), cmdline_init(), concat_strings(), convert_alaw_buffer(), convert_double_buffer(), convert_float_buffer(), convert_pcm_buffer(), convert_ulaw_buffer(), crc32_file(), create_combo_entries(), create_control_data(), create_current_team_list(), create_list(), create_shader(), create_shader_program(), create_video_driver_list(), disk_image_create(), diskcontents_block_read(), display_error_with_vice_version(), drive_snapshot_read_p64image_module(), drivecpu65c02_setup_context(), drivecpu_setup_context(), driver_select_register(), drv_nl10_init(), event_initial_write(), event_record_attach_in_list(), event_record_in_list(), event_snapshot_read_module(), event_write_version(), expand_shortname(), expandable_list_get_resources(), export_add(), fdd_flush_raw(), fdd_image_attach(), fdd_init(), fdd_init_crc1021(), fdd_snapshot_read_module(), ffmpegexedrv_open_audio(), file_load_sample(), fliplist_add_image(), fliplist_load_list(), fsimage_create(), fsimage_create_dxm(), fsimage_dxx_write_half_track(), fsimage_gcr_read_half_track(), fsimage_p64_read_half_track(), fsimage_read_dxx_image(), fsimage_read_gcr_image(), fsimage_read_p64_image(), generate_baud_rate_list(), get_formats_and_codecs(), get_resource_chip_mode(), gfxoutput_early_init(), gfxoutput_register(), godotdrv_open(), iffdrv_open(), ifstack_push(), io_source_msg_detach_all(), io_source_msg_detach_last(), io_source_register(), keyboard_keyconvmap_alloc(), koala_check_and_correct_cell(), koala_find_bgcolor(), koala_render_and_save(), lib_mvsprintf(), lib_strdup(), load_prg(), m3u_open(), minipaint_check_and_correct_cell(), minipaint_find_hires_colors(), minipaint_find_shared_colors_pass(), minipaint_render_and_save(), mon_add_name_to_symbol_table(), mon_breakpoint_checkpoint_list_get(), mon_buffer_alloc(), mon_memory_display(), mon_memory_hunt(), mon_memory_move(), mon_register_list_get6502(), mon_register_list_get6502dtv(), mon_register_list_get65816(), mon_register_list_get6809(), mon_register_list_getR65C02(), mon_register_list_getz80(), monitor_binary_get_command_line(), monitor_binary_process_banks_available(), monitor_binary_process_condition_set(), monitor_binary_process_display_get(), monitor_binary_process_mem_get(), monitor_binary_process_palette_get(), monitor_binary_process_registers_available(), monitor_binary_process_resource_get(), monitor_binary_response_register_info(), monitor_list_new(), native_borderize_colormap(), native_console_open(), native_crop_and_borderize_colormap(), native_generic_render(), native_is_colormap_multicolor(), native_scale_colormap(), native_sort_colors_colormap(), network_client_connect_trap(), network_connect_client(), network_create_event_buffer(), network_create_event_list(), network_hook_connected_receive(), network_init_frame_event_list(), network_server_connect_trap(), node_new(), OPLCreate(), output_graphics_open(), output_select_register(), p00_open(), palette_create(), parse_quoted_argument(), pcxdrv_open(), ppmdrv_open(), ram_init_print_pattern(), raster_canvas_init(), raster_init(), raster_modes_init(), raster_modes_new(), raster_realize(), raster_sprite_cache_new(), raster_sprite_status_init(), raster_sprite_status_new(), rawfile_open(), rb_state_new(), rb_state_set_patterns(), render_queue_create(), render_queue_get_from_pool(), resource_create_event_data(), resources_add_callback(), resources_init(), romset_archive_item_create(), romset_archive_load(), set_drive_fixed(), snapshot_create(), snapshot_module_create(), snapshot_module_open(), snapshot_open(), snapshot_read_string(), sound_get_valid_devices(), sound_machine_calculate_samples(), sound_open(), state_line_end(), statusbar_led_widget_create(), string_list_append_list(), sysfile_get_system_path_next(), t64_open(), tap_cbm_read_file_prg(), tap_tt_read_file(), tape_internal_open_tape_image(), tape_read_contents(), tape_snapshot_read_tapimage_module(), tapecart_enable(), tapeport_get_valid_devices(), textfile_entry_new(), textfile_reader_init(), token_list_init(), traps_add(), ui_action_get_info_list(), ui_hotkeys_vhk_filename_user(), uimon_write_to_terminal(), userport_get_valid_devices(), util_concat(), util_file_load_string(), util_fname_split(), util_strjoin(), util_strsplit(), util_subst(), vdrive_alloc_buffer(), vdrive_bam_setup_bam(), vdrive_command_copy(), vdrive_command_execute(), vdrive_command_format(), vdrive_command_format_internal(), vdrive_command_mkdir(), vdrive_command_validate(), vdrive_dir_find_next_slot(), vdrive_dir_first_directory(), vdrive_internal_open_fsimage(), vdrive_pack_parts(), vdrive_rel_open(), vdrive_rel_open_existing(), vdrive_rel_setup_ss_buffers(), vhk_gtk_map_new(), vhk_hotkey_label(), vhk_modmask_name(), vhk_parser_strtrim(), via1d1541_setup_context(), via4000_setup_context(), vice_gtk3_petscii_to_utf8(), vice_gtk3_petscii_to_utf8_petme(), vice_gtk3_petscii_to_utf8_petme64(), vice_gtk3_scrcode_to_utf8(), vice_gtk3_scrcode_to_utf8_petme(), vice_gtk3_scrcode_to_utf8_petme64(), vicii_init(), video_alloc_picture(), video_ycbcr_palette_create(), voc_handle_silence(), voc_handle_sound_1(), voc_handle_sound_2(), voc_handle_sound_9(), zfile_list_add(), zmbv_get_formats_and_codecs(), zmbvdrv_alloc_picture(), and zmbvdrv_open_audio().
lib_msprintf()
char * lib_msprintf (const char * fmt, ...)
Referenced by advance_hasdisk(), append_char_to_input_buffer(), ata_init(), build_tapeport_string(), build_userport_string(), cia1571_setup_context(), cia1581_setup_context(), cia1_setup_context(), cia2_setup_context(), ciacore_init(), cmdhd_attach_image(), cmdhd_setup_context(), cmdline_options_string(), create_model(), create_proposed_audio_recording_name(), create_proposed_snapshot_name(), create_proposed_video_recording_name(), dir_menu_popup_create(), drive_cmdline_options_init(), drive_init(), drive_resources_init(), drive_resources_type(), drive_resources_type_init(), drive_snapshot_read_image_module(), drivecpu65c02_setup_context(), drivecpu_setup_context(), fdd_init(), generate_baud_rate_list(), iec_cmdline_options_init(), iec_drive_idling_method(), iec_resources_init(), image_contents_file_to_string(), image_contents_to_string(), log_helper(), mon_disassemble_with_label(), mon_drive_list(), mon_dump_with_label(), monitor_completions(), pc8477_setup_context(), pc8477d_init(), psid_init_tune(), riotcore_init(), romset_archive_list(), save_audio_recording_handler(), save_screenshot_handler(), save_video_recording_handler(), screenshot_create_datetime_string(), screenshot_create_quickscreenshot_filename(), scsi_process_ack(), serial_iec_lib_read_sector(), set_drive_fixed(), sound_init(), sound_open(), string_resource_item(), util_gen_hex_address_list(), vdrive_dir_first_directory(), via1d1541_setup_context(), via4000_setup_context(), viacore_init(), vice_gtk3_grid_new_spaced_with_label(), vice_gtk3_integer_input_box(), and wd1770d_init().
lib_mvsprintf()
char * lib_mvsprintf (const char * fmt, va_list args)
Referenced by archdep_startup_log_error(), drive_jam(), lib_msprintf(), log_archdep(), machine_jam(), mon_out(), mon_petscii_out(), mon_petscii_upper_out(), mon_scrcode_out(), mon_scrcode_upper_out(), monitor_network_ui_jam_dialog(), native_console_out(), native_console_petscii_out(), native_console_petscii_upper_out(), native_console_scrcode_out(), resources_get_int_sprintf(), resources_get_string_sprintf(), resources_set_int_sprintf(), resources_set_string_sprintf(), ui_error(), ui_jam_dialog(), ui_message(), vice_gtk3_message_confirm(), vice_gtk3_message_error(), vice_gtk3_message_info(), and vice_gtk3_resource_scale_custom_new_printf().
lib_rand_printseed()
void lib_rand_printseed (void)
Referenced by main_program().
lib_rand_seed()
void lib_rand_seed (uint64_t seed)
Referenced by cmdline_seed(), lib_init(), and main_program().
lib_realloc()
void * lib_realloc (void * ptr, size_t size)
Like realloc, but abort if not enough memory is available.
Referenced by add_dir_entry(), add_file_entry(), append_string_to_input_buffer(), archdep_current_dir(), array_append(), c64_256k_activate(), charset_petconv_stralloc(), circular_check(), cmdline_register_options(), drive_snapshot_read_gcrimage_module(), event_record_attach_in_list(), fsimage_dxx_write_half_track(), fsimage_read_dxx_image(), get_context_id(), get_formats_and_codecs(), interrupt_cpu_status_int_new(), interrupt_maincpu_trigger_trap(), kbd_buf_parse_string(), keyboard_keyconvmap_realloc(), log_open(), mon_ioreg_add_list(), mon_playback_commands(), monitor_binary_get_command_line(), plus256k_activate(), plus60k_activate(), raster_cache_realloc(), raster_realize_frame_buffer(), raster_snapshot_read(), read_line(), realloc_buffer(), resources_register_int(), resources_register_string(), romset_archive_item_create(), romset_archive_load(), string_list_append_list(), tap_cbm_read_file_seq(), textfile_reader_read(), token_list_resize_maybe(), uimon_write_to_terminal(), util_add_extension(), util_bufcat(), util_string_set(), vdrive_alloc_buffer(), vdrive_rel_add_sector(), vicii_sprites_init_sprline(), vsync_on_vsync_do(), and zmbv_get_formats_and_codecs().
lib_strdup()
char * lib_strdup (const char * str)
Referenced by add_dir_entry(), add_file_entry(), advance_hasdisk(), advance_hastape(), alarm_context_init(), alarm_init(), archdep_boot_path(), archdep_current_dir(), archdep_default_sysfile_pathlist(), archdep_expand_path(), archdep_filename_parameter(), archdep_get_vice_datadir(), archdep_get_vice_docsdir(), archdep_home_path(), archdep_init(), archdep_make_backup_filename(), archdep_mkstemp_fd(), archdep_program_path(), archdep_quote_parameter(), archdep_tmpnam(), archdep_user_cache_path(), archdep_user_config_path(), archdep_user_state_path(), archdep_xdg_cache_home(), archdep_xdg_config_home(), archdep_xdg_data_home(), archdep_xdg_state_home(), autostart_autodetect_opt_prgname(), autostart_disk(), build_sid_cmdline_option(), cbmfile_find_file(), cbmfile_open(), cbmfile_rename(), cbmfile_scratch(), charset_replace_hexcodes(), cmdhd_attach_image(), cmdline_attach(), cmdline_autoload(), cmdline_autostart(), cmdline_log_active(), cmdline_options_get_description(), cmdline_options_string(), cmdline_register_options(), compress_with_bzip(), compress_with_gzip(), create_combo_box(), create_file_chooser_filter(), disk_dir_autostart_callback(), driver_select_register(), event_image_append(), event_playback_start_trap(), fastsid_dump_state(), ffmpegexedrv_save(), fileio_open(), findpath(), fliplist_add_image(), fliplist_load_list(), fliplist_set_current(), fsdevice_open_directory(), fsimage_create(), fsimage_create_dxm(), fsimage_name_set(), generate_sid_address_range(), get_config_file_path(), get_formats_and_codecs(), help_manual_action(), image_contents_filename_by_number(), image_contents_filename_to_string(), image_contents_filetype_to_string(), initcmdline_check_args(), interrupt_cpu_status_int_new(), io_source_log_collisions(), io_source_msg_detach_all(), io_source_msg_detach_last(), lib_strdup_trimmed(), log_open(), m3u_create(), m3u_open(), m3u_parse(), machine_autodetect_psid(), machine_bus_device_attach(), main_program(), mon_bank(), mon_playback_commands(), mon_show_dir(), monitor_network_extract_text_command_line(), monitor_process(), mus_load_file(), native_console_in(), node_new(), on_launcher_clicked(), on_save_screenshot_filename(), p00_file_find(), p00_open(), palette_create(), palette_load(), palette_read_info(), paste_callback(), prepend_current_dir(), prepend_dir_to_path(), prg_name_unix(), print_help_details(), rawfile_open(), rawfile_remove(), rawfile_rename(), rb_state_set_directory(), rb_state_set_patterns(), reboot_for_autostart(), resid_dump_state(), resource_widget_set_string(), resources_init(), resources_load(), resources_register_int(), resources_register_string(), resources_save(), romset_archive_list(), romset_file_list(), sampler_cmdline_options_init(), save_screenshot_vsync_callback(), screenshot_save(), set_attach_device_readonly(), set_drive_fixed(), sound_cmdline_options_init(), sound_init(), statusbar_speed_widget_update(), sysfile_get_system_path_start(), t64_open(), tap_open(), tape_dir_autostart_callback(), tape_image_attach_internal(), tape_internal_open_tape_image(), tapecart_attach_tcrt(), textfile_entry_new(), try_uncompress_archive(), try_uncompress_lynx(), try_uncompress_with_bzip(), try_uncompress_with_gzip(), try_uncompress_with_tzx(), try_uncompress_zipcode(), ui_hotkeys_init(), ui_hotkeys_save_dialog_show(), ui_hotkeys_vhk_source_path(), ui_vsid_window_load_psid(), uimon_get_in(), uimon_in(), update_current_dir(), util_add_extension_const(), util_fname_split(), util_gen_hex_address_list(), util_string_set(), util_strjoin(), util_strsplit(), vdrive_command_format(), vdrive_command_rmdir(), vdrive_dir_first_directory(), vhk_hotkey_label(), vice_gtk3_resource_browser_new(), vice_gtk3_resource_browser_save_new(), vice_network_address_generate_ipv4(), video_resources_chip_init(), vsid_playlist_set_path(), vsid_playlist_set_title(), vsid_ui_display_author(), vsid_ui_display_copyright(), vsid_ui_display_irqtype(), vsid_ui_display_name(), zfile_close_action(), zfile_list_add(), and zmbv_get_formats_and_codecs().
lib_strdup_trimmed()
char * lib_strdup_trimmed (char * str)
Return a copy of str with leading and trailing whitespace removed.
Referenced by monitor_process(), and playback_next_command().
lib_unsigned_rand()
unsigned int lib_unsigned_rand (unsigned int min, unsigned int max)
Referenced by ciacore_inttod(), kbdbuf_flush(), ram_init_with_pattern(), reboot_for_autostart(), and rotation_do_wobble().