vsid: drive/iec/pc8477.h File Reference
pc8477.h File Reference
#include "types.h"
Typedefs
typedef void(* pc8477_motor_on_callback_t) (void *data, int signal)
typedef struct pc8477_s pc8477_t
Functions
void pc8477d_init (struct diskunit_context_s *drv)
Functions using drive context.
void pc8477_shutdown (pc8477_t *drv)
void pc8477_setup_context (struct diskunit_context_s *drv)
void pc8477d_store (struct diskunit_context_s *drv, uint16_t addr, uint8_t byte)
uint8_t pc8477d_read (struct diskunit_context_s *drv, uint16_t addr)
uint8_t pc8477d_peek (struct diskunit_context_s *drv, uint16_t addr)
void pc8477d_dump (struct diskunit_context_s *drv)
void pc8477_reset (pc8477_t *drv, int is8477)
int pc8477_irq (pc8477_t *drv)
int pc8477_attach_image (struct disk_image_s *image, unsigned int unit)
int pc8477_detach_image (struct disk_image_s *image, unsigned int unit)
Typedef Documentation
pc8477_motor_on_callback_t
typedef void(* pc8477_motor_on_callback_t) (void *data, int signal)
pc8477_t
typedef struct pc8477_s pc8477_t
Function Documentation
pc8477_attach_image()
int pc8477_attach_image (struct disk_image_s * image, unsigned int unit)
Referenced by iec_drive_image_attach().
pc8477_detach_image()
int pc8477_detach_image (struct disk_image_s * image, unsigned int unit)
Referenced by iec_drive_image_detach().
pc8477_irq()
int pc8477_irq (pc8477_t * drv)
Referenced by read_prb().
pc8477_reset()
void pc8477_reset (pc8477_t * drv, int is8477)
Referenced by iec_drive_reset().
pc8477_setup_context()
void pc8477_setup_context (struct diskunit_context_s * drv)
Referenced by iec_drive_setup_context().
pc8477_shutdown()
void pc8477_shutdown (pc8477_t * drv)
Referenced by iec_drive_shutdown().
pc8477d_dump()
void pc8477d_dump (struct diskunit_context_s * drv)
Referenced by drivemem_ioreg_list_get().
pc8477d_init()
void pc8477d_init (diskunit_context_t * drv)
Functions using drive context.
Todo:
FIXME: whats the deal with the different prefixes?
Referenced by iec_drive_init().
pc8477d_peek()
uint8_t pc8477d_peek (struct diskunit_context_s * drv, uint16_t addr)
Referenced by memiec_init().
pc8477d_read()
uint8_t pc8477d_read (struct diskunit_context_s * drv, uint16_t addr)
Referenced by memiec_init().
pc8477d_store()
void pc8477d_store (struct diskunit_context_s * drv, uint16_t addr, uint8_t byte)
Referenced by memiec_init().