vsid: arch/gtk3/widgets/userportrsinterfacewidget.c File Reference
userportrsinterfacewidget.c File Reference
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "machine.h"
#include "resources.h"
#include "userportrsinterfacewidget.h"
Functions
static int get_rsinterface_index (void)
Get RS-232 interface combo box index from the control lines checkboxes combinations.
static void on_combo_changed (GtkWidget *widget, gpointer user_data)
Handler for the "changed" event of the Userport RS-232 Interface combo box.
static void on_control_toggled (GtkWidget *widget, gpointer user_data)
Handler for the "toggled" event of the Userport RS-232 Interface control lines Refresh Userport RS-232 interface combo box.
static GtkWidget * create_label (const char *text)
Create left-aligned, 8 pixels indented label.
GtkWidget * userport_rsinterface_widget_create (void)
Create userport rsinterface widget.
void userport_rsinterface_widget_add_callback (GtkGrid *widget, void(*cb_func)(GtkWidget *))
Add custom callback to widget.
Variables
static const vice_gtk3_combo_entry_int_t userport_rsinterfaces64 []
List of possible userport RS-232 interfaces for C64.
static const vice_gtk3_combo_entry_int_t userport_rsinterfacesvic []
List of possible userport RS-232 interfaces for VIC-20/C128.
Function Documentation
create_label()
static GtkWidget * create_label (const char * text) static
Create left-aligned, 8 pixels indented label.
Parameters
[in] text label text
Returns
GtkLabel
Referenced by userport_rsinterface_widget_create().
get_rsinterface_index()
static int get_rsinterface_index (void) static
Get RS-232 interface combo box index from the control lines checkboxes combinations.
Returns
int
Referenced by on_control_toggled(), and userport_rsinterface_widget_create().
on_combo_changed()
static void on_combo_changed (GtkWidget * widget, gpointer user_data) static
Handler for the "changed" event of the Userport RS-232 Interface combo box.
Parameters
[in] widget combo box
[in] user_data extra event data (unused)
Referenced by userport_rsinterface_widget_create().
on_control_toggled()
static void on_control_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the "toggled" event of the Userport RS-232 Interface control lines Refresh Userport RS-232 interface combo box.
Parameters
[in] widget check button
[in] user_data extra event data (unused)
Referenced by userport_rsinterface_widget_create().
userport_rsinterface_widget_add_callback()
void userport_rsinterface_widget_add_callback (GtkGrid * widget, void(*)(GtkWidget *) cb_func)
Add custom callback to widget.
Adds a user-defined callback function on modem type changes.
Parameters
[in,out] widget userport modem widget
[in] cb_func callback function
Referenced by create_userport_widget().
userport_rsinterface_widget_create()
GtkWidget * userport_rsinterface_widget_create (void)
Create userport rsinterface widget.
Returns
GtkCombobox
Referenced by create_userport_widget().
Variable Documentation
userport_rsinterfaces64
const vice_gtk3_combo_entry_int_t userport_rsinterfaces64[] static
Initial value:
= {
    { "RS-232, normal control lines levels",     0  },
    { "RS-232, inverted control lines levels",   1  },
    { "RS-232, custom control lines levels",     2  },
    { "UP-9600",                                 3  },
    { NULL,                                     -1 }
}
List of possible userport RS-232 interfaces for C64.
Referenced by userport_rsinterface_widget_create().
userport_rsinterfacesvic
const vice_gtk3_combo_entry_int_t userport_rsinterfacesvic[] static
Initial value:
= {
    { "RS-232, normal control lines levels",    0 },
    { "RS-232, inverted control lines levels",  1 },
    { "RS-232, custom control lines levels",    2 },
    { NULL,                                    -1 }
}
List of possible userport RS-232 interfaces for VIC-20/C128.
Referenced by userport_rsinterface_widget_create().