vsid: arch/gtk3/widgets/mixerwidget.c File Reference
mixerwidget.c File Reference
GTK3 mixer widget for emus other than VSID.
#include "vice.h"
#include <stdlib.h>
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "debug.h"
#include "machine.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "sid/sid.h"
#include "mixerwidget.h"
Macros
#define SLIDER_CSS
CSS for the scales.
#define LABEL_CSS
CSS for the labels.
Functions
void mixer_widget_sid_type_changed (void)
Depending on what SID type is being used, show the right widgets.
static void on_reset_clicked (GtkWidget *widget, gpointer data)
Handler for the 'clicked' event of the reset button.
static GtkWidget * create_label (const char *text, gboolean minimal, GtkAlign alignment)
Create a horizontally aligned label.
static GtkWidget * create_slider (const char *resource, const char *resfmt, int low, int high, int reslow, int reshigh, float step, gboolean minimal)
Create a customized GtkScale for resource.
static GtkWidget * create_exp_slider (const char *resource, double power, int low, int high, int step, gboolean minimal)
Create an exponential GtkScale for resource.
static GtkWidget * create_volume_widget (gboolean minimal)
Create slider for main volume.
static GtkWidget * create_lowpass_widget (gboolean minimal)
Create slider for CB2 low pass filter.
GtkWidget * mixer_widget_create (gboolean minimal, GtkAlign alignment)
Create mixer widget.
Variables
static GtkWidget * volume
Main volume slider.
static GtkWidget * lowpass
CB2 low pass filter setting (PETs only)
static GtkCssProvider * label_css_provider
CSS provider for labels.
static GtkCssProvider * scale_css_provider
CSS provider for scales (sliders)
Detailed Description
GTK3 mixer widget for emus other than VSID.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
LABEL_CSS
#define LABEL_CSS
Value:
    "label {\n" \
    "    font-size: 80%;\n" \
    "    margin-top: -2px;\n" \
    "    margin-bottom: -2px;\n" \
    "}\n"
CSS for the labels.
Make font smaller and reduce the vertical size the labels use
Here Be Dragons!
SLIDER_CSS
#define SLIDER_CSS
Value:
    "scale slider {\n" \
    "    min-width: 10px;\n" \
    "    min-height: 10px;\n" \
    "    margin: -3px;\n" \
    "}\n" \
    "scale {\n" \
    "    margin-top: -8px;\n" \
    "    margin-bottom: -8px;\n" \
    "}\n" \
    "scale value {\n" \
    "    min-width: 4em;\n" \
    "}\n"
CSS for the scales.
This makes the sliders take up less vertical space. The margin can be set to a negative value (in px) to allow the slider to be larger than the scale itself.
Probably will require some testing/tweaking to get this to look acceptable with various themes (and OSes).
Function Documentation
create_exp_slider()
static GtkWidget * create_exp_slider (const char * resource, double power, int low, int high, int step, gboolean minimal) static
Create an exponential GtkScale for resource.
Parameters
[in] resource resource name without the video chip name prefix
[in] power exponent
[in] low lower bound
[in] high upper bound
[in] step step used to increase/decrease slider value
[in] minimal reduce slider size to be used in the statusbar
Returns
GtkScale
Referenced by create_lowpass_widget().
create_label()
static GtkWidget * create_label (const char * text, gboolean minimal, GtkAlign alignment) static
Create a horizontally aligned label.
Parameters
[in] text text for the label
[in] minimal use CSS to reduce size of use as statusbar widget
[in] alignment label alignment (see GtkAlingn enum`)
Returns
GtkLabel
Referenced by mixer_widget_create().
create_lowpass_widget()
static GtkWidget * create_lowpass_widget (gboolean minimal) static
Create slider for CB2 low pass filter.
Parameters
[in] minimal resize slider to minimal size
Returns
GtkScale
Referenced by mixer_widget_create().
create_slider()
static GtkWidget * create_slider (const char * resource, const char * resfmt, int low, int high, int reslow, int reshigh, float step, gboolean minimal) static
Create a customized GtkScale for resource.
Parameters
[in] resource resource name
[in] low lower bound
[in] high upper bound
[in] reslow resource lower bound
[in] reshigh resource upper bound
[in] step step used to increase/decrease slider value
[in] minimal reduce slider size to be used in the statusbar
Returns
GtkScale
Referenced by create_volume_widget().
create_volume_widget()
static GtkWidget * create_volume_widget (gboolean minimal) static
Create slider for main volume.
Parameters
[in] minimal resize slider to minimal size
Returns
GtkScale
< 100%
< 100%
Referenced by mixer_widget_create().
mixer_widget_create()
GtkWidget * mixer_widget_create (gboolean minimal, GtkAlign alignment)
Create mixer widget.
Parameters
[in] minimal minimize side of sliders and labels
[in] alignment alignment of labels
Returns
GtkGrid
Referenced by settings_mixer_widget_create(), and ui_create_main_window().
mixer_widget_sid_type_changed()
void mixer_widget_sid_type_changed (void)
Depending on what SID type is being used, show the right widgets.
Referenced by mixer_widget_create(), on_reset_clicked(), settings_mixer_widget_create(), sid_model_callback(), and sid_model_widget_update().
on_reset_clicked()
static void on_reset_clicked (GtkWidget * widget, gpointer data) static
Handler for the 'clicked' event of the reset button.
Resets the slider to when the widget was created.
Parameters
[in] widget button (unused)
[in] data extra event data (unused)
Referenced by mixer_widget_create().
Variable Documentation
label_css_provider
GtkCssProvider* label_css_provider static
CSS provider for labels.
Referenced by create_label(), and mixer_widget_create().
lowpass
GtkWidget* lowpass static
CB2 low pass filter setting (PETs only)
Referenced by mixer_widget_create(), and on_reset_clicked().
scale_css_provider
GtkCssProvider* scale_css_provider static
CSS provider for scales (sliders)
Referenced by create_exp_slider(), create_slider(), and mixer_widget_create().
volume
GtkWidget* volume static
Main volume slider.
Referenced by mixer_widget_create(), and on_reset_clicked().