vsid: arch/gtk3/widgets/settings_printer.c File Reference
settings_printer.c File Reference
Widget to control printer settings.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdbool.h>
#include "vice_gtk3.h"
#include "debug_gtk3.h"
#include "driver-select.h"
#include "resources.h"
#include "machine.h"
#include "printer.h"
#include "userport.h"
#include "printeremulationtypewidget.h"
#include "printerdriverwidget.h"
#include "printeroutputmodewidget.h"
#include "printeroutputdevicewidget.h"
#include "userportdevicecheckbutton.h"
#include "settings_printer.h"
Data Structures
struct child_s
GtkStack child data.
Macros
#define PRINTER_NUM 4
widgets
#define PRINTER_MIN 4
lowest device number for a printer
#define PRINTER_MAX 7
highest device number for a printer
#define PRINTER_USERPORT 3
userport printer virtual device number
Typedefs
typedef struct child_s child_t
GtkStack child data.
Functions
static int get_child_index_for_device (int device)
Get tab child index for device number.
static bool machine_has_iec (void)
Current machine has IEC bus support.
static bool machine_has_userport (void)
Current machine has userport.
static void on_real_device7_toggled (GtkCheckButton *check, gpointer user_data)
Handler for the "toggled" event of the Printer7 checkbox.
static void on_formfeed_clicked (GtkWidget *widget, gpointer data)
Handler for the 'clicked event of the "formfeed" button.
static GtkWidget * create_virtual_device_check_button (int device)
Create Virtual Device check button.
static GtkWidget * create_iec_check_button (int device)
Create IEC device emulation check button.
static GtkWidget * create_real_device7_check_button (void)
Create checkbox to switch between NONE/REAL emu mode for Printer7.
static GtkWidget * create_formfeed_button (const child_t *child)
Create button to send formfeed to the printer.
static void driver_radio_callback (GtkWidget *radio, int device, const char *drv_name)
Callback for driver changes.
static GtkWidget * create_printer_widget (int index)
Create a widget for the settings of printer # device.
static GtkWidget * create_printer_text_devices_widget (void)
Create widget to control Printer Text Devices 1-3.
GtkWidget * settings_printer_widget_create (GtkWidget *parent)
Create widget to control printer settings.
Variables
static const child_t children []
Stack child widget info.
static GtkWidget * output_mode_widget [sizeof children/sizeof children[0]]
Output mode widgets.
Detailed Description
Widget to control printer settings.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
PRINTER_MAX
#define PRINTER_MAX 7
highest device number for a printer
PRINTER_MIN
#define PRINTER_MIN 4
lowest device number for a printer
PRINTER_NUM
#define PRINTER_NUM 4
widgets
number of printer devices supported
PRINTER_USERPORT
#define PRINTER_USERPORT 3
userport printer virtual device number
Typedef Documentation
child_t
typedef struct child_s child_t
GtkStack child data.
Function Documentation
create_formfeed_button()
static GtkWidget * create_formfeed_button (const child_t * child) static
Create button to send formfeed to the printer.
Parameters
[in] child switcher child info
Returns
GtkButton
Referenced by create_printer_widget().
create_iec_check_button()
static GtkWidget * create_iec_check_button (int device) static
Create IEC device emulation check button.
Parameters
[in] device printer device
Returns
GtkCheckButton
Referenced by create_printer_widget().
create_printer_text_devices_widget()
static GtkWidget * create_printer_text_devices_widget (void) static
Create widget to control Printer Text Devices 1-3.
Returns
GtkGrid
Referenced by settings_printer_widget_create().
create_printer_widget()
static GtkWidget * create_printer_widget (int index) static
Create a widget for the settings of printer # device.
Creates a widget for device to control its resource. The widget for device #7 is different/simpler.
Parameters
[in] index index in the children array
Returns
GtkGrid
Referenced by settings_printer_widget_create().
create_real_device7_check_button()
static GtkWidget * create_real_device7_check_button (void) static
Create checkbox to switch between NONE/REAL emu mode for Printer7.
NOTE: Cannot use resourcecheckbutton here since this toggle button switches between PRINTER_DEVICE_NONE (0) and PRINTER_DEVICE_REAL (2).
Returns
GtkCheckButton
Referenced by create_printer_widget().
create_virtual_device_check_button()
static GtkWidget * create_virtual_device_check_button (int device) static
Create Virtual Device check button.
Parameters
[in] device printer device
Returns
GtkCheckButton
Referenced by create_printer_widget().
driver_radio_callback()
static void driver_radio_callback (GtkWidget * radio, int device, const char * drv_name) static
Callback for driver changes.
Parameters
[in] radio driver radio button (unused)
[in] device device number (4-7, 3)
[in] drv_name driver name
Todo:
FIXME: Ugly hack for RAW plotter driver. The RAW driver is a driver for printer AND plotter and it can only do text for printers and only graphics for plotters, so the logic using the capabilities in driver_select_t breaks down for RAW plotters.
Referenced by create_printer_widget().
get_child_index_for_device()
static int get_child_index_for_device (int device) static
Get tab child index for device number.
Parameters
[in] device device number (4-5: printer, 6: plotter, 7: opencbm, 3: userport)
Returns
tab child index or -1 on error
Referenced by driver_radio_callback().
machine_has_iec()
static bool machine_has_iec (void) static
Current machine has IEC bus support.
Returns
true if machine supportS IEC
Note
Returns false for xvic due to xvic having its own iecbus code.
Referenced by create_printer_widget().
machine_has_userport()
static bool machine_has_userport (void) static
Current machine has userport.
Returns
true if userport is capable of supporting printers/plotters
Note
Returns false for Plus/4 although it has a userport.
Referenced by settings_printer_widget_create().
on_formfeed_clicked()
static void on_formfeed_clicked (GtkWidget * widget, gpointer data) static
Handler for the 'clicked event of the "formfeed" button.
Parameters
[in] widget button
[in] data device number (3-6)
Referenced by create_formfeed_button().
on_real_device7_toggled()
static void on_real_device7_toggled (GtkCheckButton * check, gpointer user_data) static
Handler for the "toggled" event of the Printer7 checkbox.
Switches between PRINTER_DEVICE_NONE and PRINTER_DEVICE_REAL.
Parameters
[in] check check button
[in] user_data extra data (unused)
Referenced by create_real_device7_check_button().
settings_printer_widget_create()
GtkWidget * settings_printer_widget_create (GtkWidget * parent)
Create widget to control printer settings.
Parameters
[in] parent parent widget
Returns
GtkGrid
Variable Documentation
children
const child_t children[] static
Initial value:
= {
    {
        .title        = "Printer 4",
        .name         = "printer4",
        .device       = 4,
        .device_drv   =  0  ,
        .has_type     = true,
        .has_virtdev  = true,
        .has_iec      = true,
        .has_formfeed = true,
        .has_driver   = true,
        .has_outmode  = true,
        .has_outdev   = true
    },
    {
        .title        = "Printer 5",
        .name         = "printer5",
        .device       = 5,
        .device_drv   =  1  ,
        .has_type     = true,
        .has_virtdev  = true,
        .has_iec      = true,
        .has_formfeed = true,
        .has_driver   = true,
        .has_outmode  = true,
        .has_outdev   = true
    },
    {
        .title        = "Plotter 6",
        .name         = "plotter6",
        .device       = 6,
        .device_drv   =  2  ,
        .has_type     = true,
        .has_virtdev  = true,
        .has_iec      = true,
        .has_formfeed = true,
        .has_driver   = true,
        .has_outmode  = true,
        .has_outdev   = true,
    },
    {
        .title        = "OpenCBM 7",
        .name         = "opencbm7",
        .device       = 7,
        .device_drv   =  3 ,
        .has_virtdev  = true,
        .has_iec      = true,
        .has_realdev  = true,
    },
    {
        .title        = "Userport",
        .name         = "userport",
        .device       = 3,
        .has_userport = true,
        .has_driver   = true,
        .has_outmode  = true,
        .has_outdev   = true,
        .has_formfeed = true
    }
}
Stack child widget info.
Referenced by create_printer_widget(), get_child_index_for_device(), populate_tree_model(), settings_printer_widget_create(), ui_datasette_update_sensitive(), ui_do_datasette_popup(), ui_do_drive_popup(), and ui_populate_fliplist_menu().
output_mode_widget
GtkWidget* output_mode_widget[sizeof children/sizeof children[0]] static
Output mode widgets.
Referenced by create_printer_widget(), and driver_radio_callback().