vsid: arch/shared/archdep_mkstemp_fd.c File Reference
archdep_mkstemp_fd.c File Reference
Create temporary file, return file pointer.
#include "vice.h"
#include "archdep_defs.h"
#include <stdio.h>
#include <stdlib.h>
#include "lib.h"
#include "util.h"
#include "archdep_mkstemp_fd.h"
Functions
FILE * archdep_mkstemp_fd (char **filename, const char *mode)
Unix.
Detailed Description
Create temporary file, return file pointer.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Note
Only tested on Windows and Linux
Function Documentation
archdep_mkstemp_fd()
FILE * archdep_mkstemp_fd (char ** filename, const char * mode)
Unix.
Create temporary file.
Referenced by drive_snapshot_read_image_module(), event_playback_attach_image(), network_connect_client(), tape_snapshot_read_tapimage_module(), and try_uncompress_with_gzip().