vsid: sound_device_s Struct Reference
sound_device_s Struct Reference
device structure
#include <sound.h>
Data Fields
const char * name
int(* init)(const char *param, int *speed, int *fragsize, int *fragnr, int *channels)
int(* write)(int16_t *pbuf, size_t nr)
int(* dump)(uint16_t addr, uint8_t byte, CLOCK clks)
int(* flush)(char *state)
int(* bufferspace)(void)
void(* close)(void)
int(* suspend)(void)
int(* resume)(void)
int need_attenuation
int max_channels
bool is_timing_source
Detailed Description
device structure
Field Documentation
bufferspace
int(* sound_device_s::bufferspace) (void)
Referenced by sound_flush(), sound_open(), and sound_suspend().
close
void(* sound_device_s::close) (void)
Referenced by sound_open().
dump
int(* sound_device_s::dump) (uint16_t addr, uint8_t byte, CLOCK clks)
Referenced by sound_store().
flush
int(* sound_device_s::flush) (char *state)
Referenced by sound_flush().
init
int(* sound_device_s::init) (const char *param, int *speed, int *fragsize, int *fragnr, int *channels)
Referenced by sound_open().
is_timing_source
bool sound_device_s::is_timing_source
Referenced by sound_open().
max_channels
int sound_device_s::max_channels
name
const char* sound_device_s::name
Referenced by sound_device_name(), and sound_open().
need_attenuation
int sound_device_s::need_attenuation
Referenced by sound_resume(), and sound_suspend().
resume
int(* sound_device_s::resume) (void)
Referenced by sound_resume().
suspend
int(* sound_device_s::suspend) (void)
Referenced by sound_suspend().
write
int(* sound_device_s::write) (int16_t *pbuf, size_t nr)
Referenced by fill_buffer(), sound_flush(), sound_resume(), and sound_suspend().
The documentation for this struct was generated from the following file:
sound.h