x128: arch/gtk3/widgets/kernalrevisionwidget.h File Reference
kernalrevisionwidget.h File Reference
GTK3 KERNAL revision widget - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
GtkWidget * kernal_revision_widget_create (void)
Create KERNAL revision widget (c64/c64sc/c64dtv only)
void kernal_revision_widget_update (GtkWidget *widget, int revision)
Update KERNAL revision widget.
void kernal_revision_widget_sync (GtkWidget *widget)
Synchronize the KERNAL widget with its current value.
void kernal_revision_widget_add_callback (void(*callback)(int))
Add extra callback.
Detailed Description
GTK3 KERNAL revision widget - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
kernal_revision_widget_add_callback()
void kernal_revision_widget_add_callback (void(*)(int) callback)
Add extra callback.
Parameters
[in] callback extra callback for widget changes
Referenced by create_c64_layout().
kernal_revision_widget_create()
GtkWidget * kernal_revision_widget_create (void)
Create KERNAL revision widget (c64/c64sc/c64dtv only)
Returns
GtkGrid
Referenced by create_c64_layout().
kernal_revision_widget_sync()
void kernal_revision_widget_sync (GtkWidget * widget)
Synchronize the KERNAL widget with its current value.
Parameters
[in,out] widget KERNAL version widget
Referenced by machine_model_handler_c64().
kernal_revision_widget_update()
void kernal_revision_widget_update (GtkWidget * widget, int revision)
Update KERNAL revision widget.
Parameters
[in,out] widget KERNAL revision widget
[in] revision new revision (
See also
src/c64/c64-resources.h)