vsid: arch/gtk3/widgets/base/resourcewidgetmediator.h File Reference
resourcewidgetmediator.h File Reference
Resource widget mediator - header.
#include <gtk/gtk.h>
Data Structures
struct mediator_s
Resource widget mediator object.
Typedefs
typedef struct mediator_s mediator_t
Resource widget mediator object.
Functions
mediator_t * mediator_new (GtkWidget *widget, const char *name, GType type)
Create and attach resource widget mediator.
GtkWidget * mediator_get_widget (mediator_t *mediator)
Get widget of the mediator.
mediator_t * mediator_for_widget (GtkWidget *widget)
Get the mediator for a widget.
const char * mediator_get_name (mediator_t *mediator)
Get resource name of a mediator.
const char * mediator_get_name_w (GtkWidget *widget)
Get resource name of a mediator for a widget.
void mediator_set_data (mediator_t *mediator, void *data, void(*data_free)(void *))
Set pointer to additional state data a widget might need.
void * mediator_get_data (mediator_t *mediator)
Get pointer to additional state data.
void * mediator_get_data_w (GtkWidget *widget)
Get pointer to additional state data through widget.
void mediator_set_handler (mediator_t *mediator, gulong handler)
Set ID of the signal handler of the widget that updates the resource.
void mediator_handler_block (mediator_t *mediator)
Block signal handler registered on the widget for resource updates.
void mediator_handler_unblock (mediator_t *mediator)
Unblock signal handler registered on the widget for resource updates.
gboolean mediator_get_resource_boolean (mediator_t *mediator)
Get boolean resource value through mediator.
gboolean mediator_get_initial_boolean (mediator_t *mediator)
Get boolean resource value on mediator instanciation.
gboolean mediator_get_factory_boolean (mediator_t *mediator)
Get boolean factory value for resource.
gboolean mediator_get_current_boolean (mediator_t *mediator)
Get last valid value of boolean resource.
void mediator_set_current_boolean (mediator_t *mediator, gboolean value)
Set current boolean resource value in the mediator.
void mediator_set_callback_boolean (mediator_t *mediator, void(*callback)(GtkWidget *, gboolean))
Set callback function to be called on succesful resource updates.
void mediator_set_callback_boolean_w (GtkWidget *widget, void(*callback)(GtkWidget *, gboolean))
Set callback function to be called on succesful resource updates.
gboolean mediator_update_boolean (mediator_t *mediator, gboolean value)
Set resource, update internal mediator and trigger user callback.
gboolean mediator_update_boolean_w (GtkWidget *widget, gboolean value)
Shortcut for mediator_update_boolean() using a widget.
int mediator_get_resource_int (mediator_t *mediator)
Get integer resource value through mediator.
int mediator_get_initial_int (mediator_t *mediator)
Get integer resource value on mediator instanciation.
int mediator_get_factory_int (mediator_t *mediator)
Get integer resource factory value.
int mediator_get_current_int (mediator_t *mediator)
Get last valid value of integer resource.
void mediator_set_current_int (mediator_t *mediator, int value)
Set current integer resource value in the mediator.
void mediator_set_callback_int (mediator_t *mediator, void(*callback)(GtkWidget *, int))
Set callback function to be called on succesful resource updates.
gboolean mediator_update_int (mediator_t *mediator, int value)
Set resource, update internal mediator and trigger user callback.
gboolean mediator_update_int_w (GtkWidget *widget, int value)
Shortcut for mediator_update_int() using a widget.
const char * mediator_get_resource_string (mediator_t *mediator)
Get current string value of the resource.
const char * mediator_get_initial_string (mediator_t *mediator)
Get string resource value on mediator instanciation.
const char * mediator_get_factory_string (mediator_t *mediator)
Get string factory value of resource.
const char * mediator_get_current_string (mediator_t *mediator)
Get last valid string resource value.
void mediator_set_current_string (mediator_t *mediator, const char *value)
Set last valid string resource value.
void mediator_set_callback_string (mediator_t *mediator, void(*callback)(GtkWidget *, const char *))
Set user-defined callback.
void mediator_set_callback_string_w (GtkWidget *widget, void(*callback)(GtkWidget *, const char *))
Set user-defined callback on widget.
gboolean mediator_update_string (mediator_t *mediator, const char *value)
Update string resource value, trigger callback.
gboolean mediator_update_string_w (GtkWidget *widget, const char *value)
Update string resource value, trigger callback.
Detailed Description
Resource widget mediator - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Typedef Documentation
mediator_t
typedef struct mediator_s mediator_t
Resource widget mediator object.
Function Documentation
mediator_for_widget()
mediator_t * mediator_for_widget (GtkWidget * widget)
Get the mediator for a widget.
Returns
mediator or NULL when no mediator is attached
Referenced by cart_image_widget_append_check(), mediator_get_data_w(), mediator_get_name_w(), mediator_set_callback_boolean_w(), mediator_set_callback_string_w(), mediator_update_boolean_w(), mediator_update_int_w(), mediator_update_string_w(), on_check_button_toggled(), on_combo_int_changed(), on_combo_str_changed(), on_icon_press(), on_switch_notify_active(), resource_entry_update_resource(), set_resource_and_entry(), update_resource_value(), vice_gtk3_resource_check_button_factory(), vice_gtk3_resource_check_button_reset(), vice_gtk3_resource_check_button_sync(), vice_gtk3_resource_combo_int_factory(), vice_gtk3_resource_combo_int_reset(), vice_gtk3_resource_combo_int_sync(), vice_gtk3_resource_combo_str_factory(), vice_gtk3_resource_combo_str_reset(), vice_gtk3_resource_combo_str_sync(), vice_gtk3_resource_entry_factory(), vice_gtk3_resource_entry_reset(), vice_gtk3_resource_entry_sync(), vice_gtk3_resource_filechooser_set_callback(), vice_gtk3_resource_filechooser_set_confirm(), vice_gtk3_resource_filechooser_set_custom_title(), vice_gtk3_resource_filechooser_set_directory(), vice_gtk3_resource_filechooser_set_filter(), vice_gtk3_resource_filechooser_sync(), vice_gtk3_resource_switch_factory(), vice_gtk3_resource_switch_reset(), and vice_gtk3_resource_switch_sync().
mediator_get_current_boolean()
gboolean mediator_get_current_boolean (mediator_t * mediator)
Get last valid value of boolean resource.
The current member is updated on succesfully setting the resource, it can be used to revert a widget to its previous state should setting the resource fail.
Parameters
[in] mediator resource mediator
Returns
last valid resource value
Referenced by on_check_button_toggled(), on_switch_notify_active(), and vice_gtk3_resource_switch_new().
mediator_get_current_int()
int mediator_get_current_int (mediator_t * mediator)
Get last valid value of integer resource.
The current member is updated on succesfully setting the resource, it can be used to revert a widget to its previous state should setting the resource fail.
Parameters
[in] mediator resource mediator
Returns
last valid resource value
Referenced by combo_hex_helper(), on_combo_int_changed(), and vice_gtk3_resource_combo_int_new().
mediator_get_current_string()
const char * mediator_get_current_string (mediator_t * mediator)
Get last valid string resource value.
Get the last valid value of the resource. This can be used to revert the widget to its previous state when setting the resource fails.
Parameters
[in] mediator resource mediator
Returns
last valid value
Referenced by on_combo_str_changed(), resource_entry_update_resource(), and vice_gtk3_resource_entry_new().
mediator_get_data()
void * mediator_get_data (mediator_t * mediator)
Get pointer to additional state data.
Parameters
[in] mediator
Returns
object or NULL when not set
Referenced by cart_image_widget_append_check(), on_icon_press(), set_resource_and_entry(), vice_gtk3_resource_filechooser_set_callback(), vice_gtk3_resource_filechooser_set_confirm(), vice_gtk3_resource_filechooser_set_custom_title(), vice_gtk3_resource_filechooser_set_directory(), and vice_gtk3_resource_filechooser_set_filter().
mediator_get_data_w()
void * mediator_get_data_w (GtkWidget * widget)
Get pointer to additional state data through widget.
Parameters
[in] widget widget with resource mediator
Returns
object or NULL when not set
Referenced by on_entry_changed(), value_is_valid(), and vice_gtk3_resource_numeric_string_set_limits().
mediator_get_factory_boolean()
gboolean mediator_get_factory_boolean (mediator_t * mediator)
Get boolean factory value for resource.
Parameters
[in] mediator resource mediator
Returns
resource factory value
Referenced by vice_gtk3_resource_check_button_factory(), and vice_gtk3_resource_switch_factory().
mediator_get_factory_int()
int mediator_get_factory_int (mediator_t * mediator)
Get integer resource factory value.
Parameters
[in] mediator resource mediator
Returns
factory value
Referenced by vice_gtk3_resource_combo_int_factory().
mediator_get_factory_string()
const char * mediator_get_factory_string (mediator_t * mediator)
Get string factory value of resource.
Parameters
[in] mediator resource mediator
Returns
factory value
Referenced by vice_gtk3_resource_combo_str_factory(), and vice_gtk3_resource_entry_factory().
mediator_get_initial_boolean()
gboolean mediator_get_initial_boolean (mediator_t * mediator)
Get boolean resource value on mediator instanciation.
Parameters
[in] mediator resource mediator
Returns
resource value
Referenced by vice_gtk3_resource_check_button_new(), vice_gtk3_resource_check_button_reset(), and vice_gtk3_resource_switch_reset().
mediator_get_initial_int()
int mediator_get_initial_int (mediator_t * mediator)
Get integer resource value on mediator instanciation.
Parameters
[in] mediator resource mediator
Returns
resource's value when mediator_new() was called
Referenced by vice_gtk3_resource_combo_int_reset().
mediator_get_initial_string()
const char * mediator_get_initial_string (mediator_t * mediator)
Get string resource value on mediator instanciation.
Parameters
[in] mediator resource mediator
Returns
value of resource on mediator instanciation
Referenced by vice_gtk3_resource_combo_str_reset(), and vice_gtk3_resource_entry_reset().
mediator_get_name()
const char * mediator_get_name (mediator_t * mediator)
Get resource name of a mediator.
Get the resource name of mediator.
Parameters
[in] mediator
Returns
resource name
mediator_get_name_w()
const char * mediator_get_name_w (GtkWidget * widget)
Get resource name of a mediator for a widget.
Get the resource name of the mediator for widget. If no mediator is attached NULL is returned
Returns
resource name
Referenced by expandable_list_get_chooser_by_resource(), expandable_list_get_resources(), on_chooser_drag_data_received(), on_eject_icon_clicked(), and on_reset_icon_clicked().
mediator_get_resource_boolean()
gboolean mediator_get_resource_boolean (mediator_t * mediator)
Get boolean resource value through mediator.
Parameters
[in] mediator resource mediator
Returns
resource value
Referenced by vice_gtk3_resource_check_button_sync(), and vice_gtk3_resource_switch_sync().
mediator_get_resource_int()
int mediator_get_resource_int (mediator_t * mediator)
Get integer resource value through mediator.
Parameters
[in] mediator resource mediator
Returns
resource value
Referenced by vice_gtk3_resource_combo_int_sync().
mediator_get_resource_string()
const char * mediator_get_resource_string (mediator_t * mediator)
Get current string value of the resource.
Parameters
[in] mediator resource mediator
Returns
value of resource
Referenced by create_filename_entry(), on_icon_press(), resource_entry_update_resource(), set_resource_and_entry(), update_resource_value(), vice_gtk3_resource_combo_str_new(), vice_gtk3_resource_combo_str_sync(), vice_gtk3_resource_entry_sync(), vice_gtk3_resource_filechooser_new(), vice_gtk3_resource_filechooser_sync(), and vice_gtk3_resource_numeric_string_new().
mediator_get_widget()
GtkWidget * mediator_get_widget (mediator_t * mediator)
Get widget of the mediator.
Parameters
[in] mediator resource mediator
Returns
GtkWidget
mediator_handler_block()
void mediator_handler_block (mediator_t * mediator)
Block signal handler registered on the widget for resource updates.
Block the signal handler of the widget that is used to update the bound resource on widget state changes.
Parameters
[in] mediator
Note
Requires a handler ID having been set via mediator_set_handler().
Referenced by on_combo_int_changed(), on_combo_str_changed(), vice_gtk3_resource_check_button_sync(), vice_gtk3_resource_combo_int_sync(), vice_gtk3_resource_combo_str_sync(), and vice_gtk3_resource_switch_sync().
mediator_handler_unblock()
void mediator_handler_unblock (mediator_t * mediator)
Unblock signal handler registered on the widget for resource updates.
Unlock the signal handler of the widget that is used to update the bound resource on widget state changes.
Parameters
[in] mediator
Note
Requires a handler ID having been set via mediator_set_handler().
Referenced by on_combo_int_changed(), on_combo_str_changed(), vice_gtk3_resource_check_button_sync(), vice_gtk3_resource_combo_int_sync(), vice_gtk3_resource_combo_str_sync(), and vice_gtk3_resource_switch_sync().
mediator_new()
mediator_t * mediator_new (GtkWidget * widget, const char * name, GType type)
Create and attach resource widget mediator.
Create new resource mediator object for resource name and attach it to widget. Registers a 'destroy' signal handler on widget that frees the mediator and its members.
The resource name can be NULL so the mediator can be used to wrangle additional state objects (like in cartwidgets.c).
Parameters
[in] widget resource widget
[in] name resource name
[in] type resource type (G_TYPE_BOOLEAN, G_TYPE_INT or G_TYPE_STRING)
Returns
new resource mediator
Referenced by cart_image_widget_new(), combo_hex_helper(), vice_gtk3_resource_check_button_new(), vice_gtk3_resource_combo_int_new(), vice_gtk3_resource_combo_str_new(), vice_gtk3_resource_entry_new(), vice_gtk3_resource_filechooser_new(), vice_gtk3_resource_numeric_string_new(), and vice_gtk3_resource_switch_new().
mediator_set_callback_boolean()
void mediator_set_callback_boolean (mediator_t * mediator, void(*)(GtkWidget *, gboolean) callback)
Set callback function to be called on succesful resource updates.
When a resource is succesfully updated callback will be called with the widget and the new resource value as its arguments.
Parameters
[in] mediator resource mediator
[in] callback user-defined callback
mediator_set_callback_boolean_w()
void mediator_set_callback_boolean_w (GtkWidget * widget, void(*)(GtkWidget *, gboolean) callback)
Set callback function to be called on succesful resource updates.
When a resource is succesfully updated callback will be called with the widget and the new resource value as its arguments.
Parameters
[in] widget resource widget
[in] callback user-defined callback
Referenced by vice_gtk3_resource_check_button_add_callback(), and vice_gtk3_resource_switch_add_callback().
mediator_set_callback_int()
void mediator_set_callback_int (mediator_t * mediator, void(*)(GtkWidget *, int) callback)
Set callback function to be called on succesful resource updates.
When a resource is succesfully updated callback will be called with the widget and the new resource value as its arguments.
Parameters
[in] mediator resource mediator
[in] callback user-defined callback
mediator_set_callback_string()
void mediator_set_callback_string (mediator_t * mediator, void(*)(GtkWidget *, const char *) callback)
Set user-defined callback.
Register callback to be called on succesful resource changes.
Parameters
[in] mediator resource mediator
[in] callback user-defined function
mediator_set_callback_string_w()
void mediator_set_callback_string_w (GtkWidget * widget, void(*)(GtkWidget *, const char *) callback)
Set user-defined callback on widget.
Register callback to be called on succesful resource changes.
Parameters
[in] widget string resource-bound widget
[in] callback user-defined function
mediator_set_current_boolean()
void mediator_set_current_boolean (mediator_t * mediator, gboolean value)
Set current boolean resource value in the mediator.
Calling this will update the last valid value of the resource in the mediator, which can be used to revert the widget to its previous state when setting the resource fails. When using update() there's no need to call this, that function calls this function on success.
Parameters
[in] mediator resource mediator
[in] value resource value
Referenced by mediator_get_resource_boolean(), and mediator_update_boolean().
mediator_set_current_int()
void mediator_set_current_int (mediator_t * mediator, int value)
Set current integer resource value in the mediator.
Calling this will update the last valid value of the resource in the mediator, which can be used to revert the widget to its previous state when setting the resource fails. When using update() there's no need to call this, that function calls this function on success.
Parameters
[in] mediator resource mediator
[in] value resource value
Referenced by mediator_update_int().
mediator_set_current_string()
void mediator_set_current_string (mediator_t * mediator, const char * value)
Set last valid string resource value.
Set the last valid value of the resource. This can be used to revert the widget to its previous state when setting the resource fails.
Parameters
[in] mediator resource mediator
Returns
last valid value
Referenced by mediator_update_string().
mediator_set_data()
void mediator_set_data (mediator_t * mediator, void * data, void(*)(void *) data_free)
Set pointer to additional state data a widget might need.
Parameters
[in] mediator resource mediator
[in] data additional state object
[in] data_free function to call to free data (can be NULL)
Referenced by cart_image_widget_new(), vice_gtk3_resource_filechooser_new(), and vice_gtk3_resource_numeric_string_new().
mediator_set_handler()
void mediator_set_handler (mediator_t * mediator, gulong handler)
Set ID of the signal handler of the widget that updates the resource.
Set ID of the signal handler of the widget that is used to update the bound resource on widget state changes.
Parameters
[in] mediator resource mediator
[in] handler ID of the signal handler
Referenced by combo_hex_helper(), vice_gtk3_resource_check_button_new(), vice_gtk3_resource_combo_int_new(), vice_gtk3_resource_combo_str_new(), and vice_gtk3_resource_switch_new().
mediator_update_boolean()
gboolean mediator_update_boolean (mediator_t * mediator, gboolean value)
Set resource, update internal mediator and trigger user callback.
Set resource and upon success update the last valid resource value in mediator and trigger the user-registered callback, if present.
Parameters
[in] mediator resource mediator
[in] value new value for resource
Returns
TRUE if the resource succesfully updated
Referenced by mediator_update_boolean_w(), on_check_button_toggled(), and on_switch_notify_active().
mediator_update_boolean_w()
gboolean mediator_update_boolean_w (GtkWidget * widget, gboolean value)
Shortcut for mediator_update_boolean() using a widget.
Calls mediator_update_boolean() on the mediator obtained from widget.
Parameters
[in] widget resource widget
[in] value resource value
Returns
TRUE if the resource succesfully updated
mediator_update_int()
gboolean mediator_update_int (mediator_t * mediator, int value)
Set resource, update internal mediator and trigger user callback.
Set resource and upon success update the last valid resource value in mediator and trigger the user-registered callback, if present.
Parameters
[in] mediator resource mediator
[in] value new value for resource
Returns
TRUE if the resource succesfully updated
Referenced by mediator_update_int_w(), and on_combo_int_changed().
mediator_update_int_w()
gboolean mediator_update_int_w (GtkWidget * widget, int value)
Shortcut for mediator_update_int() using a widget.
Calls mediator_update_int() on the mediator obtained from widget.
Parameters
[in] widget resource widget
[in] value resource value
Returns
TRUE if the resource succesfully updated
mediator_update_string()
gboolean mediator_update_string (mediator_t * mediator, const char * value)
Update string resource value, trigger callback.
Update the resource of mediator to value, mark value as the last valid value and call the user-definedcallback (if present) on succesful resource change.
Parameters
[in] mediator resource mediator
[in] value new string value for resource
Returns
TRUE on succesful resource change
Referenced by mediator_update_string_w(), on_combo_str_changed(), resource_entry_update_resource(), set_resource_and_entry(), update_resource(), and update_resource_value().
mediator_update_string_w()
gboolean mediator_update_string_w (GtkWidget * widget, const char * value)
Update string resource value, trigger callback.
Update the resource of mediator to value, mark value as the last valid value and call the user-definedcallback (if present) on succesful resource change.
Parameters
[in] mediator resource mediator
[in] value new string value for resource
Returns
TRUE on succesful resource change