vsid: raster/raster-cache.c File Reference
raster-cache.c File Reference
#include "vice.h"
#include <string.h>
#include "lib.h"
#include "raster-cache.h"
#include "raster-sprite-status.h"
Functions
void raster_cache_new (raster_cache_t *cache, raster_sprite_status_t *status)
void raster_cache_destroy (raster_cache_t *cache, raster_sprite_status_t *status)
void raster_cache_realloc (raster_cache_t **cache, unsigned int screen_height)
Function Documentation
raster_cache_destroy()
void raster_cache_destroy (raster_cache_t * cache, raster_sprite_status_t * status)
Referenced by raster_destroy_cache().
raster_cache_new()
void raster_cache_new (raster_cache_t * cache, raster_sprite_status_t * status)
Referenced by raster_new_cache().
raster_cache_realloc()
void raster_cache_realloc (raster_cache_t ** cache, unsigned int screen_height)
Referenced by raster_set_geometry().