vsid: core/ata.c File Reference
ata.c File Reference
#include "vice.h"
#include <sys/types.h>
#include <stdio.h>
#include <string.h>
#include "archdep.h"
#include "log.h"
#include "ata.h"
#include "snapshot.h"
#include "types.h"
#include "util.h"
#include "lib.h"
#include "alarm.h"
#include "maincpu.h"
#include "monitor.h"
Data Structures
struct ata_drive_s
Macros
#define ATA_UNC 0x40
required for off_t on some platforms
#define ATA_IDNF 0x10
#define ATA_ABRT 0x04
#define ATA_WP 0x40
#define ATA_DRDY 0x40
#define ATA_DRQ 0x08
#define ATA_ERR 0x01
#define ATA_COPYRIGHT "KAJTAR ZSOLT (SOCI/SINGULAR)"
#define ATA_SERIAL_NUMBER &"$Date:: 2015-02-17 13:41:45 #$"[8]
#define ATA_REVISION &"$Revision:: 29352 $"[12]
#define debug(_x_)
#define putw(a, b) {result[(a) * 2] = (b) & 0xff; result[(a) * 2 + 1] = (b) >> 8; }
#define setb(a, b, c) {result[(a) * 2 + (b) / 8] |= (c) ? (1 << ((b) & 7)) : 0; }
#define CART_DUMP_VER_MAJOR 0
snapshot support functions
#define CART_DUMP_VER_MINOR 7
Functions
static void ident_update_string (uint8_t *b, char *s, int n)
static void ata_change_power_mode (ata_drive_t *drv, uint8_t value)
static int ata_set_standby (ata_drive_t *drv, int value)
static void drive_diag (ata_drive_t *drv)
static void ata_set_command_block (ata_drive_t *drv)
static int seek_sector (ata_drive_t *drv)
static void debug_addr (ata_drive_t *drv, char *cmd)
static int read_sector (ata_drive_t *drv)
static int write_sector (ata_drive_t *drv)
void ata_reset (ata_drive_t *drv)
void ata_update_timing (ata_drive_t *drv, CLOCK cycles_1s)
static void ata_poweron (ata_drive_t *drv, ata_drive_type_t type)
static void ata_spindle_alarm_handler (CLOCK offset, void *data)
static void ata_head_alarm_handler (CLOCK offset, void *data)
static void ata_standby_alarm_handler (CLOCK offset, void *data)
ata_drive_t * ata_init (int drive)
void ata_shutdown (ata_drive_t *drv)
static void ata_execute_command (ata_drive_t *drv, uint8_t value)
static void atapi_execute_command (ata_drive_t *drv, uint8_t value)
static void atapi_packet_execute_command (ata_drive_t *drv)
uint16_t ata_register_read (ata_drive_t *drv, uint16_t addr, uint16_t bus)
uint16_t ata_register_peek (ata_drive_t *drv, uint16_t addr)
void ata_register_store (ata_drive_t *drv, uint16_t addr, uint16_t value)
void ata_image_attach (ata_drive_t *drv, char *filename, ata_drive_type_t type, ata_drive_geometry_t geometry)
void ata_image_detach (ata_drive_t *drv)
int ata_image_change (ata_drive_t *drv, char *filename, ata_drive_type_t type, ata_drive_geometry_t geometry)
int ata_register_dump (ata_drive_t *drv)
int ata_snapshot_write_module (ata_drive_t *drv, snapshot_t *s)
int ata_snapshot_read_module (ata_drive_t *drv, snapshot_t *s)
Variables
static const uint8_t identify [128]
Macro Definition Documentation
ATA_ABRT
#define ATA_ABRT 0x04
ATA_COPYRIGHT
#define ATA_COPYRIGHT "KAJTAR ZSOLT (SOCI/SINGULAR)"
ATA_DRDY
#define ATA_DRDY 0x40
ATA_DRQ
#define ATA_DRQ 0x08
ATA_ERR
#define ATA_ERR 0x01
ATA_IDNF
#define ATA_IDNF 0x10
ATA_REVISION
#define ATA_REVISION &"$Revision:: 29352 $"[12]
ATA_SERIAL_NUMBER
#define ATA_SERIAL_NUMBER &"$Date:: 2015-02-17 13:41:45 #$"[8]
ATA_UNC
#define ATA_UNC 0x40
required for off_t on some platforms
ATA_WP
#define ATA_WP 0x40
CART_DUMP_VER_MAJOR
#define CART_DUMP_VER_MAJOR 0
snapshot support functions
CART_DUMP_VER_MINOR
#define CART_DUMP_VER_MINOR 7
debug
#define debug (_x_)
putw
#define putw (a, b) {result[(a) * 2] = (b) & 0xff; result[(a) * 2 + 1] = (b) >> 8; }
setb
#define setb (a, b, c) {result[(a) * 2 + (b) / 8] |= (c) ? (1 << ((b) & 7)) : 0; }
Function Documentation
ata_change_power_mode()
static void ata_change_power_mode (ata_drive_t * drv, uint8_t value) static
Referenced by ata_execute_command(), ata_poweron(), atapi_packet_execute_command(), and seek_sector().
ata_execute_command()
static void ata_execute_command (ata_drive_t * drv, uint8_t value) static
Referenced by ata_register_store(), and atapi_execute_command().
ata_head_alarm_handler()
static void ata_head_alarm_handler (CLOCK offset, void * data) static
Referenced by ata_init().
ata_image_attach()
void ata_image_attach (ata_drive_t * drv, char * filename, ata_drive_type_t type, ata_drive_geometry_t geometry)
< read/write mode
< read mode (binary)
Referenced by ata_image_change(), ata_snapshot_read_module(), and atapi_packet_execute_command().
ata_image_change()
int ata_image_change (ata_drive_t * drv, char * filename, ata_drive_type_t type, ata_drive_geometry_t geometry)
ata_image_detach()
void ata_image_detach (ata_drive_t * drv)
Referenced by atapi_packet_execute_command().
ata_init()
ata_drive_t * ata_init (int drive)
ata_poweron()
static void ata_poweron (ata_drive_t * drv, ata_drive_type_t type) static
Referenced by ata_image_attach(), and ata_init().
ata_register_dump()
int ata_register_dump (ata_drive_t * drv)
ata_register_peek()
uint16_t ata_register_peek (ata_drive_t * drv, uint16_t addr)
Referenced by ata_register_dump().
ata_register_read()
uint16_t ata_register_read (ata_drive_t * drv, uint16_t addr, uint16_t bus)
Referenced by ata_register_peek().
ata_register_store()
void ata_register_store (ata_drive_t * drv, uint16_t addr, uint16_t value)
ata_reset()
void ata_reset (ata_drive_t * drv)
Referenced by ata_poweron(), and ata_register_store().
ata_set_command_block()
static void ata_set_command_block (ata_drive_t * drv) static
Referenced by read_sector(), and write_sector().
ata_set_standby()
static int ata_set_standby (ata_drive_t * drv, int value) static
Referenced by ata_execute_command().
ata_shutdown()
void ata_shutdown (ata_drive_t * drv)
ata_snapshot_read_module()
int ata_snapshot_read_module (ata_drive_t * drv, snapshot_t * s)
Todo:
FIXME: this is really retarded - we should instead identify the image by making a checksum instead of using the filename
ata_snapshot_write_module()
int ata_snapshot_write_module (ata_drive_t * drv, snapshot_t * s)
ata_spindle_alarm_handler()
static void ata_spindle_alarm_handler (CLOCK offset, void * data) static
Referenced by ata_init().
ata_standby_alarm_handler()
static void ata_standby_alarm_handler (CLOCK offset, void * data) static
Referenced by ata_init().
ata_update_timing()
void ata_update_timing (ata_drive_t * drv, CLOCK cycles_1s)
Referenced by ata_poweron().
atapi_execute_command()
static void atapi_execute_command (ata_drive_t * drv, uint8_t value) static
Referenced by ata_register_store().
atapi_packet_execute_command()
static void atapi_packet_execute_command (ata_drive_t * drv) static
Referenced by ata_register_store().
debug_addr()
static void debug_addr (ata_drive_t * drv, char * cmd) static
Referenced by ata_execute_command().
drive_diag()
static void drive_diag (ata_drive_t * drv) static
Referenced by ata_execute_command(), ata_reset(), and atapi_execute_command().
ident_update_string()
static void ident_update_string (uint8_t * b, char * s, int n) static
Referenced by ata_execute_command(), and atapi_execute_command().
read_sector()
static int read_sector (ata_drive_t * drv) static
Referenced by ata_execute_command(), ata_register_read(), and atapi_packet_execute_command().
seek_sector()
static int seek_sector (ata_drive_t * drv) static
Referenced by ata_execute_command(), and atapi_packet_execute_command().
write_sector()
static int write_sector (ata_drive_t * drv) static
Referenced by ata_register_store().
Variable Documentation
identify
const uint8_t identify[128] static
Initial value:
= {
    0x40, 0x00, 0x00, 0x01, 0x00, 0x00, 0x04, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x30, 0x32, 0x31, 0x31,
    0x38, 0x30, 0x30, 0x32, 0x20, 0x20, 0x20, 0x20,
    0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x36,
    0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x49, 0x56,
    0x45, 0x43, 0x48, 0x2d, 0x44, 0x44, 0x20, 0x20,
    0x20, 0x20, 0x41, 0x4b, 0x54, 0x4a, 0x52, 0x41,
    0x5a, 0x20, 0x4f, 0x53, 0x54, 0x4c, 0x28, 0x20,
    0x4f, 0x53, 0x49, 0x43, 0x53, 0x2f, 0x4e, 0x49,
    0x55, 0x47, 0x41, 0x4c, 0x29, 0x52, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x04, 0x00,
    0x10, 0x00, 0x00, 0x40, 0x00, 0x00, 0x01, 0x01,
    0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}
Referenced by ata_image_attach().