x128: vdc/vdc-mem.h File Reference
vdc-mem.h File Reference
#include "types.h"
Functions
void vdc_store (uint16_t addr, uint8_t value)
VDC interface functions.
uint8_t vdc_read (uint16_t addr)
uint8_t vdc_peek (uint16_t addr)
void vdc_ram_store (uint16_t addr, uint8_t value)
uint8_t vdc_ram_read (uint16_t addr)
int vdc_dump (void)
Function Documentation
vdc_dump()
int vdc_dump (void)
vdc_peek()
uint8_t vdc_peek (uint16_t addr)
vdc_ram_read()
uint8_t vdc_ram_read (uint16_t addr)
Referenced by draw_std_bitmap(), draw_std_text(), mem_bank_read(), mem_read_screen(), vdc_peek(), vdc_perform_fillcopy(), vdc_raster_draw_alarm_handler(), and vdc_read().
vdc_ram_store()
void vdc_ram_store (uint16_t addr, uint8_t value)
Referenced by mem_bank_write(), vdc_perform_fillcopy(), and vdc_write_data().
vdc_read()
uint8_t vdc_read (uint16_t addr)
Referenced by vdc_peek(), and z80_vdc_read().
vdc_store()
void vdc_store (uint16_t addr, uint8_t value)
VDC interface functions.
Store a value in a VDC register.
< 8563 R7A
Referenced by z80_vdc_store().