vsid: core/ser-eeprom.h File Reference
ser-eeprom.h File Reference
#include "types.h"
Functions
void eeprom_data_readadvance (void)
TODO.
uint8_t eeprom_data_readbyte (void)
uint8_t eeprom_data_readbit (void)
uint8_t eeprom_data_read (void)
void eeprom_cmd_reset (void)
void eeprom_cmd_write (uint8_t value)
void eeprom_seq_reset (void)
void eeprom_seq_write (uint8_t value)
int eeprom_execute_command (int eeprom_mode)
void eeprom_port_write (uint8_t clk, uint8_t data, int ddr, int status)
int eeprom_open_image (char *name, int rw)
void eeprom_close_image (int rw)
int eeprom_snapshot_read_module (struct snapshot_s *s)
int eeprom_snapshot_write_module (struct snapshot_s *s)
Function Documentation
eeprom_close_image()
void eeprom_close_image (int rw)
Referenced by eeprom_open_image().
eeprom_cmd_reset()
void eeprom_cmd_reset (void)
Referenced by eeprom_port_write().
eeprom_cmd_write()
void eeprom_cmd_write (uint8_t value)
Referenced by eeprom_port_write().
eeprom_data_read()
uint8_t eeprom_data_read (void)
eeprom_data_readadvance()
void eeprom_data_readadvance (void)
TODO.
Referenced by eeprom_port_write().
eeprom_data_readbit()
uint8_t eeprom_data_readbit (void)
Referenced by eeprom_port_write().
eeprom_data_readbyte()
uint8_t eeprom_data_readbyte (void)
Todo:
FIXME: wraparound at 0x100 ?!
Referenced by eeprom_data_readbit(), and eeprom_execute_command().
eeprom_execute_command()
int eeprom_execute_command (int eeprom_mode)
Todo:
FIXME: wraparound at 0x100 ?!
Referenced by eeprom_port_write().
eeprom_open_image()
int eeprom_open_image (char * name, int rw)
eeprom_port_write()
void eeprom_port_write (uint8_t clk, uint8_t data, int ddr, int status)
eeprom_seq_reset()
void eeprom_seq_reset (void)
Referenced by eeprom_port_write().
eeprom_seq_write()
void eeprom_seq_write (uint8_t value)
Referenced by eeprom_port_write().
eeprom_snapshot_read_module()
int eeprom_snapshot_read_module (struct snapshot_s * s)
eeprom_snapshot_write_module()
int eeprom_snapshot_write_module (snapshot_t * s)
Todo:
FIXME: implement snapshot support