x128: arch/gtk3/widgets/statusbarspeedwidget.c File Reference
statusbarspeedwidget.c File Reference
CPU speed, FPS display, Pause, Warp widget for the statusbar.
#include "vice.h"
#include <gtk/gtk.h>
#include <math.h>
#include <string.h>
#include "vice_gtk3.h"
#include "basedialogs.h"
#include "drive.h"
#include "hotkeys.h"
#include "keyboard.h"
#include "lib.h"
#include "machine.h"
#include "petpia.h"
#include "resources.h"
#include "statusbarledwidget.h"
#include "uiapi.h"
#include "ui.h"
#include "uiactions.h"
#include "uimenu.h"
#include "uistatusbar.h"
#include "vsync.h"
#include "vsyncapi.h"
#include "statusbarspeedwidget.h"
Macros
#define CPU_DECIMAL_PLACES 0
CPU display decimals.
#define FPS_DECIMAL_PLACES 1
FPS display decimals.
#define STR_(x) #x
Helper macro to allow concatenating string literals.
#define STR(x) STR_(x)
Helper macro to allow concatenating string literals.
Functions
static void add_separator (GtkWidget *menu)
Add separator to menu.
static void trigger_ui_action (GtkWidget *item, gpointer action)
static GtkWidget * emulation_speed_submenu_create (void)
Create emulation speed submenu.
GtkWidget * speed_menu_popup_create (void)
Create popup menu for the statusbar speed widget.
static gboolean on_widget_clicked (GtkWidget *widget, GdkEvent *event, gpointer data)
Event handler for the mouse clicks on the speed widget.
static gboolean on_widget_hover (GtkWidget *widget, GdkEvent *event, gpointer data)
Handler for the "enter/leave" events of the event box.
GtkWidget * statusbar_speed_widget_create (statusbar_speed_widget_state_t *state)
Create widget to display CPU/FPS/pause.
void statusbar_speed_widget_update (GtkWidget *widget, statusbar_speed_widget_state_t *state, int window_identity)
Update the speed widget's display state.
Variables
static int emu_speeds [][2]
Predefined emulation speeds.
static int emu_fps_targets [][2]
Predefined emulation speed fps targets.
static GdkCursor * mouse_ptr
Reference to the alternate "hand" mouse pointer.
Detailed Description
CPU speed, FPS display, Pause, Warp widget for the statusbar.
Widget for the status bar that displays CPU speed, FPS and warp/pause state.
When primary-button-clicking on the widget a menu will pop up allowing the user to control refresh rate, emulation speed, warp and pause.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
CPU_DECIMAL_PLACES
#define CPU_DECIMAL_PLACES 0
CPU display decimals.
FPS_DECIMAL_PLACES
#define FPS_DECIMAL_PLACES 1
FPS display decimals.
STR
#define STR (x) STR_(x)
Helper macro to allow concatenating string literals.
STR_
#define STR_ (x) #x
Helper macro to allow concatenating string literals.
Function Documentation
add_separator()
static void add_separator (GtkWidget * menu) static
Add separator to menu.
Little helper function to add a separator item to a menu.
Parameters
[in,out] menu GtkMenu instance
Referenced by emulation_speed_submenu_create(), and speed_menu_popup_create().
emulation_speed_submenu_create()
static GtkWidget * emulation_speed_submenu_create (void) static
Create emulation speed submenu.
Returns
GtkMenu
Referenced by speed_menu_popup_create().
on_widget_clicked()
static gboolean on_widget_clicked (GtkWidget * widget, GdkEvent * event, gpointer data) static
Event handler for the mouse clicks on the speed widget.
Parameters
[in] widget event box around the speed label
[in] event event
[in] data extra event data (unused)
Returns
TRUE when event was handled, FALSE otherwise
Referenced by statusbar_speed_widget_create().
on_widget_hover()
static gboolean on_widget_hover (GtkWidget * widget, GdkEvent * event, gpointer data) static
Handler for the "enter/leave" events of the event box.
This changes the mouse cursor into a little "hand" when hovering over the widget, to indicate to the user they can click on the widget.
Parameters
[in] widget widget triggering the event
[in] event event triggered
[in] data extra event data (unused)
!
Todo:
refactor, code can be simplified
Returns
TRUE if the event was handled
Referenced by statusbar_speed_widget_create().
speed_menu_popup_create()
GtkWidget * speed_menu_popup_create (void)
Create popup menu for the statusbar speed widget.
Returns
GtkMenu
Referenced by on_widget_clicked().
statusbar_speed_widget_create()
GtkWidget * statusbar_speed_widget_create (statusbar_speed_widget_state_t * state)
Create widget to display CPU/FPS/pause.
Parameters
[in,out] state current widget state
Returns
GtkEventBox
Referenced by ui_statusbar_create().
statusbar_speed_widget_update()
void statusbar_speed_widget_update (GtkWidget * widget, statusbar_speed_widget_state_t * state, int window_identity)
Update the speed widget's display state.
Parameters
[in,out] widget GtkEventBox containing the CPU/FPS widgets
[in,out] state current widget state
[in] window_identity window index (primary/secondary)
Referenced by ui_update_statusbars(), and ui_update_vsid_statusbar().
trigger_ui_action()
static void trigger_ui_action (GtkWidget * item, gpointer action) static
Referenced by emulation_speed_submenu_create(), and speed_menu_popup_create().
Variable Documentation
emu_fps_targets
int emu_fps_targets[][2] static
Initial value:
= {
    { 60, ACTION_SPEED_FPS_60 },
    { 50, ACTION_SPEED_FPS_50 },
    {  0, ACTION_NONE }
}
Predefined emulation speed fps targets.
Referenced by emulation_speed_submenu_create().
emu_speeds
int emu_speeds[][2] static
Initial value:
= {
    { 200, ACTION_SPEED_CPU_200 },
    { 100, ACTION_SPEED_CPU_100 },
    {  50, ACTION_SPEED_CPU_50 },
    {  25, ACTION_SPEED_CPU_25 },
    {  10, ACTION_SPEED_CPU_10 },
    {   0, ACTION_NONE }
}
Predefined emulation speeds.
Referenced by emulation_speed_submenu_create().
mouse_ptr
GdkCursor* mouse_ptr static
Reference to the alternate "hand" mouse pointer.
!
Todo:
FIXME: Do I need to clean this up somehow? Gdk docs aren't clear at all
Referenced by on_widget_hover().