vsid: arch/gtk3/widgets/plus4memorysizewidget.h File Reference
plus4memorysizewidget.h File Reference
Plus4 memory size widget - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
GtkWidget * plus4_memory_size_widget_create (void)
Create Plus/4 memory size widget.
void plus4_memory_size_widget_add_callback (void(*cb)(GtkWidget *, int))
Set extra callback to trigger when the resource changes.
gboolean plus4_memory_size_widget_sync (void)
Synchronize the widget with its resource.
Detailed Description
Plus4 memory size widget - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
plus4_memory_size_widget_add_callback()
void plus4_memory_size_widget_add_callback (void(*)(GtkWidget *, int) callback)
Set extra callback to trigger when the resource changes.
Parameters
[in] callback function to trigger
Referenced by create_plus4_layout().
plus4_memory_size_widget_create()
GtkWidget * plus4_memory_size_widget_create (void)
Create Plus/4 memory size widget.
Returns
GtkGrid
Referenced by create_plus4_layout().
plus4_memory_size_widget_sync()
gboolean plus4_memory_size_widget_sync (void)
Synchronize the widget with its resource.
Returns
TRUE if the widget was synchronized
Referenced by machine_model_handler_plus4(), and plus4_mem_hack_callback().