vsid: monitor/mon_register6502.c File Reference
mon_register6502.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "lib.h"
#include "log.h"
#include "mon_register.h"
#include "mon_util.h"
#include "montypes.h"
#include "mos6510.h"
#include "uimon.h"
Macros
#define DBG(_x_)
#define TEST(x) ((x) != 0)
#define REG_LIST_6510_SIZE (11 + 1)
#define REG_LIST_6502_SIZE (9 + 1)
Functions
static unsigned int mon_register_get_val (int mem, int reg_id)
static void mon_register_set_val (int mem, int reg_id, uint16_t val)
assinged to mon_register_set_val() in the monitor interface struct
static void mon_register_print (int mem)
static const char * mon_register_print_ex (int mem)
static mon_reg_list_t * mon_register_list_get6502 (int mem)
void mon_register6502_init (monitor_cpu_type_t *monitor_cpu_type)
CPU specific functions.
Variables
static const mon_reg_list_t mon_reg_list_6510 [(11+1)]
static const mon_reg_list_t mon_reg_list_6502 [(9+1)]
Macro Definition Documentation
DBG
#define DBG (_x_)
REG_LIST_6502_SIZE
#define REG_LIST_6502_SIZE (9 + 1)
REG_LIST_6510_SIZE
#define REG_LIST_6510_SIZE (11 + 1)
Todo:
make the other functions here use this table. when done also do the same with the other CPUs and finally move common code to mon_register.c
TEST
#define TEST (x) ((x) != 0)
Function Documentation
mon_register6502_init()
void mon_register6502_init (monitor_cpu_type_t * monitor_cpu_type)
CPU specific functions.
Referenced by asm6502_init().
mon_register_get_val()
static unsigned int mon_register_get_val (int mem, int reg_id) static
Referenced by mon_read_snapshot(), mon_register6502_init(), mon_register_id_to_value(), mon_register_list_get6502(), mon_register_print(), mon_register_print_ex(), monitor_binary_process_undump(), monitor_binary_response_resumed(), monitor_binary_response_stopped(), monitor_binary_ui_jam_dialog(), and monitor_open().
mon_register_list_get6502()
static mon_reg_list_t * mon_register_list_get6502 (int mem) static
Todo:
try to make this a generic function, move it into mon_register.c and remove mon_register_list_get from the monitor_cpu_type_t struct
Todo:
FIXME: This is not elegant. The destinction between 6502/6510 should not be done by the memory space. This will change once we have completely separated 6502, 6509, 6510 and Z80.
Referenced by mon_register6502_init().
mon_register_print()
static void mon_register_print (int mem) static
Todo:
should use mon_register_list_get
Referenced by mon_register6502_init().
mon_register_print_ex()
static const char * mon_register_print_ex (int mem) static
Todo:
should use mon_register_list_get
Referenced by mon_register6502_init().
mon_register_set_val()
static void mon_register_set_val (int mem, int reg_id, uint16_t val) static
assinged to mon_register_set_val() in the monitor interface struct
Referenced by mon_register6502_init().
Variable Documentation
mon_reg_list_6502
const mon_reg_list_t mon_reg_list_6502[(9+1)] static
Initial value:
= {
    {      "PC",         e_PC, 16,                      0, 0, 0 },
    {       "A",          e_A,  8,                      0, 0, 0 },
    {       "X",          e_X,  8,                      0, 0, 0 },
    {       "Y",          e_Y,  8,                      0, 0, 0 },
    {      "SP",         e_SP,  8,                      0, 0, 0 },
    {      "FL",      e_FLAGS,  8,                      0, 0, 0 },
    {"NV-BDIZC",      e_FLAGS,  8,   0x01  , 0, 0 },
    {     "LIN", e_Rasterline, 16,                      0, 0, 0 },
    {     "CYC",      e_Cycle, 16,                      0, 0, 0 },
    { NULL, -1,  0,  0, 0, 0 }
}
Referenced by mon_register_list_get6502().
mon_reg_list_6510
const mon_reg_list_t mon_reg_list_6510[(11+1)] static
Initial value:
= {
    {      "PC",         e_PC, 16,                      0, 0, 0 },
    {       "A",          e_A,  8,                      0, 0, 0 },
    {       "X",          e_X,  8,                      0, 0, 0 },
    {       "Y",          e_Y,  8,                      0, 0, 0 },
    {      "SP",         e_SP,  8,                      0, 0, 0 },
    {      "00",       e_Zero,  8,  0x02  , 0, 0 },
    {      "01",        e_One,  8,  0x02  , 1, 0 },
    {      "FL",      e_FLAGS,  8,                      0, 0, 0 },
    {"NV-BDIZC",      e_FLAGS,  8,   0x01  , 0, 0 },
    {     "LIN", e_Rasterline, 16,                      0, 0, 0 },
    {     "CYC",      e_Cycle, 16,                      0, 0, 0 },
    { NULL, -1,  0,  0, 0, 0 }
}
Referenced by mon_register_list_get6502().