vsid: init.h File Reference
init.h File Reference
Functions
int init_resources (void)
int init_cmdline_options (void)
int init_main (void)
int init_main_is_done (void)
returns true once everything is initialized and the UI has started up
void init_resource_fail (const char *module)
void init_cmdline_options_fail (const char *module)
Function Documentation
init_cmdline_options()
int init_cmdline_options (void)
Referenced by main_program().
init_cmdline_options_fail()
void init_cmdline_options_fail (const char * module)
Referenced by init_cmdline_options(), machine_cmdline_options_init(), and main_program().
init_main()
int init_main (void)
Todo:
FIXME: what's about uimon_init???
Referenced by main_program().
init_main_is_done()
int init_main_is_done (void)
returns true once everything is initialized and the UI has started up
Referenced by userport_set_device().
init_resource_fail()
void init_resource_fail (const char * module)
Referenced by init_resources(), and machine_resources_init().
init_resources()
int init_resources (void)
Referenced by main_program().