vsid: printerdrv/interface-serial.h File Reference
interface-serial.h File Reference
Functions
void interface_serial_init (void)
int interface_serial_init_resources (void)
int interface_serial_init_cmdline_options (void)
void interface_serial_shutdown (void)
called by printer.serial.c:printer_serial_shutdown()
int interface_serial_late_init (void)
int interface_serial_close (unsigned int unit)
Function Documentation
interface_serial_close()
int interface_serial_close (unsigned int unit)
< 4...6
Referenced by printer_serial_close().
interface_serial_init()
void interface_serial_init (void)
Referenced by printer_serial_init().
interface_serial_init_cmdline_options()
int interface_serial_init_cmdline_options (void)
Referenced by printer_serial_init_cmdline_options().
interface_serial_init_resources()
int interface_serial_init_resources (void)
Referenced by printer_serial_init_resources().
interface_serial_late_init()
int interface_serial_late_init (void)
< 4...7
Referenced by printer_serial_late_init().
interface_serial_shutdown()
void interface_serial_shutdown (void)
called by printer.serial.c:printer_serial_shutdown()
< 4...7
Referenced by printer_serial_shutdown().