x128: drive/ieee/riot2d.c File Reference
riot2d.c File Reference
#include "vice.h"
#include <stdio.h>
#include "drive-check.h"
#include "drive.h"
#include "drivetypes.h"
#include "interrupt.h"
#include "lib.h"
#include "parallel.h"
#include "riot.h"
#include "riotd.h"
#include "types.h"
Data Structures
struct driveriot2_context_s
Typedefs
typedef struct driveriot2_context_s driveriot2_context_t
Functions
void riot2_store (diskunit_context_t *ctxptr, uint16_t addr, uint8_t data)
uint8_t riot2_read (diskunit_context_t *ctxptr, uint16_t addr)
uint8_t riot2_peek (diskunit_context_t *ctxptr, uint16_t addr)
static void set_irq (riot_context_t *riot_context, int fl, CLOCK clk)
static void restore_irq (riot_context_t *riot_context, int fl)
static void set_handshake (riot_context_t *riot_context, uint8_t pa)
void riot2_set_atn (riot_context_t *riot_context, int state)
static void undump_pra (riot_context_t *riot_context, uint8_t byte)
static void store_pra (riot_context_t *riot_context, uint8_t byte)
static void undump_prb (riot_context_t *riot_context, uint8_t byte)
static void store_prb (riot_context_t *riot_context, uint8_t byte)
static void reset (riot_context_t *riot_context)
static uint8_t read_pra (riot_context_t *riot_context)
static uint8_t read_prb (riot_context_t *riot_context)
void riot2_init (diskunit_context_t *ctxptr)
void riot2_setup_context (diskunit_context_t *ctxptr)
Typedef Documentation
driveriot2_context_t
typedef struct driveriot2_context_s driveriot2_context_t
Function Documentation
read_pra()
static uint8_t read_pra (riot_context_t * riot_context) static
Referenced by riot2_setup_context().
read_prb()
static uint8_t read_prb (riot_context_t * riot_context) static
Referenced by riot2_setup_context().
reset()
static void reset (riot_context_t * riot_context) static
Referenced by riot2_setup_context().
restore_irq()
static void restore_irq (riot_context_t * riot_context, int fl) static
Referenced by riot2_setup_context().
riot2_init()
void riot2_init (diskunit_context_t * ctxptr)
Referenced by ieee_drive_init().
riot2_peek()
uint8_t riot2_peek (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by drive_peek_1001_io().
riot2_read()
uint8_t riot2_read (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by drive_read_1001_io().
riot2_set_atn()
void riot2_set_atn (riot_context_t * riot_context, int state)
Referenced by ieee_drive_parallel_set_atn().
riot2_setup_context()
void riot2_setup_context (diskunit_context_t * ctxptr)
Referenced by ieee_drive_setup_context().
riot2_store()
void riot2_store (diskunit_context_t * ctxptr, uint16_t addr, uint8_t data)
Referenced by drive_store_1001_io().
set_handshake()
static void set_handshake (riot_context_t * riot_context, uint8_t pa) static
Referenced by reset(), riot2_set_atn(), store_pra(), and undump_pra().
set_irq()
static void set_irq (riot_context_t * riot_context, int fl, CLOCK clk) static
Referenced by riot2_setup_context().
store_pra()
static void store_pra (riot_context_t * riot_context, uint8_t byte) static
Referenced by riot2_setup_context().
store_prb()
static void store_prb (riot_context_t * riot_context, uint8_t byte) static
Referenced by riot2_setup_context().
undump_pra()
static void undump_pra (riot_context_t * riot_context, uint8_t byte) static
Referenced by riot2_setup_context().
undump_prb()
static void undump_prb (riot_context_t * riot_context, uint8_t byte) static
Referenced by riot2_setup_context().