vsid: c64/c64mem.h File Reference
c64mem.h File Reference
#include "mem.h"
#include "types.h"
Macros
#define C64_RAM_SIZE 0x10000
#define C64_KERNAL_ROM_SIZE 0x2000
#define C64_BASIC_ROM_SIZE 0x2000
#define C64_CHARGEN_ROM_SIZE 0x1000
Functions
int c64_mem_init_resources (void)
int c64_mem_init_cmdline_options (void)
void mem_set_vbank (int new_vbank)
uint8_t ram_read (uint16_t addr)
void ram_store (uint16_t addr, uint8_t value)
void ram_hi_store (uint16_t addr, uint8_t value)
uint8_t chargen_read (uint16_t addr)
void chargen_store (uint16_t addr, uint8_t value)
void colorram_store (uint16_t addr, uint8_t value)
uint8_t colorram_read (uint16_t addr)
void mem_pla_config_changed (void)
void mem_set_tape_sense (int sense)
Set the tape sense status.
void mem_set_tape_write_in (int val)
Set the tape write in.
void mem_set_tape_motor_in (int val)
Set the tape motor in.
void mem_set_write_hook (int config, int page, store_func_t *f)
void mem_read_tab_set (unsigned int base, unsigned int index, read_func_ptr_t read_func)
void mem_read_base_set (unsigned int base, unsigned int index, uint8_t *mem_ptr)
void mem_read_limit_set (unsigned int base, unsigned int index, uint32_t limit)
void mem_store_without_ultimax (uint16_t addr, uint8_t value)
uint8_t mem_read_without_ultimax (uint16_t addr)
void mem_store_without_romlh (uint16_t addr, uint8_t value)
void store_bank_io (uint16_t addr, uint8_t byte)
Banked memory access functions for the monitor.
uint8_t read_bank_io (uint16_t addr)
void c64_mem_init (void)
int c64_mem_ui_init_early (void)
UI functions (used to distinguish between x64 and x64sc)
int c64_mem_ui_init (void)
void c64_mem_ui_shutdown (void)
uint8_t vsid_io_read (uint16_t addr)
void vsid_io_store (uint16_t addr, uint8_t val)
Variables
uint8_t mem_chargen_rom [0x1000]
Macro Definition Documentation
C64_BASIC_ROM_SIZE
#define C64_BASIC_ROM_SIZE 0x2000
C64_CHARGEN_ROM_SIZE
#define C64_CHARGEN_ROM_SIZE 0x1000
C64_KERNAL_ROM_SIZE
#define C64_KERNAL_ROM_SIZE 0x2000
C64_RAM_SIZE
#define C64_RAM_SIZE 0x10000
Function Documentation
c64_mem_init()
void c64_mem_init (void)
Referenced by machine_specific_init().
c64_mem_init_cmdline_options()
int c64_mem_init_cmdline_options (void)
c64_mem_init_resources()
int c64_mem_init_resources (void)
c64_mem_ui_init()
int c64_mem_ui_init (void)
Referenced by machine_specific_init().
c64_mem_ui_init_early()
int c64_mem_ui_init_early (void)
UI functions (used to distinguish between x64 and x64sc)
Referenced by machine_specific_init().
c64_mem_ui_shutdown()
void c64_mem_ui_shutdown (void)
Referenced by machine_specific_shutdown().
chargen_read()
uint8_t chargen_read (uint16_t addr)
Referenced by c64memrom_rom64_read(), and mem_initialize_memory().
chargen_store()
void chargen_store (uint16_t addr, uint8_t value)
Referenced by c64memrom_rom64_store().
colorram_read()
uint8_t colorram_read (uint16_t addr)
Referenced by c64meminit(), peek_bank_io(), and read_bank_io().
colorram_store()
void colorram_store (uint16_t addr, uint8_t value)
Referenced by c64meminit(), and store_bank_io().
mem_pla_config_changed()
void mem_pla_config_changed (void)
Referenced by c64_snapshot_read_module(), mem_initialize_memory(), mem_set_tape_motor_in(), mem_set_tape_sense(), mem_set_tape_write_in(), and zero_store().
mem_read_base_set()
void mem_read_base_set (unsigned int base, unsigned int index, uint8_t * mem_ptr)
Referenced by c64meminit().
mem_read_limit_set()
void mem_read_limit_set (unsigned int base, unsigned int index, uint32_t limit)
Referenced by mem_limit_256k_init(), mem_limit_init(), mem_limit_max_init(), and mem_limit_plus60k_init().
mem_read_tab_set()
void mem_read_tab_set (unsigned int base, unsigned int index, read_func_ptr_t read_func)
Referenced by c64meminit().
mem_read_without_ultimax()
uint8_t mem_read_without_ultimax (uint16_t addr)
mem_set_tape_motor_in()
void mem_set_tape_motor_in (int val)
Set the tape motor in.
Referenced by machine_set_tape_motor_in().
mem_set_tape_sense()
void mem_set_tape_sense (int sense)
Set the tape sense status.
Referenced by machine_set_tape_sense().
mem_set_tape_write_in()
void mem_set_tape_write_in (int val)
Set the tape write in.
Referenced by machine_set_tape_write_in().
mem_set_vbank()
void mem_set_vbank (int new_vbank)
Referenced by c64_256k_cia_set_vbank(), c64_256k_reset(), perform_vbank_switch(), and pia_set_vbank().
mem_set_write_hook()
void mem_set_write_hook (int config, int page, store_func_t * f)
Referenced by c64meminit(), and mem_initialize_memory().
mem_store_without_romlh()
void mem_store_without_romlh (uint16_t addr, uint8_t value)
mem_store_without_ultimax()
void mem_store_without_ultimax (uint16_t addr, uint8_t value)
ram_hi_store()
void ram_hi_store (uint16_t addr, uint8_t value)
Referenced by check_256k_ram_write(), mem_initialize_memory(), plus60k_init_config(), and ram_hi_store_wrapper().
ram_read()
uint8_t ram_read (uint16_t addr)
Referenced by c64_256k_init_config(), mem_initialize_memory(), mem_read_screen(), plus256k_init_config(), plus60k_init_config(), and psid_set_cbm80().
ram_store()
void ram_store (uint16_t addr, uint8_t value)
Referenced by check_256k_ram_write(), mem_initialize_memory(), plus60k_init_config(), psid_init_driver(), psid_init_tune(), and psid_set_cbm80().
read_bank_io()
uint8_t read_bank_io (uint16_t addr)
Referenced by mem_bank_read().
store_bank_io()
void store_bank_io (uint16_t addr, uint8_t byte)
Banked memory access functions for the monitor.
Referenced by mem_bank_write(), and poke_bank_io().
vsid_io_read()
uint8_t vsid_io_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
vsid_io_store()
void vsid_io_store (uint16_t addr, uint8_t val)
Referenced by c64meminit(), and store_bank_io().
Variable Documentation
mem_chargen_rom
uint8_t mem_chargen_rom[0x1000] extern
Referenced by c64_snapshot_read_rom_module(), c64_snapshot_write_rom_module(), c64rom_load_chargen(), chargen_read(), chargen_store(), mem_bank_peek(), mem_bank_read(), mem_initialize_memory(), and mem_peek_with_config().