vsid: raster/raster-line.h File Reference
raster-line.h File Reference
Functions
unsigned int raster_line_get_real_mode (struct raster_s *raster)
void raster_line_draw_borders (struct raster_s *raster)
void raster_line_fill_xsmooth_region (struct raster_s *raster)
void raster_line_draw_blank (struct raster_s *raster, unsigned int start, unsigned int end)
void raster_line_emulate (struct raster_s *raster)
Function Documentation
raster_line_draw_blank()
void raster_line_draw_blank (struct raster_s * raster, unsigned int start, unsigned int end) inline
Referenced by handle_blank_line(), handle_blank_line_cached(), handle_visible_line_with_changes(), raster_line_draw_borders(), and update_for_minor_changes_sprite().
raster_line_draw_borders()
void raster_line_draw_borders (struct raster_s * raster)
Referenced by handle_visible_line_with_cache(), handle_visible_line_without_cache(), update_for_minor_changes(), and update_for_minor_changes_sprite().
raster_line_emulate()
void raster_line_emulate (struct raster_s * raster)
Referenced by vicii_raster_draw_alarm_handler().
raster_line_fill_xsmooth_region()
void raster_line_fill_xsmooth_region (struct raster_s * raster)
Referenced by fill_background(), and update_for_minor_changes_sprite().
raster_line_get_real_mode()
unsigned int raster_line_get_real_mode (struct raster_s * raster)
Referenced by handle_visible_line_with_cache(), handle_visible_line_with_changes(), handle_visible_line_without_cache(), update_for_minor_changes(), and update_for_minor_changes_sprite().