vsid: vicii/vicii-fetch.h File Reference
vicii-fetch.h File Reference
#include "types.h"
Functions
void vicii_fetch_init (void)
void vicii_fetch_alarm_handler (CLOCK offset, void *data)
void vicii_fetch_matrix (int offs, int num, int num_0xff, int cycle)
Function Documentation
vicii_fetch_alarm_handler()
void vicii_fetch_alarm_handler (CLOCK offset, void * data)
Referenced by vicii_fetch_init(), vicii_handle_pending_alarms(), and vicii_local_store_vbank().
vicii_fetch_init()
void vicii_fetch_init (void)
Referenced by vicii_init().
vicii_fetch_matrix()
void vicii_fetch_matrix (int offs, int num, int num_0xff, int cycle)
Todo:
FIXME: Crunch table in Multiplexer part of Krestage
Referenced by do_matrix_fetch(), and line_becomes_bad().