x128: tape/t64.h File Reference
t64.h File Reference
T64 file support.
#include <stdio.h>
#include "types.h"
Data Structures
struct t64_header_s
T64 header structure.
struct t64_file_record_s
T64 file record object.
struct t64
T64 container object.
Macros
#define T64_HDR_SIZE 64
Size of a T64 header n bytes.
#define T64_HDR_MAGIC_OFFSET 0
Offset in header of the 'magic' bytes.
#define T64_HDR_MAGIC_LEN 32
Size of the 'magic' bytes.
#define T64_HDR_VERSION_OFFSET 32
Offset in header of version number.
#define T64_HDR_VERSION_LEN 2
Size in bytes of the version number.
#define T64_HDR_NUMENTRIES_OFFSET 34
Offset in header of available file records.
#define T64_HDR_NUMENTRIES_LEN 2
Size of file record count value in bytes.
#define T64_HDR_NUMUSED_OFFSET 36
Offset in header of the number of file records in use.
#define T64_HDR_NUMUSED_LEN 2
Size in bytes of the file records in use value.
#define T64_HDR_DESCRIPTION_OFFSET 40
Offset in header of the tape description string.
#define T64_HDR_DESCRIPTION_LEN 24
Size in bytes of the tape description.
#define T64_REC_SIZE 32
Size of a single file record.
#define T64_REC_ENTRYTYPE_OFFSET 0
Offset to entry type.
#define T64_REC_ENTRYTYPE_LEN 1
Size of entry type in bytes.
#define T64_REC_CBMTYPE_OFFSET 1
Offset to C1541 file type.
#define T64_REC_CBMTYPE_LEN 1
Size of C1541 file type.
#define T64_REC_STARTADDR_OFFSET 2
Offset to start address of file data.
#define T64_REC_STARTADDR_LEN 2
Size of start address in bytes.
#define T64_REC_ENDADDR_OFFSET 4
Offset to end adress of file data.
#define T64_REC_ENDADDR_LEN 2
Size of end adress in bytes.
#define T64_REC_CONTENTS_OFFSET 8
Offset to offset in the T64 file of the file data.
#define T64_REC_CONTENTS_LEN 4
Size of the offset in the T64 to the file data.
#define T64_REC_CBMNAME_OFFSET 16
Offset to PETSCII filename.
#define T64_REC_CBMNAME_LEN 16
Size of PETSCII filename.
Typedefs
typedef struct t64_header_s t64_header_t
T64 header structure.
typedef enum t64_file_record_type_s t64_file_record_type_t
typedef struct t64_file_record_s t64_file_record_t
typedef struct t64 t64_t
Enumerations
enum t64_file_record_type_s {
T64_FILE_RECORD_FREE ,
T64_FILE_RECORD_NORMAL ,
T64_FILE_RECORD_HEADER ,
T64_FILE_RECORD_SNAPSHOT ,
T64_FILE_RECORD_BLOCK ,
T64_FILE_RECORD_STREAM
}
File record type enumerator.
Functions
t64_t * t64_open (const char *name, unsigned int *read_only)
Try to open file name as a T64 container.
int t64_close (t64_t *t64)
Close T64 container t64.
int t64_seek_start (t64_t *t64)
Move file index in t64 to the first file record.
int t64_seek_to_file (t64_t *t64, int file_number)
Move file index in t64 to file_number.
int t64_seek_to_next_file (t64_t *t64, unsigned int allow_rewind)
Move file index record in t64 to next record.
t64_file_record_t * t64_get_current_file_record (t64_t *t64)
Get pointer to current file record.
int t64_read (t64_t *t64, uint8_t *buf, size_t size)
Read size bytes of the current file record in t64 into buf.
void t64_get_header (t64_t *t64, uint8_t *name)
Copy tape description in t64 to name.
Detailed Description
T64 file support.
t64.h - T64 file support.
Written by Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Macro Definition Documentation
T64_HDR_DESCRIPTION_LEN
#define T64_HDR_DESCRIPTION_LEN 24
Size in bytes of the tape description.
T64_HDR_DESCRIPTION_OFFSET
#define T64_HDR_DESCRIPTION_OFFSET 40
Offset in header of the tape description string.
String is in PETSCII, padded with 0x20, not 0xa0, and doesn't contain a terminating nul character
T64_HDR_MAGIC_LEN
#define T64_HDR_MAGIC_LEN 32
Size of the 'magic' bytes.
T64_HDR_MAGIC_OFFSET
#define T64_HDR_MAGIC_OFFSET 0
Offset in header of the 'magic' bytes.
ASCII string padded with 0x00
T64_HDR_NUMENTRIES_LEN
#define T64_HDR_NUMENTRIES_LEN 2
Size of file record count value in bytes.
T64_HDR_NUMENTRIES_OFFSET
#define T64_HDR_NUMENTRIES_OFFSET 34
Offset in header of available file records.
This value includes file records in use. Highly unreliable.
T64_HDR_NUMUSED_LEN
#define T64_HDR_NUMUSED_LEN 2
Size in bytes of the file records in use value.
T64_HDR_NUMUSED_OFFSET
#define T64_HDR_NUMUSED_OFFSET 36
Offset in header of the number of file records in use.
Highly unreliable, values of 0 not uncommon while the T64 actually contains a single file.
T64_HDR_SIZE
#define T64_HDR_SIZE 64
Size of a T64 header n bytes.
T64_HDR_VERSION_LEN
#define T64_HDR_VERSION_LEN 2
Size in bytes of the version number.
T64_HDR_VERSION_OFFSET
#define T64_HDR_VERSION_OFFSET 32
Offset in header of version number.
T64_REC_CBMNAME_LEN
#define T64_REC_CBMNAME_LEN 16
Size of PETSCII filename.
T64_REC_CBMNAME_OFFSET
#define T64_REC_CBMNAME_OFFSET 16
Offset to PETSCII filename.
T64_REC_CBMTYPE_LEN
#define T64_REC_CBMTYPE_LEN 1
Size of C1541 file type.
T64_REC_CBMTYPE_OFFSET
#define T64_REC_CBMTYPE_OFFSET 1
Offset to C1541 file type.
T64_REC_CONTENTS_LEN
#define T64_REC_CONTENTS_LEN 4
Size of the offset in the T64 to the file data.
T64_REC_CONTENTS_OFFSET
#define T64_REC_CONTENTS_OFFSET 8
Offset to offset in the T64 file of the file data.
T64_REC_ENDADDR_LEN
#define T64_REC_ENDADDR_LEN 2
Size of end adress in bytes.
T64_REC_ENDADDR_OFFSET
#define T64_REC_ENDADDR_OFFSET 4
Offset to end adress of file data.
T64_REC_ENTRYTYPE_LEN
#define T64_REC_ENTRYTYPE_LEN 1
Size of entry type in bytes.
T64_REC_ENTRYTYPE_OFFSET
#define T64_REC_ENTRYTYPE_OFFSET 0
Offset to entry type.
T64_REC_SIZE
#define T64_REC_SIZE 32
Size of a single file record.
T64_REC_STARTADDR_LEN
#define T64_REC_STARTADDR_LEN 2
Size of start address in bytes.
T64_REC_STARTADDR_OFFSET
#define T64_REC_STARTADDR_OFFSET 2
Offset to start address of file data.
Typedef Documentation
t64_file_record_t
typedef struct t64_file_record_s t64_file_record_t
t64_file_record_type_t
typedef enum t64_file_record_type_s t64_file_record_type_t
t64_header_t
typedef struct t64_header_s t64_header_t
T64 header structure.
t64_t
typedef struct t64 t64_t
Enumeration Type Documentation
t64_file_record_type_s
enum t64_file_record_type_s
File record type enumerator.
Enumerator
T64_FILE_RECORD_FREE
unused record
T64_FILE_RECORD_NORMAL
normal record
T64_FILE_RECORD_HEADER
T64_FILE_RECORD_SNAPSHOT
C64S snapshot file.
T64_FILE_RECORD_BLOCK
T64_FILE_RECORD_STREAM
Function Documentation
t64_close()
int t64_close (t64_t * t64)
Close T64 container t64.
Parameters
[in,out] t64 T64 container
Returns
0 on success, -1 on failure
Referenced by tape_image_close().
t64_get_current_file_record()
t64_file_record_t * t64_get_current_file_record (t64_t * t64)
Get pointer to current file record.
Parameters
[in] t64 T64 container
Returns
file record on NULL on failure
Referenced by tape_find_header_trap(), tape_find_header_trap_plus4(), and tape_get_current_file_record().
t64_get_header()
void t64_get_header (t64_t * t64, uint8_t * name)
Copy tape description in t64 to name.
Copies the tape description string in t64 to name. Doesn't terminate string with nul if the string is 24 bytes.
Parameters
[in] t64 T64 container
[out] name destination for description, should be at least 24 bytes
Referenced by tape_get_header().
t64_open()
t64_t * t64_open (const char * name, unsigned int * read_only)
Try to open file name as a T64 container.
Parameters
[in] name filename/path to T64 file
[out] read_only read-only status of container
Returns
T64 container on success or NULL on failure
< read mode (binary)
Todo:
FIXME: why does this read all entries and not just the entries actually used?
Referenced by tape_image_open().
t64_read()
int t64_read (t64_t * t64, uint8_t * buf, size_t size)
Read size bytes of the current file record in t64 into buf.
Parameters
[in,out] t64 T64 container
[out] buf buffer to store file data
[in] size number of bytes to read
Returns
number of bytes read or -1 on failure
Todo:
should return long, fread(3) returns long, not int
Referenced by tape_read(), tape_receive_trap(), and tape_receive_trap_plus4().
t64_seek_start()
int t64_seek_start (t64_t * t64)
Move file index in t64 to the first file record.
Parameters
[in] t64 T64 container
Returns
0 on success, -1 on failure
Referenced by tape_seek_start().
t64_seek_to_file()
int t64_seek_to_file (t64_t * t64, int file_number)
Move file index in t64 to file_number.
Parameters
[in,out] t64 T64 container
[in] file_number index in directory of t64
Returns
0 on success, -1 on failure
Referenced by t64_seek_start(), and tape_seek_to_file().
t64_seek_to_next_file()
int t64_seek_to_next_file (t64_t * t64, unsigned int allow_rewind)
Move file index record in t64 to next record.
Moves the directory index one record forward, if no such record exists AND allow_rewind is true, move to the first record.
Parameters
[in,out] t64 T64 container
[in] allow_rewind allow rewinding the 'tape' once
Returns
0 on success, -1 on failure
Referenced by tape_find_header_trap(), tape_find_header_trap_plus4(), and tape_seek_to_next_file().