vsid: cmdline.c File Reference
cmdline.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "types.h"
#include "uicmdline.h"
#include "util.h"
Macros
#define DBG(x)
Functions
int cmdline_init (void)
static cmdline_option_ram_t * lookup_exact (const char *name)
int cmdline_register_options (const cmdline_option_t *c)
static void cmdline_free (void)
void cmdline_shutdown (void)
static cmdline_option_ram_t * lookup (const char *name, int *is_ambiguous)
int cmdline_parse (int *argc, char **argv)
void cmdline_show_help (void *userparam)
Dump command line options on stdout.
char * cmdline_options_get_name (int counter)
const char * cmdline_options_get_param (int counter)
char * cmdline_options_get_description (int counter)
char * cmdline_options_string (void)
int cmdline_get_num_options (void)
void cmdline_log_active (void)
Variables
static unsigned int num_options
static unsigned int num_allocated_options
static cmdline_option_ram_t * options
static char * combined_string = NULL
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
cmdline_free()
static void cmdline_free (void) static
Referenced by cmdline_shutdown().
cmdline_get_num_options()
int cmdline_get_num_options (void)
Referenced by create_content_widget().
cmdline_init()
int cmdline_init (void)
Referenced by init_cmdline_options().
cmdline_log_active()
void cmdline_log_active (void)
cmdline_options_get_description()
char * cmdline_options_get_description (int counter)
Referenced by cmdline_options_string(), cmdline_show_help(), and create_content_widget().
cmdline_options_get_name()
char * cmdline_options_get_name (int counter)
Referenced by create_content_widget().
cmdline_options_get_param()
const char * cmdline_options_get_param (int counter)
Referenced by cmdline_log_active(), cmdline_options_string(), cmdline_show_help(), and create_content_widget().
cmdline_options_string()
char * cmdline_options_string (void)
cmdline_parse()
int cmdline_parse (int * argc, char ** argv)
Referenced by initcmdline_check_args().
cmdline_register_options()
int cmdline_register_options (const cmdline_option_t * c)
cmdline_show_help()
void cmdline_show_help (void * userparam)
Dump command line options on stdout.
Parameters
[in] num_options number of options
[in] options list of options
[in] userparm ignored for some reason
XXX: this function and its brethren where all over archdep, while basically doing the same thing.
On Windows it seems we need to use x64 -help|more to make the list appear on the console. (thanks Greg)
Once this works, we can remove a lot of 'uicmdline.c' files from various src/arch/$arch directories. – compyx, 2017-08-12
Referenced by cmdline_help().
cmdline_shutdown()
void cmdline_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
lookup()
static cmdline_option_ram_t * lookup (const char * name, int * is_ambiguous) static
Referenced by cmdline_parse().
lookup_exact()
static cmdline_option_ram_t * lookup_exact (const char * name) static
Referenced by cmdline_register_options().
Variable Documentation
combined_string
char* combined_string = NULL static
Referenced by cmdline_free(), and cmdline_options_get_description().
num_allocated_options
unsigned int num_allocated_options static
Referenced by cmdline_init(), and cmdline_register_options().
num_options
unsigned int num_options static
Referenced by cmdline_free(), cmdline_get_num_options(), cmdline_init(), cmdline_log_active(), cmdline_options_string(), cmdline_register_options(), cmdline_show_help(), cmdline_shutdown(), create_content_widget(), lookup(), and lookup_exact().
options
cmdline_option_ram_t* options static
Referenced by cmdline_free(), cmdline_init(), cmdline_log_active(), cmdline_options_get_description(), cmdline_options_get_name(), cmdline_options_get_param(), cmdline_options_string(), cmdline_register_options(), cmdline_show_help(), cmdline_shutdown(), lookup(), and lookup_exact().