vsid: drive/drive.h File Reference
drive.h File Reference
#include "types.h"
#include "ds1216e.h"
#include "p64.h"
#include "drivetypes.h"
Data Structures
struct drive_type_info_s
struct drive_s
Macros
#define NUM_DISK_UNITS 4
Number of supported disk units.
#define DRIVE_UNIT_MIN 8
Minimum drive unit number.
#define DRIVE_UNIT_MAX (DRIVE_UNIT_MIN + NUM_DISK_UNITS - 1)
Maximum drive unit number.
#define DRIVE_UNIT_DEFAULT DRIVE_UNIT_MIN
Default drive unit number.
#define DRIVE_NUMBER_MIN 0
Minimum drive number.
#define DRIVE_NUMBER_MAX 1
Maximum drive number.
#define NUM_DRIVES 2
#define DRIVE_NUMBER_DEFAULT DRIVE_NUMBER_MIN
Default drive number.
#define MAX_PWM 1000
#define DRIVE_ROM_SIZE 0x8000
#define DRIVE_RAM_SIZE 0x10000
Upped to 64K due to CMD HD.
#define DRIVE_EXTEND_NEVER 0
Extended disk image handling.
#define DRIVE_EXTEND_ASK 1
#define DRIVE_EXTEND_ACCESS 2
#define DRIVE_IDLE_NO_IDLE 0
Drive idling methods.
#define DRIVE_IDLE_SKIP_CYCLES 1
#define DRIVE_IDLE_TRAP_IDLE 2
#define DRIVE_TYPE_NONE 0
#define DRIVE_NAME_NONE "None"
#define DRIVE_TYPE_ANY 9999
#define DRIVE_NAME_ANY "Any"
#define DRIVE_TYPE_1540 1540
#define DRIVE_NAME_1540 "CBM 1540"
#define DRIVE_TYPE_1541 1541
#define DRIVE_NAME_1541 "CBM 1541"
#define DRIVE_TYPE_1541II 1542
#define DRIVE_NAME_1541II "CBM 1541-II"
#define DRIVE_TYPE_1551 1551
#define DRIVE_NAME_1551 "CBM 1551"
#define DRIVE_TYPE_1570 1570
#define DRIVE_NAME_1570 "CBM 1570"
#define DRIVE_TYPE_1571 1571
#define DRIVE_NAME_1571 "CBM 1571"
#define DRIVE_TYPE_1571CR 1573
#define DRIVE_NAME_1571CR "CBM 1571 CR"
#define DRIVE_TYPE_1581 1581
#define DRIVE_NAME_1581 "CBM 1581"
#define DRIVE_TYPE_2000 2000
#define DRIVE_NAME_2000 "CMD FD-2000"
#define DRIVE_TYPE_4000 4000
#define DRIVE_NAME_4000 "CMD FD-4000"
#define DRIVE_TYPE_2031 2031
#define DRIVE_NAME_2031 "CBM 2031"
#define DRIVE_TYPE_2040 2040
DOS 1 dual floppy drive, 170k/disk.
#define DRIVE_NAME_2040 "CBM 2040"
#define DRIVE_TYPE_3040 3040
DOS 2.0 dual floppy drive, 170k/disk.
#define DRIVE_NAME_3040 "CBM 3040"
#define DRIVE_TYPE_4040 4040
DOS 2.5 dual floppy drive, 170k/disk.
#define DRIVE_NAME_4040 "CBM 4040"
#define DRIVE_TYPE_1001 1001
DOS 2.7 single floppy drive, 1M/disk.
#define DRIVE_NAME_1001 "CBM SFD-1001"
#define DRIVE_TYPE_8050 8050
DOS 2.7 dual floppy drive, 0.5M/disk.
#define DRIVE_NAME_8050 "CBM 8050"
#define DRIVE_TYPE_8250 8250
DOS 2.7 dual floppy drive, 1M/disk.
#define DRIVE_NAME_8250 "CBM 8250"
#define DRIVE_TYPE_9000 9000
DOS 3.0 hard drive.
#define DRIVE_NAME_9000 "CBM D9090/60"
#define DRIVE_TYPE_CMDHD 4844
ASCII for HD.
#define DRIVE_NAME_CMDHD "CMD HD"
#define DRIVE_TYPE_NUM 19
#define DRIVE_HALFTRACKS_1541 84
max.
#define DRIVE_HALFTRACKS_1571 84
#define DRIVE_LED1_RED 0
Possible colors of the drive active LED.
#define DRIVE_LED1_GREEN 1
#define DRIVE_LED2_RED 0
#define DRIVE_LED2_GREEN 2
#define DRIVE_LEDS_MAX 2
maximum number of LEDs per drive (not unit!)
#define DRIVE_BUTTON_WRITE_PROTECT 0x01
Drive has write protect button.
#define DRIVE_BUTTON_SWAP_8 0x02
Drive has SWAP 8 button.
#define DRIVE_BUTTON_SWAP_9 0x04
Drive has SWAP 9 button.
#define DRIVE_BUTTON_SWAP_SINGLE 0x08
Drive has single SWAP button.
#define DRIVE_ATTACH_DELAY (3 * 600000)
#define DRIVE_DETACH_DELAY (3 * 200000)
Number of cycles the write protection is activated on detach.
#define DRIVE_ATTACH_DETACH_DELAY (3 * 400000)
#define DRIVE_PC_NONE 0
Parallel cables available.
#define DRIVE_PC_STANDARD 1
speed-dos userport cable
#define DRIVE_PC_DD3 2
dolphin-dos 3 userport cable
#define DRIVE_PC_FORMEL64 3
formel 64 cartridge
#define DRIVE_PC_21SEC_BACKUP 4
21 second backup userport cable
#define DRIVE_PC_NUM 5
#define DRIVE_RPM_ONE 100
1 RPM
#define DRIVE_RPM_MAX 32000
320 RPM
#define DRIVE_RPM_DEFAULT 30000
300 RPM
#define DRIVE_WOBBLE_FREQ_ONE 1000
1 Hz
#define DRIVE_WOBBLE_FREQ_MAX 50000
50 Hz
#define DRIVE_WOBBLE_FREQ_DEFAULT 75
.075 Hz
#define DRIVE_WOBBLE_AMPLITUDE_ONE 1000
+/- 1 RPM
#define DRIVE_WOBBLE_AMPLITUDE_MAX 5000
+/- 5 RPM
#define DRIVE_WOBBLE_AMPLITUDE_DEFAULT 200
+/- 0.2 RPM
#define DRIVE_SOUND_VOLUME_ONE 4000
100%
#define DRIVE_SOUND_VOLUME_MAX 4000
100%
#define DRIVE_SOUND_VOLUME_DEFAULT 1000
25%
#define BRA_BYTE_READY 0x02
chosen for the bit in the VIA2 PCR register
#define BRA_MOTOR_ON 0x04
chosen for the bit in the VIA2 PB register
#define BRA_LED 0x08
Typedefs
typedef struct drive_type_info_s drive_type_info_t
typedef struct drive_s drive_t
Functions
int drive_init (void)
int drive_enable (struct diskunit_context_s *drv)
Activate full drive emulation.
void drive_disable (struct diskunit_context_s *drv)
Disable full drive emulation.
void drive_move_head (int step, struct drive_s *drive)
struct monitor_interface_s * drive_cpu_monitor_interface_get (unsigned int dnr)
Don't use these pointers before the context is set up!
void drive_cpu_early_init_all (void)
void drive_cpu_trigger_reset (unsigned int dnr)
reset one drive only
void drive_reset (void)
called by machine_specific_reset()
void drive_shutdown (void)
void drive_cpu_execute_one (struct diskunit_context_s *drv, CLOCK clk_value)
void drive_cpu_execute_all (CLOCK clk_value)
void drive_cpu_set_overflow (struct diskunit_context_s *drv)
void drive_vsync_hook (void)
This is called at every vsync.
int drive_get_disk_drive_type (int dnr)
void drive_enable_update_ui (struct diskunit_context_s *drv)
void drive_update_ui_status (void)
Update the status bar in the UI.
void drive_gcr_data_writeback (struct drive_s *drive)
void drive_gcr_data_writeback_all (void)
void drive_set_active_led_color (unsigned int type, unsigned int dnr)
int drive_set_disk_drive_type (unsigned int drive_type, struct diskunit_context_s *drv)
void drive_set_half_track (int num, int side, drive_t *dptr)
Move the head to half track ‘num’.
void drive_set_machine_parameter (long cycles_per_sec)
void drive_set_disk_memory (uint8_t *id, unsigned int track, unsigned int sector, struct diskunit_context_s *drv)
void drive_set_last_read (unsigned int track, unsigned int sector, uint8_t *buffer, struct diskunit_context_s *drv)
int drive_check_type (unsigned int drive_type, unsigned int dnr)
int drive_check_extend_policy (int drive_type)
int drive_check_idle_method (int drive_type)
int drive_check_expansion (int drive_type)
int drive_check_expansion2000 (int drive_type)
int drive_check_expansion4000 (int drive_type)
int drive_check_expansion6000 (int drive_type)
int drive_check_expansion8000 (int drive_type)
int drive_check_expansionA000 (int drive_type)
int drive_check_parallel_cable (int drive_type)
int drive_check_profdos (int drive_type)
int drive_check_supercard (int drive_type)
int drive_check_stardos (int drive_type)
int drive_check_rtc (int drive_type)
Check if drive_type supports a real-time clock.
int drive_check_iec (int drive_type)
int drive_num_leds (unsigned int dnr)
int drive_get_type_by_devnr (int devnr)
int drive_is_dualdrive_by_devnr (int devnr)
void drive_setup_context (void)
int drive_resources_type_init (unsigned int default_type)
int drive_has_buttons (unsigned int dnr)
void drive_cpu_trigger_reset_button (unsigned int dnr, unsigned int button)
unsigned int drive_jam (int mynumber, const char *format,...)
bool drive_is_jammed (int mynumber)
char * drive_jam_reason (int mynumber)
Variables
CLOCK diskunit_clk [4]
Global clock counters.
struct diskunit_context_s * diskunit_context [4]
int rom_loaded
If nonzero, at least one vaild drive ROM has already been loaded.
Macro Definition Documentation
BRA_BYTE_READY
#define BRA_BYTE_READY 0x02
chosen for the bit in the VIA2 PCR register
BRA_LED
#define BRA_LED 0x08
BRA_MOTOR_ON
#define BRA_MOTOR_ON 0x04
chosen for the bit in the VIA2 PB register
DRIVE_ATTACH_DELAY
#define DRIVE_ATTACH_DELAY (3 * 600000)
DRIVE_ATTACH_DETACH_DELAY
#define DRIVE_ATTACH_DETACH_DELAY (3 * 400000)
DRIVE_BUTTON_SWAP_8
#define DRIVE_BUTTON_SWAP_8 0x02
Drive has SWAP 8 button.
DRIVE_BUTTON_SWAP_9
#define DRIVE_BUTTON_SWAP_9 0x04
Drive has SWAP 9 button.
DRIVE_BUTTON_SWAP_SINGLE
#define DRIVE_BUTTON_SWAP_SINGLE 0x08
Drive has single SWAP button.
DRIVE_BUTTON_WRITE_PROTECT
#define DRIVE_BUTTON_WRITE_PROTECT 0x01
Drive has write protect button.
DRIVE_DETACH_DELAY
#define DRIVE_DETACH_DELAY (3 * 200000)
Number of cycles the write protection is activated on detach.
DRIVE_EXTEND_ACCESS
#define DRIVE_EXTEND_ACCESS 2
DRIVE_EXTEND_ASK
#define DRIVE_EXTEND_ASK 1
DRIVE_EXTEND_NEVER
#define DRIVE_EXTEND_NEVER 0
Extended disk image handling.
DRIVE_HALFTRACKS_1541
#define DRIVE_HALFTRACKS_1541 84
max.
half tracks
DRIVE_HALFTRACKS_1571
#define DRIVE_HALFTRACKS_1571 84
Todo:
FIXME: this constant is at some places used unconditionally for all 2-sided drives
DRIVE_IDLE_NO_IDLE
#define DRIVE_IDLE_NO_IDLE 0
Drive idling methods.
DRIVE_IDLE_SKIP_CYCLES
#define DRIVE_IDLE_SKIP_CYCLES 1
DRIVE_IDLE_TRAP_IDLE
#define DRIVE_IDLE_TRAP_IDLE 2
DRIVE_LED1_GREEN
#define DRIVE_LED1_GREEN 1
DRIVE_LED1_RED
#define DRIVE_LED1_RED 0
Possible colors of the drive active LED.
DRIVE_LED2_GREEN
#define DRIVE_LED2_GREEN 2
DRIVE_LED2_RED
#define DRIVE_LED2_RED 0
DRIVE_LEDS_MAX
#define DRIVE_LEDS_MAX 2
maximum number of LEDs per drive (not unit!)
DRIVE_NAME_1001
#define DRIVE_NAME_1001 "CBM SFD-1001"
DRIVE_NAME_1540
#define DRIVE_NAME_1540 "CBM 1540"
DRIVE_NAME_1541
#define DRIVE_NAME_1541 "CBM 1541"
DRIVE_NAME_1541II
#define DRIVE_NAME_1541II "CBM 1541-II"
DRIVE_NAME_1551
#define DRIVE_NAME_1551 "CBM 1551"
DRIVE_NAME_1570
#define DRIVE_NAME_1570 "CBM 1570"
DRIVE_NAME_1571
#define DRIVE_NAME_1571 "CBM 1571"
DRIVE_NAME_1571CR
#define DRIVE_NAME_1571CR "CBM 1571 CR"
DRIVE_NAME_1581
#define DRIVE_NAME_1581 "CBM 1581"
DRIVE_NAME_2000
#define DRIVE_NAME_2000 "CMD FD-2000"
DRIVE_NAME_2031
#define DRIVE_NAME_2031 "CBM 2031"
DRIVE_NAME_2040
#define DRIVE_NAME_2040 "CBM 2040"
DRIVE_NAME_3040
#define DRIVE_NAME_3040 "CBM 3040"
DRIVE_NAME_4000
#define DRIVE_NAME_4000 "CMD FD-4000"
DRIVE_NAME_4040
#define DRIVE_NAME_4040 "CBM 4040"
DRIVE_NAME_8050
#define DRIVE_NAME_8050 "CBM 8050"
DRIVE_NAME_8250
#define DRIVE_NAME_8250 "CBM 8250"
DRIVE_NAME_9000
#define DRIVE_NAME_9000 "CBM D9090/60"
DRIVE_NAME_ANY
#define DRIVE_NAME_ANY "Any"
DRIVE_NAME_CMDHD
#define DRIVE_NAME_CMDHD "CMD HD"
DRIVE_NAME_NONE
#define DRIVE_NAME_NONE "None"
DRIVE_NUMBER_DEFAULT
#define DRIVE_NUMBER_DEFAULT DRIVE_NUMBER_MIN
Default drive number.
DRIVE_NUMBER_MAX
#define DRIVE_NUMBER_MAX 1
Maximum drive number.
DRIVE_NUMBER_MIN
#define DRIVE_NUMBER_MIN 0
Minimum drive number.
DRIVE_PC_21SEC_BACKUP
#define DRIVE_PC_21SEC_BACKUP 4
21 second backup userport cable
DRIVE_PC_DD3
#define DRIVE_PC_DD3 2
dolphin-dos 3 userport cable
DRIVE_PC_FORMEL64
#define DRIVE_PC_FORMEL64 3
formel 64 cartridge
DRIVE_PC_NONE
#define DRIVE_PC_NONE 0
Parallel cables available.
DRIVE_PC_NUM
#define DRIVE_PC_NUM 5
DRIVE_PC_STANDARD
#define DRIVE_PC_STANDARD 1
speed-dos userport cable
DRIVE_RAM_SIZE
#define DRIVE_RAM_SIZE 0x10000
Upped to 64K due to CMD HD.
DRIVE_ROM_SIZE
#define DRIVE_ROM_SIZE 0x8000
DRIVE_RPM_DEFAULT
#define DRIVE_RPM_DEFAULT 30000
300 RPM
DRIVE_RPM_MAX
#define DRIVE_RPM_MAX 32000
320 RPM
DRIVE_RPM_ONE
#define DRIVE_RPM_ONE 100
1 RPM
DRIVE_SOUND_VOLUME_DEFAULT
#define DRIVE_SOUND_VOLUME_DEFAULT 1000
25%
DRIVE_SOUND_VOLUME_MAX
#define DRIVE_SOUND_VOLUME_MAX 4000
100%
DRIVE_SOUND_VOLUME_ONE
#define DRIVE_SOUND_VOLUME_ONE 4000
100%
DRIVE_TYPE_1001
#define DRIVE_TYPE_1001 1001
DOS 2.7 single floppy drive, 1M/disk.
DRIVE_TYPE_1540
#define DRIVE_TYPE_1540 1540
DRIVE_TYPE_1541
#define DRIVE_TYPE_1541 1541
DRIVE_TYPE_1541II
#define DRIVE_TYPE_1541II 1542
DRIVE_TYPE_1551
#define DRIVE_TYPE_1551 1551
DRIVE_TYPE_1570
#define DRIVE_TYPE_1570 1570
DRIVE_TYPE_1571
#define DRIVE_TYPE_1571 1571
DRIVE_TYPE_1571CR
#define DRIVE_TYPE_1571CR 1573
DRIVE_TYPE_1581
#define DRIVE_TYPE_1581 1581
DRIVE_TYPE_2000
#define DRIVE_TYPE_2000 2000
DRIVE_TYPE_2031
#define DRIVE_TYPE_2031 2031
DRIVE_TYPE_2040
#define DRIVE_TYPE_2040 2040
DOS 1 dual floppy drive, 170k/disk.
DRIVE_TYPE_3040
#define DRIVE_TYPE_3040 3040
DOS 2.0 dual floppy drive, 170k/disk.
DRIVE_TYPE_4000
#define DRIVE_TYPE_4000 4000
DRIVE_TYPE_4040
#define DRIVE_TYPE_4040 4040
DOS 2.5 dual floppy drive, 170k/disk.
DRIVE_TYPE_8050
#define DRIVE_TYPE_8050 8050
DOS 2.7 dual floppy drive, 0.5M/disk.
DRIVE_TYPE_8250
#define DRIVE_TYPE_8250 8250
DOS 2.7 dual floppy drive, 1M/disk.
DRIVE_TYPE_9000
#define DRIVE_TYPE_9000 9000
DOS 3.0 hard drive.
DRIVE_TYPE_ANY
#define DRIVE_TYPE_ANY 9999
DRIVE_TYPE_CMDHD
#define DRIVE_TYPE_CMDHD 4844
ASCII for HD.
DRIVE_TYPE_NONE
#define DRIVE_TYPE_NONE 0
DRIVE_TYPE_NUM
#define DRIVE_TYPE_NUM 19
DRIVE_UNIT_DEFAULT
#define DRIVE_UNIT_DEFAULT DRIVE_UNIT_MIN
Default drive unit number.
DRIVE_UNIT_MAX
#define DRIVE_UNIT_MAX (DRIVE_UNIT_MIN + NUM_DISK_UNITS - 1)
Maximum drive unit number.
DRIVE_UNIT_MIN
#define DRIVE_UNIT_MIN 8
Minimum drive unit number.
DRIVE_WOBBLE_AMPLITUDE_DEFAULT
#define DRIVE_WOBBLE_AMPLITUDE_DEFAULT 200
+/- 0.2 RPM
DRIVE_WOBBLE_AMPLITUDE_MAX
#define DRIVE_WOBBLE_AMPLITUDE_MAX 5000
+/- 5 RPM
DRIVE_WOBBLE_AMPLITUDE_ONE
#define DRIVE_WOBBLE_AMPLITUDE_ONE 1000
+/- 1 RPM
DRIVE_WOBBLE_FREQ_DEFAULT
#define DRIVE_WOBBLE_FREQ_DEFAULT 75
.075 Hz
DRIVE_WOBBLE_FREQ_MAX
#define DRIVE_WOBBLE_FREQ_MAX 50000
50 Hz
DRIVE_WOBBLE_FREQ_ONE
#define DRIVE_WOBBLE_FREQ_ONE 1000
1 Hz
MAX_PWM
#define MAX_PWM 1000
NUM_DISK_UNITS
#define NUM_DISK_UNITS 4
Number of supported disk units.
NUM_DRIVES
#define NUM_DRIVES 2
Typedef Documentation
drive_t
typedef struct drive_s drive_t
drive_type_info_t
typedef struct drive_type_info_s drive_type_info_t
Function Documentation
drive_check_expansion()
int drive_check_expansion (int drive_type)
drive_check_expansion2000()
int drive_check_expansion2000 (int drive_type)
drive_check_expansion4000()
int drive_check_expansion4000 (int drive_type)
drive_check_expansion6000()
int drive_check_expansion6000 (int drive_type)
drive_check_expansion8000()
int drive_check_expansion8000 (int drive_type)
drive_check_expansionA000()
int drive_check_expansionA000 (int drive_type)
drive_check_extend_policy()
int drive_check_extend_policy (int drive_type)
Todo:
FIXME: will be always extended
Todo:
FIXME: will be always extended
Todo:
FIXME: will be always extended
Todo:
FIXME: will be always extended
Referenced by drive_extend_policy_widget_update(), and on_model_changed().
drive_check_idle_method()
int drive_check_idle_method (int drive_type)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
Referenced by on_model_changed().
drive_check_iec()
int drive_check_iec (int drive_type)
< ASCII for HD
Referenced by drive_check_bus().
drive_check_parallel_cable()
int drive_check_parallel_cable (int drive_type)
Referenced by drive_parallel_cable_widget_update(), and on_model_changed().
drive_check_profdos()
int drive_check_profdos (int drive_type)
drive_check_rtc()
int drive_check_rtc (int drive_type)
Check if drive_type supports a real-time clock.
Parameters
[in] drive_type drive type
Returns
bool
< ASCII for HD
Referenced by create_rtc_check_button(), and on_model_changed().
drive_check_stardos()
int drive_check_stardos (int drive_type)
Todo:
FIXME: stardos apparently exists for 157x, needs more research
drive_check_supercard()
int drive_check_supercard (int drive_type)
drive_check_type()
int drive_check_type (unsigned int drive_type, unsigned int dnr)
Referenced by create_combo_model(), drive_init(), and drive_model_widget_update().
drive_cpu_early_init_all()
void drive_cpu_early_init_all (void)
Referenced by init_main().
drive_cpu_execute_all()
void drive_cpu_execute_all (CLOCK clk_value)
Referenced by c64_snapshot_write(), iecbus_cpu_read_conf1(), iecbus_cpu_read_conf2(), iecbus_cpu_read_conf3(), iecbus_cpu_write_conf3(), monitor_binary_process_command(), read_ciaicr(), and read_sdr().
drive_cpu_execute_one()
void drive_cpu_execute_one (struct diskunit_context_s * drv, CLOCK clk_value)
< ASCII for HD
Referenced by c64fastiec_fast_cpu_write(), drive_cpu_execute_all(), drive_vsync_hook(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), and parallel_cable_cpu_execute().
drive_cpu_monitor_interface_get()
struct monitor_interface_s * drive_cpu_monitor_interface_get (unsigned int dnr)
Don't use these pointers before the context is set up!
Referenced by c64_monitor_init().
drive_cpu_set_overflow()
void drive_cpu_set_overflow (struct diskunit_context_s * drv)
< ASCII for HD
drive_cpu_trigger_reset()
void drive_cpu_trigger_reset (unsigned int dnr)
reset one drive only
< ASCII for HD
Referenced by autostart_disk(), autostart_prg(), cmdhd_attach_image(), drive_cpu_trigger_reset_button(), drive_reset(), driverom_load(), mon_reset_machine(), and reset_drive_action().
drive_cpu_trigger_reset_button()
void drive_cpu_trigger_reset_button (unsigned int dnr, unsigned int button)
Referenced by on_drive_reset_config_clicked().
drive_disable()
void drive_disable (diskunit_context_t * drv)
Disable full drive emulation.
< ASCII for HD
Referenced by drive_resources_type(), drive_snapshot_read_module(), driverom_load(), and set_drive_true_emulation().
drive_enable()
int drive_enable (struct diskunit_context_s * drv)
Activate full drive emulation.
< ASCII for HD
Referenced by drive_init(), drive_resources_type(), drive_snapshot_read_module(), and set_drive_true_emulation().
drive_enable_update_ui()
void drive_enable_update_ui (struct diskunit_context_s * drv)
Todo:
drive 1
Referenced by drive_disable(), drive_enable(), and drive_resources_type().
drive_gcr_data_writeback()
void drive_gcr_data_writeback (struct drive_s * drive)
Todo:
FIXME: why would the offset be different for D71 and G71?
Todo:
FIXME: doublesided images cant be extended with this logic, so never do it
Referenced by drive_disable(), drive_gcr_data_writeback_all(), drive_image_detach(), drive_move_head(), drive_set_last_read(), and glue1571_side_set().
drive_gcr_data_writeback_all()
void drive_gcr_data_writeback_all (void)
Referenced by drive_snapshot_read_module(), drive_snapshot_write_module(), and machine_drive_flush().
drive_get_disk_drive_type()
int drive_get_disk_drive_type (int dnr)
Referenced by autostart_prg_with_disk_image(), and fsimage_read_dxx_image().
drive_get_type_by_devnr()
int drive_get_type_by_devnr (int devnr)
Todo:
FIXME: xvic has its own IEC code and doesn't use "IECDevice[8-11]"
Referenced by drive_is_dualdrive_by_devnr().
drive_has_buttons()
int drive_has_buttons (unsigned int dnr)
< ASCII for HD
Referenced by ui_do_drive_popup().
drive_init()
int drive_init (void)
Todo:
rotation code is not drive1 aware
< ASCII for HD
Referenced by machine_specific_init().
drive_is_dualdrive_by_devnr()
int drive_is_dualdrive_by_devnr (int devnr)
Referenced by advance_hasdisk(), create_extra_widget(), dir_menu_popup_create(), drive_snapshot_write_module(), on_unit_changed(), and ui_do_drive_popup().
drive_is_jammed()
bool drive_is_jammed (int mynumber)
Referenced by statusbar_speed_widget_update().
drive_jam()
unsigned int drive_jam (int mynumber, const char * format, ...)
Todo:
FIXME: perhaps we want a seperate setting for drives?
Referenced by drivecpu_jam().
drive_jam_reason()
char * drive_jam_reason (int mynumber)
Referenced by statusbar_speed_widget_update().
drive_move_head()
void drive_move_head (int step, struct drive_s * drive)
drive_num_leds()
int drive_num_leds (unsigned int dnr)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
< ASCII for HD
drive_reset()
void drive_reset (void)
called by machine_specific_reset()
reset all drives
Referenced by machine_specific_reset().
drive_resources_type_init()
int drive_resources_type_init (unsigned int default_type)
Referenced by machine_drive_resources_init().
drive_set_active_led_color()
void drive_set_active_led_color (unsigned int type, unsigned int dnr)
< ASCII for HD
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 3.0 hard drive
< DOS 2.7 dual floppy drive, 1M/disk
Referenced by drive_init(), drive_set_disk_drive_type(), and drive_snapshot_read_module().
drive_set_disk_drive_type()
int drive_set_disk_drive_type (unsigned int drive_type, struct diskunit_context_s * drv)
Todo:
drive 1?
< ASCII for HD
< ASCII for HD
Referenced by drive_resources_type().
drive_set_disk_memory()
void drive_set_disk_memory (uint8_t * id, unsigned int track, unsigned int sector, struct diskunit_context_s * drv)
Referenced by disk_eof_callback().
drive_set_half_track()
void drive_set_half_track (int num, int side, drive_t * dptr)
Move the head to half track ‘num’.
Todo:
FIXME: why would the offset be different for D71 and G71?
Referenced by drive_image_attach(), drive_image_detach(), drive_init(), drive_move_head(), drive_set_last_read(), drive_snapshot_read_module(), and glue1571_side_set().
drive_set_last_read()
void drive_set_last_read (unsigned int track, unsigned int sector, uint8_t * buffer, struct diskunit_context_s * drv)
Todo:
drive 1 ?
Todo:
drive 1 ?
Referenced by disk_eof_callback().
drive_set_machine_parameter()
void drive_set_machine_parameter (long cycles_per_sec)
Referenced by machine_change_timing().
drive_setup_context()
void drive_setup_context (void)
Referenced by main_program().
drive_shutdown()
void drive_shutdown (void)
< ASCII for HD
Referenced by cmdline_help(), and machine_shutdown().
drive_update_ui_status()
void drive_update_ui_status (void)
Update the status bar in the UI.
Referenced by drive_snapshot_read_module(), and drive_vsync_hook().
drive_vsync_hook()
void drive_vsync_hook (void)
This is called at every vsync.
Todo:
drive 1
Referenced by machine_vsync_hook().
Variable Documentation
diskunit_clk
CLOCK diskunit_clk[4] extern
Global clock counters.
Referenced by drive_image_attach(), drive_image_detach(), drive_init(), drive_setup_context_for_unit(), drivecpu65c02_setup_context(), drivecpu65c02_trigger_reset(), drivecpu_setup_context(), and drivecpu_trigger_reset().
diskunit_context
struct diskunit_context_s* diskunit_context[4] extern
Referenced by c64fastiec_fast_cpu_write(), cmdbus_update(), cmdhd_attach_image(), cmdhd_detach_image(), cmdhd_init(), cmdhd_patn_changed(), cmdhd_update_maxsize(), disk_eof_callback(), drive_check_image_format(), drive_cpu_early_init_all(), drive_cpu_execute_all(), drive_cpu_monitor_interface_get(), drive_cpu_trigger_reset(), drive_cpu_trigger_reset_button(), drive_enable_update_ui(), drive_gcr_data_writeback_all(), drive_get_disk_drive_type(), drive_has_buttons(), drive_image_attach(), drive_image_detach(), drive_init(), drive_num_leds(), drive_resources_init(), drive_resources_type(), drive_resources_type_init(), drive_set_machine_parameter(), drive_setup_context(), drive_shutdown(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), drive_snapshot_write_gcrimage_module(), drive_snapshot_write_image_module(), drive_snapshot_write_module(), drive_snapshot_write_p64image_module(), drive_update_ui_status(), drive_vsync_hook(), driverom_load(), iec_drive_rom_do_checksum(), iec_drive_rom_setup_image(), iec_resources_init(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), iecbus_cpu_write_conf3(), layout_statusbar_drives(), parallel_atn_signal(), parallel_cable_cpu_execute(), parallel_cable_cpu_pulse(), parallel_cable_value(), parallel_trap_attention(), parallel_trap_receivebyte(), parallel_trap_sendbyte(), parallelcommand(), pc8477_attach_image(), pc8477_detach_image(), rotation_table_get(), rotation_table_set(), set_drive_extend_image_policy(), set_drive_fixed(), set_drive_idling_method(), set_drive_ram(), set_drive_ram2(), set_drive_ram4(), set_drive_ram6(), set_drive_ram8(), set_drive_rama(), set_drive_rpm(), set_drive_rtc_save(), set_drive_true_emulation(), set_drive_wobble_amplitude(), set_drive_wobble_frequency(), wd1770_attach_image(), and wd1770_detach_image().
rom_loaded
int rom_loaded extern
If nonzero, at least one vaild drive ROM has already been loaded.
Referenced by drive_disable(), drive_enable(), drive_init(), drivesync_set_1571(), drivesync_set_4000(), iecrom_check_loaded(), iecrom_setup_image(), and set_drive_idling_method().