vsid: monitor/montypes.h File Reference
montypes.h File Reference
#include <stdbool.h>
#include "monitor.h"
#include "types.h"
Data Structures
struct cond_node_s
Macros
#define TRUE 1
Defines.
#define FALSE 0
#define HI16(x) ((x) & 0xffff0000)
#define LO16(x) ((x) & 0xffff)
#define LO16_TO_HI16(x) (((x) & 0xffff) << 16)
#define HI16_TO_LO16(x) (((x) >> 16) & 0xffff)
#define STATE_INITIAL 0
#define STATE_FNAME 1
#define STATE_REG_ASGN 2
#define STATE_ROL 3
#define STATE_BNAME 4
#define STATE_CTYPE 5
#define DEFAULT_DISASSEMBLY_SIZE 40
#define any_watchpoints_load(mem) (watchpoints_load[(mem)] != NULL)
#define any_watchpoints_store(mem) (watchpoints_store[(mem)] != NULL)
#define new_cond ((cond_node_t *)(lib_malloc(sizeof(cond_node_t))))
#define addr_memspace(ma) (HI16_TO_LO16(ma))
#define addr_location(ma) (LO16(ma))
#define addr_mask(l) (LO16(l))
#define new_addr(m, l) (LO16_TO_HI16(m) | (l))
#define new_reg(m, r) (LO16_TO_HI16(m) | (r))
#define reg_memspace(mr) (HI16_TO_LO16(mr))
#define reg_regid(mr) (LO16(mr))
Typedefs
typedef enum t_reg_id REG_ID
typedef enum t_memory_op MEMORY_OP
typedef unsigned int MON_ADDR
typedef unsigned int MON_REG
typedef enum t_conditional CONDITIONAL
typedef enum t_radixtype RADIXTYPE
typedef enum t_action ACTION
typedef enum t_io_sim_result IO_SIM_RESULT
typedef struct cond_node_s cond_node_t
typedef void monitor_toggle_func_t(int value)
Enumerations
enum t_reg_id {
e_A = 0x00 ,
e_X = 0x01 ,
e_Y = 0x02 ,
e_PC = 0x03 ,
e_SP = 0x04 ,
e_FLAGS = 0x05 ,
e_AF = 0x06 ,
e_BC = 0x07 ,
e_DE = 0x08 ,
e_HL = 0x09 ,
e_IX = 0x0a ,
e_IY = 0x0b ,
e_I = 0x0c ,
e_R = 0x0d ,
e_AF2 = 0x0e ,
e_BC2 = 0x0f ,
e_DE2 = 0x10 ,
e_HL2 = 0x11 ,
e_R3 = 0x12 ,
e_R4 = 0x13 ,
e_R5 = 0x14 ,
e_R6 = 0x15 ,
e_R7 = 0x16 ,
e_R8 = 0x17 ,
e_R9 = 0x18 ,
e_R10 = 0x19 ,
e_R11 = 0x1a ,
e_R12 = 0x1b ,
e_R13 = 0x1c ,
e_R14 = 0x1d ,
e_R15 = 0x1e ,
e_ACM = 0x1f ,
e_YXM = 0x20 ,
e_B = 0x21 ,
e_C = 0x22 ,
e_DPR = 0x23 ,
e_PBR = 0x24 ,
e_DBR = 0x25 ,
e_D = 0x26 ,
e_U = 0x27 ,
e_DP = 0x28 ,
e_E = 0x29 ,
e_F = 0x2a ,
e_W = 0x2b ,
e_Q = 0x2c ,
e_V = 0x2d ,
e_MD = 0x2e ,
e_H = 0x2f ,
e_L = 0x30 ,
e_IXL = 0x31 ,
e_IXH = 0x32 ,
e_IYL = 0x33 ,
e_IYH = 0x34 ,
e_Rasterline = 0x35 ,
e_Cycle = 0x36 ,
e_Zero = 0x37 ,
e_One = 0x38
}
Types.
enum t_memory_op {
e_load = 0x01 ,
e_store = 0x02 ,
e_exec = 0x04
}
enum t_conditional {
e_INV ,
e_EQU ,
e_NEQ ,
e_GT ,
e_LT ,
e_GTE ,
e_LTE ,
e_LOGICAL_AND ,
e_LOGICAL_OR ,
e_ADD ,
e_SUB ,
e_MUL ,
e_DIV ,
e_BINARY_AND ,
e_BINARY_OR
}
enum t_radixtype {
e_text = -1 ,
e_default_radix = 0 ,
e_hexadecimal ,
e_decimal ,
e_octal ,
e_binary
}
enum t_action {
e_OFF = 0 ,
e_ON = 1 ,
e_TOGGLE = 2
}
enum t_io_sim_result {
e_IO_SIM_RESULT_OK = 0 ,
e_IO_SIM_RESULT_GENERAL_FAILURE = -1 ,
e_IO_SIM_RESULT_ILLEGAL_VALUE = -2 ,
e_IO_SIM_RESULT_ILLEGAL_PORT = -3
}
Functions
void mon_clear_buffer (void)
Function declarations.
void mon_add_number_to_buffer (int number)
void mon_add_number_masked_to_buffer (int number, int mask)
void mon_add_string_to_buffer (char *str)
void mon_backtrace (void)
void mon_cart_freeze (void)
IO_SIM_RESULT mon_userport_set_output (int value)
IO_SIM_RESULT mon_joyport_set_output (int port, int value)
void mon_reset_machine (int type)
void mon_resource_get (const char *name)
void mon_resource_set (const char *name, const char *value)
void mon_screenshot_save (const char *filename, int format)
void mon_show_dir (const char *path)
void mon_show_pwd (void)
Display current working directory.
void mon_make_dir (const char *path)
void mon_remove_dir (const char *path)
void mon_tape_ctrl (int port, int command)
void mon_tape_offs (int port, int offset)
void mon_display_screen (long addr)
Memory.
void mon_instructions_step (int count)
*** INSTRUCTION COMMANDS ***
void mon_instructions_next (int count)
void mon_instruction_return (void)
void mon_stack_up (int count)
void mon_stack_down (int count)
void mon_print_convert (int val)
void mon_change_dir (const char *path)
*** FILE COMMANDS ***
void mon_bank (MEMSPACE mem, const char *bank)
const char * mon_get_current_bank_name (MEMSPACE mem)
const char * mon_get_bank_name_for_bank (MEMSPACE mem, int banknum)
return the literal bank name for a given bank in a given memspace
int mon_get_bank_index_for_bank (MEMSPACE mem, int banknum)
return the current bank index for a given bank in a given memspace
int mon_get_bank_flags_for_bank (MEMSPACE mem, int banknum)
return the current bank flags for a given bank in a given memspace
const int mon_banknum_validate (MEMSPACE mem, int banknum)
check if the bank number is valid for memspace
int mon_banknum_from_bank (MEMSPACE mem, const char *bankname)
void mon_display_io_regs (MON_ADDR addr)
void mon_evaluate_default_addr (MON_ADDR *a)
void mon_set_mem_val (MEMSPACE mem, uint16_t mem_addr, uint8_t val)
void mon_set_mem_val_ex (MEMSPACE mem, int bank, uint16_t mem_addr, uint8_t val)
set a byte of memory in a specific bank, not the current.
bool mon_inc_addr_location (MON_ADDR *a, unsigned inc)
void mon_start_assemble_mode (MON_ADDR addr, char *asm_line)
long mon_evaluate_address_range (MON_ADDR *start_addr, MON_ADDR *end_addr, bool must_be_range, uint16_t default_len)
bool check_drive_emu_level_ok (int drive_num)
void mon_print_conditional (cond_node_t *cnode)
*** CONDITIONAL EXPRESSIONS ***
void mon_delete_conditional (cond_node_t *cnode)
int mon_evaluate_conditional (cond_node_t *cnode)
int mon_write_snapshot (const char *name, int save_roms, int save_disks, int even_mode)
*** SNAPSHOTS ***
int mon_read_snapshot (const char *name, int even_mode)
bool mon_is_valid_addr (MON_ADDR a)
bool mon_is_in_range (MON_ADDR start_addr, MON_ADDR end_addr, unsigned loc)
void mon_print_bin (int val, char on, char off)
*** ULTILITY FUNCTIONS ***
uint8_t mon_get_mem_val (MEMSPACE mem, uint16_t mem_addr)
uint8_t mon_get_mem_val_ex (MEMSPACE mem, int bank, uint16_t mem_addr)
uint8_t mon_get_mem_val_ex_nosfx (MEMSPACE mem, int bank, uint16_t mem_addr)
uint8_t mon_get_mem_val_nosfx (MEMSPACE mem, uint16_t mem_config, uint16_t mem_addr)
void mon_get_mem_block (MEMSPACE mem, uint16_t mem_start, uint16_t mem_end, uint8_t *data)
void mon_get_mem_block_ex (MEMSPACE mem, int bank, uint16_t mem_start, uint16_t mem_end, uint8_t *data)
void mon_jump (MON_ADDR addr)
exit monitor
void mon_go (void)
exit monitor
void mon_exit (void)
exit monitor, close monitor window
void mon_quit (void)
void mon_keyboard_feed (const char *string)
char * mon_symbol_table_lookup_name (MEMSPACE mem, uint16_t addr)
int mon_symbol_table_lookup_addr (MEMSPACE mem, char *name)
look up a symbol in the given memspace, returns address or -1 on error
char * mon_prepend_dot_to_name (char *name)
void mon_add_name_to_symbol_table (MON_ADDR addr, char *name)
void mon_remove_name_from_symbol_table (MEMSPACE mem, char *name)
void mon_print_symbol_table (MEMSPACE mem)
void mon_clear_symbol_table (MEMSPACE mem)
void mon_load_symbols (MEMSPACE mem, const char *filename)
void mon_save_symbols (MEMSPACE mem, const char *filename)
void mon_record_commands (char *filename)
*** COMMAND FILES ***
void mon_end_recording (void)
int mon_playback_commands (const char *filename, bool interrupt_current_playback)
void monitor_change_device (MEMSPACE mem)
void mon_export (void)
void mon_stopwatch_show (const char *prefix, const char *suffix)
void mon_stopwatch_reset (void)
void mon_maincpu_trace (void)
void mon_maincpu_toggle_trace (int state)
void mon_breakpoint_set_dummy_state (MEMSPACE mem, int state)
void mon_update_all_checkpoint_state (void)
Ensure checkpoint state for memspaces is set correctly.
Variables
const char *const _mon_space_strings []
Global variables.
struct console_s * console_log
int sidefx
int break_on_dummy_access
int exit_mon
RADIXTYPE default_radix
MEMSPACE default_memspace
bool asm_mode
MON_ADDR asm_mode_addr
struct monitor_cpu_type_s * monitor_cpu_for_memspace [e_invalid_space]
We now have an array of pointers to the current monitor_cpu_type for each memspace.
MON_ADDR dot_addr [e_invalid_space]
const char *const mon_memspace_string []
int mon_stop_output
monitor_interface_t * mon_interfaces [e_invalid_space]
unsigned char data_buf [256]
unsigned char data_mask_buf [256]
unsigned int data_buf_len
Macro Definition Documentation
addr_location
#define addr_location (ma) (LO16(ma))
addr_mask
#define addr_mask (l) (LO16(l))
addr_memspace
#define addr_memspace (ma) (HI16_TO_LO16(ma))
any_watchpoints_load
#define any_watchpoints_load (mem) (watchpoints_load[(mem)] != NULL)
any_watchpoints_store
#define any_watchpoints_store (mem) (watchpoints_store[(mem)] != NULL)
DEFAULT_DISASSEMBLY_SIZE
#define DEFAULT_DISASSEMBLY_SIZE 40
FALSE
#define FALSE 0
HI16
#define HI16 (x) ((x) & 0xffff0000)
HI16_TO_LO16
#define HI16_TO_LO16 (x) (((x) >> 16) & 0xffff)
LO16
#define LO16 (x) ((x) & 0xffff)
LO16_TO_HI16
#define LO16_TO_HI16 (x) (((x) & 0xffff) << 16)
new_addr
#define new_addr (m, l) (LO16_TO_HI16(m) | (l))
new_cond
#define new_cond ((cond_node_t *)(lib_malloc(sizeof(cond_node_t))))
new_reg
#define new_reg (m, r) (LO16_TO_HI16(m) | (r))
reg_memspace
#define reg_memspace (mr) (HI16_TO_LO16(mr))
reg_regid
#define reg_regid (mr) (LO16(mr))
STATE_BNAME
#define STATE_BNAME 4
STATE_CTYPE
#define STATE_CTYPE 5
STATE_FNAME
#define STATE_FNAME 1
STATE_INITIAL
#define STATE_INITIAL 0
STATE_REG_ASGN
#define STATE_REG_ASGN 2
STATE_ROL
#define STATE_ROL 3
TRUE
#define TRUE 1
Defines.
Typedef Documentation
ACTION
typedef enum t_action ACTION
cond_node_t
typedef struct cond_node_s cond_node_t
CONDITIONAL
typedef enum t_conditional CONDITIONAL
IO_SIM_RESULT
typedef enum t_io_sim_result IO_SIM_RESULT
MEMORY_OP
typedef enum t_memory_op MEMORY_OP
MON_ADDR
typedef unsigned int MON_ADDR
MON_REG
typedef unsigned int MON_REG
monitor_toggle_func_t
typedef void monitor_toggle_func_t(int value)
RADIXTYPE
typedef enum t_radixtype RADIXTYPE
REG_ID
typedef enum t_reg_id REG_ID
Enumeration Type Documentation
t_action
enum t_action
Enumerator
e_OFF
e_ON
e_TOGGLE
t_conditional
enum t_conditional
Enumerator
e_INV
e_EQU
e_NEQ
e_GT
e_LT
e_GTE
e_LTE
e_LOGICAL_AND
e_LOGICAL_OR
e_ADD
e_SUB
e_MUL
e_DIV
e_BINARY_AND
e_BINARY_OR
t_io_sim_result
enum t_io_sim_result
Enumerator
e_IO_SIM_RESULT_OK
e_IO_SIM_RESULT_GENERAL_FAILURE
e_IO_SIM_RESULT_ILLEGAL_VALUE
e_IO_SIM_RESULT_ILLEGAL_PORT
t_memory_op
enum t_memory_op
Enumerator
e_load
e_store
e_exec
t_radixtype
enum t_radixtype
Enumerator
e_text
e_default_radix
e_hexadecimal
e_decimal
e_octal
e_binary
t_reg_id
enum t_reg_id
Types.
Enumerator
e_A
e_X
e_Y
e_PC
e_SP
e_FLAGS
e_AF
e_BC
e_DE
e_HL
e_IX
e_IY
e_I
e_R
e_AF2
e_BC2
e_DE2
e_HL2
e_R3
e_R4
e_R5
e_R6
e_R7
e_R8
e_R9
e_R10
e_R11
e_R12
e_R13
e_R14
e_R15
e_ACM
e_YXM
e_B
e_C
e_DPR
e_PBR
e_DBR
e_D
e_U
e_DP
e_E
e_F
e_W
e_Q
e_V
e_MD
e_H
e_L
e_IXL
e_IXH
e_IYL
e_IYH
e_Rasterline
e_Cycle
e_Zero
e_One
Function Documentation
check_drive_emu_level_ok()
bool check_drive_emu_level_ok (int drive_num)
Referenced by mon_get_mem_val_ex(), mon_get_mem_val_ex_nosfx(), mon_get_mem_val_nosfx(), mon_register_get_val(), mon_register_print(), mon_register_print_ex(), mon_register_set_val(), mon_register_valid(), mon_set_mem_val(), and mon_set_mem_val_ex().
mon_add_name_to_symbol_table()
void mon_add_name_to_symbol_table (MON_ADDR addr, char * name)
mon_add_number_masked_to_buffer()
void mon_add_number_masked_to_buffer (int number, int mask)
mon_add_number_to_buffer()
void mon_add_number_to_buffer (int number)
mon_add_string_to_buffer()
void mon_add_string_to_buffer (char * str)
mon_backtrace()
void mon_backtrace (void)
mon_bank()
void mon_bank (MEMSPACE mem, const char * bank)
< part of a bank group, eg "ram00, ram01 ..."
< first in a bank group, eg "ram00"
< last in a bank group, eg "ramff"
mon_banknum_from_bank()
int mon_banknum_from_bank (MEMSPACE mem, const char * bankname)
mon_banknum_validate()
const int mon_banknum_validate (MEMSPACE mem, int banknum)
check if the bank number is valid for memspace
Parameters
mem The memspace of the bank
banknum The number of the bank
Returns
-1: Memspace doesn't have banks 0: Bank number invalid 1: Bank number valid
Referenced by monitor_binary_process_mem_get(), and monitor_binary_process_mem_set().
mon_breakpoint_set_dummy_state()
void mon_breakpoint_set_dummy_state (MEMSPACE mem, int state)
Todo:
FIXME: some day we might want to toggle the break-on-dummy-access per MEMSPACE, for now its a global option
mon_cart_freeze()
void mon_cart_freeze (void)
mon_change_dir()
void mon_change_dir (const char * path)
*** FILE COMMANDS ***
mon_clear_buffer()
void mon_clear_buffer (void)
Function declarations.
Referenced by mon_memory_fill(), and mon_memory_hunt().
mon_clear_symbol_table()
void mon_clear_symbol_table (MEMSPACE mem)
mon_delete_conditional()
void mon_delete_conditional (cond_node_t * cnode)
Referenced by mon_delete_conditional(), and remove_checkpoint().
mon_display_io_regs()
void mon_display_io_regs (MON_ADDR addr)
< registered area contains mirrors of another registered area
mon_display_screen()
void mon_display_screen (long addr)
Memory.
Display screen memory
Display (current) screen memory, converting PETSCII to ASCII.
The lex/yuck stuff will pass in either -1 when no arg has been given or an address.
Parameters
[in] address address of screen memory, -1 to show current screen
Note
Currently doesn't show the addresses in the SDL monitor, since the SDL monitor is only 40 columns
Todo:
FIXME: this should really be handled by the UI instead, ie the UI should always just give us valid numbers
mon_end_recording()
void mon_end_recording (void)
mon_evaluate_address_range()
long mon_evaluate_address_range (MON_ADDR * start_addr, MON_ADDR * end_addr, bool must_be_range, uint16_t default_len)
Referenced by breakpoint_add_checkpoint(), mon_disassemble_lines(), mon_file_save(), mon_memory_compare(), mon_memory_display(), mon_memory_display_data(), mon_memory_fill(), mon_memory_hunt(), and mon_memory_move().
mon_evaluate_conditional()
int mon_evaluate_conditional (cond_node_t * cnode)
Referenced by mon_breakpoint_check_checkpoint(), and mon_evaluate_conditional().
mon_evaluate_default_addr()
void mon_evaluate_default_addr (MON_ADDR * a)
Referenced by mon_drive_block_cmd(), mon_evaluate_address_range(), mon_file_load(), mon_file_verify(), mon_jump(), mon_memory_compare(), mon_memory_move(), and mon_start_assemble_mode().
mon_exit()
void mon_exit (void)
exit monitor, close monitor window
Referenced by monitor_startup(), and playback_end_file().
mon_export()
void mon_export (void)
mon_get_bank_flags_for_bank()
int mon_get_bank_flags_for_bank (MEMSPACE mem, int banknum)
return the current bank flags for a given bank in a given memspace
Referenced by mon_bank().
mon_get_bank_index_for_bank()
int mon_get_bank_index_for_bank (MEMSPACE mem, int banknum)
return the current bank index for a given bank in a given memspace
Referenced by mon_bank().
mon_get_bank_name_for_bank()
const char * mon_get_bank_name_for_bank (MEMSPACE mem, int banknum)
return the literal bank name for a given bank in a given memspace
Referenced by mon_get_current_bank_name(), and mon_print_conditional().
mon_get_current_bank_name()
const char * mon_get_current_bank_name (MEMSPACE mem)
mon_get_mem_block()
void mon_get_mem_block (MEMSPACE mem, uint16_t mem_start, uint16_t mem_end, uint8_t * data)
mon_get_mem_block_ex()
void mon_get_mem_block_ex (MEMSPACE mem, int bank, uint16_t mem_start, uint16_t mem_end, uint8_t * data)
Referenced by mon_get_mem_block(), and monitor_binary_process_mem_get().
mon_get_mem_val()
uint8_t mon_get_mem_val (MEMSPACE mem, uint16_t mem_addr)
Referenced by mon_disassemble_with_label(), mon_drive_block_cmd(), mon_dump_with_label(), mon_file_save(), mon_file_verify(), mon_memory_compare(), mon_memory_display(), mon_memory_display_data(), mon_memory_hunt(), mon_memory_move(), mon_register_list_get6502(), mon_register_list_get6502dtv(), mon_register_list_getR65C02(), and mon_register_print().
mon_get_mem_val_ex()
uint8_t mon_get_mem_val_ex (MEMSPACE mem, int bank, uint16_t mem_addr)
Referenced by mon_evaluate_conditional(), mon_get_mem_block_ex(), and mon_get_mem_val().
mon_get_mem_val_ex_nosfx()
uint8_t mon_get_mem_val_ex_nosfx (MEMSPACE mem, int bank, uint16_t mem_addr)
Referenced by mon_disassemble_instr_bank_internal(), mon_display_screen(), and mon_get_mem_val_nosfx().
mon_get_mem_val_nosfx()
uint8_t mon_get_mem_val_nosfx (MEMSPACE mem, uint16_t mem_config, uint16_t mem_addr)
Referenced by are_aggregates_compatible(), is_branch_instruction(), mon_backtrace(), mon_disassemble_instr_memconfig_internal(), and mon_disassemble_oneline().
mon_go()
void mon_go (void)
exit monitor
mon_inc_addr_location()
bool mon_inc_addr_location (MON_ADDR * a, unsigned inc)
Referenced by mon_assemble_instr(), mon_disassemble_lines(), and mon_evaluate_address_range().
mon_instruction_return()
void mon_instruction_return (void)
Referenced by monitor_binary_process_execute_until_return().
mon_instructions_next()
void mon_instructions_next (int count)
Referenced by monitor_binary_process_advance_instructions().
mon_instructions_step()
void mon_instructions_step (int count)
*** INSTRUCTION COMMANDS ***
Referenced by monitor_binary_process_advance_instructions().
mon_is_in_range()
bool mon_is_in_range (MON_ADDR start_addr, MON_ADDR end_addr, unsigned loc)
Referenced by mon_breakpoint_check_checkpoint(), and search_checkpoint_list().
mon_is_valid_addr()
bool mon_is_valid_addr (MON_ADDR a)
Referenced by mon_drive_block_cmd(), mon_evaluate_address_range(), mon_file_load(), mon_file_verify(), mon_is_in_range(), mon_memory_fill(), and print_checkpoint_info().
mon_joyport_set_output()
IO_SIM_RESULT mon_joyport_set_output (int port, int value)
Referenced by monitor_binary_process_joyport_set().
mon_jump()
void mon_jump (MON_ADDR addr)
exit monitor
mon_keyboard_feed()
void mon_keyboard_feed (const char * string)
mon_load_symbols()
void mon_load_symbols (MEMSPACE mem, const char * filename)
mon_maincpu_toggle_trace()
void mon_maincpu_toggle_trace (int state)
mon_maincpu_trace()
void mon_maincpu_trace (void)
Referenced by mon_maincpu_toggle_trace().
mon_make_dir()
void mon_make_dir (const char * path)
mon_playback_commands()
int mon_playback_commands (const char * filename, bool interrupt_current_playback)
< read mode (text)
< read mode (text)
Referenced by monitor_set_moncommands_file().
mon_prepend_dot_to_name()
char * mon_prepend_dot_to_name (char * name)
mon_print_bin()
void mon_print_bin (int val, char on, char off)
*** ULTILITY FUNCTIONS ***
Referenced by mon_memory_display(), mon_memory_display_data(), and mon_print_convert().
mon_print_conditional()
void mon_print_conditional (cond_node_t * cnode)
*** CONDITIONAL EXPRESSIONS ***
Referenced by mon_breakpoint_set_checkpoint_condition(), mon_print_conditional(), and print_checkpoint_info().
mon_print_convert()
void mon_print_convert (int val)
mon_print_symbol_table()
void mon_print_symbol_table (MEMSPACE mem)
mon_quit()
void mon_quit (void)
Referenced by monitor_binary_process_quit().
mon_read_snapshot()
int mon_read_snapshot (const char * name, int even_mode)
Referenced by monitor_binary_process_undump().
mon_record_commands()
void mon_record_commands (char * filename)
*** COMMAND FILES ***
< write mode (binary)
mon_remove_dir()
void mon_remove_dir (const char * path)
mon_remove_name_from_symbol_table()
void mon_remove_name_from_symbol_table (MEMSPACE mem, char * name)
Referenced by mon_add_name_to_symbol_table().
mon_reset_machine()
void mon_reset_machine (int type)
Referenced by monitor_binary_process_reset().
mon_resource_get()
void mon_resource_get (const char * name)
mon_resource_set()
void mon_resource_set (const char * name, const char * value)
mon_save_symbols()
void mon_save_symbols (MEMSPACE mem, const char * filename)
< write mode (binary)
Todo:
FIXME: Write out all memspaces?
mon_screenshot_save()
void mon_screenshot_save (const char * filename, int format)
mon_set_mem_val()
void mon_set_mem_val (MEMSPACE mem, uint16_t mem_addr, uint8_t val)
Referenced by mon_assemble_instr(), mon_drive_block_cmd(), mon_file_load(), mon_memory_fill(), and mon_memory_move().
mon_set_mem_val_ex()
void mon_set_mem_val_ex (MEMSPACE mem, int bank, uint16_t mem_addr, uint8_t val)
set a byte of memory in a specific bank, not the current.
Parameters
mem Memspace of bank
bank The bank number
mem_addr The 16 bit memory address
val The byte to write
Referenced by monitor_binary_process_mem_set().
mon_show_dir()
void mon_show_dir (const char * path)
< directory separator as a string
Referenced by mon_drive_list().
mon_show_pwd()
void mon_show_pwd (void)
Display current working directory.
mon_stack_down()
void mon_stack_down (int count)
mon_stack_up()
void mon_stack_up (int count)
mon_start_assemble_mode()
void mon_start_assemble_mode (MON_ADDR addr, char * asm_line)
mon_stopwatch_reset()
void mon_stopwatch_reset (void)
mon_stopwatch_show()
void mon_stopwatch_show (const char * prefix, const char * suffix)
Referenced by mon_disassemble_with_regdump(), and mon_register_print().
mon_symbol_table_lookup_addr()
int mon_symbol_table_lookup_addr (MEMSPACE mem, char * name)
look up a symbol in the given memspace, returns address or -1 on error
Referenced by mon_add_name_to_symbol_table(), and mon_remove_name_from_symbol_table().
mon_symbol_table_lookup_name()
char * mon_symbol_table_lookup_name (MEMSPACE mem, uint16_t addr)
Referenced by mon_add_name_to_symbol_table(), mon_disassemble_instr(), mon_disassemble_lines(), mon_disassemble_to_string_internal(), mon_disassemble_with_label(), mon_dump_with_label(), and print_dst().
mon_tape_ctrl()
void mon_tape_ctrl (int port, int command)
mon_tape_offs()
void mon_tape_offs (int port, int offset)
mon_update_all_checkpoint_state()
void mon_update_all_checkpoint_state (void)
Ensure checkpoint state for memspaces is set correctly.
Used to keep breakpoints working after a snapshot load.
Referenced by load_snapshot_trap().
mon_userport_set_output()
IO_SIM_RESULT mon_userport_set_output (int value)
Referenced by monitor_binary_process_userport_set().
mon_write_snapshot()
int mon_write_snapshot (const char * name, int save_roms, int save_disks, int even_mode)
*** SNAPSHOTS ***
Referenced by monitor_binary_process_dump().
monitor_change_device()
void monitor_change_device (MEMSPACE mem)
Variable Documentation
_mon_space_strings
const char* const _mon_space_strings[] extern
Global variables.
Referenced by monitor_change_device(), and monitor_cpu_type_set().
asm_mode
bool asm_mode extern
Referenced by make_prompt(), mon_start_assemble_mode(), monitor_init(), and monitor_process().
asm_mode_addr
MON_ADDR asm_mode_addr extern
Referenced by make_prompt(), mon_assemble_instr(), mon_start_assemble_mode(), and monitor_init().
break_on_dummy_access
int break_on_dummy_access extern
Referenced by mon_breakpoint_set_dummy_state(), and update_checkpoint_state().
console_log
struct console_s* console_log extern
Referenced by mon_disassemble_lines(), mon_display_screen(), mon_memory_display(), mon_out_buffered(), mon_out_wordwrap(), monitor_close(), monitor_open(), and print_help_topics().
data_buf
unsigned char data_buf[256] extern
Referenced by mon_add_number_masked_to_buffer(), mon_add_number_to_buffer(), mon_add_string_to_buffer(), mon_memory_fill(), and mon_memory_hunt().
data_buf_len
unsigned int data_buf_len extern
Referenced by mon_add_number_masked_to_buffer(), mon_add_number_to_buffer(), mon_add_string_to_buffer(), mon_clear_buffer(), mon_memory_fill(), mon_memory_hunt(), and monitor_init().
data_mask_buf
unsigned char data_mask_buf[256] extern
Referenced by mon_add_number_masked_to_buffer(), mon_add_number_to_buffer(), mon_add_string_to_buffer(), and mon_memory_hunt().
default_memspace
MEMSPACE default_memspace extern
Referenced by make_prompt(), mon_add_name_to_symbol_table(), mon_backtrace(), mon_bank(), mon_banknum_from_bank(), mon_breakpoint_set_dummy_state(), mon_clear_symbol_table(), mon_display_io_regs(), mon_evaluate_address_range(), mon_evaluate_default_addr(), mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), mon_print_conditional(), mon_print_symbol_table(), mon_remove_name_from_symbol_table(), mon_save_symbols(), mon_stopwatch_reset(), mon_stopwatch_show(), mon_symbol_table_lookup_addr(), mon_symbol_table_lookup_name(), monitor_change_device(), monitor_check_icount(), monitor_cpu_type_set(), monitor_cpu_type_set_value(), monitor_find_cpu_for_memspace(), monitor_init(), monitor_open(), monitor_startup(), and print_dst().
default_radix
RADIXTYPE default_radix extern
Referenced by monitor_init().
dot_addr
MON_ADDR dot_addr[e_invalid_space] extern
Referenced by make_prompt(), mon_assemble_instr(), mon_disassemble_lines(), mon_evaluate_address_range(), mon_memory_display(), mon_memory_display_data(), mon_read_snapshot(), monitor_binary_process_undump(), monitor_init(), and monitor_open().
exit_mon
int exit_mon extern
Referenced by breakpoint_add_checkpoint(), mon_autostart(), mon_exit(), mon_go(), mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), mon_jump(), mon_quit(), mon_reset_machine(), monitor_binary_get_command_line(), monitor_binary_process_exit(), monitor_close(), monitor_init(), monitor_open(), monitor_process(), and monitor_startup().
mon_interfaces
monitor_interface_t* mon_interfaces[e_invalid_space] extern
Referenced by check_drive_emu_level_ok(), mon_bank(), mon_banknum_from_bank(), mon_banknum_validate(), mon_breakpoint_check_checkpoint(), mon_disassemble_instr_bank_internal(), mon_display_io_regs(), mon_display_screen(), mon_evaluate_conditional(), mon_get_bank_flags_for_bank(), mon_get_bank_index_for_bank(), mon_get_bank_name_for_bank(), mon_get_current_bank_name(), mon_get_mem_block(), mon_get_mem_val(), mon_get_mem_val_ex(), mon_get_mem_val_ex_nosfx(), mon_get_mem_val_nosfx(), mon_instruction_return(), mon_instructions_next(), mon_instructions_step(), mon_register_get_val(), mon_register_list_get6502(), mon_register_list_get6502dtv(), mon_register_print(), mon_register_print_ex(), mon_register_set_val(), mon_set_mem_val(), mon_set_mem_val_ex(), mon_stopwatch_reset(), mon_stopwatch_show(), monitor_binary_process_banks_available(), monitor_check_icount(), monitor_init(), monitor_open(), and update_checkpoint_state().
mon_memspace_string
const char* const mon_memspace_string[] extern
Referenced by make_prompt(), mon_disassemble_instr(), mon_disassemble_instr_bank_internal(), mon_disassemble_instr_memconfig_internal(), mon_disassemble_oneline(), mon_memory_display(), mon_memory_display_data(), mon_save_symbols(), and print_checkpoint_info().
mon_stop_output
int mon_stop_output extern
Referenced by mon_disassemble_lines(), mon_memory_display(), mon_memory_display_data(), monitor_abort(), monitor_process(), and print_help_topics().
monitor_cpu_for_memspace
struct monitor_cpu_type_s* monitor_cpu_for_memspace[e_invalid_space] extern
We now have an array of pointers to the current monitor_cpu_type for each memspace.
This gets initialized in monitor_init().
Referenced by mon_assemble_instr(), mon_backtrace(), mon_breakpoint_check_checkpoint(), mon_disassemble_instr_bank_internal(), mon_disassemble_instr_memconfig_internal(), mon_disassemble_to_string_ex(), mon_disassemble_to_string_internal(), mon_disassemble_with_regdump(), mon_evaluate_conditional(), mon_jump(), mon_read_snapshot(), mon_register_id_to_value(), mon_register_list_get(), monitor_binary_process_registers_set(), monitor_binary_process_undump(), monitor_binary_response_resumed(), monitor_binary_response_stopped(), monitor_binary_ui_jam_dialog(), monitor_cpu_type_set(), monitor_cpu_type_set_value(), monitor_init(), and monitor_open().
sidefx
int sidefx extern
Referenced by mon_evaluate_conditional(), mon_get_mem_val_ex(), mon_register_list_get6502(), mon_register_print(), mon_set_mem_val(), mon_set_mem_val_ex(), monitor_binary_process_mem_get(), monitor_binary_process_mem_set(), and monitor_init().