vsid: core/i8255a.h File Reference
i8255a.h File Reference
#include "types.h"
Data Structures
struct _i8255a_state
Macros
#define I8255A_G2_PC 0x01
control register bit masks
#define I8255A_G2_PB 0x02
#define I8255A_G2_MS 0x04
#define I8255A_G1_PC 0x08
#define I8255A_G1_PA 0x10
#define I8255A_G1_MS 0x60
#define I8255A_MODE 0x80
#define I8255A_BS 0x01
Typedefs
typedef struct _i8255a_state i8255a_state
Functions
void i8255a_reset (i8255a_state *ctx)
uint8_t i8255a_read (i8255a_state *ctx, int8_t reg)
uint8_t i8255a_peek (i8255a_state *ctx, int8_t reg)
void i8255a_store (i8255a_state *ctx, int8_t reg, uint8_t data)
int i8255a_dump (i8255a_state *ctx)
int i8255a_snapshot_write_data (i8255a_state *ctx, struct snapshot_module_s *m)
int i8255a_snapshot_read_data (i8255a_state *ctx, struct snapshot_module_s *m)
Macro Definition Documentation
I8255A_BS
#define I8255A_BS 0x01
I8255A_G1_MS
#define I8255A_G1_MS 0x60
I8255A_G1_PA
#define I8255A_G1_PA 0x10
I8255A_G1_PC
#define I8255A_G1_PC 0x08
I8255A_G2_MS
#define I8255A_G2_MS 0x04
I8255A_G2_PB
#define I8255A_G2_PB 0x02
I8255A_G2_PC
#define I8255A_G2_PC 0x01
control register bit masks
I8255A_MODE
#define I8255A_MODE 0x80
Typedef Documentation
i8255a_state
typedef struct _i8255a_state i8255a_state
Function Documentation
i8255a_dump()
int i8255a_dump (i8255a_state * ctx)
Referenced by drivemem_ioreg_list_get().
i8255a_peek()
uint8_t i8255a_peek (i8255a_state * ctx, int8_t reg)
Referenced by i8255a_dump().
i8255a_read()
uint8_t i8255a_read (i8255a_state * ctx, int8_t reg)
Referenced by cmdhd_read(), and i8255a_peek().
i8255a_reset()
void i8255a_reset (i8255a_state * ctx)
Referenced by cmdhd_reset().
i8255a_snapshot_read_data()
int i8255a_snapshot_read_data (i8255a_state * ctx, struct snapshot_module_s * m)
Referenced by cmdhd_snapshot_read_module().
i8255a_snapshot_write_data()
int i8255a_snapshot_write_data (i8255a_state * ctx, struct snapshot_module_s * m)
Referenced by cmdhd_snapshot_write_module().
i8255a_store()
void i8255a_store (i8255a_state * ctx, int8_t reg, uint8_t data)
Referenced by cmdhd_store().