vsid: video/render-common.c File Reference
render-common.c File Reference
#include "vice.h"
#include "types.h"
#include "video.h"
Functions
static void render_source_line (uint32_t *tmptrg, const uint8_t *tmpsrc, const uint32_t *colortab, unsigned int wstart, unsigned int wfast, unsigned int wend)
static void render_source_line_2x (uint32_t *tmptrg, const uint8_t *tmpsrc, const uint32_t *colortab, unsigned int wstart, unsigned int wfast, unsigned int wend, unsigned int wfirst, unsigned int wlast)
static void render_solid_line (uint32_t *tmptrg, const uint8_t *tmpsrc, const uint32_t color, unsigned int wstart, unsigned int wfast, unsigned int wend)
static void render_solid_line_2x (uint32_t *tmptrg, const uint8_t *tmpsrc, const uint32_t color, unsigned int wstart, unsigned int wfast, unsigned int wend, unsigned int wfirst, unsigned int wlast)
Function Documentation
render_solid_line()
static void render_solid_line (uint32_t * tmptrg, const uint8_t * tmpsrc, const uint32_t color, unsigned int wstart, unsigned int wfast, unsigned int wend) inline static
Referenced by render_32_1x2_interlaced(), render_32_1x2_non_interlaced(), and render_32_2x2_interlaced().
render_solid_line_2x()
static void render_solid_line_2x (uint32_t * tmptrg, const uint8_t * tmpsrc, const uint32_t color, unsigned int wstart, unsigned int wfast, unsigned int wend, unsigned int wfirst, unsigned int wlast) inline static
Referenced by render_32_2x4_interlaced(), and render_32_2x4_non_interlaced().
render_source_line()
static void render_source_line (uint32_t * tmptrg, const uint8_t * tmpsrc, const uint32_t * colortab, unsigned int wstart, unsigned int wfast, unsigned int wend) inline static
Referenced by render_32_1x2_interlaced(), and render_32_1x2_non_interlaced().
render_source_line_2x()
static void render_source_line_2x (uint32_t * tmptrg, const uint8_t * tmpsrc, const uint32_t * colortab, unsigned int wstart, unsigned int wfast, unsigned int wend, unsigned int wfirst, unsigned int wlast) inline static
Referenced by render_32_2x2_interlaced(), render_32_2x4_interlaced(), and render_32_2x4_non_interlaced().