vsid: arch/gtk3/actions-vsid.c File Reference
actions-vsid.c File Reference
UI action implementations for VSID.
#include "vice.h"
#include <gtk/gtk.h>
#include <stddef.h>
#include <stdbool.h>
#include "debug_gtk3.h"
#include "hotkeys.h"
#include "machine.h"
#include "psid.h"
#include "resources.h"
#include "ui.h"
#include "uiactions.h"
#include "uisidattach.h"
#include "vsidcontrolwidget.h"
#include "vsidmixerwidget.h"
#include "vsidplaylistwidget.h"
#include "vsidstate.h"
#include "actions-vsid.h"
Macros
#define FFWD_SPEED 500
Emulation speed during fast forward.
Functions
static void play_current_tune (void)
Trigger play of current tune.
static void play_subtune (int tune)
Play subtune.
static void psid_load_action (ui_action_map_t *self)
Show PSID load dialog.
static void psid_override_toggle_action (ui_action_map_t *self)
Toggle override of PSID file settings.
static void psid_play_action (ui_action_map_t *self)
Start playback.
static void psid_pause_action (ui_action_map_t *self)
Toggle pause.
static void psid_stop_action (ui_action_map_t *self)
Stop playback.
static void psid_ffwd_action (ui_action_map_t *self)
Toggle fast forward.
static void psid_subtune_next_action (ui_action_map_t *self)
Play next subtune.
static void psid_subtune_previous_action (ui_action_map_t *self)
Play previous subtune.
static void psid_subtune_action (ui_action_map_t *self)
Play a subtune.
static void psid_loop_toggle_action (ui_action_map_t *self)
Toggle SID tune looping.
static void psid_playlist_action (ui_action_map_t *self)
Call a VSID playlist function.
void actions_vsid_register (void)
Register VSID-specific actions.
void actions_vsid_setup_ui (void)
Set initial UI element states for VSID.
Variables
static const ui_action_map_t vsid_actions []
List of VSID-specific actions.
Detailed Description
UI action implementations for VSID.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Note
This file cannot be used from ui.c since that causes massive linker errors due to the way vsid is linked. Currently registering the actions happens in vsidui.c, which magically does work.
Macro Definition Documentation
FFWD_SPEED
#define FFWD_SPEED 500
Emulation speed during fast forward.
Function Documentation
actions_vsid_register()
void actions_vsid_register (void)
Register VSID-specific actions.
Referenced by vsid_ui_init().
actions_vsid_setup_ui()
void actions_vsid_setup_ui (void)
Set initial UI element states for VSID.
Referenced by vsid_ui_init().
play_current_tune()
static void play_current_tune (void) static
Trigger play of current tune.
Helper to (re)start playback of current selected subtune
Referenced by play_subtune(), psid_subtune_next_action(), and psid_subtune_previous_action().
play_subtune()
static void play_subtune (int tune) static
Play subtune.
Parameters
[in] tune subtune number
Referenced by psid_subtune_action().
psid_ffwd_action()
static void psid_ffwd_action (ui_action_map_t * self) static
Toggle fast forward.
Parameters
[in] self action map
psid_load_action()
static void psid_load_action (ui_action_map_t * self) static
Show PSID load dialog.
Parameters
[in] self action map
psid_loop_toggle_action()
static void psid_loop_toggle_action (ui_action_map_t * self) static
Toggle SID tune looping.
Parameters
[in] self action map
psid_override_toggle_action()
static void psid_override_toggle_action (ui_action_map_t * self) static
Toggle override of PSID file settings.
Parameters
[in] self action map
psid_pause_action()
static void psid_pause_action (ui_action_map_t * self) static
Toggle pause.
Parameters
[in] self action map
psid_play_action()
static void psid_play_action (ui_action_map_t * self) static
Start playback.
Parameters
[in] self action map
psid_playlist_action()
static void psid_playlist_action (ui_action_map_t * self) static
Call a VSID playlist function.
Parameters
[in] self action map
psid_stop_action()
static void psid_stop_action (ui_action_map_t * self) static
Stop playback.
Parameters
[in] self action map
psid_subtune_action()
static void psid_subtune_action (ui_action_map_t * self) static
Play a subtune.
Parameters
[in] self action map
psid_subtune_next_action()
static void psid_subtune_next_action (ui_action_map_t * self) static
Play next subtune.
Parameters
[in] self action map
Note
Wraps around to the first tune if the current tune is the last.
psid_subtune_previous_action()
static void psid_subtune_previous_action (ui_action_map_t * self) static
Play previous subtune.
Parameters
[in] self action map
Note
Wraps around to the last tune if the current tune is the first.
Variable Documentation
vsid_actions
const ui_action_map_t vsid_actions[] static
List of VSID-specific actions.
Referenced by actions_vsid_register().