vsid: arch/gtk3/widgets/statusbarrecordingwidget.c File Reference
statusbarrecordingwidget.c File Reference
Widget to display and control recording of events/audio/video.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "basedialogs.h"
#include "vice-event.h"
#include "machine.h"
#include "resources.h"
#include "screenshot.h"
#include "sound.h"
#include "ui.h"
#include "uimedia.h"
#include "statusbarrecordingwidget.h"
Macros
#define HIDE_ALL_TIMEOUT 5
Seconds to wait before hiding the widget after pressing 'STOP'.
#define STOP_BUTTON_CSS
CSS rules for the media recording STOP button.
#define TIMING_CSS
CSS for the timing widget.
Enumerations
enum {
RW_COL_TEXT = 0 ,
RW_COL_TIME = 1 ,
RW_COL_BUTTON = 2
}
Columns in the recording widget.
enum {
RW_ROW_TEXT = 0 ,
RW_ROW_TIME = 0 ,
RW_ROW_BUTTON = 0
}
Rows in the recording widget.
enum {
RW_TYPE_NONE ,
RW_TYPE_EVENTS ,
RW_TYPE_AUDIO ,
RW_TYPE_VIDEO
}
Types of recordings.
Functions
static gboolean update_timer (gpointer data)
Callback for the g_timeout.
static void on_stop_clicked (GtkWidget *button, gpointer data)
Event handler for the 'clicked' event of the STOP button.
static GtkWidget * create_stop_button (void)
Create "Stop" button.
GtkWidget * statusbar_recording_widget_create (void)
Create recording status widget.
void statusbar_recording_widget_set_recording_status (GtkWidget *widget, int status)
Set recording status.
void statusbar_recording_widget_set_time (GtkWidget *widget, unsigned int current, unsigned int total)
Update recording/playback time display.
void statusbar_recording_widget_set_event_playback (GtkWidget *widget, char *version)
Set event playback status.
static gboolean hide_all_timer_callback (gpointer data)
Timer callback for the hide_all() method.
void statusbar_recording_widget_hide_all (GtkWidget *widget, guint timeout)
Clear the labels and hide the button after timeout seconds.
Variables
static const gchar * rec_types []
Types of recordings as strings.
static guint timeout_id = 0
GSource id of the timeout to hide the recording button.
Detailed Description
Widget to display and control recording of events/audio/video.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
HIDE_ALL_TIMEOUT
#define HIDE_ALL_TIMEOUT 5
Seconds to wait before hiding the widget after pressing 'STOP'.
STOP_BUTTON_CSS
#define STOP_BUTTON_CSS
Value:
    "button { \n" \
    "  padding: 0;\n" \
    "  min-width: 14px;\n" \
    "  min-height: 10px;\n" \
    "  margin-top: 0px;\n" \
    "  margin-bottom: 2px;\n" \
    "  margin-right: 8px;\n" \
    "}"
CSS rules for the media recording STOP button.
TIMING_CSS
#define TIMING_CSS
Value:
    "label { \n" \
    "  font-family: monospace;\n" \
    "}"
CSS for the timing widget.
Enumeration Type Documentation
anonymous enum
anonymous enum
Columns in the recording widget.
Enumerator
RW_COL_TEXT
recording status label
RW_COL_TIME
recording time label
RW_COL_BUTTON
STOP button.
anonymous enum
anonymous enum
Rows in the recording widget.
Enumerator
RW_ROW_TEXT
recording status label
RW_ROW_TIME
recording time label
RW_ROW_BUTTON
STOP button (takes both rows)
anonymous enum
anonymous enum
Types of recordings.
Enumerator
RW_TYPE_NONE
nothing is being recorded
RW_TYPE_EVENTS
recording events
RW_TYPE_AUDIO
recording audio
RW_TYPE_VIDEO
recording video
Function Documentation
create_stop_button()
static GtkWidget * create_stop_button (void) static
Create "Stop" button.
Create a Stop button with an icon, reduced in size.
Returns
GtkButton
Referenced by statusbar_recording_widget_create().
hide_all_timer_callback()
static gboolean hide_all_timer_callback (gpointer data) static
Timer callback for the hide_all() method.
Parameters
[in,out] data recording widget
Returns
FALSE to delete the timer source
Referenced by statusbar_recording_widget_hide_all().
on_stop_clicked()
static void on_stop_clicked (GtkWidget * button, gpointer data) static
Event handler for the 'clicked' event of the STOP button.
Stops all recordings.
Parameters
[in,out] button button triggering the event
[in,out] data statusbar recording widget (GtkGrid)
Referenced by statusbar_recording_widget_create().
statusbar_recording_widget_create()
GtkWidget * statusbar_recording_widget_create (void)
Create recording status widget.
Generate a widget to show on the statusbar to display recording state.
Returns
GtkGrid
gtk_widget_set_hexpand(label, TRUE);
Referenced by ui_statusbar_create().
statusbar_recording_widget_hide_all()
void statusbar_recording_widget_hide_all (GtkWidget * widget, guint timeout)
Clear the labels and hide the button after timeout seconds.
Use a timeout of 0 to immediately clear the labels and hide the button, skipping timer setup.
Parameters
[in,out] widget recording widget
[in] timeout timeout in seconds
Referenced by on_stop_clicked(), and ui_media_stop_recording().
statusbar_recording_widget_set_event_playback()
void statusbar_recording_widget_set_event_playback (GtkWidget * widget, char * version)
Set event playback status.
Parameters
[in,out] widget statusbar recording status widget
[in] version VICE version major.minor string during playback, NULL when playback is done
Referenced by ui_display_playback().
statusbar_recording_widget_set_recording_status()
void statusbar_recording_widget_set_recording_status (GtkWidget * widget, int status)
Set recording status.
Sets the type of recording and the status (ie 'Recording $rec-type or 'Recording stopped).
Note
Somehow getting the recording state of events doesn't work yet, so that currently displays 'inactive'.
Parameters
[in,out] widget statusbar recording status widget
[in] status recording status (boolean)
Todo:
FIXME: sound_is_recording() returns false when using the UI, it uses a variable that only gets set when using command-line options. Triggering the recording from the UI doesn't set the variable but does set the related resource, which I use in the function used to update the UI display.
So this needs some serious refactoring.
Referenced by ui_display_recording().
statusbar_recording_widget_set_time()
void statusbar_recording_widget_set_time (GtkWidget * widget, unsigned int current, unsigned int total)
Update recording/playback time display.
Parameters
[in,out] widget recording widget
[in] current current time in seconds
[in] total total time in seconds
Note
total only makes sense when replaying events. I could make the time display '–:–' when total is 0, but it it possible, though unlikely, we're replaying a sequence of events which take less than a second.
Todo:
FIXME: Determining the recording status/type is currently very flaky. When triggering a recording from the UI the variables that should indicate the recording type aren't set yet. So for now we have to check them in this timer callback. Also the sound recording status function is broken in src/sound.c.
Referenced by ui_display_event_time(), and update_timer().
update_timer()
static gboolean update_timer (gpointer data) static
Callback for the g_timeout.
Parameters
[in,out] data statusbar recording widget
Returns
boolean (TRUE == keep running, FALSE == delete timer source)
Referenced by statusbar_recording_widget_set_recording_status().
Variable Documentation
rec_types
const gchar* rec_types[] static
Initial value:
= {
    "inactive",
    "events",
    "audio",
    "video"
}
Types of recordings as strings.
Referenced by statusbar_recording_widget_set_recording_status(), and statusbar_recording_widget_set_time().
timeout_id
guint timeout_id = 0 static
GSource id of the timeout to hide the recording button.
Referenced by statusbar_recording_widget_hide_all(), and statusbar_recording_widget_set_recording_status().