vsid: printerdrv/drv-nl10.c File Reference
drv-nl10.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "driver-select.h"
#include "drv-nl10.h"
#include "log.h"
#include "output-select.h"
#include "output.h"
#include "palette.h"
#include "printer.h"
#include "sysfile.h"
#include "types.h"
#include "lib.h"
#include "userport.h"
Data Structures
struct nl10_s
Macros
#define DBG(x)
#define BORDERX 16
MAX_COL must be a multiple of 32.
#define BORDERY 2
#define MAX_COL (80 * 30 + 2 * BORDERX)
#define MAX_ROW (66 * 48 + 2 * BORDERY)
#define BUF_ROW (4 * 4 * 9 + 1)
#define CHARSET_SIZE 200
#define NL10_ROM_SIZE 0x8000
#define NL10_NLQ 0x00001
#define NL10_ELITE 0x00002
#define NL10_CONDENSED 0x00004
#define NL10_EXPANDED 0x00008
#define NL10_EXPANDED_LINE 0x00010
#define NL10_UNDERLINE 0x00020
#define NL10_SUPERSCRIPT 0x00040
#define NL10_SUBSCRIPT 0x00080
#define NL10_ITALIC 0x00100
#define NL10_BOLD 0x00200
#define NL10_EMPHASIZE 0x00400
#define NL10_PROP 0x00800
#define NL10_USERAM 0x01000
#define NL10_ASCII 0x02000
#define NL10_CBMTEXT 0x04000
#define NL10_REVERSE 0x08000
#define NL10_QUOTED 0x10000
#define NL10_ZERO_CROSSED 0x20000
#define NL10_GFX_OFF 0x00
#define NL10_GFX_SINGLE 0x01
#define NL10_GFX_DOUBLE 0x02
#define NL10_GFX_QUAD 0x03
#define NL10_GFX_CRT 0x04
#define NL10_GFX_PLOT 0x05
#define NL10_GFX_CRT2 0x06
#define NL10_GFX_REVERSE 0x40
#define NL10_GFX_7PIN 0x80
#define NL10_ESCBUF_SIZE 60
#define valid_xpos(X) ((X) >= 0 && (X) < MAX_COL)
#define valid_ypos(Y) ((Y) >= 0 && (Y) < BUF_ROW)
#define valid_pos(X, Y) (valid_xpos(X) && valid_ypos(Y))
Typedefs
typedef struct nl10_s nl10_t
Functions
static int drv_nl10_init_charset (void)
static int handle_control_sequence (nl10_t *nl10, unsigned int prnr, const uint8_t c)
static int handle_esc_control_sequence (nl10_t *nl10, unsigned int prnr, const uint8_t c)
static void set_mode (nl10_t *nl10, unsigned int m)
NL-10 printer engine.
static void del_mode (nl10_t *nl10, unsigned int m)
static int is_mode (nl10_t *nl10, unsigned int m)
static uint8_t * get_char_data (nl10_t *nl10, uint8_t c)
static double get_char_width (nl10_t *nl10, uint8_t c, int no_prop)
static void init_mapping (nl10_t *nl10, int intl)
static void reset (nl10_t *nl10)
static void reset_hard (nl10_t *nl10)
static int store_char (uint8_t *dest, const uint8_t *src)
static int store_char_nlq (uint8_t *dest, const uint8_t *src)
static int inc_y (nl10_t *nl10)
static void linefeed (nl10_t *nl10, unsigned int prnr)
static void output_buf (nl10_t *nl10, unsigned int prnr)
static void formfeed (nl10_t *nl10, unsigned int prnr)
static void draw_point2 (nl10_t *nl10, int x, int y)
static void draw_point3 (nl10_t *nl10, int x, int y)
static void draw_char_nlq (nl10_t *nl10, const uint8_t c)
static void draw_char_draft (nl10_t *nl10, const uint8_t c)
static void draw_char_draft_reverse (nl10_t *nl10, const uint8_t c)
static void draw_char (nl10_t *nl10, const uint8_t c)
static void draw_graphics (nl10_t *nl10, uint8_t c)
static void print_char (nl10_t *nl10, unsigned int prnr, const uint8_t c)
static int drv_nl10_open (unsigned int prnr, unsigned int secondary)
Interface to the upper layer.
static void drv_nl10_close (unsigned int prnr, unsigned int secondary)
static int drv_nl10_putc (unsigned int prnr, unsigned int secondary, uint8_t b)
static int drv_nl10_getc (unsigned int prnr, unsigned int secondary, uint8_t *b)
static int drv_nl10_flush (unsigned int prnr, unsigned int secondary)
static int drv_nl10_formfeed (unsigned int prnr)
static int drv_nl10_select (unsigned int prnr)
int drv_nl10_init_resources (void)
int drv_nl10_init (void)
void drv_nl10_shutdown (void)
void drv_nl10_reset (void)
Variables
static palette_t * palette = NULL
static log_t drvnl10_log = ((log_t)-1)
Logging goes here.
static uint8_t drv_nl10_rom [0x8000]
static uint8_t * drv_nl10_charset = drv_nl10_rom
static uint8_t drv_nl10_charset_nlq [200 *47]
static uint8_t drv_nl10_charset_nlq_italic [200 *47]
static const uint8_t drv_nl10_charset_mapping_intl [3][8][14]
character data and mappings
static const uint8_t drv_nl10_charset_mapping [3][256]
static nl10_t drv_nl10 [4]
Macro Definition Documentation
BORDERX
#define BORDERX 16
MAX_COL must be a multiple of 32.
2432 x 3172
BORDERY
#define BORDERY 2
BUF_ROW
#define BUF_ROW (4 * 4 * 9 + 1)
CHARSET_SIZE
#define CHARSET_SIZE 200
DBG
#define DBG (x)
MAX_COL
#define MAX_COL (80 * 30 + 2 * BORDERX)
MAX_ROW
#define MAX_ROW (66 * 48 + 2 * BORDERY)
NL10_ASCII
#define NL10_ASCII 0x02000
NL10_BOLD
#define NL10_BOLD 0x00200
NL10_CBMTEXT
#define NL10_CBMTEXT 0x04000
NL10_CONDENSED
#define NL10_CONDENSED 0x00004
NL10_ELITE
#define NL10_ELITE 0x00002
NL10_EMPHASIZE
#define NL10_EMPHASIZE 0x00400
NL10_ESCBUF_SIZE
#define NL10_ESCBUF_SIZE 60
NL10_EXPANDED
#define NL10_EXPANDED 0x00008
NL10_EXPANDED_LINE
#define NL10_EXPANDED_LINE 0x00010
NL10_GFX_7PIN
#define NL10_GFX_7PIN 0x80
NL10_GFX_CRT
#define NL10_GFX_CRT 0x04
NL10_GFX_CRT2
#define NL10_GFX_CRT2 0x06
NL10_GFX_DOUBLE
#define NL10_GFX_DOUBLE 0x02
NL10_GFX_OFF
#define NL10_GFX_OFF 0x00
NL10_GFX_PLOT
#define NL10_GFX_PLOT 0x05
NL10_GFX_QUAD
#define NL10_GFX_QUAD 0x03
NL10_GFX_REVERSE
#define NL10_GFX_REVERSE 0x40
NL10_GFX_SINGLE
#define NL10_GFX_SINGLE 0x01
NL10_ITALIC
#define NL10_ITALIC 0x00100
NL10_NLQ
#define NL10_NLQ 0x00001
NL10_PROP
#define NL10_PROP 0x00800
NL10_QUOTED
#define NL10_QUOTED 0x10000
NL10_REVERSE
#define NL10_REVERSE 0x08000
NL10_ROM_SIZE
#define NL10_ROM_SIZE 0x8000
NL10_SUBSCRIPT
#define NL10_SUBSCRIPT 0x00080
NL10_SUPERSCRIPT
#define NL10_SUPERSCRIPT 0x00040
NL10_UNDERLINE
#define NL10_UNDERLINE 0x00020
NL10_USERAM
#define NL10_USERAM 0x01000
NL10_ZERO_CROSSED
#define NL10_ZERO_CROSSED 0x20000
valid_pos
#define valid_pos (X, Y) (valid_xpos(X) && valid_ypos(Y))
valid_xpos
#define valid_xpos (X) ((X) >= 0 && (X) < MAX_COL)
valid_ypos
#define valid_ypos (Y) ((Y) >= 0 && (Y) < BUF_ROW)
Typedef Documentation
nl10_t
typedef struct nl10_s nl10_t
Function Documentation
del_mode()
static void del_mode (nl10_t * nl10, unsigned int m) inline static
Referenced by drv_nl10_open(), handle_control_sequence(), handle_esc_control_sequence(), and print_char().
draw_char()
static void draw_char (nl10_t * nl10, const uint8_t c) static
Referenced by print_char().
draw_char_draft()
static void draw_char_draft (nl10_t * nl10, const uint8_t c) static
Referenced by draw_char().
draw_char_draft_reverse()
static void draw_char_draft_reverse (nl10_t * nl10, const uint8_t c) static
Referenced by draw_char().
draw_char_nlq()
static void draw_char_nlq (nl10_t * nl10, const uint8_t c) static
Referenced by draw_char().
draw_graphics()
static void draw_graphics (nl10_t * nl10, uint8_t c) static
Referenced by handle_control_sequence(), and print_char().
draw_point2()
static void draw_point2 (nl10_t * nl10, int x, int y) inline static
Referenced by draw_char_draft(), draw_char_draft_reverse(), draw_char_nlq(), and draw_graphics().
draw_point3()
static void draw_point3 (nl10_t * nl10, int x, int y) inline static
Referenced by draw_char_draft(), draw_char_draft_reverse(), draw_char_nlq(), and draw_graphics().
drv_nl10_close()
static void drv_nl10_close (unsigned int prnr, unsigned int secondary) static
Referenced by drv_nl10_init_resources().
drv_nl10_flush()
static int drv_nl10_flush (unsigned int prnr, unsigned int secondary) static
Referenced by drv_nl10_init_resources().
drv_nl10_formfeed()
static int drv_nl10_formfeed (unsigned int prnr) static
Referenced by drv_nl10_init_resources().
drv_nl10_getc()
static int drv_nl10_getc (unsigned int prnr, unsigned int secondary, uint8_t * b) static
Referenced by drv_nl10_init_resources().
drv_nl10_init()
int drv_nl10_init (void)
< serial dev 4, 5, 6 and user port
Referenced by printer_init().
drv_nl10_init_charset()
static int drv_nl10_init_charset (void) static
Referenced by drv_nl10_init().
drv_nl10_init_resources()
int drv_nl10_init_resources (void)
Referenced by printer_resources_init().
drv_nl10_open()
static int drv_nl10_open (unsigned int prnr, unsigned int secondary) static
Interface to the upper layer.
Referenced by drv_nl10_init_resources(), and drv_nl10_select().
drv_nl10_putc()
static int drv_nl10_putc (unsigned int prnr, unsigned int secondary, uint8_t b) static
Referenced by drv_nl10_init_resources().
drv_nl10_reset()
void drv_nl10_reset (void)
< serial dev 4, 5, 6 and user port
Referenced by printer_reset().
drv_nl10_select()
static int drv_nl10_select (unsigned int prnr) static
Referenced by drv_nl10_init_resources().
drv_nl10_shutdown()
void drv_nl10_shutdown (void)
< serial dev 4, 5, 6 and user port
Referenced by printer_shutdown().
formfeed()
static void formfeed (nl10_t * nl10, unsigned int prnr) static
Referenced by create_printer_widget(), drv_nl10_formfeed(), handle_control_sequence(), and print_char().
get_char_data()
static uint8_t * get_char_data (nl10_t * nl10, uint8_t c) static
Referenced by draw_char_draft(), draw_char_draft_reverse(), draw_char_nlq(), and get_char_width().
get_char_width()
static double get_char_width (nl10_t * nl10, uint8_t c, int no_prop) static
Referenced by handle_control_sequence(), handle_esc_control_sequence(), and print_char().
handle_control_sequence()
static int handle_control_sequence (nl10_t * nl10, unsigned int prnr, const uint8_t c) static
Referenced by print_char().
handle_esc_control_sequence()
static int handle_esc_control_sequence (nl10_t * nl10, unsigned int prnr, const uint8_t c) static
Referenced by handle_control_sequence().
inc_y()
static int inc_y (nl10_t * nl10) inline static
Referenced by linefeed().
init_mapping()
static void init_mapping (nl10_t * nl10, int intl) static
Referenced by drv_nl10_open(), handle_control_sequence(), and handle_esc_control_sequence().
is_mode()
static int is_mode (nl10_t * nl10, unsigned int m) inline static
Referenced by draw_char(), draw_char_draft(), draw_char_draft_reverse(), draw_char_nlq(), get_char_data(), get_char_width(), handle_control_sequence(), handle_esc_control_sequence(), init_mapping(), and print_char().
linefeed()
static void linefeed (nl10_t * nl10, unsigned int prnr) static
Referenced by handle_control_sequence(), handle_esc_control_sequence(), and print_char().
output_buf()
static void output_buf (nl10_t * nl10, unsigned int prnr) static
Referenced by formfeed().
print_char()
static void print_char (nl10_t * nl10, unsigned int prnr, const uint8_t c) static
Referenced by drv_nl10_putc(), handle_esc_control_sequence(), and print_char().
reset()
static void reset (nl10_t * nl10) static
Referenced by handle_esc_control_sequence(), and reset_hard().
reset_hard()
static void reset_hard (nl10_t * nl10) static
Referenced by drv_nl10_init(), and drv_nl10_reset().
set_mode()
static void set_mode (nl10_t * nl10, unsigned int m) inline static
NL-10 printer engine.
Referenced by drv_nl10_open(), handle_control_sequence(), handle_esc_control_sequence(), and print_char().
store_char()
static int store_char (uint8_t * dest, const uint8_t * src) static
Referenced by handle_esc_control_sequence().
store_char_nlq()
static int store_char_nlq (uint8_t * dest, const uint8_t * src) static
Referenced by handle_esc_control_sequence().
Variable Documentation
drv_nl10
nl10_t drv_nl10[4] static
Referenced by drv_nl10_formfeed(), drv_nl10_init(), drv_nl10_open(), drv_nl10_putc(), drv_nl10_reset(), drv_nl10_shutdown(), and output_buf().
drv_nl10_charset
uint8_t* drv_nl10_charset = drv_nl10_rom static
Referenced by drv_nl10_init_charset(), get_char_data(), and handle_esc_control_sequence().
drv_nl10_charset_mapping
static const uint8_t drv_nl10_charset_mapping static
Referenced by init_mapping().
drv_nl10_charset_mapping_intl
static const uint8_t drv_nl10_charset_mapping_intl static
Initial value:
=
{
    {
        {  0x23, 0x24, 0x40, 0x5b, 0x5c, 0x5d, 0x7b, 0x7c, 0x7d, 0x7e, 0x81, 0x82, 0x83, 0x84},
        {  0x23, 0x24, 0x40, 0x5b, 0x5c, 0x5d, 0x7b, 0x7c, 0x7d, 0x7e, 0x7b, 0x7c, 0x7d, 0x7e},
        {  0x23, 0x24, 0x10, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x11, 0x1a, 0x1b, 0x1c, 0x11},
        {  0x23, 0x24, 0x40, 0x12, 0x14, 0x0d, 0x13, 0x15, 0x0e, 0x7e, 0x13, 0x15, 0x0e, 0x7e},
        {  0x23, 0x24, 0x00, 0x05, 0x0f, 0x10, 0x1e, 0x02, 0x01, 0x16, 0x1e, 0x02, 0x01, 0x16},
        {  0x23, 0x0b, 0x1d, 0x17, 0x18, 0x0d, 0x1a, 0x1b, 0x0e, 0x1c, 0x1a, 0x1b, 0x0e, 0x1c},
        {  0x23, 0x24, 0x40, 0x05, 0x5c, 0x1e, 0x00, 0x03, 0x01, 0x04, 0x00, 0x03, 0x01, 0x04},
        {  0x0c, 0x24, 0x40, 0x07, 0x09, 0x08, 0x16, 0x0a, 0x7d, 0x7e, 0x16, 0x0a, 0x7d, 0x7e},
    },
    {
        {  0x23, 0x24, 0x40, 0x5b, 0x06, 0x5d, 0xa1, 0xa2, 0xa3, 0xa4, 0xa1, 0xa2, 0xa3, 0xa4},
        {  0x23, 0x24, 0x40, 0x5b, 0x5c, 0x5d, 0xa1, 0xa2, 0xa3, 0xa4, 0xa1, 0xa2, 0xa3, 0xa4},
        {  0x23, 0x24, 0x10, 0x17, 0x18, 0x19, 0xa1, 0xa2, 0xa3, 0xa4, 0xa1, 0xa2, 0xa3, 0xa4},
        {  0x23, 0x24, 0x40, 0x12, 0x14, 0x0d, 0xa1, 0xa2, 0xa3, 0xa4, 0xa1, 0xa2, 0xa3, 0xa4},
        {  0x23, 0x24, 0x00, 0x05, 0x0f, 0x10, 0xa1, 0xa2, 0xa3, 0xa4, 0xa1, 0xa2, 0xa3, 0xa4},
        {  0x23, 0x0b, 0x1d, 0x17, 0x18, 0x0d, 0xa1, 0xa2, 0xa3, 0xa4, 0xa1, 0xa2, 0xa3, 0xa4},
        {  0x23, 0x24, 0x40, 0x05, 0x5c, 0x1e, 0xa1, 0xa2, 0xa3, 0xa4, 0xa1, 0xa2, 0xa3, 0xa4},
        {  0x0c, 0x24, 0x40, 0x07, 0x09, 0x08, 0xa1, 0xa2, 0xa3, 0xa4, 0xa1, 0xa2, 0xa3, 0xa4},
    },
    {
        {  0x23, 0x24, 0x40, 0x5b, 0x06, 0x5d, 0x81, 0x82, 0x83, 0x84, 0x81, 0x82, 0x83, 0x84},
        {  0x23, 0x24, 0x40, 0x5b, 0x5c, 0x5d, 0x7b, 0x7c, 0x7d, 0x7e, 0x7b, 0x7c, 0x7d, 0x7e},
        {  0x23, 0x24, 0x10, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x11, 0x1a, 0x1b, 0x1c, 0x11},
        {  0x23, 0x24, 0x40, 0x12, 0x14, 0x0d, 0x13, 0x15, 0x0e, 0x7e, 0x13, 0x15, 0x0e, 0x7e},
        {  0x23, 0x24, 0x00, 0x05, 0x0f, 0x10, 0x1e, 0x02, 0x01, 0x16, 0x1e, 0x02, 0x01, 0x16},
        {  0x23, 0x0b, 0x1d, 0x17, 0x18, 0x0d, 0x1a, 0x1b, 0x0e, 0x1c, 0x1a, 0x1b, 0x0e, 0x1c},
        {  0x23, 0x24, 0x40, 0x05, 0x5c, 0x1e, 0x00, 0x03, 0x01, 0x04, 0x00, 0x03, 0x01, 0x04},
        {  0x0c, 0x24, 0x40, 0x07, 0x09, 0x08, 0x16, 0x0a, 0x7d, 0x7e, 0x16, 0x0a, 0x7d, 0x7e},
    }
}
character data and mappings
Referenced by init_mapping().
drv_nl10_charset_nlq
uint8_t drv_nl10_charset_nlq[200 *47] static
Referenced by drv_nl10_init_charset(), get_char_data(), and handle_esc_control_sequence().
drv_nl10_charset_nlq_italic
uint8_t drv_nl10_charset_nlq_italic[200 *47] static
Referenced by drv_nl10_init_charset(), and get_char_data().
drv_nl10_rom
uint8_t drv_nl10_rom[0x8000] static
Referenced by drv_nl10_init_charset(), and print_char().
drvnl10_log
log_t drvnl10_log = ((log_t)-1) static
Logging goes here.
Referenced by drv_nl10_init(), drv_nl10_init_charset(), handle_control_sequence(), handle_esc_control_sequence(), store_char(), and store_char_nlq().
palette
palette_t* palette = NULL static
Referenced by drv_nl10_init(), drv_nl10_open(), and drv_nl10_shutdown().