vsid: printerdrv/drv-raw.c File Reference
drv-raw.c File Reference
#include "vice.h"
#include "driver-select.h"
#include "drv-raw.h"
#include "log.h"
#include "output-select.h"
#include "output.h"
#include "printer.h"
#include "types.h"
#include "userport.h"
Macros
#define DBG(x)
Functions
static int drv_raw_open (unsigned int prnr, unsigned int secondary)
static void drv_raw_close (unsigned int prnr, unsigned int secondary)
static int drv_raw_putc (unsigned int prnr, unsigned int secondary, uint8_t b)
static int drv_raw_getc (unsigned int prnr, unsigned int secondary, uint8_t *b)
static int drv_raw_flush (unsigned int prnr, unsigned int secondary)
static int drv_raw_formfeed (unsigned int prnr)
static int drv_raw_select (unsigned int prnr)
int drv_raw_init_resources (void)
void drv_raw_init (void)
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
drv_raw_close()
static void drv_raw_close (unsigned int prnr, unsigned int secondary) static
Referenced by drv_raw_init_resources().
drv_raw_flush()
static int drv_raw_flush (unsigned int prnr, unsigned int secondary) static
Referenced by drv_raw_init_resources().
drv_raw_formfeed()
static int drv_raw_formfeed (unsigned int prnr) static
Referenced by drv_raw_init_resources().
drv_raw_getc()
static int drv_raw_getc (unsigned int prnr, unsigned int secondary, uint8_t * b) static
Referenced by drv_raw_init_resources().
drv_raw_init()
void drv_raw_init (void)
Referenced by printer_init().
drv_raw_init_resources()
int drv_raw_init_resources (void)
Referenced by printer_resources_init().
drv_raw_open()
static int drv_raw_open (unsigned int prnr, unsigned int secondary) static
Referenced by drv_raw_init_resources(), and drv_raw_select().
drv_raw_putc()
static int drv_raw_putc (unsigned int prnr, unsigned int secondary, uint8_t b) static
Referenced by drv_raw_init_resources().
drv_raw_select()
static int drv_raw_select (unsigned int prnr) static
Referenced by drv_raw_init_resources().