x128: drive/drivesync.c File Reference
drivesync.c File Reference
#include "vice.h"
#include <math.h>
#include "drive.h"
#include "drivesync.h"
#include "drivetypes.h"
#include "rotation.h"
Functions
static void drive_sync_cpu_set_factor (diskunit_context_t *drv, unsigned int sf)
void drivesync_factor (struct diskunit_context_s *drv)
void drive_set_machine_parameter (long cycles_per_sec)
void drivesync_set_1571 (struct diskunit_context_s *drv, int new_sync)
void drivesync_set_4000 (struct diskunit_context_s *drv, int new_sync)
void drivesync_clock_frequency (diskunit_context_t *unit, unsigned int type)
Variables
static unsigned int sync_factor
Function Documentation
drive_set_machine_parameter()
void drive_set_machine_parameter (long cycles_per_sec)
Referenced by machine_change_timing().
drive_sync_cpu_set_factor()
static void drive_sync_cpu_set_factor (diskunit_context_t * drv, unsigned int sf) static
Referenced by drivesync_factor().
drivesync_clock_frequency()
void drivesync_clock_frequency (diskunit_context_t * unit, unsigned int type)
< ASCII for HD
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
Referenced by drive_init(), and drive_set_disk_drive_type().
drivesync_factor()
void drivesync_factor (struct diskunit_context_s * drv)
Referenced by drive_init(), drive_set_disk_drive_type(), drive_set_machine_parameter(), drivesync_set_1571(), and drivesync_set_4000().
drivesync_set_1571()
void drivesync_set_1571 (struct diskunit_context_s * drv, int new_sync)
Referenced by store_pra(), and undump_pra().
drivesync_set_4000()
void drivesync_set_4000 (struct diskunit_context_s * drv, int new_sync)
Referenced by pc8477_setup_context().
Variable Documentation
sync_factor
unsigned int sync_factor static
Referenced by drive_set_machine_parameter(), drive_snapshot_read_module(), drive_snapshot_write_module(), and drivesync_factor().