x128: monitor/mon_register.h File Reference
mon_register.h File Reference
Data Structures
struct mon_reg_list_s
Macros
#define MON_REGISTER_IS_FLAGS
bits for mon_reg_list_t->flags
#define MON_REGISTER_IS_MEMORY
Typedefs
typedef struct mon_reg_list_s mon_reg_list_t
Functions
void mon_register6502_init (struct monitor_cpu_type_s *monitor_cpu_type)
CPU specific functions.
void mon_register6502dtv_init (struct monitor_cpu_type_s *monitor_cpu_type)
void mon_registerR65C02_init (struct monitor_cpu_type_s *monitor_cpu_type)
void mon_register65816_init (struct monitor_cpu_type_s *monitor_cpu_type)
void mon_registerz80_init (struct monitor_cpu_type_s *monitor_cpu_type)
void mon_register6809_init (struct monitor_cpu_type_s *monitor_cpu_type)
int mon_register_valid (int mem, int reg_id)
common functions
int mon_register_name_to_id (int mem, char *name)
takes a register by name, and returns its id.
int mon_register_name_valid (int mem, char *name)
checks if a given string is a valid register name, returns 1 on valid, 0 on invalid
int mon_register_id_to_value (int mem, int reg_id)
takes a register by id, and returns its value.
int mon_register_name_to_value (int mem, char *name)
takes a register by name, and returns its value.
Macro Definition Documentation
MON_REGISTER_IS_FLAGS
#define MON_REGISTER_IS_FLAGS
Value:
                                           0x01    /* register contains flags and will be
                                           printed as bits */
bits for mon_reg_list_t->flags
MON_REGISTER_IS_MEMORY
#define MON_REGISTER_IS_MEMORY
Value:
                                           0x02    /* memory mapped register, extra contains
                                           the memory address */
Typedef Documentation
mon_reg_list_t
typedef struct mon_reg_list_s mon_reg_list_t
Function Documentation
mon_register6502_init()
void mon_register6502_init (struct monitor_cpu_type_s * monitor_cpu_type)
CPU specific functions.
Referenced by asm6502_init().
mon_register6502dtv_init()
void mon_register6502dtv_init (struct monitor_cpu_type_s * monitor_cpu_type)
Referenced by asm6502dtv_init().
mon_register65816_init()
void mon_register65816_init (struct monitor_cpu_type_s * monitor_cpu_type)
Referenced by asm65816_init().
mon_register6809_init()
void mon_register6809_init (struct monitor_cpu_type_s * monitor_cpu_type)
Referenced by asm6809_init().
mon_register_id_to_value()
int mon_register_id_to_value (int mem, int reg_id)
takes a register by id, and returns its value.
returns -1 on error
Referenced by mon_register_name_to_value().
mon_register_name_to_id()
int mon_register_name_to_id (int mem, char * name)
takes a register by name, and returns its id.
returns -1 on error
Referenced by mon_register_name_to_value(), and mon_register_name_valid().
mon_register_name_to_value()
int mon_register_name_to_value (int mem, char * name)
takes a register by name, and returns its value.
returns -1 on error
Referenced by mon_symbol_table_lookup_addr().
mon_register_name_valid()
int mon_register_name_valid (int mem, char * name)
checks if a given string is a valid register name, returns 1 on valid, 0 on invalid
Referenced by mon_add_name_to_symbol_table(), and mon_symbol_table_lookup_addr().
mon_register_valid()
int mon_register_valid (int mem, int reg_id)
common functions
checks if a given register id is valid, returns 1 on valid, 0 on invalid
common functions
Referenced by mon_register_id_to_value(), and monitor_binary_process_registers_set().
mon_registerR65C02_init()
void mon_registerR65C02_init (struct monitor_cpu_type_s * monitor_cpu_type)
Referenced by asmR65C02_init().
mon_registerz80_init()
void mon_registerz80_init (struct monitor_cpu_type_s * monitor_cpu_type)
Referenced by asmz80_init().