x128: profiler.c File Reference
profiler.c File Reference
#include "vice.h"
#include <assert.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>
#include "lib.h"
#include "mem.h"
#include "profiler.h"
#include "profiler_data.h"
Macros
#define MAX_CALLSTACK_SIZE 129
Functions
profiling_context_t * profile_context_by_id (int id)
int get_context_id (profiling_context_t *context)
static void callstack_push (uint16_t pc_dst, uint16_t pc_src, uint8_t sp)
push pc to callstack (triggered by interrupt or JSR)
static void callstack_pop_check (uint8_t sp)
check if we should pop the callstack
static profiling_page_t * alloc_profiling_page (void)
profiling_context_t * alloc_profiling_context (void)
void free_profiling_context (profiling_context_t *data)
profiling_page_t * profiling_get_page (profiling_context_t *ctx, uint8_t page)
profiling_context_t * get_mem_config_context (profiling_context_t *main_context, uint16_t mem_config)
static profiling_context_t * get_child_context (profiling_context_t *parent, uint16_t pc_dst, uint16_t pc_src, uint16_t mem_config)
static void initialize_context (void)
store profiling samples
void profile_sample_start (uint16_t pc)
called by the CPU for each instruction
void profile_sample_finish (uint16_t cycle_time, uint16_t stolen_cycles)
void profile_jsr (uint16_t pc_dst, uint16_t pc_src, uint8_t sp)
called whenever a JSR is encountered
void profile_int (uint16_t pc_dst, uint16_t handler, uint8_t sp, uint16_t cycle_time)
void profile_rtx (uint8_t sp)
called whenever an RTS/RI is called
void profile_start (void)
resets sample statistics and starts profiling sample collection
void compute_aggregate_stats (profiling_context_t *context)
void profile_stop (void)
stops profiling and writes profiling log to disk
static void profile_reset (void)
void profile_shutdown (void)
Variables
uint16_t callstack_pc_dst [129]
uint16_t callstack_pc_src [129]
uint8_t callstack_sp [129]
uint16_t callstack_memory_bank_config [129]
unsigned callstack_size = 0
bool context_dirty = true
bool maincpu_profiling = false
bool entered_context = false
(fragile) flags if the current command is a JSR/INT or RTS/RTI
bool exited_context = false
profiling_context_t * root_context = NULL
profiling_context_t * current_context = NULL
uint16_t current_pc
int num_context_ids = 0
int context_id_capacity = 0
profiling_context_t ** id_to_context = NULL
Macro Definition Documentation
MAX_CALLSTACK_SIZE
#define MAX_CALLSTACK_SIZE 129
Function Documentation
alloc_profiling_context()
profiling_context_t * alloc_profiling_context (void)
Referenced by array_compact(), get_child_context(), get_mem_config_context(), profile_start(), recursively_aggregate_all_functions(), and recursively_aggregate_matching_functions().
alloc_profiling_page()
static profiling_page_t * alloc_profiling_page (void) static
Referenced by profiling_get_page().
callstack_pop_check()
static void callstack_pop_check (uint8_t sp) static
check if we should pop the callstack
Referenced by profile_rtx().
callstack_push()
static void callstack_push (uint16_t pc_dst, uint16_t pc_src, uint8_t sp) static
push pc to callstack (triggered by interrupt or JSR)
Todo:
move out to interface?
Referenced by profile_int(), and profile_jsr().
compute_aggregate_stats()
void compute_aggregate_stats (profiling_context_t * context)
Referenced by compute_aggregate_stats(), and init_profiling_data().
free_profiling_context()
void free_profiling_context (profiling_context_t * data)
Referenced by free_aggregate_stats(), free_profiling_context(), merge_all_memory_configs(), mon_profile_flat(), mon_profile_func(), profile_reset(), and profile_start().
get_child_context()
static profiling_context_t * get_child_context (profiling_context_t * parent, uint16_t pc_dst, uint16_t pc_src, uint16_t mem_config) static
Referenced by initialize_context().
get_context_id()
int get_context_id (profiling_context_t * context)
Referenced by print_all_contexts(), and print_context_id().
get_mem_config_context()
profiling_context_t * get_mem_config_context (profiling_context_t * main_context, uint16_t mem_config)
Referenced by initialize_context(), and merge_aggregate_contexts().
initialize_context()
static void initialize_context (void) static
store profiling samples
Referenced by profile_sample_start().
profile_context_by_id()
profiling_context_t * profile_context_by_id (int id)
Referenced by mon_profile_disass_context(), and mon_profile_graph().
profile_int()
void profile_int (uint16_t pc_dst, uint16_t handler, uint8_t sp, uint16_t cycle_time)
profile_jsr()
void profile_jsr (uint16_t pc_dst, uint16_t pc_src, uint8_t sp)
called whenever a JSR is encountered
profile_reset()
static void profile_reset (void) static
Referenced by profile_shutdown().
profile_rtx()
void profile_rtx (uint8_t sp)
called whenever an RTS/RI is called
profile_sample_finish()
void profile_sample_finish (uint16_t cycle_time, uint16_t stolen_cycles)
Referenced by profile_int().
profile_sample_start()
void profile_sample_start (uint16_t pc)
called by the CPU for each instruction
Referenced by if(), and profile_int().
profile_shutdown()
void profile_shutdown (void)
Referenced by machine_shutdown().
profile_start()
void profile_start (void)
resets sample statistics and starts profiling sample collection
Referenced by mon_profile_action().
profile_stop()
void profile_stop (void)
stops profiling and writes profiling log to disk
Referenced by mon_profile_action().
profiling_get_page()
profiling_page_t * profiling_get_page (profiling_context_t * ctx, uint8_t page)
Referenced by compute_aggregate_stats(), merge_aggregate_contexts(), merge_all_pages(), and profile_sample_finish().
Variable Documentation
callstack_memory_bank_config
uint16_t callstack_memory_bank_config[129]
Referenced by callstack_push(), initialize_context(), and mon_backtrace().
callstack_pc_dst
uint16_t callstack_pc_dst[129]
Referenced by callstack_push(), initialize_context(), and mon_backtrace().
callstack_pc_src
uint16_t callstack_pc_src[129]
Referenced by callstack_push(), initialize_context(), and mon_backtrace().
callstack_size
unsigned callstack_size = 0
Referenced by callstack_pop_check(), callstack_push(), initialize_context(), and mon_backtrace().
callstack_sp
uint8_t callstack_sp[129]
Referenced by callstack_pop_check(), callstack_push(), and mon_backtrace().
context_dirty
bool context_dirty = true
Referenced by callstack_pop_check(), callstack_push(), profile_sample_start(), and profile_start().
context_id_capacity
int context_id_capacity = 0
Referenced by get_context_id(), and profile_reset().
current_context
profiling_context_t* current_context = NULL
Referenced by initialize_context(), print_context_graph(), profile_reset(), profile_sample_finish(), profile_sample_start(), and profile_start().
current_pc
uint16_t current_pc
Referenced by profile_sample_finish(), and profile_sample_start().
entered_context
bool entered_context = false
(fragile) flags if the current command is a JSR/INT or RTS/RTI
Referenced by profile_int(), profile_jsr(), profile_sample_start(), and profile_start().
exited_context
bool exited_context = false
Referenced by profile_rtx(), profile_sample_start(), and profile_start().
id_to_context
profiling_context_t** id_to_context = NULL
Referenced by get_context_id(), profile_context_by_id(), and profile_reset().
maincpu_profiling
bool maincpu_profiling = false
Referenced by mon_profile(), mon_profile_action(), profile_int(), profile_start(), and profile_stop().
num_context_ids
int num_context_ids = 0
Referenced by get_context_id(), profile_context_by_id(), profile_reset(), and profile_start().
root_context
profiling_context_t* root_context = NULL
Referenced by init_profiling_data(), initialize_context(), mon_profile(), mon_profile_clear(), mon_profile_disass(), mon_profile_flat(), mon_profile_func(), mon_profile_graph(), profile_reset(), and profile_start().