x128: video/video-resources.c File Reference
video-resources.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "videoarch.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "video-color.h"
#include "video.h"
#include "viewport.h"
#include "util.h"
#include "ui.h"
Data Structures
struct video_resource_chip_mode_s
Per chip resources.
Macros
#define DEBUG_VIDEO 1
#define DBG(_x_) log_debug _x_
#define FULLSCREENCUSTOMWIDTH_DEFAULT 640
#define FULLSCREENCUSTOMHEIGHT_DEFAULT 480
#define RES_CHIP_MODE_MAX (2*4)
assume max 2 videochips, 4 fullscreen devices
Typedefs
typedef struct video_resource_chip_mode_s video_resource_chip_mode_t
Functions
int video_resources_init (void)
global resources.
void video_resources_shutdown (void)
static int set_double_size_enabled (int double_size, video_canvas_t *canvas)
Setter for boolean resource "${CHIP}DoubleSize".
static int set_double_scan_enabled (int double_scan, void *canvas)
Setter for the boolean resource "${CHIP}DoubleScan".
static int set_chip_rendermode (int filter, void *canvas)
Setter for integer resource "${CHIP}Filter".
static int set_fullscreen_enabled (int enabled, void *canvas)
Setter for the boolean resource "CHIPFullscreen".
static int set_fullscreen_mode (int val, void *param)
static int set_fullscreen_custom_width (int w, void *canvas)
<CHIP>FullscreenCustomWidth (SDL only)
static int set_fullscreen_custom_height (int h, void *canvas)
<CHIP>FullscreenCustomHeight (SDL only)
static int set_palette_is_external (int external, void *canvas)
Setter for the boolean resource "${CHIP}ExternalPalette".
static int set_palette_file_name (const char *filename, void *canvas)
Setter for the resource "${CHIP}PaletteFile".
static int set_aspect_mode (int mode, void *canvas)
Setter for the integer resource "${CHIP}AspectMode".
static int set_aspect_ratio (const char *val, void *canvas)
Setter for the resource "${CHIP}AspectRatio".
static int set_glfilter (int val, void *canvas)
static int set_flipx (int val, void *canvas)
static int set_flipy (int val, void *canvas)
static int set_rotate (int val, void *canvas)
static int set_vsync (int val, void *canvas)
static int set_color_saturation (int val, void *param)
static int set_color_contrast (int val, void *param)
static int set_color_brightness (int val, void *param)
static int set_color_gamma (int val, void *param)
static int set_color_tint (int val, void *param)
static int set_pal_scanlineshade (int val, void *param)
static int set_pal_oddlinesphase (int val, void *param)
static int set_pal_oddlinesoffset (int val, void *param)
static int set_pal_blur (int val, void *param)
static int set_delaylinetype (int val, void *param)
static int set_audioleak (int val, void *param)
static int set_show_statusbar (int show_statusbar, void *canvas)
Setter for the boolean resource "${CHIP}ShowStatusbar".
static video_resource_chip_mode_t * get_resource_chip_mode (void)
static void shutdown_resource_chip_mode (void)
int video_resources_chip_init (const char *chipname, struct video_canvas_s **canvas, video_chip_cap_t *video_chip_cap)
void video_resources_chip_shutdown (struct video_canvas_s *canvas)
Variables
static resource_int_t resources_chip_double_size []
Resource init template for "${CHIP}DoubleSize".
static resource_int_t resources_chip_scan []
Resource registration template for "${CHIP}DoubleScan".
static resource_int_t resources_chip_rendermode []
Resource registration template for "${CHIP}Filter".
static resource_int_t resources_chip_fullscreen_int []
Resource registration template for "${CHIP}Fullscreen".
static const char *const vname_chip_fullscreen_mode [] = { "FullscreenMode", NULL }
<CHIP>FullscreenMode (SDL only)
static resource_int_t resources_chip_fullscreen_mode []
static const char *const vname_chip_fullscreen_size []
static resource_int_t resources_chip_fullscreen_size []
static resource_string_t resources_chip_palette_string []
Resource registration template for "${CHIP}PaletteFile".
static resource_int_t resources_chip_palette_int []
Resource registration template for "${CHIP}ExternalPalette".
static const char *const vname_chip_gloptions_int []
static resource_int_t resources_chip_gloptions_int []
Resource registration template for "${CHIP}AspectMode".
static resource_string_t resources_chip_gloptions_string []
Resource registration template for "${CHIP}AspectRatio".
static const char *const vname_chip_colors []
static resource_int_t resources_chip_colors []
static const char *const vname_chip_crtemu []
static resource_int_t resources_chip_crtemu []
static const char *const vname_chip_crtemu_palntsc []
static resource_int_t resources_chip_crtemu_palntsc []
static resource_int_t resources_chip_show_statusbar []
Resource registration template for CHIPShowStatusbar.
static video_resource_chip_mode_t * resource_chip_modes [(2 *4)]
static int resource_chip_modes_num = 0
Macro Definition Documentation
DBG
#define DBG (_x_) log_debug _x_
DEBUG_VIDEO
#define DEBUG_VIDEO 1
FULLSCREENCUSTOMHEIGHT_DEFAULT
#define FULLSCREENCUSTOMHEIGHT_DEFAULT 480
FULLSCREENCUSTOMWIDTH_DEFAULT
#define FULLSCREENCUSTOMWIDTH_DEFAULT 640
RES_CHIP_MODE_MAX
#define RES_CHIP_MODE_MAX (2*4)
assume max 2 videochips, 4 fullscreen devices
Typedef Documentation
video_resource_chip_mode_t
typedef struct video_resource_chip_mode_s video_resource_chip_mode_t
Function Documentation
get_resource_chip_mode()
static video_resource_chip_mode_t * get_resource_chip_mode (void) static
< assume max 2 videochips, 4 fullscreen devices
Referenced by video_resources_chip_init().
set_aspect_mode()
static int set_aspect_mode (int mode, void * canvas) static
Setter for the integer resource "${CHIP}AspectMode".
Parameters
[in] mode aspect mode
[in] canvas video canvas
Returns
0
set_aspect_ratio()
static int set_aspect_ratio (const char * val, void * canvas) static
Setter for the resource "${CHIP}AspectRatio".
Parameters
[in] string ratio
[in] canvas video canvas
Returns
0
set_audioleak()
static int set_audioleak (int val, void * param) static
Referenced by video_resources_chip_init().
set_chip_rendermode()
static int set_chip_rendermode (int filter, void * canvas) static
Setter for integer resource "${CHIP}Filter".
Sets the "render mode" to VIDEO_FILTER_NONE, VIDEO_FILTER_CRT or VIDEO_FILTER_SCALE2X.
Parameters
[in] filter filter to use
[in] canvas video canvas
Returns
0 on success, -1 on failure
!
Todo:
FIXME: Function name does not match the resource name at all!
Referenced by video_resources_chip_init().
set_color_brightness()
static int set_color_brightness (int val, void * param) static
Referenced by video_resources_chip_init().
set_color_contrast()
static int set_color_contrast (int val, void * param) static
Referenced by video_resources_chip_init().
set_color_gamma()
static int set_color_gamma (int val, void * param) static
Referenced by video_resources_chip_init().
set_color_saturation()
static int set_color_saturation (int val, void * param) static
Referenced by video_resources_chip_init().
set_color_tint()
static int set_color_tint (int val, void * param) static
Referenced by video_resources_chip_init().
set_delaylinetype()
static int set_delaylinetype (int val, void * param) static
Referenced by video_resources_chip_init().
set_double_scan_enabled()
static int set_double_scan_enabled (int double_scan, void * canvas) static
Setter for the boolean resource "${CHIP}DoubleScan".
Parameters
[in] double_scan enable double scan
[in] canvas video canvas
Returns
0
Referenced by video_resources_chip_init().
set_double_size_enabled()
static int set_double_size_enabled (int double_size, video_canvas_t * canvas) static
Setter for boolean resource "${CHIP}DoubleSize".
Parameters
[in] double_size enable double size rendering
[in] canvas video canvas
Returns
0 on success, -1 on failure
Referenced by video_resources_chip_init().
set_flipx()
static int set_flipx (int val, void * canvas) static
set_flipy()
static int set_flipy (int val, void * canvas) static
set_fullscreen_custom_height()
static int set_fullscreen_custom_height (int h, void * canvas) static
<CHIP>FullscreenCustomHeight (SDL only)
set_fullscreen_custom_width()
static int set_fullscreen_custom_width (int w, void * canvas) static
<CHIP>FullscreenCustomWidth (SDL only)
set_fullscreen_enabled()
static int set_fullscreen_enabled (int enabled, void * canvas) static
Setter for the boolean resource "CHIPFullscreen".
Parameters
[in] enabled full screen enabled (bool)
[in] canvas video canvas reference
Returns
0 on success, -1 on failure
Referenced by video_resources_chip_init().
set_fullscreen_mode()
static int set_fullscreen_mode (int val, void * param) static
Todo:
Remove device from the API: turn fullscreen_mode[] into an integer etc.
Referenced by video_resources_chip_init().
set_glfilter()
static int set_glfilter (int val, void * canvas) static
set_pal_blur()
static int set_pal_blur (int val, void * param) static
Referenced by video_resources_chip_init().
set_pal_oddlinesoffset()
static int set_pal_oddlinesoffset (int val, void * param) static
Referenced by video_resources_chip_init().
set_pal_oddlinesphase()
static int set_pal_oddlinesphase (int val, void * param) static
Referenced by video_resources_chip_init().
set_pal_scanlineshade()
static int set_pal_scanlineshade (int val, void * param) static
Referenced by video_resources_chip_init().
set_palette_file_name()
static int set_palette_file_name (const char * filename, void * canvas) static
Setter for the resource "${CHIP}PaletteFile".
Parameters
[in] filename palette filename
[in] canvas video canvas
Returns
0
Referenced by video_resources_chip_init().
set_palette_is_external()
static int set_palette_is_external (int external, void * canvas) static
Setter for the boolean resource "${CHIP}ExternalPalette".
Parameters
[in] external use external palette
[in] canvas video canvas
Returns
0
Referenced by video_resources_chip_init().
set_rotate()
static int set_rotate (int val, void * canvas) static
set_show_statusbar()
static int set_show_statusbar (int show_statusbar, void * canvas) static
Setter for the boolean resource "${CHIP}ShowStatusbar".
Parameters
[in] show_statusbar show status bar in the UI
[in] canvas video canvas reference
Returns
0 (success)
set_vsync()
static int set_vsync (int val, void * canvas) static
shutdown_resource_chip_mode()
static void shutdown_resource_chip_mode (void) static
Referenced by video_resources_chip_shutdown().
video_resources_chip_init()
int video_resources_chip_init (const char * chipname, struct video_canvas_s ** canvas, video_chip_cap_t * video_chip_cap)
Todo:
perhaps we should not do this and let the user decide about cranking up brightness/saturation/contrast if needed?
Referenced by raster_resources_chip_init().
video_resources_chip_shutdown()
void video_resources_chip_shutdown (struct video_canvas_s * canvas)
Referenced by raster_resources_chip_shutdown().
video_resources_init()
int video_resources_init (void)
global resources.
Referenced by machine_video_resources_init().
video_resources_shutdown()
void video_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
Variable Documentation
resource_chip_modes
video_resource_chip_mode_t* resource_chip_modes[(2 *4)] static
Referenced by get_resource_chip_mode(), and shutdown_resource_chip_mode().
resource_chip_modes_num
int resource_chip_modes_num = 0 static
Referenced by get_resource_chip_mode(), and shutdown_resource_chip_mode().
resources_chip_colors
resource_int_t resources_chip_colors[] static
Initial value:
=
{
    { NULL, 1000, RES_EVENT_NO, NULL,
      NULL, set_color_saturation, NULL },
    { NULL, 1000, RES_EVENT_NO, NULL,
      NULL, set_color_contrast, NULL },
    { NULL, 1000, RES_EVENT_NO, NULL,
      NULL, set_color_brightness, NULL },
    { NULL, 1000, RES_EVENT_NO, NULL,
      NULL, set_color_gamma, NULL },
    { NULL, 1000, RES_EVENT_NO, NULL,
      NULL, set_color_tint, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Todo:
we should have different sets of defaults per video mode
Referenced by video_resources_chip_init().
resources_chip_crtemu
resource_int_t resources_chip_crtemu[] static
Initial value:
=
{
    { NULL, 750, RES_EVENT_NO, NULL,
      NULL, set_pal_scanlineshade, NULL },
    { NULL, 500, RES_EVENT_NO, NULL,
      NULL, set_pal_blur, NULL },
    { NULL, 0, RES_EVENT_NO, NULL,
      NULL, set_audioleak, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by video_resources_chip_init().
resources_chip_crtemu_palntsc
resource_int_t resources_chip_crtemu_palntsc[] static
Initial value:
=
{
    { NULL, 1500, RES_EVENT_NO, NULL,
      NULL, set_pal_oddlinesphase, NULL },
    { NULL, 500, RES_EVENT_NO, NULL,
      NULL, set_pal_oddlinesoffset, NULL },
    { NULL, 0, RES_EVENT_NO, NULL,
      NULL, set_delaylinetype, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by video_resources_chip_init().
resources_chip_double_size
resource_int_t resources_chip_double_size[] static
Initial value:
=
{
    { NULL, 0, RES_EVENT_NO, NULL,
      NULL, set_double_size_enabled, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Resource init template for "${CHIP}DoubleSize".
Referenced by video_resources_chip_init().
resources_chip_fullscreen_int
resource_int_t resources_chip_fullscreen_int[] static
Initial value:
=
{
    { NULL, 0, RES_EVENT_NO, NULL,
      NULL, set_fullscreen_enabled, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Resource registration template for "${CHIP}Fullscreen".
Referenced by video_resources_chip_init().
resources_chip_fullscreen_mode
resource_int_t resources_chip_fullscreen_mode[] static
Initial value:
=
{
    { NULL, 0, RES_EVENT_NO, NULL,
      NULL, set_fullscreen_mode, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by video_resources_chip_init().
resources_chip_fullscreen_size
resource_int_t resources_chip_fullscreen_size[] static
Initial value:
=
{
    { NULL,  640 , RES_EVENT_NO, NULL,
      NULL, set_fullscreen_custom_width, NULL },
    { NULL,  480 , RES_EVENT_NO, NULL,
      NULL, set_fullscreen_custom_height, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by video_resources_chip_init().
resources_chip_gloptions_int
resource_int_t resources_chip_gloptions_int[] static
Initial value:
=
{
    { NULL,  2 , RES_EVENT_NO, NULL, NULL, set_aspect_mode, NULL },
    { NULL,  2 , RES_EVENT_NO, NULL, NULL, set_glfilter, NULL },
    { NULL, 0                     , RES_EVENT_NO, NULL, NULL, set_flipx, NULL },
    { NULL, 0                     , RES_EVENT_NO, NULL, NULL, set_flipy, NULL },
    { NULL, 0                     , RES_EVENT_NO, NULL, NULL, set_rotate, NULL },
    { NULL, 1                     , RES_EVENT_NO, NULL, NULL, set_vsync, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Resource registration template for "${CHIP}AspectMode".
Referenced by video_resources_chip_init().
resources_chip_gloptions_string
resource_string_t resources_chip_gloptions_string[] static
Initial value:
=
{
    { NULL, NULL, RES_EVENT_NO, NULL,
      NULL, set_aspect_ratio, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Resource registration template for "${CHIP}AspectRatio".
Referenced by video_resources_chip_init().
resources_chip_palette_int
resource_int_t resources_chip_palette_int[] static
Initial value:
=
{
    { NULL, 0, RES_EVENT_NO, NULL,
      NULL, set_palette_is_external, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Resource registration template for "${CHIP}ExternalPalette".
Referenced by video_resources_chip_init().
resources_chip_palette_string
resource_string_t resources_chip_palette_string[] static
Initial value:
=
{
    { NULL, NULL, RES_EVENT_NO, NULL,
      NULL, set_palette_file_name, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Resource registration template for "${CHIP}PaletteFile".
Referenced by video_resources_chip_init().
resources_chip_rendermode
resource_int_t resources_chip_rendermode[] static
Initial value:
=
{
    { NULL,  1 , RES_EVENT_NO, NULL,
      NULL, set_chip_rendermode, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Resource registration template for "${CHIP}Filter".
Referenced by video_resources_chip_init().
resources_chip_scan
resource_int_t resources_chip_scan[] static
Initial value:
=
{
    { NULL, 1, RES_EVENT_NO, NULL,
      NULL, set_double_scan_enabled, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Resource registration template for "${CHIP}DoubleScan".
Referenced by video_resources_chip_init().
resources_chip_show_statusbar
resource_int_t resources_chip_show_statusbar[] static
Initial value:
=
{
    { NULL,
       1 ,
      RES_EVENT_NO, NULL,
      NULL,
      set_show_statusbar,
      NULL
    },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Resource registration template for CHIPShowStatusbar.
Values are filled in during resource registration, dependent on CHIP and UI.
Referenced by video_resources_chip_init().
vname_chip_colors
const char* const vname_chip_colors[] static
Initial value:
= {
    "ColorSaturation",
    "ColorContrast",
    "ColorBrightness",
    "ColorGamma",
    "ColorTint",
    NULL }
Referenced by video_resources_chip_init().
vname_chip_crtemu
const char* const vname_chip_crtemu[] static
Initial value:
= {
    "PALScanLineShade",
    "PALBlur",
    "AudioLeak",
    NULL }
Referenced by video_resources_chip_init().
vname_chip_crtemu_palntsc
const char* const vname_chip_crtemu_palntsc[] static
Initial value:
= {
    "PALOddLinePhase",
    "PALOddLineOffset",
    "PALDelaylineType",
    NULL }
Referenced by video_resources_chip_init().
vname_chip_fullscreen_mode
const char* const vname_chip_fullscreen_mode[] = { "FullscreenMode", NULL } static
<CHIP>FullscreenMode (SDL only)
Referenced by video_resources_chip_init().
vname_chip_fullscreen_size
const char* const vname_chip_fullscreen_size[] static
Initial value:
= {
    "FullscreenCustomWidth",
    "FullscreenCustomHeight",
    NULL }
Referenced by video_resources_chip_init().
vname_chip_gloptions_int
const char* const vname_chip_gloptions_int[] static
Initial value:
= {
    "AspectMode",
    "GLFilter",
    "FlipX",
    "FlipY",
    "Rotate",
    "VSync",
    NULL }
Referenced by video_resources_chip_init().