x128: socket.c File Reference
socket.c File Reference
#include "vice.h"
#include <assert.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include "socketimpl.h"
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "vicesocket.h"
#include "signals.h"
#include <network.h>
Data Structures
struct in_addr
struct sockaddr
struct sockaddr_in
struct hostent
union socket_addresses_u
struct vice_network_socket_address_s
opaque structure describing an address for use with socket functions
struct vice_network_socket_s
opaque structure describing a socket
Macros
#define SOL_TCP IPPROTO_TCP
hopefully fixed in configure
#define arraysize(_x) (sizeof _x / sizeof _x[0])
determine the number of elements of an array
#define SOCK_STREAM 1
Access to socket addresses.
#define AF_INET 2
#define PF_INET AF_INET
#define IPPROTO_TCP 6
#define INADDR_ANY 0
Functions
static int get_new_pool_entry (unsigned int *PoolUsage)
Get the next free entry of a pool.
static vice_network_socket_t * vice_network_alloc_new_socket (SOCKET sockfd)
Get a free memory area for a socket.
static int socket_init (void)
Initialise networking.
static void initialize_socket_address (vice_network_socket_address_t *address)
Initialise a socket address structure.
static vice_network_socket_address_t * vice_network_alloc_new_socket_address (void)
Get a free memory area for a socket address.
vice_network_socket_t * vice_network_server (const vice_network_socket_address_t *server_address)
Open a socket and initialise it for server operation.
vice_network_socket_t * vice_network_client (const vice_network_socket_address_t *server_address)
Open a socket and initialise it for client operation.
static int vice_network_address_generate_ipv4 (vice_network_socket_address_t *socket_address, const char *address_string, unsigned short port)
Generate an IPv4 socket address.
static int vice_network_address_generate_ipv6 (vice_network_socket_address_t *socket_address, const char *address_string, unsigned short port)
Generate an IPv6 socket address.
vice_network_socket_address_t * vice_network_address_generate (const char *address_string, unsigned short port)
Generate a socket address.
void vice_network_address_close (vice_network_socket_address_t *address)
Return memory of a socket address.
vice_network_socket_t * vice_network_accept (vice_network_socket_t *sockfd)
Accept a connection on a listening socket.
int vice_network_socket_close (vice_network_socket_t *sockfd)
Close a socket.
int vice_network_send (vice_network_socket_t *sockfd, const void *buffer, size_t buffer_length, int flags)
Send data on a connected socket.
int vice_network_receive (vice_network_socket_t *sockfd, void *buffer, size_t buffer_length, int flags)
Receive data from a connected socket.
int vice_network_select_poll_one (vice_network_socket_t *readsockfd)
Check if a socket has incoming data to receive.
int vice_network_select_multiple (vice_network_socket_t **readsockfd)
Monitor multiple sockets.
int vice_network_get_errorcode (void)
Get the error of the last socket operation.
Variables
static vice_network_socket_address_t address_pool [16]
a memory pool for network addresses
static unsigned int address_pool_usage = 0
usage bit pattern for address_pool
static vice_network_socket_t socket_pool [16]
a memory pool for sockets
static unsigned int socket_pool_usage = 0
usage bit pattern for socket_pool
Detailed Description
Author
Spiro Trikaliotis
Abstraction from network sockets.
socket.c - Abstraction from network sockets.
Written by Spiro Trikaliotis spiro.nosp@m..tri.nosp@m.kalio.nosp@m.tis@.nosp@m.gmx.d.nosp@m.e Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
based on code from network.c written by Andreas Matthies andre.nosp@m.as.m.nosp@m.atthi.nosp@m.es@g.nosp@m.mx.ne.nosp@m.t
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Macro Definition Documentation
AF_INET
#define AF_INET 2
arraysize
#define arraysize (_x) (sizeof _x / sizeof _x[0])
determine the number of elements of an array
Parameters
_x The array of which the size is to be determined
Remarks
The count of elements of the array
Make sure to really pass an array, not a pointer, as _x
INADDR_ANY
#define INADDR_ANY 0
IPPROTO_TCP
#define IPPROTO_TCP 6
PF_INET
#define PF_INET AF_INET
SOCK_STREAM
#define SOCK_STREAM 1
Access to socket addresses.
This union is used to access socket addresses. It replaces the casts needed otherwise.
Furthermore, it ensures we have always enough memory for any type needed. (sizeof struct sockaddr_in6 is bigger than struct sockaddr).
Note, however, that there is no consensus if the C standard guarantees that all union members start at the same address. There are arguments for and against this.
However, in practice, this approach works.
SOL_TCP
#define SOL_TCP IPPROTO_TCP
hopefully fixed in configure
Function Documentation
get_new_pool_entry()
static int get_new_pool_entry (unsigned int * PoolUsage) static
Get the next free entry of a pool.
Parameters
PoolUsage Pointer to a bit pattern that contains the allocations of the pool.
Returns
The next free pool entry, or -1 if there is none left.
Remarks
A 1 bit marks a used pool entry, a 0 bit a free pool entry.
In the current implementation, this function is restricted to 16 entries.
Referenced by vice_network_alloc_new_socket(), and vice_network_alloc_new_socket_address().
initialize_socket_address()
static void initialize_socket_address (vice_network_socket_address_t * address) static
Initialise a socket address structure.
This function initialises a socket address structure.
Regardless of the structure was used before or not, after this call, the memory contents are as if the structure was never used before.
Parameters
address Pointer to the memory structure to initialise
Remarks
This function marks the memory structure as being used and initialises the length of the address field.
Referenced by vice_network_accept(), and vice_network_alloc_new_socket_address().
socket_init()
static int socket_init (void) static
Initialise networking.
This function initialises networking. It ensures that the initialisation is performed only once.
Returns
0 on success, else -1.
Remarks
If this function returns with an error, it is likely that all subsequent networking functions will fail.
Referenced by vice_network_client(), and vice_network_server().
vice_network_accept()
vice_network_socket_t * vice_network_accept (vice_network_socket_t * sockfd)
Accept a connection on a listening socket.
This function accepts a connection on a socket that has been opened with vice_network_server().
Parameters
sockfd The socket that has been oped with vice_network_server()
Returns
A new socket that can be used for transmission on this this connection.
Referenced by monitor_binary_data_available(), monitor_network_data_available(), network_hook(), and start_ffmpeg_executable().
vice_network_address_close()
void vice_network_address_close (vice_network_socket_address_t * address)
Return memory of a socket address.
This function returns a socket address to the memory pool of addresses.
Parameters
address A socket address that has been allocated by vice_network_alloc_new_socket_address() or by vice_network_address_generate().
Referenced by monitor_binary_activate(), monitor_network_activate(), network_connect_client(), network_start_server(), rs232net_open(), and vice_network_address_generate().
vice_network_address_generate()
vice_network_socket_address_t * vice_network_address_generate (const char * address_string, unsigned short port)
Generate a socket address.
Initialises a socket address with the value specified as input parameter.
Parameters
address_string A string describing the address to set.
port A default port number. If address_string does not specify a port number, the number here will be used. If address_string specifies a port number, that one will be used instead.
Returns
socket_address Pointer to a socket address that has been initialised to the specification in address_string (and port, if supported). NULL in case of an error.
Remarks
If address_string starts with a pipe ('|'), then the address_string is treated as a unix domain socket. Otherwise, address_string can be prepended with ip6:// or ip4://, in which case address_string is treated exactly as an IPv6 or IPv4 address, respectively.
If there is no specification, this routine tests for an IPv6 address. If this fails, it tries an IPv4 address.
Todo:
FIXME: "|" as first character indicates that we want to pipe through an external process - if we want to support unix domain socket, this has to use another syntax!
Referenced by monitor_binary_activate(), monitor_network_activate(), network_connect_client(), network_start_server(), rs232_is_physical_device(), rs232net_open(), and start_ffmpeg_executable().
vice_network_address_generate_ipv4()
static int vice_network_address_generate_ipv4 (vice_network_socket_address_t * socket_address, const char * address_string, unsigned short port) static
Generate an IPv4 socket address.
Initialises a socket address with an IPv4 address.
Parameters
socket_address Pointer to an empty socket address that will be initialized
address_string A string describing the address to set.
port A default port number. If address_string does not specify a port number, the number here will be used. If address_string specifies a port number, that one will be used instead.
Returns
0 on success, else an error occurred.
Remarks
address_string must be specified in the form <host> or <host>:<port> with <host> being the name or the IPv4 address of the host, and <port> being the port number. If the first form is used, the default port will be used.
Referenced by vice_network_address_generate().
vice_network_address_generate_ipv6()
static int vice_network_address_generate_ipv6 (vice_network_socket_address_t * socket_address, const char * address_string, unsigned short port) static
Generate an IPv6 socket address.
Initialises a socket address with an IPv6 address.
Parameters
socket_address Pointer to an empty socket address that will be initialized
address_string A string describing the address to set.
port A default port number. If address_string does not specify a port number, the number here will be used. If address_string specifies a port number, that one will be used instead.
Returns
0 on success, else an error occurred.
Remarks
address_string must be specified in one of the forms <host> or
with <hostname> being the name of the host, <hostipv6> being the IP of the host, and <host> being the name of the host or its IPv6, and <port> being the port number.
The extra braces [...] in case the port is specified are needed as IPv6 addresses themselves already contain colons, and it would be impossible to clearly distinguish between an IPv6 address, and an IPv6 address where a port has been specified. This format is a common one.
Remarks
On platforms which do not support IPv6, this function returns -1 as error.
Todo:
Specifying a port is not implemented yet.
Referenced by vice_network_address_generate().
vice_network_alloc_new_socket()
static vice_network_socket_t * vice_network_alloc_new_socket (SOCKET sockfd) static
Get a free memory area for a socket.
Parameters
sockfd socket handle as initialisation value.
Returns
NULL on error; else, a pointer to an empty vice_network_socket_t structure
Remarks
If not used anymore, the returned pointer must be freed with a call to vice_network_socket_close().
Referenced by vice_network_accept(), vice_network_client(), and vice_network_server().
vice_network_alloc_new_socket_address()
static vice_network_socket_address_t * vice_network_alloc_new_socket_address (void) static
Get a free memory area for a socket address.
Returns
NULL on error; else, a pointer to an empty vice_network_socket_address_t structure
Remarks
If not used anymore, the returned pointer must be freed with a call to vice_network_address_close().
Referenced by vice_network_address_generate().
vice_network_client()
vice_network_socket_t * vice_network_client (const vice_network_socket_address_t * server_address)
Open a socket and initialise it for client operation.
Parameters
server_address The address of the server to which to connect to.
Returns
0 on error; else, a handle to the socket on success.
Remarks
The server_address variable determines the type of socket to be used (IPv4, IPv6, Unix Domain Socket, ...)
Referenced by network_connect_client(), rs232net_open(), and start_ffmpeg_executable().
vice_network_get_errorcode()
int vice_network_get_errorcode (void)
Get the error of the last socket operation.
This function determines the error code for the last socket operation.
Returns
the error code
Remarks
It does not distinguish between different sockets, thus, make sure to call it directly after an erroneous socket operation. Furthermore, reading the error status does not reset the error code. Thus, do not expect correct results if the previous operation did not produce an error.
Todo:
Generate a mapping between WIN32 and Unix style error numbers
Referenced by _rs232net_getc(), and _rs232net_putc().
vice_network_receive()
int vice_network_receive (vice_network_socket_t * sockfd, void * buffer, size_t buffer_length, int flags)
Receive data from a connected socket.
This function receives incoming data from a connected socket. opened either by vice_network_client() or vice_network_accept().
Parameters
sockfd The connected socket to receive from
buffer Pointer to the buffer which will hold the received data
buffer_length The length of the buffer pointed to by buffer. This indicates the maximum number of bytes to receive.
flags Flags for the socket. These flags are architecture dependent.
Returns
the number of bytes received. This can be less than buffer_length.
When the return value is 0, either the other site has gracefully closed the socket (and all data has been received), or no data was received in the case of a non-blocking socket.
In case of an error, -1 is returned.
Referenced by _rs232net_getc(), monitor_binary_receive(), monitor_network_receive(), and network_recv_buffer().
vice_network_select_multiple()
int vice_network_select_multiple (vice_network_socket_t ** readsockfd)
Monitor multiple sockets.
This function blocks for many different connections and returns when any has data.
Parameters
readsockfd NULL terminated list of sockets to monitor
Returns
1 if the specified socket has data; 0 if it does not contain any data, and -1 in case of an error.
Referenced by uimon_in().
vice_network_select_poll_one()
int vice_network_select_poll_one (vice_network_socket_t * readsockfd)
Check if a socket has incoming data to receive.
This function is called in order to determine if there is data to be received on a socket. For a blocking socket, this is the only way to receive data without actually blocking.
Parameters
readsockfd The connected socket to test for data
Returns
1 if the specified socket has data; 0 if it does not contain any data, and -1 in case of an error.
Referenced by _rs232net_getc(), monitor_binary_data_available(), monitor_network_data_available(), network_hook(), and start_ffmpeg_executable().
vice_network_send()
int vice_network_send (vice_network_socket_t * sockfd, const void * buffer, size_t buffer_length, int flags)
Send data on a connected socket.
This function sends outgoing data to a connected socket. opened either by vice_network_client() or vice_network_accept().
Parameters
sockfd The connected socket to send to
buffer Pointer to the buffer which holds the data to send
buffer_length The length of the buffer pointed to by buffer.
flags Flags for the socket. These flags are architecture dependent.
Returns
the number of bytes send. For non-blocking sockets, this can be less than len. For blocking sockets (default), any return value different than len must be treated as an error.
Note
Amazing there's docs on this, but send() returns size_t, not int, so properly checking the return type could fail.
Referenced by _rs232net_putc(), ffmpegexe_soundmovie_encode(), monitor_binary_transmit(), monitor_network_transmit(), network_send_buffer(), write_initial_audio_frames(), and write_video_frame().
vice_network_server()
vice_network_socket_t * vice_network_server (const vice_network_socket_address_t * server_address)
Open a socket and initialise it for server operation.
Parameters
server_address The address of the server to which to bind to.
Returns
0 on error; else, a handle to the socket on success.
Remarks
The server_address variable determines the type of socket to be used (IPv4, IPv6, Unix Domain Socket, ...) Thus, server_address must not be NULL.
Referenced by monitor_binary_activate(), monitor_network_activate(), network_start_server(), start_ffmpeg_executable(), and vice_network_server().
vice_network_socket_close()
int vice_network_socket_close (vice_network_socket_t * sockfd)
Close a socket.
This function closes the socket that has been opened either by vice_network_server(), vice_network_client() or vice_network_accept().
Parameters
sockfd The socket to be closed
Returns
0 on success, else an error occurred.
Referenced by close_audio_stream(), close_stream(), close_video_stream(), monitor_binary_deactivate(), monitor_binary_quit(), monitor_network_deactivate(), monitor_network_quit(), network_connect_client(), network_disconnect(), and rs232net_closesocket().
Variable Documentation
address_pool
vice_network_socket_address_t address_pool[16] static
a memory pool for network addresses
Referenced by vice_network_address_close(), and vice_network_alloc_new_socket_address().
address_pool_usage
unsigned int address_pool_usage = 0 static
usage bit pattern for address_pool
Referenced by vice_network_address_close(), and vice_network_alloc_new_socket_address().
socket_pool
vice_network_socket_t socket_pool[16] static
a memory pool for sockets
Referenced by vice_network_alloc_new_socket(), and vice_network_socket_close().
socket_pool_usage
unsigned int socket_pool_usage = 0 static
usage bit pattern for socket_pool
Referenced by vice_network_alloc_new_socket(), and vice_network_socket_close().