x128: drive/rotation.c File Reference
rotation.c File Reference
#include "vice.h"
#include "drive.h"
#include "drivetypes.h"
#include "lib.h"
#include "rotation.h"
#include "types.h"
#include "p64.h"
#include <stdlib.h>
#include <math.h>
Data Structures
struct rotation_s
Macros
#define ACCUM_MAX 0x10000
#define ROTATION_TABLE_SIZE 0x1000
Typedefs
typedef struct rotation_s rotation_t
Functions
void rotation_init (int freq, unsigned int dnr)
void rotation_reset (drive_t *drive)
void rotation_speed_zone_set (unsigned int zone, unsigned int dnr)
void rotation_table_get (uint32_t *rotation_table_ptr)
void rotation_table_set (uint32_t *rotation_table_ptr)
void rotation_overflow_callback (CLOCK sub, unsigned int dnr)
static void write_next_bit (drive_t *dptr, int value)
static int read_next_bit (drive_t *dptr)
static int32_t RANDOM_nextInt (rotation_t *rptr)
static uint32_t RANDOM_nextUInt (rotation_t *rptr)
void rotation_begins (drive_t *dptr)
static void rotation_do_wobble (drive_t *dptr)
calculate wobble factor from the respective resources
static void rotation_1541_gcr (drive_t *dptr, CLOCK ref_cycles)
static void rotation_1541_gcr_cycle (drive_t *dptr)
static int rotation_p64_get_delta (drive_t *dptr)
Calculate delta to the next NRZI transition flux pulse.
static void rotation_1541_p64 (drive_t *dptr, CLOCK ref_cycles)
static void rotation_1541_p64_cycle (drive_t *dptr)
static void rotation_1541_simple (drive_t *dptr)
void rotation_rotate_disk (drive_t *dptr)
uint8_t rotation_sync_found (drive_t *dptr)
void rotation_byte_read (drive_t *dptr)
Variables
static rotation_t rotation [4]
static const unsigned int rot_speed_bps [2][4]
Speed (in bps) of the disk in the 4 disk areas.
Macro Definition Documentation
ACCUM_MAX
#define ACCUM_MAX 0x10000
ROTATION_TABLE_SIZE
#define ROTATION_TABLE_SIZE 0x1000
Typedef Documentation
rotation_t
typedef struct rotation_s rotation_t
Function Documentation
RANDOM_nextInt()
static int32_t RANDOM_nextInt (rotation_t * rptr) inline static
Referenced by rotation_1541_p64().
RANDOM_nextUInt()
static uint32_t RANDOM_nextUInt (rotation_t * rptr) inline static
Referenced by rotation_1541_gcr(), and rotation_1541_p64().
read_next_bit()
static int read_next_bit (drive_t * dptr) inline static
Referenced by rotation_1541_gcr().
rotation_1541_gcr()
static void rotation_1541_gcr (drive_t * dptr, CLOCK ref_cycles) static
Todo:
FIXME: code should take into account whether BYTE READY has been latched anywhere in the system or not and negate only the unlatched inputs. So we just leave it be for now
< chosen for the bit in the VIA2 PCR register
< chosen for the bit in the VIA2 PCR register
Referenced by rotation_1541_gcr_cycle().
rotation_1541_gcr_cycle()
static void rotation_1541_gcr_cycle (drive_t * dptr) static
Referenced by rotation_rotate_disk().
rotation_1541_p64()
static void rotation_1541_p64 (drive_t * dptr, CLOCK ref_cycles) static
Todo:
FIXME: RPM related resources "DriveXRPM" and "DriveXwobble" are ignored for p64
< chosen for the bit in the VIA2 PCR register
< chosen for the bit in the VIA2 PCR register
Referenced by rotation_1541_p64_cycle().
rotation_1541_p64_cycle()
static void rotation_1541_p64_cycle (drive_t * dptr) static
Referenced by rotation_rotate_disk().
rotation_1541_simple()
static void rotation_1541_simple (drive_t * dptr) static
< chosen for the bit in the VIA2 PCR register
< chosen for the bit in the VIA2 PCR register
Todo:
only if we introduced more than two 0 bits in a row
Referenced by rotation_rotate_disk().
rotation_begins()
void rotation_begins (drive_t * dptr)
Referenced by glue_pport_update(), and store_prb().
rotation_byte_read()
void rotation_byte_read (drive_t * dptr)
Referenced by read_pb(), and read_pra().
rotation_do_wobble()
static void rotation_do_wobble (drive_t * dptr) static
calculate wobble factor from the respective resources
Todo:
FIXME: we should introduce random deviation too
Referenced by rotation_rotate_disk().
rotation_init()
void rotation_init (int freq, unsigned int dnr)
Referenced by drive_init(), drive_set_disk_drive_type(), and drivesync_set_1571().
rotation_overflow_callback()
void rotation_overflow_callback (CLOCK sub, unsigned int dnr)
rotation_p64_get_delta()
static int rotation_p64_get_delta (drive_t * dptr) inline static
Calculate delta to the next NRZI transition flux pulse.
Todo:
FIXME: this is incorrect, see https://sourceforge.net/p/vice-emu/bugs/1305/
Referenced by rotation_1541_p64().
rotation_reset()
void rotation_reset (drive_t * drive)
Referenced by cpu_reset(), and drive_init().
rotation_rotate_disk()
void rotation_rotate_disk (drive_t * dptr)
< chosen for the bit in the VIA2 PB register
Referenced by drive_set_disk_drive_type(), drive_vsync_hook(), drivesync_set_1571(), glue1571_side_set(), glue_pport_update(), read_pc(), read_pra(), read_prb(), rotation_byte_read(), set_ca2(), set_cb2(), store_pb(), store_pc(), store_pcr(), store_pra(), store_prb(), and via2d_update_pcr().
rotation_speed_zone_set()
void rotation_speed_zone_set (unsigned int zone, unsigned int dnr)
Referenced by glue_pport_update(), store_prb(), and undump_prb().
rotation_sync_found()
uint8_t rotation_sync_found (drive_t * dptr)
Referenced by read_pc(), and read_prb().
rotation_table_get()
void rotation_table_get (uint32_t * rotation_table_ptr)
Referenced by drive_snapshot_write_module().
rotation_table_set()
void rotation_table_set (uint32_t * rotation_table_ptr)
Referenced by drive_snapshot_read_module().
write_next_bit()
static void write_next_bit (drive_t * dptr, int value) inline static
Referenced by rotation_1541_gcr(), and rotation_1541_simple().
Variable Documentation
rot_speed_bps
const unsigned int rot_speed_bps[2][4] static
Initial value:
= { { 250000, 266667, 285714, 307692 },
                                                  { 125000, 133333, 142857, 153846 } }
Speed (in bps) of the disk in the 4 disk areas.
Referenced by rotation_1541_simple().
rotation
rotation_t rotation[4] static
Referenced by rotation_1541_gcr(), rotation_1541_gcr_cycle(), rotation_1541_p64(), rotation_1541_p64_cycle(), rotation_1541_simple(), rotation_begins(), rotation_do_wobble(), rotation_init(), rotation_overflow_callback(), rotation_p64_get_delta(), rotation_reset(), rotation_speed_zone_set(), rotation_sync_found(), rotation_table_get(), and rotation_table_set().