vsid: arch/gtk3/widgets/sidmodelwidget.c File Reference
sidmodelwidget.c File Reference
Widget to select SID model.
#include "vice.h"
#include <gtk/gtk.h>
#include <glib/gstdio.h>
#include "sid.h"
#include "vice_gtk3.h"
#include "lib.h"
#include "resources.h"
#include "machine.h"
#include "machinemodelwidget.h"
#include "mixerwidget.h"
#include "sidmodelwidget.h"
Functions
static void sid_model_callback (GtkWidget *widget, int sid_type)
Extra callback for the SID type radio buttons.
GtkWidget * sid_model_widget_create (GtkWidget *machine_model_widget)
Create SID model widget.
void sid_model_widget_update (GtkWidget *widget, int model)
Update the SID model widget.
void sid_model_widget_sync (GtkWidget *widget)
Synchronize the widget with its resource.
void sid_model_widget_set_callback (GtkWidget *widget, void(*callback)(int))
Set extra callback to trigger when the model changes.
Variables
static const vice_gtk3_radiogroup_entry_t sid_models_none []
Empty list of SID models.
static const vice_gtk3_radiogroup_entry_t sid_models_c64 []
SID models used in the C64/C64SCPU, C128 and expanders for PET, VIC-20 and Plus/4.
static const vice_gtk3_radiogroup_entry_t sid_models_c64dtv []
SID models used in the C64DTV.
static const vice_gtk3_radiogroup_entry_t sid_models_cbm5x0 []
SID models used in the CBM-II 510/520 models.
static GtkWidget * machine_widget = NULL
Reference to the machine model widget.
Detailed Description
Widget to select SID model.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
sid_model_callback()
static void sid_model_callback (GtkWidget * widget, int sid_type) static
Extra callback for the SID type radio buttons.
Parameters
[in] widget radio button triggering the event
[in] sid_type SID type
Referenced by sid_model_widget_create().
sid_model_widget_create()
GtkWidget * sid_model_widget_create (GtkWidget * machine_model_widget)
Create SID model widget.
Creates a SID model widget, depending on machine_class. Also sets a callback to force an update of the 'machine model' widget.
Parameters
[in,out] machine_model_widget reference to machine model widget
Returns
GtkGrid
Referenced by create_c128_layout(), create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), create_vsid_layout(), and settings_sidcart_widget_create().
sid_model_widget_set_callback()
void sid_model_widget_set_callback (GtkWidget * widget, void(*)(int) callback)
Set extra callback to trigger when the model changes.
Parameters
[in] widget the SID model widget
[in] callback function to call on model change
Referenced by create_c128_layout(), create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), and create_cbm6x0_layout().
sid_model_widget_sync()
void sid_model_widget_sync (GtkWidget * widget)
Synchronize the widget with its resource.
Parameters
[in,out] widget SID model widget
sid_model_widget_update()
void sid_model_widget_update (GtkWidget * widget, int model)
Update the SID model widget.
Parameters
[in,out] widget SID model widget
[in] model SID model ID
Referenced by sid_model_widget_sync().
Variable Documentation
machine_widget
GtkWidget* machine_widget = NULL static
Reference to the machine model widget.
Used to update the widget when the SID model changes
Referenced by sid_model_widget_create().
sid_models_c64
const vice_gtk3_radiogroup_entry_t sid_models_c64[] static
Initial value:
= {
    { "6581",               SID_MODEL_6581 },
    { "8580",               SID_MODEL_8580 },
    { "8580 + digi boost",  SID_MODEL_8580D },
    { NULL,                 -1 }
}
SID models used in the C64/C64SCPU, C128 and expanders for PET, VIC-20 and Plus/4.
Referenced by sid_model_widget_create().
sid_models_c64dtv
const vice_gtk3_radiogroup_entry_t sid_models_c64dtv[] static
Initial value:
= {
    { "DTVSID (ReSID-DTV)", SID_MODEL_DTVSID },
    { "6581",               SID_MODEL_6581 },
    { "8580",               SID_MODEL_8580 },
    { "8580 + digi boost",  SID_MODEL_8580D },
    { NULL,                 -1 }
}
SID models used in the C64DTV.
Referenced by sid_model_widget_create().
sid_models_cbm5x0
const vice_gtk3_radiogroup_entry_t sid_models_cbm5x0[] static
Initial value:
= {
    { "6581",               SID_MODEL_6581 },
    { "8580",               SID_MODEL_8580 },
    { "8580 + digi boost",  SID_MODEL_8580D },
    { NULL,                 -1 }
}
SID models used in the CBM-II 510/520 models.
Referenced by sid_model_widget_create().
sid_models_none
const vice_gtk3_radiogroup_entry_t sid_models_none[] static
Initial value:
= {
    { NULL, -1 }
}
Empty list of SID models.
Referenced by sid_model_widget_create().