x128: arch/shared/archdep_fseeko.c File Reference
archdep_fseeko.c File Reference
Provides fseeko(3) replacement on systems that lack fseeko(3)
#include "vice.h"
#include "types.h"
#include <stdio.h>
#include "archdep_fseeko.h"
Functions
int archdep_fseeko (FILE *stream, off_t offset, int whence)
Set position in stream.
Detailed Description
Provides fseeko(3) replacement on systems that lack fseeko(3)
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
archdep_fseeko()
int archdep_fseeko (FILE * stream, off_t offset, int whence)
Set position in stream.
Set position in stream using a 64-bit signed type.
Parameters
[in] stream stream
Returns
0 on success, -1 otherwise
See also
fseeko(3)
Referenced by archdep_file_size(), ata_snapshot_read_module(), disk_image_check_for_dhd(), scsi_image_read(), scsi_image_write(), and seek_sector().