vsid: arch/gtk3/widgets/base/resourcecheckbutton.h File Reference
resourcecheckbutton.h File Reference
Check button bound to a resource - header.
#include <gtk/gtk.h>
Functions
GtkWidget * vice_gtk3_resource_check_button_new (const char *resource, const char *label)
Create check button to toggle resource.
GtkWidget * vice_gtk3_resource_check_button_new_sprintf (const char *fmt, const char *label,...)
Create check button to toggle a resource.
gboolean vice_gtk3_resource_check_button_set (GtkWidget *widget, gboolean value)
Set new value for widget.
gboolean vice_gtk3_resource_check_button_reset (GtkWidget *widget)
Reset widget to the state it was when it was created.
gboolean vice_gtk3_resource_check_button_factory (GtkWidget *widget)
Reset check button to factory state.
gboolean vice_gtk3_resource_check_button_sync (GtkWidget *widget)
Synchronize the widget state with its resource.
void vice_gtk3_resource_check_button_add_callback (GtkWidget *widget, void(*callback)(GtkWidget *, gboolean))
Add user callback to resource checkbutton.
Detailed Description
Check button bound to a resource - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
vice_gtk3_resource_check_button_add_callback()
void vice_gtk3_resource_check_button_add_callback (GtkWidget * widget, void(*)(GtkWidget *, gboolean) callback)
Add user callback to resource checkbutton.
Parameters
[in] widget resource checkbutton
[in] callback function to call when the checkbutton state changes
Referenced by create_c64dtv_layout(), create_double_size_widget(), and create_superpet_enable_widget().
vice_gtk3_resource_check_button_factory()
gboolean vice_gtk3_resource_check_button_factory (GtkWidget * widget)
Reset check button to factory state.
Parameters
[in,out] widget resource check button widget
Returns
TRUE if the resource was reset to its factory value
vice_gtk3_resource_check_button_new()
GtkWidget * vice_gtk3_resource_check_button_new (const char * resource, const char * label)
Create check button to toggle resource.
Creates a check button to toggle resource. Makes a heap-allocated copy of the resource name so initializing this widget with a constructed/temporary resource name works as well.
Parameters
[in] resource resource name
[in] label label of the check button (optional)
Note
The resource name is stored in the "ResourceName" property.
Returns
new check button
Referenced by cart_image_widget_append_check(), cbm2_ram_mapping_widget_create(), create_64kb_widget(), create_acia_enable_widget(), create_bios_image_layout(), create_c64dtv_layout(), create_card_image_layout(), create_card_layout(), create_cart_image_layout(), create_cart_image_widget(), create_cart_reset_widget(), create_confirm_on_exit_checkbox(), create_cpcf83_widget(), create_datasette_widget(), create_delay_layout(), create_eeprom_image_widget(), create_eeprom_layout(), create_fullscreen_decorations_widget(), create_georam_ioswap_widget(), create_go64_widget(), create_ide64_clockport_layout(), create_ide64_shortbus_layout(), create_ide64_usb_layout(), create_keyset_enable_checkbox(), create_layout(), create_opposite_enable_checkbox(), create_pause_on_settings_checkbox(), create_prg_layout(), create_ramcart_enable_widget(), create_reset_with_iec_widget(), create_rtc_58321a_save_widget(), create_rtc_ds1307_save_widget(), create_save_on_exit_checkbox(), create_sidcart_enable_widget(), create_sidcart_joy_widget(), create_superpet_enable_widget(), create_tapecart_widget(), drive_sound_widget_create(), ffmpeg_widget_create(), layout_add_bbrtc_widget(), layout_add_ps2mouse_widget(), layout_add_smartmouse_rtc_widget(), pet_diagnosticpin_widget_create(), plus4_acia_widget_create(), settings_autostart_widget_create(), settings_c128fullbanks_widget_create(), settings_c64dtvflash_widget_create(), settings_digimax_widget_create(), settings_ds12c887_widget_create(), settings_fsdevice_widget_create(), settings_host_display_widget_create(), settings_ieeeflash64_widget_create(), settings_keyboard_widget_create(), settings_monitor_widget_create(), settings_pethre_widget_create(), settings_petreu_widget_create(), settings_plus4_digiblaster_widget_create(), settings_ramlink_widget_create(), settings_retroreplay_widget_create(), settings_rom_widget_create(), settings_rrnetmk3_widget_create(), settings_sfxsoundexpander_widget_create(), settings_sfxsoundsampler_widget_create(), settings_sound_widget_create(), settings_supersnapshotv5_widget_create(), settings_vfli_widget_create(), settings_vicieee488_widget_create(), settings_vicioram_widget_create(), sid_sound_widget_create(), userport_rsinterface_widget_create(), v364_speech_widget_create(), and vice_gtk3_resource_check_button_new_sprintf().
vice_gtk3_resource_check_button_new_sprintf()
GtkWidget * vice_gtk3_resource_check_button_new_sprintf (const char * fmt, const char * label, ...)
Create check button to toggle a resource.
Creates a check button to toggle a resource. Makes a heap-allocated copy of the resource name so initializing this widget with a constructed/temporary resource name works as well. The resource name can be constructed with a printf() format string.
Parameters
[in] fmt resource name format string
[in] label label of the check button and optional printf args
Note
The resource name is stored in the "ResourceName" property.
Returns
new check button
Referenced by canvas_render_mirror_widget_create(), canvas_render_vsync_widget_create(), create_audio_leak_widget(), create_delayline_widget(), create_double_scan_widget(), create_double_size_widget(), create_drive_true_emulation_widget(), create_drive_virtual_device_widget(), create_ide64_device_widget(), create_iec_check_button(), create_p00_widget(), create_ram_check_button(), create_readonly_check_button(), create_rom_widget(), create_rs232_devices_widget(), create_rtc_check_button(), create_sprite_background_widget(), create_sprite_sprite_widget(), create_vert_stretch_widget(), create_virtual_device_check_button(), and create_vsp_bug_widget().
vice_gtk3_resource_check_button_reset()
gboolean vice_gtk3_resource_check_button_reset (GtkWidget * widget)
Reset widget to the state it was when it was created.
Parameters
[in,out] widget resource check button widget
Returns
bool
vice_gtk3_resource_check_button_set()
gboolean vice_gtk3_resource_check_button_set (GtkWidget * widget, gboolean value)
Set new value for widget.
Parameters
[in,out] widget resource check button widget
[in] value new value
Returns
TRUE
Referenced by on_rsinterface_changed(), vice_gtk3_resource_check_button_factory(), and vice_gtk3_resource_check_button_reset().
vice_gtk3_resource_check_button_sync()
gboolean vice_gtk3_resource_check_button_sync (GtkWidget * widget)
Synchronize the widget state with its resource.
Parameters
[in,out] widget resource check button
Returns
bool
Referenced by pet_superpet_enable_widget_sync(), plus4_acia_widget_sync(), render_filter_callback(), and v364_speech_widget_sync().