x128: drive/drivemem.c File Reference
drivemem.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cartio.h"
#include "ciad.h"
#include "drive.h"
#include "drivemem.h"
#include "driverom.h"
#include "drivetypes.h"
#include "ds1216e.h"
#include "log.h"
#include "machine-drive.h"
#include "mem.h"
#include "monitor.h"
#include "riot.h"
#include "tpid.h"
#include "types.h"
#include "via1d1541.h"
#include "via4000.h"
#include "viad.h"
#include "pc8477.h"
#include "wd1770.h"
#include "cmdhd.h"
Functions
static uint8_t drive_read_free (diskunit_context_t *drv, uint16_t address)
Common memory access.
static void drive_store_free (diskunit_context_t *drv, uint16_t address, uint8_t value)
static uint8_t drive_peek_free (diskunit_context_t *drv, uint16_t address)
static uint8_t drive_zero_read_watch (diskunit_context_t *drv, uint16_t addr)
Watchpoint memory access.
static void drive_zero_store_watch (diskunit_context_t *drv, uint16_t addr, uint8_t value)
static uint8_t drive_read_watch (diskunit_context_t *drv, uint16_t address)
static void drive_store_watch (diskunit_context_t *drv, uint16_t address, uint8_t value)
void drivemem_toggle_watchpoints (int flag, void *context)
void drivemem_set_func (drivecpud_context_t *cpud, unsigned int start, unsigned int stop, drive_read_func_t *read_func, drive_store_func_t *store_func, drive_peek_func_t *peek_func, uint8_t *base, uint32_t limit)
uint8_t drivemem_bank_read (int bank, uint16_t addr, void *context)
This is the external interface for banked memory access.
uint8_t drivemem_bank_peek (int bank, uint16_t addr, void *context)
used by monitor when sfx off
void drivemem_bank_store (int bank, uint16_t addr, uint8_t value, void *context)
void drivemem_bank_poke (int bank, uint16_t addr, uint8_t value, void *context)
used by monitor when sfx off
void drivemem_init (diskunit_context_t *unit)
mem_ioreg_list_t * drivemem_ioreg_list_get (void *context)
Variables
static drive_read_func_t * read_tab_watch [0x101]
static drive_store_func_t * store_tab_watch [0x101]
static int watchpoints_active = 0
Function Documentation
drive_peek_free()
static uint8_t drive_peek_free (diskunit_context_t * drv, uint16_t address) static
Referenced by drivemem_init().
drive_read_free()
static uint8_t drive_read_free (diskunit_context_t * drv, uint16_t address) static
Common memory access.
Referenced by drivemem_init().
drive_read_watch()
static uint8_t drive_read_watch (diskunit_context_t * drv, uint16_t address) static
Referenced by drivemem_init().
drive_store_free()
static void drive_store_free (diskunit_context_t * drv, uint16_t address, uint8_t value) static
Referenced by drivemem_init().
drive_store_watch()
static void drive_store_watch (diskunit_context_t * drv, uint16_t address, uint8_t value) static
Referenced by drivemem_init().
drive_zero_read_watch()
static uint8_t drive_zero_read_watch (diskunit_context_t * drv, uint16_t addr) static
Watchpoint memory access.
Referenced by drivemem_init().
drive_zero_store_watch()
static void drive_zero_store_watch (diskunit_context_t * drv, uint16_t addr, uint8_t value) static
Referenced by drivemem_init().
drivemem_bank_peek()
uint8_t drivemem_bank_peek (int bank, uint16_t addr, void * context)
used by monitor when sfx off
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
drivemem_bank_poke()
void drivemem_bank_poke (int bank, uint16_t addr, uint8_t value, void * context)
used by monitor when sfx off
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
drivemem_bank_read()
uint8_t drivemem_bank_read (int bank, uint16_t addr, void * context)
This is the external interface for banked memory access.
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
drivemem_bank_store()
void drivemem_bank_store (int bank, uint16_t addr, uint8_t value, void * context)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), and drivemem_bank_poke().
drivemem_init()
void drivemem_init (diskunit_context_t * unit)
Referenced by drive_snapshot_read_module(), drivecpu65c02_init(), drivecpu_init(), and set_drive_ram().
drivemem_ioreg_list_get()
mem_ioreg_list_t * drivemem_ioreg_list_get (void * context)
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
Todo:
FIXME: register dump function
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
Todo:
FIXME: register dump function
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
Todo:
FIXME: register dump function
< registered area contains no mirrors
< registered area contains no mirrors
Todo:
FIXME: register dump function
< registered area contains no mirrors
< registered area contains no mirrors
Todo:
FIXME: register dump function
< ASCII for HD
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
< registered area contains no mirrors
< registered area contains no mirrors
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
drivemem_set_func()
void drivemem_set_func (drivecpud_context_t * cpud, unsigned int start, unsigned int stop, drive_read_func_t * read_func, drive_store_func_t * store_func, drive_peek_func_t * peek_func, uint8_t * base, uint32_t limit)
Referenced by drivemem_init(), mem1551_init(), memiec_init(), and memieee_init().
drivemem_toggle_watchpoints()
void drivemem_toggle_watchpoints (int flag, void * context)
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
Variable Documentation
read_tab_watch
drive_read_func_t* read_tab_watch[0x101] static
Referenced by drivemem_init(), and drivemem_toggle_watchpoints().
store_tab_watch
drive_store_func_t* store_tab_watch[0x101] static
Referenced by drivemem_init(), and drivemem_toggle_watchpoints().
watchpoints_active
int watchpoints_active = 0 static
Referenced by drivemem_toggle_watchpoints().