x128: tapeport/tapeport.h File Reference
tapeport.h File Reference
#include "snapshot.h"
#include "types.h"
Data Structures
struct tapeport_device_s
This struct holds all the information about the tapeport devices.
struct tapeport_desc_s
Macros
#define TAPEPORT_PORT_1_MASK (1 << TAPEPORT_PORT_1)
#define TAPEPORT_PORT_2_MASK (1 << TAPEPORT_PORT_2)
#define TAPEPORT_PORT_ALL_MASK (TAPEPORT_PORT_1_MASK | TAPEPORT_PORT_2_MASK)
Typedefs
typedef struct tapeport_device_s tapeport_device_t
This struct holds all the information about the tapeport devices.
typedef struct tapeport_desc_s tapeport_desc_t
Enumerations
enum {
TAPEPORT_DEVICE_NONE = 0 ,
TAPEPORT_DEVICE_DATASETTE ,
TAPEPORT_DEVICE_CP_CLOCK_F83 ,
TAPEPORT_DEVICE_DTL_BASIC_DONGLE ,
TAPEPORT_DEVICE_SENSE_DONGLE ,
TAPEPORT_DEVICE_TAPE_DIAG_586220_HARNESS ,
TAPEPORT_DEVICE_TAPECART ,
TAPEPORT_MAX_DEVICES
}
enum {
TAPEPORT_DEVICE_TYPE_NONE = 0 ,
TAPEPORT_DEVICE_TYPE_TAPE ,
TAPEPORT_DEVICE_TYPE_STORAGE ,
TAPEPORT_DEVICE_TYPE_RTC ,
TAPEPORT_DEVICE_TYPE_DONGLE
}
enum {
TAPEPORT_PORT_1 = 0 ,
TAPEPORT_PORT_2 ,
TAPEPORT_MAX_PORTS
}
enum {
TAPEPORT_UNIT_1 = 1 ,
TAPEPORT_UNIT_2 = 2
}
Functions
int tapeport_device_register (int id, tapeport_device_t *device)
register a device to be used in the tapeport system
void tapeport_set_motor (int port, int flag)
void tapeport_toggle_write_bit (int port, int write_bit)
void tapeport_set_sense_out (int port, int sense)
void tapeport_powerup (void)
int tapeport_valid_port (int port)
void tapeport_trigger_flux_change (unsigned int on, int port)
void tapeport_set_tape_sense (int sense, int port)
void tapeport_set_write_in (int val, int port)
void tapeport_set_motor_in (int val, int port)
int tapeport_resources_init (int amount)
void tapeport_resources_shutdown (void)
int tapeport_cmdline_options_init (void)
void tapeport_enable (int val)
int tapeport_get_active_state (void)
tapeport_desc_t * tapeport_get_valid_devices (int port, int sort)
const char * tapeport_get_device_type_desc (int type)
int tapeport_snapshot_write_module (struct snapshot_s *s, int save_image)
int tapeport_snapshot_read_module (struct snapshot_s *s)
Macro Definition Documentation
TAPEPORT_PORT_1_MASK
#define TAPEPORT_PORT_1_MASK (1 << TAPEPORT_PORT_1)
TAPEPORT_PORT_2_MASK
#define TAPEPORT_PORT_2_MASK (1 << TAPEPORT_PORT_2)
TAPEPORT_PORT_ALL_MASK
#define TAPEPORT_PORT_ALL_MASK (TAPEPORT_PORT_1_MASK | TAPEPORT_PORT_2_MASK)
Typedef Documentation
tapeport_desc_t
typedef struct tapeport_desc_s tapeport_desc_t
tapeport_device_t
typedef struct tapeport_device_s tapeport_device_t
This struct holds all the information about the tapeport devices.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TAPEPORT_DEVICE_NONE
TAPEPORT_DEVICE_DATASETTE
TAPEPORT_DEVICE_CP_CLOCK_F83
TAPEPORT_DEVICE_DTL_BASIC_DONGLE
TAPEPORT_DEVICE_SENSE_DONGLE
TAPEPORT_DEVICE_TAPE_DIAG_586220_HARNESS
TAPEPORT_DEVICE_TAPECART
TAPEPORT_MAX_DEVICES
anonymous enum
anonymous enum
Enumerator
TAPEPORT_DEVICE_TYPE_NONE
TAPEPORT_DEVICE_TYPE_TAPE
TAPEPORT_DEVICE_TYPE_STORAGE
TAPEPORT_DEVICE_TYPE_RTC
TAPEPORT_DEVICE_TYPE_DONGLE
anonymous enum
anonymous enum
Enumerator
TAPEPORT_PORT_1
TAPEPORT_PORT_2
TAPEPORT_MAX_PORTS
anonymous enum
anonymous enum
Enumerator
TAPEPORT_UNIT_1
tape port 1 unit number
TAPEPORT_UNIT_2
tape port 2 unit number
Function Documentation
tapeport_cmdline_options_init()
int tapeport_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
tapeport_device_register()
int tapeport_device_register (int id, tapeport_device_t * device)
register a device to be used in the tapeport system
Referenced by dtlbasic_dongle_resources_init(), sense_dongle_resources_init(), tapecart_resources_init(), and tapertc_resources_init().
tapeport_enable()
void tapeport_enable (int val)
tapeport_get_active_state()
int tapeport_get_active_state (void)
tapeport_get_device_type_desc()
const char * tapeport_get_device_type_desc (int type)
Referenced by create_device_model().
tapeport_get_valid_devices()
tapeport_desc_t * tapeport_get_valid_devices (int port, int sort)
Referenced by build_tapeport_string(), and create_device_model().
tapeport_powerup()
void tapeport_powerup (void)
Referenced by machine_specific_powerup().
tapeport_resources_init()
int tapeport_resources_init (int amount)
Referenced by machine_resources_init().
tapeport_resources_shutdown()
void tapeport_resources_shutdown (void)
Referenced by machine_resources_shutdown().
tapeport_set_motor()
void tapeport_set_motor (int port, int flag)
tapeport_set_motor_in()
void tapeport_set_motor_in (int val, int port)
tapeport_set_sense_out()
void tapeport_set_sense_out (int port, int sense)
tapeport_set_tape_sense()
void tapeport_set_tape_sense (int sense, int port)
Referenced by check_sense(), sense_dongle_enable(), sense_dongle_powerup(), and set_sense().
tapeport_set_write_in()
void tapeport_set_write_in (int val, int port)
Referenced by set_write().
tapeport_snapshot_read_module()
int tapeport_snapshot_read_module (struct snapshot_s * s)
Referenced by c128_snapshot_read().
tapeport_snapshot_write_module()
int tapeport_snapshot_write_module (struct snapshot_s * s, int save_image)
Referenced by c128_snapshot_write().
tapeport_toggle_write_bit()
void tapeport_toggle_write_bit (int port, int write_bit)
tapeport_trigger_flux_change()
void tapeport_trigger_flux_change (unsigned int on, int port)
Referenced by cmdmode_send_pulses(), dtlbasic_write(), and tapecart_pulse_alarm_handler().
tapeport_valid_port()
int tapeport_valid_port (int port)