x128: sid_engine_s Struct Reference
sid_engine_s Struct Reference
#include <sid.h>
Data Fields
struct sound_s *(* open)(uint8_t *sidstate)
int(* init)(struct sound_s *psid, int speed, int cycles_per_sec, int factor)
void(* close)(struct sound_s *psid)
uint8_t(* read)(struct sound_s *psid, uint16_t addr)
void(* store)(struct sound_s *psid, uint16_t addr, uint8_t val)
void(* reset)(struct sound_s *psid, CLOCK cpu_clk)
int(* calculate_samples)(struct sound_s *psid, short *pbuf, int nr, int interleave, CLOCK *delta_t)
char *(* dump_state)(struct sound_s *psid)
void(* state_read)(struct sound_s *psid, struct sid_snapshot_state_s *sid_state)
void(* state_write)(struct sound_s *psid, struct sid_snapshot_state_s *sid_state)
Field Documentation
calculate_samples
int(* sid_engine_s::calculate_samples) (struct sound_s *psid, short *pbuf, int nr, int interleave, CLOCK *delta_t)
Referenced by sid_sound_machine_calculate_samples().
close
void(* sid_engine_s::close) (struct sound_s *psid)
Referenced by sid_sound_machine_close().
dump_state
char *(* sid_engine_s::dump_state) (struct sound_s *psid)
Referenced by sid_sound_machine_dump_state().
init
int(* sid_engine_s::init) (struct sound_s *psid, int speed, int cycles_per_sec, int factor)
Referenced by sid_sound_machine_init(), and sid_sound_machine_init_vbr().
open
struct sound_s *(* sid_engine_s::open) (uint8_t *sidstate)
Referenced by sid_sound_machine_open().
read
uint8_t(* sid_engine_s::read) (struct sound_s *psid, uint16_t addr)
Referenced by sid_sound_machine_read().
reset
void(* sid_engine_s::reset) (struct sound_s *psid, CLOCK cpu_clk)
Referenced by sid_sound_machine_reset().
state_read
void(* sid_engine_s::state_read) (struct sound_s *psid, struct sid_snapshot_state_s *sid_state)
Referenced by sid_state_read().
state_write
void(* sid_engine_s::state_write) (struct sound_s *psid, struct sid_snapshot_state_s *sid_state)
Referenced by sid_state_write().
store
void(* sid_engine_s::store) (struct sound_s *psid, uint16_t addr, uint8_t val)
Referenced by sid_sound_machine_store().
The documentation for this struct was generated from the following file:
sid/sid.h