vsid: vsyncapi.h File Reference
vsyncapi.h File Reference
#include "vice.h"
Typedefs
typedef void(* void_hook_t) (void)
Functions
void vsyncarch_get_metrics (double *cpu_percent, double *emulated_fps, int *warp_enabled)
current performance metrics
void vsyncarch_presync (void)
this is called before vsync_do_vsync does the synchroniation
void vsyncarch_postsync (void)
this is called after vsync_do_vsync did the synchroniation
void vsyncarch_advance_frame (void)
called to advance the emulation by one frame
int vsyncarch_vbl_sync_enabled (void)
Typedef Documentation
void_hook_t
typedef void(* void_hook_t) (void)
Function Documentation
vsyncarch_advance_frame()
void vsyncarch_advance_frame (void)
called to advance the emulation by one frame
Referenced by advance_frame_action().
vsyncarch_get_metrics()
void vsyncarch_get_metrics (double * cpu_percent, double * emulated_fps, int * warp_enabled)
current performance metrics
Referenced by statusbar_speed_widget_update().
vsyncarch_postsync()
void vsyncarch_postsync (void)
this is called after vsync_do_vsync did the synchroniation
Referenced by vsync_do_vsync().
vsyncarch_presync()
void vsyncarch_presync (void)
this is called before vsync_do_vsync does the synchroniation
Referenced by vsync_do_vsync().
vsyncarch_vbl_sync_enabled()
int vsyncarch_vbl_sync_enabled (void)