x128: core/ata.h File Reference
ata.h File Reference
#include "types.h"
Data Structures
struct ata_drive_geometry_s
Typedefs
typedef enum ata_drive_type_e ata_drive_type_t
typedef struct ata_drive_s ata_drive_t
typedef struct ata_drive_geometry_s ata_drive_geometry_t
Enumerations
enum ata_drive_type_e {
ATA_DRIVE_NONE ,
ATA_DRIVE_HDD ,
ATA_DRIVE_FDD ,
ATA_DRIVE_CD ,
ATA_DRIVE_CF
}
Functions
ata_drive_t * ata_init (int drive)
void ata_shutdown (ata_drive_t *drv)
void ata_register_store (ata_drive_t *cdrive, uint16_t addr, uint16_t value)
uint16_t ata_register_read (ata_drive_t *cdrive, uint16_t addr, uint16_t bus)
uint16_t ata_register_peek (ata_drive_t *cdrive, uint16_t addr)
int ata_register_dump (ata_drive_t *cdrive)
void ata_image_attach (ata_drive_t *cdrive, char *filename, ata_drive_type_t type, ata_drive_geometry_t geometry)
void ata_image_detach (ata_drive_t *cdrive)
int ata_image_change (ata_drive_t *cdrive, char *filename, ata_drive_type_t type, ata_drive_geometry_t geometry)
void ata_reset (ata_drive_t *cdrive)
void ata_update_timing (ata_drive_t *drv, CLOCK cycles_1s)
int ata_snapshot_read_module (ata_drive_t *drv, struct snapshot_s *s)
int ata_snapshot_write_module (ata_drive_t *drv, struct snapshot_s *s)
Typedef Documentation
ata_drive_geometry_t
typedef struct ata_drive_geometry_s ata_drive_geometry_t
ata_drive_t
typedef struct ata_drive_s ata_drive_t
ata_drive_type_t
typedef enum ata_drive_type_e ata_drive_type_t
Enumeration Type Documentation
ata_drive_type_e
enum ata_drive_type_e
Enumerator
ATA_DRIVE_NONE
ATA_DRIVE_HDD
ATA_DRIVE_FDD
ATA_DRIVE_CD
ATA_DRIVE_CF
Function Documentation
ata_image_attach()
void ata_image_attach (ata_drive_t * cdrive, char * filename, ata_drive_type_t type, ata_drive_geometry_t geometry)
< read/write mode
< read mode (binary)
Referenced by ata_image_change(), ata_snapshot_read_module(), and atapi_packet_execute_command().
ata_image_change()
int ata_image_change (ata_drive_t * cdrive, char * filename, ata_drive_type_t type, ata_drive_geometry_t geometry)
ata_image_detach()
void ata_image_detach (ata_drive_t * cdrive)
Referenced by atapi_packet_execute_command().
ata_init()
ata_drive_t * ata_init (int drive)
ata_register_dump()
int ata_register_dump (ata_drive_t * cdrive)
ata_register_peek()
uint16_t ata_register_peek (ata_drive_t * cdrive, uint16_t addr)
Referenced by ata_register_dump().
ata_register_read()
uint16_t ata_register_read (ata_drive_t * cdrive, uint16_t addr, uint16_t bus)
Referenced by ata_register_peek().
ata_register_store()
void ata_register_store (ata_drive_t * cdrive, uint16_t addr, uint16_t value)
ata_reset()
void ata_reset (ata_drive_t * cdrive)
Referenced by ata_poweron(), and ata_register_store().
ata_shutdown()
void ata_shutdown (ata_drive_t * drv)
ata_snapshot_read_module()
int ata_snapshot_read_module (ata_drive_t * drv, struct snapshot_s * s)
Todo:
FIXME: this is really retarded - we should instead identify the image by making a checksum instead of using the filename
ata_snapshot_write_module()
int ata_snapshot_write_module (ata_drive_t * drv, struct snapshot_s * s)
ata_update_timing()
void ata_update_timing (ata_drive_t * drv, CLOCK cycles_1s)
Referenced by ata_poweron().