vsid: arch/gtk3/uifliplist.c File Reference
uifliplist.c File Reference
Fliplist menu management.
#include "vice.h"
#include "attach.h"
#include "drive.h"
#include "fliplist.h"
#include "lib.h"
#include "util.h"
#include "filechooserhelpers.h"
#include "ui.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uistatusbar.h"
#include "uifliplist.h"
Macros
#define MSGBUF_SIZE 1024
Size of message buffer.
Functions
static void trigger_ui_action (GtkWidget *item, gpointer action)
Handler for the 'activate' event of menu items.
static void ui_fliplist_select_cb (GtkWidget *widget, gpointer data)
Handler for attaching an image from the fliplist.
void ui_populate_fliplist_menu (GtkWidget *menu, int unit, int separator_count)
Fill in a menu with controls for fliplist control.
static void fliplist_load_response (GtkWidget *widget, gint response_id, gpointer user_data)
Handler for the 'response' event of the 'load fliplist' dialog.
void ui_fliplist_load_dialog_show (int unit)
Create and show the "load fliplist" dialog.
static void fliplist_save_response (GtkWidget *widget, gint response_id, gpointer user_data)
Handler for the 'response' event of the 'save fliplist' dialog.
void ui_fliplist_save_dialog_show (int unit)
Create and show the "save fliplist" dialog.
Detailed Description
Fliplist menu management.
Author
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Todo:
Refactor to use UI actions, remove code (re)implemented in actions-drive.c.
Macro Definition Documentation
MSGBUF_SIZE
#define MSGBUF_SIZE 1024
Size of message buffer.
Function Documentation
fliplist_load_response()
static void fliplist_load_response (GtkWidget * widget, gint response_id, gpointer user_data) static
Handler for the 'response' event of the 'load fliplist' dialog.
Parameters
[in] widget dialog
[in] response_id response ID
[in] user_data unit number
Todo:
read autoattach out of an extra widget.
Todo:
Autoattach looks slightly buggy in fliplist.c
Referenced by ui_fliplist_load_dialog_show().
fliplist_save_response()
static void fliplist_save_response (GtkWidget * widget, gint response_id, gpointer user_data) static
Handler for the 'response' event of the 'save fliplist' dialog.
Parameters
[in] widget dialog
[in] response_id response ID
[in] user_data unit number
Referenced by ui_fliplist_save_dialog_show().
trigger_ui_action()
static void trigger_ui_action (GtkWidget * item, gpointer action) static
Handler for the 'activate' event of menu items.
Triggers UI action action.
Parameters
[in] item menu item (unused)
[in] action UI action ID
Referenced by ui_populate_fliplist_menu().
ui_fliplist_load_dialog_show()
void ui_fliplist_load_dialog_show (int unit)
Create and show the "load fliplist" dialog.
Parameters
[in] unit Disk unit to load fliplist to, or FLIPLIST_ALL_UNITS
Todo:
add a separate "extra widget" that will let the user select autoattach
Referenced by fliplist_load_action().
ui_fliplist_save_dialog_show()
void ui_fliplist_save_dialog_show (int unit)
Create and show the "save fliplist" dialog.
Parameters
[in] unit Drive unit to save fliplist from, or FLIPLIST_ALL_UNITS
Referenced by fliplist_save_action().
ui_fliplist_select_cb()
static void ui_fliplist_select_cb (GtkWidget * widget, gpointer data) static
Handler for attaching an image from the fliplist.
Parameters
[in] widget widget triggering the event
[in] data unit number and file index
Referenced by ui_populate_fliplist_menu().
ui_populate_fliplist_menu()
void ui_populate_fliplist_menu (GtkWidget * menu, int unit, int separator_count)
Fill in a menu with controls for fliplist control.
Fliplist controls are placed at the end of a menu, after a separator. Any previously-existing fliplist controls within the menu will be removed.
Parameters
menu The menu to be edited.
unit The drive unit (8-11) that this menu will control.
separator_count The number of menu separators in the part of the menu that does not involve the fliplist.
Todo:
Add/Remove current image to/from fliplist should really be here too.
Referenced by ui_do_drive_popup(), and ui_drive_menu_create().