x128: arch/gtk3/uidata.h File Reference
uidata.h File Reference
GTK3 binary resources handling - header.
#include <gtk/gtk.h>
Macros
#define UIDATA_ROOT_PATH "/org/pokefinder/vice"
Root namespace of the GResouce files.
#define UIDATA_GRESOURCE_FILE "vice.gresource"
Name of the GResource file.
Functions
gboolean uidata_init (void)
Intialize the GResource binary blob handling.
void uidata_shutdown (void)
Clean up GResource data.
GdkPixbuf * uidata_get_pixbuf (const gchar *name)
Get a pixbuf from the GResource blob.
GdkPixbuf * uidata_get_pixbuf_at_scale (const gchar *name, gint width, gint height, gboolean preserve_aspect_ratio)
Get a pixbuf from the GResource blob and scale it.
GBytes * uidata_get_bytes (const gchar *name)
Get a bytes from the GResource blob.
Detailed Description
GTK3 binary resources handling - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
UIDATA_GRESOURCE_FILE
#define UIDATA_GRESOURCE_FILE "vice.gresource"
Name of the GResource file.
UIDATA_ROOT_PATH
#define UIDATA_ROOT_PATH "/org/pokefinder/vice"
Root namespace of the GResouce files.
The GResource handling requires setting a namespace for the files, which is similar to the argument to gtk_application_new(), basically inverting a URL's components.
In this case, I have used vice.pokefinder.org as our website.
Function Documentation
uidata_get_bytes()
GBytes * uidata_get_bytes (const gchar * name)
Get a bytes from the GResource blob.
Parameters
[in] name path in gresource
Returns
GBytes* or NULL on error
uidata_get_pixbuf()
GdkPixbuf * uidata_get_pixbuf (const gchar * name)
Get a pixbuf from the GResource blob.
Parameters
[in] name virtual path to the file
Returns
GdkPixbuf or NULL on error
Referenced by get_default_icon(), and get_vice_logo().
uidata_get_pixbuf_at_scale()
GdkPixbuf * uidata_get_pixbuf_at_scale (const gchar * name, gint width, gint height, gboolean preserve_aspect)
Get a pixbuf from the GResource blob and scale it.
Parameters
[in] name path in gresource
[in] width width of rescaled pixbuf
[in] height height of rescaled pixbuf
[in] preserve_aspect preserve aspect ratio
Returns
pixbuf or NULL on error
Referenced by get_default_icon().
uidata_init()
gboolean uidata_init (void)
Intialize the GResource binary blob handling.
Returns
non-0 on success
Referenced by ui_init().
uidata_shutdown()
void uidata_shutdown (void)
Clean up GResource data.
Referenced by ui_shutdown().