vsid: kbdbuf.h File Reference
kbdbuf.h File Reference
#include "types.h"
Functions
int kbdbuf_is_empty (void)
Return nonzero if the keyboard buffer is empty.
int kbdbuf_queue_is_empty (void)
Return nonzero if there are keys in the buffer queue.
void kbdbuf_init (int location, int plocation, int buffer_size, CLOCK mincycles)
Initialization.
void kbdbuf_shutdown (void)
void kbdbuf_abort (void)
abort ongoing "paste", called by reset
void kbdbuf_reset (int location, int plocation, int buffer_size, CLOCK mincycles)
int kbdbuf_feed (const char *s)
used by autostart, monitor binary remote protocol, "paste" UI action
int kbdbuf_feed_runcmd (const char *string)
used by autostart to feed "RUN"
int kbdbuf_feed_string (const char *string)
void kbdbuf_feed_cmdline (void)
used by autostart
void kbdbuf_flush (void)
int kbdbuf_cmdline_options_init (void)
int kbdbuf_resources_init (void)
initialize the resources
Function Documentation
kbdbuf_abort()
void kbdbuf_abort (void)
abort ongoing "paste", called by reset
Referenced by machine_reset().
kbdbuf_cmdline_options_init()
int kbdbuf_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
kbdbuf_feed()
int kbdbuf_feed (const char * s)
used by autostart, monitor binary remote protocol, "paste" UI action
Referenced by advance_hasdisk(), advance_hastape(), autostart_finish(), kbdbuf_feed_cmdline(), kbdbuf_feed_string(), monitor_binary_process_keyboard_feed(), and paste_callback().
kbdbuf_feed_cmdline()
void kbdbuf_feed_cmdline (void)
used by autostart
Referenced by autostart_finish(), and kbdbuf_init().
kbdbuf_feed_runcmd()
int kbdbuf_feed_runcmd (const char * string)
used by autostart to feed "RUN"
Referenced by autostart_finish(), kbdbuf_feed_cmdline(), and machine_vsync_hook().
kbdbuf_feed_string()
int kbdbuf_feed_string (const char * string)
Referenced by mon_keyboard_feed().
kbdbuf_flush()
void kbdbuf_flush (void)
Referenced by string_to_queue(), and vsync_do_vsync().
kbdbuf_init()
void kbdbuf_init (int location, int plocation, int size, CLOCK mincycles)
Initialization.
Referenced by machine_specific_init().
kbdbuf_is_empty()
int kbdbuf_is_empty (void)
Return nonzero if the keyboard buffer is empty.
Referenced by check2(), is_machine_ready(), and kbdbuf_flush().
kbdbuf_queue_is_empty()
int kbdbuf_queue_is_empty (void)
Return nonzero if there are keys in the buffer queue.
Referenced by check2().
kbdbuf_reset()
void kbdbuf_reset (int location, int plocation, int buffer_size, CLOCK mincycles)
Referenced by kbdbuf_init().
kbdbuf_resources_init()
int kbdbuf_resources_init (void)
initialize the resources
Returns
0 on success, else -1.
Remarks
Registers the integer resources
Referenced by machine_resources_init().
kbdbuf_shutdown()
void kbdbuf_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().