vsid: printerdrv/drv-mps803.c File Reference
drv-mps803.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "driver-select.h"
#include "drv-mps803.h"
#include "log.h"
#include "output-select.h"
#include "output.h"
#include "palette.h"
#include "printer.h"
#include "sysfile.h"
#include "types.h"
Data Structures
struct mps_s
Macros
#define DBG(x)
#define MAX_ROM_SIZE (8 * 1024)
#define MAX_CHARS_PER_LINE 136
#define MAX_BYTES_PER_CHAR 8
#define MAX_COLS_PER_CHAR 8
#define MAX_ROWS_PER_CHAR 8
#define MPS803_PAGE_HEIGHT_CHARACTERS 70
#define MPS803_PAGE_WIDTH_CHARACTERS 80
#define MPS803_PAGE_WIDTH_DOTS (MPS803_PAGE_WIDTH_CHARACTERS * 6)
#define MPS803_PAGE_HEIGHT_DOTS (MPS803_PAGE_HEIGHT_CHARACTERS * 10)
#define MPS802_BYTES_PER_CHAR 8
#define MPS803_BYTES_PER_CHAR 6
#define C2022_BYTES_PER_CHAR 6
#define C4023_BYTES_PER_CHAR 8
#define SA_FEATURE_PROG_CHAR_254 0x01
programable character, SA=5
#define CTRL_FEATURE_OLD_ENHANCE 0x01
old-style enhance using ctrl 1/129
#define CTRL_FEATURE_NEW_ENHANCE 0x02
new-style enhance using ctrl 14/15
#define CTRL_FEATURE_BIT_IMAGE_PRINTING 0x04
ctrl 8
#define CTRL_FEATURE_CR_WITHOUT_LF 0x08
carriage return without linefeed, ctrl 141
#define MPS_REVERSE 0x01
global mode
#define MPS_CRSRUP 0x02
set in gfxmode (default) unset in businessmode
#define MPS_BITMODE 0x04
#define MPS_DBLWDTH 0x08
#define MPS_REPEAT 0x10
#define MPS_ESC 0x20
#define MPS_QUOTED 0x40
odd number of quotes in line (textmode)
#define MPS_BUSINESS 0x80
opened with SA = 7 in business mode
#define MPS_GRAPHICS 0x00
opened with SA = 0 in graphics mode
Typedefs
typedef struct mps_s mps_t
Functions
static int get_charset_bit (mps_t *mps, int nr, unsigned int col, unsigned int row)
static int get_bit_from_rom (mps_t *mps, int offs, int ch, int col, int row)
static void convert_rom_char (mps_t *mps, int offs, int destchar, int numchar)
static void convert_rom_char_192 (mps_t *mps, int offs)
used by 2022,2023,3022,8023
static void convert_rom_char_160 (mps_t *mps, int offs)
used by mps803 (160 chars)
static void convert_rom_char_mps801 (mps_t *mps, int offs)
used by mps801 (164 chars)
static void set_global_mode (mps_t *mps, unsigned int m)
static void unset_global_mode (mps_t *mps, unsigned int m)
static int get_global_mode (mps_t *mps, unsigned int m)
static int get_chargen_mode (mps_t *mps, unsigned int secondary)
static void print_cbm_char (mps_t *mps, const uint8_t rawchar)
static void write_line (mps_t *mps, unsigned int prnr)
static void clear_buffer (mps_t *mps)
static void print_bitmask (mps_t *mps, unsigned int prnr, const char c)
static void warn_ctrl_code (int code)
static void mps_engine_putc (mps_t *mps, unsigned int prnr, unsigned int secondary, const uint8_t c)
static int drv_common_open (unsigned int prnr, unsigned int secondary)
Interface to the upper layer.
static int drv_2022_open (unsigned int prnr, unsigned int secondary)
static int drv_2022_select (unsigned int prnr)
static int drv_4023_open (unsigned int prnr, unsigned int secondary)
static int drv_4023_select (unsigned int prnr)
static int drv_8023_open (unsigned int prnr, unsigned int secondary)
static int drv_8023_select (unsigned int prnr)
static int drv_mps801_open (unsigned int prnr, unsigned int secondary)
static int drv_mps801_select (unsigned int prnr)
static int drv_mps802_open (unsigned int prnr, unsigned int secondary)
static int drv_mps802_select (unsigned int prnr)
static int drv_mps803_open (unsigned int prnr, unsigned int secondary)
static int drv_mps803_select (unsigned int prnr)
static void drv_mps803_close (unsigned int prnr, unsigned int secondary)
static int drv_mps803_putc (unsigned int prnr, unsigned int secondary, uint8_t b)
static int drv_mps803_getc (unsigned int prnr, unsigned int secondary, uint8_t *b)
static int drv_mps803_flush (unsigned int prnr, unsigned int secondary)
static int drv_mps803_formfeed (unsigned int prnr)
int drv_mps803_init_resources (void)
Register drivers.
int drv_mps803_init (void)
void drv_mps803_shutdown (void)
Variables
static mps_t drv_mps803 [4]
static palette_t * palette = NULL
static log_t drv803_log = ((log_t)-1)
Macro Definition Documentation
C2022_BYTES_PER_CHAR
#define C2022_BYTES_PER_CHAR 6
C4023_BYTES_PER_CHAR
#define C4023_BYTES_PER_CHAR 8
CTRL_FEATURE_BIT_IMAGE_PRINTING
#define CTRL_FEATURE_BIT_IMAGE_PRINTING 0x04
ctrl 8
CTRL_FEATURE_CR_WITHOUT_LF
#define CTRL_FEATURE_CR_WITHOUT_LF 0x08
carriage return without linefeed, ctrl 141
CTRL_FEATURE_NEW_ENHANCE
#define CTRL_FEATURE_NEW_ENHANCE 0x02
new-style enhance using ctrl 14/15
CTRL_FEATURE_OLD_ENHANCE
#define CTRL_FEATURE_OLD_ENHANCE 0x01
old-style enhance using ctrl 1/129
DBG
#define DBG (x)
MAX_BYTES_PER_CHAR
#define MAX_BYTES_PER_CHAR 8
MAX_CHARS_PER_LINE
#define MAX_CHARS_PER_LINE 136
MAX_COLS_PER_CHAR
#define MAX_COLS_PER_CHAR 8
MAX_ROM_SIZE
#define MAX_ROM_SIZE (8 * 1024)
MAX_ROWS_PER_CHAR
#define MAX_ROWS_PER_CHAR 8
MPS802_BYTES_PER_CHAR
#define MPS802_BYTES_PER_CHAR 8
MPS803_BYTES_PER_CHAR
#define MPS803_BYTES_PER_CHAR 6
MPS803_PAGE_HEIGHT_CHARACTERS
#define MPS803_PAGE_HEIGHT_CHARACTERS 70
MPS803_PAGE_HEIGHT_DOTS
#define MPS803_PAGE_HEIGHT_DOTS (MPS803_PAGE_HEIGHT_CHARACTERS * 10)
MPS803_PAGE_WIDTH_CHARACTERS
#define MPS803_PAGE_WIDTH_CHARACTERS 80
MPS803_PAGE_WIDTH_DOTS
#define MPS803_PAGE_WIDTH_DOTS (MPS803_PAGE_WIDTH_CHARACTERS * 6)
MPS_BITMODE
#define MPS_BITMODE 0x04
MPS_BUSINESS
#define MPS_BUSINESS 0x80
opened with SA = 7 in business mode
MPS_CRSRUP
#define MPS_CRSRUP 0x02
set in gfxmode (default) unset in businessmode
MPS_DBLWDTH
#define MPS_DBLWDTH 0x08
MPS_ESC
#define MPS_ESC 0x20
MPS_GRAPHICS
#define MPS_GRAPHICS 0x00
opened with SA = 0 in graphics mode
MPS_QUOTED
#define MPS_QUOTED 0x40
odd number of quotes in line (textmode)
MPS_REPEAT
#define MPS_REPEAT 0x10
MPS_REVERSE
#define MPS_REVERSE 0x01
global mode
SA_FEATURE_PROG_CHAR_254
#define SA_FEATURE_PROG_CHAR_254 0x01
programable character, SA=5
Typedef Documentation
mps_t
typedef struct mps_s mps_t
Function Documentation
clear_buffer()
static void clear_buffer (mps_t * mps) static
Referenced by mps_engine_putc(), and print_bitmask().
convert_rom_char()
static void convert_rom_char (mps_t * mps, int offs, int destchar, int numchar) static
Referenced by convert_rom_char_160(), convert_rom_char_192(), and convert_rom_char_mps801().
convert_rom_char_160()
static void convert_rom_char_160 (mps_t * mps, int offs) static
used by mps803 (160 chars)
Referenced by drv_mps803_open().
convert_rom_char_192()
static void convert_rom_char_192 (mps_t * mps, int offs) static
used by 2022,2023,3022,8023
Referenced by drv_2022_open(), drv_4023_open(), drv_8023_open(), and drv_mps802_open().
convert_rom_char_mps801()
static void convert_rom_char_mps801 (mps_t * mps, int offs) static
used by mps801 (164 chars)
Referenced by drv_mps801_open().
drv_2022_open()
static int drv_2022_open (unsigned int prnr, unsigned int secondary) static
< 2022/2023
< 2022/2023
< programable character, SA=5
< old-style enhance using ctrl 1/129
< carriage return without linefeed, ctrl 141
Referenced by drv_2022_select(), and drv_mps803_init_resources().
drv_2022_select()
static int drv_2022_select (unsigned int prnr) static
Referenced by drv_mps803_init_resources().
drv_4023_open()
static int drv_4023_open (unsigned int prnr, unsigned int secondary) static
< 4023
< 4023
< programable character, SA=5
< old-style enhance using ctrl 1/129
< carriage return without linefeed, ctrl 141
Referenced by drv_4023_select(), and drv_mps803_init_resources().
drv_4023_select()
static int drv_4023_select (unsigned int prnr) static
Referenced by drv_mps803_init_resources().
drv_8023_open()
static int drv_8023_open (unsigned int prnr, unsigned int secondary) static
< 8023
< 8023
< programable character, SA=5
< old-style enhance using ctrl 1/129
< carriage return without linefeed, ctrl 141
Referenced by drv_8023_select(), and drv_mps803_init_resources().
drv_8023_select()
static int drv_8023_select (unsigned int prnr) static
Referenced by drv_mps803_init_resources().
drv_common_open()
static int drv_common_open (unsigned int prnr, unsigned int secondary) static
Interface to the upper layer.
< set in gfxmode (default) unset in businessmode
< set in gfxmode (default) unset in businessmode
< set in gfxmode (default) unset in businessmode
Referenced by drv_2022_open(), drv_4023_open(), drv_8023_open(), drv_mps801_open(), drv_mps802_open(), and drv_mps803_open().
drv_mps801_open()
static int drv_mps801_open (unsigned int prnr, unsigned int secondary) static
< c1fbd1f3
< c1fbd1f3
< new-style enhance using ctrl 14/15
< ctrl 8
Referenced by drv_mps801_select(), and drv_mps803_init_resources().
drv_mps801_select()
static int drv_mps801_select (unsigned int prnr) static
Referenced by drv_mps803_init_resources().
drv_mps802_open()
static int drv_mps802_open (unsigned int prnr, unsigned int secondary) static
< same as mps802 ?
< same as mps802 ?
< programable character, SA=5
< carriage return without linefeed, ctrl 141
Referenced by drv_mps802_select(), and drv_mps803_init_resources().
drv_mps802_select()
static int drv_mps802_select (unsigned int prnr) static
Referenced by drv_mps803_init_resources().
drv_mps803_close()
static void drv_mps803_close (unsigned int prnr, unsigned int secondary) static
Referenced by drv_mps803_init_resources().
drv_mps803_flush()
static int drv_mps803_flush (unsigned int prnr, unsigned int secondary) static
Referenced by drv_mps803_init_resources().
drv_mps803_formfeed()
static int drv_mps803_formfeed (unsigned int prnr) static
Referenced by drv_mps803_init_resources().
drv_mps803_getc()
static int drv_mps803_getc (unsigned int prnr, unsigned int secondary, uint8_t * b) static
Referenced by drv_mps803_init_resources().
drv_mps803_init()
int drv_mps803_init (void)
Todo:
FIXME: rename the palette somehow?
Referenced by printer_init().
drv_mps803_init_resources()
int drv_mps803_init_resources (void)
Register drivers.
Register printer drivers.
Commodore MPS 801
Commodore MPS 802
Commodore MPS 803
Commodore 2022
Commodore 4034
Commodore 8034
Returns
0
Referenced by printer_resources_init().
drv_mps803_open()
static int drv_mps803_open (unsigned int prnr, unsigned int secondary) static
< new-style enhance using ctrl 14/15
< ctrl 8
Referenced by drv_mps803_init_resources(), and drv_mps803_select().
drv_mps803_putc()
static int drv_mps803_putc (unsigned int prnr, unsigned int secondary, uint8_t b) static
Referenced by drv_mps803_init_resources().
drv_mps803_select()
static int drv_mps803_select (unsigned int prnr) static
Referenced by drv_mps803_init_resources().
drv_mps803_shutdown()
void drv_mps803_shutdown (void)
Referenced by printer_shutdown().
get_bit_from_rom()
static int get_bit_from_rom (mps_t * mps, int offs, int ch, int col, int row) static
Referenced by convert_rom_char().
get_chargen_mode()
static int get_chargen_mode (mps_t * mps, unsigned int secondary) static
Todo:
FIXME: it is not quite clear how this works exactly
< opened with SA = 7 in business mode
< opened with SA = 0 in graphics mode
Referenced by mps_engine_putc().
get_charset_bit()
static int get_charset_bit (mps_t * mps, int nr, unsigned int col, unsigned int row) static
Todo:
FIXME: custom char
Referenced by print_cbm_char().
get_global_mode()
static int get_global_mode (mps_t * mps, unsigned int m) static
Referenced by mps_engine_putc(), print_cbm_char(), and write_line().
mps_engine_putc()
static void mps_engine_putc (mps_t * mps, unsigned int prnr, unsigned int secondary, const uint8_t c) static
Todo:
FIXME: it is not quite clear under what condition the chargen mode is reset to what the secondary address implies. right now we do it under the following conditions:
the current character is the first character in a logical line, ie it follows a CR
the secondary address is different to the secondary address used for the last character.
< opened with SA = 7 in business mode
< set in gfxmode (default) unset in businessmode
< set in gfxmode (default) unset in businessmode
< programable character, SA=5
< odd number of quotes in line (textmode)
< old-style enhance using ctrl 1/129
< odd number of quotes in line (textmode)
< ctrl 8
< carriage return without linefeed, ctrl 141
< opened with SA = 7 in business mode
< set in gfxmode (default) unset in businessmode
< set in gfxmode (default) unset in businessmode
< odd number of quotes in line (textmode)
< old-style enhance using ctrl 1/129
< old-style enhance using ctrl 1/129
< new-style enhance using ctrl 14/15
< new-style enhance using ctrl 14/15
< ctrl 8
< set in gfxmode (default) unset in businessmode
< set in gfxmode (default) unset in businessmode
Todo:
FIXME: (MPS1000: Double density (960 DPL) bit image graphics)
Todo:
FIXME: Form Feed
Todo:
FIXME: Paging OFF (HOME)
Todo:
FIXME: Skip Space
Todo:
FIXME: Paging ON (CLR)
Todo:
FIXME: NLQ OFF
Todo:
FIXME: Prints blank alpha field in formatting print
< ctrl 8
< odd number of quotes in line (textmode)
< odd number of quotes in line (textmode)
Referenced by drv_mps803_putc().
print_bitmask()
static void print_bitmask (mps_t * mps, unsigned int prnr, const char c) static
Referenced by mps_engine_putc().
print_cbm_char()
static void print_cbm_char (mps_t * mps, const uint8_t rawchar) static
< programable character, SA=5
Todo:
FIXME: tag custom char
< set in gfxmode (default) unset in businessmode
Referenced by mps_engine_putc().
set_global_mode()
static void set_global_mode (mps_t * mps, unsigned int m) static
Referenced by drv_common_open(), and mps_engine_putc().
unset_global_mode()
static void unset_global_mode (mps_t * mps, unsigned int m) static
Referenced by drv_common_open(), and mps_engine_putc().
warn_ctrl_code()
static void warn_ctrl_code (int code) static
Referenced by mps_engine_putc().
write_line()
static void write_line (mps_t * mps, unsigned int prnr) static
Referenced by mps_engine_putc(), and print_bitmask().
Variable Documentation
drv803_log
log_t drv803_log = ((log_t)-1) static
Todo:
FIXME: log per mps_t?
Referenced by drv_2022_open(), drv_4023_open(), drv_8023_open(), drv_mps801_open(), drv_mps802_open(), drv_mps803_init(), drv_mps803_open(), print_cbm_char(), and warn_ctrl_code().
drv_mps803
mps_t drv_mps803[4] static
Referenced by drv_2022_open(), drv_4023_open(), drv_8023_open(), drv_common_open(), drv_mps801_open(), drv_mps802_open(), drv_mps803_open(), and drv_mps803_putc().
palette
palette_t* palette = NULL static
Todo:
FIXME: palette per mps_t?
Referenced by drv_2022_open(), drv_4023_open(), drv_8023_open(), drv_mps801_open(), drv_mps802_open(), drv_mps803_init(), drv_mps803_open(), and drv_mps803_shutdown().