vsid: serial/serial-iec-device.c File Reference
serial-iec-device.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "cmdline.h"
#include "iecbus.h"
#include "resources.h"
#include "serial-iec-device.h"
#include "serial.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "serial-iec-bus.h"
Data Structures
struct serial_iec_device_state_s
Implement IEC devices here.
Macros
#define US2CYCLES(us) ((long) ((((double) us) * serial_iec_device_cycles_per_us) + 0.5))
Typedefs
typedef struct serial_iec_device_state_s serial_iec_device_state_t
Enumerations
enum {
P_PRE0 = 0 ,
P_PRE1 ,
P_PRE2 ,
P_READY ,
P_EOI ,
P_EOIw ,
P_BIT0 ,
P_BIT0w ,
P_BIT1 ,
P_BIT1w ,
P_BIT2 ,
P_BIT2w ,
P_BIT3 ,
P_BIT3w ,
P_BIT4 ,
P_BIT4w ,
P_BIT5 ,
P_BIT5w ,
P_BIT6 ,
P_BIT6w ,
P_BIT7 ,
P_BIT7w ,
P_DONE0 ,
P_DONE1 ,
P_FRAMEERR0 ,
P_FRAMEERR1 ,
P_TALKING = 0x20 ,
P_LISTENING = 0x40 ,
P_ATN = 0x80
}
Functions
void serial_iec_device_enable (unsigned int devnr)
void serial_iec_device_disable (unsigned int devnr)
static void serial_iec_device_exec_main (unsigned int devnr, CLOCK clk_value)
static int set_iec_device_enable (int enable, void *param)
int serial_iec_device_resources_init (void)
int serial_iec_device_cmdline_options_init (void)
void serial_iec_device_init (void)
void serial_iec_device_reset (void)
void serial_iec_device_exec (CLOCK clk_value)
static void set_st (uint8_t b)
static uint8_t get_st (void)
void serial_iec_device_set_machine_parameter (long cycles_per_sec)
Variables
static int iec_device_enabled [16]
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
static int serial_iec_device_inited = 0
static serial_iec_device_state_t serial_iec_device_state [16]
static uint8_t serial_iec_device_st
static double serial_iec_device_cycles_per_us = 1.0
Macro Definition Documentation
US2CYCLES
#define US2CYCLES (us) ((long) ((((double) us) * serial_iec_device_cycles_per_us) + 0.5))
Typedef Documentation
serial_iec_device_state_t
typedef struct serial_iec_device_state_s serial_iec_device_state_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
P_PRE0
P_PRE1
P_PRE2
P_READY
P_EOI
P_EOIw
P_BIT0
P_BIT0w
P_BIT1
P_BIT1w
P_BIT2
P_BIT2w
P_BIT3
P_BIT3w
P_BIT4
P_BIT4w
P_BIT5
P_BIT5w
P_BIT6
P_BIT6w
P_BIT7
P_BIT7w
P_DONE0
P_DONE1
P_FRAMEERR0
P_FRAMEERR1
P_TALKING
P_LISTENING
P_ATN
Function Documentation
get_st()
static uint8_t get_st (void) inline static
Referenced by serial_iec_device_exec_main().
serial_iec_device_cmdline_options_init()
int serial_iec_device_cmdline_options_init (void)
Todo:
FIXME: xvic does not use the generic iec code in src/iecbus/iecbus.c, which makes iecdevice not work
Referenced by serial_cmdline_options_init().
serial_iec_device_disable()
void serial_iec_device_disable (unsigned int devnr)
Referenced by set_iec_device_enable().
serial_iec_device_enable()
void serial_iec_device_enable (unsigned int devnr)
Referenced by serial_iec_device_init(), and set_iec_device_enable().
serial_iec_device_exec()
void serial_iec_device_exec (CLOCK clk_value)
Referenced by iecbus_cpu_read_conf3(), and iecbus_cpu_write_conf3().
serial_iec_device_exec_main()
static void serial_iec_device_exec_main (unsigned int devnr, CLOCK clk_value) static
Referenced by serial_iec_device_exec().
serial_iec_device_init()
void serial_iec_device_init (void)
Referenced by serial_trap_init().
serial_iec_device_reset()
void serial_iec_device_reset (void)
Referenced by serial_traps_reset().
serial_iec_device_resources_init()
int serial_iec_device_resources_init (void)
Todo:
FIXME: xvic does not use the generic iec code in src/iecbus/iecbus.c, which makes iecdevice not work
Referenced by serial_resources_init().
serial_iec_device_set_machine_parameter()
void serial_iec_device_set_machine_parameter (long cycles_per_sec)
Referenced by machine_change_timing().
set_iec_device_enable()
static int set_iec_device_enable (int enable, void * param) static
set_st()
static void set_st (uint8_t b) inline static
Referenced by serial_iec_device_exec_main().
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-iecdevice4", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice4", (resource_value_t)1,
      NULL, "Enable IEC device emulation for device #4" },
    { "+iecdevice4", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice4", (resource_value_t)0,
      NULL, "Disable IEC device emulation for device #4" },
    { "-iecdevice5", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice5", (resource_value_t)1,
      NULL, "Enable IEC device emulation for device #5" },
    { "+iecdevice5", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice5", (resource_value_t)0,
      NULL, "Disable IEC device emulation for device #5" },
    { "-iecdevice6", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice6", (resource_value_t)1,
      NULL, "Enable IEC device emulation for device #6" },
    { "+iecdevice6", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice6", (resource_value_t)0,
      NULL, "Disable IEC device emulation for device #6" },
    { "-iecdevice7", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice7", (resource_value_t)1,
      NULL, "Enable IEC device emulation for device #7" },
    { "+iecdevice7", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice7", (resource_value_t)0,
      NULL, "Disable IEC device emulation for device #7" },
    { "-iecdevice8", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice8", (resource_value_t)1,
      NULL, "Enable IEC device emulation for device #8" },
    { "+iecdevice8", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice8", (resource_value_t)0,
      NULL, "Disable IEC device emulation for device #8" },
    { "-iecdevice9", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice9", (resource_value_t)1,
      NULL, "Enable IEC device emulation for device #9" },
    { "+iecdevice9", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice9", (resource_value_t)0,
      NULL, "Disable IEC device emulation for device #9" },
    { "-iecdevice10", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice10", (resource_value_t)1,
      NULL, "Enable IEC device emulation for device #10" },
    { "+iecdevice10", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice10", (resource_value_t)0,
      NULL, "Disable IEC device emulation for device #10" },
    { "-iecdevice11", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice11", (resource_value_t)1,
      NULL, "Enable IEC device emulation for device #11" },
    { "+iecdevice11", SET_RESOURCE,  0 ,
      NULL, NULL, "IECDevice11", (resource_value_t)0,
      NULL, "Disable IEC device emulation for device #11" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by serial_iec_device_cmdline_options_init().
iec_device_enabled
int iec_device_enabled[16] static
Referenced by serial_iec_device_init(), and set_iec_device_enable().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "IECDevice4", 0, RES_EVENT_SAME, NULL,
      &iec_device_enabled[4], set_iec_device_enable, (void *)4 },
    { "IECDevice5", 0, RES_EVENT_SAME, NULL,
      &iec_device_enabled[5], set_iec_device_enable, (void *)5 },
    { "IECDevice6", 0, RES_EVENT_SAME, NULL,
      &iec_device_enabled[6], set_iec_device_enable, (void *)6 },
    { "IECDevice7", 0, RES_EVENT_SAME, NULL,
      &iec_device_enabled[7], set_iec_device_enable, (void *)7 },
    { "IECDevice8", 0, RES_EVENT_SAME, NULL,
      &iec_device_enabled[8], set_iec_device_enable, (void *)8 },
    { "IECDevice9", 0, RES_EVENT_SAME, NULL,
      &iec_device_enabled[9], set_iec_device_enable, (void *)9 },
    { "IECDevice10", 0, RES_EVENT_SAME, NULL,
      &iec_device_enabled[10], set_iec_device_enable, (void *)10 },
    { "IECDevice11", 0, RES_EVENT_SAME, NULL,
      &iec_device_enabled[11], set_iec_device_enable, (void *)11 },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by serial_iec_device_resources_init().
serial_iec_device_cycles_per_us
double serial_iec_device_cycles_per_us = 1.0 static
Referenced by serial_iec_device_set_machine_parameter().
serial_iec_device_inited
int serial_iec_device_inited = 0 static
Referenced by serial_iec_device_disable(), serial_iec_device_enable(), and serial_iec_device_init().
serial_iec_device_st
uint8_t serial_iec_device_st static
Referenced by get_st(), and set_st().
serial_iec_device_state
serial_iec_device_state_t serial_iec_device_state[16] static
Referenced by serial_iec_device_disable(), serial_iec_device_enable(), serial_iec_device_exec(), serial_iec_device_exec_main(), serial_iec_device_init(), and serial_iec_device_reset().