vsid: core/flash040core.c File Reference
flash040core.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "alarm.h"
#include "flash040.h"
#include "lib.h"
#include "log.h"
#include "maincpu.h"
#include "snapshot.h"
#include "types.h"
Data Structures
struct flash_types_s
Macros
#define FLASH_DEBUG(x)
#define FLASH040_DUMP_VER_MAJOR 2
#define FLASH040_DUMP_VER_MINOR 0
Typedefs
typedef struct flash_types_s flash_types_t
Functions
static int flash_magic_1 (flash040_context_t *flash040_context, unsigned int addr)
static int flash_magic_2 (flash040_context_t *flash040_context, unsigned int addr)
static void flash_clear_erase_mask (flash040_context_t *flash040_context)
static unsigned int flash_sector_to_addr (flash040_context_t *flash040_context, unsigned int sector)
static unsigned int flash_addr_to_sector_number (flash040_context_t *flash040_context, unsigned int addr)
static void flash_add_sector_to_erase_mask (flash040_context_t *flash040_context, unsigned int addr)
static void flash_erase_sector (flash040_context_t *flash040_context, unsigned int sector)
static void flash_erase_chip (flash040_context_t *flash040_context)
static int flash_program_byte (flash040_context_t *flash040_context, unsigned int addr, uint8_t byte)
static int flash_write_operation_status (flash040_context_t *flash040_context)
static int flash_erase_operation_status (flash040_context_t *flash040_context)
static void erase_alarm_handler (CLOCK offset, void *data)
static void flash040core_store_internal (flash040_context_t *flash040_context, unsigned int addr, uint8_t byte)
void flash040core_store (flash040_context_t *flash040_context, unsigned int addr, uint8_t byte)
uint8_t flash040core_read (flash040_context_t *flash040_context, unsigned int addr)
uint8_t flash040core_peek (flash040_context_t *flash040_context, unsigned int addr)
void flash040core_reset (flash040_context_t *flash040_context)
void flash040core_init (struct flash040_context_s *flash040_context, struct alarm_context_s *alarm_context, flash040_type_t type, uint8_t *data)
void flash040core_shutdown (flash040_context_t *flash040_context)
int flash040core_snapshot_write_module (snapshot_t *s, flash040_context_t *flash040_context, const char *name)
int flash040core_snapshot_read_module (snapshot_t *s, flash040_context_t *flash040_context, const char *name)
Variables
static const flash_types_t flash_types [FLASH040_TYPE_NUM]
Macro Definition Documentation
FLASH040_DUMP_VER_MAJOR
#define FLASH040_DUMP_VER_MAJOR 2
FLASH040_DUMP_VER_MINOR
#define FLASH040_DUMP_VER_MINOR 0
FLASH_DEBUG
#define FLASH_DEBUG (x)
Typedef Documentation
flash_types_t
typedef struct flash_types_s flash_types_t
Function Documentation
erase_alarm_handler()
static void erase_alarm_handler (CLOCK offset, void * data) static
Referenced by flash040core_init().
flash040core_init()
void flash040core_init (struct flash040_context_s * flash040_context, struct alarm_context_s * alarm_context, flash040_type_t type, uint8_t * data)
flash040core_peek()
uint8_t flash040core_peek (flash040_context_t * flash040_context, unsigned int addr)
flash040core_read()
uint8_t flash040core_read (flash040_context_t * flash040_context, unsigned int addr)
flash040core_reset()
void flash040core_reset (flash040_context_t * flash040_context)
flash040core_shutdown()
void flash040core_shutdown (flash040_context_t * flash040_context)
flash040core_snapshot_read_module()
int flash040core_snapshot_read_module (snapshot_t * s, flash040_context_t * flash040_context, const char * name)
flash040core_snapshot_write_module()
int flash040core_snapshot_write_module (snapshot_t * s, flash040_context_t * flash040_context, const char * name)
flash040core_store()
void flash040core_store (flash040_context_t * flash040_context, unsigned int addr, uint8_t byte)
flash040core_store_internal()
static void flash040core_store_internal (flash040_context_t * flash040_context, unsigned int addr, uint8_t byte) static
Referenced by flash040core_store().
flash_add_sector_to_erase_mask()
static void flash_add_sector_to_erase_mask (flash040_context_t * flash040_context, unsigned int addr) inline static
Referenced by flash040core_store_internal().
flash_addr_to_sector_number()
static unsigned int flash_addr_to_sector_number (flash040_context_t * flash040_context, unsigned int addr) inline static
Referenced by flash_add_sector_to_erase_mask().
flash_clear_erase_mask()
static void flash_clear_erase_mask (flash040_context_t * flash040_context) inline static
Referenced by flash040core_init(), flash040core_reset(), and flash040core_store_internal().
flash_erase_chip()
static void flash_erase_chip (flash040_context_t * flash040_context) inline static
Referenced by erase_alarm_handler().
flash_erase_operation_status()
static int flash_erase_operation_status (flash040_context_t * flash040_context) inline static
Referenced by flash040core_read().
flash_erase_sector()
static void flash_erase_sector (flash040_context_t * flash040_context, unsigned int sector) inline static
Referenced by erase_alarm_handler().
flash_magic_1()
static int flash_magic_1 (flash040_context_t * flash040_context, unsigned int addr) inline static
Referenced by flash040core_store_internal().
flash_magic_2()
static int flash_magic_2 (flash040_context_t * flash040_context, unsigned int addr) inline static
Referenced by flash040core_store_internal().
flash_program_byte()
static int flash_program_byte (flash040_context_t * flash040_context, unsigned int addr, uint8_t byte) inline static
Referenced by flash040core_store_internal().
flash_sector_to_addr()
static unsigned int flash_sector_to_addr (flash040_context_t * flash040_context, unsigned int sector) inline static
Referenced by flash_erase_sector().
flash_write_operation_status()
static int flash_write_operation_status (flash040_context_t * flash040_context) inline static
Referenced by flash040core_read().
Variable Documentation
flash_types
const flash_types_t flash_types[FLASH040_TYPE_NUM] static
Initial value:
= {
    { 0x01, 0xa4, 1,
      0x80000,
      0x70000, 0x10000, 16,
      0x5555, 0x2aaa, 0x7fff, 0x7fff,
      0x40,
      80, 2000000, 14000000},
    { 0x01, 0xa4, 1,
      0x80000,
      0x70000, 0x10000, 16,
      0x555, 0x2aa, 0x7ff, 0x7ff,
      0x40,
      50, 1000000, 8000000},
    { 0x01, 0x20, 1,
      0x20000,
      0x1c000, 0x04000, 14,
      0x5555, 0x2aaa, 0x7fff, 0x7fff,
      0x40,
      80, 1000000, 1000000 },
    { 0x01, 0x41, 1,
      0x400000,
      0x3f0000, 0x10000, 16,
      0x556, 0x2a9, 0x7ff, 0x7ff,
      0x44,
      50, 1000000, 64000000 },
    { 0x01, 0x7e, 2,
      0x800000,
      0x7f0000, 0x10000, 16,
      0xaaa, 0x555, 0xfff, 0xfff,
      0x40,
      50, 500000, 64000000},
}
Referenced by erase_alarm_handler(), flash040core_read(), flash040core_snapshot_read_module(), flash040core_store_internal(), flash_addr_to_sector_number(), flash_erase_chip(), flash_erase_operation_status(), flash_erase_sector(), flash_magic_1(), flash_magic_2(), and flash_sector_to_addr().