vsid: arch/gtk3/ui.c File Reference
ui.c File Reference
Native GTK3 UI stuff.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdio.h>
#include <string.h>
#include <limits.h>
#include <unistd.h>
#include "archdep.h"
#include "attach.h"
#include "autostart.h"
#include "basedialogs.h"
#include "cmdline.h"
#include "cartridgewidgets.h"
#include "crtcontrolwidget.h"
#include "debug.h"
#include "debug_gtk3.h"
#include "drive.h"
#include "extendimagedialog.h"
#include "fullscreen.h"
#include "hotkeys.h"
#include "interrupt.h"
#include "jamdialog.h"
#include "kbd.h"
#include "lib.h"
#include "lightpen.h"
#include "log.h"
#include "machine.h"
#include "mainlock.h"
#include "mixerwidget.h"
#include "monitor.h"
#include "resources.h"
#include "settings_keyboard.h"
#include "settings_rom.h"
#include "types.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uicart.h"
#include "uidata.h"
#include "uidiskattach.h"
#include "uihotkeys.h"
#include "uimachinemenu.h"
#include "uimachinewindow.h"
#include "uimedia.h"
#include "uimenu.h"
#include "uimon.h"
#include "uisettings.h"
#include "uismartattach.h"
#include "uistatusbar.h"
#include "uitapeattach.h"
#include "util.h"
#include "videoarch.h"
#include "vsync.h"
#include "vsyncapi.h"
#include "widgethelpers.h"
#include "actions-cartridge.h"
#include "actions-clipboard.h"
#include "actions-datasette.h"
#include "actions-display.h"
#include "actions-drive.h"
#include "actions-help.h"
#include "actions-hotkeys.h"
#include "actions-joystick.h"
#include "actions-machine.h"
#include "actions-media.h"
#include "actions-printer.h"
#include "actions-settings.h"
#include "actions-snapshot.h"
#include "actions-speed.h"
#include "ui.h"
Data Structures
struct ui_resources_s
Struct holding basic UI rescources.
Typedefs
typedef struct ui_resources_s ui_resource_t
Struct holding basic UI rescources.
Enumerations
enum {
ROW_MENU_BAR = 0 ,
ROW_DISPLAY ,
ROW_STATUS_BAR ,
ROW_CRT_CONTROLS ,
ROW_MIXER_CONTROLS
}
Row numbers of the various widgets packed in a main GtkWindow.
Functions
static int set_save_resources_on_exit (gboolean save_on_exit, void *unused)
for the fullscreen_capability() stub
static int set_confirm_on_exit (gboolean confirm_on_exit, void *unused)
Set ConfirmOnExit resource.
static int set_window_height (gint height, void *window_index)
Set Window[X]Height resource.
static int set_window_width (gint width, void *window_index)
Set Window[X]Width resource.
static int set_window_xpos (gint xpos, void *window_index)
Set Window[X]Xpos resource.
static int set_window_ypos (gint ypos, void *window_index)
Set Window[X]Ypos resource (int)
static int set_start_minimized (gboolean start_minimized, void *unused)
Set StartMinimized resource.
static int set_native_monitor (gboolean use_native_monitor, void *unused)
Set NativeMonitor resource (bool)
static int set_monitor_font (const gchar *font_description, void *param)
Resource handler: set monitor font for VTE-based monitor.
static int set_monitor_bg (const gchar *color, void *param)
Resource handler: set monitor background color for VTE-based monitor.
static int set_monitor_fg (const gchar *color, void *param)
Resource handler: set monitor foreground color for VTE-based monitor.
static int set_fullscreen_decorations (gboolean fullscreen_decorations, void *unused)
Resource setter for "FullscreenDecorations".
static int set_pause_on_settings (gboolean pause_on_settings, void *param)
Set PauseOnSettings resource.
static int set_autostart_on_doubleclick (gboolean autostart_on_doubleclick, void *unused)
Set AutostartOnDoubleClick resource.
static int set_monitor_xpos (const gchar *xpos, void *window_index)
Cmdline handler for -monitorxpos, -windowxpos, -windowxpos1.
static int set_monitor_ypos (const gchar *ypos, void *window_index)
Cmdline handler for -monitorypos, -windowypos, -windowypos1.
static int set_monitor_width (const gchar *width, void *window_index)
Cmdline handler for -monitorwidth, -windowwidth, -windowwidth1.
static int set_monitor_height (const gchar *height, void *window_index)
Cmdline handler for -monitorheight, -windowheight, -windowheight1.
static int set_settings_node_path (const gchar *path, void *param)
Set settings node path to activate on UI startup.
static int window_index_from_param (void *param)
Get a window-spec array index from param.
static void ui_action_dispatch (ui_action_map_t *map)
Dispatcher for UI actions.
static gboolean on_drag_drop (GtkWidget *widget, GdkDragContext *context, gint x, gint y, guint time, gpointer data)
Handler for the 'drag-drop' event of the GtkWindow(s)
static gchar * drag_data_get_filename (GtkSelectionData *data, guint info)
Extract filename from drag data.
static void on_drag_data_received (GtkWidget *widget, GdkDragContext *context, gint x, gint y, GtkSelectionData *data, guint info, guint time)
Handler for the 'drag-data-received' event.
static gboolean on_delete_event (GtkWidget *widget, GdkEvent *event, gpointer user_data)
Handler for the 'delete-event' of a main window.
static gboolean on_focus_in_event (GtkWidget *widget, GdkEventFocus *event, gpointer user_data)
Handler for the "focus-in-event" of a main window.
static gboolean on_focus_out_event (GtkWidget *widget, GdkEventFocus *event, gpointer user_data)
Handler for the "focus-out-event" of a main window.
static gboolean on_window_state_event (GtkWidget *widget, GdkEventWindowState *event, gpointer user_data)
Handler for the "window-state-event" of a main window.
static GdkPixbuf * get_default_icon (void)
Create an icon by loading it from the vice.gresource file.
static gboolean ui_action_dispatch_impl (gpointer data)
Dispatch function and its helper for the UI actions.
GtkWindow * ui_get_active_window (void)
Get the most recently focused toplevel window.
video_canvas_t * ui_get_active_canvas (void)
Get video canvas of active window.
video_canvas_t * ui_get_canvas_for_window (int index)
Get canvas by main window index.
int ui_get_main_window_index (void)
Get the active main window's index.
GtkWidget * ui_get_main_window_by_index (gint index)
Get active main window.
int ui_get_window_index (GtkWidget *widget)
Get a window's index.
void ui_update_fullscreen_decorations (void)
Show or hide the decorations of the active main window as needed.
void fullscreen_capability (struct cap_fullscreen_s *cap_fullscreen)
Stub to satisfy the various $videochip-resources.c files.
gboolean ui_is_fullscreen_from_canvas (const video_canvas_t *canvas)
Determine fullscreen state via canvas.
gboolean ui_is_fullscreen (void)
Checks if we're in fullscreen mode.
void ui_set_fullscreen_enabled (gboolean enabled)
Enable/disable fullscreen for current canvas.
void ui_trigger_resize (void)
Updates UI in response to the simulated machine screen changing its dimensions or aspect ratio.
void ui_set_handle_dropped_files_func (int(*func)(const char *))
Set function to handle files dropped on a main window.
void ui_set_create_window_func (void(*func)(video_canvas_t *))
Set function to help create the main window(s)
void ui_set_identify_canvas_func (int(*func)(video_canvas_t *))
Set function to identify a canvas from its video chip.
void ui_set_create_controls_widget_func (GtkWidget *(*func)(int))
Set function to help create the CRT controls widget(s)
static void on_window_grid_destroy (GtkWidget *widget, gpointer data)
Handler for the "destroy" event of widget.
static gboolean on_window_configure_event (GtkWidget *widget, GdkEvent *event, gpointer data)
Handler for window 'configure' events.
static gboolean rendering_area_event_handler (GtkWidget *canvas, GdkEventButton *event, gpointer data)
Event handler for the rendering area's button presses.
static bool set_window_geometry_from_resources (int index)
Set window geomeotry of a window by index from resources.
void ui_set_window_geometries (void)
Set geometry of (both) emulated display window(s) from resources.
void ui_create_main_window (video_canvas_t *canvas)
Create a toplevel window to represent a video canvas.
void ui_display_main_window (int index)
Makes a main window visible once it's been initialized.
void ui_destroy_main_window (int index)
Destroy a main window.
int ui_cmdline_options_init (void)
Initialize command line options (generic)
char * ui_get_file (const char *format,...)
Display a generic file chooser dialog.
void ui_init_with_args (int *argc, char **argv)
Initialize Gtk3/GLib.
int ui_init (void)
Initialize UI.
int ui_init_finalize (void)
Finalize initialization after creating the main window(s)
static gboolean ui_jam_dialog_impl (gpointer user_data)
JAM dialog handler for the threaded UI.
ui_jam_action_t ui_jam_dialog (const char *format,...)
Display a dialog box in response to a CPU jam.
int ui_resources_init (void)
Initialize resources related to the UI in general.
void ui_resources_shutdown (void)
Clean up memory used by VICE resources.
void ui_shutdown (void)
Clean up memory used by the UI system itself.
static gboolean ui_extendimage_dialog_impl (gpointer user_data)
extend image dialog handler for the threaded UI
int ui_extend_image_dialog (void)
Display the "Do you want to extend the disk image?" dialog.
void ui_dispatch_events (void)
Not used.
void arch_ui_activate (void)
Show settings dialog from a joystick button.
static gboolean ui_error_impl (gpointer user_data)
Error dialog handler for the threaded UI.
void ui_error (const char *format,...)
Display error message through the UI.
static gboolean ui_message_impl (gpointer user_data)
Message dialog handler for the threaded UI.
void ui_message (const char *format,...)
Display a message through the UI.
bool ui_pause_loop_iteration (void)
Perform a single iteration of the pause loop.
static void pause_loop (void *param)
Keeps the ui events going while the emulation is paused.
int ui_pause_active (void)
Get pause active state.
void ui_pause_enable (void)
Pause emulation.
void ui_pause_disable (void)
Unpause emulation.
void ui_pause_enter_monitor (void)
The pause loop should trigger the monitor.
void ui_pause_toggle (void)
Toggle pause state.
void ui_exit (void)
Destroy UI resources (but NOT vice 'resources')
void ui_update_lightpen (void)
Send current light pen state to the emulator core for all windows.
void ui_enable_crt_controls (int enabled)
Enable/disable CRT controls.
void ui_enable_mixer_controls (int enabled)
Enable/disable mixer controls.
GtkWidget * ui_get_window_by_index (int index)
Get GtkWindow instance by index.
gboolean ui_fullscreen_has_decorations (void)
Determine if the window should have decorations in fullscreen mode.
Variables
GtkTargetEntry ui_drag_targets [3]
List of drag targets for the drag-n-drop event handler.
static ui_resource_t ui_resources
Collection of UI resources.
static int fullscreen_has_decorations = 0
Flag inidicating whether fullscreen mode shows the decorations.
static const char * settings_node_path = NULL
Settings node to activate after booting the emulator.
static const resource_string_t resources_string []
String type resources list.
static const resource_int_t resources_int_shared []
Boolean and integer resources shared between windows.
static const resource_int_t resources_int_primary_window []
Window size and position resources for the primary window.
static const resource_int_t resources_int_secondary_window []
Window size and position resources list for the secondary window.
static const cmdline_option_t cmdline_options_common []
Command line options shared between emu's, include VSID.
static int is_paused = 0
Flag indicating pause mode.
static int enter_monitor_while_paused = 0
Flag indicating that the monitor should be entered whilst paused.
static int active_win_index = -1
Index of the most recently focused main window.
static int(* handle_dropped_files_func)(const char *) = NULL
Function to handle files dropped on a main window.
static void(* create_window_func)(video_canvas_t *) = NULL
Function to help create a main window.
static int(* identify_canvas_func)(video_canvas_t *) = NULL
Function to identify a canvas from its video chip.
static GtkWidget *(* create_controls_widget_func)(int) = NULL
Function to help create a CRT controls widget.
static ui_jam_action_t jam_dialog_result
Result of the JAM dialog.
static ui_extendimage_action_t extendimage_dialog_result
Result of the extend image dialog.
Detailed Description
Native GTK3 UI stuff.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Marcus Sutton logge.nosp@m.doub.nosp@m.t@gma.nosp@m.il.c.nosp@m.om
$VICERES AutostartOnDoubleclick all $VICERES CrtcFullscreen xcbm2 xpet $VICERES TEDFullscreen xplus4 $VICERES VDCFullscreen x128 $VICERES VICFullscreen xvic $VICERES VICIIFullscreen x64 x64sc x64dtv xscpu64 x128 xcbm5x0 $VICERES MonitorBG all $VICERES MonitorFG all $VICERES MonitorFont all $VICERES MonitorXPos all $VICERES MonitorYPos all $VICERES MonitorWidth all $VICERES MonitorHeight all $VICERES Window0Height -vsid $VICERES Window0Width -vsid $VICERES Window0Xpos -vsid $VICERES Window0Ypos -vsid $VICERES Window1Height x128 $VICERES Window1Width x128 $VICERES Window1Xpos x128 $VICERES Window1Ypos x128
Typedef Documentation
ui_resource_t
typedef struct ui_resources_s ui_resource_t
Struct holding basic UI rescources.
Enumeration Type Documentation
anonymous enum
anonymous enum
Row numbers of the various widgets packed in a main GtkWindow.
Enumerator
ROW_MENU_BAR
application menu bar
ROW_DISPLAY
emulated display
ROW_STATUS_BAR
status bar
ROW_CRT_CONTROLS
CRT control widgets.
ROW_MIXER_CONTROLS
mixer control widgets
Function Documentation
arch_ui_activate()
void arch_ui_activate (void)
Show settings dialog from a joystick button.
drag_data_get_filename()
static gchar * drag_data_get_filename (GtkSelectionData * data, guint info) static
Extract filename from drag data.
Parameters
[in] data drag data from dropping media onto the emulator window
[in] info drag target mime type info
Returns
filename or NULL
Note
the filename should be freed with g_free() after use
Todo:
Perhaps make public, VSID uses duplicate code.
Referenced by on_drag_data_received().
fullscreen_capability()
void fullscreen_capability (struct cap_fullscreen_s * cap_fullscreen)
Stub to satisfy the various $videochip-resources.c files.
Parameters
[in] cap_fullscreen unused
Referenced by vicii_resources_init().
get_default_icon()
static GdkPixbuf * get_default_icon (void) static
Create an icon by loading it from the vice.gresource file.
Returns
App icon for the current machine
Todo:
Refactor to use arch/shared/archdep_icon_path.c
Todo:
Can we figure out the right icon size on Windows, Linux?
Referenced by ui_create_main_window().
on_delete_event()
static gboolean on_delete_event (GtkWidget * widget, GdkEvent * event, gpointer user_data) static
Handler for the 'delete-event' of a main window.
Parameters
[in] widget window triggering the event (unused)
[in] event event details (unused)
[in] user_data extra data for the event (unused)
Returns
TRUE, if the function returns at all
Referenced by ui_create_main_window().
on_drag_data_received()
static void on_drag_data_received (GtkWidget * widget, GdkDragContext * context, gint x, gint y, GtkSelectionData * data, guint info, guint time) static
Handler for the 'drag-data-received' event.
Autostarts an image/prg when valid. Please note that VSID now has its own drag-n-drop handlers.
Parameters
[in] widget widget triggering the event (unused)
[in] context drag context (unused)
[in] x probably X-coordinate in the drop target?
[in] y probablt Y-coordinate in the drop target?
[in] data dragged data
[in] info int declared in the targets array (unclear)
[in] time no idea
Referenced by ui_create_main_window().
on_drag_drop()
static gboolean on_drag_drop (GtkWidget * widget, GdkDragContext * context, gint x, gint y, guint time, gpointer data) static
Handler for the 'drag-drop' event of the GtkWindow(s)
Can be used to filter certain drop targets or altering the data before triggering the 'drag-drop-received' event. Currently just returns TRUE
Parameters
[in] widget widget triggering the event
[in] context gtk drag context
[in] x x position of drag event
[in] y y position of drag event
[in] time (I don't have a clue)
[in] data extra event data (unused)
Returns
TRUE
Referenced by ui_create_main_window().
on_focus_in_event()
static gboolean on_focus_in_event (GtkWidget * widget, GdkEventFocus * event, gpointer user_data) static
Handler for the "focus-in-event" of a main window.
Parameters
[in] widget window triggering the event
[in] event window focus details
[in] user_data extra data for the event (ignored)
Returns
FALSE to continue processing
Note
We only use this for canvas-window-specific stuff like fullscreen mode.
Referenced by ui_create_main_window().
on_focus_out_event()
static gboolean on_focus_out_event (GtkWidget * widget, GdkEventFocus * event, gpointer user_data) static
Handler for the "focus-out-event" of a main window.
Parameters
[in] widget window triggering the event
[in] event window focus details
[in] user_data extra data for the event (ignored)
Returns
FALSE to continue processing
Note
We only use this for canvas-window-specific stuff like fullscreen mode.
Referenced by ui_create_main_window().
on_window_configure_event()
static gboolean on_window_configure_event (GtkWidget * widget, GdkEvent * event, gpointer data) static
Handler for window 'configure' events.
Triggered when a window is moved or changes size. Used currently to update the Window[01]* resources to allow restoring window size and position on emulator start.
Parameters
[in] widget widget triggering the event
[in] event event reference
[in] data extra event data (used to pass window index)
Returns
bool
Referenced by ui_create_main_window().
on_window_grid_destroy()
static void on_window_grid_destroy (GtkWidget * widget, gpointer data) static
Handler for the "destroy" event of widget.
Looks like debug code. But better keep it here to debug the warnings about GtkEventBox'es getting destroyed prematurely.
Parameters
[in] widget widget triggering the event
[in] data extra event data (unused)
Referenced by ui_create_main_window().
on_window_state_event()
static gboolean on_window_state_event (GtkWidget * widget, GdkEventWindowState * event, gpointer user_data) static
Handler for the "window-state-event" of a main window.
Parameters
[in] widget window triggering the event
[in] event window state details
[in] user_data extra data for the event (ignored)
Returns
FALSE to continue processing
Note
This handler is not used on VSID since we have neither fullscreen nor fullscreen decorations in VSID
Referenced by ui_create_main_window().
pause_loop()
static void pause_loop (void * param) static
Keeps the ui events going while the emulation is paused.
Referenced by pause_loop(), and ui_pause_enable().
rendering_area_event_handler()
static gboolean rendering_area_event_handler (GtkWidget * canvas, GdkEventButton * event, gpointer data) static
Event handler for the rendering area's button presses.
Currently switches fullscreen mode when double-clicking, but can also be used to present a context menu to for some video settings via right-click, which is one of our many TODO's.
Parameters
[in] canvas rendering area
[in] event event object
[in] data GtkWindow parent of canvas
Returns
TRUE if event accepted
Referenced by ui_create_main_window().
set_autostart_on_doubleclick()
static int set_autostart_on_doubleclick (gboolean autostart_on_doubleclick, void * unused) static
Set AutostartOnDoubleClick resource.
Parameters
[in] autostart_on_doublelick autostart when doubleclicking in attach dialogs
[in] unused extra param (ignored)
Returns
0
set_confirm_on_exit()
static int set_confirm_on_exit (gboolean confirm_on_exit, void * unused) static
Set ConfirmOnExit resource.
Parameters
[in] confirm_on_exit pop up confirmation dialog on exit
[in] unused extra param (ignored)
Returns
0
set_fullscreen_decorations()
static int set_fullscreen_decorations (gboolean fullscreen_decorations, void * unused) static
Resource setter for "FullscreenDecorations".
Parameters
[in] enabled enable fullscreen decorations
[in] unused extra argument (unused)
Returns
0
set_monitor_bg()
static int set_monitor_bg (const gchar * color, void * param) static
Resource handler: set monitor background color for VTE-based monitor.
Parameters
[in] color Gdk RGBA color string
[in] unused extra argument (unused)
Returns
0 on success, -1 if color could not be parsed by gdk_rgba_parse()
set_monitor_fg()
static int set_monitor_fg (const gchar * color, void * param) static
Resource handler: set monitor foreground color for VTE-based monitor.
Parameters
[in] color Gdk RGBA color string
[in] unused extra argument (unused)
Returns
0 on success, -1 if color could not be parsed by gdk_rgba_parse()
set_monitor_font()
static int set_monitor_font (const gchar * font_description, void * param) static
Resource handler: set monitor font for VTE-based monitor.
Parameters
[in] font_description font description, passed to Pango
[in] unused extra argument (unused)
Returns
0 (success)
set_monitor_height()
static int set_monitor_height (const gchar * height, void * window_index) static
Cmdline handler for -monitorheight, -windowheight, -windowheight1.
Parameters
[in] height height in pixels as string
[in] window_index window index
Returns
0 on success
set_monitor_width()
static int set_monitor_width (const gchar * width, void * window_index) static
Cmdline handler for -monitorwidth, -windowwidth, -windowwidth1.
Parameters
[in] width width in pixels as string
[in] window_index window index
Returns
0 on success
set_monitor_xpos()
static int set_monitor_xpos (const gchar * xpos, void * window_index) static
Cmdline handler for -monitorxpos, -windowxpos, -windowxpos1.
Parameters
[in] xpos xpos in pixels as string
[in] window_index window index
Returns
0 on success
set_monitor_ypos()
static int set_monitor_ypos (const gchar * ypos, void * window_index) static
Cmdline handler for -monitorypos, -windowypos, -windowypos1.
Parameters
[in] ypos ypos in pixels as string
[in] window_index window index
Returns
0 on success
set_native_monitor()
static int set_native_monitor (gboolean use_native_monitor, void * unused) static
Set NativeMonitor resource (bool)
Use the spawning shell for the monitor instead of the VTE widget.
Parameters
[in] use_native_monitor use native monitor instead of VTE
[in] unused extra param (ignored)
Returns
0
Todo:
FIXME: setting this to 1 should probably fail if either stdin or stdout is not a terminal.
set_pause_on_settings()
static int set_pause_on_settings (gboolean pause_on_settings, void * param) static
Set PauseOnSettings resource.
Parameters
[in] pause_on_settings pause emulation when entering the settings dialog
[in] unused extra param (ignored)
Returns
0
set_save_resources_on_exit()
static int set_save_resources_on_exit (gboolean save_on_exit, void * unused) static
for the fullscreen_capability() stub
Set SaveResourcesOnExit resource.
UI action implementations
Parameters
[in] save_on_exit save resources on emulator exit
[in] unused extra param (ignored)
Returns
0
set_settings_node_path()
static int set_settings_node_path (const gchar * path, void * param) static
Set settings node path to activate on UI startup.
Triggers opening the settings dialog at node path once when starting VICE.
Useful for working on settings dialogs, avoiding clicking through the UI. For example: x64sc -settings-node peripheral/drive will open the drive settings.
Parameters
[in] path setting node path
[in] unused extra data (unused);
Returns
0
set_start_minimized()
static int set_start_minimized (gboolean start_minimized, void * unused) static
Set StartMinimized resource.
Parameters
[in] start_minimized start the emulator window minimized
[in] unused extra param (ignored)
Returns
0
set_window_geometry_from_resources()
static bool set_window_geometry_from_resources (int index) static
Set window geomeotry of a window by index from resources.
Parameters
[in] index window index (PRIMARY_WINDOW or SECONDARY_WINDOW)
Returns
true if the geomeotry for the given index was set due to the resources not containing their default values
Referenced by ui_create_main_window(), and ui_set_window_geometries().
set_window_height()
static int set_window_height (gint height, void * window_index) static
Set Window[X]Height resource.
Parameters
[in] height height in pixels
[in] window_index window index
Returns
0
Referenced by set_monitor_height().
set_window_width()
static int set_window_width (gint width, void * window_index) static
Set Window[X]Width resource.
Parameters
[in] width width in pixels
[in] window_index window index
Returns
0
Referenced by set_monitor_width().
set_window_xpos()
static int set_window_xpos (gint xpos, void * window_index) static
Set Window[X]Xpos resource.
Parameters
[in] xpos xpos in pixels
[in] window_index window index
Returns
0
Referenced by set_monitor_xpos().
set_window_ypos()
static int set_window_ypos (gint ypos, void * window_index) static
Set Window[X]Ypos resource (int)
Parameters
[in] ypos ypos in pixels
[in] window_index window index
Returns
0
Referenced by set_monitor_ypos().
ui_action_dispatch()
static void ui_action_dispatch (ui_action_map_t * map) static
Dispatcher for UI actions.
Executes UI action handler on the the UI thread if requested.
Parameters
[in] map UI action map
Referenced by ui_init_finalize().
ui_action_dispatch_impl()
static gboolean ui_action_dispatch_impl (gpointer data) static
Dispatch function and its helper for the UI actions.
GSourceFunc to call a UI action
Parameters
[in] data UI action map
Returns
G_SOURCE_REMOVE to remove this timeout source
Referenced by ui_action_dispatch().
ui_cmdline_options_init()
int ui_cmdline_options_init (void)
Initialize command line options (generic)
Returns
0 on success, -1 on failure
Referenced by init_cmdline_options().
ui_create_main_window()
void ui_create_main_window (video_canvas_t * canvas)
Create a toplevel window to represent a video canvas.
This function takes a video canvas structure and builds the widgets that will represent that canvas in the UI as a whole.
While it creates the widgets, it does not make them visible. The video canvas routines are expected to do any last-minute processing or preparation, and then call ui_display_main_window() when ready.
Parameters
[in] canvas the video_canvas_s to initialize
Warning
The order of the windows created for x128 depends on the order of the calls to vicii_init() and vdc_init() in src/c128/c128.c. That order is currently set to vicii before vdc so we get the proper window indexes. There has to be a better way.
Referenced by video_canvas_create(), and vsid_ui_init().
ui_destroy_main_window()
void ui_destroy_main_window (int index)
Destroy a main window.
Parameters
[in] index which window to destroy
See also
ui_resources_s::window_widget
Referenced by ui_exit().
ui_dispatch_events()
void ui_dispatch_events (void)
Not used.
Referenced by monitor_network_get_command_line(), and uimon_in().
ui_display_main_window()
void ui_display_main_window (int index)
Makes a main window visible once it's been initialized.
Parameters
[in] index which window to display
See also
ui_resources_s::window_widget
Referenced by video_canvas_create(), and vsid_ui_init().
ui_enable_crt_controls()
void ui_enable_crt_controls (int enabled)
Enable/disable CRT controls.
Parameters
[in] enabled enabled state for the CRT controls
Referenced by on_crt_toggled().
ui_enable_mixer_controls()
void ui_enable_mixer_controls (int enabled)
Enable/disable mixer controls.
Parameters
[in] enabled enabled state for the mixer controls
Referenced by on_mixer_toggled().
ui_error()
void ui_error (const char * format, ...)
Display error message through the UI.
Print an error message.
Parameters
[in] format format string for the error
ui_error_impl()
static gboolean ui_error_impl (gpointer user_data) static
Error dialog handler for the threaded UI.
Parameters
[in] user_data error message (allocated by VICE)
Returns
G_SOURCE_REMOVE to only run once
Referenced by ui_error().
ui_exit()
void ui_exit (void)
Destroy UI resources (but NOT vice 'resources')
Don't call this directly except from main_exit();
Referenced by main_exit().
ui_extend_image_dialog()
int ui_extend_image_dialog (void)
Display the "Do you want to extend the disk image?" dialog.
Returns
nonzero to extend the image, 0 otherwise
Todo:
FIXME: ideally we would somehow get the drive and perhaps name of the mounted image and put it into the message.
Referenced by drive_gcr_data_writeback().
ui_extendimage_dialog_impl()
static gboolean ui_extendimage_dialog_impl (gpointer user_data) static
extend image dialog handler for the threaded UI
Parameters
[in] user_data message
Returns
FALSE
Referenced by ui_extend_image_dialog().
ui_fullscreen_has_decorations()
gboolean ui_fullscreen_has_decorations (void)
Determine if the window should have decorations in fullscreen mode.
Returns
bool
Referenced by fullscreen_decorations_toggle_action(), and ui_statusbar_set_visible_for_window().
ui_get_active_canvas()
video_canvas_t * ui_get_active_canvas (void)
Get video canvas of active window.
Returns
current active video canvas, or NULL
Referenced by on_save_screenshot_filename(), on_save_video_filename(), screenshot_ui_auto_screenshot(), ui_action_toggle_show_statusbar(), ui_is_fullscreen(), ui_set_fullscreen_enabled(), and ui_update_fullscreen_decorations().
ui_get_active_window()
GtkWindow * ui_get_active_window (void)
Get the most recently focused toplevel window.
Returns
pointer to a toplevel window, or NULL
Note
Not an event handler, needs to be moved
Referenced by cart_dialog_internal(), create_disk_attach_dialog(), create_sid_attach_dialog(), create_smart_attach_dialog(), create_tape_attach_dialog(), dialog_create_helper(), extendimage_dialog(), keyset_dialog_show(), on_icon_press(), on_launcher_clicked(), open_dialog_new(), restore_display_action(), save_dialog_new(), save_snapshot_dialog(), show_hotkey_dialog(), ui_about_dialog_show(), ui_action_toggle_show_statusbar(), ui_disk_create_dialog_show(), ui_fliplist_load_dialog_show(), ui_fliplist_save_dialog_show(), ui_media_dialog_show(), ui_set_fullscreen_enabled(), ui_tape_create_dialog_show(), uicmdline_dialog_show(), uicompiletimefeatures_dialog_show(), vice_gtk3_integer_input_box(), vice_gtk3_message_confirm(), vice_gtk3_message_error(), vice_gtk3_message_info(), vice_gtk3_open_create_file_dialog(), vice_gtk3_open_file_dialog(), vice_gtk3_save_file_dialog(), vice_gtk3_select_directory_dialog(), and vsid_playlist_add_dialog_create().
ui_get_canvas_for_window()
video_canvas_t * ui_get_canvas_for_window (int index)
Get canvas by main window index.
Parameters
[in] index window index (PRIMARY_WINDOW or SECONDARY_WINDOW)
Returns
video canvas or NULL on error
Referenced by actions_display_setup_ui(), border_mode_action(), show_statusbar_toggle_action(), and ui_statusbar_recreate_crt_controls().
ui_get_file()
char * ui_get_file (const char * format, ...)
Display a generic file chooser dialog.
Let the user browse for a filename; display format as a titel.
Parameters
[in] format format string for the dialog's title
Returns
a copy of the chosen file's name; free it with lib_free()
Note
This is currently only called by event_playback_attach_image()
Warning
This function is unimplemented and will intentionally crash VICE if it is called.
Referenced by event_playback_attach_image().
ui_get_main_window_by_index()
GtkWidget * ui_get_main_window_by_index (gint index)
Get active main window.
Parameters
[in] index window index (PRIMARY WINDOW or SECONDARY_WINDOW)
Returns
window or NULL when index is out of bounds
Referenced by mouse_grab_toggle_action().
ui_get_main_window_index()
int ui_get_main_window_index (void)
Get the active main window's index.
Returns
index of a main emulator window
Referenced by fullscreen_toggle_action(), on_hide_vdc_toggled(), speed_cpu_custom_action(), speed_fps_custom_action(), ui_statusbar_get_recording_widget(), uimon_window_suspend_impl(), and video_arch_get_active_chip().
ui_get_window_by_index()
GtkWidget * ui_get_window_by_index (int index)
Get GtkWindow instance by index.
Parameters
[in] index index in the windows widgets array (0-2)
Returns
GtkWindow instance
Referenced by double_size_callback(), on_hide_vdc_toggled(), show_statusbar_secondary_toggle_action(), show_statusbar_toggle_action(), ui_mouse_grab_pointer(), ui_statusbar_recreate_crt_controls(), ui_statusbar_set_kbd_debug(), uimon_window_suspend_impl(), and warp().
ui_get_window_index()
int ui_get_window_index (GtkWidget * widget)
Get a window's index.
Parameters
[in] widget window to get the index of
Returns
window index, or -1 if not a main window
Referenced by on_focus_in_event(), and on_window_state_event().
ui_init()
int ui_init (void)
Initialize UI.
Loads gresource data, disables F10 as the accelerator for the menu bar, registers the CBM font with the host and initializes the statusbar.
Returns
0
Referenced by main_program().
ui_init_finalize()
int ui_init_finalize (void)
Finalize initialization after creating the main window(s)
Currently sets the proper state for the CHIPShowStatusbar toggle buttons since the resources aren't yet initialized when creating the menu structure(s) and the main window(s) is/are created.
Returns
0 on success, -1 on failure
Referenced by init_main().
ui_init_with_args()
void ui_init_with_args (int * argc, char ** argv)
Initialize Gtk3/GLib.
Parameters
[in] argc pointer to main()'s argc
[in] argv main()'s argv
Returns
0 on success, -1 on failure
Referenced by main_program().
ui_is_fullscreen()
gboolean ui_is_fullscreen (void)
Checks if we're in fullscreen mode.
Determines fullscreen state by inspecting the "${CHIP}Fullscreen" resource for the active canvas.
Returns
nonzero if we're in fullscreen mode
Todo:
FIXME: During emu boot the array ui_resources.canvas[] will not be properly initialized yet, so when the opengl renderer calls this function during a realize() call the references will still be NULL and we cannot access the chip name, and thus not access CHIPFullscreen.
Referenced by double_size_callback(), fullscreen_toggle_action(), on_window_state_event(), restore_display_action(), ui_statusbar_set_visible_for_window(), and ui_update_fullscreen_decorations().
ui_is_fullscreen_from_canvas()
gboolean ui_is_fullscreen_from_canvas (const video_canvas_t * canvas)
Determine fullscreen state via canvas.
Work around situations where ui_is_fullscreen() cannot be used.
Parameters
[in] canvas video canvas reference
Returns
non-0 if fullscreen is enabled
Referenced by on_widget_resized(), and ui_create_main_window().
ui_jam_dialog()
ui_jam_action_t ui_jam_dialog (const char * format, ...)
Display a dialog box in response to a CPU jam.
Show a CPU JAM dialog.
Parameters
[in] format format string for the message to display
Returns
the action the user selected in response to the jam
Referenced by drive_jam(), and machine_jam().
ui_jam_dialog_impl()
static gboolean ui_jam_dialog_impl (gpointer user_data) static
JAM dialog handler for the threaded UI.
Parameters
[in] user_data message
Returns
FALSE
Referenced by ui_jam_dialog().
ui_message()
void ui_message (const char * format, ...)
Display a message through the UI.
Print a message.
Parameters
[in] format format string for message
Referenced by userport_set_device().
ui_message_impl()
static gboolean ui_message_impl (gpointer user_data) static
Message dialog handler for the threaded UI.
Parameters
[in] user_data message
Returns
FALSE
Referenced by ui_message().
ui_pause_active()
int ui_pause_active (void)
Get pause active state.
Returns
boolean
Referenced by actions_speed_setup_ui(), advance_frame_action(), create_pause_checkbox(), mon_exit(), mon_go(), monitor_open_action(), monitor_startup(), pause_toggle_action(), psid_pause_action(), speed_menu_popup_create(), statusbar_speed_widget_update(), ui_media_dialog_show(), ui_pause_toggle(), ui_settings_dialog_show(), ui_snapshot_load_snapshot(), ui_snapshot_save_snapshot(), and vice_opengl_on_ui_frame_clock().
ui_pause_disable()
void ui_pause_disable (void)
Unpause emulation.
Referenced by machine_reset_action(), monitor_startup(), on_dialog_destroy(), on_response(), pause_callback(), play_current_tune(), psid_ffwd_action(), psid_play_action(), psid_subtune_previous_action(), response_callback(), ui_pause_toggle(), ui_vsid_window_load_psid(), and vsyncarch_advance_frame().
ui_pause_enable()
void ui_pause_enable (void)
Pause emulation.
Referenced by advance_frame_action(), monitor_startup(), pause_callback(), response_callback(), ui_media_dialog_show(), ui_pause_toggle(), ui_settings_dialog_show(), and vsyncarch_postsync().
ui_pause_enter_monitor()
void ui_pause_enter_monitor (void)
The pause loop should trigger the monitor.
Referenced by monitor_open_action().
ui_pause_loop_iteration()
bool ui_pause_loop_iteration (void)
Perform a single iteration of the pause loop.
Returns
boolean whether to keep iterating
Referenced by monitor_startup(), and pause_loop().
ui_pause_toggle()
void ui_pause_toggle (void)
Toggle pause state.
Referenced by pause_toggle_action(), and psid_pause_action().
ui_resources_init()
int ui_resources_init (void)
Initialize resources related to the UI in general.
Initialization
Returns
0 on success, -1 on failure
Referenced by init_resources().
ui_resources_shutdown()
void ui_resources_shutdown (void)
Clean up memory used by VICE resources.
Referenced by cmdline_help(), and machine_shutdown().
ui_set_create_controls_widget_func()
void ui_set_create_controls_widget_func (GtkWidget *(*)(int) func)
Set function to help create the CRT controls widget(s)
Parameters
[in] func create CRT controls widget function
ui_set_create_window_func()
void ui_set_create_window_func (void(*)(video_canvas_t *) func)
Set function to help create the main window(s)
Parameters
[in] func create window function
Referenced by ui_machine_window_init(), and ui_vsid_window_init().
ui_set_fullscreen_enabled()
void ui_set_fullscreen_enabled (gboolean enabled)
Enable/disable fullscreen for current canvas.
Set the "${CHIP}Fullscreen" resource and enables or disables fullscreen mode for the main window of the current canvas.
Parameters
[in] enabled enable fullscreen
Referenced by fullscreen_toggle_action(), and on_window_state_event().
ui_set_handle_dropped_files_func()
void ui_set_handle_dropped_files_func (int(*)(const char *) func)
Set function to handle files dropped on a main window.
Prototypes.
Parameters
[in] func handle dropped files function
Referenced by ui_vsid_window_init().
ui_set_identify_canvas_func()
void ui_set_identify_canvas_func (int(*)(video_canvas_t *) func)
Set function to identify a canvas from its video chip.
Parameters
[in] func identify canvas function
Referenced by vsid_ui_init().
ui_set_window_geometries()
void ui_set_window_geometries (void)
Set geometry of (both) emulated display window(s) from resources.
Attempt to set the size and position of the display window(s) from resources.
Referenced by settings_load_action(), and settings_load_filename_callback().
ui_shutdown()
void ui_shutdown (void)
Clean up memory used by the UI system itself.
Referenced by cmdline_help(), and machine_shutdown().
ui_trigger_resize()
void ui_trigger_resize (void)
Updates UI in response to the simulated machine screen changing its dimensions or aspect ratio.
Referenced by ui_set_aspect_mode(), and ui_set_aspect_ratio().
ui_update_fullscreen_decorations()
void ui_update_fullscreen_decorations (void)
Show or hide the decorations of the active main window as needed.
Todo:
FIXME: this function does not work properly for vsid and should never get called by it, but at least on Macs it can get called if the user clicks the fullscreen button in the main vsid window.
Referenced by fullscreen_decorations_toggle_action(), fullscreen_toggle_action(), on_window_state_event(), and ui_display_main_window().
ui_update_lightpen()
void ui_update_lightpen (void)
Send current light pen state to the emulator core for all windows.
Referenced by vsyncarch_presync().
window_index_from_param()
static int window_index_from_param (void * param) static
Get a window-spec array index from param.
Also performs a bounds check and returns -1 on boundary violation.
Parameters
[in] param extra param passed to a setter
Returns
index in array or -1 on error
Referenced by set_window_height(), set_window_width(), set_window_xpos(), and set_window_ypos().
Variable Documentation
active_win_index
int active_win_index = -1 static
Index of the most recently focused main window.
Referenced by on_focus_in_event(), ui_display_main_window(), ui_enable_crt_controls(), ui_enable_mixer_controls(), ui_get_active_canvas(), ui_get_active_window(), ui_get_main_window_index(), and ui_update_fullscreen_decorations().
cmdline_options_common
const cmdline_option_t cmdline_options_common[] static
Initial value:
=
{
    { "-confirmonexit", SET_RESOURCE,  0 ,
        NULL, NULL, "ConfirmOnExit", (void *)1,
        NULL, "Confirm quitting VICE" },
    { "+confirmonexit", SET_RESOURCE,  0 ,
        NULL, NULL, "ConfirmOnExit", (void *)0,
        NULL, "Do not confirm quitting VICE" },
    { "-pauseonsettings", SET_RESOURCE,  0 ,
        NULL, NULL, "PauseOnSettings", (void *)1,
        NULL, "Pause emulation when activating settings dialog" },
    { "+pauseonsettings", SET_RESOURCE,  0 ,
        NULL, NULL, "PauseOnSettings", (void *)0,
        NULL, "Do not pause emulation when activating settings dialog" },
    { "-saveres", SET_RESOURCE,  0 ,
        NULL, NULL, "SaveResourcesOnExit", (void *)1,
        NULL, "Save settings on exit" },
    { "+saveres", SET_RESOURCE,  0 ,
        NULL, NULL, "SaveResourcesOnExit", (void *)0,
        NULL, "Do not save settings on exit" },
    { "-minimized", SET_RESOURCE,  0 ,
        NULL, NULL, "StartMinimized", (void *)1,
        NULL, "Start VICE minimized" },
    { "+minimized", SET_RESOURCE,  0 ,
        NULL, NULL, "StartMinimized", (void *)0,
        NULL, "Do not start VICE minimized" },
    { "-nativemonitor", SET_RESOURCE,  0 ,
        NULL, NULL, "NativeMonitor", (void *)1,
        NULL, "Use native monitor on OS terminal" },
    { "+nativemonitor", SET_RESOURCE,  0 ,
        NULL, NULL, "NativeMonitor", (void *)0,
        NULL, "Use VICE Gtk3 monitor terminal" },
    { "-fullscreen-decorations", SET_RESOURCE,  0 ,
        NULL, NULL, "FullscreenDecorations", (void*)1,
        NULL, "Enable fullscreen decorations" },
    { "+fullscreen-decorations", SET_RESOURCE,  0 ,
        NULL, NULL, "FullscreenDecorations", (void*)0,
        NULL, "Disable fullscreen decorations" },
    { "-monitorfont", SET_RESOURCE,  (1 << 0) ,
        set_monitor_font, NULL, "MonitorFont", NULL,
        "font-description", "Set monitor font for the Gtk3 monitor" },
    { "-monitorbg", SET_RESOURCE,  (1 << 0) ,
        set_monitor_bg,  NULL, "MonitorBG", NULL,
        "font-background", "Set monitor font background color" },
    { "-monitorfg", SET_RESOURCE,  (1 << 0) ,
        set_monitor_fg,  NULL, "MonitorFG", NULL,
        "font-foreground", "Set monitor font foreround color" },
    { "-autostart-on-doubleclick", SET_RESOURCE,  0 ,
        NULL, NULL, "AutostartOnDoubleclick", (void*)1,
        NULL, "Autostart files on doubleclick" },
    { "+autostart-on-doubleclick", SET_RESOURCE,  0 ,
        NULL, NULL, "AutostartOnDoubleclick", (void*)0,
        NULL, "Open files on doubleclick" },
    { "-settings-node", CALL_FUNCTION,  (1 << 0) ,
        set_settings_node_path, NULL, NULL, NULL,
        "settings-node", "Open settings dialog at <settings-node>" },
    { "-monitorxpos", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_xpos, (void*)MONITOR_WINDOW, "MonitorXPos", NULL,
        "X", "Set monitor window X position" },
    { "-monitorypos", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_ypos, (void*)MONITOR_WINDOW, "MonitorYPos", NULL,
        "Y", "Set monitor window Y position" },
    { "-monitorwidth", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_width, (void*)MONITOR_WINDOW, "MonitorWidth", NULL,
        "width", "Set monitor window width" },
    { "-monitorheight", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_height, (void*)MONITOR_WINDOW, "MonitorHeight", NULL,
        "height", "Set monitor window height" },
    { "-windowxpos", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_xpos, (void*)PRIMARY_WINDOW, "Window0XPos", NULL,
        "X", "Set window X position" },
    { "-windowypos", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_ypos, (void*)PRIMARY_WINDOW, "Window0YPos", NULL,
        "Y", "Set window Y position" },
    { "-windowwidth", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_width, (void*)PRIMARY_WINDOW, "Window0Width", NULL,
        "width", "Set window width" },
    { "-windowheight", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_height, (void*)PRIMARY_WINDOW, "Window0Height", NULL,
        "height", "Set window height" },
    { "-windowxpos1", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_xpos, (void*)SECONDARY_WINDOW, "Window1XPos", NULL,
        "X", "Set secondary window X position" },
    { "-windowypos1", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_ypos, (void*)SECONDARY_WINDOW, "Window1YPos", NULL,
        "Y", "Set secondary window Y position" },
    { "-windowwidth1", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_width, (void*)SECONDARY_WINDOW, "Window1Width", NULL,
        "width", "Set secondary window width" },
    { "-windowheight1", CALL_FUNCTION,  (1 << 0) ,
        set_monitor_height, (void*)SECONDARY_WINDOW, "Window1Height", NULL,
        "height", "Set secondary window height" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Command line options shared between emu's, include VSID.
Referenced by ui_cmdline_options_init().
create_controls_widget_func
GtkWidget *(* create_controls_widget_func) (int) (int) = NULL static
Function to help create a CRT controls widget.
Referenced by ui_create_main_window(), and ui_set_create_controls_widget_func().
create_window_func
void(* create_window_func) (video_canvas_t *) (video_canvas_t *) = NULL static
Function to help create a main window.
Referenced by ui_create_main_window(), and ui_set_create_window_func().
enter_monitor_while_paused
int enter_monitor_while_paused = 0 static
Flag indicating that the monitor should be entered whilst paused.
Referenced by ui_pause_enter_monitor(), and ui_pause_loop_iteration().
extendimage_dialog_result
ui_extendimage_action_t extendimage_dialog_result static
Result of the extend image dialog.
Referenced by ui_extend_image_dialog(), and ui_extendimage_dialog_impl().
fullscreen_has_decorations
int fullscreen_has_decorations = 0 static
Flag inidicating whether fullscreen mode shows the decorations.
Used by the resource "FullscreenDecorations".
Referenced by set_fullscreen_decorations(), ui_create_main_window(), ui_fullscreen_has_decorations(), and ui_update_fullscreen_decorations().
handle_dropped_files_func
int(* handle_dropped_files_func) (const char *) (const char *) = NULL static
Function to handle files dropped on a main window.
Referenced by ui_set_handle_dropped_files_func().
identify_canvas_func
int(* identify_canvas_func) (video_canvas_t *) (video_canvas_t *) = NULL static
Function to identify a canvas from its video chip.
Referenced by ui_create_main_window(), and ui_set_identify_canvas_func().
is_paused
int is_paused = 0 static
Flag indicating pause mode.
Referenced by statusbar_speed_widget_update(), ui_pause_active(), ui_pause_disable(), ui_pause_enable(), and ui_pause_loop_iteration().
jam_dialog_result
ui_jam_action_t jam_dialog_result static
Result of the JAM dialog.
Referenced by ui_jam_dialog(), and ui_jam_dialog_impl().
resources_int_primary_window
const resource_int_t resources_int_primary_window[] static
Initial value:
= {
    { "Window0Height", INT_MIN, RES_EVENT_NO, NULL,
        &(ui_resources.window_height[PRIMARY_WINDOW]), set_window_height,
        (void*)PRIMARY_WINDOW },
    { "Window0Width", INT_MIN, RES_EVENT_NO, NULL,
        &(ui_resources.window_width[PRIMARY_WINDOW]), set_window_width,
        (void*)PRIMARY_WINDOW },
    { "Window0Xpos", INT_MIN, RES_EVENT_NO, NULL,
        &(ui_resources.window_xpos[PRIMARY_WINDOW]), set_window_xpos,
        (void*)PRIMARY_WINDOW },
    { "Window0Ypos", INT_MIN, RES_EVENT_NO, NULL,
        &(ui_resources.window_ypos[PRIMARY_WINDOW]), set_window_ypos,
        (void*)PRIMARY_WINDOW },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Window size and position resources for the primary window.
These are used by all emulators.
Referenced by ui_resources_init().
resources_int_secondary_window
const resource_int_t resources_int_secondary_window[] static
Initial value:
= {
    { "Window1Height", 0, RES_EVENT_NO, NULL,
        &(ui_resources.window_height[SECONDARY_WINDOW]), set_window_height,
        (void*)SECONDARY_WINDOW },
    { "Window1Width", 0, RES_EVENT_NO, NULL,
        &(ui_resources.window_width[SECONDARY_WINDOW]), set_window_width,
        (void*)SECONDARY_WINDOW },
    { "Window1Xpos", 0, RES_EVENT_NO, NULL,
        &(ui_resources.window_xpos[SECONDARY_WINDOW]), set_window_xpos,
        (void*)SECONDARY_WINDOW },
    { "Window1Ypos", 0, RES_EVENT_NO, NULL,
        &(ui_resources.window_ypos[SECONDARY_WINDOW]), set_window_ypos,
        (void*)SECONDARY_WINDOW },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Window size and position resources list for the secondary window.
These are only used by x128's VDC window.
Referenced by ui_resources_init().
resources_int_shared
const resource_int_t resources_int_shared[] static
Initial value:
= {
    { "SaveResourcesOnExit", 0, RES_EVENT_NO, NULL,
        &ui_resources.save_resources_on_exit, set_save_resources_on_exit, NULL },
    { "ConfirmOnExit", 1, RES_EVENT_NO, NULL,
        &ui_resources.confirm_on_exit, set_confirm_on_exit, NULL },
    { "StartMinimized", 0, RES_EVENT_NO, NULL,
        &ui_resources.start_minimized, set_start_minimized, NULL },
    { "NativeMonitor", 0, RES_EVENT_NO, NULL,
        &ui_resources.use_native_monitor, set_native_monitor, NULL },
    { "FullscreenDecorations", 0, RES_EVENT_NO, NULL,
        &fullscreen_has_decorations, set_fullscreen_decorations, NULL },
    { "PauseOnSettings", 0, RES_EVENT_NO, NULL,
        &ui_resources.pause_on_settings, set_pause_on_settings, NULL },
    { "AutostartOnDoubleclick", 0, RES_EVENT_NO, NULL,
        &ui_resources.autostart_on_doubleclick, set_autostart_on_doubleclick,
        NULL },
    { "MonitorXPos", INT_MIN, RES_EVENT_NO, NULL,
        &(ui_resources.window_xpos[MONITOR_WINDOW]), set_window_xpos,
        (void*)MONITOR_WINDOW },
    { "MonitorYPos", INT_MIN, RES_EVENT_NO, NULL,
        &(ui_resources.window_ypos[MONITOR_WINDOW]), set_window_ypos,
        (void*)MONITOR_WINDOW },
    { "MonitorWidth", INT_MIN, RES_EVENT_NO, NULL,
        &(ui_resources.window_width[MONITOR_WINDOW]), set_window_width,
        (void*)MONITOR_WINDOW },
    { "MonitorHeight", INT_MIN, RES_EVENT_NO, NULL,
        &(ui_resources.window_height[MONITOR_WINDOW]), set_window_height,
        (void*)MONITOR_WINDOW },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Boolean and integer resources shared between windows.
Referenced by ui_resources_init().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "MonitorFont", "C64 Pro Mono Regular 9", RES_EVENT_NO, NULL,
        &ui_resources.monitor_font, set_monitor_font, NULL },
    { "MonitorFG", "#ffffff", RES_EVENT_NO, NULL,
        &ui_resources.monitor_fg, set_monitor_fg, NULL },
    { "MonitorBG", "#000000", RES_EVENT_NO, NULL,
        &ui_resources.monitor_bg, set_monitor_bg, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
String type resources list.
Referenced by ui_resources_init().
settings_node_path
const char* settings_node_path = NULL static
Settings node to activate after booting the emulator.
Used by the -settings-node command line option
Referenced by set_settings_node_path(), and ui_create_main_window().
ui_drag_targets
GtkTargetEntry ui_drag_targets[3]
Initial value:
= {
    { "text/plain",     0, DT_TEXT_PLAIN    },
    { "text/uri",       0, DT_TEXT_URI      },
    { "text/uri-list",  0, DT_TEXT_URI_LIST }
}
List of drag targets for the drag-n-drop event handler.
It would appear different OS'es/WM's pass dropped files using various mime-types.
Referenced by ui_create_main_window(), and vsid_main_widget_create().
ui_resources
ui_resource_t ui_resources static
Collection of UI resources.
This needs to stay here, to allow the command line and resources initializers to reference the UI resources.
Referenced by set_autostart_on_doubleclick(), set_confirm_on_exit(), set_monitor_bg(), set_monitor_fg(), set_monitor_font(), set_native_monitor(), set_pause_on_settings(), set_save_resources_on_exit(), set_start_minimized(), set_window_geometry_from_resources(), set_window_height(), set_window_width(), set_window_xpos(), set_window_ypos(), ui_create_main_window(), ui_destroy_main_window(), ui_display_main_window(), ui_enable_crt_controls(), ui_enable_mixer_controls(), ui_get_active_canvas(), ui_get_active_window(), ui_get_canvas_for_window(), ui_get_main_window_by_index(), ui_get_window_by_index(), ui_get_window_index(), ui_init_finalize(), ui_jam_dialog_impl(), ui_resources_init(), ui_resources_shutdown(), ui_trigger_resize(), ui_update_fullscreen_decorations(), and ui_update_lightpen().