vsid: fsdevice.h File Reference
fsdevice.h File Reference
Functions
int fsdevice_cmdline_options_init (void)
int fsdevice_resources_init (void)
void fsdevice_resources_shutdown (void)
void fsdevice_init (void)
void fsdevice_shutdown (void)
int fsdevice_attach (unsigned int device, unsigned int drive, const char *name)
void fsdevice_set_directory (char *filename, unsigned int unit)
Function Documentation
fsdevice_attach()
int fsdevice_attach (unsigned int device, unsigned int drive, const char * name)
Referenced by file_system_set_serial_hooks().
fsdevice_cmdline_options_init()
int fsdevice_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
fsdevice_init()
void fsdevice_init (void)
Referenced by machine_init().
fsdevice_resources_init()
int fsdevice_resources_init (void)
Referenced by machine_resources_init().
fsdevice_resources_shutdown()
void fsdevice_resources_shutdown (void)
Referenced by machine_resources_shutdown().
fsdevice_set_directory()
void fsdevice_set_directory (char * filename, unsigned int unit)
Referenced by autostart_prg_with_virtual_fs(), cmdline_fsdirectory(), and fsdevice_flush_cd().
fsdevice_shutdown()
void fsdevice_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().