vsid: fliplist.h File Reference
fliplist.h File Reference
Fliplist handling - header.
#include <stdbool.h>
Macros
#define FLIP_NEXT 1
#define FLIP_PREV 0
#define FLIPLIST_ALL_UNITS ((unsigned int)-1)
Typedefs
typedef struct fliplist_s * fliplist_t
Functions
int fliplist_resources_init (void)
void fliplist_resources_shutdown (void)
int fliplist_cmdline_options_init (void)
void fliplist_shutdown (void)
interface functions
void fliplist_set_current (unsigned int unit, const char *image)
bool fliplist_add_image (unsigned int unit)
void fliplist_remove (unsigned int unit, const char *image)
bool fliplist_attach_head (unsigned int unit, int direction)
Attach new image from the fliplist.
fliplist_t fliplist_init_iterate (unsigned int unit)
fliplist_t fliplist_next_iterate (unsigned int unit)
char * fliplist_get_head (unsigned int unit)
const char * fliplist_get_next (unsigned int unit)
const char * fliplist_get_prev (unsigned int unit)
const char * fliplist_get_image (fliplist_t fl)
unsigned int fliplist_get_unit (fliplist_t fl)
void fliplist_clear_list (unsigned int unit)
int fliplist_save_list (unsigned int unit, const char *filename)
int fliplist_load_list (unsigned int unit, const char *filename, int autoattach)
Detailed Description
Fliplist handling - header.
Author
pottendo potte.nosp@m.ndo@.nosp@m.gmx.n.nosp@m.et
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
FLIP_NEXT
#define FLIP_NEXT 1
FLIP_PREV
#define FLIP_PREV 0
FLIPLIST_ALL_UNITS
#define FLIPLIST_ALL_UNITS ((unsigned int)-1)
Todo:
FIXME: once all UIs are updated to use FLIPLIST_ALL_UNITS this should be changed to a positive value and the cast removed
Typedef Documentation
fliplist_t
typedef struct fliplist_s* fliplist_t
Function Documentation
fliplist_add_image()
bool fliplist_add_image (unsigned int unit)
Referenced by fliplist_add_action().
fliplist_attach_head()
bool fliplist_attach_head (unsigned int unit, int direction)
Attach new image from the fliplist.
Parameters
[in] unit drive unit number (8-11)
[in] direction attach either next (>=1) or previous image
Returns
boolean
Referenced by fliplist_load_list(), fliplist_next_action(), fliplist_previous_action(), and ui_fliplist_select_cb().
fliplist_clear_list()
void fliplist_clear_list (unsigned int unit)
Referenced by fliplist_clear_action(), fliplist_load_list(), and fliplist_resources_shutdown().
fliplist_cmdline_options_init()
int fliplist_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
fliplist_get_head()
char * fliplist_get_head (unsigned int unit)
Referenced by fliplist_add_action(), fliplist_next_action(), fliplist_previous_action(), fliplist_remove_action(), and ui_fliplist_select_cb().
fliplist_get_image()
const char * fliplist_get_image (fliplist_t fl)
Referenced by ui_fliplist_select_cb(), and ui_populate_fliplist_menu().
fliplist_get_next()
const char * fliplist_get_next (unsigned int unit)
Referenced by ui_populate_fliplist_menu().
fliplist_get_prev()
const char * fliplist_get_prev (unsigned int unit)
Referenced by ui_populate_fliplist_menu().
fliplist_get_unit()
unsigned int fliplist_get_unit (fliplist_t fl)
fliplist_init_iterate()
fliplist_t fliplist_init_iterate (unsigned int unit)
Referenced by ui_do_drive_popup(), ui_fliplist_select_cb(), and ui_populate_fliplist_menu().
fliplist_load_list()
int fliplist_load_list (unsigned int unit, const char * filename, int autoattach)
< read mode (binary)
Todo:
FIXME: we should handle some special cases of pathes we can find in .lst files:
sd2iec accepts 'cmd' style pathes
all kinds of absolute pathes musst not be converted, those are non portable anyway
Referenced by fliplist_load_response(), and set_fliplist_file_name().
fliplist_next_iterate()
fliplist_t fliplist_next_iterate (unsigned int unit)
Referenced by ui_populate_fliplist_menu().
fliplist_remove()
void fliplist_remove (unsigned int unit, const char * image)
Referenced by fliplist_remove(), and fliplist_remove_action().
fliplist_resources_init()
int fliplist_resources_init (void)
Referenced by machine_resources_init().
fliplist_resources_shutdown()
void fliplist_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
fliplist_save_list()
int fliplist_save_list (unsigned int unit, const char * filename)
< write mode (binary)
Todo:
FIXME: we should handle some more special cases:
absolute pathes must not be modified (those are non portable anyway
relative pathes could be converted to a CMD style path so it works with sd2iec
Referenced by fliplist_save_response().
fliplist_set_current()
void fliplist_set_current (unsigned int unit, const char * image)
Referenced by file_system_attach_disk_internal().
fliplist_shutdown()
void fliplist_shutdown (void)
interface functions
Referenced by cmdline_help(), and machine_shutdown().