x128: arch/gtk3/widgets/vsidcontrolwidget.h File Reference
vsidcontrolwidget.h File Reference
GTK3 control widget for VSID - header.
#include "vice.h"
#include <gtk/gtk.h>
Typedefs
typedef enum vsid_control_e vsid_control_t
VSID player status.
Enumerations
enum vsid_control_e {
VSID_ERROR = -1 ,
VSID_STOPPED = 0 ,
VSID_PLAYING ,
VSID_PAUSED ,
VSID_FORWARDING
}
VSID player status.
Functions
GtkWidget * vsid_control_widget_create (void)
Create widget with media buttons to control VSID playback.
void vsid_control_widget_set_tune_count (int nr)
Set number of tunes.
void vsid_control_widget_set_tune_current (int nr)
Set current tune.
void vsid_control_widget_set_tune_default (int nr)
Set default tune.
void vsid_control_widget_set_progress (gdouble fraction)
Set tune progress bar value.
void vsid_control_widget_next_tune (void)
Play next tune.
void vsid_control_widget_set_repeat (gboolean enabled)
Set repeat of psid.
gboolean vsid_control_widget_get_repeat (void)
Get repeat/loop widget state.
void vsid_control_widget_set_state (vsid_control_t state)
Update control buttons toggled state.
Detailed Description
GTK3 control widget for VSID - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Typedef Documentation
vsid_control_t
typedef enum vsid_control_e vsid_control_t
VSID player status.
Enumeration Type Documentation
vsid_control_e
enum vsid_control_e
VSID player status.
Enumerator
VSID_ERROR
player encountered error
VSID_STOPPED
player is stopped
VSID_PLAYING
player is playing normally
VSID_PAUSED
player is paused
VSID_FORWARDING
player is fast-forwarding
Function Documentation
vsid_control_widget_create()
GtkWidget * vsid_control_widget_create (void)
Create widget with media buttons to control VSID playback.
Returns
GtkGrid
Referenced by vsid_main_widget_create().
vsid_control_widget_get_repeat()
gboolean vsid_control_widget_get_repeat (void)
Get repeat/loop widget state.
Returns
loop state
Referenced by psid_loop_toggle_action(), and vsid_tune_info_widget_update().
vsid_control_widget_next_tune()
void vsid_control_widget_next_tune (void)
Play next tune.
vsid_control_widget_set_progress()
void vsid_control_widget_set_progress (gdouble fraction)
Set tune progress bar value.
Parameters
[in] fraction amount to fill (0.0 - 1.0)
Referenced by vsid_tune_info_widget_update().
vsid_control_widget_set_repeat()
void vsid_control_widget_set_repeat (gboolean enabled)
Set repeat of psid.
Set internal repeat state and toggle button state
Parameters
[in] enabled repeat current psid
Referenced by psid_loop_toggle_action().
vsid_control_widget_set_state()
void vsid_control_widget_set_state (vsid_control_t state)
Update control buttons toggled state.
Parameters
[in] state player state
Referenced by play_current_tune(), psid_ffwd_action(), psid_pause_action(), psid_play_action(), psid_stop_action(), and ui_vsid_window_load_psid().
vsid_control_widget_set_tune_count()
void vsid_control_widget_set_tune_count (int n)
Set number of tunes.
Parameters
[in] n tune count
vsid_control_widget_set_tune_current()
void vsid_control_widget_set_tune_current (int n)
Set current tune.
Parameters
[in] n tune number
vsid_control_widget_set_tune_default()
void vsid_control_widget_set_tune_default (int n)
Set default tune.
Parameters
[in] n tune number