x128: monitor/mon_register6502dtv.c File Reference
mon_register6502dtv.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "lib.h"
#include "log.h"
#include "mon_register.h"
#include "mon_util.h"
#include "montypes.h"
#include "mos6510dtv.h"
#include "uimon.h"
Macros
#define DBG(_x_)
#define TEST(x) ((x) != 0)
#define REG_LIST_6510DTV_SIZE (26 + 1)
Functions
static unsigned int mon_register_get_val (int mem, int reg_id)
static void mon_register_set_val (int mem, int reg_id, uint16_t val)
static void mon_register_print (int mem)
static mon_reg_list_t * mon_register_list_get6502dtv (int mem)
void mon_register6502dtv_init (monitor_cpu_type_t *monitor_cpu_type)
Variables
static const mon_reg_list_t mon_reg_list_6510dtv [(26+1)]
Macro Definition Documentation
DBG
#define DBG (_x_)
REG_LIST_6510DTV_SIZE
#define REG_LIST_6510DTV_SIZE (26 + 1)
Todo:
make the other functions here use this table. when done also do the same with the other CPUs and finally move common code to mon_register.c
TEST
#define TEST (x) ((x) != 0)
Function Documentation
mon_register6502dtv_init()
void mon_register6502dtv_init (monitor_cpu_type_t * monitor_cpu_type)
Referenced by asm6502dtv_init().
mon_register_get_val()
static unsigned int mon_register_get_val (int mem, int reg_id) static
Referenced by mon_register6502dtv_init(), mon_register_list_get6502dtv(), and mon_register_print().
mon_register_list_get6502dtv()
static mon_reg_list_t * mon_register_list_get6502dtv (int mem) static
Todo:
try to make this a generic function, move it into mon_register.c and remove mon_register_list_get from the monitor_cpu_type_t struct
Referenced by mon_register6502dtv_init().
mon_register_print()
static void mon_register_print (int mem) static
Todo:
should use mon_register_list_get
Referenced by mon_register6502dtv_init().
mon_register_set_val()
static void mon_register_set_val (int mem, int reg_id, uint16_t val) static
Referenced by mon_register6502dtv_init().
Variable Documentation
mon_reg_list_6510dtv
const mon_reg_list_t mon_reg_list_6510dtv[(26+1)] static
Initial value:
= {
    {      "PC",         e_PC, 16,                      0, 0, 0 },
    {       "A",          e_A,  8,                      0, 0, 0 },
    {       "X",          e_X,  8,                      0, 0, 0 },
    {       "Y",          e_Y,  8,                      0, 0, 0 },
    {      "SP",         e_SP,  8,                      0, 0, 0 },
    {      "00",       e_Zero,  8,  0x02  , 0, 0 },
    {      "01",        e_One,  8,  0x02  , 1, 0 },
    {      "FL",      e_FLAGS,  8,                      0, 0, 0 },
    {"NV-BDIZC",      e_FLAGS,  8,   0x01  , 0, 0 },
    {      "R3",         e_R3,  8,                      0, 0, 0 },
    {      "R4",         e_R4,  8,                      0, 0, 0 },
    {      "R5",         e_R5,  8,                      0, 0, 0 },
    {      "R6",         e_R6,  8,                      0, 0, 0 },
    {      "R7",         e_R7,  8,                      0, 0, 0 },
    {      "R8",         e_R8,  8,                      0, 0, 0 },
    {      "R9",         e_R9,  8,                      0, 0, 0 },
    {     "R10",        e_R10,  8,                      0, 0, 0 },
    {     "R11",        e_R11,  8,                      0, 0, 0 },
    {     "R12",        e_R12,  8,                      0, 0, 0 },
    {     "R13",        e_R13,  8,                      0, 0, 0 },
    {     "R14",        e_R14,  8,                      0, 0, 0 },
    {     "R15",        e_R15,  8,                      0, 0, 0 },
    {     "ACM",        e_ACM,  8,                      0, 0, 0 },
    {     "YXM",        e_YXM,  8,                      0, 0, 0 },
    {     "LIN", e_Rasterline, 16,                      0, 0, 0 },
    {     "CYC",      e_Cycle, 16,                      0, 0, 0 },
    { NULL, -1,  0,  0, 0, 0 }
}
Referenced by mon_register_list_get6502dtv().