vsid: drive/iec-c64exp.h File Reference
iec-c64exp.h File Reference
Functions
int iec_c64exp_resources_init (void)
void iec_c64exp_resources_shutdown (void)
int iec_c64exp_cmdline_options_init (void)
void iec_c64exp_init (struct diskunit_context_s *drv)
void iec_c64exp_reset (struct diskunit_context_s *drv)
void iec_c64exp_mem_init (struct diskunit_context_s *drv, unsigned int type)
Function Documentation
iec_c64exp_cmdline_options_init()
int iec_c64exp_cmdline_options_init (void)
Referenced by machine_drive_cmdline_options_init().
iec_c64exp_init()
void iec_c64exp_init (struct diskunit_context_s * drv)
Referenced by machine_drive_init().
iec_c64exp_mem_init()
void iec_c64exp_mem_init (struct diskunit_context_s * drv, unsigned int type)
Referenced by machine_drive_mem_init().
iec_c64exp_reset()
void iec_c64exp_reset (struct diskunit_context_s * drv)
Referenced by machine_drive_reset().
iec_c64exp_resources_init()
int iec_c64exp_resources_init (void)
Referenced by machine_drive_resources_init().
iec_c64exp_resources_shutdown()
void iec_c64exp_resources_shutdown (void)
Referenced by machine_drive_resources_shutdown().