vsid: c64/c64-memory-hacks.c File Reference
c64-memory-hacks.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "c64-memory-hacks.h"
#include "c64_256k.h"
#include "cmdline.h"
#include "mem.h"
#include "plus256k.h"
#include "plus60k.h"
#include "resources.h"
#include "snapshot.h"
#include "types.h"
#include "ui.h"
Macros
#define SNAP_MAJOR 0
#define SNAP_MINOR 0
Functions
static int set_memory_hack (int value, void *param)
Set memory hack.
int memory_hacks_ram_inject (uint16_t addr, uint8_t value)
int memory_hacks_resources_init (void)
int memory_hacks_cmdline_options_init (void)
int memhacks_snapshot_write_modules (struct snapshot_s *s)
int memhacks_snapshot_read_modules (struct snapshot_s *s)
Variables
static int memory_hack = 0
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
static char snap_module_name [] = "C64MEMHACKS"
Macro Definition Documentation
SNAP_MAJOR
#define SNAP_MAJOR 0
SNAP_MINOR
#define SNAP_MINOR 0
Function Documentation
memhacks_snapshot_read_modules()
int memhacks_snapshot_read_modules (struct snapshot_s * s)
Referenced by c64_snapshot_read().
memhacks_snapshot_write_modules()
int memhacks_snapshot_write_modules (struct snapshot_s * s)
Referenced by c64_snapshot_write().
memory_hacks_cmdline_options_init()
int memory_hacks_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
memory_hacks_ram_inject()
int memory_hacks_ram_inject (uint16_t addr, uint8_t value)
Referenced by mem_inject().
memory_hacks_resources_init()
int memory_hacks_resources_init (void)
Referenced by machine_resources_init().
set_memory_hack()
static int set_memory_hack (int value, void * param) static
Set memory hack.
Pauses emulation when switching to another memory expansion hack to avoid having a running CPU access invalid memory. Unpauses emulation if the emulation wasn't already paused before switching memory expansion.
Parameters
[in] value memory hack ID
[in] param extra data (unused)
Returns
0 on succes, -1 on failure
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-memoryexphack", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "MemoryHack", NULL,
      "<device>", "Set the 'memory expansion hack' device (0: None, 1: C64 256K, 2: +60K, 3: +256K)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by memory_hacks_cmdline_options_init().
memory_hack
int memory_hack = 0 static
Referenced by memhacks_snapshot_read_modules(), memhacks_snapshot_write_modules(), memory_hacks_ram_inject(), and set_memory_hack().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "MemoryHack", MEMORY_HACK_NONE, RES_EVENT_STRICT, (resource_value_t)0,
      &memory_hack, set_memory_hack, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by memory_hacks_resources_init().
snap_module_name
char snap_module_name[] = "C64MEMHACKS" static
Referenced by memhacks_snapshot_read_modules(), and memhacks_snapshot_write_modules().