vsid: c64/vsidmeminit.c File Reference
vsidmeminit.c File Reference
#include "vice.h"
#include <stdio.h>
#include "c64cart.h"
#include "c64cartmem.h"
#include "c64cia.h"
#include "c64mem.h"
#include "c64meminit.h"
#include "c64memrom.h"
#include "machine.h"
#include "resources.h"
#include "sid.h"
#include "sid-resources.h"
#include "vsid-debugcart.h"
#include "vicii-mem.h"
#include "vicii-phi1.h"
Functions
uint8_t vsid_io_read (uint16_t addr)
void vsid_io_store (uint16_t addr, uint8_t val)
static void sid_store_d700 (uint16_t addr, uint8_t val)
void c64meminit (unsigned int base)
Variables
const unsigned int c64meminit_io_config [32]
IO is enabled at memory configs 5, 6, 7 and mirrors since game/exrom will never be changed.
Function Documentation
c64meminit()
void c64meminit (unsigned int base)
sid_store_d700()
static void sid_store_d700 (uint16_t addr, uint8_t val) static
Referenced by c64meminit().
vsid_io_read()
uint8_t vsid_io_read (uint16_t addr)
Referenced by c64meminit(), and read_bank_io().
vsid_io_store()
void vsid_io_store (uint16_t addr, uint8_t val)
Referenced by c64meminit(), and store_bank_io().
Variable Documentation
c64meminit_io_config
const unsigned int c64meminit_io_config[32]
Initial value:
= {
    0, 0, 0, 0, 0, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0
}
IO is enabled at memory configs 5, 6, 7 and mirrors since game/exrom will never be changed.
IO is enabled at memory configs 5, 6, 7 and Ultimax.
Referenced by c64meminit().