vsid: monitor/mon_memory.c File Reference
mon_memory.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "charset.h"
#include "console.h"
#include "lib.h"
#include "mem.h"
#include "montypes.h"
#include "mon_memory.h"
#include "mon_util.h"
#include "types.h"
Macros
#define ADDR_LIMIT(x) ((uint16_t)(addr_mask(x)))
Functions
void mon_memory_move (MON_ADDR start_addr, MON_ADDR end_addr, MON_ADDR dest)
void mon_memory_compare (MON_ADDR start_addr, MON_ADDR end_addr, MON_ADDR dest)
void mon_memory_fill (MON_ADDR start_addr, MON_ADDR end_addr, unsigned char *data)
void mon_memory_hunt (MON_ADDR start_addr, MON_ADDR end_addr, unsigned char *data)
static void set_addr_location (MON_ADDR *a, unsigned l)
void mon_memory_display (int radix_type, MON_ADDR start_addr, MON_ADDR end_addr, mon_display_format_t format)
display memory dump (binary, text) 'm', 'i', 'ii' commands
void mon_memory_display_data (MON_ADDR start_addr, MON_ADDR end_addr, unsigned int x, unsigned int y)
display binary data (sprites/chars), "mc" and "ms" commands
Variables
static const int radix_chars_per_byte []
Macro Definition Documentation
ADDR_LIMIT
#define ADDR_LIMIT (x) ((uint16_t)(addr_mask(x)))
Function Documentation
mon_memory_compare()
void mon_memory_compare (MON_ADDR start_addr, MON_ADDR end_addr, MON_ADDR dest)
mon_memory_display()
void mon_memory_display (int radix_type, MON_ADDR start_addr, MON_ADDR end_addr, mon_display_format_t format)
display memory dump (binary, text) 'm', 'i', 'ii' commands
Todo:
FIXME: this should really be handled by the UI instead, ie the UI should always just give us valid numbers
Todo:
FIXME: limit width vs console width
Referenced by mon_display_io_regs().
mon_memory_display_data()
void mon_memory_display_data (MON_ADDR start_addr, MON_ADDR end_addr, unsigned int x, unsigned int y)
display binary data (sprites/chars), "mc" and "ms" commands
mon_memory_fill()
void mon_memory_fill (MON_ADDR start_addr, MON_ADDR end_addr, unsigned char * data)
mon_memory_hunt()
void mon_memory_hunt (MON_ADDR start_addr, MON_ADDR end_addr, unsigned char * data)
mon_memory_move()
void mon_memory_move (MON_ADDR start_addr, MON_ADDR end_addr, MON_ADDR dest)
set_addr_location()
static void set_addr_location (MON_ADDR * a, unsigned l) static
Referenced by mon_memory_display(), and mon_memory_display_data().
Variable Documentation
radix_chars_per_byte
const int radix_chars_per_byte[] static
Initial value:
= {
    2,
    2,
    3,
    3,
    8,
}
Referenced by mon_memory_display().