vsid: gfxoutputdrv/ppmdrv.c File Reference
ppmdrv.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "archdep.h"
#include "ppmdrv.h"
#include "lib.h"
#include "log.h"
#include "gfxoutput.h"
#include "palette.h"
#include "screenshot.h"
#include "types.h"
#include "util.h"
Data Structures
struct gfxoutputdrv_data_s
Typedefs
typedef struct gfxoutputdrv_data_s gfxoutputdrv_data_t
Functions
static int ppmdrv_write_file_header (screenshot_t *screenshot)
static int ppmdrv_open (screenshot_t *screenshot, const char *filename)
static int ppmdrv_write (screenshot_t *screenshot)
static int ppmdrv_close (screenshot_t *screenshot)
static int ppmdrv_save (screenshot_t *screenshot, const char *filename)
void gfxoutput_init_ppm (int help)
Variables
static gfxoutputdrv_t ppm_drv
Typedef Documentation
gfxoutputdrv_data_t
typedef struct gfxoutputdrv_data_s gfxoutputdrv_data_t
Function Documentation
gfxoutput_init_ppm()
void gfxoutput_init_ppm (int help)
Referenced by gfxoutput_early_init().
ppmdrv_close()
static int ppmdrv_close (screenshot_t * screenshot) static
Referenced by ppmdrv_save().
ppmdrv_open()
static int ppmdrv_open (screenshot_t * screenshot, const char * filename) static
Referenced by ppmdrv_save().
ppmdrv_save()
static int ppmdrv_save (screenshot_t * screenshot, const char * filename) static
ppmdrv_write()
static int ppmdrv_write (screenshot_t * screenshot) static
Referenced by ppmdrv_save().
ppmdrv_write_file_header()
static int ppmdrv_write_file_header (screenshot_t * screenshot) static
Referenced by ppmdrv_open().
Variable Documentation
ppm_drv
static gfxoutputdrv_t ppm_drv static
Initial value:
=
{
    GFXOUTPUTDRV_TYPE_SCREENSHOT_IMAGE,
    "PPM",
    "PPM screenshot",
    "ppm",
    NULL,
    ppmdrv_open,
    ppmdrv_close,
    ppmdrv_write,
    ppmdrv_save,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
}
Referenced by gfxoutput_init_ppm(), and ppmdrv_open().