x128: monitor/monitor_network.h File Reference
monitor_network.h File Reference
#include "types.h"
#include "uiapi.h"
#include "vicesocket.h"
Functions
int monitor_network_resources_init (void)
initialize the network monitor resources
void monitor_network_resources_shutdown (void)
uninitialize the network monitor resources
int monitor_network_cmdline_options_init (void)
initialize the command-line options'
void monitor_check_remote (void)
int monitor_network_receive (char *buffer, size_t buffer_length)
int monitor_network_transmit (const char *buffer, size_t buffer_length)
int monitor_network_get_command_line (char **prompt)
int monitor_is_remote (void)
vice_network_socket_t * monitor_get_connected_socket (void)
ui_jam_action_t monitor_network_ui_jam_dialog (const char *format,...)
Detailed Description
Author
Spiro Trikaliotis
Monitor implementation - network access
monitor_network.h - Monitor implementation - network access.
Written by Spiro Trikaliotis spiro.nosp@m..tri.nosp@m.kalio.nosp@m.tis@.nosp@m.gmx.d.nosp@m.e
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Function Documentation
monitor_check_remote()
void monitor_check_remote (void)
Referenced by monitor_vsync_hook(), and uimon_in().
monitor_get_connected_socket()
vice_network_socket_t * monitor_get_connected_socket (void)
Referenced by uimon_in().
monitor_is_remote()
int monitor_is_remote (void)
Referenced by drive_jam(), machine_jam(), mon_out(), mon_petscii_out(), mon_petscii_upper_out(), mon_scrcode_out(), mon_scrcode_upper_out(), monitor_close(), monitor_open(), and uimon_in().
monitor_network_cmdline_options_init()
int monitor_network_cmdline_options_init (void)
initialize the command-line options'
Returns
0 on success, else -1.
Remarks
Registers the command-line options
Referenced by init_cmdline_options().
monitor_network_get_command_line()
int monitor_network_get_command_line (char ** prompt)
Referenced by uimon_in().
monitor_network_receive()
int monitor_network_receive (char * buffer, size_t buffer_length)
Referenced by monitor_network_get_command_line().
monitor_network_resources_init()
int monitor_network_resources_init (void)
initialize the network monitor resources
Returns
0 on success, else -1.
Remarks
Registers the string and the integer resources
Referenced by init_resources().
monitor_network_resources_shutdown()
void monitor_network_resources_shutdown (void)
uninitialize the network monitor resources
Referenced by cmdline_help(), and machine_shutdown().
monitor_network_transmit()
int monitor_network_transmit (const char * buffer, size_t buffer_length)
Referenced by mon_out(), mon_petscii_out(), mon_petscii_upper_out(), mon_scrcode_out(), mon_scrcode_upper_out(), monitor_network_ui_jam_dialog(), and uimon_in().
monitor_network_ui_jam_dialog()
ui_jam_action_t monitor_network_ui_jam_dialog (const char * format, ...)
Referenced by drive_jam(), and machine_jam().