vsid: serial_s Struct Reference
serial_s Struct Reference
#include <serial.h>
Data Fields
int inuse
int isopen [16]
struct disk_image_s * image
char * name
int(* getf)(struct vdrive_s *, uint8_t *, unsigned int)
int(* putf)(struct vdrive_s *, uint8_t, unsigned int)
int(* openf)(struct vdrive_s *, const uint8_t *, unsigned int, unsigned int, struct cbmdos_cmd_parse_s *cmd_parse_ext)
int(* closef)(struct vdrive_s *, unsigned int)
void(* flushf)(struct vdrive_s *, unsigned int)
void(* listenf)(struct vdrive_s *, unsigned int)
uint8_t nextbyte [16]
char nextok [16]
int nextst [16]
unsigned int device
uint8_t lastbyte [16]
char lastok [16]
int lastst [16]
Field Documentation
closef
int(* serial_s::closef) (struct vdrive_s *, unsigned int)
Referenced by fsdrive_open(), fsdrive_reset(), machine_bus_device_attach(), machine_bus_device_detach(), machine_bus_init(), parallel_trap_attention(), parallelcommand(), and serialcommand().
device
unsigned int serial_s::device
Referenced by machine_bus_device_attach(), serial_device_type_get(), and serial_device_type_set().
flushf
void(* serial_s::flushf) (struct vdrive_s *, unsigned int)
Referenced by machine_bus_device_attach(), machine_bus_device_detach(), machine_bus_init(), parallelcommand(), and serialcommand().
getf
int(* serial_s::getf) (struct vdrive_s *, uint8_t *, unsigned int)
Referenced by fsdrive_read(), machine_bus_device_attach(), machine_bus_device_detach(), machine_bus_init(), and parallel_trap_receivebyte().
image
struct disk_image_s* serial_s::image
inuse
int serial_s::inuse
Referenced by fsdrive_reset(), fsdrive_write(), machine_bus_device_attach(), machine_bus_device_detach(), machine_bus_init(), parallel_trap_attention(), parallel_trap_sendbyte(), and serial_trap_attention().
isopen
int serial_s::isopen[16]
Referenced by fsdrive_open(), fsdrive_reset(), fsdrive_write(), machine_bus_device_attach(), parallel_trap_attention(), parallel_trap_sendbyte(), parallelcommand(), and serialcommand().
lastbyte
uint8_t serial_s::lastbyte[16]
Referenced by parallel_trap_receivebyte().
lastok
char serial_s::lastok[16]
Referenced by parallel_trap_receivebyte(), and parallelcommand().
lastst
int serial_s::lastst[16]
Referenced by parallel_trap_receivebyte().
listenf
void(* serial_s::listenf) (struct vdrive_s *, unsigned int)
Referenced by fsdrive_listentalk(), fsdrive_unlisten(), machine_bus_device_attach(), machine_bus_device_detach(), machine_bus_init(), and parallel_trap_attention().
name
char* serial_s::name
Referenced by machine_bus_device_attach(), and machine_bus_device_detach().
nextbyte
uint8_t serial_s::nextbyte[16]
Referenced by fsdrive_read(), and parallel_trap_receivebyte().
nextok
char serial_s::nextok[16]
Referenced by fsdrive_read(), fsdrive_unlisten(), machine_bus_device_attach(), parallel_trap_receivebyte(), parallelcommand(), and serialcommand().
nextst
int serial_s::nextst[16]
Referenced by parallel_trap_receivebyte().
openf
int(* serial_s::openf) (struct vdrive_s *, const uint8_t *, unsigned int, unsigned int, struct cbmdos_cmd_parse_s *cmd_parse_ext)
Referenced by machine_bus_device_attach(), machine_bus_device_detach(), machine_bus_init(), parallelcommand(), and serialcommand().
putf
int(* serial_s::putf) (struct vdrive_s *, uint8_t, unsigned int)
Referenced by fsdrive_write(), machine_bus_device_attach(), machine_bus_device_detach(), machine_bus_init(), parallel_trap_sendbyte(), parallelcommand(), and serialcommand().
The documentation for this struct was generated from the following file:
serial.h