vsid: arch/gtk3/widgets/statusbarledwidget.c File Reference
statusbarledwidget.c File Reference
Small LED widgets for the status bar.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdint.h>
#include "vice_gtk3.h"
#include "lib.h"
#include "log.h"
#include "statusbarledwidget.h"
Data Structures
struct led_state_s
LED state object.
Macros
#define COLOR_DEFAULT_ON "#00ff00"
Default color for ON.
#define COLOR_DEFAULT_OFF "#ff0000"
Default color for OFF.
#define LABEL_CSS
CSS to reduce size of the label.
Typedefs
typedef struct led_state_s led_state_t
LED state object.
Enumerations
enum {
COLUMN_LABEL ,
COLUMN_LED
}
column indexes of the grid
Functions
static GtkWidget * get_grid (GtkWidget *self)
Get grid inside the event box.
static gpointer get_data (GtkWidget *self, const char *key)
Get data by key.
static void set_data (GtkWidget *self, const char *key, gpointer data)
Set data by key.
static led_state_t * get_state (GtkWidget *self)
Get internal state object of the widget.
static GtkWidget * get_led_widget (GtkWidget *self)
Get the drawing area presenting the LED.
static void on_destroy (GtkWidget *self, gpointer data)
Handler for the 'destroy' event of the event box.
static gboolean on_led_draw (GtkWidget *widget, cairo_t *cr, gpointer data)
Handler for the 'draw' event of the widget.
static gboolean on_button_press_event (GtkWidget *self, GdkEvent *event, gpointer data)
Handler for button press events.
static gboolean on_crossing_event (GtkWidget *self, GdkEvent *event, gpointer data)
Handler for enter/leave events of the widget.
GtkWidget * statusbar_led_widget_create (const gchar *text, const gchar *on, const gchar *off)
Create LED widget for status bar.
void statusbar_led_widget_set_active (GtkWidget *widget, gboolean active)
Set status bar LED widget state.
gboolean statusbar_led_widget_get_active (GtkWidget *widget)
Get status bar LED widget state.
void statusbar_led_widget_set_toggleable (GtkWidget *widget, gboolean toggleable)
Make widget toggleable, toggling state on mouse click.
gboolean statusbar_led_widget_get_toggleable (GtkWidget *widget)
Get toggleable state of widget.
void statusbar_led_widget_set_toggle_callback (GtkWidget *widget, void(*cb)(GtkWidget *, gboolean))
Set callback to trigger on state change.
Detailed Description
Small LED widgets for the status bar.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
A small widget with a label and a drawing area displaying on/off status.
Can be used to display statuses like 'Pause' and 'Warp', and perhaps also key states such as 'ShiftLock', '40/80 Column' etc.
The widget is structured as follows:
+-GtkEventBox----------------—+ | +-GtkGrid–+-------------—+ | | | GtkLabel | GtkDrawingArea | | | +-------—+-------------—+ | +----------------------------—+
Macro Definition Documentation
COLOR_DEFAULT_OFF
#define COLOR_DEFAULT_OFF "#ff0000"
Default color for OFF.
COLOR_DEFAULT_ON
#define COLOR_DEFAULT_ON "#00ff00"
Default color for ON.
LABEL_CSS
#define LABEL_CSS
Value:
    "label {\n" \
    "    font-size: 90%;\n" \
    "}\n"
CSS to reduce size of the label.
Typedef Documentation
led_state_t
typedef struct led_state_s led_state_t
LED state object.
Enumeration Type Documentation
anonymous enum
anonymous enum
column indexes of the grid
Enumerator
COLUMN_LABEL
column of label
COLUMN_LED
column of led
Function Documentation
get_data()
static gpointer get_data (GtkWidget * self, const char * key) static
Get data by key.
Wrapper around g_object_get_data().
Parameters
[in] self status bar led widget (GtkEventBox)
[in] key key
Returns
data as a void*
Referenced by get_state(), on_button_press_event(), on_crossing_event(), on_destroy(), and statusbar_led_widget_get_toggleable().
get_grid()
static GtkWidget * get_grid (GtkWidget * self) static
Get grid inside the event box.
Parameters
[in] self status bar led widget (GtkEventBox)
Returns
GtkGrid
Referenced by get_led_widget().
get_led_widget()
static GtkWidget * get_led_widget (GtkWidget * self) static
Get the drawing area presenting the LED.
Parameters
[in] self status bar led widget
Returns
GtkDrawingArea
Referenced by statusbar_led_widget_set_active().
get_state()
static led_state_t * get_state (GtkWidget * self) static
Get internal state object of the widget.
Small helper function to get the internal state object of self.
Parameters
[in] self status bar led widget (GtkEventBox)
Returns
state object
Referenced by on_destroy(), on_led_draw(), statusbar_led_widget_get_active(), and statusbar_led_widget_set_active().
on_button_press_event()
static gboolean on_button_press_event (GtkWidget * self, GdkEvent * event, gpointer data) static
Handler for button press events.
Parameters
[in] self event box
[in] event event data
[in] data extra event data (unused)
Returns
GDK_EVENT_PROPAGATE
Referenced by statusbar_led_widget_create().
on_crossing_event()
static gboolean on_crossing_event (GtkWidget * self, GdkEvent * event, gpointer data) static
Handler for enter/leave events of the widget.
Set the mouse pointer shape when hovering over the widget.
Parameters
[in] self event box
[in] event event object
[in] data extra event data (unused)
Note
Gtk docs incorrectly state the second argument should be GdkEventCrossing event, this doesn't work.
Returns
GDK_EVENT_PROPAGATE
Referenced by statusbar_led_widget_create().
on_destroy()
static void on_destroy (GtkWidget * self, gpointer data) static
Handler for the 'destroy' event of the event box.
Deallocates memory used for the internal state.
Parameters
[in] self status bar led widget (GtkEventBox)
[in] data extra event data (unused)
Referenced by statusbar_led_widget_create().
on_led_draw()
static gboolean on_led_draw (GtkWidget * widget, cairo_t * cr, gpointer data) static
Handler for the 'draw' event of the widget.
Parameters
[in] widget LED GtkDrawingArea
[in] cr cairo context that handles the drawing
[in] data extra event data (unused)
Returns
FALSE, telling GTK to continue event processing
Referenced by statusbar_led_widget_create().
set_data()
static void set_data (GtkWidget * self, const char * key, gpointer data) static
Set data by key.
Wrapper around g_object_set_data().
Parameters
[in] self status bar led widget (GtkEventBox)
[in] key key
[in] data data
Referenced by on_crossing_event(), statusbar_led_widget_create(), statusbar_led_widget_set_toggle_callback(), and statusbar_led_widget_set_toggleable().
statusbar_led_widget_create()
GtkWidget * statusbar_led_widget_create (const gchar * text, const gchar * on, const gchar * off)
Create LED widget for status bar.
Create a small widget with a label and a two-state LED.
The colors are parsed with gdk_rgba_parse(), and if parsing fails default to #00ff00 (green) for 'on' and #ff0000 for 'off'.
Parameters
[in] text label text
[in] on color for on (use NULL for default green)
[in] off color for off (used NULL for default red)
Returns
GtkGrid
Referenced by capslock_led_create(), diagnosticpin_led_create(), mode4080_led_create(), pause_led_create(), shiftlock_led_create(), statusbar_speed_widget_create(), supercpu_jiffy_led_create(), supercpu_turbo_led_create(), and warp_led_create().
statusbar_led_widget_get_active()
gboolean statusbar_led_widget_get_active (GtkWidget * widget)
Get status bar LED widget state.
Parameters
[in] widget status bar led widget
Returns
TRUE for on, FALSE for off
Referenced by on_button_press_event().
statusbar_led_widget_get_toggleable()
gboolean statusbar_led_widget_get_toggleable (GtkWidget * widget)
Get toggleable state of widget.
Returns
LED widget is toggleable via mouse click
Referenced by on_button_press_event().
statusbar_led_widget_set_active()
void statusbar_led_widget_set_active (GtkWidget * widget, gboolean active)
Set status bar LED widget state.
Parameters
[in] widget status bar led widget
[in] active new state (TRUE = on, FALSE = off)
Referenced by capslock_led_set_active(), diagnosticpin_led_set_active(), mode4080_led_set_active(), on_button_press_event(), pause_led_set_active(), shiftlock_led_set_active(), supercpu_jiffy_led_create(), supercpu_jiffy_led_set_active(), supercpu_turbo_led_create(), supercpu_turbo_led_set_active(), and warp_led_set_active().
statusbar_led_widget_set_toggle_callback()
void statusbar_led_widget_set_toggle_callback (GtkWidget * widget, void(*)(GtkWidget *, gboolean) cb)
Set callback to trigger on state change.
Set callback function cb to be triggered on LED status change, which means through mouse clicks (enabled via statusbar_led_widget_set_toggleable()) but not through statusbar_led_widget_set_active().
Parameters
[in] widget status bar led widget
[in] cb callback function
Referenced by capslock_led_create(), diagnosticpin_led_create(), mode4080_led_create(), pause_led_create(), supercpu_jiffy_led_create(), supercpu_turbo_led_create(), and warp_led_create().
statusbar_led_widget_set_toggleable()
void statusbar_led_widget_set_toggleable (GtkWidget * widget, gboolean toggleable)
Make widget toggleable, toggling state on mouse click.
Make the widget accept mouse clicks, toggling its state.
Parameters
[in] widget status bar led widget
[in] toggleable accept mouse clicks to toggle state
Referenced by capslock_led_create(), diagnosticpin_led_create(), mode4080_led_create(), pause_led_create(), supercpu_jiffy_led_create(), supercpu_turbo_led_create(), and warp_led_create().