vsid: arch/gtk3/widgets/settings_scpu64.c File Reference
settings_scpu64.c File Reference
Settings widget controlling SCPU64-specific settings.
#include "vice.h"
#include <gtk/gtk.h>
#include "ui.h"
#include "uistatusbar.h"
#include "vice_gtk3.h"
#include "settings_scpu64.h"
Functions
static void speed_switch_callback (GtkWidget *self, gboolean active)
Callback for the SuperCPU Speed switch.
static void jiffy_switch_callback (GtkWidget *self, gboolean active)
Callback for the SuperCPU JiffyDOS switch.
static GtkWidget * create_label (const char *text)
Create left-aligned label.
GtkWidget * settings_scpu64_widget_create (GtkWidget *parent)
Create widgets for SCPU64-specific settings.
Variables
static const vice_gtk3_combo_entry_int_t simm_sizes []
List of SCPU64 SIMM sizes.
Detailed Description
Settings widget controlling SCPU64-specific settings.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_label()
static GtkWidget * create_label (const char * text) static
Create left-aligned label.
Parameters
[in] text text for the label
Returns
GtkLabel
Referenced by settings_scpu64_widget_create().
jiffy_switch_callback()
static void jiffy_switch_callback (GtkWidget * self, gboolean active) static
Callback for the SuperCPU JiffyDOS switch.
Update statusbar "JiffyDOS" LED when the switch is toggled.
Parameters
[in] self resource switch (ignored)
[in] active new state of switch
Referenced by settings_scpu64_widget_create().
settings_scpu64_widget_create()
GtkWidget * settings_scpu64_widget_create (GtkWidget * parent)
Create widgets for SCPU64-specific settings.
Parameters
[in] parent parent widget (ignored)
Returns
GtkGrid
speed_switch_callback()
static void speed_switch_callback (GtkWidget * self, gboolean active) static
Callback for the SuperCPU Speed switch.
Update statusbar "turbo" LED when the switch is toggled.
Parameters
[in] self resource switch (ignored)
[in] active new state of switch
Referenced by settings_scpu64_widget_create().
Variable Documentation
simm_sizes
const vice_gtk3_combo_entry_int_t simm_sizes[] static
Initial value:
= {
    { "Not installed",  0 },
    { "1MiB",           1 },
    { "4MiB",           4 },
    { "8MiB",           8 },
    { "16MiB",         16 },
    { NULL,            -1 }
}
List of SCPU64 SIMM sizes.
Referenced by settings_scpu64_widget_create().