vsid: c64/c64printer.c File Reference
c64printer.c File Reference
#include "vice.h"
#include "c64.h"
#include "cia.h"
#include "machine-printer.h"
#include "printer.h"
Functions
void machine_printer_setup_context (struct machine_context_s *machinecontext)
int machine_printer_resources_init (void)
void machine_printer_resources_shutdown (void)
int machine_printer_cmdline_options_init (void)
void machine_printer_init (void)
void machine_printer_shutdown (void)
Function Documentation
machine_printer_cmdline_options_init()
int machine_printer_cmdline_options_init (void)
Referenced by printer_cmdline_options_init().
machine_printer_init()
void machine_printer_init (void)
Referenced by printer_init().
machine_printer_resources_init()
int machine_printer_resources_init (void)
Referenced by printer_resources_init().
machine_printer_resources_shutdown()
void machine_printer_resources_shutdown (void)
machine_printer_setup_context()
void machine_printer_setup_context (struct machine_context_s * machinecontext)
Referenced by machine_setup_context().
machine_printer_shutdown()
void machine_printer_shutdown (void)
Referenced by printer_shutdown().