x128: drive/iecieee/via2d.c File Reference
via2d.c File Reference
#include "vice.h"
#include <stdio.h>
#include "drive-writeprotect.h"
#include "drive.h"
#include "drivetypes.h"
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "monitor.h"
#include "rotation.h"
#include "types.h"
#include "via.h"
#include "viad.h"
#include "drive-sound.h"
Data Structures
struct drivevia2_context_s
Macros
#define OLDCODE 0
set to 1 to use the old ca2/cb2 handling code
#define DBG(_x_)
#define DBGSTEP(_x_)
#define PCR_BYTE_READY BRA_BYTE_READY
#define PB_MOTOR_ON BRA_MOTOR_ON
Typedefs
typedef struct drivevia2_context_s drivevia2_context_t
Functions
static void set_ca2 (via_context_t *via_context, int state)
static void set_cb2 (via_context_t *via_context, int state, int offset)
static void set_int (via_context_t *via_context, unsigned int int_num, int value, CLOCK rclk)
see interrupt.h; ugly, but more efficient...
static void restore_int (via_context_t *via_context, unsigned int int_num, int value)
void via2d_store (diskunit_context_t *ctxptr, uint16_t addr, uint8_t data)
uint8_t via2d_read (diskunit_context_t *ctxptr, uint16_t addr)
uint8_t via2d_peek (diskunit_context_t *ctxptr, uint16_t addr)
int via2d_dump (diskunit_context_t *ctxptr, uint16_t addr)
void via2d_update_pcr (int pcrval, drive_t *dptr)
static void store_pra (via_context_t *via_context, uint8_t byte, uint8_t oldpa_value, uint16_t addr)
static void undump_pra (via_context_t *via_context, uint8_t byte)
static void store_prb (via_context_t *via_context, uint8_t byte, uint8_t poldpb, uint16_t addr)
static void undump_prb (via_context_t *via_context, uint8_t byte)
static uint8_t store_pcr (via_context_t *via_context, uint8_t byte, uint16_t addr)
static void undump_pcr (via_context_t *via_context, uint8_t byte)
static void undump_acr (via_context_t *via_context, uint8_t byte)
static void store_acr (via_context_t *via_context, uint8_t byte)
static void store_sr (via_context_t *via_context, uint8_t byte)
static void store_t2l (via_context_t *via_context, uint8_t byte)
static void reset (via_context_t *via_context)
static uint8_t read_pra (via_context_t *via_context, uint16_t addr)
static uint8_t read_prb (via_context_t *via_context)
void via2d_init (diskunit_context_t *ctxptr)
void via2d_setup_context (diskunit_context_t *ctxptr)
Macro Definition Documentation
DBG
#define DBG (_x_)
DBGSTEP
#define DBGSTEP (_x_)
OLDCODE
#define OLDCODE 0
set to 1 to use the old ca2/cb2 handling code
PB_MOTOR_ON
#define PB_MOTOR_ON BRA_MOTOR_ON
PCR_BYTE_READY
#define PCR_BYTE_READY BRA_BYTE_READY
Typedef Documentation
drivevia2_context_t
typedef struct drivevia2_context_s drivevia2_context_t
Function Documentation
read_pra()
static uint8_t read_pra (via_context_t * via_context, uint16_t addr) static
< Data direction register for port A
< Port A
< Data direction register for port A
Referenced by via2d_setup_context().
read_prb()
static uint8_t read_prb (via_context_t * via_context) static
< Data direction register for port B
< Port B
< Data direction register for port B
Referenced by via2d_setup_context().
reset()
static void reset (via_context_t * via_context) static
Referenced by via2d_setup_context().
restore_int()
static void restore_int (via_context_t * via_context, unsigned int int_num, int value) static
Referenced by via2d_setup_context().
set_ca2()
static void set_ca2 (via_context_t * via_context, int state) static
Referenced by via2d_setup_context().
set_cb2()
static void set_cb2 (via_context_t * via_context, int state, int offset) static
Referenced by via2d_setup_context().
set_int()
static void set_int (via_context_t * via_context, unsigned int int_num, int value, CLOCK rclk) static
see interrupt.h; ugly, but more efficient...
Referenced by via2d_setup_context().
store_acr()
static void store_acr (via_context_t * via_context, uint8_t byte) static
Referenced by via2d_setup_context().
store_pcr()
static uint8_t store_pcr (via_context_t * via_context, uint8_t byte, uint16_t addr) static
Referenced by via2d_setup_context().
store_pra()
static void store_pra (via_context_t * via_context, uint8_t byte, uint8_t oldpa_value, uint16_t addr) static
Referenced by via2d_setup_context().
store_prb()
static void store_prb (via_context_t * via_context, uint8_t byte, uint8_t poldpb, uint16_t addr) static
Todo:
FIXME: emulating the mechanical delay with such naive approach does not work, as the actual step is delayed to the next write to pb. regardless how long that will take. for one example that does not work like this, see bug #508
FIXME: we should implement the intended behaviour using an alarm instead.
Todo:
the general assumption for the case when opposite coils are active is that the stepper will not move at all. however, that doesnt seem to be true in all cases. when the stepper is already moving (up or down), and such "double step" takes place with the right timing, then it would actually result in two steps (in the "current" direction!). this seems unreliable on real hw as well, and only very few original titles need it. allowing it always does more harm than good, so we should simply ignore this condition for the time being.
< chosen for the bit in the VIA2 PB register
< chosen for the bit in the VIA2 PB register
< chosen for the bit in the VIA2 PB register
< chosen for the bit in the VIA2 PB register
Referenced by via2d_setup_context().
store_sr()
static void store_sr (via_context_t * via_context, uint8_t byte) static
Referenced by via2d_setup_context().
store_t2l()
static void store_t2l (via_context_t * via_context, uint8_t byte) static
Referenced by via2d_setup_context().
undump_acr()
static void undump_acr (via_context_t * via_context, uint8_t byte) static
Referenced by via2d_setup_context().
undump_pcr()
static void undump_pcr (via_context_t * via_context, uint8_t byte) static
Referenced by via2d_setup_context().
undump_pra()
static void undump_pra (via_context_t * via_context, uint8_t byte) static
Referenced by via2d_setup_context().
undump_prb()
static void undump_prb (via_context_t * via_context, uint8_t byte) static
< chosen for the bit in the VIA2 PB register
< chosen for the bit in the VIA2 PB register
Referenced by via2d_setup_context().
via2d_dump()
int via2d_dump (diskunit_context_t * ctxptr, uint16_t addr)
< Port B
< Peripheral control register
Referenced by drivemem_ioreg_list_get().
via2d_init()
void via2d_init (diskunit_context_t * ctxptr)
Referenced by iecieee_drive_init().
via2d_peek()
uint8_t via2d_peek (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by memiec_init(), and memieee_init().
via2d_read()
uint8_t via2d_read (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by memiec_init(), and memieee_init().
via2d_setup_context()
void via2d_setup_context (diskunit_context_t * ctxptr)
Referenced by iecieee_drive_setup_context().
via2d_store()
void via2d_store (diskunit_context_t * ctxptr, uint16_t addr, uint8_t data)
Referenced by memiec_init(), and memieee_init().
via2d_update_pcr()
void via2d_update_pcr (int pcrval, drive_t * dptr)
< chosen for the bit in the VIA2 PCR register
< chosen for the bit in the VIA2 PCR register
< 0x02
Referenced by store_pcr(), and undump_pcr().