vsid: arch/gtk3/linenoise.c File Reference
linenoise.c File Reference
Guerrilla line editing library against the idea that a line editing lib needs to be 20,000 lines of C code.
#include "vice.h"
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include "linenoise.h"
#include "uimon.h"
Macros
#define LINENOISE_DEFAULT_HISTORY_MAX_LEN 100
#define LINENOISE_MAX_LINE 4096
Functions
int vte_linenoiseHistoryAdd (const char *line)
static void linenoiseAtExit(void);
static void refreshLine (struct console_private_s *term, const char *prompt, char *buf, size_t len, size_t pos, size_t cols)
At exit we'll try to fix the terminal to the initial conditions.
static void beep (struct console_private_s *term)
static void freeCompletions (linenoiseCompletions *lc)
static int completeLine (struct console_private_s *term, const char *prompt, char *buf, size_t buflen, size_t *len, size_t *pos, size_t cols)
void vte_linenoiseClearScreen (struct console_private_s *term)
static int linenoisePrompt (struct console_private_s *term, char *buf, size_t buflen, const char *prompt)
char * vte_linenoise (const char *prompt, struct console_private_s *term)
void vte_linenoiseSetCompletionCallback (linenoiseCompletionCallback *fn)
Register a callback function to be called for tab-completion.
void vte_linenoiseAddCompletion (linenoiseCompletions *lc, char *str)
int vte_linenoiseHistorySetMaxLen (int len)
Variables
static linenoiseCompletionCallback * completionCallback = NULL
static int history_max_len = 100
static struct termios orig_termios;
static int history_len = 0
char ** history = NULL
Detailed Description
Guerrilla line editing library against the idea that a line editing lib needs to be 20,000 lines of C code.
Modified for the VICE project by Fabrizio Gennari, for use in combination with a terminal not represented by a couple of file descrptors (abstracted buy the opaque struct console_private_s)
You can find the latest source code at:
http://github.com/antirez/linenoise
Does a number of crazy assumptions that happen to be true in 99.9999% of the 2010 UNIX computers around.
Copyright (c) 2010, Salvatore Sanfilippo <antirez at gmail dot com> Copyright (c) 2010, Pieter Noordhuis <pcnoordhuis at gmail dot com>
All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
References:
http://invisible-island.net/xterm/ctlseqs/ctlseqs.html
http://www.3waylabs.com/nw/WWW/products/wizcon/vt220.html
Todo list:
Switch to gets() if $TERM is something we can't support.
Filter bogus Ctrl+<char> combinations.
Win32 support
Bloat:
Completion?
History search like Ctrl+r in readline?
List of escape sequences used by this program, we do everything just with three sequences. In order to be so cheap we may have some flickering effect with some slow terminal, but the lesser sequences the more compatible.
CHA (Cursor Horizontal Absolute) Sequence: ESC [ n G Effect: moves cursor to column n
EL (Erase Line) Sequence: ESC [ n K Effect: if n is 0 or missing, clear from cursor to end of line Effect: if n is 1, clear from beginning of line to cursor Effect: if n is 2, clear entire line
CUF (CUrsor Forward) Sequence: ESC [ n C Effect: moves cursor forward of n chars
The following are used to clear the screen: ESC [ H ESC [ 2 J This is actually composed of two sequences:
cursorhome Sequence: ESC [ H Effect: moves the cursor to upper left corner
ED2 (Clear entire screen) Sequence: ESC [ 2 J Effect: clear the whole screen
Macro Definition Documentation
LINENOISE_DEFAULT_HISTORY_MAX_LEN
#define LINENOISE_DEFAULT_HISTORY_MAX_LEN 100
LINENOISE_MAX_LINE
#define LINENOISE_MAX_LINE 4096
Function Documentation
beep()
static void beep (struct console_private_s * term) static
Referenced by completeLine().
completeLine()
static int completeLine (struct console_private_s * term, const char * prompt, char * buf, size_t buflen, size_t * len, size_t * pos, size_t cols) static
Referenced by linenoisePrompt().
freeCompletions()
static void freeCompletions (linenoiseCompletions * lc) static
Referenced by completeLine().
linenoisePrompt()
static int linenoisePrompt (struct console_private_s * term, char * buf, size_t buflen, const char * prompt) static
Referenced by vte_linenoise().
refreshLine()
static void refreshLine (struct console_private_s * term, const char * prompt, char * buf, size_t len, size_t pos, size_t cols) static
At exit we'll try to fix the terminal to the initial conditions.
Todo:
FIXME: unused -> memory leak static void freeHistory(void) { if (history) { int j;
for (j = 0; j < history_len; j++) { free(history[j]); } free(history); } }
Referenced by completeLine(), and linenoisePrompt().
vte_linenoise()
char * vte_linenoise (const char * prompt, struct console_private_s * term)
Referenced by uimon_get_in().
vte_linenoiseAddCompletion()
void vte_linenoiseAddCompletion (linenoiseCompletions * lc, char * str)
Referenced by console_init(), fill_completions(), and monitor_completions().
vte_linenoiseClearScreen()
void vte_linenoiseClearScreen (struct console_private_s * term)
Referenced by linenoisePrompt().
vte_linenoiseHistoryAdd()
int vte_linenoiseHistoryAdd (const char * line)
static void linenoiseAtExit(void);
Using a circular buffer is smarter, but a bit more complex to handle.
Referenced by linenoisePrompt(), and uimon_get_in().
vte_linenoiseHistorySetMaxLen()
int vte_linenoiseHistorySetMaxLen (int len)
vte_linenoiseSetCompletionCallback()
void vte_linenoiseSetCompletionCallback (linenoiseCompletionCallback * fn)
Register a callback function to be called for tab-completion.
Referenced by uimon_get_in().
Variable Documentation
completionCallback
linenoiseCompletionCallback* completionCallback = NULL static
Referenced by completeLine(), linenoisePrompt(), and vte_linenoiseSetCompletionCallback().
history
char** history = NULL
Referenced by linenoisePrompt(), vte_linenoiseHistoryAdd(), and vte_linenoiseHistorySetMaxLen().
history_len
int history_len = 0 static
Referenced by linenoisePrompt(), vte_linenoiseHistoryAdd(), and vte_linenoiseHistorySetMaxLen().
history_max_len
int history_max_len = 100 static
static struct termios orig_termios;
static int atexit_registered = 0;
Referenced by vte_linenoiseHistoryAdd(), and vte_linenoiseHistorySetMaxLen().