x128: arch/gtk3/widgets/settings_autofire.c File Reference
settings_autofire.c File Reference
Widget to control autofire settings for joysticks.
#include "vice.h"
#include <gtk/gtk.h>
#include "joyport.h"
#include "joystickautofirewidget.h"
#include "machine.h"
#include "vice_gtk3.h"
#include "settings_autofire.h"
Functions
static int add_userport_widgets (GtkWidget *layout, int row, int count)
See widgets/joystickautofirewidget.c for resources used.
static int create_c64_layout (GtkWidget *layout, int row)
Create layout for x64, x64sc, x64dtv, xscpu64, x128 and xcbm5x0.
static int create_vic20_layout (GtkWidget *layout, int row)
Create layout for xvic.
static int create_cbm2_layout (GtkWidget *layout, int row)
Create layout for xcbm2.
static int create_pet_layout (GtkWidget *layout, int row)
Create layout for xpet.
static int create_plus4_layout (GtkWidget *layout, int row)
Create layout for xplus4.
GtkWidget * settings_autofire_widget_create (GtkWidget *parent)
Create settings 'page' widget for autofire settings.
Detailed Description
Widget to control autofire settings for joysticks.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
add_userport_widgets()
static int add_userport_widgets (GtkWidget * layout, int row, int count) static
See widgets/joystickautofirewidget.c for resources used.
Add userport joystick widgets to layout
Add userport joystick widgets, starting at resource 'JoyStick3*'.
Parameters
[in] layout GtkGrid to add widgets to
[in] row row in layout to start
[in] count number of widgets to add
Returns
row in layout for additional widgets
Referenced by create_c64_layout(), create_cbm2_layout(), create_pet_layout(), create_plus4_layout(), and create_vic20_layout().
create_c64_layout()
static int create_c64_layout (GtkWidget * layout, int row) static
Create layout for x64, x64sc, x64dtv, xscpu64, x128 and xcbm5x0.
Parameters
[in] layout GtkGrid to add widgets to
[in] row row in layout to start adding widgets
Returns
row in layout for additional widgets
Referenced by settings_autofire_widget_create().
create_cbm2_layout()
static int create_cbm2_layout (GtkWidget * layout, int row) static
Create layout for xcbm2.
Parameters
[in] layout GtkGrid to add widgets to
[in] row row in layout to start adding widgets
Returns
row in layout for additional widgets
Referenced by settings_autofire_widget_create().
create_pet_layout()
static int create_pet_layout (GtkWidget * layout, int row) static
Create layout for xpet.
Parameters
[in] layout GtkGrid to add widgets to
[in] row row in layout to start adding widgets
Returns
row in layout for additional widgets
Referenced by settings_autofire_widget_create().
create_plus4_layout()
static int create_plus4_layout (GtkWidget * layout, int row) static
Create layout for xplus4.
Parameters
[in] layout GtkGrid to add widgets to
[in] row row in layout to start adding widgets
Returns
row in layout for additional widgets
Note
Contains support for the 3-way userport joystick adapter from Synergy, which isn't emulated yet. See https://plus4world.powweb.com/hardware/3fach_Joystickadapter_Synergy for details. This moves the SIDCard joystick port to JoyStick6.
Referenced by settings_autofire_widget_create().
create_vic20_layout()
static int create_vic20_layout (GtkWidget * layout, int row) static
Create layout for xvic.
Parameters
[in] layout GtkGrid to add widgets to
[in] row row in layout to start adding widgets
Returns
row in layout for additional widgets
Referenced by settings_autofire_widget_create().
settings_autofire_widget_create()
GtkWidget * settings_autofire_widget_create (GtkWidget * parent)
Create settings 'page' widget for autofire settings.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid