x128: arch/gtk3/widgets/settings_sfxsoundexpander.c File Reference
settings_sfxsoundexpander.c File Reference
Setting widget for SFX Sound Expander resources.
#include "vice.h"
#include <gtk/gtk.h>
#include "cartridge.h"
#include "machine.h"
#include "vice_gtk3.h"
#include "settings_sfxsoundexpander.h"
Functions
static void set_widgets_sensitivity (gboolean sensitive)
Set sensitivity of the IO swap and YM Chip selection widgets.
static void on_sfx_sound_expander_toggled (GtkWidget *widget, gpointer user_data)
Handler for the 'toggled' event of the SFXSE check button.
static GtkWidget * create_sfx_chip_widget (void)
Create YM chip selection widget.
GtkWidget * settings_sfxsoundexpander_widget_create (GtkWidget *parent)
Create SFX Sound Expander widget.
Variables
static const vice_gtk3_radiogroup_entry_t chip_models []
List of YM chip models.
static GtkWidget * chip_group = NULL
Chip selection radiogroup.
static GtkWidget * io_swap = NULL
I/O swap toggle button.
Detailed Description
Setting widget for SFX Sound Expander resources.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_sfx_chip_widget()
static GtkWidget * create_sfx_chip_widget (void) static
Create YM chip selection widget.
Returns
GtkGrid
Referenced by settings_sfxsoundexpander_widget_create().
on_sfx_sound_expander_toggled()
static void on_sfx_sound_expander_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the 'toggled' event of the SFXSE check button.
Parameters
[in] widget check button
[in,out] user_data unused
Referenced by settings_sfxsoundexpander_widget_create().
set_widgets_sensitivity()
static void set_widgets_sensitivity (gboolean sensitive) static
Set sensitivity of the IO swap and YM Chip selection widgets.
Parameters
[in] sensitive sensitivity
Referenced by on_sfx_sound_expander_toggled(), and settings_sfxsoundexpander_widget_create().
settings_sfxsoundexpander_widget_create()
GtkWidget * settings_sfxsoundexpander_widget_create (GtkWidget * parent)
Create SFX Sound Expander widget.
Parameters
[in] parent parent widget
Returns
GtkGrid
< sfx_soundexpander.c, fmopl.c
< sfx_soundexpander.c, fmopl.c
< http://www.floodgap.com/retrobits/ckb/secret/cbm-sfx-fmbport.jpg
Variable Documentation
chip_group
GtkWidget* chip_group = NULL static
Chip selection radiogroup.
Referenced by set_widgets_sensitivity(), and settings_sfxsoundexpander_widget_create().
chip_models
const vice_gtk3_radiogroup_entry_t chip_models[] static
Initial value:
= {
    { "3526", 3526 },
    { "3812", 3812 },
    { NULL,     -1 }
}
List of YM chip models.
Referenced by create_sfx_chip_widget().
io_swap
GtkWidget* io_swap = NULL static
I/O swap toggle button.
Referenced by on_enable_toggled(), set_widgets_sensitivity(), settings_sfxsoundexpander_widget_create(), and settings_sfxsoundsampler_widget_create().