vsid: arch/gtk3/widgets/base/popupmenu.h File Reference
popupmenu.h File Reference
Gtk3 popup menu helpers - header.
#include <gtk/gtk.h>
#include <stdbool.h>
Data Structures
struct popup_item_s
Popup menu item object.
Macros
#define POPUP_MENU_TERMINATOR { .type = POPUP_MENU_SENTINEL }
Typedefs
typedef struct popup_item_s popup_item_t
Popup menu item object.
Enumerations
enum {
POPUP_ITEM_SENTINEL = -1 ,
POPUP_ITEM_NORMAL ,
POPUP_ITEM_CHECK ,
POPUP_ITEM_RADIO ,
POPUP_ITEM_SUBMENU ,
POPUP_ITEM_SEPARATOR
}
Functions
GtkWidget * popup_menu_item_action_new (const char *text, int action)
Create menu item that triggers a UI action.
void popup_menu_add_separator (GtkWidget *menu)
Add separator item to menu.
GtkWidget * popup_menu_new (const popup_item_t *items)
Create popup menu.
GtkWidget * popup_menu_nth_item (GtkWidget *menu, guint n)
Get item of menu by index.
Detailed Description
Gtk3 popup menu helpers - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
POPUP_MENU_TERMINATOR
#define POPUP_MENU_TERMINATOR { .type = POPUP_MENU_SENTINEL }
Typedef Documentation
popup_item_t
typedef struct popup_item_s popup_item_t
Popup menu item object.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
POPUP_ITEM_SENTINEL
end of items list
POPUP_ITEM_NORMAL
normal menu item
POPUP_ITEM_CHECK
check button item
POPUP_ITEM_RADIO
radio menu item
POPUP_ITEM_SUBMENU
submenu
POPUP_ITEM_SEPARATOR
separator
Function Documentation
popup_menu_add_separator()
void popup_menu_add_separator (GtkWidget * menu)
Add separator item to menu.
Parameters
[in] menu menu
Referenced by ui_do_drive_popup().
popup_menu_item_action_new()
GtkWidget * popup_menu_item_action_new (const char * text, int action)
Create menu item that triggers a UI action.
Creates menu item to trigger action, setting the appropriate accelerator if a hotkey is defined for action.
Parameters
[in] text text for the item
[in] action UI action ID
Referenced by ui_do_drive_popup().
popup_menu_new()
GtkWidget * popup_menu_new (const popup_item_t * items)
Create popup menu.
Create popup menu from items.
Parameters
[in] items list of items for the new menu
Returns
GtkMenu
Referenced by popup_menu_new().
popup_menu_nth_item()
GtkWidget * popup_menu_nth_item (GtkWidget * menu, guint n)
Get item of menu by index.
Parameters
[in] menu popup menu
[in] n index of item to retrieve
Returns
GtkMenuItem or NULL when not found