vsid: diskimage/fsimage-gcr.c File Reference
fsimage-gcr.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "diskconstants.h"
#include "diskimage.h"
#include "fsimage-gcr.h"
#include "fsimage.h"
#include "gcr.h"
#include "cbmdos.h"
#include "log.h"
#include "lib.h"
#include "types.h"
#include "util.h"
Functions
int fsimage_read_gcr_image (const disk_image_t *image)
Intial GCR buffer setup.
static long fsimage_gcr_seek_half_track (fsimage_t *fsimage, unsigned int half_track, uint16_t *max_track_length, uint8_t *num_half_tracks)
Seek to half track.
int fsimage_gcr_read_half_track (const disk_image_t *image, unsigned int half_track, disk_track_t *raw)
Read an entire GCR track from the disk image.
static int fsimage_gcr_read_track (const disk_image_t *image, unsigned int track, disk_track_t *raw)
int fsimage_gcr_write_half_track (disk_image_t *image, unsigned int half_track, const disk_track_t *raw)
Write an entire GCR track to the disk image.
static int fsimage_gcr_write_track (disk_image_t *image, unsigned int track, const disk_track_t *raw)
int fsimage_gcr_read_sector (const disk_image_t *image, uint8_t *buf, const disk_addr_t *dadr)
Read a sector from the GCR disk image.
int fsimage_gcr_write_sector (disk_image_t *image, const uint8_t *buf, const disk_addr_t *dadr)
Write a sector to the GCR disk image.
void fsimage_gcr_init (void)
Variables
static log_t fsimage_gcr_log = ((log_t)-1)
static const uint8_t gcr_image_header_expected_1541 []
static const uint8_t gcr_image_header_expected_1571 []
Function Documentation
fsimage_gcr_init()
void fsimage_gcr_init (void)
Referenced by fsimage_init().
fsimage_gcr_read_half_track()
int fsimage_gcr_read_half_track (const disk_image_t * image, unsigned int half_track, disk_track_t * raw)
Read an entire GCR track from the disk image.
Referenced by fsimage_gcr_read_track(), and fsimage_read_gcr_image().
fsimage_gcr_read_sector()
int fsimage_gcr_read_sector (const disk_image_t * image, uint8_t * buf, const disk_addr_t * dadr)
Read a sector from the GCR disk image.
Referenced by fsimage_read_sector().
fsimage_gcr_read_track()
static int fsimage_gcr_read_track (const disk_image_t * image, unsigned int track, disk_track_t * raw) static
Referenced by fsimage_gcr_read_sector(), and fsimage_gcr_write_sector().
fsimage_gcr_seek_half_track()
static long fsimage_gcr_seek_half_track (fsimage_t * fsimage, unsigned int half_track, uint16_t * max_track_length, uint8_t * num_half_tracks) static
Seek to half track.
Referenced by fsimage_gcr_read_half_track(), and fsimage_gcr_write_half_track().
fsimage_gcr_write_half_track()
int fsimage_gcr_write_half_track (disk_image_t * image, unsigned int half_track, const disk_track_t * raw)
Write an entire GCR track to the disk image.
Todo:
FIXME: danger zone: 'DWORD' is a loose term, doesn't indicate a size, just that's the next bigger size of 'WORD'. Probably these terms are taken from the horrible Win API. – compyx 2020-07-24
Referenced by disk_image_write_half_track(), and fsimage_gcr_write_track().
fsimage_gcr_write_sector()
int fsimage_gcr_write_sector (disk_image_t * image, const uint8_t * buf, const disk_addr_t * dadr)
Write a sector to the GCR disk image.
Referenced by fsimage_write_sector().
fsimage_gcr_write_track()
static int fsimage_gcr_write_track (disk_image_t * image, unsigned int track, const disk_track_t * raw) static
Referenced by fsimage_gcr_write_sector().
fsimage_read_gcr_image()
int fsimage_read_gcr_image (const disk_image_t * image)
Intial GCR buffer setup.
Referenced by disk_image_read_image().
Variable Documentation
fsimage_gcr_log
log_t fsimage_gcr_log = ((log_t)-1) static
Referenced by fsimage_gcr_init(), fsimage_gcr_read_half_track(), fsimage_gcr_read_sector(), fsimage_gcr_seek_half_track(), fsimage_gcr_write_half_track(), and fsimage_gcr_write_sector().
gcr_image_header_expected_1541
const uint8_t gcr_image_header_expected_1541[] static
Initial value:
=
    { 0x47, 0x43, 0x52, 0x2D, 0x31, 0x35, 0x34, 0x31, 0x00 }
Referenced by fsimage_gcr_seek_half_track().
gcr_image_header_expected_1571
const uint8_t gcr_image_header_expected_1571[] static
Initial value:
=
    { 0x47, 0x43, 0x52, 0x2D, 0x31, 0x35, 0x37, 0x31, 0x00 }
Referenced by fsimage_gcr_seek_half_track().