x128: vice-event.h File Reference
vice-event.h File Reference
#include "types.h"
Data Structures
struct event_list_s
struct event_list_state_s
Macros
#define EVENT_LIST_END 0
#define EVENT_KEYBOARD_MATRIX 1
#define EVENT_KEYBOARD_RESTORE 2
#define EVENT_JOYSTICK_VALUE 3
#define EVENT_DATASETTE 4
#define EVENT_INITIAL 5
#define EVENT_ATTACHDISK 6
#define EVENT_ATTACHTAPE 7
#define EVENT_RESETCPU 8
#define EVENT_TIMESTAMP 9
#define EVENT_ATTACHIMAGE 10
#define EVENT_KEYBOARD_DELAY 12
#define EVENT_JOYSTICK_DELAY 13
#define EVENT_SYNC_TEST 14
#define EVENT_KEYBOARD_CLEAR 15
#define EVENT_RESOURCE 16
#define EVENT_START_MODE_FILE_SAVE 0
#define EVENT_START_MODE_FILE_LOAD 1
#define EVENT_START_MODE_RESET 2
#define EVENT_START_MODE_PLAYBACK 3
Typedefs
typedef struct event_list_s event_list_t
typedef struct event_list_state_s event_list_state_t
Functions
void event_init (void)
int event_resources_init (void)
void event_shutdown (void)
int event_cmdline_options_init (void)
void event_register_event_list (event_list_state_t *list)
void event_init_image_list (void)
void event_destroy_image_list (void)
void event_clear_list (event_list_state_t *list)
void event_playback_event_list (event_list_state_t *list)
int event_record_start (void)
int event_record_stop (void)
int event_playback_start (void)
int event_playback_stop (void)
int event_record_active (void)
int event_playback_active (void)
int event_record_set_milestone (void)
int event_record_reset_milestone (void)
void event_reset_ack (void)
void event_record_in_list (event_list_state_t *list, unsigned int type, void *data, unsigned int size)
void event_record (unsigned int type, void *data, unsigned int size)
void event_record_attach_in_list (event_list_state_t *list, unsigned int unit, unsigned int drive, const char *filename, unsigned int read_only)
void event_record_attach_image (unsigned int unit, unsigned int drive, const char *filename, unsigned int read_only)
int event_snapshot_read_module (struct snapshot_s *s, int event_mode)
int event_snapshot_write_module (struct snapshot_s *s, int event_mode)
Macro Definition Documentation
EVENT_ATTACHDISK
#define EVENT_ATTACHDISK 6
EVENT_ATTACHIMAGE
#define EVENT_ATTACHIMAGE 10
EVENT_ATTACHTAPE
#define EVENT_ATTACHTAPE 7
EVENT_DATASETTE
#define EVENT_DATASETTE 4
EVENT_INITIAL
#define EVENT_INITIAL 5
EVENT_JOYSTICK_DELAY
#define EVENT_JOYSTICK_DELAY 13
EVENT_JOYSTICK_VALUE
#define EVENT_JOYSTICK_VALUE 3
EVENT_KEYBOARD_CLEAR
#define EVENT_KEYBOARD_CLEAR 15
EVENT_KEYBOARD_DELAY
#define EVENT_KEYBOARD_DELAY 12
EVENT_KEYBOARD_MATRIX
#define EVENT_KEYBOARD_MATRIX 1
EVENT_KEYBOARD_RESTORE
#define EVENT_KEYBOARD_RESTORE 2
EVENT_LIST_END
#define EVENT_LIST_END 0
EVENT_RESETCPU
#define EVENT_RESETCPU 8
EVENT_RESOURCE
#define EVENT_RESOURCE 16
EVENT_START_MODE_FILE_LOAD
#define EVENT_START_MODE_FILE_LOAD 1
EVENT_START_MODE_FILE_SAVE
#define EVENT_START_MODE_FILE_SAVE 0
EVENT_START_MODE_PLAYBACK
#define EVENT_START_MODE_PLAYBACK 3
EVENT_START_MODE_RESET
#define EVENT_START_MODE_RESET 2
EVENT_SYNC_TEST
#define EVENT_SYNC_TEST 14
EVENT_TIMESTAMP
#define EVENT_TIMESTAMP 9
Typedef Documentation
event_list_state_t
typedef struct event_list_state_s event_list_state_t
event_list_t
typedef struct event_list_s event_list_t
Function Documentation
event_clear_list()
void event_clear_list (event_list_state_t * list)
Referenced by destroy_list(), network_client_connect_trap(), network_free_frame_event_list(), network_hook_connected_receive(), network_prepare_next_frame(), and network_server_connect_trap().
event_cmdline_options_init()
int event_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
event_destroy_image_list()
void event_destroy_image_list (void)
Referenced by destroy_list(), event_record_start_trap(), and network_free_frame_event_list().
event_init()
void event_init (void)
Referenced by machine_specific_init().
event_init_image_list()
void event_init_image_list (void)
Referenced by create_list(), and network_init_frame_event_list().
event_playback_active()
int event_playback_active (void)
Referenced by autostart_autodetect(), autostart_disk(), autostart_prg(), autostart_snapshot(), autostart_tape(), file_system_attach_disk(), file_system_detach_disk(), keyboard_key_clear(), keyboard_key_pressed(), keyboard_key_released(), machine_trigger_reset(), tape_image_attach(), and tape_image_detach().
event_playback_event_list()
void event_playback_event_list (event_list_state_t * list)
Todo:
drive 1?
Referenced by network_client_connect_trap(), and network_hook_connected_receive().
event_playback_start()
int event_playback_start (void)
Referenced by cmdline_help(), and history_playback_start_action().
event_playback_stop()
int event_playback_stop (void)
Referenced by event_alarm_handler(), event_record_start(), and history_playback_stop_action().
event_record()
void event_record (unsigned int type, void * data, unsigned int size)
Referenced by event_initial_write(), event_record_stop(), file_system_detach_disk_internal(), keyboard_event_record(), machine_trigger_reset(), restore_alarm_triggered(), and tape_image_detach_internal().
event_record_active()
int event_record_active (void)
Referenced by autostart_autodetect(), autostart_disk(), autostart_prg(), autostart_snapshot(), autostart_tape(), on_stop_clicked(), statusbar_recording_widget_set_recording_status(), and statusbar_recording_widget_set_time().
event_record_attach_image()
void event_record_attach_image (unsigned int unit, unsigned int drive, const char * filename, unsigned int read_only)
Referenced by file_system_attach_disk_internal(), and tape_image_attach_internal().
event_record_attach_in_list()
void event_record_attach_in_list (event_list_state_t * list, unsigned int unit, unsigned int drive, const char * filename, unsigned int read_only)
< read mode (binary)
Referenced by event_record_attach_image(), and network_attach_image().
event_record_in_list()
void event_record_in_list (event_list_state_t * list, unsigned int type, void * data, unsigned int size)
Referenced by event_record(), network_create_event_list(), network_event_record(), and resources_get_event_safe_list().
event_record_reset_milestone()
int event_record_reset_milestone (void)
Referenced by history_milestone_reset_action().
event_record_set_milestone()
int event_record_set_milestone (void)
Referenced by history_milestone_set_action().
event_record_start()
int event_record_start (void)
Referenced by history_record_start_action().
event_record_stop()
int event_record_stop (void)
Referenced by history_record_stop_action(), and on_stop_clicked().
event_register_event_list()
void event_register_event_list (event_list_state_t * list)
Referenced by create_list(), network_create_event_list(), network_init_frame_event_list(), network_prepare_next_frame(), and network_server_connect_trap().
event_reset_ack()
void event_reset_ack (void)
Referenced by machine_reset().
event_resources_init()
int event_resources_init (void)
Referenced by machine_resources_init().
event_shutdown()
void event_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
event_snapshot_read_module()
int event_snapshot_read_module (struct snapshot_s * s, int event_mode)
Referenced by c128_snapshot_read(), and event_playback_start_trap().
event_snapshot_write_module()
int event_snapshot_write_module (struct snapshot_s * s, int event_mode)
Referenced by c128_snapshot_write().