x128: vicesocket.h File Reference
vicesocket.h File Reference
#include "types.h"
Typedefs
typedef struct vice_network_socket_s vice_network_socket_t
typedef struct vice_network_socket_address_s vice_network_socket_address_t
Functions
vice_network_socket_t * vice_network_server (const vice_network_socket_address_t *server_address)
Open a socket and initialise it for server operation.
vice_network_socket_t * vice_network_client (const vice_network_socket_address_t *server_address)
Open a socket and initialise it for client operation.
vice_network_socket_address_t * vice_network_address_generate (const char *address, unsigned short port)
Generate a socket address.
void vice_network_address_close (vice_network_socket_address_t *)
Return memory of a socket address.
vice_network_socket_t * vice_network_accept (vice_network_socket_t *sockfd)
Accept a connection on a listening socket.
int vice_network_socket_close (vice_network_socket_t *sockfd)
Close a socket.
int vice_network_send (vice_network_socket_t *sockfd, const void *buffer, size_t buffer_length, int flags)
Send data on a connected socket.
int vice_network_receive (vice_network_socket_t *sockfd, void *buffer, size_t buffer_length, int flags)
Receive data from a connected socket.
int vice_network_select_poll_one (vice_network_socket_t *readsockfd)
Check if a socket has incoming data to receive.
int vice_network_select_multiple (vice_network_socket_t **readsockfd)
Monitor multiple sockets.
int vice_network_get_errorcode (void)
Get the error of the last socket operation.
Detailed Description
Author
Spiro Trikaliotis
Abstraction from network sockets.
socket.h - Abstraction from network sockets.
Written by Spiro Trikaliotis spiro.nosp@m..tri.nosp@m.kalio.nosp@m.tis@.nosp@m.gmx.d.nosp@m.e
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Typedef Documentation
vice_network_socket_address_t
typedef struct vice_network_socket_address_s vice_network_socket_address_t
vice_network_socket_t
typedef struct vice_network_socket_s vice_network_socket_t
Function Documentation
vice_network_accept()
vice_network_socket_t * vice_network_accept (vice_network_socket_t * sockfd)
Accept a connection on a listening socket.
This function accepts a connection on a socket that has been opened with vice_network_server().
Parameters
sockfd The socket that has been oped with vice_network_server()
Returns
A new socket that can be used for transmission on this this connection.
Referenced by monitor_binary_data_available(), monitor_network_data_available(), network_hook(), and start_ffmpeg_executable().
vice_network_address_close()
void vice_network_address_close (vice_network_socket_address_t * address)
Return memory of a socket address.
This function returns a socket address to the memory pool of addresses.
Parameters
address A socket address that has been allocated by vice_network_alloc_new_socket_address() or by vice_network_address_generate().
Referenced by monitor_binary_activate(), monitor_network_activate(), network_connect_client(), network_start_server(), rs232net_open(), and vice_network_address_generate().
vice_network_address_generate()
vice_network_socket_address_t * vice_network_address_generate (const char * address_string, unsigned short port)
Generate a socket address.
Initialises a socket address with the value specified as input parameter.
Parameters
address_string A string describing the address to set.
port A default port number. If address_string does not specify a port number, the number here will be used. If address_string specifies a port number, that one will be used instead.
Returns
socket_address Pointer to a socket address that has been initialised to the specification in address_string (and port, if supported). NULL in case of an error.
Remarks
If address_string starts with a pipe ('|'), then the address_string is treated as a unix domain socket. Otherwise, address_string can be prepended with ip6:// or ip4://, in which case address_string is treated exactly as an IPv6 or IPv4 address, respectively.
If there is no specification, this routine tests for an IPv6 address. If this fails, it tries an IPv4 address.
Todo:
FIXME: "|" as first character indicates that we want to pipe through an external process - if we want to support unix domain socket, this has to use another syntax!
Referenced by monitor_binary_activate(), monitor_network_activate(), network_connect_client(), network_start_server(), rs232_is_physical_device(), rs232net_open(), and start_ffmpeg_executable().
vice_network_client()
vice_network_socket_t * vice_network_client (const vice_network_socket_address_t * server_address)
Open a socket and initialise it for client operation.
Parameters
server_address The address of the server to which to connect to.
Returns
0 on error; else, a handle to the socket on success.
Remarks
The server_address variable determines the type of socket to be used (IPv4, IPv6, Unix Domain Socket, ...)
Referenced by network_connect_client(), rs232net_open(), and start_ffmpeg_executable().
vice_network_get_errorcode()
int vice_network_get_errorcode (void)
Get the error of the last socket operation.
This function determines the error code for the last socket operation.
Returns
the error code
Remarks
It does not distinguish between different sockets, thus, make sure to call it directly after an erroneous socket operation. Furthermore, reading the error status does not reset the error code. Thus, do not expect correct results if the previous operation did not produce an error.
Todo:
Generate a mapping between WIN32 and Unix style error numbers
Referenced by _rs232net_getc(), and _rs232net_putc().
vice_network_receive()
int vice_network_receive (vice_network_socket_t * sockfd, void * buffer, size_t buffer_length, int flags)
Receive data from a connected socket.
This function receives incoming data from a connected socket. opened either by vice_network_client() or vice_network_accept().
Parameters
sockfd The connected socket to receive from
buffer Pointer to the buffer which will hold the received data
buffer_length The length of the buffer pointed to by buffer. This indicates the maximum number of bytes to receive.
flags Flags for the socket. These flags are architecture dependent.
Returns
the number of bytes received. This can be less than buffer_length.
When the return value is 0, either the other site has gracefully closed the socket (and all data has been received), or no data was received in the case of a non-blocking socket.
In case of an error, -1 is returned.
Referenced by _rs232net_getc(), monitor_binary_receive(), monitor_network_receive(), and network_recv_buffer().
vice_network_select_multiple()
int vice_network_select_multiple (vice_network_socket_t ** readsockfd)
Monitor multiple sockets.
This function blocks for many different connections and returns when any has data.
Parameters
readsockfd NULL terminated list of sockets to monitor
Returns
1 if the specified socket has data; 0 if it does not contain any data, and -1 in case of an error.
Referenced by uimon_in().
vice_network_select_poll_one()
int vice_network_select_poll_one (vice_network_socket_t * readsockfd)
Check if a socket has incoming data to receive.
This function is called in order to determine if there is data to be received on a socket. For a blocking socket, this is the only way to receive data without actually blocking.
Parameters
readsockfd The connected socket to test for data
Returns
1 if the specified socket has data; 0 if it does not contain any data, and -1 in case of an error.
Referenced by _rs232net_getc(), monitor_binary_data_available(), monitor_network_data_available(), network_hook(), and start_ffmpeg_executable().
vice_network_send()
int vice_network_send (vice_network_socket_t * sockfd, const void * buffer, size_t buffer_length, int flags)
Send data on a connected socket.
This function sends outgoing data to a connected socket. opened either by vice_network_client() or vice_network_accept().
Parameters
sockfd The connected socket to send to
buffer Pointer to the buffer which holds the data to send
buffer_length The length of the buffer pointed to by buffer.
flags Flags for the socket. These flags are architecture dependent.
Returns
the number of bytes send. For non-blocking sockets, this can be less than len. For blocking sockets (default), any return value different than len must be treated as an error.
Note
Amazing there's docs on this, but send() returns size_t, not int, so properly checking the return type could fail.
Referenced by _rs232net_putc(), ffmpegexe_soundmovie_encode(), monitor_binary_transmit(), monitor_network_transmit(), network_send_buffer(), write_initial_audio_frames(), and write_video_frame().
vice_network_server()
vice_network_socket_t * vice_network_server (const vice_network_socket_address_t * server_address)
Open a socket and initialise it for server operation.
Parameters
server_address The address of the server to which to bind to.
Returns
0 on error; else, a handle to the socket on success.
Remarks
The server_address variable determines the type of socket to be used (IPv4, IPv6, Unix Domain Socket, ...) Thus, server_address must not be NULL.
Referenced by monitor_binary_activate(), monitor_network_activate(), network_start_server(), start_ffmpeg_executable(), and vice_network_server().
vice_network_socket_close()
int vice_network_socket_close (vice_network_socket_t * sockfd)
Close a socket.
This function closes the socket that has been opened either by vice_network_server(), vice_network_client() or vice_network_accept().
Parameters
sockfd The socket to be closed
Returns
0 on success, else an error occurred.
Referenced by close_audio_stream(), close_stream(), close_video_stream(), monitor_binary_deactivate(), monitor_binary_quit(), monitor_network_deactivate(), monitor_network_quit(), network_connect_client(), network_disconnect(), and rs232net_closesocket().