vsid: arch/gtk3/widgets/dirmenupopup.c File Reference
dirmenupopup.c File Reference
Create a menu to show a directory of a drive or tape deck.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdbool.h>
#include "attach.h"
#include "autostart.h"
#include "charset.h"
#include "csshelpers.h"
#include "debug_gtk3.h"
#include "diskimage.h"
#include "diskimage/fsimage.h"
#include "drive.h"
#include "drivetypes.h"
#include "imagecontents/diskcontents.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "tape.h"
#include "tapeport.h"
#include "unicodehelpers.h"
#include "util.h"
#include "widgethelpers.h"
#include "dirmenupopup.h"
Macros
#define MENULABEL_CSS
CSS style string to set the CBM font and remove padding.
#define MENUITEM_CSS
CSS style string to remove padding from menu items.
Functions
static void on_item_activate (GtkWidget *item, gpointer data)
Handler for the "activate" event of a menu item.
static gboolean create_css_providers (void)
Create reusable CSS providers.
static void dir_item_apply_style (GtkWidget *item)
Apply CSS style and margins to a directory listing item.
GtkWidget * dir_menu_popup_create (int unit, int drive, read_contents_func_type func, void(*response)(const char *, int, int, unsigned int))
Create a popup menu to select a file to autostart.
Variables
static read_contents_func_type content_func
Function to read the contents of an image.
static void(* response_func)(const char *, int, int, unsigned int)
Function to call when a file in the directory is selected.
static const char * autostart_diskimage
Disk image being used.
static GtkCssProvider * menulabel_css_provider
CSS provider used for directory entry GtkMenuItem labels.
static GtkCssProvider * menuitem_css_provider
CSS provider used for directory entry GtkMenuItem's.
Detailed Description
Create a menu to show a directory of a drive or tape deck.
!
Todo:
FIXME: The current code depends way too much on internal/core code. The code to retrieve the current disk/tape image should be implemented somewhere in the core code, not here.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Groepaz (groep.nosp@m.az@g.nosp@m.mx.de>
Macro Definition Documentation
MENUITEM_CSS
#define MENUITEM_CSS
Value:
    "menuitem {\n" \
    "  min-height: 16px;\n" \
    "  margin: 0px;\n" \
    "  border: 0px;\n" \
    "  padding: 0px;\n" \
    "}"
CSS style string to remove padding from menu items.
MENULABEL_CSS
#define MENULABEL_CSS
Value:
    "label {\n" \
    "  font-family: \"C64 Pro Mono\";\n" \
    "  font-size: 16px;\n" \
    "  min-height: 16px;\n" \
    "  letter-spacing: 0;\n" \
    "  margin: -2px;\n" \
    "  border: 0px;\n" \
    "  padding: 0px;\n" \
    "}"
CSS style string to set the CBM font and remove padding.
Function Documentation
create_css_providers()
static gboolean create_css_providers (void) static
Create reusable CSS providers.
Returns
bool
Referenced by dir_menu_popup_create().
dir_item_apply_style()
static void dir_item_apply_style (GtkWidget * item) static
Apply CSS style and margins to a directory listing item.
Parameters
[in,out] item direct list item
Referenced by dir_menu_popup_create().
dir_menu_popup_create()
GtkWidget * dir_menu_popup_create (int unit, int drive, read_contents_func_type func, void(*)(const char *, int, int, unsigned int) response)
Create a popup menu to select a file to autostart.
XXX: This is an UNHOLY MESS, and should be refactored
Parameters
[in] unit unit number (1,2 for tapes, 8-11 for drives)
[in] drive drive number (0 or 1 (dual-drives))
[in] func function to read image contents
[in] response function to call when an item has been selected
Returns
GtkMenu
< return string in PETSCII form
< return string in PETSCII form
Referenced by ui_do_datasette_popup(), and ui_do_drive_popup().
on_item_activate()
static void on_item_activate (GtkWidget * item, gpointer data) static
Handler for the "activate" event of a menu item.
Parameters
[in] item menu item triggering the event
[in] data index in the directory
Referenced by dir_menu_popup_create().
Variable Documentation
autostart_diskimage
const char* autostart_diskimage static
Disk image being used.
!
Todo:
FIXME: Somehow pass this via the event handlers
Referenced by dir_menu_popup_create(), and on_item_activate().
content_func
read_contents_func_type content_func static
Function to read the contents of an image.
!
Todo:
FIXME: Hiding the pointer-ness of a function is NOT a good idea
Referenced by dir_menu_popup_create().
menuitem_css_provider
GtkCssProvider* menuitem_css_provider static
CSS provider used for directory entry GtkMenuItem's.
Referenced by create_css_providers(), and dir_item_apply_style().
menulabel_css_provider
GtkCssProvider* menulabel_css_provider static
CSS provider used for directory entry GtkMenuItem labels.
Referenced by create_css_providers(), and dir_item_apply_style().
response_func
void(* response_func) (const char *, int, int, unsigned int) (const char * , int , int , unsigned int) static
Function to call when a file in the directory is selected.
Referenced by dir_menu_popup_create(), and on_item_activate().