x128: fsdevice/fsdevice-open.c File Reference
fsdevice-open.c File Reference
File system device.
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "cbmdos.h"
#include "charset.h"
#include "fileio.h"
#include "fsdevice-filename.h"
#include "fsdevice-read.h"
#include "fsdevice-resources.h"
#include "fsdevice-write.h"
#include "fsdevicetypes.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "tape.h"
#include "vdrive-command.h"
#include "vdrive.h"
#include "util.h"
#include "fsdevice-open.h"
Macros
#define DBG(x)
Functions
static uint8_t * makeshortheader (uint8_t *p)
shorten the path shown in the disk header to 16 characters
static int fsdevice_open_directory (vdrive_t *vdrive, unsigned int secondary, bufinfo_t *bufinfo, cbmdos_cmd_parse_t *cmd_parse, char *rname)
static int fsdevice_open_file (vdrive_t *vdrive, unsigned int secondary, bufinfo_t *bufinfo, cbmdos_cmd_parse_t *cmd_parse, char *rname)
static int fsdevice_open_buffer (vdrive_t *vdrive, unsigned int secondary, bufinfo_t *bufinfo, cbmdos_cmd_parse_t *cmd_parse, char *rname)
int fsdevice_open (vdrive_t *vdrive, const uint8_t *name, unsigned int length, unsigned int secondary, cbmdos_cmd_parse_t *cmd_parse_ext)
Detailed Description
File system device.
Author
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Teemu Rantanen tvr@c.nosp@m.s.hu.nosp@m.t.fi
Jarkko Sonninen sonni.nosp@m.nen@.nosp@m.lut.f.nosp@m.i
Jouko Valta jopi@.nosp@m.stek.nosp@m.t.oul.nosp@m.u.fi
Olaf Seibert rhial.nosp@m.to@m.nosp@m.bfys..nosp@m.kun..nosp@m.nl
Andre Fachat a.fac.nosp@m.hat@.nosp@m.physi.nosp@m.k.tu.nosp@m.-chem.nosp@m.nitz.nosp@m..de
Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it
pottendo potte.nosp@m.ndo@.nosp@m.gmx.n.nosp@m.et
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
fsdevice_open()
int fsdevice_open (vdrive_t * vdrive, const uint8_t * name, unsigned int length, unsigned int secondary, cbmdos_cmd_parse_t * cmd_parse_ext)
Referenced by fsdevice_attach().
fsdevice_open_buffer()
static int fsdevice_open_buffer (vdrive_t * vdrive, unsigned int secondary, bufinfo_t * bufinfo, cbmdos_cmd_parse_t * cmd_parse, char * rname) static
Referenced by fsdevice_open().
fsdevice_open_directory()
static int fsdevice_open_directory (vdrive_t * vdrive, unsigned int secondary, bufinfo_t * bufinfo, cbmdos_cmd_parse_t * cmd_parse, char * rname) static
Referenced by fsdevice_open().
fsdevice_open_file()
static int fsdevice_open_file (vdrive_t * vdrive, unsigned int secondary, bufinfo_t * bufinfo, cbmdos_cmd_parse_t * cmd_parse, char * rname) static
Todo:
maybe rename to a backup name
< Overwrites existing file, if any
< Overwrites existing file, if any
< Will not overwrite existing file
< directory separator as a string
< directory separator as a string
Referenced by fsdevice_open().
makeshortheader()
static uint8_t * makeshortheader (uint8_t * p) static
shorten the path shown in the disk header to 16 characters
Todo:
FIXME: use macro
Referenced by fsdevice_open_directory().