x128: c128/cart/warpspeed128.c File Reference
warpspeed128.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cartridge.h"
#include "cartio.h"
#include "util.h"
#include "c64cart.h"
#include "export.h"
#include "c128cart.h"
#include "functionrom.h"
#include "crt.h"
#include "warpspeed128.h"
Macros
#define DBG(x)
#define WARPSPEED_ROM_SIZE 0x4000
#define SNAP_MAJOR 0
#define SNAP_MINOR 1
Functions
static uint8_t warpspeed128_io1_peek (uint16_t addr)
some prototypes are needed
static uint8_t warpspeed128_io1_read (uint16_t addr)
static void warpspeed128_io1_store (uint16_t addr, uint8_t value)
static uint8_t warpspeed128_io2_read (uint16_t addr)
static uint8_t warpspeed128_io2_peek (uint16_t addr)
static void warpspeed128_io2_store (uint16_t addr, uint8_t value)
static int warpspeed128_dump (void)
void warpspeed128_config_setup (uint8_t *rawcart)
static int warpspeed128_common_attach (void)
int warpspeed128_bin_attach (const char *filename, uint8_t *rawcart)
int warpspeed128_crt_attach (FILE *fd, uint8_t *rawcart)
void warpspeed128_detach (void)
void warpspeed128_reset (void)
int warpspeed128_snapshot_write_module (snapshot_t *s)
int warpspeed128_snapshot_read_module (snapshot_t *s)
Variables
static io_source_t warpspeed128_io1_device
static io_source_t warpspeed128_io2_device
static io_source_list_t * warpspeed128_io1_list_item = NULL
static io_source_list_t * warpspeed128_io2_list_item = NULL
static const export_resource_t export_res
static char snap_module_name [] = "WARPSPEED128"
Macro Definition Documentation
DBG
#define DBG (x)
SNAP_MAJOR
#define SNAP_MAJOR 0
SNAP_MINOR
#define SNAP_MINOR 1
WARPSPEED_ROM_SIZE
#define WARPSPEED_ROM_SIZE 0x4000
Function Documentation
warpspeed128_bin_attach()
int warpspeed128_bin_attach (const char * filename, uint8_t * rawcart)
Referenced by c128cartridge_bin_attach().
warpspeed128_common_attach()
static int warpspeed128_common_attach (void) static
Referenced by warpspeed128_bin_attach(), warpspeed128_crt_attach(), and warpspeed128_snapshot_read_module().
warpspeed128_config_setup()
void warpspeed128_config_setup (uint8_t * rawcart)
Referenced by c128cartridge_config_setup().
warpspeed128_crt_attach()
int warpspeed128_crt_attach (FILE * fd, uint8_t * rawcart)
Referenced by c128cartridge_attach_crt().
warpspeed128_detach()
void warpspeed128_detach (void)
Referenced by c128cartridge_detach_image().
warpspeed128_dump()
static int warpspeed128_dump (void) static
warpspeed128_io1_peek()
static uint8_t warpspeed128_io1_peek (uint16_t addr) static
some prototypes are needed
warpspeed128_io1_read()
static uint8_t warpspeed128_io1_read (uint16_t addr) static
warpspeed128_io1_store()
static void warpspeed128_io1_store (uint16_t addr, uint8_t value) static
warpspeed128_io2_peek()
static uint8_t warpspeed128_io2_peek (uint16_t addr) static
warpspeed128_io2_read()
static uint8_t warpspeed128_io2_read (uint16_t addr) static
warpspeed128_io2_store()
static void warpspeed128_io2_store (uint16_t addr, uint8_t value) static
warpspeed128_reset()
void warpspeed128_reset (void)
Referenced by c128cartridge_reset().
warpspeed128_snapshot_read_module()
int warpspeed128_snapshot_read_module (snapshot_t * s)
Referenced by c128cartridge_snapshot_read().
warpspeed128_snapshot_write_module()
int warpspeed128_snapshot_write_module (snapshot_t * s)
Referenced by c128cartridge_snapshot_write().
Variable Documentation
export_res
const export_resource_t export_res static
Initial value:
= {
     "Warp Speed 128" , 1, 1, &warpspeed128_io1_device, &warpspeed128_io2_device, ((  1  ) +  ( 79   + 1) )
}
Referenced by warpspeed128_common_attach(), and warpspeed128_detach().
snap_module_name
char snap_module_name[] = "WARPSPEED128" static
Referenced by warpspeed128_snapshot_read_module(), and warpspeed128_snapshot_write_module().
warpspeed128_io1_device
io_source_t warpspeed128_io1_device static
Initial value:
= {
     "Warp Speed 128" ,
     0 ,
     NULL ,
    0xde00, 0xdeff, 0xff,
    1,
    warpspeed128_io1_store,
    NULL,
    warpspeed128_io1_read,
    warpspeed128_io1_peek,
    warpspeed128_dump,
     1 ,
     0  ,
    0,
     0
}
Referenced by warpspeed128_common_attach().
warpspeed128_io1_list_item
io_source_list_t* warpspeed128_io1_list_item = NULL static
Referenced by warpspeed128_common_attach(), and warpspeed128_detach().
warpspeed128_io2_device
io_source_t warpspeed128_io2_device static
Initial value:
= {
     "Warp Speed 128" ,
     0 ,
     NULL ,
    0xdf00, 0xdfff, 0xff,
    1,
    warpspeed128_io2_store,
    NULL,
    warpspeed128_io2_read,
    warpspeed128_io2_peek,
    warpspeed128_dump,
    ((  1  ) +  ( 79   + 1) ) ,
     0  ,
    0,
     0
}
Referenced by warpspeed128_common_attach().
warpspeed128_io2_list_item
io_source_list_t* warpspeed128_io2_list_item = NULL static
Referenced by warpspeed128_common_attach(), and warpspeed128_detach().