x128: vdc/vdc-mem.c File Reference
vdc-mem.c File Reference
#include "vice.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "monitor.h"
#include "types.h"
#include "vdc-mem.h"
#include "vdc.h"
#include "vdctypes.h"
#include "vdc-draw.h"
#include "videoarch.h"
#include "vdc-resources.h"
Functions
static void vdc_write_data (void)
static void vdc_perform_fillcopy (void)
static void vdc_calculate_charwidth (void)
(re)calculate the width of each vdc character in pixels
void vdc_store (uint16_t addr, uint8_t value)
VDC interface functions.
uint8_t vdc_read (uint16_t addr)
uint8_t vdc_peek (uint16_t addr)
static uint16_t vdc_16k_to_64k_map (uint16_t address)
address translation function for a 16KB VDC in 64KB mode, used by read/write functions below
static uint16_t vdc_64k_to_16k_map (uint16_t address)
address translation function for a 64KB VDC in 16KB mode, used by read/write functions below
uint8_t vdc_ram_read (uint16_t addr)
void vdc_ram_store (uint16_t addr, uint8_t value)
int vdc_dump (void)
Variables
static CLOCK vdc_status_clear_clock = 0
static const uint8_t regmask [38]
bitmask to set the unused bits in returned register values
Function Documentation
vdc_16k_to_64k_map()
static uint16_t vdc_16k_to_64k_map (uint16_t address) static
address translation function for a 16KB VDC in 64KB mode, used by read/write functions below
Referenced by vdc_ram_read(), and vdc_ram_store().
vdc_64k_to_16k_map()
static uint16_t vdc_64k_to_16k_map (uint16_t address) static
address translation function for a 64KB VDC in 16KB mode, used by read/write functions below
Referenced by vdc_ram_read(), and vdc_ram_store().
vdc_calculate_charwidth()
static void vdc_calculate_charwidth (void) static
(re)calculate the width of each vdc character in pixels
Referenced by vdc_store().
vdc_dump()
int vdc_dump (void)
vdc_peek()
uint8_t vdc_peek (uint16_t addr)
vdc_perform_fillcopy()
static void vdc_perform_fillcopy (void) static
Referenced by vdc_store().
vdc_ram_read()
uint8_t vdc_ram_read (uint16_t addr)
Referenced by draw_std_bitmap(), draw_std_text(), mem_bank_read(), mem_read_screen(), vdc_peek(), vdc_perform_fillcopy(), vdc_raster_draw_alarm_handler(), and vdc_read().
vdc_ram_store()
void vdc_ram_store (uint16_t addr, uint8_t value)
Referenced by mem_bank_write(), vdc_perform_fillcopy(), and vdc_write_data().
vdc_read()
uint8_t vdc_read (uint16_t addr)
Referenced by vdc_peek(), and z80_vdc_read().
vdc_store()
void vdc_store (uint16_t addr, uint8_t value)
VDC interface functions.
Store a value in a VDC register.
< 8563 R7A
Referenced by z80_vdc_store().
vdc_write_data()
static void vdc_write_data (void) static
Referenced by vdc_store().
Variable Documentation
regmask
const uint8_t regmask[38] static
Initial value:
= {
    0x00, 0x00, 0x00, 0x00, 0x00, 0xE0, 0x00, 0x00,
    0xFC, 0xE0, 0x80, 0xE0, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xE0,
    0x00, 0x00, 0x00, 0x00, 0x0f, 0xE0, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0xF0, 0x3F
}
bitmask to set the unused bits in returned register values
Referenced by vdc_dump(), and vdc_read().
vdc_status_clear_clock
CLOCK vdc_status_clear_clock = 0 static
Referenced by vdc_dump(), vdc_perform_fillcopy(), vdc_read(), and vdc_store().