x128: gcr.c File Reference
gcr.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "gcr.h"
#include "lib.h"
#include "log.h"
#include "types.h"
#include "cbmdos.h"
#include "diskimage.h"
Macros
#define DBG(_x_)
Functions
static void gcr_convert_4bytes_to_GCR (const uint8_t *source, uint8_t *dest)
static void gcr_convert_GCR_to_4bytes (const uint8_t *source, uint8_t *dest)
void gcr_convert_sector_to_GCR (const uint8_t *buffer, uint8_t *data, const gcr_header_t *header, int gap, int sync, fdc_err_t error_code)
static int gcr_find_sync (const disk_track_t *raw, int p, int s)
static void gcr_decode_block (const disk_track_t *raw, int p, uint8_t *buf, int num)
static int gcr_find_sector_header (const disk_track_t *raw, uint8_t sector)
fdc_err_t gcr_read_sector (const disk_track_t *raw, uint8_t *data, uint8_t sector)
fdc_err_t gcr_write_sector (disk_track_t *raw, const uint8_t *data, uint8_t sector)
gcr_t * gcr_create_image (void)
void gcr_destroy_image (gcr_t *gcr)
Variables
static const uint8_t GCR_conv_data [16]
static const uint8_t From_GCR_conv_data [32]
Macro Definition Documentation
DBG
#define DBG (_x_)
Function Documentation
gcr_convert_4bytes_to_GCR()
static void gcr_convert_4bytes_to_GCR (const uint8_t * source, uint8_t * dest) static
Referenced by gcr_convert_sector_to_GCR(), and gcr_write_sector().
gcr_convert_GCR_to_4bytes()
static void gcr_convert_GCR_to_4bytes (const uint8_t * source, uint8_t * dest) static
Referenced by gcr_decode_block().
gcr_convert_sector_to_GCR()
void gcr_convert_sector_to_GCR (const uint8_t * buffer, uint8_t * data, const gcr_header_t * header, int gap, int sync, fdc_err_t error_code)
Referenced by fsimage_create_gcr(), fsimage_create_p64(), and fsimage_read_dxx_image().
gcr_create_image()
gcr_t * gcr_create_image (void)
Referenced by drive_init().
gcr_decode_block()
static void gcr_decode_block (const disk_track_t * raw, int p, uint8_t * buf, int num) static
Referenced by gcr_find_sector_header(), and gcr_read_sector().
gcr_destroy_image()
void gcr_destroy_image (gcr_t * gcr)
Referenced by drive_shutdown().
gcr_find_sector_header()
static int gcr_find_sector_header (const disk_track_t * raw, uint8_t sector) static
Referenced by gcr_read_sector(), and gcr_write_sector().
gcr_find_sync()
static int gcr_find_sync (const disk_track_t * raw, int p, int s) static
Referenced by gcr_find_sector_header(), gcr_read_sector(), and gcr_write_sector().
gcr_read_sector()
fdc_err_t gcr_read_sector (const disk_track_t * raw, uint8_t * data, uint8_t sector)
Referenced by fsimage_dxx_read_sector(), fsimage_dxx_write_half_track(), fsimage_gcr_read_sector(), and fsimage_p64_read_sector().
gcr_write_sector()
fdc_err_t gcr_write_sector (disk_track_t * raw, const uint8_t * data, uint8_t sector)
Referenced by fsimage_dxx_write_sector(), fsimage_gcr_write_sector(), and fsimage_p64_write_sector().
Variable Documentation
From_GCR_conv_data
const uint8_t From_GCR_conv_data[32] static
Initial value:
=
{
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 8, 0, 1, 0, 12, 4, 5,
    0, 0, 2, 3, 0, 15, 6, 7,
    0, 9, 10, 11, 0, 13, 14, 0
}
Referenced by gcr_convert_GCR_to_4bytes().
GCR_conv_data
const uint8_t GCR_conv_data[16] static
Initial value:
=
{
    0x0a, 0x0b, 0x12, 0x13,
    0x0e, 0x0f, 0x16, 0x17,
    0x09, 0x19, 0x1a, 0x1b,
    0x0d, 0x1d, 0x1e, 0x15
}
Referenced by gcr_convert_4bytes_to_GCR().