vsid: arch/gtk3/uisnapshot.h File Reference
uisnapshot.h File Reference
Snapshot dialogs and menu item handlers - header.
#include "vice.h"
#include <gtk/gtk.h>
Functions
void ui_snapshot_load_snapshot (void)
Display UI to load a snapshot file.
void ui_snapshot_save_snapshot (void)
Display UI to save a snapshot file.
void ui_snapshot_quickload_snapshot (void)
Quicksave snapshot.
void ui_snapshot_quicksave_snapshot (void)
Quicksave snapshot.
Detailed Description
Snapshot dialogs and menu item handlers - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
ui_snapshot_load_snapshot()
void ui_snapshot_load_snapshot (void)
Display UI to load a snapshot file.
Referenced by snapshot_load_action().
ui_snapshot_quickload_snapshot()
void ui_snapshot_quickload_snapshot (void)
Quicksave snapshot.
Referenced by snapshot_quickload_action().
ui_snapshot_quicksave_snapshot()
void ui_snapshot_quicksave_snapshot (void)
Quicksave snapshot.
Referenced by snapshot_quicksave_action().
ui_snapshot_save_snapshot()
void ui_snapshot_save_snapshot (void)
Display UI to save a snapshot file.
Referenced by snapshot_save_action().