vsid: monitor/mon_register.c File Reference
mon_register.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "lib.h"
#include "log.h"
#include "mon_register.h"
#include "mon_util.h"
#include "montypes.h"
Macros
#define DBG(_x_)
Functions
int mon_register_valid (int mem, int reg_id)
check if register id is valid, returns 1 on valid, 0 on invalid
int mon_register_name_to_id (int mem, char *name)
takes a register by name, and returns its id.
int mon_register_name_valid (int mem, char *name)
checks if a given string is a valid register name, returns 1 on valid, 0 on invalid
int mon_register_id_to_value (int mem, int reg_id)
takes a register by id, and returns its value.
int mon_register_name_to_value (int mem, char *name)
takes a register by name, and returns its value.
Macro Definition Documentation
DBG
#define DBG (_x_)
Function Documentation
mon_register_id_to_value()
int mon_register_id_to_value (int mem, int reg_id)
takes a register by id, and returns its value.
returns -1 on error
Referenced by mon_register_name_to_value().
mon_register_name_to_id()
int mon_register_name_to_id (int mem, char * name)
takes a register by name, and returns its id.
returns -1 on error
Referenced by mon_register_name_to_value(), and mon_register_name_valid().
mon_register_name_to_value()
int mon_register_name_to_value (int mem, char * name)
takes a register by name, and returns its value.
returns -1 on error
Referenced by mon_symbol_table_lookup_addr().
mon_register_name_valid()
int mon_register_name_valid (int mem, char * name)
checks if a given string is a valid register name, returns 1 on valid, 0 on invalid
Referenced by mon_add_name_to_symbol_table(), and mon_symbol_table_lookup_addr().
mon_register_valid()
int mon_register_valid (int mem, int reg_id)
check if register id is valid, returns 1 on valid, 0 on invalid
common functions
Referenced by mon_register_id_to_value(), and monitor_binary_process_registers_set().