x128: drive/iec/iecrom.c File Reference
iecrom.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "drive.h"
#include "driverom.h"
#include "drivetypes.h"
#include "iecrom.h"
#include "log.h"
#include "resources.h"
#include "sysfile.h"
Macros
#define DRIVE_ROM1541_CHECKSUM 1991711
Functions
static int iecrom_do_1541_checksum (void)
int iecrom_load_1540 (void)
int iecrom_load_1541 (void)
int iecrom_load_1541ii (void)
int iecrom_load_1570 (void)
int iecrom_load_1571 (void)
int iecrom_load_1581 (void)
int iecrom_load_2000 (void)
int iecrom_load_4000 (void)
int iecrom_load_CMDHD (void)
void iecrom_setup_image (diskunit_context_t *unit)
int iecrom_check_loaded (unsigned int type)
void iecrom_do_checksum (diskunit_context_t *unit)
void iecrom_init (void)
Variables
static log_t iecrom_log
NOTE: 1571CR is handled in iec128dcr/iec128dcrrom.c.
static uint8_t drive_rom1540 [0x8000]
static uint8_t drive_rom1541 [0x8000]
static uint8_t drive_rom1541ii [0x8000]
static uint8_t drive_rom1570 [0x8000]
static uint8_t drive_rom1571 [0x8000]
static uint8_t drive_rom1581 [0x8000]
static uint8_t drive_rom2000 [0x8000]
static uint8_t drive_rom4000 [0x8000]
static uint8_t drive_romCMDHD [0x4000]
static unsigned int rom1540_loaded = 0
If nonzero, the ROM image has been loaded.
static unsigned int rom1541_loaded = 0
static unsigned int rom1541ii_loaded = 0
static unsigned int rom1570_loaded = 0
static unsigned int rom1571_loaded = 0
static unsigned int rom1581_loaded = 0
static unsigned int rom2000_loaded = 0
static unsigned int rom4000_loaded = 0
static unsigned int romCMDHD_loaded = 0
static unsigned int drive_rom1540_size
static unsigned int drive_rom1541_size
static unsigned int drive_rom1541ii_size
Macro Definition Documentation
DRIVE_ROM1541_CHECKSUM
#define DRIVE_ROM1541_CHECKSUM 1991711
Function Documentation
iecrom_check_loaded()
int iecrom_check_loaded (unsigned int type)
< ASCII for HD
Referenced by iec_drive_rom_check_loaded().
iecrom_do_1541_checksum()
static int iecrom_do_1541_checksum (void) static
Referenced by iecrom_do_checksum().
iecrom_do_checksum()
void iecrom_do_checksum (diskunit_context_t * unit)
Referenced by iec_drive_rom_do_checksum().
iecrom_init()
void iecrom_init (void)
Referenced by iec_drive_init().
iecrom_load_1540()
int iecrom_load_1540 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1540().
iecrom_load_1541()
int iecrom_load_1541 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1541().
iecrom_load_1541ii()
int iecrom_load_1541ii (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1541ii().
iecrom_load_1570()
int iecrom_load_1570 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1570().
iecrom_load_1571()
int iecrom_load_1571 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1571().
iecrom_load_1581()
int iecrom_load_1581 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_1581().
iecrom_load_2000()
int iecrom_load_2000 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_2000().
iecrom_load_4000()
int iecrom_load_4000 (void)
Referenced by iec_drive_rom_load(), and set_dos_rom_name_4000().
iecrom_load_CMDHD()
int iecrom_load_CMDHD (void)
< ASCII for HD
Referenced by iec_drive_rom_load(), and set_dos_rom_name_CMDHD().
iecrom_setup_image()
void iecrom_setup_image (diskunit_context_t * unit)
< ASCII for HD
Referenced by iec_drive_rom_setup_image().
Variable Documentation
drive_rom1540
uint8_t drive_rom1540[0x8000] static
Referenced by iecrom_load_1540(), and iecrom_setup_image().
drive_rom1540_size
unsigned int drive_rom1540_size static
Referenced by iecrom_load_1540(), and iecrom_setup_image().
drive_rom1541
uint8_t drive_rom1541[0x8000] static
Referenced by iecrom_do_1541_checksum(), iecrom_load_1541(), and iecrom_setup_image().
drive_rom1541_size
unsigned int drive_rom1541_size static
Referenced by iecrom_do_1541_checksum(), iecrom_load_1541(), and iecrom_setup_image().
drive_rom1541ii
uint8_t drive_rom1541ii[0x8000] static
Referenced by iecrom_load_1541ii(), and iecrom_setup_image().
drive_rom1541ii_size
unsigned int drive_rom1541ii_size static
Referenced by iecrom_load_1541ii(), and iecrom_setup_image().
drive_rom1570
uint8_t drive_rom1570[0x8000] static
Referenced by iecrom_load_1570(), and iecrom_setup_image().
drive_rom1571
uint8_t drive_rom1571[0x8000] static
Referenced by iecrom_load_1571(), and iecrom_setup_image().
drive_rom1581
uint8_t drive_rom1581[0x8000] static
Referenced by iecrom_load_1581(), and iecrom_setup_image().
drive_rom2000
uint8_t drive_rom2000[0x8000] static
Referenced by iecrom_load_2000(), and iecrom_setup_image().
drive_rom4000
uint8_t drive_rom4000[0x8000] static
Referenced by iecrom_load_4000(), and iecrom_setup_image().
drive_romCMDHD
uint8_t drive_romCMDHD[0x4000] static
Referenced by iecrom_load_CMDHD(), and iecrom_setup_image().
iecrom_log
log_t iecrom_log static
NOTE: 1571CR is handled in iec128dcr/iec128dcrrom.c.
Logging goes here.
Referenced by iecrom_do_1541_checksum(), and iecrom_init().
rom1540_loaded
unsigned int rom1540_loaded = 0 static
If nonzero, the ROM image has been loaded.
Referenced by iecrom_check_loaded(), and iecrom_load_1540().
rom1541_loaded
unsigned int rom1541_loaded = 0 static
Referenced by iecrom_check_loaded(), and iecrom_load_1541().
rom1541ii_loaded
unsigned int rom1541ii_loaded = 0 static
Referenced by iecrom_check_loaded(), and iecrom_load_1541ii().
rom1570_loaded
unsigned int rom1570_loaded = 0 static
Referenced by iecrom_check_loaded(), and iecrom_load_1570().
rom1571_loaded
unsigned int rom1571_loaded = 0 static
Referenced by iecrom_check_loaded(), and iecrom_load_1571().
rom1581_loaded
unsigned int rom1581_loaded = 0 static
Referenced by iecrom_check_loaded(), and iecrom_load_1581().
rom2000_loaded
unsigned int rom2000_loaded = 0 static
Referenced by iecrom_check_loaded(), and iecrom_load_2000().
rom4000_loaded
unsigned int rom4000_loaded = 0 static
Referenced by iecrom_check_loaded(), and iecrom_load_4000().
romCMDHD_loaded
unsigned int romCMDHD_loaded = 0 static
Referenced by iecrom_check_loaded(), and iecrom_load_CMDHD().