vsid: vicii/vicii-phi1.c File Reference
vicii-phi1.c File Reference
#include "vice.h"
#include "maincpu.h"
#include "types.h"
#include "vicii-phi1.h"
#include "viciitypes.h"
Functions
static uint8_t gfx_data_illegal_bitmap (unsigned int num)
static uint8_t gfx_data_hires_bitmap (unsigned int num)
static uint8_t gfx_data_extended_text (unsigned int num)
static uint8_t gfx_data_normal_text (unsigned int num)
static uint8_t gfx_data (unsigned int num)
static uint8_t idle_gap (void)
static uint8_t sprite_data (unsigned int num)
static uint8_t sprite_pointer (unsigned int num)
static uint8_t refresh_counter (unsigned int num)
static uint8_t phi1_pal (unsigned int cycle)
static uint8_t phi1_ntsc_old (unsigned int cycle)
static uint8_t phi1_ntsc (unsigned int cycle)
uint8_t vicii_read_phi1_lowlevel (void)
uint8_t vicii_read_phi1 (void)
Function Documentation
gfx_data()
static uint8_t gfx_data (unsigned int num) static
Referenced by phi1_ntsc(), phi1_ntsc_old(), and phi1_pal().
gfx_data_extended_text()
static uint8_t gfx_data_extended_text (unsigned int num) inline static
Referenced by gfx_data().
gfx_data_hires_bitmap()
static uint8_t gfx_data_hires_bitmap (unsigned int num) inline static
Referenced by gfx_data().
gfx_data_illegal_bitmap()
static uint8_t gfx_data_illegal_bitmap (unsigned int num) inline static
Referenced by gfx_data().
gfx_data_normal_text()
static uint8_t gfx_data_normal_text (unsigned int num) inline static
Referenced by gfx_data().
idle_gap()
static uint8_t idle_gap (void) static
Referenced by phi1_ntsc(), phi1_ntsc_old(), and phi1_pal().
phi1_ntsc()
static uint8_t phi1_ntsc (unsigned int cycle) inline static
Referenced by vicii_read_phi1_lowlevel().
phi1_ntsc_old()
static uint8_t phi1_ntsc_old (unsigned int cycle) inline static
Referenced by vicii_read_phi1_lowlevel().
phi1_pal()
static uint8_t phi1_pal (unsigned int cycle) inline static
Referenced by vicii_read_phi1_lowlevel().
refresh_counter()
static uint8_t refresh_counter (unsigned int num) static
Referenced by phi1_ntsc(), phi1_ntsc_old(), and phi1_pal().
sprite_data()
static uint8_t sprite_data (unsigned int num) static
Referenced by phi1_ntsc(), phi1_ntsc_old(), and phi1_pal().
sprite_pointer()
static uint8_t sprite_pointer (unsigned int num) static
Referenced by phi1_ntsc(), phi1_ntsc_old(), and phi1_pal().
vicii_read_phi1()
uint8_t vicii_read_phi1 (void)
Referenced by colorram_read(), io_peek(), io_read(), void_read(), vsid_io_read(), and zero_store().
vicii_read_phi1_lowlevel()
uint8_t vicii_read_phi1_lowlevel (void)
Referenced by vicii_read_phi1(), and zero_store().