x128: fileio/p00.h File Reference
p00.h File Reference
#include <stdio.h>
#include "types.h"
Functions
struct fileio_info_s * p00_open (const char *file_name, const char *path, unsigned int command, unsigned int type, int *reclenp)
void p00_close (struct fileio_info_s *info)
unsigned int p00_read (struct fileio_info_s *info, uint8_t *buf, unsigned int len)
unsigned int p00_write (struct fileio_info_s *info, uint8_t *buf, unsigned int len)
unsigned int p00_ferror (struct fileio_info_s *info)
unsigned int p00_rename (const char *src_name, const char *dest_name, const char *path)
unsigned int p00_scratch (const char *file_name, const char *path)
unsigned int p00_get_bytes_left (struct fileio_info_s *info)
unsigned int p00_seek (struct fileio_info_s *info, off_t offset, int whence)
unsigned int p00_tell (struct fileio_info_s *info)
char * p00_filename_create (const char *filename, unsigned int type)
Function Documentation
p00_close()
void p00_close (struct fileio_info_s * info)
Referenced by fileio_close().
p00_ferror()
unsigned int p00_ferror (struct fileio_info_s * info)
Referenced by fileio_ferror().
p00_filename_create()
char * p00_filename_create (const char * filename, unsigned int type)
< should match CBMDOS_FT_xxx
Referenced by extract_cmd_common(), and p00_file_create().
p00_get_bytes_left()
unsigned int p00_get_bytes_left (struct fileio_info_s * info)
Referenced by fileio_get_bytes_left().
p00_open()
struct fileio_info_s * p00_open (const char * file_name, const char * path, unsigned int command, unsigned int type, int * reclenp)
< works with directories
< Will not overwrite existing file
< Overwrites existing file, if any
< Will not overwrite existing file
< works with directories
< Will not overwrite existing file
< Overwrites existing file, if any
Referenced by fileio_open().
p00_read()
unsigned int p00_read (struct fileio_info_s * info, uint8_t * buf, unsigned int len)
Referenced by fileio_read().
p00_rename()
unsigned int p00_rename (const char * src_name, const char * dest_name, const char * path)
Referenced by fileio_rename().
p00_scratch()
unsigned int p00_scratch (const char * file_name, const char * path)
Referenced by fileio_scratch().
p00_seek()
unsigned int p00_seek (struct fileio_info_s * info, off_t offset, int whence)
Referenced by fileio_seek().
p00_tell()
unsigned int p00_tell (struct fileio_info_s * info)
Referenced by fileio_tell().
p00_write()
unsigned int p00_write (struct fileio_info_s * info, uint8_t * buf, unsigned int len)
Referenced by fileio_write().