vsid: arch/gtk3/widgets/driveramwidget.h File Reference
driveramwidget.h File Reference
Drive RAM expansions widget - header.
#include <gtk/gtk.h>
Functions
GtkWidget * drive_ram_widget_create (int unit)
Create extra drive RAM expansions widget.
void drive_ram_widget_update (GtkWidget *widget, int model)
Update sensitivity of check buttons based on drive model.
Detailed Description
Drive RAM expansions widget - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
drive_ram_widget_create()
GtkWidget * drive_ram_widget_create (int unit)
Create extra drive RAM expansions widget.
Create a group of check buttons to enable/disable RAM expansions in a drive.
The check buttons that can be toggled is dependent on the drive type, see drive_ram_widget_update().
Parameters
[in] unit drive unit (8-11)
Returns
GtkGrid
Referenced by create_c64_layout(), create_plus4_layout(), and create_vic20_layout().
drive_ram_widget_update()
void drive_ram_widget_update (GtkWidget * widget, int model)
Update sensitivity of check buttons based on drive model.
Parameters
[in] widget drive RAM expansions widget
[in] model drive model ID
Referenced by drive_ram_widget_create(), and on_model_changed().