x128: vicii/vicii-badline.c File Reference
vicii-badline.c File Reference
#include "vice.h"
#include "dma.h"
#include "maincpu.h"
#include "raster-changes.h"
#include "types.h"
#include "vicii-badline.h"
#include "vicii-fetch.h"
#include "viciitypes.h"
Functions
static void switch_to_display_state (const int cycle)
static void line_becomes_good (const int cycle)
static void line_becomes_bad (const int cycle)
void vicii_badline_check_state (uint8_t value, const int cycle, const unsigned int line, const int old_allow_bad_lines)
Function Documentation
line_becomes_bad()
static void line_becomes_bad (const int cycle) inline static
Referenced by vicii_badline_check_state().
line_becomes_good()
static void line_becomes_good (const int cycle) inline static
Referenced by vicii_badline_check_state().
switch_to_display_state()
static void switch_to_display_state (const int cycle) inline static
Referenced by line_becomes_bad(), and line_becomes_good().
vicii_badline_check_state()
void vicii_badline_check_state (uint8_t value, const int cycle, const unsigned int line, const int old_allow_bad_lines)
Referenced by d011_store().