vsid: c64/reloc65.c File Reference
reloc65.c File Reference
#include <stdio.h>
#include <string.h>
#include "psid.h"
Data Structures
struct file65
Macros
#define BUF (9 * 2 + 8)
16 bit header
#define reldiff(s) (((s) == 2) ? fp->tdiff : (((s) == 3) ? fp->ddiff : (((s) == 4) ? fp->bdiff : (((s) == 5) ? fp->zdiff : 0))))
Functions
static int read_options (unsigned char *f)
static int read_undef (unsigned char *f)
static unsigned char * reloc_seg (unsigned char *f, int len, unsigned char *rtab, file65 *fp)
static unsigned char * reloc_globals (unsigned char *, file65 *fp)
int reloc65 (char **buf, int *fsize, int addr)
Variables
static file65 file
static const unsigned char cmp [] = {1, 0, 'o', '6', '5'}
Macro Definition Documentation
BUF
#define BUF (9 * 2 + 8)
16 bit header
reldiff
#define reldiff (s) (((s) == 2) ? fp->tdiff : (((s) == 3) ? fp->ddiff : (((s) == 4) ? fp->bdiff : (((s) == 5) ? fp->zdiff : 0))))
Function Documentation
read_options()
static int read_options (unsigned char * f) static
Referenced by reloc65().
read_undef()
static int read_undef (unsigned char * f) static
Referenced by reloc65().
reloc65()
int reloc65 (char ** buf, int * fsize, int addr)
< 16 bit header
< 16 bit header
Referenced by psid_init_driver().
reloc_globals()
static unsigned char * reloc_globals (unsigned char * buf, file65 * fp) static
Referenced by reloc65().
reloc_seg()
static unsigned char * reloc_seg (unsigned char * f, int len, unsigned char * rtab, file65 * fp) static
Referenced by reloc65().
Variable Documentation
cmp
const unsigned char cmp[] = {1, 0, 'o', '6', '5'} static
Referenced by reloc65().
file
file65 file static
Referenced by autostart_prg_with_virtual_fs(), create_combo_box(), on_update_preview(), palette_find_name(), reloc65(), util_check_filename_access(), vdrive_command_copy(), and vdrive_command_rmdir().