vsid: arch/gtk3/widgets/base/resourcenumericstring.c File Reference
resourcenumericstring.c File Reference
Numeric string connected to a resource.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include "resources.h"
#include "resourcewidgetmediator.h"
#include "vice_gtk3.h"
#include "types.h"
#include "resourcenumericstring.h"
Data Structures
struct numstr_unit_s
Object holding unit (suffix, factor) pairs.
struct numstr_info_s
Object holding additional widget info.
Macros
#define CSS_INVALID "entry { color: red; }"
CSS rule for the widget to show the current contents are invalid.
#define CSS_VALID "entry { color: green; }"
CSS rule for the widget to show the current contents are alid.
Typedefs
typedef struct numstr_unit_s numstr_unit_t
Object holding unit (suffix, factor) pairs.
typedef struct numstr_info_s numstr_info_t
Object holding additional widget info.
Functions
static void free_info (void *info)
Free additional data object.
static gboolean value_is_valid (GtkEntry *self, guint64 value)
Check value against limits set on widget.
static gboolean input_is_valid (GtkEntry *self)
Validate input.
static gboolean update_resource_value (GtkEntry *self)
Update resource with text of entry.
static void on_entry_changed (GtkEntry *self, gpointer data)
Event handler for the 'changed' event.
static gboolean on_focus_out_event (GtkEntry *self, GdkEvent *event, gpointer data)
Handler for the "focus-out" event.
static gboolean on_key_press_event (GtkEntry *self, GdkEvent *event, gpointer data)
Handler for the 'on-key-press' event.
GtkWidget * vice_gtk3_resource_numeric_string_new (const char *resource)
Create numeric string entry box for resource.
void vice_gtk3_resource_numeric_string_set_limits (GtkWidget *widget, guint64 minimum, guint64 maximum, gboolean allow_zero)
Set limits on the widget's valid values.
Variables
static const numstr_unit_t units []
List of suffixes and their factors.
static const gint valid_keys []
List of valid keys for the widget.
Detailed Description
Numeric string connected to a resource.
Used for resources that store their numeric value as a string.
Supports using suffixes 'K', 'M', and 'G' for KiB, MiB and GiB respectively. Digits are accepted as well a navigation keys (left, right, home, end, insert, delete) and Tab, Return and Enter to accept input.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
CSS_INVALID
#define CSS_INVALID "entry { color: red; }"
CSS rule for the widget to show the current contents are invalid.
CSS_VALID
#define CSS_VALID "entry { color: green; }"
CSS rule for the widget to show the current contents are alid.
Typedef Documentation
numstr_info_t
typedef struct numstr_info_s numstr_info_t
Object holding additional widget info.
numstr_unit_t
typedef struct numstr_unit_s numstr_unit_t
Object holding unit (suffix, factor) pairs.
Function Documentation
free_info()
static void free_info (void * info) static
Free additional data object.
Called during widget destruction by the mediator.
Parameters
[in] info info object to free
Referenced by vice_gtk3_resource_numeric_string_new().
input_is_valid()
static gboolean input_is_valid (GtkEntry * self) static
Validate input.
Parameters
[in] widget GtkEntry instance
Returns
TRUE if the current text in self is valid
Referenced by on_entry_changed().
on_entry_changed()
static void on_entry_changed (GtkEntry * self, gpointer data) static
Event handler for the 'changed' event.
Gets triggered after accepting/refusing any key input. so we check the input for validity here, and also add a visual hint via CSS.
Parameters
[in,out] self entry widget
[in] data extra event data (unused)
Referenced by vice_gtk3_resource_numeric_string_new().
on_focus_out_event()
static gboolean on_focus_out_event (GtkEntry * self, GdkEvent * event, gpointer data) static
Handler for the "focus-out" event.
Parameters
[in] self entry widget (unused)
[in] event event object (unused)
[in] data extra event data (unused)
Returns
GDK_EVENT_PROPAGATE
Referenced by vice_gtk3_resource_numeric_string_new().
on_key_press_event()
static gboolean on_key_press_event (GtkEntry * self, GdkEvent * event, gpointer data) static
Handler for the 'on-key-press' event.
Filter certain keys from being used in the entry widget.
Parameters
[in] self entry widget
[in] event event object
[in] data unused
Returns
TRUE if Enter was pushed, FALSE otherwise (makes the pushed key propagate to the entry)
Referenced by vice_gtk3_resource_numeric_string_new().
update_resource_value()
static gboolean update_resource_value (GtkEntry * self) static
Update resource with text of entry.
Attempt to update the resource with the text of self, if that fails revert to previous valid resource value.
Parameters
[in] self entry widget
Returns
TRUE on succesfully updating the resource
Referenced by on_focus_out_event(), and on_key_press_event().
value_is_valid()
static gboolean value_is_valid (GtkEntry * self, guint64 value) static
Check value against limits set on widget.
Parameters
[in] widget resource numeric digits widget
[in] value 64-bit unsigned value to check against limits
Returns
value is valid for the given (or missing) limits
Referenced by input_is_valid().
vice_gtk3_resource_numeric_string_new()
GtkWidget * vice_gtk3_resource_numeric_string_new (const char * resource)
Create numeric string entry box for resource.
Create a widget that accepts numeric strings with suffixes (K, M, G).
Parameters
[in] resource resource name
Returns
GtkEntry
Referenced by drive_fixed_size_widget_create().
vice_gtk3_resource_numeric_string_set_limits()
void vice_gtk3_resource_numeric_string_set_limits (GtkWidget * widget, guint64 minimum, guint64 maximum, gboolean allow_zero)
Set limits on the widget's valid values.
These limits are by default set to 0 to UINT64_MAX. The allow_zero argument is meant to allow using 0 to indicate a special case.
Parameters
[in,out] widget resource numeric string widget
[in] minimum minimum value
[in] maximum maximum value
[in] allow_zero allow zero as a special (Nul) value
Referenced by drive_fixed_size_widget_create().
Variable Documentation
units
const numstr_unit_t units[] static
Initial value:
= {
    { 'K',  1<<10 },
    { 'M',  1<<20 },
    { 'G',  1<<30 },
    { -1,   0 }
}
List of suffixes and their factors.
Referenced by input_is_valid().
valid_keys
const gint valid_keys[] static
Initial value:
= {
    GDK_KEY_0, GDK_KEY_1, GDK_KEY_2, GDK_KEY_3, GDK_KEY_4,
    GDK_KEY_5, GDK_KEY_6, GDK_KEY_7, GDK_KEY_8, GDK_KEY_9,
    GDK_KEY_k, GDK_KEY_K,
    GDK_KEY_m, GDK_KEY_M,
    GDK_KEY_g, GDK_KEY_G,
    GDK_KEY_x, GDK_KEY_X,
    GDK_KEY_BackSpace,
    GDK_KEY_Delete,
    GDK_KEY_Insert,
    GDK_KEY_Left,
    GDK_KEY_Right,
    GDK_KEY_Home,
    GDK_KEY_End,
    -1
}
List of valid keys for the widget.
This excludes GKD_Enter since that's used to attempt to set the entry.
Referenced by on_key_press_event().