vsid: opencbmlib.h File Reference
opencbmlib.h File Reference
#include "vice.h"
#include "opencbm.h"
Data Structures
struct opencbmlib_s
Typedefs
typedef int port
typedef const char ** cbm_get_driver_name_t(int port)
< CBMAPIDECL is a dummy on Linux
typedef unsigned char dev
typedef unsigned char unsigned char secadr
typedef unsigned char unsigned char const void * fname
typedef unsigned char unsigned char const void size_t len
typedef void * buf
typedef void size_t size
typedef struct opencbmlib_s opencbmlib_t
Functions
typedef int (*cbm_driver_open_t)(void **f
< The "file descriptor" for an opened driver
typedef void (*cbm_driver_close_t)(void *f)
< The "file descriptor" for an opened driver
int opencbmlib_open (opencbmlib_t *opencbmlib)
void opencbmlib_close (void)
unsigned int opencbmlib_is_available (void)
Typedef Documentation
buf
typedef const void * buf
cbm_get_driver_name_t
typedef const char ** cbm_get_driver_name_t(int port)
< CBMAPIDECL is a dummy on Linux
dev
typedef unsigned char dev
fname
typedef unsigned char unsigned char const void* fname
len
typedef unsigned char unsigned char const void size_t len
opencbmlib_t
typedef struct opencbmlib_s opencbmlib_t
port
typedef int port
secadr
typedef unsigned char unsigned char secadr
size
typedef const void size_t size
Function Documentation
int()
typedef int (* cbm_driver_open_t)
< The "file descriptor" for an opened driver
Parameters
cbm_driver_open_t CBMAPIDECL is a dummy on Linux
Referenced by reSID::ExternalFilter::ExternalFilter(), reSID::Filter::Filter(), reSID::Filter::adjust_filter_bias(), advance_outfile_name(), aifc_handle_comm(), aiff_handle_comm(), aiff_write(), alarm_context_update_next_pending(), alarm_set(), attach_disk_image(), autostart_prg_with_disk_image(), bmpdrv_write(), calculate_baudrate(), cbmdos_command_parse(), cbmdos_command_parse_plus(), cbmfile_open(), charset_petscii_to_screencode_line(), check_sprite_dma(), cia1571_set_timing(), ciat_update(), clipboard_read_screen_output(), reSID::SID::clock_resample(), cmdline_parse(), command_directory_get(), debugcart_store(), dir_menu_popup_create(), disk_image_check_for_d64(), diskcontents_block_read(), dofilter(), drive_led_update(), drive_resources_type(), drive_resources_type_init(), drive_set_machine_parameter(), driverom_load(), entry_get_int(), event_alarm_handler(), event_playback_attach_image(), event_playback_event_list(), event_record_attach_in_list(), event_write_version(), export_dump(), fastsid_state_write(), fdd_flush_raw(), fdd_image_attach(), fdd_update_raw(), file_load_sample(), fill_sprite_cache(), findpath(), flash_write_operation_status(), fliplist_load_list(), fsdevice_error(), fsdevice_open_directory(), fsdevice_relative_switch_record(), fsdrive_write(), godotdrv_write(), handle_control_sequence(), handle_esc_control_sequence(), iec_open_read(), iec_open_read_directory(), iec_read_sequential(), iff_write(), init_tables(), initcmdline_check_args(), interrupt_ack_irq(), interrupt_ack_nmi(), interrupt_set_irq(), interrupt_set_nmi(), is_valid_token_id(), kbd_make_event_timestap(), kbd_queue_popkey(), keyboard_parse_entry(), keyboard_parse_set_neg_row(), log_close(), log_helper(), machine_get_line_cycle(), machine_specific_reset(), main_program(), mon_add_string_to_buffer(), mon_drive_execute_disk_cmd(), mon_evaluate_address_range(), mon_instruction_return(), mon_instructions_next(), mon_out_buffered(), mon_register_list_get6502(), mon_register_list_get6502dtv(), mon_register_list_get65816(), mon_register_list_get6809(), mon_register_list_getR65C02(), mon_register_list_getz80(), mon_tape_offs(), monitor_binary_transmit(), monitor_network_extract_text_command_line(), monitor_network_transmit(), monitor_set_initial_breakpoint(), network_test_delay(), on_custom_item_activate(), on_device_changed(), on_iec_toggled(), on_key_release_event(), on_model_toggled(), on_radio_toggled(), on_scale_int_changed(), on_term_text_modified(), on_virtual_device_toggled(), on_window_configure_event(), reSID::PointPlotter< F >::operator()(), p00_filename_create(), p00_open(), p00_read_header(), pc8477_store(), print_bitmask(), print_cbm_char(), print_help_topics(), psid_load_file(), raster_changes_add_sorted_int(), render_32_1x1_04(), render_32_1x2_interlaced(), render_32_1x2_non_interlaced(), render_32_2x2_interlaced(), render_32_2x2_non_interlaced(), render_32_2x4_interlaced(), render_32_2x4_non_interlaced(), render_generic_1x1_pal(), render_generic_1x2_rgbi(), render_generic_2x2_ntsc(), render_generic_2x2_pal(), render_generic_2x2_pal_u(), render_generic_2x2_rgbi(), render_generic_2x4_rgbi(), resid_calculate_samples(), resource_create_event_data(), resources_calc_hash_key(), resources_init(), resources_read_item_from_file(), resources_register_int(), resources_register_string(), resources_set_value_string(), rotation_1541_gcr(), rotation_1541_simple(), rotation_do_wobble(), rsuser_init(), sdl_callback(), sdl_write(), serial_iec_set_st(), set_acia_ticks(), set_drive_fixed(), set_fullscreen_enabled(), set_keyset_resources(), set_printer_device(), set_ps2mouse_enable(), reSID::SID::set_sampling_parameters(), set_volume(), sid_engine_model_widget_create(), sid_model_callback(), sid_snapshot_read_module_simple(), snapshot_module_open(), snapshot_module_read_byte_into_int(), snapshot_module_read_byte_into_uint(), snapshot_module_read_dword_into_int(), snapshot_module_read_dword_into_uint(), snapshot_module_read_word_into_int(), snapshot_module_read_word_into_uint(), snapshot_open(), snapshot_read_string(), sort_by_parent_function(), sound_dac_calculate_samples(), sound_open(), sound_run_sound(), sound_set_machine_parameter(), soundmovie_write(), statusbar_speed_widget_update(), string_to_queue(), t64_read(), t6721_update_output(), tap_close(), tap_find_header(), tap_find_pilot(), tap_get_pulse(), tap_open(), tap_seek_to_offset(), tape_receive_trap(), tape_receive_trap_plus4(), tape_snapshot_write_tapimage_module(), ui_mouse_grab_pointer(), update_runtime_widget(), util_subst(), vdrive_bam_allocate_chain(), vdrive_bam_allocate_chain_255(), vdrive_bam_clr(), vdrive_bam_isset(), vdrive_bam_sector_free(), vdrive_bam_set(), vdrive_command_allocate_chain(), vdrive_command_chpart(), vdrive_command_format(), vdrive_command_format_internal(), vdrive_command_format_worker(), vdrive_command_get_block_parameters(), vdrive_command_scratch(), vdrive_command_set_error(), vdrive_command_switchtraverse(), vdrive_command_time(), vdrive_command_validate(), vdrive_dir_find_next_slot(), vdrive_dir_first_directory(), vdrive_dir_free_chain(), vdrive_dir_part_find_next_slot(), vdrive_dir_part_first_directory(), vdrive_dir_remove_slot(), vdrive_rel_read(), vdrive_rel_write(), vice_gtk3_resource_scale_int_get(), vice_gtk3_resource_scale_int_set_marks(), vice_network_client(), vice_network_server(), vicii_badline_check_state(), vicii_raster_draw_alarm_handler(), vicii_snapshot_read_module(), video_calc_ycbcrtable(), video_convert_renderer_to_rgb_gamma(), video_sound_machine_calculate_samples(), video_sound_update(), video_viewport_resize(), voc_write(), wav_write(), and wd1770_store().
opencbmlib_close()
void opencbmlib_close (void)
opencbmlib_is_available()
unsigned int opencbmlib_is_available (void)
opencbmlib_open()
int opencbmlib_open (opencbmlib_t * opencbmlib)
void()
typedef void (* cbm_driver_close_t)
< The "file descriptor" for an opened driver
Parameters
cbm_driver_close_t CBMAPIDECL is a dummy on Linux
Referenced by fliplist_load_action(), fliplist_save_action(), io_store(), on_button_press_event(), on_combo_changed(), on_custom_item_activate(), on_iec_toggled(), on_model_toggled(), on_radio_toggled(), on_response_confirm(), on_virtual_device_toggled(), psid_playlist_action(), and sid_model_callback().