vsid: arch/gtk3/widgets/settings_io.c File Reference
settings_io.c File Reference
I/O extension settings that don't go/fit into subwidgets.
#include "vice.h"
#include <gtk/gtk.h>
#include "cartio.h"
#include "machine.h"
#include "vice_gtk3.h"
#include "settings_io.h"
Functions
static GtkWidget * create_collision_widget (const char *desc)
Create widget to specify I/O collision handling method.
static GtkWidget * create_cart_reset_widget (void)
Create check button for "reset-on-cart-change".
static void create_c64_layout (GtkWidget *grid)
Create layout for x64/x64sc.
static void create_scpu64_layout (GtkWidget *grid)
Create layout for xscpu64.
static void create_c128_layout (GtkWidget *grid)
Create layout for x128.
static void create_c64dtv_layout (GtkWidget *grid)
Create layout for x64dtv.
static void create_vic20_layout (GtkWidget *grid)
Create layout for xvic.
static void create_plus4_layout (GtkWidget *grid)
Create layout for xplus4.
static void create_pet_layout (GtkWidget *grid)
Create layout for xpet.
static void create_cbm5x0_layout (GtkWidget *grid)
Create layout for xcbm5x0/xcbm2.
GtkWidget * settings_io_widget_create (GtkWidget *parent)
Create widget for generic I/O extension settings.
Variables
static const vice_gtk3_radiogroup_entry_t io_collision_methods []
Methods of handling I/O collisions.
Detailed Description
I/O extension settings that don't go/fit into subwidgets.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_c128_layout()
static void create_c128_layout (GtkWidget * grid) static
Create layout for x128.
Parameters
[in,out] grid grid to add widgets to
Referenced by settings_io_widget_create().
create_c64_layout()
static void create_c64_layout (GtkWidget * grid) static
Create layout for x64/x64sc.
Parameters
[in,out] grid grid to add widgets to
Referenced by settings_io_widget_create().
create_c64dtv_layout()
static void create_c64dtv_layout (GtkWidget * grid) static
Create layout for x64dtv.
Parameters
[in,out] grid grid to add widgets to
Referenced by settings_io_widget_create().
create_cart_reset_widget()
static GtkWidget * create_cart_reset_widget (void) static
Create check button for "reset-on-cart-change".
Returns
GtkCheckButton
Referenced by create_c128_layout(), create_c64_layout(), create_cbm5x0_layout(), create_plus4_layout(), create_scpu64_layout(), and create_vic20_layout().
create_cbm5x0_layout()
static void create_cbm5x0_layout (GtkWidget * grid) static
Create layout for xcbm5x0/xcbm2.
Parameters
[in,out] grid grid to add widgets to
Referenced by settings_io_widget_create().
create_collision_widget()
static GtkWidget * create_collision_widget (const char * desc) static
Create widget to specify I/O collision handling method.
The desc is added as a label under the "I/O collision handling" label, in italics and surrounded with parenthesis.
Parameters
[in] desc description of the I/O areas involved
Returns
GtkGrid
Referenced by create_c128_layout(), create_c64_layout(), create_cbm5x0_layout(), create_pet_layout(), create_plus4_layout(), create_scpu64_layout(), and create_vic20_layout().
create_pet_layout()
static void create_pet_layout (GtkWidget * grid) static
Create layout for xpet.
Parameters
[in,out] grid grid to add widgets to
Referenced by settings_io_widget_create().
create_plus4_layout()
static void create_plus4_layout (GtkWidget * grid) static
Create layout for xplus4.
Parameters
[in,out] grid grid to add widgets to
Referenced by settings_io_widget_create().
create_scpu64_layout()
static void create_scpu64_layout (GtkWidget * grid) static
Create layout for xscpu64.
Parameters
[in,out] grid grid to add widgets to
Referenced by settings_io_widget_create().
create_vic20_layout()
static void create_vic20_layout (GtkWidget * grid) static
Create layout for xvic.
Parameters
[in,out] grid grid to add widgets to
Referenced by settings_io_widget_create().
settings_io_widget_create()
GtkWidget * settings_io_widget_create (GtkWidget * parent)
Create widget for generic I/O extension settings.
Creates a widget for generic I/O extension settings and settings that don't make sense to create a separate widget for (ie stuff that has a single bool resource or a single "open file" dialog").
Parameters
[in] parent parent widget
Returns
GtkGrid
Variable Documentation
io_collision_methods
const vice_gtk3_radiogroup_entry_t io_collision_methods[] static
Initial value:
= {
    { "Detach all",      0  },
    { "Detach last",     1  },
    { "AND values",      2  },
    { NULL,             -1 }
}
Methods of handling I/O collisions.
Referenced by create_collision_widget().