vsid: userport/userport.h File Reference
userport.h File Reference
#include "snapshot.h"
#include "types.h"
Data Structures
struct userport_device_s
this structure is used by userport devices
struct userport_port_props_s
this structure is used by userport ports
struct userport_desc_s
Macros
#define USERPORT_NO_PULSE 0
#define USERPORT_PULSE 1
#define USERPORT24_PIN_1 0x00000001
24 pin userport pin defines
#define USERPORT24_PIN_2 0x00000002
#define USERPORT24_PIN_3 0x00000004
#define USERPORT24_PIN_4 0x00000008
#define USERPORT24_PIN_5 0x00000010
#define USERPORT24_PIN_6 0x00000020
#define USERPORT24_PIN_7 0x00000040
#define USERPORT24_PIN_8 0x00000080
#define USERPORT24_PIN_9 0x00000100
#define USERPORT24_PIN_10 0x00000200
#define USERPORT24_PIN_11 0x00000400
#define USERPORT24_PIN_12 0x00000800
pin 12 is currently GND on all supported 24 pin userports
#define USERPORT24_PIN_A 0x00001000
pin A is currently GND on all supported 24 pin userports
#define USERPORT24_PIN_B 0x00002000
#define USERPORT24_PIN_C 0x00004000
#define USERPORT24_PIN_D 0x00008000
#define USERPORT24_PIN_E 0x00010000
#define USERPORT24_PIN_F 0x00020000
#define USERPORT24_PIN_H 0x00040000
#define USERPORT24_PIN_J 0x00080000
#define USERPORT24_PIN_K 0x00100000
#define USERPORT24_PIN_L 0x00200000
#define USERPORT24_PIN_M 0x00400000
#define USERPORT24_PIN_N 0x00800000
pin N is currently GND on all supported 24 pin userports
#define USERPORT26_PIN_1 0x00000001
xcbm2 pins
#define USERPORT26_PIN_2 0x00000002
#define USERPORT26_PIN_3 0x00000004
pin 3 is GND on cbm2
#define USERPORT26_PIN_4 0x00000008
#define USERPORT26_PIN_5 0x00000010
#define USERPORT26_PIN_6 0x00000020
#define USERPORT26_PIN_7 0x00000040
#define USERPORT26_PIN_8 0x00000080
#define USERPORT26_PIN_9 0x00000100
#define USERPORT26_PIN_10 0x00000200
#define USERPORT26_PIN_11 0x00000400
#define USERPORT26_PIN_12 0x00000800
#define USERPORT26_PIN_13 0x00001000
#define USERPORT26_PIN_14 0x00002000
#define USERPORT26_PIN_15 0x00004000
#define USERPORT26_PIN_16 0x00008000
#define USERPORT26_PIN_17 0x00010000
#define USERPORT26_PIN_18 0x00020000
#define USERPORT26_PIN_19 0x00040000
#define USERPORT26_PIN_20 0x00080000
#define USERPORT26_PIN_21 0x00100000
#define USERPORT26_PIN_22 0x00200000
#define USERPORT26_PIN_23 0x00400000
#define USERPORT26_PIN_24 0x00800000
pin 24 is +5VDC on cbm2
#define USERPORT26_PIN_25 0x01000000
#define USERPORT26_PIN_26 0x02000000
#define USERPORT24_PIN_D0 USERPORT24_PIN_C
x64/x64sc/x128/xscpu64/xvic/xpet/xpet data pins
#define USERPORT24_PIN_D1 USERPORT24_PIN_D
#define USERPORT24_PIN_D2 USERPORT24_PIN_E
#define USERPORT24_PIN_D3 USERPORT24_PIN_F
#define USERPORT24_PIN_D4 USERPORT24_PIN_H
#define USERPORT24_PIN_D5 USERPORT24_PIN_J
#define USERPORT24_PIN_D6 USERPORT24_PIN_K
#define USERPORT24_PIN_D7 USERPORT24_PIN_L
#define USERPORT24_PLUS4_PIN_P0 USERPORT24_PIN_B
xplus4 data pins
#define USERPORT24_PLUS4_PIN_P1 USERPORT24_PIN_K
#define USERPORT24_PLUS4_PIN_P2 USERPORT24_PIN_4
#define USERPORT24_PLUS4_PIN_P3 USERPORT24_PIN_5
#define USERPORT24_PLUS4_PIN_P4 USERPORT24_PIN_6
#define USERPORT24_PLUS4_PIN_P5 USERPORT24_PIN_7
#define USERPORT24_PLUS4_PIN_P6 USERPORT24_PIN_J
#define USERPORT24_PLUS4_PIN_P7 USERPORT24_PIN_F
#define USERPORT24_C64_PIN_CNT1 USERPORT24_PIN_4
x64/x64sc/xscpu64/x128 specific pins, you can use these pin names when a device only works on the machines in question.
#define USERPORT24_C64_PIN_SP1 USERPORT24_PIN_5
#define USERPORT24_C64_PIN_CNT2 USERPORT24_PIN_6
#define USERPORT24_C64_PIN_SP2 USERPORT24_PIN_7
#define USERPORT24_C64_PIN_PC2 USERPORT24_PIN_8
#define USERPORT24_C64_PIN_IEC_ATN_IN USERPORT24_PIN_9
#define USERPORT24_C64_PIN_NFLAG2 USERPORT24_PIN_B
#define USERPORT24_C64_PIN_PA2 USERPORT24_PIN_M
#define USERPORT24_C64DTV_PIN_PA2 USERPORT24_PIN_M
x64dtv specific pins
#define USERPORT24_VIC20_PIN_JOY0 USERPORT24_PIN_4
xvic specific pins
#define USERPORT24_VIC20_PIN_JOY1 USERPORT24_PIN_5
#define USERPORT24_VIC20_PIN_JOY2 USERPORT24_PIN_6
#define USERPORT24_VIC20_PIN_LP_FIRE USERPORT24_PIN_7
#define USERPORT24_VIC20_PIN_PA6_TAPE_SENSE USERPORT24_PIN_8
#define USERPORT24_VIC20_PIN_IEC_ATN_IN USERPORT24_PIN_9
#define USERPORT24_VIC20_PIN_CB1 USERPORT24_PIN_B
#define USERPORT24_VIC20_PIN_CB2 USERPORT24_PIN_M
#define USERPORT24_PLUS4_PIN_RS232_CLOCK USERPORT24_PIN_8
xplus4 specific pins
#define USERPORT24_PLUS4_PIN_ATN USERPORT24_PIN_9
#define USERPORT24_PLUS4_PIN_ACIA_RXD USERPORT24_PIN_C
#define USERPORT24_PLUS4_PIN_ACIA_RTS USERPORT24_PIN_D
#define USERPORT24_PLUS4_PIN_ACIA_DTR USERPORT24_PIN_E
#define USERPORT24_PLUS4_PIN_ACIA_DCD USERPORT24_PIN_H
#define USERPORT24_PLUS4_PIN_ACIA_DSR USERPORT24_PIN_L
#define USERPORT24_PLUS4_PIN_ACIA_TXD USERPORT24_PIN_M
#define USERPORT24_PET_PIN_TV_VIDEO USERPORT24_PIN_2
xpet specific pins
#define USERPORT24_PET_PIN_IEEE_SRQ USERPORT24_PIN_3
#define USERPORT24_PET_PIN_IEEE_EOI USERPORT24_PIN_4
#define USERPORT24_PET_PIN_IEEE_DIAG_SENSE USERPORT24_PIN_5
#define USERPORT24_PET_PIN_TAPE2_READ USERPORT24_PIN_6
#define USERPORT24_PET_PIN_TAPE_WRITE USERPORT24_PIN_7
#define USERPORT24_PET_PIN_TAPE1_READ USERPORT24_PIN_8
#define USERPORT24_PET_PIN_TV_VERTICAL USERPORT24_PIN_9
#define USERPORT24_PET_PIN_TV_HORIZONTAL USERPORT24_PIN_10
#define USERPORT24_PET_PIN_GRAPHIC USERPORT24_PIN_11
#define USERPORT24_PET_PIN_CA1 USERPORT24_PIN_B
#define USERPORT24_PET_PIN_CB2 USERPORT24_PIN_M
#define USERPORT26_CBM2_PIN_PB2 USERPORT26_PIN_2
xcbm2 specific pins
#define USERPORT26_CBM2_PIN_PB3 USERPORT26_PIN_4
#define USERPORT26_CBM2_PIN_NPC USERPORT26_PIN_5
#define USERPORT26_CBM2_PIN_NFLAG USERPORT26_PIN_6
#define USERPORT26_CBM2_PIN_2D7 USERPORT26_PIN_7
#define USERPORT26_CBM2_PIN_2D6 USERPORT26_PIN_8
#define USERPORT26_CBM2_PIN_2D5 USERPORT26_PIN_9
#define USERPORT26_CBM2_PIN_2D4 USERPORT26_PIN_10
#define USERPORT26_CBM2_PIN_2D3 USERPORT26_PIN_11
#define USERPORT26_CBM2_PIN_2D2 USERPORT26_PIN_12
#define USERPORT26_CBM2_PIN_2D1 USERPORT26_PIN_13
#define USERPORT26_CBM2_PIN_2D0 USERPORT26_PIN_14
#define USERPORT26_CBM2_PIN_1D7 USERPORT26_PIN_15
#define USERPORT26_CBM2_PIN_1D6 USERPORT26_PIN_16
#define USERPORT26_CBM2_PIN_1D5 USERPORT26_PIN_17
#define USERPORT26_CBM2_PIN_1D4 USERPORT26_PIN_18
#define USERPORT26_CBM2_PIN_1D3 USERPORT26_PIN_19
#define USERPORT26_CBM2_PIN_1D2 USERPORT26_PIN_20
#define USERPORT26_CBM2_PIN_1D1 USERPORT26_PIN_21
#define USERPORT26_CBM2_PIN_1D0 USERPORT26_PIN_22
#define USERPORT26_CBM2_PIN_NCNT USERPORT26_PIN_23
#define USERPORT26_CBM2_PIN_NIRQ USERPORT26_PIN_25
#define USERPORT26_CBM2_PIN_SP USERPORT26_PIN_26
Typedefs
typedef struct userport_device_s userport_device_t
this structure is used by userport devices
typedef struct userport_port_props_s userport_port_props_t
this structure is used by userport ports
typedef struct userport_desc_s userport_desc_t
Enumerations
enum {
USERPORT_DEVICE_NONE = 0 ,
USERPORT_DEVICE_PRINTER ,
USERPORT_DEVICE_RS232_MODEM ,
USERPORT_DEVICE_JOYSTICK_CGA ,
USERPORT_DEVICE_JOYSTICK_PET ,
USERPORT_DEVICE_JOYSTICK_HUMMER ,
USERPORT_DEVICE_JOYSTICK_OEM ,
USERPORT_DEVICE_JOYSTICK_HIT ,
USERPORT_DEVICE_JOYSTICK_KINGSOFT ,
USERPORT_DEVICE_JOYSTICK_STARBYTE ,
USERPORT_DEVICE_JOYSTICK_SYNERGY ,
USERPORT_DEVICE_JOYSTICK_WOJ ,
USERPORT_DEVICE_DAC ,
USERPORT_DEVICE_DIGIMAX ,
USERPORT_DEVICE_4BIT_SAMPLER ,
USERPORT_DEVICE_8BSS ,
USERPORT_DEVICE_RTC_58321A ,
USERPORT_DEVICE_RTC_DS1307 ,
USERPORT_DEVICE_PETSCII_SNESPAD ,
USERPORT_DEVICE_SUPERPAD64 ,
USERPORT_DEVICE_DIAG_586220_HARNESS ,
USERPORT_DEVICE_DRIVE_PAR_CABLE ,
USERPORT_DEVICE_IO_SIMULATION ,
USERPORT_DEVICE_WIC64 ,
USERPORT_DEVICE_SPACEBALLS ,
USERPORT_DEVICE_SPT_JOYSTICK ,
USERPORT_MAX_DEVICES
}
enum {
USERPORT_DEVICE_TYPE_NONE = 0 ,
USERPORT_DEVICE_TYPE_PRINTER ,
USERPORT_DEVICE_TYPE_MODEM ,
USERPORT_DEVICE_TYPE_DRIVE_PAR_CABLE ,
USERPORT_DEVICE_TYPE_JOYSTICK_ADAPTER ,
USERPORT_DEVICE_TYPE_AUDIO_OUTPUT ,
USERPORT_DEVICE_TYPE_SAMPLER ,
USERPORT_DEVICE_TYPE_RTC ,
USERPORT_DEVICE_TYPE_IO_SIMULATION
}
Functions
void userport_port_register (userport_port_props_t *props)
int userport_device_register (int id, userport_device_t *device)
register a device to be used in the userport system if possible
int userport_get_device (void)
uint8_t read_userport_pbx (uint8_t orig)
void store_userport_pbx (uint8_t val, int pulse)
uint8_t read_userport_pa2 (uint8_t orig)
void store_userport_pa2 (uint8_t val)
uint8_t read_userport_pa3 (uint8_t orig)
void store_userport_pa3 (uint8_t val)
uint8_t read_userport_pc (uint8_t orig)
uint8_t read_userport_sp1 (uint8_t orig)
void store_userport_sp1 (uint8_t val)
uint8_t read_userport_sp2 (uint8_t orig)
void store_userport_sp2 (uint8_t val)
void userport_reset_start (void)
void userport_reset (void)
void userport_reset_end (void)
void userport_powerup (void)
void set_userport_flag (uint8_t val)
use this function from userport device code to set the userport flag
int userport_resources_init (void)
int userport_cmdline_options_init (void)
userport_desc_t * userport_get_valid_devices (int sort)
const char * userport_get_device_type_desc (int type)
Get short description of of userport device type.
void userport_enable (int val)
int userport_get_active_state (void)
int userport_snapshot_write_module (snapshot_t *s)
int userport_snapshot_read_module (snapshot_t *s)
Macro Definition Documentation
USERPORT24_C64_PIN_CNT1
#define USERPORT24_C64_PIN_CNT1 USERPORT24_PIN_4
x64/x64sc/xscpu64/x128 specific pins, you can use these pin names when a device only works on the machines in question.
USERPORT24_C64_PIN_CNT2
#define USERPORT24_C64_PIN_CNT2 USERPORT24_PIN_6
USERPORT24_C64_PIN_IEC_ATN_IN
#define USERPORT24_C64_PIN_IEC_ATN_IN USERPORT24_PIN_9
USERPORT24_C64_PIN_NFLAG2
#define USERPORT24_C64_PIN_NFLAG2 USERPORT24_PIN_B
USERPORT24_C64_PIN_PA2
#define USERPORT24_C64_PIN_PA2 USERPORT24_PIN_M
USERPORT24_C64_PIN_PC2
#define USERPORT24_C64_PIN_PC2 USERPORT24_PIN_8
USERPORT24_C64_PIN_SP1
#define USERPORT24_C64_PIN_SP1 USERPORT24_PIN_5
USERPORT24_C64_PIN_SP2
#define USERPORT24_C64_PIN_SP2 USERPORT24_PIN_7
USERPORT24_C64DTV_PIN_PA2
#define USERPORT24_C64DTV_PIN_PA2 USERPORT24_PIN_M
x64dtv specific pins
USERPORT24_PET_PIN_CA1
#define USERPORT24_PET_PIN_CA1 USERPORT24_PIN_B
USERPORT24_PET_PIN_CB2
#define USERPORT24_PET_PIN_CB2 USERPORT24_PIN_M
USERPORT24_PET_PIN_GRAPHIC
#define USERPORT24_PET_PIN_GRAPHIC USERPORT24_PIN_11
USERPORT24_PET_PIN_IEEE_DIAG_SENSE
#define USERPORT24_PET_PIN_IEEE_DIAG_SENSE USERPORT24_PIN_5
USERPORT24_PET_PIN_IEEE_EOI
#define USERPORT24_PET_PIN_IEEE_EOI USERPORT24_PIN_4
USERPORT24_PET_PIN_IEEE_SRQ
#define USERPORT24_PET_PIN_IEEE_SRQ USERPORT24_PIN_3
USERPORT24_PET_PIN_TAPE1_READ
#define USERPORT24_PET_PIN_TAPE1_READ USERPORT24_PIN_8
USERPORT24_PET_PIN_TAPE2_READ
#define USERPORT24_PET_PIN_TAPE2_READ USERPORT24_PIN_6
USERPORT24_PET_PIN_TAPE_WRITE
#define USERPORT24_PET_PIN_TAPE_WRITE USERPORT24_PIN_7
USERPORT24_PET_PIN_TV_HORIZONTAL
#define USERPORT24_PET_PIN_TV_HORIZONTAL USERPORT24_PIN_10
USERPORT24_PET_PIN_TV_VERTICAL
#define USERPORT24_PET_PIN_TV_VERTICAL USERPORT24_PIN_9
USERPORT24_PET_PIN_TV_VIDEO
#define USERPORT24_PET_PIN_TV_VIDEO USERPORT24_PIN_2
xpet specific pins
USERPORT24_PIN_1
#define USERPORT24_PIN_1 0x00000001
24 pin userport pin defines
pin 1 is currently GND on all supported 24 pin userports
USERPORT24_PIN_10
#define USERPORT24_PIN_10 0x00000200
USERPORT24_PIN_11
#define USERPORT24_PIN_11 0x00000400
USERPORT24_PIN_12
#define USERPORT24_PIN_12 0x00000800
pin 12 is currently GND on all supported 24 pin userports
USERPORT24_PIN_2
#define USERPORT24_PIN_2 0x00000002
USERPORT24_PIN_3
#define USERPORT24_PIN_3 0x00000004
USERPORT24_PIN_4
#define USERPORT24_PIN_4 0x00000008
USERPORT24_PIN_5
#define USERPORT24_PIN_5 0x00000010
USERPORT24_PIN_6
#define USERPORT24_PIN_6 0x00000020
USERPORT24_PIN_7
#define USERPORT24_PIN_7 0x00000040
USERPORT24_PIN_8
#define USERPORT24_PIN_8 0x00000080
USERPORT24_PIN_9
#define USERPORT24_PIN_9 0x00000100
USERPORT24_PIN_A
#define USERPORT24_PIN_A 0x00001000
pin A is currently GND on all supported 24 pin userports
USERPORT24_PIN_B
#define USERPORT24_PIN_B 0x00002000
USERPORT24_PIN_C
#define USERPORT24_PIN_C 0x00004000
USERPORT24_PIN_D
#define USERPORT24_PIN_D 0x00008000
USERPORT24_PIN_D0
#define USERPORT24_PIN_D0 USERPORT24_PIN_C
x64/x64sc/x128/xscpu64/xvic/xpet/xpet data pins
USERPORT24_PIN_D1
#define USERPORT24_PIN_D1 USERPORT24_PIN_D
USERPORT24_PIN_D2
#define USERPORT24_PIN_D2 USERPORT24_PIN_E
USERPORT24_PIN_D3
#define USERPORT24_PIN_D3 USERPORT24_PIN_F
USERPORT24_PIN_D4
#define USERPORT24_PIN_D4 USERPORT24_PIN_H
USERPORT24_PIN_D5
#define USERPORT24_PIN_D5 USERPORT24_PIN_J
USERPORT24_PIN_D6
#define USERPORT24_PIN_D6 USERPORT24_PIN_K
USERPORT24_PIN_D7
#define USERPORT24_PIN_D7 USERPORT24_PIN_L
USERPORT24_PIN_E
#define USERPORT24_PIN_E 0x00010000
USERPORT24_PIN_F
#define USERPORT24_PIN_F 0x00020000
USERPORT24_PIN_H
#define USERPORT24_PIN_H 0x00040000
USERPORT24_PIN_J
#define USERPORT24_PIN_J 0x00080000
USERPORT24_PIN_K
#define USERPORT24_PIN_K 0x00100000
USERPORT24_PIN_L
#define USERPORT24_PIN_L 0x00200000
USERPORT24_PIN_M
#define USERPORT24_PIN_M 0x00400000
USERPORT24_PIN_N
#define USERPORT24_PIN_N 0x00800000
pin N is currently GND on all supported 24 pin userports
USERPORT24_PLUS4_PIN_ACIA_DCD
#define USERPORT24_PLUS4_PIN_ACIA_DCD USERPORT24_PIN_H
USERPORT24_PLUS4_PIN_ACIA_DSR
#define USERPORT24_PLUS4_PIN_ACIA_DSR USERPORT24_PIN_L
USERPORT24_PLUS4_PIN_ACIA_DTR
#define USERPORT24_PLUS4_PIN_ACIA_DTR USERPORT24_PIN_E
USERPORT24_PLUS4_PIN_ACIA_RTS
#define USERPORT24_PLUS4_PIN_ACIA_RTS USERPORT24_PIN_D
USERPORT24_PLUS4_PIN_ACIA_RXD
#define USERPORT24_PLUS4_PIN_ACIA_RXD USERPORT24_PIN_C
USERPORT24_PLUS4_PIN_ACIA_TXD
#define USERPORT24_PLUS4_PIN_ACIA_TXD USERPORT24_PIN_M
USERPORT24_PLUS4_PIN_ATN
#define USERPORT24_PLUS4_PIN_ATN USERPORT24_PIN_9
USERPORT24_PLUS4_PIN_P0
#define USERPORT24_PLUS4_PIN_P0 USERPORT24_PIN_B
xplus4 data pins
USERPORT24_PLUS4_PIN_P1
#define USERPORT24_PLUS4_PIN_P1 USERPORT24_PIN_K
USERPORT24_PLUS4_PIN_P2
#define USERPORT24_PLUS4_PIN_P2 USERPORT24_PIN_4
USERPORT24_PLUS4_PIN_P3
#define USERPORT24_PLUS4_PIN_P3 USERPORT24_PIN_5
USERPORT24_PLUS4_PIN_P4
#define USERPORT24_PLUS4_PIN_P4 USERPORT24_PIN_6
USERPORT24_PLUS4_PIN_P5
#define USERPORT24_PLUS4_PIN_P5 USERPORT24_PIN_7
USERPORT24_PLUS4_PIN_P6
#define USERPORT24_PLUS4_PIN_P6 USERPORT24_PIN_J
USERPORT24_PLUS4_PIN_P7
#define USERPORT24_PLUS4_PIN_P7 USERPORT24_PIN_F
USERPORT24_PLUS4_PIN_RS232_CLOCK
#define USERPORT24_PLUS4_PIN_RS232_CLOCK USERPORT24_PIN_8
xplus4 specific pins
USERPORT24_VIC20_PIN_CB1
#define USERPORT24_VIC20_PIN_CB1 USERPORT24_PIN_B
USERPORT24_VIC20_PIN_CB2
#define USERPORT24_VIC20_PIN_CB2 USERPORT24_PIN_M
USERPORT24_VIC20_PIN_IEC_ATN_IN
#define USERPORT24_VIC20_PIN_IEC_ATN_IN USERPORT24_PIN_9
USERPORT24_VIC20_PIN_JOY0
#define USERPORT24_VIC20_PIN_JOY0 USERPORT24_PIN_4
xvic specific pins
USERPORT24_VIC20_PIN_JOY1
#define USERPORT24_VIC20_PIN_JOY1 USERPORT24_PIN_5
USERPORT24_VIC20_PIN_JOY2
#define USERPORT24_VIC20_PIN_JOY2 USERPORT24_PIN_6
USERPORT24_VIC20_PIN_LP_FIRE
#define USERPORT24_VIC20_PIN_LP_FIRE USERPORT24_PIN_7
USERPORT24_VIC20_PIN_PA6_TAPE_SENSE
#define USERPORT24_VIC20_PIN_PA6_TAPE_SENSE USERPORT24_PIN_8
USERPORT26_CBM2_PIN_1D0
#define USERPORT26_CBM2_PIN_1D0 USERPORT26_PIN_22
USERPORT26_CBM2_PIN_1D1
#define USERPORT26_CBM2_PIN_1D1 USERPORT26_PIN_21
USERPORT26_CBM2_PIN_1D2
#define USERPORT26_CBM2_PIN_1D2 USERPORT26_PIN_20
USERPORT26_CBM2_PIN_1D3
#define USERPORT26_CBM2_PIN_1D3 USERPORT26_PIN_19
USERPORT26_CBM2_PIN_1D4
#define USERPORT26_CBM2_PIN_1D4 USERPORT26_PIN_18
USERPORT26_CBM2_PIN_1D5
#define USERPORT26_CBM2_PIN_1D5 USERPORT26_PIN_17
USERPORT26_CBM2_PIN_1D6
#define USERPORT26_CBM2_PIN_1D6 USERPORT26_PIN_16
USERPORT26_CBM2_PIN_1D7
#define USERPORT26_CBM2_PIN_1D7 USERPORT26_PIN_15
USERPORT26_CBM2_PIN_2D0
#define USERPORT26_CBM2_PIN_2D0 USERPORT26_PIN_14
USERPORT26_CBM2_PIN_2D1
#define USERPORT26_CBM2_PIN_2D1 USERPORT26_PIN_13
USERPORT26_CBM2_PIN_2D2
#define USERPORT26_CBM2_PIN_2D2 USERPORT26_PIN_12
USERPORT26_CBM2_PIN_2D3
#define USERPORT26_CBM2_PIN_2D3 USERPORT26_PIN_11
USERPORT26_CBM2_PIN_2D4
#define USERPORT26_CBM2_PIN_2D4 USERPORT26_PIN_10
USERPORT26_CBM2_PIN_2D5
#define USERPORT26_CBM2_PIN_2D5 USERPORT26_PIN_9
USERPORT26_CBM2_PIN_2D6
#define USERPORT26_CBM2_PIN_2D6 USERPORT26_PIN_8
USERPORT26_CBM2_PIN_2D7
#define USERPORT26_CBM2_PIN_2D7 USERPORT26_PIN_7
USERPORT26_CBM2_PIN_NCNT
#define USERPORT26_CBM2_PIN_NCNT USERPORT26_PIN_23
USERPORT26_CBM2_PIN_NFLAG
#define USERPORT26_CBM2_PIN_NFLAG USERPORT26_PIN_6
USERPORT26_CBM2_PIN_NIRQ
#define USERPORT26_CBM2_PIN_NIRQ USERPORT26_PIN_25
USERPORT26_CBM2_PIN_NPC
#define USERPORT26_CBM2_PIN_NPC USERPORT26_PIN_5
USERPORT26_CBM2_PIN_PB2
#define USERPORT26_CBM2_PIN_PB2 USERPORT26_PIN_2
xcbm2 specific pins
USERPORT26_CBM2_PIN_PB3
#define USERPORT26_CBM2_PIN_PB3 USERPORT26_PIN_4
USERPORT26_CBM2_PIN_SP
#define USERPORT26_CBM2_PIN_SP USERPORT26_PIN_26
USERPORT26_PIN_1
#define USERPORT26_PIN_1 0x00000001
xcbm2 pins
pin 1 is GND on cbm2
USERPORT26_PIN_10
#define USERPORT26_PIN_10 0x00000200
USERPORT26_PIN_11
#define USERPORT26_PIN_11 0x00000400
USERPORT26_PIN_12
#define USERPORT26_PIN_12 0x00000800
USERPORT26_PIN_13
#define USERPORT26_PIN_13 0x00001000
USERPORT26_PIN_14
#define USERPORT26_PIN_14 0x00002000
USERPORT26_PIN_15
#define USERPORT26_PIN_15 0x00004000
USERPORT26_PIN_16
#define USERPORT26_PIN_16 0x00008000
USERPORT26_PIN_17
#define USERPORT26_PIN_17 0x00010000
USERPORT26_PIN_18
#define USERPORT26_PIN_18 0x00020000
USERPORT26_PIN_19
#define USERPORT26_PIN_19 0x00040000
USERPORT26_PIN_2
#define USERPORT26_PIN_2 0x00000002
USERPORT26_PIN_20
#define USERPORT26_PIN_20 0x00080000
USERPORT26_PIN_21
#define USERPORT26_PIN_21 0x00100000
USERPORT26_PIN_22
#define USERPORT26_PIN_22 0x00200000
USERPORT26_PIN_23
#define USERPORT26_PIN_23 0x00400000
USERPORT26_PIN_24
#define USERPORT26_PIN_24 0x00800000
pin 24 is +5VDC on cbm2
USERPORT26_PIN_25
#define USERPORT26_PIN_25 0x01000000
USERPORT26_PIN_26
#define USERPORT26_PIN_26 0x02000000
USERPORT26_PIN_3
#define USERPORT26_PIN_3 0x00000004
pin 3 is GND on cbm2
USERPORT26_PIN_4
#define USERPORT26_PIN_4 0x00000008
USERPORT26_PIN_5
#define USERPORT26_PIN_5 0x00000010
USERPORT26_PIN_6
#define USERPORT26_PIN_6 0x00000020
USERPORT26_PIN_7
#define USERPORT26_PIN_7 0x00000040
USERPORT26_PIN_8
#define USERPORT26_PIN_8 0x00000080
USERPORT26_PIN_9
#define USERPORT26_PIN_9 0x00000100
USERPORT_NO_PULSE
#define USERPORT_NO_PULSE 0
USERPORT_PULSE
#define USERPORT_PULSE 1
Typedef Documentation
userport_desc_t
typedef struct userport_desc_s userport_desc_t
userport_device_t
typedef struct userport_device_s userport_device_t
this structure is used by userport devices
userport_port_props_t
typedef struct userport_port_props_s userport_port_props_t
this structure is used by userport ports
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
USERPORT_DEVICE_NONE
USERPORT_DEVICE_PRINTER
USERPORT_DEVICE_RS232_MODEM
USERPORT_DEVICE_JOYSTICK_CGA
USERPORT_DEVICE_JOYSTICK_PET
USERPORT_DEVICE_JOYSTICK_HUMMER
USERPORT_DEVICE_JOYSTICK_OEM
USERPORT_DEVICE_JOYSTICK_HIT
USERPORT_DEVICE_JOYSTICK_KINGSOFT
USERPORT_DEVICE_JOYSTICK_STARBYTE
USERPORT_DEVICE_JOYSTICK_SYNERGY
USERPORT_DEVICE_JOYSTICK_WOJ
USERPORT_DEVICE_DAC
USERPORT_DEVICE_DIGIMAX
USERPORT_DEVICE_4BIT_SAMPLER
USERPORT_DEVICE_8BSS
USERPORT_DEVICE_RTC_58321A
USERPORT_DEVICE_RTC_DS1307
USERPORT_DEVICE_PETSCII_SNESPAD
USERPORT_DEVICE_SUPERPAD64
USERPORT_DEVICE_DIAG_586220_HARNESS
USERPORT_DEVICE_DRIVE_PAR_CABLE
USERPORT_DEVICE_IO_SIMULATION
USERPORT_DEVICE_WIC64
USERPORT_DEVICE_SPACEBALLS
USERPORT_DEVICE_SPT_JOYSTICK
USERPORT_MAX_DEVICES
anonymous enum
anonymous enum
Enumerator
USERPORT_DEVICE_TYPE_NONE
USERPORT_DEVICE_TYPE_PRINTER
USERPORT_DEVICE_TYPE_MODEM
USERPORT_DEVICE_TYPE_DRIVE_PAR_CABLE
USERPORT_DEVICE_TYPE_JOYSTICK_ADAPTER
USERPORT_DEVICE_TYPE_AUDIO_OUTPUT
USERPORT_DEVICE_TYPE_SAMPLER
USERPORT_DEVICE_TYPE_RTC
USERPORT_DEVICE_TYPE_IO_SIMULATION
Function Documentation
read_userport_pa2()
uint8_t read_userport_pa2 (uint8_t orig)
Referenced by read_ciapa().
read_userport_pa3()
uint8_t read_userport_pa3 (uint8_t orig)
Referenced by read_ciapa().
read_userport_pbx()
uint8_t read_userport_pbx (uint8_t orig)
Referenced by read_ciapb().
read_userport_pc()
uint8_t read_userport_pc (uint8_t orig)
read_userport_sp1()
uint8_t read_userport_sp1 (uint8_t orig)
Referenced by read_sdr().
read_userport_sp2()
uint8_t read_userport_sp2 (uint8_t orig)
Referenced by read_sdr().
set_userport_flag()
void set_userport_flag (uint8_t val)
use this function from userport device code to set the userport flag
Referenced by userport_printer_store_pa2().
store_userport_pa2()
void store_userport_pa2 (uint8_t val)
Referenced by do_reset_cia(), store_ciapa(), and undump_ciapa().
store_userport_pa3()
void store_userport_pa3 (uint8_t val)
Referenced by store_ciapa(), and undump_ciapa().
store_userport_pbx()
void store_userport_pbx (uint8_t val, int pulse)
Referenced by do_reset_cia(), pulse_ciapc(), store_ciapb(), and undump_ciapb().
store_userport_sp1()
void store_userport_sp1 (uint8_t val)
Referenced by store_sdr().
store_userport_sp2()
void store_userport_sp2 (uint8_t val)
Referenced by store_sdr().
userport_cmdline_options_init()
int userport_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
userport_device_register()
int userport_device_register (int id, userport_device_t * device)
register a device to be used in the userport system if possible
Referenced by interface_userport_init_resources(), parallel_cable_cpu_resources_init(), rsuser_resources_init(), userport_4bit_sampler_resources_init(), userport_8bss_resources_init(), userport_dac_resources_init(), userport_digimax_resources_init(), userport_io_sim_resources_init(), userport_joystick_cga_resources_init(), userport_joystick_hit_resources_init(), userport_joystick_hummer_resources_init(), userport_joystick_kingsoft_resources_init(), userport_joystick_oem_resources_init(), userport_joystick_pet_resources_init(), userport_joystick_starbyte_resources_init(), userport_joystick_synergy_resources_init(), userport_joystick_woj_resources_init(), userport_petscii_snespad_resources_init(), userport_rtc_58321a_resources_init(), userport_rtc_ds1307_resources_init(), userport_spt_joystick_resources_init(), and userport_superpad64_resources_init().
userport_enable()
void userport_enable (int val)
Referenced by c64model_set().
userport_get_active_state()
int userport_get_active_state (void)
userport_get_device()
int userport_get_device (void)
Referenced by drv_ascii_select(), drv_nl10_select(), and drv_raw_select().
userport_get_device_type_desc()
const char * userport_get_device_type_desc (int type)
Get short description of of userport device type.
Parameters
[in] type userport device type
Referenced by create_device_model().
userport_get_valid_devices()
userport_desc_t * userport_get_valid_devices (int sort)
Referenced by build_userport_string(), and create_device_model().
userport_port_register()
void userport_port_register (userport_port_props_t * props)
Referenced by machine_register_userport().
userport_powerup()
void userport_powerup (void)
Referenced by machine_specific_powerup().
userport_reset()
void userport_reset (void)
Referenced by machine_specific_reset().
userport_reset_end()
void userport_reset_end (void)
userport_reset_start()
void userport_reset_start (void)
userport_resources_init()
int userport_resources_init (void)
Referenced by machine_resources_init().
userport_snapshot_read_module()
int userport_snapshot_read_module (snapshot_t * s)
Referenced by c64_snapshot_read().
userport_snapshot_write_module()
int userport_snapshot_write_module (snapshot_t * s)
Referenced by c64_snapshot_write().