x128: arch/shared/archdep_tick.h File Reference
archdep_tick.h File Reference
Relating to the management of time.
#include <stdint.h>
Macros
#define MILLI_PER_SECOND (1000)
#define MICRO_PER_SECOND (1000 * 1000)
#define NANO_PER_SECOND (1000 * 1000 * 1000)
#define TICK_PER_SECOND (MICRO_PER_SECOND)
#define TICK_TO_MILLI(tick) ((uint32_t) (uint64_t)((double)(tick) * ((double)MILLI_PER_SECOND / TICK_PER_SECOND)))
#define TICK_TO_MICRO(tick) ((uint32_t) (uint64_t)((double)(tick) * ((double)MICRO_PER_SECOND / TICK_PER_SECOND)))
#define TICK_TO_NANO(tick) ((uint64_t) (uint64_t)((double)(tick) * ((double)NANO_PER_SECOND / TICK_PER_SECOND)))
#define NANO_TO_TICK(nano) ((tick_t) (uint64_t)((double)(nano) / ((double)NANO_PER_SECOND / TICK_PER_SECOND)))
Typedefs
typedef uint32_t tick_t
Using a 32-bit type for tick_t prevents wraparound bugs on platforms with 32-bit timers.
Functions
void tick_init (void)
tick_t tick_per_second (void)
number of ticks per second
tick_t tick_now (void)
Get time in ticks.
tick_t tick_now_after (tick_t previous_tick)
Get time in ticks, compensating for the +/- 1 tick that is possible on Windows.
tick_t tick_now_delta (tick_t previous_tick)
Get number of ticks since a previous tick, compensating for the +/- 1 tick that is possible on Windows.
void tick_sleep (tick_t delay)
Sleep a number of ticks.
Detailed Description
Relating to the management of time.
Author
David Hogan david.nosp@m..q.h.nosp@m.ogan@.nosp@m.gmai.nosp@m.l.com
Macro Definition Documentation
MICRO_PER_SECOND
#define MICRO_PER_SECOND (1000 * 1000)
MILLI_PER_SECOND
#define MILLI_PER_SECOND (1000)
NANO_PER_SECOND
#define NANO_PER_SECOND (1000 * 1000 * 1000)
NANO_TO_TICK
#define NANO_TO_TICK (nano) ((tick_t) (uint64_t)((double)(nano) / ((double)NANO_PER_SECOND / TICK_PER_SECOND)))
TICK_PER_SECOND
#define TICK_PER_SECOND (MICRO_PER_SECOND)
TICK_TO_MICRO
#define TICK_TO_MICRO (tick) ((uint32_t) (uint64_t)((double)(tick) * ((double)MICRO_PER_SECOND / TICK_PER_SECOND)))
TICK_TO_MILLI
#define TICK_TO_MILLI (tick) ((uint32_t) (uint64_t)((double)(tick) * ((double)MILLI_PER_SECOND / TICK_PER_SECOND)))
TICK_TO_NANO
#define TICK_TO_NANO (tick) ((uint64_t) (uint64_t)((double)(tick) * ((double)NANO_PER_SECOND / TICK_PER_SECOND)))
Typedef Documentation
tick_t
typedef uint32_t tick_t
Using a 32-bit type for tick_t prevents wraparound bugs on platforms with 32-bit timers.
Function Documentation
tick_init()
void tick_init (void)
Referenced by main_program().
tick_now()
tick_t tick_now (void)
Get time in ticks.
Referenced by network_hook_connected_send(), network_test_delay(), render(), statusbar_speed_widget_update(), tick_now_after(), tick_sleep(), vsync_do_end_of_line(), vsync_do_vsync(), and vsync_should_skip_frame().
tick_now_after()
tick_t tick_now_after (tick_t previous_tick)
Get time in ticks, compensating for the +/- 1 tick that is possible on Windows.
Referenced by network_hook_connected_receive(), network_hook_connected_send(), tick_now_delta(), vsync_do_end_of_line(), and vsync_do_vsync().
tick_now_delta()
tick_t tick_now_delta (tick_t previous_tick)
Get number of ticks since a previous tick, compensating for the +/- 1 tick that is possible on Windows.
Referenced by network_test_delay(), tick_sleep(), and vsync_do_vsync().
tick_per_second()
tick_t tick_per_second (void)
number of ticks per second
Referenced by load_snapshot_trap(), network_test_delay(), save_snapshot_trap(), set_timer_speed(), sound_flush(), statusbar_speed_widget_update(), ui_extend_image_dialog(), ui_jam_dialog(), ui_pause_loop_iteration(), uimon_get_string(), update_performance_metrics(), vsync_do_end_of_line(), and vsync_init().
tick_sleep()
void tick_sleep (tick_t sleep_ticks)
Sleep a number of ticks.
Sleep a number of ticks.