x128: arch/gtk3/uicompiletimefeatures.c File Reference
uicompiletimefeatures.c File Reference
Dialog to display compile time features.
#include "vice.h"
#include <gtk/gtk.h>
#include "widgethelpers.h"
#include "debug_gtk3.h"
#include "machine.h"
#include "vicefeatures.h"
#include "ui.h"
#include "uiactions.h"
#include "uicompiletimefeatures.h"
Enumerations
enum {
COL_DESCR = 0 ,
COL_SYMBOL ,
COL_ISDEFINED
}
Column indexes.
Functions
static void on_destroy (GtkDialog *dialog, gpointer unused)
Handler for the 'destroy' event of the dialog.
static void on_response (GtkDialog *dialog, gint response_id, gpointer user_data)
Handler for the 'response' event of the dialog.
static int sort_symbol_func (GtkTreeModel *model, GtkTreeIter *a, GtkTreeIter *b, gpointer data)
Sort callback for column data.
static GtkTreeStore * create_store (void)
Create tree model with compile time features.
static GtkWidget * create_content_widget (void)
Create listview with compile time features.
void uicompiletimefeatures_dialog_show (void)
Show list of compile time features.
Detailed Description
Dialog to display compile time features.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
anonymous enum
anonymous enum
Column indexes.
Enumerator
COL_DESCR
Symbol description.
COL_SYMBOL
Symbol name in config.h.
COL_ISDEFINED
Symbol is defined.
Function Documentation
create_content_widget()
static GtkWidget * create_content_widget (void) static
Create listview with compile time features.
Returns
GtkScrolledWindow
Referenced by uicompiletimefeatures_dialog_show().
create_store()
static GtkTreeStore * create_store (void) static
Create tree model with compile time features.
Returns
GtkTreeStore
Referenced by create_content_widget().
on_destroy()
static void on_destroy (GtkDialog * dialog, gpointer unused) static
Handler for the 'destroy' event of the dialog.
Parameters
[in] dialog dialog triggering the event
[in] unused extra event data (unused)
Referenced by uicompiletimefeatures_dialog_show().
on_response()
static void on_response (GtkDialog * dialog, gint response_id, gpointer user_data) static
Handler for the 'response' event of the dialog.
Parameters
[in,out] dialog dialog triggering the event
[in] response_id response ID
[in] user_data extra event data (unused)
Referenced by uicompiletimefeatures_dialog_show().
sort_symbol_func()
static int sort_symbol_func (GtkTreeModel * model, GtkTreeIter * a, GtkTreeIter * b, gpointer data) static
Sort callback for column data.
Parameters
[in,out] model tree model
[in] a tree iterator to first element
[in] b tree iterator to second element
[in] data column ID
Returns
0 if equal, -1 if a < b, 1 if a > b
Referenced by create_content_widget().
uicompiletimefeatures_dialog_show()
void uicompiletimefeatures_dialog_show (void)
Show list of compile time features.
Referenced by help_compile_time_action().