vsid: log.h File Reference
log.h File Reference
#include <stdio.h>
Macros
#define LOG_LEVEL_NONE 0x00
#define LOG_ERR ((log_t)-1)
#define LOG_DEFAULT ((log_t)-2)
Typedefs
typedef signed int log_t
Functions
int log_resources_init (void)
void log_resources_shutdown (void)
int log_cmdline_options_init (void)
int log_init (void)
int log_init_with_fd (FILE *f)
log_t log_open (const char *id)
int log_close (log_t log)
void log_close_all (void)
void log_enable (int on)
int log_set_silent (int n)
int log_set_verbose (int n)
int log_early_init (int argc, char **argv)
int log_message (log_t log, const char *format,...) VICE_ATTR_PRINTF2
int log_warning (log_t log, const char *format,...) VICE_ATTR_PRINTF2
int log_error (log_t log, const char *format,...) VICE_ATTR_PRINTF2
int log_debug (const char *format,...) VICE_ATTR_PRINTF
int log_verbose (const char *format,...) VICE_ATTR_PRINTF
Macro Definition Documentation
LOG_DEFAULT
#define LOG_DEFAULT ((log_t)-2)
LOG_ERR
#define LOG_ERR ((log_t)-1)
LOG_LEVEL_NONE
#define LOG_LEVEL_NONE 0x00
Typedef Documentation
log_t
typedef signed int log_t
Function Documentation
log_close()
int log_close (log_t log)
Referenced by ata_shutdown(), log_close_all(), tapecart_enable(), and ui_hotkeys_shutdown().
log_close_all()
void log_close_all (void)
Referenced by cmdline_help(), and machine_shutdown().
log_cmdline_options_init()
int log_cmdline_options_init (void)
Referenced by init_cmdline_options().
log_debug()
int log_debug (const char * format, ...)
Referenced by aiff_close(), cbmdos_command_parse(), cbmdos_command_parse_plus(), dma_maincpu_steal_cycles(), eeprom_close_image(), eeprom_open_image(), ffmpegexedrv_close(), ffmpegexedrv_init_file(), ffmpegexedrv_open_video(), find_next_directory_sector(), handle_fetch_sprite(), iec_close_sequential(), iff_close(), In1_ATN_false(), In1_DAV_true(), interrupt_fixup_int_clk(), interrupt_set_irq(), interrupt_set_nmi(), m93c86_close_image(), m93c86_flush_image(), m93c86_open_image(), m93c86_save_image(), machine_window_create(), mmc_execute_cmd(), network_connect_client(), network_server_connect_trap(), network_test_delay(), OPet_NRFD_true(), parallel_restore_clr_atn(), parallel_restore_set_atn(), set_sid_engine(), set_sid_model(), tap_cbm_read_block(), tap_cbm_read_block_once(), tap_find_pilot(), tap_get_pulse(), tap_read_file(), tap_skip_file(), tap_tt_read_block(), tap_tt_skip_pilot(), unexpected(), vdrive_attach_image(), vdrive_change_part(), vdrive_command_block(), vdrive_command_chpart(), vdrive_command_execute(), vdrive_command_lockunlock(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_renameheader(), vdrive_command_renamepart(), vdrive_command_scratch(), vdrive_command_set_error(), vdrive_command_time(), vdrive_command_u1a2b(), vdrive_dir_create_slot(), vdrive_dir_find_first_slot(), vdrive_dir_find_next_slot(), vdrive_dir_first_directory(), vdrive_dir_part_find_next_slot(), vdrive_dir_part_first_directory(), vdrive_flush(), vdrive_iec_flush(), vdrive_iec_open(), vdrive_iec_read(), vdrive_iec_write(), vdrive_log_to_phy(), vdrive_read_sector(), vdrive_refresh(), vdrive_rel_close(), vdrive_rel_listen(), vdrive_rel_open(), vdrive_rel_open_new(), vdrive_rel_position_internal(), vdrive_rel_read(), vdrive_switch(), vdrive_write_sector(), vhk_parser_parse(), vicii_raster_draw_alarm_handler(), video_alloc_picture(), video_render_main(), video_render_pal_ntsc_main(), voc_close(), vsid_state_print_tunes_played_unlocked(), vsync_do_vsync(), wav_close(), zmbvdrv_close(), zmbvdrv_init_file(), and zmbvdrv_record().
log_early_init()
int log_early_init (int argc, char ** argv)
Referenced by archdep_init().
log_enable()
void log_enable (int on)
Referenced by settings_monitor_widget_create().
log_error()
int log_error (log_t log, const char * format, ...)
Referenced by _limit_longname(), _rs232net_getc(), _rs232net_putc(), acia_set_device(), add_predef_symbols(), aifc_handle_comm(), aifc_handle_ssnd(), aiff_handle_comm(), aiff_handle_ssnd(), alarm_log_too_many_alarms(), archdep_create_user_cache_dir(), archdep_create_user_config_dir(), archdep_create_user_state_dir(), archdep_expand_path(), archdep_mkdir(), archdep_mkdir_recursive(), archdep_open_default_log_file(), archdep_path_is_relative(), archdep_program_path(), archdep_spawn(), archdep_tmpnam(), argv_fallback(), attach_disk_image(), autostart_autodetect(), autostart_disable(), autostart_disk(), autostart_prg(), autostart_prg_perform_injection(), autostart_prg_with_disk_image(), browse_filename_callback(), c64_snapshot_read(), c64_snapshot_read_module(), c64_snapshot_read_rom_module(), c64rom_load_basic(), c64rom_load_chargen(), c64rom_load_kernal(), cart_image_widget_new(), charset_petconv_stralloc(), charset_petconvstring(), charset_ucs_to_utf8(), check_tx_buffer(), ciacore_snapshot_read_module(), close_pr(), combo_str_model_append(), create_css_provider(), create_model(), create_shader(), create_shader_program(), crt_control_widget_create(), crt_open(), crt_preview_widget_update(), custom_get_display_value(), detach_disk_image(), disk_image_check_for_d1m(), disk_image_check_for_d2m(), disk_image_check_for_d4m(), disk_image_check_for_d64(), disk_image_check_for_d67(), disk_image_check_for_d80(), disk_image_check_for_d81(), disk_image_check_for_d82(), disk_image_check_for_dhd(), disk_image_check_for_gcr(), disk_image_check_for_p64(), disk_image_check_min_block(), disk_image_close(), disk_image_media_create(), disk_image_media_destroy(), disk_image_open(), disk_image_read_sector(), disk_image_size(), disk_image_write_half_track(), disk_image_write_sector(), do_attach(), do_autostart(), do_smart_attach(), drag_data_get_filename(), draw(), drive_image_detach(), drive_snapshot_read_image_module(), drivemem_ioreg_list_get(), driverom_load(), driverom_load_images(), driverom_snapshot_read(), drv_1520_init(), drv_2022_open(), drv_4023_open(), drv_8023_open(), drv_mps801_open(), drv_mps802_open(), drv_mps803_init(), drv_mps803_open(), drv_nl10_init(), drv_nl10_init_charset(), event_alarm_handler(), event_box_motion_cb(), event_playback_event_list(), event_record_attach_in_list(), event_record_in_list(), event_record_start_trap(), expected_header_error(), fasttx_nibble_advance(), ffmpegexe_soundmovie_encode(), ffmpegexedrv_open_audio(), file_load_sample(), file_system_detach_disk_internal(), file_system_get_vdrive(), file_system_set_serial_hooks(), fliplist_load_list(), flush_pr(), fopen_or_pipe(), fork_coproc(), fsdevice_get_path(), fsdrive_snapshot_read_module(), fsimage_close(), fsimage_create(), fsimage_create_dhd(), fsimage_create_dxm(), fsimage_create_dxx(), fsimage_create_gcr(), fsimage_create_p64(), fsimage_dxx_read_sector(), fsimage_dxx_write_half_track(), fsimage_dxx_write_sector(), fsimage_gcr_read_half_track(), fsimage_gcr_read_sector(), fsimage_gcr_seek_half_track(), fsimage_gcr_write_half_track(), fsimage_gcr_write_sector(), fsimage_open(), fsimage_p64_read_half_track(), fsimage_p64_read_sector(), fsimage_p64_write_half_track(), fsimage_p64_write_sector(), fsimage_p64_write_track(), fsimage_read_p64_image(), fsimage_read_sector(), fsimage_write_p64_image(), fsimage_write_sector(), get_keyset_resources(), get_resource_chip_mode(), gfxoutput_get_driver(), handle_aifc_file(), handle_aiff_file(), handle_close(), handle_close_action(), handle_file_type(), handle_iff_file(), handle_voc_file(), handle_wav_file(), have_output_file(), help_manual_action(), iff_handle_body(), iff_handle_chan(), iffdrv_open(), init_main(), init_raster(), initcmdline_check_attach(), initcmdline_check_psid(), install_trap(), interface_serial_attach(), interrupt_log_wrong_nirq(), interrupt_log_wrong_nnmi(), io_source_register(), kbd_limit_pointers(), keyboard_parse_entry(), keyboard_parse_keyword(), keyboard_set_keyboard_mapping(), keyboard_set_keyboard_type(), keyboard_set_keymap_index(), keyset_dialog_show(), kill_coproc(), load_keymap_file(), load_prg(), load_resource_file(), load_tcrt(), m3u_append_comment(), m3u_append_newline(), m3u_append_string(), m3u_create(), m3u_open(), m3u_parse(), m3u_set_playlist_title(), m93c86_write_clock(), machine_bus_device_detach(), machine_change_timing(), main_loop_forever(), main_program(), maincpu_mainloop(), mediator_new(), mixer_widget_create(), mon_disassemble_lines(), mon_evaluate_address_range(), mon_evaluate_conditional(), mon_get_mem_val_ex(), mon_get_mem_val_ex_nosfx(), mon_playback_commands(), mon_print_conditional(), mon_register_get_val(), mon_register_print(), mon_register_print_ex(), mon_register_set_val(), monitor_binary_activate(), monitor_network_activate(), monitor_open(), mouse_button(), mus_load_file(), native_console_open(), network_client_connect_trap(), network_create_event_list(), network_server_connect_trap(), on_custom_changed(), on_enable_toggled(), on_exp_changed(), on_flush_clicked(), on_focus_in_event(), on_launcher_clicked(), on_model_toggled(), on_netplay_notify_active(), on_radio_toggled(), on_response(), on_save_response(), on_scale_int_changed(), on_spin_button_value_changed(), on_window_state_event(), open_pr(), Out1_NRFD_false(), output_graphics_line_data(), palette_copy(), palette_get_info_list(), palette_load(), palette_load_core(), parallelcommand(), pcxdrv_open(), populate_tree_model(), print_cbm_char(), printer_driver_widget_create(), printer_output_device_widget_create(), printer_output_mode_widget_create(), psid_init_driver(), psid_load_file(), remove_checkpoint_from_list(), remove_trap(), render_thread_create(), resource_item_isdefault(), resource_scale_int_new_helper(), resource_spin_int_new_helper(), resources_read_item_from_file(), resources_set_event_safe(), resources_set_value_event(), romset_file_load(), rs232net_close(), rs232net_get_status(), rs232net_getc(), rs232net_open(), save_filename_callback(), save_log_io_error(), save_screenshot_vsync_callback(), screenshot_auto_screenshot_vsync_callback(), screenshot_create_datetime_string(), screenshot_create_quickscreenshot_filename(), screenshot_get_quickscreenshot_format(), screenshot_line_data(), screenshot_record(), screenshot_save(), screenshot_save_core(), serialcommand(), set_autosave_screenshot_format(), set_kernal_revision(), set_keyset_resources(), set_tapeport_device(), snapshot_display_error(), sound_register_device(), spi_flash_write_clock(), spi_flash_write_select(), start_ffmpeg_executable(), statusbar_append_led(), statusbar_append_widget(), statusbar_append_widget_end(), string_resource_item(), sysfile_load(), sysfile_open(), t64_get_current_file_record(), tap_header_read(), tape_image_attach_internal(), tape_image_detach_internal(), tape_internal_open_tape_image(), tape_receive_trap(), tape_snapshot_read_module(), tape_snapshot_read_t64image_module(), tape_snapshot_read_tapimage_module(), tape_snapshot_write_t64image_module(), tape_snapshot_write_tapimage_module(), tapecart_logic_alarm_handler(), tapecart_read_snapshot(), tapecart_write_snapshot(), textfile_reader_read(), traps_remove(), try_attach_disk(), try_attach_tapecart(), ui_action_trigger(), ui_actions_register(), ui_create_main_window(), ui_get_active_canvas(), ui_hotkeys_init(), ui_hotkeys_load(), ui_hotkeys_save_as(), ui_init(), ui_settings_dialog_activate_node(), ui_statusbar_create(), uidata_get_bytes(), uidata_get_pixbuf(), uidata_get_pixbuf_at_scale(), uidata_init(), uimon_set_font(), uimonfb_window_resume(), util_file_load(), util_file_load_string(), util_file_save(), valid_window_id(), vdrive_attach_image(), vdrive_bam_clear_all(), vdrive_bam_create_empty_bam(), vdrive_bam_free_block_count(), vdrive_bam_get_interleave(), vdrive_bam_get_track_entry(), vdrive_bam_read_bam(), vdrive_bam_read_bam_block(), vdrive_bam_sector_free(), vdrive_bam_setup_bam(), vdrive_bam_write_bam(), vdrive_calculate_disk_half(), vdrive_command_block(), vdrive_command_execute(), vdrive_command_u1a2b(), vdrive_dir_get_interleave(), vdrive_iec_close(), vdrive_iec_read(), vdrive_iec_write(), vdrive_internal_open_fsimage(), vdrive_log_to_phy(), vdrive_rel_add_sector(), vdrive_rel_blocks_max(), vdrive_rel_has_super(), vdrive_rel_open_existing(), vdrive_rel_position_internal(), vdrive_rel_read(), vdrive_rel_record_max(), vdrive_rel_write(), vdrive_set_disk_geometry(), vhk_parser_error(), vhk_parser_parse(), vice_gtk3_css_provider_add(), vice_gtk3_css_provider_new(), vice_gtk3_css_provider_remove(), vice_gtk3_resource_combo_hex_new_range(), vice_gtk3_resource_spin_double_factory(), vice_gtk3_resource_spin_int_factory(), vice_gtk3_resource_spin_int_get(), vice_gtk3_resource_spin_int_new(), vice_gtk3_resource_spin_int_sync(), vice_network_send(), vice_network_server(), vice_opengl_renderer_create_child_view(), vice_opengl_renderer_set_vsync(), vicii_color_update_palette(), vicii_snapshot_read_module(), video_calc_ycbcrtable(), video_canvas_init(), video_render_crt_mono_main(), video_render_main(), video_render_rgbi_main(), voc_handle_extra_info(), voc_handle_ignore(), voc_handle_silence(), voc_handle_sound_1(), voc_handle_sound_2(), voc_handle_sound_9(), voc_handle_text(), warp(), write_initial_audio_frames(), write_video_frame(), z80_maincpu_loop(), zfile_compress(), and zmbvdrv_open_audio().
log_init()
int log_init (void)
Referenced by main_program().
log_init_with_fd()
int log_init_with_fd (FILE * f)
log_message()
int log_message (log_t log, const char * format, ...)
Referenced by actually_exit(), advance_hasdisk(), advance_hassnapshot(), advance_hastape(), advance_waitloading(), advance_waitloadready(), advance_waitsearchingfor(), archdep_default_sysfile_pathlist(), ata_image_attach(), ata_image_detach(), autostart_advance(), autostart_autodetect(), autostart_disk(), autostart_done(), autostart_finish(), autostart_prg(), autostart_prg_perform_injection(), autostart_prg_with_virtual_fs(), autostart_reset(), autostart_snapshot(), autostart_tape(), break64(), bresenham(), bresenham_par(), c64_256k_activate(), c64_256k_deactivate(), c64rom_print_kernal_info(), check_pulsebuffer_size(), check_rom_area(), ciacore_read(), ciacore_snapshot_read_module(), ciacore_snapshot_write_module(), ciacore_store_internal(), cmd_crc32_flash(), cmd_dir_lookup(), cmd_dir_setparams(), cmd_erase_flash_64k(), cmd_erase_flash_block(), cmd_read_flash(), cmd_read_flash_fast(), cmd_write_flash(), cmd_write_loadinfo(), cmdline_log_active(), cmdmode_dispatch_command(), cmdmode_write_flash_page(), cpu_reset(), create_shader_program(), d01f_read(), disk_eof_callback(), disk_image_gap_size(), disk_image_header_gap_size(), disk_image_raw_track_size(), disk_image_sector_per_track(), disk_image_speed_map(), disk_image_sync_size(), draw(), drive_init(), drive_jam(), drivecpu65c02_snapshot_read_module(), drivecpu65c02_wake_up(), drivecpu_snapshot_read_module(), drivecpu_wake_up(), driver_select(), driver_select_close(), driver_select_flush(), driver_select_formfeed(), driver_select_open(), drv_1520_close(), drv_1520_flush(), drv_1520_formfeed(), drv_1520_init(), drv_1520_init_resources(), drv_1520_open(), drv_1520_putc(), drv_1520_shutdown(), drv_ascii_flush(), drv_ascii_formfeed(), drv_ascii_putc(), drv_nl10_init(), eject(), file_load_sample(), fliplist_add_image(), fliplist_load_list(), fliplist_remove(), fork_coproc(), fsdevice_error(), fsdevice_flush_ba(), fsdevice_flush_be(), fsdevice_flush_bf(), fsdevice_flush_bp(), fsdevice_flush_br(), fsdevice_flush_bw(), fsdevice_flush_u1(), fsdevice_flush_u2(), fsdevice_open(), fsdevice_open_buffer(), fsdevice_set_directory(), fsimage_open(), get_acia_bps(), interrupt_maincpu_trigger_trap(), io_source_log_collisions(), io_source_msg_detach_all(), io_source_msg_detach_last(), kbd_debug_widget_update(), keyboard_custom_key_func_by_keysym(), keyboard_parse_keymap(), kill_coproc(), lib_rand_printseed(), load_resource_file(), load_snapshot_trap(), machine_jam(), machine_reset(), machine_vsync_hook(), machine_window_create(), main_loop_forever(), main_program(), mon_playback_commands(), monitor_binary_process_checkpoint_set(), monitor_binary_process_command(), monitor_binary_process_mem_get(), monitor_binary_process_mem_set(), monitor_binary_process_registers_available(), monitor_binary_process_registers_get(), monitor_binary_process_registers_set(), monitor_binary_receive(), monitor_network_receive(), my_set_int(), myacia_store(), on_key_release_event(), opcode_ed(), palette_load(), parallel_trap_attention(), parallel_trap_receivebyte(), parallel_trap_sendbyte(), playback_end_file(), playback_next_command(), plot(), plus256k_activate(), plus256k_deactivate(), plus60k_activate(), plus60k_deactivate(), pop_irq_state(), print_char_plot(), print_char_select_scribe(), printfontinfo(), psid_init_driver(), psid_init_tune(), psid_load_file(), push_irq_state(), reboot_for_autostart(), render(), render_thread_create(), render_thread_initiate_shutdown(), render_thread_join(), render_thread_push_job(), reset_abs_origin(), resid_init(), resources_dump(), resources_log_active(), resources_save(), resources_set_defaults(), restore_drive_emulation_state(), riotcore_read(), riotcore_snapshot_read_module(), romset_archive_load(), romset_archive_save(), romset_file_load(), romset_file_save(), screenshot_auto_screenshot_vsync_callback(), sdl_init(), serial_iec_device_disable(), serial_iec_device_enable(), serial_iec_device_exec_main(), serial_iec_device_init(), serial_iec_device_reset(), set_c64_256k_base(), set_device_traps_state(), set_iec_device_state(), set_latch_bit(), set_plus60k_base(), set_printer_driver(), set_true_drive_emulation_mode(), set_warp_mode(), setup_for_disk(), setup_for_disk_ready(), setup_for_prg_vfs(), show_fliplist(), sound_error(), sound_init(), sound_open(), sounddev_close(), start_ffmpeg_executable(), sysfile_load(), tap_header_read(), tape_image_attach_internal(), tape_image_detach_internal(), tapecart_logic_alarm_handler(), tapecart_store_motor(), textfile_reader_close(), tpicore_store(), try_attach_disk(), ui_hotkeys_init(), ui_hotkeys_load_user_default(), ui_hotkeys_load_vice_default(), ui_hotkeys_save_as(), ui_hotkeys_shutdown(), uimon_set_font(), vdrive_bam_alloc_first_free_sector(), vdrive_command_set_error(), vdrive_get_max_sectors(), vdrive_iec_open(), vdrive_snapshot_module_read(), vhk_filename_set(), vhk_parser_do_clear(), vhk_parser_do_undef(), vhk_parser_handle_mapping(), viacore_read(), vice_network_address_generate_ipv4(), vice_network_address_generate_ipv6(), vice_opengl_renderer_create_child_view(), vice_opengl_renderer_set_vsync(), write_lines(), write_pr(), and z80_maincpu_loop().
log_open()
log_t log_open (const char * id)
Referenced by ata_init(), autostart_init(), c64_256k_init(), ciacore_init(), disk_image_init(), drive_image_init(), drive_init(), driver_select_init(), driverom_init(), drv_1520_init(), drv_ascii_init(), drv_mps803_init(), drv_nl10_init(), event_init(), file_system_init(), fileaudio_init(), fsdrive_init(), fsimage_create_init(), fsimage_dxx_init(), fsimage_gcr_init(), fsimage_init(), fsimage_p64_init(), fsimage_probe_init(), gfxoutput_init(), iecrom_init(), interface_serial_init(), keyboard_init(), machine_specific_init(), mem_load(), mouse_ps2_init(), myacia_init(), mypia_init(), palette_init(), pc8477d_init(), plus256k_init(), plus60k_init(), psid_load_file(), realimage_init(), riotcore_init(), romset_init(), rs232net_init(), screenshot_init(), serial_iec_device_init(), serial_init(), sound_init(), tap_init(), tape_init(), tapecart_enable(), traps_init(), ui_hotkeys_init(), vdrive_command_init(), vdrive_dir_init(), vdrive_iec_init(), vdrive_init(), vdrive_internal_init(), vdrive_rel_init(), vdrive_snapshot_init(), viacore_init(), vicii_init(), video_init(), wd1770d_init(), and zinit().
log_resources_init()
int log_resources_init (void)
Referenced by init_resources().
log_resources_shutdown()
void log_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
log_set_silent()
int log_set_silent (int n)
Referenced by main_program().
log_set_verbose()
int log_set_verbose (int n)
Referenced by log_early_init(), and main_program().
log_verbose()
int log_verbose (const char * format, ...)
Referenced by disk_image_attach_log(), disk_image_check_log(), disk_image_detach_log(), install_trap(), keymap_resources_init(), mousedrv_mouse_changed(), p00_open(), remove_trap(), resources_set_defaults(), set_kernal_revision(), set_kernal_rom_name(), and traps_add().
log_warning()
int log_warning (log_t log, const char * format, ...)
Referenced by ata_image_attach(), ata_snapshot_read_module(), c64_glue_snapshot_read_module(), c64rom_print_basic_info(), c64rom_print_kernal_info(), check_and_skip_chunk(), check_modifiers(), check_resource_file_version(), drive_move_head(), drv_common_open(), drv_nl10_init_charset(), fdd_seek_pulse(), file_chooser_convert_from_locale(), file_chooser_convert_to_locale(), file_load_sample(), fliplist_load_list(), getfontdesc(), handle_aifc_file(), handle_aiff_file(), handle_control_sequence(), handle_esc_control_sequence(), handle_file_type(), iecrom_do_1541_checksum(), init_main(), keyboard_parse_entry(), load_resource_file(), main_program(), mon_get_bank_flags_for_bank(), mon_get_bank_index_for_bank(), mps_engine_putc(), palette_load_core(), parallelcommand(), psid_init_tune(), receive_1bit(), resid_init(), resources_get_default_value(), resources_get_int(), resources_get_string(), resources_get_value(), resources_set_default_int(), resources_set_default_string(), resources_set_int(), resources_set_string(), resources_set_value(), resources_set_value_string(), resources_toggle(), resources_write_item_to_file(), resources_write_item_to_string(), romset_archive_item_save(), romset_archive_load(), romset_archive_save(), romset_file_load(), romset_file_save(), serialcommand(), set_file_system_device(), set_relative_speed(), snapshot_open(), sound_open(), sound_run_sound(), sound_suspend(), statusbar_led_widget_create(), store_char(), store_char_nlq(), sysfile_load(), t64_header_read(), t64_open(), tap_close(), tap_header_read(), tape_receive_trap(), tape_receive_trap_plus4(), update_virtual_modifier_flags(), vdrive_command_block(), vdrive_command_memory_exec(), vdrive_command_memory_read(), vdrive_command_memory_write(), vdrive_iec_open(), vhk_parser_do_warning(), vhk_parser_warning(), vsid_tune_info_widget_set_song_lengths(), vsid_tune_info_widget_set_song_lengths_md5(), and warn_ctrl_code().