vsid: core/tpicore.c File Reference
tpicore.c File Reference
#include "vice.h"
#include <stdio.h>
#include "lib.h"
#include "log.h"
#include "monitor.h"
#include "snapshot.h"
#include "tpi.h"
#include "types.h"
Macros
#define irq_active (tpi_context->c_tpi[TPI_AIR])
#define irq_latches (tpi_context->c_tpi[TPI_PC])
#define irq_mask (tpi_context->c_tpi[TPI_DDPC])
#define irq_mode (tpi_context->c_tpi[TPI_CREG] & 1)
#define irq_priority (tpi_context->c_tpi[TPI_CREG] & 2)
#define IS_CA_MODE() ((tpi_context->c_tpi[TPI_CREG] & 0x20) == 0x00)
#define IS_CA_PULSE_MODE() ((tpi_context->c_tpi[TPI_CREG] & 0x30) == 0x10)
#define IS_CA_TOGGLE_MODE() ((tpi_context->c_tpi[TPI_CREG] & 0x30) == 0x00)
#define IS_CB_MODE() ((tpi_context->c_tpi[TPI_CREG] & 0x80) == 0x00)
#define IS_CB_PULSE_MODE() ((tpi_context->c_tpi[TPI_CREG] & 0xc0) == 0x40)
#define IS_CB_TOGGLE_MODE() ((tpi_context->c_tpi[TPI_CREG] & 0xc0) == 0x00)
#define TPI_DUMP_VER_MAJOR 1
#define TPI_DUMP_VER_MINOR 0
Functions
static void set_latch_bit (tpi_context_t *tpi_context, int bit)
Handle irq stack etc.
static void pop_irq_state (tpi_context_t *tpi_context)
static uint8_t push_irq_state (tpi_context_t *tpi_context)
void tpicore_reset (tpi_context_t *tpi_context)
void tpicore_store (tpi_context_t *tpi_context, uint16_t addr, uint8_t byte)
uint8_t tpicore_read (tpi_context_t *tpi_context, uint16_t addr)
uint8_t tpicore_peek (tpi_context_t *tpi_context, uint16_t addr)
void tpicore_set_int (tpi_context_t *tpi_context, int bit, int state)
void tpicore_restore_int (tpi_context_t *tpi_context, int bit, int state)
void tpicore_setup_context (tpi_context_t *tpi_context)
void tpicore_shutdown (tpi_context_t *tpi_context)
int tpicore_snapshot_write_module (tpi_context_t *tpi_context, snapshot_t *p)
FIXME!!! Error check.
int tpicore_snapshot_read_module (tpi_context_t *tpi_context, snapshot_t *p)
int tpicore_dump (tpi_context_t *tpi_context)
Variables
static const uint8_t pow2 [] = { 1, 2, 4, 8, 16 }
static int mytpi_debug = 0
Macro Definition Documentation
irq_active
#define irq_active (tpi_context->c_tpi[TPI_AIR])
irq_latches
#define irq_latches (tpi_context->c_tpi[TPI_PC])
irq_mask
#define irq_mask (tpi_context->c_tpi[TPI_DDPC])
irq_mode
#define irq_mode (tpi_context->c_tpi[TPI_CREG] & 1)
irq_priority
#define irq_priority (tpi_context->c_tpi[TPI_CREG] & 2)
IS_CA_MODE
#define IS_CA_MODE () ((tpi_context->c_tpi[TPI_CREG] & 0x20) == 0x00)
IS_CA_PULSE_MODE
#define IS_CA_PULSE_MODE () ((tpi_context->c_tpi[TPI_CREG] & 0x30) == 0x10)
IS_CA_TOGGLE_MODE
#define IS_CA_TOGGLE_MODE () ((tpi_context->c_tpi[TPI_CREG] & 0x30) == 0x00)
IS_CB_MODE
#define IS_CB_MODE () ((tpi_context->c_tpi[TPI_CREG] & 0x80) == 0x00)
IS_CB_PULSE_MODE
#define IS_CB_PULSE_MODE () ((tpi_context->c_tpi[TPI_CREG] & 0xc0) == 0x40)
IS_CB_TOGGLE_MODE
#define IS_CB_TOGGLE_MODE () ((tpi_context->c_tpi[TPI_CREG] & 0xc0) == 0x00)
TPI_DUMP_VER_MAJOR
#define TPI_DUMP_VER_MAJOR 1
TPI_DUMP_VER_MINOR
#define TPI_DUMP_VER_MINOR 0
Function Documentation
pop_irq_state()
static void pop_irq_state (tpi_context_t * tpi_context) static
Referenced by tpicore_store().
push_irq_state()
static uint8_t push_irq_state (tpi_context_t * tpi_context) static
Referenced by tpicore_read().
set_latch_bit()
static void set_latch_bit (tpi_context_t * tpi_context, int bit) static
Handle irq stack etc.
Referenced by tpicore_set_int(), and tpicore_store().
tpicore_dump()
int tpicore_dump (tpi_context_t * tpi_context)
tpicore_peek()
uint8_t tpicore_peek (tpi_context_t * tpi_context, uint16_t addr)
Todo:
FIXME: peek into register without any side effect
tpicore_read()
uint8_t tpicore_read (tpi_context_t * tpi_context, uint16_t addr)
tpicore_reset()
void tpicore_reset (tpi_context_t * tpi_context)
tpicore_restore_int()
void tpicore_restore_int (tpi_context_t * tpi_context, int bit, int state)
tpicore_set_int()
void tpicore_set_int (tpi_context_t * tpi_context, int bit, int state)
tpicore_setup_context()
void tpicore_setup_context (tpi_context_t * tpi_context)
tpicore_shutdown()
void tpicore_shutdown (tpi_context_t * tpi_context)
tpicore_snapshot_read_module()
int tpicore_snapshot_read_module (tpi_context_t * tpi_context, snapshot_t * p)
tpicore_snapshot_write_module()
int tpicore_snapshot_write_module (tpi_context_t * tpi_context, snapshot_t * p)
FIXME!!! Error check.
tpicore_store()
void tpicore_store (tpi_context_t * tpi_context, uint16_t addr, uint8_t byte)
Referenced by tpicore_store().
Variable Documentation
mytpi_debug
int mytpi_debug = 0 static
Referenced by pop_irq_state(), push_irq_state(), set_latch_bit(), and tpicore_store().
pow2
const uint8_t pow2[] = { 1, 2, 4, 8, 16 } static
Referenced by pop_irq_state(), tpicore_restore_int(), tpicore_set_int(), and tpicore_store().