vsid: arch/gtk3/opengl_renderer.h File Reference
opengl_renderer.h File Reference
#include "vice.h"
#include <GL/glew.h>
#include <X11/Xlib.h>
#include <GL/glxew.h>
#include <stdbool.h>
#include "render_thread.h"
#include "videoarch.h"
Data Structures
struct vice_opengl_renderer_context_s
Rendering context for the OpenGL backend.
Typedefs
typedef struct vice_opengl_renderer_context_s vice_opengl_renderer_context_t
Rendering context for the OpenGL backend.
Functions
void vice_opengl_renderer_create_child_view (GtkWidget *widget, vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_resize_child_view (GtkWidget *widget, vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_destroy_child_view (vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_make_current (vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_set_viewport (vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_set_vsync (vice_opengl_renderer_context_t *context, bool enable_vsync)
void vice_opengl_renderer_render (vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_present_backbuffer (vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_clear_current (vice_opengl_renderer_context_t *context)
Variables
vice_renderer_backend_t vice_opengl_backend
A renderer that uses OpenGL to render to a native child window.
Typedef Documentation
vice_opengl_renderer_context_t
typedef struct vice_opengl_renderer_context_s vice_opengl_renderer_context_t
Rendering context for the OpenGL backend.
See also
video_canvas_s::renderer_context
Function Documentation
vice_opengl_renderer_clear_current()
void vice_opengl_renderer_clear_current (vice_opengl_renderer_context_t * context)
Referenced by on_widget_realized(), render(), and vice_opengl_renderer_create_child_view().
vice_opengl_renderer_create_child_view()
void vice_opengl_renderer_create_child_view (GtkWidget * widget, vice_opengl_renderer_context_t * context)
Referenced by on_widget_realized().
vice_opengl_renderer_destroy_child_view()
void vice_opengl_renderer_destroy_child_view (vice_opengl_renderer_context_t * context)
Referenced by on_widget_unrealized().
vice_opengl_renderer_make_current()
void vice_opengl_renderer_make_current (vice_opengl_renderer_context_t * context)
Referenced by on_widget_realized(), render(), and vice_opengl_renderer_create_child_view().
vice_opengl_renderer_present_backbuffer()
void vice_opengl_renderer_present_backbuffer (vice_opengl_renderer_context_t * context)
Referenced by render().
vice_opengl_renderer_render()
void vice_opengl_renderer_render (vice_opengl_renderer_context_t * context)
vice_opengl_renderer_resize_child_view()
void vice_opengl_renderer_resize_child_view (GtkWidget * widget, vice_opengl_renderer_context_t * context)
Referenced by on_widget_resized().
vice_opengl_renderer_set_viewport()
void vice_opengl_renderer_set_viewport (vice_opengl_renderer_context_t * context)
Referenced by render().
vice_opengl_renderer_set_vsync()
void vice_opengl_renderer_set_vsync (vice_opengl_renderer_context_t * context, bool enable_vsync)
Referenced by render().
Variable Documentation
vice_opengl_backend
vice_renderer_backend_t vice_opengl_backend extern
A renderer that uses OpenGL to render to a native child window.
Because OpenGL + GTK3 just doesn't work that well, this.
Referenced by machine_window_create().