vsid: arch/gtk3/hotkeys.c File Reference
hotkeys.c File Reference
Gtk3 custom hotkeys handling.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <inttypes.h>
#include "archdep.h"
#include "debug_gtk3.h"
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "parser.h"
#include "textfilereader.h"
#include "ui.h"
#include "uiapi.h"
#include "uiactions.h"
#include "uihotkeys.h"
#include "uimenu.h"
#include "util.h"
#include "version.h"
#include "vice_gtk3.h"
#include "hotkeys.h"
Functions
static gboolean valid_window_id (gint window_id)
Check if window ID is valid.
static gboolean handle_accelerator (GtkAccelGroup *accel_grp, GObject *acceleratable, guint keyval, GdkModifierType modifiers, gpointer action)
Callback that forwards accelerator codes.
static void connect_accelerator (int action, guint keysym, GdkModifierType modifier, bool unlocked)
Set up a closure to trigger UI action for a hotkey.
static void set_menu_item_accel (GtkWidget *item, uint32_t arch_keysym, uint32_t arch_modmask)
Set accelerator for menu item, using new API.
static void clear_menu_item_accel (GtkWidget *item)
Clear accelerator from runtime menu item.
gboolean vhk_gtk_remove_accelerator (guint keysym, GdkModifierType modifier)
Remove accelerator from global accelerator group.
void vhk_gtk_init_accelerators (GtkWidget *window)
Create accelerator group and add it to window.
gchar * vhk_gtk_get_accel_label_by_map (const ui_action_map_t *map)
Get accelerator label for hotkey in map.
gchar * vhk_gtk_get_accel_label_by_action (int action)
Get accelerator label for UI action, if any.
GtkWidget * vhk_gtk_get_menu_item_by_action_for_window (int action, int window_id)
Get runtime menu item for UI action and main window.
void vhk_gtk_set_menu_item_accel_label (GtkWidget *item, int action)
Set accelerator label to the hotkey associated with UI action.
void vhk_gtk_set_check_item_blocked (GtkWidget *item, gboolean checked)
Check/uncheck check menu item while blocking its handler.
void vhk_gtk_set_check_item_blocked_by_action (int action, gboolean checked)
Check/uncheck check menu item(s) mapped to UI action.
void vhk_gtk_set_check_item_blocked_by_action_for_window (int action, int window_id, gboolean checked)
Check/uncheck check menu item mapped to UI action for a window.
vhk_gtk_map_t * vhk_gtk_map_new (const ui_menu_item_t *decl)
Create gtk3-specific hotkey data object.
void vhk_gtk_map_free (vhk_gtk_map_t *arch_map)
Free memory used by gtk3-specific hotkey data object.
uint32_t ui_hotkeys_arch_modifier_to_arch (uint32_t vice_mod)
Virtual method for obtaining Gdk modifier mask from VICE modifier mask.
uint32_t ui_hotkeys_arch_modifier_from_arch (uint32_t arch_mod)
VICE modifier mask bit from GDK modifier mask bit.
uint32_t ui_hotkeys_arch_keysym_to_arch (uint32_t vice_keysym)
Translate VICE keysym to UI keysym.
uint32_t ui_hotkeys_arch_keysym_from_arch (uint32_t arch_keysym)
Translate UI keysym to VICE keysym.
uint32_t ui_hotkeys_arch_modmask_to_arch (uint32_t vice_modmask)
Translate a full modifier mask from VICE to Gdk.
uint32_t ui_hotkeys_arch_modmask_from_arch (uint32_t arch_modmask)
Translate a full modifier mask from Gdk to VICE.
void ui_hotkeys_arch_install_by_map (ui_action_map_t *map)
Install hotkey, see src/uiapi.h for docblock.
void ui_hotkeys_arch_remove_by_map (ui_action_map_t *map)
Remove hotkey, see src/uiapi.h for docblock.
void ui_hotkeys_arch_init (void)
Initialize Gtk3-specific hotkeys resources.
void ui_hotkeys_arch_shutdown (void)
Gtk3-specific hotkeys shutdown function.
Variables
static GtkAccelGroup * accel_group = NULL
Reference to the accelerator group.
Detailed Description
Gtk3 custom hotkeys handling.
Provides custom keyboard shortcuts for the Gtk3 UI.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
clear_menu_item_accel()
static void clear_menu_item_accel (GtkWidget * item) static
Clear accelerator from runtime menu item.
Parameters
[in] item runtime menu item
Referenced by ui_hotkeys_arch_remove_by_map().
connect_accelerator()
static void connect_accelerator (int action, guint keysym, GdkModifierType modifier, bool unlocked) static
Set up a closure to trigger UI action for a hotkey.
Create a closure to trigger UI action for keysym and modifier. This way hotkeys will work in fullscreen and also when there's no menu item associated with action.
Parameters
[in] action UI action ID
[in] keysym Gdk keysym
[in] modifier Gdk modifier mask
[in] unlocked connect accelator non-lockeding
Referenced by ui_hotkeys_arch_install_by_map().
handle_accelerator()
static gboolean handle_accelerator (GtkAccelGroup * accel_grp, GObject * acceleratable, guint keyval, GdkModifierType modifiers, gpointer action) static
Callback that forwards accelerator codes.
Parameters
[in] accel_grp accelerator group (unused)
[in] acceleratable ? (unused)
[in] keyval GDK keyval (unused)
[in] modifiers GDK key modifier(s) (unused)
[in] action UI action ID
Referenced by connect_accelerator().
set_menu_item_accel()
static void set_menu_item_accel (GtkWidget * item, uint32_t arch_keysym, uint32_t arch_modmask) static
Set accelerator for menu item, using new API.
Parameters
[in] item runtime menu item
[in] arch_keysym Gkd keysym
[in] arch_modmask Gdk modifier mask
Note
This only sets the item's accelerator, it does not connect any handler, the handler is set up during menu creation in uimenu.c.
Referenced by ui_hotkeys_arch_install_by_map().
ui_hotkeys_arch_init()
void ui_hotkeys_arch_init (void)
Initialize Gtk3-specific hotkeys resources.
Run UI-specific hotkeys initialization code.
Note
Does not initialize command line options or vice resources, that is done separately in hotkeys_cmdline_options_init() and hotkeys_resources_init().
ui_hotkeys_arch_install_by_map()
void ui_hotkeys_arch_install_by_map (ui_action_map_t * map)
Install hotkey, see src/uiapi.h for docblock.
Install hotkey.
Referenced by ui_hotkeys_install_by_map(), and ui_hotkeys_update_by_map().
ui_hotkeys_arch_keysym_from_arch()
uint32_t ui_hotkeys_arch_keysym_from_arch (uint32_t arch_keysym)
Translate UI keysym to VICE keysym.
Translate arch keysym to VICE keysysm.
Parameters
[in] arch_keysym UI-specific keysym
Returns
VICE-specific keysym
See also
src/arch/shared/hotkeys/vhkkeysyms.h
Referenced by dialog_accept_handler(), and ui_action_map_get_by_arch_hotkey().
ui_hotkeys_arch_keysym_to_arch()
uint32_t ui_hotkeys_arch_keysym_to_arch (uint32_t vice_keysym)
Translate VICE keysym to UI keysym.
Translate VICE keysym to arch keysysm.
Parameters
[in] vice_keysym VICE-specific keysym
Returns
UI-specific keysym
See also
src/arch/shared/hotkeys/vhkkeysyms.h
Referenced by ui_hotkeys_update_by_map(), and vhk_parser_get_keysym_and_modmask().
ui_hotkeys_arch_modifier_from_arch()
uint32_t ui_hotkeys_arch_modifier_from_arch (uint32_t arch_mod)
VICE modifier mask bit from GDK modifier mask bit.
Translate arch modifier to VICE modifier.
Parameters
[in] arch_mod GDK modifier mask bit
Returns
VICE modifier mask bit
Note
Returns different values on MacOS vs normal OSes.
Referenced by ui_hotkeys_arch_modmask_from_arch().
ui_hotkeys_arch_modifier_to_arch()
uint32_t ui_hotkeys_arch_modifier_to_arch (uint32_t vice_mod)
Virtual method for obtaining Gdk modifier mask from VICE modifier mask.
Translate VICE modifier to arch modifier.
Get GDK modifier mask bit from VICE modifier mask bit
Parameters
[in] vice_mod VICE modifier mask bit
Returns
GDK modifier mask bit
Note
Only works on single-bit values, for combined values we'll need another (UI-agnostic) function.
Referenced by ui_hotkeys_arch_modmask_to_arch(), and vhk_parser_get_keysym_and_modmask().
ui_hotkeys_arch_modmask_from_arch()
uint32_t ui_hotkeys_arch_modmask_from_arch (uint32_t arch_modmask)
Translate a full modifier mask from Gdk to VICE.
Translate arch modifier mask to VICE modifier mask.
Parameters
[in] arch_modmask Gdk modifier mask
Returns
VICE modifier mask
Todo:
We might be able to move this into shared/hotkeys, reducing the number of virtual methods required for a UI.
Referenced by dialog_accept_handler(), and ui_action_map_get_by_arch_hotkey().
ui_hotkeys_arch_modmask_to_arch()
uint32_t ui_hotkeys_arch_modmask_to_arch (uint32_t vice_modmask)
Translate a full modifier mask from VICE to Gdk.
Translate VICE modifier mask to arch modifier.
Parameters
[in] vice_modmask VICE modifier mask
Returns
Gdk modifier mask
Todo:
We might be able to move this into shared/hotkeys, reducing the number of virtual methods required for a UI.
Referenced by ui_hotkeys_update_by_map().
ui_hotkeys_arch_remove_by_map()
void ui_hotkeys_arch_remove_by_map (ui_action_map_t * map)
Remove hotkey, see src/uiapi.h for docblock.
Remove hotkey.
Referenced by ui_hotkeys_remove_all(), ui_hotkeys_remove_by_map(), and ui_hotkeys_update_by_map().
ui_hotkeys_arch_shutdown()
void ui_hotkeys_arch_shutdown (void)
Gtk3-specific hotkeys shutdown function.
Run UI-specific hotkeys shutdown code.
Implements virtual method in uiapi.h that's called on generic hotkeys shut down. Frees the Gtk3-specific hotkey data in the generic hotkeys array.
Referenced by ui_hotkeys_shutdown().
valid_window_id()
static gboolean valid_window_id (gint window_id) static
Check if window ID is valid.
Check if window_id is either PRIMARY_WINDOW or SECONDARY_WINDOW.
Logs an error if window_id is invalid.
Parameters
[in] window_id window ID
Referenced by vhk_gtk_get_menu_item_by_action_for_window(), and vhk_gtk_set_check_item_blocked_by_action_for_window().
vhk_gtk_get_accel_label_by_action()
gchar * vhk_gtk_get_accel_label_by_action (int action)
Get accelerator label for UI action, if any.
Parameters
[in] action UI action ID
Returns
accelerator label or `NULL when action not found or no hotkey exists for the action
Todo:
Rename
Referenced by isresethotkey(), mouse_grab_toggle_action(), and ui_create_main_window().
vhk_gtk_get_accel_label_by_map()
gchar * vhk_gtk_get_accel_label_by_map (const ui_action_map_t * map)
Get accelerator label for hotkey in map.
Parameters
[in] map hotkey map
Returns
accelerator label or NULL when no hotkey defined
Note
The value returned is allocated by Gtk and should be freed after use with g_free()
Todo:
Rename
Referenced by create_hotkeys_model(), and vhk_gtk_get_accel_label_by_action().
vhk_gtk_get_menu_item_by_action_for_window()
GtkWidget * vhk_gtk_get_menu_item_by_action_for_window (int action, int window_id)
Get runtime menu item for UI action and main window.
Parameters
[in] action UI action ID
[in] window_id window ID (PRIMARY_WINDOW or SECONDARY_WINDOW)
Returns
menu item or NULL when not found
!
Todo:
Nothing Gtk-specific in this function: could be moved to shared code and return a void*.
Referenced by actions_speed_setup_ui(), speed_cpu_custom_action(), and speed_fps_custom_action().
vhk_gtk_init_accelerators()
void vhk_gtk_init_accelerators (GtkWidget * window)
Create accelerator group and add it to window.
Parameters
[in] window top level window
Note
Allocating the accel group in ui_hotkeys_arch_init() cannot be done since it's too late in the UI setup process.
Referenced by ui_create_main_window().
vhk_gtk_map_free()
void vhk_gtk_map_free (vhk_gtk_map_t * arch_map)
Free memory used by gtk3-specific hotkey data object.
Free memory used by arch_map and its members.
Parameters
[in] arch_map gtk3-specific hotkey data object
Referenced by ui_hotkeys_arch_shutdown().
vhk_gtk_map_new()
vhk_gtk_map_t * vhk_gtk_map_new (const ui_menu_item_t * decl)
Create gtk3-specific hotkey data object.
Create object with a reference to the menu item declaration for a UI action and signal handler IDs to allow the UI code to block/unblock signal handlers. The menu item declaration contains a bool indicating whether to connect a signal handler directly or through the VICE locking mechanism. The signal handler IDs are used to temporarily block signal handlers from triggering when updating their menu items' state (e.g. check/radio buttons).
Parameters
[in] decl UI menu item declaration
Returns
new gtk3-specific hotkey data object
Note
Free object with vhk_map_gtk_free()
Referenced by ui_menu_add().
vhk_gtk_remove_accelerator()
gboolean vhk_gtk_remove_accelerator (guint keysym, GdkModifierType modifier)
Remove accelerator from global accelerator group.
Parameters
[in] keysym Gdk keysym
[in] modifier Gdk modifier mask
Returns
TRUE on success
Referenced by dialog_accept_handler(), on_menu_item_destroy(), and ui_hotkeys_arch_remove_by_map().
vhk_gtk_set_check_item_blocked()
void vhk_gtk_set_check_item_blocked (GtkWidget * item, gboolean checked)
Check/uncheck check menu item while blocking its handler.
Set a checkbox menu item's state while blocking the 'activate' handler so the handler won't recursively call itself.
Parameters
[in] item GtkCheckMenuItem instance
[in] checked new check button state
Referenced by vhk_gtk_set_check_item_blocked_by_action(), and vhk_gtk_set_check_item_blocked_by_action_for_window().
vhk_gtk_set_check_item_blocked_by_action()
void vhk_gtk_set_check_item_blocked_by_action (int action, gboolean checked)
Check/uncheck check menu item(s) mapped to UI action.
Set menu item or items (x128) that are registered for UI action to checked.
Note
This will usually suffice for most items, but in cases where x128 can have different states for a menu item per window (status bar enable/disable, fullscreen, fulllscreen-decorations) the function vhk_gtk_set_check_item_blocked_by_action_for_window() is available.
Parameters
[in] action UI action ID
[in] checked new checked state for menu item(s)
Referenced by actions_display_setup_ui(), actions_joystick_setup_ui(), actions_speed_setup_ui(), actions_vsid_setup_ui(), advance_frame_action(), fullscreen_decorations_toggle_action(), keyset_joystick_toggle_action(), mouse_grab_toggle_action(), pause_toggle_action(), psid_override_toggle_action(), swap_controlport_toggle_action(), ui_action_toggle_show_statusbar(), ui_create_main_window(), update_cpu_radio_buttons(), update_fps_radio_buttons(), and warp_mode_toggle_action().
vhk_gtk_set_check_item_blocked_by_action_for_window()
void vhk_gtk_set_check_item_blocked_by_action_for_window (int action, int window_id, gboolean checked)
Check/uncheck check menu item mapped to UI action for a window.
Set menu item for a main window that is registered for UI action to checked.
Parameters
[in] action UI action ID
[in] window_id window ID (PRIMARY_WINDOW or SECONDARY_WINDOW)
[in] checked new checked state for menu item(s)
Referenced by actions_display_setup_ui(), fullscreen_toggle_action(), show_statusbar_secondary_toggle_action(), and show_statusbar_toggle_action().
vhk_gtk_set_menu_item_accel_label()
void vhk_gtk_set_menu_item_accel_label (GtkWidget * item, int action)
Set accelerator label to the hotkey associated with UI action.
Look up action and if found set the accelerator label of item to the hotkey defined for action, if the action is not found the accelerator label will be cleared. This allows context menus to display an accelerator next to an item. Only sets the label of a menu item, no action handler is set for the item.
Parameters
[in] item runtime menu item
[in] action UI action ID
Referenced by joystick_menu_popup_create(), popup_menu_item_action_new(), popup_menu_new(), speed_menu_popup_create(), ui_do_datasette_popup(), and ui_do_drive_popup().
Variable Documentation
accel_group
GtkAccelGroup* accel_group = NULL static
Reference to the accelerator group.
Global accelerator group used for all accelerators in UI.
Referenced by connect_accelerator(), ui_hotkeys_arch_shutdown(), vhk_gtk_init_accelerators(), vhk_gtk_remove_accelerator(), and vice_locking_gtk_accel_group_connect().