x128: samplerdrv/sampler.h File Reference
sampler.h File Reference
#include "types.h"
Data Structures
struct sampler_device_s
Macros
#define SAMPLER_CHANNEL_DEFAULT 0
#define SAMPLER_CHANNEL_1 1
#define SAMPLER_CHANNEL_2 2
#define SAMPLER_OPEN_MONO 1
#define SAMPLER_OPEN_STEREO 2
#define SAMPLER_CLOSED 0
#define SAMPLER_STARTED 1
#define SAMPLER_GAIN_ONE 100
100%
#define SAMPLER_GAIN_MIN 1
#define SAMPLER_GAIN_MAX 200
200%
#define SAMPLER_GAIN_DEFAULT SAMPLER_GAIN_ONE
Typedefs
typedef struct sampler_device_s sampler_device_t
Enumerations
enum {
SAMPLER_DEVICE_FILE = 0 ,
SAMPLER_DEVICE_PORTAUDIO ,
SAMPLER_MAX_DEVICES
}
Functions
void sampler_start (int channels, char *devname)
void sampler_stop (void)
uint8_t sampler_get_sample (int channel)
void sampler_reset (void)
void sampler_device_register (sampler_device_t *device, int id)
int sampler_resources_init (void)
void sampler_resources_shutdown (void)
int sampler_cmdline_options_init (void)
sampler_device_t * sampler_get_devices (void)
Macro Definition Documentation
SAMPLER_CHANNEL_1
#define SAMPLER_CHANNEL_1 1
SAMPLER_CHANNEL_2
#define SAMPLER_CHANNEL_2 2
SAMPLER_CHANNEL_DEFAULT
#define SAMPLER_CHANNEL_DEFAULT 0
SAMPLER_CLOSED
#define SAMPLER_CLOSED 0
SAMPLER_GAIN_DEFAULT
#define SAMPLER_GAIN_DEFAULT SAMPLER_GAIN_ONE
SAMPLER_GAIN_MAX
#define SAMPLER_GAIN_MAX 200
200%
SAMPLER_GAIN_MIN
#define SAMPLER_GAIN_MIN 1
SAMPLER_GAIN_ONE
#define SAMPLER_GAIN_ONE 100
100%
SAMPLER_OPEN_MONO
#define SAMPLER_OPEN_MONO 1
SAMPLER_OPEN_STEREO
#define SAMPLER_OPEN_STEREO 2
SAMPLER_STARTED
#define SAMPLER_STARTED 1
Typedef Documentation
sampler_device_t
typedef struct sampler_device_s sampler_device_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAMPLER_DEVICE_FILE
SAMPLER_DEVICE_PORTAUDIO
SAMPLER_MAX_DEVICES
Function Documentation
sampler_cmdline_options_init()
int sampler_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
sampler_device_register()
void sampler_device_register (sampler_device_t * device, int id)
Referenced by fileaudio_init().
sampler_get_devices()
sampler_device_t * sampler_get_devices (void)
Referenced by create_device_combo().
sampler_get_sample()
uint8_t sampler_get_sample (int channel)
< 100%
Referenced by userport_4bit_sampler_read_pbx(), and userport_8bss_read_pbx().
sampler_reset()
void sampler_reset (void)
Referenced by machine_specific_reset().
sampler_resources_init()
int sampler_resources_init (void)
Referenced by machine_resources_init().
sampler_resources_shutdown()
void sampler_resources_shutdown (void)
Referenced by machine_resources_shutdown().
sampler_start()
void sampler_start (int channels, char * devname)
Referenced by set_sampler_device(), userport_4bit_sampler_set_enabled(), and userport_8bss_set_enabled().
sampler_stop()
void sampler_stop (void)
Referenced by set_sampler_device(), userport_4bit_sampler_set_enabled(), and userport_8bss_set_enabled().