x128: arch/gtk3/widgets/kbdmappingwidget.c File Reference
kbdmappingwidget.c File Reference
GTK3 keyboard mapping widget for the settings dialog.
#include "vice.h"
#include <gtk/gtk.h>
#include "archdep.h"
#include "debug_gtk3.h"
#include "keyboard.h"
#include "keymap.h"
#include "lib.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "kbdmappingwidget.h"
Functions
static void open_sym_file_callback (GtkEntry *chooser, gchar *filename)
Extra callback for the symbolic user keymap file chooser.
static void open_pos_file_callback (GtkEntry *chooser, gchar *filename)
Extra callback for the positional user keymap file chooser.
static GtkWidget * create_symbolic_keymap_browser (void)
Create resource file chooser widget for the user-defined symbolic keymap.
static GtkWidget * create_positional_keymap_browser (void)
Create resource file chooser widget for the user-defined positional keymap.
void kbdmapping_widget_update (void)
Update the widget depending on external dependencies.
GtkWidget * kbdmapping_widget_create (GtkWidget *parent)
Create a keyboard mapping selection widget.
Variables
static const char * keymap_patterns [] = { "*.vkm", NULL }
Keymap file glob.
static const vice_gtk3_radiogroup_entry_t mappings []
Keyboard mapping types.
static GtkWidget * radio_group = NULL
resource radiogroup widget controlling the "KeymapIndex" resource
Detailed Description
GTK3 keyboard mapping widget for the settings dialog.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_positional_keymap_browser()
static GtkWidget * create_positional_keymap_browser (void) static
Create resource file chooser widget for the user-defined positional keymap.
Returns
GtkGrid
Referenced by kbdmapping_widget_create().
create_symbolic_keymap_browser()
static GtkWidget * create_symbolic_keymap_browser (void) static
Create resource file chooser widget for the user-defined symbolic keymap.
Returns
resource browser widget
Referenced by kbdmapping_widget_create().
kbdmapping_widget_create()
GtkWidget * kbdmapping_widget_create (GtkWidget * parent)
Create a keyboard mapping selection widget.
Parameters
[in] parent parent widget (unused)
Returns
GtkWidget
Referenced by settings_keyboard_widget_create().
kbdmapping_widget_update()
void kbdmapping_widget_update (void)
Update the widget depending on external dependencies.
Referenced by on_combo_changed(), and settings_keyboard_widget_create().
open_pos_file_callback()
static void open_pos_file_callback (GtkEntry * chooser, gchar * filename) static
Extra callback for the positional user keymap file chooser.
Parameters
[in] chooser resource file chooser widget (ignored)
[in] filename new resource value
Referenced by create_positional_keymap_browser().
open_sym_file_callback()
static void open_sym_file_callback (GtkEntry * chooser, gchar * filename) static
Extra callback for the symbolic user keymap file chooser.
Parameters
[in] chooser resource file chooser widget (ignored)
[in] filename new resource value
Referenced by create_symbolic_keymap_browser().
Variable Documentation
keymap_patterns
const char* keymap_patterns[] = { "*.vkm", NULL } static
Keymap file glob.
Looks like shit, but this is how Gtk/GLib works
Referenced by create_positional_keymap_browser(), and create_symbolic_keymap_browser().
mappings
const vice_gtk3_radiogroup_entry_t mappings[] static
Initial value:
= {
    { "Symbolic",            0  },
    { "Positional",          1  },
    { "Symbolic (user)",     2  },
    { "Positional (user)",   3  },
    { NULL,                 -1 }
}
Keyboard mapping types.
Referenced by kbdmapping_widget_create().
radio_group
GtkWidget* radio_group = NULL static
resource radiogroup widget controlling the "KeymapIndex" resource
Referenced by cbm2_hardwired_switches_widget_create(), cbm2_memory_size_widget_create(), create_cia_widget(), kbdmapping_widget_create(), kbdmapping_widget_update(), open_pos_file_callback(), and open_sym_file_callback().