x128: drive/iec/iec.c File Reference
iec.c File Reference
#include "vice.h"
#include <stdio.h>
#include "cia.h"
#include "ciad.h"
#include "drive.h"
#include "drivetypes.h"
#include "iec-cmdline-options.h"
#include "iec-resources.h"
#include "iec.h"
#include "iecbus.h"
#include "iecdrive.h"
#include "iecrom.h"
#include "lib.h"
#include "memiec.h"
#include "resources.h"
#include "types.h"
#include "via.h"
#include "via1d1541.h"
#include "wd1770.h"
#include "via4000.h"
#include "pc8477.h"
#include "cmdhd.h"
Functions
int iec_drive_resources_init (void)
void iec_drive_resources_shutdown (void)
int iec_drive_cmdline_options_init (void)
void iec_drive_init (struct diskunit_context_s *drv)
void iec_drive_reset (struct diskunit_context_s *drv)
called by machine_drive_reset()
void iec_drive_mem_init (struct diskunit_context_s *drv, unsigned int type)
void iec_drive_setup_context (struct diskunit_context_s *drv)
void iec_drive_shutdown (struct diskunit_context_s *drv)
void iec_drive_idling_method (unsigned int dnr)
void iec_drive_rom_load (void)
void iec_drive_rom_setup_image (unsigned int dnr)
int iec_drive_rom_check_loaded (unsigned int type)
void iec_drive_rom_do_checksum (unsigned int dnr)
int iec_drive_snapshot_read (struct diskunit_context_s *ctxptr, struct snapshot_s *s)
int iec_drive_snapshot_write (struct diskunit_context_s *ctxptr, struct snapshot_s *s)
int iec_drive_image_attach (struct disk_image_s *image, unsigned int unit, unsigned int drive)
int iec_drive_image_detach (struct disk_image_s *image, unsigned int unit, unsigned int drive)
void iec_drive_port_default (struct diskunit_context_s *drv)
Variables
static iecbus_t * drive_iecbus
Pointer to the IEC bus structure.
Function Documentation
iec_drive_cmdline_options_init()
int iec_drive_cmdline_options_init (void)
Referenced by machine_drive_cmdline_options_init().
iec_drive_idling_method()
void iec_drive_idling_method (unsigned int dnr)
Referenced by machine_drive_idling_method().
iec_drive_image_attach()
int iec_drive_image_attach (struct disk_image_s * image, unsigned int unit, unsigned int drive)
Referenced by machine_drive_image_attach().
iec_drive_image_detach()
int iec_drive_image_detach (struct disk_image_s * image, unsigned int unit, unsigned int drive)
Referenced by machine_drive_image_detach().
iec_drive_init()
void iec_drive_init (struct diskunit_context_s * drv)
Referenced by machine_drive_init().
iec_drive_mem_init()
void iec_drive_mem_init (struct diskunit_context_s * drv, unsigned int type)
Referenced by machine_drive_mem_init().
iec_drive_port_default()
void iec_drive_port_default (struct diskunit_context_s * drv)
Referenced by machine_drive_port_default().
iec_drive_reset()
void iec_drive_reset (struct diskunit_context_s * drv)
called by machine_drive_reset()
< ASCII for HD
Referenced by machine_drive_reset().
iec_drive_resources_init()
int iec_drive_resources_init (void)
Referenced by machine_drive_resources_init().
iec_drive_resources_shutdown()
void iec_drive_resources_shutdown (void)
Referenced by machine_drive_resources_shutdown().
iec_drive_rom_check_loaded()
int iec_drive_rom_check_loaded (unsigned int type)
Referenced by machine_drive_rom_check_loaded().
iec_drive_rom_do_checksum()
void iec_drive_rom_do_checksum (unsigned int dnr)
Referenced by machine_drive_rom_do_checksum().
iec_drive_rom_load()
void iec_drive_rom_load (void)
Referenced by machine_drive_rom_load().
iec_drive_rom_setup_image()
void iec_drive_rom_setup_image (unsigned int dnr)
Referenced by machine_drive_rom_setup_image().
iec_drive_setup_context()
void iec_drive_setup_context (struct diskunit_context_s * drv)
Referenced by machine_drive_setup_context().
iec_drive_shutdown()
void iec_drive_shutdown (struct diskunit_context_s * drv)
Referenced by machine_drive_shutdown().
iec_drive_snapshot_read()
int iec_drive_snapshot_read (struct diskunit_context_s * ctxptr, struct snapshot_s * s)
< ASCII for HD
Referenced by machine_drive_snapshot_read().
iec_drive_snapshot_write()
int iec_drive_snapshot_write (struct diskunit_context_s * ctxptr, struct snapshot_s * s)
< ASCII for HD
Referenced by machine_drive_snapshot_write().
Variable Documentation
drive_iecbus
iecbus_t* drive_iecbus static
Pointer to the IEC bus structure.
Referenced by iec_drive_port_default().