vsid: arch/gtk3/widgets/base/resourcescale.c File Reference
resourcescale.c File Reference
GktScale widget to control resources.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdarg.h>
#include <math.h>
#include "basewidget_types.h"
#include "debug_gtk3.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "resourcehelpers.h"
#include "resourcescale.h"
Functions
static void on_scale_int_changed (GtkWidget *widget, gpointer user_data)
Handler for the 'value-changed' event of the scale widget.
static GtkWidget * resource_scale_int_new_helper (GtkWidget *widget)
Create a scale for an integer resource - helper.
GtkWidget * vice_gtk3_resource_scale_int_new (const char *resource, GtkOrientation orientation, int low, int high, int step)
Create a scale for an integer resource.
GtkWidget * vice_gtk3_resource_scale_int_new_sprintf (const char *fmt, GtkOrientation orientation, int low, int high, int step,...)
Create a scale for an integer resource.
void vice_gtk3_resource_scale_int_set_marks (GtkWidget *widget, int step)
Add marks to integer scale widget at each step increment.
gboolean vice_gtk3_resource_scale_int_set (GtkWidget *widget, int value)
Set the integer scale widget to value.
gboolean vice_gtk3_resource_scale_int_get (GtkWidget *widget, int *value)
Get the value of the integer scale widget.
gboolean vice_gtk3_resource_scale_int_reset (GtkWidget *widget)
Restore the scale to the resource's value on instanciation.
gboolean vice_gtk3_resource_scale_int_factory (GtkWidget *widget)
Reset widget to the resource factory value.
gboolean vice_gtk3_resource_scale_int_sync (GtkWidget *widget)
Synchronize widget with its resource.
static int custom_get_resource_value (GtkWidget *self)
Convert current display value to integer resource value.
static gdouble custom_get_display_value (GtkWidget *self)
Convert current resource integer value to gdouble for display.
static void custom_get_params (GtkWidget *self, gint *resource_low, gint *resource_high, gint *resource_range, gdouble *display_low, gdouble *display_high, gdouble *display_range)
Get parameters required to convert between resource and display value.
static int custom_display_to_resource (GtkWidget *self, gdouble value)
Convert display value to resource value.
static gdouble custom_resource_to_display (GtkWidget *self, int value)
Convert resource value to display value.
static void on_scale_custom_destroy (GtkWidget *widget, gpointer user_data)
Handler for the 'destroy' event of the scale widget.
static void on_custom_changed (GtkWidget *self, gpointer data)
Handler for the 'value-changed' event of the custom scale widget.
static gchar * on_custom_format (GtkScale *self, gdouble value)
static GtkWidget * custom_new_helper (GtkWidget *self, gint resource_low, gint resource_high, const gchar *display_fmt)
Helper function to create the custom resource-bound scale widget.
GtkWidget * vice_gtk3_resource_scale_custom_new (const gchar *resource, GtkOrientation orientation, gint resource_low, gint resource_high, gdouble display_low, gdouble display_high, gdouble display_step, const gchar *display_fmt)
Create scale widget displaying custom value bound to resource.
GtkWidget * vice_gtk3_resource_scale_custom_new_printf (const gchar *resource, GtkOrientation orientation, gint resource_low, gint resource_high, gdouble display_low, gdouble display_high, gdouble display_step, const gchar *display_fmt,...)
Create scale widget displaying custom value bound to resource.
gboolean vice_gtk3_resource_scale_custom_set (GtkWidget *widget, int value)
Set the raw resource-bound value.
gboolean vice_gtk3_resource_scale_custom_get (GtkWidget *widget, int *value)
Get the raw resource-bound value.
gboolean vice_gtk3_resource_scale_custom_reset (GtkWidget *widget)
Reset widget to the state it had when instanciated.
gboolean vice_gtk3_resource_scale_custom_factory (GtkWidget *widget)
Set widget to the factory value of its resource.
gboolean vice_gtk3_resource_scale_custom_sync (GtkWidget *widget)
Synchronize the widget state with its resource.
static void exponential_get_params (GtkWidget *self, gdouble *power, gint *resource_low, gint *resource_high, gint *resource_range)
Get parameters required to convert between resource value and slider position.
static gint exp_slider_to_resource (GtkWidget *self, gint value)
Convert slider value to resource value.
static gint exp_resource_to_slider (GtkWidget *self, gint value)
Convert resource value to slider value.
static void on_scale_exp_destroy (GtkWidget *widget, gpointer user_data)
Handler for the 'destroy' event of the exp widget.
static void on_exp_changed (GtkWidget *self, gpointer data)
Handler for the 'value-changed' event of the exp scale widget.
static gchar * on_exp_format (GtkScale *self, gdouble value)
void vice_gtk3_resource_exp_range_set_value (GtkRange *self, gdouble value)
static GtkWidget * exp_new_helper (GtkWidget *self, gdouble power, gint resource_low, gint resource_high, const gchar *display_fmt)
Helper function to create the exponential resource-bound scale widget.
GtkWidget * vice_gtk3_resource_scale_exp_new (const gchar *resource, GtkOrientation orientation, gdouble power, gint resource_low, gint resource_high, gint display_step, const gchar *display_fmt)
Create exponential scale widget displaying value bound to resource.
Detailed Description
GktScale widget to control resources.
Note
Only integer resources are supported, which should be fine since VICE resources are either int or string (or strings abused to store arbitraty data)
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
custom_display_to_resource()
static int custom_display_to_resource (GtkWidget * self, gdouble value) static
Convert display value to resource value.
Parameters
[in] self custom scale widget
[in] value custom display value
Returns
resource value
Note
Doesn't touch the resource
Referenced by custom_get_resource_value(), and on_custom_changed().
custom_get_display_value()
static gdouble custom_get_display_value (GtkWidget * self) static
Convert current resource integer value to gdouble for display.
Parameters
[in] self custom scale widget
Returns
current resource value scaled and offset for display
Referenced by custom_new_helper().
custom_get_params()
static void custom_get_params (GtkWidget * self, gint * resource_low, gint * resource_high, gint * resource_range, gdouble * display_low, gdouble * display_high, gdouble * display_range) static
Get parameters required to convert between resource and display value.
Parameters
[in] self custom scale widget
[out] resource_low resource value lower bound
[out] resource_high resource value upper bound
[out] resource_range resource value range
[out] display_low display value lower bound
[out] display_high display value upper bound
[out] display_range display value range
Referenced by custom_display_to_resource(), and custom_resource_to_display().
custom_get_resource_value()
static int custom_get_resource_value (GtkWidget * self) static
Convert current display value to integer resource value.
Parameters
[in] self custom scale widget
Returns
current display value scaled and offset for setting the resource
Referenced by vice_gtk3_resource_scale_custom_get().
custom_new_helper()
static GtkWidget * custom_new_helper (GtkWidget * self, gint resource_low, gint resource_high, const gchar * display_fmt) static
Helper function to create the custom resource-bound scale widget.
Parameters
[in] self scale widget
[in] resource_low resource lower bound (inclusive)
[in] resource_high resource upper bound (inclusive)
[in] display_fmt display format string
Returns
self
Referenced by vice_gtk3_resource_scale_custom_new(), and vice_gtk3_resource_scale_custom_new_printf().
custom_resource_to_display()
static gdouble custom_resource_to_display (GtkWidget * self, int value) static
Convert resource value to display value.
Parameters
[in] self custom scale widget
[in] value raw resource value
Returns
custom display value
Note
Doesn't touch the resource
Referenced by custom_get_display_value(), and vice_gtk3_resource_scale_custom_set().
exp_new_helper()
static GtkWidget * exp_new_helper (GtkWidget * self, gdouble power, gint resource_low, gint resource_high, const gchar * display_fmt) static
Helper function to create the exponential resource-bound scale widget.
Parameters
[in] self scale widget
[in] power the exponent
[in] resource_low resource lower bound (inclusive)
[in] resource_high resource upper bound (inclusive)
[in] display_fmt display format string
Returns
self
Referenced by vice_gtk3_resource_scale_exp_new().
exp_resource_to_slider()
static gint exp_resource_to_slider (GtkWidget * self, gint value) static
Convert resource value to slider value.
Parameters
[in] self exponential scale widget
[in] value linear slider value
Returns
resource value
Note
Doesn't touch the resource
Referenced by vice_gtk3_resource_exp_range_set_value().
exp_slider_to_resource()
static int exp_slider_to_resource (GtkWidget * self, gint value) static
Convert slider value to resource value.
Parameters
[in] self exponential scale widget
[in] value linear slider value
Returns
resource value
Note
Doesn't touch the resource
Referenced by on_exp_changed(), and on_exp_format().
exponential_get_params()
static void exponential_get_params (GtkWidget * self, gdouble * power, gint * resource_low, gint * resource_high, gint * resource_range) static
Get parameters required to convert between resource value and slider position.
Parameters
[in] self custom scale widget
[out] power exponent
[out] resource_low resource value lower bound
[out] resource_high resource value upper bound
[out] resource_range resource value range
Referenced by exp_resource_to_slider(), and exp_slider_to_resource().
on_custom_changed()
static void on_custom_changed (GtkWidget * self, gpointer data) static
Handler for the 'value-changed' event of the custom scale widget.
Parameters
[in] self custom scale widget
[in] data extra event data (unused)
Referenced by custom_new_helper().
on_custom_format()
static gchar * on_custom_format (GtkScale * self, gdouble value) static
Referenced by custom_new_helper().
on_exp_changed()
static void on_exp_changed (GtkWidget * self, gpointer data) static
Handler for the 'value-changed' event of the exp scale widget.
Parameters
[in] self custom scale widget
[in] data extra event data (unused)
Referenced by exp_new_helper().
on_exp_format()
static gchar * on_exp_format (GtkScale * self, gdouble value) static
Referenced by exp_new_helper().
on_scale_custom_destroy()
static void on_scale_custom_destroy (GtkWidget * widget, gpointer user_data) static
Handler for the 'destroy' event of the scale widget.
Frees memory used by the resource name and the display format string.
Parameters
[in,out] widget integer scale widget
[in] user_data extra event data (unused)
Referenced by custom_new_helper().
on_scale_exp_destroy()
static void on_scale_exp_destroy (GtkWidget * widget, gpointer user_data) static
Handler for the 'destroy' event of the exp widget.
Frees memory used by the resource name and the display format string.
Parameters
[in,out] widget integer exponential scale widget
[in] user_data extra event data (unused)
Referenced by exp_new_helper().
on_scale_int_changed()
static void on_scale_int_changed (GtkWidget * widget, gpointer user_data) static
Handler for the 'value-changed' event of the scale widget.
Updates resource value.
Parameters
[in] widget integer scale widget
[in] user_data extra event data (unused)
Referenced by resource_scale_int_new_helper().
resource_scale_int_new_helper()
static GtkWidget * resource_scale_int_new_helper (GtkWidget * widget) static
Create a scale for an integer resource - helper.
Parameters
[in,out] widget interger scale widget
Returns
GtkScale
Referenced by vice_gtk3_resource_scale_int_new(), and vice_gtk3_resource_scale_int_new_sprintf().
vice_gtk3_resource_exp_range_set_value()
void vice_gtk3_resource_exp_range_set_value (GtkRange * self, gdouble value)
Referenced by exp_new_helper(), and on_reset_clicked().
vice_gtk3_resource_scale_custom_factory()
gboolean vice_gtk3_resource_scale_custom_factory (GtkWidget * widget)
Set widget to the factory value of its resource.
Reset the widget to the value its resource had when the widget was instanciated.
Parameters
[in] widget custom scale widget
Returns
TRUE on success
Referenced by on_reset_clicked(), and reset_sliders().
vice_gtk3_resource_scale_custom_get()
gboolean vice_gtk3_resource_scale_custom_get (GtkWidget * widget, int * value)
Get the raw resource-bound value.
Get the bound resource's current value.
Parameters
[in] widget custom scale widget
[out] value current value of the resource
Returns
TRUE
vice_gtk3_resource_scale_custom_new()
GtkWidget * vice_gtk3_resource_scale_custom_new (const gchar * resource, GtkOrientation orientation, gint resource_low, gint resource_high, gdouble display_low, gdouble display_high, gdouble display_step, const gchar * display_fmt)
Create scale widget displaying custom value bound to resource.
Create a scale widget that maps an integer resource's range to a custom range using double with a custom format string.
Parameters
[in] resource resource name
[in] orientation GtkScale orientation
[in] resource_low resource lower bound (inclusive)
[in] resource_high resource upper bound (inclusive)
[in] display_low display lower bound (inclusive)
[in] display_high display upper bound (inclusive)
[in] display_step display stepping
[in] display_fmt display format string
Returns
new custom resource-bound scale widget
vice_gtk3_resource_scale_custom_new_printf()
GtkWidget * vice_gtk3_resource_scale_custom_new_printf (const gchar * resource, GtkOrientation orientation, gint resource_low, gint resource_high, gdouble display_low, gdouble display_high, gdouble display_step, const gchar * display_fmt, ...)
Create scale widget displaying custom value bound to resource.
Create a scale widget that maps an integer resource's range to a custom range using double with a custom format string. This version uses resource as a printf format string to generate the resource name.
Parameters
[in] resource resource name format string
[in] orientation GtkScale orientation
[in] resource_low resource lower bound (inclusive)
[in] resource_high resource upper bound (inclusive)
[in] display_low display lower bound (inclusive)
[in] display_high display upper bound (inclusive)
[in] display_step display stepping
[in] display_fmt display format string
[in] ... resource name format string arguments
Returns
new custom resource-bound scale widget
Referenced by create_autofire_speed_widget(), create_datasette_widget(), create_slider(), settings_sampler_widget_create(), and settings_sound_widget_create().
vice_gtk3_resource_scale_custom_reset()
gboolean vice_gtk3_resource_scale_custom_reset (GtkWidget * widget)
Reset widget to the state it had when instanciated.
Reset the widget to its resource value when the widget was instanciated.
Parameters
[in] widget custom scale widget
Returns
TRUE on success
vice_gtk3_resource_scale_custom_set()
gboolean vice_gtk3_resource_scale_custom_set (GtkWidget * widget, int value)
Set the raw resource-bound value.
Set the bound resource's new value and update the widget.
Parameters
[in] widget custom scale widget
[in] value new value for widget
Returns
true on success
Referenced by reset_sliders_neutral(), vice_gtk3_resource_scale_custom_factory(), vice_gtk3_resource_scale_custom_reset(), and vice_gtk3_resource_scale_custom_sync().
vice_gtk3_resource_scale_custom_sync()
gboolean vice_gtk3_resource_scale_custom_sync (GtkWidget * widget)
Synchronize the widget state with its resource.
Update the widget's state in case its resource was altered through other means than this widget.
Parameters
[in] widget custom scale widget
Returns
TRUE on success
vice_gtk3_resource_scale_exp_new()
GtkWidget * vice_gtk3_resource_scale_exp_new (const gchar * resource, GtkOrientation orientation, gdouble power, gint resource_low, gint resource_high, gint display_step, const gchar * display_fmt)
Create exponential scale widget displaying value bound to resource.
Create a scale widget that displays an integer resource's range to a slider which reacts exponentially.
Parameters
[in] resource resource name
[in] orientation GtkScale orientation
[in] power exponent
[in] resource_low lower bound (inclusive)
[in] resource_high upper bound (inclusive)
[in] display_step stepping
[in] display_fmt display format string
Returns
new exponential resource-bound scale widget
Referenced by create_exp_slider().
vice_gtk3_resource_scale_int_factory()
gboolean vice_gtk3_resource_scale_int_factory (GtkWidget * widget)
Reset widget to the resource factory value.
Parameters
[in,out] widget integer scale widget
Returns
TRUE if the widget was restored to its factory value
vice_gtk3_resource_scale_int_get()
gboolean vice_gtk3_resource_scale_int_get (GtkWidget * widget, int * value)
Get the value of the integer scale widget.
Parameters
[in] widget integer scale widget
[out] value location to store value
Returns
TRUE
vice_gtk3_resource_scale_int_new()
GtkWidget * vice_gtk3_resource_scale_int_new (const char * resource, GtkOrientation orientation, int low, int high, int step)
Create a scale for an integer resource.
Parameters
[in] resource resource name
[in] orientation scale orientation (
See also
GtkOrientation)
Parameters
[in] low lowest value for scale
[in] high highest value for scale
[in] step value to incr/decr value with cursor keys
Returns
GtkScale
Referenced by drive_sound_widget_create().
vice_gtk3_resource_scale_int_new_sprintf()
GtkWidget * vice_gtk3_resource_scale_int_new_sprintf (const char * fmt, GtkOrientation orientation, int low, int high, int step, ...)
Create a scale for an integer resource.
Parameters
[in] fmt resource name format string
[in] orientation scale orientation (
See also
GtkOrientation)
Parameters
[in] low lowest value for scale
[in] high highest value for scale
[in] step value to incr/decr value with cursor keys
Returns
GtkScale
vice_gtk3_resource_scale_int_reset()
gboolean vice_gtk3_resource_scale_int_reset (GtkWidget * widget)
Restore the scale to the resource's value on instanciation.
Restores the widget to the resource value on instanciantion.
Parameters
[in,out] widget integer scale widget
Returns
TRUE if the widget was reset to its original value
vice_gtk3_resource_scale_int_set()
gboolean vice_gtk3_resource_scale_int_set (GtkWidget * widget, int value)
Set the integer scale widget to value.
Parameters
[in,out] widget integer scale widget
[in] value new value for scale
Returns
TRUE
Referenced by vice_gtk3_resource_scale_int_factory(), vice_gtk3_resource_scale_int_reset(), and vice_gtk3_resource_scale_int_sync().
vice_gtk3_resource_scale_int_set_marks()
void vice_gtk3_resource_scale_int_set_marks (GtkWidget * widget, int step)
Add marks to integer scale widget at each step increment.
Parameters
[in,out] widget integer scale widget
[in] step distance between marks
vice_gtk3_resource_scale_int_sync()
gboolean vice_gtk3_resource_scale_int_sync (GtkWidget * widget)
Synchronize widget with its resource.
Parameters
[in,out] widget integer scale widget
Returns
TRUE if the widget was synchronized with its resource