vsid: printerdrv/output-text.c File Reference
output-text.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "archdep.h"
#include "cmdline.h"
#include "coproc.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "output-select.h"
#include "output.h"
#include "resources.h"
#include "types.h"
#include "util.h"
#include "output-text.h"
Macros
#define DBG(x)
Functions
static int set_printer_device_name (const char *val, void *param)
static int set_printer_device (int prn_dev, void *param)
int output_text_init_cmdline_options (void)
static FILE * fopen_or_pipe (char *name, vice_pid_t *pid)
static int output_text_open (unsigned int prnr, output_parameter_t *output_parameter)
static void output_text_close (unsigned int prnr)
static int output_text_putc (unsigned int prnr, uint8_t b)
static int output_text_getc (unsigned int prnr, uint8_t *b)
static int output_text_flush (unsigned int prnr)
static int output_text_formfeed (unsigned int prnr)
int output_text_init_resources (void)
void output_text_shutdown_resources (void)
Variables
static char * PrinterDev [4] = { NULL, NULL, NULL }
static int printer_device [4]
static FILE * output_fd [4] = { NULL, NULL, NULL }
static vice_pid_t output_pid [4] = { 0, 0, 0 }
static const resource_string_t resources_string []
static const resource_int_t resources_int []
static const resource_int_t resources_int_userport []
static const cmdline_option_t cmdline_options []
static const cmdline_option_t cmdline_options_userport []
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
fopen_or_pipe()
static FILE * fopen_or_pipe (char * name, vice_pid_t * pid) static
< write mode (binary)
< append mode
Referenced by output_text_open().
output_text_close()
static void output_text_close (unsigned int prnr) static
Referenced by output_text_init_resources().
output_text_flush()
static int output_text_flush (unsigned int prnr) static
Referenced by output_text_formfeed(), and output_text_init_resources().
output_text_formfeed()
static int output_text_formfeed (unsigned int prnr) static
Referenced by output_text_init_resources().
output_text_getc()
static int output_text_getc (unsigned int prnr, uint8_t * b) static
Referenced by output_text_init_resources().
output_text_init_cmdline_options()
int output_text_init_cmdline_options (void)
Referenced by printer_cmdline_options_init().
output_text_init_resources()
int output_text_init_resources (void)
Referenced by printer_resources_init().
output_text_open()
static int output_text_open (unsigned int prnr, output_parameter_t * output_parameter) static
Referenced by output_text_init_resources().
output_text_putc()
static int output_text_putc (unsigned int prnr, uint8_t b) static
Referenced by output_text_init_resources().
output_text_shutdown_resources()
void output_text_shutdown_resources (void)
Referenced by printer_resources_shutdown().
set_printer_device()
static int set_printer_device (int prn_dev, void * param) static
set_printer_device_name()
static int set_printer_device_name (const char * val, void * param) static
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-prtxtdev1", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "PrinterTextDevice1", NULL,
      "<Name>", "Specify name of printer text device or dump file" },
    { "-prtxtdev2", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "PrinterTextDevice2", NULL,
      "<Name>", "Specify name of printer text device or dump file" },
    { "-prtxtdev3", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "PrinterTextDevice3", NULL,
      "<Name>", "Specify name of printer text device or dump file" },
    { "-pr4txtdev", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer4TextDevice", NULL,
      "<0-2>", "Specify printer text output device for printer #4" },
    { "-pr5txtdev", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer5TextDevice", NULL,
      "<0-2>", "Specify printer text output device for printer #5" },
    { "-pr6txtdev", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer6TextDevice", NULL,
      "<0-2>", "Specify printer text output device for printer #6" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by output_text_init_cmdline_options().
cmdline_options_userport
const cmdline_option_t cmdline_options_userport[] static
Initial value:
=
{
    { "-prusertxtdev", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "PrinterUserportTextDevice", (resource_value_t)0,
      "<0-2>", "Specify printer text output device for userport printer" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by output_text_init_cmdline_options().
output_fd
FILE* output_fd[4] = { NULL, NULL, NULL } static
Referenced by output_text_close(), output_text_flush(), output_text_getc(), output_text_open(), and output_text_putc().
output_pid
vice_pid_t output_pid[4] = { 0, 0, 0 } static
Referenced by output_text_close(), and output_text_open().
printer_device
int printer_device[4] static
Referenced by output_text_close(), output_text_flush(), output_text_getc(), output_text_open(), output_text_putc(), and set_printer_device().
PrinterDev
char* PrinterDev[4] = { NULL, NULL, NULL } static
Referenced by output_text_open(), output_text_shutdown_resources(), and set_printer_device_name().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "Printer4TextDevice", 0, RES_EVENT_NO, NULL,
      &printer_device[0], set_printer_device, (void *)0 },
    { "Printer5TextDevice", 0, RES_EVENT_NO, NULL,
      &printer_device[1], set_printer_device, (void *)1 },
    { "Printer6TextDevice", 0, RES_EVENT_NO, NULL,
      &printer_device[2], set_printer_device, (void *)2 },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by output_text_init_resources().
resources_int_userport
const resource_int_t resources_int_userport[] static
Initial value:
= {
    { "PrinterUserportTextDevice", 0, RES_EVENT_NO, NULL,
      &printer_device[3], set_printer_device, (void *)3 },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by output_text_init_resources().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "PrinterTextDevice1",  "print.dump" ,
      RES_EVENT_NO, NULL,
      &PrinterDev[0], set_printer_device_name, (void *)0 },
    { "PrinterTextDevice2",  "|lpr" ,
      RES_EVENT_NO, NULL,
      &PrinterDev[1], set_printer_device_name, (void *)1 },
    { "PrinterTextDevice3",  "|petlp -F PS|lpr" ,
      RES_EVENT_NO, NULL,
      &PrinterDev[2], set_printer_device_name, (void *)2 },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by output_text_init_resources().