vsid: arch/gtk3/widgets/contentpreviewwidget.c File Reference
contentpreviewwidget.c File Reference
GTK3 disk/tape/archive preview widget.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include "basedialogs.h"
#include "charset.h"
#include "debug_gtk3.h"
#include "imagecontents.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "unicodehelpers.h"
#include "util.h"
#include "widgethelpers.h"
#include "contentpreviewwidget.h"
Functions
static void on_row_activated (GtkTreeView *view, GtkTreePath *path, GtkTreeViewColumn *column, gpointer data)
Handler for the "row-activated" event of the view.
static GtkListStore * create_model (const char *path)
Create the model for the view.
static GtkWidget * create_view (const char *path)
Create the view for the content widget.
GtkWidget * content_preview_widget_create (GtkWidget *dialog, read_contents_func_type func, void(*response)(GtkWidget *, gint, gpointer), int unit)
Create widget to show image contents in a file dialog.
void content_preview_widget_set_image (GtkWidget *widget, const char *path)
Set image file for the widget.
gboolean content_preview_widget_set_index (GtkWidget *widget, int index)
Set index in directory.
int content_preview_widget_get_index (GtkWidget *widget)
Get index in directory.
Variables
static read_contents_func_type content_func = NULL
Function to read image contents.
static void(* response_func)(GtkWidget *, gint, gpointer)
Callback to trigger on the "response" event of the widget.
static int unit_number = 0
Unit number to use in the callback.
static GtkWidget * content_view = NULL
reference to the content view widget
static GtkWidget * parent_dialog
Reference to the parent dialog.
Detailed Description
GTK3 disk/tape/archive preview widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Function Documentation
content_preview_widget_create()
GtkWidget * content_preview_widget_create (GtkWidget * dialog, read_contents_func_type func, void(*)(GtkWidget *, gint, gpointer) response, int unit)
Create widget to show image contents in a file dialog.
The func argument sets the function to use to retrieve the contents ('directory') of an image. For disk images this will be diskcontents_filesystem_read(), for tape images ... If this argument is NULL, no image contents will be displayed in the widget.
Parameters
[in,out] dialog parent dialog
[in] func function to use to retrieve image contents
[in] response dialog response callback
[in] unit unit number (1-2 for tape, 8-11 for drive)
Returns
GtkGrid
Referenced by create_disk_attach_dialog(), create_smart_attach_dialog(), and create_tape_attach_dialog().
content_preview_widget_get_index()
int content_preview_widget_get_index (GtkWidget * widget)
Get index in directory.
Parameters
[in] widget widget (unused)
Returns
index in directory
Referenced by on_response().
content_preview_widget_set_image()
void content_preview_widget_set_image (GtkWidget * widget, const char * path)
Set image file for the widget.
Parameters
[in,out] widget preview widget
[in] path path to image file
Referenced by on_update_preview().
content_preview_widget_set_index()
gboolean content_preview_widget_set_index (GtkWidget * widget, int index)
Set index in directory.
Parameters
[in] widget widget (unused)
[in] index index in directory
Returns
bool
create_model()
static GtkListStore * create_model (const char * path) static
Create the model for the view.
The model created has two columns, a string representing a file: '<blocks> "\<filename\>" <filetype-and-flags>' and an integer which indicates the file's index in the image's "directory".
Parameters
[in] path path to image file
Returns
model (empty if reading the image failed)
< return string in PETSCII form
< return string in PETSCII form
Referenced by content_preview_widget_set_image(), and create_view().
create_view()
static GtkWidget * create_view (const char * path) static
Create the view for the content widget.
Creates a GtkTreeView to display the contents of image path
Parameters
[in] path path to image file
Returns
GtkTreeView
Referenced by content_preview_widget_create().
on_row_activated()
static void on_row_activated (GtkTreeView * view, GtkTreePath * path, GtkTreeViewColumn * column, gpointer data) static
Handler for the "row-activated" event of the view.
This function handles auto-starting a file selected in the preview. It retrieves an integer in the model and uses that to call the Gtk callback handler of the parent dialog.
Parameters
[in] view tree view
[in] path tree path (unused)
[in] column tree view column (unused)
[in] data extra event data (unused)
Referenced by create_view().
Variable Documentation
content_func
read_contents_func_type content_func = NULL static
Function to read image contents.
Referenced by content_preview_widget_create(), and create_model().
content_view
GtkWidget* content_view = NULL static
reference to the content view widget
Referenced by content_preview_widget_create(), content_preview_widget_get_index(), content_preview_widget_set_image(), and content_preview_widget_set_index().
parent_dialog
GtkWidget* parent_dialog static
Reference to the parent dialog.
Referenced by content_preview_widget_create(), and on_row_activated().
response_func
void(* response_func) (GtkWidget *, gint, gpointer) (GtkWidget * , gint , gpointer) static
Callback to trigger on the "response" event of the widget.
Referenced by content_preview_widget_create(), and on_row_activated().
unit_number
int unit_number = 0 static
Unit number to use in the callback.
Referenced by content_preview_widget_create(), and on_row_activated().