x128: arch/gtk3/widgets/petkeyboardtypewidget.c File Reference
petkeyboardtypewidget.c File Reference
PET keyboard type widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "resources.h"
#include "machine.h"
#include "pet.h"
#include "petkeyboardtypewidget.h"
Functions
static void on_keyboard_type_toggled (GtkWidget *widget, gpointer type)
Handler for the 'toggled' event of the radio buttons.
void pet_keyboard_type_widget_set_keyboard_num_get (int(*func)(void))
Set the getter function for the number of keyboard types.
void pet_keyboard_type_widget_set_keyboard_list_get (kbdtype_info_t *(*func)(void))
Set the getter function for the keyboard types list.
GtkWidget * pet_keyboard_type_widget_create (void)
Create PET keyboard type widget.
void pet_keyboard_type_widget_set_callback (GtkWidget *widget, void(*func)(int))
Set user-defined callback to be triggered when the widget changes.
void pet_keyboard_type_widget_sync (GtkWidget *widget)
Synchronize widget with its current resource value.
Variables
static int(* get_keyboard_num)(void) = NULL
Function to get the number of keyboard types.
static kbdtype_info_t *(* get_keyboard_list)(void) = NULL
Function to get a list of keyboard types.
static void(* user_callback)(int) = NULL
Function triggered on selecting a keyboard.
Detailed Description
PET keyboard type widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_keyboard_type_toggled()
static void on_keyboard_type_toggled (GtkWidget * widget, gpointer type) static
Handler for the 'toggled' event of the radio buttons.
Parameters
[in] widget radio button triggering the event
[in] type keyboard ID (int)
Referenced by pet_keyboard_type_widget_create().
pet_keyboard_type_widget_create()
GtkWidget * pet_keyboard_type_widget_create (void)
Create PET keyboard type widget.
Returns
GtkGrid
Referenced by create_pet_layout().
pet_keyboard_type_widget_set_callback()
void pet_keyboard_type_widget_set_callback (GtkWidget * widget, void(*)(int) func)
Set user-defined callback to be triggered when the widget changes.
Parameters
[in] widget PET keyboard type widget
[in] func user-defined callback
Referenced by create_pet_layout().
pet_keyboard_type_widget_set_keyboard_list_get()
void pet_keyboard_type_widget_set_keyboard_list_get (kbdtype_info_t *(*)(void) func)
Set the getter function for the keyboard types list.
Parameters
[in] func function pointer
pet_keyboard_type_widget_set_keyboard_num_get()
void pet_keyboard_type_widget_set_keyboard_num_get (int(*)(void) func)
Set the getter function for the number of keyboard types.
This doesn't seem strictly required for PET, since the keyboard info list has a terminator
Parameters
[in] func function pointer
pet_keyboard_type_widget_sync()
void pet_keyboard_type_widget_sync (GtkWidget * widget)
Synchronize widget with its current resource value.
Parameters
[in,out] widget PET keyboard type widget
Referenced by machine_model_handler_pet().
Variable Documentation
get_keyboard_list
kbdtype_info_t *(* get_keyboard_list) (void) (void) = NULL static
Function to get a list of keyboard types.
Required thanks to the way VSID is linked.
Referenced by pet_keyboard_type_widget_create(), and pet_keyboard_type_widget_set_keyboard_list_get().
get_keyboard_num
int(* get_keyboard_num) (void) (void) = NULL static
Function to get the number of keyboard types.
Required thanks to the way VSID is linked.
Referenced by pet_keyboard_type_widget_create(), and pet_keyboard_type_widget_set_keyboard_num_get().
user_callback
void(* user_callback) (int) (int) = NULL static
Function triggered on selecting a keyboard.
Referenced by on_keyboard_type_toggled(), pet_keyboard_type_widget_create(), and pet_keyboard_type_widget_set_callback().