x128: userport/userport_rtc_58321a.h File Reference
userport_rtc_58321a.h File Reference
#include "types.h"
Functions
int userport_rtc_58321a_resources_init (void)
int userport_rtc_58321a_cmdline_options_init (void)
void userport_rtc_58321a_resources_shutdown (void)
Variables
int userport_rtc_58321a_enable
Function Documentation
userport_rtc_58321a_cmdline_options_init()
int userport_rtc_58321a_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
userport_rtc_58321a_resources_init()
int userport_rtc_58321a_resources_init (void)
Referenced by machine_resources_init().
userport_rtc_58321a_resources_shutdown()
void userport_rtc_58321a_resources_shutdown (void)
Referenced by machine_resources_shutdown().
Variable Documentation
userport_rtc_58321a_enable
int userport_rtc_58321a_enable extern