vsid: raster/raster.c File Reference
raster.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "videoarch.h"
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "raster-cache.h"
#include "raster-canvas.h"
#include "raster-changes.h"
#include "raster-modes.h"
#include "raster-resources.h"
#include "raster-sprite-status.h"
#include "raster-sprite.h"
#include "raster.h"
#include "screenshot.h"
#include "types.h"
#include "util.h"
#include "video.h"
#include "viewport.h"
Data Structures
struct raster_list_t
Typedefs
typedef struct raster_list_t raster_list_t
Functions
static int raster_calc_frame_buffer_width (raster_t *raster)
void raster_calculate_padding_size (unsigned int fb_width, unsigned int fb_height, unsigned int *padded_size, unsigned int *unpadded_offset)
static int raster_draw_buffer_alloc (video_canvas_t *canvas, unsigned int fb_width, unsigned int fb_height, unsigned int *fb_pitch)
static void raster_draw_buffer_free (video_canvas_t *canvas)
static void raster_draw_buffer_clear (video_canvas_t *canvas, uint8_t value, unsigned int fb_width, unsigned int fb_height, unsigned int fb_pitch)
void raster_draw_buffer_ptr_update (raster_t *raster)
static int raster_realize_frame_buffer (raster_t *raster)
static int realize_canvas (raster_t *raster)
called from raster_realize()
static int perform_mode_change (raster_t *raster)
int raster_init (raster_t *raster, unsigned int num_modes)
void raster_reset (raster_t *raster)
void raster_mode_change (void)
seemingly dead code
void raster_new_cache (raster_t *raster, unsigned int screen_height)
static void raster_destroy_cache (raster_t *raster, unsigned int screen_height)
void raster_set_geometry (raster_t *raster, unsigned int canvas_width, unsigned int canvas_height, unsigned int screen_width, unsigned int screen_height, unsigned int gfx_width, unsigned int gfx_height, unsigned int text_width, unsigned int text_height, unsigned int gfx_position_x, unsigned int gfx_position_y, int gfx_area_moves, unsigned int first_displayed_line, unsigned int last_displayed_line, unsigned int extra_offscreen_border_left, unsigned int extra_offscreen_border_right)
int raster_realize (raster_t *raster)
called from init_raster() in the videochip code
static void raster_destroy_raster (raster_t *raster)
void raster_force_repaint (raster_t *raster)
void raster_enable_cache (raster_t *raster, int enable)
void raster_set_canvas_refresh (raster_t *raster, int enable)
void raster_screenshot (raster_t *raster, screenshot_t *screenshot)
void raster_async_refresh (raster_t *raster, struct canvas_refresh_s *ref)
void raster_shutdown (raster_t *raster)
Variables
static raster_list_t * ActiveRasters = NULL
static int raster_realize_init_done = 0
Typedef Documentation
raster_list_t
typedef struct raster_list_t raster_list_t
Function Documentation
perform_mode_change()
static int perform_mode_change (raster_t * raster) static
Referenced by raster_mode_change().
raster_async_refresh()
void raster_async_refresh (raster_t * raster, struct canvas_refresh_s * ref)
Referenced by vicii_async_refresh().
raster_calc_frame_buffer_width()
static int raster_calc_frame_buffer_width (raster_t * raster) static
Referenced by raster_draw_buffer_ptr_update(), and raster_realize_frame_buffer().
raster_calculate_padding_size()
void raster_calculate_padding_size (unsigned int fb_width, unsigned int fb_height, unsigned int * padded_size, unsigned int * unpadded_offset)
Referenced by raster_draw_buffer_alloc(), raster_snapshot_read(), and raster_snapshot_write().
raster_destroy_cache()
static void raster_destroy_cache (raster_t * raster, unsigned int screen_height) static
Referenced by raster_set_geometry(), and raster_shutdown().
raster_destroy_raster()
static void raster_destroy_raster (raster_t * raster) static
Referenced by raster_shutdown().
raster_draw_buffer_alloc()
static int raster_draw_buffer_alloc (video_canvas_t * canvas, unsigned int fb_width, unsigned int fb_height, unsigned int * fb_pitch) static
Referenced by raster_realize_frame_buffer().
raster_draw_buffer_clear()
static void raster_draw_buffer_clear (video_canvas_t * canvas, uint8_t value, unsigned int fb_width, unsigned int fb_height, unsigned int fb_pitch) static
Referenced by raster_realize_frame_buffer().
raster_draw_buffer_free()
static void raster_draw_buffer_free (video_canvas_t * canvas) static
Referenced by raster_realize_frame_buffer(), and raster_shutdown().
raster_draw_buffer_ptr_update()
void raster_draw_buffer_ptr_update (raster_t * raster)
Referenced by raster_line_emulate().
raster_enable_cache()
void raster_enable_cache (raster_t * raster, int enable)
Referenced by set_video_cache_enabled().
raster_force_repaint()
void raster_force_repaint (raster_t * raster)
Referenced by perform_mode_change(), raster_enable_cache(), and vicii_snapshot_read_module().
raster_init()
int raster_init (raster_t * raster, unsigned int num_modes)
Todo:
FIXME: dead code
Referenced by init_raster().
raster_mode_change()
void raster_mode_change (void)
seemingly dead code
Referenced by vicii_change_timing().
raster_new_cache()
void raster_new_cache (raster_t * raster, unsigned int screen_height)
Referenced by raster_set_geometry().
raster_realize()
int raster_realize (raster_t * raster)
called from init_raster() in the videochip code
Referenced by init_raster().
raster_realize_frame_buffer()
static int raster_realize_frame_buffer (raster_t * raster) static
Referenced by raster_set_geometry(), and realize_canvas().
raster_reset()
void raster_reset (raster_t * raster)
Referenced by raster_init(), and vicii_reset().
raster_screenshot()
void raster_screenshot (raster_t * raster, screenshot_t * screenshot)
Referenced by vicii_screenshot().
raster_set_canvas_refresh()
void raster_set_canvas_refresh (raster_t * raster, int enable)
Referenced by raster_init(), and vicii_set_canvas_refresh().
raster_set_geometry()
void raster_set_geometry (raster_t * raster, unsigned int canvas_width, unsigned int canvas_height, unsigned int screen_width, unsigned int screen_height, unsigned int gfx_width, unsigned int gfx_height, unsigned int text_width, unsigned int text_height, unsigned int gfx_position_x, unsigned int gfx_position_y, int gfx_area_moves, unsigned int first_displayed_line, unsigned int last_displayed_line, unsigned int extra_offscreen_border_left, unsigned int extra_offscreen_border_right)
Referenced by vicii_set_geometry().
raster_shutdown()
void raster_shutdown (raster_t * raster)
Referenced by vicii_shutdown().
realize_canvas()
static int realize_canvas (raster_t * raster) static
called from raster_realize()
Referenced by raster_realize().
Variable Documentation
ActiveRasters
raster_list_t* ActiveRasters = NULL static
Referenced by raster_destroy_raster(), raster_mode_change(), and raster_realize().
raster_realize_init_done
int raster_realize_init_done = 0 static
Referenced by raster_destroy_raster(), and raster_realize().