x128: monitor/monitor_binary.c File Reference
monitor_binary.c File Reference
Monitor implementation - binary network access.
#include "vice.h"
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include "archdep_defs.h"
#include "cmdline.h"
#include "drive.h"
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "kbdbuf.h"
#include "monitor.h"
#include "monitor_binary.h"
#include "montypes.h"
#include "resources.h"
#include "uiapi.h"
#include "util.h"
#include "vicesocket.h"
#include "machine.h"
#include "screenshot.h"
#include "machine-video.h"
#include "palette.h"
#include "mon_breakpoint.h"
#include "mon_file.h"
#include "mon_register.h"
#include "version.h"
Data Structures
struct binary_command_s
Macros
#define ADDR_LIMIT(x) ((uint16_t)(addr_mask(x)))
#define ASC_STX 0x02
#define MON_BINARY_API_VERSION 0x02
#define MON_EVENT_ID 0xffffffff
#define BUFFER_LINE_START(i, n) ((i)->draw_buffer + (n) * (i)->draw_buffer_line_size)
Typedefs
typedef enum t_binary_command BINARY_COMMAND
typedef enum t_binary_response BINARY_RESPONSE
typedef enum t_mon_error BINARY_ERROR
typedef enum t_display_get_mode DISPLAY_GET_MODE
typedef enum t_mon_resource_type MON_RESOURCE_TYPE
typedef struct binary_command_s binary_command_t
Enumerations
enum t_binary_command {
e_MON_CMD_INVALID = 0x00 ,
e_MON_CMD_MEM_GET = 0x01 ,
e_MON_CMD_MEM_SET = 0x02 ,
e_MON_CMD_CHECKPOINT_GET = 0x11 ,
e_MON_CMD_CHECKPOINT_SET = 0x12 ,
e_MON_CMD_CHECKPOINT_DELETE = 0x13 ,
e_MON_CMD_CHECKPOINT_LIST = 0x14 ,
e_MON_CMD_CHECKPOINT_TOGGLE = 0x15 ,
e_MON_CMD_CONDITION_SET = 0x22 ,
e_MON_CMD_REGISTERS_GET = 0x31 ,
e_MON_CMD_REGISTERS_SET = 0x32 ,
e_MON_CMD_DUMP = 0x41 ,
e_MON_CMD_UNDUMP = 0x42 ,
e_MON_CMD_RESOURCE_GET = 0x51 ,
e_MON_CMD_RESOURCE_SET = 0x52 ,
e_MON_CMD_ADVANCE_INSTRUCTIONS = 0x71 ,
e_MON_CMD_KEYBOARD_FEED = 0x72 ,
e_MON_CMD_EXECUTE_UNTIL_RETURN = 0x73 ,
e_MON_CMD_PING = 0x81 ,
e_MON_CMD_BANKS_AVAILABLE = 0x82 ,
e_MON_CMD_REGISTERS_AVAILABLE = 0x83 ,
e_MON_CMD_DISPLAY_GET = 0x84 ,
e_MON_CMD_VICE_INFO = 0x85 ,
e_MON_CMD_PALETTE_GET = 0x91 ,
e_MON_CMD_JOYPORT_SET = 0xa2 ,
e_MON_CMD_USERPORT_SET = 0xb2 ,
e_MON_CMD_EXIT = 0xaa ,
e_MON_CMD_QUIT = 0xbb ,
e_MON_CMD_RESET = 0xcc ,
e_MON_CMD_AUTOSTART = 0xdd
}
enum t_binary_response {
e_MON_RESPONSE_INVALID = 0x00 ,
e_MON_RESPONSE_MEM_GET = 0x01 ,
e_MON_RESPONSE_MEM_SET = 0x02 ,
e_MON_RESPONSE_CHECKPOINT_INFO = 0x11 ,
e_MON_RESPONSE_CHECKPOINT_DELETE = 0x13 ,
e_MON_RESPONSE_CHECKPOINT_LIST = 0x14 ,
e_MON_RESPONSE_CHECKPOINT_TOGGLE = 0x15 ,
e_MON_RESPONSE_CONDITION_SET = 0x22 ,
e_MON_RESPONSE_REGISTER_INFO = 0x31 ,
e_MON_RESPONSE_DUMP = 0x41 ,
e_MON_RESPONSE_UNDUMP = 0x42 ,
e_MON_RESPONSE_RESOURCE_GET = 0x51 ,
e_MON_RESPONSE_RESOURCE_SET = 0x52 ,
e_MON_RESPONSE_JAM = 0x61 ,
e_MON_RESPONSE_STOPPED = 0x62 ,
e_MON_RESPONSE_RESUMED = 0x63 ,
e_MON_RESPONSE_ADVANCE_INSTRUCTIONS = 0x71 ,
e_MON_RESPONSE_KEYBOARD_FEED = 0x72 ,
e_MON_RESPONSE_EXECUTE_UNTIL_RETURN = 0x73 ,
e_MON_RESPONSE_PING = 0x81 ,
e_MON_RESPONSE_BANKS_AVAILABLE = 0x82 ,
e_MON_RESPONSE_REGISTERS_AVAILABLE = 0x83 ,
e_MON_RESPONSE_DISPLAY_GET = 0x84 ,
e_MON_RESPONSE_VICE_INFO = 0x85 ,
e_MON_RESPONSE_PALETTE_GET = 0x91 ,
e_MON_RESPONSE_JOYPORT_SET = 0xa2 ,
e_MON_RESPONSE_USERPORT_SET = 0xb2 ,
e_MON_RESPONSE_EXIT = 0xaa ,
e_MON_RESPONSE_QUIT = 0xbb ,
e_MON_RESPONSE_RESET = 0xcc ,
e_MON_RESPONSE_AUTOSTART = 0xdd
}
enum t_mon_error {
e_MON_ERR_OK = 0x00 ,
e_MON_ERR_OBJECT_MISSING = 0x01 ,
e_MON_ERR_INVALID_MEMSPACE = 0x02 ,
e_MON_ERR_CMD_INVALID_LENGTH = 0x80 ,
e_MON_ERR_INVALID_PARAMETER = 0x81 ,
e_MON_ERR_CMD_INVALID_API_VERSION = 0x82 ,
e_MON_ERR_CMD_INVALID_TYPE = 0x83 ,
e_MON_ERR_CMD_FAILURE = 0x8f
}
enum t_display_get_mode { e_DISPLAY_GET_MODE_INDEXED8 = 0x00 }
enum t_mon_resource_type {
e_MON_RESOURCE_TYPE_STRING = 0x00 ,
e_MON_RESOURCE_TYPE_INT = 0x01
}
Functions
int monitor_binary_transmit (const unsigned char *buffer, size_t buffer_length)
static void monitor_binary_quit (void)
int monitor_binary_receive (unsigned char *buffer, size_t buffer_length)
static int monitor_binary_data_available (void)
void monitor_check_binary (void)
static unsigned char * write_uint16 (uint16_t input, unsigned char *output)
Write uint16 to buffer and return pointer to byte after.
static unsigned char * write_uint32 (uint32_t input, unsigned char *output)
Write uint32 to buffer and return pointer to byte after.
static unsigned char * write_string (uint8_t length, unsigned char *input, unsigned char *output)
Write string to buffer and return pointer to byte after.
static uint32_t little_endian_to_uint32 (unsigned char *input)
Read 32bit little endian value from buffer to uint32 value.
static uint16_t little_endian_to_uint16 (unsigned char *input)
Read 16bit little endian value from buffer to uint16 value.
static void monitor_binary_response (uint32_t length, BINARY_RESPONSE response_type, BINARY_ERROR errorcode, uint32_t request_id, unsigned char *body)
static void monitor_binary_error (BINARY_ERROR errorcode, uint32_t request_id)
static void monitor_binary_response_stopped (uint32_t request_id)
static void monitor_binary_response_resumed (uint32_t request_id)
ui_jam_action_t monitor_binary_ui_jam_dialog (const char *format,...)
static bool ignore_fake_register (mon_reg_list_t *reg)
static MEMSPACE get_requested_memspace (uint8_t requested_memspace)
static uint8_t memspace_to_uint8_t (MEMSPACE mem)
static void monitor_binary_response_register_info (uint32_t request_id, MEMSPACE memspace)
void monitor_binary_event_opened (void)
called when the monitor is opened
void monitor_binary_event_closed (void)
called when the monitor is closed
void monitor_binary_response_checkpoint_info (uint32_t request_id, mon_checkpoint_t *checkpt, bool hit)
Responds with information about a checkpoint.
static void monitor_binary_process_ping (binary_command_t *command)
static void monitor_binary_process_checkpoint_get (binary_command_t *command)
static void monitor_binary_process_checkpoint_set (binary_command_t *command)
static void monitor_binary_process_checkpoint_delete (binary_command_t *command)
static void monitor_binary_process_checkpoint_list (binary_command_t *command)
static void monitor_binary_process_checkpoint_toggle (binary_command_t *command)
static void monitor_binary_process_condition_set (binary_command_t *command)
static void monitor_binary_process_advance_instructions (binary_command_t *command)
static void monitor_binary_process_reset (binary_command_t *command)
static void monitor_binary_process_keyboard_feed (binary_command_t *command)
static void monitor_binary_process_execute_until_return (binary_command_t *command)
static void monitor_binary_process_autostart (binary_command_t *command)
static void monitor_binary_process_registers_get (binary_command_t *command)
static void monitor_binary_process_registers_set (binary_command_t *command)
static void monitor_binary_process_dump (binary_command_t *command)
static void monitor_binary_process_undump (binary_command_t *command)
static void monitor_binary_process_resource_get (binary_command_t *command)
static void monitor_binary_process_resource_set (binary_command_t *command)
static void monitor_binary_process_exit (binary_command_t *command)
static void monitor_binary_process_quit (binary_command_t *command)
static void monitor_binary_process_banks_available (binary_command_t *command)
static void monitor_binary_process_registers_available (binary_command_t *command)
static void monitor_binary_screenshot_line_data (screenshot_t *screenshot, uint8_t *data, unsigned int line, DISPLAY_GET_MODE mode)
static void monitor_binary_process_display_get (binary_command_t *command)
static void monitor_binary_process_palette_get (binary_command_t *command)
static void monitor_binary_process_joyport_set (binary_command_t *command)
static void monitor_binary_process_userport_set (binary_command_t *command)
static void monitor_binary_process_vice_info (binary_command_t *command)
static void monitor_binary_process_mem_get (binary_command_t *command)
static void monitor_binary_process_mem_set (binary_command_t *command)
static void monitor_binary_process_command (unsigned char *pbuffer)
static int monitor_binary_activate (void)
int monitor_binary_get_command_line (void)
static int monitor_binary_deactivate (void)
static int set_binary_monitor_enabled (int value, void *param)
set the binary monitor to the enabled or disabled state
static int set_binary_server_address (const char *name, void *param)
set the network address of the network monitor
int monitor_binary_resources_init (void)
initialize the binary monitor resources
void monitor_binary_resources_shutdown (void)
uninitialize the network monitor resources
int monitor_binary_cmdline_options_init (void)
initialize the command-line options'
int monitor_is_binary (void)
vice_network_socket_t * monitor_binary_get_connected_socket (void)
Variables
static vice_network_socket_t * listen_socket = NULL
static vice_network_socket_t * connected_socket = NULL
static char * monitor_binary_server_address = NULL
static int monitor_binary_enabled = 0
static const resource_string_t resources_string []
string resources used by the binary monitor module
static const resource_int_t resources_int []
integer resources used by the binary monitor module
static const cmdline_option_t cmdline_options []
Detailed Description
Monitor implementation - binary network access.
Author
EmpathicQubit empat.nosp@m.hicq.nosp@m.ubit@.nosp@m.enta.nosp@m.n.gl
Macro Definition Documentation
ADDR_LIMIT
#define ADDR_LIMIT (x) ((uint16_t)(addr_mask(x)))
ASC_STX
#define ASC_STX 0x02
BUFFER_LINE_START
#define BUFFER_LINE_START (i, n) ((i)->draw_buffer + (n) * (i)->draw_buffer_line_size)
MON_BINARY_API_VERSION
#define MON_BINARY_API_VERSION 0x02
MON_EVENT_ID
#define MON_EVENT_ID 0xffffffff
Typedef Documentation
BINARY_COMMAND
typedef enum t_binary_command BINARY_COMMAND
binary_command_t
typedef struct binary_command_s binary_command_t
BINARY_ERROR
typedef enum t_mon_error BINARY_ERROR
BINARY_RESPONSE
typedef enum t_binary_response BINARY_RESPONSE
DISPLAY_GET_MODE
typedef enum t_display_get_mode DISPLAY_GET_MODE
MON_RESOURCE_TYPE
typedef enum t_mon_resource_type MON_RESOURCE_TYPE
Enumeration Type Documentation
t_binary_command
enum t_binary_command
Enumerator
e_MON_CMD_INVALID
e_MON_CMD_MEM_GET
e_MON_CMD_MEM_SET
e_MON_CMD_CHECKPOINT_GET
e_MON_CMD_CHECKPOINT_SET
e_MON_CMD_CHECKPOINT_DELETE
e_MON_CMD_CHECKPOINT_LIST
e_MON_CMD_CHECKPOINT_TOGGLE
e_MON_CMD_CONDITION_SET
e_MON_CMD_REGISTERS_GET
e_MON_CMD_REGISTERS_SET
e_MON_CMD_DUMP
e_MON_CMD_UNDUMP
e_MON_CMD_RESOURCE_GET
e_MON_CMD_RESOURCE_SET
e_MON_CMD_ADVANCE_INSTRUCTIONS
e_MON_CMD_KEYBOARD_FEED
e_MON_CMD_EXECUTE_UNTIL_RETURN
e_MON_CMD_PING
e_MON_CMD_BANKS_AVAILABLE
e_MON_CMD_REGISTERS_AVAILABLE
e_MON_CMD_DISPLAY_GET
e_MON_CMD_VICE_INFO
e_MON_CMD_PALETTE_GET
e_MON_CMD_JOYPORT_SET
e_MON_CMD_USERPORT_SET
e_MON_CMD_EXIT
e_MON_CMD_QUIT
e_MON_CMD_RESET
e_MON_CMD_AUTOSTART
t_binary_response
enum t_binary_response
Enumerator
e_MON_RESPONSE_INVALID
e_MON_RESPONSE_MEM_GET
e_MON_RESPONSE_MEM_SET
e_MON_RESPONSE_CHECKPOINT_INFO
e_MON_RESPONSE_CHECKPOINT_DELETE
e_MON_RESPONSE_CHECKPOINT_LIST
e_MON_RESPONSE_CHECKPOINT_TOGGLE
e_MON_RESPONSE_CONDITION_SET
e_MON_RESPONSE_REGISTER_INFO
e_MON_RESPONSE_DUMP
e_MON_RESPONSE_UNDUMP
e_MON_RESPONSE_RESOURCE_GET
e_MON_RESPONSE_RESOURCE_SET
e_MON_RESPONSE_JAM
e_MON_RESPONSE_STOPPED
e_MON_RESPONSE_RESUMED
e_MON_RESPONSE_ADVANCE_INSTRUCTIONS
e_MON_RESPONSE_KEYBOARD_FEED
e_MON_RESPONSE_EXECUTE_UNTIL_RETURN
e_MON_RESPONSE_PING
e_MON_RESPONSE_BANKS_AVAILABLE
e_MON_RESPONSE_REGISTERS_AVAILABLE
e_MON_RESPONSE_DISPLAY_GET
e_MON_RESPONSE_VICE_INFO
e_MON_RESPONSE_PALETTE_GET
e_MON_RESPONSE_JOYPORT_SET
e_MON_RESPONSE_USERPORT_SET
e_MON_RESPONSE_EXIT
e_MON_RESPONSE_QUIT
e_MON_RESPONSE_RESET
e_MON_RESPONSE_AUTOSTART
t_display_get_mode
enum t_display_get_mode
Enumerator
e_DISPLAY_GET_MODE_INDEXED8
t_mon_error
enum t_mon_error
Enumerator
e_MON_ERR_OK
e_MON_ERR_OBJECT_MISSING
e_MON_ERR_INVALID_MEMSPACE
e_MON_ERR_CMD_INVALID_LENGTH
e_MON_ERR_INVALID_PARAMETER
e_MON_ERR_CMD_INVALID_API_VERSION
e_MON_ERR_CMD_INVALID_TYPE
e_MON_ERR_CMD_FAILURE
t_mon_resource_type
enum t_mon_resource_type
Enumerator
e_MON_RESOURCE_TYPE_STRING
e_MON_RESOURCE_TYPE_INT
Function Documentation
get_requested_memspace()
static MEMSPACE get_requested_memspace (uint8_t requested_memspace) static
Referenced by monitor_binary_process_checkpoint_set(), monitor_binary_process_mem_get(), monitor_binary_process_mem_set(), monitor_binary_process_registers_available(), monitor_binary_process_registers_get(), and monitor_binary_process_registers_set().
ignore_fake_register()
static bool ignore_fake_register (mon_reg_list_t * reg) static
Referenced by monitor_binary_process_registers_available(), and monitor_binary_response_register_info().
little_endian_to_uint16()
static uint16_t little_endian_to_uint16 (unsigned char * input) static
Read 16bit little endian value from buffer to uint16 value.
Referenced by monitor_binary_process_advance_instructions(), monitor_binary_process_autostart(), monitor_binary_process_checkpoint_set(), monitor_binary_process_joyport_set(), monitor_binary_process_mem_get(), monitor_binary_process_mem_set(), monitor_binary_process_registers_set(), monitor_binary_process_resource_set(), and monitor_binary_process_userport_set().
little_endian_to_uint32()
static uint32_t little_endian_to_uint32 (unsigned char * input) static
Read 32bit little endian value from buffer to uint32 value.
Referenced by monitor_binary_get_command_line(), monitor_binary_process_checkpoint_delete(), monitor_binary_process_checkpoint_get(), monitor_binary_process_checkpoint_toggle(), monitor_binary_process_command(), monitor_binary_process_condition_set(), and monitor_binary_process_resource_set().
memspace_to_uint8_t()
static uint8_t memspace_to_uint8_t (MEMSPACE mem) static
Referenced by monitor_binary_response_checkpoint_info().
monitor_binary_activate()
static int monitor_binary_activate (void) static
Referenced by set_binary_monitor_enabled(), and set_binary_server_address().
monitor_binary_cmdline_options_init()
int monitor_binary_cmdline_options_init (void)
initialize the command-line options'
Returns
0 on success, else -1.
Remarks
Registers the command-line options
Referenced by init_cmdline_options().
monitor_binary_data_available()
static int monitor_binary_data_available (void) static
Referenced by monitor_binary_get_command_line(), and monitor_check_binary().
monitor_binary_deactivate()
static int monitor_binary_deactivate (void) static
Referenced by monitor_binary_resources_shutdown(), set_binary_monitor_enabled(), and set_binary_server_address().
monitor_binary_error()
static void monitor_binary_error (BINARY_ERROR errorcode, uint32_t request_id) static
Referenced by monitor_binary_process_advance_instructions(), monitor_binary_process_autostart(), monitor_binary_process_banks_available(), monitor_binary_process_checkpoint_delete(), monitor_binary_process_checkpoint_get(), monitor_binary_process_checkpoint_set(), monitor_binary_process_checkpoint_toggle(), monitor_binary_process_command(), monitor_binary_process_condition_set(), monitor_binary_process_display_get(), monitor_binary_process_dump(), monitor_binary_process_joyport_set(), monitor_binary_process_keyboard_feed(), monitor_binary_process_mem_get(), monitor_binary_process_mem_set(), monitor_binary_process_palette_get(), monitor_binary_process_registers_available(), monitor_binary_process_registers_get(), monitor_binary_process_registers_set(), monitor_binary_process_reset(), monitor_binary_process_resource_get(), monitor_binary_process_resource_set(), monitor_binary_process_undump(), and monitor_binary_process_userport_set().
monitor_binary_event_closed()
void monitor_binary_event_closed (void)
called when the monitor is closed
Referenced by mon_event_closed().
monitor_binary_event_opened()
void monitor_binary_event_opened (void)
called when the monitor is opened
Referenced by mon_event_opened().
monitor_binary_get_command_line()
int monitor_binary_get_command_line (void)
Referenced by uimon_in().
monitor_binary_get_connected_socket()
vice_network_socket_t * monitor_binary_get_connected_socket (void)
Referenced by uimon_in().
monitor_binary_process_advance_instructions()
static void monitor_binary_process_advance_instructions (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_autostart()
static void monitor_binary_process_autostart (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_banks_available()
static void monitor_binary_process_banks_available (binary_command_t * command) static
Todo:
Better error codes?
Referenced by monitor_binary_process_command().
monitor_binary_process_checkpoint_delete()
static void monitor_binary_process_checkpoint_delete (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_checkpoint_get()
static void monitor_binary_process_checkpoint_get (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_checkpoint_list()
static void monitor_binary_process_checkpoint_list (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_checkpoint_set()
static void monitor_binary_process_checkpoint_set (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_checkpoint_toggle()
static void monitor_binary_process_checkpoint_toggle (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_command()
static void monitor_binary_process_command (unsigned char * pbuffer) static
Referenced by monitor_binary_get_command_line().
monitor_binary_process_condition_set()
static void monitor_binary_process_condition_set (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_display_get()
static void monitor_binary_process_display_get (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_dump()
static void monitor_binary_process_dump (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_execute_until_return()
static void monitor_binary_process_execute_until_return (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_exit()
static void monitor_binary_process_exit (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_joyport_set()
static void monitor_binary_process_joyport_set (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_keyboard_feed()
static void monitor_binary_process_keyboard_feed (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_mem_get()
static void monitor_binary_process_mem_get (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_mem_set()
static void monitor_binary_process_mem_set (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_palette_get()
static void monitor_binary_process_palette_get (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_ping()
static void monitor_binary_process_ping (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_quit()
static void monitor_binary_process_quit (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_registers_available()
static void monitor_binary_process_registers_available (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_registers_get()
static void monitor_binary_process_registers_get (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_registers_set()
static void monitor_binary_process_registers_set (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_reset()
static void monitor_binary_process_reset (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_resource_get()
static void monitor_binary_process_resource_get (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_resource_set()
static void monitor_binary_process_resource_set (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_undump()
static void monitor_binary_process_undump (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_userport_set()
static void monitor_binary_process_userport_set (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_process_vice_info()
static void monitor_binary_process_vice_info (binary_command_t * command) static
Referenced by monitor_binary_process_command().
monitor_binary_quit()
static void monitor_binary_quit (void) static
Referenced by monitor_binary_get_command_line(), monitor_binary_receive(), and monitor_binary_resources_shutdown().
monitor_binary_receive()
int monitor_binary_receive (unsigned char * buffer, size_t buffer_length)
Referenced by monitor_binary_get_command_line().
monitor_binary_resources_init()
int monitor_binary_resources_init (void)
initialize the binary monitor resources
Returns
0 on success, else -1.
Remarks
Registers the string and the integer resources
Referenced by init_resources().
monitor_binary_resources_shutdown()
void monitor_binary_resources_shutdown (void)
uninitialize the network monitor resources
Referenced by cmdline_help(), and machine_shutdown().
monitor_binary_response()
static void monitor_binary_response (uint32_t length, BINARY_RESPONSE response_type, BINARY_ERROR errorcode, uint32_t request_id, unsigned char * body) static
Referenced by monitor_binary_error(), monitor_binary_process_advance_instructions(), monitor_binary_process_autostart(), monitor_binary_process_banks_available(), monitor_binary_process_checkpoint_delete(), monitor_binary_process_checkpoint_list(), monitor_binary_process_checkpoint_toggle(), monitor_binary_process_condition_set(), monitor_binary_process_display_get(), monitor_binary_process_dump(), monitor_binary_process_execute_until_return(), monitor_binary_process_exit(), monitor_binary_process_joyport_set(), monitor_binary_process_keyboard_feed(), monitor_binary_process_mem_get(), monitor_binary_process_mem_set(), monitor_binary_process_palette_get(), monitor_binary_process_ping(), monitor_binary_process_quit(), monitor_binary_process_registers_available(), monitor_binary_process_reset(), monitor_binary_process_resource_get(), monitor_binary_process_resource_set(), monitor_binary_process_undump(), monitor_binary_process_userport_set(), monitor_binary_process_vice_info(), monitor_binary_response_checkpoint_info(), monitor_binary_response_register_info(), monitor_binary_response_resumed(), monitor_binary_response_stopped(), and monitor_binary_ui_jam_dialog().
monitor_binary_response_checkpoint_info()
void monitor_binary_response_checkpoint_info (uint32_t request_id, mon_checkpoint_t * checkpt, bool hit)
Responds with information about a checkpoint.
Parameters
request_id ID of the request
mon_checkpoint_t The checkpoint
hit Is the checkpoint hit in the emulator?
Referenced by mon_breakpoint_event(), monitor_binary_process_checkpoint_get(), monitor_binary_process_checkpoint_list(), and monitor_binary_process_checkpoint_set().
monitor_binary_response_register_info()
static void monitor_binary_response_register_info (uint32_t request_id, MEMSPACE memspace) static
Referenced by monitor_binary_event_opened(), monitor_binary_process_registers_get(), and monitor_binary_process_registers_set().
monitor_binary_response_resumed()
static void monitor_binary_response_resumed (uint32_t request_id) static
Referenced by monitor_binary_event_closed().
monitor_binary_response_stopped()
static void monitor_binary_response_stopped (uint32_t request_id) static
Referenced by monitor_binary_event_opened().
monitor_binary_screenshot_line_data()
static void monitor_binary_screenshot_line_data (screenshot_t * screenshot, uint8_t * data, unsigned int line, DISPLAY_GET_MODE mode) static
Referenced by monitor_binary_process_display_get().
monitor_binary_transmit()
int monitor_binary_transmit (const unsigned char * buffer, size_t buffer_length)
Referenced by monitor_binary_response().
monitor_binary_ui_jam_dialog()
ui_jam_action_t monitor_binary_ui_jam_dialog (const char * format, ...)
Referenced by drive_jam(), and machine_jam().
monitor_check_binary()
void monitor_check_binary (void)
Referenced by monitor_vsync_hook(), and uimon_in().
monitor_is_binary()
int monitor_is_binary (void)
Referenced by drive_jam(), machine_jam(), mon_breakpoint_event(), mon_event_closed(), mon_event_opened(), monitor_close(), monitor_open(), and uimon_in().
set_binary_monitor_enabled()
static int set_binary_monitor_enabled (int value, void * param) static
set the binary monitor to the enabled or disabled state
Parameters
val if 0, disable the binary monitor; else, enable it.
param unused
Returns
0 on success. else -1.
set_binary_server_address()
static int set_binary_server_address (const char * name, void * param) static
set the network address of the network monitor
Parameters
name pointer to a buffer which holds the network server addresss.
param unused
Returns
0 on success, else -1.
write_string()
static unsigned char * write_string (uint8_t length, unsigned char * input, unsigned char * output) static
Write string to buffer and return pointer to byte after.
Referenced by monitor_binary_process_banks_available(), monitor_binary_process_registers_available(), and monitor_binary_process_resource_get().
write_uint16()
static unsigned char * write_uint16 (uint16_t input, unsigned char * output) static
Write uint16 to buffer and return pointer to byte after.
Referenced by monitor_binary_process_banks_available(), monitor_binary_process_display_get(), monitor_binary_process_mem_get(), monitor_binary_process_palette_get(), monitor_binary_process_registers_available(), monitor_binary_process_undump(), monitor_binary_response_checkpoint_info(), monitor_binary_response_register_info(), monitor_binary_response_resumed(), monitor_binary_response_stopped(), and monitor_binary_ui_jam_dialog().
write_uint32()
static unsigned char * write_uint32 (uint32_t input, unsigned char * output) static
Write uint32 to buffer and return pointer to byte after.
Referenced by monitor_binary_process_checkpoint_list(), monitor_binary_process_display_get(), monitor_binary_process_resource_get(), monitor_binary_process_vice_info(), monitor_binary_response(), and monitor_binary_response_checkpoint_info().
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-binarymonitor", SET_RESOURCE,  0 ,
      NULL, NULL, "BinaryMonitorServer", (resource_value_t)1,
      NULL, "Enable binary monitor" },
    { "+binarymonitor", SET_RESOURCE,  0 ,
      NULL, NULL, "BinaryMonitorServer", (resource_value_t)0,
      NULL, "Disable binary monitor" },
    { "-binarymonitoraddress", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "BinaryMonitorServerAddress", NULL,
      "<Name>", "The local address the binary monitor should bind to" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by monitor_binary_cmdline_options_init().
connected_socket
vice_network_socket_t* connected_socket = NULL static
Referenced by monitor_binary_data_available(), monitor_binary_get_connected_socket(), monitor_binary_quit(), monitor_binary_receive(), monitor_binary_transmit(), and monitor_is_binary().
listen_socket
vice_network_socket_t* listen_socket = NULL static
Referenced by monitor_binary_activate(), monitor_binary_data_available(), and monitor_binary_deactivate().
monitor_binary_enabled
int monitor_binary_enabled = 0 static
Referenced by set_binary_monitor_enabled(), and set_binary_server_address().
monitor_binary_server_address
char* monitor_binary_server_address = NULL static
Referenced by monitor_binary_activate(), monitor_binary_resources_shutdown(), and set_binary_server_address().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "BinaryMonitorServer", 0, RES_EVENT_STRICT, (resource_value_t)0,
      &monitor_binary_enabled, set_binary_monitor_enabled, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
integer resources used by the binary monitor module
Referenced by monitor_binary_resources_init().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "BinaryMonitorServerAddress", "ip4://127.0.0.1:6502", RES_EVENT_NO, NULL,
      &monitor_binary_server_address, set_binary_server_address, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
string resources used by the binary monitor module
Referenced by monitor_binary_resources_init().