vsid: arch/gtk3/uihotkeysload.c File Reference
uihotkeysload.c File Reference
File dialog to load a hotkeys file.
#include "vice.h"
#include <gtk/gtk.h>
#include "debug_gtk3.h"
#include "filechooserhelpers.h"
#include "openfiledialog.h"
#include "resources.h"
#include "uiactions.h"
#include "uihotkeysload.h"
Functions
static void on_destroy (GtkDialog *self, gpointer unused)
Handler for the 'destroy' event of the dialog.
static void load_callback (GtkDialog *self, gchar *filename, gpointer data)
Callback for the dialog's response handler.
void ui_hotkeys_load_dialog_show (void(*callback)(gboolean))
Show dialog to load hotkeys file.
Variables
static void(* extra_callback)(gboolean) = NULL
Detailed Description
File dialog to load a hotkeys file.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
load_callback()
static void load_callback (GtkDialog * self, gchar * filename, gpointer data) static
Callback for the dialog's response handler.
Sets resource "HotkeyFile", triggering parsing of file and destroys dialog, marking the UI action ACTION_HOTKEYS_LOAD_FROM finished.
Parameters
[in] self dialog
[in] filename file to load (NULL means canceled)
[in] data extra event data (unused)
Referenced by ui_hotkeys_load_dialog_show().
on_destroy()
static void on_destroy (GtkDialog * self, gpointer unused) static
Handler for the 'destroy' event of the dialog.
Parameters
[in] dialog dialog (unused)
[in] unused extra event data (unused)
Referenced by ui_hotkeys_load_dialog_show().
ui_hotkeys_load_dialog_show()
void ui_hotkeys_load_dialog_show (void(*)(gboolean) callback)
Show dialog to load hotkeys file.
Show file dialog to load hotkeysfile. If callback is set it will be called with a boolean parameter that's TRUE when the user clicked 'Open'.
Parameters
[in] callback function to call on response (optional)
Referenced by hotkeys_load_from_action(), and on_load_from_clicked().
Variable Documentation
extra_callback
void(* extra_callback) (gboolean) (gboolean) = NULL static
Referenced by load_callback(), and ui_hotkeys_load_dialog_show().