vsid: arch/gtk3/widgets/drivemodelwidget.c File Reference
drivemodelwidget.c File Reference
Drive model selection widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "drive-check.h"
#include "drive.h"
#include "driveparallelcablewidget.h"
#include "drivewidgethelpers.h"
#include "machine-drive.h"
#include "resources.h"
#include "drivemodelwidget.h"
Enumerations
enum {
COL_NAME ,
COL_ID ,
COL_COUNT
}
Combo box columns.
Functions
static void on_radio_toggled (GtkWidget *widget, gpointer user_data)
Handler for the 'toggled' event of the radio buttons.
GtkWidget * drive_model_widget_create (int unit)
Create a drive unit selection widget.
void drive_model_widget_update (GtkWidget *widget)
Update the drive type widget.
void drive_model_widget_add_callback (GtkWidget *widget, void(*cb_func)(GtkWidget *, gpointer), gpointer cb_data)
Add custom callback to widget.
static int get_unit_number (GtkWidget *self)
Get drive unit number.
static int get_drive_type (GtkWidget *self)
Get drive type (called model in the UI)
static void on_combo_changed (GtkWidget *self, gpointer data)
Handler for the 'changed' event of the combo box.
static GtkListStore * create_combo_model (GtkWidget *self, gboolean show_all)
Create model for the combo box.
GtkWidget * drive_model_widget_create_combo (int unit, gboolean show_all)
Create drive model combo box.
gboolean drive_model_widget_sync_combo (GtkWidget *widget)
Synchronize the widget with its resource.
int drive_model_widget_value_combo (GtkWidget *widget)
Get current drive model.
Detailed Description
Drive model selection widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
anonymous enum
anonymous enum
Combo box columns.
Enumerator
COL_NAME
drive model name column
COL_ID
drive model id column
COL_COUNT
number of columns
Function Documentation
create_combo_model()
static GtkListStore * create_combo_model (GtkWidget * self, gboolean show_all) static
Create model for the combo box.
Parameters
[in] self drive model widget
[in] show_all show all drive types, use FALSE to only show types supported by the current machine config
Returns
GtkListStore
Todo:
check if supported by current config
Referenced by drive_model_widget_create_combo().
drive_model_widget_add_callback()
void drive_model_widget_add_callback (GtkWidget * widget, void(*)(GtkWidget *, gpointer) cb_func, gpointer cb_data)
Add custom callback to widget.
Adds a user-defined callback function on drive type changes.
Parameters
[in,out] widget drive options widget
[in] cb_func callback function
[in] cb_data data passed with cb_func
Referenced by create_left_layout().
drive_model_widget_create()
GtkWidget * drive_model_widget_create (int unit)
Create a drive unit selection widget.
Creates a widget with four radio buttons, horizontally aligned, to select a drive unit (8-11).
Parameters
[in] unit default drive unit (8-11)
Returns
GtkGrid
drive_model_widget_create_combo()
GtkWidget * drive_model_widget_create_combo (int unit, gboolean show_all)
Create drive model combo box.
Parameters
[in] unit drive unit (8-11)
[in] show_all show all drive types, use FALSE to only show types supported by the current machine config
Returns
GtkComboBox
Referenced by create_left_layout().
drive_model_widget_sync_combo()
gboolean drive_model_widget_sync_combo (GtkWidget * widget)
Synchronize the widget with its resource.
Select current item based on resource without triggering the 'changed' event.
Parameters
[in] widget drive model widget
Returns
TRUE if an item matched the current resource value
Referenced by drive_model_widget_create_combo().
drive_model_widget_update()
void drive_model_widget_update (GtkWidget * widget)
Update the drive type widget.
This reiterates the drive info list to see if any setting changes made drive types available/unavailable.
Parameters
[in,out] widget drive type widget
Todo:
temporary block the resource-set callback
Todo:
temporary block the resource-set callback
Referenced by drive_model_widget_create().
drive_model_widget_value_combo()
int drive_model_widget_value_combo (GtkWidget * widget)
Get current drive model.
Parameters
[in] widget drive model widget
Returns
drive model ID or -1 when no item is selected in the widget
Referenced by on_combo_changed(), and on_model_changed().
get_drive_type()
static int get_drive_type (GtkWidget * self) static
Get drive type (called model in the UI)
Parameters
[in] self combo box
Returns
drive type
Referenced by drive_model_widget_sync_combo(), and on_combo_changed().
get_unit_number()
static int get_unit_number (GtkWidget * self) static
Get drive unit number.
Parameters
[in] self combo box
Returns
unit number
Referenced by create_combo_model(), get_drive_type(), and on_combo_changed().
on_combo_changed()
static void on_combo_changed (GtkWidget * self, gpointer data) static
Handler for the 'changed' event of the combo box.
Trigger user-defined callback on value change.
Parameters
[in] self drive model combo box
[in] data extra event data (unused)
Todo:
flip combo back to previous value?
Referenced by drive_model_widget_create_combo().
on_radio_toggled()
static void on_radio_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the 'toggled' event of the radio buttons.
Parameters
[in] widget radio button
[in] user_data unit number
Referenced by drive_model_widget_create().