vsid: charset.c File Reference
charset.c File Reference
#include "vice.h"
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "charset.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "types.h"
#include "util.h"
Macros
#define ASCII_UNMAPPED '.'
#define PETSCII_UNMAPPED 0x3f
petscii "?"
Functions
static int test_lineend (uint8_t *s)
uint8_t * charset_petconvstring (uint8_t *c, int mode)
static uint8_t petcii_fix_dupes (uint8_t c)
uint8_t charset_p_toascii (uint8_t c, int mode)
uint8_t charset_p_topetscii (uint8_t c)
uint8_t charset_screencode_to_petscii (uint8_t code)
uint8_t charset_petscii_to_screencode (uint8_t code, unsigned int reverse_mode)
void charset_petscii_to_screencode_line (const uint8_t *line, uint8_t **buf, unsigned int *len)
int charset_petscii_to_ucs (uint8_t c)
int charset_ucs_to_utf8 (uint8_t *out, int code, size_t len)
uint8_t * charset_petconv_stralloc (uint8_t *in, int mode)
char * charset_hexstring_to_byte (char *source, char *destination)
char * charset_replace_hexcodes (char *source)
Macro Definition Documentation
ASCII_UNMAPPED
#define ASCII_UNMAPPED '.'
PETSCII_UNMAPPED
#define PETSCII_UNMAPPED 0x3f
petscii "?"
Function Documentation
charset_hexstring_to_byte()
char * charset_hexstring_to_byte (char * source, char * destination)
Referenced by charset_replace_hexcodes().
charset_p_toascii()
uint8_t charset_p_toascii (uint8_t c, int mode)
Referenced by charset_petconv_stralloc(), charset_petconvstring(), charset_petscii_to_ucs(), clipboard_read_screen_output(), mon_petscii_out(), mon_petscii_upper_out(), mon_scrcode_out(), mon_scrcode_upper_out(), native_console_petscii_out(), native_console_petscii_upper_out(), native_console_scrcode_out(), print_char(), uimon_petscii_out(), uimon_petscii_upper_out(), uimon_scrcode_out(), and uimon_scrcode_upper_out().
charset_p_topetscii()
uint8_t charset_p_topetscii (uint8_t c)
< petscii "?"
< petscii "?"
Referenced by charset_petconv_stralloc(), charset_petconvstring(), kbd_buf_parse_string(), and mon_file_open().
charset_petconv_stralloc()
uint8_t * charset_petconv_stralloc (uint8_t * in, int mode)
Referenced by image_contents_file_to_string(), image_contents_filename_to_string(), image_contents_filetype_to_string(), and image_contents_to_string().
charset_petconvstring()
uint8_t * charset_petconvstring (uint8_t * c, int mode)
Todo:
Fix these functions to use size_t for lenght, not int
Referenced by _limit_longname(), autostart_autodetect_opt_prgname(), cbmfile_open(), cbmfile_rename(), cbmfile_scratch(), copystring(), create_disk_image(), expand_shortname(), fliplist_load_list(), fsdevice_flush(), fsdevice_open(), fsdevice_open_directory(), fsdevice_open_file(), mon_drive_execute_disk_cmd(), and paste_callback().
charset_petscii_to_screencode()
uint8_t charset_petscii_to_screencode (uint8_t code, unsigned int reverse_mode)
Referenced by charset_petscii_to_screencode_line(), vice_gtk3_petscii_to_utf8_petme(), and vice_gtk3_petscii_to_utf8_petme64().
charset_petscii_to_screencode_line()
void charset_petscii_to_screencode_line (const uint8_t * line, uint8_t ** buf, unsigned int * len)
charset_petscii_to_ucs()
int charset_petscii_to_ucs (uint8_t c)
Referenced by charset_petconv_stralloc().
charset_replace_hexcodes()
char * charset_replace_hexcodes (char * source)
Referenced by autostart_autodetect_opt_prgname().
charset_screencode_to_petscii()
uint8_t charset_screencode_to_petscii (uint8_t code)
Referenced by clipboard_read_screen_output(), mon_scrcode_out(), mon_scrcode_upper_out(), native_console_scrcode_out(), uimon_scrcode_out(), uimon_scrcode_upper_out(), and vice_gtk3_scrcode_to_utf8().
charset_ucs_to_utf8()
int charset_ucs_to_utf8 (uint8_t * out, int code, size_t len)
Todo:
FIXME: len should be size_t
Referenced by charset_petconv_stralloc().
petcii_fix_dupes()
static uint8_t petcii_fix_dupes (uint8_t c) static
Referenced by charset_p_toascii(), and charset_p_topetscii().
test_lineend()
static int test_lineend (uint8_t * s) static
Referenced by charset_petconv_stralloc(), and charset_petconvstring().