vsid: printerdrv/driver-select.c File Reference
driver-select.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include "cmdline.h"
#include "driver-select.h"
#include "drv-ascii.h"
#include "lib.h"
#include "log.h"
#include "printer.h"
#include "resources.h"
#include "types.h"
#include "util.h"
Macros
#define PROP_CHECK_FUNC(property)
Define printer driver property check function.
Functions
static bool check_property (const char *name, bool(*propcheck)(const driver_select_t *))
Check boolean propery of a printer driver.
static bool check_prop_printer (const driver_select_t *drv)
property check functions
static bool check_prop_plotter (const driver_select_t *drv)
static bool check_prop_iec (const driver_select_t *drv)
static bool check_prop_ieee488 (const driver_select_t *drv)
static bool check_prop_userport (const driver_select_t *drv)
static bool check_prop_text (const driver_select_t *drv)
static bool check_prop_graphics (const driver_select_t *drv)
bool driver_select_is_printer (const char *drv_name)
Determine if drive is a printer driver.
bool driver_select_is_plotter (const char *drv_name)
Determine if driver is a plotter driver.
bool driver_select_has_iec_bus (const char *drv_name)
Determine if driver supports an IEC bus-connected device.
bool driver_select_has_ieee488_bus (const char *drv_name)
Determine if driver supports an IEEE-488 bus-connected device.
bool driver_select_has_userport (const char *drv_name)
Determine if driver supports a userport-connected device.
bool driver_select_has_text_output (const char *drv_name)
Determine if driver supports text output.
bool driver_select_has_graphics_output (const char *drv_name)
Determine if driver supports graphics output.
const driver_select_list_t * driver_select_get_drivers (void)
Get list of registered printer drivers.
static int set_printer_driver (const char *name, void *param)
int driver_select_init_resources (void)
int driver_select_userport_init_resources (void)
int driver_select_init_cmdline_options (void)
int driver_select_userport_init_cmdline_options (void)
void driver_select_init (void)
void driver_select_register (driver_select_t *drv_select)
void driver_select_shutdown (void)
int driver_select (unsigned int prnr)
int driver_select_open (unsigned int prnr, unsigned int secondary)
void driver_select_close (unsigned int prnr, unsigned int secondary)
int driver_select_putc (unsigned int prnr, unsigned int secondary, uint8_t b)
int driver_select_getc (unsigned int prnr, unsigned int secondary, uint8_t *b)
int driver_select_flush (unsigned int prnr, unsigned int secondary)
int driver_select_formfeed (unsigned int prnr)
called by printer.c:printer_formfeed()
Variables
static log_t driver_select_log = ((log_t)-1)
static driver_select_t driver [4]
Currently used printer driver.
static driver_select_list_t * driver_select_list = NULL
Pointer to registered printer driver.
static driver_select_list_t * driver_select_list_tail = NULL
Pointer to tail of registered printer driver list.
static const resource_string_t resources_string []
static const resource_string_t resources_string_userport []
static const cmdline_option_t cmdline_options []
static const cmdline_option_t cmdline_options_userport []
Macro Definition Documentation
PROP_CHECK_FUNC
#define PROP_CHECK_FUNC (property)
Value:
    static bool check_prop_##property(const driver_select_t *drv) \
    {                                                             \
        return drv->property;                                     \
    }
Define printer driver property check function.
Parameters
[in] property boolean member to test for true
Function Documentation
check_prop_graphics()
static bool check_prop_graphics (const driver_select_t * drv) static
Referenced by driver_select_has_graphics_output().
check_prop_iec()
static bool check_prop_iec (const driver_select_t * drv) static
Referenced by driver_select_has_iec_bus().
check_prop_ieee488()
static bool check_prop_ieee488 (const driver_select_t * drv) static
Referenced by driver_select_has_ieee488_bus().
check_prop_plotter()
static bool check_prop_plotter (const driver_select_t * drv) static
Referenced by driver_select_is_plotter().
check_prop_printer()
static bool check_prop_printer (const driver_select_t * drv) static
property check functions
Referenced by driver_select_is_printer().
check_prop_text()
static bool check_prop_text (const driver_select_t * drv) static
Referenced by driver_select_has_text_output().
check_prop_userport()
static bool check_prop_userport (const driver_select_t * drv) static
Referenced by driver_select_has_userport().
check_property()
static bool check_property (const char * name, bool(*)(const driver_select_t *) propcheck) static
Check boolean propery of a printer driver.
Iterate registered printer drivers for drive name and call function propcheck to test a boolean propery.
Parameters
[in] name printer driver name
[in] propcheck function to call to check property
Returns
true if name is valid and propcheck returned true, false otherwise
Referenced by driver_select_has_graphics_output(), driver_select_has_iec_bus(), driver_select_has_ieee488_bus(), driver_select_has_text_output(), driver_select_has_userport(), driver_select_is_plotter(), and driver_select_is_printer().
driver_select()
int driver_select (unsigned int prnr)
Referenced by drv_ascii_init_resources(), drv_mps803_init_resources(), drv_nl10_init_resources(), and drv_raw_init_resources().
driver_select_close()
void driver_select_close (unsigned int prnr, unsigned int secondary)
Referenced by close_pr(), and userport_printer_enable().
driver_select_flush()
int driver_select_flush (unsigned int prnr, unsigned int secondary)
Referenced by flush_pr().
driver_select_formfeed()
int driver_select_formfeed (unsigned int prnr)
called by printer.c:printer_formfeed()
Referenced by printer_formfeed(), and printer_shutdown().
driver_select_get_drivers()
const driver_select_list_t * driver_select_get_drivers (void)
Get list of registered printer drivers.
Returns
singly-linked list of registered drivers
Referenced by printer_driver_widget_create().
driver_select_getc()
int driver_select_getc (unsigned int prnr, unsigned int secondary, uint8_t * b)
driver_select_has_graphics_output()
bool driver_select_has_graphics_output (const char * drv_name)
Determine if driver supports graphics output.
Parameters
[in] drv_name driver name
Returns
true if drv_name supports graphics output
Referenced by driver_radio_callback().
driver_select_has_iec_bus()
bool driver_select_has_iec_bus (const char * drv_name)
Determine if driver supports an IEC bus-connected device.
Parameters
[in] drv_name driver name
Returns
true if drv_name is an IEC driver
driver_select_has_ieee488_bus()
bool driver_select_has_ieee488_bus (const char * drv_name)
Determine if driver supports an IEEE-488 bus-connected device.
Parameters
[in] drv_name driver name
Returns
true if drv_name is an IEEE-488 driver
driver_select_has_text_output()
bool driver_select_has_text_output (const char * drv_name)
Determine if driver supports text output.
Parameters
[in] drv_name driver name
Returns
true if drv_name supports text output
Referenced by driver_radio_callback().
driver_select_has_userport()
bool driver_select_has_userport (const char * drv_name)
Determine if driver supports a userport-connected device.
Parameters
[in] drv_name driver name
Returns
true if drv_name is a userport driver
Referenced by printer_driver_widget_create(), and set_printer_driver().
driver_select_init()
void driver_select_init (void)
Referenced by printer_init().
driver_select_init_cmdline_options()
int driver_select_init_cmdline_options (void)
Referenced by printer_cmdline_options_init().
driver_select_init_resources()
int driver_select_init_resources (void)
Referenced by printer_resources_init().
driver_select_is_plotter()
bool driver_select_is_plotter (const char * drv_name)
Determine if driver is a plotter driver.
Parameters
[in] drv_name driver name
Returns
true if drv_name is a plotter driver
Referenced by printer_driver_widget_create(), and set_printer_driver().
driver_select_is_printer()
bool driver_select_is_printer (const char * drv_name)
Determine if drive is a printer driver.
Parameters
[in] drv_name driver name
Returns
true if drv_name is a printer driver
Referenced by printer_driver_widget_create(), and set_printer_driver().
driver_select_open()
int driver_select_open (unsigned int prnr, unsigned int secondary)
Referenced by open_pr(), and userport_printer_enable().
driver_select_putc()
int driver_select_putc (unsigned int prnr, unsigned int secondary, uint8_t b)
Referenced by userport_printer_store_pa2(), and write_pr().
driver_select_register()
void driver_select_register (driver_select_t * drv_select)
Referenced by drv_1520_init_resources(), drv_ascii_init_resources(), drv_mps803_init_resources(), drv_nl10_init_resources(), and drv_raw_init_resources().
driver_select_shutdown()
void driver_select_shutdown (void)
Referenced by printer_shutdown().
driver_select_userport_init_cmdline_options()
int driver_select_userport_init_cmdline_options (void)
Referenced by printer_userport_cmdline_options_init().
driver_select_userport_init_resources()
int driver_select_userport_init_resources (void)
Referenced by printer_userport_resources_init().
set_printer_driver()
static int set_printer_driver (const char * name, void * param) static
< CBM devnr 4
< CBM devnr 5
< CBM devnr 6
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-pr4drv", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer4Driver", NULL,
      "<Name>", "Specify name of printer driver for device #4. (ascii/raw/mps801/mps802/mps803/220/4032/8023/nl10)" },
    { "-pr5drv", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer5Driver", NULL,
      "<Name>", "Specify name of printer driver for device #5. (ascii/raw/mps801/mps802/mps803/220/4032/8023/nl10)" },
    { "-pr6drv", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "Printer6Driver", NULL,
      "<Name>", "Specify name of printer driver for device #6. (1520/raw)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by driver_select_init_cmdline_options().
cmdline_options_userport
const cmdline_option_t cmdline_options_userport[] static
Initial value:
=
{
    { "-pruserdrv", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "PrinterUserportDriver", NULL,
      "<Name>", "Specify name of printer driver for the userport printer. (ascii/nl10/raw)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by driver_select_userport_init_cmdline_options().
driver
driver_select_t driver[4] static
Currently used printer driver.
Referenced by create_inner_grid(), create_printer_widget(), create_video_driver_list(), driver_select(), driver_select_close(), driver_select_flush(), driver_select_formfeed(), driver_select_getc(), driver_select_open(), driver_select_putc(), drv_1520_init_resources(), ffmpeg_widget_create(), gfxoutput_cmdline_options_init(), gfxoutput_resources_init(), gfxoutput_shutdown(), on_radio_toggled(), on_save_video_filename(), printer_driver_widget_update(), screenshot_get_fext_for_format(), set_printer_driver(), and settings_snapshot_widget_create().
driver_select_list
driver_select_list_t* driver_select_list = NULL static
Pointer to registered printer driver.
Referenced by check_property(), driver_select_get_drivers(), driver_select_register(), driver_select_shutdown(), and set_printer_driver().
driver_select_list_tail
driver_select_list_t* driver_select_list_tail = NULL static
Pointer to tail of registered printer driver list.
Referenced by driver_select_register().
driver_select_log
log_t driver_select_log = ((log_t)-1) static
Referenced by driver_select(), driver_select_close(), driver_select_flush(), driver_select_formfeed(), driver_select_init(), driver_select_open(), and set_printer_driver().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "Printer4Driver", "mps803", RES_EVENT_NO, NULL,
      (char **)&driver[0].drv_name, set_printer_driver, (void *)0 },
    { "Printer5Driver", "ascii", RES_EVENT_NO, NULL,
      (char **)&driver[1].drv_name, set_printer_driver, (void *)1 },
    { "Printer6Driver", "1520", RES_EVENT_NO, NULL,
      (char **)&driver[2].drv_name, set_printer_driver, (void *)2 },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by driver_select_init_resources().
resources_string_userport
const resource_string_t resources_string_userport[] static
Initial value:
= {
    { "PrinterUserportDriver", "ascii", RES_EVENT_NO, NULL,
      (char **)&driver[3].drv_name, set_printer_driver, (void *)3 },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by driver_select_userport_init_resources().