x128: raster/raster-resources.h File Reference
raster-resources.h File Reference
Functions
int raster_resources_chip_init (const char *chipname, struct raster_s *raster, struct video_chip_cap_s *video_chip_cap)
void raster_resources_chip_shutdown (struct raster_s *raster)
void raster_resources_shutdown (void)
Function Documentation
raster_resources_chip_init()
int raster_resources_chip_init (const char * chipname, struct raster_s * raster, struct video_chip_cap_s * video_chip_cap)
Referenced by vdc_resources_init(), and vicii_resources_init().
raster_resources_chip_shutdown()
void raster_resources_chip_shutdown (struct raster_s * raster)
Referenced by raster_shutdown().
raster_resources_shutdown()
void raster_resources_shutdown (void)