vsid: arch/gtk3/widgets/settings_video.c File Reference
settings_video.c File Reference
Settings widget to control video settings.
#include "vice.h"
#include <gtk/gtk.h>
#include <string.h>
#include "debug_gtk3.h"
#include "machine.h"
#include "ui.h"
#include "uivideo.h"
#include "vice_gtk3.h"
#include "videobordermodewidget.h"
#include "videopalettewidget.h"
#include "videorenderfilterwidget.h"
#include "settings_video.h"
Functions
static void render_filter_callback (GtkWidget *widget, int value)
Callback for changes of the render-filter widgets.
static void double_size_callback (GtkWidget *widget, gboolean state)
Callback for changes of the "Double Size" widget.
static void on_hide_vdc_toggled (GtkWidget *check, gpointer data)
Event handler for the 'Hide VDC Window' checkbox.
static GtkWidget * label_helper (const char *text)
Create left-indented label with Pango markup.
static GtkWidget * create_double_size_widget (const char *chip)
Create "Double Size" checkbox.
static GtkWidget * create_double_scan_widget (const char *chip)
Create "Double Scan" checkbox.
static GtkWidget * create_vert_stretch_widget (const char *chip)
Create "Vertical Stretch" checkbox.
static GtkWidget * create_audio_leak_widget (const char *chip)
Create "Audio leak emulation" checkbox.
static GtkWidget * create_sprite_sprite_widget (const char *chip)
Create "Sprite-sprite collisions" checkbox.
static GtkWidget * create_sprite_background_widget (const char *chip)
Create "Sprite-background collisions" checkbox.
static GtkWidget * create_vsp_bug_widget (const char *chip)
Create "VSP bug emulation" checkbox.
static GtkWidget * create_render_widget (int index, const char *chip)
Create widget for double size, double scan and vertical stretch.
static GtkWidget * create_misc_widget (int index, const char *chip)
Create widget for audio leak, sprite collisions and VSP bug.
static GtkWidget * create_layout (GtkWidget *parent, const char *chip, int index)
Create a per-chip video settings layout.
GtkWidget * settings_video_widget_create (GtkWidget *parent)
Create video settings widget.
GtkWidget * settings_video_widget_create_vdc (GtkWidget *parent)
Create video settings widget for VDC.
Variables
static GtkWidget * double_size_widget [2] = { NULL, NULL }
double-size widgets
Detailed Description
Settings widget to control video settings.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_audio_leak_widget()
static GtkWidget * create_audio_leak_widget (const char * chip) static
Create "Audio leak emulation" checkbox.
Parameters
[in] chip chip name
Returns
GtkCheckButton
Referenced by create_misc_widget().
create_double_scan_widget()
static GtkWidget * create_double_scan_widget (const char * chip) static
Create "Double Scan" checkbox.
Parameters
[in] chip chip name
Returns
GtkCheckButton
Referenced by create_render_widget().
create_double_size_widget()
static GtkWidget * create_double_size_widget (const char * chip) static
Create "Double Size" checkbox.
Parameters
[in] chip chip name
Returns
GtkCheckButton
Referenced by create_render_widget().
create_layout()
static GtkWidget * create_layout (GtkWidget * parent, const char * chip, int index) static
Create a per-chip video settings layout.
Parameters
[in] parent parent widget, required for dialogs and window switching
[in] chip chip name ("Crtc", "TED", "VDC", "VIC", or "VICII")
[in] index index in the general layout (0 or 1 (x128))
Returns
GtkGrid
Referenced by settings_video_widget_create(), and settings_video_widget_create_vdc().
create_misc_widget()
static GtkWidget * create_misc_widget (int index, const char * chip) static
Create widget for audio leak, sprite collisions and VSP bug.
Parameters
[in] index chip index (using in x128)
[in] chip chip name
Returns
GtkGrid
Referenced by create_layout().
create_render_widget()
static GtkWidget * create_render_widget (int index, const char * chip) static
Create widget for double size, double scan and vertical stretch.
Parameters
[in] index chip index (using in x128)
[in] chip chip name
Returns
GtkGrid
Referenced by create_layout().
create_sprite_background_widget()
static GtkWidget * create_sprite_background_widget (const char * chip) static
Create "Sprite-background collisions" checkbox.
Parameters
[in] chip chip name
Returns
GtkCheckButton
Referenced by create_misc_widget().
create_sprite_sprite_widget()
static GtkWidget * create_sprite_sprite_widget (const char * chip) static
Create "Sprite-sprite collisions" checkbox.
Parameters
[in] chip chip name
Returns
GtkCheckButton
Referenced by create_misc_widget().
create_vert_stretch_widget()
static GtkWidget * create_vert_stretch_widget (const char * chip) static
Create "Vertical Stretch" checkbox.
Parameters
[in] chip chip name
Returns
GtkCheckButton
Referenced by create_render_widget().
create_vsp_bug_widget()
static GtkWidget * create_vsp_bug_widget (const char * chip) static
Create "VSP bug emulation" checkbox.
Parameters
[in] chip chip name
Returns
GtkCheckButton
Referenced by create_misc_widget().
double_size_callback()
static void double_size_callback (GtkWidget * widget, gboolean state) static
Callback for changes of the "Double Size" widget.
Trigger a resize of the primary or secondary window if state is false.
There's no need to trigger a resize here when state is true, than happens automatically by GDK to accomodate for the larger canvas.
Parameters
[in] widget check button (unused)
[in] state check button toggle state
Referenced by create_double_size_widget().
label_helper()
static GtkWidget * label_helper (const char * text) static
Create left-indented label with Pango markup.
Parameters
[in] text text for label (Pango markup allowed)
Returns
GtkLabel
Referenced by create_layout(), and create_misc_widget().
on_hide_vdc_toggled()
static void on_hide_vdc_toggled (GtkWidget * check, gpointer data) static
Event handler for the 'Hide VDC Window' checkbox.
Parameters
[in] check checkbutton triggering the event
[in] data settings dialog
Referenced by create_layout().
render_filter_callback()
static void render_filter_callback (GtkWidget * widget, int value) static
Callback for changes of the render-filter widgets.
Parameters
[in] widget radio group
[in] value new resource value
Referenced by create_layout().
settings_video_widget_create()
GtkWidget * settings_video_widget_create (GtkWidget * parent)
Create video settings widget.
This will create the VICII widget for x128, for the VDC widget use settings_video_create_vdc().
Parameters
[in] parent settings dialog
Returns
GtkGrid
settings_video_widget_create_vdc()
GtkWidget * settings_video_widget_create_vdc (GtkWidget * parent)
Create video settings widget for VDC.
This will create the VDC widget for x128, for the VICII widget use settings_video_create().
Parameters
[in] parent settings dialog
Returns
GtkGrid
Variable Documentation
double_size_widget
GtkWidget* double_size_widget[2] = { NULL, NULL } static
double-size widgets
Used in render_filter_callback() to synchronize the double size widgets' state.
Referenced by create_render_widget(), render_filter_callback(), and settings_video_widget_create().