x128: arch/shared/hotkeys/boolexpr.c File Reference
boolexpr.c File Reference
Boolean expression evaluation.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <ctype.h>
#include <stdarg.h>
#include "lib.h"
#include "boolexpr.h"
Data Structures
struct token_s
Token object.
struct token_list_s
Token list object.
Macros
#define bexpr_debug(...)
Enable debugging messages.
#define ARRAY_LEN(arr) (sizeof arr / sizeof arr[0])
{{{ Types, enums, macros
#define SET_ERROR(errnum)
Set error code (and for now print error code and message on stderr.
#define MAX_TOKEN_LEN 5
Maximum lenght of a token's text.
#define TLIST_INIT { .tokens = NULL, .size = 0, .index = -1 }
Initializer for a token list.
#define TLIST_INITIAL_SIZE 32u
Initial number of available tokens in a token list.
#define token_list_enqueue(list, token) token_list_push(list, token)
Enqueue token onto? token list.
Typedefs
typedef struct token_s token_t
Token object.
typedef struct token_list_s token_list_t
Token list object.
Enumerations
enum {
BEXPR_LTR ,
BEXPR_RTL
}
Associativity of operators.
enum {
BEXPR_UNARY = 1 ,
BEXPR_BINARY = 2
}
Arity of operators.
Functions
const char * bexpr_strerror (int errnum)
Get error message for error number.
static const char * skip_whitespace (const char *s)
{{{ Memory management: reimplementation of VICE's lib_foo() functions
static bool is_token_char (int ch)
Determine if a character is a valid token text character.
static bool is_valid_token_id (int id)
Determine if token ID is valid.
static bool is_operand (int id)
Determine if a token is an operand.
int bexpr_token_parse (const char *text, const char **endptr)
Parse text for a valid token.
static const token_t * token_get (int id)
Get pointer to element in token info array.
static bool token_to_bool (const token_t *token)
Get bool value from token.
static const token_t * token_from_bool (bool value)
Get token for boolean value.
static void token_list_init (token_list_t *list)
}}}
static void token_list_reset (token_list_t *list)
Reset token list for reuse.
static void token_list_resize_maybe (token_list_t *list)
Resize token array if required.
static void token_list_free (token_list_t *list)
Free memory used by token list.
static int token_list_length (const token_list_t *list)
Get length of token list.
static bool token_list_is_empty (const token_list_t *list)
Determine if token list is empty.
static void token_list_push (token_list_t *list, const token_t *token)
Push token onto end of list.
static bool token_list_push_id (token_list_t *list, int id)
Push token by its ID onto end of list.
static const token_t * token_list_peek (const token_list_t *list)
Peek at the end of the list.
static const token_t * token_list_pull (token_list_t *list)
Pull token from end of list.
static const token_t * token_list_token_at (const token_list_t *list, int index)
Get token at index without removing it.
void bexpr_init (void)
Initialize expression for use.
void bexpr_reset (void)
Reset tokenizer and evaluator for new expression.
void bexpr_print (void)
Print tokenized expression on stdout.
void bexpr_free (void)
Free memory used by expression.
bool bexpr_token_add (int id)
Add token to expression.
bool bexpr_tokenize (const char *text)
Generate expression from a string.
static bool infix_to_postfix (void)
Convert infix expression to postfix expression.
static bool eval_postfix (bool *result)
Evaluate postfix expression.
bool bexpr_evaluate (bool *result)
Evaluate boolean expression.
Variables
static const token_t token_info []
}}}
static const int token_chars []
Valid characters in a token's text.
static const char * error_messages []
Error messages.
static char * infix_text = NULL
}}}
static token_list_t infix_tokens = { .tokens = NULL, .size = 0, .index = -1 }
Tokenized infix expression.
static token_list_t stack = { .tokens = NULL, .size = 0, .index = -1 }
Token stack.
static token_list_t queue = { .tokens = NULL, .size = 0, .index = -1 }
Token queue.
int bexpr_errno = 0
Error code.
Detailed Description
Boolean expression evaluation.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
This code was originally developed at https://github.com/Compyx/boolexpr/ The project page at github has a test driver which can be used to debug this code in a test driven way, should that be required.
Macro Definition Documentation
ARRAY_LEN
#define ARRAY_LEN (arr) (sizeof arr / sizeof arr[0])
{{{ Types, enums, macros
Array length helper
Determine size of arr in number of elements.
bexpr_debug
#define bexpr_debug (...)
Enable debugging messages.
Print debugging message on stdout if DEBUG_BEXPR is defined. Use just like printf(), for example: bexpr_debug("value = %d\n", 42) will print "[debug] \<funcname\>(): value = 42".
MAX_TOKEN_LEN
#define MAX_TOKEN_LEN 5
Maximum lenght of a token's text.
SET_ERROR
#define SET_ERROR (errnum)
Value:
    bexpr_errno = errnum; \
    fprintf(stderr, "%s(): error %d: %s\n", __func__, errnum, bexpr_strerror(errnum));
Set error code (and for now print error code and message on stderr.
Parameters
[in] errnum error code
TLIST_INIT
#define TLIST_INIT { .tokens = NULL, .size = 0, .index = -1 }
Initializer for a token list.
TLIST_INITIAL_SIZE
#define TLIST_INITIAL_SIZE 32u
Initial number of available tokens in a token list.
token_list_enqueue
#define token_list_enqueue (list, token) token_list_push(list, token)
Enqueue token onto? token list.
Enqueue token onto list, treating list as a queue.
Parameters
[in] list token list
[in] token token
Typedef Documentation
token_list_t
typedef struct token_list_s token_list_t
Token list object.
token_t
typedef struct token_s token_t
Token object.
Enumeration Type Documentation
anonymous enum
anonymous enum
Associativity of operators.
Enumerator
BEXPR_LTR
left-to-right associativity
BEXPR_RTL
right-to-left associativity
anonymous enum
anonymous enum
Arity of operators.
Enumerator
BEXPR_UNARY
unary operator
BEXPR_BINARY
binary operator
Function Documentation
bexpr_evaluate()
bool bexpr_evaluate (bool * result)
Evaluate boolean expression.
Evaluate boolean expression, either obtained by bexpr_parse() or by adding tokens with bexpr_add_token().
Parameters
[out] result result of evaluation
Returns
true on succes
Referenced by vhk_parser_do_if().
bexpr_free()
void bexpr_free (void)
Free memory used by expression.
Free all memory used by the expression, including the operator stack and the output queue.
Referenced by vhk_parser_shutdown().
bexpr_init()
void bexpr_init (void)
Initialize expression for use.
Allocate memory for tokenizer and evaluator.
Referenced by vhk_parser_init().
bexpr_print()
void bexpr_print (void)
Print tokenized expression on stdout.
bexpr_reset()
void bexpr_reset (void)
Reset tokenizer and evaluator for new expression.
Reset internal data structures for new expression, without freeing and then allocating resources again.
If using this module multiple times during the lifetime of a program (which is likely), do not call bexpr_free() followed by bexpr_init() when having to handle another expression, but call this function instead.
Referenced by vhk_parser_do_if().
bexpr_strerror()
const char * bexpr_strerror (int errnum)
Get error message for error number.
Parameters
[in] errnum error number
Returns
error message
Referenced by vhk_parser_do_if().
bexpr_token_add()
bool bexpr_token_add (int id)
Add token to expression.
Parameters
[in] id token ID
Returns
false if token id is invalid
Referenced by bexpr_tokenize(), and vhk_parser_do_if().
bexpr_token_parse()
int bexpr_token_parse (const char * text, const char ** endptr)
Parse text for a valid token.
Parse text looking for a valid token text, and if found return the ID. A pointer to the first non-valid character in text is stored in endptr if endptr isn't NULL.
Parameters
[in] text text to parse
[out] endptr location in text of first non-token character
Returns
token ID or BEXPR_INVALID on error
Exceptions
BEXPR_ERR_EXPECTED_TOKEN
BEXPR_ERR_INVALID_TOKEN
Referenced by bexpr_tokenize(), and vhk_parser_do_if().
bexpr_tokenize()
bool bexpr_tokenize (const char * text)
Generate expression from a string.
Parse text and tokenize into an expression. There is no syntax checking performed, only splitting the text into tokens for the evaluator.
Parameters
[in] text string to tokenize
Returns
true on success
eval_postfix()
static bool eval_postfix (bool * result) static
Evaluate postfix expression.
Evaluate postfix expression in queue.
Parameters
[out] result result of expression
Returns
true on success
Referenced by bexpr_evaluate().
infix_to_postfix()
static bool infix_to_postfix (void) static
Convert infix expression to postfix expression.
Use the Shunting yard algorithm to convert an infix expression to postfix ("reverse polish notation").
Returns
true on succces
Referenced by bexpr_evaluate().
is_operand()
static bool is_operand (int id) static
Determine if a token is an operand.
Parameters
[in] id token ID
Returns
true if token is an operand
Referenced by eval_postfix(), and infix_to_postfix().
is_token_char()
static bool is_token_char (int ch) static
Determine if a character is a valid token text character.
Parameters
[in] ch character to check
Returns
true if valid
Referenced by bexpr_token_parse().
is_valid_token_id()
static bool is_valid_token_id (int id) static
Determine if token ID is valid.
Parameters
[in] id token ID
Returns
true if valid
Referenced by is_operand(), and token_get().
skip_whitespace()
static const char * skip_whitespace (const char * s) static
{{{ Memory management: reimplementation of VICE's lib_foo() functions
}}}
{{{ Token handling
Skip whitespace in string
Parameters
[in] s string
Returns
pointer to first non-whitepace character (can be the terminating nul character if s consists of only whitespace)
Referenced by bexpr_token_parse(), and bexpr_tokenize().
token_from_bool()
static const token_t * token_from_bool (bool value) static
Get token for boolean value.
Parameters
[in] value boolean value
Returns
pointer to token representing value
Referenced by eval_postfix().
token_get()
static const token_t * token_get (int id) static
Get pointer to element in token info array.
Parameters
[in] id token ID
Returns
token info array element or NULL when not found
Referenced by token_from_bool(), and token_list_push_id().
token_list_free()
static void token_list_free (token_list_t * list) static
Free memory used by token list.
Free memory used by the list's token array.
Referenced by bexpr_free().
token_list_init()
static void token_list_init (token_list_t * list) static
}}}
Initialize token list for use
Initialize list by allocating space for TLIST_INITIAL_SIZE tokens and marking the list empty.
Parameters
[in] list token list
Referenced by bexpr_init().
token_list_is_empty()
static bool token_list_is_empty (const token_list_t * list) static
Determine if token list is empty.
Parameters
[in] list token list
Returns
true if list is empty
Referenced by infix_to_postfix().
token_list_length()
static int token_list_length (const token_list_t * list) static
Get length of token list.
Get number of tokens in list.
Parameters
[in] list token list
Returns
length of list
Referenced by bexpr_evaluate(), bexpr_print(), eval_postfix(), and infix_to_postfix().
token_list_peek()
static const token_t * token_list_peek (const token_list_t * list) static
Peek at the end of the list.
Get token at the tail of list without removing it.
Parameters
[in] list toke list
Returns
token or NULL if list is empty
Referenced by infix_to_postfix().
token_list_pull()
static const token_t * token_list_pull (token_list_t * list) static
Pull token from end of list.
Get item from end of list and remove it, treating list as a stack.
Parameters
[in] list token list
Returns
token or NULL if list is empty
Referenced by eval_postfix(), and infix_to_postfix().
token_list_push()
static void token_list_push (token_list_t * list, const token_t * token) static
Push token onto end of list.
Push token onto end of list, treating list like a stack.
Parameters
[in] list token list
[in] token token
Referenced by eval_postfix(), infix_to_postfix(), and token_list_push_id().
token_list_push_id()
static bool token_list_push_id (token_list_t * list, int id) static
Push token by its ID onto end of list.
Push token onto end of list, treating list like a stack.
Parameters
[in] list token list
[in] id token ID
Returns
false if id is invalid
Referenced by bexpr_token_add().
token_list_reset()
static void token_list_reset (token_list_t * list) static
Reset token list for reuse.
Reset list for reuse by marking it empty, without freeing the token array. To properly free a token list, use token_list_free().
Parameters
[in] list token list
Referenced by bexpr_reset(), eval_postfix(), and infix_to_postfix().
token_list_resize_maybe()
static void token_list_resize_maybe (token_list_t * list) static
Resize token array if required.
Double the size of the token array if it's full.
Parameters
[in] list token list
Referenced by token_list_push().
token_list_token_at()
static const token_t * token_list_token_at (const token_list_t * list, int index) static
Get token at index without removing it.
Parameters
[in] list token list
[in] index index in list
Returns
token or NULL if index is out of bounds
Referenced by bexpr_print(), eval_postfix(), and infix_to_postfix().
token_to_bool()
static bool token_to_bool (const token_t * token) static
Get bool value from token.
Parameters
[in] token token
Returns
true if token is BEXPR_TRUE
Referenced by eval_postfix().
Variable Documentation
bexpr_errno
int bexpr_errno = 0
Error code.
Referenced by bexpr_evaluate(), bexpr_init(), bexpr_reset(), and vhk_parser_do_if().
error_messages
const char* error_messages[] static
Initial value:
= {
    "OK",
    "fatal error",
    "expected token",
    "invalid token",
    "expected left parenthesis",
    "expected right parenthesis",
    "unmatched parentheses",
    "expression is empty",
    "missing operand"
}
Error messages.
Referenced by bexpr_strerror().
infix_text
char* infix_text = NULL static
}}}
Copy of text fed to tokenizer with bexpr_parse()
Referenced by bexpr_free(), bexpr_init(), bexpr_reset(), and bexpr_tokenize().
infix_tokens
token_list_t infix_tokens = { .tokens = NULL, .size = 0, .index = -1 } static
Tokenized infix expression.
Input for the infix to postfix conversion.
Referenced by bexpr_evaluate(), bexpr_free(), bexpr_init(), bexpr_print(), bexpr_reset(), bexpr_token_add(), and infix_to_postfix().
queue
token_list_t queue = { .tokens = NULL, .size = 0, .index = -1 } static
Token queue.
Queue used for output during postfix to infix conversion, and as input during postfix expression evaluation.
Referenced by bexpr_free(), bexpr_init(), bexpr_reset(), eval_postfix(), and infix_to_postfix().
stack
token_list_t stack = { .tokens = NULL, .size = 0, .index = -1 } static
Token stack.
Stack used for operators during postfix to infix conversion, and for operands during postfix expression evaluation.
Referenced by bexpr_free(), bexpr_init(), bexpr_reset(), create_ide64_devices_layout(), create_pet_layout(), eval_postfix(), infix_to_postfix(), settings_crt_widget_create(), settings_drive_widget_create(), settings_fsdevice_widget_create(), and settings_printer_widget_create().
token_chars
const int token_chars[] static
Initial value:
= {
    '(', ')', '!', '&', '|', '0', '1', 'a', 'e', 'f', 'l', 'r', 's', 't', 'u'
}
Valid characters in a token's text.
Referenced by is_token_char().
token_info
const token_t token_info[] static
Initial value:
= {
    { "false",  BEXPR_FALSE,    0,                  0,              0 },
    { "true",   BEXPR_TRUE,     0,                  0,              0 },
    { "(",      BEXPR_LPAREN,   0,                  BEXPR_LTR,      4 },
    { ")",      BEXPR_RPAREN,   0,                  BEXPR_LTR,      4 },
    { "!",      BEXPR_NOT,      BEXPR_UNARY,        BEXPR_RTL,      3 },
    { "&&",     BEXPR_AND,      BEXPR_BINARY,       BEXPR_LTR,      2 },
    { "||",     BEXPR_OR,       BEXPR_BINARY,       BEXPR_LTR,      1 }
}
}}}
{{{ Static constant data
List of valid tokens
Contains both operators and operands.
The id members here must match their array index.
Referenced by bexpr_token_parse(), is_valid_token_id(), and token_get().