x128: fsdevice/fsdevice-read.h File Reference
fsdevice-read.h File Reference
#include "types.h"
Functions
int fsdevice_read (struct vdrive_s *vdrive, uint8_t *data, unsigned int secondary)
void fsdevice_relative_pad_record (struct bufinfo_s *bufinfo)
int fsdevice_relative_switch_record (struct vdrive_s *vdrive, struct bufinfo_s *bufinfo, int record, int pos)
Function Documentation
fsdevice_read()
int fsdevice_read (struct vdrive_s * vdrive, uint8_t * data, unsigned int secondary)
Referenced by fsdevice_attach().
fsdevice_relative_pad_record()
void fsdevice_relative_pad_record (struct bufinfo_s * bufinfo)
Referenced by fsdevice_close(), and fsdevice_relative_switch_record().
fsdevice_relative_switch_record()
int fsdevice_relative_switch_record (struct vdrive_s * vdrive, struct bufinfo_s * bufinfo, int record, int pos)
Referenced by fsdevice_flush_position(), fsdevice_open_file(), fsdevice_rel_listen(), and relative_read().