x128: vicii/vicii-mem.c File Reference
vicii-mem.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "alarm.h"
#include "c64cia.h"
#include "debug.h"
#include "maincpu.h"
#include "mem.h"
#include "raster-changes.h"
#include "raster-sprite-status.h"
#include "raster-sprite.h"
#include "types.h"
#include "vicii-badline.h"
#include "vicii-colorram.h"
#include "vicii-fetch.h"
#include "vicii-irq.h"
#include "vicii-resources.h"
#include "vicii-sprites.h"
#include "vicii-mem.h"
#include "vicii.h"
#include "viciitypes.h"
#include "viewport.h"
Functions
static void vicii_local_store_vbank (uint16_t addr, uint8_t value)
Store a value in the video bank (it is assumed to be in RAM).
void vicii_mem_vbank_store (uint16_t addr, uint8_t value)
Encapsulate inlined function for other modules.
void vicii_mem_vbank_39xx_store (uint16_t addr, uint8_t value)
As ‘store_vbank()’, but for the $3900...$39FF address range.
void vicii_mem_vbank_3fxx_store (uint16_t addr, uint8_t value)
As ‘store_vbank()’, but for the $3F00...$3FFF address range.
static void store_sprite_x_position_lsb (const uint16_t addr, uint8_t value)
static void store_sprite_y_position (const uint16_t addr, uint8_t value)
static void store_sprite_x_position_msb (const uint16_t addr, uint8_t value)
static void check_lower_upper_border (const uint8_t value, unsigned int line, int cycle)
static void d011_store (uint8_t value)
static void d012_store (uint8_t value)
static void d015_store (const uint8_t value)
static void check_lateral_border (const uint8_t value, int cycle, raster_t *raster)
static void d016_store (const uint8_t value)
static void d017_store (const uint8_t value)
static void d018_store (const uint8_t value)
static void d019_store (const uint8_t value)
static void d01a_store (const uint8_t value)
static void d01b_store (const uint8_t value)
static void d01c_store (const uint8_t value)
static void d01d_store (const uint8_t value)
static void collision_store (const uint16_t addr, const uint8_t value)
static void d020_store (uint8_t value)
static void d021_store (uint8_t value)
static void ext_background_store (uint16_t addr, uint8_t value)
static void d025_store (uint8_t value)
static void d026_store (uint8_t value)
static void sprite_color_store (uint16_t addr, uint8_t value)
static void d02f_store (uint8_t value)
static void d030_store (uint8_t value)
void viciidtv_update_colorram (void)
static void d036_store (const uint8_t value)
static void d037_store (const uint8_t value)
static void d038_store (const uint8_t value)
static void d039_store (const uint8_t value)
static void d03a_store (const uint8_t value)
static void d03b_store (const uint8_t value)
static void d03c_store (const uint8_t value)
static void d03d_store (const uint8_t value)
static void d03f_store (const uint8_t value)
int vicii_extended_regs (void)
static void d040_store (const uint8_t value)
static void d044_store (const uint8_t value)
static void d045_store (const uint8_t value)
static void d046_store (const uint8_t value)
static void d047_store (const uint8_t value)
static void d048_store (const uint8_t value)
static void d049_store (const uint8_t value)
static void d04a_store (const uint8_t value)
static void d04b_store (const uint8_t value)
static void d04c_store (const uint8_t value)
static void d04d_store (const uint8_t value)
void vicii_palette_store (uint16_t addr, uint8_t value)
DTV Palette registers at $d2xx.
uint8_t vicii_palette_read (uint16_t addr)
void vicii_store (uint16_t addr, uint8_t value)
Store a value in a VIC-II register.
static unsigned int read_raster_y (void)
Helper function for reading from $D011/$D012.
static uint8_t d01112_read (uint16_t addr)
static uint8_t d019_read (void)
static uint8_t d01e_read (void)
static uint8_t d01f_read (void)
static uint8_t d044_read (void)
uint8_t vicii_read (uint16_t addr)
Read a value from a VIC-II register.
static uint8_t d019_peek (void)
uint8_t vicii_peek (uint16_t addr)
void vicii_init_colorram (uint8_t *colorram)
Variables
static const uint8_t unused_bits_in_registers [0x40]
Unused bits in VIC-II registers: these are always 1 when read.
static const uint8_t unused_bits_in_registers_dtv [0x50]
Unused bits in VIC-II DTV registers: these are always 1 when read.
Function Documentation
check_lateral_border()
static void check_lateral_border (const uint8_t value, int cycle, raster_t * raster) inline static
Referenced by d016_store().
check_lower_upper_border()
static void check_lower_upper_border (const uint8_t value, unsigned int line, int cycle) inline static
Referenced by d011_store().
collision_store()
static void collision_store (const uint16_t addr, const uint8_t value) inline static
Referenced by vicii_store().
d01112_read()
static uint8_t d01112_read (uint16_t addr) inline static
Referenced by vicii_read().
d011_store()
static void d011_store (uint8_t value) inline static
Todo:
FIXME: save time.
Referenced by vicii_store().
d012_store()
static void d012_store (uint8_t value) inline static
Referenced by vicii_store().
d015_store()
static void d015_store (const uint8_t value) inline static
Referenced by vicii_store().
d016_store()
static void d016_store (const uint8_t value) inline static
Referenced by vicii_store().
d017_store()
static void d017_store (const uint8_t value) inline static
Referenced by vicii_store().
d018_store()
static void d018_store (const uint8_t value) inline static
Referenced by vicii_store().
d019_peek()
static uint8_t d019_peek (void) inline static
Referenced by vicii_peek().
d019_read()
static uint8_t d019_read (void) inline static
Referenced by vicii_read().
d019_store()
static void d019_store (const uint8_t value) inline static
Referenced by vicii_store().
d01a_store()
static void d01a_store (const uint8_t value) inline static
VICII_DEBUG_REGISTER(("IRQ mask register: $%02X", vicii.regs[addr]));
Referenced by vicii_store().
d01b_store()
static void d01b_store (const uint8_t value) inline static
Referenced by vicii_store().
d01c_store()
static void d01c_store (const uint8_t value) inline static
Referenced by vicii_store().
d01d_store()
static void d01d_store (const uint8_t value) inline static
Todo:
FIXME: The offset of 6 was calibrated with the GULP demo and CCS
Referenced by vicii_store().
d01e_read()
static uint8_t d01e_read (void) inline static
Referenced by vicii_read().
d01f_read()
static uint8_t d01f_read (void) inline static
Referenced by vicii_read().
d020_store()
static void d020_store (uint8_t value) inline static
Referenced by d03c_store(), vicii_palette_store(), and vicii_store().
d021_store()
static void d021_store (uint8_t value) inline static
Referenced by d03c_store(), vicii_palette_store(), and vicii_store().
d025_store()
static void d025_store (uint8_t value) inline static
Referenced by vicii_palette_store(), and vicii_store().
d026_store()
static void d026_store (uint8_t value) inline static
Referenced by vicii_palette_store(), and vicii_store().
d02f_store()
static void d02f_store (uint8_t value) inline static
Referenced by vicii_store().
d030_store()
static void d030_store (uint8_t value) inline static
Referenced by vicii_store().
d036_store()
static void d036_store (const uint8_t value) inline static
Referenced by vicii_store().
d037_store()
static void d037_store (const uint8_t value) inline static
Referenced by vicii_store().
d038_store()
static void d038_store (const uint8_t value) inline static
Referenced by vicii_store().
d039_store()
static void d039_store (const uint8_t value) inline static
Referenced by vicii_store().
d03a_store()
static void d03a_store (const uint8_t value) inline static
Referenced by vicii_store().
d03b_store()
static void d03b_store (const uint8_t value) inline static
Referenced by vicii_store().
d03c_store()
static void d03c_store (const uint8_t value) static
Referenced by vicii_store().
d03d_store()
static void d03d_store (const uint8_t value) inline static
Referenced by vicii_store().
d03f_store()
static void d03f_store (const uint8_t value) inline static
Referenced by vicii_store().
d040_store()
static void d040_store (const uint8_t value) inline static
Referenced by vicii_store().
d044_read()
static uint8_t d044_read (void) inline static
Referenced by vicii_read().
d044_store()
static void d044_store (const uint8_t value) inline static
Referenced by vicii_store().
d045_store()
static void d045_store (const uint8_t value) inline static
Referenced by vicii_store().
d046_store()
static void d046_store (const uint8_t value) inline static
Referenced by vicii_store().
d047_store()
static void d047_store (const uint8_t value) inline static
Referenced by vicii_store().
d048_store()
static void d048_store (const uint8_t value) inline static
Referenced by vicii_store().
d049_store()
static void d049_store (const uint8_t value) inline static
Referenced by vicii_store().
d04a_store()
static void d04a_store (const uint8_t value) inline static
Referenced by vicii_store().
d04b_store()
static void d04b_store (const uint8_t value) inline static
Referenced by vicii_store().
d04c_store()
static void d04c_store (const uint8_t value) inline static
Referenced by vicii_store().
d04d_store()
static void d04d_store (const uint8_t value) inline static
Referenced by vicii_store().
ext_background_store()
static void ext_background_store (uint16_t addr, uint8_t value) inline static
Referenced by d03c_store(), vicii_palette_store(), and vicii_store().
read_raster_y()
static unsigned int read_raster_y (void) inline static
Helper function for reading from $D011/$D012.
Referenced by d01112_read(), and vicii_peek().
sprite_color_store()
static void sprite_color_store (uint16_t addr, uint8_t value) inline static
Referenced by vicii_palette_store(), and vicii_store().
store_sprite_x_position_lsb()
static void store_sprite_x_position_lsb (const uint16_t addr, uint8_t value) inline static
Referenced by vicii_store().
store_sprite_x_position_msb()
static void store_sprite_x_position_msb (const uint16_t addr, uint8_t value) inline static
Referenced by vicii_store().
store_sprite_y_position()
static void store_sprite_y_position (const uint16_t addr, uint8_t value) inline static
Referenced by vicii_store().
vicii_extended_regs()
int vicii_extended_regs (void)
vicii_init_colorram()
void vicii_init_colorram (uint8_t * colorram)
Referenced by mem_powerup().
vicii_local_store_vbank()
static void vicii_local_store_vbank (uint16_t addr, uint8_t value) inline static
Store a value in the video bank (it is assumed to be in RAM).
Referenced by vicii_mem_vbank_39xx_store(), vicii_mem_vbank_3fxx_store(), and vicii_mem_vbank_store().
vicii_mem_vbank_39xx_store()
void vicii_mem_vbank_39xx_store (uint16_t addr, uint8_t value)
As ‘store_vbank()’, but for the $3900...$39FF address range.
Referenced by c64mode_vicii_mem_vbank_39xx_lo_store(), c64mode_vicii_mem_vbank_39xx_ram_store(), and c64mode_vicii_mem_vbank_39xx_top_shared_store().
vicii_mem_vbank_3fxx_store()
void vicii_mem_vbank_3fxx_store (uint16_t addr, uint8_t value)
As ‘store_vbank()’, but for the $3F00...$3FFF address range.
Referenced by c64mode_ffxx_store(), c64mode_vicii_mem_vbank_3fxx_lo_store(), c64mode_vicii_mem_vbank_3fxx_ram_store(), c64mode_vicii_mem_vbank_3fxx_top_shared_store(), and ram_hi_store().
vicii_mem_vbank_store()
void vicii_mem_vbank_store (uint16_t addr, uint8_t value)
Encapsulate inlined function for other modules.
Referenced by c64mode_vicii_mem_vbank_lo_store(), c64mode_vicii_mem_vbank_ram_store(), and c64mode_vicii_mem_vbank_top_shared_store().
vicii_palette_read()
uint8_t vicii_palette_read (uint16_t addr)
vicii_palette_store()
void vicii_palette_store (uint16_t addr, uint8_t value)
DTV Palette registers at $d2xx.
vicii_peek()
uint8_t vicii_peek (uint16_t addr)
Referenced by mem_get_screen_parameter().
vicii_read()
uint8_t vicii_read (uint16_t addr)
Read a value from a VIC-II register.
vicii_store()
void vicii_store (uint16_t addr, uint8_t value)
Store a value in a VIC-II register.
Referenced by vicii_reset_registers(), and vicii_snapshot_read_module().
viciidtv_update_colorram()
void viciidtv_update_colorram (void)
Referenced by d036_store(), d037_store(), d045_store(), vicii_update_memory_ptrs(), and vicii_update_video_mode().
Variable Documentation
unused_bits_in_registers
const uint8_t unused_bits_in_registers[0x40] static
Initial value:
=
{
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0x00 , 0xc0 , 0x00 ,
    0x01 , 0x70 , 0xf0 , 0x00 ,
    0x00 , 0x00 , 0x00 , 0x00 ,
    0xf0 , 0xf0 , 0xf0 , 0xf0 ,
    0xf0 , 0xf0 , 0xf0 , 0xf0 ,
    0xf0 , 0xf0 , 0xf0 , 0xf0 ,
    0xf0 , 0xf0 , 0xf0 , 0xff ,
    0xff , 0xff , 0xff , 0xff ,
    0xff , 0xff , 0xff , 0xff ,
    0xff , 0xff , 0xff , 0xff ,
    0xff , 0xff , 0xff , 0xff
}
Unused bits in VIC-II registers: these are always 1 when read.
Referenced by vicii_peek().
unused_bits_in_registers_dtv
const uint8_t unused_bits_in_registers_dtv[0x50] static
Initial value:
=
{
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0x00 , 0xc0 , 0x00 ,
    0x01 , 0x70 , 0xf0 , 0x00 ,
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0x00 , 0x00 , 0x00 ,
    0x00 , 0xf0 , 0xf0 , 0xf0 ,
    0xf0 , 0xf0 , 0xf0 , 0xf0 ,
    0xf0 , 0xf0 , 0xf0 , 0xff ,
    0xff , 0xff , 0xff , 0xff ,
    0xff , 0xff , 0x00 , 0x00 ,
    0x00 , 0xf0 , 0x00 , 0x00 ,
    0x80 , 0x00 , 0xff , 0xfc ,
    0xf8 , 0x00 , 0x00 , 0x00 ,
    0x80 , 0xc0 , 0x00 , 0x00 ,
    0xf0 , 0x00 , 0x00 , 0xc0 ,
    0x00 , 0xc0 , 0x00 , 0xf0
}
Unused bits in VIC-II DTV registers: these are always 1 when read.
Referenced by vicii_peek().