vsid: arch/gtk3/widgets/settings_tapeport.c File Reference
settings_tapeport.c File Reference
Tape port settings dialog widget.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include "datasette.h"
#include "lib.h"
#include "machine.h"
#include "resources.h"
#include "tapecart.h"
#include "tapeport.h"
#include "vice_gtk3.h"
#include "settings_tapeport.h"
Enumerations
enum {
COL_DEVICE_ID ,
COL_DEVICE_NAME ,
COL_DEVICE_TYPE_ID ,
COL_DEVICE_TYPE_DESC
}
Column indexes in the tapeport devices model.
Functions
static gboolean machine_has_tapecart (void)
Determine if current machine supports tapecart.
static gboolean machine_has_second_tape_port (void)
Determine if the current machine has a second tape port.
static void set_datasette_active (gboolean state)
Set Datasette widget active/inactive.
static void set_f83_active (gboolean state)
Set CP Clock F83 widget active/inactive.
static void set_tapecart_active (gboolean state)
Set tapecart active/inactive.
static void set_options_widgets_sensitivity (int id)
Set individual options active/inactive.
static void on_tcrt_flush_clicked (GtkWidget *widget, gpointer data)
Handler for the 'clicked' event of the tapecart flush button.
static GtkWidget * label_helper (const char *text)
Create left-aligned label with Pango markup.
static GtkWidget * create_datasette_widget (void)
Create widgets for the datasette.
static GtkWidget * create_cpcf83_widget (void)
Create widget to handler the Cassette Port Clock F83 resources.
static GtkWidget * create_tapecart_widget (void)
Create widget to handle the tapecart resources.
static void on_device_changed (GtkComboBox *combo, gpointer portnum)
Handler for the 'changed' event of the device combobox.
static gboolean set_device_id (GtkComboBox *combo, gint id, gboolean blocked)
Set tapeport device ID.
static GtkListStore * create_device_model (int port)
Create model for the device combobox.
static GtkWidget * create_device_combobox (int port)
Create combobox for the tapeport devices.
static GtkWidget * create_device_types_widget (void)
Create combobox(es) to select device type for port 1 (and 2 for PET)
GtkWidget * settings_tapeport_widget_create (GtkWidget *parent)
Create widget to select/control tape port devices.
Variables
static const vice_gtk3_combo_entry_int_t tcrt_loglevels []
List of log levels and their descriptions for the Tapecart.
static GtkWidget * port1_type = NULL
Tape port #1 device combo.
static GtkWidget * port2_type = NULL
Tape port #2 device combo.
static GtkWidget * ds_traps1 = NULL
Datasette 1 device traps toggle button.
static GtkWidget * ds_traps2 = NULL
Datasette 2 device traps toggle button.
static GtkWidget * ds_reset = NULL
Datasette reset toggle button.
static GtkWidget * ds_zerogap = NULL
Datasette zerogap delay spine button.
static GtkWidget * ds_speed = NULL
Datasette speed tuning spin button.
static GtkWidget * ds_wobblefreq = NULL
Datasette wobble frequency spin button.
static GtkWidget * ds_wobbleamp = NULL
Datasette wobble amplitude spin button.
static GtkWidget * ds_align = NULL
Datasette align spin button.
static GtkWidget * ds_sound = NULL
Datasette sound emulation toggle button.
static GtkWidget * f83_rtc = NULL
F83 RTC toggle button.
static GtkWidget * tcrt_update = NULL
Tapecart save-when-changed toggle button.
static GtkWidget * tcrt_optimize = NULL
Tapecart optimize-when-saving toggle button.
static GtkWidget * tcrt_loglevel = NULL
Tapecart log level radiogroup.
static GtkWidget * tcrt_filename = NULL
Tapecart image file browser.
static GtkWidget * tcrt_flush = NULL
Tapecart flush button.
Detailed Description
Tape port settings dialog widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
anonymous enum
anonymous enum
Column indexes in the tapeport devices model.
Enumerator
COL_DEVICE_ID
device ID (int)
COL_DEVICE_NAME
device name (str)
COL_DEVICE_TYPE_ID
device type (int)
COL_DEVICE_TYPE_DESC
device type description (str)
Function Documentation
create_cpcf83_widget()
static GtkWidget * create_cpcf83_widget (void) static
Create widget to handler the Cassette Port Clock F83 resources.
Returns
GtkGrid
Referenced by settings_tapeport_widget_create().
create_datasette_widget()
static GtkWidget * create_datasette_widget (void) static
Create widgets for the datasette.
!
Todo:
Someone needs to check the spin button bounds and steps for sane values.
Returns
GtkGrid
Referenced by settings_tapeport_widget_create().
create_device_combobox()
static GtkWidget * create_device_combobox (int port) static
Create combobox for the tapeport devices.
Create a combobox with valid tapeport devices for current machine.
The model of the combobox contains device ID, name and type, of which name is shown and ID is used to set the related resource.
Parameters
[in] port tape port number (1 or 2 (PET only))
Returns
GtkComboBox
Todo:
Try using the device type to create little headers in the combobox, grouping the devices by type. Might be overkill for some machines that only have a few tapeport devices, we'll see. I tried using a second column for the device type description, and althought it doesn't look bad in the popup list, when the popup isn't active it looks weird ;) So for now the device type isn't used.
Todo:
Check if the model can be shared for both ports, perhaps the second tape port has a different set of supported devices
Referenced by create_device_types_widget().
create_device_model()
static GtkListStore * create_device_model (int port) static
Create model for the device combobox.
Create a model with (dev-id, dev-name, dev-type-id, dev-type-desc).
Parameters
[in] port tape port number (1 or 2 (PET))
Returns
model
Referenced by create_device_combobox().
create_device_types_widget()
static GtkWidget * create_device_types_widget (void) static
Create combobox(es) to select device type for port 1 (and 2 for PET)
Returns
GtkGrid
Referenced by settings_tapeport_widget_create().
create_tapecart_widget()
static GtkWidget * create_tapecart_widget (void) static
Create widget to handle the tapecart resources.
Returns
GtkGrid
Referenced by settings_tapeport_widget_create().
label_helper()
static GtkWidget * label_helper (const char * text) static
Create left-aligned label with Pango markup.
Parameters
[in] text text for label (can use Pango markup)
Returns
GtkLabel
Referenced by create_cpcf83_widget(), create_datasette_widget(), create_device_types_widget(), and create_tapecart_widget().
machine_has_second_tape_port()
static gboolean machine_has_second_tape_port (void) static
Determine if the current machine has a second tape port.
Returns
TRUE if the machine has a second tape port
Referenced by create_datasette_widget(), create_device_types_widget(), set_datasette_active(), and settings_tapeport_widget_create().
machine_has_tapecart()
static gboolean machine_has_tapecart (void) static
Determine if current machine supports tapecart.
Returns
TRUE if tapecart emulation is available
Referenced by set_tapecart_active(), and settings_tapeport_widget_create().
on_device_changed()
static void on_device_changed (GtkComboBox * combo, gpointer portnum) static
Handler for the 'changed' event of the device combobox.
Sets the active tapeport device via the "TapePort[12]Device" resource.
Parameters
[in] combo device combo box
[in] portnum tape port number
Referenced by create_device_combobox(), and set_device_id().
on_tcrt_flush_clicked()
static void on_tcrt_flush_clicked (GtkWidget * widget, gpointer data) static
Handler for the 'clicked' event of the tapecart flush button.
Parameters
[in] widget button (unused)
[in] data extra event data (unused)
Referenced by create_tapecart_widget().
set_datasette_active()
static void set_datasette_active (gboolean state) static
Set Datasette widget active/inactive.
Parameters
[in] state status
Referenced by set_options_widgets_sensitivity().
set_device_id()
static gboolean set_device_id (GtkComboBox * combo, gint id, gboolean blocked) static
Set tapeport device ID.
Sets the currently selected combobox item via device ID.
To avoid updating the related resource via the combobox' event handler, use the blocked argument.
Parameters
[in] combo device combo box
[in] id device ID
[in] blocked block 'changed' signal handler
Referenced by settings_tapeport_widget_create().
set_f83_active()
static void set_f83_active (gboolean state) static
Set CP Clock F83 widget active/inactive.
Parameters
[in] state status
Referenced by set_options_widgets_sensitivity().
set_options_widgets_sensitivity()
static void set_options_widgets_sensitivity (int id) static
Set individual options active/inactive.
Parameters
[in] id id of active device
Referenced by on_device_changed(), and set_device_id().
set_tapecart_active()
static void set_tapecart_active (gboolean state) static
Set tapecart active/inactive.
Parameters
[in] state status
Referenced by set_options_widgets_sensitivity().
settings_tapeport_widget_create()
GtkWidget * settings_tapeport_widget_create (GtkWidget * parent)
Create widget to select/control tape port devices.
Parameters
[in] parent parent widget (ignored)
Returns
GtkGrid
Variable Documentation
ds_align
GtkWidget* ds_align = NULL static
Datasette align spin button.
Referenced by create_datasette_widget(), and set_datasette_active().
ds_reset
GtkWidget* ds_reset = NULL static
Datasette reset toggle button.
Referenced by create_datasette_widget(), and set_datasette_active().
ds_sound
GtkWidget* ds_sound = NULL static
Datasette sound emulation toggle button.
Referenced by create_datasette_widget(), and set_datasette_active().
ds_speed
GtkWidget* ds_speed = NULL static
Datasette speed tuning spin button.
Referenced by create_datasette_widget(), and set_datasette_active().
ds_traps1
GtkWidget* ds_traps1 = NULL static
Datasette 1 device traps toggle button.
Referenced by create_datasette_widget(), and set_datasette_active().
ds_traps2
GtkWidget* ds_traps2 = NULL static
Datasette 2 device traps toggle button.
Referenced by create_datasette_widget(), and set_datasette_active().
ds_wobbleamp
GtkWidget* ds_wobbleamp = NULL static
Datasette wobble amplitude spin button.
Referenced by create_datasette_widget(), and set_datasette_active().
ds_wobblefreq
GtkWidget* ds_wobblefreq = NULL static
Datasette wobble frequency spin button.
Referenced by create_datasette_widget(), and set_datasette_active().
ds_zerogap
GtkWidget* ds_zerogap = NULL static
Datasette zerogap delay spine button.
Referenced by create_datasette_widget(), and set_datasette_active().
f83_rtc
GtkWidget* f83_rtc = NULL static
F83 RTC toggle button.
Referenced by create_cpcf83_widget(), and set_f83_active().
port1_type
GtkWidget* port1_type = NULL static
Tape port #1 device combo.
Referenced by create_device_types_widget(), and settings_tapeport_widget_create().
port2_type
GtkWidget* port2_type = NULL static
Tape port #2 device combo.
Referenced by create_device_types_widget(), and settings_tapeport_widget_create().
tcrt_filename
GtkWidget* tcrt_filename = NULL static
Tapecart image file browser.
Referenced by create_tapecart_widget(), and set_tapecart_active().
tcrt_flush
GtkWidget* tcrt_flush = NULL static
Tapecart flush button.
Referenced by create_tapecart_widget(), and set_tapecart_active().
tcrt_loglevel
GtkWidget* tcrt_loglevel = NULL static
Tapecart log level radiogroup.
Referenced by create_tapecart_widget(), and set_tapecart_active().
tcrt_loglevels
const vice_gtk3_combo_entry_int_t tcrt_loglevels[] static
Initial value:
= {
    { "0 (errors only)",                         0 },
    { "1 (0 + mode changes and command bytes)",  1 },
    { "2 (1 + command parameter details)",       2 },
    { NULL,                                     -1 }
}
List of log levels and their descriptions for the Tapecart.
Referenced by create_tapecart_widget().
tcrt_optimize
GtkWidget* tcrt_optimize = NULL static
Tapecart optimize-when-saving toggle button.
Referenced by create_tapecart_widget(), and set_tapecart_active().
tcrt_update
GtkWidget* tcrt_update = NULL static
Tapecart save-when-changed toggle button.
Referenced by create_tapecart_widget(), and set_tapecart_active().