x128: arch/gtk3/widgets/base/carthelpers.c File Reference
carthelpers.c File Reference
Cartridge helper functions.
#include "vice.h"
#include <gtk/gtk.h>
#include "basewidget_types.h"
#include "cartridge.h"
#include "carthelpers.h"
Functions
static void set_active_blocked (GtkToggleButton *button, gulong handler_id, gboolean active)
Set toggle button active state while blocking event handler.
static void on_cart_enable_check_button_toggled (GtkToggleButton *self, gpointer id)
Handler for the "toggled" event of the cart enable check button.
GtkWidget * carthelpers_create_enable_check_button (const char *cart_name, int cart_id)
Create a check button to enable/disable a cartridge.
Detailed Description
Cartridge helper functions.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
carthelpers_create_enable_check_button()
GtkWidget * carthelpers_create_enable_check_button (const char * cart_name, int cart_id)
Create a check button to enable/disable a cartridge.
Creates a check button that enables/disables a cartridge. The cart_name argument is copied to allow for debug/error messages to mention the cart by name, rather than by ID. The name is freed when the check button is destroyed.
What the widget basically does is call cartridge_enable(cart_id) or cartridge_disable(cart_id), using cartridge_type_enabled(cart_id) to set the initial state of the widget. But since all Gtk3 widgets are currently linked into a big lib and vsid doesn't like that, we use some function pointer magic is used.
Parameters
[in] cart_name cartridge name (see cartridge.h)
[in] cart_id cartridge ID (see cartridge.h)
Returns
GtkCheckButton
Referenced by settings_cpm_widget_create(), settings_dqbb_widget_create(), settings_ds12c887_widget_create(), settings_expert_widget_create(), settings_georam_widget_create(), settings_isepic_widget_create(), settings_magicvoice_widget_create(), settings_reu_widget_create(), settings_sfxsoundexpander_widget_create(), and settings_sfxsoundsampler_widget_create().
on_cart_enable_check_button_toggled()
static void on_cart_enable_check_button_toggled (GtkToggleButton * self, gpointer id) static
Handler for the "toggled" event of the cart enable check button.
When this function fails to enable/disable the cartridge, it'll revert self to its previous state.
Parameters
[in,out] self check button
[in] id cartridge ID
Referenced by carthelpers_create_enable_check_button().
set_active_blocked()
static void set_active_blocked (GtkToggleButton * button, gulong handler_id, gboolean active) static
Set toggle button active state while blocking event handler.
Set button to active while blocking signal handler handler_id.
Parameters
[in] button toggle button
[in] handler_id ID of signal handler to temporarily block
[in] active new active state for button
Referenced by on_cart_enable_check_button_toggled().