x128: arch/gtk3/widgets/base/unicodehelpers.h File Reference
unicodehelpers.h File Reference
GTK3 helper functions for unicode - header.
Functions
unsigned char * vice_gtk3_petscii_to_utf8 (unsigned char *s, bool inverted, bool lowercase)
Convert petscii encoded string to utf8 string we can show using the CBM font.
unsigned char * vice_gtk3_scrcode_to_utf8 (unsigned char *s, bool inverted, bool lowercase)
unsigned char * vice_gtk3_petscii_upper_to_utf8 (unsigned char *s, bool inverted)
unsigned char * vice_gtk3_scrcode_upper_to_utf8 (unsigned char *s, bool inverted)
unsigned char * vice_gtk3_petscii_to_utf8_petme (unsigned char *s, bool inverted, bool lowercase)
Convert petscii encoded string to utf8 string we can show using a CBM font.
unsigned char * vice_gtk3_scrcode_to_utf8_petme (unsigned char *s, bool inverted, bool lowercase)
unsigned char * vice_gtk3_petscii_upper_to_utf8_petme (unsigned char *s, bool inverted)
unsigned char * vice_gtk3_scrcode_upper_to_utf8_petme (unsigned char *s, bool inverted)
unsigned char * vice_gtk3_petscii_to_utf8_petme64 (unsigned char *s, bool inverted, bool lowercase)
Convert petscii encoded string to utf8 string we can show using a CBM font.
unsigned char * vice_gtk3_scrcode_to_utf8_petme64 (unsigned char *s, bool inverted, bool lowercase)
unsigned char * vice_gtk3_petscii_upper_to_utf8_petme64 (unsigned char *s, bool inverted)
unsigned char * vice_gtk3_scrcode_upper_to_utf8_petme64 (unsigned char *s, bool inverted)
Detailed Description
GTK3 helper functions for unicode - header.
Author
Groepaz
Function Documentation
vice_gtk3_petscii_to_utf8()
unsigned char * vice_gtk3_petscii_to_utf8 (unsigned char * s, bool inverted, bool lowercase)
Convert petscii encoded string to utf8 string we can show using the CBM font.
Todo:
FIXME: since these functions work on strings, they can't convert the 0 character correctly - we should provide additional functions that convert as single character (which can always work) and/or alternative functions that take a buffer length
this function handles all characters that may appear in a directory listing, including "non printable" control characters, which appear as inverted characters in so called "quote mode".
Parameters
[in] s PETSCII string to convert to UTF-8
[in] inverted use inverted mode
[in] lowercase use the lowercase chargen
Returns
heap-allocated UTF-8 string, free with lib_free()
Note
only valid for the "C64_Pro_Mono-STYLE.ttf" font, not the old "CBM.ttf" font.
Somehow the inverted space has a line on top on at least Linux, the codepoint seems fine though, so perhaps a bug in Pango?
Referenced by uimon_petscii_out(), uimon_scrcode_out(), and vice_gtk3_petscii_upper_to_utf8().
vice_gtk3_petscii_to_utf8_petme()
unsigned char * vice_gtk3_petscii_to_utf8_petme (unsigned char * s, bool inverted, bool lowercase)
Convert petscii encoded string to utf8 string we can show using a CBM font.
this function handles all "printable" PETSCII characters, including "non printable" control characters, which appear as inverted characters in so called "quote mode".
Parameters
[in] s PETSCII string to convert to UTF-8
[in] inverted use inverted mode
[in] lowercase use the lowercase chargen
Returns
heap-allocated UTF-8 string, free with lib_free()
Note
only valid for the "PetMe.ttf" font
Referenced by uimon_petscii_out(), uimon_scrcode_out(), and vice_gtk3_petscii_upper_to_utf8_petme().
vice_gtk3_petscii_to_utf8_petme64()
unsigned char * vice_gtk3_petscii_to_utf8_petme64 (unsigned char * s, bool inverted, bool lowercase)
Convert petscii encoded string to utf8 string we can show using a CBM font.
this function handles all "printable" PETSCII characters, including "non printable" control characters, which appear as inverted characters in so called "quote mode".
Parameters
[in] s PETSCII string to convert to UTF-8
[in] inverted use inverted mode
[in] lowercase use the lowercase chargen
Returns
heap-allocated UTF-8 string, free with lib_free()
Note
only valid for the "PetMe64.ttf" font
Referenced by uimon_petscii_out(), uimon_scrcode_out(), and vice_gtk3_petscii_upper_to_utf8_petme64().
vice_gtk3_petscii_upper_to_utf8()
unsigned char * vice_gtk3_petscii_upper_to_utf8 (unsigned char * s, bool inverted)
Referenced by create_model(), dir_menu_popup_create(), uimon_petscii_upper_out(), and uimon_scrcode_upper_out().
vice_gtk3_petscii_upper_to_utf8_petme()
unsigned char * vice_gtk3_petscii_upper_to_utf8_petme (unsigned char * s, bool inverted)
Referenced by uimon_petscii_upper_out(), and uimon_scrcode_upper_out().
vice_gtk3_petscii_upper_to_utf8_petme64()
unsigned char * vice_gtk3_petscii_upper_to_utf8_petme64 (unsigned char * s, bool inverted)
Referenced by uimon_petscii_upper_out(), and uimon_scrcode_upper_out().
vice_gtk3_scrcode_to_utf8()
unsigned char * vice_gtk3_scrcode_to_utf8 (unsigned char * s, bool inverted, bool lowercase)
Referenced by uimon_scrcode_out(), and vice_gtk3_scrcode_upper_to_utf8().
vice_gtk3_scrcode_to_utf8_petme()
unsigned char * vice_gtk3_scrcode_to_utf8_petme (unsigned char * s, bool inverted, bool lowercase)
Referenced by uimon_scrcode_out().
vice_gtk3_scrcode_to_utf8_petme64()
unsigned char * vice_gtk3_scrcode_to_utf8_petme64 (unsigned char * s, bool inverted, bool lowercase)
Referenced by uimon_scrcode_out(), vice_gtk3_scrcode_upper_to_utf8_petme(), and vice_gtk3_scrcode_upper_to_utf8_petme64().
vice_gtk3_scrcode_upper_to_utf8()
unsigned char * vice_gtk3_scrcode_upper_to_utf8 (unsigned char * s, bool inverted)
Referenced by uimon_scrcode_upper_out().
vice_gtk3_scrcode_upper_to_utf8_petme()
unsigned char * vice_gtk3_scrcode_upper_to_utf8_petme (unsigned char * s, bool inverted)
Referenced by uimon_scrcode_upper_out().
vice_gtk3_scrcode_upper_to_utf8_petme64()
unsigned char * vice_gtk3_scrcode_upper_to_utf8_petme64 (unsigned char * s, bool inverted)
Referenced by uimon_scrcode_upper_out().