vsid: imagecontents/diskcontents-block.c File Reference
diskcontents-block.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "cbmdos.h"
#include "diskcontents-block.h"
#include "diskimage.h"
#include "imagecontents.h"
#include "lib.h"
#include "types.h"
#include "vdrive-bam.h"
#include "vdrive-dir.h"
#include "vdrive-internal.h"
#include "vdrive.h"
#include "machine-drive.h"
Data Structures
struct block_list_t
Functions
static void circular_check_init (void)
static void circular_check_free (void)
static int circular_check (unsigned int track, unsigned int sector)
image_contents_t * diskcontents_block_read (vdrive_t *vdrive, int part)
Variables
static struct block_list_t * block_list = NULL
static unsigned int block_list_nelems
static unsigned int block_list_size
Function Documentation
circular_check()
static int circular_check (unsigned int track, unsigned int sector) static
Referenced by diskcontents_block_read().
circular_check_free()
static void circular_check_free (void) static
Referenced by diskcontents_block_read().
circular_check_init()
static void circular_check_init (void) static
Referenced by diskcontents_block_read().
diskcontents_block_read()
image_contents_t * diskcontents_block_read (vdrive_t * vdrive, int part)
< standard length of container names, such as D64
< standard length of container names, such as D64
< length of a disk ID
< length of a disk ID
< lenght of a PETSCII filename
< lenght of a PETSCII filename
Referenced by diskcontents_filesystem_read(), and mon_drive_list().
Variable Documentation
block_list
struct block_list_t * block_list = NULL static
Referenced by circular_check(), and circular_check_free().
block_list_nelems
unsigned int block_list_nelems static
Referenced by circular_check(), circular_check_free(), and circular_check_init().
block_list_size
unsigned int block_list_size static
Referenced by circular_check(), and circular_check_free().