vsid: arch/gtk3/mousedrv.c File Reference
mousedrv.c File Reference
Native GTK3 UI mouse driver stuff.
#include "vice.h"
#include <X11/Xlib.h>
#include <gdk/gdkx.h>
#include <stdio.h>
#include <math.h>
#include "log.h"
#include "vsyncapi.h"
#include "maincpu.h"
#include "mouse.h"
#include "mousedrv.h"
#include "ui.h"
#include "uimachinewindow.h"
Functions
int mousedrv_cmdline_options_init (void)
Register and parse mouse-related command-line options.
void mouse_button (int bnumber, int state)
Called by the UI event handler to announce the user has pressed or released a button.
void mousedrv_init (void)
Initialize the mouse-handling subsystem.
void mousedrv_mouse_changed (void)
Called by the emulation core to announce the mouse has been enabled or disabled.
int mousedrv_resources_init (const mouse_func_t *funcs)
Register callbacks for mouse button presses.
Variables
static mouse_func_t mouse_funcs
The callbacks registered for mouse buttons being pressed or released.
Detailed Description
Native GTK3 UI mouse driver stuff.
Author
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Function Documentation
mouse_button()
void mouse_button (int bnumber, int state)
Called by the UI event handler to announce the user has pressed or released a button.
Parameters
bnumber Which button was pressed or released.
state Nonzero if button was pressed, zero if it was released.
Referenced by event_box_mouse_button_cb(), and event_box_scroll_cb().
mousedrv_cmdline_options_init()
int mousedrv_cmdline_options_init (void)
Register and parse mouse-related command-line options.
Returns
Zero on success, nonzero on failure.
Referenced by mouse_ps2_cmdline_options_init().
mousedrv_init()
void mousedrv_init (void)
Initialize the mouse-handling subsystem.
Referenced by mouse_ps2_init().
mousedrv_mouse_changed()
void mousedrv_mouse_changed (void)
Called by the emulation core to announce the mouse has been enabled or disabled.
Todo:
Tell UI level to capture mouse cursor if necessary and permitted
mousedrv_resources_init()
int mousedrv_resources_init (const mouse_func_t * funcs)
Register callbacks for mouse button presses.
Parameters
funcs The callbacks to register.
Returns
Zero on success, nonzero on failure.
Referenced by mouse_ps2_resources_init().
Variable Documentation
mouse_funcs
mouse_func_t mouse_funcs static
Initial value:
= {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
}
The callbacks registered for mouse buttons being pressed or released.
See also
mousedrv_resources_init which sets these values properly
mouse_button which uses them
Referenced by mouse_button(), and mousedrv_resources_init().