vsid: imagecontents/diskcontents.h File Reference
diskcontents.h File Reference
Functions
struct image_contents_s * diskcontents_read (const char *file_name, unsigned int unit, unsigned int drive)
struct image_contents_s * diskcontents_filesystem_read (const char *file_name)
struct image_contents_s * diskcontents_read_unit8 (const char *file_name)
struct image_contents_s * diskcontents_read_unit9 (const char *file_name)
struct image_contents_s * diskcontents_read_unit10 (const char *file_name)
struct image_contents_s * diskcontents_read_unit11 (const char *file_name)
Function Documentation
diskcontents_filesystem_read()
struct image_contents_s * diskcontents_filesystem_read (const char * file_name)
Referenced by autostart_disk(), create_disk_attach_dialog(), read_contents_wrapper(), and ui_do_drive_popup().
diskcontents_read()
struct image_contents_s * diskcontents_read (const char * file_name, unsigned int unit, unsigned int drive)
diskcontents_read_unit10()
struct image_contents_s * diskcontents_read_unit10 (const char * file_name)
diskcontents_read_unit11()
struct image_contents_s * diskcontents_read_unit11 (const char * file_name)
diskcontents_read_unit8()
struct image_contents_s * diskcontents_read_unit8 (const char * file_name)
diskcontents_read_unit9()
struct image_contents_s * diskcontents_read_unit9 (const char * file_name)