x128: fsdevice/fsdevice.c File Reference
fsdevice.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "attach.h"
#include "cbmdos.h"
#include "fileio.h"
#include "fsdevice-close.h"
#include "fsdevice-flush.h"
#include "fsdevice-open.h"
#include "fsdevice-read.h"
#include "fsdevice-resources.h"
#include "fsdevice-write.h"
#include "fsdevice.h"
#include "fsdevicetypes.h"
#include "lib.h"
#include "log.h"
#include "machine-bus.h"
#include "resources.h"
#include "tape.h"
#include "vdrive-command.h"
#include "vdrive.h"
Macros
#define DBG(x)
Functions
void fsdevice_set_directory (char *filename, unsigned int unit)
char * fsdevice_get_path (unsigned int unit)
void fsdevice_error (vdrive_t *vdrive, int code)
int fsdevice_error_get_byte (vdrive_t *vdrive, uint8_t *data)
int fsdevice_attach (unsigned int device, unsigned int drive, const char *name)
void fsdevice_init (void)
void fsdevice_shutdown (void)
Variables
fsdevice_dev_t fsdevice_dev [4]
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
fsdevice_attach()
int fsdevice_attach (unsigned int device, unsigned int drive, const char * name)
Referenced by file_system_set_serial_hooks().
fsdevice_error()
void fsdevice_error (vdrive_t * vdrive, int code)
Referenced by fsdevice_attach(), fsdevice_close(), fsdevice_error_get_byte(), fsdevice_flush(), fsdevice_flush_write_byte(), fsdevice_open(), fsdevice_open_buffer(), fsdevice_open_directory(), fsdevice_open_file(), fsdevice_relative_switch_record(), fsdevice_write(), and relative_read().
fsdevice_error_get_byte()
int fsdevice_error_get_byte (vdrive_t * vdrive, uint8_t * data)
Referenced by fsdevice_read().
fsdevice_get_path()
char * fsdevice_get_path (unsigned int unit)
Referenced by expand_shortname(), fsdevice_flush_cd(), fsdevice_flush_mkdir(), fsdevice_flush_rename(), fsdevice_flush_rmdir(), fsdevice_flush_scratch(), fsdevice_open_directory(), fsdevice_open_file(), and limit_longname().
fsdevice_init()
void fsdevice_init (void)
Referenced by machine_init().
fsdevice_set_directory()
void fsdevice_set_directory (char * filename, unsigned int unit)
Referenced by autostart_prg_with_virtual_fs(), cmdline_fsdirectory(), and fsdevice_flush_cd().
fsdevice_shutdown()
void fsdevice_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
Variable Documentation
fsdevice_dev
fsdevice_dev_t fsdevice_dev[4]
Referenced by fsdevice_close(), fsdevice_error(), fsdevice_error_get_byte(), fsdevice_flush(), fsdevice_flush_ba(), fsdevice_flush_be(), fsdevice_flush_bf(), fsdevice_flush_br(), fsdevice_flush_bw(), fsdevice_flush_initialize(), fsdevice_flush_new(), fsdevice_flush_position(), fsdevice_flush_rename(), fsdevice_flush_scratch(), fsdevice_flush_u1(), fsdevice_flush_u2(), fsdevice_flush_validate(), fsdevice_flush_write_byte(), fsdevice_init(), fsdevice_listen(), fsdevice_open(), fsdevice_read(), fsdevice_shutdown(), and fsdevice_write().