vsid: drive/drive-check.h File Reference
drive-check.h File Reference
Functions
unsigned int drive_check_bus (unsigned int drive_type, unsigned int bus_map)
unsigned int drive_check_old (unsigned int type)
unsigned int drive_check_dual (unsigned int type)
unsigned int drive_get_num_heads (unsigned int type)
return number of heads for given drive
unsigned int drive_get_half_tracks (unsigned int type)
return number of physical half tracks for given drive
Function Documentation
drive_check_bus()
unsigned int drive_check_bus (unsigned int drive_type, unsigned int bus_map)
< parallel IEEE bus
< serial IEC bus
< parallel TCBM bus
Referenced by drive_check_type(), and drive_resources_type().
drive_check_dual()
unsigned int drive_check_dual (unsigned int type)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
Referenced by create_readonly_check_button(), drive_is_dualdrive_by_devnr(), drive_update_ui_status(), layout_statusbar_drives(), on_model_changed(), ui_display_drive_track(), and ui_enable_drive_status().
drive_check_old()
unsigned int drive_check_old (unsigned int type)
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
Referenced by drivecpu_snapshot_read_module(), and drivecpu_snapshot_write_module().
drive_get_half_tracks()
unsigned int drive_get_half_tracks (unsigned int type)
return number of physical half tracks for given drive
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
drive_get_num_heads()
unsigned int drive_get_num_heads (unsigned int type)
return number of heads for given drive
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 1M/disk
Referenced by ui_display_drive_track().