x128: console.h File Reference
console.h File Reference
Data Structures
struct console_s
Typedefs
typedef struct console_s console_t
Functions
console_t * console_open (const char *id)
int console_close (console_t *log)
int console_init (void)
int console_close_all (void)
int console_out (console_t *log, const char *format,...) VICE_ATTR_PRINTF2
int console_flush (console_t *log)
char * console_in (console_t *log, const char *prompt)
console_t * native_console_open (const char *id)
the same set of functions, which will work with a "native" console of the host
int native_console_close (console_t *log)
int native_console_init (void)
int native_console_close_all (void)
int native_console_out (console_t *log, const char *format,...) VICE_ATTR_PRINTF2
output to console, no translation (ASCII)
int native_console_petscii_out (int maxlen, console_t *log, const char *format,...) VICE_ATTR_PRINTF3
int native_console_petscii_upper_out (int maxlen, console_t *log, const char *format,...) VICE_ATTR_PRINTF3
int native_console_scrcode_out (int maxlen, console_t *log, const char *format,...) VICE_ATTR_PRINTF3
int native_console_flush (console_t *log)
char * native_console_in (console_t *log, const char *prompt)
Typedef Documentation
console_t
typedef struct console_s console_t
Function Documentation
console_close()
int console_close (console_t * log)
console_close_all()
int console_close_all (void)
Referenced by cmdline_help(), and machine_shutdown().
console_flush()
int console_flush (console_t * log)
console_in()
char * console_in (console_t * log, const char * prompt)
Referenced by disableRawMode(), enableRawMode(), and linenoiseReadChar().
console_init()
int console_init (void)
Referenced by init_main().
console_open()
console_t * console_open (const char * id)
console_out()
int console_out (console_t * log, const char * format, ...)
Referenced by disableRawMode(), dynamicRefresh(), enableRawMode(), InputBuffer::refreshLine(), and setDisplayAttribute().
native_console_close()
int native_console_close (console_t * log)
Referenced by uimonfb_window_close().
native_console_close_all()
int native_console_close_all (void)
Referenced by consolefb_close_all().
native_console_flush()
int native_console_flush (console_t * log)
native_console_in()
char * native_console_in (console_t * log, const char * prompt)
Referenced by uimonfb_get_in().
native_console_init()
int native_console_init (void)
Referenced by consolefb_init().
native_console_open()
console_t * native_console_open (const char * id)
the same set of functions, which will work with a "native" console of the host
Referenced by uimonfb_window_open().
native_console_out()
int native_console_out (console_t * log, const char * format, ...)
output to console, no translation (ASCII)
Referenced by consolefb_out(), and uimonfb_out().
native_console_petscii_out()
int native_console_petscii_out (int maxlen, console_t * log, const char * format, ...)
Referenced by uimonfb_petscii_out().
native_console_petscii_upper_out()
int native_console_petscii_upper_out (int maxlen, console_t * log, const char * format, ...)
Referenced by uimonfb_petscii_upper_out().
native_console_scrcode_out()
int native_console_scrcode_out (int maxlen, console_t * log, const char * format, ...)
Referenced by uimonfb_scrcode_out().