vsid: ram.c File Reference
ram.c File Reference
#include "vice.h"
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "cmdline.h"
#include "lib.h"
#include "machine.h"
#include "ram.h"
#include "resources.h"
#include "types.h"
Macros
#define DBG(x)
Enumerations
enum random_method_t {
RANDOM_METHOD_NONE ,
RANDOM_METHOD_GEOM ,
RANDOM_METHOD_UNIFORM
}
Methods for randomly selecting bits to flip.
Functions
static int set_start_value (int val, void *param)
first value of the base pattern (byte value)
static int set_value_invert (int val, void *param)
number of bytes until start value is inverted
static int set_value_offset (int val, void *param)
offset of first pattern in bytes
static int set_pattern_invert (int val, void *param)
invert base pattern after this many bytes
static int set_pattern_invert_value (int val, void *param)
invert base pattern with this byte
static int set_random_start (int val, void *param)
offset where the random pattern starts
static int set_random_repeat (int val, void *param)
repeat random pattern every "val" bytes
static int set_random_chance (int val, void *param)
global random chance
int ram_resources_init (void)
int ram_cmdline_options_init (void)
static unsigned int random_method_geom_next (double log_1mp)
void ram_init_with_pattern (uint8_t *memram, unsigned int ramsize, RAMINITPARAM *ramparam)
this can be used to init arbitrary memory
void ram_init (uint8_t *memram, unsigned int ramsize)
used to initialize the main memory of the machine
void ram_init_print_pattern (char *s, int len, char *eol)
Variables
static RAMINITPARAM mainramparam
static resource_int_t resources_int []
RAM-related resources.
static const cmdline_option_t cmdline_options []
Macro Definition Documentation
DBG
#define DBG (x)
Enumeration Type Documentation
random_method_t
enum random_method_t
Methods for randomly selecting bits to flip.
Enumerator
RANDOM_METHOD_NONE
RANDOM_METHOD_GEOM
RANDOM_METHOD_UNIFORM
Function Documentation
ram_cmdline_options_init()
int ram_cmdline_options_init (void)
Referenced by init_cmdline_options().
ram_init()
void ram_init (uint8_t * memram, unsigned int ramsize)
used to initialize the main memory of the machine
Referenced by mem_powerup(), and ram_init_print_pattern().
ram_init_print_pattern()
void ram_init_print_pattern (char * s, int len, char * eol)
Referenced by on_value_changed().
ram_init_with_pattern()
void ram_init_with_pattern (uint8_t * memram, unsigned int ramsize, RAMINITPARAM * ramparam)
this can be used to init arbitrary memory
< 100%
< 100%
< 100%
< 100%
< 100%
Referenced by ram_init().
ram_resources_init()
int ram_resources_init (void)
Todo:
FIXME: tweak and test defaults for the various machines
< 0.1%
< 0.1%
Referenced by init_resources().
random_method_geom_next()
static unsigned int random_method_geom_next (double log_1mp) static
Referenced by ram_init_with_pattern().
set_pattern_invert()
static int set_pattern_invert (int val, void * param) static
invert base pattern after this many bytes
set_pattern_invert_value()
static int set_pattern_invert_value (int val, void * param) static
invert base pattern with this byte
set_random_chance()
static int set_random_chance (int val, void * param) static
global random chance
< 100%
< 100%
set_random_repeat()
static int set_random_repeat (int val, void * param) static
repeat random pattern every "val" bytes
set_random_start()
static int set_random_start (int val, void * param) static
offset where the random pattern starts
set_start_value()
static int set_start_value (int val, void * param) static
first value of the base pattern (byte value)
set_value_invert()
static int set_value_invert (int val, void * param) static
number of bytes until start value is inverted
set_value_offset()
static int set_value_offset (int val, void * param) static
offset of first pattern in bytes
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-raminitvalueoffset", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RAMInitValueOffset", NULL,
      "<offset>", "The first pattern is shifted by this many bytes" },
    { "-raminitstartvalue", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RAMInitStartValue", NULL,
      "<value>", "Set the value for the very first RAM address after powerup" },
    { "-raminitvalueinvert", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RAMInitValueInvert", NULL,
      "<num of bytes>", "Length of memory block initialized with the same value" },
    { "-raminitpatterninvert", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RAMInitPatternInvert", NULL,
      "<num of bytes>", "Length of memory block initialized with the same pattern" },
    { "-raminitpatterninvertvalue", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RAMInitPatternInvertValue", NULL,
      "<value>", "Value to invert with in second pattern" },
    { "-raminitstartrandom", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RAMInitStartRandom", NULL,
      "<num of bytes>", "Number of random bytes in random pattern" },
    { "-raminitrepeatrandom", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RAMInitRepeatRandom", NULL,
      "<num of bytes>", "Repeat random pattern after this many bytes" },
    { "-raminitrandomchance", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RAMInitRandomChance", NULL,
      "<value>", "Random chance for any bit to flip (0-0xfff)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by ram_cmdline_options_init().
mainramparam
RAMINITPARAM mainramparam static
Initial value:
= {
    .start_value = 255,
    .value_invert = 128,
    .value_offset = 0,
    .pattern_invert = 0,
    .pattern_invert_value = 0,
    .random_start = 0,
    .random_repeat = 0,
    .random_chance = 0,
}
Referenced by ram_init(), set_pattern_invert(), set_pattern_invert_value(), set_random_chance(), set_random_repeat(), set_random_start(), set_start_value(), set_value_invert(), and set_value_offset().
resources_int
resource_int_t resources_int[] static
Initial value:
= {
    { "RAMInitValueOffset", 2, RES_EVENT_SAME, NULL,
      &mainramparam.value_offset, set_value_offset, NULL },
    { "RAMInitStartValue", 0, RES_EVENT_SAME, NULL,
      &mainramparam.start_value, set_start_value, NULL },
    { "RAMInitValueInvert", 4, RES_EVENT_SAME, NULL,
      &mainramparam.value_invert, set_value_invert, NULL },
    { "RAMInitPatternInvert", 16384, RES_EVENT_SAME, NULL,
      &mainramparam.pattern_invert, set_pattern_invert, NULL },
    { "RAMInitPatternInvertValue", 255, RES_EVENT_SAME, NULL,
      &mainramparam.pattern_invert_value, set_pattern_invert_value, NULL },
    { "RAMInitStartRandom", 0, RES_EVENT_SAME, NULL,
      &mainramparam.random_start, set_random_start, NULL },
    { "RAMInitRepeatRandom", 0, RES_EVENT_SAME, NULL,
      &mainramparam.random_repeat, set_random_repeat, NULL },
    { "RAMInitRandomChance",  10  , RES_EVENT_SAME, NULL,
      &mainramparam.random_chance, set_random_chance, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
RAM-related resources.
Todo:
FIXME: the defaults have been choosen so the result matches a real reported pattern in x64sc, AND from those one was picked so all raminitvalue tests pass.
however, the respective defaults should probably be different per emulator/machine.
Referenced by ram_resources_init().