x128: arch/gtk3/widgets/base/ramsizeradiogroup.c File Reference
ramsizeradiogroup.c File Reference
Widget to show a list of radio buttons for RAM sizes.
#include "vice.h"
#include <gtk/gtk.h>
#include "resourceradiogroup.h"
#include "widgethelpers.h"
#include "ramsizeradiogroup.h"
Functions
static vice_gtk3_radiogroup_entry_t * create_entries (const int *sizes)
Generate radio group entries for given array.
static void free_entries (vice_gtk3_radiogroup_entry_t *entries)
Free entries.
GtkWidget * ram_size_radiogroup_new (const char *resource, const char *title, const int *sizes)
Create radio group with RAM size entries and a title.
Detailed Description
Widget to show a list of radio buttons for RAM sizes.
Creates a grid with title and a vertically oriented radio group with radio buttons with KiB/MiB/GiB labels for each ram size given. Note that the sizes are taken to be in kibibytes, so an integer value of 64 will result in "64KiB" and the resource value 64 (NOT 65536).
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_entries()
static vice_gtk3_radiogroup_entry_t * create_entries (const int * sizes) static
Generate radio group entries for given array.
Parameters
[in] sizes sizes in KiB, terminate with <0
Returns
heap-allocated entries, owned by Gtk
Referenced by ram_size_radiogroup_new().
free_entries()
static void free_entries (vice_gtk3_radiogroup_entry_t * entries) static
Free entries.
Parameters
[in] entries heap-allocated list of radio group entries
Referenced by ram_size_radiogroup_new().
ram_size_radiogroup_new()
GtkWidget * ram_size_radiogroup_new (const char * resource, const char * title, const int * sizes)
Create radio group with RAM size entries and a title.
Create a GtkGrid with a label in the top row set to title and a resource radio group for sizes. If title is NULL a resource radio group is returned without the surrounding grid.
The sizes are taken as kibibytes, so plain 64 results in "64KiB" while setting the resource to 64 (not 65536).
Parameters
[in] resource resource to set
[in] title title for the grid (can be NULL)
[in] sizes list of sizes in kibibytes, terminated with < 0
Returns
GtkGrid
Referenced by create_georam_size_widget(), create_ramcart_size_widget(), create_reu_size_widget(), and settings_petreu_widget_create().