vsid: fsdevice/fsdevice-flush.c File Reference
fsdevice-flush.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "archdep.h"
#include "cbmdos.h"
#include "charset.h"
#include "fileio.h"
#include "fsdevice-flush.h"
#include "fsdevice-filename.h"
#include "fsdevice-read.h"
#include "fsdevice-resources.h"
#include "fsdevice.h"
#include "fsdevicetypes.h"
#include "lib.h"
#include "log.h"
#include "types.h"
#include "util.h"
#include "vdrive-command.h"
#include "vdrive.h"
Macros
#define DBG(x)
#define DRIVE_UNIT_MIN 8
Functions
static int fsdevice_flush_reset (void)
static int fsdevice_flush_cd (vdrive_t *vdrive, char *arg)
static int fsdevice_flush_cdup (vdrive_t *vdrive)
static int fsdevice_flush_mkdir (vdrive_t *vdrive, char *arg)
Create directory arg.
static int fsdevice_flush_partition (vdrive_t *vdrive, char *arg)
static int fsdevice_flush_rmdir (vdrive_t *vdrive, char *arg)
Remove directory arg.
static int fsdevice_flush_rename (vdrive_t *vdrive, char *realarg)
static int fsdevice_flush_scratch (vdrive_t *vdrive, char *realarg)
static void get4args (char *realarg, unsigned int *a1, unsigned int *a2, unsigned int *a3, unsigned int *a4)
static unsigned int get_bamptr (unsigned int trk, unsigned int sec)
static unsigned int get_bammask (unsigned int trk, unsigned int sec)
static int fsdevice_flush_ba (vdrive_t *vdrive, char *realarg)
B-A - Block Allocate.
static int fsdevice_flush_bf (vdrive_t *vdrive, char *realarg)
B-F - Block Free.
static int fsdevice_flush_bp (vdrive_t *vdrive, char *realarg)
B-P - Block Pointer.
static int fsdevice_flush_be (vdrive_t *vdrive, char *realarg)
B-E - Block Execute.
static int fsdevice_flush_br (vdrive_t *vdrive, char *realarg)
B-W - Block Read.
static int fsdevice_flush_u1 (vdrive_t *vdrive, char *realarg)
U1, like B-R.
static int fsdevice_flush_bw (vdrive_t *vdrive, char *realarg)
B-W - Block Write.
static int fsdevice_flush_u2 (vdrive_t *vdrive, char *realarg)
U2, like B-W.
static int fsdevice_flush_initialize (vdrive_t *vdrive)
I - Initialize Disk.
static int fsdevice_flush_validate (vdrive_t *vdrive)
V - Validate Disk.
static int fsdevice_flush_new (vdrive_t *vdrive, char *realarg)
N - Format Disk.
static int fsdevice_flush_position (vdrive_t *vdrive, char *buf, int length)
P - Position in RELative file.
void fsdevice_flush (vdrive_t *vdrive, unsigned int secondary)
int fsdevice_flush_write_byte (vdrive_t *vdrive, uint8_t data)
Macro Definition Documentation
DBG
#define DBG (x)
DRIVE_UNIT_MIN
#define DRIVE_UNIT_MIN 8
Function Documentation
fsdevice_flush()
void fsdevice_flush (vdrive_t * vdrive, unsigned int secondary)
Todo:
FIXME: Use ‘vdrive_command_parse()’!
Todo:
FIXME: not implemented
Todo:
FIXME: not implemented
Todo:
FIXME: not implemented
Todo:
FIXME: not implemented
Todo:
FIXME: not implemented
Todo:
FIXME: not implemented
Todo:
FIXME: not implemented
Todo:
FIXME: is this really correct? perhaps we must consider a full path here and only limit the last portion?
Todo:
FIXME: not implemented
Todo:
FIXME: a comma seperated list of files is not handled at all
Referenced by fsdevice_attach().
fsdevice_flush_ba()
static int fsdevice_flush_ba (vdrive_t * vdrive, char * realarg) static
B-A - Block Allocate.
Referenced by fsdevice_flush().
fsdevice_flush_be()
static int fsdevice_flush_be (vdrive_t * vdrive, char * realarg) static
B-E - Block Execute.
Referenced by fsdevice_flush().
fsdevice_flush_bf()
static int fsdevice_flush_bf (vdrive_t * vdrive, char * realarg) static
B-F - Block Free.
Referenced by fsdevice_flush().
fsdevice_flush_bp()
static int fsdevice_flush_bp (vdrive_t * vdrive, char * realarg) static
B-P - Block Pointer.
Referenced by fsdevice_flush().
fsdevice_flush_br()
static int fsdevice_flush_br (vdrive_t * vdrive, char * realarg) static
B-W - Block Read.
Referenced by fsdevice_flush().
fsdevice_flush_bw()
static int fsdevice_flush_bw (vdrive_t * vdrive, char * realarg) static
B-W - Block Write.
Referenced by fsdevice_flush().
fsdevice_flush_cd()
static int fsdevice_flush_cd (vdrive_t * vdrive, char * arg) static
< permission denied
Referenced by fsdevice_flush(), fsdevice_flush_cdup(), and fsdevice_flush_partition().
fsdevice_flush_cdup()
static int fsdevice_flush_cdup (vdrive_t * vdrive) static
Referenced by fsdevice_flush().
fsdevice_flush_initialize()
static int fsdevice_flush_initialize (vdrive_t * vdrive) static
I - Initialize Disk.
Referenced by fsdevice_flush().
fsdevice_flush_mkdir()
static int fsdevice_flush_mkdir (vdrive_t * vdrive, char * arg) static
Create directory arg.
Parameters
[in] vdrive vdrive reference
[in] arg directory name
Returns
CBMDOS error code
< directory separator as a string
< permission denied
Referenced by fsdevice_flush(), and fsdevice_flush_partition().
fsdevice_flush_new()
static int fsdevice_flush_new (vdrive_t * vdrive, char * realarg) static
N - Format Disk.
Referenced by fsdevice_flush().
fsdevice_flush_partition()
static int fsdevice_flush_partition (vdrive_t * vdrive, char * arg) static
Referenced by fsdevice_flush().
fsdevice_flush_position()
static int fsdevice_flush_position (vdrive_t * vdrive, char * buf, int length) static
P - Position in RELative file.
Referenced by fsdevice_flush().
fsdevice_flush_rename()
static int fsdevice_flush_rename (vdrive_t * vdrive, char * realarg) static
< permission denied
Referenced by fsdevice_flush().
fsdevice_flush_reset()
static int fsdevice_flush_reset (void) static
Referenced by fsdevice_flush().
fsdevice_flush_rmdir()
static int fsdevice_flush_rmdir (vdrive_t * vdrive, char * arg) static
Remove directory arg.
Parameters
[in] vdrive vdrive reference
[in] arg directory to remove
Returns
CBMDOS error code
< directory separator as a string
Todo:
FIXME: rmdir() can set a lot of different errors codes, so this probably is a little naive
< dir to remove not empty
< permission denied
Referenced by fsdevice_flush().
fsdevice_flush_scratch()
static int fsdevice_flush_scratch (vdrive_t * vdrive, char * realarg) static
Todo:
FIXME: we need to handle a comma seperated list of files to scratch
< permission denied
Todo:
FIXME: number of files that were scratched
Referenced by fsdevice_flush().
fsdevice_flush_u1()
static int fsdevice_flush_u1 (vdrive_t * vdrive, char * realarg) static
U1, like B-R.
Referenced by fsdevice_flush().
fsdevice_flush_u2()
static int fsdevice_flush_u2 (vdrive_t * vdrive, char * realarg) static
U2, like B-W.
Referenced by fsdevice_flush().
fsdevice_flush_validate()
static int fsdevice_flush_validate (vdrive_t * vdrive) static
V - Validate Disk.
Referenced by fsdevice_flush().
fsdevice_flush_write_byte()
int fsdevice_flush_write_byte (vdrive_t * vdrive, uint8_t data)
Todo:
FIXME: Consider the real size of the input buffer.
Referenced by fsdevice_write().
get4args()
static void get4args (char * realarg, unsigned int * a1, unsigned int * a2, unsigned int * a3, unsigned int * a4) static
Referenced by fsdevice_flush_ba(), fsdevice_flush_be(), fsdevice_flush_bf(), fsdevice_flush_bp(), fsdevice_flush_br(), fsdevice_flush_bw(), fsdevice_flush_u1(), and fsdevice_flush_u2().
get_bammask()
static unsigned int get_bammask (unsigned int trk, unsigned int sec) static
Referenced by fsdevice_flush_ba(), and fsdevice_flush_bf().
get_bamptr()
static unsigned int get_bamptr (unsigned int trk, unsigned int sec) static
Referenced by fsdevice_flush_ba(), and fsdevice_flush_bf().