vsid: printerdrv/output-select.h File Reference
output-select.h File Reference
#include "types.h"
Data Structures
struct output_select_s
Macros
#define NUM_OUTPUT_SELECT 4
serial dev 4, 5, 6 and user port
Typedefs
typedef struct output_select_s output_select_t
Functions
int output_select_init_resources (void)
int output_select_userport_init_resources (void)
void output_select_shutdown (void)
int output_select_init_cmdline_options (void)
int output_select_userport_init_cmdline_options (void)
void output_select_register (output_select_t *output_select)
int output_select_open (unsigned int prnr, struct output_parameter_s *output_parameter)
void output_select_close (unsigned int prnr)
int output_select_putc (unsigned int prnr, uint8_t b)
int output_select_getc (unsigned int prnr, uint8_t *b)
int output_select_flush (unsigned int prnr)
int output_select_formfeed (unsigned int prnr)
void output_select_writeline (unsigned int prnr)
Macro Definition Documentation
NUM_OUTPUT_SELECT
#define NUM_OUTPUT_SELECT 4
serial dev 4, 5, 6 and user port
Typedef Documentation
output_select_t
typedef struct output_select_s output_select_t
Function Documentation
output_select_close()
void output_select_close (unsigned int prnr)
Referenced by drv_1520_close(), drv_2022_select(), drv_4023_select(), drv_8023_select(), drv_ascii_close(), drv_mps801_select(), drv_mps802_select(), drv_mps803_close(), drv_mps803_select(), drv_nl10_shutdown(), and drv_raw_close().
output_select_flush()
int output_select_flush (unsigned int prnr)
Referenced by drv_1520_flush(), drv_ascii_flush(), drv_mps803_flush(), and drv_raw_flush().
output_select_formfeed()
int output_select_formfeed (unsigned int prnr)
Referenced by drv_1520_formfeed(), drv_ascii_formfeed(), drv_mps803_formfeed(), and drv_raw_formfeed().
output_select_getc()
int output_select_getc (unsigned int prnr, uint8_t * b)
Referenced by drv_1520_getc(), drv_ascii_getc(), drv_mps803_getc(), and drv_raw_getc().
output_select_init_cmdline_options()
int output_select_init_cmdline_options (void)
Referenced by printer_cmdline_options_init().
output_select_init_resources()
int output_select_init_resources (void)
Referenced by printer_resources_init().
output_select_open()
int output_select_open (unsigned int prnr, struct output_parameter_s * output_parameter)
Referenced by drv_1520_open(), drv_2022_open(), drv_4023_open(), drv_8023_open(), drv_ascii_open(), drv_mps801_open(), drv_mps802_open(), drv_mps803_open(), drv_nl10_open(), and drv_raw_open().
output_select_putc()
int output_select_putc (unsigned int prnr, uint8_t b)
Referenced by drv_raw_putc(), formfeed(), linefeed(), output_buf(), print_char(), print_lineend(), write_line(), and write_lines().
output_select_register()
void output_select_register (output_select_t * output_select)
Referenced by output_graphics_init_resources(), and output_text_init_resources().
output_select_shutdown()
void output_select_shutdown (void)
Referenced by printer_shutdown().
output_select_userport_init_cmdline_options()
int output_select_userport_init_cmdline_options (void)
Referenced by printer_userport_cmdline_options_init().
output_select_userport_init_resources()
int output_select_userport_init_resources (void)
Referenced by printer_userport_resources_init().
output_select_writeline()
void output_select_writeline (unsigned int prnr)