vsid: tape/t64.c File Reference
t64.c File Reference
T64 file support.
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "lib.h"
#include "log.h"
#include "t64.h"
#include "types.h"
#include "zfile.h"
Functions
static uint32_t get_number (const uint8_t *p, unsigned int n)
Parse n bytes of p for a little endian unsigned integer.
static int check_magic (t64_header_t *hdr)
Check hdr for a valid magic sequence.
static int comp_content (const void *p1, const void *p2)
compar argument to qsort(3) call in t64_open()
static int comp_index (const void *p1, const void *p2)
compar argument to qsort(3) call in t64_open()
static int t64_file_record_read (t64_file_record_t *rec, FILE *fd)
Read and parse a file record.
static int t64_file_record_get_size (t64_file_record_t *rec)
Calculate file size for rec.
static t64_file_record_t * t64_get_file_record (t64_t *t64, unsigned int num)
Get pointer to file record at index num in t64.
static int t64_header_read (t64_header_t *hdr, FILE *fd)
Read and parse T64 header into hdr from file fd.
static t64_t * t64_new (void)
Allocate memory for new T64 container and initialize members.
static void t64_destroy (t64_t *t64)
Free memory and close file used by T64 container t64.
int t64_seek_start (t64_t *t64)
Move file index in t64 to the first file record.
int t64_seek_to_file (t64_t *t64, int file_number)
Move file index in t64 to file_number.
int t64_seek_to_next_file (t64_t *t64, unsigned int allow_rewind)
Move file index record in t64 to next record.
t64_file_record_t * t64_get_current_file_record (t64_t *t64)
Get pointer to current file record.
int t64_read (t64_t *t64, uint8_t *buf, size_t size)
Read size bytes of the current file record in t64 into buf.
void t64_get_header (t64_t *t64, uint8_t *name)
Copy tape description in t64 to name.
t64_t * t64_open (const char *name, unsigned int *read_only)
Try to open file name as a T64 container.
int t64_close (t64_t *t64)
Close T64 container t64.
Variables
static const char *const magic_headers []
magic bytes found at the start of a possible T64 file
Detailed Description
T64 file support.
t64.c - T64 file support.
Written by Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de Compyx b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Function Documentation
check_magic()
static int check_magic (t64_header_t * hdr) static
Check hdr for a valid magic sequence.
Parameters
[in] hdr T64 header
Returns
boolean
Referenced by t64_header_read().
comp_content()
static int comp_content (const void * p1, const void * p2) static
compar argument to qsort(3) call in t64_open()
Compares offsets in T64 container of p1 and \p2 and returns a value like strcmp(). Used to sort records on their data offset, which is required to fix invalid end addresses of records.
Parameters
[in] p1 T64 file record
[in] p2 T64 file record
Returns
0 if equal, <0 if p1 < p2, >0 if p1 > p2
Referenced by t64_open().
comp_index()
static int comp_index (const void * p1, const void * p2) static
compar argument to qsort(3) call in t64_open()
Compares original index of p1 and p2 in T64 container and returns a value like strcmp(). Required to restore the original order of records after sorting on data offset.
Parameters
[in] p1 T64 file record
[in] p2 T64 file record
Returns
0 if equal, <0 if p1 < p2, >0 if p1 > p2
Referenced by t64_open().
get_number()
static uint32_t get_number (const uint8_t * p, unsigned int n) static
Parse n bytes of p for a little endian unsigned integer.
Parameters
[in] p pointer to memory containing value
[in] n number of bytes to use from p
Returns
unsigned integer
Referenced by t64_file_record_read(), and t64_header_read().
t64_close()
int t64_close (t64_t * t64)
Close T64 container t64.
Parameters
[in,out] t64 T64 container
Returns
0 on success, -1 on failure
Referenced by tape_image_close().
t64_destroy()
static void t64_destroy (t64_t * t64) static
Free memory and close file used by T64 container t64.
Parameters
[in,out] t64 T64 container
Referenced by t64_close(), and t64_open().
t64_file_record_get_size()
static int t64_file_record_get_size (t64_file_record_t * rec) static
Calculate file size for rec.
Returns
file size in bytes
Referenced by t64_read().
t64_file_record_read()
static int t64_file_record_read (t64_file_record_t * rec, FILE * fd) static
Read and parse a file record.
Parameters
[out] rec T64 file record
[in] fd file descriptor
Returns
0 on success, -1 on failure
Referenced by t64_open().
t64_get_current_file_record()
t64_file_record_t * t64_get_current_file_record (t64_t * t64)
Get pointer to current file record.
Parameters
[in] t64 T64 container
Returns
file record on NULL on failure
Referenced by tape_find_header_trap(), tape_find_header_trap_plus4(), and tape_get_current_file_record().
t64_get_file_record()
static t64_file_record_t * t64_get_file_record (t64_t * t64, unsigned int num) static
Get pointer to file record at index num in t64.
Parameters
[in] t64 T64 container
[in] num index in directory of t64
Returns
file record or NULL on failure
Referenced by t64_get_current_file_record().
t64_get_header()
void t64_get_header (t64_t * t64, uint8_t * name)
Copy tape description in t64 to name.
Copies the tape description string in t64 to name. Doesn't terminate string with nul if the string is 24 bytes.
Parameters
[in] t64 T64 container
[out] name destination for description, should be at least 24 bytes
Referenced by tape_get_header().
t64_header_read()
static int t64_header_read (t64_header_t * hdr, FILE * fd) static
Read and parse T64 header into hdr from file fd.
Parameters
[out] hdr T64 header
[in] fd file descriptor
Returns
0 on success, -1 on failure
Referenced by t64_open().
t64_new()
static t64_t * t64_new (void) static
Allocate memory for new T64 container and initialize members.
Returns
new T64 object
Referenced by t64_open().
t64_open()
t64_t * t64_open (const char * name, unsigned int * read_only)
Try to open file name as a T64 container.
Parameters
[in] name filename/path to T64 file
[out] read_only read-only status of container
Returns
T64 container on success or NULL on failure
< read mode (binary)
Todo:
FIXME: why does this read all entries and not just the entries actually used?
Referenced by tape_image_open().
t64_read()
int t64_read (t64_t * t64, uint8_t * buf, size_t size)
Read size bytes of the current file record in t64 into buf.
Parameters
[in,out] t64 T64 container
[out] buf buffer to store file data
[in] size number of bytes to read
Returns
number of bytes read or -1 on failure
Todo:
should return long, fread(3) returns long, not int
Referenced by tape_read(), tape_receive_trap(), and tape_receive_trap_plus4().
t64_seek_start()
int t64_seek_start (t64_t * t64)
Move file index in t64 to the first file record.
Parameters
[in] t64 T64 container
Returns
0 on success, -1 on failure
Referenced by tape_seek_start().
t64_seek_to_file()
int t64_seek_to_file (t64_t * t64, int file_number)
Move file index in t64 to file_number.
Parameters
[in,out] t64 T64 container
[in] file_number index in directory of t64
Returns
0 on success, -1 on failure
Referenced by t64_seek_start(), and tape_seek_to_file().
t64_seek_to_next_file()
int t64_seek_to_next_file (t64_t * t64, unsigned int allow_rewind)
Move file index record in t64 to next record.
Moves the directory index one record forward, if no such record exists AND allow_rewind is true, move to the first record.
Parameters
[in,out] t64 T64 container
[in] allow_rewind allow rewinding the 'tape' once
Returns
0 on success, -1 on failure
Referenced by tape_find_header_trap(), tape_find_header_trap_plus4(), and tape_seek_to_next_file().
Variable Documentation
magic_headers
const char* const magic_headers[] static
Initial value:
= {
    "C64 tape image file",
    "C64S tape file",
    "C64S tape image file",
    NULL
}
magic bytes found at the start of a possible T64 file
Referenced by check_magic().