x128: arch/gtk3/uidata.c File Reference
uidata.c File Reference
GTK3 binary resources handling.
#include "vice.h"
#include <gtk/gtk.h>
#include "debug_gtk3.h"
#include "lib.h"
#include "log.h"
#include "sysfile.h"
#include "util.h"
#include "uidata.h"
Functions
gboolean uidata_init (void)
Intialize the GResource binary blob handling.
void uidata_shutdown (void)
Clean up GResource data.
GdkPixbuf * uidata_get_pixbuf (const gchar *name)
Get a pixbuf from the GResource blob.
GdkPixbuf * uidata_get_pixbuf_at_scale (const gchar *name, gint width, gint height, gboolean preserve_aspect)
Get a pixbuf from the GResource blob and scale it.
GBytes * uidata_get_bytes (const gchar *name)
Get a bytes from the GResource blob.
Variables
static GResource * gresource = NULL
Reference to the global GResource data.
Detailed Description
GTK3 binary resources handling.
Mostly a wrapper around the GResource API, which appears to be the way to handle binary resources in Gtk3 applications.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
uidata_get_bytes()
GBytes * uidata_get_bytes (const gchar * name)
Get a bytes from the GResource blob.
Parameters
[in] name path in gresource
Returns
GBytes* or NULL on error
uidata_get_pixbuf()
GdkPixbuf * uidata_get_pixbuf (const gchar * name)
Get a pixbuf from the GResource blob.
Parameters
[in] name virtual path to the file
Returns
GdkPixbuf or NULL on error
Referenced by get_default_icon(), and get_vice_logo().
uidata_get_pixbuf_at_scale()
GdkPixbuf * uidata_get_pixbuf_at_scale (const gchar * name, gint width, gint height, gboolean preserve_aspect)
Get a pixbuf from the GResource blob and scale it.
Parameters
[in] name path in gresource
[in] width width of rescaled pixbuf
[in] height height of rescaled pixbuf
[in] preserve_aspect preserve aspect ratio
Returns
pixbuf or NULL on error
Referenced by get_default_icon().
uidata_init()
gboolean uidata_init (void)
Intialize the GResource binary blob handling.
Returns
non-0 on success
Referenced by ui_init().
uidata_shutdown()
void uidata_shutdown (void)
Clean up GResource data.
Referenced by ui_shutdown().
Variable Documentation
gresource
GResource* gresource = NULL static
Reference to the global GResource data.
Referenced by uidata_get_bytes(), uidata_init(), and uidata_shutdown().