x128: vdrive/vdrive-rel.h File Reference
vdrive-rel.h File Reference
#include "types.h"
Macros
#define SIDE_SECTORS_MAX 6
#define SIDE_INDEX_MAX 120
#define OFFSET_NEXT_TRACK 0
#define OFFSET_NEXT_SECTOR 1
#define OFFSET_SECTOR_NUM 2
#define OFFSET_RECORD_LEN 3
#define OFFSET_SIDE_SECTOR 4
#define OFFSET_POINTER 16
#define OFFSET_SUPER_254 2
#define OFFSET_SUPER_POINTER 3
#define SIDE_SUPER_MAX 126
Functions
void vdrive_rel_init (void)
int vdrive_rel_open (struct vdrive_s *vdrive, unsigned int secondary, cbmdos_cmd_parse_plus_t *cmd_parse)
int vdrive_rel_position (struct vdrive_s *vdrive, unsigned int channel, unsigned int rec_lo, unsigned int rec_hi, unsigned int position)
int vdrive_rel_read (struct vdrive_s *vdrive, uint8_t *data, unsigned int secondary)
int vdrive_rel_write (struct vdrive_s *vdrive, uint8_t data, unsigned int secondary)
int vdrive_rel_close (struct vdrive_s *vdrive, unsigned int secondary)
void vdrive_rel_listen (struct vdrive_s *vdrive, unsigned int secondary)
void vdrive_rel_scratch (struct vdrive_s *vdrive, unsigned int t, unsigned int s)
un-allocate super/sidesector blocks
int vdrive_rel_setup_ss_buffers (struct vdrive_s *vdrive, unsigned int secondary)
void vdrive_rel_shutdown_ss_buffers (struct vdrive_s *vdrive, unsigned int secondary)
Macro Definition Documentation
OFFSET_NEXT_SECTOR
#define OFFSET_NEXT_SECTOR 1
OFFSET_NEXT_TRACK
#define OFFSET_NEXT_TRACK 0
OFFSET_POINTER
#define OFFSET_POINTER 16
OFFSET_RECORD_LEN
#define OFFSET_RECORD_LEN 3
OFFSET_SECTOR_NUM
#define OFFSET_SECTOR_NUM 2
OFFSET_SIDE_SECTOR
#define OFFSET_SIDE_SECTOR 4
OFFSET_SUPER_254
#define OFFSET_SUPER_254 2
OFFSET_SUPER_POINTER
#define OFFSET_SUPER_POINTER 3
SIDE_INDEX_MAX
#define SIDE_INDEX_MAX 120
SIDE_SECTORS_MAX
#define SIDE_SECTORS_MAX 6
SIDE_SUPER_MAX
#define SIDE_SUPER_MAX 126
Function Documentation
vdrive_rel_close()
int vdrive_rel_close (struct vdrive_s * vdrive, unsigned int secondary)
Referenced by vdrive_iec_close().
vdrive_rel_init()
void vdrive_rel_init (void)
Referenced by vdrive_init().
vdrive_rel_listen()
void vdrive_rel_listen (struct vdrive_s * vdrive, unsigned int secondary)
Referenced by vdrive_iec_listen().
vdrive_rel_open()
int vdrive_rel_open (struct vdrive_s * vdrive, unsigned int secondary, cbmdos_cmd_parse_plus_t * cmd_parse)
Referenced by vdrive_iec_open().
vdrive_rel_position()
int vdrive_rel_position (struct vdrive_s * vdrive, unsigned int channel, unsigned int rec_lo, unsigned int rec_hi, unsigned int position)
Referenced by copy_cmd(), and vdrive_command_position().
vdrive_rel_read()
int vdrive_rel_read (struct vdrive_s * vdrive, uint8_t * data, unsigned int secondary)
Referenced by vdrive_iec_read().
vdrive_rel_scratch()
void vdrive_rel_scratch (struct vdrive_s * vdrive, unsigned int t, unsigned int s)
un-allocate super/sidesector blocks
Referenced by vdrive_dir_remove_slot().
vdrive_rel_setup_ss_buffers()
int vdrive_rel_setup_ss_buffers (struct vdrive_s * vdrive, unsigned int secondary)
Referenced by vdrive_command_copy(), and vdrive_rel_open_new().
vdrive_rel_shutdown_ss_buffers()
void vdrive_rel_shutdown_ss_buffers (struct vdrive_s * vdrive, unsigned int secondary)
Referenced by vdrive_command_copy(), and vdrive_rel_close().
vdrive_rel_write()
int vdrive_rel_write (struct vdrive_s * vdrive, uint8_t data, unsigned int secondary)
Referenced by vdrive_iec_write(), and vdrive_rel_fillrecord().