x128: drive/tcbm/glue1551.c File Reference
glue1551.c File Reference
#include "vice.h"
#include "alarm.h"
#include "drive-writeprotect.h"
#include "drive.h"
#include "drivetypes.h"
#include "glue1551.h"
#include "interrupt.h"
#include "lib.h"
#include "rotation.h"
#include "types.h"
#include "drive-sound.h"
Data Structures
struct glue1551_s
Macros
#define GLUE1551_ALARM_TICKS_ON 50
#define GLUE1551_ALARM_TICKS_OFF 19950
Typedefs
typedef struct glue1551_s glue1551_t
Functions
static void glue_pport_update (diskunit_context_t *drv)
uint8_t glue1551_port0_read (diskunit_context_t *drv)
uint8_t glue1551_port1_read (diskunit_context_t *drv)
void glue1551_port0_store (diskunit_context_t *drv, uint8_t value)
void glue1551_port1_store (diskunit_context_t *drv, uint8_t value)
static void glue1551_timer (CLOCK offset, void *data)
void glue1551_init (diskunit_context_t *drv)
void glue1551_reset (diskunit_context_t *drv)
Variables
static glue1551_t glue1551 [4]
Macro Definition Documentation
GLUE1551_ALARM_TICKS_OFF
#define GLUE1551_ALARM_TICKS_OFF 19950
GLUE1551_ALARM_TICKS_ON
#define GLUE1551_ALARM_TICKS_ON 50
Typedef Documentation
glue1551_t
typedef struct glue1551_s glue1551_t
Function Documentation
glue1551_init()
void glue1551_init (diskunit_context_t * drv)
Referenced by tcbm_drive_init().
glue1551_port0_read()
uint8_t glue1551_port0_read (diskunit_context_t * drv)
Referenced by drive_read_zero().
glue1551_port0_store()
void glue1551_port0_store (diskunit_context_t * drv, uint8_t value)
Referenced by drive_store_zero().
glue1551_port1_read()
uint8_t glue1551_port1_read (diskunit_context_t * drv)
Referenced by drive_read_zero().
glue1551_port1_store()
void glue1551_port1_store (diskunit_context_t * drv, uint8_t value)
Referenced by drive_store_zero().
glue1551_reset()
void glue1551_reset (diskunit_context_t * drv)
Referenced by tcbm_drive_reset().
glue1551_timer()
static void glue1551_timer (CLOCK offset, void * data) static
Referenced by glue1551_init().
glue_pport_update()
static void glue_pport_update (diskunit_context_t * drv) static
< chosen for the bit in the VIA2 PB register
< chosen for the bit in the VIA2 PCR register
< chosen for the bit in the VIA2 PB register
< chosen for the bit in the VIA2 PCR register
Referenced by glue1551_port0_read(), glue1551_port0_store(), glue1551_port1_read(), and glue1551_port1_store().
Variable Documentation
glue1551
glue1551_t glue1551[4] static
Referenced by glue1551_init(), glue1551_reset(), and glue1551_timer().