vsid: arch/gtk3/widgets/base/resourcecombobox.c File Reference
resourcecombobox.c File Reference
Combo boxes connected to a resource.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdarg.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "basewidget_types.h"
#include "debug_gtk3.h"
#include "lib.h"
#include "log.h"
#include "resourcehelpers.h"
#include "resources.h"
#include "resourcewidgetmediator.h"
#include "resourcecombobox.h"
Enumerations
enum {
COLUMN_ID ,
COLUMN_VALUE
}
Model columns for (id, value) pairs.
Functions
static GtkListStore * combo_int_model_new (const vice_gtk3_combo_entry_int_t *list)
Create a model for a combo box with ints as IDs.
static void combo_int_model_append (GtkListStore *model, int id, const char *value)
Append row to int combo model.
static GtkWidget * combo_int_view_new (GtkListStore *model)
Create a view for a combo box with ints as IDs.
static gboolean get_combo_int_id (GtkComboBox *combo, int *id)
Get current ID of combo.
static gboolean set_combo_int_id (GtkComboBox *combo, int id)
Set ID of combo to id.
static void on_combo_int_changed (GtkComboBox *self, gpointer data)
Handler for the "changed" event of the integer combo box.
GtkWidget * vice_gtk3_resource_combo_int_new (const char *resource, const vice_gtk3_combo_entry_int_t *entries)
Create a combo box to control an integer resource.
GtkWidget * vice_gtk3_resource_combo_int_new_sprintf (const char *fmt, const vice_gtk3_combo_entry_int_t *entries,...)
Create a combo box to control an integer resource.
void vice_gtk3_resource_combo_int_append (GtkWidget *widget, int id, const char *value)
Append row to integer combo box.
gboolean vice_gtk3_resource_combo_int_set (GtkWidget *widget, int id)
Set new ID for integer combo box.
gboolean vice_gtk3_resource_combo_int_factory (GtkWidget *widget)
Reset widget to its factory default.
gboolean vice_gtk3_resource_combo_int_reset (GtkWidget *widget)
Reset widget to its state when it was instanciated.
gboolean vice_gtk3_resource_combo_int_sync (GtkWidget *widget)
Synchronize widget with its resource value.
static void combo_hex_model_append (GtkListStore *model, int value)
Add value to model.
static GtkListStore * combo_hex_model_list_new (const int *list)
Create model from list of integer values.
static GtkListStore * combo_hex_model_range_new (int lower, int upper, int step)
Create model from range of integer values.
static GtkWidget * combo_hex_view_new (GtkListStore *model)
Create view for a hex resource combo.
static GtkWidget * combo_hex_helper (const char *resource, GtkListStore *model)
Helper to create hex resource combo box.
GtkWidget * vice_gtk3_resource_combo_hex_new (const char *resource)
Create resource-bound combo box showing hex literals.
GtkWidget * vice_gtk3_resource_combo_hex_new_list (const char *resource, const int *list)
Create resource-bound combo box showing hex literals.
GtkWidget * vice_gtk3_resource_combo_hex_new_range (const char *resource, int lower, int upper, int step)
Create resource-bound combo box showing hex literals.
void vice_gtk3_resource_combo_hex_append (GtkWidget *combo, int value)
Append value to hex combo box.
gboolean vice_gtk3_resource_combo_hex_set (GtkWidget *combo, int id)
Set hex resource combo box ID, triggering resource update.
gboolean vice_gtk3_resource_combo_hex_factory (GtkWidget *combo)
Reset hex combo box to the resource factory value.
gboolean vice_gtk3_resource_combo_hex_reset (GtkWidget *combo)
Reset hex combo box to its value on instanciation.
gboolean vice_gtk3_resource_combo_hex_sync (GtkWidget *combo)
Synchronized hex combo box with its resource.
static GtkListStore * combo_str_model_new (const vice_gtk3_combo_entry_str_t *entries)
Create model for combo box with string (id,value) pairs.
static void combo_str_model_append (GtkListStore *model, const char *id, const char *value)
Append row to string resource combo box model.
static GtkWidget * combo_str_view_new (GtkListStore *model)
Create combo box for string resources and initialize with model.
static void on_combo_str_changed (GtkComboBox *self, gpointer data)
Handler for the 'changed' event of the string combo box.
GtkWidget * vice_gtk3_resource_combo_str_new (const char *resource, const vice_gtk3_combo_entry_str_t *entries)
Create a combo box bound to a string resource.
GtkWidget * vice_gtk3_resource_combo_str_new_sprintf (const char *fmt, const vice_gtk3_combo_entry_str_t *entries,...)
Create a combo box to control a string resource.
void vice_gtk3_resource_combo_str_append (GtkWidget *widget, const char *id, const char *value)
Append row to string resource combo box.
gboolean vice_gtk3_resource_combo_str_set (GtkWidget *widget, const char *id)
Update string combo box by ID.
gboolean vice_gtk3_resource_combo_str_factory (GtkWidget *widget)
Reset string combo box to its factory default.
gboolean vice_gtk3_resource_combo_str_reset (GtkWidget *widget)
Reset string combo box to its original value.
gboolean vice_gtk3_resource_combo_str_sync (GtkWidget *widget)
Synchronize widget with its resource.
Detailed Description
Combo boxes connected to a resource.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
anonymous enum
anonymous enum
Model columns for (id, value) pairs.
Enumerator
COLUMN_ID
ID column (hidden)
COLUMN_VALUE
value column (shown)
Function Documentation
combo_hex_helper()
static GtkWidget * combo_hex_helper (const char * resource, GtkListStore * model) static
Helper to create hex resource combo box.
Parameters
[in] resource resource name
[in] model model for the combo box
Returns
GtkComboBox
Referenced by vice_gtk3_resource_combo_hex_new(), vice_gtk3_resource_combo_hex_new_list(), and vice_gtk3_resource_combo_hex_new_range().
combo_hex_model_append()
static void combo_hex_model_append (GtkListStore * model, int value) static
Add value to model.
Add value as integer ID and as a hex string (prefixed with '$') to be displayed.
Parameters
[in] model hex resource combo model
[in] value value for model
Referenced by combo_hex_model_list_new(), combo_hex_model_range_new(), and vice_gtk3_resource_combo_hex_append().
combo_hex_model_list_new()
static GtkListStore * combo_hex_model_list_new (const int * list) static
Create model from list of integer values.
Create hex combo model from values in list.
Parameters
[in] list values, terminated with <0
Returns
populated model
Referenced by vice_gtk3_resource_combo_hex_new_list().
combo_hex_model_range_new()
static GtkListStore * combo_hex_model_range_new (int lower, int upper, int step) static
Create model from range of integer values.
Create hex combo model with values starting with lower up to, but excluding, upper, incrementing with step.
Parameters
[in] list values, terminated with <0
Returns
populated model
Referenced by vice_gtk3_resource_combo_hex_new_range().
combo_hex_view_new()
static GtkWidget * combo_hex_view_new (GtkListStore * model) static
Create view for a hex resource combo.
Create combo box for model.
Parameters
[in] model model for the combo box
Returns
GtkComboBox
Referenced by combo_hex_helper().
combo_int_model_append()
static void combo_int_model_append (GtkListStore * model, int id, const char * value) static
Append row to int combo model.
Parameters
[in] model combo box model
[in] id ID for row
[in] value displayed value for row
Referenced by combo_hex_model_append(), and vice_gtk3_resource_combo_int_append().
combo_int_model_new()
static GtkListStore * combo_int_model_new (const vice_gtk3_combo_entry_int_t * list) static
Create a model for a combo box with ints as IDs.
Parameters
[in] list list of options
Returns
model
Referenced by combo_hex_model_list_new(), combo_hex_model_range_new(), vice_gtk3_resource_combo_hex_new(), and vice_gtk3_resource_combo_int_new().
combo_int_view_new()
static GtkWidget * combo_int_view_new (GtkListStore * model) static
Create a view for a combo box with ints as IDs.
Parameters
[in] model model
Returns
GtkComboBox
Todo:
almost exact copy of create_combo_hex_view(), so refactor!
Referenced by vice_gtk3_resource_combo_int_new().
combo_str_model_append()
static void combo_str_model_append (GtkListStore * model, const char * id, const char * value) static
Append row to string resource combo box model.
Parameters
[in] model model
[in] id ID for the row
[in] value display value for the row
Referenced by vice_gtk3_resource_combo_str_append().
combo_str_model_new()
static GtkListStore * combo_str_model_new (const vice_gtk3_combo_entry_str_t * entries) static
Create model for combo box with string (id,value) pairs.
Create model for combo box with column 0 as ID (string) and column 1 as display value (string)).
Parameters
[in] entries list of entries for the model (can be NULL)
Returns
new model
Referenced by vice_gtk3_resource_combo_str_new().
combo_str_view_new()
static GtkWidget * combo_str_view_new (GtkListStore * model) static
Create combo box for string resources and initialize with model.
Parameters
[in] model model
Returns
GtkComboBox
Referenced by vice_gtk3_resource_combo_str_new().
get_combo_int_id()
static gboolean get_combo_int_id (GtkComboBox * combo, int * id) static
Get current ID of combo.
Parameters
[in] combo combo box
[out] id target of ID value
Returns
boolean
Note
When this function returns false, the value in id is unchanged
Referenced by on_combo_int_changed(), and vice_gtk3_resource_combo_int_sync().
on_combo_int_changed()
static void on_combo_int_changed (GtkComboBox * self, gpointer data) static
Handler for the "changed" event of the integer combo box.
Updates the resource connected to the combo box
Parameters
[in] self combo box
[in] data extra event data (unused)
Referenced by combo_hex_helper(), and vice_gtk3_resource_combo_int_new().
on_combo_str_changed()
static void on_combo_str_changed (GtkComboBox * self, gpointer data) static
Handler for the 'changed' event of the string combo box.
Updates the resource connected to the combo box
Parameters
[in] combo combo box
[in] data extra event data (unused)
Referenced by vice_gtk3_resource_combo_str_new().
set_combo_int_id()
static gboolean set_combo_int_id (GtkComboBox * combo, int id) static
Set ID of combo to id.
Parameters
[in,out] combo combo box
[in] id ID for combo
Returns
boolean
Referenced by combo_hex_helper(), on_combo_int_changed(), vice_gtk3_resource_combo_int_factory(), vice_gtk3_resource_combo_int_new(), vice_gtk3_resource_combo_int_set(), and vice_gtk3_resource_combo_int_sync().
vice_gtk3_resource_combo_hex_append()
void vice_gtk3_resource_combo_hex_append (GtkWidget * combo, int value)
Append value to hex combo box.
Parameters
[in] combo hex resource combo box
[in] value value to apend (will be displayed as "\$hhhhh")
vice_gtk3_resource_combo_hex_factory()
gboolean vice_gtk3_resource_combo_hex_factory (GtkWidget * combo)
Reset hex combo box to the resource factory value.
Set combo box and the bound resource to the resource factory value.
Parameters
[in] combo
Returns
TRUE if the combo box and the resource could be set
vice_gtk3_resource_combo_hex_new()
GtkWidget * vice_gtk3_resource_combo_hex_new (const char * resource)
Create resource-bound combo box showing hex literals.
Create combo box bound to an integer resource that shows a hex string in the form '$hhhh' for each value in list.
This function creates the combo box with an empty model, which can then be populated using vice_gtk3_resource_combo_hex_append().
Returns
GtkComboBox
vice_gtk3_resource_combo_hex_new_list()
GtkWidget * vice_gtk3_resource_combo_hex_new_list (const char * resource, const int * list)
Create resource-bound combo box showing hex literals.
Create combo box bound to an integer resource that shows a hex string in the form '$hhhh' for each value in list.
Parameters
[in] resource resource name
[in] list list of values, terminate with <0
Returns
GtkComboBox
Referenced by create_base_widget(), and create_extra_sid_address_widget().
vice_gtk3_resource_combo_hex_new_range()
GtkWidget * vice_gtk3_resource_combo_hex_new_range (const char * resource, int lower, int upper, int step)
Create resource-bound combo box showing hex literals.
Create combo box bound to an integer resource that shows a hex string in the form '$hhhh' for each value in range lower to upper (exclusive).
Parameters
[in] resource resource name
[in] lower range starting value (inclusive)
[in] upper range ending value (exclusive)
[in] step increment of value
Returns
GtkComboBox
Referenced by settings_digimax_widget_create().
vice_gtk3_resource_combo_hex_reset()
gboolean vice_gtk3_resource_combo_hex_reset (GtkWidget * combo)
Reset hex combo box to its value on instanciation.
Reset combo to the value the resource had when the combo was created.
Parameters
[in] combo
Returns
TRUE if the combo box and the resource could be set
vice_gtk3_resource_combo_hex_set()
gboolean vice_gtk3_resource_combo_hex_set (GtkWidget * combo, int id)
Set hex resource combo box ID, triggering resource update.
Parameters
[in] combo hex resource combo box
[in] id new ID for combo
Returns
TRUE if the combo box ID and resource value could be set
vice_gtk3_resource_combo_hex_sync()
gboolean vice_gtk3_resource_combo_hex_sync (GtkWidget * combo)
Synchronized hex combo box with its resource.
Set combo to the current value of its resource, without triggering a resource-set operation.
Returns
TRUE if the combo box could be synchronized with its resource
vice_gtk3_resource_combo_int_append()
void vice_gtk3_resource_combo_int_append (GtkWidget * widget, int id, const char * value)
Append row to integer combo box.
Parameters
[in] widget integer resource combo box
[in] id ID for row
[in] value displayed string for row
Referenced by create_joyport_combo(), and joystick_device_widget_create().
vice_gtk3_resource_combo_int_factory()
gboolean vice_gtk3_resource_combo_int_factory (GtkWidget * widget)
Reset widget to its factory default.
Parameters
[in,out] widget integer resource combo box
Returns
TRUE if the widget was reset to its factory value
Referenced by vice_gtk3_resource_combo_hex_factory().
vice_gtk3_resource_combo_int_new()
GtkWidget * vice_gtk3_resource_combo_int_new (const char * resource, const vice_gtk3_combo_entry_int_t * entries)
Create a combo box to control an integer resource.
Create integer resource-bound combo box for resource, populating it with entries. The entries list is allowed to be NULL, in which case an empty model is created and the user can manually add rows using vice_gtk3_resource_combo_int_append().
Parameters
[in] resource resource name
[in] entries list of entries for the combo box (can be NULL)
Returns
GtkComboBoxText
Referenced by create_acia_serial_device_widget(), create_acia_widget(), create_ide64_shortbus_layout(), create_serial_baud_widget(), create_tapecart_widget(), create_userport_widget(), joystick_device_widget_create(), kbdhostlayout_widget_create(), settings_ramreset_widget_create(), settings_retroreplay_widget_create(), settings_scpu64_widget_create(), and vice_gtk3_resource_combo_int_new_sprintf().
vice_gtk3_resource_combo_int_new_sprintf()
GtkWidget * vice_gtk3_resource_combo_int_new_sprintf (const char * fmt, const vice_gtk3_combo_entry_int_t * entries, ...)
Create a combo box to control an integer resource.
Create integer resource-bound combo box, populating it with entries. The entries list is allowed to be NULL, in which case an empty model is created and the user can manually add rows using vice_gtk3_resource_combo_int_append().
This verions allows setting the resource name via sprintf()-syntax.
Parameters
[in] fmt format string for the resource name
[in] entries list of entries for the combo box (can be NULL)
Returns
GtkComboBoxText
Referenced by create_drive_device_type_widget(), create_joyport_combo(), create_screenshot_param_widget(), drive_extend_policy_widget_create(), drive_idle_method_widget_create(), and drive_parallel_cable_widget_create().
vice_gtk3_resource_combo_int_reset()
gboolean vice_gtk3_resource_combo_int_reset (GtkWidget * widget)
Reset widget to its state when it was instanciated.
Parameters
[in,out] widget integer resource combo box
Returns
bool
Referenced by vice_gtk3_resource_combo_hex_reset().
vice_gtk3_resource_combo_int_set()
gboolean vice_gtk3_resource_combo_int_set (GtkWidget * widget, int id)
Set new ID for integer combo box.
Set new ID of the combo box
Parameters
[in,out] widget integer resource combo box
[in] id new ID for the combo box resource
Returns
TRUE if the new id was set
Referenced by on_rsinterface_changed(), vice_gtk3_resource_combo_hex_set(), and vice_gtk3_resource_combo_int_reset().
vice_gtk3_resource_combo_int_sync()
gboolean vice_gtk3_resource_combo_int_sync (GtkWidget * widget)
Synchronize widget with its resource value.
Parameters
[in,out] widget integer resource combo box
Returns
bool
Referenced by on_control_port_changed(), and vice_gtk3_resource_combo_hex_sync().
vice_gtk3_resource_combo_str_append()
void vice_gtk3_resource_combo_str_append (GtkWidget * widget, const char * id, const char * value)
Append row to string resource combo box.
Parameters
[in] widget string resource combo box
[in] id ID for the row
[in] value display value for the row
Note
id and value must both be non-NULL and non-empty.
Referenced by settings_snapshot_widget_create().
vice_gtk3_resource_combo_str_factory()
gboolean vice_gtk3_resource_combo_str_factory (GtkWidget * widget)
Reset string combo box to its factory default.
Parameters
[in,out] widget string resource combo box
Returns
TRUE if the factory default was set
vice_gtk3_resource_combo_str_new()
GtkWidget * vice_gtk3_resource_combo_str_new (const char * resource, const vice_gtk3_combo_entry_str_t * entries)
Create a combo box bound to a string resource.
Parameters
[in] resource resource name
[in] entries list of entries for the combo box or NULL
Returns
GtkComboBox
Referenced by settings_snapshot_widget_create(), and vice_gtk3_resource_combo_str_new_sprintf().
vice_gtk3_resource_combo_str_new_sprintf()
GtkWidget * vice_gtk3_resource_combo_str_new_sprintf (const char * fmt, const vice_gtk3_combo_entry_str_t * entries, ...)
Create a combo box to control a string resource.
Parameters
[in] fmt resource name, printf-style format string
[in] entries list of entries for the combo box or NULL
Returns
GtkComboBoxText
vice_gtk3_resource_combo_str_reset()
gboolean vice_gtk3_resource_combo_str_reset (GtkWidget * widget)
Reset string combo box to its original value.
Restores the state of the widget as it was when instanciated.
Parameters
[in,out] widget string resource combo box
Returns
TRUE if the combo box was reset
vice_gtk3_resource_combo_str_set()
gboolean vice_gtk3_resource_combo_str_set (GtkWidget * widget, const char * id)
Update string combo box by ID.
Set new ID of the combo box
Parameters
[in,out] widget string resource combo box
[in] id new ID of the combo box
Returns
TRUE if the new id was set
vice_gtk3_resource_combo_str_sync()
gboolean vice_gtk3_resource_combo_str_sync (GtkWidget * widget)
Synchronize widget with its resource.
Updates the widget state to what its resource currently is.
Parameters
[in,out] widget string resource combo box
Returns
TRUE if the widget was synchronized with its resource
Referenced by settings_snapshot_widget_create().