vsid: arch/gtk3/widgets/plus4memoryexpansionwidget.c File Reference
plus4memoryexpansionwidget.c File Reference
Plus4 memory expansion widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "resources.h"
#include "plus4memhacks.h"
#include "plus4memoryexpansionwidget.h"
Functions
GtkWidget * plus4_memory_expansion_widget_create (void)
Create Plus/4 memory expansion widget.
void plus4_memory_expansion_widget_add_callback (void(*callback)(GtkWidget *, int))
Set user-defined callback.
gboolean plus4_memory_expansion_widget_sync (void)
Synchronize the widget with its resource.
Variables
static const vice_gtk3_radiogroup_entry_t expansions []
List of memory expansion hacks.
static GtkWidget * radio_group = NULL
Reference to the radiogroup widget.
Detailed Description
Plus4 memory expansion widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
plus4_memory_expansion_widget_add_callback()
void plus4_memory_expansion_widget_add_callback (void(*)(GtkWidget *, int) callback)
Set user-defined callback.
This callback will be called with RAM-size and hack-type arguments
Parameters
[in] callback function to trigger
Referenced by create_plus4_layout().
plus4_memory_expansion_widget_create()
GtkWidget * plus4_memory_expansion_widget_create (void)
Create Plus/4 memory expansion widget.
Returns
GtkGrid
Referenced by create_plus4_layout().
plus4_memory_expansion_widget_sync()
gboolean plus4_memory_expansion_widget_sync (void)
Synchronize the widget with its resource.
No need for passing in the widget reference, there shall be only one.
Returns
TRUE if the widget was synchronized
Referenced by plus4_mem_size_callback().
Variable Documentation
expansions
const vice_gtk3_radiogroup_entry_t expansions[] static
Initial value:
= {
    { "None",               MEMORY_HACK_NONE },
    { "256KiB (CSORY)",     MEMORY_HACK_C256K },
    { "256KiB (HANNES)",    MEMORY_HACK_H256K },
    { "1024KiB (HANNES)",   MEMORY_HACK_H1024K },
    { "4096KiB (HANNES)",   MEMORY_HACK_H4096K },
    { NULL, -1 }
}
List of memory expansion hacks.
This list is used to build the radio button group
Referenced by plus4_memory_expansion_widget_create().
radio_group
GtkWidget* radio_group = NULL static
Reference to the radiogroup widget.
Referenced by plus4_memory_expansion_widget_add_callback(), plus4_memory_expansion_widget_create(), and plus4_memory_expansion_widget_sync().