vsid: arch/gtk3/widgets/ciamodelwidget.c File Reference
ciamodelwidget.c File Reference
Widget to set the CIA model.
#include "vice.h"
#include <gtk/gtk.h>
#include "cia.h"
#include "vice_gtk3.h"
#include "ciamodelwidget.h"
Functions
static void cia_model_callback_internal (GtkWidget *widget, int model)
Handler for the radiogroup callbacks for the CIA models.
static void on_destroy (GtkWidget *self, gpointer data)
Properly clear references.
static GtkWidget * create_cia_widget (int num)
Create a widget for CIA num.
GtkWidget * cia_model_widget_create (int count)
Create CIA model(s) widget.
void cia_model_widget_sync (GtkWidget *widget)
Synchronize CIA model widgets with their current resources.
void cia_model_widget_set_callback (GtkWidget *widget, void(*func)(int cia_num, int cia_model))
Set extra callback for changes in the widget.
Variables
static const vice_gtk3_radiogroup_entry_t cia_models []
List of CIA models.
static GtkWidget * cia1_group
Reference to the radiobutton group used for CIA1.
static GtkWidget * cia2_group
Reference to the radiobutton group used for CIA2.
static void(* cia_model_callback)(int, int)
Optional extra callback for widget changes.
Detailed Description
Widget to set the CIA model.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
cia_model_callback_internal()
static void cia_model_callback_internal (GtkWidget * widget, int model) static
Handler for the radiogroup callbacks for the CIA models.
Triggers the callback set with cia_model_widget_set_callback()
Parameters
[in] widget CIA radiogroup widget triggering the event
[in] model CIA model ID
Referenced by create_cia_widget().
cia_model_widget_create()
GtkWidget * cia_model_widget_create (int count)
Create CIA model(s) widget.
Creates a CIA model widget for either one or two CIA's.
Parameters
[in] count number of CIA's (1 or 2)
Returns
GtkGrid
Referenced by create_c128_layout(), create_c64_layout(), create_cbm5x0_layout(), and create_cbm6x0_layout().
cia_model_widget_set_callback()
void cia_model_widget_set_callback (GtkWidget * widget, void(*)(int cia_num, int cia_model) func)
Set extra callback for changes in the widget.
The callback func get called with two arguments: CIA number (1 or 2) and CIA model ID.
Parameters
[in,out] widget CIA model widget
[in] func callback
Referenced by create_c128_layout(), create_c64_layout(), create_cbm5x0_layout(), and create_cbm6x0_layout().
cia_model_widget_sync()
void cia_model_widget_sync (GtkWidget * widget)
Synchronize CIA model widgets with their current resources.
Only updates the widget if the widget is out of sync with the resources, this will avoid having the machine model widget and the CIA model widget triggering each others' event handlers.
Parameters
[in,out] widget CIA model widget
Referenced by machine_model_handler_c128(), and machine_model_handler_c64().
create_cia_widget()
static GtkWidget * create_cia_widget (int num) static
Create a widget for CIA num.
Parameters
[in] num CIA number (1 or 2)
Returns
GtkGrid
Referenced by cia_model_widget_create().
on_destroy()
static void on_destroy (GtkWidget * self, gpointer data) static
Properly clear references.
Parameters
[in] self CIA widget (unused)
[in] data extra event data (unused)
Referenced by cia_model_widget_create().
Variable Documentation
cia1_group
GtkWidget* cia1_group static
Reference to the radiobutton group used for CIA1.
Referenced by cia_model_callback_internal(), cia_model_widget_sync(), create_cia_widget(), and on_destroy().
cia2_group
GtkWidget* cia2_group static
Reference to the radiobutton group used for CIA2.
Referenced by cia_model_widget_sync(), create_cia_widget(), and on_destroy().
cia_model_callback
void(* cia_model_callback) (int, int) (int , int) static
Optional extra callback for widget changes.
Referenced by cia_model_callback_internal(), cia_model_widget_set_callback(), and on_destroy().
cia_models
const vice_gtk3_radiogroup_entry_t cia_models[] static
Initial value:
= {
    { "6526 (old)",  0    },
    { "8521 (new)",  1   },
    { NULL,         -1 }
}
List of CIA models.
Referenced by create_cia_widget().