vsid: monitor/mon_util.c File Reference
mon_util.c File Reference
#include "vice.h"
#include <assert.h>
#include <ctype.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "ui.h"
#include "archdep.h"
#include "charset.h"
#include "console.h"
#include "lib.h"
#include "mem.h"
#include "mon_disassemble.h"
#include "mon_util.h"
#include "monitor.h"
#include "monitor_network.h"
#include "monitor_binary.h"
#include "vicesocket.h"
#include "types.h"
#include "uimon.h"
#include "vsyncapi.h"
Functions
int mon_log_file_open (const char *name)
void mon_log_file_close (void)
static int mon_log_file_out (const char *buffer)
static void mon_buffer_alloc (void)
static int mon_buffer_flush (void)
static void stringcopy_n (char *dest, const char *src, unsigned int len)
static void mon_buffer_add (const char *buffer, unsigned int bufferlen)
void mon_event_opened (void)
Notify interested interfaces that the monitor opened.
void mon_event_closed (void)
Notify interested interfaces that the monitor closed.
static int mon_out_buffered (const char *buffer, int mode, int maxlen)
int mon_out (const char *format,...)
int mon_petscii_out (int maxlen, const char *format,...)
int mon_petscii_upper_out (int maxlen, const char *format,...)
int mon_scrcode_out (int maxlen, const char *format,...)
int mon_scrcode_upper_out (int maxlen, const char *format,...)
char * mon_disassemble_with_label (MEMSPACE memspace, uint16_t loc, int hex, unsigned *opc_size_p, unsigned *label_p)
char * mon_dump_with_label (MEMSPACE memspace, uint16_t loc, int hex, unsigned *label_p)
void mon_set_command (console_t *cons_log, char *command, void(*pAfter)(void))
char * uimon_in (const char *prompt)
Variables
static char * bigbuffer = NULL
static const unsigned int bigbuffersize = 10000
static unsigned int bigbufferwrite = 0
static unsigned int bigbuffermode = 0
static FILE * mon_log_file = NULL
static char * pchCommandLine = NULL
Function Documentation
mon_buffer_add()
static void mon_buffer_add (const char * buffer, unsigned int bufferlen) static
Referenced by mon_out_buffered().
mon_buffer_alloc()
static void mon_buffer_alloc (void) static
Referenced by mon_out_buffered().
mon_buffer_flush()
static int mon_buffer_flush (void) static
Referenced by mon_buffer_add(), mon_out_buffered(), and uimon_in().
mon_disassemble_with_label()
char * mon_disassemble_with_label (MEMSPACE memspace, uint16_t loc, int hex, unsigned * opc_size_p, unsigned * label_p)
mon_dump_with_label()
char * mon_dump_with_label (MEMSPACE memspace, uint16_t loc, int hex, unsigned * label_p)
mon_event_closed()
void mon_event_closed (void)
Notify interested interfaces that the monitor closed.
Referenced by monitor_close().
mon_event_opened()
void mon_event_opened (void)
Notify interested interfaces that the monitor opened.
Referenced by monitor_open().
mon_log_file_close()
void mon_log_file_close (void)
Referenced by mon_log_file_open(), monitor_shutdown(), set_monitor_log_enabled(), and set_monitor_log_filename().
mon_log_file_open()
int mon_log_file_open (const char * name)
< append mode
Referenced by set_monitor_log_enabled(), and set_monitor_log_filename().
mon_log_file_out()
static int mon_log_file_out (const char * buffer) static
Referenced by mon_out(), mon_petscii_out(), mon_petscii_upper_out(), mon_scrcode_out(), mon_scrcode_upper_out(), and uimon_in().
mon_out()
int mon_out (const char * format, ...)
Referenced by acia_dump(), ata_register_dump(), c64_256k_dump(), check_drive_emu_level_ok(), ciacore_dump(), export_dump(), i8255a_dump(), init_profiling_data(), make_offset_mode(), mc6821core_dump(), mon_add_name_to_symbol_table(), mon_assemble_instr(), mon_attach(), mon_autostart(), mon_backtrace(), mon_bank(), mon_banknum_from_bank(), mon_banknum_validate(), mon_breakpoint_check_checkpoint(), mon_breakpoint_delete_checkpoint(), mon_breakpoint_print_checkpoints(), mon_breakpoint_set_checkpoint_command(), mon_breakpoint_set_checkpoint_condition(), mon_breakpoint_set_ignore_count(), mon_breakpoint_switch_checkpoint(), mon_cart_freeze(), mon_change_dir(), mon_detach(), mon_disassemble_instr(), mon_disassemble_oneline(), mon_disassemble_to_string_internal(), mon_disassemble_with_regdump(), mon_display_io_regs(), mon_display_screen(), mon_drive_block_cmd(), mon_drive_execute_disk_cmd(), mon_drive_list(), mon_end_recording(), mon_export(), mon_file_load(), mon_file_save(), mon_file_verify(), mon_instructions_next(), mon_instructions_step(), mon_joyport_set_output(), mon_maincpu_trace(), mon_make_dir(), mon_memmap_stub(), mon_memory_compare(), mon_memory_display(), mon_memory_display_data(), mon_memory_fill(), mon_memory_hunt(), mon_memory_move(), mon_out_wordwrap(), mon_playback_commands(), mon_print_bin(), mon_print_conditional(), mon_print_convert(), mon_print_symbol_table(), mon_profile(), mon_profile_action(), mon_profile_clear(), mon_profile_disass(), mon_profile_disass_context(), mon_profile_flat(), mon_profile_func(), mon_profile_graph(), mon_record_commands(), mon_register_print(), mon_remove_dir(), mon_remove_name_from_symbol_table(), mon_resource_get(), mon_resource_set(), mon_save_symbols(), mon_screenshot_save(), mon_set_command(), mon_show_dir(), mon_show_pwd(), mon_stack_down(), mon_stack_up(), mon_stopwatch_reset(), mon_stopwatch_show(), mon_tape_ctrl(), mon_tape_offs(), mon_userport_set_output(), monitor_change_device(), monitor_cpu_type_set(), monitor_open(), monitor_print_cpu_types_supported(), monitor_process(), mypia_dump(), pc8477d_dump(), plus256k_dump(), plus60k_dump(), print_all_contexts(), print_checkpoint_info(), print_context_graph(), print_context_id(), print_context_line(), print_context_name(), print_cycle_time(), print_disass_context(), print_dst(), print_function_line(), print_help_details(), print_help_topics(), print_hex(), print_octal(), print_src(), riotcore_dump(), sound_dump(), t6721_dump(), tpicore_dump(), viacore_dump(), vicii_dump(), and wd1770d_dump().
mon_out_buffered()
static int mon_out_buffered (const char * buffer, int mode, int maxlen) static
Todo:
FIXME: convert to mode
Referenced by mon_out(), mon_petscii_out(), mon_petscii_upper_out(), mon_scrcode_out(), and mon_scrcode_upper_out().
mon_petscii_out()
int mon_petscii_out (int maxlen, const char * format, ...)
Referenced by mon_memory_display(), and monitor_open().
mon_petscii_upper_out()
int mon_petscii_upper_out (int maxlen, const char * format, ...)
Referenced by mon_drive_list(), and monitor_open().
mon_scrcode_out()
int mon_scrcode_out (int maxlen, const char * format, ...)
Referenced by mon_display_screen(), mon_memory_display(), and monitor_open().
mon_scrcode_upper_out()
int mon_scrcode_upper_out (int maxlen, const char * format, ...)
Referenced by monitor_open().
mon_set_command()
void mon_set_command (console_t * cons_log, char * command, void(*)(void) pAfter)
Referenced by uimon_in().
stringcopy_n()
static void stringcopy_n (char * dest, const char * src, unsigned int len) static
Referenced by mon_buffer_add().
uimon_in()
char * uimon_in (const char * prompt)
Referenced by monitor_startup().
Variable Documentation
bigbuffer
char* bigbuffer = NULL static
Referenced by mon_buffer_add(), mon_buffer_alloc(), and mon_buffer_flush().
bigbuffermode
unsigned int bigbuffermode = 0 static
Referenced by mon_buffer_flush(), and mon_out_buffered().
bigbuffersize
const unsigned int bigbuffersize = 10000 static
Referenced by mon_buffer_add(), and mon_buffer_alloc().
bigbufferwrite
unsigned int bigbufferwrite = 0 static
Referenced by mon_buffer_add(), and mon_buffer_flush().
mon_log_file
FILE* mon_log_file = NULL static
Referenced by mon_log_file_close(), mon_log_file_open(), and mon_log_file_out().
pchCommandLine
char* pchCommandLine = NULL static
Referenced by mon_set_command(), and uimon_in().