vsid: c64/c64iec.c File Reference
c64iec.c File Reference
#include "vice.h"
#include "c64.h"
#include "c64cart.h"
#include "c64iec.h"
#include "cartridge.h"
#include "drive.h"
#include "iecbus.h"
#include "iecdrive.h"
#include "maincpu.h"
#include "types.h"
Macros
#define IEC_DEBUG_PORTS()
Functions
void iec_update_cpu_bus (uint8_t data)
void iec_update_ports (void)
void iec_update_ports_embedded (void)
void iec_drive_write (uint8_t data, unsigned int dnr)
uint8_t iec_drive_read (unsigned int dnr)
iecbus_t * iecbus_drive_port (void)
int iec_available_busses (void)
This function is called from ui_update_menus()
void c64iec_init (void)
void c64iec_enable (int val)
int c64iec_get_active_state (void)
void plus4tcbm_update_pa (uint8_t byte, unsigned int dnr)
void plus4tcbm_update_pb (uint8_t byte, unsigned int dnr)
void plus4tcbm_update_pc (uint8_t byte, unsigned int dnr)
Variables
int c64iec_active = 1
uint8_t plus4tcbm_outputa [2]
KLUDGES: dummy to satisfy linker, unused.
uint8_t plus4tcbm_outputb [2]
uint8_t plus4tcbm_outputc [2]
Macro Definition Documentation
IEC_DEBUG_PORTS
#define IEC_DEBUG_PORTS ()
Function Documentation
c64iec_enable()
void c64iec_enable (int val)
Referenced by c64model_set().
c64iec_get_active_state()
int c64iec_get_active_state (void)
c64iec_init()
void c64iec_init (void)
Referenced by machine_specific_init().
iec_available_busses()
int iec_available_busses (void)
This function is called from ui_update_menus()
< c64tpi.c
< ieeeflash64.c
< serial IEC bus
< parallel IEEE bus
< serial IEC bus
iec_drive_read()
uint8_t iec_drive_read (unsigned int dnr)
Referenced by read_ciapb(), read_pra(), read_prb(), and read_prb10().
iec_drive_write()
void iec_drive_write (uint8_t data, unsigned int dnr)
Referenced by store_ciapb(), store_pra(), store_prb(), store_prb10(), undump_pra(), undump_prb(), and undump_prb10().
iec_update_cpu_bus()
void iec_update_cpu_bus (uint8_t data)
Referenced by iecbus_cpu_undump(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), and iecbus_cpu_write_conf3().
iec_update_ports()
void iec_update_ports (void)
Referenced by c64iec_init(), iec_drive_write(), iec_update_ports_embedded(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), and iecbus_cpu_write_conf3().
iec_update_ports_embedded()
void iec_update_ports_embedded (void)
Referenced by drive_snapshot_read_module().
iecbus_drive_port()
iecbus_t * iecbus_drive_port (void)
Referenced by cia1581_setup_context(), cmdhd_setup_context(), iec_drive_port_default(), via1d1541_setup_context(), and via4000_setup_context().
plus4tcbm_update_pa()
void plus4tcbm_update_pa (uint8_t byte, unsigned int dnr)
plus4tcbm_update_pb()
void plus4tcbm_update_pb (uint8_t byte, unsigned int dnr)
plus4tcbm_update_pc()
void plus4tcbm_update_pc (uint8_t byte, unsigned int dnr)
Variable Documentation
c64iec_active
int c64iec_active = 1
Referenced by c64iec_enable(), c64iec_get_active_state(), read_ciapa(), store_ciapa(), store_sdr(), and undump_ciapa().
plus4tcbm_outputa
uint8_t plus4tcbm_outputa[2]
KLUDGES: dummy to satisfy linker, unused.
plus4tcbm_outputb
uint8_t plus4tcbm_outputb[2]
plus4tcbm_outputc
uint8_t plus4tcbm_outputc[2]