vsid: crc32.c File Reference
crc32.c File Reference
CRC32 checksum implementation.
#include "vice.h"
#include <stdio.h>
#include "archdep.h"
#include "crc32.h"
#include "lib.h"
#include "util.h"
Macros
#define CRC32_POLY 0xedb88320
CRC32 polynomial.
Functions
uint32_t crc32_buf (const char *buffer, unsigned int len)
Calculate CRC32 checksum of len bytes of buffer.
uint32_t crc32_file (const char *filename)
Calculate CRC32 checksum of file filename.
void crc32_to_le (uint8_t *dest, uint32_t crc)
Turn crc into a little endian value.
uint32_t crc32_from_le (const uint8_t *src)
Read 32-bit unsigned from little endian data.
Variables
static uint32_t crc32_table [256]
Table of constants.
static int crc32_is_initialized = 0
Flag indicating if crc32_table has been initialized.
Detailed Description
CRC32 checksum implementation.
Author
Spiro Trikaliotis Spiro.nosp@m..Tri.nosp@m.kalio.nosp@m.tis@.nosp@m.gmx.d.nosp@m.e
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
CRC32_POLY
#define CRC32_POLY 0xedb88320
CRC32 polynomial.
Function Documentation
crc32_buf()
uint32_t crc32_buf (const char * buffer, unsigned int len)
Calculate CRC32 checksum of len bytes of buffer.
Parameters
[in] buffer buffer
[in] len length of buffer
Returns
CRC32 checksum
Todo:
Perhaps change buffer into uint8_t and len into size_t?
Referenced by cmd_crc32_flash(), and crc32_file().
crc32_file()
uint32_t crc32_file (const char * filename)
Calculate CRC32 checksum of file filename.
Parameters
[in] filename path to file
Returns
CRC32 checksum
< read mode (binary)
Referenced by event_playback_attach_image(), and event_record_attach_in_list().
crc32_from_le()
uint32_t crc32_from_le (const uint8_t * src)
Read 32-bit unsigned from little endian data.
Parameters
[in] src data (4 bytes representing a 32-bit little endian value)
Returns
32-bit architecture-dependent unsigned int
Referenced by event_playback_attach_image().
crc32_to_le()
void crc32_to_le (uint8_t * dest, uint32_t crc)
Turn crc into a little endian value.
Parameters
[in] crc 32-bit architecture-independent unsigned int
[out] dest destination of little endian value (4 bytes)
Referenced by event_playback_attach_image(), and event_record_attach_in_list().
Variable Documentation
crc32_is_initialized
int crc32_is_initialized = 0 static
Flag indicating if crc32_table has been initialized.
Referenced by crc32_buf().
crc32_table
uint32_t crc32_table[256] static
Table of constants.
Referenced by crc32_buf().