vsid: arch/gtk3/uismartattach.c File Reference
uismartattach.c File Reference
GTK3 smart-attach dialog.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "attach.h"
#include "autostart.h"
#include "cartridge.h"
#include "drive.h"
#include "tape.h"
#include "debug_gtk3.h"
#include "contentpreviewwidget.h"
#include "diskcontents.h"
#include "diskimage.h"
#include "driveimage.h"
#include "tapecontents.h"
#include "machine.h"
#include "mainlock.h"
#include "resources.h"
#include "ui.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uimachinewindow.h"
#include "lastdir.h"
#include "initcmdline.h"
#include "log.h"
#include "tapecart.h"
#include "tapeport.h"
#include "uismartattach.h"
Functions
static void do_autostart (GtkWidget *dialog, int index, int autostart)
Trigger autostart.
static int try_attach_disk (int unit_number, int drive_number, char *filename_locale)
try attach a disk image, change drive type if needed
static int try_attach_tapecart (char *filename)
try attach a Tapecart image, change tape port device if needed
static void do_smart_attach (GtkWidget *widget, gpointer data)
Do smart attach.
static void on_selection_changed (GtkFileChooser *chooser, gpointer data)
Handler for 'selection-changed' event of the preview widget.
static void on_update_preview (GtkFileChooser *chooser, gpointer data)
Handler for the "update-preview" event.
static void on_hidden_toggled (GtkWidget *widget, gpointer user_data)
Handler for the 'toggled' event of the 'show hidden files' checkbox.
static void on_readonly_toggled (GtkWidget *widget, gpointer user_data)
Handler for the 'toggled' event of the 'attach read-only' checkbox.
static void on_response (GtkWidget *widget, gint response_id, gpointer user_data)
Handler for 'response' event of the dialog.
static GtkWidget * create_extra_widget (GtkWidget *parent)
Create the 'extra' widget.
static image_contents_t * read_contents_wrapper (const char *path)
Wrapper around disk/tape contents readers.
static void on_destroy (GtkWidget *self, gpointer data)
static GtkWidget * create_smart_attach_dialog (void)
Create the smart-attach dialog.
void ui_smart_attach_dialog_show (void)
Callback for the File menu's "smart-attach" item.
void ui_smart_attach_shutdown (void)
Clean up last used directory string.
Variables
static ui_file_filter_t filters []
File type filters for the dialog.
static GtkWidget * preview_widget = NULL
Preview widget reference.
static gchar * last_dir = NULL
Last directory used.
static gchar * last_file = NULL
Last file selected.
static GtkWidget * autostart_button
Reference to the custom 'Autostart' button.
Detailed Description
GTK3 smart-attach dialog.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_extra_widget()
static GtkWidget * create_extra_widget (GtkWidget * parent) static
Create the 'extra' widget.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
Referenced by create_smart_attach_dialog().
create_smart_attach_dialog()
static GtkWidget * create_smart_attach_dialog (void) static
Create the smart-attach dialog.
Returns
GtkFileChooserDialog
Todo:
Figure out how to only enable the 'Autostart' button when an actual file/image has been selected. And when I do, make sure it's somehow reusable for other 'open file' dialogs'.
Referenced by ui_smart_attach_dialog_show().
do_autostart()
static void do_autostart (GtkWidget * dialog, int index, int autostart) static
Trigger autostart.
Parameters
[in] dialog dialog
[in] index file index in the directory preview
[in] autostart flag: 0: just load, 1: autostart
Referenced by on_response().
do_smart_attach()
static void do_smart_attach (GtkWidget * widget, gpointer data) static
Do smart attach.
Parameters
[in] widget dialog
[in] data file index in the directory preview
Referenced by on_response().
on_destroy()
static void on_destroy (GtkWidget * self, gpointer data) static
Referenced by create_smart_attach_dialog().
on_hidden_toggled()
static void on_hidden_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the 'toggled' event of the 'show hidden files' checkbox.
Parameters
[in] widget checkbox triggering the event
[in] user_data data for the event (the dialog)
Referenced by create_extra_widget().
on_readonly_toggled()
static void on_readonly_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the 'toggled' event of the 'attach read-only' checkbox.
Parameters
[in] widget checkbox triggering the event
[in] user_data data for the event (the dialog)
Referenced by create_extra_widget().
on_response()
static void on_response (GtkWidget * widget, gint response_id, gpointer user_data) static
Handler for 'response' event of the dialog.
This handler is called when the user clicks a button in the dialog.
Parameters
[in] widget the dialog
[in] response_id response ID
[in] user_data unit number
!
Todo:
proper (error) messages
Referenced by create_smart_attach_dialog().
on_selection_changed()
static void on_selection_changed (GtkFileChooser * chooser, gpointer data) static
Handler for 'selection-changed' event of the preview widget.
Checks if a proper selection was made and activates the 'Autostart' button if so, disabled it otherwise
Parameters
[in] chooser Parent dialog
[in] data Extra event data (unused)
Referenced by create_smart_attach_dialog().
on_update_preview()
static void on_update_preview (GtkFileChooser * chooser, gpointer data) static
Handler for the "update-preview" event.
Parameters
[in] chooser file chooser dialog
[in] data extra event data (unused)
Referenced by create_smart_attach_dialog().
read_contents_wrapper()
static image_contents_t * read_contents_wrapper (const char * path) static
Wrapper around disk/tape contents readers.
First treats path as disk image file and when that fails it falls back to treating path as a tape image, when that fails as well, it gives up.
Parameters
[in] path path to image file
Returns
image contents or NULL on failure
Referenced by create_smart_attach_dialog().
try_attach_disk()
static int try_attach_disk (int unit_number, int drive_number, char * filename_locale) static
try attach a disk image, change drive type if needed
Parameters
[in] unit_number
[in] drive_number
[in] filename_locale
Referenced by do_smart_attach().
try_attach_tapecart()
static int try_attach_tapecart (char * filename) static
try attach a Tapecart image, change tape port device if needed
Parameters
[in] filename
Referenced by do_smart_attach().
ui_smart_attach_dialog_show()
void ui_smart_attach_dialog_show (void)
Callback for the File menu's "smart-attach" item.
Creates the smart-dialog and runs it.
Parameters
[in] widget menu item triggering the callback
[in] user_data data for the event (unused)
Returns
TRUE
Referenced by smart_attach_action().
ui_smart_attach_shutdown()
void ui_smart_attach_shutdown (void)
Clean up last used directory string.
Referenced by ui_exit().
Variable Documentation
autostart_button
GtkWidget* autostart_button static
Reference to the custom 'Autostart' button.
Referenced by create_smart_attach_dialog(), and on_selection_changed().
filters
ui_file_filter_t filters[] static
Initial value:
= {
    { "All files",          file_chooser_pattern_all },
    { "Disk images",        file_chooser_pattern_disk },
    { "Tape images",        file_chooser_pattern_tape },
    { "Cartridge images",   file_chooser_pattern_cart },
    { "Program files",      file_chooser_pattern_program },
    { "Snapshot files",     file_chooser_pattern_snapshot },
    { "Archives files",     file_chooser_pattern_archive },
    { "Compressed files",   file_chooser_pattern_compressed },
    { NULL, NULL }
}
File type filters for the dialog.
Referenced by create_smart_attach_dialog().
last_dir
gchar* last_dir = NULL static
Last directory used.
When an image is attached, this is set to the directory of that file.
Since it's heap-allocated by Gtk3, it must be freed with a call to ui_smart_attach_shutdown() on emulator shutdown.
Referenced by create_smart_attach_dialog(), do_autostart(), do_smart_attach(), and ui_smart_attach_shutdown().
last_file
gchar* last_file = NULL static
Last file selected.
Referenced by create_smart_attach_dialog(), do_autostart(), do_smart_attach(), and ui_smart_attach_shutdown().
preview_widget
GtkWidget* preview_widget = NULL static
Preview widget reference.
Referenced by create_smart_attach_dialog(), on_response(), and on_update_preview().