x128: riot.h File Reference
riot.h File Reference
#include "types.h"
Data Structures
struct riot_context_s
Macros
#define RIOT_SIG_PA7 0
#define RIOT_SIG_FALL 0
#define RIOT_SIG_RISE 1
Typedefs
typedef struct riot_context_s riot_context_t
Functions
void riotcore_setup_context (riot_context_t *riot_context)
void riotcore_init (riot_context_t *riot_context, struct alarm_context_s *alarm_context, unsigned int number)
void riotcore_shutdown (struct riot_context_s *riot_context)
void riotcore_reset (riot_context_t *riot_context)
void riotcore_disable (riot_context_t *riot_context)
void riotcore_signal (riot_context_t *riot_context, int sig, int type)
void riotcore_store (riot_context_t *riot_context, uint16_t addr, uint8_t data)
uint8_t riotcore_read (riot_context_t *riot_context, uint16_t addr)
uint8_t riotcore_peek (riot_context_t *riot_context, uint16_t addr)
read from I/O without side effects
void riotcore_dump (riot_context_t *riot_context)
int riotcore_snapshot_write_module (struct riot_context_s *riot_context, struct snapshot_s *p)
int riotcore_snapshot_read_module (struct riot_context_s *riot_context, struct snapshot_s *p)
Macro Definition Documentation
RIOT_SIG_FALL
#define RIOT_SIG_FALL 0
RIOT_SIG_PA7
#define RIOT_SIG_PA7 0
RIOT_SIG_RISE
#define RIOT_SIG_RISE 1
Typedef Documentation
riot_context_t
typedef struct riot_context_s riot_context_t
Function Documentation
riotcore_disable()
void riotcore_disable (riot_context_t * riot_context)
Referenced by ieee_drive_reset().
riotcore_dump()
void riotcore_dump (riot_context_t * riot_context)
Referenced by drivemem_ioreg_list_get().
riotcore_init()
void riotcore_init (riot_context_t * riot_context, struct alarm_context_s * alarm_context, unsigned int number)
Referenced by riot1_init(), and riot2_init().
riotcore_peek()
uint8_t riotcore_peek (riot_context_t * riot_context, uint16_t addr)
read from I/O without side effects
Todo:
FIXME: check if this is working correctly
Referenced by riot1_peek(), and riot2_peek().
riotcore_read()
uint8_t riotcore_read (riot_context_t * riot_context, uint16_t addr)
Referenced by riot1_read(), and riot2_read().
riotcore_reset()
void riotcore_reset (riot_context_t * riot_context)
Referenced by ieee_drive_reset().
riotcore_setup_context()
void riotcore_setup_context (riot_context_t * riot_context)
Referenced by riot1_setup_context(), and riot2_setup_context().
riotcore_shutdown()
void riotcore_shutdown (struct riot_context_s * riot_context)
Referenced by ieee_drive_shutdown().
riotcore_signal()
void riotcore_signal (riot_context_t * riot_context, int sig, int type)
Referenced by riot2_set_atn().
riotcore_snapshot_read_module()
int riotcore_snapshot_read_module (struct riot_context_s * riot_context, struct snapshot_s * p)
Referenced by ieee_drive_snapshot_read().
riotcore_snapshot_write_module()
int riotcore_snapshot_write_module (struct riot_context_s * riot_context, struct snapshot_s * p)
Referenced by ieee_drive_snapshot_write().
riotcore_store()
void riotcore_store (riot_context_t * riot_context, uint16_t addr, uint8_t data)
Referenced by riot1_store(), riot2_store(), and riotcore_store().