x128: arch/gtk3/uicart.c File Reference
uicart.c File Reference
Widget to attach carts.
#include "vice.h"
#include <gtk/gtk.h>
#include <string.h>
#include "machine.h"
#include "resources.h"
#include "debug_gtk3.h"
#include "basewidgets.h"
#include "widgethelpers.h"
#include "basedialogs.h"
#include "filechooserhelpers.h"
#include "lastdir.h"
#include "log.h"
#include "openfiledialog.h"
#include "savefiledialog.h"
#include "cartridge.h"
#include "vsync.h"
#include "ui.h"
#include "uiactions.h"
#include "uimachinewindow.h"
#include "crtpreviewwidget.h"
#include "uicart.h"
Data Structures
struct cart_type_list_s
Simple (text,id) data structure for the cart type model.
Typedefs
typedef enum ui_cart_type_e ui_cart_type_t
Enum with various cart types, independent from cartridge.h.
typedef struct cart_type_list_s cart_type_list_t
Simple (text,id) data structure for the cart type model.
Enumerations
enum ui_cart_type_e {
UICART_C64_SMART = 0 ,
UICART_C64_GENERIC ,
UICART_C64_FREEZER ,
UICART_C64_GAME ,
UICART_C64_UTIL ,
UICART_C128_FUNCROM ,
UICART_VIC20_SMART ,
UICART_VIC20_GENERIC ,
UICART_VIC20_FREEZER ,
UICART_VIC20_GAME ,
UICART_VIC20_UTIL ,
UICART_PLUS4_SMART ,
UICART_PLUS4_GENERIC ,
UICART_PLUS4_FREEZER ,
UICART_PLUS4_GAME ,
UICART_PLUS4_UTIL ,
UICART_CBM2_SMART ,
UICART_CBM2_GENERIC ,
UICART_CBM2_FREEZER ,
UICART_CBM2_GAME ,
UICART_CBM2_UTIL
}
Enum with various cart types, independent from cartridge.h.
enum {
UICART_PATTERN_CRT = 0 ,
UICART_PATTERN_BIN_PRG ,
UICART_PATTERN_ALL
}
Indici of filename patterns.
Functions
static GtkListStore * create_cart_id_model (unsigned int flags)
forward declarations of functions
static int get_cart_type (void)
Get the ID of the model for the 'cart type' combo box.
static int get_cart_id (void)
Get the ID of the model for the 'cart ID' combo box.
static int attach_cart_image (int type, int id, const char *path)
Cart attach handler.
static void on_destroy (GtkWidget *dialog, gpointer data)
Handler for the 'destroy' event of the dialog.
static void on_response (GtkWidget *dialog, gint response_id, gpointer data)
Handler for the "response" event of the dialog.
static void set_pattern (int pattern)
Set the file filter pattern for the dialog.
static void on_cart_type_changed (GtkComboBox *combo, gpointer data)
Handler for the "changed" event of the cart type combo box.
static GtkListStore * create_cart_type_model (void)
Create model for the 'cart type' combo box.
static GtkWidget * create_cart_type_combo_box (void)
Create combo box with main cartridge types.
static GtkWidget * create_cart_id_combo_box (unsigned int mask)
Create combo box with cartridges with adhere to mask.
static GtkWidget * create_extra_widget (gboolean set_default)
Create the 'extra' widget for the dialog.
static void update_preview (GtkFileChooser *file_chooser, gpointer data)
Update the 'preview' widget for the dialog.
static GtkWidget * cart_dialog_internal (gboolean set_as_default, void(*callback)(void))
Create attach dialog.
void ui_cart_show_dialog (void)
Pop up the cart-attach dialog.
void ui_cart_default_attach (GtkWidget *widget, void(*callback)(void))
Attach dialog for the settings->default cart page.
void ui_cart_shutdown (void)
Clean up the last directory string.
Variables
static const cart_type_list_t c64_cart_types []
Available C64 cart types.
static const cart_type_list_t c128_cart_types []
Available C128 cart types.
static const cart_type_list_t vic20_cart_types []
List of VIC-20 'main' cart types.
static const cart_type_list_t plus4_cart_types []
List of Plus4/C16/C116 cart types.
static const cart_type_list_t cbm2_cart_types []
List of CBM-II cart types.
static const char * pattern_crt [] = { "*.crt", NULL }
File filter pattern for CRT images.
static const char * pattern_bin_prg [] = { "*.bin", "*.prg", NULL }
File filter pattern for raw images.
static ui_file_filter_t filters []
File type filters for the dialog.
static gchar * last_dir = NULL
Last used directory.
static gchar * last_file = NULL
Last used filename.
static GtkWidget * cart_dialog = NULL
References to widgets used in various event handlers.
static GtkWidget * cart_type_widget = NULL
Reference to the cart dialog.
static GtkWidget * cart_id_widget = NULL
Reference to the cart-id widget.
static GtkWidget * cart_preview_widget = NULL
Reference to the cart content 'preview' widget.
static GtkWidget * cart_set_default_widget = NULL
Reference to the cart-set-default widget.
static GtkWidget * cart_id_label = NULL
Reference to the cart ID widget.
GtkFileFilter * flt_crt = NULL
Reference to the dialog file filter showing only .crt images.
static GtkFileFilter * flt_bin_prg = NULL
Reference to the dialog file filter showing only .bin images.
static GtkFileFilter * flt_all = NULL
Reference to the dialog file filter showing all files.
static void(* extra_attach_callback)(void) = NULL
Optional extra callback.
Detailed Description
Widget to attach carts.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Typedef Documentation
cart_type_list_t
typedef struct cart_type_list_s cart_type_list_t
Simple (text,id) data structure for the cart type model.
ui_cart_type_t
typedef enum ui_cart_type_e ui_cart_type_t
Enum with various cart types, independent from cartridge.h.
The define's in cartridge.h don't provide the values I need, so this will have to do.
Enumeration Type Documentation
anonymous enum
anonymous enum
Indici of filename patterns.
Enumerator
UICART_PATTERN_CRT
UICART_PATTERN_BIN_PRG
UICART_PATTERN_ALL
ui_cart_type_e
enum ui_cart_type_e
Enum with various cart types, independent from cartridge.h.
The define's in cartridge.h don't provide the values I need, so this will have to do.
Enumerator
UICART_C64_SMART
UICART_C64_GENERIC
UICART_C64_FREEZER
UICART_C64_GAME
UICART_C64_UTIL
UICART_C128_FUNCROM
UICART_VIC20_SMART
UICART_VIC20_GENERIC
UICART_VIC20_FREEZER
UICART_VIC20_GAME
UICART_VIC20_UTIL
UICART_PLUS4_SMART
UICART_PLUS4_GENERIC
UICART_PLUS4_FREEZER
UICART_PLUS4_GAME
UICART_PLUS4_UTIL
UICART_CBM2_SMART
UICART_CBM2_GENERIC
UICART_CBM2_FREEZER
UICART_CBM2_GAME
UICART_CBM2_UTIL
Function Documentation
attach_cart_image()
static int attach_cart_image (int type, int id, const char * path) static
Cart attach handler.
Parameters
[in] type cartridge type
[in] id cartridge ID
[in] path path to cartrige image
Returns
bool
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by on_response().
cart_dialog_internal()
static GtkWidget * cart_dialog_internal (gboolean set_as_default, void(*)(void) callback) static
Create attach dialog.
Parameters
[in] set_as_default initial state of the 'set as default' checkbox
[in] callback extra callback when attach succeeds
Returns
GtkDialog
Referenced by ui_cart_default_attach(), and ui_cart_show_dialog().
create_cart_id_combo_box()
static GtkWidget * create_cart_id_combo_box (unsigned int mask) static
Create combo box with cartridges with adhere to mask.
Parameters
[in] mask bitmask to filter cartridges
Returns
GtkComboBox
Note
Only for x64/x64sc/xscp64/x128/plus4
Referenced by create_extra_widget().
create_cart_id_model()
static GtkListStore * create_cart_id_model (unsigned int flags) static
forward declarations of functions
Create a list of cartridges, filtered with flags.
Only valid for c64/c128/scpu
Parameters
[in] flags flags determining what cart types to use
Returns
Three-column list store (name, crtid, flags)
Referenced by create_cart_id_combo_box(), and on_cart_type_changed().
create_cart_type_combo_box()
static GtkWidget * create_cart_type_combo_box (void) static
Create combo box with main cartridge types.
Returns
GtkComboBox
Referenced by create_extra_widget().
create_cart_type_model()
static GtkListStore * create_cart_type_model (void) static
Create model for the 'cart type' combo box.
This depends on the machine_class, so for some machines, this may return an empty (useless) model
Returns
model
Referenced by create_cart_type_combo_box().
create_extra_widget()
static GtkWidget * create_extra_widget (gboolean set_default) static
Create the 'extra' widget for the dialog.
Parameters
[in] set_default initial state of the 'set as default' checkbox
Returns
GtkGrid
Referenced by cart_dialog_internal().
get_cart_id()
static int get_cart_id (void) static
Get the ID of the model for the 'cart ID' combo box.
Returns
ID or -1 on error
Referenced by on_response().
get_cart_type()
static int get_cart_type (void) static
Get the ID of the model for the 'cart type' combo box.
Returns
ID or -1 on error
Referenced by on_cart_type_changed(), and on_response().
on_cart_type_changed()
static void on_cart_type_changed (GtkComboBox * combo, gpointer data) static
Handler for the "changed" event of the cart type combo box.
Parameters
[in] combo cart type combo
[in] data extra event data (unused)
Referenced by create_cart_type_combo_box().
on_destroy()
static void on_destroy (GtkWidget * dialog, gpointer data) static
Handler for the 'destroy' event of the dialog.
Parameters
[in] dialog dialog
[in] data extra event data (unused)
Referenced by cart_dialog_internal().
on_response()
static void on_response (GtkWidget * dialog, gint response_id, gpointer data) static
Handler for the "response" event of the dialog.
Parameters
[in] dialog dialog
[in] response_id response ID
[in] data extra event data (unused)
Todo:
FIXME: hack to avoid the 'normal' dialog (via the menu) triggering the extra callback meant for the default cart setting page.
Didn't I fix this? (cpx-2021-03-14)
Referenced by cart_dialog_internal().
set_pattern()
static void set_pattern (int pattern) static
Set the file filter pattern for the dialog.
Parameters
[in] pattern UICART_PATTERN_* enum value
Referenced by on_cart_type_changed().
ui_cart_default_attach()
void ui_cart_default_attach (GtkWidget * widget, void(*)(void) callback)
Attach dialog for the settings->default cart page.
Parameters
[in] widget parent widget (unused)
[in] callback function to call on succesfull attach
Referenced by on_attach_clicked().
ui_cart_show_dialog()
void ui_cart_show_dialog (void)
Pop up the cart-attach dialog.
Referenced by cart_attach_action().
ui_cart_shutdown()
void ui_cart_shutdown (void)
Clean up the last directory string.
Referenced by ui_exit().
update_preview()
static void update_preview (GtkFileChooser * file_chooser, gpointer data) static
Update the 'preview' widget for the dialog.
Parameters
[in,out] file_chooser GtkFileChooser instance
[in] data extra event data (unused)
Returns
GtkGrid
Referenced by cart_dialog_internal().
Variable Documentation
c128_cart_types
const cart_type_list_t c128_cart_types[] static
Initial value:
= {
    { "Smart-attach",   UICART_C64_SMART },
    { "Generic",        UICART_C64_GENERIC },
    { "Freezer",        UICART_C64_FREEZER },
    { "Games",          UICART_C64_GAME },
    { "Utilities",      UICART_C64_UTIL },
    { NULL,             -1 }
}
Available C128 cart types.
When the 'type' is freezer, games or utilities, a second combo box will be populated with cartridges which fall in that category.
Referenced by create_cart_type_model().
c64_cart_types
const cart_type_list_t c64_cart_types[] static
Initial value:
= {
    { "Smart-attach",   UICART_C64_SMART },
    { "Generic",        UICART_C64_GENERIC },
    { "Freezer",        UICART_C64_FREEZER },
    { "Games",          UICART_C64_GAME },
    { "Utilities",      UICART_C64_UTIL },
    { NULL,             -1 }
}
Available C64 cart types.
When the 'type' is freezer, games or utilities, a second combo box will be populated with cartridges which fall in that category.
Referenced by create_cart_type_model().
cart_dialog
GtkWidget* cart_dialog = NULL static
References to widgets used in various event handlers.
Reference to the cart dialog
Referenced by cart_dialog_internal(), and set_pattern().
cart_id_label
GtkWidget* cart_id_label = NULL static
Reference to the cart ID widget.
Referenced by cart_dialog_internal(), create_extra_widget(), and on_cart_type_changed().
cart_id_widget
GtkWidget* cart_id_widget = NULL static
Reference to the cart-id widget.
Referenced by cart_dialog_internal(), create_extra_widget(), get_cart_id(), and on_cart_type_changed().
cart_preview_widget
GtkWidget* cart_preview_widget = NULL static
Reference to the cart content 'preview' widget.
This widget shows the contents of the cart selected in the dialog.
Referenced by cart_dialog_internal().
cart_set_default_widget
GtkWidget* cart_set_default_widget = NULL static
Reference to the cart-set-default widget.
Referenced by attach_cart_image(), and create_extra_widget().
cart_type_widget
GtkWidget* cart_type_widget = NULL static
Reference to the cart dialog.
Referenced by create_extra_widget(), and get_cart_type().
cbm2_cart_types
const cart_type_list_t cbm2_cart_types[] static
Initial value:
= {
    { "Smart-attach",               UICART_CBM2_SMART },
    { "Generic",                    UICART_CBM2_GENERIC },
    { "Freezer",                    UICART_CBM2_FREEZER },
    { "Games",                      UICART_CBM2_GAME },
    { "Utilities",                  UICART_CBM2_UTIL },
    { NULL, -1 }
}
List of CBM-II cart types.
Referenced by create_cart_type_model().
extra_attach_callback
void(* extra_attach_callback) (void) (void) = NULL static
Optional extra callback.
This function is triggered when a cartidge is attached.
Referenced by cart_dialog_internal(), and on_response().
filters
ui_file_filter_t filters[] static
Initial value:
= {
    { "CRT images", pattern_crt },
    { "Raw images", pattern_bin_prg },
    { "All files", file_chooser_pattern_all },
    { NULL, NULL }
}
File type filters for the dialog.
Todo:
FIXME: for vic20 we should add .vrt(?), for plus4 .prt(?)
Referenced by cart_dialog_internal(), and load_snapshot_trap_impl().
flt_all
GtkFileFilter* flt_all = NULL static
Reference to the dialog file filter showing all files.
Referenced by cart_dialog_internal(), and set_pattern().
flt_bin_prg
GtkFileFilter* flt_bin_prg = NULL static
Reference to the dialog file filter showing only .bin images.
Reference to the dialog file filter showing .bin + .prg images
Referenced by cart_dialog_internal(), and set_pattern().
flt_crt
GtkFileFilter* flt_crt = NULL
Reference to the dialog file filter showing only .crt images.
Referenced by cart_dialog_internal(), and set_pattern().
last_dir
gchar* last_dir = NULL static
Last used directory.
Referenced by cart_dialog_internal(), on_response(), and ui_cart_shutdown().
last_file
gchar* last_file = NULL static
Last used filename.
Referenced by cart_dialog_internal(), on_response(), and ui_cart_shutdown().
pattern_bin_prg
const char* pattern_bin_prg[] = { "*.bin", "*.prg", NULL } static
File filter pattern for raw images.
File filter pattern for raw images
pattern_crt
const char* pattern_crt[] = { "*.crt", NULL } static
File filter pattern for CRT images.
plus4_cart_types
const cart_type_list_t plus4_cart_types[] static
Initial value:
= {
    { "Smart-attach",               UICART_PLUS4_SMART },
    { "Generic",                    UICART_PLUS4_GENERIC },
    { "Freezer",                    UICART_PLUS4_FREEZER },
    { "Games",                      UICART_PLUS4_GAME },
    { "Utilities",                  UICART_PLUS4_UTIL },
    { NULL, -1 }
}
List of Plus4/C16/C116 cart types.
Referenced by create_cart_type_model().
vic20_cart_types
const cart_type_list_t vic20_cart_types[] static
Initial value:
= {
    { "Smart-attach",               UICART_VIC20_SMART },
    { "Generic",                    UICART_VIC20_GENERIC },
    { "Freezer",                    UICART_VIC20_FREEZER },
    { "Games",                      UICART_VIC20_GAME },
    { "Utilities",                  UICART_VIC20_UTIL },
    { NULL, -1 }
}
List of VIC-20 'main' cart types.
The generic type will use the generic carts list in #vic20_cart_types_generic
Referenced by create_cart_type_model().