vsid: diskimage/fsimage.c File Reference
fsimage.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include "archdep.h"
#include "diskconstants.h"
#include "diskimage.h"
#include "fsimage-dxx.h"
#include "fsimage-gcr.h"
#include "fsimage-p64.h"
#include "fsimage-probe.h"
#include "fsimage.h"
#include "lib.h"
#include "log.h"
#include "types.h"
#include "zfile.h"
#include "util.h"
#include "cbmdos.h"
Functions
void fsimage_name_set (disk_image_t *image, const char *name)
Set image name.
const char * fsimage_name_get (const disk_image_t *image)
Get image name.
void * fsimage_fd_get (const disk_image_t *image)
Get file descriptor for image.
void fsimage_media_create (disk_image_t *image)
void fsimage_media_destroy (disk_image_t *image)
int fsimage_open (disk_image_t *image)
int fsimage_close (disk_image_t *image)
int fsimage_read_sector (const disk_image_t *image, uint8_t *buf, const disk_addr_t *dadr)
int fsimage_write_sector (disk_image_t *image, const uint8_t *buf, const disk_addr_t *dadr)
void fsimage_init (void)
off_t fsimage_size (const disk_image_t *image)
Variables
static log_t fsimage_log = ((log_t)-2)
Function Documentation
fsimage_close()
int fsimage_close (disk_image_t * image)
Referenced by disk_image_close(), fsimage_media_destroy(), and fsimage_open().
fsimage_fd_get()
void * fsimage_fd_get (const disk_image_t * image)
Get file descriptor for image.
Parameters
[in] image disk image
Returns
file descriptor
XXX: image should not be const, since we return the a member we later use to manipulate the image.
Referenced by disk_image_fsimage_fd_get().
fsimage_init()
void fsimage_init (void)
Referenced by disk_image_init().
fsimage_media_create()
void fsimage_media_create (disk_image_t * image)
Referenced by disk_image_media_create().
fsimage_media_destroy()
void fsimage_media_destroy (disk_image_t * image)
Referenced by disk_image_media_destroy().
fsimage_name_get()
const char * fsimage_name_get (const disk_image_t * image)
Get image name.
Parameters
[in] image disk image
Returns
image name
Referenced by disk_image_attach_log(), disk_image_detach_log(), disk_image_fsimage_name_get(), and disk_image_name_get().
fsimage_name_set()
void fsimage_name_set (disk_image_t * image, const char * name)
Set image name.
Parameters
[in] name image name
Referenced by disk_image_fsimage_name_set(), and disk_image_name_set().
fsimage_open()
int fsimage_open (disk_image_t * image)
< read mode (binary)
< read/write mode
< read mode (binary)
Referenced by disk_image_open().
fsimage_read_sector()
int fsimage_read_sector (const disk_image_t * image, uint8_t * buf, const disk_addr_t * dadr)
< HD in ASCII for CMDHD
< D9090/D9060
Referenced by disk_image_read_sector().
fsimage_size()
off_t fsimage_size (const disk_image_t * image)
Referenced by disk_image_size().
fsimage_write_sector()
int fsimage_write_sector (disk_image_t * image, const uint8_t * buf, const disk_addr_t * dadr)
< HD in ASCII for CMDHD
< D9090/D9060
Referenced by disk_image_write_sector().
Variable Documentation
fsimage_log
log_t fsimage_log = ((log_t)-2) static
Referenced by fsimage_close(), fsimage_init(), fsimage_open(), fsimage_read_sector(), and fsimage_write_sector().