vsid: diskimage/fsimage-p64.c File Reference
fsimage-p64.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "archdep.h"
#include "diskconstants.h"
#include "diskimage.h"
#include "fsimage-p64.h"
#include "fsimage.h"
#include "cbmdos.h"
#include "gcr.h"
#include "log.h"
#include "lib.h"
#include "types.h"
#include "util.h"
#include "p64.h"
Functions
int fsimage_read_p64_image (const disk_image_t *image)
Intial P64 buffer setup.
int fsimage_write_p64_image (const disk_image_t *image)
int fsimage_p64_read_half_track (const disk_image_t *image, unsigned int half_track, disk_track_t *raw)
Read an entire P64 track from the disk image.
static int fsimage_p64_read_track (const disk_image_t *image, unsigned int track, disk_track_t *raw)
int fsimage_p64_write_half_track (disk_image_t *image, unsigned int half_track, const disk_track_t *raw)
Write an entire P64 track to the disk image.
static int fsimage_p64_write_track (disk_image_t *image, unsigned int track, int gcr_track_size, uint8_t *gcr_track_start_ptr)
int fsimage_p64_read_sector (const disk_image_t *image, uint8_t *buf, const disk_addr_t *dadr)
Read a sector from the P64 disk image.
int fsimage_p64_write_sector (disk_image_t *image, const uint8_t *buf, const disk_addr_t *dadr)
Write a sector to the P64 disk image.
void fsimage_p64_init (void)
Variables
static log_t fsimage_p64_log = ((log_t)-1)
Function Documentation
fsimage_p64_init()
void fsimage_p64_init (void)
Referenced by fsimage_init().
fsimage_p64_read_half_track()
int fsimage_p64_read_half_track (const disk_image_t * image, unsigned int half_track, disk_track_t * raw)
Read an entire P64 track from the disk image.
Referenced by fsimage_p64_read_track().
fsimage_p64_read_sector()
int fsimage_p64_read_sector (const disk_image_t * image, uint8_t * buf, const disk_addr_t * dadr)
Read a sector from the P64 disk image.
Referenced by fsimage_read_sector().
fsimage_p64_read_track()
static int fsimage_p64_read_track (const disk_image_t * image, unsigned int track, disk_track_t * raw) static
Referenced by fsimage_p64_read_sector(), and fsimage_p64_write_sector().
fsimage_p64_write_half_track()
int fsimage_p64_write_half_track (disk_image_t * image, unsigned int half_track, const disk_track_t * raw)
Write an entire P64 track to the disk image.
Referenced by disk_image_write_half_track().
fsimage_p64_write_sector()
int fsimage_p64_write_sector (disk_image_t * image, const uint8_t * buf, const disk_addr_t * dadr)
Write a sector to the P64 disk image.
Referenced by fsimage_write_sector().
fsimage_p64_write_track()
static int fsimage_p64_write_track (disk_image_t * image, unsigned int track, int gcr_track_size, uint8_t * gcr_track_start_ptr) static
Referenced by fsimage_p64_write_sector().
fsimage_read_p64_image()
int fsimage_read_p64_image (const disk_image_t * image)
Intial P64 buffer setup.
Referenced by disk_image_check_for_p64(), and disk_image_read_image().
fsimage_write_p64_image()
int fsimage_write_p64_image (const disk_image_t * image)
Referenced by disk_image_write_p64_image(), fsimage_close(), fsimage_p64_write_half_track(), and fsimage_p64_write_track().
Variable Documentation
fsimage_p64_log
log_t fsimage_p64_log = ((log_t)-1) static
Referenced by fsimage_p64_init(), fsimage_p64_read_half_track(), fsimage_p64_read_sector(), fsimage_p64_write_half_track(), fsimage_p64_write_sector(), fsimage_p64_write_track(), fsimage_read_p64_image(), and fsimage_write_p64_image().