vsid: core/ciacore.c File Reference
ciacore.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "cia.h"
#include "ciatimer.h"
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "monitor.h"
#include "snapshot.h"
#include "types.h"
Macros
#define DBG(_x_)
#define STORE_OFFSET 1
#define READ_OFFSET 0
#define CIA_SDR_TOGGLE_CNT2 0x0001u
countdown to toggling CNT
#define CIA_SDR_TOGGLE_CNT1 0x0002u
#define CIA_SDR_TOGGLE_CNT0 0x0004u
#define CIA_SDR_TOGGLE_CNT_1 0x0008u
_1 = -1
#define CIA_SDR_NOGGLE_CNT2 0x0010u
countdown to NOT toggling CNT
#define CIA_SDR_NOGGLE_CNT1 0x0020u
#define CIA_SDR_NOGGLE_CNT0 0x0040u
#define CIA_SDR_NOGGLE_CNT_1 0x0080u
#define CIA_SDR_SET_SDR_IRQ3 0x0100u
countdown to setting the SDR IRQ
#define CIA_SDR_SET_SDR_IRQ2 0x0200u
#define CIA_SDR_SET_SDR_IRQ1 0x0400u
#define CIA_SDR_SET_SDR_IRQ0 0x0800u
#define CIA_SDR_CNT0 0x1000u
history of the CNT output value
#define CIA_SDR_CNT1 0x2000u
After all these bits are set or.
#define CIA_SDR_CNT2 0x4000u
reset, we can stop updating them
#define CIA_SDR_CNT3 0x8000u
until CNT is toggled.
#define CIA_SDR_SET3 0x00010000u
countdown to setting shifter
#define CIA_SDR_SET2 0x00020000u
from SDR
#define CIA_SDR_SET1 0x00040000u
#define CIA_SDR_SET0 0x00080000u
#define CIA_SDR_LEFTMOST 0x00100000u
#define CIA_SDR_CLEAR
#define CIA_SDR_ACTIVE
#define ALL_SDR_CNT (CIA_SDR_CNT0|CIA_SDR_CNT1|CIA_SDR_CNT2|CIA_SDR_CNT3)
#define ALL_SDR_TOGGLE_CNT
#define ALL_SDR_NOGGLE_CNT
#define CIA_IRQ_ACK1 0x0001
ClearIcr0 Countdown to ack-ing (resetting) irq source bits.
#define CIA_IRQ_ACK0 0x0002
ClearIcr1.
#define CIA_IRQ_ACK_1 0x0004
ClearIcr2.
#define CIA_IRQ_ACK_2 0x0008
#define CIA_IRQ_D7SET1 0x0010
SetIcr0 Countdown to setting D7 in IFR.
#define CIA_IRQ_D7SET0 0x0020
SetIcr1.
#define CIA_IRQ_D7SET_1 0x0040
#define CIA_IRQ_RAISE1 0x0100
Interrupt0 Countdown to raising interrupt.
#define CIA_IRQ_RAISE0 0x0200
Interrupt1.
#define CIA_IRQ_RAISE_1 0x0400
#define CIA_IRQ_READ0 0x1000
ReadIcr0 How long since ICR was read.
#define CIA_IRQ_READ1 0x2000
ReadIcr1.
#define CIA_IRQ_READ2 0x4000
ReadIcr2.
#define CIA_IRQ_CLEAR
#define USE_IRQ_RAISE0_SHORTCUT 1
Documented at location of use.
#define CIA_IFR_CURRENT 0x01
#define CIA_IFR_NEXT 0x02
#define CIA_IFR_CUR_NXT 0x03
#define CIA_MAX_IDLE_CYCLES 5000
#define TODRANDOM
#define CIA_DUMP_VER_MAJOR 2
#define CIA_DUMP_VER_MINOR 5
Functions
static void ciacore_intta (CLOCK offset, void *data)
static void ciacore_inttb (CLOCK offset, void *data)
static void ciacore_intsdr (CLOCK offset, void *data)
static void schedule_sdr_alarm (cia_context_t *cia_context, CLOCK rclk, uint32_t feed)
static void cia_set_irq_flag (cia_context_t *cia_context, CLOCK rclk, unsigned int bits)
static void my_set_int (cia_context_t *cia_context, bool value, CLOCK rclk)
new semantics and as inline function, value can be replaced by 0/1
static CLOCK alarm_clk (alarm_t *alarm)
static void run_pending_alarms (CLOCK clk, int offset, alarm_context_t *alarm_context)
static void check_ciatodalarm (cia_context_t *cia_context, CLOCK rclk)
cia
static void cia_do_update_ta (cia_context_t *cia_context, CLOCK rclk)
static void cia_do_update_tb (cia_context_t *cia_context, CLOCK rclk)
static void cia_do_step_tb (cia_context_t *cia_context, CLOCK rclk)
static void cia_update_ta (cia_context_t *cia_context, CLOCK rclk)
static void cia_update_tb (cia_context_t *cia_context, CLOCK rclk)
static void cia_run_ifr_cycle (cia_context_t *cia_context)
static void cia_ifr_current (cia_context_t *cia_context, CLOCK rclk, int what)
static void cia_ifr_catchup (cia_context_t *cia_context, CLOCK rclk)
void ciacore_disable (cia_context_t *cia_context)
void ciacore_reset (cia_context_t *cia_context)
static void strange_extra_sdr_flags (cia_context_t *cia_context, CLOCK rclk, uint8_t byte)
static bool ciacore_update_pb67 (cia_context_t *cia_context, CLOCK rclk)
static void ciacore_store_internal (cia_context_t *cia_context, uint16_t addr, uint8_t byte)
void ciacore_store (cia_context_t *cia_context, uint16_t addr, uint8_t byte)
uint8_t ciacore_read (cia_context_t *cia_context, uint16_t addr)
uint8_t ciacore_peek (cia_context_t *cia_context, uint16_t addr)
static void ciacore_intta_entry (CLOCK offset, void *data)
static void ciacore_inttb_entry (CLOCK offset, void *data)
static void ciacore_async_interrupt (cia_context_t *cia_context, int flag)
void ciacore_set_flag (cia_context_t *cia_context)
void ciacore_set_sdr (cia_context_t *cia_context, uint8_t data)
void ciacore_set_cnt (cia_context_t *cia_context, bool data)
void ciacore_set_sp (cia_context_t *cia_context, bool data)
static void ciacore_intsdr_entry (CLOCK offset, void *data)
static void ciacore_inttod (CLOCK offset, void *data)
static void ciacore_inttod_entry (CLOCK offset, void *data)
void ciacore_setup_context (cia_context_t *cia_context)
static void ciacore_idle (CLOCK offset, void *data)
void ciacore_init (cia_context_t *cia_context, alarm_context_t *alarm_context, interrupt_cpu_status_t *int_status)
void ciacore_shutdown (cia_context_t *cia_context)
int ciacore_snapshot_write_module (cia_context_t *cia_context, snapshot_t *s)
FIXME!!! Error check.
int ciacore_snapshot_read_module (cia_context_t *cia_context, snapshot_t *s)
int ciacore_dump (cia_context_t *cia_context)
Macro Definition Documentation
ALL_SDR_CNT
#define ALL_SDR_CNT (CIA_SDR_CNT0|CIA_SDR_CNT1|CIA_SDR_CNT2|CIA_SDR_CNT3)
ALL_SDR_NOGGLE_CNT
#define ALL_SDR_NOGGLE_CNT
Value:
                             (CIA_SDR_NOGGLE_CNT2 | CIA_SDR_NOGGLE_CNT1 | \
                             CIA_SDR_NOGGLE_CNT0 | CIA_SDR_NOGGLE_CNT_1)
ALL_SDR_TOGGLE_CNT
#define ALL_SDR_TOGGLE_CNT
Value:
                             (CIA_SDR_TOGGLE_CNT2 | CIA_SDR_TOGGLE_CNT1 | \
                             CIA_SDR_TOGGLE_CNT0 | CIA_SDR_TOGGLE_CNT_1)
CIA_DUMP_VER_MAJOR
#define CIA_DUMP_VER_MAJOR 2
CIA_DUMP_VER_MINOR
#define CIA_DUMP_VER_MINOR 5
CIA_IFR_CUR_NXT
#define CIA_IFR_CUR_NXT 0x03
CIA_IFR_CURRENT
#define CIA_IFR_CURRENT 0x01
CIA_IFR_NEXT
#define CIA_IFR_NEXT 0x02
CIA_IRQ_ACK0
#define CIA_IRQ_ACK0 0x0002
ClearIcr1.
CIA_IRQ_ACK1
#define CIA_IRQ_ACK1 0x0001
ClearIcr0 Countdown to ack-ing (resetting) irq source bits.
CIA_IRQ_ACK_1
#define CIA_IRQ_ACK_1 0x0004
ClearIcr2.
CIA_IRQ_ACK_2
#define CIA_IRQ_ACK_2 0x0008
CIA_IRQ_CLEAR
#define CIA_IRQ_CLEAR
Value:
                         (CIA_IRQ_ACK_2    | \
                         CIA_IRQ_D7SET_1  | \
                         CIA_IRQ_RAISE_1  | \
                         CIA_IRQ_READ2)
CIA_IRQ_D7SET0
#define CIA_IRQ_D7SET0 0x0020
SetIcr1.
CIA_IRQ_D7SET1
#define CIA_IRQ_D7SET1 0x0010
SetIcr0 Countdown to setting D7 in IFR.
CIA_IRQ_D7SET_1
#define CIA_IRQ_D7SET_1 0x0040
CIA_IRQ_RAISE0
#define CIA_IRQ_RAISE0 0x0200
Interrupt1.
CIA_IRQ_RAISE1
#define CIA_IRQ_RAISE1 0x0100
Interrupt0 Countdown to raising interrupt.
CIA_IRQ_RAISE_1
#define CIA_IRQ_RAISE_1 0x0400
CIA_IRQ_READ0
#define CIA_IRQ_READ0 0x1000
ReadIcr0 How long since ICR was read.
CIA_IRQ_READ1
#define CIA_IRQ_READ1 0x2000
ReadIcr1.
CIA_IRQ_READ2
#define CIA_IRQ_READ2 0x4000
ReadIcr2.
CIA_MAX_IDLE_CYCLES
#define CIA_MAX_IDLE_CYCLES 5000
CIA_SDR_ACTIVE
#define CIA_SDR_ACTIVE
Value:
                         (CIA_SDR_TOGGLE_CNT2 | CIA_SDR_TOGGLE_CNT1 |   \
                         CIA_SDR_TOGGLE_CNT0 | CIA_SDR_TOGGLE_CNT_1 |  \
                         CIA_SDR_NOGGLE_CNT2 | CIA_SDR_NOGGLE_CNT1 |   \
                         CIA_SDR_NOGGLE_CNT0 | CIA_SDR_NOGGLE_CNT_1 |  \
                         CIA_SDR_SET_SDR_IRQ3 | CIA_SDR_SET_SDR_IRQ2 | \
                         CIA_SDR_SET_SDR_IRQ1 | CIA_SDR_SET_SDR_IRQ0 | \
                         CIA_SDR_SET3 | CIA_SDR_SET2 |                 \
                         CIA_SDR_SET1 | CIA_SDR_SET0)
CIA_SDR_CLEAR
#define CIA_SDR_CLEAR
Value:
                         (CIA_SDR_NOGGLE_CNT2 | CIA_SDR_SET_SDR_IRQ3 | \
                         CIA_SDR_CNT0 | CIA_SDR_SET3 | CIA_SDR_LEFTMOST)
CIA_SDR_CNT0
#define CIA_SDR_CNT0 0x1000u
history of the CNT output value
CIA_SDR_CNT1
#define CIA_SDR_CNT1 0x2000u
After all these bits are set or.
CIA_SDR_CNT2
#define CIA_SDR_CNT2 0x4000u
reset, we can stop updating them
CIA_SDR_CNT3
#define CIA_SDR_CNT3 0x8000u
until CNT is toggled.
CIA_SDR_LEFTMOST
#define CIA_SDR_LEFTMOST 0x00100000u
CIA_SDR_NOGGLE_CNT0
#define CIA_SDR_NOGGLE_CNT0 0x0040u
CIA_SDR_NOGGLE_CNT1
#define CIA_SDR_NOGGLE_CNT1 0x0020u
CIA_SDR_NOGGLE_CNT2
#define CIA_SDR_NOGGLE_CNT2 0x0010u
countdown to NOT toggling CNT
CIA_SDR_NOGGLE_CNT_1
#define CIA_SDR_NOGGLE_CNT_1 0x0080u
CIA_SDR_SET0
#define CIA_SDR_SET0 0x00080000u
CIA_SDR_SET1
#define CIA_SDR_SET1 0x00040000u
CIA_SDR_SET2
#define CIA_SDR_SET2 0x00020000u
from SDR
CIA_SDR_SET3
#define CIA_SDR_SET3 0x00010000u
countdown to setting shifter
CIA_SDR_SET_SDR_IRQ0
#define CIA_SDR_SET_SDR_IRQ0 0x0800u
CIA_SDR_SET_SDR_IRQ1
#define CIA_SDR_SET_SDR_IRQ1 0x0400u
CIA_SDR_SET_SDR_IRQ2
#define CIA_SDR_SET_SDR_IRQ2 0x0200u
CIA_SDR_SET_SDR_IRQ3
#define CIA_SDR_SET_SDR_IRQ3 0x0100u
countdown to setting the SDR IRQ
CIA_SDR_TOGGLE_CNT0
#define CIA_SDR_TOGGLE_CNT0 0x0004u
CIA_SDR_TOGGLE_CNT1
#define CIA_SDR_TOGGLE_CNT1 0x0002u
CIA_SDR_TOGGLE_CNT2
#define CIA_SDR_TOGGLE_CNT2 0x0001u
countdown to toggling CNT
CIA_SDR_TOGGLE_CNT_1
#define CIA_SDR_TOGGLE_CNT_1 0x0008u
_1 = -1
DBG
#define DBG (_x_)
READ_OFFSET
#define READ_OFFSET 0
STORE_OFFSET
#define STORE_OFFSET 1
TODRANDOM
#define TODRANDOM
USE_IRQ_RAISE0_SHORTCUT
#define USE_IRQ_RAISE0_SHORTCUT 1
Documented at location of use.
Function Documentation
alarm_clk()
static CLOCK alarm_clk (alarm_t * alarm) inline static
Referenced by ciacore_async_interrupt(), ciacore_intsdr(), and ciacore_snapshot_write_module().
check_ciatodalarm()
static void check_ciatodalarm (cia_context_t * cia_context, CLOCK rclk) inline static
cia
< Time Of Day clock 1/10 s
< TOD Clock Alarm
Referenced by ciacore_inttod(), and ciacore_store_internal().
cia_do_step_tb()
static void cia_do_step_tb (cia_context_t * cia_context, CLOCK rclk) static
< Timer B underflow
Referenced by ciacore_intta().
cia_do_update_ta()
static void cia_do_update_ta (cia_context_t * cia_context, CLOCK rclk) static
< Timer A underflow
Referenced by cia_update_ta(), and ciacore_intta().
cia_do_update_tb()
static void cia_do_update_tb (cia_context_t * cia_context, CLOCK rclk) static
< Timer B underflow
< "old"
< Timer B bug flag
< Timer B bug flag
Referenced by cia_update_tb(), and ciacore_inttb().
cia_ifr_catchup()
static void cia_ifr_catchup (cia_context_t * cia_context, CLOCK rclk) static
Referenced by cia_set_irq_flag(), ciacore_idle(), ciacore_intsdr_entry(), ciacore_intta_entry(), ciacore_inttb_entry(), ciacore_inttod_entry(), ciacore_snapshot_write_module(), ciacore_store_internal(), and ciacore_update_pb67().
cia_ifr_current()
static void cia_ifr_current (cia_context_t * cia_context, CLOCK rclk, int what) static
< Interrupt1
< Interrupt0 Countdown to raising interrupt
Referenced by ciacore_idle(), ciacore_intsdr_entry(), ciacore_intta_entry(), ciacore_inttb_entry(), ciacore_inttod_entry(), ciacore_snapshot_read_module(), ciacore_snapshot_write_module(), ciacore_store_internal(), and ciacore_update_pb67().
cia_run_ifr_cycle()
static void cia_run_ifr_cycle (cia_context_t * cia_context) static
< "old"
< ClearIcr1
< ClearIcr1
< Control Bit
< Interrupt control register
< "old"
< Interrupt0 Countdown to raising interrupt
< SetIcr0 Countdown to setting D7 in IFR
< Interrupt1
< SetIcr1
< Interrupt0 Countdown to raising interrupt
< SetIcr0 Countdown to setting D7 in IFR
< SetIcr1
< Control Bit
< Interrupt1
< ReadIcr2
Referenced by cia_ifr_catchup(), and cia_ifr_current().
cia_set_irq_flag()
static void cia_set_irq_flag (cia_context_t * cia_context, CLOCK rclk, unsigned int bits) static
Referenced by check_ciatodalarm(), cia_do_step_tb(), cia_do_update_ta(), cia_do_update_tb(), ciacore_async_interrupt(), and ciacore_intsdr().
cia_update_ta()
static void cia_update_ta (cia_context_t * cia_context, CLOCK rclk) static
Referenced by cia_update_tb(), ciacore_idle(), ciacore_snapshot_write_module(), ciacore_store_internal(), and ciacore_update_pb67().
cia_update_tb()
static void cia_update_tb (cia_context_t * cia_context, CLOCK rclk) static
< Control register B
Referenced by ciacore_idle(), ciacore_intta(), ciacore_snapshot_write_module(), ciacore_store_internal(), and ciacore_update_pb67().
ciacore_async_interrupt()
static void ciacore_async_interrupt (cia_context_t * cia_context, int flag) static
Referenced by ciacore_set_flag(), and ciacore_set_sdr().
ciacore_disable()
void ciacore_disable (cia_context_t * cia_context)
Referenced by iec_drive_reset().
ciacore_dump()
int ciacore_dump (cia_context_t * cia_context)
< Interrupt control register
< Interrupt control register
< Interrupt control register
< Interrupt control register
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Interrupt control register
< Interrupt control register
Referenced by cia1571_dump(), cia1581_dump(), cia2_dump(), mem_dump_io(), and mos5710_dump().
ciacore_idle()
static void ciacore_idle (CLOCK offset, void * data) static
printf("ciacore_idle: clk=%lu rclk=%lu\n", clk, rclk);
Referenced by ciacore_init().
ciacore_init()
void ciacore_init (cia_context_t * cia_context, alarm_context_t * alarm_context, interrupt_cpu_status_t * int_status)
Referenced by cia1571_init(), cia1581_init(), cia1_init(), and cia2_init().
ciacore_intsdr()
static void ciacore_intsdr (CLOCK offset, void * data) static
< Serial port shift register
< Serial port shift register
Todo:
maybe unset the other SET_SDR_IRQx bits?
< Serial port shift register
< Shift Register completion
< countdown to NOT toggling CNT
< countdown to setting the SDR IRQ
< history of the CNT output value
< countdown to setting shifter
< history of the CNT output value
< countdown to toggling CNT
< _1 = -1
< countdown to NOT toggling CNT
< countdown to setting the SDR IRQ
< countdown to setting shifter
< from SDR
< history of the CNT output value
< After all these bits are set or
< reset, we can stop updating them
< until CNT is toggled.
< history of the CNT output value
< After all these bits are set or
< reset, we can stop updating them
< until CNT is toggled.
Referenced by ciacore_intsdr_entry().
ciacore_intsdr_entry()
static void ciacore_intsdr_entry (CLOCK offset, void * data) static
Referenced by ciacore_init().
ciacore_intta()
static void ciacore_intta (CLOCK offset, void * data) static
< Control register A
< Interrupt control register
< Timer A underflow
< Control Bit
< Control register A
< Control register B
< Control register A
< Control register B
Referenced by cia_update_ta(), ciacore_intsdr(), and ciacore_intta_entry().
ciacore_intta_entry()
static void ciacore_intta_entry (CLOCK offset, void * data) static
Referenced by ciacore_init().
ciacore_inttb()
static void ciacore_inttb (CLOCK offset, void * data) static
< Control register B
< Interrupt control register
< Timer B underflow
Referenced by cia_update_tb(), and ciacore_inttb_entry().
ciacore_inttb_entry()
static void ciacore_inttb_entry (CLOCK offset, void * data) static
Referenced by ciacore_init().
ciacore_inttod()
static void ciacore_inttod (CLOCK offset, void * data) static
< Control register A
< Time Of Day clock 1/10 s
< Time Of Day clock sec
< Time Of Day clock sec
< Time Of Day clock min
< Time Of Day clock min
< Time Of Day clock hour
< Time Of Day clock hour
< Time Of Day clock hour
< Time Of Day clock 1/10 s
< Time Of Day clock sec
< Time Of Day clock min
< Time Of Day clock hour
Referenced by ciacore_inttod_entry().
ciacore_inttod_entry()
static void ciacore_inttod_entry (CLOCK offset, void * data) static
Referenced by ciacore_init().
ciacore_peek()
uint8_t ciacore_peek (cia_context_t * cia_context, uint16_t addr)
Todo:
FIXME: this function should return the current state of the registers without affecting the state of the emulation.
< Port A
< Port B
< Data direction register for port A
< Data direction register for port B
< Timer A low
< Timer A high
< Timer B low
< Timer B high
< Time Of Day clock 1/10 s
< Time Of Day clock sec
< Time Of Day clock min
< Time Of Day clock hour
< Serial port shift register
< Serial port shift register
< Interrupt control register
< Control register A
< Control register B
Todo:
FIXME: perhaps we need to restore some of the state from before reading. needs testing. NOTE: cia_context->last_read is only used to handle RMW instructions, since we only ever call this function in between instructions, we dont have to restore it's value.
Referenced by cia1571_peek(), cia1581_peek(), cia1_peek(), cia2_peek(), ciacore_dump(), ciacore_snapshot_write_module(), and mos5710_peek().
ciacore_read()
uint8_t ciacore_read (cia_context_t * cia_context, uint16_t addr)
< Port A
< Port B
< Control register A
< Control register B
< Control register A
< Control register A
< Control register B
< Control register B
< Timer A low
< Timer A high
< Timer B low
< Timer B high
< Time Of Day clock 1/10 s
< Time Of Day clock sec
< Time Of Day clock min
< Time Of Day clock hour
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Time Of Day clock hour
< Time Of Day clock 1/10 s
< Serial port shift register
< Serial port shift register
< Interrupt control register
< Timer B bug flag
< Timer B bug flag
< Timer B underflow
< "old"
< Interrupt1
< Control Bit
< ClearIcr0 Countdown to ack-ing (resetting) irq source bits
< Interrupt1
< SetIcr1
< ClearIcr0 Countdown to ack-ing (resetting) irq source bits
< Interrupt1
< Control Bit
< ReadIcr0 How long since ICR was read
< Control register A
< Control register A
< Control register B
< Control register B
Referenced by cia1571_read(), cia1581_read(), cia1_read(), cia2_read(), ciacore_peek(), and mos5710_read().
ciacore_reset()
void ciacore_reset (cia_context_t * cia_context)
< history of the CNT output value
< After all these bits are set or
< reset, we can stop updating them
< until CNT is toggled.
< Time Of Day clock hour
< Time Of Day clock 1/10 s
Referenced by ciacore_snapshot_read_module(), iec_drive_reset(), and machine_specific_reset().
ciacore_set_cnt()
void ciacore_set_cnt (cia_context_t * cia_context, bool data)
< Control register A
Todo:
Handle Timer B if it is in CNT pulse counting mode
ciacore_set_flag()
void ciacore_set_flag (cia_context_t * cia_context)
< Handshake
Referenced by c64_userport_set_flag(), cia2_set_flagx(), iecbus_cpu_write_conf1(), iecbus_cpu_write_conf2(), iecbus_cpu_write_conf3(), machine_trigger_flux_change(), parallel_cable_cpu_pulse(), parallel_cable_drive_read(), and parallel_cable_drive_write().
ciacore_set_sdr()
void ciacore_set_sdr (cia_context_t * cia_context, uint8_t data)
< Control register A
< Serial port shift register
< Shift Register completion
Referenced by c64fastiec_fast_cpu_write(), cia2_set_sdrx(), ciacore_set_cnt(), and iec_fast_drive_write().
ciacore_set_sp()
void ciacore_set_sp (cia_context_t * cia_context, bool data)
ciacore_setup_context()
void ciacore_setup_context (cia_context_t * cia_context)
Referenced by cia1571_setup_context(), cia1581_setup_context(), cia1_setup_context(), and cia2_setup_context().
ciacore_shutdown()
void ciacore_shutdown (cia_context_t * cia_context)
Referenced by iec_drive_shutdown(), and machine_specific_shutdown().
ciacore_snapshot_read_module()
int ciacore_snapshot_read_module (cia_context_t * cia_context, snapshot_t * s)
< Port A
< Port B
< Data direction register for port A
< Data direction register for port B
< Port A
< Data direction register for port A
< Port B
< Data direction register for port B
< Time Of Day clock 1/10 s
< Time Of Day clock sec
< Time Of Day clock min
< Time Of Day clock hour
< Serial port shift register
< Interrupt control register
< Control register A
< Control register B
< Control register A
< Control register B
< Interrupt control register
< Control Bit
Referenced by c64_snapshot_read(), and iec_drive_snapshot_read().
ciacore_snapshot_write_module()
int ciacore_snapshot_write_module (cia_context_t * cia_context, snapshot_t * s)
FIXME!!! Error check.
< Port A
< Port B
< Data direction register for port A
< Data direction register for port B
< Time Of Day clock 1/10 s
< Time Of Day clock sec
< Time Of Day clock min
< Time Of Day clock hour
< Serial port shift register
< Interrupt control register
< Control register A
< Control register B
< Interrupt control register
Referenced by c64_snapshot_write(), and iec_drive_snapshot_write().
ciacore_store()
void ciacore_store (cia_context_t * cia_context, uint16_t addr, uint8_t byte)
Referenced by cia1571_store(), cia1581_store(), cia1_store(), cia2_store(), and mos5710_store().
ciacore_store_internal()
static void ciacore_store_internal (cia_context_t * cia_context, uint16_t addr, uint8_t byte) static
< Port A
< Data direction register for port A
< Port A
< Data direction register for port A
< Port B
< Data direction register for port B
< Port B
< Timer A low
< Timer B low
< Timer A high
< Timer B high
< Time Of Day clock 1/10 s
< Time Of Day clock hour
< Time Of Day clock sec
< Time Of Day clock min
< Time Of Day clock hour
< Control register B
< Time Of Day clock min
< Time Of Day clock sec
< Time Of Day clock 1/10 s
< Control register B
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Time Of Day clock 1/10 s
< Time Of Day clock hour
< Serial port shift register
< Control register A
< Interrupt control register
< Control Bit
< Interrupt control register
< Interrupt control register
< Interrupt control register
< "old"
< ReadIcr1
< Interrupt1
< SetIcr1
< Interrupt0 Countdown to raising interrupt
< SetIcr0 Countdown to setting D7 in IFR
< "old"
< ClearIcr2
< Interrupt1
< SetIcr1
< Interrupt control register
< Timer A underflow
< Interrupt control register
< Timer B underflow
< Control register A
< Control register A
< Control register A
< countdown to toggling CNT
< _1 = -1
< countdown to NOT toggling CNT
Todo:
timers driven by positive CNT edge
< Control register B
< Control register B
Referenced by ciacore_store().
ciacore_update_pb67()
static bool ciacore_update_pb67 (cia_context_t * cia_context, CLOCK rclk) inline static
< Port B
< Data direction register for port B
< Control register A
< Control register B
< Control register A
< Control register A
< Control register B
< Control register B
Referenced by ciacore_store_internal().
my_set_int()
static void my_set_int (cia_context_t * cia_context, bool value, CLOCK rclk) inline static
new semantics and as inline function, value can be replaced by 0/1
Referenced by cia_ifr_current(), cia_run_ifr_cycle(), ciacore_reset(), mypia_reset(), and mypia_update_irq().
run_pending_alarms()
static void run_pending_alarms (CLOCK clk, int offset, alarm_context_t * alarm_context) inline static
Referenced by ciacore_store_internal().
schedule_sdr_alarm()
static void schedule_sdr_alarm (cia_context_t * cia_context, CLOCK rclk, uint32_t feed) static
Referenced by ciacore_intta(), ciacore_store_internal(), and strange_extra_sdr_flags().
strange_extra_sdr_flags()
static void strange_extra_sdr_flags (cia_context_t * cia_context, CLOCK rclk, uint8_t byte) inline static
< "old"
< history of the CNT output value
< After all these bits are set or
< reset, we can stop updating them
< After all these bits are set or
< reset, we can stop updating them
< countdown to toggling CNT
Referenced by ciacore_store_internal().