vsid: vsidui.h File Reference
vsidui.h File Reference
#include <stdint.h>
Functions
int vsid_ui_init_early (void)
int vsid_ui_init (void)
Initialize the VSID UI.
void vsid_ui_close (void)
void vsid_ui_display_name (const char *name)
Display tune name in the UI.
void vsid_ui_display_author (const char *author)
Display tune author in the UI.
void vsid_ui_display_copyright (const char *copyright)
Display tune copyright info in the UI.
void vsid_ui_display_sync (int sync)
Set sync factor for the UI.
void vsid_ui_display_sid_model (int model)
Set SID model for the UI.
void vsid_ui_display_tune_nr (int nr)
Set current tune number in the UI.
void vsid_ui_display_nr_of_tunes (int count)
Set number of tunes for the UI.
void vsid_ui_set_default_tune (int nr)
Set default tune number in the UI.
void vsid_ui_display_time (unsigned int sec)
Set run time of tune in the UI.
void vsid_ui_display_irqtype (const char *irq)
Set IRQ type for the UI.
void vsid_ui_setdrv (char *driver_info_text)
Set driver info text for the UI.
void vsid_ui_set_driver_addr (uint16_t addr)
Set driver address.
void vsid_ui_set_load_addr (uint16_t addr)
Set load address.
void vsid_ui_set_init_addr (uint16_t addr)
Set init routine address.
void vsid_ui_set_play_addr (uint16_t addr)
Set play routine address.
void vsid_ui_set_data_size (uint16_t size)
Set size of SID on actual machine.
Function Documentation
vsid_ui_close()
void vsid_ui_close (void)
Referenced by machine_specific_shutdown().
vsid_ui_display_author()
void vsid_ui_display_author (const char * author)
Display tune author in the UI.
Parameters
[in] author author name
Referenced by psid_init_tune().
vsid_ui_display_copyright()
void vsid_ui_display_copyright (const char * copyright)
Display tune copyright info in the UI.
Parameters
[in] copright copyright info
Referenced by psid_init_tune().
vsid_ui_display_irqtype()
void vsid_ui_display_irqtype (const char * irq)
Set IRQ type for the UI.
Parameters
[in] irq IRQ type
Referenced by psid_init_tune().
vsid_ui_display_name()
void vsid_ui_display_name (const char * name)
Display tune name in the UI.
Parameters
[in] name tune name
Referenced by psid_init_tune().
vsid_ui_display_nr_of_tunes()
void vsid_ui_display_nr_of_tunes (int count)
Set number of tunes for the UI.
Parameters
[in] count number of tunes
Referenced by psid_init_tune(), and psid_load_file().
vsid_ui_display_sid_model()
void vsid_ui_display_sid_model (int model)
Set SID model for the UI.
Parameters
[in] model SID model
Referenced by psid_init_tune().
vsid_ui_display_sync()
void vsid_ui_display_sync (int sync)
Set sync factor for the UI.
Parameters
[in] sync sync factor
Referenced by psid_init_tune().
vsid_ui_display_time()
void vsid_ui_display_time (unsigned int dsec)
Set run time of tune in the UI.
Parameters
[in] sec seconds of play time
Referenced by machine_vsync_hook(), and psid_init_tune().
vsid_ui_display_tune_nr()
void vsid_ui_display_tune_nr (int nr)
Set current tune number in the UI.
Parameters
[in] nr tune number
Referenced by psid_init_tune().
vsid_ui_init()
int vsid_ui_init (void)
Initialize the VSID UI.
Returns
0 on success, -1 on failure
Referenced by machine_specific_init().
vsid_ui_init_early()
int vsid_ui_init_early (void)
vsid_ui_set_data_size()
void vsid_ui_set_data_size (uint16_t size)
Set size of SID on actual machine.
Parameters
[in] size size of SID
Referenced by psid_init_tune().
vsid_ui_set_default_tune()
void vsid_ui_set_default_tune (int nr)
Set default tune number in the UI.
Parameters
[in] nr tune number
Referenced by psid_init_tune(), and psid_load_file().
vsid_ui_set_driver_addr()
void vsid_ui_set_driver_addr (uint16_t addr)
Set driver address.
Parameters
[in] addr driver address
Referenced by psid_init_tune().
vsid_ui_set_init_addr()
void vsid_ui_set_init_addr (uint16_t addr)
Set init routine address.
Parameters
[in] addr init routine address
Referenced by psid_init_tune().
vsid_ui_set_load_addr()
void vsid_ui_set_load_addr (uint16_t addr)
Set load address.
Parameters
[in] addr load address
Referenced by psid_init_tune().
vsid_ui_set_play_addr()
void vsid_ui_set_play_addr (uint16_t addr)
Set play routine address.
Parameters
[in] addr play routine address
Referenced by psid_init_tune().
vsid_ui_setdrv()
void vsid_ui_setdrv (char * driver_info_text)
Set driver info text for the UI.
Parameters
[in] driver_info_text text with driver info (duh)
Referenced by psid_init_tune().