vsid: arch/gtk3/widgets/settings_keyboard.c File Reference
settings_keyboard.c File Reference
GTK3 keyboard settings main widget.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include "kbdhostlayoutwidget.h"
#include "kbdmappingwidget.h"
#include "keyboard.h"
#include "keymap.h"
#include "lastdir.h"
#include "lib.h"
#include "resources.h"
#include "uistatusbar.h"
#include "util.h"
#include "vice_gtk3.h"
#include "settings_keyboard.h"
Functions
static void on_kbd_debug_toggled (GtkWidget *widget, gpointer data)
Toggle statusbar keyboard debugging widget display.
static void save_filename_callback (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the save-dialog response handler.
static void on_save_custom_keymap_clicked (GtkWidget *widget, gpointer data)
Write current keymap to host system.
GtkWidget * settings_keyboard_widget_create (GtkWidget *widget)
Create keyboard settings widget.
void settings_keyboard_widget_shutdown (void)
Free last used directory and file strings.
Variables
static char * last_dir = NULL
Last directory of the save-as dialog.
static char * last_file = NULL
Last filename of the save-as dialog.
Detailed Description
GTK3 keyboard settings main widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
on_kbd_debug_toggled()
static void on_kbd_debug_toggled (GtkWidget * widget, gpointer data) static
Toggle statusbar keyboard debugging widget display.
Parameters
[in] widget toggle button
[in] data extra event data (unused)
Referenced by settings_keyboard_widget_create().
on_save_custom_keymap_clicked()
static void on_save_custom_keymap_clicked (GtkWidget * widget, gpointer data) static
Write current keymap to host system.
Parameters
[in] widget button triggering the event (ignored)
[in] data extra event data (ignored)
Referenced by settings_keyboard_widget_create().
save_filename_callback()
static void save_filename_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the save-dialog response handler.
Parameters
[in,out] dialog save-file dialog
[in,out] filename filename
[in] data extra data (unused)
Referenced by on_save_custom_keymap_clicked().
settings_keyboard_widget_create()
GtkWidget * settings_keyboard_widget_create (GtkWidget * widget)
Create keyboard settings widget.
Parameters
[in] widget parent widget (unused)
Returns
GtkGrid
settings_keyboard_widget_shutdown()
void settings_keyboard_widget_shutdown (void)
Free last used directory and file strings.
This function should be called on emulator shutdown to clean up the resources used by the last used directory/file strings.
Referenced by ui_shutdown().
Variable Documentation
last_dir
char* last_dir = NULL static
Last directory of the save-as dialog.
Referenced by on_save_custom_keymap_clicked(), save_filename_callback(), and settings_keyboard_widget_shutdown().
last_file
char* last_file = NULL static
Last filename of the save-as dialog.
Referenced by on_save_custom_keymap_clicked(), save_filename_callback(), and settings_keyboard_widget_shutdown().