x128: output_select_s Struct Reference
output_select_s Struct Reference
#include <output-select.h>
Data Fields
char * output_name
int(* output_open)(unsigned int prnr, struct output_parameter_s *output_parameter)
void(* output_close)(unsigned int prnr)
int(* output_putc)(unsigned int prnr, uint8_t b)
int(* output_getc)(unsigned int prnr, uint8_t *b)
int(* output_flush)(unsigned int prnr)
int(* output_formfeed)(unsigned int prnr)
Field Documentation
output_close
void(* output_select_s::output_close) (unsigned int prnr)
Referenced by output_graphics_init_resources(), output_select_close(), and output_text_init_resources().
output_flush
int(* output_select_s::output_flush) (unsigned int prnr)
Referenced by output_graphics_init_resources(), output_select_flush(), and output_text_init_resources().
output_formfeed
int(* output_select_s::output_formfeed) (unsigned int prnr)
Referenced by output_graphics_init_resources(), output_select_formfeed(), and output_text_init_resources().
output_getc
int(* output_select_s::output_getc) (unsigned int prnr, uint8_t *b)
Referenced by output_graphics_init_resources(), output_select_getc(), and output_text_init_resources().
output_name
char* output_select_s::output_name
Referenced by build_printer_output_names(), output_graphics_init_resources(), output_text_init_resources(), and set_output_device().
output_open
int(* output_select_s::output_open) (unsigned int prnr, struct output_parameter_s *output_parameter)
Referenced by output_graphics_init_resources(), output_select_open(), and output_text_init_resources().
output_putc
int(* output_select_s::output_putc) (unsigned int prnr, uint8_t b)
Referenced by output_graphics_init_resources(), output_select_putc(), and output_text_init_resources().
The documentation for this struct was generated from the following file:
printerdrv/output-select.h