x128: arch/gtk3/uivideo.h File Reference
uivideo.h File Reference
Video chip/config helpers - header.
#include "vice.h"
Enumerations
enum {
UI_VIDEO_CHIP_NONE = -1 ,
UI_VIDEO_CHIP_VICII ,
UI_VIDEO_CHIP_VIC ,
UI_VIDEO_CHIP_CRTC ,
UI_VIDEO_CHIP_TED
}
Video chip ID enum.
Functions
const char * uivideo_chip_name (void)
Get video chip name by machine_class
int uivideo_chip_id (void)
Get video chip ID by machine_class
int uivideo_chip_has_vert_stretch (const char *chip)
Determine if the current video chip supports VerticalStretch.
int uivideo_chip_has_border_mode (const char *chip)
Determine if the current video chip supports BorderMode.
int uivideo_chip_has_vsp_bug (const char *chip)
Determine if the current video chip supports VSP-bug emulation.
int uivideo_chip_has_sprites (const char *chip)
Determine if the current video chip supports sprites.
Detailed Description
Video chip/config helpers - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
anonymous enum
anonymous enum
Video chip ID enum.
Enumerator
UI_VIDEO_CHIP_NONE
invalid chip
UI_VIDEO_CHIP_VICII
VIC-II.
UI_VIDEO_CHIP_VIC
VIC.
UI_VIDEO_CHIP_CRTC
CRTC.
UI_VIDEO_CHIP_TED
TED.
Function Documentation
uivideo_chip_has_border_mode()
int uivideo_chip_has_border_mode (const char * chip)
Determine if the current video chip supports BorderMode.
Parameters
[in] chip chip name (only used in case of the C128)
Returns
bool
Referenced by create_layout().
uivideo_chip_has_sprites()
int uivideo_chip_has_sprites (const char * chip)
Determine if the current video chip supports sprites.
Parameters
[in] chip chip name (only used in case of the C128
Returns
bool
Referenced by create_misc_widget().
uivideo_chip_has_vert_stretch()
int uivideo_chip_has_vert_stretch (const char * chip)
Determine if the current video chip supports VerticalStretch.
Parameters
[in] chip chip name (only used in case of the C128
Returns
bool
Referenced by create_render_widget().
uivideo_chip_has_vsp_bug()
int uivideo_chip_has_vsp_bug (const char * chip)
Determine if the current video chip supports VSP-bug emulation.
Parameters
[in] chip chip name (only used in case of the C128)
Returns
bool
Referenced by create_misc_widget().
uivideo_chip_id()
int uivideo_chip_id (void)
Get video chip ID by machine_class
Returns
Video chip ID (
See also
src/arch/gtk3/uivideo.h)
Warning
Returns "VICII" for C128, not VDC
uivideo_chip_name()
const char * uivideo_chip_name (void)
Get video chip name by machine_class
Returns
Video chip name (the prefix used in "${CHIP}FooBar" resources)
Warning
Returns "VICII" for C128, not VDC
Referenced by settings_host_display_widget_create(), and settings_video_widget_create().