x128: network.c File Reference
network.c File Reference
#include "vice.h"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <strings.h>
#include "archdep.h"
#include "cmdline.h"
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "maincpu.h"
#include "mos6510.h"
#include "network.h"
#include "resources.h"
#include "types.h"
#include "uiapi.h"
#include "util.h"
#include "vice-event.h"
#include "vicesocket.h"
#include "vsync.h"
#include "vsyncapi.h"
Data Structures
struct testpacket
Macros
#define DBG(x)
#define DBGT(x)
#define SEND_FLAGS 0
#define NUM_OF_TESTPACKETS 50
Functions
static int set_server_name (const char *val, void *param)
static int set_server_bind_address (const char *val, void *param)
static int set_server_port (int val, void *param)
static int set_network_control (int val, void *param)
int network_resources_init (void)
static void network_set_mask (int offset, int val)
static int network_control_cmd (const char *param, void *extra_param)
int network_cmdline_options_init (void)
static void network_free_frame_event_list (void)
static void network_event_record_sync_test (uint16_t addr, void *data)
static void network_init_frame_event_list (void)
static void network_prepare_next_frame (void)
static unsigned int network_create_event_buffer (uint8_t **buf, event_list_state_t *list)
static event_list_state_t * network_create_event_list (uint8_t *remote_event_buffer)
static int network_recv_buffer (vice_network_socket_t *s, uint8_t *buf, int len)
static int network_send_buffer (vice_network_socket_t *s, const uint8_t *buf, int len)
static int network_test_delay (void)
static void network_server_connect_trap (uint16_t addr, void *data)
triggers on the server, when the client connects
static void network_client_connect_trap (uint16_t addr, void *data)
triggers on the client, when it connects to the server
void network_event_record (unsigned int type, void *data, unsigned int size)
void network_attach_image (unsigned int unit, const char *filename)
int network_get_mode (void)
int network_connected (void)
int network_start_server (void)
int network_connect_client (void)
void network_disconnect (void)
void network_suspend (void)
static void network_hook_connected_send (void)
static void network_hook_connected_receive (void)
void network_hook (void)
void network_shutdown (void)
Variables
static network_mode_t network_mode = NETWORK_IDLE
static int current_send_frame
static int last_received_frame
static vice_network_socket_t * listen_socket
static vice_network_socket_t * network_socket
static int suspended
static char * server_name = NULL
static char * server_bind_address = NULL
static unsigned short server_port
static int res_server_port
static int frame_delta
static int network_control
static int frame_buffer_full
static int current_frame
static int frame_to_play
static event_list_state_t * frame_event_list = NULL
static char * snapshotfilename
static const resource_string_t resources_string []
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
Macro Definition Documentation
DBG
#define DBG (x)
DBGT
#define DBGT (x)
NUM_OF_TESTPACKETS
#define NUM_OF_TESTPACKETS 50
SEND_FLAGS
#define SEND_FLAGS 0
Function Documentation
network_attach_image()
void network_attach_image (unsigned int unit, const char * filename)
Todo:
drive 1?
Referenced by file_system_attach_disk(), and tape_image_attach().
network_client_connect_trap()
static void network_client_connect_trap (uint16_t addr, void * data) static
triggers on the client, when it connects to the server
Referenced by network_connect_client().
network_cmdline_options_init()
int network_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
network_connect_client()
int network_connect_client (void)
< write mode (binary)
Referenced by on_netplay_notify_active().
network_connected()
int network_connected (void)
Referenced by network_hook(), network_shutdown(), and network_suspend().
network_control_cmd()
static int network_control_cmd (const char * param, void * extra_param) static
network_create_event_buffer()
static unsigned int network_create_event_buffer (uint8_t ** buf, event_list_state_t * list) static
Referenced by network_hook_connected_send(), and network_server_connect_trap().
network_create_event_list()
static event_list_state_t * network_create_event_list (uint8_t * remote_event_buffer) static
Referenced by network_client_connect_trap(), and network_hook_connected_receive().
network_disconnect()
void network_disconnect (void)
Referenced by network_hook_connected_receive(), network_hook_connected_send(), network_shutdown(), and on_netplay_notify_active().
network_event_record()
void network_event_record (unsigned int type, void * data, unsigned int size)
Referenced by network_event_record_sync_test(), and network_hook_connected_send().
network_event_record_sync_test()
static void network_event_record_sync_test (uint16_t addr, void * data) static
Referenced by network_init_frame_event_list(), and network_prepare_next_frame().
network_free_frame_event_list()
static void network_free_frame_event_list (void) static
Referenced by network_shutdown(), and network_test_delay().
network_get_mode()
int network_get_mode (void)
Referenced by network_attach_image(), and network_event_record().
network_hook()
void network_hook (void)
network_hook_connected_receive()
static void network_hook_connected_receive (void) static
Referenced by network_hook().
network_hook_connected_send()
static void network_hook_connected_send (void) static
Referenced by network_hook().
network_init_frame_event_list()
static void network_init_frame_event_list (void) static
Referenced by network_test_delay().
network_prepare_next_frame()
static void network_prepare_next_frame (void) static
Referenced by network_hook_connected_receive().
network_recv_buffer()
static int network_recv_buffer (vice_network_socket_t * s, uint8_t * buf, int len) static
Referenced by network_client_connect_trap(), network_connect_client(), network_hook_connected_receive(), and network_test_delay().
network_resources_init()
int network_resources_init (void)
Referenced by machine_resources_init().
network_send_buffer()
static int network_send_buffer (vice_network_socket_t * s, const uint8_t * buf, int len) static
Referenced by network_hook_connected_send(), network_server_connect_trap(), network_suspend(), and network_test_delay().
network_server_connect_trap()
static void network_server_connect_trap (uint16_t addr, void * data) static
triggers on the server, when the client connects
< read mode (binary)
Referenced by network_hook().
network_set_mask()
static void network_set_mask (int offset, int val) static
Referenced by network_control_cmd().
network_shutdown()
void network_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
network_start_server()
int network_start_server (void)
Referenced by on_netplay_notify_active().
network_suspend()
void network_suspend (void)
Referenced by vsync_suspend_speed_eval().
network_test_delay()
static int network_test_delay (void) static
Todo:
FIXME: This needs some further investigation
Referenced by network_client_connect_trap(), and network_server_connect_trap().
set_network_control()
static int set_network_control (int val, void * param) static
set_server_bind_address()
static int set_server_bind_address (const char * val, void * param) static
set_server_name()
static int set_server_name (const char * val, void * param) static
set_server_port()
static int set_server_port (int val, void * param) static
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-netplayserver", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "NetworkServerName", NULL,
      "<hostname>", "Set the netplay server hostname" },
    { "-netplaybind", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "NetworkServerBindAddress", NULL,
      "<hostname>", "Set the netplay binding address" },
    { "-netplayport", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "NetworkServerPort", NULL,
      "<port>", "Set the netplay port (0..65535)" },
    { "-netplayctrl", CALL_FUNCTION,  (1 << 0) ,
      network_control_cmd, NULL, NULL, NULL,
      "<key,joy1,joy2,dev,rsrc>", "Set the netplay control elements (keyboard, joystick1, joystick2, devices and resources), each item takes a value (0: None, 1: Server, 2: Client, 3: Both)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by network_cmdline_options_init().
current_frame
int current_frame static
Referenced by file_get_sample(), network_attach_image(), network_event_record(), network_hook_connected_receive(), network_hook_connected_send(), network_init_frame_event_list(), and network_prepare_next_frame().
current_send_frame
int current_send_frame static
Referenced by network_client_connect_trap(), and network_server_connect_trap().
frame_buffer_full
int frame_buffer_full static
Referenced by network_hook_connected_receive(), and network_init_frame_event_list().
frame_delta
int frame_delta static
Referenced by network_free_frame_event_list(), network_hook_connected_receive(), network_init_frame_event_list(), network_prepare_next_frame(), and network_test_delay().
frame_event_list
event_list_state_t* frame_event_list = NULL static
Referenced by network_attach_image(), network_event_record(), network_free_frame_event_list(), network_hook_connected_receive(), network_hook_connected_send(), network_init_frame_event_list(), and network_prepare_next_frame().
frame_to_play
int frame_to_play static
Referenced by network_hook_connected_receive(), and network_prepare_next_frame().
last_received_frame
int last_received_frame static
Referenced by network_client_connect_trap(), and network_server_connect_trap().
listen_socket
vice_network_socket_t* listen_socket static
Referenced by network_disconnect(), network_hook(), and network_start_server().
network_control
int network_control static
Referenced by network_attach_image(), network_control_cmd(), network_event_record(), network_set_mask(), and set_network_control().
network_mode
network_mode_t network_mode = NETWORK_IDLE static
Referenced by network_client_connect_trap(), network_connect_client(), network_connected(), network_disconnect(), network_get_mode(), network_hook(), network_hook_connected_receive(), network_server_connect_trap(), network_start_server(), and network_test_delay().
network_socket
vice_network_socket_t* network_socket static
Referenced by network_client_connect_trap(), network_connect_client(), network_disconnect(), network_hook(), network_hook_connected_receive(), network_hook_connected_send(), network_server_connect_trap(), network_suspend(), and network_test_delay().
res_server_port
int res_server_port static
Referenced by set_server_port().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "NetworkServerPort", 6502, RES_EVENT_NO, NULL,
      &res_server_port, set_server_port, NULL },
    { "NetworkControl",  (  (1 << 0)    |  (1 << 2)    |  (1 << 4)    |  (1 << 3)    | ( (1 << 0)    |  (1 << 1) )   <<  8 ) , RES_EVENT_SAME, NULL,
      &network_control, set_network_control, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by network_resources_init().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "NetworkServerName", "127.0.0.1", RES_EVENT_NO, NULL,
      &server_name, set_server_name, NULL },
    { "NetworkServerBindAddress", "", RES_EVENT_NO, NULL,
      &server_bind_address, set_server_bind_address, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by network_resources_init().
server_bind_address
char* server_bind_address = NULL static
Referenced by network_shutdown(), network_start_server(), and set_server_bind_address().
server_name
char* server_name = NULL static
Referenced by network_connect_client(), network_shutdown(), and set_server_name().
server_port
unsigned short server_port static
Referenced by network_connect_client(), network_start_server(), and set_server_port().
snapshotfilename
char* snapshotfilename static
Referenced by network_client_connect_trap(), network_connect_client(), and network_server_connect_trap().
suspended
int suspended static
Referenced by network_hook_connected_receive(), and network_suspend().