vsid: arch/gtk3/uimachinewindow.h File Reference
uimachinewindow.h File Reference
Native GTK3 main emulator window code.
#include <gtk/gtk.h>
Functions
void ui_machine_window_init (void)
Set up any resources needed to create new machine windows.
void ui_mouse_grab_pointer (void)
Grab the mouse pointer when mouse emulation is enabled.
void ui_mouse_ungrab_pointer (void)
Ungrab the mouse pointer when it was grabbed before.
void ui_set_ignore_mouse_hide (gboolean state)
Set mouse-hide-ignore state.
Detailed Description
Native GTK3 main emulator window code.
Author
Marcus Sutton logge.nosp@m.doub.nosp@m.t@gma.nosp@m.il.c.nosp@m.om
A "machine window" is any window whose primary purpose is to display an emulated screen. It usually also includes a menu bar and a status bar.
Function Documentation
ui_machine_window_init()
void ui_machine_window_init (void)
Set up any resources needed to create new machine windows.
ui_mouse_grab_pointer()
void ui_mouse_grab_pointer (void)
Grab the mouse pointer when mouse emulation is enabled.
Referenced by event_box_cross_cb(), mousedrv_mouse_changed(), and on_focus_in_event().
ui_mouse_ungrab_pointer()
void ui_mouse_ungrab_pointer (void)
Ungrab the mouse pointer when it was grabbed before.
Referenced by mousedrv_mouse_changed(), and on_focus_out_event().
ui_set_ignore_mouse_hide()
void ui_set_ignore_mouse_hide (gboolean state)
Set mouse-hide-ignore state.
Parameters
[in] state enable/disable ignoring the mouse pointer hiding
Referenced by on_focus_in_event(), and on_focus_out_event().