vsid: debug.c File Reference
debug.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "archdep.h"
#include "cmdline.h"
#include "debug.h"
#include "drive.h"
#include "interrupt.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "types.h"
#include "uiapi.h"
#include "util.h"
#include "vice-event.h"
Functions
static int set_do_core_dumps (int val, void *param)
int debug_resources_init (void)
int debug_cmdline_options_init (void)
void debug_set_machine_parameter (unsigned int cycles, unsigned int lines)
Variables
debug_t debug
static const resource_int_t resources_int []
Debug-related resources.
static const cmdline_option_t cmdline_options []
static unsigned int cycles_per_line
static unsigned int screen_lines
Function Documentation
debug_cmdline_options_init()
int debug_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
debug_resources_init()
int debug_resources_init (void)
Referenced by machine_resources_init().
debug_set_machine_parameter()
void debug_set_machine_parameter (unsigned int cycles, unsigned int lines)
Referenced by machine_change_timing().
set_do_core_dumps()
static int set_do_core_dumps (int val, void * param) static
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by debug_cmdline_options_init().
cycles_per_line
unsigned int cycles_per_line static
Referenced by debug_set_machine_parameter().
debug
debug_t debug
Referenced by set_do_core_dumps().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "DoCoreDump", 0, RES_EVENT_NO, NULL,
      &debug.do_core_dumps, set_do_core_dumps, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Debug-related resources.
Referenced by debug_resources_init().
screen_lines
unsigned int screen_lines static
Referenced by debug_set_machine_parameter().