x128: drive/drivecpu.h File Reference
drivecpu.h File Reference
#include "types.h"
Macros
#define OPINFO_NUMBER_MSK 0xff
Masks to extract information.
#define OPINFO_NUMBER(opinfo) ((opinfo) & OPINFO_NUMBER_MSK)
Return the opcode number for ‘opinfo’.
Functions
void drivecpu_setup_context (struct diskunit_context_s *drv, int i)
void drivecpu_init (struct diskunit_context_s *drv, int type)
void drivecpu_reset (struct diskunit_context_s *drv)
called by drive_reset() (via machine_specific_reset())
void drivecpu_sleep (struct diskunit_context_s *drv)
void drivecpu_wake_up (struct diskunit_context_s *drv)
void drivecpu_shutdown (struct diskunit_context_s *drv)
void drivecpu_reset_clk (struct diskunit_context_s *drv)
void drivecpu_trigger_reset (unsigned int dnr)
called by drive_cpu_trigger_reset()
void drivecpu_set_overflow (struct diskunit_context_s *drv)
void drivecpu_execute (struct diskunit_context_s *drv, CLOCK clk_value)
int drivecpu_snapshot_write_module (struct diskunit_context_s *drv, struct snapshot_s *s)
int drivecpu_snapshot_read_module (struct diskunit_context_s *drv, struct snapshot_s *s)
Macro Definition Documentation
OPINFO_NUMBER
#define OPINFO_NUMBER (opinfo) ((opinfo) & OPINFO_NUMBER_MSK)
Return the opcode number for ‘opinfo’.
OPINFO_NUMBER_MSK
#define OPINFO_NUMBER_MSK 0xff
Masks to extract information.
Function Documentation
drivecpu_execute()
void drivecpu_execute (struct diskunit_context_s * drv, CLOCK clk_value)
Include the 6502/6510 CPU emulation core.
Referenced by drive_cpu_execute_one().
drivecpu_init()
void drivecpu_init (diskunit_context_t * drv, int type)
Todo:
check type is already set, and remove type from parameters
Referenced by drive_init(), and drive_set_disk_drive_type().
drivecpu_reset()
void drivecpu_reset (struct diskunit_context_s * drv)
called by drive_reset() (via machine_specific_reset())
Referenced by drive_cpu_trigger_reset(), drivecpu_init(), and drivecpu_snapshot_read_module().
drivecpu_reset_clk()
void drivecpu_reset_clk (struct diskunit_context_s * drv)
Referenced by drivecpu_reset(), and set_drive_true_emulation().
drivecpu_set_overflow()
void drivecpu_set_overflow (struct diskunit_context_s * drv)
Referenced by drive_cpu_set_overflow().
drivecpu_setup_context()
void drivecpu_setup_context (struct diskunit_context_s * drv, int i)
Referenced by drive_set_disk_drive_type(), and drive_setup_context_for_unit().
drivecpu_shutdown()
void drivecpu_shutdown (struct diskunit_context_s * drv)
Referenced by drive_shutdown().
drivecpu_sleep()
void drivecpu_sleep (struct diskunit_context_s * drv) inline
Referenced by drive_disable(), and drivecpu_execute().
drivecpu_snapshot_read_module()
int drivecpu_snapshot_read_module (struct diskunit_context_s * drv, struct snapshot_s * s)
Referenced by drive_snapshot_read_module().
drivecpu_snapshot_write_module()
int drivecpu_snapshot_write_module (struct diskunit_context_s * drv, struct snapshot_s * s)
Referenced by drive_snapshot_write_module().
drivecpu_trigger_reset()
void drivecpu_trigger_reset (unsigned int dnr)
called by drive_cpu_trigger_reset()
drivecpu_wake_up()
void drivecpu_wake_up (struct diskunit_context_s * drv) inline
Todo:
FIXME: this value could break some programs, or be way too high for others. Maybe we should put it into a user-definable resource.
Referenced by drive_enable(), and drivecpu_execute().