x128: arch/gtk3/uitapecreate.c File Reference
uitapecreate.c File Reference
Gtk3 dialog to create and attach a new tape image.
#include "vice.h"
#include <gtk/gtk.h>
#include <string.h>
#include "basewidgets.h"
#include "basedialogs.h"
#include "widgethelpers.h"
#include "filechooserhelpers.h"
#include "util.h"
#include "lib.h"
#include "attach.h"
#include "diskimage.h"
#include "cbmimage.h"
#include "resources.h"
#include "tape.h"
#include "ui.h"
#include "uiapi.h"
#include "uiactions.h"
#include "uitapecreate.h"
Functions
static gboolean create_tape_image (GtkWindow *parent, const char *filename, int port)
forward declarations of functions
static void on_destroy (GtkWidget *dialog, gpointer port)
Handler for the 'destroy' event of the dialog.
static void on_response (GtkDialog *dialog, gint response_id, gpointer data)
Handler for 'response' event of the dialog.
static GtkWidget * create_extra_widget (void)
Create the 'extra' widget for the dialog.
void ui_tape_create_dialog_show (int port)
Create and show 'attach new tape image' dialog.
Variables
static GtkWidget * auto_attach = NULL
Reference to the 'auto-attach' check button.
Detailed Description
Gtk3 dialog to create and attach a new tape image.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_extra_widget()
static GtkWidget * create_extra_widget (void) static
Create the 'extra' widget for the dialog.
Returns
GtkGrid
Referenced by ui_tape_create_dialog_show().
create_tape_image()
static gboolean create_tape_image (GtkWindow * parent, const char * filename, int port) static
forward declarations of functions
Actually create the tape image and attach it.
Parameters
[in] parent parent dialog
[in] filename filename of the new image
[in] port datasette port number (1 or 2)
Returns
bool
Todo:
FIXME: this is nonsense, rename and move elsewhere
Referenced by on_response().
on_destroy()
static void on_destroy (GtkWidget * dialog, gpointer port) static
Handler for the 'destroy' event of the dialog.
Parameters
[in] dialog dialog (unused)
[in] port port number
Referenced by ui_tape_create_dialog_show().
on_response()
static void on_response (GtkDialog * dialog, gint response_id, gpointer data) static
Handler for 'response' event of the dialog.
This handler is called when the user clicks a button in the dialog.
Parameters
[in] dialog the dialog
[in] response_id response ID
[in] data port number (integer, 1 or 2)
Referenced by ui_tape_create_dialog_show().
ui_tape_create_dialog_show()
void ui_tape_create_dialog_show (int port)
Create and show 'attach new tape image' dialog.
Parameters
[in] port port number (1 or 2)
Returns
TRUE
Referenced by tape_create_action().
Variable Documentation
auto_attach
GtkWidget* auto_attach = NULL static
Reference to the 'auto-attach' check button.
Referenced by create_extra_widget(), and create_tape_image().