vsid: raster/raster-changes.h File Reference
raster-changes.h File Reference
#include "raster.h"
#include "viewport.h"
Data Structures
struct raster_changes_integer_action_value_s
struct raster_changes_ptr_action_value_s
union raster_changes_action_value_s
struct raster_changes_action_s
struct raster_changes_s
struct raster_changes_all_s
Macros
#define RASTER_CHANGES_MAX 1024
This should be a lot more than what is actually needed.
Typedefs
typedef enum raster_changes_type_s raster_changes_type_t
typedef struct raster_changes_integer_action_value_s raster_changes_integer_action_value_t
typedef struct raster_changes_ptr_action_value_s raster_changes_ptr_action_value_t
typedef union raster_changes_action_value_s raster_changes_action_value_t
typedef struct raster_changes_action_s raster_changes_action_t
typedef struct raster_changes_s raster_changes_t
typedef struct raster_changes_all_s raster_changes_all_t
Enumerations
enum raster_changes_type_s {
RASTER_CHANGES_TYPE_INT ,
RASTER_CHANGES_TYPE_PTR
}
Functions
void raster_changes_init (struct raster_s *raster)
void raster_changes_shutdown (struct raster_s *raster)
static void raster_changes_apply (raster_changes_t *changes, const unsigned int idx)
Inline functions.
static void raster_changes_remove_all (raster_changes_t *changes)
Remove all the changes in ‘changes’.
static void raster_changes_apply_all (raster_changes_t *changes)
Apply all the changes in ‘changes’.
static void raster_changes_add_int (raster_changes_t *changes, const int where, int *ptr, const int new_value)
Add an int change.
static void raster_changes_add_sorted_int (raster_changes_t *changes, const int where, int *ptr, const int new_value)
Add an int change in correct order.
static void raster_changes_add_ptr (raster_changes_t *changes, const int where, void **ptr, void *new_value)
Add a pointer (‘void *’) change.
static void raster_changes_next_line_add_int (raster_t *raster, int *ptr, int new_value)
Inlined functions.
static void raster_changes_next_line_add_ptr (raster_t *raster, void **ptr, void *new_value)
static void raster_changes_foreground_add_int (raster_t *raster, int char_x, int *ptr, int new_value)
static void raster_changes_foreground_add_ptr (raster_t *raster, int char_x, void **ptr, void *new_value)
static void raster_changes_background_add_int (raster_t *raster, int raster_x, int *ptr, int new_value)
static void raster_changes_background_add_ptr (raster_t *raster, int raster_x, void **ptr, void *new_value)
static void raster_changes_border_add_int (raster_t *raster, int raster_x, int *ptr, int new_value)
static void raster_changes_sprites_add_int (raster_t *raster, int raster_x, int *ptr, int new_value)
Macro Definition Documentation
RASTER_CHANGES_MAX
#define RASTER_CHANGES_MAX 1024
This should be a lot more than what is actually needed.
Typedef Documentation
raster_changes_action_t
typedef struct raster_changes_action_s raster_changes_action_t
raster_changes_action_value_t
typedef union raster_changes_action_value_s raster_changes_action_value_t
raster_changes_all_t
typedef struct raster_changes_all_s raster_changes_all_t
raster_changes_integer_action_value_t
typedef struct raster_changes_integer_action_value_s raster_changes_integer_action_value_t
raster_changes_ptr_action_value_t
typedef struct raster_changes_ptr_action_value_s raster_changes_ptr_action_value_t
raster_changes_t
typedef struct raster_changes_s raster_changes_t
raster_changes_type_t
typedef enum raster_changes_type_s raster_changes_type_t
Enumeration Type Documentation
raster_changes_type_s
enum raster_changes_type_s
Enumerator
RASTER_CHANGES_TYPE_INT
RASTER_CHANGES_TYPE_PTR
Function Documentation
raster_changes_add_int()
static void raster_changes_add_int (raster_changes_t * changes, const int where, int * ptr, const int new_value) inline static
Add an int change.
Referenced by raster_changes_background_add_int(), raster_changes_border_add_int(), raster_changes_foreground_add_int(), and raster_changes_next_line_add_int().
raster_changes_add_ptr()
static void raster_changes_add_ptr (raster_changes_t * changes, const int where, void ** ptr, void * new_value) inline static
Add a pointer (‘void *’) change.
Referenced by raster_changes_background_add_ptr(), raster_changes_foreground_add_ptr(), and raster_changes_next_line_add_ptr().
raster_changes_add_sorted_int()
static void raster_changes_add_sorted_int (raster_changes_t * changes, const int where, int * ptr, const int new_value) inline static
Add an int change in correct order.
Referenced by raster_changes_sprites_add_int().
raster_changes_apply()
static void raster_changes_apply (raster_changes_t * changes, const unsigned int idx) inline static
Inline functions.
These need to be fast.
Apply change number ‘idx’ in ‘changes’.
Referenced by handle_blank_line(), handle_visible_line_with_changes(), and raster_changes_apply_all().
raster_changes_apply_all()
static void raster_changes_apply_all (raster_changes_t * changes) inline static
Apply all the changes in ‘changes’.
Referenced by handle_blank_line(), and raster_line_emulate().
raster_changes_background_add_int()
static void raster_changes_background_add_int (raster_t * raster, int raster_x, int * ptr, int new_value) inline static
Referenced by check_lateral_border(), d016_store(), d021_store(), ext_background_store(), switch_to_display_state(), and vicii_update_video_mode().
raster_changes_background_add_ptr()
static void raster_changes_background_add_ptr (raster_t * raster, int raster_x, void ** ptr, void * new_value) inline static
raster_changes_border_add_int()
static void raster_changes_border_add_int (raster_t * raster, int raster_x, int * ptr, int new_value) inline static
Referenced by d020_store(), and d03c_store().
raster_changes_foreground_add_int()
static void raster_changes_foreground_add_int (raster_t * raster, int char_x, int * ptr, int new_value) inline static
Referenced by d016_store(), ext_background_store(), switch_to_display_state(), vicii_mem_vbank_39xx_store(), vicii_mem_vbank_3fxx_store(), vicii_update_memory_ptrs(), and vicii_update_video_mode().
raster_changes_foreground_add_ptr()
static void raster_changes_foreground_add_ptr (raster_t * raster, int char_x, void ** ptr, void * new_value) inline static
Referenced by vicii_update_memory_ptrs().
raster_changes_init()
void raster_changes_init (struct raster_s * raster)
Referenced by raster_init().
raster_changes_next_line_add_int()
static void raster_changes_next_line_add_int (raster_t * raster, int * ptr, int new_value) inline static
Inlined functions.
These need to be fast.
Referenced by check_lateral_border(), d01b_store(), raster_changes_background_add_int(), raster_changes_border_add_int(), raster_changes_foreground_add_int(), raster_changes_sprites_add_int(), and vicii_fetch_matrix().
raster_changes_next_line_add_ptr()
static void raster_changes_next_line_add_ptr (raster_t * raster, void ** ptr, void * new_value) inline static
Referenced by raster_changes_background_add_ptr(), raster_changes_foreground_add_ptr(), and vicii_update_memory_ptrs().
raster_changes_remove_all()
static void raster_changes_remove_all (raster_changes_t * changes) inline static
Remove all the changes in ‘changes’.
Referenced by handle_blank_line(), handle_visible_line_with_changes(), raster_changes_apply_all(), and raster_reset().
raster_changes_shutdown()
void raster_changes_shutdown (struct raster_s * raster)
Referenced by raster_shutdown().
raster_changes_sprites_add_int()
static void raster_changes_sprites_add_int (raster_t * raster, int raster_x, int * ptr, int new_value) inline static
Referenced by d016_store(), d01c_store(), d01d_store(), d025_store(), d026_store(), sprite_color_store(), and vicii_sprites_set_x_position().