vsid: video/render1x1.c File Reference
render1x1.c File Reference
#include "vice.h"
#include "render1x1.h"
#include "types.h"
Functions
void render_32_1x1_04 (const video_render_color_tables_t *color_tab, const uint8_t *src, uint8_t *trg, unsigned int width, const unsigned int height, const unsigned int xs, const unsigned int ys, const unsigned int xt, const unsigned int yt, const unsigned int pitchs, const unsigned int pitcht)
16 color 1x1 renderer
Function Documentation
render_32_1x1_04()
void render_32_1x1_04 (const video_render_color_tables_t * color_tab, const uint8_t * src, uint8_t * trg, unsigned int width, const unsigned int height, const unsigned int xs, const unsigned int ys, const unsigned int xt, const unsigned int yt, const unsigned int pitchs, const unsigned int pitcht)
16 color 1x1 renderer
Referenced by video_render_crt_mono_main(), video_render_pal_ntsc_main(), and video_render_rgbi_main().