vsid: diskimage/fsimage-create.c File Reference
fsimage-create.c File Reference
Create disk images on the host file system.
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "archdep.h"
#include "diskconstants.h"
#include "diskimage.h"
#include "fsimage-create.h"
#include "fsimage.h"
#include "gcr.h"
#include "lib.h"
#include "log.h"
#include "types.h"
#include "util.h"
#include "x64.h"
#include "p64.h"
#include "cbmdos.h"
Macros
#define DBG(x)
Functions
static int fsimage_create_dxx (disk_image_t *image)
Create a Dxx disk image on the host file system.
int fsimage_create_dxm (const char *name, const char *diskname, unsigned int type)
Create a DxM disk image on the host file system.
int fsimage_create_dhd (const char *name, const char *diskname, unsigned int type)
Create a DHD (hard)disk image on the host file system.
static int fsimage_create_gcr (disk_image_t *image)
Create a G64 disk image on the host file system.
static int fsimage_create_p64 (disk_image_t *image)
Create a P64 disk image on the host file system.
int fsimage_create (const char *name, unsigned int type)
Create a disk image of type type called name on the host OS.
void fsimage_create_init (void)
Initialize module.
Variables
static log_t createdisk_log = ((log_t)-2)
Log instance for this module.
Detailed Description
Create disk images on the host file system.
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
fsimage_create()
int fsimage_create (const char * name, unsigned int type)
Create a disk image of type type called name on the host OS.
Parameters
[in] name disk image name/path
[in] type disk image type
Returns
0 on success, < 0 on failure
< write mode (binary)
< D9090/D9060
Referenced by disk_image_fsimage_create().
fsimage_create_dhd()
int fsimage_create_dhd (const char * name, const char * diskname, unsigned int type)
Create a DHD (hard)disk image on the host file system.
This handles CMD HD (hard)disk images supported by VICE.
!
Todo:
FIXME: Right now this simply creates a zero-byte file, which then has to be partitioned/formatted using the CMD tools.
!
Todo:
FIXME: Once creating formatted images was implemented, the type and number of params passed to this function perhaps needs to be adjusted. In that case make sure to fix them the entire call chain. Maybe even the UIs will have to be updated so extra parameters can be provided.
Parameters
[in] name disk image name/path
[in] diskname disk name and id
[in] type disk image type
Returns
0 on success, < 0 on failure
< write mode (binary)
< HD in ASCII for CMDHD
Referenced by disk_image_fsimage_create_dhd().
fsimage_create_dxm()
int fsimage_create_dxm (const char * name, const char * diskname, unsigned int type)
Create a DxM disk image on the host file system.
This handles any 'FD2000 or FD4000 disk image supported by VICE.
Parameters
[in] name disk image name/path
[in] diskname disk name and id
[in] type disk image type
Returns
0 on success, < 0 on failure
< write mode (binary)
< D1M image, 81 tracks
< D2M image, 81 tracks
< D4M image, 81 tracks
Referenced by disk_image_fsimage_create_dxm().
fsimage_create_dxx()
static int fsimage_create_dxx (disk_image_t * image) static
Create a Dxx disk image on the host file system.
This handles any 'normal'/non-GCR disk image supported by VICE. The only image contained inside a X64 that is supported is a D64.
Parameters
[in,out] image disk image
Returns
0 on success, < 0 on failure
< D64 image, 35 tracks
< D67 image, 35 tracks DOS1
< D71 image, 70 tracks
< D81 image, 80 tracks
< D80 image, 77 tracks
< D82 image, 77 tracks
< D9090/D9060
< D90 image, 153 tracks, 32 sectors, 6 heads
Referenced by fsimage_create().
fsimage_create_gcr()
static int fsimage_create_gcr (disk_image_t * image) static
Create a G64 disk image on the host file system.
Parameters
[in,out] image disk image
return 0 on success, < 0 on failure
< number of tracks on a standard 1541 floppy
< maximum number of accessible tracks for a 1541 drive: not all 1541 drives can do this
Todo:
FIXME: why is NUM_TRACKS_1571 different?
Todo:
FIXME: why is MAX_TRACKS_1571 different?
Referenced by fsimage_create().
fsimage_create_init()
void fsimage_create_init (void)
Initialize module.
In this case: just open a log
Referenced by disk_image_init().
fsimage_create_p64()
static int fsimage_create_p64 (disk_image_t * image) static
Create a P64 disk image on the host file system.
Parameters
[in,out] image disk image
Returns
0 on success, < 0 on failure
< number of tracks on a standard 1541 floppy
Referenced by fsimage_create().
Variable Documentation
createdisk_log
log_t createdisk_log = ((log_t)-2) static
Log instance for this module.
Referenced by fsimage_create(), fsimage_create_dhd(), fsimage_create_dxm(), fsimage_create_dxx(), fsimage_create_gcr(), fsimage_create_init(), and fsimage_create_p64().