vsid: c64/c64parallel.c File Reference
c64parallel.c File Reference
#include "vice.h"
#include "c64.h"
#include "c64parallel.h"
#include "cia.h"
#include "dolphindos3.h"
#include "drive.h"
#include "drivetypes.h"
#include "iecdrive.h"
#include "joyport.h"
#include "log.h"
#include "maincpu.h"
#include "types.h"
#include "userport.h"
#include "via.h"
Macros
#define DBG(x)
define for debug messages
#define PC_PORT_STANDARD 0
#define PC_PORT_FORMEL64 1
#define PC_PORT_NUM 2
Functions
static uint8_t parallel_cable_value (int type)
static void userport_par_cable_store_pbx (uint8_t data, int pulse)
Some prototypes are needed.
static uint8_t userport_par_cable_read_pbx (uint8_t orig)
static int userport_par_cable_enable (int value)
int parallel_cable_cpu_resources_init (void)
void parallel_cable_drive_write (int type, uint8_t data, int handshake, unsigned int dnr)
uint8_t parallel_cable_drive_read (int type, int handshake)
void parallel_cable_cpu_execute (int type)
void parallel_cable_cpu_write (int type, uint8_t data)
uint8_t parallel_cable_cpu_read (int type, uint8_t data)
void parallel_cable_cpu_pulse (int type)
void parallel_cable_cpu_undump (int type, uint8_t data)
Variables
static uint8_t parallel_cable_drive_value [4] = { 0xff, 0xff, 0xff, 0xff }
static uint8_t parallel_cable_cpu_value [2] = { 0xff, 0xff }
static int parallel_cable_enabled = 0
static const int portmap [5]
static userport_device_t par_cable_device
Macro Definition Documentation
DBG
#define DBG (x)
define for debug messages
PC_PORT_FORMEL64
#define PC_PORT_FORMEL64 1
PC_PORT_NUM
#define PC_PORT_NUM 2
PC_PORT_STANDARD
#define PC_PORT_STANDARD 0
Function Documentation
parallel_cable_cpu_execute()
void parallel_cable_cpu_execute (int type)
Referenced by parallel_cable_cpu_pulse(), parallel_cable_cpu_read(), parallel_cable_cpu_write(), and read_ciaicr().
parallel_cable_cpu_pulse()
void parallel_cable_cpu_pulse (int type)
< dolphin-dos 3 userport cable
< formel 64 cartridge
< 21 second backup userport cable
Todo:
FIXME: don't do this for the 21.sec cable
Referenced by userport_par_cable_store_pbx().
parallel_cable_cpu_read()
uint8_t parallel_cable_cpu_read (int type, uint8_t data)
Referenced by userport_par_cable_read_pbx().
parallel_cable_cpu_resources_init()
int parallel_cable_cpu_resources_init (void)
Referenced by machine_resources_init().
parallel_cable_cpu_undump()
void parallel_cable_cpu_undump (int type, uint8_t data)
Referenced by undump_ciapb().
parallel_cable_cpu_write()
void parallel_cable_cpu_write (int type, uint8_t data)
Referenced by userport_par_cable_store_pbx().
parallel_cable_drive_read()
uint8_t parallel_cable_drive_read (int type, int handshake)
Referenced by read_ciapb(), and read_pra().
parallel_cable_drive_write()
void parallel_cable_drive_write (int type, uint8_t data, int handshake, unsigned int dnr)
< write data, set flag (cia2)
< set flag (cia2)
< write data, set flag (cia2)
< write data
Referenced by drive_snapshot_read_module(), pulse_ciapc(), store_ciapb(), store_pra(), undump_ciapb(), and undump_pra().
parallel_cable_value()
static uint8_t parallel_cable_value (int type) static
Referenced by parallel_cable_cpu_read(), and parallel_cable_drive_read().
userport_par_cable_enable()
static int userport_par_cable_enable (int value) static
userport_par_cable_read_pbx()
static uint8_t userport_par_cable_read_pbx (uint8_t orig) static
< speed-dos userport cable
userport_par_cable_store_pbx()
static void userport_par_cable_store_pbx (uint8_t data, int pulse) static
Some prototypes are needed.
< speed-dos userport cable
< speed-dos userport cable
Variable Documentation
par_cable_device
userport_device_t par_cable_device static
Initial value:
= {
    "Userport parallel drive cable",
    JOYSTICK_ADAPTER_ID_NONE,
    USERPORT_DEVICE_TYPE_DRIVE_PAR_CABLE,
    userport_par_cable_enable,
    userport_par_cable_read_pbx,
    userport_par_cable_store_pbx,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
}
Referenced by parallel_cable_cpu_resources_init().
parallel_cable_cpu_value
uint8_t parallel_cable_cpu_value[2] = { 0xff, 0xff } static
Referenced by parallel_cable_cpu_undump(), parallel_cable_cpu_write(), and parallel_cable_value().
parallel_cable_drive_value
uint8_t parallel_cable_drive_value[4] = { 0xff, 0xff, 0xff, 0xff } static
Referenced by parallel_cable_drive_write(), and parallel_cable_value().
parallel_cable_enabled
int parallel_cable_enabled = 0 static
Referenced by userport_par_cable_enable().
portmap
const int portmap[5] static
Initial value:
= {
     0 ,
     0 ,
     0 ,
     1 ,
     0 ,
}
Referenced by parallel_cable_cpu_execute(), parallel_cable_cpu_pulse(), parallel_cable_cpu_read(), parallel_cable_cpu_undump(), parallel_cable_cpu_write(), parallel_cable_drive_read(), parallel_cable_drive_write(), and parallel_cable_value().