x128: c128/c128cart.h File Reference
c128cart.h File Reference
#include "types.h"
Macros
#define EXTERNAL_FUNCTION_ROM_SIZE 0x8000
Image of the external function ROM.
#define EXTERNAL_FUNCTION_ROM_BANKS 0x40
max: "Magic Desk 128" has 64
Functions
int c128cartridge_cmdline_options_init (void)
int c128cartridge_resources_init (void)
void c128cartridge_resources_shutdown (void)
void c128cartridge_setup_interface (void)
only x128 actually implements this function
void external_function_rom_set_bank (int value)
set the bank for generic function rom access
uint8_t external_function_rom_read (uint16_t addr)
ROML and ROMH reads at the cartridge port.
void external_function_rom_store (uint16_t addr, uint8_t value)
ROML and ROMH stores at the cartridge port.
void external_function_top_shared_store (uint16_t addr, uint8_t value)
uint8_t external_function_rom_peek (uint16_t addr)
ROML and ROMH peeks at the cartridge port.
uint8_t c128cartridge_hi_read (uint16_t addr, uint8_t *value)
kernal replacement reads at the cartridge port
uint8_t c128cartridge_hi_store (uint16_t addr, uint8_t value)
kernal replacement store at the cartridge port
uint8_t c128cartridge_basic_hi_read (uint16_t addr, uint8_t *value)
basic hi replacement reads at the cartridge port
uint8_t c128cartridge_basic_hi_store (uint16_t addr, uint8_t value)
basic hi replacement store at the cartridge port
uint8_t c128cartridge_ram_read (uint16_t addr, uint8_t *value)
memory replacement reads at the cartridge port
uint8_t c128cartridge_ram_store (uint16_t addr, uint8_t value)
kernal replacement store at the cartridge port
int c128cartridge_mmu_translate (unsigned int addr, uint8_t **base, int *start, int *limit, int mem_config)
mmu translation: return 0 if no translation applied, leave it for the tables
void c128cartridge_switch_mode (int mode)
notify cartridge of mode change
Variables
uint8_t ext_function_rom [0x8000 *0x40]
Macro Definition Documentation
EXTERNAL_FUNCTION_ROM_BANKS
#define EXTERNAL_FUNCTION_ROM_BANKS 0x40
max: "Magic Desk 128" has 64
EXTERNAL_FUNCTION_ROM_SIZE
#define EXTERNAL_FUNCTION_ROM_SIZE 0x8000
Image of the external function ROM.
Function Documentation
c128cartridge_basic_hi_read()
uint8_t c128cartridge_basic_hi_read (uint16_t addr, uint8_t * value)
basic hi replacement reads at the cartridge port
< ltkernal.c
Referenced by basic_hi_peek(), and basic_hi_read().
c128cartridge_basic_hi_store()
uint8_t c128cartridge_basic_hi_store (uint16_t addr, uint8_t value)
basic hi replacement store at the cartridge port
< ltkernal.c
Referenced by basic_hi_store().
c128cartridge_cmdline_options_init()
int c128cartridge_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
c128cartridge_hi_read()
uint8_t c128cartridge_hi_read (uint16_t addr, uint8_t * value)
kernal replacement reads at the cartridge port
< ramlink.c
< ltkernal.c
Referenced by hi_peek(), and hi_read().
c128cartridge_hi_store()
uint8_t c128cartridge_hi_store (uint16_t addr, uint8_t value)
kernal replacement store at the cartridge port
< ltkernal.c
Referenced by hi_store().
c128cartridge_mmu_translate()
int c128cartridge_mmu_translate (unsigned int addr, uint8_t ** base, int * start, int * limit, int mem_config)
mmu translation: return 0 if no translation applied, leave it for the tables
< ramlink.c
< ltkernal.c
Referenced by mem_mmu_translate().
c128cartridge_ram_read()
uint8_t c128cartridge_ram_read (uint16_t addr, uint8_t * value)
memory replacement reads at the cartridge port
< ltkernal.c
Referenced by ram_peek(), and ram_read().
c128cartridge_ram_store()
uint8_t c128cartridge_ram_store (uint16_t addr, uint8_t value)
kernal replacement store at the cartridge port
< ltkernal.c
Referenced by ram_store().
c128cartridge_resources_init()
int c128cartridge_resources_init (void)
Referenced by machine_resources_init().
c128cartridge_resources_shutdown()
void c128cartridge_resources_shutdown (void)
c128cartridge_setup_interface()
void c128cartridge_setup_interface (void)
only x128 actually implements this function
Referenced by machine_resources_init().
c128cartridge_switch_mode()
void c128cartridge_switch_mode (int mode)
notify cartridge of mode change
< ramlink.c
< ltkernal.c
< mmcreplay.c, ser-eeprom.c, spi-sdcard.c
Referenced by mmu_reset(), and mmu_store().
external_function_rom_peek()
uint8_t external_function_rom_peek (uint16_t addr)
ROML and ROMH peeks at the cartridge port.
Todo:
FIXME: What should we return here? is vicii_read_phi1() safe for a peek?
< ramlink.c
< cartconv: last cartridge in list
< from CRT ID to internal ID
Todo:
FIXME: gmod2 needs a peek
val = c128gmod2_roml_peek(addr);
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< mmcreplay.c, ser-eeprom.c, spi-sdcard.c
< ltkernal.c
Referenced by mem_bank_peek(), mem_peek_with_config_c128(), z80mem_chargen_rom_area_peek(), z80mem_editor_rom_area_peek(), z80mem_hi_rom_area_peek(), and z80mem_mid_rom_area_peek().
external_function_rom_read()
uint8_t external_function_rom_read (uint16_t addr)
ROML and ROMH reads at the cartridge port.
< ramlink.c
< cartconv: last cartridge in list
< from CRT ID to internal ID
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< mmcreplay.c, ser-eeprom.c, spi-sdcard.c
< ltkernal.c
Referenced by c128meminit(), mem_bank_read(), mmu_ffxx_read(), z80mem_chargen_rom_area_read(), z80mem_editor_rom_area_read(), z80mem_hi_rom_area_read(), and z80mem_mid_rom_area_read().
external_function_rom_set_bank()
void external_function_rom_set_bank (int value)
set the bank for generic function rom access
Referenced by c128comal80_io1_store(), c128comal80_reset(), magicdesk128_io1_read(), magicdesk128_io1_store(), and magicdesk128_reset().
external_function_rom_store()
void external_function_rom_store (uint16_t addr, uint8_t value)
ROML and ROMH stores at the cartridge port.
< cartconv: last cartridge in list
< from CRT ID to internal ID
< ltkernal.c
< external function rom
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
< cartconv: last cartridge in list
< from CRT ID to internal ID
Referenced by c128meminit(), z80mem_chargen_rom_area_store(), z80mem_editor_rom_area_store(), z80mem_hi_rom_area_store(), and z80mem_mid_rom_area_store().
external_function_top_shared_store()
void external_function_top_shared_store (uint16_t addr, uint8_t value)
Referenced by c128meminit().
Variable Documentation
ext_function_rom
uint8_t ext_function_rom[0x8000 * 0x40] extern
Referenced by c128cartridge_detach_image(), c128comal80_config_setup(), c128comal80_io1_peek(), c128comal80_io2_peek(), c128comal80_io2_read(), c128comal80_snapshot_read_module(), c128comal80_snapshot_write_module(), c128generic_config_setup(), c128generic_snapshot_read_module(), c128generic_snapshot_write_module(), c128gmod2_bin_save(), c128gmod2_config_setup(), c128gmod2_crt_save(), c128gmod2_snapshot_read_module(), external_function_rom_peek(), external_function_rom_read(), magicdesk128_config_setup(), partner128_config_setup(), partner128_io1_peek(), partner128_io1_read(), warpspeed128_config_setup(), warpspeed128_io1_peek(), warpspeed128_io1_read(), warpspeed128_io2_peek(), warpspeed128_io2_read(), warpspeed128_snapshot_read_module(), and warpspeed128_snapshot_write_module().