vsid: rs232drv/rsuser.h File Reference
rsuser.h File Reference
#include "types.h"
Macros
#define TXD_OUT 0x04
PA2.
#define RXD_IN 0x01
PB0 (also connected to !FLAG2)
#define RTS_OUT 0x02
PB1.
#define DTR_OUT 0x04
PB2.
#define OH_OUT 0x20
PB5 ON_HOOK output to some Commodore modems and clones.
#define RI_IN 0x08
PB3.
#define DCD_IN 0x10
PB4.
#define CTS_IN 0x40
PB6.
#define DSR_IN 0x80
PB7.
#define RS_USER_DEVICE_1 0
#define RS_USER_DEVICE_2 1
#define RS_USER_DEVICE_3 2
#define RS_USER_DEVICE_4 3
Functions
void rsuser_init (long cycles_per_sec, void(*start_bit_trigger)(void), void(*byte_rx_func)(uint8_t))
void rsuser_change_timing (long cycles_per_sec)
int rsuser_resources_init (void)
int rsuser_cmdline_options_init (void)
Macro Definition Documentation
CTS_IN
#define CTS_IN 0x40
PB6.
DCD_IN
#define DCD_IN 0x10
PB4.
DSR_IN
#define DSR_IN 0x80
PB7.
DTR_OUT
#define DTR_OUT 0x04
PB2.
OH_OUT
#define OH_OUT 0x20
PB5 ON_HOOK output to some Commodore modems and clones.
RI_IN
#define RI_IN 0x08
PB3.
RS_USER_DEVICE_1
#define RS_USER_DEVICE_1 0
RS_USER_DEVICE_2
#define RS_USER_DEVICE_2 1
RS_USER_DEVICE_3
#define RS_USER_DEVICE_3 2
RS_USER_DEVICE_4
#define RS_USER_DEVICE_4 3
RTS_OUT
#define RTS_OUT 0x02
PB1.
RXD_IN
#define RXD_IN 0x01
PB0 (also connected to !FLAG2)
TXD_OUT
#define TXD_OUT 0x04
PA2.
Function Documentation
rsuser_change_timing()
void rsuser_change_timing (long cycles_per_sec)
Referenced by machine_change_timing(), and rsuser_init().
rsuser_cmdline_options_init()
int rsuser_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
rsuser_init()
void rsuser_init (long cycles_per_sec, void(*)(void) start_bit_trigger, void(*)(uint8_t) byte_rx_func)
< PB2
< PB1
Referenced by c64_rsuser_init().
rsuser_resources_init()
int rsuser_resources_init (void)
Referenced by machine_resources_init().