x128: aciacore.c File Reference
aciacore.c File Reference
#include "vice.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "acia.h"
#include "alarm.h"
#include "cmdline.h"
#include "interrupt.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "rs232drv.h"
#include "rs232.h"
#include "snapshot.h"
#include "types.h"
#include "monitor.h"
Data Structures
struct acia_struct
Macros
#define DEBUG_LOG_MESSAGE(_x)
Helper macro for outputting debugging messages.
#define DEBUG_VERBOSE_LOG_MESSAGE(_x)
Helper macro for outputting verbose debugging messages.
#define ACIA_DUMP_VER_MAJOR 1
dump definitions and functions
#define ACIA_DUMP_VER_MINOR 1
the minor version number of the dump data
Typedefs
typedef struct acia_struct acia_type
Enumerations
enum acia_tx_state {
ACIA_TX_STATE_NO_TRANSMIT = 0 ,
ACIA_TX_STATE_TX_STARTED = 1 ,
ACIA_TX_STATE_DR_WRITTEN = 2
}
specify the transmit state the ACIA is currently in
Functions
uint8_t myacia_read (uint16_t addr)
define if you want "normal" debugging output
static void acia_preinit (void)
static void int_acia_tx (CLOCK offset, void *data)
alarm functions
static void int_acia_rx (CLOCK offset, void *data)
Receive (RX) alarm function.
static int acia_set_device (int val, void *param)
Change the device resource for this ACIA.
static void acia_set_int (int aciairq, unsigned int int_num, int value)
Generate an ACIA interrupt.
static double get_acia_bps (void)
Change the Interrupt resource for this ACIA.
static void set_acia_ticks (void)
set the ticks between characters of the ACIA according to the bps rate
int myacia_init_resources (void)
initialize the ACIA resources
int myacia_init_cmdline_options (void)
initialize the command-line options
static int acia_get_status (void)
auxiliary functions
static void acia_set_handshake_lines (void)
Set the handshake (output) lines to the status of the cmd register.
void myacia_init (void)
initialize the ACIA
void myacia_reset (void)
reset the ACIA
int myacia_snapshot_write_module (snapshot_t *p)
Write the snapshot module for the ACIA.
int myacia_snapshot_read_module (snapshot_t *p)
Read the snapshot module for the ACIA.
void myacia_store (uint16_t addr, uint8_t byte)
write the ACIA register values This function is used to write the ACIA values from the computer.
uint8_t myacia_peek (uint16_t addr)
read the ACIA register values without side effects This function reads the ACIA values, so they can be accessed like an array of bytes.
int acia_dump (void)
Variables
static acia_type acia
static const double acia_bps_table [16]
the bps rates available in the order of the control register
static const double t232_bps_table [4]
the extra bps rates of the turbo232 card
static const resource_int_t resources_int []
Change the emulation mode for this ACIA.
static const cmdline_option_t cmdline_options []
the command-line options available for the ACIA
static const char module_name [] = MYACIA
the name of this module
Detailed Description
Author
Andre Fachat, Spiro Trikaliotis
Template file for ACIA 6551 emulation.
Written by Andre Fachat facha.nosp@m.t@ph.nosp@m.ysik..nosp@m.tu-c.nosp@m.hemni.nosp@m.tz.d.nosp@m.e Spiro Trikaliotis spiro.nosp@m..tri.nosp@m.kalio.nosp@m.tis@.nosp@m.gmx.d.nosp@m.e
This file is part of VICE, the Versatile Commodore Emulator. See README for copyright notice.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
Macro Definition Documentation
ACIA_DUMP_VER_MAJOR
#define ACIA_DUMP_VER_MAJOR 1
dump definitions and functions
the major version number of the dump data
ACIA_DUMP_VER_MINOR
#define ACIA_DUMP_VER_MINOR 1
the minor version number of the dump data
DEBUG_LOG_MESSAGE
#define DEBUG_LOG_MESSAGE (_x)
Helper macro for outputting debugging messages.
DEBUG_VERBOSE_LOG_MESSAGE
#define DEBUG_VERBOSE_LOG_MESSAGE (_x)
Helper macro for outputting verbose debugging messages.
Typedef Documentation
acia_type
typedef struct acia_struct acia_type
Enumeration Type Documentation
acia_tx_state
enum acia_tx_state
specify the transmit state the ACIA is currently in
Remarks
The numerical values must remain as they are! int_acia_tx() relies on them when testing and decrementing the in_tx variable!
Enumerator
ACIA_TX_STATE_NO_TRANSMIT
currently, there is no transmit processed
ACIA_TX_STATE_TX_STARTED
the transmit has already begun
ACIA_TX_STATE_DR_WRITTEN
the data register has been written, but the byte written is not yet in transmit
Function Documentation
acia_dump()
int acia_dump (void)
acia_get_status()
static int acia_get_status (void) static
auxiliary functions
Get the modem status and set the status register accordingly
This function reads the physical modem status lines (DSR, DCD) and sets the emulated ACIA status register accordingly.
Returns
The new value of the status register
Todo:
Changes in DSR and DCD should trigger an interrupt
Referenced by myacia_snapshot_write_module().
acia_preinit()
static void acia_preinit (void) static
< Normal ACIA emulation
Referenced by myacia_init_resources().
acia_set_device()
static int acia_set_device (int val, void * param) static
Change the device resource for this ACIA.
Parameters
val The device no. to use for this ACIA
param Unused
Returns
0 on success, -1 on error.
Remarks
This function is called whenever the resource MYACIA "Dev" is changed.
acia_set_handshake_lines()
static void acia_set_handshake_lines (void) static
Set the handshake (output) lines to the status of the cmd register.
This function sets the physical handshake lines accordingly to the state of the emulated ACIA cmd register.
Referenced by myacia_snapshot_read_module(), and myacia_store().
acia_set_int()
static void acia_set_int (int aciairq, unsigned int int_num, int value) static
Generate an ACIA interrupt.
This function is used to generate an ACIA interrupt. Depending upon the type of interrupt to generate (IK_NONE, IK_IRQ or IK_NMI), the appropriate function is called (or no function at all if the interrupt type is set to IK_NONE).
Parameters
aciairq The interrupt type to use. Must be one of IK_NONE, IK_IRQ or IK_NMI.
int_num the (internal) number for the ACIA interrupt as returned by interrupt_cpu_status_int_new()
value The state to set this interrupt to.
Remarks
In case of aciairq = IK_NONE, value must be IK_NONE, too.
In case of aciairq = IK_IRQ, value must be one of IK_IRQ or IK_NONE.
In case of aciairq = IK_NMI, value must be one of IK_NMI or IK_NONE.
Referenced by int_acia_rx(), int_acia_tx(), myacia_reset(), and myacia_store().
get_acia_bps()
static double get_acia_bps (void) static
Change the Interrupt resource for this ACIA.
Parameters
new_irq_res The interrupt type to use: 0 = none, 1 = NMI, 2 = IRQ.
param Unused
Returns
0 on success, -1 on error.
Remarks
This function is called whenever the resource MYACIA "Irq" is changed.
get the bps rate ("baud rate") of the ACIA
Returns
the bps rate the acia is currently programmed to.
< Normal ACIA emulation
< Swiftlink ACIA emulation, baud rates are doubled
Referenced by acia_dump(), and set_acia_ticks().
int_acia_rx()
static void int_acia_rx (CLOCK offset, void * data) static
Receive (RX) alarm function.
This function is called when the receive alarm fires. It checks if there is any data received. If there is some, this data is made available in the ACIA data register (DR)
Parameters
offset The clock offset this alarm is executed at.
The current implementation of the emulation core does not allow to guarantee that the alarm will fire exactly at the time it was scheduled at. The offset tells the alarm function how many cycles have passed since the time the alarm was scheduled to fire. Thus, (myclk - offset) yiels the clock count which the alarm was scheduled to.
Parameters
data Additional data defined in the call to alarm_new(). For the acia implementation, this is always NULL.
Remarks
The alarm is re-scheduled for the time when the reception has completed.
Referenced by myacia_init().
int_acia_tx()
static void int_acia_tx (CLOCK offset, void * data) static
alarm functions
Transmit (TX) alarm function
This function is called when the transmit alarm fires. It checks if there is any data to send. If there is some, this data is sent to the physical RS232 device.
Parameters
offset The clock offset this alarm is executed at.
The current implementation of the emulation core does not allow to guarantee that the alarm will fire exactly at the time it was scheduled at. The offset tells the alarm function how many cycles have passed since the time the alarm was scheduled to fire. Thus, (myclk - offset) yiels the clock count which the alarm was scheduled to.
Parameters
data Additional data defined in the call to alarm_new(). For the acia implementation, this is always NULL.
Remarks
If we just transmitted a value, the alarm is re-scheduled for the time when the transmission has completed. This way, we ensure that we do not send out faster than a real ACIA could do.
Referenced by myacia_init().
myacia_init()
void myacia_init (void)
initialize the ACIA
myacia_init_cmdline_options()
int myacia_init_cmdline_options (void)
initialize the command-line options
Returns
0 on success, else -1.
Remarks
Registers the command-line options
myacia_init_resources()
int myacia_init_resources (void)
initialize the ACIA resources
Returns
0 on success, else -1.
Remarks
Registers the integer resources
< Normal ACIA emulation
myacia_peek()
uint8_t myacia_peek (uint16_t addr)
read the ACIA register values without side effects This function reads the ACIA values, so they can be accessed like an array of bytes.
No side-effects that would be performed if a real read access would occur are executed.
Parameters
addr The address of the ACIA register to read
Returns
The value the register has
Referenced by acia_dump().
myacia_read()
uint8_t myacia_read (uint16_t addr)
define if you want "normal" debugging output
read the ACIA register values
define if you want very verbose debugging output.
This function is used to read the ACIA values from the computer. All side-effects are executed.
Parameters
addr The address of the ACIA register to read
Returns
The value the register has
myacia_reset()
void myacia_reset (void)
reset the ACIA
myacia_snapshot_read_module()
int myacia_snapshot_read_module (snapshot_t * p)
Read the snapshot module for the ACIA.
Parameters
p Pointer to the snapshot data
Returns
0 on success, -1 on error
Remarks
The format has been extended in VICE 2.0.9. However, the version number remained the same. This function tries to read the new values. If they are not available, it mimics the old behaviour and reports success, anyway.
It is unclear if it is sensible to mimic the old behaviour, as the old implementation was severely broken.
< the major version number of the dump data
< the minor version number of the dump data
myacia_snapshot_write_module()
int myacia_snapshot_write_module (snapshot_t * p)
Write the snapshot module for the ACIA.
Parameters
p Pointer to the snapshot data
Returns
0 on success, -1 on error
Remarks
Is it sensible to put the ACIA into a snapshot? It is unlikely the "other side" of the connection will be able to handle this case if a transfer was under way, anyway.
Todo:
FIXME!!! Error check.
Todo:
FIXME!!! If no connection, emulate carrier lost or so.
< the major version number of the dump data
< the minor version number of the dump data
myacia_store()
void myacia_store (uint16_t addr, uint8_t byte)
write the ACIA register values This function is used to write the ACIA values from the computer.
Parameters
addr The address of the ACIA register to write
byte The value to set the register to
Referenced by myacia_store().
set_acia_ticks()
static void set_acia_ticks (void) static
set the ticks between characters of the ACIA according to the bps rate
Set the ticks that will pass for one character to be transferred according to the current ACIA settings.
Referenced by acia_set_handshake_lines(), myacia_reset(), myacia_snapshot_read_module(), and myacia_store().
Variable Documentation
acia
acia_type acia static
Initial value:
= { NULL, NULL, 0, 0, 0, (enum acia_tx_state)0,
                          0, 0, 0, 0, 0, 0, 0, 0xff, 0, 0, 0, 0, 0, 0, 0,
                          (enum cpu_int)0, 0, 0, (enum rs232handshake_out)0 }
Referenced by acia_dump(), acia_get_status(), acia_preinit(), acia_set_device(), acia_set_handshake_lines(), acia_set_int(), get_acia_bps(), int_acia_rx(), int_acia_tx(), myacia_init(), myacia_init_resources(), myacia_peek(), myacia_read(), myacia_reset(), myacia_snapshot_read_module(), myacia_snapshot_write_module(), myacia_store(), and set_acia_ticks().
acia_bps_table
const double acia_bps_table[16] static
Initial value:
= {
    10, 50, 75, 109.92, 134.58, 150, 300, 600, 1200, 1800,
    2400, 3600, 4800, 7200, 9600, 19200
}
the bps rates available in the order of the control register
This array is used to set the bps rate of the 6551. For this, the values are set in the same order as they are defined in the CONTROL register.
Remarks
the first value is bogus. It should be 16*external clock.
swiftlink and turbo232 modes use the same table except they double the values.
Referenced by get_acia_bps().
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-myaciadev", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, MYACIA "Dev", NULL,
      "<0-3>", "Specify RS232 device this ACIA should work on" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
the command-line options available for the ACIA
Referenced by myacia_init_cmdline_options().
module_name
const char module_name[] = MYACIA static
the name of this module
Referenced by myacia_snapshot_read_module(), and myacia_snapshot_write_module().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { MYACIA "Dev", MyDevice, RES_EVENT_NO, NULL,
      &acia.device, acia_set_device, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Change the emulation mode for this ACIA.
Parameters
new_mode The exact device type to emulate. ACIA_MODE_NORMAL for a "normal" 6551 device, ACIA_MODE_SWIFTLINK for a SwiftLink device, or ACIA_MODE_TURBO232 for a Turbo232 device.
param Unused
Returns
0 on success, -1 on error.
Remarks
This function is called whenever the resource MYACIA "Mode" is changed.
integer resources used by the ACIA module
Referenced by myacia_init_resources().
t232_bps_table
const double t232_bps_table[4] static
Initial value:
= {
    230400, 115200, 57600, 28800
}
the extra bps rates of the turbo232 card
This lists the extra bps rates available in the turbo232 card. In the turbo232 card, if the CTRL register is set to the bps rate of 10 bps, the extended ctrl register determines the bps rates. The extended ctrl register is used as an index in this table to get the bps rate.
Remarks
the last value is a bogus value and in the real module that value is reserved for future use.
Referenced by get_acia_bps().