vsid: arch/gtk3/widgets/vsidplaylistadddialog.h File Reference
vsidplaylistadddialog.h File Reference
GTK3 Add SID files dialog for the playlist widget - header.
#include <gtk/gtk.h>
Functions
void vsid_playlist_add_dialog_exec (void(*callback)(GSList *files))
Run dialog to add SID files to the playlist.
void vsid_playlist_add_dialog_free (void)
Free memory used by the lastdir.c functions.
Detailed Description
GTK3 Add SID files dialog for the playlist widget - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
vsid_playlist_add_dialog_exec()
void vsid_playlist_add_dialog_exec (void(*)(GSList *files) callback)
Run dialog to add SID files to the playlist.
Parameters
[in] callback function accepting a list of selected files
Referenced by open_add_dialog(), and vsid_playlist_add().
vsid_playlist_add_dialog_free()
void vsid_playlist_add_dialog_free (void)
Free memory used by the lastdir.c functions.
Frees the last_used_dir and last_used_file strings.
Called on emulator shutdown.
Referenced by on_destroy().