x128: serial/serial-trap.c File Reference
serial-trap.c File Reference
#include "vice.h"
#include <stdio.h>
#include "iecbus.h"
#include "maincpu.h"
#include "mem.h"
#include "serial-iec-bus.h"
#include "serial-iec-device.h"
#include "serial-trap.h"
#include "serial.h"
#include "types.h"
Macros
#define DBG(x)
Will be removed once serial.c is clean.
#define MAX_DEVICES 15 /*! \todo FIXME: is there another constant we can use instead? */
#define BSOUR 0x95
Buffered Character for IEEE Bus.
#define DEVNR_MASK 0x0F
should be 0x1F
#define SA_MASK 0x0F
#define LISTEN 0x20
bits 7=0 6,5 dev=4,3,2,1,0
#define TALK 0x40
#define SECONDARY 0x60
#define CLOSE 0xE0
bits 7=1 6,5,4 sec=3,2,1,0
#define OPEN 0xF0
#define UNLISTEN 0x3f
bits 7=0 6,5 dev=4,3,2,1,0=31
#define UNTALK 0x5f
TALK with dev=31 correct?
#define IS_PRINTER(d) (((d) & DEVNR_MASK) >= 4 && ((d) & DEVNR_MASK) <= 7)
Functions
static void serial_set_st (uint8_t st)
static uint8_t serial_get_st (void)
static void send_listen_talk_secondary (uint8_t b)
static int device_uses_serial_traps (int device)
int serial_trap_attention (void)
int serial_trap_send (void)
Send one byte on the serial bus.
int serial_trap_receive (void)
Receive one byte from the serial bus.
int serial_trap_ready (void)
int serial_resources_init (void)
int serial_cmdline_options_init (void)
void serial_trap_init (uint16_t tmpin)
void serial_traps_reset (void)
called by machine_specific_reset()
void serial_trap_eof_callback_set (void(*func)(void))
Specify a function to call when EOF happens in ‘serialreceivebyte()’.
void serial_trap_attention_callback_set (void(*func)(void))
Specify a function to call when the ‘serialattention()’ trap is called.
void serial_trap_truedrive_set (unsigned int unit, unsigned int flag)
Variables
int traps_enabled_device [15]
static uint16_t tmp_in
Address of serial TMP register.
static uint8_t TrapDevice
On which channel did listen happen to?
static uint8_t TrapSecondary
static int ActiveDevice = -1
static void(* eof_callback_func)(void)
Function to call when EOF happens in ‘serialreceivebyte()’.
static void(* attention_callback_func)(void)
Function to call when the ‘serialattention()’ trap is called.
static unsigned int serial_truedrive [16]
Macro Definition Documentation
BSOUR
#define BSOUR 0x95
Buffered Character for IEEE Bus.
CLOSE
#define CLOSE 0xE0
bits 7=1 6,5,4 sec=3,2,1,0
DBG
#define DBG (x)
Will be removed once serial.c is clean.
DEVNR_MASK
#define DEVNR_MASK 0x0F
should be 0x1F
Todo:
FIXME: code here assumes 4 bits for device number; should be 5?
IS_PRINTER
#define IS_PRINTER (d) (((d) & DEVNR_MASK) >= 4 && ((d) & DEVNR_MASK) <= 7)
LISTEN
#define LISTEN 0x20
bits 7=0 6,5 dev=4,3,2,1,0
MAX_DEVICES
#define MAX_DEVICES 15 /*! \todo FIXME: is there another constant we can use instead? */
OPEN
#define OPEN 0xF0
SA_MASK
#define SA_MASK 0x0F
SECONDARY
#define SECONDARY 0x60
TALK
#define TALK 0x40
UNLISTEN
#define UNLISTEN 0x3f
bits 7=0 6,5 dev=4,3,2,1,0=31
LISTEN with dev=31 correct?
UNTALK
#define UNTALK 0x5f
TALK with dev=31 correct?
Function Documentation
device_uses_serial_traps()
static int device_uses_serial_traps (int device) static
Todo:
FIXME: the printers are strange
< should be 0x1F
< should be 0x1F
Referenced by serial_trap_attention(), serial_trap_ready(), serial_trap_receive(), and serial_trap_send().
send_listen_talk_secondary()
static void send_listen_talk_secondary (uint8_t b) static
Referenced by serial_trap_attention(), serial_trap_receive(), and serial_trap_send().
serial_cmdline_options_init()
int serial_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
serial_get_st()
static uint8_t serial_get_st (void) static
Referenced by serial_trap_receive().
serial_resources_init()
int serial_resources_init (void)
Referenced by machine_resources_init().
serial_set_st()
static void serial_set_st (uint8_t st) static
Referenced by send_listen_talk_secondary(), serial_trap_attention(), serial_trap_receive(), and serial_trap_send().
serial_trap_attention()
int serial_trap_attention (void)
< Buffered Character for IEEE Bus
< LISTEN with dev=31 correct?
< TALK with dev=31 correct?
< should be 0x1F
< LISTEN with dev=31 correct?
< TALK with dev=31 correct?
< LISTEN with dev=31 correct?
< TALK with dev=31 correct?
< should be 0x1F
serial_trap_attention_callback_set()
void serial_trap_attention_callback_set (void(*)(void) func)
Specify a function to call when the ‘serialattention()’ trap is called.
serial_trap_eof_callback_set()
void serial_trap_eof_callback_set (void(*)(void) func)
Specify a function to call when EOF happens in ‘serialreceivebyte()’.
serial_trap_init()
void serial_trap_init (uint16_t tmpin)
Referenced by machine_specific_init().
serial_trap_ready()
int serial_trap_ready (void)
serial_trap_receive()
int serial_trap_receive (void)
Receive one byte from the serial bus.
serial_trap_send()
int serial_trap_send (void)
Send one byte on the serial bus.
< Buffered Character for IEEE Bus
serial_trap_truedrive_set()
void serial_trap_truedrive_set (unsigned int unit, unsigned int flag)
serial_traps_reset()
void serial_traps_reset (void)
called by machine_specific_reset()
Todo:
FIXME: bad name, this function is basically the main/top entry point for doing a IEC reset that distributes to all drives. It does however NOT reset the true-drive emulated drive CPUs (that is done in drive_reset)
Referenced by machine_specific_reset().
Variable Documentation
ActiveDevice
int ActiveDevice = -1 static
Referenced by serial_trap_attention(), serial_trap_ready(), serial_trap_receive(), and serial_trap_send().
attention_callback_func
void(* attention_callback_func) (void) (void) static
Function to call when the ‘serialattention()’ trap is called.
Referenced by serial_trap_attention(), and serial_trap_attention_callback_set().
eof_callback_func
void(* eof_callback_func) (void) (void) static
Function to call when EOF happens in ‘serialreceivebyte()’.
Referenced by serial_trap_eof_callback_set(), and serial_trap_receive().
serial_truedrive
unsigned int serial_truedrive[16] static
Referenced by device_uses_serial_traps(), and serial_trap_truedrive_set().
tmp_in
uint16_t tmp_in static
Address of serial TMP register.
Referenced by serial_trap_init(), and serial_trap_receive().
TrapDevice
uint8_t TrapDevice static
On which channel did listen happen to?
Referenced by send_listen_talk_secondary(), serial_trap_attention(), serial_trap_ready(), serial_trap_receive(), and serial_trap_send().
traps_enabled_device
int traps_enabled_device[15] extern
Referenced by device_uses_serial_traps(), and set_traps_enabled().
TrapSecondary
uint8_t TrapSecondary static
Referenced by send_listen_talk_secondary(), serial_trap_attention(), serial_trap_receive(), and serial_trap_send().