vsid: arch/gtk3/uisnapshot.c File Reference
uisnapshot.c File Reference
Snapshot dialogs and menu item handlers.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include <stdbool.h>
#include "lib.h"
#include "util.h"
#include "archdep.h"
#include "basewidgets.h"
#include "widgethelpers.h"
#include "debug_gtk3.h"
#include "machine.h"
#include "mainlock.h"
#include "resources.h"
#include "filechooserhelpers.h"
#include "openfiledialog.h"
#include "savefiledialog.h"
#include "selectdirectorydialog.h"
#include "basedialogs.h"
#include "interrupt.h"
#include "vsync.h"
#include "vsyncapi.h"
#include "snapshot.h"
#include "vice-event.h"
#include "uistatusbar.h"
#include "ui.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uisnapshot.h"
Functions
static gchar * create_datetime_string (void)
Create a string in the format 'yyyymmddHHMMss' of the current time.
static char * quicksnap_filename (void)
Construct filename for quickload/quicksave snapshots.
static char * create_proposed_snapshot_name (void)
Create a filename based on the current datetime.
static void save_snapshot_dialog (void)
Show dialog to save a snapshot.
static void load_snapshot_filename_callback (GtkDialog *dialog, gchar *filename, gpointer data)
file-open dialog callback for "Load snapshot file"
static gboolean load_snapshot_trap_impl (gpointer user_data)
load-snapshot handler
static void load_snapshot_trap (uint16_t addr, void *data)
CPU trap handler for the load snapshot dialog.
static gboolean save_snapshot_trap_impl (gpointer user_data)
save-snapshot handler
static void save_snapshot_trap (uint16_t addr, void *data)
CPU trap handler to trigger the Save dialog.
static void quickload_snapshot_trap (uint16_t addr, void *data)
CPU trap handler for the QuickLoad snapshot menu item.
static void quicksave_snapshot_trap (uint16_t addr, void *data)
CPU trap handler for the QuickSave snapshot menu item.
void ui_snapshot_load_snapshot (void)
Display UI to load a snapshot file.
void ui_snapshot_save_snapshot (void)
Display UI to save a snapshot file.
void ui_snapshot_quickload_snapshot (void)
Quicksave snapshot.
void ui_snapshot_quicksave_snapshot (void)
Quicksave snapshot.
Variables
static bool ui_done
Flag indicating the UI is 'done', whatever that means.
Detailed Description
Snapshot dialogs and menu item handlers.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_datetime_string()
static gchar * create_datetime_string (void) static
Create a string in the format 'yyyymmddHHMMss' of the current time.
Returns
string owned by GLib, free with g_free()
Referenced by create_proposed_snapshot_name().
create_proposed_snapshot_name()
static char * create_proposed_snapshot_name (void) static
Create a filename based on the current datetime.
Returns
heap-allocated string, owned by VICE, free with lib_free()
Referenced by save_snapshot_dialog().
load_snapshot_filename_callback()
static void load_snapshot_filename_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
file-open dialog callback for "Load snapshot file"
Parameters
[in,out] dialog file-open dialog
[in,out] filename filename
[in] data extra callback data (unused)
Referenced by load_snapshot_trap_impl().
load_snapshot_trap()
static void load_snapshot_trap (uint16_t addr, void * data) static
CPU trap handler for the load snapshot dialog.
Parameters
[in] addr memory address (unused)
[in] data unused
Referenced by ui_snapshot_load_snapshot().
load_snapshot_trap_impl()
static gboolean load_snapshot_trap_impl (gpointer user_data) static
load-snapshot handler
Parameters
[in] user_data extra callback data (unused)
Returns
FALSE
Todo:
FIXME: shouldn't this return TRUE?
Referenced by load_snapshot_trap(), and ui_snapshot_load_snapshot().
quickload_snapshot_trap()
static void quickload_snapshot_trap (uint16_t addr, void * data) static
CPU trap handler for the QuickLoad snapshot menu item.
Parameters
[in] addr memory address (unused)
[in] data quickload snapshot filename
Referenced by ui_snapshot_quickload_snapshot().
quicksave_snapshot_trap()
static void quicksave_snapshot_trap (uint16_t addr, void * data) static
CPU trap handler for the QuickSave snapshot menu item.
Parameters
[in] addr memory address (unused)
[in] data quicksave snapshot filename
Referenced by ui_snapshot_quicksave_snapshot().
quicksnap_filename()
static char * quicksnap_filename (void) static
Construct filename for quickload/quicksave snapshots.
Returns
filename for the quickload/save file
Note
free after use with lib_free()
Referenced by ui_snapshot_quickload_snapshot(), and ui_snapshot_quicksave_snapshot().
save_snapshot_dialog()
static void save_snapshot_dialog (void) static
Show dialog to save a snapshot.
!
Todo:
FIXME: Why isn't this dialog non-blocking?
Referenced by save_snapshot_trap_impl().
save_snapshot_trap()
static void save_snapshot_trap (uint16_t addr, void * data) static
CPU trap handler to trigger the Save dialog.
Parameters
[in] addr memory address (unused)
[in] data unused
Referenced by ui_snapshot_save_snapshot().
save_snapshot_trap_impl()
static gboolean save_snapshot_trap_impl (gpointer user_data) static
save-snapshot handler
Parameters
[in] user_data extra event data (unused)
Returns
FALSE
Referenced by save_snapshot_trap(), and ui_snapshot_save_snapshot().
ui_snapshot_load_snapshot()
void ui_snapshot_load_snapshot (void)
Display UI to load a snapshot file.
Referenced by snapshot_load_action().
ui_snapshot_quickload_snapshot()
void ui_snapshot_quickload_snapshot (void)
Quicksave snapshot.
Referenced by snapshot_quickload_action().
ui_snapshot_quicksave_snapshot()
void ui_snapshot_quicksave_snapshot (void)
Quicksave snapshot.
Referenced by snapshot_quicksave_action().
ui_snapshot_save_snapshot()
void ui_snapshot_save_snapshot (void)
Display UI to save a snapshot file.
Referenced by snapshot_save_action().
Variable Documentation
ui_done
bool ui_done static
Flag indicating the UI is 'done', whatever that means.
Referenced by load_snapshot_filename_callback(), load_snapshot_trap(), save_snapshot_trap(), and save_snapshot_trap_impl().