x128: arch/gtk3/widgets/settings_model.c File Reference
settings_model.c File Reference
Model settings dialog.
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <gtk/gtk.h>
#include "archdep.h"
#include "c128machinetypewidget.h"
#include "c64dtvmodel.h"
#include "c64model.h"
#include "cbm2hardwiredswitcheswidget.h"
#include "cbm2memorysizewidget.h"
#include "cbm2rammappingwidget.h"
#include "ciamodelwidget.h"
#include "crtcontrolwidget.h"
#include "debug_gtk3.h"
#include "kernalrevisionwidget.h"
#include "machine.h"
#include "machinemodelwidget.h"
#include "machinepowerfrequencywidget.h"
#include "petiosizewidget.h"
#include "petkeyboardtypewidget.h"
#include "petmiscwidget.h"
#include "petmodel.h"
#include "petram9widget.h"
#include "petramawidget.h"
#include "petramsizewidget.h"
#include "petvideosizewidget.h"
#include "plus4aciawidget.h"
#include "plus4memhacks.h"
#include "plus4memoryexpansionwidget.h"
#include "plus4memorysizewidget.h"
#include "resourcecheckbutton.h"
#include "resources.h"
#include "sidmodelwidget.h"
#include "superpetwidget.h"
#include "uistatusbar.h"
#include "v364speechwidget.h"
#include "vdcmodelwidget.h"
#include "vic20memoryexpansionwidget.h"
#include "vice_gtk3.h"
#include "videomodelwidget.h"
#include "settings_model.h"
Functions
static void plus4_debug_dump_resources (void)
}}}
static void machine_model_handler_pet (int model)
Callback for PET model changes.
static void update_crt_controls (void)
Update CRT controls.
static void video_model_callback (int model)
Function called video model changes.
static void vdc_revision_callback (int revision)
Function called on VDC revision changes.
static void vdc_ram_callback (int state)
Function called on VDC RAM changes.
static void sid_model_callback (int model)
}}}
static void kernal_revision_callback (int rev)
Custom callback for the Kernal Revision widget.
static void iec_callback (GtkWidget *widget, gpointer data)
Function called on IEC checkbox toggles.
static void cia_model_callback (int cia_num, int cia_model)
Callback for CIA model changes.
static void power_frequency_callback (GtkWidget *self, int frequency)
Callback for machine power frequency changes.
static void pet_ram_size_callback (int size)
{{{ PET glue logic
static void pet_video_size_callback (int size)
Function called on PET I/O size changes.
static void pet_keyboard_type_callback (int type)
Function called on PET keyboard type changes.
static void pet_crtc_callback (int state)
Function called on PET CRTC changes.
static void pet_blank_callback (int state)
Function called on PET blank-on-eoi changes.
static void pet_screen2001_callback (int state)
Function called on PET screen-mirrors-like-2001 changes.
static void superpet_enable_callback (int state)
Callback for SuperPET I/O changes.
static void pet_io_callback (int state)
Function called on PET I/O changes.
static void pet_ram9_callback (int state)
Function called on PET RAM9 changes.
static void pet_rama_callback (int state)
Function called on PET RAMA changes.
static void plus4_mem_size_callback (GtkWidget *widget, int value)
Extra calback for the Plus4 memory size widget.
static void plus4_mem_hack_callback (GtkWidget *widget, int value)
Extra calback for the Plus4 memory expansion hack widget.
static void plus4_acia_widget_callback (GtkWidget *widget, int value)
Callback to update the Plus4 model widget on ACIA widget change.
static void v364_speech_widget_callback (GtkWidget *widget, int value)
Callback to update the Plus4 model widget on v364 widget change.
static void c64_misc_widget_sync (void)
}}}
static void machine_model_handler_c64 (int model)
Callback triggered on changing machine model.
static void machine_model_handler_c128 (int model)
Callback triggered on changing machine model.
static void dtv_revision_callback (GtkWidget *widget, int revision)
Callback for the DTV revision.
static void dtv_video_callback (int model)
Callback for the DTV VIC-II model (sync factor)
static void c64dtv_hummer_adc_sync (void)
Sync "Hummer ADC" widget with the associated resource.
static void c64dtv_hummer_adc_callback (GtkWidget *widget, gboolean value)
Update DTV widget on 'Hummer ADC' toggle.
static void machine_model_handler_c64dtv (int model)
Callback for DTV machine model changes.
static void vic20_video_callback (int model)
Callback for the VIC-2- VIC model (sync factor)
static void machine_model_handler_vic20 (int model)
Callback for VIC-20 machine model changes.
static void plus4_video_callback (int model)
Callback for the Plus4 TED model (sync factor)
static void machine_model_handler_plus4 (int model)
Handler for the model change for Plus4.
static void cbm5x0_video_callback (int model)
Callback for the CBM-II 5x0 VIC-II model (sync factor)
static void cbm2_video_callback (int model)
Callback for the CBM-II 6x0/7x0 CRTC model (sync factor)
static void cbm2_switches_callback (GtkWidget *widget, int model_line)
Callback for the CBM-II 6x0/7x0 ModelLine switches.
static void cbm2_memory_size_callback (GtkWidget *widget, int size)
Callback for CBM-II 6x0/7x0 memory size changes.
static void machine_model_handler_cbm5x0 (int model)
Callback for CBM 5x0 model changes.
static void machine_model_handler_cbm6x0 (int model)
Callback for CBM 6x0/7x0 model changes.
static void pet_set_ram9a_sensitivity (void)
Set sensitivity of PET Ram9 and RamA widgets.
static void machine_model_callback (int model)
Generic callback for machine model changes.
static void on_c64_glue_toggled (GtkWidget *widget, gpointer user_data)
Handler for the 'toggled' event of the C64 "Glue Logic" radio buttons.
static void c64_reset_with_iec_sync (void)
Sync "Reset-to-IEC" widget with the associated resource.
static GtkWidget * create_reset_with_iec_widget (void)
Create widget to toggle "Reset-to-IEC".
static GtkWidget * create_go64_widget (void)
Create widget to toggle "Go64Mode".
static void c64_glue_widget_sync (void)
Sync "Glue Logic" widget with the associated resource.
static GtkWidget * label_helper (const char *text)
Create left-aligned label with Pango markup.
static GtkWidget * create_c64_glue_widget (void)
Create widget to select C64SC Glue Logic.
static GtkWidget * create_c64_misc_widget (void)
Create 'misc' widget for C64/C64SC/SCPU64.
static GtkWidget * create_c128_misc_widget (void)
Create 'misc' widget for C128.
static GtkWidget * create_c64dtv_revision_widget (void)
Create widget to select DTV revision.
static GtkWidget * create_c64_layout (GtkWidget *grid)
Create widget layout for C64/C64SC.
static GtkWidget * create_c128_layout (GtkWidget *grid)
Create widget layout for C128.
static GtkWidget * create_c64dtv_layout (GtkWidget *grid)
Create C64DTV model settings widget layout.
static GtkWidget * create_vic20_layout (GtkWidget *grid)
Create VIC20 model settings widget layout.
static GtkWidget * create_plus4_layout (GtkWidget *grid)
Create Plus4 model settings widget layout.
static GtkWidget * create_pet_layout (GtkWidget *grid)
Creat PET layout.
static GtkWidget * create_cbm5x0_layout (GtkWidget *grid)
Create CBM-II/5x0 model settings widget layout.
static GtkWidget * create_cbm6x0_layout (GtkWidget *grid)
Create CBM-II/6x0-7x0 model settings widget layout.
static GtkWidget * create_vsid_layout (GtkWidget *grid)
Create VSID layout.
static GtkWidget * create_layout (void)
Create machine-specific layout.
GtkWidget * settings_model_widget_create (GtkWidget *parent)
Create 'Model' widget for the settings UI.
void settings_model_widget_set_model_func (int(*func)(void))
Set function pointer to function that determines if the model settings indicate a valid model.
void settings_model_widget_set_memhack_func (const char *(*func)(int))
Set function to get a memory hack description.
Variables
static const vice_gtk3_radiogroup_entry_t c64dtv_revisions []
List of C64DTV revisions.
static int(* get_model_func)(void)
Function to call to get the model for the current machine.
static const char *(* get_memhack_func)(int hack)
Function to call to get the memhack name.
static GtkWidget * machine_widget = NULL
Machine model widget.
static GtkWidget * cia_widget = NULL
CIA model widget.
static GtkWidget * video_widget = NULL
Video model widget.
static GtkWidget * power_frequency_widget
Machine power frequency widget.
static GtkWidget * ram_widget = NULL
RAM widget.
static GtkWidget * memhack_widget = NULL
Memhacks widget.
static GtkWidget * acia_widget = NULL
ACIA widget.
static GtkWidget * speech_widget = NULL
V364 speech widget.
static GtkWidget * vdc_widget = NULL
VDC display widget.
static GtkWidget * sid_widget = NULL
SID widget.
static GtkWidget * kernal_widget = NULL
KERNAL widget.
static GtkWidget * pet_video_size_widget = NULL
PET video widget.
static GtkWidget * pet_keyboard_widget = NULL
PET keyboard widget.
static GtkWidget * pet_misc_widget = NULL
PET miscellaneous settings widget.
static GtkWidget * pet_io_widget = NULL
PET I/O size widget.
static GtkWidget * pet_ram9_widget = NULL
PET RAM9 ($9000-$9fff) widget.
static GtkWidget * pet_rama_widget = NULL
PET RAMA ($a000-$afff) widget.
static GtkWidget * c64dtv_rev_widget = NULL
C64 DTV revision widget.
static GtkWidget * c64dtv_hummer_adc_widget = NULL
C64 DTV Hummer ADC widget.
static GtkWidget * reset_with_iec_widget = NULL
Reset with IEC checkbox.
static GtkWidget * c64_discrete_radio = NULL
C64 "discrete glue logic" radio button.
static GtkWidget * c64_custom_radio = NULL
C64 "custom glue logic" radio button.
static int mvs_current = 0
Current value of MachineVideoStandard resource.
Detailed Description
Model settings dialog.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Groepaz groep.nosp@m.az@g.nosp@m.mx.de
Function Documentation
c64_glue_widget_sync()
static void c64_glue_widget_sync (void) static
Sync "Glue Logic" widget with the associated resource.
Referenced by c64_misc_widget_sync().
c64_misc_widget_sync()
static void c64_misc_widget_sync (void) static
}}}
Synchronize Glue logic and IEC widget with their resources.
Referenced by machine_model_handler_c64().
c64_reset_with_iec_sync()
static void c64_reset_with_iec_sync (void) static
Sync "Reset-to-IEC" widget with the associated resource.
Referenced by c64_misc_widget_sync().
c64dtv_hummer_adc_callback()
static void c64dtv_hummer_adc_callback (GtkWidget * widget, gboolean value) static
Update DTV widget on 'Hummer ADC' toggle.
Parameters
[in] widget check button
[in] value new value (ignored)
Referenced by create_c64dtv_layout().
c64dtv_hummer_adc_sync()
static void c64dtv_hummer_adc_sync (void) static
Sync "Hummer ADC" widget with the associated resource.
Referenced by machine_model_handler_c64dtv().
cbm2_memory_size_callback()
static void cbm2_memory_size_callback (GtkWidget * widget, int size) static
Callback for CBM-II 6x0/7x0 memory size changes.
Calls model widget update.
Parameters
[in] widget memory size widget (unused)
[in] size new memory size (unused)
Referenced by create_cbm5x0_layout(), and create_cbm6x0_layout().
cbm2_switches_callback()
static void cbm2_switches_callback (GtkWidget * widget, int model_line) static
Callback for the CBM-II 6x0/7x0 ModelLine switches.
Calls model widget update.
Parameters
[in] widget switches widget (unused)
[in] model_line new mode line value (unused)
Referenced by create_cbm5x0_layout(), and create_cbm6x0_layout().
cbm2_video_callback()
static void cbm2_video_callback (int model) static
Callback for the CBM-II 6x0/7x0 CRTC model (sync factor)
Calls model widget update.
Parameters
[in] model new VIC-II model
Referenced by create_cbm6x0_layout().
cbm5x0_video_callback()
static void cbm5x0_video_callback (int model) static
Callback for the CBM-II 5x0 VIC-II model (sync factor)
Calls model widget update.
Parameters
[in] model new VIC-II model
Referenced by create_cbm5x0_layout().
cia_model_callback()
static void cia_model_callback (int cia_num, int cia_model) static
Callback for CIA model changes.
Parameters
[in] cia_num CIA number (1 or 2)
[in] cia_model CIA model ID
Referenced by create_c128_layout(), create_c64_layout(), create_cbm5x0_layout(), and create_cbm6x0_layout().
create_c128_layout()
static GtkWidget * create_c128_layout (GtkWidget * grid) static
Create widget layout for C128.
Parameters
[in,out] grid GtkGrid to use for layout
Returns
grid
Referenced by create_layout().
create_c128_misc_widget()
static GtkWidget * create_c128_misc_widget (void) static
Create 'misc' widget for C128.
Returns
GtkGrid
Referenced by create_c128_layout().
create_c64_glue_widget()
static GtkWidget * create_c64_glue_widget (void) static
Create widget to select C64SC Glue Logic.
Returns
GtkGrid
Referenced by create_c64_misc_widget().
create_c64_layout()
static GtkWidget * create_c64_layout (GtkWidget * grid) static
Create widget layout for C64/C64SC.
Parameters
[in,out] grid GtkGrid to use for layout
Returns
grid
Referenced by create_layout().
create_c64_misc_widget()
static GtkWidget * create_c64_misc_widget (void) static
Create 'misc' widget for C64/C64SC/SCPU64.
Returns
GtkGrid
Referenced by create_c64_layout().
create_c64dtv_layout()
static GtkWidget * create_c64dtv_layout (GtkWidget * grid) static
Create C64DTV model settings widget layout.
Parameters
[in] grid GtkGrid to attach widgets to
Returns
grid
add machine widget
Referenced by create_layout().
create_c64dtv_revision_widget()
static GtkWidget * create_c64dtv_revision_widget (void) static
Create widget to select DTV revision.
Creates a grid with a label and a vice_gtk3_resource_radiogroup widget.
Returns
GtkGrid
Referenced by create_c64dtv_layout().
create_cbm5x0_layout()
static GtkWidget * create_cbm5x0_layout (GtkWidget * grid) static
Create CBM-II/5x0 model settings widget layout.
Parameters
[in] grid GtkGrid to attach widgets to
Returns
grid
Referenced by create_layout().
create_cbm6x0_layout()
static GtkWidget * create_cbm6x0_layout (GtkWidget * grid) static
Create CBM-II/6x0-7x0 model settings widget layout.
Parameters
[in] grid GtkGrid to attach widgets to
Returns
grid
Referenced by create_layout().
create_go64_widget()
static GtkWidget * create_go64_widget (void) static
Create widget to toggle "Go64Mode".
Returns
GtkGrid
Referenced by create_c128_misc_widget().
create_layout()
static GtkWidget * create_layout (void) static
Create machine-specific layout.
Creates a machine-specific layout, including creating the required widgets
Returns
GtkGrid
Referenced by settings_model_widget_create().
create_pet_layout()
static GtkWidget * create_pet_layout (GtkWidget * grid) static
Creat PET layout.
Create PET layout using a GtkStack and GtkStackSwitcher to reduce space.
Parameters
[in,out] grid main grid to add widgets to
Returns
grid
Referenced by create_layout().
create_plus4_layout()
static GtkWidget * create_plus4_layout (GtkWidget * grid) static
Create Plus4 model settings widget layout.
Parameters
[in] grid GtkGrid to attach widgets to
Returns
grid
Referenced by create_layout().
create_reset_with_iec_widget()
static GtkWidget * create_reset_with_iec_widget (void) static
Create widget to toggle "Reset-to-IEC".
Returns
GtkGrid
Referenced by create_c64_misc_widget().
create_vic20_layout()
static GtkWidget * create_vic20_layout (GtkWidget * grid) static
Create VIC20 model settings widget layout.
Parameters
[in] grid GtkGrid to attach widgets to
Returns
grid
Referenced by create_layout().
create_vsid_layout()
static GtkWidget * create_vsid_layout (GtkWidget * grid) static
Create VSID layout.
Parameters
[in,out] grid GtkGrid to use for layout
Returns
grid
Referenced by create_layout().
dtv_revision_callback()
static void dtv_revision_callback (GtkWidget * widget, int revision) static
Callback for the DTV revision.
Calls model widget update
Parameters
[in] widget radio button triggering the callback (unused)
[in] revision new DTV revision (unused)
Referenced by create_c64dtv_revision_widget().
dtv_video_callback()
static void dtv_video_callback (int model) static
Callback for the DTV VIC-II model (sync factor)
Calls model widget update
Parameters
[in] model new VIC-II model (unused)
Referenced by create_c64dtv_layout().
iec_callback()
static void iec_callback (GtkWidget * widget, gpointer data) static
Function called on IEC checkbox toggles.
Parameters
[in] widget IEC widget (unused)
[in] data extra event data (unused)
Referenced by create_reset_with_iec_widget().
kernal_revision_callback()
static void kernal_revision_callback (int rev) static
Custom callback for the Kernal Revision widget.
Triggers an update of the 'machine model' widget when a different kernal rev has been selected. Only valid for x64/x64sc as far as I know.
Parameters
[in] rev new KERNAL revision
Referenced by create_c64_layout().
label_helper()
static GtkWidget * label_helper (const char * text) static
Create left-aligned label with Pango markup.
Parameters
[in] text text for label using Pango markup
Returns
GtkLabel
Referenced by create_c128_misc_widget(), and create_c64_misc_widget().
machine_model_callback()
static void machine_model_callback (int model) static
Generic callback for machine model changes.
Parameters
[in] model
Referenced by settings_model_widget_create().
machine_model_handler_c128()
static void machine_model_handler_c128 (int model) static
Callback triggered on changing machine model.
Parameters
[in] model machine model
Referenced by machine_model_callback().
machine_model_handler_c64()
static void machine_model_handler_c64 (int model) static
Callback triggered on changing machine model.
Parameters
[in] model machine model
Referenced by machine_model_callback().
machine_model_handler_c64dtv()
static void machine_model_handler_c64dtv (int model) static
Callback for DTV machine model changes.
Updates the DTV revision and VIC-II model widgets.
Parameters
[in] model DTV model
Referenced by machine_model_callback().
machine_model_handler_cbm5x0()
static void machine_model_handler_cbm5x0 (int model) static
Callback for CBM 5x0 model changes.
Parameters
[in] model new model
Referenced by machine_model_callback().
machine_model_handler_cbm6x0()
static void machine_model_handler_cbm6x0 (int model) static
Callback for CBM 6x0/7x0 model changes.
Parameters
[in] model new model
Referenced by machine_model_callback().
machine_model_handler_pet()
static void machine_model_handler_pet (int model) static
Callback for PET model changes.
Also called if the model doesn't apparently change; one resource change may have triggered another so all widgets must be synced.
Parameters
[in] model new model
Referenced by machine_model_callback().
machine_model_handler_plus4()
static void machine_model_handler_plus4 (int model) static
Handler for the model change for Plus4.
Parameters
[in] model new model (unused, it seems)
Referenced by machine_model_callback().
machine_model_handler_vic20()
static void machine_model_handler_vic20 (int model) static
Callback for VIC-20 machine model changes.
Parameters
[in] model VIC-20 model
Todo:
FIXME:
Referenced by machine_model_callback().
on_c64_glue_toggled()
static void on_c64_glue_toggled (GtkWidget * widget, gpointer user_data) static
Handler for the 'toggled' event of the C64 "Glue Logic" radio buttons.
Parameters
[in] widget radio button triggering the event
[in] user_data glue value (int)
Referenced by create_c64_glue_widget().
pet_blank_callback()
static void pet_blank_callback (int state) static
Function called on PET blank-on-eoi changes.
Parameters
[in] state new blank-on-eoi state (unused)
Referenced by create_pet_layout().
pet_crtc_callback()
static void pet_crtc_callback (int state) static
Function called on PET CRTC changes.
Parameters
[in] state new CRTC state (unused)
Referenced by create_pet_layout().
pet_io_callback()
static void pet_io_callback (int state) static
Function called on PET I/O changes.
Parameters
[in] state new I/O state (unused)
Referenced by create_pet_layout().
pet_keyboard_type_callback()
static void pet_keyboard_type_callback (int type) static
Function called on PET keyboard type changes.
Parameters
[in] type new keyboard type (unused)
Referenced by create_pet_layout().
pet_ram9_callback()
static void pet_ram9_callback (int state) static
Function called on PET RAM9 changes.
Parameters
[in] state new RAM9 state (unused)
Referenced by create_pet_layout().
pet_ram_size_callback()
static void pet_ram_size_callback (int size) static
{{{ PET glue logic
Callback for PET RAM size changes
Parameters
[in] size RAM size in KiB (unused)
Referenced by create_pet_layout().
pet_rama_callback()
static void pet_rama_callback (int state) static
Function called on PET RAMA changes.
Parameters
[in] state new RAMA state (unused)
Referenced by create_pet_layout().
pet_screen2001_callback()
static void pet_screen2001_callback (int state) static
Function called on PET screen-mirrors-like-2001 changes.
Parameters
[in] state new blank-on-eoi state (unused)
Referenced by create_pet_layout().
pet_set_ram9a_sensitivity()
static void pet_set_ram9a_sensitivity (void) static
Set sensitivity of PET Ram9 and RamA widgets.
Only the 8296 memory mapping has the Ram9 and RamA resources. Use RamSize as a proxy to determine this.
Referenced by create_pet_layout(), and machine_model_handler_pet().
pet_video_size_callback()
static void pet_video_size_callback (int size) static
Function called on PET I/O size changes.
Parameters
[in] size new I/O size (unused)
Referenced by create_pet_layout().
plus4_acia_widget_callback()
static void plus4_acia_widget_callback (GtkWidget * widget, int value) static
Callback to update the Plus4 model widget on ACIA widget change.
Parameters
[in] widget ACIA widget
[in] value new value
Referenced by create_plus4_layout().
plus4_debug_dump_resources()
static void plus4_debug_dump_resources (void) static
}}}
{{{ Plus4 glue logic and helpers
Debug hook: dump Plus4-related resources on stdoud
Referenced by machine_model_handler_plus4(), plus4_mem_hack_callback(), plus4_mem_size_callback(), plus4_video_callback(), and video_model_callback().
plus4_mem_hack_callback()
static void plus4_mem_hack_callback (GtkWidget * widget, int value) static
Extra calback for the Plus4 memory expansion hack widget.
Triggered when the widget changes value.
Parameters
[in,out] widget plus4 memory expansion hack widget
[in] value new size in KiB
Referenced by create_plus4_layout().
plus4_mem_size_callback()
static void plus4_mem_size_callback (GtkWidget * widget, int value) static
Extra calback for the Plus4 memory size widget.
Triggered when the widget changes value.
Parameters
[in,out] widget plus4 ram size widget
[in] value new size in KiB
Referenced by create_plus4_layout().
plus4_video_callback()
static void plus4_video_callback (int model) static
Callback for the Plus4 TED model (sync factor)
Calls model widget update
Parameters
[in] model new TED model
Referenced by create_plus4_layout().
power_frequency_callback()
static void power_frequency_callback (GtkWidget * self, int frequency) static
Callback for machine power frequency changes.
Parameters
[in] self radio group with the frequency radio buttons (ignored)
[in] frequency new frequency of the "MachinePowerFrequency" resource (ignored)
Referenced by create_c128_layout(), create_c64_layout(), create_cbm5x0_layout(), and create_cbm6x0_layout().
settings_model_widget_create()
GtkWidget * settings_model_widget_create (GtkWidget * parent)
Create 'Model' widget for the settings UI.
Parameters
[in] parent parent widget
Returns
GtkGrid
settings_model_widget_set_memhack_func()
void settings_model_widget_set_memhack_func (const char *(*)(int) func)
Set function to get a memory hack description.
Parameters
[in] func function to get a string for a memhack ID (int)
settings_model_widget_set_model_func()
void settings_model_widget_set_model_func (int(*)(void) func)
Set function pointer to function that determines if the model settings indicate a valid model.
Parameters
[in] func function pointer
sid_model_callback()
static void sid_model_callback (int model) static
}}}
Function called on SID model changes
Parameters
[in] model new SID model
Referenced by create_c128_layout(), create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), and create_cbm6x0_layout().
superpet_enable_callback()
static void superpet_enable_callback (int state) static
Callback for SuperPET I/O changes.
Parameters
[in] state enabled
Referenced by create_pet_layout().
update_crt_controls()
static void update_crt_controls (void) static
Update CRT controls.
Checks old and new values for the "MachineVideoStandard" resource and if the values switched from PAL to NTSC or vice versa the status bar CRT widgets are recreated.
Referenced by machine_model_callback(), and video_model_callback().
v364_speech_widget_callback()
static void v364_speech_widget_callback (GtkWidget * widget, int value) static
Callback to update the Plus4 model widget on v364 widget change.
Parameters
[in] widget v364 widget
[in] value new value
Referenced by create_plus4_layout().
vdc_ram_callback()
static void vdc_ram_callback (int state) static
Function called on VDC RAM changes.
Parameters
[in] state new VDC RAM state (unused)
Referenced by create_c128_layout().
vdc_revision_callback()
static void vdc_revision_callback (int revision) static
Function called on VDC revision changes.
Parameters
[in] revision new VDC revision (unused)
Referenced by create_c128_layout().
vic20_video_callback()
static void vic20_video_callback (int model) static
Callback for the VIC-2- VIC model (sync factor)
Calls model widget update
Parameters
[in] model new VIC model
Referenced by create_vic20_layout().
video_model_callback()
static void video_model_callback (int model) static
Function called video model changes.
Parameters
[in] model new videochip model
Referenced by create_c128_layout(), and create_c64_layout().
Variable Documentation
acia_widget
GtkWidget* acia_widget = NULL static
ACIA widget.
Plus4 only.
Referenced by create_plus4_layout().
c64_custom_radio
GtkWidget* c64_custom_radio = NULL static
C64 "custom glue logic" radio button.
Referenced by c64_glue_widget_sync(), and create_c64_glue_widget().
c64_discrete_radio
GtkWidget* c64_discrete_radio = NULL static
C64 "discrete glue logic" radio button.
Referenced by c64_glue_widget_sync(), and create_c64_glue_widget().
c64dtv_hummer_adc_widget
GtkWidget* c64dtv_hummer_adc_widget = NULL static
C64 DTV Hummer ADC widget.
Referenced by c64dtv_hummer_adc_sync(), and create_c64dtv_layout().
c64dtv_rev_widget
GtkWidget* c64dtv_rev_widget = NULL static
C64 DTV revision widget.
Referenced by create_c64dtv_layout(), and machine_model_handler_c64dtv().
c64dtv_revisions
const vice_gtk3_radiogroup_entry_t c64dtv_revisions[] static
Initial value:
= {
    { "DTV2", DTVREV_2 },
    { "DTV3", DTVREV_3 },
    { NULL,   -1 }
}
List of C64DTV revisions.
Referenced by create_c64dtv_revision_widget().
cia_widget
GtkWidget* cia_widget = NULL static
CIA model widget.
Used by C64, C64SC, SCPU64, C64DTV, C128, CBM5x0, CBM-II, VSID
Referenced by create_c128_layout(), create_c64_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), machine_model_handler_c128(), machine_model_handler_c64(), and settings_model_widget_create().
get_memhack_func
const char *(* get_memhack_func) (int hack) (int hack) static
Function to call to get the memhack name.
Referenced by plus4_debug_dump_resources(), and settings_model_widget_set_memhack_func().
get_model_func
int(* get_model_func) (void) (void) static
Function to call to get the model for the current machine.
Referenced by cia_model_callback(), dtv_revision_callback(), pet_blank_callback(), pet_crtc_callback(), pet_io_callback(), pet_keyboard_type_callback(), pet_ram9_callback(), pet_ram_size_callback(), pet_rama_callback(), pet_screen2001_callback(), pet_video_size_callback(), plus4_debug_dump_resources(), power_frequency_callback(), settings_model_widget_set_model_func(), sid_model_callback(), superpet_enable_callback(), vdc_ram_callback(), vdc_revision_callback(), and video_model_callback().
kernal_widget
GtkWidget* kernal_widget = NULL static
KERNAL widget.
Referenced by create_c64_layout(), machine_model_handler_c64(), and settings_model_widget_create().
machine_widget
GtkWidget* machine_widget = NULL static
Machine model widget.
This widget controls which machine model is used.
Changing the machine model means a lot of other resources being changed, and changing a resource changes the model (or invalidates it).
Referenced by c64dtv_hummer_adc_callback(), cbm2_memory_size_callback(), cbm2_switches_callback(), cbm2_video_callback(), cbm5x0_video_callback(), cia_model_callback(), create_c128_layout(), create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), create_pet_layout(), create_plus4_layout(), create_vic20_layout(), create_vsid_layout(), dtv_revision_callback(), dtv_video_callback(), iec_callback(), kernal_revision_callback(), on_c64_glue_toggled(), pet_blank_callback(), pet_crtc_callback(), pet_io_callback(), pet_keyboard_type_callback(), pet_ram9_callback(), pet_ram_size_callback(), pet_rama_callback(), pet_screen2001_callback(), pet_video_size_callback(), plus4_acia_widget_callback(), plus4_mem_hack_callback(), plus4_mem_size_callback(), plus4_video_callback(), power_frequency_callback(), settings_model_widget_create(), sid_model_callback(), superpet_enable_callback(), v364_speech_widget_callback(), vdc_ram_callback(), vdc_revision_callback(), vic20_video_callback(), and video_model_callback().
memhack_widget
GtkWidget* memhack_widget = NULL static
Memhacks widget.
Hardware hacks related to installed memory, x64/x64sc only.
Referenced by create_plus4_layout().
mvs_current
int mvs_current = 0 static
Current value of MachineVideoStandard resource.
Is set in the constructor and checked and updated in update_crt_controls()
Referenced by settings_model_widget_create(), and update_crt_controls().
pet_io_widget
GtkWidget* pet_io_widget = NULL static
PET I/O size widget.
Referenced by create_pet_layout(), and machine_model_handler_pet().
pet_keyboard_widget
GtkWidget* pet_keyboard_widget = NULL static
PET keyboard widget.
Referenced by create_pet_layout(), and machine_model_handler_pet().
pet_misc_widget
GtkWidget* pet_misc_widget = NULL static
PET miscellaneous settings widget.
Referenced by create_pet_layout(), and machine_model_handler_pet().
pet_ram9_widget
GtkWidget* pet_ram9_widget = NULL static
PET RAM9 ($9000-$9fff) widget.
Referenced by create_pet_layout(), machine_model_handler_pet(), and pet_set_ram9a_sensitivity().
pet_rama_widget
GtkWidget* pet_rama_widget = NULL static
PET RAMA ($a000-$afff) widget.
Referenced by create_pet_layout(), machine_model_handler_pet(), and pet_set_ram9a_sensitivity().
pet_video_size_widget
GtkWidget* pet_video_size_widget = NULL static
PET video widget.
Referenced by create_pet_layout(), and machine_model_handler_pet().
power_frequency_widget
GtkWidget* power_frequency_widget static
Machine power frequency widget.
Referenced by create_c128_layout(), create_c64_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), machine_model_handler_c128(), machine_model_handler_c64(), machine_model_handler_cbm5x0(), and machine_model_handler_cbm6x0().
ram_widget
GtkWidget* ram_widget = NULL static
RAM widget.
Referenced by create_cbm5x0_layout(), create_cbm6x0_layout(), create_pet_layout(), create_plus4_layout(), create_vic20_layout(), machine_model_handler_cbm5x0(), machine_model_handler_cbm6x0(), machine_model_handler_pet(), plus4_mem_hack_callback(), and vdc_model_widget_update().
reset_with_iec_widget
GtkWidget* reset_with_iec_widget = NULL static
Reset with IEC checkbox.
Referenced by c64_reset_with_iec_sync(), and create_reset_with_iec_widget().
sid_widget
GtkWidget* sid_widget = NULL static
SID widget.
Referenced by create_c128_layout(), create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), create_vsid_layout(), machine_model_handler_c128(), machine_model_handler_c64(), and settings_model_widget_create().
speech_widget
GtkWidget* speech_widget = NULL static
V364 speech widget.
Used only in xplus4.
Referenced by create_plus4_layout().
vdc_widget
GtkWidget* vdc_widget = NULL static
VDC display widget.
Used in x128.
Referenced by create_c128_layout(), machine_model_handler_c128(), and settings_model_widget_create().
video_widget
GtkWidget* video_widget = NULL static
Video model widget.
Referenced by create_c128_layout(), create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), create_plus4_layout(), create_vic20_layout(), create_vsid_layout(), machine_model_handler_c128(), machine_model_handler_c64(), machine_model_handler_c64dtv(), machine_model_handler_cbm5x0(), machine_model_handler_cbm6x0(), machine_model_handler_plus4(), machine_model_handler_vic20(), and settings_model_widget_create().