vsid: machine.c File Reference
machine.c File Reference
#include "vice.h"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "alarm.h"
#include "archdep.h"
#include "attach.h"
#include "autostart.h"
#include "cmdline.h"
#include "console.h"
#include "diskimage.h"
#include "drive.h"
#include "vice-event.h"
#include "fliplist.h"
#include "fsdevice.h"
#include "gfxoutput.h"
#include "initcmdline.h"
#include "interrupt.h"
#include "joystick.h"
#include "kbdbuf.h"
#include "keyboard.h"
#include "lib.h"
#include "log.h"
#include "machine-video.h"
#include "machine.h"
#include "maincpu.h"
#include "mem.h"
#include "monitor.h"
#include "monitor_network.h"
#include "monitor_binary.h"
#include "network.h"
#include "palette.h"
#include "printer.h"
#include "profiler.h"
#include "resources.h"
#include "romset.h"
#include "screenshot.h"
#include "sound.h"
#include "sysfile.h"
#include "tape.h"
#include "traps.h"
#include "types.h"
#include "uiapi.h"
#include "uiactions.h"
#include "uihotkeys.h"
#include "util.h"
#include "video.h"
#include "vsync.h"
#include "zfile.h"
Macros
#define EXIT_SUCCESS 0
#define DBG(x)
Functions
unsigned int machine_jam (const char *format,...)
bool machine_is_jammed (void)
char * machine_jam_reason (void)
void machine_powerup (void)
Power-up the machine.
static void machine_trigger_reset_internal (const unsigned int mode)
void machine_trigger_reset (const unsigned int mode)
void machine_reset_event_playback (CLOCK offset, void *data)
void machine_reset (void)
called via cpu_reset()
void machine_maincpu_init (void)
Initialize the main CPU of the machine.
void machine_early_init (void)
int machine_init (void)
void machine_maincpu_shutdown (void)
Shutdown the main CPU of the machine.
static void screenshot_at_exit (void)
void machine_shutdown (void)
Shutdown the emachine.
static int set_jam_action (int val, void *param)
Resources & cmdline.
static int set_exit_screenshot_name (const char *val, void *param)
static int set_exit_screenshot_name1 (const char *val, void *param)
int machine_common_resources_init (void)
Initialize the machine's resources.
void machine_common_resources_shutdown (void)
int machine_common_cmdline_options_init (void)
Initialize the machine's command-line options.
Variables
static int machine_init_was_called = 0
static bool is_jammed = false
static char * jam_reason = NULL
static int jam_action = 0
int machine_keymap_index
static char * ExitScreenshotName = NULL
static char * ExitScreenshotName1 = NULL
static bool is_first_reset = true
static resource_string_t resources_string []
static resource_string_t resources_string_c128 []
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options_c128 []
static const cmdline_option_t cmdline_options []
static const cmdline_option_t cmdline_options_vsid []
Macro Definition Documentation
DBG
#define DBG (x)
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Function Documentation
machine_common_cmdline_options_init()
int machine_common_cmdline_options_init (void)
Initialize the machine's command-line options.
Referenced by init_cmdline_options().
machine_common_resources_init()
int machine_common_resources_init (void)
Initialize the machine's resources.
Referenced by init_resources().
machine_common_resources_shutdown()
void machine_common_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
machine_early_init()
void machine_early_init (void)
Referenced by main_program().
machine_init()
int machine_init (void)
Referenced by init_main().
machine_is_jammed()
bool machine_is_jammed (void)
Referenced by statusbar_speed_widget_update(), and vice_opengl_on_ui_frame_clock().
machine_jam()
unsigned int machine_jam (const char * format, ...)
machine_jam_reason()
char * machine_jam_reason (void)
Referenced by statusbar_speed_widget_update().
machine_maincpu_init()
void machine_maincpu_init (void)
Initialize the main CPU of the machine.
Referenced by init_main().
machine_maincpu_shutdown()
void machine_maincpu_shutdown (void)
Shutdown the main CPU of the machine.
Referenced by cmdline_help(), and machine_shutdown().
machine_powerup()
void machine_powerup (void)
Power-up the machine.
Referenced by machine_reset(), and machine_trigger_reset_internal().
machine_reset()
void machine_reset (void)
called via cpu_reset()
Referenced by cpu_reset().
machine_reset_event_playback()
void machine_reset_event_playback (CLOCK offset, void * data)
Referenced by event_alarm_handler(), and event_playback_event_list().
machine_shutdown()
void machine_shutdown (void)
Shutdown the emachine.
Referenced by main_exit().
machine_trigger_reset()
void machine_trigger_reset (const unsigned int mode)
Referenced by c64_snapshot_read(), drivecpu_jam(), event_playback_start_trap(), event_record_start_trap(), machine_change_timing(), machine_reset_action(), maincpu_mainloop(), mon_reset_machine(), play_current_tune(), psid_play_action(), psid_stop_action(), psid_ui_set_tune(), reboot_for_autostart(), select_tune_from_menu(), set_basic_rom_name(), set_board_type(), set_c64_256k_enabled(), set_kernal_revision(), set_kernal_rom_name(), set_plus256k_enabled(), set_plus60k_enabled(), and ui_vsid_window_load_psid().
machine_trigger_reset_internal()
static void machine_trigger_reset_internal (const unsigned int mode) static
Referenced by machine_reset_event_playback(), and machine_trigger_reset().
screenshot_at_exit()
static void screenshot_at_exit (void) static
Todo:
FIXME: this always uses the first canvas, for x128 this is the VDC
Todo:
FIXME: perhaps select driver based on the extension of the given name. for now PNG is good enough :)
Todo:
FIXME: this always uses the second canvas, for x128 this is the VICII
Todo:
FIXME: perhaps select driver based on the extension of the given name. for now PNG is good enough :)
Referenced by machine_shutdown().
set_exit_screenshot_name()
static int set_exit_screenshot_name (const char * val, void * param) static
set_exit_screenshot_name1()
static int set_exit_screenshot_name1 (const char * val, void * param) static
set_jam_action()
static int set_jam_action (int val, void * param) static
Resources & cmdline.
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-jamaction", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "JAMAction", NULL,
      "<Type>", "Set action on CPU JAM: (0: Ask, 1: continue, 2: Monitor, 3: Reset, 4: Power cycle, 5: Quit Emulator)" },
    { "-exitscreenshot", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "ExitScreenshotName", NULL,
      "<Name>", "Set name of screenshot to save when emulator exits." },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by machine_common_cmdline_options_init().
cmdline_options_c128
const cmdline_option_t cmdline_options_c128[] static
Initial value:
=
{
    { "-jamaction", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "JAMAction", NULL,
      "<Type>", "Set action on CPU JAM: (0: Ask, 1: continue, 2: Monitor, 3: Reset, 4: Power cycle, 5: Quit Emulator)" },
    { "-exitscreenshot", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "ExitScreenshotName", NULL,
      "<Name>", "Set name of screenshot to save when emulator exits." },
    { "-exitscreenshotvicii", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "ExitScreenshotName1", NULL,
      "<Name>", "Set name of screenshot to save when emulator exits." },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by machine_common_cmdline_options_init().
cmdline_options_vsid
const cmdline_option_t cmdline_options_vsid[] static
Initial value:
=
{
    { "-jamaction", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "JAMAction", NULL,
      "<Type>", "Set action on CPU JAM: (0: Ask, 1: continue, 2: Monitor, 3: Reset, 4: Power cycle, 5: Quit Emulator)" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by machine_common_cmdline_options_init().
ExitScreenshotName
char* ExitScreenshotName = NULL static
Referenced by machine_common_resources_shutdown(), screenshot_at_exit(), and set_exit_screenshot_name().
ExitScreenshotName1
char* ExitScreenshotName1 = NULL static
Referenced by machine_common_resources_shutdown(), screenshot_at_exit(), and set_exit_screenshot_name1().
is_first_reset
bool is_first_reset = true static
Referenced by machine_reset().
is_jammed
bool is_jammed = false static
Referenced by machine_is_jammed(), machine_jam(), machine_reset(), and machine_trigger_reset_internal().
jam_action
int jam_action = 0 static
Referenced by machine_jam(), and set_jam_action().
jam_reason
char* jam_reason = NULL static
Referenced by machine_jam(), machine_jam_reason(), machine_maincpu_shutdown(), machine_reset(), and machine_trigger_reset_internal().
machine_init_was_called
int machine_init_was_called = 0 static
Referenced by machine_init(), and machine_shutdown().
machine_keymap_index
int machine_keymap_index
Referenced by keyboard_set_default_keymap_file(), keyboard_set_keyboard_mapping(), keyboard_set_keyboard_type(), keyboard_set_keymap_index(), and keymap_init().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "JAMAction",  1 , RES_EVENT_SAME, NULL,
      &jam_action, set_jam_action, NULL },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by machine_common_resources_init().
resources_string
resource_string_t resources_string[] static
Initial value:
= {
    { "ExitScreenshotName", "", RES_EVENT_NO, NULL,
      &ExitScreenshotName, set_exit_screenshot_name, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by machine_common_resources_init().
resources_string_c128
resource_string_t resources_string_c128[] static
Initial value:
= {
    { "ExitScreenshotName1", "", RES_EVENT_NO, NULL,
      &ExitScreenshotName1, set_exit_screenshot_name1, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by machine_common_resources_init().