vsid: arch/gtk3/uimenu.h File Reference
uimenu.h File Reference
Native GTK3 menu handling - header.
#include "vice.h"
#include <gtk/gtk.h>
#include "uitypes.h"
Functions
GtkWidget * ui_menu_submenu_create (GtkWidget *bar, const char *label)
Create an empty submenu and add it to a menu bar.
GtkWidget * ui_menu_add (GtkWidget *menu, const ui_menu_item_t *items, gint window_id)
Add menu items to menu.
Detailed Description
Native GTK3 menu handling - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Marcus Sutton logge.nosp@m.doub.nosp@m.t@gma.nosp@m.il.c.nosp@m.om
Function Documentation
ui_menu_add()
GtkWidget * ui_menu_add (GtkWidget * menu, const ui_menu_item_t * items, gint window_id)
Add menu items to menu.
Parameters
[in,out] menu Gtk menu
[in] items menu items to add to menu
[in] window_id window ID (PRIMARY_WINDOW or SECONDARY_WINDOW)
Returns
menu
Referenced by ui_machine_menu_bar_create(), ui_machine_menu_bar_vsid_patch(), ui_menu_add(), and ui_vsid_menu_bar_create().
ui_menu_submenu_create()
GtkWidget * ui_menu_submenu_create (GtkWidget * bar, const char * label)
Create an empty submenu and add it to a menu bar.
Parameters
[in] bar the menu bar to add the submenu to
[in] label label of the submenu to create
Returns
a reference to the new submenu
Referenced by ui_machine_menu_bar_create(), and ui_vsid_menu_bar_create().