vsid: snapshot.h File Reference
snapshot.h File Reference
#include "types.h"
Macros
#define SNAPSHOT_MACHINE_NAME_LEN 16
#define SNAPSHOT_MODULE_NAME_LEN 16
#define SNAPSHOT_NO_ERROR 0
#define SNAPSHOT_WRITE_EOF_ERROR 1
#define SNAPSHOT_WRITE_BYTE_ARRAY_ERROR 2
#define SNAPSHOT_READ_EOF_ERROR 3
#define SNAPSHOT_READ_BYTE_ARRAY_ERROR 4
#define SNAPSHOT_ILLEGAL_STRING_LENGTH_ERROR 5
#define SNAPSHOT_READ_OUT_OF_BOUNDS_ERROR 6
#define SNAPSHOT_ILLEGAL_OFFSET_ERROR 7
#define SNAPSHOT_FIRST_MODULE_NOT_FOUND_ERROR 8
#define SNAPSHOT_MODULE_HEADER_READ_ERROR 9
#define SNAPSHOT_MODULE_NOT_FOUND_ERROR 10
#define SNAPSHOT_MODULE_CLOSE_ERROR 11
#define SNAPSHOT_MODULE_SKIP_ERROR 12
#define SNAPSHOT_CANNOT_CREATE_SNAPSHOT_ERROR 13
#define SNAPSHOT_CANNOT_WRITE_MAGIC_STRING_ERROR 14
#define SNAPSHOT_CANNOT_WRITE_VERSION_ERROR 15
#define SNAPSHOT_CANNOT_WRITE_MACHINE_NAME_ERROR 16
#define SNAPSHOT_CANNOT_OPEN_FOR_READ_ERROR 17
#define SNAPSHOT_MAGIC_STRING_MISMATCH_ERROR 18
#define SNAPSHOT_CANNOT_READ_VERSION_ERROR 19
#define SNAPSHOT_CANNOT_READ_MACHINE_NAME_ERROR 20
#define SNAPSHOT_MACHINE_MISMATCH_ERROR 21
#define SNAPSHOT_READ_CLOSE_EOF_ERROR 22
#define SNAPSHOT_WRITE_CLOSE_EOF_ERROR 23
#define SNAPSHOT_MODULE_HIGHER_VERSION 24
#define SNAPSHOT_MODULE_INCOMPATIBLE 25
#define SNAPSHOT_CANNOT_WRITE_SNAPSHOT 26
#define SNAPSHOT_CANNOT_READ_SNAPSHOT 27
#define SNAPSHOT_MODULE_NOT_IMPLEMENTED 28
#define SNAPSHOT_ATA_IMAGE_FILENAME_MISMATCH 29
#define SNAPSHOT_VICII_MODEL_MISMATCH 30
#define SMW_B snapshot_module_write_byte
#define SMW_W snapshot_module_write_word
#define SMW_DW snapshot_module_write_dword
#define SMW_QW snapshot_module_write_qword
#define SMW_DB snapshot_module_write_double
#define SMW_PSTR snapshot_module_write_padded_string
#define SMW_BA snapshot_module_write_byte_array
#define SMW_WA snapshot_module_write_word_array
#define SMW_DWA snapshot_module_write_dword_array
#define SMW_STR snapshot_module_write_string
#define SMW_CLOCK snapshot_module_write_qword
#define SMR_B snapshot_module_read_byte
#define SMR_W snapshot_module_read_word
#define SMR_DW snapshot_module_read_dword
#define SMR_QW snapshot_module_read_qword
#define SMR_DB snapshot_module_read_double
#define SMR_BA snapshot_module_read_byte_array
#define SMR_WA snapshot_module_read_word_array
#define SMR_DWA snapshot_module_read_dword_array
#define SMR_STR snapshot_module_read_string
#define SMR_B_INT snapshot_module_read_byte_into_int
#define SMR_B_UINT snapshot_module_read_byte_into_uint
#define SMR_W_INT snapshot_module_read_word_into_int
#define SMR_W_UINT snapshot_module_read_word_into_uint
#define SMR_DW_UL snapshot_module_read_dword_into_ulong
#define SMR_DW_INT snapshot_module_read_dword_into_int
#define SMR_DW_UINT snapshot_module_read_dword_into_uint
#define SMR_CLOCK snapshot_module_read_qword
Typedefs
typedef struct snapshot_module_s snapshot_module_t
typedef struct snapshot_s snapshot_t
Functions
void snapshot_display_error (void)
int snapshot_module_write_byte (snapshot_module_t *m, uint8_t data)
int snapshot_module_write_word (snapshot_module_t *m, uint16_t data)
int snapshot_module_write_dword (snapshot_module_t *m, uint32_t data)
int snapshot_module_write_qword (snapshot_module_t *m, uint64_t data)
int snapshot_module_write_double (snapshot_module_t *m, double db)
int snapshot_module_write_padded_string (snapshot_module_t *m, const char *s, uint8_t pad_char, int len)
int snapshot_module_write_byte_array (snapshot_module_t *m, const uint8_t *data, unsigned int num)
int snapshot_module_write_word_array (snapshot_module_t *m, const uint16_t *data, unsigned int num)
int snapshot_module_write_dword_array (snapshot_module_t *m, const uint32_t *data, unsigned int num)
int snapshot_module_write_string (snapshot_module_t *m, const char *s)
int snapshot_module_read_byte (snapshot_module_t *m, uint8_t *b_return)
int snapshot_module_read_word (snapshot_module_t *m, uint16_t *w_return)
int snapshot_module_read_dword (snapshot_module_t *m, uint32_t *dw_return)
int snapshot_module_read_qword (snapshot_module_t *m, uint64_t *qw_return)
int snapshot_module_read_double (snapshot_module_t *m, double *db_return)
int snapshot_module_read_byte_array (snapshot_module_t *m, uint8_t *b_return, unsigned int num)
int snapshot_module_read_word_array (snapshot_module_t *m, uint16_t *w_return, unsigned int num)
int snapshot_module_read_dword_array (snapshot_module_t *m, uint32_t *dw_return, unsigned int num)
int snapshot_module_read_string (snapshot_module_t *m, char **s)
int snapshot_module_read_byte_into_int (snapshot_module_t *m, int *value_return)
int snapshot_module_read_byte_into_uint (snapshot_module_t *m, unsigned int *value_return)
int snapshot_module_read_word_into_int (snapshot_module_t *m, int *value_return)
int snapshot_module_read_word_into_uint (snapshot_module_t *m, unsigned int *value_return)
int snapshot_module_read_dword_into_ulong (snapshot_module_t *m, unsigned long *value_return)
int snapshot_module_read_dword_into_int (snapshot_module_t *m, int *value_return)
int snapshot_module_read_dword_into_uint (snapshot_module_t *m, unsigned int *value_return)
int snapshot_module_read_qword_into_int64 (snapshot_module_t *m, int64_t *value_return)
snapshot_module_t * snapshot_module_create (snapshot_t *s, const char *name, uint8_t major_version, uint8_t minor_version)
snapshot_module_t * snapshot_module_open (snapshot_t *s, const char *name, uint8_t *major_version_return, uint8_t *minor_version_return)
int snapshot_module_close (snapshot_module_t *m)
snapshot_t * snapshot_create (const char *filename, uint8_t major_version, uint8_t minor_version, const char *snapshot_machine_name)
snapshot_t * snapshot_open (const char *filename, uint8_t *major_version_return, uint8_t *minor_version_return, const char *snapshot_machine_name)
int snapshot_close (snapshot_t *s)
void snapshot_set_error (int error)
int snapshot_get_error (void)
int snapshot_version_is_equal (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version == required version
int snapshot_version_is_bigger (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version > required version
int snapshot_version_is_smaller (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version < required version
Macro Definition Documentation
SMR_B
#define SMR_B snapshot_module_read_byte
SMR_B_INT
#define SMR_B_INT snapshot_module_read_byte_into_int
SMR_B_UINT
#define SMR_B_UINT snapshot_module_read_byte_into_uint
SMR_BA
#define SMR_BA snapshot_module_read_byte_array
SMR_CLOCK
#define SMR_CLOCK snapshot_module_read_qword
SMR_DB
#define SMR_DB snapshot_module_read_double
SMR_DW
#define SMR_DW snapshot_module_read_dword
SMR_DW_INT
#define SMR_DW_INT snapshot_module_read_dword_into_int
SMR_DW_UINT
#define SMR_DW_UINT snapshot_module_read_dword_into_uint
SMR_DW_UL
#define SMR_DW_UL snapshot_module_read_dword_into_ulong
SMR_DWA
#define SMR_DWA snapshot_module_read_dword_array
SMR_QW
#define SMR_QW snapshot_module_read_qword
SMR_STR
#define SMR_STR snapshot_module_read_string
SMR_W
#define SMR_W snapshot_module_read_word
SMR_W_INT
#define SMR_W_INT snapshot_module_read_word_into_int
SMR_W_UINT
#define SMR_W_UINT snapshot_module_read_word_into_uint
SMR_WA
#define SMR_WA snapshot_module_read_word_array
SMW_B
#define SMW_B snapshot_module_write_byte
SMW_BA
#define SMW_BA snapshot_module_write_byte_array
SMW_CLOCK
#define SMW_CLOCK snapshot_module_write_qword
SMW_DB
#define SMW_DB snapshot_module_write_double
SMW_DW
#define SMW_DW snapshot_module_write_dword
SMW_DWA
#define SMW_DWA snapshot_module_write_dword_array
SMW_PSTR
#define SMW_PSTR snapshot_module_write_padded_string
SMW_QW
#define SMW_QW snapshot_module_write_qword
SMW_STR
#define SMW_STR snapshot_module_write_string
SMW_W
#define SMW_W snapshot_module_write_word
SMW_WA
#define SMW_WA snapshot_module_write_word_array
SNAPSHOT_ATA_IMAGE_FILENAME_MISMATCH
#define SNAPSHOT_ATA_IMAGE_FILENAME_MISMATCH 29
SNAPSHOT_CANNOT_CREATE_SNAPSHOT_ERROR
#define SNAPSHOT_CANNOT_CREATE_SNAPSHOT_ERROR 13
SNAPSHOT_CANNOT_OPEN_FOR_READ_ERROR
#define SNAPSHOT_CANNOT_OPEN_FOR_READ_ERROR 17
SNAPSHOT_CANNOT_READ_MACHINE_NAME_ERROR
#define SNAPSHOT_CANNOT_READ_MACHINE_NAME_ERROR 20
SNAPSHOT_CANNOT_READ_SNAPSHOT
#define SNAPSHOT_CANNOT_READ_SNAPSHOT 27
SNAPSHOT_CANNOT_READ_VERSION_ERROR
#define SNAPSHOT_CANNOT_READ_VERSION_ERROR 19
SNAPSHOT_CANNOT_WRITE_MACHINE_NAME_ERROR
#define SNAPSHOT_CANNOT_WRITE_MACHINE_NAME_ERROR 16
SNAPSHOT_CANNOT_WRITE_MAGIC_STRING_ERROR
#define SNAPSHOT_CANNOT_WRITE_MAGIC_STRING_ERROR 14
SNAPSHOT_CANNOT_WRITE_SNAPSHOT
#define SNAPSHOT_CANNOT_WRITE_SNAPSHOT 26
SNAPSHOT_CANNOT_WRITE_VERSION_ERROR
#define SNAPSHOT_CANNOT_WRITE_VERSION_ERROR 15
SNAPSHOT_FIRST_MODULE_NOT_FOUND_ERROR
#define SNAPSHOT_FIRST_MODULE_NOT_FOUND_ERROR 8
SNAPSHOT_ILLEGAL_OFFSET_ERROR
#define SNAPSHOT_ILLEGAL_OFFSET_ERROR 7
SNAPSHOT_ILLEGAL_STRING_LENGTH_ERROR
#define SNAPSHOT_ILLEGAL_STRING_LENGTH_ERROR 5
SNAPSHOT_MACHINE_MISMATCH_ERROR
#define SNAPSHOT_MACHINE_MISMATCH_ERROR 21
SNAPSHOT_MACHINE_NAME_LEN
#define SNAPSHOT_MACHINE_NAME_LEN 16
SNAPSHOT_MAGIC_STRING_MISMATCH_ERROR
#define SNAPSHOT_MAGIC_STRING_MISMATCH_ERROR 18
SNAPSHOT_MODULE_CLOSE_ERROR
#define SNAPSHOT_MODULE_CLOSE_ERROR 11
SNAPSHOT_MODULE_HEADER_READ_ERROR
#define SNAPSHOT_MODULE_HEADER_READ_ERROR 9
SNAPSHOT_MODULE_HIGHER_VERSION
#define SNAPSHOT_MODULE_HIGHER_VERSION 24
SNAPSHOT_MODULE_INCOMPATIBLE
#define SNAPSHOT_MODULE_INCOMPATIBLE 25
SNAPSHOT_MODULE_NAME_LEN
#define SNAPSHOT_MODULE_NAME_LEN 16
SNAPSHOT_MODULE_NOT_FOUND_ERROR
#define SNAPSHOT_MODULE_NOT_FOUND_ERROR 10
SNAPSHOT_MODULE_NOT_IMPLEMENTED
#define SNAPSHOT_MODULE_NOT_IMPLEMENTED 28
SNAPSHOT_MODULE_SKIP_ERROR
#define SNAPSHOT_MODULE_SKIP_ERROR 12
SNAPSHOT_NO_ERROR
#define SNAPSHOT_NO_ERROR 0
SNAPSHOT_READ_BYTE_ARRAY_ERROR
#define SNAPSHOT_READ_BYTE_ARRAY_ERROR 4
SNAPSHOT_READ_CLOSE_EOF_ERROR
#define SNAPSHOT_READ_CLOSE_EOF_ERROR 22
SNAPSHOT_READ_EOF_ERROR
#define SNAPSHOT_READ_EOF_ERROR 3
SNAPSHOT_READ_OUT_OF_BOUNDS_ERROR
#define SNAPSHOT_READ_OUT_OF_BOUNDS_ERROR 6
SNAPSHOT_VICII_MODEL_MISMATCH
#define SNAPSHOT_VICII_MODEL_MISMATCH 30
SNAPSHOT_WRITE_BYTE_ARRAY_ERROR
#define SNAPSHOT_WRITE_BYTE_ARRAY_ERROR 2
SNAPSHOT_WRITE_CLOSE_EOF_ERROR
#define SNAPSHOT_WRITE_CLOSE_EOF_ERROR 23
SNAPSHOT_WRITE_EOF_ERROR
#define SNAPSHOT_WRITE_EOF_ERROR 1
Typedef Documentation
snapshot_module_t
typedef struct snapshot_module_s snapshot_module_t
snapshot_t
typedef struct snapshot_s snapshot_t
Function Documentation
snapshot_close()
int snapshot_close (snapshot_t * s)
Referenced by autostart_snapshot(), c64_snapshot_read(), c64_snapshot_write(), and event_playback_start_trap().
snapshot_create()
snapshot_t * snapshot_create (const char * filename, uint8_t major_version, uint8_t minor_version, const char * snapshot_machine_name)
< write mode (binary)
Referenced by c64_snapshot_write().
snapshot_display_error()
void snapshot_display_error (void)
Referenced by load_snapshot_filename_callback(), load_snapshot_trap(), quickload_snapshot_trap(), quicksave_snapshot_trap(), and save_snapshot_dialog().
snapshot_get_error()
int snapshot_get_error (void)
Referenced by machine_read_snapshot(), and machine_write_snapshot().
snapshot_module_close()
int snapshot_module_close (snapshot_module_t * m)
Referenced by ata_snapshot_read_module(), ata_snapshot_write_module(), c64_256k_snapshot_read(), c64_256k_snapshot_write(), c64_glue_snapshot_read_module(), c64_glue_snapshot_write_module(), c64_snapshot_read_module(), c64_snapshot_read_rom_module(), c64_snapshot_write_module(), c64_snapshot_write_rom_module(), ciacore_snapshot_read_module(), ciacore_snapshot_write_module(), cmdhd_snapshot_read_module(), cmdhd_snapshot_write_module(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), drive_snapshot_write_gcrimage_module(), drive_snapshot_write_image_module(), drive_snapshot_write_module(), drive_snapshot_write_p64image_module(), drivecpu65c02_snapshot_read_module(), drivecpu65c02_snapshot_write_module(), drivecpu_snapshot_read_module(), drivecpu_snapshot_write_module(), driverom_snapshot_read(), driverom_snapshot_write(), dtlbasic_read_snapshot(), dtlbasic_write_snapshot(), eeprom_snapshot_read_module(), eeprom_snapshot_write_module(), event_snapshot_read_module(), event_snapshot_write_module(), fdd_snapshot_read_module(), fdd_snapshot_write_module(), flash040core_snapshot_read_module(), flash040core_snapshot_write_module(), fsdrive_snapshot_read_module(), fsdrive_snapshot_write_module(), keyboard_snapshot_read_module(), keyboard_snapshot_write_module(), m93c86_snapshot_read_module(), m93c86_snapshot_write_module(), maincpu_snapshot_read_module(), maincpu_snapshot_write_module(), memhacks_snapshot_read_modules(), memhacks_snapshot_write_modules(), mmc_snapshot_read_module(), mmc_snapshot_write_module(), myacia_snapshot_read_module(), myacia_snapshot_write_module(), mypia_snapshot_read_module(), mypia_snapshot_write_module(), plus256k_snapshot_read(), plus256k_snapshot_write(), plus60k_snapshot_read(), plus60k_snapshot_write(), riotcore_snapshot_read_module(), riotcore_snapshot_write_module(), scsi_snapshot_read_module(), scsi_snapshot_write_module(), sid_snapshot_read_module_extended(), sid_snapshot_read_module_simple(), sid_snapshot_write_module_extended(), sid_snapshot_write_module_simple(), spi_flash_snapshot_read_module(), spi_flash_snapshot_write_module(), t6721_snapshot_read_module(), t6721_snapshot_write_module(), tape_snapshot_read_module(), tape_snapshot_read_tapimage_module(), tape_snapshot_write_module(), tape_snapshot_write_tapimage_module(), tapeport_snapshot_read_module(), tapeport_snapshot_write_module(), tapertc_read_snapshot(), tapertc_write_snapshot(), tpicore_snapshot_read_module(), tpicore_snapshot_write_module(), userport_8bss_read_snapshot_module(), userport_8bss_write_snapshot_module(), userport_dac_read_snapshot_module(), userport_dac_write_snapshot_module(), userport_digimax_read_snapshot_module(), userport_digimax_write_snapshot_module(), userport_io_sim_read_snapshot_module(), userport_io_sim_write_snapshot_module(), userport_joystick_cga_read_snapshot_module(), userport_joystick_cga_write_snapshot_module(), userport_joystick_hit_read_snapshot_module(), userport_joystick_hit_write_snapshot_module(), userport_joystick_kingsoft_read_snapshot_module(), userport_joystick_kingsoft_write_snapshot_module(), userport_joystick_starbyte_read_snapshot_module(), userport_joystick_starbyte_write_snapshot_module(), userport_joystick_synergy_read_snapshot_module(), userport_joystick_synergy_write_snapshot_module(), userport_joystick_woj_read_snapshot_module(), userport_joystick_woj_write_snapshot_module(), userport_petscii_read_snapshot_module(), userport_petscii_write_snapshot_module(), userport_printer_read_snapshot_module(), userport_printer_write_snapshot_module(), userport_rtc_read_snapshot_module(), userport_rtc_write_snapshot_module(), userport_snapshot_read_module(), userport_snapshot_write_module(), userport_superpad64_read_snapshot_module(), userport_superpad64_write_snapshot_module(), vdrive_snapshot_module_read(), vdrive_snapshot_module_write(), viacore_snapshot_read_module(), viacore_snapshot_write_module(), vicii_snapshot_read_module(), vicii_snapshot_write_module(), wd1770_snapshot_read_module(), wd1770_snapshot_write_module(), ym3526_snapshot_read_module(), and ym3526_snapshot_write_module().
snapshot_module_create()
snapshot_module_t * snapshot_module_create (snapshot_t * s, const char * name, uint8_t major_version, uint8_t minor_version)
Referenced by ata_snapshot_write_module(), c64_256k_snapshot_write(), c64_glue_snapshot_write_module(), c64_snapshot_write_module(), c64_snapshot_write_rom_module(), ciacore_snapshot_write_module(), cmdhd_snapshot_write_module(), drive_snapshot_write_gcrimage_module(), drive_snapshot_write_image_module(), drive_snapshot_write_module(), drive_snapshot_write_p64image_module(), drivecpu65c02_snapshot_write_module(), drivecpu_snapshot_write_module(), driverom_snapshot_write(), dtlbasic_write_snapshot(), eeprom_snapshot_write_module(), event_snapshot_write_module(), fdd_snapshot_write_module(), flash040core_snapshot_write_module(), fsdrive_snapshot_write_module(), keyboard_snapshot_write_module(), m93c86_snapshot_write_module(), maincpu_snapshot_write_module(), memhacks_snapshot_write_modules(), mmc_snapshot_write_module(), myacia_snapshot_write_module(), mypia_snapshot_write_module(), plus256k_snapshot_write(), plus60k_snapshot_write(), riotcore_snapshot_write_module(), scsi_snapshot_write_module(), sid_snapshot_write_module_extended(), sid_snapshot_write_module_simple(), spi_flash_snapshot_write_module(), t6721_snapshot_write_module(), tape_snapshot_write_module(), tape_snapshot_write_tapimage_module(), tapeport_snapshot_write_module(), tapertc_write_snapshot(), tpicore_snapshot_write_module(), userport_8bss_write_snapshot_module(), userport_dac_write_snapshot_module(), userport_digimax_write_snapshot_module(), userport_io_sim_write_snapshot_module(), userport_joystick_cga_write_snapshot_module(), userport_joystick_hit_write_snapshot_module(), userport_joystick_kingsoft_write_snapshot_module(), userport_joystick_starbyte_write_snapshot_module(), userport_joystick_synergy_write_snapshot_module(), userport_joystick_woj_write_snapshot_module(), userport_petscii_write_snapshot_module(), userport_printer_write_snapshot_module(), userport_rtc_write_snapshot_module(), userport_snapshot_write_module(), userport_superpad64_write_snapshot_module(), vdrive_snapshot_module_write(), viacore_snapshot_write_module(), vicii_snapshot_write_module(), wd1770_snapshot_write_module(), and ym3526_snapshot_write_module().
snapshot_module_open()
snapshot_module_t * snapshot_module_open (snapshot_t * s, const char * name, uint8_t * major_version_return, uint8_t * minor_version_return)
Referenced by ata_snapshot_read_module(), c64_256k_snapshot_read(), c64_glue_snapshot_read_module(), c64_snapshot_read_module(), c64_snapshot_read_rom_module(), ciacore_snapshot_read_module(), cmdhd_snapshot_read_module(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), drivecpu65c02_snapshot_read_module(), drivecpu_snapshot_read_module(), driverom_snapshot_read(), dtlbasic_read_snapshot(), eeprom_snapshot_read_module(), event_snapshot_read_module(), fdd_snapshot_read_module(), flash040core_snapshot_read_module(), fsdrive_snapshot_read_module(), keyboard_snapshot_read_module(), m93c86_snapshot_read_module(), maincpu_snapshot_read_module(), memhacks_snapshot_read_modules(), mmc_snapshot_read_module(), myacia_snapshot_read_module(), mypia_snapshot_read_module(), plus256k_snapshot_read(), plus60k_snapshot_read(), riotcore_snapshot_read_module(), scsi_snapshot_read_module(), sid_snapshot_read_module_extended(), sid_snapshot_read_module_simple(), spi_flash_snapshot_read_module(), t6721_snapshot_read_module(), tape_snapshot_read_module(), tape_snapshot_read_tapimage_module(), tapeport_snapshot_read_module(), tapertc_read_snapshot(), tpicore_snapshot_read_module(), userport_8bss_read_snapshot_module(), userport_dac_read_snapshot_module(), userport_digimax_read_snapshot_module(), userport_io_sim_read_snapshot_module(), userport_joystick_cga_read_snapshot_module(), userport_joystick_hit_read_snapshot_module(), userport_joystick_kingsoft_read_snapshot_module(), userport_joystick_starbyte_read_snapshot_module(), userport_joystick_synergy_read_snapshot_module(), userport_joystick_woj_read_snapshot_module(), userport_petscii_read_snapshot_module(), userport_printer_read_snapshot_module(), userport_rtc_read_snapshot_module(), userport_snapshot_read_module(), userport_superpad64_read_snapshot_module(), vdrive_snapshot_module_read(), viacore_snapshot_read_module(), vicii_snapshot_read_module(), wd1770_snapshot_read_module(), and ym3526_snapshot_read_module().
snapshot_module_read_byte()
int snapshot_module_read_byte (snapshot_module_t * m, uint8_t * b_return)
Referenced by snapshot_module_read_byte_into_int(), and snapshot_module_read_byte_into_uint().
snapshot_module_read_byte_array()
int snapshot_module_read_byte_array (snapshot_module_t * m, uint8_t * b_return, unsigned int num)
snapshot_module_read_byte_into_int()
int snapshot_module_read_byte_into_int (snapshot_module_t * m, int * value_return)
snapshot_module_read_byte_into_uint()
int snapshot_module_read_byte_into_uint (snapshot_module_t * m, unsigned int * value_return)
snapshot_module_read_double()
int snapshot_module_read_double (snapshot_module_t * m, double * db_return)
snapshot_module_read_dword()
int snapshot_module_read_dword (snapshot_module_t * m, uint32_t * dw_return)
Referenced by snapshot_module_read_dword_into_int(), snapshot_module_read_dword_into_uint(), and snapshot_module_read_dword_into_ulong().
snapshot_module_read_dword_array()
int snapshot_module_read_dword_array (snapshot_module_t * m, uint32_t * dw_return, unsigned int num)
snapshot_module_read_dword_into_int()
int snapshot_module_read_dword_into_int (snapshot_module_t * m, int * value_return)
snapshot_module_read_dword_into_uint()
int snapshot_module_read_dword_into_uint (snapshot_module_t * m, unsigned int * value_return)
snapshot_module_read_dword_into_ulong()
int snapshot_module_read_dword_into_ulong (snapshot_module_t * m, unsigned long * value_return)
snapshot_module_read_qword()
int snapshot_module_read_qword (snapshot_module_t * m, uint64_t * qw_return)
Referenced by snapshot_module_read_qword_into_int64().
snapshot_module_read_qword_into_int64()
int snapshot_module_read_qword_into_int64 (snapshot_module_t * m, int64_t * value_return)
snapshot_module_read_string()
int snapshot_module_read_string (snapshot_module_t * m, char ** s)
snapshot_module_read_word()
int snapshot_module_read_word (snapshot_module_t * m, uint16_t * w_return)
Referenced by snapshot_module_read_word_into_int(), and snapshot_module_read_word_into_uint().
snapshot_module_read_word_array()
int snapshot_module_read_word_array (snapshot_module_t * m, uint16_t * w_return, unsigned int num)
snapshot_module_read_word_into_int()
int snapshot_module_read_word_into_int (snapshot_module_t * m, int * value_return)
snapshot_module_read_word_into_uint()
int snapshot_module_read_word_into_uint (snapshot_module_t * m, unsigned int * value_return)
snapshot_module_write_byte()
int snapshot_module_write_byte (snapshot_module_t * m, uint8_t data)
snapshot_module_write_byte_array()
int snapshot_module_write_byte_array (snapshot_module_t * m, const uint8_t * data, unsigned int num)
snapshot_module_write_double()
int snapshot_module_write_double (snapshot_module_t * m, double db)
snapshot_module_write_dword()
int snapshot_module_write_dword (snapshot_module_t * m, uint32_t data)
snapshot_module_write_dword_array()
int snapshot_module_write_dword_array (snapshot_module_t * m, const uint32_t * data, unsigned int num)
snapshot_module_write_padded_string()
int snapshot_module_write_padded_string (snapshot_module_t * m, const char * s, uint8_t pad_char, int len)
snapshot_module_write_qword()
int snapshot_module_write_qword (snapshot_module_t * m, uint64_t data)
snapshot_module_write_string()
int snapshot_module_write_string (snapshot_module_t * m, const char * s)
snapshot_module_write_word()
int snapshot_module_write_word (snapshot_module_t * m, uint16_t data)
snapshot_module_write_word_array()
int snapshot_module_write_word_array (snapshot_module_t * m, const uint16_t * data, unsigned int num)
snapshot_open()
snapshot_t * snapshot_open (const char * filename, uint8_t * major_version_return, uint8_t * minor_version_return, const char * snapshot_machine_name)
< read mode (binary)
Referenced by autostart_snapshot(), c64_snapshot_read(), and event_playback_start_trap().
snapshot_set_error()
void snapshot_set_error (int error)
Referenced by ata_snapshot_read_module(), c64_256k_snapshot_read(), c64_glue_snapshot_read_module(), c64_snapshot_read(), c64_snapshot_read_module(), c64_snapshot_read_rom_module(), cmdhd_snapshot_read_module(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), driverom_snapshot_read(), dtlbasic_read_snapshot(), eeprom_snapshot_write_module(), fdd_snapshot_read_module(), fsdrive_snapshot_read_module(), keyboard_snapshot_read_module(), machine_read_snapshot(), machine_write_snapshot(), memhacks_snapshot_read_modules(), mmc_snapshot_write_module(), myacia_snapshot_read_module(), plus256k_snapshot_read(), plus60k_snapshot_read(), riotcore_snapshot_read_module(), scsi_snapshot_read_module(), sid_snapshot_read_module_extended(), sid_snapshot_read_module_simple(), t6721_snapshot_write_module(), tapertc_read_snapshot(), tpicore_snapshot_read_module(), userport_8bss_read_snapshot_module(), userport_dac_read_snapshot_module(), userport_digimax_read_snapshot_module(), userport_io_sim_read_snapshot_module(), userport_joystick_cga_read_snapshot_module(), userport_joystick_hit_read_snapshot_module(), userport_joystick_kingsoft_read_snapshot_module(), userport_joystick_starbyte_read_snapshot_module(), userport_joystick_synergy_read_snapshot_module(), userport_joystick_woj_read_snapshot_module(), userport_petscii_read_snapshot_module(), userport_printer_read_snapshot_module(), userport_rtc_read_snapshot_module(), userport_superpad64_read_snapshot_module(), viacore_snapshot_read_module(), and wd1770_snapshot_read_module().
snapshot_version_is_bigger()
int snapshot_version_is_bigger (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version > required version
Referenced by c64_256k_snapshot_read(), c64_glue_snapshot_read_module(), c64_snapshot_read_module(), c64_snapshot_read_rom_module(), cmdhd_snapshot_read_module(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), driverom_snapshot_read(), dtlbasic_read_snapshot(), fdd_snapshot_read_module(), fsdrive_snapshot_read_module(), keyboard_snapshot_read_module(), m93c86_snapshot_read_module(), memhacks_snapshot_read_modules(), myacia_snapshot_read_module(), plus256k_snapshot_read(), plus60k_snapshot_read(), riotcore_snapshot_read_module(), scsi_snapshot_read_module(), sid_snapshot_read_module_extended(), sid_snapshot_read_module_simple(), spi_flash_snapshot_read_module(), tape_snapshot_read_tapimage_module(), tapertc_read_snapshot(), tpicore_snapshot_read_module(), userport_8bss_read_snapshot_module(), userport_dac_read_snapshot_module(), userport_digimax_read_snapshot_module(), userport_io_sim_read_snapshot_module(), userport_joystick_cga_read_snapshot_module(), userport_joystick_hit_read_snapshot_module(), userport_joystick_kingsoft_read_snapshot_module(), userport_joystick_starbyte_read_snapshot_module(), userport_joystick_synergy_read_snapshot_module(), userport_joystick_woj_read_snapshot_module(), userport_petscii_read_snapshot_module(), userport_printer_read_snapshot_module(), userport_rtc_read_snapshot_module(), userport_superpad64_read_snapshot_module(), viacore_snapshot_read_module(), vicii_snapshot_read_module(), and wd1770_snapshot_read_module().
snapshot_version_is_equal()
int snapshot_version_is_equal (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version == required version
Referenced by ata_snapshot_read_module(), c64_snapshot_read(), sid_snapshot_read_module_simple(), tapeport_snapshot_read_module(), and userport_snapshot_read_module().
snapshot_version_is_smaller()
int snapshot_version_is_smaller (uint8_t major_version, uint8_t minor_version, uint8_t major_version_required, uint8_t minor_version_required)
check if version < required version
Referenced by c64_snapshot_read_module(), drive_snapshot_read_gcrimage_module(), drive_snapshot_read_image_module(), drive_snapshot_read_module(), drive_snapshot_read_p64image_module(), sid_snapshot_read_module_extended(), and sid_snapshot_read_module_simple().