x128: cmdline.h File Reference
cmdline.h File Reference
Data Structures
struct cmdline_option_s
struct cmdline_option_ram_s
union char_func
union to change pointer types for dynamic translations
Macros
#define CMDLINE_ATTRIB_NONE 0
#define CMDLINE_ATTRIB_NEED_ARGS (1 << 0)
#define CMDLINE_ATTRIB_NEED_BRACKETS (1 << 1)
#define CMDLINE_ATTRIB_DYNAMIC_DESCRIPTION (1 << 2)
#define CMDLINE_LIST_END { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
Typedefs
typedef enum cmdline_option_type cmdline_option_type_t
This describes a command-line option.
typedef struct cmdline_option_s cmdline_option_t
typedef struct cmdline_option_ram_s cmdline_option_ram_t
Enumerations
enum cmdline_option_type {
SET_RESOURCE ,
CALL_FUNCTION
}
This describes a command-line option.
Functions
int cmdline_init (void)
int cmdline_register_options (const cmdline_option_t *c)
void cmdline_shutdown (void)
int cmdline_parse (int *argc, char **argv)
void cmdline_show_help (void *userparam)
Dump command line options on stdout.
char * cmdline_options_string (void)
char * cmdline_options_get_name (int counter)
const char * cmdline_options_get_param (int counter)
char * cmdline_options_get_description (int counter)
int cmdline_get_num_options (void)
void cmdline_log_active (void)
Macro Definition Documentation
CMDLINE_ATTRIB_DYNAMIC_DESCRIPTION
#define CMDLINE_ATTRIB_DYNAMIC_DESCRIPTION (1 << 2)
CMDLINE_ATTRIB_NEED_ARGS
#define CMDLINE_ATTRIB_NEED_ARGS (1 << 0)
CMDLINE_ATTRIB_NEED_BRACKETS
#define CMDLINE_ATTRIB_NEED_BRACKETS (1 << 1)
CMDLINE_ATTRIB_NONE
#define CMDLINE_ATTRIB_NONE 0
CMDLINE_LIST_END
#define CMDLINE_LIST_END { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
Typedef Documentation
cmdline_option_ram_t
typedef struct cmdline_option_ram_s cmdline_option_ram_t
cmdline_option_t
typedef struct cmdline_option_s cmdline_option_t
cmdline_option_type_t
typedef enum cmdline_option_type cmdline_option_type_t
This describes a command-line option.
Enumeration Type Documentation
cmdline_option_type
enum cmdline_option_type
This describes a command-line option.
Enumerator
SET_RESOURCE
CALL_FUNCTION
Function Documentation
cmdline_get_num_options()
int cmdline_get_num_options (void)
Referenced by create_content_widget().
cmdline_init()
int cmdline_init (void)
Referenced by init_cmdline_options().
cmdline_log_active()
void cmdline_log_active (void)
cmdline_options_get_description()
char * cmdline_options_get_description (int counter)
Referenced by cmdline_options_string(), cmdline_show_help(), and create_content_widget().
cmdline_options_get_name()
char * cmdline_options_get_name (int counter)
Referenced by create_content_widget().
cmdline_options_get_param()
const char * cmdline_options_get_param (int counter)
Referenced by cmdline_log_active(), cmdline_options_string(), cmdline_show_help(), and create_content_widget().
cmdline_options_string()
char * cmdline_options_string (void)
cmdline_parse()
int cmdline_parse (int * argc, char ** argv)
Referenced by initcmdline_check_args().
cmdline_register_options()
int cmdline_register_options (const cmdline_option_t * c)
Referenced by artstudiodrv_cmdline_options_init(), autostart_cmdline_options_init(), c128_cmdline_options_init(), c128cartridge_cmdline_options_init(), c128gmod2_cmdline_options_init(), debug_cmdline_options_init(), drive_cmdline_options_init(), driver_select_init_cmdline_options(), driver_select_userport_init_cmdline_options(), event_cmdline_options_init(), ffmpegexedrv_cmdline_options_init(), file_system_cmdline_options_init(), fliplist_cmdline_options_init(), fsdevice_cmdline_options_init(), functionrom_cmdline_options_init(), iec128dcr_cmdline_options_init(), iec_cmdline_options_init(), ieee_cmdline_options_init(), initcmdline_init(), interface_serial_init_cmdline_options(), kbdbuf_cmdline_options_init(), keyboard_cmdline_options_init(), keymap_cmdline_options_init(), koaladrv_cmdline_options_init(), log_cmdline_options_init(), machine_common_cmdline_options_init(), minipaintdrv_cmdline_options_init(), mmu_cmdline_options_init(), monitor_binary_cmdline_options_init(), monitor_cmdline_options_init(), monitor_network_cmdline_options_init(), mouse_ps2_cmdline_options_init(), myacia_init_cmdline_options(), network_cmdline_options_init(), output_select_init_cmdline_options(), output_select_userport_init_cmdline_options(), output_text_init_cmdline_options(), ram_cmdline_options_init(), raster_cmdline_options_chip_init(), romset_cmdline_options_init(), rs232drv_cmdline_options_init(), rsuser_cmdline_options_init(), sampler_cmdline_options_init(), sampler_file_cmdline_options_init(), serial_iec_device_cmdline_options_init(), sid_cmdline_options_init(), sound_cmdline_options_init(), sysfile_cmdline_options_init(), tapecart_cmdline_options_init(), tapeport_cmdline_options_init(), tapertc_cmdline_options_init(), tcbm_cmdline_options_init(), traps_cmdline_options_init(), ui_cmdline_options_init(), ui_hotkeys_cmdline_options_init(), userport_cmdline_options_init(), userport_rtc_58321a_cmdline_options_init(), userport_rtc_ds1307_cmdline_options_init(), vdc_cmdline_options_init(), vicii_cmdline_options_init(), video_cmdline_options_chip_init(), vsync_cmdline_options_init(), and zmbvdrv_cmdline_options_init().
cmdline_show_help()
void cmdline_show_help (void * userparam)
Dump command line options on stdout.
Parameters
[in] num_options number of options
[in] options list of options
[in] userparm ignored for some reason
XXX: this function and its brethren where all over archdep, while basically doing the same thing.
On Windows it seems we need to use x64 -help|more to make the list appear on the console. (thanks Greg)
Once this works, we can remove a lot of 'uicmdline.c' files from various src/arch/$arch directories. – compyx, 2017-08-12
Referenced by cmdline_help().
cmdline_shutdown()
void cmdline_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().