x128: arch/gtk3/widgets/settings_speed.c File Reference
settings_speed.c File Reference
GTK3 speed control central widget for the settings dialog.
#include "vice.h"
#include <gtk/gtk.h>
#include "lib.h"
#include "machine.h"
#include "ui.h"
#include "resources.h"
#include "vsync.h"
#include "basewidgets.h"
#include "debug_gtk3.h"
#include "resourcecheckbutton.h"
#include "widgethelpers.h"
#include "speedwidget.h"
#include "settings_speed.h"
Functions
static void warp_callback (GtkWidget *widget, gpointer data)
Event handler for the 'Warp mode' checkbox.
static void pause_callback (GtkWidget *widget, gpointer data)
Event handler for the 'pause' checkbox.
static GtkWidget * create_warp_checkbox (void)
Generate the 'Warp mode' checkbox.
static GtkWidget * create_pause_checkbox (void)
Generate the 'Pause emulation' checkbox.
GtkWidget * settings_speed_widget_create (GtkWidget *widget)
Create the composite speed settings widget.
Variables
static GtkWidget * checkbox_pause = NULL
Checkbox indicating 'Pause'.
static GtkWidget * checkbox_warp = NULL
Checkbox indicating 'Warp'.
Detailed Description
GTK3 speed control central widget for the settings dialog.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_pause_checkbox()
static GtkWidget * create_pause_checkbox (void) static
Generate the 'Pause emulation' checkbox.
Returns
Pause checkbox
Referenced by settings_speed_widget_create().
create_warp_checkbox()
static GtkWidget * create_warp_checkbox (void) static
Generate the 'Warp mode' checkbox.
Returns
Warp checkbox
Referenced by settings_speed_widget_create().
pause_callback()
static void pause_callback (GtkWidget * widget, gpointer data) static
Event handler for the 'pause' checkbox.
Parameters
[in] widget widget triggering the event
[in] data data for the event (unused)
Referenced by create_pause_checkbox().
settings_speed_widget_create()
GtkWidget * settings_speed_widget_create (GtkWidget * widget)
Create the composite speed settings widget.
This will create a composite widget to control emulation speed, refresh rate and warp/pause settings. To be used as the 'central widget' of the settings dialog.
Parameters
[in] widget parent widget (unused)
Returns
speed settings widget
Todo:
Add 'advance frame' button
warp_callback()
static void warp_callback (GtkWidget * widget, gpointer data) static
Event handler for the 'Warp mode' checkbox.
Parameters
[in] widget widget triggering the event
[in] data data for the event (unused)
Referenced by create_warp_checkbox().
Variable Documentation
checkbox_pause
GtkWidget* checkbox_pause = NULL static
Checkbox indicating 'Pause'.
Referenced by settings_speed_widget_create().
checkbox_warp
GtkWidget* checkbox_warp = NULL static
Checkbox indicating 'Warp'.
Referenced by settings_speed_widget_create().