vsid: video/video-canvas.c File Reference
video-canvas.c File Reference
#include "vice.h"
#include "videoarch.h"
#include <stdio.h>
#include <stdlib.h>
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "types.h"
#include "video-canvas.h"
#include "video-color.h"
#include "video-render.h"
#include "video.h"
#include "viewport.h"
Macros
#define DEBUG_VIDEO 1
#define DBG(_x_) log_debug _x_
#define TRACKED_CANVAS_MAX 2
#define MIN(a, b) ((a) < (b) ? (a) : (b))
Temporary!
Functions
video_canvas_t * video_canvas_init (void)
called from raster/raster-resources.c:raster_resources_chip_init
void video_canvas_shutdown (video_canvas_t *canvas)
void video_canvas_render (video_canvas_t *canvas, uint8_t *trg, int width, int height, int xs, int ys, int xt, int yt, int pitcht)
void video_canvas_refresh_all_tracked (void)
Force refresh all tracked canvases.
void video_canvas_refresh_all (video_canvas_t *canvas)
int video_canvas_palette_set (struct video_canvas_s *canvas, struct palette_s *palette)
This will go away.
void video_canvas_create_set (struct video_canvas_s *canvas)
Variables
static video_canvas_t * tracked_canvas [2]
Used to enable video_canvas_refresh_all_tracked()
Macro Definition Documentation
DBG
#define DBG (_x_) log_debug _x_
DEBUG_VIDEO
#define DEBUG_VIDEO 1
MIN
#define MIN (a, b) ((a) < (b) ? (a) : (b))
Temporary!
TRACKED_CANVAS_MAX
#define TRACKED_CANVAS_MAX 2
Function Documentation
video_canvas_create_set()
void video_canvas_create_set (struct video_canvas_s * canvas)
Referenced by realize_canvas().
video_canvas_init()
video_canvas_t * video_canvas_init (void)
called from raster/raster-resources.c:raster_resources_chip_init
Referenced by raster_resources_chip_init().
video_canvas_palette_set()
int video_canvas_palette_set (struct video_canvas_s * canvas, struct palette_s * palette)
This will go away.
Referenced by video_color_update_palette().
video_canvas_refresh_all()
void video_canvas_refresh_all (video_canvas_t * canvas)
Referenced by raster_canvas_handle_end_of_frame(), raster_realize(), set_chip_rendermode(), set_double_scan_enabled(), video_canvas_palette_set(), video_canvas_refresh_all_tracked(), and video_viewport_resize().
video_canvas_refresh_all_tracked()
void video_canvas_refresh_all_tracked (void)
Force refresh all tracked canvases.
Added to enable visible updates each time the monitor prompts for input.
Referenced by monitor_startup().
video_canvas_render()
void video_canvas_render (video_canvas_t * canvas, uint8_t * trg, int width, int height, int xs, int ys, int xt, int yt, int pitcht)
Referenced by vice_opengl_refresh_rect().
video_canvas_shutdown()
void video_canvas_shutdown (video_canvas_t * canvas)
Referenced by raster_resources_chip_shutdown().
Variable Documentation
tracked_canvas
video_canvas_t* tracked_canvas[2] static
Used to enable video_canvas_refresh_all_tracked()
Referenced by video_canvas_init(), video_canvas_refresh_all_tracked(), and video_canvas_shutdown().