vsid: drive/iec/cmdhd.c File Reference
cmdhd.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdint.h>
#include "archdep.h"
#include "diskimage.h"
#include "debug.h"
#include "drive.h"
#include "drivesync.h"
#include "drivetypes.h"
#include "iecbus.h"
#include "iecdrive.h"
#include "interrupt.h"
#include "lib.h"
#include "types.h"
#include "cmdhd.h"
#include "util.h"
#include "diskimage/fsimage.h"
#include "rtc/rtc-72421.h"
#include "resources.h"
Data Structures
struct drivevia_context_s
Macros
#define LOG LOG_DEFAULT
#define ERR LOG_ERR
#define CLOG(_x_)
#define IDBG(_x_)
#define BLOG(_x_)
#define CRIT(_x_) log_message _x_
#define iecbus (viap->v_iecbus)
#define CMD_STATE_DATAOUT 0x00
#define CMD_STATE_COMMAND 0x01
#define CMD_STATE_DATAIN 0x04
#define CMD_STATE_STATUS 0x05
#define CMD_STATE_MESSAGEOUT 0x03
#define CMD_STATE_MESSAGEIN 0x07
#define DEBUG_IEC_DRV_WRITE(_data)
#define DEBUG_IEC_DRV_READ(_data)
#define storedebug()
#define readdebug()
#define CMDHD_SNAP_MAJOR 1
#define CMDHD_SNAP_MINOR 0
Typedefs
typedef struct drivevia_context_s drivevia_context_t
Functions
static uint8_t drive_read_rom (diskunit_context_t *drv, uint16_t address)
copy some functions here so we don't make them external
static uint8_t drive_read_ram (diskunit_context_t *drv, uint16_t address)
static void drive_store_ram (diskunit_context_t *drv, uint16_t address, uint8_t value)
static void reset_alarm_handler (CLOCK offset, void *data)
static int cmdhd_has_sig (unsigned char *buf)
returns 0 if block has CMCHD signature at end
static void cmdhd_scsiread (struct scsi_context_s *scsi)
static void cmdhd_scsiwrite (struct scsi_context_s *scsi)
static void cmdhd_scsiformat (struct scsi_context_s *scsi)
We don't actually format the disk, we just remove the 16 byte CMD signature.
void cmdbus_init (void)
Set all the inputs high, like the pull-up resistors do.
void cmdbus_update (void)
Calculate the data/bus values.
static void set_pa (struct _i8255a_state *ctx, uint8_t byte, int8_t reg)
U11 or i8255a interfacing.
static uint8_t get_pa (struct _i8255a_state *ctx, int8_t reg)
static void set_pb (struct _i8255a_state *ctx, uint8_t byte, int8_t reg)
static uint8_t get_pb (struct _i8255a_state *ctx, int8_t reg)
static int cmdhd_patn_changed (unsigned int unit, int new, int old)
Called to deal with how PATN changes PREADY.
void cmdbus_patn_changed (int new, int old)
Update ALL TDE units when PATN changed.
static void set_pc (struct _i8255a_state *ctx, uint8_t byte, int8_t reg)
static uint8_t get_pc (struct _i8255a_state *ctx, int8_t reg)
static void updateleds (diskunit_context_t *ctxptr)
void cmdhd_store (diskunit_context_t *ctxptr, uint16_t addr, uint8_t data)
uint8_t cmdhd_read (diskunit_context_t *ctxptr, uint16_t addr)
uint8_t cmdhd_peek (diskunit_context_t *ctxptr, uint16_t addr)
int cmdhd_dump (diskunit_context_t *ctxptr, uint16_t addr)
static void set_ca2 (via_context_t *via_context, int state)
static void set_cb2 (via_context_t *via_context, int state, int offset)
static void set_int (via_context_t *via_context, unsigned int int_num, int value, CLOCK rclk)
static void restore_int (via_context_t *via_context, unsigned int int_num, int value)
static void undump_pra (via_context_t *via_context, uint8_t byte)
static void undump_prb10 (via_context_t *via_context, uint8_t byte)
static void store_pra9 (via_context_t *via_context, uint8_t byte, uint8_t oldpa, uint16_t addr)
static uint8_t read_pra9 (via_context_t *via_context, uint16_t addr)
static void store_prb9 (via_context_t *via_context, uint8_t byte, uint8_t p_oldpb, uint16_t addr)
static uint8_t read_prb9 (via_context_t *via_context)
static uint8_t read_prb10 (via_context_t *via_context)
static void store_prb10 (via_context_t *via_context, uint8_t byte, uint8_t oldpb, uint16_t addr)
static void undump_prb (via_context_t *via_context, uint8_t byte)
static void store_pra10 (via_context_t *via_context, uint8_t byte, uint8_t p_oldpb, uint16_t addr)
static void undump_pcr (via_context_t *via_context, uint8_t byte)
static uint8_t store_pcr (via_context_t *via_context, uint8_t byte, uint16_t addr)
static void undump_acr (via_context_t *via_context, uint8_t byte)
static void store_acr (via_context_t *via_context, uint8_t byte)
static void store_sr (via_context_t *via_context, uint8_t byte)
static void store_sr10 (via_context_t *via_context, uint8_t byte)
static void store_t2l (via_context_t *via_context, uint8_t byte)
static void reset (via_context_t *via_context)
static uint8_t read_pra10 (via_context_t *via_context, uint16_t addr)
void cmdhd_setup_context (diskunit_context_t *ctxptr)
void cmdhd_init (diskunit_context_t *ctxptr)
void cmdhd_shutdown (cmdhd_context_t *hd)
static void cmdhd_findbaselba (cmdhd_context_t *hd)
void cmdhd_reset (cmdhd_context_t *hd)
int cmdhd_attach_image (disk_image_t *image, unsigned int unit)
int cmdhd_detach_image (disk_image_t *image, unsigned int unit)
int cmdhd_update_maxsize (unsigned int size, unsigned int unit)
int cmdhd_snapshot_write_module (cmdhd_context_t *drv, struct snapshot_s *s)
int cmdhd_snapshot_read_module (cmdhd_context_t *drv, struct snapshot_s *s)
Variables
cmdbus_t cmdbus
Macro Definition Documentation
BLOG
#define BLOG (_x_)
CLOG
#define CLOG (_x_)
CMD_STATE_COMMAND
#define CMD_STATE_COMMAND 0x01
CMD_STATE_DATAIN
#define CMD_STATE_DATAIN 0x04
CMD_STATE_DATAOUT
#define CMD_STATE_DATAOUT 0x00
CMD_STATE_MESSAGEIN
#define CMD_STATE_MESSAGEIN 0x07
CMD_STATE_MESSAGEOUT
#define CMD_STATE_MESSAGEOUT 0x03
CMD_STATE_STATUS
#define CMD_STATE_STATUS 0x05
CMDHD_SNAP_MAJOR
#define CMDHD_SNAP_MAJOR 1
CMDHD_SNAP_MINOR
#define CMDHD_SNAP_MINOR 0
CRIT
#define CRIT (_x_) log_message _x_
DEBUG_IEC_DRV_READ
#define DEBUG_IEC_DRV_READ (_data)
DEBUG_IEC_DRV_WRITE
#define DEBUG_IEC_DRV_WRITE (_data)
ERR
#define ERR LOG_ERR
IDBG
#define IDBG (_x_)
iecbus
#define iecbus (viap->v_iecbus)
LOG
#define LOG LOG_DEFAULT
readdebug
#define readdebug ()
storedebug
#define storedebug ()
Typedef Documentation
drivevia_context_t
typedef struct drivevia_context_s drivevia_context_t
Function Documentation
cmdbus_init()
void cmdbus_init (void)
Set all the inputs high, like the pull-up resistors do.
cmdbus_patn_changed()
void cmdbus_patn_changed (int new, int old)
Update ALL TDE units when PATN changed.
called from ramlink
cmdbus_update()
void cmdbus_update (void)
Calculate the data/bus values.
Referenced by set_pa(), and set_pc().
cmdhd_attach_image()
int cmdhd_attach_image (disk_image_t * image, unsigned int unit)
< HD in ASCII for CMDHD
Referenced by iec_drive_image_attach().
cmdhd_detach_image()
int cmdhd_detach_image (disk_image_t * image, unsigned int unit)
< HD in ASCII for CMDHD
Referenced by iec_drive_image_detach().
cmdhd_dump()
int cmdhd_dump (diskunit_context_t * ctxptr, uint16_t addr)
cmdhd_findbaselba()
static void cmdhd_findbaselba (cmdhd_context_t * hd) static
Referenced by cmdhd_attach_image(), and cmdhd_reset().
cmdhd_has_sig()
static int cmdhd_has_sig (unsigned char * buf) static
returns 0 if block has CMCHD signature at end
Referenced by cmdhd_findbaselba(), cmdhd_reset(), cmdhd_scsiformat(), and cmdhd_scsiread().
cmdhd_init()
void cmdhd_init (diskunit_context_t * ctxptr)
Referenced by iec_drive_init().
cmdhd_patn_changed()
static int cmdhd_patn_changed (unsigned int unit, int new, int old) static
Called to deal with how PATN changes PREADY.
"new" and "old", 0 or 1, are PATN, not /PATN
CMDHD's have a circuit which drives /PREADY
It has a FF where PC7 controls /CLR and PATN is the CLK
The output is NANDed with PATN which drives /PREADY
/PREADY is also connected to a buffer (OC) driven by PC7
< ASCII for HD
Referenced by cmdbus_patn_changed(), and set_pc().
cmdhd_peek()
uint8_t cmdhd_peek (diskunit_context_t * ctxptr, uint16_t addr)
cmdhd_read()
uint8_t cmdhd_read (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by memiec_init().
cmdhd_reset()
void cmdhd_reset (cmdhd_context_t * hd)
Referenced by iec_drive_reset().
cmdhd_scsiformat()
static void cmdhd_scsiformat (struct scsi_context_s * scsi) static
We don't actually format the disk, we just remove the 16 byte CMD signature.
Referenced by cmdhd_init().
cmdhd_scsiread()
static void cmdhd_scsiread (struct scsi_context_s * scsi) static
Referenced by cmdhd_init().
cmdhd_scsiwrite()
static void cmdhd_scsiwrite (struct scsi_context_s * scsi) static
Referenced by cmdhd_init().
cmdhd_setup_context()
void cmdhd_setup_context (diskunit_context_t * ctxptr)
Referenced by iec_drive_setup_context().
cmdhd_shutdown()
void cmdhd_shutdown (cmdhd_context_t * hd)
alarm_destroy(hd->reset_alarm);
Referenced by iec_drive_shutdown().
cmdhd_snapshot_read_module()
int cmdhd_snapshot_read_module (cmdhd_context_t * drv, struct snapshot_s * s)
Referenced by iec_drive_snapshot_read().
cmdhd_snapshot_write_module()
int cmdhd_snapshot_write_module (cmdhd_context_t * drv, struct snapshot_s * s)
Referenced by iec_drive_snapshot_write().
cmdhd_store()
void cmdhd_store (diskunit_context_t * ctxptr, uint16_t addr, uint8_t data)
Referenced by memiec_init().
cmdhd_update_maxsize()
int cmdhd_update_maxsize (unsigned int size, unsigned int unit)
Referenced by set_drive_fixed().
drive_read_ram()
static uint8_t drive_read_ram (diskunit_context_t * drv, uint16_t address) static
Referenced by cmdhd_read().
drive_read_rom()
static uint8_t drive_read_rom (diskunit_context_t * drv, uint16_t address) static
copy some functions here so we don't make them external
Referenced by cmdhd_read().
drive_store_ram()
static void drive_store_ram (diskunit_context_t * drv, uint16_t address, uint8_t value) static
Referenced by cmdhd_store().
get_pa()
static uint8_t get_pa (struct _i8255a_state * ctx, int8_t reg) static
Referenced by cmdhd_setup_context().
get_pb()
static uint8_t get_pb (struct _i8255a_state * ctx, int8_t reg) static
Referenced by cmdhd_setup_context().
get_pc()
static uint8_t get_pc (struct _i8255a_state * ctx, int8_t reg) static
Referenced by cmdhd_setup_context().
read_pra10()
static uint8_t read_pra10 (via_context_t * via_context, uint16_t addr) static
Referenced by cmdhd_setup_context().
read_pra9()
static uint8_t read_pra9 (via_context_t * via_context, uint16_t addr) static
< Port A
Referenced by cmdhd_setup_context().
read_prb10()
static uint8_t read_prb10 (via_context_t * via_context) static
< Port B
< Port B
Referenced by cmdhd_setup_context().
read_prb9()
static uint8_t read_prb9 (via_context_t * via_context) static
< Peripheral control register
Referenced by cmdhd_setup_context().
reset()
static void reset (via_context_t * via_context) static
Referenced by add_rom_chooser(), cmdhd_setup_context(), sampler_reset(), sound_machine_reset(), and userport_reset().
reset_alarm_handler()
static void reset_alarm_handler (CLOCK offset, void * data) static
Referenced by cmdhd_setup_context().
restore_int()
static void restore_int (via_context_t * via_context, unsigned int int_num, int value) static
Referenced by cmdhd_setup_context().
set_ca2()
static void set_ca2 (via_context_t * via_context, int state) static
Referenced by cmdhd_setup_context().
set_cb2()
static void set_cb2 (via_context_t * via_context, int state, int offset) static
Referenced by cmdhd_setup_context().
set_int()
static void set_int (via_context_t * via_context, unsigned int int_num, int value, CLOCK rclk) static
Referenced by cmdhd_setup_context().
set_pa()
static void set_pa (struct _i8255a_state * ctx, uint8_t byte, int8_t reg) static
U11 or i8255a interfacing.
Port A is for CMD Parallel bus, input/output, data only
Referenced by cmdhd_setup_context().
set_pb()
static void set_pb (struct _i8255a_state * ctx, uint8_t byte, int8_t reg) static
Referenced by cmdhd_setup_context().
set_pc()
static void set_pc (struct _i8255a_state * ctx, uint8_t byte, int8_t reg) static
Referenced by cmdhd_setup_context().
store_acr()
static void store_acr (via_context_t * via_context, uint8_t byte) static
Referenced by cmdhd_setup_context().
store_pcr()
static uint8_t store_pcr (via_context_t * via_context, uint8_t byte, uint16_t addr) static
Referenced by cmdhd_setup_context().
store_pra10()
static void store_pra10 (via_context_t * via_context, uint8_t byte, uint8_t p_oldpb, uint16_t addr) static
Referenced by cmdhd_setup_context().
store_pra9()
static void store_pra9 (via_context_t * via_context, uint8_t byte, uint8_t oldpa, uint16_t addr) static
< Port A
Referenced by cmdhd_setup_context().
store_prb10()
static void store_prb10 (via_context_t * via_context, uint8_t byte, uint8_t oldpb, uint16_t addr) static
Referenced by cmdhd_setup_context().
store_prb9()
static void store_prb9 (via_context_t * via_context, uint8_t byte, uint8_t p_oldpb, uint16_t addr) static
Referenced by cmdhd_setup_context().
store_sr()
static void store_sr (via_context_t * via_context, uint8_t byte) static
Referenced by cmdhd_setup_context().
store_sr10()
static void store_sr10 (via_context_t * via_context, uint8_t byte) static
Referenced by cmdhd_setup_context().
store_t2l()
static void store_t2l (via_context_t * via_context, uint8_t byte) static
Referenced by cmdhd_setup_context().
undump_acr()
static void undump_acr (via_context_t * via_context, uint8_t byte) static
Referenced by cmdhd_setup_context().
undump_pcr()
static void undump_pcr (via_context_t * via_context, uint8_t byte) static
Referenced by cmdhd_setup_context().
undump_pra()
static void undump_pra (via_context_t * via_context, uint8_t byte) static
Referenced by cmdhd_setup_context().
undump_prb()
static void undump_prb (via_context_t * via_context, uint8_t byte) static
Referenced by cmdhd_setup_context().
undump_prb10()
static void undump_prb10 (via_context_t * via_context, uint8_t byte) static
Referenced by cmdhd_setup_context().
updateleds()
static void updateleds (diskunit_context_t * ctxptr) static
Referenced by cmdhd_store().
Variable Documentation
cmdbus
cmdbus_t cmdbus
Referenced by cmdbus_init(), cmdbus_update(), cmdhd_detach_image(), cmdhd_patn_changed(), cmdhd_reset(), get_pa(), get_pb(), set_pa(), and set_pc().