vsid: lib/linenoise-ng/linenoise.cpp File Reference
linenoise.cpp File Reference
#include <signal.h>
#include <termios.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <cctype>
#include <wctype.h>
#include <stdio.h>
#include <errno.h>
#include <fcntl.h>
#include "linenoise.h"
#include "ConvertUTF.h"
#include "wcwidth.h"
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
Data Structures
class Utf32String
class Utf8String
struct linenoiseCompletions
Linenoise completions object.
struct PromptBase
struct PromptInfo
struct DynamicPrompt
class KillRing
class InputBuffer
struct EscapeSequenceProcessing::CharacterDispatch
Namespaces
namespace linenoise_ng
Recompute widths of all characters in a char32_t buffer.
namespace EscapeSequenceProcessing
Macros
#define LINENOISE_DEFAULT_HISTORY_MAX_LEN 100
#define LINENOISE_MAX_LINE 4096
#define ctrlChar(upperCaseASCII) (upperCaseASCII - 0x40)
#define _DEBUG_LINUX_KEYBOARD
Typedefs
typedef char32_t(* EscapeSequenceProcessing::CharacterDispatchRoutine) (char32_t)
Functions
static ConversionResult copyString8to32 (char32_t *dst, size_t dstSize, size_t &dstCount, const char *src)
static ConversionResult copyString8to32 (char32_t *dst, size_t dstSize, size_t &dstCount, const uint8_t *src)
static size_t strlen32 (const char32_t *str)
static size_t strlen8 (const uint8_t *str)
static uint8_t * strdup8 (const char *src)
static void copyString32to8 (char *dst, size_t dstSize, size_t *dstCount, const char32_t *src, size_t srcSize)
static void copyString32to8 (char *dst, size_t dstLen, const char32_t *src)
static void copyString32 (char32_t *dst, const char32_t *src, size_t len)
static int strncmp32 (const char32_t *left, const char32_t *right, size_t len)
static int write32 (int fd, char32_t *text32, int len32)
int linenoise_ng::mk_wcwidth (char32_t ucs)
static void recomputeCharacterWidths (const char32_t *text, char *widths, int charCount)
static void calculateScreenPosition (int x, int y, int screenColumns, int charCount, int &xOut, int &yOut)
Calculate a new screen position given a starting position, screen width and character count.
int linenoise_ng::mk_wcswidth (const char32_t *pwcs, size_t n)
static int calculateColumnPosition (char32_t *buf32, int len)
static bool isControlChar (char32_t testChar)
static void linenoiseAtExit (void)
static bool isUnsupportedTerm (void)
static void beep ()
void linenoiseHistoryFree (void)
static int enableRawMode (void)
static void disableRawMode (void)
static int getScreenColumns (void)
static int getScreenRows (void)
static void setDisplayAttribute (bool enhancedDisplay, bool error)
static void dynamicRefresh (PromptBase &pi, char32_t *buf32, int len, int pos)
Display the dynamic incremental search prompt and the current user input line.
static char32_t readUnicodeCharacter (void)
Read a UTF-8 sequence from the non-Windows keyboard and return the Unicode (char32_t) character it encodes.
static char32_t EscapeSequenceProcessing::doDispatch (char32_t c, CharacterDispatch &dispatchTable)
static char32_t EscapeSequenceProcessing::normalKeyRoutine (char32_t c)
static char32_t EscapeSequenceProcessing::upArrowKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::downArrowKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::rightArrowKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::leftArrowKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::homeKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::endKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::pageUpKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::pageDownKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::deleteCharRoutine (char32_t)
static char32_t EscapeSequenceProcessing::deleteKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::ctrlUpArrowKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::ctrlDownArrowKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::ctrlRightArrowKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::ctrlLeftArrowKeyRoutine (char32_t)
static char32_t EscapeSequenceProcessing::escFailureRoutine (char32_t)
static char32_t EscapeSequenceProcessing::escLeftBracket1Semicolon3Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket1Semicolon5Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket1SemicolonRoutine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket0Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket1Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket2Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket3Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket4Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket5Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket6Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket7Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket8Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracket9Routine (char32_t c)
static char32_t EscapeSequenceProcessing::escLeftBracketRoutine (char32_t c)
static char32_t EscapeSequenceProcessing::escORoutine (char32_t c)
static char32_t EscapeSequenceProcessing::setMetaRoutine (char32_t c)
static char32_t EscapeSequenceProcessing::escRoutine (char32_t c)
static char32_t linenoiseReadChar (void)
static void freeCompletions (linenoiseCompletions *lc)
Free memory used in a recent command completion session.
static int cleanupCtrl (int c)
convert {CTRL + 'A'}, {CTRL + 'a'} and {CTRL + ctrlChar('A')} into ctrlChar('A') leave META alone
void linenoiseClearScreen (void)
Clear the screen ONLY (no redisplay of anything)
static bool isCharacterAlphanumeric (char32_t testChar)
void linenoisePreloadBuffer (const char *preloadText)
linenoisePreloadBuffer provides text to be inserted into the command buffer
char * linenoise (const char *prompt)
linenoise is a readline replacement.
void linenoiseSetCompletionCallback (linenoiseCompletionCallback *fn)
Register a callback function to be called for tab-completion.
void linenoiseAddCompletion (linenoiseCompletions *lc, const char *str)
int linenoiseHistoryAdd (const char *line)
int linenoiseHistorySetMaxLen (int len)
char * linenoiseHistoryLine (int index)
int linenoiseHistorySave (const char *filename)
int linenoiseHistoryLoad (const char *filename)
void linenoiseSetMultiLine (int)
Set if to use or not the multi line mode.
void linenoisePrintKeyCodes (void)
static void WindowSizeChanged (int)
int linenoiseInstallWindowChangeHandler (void)
the following are extensions to the original linenoise API
int linenoiseKeyType (void)
returns type of key pressed: 1 = CTRL-C, 2 = CTRL-D, 0 = other
Variables
static const Utf32String forwardSearchBasePrompt ("(i-search)`")
static const Utf32String reverseSearchBasePrompt ("(reverse-i-search)`")
static const Utf32String endSearchBasePrompt ("': ")
static Utf32String previousSearchText
static const int META = 0x40000000
static const int CTRL = 0x20000000
static const int UP_ARROW_KEY = 0x10200000
static const int DOWN_ARROW_KEY = 0x10400000
static const int RIGHT_ARROW_KEY = 0x10600000
static const int LEFT_ARROW_KEY = 0x10800000
static const int HOME_KEY = 0x10A00000
static const int END_KEY = 0x10C00000
static const int DELETE_KEY = 0x10E00000
static const int PAGE_UP_KEY = 0x11000000
static const int PAGE_DOWN_KEY = 0x11200000
static const char * unsupported_term [] = {"dumb", "cons25", "emacs", NULL}
static linenoiseCompletionCallback * completionCallback = NULL
static struct termios orig_termios
static KillRing killRing
static int rawmode = 0
static int atexit_registered = 0
static int historyMaxLen = 100
static int historyLen = 0
static int historyIndex = 0
static uint8_t ** history = NULL
static int historyPreviousIndex = -2
static bool historyRecallMostRecent = false
static char32_t EscapeSequenceProcessing::thisKeyMetaCtrl
static CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket1Semicolon3or5Routines []
static CharacterDispatch EscapeSequenceProcessing::escLeftBracket1Semicolon3or5Dispatch
static CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket1SemicolonRoutines []
static CharacterDispatch EscapeSequenceProcessing::escLeftBracket1SemicolonDispatch
static CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket1Routines []
static CharacterDispatch EscapeSequenceProcessing::escLeftBracket1Dispatch
static CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket3Routines []
static CharacterDispatch EscapeSequenceProcessing::escLeftBracket3Dispatch
static CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket4Routines []
static CharacterDispatch EscapeSequenceProcessing::escLeftBracket4Dispatch
static CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket5Routines []
static CharacterDispatch EscapeSequenceProcessing::escLeftBracket5Dispatch
static CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket6Routines []
static CharacterDispatch EscapeSequenceProcessing::escLeftBracket6Dispatch
static CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket7Routines []
static CharacterDispatch EscapeSequenceProcessing::escLeftBracket7Dispatch
static CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket8Routines []
static CharacterDispatch EscapeSequenceProcessing::escLeftBracket8Dispatch
static CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracketRoutines []
static CharacterDispatch EscapeSequenceProcessing::escLeftBracketDispatch
static CharacterDispatchRoutine EscapeSequenceProcessing::escORoutines []
static CharacterDispatch EscapeSequenceProcessing::escODispatch = {10, "ABCDHFabcd", escORoutines}
static CharacterDispatchRoutine EscapeSequenceProcessing::escRoutines []
static CharacterDispatch EscapeSequenceProcessing::escDispatch = {2, "[O", escRoutines}
static CharacterDispatchRoutine EscapeSequenceProcessing::initialRoutines []
static CharacterDispatch EscapeSequenceProcessing::initialDispatch = {2, "\x1B\x7F", initialRoutines}
static const char breakChars [] = " =+-/\\*?\"'`&<>;|@{([])}"
static const size_t completionCountCutoff = 100
static bool gotResize = false
static int keyType = 0
static string preloadedBufferContents
static string preloadErrorMessage
Macro Definition Documentation
_DEBUG_LINUX_KEYBOARD
#define _DEBUG_LINUX_KEYBOARD
ctrlChar
#define ctrlChar (upperCaseASCII) (upperCaseASCII - 0x40)
LINENOISE_DEFAULT_HISTORY_MAX_LEN
#define LINENOISE_DEFAULT_HISTORY_MAX_LEN 100
LINENOISE_MAX_LINE
#define LINENOISE_MAX_LINE 4096
Function Documentation
beep()
static void beep () static
Referenced by InputBuffer::completeLine(), EscapeSequenceProcessing::escFailureRoutine(), InputBuffer::getInputLine(), and InputBuffer::incrementalHistorySearch().
calculateColumnPosition()
static int calculateColumnPosition (char32_t * buf32, int len) static
Referenced by dynamicRefresh(), InputBuffer::getInputLine(), and InputBuffer::refreshLine().
calculateScreenPosition()
static void calculateScreenPosition (int x, int y, int screenColumns, int charCount, int & xOut, int & yOut) static
Calculate a new screen position given a starting position, screen width and character count.
Parameters
x initial x position (zero-based)
y initial y position (zero-based)
screenColumns screen column count
charCount character positions to advance
xOut returned x position (zero-based)
yOut returned y position (zero-based)
Referenced by DynamicPrompt::DynamicPrompt(), dynamicRefresh(), and InputBuffer::refreshLine().
cleanupCtrl()
static int cleanupCtrl (int c) static
convert {CTRL + 'A'}, {CTRL + 'a'} and {CTRL + ctrlChar('A')} into ctrlChar('A') leave META alone
Parameters
c character to clean up
Returns
cleaned-up character
Referenced by InputBuffer::completeLine(), InputBuffer::getInputLine(), and InputBuffer::incrementalHistorySearch().
copyString32()
static void copyString32 (char32_t * dst, const char32_t * src, size_t len) static
Referenced by InputBuffer::completeLine(), and InputBuffer::incrementalHistorySearch().
copyString32to8() [1/2]
static void copyString32to8 (char * dst, size_t dstLen, const char32_t * src) static
copyString32to8() [2/2]
static void copyString32to8 (char * dst, size_t dstSize, size_t * dstCount, const char32_t * src, size_t srcSize) static
Referenced by Utf8String::Utf8String(), copyString32to8(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), linenoise(), and write32().
copyString8to32() [1/2]
static ConversionResult copyString8to32 (char32_t * dst, size_t dstSize, size_t & dstCount, const char * src) static
Referenced by Utf32String::Utf32String(), copyString8to32(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), InputBuffer::preloadBuffer(), and readUnicodeCharacter().
copyString8to32() [2/2]
static ConversionResult copyString8to32 (char32_t * dst, size_t dstSize, size_t & dstCount, const uint8_t * src) static
disableRawMode()
static void disableRawMode (void) static
Referenced by InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), linenoise(), linenoiseAtExit(), and linenoisePrintKeyCodes().
dynamicRefresh()
static void dynamicRefresh (PromptBase & pi, char32_t * buf32, int len, int pos) static
Display the dynamic incremental search prompt and the current user input line.
Parameters
pi PromptBase struct holding information about the prompt and our screen position
buf32 input buffer to be displayed
len count of characters in the buffer
pos current cursor position within the buffer (0 <= pos <= len)
Referenced by InputBuffer::getInputLine(), and InputBuffer::incrementalHistorySearch().
enableRawMode()
static int enableRawMode (void) static
Referenced by InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), linenoise(), and linenoisePrintKeyCodes().
freeCompletions()
static void freeCompletions (linenoiseCompletions * lc) static
Free memory used in a recent command completion session.
Parameters
lc pointer to a linenoiseCompletions struct
Referenced by InputBuffer::completeLine().
getScreenColumns()
static int getScreenColumns (void) static
Referenced by InputBuffer::getInputLine(), and linenoise().
getScreenRows()
static int getScreenRows (void) static
Referenced by InputBuffer::completeLine().
isCharacterAlphanumeric()
static bool isCharacterAlphanumeric (char32_t testChar) static
Referenced by InputBuffer::getInputLine().
isControlChar()
static bool isControlChar (char32_t testChar) static
Referenced by PromptInfo::PromptInfo(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), and linenoisePreloadBuffer().
isUnsupportedTerm()
static bool isUnsupportedTerm (void) static
Referenced by linenoise().
linenoise()
char * linenoise (const char * prompt)
linenoise is a readline replacement.
call it with a prompt to display and it will return a line of input from the user
Parameters
prompt text of prompt to display to the user
Returns
the returned string belongs to the caller on return and must be freed to prevent memory leaks
Referenced by native_console_in().
linenoiseAddCompletion()
void linenoiseAddCompletion (linenoiseCompletions * lc, const char * str)
linenoiseAtExit()
static void linenoiseAtExit (void) static
Referenced by enableRawMode().
linenoiseClearScreen()
void linenoiseClearScreen (void)
Clear the screen ONLY (no redisplay of anything)
Referenced by InputBuffer::clearScreen().
linenoiseHistoryAdd()
int linenoiseHistoryAdd (const char * line)
Referenced by InputBuffer::getInputLine(), linenoiseHistoryLoad(), and native_console_in().
linenoiseHistoryFree()
void linenoiseHistoryFree (void)
Referenced by native_console_close().
linenoiseHistoryLine()
char * linenoiseHistoryLine (int index)
linenoiseHistoryLoad()
int linenoiseHistoryLoad (const char * filename)
linenoiseHistorySave()
int linenoiseHistorySave (const char * filename)
linenoiseHistorySetMaxLen()
int linenoiseHistorySetMaxLen (int len)
Referenced by native_console_open().
linenoiseInstallWindowChangeHandler()
int linenoiseInstallWindowChangeHandler (void)
the following are extensions to the original linenoise API
linenoiseKeyType()
int linenoiseKeyType (void)
returns type of key pressed: 1 = CTRL-C, 2 = CTRL-D, 0 = other
linenoisePreloadBuffer()
void linenoisePreloadBuffer (const char * preloadText)
linenoisePreloadBuffer provides text to be inserted into the command buffer
the provided text will be processed to be usable and will be used to preload the input buffer on the next call to linenoise()
Parameters
preloadText text to begin with on the next call to linenoise()
linenoisePrintKeyCodes()
void linenoisePrintKeyCodes (void)
linenoiseReadChar()
static char32_t linenoiseReadChar (void) static
Referenced by InputBuffer::completeLine(), InputBuffer::getInputLine(), and InputBuffer::incrementalHistorySearch().
linenoiseSetCompletionCallback()
void linenoiseSetCompletionCallback (linenoiseCompletionCallback * fn)
Register a callback function to be called for tab-completion.
linenoiseSetMultiLine()
void linenoiseSetMultiLine (int ml)
Set if to use or not the multi line mode.
note that this is a stub only, as linenoise-ng always multi-line
readUnicodeCharacter()
static char32_t readUnicodeCharacter (void) static
Read a UTF-8 sequence from the non-Windows keyboard and return the Unicode (char32_t) character it encodes.
Returns
char32_t Unicode character
Referenced by EscapeSequenceProcessing::escLeftBracket1Routine(), EscapeSequenceProcessing::escLeftBracket1Semicolon3Routine(), EscapeSequenceProcessing::escLeftBracket1Semicolon5Routine(), EscapeSequenceProcessing::escLeftBracket1SemicolonRoutine(), EscapeSequenceProcessing::escLeftBracket3Routine(), EscapeSequenceProcessing::escLeftBracket4Routine(), EscapeSequenceProcessing::escLeftBracket5Routine(), EscapeSequenceProcessing::escLeftBracket6Routine(), EscapeSequenceProcessing::escLeftBracket7Routine(), EscapeSequenceProcessing::escLeftBracket8Routine(), EscapeSequenceProcessing::escLeftBracketRoutine(), EscapeSequenceProcessing::escORoutine(), EscapeSequenceProcessing::escRoutine(), linenoiseReadChar(), and EscapeSequenceProcessing::setMetaRoutine().
recomputeCharacterWidths()
static void recomputeCharacterWidths (const char32_t * text, char * widths, int charCount) static
Referenced by InputBuffer::preloadBuffer().
setDisplayAttribute()
static void setDisplayAttribute (bool enhancedDisplay, bool error) static
Referenced by InputBuffer::refreshLine().
strdup8()
static uint8_t * strdup8 (const char * src) static
Referenced by InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), and linenoiseHistoryAdd().
strlen32()
static size_t strlen32 (const char32_t * str) static
Referenced by copyString32to8().
strlen8()
static size_t strlen8 (const uint8_t * str) static
Referenced by InputBuffer::incrementalHistorySearch().
strncmp32()
static int strncmp32 (const char32_t * left, const char32_t * right, size_t len) static
Referenced by InputBuffer::incrementalHistorySearch().
WindowSizeChanged()
static void WindowSizeChanged (int) static
Referenced by linenoiseInstallWindowChangeHandler().
write32()
static int write32 (int fd, char32_t * text32, int len32) static
Referenced by InputBuffer::completeLine(), dynamicRefresh(), InputBuffer::getInputLine(), InputBuffer::refreshLine(), and PromptBase::write().
Variable Documentation
atexit_registered
int atexit_registered = 0 static
Referenced by enableRawMode().
breakChars
const char breakChars[] = " =+-/\\*?\"'`&<>;|@{([])}" static
Referenced by InputBuffer::completeLine().
completionCallback
linenoiseCompletionCallback* completionCallback = NULL static
Referenced by InputBuffer::completeLine(), InputBuffer::getInputLine(), and linenoiseSetCompletionCallback().
completionCountCutoff
const size_t completionCountCutoff = 100 static
Referenced by InputBuffer::completeLine().
CTRL
const int CTRL = 0x20000000 static
Referenced by cleanupCtrl(), EscapeSequenceProcessing::ctrlDownArrowKeyRoutine(), EscapeSequenceProcessing::ctrlLeftArrowKeyRoutine(), EscapeSequenceProcessing::ctrlRightArrowKeyRoutine(), EscapeSequenceProcessing::ctrlUpArrowKeyRoutine(), EscapeSequenceProcessing::escLeftBracket1Semicolon5Routine(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), and linenoiseReadChar().
DELETE_KEY
const int DELETE_KEY = 0x10E00000 static
Referenced by EscapeSequenceProcessing::deleteKeyRoutine(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), and linenoiseReadChar().
DOWN_ARROW_KEY
const int DOWN_ARROW_KEY = 0x10400000 static
Referenced by EscapeSequenceProcessing::ctrlDownArrowKeyRoutine(), EscapeSequenceProcessing::downArrowKeyRoutine(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), and linenoiseReadChar().
END_KEY
const int END_KEY = 0x10C00000 static
Referenced by EscapeSequenceProcessing::endKeyRoutine(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), and linenoiseReadChar().
endSearchBasePrompt
const Utf32String endSearchBasePrompt("': ") ("': ") static
Referenced by DynamicPrompt::DynamicPrompt(), and DynamicPrompt::updateSearchPrompt().
forwardSearchBasePrompt
const Utf32String forwardSearchBasePrompt("(i-search)`") ("(i-search)`") static
Referenced by DynamicPrompt::DynamicPrompt(), and DynamicPrompt::updateSearchPrompt().
gotResize
bool gotResize = false static
Referenced by InputBuffer::getInputLine(), linenoise(), and WindowSizeChanged().
history
uint8_t** history = NULL static
Referenced by InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), linenoiseHistoryAdd(), linenoiseHistoryFree(), linenoiseHistoryLine(), linenoiseHistorySave(), and linenoiseHistorySetMaxLen().
historyIndex
int historyIndex = 0 static
Referenced by InputBuffer::getInputLine(), and InputBuffer::incrementalHistorySearch().
historyLen
int historyLen = 0 static
Referenced by InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), linenoiseHistoryAdd(), linenoiseHistoryFree(), linenoiseHistoryLine(), linenoiseHistorySave(), and linenoiseHistorySetMaxLen().
historyMaxLen
int historyMaxLen = 100 static
Referenced by linenoiseHistoryAdd(), and linenoiseHistorySetMaxLen().
historyPreviousIndex
int historyPreviousIndex = -2 static
Referenced by InputBuffer::getInputLine(), and linenoiseHistoryAdd().
historyRecallMostRecent
bool historyRecallMostRecent = false static
Referenced by InputBuffer::getInputLine(), and InputBuffer::incrementalHistorySearch().
HOME_KEY
const int HOME_KEY = 0x10A00000 static
Referenced by InputBuffer::getInputLine(), EscapeSequenceProcessing::homeKeyRoutine(), InputBuffer::incrementalHistorySearch(), and linenoiseReadChar().
keyType
int keyType = 0 static
Referenced by InputBuffer::getInputLine(), and linenoiseKeyType().
killRing
KillRing killRing static
Referenced by InputBuffer::getInputLine().
LEFT_ARROW_KEY
const int LEFT_ARROW_KEY = 0x10800000 static
Referenced by EscapeSequenceProcessing::ctrlLeftArrowKeyRoutine(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), EscapeSequenceProcessing::leftArrowKeyRoutine(), and linenoiseReadChar().
META
const int META = 0x40000000 static
Referenced by EscapeSequenceProcessing::escLeftBracket1Semicolon3Routine(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), linenoiseReadChar(), and EscapeSequenceProcessing::setMetaRoutine().
orig_termios
struct termios orig_termios static
Referenced by disableRawMode(), and enableRawMode().
PAGE_DOWN_KEY
const int PAGE_DOWN_KEY = 0x11200000 static
Referenced by InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), linenoiseReadChar(), and EscapeSequenceProcessing::pageDownKeyRoutine().
PAGE_UP_KEY
const int PAGE_UP_KEY = 0x11000000 static
Referenced by InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), linenoiseReadChar(), and EscapeSequenceProcessing::pageUpKeyRoutine().
preloadedBufferContents
string preloadedBufferContents static
Referenced by linenoise(), and linenoisePreloadBuffer().
preloadErrorMessage
string preloadErrorMessage static
Referenced by linenoise(), and linenoisePreloadBuffer().
previousSearchText
Utf32String previousSearchText static
Referenced by InputBuffer::incrementalHistorySearch().
rawmode
int rawmode = 0 static
Referenced by disableRawMode(), and enableRawMode().
reverseSearchBasePrompt
const Utf32String reverseSearchBasePrompt("(reverse-i-search)`") ("(reverse-i-search)`") static
Referenced by DynamicPrompt::DynamicPrompt(), and DynamicPrompt::updateSearchPrompt().
RIGHT_ARROW_KEY
const int RIGHT_ARROW_KEY = 0x10600000 static
Referenced by EscapeSequenceProcessing::ctrlRightArrowKeyRoutine(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), linenoiseReadChar(), and EscapeSequenceProcessing::rightArrowKeyRoutine().
unsupported_term
const char* unsupported_term[] = {"dumb", "cons25", "emacs", NULL} static
Referenced by isUnsupportedTerm().
UP_ARROW_KEY
const int UP_ARROW_KEY = 0x10200000 static
Referenced by EscapeSequenceProcessing::ctrlUpArrowKeyRoutine(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), linenoiseReadChar(), and EscapeSequenceProcessing::upArrowKeyRoutine().