vsid: linenoise_ng Namespace Reference
linenoise_ng Namespace Reference
Recompute widths of all characters in a char32_t buffer.
Data Structures
struct interval
Typedefs
typedef uint32_t UTF32
typedef uint16_t UTF16
typedef uint8_t UTF8
typedef unsigned char Boolean
Enumerations
enum ConversionResult {
conversionOK ,
sourceExhausted ,
targetExhausted ,
sourceIllegal
}
enum ConversionFlags {
strictConversion = 0 ,
lenientConversion
}
Functions
ConversionResult ConvertUTF32toUTF16 (const UTF32 **sourceStart, const UTF32 *sourceEnd, char16_t **targetStart, char16_t *targetEnd, ConversionFlags flags)
ConversionResult ConvertUTF16toUTF32 (const UTF16 **sourceStart, const UTF16 *sourceEnd, UTF32 **targetStart, UTF32 *targetEnd, ConversionFlags flags)
ConversionResult ConvertUTF16toUTF8 (const UTF16 **sourceStart, const UTF16 *sourceEnd, UTF8 **targetStart, UTF8 *targetEnd, ConversionFlags flags)
static Boolean isLegalUTF8 (const UTF8 *source, int length)
Boolean isLegalUTF8Sequence (const UTF8 *source, const UTF8 *sourceEnd)
ConversionResult ConvertUTF8toUTF16 (const UTF8 **sourceStart, const UTF8 *sourceEnd, UTF16 **targetStart, UTF16 *targetEnd, ConversionFlags flags)
ConversionResult ConvertUTF32toUTF8 (const UTF32 **sourceStart, const UTF32 *sourceEnd, UTF8 **targetStart, UTF8 *targetEnd, ConversionFlags flags)
ConversionResult ConvertUTF8toUTF32 (const UTF8 **sourceStart, const UTF8 *sourceEnd, UTF32 **targetStart, UTF32 *targetEnd, ConversionFlags flags)
int mk_wcwidth (char32_t ucs)
int mk_wcswidth (const char32_t *pwcs, size_t n)
static int bisearch (char32_t ucs, const struct interval *table, int max)
auxiliary function for binary search in interval table
int mk_wcwidth_cjk (wchar_t ucs)
int mk_wcswidth_cjk (const wchar_t *pwcs, size_t n)
Variables
static const int halfShift = 10
static const UTF32 halfBase = 0x0010000UL
static const UTF32 halfMask = 0x3FFUL
static const char trailingBytesForUTF8 [256]
static const UTF32 offsetsFromUTF8 [6]
static const UTF8 firstByteMark [7] = { 0x00, 0x00, 0xC0, 0xE0, 0xF0, 0xF8, 0xFC }
Detailed Description
Recompute widths of all characters in a char32_t buffer.
Calculate a column width using mk_wcswidth()
Parameters
text input buffer of Unicode characters
widths output buffer of character widths
charCount number of characters in buffer
buf32 text to calculate
len length of text to calculate
Typedef Documentation
Boolean
typedef unsigned char linenoise_ng::Boolean
UTF16
typedef uint16_t linenoise_ng::UTF16
UTF32
typedef uint32_t linenoise_ng::UTF32
UTF8
typedef uint8_t linenoise_ng::UTF8
Enumeration Type Documentation
ConversionFlags
enum linenoise_ng::ConversionFlags
Enumerator
strictConversion
lenientConversion
ConversionResult
enum linenoise_ng::ConversionResult
Enumerator
conversionOK
sourceExhausted
targetExhausted
sourceIllegal
Function Documentation
bisearch()
static int linenoise_ng::bisearch (char32_t ucs, const struct interval * table, int max) static
auxiliary function for binary search in interval table
Referenced by mk_wcwidth(), and mk_wcwidth_cjk().
ConvertUTF16toUTF32()
ConversionResult linenoise_ng::ConvertUTF16toUTF32 (const UTF16 ** sourceStart, const UTF16 * sourceEnd, UTF32 ** targetStart, UTF32 * targetEnd, ConversionFlags flags)
ConvertUTF16toUTF8()
ConversionResult linenoise_ng::ConvertUTF16toUTF8 (const UTF16 ** sourceStart, const UTF16 * sourceEnd, UTF8 ** targetStart, UTF8 * targetEnd, ConversionFlags flags)
ConvertUTF32toUTF16()
ConversionResult linenoise_ng::ConvertUTF32toUTF16 (const UTF32 ** sourceStart, const UTF32 * sourceEnd, char16_t ** targetStart, char16_t * targetEnd, ConversionFlags flags)
ConvertUTF32toUTF8()
ConversionResult linenoise_ng::ConvertUTF32toUTF8 (const UTF32 ** sourceStart, const UTF32 * sourceEnd, UTF8 ** targetStart, UTF8 * targetEnd, ConversionFlags flags)
Referenced by copyString32to8().
ConvertUTF8toUTF16()
ConversionResult linenoise_ng::ConvertUTF8toUTF16 (const UTF8 ** sourceStart, const UTF8 * sourceEnd, UTF16 ** targetStart, UTF16 * targetEnd, ConversionFlags flags)
ConvertUTF8toUTF32()
ConversionResult linenoise_ng::ConvertUTF8toUTF32 (const UTF8 ** sourceStart, const UTF8 * sourceEnd, UTF32 ** targetStart, UTF32 * targetEnd, ConversionFlags flags)
Referenced by copyString8to32().
isLegalUTF8()
static Boolean linenoise_ng::isLegalUTF8 (const UTF8 * source, int length) static
Referenced by ConvertUTF8toUTF16(), ConvertUTF8toUTF32(), and isLegalUTF8Sequence().
isLegalUTF8Sequence()
Boolean linenoise_ng::isLegalUTF8Sequence (const UTF8 * source, const UTF8 * sourceEnd)
mk_wcswidth()
int linenoise_ng::mk_wcswidth (const char32_t * pwcs, size_t n)
Referenced by calculateColumnPosition().
mk_wcswidth_cjk()
int linenoise_ng::mk_wcswidth_cjk (const wchar_t * pwcs, size_t n)
mk_wcwidth()
int linenoise_ng::mk_wcwidth (char32_t ucs)
Referenced by mk_wcswidth(), mk_wcwidth_cjk(), and recomputeCharacterWidths().
mk_wcwidth_cjk()
int linenoise_ng::mk_wcwidth_cjk (wchar_t ucs)
Referenced by mk_wcswidth_cjk().
Variable Documentation
firstByteMark
const UTF8 linenoise_ng::firstByteMark[7] = { 0x00, 0x00, 0xC0, 0xE0, 0xF0, 0xF8, 0xFC } static
Referenced by ConvertUTF16toUTF8(), and ConvertUTF32toUTF8().
halfBase
const UTF32 linenoise_ng::halfBase = 0x0010000UL static
Referenced by ConvertUTF16toUTF32(), ConvertUTF16toUTF8(), ConvertUTF32toUTF16(), and ConvertUTF8toUTF16().
halfMask
const UTF32 linenoise_ng::halfMask = 0x3FFUL static
Referenced by ConvertUTF32toUTF16(), and ConvertUTF8toUTF16().
halfShift
const int linenoise_ng::halfShift = 10 static
Referenced by ConvertUTF16toUTF32(), ConvertUTF16toUTF8(), ConvertUTF32toUTF16(), and ConvertUTF8toUTF16().
offsetsFromUTF8
const UTF32 linenoise_ng::offsetsFromUTF8[6] static
Initial value:
= { 0x00000000UL, 0x00003080UL, 0x000E2080UL,
                     0x03C82080UL, 0xFA082080UL, 0x82082080UL }
Referenced by ConvertUTF8toUTF16(), and ConvertUTF8toUTF32().
trailingBytesForUTF8
const char linenoise_ng::trailingBytesForUTF8[256] static
Initial value:
= {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2, 3,3,3,3,3,3,3,3,4,4,4,4,5,5,5,5
}
Referenced by ConvertUTF8toUTF16(), ConvertUTF8toUTF32(), and isLegalUTF8Sequence().