vsid: arch/gtk3/widgets/ffmpegwidget.c File Reference
ffmpegwidget.c File Reference
FFMPEG media recording options dialog.
#include "vice.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "basewidgets.h"
#include "debug_gtk3.h"
#include "gfxoutput.h"
#include "lib.h"
#include "machine.h"
#include "resources.h"
#include "ui.h"
#include "widgethelpers.h"
#include "ffmpegwidget.h"
Functions
static GtkListStore * create_video_model (int fmt)
forward declarations of functions
static GtkListStore * create_audio_model (int fmt)
Create a GtkListStore for the audio codecs of fmt.
static void update_video_combo_box (int id)
Update the video codec combo box.
static void update_audio_combo_box (int id)
Update the audio codec combo box.
static const char * ffmpeg_kludges (const char *name)
static void on_format_changed (GtkWidget *widget, gpointer data)
Handler for the "changed" event of the format combo box.
static void on_video_codec_changed (GtkComboBox *combo, gpointer data)
Handler for the "changed" event of the video codec combo box.
static void on_audio_codec_changed (GtkComboBox *combo, gpointer data)
Handler for the "changed" event of the audio codec combo box.
static int get_format_index_by_name (const char *fmt)
Get index in format list of fmt.
static GtkListStore * create_format_model (void)
Create a model for the FFMPEG output formats.
static GtkWidget * create_indented_label (const gchar *text)
Create a left-aligned, 16px indented label.
static GtkWidget * create_format_combo_box (void)
Create combo box with supported output formats.
static void update_format_combo_box (const char *fmt)
Update the format combo box.
static GtkWidget * create_video_combo_box (int fmt)
Create combo box with supported video codecs for fmt.
static GtkWidget * create_audio_combo_box (int fmt)
Create combo box with supported audio codecs for fmt.
GtkWidget * ffmpeg_widget_create (const char *driver)
Create widget to control FFMPEG output options.
Variables
static gfxoutputdrv_t * driver_info = NULL
FFMPEG driver info.
static GtkWidget * format_widget = NULL
references to combo boxes, used in various event handlers
static GtkWidget * video_widget = NULL
Video codec combo box reference.
static GtkWidget * audio_widget = NULL
Audio codec combo box reference.
static GtkWidget * audiobitrate
static GtkWidget * videobitrate
Detailed Description
FFMPEG media recording options dialog.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_audio_combo_box()
static GtkWidget * create_audio_combo_box (int fmt) static
Create combo box with supported audio codecs for fmt.
Parameters
[in] fmt format index
Returns
GtkComboBox
Referenced by ffmpeg_widget_create().
create_audio_model()
static GtkListStore * create_audio_model (int fmt) static
Create a GtkListStore for the audio codecs of fmt.
Parameters
[in] fmt format index
Returns
GtkListStore
Referenced by create_audio_combo_box(), and on_format_changed().
create_format_combo_box()
static GtkWidget * create_format_combo_box (void) static
Create combo box with supported output formats.
Returns
GtkComboBox
Referenced by ffmpeg_widget_create().
create_format_model()
static GtkListStore * create_format_model (void) static
Create a model for the FFMPEG output formats.
Returns
GtkListStore
Referenced by create_format_combo_box().
create_indented_label()
static GtkWidget * create_indented_label (const gchar * text) static
Create a left-aligned, 16px indented label.
Parameters
[in] text label text
Returns
GtkLabel
Referenced by ffmpeg_widget_create().
create_video_combo_box()
static GtkWidget * create_video_combo_box (int fmt) static
Create combo box with supported video codecs for fmt.
Parameters
[in] fmt format index
Returns
GtkComboBox
Referenced by ffmpeg_widget_create().
create_video_model()
static GtkListStore * create_video_model (int fmt) static
forward declarations of functions
Create a model for the video codecs of fmt.
Parameters
[in] fmt format index
Returns
GtkListStore
Referenced by create_video_combo_box(), and on_format_changed().
ffmpeg_kludges()
static const char * ffmpeg_kludges (const char * name) static
Referenced by ffmpeg_widget_create(), on_audio_codec_changed(), on_format_changed(), and on_video_codec_changed().
ffmpeg_widget_create()
GtkWidget * ffmpeg_widget_create (const char * driver)
Create widget to control FFMPEG output options.
Returns
GtkGrid
Referenced by create_video_widget(), and on_video_driver_toggled().
get_format_index_by_name()
static int get_format_index_by_name (const char * fmt) static
Get index in format list of fmt.
Parameters
[in] fmt format name
Returns
index in list or -1 when not found
Referenced by ffmpeg_widget_create().
on_audio_codec_changed()
static void on_audio_codec_changed (GtkComboBox * combo, gpointer data) static
Handler for the "changed" event of the audio codec combo box.
Parameters
[in] combo audio codec combo box
[in] data extra event data (unused)
Referenced by ffmpeg_widget_create().
on_format_changed()
static void on_format_changed (GtkWidget * widget, gpointer data) static
Handler for the "changed" event of the format combo box.
Parameters
[in] widget format combo box
[in] data extra event data (unused)
Referenced by ffmpeg_widget_create().
on_video_codec_changed()
static void on_video_codec_changed (GtkComboBox * combo, gpointer data) static
Handler for the "changed" event of the video codec combo box.
Parameters
[in] combo video codec combo box
[in] data extra event data (unused)
Referenced by ffmpeg_widget_create().
update_audio_combo_box()
static void update_audio_combo_box (int id) static
Update the audio codec combo box.
Parameters
[in] id audio codec ID
Referenced by ffmpeg_widget_create(), and on_format_changed().
update_format_combo_box()
static void update_format_combo_box (const char * fmt) static
Update the format combo box.
Parameters
[in] fmt FFMPEG driver format name
Referenced by ffmpeg_widget_create().
update_video_combo_box()
static void update_video_combo_box (int id) static
Update the video codec combo box.
Parameters
[in] id video codec ID
Referenced by ffmpeg_widget_create(), and on_format_changed().
Variable Documentation
audio_widget
GtkWidget* audio_widget = NULL static
Audio codec combo box reference.
Referenced by ffmpeg_widget_create(), on_format_changed(), and update_audio_combo_box().
audiobitrate
GtkWidget* audiobitrate static
Referenced by ffmpeg_widget_create(), and on_format_changed().
driver_info
gfxoutputdrv_t* driver_info = NULL static
FFMPEG driver info.
Retrieved via gfxoutput_get_driver(), gets cleaned up when the gfxoutput sub system exits.
Referenced by create_audio_model(), create_format_model(), create_video_model(), ffmpeg_widget_create(), get_format_index_by_name(), on_audio_codec_changed(), on_format_changed(), and on_video_codec_changed().
format_widget
GtkWidget* format_widget = NULL static
references to combo boxes, used in various event handlers
File format combo box reference
Referenced by ffmpeg_widget_create(), and update_format_combo_box().
video_widget
GtkWidget* video_widget = NULL static
Video codec combo box reference.
Referenced by ffmpeg_widget_create(), on_format_changed(), and update_video_combo_box().
videobitrate
GtkWidget* videobitrate static
Referenced by ffmpeg_widget_create(), and on_format_changed().