vsid: arch/gtk3/uisettings.h File Reference
uisettings.h File Reference
GTK3 settings dialog - header.
#include "vice.h"
#include <gtk/gtk.h>
Data Structures
struct ui_settings_tree_node_s
Settings tree node object.
Macros
#define UI_SETTINGS_TERMINATOR { NULL, NULL, NULL, NULL }
tree nodes list terminator
#define UI_SETTINGS_SEPARATOR { "---", "(separator)", NULL, NULL }
tree nodes list separator
Typedefs
typedef struct ui_settings_tree_node_s ui_settings_tree_node_t
Settings tree node object.
Functions
void ui_settings_dialog_show (const char *path)
Menu callback for the settings dialog.
void ui_settings_shutdown (void)
Clean up resources used on emu exit.
Detailed Description
GTK3 settings dialog - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
UI_SETTINGS_SEPARATOR
#define UI_SETTINGS_SEPARATOR { "---", "(separator)", NULL, NULL }
tree nodes list separator
UI_SETTINGS_TERMINATOR
#define UI_SETTINGS_TERMINATOR { NULL, NULL, NULL, NULL }
tree nodes list terminator
Typedef Documentation
ui_settings_tree_node_t
typedef struct ui_settings_tree_node_s ui_settings_tree_node_t
Settings tree node object.
Contains name to display in the settings tree widget, an ID to allow for xpath-like access to tree nodes, a callback to render a widget next to the tree, and optionally a list of child nodes.
Function Documentation
ui_settings_dialog_show()
void ui_settings_dialog_show (const char * path)
Menu callback for the settings dialog.
Opens the main settings dialog and activates a node, if any.
Parameters
[in] path path to node
Returns
TRUE
Referenced by help_hotkeys_action(), on_configure_activate(), on_drive_configure_activate(), settings_dialog_action(), and ui_create_main_window().
ui_settings_shutdown()
void ui_settings_shutdown (void)
Clean up resources used on emu exit.
This function cleans up the data used to present the user with the last used settings page.
Note
Do NOT call this when exiting the settings UI, the event handlers will take care of cleaning up resources used by the UI.
Referenced by ui_exit().