vsid: rs232drv/rs232drv.c File Reference
rs232drv.c File Reference
#include "vice.h"
#include "archdep.h"
#include "cmdline.h"
#include "lib.h"
#include "resources.h"
#include "rs232.h"
#include "rs232drv.h"
#include "types.h"
#include "util.h"
Functions
static int set_devfile (const char *val, void *param)
static int set_useip232 (int val, void *param)
int rs232drv_resources_init (void)
void rs232drv_resources_shutdown (void)
int rs232drv_cmdline_options_init (void)
void rs232drv_init (void)
void rs232drv_reset (void)
int rs232drv_open (int device)
void rs232drv_close (int fd)
int rs232drv_putc (int fd, uint8_t b)
int rs232drv_getc (int fd, uint8_t *b)
int rs232drv_set_status (int fd, enum rs232handshake_out status)
write the output handshake lines
enum rs232handshake_in rs232drv_get_status (int fd)
write the output handshake lines
void rs232drv_set_bps (int fd, unsigned int bps)
Variables
char * rs232_devfile [4] = { NULL }
int rs232_useip232 [4]
static const resource_string_t resources_string []
static const resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
Function Documentation
rs232drv_close()
void rs232drv_close (int fd)
Referenced by myacia_reset(), myacia_snapshot_read_module(), myacia_store(), rsuser_reset(), rsuser_write_ctrl(), set_up_device(), and userport_rs232_enable().
rs232drv_cmdline_options_init()
int rs232drv_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
rs232drv_get_status()
enum rs232handshake_in rs232drv_get_status (int fd)
write the output handshake lines
Referenced by acia_get_status(), and rsuser_read_ctrl().
rs232drv_getc()
int rs232drv_getc (int fd, uint8_t * b)
Referenced by int_acia_rx(), and int_rsuser().
rs232drv_init()
void rs232drv_init (void)
Referenced by machine_specific_init().
rs232drv_open()
int rs232drv_open (int device)
Referenced by myacia_snapshot_read_module(), myacia_store(), rsuser_setup(), and set_up_device().
rs232drv_putc()
int rs232drv_putc (int fd, uint8_t b)
Referenced by check_tx_buffer(), and int_acia_tx().
rs232drv_reset()
void rs232drv_reset (void)
Referenced by machine_specific_reset().
rs232drv_resources_init()
int rs232drv_resources_init (void)
Referenced by machine_resources_init().
rs232drv_resources_shutdown()
void rs232drv_resources_shutdown (void)
Referenced by machine_resources_shutdown().
rs232drv_set_bps()
void rs232drv_set_bps (int fd, unsigned int bps)
Referenced by set_acia_ticks().
rs232drv_set_status()
int rs232drv_set_status (int fd, enum rs232handshake_out status)
write the output handshake lines
Referenced by acia_set_handshake_lines(), myacia_reset(), and rsuser_write_ctrl().
set_devfile()
static int set_devfile (const char * val, void * param) static
set_useip232()
static int set_useip232 (int val, void * param) static
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-rsdev1", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RsDevice1", NULL,
      "<Name>", "Specify name of first RS232 device" },
    { "-rsdev2", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RsDevice2", NULL,
      "<Name>", "Specify name of second RS232 device" },
    { "-rsdev3", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RsDevice3", NULL,
      "<Name>", "Specify name of third RS232 device" },
    { "-rsdev4", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "RsDevice4", NULL,
      "<Name>", "Specify name of fourth RS232 device" },
    { "-rsdev1ip232", SET_RESOURCE,  0 ,
      NULL, NULL, "RsDevice1ip232", (void *)1,
      NULL, "Enable IP232 protocol on first RS232 device" },
    { "+rsdev1ip232", SET_RESOURCE,  0 ,
      NULL, NULL, "RsDevice1ip232", (void *)0,
      NULL, "Disable IP232 protocol on first RS232 device" },
    { "-rsdev2ip232", SET_RESOURCE,  0 ,
      NULL, NULL, "RsDevice2ip232", (void *)1,
      NULL, "Enable IP232 protocol on second RS232 device" },
    { "+rsdev2ip232", SET_RESOURCE,  0 ,
      NULL, NULL, "RsDevice2ip232", (void *)0,
      NULL, "Disable IP232 protocol on second RS232 device" },
    { "-rsdev3ip232", SET_RESOURCE,  0 ,
      NULL, NULL, "RsDevice3ip232", (void *)1,
      NULL, "Enable IP232 protocol on third RS232 device" },
    { "+rsdev3ip232", SET_RESOURCE,  0 ,
      NULL, NULL, "RsDevice3ip232", (void *)0,
      NULL, "Disable IP232 protocol on third RS232 device" },
    { "-rsdev4ip232", SET_RESOURCE,  0 ,
      NULL, NULL, "RsDevice4ip232", (void *)1,
      NULL, "Enable IP232 protocol on fourth RS232 device" },
    { "+rsdev4ip232", SET_RESOURCE,  0 ,
      NULL, NULL, "RsDevice4ip232", (void *)0,
      NULL, "Disable IP232 protocol on fourth RS232 device" },
      { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Referenced by rs232drv_cmdline_options_init().
resources_int
const resource_int_t resources_int[] static
Initial value:
= {
    { "RsDevice1ip232", 0, RES_EVENT_STRICT, (resource_value_t)0,
      &rs232_useip232[0], set_useip232, (void *)0 },
    { "RsDevice2ip232", 0, RES_EVENT_STRICT, (resource_value_t)0,
      &rs232_useip232[1], set_useip232, (void *)1 },
    { "RsDevice3ip232", 0, RES_EVENT_STRICT, (resource_value_t)0,
      &rs232_useip232[2], set_useip232, (void *)2 },
    { "RsDevice4ip232", 0, RES_EVENT_STRICT, (resource_value_t)0,
      &rs232_useip232[3], set_useip232, (void *)3 },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by rs232drv_resources_init().
resources_string
const resource_string_t resources_string[] static
Initial value:
= {
    { "RsDevice1",  "/dev/ttyS0" , RES_EVENT_NO, NULL,
      &rs232_devfile[0], set_devfile, (void *)0 },
    { "RsDevice2",  "/dev/ttyS1" , RES_EVENT_NO, NULL,
      &rs232_devfile[1], set_devfile, (void *)1 },
    { "RsDevice3",  "127.0.0.1:25232" , RES_EVENT_NO, NULL,
      &rs232_devfile[2], set_devfile, (void *)2 },
    { "RsDevice4",  "|nc 127.0.0.1 25232" , RES_EVENT_NO, NULL,
      &rs232_devfile[3], set_devfile, (void *)3 },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by rs232drv_resources_init().
rs232_devfile
char* rs232_devfile[4] = { NULL }
Referenced by rs232_is_physical_device(), rs232drv_resources_shutdown(), rs232net_open(), and set_devfile().
rs232_useip232
int rs232_useip232[4]
Referenced by myacia_snapshot_read_module(), myacia_store(), rs232net_open(), and set_useip232().