vsid: arch/gtk3/opengl_renderer_unix.c File Reference
opengl_renderer_unix.c File Reference
#include "vice.h"
#include "archdep.h"
#include <string.h>
#include "opengl_renderer.h"
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include "log.h"
#include "render_queue.h"
Macros
#define CANVAS_LOCK() pthread_mutex_lock(context->canvas_lock_ptr)
#define CANVAS_UNLOCK() pthread_mutex_unlock(context->canvas_lock_ptr)
#define RENDER_LOCK() pthread_mutex_lock(&context->render_lock)
#define RENDER_UNLOCK() pthread_mutex_unlock(&context->render_lock)
Typedefs
typedef GLXContext(* glXCreateContextAttribsARBProc) (Display *, GLXFBConfig, GLXContext, Bool, const int *)
Functions
static bool isExtensionSupported (const char *extList, const char *extension)
void vice_opengl_renderer_make_current (vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_set_viewport (vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_present_backbuffer (vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_clear_current (vice_opengl_renderer_context_t *context)
static int catch_x_error (Display *display, XErrorEvent *event)
void vice_opengl_renderer_create_child_view (GtkWidget *widget, vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_set_vsync (vice_opengl_renderer_context_t *context, bool enable_vsync)
void vice_opengl_renderer_resize_child_view (GtkWidget *widget, vice_opengl_renderer_context_t *context)
void vice_opengl_renderer_destroy_child_view (vice_opengl_renderer_context_t *context)
Detailed Description
Author
David Hogan david.nosp@m..q.h.nosp@m.ogan@.nosp@m.gmai.nosp@m.l.com
Macro Definition Documentation
CANVAS_LOCK
#define CANVAS_LOCK () pthread_mutex_lock(context->canvas_lock_ptr)
CANVAS_UNLOCK
#define CANVAS_UNLOCK () pthread_mutex_unlock(context->canvas_lock_ptr)
RENDER_LOCK
#define RENDER_LOCK () pthread_mutex_lock(&context->render_lock)
RENDER_UNLOCK
#define RENDER_UNLOCK () pthread_mutex_unlock(&context->render_lock)
Typedef Documentation
glXCreateContextAttribsARBProc
typedef GLXContext(* glXCreateContextAttribsARBProc) (Display *, GLXFBConfig, GLXContext, Bool, const int *)
Function Documentation
catch_x_error()
static int catch_x_error (Display * display, XErrorEvent * event) static
Referenced by vice_opengl_renderer_create_child_view().
isExtensionSupported()
static bool isExtensionSupported (const char * extList, const char * extension) static
Referenced by vice_opengl_renderer_create_child_view().
vice_opengl_renderer_clear_current()
void vice_opengl_renderer_clear_current (vice_opengl_renderer_context_t * context)
Referenced by on_widget_realized(), render(), and vice_opengl_renderer_create_child_view().
vice_opengl_renderer_create_child_view()
void vice_opengl_renderer_create_child_view (GtkWidget * widget, vice_opengl_renderer_context_t * context)
Referenced by on_widget_realized().
vice_opengl_renderer_destroy_child_view()
void vice_opengl_renderer_destroy_child_view (vice_opengl_renderer_context_t * context)
Referenced by on_widget_unrealized().
vice_opengl_renderer_make_current()
void vice_opengl_renderer_make_current (vice_opengl_renderer_context_t * context)
Referenced by on_widget_realized(), render(), and vice_opengl_renderer_create_child_view().
vice_opengl_renderer_present_backbuffer()
void vice_opengl_renderer_present_backbuffer (vice_opengl_renderer_context_t * context)
Referenced by render().
vice_opengl_renderer_resize_child_view()
void vice_opengl_renderer_resize_child_view (GtkWidget * widget, vice_opengl_renderer_context_t * context)
Referenced by on_widget_resized().
vice_opengl_renderer_set_viewport()
void vice_opengl_renderer_set_viewport (vice_opengl_renderer_context_t * context)
Referenced by render().
vice_opengl_renderer_set_vsync()
void vice_opengl_renderer_set_vsync (vice_opengl_renderer_context_t * context, bool enable_vsync)
Referenced by render().