vsid: resources.c File Reference
resources.c File Reference
#include "vice.h"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <ctype.h>
#include <strings.h>
#include "archdep.h"
#include "attach.h"
#include "cartridge.h"
#include "lib.h"
#include "log.h"
#include "network.h"
#include "tape.h"
#include "util.h"
#include "uiapi.h"
#include "vice-event.h"
#include "resources.h"
Data Structures
struct resource_ram_s
struct resource_callback_desc_s
the type of the callback vector chain
Macros
#define DBG(x)
#define NUM_ALLOCATED_RESOURCES_INIT 512
Initial size of the array holding resources.
Typedefs
typedef struct resource_ram_s resource_ram_t
typedef struct resource_callback_desc_s resource_callback_desc_t
the type of the callback vector chain
Functions
static void write_resource_item (FILE *f, int num)
static char * string_resource_item (int num, const char *delim)
static unsigned int resources_calc_hash_key (const char *name)
calculate the hash key
static void resources_add_callback (resource_callback_desc_t **where, resource_callback_func_t *callback, void *param)
add a new callback function at the head of the vector chain
static void resources_exec_callback_chain (const resource_callback_desc_t *callbacks, const char *name)
execute a callback vector chain
static void resources_issue_callback (resource_ram_t *res, int global_callback)
issue callbacks for a modified resource
static resource_ram_t * lookup (const char *name)
int resources_register_int (const resource_int_t *r)
register an array(!) of integer resources
int resources_register_string (const resource_string_t *r)
static void resources_free (void)
void resources_shutdown (void)
Shutdown resources.
resource_type_t resources_query_type (const char *name)
int resources_write_item_to_file (FILE *fp, const char *name)
char * resources_write_item_to_string (const char *name, const char *delim)
static void resource_create_event_data (char **event_data, int *data_size, resource_ram_t *r, resource_value_t value)
static void resource_record_event (resource_ram_t *r, resource_value_t value)
int resources_init (const char *machine)
Initialize resources module.
static int resources_set_value_internal (resource_ram_t *r, resource_value_t value)
int resources_set_value (const char *name, resource_value_t value)
static int resources_set_internal_int (resource_ram_t *r, int value)
static int resources_set_internal_string (resource_ram_t *r, const char *value)
int resources_set_int (const char *name, int value)
int resources_set_string (const char *name, const char *value)
void resources_set_value_event (void *data, int size)
int resources_set_int_sprintf (const char *name, int value,...)
int resources_set_string_sprintf (const char *name, const char *value,...)
int resources_set_value_string (const char *name, const char *value)
int resources_get_value (const char *name, void *value_return)
bool resources_exists (const char *name)
Determine if a resource exists.
int resources_get_int (const char *name, int *value_return)
Get value for resource name and store in value_return.
int resources_get_string (const char *name, const char **value_return)
Get string resource name and store in value_return.
int resources_get_int_sprintf (const char *name, int *value_return,...)
int resources_get_string_sprintf (const char *name, const char **value_return,...)
int resources_set_default_int (const char *name, int value)
int resources_set_default_string (const char *name, char *value)
int resources_get_default_value (const char *name, void *value_return)
int resources_set_defaults (void)
int resources_set_event_safe (void)
set resources tagged RES_EVENT_STRICT to their event_strict_value
void resources_get_event_safe_list (event_list_state_t *list)
int resources_toggle (const char *name, int *new_value_return)
int resources_touch (const char *name)
static int check_emu_id (const char *buf, const char *checkstring)
Check whether ‘buf’ is the emulator ID for the machine we are emulating.
int resources_read_item_from_file (FILE *f)
static int check_resource_file_version (const char *fname)
static int load_resource_file (const char *fname)
int resources_load (const char *fname)
load resources from a file, keep existing settings
int resources_reset_and_load (const char *fname)
static int resource_item_isdefault (int num)
check if a resource contains its default value
int resources_save (const char *fname)
int resources_dump (const char *fname)
dump ALL resources of the current machine into a file
void resources_log_active (void)
log resources that do not have their default values
int resources_register_callback (const char *name, resource_callback_func_t *callback, void *callback_param)
Variables
static unsigned int num_resources
static unsigned int num_allocated_resources
static resource_ram_t * resources
static char * machine_id = NULL
static const unsigned int logHashSize = 10
use a hash table with 1024 entries
static int * hashTable = NULL
static resource_callback_desc_t * resource_modified_callback = NULL
char * vice_config_file = NULL
Configuration filename set via -config.
static const char * versionmessage
Macro Definition Documentation
DBG
#define DBG (x)
NUM_ALLOCATED_RESOURCES_INIT
#define NUM_ALLOCATED_RESOURCES_INIT 512
Initial size of the array holding resources.
Typedef Documentation
resource_callback_desc_t
typedef struct resource_callback_desc_s resource_callback_desc_t
the type of the callback vector chain
resource_ram_t
typedef struct resource_ram_s resource_ram_t
Function Documentation
check_emu_id()
static int check_emu_id (const char * buf, const char * checkstring) static
Check whether ‘buf’ is the emulator ID for the machine we are emulating.
Referenced by check_resource_file_version(), load_resource_file(), and resources_save().
check_resource_file_version()
static int check_resource_file_version (const char * fname) static
< read mode (text)
Referenced by resources_load(), and resources_reset_and_load().
load_resource_file()
static int load_resource_file (const char * fname) static
< read mode (text)
Referenced by resources_load().
lookup()
static resource_ram_t * lookup (const char * name) static
Referenced by resources_exists(), resources_get_default_value(), resources_get_int(), resources_get_string(), resources_get_value(), resources_query_type(), resources_read_item_from_file(), resources_register_callback(), resources_register_int(), resources_register_string(), resources_set_default_int(), resources_set_default_string(), resources_set_int(), resources_set_string(), resources_set_value(), resources_set_value_event(), resources_set_value_string(), resources_toggle(), resources_write_item_to_file(), and resources_write_item_to_string().
resource_create_event_data()
static void resource_create_event_data (char ** event_data, int * data_size, resource_ram_t * r, resource_value_t value) static
Referenced by resource_record_event(), and resources_get_event_safe_list().
resource_item_isdefault()
static int resource_item_isdefault (int num) static
check if a resource contains its default value
Referenced by resources_log_active(), and resources_save().
resource_record_event()
static void resource_record_event (resource_ram_t * r, resource_value_t value) static
Referenced by resources_set_int(), resources_set_string(), resources_set_value(), and resources_toggle().
resources_add_callback()
static void resources_add_callback (resource_callback_desc_t ** where, resource_callback_func_t * callback, void * param) static
add a new callback function at the head of the vector chain
Referenced by resources_register_callback().
resources_calc_hash_key()
static unsigned int resources_calc_hash_key (const char * name) static
calculate the hash key
Referenced by lookup(), resources_register_int(), and resources_register_string().
resources_dump()
int resources_dump (const char * fname)
dump ALL resources of the current machine into a file
< write mode (text)
Referenced by cmdline_dumpconfig().
resources_exec_callback_chain()
static void resources_exec_callback_chain (const resource_callback_desc_t * callbacks, const char * name) static
execute a callback vector chain
Referenced by load_resource_file(), resources_issue_callback(), resources_set_defaults(), and resources_set_event_safe().
resources_exists()
bool resources_exists (const char * name)
Determine if a resource exists.
Parameters
[in] name resource name
Returns
true if resource name exists
Referenced by settings_rom_widget_create().
resources_free()
static void resources_free (void) static
Referenced by resources_shutdown().
resources_get_default_value()
int resources_get_default_value (const char * name, void * value_return)
Referenced by cmdline_log_active(), mediator_get_factory_boolean(), mediator_get_factory_int(), mediator_get_factory_string(), on_reset_clicked(), on_reset_icon_clicked(), on_reset_to_defaults_clicked(), vice_gtk3_resource_browser_factory(), vice_gtk3_resource_radiogroup_factory(), vice_gtk3_resource_scale_custom_factory(), vice_gtk3_resource_scale_int_factory(), vice_gtk3_resource_spin_double_factory(), and vice_gtk3_resource_spin_int_factory().
resources_get_event_safe_list()
void resources_get_event_safe_list (event_list_state_t * list)
Referenced by network_server_connect_trap().
resources_get_int()
int resources_get_int (const char * name, int * value_return)
Get value for resource name and store in value_return.
If the resource is unknown, the return value is set to 0.
Parameters
[in] name resource name
[out] value_return resource value target
Returns
0 on succes, -1 on failure
Referenced by _limit_longname(), actions_display_setup_ui(), actions_joystick_setup_ui(), actions_vsid_setup_ui(), autostart_autodetect(), c64_glue_widget_sync(), c64_reset_with_iec_sync(), c64dtv_hummer_adc_sync(), c64io_vicii_init(), c64meminit(), c64model_get(), c64model_set(), cart_detach_action(), clockport_device_widget_create(), cmdhd_findbaselba(), cmdline_log_active(), create_c64_glue_widget(), create_controls_layout(), create_device_combo(), create_disk_attach_dialog(), create_dww_check_button(), create_plus4_layout(), create_real_device7_check_button(), create_smart_attach_dialog(), create_tape_attach_dialog(), crt_control_widget_create(), custom_get_display_value(), custom_new_helper(), diagnostic_pin_toggle_action(), drive_jam(), drive_snapshot_write_module(), emulation_speed_submenu_create(), exp_new_helper(), expand_shortname(), fastsid_init(), fsdevice_limit_createnamelength(), get_rsinterface_index(), init_drive_emulation_state(), joystick_menu_popup_create(), kbdmapping_widget_update(), kernal_revision_widget_create(), kernal_revision_widget_sync(), kernal_revision_widget_update(), keyboard_set_default_keymap_file(), keyboard_set_keymap_file(), keymap_resources_init(), keyset_joystick_toggle_action(), m93c86_snapshot_read_module(), machine_get_keyboard_type(), machine_model_handler_c128(), machine_shutdown(), machine_specific_reset(), makeshortheader(), mediator_get_resource_boolean(), mediator_get_resource_int(), mediator_new(), mem_initialize_memory(), mixer_widget_create(), mixer_widget_sid_type_changed(), mon_maincpu_toggle_trace(), mon_maincpu_trace(), monitor_binary_process_resource_get(), monitor_open_action(), mouse_grab_toggle_action(), native_monitor(), on_blank_toggled(), on_crtc_toggled(), on_custom_changed(), on_drag_data_received(), on_dww_toggled(), on_exp_changed(), on_keyboard_type_toggled(), on_model_toggled(), on_radio_toggled(), on_reset_clicked(), on_response(), on_row_activated(), on_rsinterface_changed(), on_save_video_filename(), on_scale_int_changed(), on_screen2001_toggled(), on_server_mask_toggled(), on_vsync_set_border_mode(), on_widget_hover(), output_graphics_open(), pet_io_size_widget_sync(), pet_keyboard_type_widget_create(), pet_keyboard_type_widget_sync(), pet_misc_widget_create(), pet_misc_widget_sync(), pet_ram9_widget_sync(), pet_rama_widget_sync(), pet_set_ram9a_sensitivity(), plus4_debug_dump_resources(), plus4_mem_hack_callback(), plus4_mem_size_callback(), psid_ffwd_action(), psid_init_driver(), psid_init_tune(), psid_override_toggle_action(), quit_action(), reboot_for_autostart(), rendering_area_event_handler(), resid_init(), resource_radiogroup_new_helper(), resource_scale_int_new_helper(), resource_spin_int_new_helper(), resources_get_int_sprintf(), response_callback(), scpu_jiffy_switch_toggle_action(), scpu_speed_switch_toggle_action(), set_speed_resource(), set_video_standard(), settings_c64_memhacks_widget_create(), settings_model_widget_create(), settings_tapeport_widget_create(), settings_userport_widget_create(), show_statusbar_secondary_toggle_action(), sid_engine_model_widget_create(), sid_model_widget_create(), sid_model_widget_sync(), sid_snapshot_read_module(), sid_snapshot_read_module_extended(), sid_snapshot_write_module(), sid_snapshot_write_module_extended(), sid_snapshot_write_module_simple(), sid_sound_machine_channels(), sid_sound_machine_set_engine_hooks(), sid_sound_widget_create(), speed_cpu_custom_action(), speed_fps_custom_action(), supercpu_jiffy_led_create(), supercpu_turbo_led_create(), swap_controlport_toggle_action(), tap_create(), tap_header_read(), try_attach_tapecart(), ui_create_main_window(), ui_is_fullscreen_from_canvas(), ui_settings_dialog_show(), ui_volume_button_create(), uimon_window_open_impl(), uimon_window_resume_impl(), uimon_window_suspend_impl(), update_cart_default_type_widget(), update_cpu_radio_buttons(), update_crt_controls(), update_fps_radio_buttons(), userport_device_check_button_new(), vdc_model_widget_update(), vice_gtk3_resource_radiogroup_get(), vice_gtk3_resource_radiogroup_sync(), vice_gtk3_resource_scale_custom_sync(), vice_gtk3_resource_scale_int_sync(), vice_gtk3_resource_spin_custom_new(), vice_gtk3_resource_spin_int_get(), vice_gtk3_resource_spin_int_new(), vice_gtk3_resource_spin_int_sync(), vicii_color_update_palette(), vicii_get_crt_type(), vicii_get_pixel_aspect(), vicii_timing_set(), video_model_widget_update(), video_render_initraw(), and vsid_mixer_widget_update().
resources_get_int_sprintf()
int resources_get_int_sprintf (const char * name, int * value_return, ...)
Referenced by actions_display_setup_ui(), compute_drives_enabled_mask(), create_extra_widget(), create_joyport_combo(), drive_disable(), drive_dos_widget_sync_combo(), drive_enable(), drive_get_type_by_devnr(), drive_model_widget_create(), drive_ram_widget_create(), drive_snapshot_write_module(), ffmpeg_widget_create(), get_device_traps_state(), get_drive_type(), get_iec_device_state(), get_keyset_resources(), get_trapflags(), get_true_drive_emulation_state(), iec_callback(), init_drive_emulation_state(), joystick_device_widget_create(), main_init_hack(), mon_drive_is_fsdevice(), on_format_changed(), on_ram_block_toggled(), on_swap_joysticks_toggled(), set_window_geometry_from_resources(), settings_drive_widget_create(), show_statusbar_toggle_action(), sid_snapshot_write_module_simple(), ui_action_toggle_show_statusbar(), ui_datasette_update_sensitive(), ui_enable_drive_status(), ui_get_drive_type(), ui_init_finalize(), ui_is_fullscreen(), ui_update_fullscreen_decorations(), userport_set_device(), vdrive_snapshot_module_read(), vdrive_snapshot_module_write(), vic20_ram_blocks_widget_create(), and video_palette_widget_create().
resources_get_string()
int resources_get_string (const char * name, const char ** value_return)
Get string resource name and store in value_return.
If the resource name is unknown, value_return is set to NULL.
Parameters
[in] name resource name
[out] value_return resource value target
Returns
0 on success, -1 on failure
Referenced by archdep_get_hvsc_dir(), c64model_get(), cmdline_log_active(), create_device_combobox(), create_printer_widget(), create_serial_entry(), driverom_load(), get_double_resource(), keymap_resources_init(), load_keymap_file(), logfile_widget_create(), main_program(), mediator_get_resource_string(), mediator_new(), mem_load(), on_browse_clicked(), on_enable_toggled(), on_launcher_clicked(), on_radio_toggled(), on_resource_browser_browse_clicked(), on_resource_browser_save_clicked(), on_save_as_clicked(), on_save_video_filename(), plus4_debug_dump_resources(), prepend_dir_to_path(), printer_driver_widget_create(), printer_output_mode_widget_create(), resources_get_string_sprintf(), screenshot_get_quickscreenshot_format(), settings_ieee488_widget_create(), settings_ieeeflash64_widget_create(), settings_monitor_widget_create(), settings_ramlink_widget_create(), statusbar_recording_widget_set_time(), ui_hotkeys_load_dialog_show(), ui_hotkeys_save_dialog_show(), uimon_set_font(), update_buttons(), update_cart_default_file_widget(), vice_gtk3_resource_browser_get(), vice_gtk3_resource_browser_new(), vice_gtk3_resource_browser_save_new(), and vice_gtk3_resource_browser_sync().
resources_get_string_sprintf()
int resources_get_string_sprintf (const char * name, const char ** value_return, ...)
Referenced by create_combo_box(), create_printer_widget(), ffmpeg_widget_create(), mon_drive_get_fsdevice_path(), output_graphics_open(), and save_video_recording_handler().
resources_get_value()
int resources_get_value (const char * name, void * value_return)
Referenced by monitor_binary_process_resource_get(), and resources_touch().
resources_init()
int resources_init (const char * machine)
Initialize resources module.
Allocated memory for resource objects and the hash table.
Parameters
[in] machine machine name
Returns
0
Referenced by init_resources(), and sampler_resources_init().
resources_issue_callback()
static void resources_issue_callback (resource_ram_t * res, int global_callback) static
issue callbacks for a modified resource
Referenced by resources_read_item_from_file(), resources_set_defaults(), resources_set_event_safe(), resources_set_internal_int(), resources_set_internal_string(), resources_set_value_internal(), and resources_set_value_string().
resources_load()
int resources_load (const char * fname)
load resources from a file, keep existing settings
Referenced by cmdline_add_config(), main_program(), resources_reset_and_load(), and settings_load_filename_callback().
resources_log_active()
void resources_log_active (void)
log resources that do not have their default values
resources_query_type()
resource_type_t resources_query_type (const char * name)
Referenced by cmdline_log_active(), mixer_widget_create(), mon_resource_get(), mon_resource_set(), monitor_binary_process_resource_get(), monitor_binary_process_resource_set(), and romset_archive_item_select().
resources_read_item_from_file()
int resources_read_item_from_file (FILE * f)
Todo:
FIXME: make event safe
Referenced by load_resource_file(), and romset_file_load().
resources_register_callback()
int resources_register_callback (const char * name, resource_callback_func_t * callback, void * callback_param)
resources_register_int()
int resources_register_int (const resource_int_t * r)
register an array(!) of integer resources
Referenced by artstudiodrv_resources_init(), autostart_resources_init(), c64_256k_resources_init(), c64_glue_resources_init(), c64_resources_init(), cartio_resources_init(), debug_resources_init(), debugcart_resources_init(), drive_resources_init(), drive_resources_type_init(), event_resources_init(), ffmpegexedrv_resources_init(), file_system_resources_init(), fsdevice_resources_init(), iec_resources_init(), interface_serial_init_resources(), kbdbuf_resources_init(), keyboard_resources_init(), keymap_resources_init(), koaladrv_resources_init(), machine_common_resources_init(), memory_hacks_resources_init(), minipaintdrv_resources_init(), monitor_binary_resources_init(), monitor_network_resources_init(), monitor_resources_init(), mouse_ps2_resources_init(), myacia_init_resources(), network_resources_init(), output_text_init_resources(), plus60k_resources_init(), psid_resources_init(), ram_resources_init(), raster_resources_chip_init(), rs232drv_resources_init(), rsuser_resources_init(), sampler_resources_init(), serial_iec_device_resources_init(), sid_common_resources_init(), sid_resources_init(), sound_resources_init(), tapecart_resources_init(), tapeport_resources_init(), tapertc_resources_init(), traps_resources_init(), ui_resources_init(), userport_resources_init(), userport_rtc_58321a_resources_init(), userport_rtc_ds1307_resources_init(), vicii_resources_init(), video_resources_chip_init(), vsync_resources_init(), and zmbvdrv_resources_init().
resources_register_string()
int resources_register_string (const resource_string_t * r)
Referenced by autostart_resources_init(), c64_256k_resources_init(), c64_resources_init(), driver_select_init_resources(), driver_select_userport_init_resources(), event_resources_init(), ffmpegexedrv_resources_init(), fliplist_resources_init(), fsdevice_resources_init(), iec_resources_init(), keymap_resources_init(), log_resources_init(), machine_common_resources_init(), monitor_binary_resources_init(), monitor_network_resources_init(), monitor_resources_init(), network_resources_init(), output_select_init_resources(), output_select_userport_init_resources(), output_text_init_resources(), plus256k_resources_init(), plus60k_resources_init(), rs232drv_resources_init(), sampler_file_resources_init(), screenshot_resources_init(), sound_resources_init(), sysfile_resources_init(), tapecart_resources_init(), ui_hotkeys_resources_init(), ui_resources_init(), video_resources_chip_init(), and zmbvdrv_resources_init().
resources_reset_and_load()
int resources_reset_and_load (const char * fname)
Referenced by settings_load_action(), and settings_load_filename_callback().
resources_save()
int resources_save (const char * fname)
< read mode (text)
< write mode (text)
Referenced by machine_shutdown(), on_settings_save_to_filename(), and settings_save_action().
resources_set_default_int()
int resources_set_default_int (const char * name, int value)
Referenced by keymap_resources_init().
resources_set_default_string()
int resources_set_default_string (const char * name, char * value)
Referenced by keymap_resources_init().
resources_set_defaults()
int resources_set_defaults (void)
Todo:
FIXME: make event safe
Referenced by cmdline_default(), main_program(), resources_reset_and_load(), and restore_default_callback().
resources_set_event_safe()
int resources_set_event_safe (void)
set resources tagged RES_EVENT_STRICT to their event_strict_value
Referenced by network_client_connect_trap(), and network_start_server().
resources_set_int()
int resources_set_int (const char * name, int value)
Referenced by autostart_autodetect(), border_set_func(), c64model_set(), c64rom_load_kernal(), diagnostic_pin_toggle_action(), diagnosticpin_led_callback(), drive_init(), drive_snapshot_read_module(), fullscreen_decorations_toggle_action(), io_source_detach(), kbdmapping_widget_update(), keyboard_set_keymap_file(), keymap_resources_init(), keyset_joystick_toggle_action(), mediator_update_boolean(), mediator_update_int(), mon_maincpu_toggle_trace(), monitor_binary_process_resource_set(), mouse_grab_toggle_action(), on_blank_toggled(), on_c64_glue_toggled(), on_crtc_toggled(), on_custom_changed(), on_custom_spin_value_changed(), on_device_changed(), on_dww_toggled(), on_exp_changed(), on_keyboard_type_toggled(), on_model_toggled(), on_radio_toggled(), on_real_device7_toggled(), on_revision_toggled(), on_rsinterface_changed(), on_scale_int_changed(), on_screen2001_toggled(), on_server_mask_toggled(), on_spin_button_value_changed(), on_toggled(), on_volume_value_changed(), on_window_configure_event(), play_current_tune(), psid_ffwd_action(), psid_init_driver(), psid_override_toggle_action(), psid_play_action(), resources_set_int_sprintf(), restore_drive_emulation_state(), romset_archive_item_select(), scpu_jiffy_switch_toggle_action(), scpu_speed_switch_toggle_action(), set_chip_rendermode(), set_kernal_revision(), set_sid_engine_with_fallback(), set_speed_resource(), set_tapeport_device(), set_video_standard(), setup_for_prg_vfs(), show_statusbar_secondary_toggle_action(), sid_set_engine_model(), sid_snapshot_read_module_simple(), soundmovie_start(), supercpu_jiffy_led_callback(), supercpu_turbo_led_callback(), swap_controlport_toggle_action(), try_attach_tapecart(), and vice_gtk3_resource_scale_custom_set().
resources_set_int_sprintf()
int resources_set_int_sprintf (const char * name, int value, ...)
Referenced by attempt_to_set_drive_type(), autostart_disk(), autostart_prg_with_virtual_fs(), border_mode_action(), clear_trapflags(), disable_invalid_expansions(), drive_init(), drive_snapshot_read_module(), event_playback_attach_image(), main_init_hack(), on_audio_codec_changed(), on_combo_changed(), on_device_changed(), on_external_toggled(), on_radio_toggled(), on_ram_block_toggled(), on_readonly_toggled(), on_video_codec_changed(), on_window_configure_event(), restore_drive_emulation_state(), restore_trapflags(), set_device_traps_state(), set_iec_device_state(), set_keyset_resources(), set_true_drive_emulation_mode(), show_statusbar_toggle_action(), sid_snapshot_read_module_simple(), try_attach_disk(), ui_action_toggle_show_statusbar(), ui_set_fullscreen_enabled(), and userport_set_device().
resources_set_internal_int()
static int resources_set_internal_int (resource_ram_t * r, int value) static
Referenced by resources_set_int(), and resources_toggle().
resources_set_internal_string()
static int resources_set_internal_string (resource_ram_t * r, const char * value) static
Referenced by resources_set_string().
resources_set_string()
int resources_set_string (const char * name, const char * value)
Referenced by browse_filename_callback(), c64model_set(), eeprom_filename_callback(), load_callback(), mediator_update_string(), on_bg_color_set(), on_device_changed(), on_eject_icon_clicked(), on_fg_color_set(), on_font_set(), on_pet_charset_load_clicked(), on_radio_toggled(), on_reset_icon_clicked(), on_reset_to_defaults_clicked(), on_save_audio_filename(), on_stdout_check_toggled(), prepend_dir_to_path(), resources_set_string_sprintf(), restore_path(), romset_archive_item_select(), save_filename_callback(), set_double_resource(), set_kernal_revision(), set_serial_resource(), sound_open(), sound_stop_recording(), soundmovie_start(), soundmovie_stop(), ui_hotkeys_load_vice_default(), uimon_set_font(), vice_gtk3_resource_browser_reset(), and vice_gtk3_resource_browser_set().
resources_set_string_sprintf()
int resources_set_string_sprintf (const char * name, const char * value, ...)
Referenced by browse_filename_callback(), fsdevice_set_directory(), on_combo_changed(), and on_format_changed().
resources_set_value()
int resources_set_value (const char * name, resource_value_t value)
Referenced by cmdline_parse(), and resources_touch().
resources_set_value_event()
void resources_set_value_event (void * data, int size)
Referenced by event_playback_event_list().
resources_set_value_internal()
static int resources_set_value_internal (resource_ram_t * r, resource_value_t value) static
Referenced by resources_set_value(), and resources_set_value_event().
resources_set_value_string()
int resources_set_value_string (const char * name, const char * value)
Referenced by cmdline_parse(), mon_resource_set(), and monitor_binary_process_resource_set().
resources_shutdown()
void resources_shutdown (void)
Shutdown resources.
Referenced by cmdline_help(), and machine_shutdown().
resources_toggle()
int resources_toggle (const char * name, int * new_value_return)
resources_touch()
int resources_touch (const char * name)
Referenced by iec_drive_idling_method(), and init_raster().
resources_write_item_to_file()
int resources_write_item_to_file (FILE * fp, const char * name)
Referenced by romset_file_save().
resources_write_item_to_string()
char * resources_write_item_to_string (const char * name, const char * delim)
Referenced by mon_resource_get(), romset_archive_item_create(), and romset_file_list().
string_resource_item()
static char * string_resource_item (int num, const char * delim) static
Referenced by resources_log_active(), resources_write_item_to_string(), and write_resource_item().
write_resource_item()
static void write_resource_item (FILE * f, int num) static
Referenced by resources_dump(), resources_save(), and resources_write_item_to_file().
Variable Documentation
hashTable
int* hashTable = NULL static
Referenced by lookup(), resources_init(), resources_register_int(), resources_register_string(), and resources_shutdown().
logHashSize
const unsigned int logHashSize = 10 static
use a hash table with 1024 entries
Referenced by resources_calc_hash_key(), and resources_init().
machine_id
char* machine_id = NULL static
Referenced by load_resource_file(), resources_dump(), resources_init(), resources_save(), and resources_shutdown().
num_allocated_resources
unsigned int num_allocated_resources static
Referenced by resources_init(), resources_register_int(), and resources_register_string().
num_resources
unsigned int num_resources static
Referenced by resources_dump(), resources_free(), resources_get_event_safe_list(), resources_init(), resources_log_active(), resources_register_int(), resources_register_string(), resources_save(), resources_set_defaults(), and resources_set_event_safe().
resource_modified_callback
resource_callback_desc_t* resource_modified_callback = NULL static
Referenced by load_resource_file(), resources_issue_callback(), resources_register_callback(), resources_set_defaults(), and resources_set_event_safe().
resources
resource_ram_t* resources static
Referenced by lookup(), resource_item_isdefault(), resources_free(), resources_get_event_safe_list(), resources_init(), resources_register_int(), resources_register_string(), resources_set_defaults(), resources_set_event_safe(), resources_shutdown(), resources_write_item_to_file(), resources_write_item_to_string(), and string_resource_item().
versionmessage
const char* versionmessage static
Initial value:
=
    "Please notice that using configuration files from a different VICE "
    "version is not supported. It should be mostly no problem in practice - "
    "however, if you experience any problems eg. after updating VICE, you might "
    "have to reset the settings to defaults.\n\n"
    "Save the settings now to make this message go away."
Referenced by check_resource_file_version().
vice_config_file
char* vice_config_file = NULL
Configuration filename set via -config.
Referenced by get_config_file_path(), main_program(), resources_load(), resources_save(), and resources_shutdown().