x128: sampler_device_s Struct Reference
sampler_device_s Struct Reference
#include <sampler.h>
Data Fields
const char * name
void(* open)(int channels)
void(* close)(void)
uint8_t(* get_sample)(int channel)
void(* shutdown)(void)
int(* resources_init)(void)
int(* cmdline_options_init)(void)
void(* reset)(void)
Field Documentation
close
void(* sampler_device_s::close) (void)
Referenced by sampler_device_register(), and sampler_stop().
cmdline_options_init
int(* sampler_device_s::cmdline_options_init) (void)
Referenced by sampler_device_register().
get_sample
uint8_t(* sampler_device_s::get_sample) (int channel)
Referenced by sampler_device_register(), and sampler_get_sample().
name
const char* sampler_device_s::name
Referenced by build_tapeport_string(), build_userport_string(), create_device_combo(), create_device_model(), create_joyport_combo(), and sampler_device_register().
open
void(* sampler_device_s::open) (int channels)
Referenced by sampler_device_register(), and sampler_start().
reset
void(* sampler_device_s::reset) (void)
Referenced by sampler_device_register(), and sampler_reset().
resources_init
int(* sampler_device_s::resources_init) (void)
Referenced by sampler_device_register().
shutdown
void(* sampler_device_s::shutdown) (void)
Referenced by sampler_device_register(), and sampler_resources_shutdown().
The documentation for this struct was generated from the following file:
samplerdrv/sampler.h