x128: c128/z80.h File Reference
z80.h File Reference
Macros
#define Z80_4MHZ
in preparation for a better handling of the 'real' speed of the Z80
Functions
void z80_resync_limits (void)
void z80_reset (void)
void z80_mainloop (struct interrupt_cpu_status_s *cpu_int_status, struct alarm_context_s *cpu_alarm_context)
void z80_trigger_dma (void)
void z80_clock_stretch (void)
Variables
struct z80_regs_s z80_regs
Macro Definition Documentation
Z80_4MHZ
#define Z80_4MHZ
in preparation for a better handling of the 'real' speed of the Z80
Function Documentation
z80_clock_stretch()
void z80_clock_stretch (void)
Referenced by read_unconnected_io(), store_unconnected_io(), z80_c64io_d000_read(), z80_c64io_d000_store(), z80_c64io_d100_read(), z80_c64io_d100_store(), z80_c64io_d200_read(), z80_c64io_d200_store(), z80_c64io_d300_read(), z80_c64io_d300_store(), z80_c64io_d400_read(), z80_c64io_d400_store(), z80_c64io_d700_read(), z80_c64io_d700_store(), z80_c64io_de00_read(), z80_c64io_de00_store(), z80_c64io_df00_read(), z80_c64io_df00_store(), z80_cia1_read(), z80_cia1_store(), z80_cia2_read(), z80_cia2_store(), z80_colorram_read(), z80_colorram_store(), z80_mmu_read(), z80_mmu_store(), z80_vdc_read(), and z80_vdc_store().
z80_mainloop()
void z80_mainloop (struct interrupt_cpu_status_s * cpu_int_status, struct alarm_context_s * cpu_alarm_context)
z80_reset()
void z80_reset (void)
Referenced by machine_specific_reset().
z80_resync_limits()
void z80_resync_limits (void)
Referenced by z80mem_update_config().
z80_trigger_dma()
void z80_trigger_dma (void)
Referenced by mmu_switch_cpu().
Variable Documentation
z80_regs
struct z80_regs_s z80_regs extern
Referenced by export_registers(), import_registers(), maincpu_monitor_interface_get(), and z80core_reset().