vsid: arch/shared/hotkeys/uihotkeys.c File Reference
uihotkeys.c File Reference
UI-agnostic hotkeys.
#include "vice.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include "archdep_defs.h"
#include "archdep_exit.h"
#include "archdep_file_exists.h"
#include "archdep_get_vice_hotkeysdir.h"
#include "archdep_user_config_path.h"
#include "cmdline.h"
#include "hotkeystypes.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "parser.h"
#include "vhkkeysyms.h"
#include "uiapi.h"
#include "uiactions.h"
#include "util.h"
#include "version.h"
#include "uihotkeys.h"
#include "vhkdebug.h"
Macros
#define VHK_FILENAME_LEN (1u + 7u + 1u + 4u)
to disable debugging, uncomment the #define, but keep the #include:
Functions
static void update_vhk_source_type (const char *path)
Forward declarations.
static int vhk_filename_set (const char *val, void *param)
VICE resources, command line options and their handlers.
int ui_hotkeys_resources_init (void)
Initialize resources used by the custom hotkeys.
int ui_hotkeys_cmdline_options_init (void)
Initialize command line options used by the custom hotkeys.
void ui_hotkeys_init (const char *prefix)
Initialize hotkeys system.
void ui_hotkeys_shutdown (void)
Shut down hotkeys system.
void ui_hotkeys_load_vice_default (void)
Load the default hotkeys.
bool ui_hotkeys_load_user_default (void)
Try to load user-defined hotkeys from the default user file.
static void save_log_io_error (void)
Helper: log I/O error.
static bool save_header (FILE *fp)
Output the header for a custom hotkeys file.
bool ui_hotkeys_save_as (const char *path)
Save all currently registered hotkeys to file.
void ui_hotkeys_install_by_map (ui_action_map_t *map)
Install hotkey for a UI action and its menu item(s), if any.
void ui_hotkeys_update_by_map (ui_action_map_t *map, uint32_t vice_keysym, uint32_t vice_modmask)
Update hotkey for a UI action and its menu item(s), if any.
void ui_hotkeys_update_by_action (int action, uint32_t vice_keysym, uint32_t vice_modmask)
Update hotkey for a UI action and its menu item(s), if any.
void ui_hotkeys_remove_by_map (ui_action_map_t *map)
Remove hotkey from UI action and its menu item(s), if any.
void ui_hotkeys_remove_by_action (int action)
Remove hotkey from UI action and its menu item(s), if any.
void ui_hotkeys_remove_all (void)
Remove all hotkeys.
bool ui_hotkeys_load (const char *path)
Load hotkeys file.
const char * ui_hotkeys_vhk_filename_vice (void)
Generate default hotkeys file name.
char * ui_hotkeys_vhk_filename_user (void)
Generate default filename for user-defined .vhk files.
char * ui_hotkeys_vhk_full_path_user (void)
Get full path to user-defined hotkeys for machine and UI.
char * ui_hotkeys_vhk_full_path_vice (void)
Get full path to VICE-provided hotkeys for machine and UI.
vhk_source_t ui_hotkeys_vhk_source_type (void)
Get source type of last succesfully parsed hotkeys file.
char * ui_hotkeys_vhk_source_path (void)
Get full path to current hotkeys source.
void ui_hotkeys_reload (void)
Reload hotkeys.
bool ui_hotkeys_save (void)
Save current hotkeys.
Variables
log_t vhk_log
Log for the hotkeys system.
static char * vhk_prefix = NULL
Prefix for .vhk filenames.
static char * vhk_filename = NULL
Path to current hotkey file.
static bool vhk_file_pending = false
A .vhk file is pending.
static bool vhk_init_done = false
The hotkeys system is initialized.
static vhk_source_t vhk_source = VHK_SOURCE_NONE
Source of vhk file parsed.
static resource_string_t resources_string []
String type resources.
static const cmdline_option_t cmdline_options []
List of command line options.
Detailed Description
UI-agnostic hotkeys.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
VHK_FILENAME_LEN
#define VHK_FILENAME_LEN (1u + 7u + 1u + 4u)
to disable debugging, uncomment the #define, but keep the #include:
Length of the filename string for VICE user-defined hotkeys files
This excludes the prefix set by ui_hotkeys_init(), the machine name and the terminating null
"{prefix}-hotkeys-{machine}.vhk"
Function Documentation
save_header()
static bool save_header (FILE * fp) static
Output the header for a custom hotkeys file.
Parameters
[in] fp file descriptor
Returns
true on success
Referenced by ui_hotkeys_save_as().
save_log_io_error()
static void save_log_io_error (void) static
Helper: log I/O error.
Logs libc I/O errors to the hotkeys log, including errno and description.
Referenced by save_header(), and ui_hotkeys_save_as().
ui_hotkeys_cmdline_options_init()
int ui_hotkeys_cmdline_options_init (void)
Initialize command line options used by the custom hotkeys.
Returns
0 on success
Referenced by main_program().
ui_hotkeys_init()
void ui_hotkeys_init (const char * prefix)
Initialize hotkeys system.
Initialize the hotkeys system, setting a UI prefix for user-defined hotkeys files and loading hotkeys. Although all UIs share the VICE-provided hotkeys files, we need a prefix per UI so saving custom hotkeys in the user's configuration directory can be done from multiple UIs.
Predence of hotkeys file to parse:
When -default is used on the command line we load the VICE-provided file "hotkeys.vhk" in VICE_DATADIR/hotkeys.
When the "HotkeyFile" resource contains a non-empty string, we load that file.
When a user-defined hotkeys file for the current emulator and UI is found in the user's config dir (say "~/.config/vice/gtk3-hotkeys-PET.vhk"), we load that file.
When none of the above is true we load the VICE-provided file "hotkeys.vhk" in VICE_DATADIR/hotkeys.
Parameters
[in] prefix UI name prefix for user-defined .vhk files
Referenced by ui_init_finalize().
ui_hotkeys_install_by_map()
void ui_hotkeys_install_by_map (ui_action_map_t * map)
Install hotkey for a UI action and its menu item(s), if any.
Calls the arch-specific virtual method ui_hotkeys_arch_install_by_map().
Parameters
[in] map vhk map object
Referenced by vhk_parser_handle_mapping().
ui_hotkeys_load()
bool ui_hotkeys_load (const char * path)
Load hotkeys file.
Parameters
[in] path path to hotkeys file
Returns
true on success
Referenced by ui_hotkeys_init(), ui_hotkeys_load_user_default(), ui_hotkeys_load_vice_default(), ui_hotkeys_reload(), and vhk_filename_set().
ui_hotkeys_load_user_default()
bool ui_hotkeys_load_user_default (void)
Try to load user-defined hotkeys from the default user file.
Returns
false if the default user file doesn't exist, true otherwise
Referenced by ui_hotkeys_init(), and ui_hotkeys_reload().
ui_hotkeys_load_vice_default()
void ui_hotkeys_load_vice_default (void)
Load the default hotkeys.
Parse the VICE-provided hotkey files, clearing any user-defined hotkeys. Also set the "HotkeyFile" resource to "".
Referenced by hotkeys_default_action(), on_defaults_clicked(), restore_default_callback(), ui_hotkeys_init(), and ui_hotkeys_reload().
ui_hotkeys_reload()
void ui_hotkeys_reload (void)
Reload hotkeys.
(Re)load hotkeys, using the same order as when starting the emulator, except we're skipping the -default check.
See also
ui_hotkeys_init() for an explanation of logic used to determine which file to load.
Referenced by hotkeys_load_action(), and on_reload_clicked().
ui_hotkeys_remove_all()
void ui_hotkeys_remove_all (void)
Remove all hotkeys.
Remove all hotkeys registered and clear all accelerator labels on menu items. Calls virtual method ui_hotkeys_arch_remove_by_map().
Referenced by clear_all_hotkeys(), hotkeys_clear_action(), hotkeys_load_action(), and vhk_parser_do_clear().
ui_hotkeys_remove_by_action()
void ui_hotkeys_remove_by_action (int action)
Remove hotkey from UI action and its menu item(s), if any.
Clear hotkey associated with UI action and remove any menu item accelerator labels if present. Indirectly calls virtual method ui_hotkeys_arch_remove_by_map().
Parameters
[in] map vhk map object
Referenced by dialog_clear_handler(), and on_context_clear_activate().
ui_hotkeys_remove_by_map()
void ui_hotkeys_remove_by_map (ui_action_map_t * map)
Remove hotkey from UI action and its menu item(s), if any.
Clear hotkey associated with the UI action in map and remove any menu item accelerator labels if present. Calls virtual method ui_hotkeys_arch_remove_by_map().
Parameters
[in] map UI action map object
Referenced by ui_hotkeys_remove_by_action().
ui_hotkeys_resources_init()
int ui_hotkeys_resources_init (void)
Initialize resources used by the custom hotkeys.
Returns
0 on success
Referenced by main_program().
ui_hotkeys_save()
bool ui_hotkeys_save (void)
Save current hotkeys.
Save current hotkeys to either the filename in the resource "HotkeyFile" or to the UI+emu-specific filename in the user's configuration directory.
Returns
true on success
Referenced by hotkeys_save_action(), and on_save_clicked().
ui_hotkeys_save_as()
bool ui_hotkeys_save_as (const char * path)
Save all currently registered hotkeys to file.
Generate file path and write all currently defined hotkeys to it. This file will contain hotkeys specific to the current emulator, UI and OS, meaning files generated on MacOS will lead to weird results when used on non-MacOS, and vice-versa.
Parameters
[in] path filename of vhk file to generate
Returns
true on success
Referenced by save_as_callback(), save_callback(), and ui_hotkeys_save().
ui_hotkeys_shutdown()
void ui_hotkeys_shutdown (void)
Shut down hotkeys system.
Clear up all resources used by the hotkeys system and close the log. The "virtual method" ui_hotkeys_arch_shutdown() is called first to allow the current UI/arch to clean up its hotkeys data, if any.
Referenced by machine_shutdown().
ui_hotkeys_update_by_action()
void ui_hotkeys_update_by_action (int action, uint32_t vice_keysym, uint32_t vice_modmask)
Update hotkey for a UI action and its menu item(s), if any.
Update hotkey for action, setting the new hotkey to vice_keysym + vice_modmask. Calls virtual methods ui_hotkeys_arch_remove_by_map() and ui_hotkeys_arch_install_by_map() and updates VICE and arch keysysm and modmasks for action.
Parameters
[in] action UI action ID
[in] vice_keysym new VICE keysym
[in] vice_modmask new VICE modifier mask
ui_hotkeys_update_by_map()
void ui_hotkeys_update_by_map (ui_action_map_t * map, uint32_t vice_keysym, uint32_t vice_modmask)
Update hotkey for a UI action and its menu item(s), if any.
Update hotkey for map, setting the new hotkey to vice_keysym + vice_modmask. Calls virtual methods ui_hotkeys_arch_remove_by_map() and ui_hotkeys_arch_install_by_map() and updates VICE and arch keysysm and modmasks in map.
Parameters
[in] map UI action map object
[in] vice_keysym new VICE keysym
[in] vice_modmask new VICE modifier mask
Referenced by dialog_accept_handler(), and ui_hotkeys_update_by_action().
ui_hotkeys_vhk_filename_user()
char * ui_hotkeys_vhk_filename_user (void)
Generate default filename for user-defined .vhk files.
Generate string in the form "$ARCH-hotkeys[-mac]-$MACHINE.vhk".
Returns
filename for user-defined hotkeys
Note
Free result with lib_free() after use
Referenced by ui_hotkeys_save_dialog_show(), and ui_hotkeys_vhk_full_path_user().
ui_hotkeys_vhk_filename_vice()
const char * ui_hotkeys_vhk_filename_vice (void)
Generate default hotkeys file name.
Returns either "hotkeys.vhk" (non-VSID) or "hotkeys-vsid.vhk (VSID).
Returns
filename
Referenced by ui_hotkeys_load_vice_default(), and ui_hotkeys_vhk_full_path_vice().
ui_hotkeys_vhk_full_path_user()
char * ui_hotkeys_vhk_full_path_user (void)
Get full path to user-defined hotkeys for machine and UI.
Generate full path to user-defined hotkeys in the user config directory for the current emulator and UI/arch. For example: /home/billy-bob/.config/vice/gtk3-hotkeys-C64SC.vhk
Returns
full path to user-defined hotkeys
Note
Free result with lib_free() after use
Referenced by ui_hotkeys_load_user_default(), ui_hotkeys_save(), ui_hotkeys_vhk_source_path(), and update_vhk_source_type().
ui_hotkeys_vhk_full_path_vice()
char * ui_hotkeys_vhk_full_path_vice (void)
Get full path to VICE-provided hotkeys for machine and UI.
Returns
full path to hotkeys file in VICE data dir
Note
Free result with lib_free() after use
Referenced by ui_hotkeys_vhk_source_path(), and update_vhk_source_type().
ui_hotkeys_vhk_source_path()
char * ui_hotkeys_vhk_source_path (void)
Get full path to current hotkeys source.
Determine which hotkeys file was last succesfully parsed.
Returns
path to hotkeys file
Note
free with lib_free() after use
Referenced by create_hotkey_file_grid(), on_save_clicked(), and update_hotkeys_info().
ui_hotkeys_vhk_source_type()
vhk_source_t ui_hotkeys_vhk_source_type (void)
Get source type of last succesfully parsed hotkeys file.
Returns
enum indicating source
See also
Enum vhk_source_t in shared/hotkeys/hotkeystypes.h
Referenced by update_hotkeys_info().
update_vhk_source_type()
static void update_vhk_source_type (const char * path) static
Forward declarations.
Update vhk source type.
Check path against the default hotkeys file path in VICE's data directory and against the UI and emu-specific hotkeys file path in the user's configuration directory and set vhk_source accordingly.
Parameters
[in] path path to hotkeys file
Referenced by ui_hotkeys_load(), and ui_hotkeys_save_as().
vhk_filename_set()
static int vhk_filename_set (const char * val, void * param) static
VICE resources, command line options and their handlers.
Set hotkey file and process its contents
Parameters
[in] val new hotkey file
[in] param extra argument (unused)
Returns
0 on success, -1 on error
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
= {
    { "-hotkeyfile", SET_RESOURCE,  (1 << 0) ,
      NULL, NULL, "HotkeyFile", NULL,
      "<name>", "Specify name of hotkey file" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
List of command line options.
Referenced by ui_hotkeys_cmdline_options_init().
resources_string
resource_string_t resources_string[] static
Initial value:
= {
    { "HotkeyFile", "", RES_EVENT_NO, NULL,
      &vhk_filename, vhk_filename_set, NULL },
     { NULL, NULL, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
String type resources.
Referenced by ui_hotkeys_resources_init().
vhk_file_pending
bool vhk_file_pending = false static
A .vhk file is pending.
When the 'HotkeyFile' resource is initially set the UI hasn't finished building the menu and registering actions, so trying to parse a hotkeys file and adding hotkeys for actions will fail. This flag is used to indicate a hotkey file is pending to be parsed.
Referenced by ui_hotkeys_init(), and vhk_filename_set().
vhk_filename
char* vhk_filename = NULL static
Path to current hotkey file.
Note
Freed with ui_hotkeys_shutdown() on emulator shutdown.
Referenced by ui_hotkeys_init(), ui_hotkeys_load(), ui_hotkeys_reload(), ui_hotkeys_save(), ui_hotkeys_save_as(), ui_hotkeys_shutdown(), ui_hotkeys_vhk_source_path(), and vhk_filename_set().
vhk_init_done
bool vhk_init_done = false static
The hotkeys system is initialized.
This flag is used to determine if a new HotkeyFile resource value can be used to parse a hotkeys file, or if it needs to be marked as pending, waiting for the UI to be fully initialized.
Referenced by ui_hotkeys_init(), and vhk_filename_set().
vhk_log
log_t vhk_log
Log for the hotkeys system.
Referenced by save_log_io_error(), textfile_reader_close(), ui_hotkeys_init(), ui_hotkeys_load(), ui_hotkeys_load_user_default(), ui_hotkeys_load_vice_default(), ui_hotkeys_save_as(), ui_hotkeys_shutdown(), vhk_filename_set(), vhk_parser_do_clear(), vhk_parser_do_undef(), vhk_parser_do_warning(), vhk_parser_error(), vhk_parser_handle_mapping(), vhk_parser_parse(), and vhk_parser_warning().
vhk_prefix
char* vhk_prefix = NULL static
Prefix for .vhk filenames.
Set with ui_hotkeys_init(), this string is used to differenciate between UIs/archs, so each can have their own hotkeys on the same system. For example, for the Gtk3 UI, this is "gtk3", which results in the default filename being "gtk3-hotkeys.vhk".
Note
Freed with ui_hotkeys_shutdown() on emulator shutdown.
Referenced by ui_hotkeys_init(), ui_hotkeys_shutdown(), and ui_hotkeys_vhk_filename_user().
vhk_source
vhk_source_t vhk_source = VHK_SOURCE_NONE static
Source of vhk file parsed.
Enum indicating the source of the last succesfully parsed hotkeys file. Initially this will be VHK_SOURCE_NONE, indicating no hotkeys file has been loaded. If a hotkeys file is succesfully parsed it will be set to either VHK_SOURCE_VICE for hotkeys loaded from the VICE data dir, VHK_SOURCE_USER for hotkeys loaded from the user's configuration dir, or VHK_SOURCE_RESOURCE for hotkeys loaded from a custom file specified in the "HotkeyFile" resource.
Referenced by ui_hotkeys_init(), ui_hotkeys_load(), ui_hotkeys_load_user_default(), ui_hotkeys_load_vice_default(), ui_hotkeys_save_as(), ui_hotkeys_vhk_source_path(), ui_hotkeys_vhk_source_type(), and update_vhk_source_type().