x128: traps.c File Reference
traps.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include "cmdline.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "machine-bus.h"
#include "maincpu.h"
#include "mem.h"
#include "resources.h"
#include "traps.h"
#include "types.h"
#include "wdc65816.h"
Data Structures
struct traplist_s
Macros
#define DBG(x)
#define MAX_DEVICES 15 /*! \todo FIXME: is there another constant we can use instead? */
Typedefs
typedef struct traplist_s traplist_t
Functions
static int install_trap (const trap_t *t)
static int remove_trap (const trap_t *t)
static void set_traps_status (int enabled)
static int set_traps_enabled (int val, void *param)
int traps_resources_init (void)
int traps_cmdline_options_init (void)
void traps_init (void)
void traps_shutdown (void)
int traps_add (const trap_t *trap)
int traps_remove (const trap_t *trap)
void traps_refresh (void)
uint32_t traps_handler (void)
int traps_checkaddr (unsigned int addr)
Variables
static traplist_t * traplist = NULL
static log_t traps_log = ((log_t)-1)
static int traps_enabled = 0
Trap-related resources.
int traps_enabled_device [15]
static resource_int_t resources_int []
static const cmdline_option_t cmdline_options []
Trap-related command-line options.
Macro Definition Documentation
DBG
#define DBG (x)
MAX_DEVICES
#define MAX_DEVICES 15 /*! \todo FIXME: is there another constant we can use instead? */
Typedef Documentation
traplist_t
typedef struct traplist_s traplist_t
Function Documentation
install_trap()
static int install_trap (const trap_t * t) static
Referenced by set_traps_status(), traps_add(), and traps_refresh().
remove_trap()
static int remove_trap (const trap_t * t) static
Referenced by set_traps_status(), traps_refresh(), and traps_remove().
set_traps_enabled()
static int set_traps_enabled (int val, void * param) static
Todo:
FIXME: is there another constant we can use instead?
set_traps_status()
static void set_traps_status (int enabled) static
Referenced by set_traps_enabled().
traps_add()
int traps_add (const trap_t * trap)
Referenced by serial_install_traps(), and tape_traps_install().
traps_checkaddr()
int traps_checkaddr (unsigned int addr)
Referenced by monitor_check_icount().
traps_cmdline_options_init()
int traps_cmdline_options_init (void)
Referenced by machine_cmdline_options_init().
traps_handler()
uint32_t traps_handler (void)
traps_init()
void traps_init (void)
Referenced by machine_specific_init().
traps_refresh()
void traps_refresh (void)
traps_remove()
int traps_remove (const trap_t * trap)
Referenced by serial_remove_traps(), and tape_traps_deinstall().
traps_resources_init()
int traps_resources_init (void)
Referenced by machine_resources_init().
traps_shutdown()
void traps_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
Variable Documentation
cmdline_options
const cmdline_option_t cmdline_options[] static
Initial value:
=
{
    { "-virtualdev1", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice1", (resource_value_t)1,
      NULL, "Enable general mechanisms for fast disk/tape emulation" },
    { "+virtualdev1", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice1", (resource_value_t)0,
      NULL, "Disable general mechanisms for fast disk/tape emulation" },
    { "-virtualdev2", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice2", (resource_value_t)1,
      NULL, "Enable general mechanisms for fast disk/tape emulation" },
    { "+virtualdev2", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice2", (resource_value_t)0,
      NULL, "Disable general mechanisms for fast disk/tape emulation" },
    { "-virtualdev4", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice4", (resource_value_t)1,
      NULL, "Enable general mechanisms for fast disk/tape emulation" },
    { "+virtualdev4", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice4", (resource_value_t)0,
      NULL, "Disable general mechanisms for fast disk/tape emulation" },
    { "-virtualdev5", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice5", (resource_value_t)1,
      NULL, "Enable general mechanisms for fast disk/tape emulation" },
    { "+virtualdev5", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice5", (resource_value_t)0,
      NULL, "Disable general mechanisms for fast disk/tape emulation" },
    { "-virtualdev6", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice6", (resource_value_t)1,
      NULL, "Enable general mechanisms for fast disk/tape emulation" },
    { "+virtualdev6", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice6", (resource_value_t)0,
      NULL, "Disable general mechanisms for fast disk/tape emulation" },
    { "-virtualdev7", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice7", (resource_value_t)1,
      NULL, "Enable general mechanisms for fast disk/tape emulation" },
    { "+virtualdev7", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice7", (resource_value_t)0,
      NULL, "Disable general mechanisms for fast disk/tape emulation" },
    { "-virtualdev8", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice8", (resource_value_t)1,
      NULL, "Enable general mechanisms for fast disk/tape emulation" },
    { "+virtualdev8", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice8", (resource_value_t)0,
      NULL, "Disable general mechanisms for fast disk/tape emulation" },
    { "-virtualdev9", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice9", (resource_value_t)1,
      NULL, "Enable general mechanisms for fast disk/tape emulation" },
    { "+virtualdev9", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice9", (resource_value_t)0,
      NULL, "Disable general mechanisms for fast disk/tape emulation" },
    { "-virtualdev10", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice10", (resource_value_t)1,
      NULL, "Enable general mechanisms for fast disk/tape emulation" },
    { "+virtualdev10", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice10", (resource_value_t)0,
      NULL, "Disable general mechanisms for fast disk/tape emulation" },
    { "-virtualdev11", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice11", (resource_value_t)1,
      NULL, "Enable general mechanisms for fast disk/tape emulation" },
    { "+virtualdev11", SET_RESOURCE,  0 ,
      NULL, NULL, "VirtualDevice11", (resource_value_t)0,
      NULL, "Disable general mechanisms for fast disk/tape emulation" },
     { NULL, (cmdline_option_type_t)0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
}
Trap-related command-line options.
Referenced by traps_cmdline_options_init().
resources_int
resource_int_t resources_int[] static
Initial value:
= {
    { "VirtualDevice1", 0, RES_EVENT_SAME, NULL,
      &traps_enabled_device[1], set_traps_enabled, (void*)1 },
    { "VirtualDevice2", 0, RES_EVENT_SAME, NULL,
      &traps_enabled_device[2], set_traps_enabled, (void*)2 },
    { "VirtualDevice4", 0, RES_EVENT_SAME, NULL,
      &traps_enabled_device[4], set_traps_enabled, (void*)4 },
    { "VirtualDevice5", 0, RES_EVENT_SAME, NULL,
      &traps_enabled_device[5], set_traps_enabled, (void*)5 },
    { "VirtualDevice6", 0, RES_EVENT_SAME, NULL,
      &traps_enabled_device[6], set_traps_enabled, (void*)6 },
    { "VirtualDevice7", 0, RES_EVENT_SAME, NULL,
      &traps_enabled_device[7], set_traps_enabled, (void*)7 },
    { "VirtualDevice8", 0, RES_EVENT_SAME, NULL,
      &traps_enabled_device[8], set_traps_enabled, (void*)8 },
    { "VirtualDevice9", 0, RES_EVENT_SAME, NULL,
      &traps_enabled_device[9], set_traps_enabled, (void*)9 },
    { "VirtualDevice10", 0, RES_EVENT_SAME, NULL,
      &traps_enabled_device[10], set_traps_enabled, (void*)10 },
    { "VirtualDevice11", 0, RES_EVENT_SAME, NULL,
      &traps_enabled_device[11], set_traps_enabled, (void*)11 },
     { NULL, 0, (resource_event_relevant_t)0, NULL, NULL, NULL, NULL }
}
Referenced by traps_resources_init().
traplist
traplist_t* traplist = NULL static
Referenced by set_traps_status(), traps_add(), traps_checkaddr(), traps_handler(), traps_refresh(), traps_remove(), and traps_shutdown().
traps_enabled
int traps_enabled = 0 static
Trap-related resources.
Flag: Should we avoid installing traps at all?
Referenced by set_traps_status(), traps_add(), traps_refresh(), and traps_remove().
traps_enabled_device
int traps_enabled_device[15]
Referenced by device_uses_serial_traps(), and set_traps_enabled().
traps_log
log_t traps_log = ((log_t)-1) static
Referenced by install_trap(), remove_trap(), traps_init(), and traps_remove().