x128: reSID::Filter Class Reference
reSID::Filter Class Reference
#include <filter.h>
Data Structures
struct model_filter_t
struct opamp_t
Public Member Functions
Filter ()
void enable_filter (bool enable)
void adjust_filter_bias (double dac_bias)
void set_chip_model (chip_model model)
void set_voice_mask (reg4 mask)
void clock (int voice1, int voice2, int voice3)
void clock (cycle_count delta_t, int voice1, int voice2, int voice3)
void reset ()
void writeFC_LO (reg8)
void writeFC_HI (reg8)
void writeRES_FILT (reg8)
void writeMODE_VOL (reg8)
void input (short sample)
short output ()
Filter ()
void enable_filter (bool enable)
void adjust_filter_bias (double dac_bias)
void set_chip_model (chip_model model)
void set_voice_mask (reg4 mask)
void clock (int voice1, int voice2, int voice3)
void clock (cycle_count delta_t, int voice1, int voice2, int voice3)
void reset ()
void writeFC_LO (reg8)
void writeFC_HI (reg8)
void writeRES_FILT (reg8)
void writeMODE_VOL (reg8)
void input (short sample)
short output ()
Protected Member Functions
void set_sum_mix ()
void set_w0 ()
void set_Q ()
int solve_gain (opamp_t *opamp, int n, int vi_t, int &x, model_filter_t &mf)
int solve_integrate_6581 (int dt, int vi_t, int &x, int &vc, model_filter_t &mf)
void set_sum_mix ()
void set_w0 ()
int solve_gain_d (opamp_t *opamp, double n, int vi_t, int &x, model_filter_t &mf)
int solve_integrate_6581 (int dt, int vi_t, int &x, int &vc, model_filter_t &mf)
int solve_integrate_8580 (int dt, int vi_t, int &x, int &vc, model_filter_t &mf)
Protected Attributes
bool enabled
reg12 fc
reg8 res
reg8 filt
reg4 mode
reg4 vol
reg8 voice_mask
reg8 sum
reg8 mix
int Vhp
int Vbp
int Vbp_x
int Vbp_vc
int Vlp
int Vlp_x
int Vlp_vc
int ve
int v3
int v2
int v1
int Vddt_Vw_2
int Vw_bias
int _8_div_Q
int w0
int _1024_div_Q
chip_model sid_model
int n_dac
int nVgt
Static Protected Attributes
static unsigned short vcr_kVg [1<< 16]
static unsigned short vcr_n_Ids_term [1<< 16]
static model_filter_t model_filter [2]
static int n_snake
static int n_param
Friends
class SID
Constructor & Destructor Documentation
Filter() [1/2]
reSID::Filter::Filter ()
Filter() [2/2]
reSID::Filter::Filter ()
Member Function Documentation
adjust_filter_bias() [1/2]
void reSID::Filter::adjust_filter_bias (double dac_bias)
Referenced by reSID::SID::adjust_filter_bias().
adjust_filter_bias() [2/2]
void reSID::Filter::adjust_filter_bias (double dac_bias)
clock() [1/4]
void reSID::Filter::clock (cycle_count delta_t, int voice1, int voice2, int voice3)
clock() [2/4]
void reSID::Filter::clock (cycle_count delta_t, int voice1, int voice2, int voice3)
clock() [3/4]
void reSID::Filter::clock (int voice1, int voice2, int voice3)
Referenced by reSID::SID::clock().
clock() [4/4]
void reSID::Filter::clock (int voice1, int voice2, int voice3)
enable_filter() [1/2]
void reSID::Filter::enable_filter (bool enable)
Referenced by Filter(), and reSID::SID::enable_filter().
enable_filter() [2/2]
void reSID::Filter::enable_filter (bool enable)
input() [1/2]
void reSID::Filter::input (short sample)
Referenced by Filter(), and reSID::SID::input().
input() [2/2]
void reSID::Filter::input (short sample)
output() [1/2]
short reSID::Filter::output ()
Referenced by reSID::SID::clock(), and reSID::SID::debugoutput().
output() [2/2]
short reSID::Filter::output ()
reset() [1/2]
void reSID::Filter::reset ()
Referenced by Filter(), and reSID::SID::reset().
reset() [2/2]
void reSID::Filter::reset ()
set_chip_model() [1/2]
void reSID::Filter::set_chip_model (chip_model model)
Referenced by Filter(), and reSID::SID::set_chip_model().
set_chip_model() [2/2]
void reSID::Filter::set_chip_model (chip_model model)
set_Q()
void reSID::Filter::set_Q () protected
Referenced by reset(), and writeRES_FILT().
set_sum_mix() [1/2]
void reSID::Filter::set_sum_mix () protected
Referenced by enable_filter(), reset(), set_voice_mask(), writeMODE_VOL(), and writeRES_FILT().
set_sum_mix() [2/2]
void reSID::Filter::set_sum_mix () protected
set_voice_mask() [1/2]
void reSID::Filter::set_voice_mask (reg4 mask)
Referenced by Filter(), reSID::SID::set_voice_mask(), and reSID::SID::write_state().
set_voice_mask() [2/2]
void reSID::Filter::set_voice_mask (reg4 mask)
set_w0() [1/2]
void reSID::Filter::set_w0 () protected
Referenced by adjust_filter_bias(), reset(), writeFC_HI(), and writeFC_LO().
set_w0() [2/2]
void reSID::Filter::set_w0 () protected
solve_gain()
int reSID::Filter::solve_gain (opamp_t * opamp, int n, int vi_t, int & x, model_filter_t & mf) protected
Referenced by Filter().
solve_gain_d()
int reSID::Filter::solve_gain_d (opamp_t * opamp, double n, int vi_t, int & x, model_filter_t & mf) protected
solve_integrate_6581() [1/2]
int reSID::Filter::solve_integrate_6581 (int dt, int vi_t, int & x, int & vc, model_filter_t & mf) protected
solve_integrate_6581() [2/2]
int reSID::Filter::solve_integrate_6581 (int dt, int vi_t, int & x, int & vc, model_filter_t & mf) protected
solve_integrate_8580()
int reSID::Filter::solve_integrate_8580 (int dt, int vi_t, int & x, int & vc, model_filter_t & mf) protected
writeFC_HI() [1/2]
void reSID::Filter::writeFC_HI (reg8 fc_hi)
Referenced by reSID::SID::write().
writeFC_HI() [2/2]
void reSID::Filter::writeFC_HI (reg8)
writeFC_LO() [1/2]
void reSID::Filter::writeFC_LO (reg8 fc_lo)
Referenced by reSID::SID::write().
writeFC_LO() [2/2]
void reSID::Filter::writeFC_LO (reg8)
writeMODE_VOL() [1/2]
void reSID::Filter::writeMODE_VOL (reg8 mode_vol)
Referenced by reSID::SID::write().
writeMODE_VOL() [2/2]
void reSID::Filter::writeMODE_VOL (reg8)
writeRES_FILT() [1/2]
void reSID::Filter::writeRES_FILT (reg8 res_filt)
Referenced by reSID::SID::write().
writeRES_FILT() [2/2]
void reSID::Filter::writeRES_FILT (reg8)
Friends And Related Function Documentation
SID
SID friend
Field Documentation
_1024_div_Q
int reSID::Filter::_1024_div_Q protected
Referenced by set_Q().
_8_div_Q
int reSID::Filter::_8_div_Q protected
Referenced by set_Q().
enabled
bool reSID::Filter::enabled protected
Referenced by enable_filter(), and set_sum_mix().
fc
reg12 reSID::Filter::fc protected
Referenced by reSID::SID::read_state(), reset(), set_w0(), writeFC_HI(), and writeFC_LO().
filt
reg8 reSID::Filter::filt protected
Referenced by reSID::SID::read_state(), reset(), set_sum_mix(), and writeRES_FILT().
mix
reg8 reSID::Filter::mix protected
Referenced by set_sum_mix().
mode
reg4 reSID::Filter::mode protected
Referenced by reSID::SID::read_state(), reset(), set_sum_mix(), and writeMODE_VOL().
model_filter
static model_filter_t reSID::Filter::model_filter static protected
Referenced by Filter(), adjust_filter_bias(), and set_w0().
n_dac
int reSID::Filter::n_dac protected
n_param
int reSID::Filter::n_param static protected
n_snake
int reSID::Filter::n_snake static protected
nVgt
int reSID::Filter::nVgt protected
res
reg8 reSID::Filter::res protected
Referenced by reSID::SID::read_state(), reset(), set_Q(), and writeRES_FILT().
sid_model
chip_model reSID::Filter::sid_model protected
Referenced by adjust_filter_bias(), set_chip_model(), and set_w0().
sum
reg8 reSID::Filter::sum protected
Referenced by set_sum_mix().
v1
int reSID::Filter::v1 protected
v2
int reSID::Filter::v2 protected
v3
int reSID::Filter::v3 protected
Vbp
int reSID::Filter::Vbp protected
Referenced by reset(), and set_chip_model().
Vbp_vc
int reSID::Filter::Vbp_vc protected
Referenced by reset(), and set_chip_model().
Vbp_x
int reSID::Filter::Vbp_x protected
Referenced by reset(), and set_chip_model().
vcr_kVg
static unsigned short reSID::Filter::vcr_kVg static protected
Referenced by Filter().
vcr_n_Ids_term
static unsigned short reSID::Filter::vcr_n_Ids_term static protected
Referenced by Filter().
Vddt_Vw_2
int reSID::Filter::Vddt_Vw_2 protected
Referenced by set_w0().
ve
int reSID::Filter::ve protected
Vhp
int reSID::Filter::Vhp protected
Referenced by reset(), and set_chip_model().
Vlp
int reSID::Filter::Vlp protected
Referenced by reset(), and set_chip_model().
Vlp_vc
int reSID::Filter::Vlp_vc protected
Referenced by reset(), and set_chip_model().
Vlp_x
int reSID::Filter::Vlp_x protected
Referenced by reset(), and set_chip_model().
voice_mask
reg8 reSID::Filter::voice_mask protected
Referenced by reSID::SID::read_state(), set_sum_mix(), and set_voice_mask().
vol
reg4 reSID::Filter::vol protected
Referenced by reSID::SID::read_state(), reset(), and writeMODE_VOL().
Vw_bias
int reSID::Filter::Vw_bias protected
Referenced by adjust_filter_bias(), and set_w0().
w0
int reSID::Filter::w0 protected
Referenced by set_w0().
The documentation for this class was generated from the following files:
resid/filter.h
resid/filter8580new.h
resid/filter.cc
resid/filter8580new.cc