vsid: arch/shared/archdep_access.h File Reference
archdep_access.h File Reference
Test access mode of a path - header.
#include "vice.h"
#include "archdep_defs.h"
#include <unistd.h>
Macros
#define ARCHDEP_R_OK R_OK
covers linux, bsd, macos and haiku
#define ARCHDEP_W_OK W_OK
#define ARCHDEP_X_OK X_OK
#define ARCHDEP_F_OK F_OK
#define ARCHDEP_ACCESS_R_OK 4
File is readable.
#define ARCHDEP_ACCESS_W_OK 2
File is writeable.
#define ARCHDEP_ACCESS_X_OK 1
File is executable.
#define ARCHDEP_ACCESS_F_OK 0
File exists.
Functions
int archdep_access (const char *pathname, int mode)
Appropriate headers for access(2)/_access() are included in archdep_access.h.
Detailed Description
Test access mode of a path - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
ARCHDEP_ACCESS_F_OK
#define ARCHDEP_ACCESS_F_OK 0
File exists.
ARCHDEP_ACCESS_R_OK
#define ARCHDEP_ACCESS_R_OK 4
File is readable.
ARCHDEP_ACCESS_W_OK
#define ARCHDEP_ACCESS_W_OK 2
File is writeable.
ARCHDEP_ACCESS_X_OK
#define ARCHDEP_ACCESS_X_OK 1
File is executable.
ARCHDEP_F_OK
#define ARCHDEP_F_OK F_OK
ARCHDEP_R_OK
#define ARCHDEP_R_OK R_OK
covers linux, bsd, macos and haiku
ARCHDEP_W_OK
#define ARCHDEP_W_OK W_OK
ARCHDEP_X_OK
#define ARCHDEP_X_OK X_OK
Function Documentation
archdep_access()
int archdep_access (const char * pathname, int mode)
Appropriate headers for access(2)/_access() are included in archdep_access.h.
Test access of pathname against mode
Parameters
[in] pathname path to file or directory to test
[in] mode access modes bitmask
Returns
0 on success, -1 on failure
Referenced by archdep_mkdir_recursive(), command_directory_get(), findpath(), fliplist_load_list(), resources_load(), resources_save(), zfile_compress(), and zfile_fopen().