x128: drive/iec/wd1770.h File Reference
wd1770.h File Reference
#include "types.h"
Typedefs
typedef struct wd1770_s wd1770_t
Functions
void wd1770d_init (struct diskunit_context_s *drv)
WD1770 external interface.
void wd1770_shutdown (wd1770_t *drv)
int wd1770_attach_image (struct disk_image_s *image, unsigned int unit)
int wd1770_detach_image (struct disk_image_s *image, unsigned int unit)
int wd1770_disk_change (wd1770_t *drv)
void wd1770d_store (struct diskunit_context_s *drv, uint16_t addr, uint8_t byte)
uint8_t wd1770d_read (struct diskunit_context_s *drv, uint16_t addr)
uint8_t wd1770d_peek (struct diskunit_context_s *drv, uint16_t addr)
void wd1770d_dump (struct diskunit_context_s *drv)
void wd1770_reset (wd1770_t *drv)
void wd1770_set_side (wd1770_t *drv, int side)
void wd1770_set_motor (wd1770_t *drv, int on)
int wd1770_snapshot_write_module (wd1770_t *drv, struct snapshot_s *s)
int wd1770_snapshot_read_module (wd1770_t *drv, struct snapshot_s *s)
Typedef Documentation
wd1770_t
typedef struct wd1770_s wd1770_t
Function Documentation
wd1770_attach_image()
int wd1770_attach_image (struct disk_image_s * image, unsigned int unit)
Referenced by iec_drive_image_attach().
wd1770_detach_image()
int wd1770_detach_image (struct disk_image_s * image, unsigned int unit)
Referenced by iec_drive_image_detach().
wd1770_disk_change()
int wd1770_disk_change (wd1770_t * drv)
Referenced by read_ciapa().
wd1770_reset()
void wd1770_reset (wd1770_t * drv)
Referenced by iec_drive_reset().
wd1770_set_motor()
void wd1770_set_motor (wd1770_t * drv, int on)
Referenced by store_ciapa().
wd1770_set_side()
void wd1770_set_side (wd1770_t * drv, int side)
Referenced by store_ciapa().
wd1770_shutdown()
void wd1770_shutdown (wd1770_t * drv)
Referenced by iec_drive_shutdown().
wd1770_snapshot_read_module()
int wd1770_snapshot_read_module (wd1770_t * drv, struct snapshot_s * s)
Referenced by iec_drive_snapshot_read().
wd1770_snapshot_write_module()
int wd1770_snapshot_write_module (wd1770_t * drv, struct snapshot_s * s)
Referenced by iec_drive_snapshot_write().
wd1770d_dump()
void wd1770d_dump (struct diskunit_context_s * drv)
Referenced by drivemem_ioreg_list_get().
wd1770d_init()
void wd1770d_init (diskunit_context_t * drv)
WD1770 external interface.
Todo:
FIXME: whats the deal with the different prefixes?
Functions using disk unit context.
Referenced by iec_drive_init().
wd1770d_peek()
uint8_t wd1770d_peek (struct diskunit_context_s * drv, uint16_t addr)
Referenced by memiec_init().
wd1770d_read()
uint8_t wd1770d_read (struct diskunit_context_s * drv, uint16_t addr)
Referenced by memiec_init().
wd1770d_store()
void wd1770d_store (struct diskunit_context_s * drv, uint16_t addr, uint8_t byte)
Referenced by memiec_init().