x128: arch/gtk3/widgets/settings_drive.c File Reference
settings_drive.c File Reference
Drive settings dialog.
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <gtk/gtk.h>
#include "attach.h"
#include "debug_gtk3.h"
#include "drive-check.h"
#include "drive.h"
#include "drivedoswidget.h"
#include "driveextendpolicywidget.h"
#include "drivefixedsizewidget.h"
#include "driveidlemethodwidget.h"
#include "drivemodelwidget.h"
#include "driveparallelcablewidget.h"
#include "driveramwidget.h"
#include "driverpmwidget.h"
#include "drivesoundwidget.h"
#include "driveunitwidget.h"
#include "drivewidgethelpers.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "settings_drive.h"
Functions
static gboolean has_iec (void)
Determine if the current machine supports IEC.
static void iec_callback (GtkWidget *widget, int unit)
Custom callback for the IEC widget in driveoptions.c.
static void on_model_changed (GtkWidget *widget, gpointer user_data)
Extra event handler for the drive model changes.
static void on_iec_toggled (GtkWidget *widget, gpointer data)
Handler for the 'toggled' event of the IEC checkbox.
static void on_virtual_device_toggled (GtkWidget *widget, gpointer data)
Handler for the 'toggled' event of the Virtual Devices checkbox.
static GtkWidget * create_left_aligned_label (const char *text)
Create left aligned GtkLabel with Pango markup.
static GtkWidget * create_iec_check_button (int unit, void(*callback)(GtkWidget *, int))
Create checkbox to toggle IEC-Device emulation for unit.
static GtkWidget * create_readonly_check_button (int unit, int drive)
Create widget to control read-only mode for unit.
static GtkWidget * create_rtc_check_button (int unit)
Create widget to control Real time clock emulation for unit.
static GtkWidget * create_drive_device_type_widget (int unit)
Create widget to control IEC device type.
static GtkWidget * create_drive_true_emulation_widget (int unit)
Create per-unit True Drive Emulation check button.
static GtkWidget * create_drive_virtual_device_widget (int unit, void(*callback)(GtkWidget *, int))
Create per-unit Virtual Devices check button.
static void create_vic20_layout (GtkWidget *left_grid, int left_row, GtkWidget *right_grid, int right_row, int unit)
Create layout for xvic.
static void create_c64_layout (GtkWidget *left_grid, int left_row, GtkWidget *right_grid, int right_row, int unit)
Create layout for x64, x64sc, xscpu64 and x128.
static void create_plus4_layout (GtkWidget *left_grid, int left_row, GtkWidget *right_grid, int right_row, int unit)
Create layout for xplus4 and c64dtv.
static void create_pet_layout (GtkWidget *left_grid, int left_row, GtkWidget *right_grid, int right_row, int unit)
Create layout for xpet, xcbm5x0 and xcbm2.
static int create_left_layout (GtkWidget *grid, int unit)
Add widgets to left column grid that are shared by all machines.
static int create_right_layout (GtkWidget *grid, int unit)
Add widgets to right column grid that are shared by all machines.
static GtkWidget * create_stack_child_widget (int unit)
Create a composite widget with settings for drive unit.
GtkWidget * settings_drive_widget_create (GtkWidget *parent)
Create main drive settings widget.
Variables
static const vice_gtk3_combo_entry_int_t device_types []
List of (virtual) file system types.
static GtkWidget * drive_model [4]
Drive model widgets.
static GtkWidget * drive_tde [4]
TDE check buttons.
static GtkWidget * drive_virtualdev [4]
Virtual device check buttons.
static GtkWidget * drive_read_only [4][2]
Read-only device check buttons.
static GtkWidget * drive_rtc_save [4]
Real time clock save check buttons.
static GtkWidget * drive_iec_device [4]
IEC device check buttons.
static GtkWidget * drive_extend [4]
Drive extend-policy widgets.
static GtkWidget * drive_idle [4]
Drive idle-mode widgets.
static GtkWidget * drive_parallel [4]
Drive parallel port widgets.
static GtkWidget * drive_rpm [4]
Drive RPM widgets.
static GtkWidget * drive_ram [4]
Drive RAM widgets.
static GtkWidget * drive_dos [4]
Drive DOS widgets.
static GtkWidget * drive_device_type [4]
Drive device type widgets.
static GtkWidget * drive_device_type_label [4]
Drive device type labels.
static GtkWidget * drive_size [4]
Drive fixed-size widgets.
Detailed Description
Drive settings dialog.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_c64_layout()
static void create_c64_layout (GtkWidget * left_grid, int left_row, GtkWidget * right_grid, int right_row, int unit) static
Create layout for x64, x64sc, xscpu64 and x128.
Parameters
[in] left_grid grid of the left column
[in] left_row row in left_grid to start adding widgets
[in] right_grid grid of the right column
[in] right_row row in right_grid to start adding widgets
[in] unit unit number (8-1)
Referenced by create_stack_child_widget().
create_drive_device_type_widget()
static GtkWidget * create_drive_device_type_widget (int unit) static
Create widget to control IEC device type.
Parameters
[in] unit unit number (8-11)
Returns
GtkGrid
Referenced by create_c64_layout(), create_pet_layout(), create_plus4_layout(), and create_vic20_layout().
create_drive_true_emulation_widget()
static GtkWidget * create_drive_true_emulation_widget (int unit) static
Create per-unit True Drive Emulation check button.
Parameters
[in] unit unit number (8-11)
Returns
GtkCheckButton
Referenced by create_left_layout().
create_drive_virtual_device_widget()
static GtkWidget * create_drive_virtual_device_widget (int unit, void(*)(GtkWidget *, int) callback) static
Create per-unit Virtual Devices check button.
Parameters
[in] unit unit number (8-11)
Returns
GtkCheckButton
Referenced by create_left_layout().
create_iec_check_button()
static GtkWidget * create_iec_check_button (int unit, void(*)(GtkWidget *, int) callback) static
Create checkbox to toggle IEC-Device emulation for unit.
Parameters
[in] unit unit number (8-11)
[in] callback function to call on checkbutton toggle events
Returns
GtkCheckButton
Referenced by create_c64_layout(), and create_plus4_layout().
create_left_aligned_label()
static GtkWidget * create_left_aligned_label (const char * text) static
Create left aligned GtkLabel with Pango markup.
Parameters
[in] text label text with Pango markup allowed
Returns
GtkLabel
Referenced by create_c64_layout(), create_left_layout(), create_pet_layout(), create_plus4_layout(), create_right_layout(), and create_vic20_layout().
create_left_layout()
static int create_left_layout (GtkWidget * grid, int unit) static
Add widgets to left column grid that are shared by all machines.
Add widgets that are valid for each machine to the grid making up the left column of the layout.
Parameters
[in] grid left column grid (contains two columns)
[in] unit drive unit number (8-11)
Returns
row index in grid for additional widgets
Referenced by create_stack_child_widget().
create_pet_layout()
static void create_pet_layout (GtkWidget * left_grid, int left_row, GtkWidget * right_grid, int right_row, int unit) static
Create layout for xpet, xcbm5x0 and xcbm2.
Parameters
[in] left_grid grid of the left column
[in] left_row row in left_grid to start adding widgets
[in] right_grid grid of the right column
[in] right_row row in right_grid to start adding widgets
[in] unit unit number (8-1)
Referenced by create_stack_child_widget().
create_plus4_layout()
static void create_plus4_layout (GtkWidget * left_grid, int left_row, GtkWidget * right_grid, int right_row, int unit) static
Create layout for xplus4 and c64dtv.
Parameters
[in] left_grid grid of the left column
[in] left_row row in left_grid to start adding widgets
[in] right_grid grid of the right column
[in] right_row row in right_grid to start adding widgets
[in] unit unit number (8-1)
Referenced by create_stack_child_widget().
create_readonly_check_button()
static GtkWidget * create_readonly_check_button (int unit, int drive) static
Create widget to control read-only mode for unit.
Parameters
[in] unit unit number (8-11)
[in] drive drive number (0-1)
Returns
GtkCheckButton
Referenced by create_left_layout().
create_right_layout()
static int create_right_layout (GtkWidget * grid, int unit) static
Add widgets to right column grid that are shared by all machines.
Add widgets that are valid for each machine to the grid making up the right column of the layout.
Parameters
[in] grid right column grid (contains two columns)
[in] unit drive unit number (8-11)
Returns
row index in grid for additional widgets
Referenced by create_stack_child_widget().
create_rtc_check_button()
static GtkWidget * create_rtc_check_button (int unit) static
Create widget to control Real time clock emulation for unit.
Parameters
[in] unit unit number (8-11)
Returns
GtkCheckButton
Referenced by create_left_layout().
create_stack_child_widget()
static GtkWidget * create_stack_child_widget (int unit) static
Create a composite widget with settings for drive unit.
Parameters
[in] unit unit number
Returns
GtkGrid
Referenced by settings_drive_widget_create().
create_vic20_layout()
static void create_vic20_layout (GtkWidget * left_grid, int left_row, GtkWidget * right_grid, int right_row, int unit) static
Create layout for xvic.
Parameters
[in] left_grid grid of the left column
[in] left_row row in left_grid to start adding widgets
[in] right_grid grid of the right column
[in] right_row row in right_grid to start adding widgets
[in] unit unit number (8-1)
Referenced by create_stack_child_widget().
has_iec()
static gboolean has_iec (void) static
Determine if the current machine supports IEC.
Returns
TRUE if IEC-related resources are available
Referenced by create_left_layout(), drive_cmdline_options_init(), drive_resources_init(), and settings_drive_widget_create().
iec_callback()
static void iec_callback (GtkWidget * widget, int unit) static
Custom callback for the IEC widget in driveoptions.c.
Parameters
[in] widget IEC toggle button
[in] unit unit number (8-11)
Referenced by create_c64_layout(), create_left_layout(), and create_plus4_layout().
on_iec_toggled()
static void on_iec_toggled (GtkWidget * widget, gpointer data) static
Handler for the 'toggled' event of the IEC checkbox.
Triggers the user-provided callback function on toggle.
Parameters
[in] widget IEC checkbox
[in] data unit number
Referenced by create_iec_check_button().
on_model_changed()
static void on_model_changed (GtkWidget * widget, gpointer user_data) static
Extra event handler for the drive model changes.
Parameters
[in] widget drive type radio button
[in] user_data unit number
Referenced by create_left_layout().
on_virtual_device_toggled()
static void on_virtual_device_toggled (GtkWidget * widget, gpointer data) static
Handler for the 'toggled' event of the Virtual Devices checkbox.
Triggers the user-provided callback function on toggle.
Parameters
[in] widget Virtual Devices checkbox
[in] data unit number
Referenced by create_drive_virtual_device_widget().
settings_drive_widget_create()
GtkWidget * settings_drive_widget_create (GtkWidget * parent)
Create main drive settings widget.
Parameters
[in] parent parent widget
Returns
GtkGrid
Todo:
FIXME: xvic doesn't use IEDevice (yet), uses its own iecbus code
Variable Documentation
device_types
const vice_gtk3_combo_entry_int_t device_types[] static
Initial value:
= {
    { "Disk images",             0  },
    { "Host file system",        1   },
    { NULL,                     -1 }
}
List of (virtual) file system types.
Referenced by create_drive_device_type_widget().
drive_device_type
GtkWidget* drive_device_type[4] static
Drive device type widgets.
Referenced by create_c64_layout(), create_pet_layout(), create_plus4_layout(), create_vic20_layout(), iec_callback(), and settings_drive_widget_create().
drive_device_type_label
GtkWidget* drive_device_type_label[4] static
Drive device type labels.
Referenced by create_c64_layout(), create_pet_layout(), create_plus4_layout(), create_vic20_layout(), iec_callback(), and settings_drive_widget_create().
drive_dos
GtkWidget* drive_dos[4] static
Drive DOS widgets.
Referenced by create_c64_layout(), and on_model_changed().
drive_extend
GtkWidget* drive_extend[4] static
Drive extend-policy widgets.
Referenced by create_right_layout(), and on_model_changed().
drive_idle
GtkWidget* drive_idle[4] static
Drive idle-mode widgets.
Referenced by create_right_layout(), and on_model_changed().
drive_iec_device
GtkWidget* drive_iec_device[4] static
IEC device check buttons.
Referenced by create_c64_layout(), and create_plus4_layout().
drive_model
GtkWidget* drive_model[4] static
Drive model widgets.
Referenced by create_left_layout().
drive_parallel
GtkWidget* drive_parallel[4] static
Drive parallel port widgets.
Referenced by create_c64_layout(), and on_model_changed().
drive_ram
GtkWidget* drive_ram[4] static
Drive RAM widgets.
Referenced by create_c64_layout(), create_plus4_layout(), create_vic20_layout(), and on_model_changed().
drive_read_only
GtkWidget* drive_read_only[4][2] static
Read-only device check buttons.
Referenced by create_left_layout(), and on_model_changed().
drive_rpm
GtkWidget* drive_rpm[4] static
Drive RPM widgets.
Referenced by create_right_layout().
drive_rtc_save
GtkWidget* drive_rtc_save[4] static
Real time clock save check buttons.
Referenced by create_left_layout(), and on_model_changed().
drive_size
GtkWidget* drive_size[4] static
Drive fixed-size widgets.
Referenced by create_c64_layout().
drive_tde
GtkWidget* drive_tde[4] static
TDE check buttons.
Referenced by create_left_layout().
drive_virtualdev
GtkWidget* drive_virtualdev[4] static
Virtual device check buttons.
Referenced by create_left_layout().