vsid: drive/drivemem.h File Reference
drivemem.h File Reference
#include "drivetypes.h"
#include "types.h"
Functions
void drivemem_toggle_watchpoints (int flag, void *context)
uint8_t drivemem_bank_read (int bank, uint16_t addr, void *context)
This is the external interface for banked memory access.
uint8_t drivemem_bank_peek (int bank, uint16_t addr, void *context)
used by monitor when sfx off
void drivemem_bank_store (int bank, uint16_t addr, uint8_t value, void *context)
void drivemem_bank_poke (int bank, uint16_t addr, uint8_t value, void *context)
used by monitor when sfx off
void drivemem_init (struct diskunit_context_s *drv)
void drivemem_set_func (struct drivecpud_context_s *cpud, unsigned int start, unsigned int stop, drive_read_func_t *read_func, drive_store_func_t *store_func, drive_peek_func_t *peek_func, uint8_t *base, uint32_t limit)
struct mem_ioreg_list_s * drivemem_ioreg_list_get (void *context)
Variables
uint8_t drive_cpu_last_data
Function Documentation
drivemem_bank_peek()
uint8_t drivemem_bank_peek (int bank, uint16_t addr, void * context)
used by monitor when sfx off
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
drivemem_bank_poke()
void drivemem_bank_poke (int bank, uint16_t addr, uint8_t value, void * context)
used by monitor when sfx off
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
drivemem_bank_read()
uint8_t drivemem_bank_read (int bank, uint16_t addr, void * context)
This is the external interface for banked memory access.
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
drivemem_bank_store()
void drivemem_bank_store (int bank, uint16_t addr, uint8_t value, void * context)
Referenced by drivecpu65c02_setup_context(), drivecpu_setup_context(), and drivemem_bank_poke().
drivemem_init()
void drivemem_init (struct diskunit_context_s * drv)
Referenced by drive_snapshot_read_module(), drivecpu65c02_init(), drivecpu_init(), and set_drive_ram().
drivemem_ioreg_list_get()
struct mem_ioreg_list_s * drivemem_ioreg_list_get (void * context)
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
Todo:
FIXME: register dump function
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
Todo:
FIXME: register dump function
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
Todo:
FIXME: register dump function
< registered area contains no mirrors
< registered area contains no mirrors
Todo:
FIXME: register dump function
< registered area contains no mirrors
< registered area contains no mirrors
Todo:
FIXME: register dump function
< ASCII for HD
< registered area contains no mirrors
< registered area contains no mirrors
< registered area contains no mirrors
< DOS 1 dual floppy drive, 170k/disk
< DOS 2.0 dual floppy drive, 170k/disk
< DOS 2.5 dual floppy drive, 170k/disk
< DOS 2.7 single floppy drive, 1M/disk
< DOS 2.7 dual floppy drive, 0.5M/disk
< DOS 2.7 dual floppy drive, 1M/disk
< DOS 3.0 hard drive
< registered area contains no mirrors
< registered area contains no mirrors
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
drivemem_set_func()
void drivemem_set_func (struct drivecpud_context_s * cpud, unsigned int start, unsigned int stop, drive_read_func_t * read_func, drive_store_func_t * store_func, drive_peek_func_t * peek_func, uint8_t * base, uint32_t limit)
Referenced by drivemem_init(), and memiec_init().
drivemem_toggle_watchpoints()
void drivemem_toggle_watchpoints (int flag, void * context)
Referenced by drivecpu65c02_setup_context(), and drivecpu_setup_context().
Variable Documentation
drive_cpu_last_data
uint8_t drive_cpu_last_data extern