vsid: vdrive/vdrive-dir.h File Reference
vdrive-dir.h File Reference
#include "types.h"
#include "cbmdos.h"
Data Structures
struct vdrive_dir_context_s
Macros
#define SLOT_TYPE_OFFSET 2
#define SLOT_FIRST_TRACK 3
#define SLOT_FIRST_SECTOR 4
#define SLOT_NAME_OFFSET 5
#define SLOT_SIDE_TRACK 21
#define SLOT_SIDE_SECTOR 22
#define SLOT_RECORD_LENGTH 23
for relative files
#define SLOT_REPLACE_TRACK 28
#define SLOT_REPLACE_SECTOR 29
#define SLOT_NR_BLOCKS 30
#define SLOT_GEOS_ITRACK 21
#define SLOT_GEOS_ISECTOR 22
#define SLOT_GEOS_STRUCT 23
#define SLOT_GEOS_TYPE 24
#define SLOT_GEOS_YEAR 25
same on CMD (year to minute)
#define SLOT_GEOS_MONTH 26
#define SLOT_GEOS_DATE 27
#define SLOT_GEOS_HOUR 28
#define SLOT_GEOS_MINUTE 29
#define SLOT_SIZE 32
#define PSLOT_TYPE 2
#define PSLOT_NAME 5
Typedefs
typedef struct vdrive_dir_context_s vdrive_dir_context_t
Functions
void vdrive_dir_init (void)
int vdrive_dir_first_directory (struct vdrive_s *vdrive, struct cbmdos_cmd_parse_plus_s *cmd_parse, struct bufferinfo_s *p)
int vdrive_dir_next_directory (struct vdrive_s *vdrive, struct bufferinfo_s *b)
void vdrive_dir_find_first_slot (struct vdrive_s *vdrive, const uint8_t *name, int length, unsigned int type, vdrive_dir_context_t *dir)
uint8_t * vdrive_dir_find_next_slot (vdrive_dir_context_t *dir)
void vdrive_dir_no_a0_pads (uint8_t *ptr, int l)
int vdrive_dir_filetype (const uint8_t *name, int length)
void vdrive_dir_remove_slot (vdrive_dir_context_t *dir)
void vdrive_dir_create_slot (struct bufferinfo_s *p, uint8_t *realname, int reallength, int filetype)
void vdrive_dir_free_chain (struct vdrive_s *vdrive, int t, int s)
void vdrive_dir_updatetime (struct vdrive_s *vdrive, uint8_t *slot)
uint8_t * vdrive_dir_part_find_next_slot (vdrive_dir_context_t *dir)
int vdrive_dir_part_next_directory (struct vdrive_s *vdrive, struct bufferinfo_s *b)
int vdrive_dir_part_first_directory (struct vdrive_s *vdrive, const uint8_t *name, int length, struct bufferinfo_s *p)
void vdrive_dir_part_find_first_slot (struct vdrive_s *vdrive, const uint8_t *name, int length, unsigned int type, vdrive_dir_context_t *dir)
shamelessly duplicate dir code from above to do the partition listings
Macro Definition Documentation
PSLOT_NAME
#define PSLOT_NAME 5
PSLOT_TYPE
#define PSLOT_TYPE 2
SLOT_FIRST_SECTOR
#define SLOT_FIRST_SECTOR 4
SLOT_FIRST_TRACK
#define SLOT_FIRST_TRACK 3
SLOT_GEOS_DATE
#define SLOT_GEOS_DATE 27
SLOT_GEOS_HOUR
#define SLOT_GEOS_HOUR 28
SLOT_GEOS_ISECTOR
#define SLOT_GEOS_ISECTOR 22
SLOT_GEOS_ITRACK
#define SLOT_GEOS_ITRACK 21
SLOT_GEOS_MINUTE
#define SLOT_GEOS_MINUTE 29
SLOT_GEOS_MONTH
#define SLOT_GEOS_MONTH 26
SLOT_GEOS_STRUCT
#define SLOT_GEOS_STRUCT 23
SLOT_GEOS_TYPE
#define SLOT_GEOS_TYPE 24
SLOT_GEOS_YEAR
#define SLOT_GEOS_YEAR 25
same on CMD (year to minute)
SLOT_NAME_OFFSET
#define SLOT_NAME_OFFSET 5
SLOT_NR_BLOCKS
#define SLOT_NR_BLOCKS 30
SLOT_RECORD_LENGTH
#define SLOT_RECORD_LENGTH 23
for relative files
SLOT_REPLACE_SECTOR
#define SLOT_REPLACE_SECTOR 29
SLOT_REPLACE_TRACK
#define SLOT_REPLACE_TRACK 28
SLOT_SIDE_SECTOR
#define SLOT_SIDE_SECTOR 22
SLOT_SIDE_TRACK
#define SLOT_SIDE_TRACK 21
SLOT_SIZE
#define SLOT_SIZE 32
SLOT_TYPE_OFFSET
#define SLOT_TYPE_OFFSET 2
Typedef Documentation
vdrive_dir_context_t
typedef struct vdrive_dir_context_s vdrive_dir_context_t
Function Documentation
vdrive_dir_create_slot()
void vdrive_dir_create_slot (struct bufferinfo_s * p, uint8_t * realname, int reallength, int filetype)
Referenced by iec_open_write().
vdrive_dir_filetype()
int vdrive_dir_filetype (const uint8_t * name, int length)
< should match FILEIO_TYPE_xxx
< 1581 partition
Referenced by vdrive_command_scratch().
vdrive_dir_find_first_slot()
void vdrive_dir_find_first_slot (struct vdrive_s * vdrive, const uint8_t * name, int length, unsigned int type, vdrive_dir_context_t * dir)
Referenced by iec_open_write(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_lockunlock(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_rmdir(), vdrive_command_scratch(), vdrive_command_switchtraverse(), vdrive_command_validate_worker(), vdrive_dir_first_directory(), vdrive_iec_open(), and vdrive_rel_open_new().
vdrive_dir_find_next_slot()
uint8_t * vdrive_dir_find_next_slot (vdrive_dir_context_t * dir)
< same on CMD (year to minute)
Referenced by iec_open_write(), vdrive_command_chpart(), vdrive_command_copy(), vdrive_command_lockunlock(), vdrive_command_mkdir(), vdrive_command_rename(), vdrive_command_rmdir(), vdrive_command_scratch(), vdrive_command_switchtraverse(), vdrive_command_validate_worker(), vdrive_dir_next_directory(), vdrive_iec_open(), and vdrive_rel_open_new().
vdrive_dir_first_directory()
int vdrive_dir_first_directory (struct vdrive_s * vdrive, struct cbmdos_cmd_parse_plus_s * cmd_parse, struct bufferinfo_s * p)
< should match FILEIO_TYPE_xxx
< 1581 partition
Referenced by iec_open_read_directory(), and iec_read_sequential().
vdrive_dir_free_chain()
void vdrive_dir_free_chain (struct vdrive_s * vdrive, int t, int s)
Todo:
FIXME: This seems to be redundant. AB19981124
Referenced by iec_close_sequential(), vdrive_command_scratch(), vdrive_dir_remove_slot(), and vdrive_rel_scratch().
vdrive_dir_init()
void vdrive_dir_init (void)
Referenced by vdrive_init().
vdrive_dir_next_directory()
int vdrive_dir_next_directory (struct vdrive_s * vdrive, struct bufferinfo_s * b)
< same on CMD (year to minute)
Referenced by iec_read_sequential().
vdrive_dir_no_a0_pads()
void vdrive_dir_no_a0_pads (uint8_t * ptr, int l)
Referenced by vdrive_dir_first_directory(), vdrive_dir_next_directory(), vdrive_dir_part_first_directory(), and vdrive_dir_part_next_directory().
vdrive_dir_part_find_first_slot()
void vdrive_dir_part_find_first_slot (struct vdrive_s * vdrive, const uint8_t * name, int length, unsigned int type, vdrive_dir_context_t * dir)
shamelessly duplicate dir code from above to do the partition listings
Referenced by vdrive_command_renamepart(), and vdrive_dir_part_first_directory().
vdrive_dir_part_find_next_slot()
uint8_t * vdrive_dir_part_find_next_slot (vdrive_dir_context_t * dir)
Referenced by vdrive_command_renamepart(), and vdrive_dir_part_next_directory().
vdrive_dir_part_first_directory()
int vdrive_dir_part_first_directory (struct vdrive_s * vdrive, const uint8_t * name, int length, struct bufferinfo_s * p)
< HD in ASCII for CMDHD
< HD in ASCII for CMDHD
Referenced by iec_open_read_directory().
vdrive_dir_part_next_directory()
int vdrive_dir_part_next_directory (struct vdrive_s * vdrive, struct bufferinfo_s * b)
Referenced by iec_read_sequential(), and vdrive_dir_part_first_directory().
vdrive_dir_remove_slot()
void vdrive_dir_remove_slot (vdrive_dir_context_t * dir)
Referenced by vdrive_command_rmdir(), and vdrive_command_scratch().
vdrive_dir_updatetime()
void vdrive_dir_updatetime (struct vdrive_s * vdrive, uint8_t * slot)
CMDHD's don't like the year > 99, it will screw up the date/time output
< same on CMD (year to minute)
Referenced by iec_close_sequential(), vdrive_command_copy(), and vdrive_command_mkdir().