vsid: Utf32String Class Reference
Utf32String Class Reference
Public Member Functions
Utf32String ()
Utf32String (const char *src)
Utf32String (const uint8_t *src)
Utf32String (const char32_t *src)
Utf32String (const char32_t *src, int len)
Utf32String (int len)
Utf32String (const Utf32String &that)
Utf32String & operator= (const Utf32String &that)
~Utf32String ()
char32_t * get () const
size_t length () const
size_t chars () const
void initFromBuffer ()
const char32_t & operator[] (size_t pos) const
char32_t & operator[] (size_t pos)
Private Attributes
size_t _length
char32_t * _data
Constructor & Destructor Documentation
Utf32String() [1/7]
Utf32String::Utf32String () inline
Utf32String() [2/7]
Utf32String::Utf32String (const char * src) inline explicit
Utf32String() [3/7]
Utf32String::Utf32String (const uint8_t * src) inline explicit
Utf32String() [4/7]
Utf32String::Utf32String (const char32_t * src) inline explicit
Utf32String() [5/7]
Utf32String::Utf32String (const char32_t * src, int len) inline explicit
Utf32String() [6/7]
Utf32String::Utf32String (int len) inline explicit
Utf32String() [7/7]
Utf32String::Utf32String (const Utf32String & that) inline explicit
~Utf32String()
Utf32String::~Utf32String () inline
Member Function Documentation
chars()
size_t Utf32String::chars () const inline
Referenced by DynamicPrompt::updateSearchText().
get()
char32_t * Utf32String::get () const inline
Referenced by DynamicPrompt::DynamicPrompt(), PromptInfo::PromptInfo(), Utf8String::Utf8String(), InputBuffer::completeLine(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), KillRing::kill(), DynamicPrompt::updateSearchPrompt(), and PromptBase::write().
initFromBuffer()
void Utf32String::initFromBuffer () inline
Referenced by DynamicPrompt::DynamicPrompt(), InputBuffer::incrementalHistorySearch(), KillRing::kill(), and DynamicPrompt::updateSearchPrompt().
length()
size_t Utf32String::length () const inline
Referenced by DynamicPrompt::DynamicPrompt(), Utf8String::Utf8String(), InputBuffer::getInputLine(), InputBuffer::incrementalHistorySearch(), and DynamicPrompt::updateSearchPrompt().
operator=()
Utf32String & Utf32String::operator= (const Utf32String & that) inline
operator[]() [1/2]
char32_t & Utf32String::operator[] (size_t pos) inline
operator[]() [2/2]
const char32_t & Utf32String::operator[] (size_t pos) const inline
Field Documentation
_data
char32_t* Utf32String::_data private
Referenced by Utf32String(), ~Utf32String(), get(), initFromBuffer(), operator=(), and operator[]().
_length
size_t Utf32String::_length private
Referenced by Utf32String(), chars(), initFromBuffer(), length(), and operator=().
The documentation for this class was generated from the following file:
lib/linenoise-ng/linenoise.cpp