x128: crt.c File Reference
crt.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "archdep.h"
#include "cartridge.h"
#include "crt.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "types.h"
#include "c64cart.h"
#include "util.h"
Macros
#define DBG(x)
Functions
static void expected_header_error (void)
FILE * crt_open (const char *filename, crt_header_t *header)
int crt_getid (const char *filename)
int crt_read_chip_header (crt_chip_header_t *header, FILE *fd)
int crt_read_chip (uint8_t *rawcart, int offset, crt_chip_header_t *chip, FILE *fd)
int crt_write_chip (uint8_t *data, crt_chip_header_t *header, FILE *fd)
FILE * crt_create_v20 (const char *filename, int type, int subtype, int exrom, int game, const char *name, int machine)
create v2.0 header with machine id
FILE * crt_create_vic20 (const char *filename, int type, int subtype, const char *name)
convenience functions for VIC20 etc
FILE * crt_create_v11 (const char *filename, int type, int subtype, int exrom, int game, const char *name)
create v1.1 header with sub type
FILE * crt_create (const char *filename, int type, int exrom, int game, const char *name)
create classic v1.0 header
Variables
static const char CRT_HEADER_C64 [] = "C64 CARTRIDGE "
static const char CRT_HEADER_C128 [] = "C128 CARTRIDGE "
static const char CRT_HEADER_CBM2 [] = "CBM2 CARTRIDGE "
static const char CRT_HEADER_VIC20 [] = "VIC20 CARTRIDGE "
static const char CRT_HEADER_PLUS4 [] = "PLUS4 CARTRIDGE "
static const char CHIP_HEADER [] = "CHIP"
Macro Definition Documentation
DBG
#define DBG (x)
Todo:
FIXME: for C64CART_IMAGE_LIMIT
Function Documentation
crt_create()
FILE * crt_create (const char * filename, int type, int exrom, int game, const char * name)
create classic v1.0 header
< write mode (binary)
Referenced by c128gmod2_crt_save().
crt_create_v11()
FILE * crt_create_v11 (const char * filename, int type, int subtype, int exrom, int game, const char * name)
create v1.1 header with sub type
< write mode (binary)
crt_create_v20()
FILE * crt_create_v20 (const char * filename, int type, int subtype, int exrom, int game, const char * name, int machine)
create v2.0 header with machine id
create 2.0 header
< write mode (binary)
Referenced by crt_create_vic20().
crt_create_vic20()
FILE * crt_create_vic20 (const char * filename, int type, int subtype, const char * name)
convenience functions for VIC20 etc
crt_getid()
int crt_getid (const char * filename)
< cartconv: last cartridge in list
< from CRT ID to internal ID
crt_open()
FILE * crt_open (const char * filename, crt_header_t * header)
< read mode (binary)
Referenced by crt_getid(), and crt_preview_widget_update().
crt_read_chip()
int crt_read_chip (uint8_t * rawcart, int offset, crt_chip_header_t * chip, FILE * fd)
Referenced by c128comal80_crt_attach(), c128generic_crt_attach(), c128gmod2_crt_attach(), magicdesk128_crt_attach(), partner128_crt_attach(), and warpspeed128_crt_attach().
crt_read_chip_header()
int crt_read_chip_header (crt_chip_header_t * header, FILE * fd)
Referenced by c128comal80_crt_attach(), c128generic_crt_attach(), c128gmod2_crt_attach(), crt_preview_widget_update(), magicdesk128_crt_attach(), partner128_crt_attach(), and warpspeed128_crt_attach().
crt_write_chip()
int crt_write_chip (uint8_t * data, crt_chip_header_t * header, FILE * fd)
Referenced by c128gmod2_crt_save().
expected_header_error()
static void expected_header_error (void) static
Referenced by crt_open().
Variable Documentation
CHIP_HEADER
const char CHIP_HEADER[] = "CHIP" static
Referenced by crt_read_chip_header(), and crt_write_chip().
CRT_HEADER_C128
const char CRT_HEADER_C128[] = "C128 CARTRIDGE " static
Referenced by crt_create_v20(), crt_open(), and expected_header_error().
CRT_HEADER_C64
const char CRT_HEADER_C64[] = "C64 CARTRIDGE " static
Referenced by crt_create(), crt_create_v11(), crt_create_v20(), crt_open(), and expected_header_error().
CRT_HEADER_CBM2
const char CRT_HEADER_CBM2[] = "CBM2 CARTRIDGE " static
Referenced by crt_create_v20(), crt_open(), and expected_header_error().
CRT_HEADER_PLUS4
const char CRT_HEADER_PLUS4[] = "PLUS4 CARTRIDGE " static
Referenced by crt_create_v20(), crt_open(), and expected_header_error().
CRT_HEADER_VIC20
const char CRT_HEADER_VIC20[] = "VIC20 CARTRIDGE " static
Referenced by crt_create_v20(), crt_open(), and expected_header_error().