x128: arch/gtk3/widgets/base/basedialogs.h File Reference
basedialogs.h File Reference
Gtk3 basic dialogs (Info, Yes/No, etc)
#include "vice.h"
#include <gtk/gtk.h>
#include "openfiledialog.h"
#include "savefiledialog.h"
#include "selectdirectorydialog.h"
Enumerations
enum {
VICE_RESPONSE_AUTOSTART = 1 ,
VICE_RESPONSE_AUTOLOAD ,
VICE_RESPONSE_AUTOSTART_INDEX ,
VICE_RESPONSE_AUTOLOAD_INDEX ,
VICE_RESPONSE_CUSTOM_OPEN ,
VICE_RESPONSE_INVALID
}
Custom response IDs for dialogs.
Functions
GtkWidget * vice_gtk3_message_info (GtkWindow *parent, const char *title, const char *fmt,...)
Create 'info' dialog.
GtkWidget * vice_gtk3_message_confirm (GtkWindow *parent, void(*callback)(GtkDialog *, gboolean), const char *title, const char *fmt,...)
Create 'confirm' dialog.
GtkWidget * vice_gtk3_message_error (GtkWindow *parent, const char *title, const char *fmt,...)
Create 'error' dialog.
GtkWidget * vice_gtk3_integer_input_box (void(*callback)(GtkDialog *, int, gboolean), const char *title, const char *message, int old_value, int min, int max)
Create a dialog to enter an integer value.
Detailed Description
Gtk3 basic dialogs (Info, Yes/No, etc)
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
anonymous enum
anonymous enum
Custom response IDs for dialogs.
Enumerator
VICE_RESPONSE_AUTOSTART
trigger autostart
VICE_RESPONSE_AUTOLOAD
trigger autoload
VICE_RESPONSE_AUTOSTART_INDEX
trigger autostart with index (inside image)
VICE_RESPONSE_AUTOLOAD_INDEX
trigger autoload with index (inside image)
VICE_RESPONSE_CUSTOM_OPEN
custom open event
VICE_RESPONSE_INVALID
not a valid event, drop it
Function Documentation
vice_gtk3_integer_input_box()
GtkWidget * vice_gtk3_integer_input_box (void(*)(GtkDialog *, int, gboolean) callback, const char * title, const char * message, int old_value, int min, int max)
Create a dialog to enter an integer value.
Parameters
[in] callback callback function to accept result
[in] title dialog title
[in] message dialog body text
[in] old_value current value of whatever needs to be changed
[in] min minimal valid value
[in] max maximum valid value
Returns
dialog
!
Todo:
check input while entering (marking any invalid value red or so)
Referenced by speed_cpu_custom_action(), and speed_fps_custom_action().
vice_gtk3_message_confirm()
GtkWidget * vice_gtk3_message_confirm (GtkWindow * parent, void(*)(GtkDialog *, gboolean) callback, const char * title, const char * fmt, ...)
Create 'confirm' dialog.
Parameters
[in] parent parent window (can be NULL)
[in] callback callback function to accept the dialog's result
[in] title dialog title
[in] fmt message format string and arguments
Returns
dialog
Referenced by cart_detach_action(), quit_action(), settings_default_action(), show_clear_all_confirm_dialog(), and vsid_playlist_clear().
vice_gtk3_message_error()
GtkWidget * vice_gtk3_message_error (GtkWindow * parent, const char * title, const char * fmt, ...)
Create 'error' dialog.
Create modal error dialog with either parent as parentm or if parent is NULL the active emu window as parent or if that one isn't created yet, a temporary empty (non-visible) parent window.
Parameters
[in] parent parent window/dialog
[in] title dialog title
[in] fmt message format string and arguments
Returns
dialog
Referenced by create_disk_image(), create_tape_image(), do_attach(), do_autostart(), eeprom_filename_callback(), help_manual_action(), on_dww_toggled(), on_enable_toggled(), on_flush_clicked(), on_load_romset_callback(), on_response(), on_romset_save_callback(), on_save_clicked(), on_save_response(), on_save_video_filename(), on_settings_save_to_filename(), playlist_save_dialog_callback(), save_as_callback(), save_filename_callback(), save_screenshot_error_impl(), settings_load_action(), settings_load_filename_callback(), settings_save_action(), ui_error_impl(), ui_vsid_window_load_psid(), update_resource(), and vsid_playlist_append_file().
vice_gtk3_message_info()
GtkWidget * vice_gtk3_message_info (GtkWindow * parent, const char * title, const char * fmt, ...)
Create 'info' dialog.
Parameters
[in] parent parent window (can be NULL)
[in] title dialog title
[in] fmt message format string and arguments
Returns
dialog
Referenced by on_save_clicked(), save_as_callback(), save_filename_callback(), and ui_message_impl().