x128: vicii/viciidtv-snapshot.c File Reference
viciidtv-snapshot.c File Reference
#include "vice.h"
#include <stdio.h>
#include "alarm.h"
#include "interrupt.h"
#include "log.h"
#include "mem.h"
#include "raster-snapshot.h"
#include "raster-sprite-status.h"
#include "raster-sprite.h"
#include "snapshot.h"
#include "types.h"
#include "vicii-irq.h"
#include "vicii-snapshot.h"
#include "vicii-sprites.h"
#include "vicii.h"
#include "viciitypes.h"
#include "vicii-mem.h"
Macros
#define SNAP_MAJOR 1
#define SNAP_MINOR 2
Functions
void vicii_snapshot_prepare (void)
int vicii_snapshot_write_module (snapshot_t *s)
int vicii_snapshot_read_module (snapshot_t *s)
Variables
static char snap_module_name [] = "VIC-II"
Macro Definition Documentation
SNAP_MAJOR
#define SNAP_MAJOR 1
SNAP_MINOR
#define SNAP_MINOR 2
Function Documentation
vicii_snapshot_prepare()
void vicii_snapshot_prepare (void)
Referenced by c128_snapshot_read().
vicii_snapshot_read_module()
int vicii_snapshot_read_module (snapshot_t * s)
Todo:
FIXME: initialize changes?
Todo:
FIXME: Recalculate alarms and derived values.
Todo:
FIXME: ‘vicii.ycounter_reset_checked’?
Todo:
FIXME: ‘vicii.force_display_state’?
Referenced by c128_snapshot_read().
vicii_snapshot_write_module()
int vicii_snapshot_write_module (snapshot_t * s)
Todo:
FIXME: Dispatch all events?
Referenced by c128_snapshot_write().
Variable Documentation
snap_module_name
char snap_module_name[] = "VIC-II" static
Referenced by vicii_snapshot_read_module(), and vicii_snapshot_write_module().