vsid: c64/c64fastiec.c File Reference
c64fastiec.c File Reference
#include "vice.h"
#include "c64fastiec.h"
#include "c64.h"
#include "cia.h"
#include "via.h"
#include "drive.h"
#include "drivetypes.h"
#include "iecdrive.h"
#include "maincpu.h"
#include "types.h"
#include "drive/iec/cmdhd.h"
Functions
int set_burst_mod (int mode, void *param)
void c64fastiec_init (void)
void c64fastiec_fast_cpu_write (uint8_t data)
void iec_fast_drive_write (uint8_t data, unsigned int dnr)
void iec_fast_drive_direction (int direction, unsigned int dnr)
Variables
static int fast_drive_direction [4]
Fast IEC for C64 with burst mod.
int burst_mod
Function Documentation
c64fastiec_fast_cpu_write()
void c64fastiec_fast_cpu_write (uint8_t data)
< ASCII for HD
Referenced by store_sdr().
c64fastiec_init()
void c64fastiec_init (void)
Referenced by machine_specific_init().
iec_fast_drive_direction()
void iec_fast_drive_direction (int direction, unsigned int dnr)
Referenced by store_ciapb(), store_pra(), and store_prb10().
iec_fast_drive_write()
void iec_fast_drive_write (uint8_t data, unsigned int dnr)
Referenced by store_sdr(), store_sr(), and store_sr10().
set_burst_mod()
int set_burst_mod (int mode, void * param)
Variable Documentation
burst_mod
int burst_mod
Referenced by iec_fast_drive_write(), read_ciaicr(), read_sdr(), set_burst_mod(), and store_sdr().
fast_drive_direction
int fast_drive_direction[4] static
Fast IEC for C64 with burst mod.
Referenced by c64fastiec_init(), iec_fast_drive_direction(), and iec_fast_drive_write().