x128: arch/shared/archdep_xdg.h File Reference
archdep_xdg.h File Reference
XDG base dir specification support - header.
Functions
char * archdep_xdg_cache_home (void)
Get XDG_CACHE_HOME.
char * archdep_xdg_config_home (void)
Get XDG_CONFIG_HOME.
char * archdep_xdg_data_home (void)
Get XDG_DATA_HOME.
char * archdep_xdg_state_home (void)
Get XDG_STATE_HOME.
Detailed Description
XDG base dir specification support - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
archdep_xdg_cache_home()
char * archdep_xdg_cache_home (void)
Get XDG_CACHE_HOME.
Either returns the value of $XDG_CACHE_HOME or the default $HOME/.cache
Returns
heap-allocated string, free with lib_free()
Referenced by archdep_init(), and archdep_user_cache_path().
archdep_xdg_config_home()
char * archdep_xdg_config_home (void)
Get XDG_CONFIG_HOME.
Either returns the value of $XDG_CONFIG_HOME or the default $HOME/.config
Returns
heap-allocated string, free with lib_free()
Referenced by archdep_init(), and archdep_user_config_path().
archdep_xdg_data_home()
char * archdep_xdg_data_home (void)
Get XDG_DATA_HOME.
Either returns the value of $XDG_DATA_HOME or the default $HOME/.local/share
Returns
heap-allocated string, free with lib_free()
Referenced by archdep_default_sysfile_pathlist(), and archdep_init().
archdep_xdg_state_home()
char * archdep_xdg_state_home (void)
Get XDG_STATE_HOME.
Either returns the value of $XDG_STATE_HOME or the default $HOME/.local/state
Returns
heap-allocated string, free with lib_free()
Referenced by archdep_init(), and archdep_user_state_path().