vsid: arch/gtk3/widgets/drivedoswidget.h File Reference
drivedoswidget.h File Reference
Drive DOS expansions widget - header.
#include <gtk/gtk.h>
Functions
GtkWidget * drive_dos_widget_create_combo (int unit)
Create combo box to select drive DOS expansion.
void drive_dos_widget_sync_combo (GtkWidget *widget)
Synchronize widget with the current machine configuration.
Detailed Description
Drive DOS expansions widget - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
drive_dos_widget_create_combo()
GtkWidget * drive_dos_widget_create_combo (int unit)
Create combo box to select drive DOS expansion.
Create combo box that allows selecting a DOS expansion that is valid for the current unit's drive type.
Contains the following GObject keys:
UnitNumber: Drive unit number (8-11)
ModelDriveType: Drive type used for (re)construction of the model of the combo box, to avoid rebuilding the model on every sync() call
ChangedHandlerID: ID of the 'changed' event handler, used to block the changed event when calling sync()
Parameters
[in] unit drive unit number (8-11)
Returns
GtkComboBox
Referenced by create_c64_layout().
drive_dos_widget_sync_combo()
void drive_dos_widget_sync_combo (GtkWidget * widget)
Synchronize widget with the current machine configuration.
Update the available expansions in the combo box, disable any invalid DOS expansions for the current drive model.
Parameters
[in] widget drive DOS expansion widget
Referenced by drive_dos_widget_create_combo(), and on_model_changed().