vsid: serial/fsdrive.h File Reference
fsdrive.h File Reference
#include "types.h"
Macros
#define SERIAL_NAMELENGTH 255
Functions
void fsdrive_init (void)
void fsdrive_reset (void)
void fsdrive_open (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void fsdrive_close (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void fsdrive_listentalk (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void fsdrive_unlisten (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void fsdrive_untalk (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void fsdrive_write (unsigned int device, uint8_t secondary, uint8_t data, void(*st_func)(uint8_t))
uint8_t fsdrive_read (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
Variables
uint8_t SerialBuffer [255+1]
int SerialPtr
Macro Definition Documentation
SERIAL_NAMELENGTH
#define SERIAL_NAMELENGTH 255
Function Documentation
fsdrive_close()
void fsdrive_close (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_close().
fsdrive_init()
void fsdrive_init (void)
Referenced by serial_iec_bus_init().
fsdrive_listentalk()
void fsdrive_listentalk (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_listen(), and serial_iec_bus_talk().
fsdrive_open()
void fsdrive_open (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_open().
fsdrive_read()
uint8_t fsdrive_read (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_read().
fsdrive_reset()
void fsdrive_reset (void)
Referenced by serial_iec_bus_reset().
fsdrive_unlisten()
void fsdrive_unlisten (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_unlisten().
fsdrive_untalk()
void fsdrive_untalk (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_untalk().
fsdrive_write()
void fsdrive_write (unsigned int device, uint8_t secondary, uint8_t data, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_write().
Variable Documentation
SerialBuffer
uint8_t SerialBuffer[255+1] extern
Referenced by fsdrive_snapshot_read_module(), fsdrive_snapshot_write_module(), fsdrive_write(), and serialcommand().
SerialPtr
int SerialPtr extern
Referenced by fsdrive_snapshot_read_module(), fsdrive_snapshot_write_module(), fsdrive_write(), and serialcommand().