x128: EscapeSequenceProcessing Namespace Reference
EscapeSequenceProcessing Namespace Reference
Data Structures
struct CharacterDispatch
Typedefs
typedef char32_t(* CharacterDispatchRoutine) (char32_t)
Functions
static char32_t doDispatch (char32_t c, CharacterDispatch &dispatchTable)
static char32_t normalKeyRoutine (char32_t c)
static char32_t upArrowKeyRoutine (char32_t)
static char32_t downArrowKeyRoutine (char32_t)
static char32_t rightArrowKeyRoutine (char32_t)
static char32_t leftArrowKeyRoutine (char32_t)
static char32_t homeKeyRoutine (char32_t)
static char32_t endKeyRoutine (char32_t)
static char32_t pageUpKeyRoutine (char32_t)
static char32_t pageDownKeyRoutine (char32_t)
static char32_t deleteCharRoutine (char32_t)
static char32_t deleteKeyRoutine (char32_t)
static char32_t ctrlUpArrowKeyRoutine (char32_t)
static char32_t ctrlDownArrowKeyRoutine (char32_t)
static char32_t ctrlRightArrowKeyRoutine (char32_t)
static char32_t ctrlLeftArrowKeyRoutine (char32_t)
static char32_t escFailureRoutine (char32_t)
static char32_t escLeftBracket1Semicolon3Routine (char32_t c)
static char32_t escLeftBracket1Semicolon5Routine (char32_t c)
static char32_t escLeftBracket1SemicolonRoutine (char32_t c)
static char32_t escLeftBracket0Routine (char32_t c)
static char32_t escLeftBracket1Routine (char32_t c)
static char32_t escLeftBracket2Routine (char32_t c)
static char32_t escLeftBracket3Routine (char32_t c)
static char32_t escLeftBracket4Routine (char32_t c)
static char32_t escLeftBracket5Routine (char32_t c)
static char32_t escLeftBracket6Routine (char32_t c)
static char32_t escLeftBracket7Routine (char32_t c)
static char32_t escLeftBracket8Routine (char32_t c)
static char32_t escLeftBracket9Routine (char32_t c)
static char32_t escLeftBracketRoutine (char32_t c)
static char32_t escORoutine (char32_t c)
static char32_t setMetaRoutine (char32_t c)
static char32_t escRoutine (char32_t c)
Variables
static char32_t thisKeyMetaCtrl
static CharacterDispatchRoutine escLeftBracket1Semicolon3or5Routines []
static CharacterDispatch escLeftBracket1Semicolon3or5Dispatch
static CharacterDispatchRoutine escLeftBracket1SemicolonRoutines []
static CharacterDispatch escLeftBracket1SemicolonDispatch
static CharacterDispatchRoutine escLeftBracket1Routines []
static CharacterDispatch escLeftBracket1Dispatch
static CharacterDispatchRoutine escLeftBracket3Routines []
static CharacterDispatch escLeftBracket3Dispatch
static CharacterDispatchRoutine escLeftBracket4Routines []
static CharacterDispatch escLeftBracket4Dispatch
static CharacterDispatchRoutine escLeftBracket5Routines []
static CharacterDispatch escLeftBracket5Dispatch
static CharacterDispatchRoutine escLeftBracket6Routines []
static CharacterDispatch escLeftBracket6Dispatch
static CharacterDispatchRoutine escLeftBracket7Routines []
static CharacterDispatch escLeftBracket7Dispatch
static CharacterDispatchRoutine escLeftBracket8Routines []
static CharacterDispatch escLeftBracket8Dispatch
static CharacterDispatchRoutine escLeftBracketRoutines []
static CharacterDispatch escLeftBracketDispatch
static CharacterDispatchRoutine escORoutines []
static CharacterDispatch escODispatch = {10, "ABCDHFabcd", escORoutines}
static CharacterDispatchRoutine escRoutines []
static CharacterDispatch escDispatch = {2, "[O", escRoutines}
static CharacterDispatchRoutine initialRoutines []
static CharacterDispatch initialDispatch = {2, "\x1B\x7F", initialRoutines}
Typedef Documentation
CharacterDispatchRoutine
typedef char32_t(* EscapeSequenceProcessing::CharacterDispatchRoutine) (char32_t)
Function Documentation
ctrlDownArrowKeyRoutine()
static char32_t EscapeSequenceProcessing::ctrlDownArrowKeyRoutine (char32_t) static
ctrlLeftArrowKeyRoutine()
static char32_t EscapeSequenceProcessing::ctrlLeftArrowKeyRoutine (char32_t) static
ctrlRightArrowKeyRoutine()
static char32_t EscapeSequenceProcessing::ctrlRightArrowKeyRoutine (char32_t) static
ctrlUpArrowKeyRoutine()
static char32_t EscapeSequenceProcessing::ctrlUpArrowKeyRoutine (char32_t) static
deleteCharRoutine()
static char32_t EscapeSequenceProcessing::deleteCharRoutine (char32_t) static
deleteKeyRoutine()
static char32_t EscapeSequenceProcessing::deleteKeyRoutine (char32_t) static
doDispatch()
static char32_t EscapeSequenceProcessing::doDispatch (char32_t c, CharacterDispatch & dispatchTable) static
Referenced by escLeftBracket1Routine(), escLeftBracket1Semicolon3Routine(), escLeftBracket1Semicolon5Routine(), escLeftBracket1SemicolonRoutine(), escLeftBracket3Routine(), escLeftBracket4Routine(), escLeftBracket5Routine(), escLeftBracket6Routine(), escLeftBracket7Routine(), escLeftBracket8Routine(), escLeftBracketRoutine(), escORoutine(), escRoutine(), linenoiseReadChar(), and setMetaRoutine().
downArrowKeyRoutine()
static char32_t EscapeSequenceProcessing::downArrowKeyRoutine (char32_t) static
endKeyRoutine()
static char32_t EscapeSequenceProcessing::endKeyRoutine (char32_t) static
escFailureRoutine()
static char32_t EscapeSequenceProcessing::escFailureRoutine (char32_t) static
Referenced by escLeftBracket0Routine(), escLeftBracket2Routine(), and escLeftBracket9Routine().
escLeftBracket0Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket0Routine (char32_t c) static
escLeftBracket1Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket1Routine (char32_t c) static
escLeftBracket1Semicolon3Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket1Semicolon3Routine (char32_t c) static
escLeftBracket1Semicolon5Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket1Semicolon5Routine (char32_t c) static
escLeftBracket1SemicolonRoutine()
static char32_t EscapeSequenceProcessing::escLeftBracket1SemicolonRoutine (char32_t c) static
escLeftBracket2Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket2Routine (char32_t c) static
escLeftBracket3Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket3Routine (char32_t c) static
escLeftBracket4Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket4Routine (char32_t c) static
escLeftBracket5Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket5Routine (char32_t c) static
escLeftBracket6Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket6Routine (char32_t c) static
escLeftBracket7Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket7Routine (char32_t c) static
escLeftBracket8Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket8Routine (char32_t c) static
escLeftBracket9Routine()
static char32_t EscapeSequenceProcessing::escLeftBracket9Routine (char32_t c) static
escLeftBracketRoutine()
static char32_t EscapeSequenceProcessing::escLeftBracketRoutine (char32_t c) static
escORoutine()
static char32_t EscapeSequenceProcessing::escORoutine (char32_t c) static
escRoutine()
static char32_t EscapeSequenceProcessing::escRoutine (char32_t c) static
homeKeyRoutine()
static char32_t EscapeSequenceProcessing::homeKeyRoutine (char32_t) static
leftArrowKeyRoutine()
static char32_t EscapeSequenceProcessing::leftArrowKeyRoutine (char32_t) static
normalKeyRoutine()
static char32_t EscapeSequenceProcessing::normalKeyRoutine (char32_t c) static
pageDownKeyRoutine()
static char32_t EscapeSequenceProcessing::pageDownKeyRoutine (char32_t) static
pageUpKeyRoutine()
static char32_t EscapeSequenceProcessing::pageUpKeyRoutine (char32_t) static
rightArrowKeyRoutine()
static char32_t EscapeSequenceProcessing::rightArrowKeyRoutine (char32_t) static
setMetaRoutine()
static char32_t EscapeSequenceProcessing::setMetaRoutine (char32_t c) static
upArrowKeyRoutine()
static char32_t EscapeSequenceProcessing::upArrowKeyRoutine (char32_t) static
Variable Documentation
escDispatch
CharacterDispatch EscapeSequenceProcessing::escDispatch = {2, "[O", escRoutines} static
Referenced by escRoutine(), and setMetaRoutine().
escLeftBracket1Dispatch
CharacterDispatch EscapeSequenceProcessing::escLeftBracket1Dispatch static
Initial value:
= {2, "~;",
                                                    escLeftBracket1Routines}
Referenced by escLeftBracket1Routine().
escLeftBracket1Routines
CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket1Routines[] static
Initial value:
= {
    homeKeyRoutine, escLeftBracket1SemicolonRoutine, escFailureRoutine}
escLeftBracket1Semicolon3or5Dispatch
CharacterDispatch EscapeSequenceProcessing::escLeftBracket1Semicolon3or5Dispatch static
Initial value:
= {
    4, "ABCD", escLeftBracket1Semicolon3or5Routines}
Referenced by escLeftBracket1Semicolon3Routine(), and escLeftBracket1Semicolon5Routine().
escLeftBracket1Semicolon3or5Routines
CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket1Semicolon3or5Routines[] static
Initial value:
= {
    upArrowKeyRoutine, downArrowKeyRoutine, rightArrowKeyRoutine,
    leftArrowKeyRoutine, escFailureRoutine}
escLeftBracket1SemicolonDispatch
CharacterDispatch EscapeSequenceProcessing::escLeftBracket1SemicolonDispatch static
Initial value:
= {
    2, "35", escLeftBracket1SemicolonRoutines}
Referenced by escLeftBracket1SemicolonRoutine().
escLeftBracket1SemicolonRoutines
CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket1SemicolonRoutines[] static
Initial value:
= {
    escLeftBracket1Semicolon3Routine, escLeftBracket1Semicolon5Routine,
    escFailureRoutine}
escLeftBracket3Dispatch
CharacterDispatch EscapeSequenceProcessing::escLeftBracket3Dispatch static
Initial value:
= {1, "~",
                                                    escLeftBracket3Routines}
Referenced by escLeftBracket3Routine().
escLeftBracket3Routines
CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket3Routines[] static
Initial value:
= {deleteKeyRoutine,
                                                             escFailureRoutine}
escLeftBracket4Dispatch
CharacterDispatch EscapeSequenceProcessing::escLeftBracket4Dispatch static
Initial value:
= {1, "~",
                                                    escLeftBracket4Routines}
Referenced by escLeftBracket4Routine().
escLeftBracket4Routines
CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket4Routines[] static
Initial value:
= {endKeyRoutine,
                                                             escFailureRoutine}
escLeftBracket5Dispatch
CharacterDispatch EscapeSequenceProcessing::escLeftBracket5Dispatch static
Initial value:
= {1, "~",
                                                    escLeftBracket5Routines}
Referenced by escLeftBracket5Routine().
escLeftBracket5Routines
CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket5Routines[] static
Initial value:
= {pageUpKeyRoutine,
                                                             escFailureRoutine}
escLeftBracket6Dispatch
CharacterDispatch EscapeSequenceProcessing::escLeftBracket6Dispatch static
Initial value:
= {1, "~",
                                                    escLeftBracket6Routines}
Referenced by escLeftBracket6Routine().
escLeftBracket6Routines
CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket6Routines[] static
Initial value:
= {pageDownKeyRoutine,
                                                             escFailureRoutine}
escLeftBracket7Dispatch
CharacterDispatch EscapeSequenceProcessing::escLeftBracket7Dispatch static
Initial value:
= {1, "~",
                                                    escLeftBracket7Routines}
Referenced by escLeftBracket7Routine().
escLeftBracket7Routines
CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket7Routines[] static
Initial value:
= {homeKeyRoutine,
                                                             escFailureRoutine}
escLeftBracket8Dispatch
CharacterDispatch EscapeSequenceProcessing::escLeftBracket8Dispatch static
Initial value:
= {1, "~",
                                                    escLeftBracket8Routines}
Referenced by escLeftBracket8Routine().
escLeftBracket8Routines
CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracket8Routines[] static
Initial value:
= {endKeyRoutine,
                                                             escFailureRoutine}
escLeftBracketDispatch
CharacterDispatch EscapeSequenceProcessing::escLeftBracketDispatch static
Initial value:
= {16, "ABCDHF0123456789",
                                                   escLeftBracketRoutines}
Referenced by escLeftBracketRoutine().
escLeftBracketRoutines
CharacterDispatchRoutine EscapeSequenceProcessing::escLeftBracketRoutines[] static
Initial value:
= {
    upArrowKeyRoutine,      downArrowKeyRoutine,    rightArrowKeyRoutine,
    leftArrowKeyRoutine,    homeKeyRoutine,         endKeyRoutine,
    escLeftBracket0Routine, escLeftBracket1Routine, escLeftBracket2Routine,
    escLeftBracket3Routine, escLeftBracket4Routine, escLeftBracket5Routine,
    escLeftBracket6Routine, escLeftBracket7Routine, escLeftBracket8Routine,
    escLeftBracket9Routine, escFailureRoutine}
escODispatch
CharacterDispatch EscapeSequenceProcessing::escODispatch = {10, "ABCDHFabcd", escORoutines} static
Referenced by escORoutine().
escORoutines
CharacterDispatchRoutine EscapeSequenceProcessing::escORoutines[] static
Initial value:
= {
    upArrowKeyRoutine,       downArrowKeyRoutine,     rightArrowKeyRoutine,
    leftArrowKeyRoutine,     homeKeyRoutine,          endKeyRoutine,
    ctrlUpArrowKeyRoutine,   ctrlDownArrowKeyRoutine, ctrlRightArrowKeyRoutine,
    ctrlLeftArrowKeyRoutine, escFailureRoutine}
escRoutines
CharacterDispatchRoutine EscapeSequenceProcessing::escRoutines[] static
Initial value:
= {escLeftBracketRoutine,
                                                 escORoutine, setMetaRoutine}
initialDispatch
CharacterDispatch EscapeSequenceProcessing::initialDispatch = {2, "\x1B\x7F", initialRoutines} static
Referenced by linenoiseReadChar(), and setMetaRoutine().
initialRoutines
CharacterDispatchRoutine EscapeSequenceProcessing::initialRoutines[] static
Initial value:
= {
    escRoutine, deleteCharRoutine, normalKeyRoutine}
thisKeyMetaCtrl
char32_t EscapeSequenceProcessing::thisKeyMetaCtrl static
Initial value:
=
    0
Referenced by ctrlDownArrowKeyRoutine(), ctrlLeftArrowKeyRoutine(), ctrlRightArrowKeyRoutine(), ctrlUpArrowKeyRoutine(), deleteCharRoutine(), deleteKeyRoutine(), downArrowKeyRoutine(), endKeyRoutine(), escLeftBracket1Semicolon3Routine(), escLeftBracket1Semicolon5Routine(), homeKeyRoutine(), leftArrowKeyRoutine(), linenoiseReadChar(), normalKeyRoutine(), pageDownKeyRoutine(), pageUpKeyRoutine(), rightArrowKeyRoutine(), setMetaRoutine(), and upArrowKeyRoutine().