x128: drive/tcbm/tpid.h File Reference
tpid.h File Reference
#include "types.h"
Functions
void tpid_setup_context (struct diskunit_context_s *ctxptr)
void tpid_init (struct diskunit_context_s *ctxptr)
void tpid_store (struct diskunit_context_s *ctxptr, uint16_t addr, uint8_t byte)
uint8_t tpid_read (struct diskunit_context_s *ctxptr, uint16_t addr)
uint8_t tpid_peek (struct diskunit_context_s *ctxptr, uint16_t addr)
int tpid_dump (diskunit_context_t *ctxptr, uint16_t addr)
Function Documentation
tpid_dump()
int tpid_dump (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by drivemem_ioreg_list_get().
tpid_init()
void tpid_init (struct diskunit_context_s * ctxptr)
Referenced by tcbm_drive_init().
tpid_peek()
uint8_t tpid_peek (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by mem1551_init().
tpid_read()
uint8_t tpid_read (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by mem1551_init().
tpid_setup_context()
void tpid_setup_context (struct diskunit_context_s * ctxptr)
Referenced by tcbm_drive_setup_context().
tpid_store()
void tpid_store (struct diskunit_context_s * ctxptr, uint16_t addr, uint8_t byte)
Referenced by mem1551_init().