x128: c128/c128.c File Reference
c128.c File Reference
C128 basic stuff.
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include "attach.h"
#include "autostart.h"
#include "bbrtc.h"
#include "c128-cmdline-options.h"
#include "c128-resources.h"
#include "c128-snapshot.h"
#include "c128.h"
#include "c128cart.h"
#include "c128fastiec.h"
#include "c128mem.h"
#include "c128memrom.h"
#include "c128mmu.h"
#include "c128ui.h"
#include "c64-midi.h"
#include "c64cartsystem.h"
#include "c64_256k.h"
#include "c64cia.h"
#include "c64iec.h"
#include "c64keyboard.h"
#include "c64memrom.h"
#include "c64parallel.h"
#include "c64rsuser.h"
#include "cardkey.h"
#include "cartridge.h"
#include "cia.h"
#include "clockport-mp3at64.h"
#include "datasette.h"
#include "datasette-sound.h"
#include "debug.h"
#include "diskimage.h"
#include "drive-cmdline-options.h"
#include "drive-resources.h"
#include "drive-sound.h"
#include "drive.h"
#include "export.h"
#include "fliplist.h"
#include "fmopl.h"
#include "fsdevice.h"
#include "functionrom.h"
#include "gfxoutput.h"
#include "imagecontents.h"
#include "inception.h"
#include "init.h"
#include "joyport.h"
#include "joyport_io_sim.h"
#include "joystick.h"
#include "kbdbuf.h"
#include "keyboard.h"
#include "log.h"
#include "resources.h"
#include "machine-drive.h"
#include "machine-printer.h"
#include "machine-video.h"
#include "machine.h"
#include "maincpu.h"
#include "mem.h"
#include "monitor.h"
#include "multijoy.h"
#include "network.h"
#include "ninja_snespad.h"
#include "paperclip64.h"
#include "paperclip64e.h"
#include "paperclip64sc.h"
#include "paperclip2.h"
#include "parallel.h"
#include "plus60k.h"
#include "plus256k.h"
#include "printer.h"
#include "protopad.h"
#include "rs232drv.h"
#include "rsuser.h"
#include "sampler.h"
#include "sampler2bit.h"
#include "sampler4bit.h"
#include "screenshot.h"
#include "script64_dongle.h"
#include "serial.h"
#include "sid-cmdline-options.h"
#include "sid-resources.h"
#include "sid.h"
#include "sound.h"
#include "spaceballs.h"
#include "tape.h"
#include "tape_diag_586220_harness.h"
#include "tapeport.h"
#include "tapecart.h"
#include "tpi.h"
#include "traps.h"
#include "trapthem_snespad.h"
#include "types.h"
#include "userport.h"
#include "userport_4bit_sampler.h"
#include "userport_8bss.h"
#include "userport_dac.h"
#include "userport_diag_586220_harness.h"
#include "userport_digimax.h"
#include "userport_hks_joystick.h"
#include "userport_hummer_joystick.h"
#include "userport_io_sim.h"
#include "userport_joystick.h"
#include "userport_petscii_snespad.h"
#include "userport_rtc_58321a.h"
#include "userport_rtc_ds1307.h"
#include "userport_spt_joystick.h"
#include "userport_superpad64.h"
#include "userport_synergy_joystick.h"
#include "userport_wic64.h"
#include "userport_woj_joystick.h"
#include "vdc.h"
#include "vdc-mem.h"
#include "vice-event.h"
#include "vicii.h"
#include "vicii-mem.h"
#include "video.h"
#include "video-sound.h"
#include "vizawrite64_dongle.h"
#include "vsync.h"
#include "waasoft_dongle.h"
#include "z80.h"
#include "z80mem.h"
#include "lightpen.h"
#include "mouse.h"
Macros
#define CARTRIDGE_INCLUDE_SLOTMAIN_API
#define KBDBUF_ALARM_DELAY 1
Delay in seconds before pasting -keybuf argument into the buffer.
Functions
void c64_256k_store (uint16_t addr, uint8_t byte)
uint8_t c64_256k_read (uint16_t addr)
uint8_t c64_256k_ram_segment2_read (uint16_t addr)
void c64_256k_ram_segment2_store (uint16_t addr, uint8_t byte)
void c64_256k_cia_set_vbank (int ciabank)
uint8_t plus60k_ram_read (uint16_t addr)
void plus60k_ram_store (uint16_t addr, uint8_t value)
uint8_t plus256k_ram_high_read (uint16_t addr)
void plus256k_ram_high_store (uint16_t addr, uint8_t byte)
static void c128_trigger_light_pen (CLOCK mclk)
Lightpen trigger function; needs to trigger both VICII and VDC.
static void machine_vsync_hook (void)
This hook is called at the end of every frame.
int machine_get_keyboard_type (void)
char * machine_get_keyboard_type_name (int type)
int machine_get_num_keyboard_types (void)
return number of available keyboard types for this machine
kbdtype_info_t * machine_get_keyboard_info_list (void)
void machine_tape_init_c64 (void)
void machine_tape_init_c128 (void)
static int cia2_dump (void)
void c64io_vicii_init (void)
void c64io_vicii_deinit (void)
static void c128io_init (void)
static int init_joyport_ports (void)
int machine_resources_init (void)
void machine_resources_shutdown (void)
int machine_cmdline_options_init (void)
C128-specific command-line option initialization.
static void c128_monitor_init (void)
void machine_setup_context (void)
Initialize the machine.
int machine_specific_init (void)
C128-specific initialization.
void machine_specific_reset (void)
C128-specific reset sequence.
void machine_specific_powerup (void)
void machine_specific_shutdown (void)
void machine_handle_pending_alarms (CLOCK num_write_cycles)
handle pending interrupts - needed by libsid.a.
void machine_kbdbuf_reset_c128 (void)
void machine_kbdbuf_reset_c64 (void)
void machine_autostart_reset_c128 (void)
void machine_autostart_reset_c64 (void)
void machine_set_restore_key (int v)
Set the state of the RESTORE key (!=0 means pressed)
int machine_has_restore_key (void)
returns 1 if key is present
long machine_get_cycles_per_second (void)
Get the number of CPU cylces per second.
long machine_get_cycles_per_frame (void)
Get the number of CPU cylces per frame.
void machine_get_line_cycle (unsigned int *line, unsigned int *cycle, int *half_cycle)
Get current line and cycle.
void machine_change_timing (int timeval, int powerfreq, int border_mode)
Change the timing parameters of the maching (for example PAL/NTSC).
int machine_write_snapshot (const char *name, int save_roms, int save_disks, int event_mode)
Write a snapshot.
int machine_read_snapshot (const char *name, int event_mode)
Read a snapshot.
int machine_autodetect_psid (const char *name)
Autodetect PSID file.
int machine_screenshot (screenshot_t *screenshot, struct video_canvas_s *canvas)
int machine_canvas_async_refresh (struct canvas_refresh_s *refresh, struct video_canvas_s *canvas)
void machine_update_memory_ptrs (void)
Update memory pointers if memory mapping has changed.
struct image_contents_s * machine_diskcontents_bus_read (unsigned int unit)
uint8_t machine_tape_type_default (void)
uint8_t machine_tape_behaviour (void)
int machine_addr_in_ram (unsigned int addr)
this is currently only used by the autostart code
const char * machine_get_name (void)
Get "real" name for machine.
static void c128_userport_set_flag (uint8_t b)
int machine_register_userport (void)
Variables
int c64_256k_enabled = 0
int c64_256k_start = 0xdf80
int plus60k_enabled = 0
int plus256k_enabled = 0
machine_context_t machine_context
const char machine_name [] = "C128"
The following stuff must be defined once per every emulated CBM machine.
int machine_class = (1U<<1)
Machine class.
static kbdtype_info_t kbdinfo []
For use in the UI's, the actuall keymaps still need to be generated.
static const trap_t c128_serial_traps []
static const trap_t c128_tape_traps []
Tape traps.
static const tape_init_t tapeinit_c128_mode
static const tape_init_t tapeinit_c64_mode
static int tapemode = 0
static log_t c128_log = ((log_t)-1)
static machine_timing_t machine_timing
static io_source_t vicii_d000_device
C128-specific I/O initialization.
static io_source_t vicii_d100_device
static io_source_t vicii_d200_device
static io_source_t vicii_d300_device
static io_source_t sid_d400_device
static io_source_t sid_d420_device
static io_source_t vdc_d600_device
static io_source_t cia2_dd00_device
static io_source_list_t * vicii_d000_list_item = NULL
static io_source_list_t * vicii_d100_list_item = NULL
static io_source_list_t * vicii_d200_list_item = NULL
static io_source_list_t * vicii_d300_list_item = NULL
static io_source_list_t * sid_d400_list_item = NULL
static io_source_list_t * sid_d420_list_item = NULL
static io_source_list_t * vdc_d600_list_item = NULL
static io_source_list_t * cia2_dd00_list_item = NULL
static joyport_port_props_t control_port_1
static joyport_port_props_t control_port_2
static joyport_port_props_t joy_adapter_control_port_1
static joyport_port_props_t joy_adapter_control_port_2
static joyport_port_props_t joy_adapter_control_port_3
static joyport_port_props_t joy_adapter_control_port_4
static joyport_port_props_t joy_adapter_control_port_5
static joyport_port_props_t joy_adapter_control_port_6
static joyport_port_props_t joy_adapter_control_port_7
static joyport_port_props_t joy_adapter_control_port_8
static userport_port_props_t userport_props
Detailed Description
C128 basic stuff.
Author
Andreas Boose vicet.nosp@m.eam@.nosp@m.t-onl.nosp@m.ine..nosp@m.de
Ettore Perazzoli ettor.nosp@m.e@co.nosp@m.mm200.nosp@m.0.it
Marco van den Heuvel black.nosp@m.ysta.nosp@m.rdust.nosp@m.68@y.nosp@m.ahoo..nosp@m.com
Jouko Valta jopi@.nosp@m.stek.nosp@m.t.oul.nosp@m.u.fi
Macro Definition Documentation
CARTRIDGE_INCLUDE_SLOTMAIN_API
#define CARTRIDGE_INCLUDE_SLOTMAIN_API
KBDBUF_ALARM_DELAY
#define KBDBUF_ALARM_DELAY 1
Delay in seconds before pasting -keybuf argument into the buffer.
Function Documentation
c128_monitor_init()
static void c128_monitor_init (void) static
Referenced by machine_specific_init().
c128_trigger_light_pen()
static void c128_trigger_light_pen (CLOCK mclk) static
Lightpen trigger function; needs to trigger both VICII and VDC.
Referenced by machine_specific_init().
c128_userport_set_flag()
static void c128_userport_set_flag (uint8_t b) static
c128io_init()
static void c128io_init (void) static
Referenced by machine_specific_init().
c64_256k_cia_set_vbank()
void c64_256k_cia_set_vbank (int ciabank)
c64_256k_ram_segment2_read()
uint8_t c64_256k_ram_segment2_read (uint16_t addr)
c64_256k_ram_segment2_store()
void c64_256k_ram_segment2_store (uint16_t addr, uint8_t byte)
c64_256k_read()
uint8_t c64_256k_read (uint16_t addr)
c64_256k_store()
void c64_256k_store (uint16_t addr, uint8_t byte)
c64io_vicii_deinit()
void c64io_vicii_deinit (void)
c64io_vicii_init()
void c64io_vicii_init (void)
Referenced by c128io_init().
cia2_dump()
static int cia2_dump (void) static
init_joyport_ports()
static int init_joyport_ports (void) static
Referenced by machine_resources_init().
machine_addr_in_ram()
int machine_addr_in_ram (unsigned int addr)
this is currently only used by the autostart code
Check if address is in RAM (for autostart)
Todo:
FIXME: C128 is a special beast, as it would execute some stuff in system RAM - which this special case hack checks. without this check eg autostarting a prg file with autostartmode= "disk image" will fail. (exit from ROM at $some RAM address)
Referenced by check_rom_area().
machine_autodetect_psid()
int machine_autodetect_psid (const char * name)
Autodetect PSID file.
Referenced by initcmdline_check_psid(), and ui_vsid_window_load_psid().
machine_autostart_reset_c128()
void machine_autostart_reset_c128 (void)
Todo:
FIXME: check if this is really needed and remove eventually
Referenced by mmu_switch_to_c128mode().
machine_autostart_reset_c64()
void machine_autostart_reset_c64 (void)
Todo:
FIXME: check if this is really needed and remove eventually
Referenced by mmu_switch_to_c64mode().
machine_canvas_async_refresh()
int machine_canvas_async_refresh (struct canvas_refresh_s * refresh, struct video_canvas_s * canvas)
machine_change_timing()
void machine_change_timing (int timeval, int powerfreq, int border_mode)
Change the timing parameters of the maching (for example PAL/NTSC).
Referenced by on_vsync_set_border_mode(), set_power_freq(), and set_sync_factor().
machine_cmdline_options_init()
int machine_cmdline_options_init (void)
C128-specific command-line option initialization.
Referenced by init_cmdline_options().
machine_diskcontents_bus_read()
struct image_contents_s * machine_diskcontents_bus_read (unsigned int unit)
machine_get_cycles_per_frame()
long machine_get_cycles_per_frame (void)
Get the number of CPU cylces per frame.
Referenced by ffmpegexedrv_init_video(), file_load_sample(), kbd_make_event_timestap(), kbdbuf_flush(), reboot_for_autostart(), sound_set_relative_speed(), and zmbvdrv_init_video().
machine_get_cycles_per_second()
long machine_get_cycles_per_second (void)
Get the number of CPU cylces per second.
This is used in various parts.
Referenced by event_alarm_handler(), event_snapshot_read_module(), fastload_mode_init(), fastload_postdelay(), ffmpegexedrv_init_video(), file_load_sample(), print_cycle_time(), reboot_for_autostart(), receive_1bit_callback(), set_acia_ticks(), sound_set_relative_speed(), tapecart_enable(), tapecart_logic_alarm_handler(), tapecart_pulse_alarm_handler(), tapecart_set_mode(), vdc_calculate_xsync(), vdc_lightpen_timing(), and zmbvdrv_init_video().
machine_get_keyboard_info_list()
kbdtype_info_t * machine_get_keyboard_info_list (void)
Referenced by keyboard_is_hosttype_valid().
machine_get_keyboard_type()
int machine_get_keyboard_type (void)
Todo:
FIXME: add different keyboard types
machine_get_keyboard_type_name()
char * machine_get_keyboard_type_name (int type)
Referenced by keyboard_get_keymap_name().
machine_get_line_cycle()
void machine_get_line_cycle (unsigned int * line, unsigned int * cycle, int * half_cycle)
Get current line and cycle.
Referenced by maincpu_monitor_interface_get().
machine_get_name()
const char * machine_get_name (void)
Get "real" name for machine.
May differ from machine_name.
machine_get_num_keyboard_types()
int machine_get_num_keyboard_types (void)
return number of available keyboard types for this machine
Referenced by keyboard_is_hosttype_valid().
machine_handle_pending_alarms()
void machine_handle_pending_alarms (CLOCK num_write_cycles)
handle pending interrupts - needed by libsid.a.
Referenced by sid_read_chip(), sid_store_chip(), vdc_read(), vdc_store(), and zero_store().
machine_has_restore_key()
int machine_has_restore_key (void)
returns 1 if key is present
Referenced by key_restore1_pressed(), and key_restore2_pressed().
machine_kbdbuf_reset_c128()
void machine_kbdbuf_reset_c128 (void)
Referenced by mmu_switch_to_c128mode().
machine_kbdbuf_reset_c64()
void machine_kbdbuf_reset_c64 (void)
Referenced by mmu_switch_to_c64mode().
machine_read_snapshot()
int machine_read_snapshot (const char * name, int even_mode)
Read a snapshot.
Referenced by event_playback_start_trap(), event_record_reset_milestone_trap(), event_record_start_trap(), load_snapshot_filename_callback(), load_snapshot_trap(), mon_read_snapshot(), network_client_connect_trap(), and quickload_snapshot_trap().
machine_register_userport()
int machine_register_userport (void)
Referenced by userport_resources_init().
machine_resources_init()
int machine_resources_init (void)
Referenced by init_resources().
machine_resources_shutdown()
void machine_resources_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
machine_screenshot()
int machine_screenshot (screenshot_t * screenshot, struct video_canvas_s * canvas)
Referenced by monitor_binary_process_display_get(), monitor_binary_process_palette_get(), screenshot_record(), and screenshot_save().
machine_set_restore_key()
void machine_set_restore_key (int v)
Set the state of the RESTORE key (!=0 means pressed)
Referenced by keyboard_restore_event_playback(), and restore_alarm_triggered().
machine_setup_context()
void machine_setup_context (void)
Initialize the machine.
Referenced by main_program().
machine_specific_init()
int machine_specific_init (void)
C128-specific initialization.
Referenced by machine_init().
machine_specific_powerup()
void machine_specific_powerup (void)
Referenced by machine_powerup().
machine_specific_reset()
void machine_specific_reset (void)
C128-specific reset sequence.
Referenced by machine_reset().
machine_specific_shutdown()
void machine_specific_shutdown (void)
Referenced by cmdline_help(), and machine_shutdown().
machine_tape_behaviour()
uint8_t machine_tape_behaviour (void)
< tape interrupt is falling-edge triggered, normal tape blocks end with a long and a short pulse
machine_tape_init_c128()
void machine_tape_init_c128 (void)
Referenced by machine_specific_init(), and mmu_switch_to_c128mode().
machine_tape_init_c64()
void machine_tape_init_c64 (void)
Referenced by mmu_switch_to_c64mode().
machine_tape_type_default()
uint8_t machine_tape_type_default (void)
< Binary Program (absolute load, SAVE "",1,1 (VIC-20 and later))
Referenced by default_tape_header_type().
machine_update_memory_ptrs()
void machine_update_memory_ptrs (void)
Update memory pointers if memory mapping has changed.
Referenced by mem_set_ram_config(), and mem_update_chargen().
machine_vsync_hook()
static void machine_vsync_hook (void) static
This hook is called at the end of every frame.
Referenced by machine_specific_init().
machine_write_snapshot()
int machine_write_snapshot (const char * name, int save_roms, int save_disks, int even_mode)
Write a snapshot.
Referenced by event_record_set_milestone_trap(), event_record_start_trap(), event_record_stop_trap(), mon_write_snapshot(), network_server_connect_trap(), quicksave_snapshot_trap(), and save_snapshot_dialog().
plus256k_ram_high_read()
uint8_t plus256k_ram_high_read (uint16_t addr)
plus256k_ram_high_store()
void plus256k_ram_high_store (uint16_t addr, uint8_t byte)
plus60k_ram_read()
uint8_t plus60k_ram_read (uint16_t addr)
plus60k_ram_store()
void plus60k_ram_store (uint16_t addr, uint8_t value)
Variable Documentation
c128_log
log_t c128_log = ((log_t)-1) static
Referenced by machine_change_timing(), and machine_specific_init().
c128_serial_traps
const trap_t c128_serial_traps[] static
Initial value:
= {
    { "SerialListen", 0xE355, 0xE5BA, { 0x20, 0x73, 0xE5 }, serial_trap_attention, c128memrom_trap_read, c128memrom_trap_store },
    { "SerialSaListen", 0xE37C, 0xE5BA, { 0x20, 0x73, 0xE5 }, serial_trap_attention, c128memrom_trap_read, c128memrom_trap_store },
    { "SerialSendByte", 0xE38C, 0xE5BA, { 0x20, 0x73, 0xE5 }, serial_trap_send, c128memrom_trap_read, c128memrom_trap_store },
    { "SerialReceiveByte", 0xE43E, 0xE5BA, { 0x20, 0x73, 0xE5 }, serial_trap_receive, c128memrom_trap_read, c128memrom_trap_store },
    { "Serial ready", 0xE569, 0xE572, { 0xAD, 0x00, 0xDD }, serial_trap_ready, c128memrom_trap_read, c128memrom_trap_store },
    { "Serial ready", 0xE4F5, 0xE572, { 0xAD, 0x00, 0xDD }, serial_trap_ready, c128memrom_trap_read, c128memrom_trap_store },
    { "SerialListen", 0xED24, 0xEDAB, { 0x20, 0x97, 0xEE }, serial_trap_attention, c64memrom_trap_read, c64memrom_trap_store },
    { "SerialSaListen", 0xED37, 0xEDAB, { 0x20, 0x8E, 0xEE }, serial_trap_attention, c64memrom_trap_read, c64memrom_trap_store },
    { "SerialSendByte", 0xED41, 0xEDAB, { 0x20, 0x97, 0xEE }, serial_trap_send, c64memrom_trap_read, c64memrom_trap_store },
    { "SerialReceiveByte", 0xEE14, 0xEDAB, { 0xA9, 0x00, 0x85 }, serial_trap_receive, c64memrom_trap_read, c64memrom_trap_store },
    { "SerialReady", 0xEEA9, 0xEDAB, { 0xAD, 0x00, 0xDD }, serial_trap_ready, c64memrom_trap_read, c64memrom_trap_store },
    { NULL, 0, 0, { 0, 0, 0 }, NULL, NULL, NULL }
}
Referenced by machine_specific_init().
c128_tape_traps
const trap_t c128_tape_traps[] static
Initial value:
= {
    { "TapeFindHeader", 0xE8D3, 0xE8D6, { 0x20, 0xF2, 0xE9 }, tape_find_header_trap, c128memrom_trap_read, c128memrom_trap_store },
    { "TapeReceive", 0xEA60, 0xEE57, { 0x20, 0x9B, 0xEE }, tape_receive_trap, c128memrom_trap_read, c128memrom_trap_store },
    { "TapeFindHeader", 0xF72F, 0xF732, { 0x20, 0x41, 0xF8 }, tape_find_header_trap, c64memrom_trap_read, c64memrom_trap_store },
    { "TapeReceive", 0xF8A1, 0xFC93, { 0x20, 0xBD, 0xFC }, tape_receive_trap, c64memrom_trap_read, c64memrom_trap_store },
    { NULL, 0, 0, { 0, 0, 0 }, NULL, NULL, NULL
    }
}
Tape traps.
c64_256k_enabled
int c64_256k_enabled = 0
c64_256k_start
int c64_256k_start = 0xdf80
cia2_dd00_device
io_source_t cia2_dd00_device static
Initial value:
= {
    "CIA2",
     2 ,
     NULL ,
    0xdd00, 0xddff, 0x0f,
    1,
    cia2_store,
    NULL,
    cia2_read,
    cia2_peek,
    cia2_dump,
     0 ,
     1  ,
    0,
     2
}
Referenced by c128io_init().
cia2_dd00_list_item
io_source_list_t* cia2_dd00_list_item = NULL static
Referenced by c128io_init().
control_port_1
joyport_port_props_t control_port_1 static
Initial value:
=
{
    "Control port 1",
    1,
    1,
    1,
    1,
    1,
    1
}
Referenced by init_joyport_ports().
control_port_2
joyport_port_props_t control_port_2 static
Initial value:
=
{
    "Control port 2",
    1,
    0,
    1,
    1,
    1,
    1
}
Referenced by init_joyport_ports().
joy_adapter_control_port_1
joyport_port_props_t joy_adapter_control_port_1 static
Initial value:
=
{
    "Joystick adapter port 1",
    0,
    0,
    0,
    1,
    0,
    0
}
Referenced by init_joyport_ports().
joy_adapter_control_port_2
joyport_port_props_t joy_adapter_control_port_2 static
Initial value:
=
{
    "Joystick adapter port 2",
    0,
    0,
    0,
    1,
    0,
    0
}
Referenced by init_joyport_ports().
joy_adapter_control_port_3
joyport_port_props_t joy_adapter_control_port_3 static
Initial value:
=
{
    "Joystick adapter port 3",
    0,
    0,
    0,
    1,
    0,
    0
}
Referenced by init_joyport_ports().
joy_adapter_control_port_4
joyport_port_props_t joy_adapter_control_port_4 static
Initial value:
=
{
    "Joystick adapter port 4",
    0,
    0,
    0,
    1,
    0,
    0
}
Referenced by init_joyport_ports().
joy_adapter_control_port_5
joyport_port_props_t joy_adapter_control_port_5 static
Initial value:
=
{
    "Joystick adapter port 5",
    0,
    0,
    0,
    1,
    0,
    0
}
Referenced by init_joyport_ports().
joy_adapter_control_port_6
joyport_port_props_t joy_adapter_control_port_6 static
Initial value:
=
{
    "Joystick adapter port 6",
    0,
    0,
    0,
    1,
    0,
    0
}
Referenced by init_joyport_ports().
joy_adapter_control_port_7
joyport_port_props_t joy_adapter_control_port_7 static
Initial value:
=
{
    "Joystick adapter port 7",
    0,
    0,
    0,
    1,
    0,
    0
}
Referenced by init_joyport_ports().
joy_adapter_control_port_8
joyport_port_props_t joy_adapter_control_port_8 static
Initial value:
=
{
    "Joystick adapter port 8",
    0,
    0,
    0,
    1,
    0,
    0
}
Referenced by init_joyport_ports().
kbdinfo
kbdtype_info_t kbdinfo[] static
Initial value:
= {
    { "International", C128_MACHINE_INT, 0 },
    { "Finnish", C128_MACHINE_FINNISH, 0 },
    { "French", C128_MACHINE_FRENCH, 0 },
    { "German", C128_MACHINE_GERMAN, 0 },
    { "Italian", C128_MACHINE_ITALIAN, 0 },
    { "Norwegian", C128_MACHINE_NORWEGIAN, 0 },
    { "Swedish", C128_MACHINE_SWEDISH, 0 },
    { "Swiss", C128_MACHINE_SWISS, 0 },
    { NULL, 0, 0 }
}
For use in the UI's, the actuall keymaps still need to be generated.
Referenced by machine_get_keyboard_info_list().
machine_class
int machine_class = (1U<<1)
Machine class.
machine_context
machine_context_t machine_context
Referenced by c128_snapshot_read(), c128_snapshot_write(), c128_userport_set_flag(), cia1_check_lightpen(), cia1_init(), cia1_peek(), cia1_read(), cia1_store(), cia1_update_model(), cia2_dump(), iec_fast_drive_write(), machine_change_timing(), machine_setup_context(), machine_specific_init(), machine_specific_reset(), machine_specific_shutdown(), mem_dump_io(), store_ciapa(), and store_ciapb().
machine_name
const char machine_name[] = "C128"
The following stuff must be defined once per every emulated CBM machine.
Name of the machine.
The following stuff must be defined once per every emulated CBM machine.
Referenced by machine_get_name().
machine_timing
machine_timing_t machine_timing static
Referenced by machine_change_timing(), machine_get_cycles_per_frame(), machine_get_cycles_per_second(), machine_get_line_cycle(), machine_kbdbuf_reset_c128(), machine_kbdbuf_reset_c64(), machine_specific_init(), and vicii_change_timing().
plus256k_enabled
int plus256k_enabled = 0
plus60k_enabled
int plus60k_enabled = 0
sid_d400_device
io_source_t sid_d400_device static
Initial value:
= {
    "SID",
     2 ,
     NULL ,
    0xd400, 0xd41f, 0x1f,
    1,
    sid_store,
    NULL,
    sid_read,
    sid_peek,
    sid_dump,
     0 ,
     1  ,
    0,
     0
}
Referenced by c128io_init().
sid_d400_list_item
io_source_list_t* sid_d400_list_item = NULL static
Referenced by c128io_init().
sid_d420_device
io_source_t sid_d420_device static
Initial value:
= {
    "SID mirrors",
     2 ,
     NULL ,
    0xd420, 0xd4ff, 0x1f,
    1,
    sid_store,
    NULL,
    sid_read,
    sid_peek,
    sid_dump,
     0 ,
     -1  ,
    0,
     1
}
Referenced by c128io_init().
sid_d420_list_item
io_source_list_t* sid_d420_list_item = NULL static
Referenced by c128io_init().
tapeinit_c128_mode
const tape_init_t tapeinit_c128_mode static
Initial value:
= {
    0xb2,
    0x90,
    0x93,
    0xa09,
    0,
    0xc1,
    0xae,
    0x34a,
    0xd0,
    c128_tape_traps,
    36 * 8,
    54 * 8,
    55 * 8,
    73 * 8,
    74 * 8,
    100 * 8
}
Referenced by machine_tape_init_c128().
tapeinit_c64_mode
const tape_init_t tapeinit_c64_mode static
Initial value:
= {
    0xb2,
    0x90,
    0x93,
    0x29f,
    0,
    0xc1,
    0xae,
    0x277,
    0xc6,
    c128_tape_traps,
    36 * 8,
    54 * 8,
    55 * 8,
    73 * 8,
    74 * 8,
    100 * 8
}
Referenced by machine_tape_init_c64().
tapemode
int tapemode = 0 static
Referenced by machine_tape_init_c128(), and machine_tape_init_c64().
userport_props
userport_port_props_t userport_props static
Initial value:
= {
    1,
    1,
    c128_userport_set_flag,
    1,
    1,
    1
}
Referenced by machine_register_userport().
vdc_d600_device
io_source_t vdc_d600_device static
Initial value:
= {
    "VDC",
     2 ,
     NULL ,
    0xd600, 0xd6ff, 0x01,
    1,
    vdc_store,
    NULL,
    vdc_read,
    vdc_peek,
    vdc_dump,
     0 ,
     0  ,
    0,
     2
}
Referenced by c128io_init().
vdc_d600_list_item
io_source_list_t* vdc_d600_list_item = NULL static
Referenced by c128io_init().
vicii_d000_device
io_source_t vicii_d000_device static
Initial value:
= {
    "VIC-IIe",
     2 ,
     NULL ,
    0xd000, 0xd0ff, 0x3f,
    1,
    vicii_store,
    NULL,
    vicii_read,
    vicii_peek,
    vicii_dump,
     0 ,
     1  ,
    0,
     2
}
C128-specific I/O initialization.
Referenced by c64io_vicii_init().
vicii_d000_list_item
io_source_list_t* vicii_d000_list_item = NULL static
Referenced by c64io_vicii_deinit(), and c64io_vicii_init().
vicii_d100_device
io_source_t vicii_d100_device static
Initial value:
= {
    "VIC-IIe $D100-$D1FF mirrors",
     2 ,
     NULL ,
    0xd100, 0xd1ff, 0x3f,
    1,
    vicii_store,
    NULL,
    vicii_read,
    vicii_peek,
    vicii_dump,
     0 ,
     1  ,
    0,
     1
}
Referenced by c64io_vicii_init().
vicii_d100_list_item
io_source_list_t* vicii_d100_list_item = NULL static
Referenced by c64io_vicii_deinit(), and c64io_vicii_init().
vicii_d200_device
io_source_t vicii_d200_device static
Initial value:
= {
    "VIC-IIe $D200-$D2FF mirrors",
     2 ,
     NULL ,
    0xd200, 0xd2ff, 0x3f,
    1,
    vicii_store,
    NULL,
    vicii_read,
    vicii_peek,
    vicii_dump,
     0 ,
     1  ,
    0,
     1
}
Referenced by c64io_vicii_init().
vicii_d200_list_item
io_source_list_t* vicii_d200_list_item = NULL static
Referenced by c64io_vicii_deinit(), and c64io_vicii_init().
vicii_d300_device
io_source_t vicii_d300_device static
Initial value:
= {
    "VIC-IIe $D300-$D3FF mirrors",
     2 ,
     NULL ,
    0xd300, 0xd3ff, 0x3f,
    1,
    vicii_store,
    NULL,
    vicii_read,
    vicii_peek,
    vicii_dump,
     0 ,
     1  ,
    0,
     1
}
Referenced by c64io_vicii_init().
vicii_d300_list_item
io_source_list_t* vicii_d300_list_item = NULL static
Referenced by c64io_vicii_deinit(), and c64io_vicii_init().