x128: drive/rotation.h File Reference
rotation.h File Reference
#include "types.h"
Macros
#define BUS_READ_DELAY 14
875ns delay (14*62.5ns R cycles) for data bus read access
Functions
void rotation_init (int freq, unsigned int dnr)
void rotation_reset (struct drive_s *drive)
void rotation_speed_zone_set (unsigned int zone, unsigned int dnr)
void rotation_table_get (uint32_t *rotation_table_ptr)
void rotation_table_set (uint32_t *rotation_table_ptr)
void rotation_overflow_callback (CLOCK sub, unsigned int dnr)
void rotation_change_mode (unsigned int dnr)
void rotation_begins (struct drive_s *dptr)
void rotation_rotate_disk (struct drive_s *dptr)
uint8_t rotation_sync_found (struct drive_s *dptr)
void rotation_byte_read (struct drive_s *dptr)
Macro Definition Documentation
BUS_READ_DELAY
#define BUS_READ_DELAY 14
875ns delay (14*62.5ns R cycles) for data bus read access
Function Documentation
rotation_begins()
void rotation_begins (struct drive_s * dptr)
Referenced by glue_pport_update(), and store_prb().
rotation_byte_read()
void rotation_byte_read (struct drive_s * dptr)
Referenced by read_pb(), and read_pra().
rotation_change_mode()
void rotation_change_mode (unsigned int dnr)
rotation_init()
void rotation_init (int freq, unsigned int dnr)
Referenced by drive_init(), drive_set_disk_drive_type(), and drivesync_set_1571().
rotation_overflow_callback()
void rotation_overflow_callback (CLOCK sub, unsigned int dnr)
rotation_reset()
void rotation_reset (struct drive_s * drive)
Referenced by cpu_reset(), and drive_init().
rotation_rotate_disk()
void rotation_rotate_disk (struct drive_s * dptr)
< chosen for the bit in the VIA2 PB register
Referenced by drive_set_disk_drive_type(), drive_vsync_hook(), drivesync_set_1571(), glue1571_side_set(), glue_pport_update(), read_pc(), read_pra(), read_prb(), rotation_byte_read(), set_ca2(), set_cb2(), store_pb(), store_pc(), store_pcr(), store_pra(), store_prb(), and via2d_update_pcr().
rotation_speed_zone_set()
void rotation_speed_zone_set (unsigned int zone, unsigned int dnr)
Referenced by glue_pport_update(), store_prb(), and undump_prb().
rotation_sync_found()
uint8_t rotation_sync_found (struct drive_s * dptr)
Referenced by read_pc(), and read_prb().
rotation_table_get()
void rotation_table_get (uint32_t * rotation_table_ptr)
Referenced by drive_snapshot_write_module().
rotation_table_set()
void rotation_table_set (uint32_t * rotation_table_ptr)
Referenced by drive_snapshot_read_module().