vsid: rs232drv/rs232dev.h File Reference
rs232dev.h File Reference
#include "types.h"
Functions
void rs232dev_init (void)
Initializes all RS232 stuff.
void rs232dev_reset (void)
Reset for RS232 interfaces.
int rs232dev_open (int device)
Opens a rs232 window, returns handle to give to functions below.
void rs232dev_close (int fd)
Closes the rs232 window again.
int rs232dev_putc (int fd, uint8_t b)
Sends a byte to the RS232 line.
int rs232dev_getc (int fd, uint8_t *b)
Gets a byte to the RS232 line, returns !=1 if byte received, byte in *b.
int rs232dev_set_status (int fd, enum rs232handshake_out status)
write the output handshake lines
enum rs232handshake_in rs232dev_get_status (int fd)
write the output handshake lines
void rs232dev_set_bps (int fd, unsigned int bps)
int rs232dev_resources_init (void)
void rs232dev_resources_shutdown (void)
int rs232dev_cmdline_options_init (void)
Function Documentation
rs232dev_close()
void rs232dev_close (int fd)
Closes the rs232 window again.
Referenced by rs232_close().
rs232dev_cmdline_options_init()
int rs232dev_cmdline_options_init (void)
Referenced by rs232_cmdline_options_init().
rs232dev_get_status()
enum rs232handshake_in rs232dev_get_status (int fd)
write the output handshake lines
Referenced by rs232_get_status().
rs232dev_getc()
int rs232dev_getc (int fd, uint8_t * b)
Gets a byte to the RS232 line, returns !=1 if byte received, byte in *b.
Referenced by rs232_getc().
rs232dev_init()
void rs232dev_init (void)
Initializes all RS232 stuff.
Referenced by rs232_init().
rs232dev_open()
int rs232dev_open (int device)
Opens a rs232 window, returns handle to give to functions below.
Referenced by rs232_open().
rs232dev_putc()
int rs232dev_putc (int fd, uint8_t b)
Sends a byte to the RS232 line.
Referenced by rs232_putc().
rs232dev_reset()
void rs232dev_reset (void)
Reset for RS232 interfaces.
Referenced by rs232_reset().
rs232dev_resources_init()
int rs232dev_resources_init (void)
Referenced by rs232_resources_init().
rs232dev_resources_shutdown()
void rs232dev_resources_shutdown (void)
Referenced by rs232_resources_shutdown().
rs232dev_set_bps()
void rs232dev_set_bps (int fd, unsigned int bps)
Referenced by rs232_set_bps().
rs232dev_set_status()
int rs232dev_set_status (int fd, enum rs232handshake_out status)
write the output handshake lines
Referenced by rs232_set_status().