vsid: fsdevice/fsdevice-write.c File Reference
fsdevice-write.c File Reference
#include "vice.h"
#include <stdio.h>
#include "fileio.h"
#include "fsdevice-flush.h"
#include "fsdevice-read.h"
#include "fsdevice-write.h"
#include "fsdevicetypes.h"
#include "types.h"
#include "vdrive.h"
#include "vdrive/vdrive-command.h"
Macros
#define DBG(x)
Functions
static void fsdevice_rel_listen (vdrive_t *vdrive, bufinfo_t *bufinfo, unsigned int secondary)
void fsdevice_listen (vdrive_t *vdrive, unsigned int secondary)
static void fsdevice_relfile_extend_if_needed (bufinfo_t *bufinfo)
int fsdevice_write (struct vdrive_s *vdrive, uint8_t data, unsigned int secondary)
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
fsdevice_listen()
void fsdevice_listen (vdrive_t * vdrive, unsigned int secondary)
Referenced by fsdevice_attach().
fsdevice_rel_listen()
static void fsdevice_rel_listen (vdrive_t * vdrive, bufinfo_t * bufinfo, unsigned int secondary) static
Referenced by fsdevice_listen().
fsdevice_relfile_extend_if_needed()
static void fsdevice_relfile_extend_if_needed (bufinfo_t * bufinfo) static
Referenced by fsdevice_write().
fsdevice_write()
int fsdevice_write (struct vdrive_s * vdrive, uint8_t data, unsigned int secondary)
Referenced by fsdevice_attach(), and fsdevice_open().