vsid: drive/iec/via1d1541.h File Reference
via1d1541.h File Reference
#include "types.h"
Functions
void via1d1541_setup_context (struct diskunit_context_s *ctxptr)
void via1d1541_init (struct diskunit_context_s *ctxptr)
void via1d1541_store (struct diskunit_context_s *ctxptr, uint16_t addr, uint8_t byte)
uint8_t via1d1541_read (struct diskunit_context_s *ctxptr, uint16_t addr)
uint8_t via1d1541_peek (struct diskunit_context_s *ctxptr, uint16_t addr)
int via1d1541_dump (diskunit_context_t *ctxptr, uint16_t addr)
Function Documentation
via1d1541_dump()
int via1d1541_dump (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by drivemem_ioreg_list_get().
via1d1541_init()
void via1d1541_init (struct diskunit_context_s * ctxptr)
Referenced by iec_drive_init().
via1d1541_peek()
uint8_t via1d1541_peek (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memiec_init().
via1d1541_read()
uint8_t via1d1541_read (struct diskunit_context_s * ctxptr, uint16_t addr)
Referenced by memiec_init().
via1d1541_setup_context()
void via1d1541_setup_context (struct diskunit_context_s * ctxptr)
Referenced by iec_drive_setup_context().
via1d1541_store()
void via1d1541_store (struct diskunit_context_s * ctxptr, uint16_t addr, uint8_t byte)
Referenced by memiec_init().