x128: drive/ieee/riot1d.c File Reference
riot1d.c File Reference
#include "vice.h"
#include <stdio.h>
#include "drive.h"
#include "drivetypes.h"
#include "lib.h"
#include "parallel.h"
#include "riot.h"
#include "riotd.h"
#include "types.h"
Functions
void riot1_store (diskunit_context_t *ctxptr, uint16_t addr, uint8_t data)
uint8_t riot1_read (diskunit_context_t *ctxptr, uint16_t addr)
uint8_t riot1_peek (diskunit_context_t *ctxptr, uint16_t addr)
static void set_irq (riot_context_t *riot_context, int fl, CLOCK clk)
static void restore_irq (riot_context_t *riot_context, int fl)
static void undump_pra (riot_context_t *riot_context, uint8_t byte)
static void store_pra (riot_context_t *riot_context, uint8_t byte)
static void undump_prb (riot_context_t *riot_context, uint8_t byte)
static void store_prb (riot_context_t *riot_context, uint8_t byte)
void riot1_set_pardata (riot_context_t *riot_context)
static void reset (riot_context_t *riot_context)
static uint8_t read_pra (riot_context_t *riot_context)
static uint8_t read_prb (riot_context_t *riot_context)
void riot1_init (diskunit_context_t *ctxptr)
void riot1_setup_context (diskunit_context_t *ctxptr)
Function Documentation
read_pra()
static uint8_t read_pra (riot_context_t * riot_context) static
Referenced by riot1_setup_context().
read_prb()
static uint8_t read_prb (riot_context_t * riot_context) static
Referenced by riot1_setup_context().
reset()
static void reset (riot_context_t * riot_context) static
Referenced by riot1_setup_context().
restore_irq()
static void restore_irq (riot_context_t * riot_context, int fl) static
Referenced by riot1_setup_context().
riot1_init()
void riot1_init (diskunit_context_t * ctxptr)
Referenced by ieee_drive_init().
riot1_peek()
uint8_t riot1_peek (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by drive_peek_1001_io().
riot1_read()
uint8_t riot1_read (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by drive_read_1001_io().
riot1_set_pardata()
void riot1_set_pardata (riot_context_t * riot_context)
Referenced by riot2_set_atn().
riot1_setup_context()
void riot1_setup_context (diskunit_context_t * ctxptr)
Referenced by ieee_drive_setup_context().
riot1_store()
void riot1_store (diskunit_context_t * ctxptr, uint16_t addr, uint8_t data)
Referenced by drive_store_1001_io().
set_irq()
static void set_irq (riot_context_t * riot_context, int fl, CLOCK clk) static
Referenced by riot1_setup_context().
store_pra()
static void store_pra (riot_context_t * riot_context, uint8_t byte) static
Referenced by riot1_setup_context().
store_prb()
static void store_prb (riot_context_t * riot_context, uint8_t byte) static
Referenced by reset(), riot1_set_pardata(), and riot1_setup_context().
undump_pra()
static void undump_pra (riot_context_t * riot_context, uint8_t byte) static
Referenced by riot1_setup_context().
undump_prb()
static void undump_prb (riot_context_t * riot_context, uint8_t byte) static
Referenced by riot1_setup_context().