vsid: arch/shared/hotkeys/ifstack.c File Reference
ifstack.c File Reference
IF stack implementation.
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include "lib.h"
#include "ifstack.h"
Data Structures
struct ifstack_s
Doubly linked list node making up the IF stack.
Typedefs
typedef struct ifstack_s ifstack_t
Doubly linked list node making up the IF stack.
Functions
static void ifstack_push (bool state)
Push new condition onto the stack.
static void ifstack_pull (void)
Pull current condtion off the stack.
void ifstack_init (void)
Initialize stack for use.
void ifstack_reset (void)
Reset stack for reuse.
void ifstack_free (void)
Free the stack.
bool ifstack_is_empty (void)
Determine if stack is empty.
void ifstack_print (void)
Print stack contents on stdout.
bool ifstack_true (void)
Get global condition of stack.
void ifstack_if (bool state)
Push new IF condition on stack, update global condition.
bool ifstack_else (void)
Process ELSE branch.
bool ifstack_endif (void)
Process ENDIF.
const char * ifstack_strerror (int errnum)
Get error message for error number.
Variables
static const char * err_messages []
Error message strings.
static ifstack_t * stack
IF stack reference.
static ifstack_t * stack_bottom
IF stack bottom reference.
static bool current_state
Global "truth" state.
int ifstack_errno = 0
Error code.
Detailed Description
IF stack implementation.
Note
Adjusted for VICE from https://github.com/Compyx/if-stack
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Typedef Documentation
ifstack_t
typedef struct ifstack_s ifstack_t
Doubly linked list node making up the IF stack.
Function Documentation
ifstack_else()
bool ifstack_else (void)
Process ELSE branch.
Notify the stack an ELSE branch should now be taken.
Returns
false if no preceeding IF or already in ELSE branch
Referenced by vhk_parser_do_else().
ifstack_endif()
bool ifstack_endif (void)
Process ENDIF.
Notify the stack an ENDIF statement should be handled.
Returns
false if there's no preceeding IF/ELSE
Referenced by vhk_parser_do_endif().
ifstack_free()
void ifstack_free (void)
Free the stack.
Referenced by ifstack_reset(), and vhk_parser_shutdown().
ifstack_if()
void ifstack_if (bool state)
Push new IF condition on stack, update global condition.
Parameters
[in] state condition of IF statement
Referenced by vhk_parser_do_if().
ifstack_init()
void ifstack_init (void)
Initialize stack for use.
Referenced by ifstack_reset(), and vhk_parser_init().
ifstack_is_empty()
bool ifstack_is_empty (void)
Determine if stack is empty.
Returns
true if stack is empty
Referenced by vhk_parser_parse().
ifstack_print()
void ifstack_print (void)
Print stack contents on stdout.
Print the current stack as an array of 0's and 1's.
Note
Doesn't print a newline at the end.
ifstack_pull()
static void ifstack_pull (void) static
Pull current condtion off the stack.
Referenced by ifstack_endif().
ifstack_push()
static void ifstack_push (bool state) static
Push new condition onto the stack.
Register an IF with condition state.
Note
Calls exit(1) on out-of-memory.
Referenced by ifstack_if().
ifstack_reset()
void ifstack_reset (void)
Reset stack for reuse.
Frees any old stack remaining and initializes the stack for reuse.
Referenced by vhk_parser_parse().
ifstack_strerror()
const char * ifstack_strerror (int errnum)
Get error message for error number.
Parameters
[in] errnum error number
Returns
error message
Referenced by vhk_parser_do_else(), and vhk_parser_do_endif().
ifstack_true()
bool ifstack_true (void)
Get global condition of stack.
Returns
current condition
Referenced by vhk_parser_do_clear(), vhk_parser_do_debug(), vhk_parser_do_undef(), vhk_parser_do_warning(), vhk_parser_handle_keyword(), vhk_parser_handle_mapping(), and vhk_parser_parse().
Variable Documentation
current_state
bool current_state static
Global "truth" state.
Referenced by ifstack_else(), ifstack_if(), ifstack_init(), ifstack_pull(), and ifstack_true().
err_messages
const char* err_messages[] static
Initial value:
= {
    "OK",
    "else without if",
    "endif without if"
}
Error message strings.
Referenced by ifstack_strerror().
ifstack_errno
int ifstack_errno = 0
Error code.
Referenced by ifstack_else(), ifstack_endif(), ifstack_init(), vhk_parser_do_else(), and vhk_parser_do_endif().
stack
ifstack_t* stack static
IF stack reference.
This references the top of the stack.
Referenced by ifstack_else(), ifstack_endif(), ifstack_free(), ifstack_if(), ifstack_init(), ifstack_is_empty(), ifstack_pull(), and ifstack_push().
stack_bottom
ifstack_t* stack_bottom static
IF stack bottom reference.
Used for printing the stack from bottom to top in ifstack_print().
Referenced by ifstack_free(), ifstack_init(), ifstack_print(), ifstack_pull(), and ifstack_push().