x128: tape/tape-snapshot.c File Reference
tape-snapshot.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include "archdep.h"
#include "datasette.h"
#include "lib.h"
#include "log.h"
#include "resources.h"
#include "snapshot.h"
#include "t64.h"
#include "tap.h"
#include "tape-snapshot.h"
#include "tape.h"
#include "types.h"
Macros
#define T64IMAGE_SNAP_MAJOR 1
#define T64IMAGE_SNAP_MINOR 0
#define TAPIMAGE_SNAP_MAJOR 1
#define TAPIMAGE_SNAP_MINOR 0
#define TAPE_SNAP_MAJOR 1
#define TAPE_SNAP_MINOR 0
Functions
static int tape_snapshot_write_t64image_module (snapshot_t *s)
static int tape_snapshot_read_t64image_module (snapshot_t *s)
static int tape_snapshot_write_tapimage_module (int port, snapshot_t *s)
static int tape_snapshot_read_tapimage_module (int port, snapshot_t *s)
int tape_snapshot_write_module (int port, snapshot_t *s, int save_image)
int tape_snapshot_read_module (int port, snapshot_t *s)
Variables
static log_t tape_snapshot_log = ((log_t)-1)
Logging.
static const char snap_module_name [] = "TAPE"
Macro Definition Documentation
T64IMAGE_SNAP_MAJOR
#define T64IMAGE_SNAP_MAJOR 1
T64IMAGE_SNAP_MINOR
#define T64IMAGE_SNAP_MINOR 0
TAPE_SNAP_MAJOR
#define TAPE_SNAP_MAJOR 1
TAPE_SNAP_MINOR
#define TAPE_SNAP_MINOR 0
TAPIMAGE_SNAP_MAJOR
#define TAPIMAGE_SNAP_MAJOR 1
TAPIMAGE_SNAP_MINOR
#define TAPIMAGE_SNAP_MINOR 0
Function Documentation
tape_snapshot_read_module()
int tape_snapshot_read_module (int port, snapshot_t * s)
tape_snapshot_read_t64image_module()
static int tape_snapshot_read_t64image_module (snapshot_t * s) static
Referenced by tape_snapshot_read_module().
tape_snapshot_read_tapimage_module()
static int tape_snapshot_read_tapimage_module (int port, snapshot_t * s) static
Todo:
FIXME: Were is this file deleted?
< write mode (binary)
Referenced by tape_snapshot_read_module().
tape_snapshot_write_module()
int tape_snapshot_write_module (int port, snapshot_t * s, int save_image)
tape_snapshot_write_t64image_module()
static int tape_snapshot_write_t64image_module (snapshot_t * s) static
Referenced by tape_snapshot_write_module().
tape_snapshot_write_tapimage_module()
static int tape_snapshot_write_tapimage_module (int port, snapshot_t * s) static
Referenced by tape_snapshot_write_module().
Variable Documentation
snap_module_name
const char snap_module_name[] = "TAPE" static
Referenced by tape_snapshot_read_module(), and tape_snapshot_write_module().
tape_snapshot_log
log_t tape_snapshot_log = ((log_t)-1) static
Logging.
Referenced by tape_snapshot_read_module(), tape_snapshot_read_t64image_module(), tape_snapshot_read_tapimage_module(), tape_snapshot_write_t64image_module(), and tape_snapshot_write_tapimage_module().