vsid: gfxoutputdrv/iffdrv.c File Reference
iffdrv.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "archdep.h"
#include "iffdrv.h"
#include "lib.h"
#include "log.h"
#include "gfxoutput.h"
#include "palette.h"
#include "screenshot.h"
#include "types.h"
#include "util.h"
Data Structures
struct gfxoutputdrv_data_s
Typedefs
typedef struct gfxoutputdrv_data_s gfxoutputdrv_data_t
Functions
static int iffdrv_write_file_header (screenshot_t *screenshot)
static int iffdrv_open (screenshot_t *screenshot, const char *filename)
static void iff_c2p (uint8_t *chunky, uint8_t *planar, int amount, int plane)
static int iffdrv_write (screenshot_t *screenshot)
static int iffdrv_close (screenshot_t *screenshot)
static int iffdrv_save (screenshot_t *screenshot, const char *filename)
void gfxoutput_init_iff (int help)
Variables
static gfxoutputdrv_t iff_drv
static uint8_t powers [8] = { 1, 2, 4, 8, 16, 32, 64, 128 }
Typedef Documentation
gfxoutputdrv_data_t
typedef struct gfxoutputdrv_data_s gfxoutputdrv_data_t
Function Documentation
gfxoutput_init_iff()
void gfxoutput_init_iff (int help)
Referenced by gfxoutput_early_init().
iff_c2p()
static void iff_c2p (uint8_t * chunky, uint8_t * planar, int amount, int plane) static
Referenced by iffdrv_write().
iffdrv_close()
static int iffdrv_close (screenshot_t * screenshot) static
Referenced by iffdrv_save().
iffdrv_open()
static int iffdrv_open (screenshot_t * screenshot, const char * filename) static
Referenced by iffdrv_save().
iffdrv_save()
static int iffdrv_save (screenshot_t * screenshot, const char * filename) static
iffdrv_write()
static int iffdrv_write (screenshot_t * screenshot) static
Referenced by iffdrv_save().
iffdrv_write_file_header()
static int iffdrv_write_file_header (screenshot_t * screenshot) static
Referenced by iffdrv_open().
Variable Documentation
iff_drv
static gfxoutputdrv_t iff_drv static
Initial value:
=
{
    GFXOUTPUTDRV_TYPE_SCREENSHOT_IMAGE,
    "IFF",
    "IFF screenshot",
    "iff",
    NULL,
    iffdrv_open,
    iffdrv_close,
    iffdrv_write,
    iffdrv_save,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
}
Referenced by gfxoutput_init_iff(), and iffdrv_open().
powers
uint8_t powers[8] = { 1, 2, 4, 8, 16, 32, 64, 128 } static
Referenced by iff_c2p().