x128: sha1.c File Reference
sha1.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "sha1.h"
Macros
#define SHA1HANDSOFF
Copies data before messing with it.
#define SHA1HANDSOFF
Copies data before messing with it.
#define rol(value, bits) (((value) << (bits)) | ((value) >> (32 - (bits))))
for uint32_t
#define blk0(i)
blk0() and blk() perform the initial expand.
#define blk(i)
#define R0(v, w, x, y, z, i) z+=((w&(x^y))^y)+blk0(i)+0x5A827999+rol(v,5);w=rol(w,30);
(R0+R1), R2, R3, R4 are the different operations used in SHA1
#define R1(v, w, x, y, z, i) z+=((w&(x^y))^y)+blk(i)+0x5A827999+rol(v,5);w=rol(w,30);
#define R2(v, w, x, y, z, i) z+=(w^x^y)+blk(i)+0x6ED9EBA1+rol(v,5);w=rol(w,30);
#define R3(v, w, x, y, z, i) z+=(((w|x)&y)|(w&x))+blk(i)+0x8F1BBCDC+rol(v,5);w=rol(w,30);
#define R4(v, w, x, y, z, i) z+=(w^x^y)+blk(i)+0xCA62C1D6+rol(v,5);w=rol(w,30);
Functions
static void SHA1TransformPtr (uint32_t state[5], const unsigned char *buffer)
Hash a single 512-bit block.
void SHA1Transform (uint32_t state[5], const unsigned char buffer[64])
void SHA1Init (SHA1_CTX *context)
SHA1Init - Initialize new context.
void SHA1Update (SHA1_CTX *context, const unsigned char *data, uint32_t len)
Run your data through this.
void SHA1Final (unsigned char digest[20], SHA1_CTX *context)
Add padding and return the message digest.
void SHA1 (unsigned char *hash_out, const unsigned char *str, uint32_t len)
void SHA1String (char *hash_string_out, const unsigned char *str, uint32_t len)
Macro Definition Documentation
blk
#define blk (i)
Value:
    (block->l[i&15] = rol(block->l[(i+13)&15]^block->l[(i+8)&15] \
    ^block->l[(i+2)&15]^block->l[i&15],1))
blk0
#define blk0 (i)
Value:
    (block->l[i] = (rol(block->l[i],24)&0xFF00FF00) \
    |(rol(block->l[i],8)&0x00FF00FF))
blk0() and blk() perform the initial expand.
I got the idea of expanding during the round function from SSLeay
R0
#define R0 (v, w, x, y, z, i) z+=((w&(x^y))^y)+blk0(i)+0x5A827999+rol(v,5);w=rol(w,30);
(R0+R1), R2, R3, R4 are the different operations used in SHA1
R1
#define R1 (v, w, x, y, z, i) z+=((w&(x^y))^y)+blk(i)+0x5A827999+rol(v,5);w=rol(w,30);
R2
#define R2 (v, w, x, y, z, i) z+=(w^x^y)+blk(i)+0x6ED9EBA1+rol(v,5);w=rol(w,30);
R3
#define R3 (v, w, x, y, z, i) z+=(((w|x)&y)|(w&x))+blk(i)+0x8F1BBCDC+rol(v,5);w=rol(w,30);
R4
#define R4 (v, w, x, y, z, i) z+=(w^x^y)+blk(i)+0xCA62C1D6+rol(v,5);w=rol(w,30);
rol
#define rol (value, bits) (((value) << (bits)) | ((value) >> (32 - (bits))))
for uint32_t
SHA1HANDSOFF [1/2]
#define SHA1HANDSOFF
Copies data before messing with it.
SHA1HANDSOFF [2/2]
#define SHA1HANDSOFF
Copies data before messing with it.
Function Documentation
SHA1()
void SHA1 (unsigned char * hash_out, const unsigned char * str, uint32_t len)
Referenced by SHA1String().
SHA1Final()
void SHA1Final (unsigned char digest[20], SHA1_CTX * context)
Add padding and return the message digest.
Referenced by SHA1().
SHA1Init()
void SHA1Init (SHA1_CTX * context)
SHA1Init - Initialize new context.
Referenced by SHA1().
SHA1String()
void SHA1String (char * hash_string_out, const unsigned char * str, uint32_t len)
SHA1Transform()
void SHA1Transform (uint32_t state[5], const unsigned char buffer[64])
Referenced by SHA1Update().
SHA1TransformPtr()
static void SHA1TransformPtr (uint32_t state[5], const unsigned char * buffer) static
Hash a single 512-bit block.
This is the core of the algorithm.
Referenced by SHA1Transform().
SHA1Update()
void SHA1Update (SHA1_CTX * context, const unsigned char * data, uint32_t len)
Run your data through this.
Referenced by SHA1(), and SHA1Final().