vsid: arch/gtk3/widgets/cbm2memorysizewidget.c File Reference
cbm2memorysizewidget.c File Reference
CBM-II memory size widget.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "machine.h"
#include "resources.h"
#include "cbm2memorysizewidget.h"
Functions
GtkWidget * cbm2_memory_size_widget_create (void)
Create CBM-II memory size widget.
void cbm2_memory_size_widget_set_callback (GtkWidget *widget, void(*callback)(GtkWidget *, int))
Set used-defined callback to trigger when the RAM size changes.
void cbm2_memory_size_widget_update (GtkWidget *widget)
Update/sync widget via its resource.
Variables
static const vice_gtk3_radiogroup_entry_t ram_sizes_cbm5x0 []
List of RAM sizes for 5x0 in KiB.
static const vice_gtk3_radiogroup_entry_t ram_sizes_cbm6x0 []
List of RAM sizes for 6x0/7x0 in KiB.
Detailed Description
CBM-II memory size widget.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
cbm2_memory_size_widget_create()
GtkWidget * cbm2_memory_size_widget_create (void)
Create CBM-II memory size widget.
Returns
GtkGrid
Referenced by create_cbm5x0_layout(), and create_cbm6x0_layout().
cbm2_memory_size_widget_set_callback()
void cbm2_memory_size_widget_set_callback (GtkWidget * widget, void(*)(GtkWidget *, int) callback)
Set used-defined callback to trigger when the RAM size changes.
Parameters
[in,out] widget cbm2 memory size widget
[in] callback user-defined callback
Referenced by create_cbm5x0_layout(), and create_cbm6x0_layout().
cbm2_memory_size_widget_update()
void cbm2_memory_size_widget_update (GtkWidget * widget)
Update/sync widget via its resource.
Parameters
[in] widget cbm2 memory size widget
Referenced by machine_model_handler_cbm5x0(), and machine_model_handler_cbm6x0().
Variable Documentation
ram_sizes_cbm5x0
const vice_gtk3_radiogroup_entry_t ram_sizes_cbm5x0[] static
Initial value:
= {
    { "64KiB",     64 },
    { "128KiB",   128 },
    { "256KiB",   256 },
    { "512KiB",   512 },
    { "1024KiB", 1024 },
    { NULL,        -1 }
}
List of RAM sizes for 5x0 in KiB.
Referenced by cbm2_memory_size_widget_create().
ram_sizes_cbm6x0
const vice_gtk3_radiogroup_entry_t ram_sizes_cbm6x0[] static
Initial value:
= {
    { "128KiB",   128 },
    { "256KiB",   256 },
    { "512KiB",   512 },
    { "1024KiB", 1024 },
    { NULL,        -1 }
}
List of RAM sizes for 6x0/7x0 in KiB.
Referenced by cbm2_memory_size_widget_create().