vsid: arch/gtk3/widgets/settings_controlport.c File Reference
settings_controlport.c File Reference
Widget to control settings for control ports.
#include "vice.h"
#include <gtk/gtk.h>
#include "joyport.h"
#include "lib.h"
#include "machine.h"
#include "resources.h"
#include "vice_gtk3.h"
#include "settings_controlport.h"
Functions
static void update_adapter_ports_visibility (GtkGrid *grid, int row)
Update visibility of adapter port widgets.
static void on_control_port_changed (GtkWidget *widget, gpointer data)
Handler for the 'changed' event of the control port combo boxes.
static GtkWidget * create_joyport_combo (int port)
Create combo box for joy port device.
static GtkWidget * create_joyport_widget (int port, const char *title)
Create combo box for joyport port.
static int layout_add_control_ports (GtkGrid *layout, int row, int count)
Add widgets for the control ports.
static int layout_add_adapter_ports (GtkGrid *layout, int row, int count)
Add widgets for the joystick adapter ports.
static int layout_add_sidcard_port (GtkGrid *layout, int row)
Add widget for the Plus4 SIDCart joystick port.
static int layout_add_bbrtc_widget (GtkGrid *layout, int row)
Add checkbox for the battery-backed RTC save option.
static int layout_add_smartmouse_rtc_widget (GtkGrid *layout, int row)
Add checkbox for the SmartMouse RTC save option.
static int layout_add_ps2mouse_widget (GtkGrid *layout, int row)
Add checkbox for the userport PS/2 mouse.
static int create_c64_layout (GtkGrid *layout)
Create layout for x64, x64sc, xscpu64 and x128.
static int create_c64dtv_layout (GtkGrid *layout)
Create layout for x64dtv.
static int create_vic20_layout (GtkGrid *layout)
Create layout for xvic.
static int create_plus4_layout (GtkGrid *layout)
Create layout for xplus4.
static int create_pet_layout (GtkGrid *layout)
Create layout for xpet.
static int create_cbm5x0_layout (GtkGrid *layout)
Create layout for xcbm5x0.
static int create_cbm6x0_layout (GtkGrid *layout)
Create layout for xcbm2.
GtkWidget * settings_controlport_widget_create (GtkWidget *parent)
Create widget to control control ports.
Variables
static GtkWidget * control_port_1_combo = NULL
Resource combo box for control port #1.
static GtkWidget * control_port_2_combo = NULL
Resource combo box for control port #2.
Detailed Description
Widget to control settings for control ports.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
create_c64_layout()
static int create_c64_layout (GtkGrid * layout) static
Create layout for x64, x64sc, xscpu64 and x128.
Two control ports and eight joystick adapter ports.
Parameters
[in,out] layout main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_controlport_widget_create().
create_c64dtv_layout()
static int create_c64dtv_layout (GtkGrid * layout) static
Create layout for x64dtv.
Two control ports and eight joystick adapter ports.
Parameters
[in,out] layout main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_controlport_widget_create().
create_cbm5x0_layout()
static int create_cbm5x0_layout (GtkGrid * layout) static
Create layout for xcbm5x0.
Two control ports and eight joystick adapter ports.
Parameters
[in,out] layout main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_controlport_widget_create().
create_cbm6x0_layout()
static int create_cbm6x0_layout (GtkGrid * layout) static
Create layout for xcbm2.
Eight joystick adapter ports.
Parameters
[in,out] layout main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_controlport_widget_create().
create_joyport_combo()
static GtkWidget * create_joyport_combo (int port) static
Create combo box for joy port device.
Parameters
[in] port index in devices, add 1 for JoyPort[n]Device
Returns
GtkComboBox
Referenced by create_joyport_widget().
create_joyport_widget()
static GtkWidget * create_joyport_widget (int port, const char * title) static
Create combo box for joyport port.
Parameters
[in] port Joyport number (0-4, 0 == JoyPort1Device)
[in] title widget title
Returns
GtkGrid
Referenced by layout_add_adapter_ports(), layout_add_control_ports(), and layout_add_sidcard_port().
create_pet_layout()
static int create_pet_layout (GtkGrid * layout) static
Create layout for xpet.
Two userport adapter ports.
Parameters
[in,out] layout main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_controlport_widget_create().
create_plus4_layout()
static int create_plus4_layout (GtkGrid * layout) static
Create layout for xplus4.
Two control ports, two userport adapter ports and one SIDCard control port.
Parameters
[in,out] layout main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_controlport_widget_create().
create_vic20_layout()
static int create_vic20_layout (GtkGrid * layout) static
Create layout for xvic.
One control port and eight joystick adapter ports.
Parameters
[in,out] layout main widget grid
Returns
row in the layout for additional widgets
Referenced by settings_controlport_widget_create().
layout_add_adapter_ports()
static int layout_add_adapter_ports (GtkGrid * layout, int row, int count) static
Add widgets for the joystick adapter ports.
Adds count widgets to select the emulated device for the adapter ports.
Only the widgets for active adapter ports (according to current configuration) will be shown. The function update_adapter_ports_visibility() is used when the control port devices change to update the adapter port widgets' visibility due to a changed configuration.
Parameters
[in,out] layout main widget grid
[in] row starting row in layout
[in] count number of widgets to add to layout
Returns
row in the layout for additional widgets
Referenced by create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), create_pet_layout(), create_plus4_layout(), and create_vic20_layout().
layout_add_bbrtc_widget()
static int layout_add_bbrtc_widget (GtkGrid * layout, int row) static
Add checkbox for the battery-backed RTC save option.
Add a checkbox for the "BBRTCSave" resource.
Parameters
[in,out] layout main widget grid
[in] row row in layout to add the checkbox
Returns
row in the layout for additional widgets
Note
the added widget spans two columns in the layout
Referenced by create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_cbm6x0_layout(), create_pet_layout(), create_plus4_layout(), and create_vic20_layout().
layout_add_control_ports()
static int layout_add_control_ports (GtkGrid * layout, int row, int count) static
Add widgets for the control ports.
Adds count comboboxes to select the emulated device for the control ports.
We don't use joyport_port_is_active() here due to the number of control ports for a specific machine being fixed.
Parameters
[in,out] layout main widget grid
[in] row starting row in layout
[in] count number of widgets to add to layout
Returns
row in the layout for additional widgets
Referenced by create_c64_layout(), create_c64dtv_layout(), create_cbm5x0_layout(), create_plus4_layout(), and create_vic20_layout().
layout_add_ps2mouse_widget()
static int layout_add_ps2mouse_widget (GtkGrid * layout, int row) static
Add checkbox for the userport PS/2 mouse.
Add a checkbox for the "ps2mouse" resource.
Valid for x64dtv.
Parameters
[in,out] layout main widget grid
[in] row row in layout to add the checkbox
Returns
row in the layout for additional widgets
Note
the added widget spans two columns in the layout
Referenced by create_c64dtv_layout().
layout_add_sidcard_port()
static int layout_add_sidcard_port (GtkGrid * layout, int row) static
Add widget for the Plus4 SIDCart joystick port.
Adds a widget for the Plus4-specific SIDCard extra joystick port.
Currently the resource "JoyPort5Device" is used for this widget, but once eight adapter ports are implemented for Plus4 like the other emulators, we probably should switch the widget to "JoyPort11Device".
Parameters
[in,out] layout main widget grid
[in] row starting row in layout
Returns
row in the layout for additional widgets
Referenced by create_plus4_layout().
layout_add_smartmouse_rtc_widget()
static int layout_add_smartmouse_rtc_widget (GtkGrid * layout, int row) static
Add checkbox for the SmartMouse RTC save option.
Add a checkbox for the "SmartMouseRTCSave" resource.
Valid for x64, x64sc, xscpu64, x128, xcbm5x0 and xvic.
Parameters
[in,out] layout main widget grid
[in] row row in layout to add the checkbox
Returns
row in the layout for additional widgets
Note
the added widget spans two columns in the layout
Referenced by create_c64_layout(), create_cbm5x0_layout(), and create_vic20_layout().
on_control_port_changed()
static void on_control_port_changed (GtkWidget * widget, gpointer data) static
Handler for the 'changed' event of the control port combo boxes.
Parameters
[in] widget control port widget's combo box
[in] data row in grid of the first adapter port widget
Referenced by layout_add_control_ports(), and on_control_port_changed().
settings_controlport_widget_create()
GtkWidget * settings_controlport_widget_create (GtkWidget * parent)
Create widget to control control ports.
Creates a widget to control the settings for the control ports, userport joystick adapter ports and the SIDCard control port, depending on the currently emulated machine.
Parameters
[in] parent parent widget (unused)
Returns
GtkGrid
update_adapter_ports_visibility()
static void update_adapter_ports_visibility (GtkGrid * grid, int row) static
Update visibility of adapter port widgets.
Show/hide adapter port widgets based on current configuration.
Parameters
[in] grid Grid containing all the widgets
[in] row row in grid of the first adapter port widget
Referenced by on_control_port_changed().
Variable Documentation
control_port_1_combo
GtkWidget* control_port_1_combo = NULL static
Resource combo box for control port #1.
Referenced by layout_add_control_ports(), and on_control_port_changed().
control_port_2_combo
GtkWidget* control_port_2_combo = NULL static
Resource combo box for control port #2.
Referenced by layout_add_control_ports(), and on_control_port_changed().