x128: fsdevice/fsdevice-read.c File Reference
fsdevice-read.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "archdep.h"
#include "cbmdos.h"
#include "fileio.h"
#include "fsdevice-filename.h"
#include "fsdevice-resources.h"
#include "fsdevicetypes.h"
#include "lib.h"
#include "tape.h"
#include "types.h"
#include "vdrive.h"
#include "fsdevice-read.h"
Macros
#define DBG(x)
Functions
static int command_read (bufinfo_t *bufinfo, uint8_t *data)
void fsdevice_relative_pad_record (bufinfo_t *bufinfo)
int fsdevice_relative_switch_record (vdrive_t *vdrive, bufinfo_t *bufinfo, int record, int pos)
static int relative_read (vdrive_t *vdrive, bufinfo_t *bufinfo, uint8_t *data)
static void command_directory_get (vdrive_t *vdrive, bufinfo_t *bufinfo, uint8_t *data, unsigned int secondary)
static int command_directory (vdrive_t *vdrive, bufinfo_t *bufinfo, uint8_t *data, unsigned int secondary)
int fsdevice_read (vdrive_t *vdrive, uint8_t *data, unsigned int secondary)
Macro Definition Documentation
DBG
#define DBG (x)
Function Documentation
command_directory()
static int command_directory (vdrive_t * vdrive, bufinfo_t * bufinfo, uint8_t * data, unsigned int secondary) static
Referenced by fsdevice_read().
command_directory_get()
static void command_directory_get (vdrive_t * vdrive, bufinfo_t * bufinfo, uint8_t * data, unsigned int secondary) static
< works with directories
< directory separator as a string
< should match FILEIO_TYPE_xxx
Referenced by command_directory().
command_read()
static int command_read (bufinfo_t * bufinfo, uint8_t * data) static
Referenced by fsdevice_read().
fsdevice_read()
int fsdevice_read (vdrive_t * vdrive, uint8_t * data, unsigned int secondary)
Referenced by fsdevice_attach().
fsdevice_relative_pad_record()
void fsdevice_relative_pad_record (bufinfo_t * bufinfo)
Referenced by fsdevice_close(), and fsdevice_relative_switch_record().
fsdevice_relative_switch_record()
int fsdevice_relative_switch_record (vdrive_t * vdrive, bufinfo_t * bufinfo, int record, int pos)
Referenced by fsdevice_flush_position(), fsdevice_open_file(), fsdevice_rel_listen(), and relative_read().
relative_read()
static int relative_read (vdrive_t * vdrive, bufinfo_t * bufinfo, uint8_t * data) static
Referenced by fsdevice_read().