x128: c128/cart/partner128.c File Reference
partner128.c File Reference
#include "vice.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cartridge.h"
#include "cartio.h"
#include "util.h"
#include "maincpu.h"
#include "monitor.h"
#include "c128memrom.h"
#include "c64cart.h"
#include "export.h"
#include "c128cart.h"
#include "functionrom.h"
#include "crt.h"
#include "partner128.h"
Macros
#define DBG(x)
#define PARTNER_ROM_SIZE 0x4000
#define PARTNER_RAM_SIZE (64 * 128)
64 * 128bytes
#define SNAP_MAJOR 0
#define SNAP_MINOR 0
Functions
static uint8_t partner128_io1_peek (uint16_t addr)
some prototypes are needed
static uint8_t partner128_io1_read (uint16_t addr)
static void partner128_io1_store (uint16_t addr, uint8_t value)
static uint8_t partner128_iod6_peek (uint16_t addr)
static void partner128_iod6_store (uint16_t addr, uint8_t value)
static int partner128_dump (void)
static void nmivector_save (void)
static void nmivector_patch (void)
static void nmivector_restore (void)
void partner128_config_setup (uint8_t *rawcart)
static int partner128_common_attach (void)
int partner128_bin_attach (const char *filename, uint8_t *rawcart)
int partner128_crt_attach (FILE *fd, uint8_t *rawcart)
void partner128_detach (void)
void partner128_reset (void)
void partner128_freeze (void)
void partner128_powerup (void)
int partner128_snapshot_write_module (snapshot_t *s)
int partner128_snapshot_read_module (snapshot_t *s)
Variables
static uint8_t regvalue = 0
static uint8_t rambank = 0
static uint8_t isdefreezing = 0
static uint8_t rambanks [(64 *128)]
static uint8_t nmivector [2] = { 0, 0 }
static io_source_t partner128_io1_device
static io_source_list_t * partner128_io1_list_item = NULL
static io_source_t partner128_iod6_device
static io_source_list_t * partner128_iod6_list_item = NULL
static const export_resource_t export_res
static char snap_module_name [] = "PARTNER128"
Macro Definition Documentation
DBG
#define DBG (x)
PARTNER_RAM_SIZE
#define PARTNER_RAM_SIZE (64 * 128)
64 * 128bytes
PARTNER_ROM_SIZE
#define PARTNER_ROM_SIZE 0x4000
SNAP_MAJOR
#define SNAP_MAJOR 0
SNAP_MINOR
#define SNAP_MINOR 0
Function Documentation
nmivector_patch()
static void nmivector_patch (void) static
Referenced by partner128_freeze().
nmivector_restore()
static void nmivector_restore (void) static
Referenced by partner128_detach(), partner128_io1_store(), partner128_powerup(), and partner128_reset().
nmivector_save()
static void nmivector_save (void) static
Referenced by partner128_freeze().
partner128_bin_attach()
int partner128_bin_attach (const char * filename, uint8_t * rawcart)
Referenced by c128cartridge_bin_attach().
partner128_common_attach()
static int partner128_common_attach (void) static
Referenced by partner128_bin_attach(), partner128_crt_attach(), and partner128_snapshot_read_module().
partner128_config_setup()
void partner128_config_setup (uint8_t * rawcart)
Referenced by c128cartridge_config_setup().
partner128_crt_attach()
int partner128_crt_attach (FILE * fd, uint8_t * rawcart)
Referenced by c128cartridge_attach_crt().
partner128_detach()
void partner128_detach (void)
Referenced by c128cartridge_detach_image().
partner128_dump()
static int partner128_dump (void) static
partner128_freeze()
void partner128_freeze (void)
Referenced by c128cartridge_freeze().
partner128_io1_peek()
static uint8_t partner128_io1_peek (uint16_t addr) static
some prototypes are needed
partner128_io1_read()
static uint8_t partner128_io1_read (uint16_t addr) static
partner128_io1_store()
static void partner128_io1_store (uint16_t addr, uint8_t value) static
DBG(("partner128_io1_store %04x %02x\n", addr, value));
partner128_iod6_peek()
static uint8_t partner128_iod6_peek (uint16_t addr) static
partner128_iod6_store()
static void partner128_iod6_store (uint16_t addr, uint8_t value) static
partner128_powerup()
void partner128_powerup (void)
< 64 * 128bytes
Referenced by c128cartridge_powerup().
partner128_reset()
void partner128_reset (void)
Referenced by c128cartridge_reset().
partner128_snapshot_read_module()
int partner128_snapshot_read_module (snapshot_t * s)
Referenced by c128cartridge_snapshot_read().
partner128_snapshot_write_module()
int partner128_snapshot_write_module (snapshot_t * s)
Referenced by c128cartridge_snapshot_write().
Variable Documentation
export_res
const export_resource_t export_res static
Initial value:
= {
     "Partner 128" , 1, 1, &partner128_io1_device, NULL, ((  2  ) +  ( 79   + 1) )
}
Referenced by partner128_common_attach(), and partner128_detach().
isdefreezing
uint8_t isdefreezing = 0 static
Referenced by partner128_dump(), partner128_io1_store(), partner128_powerup(), and partner128_reset().
nmivector
uint8_t nmivector[2] = { 0, 0 } static
Referenced by nmivector_restore(), and nmivector_save().
partner128_io1_device
io_source_t partner128_io1_device static
Initial value:
= {
     "Partner 128" ,
     0 ,
     NULL ,
    0xde00, 0xdeff, 0xff,
    1,
    partner128_io1_store,
    NULL,
    partner128_io1_read,
    partner128_io1_peek,
    partner128_dump,
    ((  2  ) +  ( 79   + 1) ) ,
     0  ,
    0,
     0
}
Referenced by partner128_common_attach().
partner128_io1_list_item
io_source_list_t* partner128_io1_list_item = NULL static
Referenced by partner128_common_attach(), and partner128_detach().
partner128_iod6_device
io_source_t partner128_iod6_device static
Initial value:
= {
     "Partner 128" ,
     0 ,
     NULL ,
    0xd600, 0xd60f, 0x0f,
    0,
    partner128_iod6_store,
    NULL,
    NULL,
    partner128_iod6_peek,
    partner128_dump,
    ((  2  ) +  ( 79   + 1) ) ,
     0  ,
    0,
     0
}
Referenced by partner128_common_attach().
partner128_iod6_list_item
io_source_list_t* partner128_iod6_list_item = NULL static
Referenced by partner128_common_attach(), and partner128_detach().
rambank
uint8_t rambank = 0 static
Referenced by partner128_dump(), partner128_io1_peek(), partner128_io1_read(), partner128_io1_store(), partner128_iod6_peek(), partner128_iod6_store(), partner128_powerup(), and partner128_reset().
rambanks
uint8_t rambanks[(64 *128)] static
Referenced by partner128_io1_peek(), partner128_io1_read(), partner128_io1_store(), partner128_iod6_peek(), partner128_iod6_store(), and partner128_powerup().
regvalue
uint8_t regvalue = 0 static
Referenced by partner128_dump(), partner128_io1_store(), partner128_powerup(), and partner128_reset().
snap_module_name
char snap_module_name[] = "PARTNER128" static
Referenced by partner128_snapshot_read_module(), and partner128_snapshot_write_module().