x128: vicii/vicii-color.c File Reference
vicii-color.c File Reference
#include "vice.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "vicii.h"
#include "viciitypes.h"
#include "vicii-color.h"
#include "vicii-resources.h"
#include "video.h"
Macros
#define TOBIAS_COLORS
undefine for the old "idealized" Pepto colors
#define SEPERATE_ODD_EVEN_COLORS
undefine to use seperate palettes for odd/even lines
Functions
int vicii_color_update_palette (struct video_canvas_s *canvas)
Variables
static video_cbm_color_t vicii_colors_6569r1 [16]
static video_cbm_color_t vicii_colors_6569r1_even [16]
static video_cbm_color_t vicii_colors_6569r1_odd [16]
static video_cbm_palette_t vicii_palette_6569r1
static video_cbm_color_t vicii_colors_6569r5 [16]
static video_cbm_color_t vicii_colors_6569r5_even [16]
static video_cbm_color_t vicii_colors_6569r5_odd [16]
static video_cbm_palette_t vicii_palette_6569r5
static video_cbm_color_t vicii_colors_8565r2 [16]
static video_cbm_color_t vicii_colors_8565r2_even [16]
static video_cbm_color_t vicii_colors_8565r2_odd [16]
static video_cbm_palette_t vicii_palette_8565r2
Macro Definition Documentation
SEPERATE_ODD_EVEN_COLORS
#define SEPERATE_ODD_EVEN_COLORS
undefine to use seperate palettes for odd/even lines
TOBIAS_COLORS
#define TOBIAS_COLORS
undefine for the old "idealized" Pepto colors
undefine for the new "idealized" Pepto colors, aka "colodore"
undefine for extra colors that use markos measured lumas
undefine for the colors measured by Tobias
Function Documentation
vicii_color_update_palette()
int vicii_color_update_palette (struct video_canvas_s * canvas)
FIXME
Referenced by init_raster(), set_new_luminances(), and vicii_change_timing().
Variable Documentation
vicii_colors_6569r1
video_cbm_color_t vicii_colors_6569r1[16] static
Initial value:
=
{
    { 0.000 * 256.0,           0.00        , 0.000 * 256.0, -0, "Black"       },
    { 1.000 * 256.0,           0.00        , 0.000 * 256.0,  0, "White"       },
    { 0.237 * 256.0,          95.50        , 0.217 * 256.0,  1, "Red"         },
    { 0.763 * 256.0,         275.50 - 180.0, 0.210 * 256.0, -1, "Cyan"        },
    { 0.500 * 256.0,          54.00 - 180.0, 0.219 * 256.0, -1, "Purple"      },
    { 0.500 * 256.0,         241.70        , 0.213 * 256.0,  1, "Green"       },
    { 0.237 * 256.0,         355.60 - 360.0, 0.217 * 256.0,  1, "Blue"        },
    { 0.763 * 256.0,         175.60 - 180.0, 0.211 * 256.0, -1, "Yellow"      },
    { 0.500 * 256.0,         128.25 - 180.0, 0.217 * 256.0, -1, "Orange"      },
    { 0.237 * 256.0,         146.50        , 0.214 * 256.0,  1, "Brown"       },
    { 0.500 * 256.0,          95.50        , 0.217 * 256.0,  1, "Light Red"   },
    { 0.237 * 256.0,           0.00        , 0.000 * 256.0, -0, "Dark Grey"   },
    { 0.500 * 256.0,           0.00        , 0.000 * 256.0, -0, "Medium Grey" },
    { 0.763 * 256.0,         241.70 - 360.0, 0.213 * 256.0,  1, "Light Green" },
    { 0.500 * 256.0,         355.60 - 360.0, 0.217 * 256.0,  1, "Light Blue"  },
    { 0.763 * 256.0,           0.00        , 0.000 * 256.0,  0, "Light Grey"  }
}
vicii_colors_6569r1_even
video_cbm_color_t vicii_colors_6569r1_even[16] static
Initial value:
=
{
    { 0.000 * 256.0,           0.00        , 0.000 * 256.0, -0, "Black"       },
    { 1.000 * 256.0,           0.00        , 0.000 * 256.0,  0, "White"       },
    { 0.237 * 256.0,          89.00        , 0.202 * 256.0,  1, "Red"         },
    { 0.763 * 256.0,         269.25 - 180.0, 0.191 * 256.0, -1, "Cyan"        },
    { 0.500 * 256.0,          48.50 - 180.0, 0.226 * 256.0, -1, "Purple"      },
    { 0.500 * 256.0,         235.45        , 0.222 * 256.0,  1, "Green"       },
    { 0.237 * 256.0,         -12.40 - 360.0, 0.234 * 256.0,  1, "Blue"        },
    { 0.763 * 256.0,         168.60 - 180.0, 0.231 * 256.0, -1, "Yellow"      },
    { 0.500 * 256.0,         122.00 - 180.0, 0.213 * 256.0, -1, "Orange"      },
    { 0.237 * 256.0,         140.00        , 0.226 * 256.0,  1, "Brown"       },
    { 0.500 * 256.0,          89.00        , 0.202 * 256.0,  1, "Light Red"   },
    { 0.237 * 256.0,           0.00        , 0.000 * 256.0, -0, "Dark Grey"   },
    { 0.500 * 256.0,           0.00        , 0.000 * 256.0, -0, "Medium Grey" },
    { 0.763 * 256.0,         235.45 - 360.0, 0.222 * 256.0,  1, "Light Green" },
    { 0.500 * 256.0,         -12.40 - 360.0, 0.234 * 256.0,  1, "Light Blue"  },
    { 0.763 * 256.0,           0.00        , 0.000 * 256.0, -0, "Light Grey"  }
}
vicii_colors_6569r1_odd
video_cbm_color_t vicii_colors_6569r1_odd[16] static
Initial value:
=
{
    { 0.000 * 256.0,           0.00        , 0.000 * 256.0, -0, "Black"       },
    { 1.000 * 256.0,           0.00        , 0.000 * 256.0,  0, "White"       },
    { 0.237 * 256.0,         102.00        , 0.232 * 256.0,  1, "Red"         },
    { 0.763 * 256.0,         281.75 - 180.0, 0.228 * 256.0, -1, "Cyan"        },
    { 0.500 * 256.0,          59.50 - 180.0, 0.211 * 256.0, -1, "Purple"      },
    { 0.500 * 256.0,         247.95        , 0.205 * 256.0,  1, "Green"       },
    { 0.237 * 256.0,         363.60 - 360.0, 0.200 * 256.0,  1, "Blue"        },
    { 0.763 * 256.0,         182.60 - 180.0, 0.191 * 256.0, -1, "Yellow"      },
    { 0.500 * 256.0,         134.50 - 180.0, 0.221 * 256.0, -1, "Orange"      },
    { 0.237 * 256.0,         153.00        , 0.202 * 256.0,  1, "Brown"       },
    { 0.500 * 256.0,         102.00        , 0.232 * 256.0,  1, "Light Red"   },
    { 0.237 * 256.0,           0.00        , 0.000 * 256.0, -0, "Dark Grey"   },
    { 0.500 * 256.0,           0.00        , 0.000 * 256.0, -0, "Medium Grey" },
    { 0.763 * 256.0,         247.95 - 360.0, 0.205 * 256.0,  1, "Light Green" },
    { 0.500 * 256.0,         363.60 - 360.0, 0.200 * 256.0,  1, "Light Blue"  },
    { 0.763 * 256.0,           0.00        , 0.000 * 256.0, -0, "Light Grey"  }
}
vicii_colors_6569r5
video_cbm_color_t vicii_colors_6569r5[16] static
Initial value:
=
{
    { 0.000 * 256.0,           0.00        , 0.000 * 256.0, -0, "Black"       },
    { 1.000 * 256.0,           0.00        , 0.000 * 256.0,  0, "White"       },
    { 0.306 * 256.0,          95.50        , 0.217 * 256.0,  1, "Red"         },
    { 0.639 * 256.0,         275.50 - 180.0, 0.210 * 256.0, -1, "Cyan"        },
    { 0.363 * 256.0,          54.00 - 180.0, 0.219 * 256.0, -1, "Purple"      },
    { 0.500 * 256.0,         241.70        , 0.213 * 256.0,  1, "Green"       },
    { 0.237 * 256.0,         355.60 - 360.0, 0.217 * 256.0,  1, "Blue"        },
    { 0.763 * 256.0,         175.60 - 180.0, 0.211 * 256.0, -1, "Yellow"      },
    { 0.363 * 256.0,         128.25 - 180.0, 0.217 * 256.0, -1, "Orange"      },
    { 0.237 * 256.0,         146.50        , 0.214 * 256.0,  1, "Brown"       },
    { 0.500 * 256.0,          95.50        , 0.217 * 256.0,  1, "Light Red"   },
    { 0.306 * 256.0,           0.00        , 0.000 * 256.0, -0, "Dark Grey"   },
    { 0.461 * 256.0,           0.00        , 0.000 * 256.0, -0, "Medium Grey" },
    { 0.763 * 256.0,         241.70 - 360.0, 0.213 * 256.0,  1, "Light Green" },
    { 0.461 * 256.0,         355.60 - 360.0, 0.217 * 256.0,  1, "Light Blue"  },
    { 0.639 * 256.0,           0.00        , 0.000 * 256.0,  0, "Light Grey"  }
}
vicii_colors_6569r5_even
video_cbm_color_t vicii_colors_6569r5_even[16] static
Initial value:
=
{
    { 0.000 * 256.0,           0.00        , 0.000 * 256.0, -0, "Black"       },
    { 1.000 * 256.0,           0.00        , 0.000 * 256.0,  0, "White"       },
    { 0.306 * 256.0,          89.00        , 0.202 * 256.0,  1, "Red"         },
    { 0.639 * 256.0,         269.25 - 180.0, 0.191 * 256.0, -1, "Cyan"        },
    { 0.363 * 256.0,          48.50 - 180.0, 0.226 * 256.0, -1, "Purple"      },
    { 0.500 * 256.0,         235.45        , 0.222 * 256.0,  1, "Green"       },
    { 0.237 * 256.0,         -12.40 - 360.0, 0.234 * 256.0,  1, "Blue"        },
    { 0.763 * 256.0,         168.60 - 180.0, 0.231 * 256.0, -1, "Yellow"      },
    { 0.363 * 256.0,         122.00 - 180.0, 0.213 * 256.0, -1, "Orange"      },
    { 0.237 * 256.0,         140.00        , 0.226 * 256.0,  1, "Brown"       },
    { 0.500 * 256.0,          89.00        , 0.202 * 256.0,  1, "Light Red"   },
    { 0.306 * 256.0,           0.00        , 0.000 * 256.0, -0, "Dark Grey"   },
    { 0.461 * 256.0,           0.00        , 0.000 * 256.0, -0, "Medium Grey" },
    { 0.763 * 256.0,         235.45 - 360.0, 0.222 * 256.0,  1, "Light Green" },
    { 0.461 * 256.0,         -12.40 - 360.0, 0.234 * 256.0,  1, "Light Blue"  },
    { 0.639 * 256.0,           0.00        , 0.000 * 256.0, -0, "Light Grey"  }
}
vicii_colors_6569r5_odd
video_cbm_color_t vicii_colors_6569r5_odd[16] static
Initial value:
=
{
    { 0.000 * 256.0,           0.00        , 0.000 * 256.0, -0, "Black"       },
    { 1.000 * 256.0,           0.00        , 0.000 * 256.0,  0, "White"       },
    { 0.306 * 256.0,         102.00        , 0.232 * 256.0,  1, "Red"         },
    { 0.639 * 256.0,         281.75 - 180.0, 0.228 * 256.0, -1, "Cyan"        },
    { 0.363 * 256.0,          59.50 - 180.0, 0.211 * 256.0, -1, "Purple"      },
    { 0.500 * 256.0,         247.95        , 0.205 * 256.0,  1, "Green"       },
    { 0.237 * 256.0,         363.60 - 360.0, 0.200 * 256.0,  1, "Blue"        },
    { 0.763 * 256.0,         182.60 - 180.0, 0.191 * 256.0, -1, "Yellow"      },
    { 0.363 * 256.0,         134.50 - 180.0, 0.221 * 256.0, -1, "Orange"      },
    { 0.237 * 256.0,         153.00        , 0.202 * 256.0,  1, "Brown"       },
    { 0.500 * 256.0,         102.00        , 0.232 * 256.0,  1, "Light Red"   },
    { 0.306 * 256.0,           0.00        , 0.000 * 256.0, -0, "Dark Grey"   },
    { 0.461 * 256.0,           0.00        , 0.000 * 256.0, -0, "Medium Grey" },
    { 0.763 * 256.0,         247.95 - 360.0, 0.205 * 256.0,  1, "Light Green" },
    { 0.461 * 256.0,         363.60 - 360.0, 0.200 * 256.0,  1, "Light Blue"  },
    { 0.639 * 256.0,           0.00        , 0.000 * 256.0, -0, "Light Grey"  }
}
vicii_colors_8565r2
video_cbm_color_t vicii_colors_8565r2[16] static
Initial value:
=
{
    { 0.000 * 256.0,           0.00        , 0.000 * 256.0, -0, "Black"       },
    { 1.000 * 256.0,           0.00        , 0.000 * 256.0,  0, "White"       },
    { 0.306 * 256.0,         102.50        , 0.214 * 256.0,  1, "Red"         },
    { 0.639 * 256.0,         281.50 - 180.0, 0.216 * 256.0, -1, "Cyan"        },
    { 0.363 * 256.0,          51.00 - 180.0, 0.214 * 256.0, -1, "Purple"      },
    { 0.500 * 256.0,         238.70        , 0.214 * 256.0,  1, "Green"       },
    { 0.237 * 256.0,         345.10 - 360.0, 0.214 * 256.0,  1, "Blue"        },
    { 0.763 * 256.0,         165.10 - 180.0, 0.214 * 256.0, -1, "Yellow"      },
    { 0.363 * 256.0,         126.00 - 180.0, 0.213 * 256.0, -1, "Orange"      },
    { 0.237 * 256.0,         146.00        , 0.213 * 256.0,  1, "Brown"       },
    { 0.500 * 256.0,         102.50        , 0.214 * 256.0,  1, "Light Red"   },
    { 0.306 * 256.0,           0.00        , 0.000 * 256.0, -0, "Dark Grey"   },
    { 0.461 * 256.0,           0.00        , 0.000 * 256.0, -0, "Medium Grey" },
    { 0.763 * 256.0,         238.70 - 360.0, 0.214 * 256.0,  1, "Light Green" },
    { 0.461 * 256.0,         345.10 - 360.0, 0.214 * 256.0,  1, "Light Blue"  },
    { 0.639 * 256.0,           0.00        , 0.000 * 256.0,  0, "Light Grey"  }
}
vicii_colors_8565r2_even
video_cbm_color_t vicii_colors_8565r2_even[16] static
Initial value:
=
{
    { 0.000 * 256.0,           0.00        , 0.000 * 256.0, -0, "Black"       },
    { 1.000 * 256.0,           0.00        , 0.000 * 256.0,  0, "White"       },
    { 0.306 * 256.0,          93.50        , 0.212 * 256.0,  1, "Red"         },
    { 0.639 * 256.0,         273.00 - 180.0, 0.215 * 256.0, -1, "Cyan"        },
    { 0.363 * 256.0,          43.00 - 180.0, 0.214 * 256.0, -1, "Purple"      },
    { 0.500 * 256.0,         231.70        , 0.216 * 256.0,  1, "Green"       },
    { 0.237 * 256.0,         -24.40 - 360.0, 0.215 * 256.0,  1, "Blue"        },
    { 0.763 * 256.0,         169.60 - 180.0, 0.215 * 256.0, -1, "Yellow"      },
    { 0.363 * 256.0,         120.00 - 180.0, 0.211 * 256.0, -1, "Orange"      },
    { 0.237 * 256.0,         146.50        , 0.212 * 256.0,  1, "Brown"       },
    { 0.500 * 256.0,          93.50        , 0.212 * 256.0,  1, "Light Red"   },
    { 0.306 * 256.0,           0.00        , 0.000 * 256.0, -0, "Dark Grey"   },
    { 0.461 * 256.0,           0.00        , 0.000 * 256.0, -0, "Medium Grey" },
    { 0.763 * 256.0,         231.70 - 360.0, 0.216 * 256.0,  1, "Light Green" },
    { 0.461 * 256.0,         -24.40 - 360.0, 0.215 * 256.0,  1, "Light Blue"  },
    { 0.639 * 256.0,           0.00        , 0.000 * 256.0, -0, "Light Grey"  }
}
vicii_colors_8565r2_odd
video_cbm_color_t vicii_colors_8565r2_odd[16] static
Initial value:
=
{
    { 0.000 * 256.0,           0.00        , 0.000 * 256.0, -0, "Black"       },
    { 1.000 * 256.0,           0.00        , 0.000 * 256.0,  0, "White"       },
    { 0.306 * 256.0,         111.50        , 0.215 * 256.0,  1, "Red"         },
    { 0.639 * 256.0,         290.00 - 180.0, 0.217 * 256.0, -1, "Cyan"        },
    { 0.363 * 256.0,          59.00 - 180.0, 0.213 * 256.0, -1, "Purple"      },
    { 0.500 * 256.0,         245.70        , 0.212 * 256.0,  1, "Green"       },
    { 0.237 * 256.0,         354.60 - 360.0, 0.213 * 256.0,  1, "Blue"        },
    { 0.763 * 256.0,         160.60 - 180.0, 0.214 * 256.0, -1, "Yellow"      },
    { 0.363 * 256.0,         132.00 - 180.0, 0.215 * 256.0, -1, "Orange"      },
    { 0.237 * 256.0,         145.50        , 0.213 * 256.0,  1, "Brown"       },
    { 0.500 * 256.0,         111.50        , 0.215 * 256.0,  1, "Light Red"   },
    { 0.306 * 256.0,           0.00        , 0.000 * 256.0, -0, "Dark Grey"   },
    { 0.461 * 256.0,           0.00        , 0.000 * 256.0, -0, "Medium Grey" },
    { 0.763 * 256.0,         245.70 - 360.0, 0.212 * 256.0,  1, "Light Green" },
    { 0.461 * 256.0,         354.60 - 360.0, 0.213 * 256.0,  1, "Light Blue"  },
    { 0.639 * 256.0,           0.00        , 0.000 * 256.0, -0, "Light Grey"  }
}
vicii_palette_6569r1
video_cbm_palette_t vicii_palette_6569r1 static
Initial value:
=
{
     16 ,
    vicii_colors_6569r1,
    vicii_colors_6569r1_odd,
    vicii_colors_6569r1_even,
    0.0,
     0
}
Referenced by vicii_color_update_palette().
vicii_palette_6569r5
video_cbm_palette_t vicii_palette_6569r5 static
Initial value:
=
{
     16 ,
    vicii_colors_6569r5,
    vicii_colors_6569r5_odd,
    vicii_colors_6569r5_even,
    0.0,
     0
}
Referenced by vicii_color_update_palette().
vicii_palette_8565r2
video_cbm_palette_t vicii_palette_8565r2 static
Initial value:
=
{
     16 ,
    vicii_colors_8565r2,
    vicii_colors_8565r2_odd,
    vicii_colors_8565r2_even,
    0.0,
     0
}
Referenced by vicii_color_update_palette().