vsid: arch/shared/archdep_program_path.h File Reference
archdep_program_path.h File Reference
Retrieve path of currently running binary - header.
#include "vice.h"
Functions
void archdep_program_path_set_argv0 (char *argv0)
Set reference to argv[0].
const char * archdep_program_path (void)
Get absolute path to the running executable.
void archdep_program_path_free (void)
Free memory used by path to running executable.
Detailed Description
Retrieve path of currently running binary - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Get path to running executable.
OS support:
Linux
Windows
MacOS
BeOS/Haiku (untested)
AmigaOS (untested)
OS/2 (untested)
MS-DOS (untested)
Function Documentation
archdep_program_path()
const char * archdep_program_path (void)
Get absolute path to the running executable.
Free with archdep_program_path_free() on emulator exit.
Returns
absolute path to running executable
Referenced by archdep_boot_path(), and archdep_program_name().
archdep_program_path_free()
void archdep_program_path_free (void)
Free memory used by path to running executable.
Call from program exit
Referenced by archdep_shutdown(), and main_program().
archdep_program_path_set_argv0()
void archdep_program_path_set_argv0 (char * argv0)
Set reference to argv[0].
Parameters
[in] argv0 argv[0]
Referenced by archdep_init().