vsid: arch/shared/archdep_exit.h File Reference
archdep_exit.h File Reference
atexit(3) work arounds - header
#include <stdbool.h>
Functions
bool archdep_is_exiting (void)
void archdep_vice_exit (int excode)
Wrapper around exit()
Detailed Description
atexit(3) work arounds - header
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Blacky Stardust
Function Documentation
archdep_is_exiting()
bool archdep_is_exiting (void)
Referenced by sound_run_sound(), vsync_do_end_of_line(), and vsync_should_skip_frame().
archdep_vice_exit()
void archdep_vice_exit (int excode)
Wrapper around exit()
Referenced by archdep_create_user_cache_dir(), archdep_create_user_config_dir(), archdep_create_user_state_dir(), archdep_mkdir(), archdep_path_is_relative(), archdep_program_path(), archdep_tmpnam(), cmdline_features(), cmdline_help(), confirm_exit_callback(), create_layout(), create_shader(), create_shader_program(), create_sidcart_address_widget(), create_sidcart_clock_widget(), debugcart_store(), drive_jam(), fork_coproc(), initcmdline_check_attach(), io_source_register(), jam_dialog(), lib_calloc(), lib_malloc(), lib_realloc(), lib_strdup(), machine_jam(), maincpu_mainloop(), mon_playback_commands(), monitor_close(), on_focus_in_event(), on_window_state_event(), populate_tree_model(), quit_action(), render_thread_create(), ui_create_main_window(), ui_hotkeys_init(), ui_machine_menu_bar_create(), ui_statusbar_create(), uivideo_chip_id(), uivideo_chip_name(), vdrive_iec_write(), vice_opengl_renderer_create_child_view(), video_canvas_resize(), and z80_maincpu_loop().