vsid: printerdrv/output-graphics.h File Reference
output-graphics.h File Reference
Functions
int output_graphics_init_resources (void)
void output_graphics_init (void)
void output_graphics_shutdown (void)
Function Documentation
output_graphics_init()
void output_graphics_init (void)
< serial dev 4, 5, 6 and user port
Referenced by printer_init().
output_graphics_init_resources()
int output_graphics_init_resources (void)
Referenced by printer_resources_init().
output_graphics_shutdown()
void output_graphics_shutdown (void)
< serial dev 4, 5, 6 and user port
Referenced by printer_shutdown().