vsid: core/fmopl.h File Reference
fmopl.h File Reference
#include "alarm.h"
Data Structures
struct OPL_SLOT
struct OPL_CH
struct fm_opl_f
OPL state.
Macros
#define OPL_SAMPLE_BITS 16
select output bits size of output : 8 or 16
Typedefs
typedef uint8_t UINT8
compiler dependence
typedef uint16_t UINT16
typedef uint32_t UINT32
typedef int8_t INT8
typedef int16_t INT16
typedef int32_t INT32
typedef INT16 OPLSAMPLE
typedef struct fm_opl_f FM_OPL
OPL state.
Functions
FM_OPL * ym3812_init (UINT32 clock, UINT32 rate)
void ym3812_shutdown (FM_OPL *chip)
void ym3812_reset_chip (FM_OPL *chip)
int ym3812_write (FM_OPL *chip, int a, int v)
unsigned char ym3812_read (FM_OPL *chip, int a)
unsigned char ym3812_peek (FM_OPL *chip, int a)
int ym3812_timer_over (FM_OPL *chip, int c)
void ym3812_update_one (FM_OPL *chip, OPLSAMPLE *buffer, int length)
FM_OPL * ym3526_init (UINT32 clock, UINT32 rate)
void ym3526_shutdown (FM_OPL *chip)
void ym3526_reset_chip (FM_OPL *chip)
int ym3526_write (FM_OPL *chip, int a, int v)
unsigned char ym3526_read (FM_OPL *chip, int a)
unsigned char ym3526_peek (FM_OPL *chip, int a)
int ym3526_timer_over (FM_OPL *chip, int c)
int ym3526_snapshot_read_module (struct snapshot_s *s)
int ym3526_snapshot_write_module (struct snapshot_s *s)
void fmopl_set_machine_parameter (long clock_rate)
void ym3526_update_one (FM_OPL *chip, OPLSAMPLE *buffer, int length)
int connect1_is_output0 (int *connect)
void set_connect1 (FM_OPL *chip, int x, int y, int output0)
Macro Definition Documentation
OPL_SAMPLE_BITS
#define OPL_SAMPLE_BITS 16
select output bits size of output : 8 or 16
Typedef Documentation
FM_OPL
typedef struct fm_opl_f FM_OPL
OPL state.
INT16
typedef int16_t INT16
INT32
typedef int32_t INT32
INT8
typedef int8_t INT8
OPLSAMPLE
typedef INT16 OPLSAMPLE
UINT16
typedef uint16_t UINT16
UINT32
typedef uint32_t UINT32
UINT8
typedef uint8_t UINT8
compiler dependence
Function Documentation
connect1_is_output0()
int connect1_is_output0 (int * connect)
fmopl_set_machine_parameter()
void fmopl_set_machine_parameter (long clock_rate)
Referenced by machine_change_timing(), and machine_specific_init().
set_connect1()
void set_connect1 (FM_OPL * chip, int x, int y, int output0)
ym3526_init()
FM_OPL * ym3526_init (UINT32 clock, UINT32 rate)
ym3526_peek()
unsigned char ym3526_peek (FM_OPL * chip, int a)
ym3526_read()
unsigned char ym3526_read (FM_OPL * chip, int a)
ym3526_reset_chip()
void ym3526_reset_chip (FM_OPL * chip)
Referenced by ym3526_init().
ym3526_shutdown()
void ym3526_shutdown (FM_OPL * chip)
ym3526_snapshot_read_module()
int ym3526_snapshot_read_module (struct snapshot_s * s)
ym3526_snapshot_write_module()
int ym3526_snapshot_write_module (snapshot_t * s)
Todo:
FIXME: implement snapshot support
ym3526_timer_over()
int ym3526_timer_over (FM_OPL * chip, int c)
ym3526_update_one()
void ym3526_update_one (FM_OPL * chip, OPLSAMPLE * buffer, int length)
ym3526_write()
int ym3526_write (FM_OPL * chip, int a, int v)
ym3812_init()
FM_OPL * ym3812_init (UINT32 clock, UINT32 rate)
< waveform select
ym3812_peek()
unsigned char ym3812_peek (FM_OPL * chip, int a)
ym3812_read()
unsigned char ym3812_read (FM_OPL * chip, int a)
ym3812_reset_chip()
void ym3812_reset_chip (FM_OPL * chip)
Referenced by ym3812_init().
ym3812_shutdown()
void ym3812_shutdown (FM_OPL * chip)
ym3812_timer_over()
int ym3812_timer_over (FM_OPL * chip, int c)
ym3812_update_one()
void ym3812_update_one (FM_OPL * chip, OPLSAMPLE * buffer, int length)
ym3812_write()
int ym3812_write (FM_OPL * chip, int a, int v)