vsid: arch/gtk3/widgets/vsidplaylistwidget.c File Reference
vsidplaylistwidget.c File Reference
GTK3 playlist widget for VSID.
#include "vice.h"
#include <gtk/gtk.h>
#include <string.h>
#include <stdbool.h>
#include <time.h>
#include <sys/time.h>
#include "archdep_get_hvsc_dir.h"
#include "hvsc.h"
#include "lastdir.h"
#include "lib.h"
#include "mainlock.h"
#include "m3u.h"
#include "resources.h"
#include "uiactions.h"
#include "uiapi.h"
#include "uivsidwindow.h"
#include "util.h"
#include "version.h"
#include "vice_gtk3.h"
#include "vsidplaylistadddialog.h"
#include "vsidtuneinfowidget.h"
#include "vsidplaylistwidget.h"
Data Structures
struct plist_ctrl_
Playlist control struct.
struct ctx_menu_item_s
Context menu item object.
struct vsid_hotkey_s
VSID Hotkey info object.
Macros
#define MAX_CONTROLS 32
Typedefs
typedef struct plist_ctrl_ plist_ctrl_t
Playlist control struct.
typedef struct ctx_menu_item_s ctx_menu_item_t
Context menu item object.
typedef struct vsid_hotkey_s vsid_hotkey_t
VSID Hotkey info object.
Enumerations
enum {
CTRL_LIST_END = -1 ,
CTRL_PUSH_BUTTON ,
CTRL_TOGGLE_BUTTON ,
CTRL_CENTERED_LABEL
}
Control button types.
enum {
COL_TITLE ,
COL_AUTHOR ,
COL_FULL_PATH ,
COL_DISPLAY_PATH ,
NUM_COLUMNS
}
Playlist column indexes.
enum ctx_menu_item_type_t {
CTX_MENU_ACTION ,
CTX_MENU_SEP
}
Type of context menu item types.
Functions
static void update_title (void)
}}}
static void update_current_and_total (void)
Update playlist 'current/total' display.
static gchar * strip_hvsc_base (const gchar *path)
{{{ Utility functions
static void vsid_playlist_free_title (void)
Free playlist title.
static void vsid_playlist_set_title (const char *title)
Set playlist title.
static const char * vsid_playlist_get_title (void)
Get playlist title.
static void vsid_playlist_free_path (void)
Free playlist file path.
static void vsid_playlist_set_path (const char *path)
Set playlist path.
static const char * vsid_playlist_get_path (void)
Get playlist file path.
static void set_playlist_dialogs_default_dir (void)
Set default directory of playlist load/save dialogs.
static void scroll_to_iter (GtkTreeIter *iter)
Scroll view so the selected row is visible.
static void add_files_callback (GSList *files)
}}}
static gboolean on_ctx_delete_selected (GtkWidget *widget, gpointer data)
{{{ Context menu callbacks
static gboolean on_ctx_delete_all (GtkWidget *widget, gpointer data)
}}}
static gboolean open_add_dialog (GtkWidget *widget, gpointer data)
Callback for the Insert hotkey.
static bool playlist_entry_handler (const char *text, size_t len)
{{{ Playlist loading
static bool playlist_directive_handler (m3u_ext_id_t id, const char *text, size_t len)
M3U directive handler.
static void playlist_load_callback (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the load-playlist dialog.
static GtkWidget * create_save_content_area (void)
}}}
static void playlist_save_dialog_callback (GtkDialog *dialog, gchar *filename, gpointer data)
Callback for the 'save-playlist' dialog.
static void on_destroy (GtkWidget *widget, gpointer data)
Event handler for the 'destroy' event of the playlist widget.
static void on_row_activated (GtkTreeView *view, GtkTreePath *path, GtkTreeViewColumn *column, gpointer data)
Event handler for the 'row-activated' event of the view.
static void on_btn_playlist_remove_clicked (GtkWidget *widget, gpointer data)
Event handler for the 'remove' button.
static void clear_playlist_callback (GtkDialog *dialog, gboolean result)
Callback for the clear-playlist confirmation dialog.
static GtkWidget * create_context_menu (void)
Create context menu for the playlist.
static gboolean on_button_press_event (GtkWidget *view, GdkEvent *event, gpointer data)
Event handler for button press events on the playlist.
static gboolean on_key_press_event (GtkWidget *view, GdkEvent *event, gpointer data)
Event handler for key press events on the playlist.
static void vsid_playlist_model_create (void)
Create playlist model.
static void vsid_playlist_view_create (void)
Create playlist view widget.
static void trigger_ui_action (GtkWidget *button, gpointer action)
Event handler for playlist control buttons.
static GtkWidget * vsid_playlist_controls_create (void)
Create a grid with a list of buttons to control the playlist.
GtkWidget * vsid_playlist_widget_create (void)
Create main playlist widget.
gboolean vsid_playlist_append_file (const gchar *path)
Append path to the playlist.
void vsid_playlist_remove_file (int row)
Remove SID file at row from playlist.
void vsid_playlist_first (void)
Play first tune in the playlist.
void vsid_playlist_previous (void)
Play previous tune in the playlist.
void vsid_playlist_next (void)
Play next tune in the playlist.
void vsid_playlist_last (void)
Play last tune in the playlist.
void vsid_playlist_remove_selection (void)
Remove selected tunes from the playlist.
void vsid_playlist_add (void)
Show dialog to add files to the playlist.
void vsid_playlist_clear (void)
Clear playlist.
void vsid_playlist_load (void)
Show dialog to load a playlist.
void vsid_playlist_save (void)
Show dialog to save the playlist.
gint vsid_playlist_get_current_row (const gchar **path)
Get row number of currently selected tune.
Variables
static GtkListStore * playlist_model
Reference to the playlist model.
static GtkWidget * playlist_view
Reference to the playlist view.
static GtkWidget * title_widget
Playlist title widget.
static GtkWidget * playlist_title_entry
Reference to the save-playlist dialog's entry to set playlist title.
static char * playlist_title
Playlist title.
static char * playlist_path
Playlist path.
static char * playlist_last_dir
Playlist dialogs last-used directory.
static GtkWidget * control_widgets [32]
static gulong control_handlers [32]
static const ctx_menu_item_t cmenu_items []
Playlist context menu items.
static const vsid_hotkey_t hotkeys []
Playlist hotkeys.
static const plist_ctrl_t controls []
List of playlist controls.
Detailed Description
GTK3 playlist widget for VSID.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
MAX_CONTROLS
#define MAX_CONTROLS 32
Typedef Documentation
ctx_menu_item_t
typedef struct ctx_menu_item_s ctx_menu_item_t
Context menu item object.
plist_ctrl_t
typedef struct plist_ctrl_ plist_ctrl_t
Playlist control struct.
vsid_hotkey_t
typedef struct vsid_hotkey_s vsid_hotkey_t
VSID Hotkey info object.
Enumeration Type Documentation
anonymous enum
anonymous enum
Control button types.
Enumerator
CTRL_LIST_END
end of list
CTRL_PUSH_BUTTON
action button: simple push button
CTRL_TOGGLE_BUTTON
toggle button: for 'repeat' and 'shuffle'
CTRL_CENTERED_LABEL
centered label, gtk_label_set_markup() is used for the text, so some HTML tags such as bold and italic can be used
anonymous enum
anonymous enum
Playlist column indexes.
Enumerator
COL_TITLE
title
COL_AUTHOR
author
COL_FULL_PATH
full path to psid file
COL_DISPLAY_PATH
displayed path (HVSC stripped if possible)
NUM_COLUMNS
number of columns in the model
ctx_menu_item_type_t
enum ctx_menu_item_type_t
Type of context menu item types.
Enumerator
CTX_MENU_ACTION
action
CTX_MENU_SEP
menu separator
Function Documentation
add_files_callback()
static void add_files_callback (GSList * files) static
}}}
Add SID files to the playlist
Parameters
[in,out] files List of selected files
Note
The playlist-add dialog frees files after calling this function
Referenced by open_add_dialog(), and vsid_playlist_add().
clear_playlist_callback()
static void clear_playlist_callback (GtkDialog * dialog, gboolean result) static
Callback for the clear-playlist confirmation dialog.
Destroys dialog and clears playlist if result is TRUE.
Parameters
[in] dialog confirmation dialog
[in] result result of dialog
Referenced by vsid_playlist_clear().
create_context_menu()
static GtkWidget * create_context_menu (void) static
Create context menu for the playlist.
Returns
GtkMenu
Referenced by on_button_press_event().
create_save_content_area()
static GtkWidget * create_save_content_area (void) static
}}}
{{{ Playlist saving
Create content area widget for the 'save-playlist dialog
Create GtkGrid with label and text entry to set/edit the playlist title.
Returns
GtkGrid
Referenced by vsid_playlist_save().
on_btn_playlist_remove_clicked()
static void on_btn_playlist_remove_clicked (GtkWidget * widget, gpointer data) static
Event handler for the 'remove' button.
Remove selected items from the playlist.
Parameters
[in] widget button triggering the event
[in] data extra event data (unused)
on_button_press_event()
static gboolean on_button_press_event (GtkWidget * view, GdkEvent * event, gpointer data) static
Event handler for button press events on the playlist.
Pops up a context menu on the playlist.
Parameters
[in] view playlist view widget (unused)
[in] event event reference
[in] data extra even data (unused)
Returns
TRUE when event consumed and no further propagation is needed
Referenced by vsid_playlist_view_create().
on_ctx_delete_all()
static gboolean on_ctx_delete_all (GtkWidget * widget, gpointer data) static
}}}
Delete the entire playlist
Parameters
[in] widget widget triggering the callback (unused)
[in] data event reference (unused)
Returns
TRUE
on_ctx_delete_selected()
static gboolean on_ctx_delete_selected (GtkWidget * widget, gpointer data) static
{{{ Context menu callbacks
Delete selected rows
Event handler for context menu 'delete-all' and hotkey 'Shift+Delete'.
Parameters
[in] widget widget triggering the event
[in] data extra event data (unused)
Returns
FALSE on error
on_destroy()
static void on_destroy (GtkWidget * widget, gpointer data) static
Event handler for the 'destroy' event of the playlist widget.
Parameters
[in] widget playlist widget
[in] data extra event data (unused)
Referenced by vsid_playlist_widget_create().
on_key_press_event()
static gboolean on_key_press_event (GtkWidget * view, GdkEvent * event, gpointer data) static
Event handler for key press events on the playlist.
Parameters
[in,out] view playlist view widget
[in] event event reference
[in] data extra even data
Returns
TRUE when event consumed and no further propagation is needed
Referenced by vsid_playlist_view_create().
on_row_activated()
static void on_row_activated (GtkTreeView * view, GtkTreePath * path, GtkTreeViewColumn * column, gpointer data) static
Event handler for the 'row-activated' event of the view.
Triggered by double-clicking on a SID file in the view
Parameters
[in,out] view the GtkTreeView instance
[in] path the path to the activated row
[in] column the column in the view (unused)
[in] data extra event data (unused)
Referenced by vsid_playlist_view_create().
open_add_dialog()
static gboolean open_add_dialog (GtkWidget * widget, gpointer data) static
Callback for the Insert hotkey.
Parameters
[in] widget widget triggering the callback (unused)
[in] data event reference (unused)
Returns
TRUE
playlist_directive_handler()
static bool playlist_directive_handler (m3u_ext_id_t id, const char * text, size_t len) static
M3U directive handler.
Called by the m3u parser when encountering an extended m3u directive.
Parameters
[in] id directive ID
[in] text text following the directive
[in] len length of text
Returns
false to stop the parser on an error
Referenced by playlist_load_callback().
playlist_entry_handler()
static bool playlist_entry_handler (const char * text, size_t len) static
{{{ Playlist loading
M3U entry handler
Called by the m3u parser when encountering a normal entry.
Parameters
[in] text entry text
[in] len length of text
Returns
false to stop the parser on an error
Referenced by playlist_load_callback().
playlist_load_callback()
static void playlist_load_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the load-playlist dialog.
Parameters
[in] dialog load-playlist dialog
[in] filename filename or NULL when canceled
[in] data extra callback data (ignored)
Referenced by vsid_playlist_load().
playlist_save_dialog_callback()
static void playlist_save_dialog_callback (GtkDialog * dialog, gchar * filename, gpointer data) static
Callback for the 'save-playlist' dialog.
Save the current playlist to filename.
Parameters
[in] dialog save-playlist dialog
[in] filename filename or NULL to cancel saving
[in] data extra event data (ignored)
Referenced by vsid_playlist_save().
scroll_to_iter()
static void scroll_to_iter (GtkTreeIter * iter) static
Scroll view so the selected row is visible.
Parameters
[in] iter tree view iter
Note
This function assumes the iter is valid since there's no quick way to check if the iter is valid
Referenced by vsid_playlist_first(), vsid_playlist_last(), vsid_playlist_next(), and vsid_playlist_previous().
set_playlist_dialogs_default_dir()
static void set_playlist_dialogs_default_dir (void) static
Set default directory of playlist load/save dialogs.
If the default directory (playlist_last_dir) isn't set yet, we use the HVSC base directory.
Referenced by vsid_playlist_load(), and vsid_playlist_save().
strip_hvsc_base()
static gchar * strip_hvsc_base (const gchar * path) static
{{{ Utility functions
Strip HVSC base dir from path
Try to strip the HVSC base directory from path, otherwise return the full path.
Parameters
[in] path full path to psid file
Returns
stripped path
Note
Free with g_free()
Referenced by vsid_playlist_append_file().
trigger_ui_action()
static void trigger_ui_action (GtkWidget * button, gpointer action) static
Event handler for playlist control buttons.
Trigger UI action on click/toggle.
Parameters
[in] button button triggering the event (currently ignored)
[in] action UI action ID
Referenced by vsid_playlist_controls_create().
update_current_and_total()
static void update_current_and_total (void) static
Update playlist 'current/total' display.
Todo:
Add way to determine currently playing SID when multiple rows have been selected: probably we'll need to keep track of the last selected row in the playlist, also updating when pressing the next/prev etc buttons, or autoskipping to the next SID.
Referenced by clear_playlist_callback(), on_row_activated(), playlist_load_callback(), vsid_playlist_append_file(), vsid_playlist_first(), vsid_playlist_last(), vsid_playlist_next(), vsid_playlist_previous(), vsid_playlist_remove_file(), and vsid_playlist_remove_selection().
update_title()
static void update_title (void) static
}}}
Update title widget with the playlist title, if present
Referenced by playlist_save_dialog_callback().
vsid_playlist_add()
void vsid_playlist_add (void)
Show dialog to add files to the playlist.
vsid_playlist_append_file()
gboolean vsid_playlist_append_file (const gchar * path)
Append path to the playlist.
Parameters
[in] path path to SID file
Returns
TRUE on success, FALSE on failure
Referenced by add_files_callback(), on_drag_data_received(), and playlist_entry_handler().
vsid_playlist_clear()
void vsid_playlist_clear (void)
Clear playlist.
Shows confirmation dialog box before clearing.
Referenced by clear_playlist_callback(), and on_ctx_delete_all().
vsid_playlist_controls_create()
static GtkWidget * vsid_playlist_controls_create (void) static
Create a grid with a list of buttons to control the playlist.
Most of the playlist should also be controllable via a context-menu (ie mouse right-click), which is a big fat TODO now.
Returns
GtkGrid
Referenced by vsid_playlist_widget_create().
vsid_playlist_first()
void vsid_playlist_first (void)
Play first tune in the playlist.
Todo:
check result
vsid_playlist_free_path()
static void vsid_playlist_free_path (void) static
Free playlist file path.
Referenced by on_destroy(), playlist_load_callback(), and vsid_playlist_set_path().
vsid_playlist_free_title()
static void vsid_playlist_free_title (void) static
Free playlist title.
Referenced by on_destroy(), playlist_load_callback(), playlist_save_dialog_callback(), and vsid_playlist_set_title().
vsid_playlist_get_current_row()
gint vsid_playlist_get_current_row (const gchar ** path)
Get row number of currently selected tune.
Parameters
[out] path path to SID file (optional, pass NULL to ignore
Returns
row number or -1 when no selection or multiple rows selected
Referenced by update_current_and_total(), and vsid_tune_info_widget_update().
vsid_playlist_get_path()
static const char * vsid_playlist_get_path (void) static
Get playlist file path.
Returns
playlist file path
Referenced by vsid_playlist_save().
vsid_playlist_get_title()
static const char * vsid_playlist_get_title (void) static
Get playlist title.
Returns
playlist title
Referenced by create_save_content_area(), and update_title().
vsid_playlist_last()
void vsid_playlist_last (void)
Play last tune in the playlist.
vsid_playlist_load()
void vsid_playlist_load (void)
Show dialog to load a playlist.
vsid_playlist_model_create()
static void vsid_playlist_model_create (void) static
Create playlist model.
Referenced by vsid_playlist_widget_create().
vsid_playlist_next()
void vsid_playlist_next (void)
Play next tune in the playlist.
Referenced by vsid_tune_info_widget_update().
vsid_playlist_previous()
void vsid_playlist_previous (void)
Play previous tune in the playlist.
vsid_playlist_remove_file()
void vsid_playlist_remove_file (int row)
Remove SID file at row from playlist.
Parameters
[in] row row in playlist
!
Todo:
FIXME: unlikely this will be used.
Todo:
actually remove item :)
vsid_playlist_remove_selection()
void vsid_playlist_remove_selection (void)
Remove selected tunes from the playlist.
Referenced by on_btn_playlist_remove_clicked(), and on_ctx_delete_selected().
vsid_playlist_save()
void vsid_playlist_save (void)
Show dialog to save the playlist.
vsid_playlist_set_path()
static void vsid_playlist_set_path (const char * path) static
Set playlist path.
Parameters
[in] path path to playlist file
Referenced by playlist_load_callback().
vsid_playlist_set_title()
static void vsid_playlist_set_title (const char * title) static
Set playlist title.
Parameters
[in] title playlist title
Referenced by playlist_directive_handler(), and playlist_save_dialog_callback().
vsid_playlist_view_create()
static void vsid_playlist_view_create (void) static
Create playlist view widget.
Referenced by vsid_playlist_widget_create().
vsid_playlist_widget_create()
GtkWidget * vsid_playlist_widget_create (void)
Create main playlist widget.
Returns
GtkGrid
Referenced by vsid_main_widget_create().
Variable Documentation
cmenu_items
const ctx_menu_item_t cmenu_items[] static
Initial value:
= {
    { "Play",
      NULL,
      CTX_MENU_ACTION },
    { "Delete selected item(s)",
      on_ctx_delete_selected,
      CTX_MENU_ACTION },
    { "---", NULL, CTX_MENU_SEP },
    { "Load playlist",
      NULL,
      CTX_MENU_ACTION },
    { "Save playlist",
      on_ctx_delete_all,
      CTX_MENU_ACTION },
    { "Clear playlist",
      NULL,
      CTX_MENU_ACTION },
    { "---", NULL, CTX_MENU_SEP },
    { "Export binary",
      NULL,
      CTX_MENU_ACTION },
    { NULL, NULL, -1 }
}
Playlist context menu items.
Referenced by create_context_menu().
control_handlers
gulong control_handlers[32] static
Referenced by vsid_playlist_controls_create().
control_widgets
GtkWidget* control_widgets[32] static
Referenced by update_current_and_total(), and vsid_playlist_controls_create().
controls
const plist_ctrl_t controls[] static
Initial value:
= {
    {
        .icon = "media-skip-backward",
        .type = CTRL_PUSH_BUTTON,
        .action = ACTION_PSID_PLAYLIST_FIRST,
        .tooltip = "Go to start of playlist"
    },
    {
        .icon = "media-seek-backward",
        .type = CTRL_PUSH_BUTTON,
        .action = ACTION_PSID_PLAYLIST_PREVIOUS,
        .tooltip = "Go to previous tune"
    },
    {
        .type = CTRL_CENTERED_LABEL,
        .text = "<b>0</b> of <b>0</b>",
        .margin_start = 8,
        .margin_end = 8
    },
    {
        .icon = "media-seek-forward",
        .type = CTRL_PUSH_BUTTON,
        .action = ACTION_PSID_PLAYLIST_NEXT,
        .tooltip = "Go to next tune"
    },
    {
        .icon = "media-skip-forward",
        .type = CTRL_PUSH_BUTTON,
        .action = ACTION_PSID_PLAYLIST_LAST,
        .tooltip = "Go to end of playlist"
    },
    {
        .icon = "media-playlist-repeat",
        .type = CTRL_TOGGLE_BUTTON,
        .tooltip = "Repeat playlist",
        .margin_start = 16
    },
    {
        .icon = "media-playlist-shuffle",
        .type = CTRL_TOGGLE_BUTTON,
        .tooltip = "Shuffle playlist"
    },
    {
        .icon ="list-add",
        .type = CTRL_PUSH_BUTTON,
        .action = ACTION_PSID_PLAYLIST_ADD,
        .tooltip = "Add tunes to playlist",
        .margin_start = 16
    },
    {
        .icon = "list-remove",
        .type = CTRL_PUSH_BUTTON,
        .callback = on_btn_playlist_remove_clicked,
        .tooltip = "Remove selected tune from playlist"
    },
    {
        .icon = "edit-clear-all",
        .type = CTRL_PUSH_BUTTON,
        .action = ACTION_PSID_PLAYLIST_CLEAR,
        .tooltip = "Clear playlist"
    },
    {
        .icon = "document-open",
        .type = CTRL_PUSH_BUTTON,
        .action = ACTION_PSID_PLAYLIST_LOAD,
        .tooltip = "Open playlist file",
        .margin_start = 16
    },
    {
        .icon = "document-save",
        .type = CTRL_PUSH_BUTTON,
        .action = ACTION_PSID_PLAYLIST_SAVE,
        .tooltip = "Save playlist file"
    },
    { .type = CTRL_LIST_END }
}
List of playlist controls.
Referenced by ui_datasette_update_sensitive(), ui_statusbar_recreate_crt_controls(), and vsid_playlist_controls_create().
hotkeys
const vsid_hotkey_t hotkeys[] static
Initial value:
= {
    { GDK_KEY_Insert,   0,              open_add_dialog },
    { GDK_KEY_Delete,   0,              on_ctx_delete_selected },
    { GDK_KEY_Delete,   GDK_SHIFT_MASK, on_ctx_delete_all },
    { 0, 0, NULL }
}
Playlist hotkeys.
Referenced by on_key_press_event().
playlist_last_dir
char* playlist_last_dir static
Playlist dialogs last-used directory.
Last used directory for playlist dialogs, used to set the directory of the playlist dialogs.
Referenced by on_destroy(), playlist_load_callback(), playlist_save_dialog_callback(), set_playlist_dialogs_default_dir(), vsid_playlist_load(), and vsid_playlist_save().
playlist_model
GtkListStore* playlist_model static
Reference to the playlist model.
Referenced by on_row_activated(), playlist_load_callback(), playlist_save_dialog_callback(), scroll_to_iter(), update_current_and_total(), vsid_playlist_append_file(), vsid_playlist_first(), vsid_playlist_get_current_row(), vsid_playlist_last(), vsid_playlist_model_create(), vsid_playlist_next(), vsid_playlist_previous(), vsid_playlist_remove_selection(), vsid_playlist_save(), and vsid_playlist_view_create().
playlist_path
char* playlist_path static
Playlist path.
Used to suggest filename when saving playlist, set when loading a playlist.
Referenced by vsid_playlist_free_path(), vsid_playlist_get_path(), and vsid_playlist_set_path().
playlist_title
char* playlist_title static
Playlist title.
Set when loading an m3u file with the "\#PLAYLIST:" directive. Freed when the main widget is destroyed.
Referenced by playlist_directive_handler(), update_title(), vsid_playlist_free_title(), vsid_playlist_get_title(), and vsid_playlist_set_title().
playlist_title_entry
GtkWidget* playlist_title_entry static
Reference to the save-playlist dialog's entry to set playlist title.
Only valid during lifetime of the save-playlist dialog
Referenced by create_save_content_area(), and playlist_save_dialog_callback().
playlist_view
GtkWidget* playlist_view static
Reference to the playlist view.
Referenced by scroll_to_iter(), vsid_playlist_first(), vsid_playlist_get_current_row(), vsid_playlist_last(), vsid_playlist_next(), vsid_playlist_previous(), vsid_playlist_remove_selection(), vsid_playlist_view_create(), and vsid_playlist_widget_create().
title_widget
GtkWidget* title_widget static
Playlist title widget.
Gets updated with the number of tunes in the list.
Referenced by update_title(), and vsid_playlist_widget_create().