vsid: serial/realdevice.h File Reference
realdevice.h File Reference
#include "types.h"
Functions
void realdevice_init (void)
void realdevice_reset (void)
void realdevice_open (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void realdevice_close (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void realdevice_listen (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void realdevice_talk (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void realdevice_unlisten (void(*st_func)(uint8_t))
void realdevice_untalk (void(*st_func)(uint8_t))
void realdevice_write (uint8_t data, void(*st_func)(uint8_t))
uint8_t realdevice_read (void(*st_func)(uint8_t))
int realdevice_enable (void)
void realdevice_disable (void)
Function Documentation
realdevice_close()
void realdevice_close (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_close().
realdevice_disable()
void realdevice_disable (void)
Referenced by serial_realdevice_disable().
realdevice_enable()
int realdevice_enable (void)
Referenced by serial_realdevice_enable().
realdevice_init()
void realdevice_init (void)
Referenced by serial_iec_bus_init().
realdevice_listen()
void realdevice_listen (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_listen().
realdevice_open()
void realdevice_open (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_open().
realdevice_read()
uint8_t realdevice_read (void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_read().
realdevice_reset()
void realdevice_reset (void)
Referenced by serial_iec_bus_reset().
realdevice_talk()
void realdevice_talk (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_talk().
realdevice_unlisten()
void realdevice_unlisten (void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_unlisten().
realdevice_untalk()
void realdevice_untalk (void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_untalk().
realdevice_write()
void realdevice_write (uint8_t data, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_write().