vsid: arch/gtk3/uidatasette.c File Reference
uidatasette.c File Reference
Create independent datasette control widgets.
#include "vice.h"
#include <gtk/gtk.h>
#include "datasette.h"
#include "log.h"
#include "machine.h"
#include "resources.h"
#include "tapeport.h"
#include "uiactions.h"
#include "uisettings.h"
#include "uitapeattach.h"
#include "vice_gtk3.h"
#include "uidatasette.h"
Functions
int ui_datasette_command_to_action (int port, int command)
Translate datasette command codes to UI action IDs.
static void on_configure_activate (GtkWidget *widget, gpointer data)
Handler for the 'activate' event of the "Configure" menu item.
static void trigger_ui_action (GtkWidget *item, gpointer action)
Handler for the 'activate' event of a menu item.
GtkWidget * ui_create_datasette_control_menu (int port)
Create datasette control menu.
void ui_datasette_update_sensitive (GtkWidget *menu, int port)
Update sensitivity of the datasettet controls.
Variables
static const int action_ids [][2]
Table of UI action codes for datasette control codes and port.
Detailed Description
Create independent datasette control widgets.
Author
Michael C. Martin mcmar.nosp@m.tin@.nosp@m.gmail.nosp@m..com
Function Documentation
on_configure_activate()
static void on_configure_activate (GtkWidget * widget, gpointer data) static
Handler for the 'activate' event of the "Configure" menu item.
Pop up the settings UI and select "I/O extensions" -> "Tapeport devices"
Parameters
[in] widget menu item triggering the event (unused)
[in] data extra event data (unused)
Referenced by ui_create_datasette_control_menu().
trigger_ui_action()
static void trigger_ui_action (GtkWidget * item, gpointer action) static
Handler for the 'activate' event of a menu item.
Trigger a UI action.
Parameters
[in] action UI action ID
Referenced by ui_create_datasette_control_menu().
ui_create_datasette_control_menu()
GtkWidget * ui_create_datasette_control_menu (int port)
Create datasette control menu.
Parameters
[in] port datasette port number (1 or 2)
Returns
GtkMenu with datasette controls
Todo:
Update for second datasette on PET
Referenced by ui_statusbar_create().
ui_datasette_command_to_action()
int ui_datasette_command_to_action (int port, int command)
Translate datasette command codes to UI action IDs.
Parameters
[in] command datasette command code
[in] port port number (1 or 2)
Returns
action ID or ACTION_NONE for invalid control or port values
See also
src/datasette/datasette.h for the command codes
Referenced by ui_create_datasette_control_menu().
ui_datasette_update_sensitive()
void ui_datasette_update_sensitive (GtkWidget * menu, int port)
Update sensitivity of the datasettet controls.
Disables/enables the datasette controls (keys), depending on whether the datasette is enabled.
Parameters
[in] menu tape menu
[in] port tape port number (1 or 2)
Referenced by ui_do_datasette_popup().
Variable Documentation
action_ids
const int action_ids[][2] static
Initial value:
= {
    { ACTION_TAPE_STOP_1,           ACTION_TAPE_STOP_2 },
    { ACTION_TAPE_PLAY_1,           ACTION_TAPE_PLAY_2 },
    { ACTION_TAPE_FFWD_1,           ACTION_TAPE_FFWD_2 },
    { ACTION_TAPE_REWIND_1,         ACTION_TAPE_REWIND_2 },
    { ACTION_TAPE_RECORD_1,         ACTION_TAPE_RECORD_2 },
    { ACTION_TAPE_RESET_1,          ACTION_TAPE_RESET_2 },
    { ACTION_TAPE_RESET_COUNTER_1,  ACTION_TAPE_RESET_COUNTER_2 }
}
Table of UI action codes for datasette control codes and port.
Referenced by ui_datasette_command_to_action().