x128: drive/iec/via1d1541.c File Reference
via1d1541.c File Reference
#include "vice.h"
#include <stdio.h>
#include "debug.h"
#include "drive.h"
#include "drivesync.h"
#include "drivetypes.h"
#include "glue1571.h"
#include "iecbus.h"
#include "iecdrive.h"
#include "interrupt.h"
#include "lib.h"
#include "rotation.h"
#include "types.h"
#include "via.h"
#include "via1d1541.h"
#include "viad.h"
Data Structures
struct drivevia1_context_s
Macros
#define iecbus (via1p->v_iecbus)
Typedefs
typedef struct drivevia1_context_s drivevia1_context_t
Functions
void via1d1541_store (diskunit_context_t *ctxptr, uint16_t addr, uint8_t data)
uint8_t via1d1541_read (diskunit_context_t *ctxptr, uint16_t addr)
uint8_t via1d1541_peek (diskunit_context_t *ctxptr, uint16_t addr)
int via1d1541_dump (diskunit_context_t *ctxptr, uint16_t addr)
static void set_ca2 (via_context_t *via_context, int state)
static void set_cb2 (via_context_t *via_context, int state, int offset)
static void set_int (via_context_t *via_context, unsigned int int_num, int value, CLOCK rclk)
static void restore_int (via_context_t *via_context, unsigned int int_num, int value)
static void undump_pra (via_context_t *via_context, uint8_t byte)
static void store_pra (via_context_t *via_context, uint8_t byte, uint8_t oldpa_value, uint16_t addr)
static void undump_prb (via_context_t *via_context, uint8_t byte)
static void store_prb (via_context_t *via_context, uint8_t byte, uint8_t p_oldpb, uint16_t addr)
static void undump_pcr (via_context_t *via_context, uint8_t byte)
static uint8_t store_pcr (via_context_t *via_context, uint8_t byte, uint16_t addr)
static void undump_acr (via_context_t *via_context, uint8_t byte)
static void store_acr (via_context_t *via_context, uint8_t byte)
static void store_sr (via_context_t *via_context, uint8_t byte)
static void store_t2l (via_context_t *via_context, uint8_t byte)
static void reset (via_context_t *via_context)
static uint8_t read_pra (via_context_t *via_context, uint16_t addr)
static uint8_t read_prb (via_context_t *via_context)
void via1d1541_init (diskunit_context_t *ctxptr)
void via1d1541_setup_context (diskunit_context_t *ctxptr)
Macro Definition Documentation
iecbus
#define iecbus (via1p->v_iecbus)
Typedef Documentation
drivevia1_context_t
typedef struct drivevia1_context_s drivevia1_context_t
Function Documentation
read_pra()
static uint8_t read_pra (via_context_t * via_context, uint16_t addr) static
< Data direction register for port A
< Port A
< Data direction register for port A
< speed-dos userport cable
< 21 second backup userport cable
< formel 64 cartridge
< Port A
< Peripheral control register
< Port A
< Data direction register for port A
< Data direction register for port A
Referenced by via1d1541_setup_context().
read_prb()
static uint8_t read_prb (via_context_t * via_context) static
< Port B
< Port B
Referenced by via1d1541_setup_context().
reset()
static void reset (via_context_t * via_context) static
Referenced by via1d1541_setup_context().
restore_int()
static void restore_int (via_context_t * via_context, unsigned int int_num, int value) static
Referenced by via1d1541_setup_context().
set_ca2()
static void set_ca2 (via_context_t * via_context, int state) static
Referenced by via1d1541_setup_context().
set_cb2()
static void set_cb2 (via_context_t * via_context, int state, int offset) static
Referenced by via1d1541_setup_context().
set_int()
static void set_int (via_context_t * via_context, unsigned int int_num, int value, CLOCK rclk) static
Referenced by via1d1541_setup_context().
store_acr()
static void store_acr (via_context_t * via_context, uint8_t byte) static
Referenced by via1d1541_setup_context().
store_pcr()
static uint8_t store_pcr (via_context_t * via_context, uint8_t byte, uint16_t addr) static
Referenced by via1d1541_setup_context().
store_pra()
static void store_pra (via_context_t * via_context, uint8_t byte, uint8_t oldpa_value, uint16_t addr) static
< speed-dos userport cable
< 21 second backup userport cable
< formel 64 cartridge
< Port A
< Peripheral control register
< write data, set flag (cia2)
< write data
Referenced by via1d1541_setup_context().
store_prb()
static void store_prb (via_context_t * via_context, uint8_t byte, uint8_t p_oldpb, uint16_t addr) static
Referenced by via1d1541_setup_context().
store_sr()
static void store_sr (via_context_t * via_context, uint8_t byte) static
Referenced by via1d1541_setup_context().
store_t2l()
static void store_t2l (via_context_t * via_context, uint8_t byte) static
Referenced by via1d1541_setup_context().
undump_acr()
static void undump_acr (via_context_t * via_context, uint8_t byte) static
Referenced by via1d1541_setup_context().
undump_pcr()
static void undump_pcr (via_context_t * via_context, uint8_t byte) static
Referenced by via1d1541_setup_context().
undump_pra()
static void undump_pra (via_context_t * via_context, uint8_t byte) static
< speed-dos userport cable
< 21 second backup userport cable
< formel 64 cartridge
< write data
Referenced by via1d1541_setup_context().
undump_prb()
static void undump_prb (via_context_t * via_context, uint8_t byte) static
Referenced by via1d1541_setup_context().
via1d1541_dump()
int via1d1541_dump (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by drivemem_ioreg_list_get().
via1d1541_init()
void via1d1541_init (diskunit_context_t * ctxptr)
Referenced by iec_drive_init().
via1d1541_peek()
uint8_t via1d1541_peek (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by memiec_init().
via1d1541_read()
uint8_t via1d1541_read (diskunit_context_t * ctxptr, uint16_t addr)
Referenced by memiec_init().
via1d1541_setup_context()
void via1d1541_setup_context (diskunit_context_t * ctxptr)
Referenced by iec_drive_setup_context().
via1d1541_store()
void via1d1541_store (diskunit_context_t * ctxptr, uint16_t addr, uint8_t data)
Referenced by memiec_init().