x128: parsid.h File Reference
parsid.h File Reference
#include "types.h"
#include "sid-snapshot.h"
Macros
#define parsid_STROBE 0x01
control register bits
#define parsid_AUTOFEED 0x02
#define parsid_nINIT 0x04
#define parsid_SELECTIN 0x08
#define parsid_PCD 0x20
Functions
void parsid_reset (void)
int parsid_open (void)
int parsid_close (void)
int parsid_read (uint16_t addr, int chipno)
void parsid_store (uint16_t addr, uint8_t outval, int chipno)
int parsid_available (void)
int parsid_drv_open (void)
void parsid_drv_out_ctr (uint8_t parsid_ctrport, int chipno)
uint8_t parsid_drv_in_ctr (int chipno)
int parsid_drv_close (void)
uint8_t parsid_drv_in_data (int chipno)
void parsid_drv_out_data (uint8_t addr, int chipno)
void parsid_drv_sleep (int amount)
int parsid_drv_available (void)
void parsid_state_read (int chipno, struct sid_parsid_snapshot_state_s *sid_state)
void parsid_state_write (int chipno, struct sid_parsid_snapshot_state_s *sid_state)
Macro Definition Documentation
parsid_AUTOFEED
#define parsid_AUTOFEED 0x02
parsid_nINIT
#define parsid_nINIT 0x04
parsid_PCD
#define parsid_PCD 0x20
parsid_SELECTIN
#define parsid_SELECTIN 0x08
parsid_STROBE
#define parsid_STROBE 0x01
control register bits
Function Documentation
parsid_available()
int parsid_available (void)
Referenced by build_sid_cmdline_option(), and sid_get_engine_model_list().
parsid_close()
int parsid_close (void)
Referenced by sid_engine_set().
parsid_drv_available()
int parsid_drv_available (void)
parsid_drv_close()
int parsid_drv_close (void)
parsid_drv_in_ctr()
uint8_t parsid_drv_in_ctr (int chipno)
parsid_drv_in_data()
uint8_t parsid_drv_in_data (int chipno)
parsid_drv_open()
int parsid_drv_open (void)
parsid_drv_out_ctr()
void parsid_drv_out_ctr (uint8_t parsid_ctrport, int chipno)
parsid_drv_out_data()
void parsid_drv_out_data (uint8_t addr, int chipno)
parsid_drv_sleep()
void parsid_drv_sleep (int amount)
parsid_open()
int parsid_open (void)
Referenced by sid_engine_set().
parsid_read()
int parsid_read (uint16_t addr, int chipno)
Referenced by set_sound_func().
parsid_reset()
void parsid_reset (void)
parsid_state_read()
void parsid_state_read (int chipno, struct sid_parsid_snapshot_state_s * sid_state)
parsid_state_write()
void parsid_state_write (int chipno, struct sid_parsid_snapshot_state_s * sid_state)
parsid_store()
void parsid_store (uint16_t addr, uint8_t outval, int chipno)
Referenced by set_sound_func().