vsid: arch/gtk3/widgets/vsidtuneinfowidget.c File Reference
vsidtuneinfowidget.c File Reference
GTK3 tune info widget for VSID.
#include "vice.h"
#include <gtk/gtk.h>
#include "vice_gtk3.h"
#include "debug_gtk3.h"
#include "hvsc.h"
#include "lib.h"
#include "log.h"
#include "machine.h"
#include "mainlock.h"
#include "uiactions.h"
#include "util.h"
#include "vsidcontrolwidget.h"
#include "vsidplaylistwidget.h"
#include "vsidstate.h"
#include "vsidtuneinfowidget.h"
Enumerations
enum {
DRV_INFO_SID_IMAGE = 0 ,
DRV_INFO_DRIVER_ADDR ,
DRV_INFO_LOAD_ADDR ,
DRV_INFO_INIT_ADDR ,
DRV_INFO_PLAY_ADDR
}
Rows in the driver info grid.
Functions
static void on_destroy (GtkWidget *widget, gpointer data)
Handler for the 'destroy' event of the widget.
static GtkWidget * create_left_aligned_label (const char *text)
Create left aligned label, text can use HTML markup.
gchar * convert_to_utf8 (const char *s)
Convert a string from a SID header field to UTF-8.
static GtkWidget * create_readonly_entry (void)
Create a label to display text and allow users to copy that text.
static GtkWidget * create_tune_num_widget (void)
Create widget to display tune number information.
static void update_tune_num_widget (void)
Update tune number widget.
static GtkWidget * create_irq_widget (void)
Create IRQ widget.
static void update_irq_widget (const char *irq)
Update IRQ widget.
static GtkWidget * create_model_widget (void)
Create SID model widget.
static void update_model_widget (int model)
Update SID model widget.
static GtkWidget * create_runtime_widget (void)
Create run time widget.
static void update_runtime_widget (unsigned int dsec)
Update the run time widget.
static GtkWidget * create_sync_widget (void)
Create sync widget.
static void update_sync_widget (int sync)
Update sync widget.
static GtkWidget * create_driver_info_widget (void)
Create driver information widget.
static void driver_info_set_addr (int row, uint16_t addr)
Set a label in the driver info grid at row to addr.
static void driver_info_set_image (void)
Set memory range of the SID image.
void vsid_tune_info_widget_update (void)
Update play time based ui elements.
GtkWidget * vsid_tune_info_widget_create (void)
Create widget to show tune information.
void vsid_tune_info_widget_set_name (const char *name)
Set tune name.
void vsid_tune_info_widget_set_author (const char *name)
Set author.
void vsid_tune_info_widget_set_copyright (const char *name)
Set copyright info string.
void vsid_tune_info_widget_set_tune_count (int num)
Set number of tunes.
void vsid_tune_info_widget_set_tune_default (int num)
Set default tune.
void vsid_tune_info_widget_set_tune_current (int num)
Set current tune.
void vsid_tune_info_widget_set_model (int model)
Set SID model.
void vsid_tune_info_widget_set_irq (const char *irq)
Set IRQ source.
void vsid_tune_info_widget_set_sync (int sync)
Set sync factor.
void vsid_tune_info_widget_set_time (unsigned int dsec)
Set current run time.
void vsid_tune_info_widget_set_driver_addr (uint16_t addr)
Set driver address.
void vsid_tune_info_widget_set_load_addr (uint16_t addr)
Set load address.
void vsid_tune_info_widget_set_init_addr (uint16_t addr)
Set init routine address.
void vsid_tune_info_widget_set_play_addr (uint16_t addr)
Set play routine address.
void vsid_tune_info_widget_set_data_size (uint16_t size)
Set size of SID on actual machine.
bool vsid_tune_info_widget_set_song_lengths (const char *psid)
Set song lengths for each sub-tune.
bool vsid_tune_info_widget_set_song_lengths_md5 (const char *digest)
int vsid_tune_info_widget_get_song_lengths (long **dest)
Retrieve songlengths.
Variables
static const char * driver_info_labels []
Labels for the driver info grid.
static uint16_t load_addr
Load address of the SID.
static uint16_t data_size
Size of the SID.
static int tune_count
Number of subtunes.
static int tune_current
Currently selected subtune.
static int tune_default
Default subtune.
static GtkWidget * tune_info_grid
widget references
static GtkWidget * name_widget
Name entry.
static GtkWidget * author_widget
Author entry.
static GtkWidget * copyright_widget
Copyright entry.
static GtkWidget * tune_num_widget
Tune number label.
static GtkWidget * model_widget
SID model label.
static GtkWidget * irq_widget
IRQ source label.
static GtkWidget * sync_widget
Clock speed label.
static GtkWidget * runtime_widget
Runtime label.
static GtkWidget * driver_info_widget
Driver info grid.
static unsigned int play_time
Current play time for current song.
static long * song_lengths
List of song lenghts.
static int song_lengths_count
Number of songs.
Detailed Description
GTK3 tune info widget for VSID.
Displays (sub)tune information of a PSID file
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Enumeration Type Documentation
anonymous enum
anonymous enum
Rows in the driver info grid.
Enumerator
DRV_INFO_SID_IMAGE
SID file.
DRV_INFO_DRIVER_ADDR
Address of the driver.
DRV_INFO_LOAD_ADDR
SID load address.
DRV_INFO_INIT_ADDR
SID init address.
DRV_INFO_PLAY_ADDR
SID play address.
Function Documentation
convert_to_utf8()
gchar * convert_to_utf8 (const char * s)
Convert a string from a SID header field to UTF-8.
Parameters
[in] s string from SID header, nul-terminated
Returns
UTF-8 encoded string, or the original when conversion failed
Note
the string returned needs to be freed with g_free()
Referenced by stil_widget_populate(), vsid_playlist_append_file(), vsid_tune_info_widget_set_author(), vsid_tune_info_widget_set_copyright(), and vsid_tune_info_widget_set_name().
create_driver_info_widget()
static GtkWidget * create_driver_info_widget (void) static
Create driver information widget.
Returns
GtkGrid
Referenced by vsid_tune_info_widget_create().
create_irq_widget()
static GtkWidget * create_irq_widget (void) static
Create IRQ widget.
Returns
GtkLabel
Referenced by vsid_tune_info_widget_create().
create_left_aligned_label()
static GtkWidget * create_left_aligned_label (const char * text) static
Create left aligned label, text can use HTML markup.
Parameters
[in] text label text
Returns
GtkLabel
Referenced by vsid_tune_info_widget_create().
create_model_widget()
static GtkWidget * create_model_widget (void) static
Create SID model widget.
Returns
GtkLabel
Referenced by vsid_tune_info_widget_create().
create_readonly_entry()
static GtkWidget * create_readonly_entry (void) static
Create a label to display text and allow users to copy that text.
Returns
GtkLabel
Referenced by vsid_tune_info_widget_create().
create_runtime_widget()
static GtkWidget * create_runtime_widget (void) static
Create run time widget.
Creates a widget which displays hours, minutes and seconds.
Returns
GtkLabel
Referenced by vsid_tune_info_widget_create().
create_sync_widget()
static GtkWidget * create_sync_widget (void) static
Create sync widget.
Returns
GtkLabel
Referenced by vsid_tune_info_widget_create().
create_tune_num_widget()
static GtkWidget * create_tune_num_widget (void) static
Create widget to display tune number information.
Creates label with text 'tune X of Y (Default: Z)'
Returns
GtkLabel
Referenced by vsid_tune_info_widget_create().
driver_info_set_addr()
static void driver_info_set_addr (int row, uint16_t addr) static
Set a label in the driver info grid at row to addr.
Parameters
[in] row row in the grid
[in] addr 16-bit address
Referenced by vsid_tune_info_widget_set_driver_addr(), vsid_tune_info_widget_set_init_addr(), vsid_tune_info_widget_set_load_addr(), and vsid_tune_info_widget_set_play_addr().
driver_info_set_image()
static void driver_info_set_image (void) static
Set memory range of the SID image.
Referenced by vsid_tune_info_widget_set_data_size(), and vsid_tune_info_widget_set_load_addr().
on_destroy()
static void on_destroy (GtkWidget * widget, gpointer data) static
Handler for the 'destroy' event of the widget.
Clean up memory used.
Parameters
[in] widget tune info widget (unused)
[in] data extra event data (unused)
Referenced by vsid_tune_info_widget_create().
update_irq_widget()
static void update_irq_widget (const char * irq) static
Update IRQ widget.
Parameters
[in] irq irq source
Referenced by vsid_tune_info_widget_set_irq().
update_model_widget()
static void update_model_widget (int model) static
Update SID model widget.
Parameters
[in] model SID chip model
Referenced by vsid_tune_info_widget_set_model().
update_runtime_widget()
static void update_runtime_widget (unsigned int dsec) static
Update the run time widget.
Displays the run time of the current (sub)tune in hours, minutes and seconds
Parameters
[in] dsec current run time in deciseconds
Referenced by vsid_tune_info_widget_update().
update_sync_widget()
static void update_sync_widget (int sync) static
Update sync widget.
Parameters
[in] sync sync factor ID
Referenced by vsid_tune_info_widget_set_sync().
update_tune_num_widget()
static void update_tune_num_widget (void) static
Update tune number widget.
Updates the 'X of Y (default: Z)' widget
Referenced by vsid_tune_info_widget_set_tune_count(), vsid_tune_info_widget_set_tune_current(), and vsid_tune_info_widget_set_tune_default().
vsid_tune_info_widget_create()
GtkWidget * vsid_tune_info_widget_create (void)
Create widget to show tune information.
Returns
GtkGrid
Referenced by vsid_main_widget_create().
vsid_tune_info_widget_get_song_lengths()
int vsid_tune_info_widget_get_song_lengths (long ** dest)
Retrieve songlengths.
Get the list of subtunes lengths in seconds.
Parameters
[out] dest object to store pointer to list
Returns
number of items in the list
vsid_tune_info_widget_set_author()
void vsid_tune_info_widget_set_author (const char * name)
Set author.
Parameters
[in] name author name
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_copyright()
void vsid_tune_info_widget_set_copyright (const char * name)
Set copyright info string.
Parameters
[in] name copyright string
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_data_size()
void vsid_tune_info_widget_set_data_size (uint16_t size)
Set size of SID on actual machine.
Parameters
[in] size size of SID
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_driver_addr()
void vsid_tune_info_widget_set_driver_addr (uint16_t addr)
Set driver address.
Parameters
[in] addr driver address
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_init_addr()
void vsid_tune_info_widget_set_init_addr (uint16_t addr)
Set init routine address.
Parameters
[in] addr init routine address
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_irq()
void vsid_tune_info_widget_set_irq (const char * irq)
Set IRQ source.
Parameters
[in] irq irq source string
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_load_addr()
void vsid_tune_info_widget_set_load_addr (uint16_t addr)
Set load address.
Parameters
[in] addr load address
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_model()
void vsid_tune_info_widget_set_model (int model)
Set SID model.
Parameters
[in] model model ID (0 = 6581, 1 = 8580)
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_name()
void vsid_tune_info_widget_set_name (const char * name)
Set tune name.
Parameters
[in] name tune name
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_play_addr()
void vsid_tune_info_widget_set_play_addr (uint16_t addr)
Set play routine address.
Parameters
[in] addr play routine address
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_song_lengths()
bool vsid_tune_info_widget_set_song_lengths (const char * psid)
Set song lengths for each sub-tune.
Parameters
[in] psid SID file
Returns
true if a songlengths entry was found
vsid_tune_info_widget_set_song_lengths_md5()
bool vsid_tune_info_widget_set_song_lengths_md5 (const char * digest)
Referenced by ui_vsid_window_load_psid(), and vsid_main_widget_create().
vsid_tune_info_widget_set_sync()
void vsid_tune_info_widget_set_sync (int sync)
Set sync factor.
Parameters
[in] sync sync factor (0 = 60Hz/NTSC, 1 = 50Hz/PAL)
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_time()
void vsid_tune_info_widget_set_time (unsigned int dsec)
Set current run time.
Also sets progress in current tune and handles skipping to the next tune if HVSC SLDB is found. So it probably does too much.
Parameters
[in] dsec run time in decaseconds
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_tune_count()
void vsid_tune_info_widget_set_tune_count (int num)
Set number of tunes.
Parameters
[in] num tune count
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_tune_current()
void vsid_tune_info_widget_set_tune_current (int num)
Set current tune.
Parameters
[in] num tune number
Referenced by vsid_ui_update().
vsid_tune_info_widget_set_tune_default()
void vsid_tune_info_widget_set_tune_default (int num)
Set default tune.
Parameters
[in] num tune number
Referenced by vsid_ui_update().
vsid_tune_info_widget_update()
void vsid_tune_info_widget_update (void)
Update play time based ui elements.
This function also determines if vsid should play the next subtune or play the next SID in the playlist, so it's probably doing too much or just misnamed.
Referenced by vsid_main_widget_update().
Variable Documentation
author_widget
GtkWidget* author_widget static
Author entry.
Referenced by vsid_tune_info_widget_create(), and vsid_tune_info_widget_set_author().
copyright_widget
GtkWidget* copyright_widget static
Copyright entry.
Referenced by vsid_tune_info_widget_create(), and vsid_tune_info_widget_set_copyright().
data_size
uint16_t data_size static
Size of the SID.
Referenced by driver_info_set_image(), resource_create_event_data(), resource_record_event(), resources_get_event_safe_list(), and vsid_tune_info_widget_set_data_size().
driver_info_labels
const char* driver_info_labels[] static
Initial value:
= {
    "SID image:",
    "Driver address:",
    "Load address:",
    "Init address:",
    "Play address:"
}
Labels for the driver info grid.
Referenced by create_driver_info_widget().
driver_info_widget
GtkWidget* driver_info_widget static
Driver info grid.
Referenced by driver_info_set_addr(), driver_info_set_image(), and vsid_tune_info_widget_create().
irq_widget
GtkWidget* irq_widget static
IRQ source label.
Referenced by update_irq_widget(), and vsid_tune_info_widget_create().
load_addr
uint16_t load_addr static
Load address of the SID.
Referenced by driver_info_set_image(), mon_file_load(), mon_file_verify(), and vsid_tune_info_widget_set_load_addr().
model_widget
GtkWidget* model_widget static
SID model label.
Referenced by update_model_widget(), and vsid_tune_info_widget_create().
name_widget
GtkWidget* name_widget static
Name entry.
Referenced by vsid_tune_info_widget_create(), and vsid_tune_info_widget_set_name().
play_time
unsigned int play_time static
Current play time for current song.
Referenced by vsid_tune_info_widget_set_time(), and vsid_tune_info_widget_update().
runtime_widget
GtkWidget* runtime_widget static
Runtime label.
Referenced by update_runtime_widget(), and vsid_tune_info_widget_create().
song_lengths
long* song_lengths static
List of song lenghts.
Referenced by on_destroy(), update_runtime_widget(), vsid_tune_info_widget_get_song_lengths(), vsid_tune_info_widget_set_song_lengths(), vsid_tune_info_widget_set_song_lengths_md5(), and vsid_tune_info_widget_update().
song_lengths_count
int song_lengths_count static
Number of songs.
Referenced by on_destroy(), vsid_tune_info_widget_get_song_lengths(), vsid_tune_info_widget_set_song_lengths(), and vsid_tune_info_widget_set_song_lengths_md5().
sync_widget
GtkWidget* sync_widget static
Clock speed label.
Referenced by update_sync_widget(), and vsid_tune_info_widget_create().
tune_count
int tune_count static
Number of subtunes.
Referenced by create_tune_num_widget(), update_tune_num_widget(), vsid_state_get_all_tunes_played(), and vsid_tune_info_widget_set_tune_count().
tune_current
int tune_current static
Currently selected subtune.
Referenced by create_tune_num_widget(), update_runtime_widget(), update_tune_num_widget(), vsid_tune_info_widget_set_tune_current(), and vsid_tune_info_widget_update().
tune_default
int tune_default static
Default subtune.
Referenced by create_tune_num_widget(), update_tune_num_widget(), and vsid_tune_info_widget_set_tune_default().
tune_info_grid
GtkWidget* tune_info_grid static
widget references
Main grid
Referenced by vsid_tune_info_widget_create().
tune_num_widget
GtkWidget* tune_num_widget static
Tune number label.
Referenced by update_tune_num_widget(), and vsid_tune_info_widget_create().