vsid: core/riotcore.c File Reference
riotcore.c File Reference
#include "vice.h"
#include <stdio.h>
#include "alarm.h"
#include "lib.h"
#include "log.h"
#include "monitor.h"
#include "riot.h"
#include "snapshot.h"
#include "types.h"
Macros
#define RIOT_DUMP_VER_MAJOR 0
#define RIOT_DUMP_VER_MINOR 0
Functions
static void update_irq (riot_context_t *riot_context, uint8_t new_irqfl)
void riotcore_signal (riot_context_t *riot_context, int sig, int type)
static void update_timer (riot_context_t *riot_context)
void riotcore_disable (riot_context_t *riot_context)
void riotcore_reset (riot_context_t *riot_context)
void riotcore_store (riot_context_t *riot_context, uint16_t addr, uint8_t byte)
uint8_t riotcore_read (riot_context_t *riot_context, uint16_t addr)
uint8_t riotcore_peek (riot_context_t *riot_context, uint16_t addr)
read from I/O without side effects
void riotcore_dump (riot_context_t *riot_context)
static void riotcore_int_riot (CLOCK offset, void *data)
void riotcore_setup_context (riot_context_t *riot_context)
void riotcore_init (riot_context_t *riot_context, alarm_context_t *alarm_context, unsigned int number)
void riotcore_shutdown (riot_context_t *riot_context)
int riotcore_snapshot_write_module (riot_context_t *riot_context, snapshot_t *p)
int riotcore_snapshot_read_module (riot_context_t *riot_context, snapshot_t *p)
Variables
static const int divider []
Macro Definition Documentation
RIOT_DUMP_VER_MAJOR
#define RIOT_DUMP_VER_MAJOR 0
RIOT_DUMP_VER_MINOR
#define RIOT_DUMP_VER_MINOR 0
Function Documentation
riotcore_disable()
void riotcore_disable (riot_context_t * riot_context)
riotcore_dump()
void riotcore_dump (riot_context_t * riot_context)
Referenced by drivemem_ioreg_list_get().
riotcore_init()
void riotcore_init (riot_context_t * riot_context, alarm_context_t * alarm_context, unsigned int number)
riotcore_int_riot()
static void riotcore_int_riot (CLOCK offset, void * data) static
CLOCK rclk = *(riot_context->clk_ptr) - offset;
Referenced by riotcore_init().
riotcore_peek()
uint8_t riotcore_peek (riot_context_t * riot_context, uint16_t addr)
read from I/O without side effects
Todo:
FIXME: check if this is working correctly
riotcore_read()
uint8_t riotcore_read (riot_context_t * riot_context, uint16_t addr)
riotcore_reset()
void riotcore_reset (riot_context_t * riot_context)
riotcore_setup_context()
void riotcore_setup_context (riot_context_t * riot_context)
riotcore_shutdown()
void riotcore_shutdown (riot_context_t * riot_context)
riotcore_signal()
void riotcore_signal (riot_context_t * riot_context, int sig, int type)
riotcore_snapshot_read_module()
int riotcore_snapshot_read_module (riot_context_t * riot_context, snapshot_t * p)
riotcore_snapshot_write_module()
int riotcore_snapshot_write_module (riot_context_t * riot_context, snapshot_t * p)
riotcore_store()
void riotcore_store (riot_context_t * riot_context, uint16_t addr, uint8_t byte)
Referenced by riotcore_store().
update_irq()
static void update_irq (riot_context_t * riot_context, uint8_t new_irqfl) static
Referenced by riotcore_int_riot(), riotcore_signal(), and riotcore_store().
update_timer()
static void update_timer (riot_context_t * riot_context) static
Referenced by riotcore_snapshot_write_module().
Variable Documentation
divider
const int divider[] static
Initial value:
= {
    1, 8, 64, 1024
}
Referenced by riotcore_store().