x128: arch/gtk3/widgets/sidsoundwidget.c File Reference
sidsoundwidget.c File Reference
Settings for SID emulation.
#include "vice.h"
#include <gtk/gtk.h>
#include "machine.h"
#include "mixerwidget.h"
#include "resources.h"
#include "sid.h"
#include "sidenginemodelwidget.h"
#include "sound.h"
#include "vice_gtk3.h"
#include "sidsoundwidget.h"
Macros
#define SCALE_CSS
CSS applied to scale to fix up value display.
Functions
static void update_sid_addresses_sensitivity (int count)
Set sensitivity of SID address widgets based on number of SIDs.
static void on_sid_count_changed (GtkWidget *widget, gpointer data)
Extra callback registered to the 'number of SIDs' radiogroup.
static GtkWidget * label_helper (const char *text)
static GtkWidget * create_num_sids_widget (void)
Create widget to set the number of emulated SID's.
static GtkWidget * create_extra_sid_address_widget (int sid)
Create widget for extra SID addresses.
static GtkWidget * create_sid_address_widgets (void)
Create grid with extra SID I/O address widgets.
GtkWidget * sid_sound_widget_create (void)
Create widget to control SID settings.
Variables
static int sid_addr_list_c64 []
I/O addresses for extra SID's for the C64.
static int sid_addr_list_c128 []
I/O addresses for extra SID's for the C128.
static GtkWidget * num_sids_widget
Number of extra SIDs widget.
static GtkWidget * address_widgets [8]
Reference to the extra SID address widgets.
Detailed Description
Settings for SID emulation.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Macro Definition Documentation
SCALE_CSS
#define SCALE_CSS
Value:
    "scale value {\n" \
    "  font-family: monospace;\n" \
    "  font-size: 90%;\n" \
    "}"
CSS applied to scale to fix up value display.
Fixed width font to get proper alignment of the value display of the sliders, slightly reduced font size to try to keep it roughly the same size as the sans-serif fonts used in the Adwaita theme (on Gnome Shell anyway).
Function Documentation
create_extra_sid_address_widget()
static GtkWidget * create_extra_sid_address_widget (int sid) static
Create widget for extra SID addresses.
Parameters
[in] sid extra SID number (1-7)
Returns
GtkGrid
Referenced by create_sid_address_widgets().
create_num_sids_widget()
static GtkWidget * create_num_sids_widget (void) static
Create widget to set the number of emulated SID's.
Returns
GtkGrid
Referenced by sid_sound_widget_create().
create_sid_address_widgets()
static GtkWidget * create_sid_address_widgets (void) static
Create grid with extra SID I/O address widgets.
Returns
GtkGrid
Referenced by sid_sound_widget_create().
label_helper()
static GtkWidget * label_helper (const char * text) static
Referenced by create_num_sids_widget().
on_sid_count_changed()
static void on_sid_count_changed (GtkWidget * widget, gpointer data) static
Extra callback registered to the 'number of SIDs' radiogroup.
Parameters
[in] widget widget triggering the event
[in] data unused
Referenced by create_num_sids_widget().
sid_sound_widget_create()
GtkWidget * sid_sound_widget_create (void)
Create widget to control SID settings.
Returns
GtkGrid
Referenced by settings_soundchip_widget_create().
update_sid_addresses_sensitivity()
static void update_sid_addresses_sensitivity (int count) static
Set sensitivity of SID address widgets based on number of SIDs.
Parameters
[in] count number of enabled SIDs
Referenced by on_sid_count_changed(), and sid_sound_widget_create().
Variable Documentation
address_widgets
GtkWidget* address_widgets[8] static
Reference to the extra SID address widgets.
Used to enable/disable depending on the number of SIDs active
Referenced by create_sid_address_widgets(), and update_sid_addresses_sensitivity().
num_sids_widget
GtkWidget* num_sids_widget static
Number of extra SIDs widget.
Referenced by create_num_sids_widget().
sid_addr_list_c128
int sid_addr_list_c128[] static
Initial value:
= {
     0xd420, 0xd440, 0xd460, 0xd480, 0xd4a0, 0xd4c0, 0xd4e0,
    0xd700, 0xd720, 0xd740, 0xd760, 0xd780, 0xd7a0, 0xd7c0, 0xd7e0,
    0xde00, 0xde20, 0xde40, 0xde60, 0xde80, 0xdea0, 0xdec0, 0xdee0,
    0xdf00, 0xdf20, 0xdf40, 0xdf60, 0xdf80, 0xdfa0, 0xdfc0, 0xdfe0,
    -1
}
I/O addresses for extra SID's for the C128.
Referenced by create_extra_sid_address_widget().
sid_addr_list_c64
int sid_addr_list_c64[] static
Initial value:
= {
     0xd420, 0xd440, 0xd460, 0xd480, 0xd4a0, 0xd4c0, 0xd4e0,
    0xd500, 0xd520, 0xd540, 0xd560, 0xd580, 0xd5a0, 0xd5c0, 0xd5e0,
    0xd600, 0xd620, 0xd640, 0xd660, 0xd680, 0xd6a0, 0xd6c0, 0xd6e0,
    0xd700, 0xd720, 0xd740, 0xd760, 0xd780, 0xd7a0, 0xd7c0, 0xd7e0,
    0xde00, 0xde20, 0xde40, 0xde60, 0xde80, 0xdea0, 0xdec0, 0xdee0,
    0xdf00, 0xdf20, 0xdf40, 0xdf60, 0xdf80, 0xdfa0, 0xdfc0, 0xdfe0,
    -1
}
I/O addresses for extra SID's for the C64.
Referenced by create_extra_sid_address_widget().