vsid: arch/gtk3/widgets/base/carthelpers.h File Reference
carthelpers.h File Reference
Cartridge helper functions - header.
#include <gtk/gtk.h>
Functions
GtkWidget * carthelpers_create_enable_check_button (const char *cart_name, int cart_id)
Create a check button to enable/disable a cartridge.
Detailed Description
Cartridge helper functions - header.
Author
Bas Wassink b.was.nosp@m.sink.nosp@m.@zigg.nosp@m.o.nl
Function Documentation
carthelpers_create_enable_check_button()
GtkWidget * carthelpers_create_enable_check_button (const char * cart_name, int cart_id)
Create a check button to enable/disable a cartridge.
Creates a check button that enables/disables a cartridge. The cart_name argument is copied to allow for debug/error messages to mention the cart by name, rather than by ID. The name is freed when the check button is destroyed.
What the widget basically does is call cartridge_enable(cart_id) or cartridge_disable(cart_id), using cartridge_type_enabled(cart_id) to set the initial state of the widget. But since all Gtk3 widgets are currently linked into a big lib and vsid doesn't like that, we use some function pointer magic is used.
Parameters
[in] cart_name cartridge name (see cartridge.h)
[in] cart_id cartridge ID (see cartridge.h)
Returns
GtkCheckButton
Referenced by settings_cpm_widget_create(), settings_dqbb_widget_create(), settings_ds12c887_widget_create(), settings_expert_widget_create(), settings_georam_widget_create(), settings_isepic_widget_create(), settings_magicvoice_widget_create(), settings_reu_widget_create(), settings_sfxsoundexpander_widget_create(), and settings_sfxsoundsampler_widget_create().