x128: gcr.h File Reference
gcr.h File Reference
#include "types.h"
#include "cbmdos.h"
Data Structures
struct disk_track_s
struct gcr_s
struct gcr_header_s
Macros
#define NUM_MAX_BYTES_TRACK 7928
Number of bytes in one raw track.
#define NUM_MAX_MEM_BYTES_TRACK 65536
#define MAX_GCR_TRACKS 168
Number of tracks we emulate.
#define SECTOR_GCR_SIZE_WITH_HEADER 335
Typedefs
typedef struct disk_track_s disk_track_t
typedef struct gcr_s gcr_t
typedef struct gcr_header_s gcr_header_t
Functions
void gcr_convert_sector_to_GCR (const uint8_t *buffer, uint8_t *ptr, const gcr_header_t *header, int gap, int sync, enum fdc_err_e error_code)
enum fdc_err_e gcr_read_sector (const disk_track_t *raw, uint8_t *data, uint8_t sector)
enum fdc_err_e gcr_write_sector (disk_track_t *raw, const uint8_t *data, uint8_t sector)
gcr_t * gcr_create_image (void)
void gcr_destroy_image (gcr_t *gcr)
Macro Definition Documentation
MAX_GCR_TRACKS
#define MAX_GCR_TRACKS 168
Number of tracks we emulate.
84 for 1541, 168 for 1571
NUM_MAX_BYTES_TRACK
#define NUM_MAX_BYTES_TRACK 7928
Number of bytes in one raw track.
For usage with D64/D71
NUM_MAX_MEM_BYTES_TRACK
#define NUM_MAX_MEM_BYTES_TRACK 65536
SECTOR_GCR_SIZE_WITH_HEADER
#define SECTOR_GCR_SIZE_WITH_HEADER 335
Typedef Documentation
disk_track_t
typedef struct disk_track_s disk_track_t
gcr_header_t
typedef struct gcr_header_s gcr_header_t
gcr_t
typedef struct gcr_s gcr_t
Function Documentation
gcr_convert_sector_to_GCR()
void gcr_convert_sector_to_GCR (const uint8_t * buffer, uint8_t * ptr, const gcr_header_t * header, int gap, int sync, enum fdc_err_e error_code)
gcr_create_image()
gcr_t * gcr_create_image (void)
Referenced by drive_init().
gcr_destroy_image()
void gcr_destroy_image (gcr_t * gcr)
Referenced by drive_shutdown().
gcr_read_sector()
enum fdc_err_e gcr_read_sector (const disk_track_t * raw, uint8_t * data, uint8_t sector)
Referenced by fsimage_dxx_read_sector(), fsimage_dxx_write_half_track(), fsimage_gcr_read_sector(), and fsimage_p64_read_sector().
gcr_write_sector()
enum fdc_err_e gcr_write_sector (disk_track_t * raw, const uint8_t * data, uint8_t sector)
Referenced by fsimage_dxx_write_sector(), fsimage_gcr_write_sector(), and fsimage_p64_write_sector().