vsid: serial/fsdrive.c File Reference
fsdrive.c File Reference
#include "vice.h"
#include <stdio.h>
#include <string.h>
#include "snapshot.h"
#include "attach.h"
#include "fsdrive.h"
#include "log.h"
#include "serial.h"
#include "types.h"
Macros
#define DBG(_x_)
#define DELAYEDCLOSE
#define SNAP_MAJOR 0
#define SNAP_MINOR 0
Functions
static uint8_t serialcommand (unsigned int device, uint8_t secondary)
Handle Serial Bus Commands under Attention.
void fsdrive_open (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void fsdrive_close (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void fsdrive_listentalk (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void fsdrive_unlisten (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void fsdrive_untalk (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void fsdrive_write (unsigned int device, uint8_t secondary, uint8_t data, void(*st_func)(uint8_t))
uint8_t fsdrive_read (unsigned int device, uint8_t secondary, void(*st_func)(uint8_t))
void fsdrive_reset (void)
void fsdrive_init (void)
void fsdrive_snapshot_prepare (void)
int fsdrive_snapshot_write_module (struct snapshot_s *s)
int fsdrive_snapshot_read_module (struct snapshot_s *s)
Variables
static log_t fsdrive_log = ((log_t)-1)
uint8_t SerialBuffer [255+1]
int SerialPtr
static char snap_module_name [] = "FSDRIVE"
Macro Definition Documentation
DBG
#define DBG (_x_)
DELAYEDCLOSE
#define DELAYEDCLOSE
SNAP_MAJOR
#define SNAP_MAJOR 0
SNAP_MINOR
#define SNAP_MINOR 0
Function Documentation
fsdrive_close()
void fsdrive_close (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_close().
fsdrive_init()
void fsdrive_init (void)
Referenced by serial_iec_bus_init().
fsdrive_listentalk()
void fsdrive_listentalk (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_listen(), and serial_iec_bus_talk().
fsdrive_open()
void fsdrive_open (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_open().
fsdrive_read()
uint8_t fsdrive_read (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_read().
fsdrive_reset()
void fsdrive_reset (void)
Referenced by serial_iec_bus_reset().
fsdrive_snapshot_prepare()
void fsdrive_snapshot_prepare (void)
fsdrive_snapshot_read_module()
int fsdrive_snapshot_read_module (struct snapshot_s * s)
Referenced by c64_snapshot_read().
fsdrive_snapshot_write_module()
int fsdrive_snapshot_write_module (struct snapshot_s * s)
Referenced by c64_snapshot_write().
fsdrive_unlisten()
void fsdrive_unlisten (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_unlisten().
fsdrive_untalk()
void fsdrive_untalk (unsigned int device, uint8_t secondary, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_untalk().
fsdrive_write()
void fsdrive_write (unsigned int device, uint8_t secondary, uint8_t data, void(*)(uint8_t) st_func)
Referenced by serial_iec_bus_write().
serialcommand()
static uint8_t serialcommand (unsigned int device, uint8_t secondary) static
Handle Serial Bus Commands under Attention.
Referenced by fsdrive_close(), fsdrive_listentalk(), and fsdrive_unlisten().
Variable Documentation
fsdrive_log
log_t fsdrive_log = ((log_t)-1) static
Referenced by fsdrive_init(), fsdrive_snapshot_read_module(), and serialcommand().
SerialBuffer
uint8_t SerialBuffer[255+1]
Referenced by fsdrive_snapshot_read_module(), fsdrive_snapshot_write_module(), fsdrive_write(), and serialcommand().
SerialPtr
int SerialPtr
Referenced by fsdrive_snapshot_read_module(), fsdrive_snapshot_write_module(), fsdrive_write(), and serialcommand().
snap_module_name
char snap_module_name[] = "FSDRIVE" static
Referenced by fsdrive_snapshot_read_module(), and fsdrive_snapshot_write_module().